### PR TITLE
Upgrade to Lucene 9.10.0.

### PR DESCRIPTION
**Pull request by jpountz**
This is currently a draft as Lucene 9.10.0 is still under vote.

### CODE REVIEW

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Comment by ChrisHegarty** [comment]
@elasticmachine update branch

**Review by ChrisHegarty — APPROVED** [review]
LGTM

**Comment by ChrisHegarty** [comment]
@elasticmachine update branch

**Comment by ChrisHegarty** [comment]
@elasticmachine update branch

**Comment by ChrisHegarty** [comment]
@elasticmachine update branch

**Review by benwtrent — APPROVED** [review]

**Review by tteofili — APPROVED** [review]

**Review by javanna — APPROVED** [review]
LGTM, I double checked the collector manager bits and they look fine.

**Pull request merged**
