### PR TITLE
Better logging when EsThreadPoolExecutor throws unexpected exceptions

### PR DESCRIPTION
**Pull request by tlrx**
We recently had issues with `EsThreadPoolExecutor` throwing unexpected exceptions (in our case an `AccessControlException`) before the `Runnable` or `AbstractRunnable` has been submitted for execution. In the case of `AbstractRunnable` the task is not rejected and it causes some resources to leak.

This pull request catches unexpected exceptions thrown when calling the `EsThreadPoolExecutor#execute()` method and logs a message. It also assert that this situation should never happen, and if that's the case an `AssertionError` is thrown in tests.

### CODE REVIEW

**Review by DaveCTurner — COMMENTED** [review]
Looks good, a couple of thoughts:

1. Should we always do this, or only if `command instanceof AbstractRunnable`? If it's not `AbstractRunnable` then we expect the caller to handle exceptions anyway. Not sure of the exact guarantees on `super.execute()` here.

2. Could we emit the log message first so we can see the stack trace if this fails? Also could we include `command` in the message? Many commands have useful-ish string representations.

**Comment by DaveCTurner** [comment]
3. If this were to happen in production, and it's an `AbstractRunnable`, I think the safest thing to do is call `onRejection()` rather than re-throwing the exception. At least that way it's on the expected thread (vs `onFailure()` which should be on the executor), and `onRejection()` is more likely to release resources properly.

**Comment by rjernst** [comment]
I looked at this code recently as I also thought there was a missing exception handling here. However, upon looking closer, I saw that AbstractRunnable already handles exceptions within its own `run()` method. If we want to ensure these are all logged, perhaps we should log there instead? Additionally, I wonder if the `EsRejectedExecutionException` handling could be moved to there.

As far as rethrowing, after the executor, it will go to the default exception handler, which means the node will crash. Perhaps we should be stopping the exception here (ie only implicitly allowing Error through which can stop the node, like OOM). A NPE should never cause a node to crash.

**Comment by tlrx** [comment]
> I looked at this code recently as I also thought there was a missing exception handling here. However, upon looking closer, I saw that AbstractRunnable already handles exceptions within its own `run()` method. If we want to ensure these are all logged, perhaps we should log there instead? 

I don't think it is worth to log all exceptions thrown from the `doRun()` method. If needed, log can be done by the AbstractRunnable itself when it makes sense. The point in this pull request is to log exceptions that are not handled by the runnables themselves including the ones that can be thrown before the task is submitted/added to he queue.

> Additionally, I wonder if the `EsRejectedExecutionException` handling could be moved to there.

Sorry if I'm missing something but at the time the method `run()` is called the runnable has been added to the thread pool queue and picked up by a worker - how could it be rejected from there?

> As far as rethrowing, after the executor, it will go to the default exception handler, which means the node will crash. Perhaps we should be stopping the exception here (ie only implicitly allowing Error through which can stop the node, like OOM). A NPE should never cause a node to crash.

I had the impression that such exceptions were caught by `ElasticsearchUncaughtExceptionHandler` which makes the difference between Errors and non fatal exceptions

**Comment by rjernst** [comment]
> The point in this pull request is to log exceptions that are not handled by the runnables themselves including the ones that can be thrown before the task is submitted/added to he queue.

I don't think this code handles those cases *exclusively*. In the case of exceptions, the runnable has already decided to propagate the exception by rethrowing.

> Sorry if I'm missing something but at the time the method run() is called the runnable has been added to the thread pool queue and picked up by a worker - how could it be rejected from there?

You are right, I misinterpreted that. The rejection handling must stay in the executor.

> I had the impression that such exceptions were caught by ElasticsearchUncaughtExceptionHandler which makes the difference between Errors and non fatal exceptions

Yes, that is true. But the uncaught handler also logs those exceptions. Shouldn't it already be logging what you are trying to log here?

**Comment by ChrisHegarty** [comment]
The change seems largely benign, apart from the addition of the stop-in-your-tracks assertion - which may be ok.  The description mentions an access control exception, but I don't see how that is possible, unless a transient issue was observed during development (which never got pushed) ? If a stack trace was handy, that could be informative, otherwise I'm not quite sure what problem this change is trying to address.

**Comment by tlrx** [comment]
@ChrisHegarty you can find a bit more context and a stack trace in #85239.

**Comment by DaveCTurner** [comment]
IMO the benefit of this change is to formalise and document the assumption that this method never throws anything if the argument is an `AbstractRunnable`. We make use of this assumption fairly broadly, and IMO it's much better to rely on that than to require every caller to implement exception handling in the `AbstractRunnable` and then to have to add a separate `try...catch` around the `execute()` method too.

It's important for us to find out ASAP if there are any other ways that this might throw something back to the caller, hence the `assert false`.

**Comment by rjernst** [comment]
This PR looks fine on its own, but I'm still not sure it would have surfaced the underlying AccessControlException, which afaiu happened while running a script. For that to propagate, we need to teach painless about SecurityException so it can not wrap those, since they are not user problems but internal ES problems that should be propagated up the callstack. I'm working on that change to painless separately.

**Comment by rjernst** [comment]
Also, I still don't understand what conditions this would surface additional log messages, since the exception is already rethrown and should be caught by the uncaughtexcpetionhandler, which logs at error level. @tlrx Do you have a scenario where an exception is not logged by the uncaughtexcpetionhandler and must be done so here?

**Comment by tlrx** [comment]
> @tlrx Do you have a scenario where an exception is not logged by the uncaughtexcpetionhandler and must be done so here?

No I don't. In the case I identified the exception is caught and returned to the client, without logging, and therefore is not logged by the uncaught exception handler. I wish we had a bullet proof exception propagation everywhere but the issue we had in  #85239 is a good example of how hard it is to correctly handle and propagate unexpected exceptions.

**Comment by tlrx** [comment]
I've updated the code to log, assert and call `onRejection()` for `AbstractRunnable` only. Please let me know if you agree with this change or not, thanks!

**Review by fcofdez — APPROVED** [review]
LGTM, this should surface other unhandled exceptions (if there are any). But since there's some concerns around this change, I would wait for another reviewer approval. 👍

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Review by ChrisHegarty — APPROVED** [review]

**Comment by tlrx** [comment]
Thanks everybody!

**Comment by joegallo** [comment]
I tweaked the version labels because this didn't land in time for 7.17.2 BC1, and I'm not sure there are going to be any other BCs (but feel free to change that back if I did the wrong thing).

**Pull request merged**
