### PR TITLE
Fix malformed query generation

### PR DESCRIPTION
**Pull request by alexclare**
Fix for issue #12327

### CODE REVIEW

**Comment by alexclare** [comment]
There are a few other places where this can be fixed: changing `doXContent` in the builder to avoid including `modifier` in the first place, or adding a conditional to the parsing logic. Not sure which you folks would prefer!

**Comment by clintongormley** [comment]
Hi @alexclare 

Thanks for the PR - any chance you could add a test for this please?

**Comment by alexclare** [comment]
Cool, here's that test.

**Comment by clintongormley** [comment]
@brwe could you take a look please?

**Comment by brwe** [comment]
> Not sure which you folks would prefer!

I think this is the right place.

**Comment by clintongormley** [comment]
thanks @alexclare

**Pull request merged**
