### PR TITLE
Collapse all transport versions between 8.11 and 8.12 into a constant for 8.12

### PR DESCRIPTION
**Pull request by thecoop**
Collapse all transport versions between 8.11.0 and 8.12.0 into a single constant

### CODE REVIEW

**Review by ldematte — APPROVED** [review]
LGTM

**Comment by thecoop** [comment]
@maxhniebergall This gets rid of the version mess with ELSER model serialization - could you check the simplified logic is correct, and if there's anywhere else that needs to be changed?

**Review by maxhniebergall — APPROVED** [review]
LGTM. I don't think there are any other places that need to be changed. Thanks!

**Comment by thecoop** [comment]
@elasticsearchmachine update branch

**Comment by thecoop** [comment]
@elasticmachine update branch

**Pull request merged**
