### PR TITLE
Shrink api should ignore templates

### PR DESCRIPTION
**Pull request by fred84**
Aliases, mapping, customs and settings from templates should be ignored when shrinking index #25035

### CODE REVIEW

**Comment by jasontedor** [comment]
I appreciate the work that you did here @fred84 but I think that this change is way too big to solely fix #25035. It looks instead like there's a big refactoring included here too. I would prefer that the two be separated, can we focus on #25035 only first?

**Comment by fred84** [comment]
@jasontedor I think it is still reasonable to extract anonymous class to inner class without refactoring so I will be able to keep unit test for IndexCreationTask. Do you agree?

**Comment by jasontedor** [comment]
@fred84 A refactoring to make this unit testable is of course very much welcome but it being so large and mixing it with a bug fix is what I'm concerned with. Because the bug fix here is not tricky, I would lean towards fixing the bug first, and then refactoring. If you want to do it the other way, I'm fine with that, but let's do it in manageable bite-size chunks. 😄

**Comment by fred84** [comment]
@jasontedor Got it :-) I will make new pull request with bug fix only and keep this one for future discussion.

**Comment by fred84** [comment]
@jasontedor Fix only PR: #25380

**Comment by fred84** [comment]
@jasontedor As fix #25380 is merged I'll create another PR with anonymous class converted to inner and with unit test.

**Comment by jasontedor** [comment]
Thanks; since you're going to open a new pull request I will close this one.

**Pull request closed without merging**
