### PR TITLE
Add debug logging during ILM's check-rollover-ready step

### PR DESCRIPTION
**Pull request by joegallo**
Adds some simple logging during ILM's `check-rollover-ready` step that specifies what conditions were checked and their status, it also logs whether the index was or was not ready for rollover according to those conditions.

Here's an example:

```
[2023-10-13T16:10:08,282][DEBUG][o.e.x.c.i.WaitForRolloverReadyStep] [runTask-0] index [.ds-.slm-history-5-2023.10.13-000001] is not ready for rollover, conditions: [{[max_age: 30d]=false, [max_primary_shard_docs: 200000000]=false, [min_docs: 1]=true, [max_primary_shard_size: 50gb]=false}]
[2023-10-13T16:10:08,282][DEBUG][o.e.x.c.i.WaitForRolloverReadyStep] [runTask-0] index [.ds-ilm-history-5-2023.10.13-000001] is not ready for rollover, conditions: [{[max_age: 30d]=false, [max_primary_shard_docs: 200000000]=false, [min_docs: 1]=true, [max_primary_shard_size: 50gb]=false}]
[2023-10-13T16:10:08,285][INFO][o.e.x.c.i.WaitForRolloverReadyStep] [runTask-0] index [test-index-000001] is ready for rollover, conditions: [{[max_age: 1s]=true, [min_docs: 1]=true, [max_primary_shard_docs: 200000000]=false}]
```

~I admit that debug logging is not ideal -- we don't typically have debug logging enabled, so the expected case is that these logs will not be seen. However, it can be enabled if something seems off with the rollover logic, so it's a switch that's available to us, and I think it'll be good to have. I hesitate to add it at a higher level of logging, though, because we'll be logging this every `indices.lifecycle.poll_interval` (10 minutes by default) and there can be be a lot of indices that are waiting for rollover at any given point. Seems too noisy to be `INFO`.~ (edit: see next paragraph)

Since an index can be evaluated for rollover every `ilm.poll_interval`, the "is not ready for rollover" message is logged as `DEBUG` in order to not fill the cluster logs with a lot of low-value noise. However, since an index will become "ready for rollover" only once, that message is logged at `INFO`.

This came up in a couple of support tickets, and I'm finally turning my intention into action.

### CODE REVIEW

**Review by gmarouli — APPROVED** [review]
LGTM, thank you @joegallo for acting on this! 

One last thought about this. Do you know if the support cases are mostly about indices not being ready or being ready?

Thinking out loud. Should we log on `INFO` when the conditions are met, and `DEBUG` when they are not. 
- We already log the ILM transitions, so maybe it is not that noisy to log this when the index is ready.
- When the index is not ready and it's stuck, probably we will have the opportunity to enable DEBUG to get more information.

I do think that most cases are about indices that are not rolling over so I prefer your current approach. But I thought to double check.

**Comment by joegallo** [comment]
> Do you know if the support cases are mostly about indices not being ready or being ready?

I've seen both. Very small values of N, though, so not scientific.

> When the index is not ready and it's stuck, probably we will have the opportunity to enable DEBUG to get more information.

++, we're definitely aligned on DEBUG logging in the not-ready-to-rollover case (a 30d rollover max_age will log that it isn't ready to rollover every 10 minutes for 30d -- too much!).

> We already log the ILM transitions, so maybe it is not that noisy to log this when the index is ready.

Yeah, here's what it would look like in a contrived case I just ran:

```
joegallo@simulacron:~/Code/elastic/elasticsearch $ cat build/testclusters/runTask-0/logs/es.out | grep test-index-000001 | grep -E '(WaitForRolloverReadyStep|IndexLifecycle)' | grep -v shrink | grep INFO | grep rollover
[2023-10-19T10:25:35,235][INFO ][o.e.x.i.IndexLifecycleTransition] [runTask-0] moving index [test-index-000001] from [{"phase":"hot","action":"unfollow","name":"branch-check-unfollow-prerequisites"}] to [{"phase":"hot","action":"rollover","name":"check-rollover-ready"}] in policy [test-policy]
[2023-10-19T10:26:19,006][INFO ][o.e.x.c.i.WaitForRolloverReadyStep] [runTask-0] index [test-index-000001] is ready for rollover, conditionStatus: [{[max_age: 1s]=true, [min_docs: 1]=true, [max_primary_shard_docs: 200000000]=false}]
[2023-10-19T10:26:19,009][INFO ][o.e.x.i.IndexLifecycleTransition] [runTask-0] moving index [test-index-000001] from [{"phase":"hot","action":"rollover","name":"check-rollover-ready"}] to [{"phase":"hot","action":"rollover","name":"attempt-rollover"}] in policy [test-policy]
[2023-10-19T10:26:19,230][INFO ][o.e.x.i.IndexLifecycleTransition] [runTask-0] moving index [test-index-000001] from [{"phase":"hot","action":"rollover","name":"attempt-rollover"}] to [{"phase":"hot","action":"rollover","name":"wait-for-active-shards"}] in policy [test-policy]
[2023-10-19T10:26:19,443][INFO ][o.e.x.i.IndexLifecycleTransition] [runTask-0] moving index [test-index-000001] from [{"phase":"hot","action":"rollover","name":"wait-for-active-shards"}] to [{"phase":"hot","action":"rollover","name":"update-rollover-lifecycle-date"}] in policy [test-policy]
[2023-10-19T10:26:19,445][INFO ][o.e.x.i.IndexLifecycleTransition] [runTask-0] moving index [test-index-000001] from [{"phase":"hot","action":"rollover","name":"update-rollover-lifecycle-date"}] to [{"phase":"hot","action":"rollover","name":"set-indexing-complete"}] in policy [test-policy]
[2023-10-19T10:26:19,537][INFO ][o.e.x.i.IndexLifecycleTransition] [runTask-0] moving index [test-index-000001] from [{"phase":"hot","action":"rollover","name":"set-indexing-complete"}] to [{"phase":"hot","action":"complete","name":"complete"}] in policy [test-policy]
```

**Comment by joegallo** [comment]
I changed the messages `conditionStatus:` seemed right for a `DEBUG` log, but I thought `conditions:` was more appropriate if we're logging at `INFO`.

**Comment by gmarouli** [comment]
Thanks for adding this @joegallo, this is going to be so helpful!

**Pull request merged**
