### PR TITLE
Slow log must use separate underlying logger for each index

### LINKED ISSUE #42432: index slowlog settings override other indices settings
**Elasticsearch version** : Tested with 6.6.1 and master

**Description of the problem including expected versus actual behavior**:
Slowlog settings are supposed to be per index. However, setting the slowlog settings for an index, override the respective settings in all other indices, even when these other settings have been previously configured. 

**Steps to reproduce**:

1. Create index `test_1` and set `index.search.slowlog.level: warn` and `index.search.slowlog.threshold.query.trace` to 0. 
```
curl -X PUT  -H 'Content-Type: application/json' 'http://localhost:9200/test_1/_settings' -d '{"settings": {"index.search.slowlog.level": "warn", "index.search.slowlog.threshold.query.trace": 0}}'
```

Get the settings to verify it is set correctly

```
curl -uelastic:password -X GET 'http://localhost:9200/test_1/_settings'
```

should return 

```
...
"test_1" : {
    "settings" : {
      "index" : {
        "search" : {
          "slowlog" : {
            "level" : "warn",
            "threshold" : {
              "query" : {
                "trace" : "0"
              }
            }
          }
        },
...
```

2. Make a few searches
```
curl -X GET 'http://localhost:9200/test_1/_search'
```

and verify nothing is printed in the `*.index_search_slowlog.log`

3. Create index `test_2` and set `index.search.slowlog.level: trace` and `index.search.slowlog.threshold.query.trace` to 0. 
```
curl -X PUT  -H 'Content-Type: application/json' 'http://localhost:9200/test_2/_settings' -d '{"settings": {"index.search.slowlog.level": "warn", "index.search.slowlog.threshold.query.trace": 0}}'
```

Get the settings to verify it is set correctly

```
curl -uelastic:password -X GET 'http://localhost:9200/test_2/_settings'
```

should return 

```
...
"test_2" : {
    "settings" : {
      "index" : {
        "search" : {
          "slowlog" : {
            "level" : "trace",
            "threshold" : {
              "query" : {
                "trace" : "0"
              }
            }
          }
        },
...
```

Verify also that the settings for `test_1` have **not** been changed ( at least that's reported ): 
```
curl -uelastic:password -X GET 'http://localhost:9200/test_1/_settings'
```

should still  return 

```
...
"test_1" : {
    "settings" : {
      "index" : {
        "search" : {
          "slowlog" : {
            "level" : "warn",
            "threshold" : {
              "query" : {
                "trace" : "0"
              }
            }
          }
        },
...
```

4. Make a search in `test_1` again
```
curl -X GET 'http://localhost:9200/test_1/_search'
```

Observe log lines such as 

```
[2019-05-23T13:27:38,633][TRACE][i.s.s.query              ] [node-0] [test_1][0] took[218.5micros], took_millis[0], total_hits[0 hits], types[], stats[], search_type[QUERY_THEN_FETCH], total_shards[1], source[{}], id[],
```

 in the `*.index_search_slowlog.log`

### PR DESCRIPTION
**Pull request by alexshadow007**
Closes #42432

### CODE REVIEW

**Comment by pgomulka** [comment]
@alexshadow007 thank you for looking into this. I think your fix should work.
However we certainly miss testing around this. Do you think you could add appropriate unit tests to reproduce this?

**Review by pgomulka — CHANGES_REQUESTED** [review]
@alexshadow007 thank you for looking into this. I think your fix should work.
However we certainly miss testing around this. Do you think you could add appropriate unit tests to reproduce this?

**Comment by alexshadow007** [comment]
@pgomulka I added test for SearchSlowLog, is it fine?
But i have problem with testing of IndexSlowLog.
To call IndexingSlowLog.postIndex i need Engine.IndexResult with correct took time, but took time has package private visibility - so i can't set it from test. Any advices?

**Comment by pgomulka** [comment]
@alexshadow007 added test is really good! thank you for this
in regards to `IndexSLowLogTests` how about we simplify the test case there? It is after all only a change about setting LogLevel. I was thinking of something like this
```
    public void testLevelSettingMultipleIndices() {
        IndexSettings infoSettings = new IndexSettings(
            newIndexMeta("index-1-info", Settings.builder()
                                                 .put(IndexMetaData.SETTING_INDEX_UUID, UUIDs.randomBase64UUID())
                                                 .put(IndexMetaData.SETTING_VERSION_CREATED, Version.CURRENT)
                                                 .put(SearchSlowLog.INDEX_SEARCH_SLOWLOG_THRESHOLD_FETCH_INFO_SETTING.getKey(), "0")
                                                 .put(IndexingSlowLog.INDEX_INDEXING_SLOWLOG_LEVEL_SETTING.getKey(), SlowLogLevel.INFO)
                                                 .build()), Settings.EMPTY);
        IndexingSlowLog infoLog = new IndexingSlowLog(infoSettings);
        assertEquals(infoLog.getLevel(), SlowLogLevel.INFO);


        IndexSettings debugSettings = new IndexSettings(
            newIndexMeta("index-2-debug", Settings.builder()
                                                  .put(IndexMetaData.SETTING_INDEX_UUID, UUIDs.randomBase64UUID())
                                                  .put(IndexMetaData.SETTING_VERSION_CREATED, Version.CURRENT)
                                                  .put(SearchSlowLog.INDEX_SEARCH_SLOWLOG_THRESHOLD_QUERY_DEBUG_SETTING.getKey(), "0")
                                                  .put(IndexingSlowLog.INDEX_INDEXING_SLOWLOG_LEVEL_SETTING.getKey(), SlowLogLevel.DEBUG)
                                                  .build()), Settings.EMPTY);
        IndexingSlowLog debugLog = new IndexingSlowLog(debugSettings);
        assertEquals(debugLog.getLevel(), SlowLogLevel.DEBUG);

        //assert log level is preserved
        assertEquals(infoLog.getLevel(), SlowLogLevel.INFO);
    }
```
Or maybe we could try that approach in `SearchSlowLogTests`. What do you think?

**Comment by alexshadow007** [comment]
@pgomulka 
Test case provided by you doesn't verify this bug. Because problem was in underlying logger - log level of slow log instance was right, but log level of underlying log4 logger was different (because instance of log4j logger was shared between all instances of slow logs). I can add test case where i verify log level of underlying logger by it's name.

```
        String uuid = UUIDs.randomBase64UUID();
        IndexSettings infoSettings = new IndexSettings(
            newIndexMeta("index-1-info", Settings.builder()
                                                 .put(IndexMetaData.SETTING_INDEX_UUID, uuid )
                                                 .put(IndexMetaData.SETTING_VERSION_CREATED, Version.CURRENT)
                                                 .put(SearchSlowLog.INDEX_SEARCH_SLOWLOG_THRESHOLD_FETCH_INFO_SETTING.getKey(), "0")
                                                 .put(IndexingSlowLog.INDEX_INDEXING_SLOWLOG_LEVEL_SETTING.getKey(), SlowLogLevel.INFO)
                                                 .build()), Settings.EMPTY);
        IndexingSlowLog infoLog = new IndexingSlowLog(infoSettings);
        assertEquals(LogManager.getLogger("index.search.slowlog.query." + uuid).getLevel, Level.INFO);
```

**Comment by pgomulka** [comment]
@alexshadow007 you are right. I was thinking that getLevel would be changed to something to return the level of the underlying logger
```
 SlowLogLevel getLevel() {
        return SlowLogLevel.parse(indexLogger.getLevel().name());
    }
```
I am not sure we really need that `level` variable inside SlowLoggers

**Comment by alexshadow007** [comment]
@pgomulka Yes, i think it is not bad idea. I will do it and add test case.

**Comment by alexshadow007** [comment]
@pgomulka Done

**Comment by pgomulka** [comment]
ok to test

**Comment by pgomulka** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample

**Comment by pgomulka** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by pgomulka** [comment]
@elasticmachine run elasticsearch-ci/2

**Review by pgomulka — APPROVED** [review]

**Comment by pgomulka** [comment]
@alexshadow007 there are some test failures in CI, but they seem unrelated. I will try to confirm with the team the reason it is failing (I can't reproduce it).
But once again I wanted to thank you this PR, the change looks great.

**Comment by pgomulka** [comment]
@elasticmachine update branch

**Comment by pgomulka** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample

**Comment by pgomulka** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample-matrix

**Pull request merged**
