### PR TITLE
Fixing typo in spelling of rollover

### PR DESCRIPTION
**Pull request by himanshuB2**
Fixed typo

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by nik9000** [comment]
Looks good to me. @himanshubhandoh, can you sign the CLA so I can merge it? I can't merge anything without the CLA, even a typo fix!

**Comment by nik9000** [comment]
@himanshubhandoh the CLA checker seems happy now. I'll merge and cherry-pick as appropriate.

**Comment by nik9000** [comment]
Thanks for fixing the typo @himanshubhandoh! I've merged and cherry-picked as appropriate. The docs should rebuild in a half hour or so and your typo will be fixed.

**Comment by himanshubhandoh** [comment]
Thanks @nik9000! Sorry, was out, and couldn't respond sooner. Thanks for the super quick response and for merging this.

**Comment by nik9000** [comment]
Thanks for fixing it! Sometimes we're not too quick with docs changes. I
was sweeping through a big list last night.

**Pull request merged**
