### PR TITLE
[Fleet] Support for Profiling symbolization

### PR DESCRIPTION
**Pull request by cauemarcondes**
- It adds the profiling index pattern profiling-* to the fleet server service privileges.
- And adds profiling-* to kibana system role privileges.

### CODE REVIEW

**Review by jen-huang — APPROVED** [review]
Changes to the role and service account privileges LGTM.

Pending successful CI build

**Review by slobodanadamovic — APPROVED** [review]
Looks good from `es-security` perspective, but you still need approval from @elastic/kibana-security team as this change affects `kibana_system` role.

**Comment by danielmitterdorfer** [comment]
Jenkins run elasticsearch-ci/part-1

**Comment by danielmitterdorfer** [comment]
Jenkins run elasticsearch-ci/part1-fips

**Comment by danielmitterdorfer** [comment]
Jenkins run elasticsearch-ci/part-1-fips

**Review by thomheymann — APPROVED** [review]
LGTM!

**Comment by danielmitterdorfer** [comment]
Thank you all for your reviews!

**Pull request merged**
