### PR TITLE
Docs: Fix missing example script quote

### PR DESCRIPTION
**Pull request by aptxx**
it seems lost right quote

### CODE REVIEW

**Review by cbuescher — COMMENTED** [review]
@aptxx thanks for noting this, look right to me. Ideally this should have been caught by the test. I'm currently looking into why this is not causing an error. Maybe it makes sense to add an assertion to the response that at least checks there are no failures. I will check if this would have detected this. Maybe you can add it to this PR in that case.

**Comment by cbuescher** [comment]
@aptxx this is definitely an error which we should correct. Would you mind signing the CLA so I can merge this change?

**Comment by aptxx** [comment]
@cbuescher Done. I found there are many test case without exception handling in the file. Did them run as expected? I will have a little check if it's need

**Comment by cbuescher** [comment]
@aptxx Yes, the problem with ReindexDocumentationIT seems to be that none of the test methods is actually run at the moment. We rely on test methods starting with "test..." in out test infrastructure, so I think none of them are run at the moment (which might be intentional, the Documentation tests are mainly there to include code snippets from and should mostly allow us catching compile errors in the java syntax). I think we should run those tests but I doubt this would work at the moment. I'd like to merge this change and open a separate issue about improving ReindexDocumentationIT so it actually runs the code and catches things like this.

**Comment by cbuescher** [comment]
@elasticmachine test this please

**Review by cbuescher — APPROVED** [review]
LGTM

**Comment by cbuescher** [comment]
@aptxx thanks again for catching this, I will merge this change as soon as CI passes.
I opened #32093 to improve this test suite, in case you are interested in picking it up. It might mean some changes to the test setup for this class though, I haven't checked what kind of work is required.

**Comment by cbuescher** [comment]
@aptxx there are test failures unrelated to your documentation change, could you either merge in or rebase this PR on master please? I was about to do it on your PR branch but since it is also "master" in your forked repo, I didn't want to push to it...

**Comment by aptxx** [comment]
@cbuescher oh... sorry for my mistake. I will make another PR with named branch, It's ok?

**Comment by cbuescher** [comment]
Sure, but you don't have to open a new PR I think. If you rebase your commit (aptxx:master) on  on the current ES master branch then it also should be fine. You can reset your repos master after the merge.

**Comment by cbuescher** [comment]
@elasticmachine test this please

**Comment by cbuescher** [comment]
@aptxx I merged this to master and all the 6.x branches, thanks again for fixing.

**Pull request merged**
