### PR TITLE
Use native scalar scorer for int8_flat index

### PR DESCRIPTION
**Pull request by benwtrent**
Switches to optionally using the native scorers if they are available for int8_flat indices.

### CODE REVIEW

**Comment by benwtrent** [comment]
Well, I benchmarked in GCP. The deployments were in different zones, the exact same size & were big enough to hold all the vectors in memory. My rally runner was in a zone separate from both of them. There is no perceivable difference. There are some interesting numbers, but maybe its due to other changes. 

```
------------------------------------------------------
    _______             __   _____
   / ____(_)___  ____ _/ /  / ___/_________  ________
  / /_  / / __ \/ __ `/ /   \__ \/ ___/ __ \/ ___/ _ \
 / __/ / / / / / /_/ / /   ___/ / /__/ /_/ / /  /  __/
/_/   /_/_/ /_/\__,_/_/   /____/\___/\____/_/   \___/
------------------------------------------------------

|                                                        Metric |                                         Task |       Baseline |      Contender |       Diff |   Unit |   Diff % |
|--------------------------------------------------------------:|---------------------------------------------:|---------------:|---------------:|-----------:|-------:|---------:|
|                    Cumulative indexing time of primary shards |                                              |    3.19077     |    3.03008     |   -0.16068 |    min |   -5.04% |
|             Min cumulative indexing time across primary shard |                                              |    0           |    0           |    0       |    min |    0.00% |
|          Median cumulative indexing time across primary shard |                                              |    0           |    0           |    0       |    min |    0.00% |
|             Max cumulative indexing time across primary shard |                                              |    3.18732     |    3.03008     |   -0.15723 |    min |   -4.93% |
|           Cumulative indexing throttle time of primary shards |                                              |    0           |    0           |    0       |    min |    0.00% |
|    Min cumulative indexing throttle time across primary shard |                                              |    0           |    0           |    0       |    min |    0.00% |
| Median cumulative indexing throttle time across primary shard |                                              |    0           |    0           |    0       |    min |    0.00% |
|    Max cumulative indexing throttle time across primary shard |                                              |    0           |    0           |    0       |    min |    0.00% |
|                       Cumulative merge time of primary shards |                                              |    6.93693     |    7.73925     |    0.80232 |    min |  +11.57% |
|                      Cumulative merge count of primary shards |                                              |   13           |    5           |   -8       |        |  -61.54% |
|                Min cumulative merge time across primary shard |                                              |    0           |    0           |    0       |    min |    0.00% |
|             Median cumulative merge time across primary shard |                                              |    0           |    0           |    0       |    min |    0.00% |
|                Max cumulative merge time across primary shard |                                              |    6.93347     |    7.73925     |    0.80578 |    min |  +11.62% |
|              Cumulative merge throttle time of primary shards |                                              |    5.36443     |    6.93392     |    1.56948 |    min |  +29.26% |
|       Min cumulative merge throttle time across primary shard |                                              |    0           |    0           |    0       |    min |    0.00% |
|    Median cumulative merge throttle time across primary shard |                                              |    0           |    0           |    0       |    min |    0.00% |
|       Max cumulative merge throttle time across primary shard |                                              |    5.36443     |    6.93392     |    1.56948 |    min |  +29.26% |
|                     Cumulative refresh time of primary shards |                                              |    1.66217     |    1.19818     |   -0.46398 |    min |  -27.91% |
|                    Cumulative refresh count of primary shards |                                              |  810           |  181           | -629       |        |  -77.65% |
|              Min cumulative refresh time across primary shard |                                              |    0           |    0           |    0       |    min |    0.00% |
|           Median cumulative refresh time across primary shard |                                              |    0           |    0           |    0       |    min |    0.00% |
|              Max cumulative refresh time across primary shard |                                              |    1.62318     |    1.19818     |   -0.425   |    min |  -26.18% |
|                       Cumulative flush time of primary shards |                                              |    6.63433     |    5.4019      |   -1.23243 |    min |  -18.58% |
|                      Cumulative flush count of primary shards |                                              |  294           |   37           | -257       |        |  -87.41% |
|                Min cumulative flush time across primary shard |                                              |    1.66667e-05 |    1.66667e-05 |    0       |    min |    0.00% |
|             Median cumulative flush time across primary shard |                                              |    1.66667e-05 |    1.66667e-05 |    0       |    min |    0.00% |
|                Max cumulative flush time across primary shard |                                              |    6.57047     |    5.40155     |   -1.16892 |    min |  -17.79% |
|                                       Total Young Gen GC time |                                              |    0.751       |    0.71        |   -0.041   |      s |   -5.46% |
|                                      Total Young Gen GC count |                                              |   51           |   53           |    2       |        |   +3.92% |
|                                         Total Old Gen GC time |                                              |    0           |    0           |    0       |      s |    0.00% |
|                                        Total Old Gen GC count |                                              |    0           |    0           |    0       |        |    0.00% |
|                                                  Dataset size |                                              |   13.1404      |   12.6895      |   -0.45089 |     GB |   -3.43% |
|                                                    Store size |                                              |   13.1404      |   12.6895      |   -0.45089 |     GB |   -3.43% |
|                                                 Translog size |                                              |    0.554081    |    0.627943    |    0.07386 |     GB |  +13.33% |
|                                        Heap used for segments |                                              |    0           |    0           |    0       |     MB |    0.00% |
|                                      Heap used for doc values |                                              |    0           |    0           |    0       |     MB |    0.00% |
|                                           Heap used for terms |                                              |    0           |    0           |    0       |     MB |    0.00% |
|                                           Heap used for norms |                                              |    0           |    0           |    0       |     MB |    0.00% |
|                                          Heap used for points |                                              |    0           |    0           |    0       |     MB |    0.00% |
|                                   Heap used for stored fields |                                              |    0           |    0           |    0       |     MB |    0.00% |
|                                                 Segment count |                                              |   71           |   16           |  -55       |        |  -77.46% |
|                                   Total Ingest Pipeline count |                                              |   52           |    0           |  -52       |        | -100.00% |
|                                    Total Ingest Pipeline time |                                              |   16           |    0           |  -16       |     ms | -100.00% |
|                                  Total Ingest Pipeline failed |                                              |    0           |    0           |    0       |        |    0.00% |
|                                                Min Throughput |                              random-indexing |  581.153       |  600.4         |   19.247   | docs/s |   +3.31% |
|                                               Mean Throughput |                              random-indexing |  745.991       |  757.892       |   11.9007  | docs/s |   +1.60% |
|                                             Median Throughput |                              random-indexing |  755.775       |  769.263       |   13.4877  | docs/s |   +1.78% |
|                                                Max Throughput |                              random-indexing |  763.381       |  775.118       |   11.7373  | docs/s |   +1.54% |
|                                       50th percentile latency |                              random-indexing |  421.654       |  409.133       |  -12.5212  |     ms |   -2.97% |
|                                       90th percentile latency |                              random-indexing |  524           |  515.372       |   -8.62801 |     ms |   -1.65% |
|                                       99th percentile latency |                              random-indexing |  624.972       |  649.458       |   24.486   |     ms |   +3.92% |
|                                     99.9th percentile latency |                              random-indexing |  929.399       |  756.993       | -172.407   |     ms |  -18.55% |
|                                      100th percentile latency |                              random-indexing | 1046.98        |  964.469       |  -82.5092  |     ms |   -7.88% |
|                                  50th percentile service time |                              random-indexing |  421.654       |  409.133       |  -12.5212  |     ms |   -2.97% |
|                                  90th percentile service time |                              random-indexing |  524           |  515.372       |   -8.62801 |     ms |   -1.65% |
|                                  99th percentile service time |                              random-indexing |  624.972       |  649.458       |   24.486   |     ms |   +3.92% |
|                                99.9th percentile service time |                              random-indexing |  929.399       |  756.993       | -172.407   |     ms |  -18.55% |
|                                 100th percentile service time |                              random-indexing | 1046.98        |  964.469       |  -82.5092  |     ms |   -7.88% |
|                                                    error rate |                              random-indexing |    0           |    0           |    0       |      % |    0.00% |
|                                                Min Throughput |                          refresh-after-index |    0.112092    |    0.109355    |   -0.00274 |  ops/s |   -2.44% |
|                                               Mean Throughput |                          refresh-after-index |    0.112092    |    0.109355    |   -0.00274 |  ops/s |   -2.44% |
|                                             Median Throughput |                          refresh-after-index |    0.112092    |    0.109355    |   -0.00274 |  ops/s |   -2.44% |
|                                                Max Throughput |                          refresh-after-index |    0.112092    |    0.109355    |   -0.00274 |  ops/s |   -2.44% |
|                                      100th percentile latency |                          refresh-after-index | 8918.71        | 9141.72        |  223.003   |     ms |   +2.50% |
|                                 100th percentile service time |                          refresh-after-index | 8918.71        | 9141.72        |  223.003   |     ms |   +2.50% |
|                                                    error rate |                          refresh-after-index |    0           |    0           |    0       |      % |    0.00% |
|                                                Min Throughput |   script-score-filtered-search-single-client |   60.8587      |   59.6953      |   -1.16344 |  ops/s |   -1.91% |
|                                               Mean Throughput |   script-score-filtered-search-single-client |   70.3638      |   69.6848      |   -0.67906 |  ops/s |   -0.97% |
|                                             Median Throughput |   script-score-filtered-search-single-client |   71.9288      |   71.0685      |   -0.8603  |  ops/s |   -1.20% |
|                                                Max Throughput |   script-score-filtered-search-single-client |   74.3209      |   73.9147      |   -0.40615 |  ops/s |   -0.55% |
|                                       50th percentile latency |   script-score-filtered-search-single-client |   10.9765      |   11.0733      |    0.09685 |     ms |   +0.88% |
|                                       90th percentile latency |   script-score-filtered-search-single-client |   12.0483      |   12.2341      |    0.18583 |     ms |   +1.54% |
|                                       99th percentile latency |   script-score-filtered-search-single-client |   14.9685      |   14.501       |   -0.4675  |     ms |   -3.12% |
|                                     99.9th percentile latency |   script-score-filtered-search-single-client |   20.5074      |   20.5358      |    0.02845 |     ms |   +0.14% |
|                                      100th percentile latency |   script-score-filtered-search-single-client |   68.2859      |   20.7384      |  -47.5476  |     ms |  -69.63% |
|                                  50th percentile service time |   script-score-filtered-search-single-client |   10.9765      |   11.0733      |    0.09685 |     ms |   +0.88% |
|                                  90th percentile service time |   script-score-filtered-search-single-client |   12.0483      |   12.2341      |    0.18583 |     ms |   +1.54% |
|                                  99th percentile service time |   script-score-filtered-search-single-client |   14.9685      |   14.501       |   -0.4675  |     ms |   -3.12% |
|                                99.9th percentile service time |   script-score-filtered-search-single-client |   20.5074      |   20.5358      |    0.02845 |     ms |   +0.14% |
|                                 100th percentile service time |   script-score-filtered-search-single-client |   68.2859      |   20.7384      |  -47.5476  |     ms |  -69.63% |
|                                                    error rate |   script-score-filtered-search-single-client |    0           |    0           |    0       |      % |    0.00% |
|                                                Min Throughput | script-score-filtered-search-multiple-client |  325.699       |  335.143       |    9.44461 |  ops/s |   +2.90% |
|                                               Mean Throughput | script-score-filtered-search-multiple-client |  361.083       |  359.046       |   -2.03649 |  ops/s |   -0.56% |
|                                             Median Throughput | script-score-filtered-search-multiple-client |  363.797       |  360.806       |   -2.99026 |  ops/s |   -0.82% |
|                                                Max Throughput | script-score-filtered-search-multiple-client |  375.684       |  373.475       |   -2.20873 |  ops/s |   -0.59% |
|                                       50th percentile latency | script-score-filtered-search-multiple-client |   17.9086      |   15.9883      |   -1.92035 |     ms |  -10.72% |
|                                       90th percentile latency | script-score-filtered-search-multiple-client |   26.0359      |   25.6527      |   -0.38326 |     ms |   -1.47% |
|                                       99th percentile latency | script-score-filtered-search-multiple-client |   36.696       |   51.125       |   14.429   |     ms |  +39.32% |
|                                     99.9th percentile latency | script-score-filtered-search-multiple-client |   68.6523      |   68.0195      |   -0.63274 |     ms |   -0.92% |
|                                      100th percentile latency | script-score-filtered-search-multiple-client |  247.121       |  104.011       | -143.11    |     ms |  -57.91% |
|                                  50th percentile service time | script-score-filtered-search-multiple-client |   17.9086      |   15.9883      |   -1.92035 |     ms |  -10.72% |
|                                  90th percentile service time | script-score-filtered-search-multiple-client |   26.0359      |   25.6527      |   -0.38326 |     ms |   -1.47% |
|                                  99th percentile service time | script-score-filtered-search-multiple-client |   36.696       |   51.125       |   14.429   |     ms |  +39.32% |
|                                99.9th percentile service time | script-score-filtered-search-multiple-client |   68.6523      |   68.0195      |   -0.63274 |     ms |   -0.92% |
|                                 100th percentile service time | script-score-filtered-search-multiple-client |  247.121       |  104.011       | -143.11    |     ms |  -57.91% |
|                                                    error rate | script-score-filtered-search-multiple-client |    0           |    0           |    0       |      % |    0.00% |
|                                                Min Throughput |            knn-filtered-search-single-client |   80.155       |   77.1543      |   -3.00074 |  ops/s |   -3.74% |
|                                               Mean Throughput |            knn-filtered-search-single-client |   82.145       |   78.2353      |   -3.9097  |  ops/s |   -4.76% |
|                                             Median Throughput |            knn-filtered-search-single-client |   82.1343      |   78.3576      |   -3.7767  |  ops/s |   -4.60% |
|                                                Max Throughput |            knn-filtered-search-single-client |   82.9355      |   78.5423      |   -4.3932  |  ops/s |   -5.30% |
|                                       50th percentile latency |            knn-filtered-search-single-client |   10.0516      |   10.7564      |    0.70484 |     ms |   +7.01% |
|                                       90th percentile latency |            knn-filtered-search-single-client |   10.8329      |   11.4392      |    0.6063  |     ms |   +5.60% |
|                                       99th percentile latency |            knn-filtered-search-single-client |   13.1136      |   13.7665      |    0.65285 |     ms |   +4.98% |
|                                     99.9th percentile latency |            knn-filtered-search-single-client |   22.6035      |   20.7234      |   -1.88014 |     ms |   -8.32% |
|                                    99.99th percentile latency |            knn-filtered-search-single-client |   46.4945      |   53.227       |    6.73242 |     ms |  +14.48% |
|                                      100th percentile latency |            knn-filtered-search-single-client |   51.0658      |  108.318       |   57.2523  |     ms | +112.11% |
|                                  50th percentile service time |            knn-filtered-search-single-client |   10.0516      |   10.7564      |    0.70484 |     ms |   +7.01% |
|                                  90th percentile service time |            knn-filtered-search-single-client |   10.8329      |   11.4392      |    0.6063  |     ms |   +5.60% |
|                                  99th percentile service time |            knn-filtered-search-single-client |   13.1136      |   13.7665      |    0.65285 |     ms |   +4.98% |
|                                99.9th percentile service time |            knn-filtered-search-single-client |   22.6035      |   20.7234      |   -1.88014 |     ms |   -8.32% |
|                               99.99th percentile service time |            knn-filtered-search-single-client |   46.4945      |   53.227       |    6.73242 |     ms |  +14.48% |
|                                 100th percentile service time |            knn-filtered-search-single-client |   51.0658      |  108.318       |   57.2523  |     ms | +112.11% |
|                                                    error rate |            knn-filtered-search-single-client |    0           |    0           |    0       |      % |    0.00% |
|                                                Min Throughput |          knn-filtered-search-multiple-client |  334.43        |  336.909       |    2.47878 |  ops/s |   +0.74% |
|                                               Mean Throughput |          knn-filtered-search-multiple-client |  370.824       |  362.826       |   -7.99733 |  ops/s |   -2.16% |
|                                             Median Throughput |          knn-filtered-search-multiple-client |  375.374       |  363.97        |  -11.404   |  ops/s |   -3.04% |
|                                                Max Throughput |          knn-filtered-search-multiple-client |  382.941       |  377.222       |   -5.71902 |  ops/s |   -1.49% |
|                                       50th percentile latency |          knn-filtered-search-multiple-client |   17.1318      |   16.4117      |   -0.7201  |     ms |   -4.20% |
|                                       90th percentile latency |          knn-filtered-search-multiple-client |   23.6903      |   28.4974      |    4.80716 |     ms |  +20.29% |
|                                       99th percentile latency |          knn-filtered-search-multiple-client |   30.1311      |   38.9386      |    8.8075  |     ms |  +29.23% |
|                                     99.9th percentile latency |          knn-filtered-search-multiple-client |   66.9918      |   68.3251      |    1.3333  |     ms |   +1.99% |
|                                      100th percentile latency |          knn-filtered-search-multiple-client |   79.371       |   76.2703      |   -3.10067 |     ms |   -3.91% |
|                                  50th percentile service time |          knn-filtered-search-multiple-client |   17.1318      |   16.4117      |   -0.7201  |     ms |   -4.20% |
|                                  90th percentile service time |          knn-filtered-search-multiple-client |   23.6903      |   28.4974      |    4.80716 |     ms |  +20.29% |
|                                  99th percentile service time |          knn-filtered-search-multiple-client |   30.1311      |   38.9386      |    8.8075  |     ms |  +29.23% |
|                                99.9th percentile service time |          knn-filtered-search-multiple-client |   66.9918      |   68.3251      |    1.3333  |     ms |   +1.99% |
|                                 100th percentile service time |          knn-filtered-search-multiple-client |   79.371       |   76.2703      |   -3.10067 |     ms |   -3.91% |
|                                                    error rate |          knn-filtered-search-multiple-client |    0           |    0           |    0       |      % |    0.00% |


-------------------------------
[INFO] SUCCESS (took 0 seconds)
-------------------------------
```

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Comment by benwtrent** [comment]
I have verified that the native scorer is indeed being used. 

I would prefer merging this rather than not to unify the HNSW scoring vs. the flat scoring.

**Review by ChrisHegarty — APPROVED** [review]
LGTM

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Pull request merged**
