### PR TITLE
QL: Update dependency - JLine - to v 3.21.0

### LINKED ISSUE #83575: SQL: Upgrade  JLine/Jansi
### Description

The current version of JLine used by the SQL CLI has an old JAnsi dependency - when used in an environment with new hardware (such as Apple M1/Silicon) the terminal detection is unlikely to work (see https://github.com/elastic/elasticsearch/pull/83566).
Upgrading JAnsi to 2.4 (and by transition JLine as well) should fix this problem.

### PR DESCRIPTION
**Pull request by luigidellaquila**
Previous JLine versions have a dependency from an old JAnsi version
that could lead to problems to terminal detection on new hardware (eg. M1/Silicon).

Fixes #83575

### CODE REVIEW

**Comment by luigidellaquila** [comment]
@elasticmachine retest this please

**Review by Luegg — APPROVED** [review]
Lgtm, and congrats to your inaugural ES PR 🎊

**Review by astefan — APPROVED** [review]
LGTM

**Review by bpintea — APPROVED** [review]
LGTM

**Review by costin — APPROVED** [review]
LGTM - Can you confirm that jansi 2.4+ or higher is used?

**Comment by luigidellaquila** [comment]
Good point @costin, given #83575 I thought it was the case. I also checked the pom of the 3.21.0 tag and it depends on jansi 2.4 indeed (see https://github.com/jline/jline3/blob/jline-parent-3.21.0/pom.xml#L86).

The problem (and the only thing I did not realise) is that we are using `jline-terminal-jna`, not `jline-terminal-jansi`, so unless I'm missing something, this upgrade is probably not needed.

**Comment by costin** [comment]
Since we're already down this path, please take a look at the JNA dependency since version 5.10 contains a nice fix by @DaveCTurner.
If the CLI works (I believe you have a Apple M1), let's use that instead - and maybe there's a way to sync the JNA version in gradle with that of the server so any future upgrades on this front happen for us as well.

**Comment by luigidellaquila** [comment]
Unfortunately I don't have an M1 (yet...), so I cannot test it.
And JLine 3.21.0 still depends on JNA v 5.9.0.
Still, having an updated dependency is not bad, but the scope of the "fix" is a bit different from what we expected

**Comment by costin** [comment]
Thanks for checking, I'm fine with closing the issue.

**Comment by luigidellaquila** [comment]
Do you mean closing the PR (without merging) and closing #83575 ?

**Comment by luigidellaquila** [comment]
Closing, since not really relevant to the issue we were addressing.
We can still re-consider it in case we have to upgrade JLine for other reasons

**Comment by luigidellaquila** [comment]
@elasticmachine update branch

**Comment by luigidellaquila** [comment]
Tested on Apple M1, it seems also JNA implementation has problems (see https://github.com/elastic/elasticsearch/issues/83575#issuecomment-1134806737 ). 
So even if we do not use JAnsi, we'll have to upgrade anyway.

**Comment by costin** [comment]
👍

**Pull request merged**
