### PR TITLE
Handle ambiguously deprecated APIs in YAML REST tests

### PR DESCRIPTION
**Pull request by williamrandolph**
This PR is an attempt to solve the problem raised in #45636.

The YAML test definitions use an API name and a set of parameters to invoke APIs. Sometimes the same conceptual API call can be triggered by multiple paths. For example, `PUT /{index}/_alias/{name}` does the same thing and has the same path parameters as `PUT /{index}/_aliases/{name}`. Our YAML test framework will choose randomly between these two paths when it's time for actual tests.

When a path is deprecated, using it in a YAML test will yield a warning header that the test-writer needs to account for. For example:

```
  - do:
      indices.upgrade:
        index: ["does_not_exist", "test_index"]
        ignore_unavailable: true
      warnings:
        - "The _upgrade API is no longer useful and will be removed. Instead, see _reindex API."
      node_selector:
        version: "8.0.0 - "
```

What would happen in the "put alias" example if we deprecated one path but not the other? We'd be in the situation where we'd get a deprecation warning randomly, depending on which path happened to be chosen at test time. There's currently no way to add a "sometimes" warning in tests.

This PR offers one possible solution. We can detect the situation in which we have ambiguous deprecations in our API definitions and add those warnings specifically.

One complication that I know I haven't handled: how are these tests used for backwards compatibility? For example, if something is ambiguously deprecated starting in 7.5.0, would this code expect a potential warning when run against 7.4.0? Such a problem might require more code, or an entirely different approach.

### CODE REVIEW

**Comment by williamrandolph** [comment]
@elasticmachine run elasticsearch-ci/bwc elasticsearch-ci/default-distro

I suspect that this task needs to go back to the drawing board to account for backwards compatibility.

**Comment by williamrandolph** [comment]
@elasticmachine run elasticsearch-ci/default-distro

**Comment by nik9000** [comment]
I think the simplest thing might be for the random path picker never to pick deprecated paths unless explicitly forced to do so with some kind of override parameter. That feels a little more "pure" to me. Less randomized, maybe, but a little more predictable for most tests.

**Review by nik9000 — CHANGES_REQUESTED** [review]
See my previous comment. I could certainly be convinced this is the right thing, but I don't *think* it is.

**Comment by williamrandolph** [comment]
@nik9000,

I've re-read the discussion on #45636, and I think the override parameter could work pretty well.

So by default, we would choose a non-deprecated path, falling back to a deprecated path if only deprecated paths are available. However, if a developer wants to test that a deprecated path with a non-deprecated equivalent returns a warning, they can request a deprecated path in their test.

If that's what we want to do, I may close this PR and issue a new one when I get a chance to work on this issue again.

**Comment by nik9000** [comment]
> So by default, we would choose a non-deprecated path, falling back to a deprecated path if only deprecated paths are available. However, if a developer wants to test that a deprecated path with a non-deprecated equivalent returns a warning, they can request a deprecated path in their test.
> 
> If that's what we want to do, I may close this PR and issue a new one when I get a chance to work on this issue again.

That sounds good to me!

**Comment by williamrandolph** [comment]
I'm going to try a different approach to this problem. Closing without merging.

**Pull request closed without merging**
