### PR TITLE
Remove schedule field from EnrichPolicy

### PR DESCRIPTION
**Pull request by martijnvg**

### CODE REVIEW

**Comment by hub-cap** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by hub-cap** [comment]
Just so we are on the same page and it is documented, the reason schedule is being removed is because updating the index that has the enrich data is updated by a user, and the update enrich policy can be done manually after the index is updated by said user, correct?

**Review by hub-cap — APPROVED** [review]
LGTM :shipit:

**Comment by martijnvg** [comment]
> the reason schedule is being removed is because updating the index that has the enrich data is updated by a user, and the update enrich policy can be done manually after the index is updated by said user, correct?

That is correct.

**Review by jbaiera — APPROVED** [review]
LGTM

**Comment by martijnvg** [comment]
@elasticmachine run elasticsearch-ci/1

**Pull request merged**
