### PR TITLE
Only create index on document deletion if external versioning is used

### LINKED ISSUE #15425: Deleting a document from a non-existing index creates the index
Using the default settings, if a delete request is issued for a single document against a non-existing index, Elasticsearch will create the index. Steps to reproduce:

```
DELETE /foo
```

```
DELETE /foo/bar/1
```

Then:

```
GET /foo
```

responds with HTTP 200 OK and response body

```
{
  "foo" : {
    "aliases" : { },
    "mappings" : { },
    "settings" : {
      "index" : {
        "creation_date" : "1450124918393",
        "number_of_shards" : "5",
        "number_of_replicas" : "1",
        "uuid" : "Ny3PruSCTIG5TlYecU0_XA",
        "version" : {
          "created" : "3000099"
        }
      }
    },
    "warmers" : { }
  }
}
```

showing that it created the index.

### PR DESCRIPTION
**Pull request by ywelsch**
Closes #15425

### CODE REVIEW

**Comment by nik9000** [comment]
I like it.

**Comment by bleskes** [comment]
we should also deal with the bulk request. Also, I'm fine with not pushing it all the way to 1.7.5 if mergine gets hairy.

**Comment by ywelsch** [comment]
good catch @bleskes, added support for bulk.

**Comment by ywelsch** [comment]
@bleskes pointed out that creating the index on delete can be useful in the case of external versioning. With concurrent delivery from an external source, operations might arrive out of order. A delete operation might thus arrive earlier than its preceding index operation. If the delete operation does not create an index and marks the document as deleted (with higher version), the index operation will recreate the index and document (with lower version).

I adapted the PR accordingly to only create index on document deletion if external versioning is used.

Also I changed the labels. As this is a breaking change, I don't think it should be backported.

**Comment by nik9000** [comment]
> If the delete operation does not create an index and marks the document as deleted (with higher version), the index operation will recreate the index and document (with lower version).

My understanding is that those deletes don't stick around forever anyway so you can't rely on this behavior. So its just a bonus. Is it worth the complexity in this case?

> Also I changed the labels. As this is a breaking change, I don't think it should be backported.

I don't think its worth backporting.

**Comment by dakrone** [comment]
@ywelsch is this still an issue with @abeyad's index tombstone PR in #17265 ? Is it still applicable?

**Pull request closed without merging**
