### PR TITLE
x-pack/plugin/apm-data: fix `@custom` component templates

### PR DESCRIPTION
**Pull request by axw**
Use `<data_stream.type>@custom` instead of `apm@custom`. This is an enhancement over what Fleet sets up; it is an additive improvement in the direction of https://github.com/elastic/elasticsearch/issues/97664.

The rollup data streams' `@custom` component templates now include the duration, like what Fleet sets up.

Add a YAML REST test, and a unit test ensuring consistency across the index templates.

### CODE REVIEW

**Comment by felixbarny** [comment]
I'm wondering if we should keep the `apm@custom` component templates in addition to the ones you've added for backwards compatibility reasons. Users may have already added an `apm@custom` component template. If we stop importing them, that could be considered a breaking change.

**Comment by axw** [comment]
> I'm wondering if we should keep the apm@custom component templates in addition to the ones you've added for backwards compatibility reasons. Users may have already added an apm@custom component template. If we stop importing them, that could be considered a breaking change.

@felixbarny `apm@custom` isn't something that gets added by Fleet, it was something I made up for the plugin to support cross-cutting mappings or settings customisations. Since the plugin is tech preview, I don't think we need to worry about backwards compatibility yet.

**Comment by felixbarny** [comment]
Ah, I wasn't aware of that. Makes sense then.

**Review by felixbarny — APPROVED** [review]
Love the test chat checks for compliance to the naming conventions

**Comment by axw** [comment]
@elasticmachine update branch

**Pull request merged**
