### PR TITLE
Indentation refine for api spec: indices.put_settings.json

### PR DESCRIPTION
**Pull request by dingminyi**
Hi Team,
Found a tiny imperfection in indices.put_settings.json, please kindly review.

Thanks!
Minyi

### CODE REVIEW

**Comment by karmi** [comment]
Hi @dingminyi, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/elasticsearch/pull/27718.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by dingminyi** [comment]
Hi Karmi,
Thanks for your reminder! Just added that email to my github account.

**Comment by karmi** [comment]
Hi, something weird is going with the CLA check, because if you have added the e-mail from the commit to your Github profile, the check should be green. We've had a similar issue yesterday, we'll look into it.

**Comment by dingminyi** [comment]
Hi Karmi,
Thank you for your reply, I added the email after I sent the PR, maybe that's the reason? 

Thanks!

**Comment by karmi** [comment]
Sadly no, the timing shouldn't matter...

**Comment by dingminyi** [comment]
Hi Karmi,
Got it. Waiting for the updates, thanks! :)

**Comment by javanna** [comment]
this got fixed in the meantime by #29327 , thanks anyways @dingminyi !

**Pull request closed without merging**
