### PR TITLE
Version bump AWS SDK 1.11.18

### PR DESCRIPTION
**Pull request by nl5887**
- bump version
- fixed issue with double md5 signature generation

### CODE REVIEW

**Comment by nl5887** [comment]
the repository-s3 plugin is throwing an error in the unit tests. This has probably to do with the security policy, suggestions on how to solve are appreciated.

 > Throwable #1: java.lang.AssertionError: expected [2xx] status code but api [snapshot.create_repository] returned [500 Internal Server Error] [{"error":{"root_cause":[{"type":"repository_exception","reason":"[test_repo_s3_1] failed to create repository"}],"type":"repository_exception","reason":"[test_repo_s3_1] failed to create repository","caused_by":{"type":"access_control_exception","reason":"access denied (\"java.lang.RuntimePermission\" \"accessDeclaredMembers\")"}},"status":500}]

**Comment by nik9000** [comment]
Yeah, that looks like a security exception. The plugin already has that permission but, I expect, there is so new access pattern for it now. You'll have to track that down and wrap it in `AccessController.doPrivileged`.

**Comment by nik9000** [comment]
Maybe @tlrx should review this? I don't know that AWS stuff well.

**Comment by dadoonet** [comment]
Hi @nl5887.

I'm sorry I did not see your PR before I started working on #19594 (upgrade to 1.11.20).

So I just cherry-picked your commit https://github.com/elastic/elasticsearch/pull/19489/commits/9fd0d62e2b4088088d58a5a2802c82876fbe0185 in my PR.

The PR I started has also some modifications in docs and tests as a default value of the AWS SDK has changed (throttle retries).
Also in 1.11.20 some (a lot of) methods now returns an Object instead of `void`.

I think we should close your PR and work in #19594 now.

**Comment by clintongormley** [comment]
Closing in favor of #19594

**Comment by nl5887** [comment]
@dadoonet  no worries. Thx for cherry picking the commit, that will solve some issues.

**Pull request closed without merging**
