### PR TITLE
Remove manual parsing of JVM options

### PR DESCRIPTION
**Pull request by jasontedor**
This commit removes manual parsing of JVM options when calculating ergonomics. This is to avoid a situation that we parse values differently than the JVM would. In fact, we already have a bug along these lines today. It is possible to start the JVM with the same flag multiple times on the command line. In this case, the last value wins. For example, -Xmx1g -Xmx2g would start the JVM with a heap size of two gigabytes. Our JVM ergonomics ignores this possibility and instead the first value is winning!

Our strategy to avoid manual parsing of the JVM options is to start the Java command line parser (without actually starting a JVM) by invoking java with the same command line flags as presented and request that the JVM tell us what values it would start with. This ensures that we have the correct values when making ergonomic decisions.

Moreover, our strategy also is ignoring ES_JAVA_OPTS which could override the heap size as well leading to incorrect ergonomic choices. This commit address this issue too.

Relates #30684

### CODE REVIEW

**Comment by jasontedor** [comment]
To my beloved reviewers: This approach was [initially](https://github.com/elastic/elasticsearch/pull/30684#discussion_r189003241) suggested on the original work introducing the ergonomics. Please see the [discussion](https://github.com/elastic/elasticsearch/pull/30684#discussion_r189238296) there as part of your review before we consider pulling this in. I think that we can revisit the discussion here if needed.

**Comment by rjernst** [comment]
This seems like a very heavyweight hack. Launching a VM with Xmx pretouched, just to find out what the value was is a huge cost (relative to normal startup).

Both the bugs you mentioned (first vs last wins, missing ES_JAVA_OPTS) seem fixable with the current implementation. IMO keeping our own parsing isn't that expensive vs incurring the added startup cost for every node we start (which amplifies in our integration tests as we start a lot of nodes...).

**Comment by jasontedor** [comment]
I think there is confusion here, introduced by my commit message (I will reword it); I’m sorry for that. If you refer back to the initial discussion in #30684, we do not actually start a JVM here, only invoke `java` for options parsing. By requesting `-XX:+PrintFlagsFinal -version` it only causes the Java process to parse the options, display all the JVM flags, print the version, and exit. The JVM itself never bootstraps. This is actually quite cheap then.

While what we are doing today has bugs that can be fixed without resorting to this, there are bugs we have today that can not. Here’s a list of the bugs we have today:
 - ordering of options
 - ignore `ES_JAVA_OPTS`
 - wrong value if heap size is not specified (there are use cases for this, in containers)
 - we don’t parse all possible unit specifications

The third of these simply can not be fixed by us. My change fixes all of these, with no additional effort on our end. We don’t have to have a side implementation of the JVM parsing logic.

Additionally, this sets us up to easily extract the value of `MaxDirectMemorySize`, without having to parse that too.

Thus I maintain this is a superior approach.

**Comment by jaymode** [comment]
> I think there is confusion here, introduced by my commit message (I will reword it)

The semantics of invoking `java -XX:+PrintFlagsFinal -version` with all the JVM flags we are going to start elasticsearch with is not intuitive enough to only have code without comments IMO; I think we need to spell this out in a code comment and probably cover:

1. Does not start a JVM and hence does not allocate/pretouch GBs of memory
2. Only invokes the option parser
3. Is cheap
4. Allows us to avoid having our own implementation of JVM option parsing logic 

I'm personally in favor of this approach.

**Comment by jasontedor** [comment]
@jaymode I pushed a comment in 8aed51e030e004711098d6a3e8918de4b917a904.

**Comment by rjernst** [comment]
>  we do not actually start a JVM here, only invoke java for options parsing. By requesting -XX:+PrintFlagsFinal -version it only causes the Java process to parse the options, display all the JVM flags, print the version, and exit.

You are right, I completely missed that, I'm sorry. I misinterpreted a comment from Daniel in the previous discussion about startup time of java with 8GB Xmx. Given my new understanding, this approach does sound superior.

**Review by rjernst — APPROVED** [review]
LGTM. Thanks for the comment in code, it makes much more sense now.

**Review by jaymode — APPROVED** [review]
LGTM

**Review by danielmitterdorfer — APPROVED** [review]
I'm fine with the approach. Indeed it seems superior to me.

> Additionally, this sets us up to easily extract the value of MaxDirectMemorySize, without having to parse that too.

I think you left out one detail that led me to misinterpret your statement originally. We can properly parse `MaxDirectMemorySize` provided that the user has specified one. If the user did not specify one, we see a `MaxDirectMemorySize` of 0 because the JVM determines this value in a much later stage during startup. If I run this:

```
daniel@io:~ $ java -XX:+PrintFlagsFinal -version | grep MaxDirectMemorySize
```

I get:

```
 uint64_t MaxDirectMemorySize                      = 0                                         {product} {default}
openjdk version "12" 2019-03-19
OpenJDK Runtime Environment (build 12+32)
OpenJDK 64-Bit Server VM (build 12+32, mixed mode, sharing)
```

But as I said: I think your intention was to state that we can parse the user-specified value with this approach as well.

**Pull request merged**
