### PR TITLE
Bump the min java version for examples

### PR DESCRIPTION
**Pull request by jakelandis**
This commit bumps the min java version for the example to Java 21.

### CODE REVIEW

**Comment by jakelandis** [comment]
@elasticsearchmachine update branch

**Comment by jakelandis** [comment]
@elasticmachine merge upstream

**Comment by jakelandis** [comment]
@elasticmachine merge upstream

**Comment by jakelandis** [comment]
this is now failing due to : 

```
co.elastic.clients.elasticsearch._types.ElasticsearchException: [es/security.put_user] failed: [media_type_header_exception] Invalid media-type value on headers [Content-Type, Accept]
	at __randomizedtesting.SeedInfo.seed([1785297466FBE136:F64044BABE96A74A]:0)
	at app//co.elastic.clients.transport.ElasticsearchTransportBase.getApiResponse(ElasticsearchTransportBase.java:345)
	at app//co.elastic.clients.transport.ElasticsearchTransportBase.performRequest(ElasticsearchTransportBase.java:147)
	at app//co.elastic.clients.elasticsearch.security.ElasticsearchSecurityClient.putUser(ElasticsearchSecurityClient.java:1774)
	at app//co.elastic.clients.elasticsearch.security.ElasticsearchSecurityClient.putUser(ElasticsearchSecurityClient.java:1791)
	at app//org.elasticsearch.example.CustomAuthorizationEngineIT.testRunAs(CustomAuthorizationEngineIT.java:124)
	at java.base@21.0.4/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
```
which is caused by the test using the (newish) java client (version 9) that sets the compatible rest api version to 9. The checks currently don't know about v9. https://github.com/elastic/elasticsearch/pull/113151 has been raised to allow the v9 header from the java-client.

**Comment by jakelandis** [comment]
@elasticmachine merge upstream

**Comment by jakelandis** [comment]
upstream changes are now sorted and the test here will now pass.

**Review by mark-vieira — APPROVED** [review]

**Pull request merged**
