### PR TITLE
Update release notes for 7.17.0 BC3

### PR DESCRIPTION
**Pull request by albertzaharovits**
https://elasticsearch_83153.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/7.17/release-notes-7.17.0.html

Follow-up on https://github.com/elastic/elasticsearch/pull/82858 .

### CODE REVIEW

**Comment by droberts195** [comment]
Do you think it's also worth removing the one about an internal coding detail about the `DataStream` constructor? https://github.com/elastic/elasticsearch/pull/82858#discussion_r792494203

**Comment by albertzaharovits** [comment]
@droberts195 good point, will do, Thank you!

**Comment by lockewritesdocs** [comment]
#83138 also impacts the release notes -- I'd suggest that @droberts195 merge that PR first, update this branch, and then merge to avoid conflicts.

**Comment by albertzaharovits** [comment]
Okay, I'll merge now.

**Pull request merged**
