### PR TITLE
Adding 'y' and 'M' to fuzziness parameter

### PR DESCRIPTION
**Pull request by cfontes**
Idea about how to add year and month as parameters to fuzziness search.
Without having to lock the M to 30 days and Year to 365 or something like that.

### CODE REVIEW

**Comment by s1monw** [comment]
@cfontes ping

**Comment by cfontes** [comment]
Hey, @s1monw . I completely forgot about it.

I will take a look at this week (tonight I hope)

**Comment by s1monw** [comment]
@cfontes welcome back :)

**Comment by cfontes** [comment]
Alright, so.

Hi, sorry for the delay again but I just switched jobs so studying a lot of things right now.
 
I think this should be made into 2 changes... One only for the fuzzy search and another for the common parser.

Mostly because I like having the range expanding for the fuzzy search like it is today, what do I mean by that.

If you use ``` 1M ``` in Fuzzysearch it will search the range : today - 1 Month until today + 1 month (joda months).

The time parsers to me looks more like give me back : today - 1 month.

What do you think?

So in this pull Icould add some tests ( I am trying to figure how to do it ) and maybe create another for the parser.

**Comment by clintongormley** [comment]
A long time has passed since this PR was initially proposed, and a lot has changed since then. I'm going to close this for now but please feel free to re-propose based on the current master.

**Pull request closed without merging**
