### PR TITLE
Lower severity of IDE Checkstyle rules for JavaDoc

### PR DESCRIPTION
**Pull request by pugnascotia**
Lower the severity from "warning" to "info", and raise the length of methods that we ignore from 2 lines to 5.

### CODE REVIEW

**Review by mark-vieira — APPROVED** [review]
How are "info" warnings highlighted in the IDE or are they simply omitted entirely in the editor, and just listed the the Checkstyle window details?

**Comment by pugnascotia** [comment]
IntelliJ classes them as "weak warnings", and in my IDE I get a pale yellow squiggly line, and a pale yellow marker at the side. So still there, just less intrusive.

**Comment by mark-vieira** [comment]
> IntelliJ classes them as "weak warnings", and in my IDE I get a pale yellow squiggly line, and a pale yellow marker at the side. So still there, just less intrusive.

I think this is still just superfluous noise unless we honestly expect folks to be backfilling this documentation. As you said, this might require a larger discussion. I get our docs say add javadocs everywhere but if in practice folks aren't doing it, and yelling at them just make them disable Checkstyle in its entirety then we kind of defeat the purpose of this IDE integration.

**Comment by pugnascotia** [comment]
I've merged this in the meantime while I kick off a conversation with the team.

**Pull request merged**
