### PR TITLE
Minor style change to getting-started.asciidoc

### PR DESCRIPTION
**Pull request by bkarlovitz**
I have made the following changes:

* In line 525, change the phrase "... with as little network roundtrips as possible." to "... with as few network roundtrips as possible."

### CODE REVIEW

**Comment by bkarlovitz** [comment]
I just completed signing the CLA :)

**Comment by nik9000** [comment]
Makes sense to me. Can you sign the CLA so we can merge this? We need the CLA even for docs changes.

**Comment by nik9000** [comment]
> I just completed signing the CLA :)

Like ships passing in the night. Our comments should make the CLA checker update. It rechecks every time someone comments and the test has yet to pass.

**Comment by nik9000** [comment]
Merged. Thanks @bkarlovitz! Here are the hashes for the branches this is in:

master: f03723a812e184bb448350028a187f5b98eb865d
5.x: eeca3d3449a5dcbb304a27ede091964a8226973d
5.0: e0852ce409c589774fd559a32fca36006d6c1069

It should be live in the docs in half an hour or so if all goes well.

**Pull request merged**
