### PR TITLE
Bump bundled JDK to 17.0.2+8

### LINKED ISSUE #83242: Upgrade Adoptium OpenJDK to 17.0.2+8
Adoptium OpenJDK 17.0.2+8 is now available. We need to upgrade the version that is bundled with Elasticsearch to the newer version. We currently bundle 17.0.1+12.

### PR DESCRIPTION
**Pull request by pugnascotia**
JDK 17.0.2 is released so upgrade our bundled JDK.

Closes #83242.

### CODE REVIEW

**Comment by pugnascotia** [comment]
@elasticmachine retest this please

**Comment by pugnascotia** [comment]
@elasticmachine update branch

**Review by mark-vieira — APPROVED** [review]
LGTM

**Comment by pugnascotia** [comment]
Backported to `7.17` in db2f40dd130.

**Pull request merged**
