### PR TITLE
Named analyzer should close the analyzer that it wraps

### PR DESCRIPTION
**Pull request by imotov**
It looks like [I lost it](https://github.com/elastic/elasticsearch/commit/1cc5ee7ad9be4412392b0f7e4de53c1c8b5fdd10#diff-ae608cc41abb24a78fb363cb8e415572L93) during lucene 4.0 migration.

### CODE REVIEW

**Comment by jpountz** [comment]
I *think* that makes sense. One thing that worries me a bit is that `NamedAnalyzer` has a constructor that passes the `INDEX` scope implicitly. Maybe we should get rid of this constructor or make the scope explicit in order to force things that create named analyzers to think about the scope the analyzer should have. I think the current way makes it too easy to create an analyzer with the `INDEX` scope by mistake while the intention is to use this analyzer globally.

**Comment by imotov** [comment]
@jpountz that's a great idea, I will add this change. I also realized that wrapper for another named analyzer `NamedAnalyzer(NamedAnalyzer analyzer, int positionIncrementGap)` might cause the same `INDEX`-scoped analyzer to be closed twice when we close an index. Not sure what would be a good way to handle that.

**Comment by jpountz** [comment]
Closing twice is fine, the javadocs of Closeable#close state that closing twice is a no-op: https://docs.oracle.com/javase/8/docs/api/java/io/Closeable.html#close--.

**Comment by imotov** [comment]
@jpountz you are right. I have removed the constructor that you were worried about. We can also make it 5.0.0-only fix just in case.

**Review by jpountz — APPROVED** [review]
LGTM

**Comment by jpountz** [comment]
By the way, +1 to make it 5.x only. I don't think this proved to be an issue on 2.x and destabilizing 2.x is the last thing we'd want these days.

**Pull request merged**
