### PR TITLE
#41196 | Add aws KMS encryption in the elastic search repository-s3 plugin

### PR DESCRIPTION
**Pull request by Prasannasaraf**
https://github.com/elastic/elasticsearch/issues/41196

### CODE REVIEW

**Comment by elasticcla** [comment]
Hi @Prasannasaraf, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in your Git [commit](https://github.com/elastic/elasticsearch/pull/47466.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by original-brownbear** [comment]
@Prasannasaraf we don't accept any new contributions for the `7.3.x` branch since `7.4` is out. Could you please open a PR with your changes against `master`?

Thanks!

**Comment by Prasannasaraf** [comment]
Okay. Will close this but can we merge this on  7.x branch ?. This would help our team to use repository-s3 plugin.
Master PR: https://github.com/elastic/elasticsearch/pull/47486

**Comment by original-brownbear** [comment]
@Prasannasaraf yes, if we end up merging it, we'll backport to `7.x` as well. I'll have a look at #47486 then and will close here. Thanks!

**Pull request closed without merging**
