### PR TITLE
Make Tuple a record

### PR DESCRIPTION
**Pull request by arteam**
`Tuple` is used extensively across the ES codebase and can be effectively represent as a Java record.

### CODE REVIEW

**Comment by arteam** [comment]
@elasticmachine run elasticsearch-ci/packaging-tests-unix-sample

**Comment by arteam** [comment]
@elasticmachine run elasticsearch-ci/packaging-tests-unix-sample

**Comment by arteam** [comment]
@elasticmachine update branch

**Comment by arteam** [comment]
@elasticmachine update branch

**Review by grcevski — APPROVED** [review]
LGTM!

**Comment by arteam** [comment]
@elasticmachine update branch

**Comment by arteam** [comment]
Thanks Nikola!

**Pull request merged**
