### PR TITLE
[Docs] Delete Elasticsearch Homebrew 8.x docs

### PR DESCRIPTION
**Pull request by bytebilly**
In 8.x we will not provide Elasticsearch Homebrew support anymore.
This PR removes related docs and fixes references in other pages.

### CODE REVIEW

**Review by pugnascotia — APPROVED** [review]

**Comment by bytebilly** [comment]
@debadair could you please check if everything is consistent with the docs flow? Thanks!

**Comment by bytebilly** [comment]
@elasticsearchmachine update branch

**Comment by bytebilly** [comment]
@elasticsearchmachine run elasticsearch-ci/docs

**Comment by debadair** [comment]
@elasticmachine Retest this please

**Review by debadair — APPROVED** [review]
LGTM

**Pull request merged**
