### PR TITLE
Fix ShardInfo#toString

### PR DESCRIPTION
**Pull request by jasontedor**
ShardInfo#toString resorts to calling ShardInfo#toXContent via
Strings#toString. However, the resulting XContent object will not start
with an object, and this is a violation of the generator state
machine. This commit fixes this issue by invoking the override of
Strings#toString that will wrap the resulting XContent in an
object. Without this fix, ShardInfo#toString will instead produce "Error
building toString out of XContent:
com.fasterxml.jackson.core.JsonGenerationException: Can not write a
field name, expecting a value"

### CODE REVIEW

**Comment by jasontedor** [comment]
I found this while iterating on #21254.

**Comment by javanna** [comment]
Porbably a different discussion, but I wonder if it's right to call `toXContent` from `toString` methods. Maybe we should have a different output, like the `toString` that IDEs generate? I know that we get `toXContent` for free in many cases but I am not sure how readable and useful that is. What is your opinion?

**Review by abeyad — APPROVED** [review]
LGTM, but I believe `ReplicationResponseTests` needs the license header text up top

**Comment by nik9000** [comment]
I'd like us to have `ToXContent` and `ToInnerXContent` interfaces which declare `toXContent` and `innerToXContent` respectively. The first one should always be a proper object which the second one can spit out a field. That way we can use the compiler to make this decision.

But it is a dream.

**Comment by jasontedor** [comment]
> What is your opinion?

In general, I prefer the pretty output for `toString`, not the `toXContent` output exactly (as you say) because the latter is unreadable while debugging. If you would like me to make that change for `ShardInfo` in this pull request, I'm fine with it.

**Comment by javanna** [comment]
>  If you would like me to make that change for ShardInfo in this pull request, I'm fine with it.

I think at least pretty print would make sense, yes. I meant that maybe we should not print out json at all, but that is not for this PR :)

**Comment by jasontedor** [comment]
@javanna I pushed 5faf26da634017890d7f2beaff029331f7facfee.

**Comment by javanna** [comment]
thanks @jasontedor !

**Comment by jasontedor** [comment]
Thanks @abeyad, @javanna and @nik9000 for taking a look.

**Comment by xavierfacq** [comment]
Hi, do you plan to apply this fix on the 2.x branch ?

**Comment by xavierfacq** [comment]
Hi, do you plan to apply this fix to the branch 2.4 ?

**Comment by jasontedor** [comment]
Yes, I can backport but it might be awhile until there is a release that contains it.

**Comment by jasontedor** [comment]
Backported in d464287f0850a0ba6a7beafbc855e4fa655ac209.

**Pull request merged**
