### PR TITLE
Adds usage data for ILM

### PR DESCRIPTION
**Pull request by colings86**
Currently the response from the x-pack usage API would be:
```
"ilm": {
    "policy_count": 4,
    "policy_stats": [
      {
        "phases": {
          "warm": {
            "after": "0ms",
            "actions": [
              "allocate",
              "forcemerge"
            ]
          },
          "hot": {
            "after": "0ms",
            "actions": [
              "rollover"
            ]
          },
          "delete": {
            "after": "2m",
            "actions": [
              "delete"
            ]
          }
        }
      },
      {
        "phases": {
          "hot": {
            "after": "0ms",
            "actions": [
              "rollover"
            ]
          },
          "delete": {
            "after": "2m",
            "actions": [
              "delete"
            ]
          }
        }
      },
      {
        "phases": {
          "warm": {
            "after": "0ms",
            "actions": [
              "allocate",
              "shrink",
              "forcemerge"
            ]
          },
          "cold": {
            "after": "1m",
            "actions": [
              "allocate"
            ]
          },
          "hot": {
            "after": "0ms",
            "actions": [
              "rollover"
            ]
          },
          "delete": {
            "after": "2m",
            "actions": [
              "delete"
            ]
          }
        }
      },
      {
        "phases": {
          "warm": {
            "after": "0ms",
            "actions": [
              "allocate",
              "forcemerge"
            ]
          },
          "cold": {
            "after": "1m",
            "actions": [
              "allocate"
            ]
          },
          "hot": {
            "after": "0ms",
            "actions": [
              "rollover"
            ]
          },
          "delete": {
            "after": "2m",
            "actions": [
              "delete"
            ]
          }
        }
      }
    ]
  },
```

### CODE REVIEW

**Comment by colings86** [comment]
@elasticmachine please test this

**Comment by colings86** [comment]
@elasticmachine test this please

**Comment by colings86** [comment]
@elasticmachine test this please

**Comment by talevy** [comment]
Do we know how people are expected to use this data? I believe it does a great job providing all the policy usage info on a per-policy basis for users to group and keep track of things.

What I am not clear on is, who is expected to consume this data? is it other Elasticsearch toolings, or users?
For example, if counts of action usages are important, maybe this structure would pre-calculate things for the user:


```
{
 <phase_name>: {
     "after": ["1m", "5d", "13d"],
     "actions": {
        <action_name>: <num_times_action_used_in_this_phase>,
        ...
     }
 }
}
```

@eskibars, since Colin is out, I would love your input on this since I am missing some context. thanks!

**Comment by talevy** [comment]
After speaking with @eskibars in a different channel, I learned that these documents are intended to be aggregated as documents in ES, and so their structure should reflect that intention.

If that is the case, should the phase be contained in a field value that can be used in term aggregations?

**Review by talevy — CHANGES_REQUESTED** [review]
I have left a few comments

**Comment by colings86** [comment]
@talevy I addressed your comment, could you take another look?

**Review by talevy — APPROVED** [review]
I think this will be good!

should we add yaml tests?

**Pull request merged**
