### PR TITLE
Upgrade Painless from ANTLR 4.5.1-1 to  ANTLR 4.5.3.

### PR DESCRIPTION
**Pull request by jdconrad**
As the title says.

### CODE REVIEW

**Comment by jdconrad** [comment]
Relates to https://github.com/elastic/elasticsearch/issues/26834

**Review by costin — APPROVED** [review]
LGTM.
Thanks for looking into it

**Comment by jdconrad** [comment]
@costin Sorry again for the delay.  Thanks for the review.  I'll check this in as soon as the CI passes.

**Comment by jdconrad** [comment]
@costin Will do the back port now, and then you should be good to go for upgrading your project.

**Pull request merged**
