### PR TITLE
Mute ESClientYamlSuiteTestCase

### PR DESCRIPTION
**Pull request by jan-elastic**

### CODE REVIEW

**Comment by jan-elastic** [comment]
@javanna Sorry, I copy/pasted the wrong bug URL. I fixed it here:
https://github.com/elastic/elasticsearch/pull/10

**Comment by jan-elastic** [comment]
there are multiple tests deriving from this test failing

at least:
- CcsCommonYamlTestSuiteIT
- RcsCcsCommonYamlTestSuiteIT

**Comment by jan-elastic** [comment]
if you think this PR mutes too much, let me know or feel free to revert or make it stricter

**Comment by javanna** [comment]
It mutes every single yaml test, in that the test method of the base class of yaml test IT is muted. That means thousands of tests. I will address this.

**Comment by javanna** [comment]
Opened #102666

**Pull request merged**
