### PR TITLE
Addition of new native ColdFusion (CFML) library.

### PR DESCRIPTION
**Pull request by lmajano**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by lmajano** [comment]
CLA has been signed

**Comment by nik9000** [comment]
Looks good. Me leaving this comment should trigger the CLA checker robot. If the CLA check doesn't pass I'll dig some more.

**Comment by lmajano** [comment]
Thanks

Luis Majano
CEO
Ortus Solutions, Corp
www.ortussolutions.com<http://www.ortussolutions.com>
P/F: 1-888-557-8057
________________________________

**Comment by nik9000** [comment]
@lmajano it looks like you signed the CLA with a corporate email address but used a personal one in the patch. This confuses the CLA checker. I poked it so your gmail address should also be good. My leaving this comment should cause it to pass now....

**Comment by nik9000** [comment]
Once more....

**Comment by nik9000** [comment]
Merged! Thanks @lmajano!

I should let you know that the pagination on https://www.forgebox.io doesn't seem to work. It gives 404 pages.

**Comment by lmajano** [comment]
Thanks will advice the developers.

Luis Majano
CEO
Ortus Solutions, Corp
www.ortussolutions.com<http://www.ortussolutions.com>
P/F: 1-888-557-8057
________________________________

**Pull request merged**
