### PR TITLE
Remove Blocking Transport APIs

### PR DESCRIPTION
**Pull request by original-brownbear**
* There is only a single spot in production code left that used the `submit` API to actually block on a transport action
   * Remove the submit APIs completely from prod. code, replaced the one spot it was used in by explicit waiting
   * Remove now unused `TransportFuture` interface and just flatten everything into `PlainTransportFuture`
   * Dry up related test logic a little

### CODE REVIEW

**Review by rjernst — APPROVED** [review]
LGTM. Do we need TransportFuture as an interface now or could PlainTransportFuture be collapsed into it as a followup?

**Comment by original-brownbear** [comment]
@rjernst thanks for taking a look!

> Do we need TransportFuture as an interface now or could PlainTransportFuture be collapsed into it as a followup?

I already did that here didn't I?  I just didn't rename `PlainTransportFuture` to `TransportFuture` because that turned out to be an additional ~200 lines of diff. I can do that in a follow up?

**Comment by original-brownbear** [comment]
Not backporting this to `7.x`, turns out there's a ton of uses of the blocking APIs there still that were only removed in `master`.

**Comment by rjernst** [comment]
Yes, the rename is what I meant, sorry for the confusion. A followup sounds good.

**Comment by original-brownbear** [comment]
@rjernst no worries, I opened https://github.com/elastic/elasticsearch/pull/45768 for the rename ... which turned out to be much shorter than I thought it would for some reason, my bad :)

**Pull request merged**
