### PR TITLE
Document removal of forced versioning for update API

### PR DESCRIPTION
**Pull request by moljac024**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by bleskes** [comment]
test this please

**Comment by moljac024** [comment]
I'm sorry but I'm not sure what it means to test documentation changes like this? Can you please elaborate a bit?

**Comment by imotov** [comment]
> I'm sorry but I'm not sure what it means to test documentation changes like this? Can you please elaborate a bit?

@moljac024 sorry, it wasn't meant for you. It was for a bot that automatically runs tests on PRs in this repo.

**Comment by bleskes** [comment]
thx @moljac024 . I merged this in.

**Pull request merged**
