### PR TITLE
[Docs] Fix common word repetitions

### PR DESCRIPTION
**Pull request by cbuescher**
Removing some commonly repeated words.

### CODE REVIEW

**Comment by cbuescher** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by cbuescher** [comment]
@elasticmachine run elasticsearch-ci/2

**Review by jrodewig — APPROVED** [review]
LGTM.

I generally stick to .asciidoc, but it appears the only changes to .java files are in comments.

**Comment by cbuescher** [comment]
> I generally stick to .asciidoc, but it appears the only changes to .java files are in comments.

Thanks, great you make an exception in this case ;-)

**Pull request merged**
