### PR TITLE
[DOCS] Add operator privileges to APIs and settings

### PR DESCRIPTION
**Pull request by jrodewig**
Notes required privileges for operator-only APIs and settings. Relates to #68964.

### CODE REVIEW

**Comment by jrodewig** [comment]
@elasticmachine update branch

**Comment by jrodewig** [comment]
@elasticmachine update branch

**Review by ywangd — APPROVED** [review]
LGTM Thanks @jrodewig 
I assume similar notes for `ml` settings will be handled separately?

**Comment by jrodewig** [comment]
Thanks @ywangd!

> I assume similar notes for `ml` settings will be handled separately?

Yes. @lcawl has already handled those with https://github.com/elastic/elasticsearch/pull/69766 and https://github.com/elastic/stack-docs/pull/1597

**Pull request merged**
