### PR TITLE
Optimize `routingNodes` variable in AddIncrementallyTests

### PR DESCRIPTION
**Pull request by boicehuang**
The `routingNodes` variable is unused. Replace `clusterState.getRoutingNodes()` with `routingNodes`.

### CODE REVIEW

**Review by nik9000 — APPROVED** [review]
That looks like what we intended to do, yeah.

@elasticmachine, run this please.

**Comment by nik9000** [comment]
> @elasticmachine, run this please.

Test this please.

**Comment by nik9000** [comment]
Thanks for opening this @boicehuang! It does look like that is what we meant to do in the first place. I'll get this in.

**Comment by nik9000** [comment]
@elasticmachine, update branch

**Comment by nik9000** [comment]
@elasticmachine update branch

**Comment by nik9000** [comment]
@boicehuang, could you merge master into your PR or [allow](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) me to?

**Comment by boicehuang** [comment]
Thanks, @nik9000. I have merged master into my PR.

**Comment by nik9000** [comment]
@elasticmachine, ok to test

**Comment by nik9000** [comment]
> Thanks, @nik9000. I have merged master into my PR.

That seems to have fixed the issue! I'll merge and backport.

**Comment by nik9000** [comment]
I've merged and backported! Thanks again @boicehuang!

**Pull request merged**
