### PR TITLE
Fix CachedBlobContainerIndexInputTests

### LINKED ISSUE #64215: CachedBlobContainerIndexInputTests.testRandomReads failure
**Build scan**: https://gradle-enterprise.elastic.co/s/tiqw5pjr4tiwk

**Repro line**:
```
./gradlew ':x-pack:plugin:searchable-snapshots:test' --tests "org.elasticsearch.index.store.cache.CachedBlobContainerIndexInputTests.testRandomReads" -Dtests.seed=9EFCEB28234D764F -Dtests.security.manager=true -Dtests.locale=en-AU -Dtests.timezone=Pacific/Auckland -Druntime.java=8
```

**Reproduces locally?**:
No.

**Applicable branches**:

At least 7.x, that is where it failed on #64160 

**Failure history**:

Looks like it only failed [once](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(_source),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:testRandomReads),sort:!(process.time-start,desc))), though there is also a failure of the test from September 3rd (looks like an unrelated failure).

**Failure excerpt**:

```
java.lang.AssertionError: All bytes should have been read from source	
Expected: <20522L>	
     but: was <20115L>
     at __randomizedtesting.SeedInfo.seed([9EFCEB28234D764F:ABFE49DBC9E1D265]:0)
     at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
     at org.junit.Assert.assertThat(Assert.java:956)
     at org.elasticsearch.index.store.cache.CachedBlobContainerIndexInputTests.testRandomReads(CachedBlobContainerIndexInputTests.java:150)
```

### PR DESCRIPTION
**Pull request by original-brownbear**
Closing the input stream happens on a separate thread
now that the `CacheFile` is implemented in a lock-free
fashion. If we only add up the counts on closing streams then we
need to wait on the async closes in the background.
I think the simplest solution is what this PR does and just add up the counts
as bytes are read.

Closes #64215

### CODE REVIEW

**Review by henningandersen — COMMENTED** [review]
I wonder if we should track both numbers (the interim read count and the bytes read and closed) in order to properly validate that close is always called. We could then do the assert that is there and also `assertBusy()` that the number of bytes read and subsequently closed also match up? Could also just add a closed counter.

Unless there is another test verifying that close is always caled.

**Comment by original-brownbear** [comment]
> Unless there is another test verifying that close is always called.

There sort of is. We have file leak listener tests for the cache files and all the stream inputs are opened through `try-with-resources` so technically it's impossible to leak an open stream past shutting down the thread-pool I suppose. That's why I figured I'd avoid adding more complexity through another busy assert. But I can add another counter if you want, can't hurt I guess => will do in a bit

**Comment by original-brownbear** [comment]
@henningandersen I pushed https://github.com/elastic/elasticsearch/pull/64239/commits/226e311d747699e3a38cfde80e3f62658a6ee204 to assert the closing works out fine :)

**Review by henningandersen — APPROVED** [review]
LGTM, thanks @original-brownbear

**Comment by original-brownbear** [comment]
Thanks Henning!

**Pull request merged**
