### PR TITLE
Handle deprecation header-AbstractUpgradeTestCase

### PR DESCRIPTION
**Pull request by jkakavas**
Resolves: #38395

### CODE REVIEW

**Review by danielmitterdorfer — APPROVED** [review]
LGTM

**Comment by jkakavas** [comment]
This failed because of https://github.com/elastic/elasticsearch/issues/38412 :(

**Comment by cbuescher** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by cbuescher** [comment]
@jkakavas sorry that I went ahead and merged this in, some backports on 6.x need this so I figured its best to get in once CI passed.

**Comment by jkakavas** [comment]
No worries ,glad you did ! I was left with the impression that the reverts
alpar did handled this this morning and i left for the evening without
seeing this through

**Pull request merged**
