### PR TITLE
[Geo] Integrate Lucene's LatLonShape (BKD Backed GeoShapes) as default `geo_shape` indexing approach

### PR DESCRIPTION
**Pull request by nknize**
This commit  exposes lucene's LatLonShape field as the default type in GeoShapeFieldMapper. To use the new indexing approach, simply set "type" : "geo_shape" in the mappings without setting any of the strategy, precision, tree_levels, or distance_error_pct parameters. Note the following when using the new indexing approach:
    
 * geo_shape query does not support querying by MULTIPOINT.
 * LINESTRING and MULTILINESTRING queries do not yet support WITHIN relation.
 * CONTAINS relation is not yet supported.
 * The tree, precision, tree_levels, distance_error_pct, and points_only parameters are deprecated.

### CODE REVIEW

**Comment by nknize** [comment]
This is just a cherry pick of dc4426132654fb4e4ff915c9db2ab959b0f91df3 and fefe7dfb9491e8fc3fce49ff5275d26fac173cc9 in order to backport to 6.6

**Comment by nknize** [comment]
looks like there was a CI failure unrelated to these changes. Documenting for posterity and retesting.

```
13:12:53 ERROR   0.76s | SecurityTribeTests.testTribeSettingNames <<< FAILURES!
13:12:53    > Throwable #1: java.lang.IllegalStateException: available processors value [1] did not match current value [3]
```

**Comment by nknize** [comment]
retest this please

**Review by imotov — APPROVED** [review]
LGTM

**Comment by nknize** [comment]
@elasticmachine run gradle build tests 2

**Comment by nknize** [comment]
@elasticmachine run gradle build tests 2

**Comment by jasontedor** [comment]
You will need to merge 6.6 into this branch to fix the failure that you’re trying to overcome here.

**Pull request merged**
