### PR TITLE
User Profile - remove feature flag

### PR DESCRIPTION
**Pull request by ywangd**
The feature flag is no longer necessary in the 8.4 release cycle. The
feature itself is still in beta.

### CODE REVIEW

**Comment by ywangd** [comment]
This PR is draft for now. It will be updated and merged once all 8.3-targeting docs PRs are merged.

**Comment by ywangd** [comment]
As discussed, I will update this PR once https://github.com/elastic/elasticsearch/pull/87360 is merged. Otherwise, it is ready to go.

**Comment by ywangd** [comment]
Failure is not related and tracked at https://github.com/elastic/elasticsearch/issues/87442

**Review by albertzaharovits — APPROVED** [review]
LGTM

**Comment by ywangd** [comment]
@elasticmachine update branch

**Comment by ywangd** [comment]
@elasticmachine update branch

**Pull request merged**
