### PR TITLE
Unmute esql-across-clusters yaml docs test

### LINKED ISSUE #115575: [CI] DocsClientYamlTestSuiteIT test {yaml=reference/esql/esql-across-clusters/line_197} failing
**Build Scans:**
- [elasticsearch-intake #11864 / part1](https://gradle-enterprise.elastic.co/s/rmv6qoss7e2rm)
- [elasticsearch-pull-request #37933 / part-1](https://gradle-enterprise.elastic.co/s/2drvdqap5zyyo)
- [elasticsearch-pull-request #37745 / part-1](https://gradle-enterprise.elastic.co/s/yyvge7cqzevqs)
- [elasticsearch-pull-request #37613 / part-1](https://gradle-enterprise.elastic.co/s/3lyjrzzeftieq)

**Reproduction Line:**
```
./gradlew ":docs:yamlRestTest" --tests "org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT.test {yaml=reference/esql/esql-across-clusters/line_197}" -Dtests.seed=A83A460BEE5D3720 -Dtests.locale=xog-Latn-UG -Dtests.timezone=Jamaica -Druntime.java=22
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(test%20%7Byaml%3Dreference%2Fesql%2Fesql-across-clusters%2Fline_197%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
org.elasticsearch.client.WarningFailureException: method [DELETE], host [http://127.0.0.1:40395], URI [*,-.ds-ilm-history-*,-.ds-.slm-history-*,-.ds-.watcher-history-*?expand_wildcards=open%2Cclosed%2Chidden], status line [HTTP/1.1 200 OK]
Warnings: [this request accesses system indices: [.async-search], but in a future major version, direct access to system indices will be prevented by default]
{"acknowledged":true}
```

**Issue Reasons:**
- [main] 4 failures in test test {yaml=reference/esql/esql-across-clusters/line_197} (0.6% fail rate in 640 executions)
- [main] 3 failures in step part-1 (1.0% fail rate in 293 executions)
- [main] 3 failures in pipeline elasticsearch-pull-request (0.9% fail rate in 316 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by quux00**
This test was fixed in earlier commits. Just unmuting in this PR.

Fixes https://github.com/elastic/elasticsearch/issues/115575

### CODE REVIEW

**Comment by quux00** [comment]
Note: this one does not need to be backported to 8.x, since that test is not muted in that branch.

**Comment by quux00** [comment]
buildkite test this

**Review by dnhatn — APPROVED** [review]

**Comment by quux00** [comment]
buildkite test this

**Review by ChrisHegarty — APPROVED** [review]

**Comment by quux00** [comment]
buildkite test this

**Pull request merged**
