### PR TITLE
Clarify when shard iterators get sorted

### PR DESCRIPTION
**Pull request by javanna**
Currently we have two ways to create a `GroupShardsIterator`: one that will re-sort the iterators based on their natural ordering, and another one that will leave them in their original order. This is currently done through two constructors, one that accepts a single argument which does the sorting, and another which accepts a second `boolean` argument to control whether sorting should happen or not. This second constructor is only called externally to disable the sorting.

By introducing a specific method to create a sorted shard iterator we clarify and make it easier to track when we do sort and when we do not as the iterators are externally sorted and should be kept as-is.

### CODE REVIEW

**Comment by javanna** [comment]
run elasticsearch-ci/default-distro

**Comment by javanna** [comment]
run elasticsearch-ci/bwc

**Comment by javanna** [comment]
run elasticsearch-ci/2

**Comment by javanna** [comment]
@elasticsearchmachine  update branch

**Review by jimczi — APPROVED** [review]
LGTM

**Comment by javanna** [comment]
thanks @jimczi

**Pull request merged**
