### PR TITLE
Minor Rearrangements in Snapshot Code

### PR DESCRIPTION
**Pull request by original-brownbear**
Inlining one trivial single-use method and extracting the
stale shard path blob calculation (this also allows for tackling a TODO in 
the cleanup method in parallel to the work on #46250) to make the diff with #46250
more manageable.

### CODE REVIEW

**Review by tlrx — APPROVED** [review]
LGTM

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/1

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/2

**Comment by original-brownbear** [comment]
Jenkins test this

**Comment by original-brownbear** [comment]
Jenkins test this

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/bwc
Jenkins run elasticsearch-ci/default-distro

**Pull request merged**
