### PR TITLE
Logging: Unify log rotation for index/search slow log

### PR DESCRIPTION
**Pull request by spinscale**
The existing log rotation configuration allowed the index
and search slow log to grow unbounded. This commit removes the
date based rotation and adds the same size based rotation, that
the depreciation log already has.

Tested this locally with logstash using the generator and the elasticsearch inputs and worked fine.

### CODE REVIEW

**Review by ywelsch — CHANGES_REQUESTED** [review]
The `slowlog.asciidoc` documentation needs to be updated, as it still refers to the old time-based policy.

I think @jasontedor should give this a look as well.

**Review by jasontedor — CHANGES_REQUESTED** [review]
The change itself LGTM, but I agree with @ywelsch that the docs need to updated too.

**Comment by spinscale** [comment]
good call. synced docs with the configuration file and saw that a few more lines needed fixing

**Review by jasontedor — COMMENTED** [review]
LGTM.

**Review by ywelsch — APPROVED** [review]
LGTM

**Pull request merged**
