### PR TITLE
Update getting-started.asciidoc

### PR DESCRIPTION
**Pull request by markwalkom**
Highlighted that you can change shard counts using `_shrink` and `_split`.

### CODE REVIEW

**Review by dadoonet — APPROVED** [review]

**Review by colings86 — CHANGES_REQUESTED** [review]
I think we need to be more careful with the wording here. This changes makes it looks very convenient and easy to change the number of shards on an existing index and so I am worried that users will think that they no longer need to think about how many shards to use before they create the index. In actuality you still need to think about this because changing the shards is not a trivial action and requires that you have a node which has enough free space for 2x the size of thee complete index.

**Review by colings86 — APPROVED** [review]
LGTM

**Comment by javanna** [comment]
retest this please

**Comment by javanna** [comment]
The build failure is totally unrelated, I am going to merge this in.

**Pull request merged**
