### PR TITLE
JDBC: Fix stackoverflow on getObject and timestamp conversion

### PR DESCRIPTION
**Pull request by astefan**
A fix for https://github.com/elastic/elasticsearch/issues/31734.
Another bug-fix for a StackOverFlow error in `getObject` method.

### CODE REVIEW

**Review by costin — CHANGES_REQUESTED** [review]
Could you add an explicit test for `getObject` as well (instead of `convertAsNative`) and another one that tests that the SO is not triggered anymore?

Also mark the PR for 7.x and 6.x as well. The SO might be serious enough to require backporting to 6.3...

**Review by nik9000 — APPROVED** [review]
Production code LGTM though I agree you should add a test for `getObject` before merging.

**Comment by astefan** [comment]
@costin I've addressed your review.

**Comment by astefan** [comment]
Backported to 6.x and 6.3 as well with the mention that on 6.3 only the bug-fixes themselves were backported (skipped the tests).

**Pull request merged**
