### PR TITLE
Reorder arguments to StepListener#whenComplete

### PR DESCRIPTION
**Pull request by DaveCTurner**
The `onResponse` argument is typically a large multi-line lambda which
triggers subsequent steps, whereas the `onError` argument is frequently
something short like `listener::onFailure`. I find the separation
between the call to `whenComplete` and the short `onError` argument to
be an obstruction to reading, particularly when calls are nested. I feel
like I am code that was in German written reading.

This commit reverses the order of these arguments to better suit my
taste.

### CODE REVIEW

**Comment by jasontedor** [comment]
I think this would be putting the `onResponse, onFailure` arguments in a different order than `ActionListener#wrap`, which might be a minor source of confusion?

**Comment by jasontedor** [comment]
In particular, this looks a little off:

https://github.com/elastic/elasticsearch/pull/68841/files#diff-abadbcca394cd3848455e3e1aa2cfbefac113c3900ab5ef119f58dddececd4eaR68-R69

I know that type checking etc. will prevent mistakes here, it just ends up reading weird to me. 😇

**Comment by DaveCTurner** [comment]
My argument was going to be that the `onFailure` argument to `ActionListener#wrap` isn't usually something short like `listener::onFailure` because we have `ActionListener#delegateFailure` (with the right order of arguments) to deal with that.

But then I looked, we do the same thing with `ActionListener` everywhere too :(

Maybe therefore the answer is to introduce `StepListener#delegateFailure`.

**Comment by jasontedor** [comment]
> Maybe therefore the answer is to introduce `StepListener#delegateFailure`.

I like that, that makes sense to me.

**Comment by DaveCTurner** [comment]
`StepListener` is no more, closing this.

**Pull request closed without merging**
