### PR TITLE
Remove reference to bats test

### LINKED ISSUE #60690: CI: Could not determine the dependencies of task ':qa:os:destructivePackagingTest'.
**Build scan**:
https://gradle-enterprise.elastic.co/s/xs3tglp6yzkzk

**Applicable branches**:
`master`. checking others.

**Failure history**:
Started Aug 4, 2020 1:03:30 AM
**Failure excerpt**:

```
13:07:51 > Task :buildSrc:build
13:08:06 build complete, generating: /var/lib/jenkins/workspace/elastic+elasticsearch+master+multijob+packaging-tests-unix-gcp/os/oraclelinux-7-packaging/build/210.tar.bz2
13:08:07 
13:08:07 FAILURE: Build failed with an exception.
13:08:07 
13:08:07 * What went wrong:
13:08:07 Could not determine the dependencies of task ':qa:os:destructivePackagingTest'.
13:08:07 > Task with path 'destructiveBatsTest.upgrade' not found in project ':qa:os'.
```

### PR DESCRIPTION
**Pull request by rjernst**
The packagingTest tasks run by CI (but not by PRs...) was still
refering to bats tasks. This commit removes those remaining references.

closes #60690

### CODE REVIEW

**Comment by rjernst** [comment]
@elasticmachine run elasticsearch-ci/packaging-windows

**Comment by rjernst** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by rjernst** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Review by mark-vieira — APPROVED** [review]
LGTM

**Comment by rjernst** [comment]
@elasticmachine run elasticsearch-ci/2

**Pull request merged**
