### PR TITLE
[DOCS] Flatten EQL syntax headings

### LINKED ISSUE #65487: EQL: documentation ease of use
Currently, our great EQL documentation is using a style that promotes sharing a big subject (for example, [EQL syntax reference](https://www.elastic.co/guide/en/elasticsearch/reference/master/eql-syntax.html#eql-syntax)) in a single, large page where all the sub-aspects (sub-chapters) are highlighted with bold characters ([Sequences](https://www.elastic.co/guide/en/elasticsearch/reference/master/eql-syntax.html#eql-sequences) is an example). But there are also sub sub-chapters (like the [until keyword](https://www.elastic.co/guide/en/elasticsearch/reference/master/eql-syntax.html#eql-until-keyword) from Sequences) which is also highlighted in the documentation page and has an anchor to it that can be shared and made easily accessible.

What I feel it's missing, from my point-of-view and looking at the documentation as a regular user, is an easier way of reaching certain sub sub-chapters. As an user looking for how to use `until` and what I can specify as values to `until` I'd have to go to EQL page by clicking on the right-hand side column that allows the docs reference browsing:

image

then assuming `until` is somewhere in `Syntax reference`:

image

then going to `Sequences` (since I already know `until` is about sequences):

image

But in the Sequences section (which is somewhere in the middle of a very large page about syntax) I'd have to scroll and try to pinpoint with my eyes something about `until`. When I found it, is somewhat easily visible, but not that much.

Having worked on the SQL documentation and, inevitably, comparing the two, I find the right-hand side of the reference documentation of great help in more easily browsing through sub-chapters and sub sub-chapters. For example (from SQL docs) - the right hand side has a tree like structure:

image

If I go to [Lexical Structure](https://www.elastic.co/guide/en/elasticsearch/reference/master/sql-lexical-structure.html), the page that opens has on the top right hand side "On this page" (just like EQL), but what's different in SQL page's case is what I believe is a sub sub-chapter from EQL docs (for example the [Special characters](https://www.elastic.co/guide/en/elasticsearch/reference/master/sql-lexical-structure.html#sql-syntax-special-chars) sub sub-chapter).

image

What I would have loved to see in EQL's case is something similar to SQL's documentation:
- a more detailed tree structure on the right-hand side of the page where the Reference documentation shows all the major sections/projects. For example, we could expand "Syntax reference" and have there the "Sequences" section.
- when clicking on Sequences from the right-hand side tree, the page that opens has only Sequences section in it
- the Sequences page has at the top right-hand side of the page the "On this page" summary where I can find, among others, the `until` sub sub-chapter. I can click on it and it takes me right to the `until` sub-section.

### PR DESCRIPTION
**Pull request by jrodewig**
Changes several H4s to H3s to populate the on-page nav. While the hierarchy becomes less clear, this better populates the on-page navigation.

Closes #65487

### Before:
Screen Shot 2020-11-25 at 8 59 35 AM

### After:
Screen Shot 2020-11-25 at 8 37 50 AM

### CODE REVIEW

**Review by astefan — APPROVED** [review]
LGTM.
Thank you for sharing the reasons behind the initial choice (one single page vs. smaller, per subject page) and I think the solution in this PR is an acceptable compromise.

**Review by lockewritesdocs — APPROVED** [review]
👍 on these changes. Looking forward to the new doc system so that the main navigation is flattened!

**Comment by jrodewig** [comment]
Thanks @astefan @lockewritesdocs!

**Comment by costin** [comment]
👍 to the new navigation

**Pull request merged**
