### PR TITLE
Fix typo in rest-api-spec capabilities documentation

### PR DESCRIPTION
**Pull request by dakrone**

### CODE REVIEW

**Comment by prdoyle** [comment]
Just for the record... why is the plural correct?

**Comment by prdoyle** [comment]
Oh I found it. Tons of examples in the codebase.

**Review by prdoyle — APPROVED** [review]

**Comment by prdoyle** [comment]
Here it is...

https://github.com/elastic/elasticsearch/blob/3cbb5264f5e7a2cc5d85b27b1ec72834ef85bcfc/test/yaml-rest-runner/src/main/java/org/elasticsearch/test/rest/yaml/section/PrerequisiteSection.java#L434

**Comment by dakrone** [comment]
@elasticmachine update branch

**Comment by dakrone** [comment]
@elasticmachine update branch

**Comment by dakrone** [comment]
@elasticmachine update branch

**Pull request merged**
