### PR TITLE
add getBigDecimal() [proposed Label]:Search/SQL

### LINKED ISSUE #43806: SQL: implement get/setBigDecimal for JDBC
At the moment, these two methods are not implemented in the ES SQL driver, but would be good to have them.

### PR DESCRIPTION
**Pull request by FreshOrangeXC**
Closes #43806

### CODE REVIEW

**Comment by FreshOrangeXC** [comment]
@elasticmachine ok to test

**Comment by FreshOrangeXC** [comment]
@astefan Is it ok?

**Review by costin — CHANGES_REQUESTED** [review]
Thank you for the contribution.

I've left a number of comments regarding validating parameters and using the same formatting as the rest of the file.
Lastly the tests are good however not comprehensive - testing all the various types against a BigDecimal would have spotted the incorrect casting so please add that in (see the rest of the tests).
It's the corner cases that we have to watch out for.

**Comment by FreshOrangeXC** [comment]
I get it. I will modify it.

**Comment by astefan** [comment]
@FreshOrangeXC did you get the chance to have another look at this PR and make the changes @costin suggested?

**Comment by FreshOrangeXC** [comment]
I am so sorry. I am so busy that I may not finish this PR in time. If I have time. I will finish it.

**Comment by astefan** [comment]
@FreshOrangeXC we really appreciate the effort, but it would greatly help the issues prioritization if you could give us an estimate when you believe you can finish this PR.

**Comment by matriv** [comment]
@FreshOrangeXC  any updates here?

**Comment by matriv** [comment]
@FreshOrangeXC
Do you think you have time to finish up the work on this?

**Comment by matriv** [comment]
@elastic/es-ql

**Comment by bpintea** [comment]
@FreshOrangeXC, we'll close this PR as stale, but still thanks for your initial contribution.

**Pull request closed without merging**
