### PR TITLE
Update jakarta mail dependency to 1.6.4

### PR DESCRIPTION
**Pull request by spinscale**
This one contains a few small bugfixes, see https://eclipse-ee4j.github.io/mail/docs/CHANGES.txt

### CODE REVIEW

**Review by jakelandis — APPROVED** [review]
LGTM

**Comment by spinscale** [comment]
any objections against merging this into master and 7x?

**Comment by spinscale** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by jakelandis** [comment]
> any objections against merging this into master and 7x?

Nope. merge away.

**Pull request merged**
