### PR TITLE
Refactor SamlAuthenticationIT

### LINKED ISSUE #44410: [CI] SamlAuthenticationIT.testLoginUserWithSamlRoleMapping failure
SamlAuthenticatorIT. testLoginUserWithSamlRoleMapping failed on
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.8+EAR/27/console

```
11:31:36 FAILURE 3.07s | SamlAuthenticationIT.testLoginUserWithSamlRoleMapping <<< FAILURES!
11:31:36    > Throwable #1: java.lang.AssertionError: Unexpected HTTP Response status: HTTP/1.1 503 Service Unavailable
11:31:36    > Expected: <200>
11:31:36    >      but: was <503>
11:31:36    > 	at __randomizedtesting.SeedInfo.seed([43BF4801CCD3AC0E:CC50FE2BD895C0D3]:0)
11:31:36    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
11:31:36    > 	at org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT.assertHttpOk(SamlAuthenticationIT.java:594)
11:31:36    > 	at org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT.lambda$goToLoginPage$1(SamlAuthenticationIT.java:353)
11:31:36    > 	at org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT.execute(SamlAuthenticationIT.java:502)
11:31:36    > 	at org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT.goToLoginPage(SamlAuthenticationIT.java:352)
11:31:36    > 	at org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT.loginViaSaml(SamlAuthenticationIT.java:263)
11:31:36    > 	at org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT.testLoginUserWithSamlRoleMapping(SamlAuthenticationIT.java:245)
11:31:36    > 	at java.lang.Thread.run(Thread.java:748)
```
Locally could not reproduce on 6.8:
```
./gradlew :x-pack:qa:saml-idp-tests:integTestRunner -Dtests.seed=43BF4801CCD3AC0E -Dtests.class=org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT -Dtests.method="testLoginUserWithSamlRoleMapping" -Dtests.security.manager=true -Dtests.locale=zh -Dtests.timezone=US/Hawaii -Dcompiler.java=12 -Druntime.java=8
```

Not muting for the moment as very few failures are noticed and only on 6.8 branch

### PR DESCRIPTION
**Pull request by jkakavas**
Refactor the tests to not require a mock HTTP Server. This has been
the cause of flakiness and removing it doesn't affect the logical
coverage of this suite. The "fake UI" is now simulated by an
http client that makes the necessary requests to Elasticsearch APIs.

resolves: https://github.com/elastic/elasticsearch/issues/44410

### CODE REVIEW

**Comment by jkakavas** [comment]
Tim, I don't feel _that_ strongly in favor of these changes. This grew out of frustration of not being able to reproduce and debug https://github.com/elastic/elasticsearch/issues/44410 locally and I think this is a good enough reason for these changes. I think that we don't miss anything by not having an HTTP server component in these tests ( similar to the OpenIdConnectAuthenticationIT ), but happy to discuss

**Comment by tvernum** [comment]
I think this approach is fine. I think it made sense when we started to have a HTTP server to more closely mimic Kibana, because part of the purpose of the test was to verify that you could write a HTTP front end that did the right things (calling the APIs directly avoids the need for things like cookies, and that could have been a blind spot for us).
Given the stability of these APIs, I think it's reasonable to accept that the UI part is adequately tested by Kibana and take a more holistic "stack testing" view rather than requiring that ES-CI test every tiny detail itself.

**Comment by jkakavas** [comment]
@elasticmachine run elasticsearch-ci/default-distro

**Comment by jkakavas** [comment]
@elasticmachine update branch

**Comment by jkakavas** [comment]
> I think this approach is fine.

@tvernum I assume you still want to take a look at the changes themselves, thus not merging

**Comment by tvernum** [comment]
>  I assume you still want to take a look at the changes themselves

It's not a life-goal, but yes.

**Comment by jkakavas** [comment]
> It's not a life-goal, but yes.

But why? I bet there are tons of people that are waiting in line to review my (open)SAML poetry in this PR

**Comment by jkakavas** [comment]
@tvernum no rush but pinging you as you asked

**Review by tvernum — APPROVED** [review]

**Comment by jkakavas** [comment]
@elasticmachine test this please as it's been a while

**Comment by jkakavas** [comment]
@elasticmachine update branch

**Pull request merged**
