### PR TITLE
Explicitly reject duplicate data paths

### PR DESCRIPTION
**Pull request by jasontedor**
Duplicate data paths already fail to work because we would attempt to take out a node lock on the directory a second time which will fail after the first lock attempt succeeds. However, how this failure manifests is not apparent at all and is quite difficult to debug. Instead, we should explicitly reject duplicate data paths to make the failure cause more obvious.

### CODE REVIEW

**Review by abeyad — APPROVED** [review]
LGTM, though I wonder if we could easily add a test in `EvilSecurityTests` for this scenario?

**Review by nik9000 — APPROVED** [review]
LGTM as well. Some kind of test would be nice though for something like this I don't find it a huge deal.

**Review by nik9000 — APPROVED** [review]
:heart: for test

**Comment by jasontedor** [comment]
@abeyad I pushed a test.

**Review by abeyad — APPROVED** [review]
Thanks @jasontedor

**Comment by jasontedor** [comment]
Thanks @abeyad and @nik9000.

**Pull request merged**
