### PR TITLE
Re-enable HeapAttack tests

### PR DESCRIPTION
**Pull request by dnhatn**
This PR re-enables two more heap attack tests. I have run more than 100 iterations with these tests without hitting any failures.

### CODE REVIEW

**Comment by dnhatn** [comment]
test this please

**Comment by dnhatn** [comment]
test this please

**Comment by dnhatn** [comment]
test this please

**Review by alex-spies — APPROVED** [review]
Nice! Let's go!

**Review by bpintea — APPROVED** [review]

**Comment by dnhatn** [comment]
@alex-spies @bpintea Thanks for reviews.

**Pull request merged**
