### PR TITLE
Remove useless logger instance from CircuitBreakerService

### PR DESCRIPTION
**Pull request by asdf2014**
Related to https://github.com/elastic/elasticsearch/pull/35560

### CODE REVIEW

**Review by cbuescher — APPROVED** [review]
LGTM

**Comment by cbuescher** [comment]
@elasticmachine test this please

**Comment by asdf2014** [comment]
Hi, @cbuescher . Can the PR be merged?

**Comment by cbuescher** [comment]
@asdf2014 thanks for the ping, I will need to get a clean CI run first
@elasticmachine update branch

**Comment by cbuescher** [comment]
@elasticmachine update branch

**Comment by cbuescher** [comment]
@elasticmachine test this please

**Pull request merged**
