### PR TITLE
Add migrate to data tiers API

### PR DESCRIPTION
**Pull request by andreidan**
This adds the API to expose the service for migrating the elasticsearch
abstractions (indices, ILM policies and an optional legacy template to
delete) to data tiers routing allocation (away from custom node attributes).
The details for how the migration is working are specified in https://github.com/elastic/elasticsearch/pull/73689

The API is 
```
POST /_ilm/migrate_to_data_tiers
{
  "legacy_template_to_delete": "template_name",
  "node_attribute": "data"
}
```

The response will contain the name of the deleted legacy index template
(if any was deleted), a list of ILM policies and a list of indices names containing
the policies and indices that were migrated.
```
{
  "removed_legacy_template":"catch-all-temaplte",
  "migrated_ilm_policies":["policy-one","policy-two"],
  "migrated_indices":["logs-000001","indexwithdatawarmrouting",".ds-.slm-history-5-2021.04.22-000002"]
}
```
Relates to #73154

### CODE REVIEW

**Comment by andreidan** [comment]
@elasticmachine update branch

**Comment by andreidan** [comment]
@elasticmachine run elasticsearch-ci/part-2

**Comment by sethmlarson** [comment]
Would this API be better suited in a namespace? Since it appears to be documented nearby ILM APIs perhaps the `ilm` namespace is a good choice (despite of course making changes to indices/templates as well)?

**Comment by jethr0null** [comment]
@dakrone @andreidan @sajjadwahmed could you please help us to understand the desired UX/user flows for this change (especially as it relates to any requested UI updates)?

**Review by dakrone — APPROVED** [review]
This LGTM, thanks for working on it Andrei. I do think this should be nested within the `/_ilm/` namespace, so `POST /_ilm/migrate_to_data_tiers`, as I think it fits best there rather than a top-level API. What do you think?

**Comment by dakrone** [comment]
> could you please help us to understand the desired UX/user flows for this change (especially as it relates to any requested UI updates)?

I don't think we currently have plans to expose this as part of the UI (please correct me if I'm mistaken @andreidan), but this would generally be something invoked as a one-off by an administrator or at the behest of support to help migrate without having to manually do the migration.

**Comment by andreidan** [comment]
@dakrone thanks for the review. Nested API under the `/_ilm/` namespace. The API now is `_ilm/migrate_to_data_tiers`

**Pull request merged**
