### PR TITLE
Reduce default Docker image size in 7.x

### PR DESCRIPTION
**Pull request by pugnascotia**
The `centos:8` image hasn't been updated for a while, and now the image
layer for updating it via `yum` is larger than the base image. Address
this by adopting the strategy for 8.0, where we build a custom base
image from `centos:8` and use that instead. The implementation here
differs in that `yum` is still available in the custom image, making it
more like the CentOS image, and therefore less breaking than the 8.0
changes.

Before: 1.04GB
After: 806MB

### CODE REVIEW

**Comment by pugnascotia** [comment]
Also FYI @mieciu

**Review by mieciu — APPROVED** [review]
A non-binding **LGTM** from my side 🙃 Thanks for the heads up!

**Review by mark-vieira — APPROVED** [review]
:+1: 

Is basically the only difference between `7.x` and `master` now is that the former additionally includes `yum`?

**Comment by pugnascotia** [comment]
@mark-vieira Kind of - we don't build a static `curl` either, but `7.x` and `master` are more closely aligned now.

**Comment by pugnascotia** [comment]
@mieciu I've merged this PR, can you confirm that I haven't broken Cloud?

**Pull request merged**
