### PR TITLE
[ML] Add Streaming Inference spec

### PR DESCRIPTION
**Pull request by prwhelan**
API for `/_inference/{task_type}/{inference_id}/_stream` and `/_inference/{inference_id}/_stream`

Request is `application/json`
Response is `text/event-stream`

### CODE REVIEW

**Review by davidkyle — APPROVED** [review]
LGTM

**Comment by prwhelan** [comment]
@elasticmachine update branch

**Comment by prwhelan** [comment]
@elasticmachine update branch

**Comment by prwhelan** [comment]
@elasticmachine update branch

**Comment by JoshMock** [comment]
@prwhelan Is a doc going to be created for this? The URL you added to the spec, `https://www.elastic.co/guide/en/elasticsearch/reference/master/post-stream-inference-api.html`, is a broken link right now, causing [a code-generation PR fail](https://github.com/elastic/elasticsearch-js/pull/2384) for the JavaScript client. Not super urgent, just curious if there's a timeline for when that will be fixed.

**Comment by prwhelan** [comment]
> @prwhelan Is a doc going to be created for this? The URL you added to the spec, `https://www.elastic.co/guide/en/elasticsearch/reference/master/post-stream-inference-api.html`, is a broken link right now, causing [a code-generation PR fail](https://github.com/elastic/elasticsearch-js/pull/2384) for the JavaScript client. Not super urgent, just curious if there's a timeline for when that will be fixed.

It is being created as part of our 8.16 doc updates - is there a way I can omit this link or otherwise unblock the codegen PR until that happens?

**Comment by JoshMock** [comment]
I'll keep an eye for the doc to be added, and if it holds up codegen much longer I can put in a temporary exception to skip over it.

**Pull request merged**
