### PR TITLE
add BytesRefStreamOutput

### PR DESCRIPTION
**Pull request by hendrikmuhs**
add StreamOutput that writes into BytesRef(Builder) that allows creating ByteRefs in situ, avoiding extra allocations.

relates #83055

### CODE REVIEW

**Review by grcevski — COMMENTED** [review]
Hi @hendrikmuhs, is there a particular use case within the code that we can utilize this new class at the moment, or is this a pre-requisite for a follow-up PR. It would be nice to link this class to an actual usage, otherwise it's just unused code.

**Comment by hendrikmuhs** [comment]
@grcevski 

> Hi @hendrikmuhs, is there a particular use case within the code that we can utilize this new class at the moment, or is this a pre-requisite for a follow-up PR. It would be nice to link this class to an actual usage, otherwise it's just unused code.

yes, the PR that this is spawned from is linked in the 1st message:

> relates https://github.com/elastic/elasticsearch/pull/83055

The concrete class is `HashBasedTransactionStore`: https://github.com/elastic/elasticsearch/pull/83055/files#diff-2bafc7b4471036ef9b98fbc6e0bc9c4912ebed163b360784c90011fa282abda7R84

**Comment by grcevski** [comment]
> @grcevski
> 
> > Hi @hendrikmuhs, is there a particular use case within the code that we can utilize this new class at the moment, or is this a pre-requisite for a follow-up PR. It would be nice to link this class to an actual usage, otherwise it's just unused code.
> 
> yes, the PR that this is spawned from is linked in the 1st message:
> 
> > relates #83055
> 
> The concrete class is `HashBasedTransactionStore`: https://github.com/elastic/elasticsearch/pull/83055/files#diff-2bafc7b4471036ef9b98fbc6e0bc9c4912ebed163b360784c90011fa282abda7R84

Ah sorry, I missed that.

**Review by grcevski — APPROVED** [review]
LGTM! I just left two small remarks.

**Comment by hendrikmuhs** [comment]
@elasticmachine update branch

**Pull request merged**
