### PR TITLE
[DOCS] Small fixes for the 'Installing Elasticsearch' page

### LINKED ISSUE #882: Small fixes for Installing Elasticsearch page
Not specific to this repo, but this seems a good enough place to park this.

Chris in this comment had the following suggestions for the [Installing Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/install-elasticsearch.html) page:

>I'm curious if anyone wants to revise the "Self-managed Elasticsearch options" section? I noticed the following:
> - We list different options but link to only some of them
> - Some links point to reference-like content, while others point to tutorial-like content
> - One tutorial targets local development, while the other seems more oriented to production or production-like environments
>
>There is an opportunity here to improve how we are presenting the options and resources that describe them.

### PR DESCRIPTION
**Pull request by kilfoyle**
This addresses a few items that Chris mentioned in a [comment](https://github.com/elastic/elasticsearch/pull/105034#pullrequestreview-1857602315) below with regard to the [Installing Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/install-elasticsearch.html) page, and also adds a link on that page, pointing to a new on-prem install tutorial.

Preview is [here](https://elasticsearch_105034.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/install-elasticsearch.html).

Closes: https://github.com/elastic/ingest-docs/issues/882

### CODE REVIEW

**Review by chriscressman — COMMENTED** [review]
Thanks for adding this David.

I'm fine with merging this as is, but I'm curious if anyone wants to revise the "Self-managed Elasticsearch options" section? I noticed the following:

- We list different options but link to only some of them
- Some links point to reference-like content, while others point to tutorial-like content
- One tutorial targets local development, while the other seems more oriented to production or production-like environments

There is an opportunity here to improve how we are presenting the options and resources that describe them.

cc @leemthompo

**Comment by kilfoyle** [comment]
I agree, Chris!

  - It occurs to me that the tutorial link I'm adding applies only to package installs, so I pushed a commit that would move the link to the bottom of the "Elasticsearch install packages" section. Maybe that will make the "Self-managed Elasticsearch options" section a bit less confusing.

 - Also, to your points, I think part of what's confusing is that Docker is described as a different install option, yet it's one of the items listed under "Elasticsearch install packages". Perhaps it would be clearer if we separate the "Elasticsearch install packages" section of the page into two sections, like this:
      - Elasticsearch install packages
           - Linux TAR/GZ
           - Windows ZIP
           - DEB
           - RPM
      - Elasticsearch Docker images
          - Docker

Then, the three "Self-managed Elasticsearch options" could be:
 - Run Elasticsearch on any [Linux, MacOS, or Windows machine](pretend.link).
 - Run Elasticsearch in a [Docker container](pretend.link).
 - Set up and manage Elasticsearch, Kibana, Elastic Agent, and the rest of the Elastic Stack on Kubernetes with [Elastic Cloud on Kubernetes](link).

The top two links are just pointing to further down in the page, but at least there's now a correspondence between the install options and the page structure. And the tutorial link is in a completely separate place, so it's not competing with the reference content. :-)

**Comment by leemthompo** [comment]
@kilfoyle I think your second commit and your suggestions make a lot of sense. If those changes are something you're happy to do in this PR, I approve, but if you're caught for time I can create an issue and put it in the backlog. Thanks!

**Comment by kilfoyle** [comment]
Thank you both! The changes are in the latest commit. The [preview page](https://elasticsearch_105034.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/install-elasticsearch.html) should refresh after the CI checks have rerun.

**Review by leemthompo — APPROVED** [review]
LGTM! Thanks @kilfoyle

**Comment by kilfoyle** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.12|[](https://github.com/elastic/elasticsearch/pull/105145)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
