### PR TITLE
Remove PR 41491 from release notes

### PR DESCRIPTION
**Pull request by hendrikmuhs**
PR 41491 hasn't been merged into 7.2 but got closed and superseded by #41800 (merged via feature branch merge into 7.3)

### CODE REVIEW

**Review by droberts195 — APPROVED** [review]
LGTM

**Comment by lcawl** [comment]
FYI I cherry-picked this change into the 7.2 release notes in 7.3 and 7.x branches too.  Thanks for catching this, @hendrikmuhs

**Comment by jrodewig** [comment]
Thank you @lcawl!

**Comment by hendrikmuhs** [comment]
Thanks @lcawl and @jrodewig ! I did not manage to merge/backport yesterday

**Pull request merged**
