### PR TITLE
[DOCS] Change "p0" to "yaml" in example command

### PR DESCRIPTION
**Pull request by nilanshu96**
This PR resolves the issue [78631](https://github.com/elastic/elasticsearch/issues/78631)

### CODE REVIEW

**Comment by jrodewig** [comment]
Thanks for the PR @nilanshu96. Please sign the [contributor agreement](https://www.elastic.co/contributor-agreement) using the same email address used in your commit.

You can find that email address here:
https://github.com/elastic/elasticsearch/commit/93f958b279fa7ca6e82c0725427da5fdb2921d21.patch

Once that's signed, I'll get this change merged in.

**Comment by nilanshu96** [comment]
@jrodewig Thanks for the info. I've signed the agreement again with the correct email id this time.

**Comment by jrodewig** [comment]
@elasticmachine ok to test

**Review by jrodewig — APPROVED** [review]
LGTM. Thanks @nilanshu96. I'll merge this in once the CI passes.

**Comment by nilanshu96** [comment]
Thank You @jrodewig !

**Pull request merged**
