### PR TITLE
Add 6.6.0 version to master

### PR DESCRIPTION
**Pull request by tlrx**
This commit adds the 6.6.0 version constant to the master branch, and
adapts the VersionTests.

### CODE REVIEW

**Comment by atorok** [comment]
@tlrx I think we also need to update `buildSrc/version.properties`

**Review by alpar-t — APPROVED** [review]

**Comment by tlrx** [comment]
@elasticmachine test this please

**Comment by tlrx** [comment]
@elasticmachine test this please

**Comment by tlrx** [comment]
Thanks @atorok !

**Pull request merged**
