### PR TITLE
Avoid routing loops in `TransportMasterNodeAction`

### PR DESCRIPTION
**Pull request by DaveCTurner**
Relates #102351

### CODE REVIEW

**Comment by DaveCTurner** [comment]
Oh this doesn't work at all!

**Comment by DaveCTurner** [comment]
The shutdown API tests won't work with this until https://github.com/elastic/elasticsearch/pull/108850 is merged.

**Comment by DaveCTurner** [comment]
Thanks for your work on the test @nicktindall; I made a few cosmetic changes but overall it's as you wrote it.

**Review by nicktindall — APPROVED** [review]
It seems less than ideal that we need the shims (`TermOverridingMasterNodeRequest` and `TermOverridingStreamOutput`). But I get that they allow
- immutable `TransportMasterNodeRequest`
- augmentation of the cluster state version at the moment of forwarding

And I can't think of a nicer way to achieve that. I hope there are good tests around any logic that depends on specific request types.

LGTM

**Pull request merged**
