### PR TITLE
scripted_metric _agg parameter disappears if params are provided

### LINKED ISSUE #19768: scripted_metric _agg parameter disappears if params are provided
When running a `scripted_metric` aggregation (in 2.3.x and 5.0.0-alpha4), if the user needs to specify some parameters in the  `params` section, the implicit `_agg` hashmap disappears.

When running the following dummy query:

```
POST index/type/_search
{
  "size": 0,
  "aggs": {
    "testAgg": {
      "scripted_metric": {
        "params": {
          "param1": 10,
          "param2": 20
        },
        "init_script": "_agg['max'] = []",
        "map_script": ";",
        "combine_script": ";",
        "reduce_script": ";"
      }
    }
  }
}
```

One gets an error stating  `No such property: _agg for class: b0b7ce0d2dbb5254a703a6f4d048654c3f84857b`. There are obviously no errors without the `params` section.

In order for this to work, one needs to re-specify the `_agg` implicit parameter in the `params` section like this:

```
POST index/type/_search
{
  "size": 0,
  "aggs": {
    "testAgg": {
      "scripted_metric": {
        "params": {
          "_agg": {},
          "param1": 10,
          "param2": 20
        },
        "init_script": "_agg['max'] = []",
        "map_script": ";",
        "combine_script": ";",
        "reduce_script": ";"
      }
    }
  }
}
```

I'm not sure if this is done on purpose, but it feels a bit counterintuitive. The [official documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-scripted-metric-aggregation.html#_other_parameters) (see below) states that `_agg` is an implicit hashmap, but doesn't state that `_agg` needs to be explicitly re-defined if other parameters are defined in `params` .

> If this is not specified, the default is the equivalent of providing:
> 
> ```
> "params" : {
>    "_agg" : {}
> }
> ```

I think this could be easily fixed by modifying [`ScriptedMetricAggregatorFactory.createInternal()`](https://github.com/elastic/elasticsearch/blob/0f00c14afc8428a2a72c0b766d2171029dc8f6e1/core/src/main/java/org/elasticsearch/search/aggregations/metrics/scripted/ScriptedMetricAggregatorFactory.java#L64-L70) like this:

```
    Map<String, Object> params = this.params;
    if (params != null) {
        params = deepCopyParams(params, context.searchContext());
    } else {
        params = new HashMap<>();
    }
    if (!params.containsKey("_agg")) {
        params.put("_agg", new HashMap<String, Object>());
    }
```

Note: If this is deemed worthy, I can gladly submit a PR.

### PR DESCRIPTION
**Pull request by reeselevine**
A follow up to @consulthys's PR #19863, fixes the test so the build passes.
Closes: #19768

### CODE REVIEW

**Comment by karmi** [comment]
Hi @reeselevine, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/elasticsearch/pull/27159.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by reeselevine** [comment]
Hi @karmi I added the email I used in my commit to my Github profile, let me know if that worked. Thanks!

**Comment by colings86** [comment]
jenkins test this please

**Comment by jasontedor** [comment]
retest this please

**Comment by colings86** [comment]
@reeselevine thanks for this PR, the change looks good and the build passes so I'll get this merged soon. Thank you for the contribution

**Pull request merged**
