### PR TITLE
[8.15] Use CLDR locale provider on JDK 23 (#112544)

### PR DESCRIPTION
**Pull request by thecoop**
Backport #110222 to 8.15

### CODE REVIEW

**Comment by thecoop** [comment]
@elasticmachine update branch

**Comment by mark-vieira** [comment]
@thecoop @rjernst although we don't intend to bump the bundled JDK on 7.17 do we still intend to _support_ Java 23 there? Does this need to be backported?

**Comment by thecoop** [comment]
Yes, as part of the move to CLDR, we give users the option to run 7.17.25+ and 8.15.2+ on a supported version of the JDK once JDK 23 is released

**Comment by mark-vieira** [comment]
That would require these changes to be backported to 7.17, yes? Has that been done?

**Comment by thecoop** [comment]
See https://github.com/elastic/elasticsearch/pull/112544

**Comment by mark-vieira** [comment]
Missed that. Thanks!

**Pull request merged**
