### PR TITLE
allow dynamic template deletion by defining an empty template (based on master)

### PR DESCRIPTION
**Pull request by salyh**
allow dynamic template deletion by defining an empty template - TESTS FAIL due to improper handling of mergeresult simulation. See https://github.com/elastic/elasticsearch/pull/11677#issuecomment-121566538

### CODE REVIEW

**Comment by jpountz** [comment]
Hi @salyh , I just had a look and removal does not work because empty templates are lost during serialization. I tried to comment out the `nonEmptyTemplatePresent` logic in `RootObjectMapper.doXContent` and it makes removal work but now `testAddEmtpy` fails. :)

**Comment by jpountz** [comment]
I guess the issue here is that we should not handle mappings and mappings updates differently. So maybe we should merge empty templates like any regular template in the merge method and just make sure to consider empty templates as non-existing in `findTemplate`. Said otherwise, putting an empty template would not remove existing templates but just deactivate them?

**Comment by clintongormley** [comment]
Hi @salyh 

Are you still interested in working on this?

**Comment by salyh** [comment]
if its still valueable of course

**Comment by dakrone** [comment]
Hi @salyh, would you be willing to make the changes that @jpountz suggested and update this PR?

**Comment by dakrone** [comment]
Closing this with no feedback

**Pull request closed without merging**
