### PR TITLE
[ML] Handle empty percentile results

### LINKED ISSUE #116013: [ML] no_such_element_exception when percentiles aggregation are missing
If tdigest or hdr percentile aggregation is used in an ML Anomaly Detection job, a no_such_element_exception is returned when there is no data returned in the percentiles bucket.

```
{
"name": "Error",
"request": {},
"response": {},
"body": {
"statusCode": 500,
"error": "Internal Server Error",
"message": "[no_such_element_exception\n\tRoot cause[s:\n\t\tno_such_element_exception](file:///s:/n/t/tno_such_element_exception): null]: null"
}
}
```

```
java.util.NoSuchElementException
	at java.util.Collections$EmptyIterator.next(Collections.java:4532) ~[?:?]
	at org.elasticsearch.xpack.ml.datafeed.extractor.aggregation.AggregationToJsonProcessor.processPercentiles(AggregationToJsonProcessor.java:412)
	at org.elasticsearch.xpack.ml.datafeed.extractor.aggregation.AggregationToJsonProcessor.processLeaf(AggregationToJsonProcessor.java:382)
	at org.elasticsearch.xpack.ml.datafeed.extractor.aggregation.AggregationToJsonProcessor.processAggs(AggregationToJsonProcessor.java:158)
	at org.elasticsearch.xpack.ml.datafeed.extractor.aggregation.AggregationToJsonProcessor.processDateHistogram(AggregationToJsonProcessor.java:235)
	at org.elasticsearch.xpack.ml.datafeed.extractor.aggregation.AggregationToJsonProcessor.processAggs(AggregationToJsonProcessor.java:169)
	at org.elasticsearch.xpack.ml.datafeed.extractor.aggregation.AggregationToJsonProcessor.process(AggregationToJsonProcessor.java:94)
	at org.elasticsearch.xpack.ml.datafeed.extractor.aggregation.AggregationToJsonProcessorTests.aggToString(AggregationToJsonProcessorTests.java:706)
	at org.elasticsearch.xpack.ml.datafeed.extractor.aggregation.AggregationToJsonProcessorTests.aggToString(AggregationToJsonProcessorTests.java:693)
	at org.elasticsearch.xpack.ml.datafeed.extractor.aggregation.AggregationToJsonProcessorTests.testProcessGivenEmptyPercentiles(AggregationToJsonProcessorTests.java:513)
```

### PR DESCRIPTION
**Pull request by prwhelan**
Do not add the leaf node if the percentiles bucket is empty.

Fix #116013

### CODE REVIEW

**Comment by prwhelan** [comment]
@elasticmachine update branch

**Comment by prwhelan** [comment]
@elasticmachine update branch

**Review by maxhniebergall — APPROVED** [review]
LGTM

**Review by davidkyle — APPROVED** [review]
LGTM

**Comment by prwhelan** [comment]
@elasticmachine update branch

**Pull request merged**
