### PR TITLE
SQL: Make a single JDBC driver jar

### LINKED ISSUE #29856: SQL: Make the JDBC driver a single JAR again
*Original comment by @imotov:*

As part of LINK REDACTED I had to split JDBC driver into several JARs and remove shading. We need to figure out how to merge these JARs back into a single JAR distribution while removing extra dependencies that are not needed.

Related PR elastic/elasticsearch#27955

### PR DESCRIPTION
**Pull request by imotov**
Adds a single JDBC driver jar that shades all external dependencies and bundles
all necessary classes.

Closes #29856

### CODE REVIEW

**Review by nik9000 — COMMENTED** [review]
It looks right to me but I think it is worth me downloading it and playing with it for a while which I'll try to do soon.

**Comment by imotov** [comment]
> downloading it and playing with it 

I would really appreciate that.

**Review by nik9000 — APPROVED** [review]
LGTM.

I've heard of issues with this in Intellij but @imotov uses intellij and didn't seem to have hit them.

I think it'd be nice to use the shaded jar in the qa tests but that this is worth merging as is. The qa tests will be enough work to fight and we have manually tested that the shaded jar works.

**Review by jasontedor — CHANGES_REQUESTED** [review]
I don't think we should use the default artifact name (`jdbc`); I think for now we should use an artifact name like `x-pack-sql-jdbc` and in the future `elasticsearch-sql-jdbc` but the time for latter is not now. You can do this by setting the `archivesBaseName`.

Additionally, I am curious why you dropped the use of `nebula` here? This means that the `jdbc` POM will not look like the rest of our POMs. For example, the SCM element in the POMs comes from the Nebula plugin (although it looks broken right now as it's being populated with an empty URL; that would be a follow-up).

**Comment by imotov** [comment]
@jasontedor  I had to switch from `nebula` because it kept adding dependencies that were already included into the shadow jar. I will try to switch back to `nebula` and find a way to exclude dependencies.

**Comment by imotov** [comment]
@jasontedor I pushed some changes, could you take another look when you have a chance?

**Review by jasontedor — APPROVED** [review]
Looks great; thanks for taking the extra iteration on this one.

**Pull request merged**
