### PR TITLE
B/cloud azure arm 2.3.3

### PR DESCRIPTION
**Pull request by memcmp**
updated azure plugin to support cloud-azure-arm #19146

( As we need it in 2.3. we created the PR against this branch, a PR against master will follow )

### CODE REVIEW

**Comment by karmi** [comment]
Hi @bogensberger, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/elasticsearch/pull/19575.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by bogensberger** [comment]
Hi @karmi, i think the CLA check is failing beacause @aslanbekirov didn't sign the CLA yet. Will do it immediately.

**Comment by aslanbekirov** [comment]
Hi @karmi, I signed it.

**Comment by dadoonet** [comment]
Hey @bogensberger. Thanks for the effort.

I did not read the code in details for now. But the idea with #19146 is to create a new plugin named `discovery-azure-arm` instead of changing the legacy plugin.

Also, I don't think we will add this to 2.4 but I might be wrong.

That being said, as I started a branch for 5.0 (not public yet - baby steps), I'll most likely reuse your efforts there unless you have a plan for doing so yourself in the mid term?

**Comment by dadoonet** [comment]
@bogensberger Do you think you will come with a branch based on master branch (5.0)?

**Comment by bogensberger** [comment]
@dadoonet as you planned to create a new plugin and reuse our efforts i didn't plan to create a plugin based on the master branch because the important stuff which you could reuse wouldn't be different on master and the rest will be thrown anyway.

**Comment by dakrone** [comment]
@dadoonet what's the word on this, are you still planning on reusing the efforts here?

**Comment by dadoonet** [comment]
That's my plan indeed. No idea when I'll be able to do it though. 
Thanks for the heads up!

But as we won't merge this PR as is we can close it I guess?

**Comment by dakrone** [comment]
Okay, I'm going to close this then.

**Pull request closed without merging**
