### PR TITLE
Add a run.sh to run from current source code with debugger

### PR DESCRIPTION
**Pull request by rmuir**
The maven magic needed for this is now heavier

### CODE REVIEW

**Comment by metadave** [comment]
running `mvn clean` followed by `./run.sh` yields: https://gist.githubusercontent.com/metadave/de196bbb026211c69ed9/raw/18d52d8793abc99052fb0b4b4cd18a067dd2b1be/gistfile1.txt

**Comment by dakrone** [comment]
This isn't working for me: http://p.draines.com/14381952224210898d64c.txt

**Comment by rmuir** [comment]
Because your dev-tools was out of date (no mvn install). See my commit. I made execution depend on all poms and dev-tools in case that logic changes.

**Comment by dakrone** [comment]
Great, works now, LGTM

**Comment by rmuir** [comment]
I was trying to make it fast by cheating before... but the maven shading is really the slowest part anyway, better to be safer... and that shading can be moved out (it needs to, since its an artifact untested by anything).

**Comment by metadave** [comment]
works for me now as well, LGTM

**Pull request merged**
