### PR TITLE
Check REST test nodes LeakTracker like we check Netty's LeakDetector

### PR DESCRIPTION
**Pull request by original-brownbear**
We should make sure to find leaks reported by both of these, these days our `LeakTracker` will likely be more sensitive that Netty's in some cases since our objects refer to Netty objects and thus get collected first.
Also, make the filtering of log lines a little less format dependant, it seems to me with recent format changes we might have extra spaces behind the classname and before the closing `]`.

### CODE REVIEW

**Comment by original-brownbear** [comment]
This worked better than expected, already found a leak. Let me fix that right up first ...

**Review by mark-vieira — COMMENTED** [review]
It's worth noting that this only applies to rest tests using the old legacy framework. We should probably implement something similar for the new test clusters framework.

**Comment by original-brownbear** [comment]
@mark-vieira thanks, didn't even think about that. How about merging this first though, it took an unexpected amount of work to get this to green, I kinda want to lock this in asap before we break the next thing accidentally.
Happy to get to work on a follow-up for the new framework asap :)

**Comment by mark-vieira** [comment]
Yep, let's get this merged and follow up.

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Comment by original-brownbear** [comment]
Thanks you two!

**Pull request merged**
