### PR TITLE
Add deprecation info API entries for deprecated monitoring settings

### PR DESCRIPTION
**Pull request by jbaiera**
Recently we have deprecated a number of settings in monitoring. These settings should be represented in the deprecation info API. This PR will be backported with some minor changes to the 7.x branch so that we can start the deprecation process in that release cycle.

Related issues:
https://github.com/elastic/elasticsearch/pull/77659
https://github.com/elastic/elasticsearch/pull/78564

### CODE REVIEW

**Review by danhermann — APPROVED** [review]
Code changes LGTM

**Comment by jrodewig** [comment]
Thanks for the explanation @danhermann.

**Review by jrodewig — COMMENTED** [review]
Thanks again @jbaiera. I'll leave final docs approval to @debadair. I think there's an opportunity to improve the boilerplate text here, but she's in a better position to judge that.

Otherwise, I think we need to remove the new sentence from the breaking changes docs.

**Review by debadair — COMMENTED** [review]
I agree with the patterns James suggested for the case where there are multiple settings. Had one question about the breaking changes entry--it contradicts itself. :-)

**Review by masseyke — COMMENTED** [review]
Looks good to me, although I share @debadair's slight confusion about the documentation.

**Review by jrodewig — CHANGES_REQUESTED** [review]
The deprecation info API changes LGTM. However, as @debadair pointed out, we should remove the 8.0 breaking changes docs. Instead, we should update the [7.16 deprecations](https://www.elastic.co/guide/en/elasticsearch/reference/7.x/migrating-7.16.html#breaking_716_monitoring_changes) to update any 8.0 removal references, probably as a separate PR.

**Review by jrodewig — APPROVED** [review]
LGTM. Thanks for removing the docs.

**Pull request merged**
