### PR TITLE
Replace usages of ElasticsearchParseException with ParsingException

### PR DESCRIPTION
**Pull request by cbuescher**
Our codebase currently uses a mixture of `XContentParserException`, `ParsingException` and
`ElasticsearchParseException` for more or less the same cases where the exception can carry 
additional location information with the origin of a parsing error. In order to consolidate this, this
PR replaces uses of `ElasticsearchParseException` with the similar `ParsingException`.
Both exceptions extend `ElasticsearchException`, are unchecked and translate into a 400 http error.
Note that `ElasticsearchException` is only deprecated and not removed entirely so we can continue to
deserialize it when receiving it from older version nodes.

Relates to #53106

### CODE REVIEW

**Comment by cbuescher** [comment]
`elasticsearch-ci/rest-compatibility` currently still fails because some yaml tests check the exception classes name, and while I corrected those on the main branch, apparently the rest compatibility checks run older versions of those tests. I need to find a way to either mute or skip those. I think changing an exception type that otherwise carries the same meaning doesn't fall under the rest compatibility policy.

**Comment by cbuescher** [comment]
Note that this PR needed a few transformations to rest tests. The rest compatibility checks draw yaml rest tests from the 7.17 branch and run them with a current checkout to detect bwc changes in the API surface. Some of these yaml tests check for exception names in either `catch` or `match` clauses, so we need to transform them before they are run. AFAIK exception names are not be part of the rest compatibility policy, and since the HTTP response status of these two exceptions is the same (400) the change should be okay from that perspective.

**Comment by javanna** [comment]
Could somebody @elastic/es-core-infra have a look and let us know what they think of this direction given it goes outside of the Search team boundaries? Thanks!

**Comment by rjernst** [comment]
The direction sounds great: consolidating two similar classes is always nice.

**Comment by stu-elastic** [comment]
@cbuescher This is pretty old, I'm going to close it.  Please reopen if still relevant.

**Pull request closed without merging**
