### PR TITLE
IllegalStateException: Only duplicated jar instead of classpath

### PR DESCRIPTION
**Pull request by s12v**
Currently, entire classpath is in exception message, which is not very helpful:
```
Caused by: java.lang.IllegalStateException: jar hell!
duplicate jar on classpath: /Applications/IntelliJ IDEA.app/Contents/lib/...
```

After the change, only problematic jar should be included in the message.

### CODE REVIEW

**Comment by jasontedor** [comment]
I see the point about making it easier to see the duplicate jar, but I would prefer that we not suppress the entire classpath here. Would you mind pushing a change the shows the duplicate jar and the entire classpath? Something like:

```
duplicate jar [/path/to/jar.jar] on classpath: 
```

**Review by jasontedor — CHANGES_REQUESTED** [review]
I left a comment at the top level about changing the method to still include the entire classpath.

**Comment by s12v** [comment]
@jasontedor, updated

**Comment by jasontedor** [comment]
test this please

**Comment by jasontedor** [comment]
Thanks @s12v, I've started a CI build.

**Comment by jasontedor** [comment]
retest this please

**Comment by s12v** [comment]
@jasontedor, there's a typo, sorry. Fixed, could you please retest it?

**Comment by jasontedor** [comment]
retest this please

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by jasontedor** [comment]
Thanks @s12v!

**Pull request merged**
