### PR TITLE
SQL: Implement DATETIME_PARSE function for parsing strings

### PR DESCRIPTION
**Pull request by matriv**
Implement DATETIME_PARSE(<datetime_str>, <pattern_str>) function
which allows to parse a datetime string according to the specified
pattern into a datetime object. The patterns allowed are those of
`java.time.format.DateTimeFormatter`.

Relates to #53714

### CODE REVIEW

**Comment by matriv** [comment]
@elasticmachine run elasticsearch-ci/docs

**Review by costin — APPROVED** [review]
LGTM

**Review by astefan — APPROVED** [review]
LGTM. With some minor comments.

**Comment by matriv** [comment]
@elasticmachine run elasticsearch-ci/1 
@elasticmachine run elasticsearch-ci/2

**Comment by matriv** [comment]
@elaticmachine run elasticsearch-ci/docs-check

**Pull request merged**
