### PR TITLE
Upgrade Lucene to 5.3.1

### PR DESCRIPTION
**Pull request by dpursehouse**
This is a minor release that fixes a few bugs.

See the release notes for details:

https://lucene.apache.org/core/5_3_1/changes/Changes.html

Change-Id: Iabce1eac263ae8744b9a01e11d53461bc3b23924

### CODE REVIEW

**Comment by rmuir** [comment]
Can you regenerate the sha1's for the artifacts? `mvn verify` should fail unless this is done.

There is a script to do it, but its not in this branch. Its here: https://github.com/elastic/elasticsearch/blob/2.x/dev-tools/update_lucene.sh

I think it should be committed here too. It just needs one modification: drop the line for lang-expressions since its not factored out into a plugin here.

Thanks for doing this!

**Comment by dpursehouse** [comment]
@rmuir thanks for the quick feedback.  I've done as suggested and pushed some more commits.

Note that I had to rewrite the branch because I accidentally did the first commit with the wrong author email address :(

**Comment by rmuir** [comment]
this looks great! thanks again

**Comment by rmuir** [comment]
I tried out your branch and ran tests, I think we missed a few things still. We need to bump the lucene version in `Version.java`, and also deal with the assert in `IndexShard.java`. 

I think we should defer the IndexShard assert, I want to make sure the changes in that workaround (e.g. optimization for empty disjunctions case) is really all covered by https://issues.apache.org/jira/browse/LUCENE-6748: https://github.com/elastic/elasticsearch/issues/14673

Something like this? If you don't mind to just push to your branch, then we can stay on this PR.
```
--- a/core/src/main/java/org/elasticsearch/Version.java
+++ b/core/src/main/java/org/elasticsearch/Version.java
@@ -268,7 +268,7 @@ public class Version {
     public static final int V_2_0_1_ID = 2000199;
     public static final Version V_2_0_1 = new Version(V_2_0_1_ID, true, org.apache.lucene.util.Version.LUCENE_5_2_1);
     public static final int V_2_1_0_ID = 2010099;
-    public static final Version V_2_1_0 = new Version(V_2_1_0_ID, true, org.apache.lucene.util.Version.LUCENE_5_3_0);
+    public static final Version V_2_1_0 = new Version(V_2_1_0_ID, true, org.apache.lucene.util.Version.LUCENE_5_3_1);
 
     public static final Version CURRENT = V_2_1_0;
 
index 351e20e..2563d99 100644
--- a/core/src/main/java/org/elasticsearch/index/shard/IndexShard.java
+++ b/core/src/main/java/org/elasticsearch/index/shard/IndexShard.java
@@ -263,7 +263,7 @@ public class IndexShard extends AbstractIndexShardComponent {
         if (indexSettings.getAsBoolean(IndexCacheModule.QUERY_CACHE_EVERYTHING, false)) {
             cachingPolicy = QueryCachingPolicy.ALWAYS_CACHE;
         } else {
-            assert Version.CURRENT.luceneVersion == org.apache.lucene.util.Version.LUCENE_5_3_0;
+            // https://github.com/elastic/elasticsearch/issues/14673
             // TODO: remove this hack in Lucene 5.4, use UsageTrackingQueryCachingPolicy directly
             // See https://issues.apache.org/jira/browse/LUCENE-6748
             // cachingPolicy = new UsageTrackingQueryCachingPolicy();
```

**Comment by dpursehouse** [comment]
@rmuir I added a couple more commits.  Please try again.

**Comment by dpursehouse** [comment]
`mvn test` is passing for me now.

**Comment by rmuir** [comment]
Yeah its looking good. For these lucene upgrades, I usually spin up a `mvn verify` because these upgrades modify packaging, licensing, impact plugins etc, I have it already running now, will push when its done.

**Comment by rmuir** [comment]
thanks @dpursehouse !

**Comment by dpursehouse** [comment]
No problem, thanks @rmuir for the quick feedback and merge.

Can you point me in the direction of where I can find the release schedule for v2.1.0?

**Comment by rmuir** [comment]
The most up to date view would be https://github.com/elastic/elasticsearch/issues?q=is%3Aopen+is%3Aissue+label%3Av2.1.0

A lot of those look like TODOs that got pushed out from 2.0.0 to me and just ended out with 2.1.0 slapped on them, so I don't think the situation is as intimidating as it looks :)

**Comment by dpursehouse** [comment]
Thanks.  If there are any low-hanging-fruit type issues I would be happy to help as much as I can.  I'd like to get my hands on 2.1.0 as soon as possible :)

https://gerrit-review.googlesource.com/#/c/58081/

**Comment by rmuir** [comment]
you can additionally add the `adoptme` label to find issues with no owner yet. 

https://github.com/elastic/elasticsearch/issues/14673 is one idea, as its a followup to this one. It just means being a little careful: looking at git history/blame and ensuring that no other optimizations were slipped into the custom cache code, maybe double-checking https://issues.apache.org/jira/browse/LUCENE-6748, especially the "All" tab on jira and looking at what exactly got backported to 5.3.1 (since the issue doesn't have that label, yet is in CHANGES.txt, we should be careful). Then if its all ok, we can remove it and run tests.

**Pull request merged**
