### PR TITLE
[ES|QL] allow mixed numeric types as inputs to coalesce

### PR DESCRIPTION
**Pull request by fang-xing-esql**
Today, `COALESCE` enforces the same data type among all of the input parameters, e.g. if there are both `INTEGER` and `LONG` in the inputs, it returns an error, please refer to the example below. 

```
FROM employees
| WHERE emp_no <= 10021 and emp_no >= 10018
| EVAL x = coalesce(languages.long, null, 0.0), y = coalesce(languages.long, null, 0), z = coalesce(languages, 0.0), w = coalesce(height, 0);

org.elasticsearch.xpack.esql.VerificationException: Found 4 problems
line 3:12: third argument of [coalesce(languages.long, null, 0.0)] must be [long], found value [0.0] type [double]
line 3:53: third argument of [coalesce(languages.long, null, 0)] must be [long], found value [0] type [integer]
line 3:92: second argument of [coalesce(languages, 0.0)] must be [integer], found value [0.0] type [double]
line 3:122: second argument of [coalesce(height, 0)] must be [double], found value [0] type [integer]
```

This PR is to allow mixed numeric types in the inputs.

### CODE REVIEW

**Review by costin — CHANGES_REQUESTED** [review]
The implicit conversion of int to long or float to double should happen on all functions not just Coalesce.

Namely `coalesce(long_column, 0)` is the same as `coalesce(long_column, 0::long)` since:
1. the return type of coalesce is `long` (based on the column type)
2. the potential arguments that can replace it have to have long values. In case of literals we should automatically cast those to long.

That said, we shouldn't cast double or float to long just because - the implicit casting should occur only for obvious cases (int -> long, float -> double).

**Comment by bpintea** [comment]
To keep things linked, there's an issue opened for it: https://github.com/elastic/elasticsearch/issues/111486

**Comment by bpintea** [comment]
> the implicit casting should occur only for obvious cases (int -> long, float -> double).

Wouldn't we want to always upcast? Like `COALESCE(double, integer)`, but unlike `COALESCE(int, long)`.

**Comment by costin** [comment]
I think this has been superseded by https://github.com/elastic/elasticsearch/issues/111486

**Comment by fang-xing-esql** [comment]
This is fixed by #111917 in Analyzer.

**Pull request closed without merging**
