### PR TITLE
Updates vagrant tests upgrade version number

### PR DESCRIPTION
**Pull request by abeyad**
This PR updates the latest version the vagrant tests can upgrade from to 5.0.0.

### CODE REVIEW

**Comment by abeyad** [comment]
@s1monw @nik9000 could you take a look?  this is to solve the failing vagrant tests issue on CI.  This solves the problem for me locally (i just ran `gradle updatePackagingTestUpgradeFromVersions` then re-ran the test), but I'm not sure if I did the right thing here.

**Comment by s1monw** [comment]
@nik9000 should check I guess - LGTM for what it's worth

**Comment by abeyad** [comment]
retest this please

**Comment by nik9000** [comment]
Lgtm too.  Sorry for such a late response.

**Pull request merged**
