### PR TITLE
Parse URL if bad URI

### PR DESCRIPTION
**Pull request by legoguy1000**
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?

### CODE REVIEW

**Comment by legoguy1000** [comment]
Is there a good way to test this change?? I'm looking at this page, https://github.com/elastic/elasticsearch/blob/master/TESTING.asciidoc,  but I'm not really a java guy so IDK what the generic test command is.

**Comment by legoguy1000** [comment]
This is what i get when I run `gradle chack`
```
alex@dev:~/elasticsearch$ gradle check
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type ScriptPluginFactory using BuildScopeServices.createScriptPluginFactory().
> Could not create service of type PluginResolutionStrategyInternal using BuildScopeServices.createPluginResolutionStrategy().

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
```

**Review by danhermann — COMMENTED** [review]
@legoguy1000, what are you trying to achieve with this change? Since URLs are a subset of URIs, I wouldn't expect there to be a case where a string was an invalid URI but a valid URL.

**Comment by legoguy1000** [comment]
> @legoguy1000, what are you trying to achieve with this change? Since URLs are a subset of URIs, I wouldn't expect there to be a case where a string was an invalid URI but a valid URL.

The URI type fails when parsing a url with non URL encoded values.  The URL type does not.

**Comment by danhermann** [comment]
> This is what i get when I run `gradle chack`

What happens if you use the included gradle wrapper via `./gradlew check`?

**Comment by legoguy1000** [comment]
Like I said I'm not a Java guy so IDK if i've even installed all the dev dependences that i need

**Comment by danhermann** [comment]
It looks like you're using JDK16 which does not appear to work well with our build system, yet. Try switching to JDK15 and doing a `./gradlew clean check`.

**Comment by danhermann** [comment]
@elasticmachine ok to test

**Comment by danhermann** [comment]
@legoguy1000, if you're having trouble with the Java build framework on this one, I can pick it up since I now understand what the issue is. Let me know what you prefer.

**Comment by legoguy1000** [comment]
> @legoguy1000, if you're having trouble with the Java build framework on this one, I can pick it up since I now understand what the issue is. Let me know what you prefer.

I haven't had a chance to do much with it lately.  Feel free to push whatever changes you think are needed.

**Comment by danhermann** [comment]
> I haven't had a chance to do much with it lately. Feel free to push whatever changes you think are needed. I would like to know what i'm missing or what I should change/do for next time.

Cool, I'll get a fix in for this before the next patch release. If you want to open a thread about getting your local build working in our forums (https://discuss.elastic.co/), tag me (`@danhermann`) in it and I'll be happy to work through those with you there.

**Comment by danhermann** [comment]
The resolution for this issue was merged in https://github.com/elastic/elasticsearch/pull/71559.

**Pull request closed without merging**
