### PR TITLE
Close InputStream when receiving cluster state in PublishClusterStateAction

### PR DESCRIPTION
**Pull request by ywelsch**
Not closing the InputStream will leak native memory as the DeflateCompressor/Inflater won't be closed.

### CODE REVIEW

**Review by bleskes — APPROVED** [review]
LGTM. What triggered this?

**Comment by alexbrasetvik** [comment]
@bleskes We're hunting memory issues in Cloud, details on how this was found in https://github.com/elastic/dev/issues/715

**Comment by jasontedor** [comment]
@ywelsch This should have the 5.2.0 label.

**Comment by ywelsch** [comment]
@jasontedor right! 👍

**Pull request merged**
