### PR TITLE
Remove mention of mvn from java source files

### PR DESCRIPTION
**Pull request by nik9000**
Switch with gradle.

### CODE REVIEW

**Comment by jasontedor** [comment]
Good. Can you get [`tests.maven`](https://github.com/elastic/elasticsearch/blob/70396d4243e89dbe2194499cc942bff17bc695aa/buildSrc/src/main/groovy/org/elasticsearch/gradle/BuildPlugin.groovy#L403) too?

**Comment by nik9000** [comment]
> Can you get tests.maven too? It's read in BootstrapForTesting and looks like a simple addition to this PR.

Sure.

**Comment by nik9000** [comment]
@jasontedor I've renamed the property. I'm running the tests now just to be extra paranoid.

**Comment by jasontedor** [comment]
LGTM.

**Pull request merged**
