### PR TITLE
Fix split package org.apache.lucene.analysis.miscellaneous

### PR DESCRIPTION
**Pull request by ChrisHegarty**
To allow for the future modularization of Elasticsearch with Java Modules, there are a number preparatory tasks that need be completed. This is one part of one such task: eliminate split packages.

Since recent Lucene upgrades, classes in `org.apache.lucene.analysis.miscellaneous` no longer require package-private access. This PR proposes to keep these classes in sever, but moved them to `org.elasticsearch.lucene.analysis.miscellaneous`. These classes are used by both server and common analysis plugin.

relates #78166

### CODE REVIEW

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by ChrisHegarty** [comment]
@elasticmachine update branch

**Comment by ChrisHegarty** [comment]
@elasticmachine update branch

**Comment by ChrisHegarty** [comment]
@elasticmachine update branch

**Pull request merged**
