### PR TITLE
Fix error with test conventions on tasks that require Docker

### PR DESCRIPTION
**Pull request by mark-vieira**
This PR looks to address #42680. Essentially, our test conventions plugin looks to ensure that all test classes are "covered" by some enabled test task. When using `BuildPlugin.requiresDocker()` however we disable the target task if Docker isn't available on the system. We instead should use the same technique as the test fixtures plugin, which is to conditionally _skip_ the task via `Task.onlyIf()`.

@atorok I did find `requiresDocker()` a bit confusing the comment in the method states the following: 
```
             * This is our first time encountering a task that requires Docker. We will add an extension that will let us track the tasks
             * that register as requiring Docker. We will add a delayed execution that when the task graph is ready if any such tasks are
             * in the task graph, then we check two things:
             *  - the Docker binary is available
             *  - we can execute a Docker command that requires privileges
```

However, in this case "the Docker binary is available" doesn't seem to be enforced. Essentially `buildDocker = dockerBinary != null` is just disabling all Docker tasks if no docker binaries exist on the system. It's not clear to me whether that is the desired behavior. I _would_ have expected this build to fail eagerly with an error that Docker isn't installed. So far as I can tell, the way this is written, the following code will never run:

```
                    if (dockerBinary == null) {
                        final String message = String.format(
                                Locale.ROOT,
                                "Docker (checked [%s]) is required to run the following task%s: \n%s",
                                maybeDockerBinaries.join(","),
                                tasks.size() > 1 ? "s" : "",
                                tasks.join('\n'))
                        throwDockerRequiredException(message)
                    }
```

While this PR would technically "fix" the linked issue I'm not sure this is correct. I think this method is overly lenient by mistake. Does that sound correct?

We should probably instead refactor the `thirdPartyTests` task for this project to _not_ use `requiresDocker()` and instead just piggy-back on the logic in the test fixtures plugin.

### CODE REVIEW

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by hub-cap** [comment]
ty for tackling this!

**Comment by atorok** [comment]
The change LGTM.
Did the problem reproduce for you ? I wasn't able to reproduce it yesterday when I briefly looked at it. 
The testing fixtures plugin also disables testing conventions tasks when no docker is available ( see [here](https://github.com/elastic/elasticsearch/blob/master/buildSrc/src/main/java/org/elasticsearch/gradle/testfixtures/TestFixturesPlugin.java#L109)), I'm not sure why that isn't working in CI but seems to be working locally. 

There are two types of dependency on docker, one is for test fixtures where the intent is that everything that requires it will be skipped and the other is for building the docker distribution , where we want to fail if you try to build  the docker distribution and you don't have docker set up properly the right version. 
We only fail if the task that requires it is on the classpath ( so you can build other distributions if you don't have docker )

The reason dis does not fail is that the third party audit task is not in the task graph because we disable it, so the check on the task graph ready for non existing docker is useless, we only really check for version and permissions when docker __is present__. 

I don't think we need this leniency here, as right now without docker `./gradlew :distribution:docker:assemble` succeeds without producing anything.

**Comment by atorok** [comment]
I created #42745 to clean this up

**Comment by mark-vieira** [comment]
> Did the problem reproduce for you ?

I reproduced on an actual centos machine.

> The testing fixtures plugin also disables testing conventions tasks when no docker is available ( see here), I'm not sure why that isn't working in CI but seems to be working locally.

The difference is the _way_ those tasks are "disabled". The `requiresDocker()` method actually does `enabled = false` whereas the fixtures plugin simply adds an `onlyIf()` condition to skip the task. The testing conventions task specifically ensures that there is an _enabled_ task that covers all tests. Thus the error.

**Pull request merged**
