### PR TITLE
Update get.asciidoc

### PR DESCRIPTION
**Pull request by demisx**
Fix typo in "Get" request documentation.

### CODE REVIEW

**Comment by jtibshirani** [comment]
Hi @demisx, thank you for the fix! Just for proper protocol, I'm going to kick off a docs build before merging.

One small comment: would you mind updating the PR title to be more descriptive (something like 'Fix a typo in the 'get' request documentation')?

**Comment by jtibshirani** [comment]
@elasticmachine test this please

**Comment by jtibshirani** [comment]
I also just realized that this PR is against the `6.2` branch -- would you be able to switch the base branch to `master`? Our workflow is to open PRs against `master`, and follow-up with backport commits (which I can handle).

**Comment by demisx** [comment]
@jtibshirani No problem. I've just clicked on the "Edit" button in the docs and followed the current defaults. This is how I've ended up with this PR. I've updated the comment per your request and changed the target to `master`.  However, I now see 7,833 files changed which is obviously wrong.

**Comment by jtibshirani** [comment]
My apologies, I now see that we have a different workflow for docs updates that were initiated directly from the website. Let's switch the branch back to `6.2`, and I'll merge after the build passes.

**Comment by demisx** [comment]
No worries. Done. Would really help if adjusting basic content in docs followed the simplest flow possible, thus encouraging more people to contribute with improvements. 👍

**Pull request merged**
