### PR TITLE
[Tests] Fix randomization in TokenServiceTests

### PR DESCRIPTION
**Pull request by cbuescher**
I just ran into this while removing multi-line statements, but this seems like
an actual bug in the intended randomization of the test, possibly a leftover
from a debugging session. My guess is the numRotations should be randomized, but
currently is always 0.

### CODE REVIEW

**Review by nik9000 — COMMENTED** [review]
This looks right to me.

**Comment by cbuescher** [comment]
@nik9000 are you willing to approve the PR or should @jaymode or somebody from @elastic/es-security take a second look at it? I'm also pretty sure the keys here were supposed to be rotated a number of times, but don't want to bypass the team.

**Review by tvernum — APPROVED** [review]
LGTM.
I don't know whether it was intentional, but in the absence of any comments, I'll work on the assumption that it was an accidental commit.

**Comment by cbuescher** [comment]
@tvernum @nik9000 thanks

**Comment by cbuescher** [comment]
Closing since this went in as part of #33682

**Pull request closed without merging**
