### PR TITLE
Force implementing bulk InputStream#read on StreamInput

### PR DESCRIPTION
**Pull request by original-brownbear**
We should enforce overriding here to avoid extremely slow byte-by-byte reads when using these instances as `InputStream`. I only found one case where this matters practically in the codebase (will link it shortly) but it's probably good to guard against it.

### CODE REVIEW

**Review by rjernst — COMMENTED** [review]
This seems ok, but I think it would be nicer to implement the method correctly. It seems like it should be possible from StreamInput.

**Comment by original-brownbear** [comment]
@rjernst thanks for taking a look!

>  It seems like it should be possible from StreamInput.

I don't think it is? We only have `readBytes` to work with really and that throws if we read past a potentially unknown bound. So if we can't build it from that method we don't really have anything to go by here do we?

**Comment by rjernst** [comment]
`StreamInput` has the `available()` method, so the implementation you have in `ByteArrayStreamInput` should work directly in `StreamInput`?

**Comment by original-brownbear** [comment]
Hmm but then we start relying on `available()` returning an exact result. For `InputStreamStreamInput` that is not guaranteed, granted that has an implementation of the bulk read from `InputStream`, but this seems safer than requiring either an exact `available` (or an override for when it's not exact)? Even if it's slightly more code, this approach seems to come with cleaner compile-time guarantees? :)

**Comment by rjernst** [comment]
The semantics of `available()` come from `InputStream`, it's not `StreamInput`. It only means some number of bytes are available without blocking. That's exactly what we need with `read(byte[],int,int)`, there is no guarantee it reads the requested length, only no more than it.

**Comment by original-brownbear** [comment]
>  there is no guarantee it reads the requested length, only no more than it.

The problem is that it is legitimate for implementations of `InputStream` to always return `0` (and quite a few do in fact) which would break a bulk `read` based on it.

**Review by rjernst — APPROVED** [review]
This is a mess. Thanks for the discussion, LGTM.

**Comment by original-brownbear** [comment]
Thanks Ryan!

**Pull request merged**
