### PR TITLE
Deprecate locale parameters in query_string and simple_query_string

### PR DESCRIPTION
**Pull request by javanna**
The configured analysis chain should be used instead.

Relates to #13229

### CODE REVIEW

**Comment by javanna** [comment]
@rmuir can you have a look? if this looks good I will put up another PR to remove `locale` for 3.0.

**Comment by javanna** [comment]
I updated the PR to add some docs, which I had forgotten about in the first place. Reviews are welcome.

**Comment by javanna** [comment]
while looking into removing these as previously discussed, I bumped into `org.apache.lucene.queryparser.classic.QueryParserBase#setLocale` in lucene. I am then wondering why we shouldn't expose this setting if lucene allows to set it. Are we sure this is the best way forward? It is hard for me to tell. Will leave a comment also on the original issue.

**Comment by rmuir** [comment]
I think the issue is that elasticsearch does not in fact use the configured analysis chain for wildcards, range queries, fuzzy queries, etc.

Lucene factories are annotated with the information needed to do this properly. I have explained the issue here: https://github.com/elastic/elasticsearch/issues/9978

**Comment by javanna** [comment]
thanks for the explanation @rmuir that makes sense to me. I am closing this PR then, we can't move on till we have implemented what is described in #9978.

**Pull request closed without merging**
