### PR TITLE
Gracefully handles pre 2.x compressed snapshots

### PR DESCRIPTION
**Pull request by abeyad**
In pre 2.x versions, if the repository was set to compress snapshots,
then snapshots would be compressed with the LZF algorithm.  In 5.x,
Elasticsearch no longer supports the LZF compression algorithm.  This
presents an issue when retrieving snapshots in a repository or upgrading
repository data to the 5.x version, because Elasticsearch throws an
exception when it tries to read the snapshot metadata because it was
compressed using LZF.

This commit gracefully handles the situation by introducing a new
incompatible-snapshots blob to the repository.  For any pre-2.x snapshot
that cannot be read, that snapshot is removed from the list of active
snapshots, because the snapshot could not be restored anyway.  Instead,
the snapshot is recorded in the incompatible-snapshots blob.  When
listing snapshots, both active snapshots and incompatible snapshots will
be listed, with incompatible snapshots showing a `INCOMPATIBLE` state.
Any attempt to restore an incompatible snapshot will result in an
exception.

### CODE REVIEW

**Review by imotov — COMMENTED** [review]
I am not really sure what the right solution here, but this approach seems dangerous to me. Since we are not adding this snapshot to the list of snapshots in 5.x we will not consider files that belong to this snapshot as needed, which means that we might remove these files during consecutive snapshots, right? 

I am thinking about a scenario where 1.x index was upgraded to 2.x so we have both 1.x and 2.x snapshots pointing to the same data directory. So, in a sense we might make this snapshot non-restorable even in earlier versions of elasticsearch. 

I think a better approach might be to identify a list of snapshots that cannot be brought over to 5.x and throw an exception with the list of these snapshots asking user to either delete these snapshots from the existing repository or switch to a new repository.

**Comment by abeyad** [comment]
@imotov 
> I am not really sure what the right solution here, but this approach seems dangerous to me. Since we are not adding this snapshot to the list of snapshots in 5.x we will not consider files that belong to this snapshot as needed, which means that we might remove these files during consecutive snapshots, right?

What happens in the case where there are no compressed snapshots, when a 5.x cluster is touching the repository for the first time, it updates the snapshots index file to the 5.x version.  In doing so, it is able to read the legacy pre 2.x format and get the snapshot metadata and proceed accordingly.  When you GET all the snapshots, it lists all the snapshots including the pre 2.x ones.  It is only when you try to restore the snapshot that you get an error saying "snapshot contains index data that is too old" (something to that effect).  It is only when dealing with compressed snapshots that we have an issue.  The reason is we can't even read the snapshot metadata via `LegacyBlobFormat` because the compression mode is no longer supported and throws the `IllegalStateException`.  This means when we try to upgrade the snapshot repository data to the 5.x version, we get exceptions and can't proceed.  That means we can't even delete the snapshot because being able to read the snapshot metadata is a prerequisite to updating the view of what the current snapshots are (not to mention the `getSnapshotInfo` call fails too).  So we really can't proceed with the repository in 5.x until we either drop the snapshot or have some way to read its metadata, which is now prohibited due to its compressed format.

> I am thinking about a scenario where 1.x index was upgraded to 2.x so we have both 1.x and 2.x snapshots pointing to the same data directory. So, in a sense we might make this snapshot non-restorable even in earlier versions of elasticsearch.

The upgrade process will only remove the snapshot from the new `index-N` file, so a 2.x cluster can still read the snapshot from the `index` file.  Unless I misunderstood what you intended?

> I think a better approach might be to identify a list of snapshots that cannot be brought over to 5.x and throw an exception with the list of these snapshots asking user to either delete these snapshots from the existing repository or switch to a new repository.

The issue is that we can't even list the snapshots to delete until we are able to load the repository in 5.x  We can, and indeed do, do this for uncompressed snapshots, as mentioned above, but the same strategy does not work for snapshots compressed in 1.x.  The reason I considered it acceptable to remove the snapshot from the `index-N` file, with a warning, is that the snapshot would never be restorable in 5.x anyway (because it will have 1.x index data).

Not sure if this makes sense, but this is the rationale for this approach and I'm not sure if it can be done differently without adding a new API that operates on a "non-updated" repository so one can pick and chose what snapshots they want to keep.

**Comment by imotov** [comment]
> The upgrade process will only remove the snapshot from the new index-N file, so a 2.x cluster can still read the snapshot from the index file. Unless I misunderstood what you intended?

@abeyad I was trying to describe a scenario, where this might lead to loosing data in the 1.x snapshots without a warning (I don't consider logging on master a fair warning in this case). Might be it's me how is missing something here though. Can we chat on zoom about it tomorrow morning, I will try to explain the scenario in more details.

**Comment by abeyad** [comment]
@imotov I pushed 2a3faf7daf723b6c5ab52862aecc9277979f8dbc that implements the `incompatible-snapshots` blob that we discussed.

**Review by imotov — COMMENTED** [review]
I think this is much better, but I have a couple of questions. How are we going to handle this in 6.x? Would it be possible to improve the delete snapshot experience for the unsupported snapshots or they are pretty much stuck in this repository forever since we cannot really clean them?

**Comment by abeyad** [comment]
> How are we going to handle this in 6.x? 

I will forward port this code to master, with the only omission being the actual creation of the `incompatible-snapshots` blob (because as of now, only 5.x would need to create it in its `updateRepositoryData` method that 6.x won't have).  So 6.x clusters will also be able to read the incompatible snapshots and display them just as 5.x does.

> Would it be possible to improve the delete snapshot experience for the unsupported snapshots or they are pretty much stuck in this repository forever since we cannot really clean them?

Its impossible to know from the repository data which data files can be deleted, because the `snap-*.dat` blob can't be read at all, which is the starting point to figure out which files in the repository belong to the snapshot.  

One (not so great) option is that we could iterate over all the data files in the repository and if they throw a similar compression exception, we can know they are outdated (belonging to 1.x) and delete them.  But the overhead of iterating over all repository files like that could be huge. 

WDYT?

**Review by imotov — APPROVED** [review]
Yeah, I guess this is the best we can do in this case. LGTM.

**Comment by abeyad** [comment]
retest this please

**Comment by abeyad** [comment]
thanks for the review @imotov

**Comment by abeyad** [comment]
master: b0c009ae769877594ada8a2b05267463caebf274

**Comment by abeyad** [comment]
5.2 commit: 29b777a059521c8218d9161c42f6cd9e8286cd8a

**Pull request merged**
