### PR TITLE
Fail query if it contains very large rescores

### LINKED ISSUE #17522: Very large windows_size can cause node to run OOM
**Elasticsearch version**: 2.1.x, 2.3.1 (not reproducible using 2.0.x)

**Steps to reproduce**:
 1.  Create an empty index (eg. curl -XPUT http://localhost:9200/foo)
 2.  Then run the query:

```
curl -XGET "http://localhost:9200/foo/_search" -d' 
{
  "rescore": {
    "window_size": 10000000,
    "query": {
      "match_all": {}
    }
  }
}'
```

On 2.0.x, the query will return immediately.  On 2.1x and above (including 2.3.1), the query will go to town and use CPU and memory until it OOM.

### PR DESCRIPTION
**Pull request by nik9000**
Closes #17522

### CODE REVIEW

**Comment by nik9000** [comment]
I ***HATE*** the changes that I made to Setting but it was wrong....

**Comment by jpountz** [comment]
I am not very familiar with the Settings class, what did you fix?

**Comment by nik9000** [comment]
> what did you fix?

`get(Settings, Settings)` wasn't working properly with fallback parameters. It'd never use the first `Settings`. This comes up because the new setting falls back to and old setting and the way that index settings are resolved apparently has the index's actual settings in the first slot in `get`. So the fallback wasn't working.

I'm tempted to make the new parameter not default to the old parameter but that doesn't change that the `Setting` class is still broken. The trouble is that it has so many constructors and constructor like methods that you have to fix any problems in a half dozen places.

**Comment by jpountz** [comment]
Agreed this is horrible. I opened #17931.

LGTM.

**Pull request merged**
