### PR TITLE
Improve unit test coverage of aggs

### PR DESCRIPTION
**Pull request by nik9000**
Add tests for `GlobalAggregator`, `MaxAggregator`, and `InternalMax`.

Relates to #22278

### CODE REVIEW

**Review by martijnvg — APPROVED** [review]
LGTM

**Comment by nik9000** [comment]
> LGTM

Thanks for reviewing!

**Comment by s1monw** [comment]
thanks so much for this @nik9000

**Comment by nik9000** [comment]
master: e71b26f480e7fc65c37a4862f49bd2cb54722bc3
5.x:

**Pull request merged**
