### PR TITLE
Remove index.mapper.dynamic setting

### PR DESCRIPTION
**Pull request by javanna**
This setting had been removed in the past, it was reintroduced for bw comp with 7.x with #109341. It can now be removed from main as it no longer supports indices created with 7.x .

### CODE REVIEW

**Review by martijnvg — APPROVED** [review]
LGTM

**Comment by martijnvg** [comment]
Right, I don't believe this is breaking? This setting could only be configured in 7.x. You can upgrade a 8.x cluster to 9.x if it has a 7.x index?

**Comment by javanna** [comment]
> You can upgrade a 8.x cluster to 9.x if it has a 7.x index?

no, that's not possible, you need to reindex.

**Comment by martijnvg** [comment]
> no, that's not possible, you need to reindex.

Yes, so this change on its own isn't breaking.

**Pull request merged**
