### PR TITLE
Fix eclipse project file generation

### PR DESCRIPTION
**Pull request by mark-vieira**
This will likely eventually be superseded by https://github.com/elastic/elasticsearch/pull/44075 but since that is a WiP we want to get Eclipse users unblocked on the `7.x` branch.

### CODE REVIEW

**Review by alpar-t — APPROVED** [review]

**Comment by mark-vieira** [comment]
@elasticmachine test this please

**Comment by mark-vieira** [comment]
@elasticmachine update branch

**Comment by cbuescher** [comment]
Can we backport this to at least 7.3 as well? It appears at least the "mapper-flattened" project is checked in there as well and creates the following error when creating the eclipse project files:
```
A problem occurred evaluating project ':x-pack:plugin:mapper-flattened'.
> Project with path 'plugin:core-tests' could not be found in project ':x-pack'.
```

**Comment by mark-vieira** [comment]
@cbuescher I've backported this to the `7.3` branch.

**Pull request merged**
