### PR TITLE
Packaging: Add .noarch suffix to RPM

### PR DESCRIPTION
**Pull request by spinscale**
This adds back the `.noarch` suffix to the RPM

### CODE REVIEW

**Comment by dadoonet** [comment]
LGTM.

**Comment by dadoonet** [comment]
And I guess this should go also in 2.x and master, right?

**Comment by spinscale** [comment]
can you test this against 2.0 and run the vagrant tests locally?

**Comment by spinscale** [comment]
this PR is broken. running `mvn package` produces the right name in the `target/` dir, but running `mvn install` produces `~/.m2/repository/org/elasticsearch/distribution/rpm/elasticsearch/2.0.0-beta2-SNAPSHOT/elasticsearch-2.0.0-beta2-SNAPSHOT.rpm`, because maven should totally rename the artifact another time... time to search for another option deep in the XML

**Comment by dadoonet** [comment]
WTF! So before the PR, in .m2, the artifact name was correct, right?

**Comment by spinscale** [comment]
@dadoonet not sure I understand you. The problem is that `mvn install` renames again, so where is the connection to "before that PR"? See this log

```
[INFO] Installing /~/devel/elasticsearch/distribution/rpm/target/rpm/elasticsearch/RPMS/noarch/elasticsearch-2.0.0-beta2_SNAPSHOT20150907151351.noarch.rpm to /~/.m2/repository/org/elasticsearch/distribution/rpm/elasticsearch/2.0.0-beta2-SNAPSHOT/elasticsearch-2.0.0-beta2-SNAPSHOT.rpm
```

**Comment by dadoonet** [comment]
Ah I thought this renaming was happening only because of your change within this PR...

I'm looking for another solution then.

**Comment by spinscale** [comment]
Closing this. Adding lines of XML (license checkers needs to check different artifacts, the vagrant tests need to be fixed, pom.xml) for a simple file name change is not worth the hassle.

**Pull request closed without merging**
