### PR TITLE
update for typo error

### PR DESCRIPTION
**Pull request by melson-jao**
change "for (item : list) {" to "for (item in list) {"

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?

### CODE REVIEW

**Comment by clintongormley** [comment]
Thanks for the PR.  Please could I ask you to sign the CLA so that I can merge it in?
http://www.elasticsearch.org/contributor-agreement/

@nik9000 is this change correct?

**Comment by melson-jao** [comment]
sure. CLA has been signed.
It a minor issue and thanks for the great open source product.

Regards,
Melson

2017-01-11 2:31 GMT+08:00 Clinton Gormley <notifications@github.com>:

**Comment by clintongormley** [comment]
thanks @melson-jao 

@nik9000 is this change correct?

**Comment by nik9000** [comment]
> @nik9000 is this change correct?

Sorry this took me so long to get to. I believe `:` is correct.

**Pull request closed without merging**
