### PR TITLE
Remove "best_compression" option from the ForceMergeAction

### PR DESCRIPTION
**Pull request by dakrone**
This option is only settable while the index is closed, and doesn't make sense
for a force merge.

Relates to #29823

### CODE REVIEW

**Review by talevy — APPROVED** [review]
LGTM

**Comment by wandermyz** [comment]
I was wondering if it’s removed from force merge step, in which step do I specify best_compression during the whole lifecycle?

**Comment by talevy** [comment]
Hi @wandermyz, There isn't a place in ILM that allows one to specify `best_compression`.

Since closing this issue, we've improved both the infrastructure and experience of ILM actions, so I think that Elasticsearch may be open to re-introducing this in the future.

**Comment by gwbrown** [comment]
We already have an issue open to add this back to ILM: https://github.com/elastic/elasticsearch/issues/41274

**Pull request merged**
