### PR TITLE
add missing error type mapping for apm-server monitoring

### PR DESCRIPTION
**Pull request by graphaelli**
backports #36178 to 6.x

### CODE REVIEW

**Comment by graphaelli** [comment]
run gradle build tests 2

**Comment by pickypg** [comment]
jenkins please test this

**Comment by pickypg** [comment]
run gradle build tests 2

**Review by pickypg — APPROVED** [review]
LGTM.

**Comment by graphaelli** [comment]
jenkins, retest this please

**Comment by graphaelli** [comment]
killed super long running build, pulled in latest 6.x

**Pull request merged**
