### PR TITLE
Add test suite for SingleNodeReconfigurator

### PR DESCRIPTION
**Pull request by fcofdez**

### CODE REVIEW

**Comment by fcofdez** [comment]
Looks like there's some transient infrastructure issue, build looks clean.

**Comment by fcofdez** [comment]
@elasticmachine run elasticsearch-ci/part-1

**Comment by fcofdez** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Pull request merged**
