### PR TITLE
[ML] adds support for non-numeric mapped types

### LINKED ISSUE #39974: [ML] Data frame transform silently fails if using min(timestamp)
Found in master `  "version" : {
    "number" : "8.0.0-SNAPSHOT",
    "build_flavor" : "default",
    "build_type" : "tar",
    "build_hash" : "4957cad",
    "build_date" : "2019-03-11T15:48:39.514013Z",
    "build_snapshot" : true,`

When creating a data frame using min and max against a date field, the data frame is not populated, however the response from `_stats` implies it has worked. From a user perspective, the data frame silently fails to populate (although does log an error on the server).

```
#DELETE _data_frame/transforms/farequote-a
#DELETE df-farequote-a
PUT _data_frame/transforms/farequote-a
{
  "source": "farequote-*",
  "dest": "df-farequote-a",
  "pivot": {
	  "group_by": { 
	    "airline": { "terms": { "field": "airline" }}
	  },
    "aggregations": {
	    "max_responsetime": { "max": { "field": "responsetime" }},
	    "mean_responsetime": { "avg": { "field": "responsetime" }},
	    "min_time": { "min": { "field": "@timestamp"}},
	    "max_time": { "max": { "field": "@timestamp"}}
    }
  }
}

POST _data_frame/transforms/farequote-a/_start
GET _data_frame/transforms/farequote-a/_stats
POST _data_frame/transforms/farequote-a/_stop
GET df-farequote-a/_search
```

`_stats` returns the following, which is the same as a successful data frame, i.e. one without `min_time` and `max_time`:
```
{
  "count" : 1,
  "transforms" : [
    {
      "id" : "farequote-a",
      "state" : {
        "transform_state" : "stopped",
        "current_position" : {
          "airline" : "VRD"
        },
        "generation" : 1
      },
      "stats" : {
        "pages_processed" : 2,
        "documents_processed" : 86274,
        "documents_indexed" : 19,
        "trigger_count" : 1,
        "index_time_in_ms" : 281,
        "index_total" : 1,
        "index_failures" : 0,
        "search_time_in_ms" : 6,
        "search_total" : 2,
        "search_failures" : 0
      }
    }
  ]
}
```

Error in log:
```
[2019-03-12T18:39:33,771][WARN ][o.e.x.c.i.AsyncTwoPhaseIndexer] [node1] Error while attempting to bulk index documents: failure in bulk execution:
```

### PR DESCRIPTION
**Pull request by benwtrent**
This PR does a handful of things to address the issues when creating the destination index mapping and parsing the resulting aggregations before indexing them.

The destination mapping type is taken into account now when extracting the data before putting it into the destination index. Right now all that is considered if the destination is a `Numeric` type or not, but this should not restrict more complex type requirements in the future (if they should arise). 

Future work:
* Providing multi-type `fields` mapping overrides. This should be added in tandem with our support of such in mapping deduction. Not added in this PR.
* Validations between types + Aggregations. As it stands right now, we don't really support any aggregations + types that would cause this and the indexing would simply fail on type/mapping mismatch. We should add a mechanism of alerting the user of indexing/search failure (attempt at this is: #40012)
* Add mechanisms for the end user to provide a "return type" for functions/aggregations. Certain aggregations (looking at you `bucket_script`) do not provide interfaces to accurately determine the resultant type. For this scenario the end user should provide some sort of mapping type for the field result. 

Alternative designs:
* Always use `getValueAsString`
    * Though exceedingly simple, this is a sub-optimal user experience as even numeric values get put in the `_source` as strings. This could lead to confusion, especially when considering our `_preview` endpoint. 
* Automatically determine when to use `getValueAsString` through Java type parsing
   * This restricts the user's input on the destination mapping too much. There may be use-cases where the desired type for a `integer` is actually a `keyword`.

closes #39974

### CODE REVIEW

**Comment by benwtrent** [comment]
run elasticsearch-ci/packaging-sample

**Review by davidkyle — APPROVED** [review]
LGTM

**Comment by benwtrent** [comment]
run elasticsearch-ci/bwc
run elasticsearch-ci/default-distro

**Review by hendrikmuhs — APPROVED** [review]
LGTM

**Comment by hendrikmuhs** [comment]
run elasticsearch-ci/1
run elasticsearch-ci/packaging-sample

**Comment by benwtrent** [comment]
run elasticsearch-ci/packaging-sample

**Comment by sophiec20** [comment]
does this title need amending?

**Pull request merged**
