### PR TITLE
Use the current term in a logging where it is relevant

### PR DESCRIPTION
**Pull request by ywangd**
As title says, this PR logs current term instead of last-accepted term in a logging message where the former is expected.

### CODE REVIEW

**Review by nicktindall — APPROVED** [review]
This seems sensible to me

**Review by DaveCTurner — COMMENTED** [review]
LGTM2 (we're already under the coordinator mutex here so multiple calls to `getCurrentTerm()` can't see different values)

**Review by DaveCTurner — APPROVED** [review]

**Comment by ywangd** [comment]
@elasticmachine update branch

**Comment by ywangd** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.x|[](https://github.com/elastic/elasticsearch/pull/116901)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

**Pull request merged**
