### PR TITLE
Remove type prefix support from field names in queries

### PR DESCRIPTION
**Pull request by rjernst**
This is the first part of #8872.

### CODE REVIEW

**Comment by jpountz** [comment]
Looks great, I had not anticipated it would remove so much code.

How do you plan to proceed with updating the migration guide, do you plan to do it all in the end?

**Comment by rjernst** [comment]
Thanks @jpountz.  I've added a section to the migration guide as we discussed.

**Comment by javanna** [comment]
can you please label this @rjernst ?

**Comment by clintongormley** [comment]
@rjernst could you add a link to the commit please?

If you had used `closes #9492` in the commit message then it would have been added automatically

**Comment by rjernst** [comment]
Commit is here: 6079d88

**Pull request closed without merging**
