### PR TITLE
Fix split package org.apache.lucene.document

### PR DESCRIPTION
**Pull request by ChrisHegarty**
To allow for the future modularization of Elasticsearch with Java Modules, there are a number preparatory tasks that need be completed. This is one part of one such task: eliminate split packages.

The ES class `BinaryRange` is located in the `org.apache.lucene.document` package, which is shared (thus split at runtime) with Lucene-core. A split package, in this case between Elasticsearch-core and Lucene-core, will result in a configuration error at runtime when Elasticsearch-core is deployed as a module.

The `BinaryRange` class accesses the previously package-private RangeFieldQuery class, thus requiring it to be in the same runtime package. In a recent Lucene 9.0 change, `RangeFieldQuery` has been made public, therefore `BinaryRange` no longer requires to be in the same runtime package as `RangeFieldQuery`. Moving `BinaryRange` to a non-lucene package will eliminate the split package issue mentioned above.

This PR proposes to keep `BinaryRange` in sever, but moved it to `org.elasticsearch.lucene.document`. Alternatively, since it appears that `BinaryRange` is used exclusively by code in `org.elasticsearch.percolator`, moving it to the percolator module could be reasonable.

relates #78166

### CODE REVIEW

**Comment by rjernst** [comment]
I think moving it to percolator would be good, the less stuff in server the better, but I would like @martijnvg to comment on whether there is another reason BinaryRange should be in server.

**Comment by martijnvg** [comment]
I'm +1 to moving `BinaryRange` to the percolator module. I'm not aware of any other usages of this class nor can find any usages of the class in the codebase.

**Comment by ChrisHegarty** [comment]
Thanks for the comments - moved to percolator.

**Comment by ChrisHegarty** [comment]
@elasticmachine test this please

**Comment by ChrisHegarty** [comment]
@elasticmachine update branch

**Pull request merged**
