### PR TITLE
Update shards.asciidoc

### PR DESCRIPTION
**Pull request by toritsejuFO**
Sentence correction.

### CODE REVIEW

**Comment by javanna** [comment]
Thanks @toritsejuFO that makes sense, may I ask if you signed our CLA, and in case you didn't if you could sign it that would allow us to go ahead and merge this in. Thanks!

**Comment by javanna** [comment]
ok I see now that you have signed it, thanks @toritsejuFO , my last comment has triggered a new status check which was successful, I will go ahead and merge this in. thanks again!

**Comment by javanna** [comment]
Sorry @toritsejuFO I just noticed that this PR was opened against 2.0, which is a very old branch that we no longer push fixes to. Part of the sentence is now fixed on master, please could you open a PR against master instead? I am going to close this as I can't really merge it given that this page has changed in later branches.

**Comment by toritsejuFO** [comment]
Sorry for the late reply. Alright, good to know.

**Pull request closed without merging**
