### PR TITLE
Implement the 'left' function in issue #98545

### PR DESCRIPTION
**Pull request by dreamquster**
@nik9000 
Recheck out the main branch. Refactor the 'left' function to cut the prefix string in place. But I meet a adversity that left failed the test case 'testEvaluateInManyThreads'. I find that in multiple thread situation, 
` 
EvalOperator.ExpressionEvaluator eval = evalSupplier.get();
for (int c = 0; c < count; c++) {
      assertThat(toJavaObject(eval.eval(page), 0), testCase.getMatcher());
}
`
toJavaObject function return a BytesRef with length=2, content is [81,89]. However, assertThat function in junit4 receive the BytesRef parameters that its length is 10. Can you give me some clues? I can't find which variable is mutual.

Rerun failed test case's command:
`gradlew ':x-pack:plugin:esql:test' --tests "org.elasticsearch.xpack.esql.expression.function.scalar.string.LeftTests.testEvaluateInManyThreads {TestCase=Left basic test}" -Dtests.seed=44459C172243712 -Dtests.locale=lv-LV -Dtests.timezone=Asia/Irkutsk -Druntime.java=20`

### CODE REVIEW

**Review by nik9000 — APPROVED** [review]
Ah! I found the problem. You have to make the `BytesRef` in every supplier. I pushed a fix for that. 

Otherwise looks pretty good. I pushed a few small changes - shifting things from one place to another. Adding a new test case. Correcting a test bug.

There are some instructions that would have pointed you to some of these: 
https://github.com/elastic/elasticsearch/blob/8db394570368613a833de0607233c54a0578d8aa/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/expression/function/scalar/package-info.java

I'd also like to change how we test this stuff, but that's a work in progress and I'm happy to merge this as is.

Looks like I'll be pushing a small doc fix too, but then I can merge!

**Comment by nik9000** [comment]
@elasticmachine, test this please

**Comment by nik9000** [comment]
changelogbot, there is a changelog now! be happy!

**Comment by nik9000** [comment]
@elasticmachine, test this please

**Comment by dreamquster** [comment]
> d the problem. You have to make the `BytesRef` in every supplier. I pushed a fix for that.
> 
> Otherwise looks pretty good. I pushed a few small changes - shifting things from one place to another. Adding a new test case. Correcting a test bug.

Thx

**Pull request merged**
