### PR TITLE
Make the watcher ctx unmodifiable

### PR DESCRIPTION
**Pull request by joegallo**
Changes to the `ctx` are thrown away after script execution, so it's surprising that we allow modifications to happen at all.

For some people who have been (ab)using this feature/bug, I could see the argument that this is a breaking change. OTOH this was never something we intended people to do either, and it definitely doesn't **work** (at least in the way that one might expect it to, i.e. making a change to the `ctx` in one block and being able to see those changes from elsewhere). Point is, I'm inclined to backport this to 7.x, but I'm absolutely open to objections.

/cc @nik9000 and @swallez because this relates to conversations we had earlier today.

### CODE REVIEW

**Review by martijnvg — APPROVED** [review]
I think we need to add an entry to the 8.0 breaking changes docs section and label this PR as breaking, otherwise LGTM for master branch.

**Comment by joegallo** [comment]
@martijnvg I've tweaked the labels and made some changes to the docs. Would you re-review when you've got a chance?

**Review by martijnvg — APPROVED** [review]
LGTM!

I think we should remove the 7.14 label here? The change in the 7.x will be a bit different (warning instead of error).

**Comment by jakelandis** [comment]
@joegallo - did you mean to merge this ?

**Comment by joegallo** [comment]
> @joegallo - did you mean to merge this ?

Not yet, no. The 7.16 PR would be a reimplementation so I want to have that PR up and reviewed before this goes in.

**Comment by joegallo** [comment]
@elasticmachine update branch

**Comment by joegallo** [comment]
I don't think I'm coming back for this any time soon. Closing the PR for now.

**Pull request closed without merging**
