### PR TITLE
Moving origination date settings out of ILM

### PR DESCRIPTION
**Pull request by masseyke**
In order to keep things simple for users, we plan to use the same origination date settings (`index.lifecycle.origination_date` and `index.lifecycle.parse_origination_date`) in DLM that we use in ILM. Since they are currently defined in the ILM plugin we can't access them from DLM or from DataStream in server. This PR moves the settings into IndexSettings (where most other `index.*` settings live) so that they can be used there as well as from DLM and ILM.

### CODE REVIEW

**Comment by masseyke** [comment]
This PR does not actually change DLM to take advantage of either of the settings that are being used -- that will come in follow-up PRs.

**Comment by masseyke** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by masseyke** [comment]
@elasticmachine update branch

**Comment by masseyke** [comment]
@elasticmachine run elasticsearch-ci/part-2

**Review by andreidan — APPROVED** [review]
LGTM, thanks Keith

**Comment by andreidan** [comment]
Please tag https://github.com/elastic/elasticsearch/issues/93596 in all DLM related work

**Pull request merged**
