### PR TITLE
Add reindex progress indicator

### PR DESCRIPTION
**Pull request by nik9000**
Adds a progress indicator for reindex and update_by_query requests that you
can fetch like so:

```
curl 'localhost:9200/_tasks/*/*update*?pretty&detailed'
```

```
{
  "nodes" : {
    "4_g-ViDGQxCbcum5sruV7Q" : {
      "name" : "Advisor",
      "transport_address" : "127.0.0.1:9300",
      "host" : "127.0.0.1",
      "ip" : "127.0.0.1:9300",
      "attributes" : {
        "testattr" : "test"
      },
      "tasks" : [ {
        "node" : "4_g-ViDGQxCbcum5sruV7Q",
        "id" : 10446,
        "type" : "transport",
        "action" : "indices:data/write/update/byquery",
        "description" : "300/393[updated=300,created=0,deleted=0,batches=4,versionConflicts=0]"
      } ]
    }
  }
}
```

The actual progress part of that is in the "description" field, particularly
the `300/393` bit. The rest is just metadata about how the request is going.

### CODE REVIEW

**Comment by nik9000** [comment]
@imotov have a look at the very first task management integration with reindex!

**Comment by bleskes** [comment]
@nik9000 I glanced at this and things look OK to me, but I'm not the right judge for the integration with the Task framework. It does feels very weird to me that we report progress as part of a string (description) instead of structured json. It seems that the right approach is to have a dedicated TaskInfo  but it looks like that will cause serialization issues. Maybe this is a use case for `NamedWriteableRegistry` . I'm sure you and @imotov gave it some thought - can you elaborate?

**Comment by nik9000** [comment]
We did! We decided that we didn't really have any other examples of this
yet and designing a generic system with one example is too likely to be
missengineered. I'd prefer a some streamable, toxcontent status object
rather than a taskinfo subclass but its too early to make a good call now.
So string status for a release or two.

@nik9000 <https://github.com/nik9000> I glanced at this and things look OK
to me, but I'm not the right judge for the integration with the Task
framework. It does feels very weird to me that we report progress as part
of a string (description) instead of structured json. It seems that the
right approach is to have a dedicated TaskInfo but it looks like that will
cause serialization issues. Maybe this is a use case for
NamedWriteableRegistry . I'm sure you and @imotov
<https://github.com/imotov> gave it some thought - can you elaborate?

—
Reply to this email directly or view it on GitHub
<https://github.com/elastic/elasticsearch/pull/16029#issuecomment-172296153>
.

**Comment by clintongormley** [comment]
> I'd prefer a some streamable, toxcontent status object rather than a taskinfo subclass but its too early to make a good call now. So string status for a release or two.

While I think a string is OK for now, I'd like to fix this before we release the reindex API.  I think a generic progress object basically needs something like this:

    { 
      "progress_percentage": 0.9,
      "other": {   key-values }
    }

where `other` could be named something else.... "counters"?

**Comment by imotov** [comment]
After thinking more about it, I think we should have at least 2 fields - `description`, which is static info like field and `status`. I think `description` should remain a simple string, but I can make `status` more structured if needed. If nobody opposes, I will add this to my todo list.

**Comment by nik9000** [comment]
> If nobody opposes, I will add this to my todo list.

It makes sense to me.

**Comment by bleskes** [comment]
When I read the code I took the description to be a description of the task (action is opaque). I think we should keep it like this in the task info api as well and make status be arbitrary json/object containing whatever makes sense for the given task. If this is what you mean I'm ++ :)

**Comment by imotov** [comment]
@bleskes indeed, that's what I meant

**Comment by nik9000** [comment]
I'll have to rework this one #16356 is in.

**Comment by nik9000** [comment]
OK! This is unblocked now. I'll merge #16356 into feature/reindex, rebase this on top of it, and then rework it to use the new status.

**Comment by nik9000** [comment]
I'm going to nuke an recreate this....

**Pull request closed without merging**
