### PR TITLE
throw exception when ilm-rollover-step runs on index without rollover alias

### PR DESCRIPTION
**Pull request by talevy**
The ILM Rollover Step can execute on the incorrect index if the rollover alias
exists on another valid index, but not the one the step is executing against. This
is a problem and is now guarded against

### CODE REVIEW

**Comment by talevy** [comment]
let me know if you think there should be integration tests for the same unit test. I chose to leave it out since the unit test should cover the same

**Comment by talevy** [comment]
run package tests please

**Review by AthenaEryma — APPROVED** [review]
LGTM assuming CI passes - I don't see a need for an integration test here.

**Comment by talevy** [comment]
run packaging tests

**Comment by talevy** [comment]
run sample packaging tests

**Review by dakrone — APPROVED** [review]

**Review by colings86 — APPROVED** [review]

**Pull request merged**
