### PR TITLE
Add server name to remote info API

### PR DESCRIPTION
**Pull request by jasontedor**
This commit adds the configured server_name to the proxy mode info so that it can be exposed in the remote info API.

### CODE REVIEW

**Comment by jasontedor** [comment]
@elasticmachine update branch

**Review by Tim-Brooks — APPROVED** [review]
LGTM

**Comment by alisonelizabeth** [comment]
@jasontedor / @tbrooks8 I think I may have found a bug with this change. If I create a remote cluster with the proxy mode and server_name defined (e.g., "foo"), change the server_name value (e.g., "bar") via `PUT /_cluster/settings`, then call the remote info API, the server_name field is not updated (still equals "foo"). Let me know if you'd like me to open up an issue for this. Thanks!

**Comment by tbrooks8** [comment]
There is a but and it looks like `server_name` is not dynamically updatable. I will open a PR tomorrow.

**Comment by jasontedor** [comment]
Thanks @tbrooks8.

**Comment by tbrooks8** [comment]
I opened #54107

**Pull request merged**
