### PR TITLE
Fix waiting for pidfile

### LINKED ISSUE #16717: deb's init script not waiting for pid before exiting
In the debian init script, here:
https://github.com/elastic/elasticsearch/blob/master/distribution/deb/src/main/packaging/init.d/elasticsearch#L174

The check does not work as expected and exits before the pid file is filled.
xargs exit successfully because nothing is sent to it's stdin:
```
$ cat /dev/null | xargs kill -0 ; echo $?
0
```

### PR DESCRIPTION
**Pull request by biolds**
Closes #16717

### CODE REVIEW

**Comment by clintongormley** [comment]
@nik9000 could you take a look at this please

**Comment by nik9000** [comment]
Will do on Monday.

**Comment by nik9000** [comment]
Ok - reviewed. We should totally do this. Saying you wait for the pid and not waiting is not cool. The reason this hasn't come up before is that it usually shows up quickly anyway so this is hard to test. I'll see if I can put something together.

**Comment by nik9000** [comment]
Ok - the vagrant based package tests aren't in working order at the moment (we don't run them in CI because we haven't done enough pre work) so I'll merge this sans test because its obviously better.

**Comment by nik9000** [comment]
Thanks @biolds ! I'm going to backport this to the 2.x branch as well so it'll go out with 2.3.

**Comment by nik9000** [comment]
Backported to 2.x with afbc98a47fc9b102c121c63f19581f5e74476776

**Pull request merged**
