### PR TITLE
GCE discovery plugin docs outdated

### PR DESCRIPTION
**Pull request by synhershko**

### CODE REVIEW

**Review by dadoonet — CHANGES_REQUESTED** [review]
Not exactly the same content but related to #28523 which also states that the documentation is old in general.
@synhershko Thanks for your PR but adding a `TODO` does not really fix the problem here so an issue would have been enough IMO.
I don't think we will merge it as is.

Could you propose the right steps to follow?

**Comment by synhershko** [comment]
I'd remove the machine / ES installation instructions altogether. All you need there IMO is plugin installation instructions and then configurations list with a simple sample. Basically similar to other cloud plugins docs.

**Comment by dadoonet** [comment]
> I'd remove the machine / ES installation instructions altogether. All you need there IMO is plugin installation instructions and then configurations list with a simple sample. Basically similar to other cloud plugins docs.

I agree with that.
I initially wrote those steps to help people like me who did not know the platform but that's out of the scope of this documentation indeed.

**Comment by sherry-ger** [comment]
As @dadoonet mentioned, I really like to the get started instructions as a new GCP user.  I agree it probably does not belong in the doc.  A blog is a good idea.

**Comment by cbuescher** [comment]
@dadoonet I agree we should close this and track making the updates to the GCE docs e.g. in #28523 or some new issue.

**Comment by ywelsch** [comment]
closed in favor of #28523

**Pull request closed without merging**
