### PR TITLE
Introduce PrimaryTermAndGeneration for tracking advancement of shards

### PR DESCRIPTION
**Pull request by arteam**
We recently introduced a PR (#100899) to track shards by primary term and generation, so it makes sense to make sure that we pass them both to the generation segment listeners. For that we introduce `PrimaryTermAndGeneration` objects with useful comparison capabilities.

### CODE REVIEW

**Comment by henningandersen** [comment]
I wonder if we need this in core? Can you motivate this PR a bit more? Intuitively, it is mainly a stateless concept, but if it has substantial benefits, we can discuss moving forward.

**Comment by arteam** [comment]
@henningandersen The main motivation is to be able to pass `PrimaryTermAndGeneration` to the listener in the  `addPrimaryTermAndGenerationListener` method which is declared in `Engine`.

**Comment by kingherc** [comment]
I guess this PR is mostly optional, and is refactoring instances of primary term + generation in core ES with PrimaryTermAndGeneration. @henningandersen is your concern that we should be more versatile in keeping the object in stateless so we have easier control over it, and not expose it to core ES? I am fine with either, but I am holding off reviewing until we clarify we would like the refactoring.

**Comment by arteam** [comment]
We decided to keep `PrimaryTermAndGeneration` as a stateless abstraction for the time being.

**Pull request closed without merging**
