### PR TITLE
[DOCS] Update changelog for #90302

### PR DESCRIPTION
**Pull request by lockewritesdocs**

### CODE REVIEW

**Comment by thecoop** [comment]
This fix isn't specific to windows. Also, turns out this change didn't actually fix the race condition...

**Comment by lockewritesdocs** [comment]
@thecoop, should we remove this fix from the 8.4 release notes then?

**Comment by thecoop** [comment]
Yes, turns out it was a different problem entirely.

**Comment by lockewritesdocs** [comment]
Thanks @thecoop. I removed the fix for #90302 from the 8.4.3 release notes. Closing this issue.

**Pull request closed without merging**
