### PR TITLE
Remove redundant and broken MD5 checksum from repository-s3

### PR DESCRIPTION
**Pull request by joachimdraeger**
Remove redundant and not resettable (fails on retries) check-summing. Checksums are calculated and compared by the S3 client already. #25269

### CODE REVIEW

**Comment by pickypg** [comment]
@dadoonet You probably know the most about this?

**Comment by joachimdraeger** [comment]
@abeyad, did you have a chance to have a look? Thanks.

**Review by abeyad — APPROVED** [review]
LGTM, great find @joachimdraeger !  Thank you for reporting and fixing it.

**Comment by abeyad** [comment]
5.x commit: b73adbe6cb8ab501cf6c8c9bbfe3468996e424ce
5.5 commit: 280014a3479700f2175776191b7982d955c3582f
5.4 commit: 913badda0de0772bbf354f4c539a4d9446a33dce

**Comment by joachimdraeger** [comment]
Thanks for your review and merge, @abeyad

**Pull request merged**
