### PR TITLE
ILM: add frozen phase

### PR DESCRIPTION
**Pull request by andreidan**
This adds a frozen phase to ILM that will allow the execution of the
set_priority, unfollow, allocate, freeze and searchable_snapshot actions.

The frozen phase will be executed after the cold and before the delete phase.

Relates to #60848

### CODE REVIEW

**Comment by dakrone** [comment]
Can you add an integration test for this also? Just something that makes sure the parsing and all that for `"frozen": {"actions": ...}` works correctly?

**Comment by andreidan** [comment]
> Can you add an integration test for this also? Just something that makes sure the parsing and all that for `"frozen": {"actions": ...}` works correctly?

@dakrone I've added a frozen phase to the full policy we use in integration tests (so an allocation action will be executed in the frozen phase in a few integration tests already) https://github.com/elastic/elasticsearch/pull/60983/files#diff-10033c7c446c648bcb131cf7ad168cbdR170
The full execution of a full policy is tested here https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/ilm/qa/multi-node/src/test/java/org/elasticsearch/xpack/ilm/TimeSeriesLifecycleActionsIT.java#L112

Do you think we need to add more phase based testing?

**Comment by dakrone** [comment]
@andreidan for some reason I was thinking that was transport based rather than REST based, so nevermind on that!

**Review by dakrone — APPROVED** [review]
LGTM, I'm glad this was smaller than I thought it was going to be!

**Pull request merged**
