### PR TITLE
Return clear error message if aggregation type is invalid

### PR DESCRIPTION
**Pull request by gaobinlong**
Relates to #58146.

The main changes are:

1. Catch the `NamedObjectNotFoundException` when parsing aggregation type, and then throw a `ParsingException` with clear error message with hint.
2. Add a unit test method: AggregatorFactoriesTests#testInvalidType().

### CODE REVIEW

**Review by nik9000 — APPROVED** [review]
Great! I was just starting to do this and I got distracted. You work matches what I'd started to do exactly!

Looks good to me.

@elasticmachine, ok to test.

**Comment by nik9000** [comment]
@elasticmachine, ok to test.

**Comment by nik9000** [comment]
@gaobinlong, it looks like `AggregationConfigTests` was asserting on the error message. Could you update the assertion?

**Comment by gaobinlong** [comment]
@nik9000， I have done that and all checks have passed yet.

**Comment by nik9000** [comment]
@elasticmachine, test this please

**Comment by nik9000** [comment]
@elasticmachine, update branch

**Comment by nik9000** [comment]
@elasticmachine update branch

**Comment by nik9000** [comment]
Thanks @gaobinlong! I've merged and will backport to 7.x.

**Comment by nik9000** [comment]
And I finally merged the backport! That took a while, entirely because I took a long weekend and then got sick. But not it'll be shipped out with 7.9. Thanks again for the change, @gaobinlong ! I'm quite happy that we have "did you mean" on this now too!

**Comment by gaobinlong** [comment]
@nik9000 , take good care of yourself, and thanks for your review, I'm glad to do more work on elasticsearch!

**Comment by nik9000** [comment]
> @nik9000 , take good care of yourself, and thanks for your review, I'm glad to do more work on elasticsearch!

I will and good luck with any other contributions you make. Thanks again!

**Pull request merged**
