### PR TITLE
Rename core module to server

### PR DESCRIPTION
**Pull request by Tim-Brooks**
This is related to #27933. It renames the core module to server. This is
the first step towards introducing an elasticsearch-core jar.

### CODE REVIEW

**Comment by tbrooks8** [comment]
This is a backport of https://github.com/elastic/elasticsearch/pull/28180

**Comment by rjernst** [comment]
@tbrooks8 Were there any changes you had to make in the backport that necessitate a PR?

**Comment by tbrooks8** [comment]
Files that had been deleted on master had to be moved in 6.x. Files that had been added on master had to be deleted from the new server module. That’s why I wanted a CI run @rjernst. There is no new code written.

**Review by jasontedor — APPROVED** [review]
LGTM.

**Pull request merged**
