### PR TITLE
Fix 'else if' formatting

### PR DESCRIPTION
**Pull request by sabi0**
A bug in Eclipse Code Formatter [1] causes extra indentation after 'else if' with a line break in condition:
```
                        if (argumentTypes.length == 2
                            && argumentTypes[0].equals(STRING_CLASS)
                            && argumentTypes[1].equals(OBJECT_ARRAY_CLASS)) {
                            checkArrayArgs(methodNode, logMessageFrames[i], arraySizeFrames[i], lineNumber, methodInsn, 0, 1);
                        } else if (argumentTypes.length == 2
                            && argumentTypes[0].equals(STRING_CLASS)
                            && argumentTypes[1].equals(OBJECT_CLASS)) {
                                checkFixedArityArgs(methodNode, logMessageFrames[i], lineNumber, methodInsn, 0, 1);
                            } else if (argumentTypes.length == 3
                                && argumentTypes[0].equals(STRING_CLASS)
                                && argumentTypes[1].equals(OBJECT_CLASS)
                                && argumentTypes[2].equals(OBJECT_CLASS)) {
                                    checkFixedArityArgs(methodNode, logMessageFrames[i], lineNumber, methodInsn, 0, 2);
                                } else if (argumentTypes.length == 3
                                    && argumentTypes[0].equals(STRING_CLASS)
                                    && argumentTypes[1].equals(OBJECT_ARRAY_CLASS)
                                    && argumentTypes[2].equals(THROWABLE_CLASS)) {
                                        checkArrayArgs(methodNode, logMessageFrames[i], arraySizeFrames[i], lineNumber, methodInsn, 0, 1);
```

A workaround suggested in one of the bug comments is to disable "Keep 'else' statement on same line" option.
This indeed fixes the problem. But unfortunately also affects `else return ...` statements that are then split in two lines.

I tried to reduce "eye sore" by removing the unnecessary 'else' before 'return'. That's in the second commit.
Please tell me if you think that's too much and I will drop it.

[1] https://bugs.eclipse.org/bugs/show_bug.cgi?id=548910

### CODE REVIEW

**Comment by williamrandolph** [comment]
This relates to https://github.com/elastic/elasticsearch/pull/102382 . In the course of reviewing that PR, we found that the inconsistent indentation requirement was confusing.

**Comment by williamrandolph** [comment]
In order to make this a little cleaner, I've made a PR that will separately use CheckStyle to require braces around all `else` clauses: #103217

If that gets merged, then this PR should reduce almost completely to a change in whitespace.

I'd also like to note that the classes `PainlessParser`, `SqlBaseParser`, and `EqlBaseParser` are generated by ANTLR and shouldn't be manually modified. I think it's fine if spotless formats them, but the redundant `else` is generated code and will just come back when the code is regenerated.

I'll report back once #103217 is reviewed, because I think that will make things smoother here.

**Comment by sabi0** [comment]
Thank you for mentioning the parsers. I missed the "do not edit" comment at the top.
I guess I did not expect auto-generated code under version control.
Any particular reason why they are not generated on-the-fly during build?

P.S. I will take care of the conflicts when #103217 is settled.

**Comment by williamrandolph** [comment]
In a team discussion, we decided that we didn't want to require braces on `else` without requiring them on `if`, and that requiring braces on `if` would require too large of a code change (adding several thousand lines of code). We'd prefer to wait for the upstream fix in the Eclipse Code Formatter. I opened issue https://github.com/elastic/elasticsearch/issues/104162 to track the problem.

Thank you for your patience and willingness to work with us on this, and for diagnosing this issue in the first place. I hope it's all right if I close the PR.

**Comment by sabi0** [comment]
This is the most pragmatic decision.
Though looking at the ECF bug I would not expect this to be fixed soon.
Maybe I should give it a try...

**Pull request closed without merging**
