### PR TITLE
Collapse transport versions 8500040+ into 8500061

### PR DESCRIPTION
**Pull request by thecoop**
Collapse transport versions 8,500,040-8,500,061 into 8,500,061 (used by 8.10 release)

### CODE REVIEW

**Comment by thecoop** [comment]
@elasticmachine update branch

**Comment by thecoop** [comment]
@elasticmachine update branch

**Review by ldematte — APPROVED** [review]
LGTM. Just out of curiosity: how do you find which versions are safe to collapse? Via git history I suppose?

**Comment by thecoop** [comment]
Yup, git history as in the comments in the file

**Comment by thecoop** [comment]
@elasticmachine update branch

**Pull request merged**
