### PR TITLE
[Tests] Merge two document mapper ESSingleNodeTests

### PR DESCRIPTION
**Pull request by cbuescher**
Just found a TODO in DocumentMapperParserTests that this test can probably
merged with another similar ESSingleNodeTestCase and just moved the existing
methods to DocumentMapperMergeTests.java. Since the name now is a bit too
specific also renamed this to just DocumentMapperTests.java

### CODE REVIEW

**Comment by colings86** [comment]
Whilst I don't have very strong feelings against doing this change I do think its a bit of a strange thing for us to do and would like to understand what it buys us?

 The reason I think its strange is that before this change we have a `DocumentMapperParserTests` suite which tests the class `DocumentMapperParser` and `DocumentMapper[Merge]Tests` which tests the `DocumentMapper`. So finding the test suite for each class is easy and intuitive (I do agree that `DocumentMapperMergeTests` could do with being renamed to `DocumentMapperTests`). 

Since these are both unit test suites I don't think there is much advantage in combining them around test suite overhead and the two suites are testing different classes and behaviours.

**Comment by colings86** [comment]
Its also worth noting that when the TOD was added the `DocumentMapperParserTests` suite (had a different name then) contained only one test method whereas now there are multiple test methods: https://github.com/elastic/elasticsearch/commit/7a7bd6086a9432884e9cdca359f805486a0155ac#diff-719609d41482e260172e4625036927a4

**Comment by cbuescher** [comment]
> Since these are both unit test suites

I was under the impression that the ESSingleNodeTests (which they both are) take a bit longer to start, but maybe that isn't the case anymore or negligible. But that was part of the reasoning I had.

> two suites are testing different classes and behaviours.

I agree, but the name DocumentMapperMergeTests suggested its only testing parts of DocumentMappers behaviour, while DocumentMapperParserTests indeed seems to test DocumentMapperParser. 

> when the TODO was added the `DocumentMapperParserTests` suite (had a different name then) contained only one test method

Thanks for pulling that up, this indeed explains the TODO. 
In general I thought this PR much more of a proposal, if you think its confusing you can simply close it, I don't mind really.

**Comment by colings86** [comment]
I think renaming `DocumentMapperMergeTests` to `DocumentMapperTests` makes sense regardless. I would be +1 for that change but I think my preference (happy for others to disagree and go in a different direction) would be to retain the two test suites separately

**Comment by cbuescher** [comment]
@colings86 thanks, lets just do that then. I also removed the outdated TODO.

**Review by colings86 — APPROVED** [review]
LGTM

**Pull request merged**
