### PR TITLE
Enable run_as for all authentication schemes

### PR DESCRIPTION
**Pull request by ywangd**
This PR removes the restriction for run_as so the authenticated user
does not have to be authenticated by a realm. It can now also be either
an API key, a token or a service account. Note we don't currently have
a service account that has run_as privilege.

This PR also include a change to the existing internal behaviour: the
final authentication object created for run-as now keeps information of
the authenticated user instead of dropping them. For example, metadata
associated with the original authentication is preserved. If the
original authentication is an API key, the final authentication will
have authentication type as "api_key" as well.

### CODE REVIEW

**Review by tvernum — COMMENTED** [review]
I left some comments - we might want to discuss it directly next week.

I like where this is going, but I think there's a concept missing somewhere in our set of Authentication classes, and that makes it more complex than it needs to be.

**Comment by ywangd** [comment]
@tvernum and I discussed in a separate channel and agreed that there are work needs to be done for the `Authentication` class so it's easier to reason about and use. We also agreed that it should be separate PRs and keep this one mostly as is. I raised #80117 and we agree to prioritize it once this PR is merged.

**Review by tvernum — APPROVED** [review]

**Comment by legrego** [comment]
@ywangd does this resolve https://github.com/elastic/elasticsearch/issues/51910?

**Comment by ywangd** [comment]
> @ywangd does this resolve #51910?

Yes it does. Forgot that we have this issue. I will close it. Thanks for the reminder.

**Pull request merged**
