### PR TITLE
Fix LongScriptFieldTypeTests with sorts

### LINKED ISSUE #78315: [CI] LongScriptFieldTypeTests testNow failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/gm3mgt56cw26e/tests/:server:test/org.elasticsearch.index.mapper.LongScriptFieldTypeTests/testNow

**Reproduction line:**
`./gradlew ':server:test' --tests "org.elasticsearch.index.mapper.LongScriptFieldTypeTests.testNow" -Dtests.seed=E319CC5B4F2EADC5 -Dtests.locale=th -Dtests.timezone=Greenwich -Druntime.java=11`

**Applicable branches:**
master

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.index.mapper.LongScriptFieldTypeTests&tests.test=testNow

**Failure excerpt:**
```
java.lang.NullPointerException: (No message provided)

  at __randomizedtesting.SeedInfo.seed([E319CC5B4F2EADC5:7E10B7AAC59030A9]:0)
  at java.util.TreeMap.getEntry(TreeMap.java:345)
  at java.util.TreeMap.get(TreeMap.java:277)
  at org.apache.lucene.index.ParallelLeafReader.getPointValues(ParallelLeafReader.java:384)
  at org.apache.lucene.search.comparators.NumericComparator$NumericLeafComparator.<init>(NumericComparator.java:92)
  at org.apache.lucene.search.comparators.LongComparator$LongLeafComparator.<init>(LongComparator.java:65)
  at org.elasticsearch.index.fielddata.fieldcomparator.LongValuesComparatorSource$1$1.<init>(LongValuesComparatorSource.java:96)
  at org.elasticsearch.index.fielddata.fieldcomparator.LongValuesComparatorSource$1.getLeafComparator(LongValuesComparatorSource.java:96)
  at org.apache.lucene.search.FieldValueHitQueue.getComparators(FieldValueHitQueue.java:176)
  at org.apache.lucene.search.TopFieldCollector$TopFieldLeafCollector.<init>(TopFieldCollector.java:64)
  at org.apache.lucene.search.TopFieldCollector$SimpleFieldCollector$1.<init>(TopFieldCollector.java:196)
  at org.apache.lucene.search.TopFieldCollector$SimpleFieldCollector.getLeafCollector(TopFieldCollector.java:196)
  at org.apache.lucene.search.FilterCollector.getLeafCollector(FilterCollector.java:38)
  at org.apache.lucene.search.AssertingCollector.getLeafCollector(AssertingCollector.java:45)
  at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:745)
  at org.apache.lucene.search.AssertingIndexSearcher.search(AssertingIndexSearcher.java:73)
  at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:679)
  at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:673)
  at org.apache.lucene.search.IndexSearcher.searchAfter(IndexSearcher.java:653)
  at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:570)
  at org.elasticsearch.index.mapper.LongScriptFieldTypeTests.testNow(LongScriptFieldTypeTests.java:137)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:566)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:834)

```

### PR DESCRIPTION
**Pull request by mayya-sharipova**
Disable sort optimization with points for comparators used in
scripts, as they don't provide points.

This is a temporary fix, for a permanent fix these comparators
should implement getPoints once LUCENE-10154 is available.

Closes #78315

### CODE REVIEW

**Review by jtibshirani — COMMENTED** [review]
Maybe it'd be better to have script fields use a non-null field name? It doesn't feel solid to rely on the fact that most readers leniently handle `null`.

**Comment by mayya-sharipova** [comment]
@jtibshirani Thanks for the comment. I don't know the history behind why we are [passing `null`](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/index/fielddata/fieldcomparator/LongValuesComparatorSource.java#L93)  as a field name to LongValuesComparatorSource, so I don't have enough knowledge to make this change. May be @jpountz  has more insights.

This test change seems to me very safe, besides we never use ParallelLeafReader where the test fails in elasticsearch.

**Comment by mayya-sharipova** [comment]
@jimczi  I am interested in your opinion.  Are you ok if we replace `newSearcher` with `new IndexSearcher` to fix the test failure, as the test continues to fail.

**Comment by jimczi** [comment]
> Are you ok if we replace newSearcher with new IndexSearcher to fix the test failure, as the test continues to fail.

What about disabling the sort optimization when we create the LongComparator in LongValuesComparatorSource#newComparator ? That seems needed since the optimization is enabled by default in Lucene 9 and we create doc values dynamically.

**Comment by jpountz** [comment]
In my opinion, the main bug here is that Lucene would still check points on the provided field name even though `getNumericDocValues` is overridden. We should probably have a protected `getPointValues` plus documentation on both `getNumericDocValues` and `getPointValues` that both methods need to be consistent.

The `lucene/expression` module uses the string representation of the expression as a field name. I think we could document that it's ok to use a dummy value for the field name - including `null` - as long as both `getNumericDocValues` and `getPointValues` are overridden.

**Comment by mayya-sharipova** [comment]
@jpountz Thanks a lot for you suggestions.

> In my opinion, the main bug here is that Lucene would still check points on the provided field name even though getNumericDocValues is overridden. We should probably have a protected getPointValues plus documentation on both getNumericDocValues and getPointValues that both methods need to be consistent.

Here you are talking about adding `getNumericDocValues` method in `NumericComparator`?  What is "consistent" here,  are suggesting to add documentation that says that if you override `getNumericDocValues`, you must also override `getPointValues`?

Then on elasticsearch side  `LongValuesComparatorSource::newComparator` will return `null` for `getPointValues`? Right?

---

While we are waiting for these changes, meanwhile in order to have this text fixed is it ok to a temporary fix as suggested PR with an added TODO in test to return it back and added TODO LongValuesComparatorSource to implement `getPointValues`?

**Comment by jpountz** [comment]
> Here you are talking about adding getPointValues method in NumericComparator?

Yes.

> What is "consistent" here, are suggesting to add documentation that says that if you override getNumericDocValues, you must also override getPointValues?

Almost certainly, yes? The optimization relies on the assumption that points and doc values record the same information. Yet if you extend `getNumericDocValues` it almost certainly means that whatever `PointValues` NumericComparator is going to look at shouldn't be used to skip non-competitive documents?

**Comment by jpountz** [comment]
I'm fine with merging the temporary fix until we have a better one.

**Comment by mayya-sharipova** [comment]
@jpountz  Thanks for your feedback, I've put your proposal into a new [LUCENE-10154 issue](https://issues.apache.org/jira/browse/LUCENE-10154)

I thought more about this, and as a temporarily fix I think it would better to keep tests as before, and instead go with @jimczi's proposal to `disableSkipping` in these comparators with added to do to implement `getPoints` once `LUCENE-10154` is implemented and available.

**Comment by mayya-sharipova** [comment]
In 2a17de2584b8c9c2ca157449dcf8f302ba1b744b, I've disabled sort optimization on script comparators. Would appreciate review from somebody.

**Review by nik9000 — COMMENTED** [review]
This is what I was thinking of doing, yeah. I'm happy with it, but probably worth some of the folks above me having another look.

**Review by jimczi — APPROVED** [review]
LGTM

**Pull request merged**
