### PR TITLE
Synthetic source: Support ignore_above for keyword fields

### PR DESCRIPTION
**Pull request by nik9000**
Support `ignore_above` for `keyword` fields, but only when they don't
have sub-fields. If you send a field longer than `ignore_above` then
it'll *vanish*. It won't come back from the synthetic `_source` because
it wasn't saved anywhere.

### CODE REVIEW

**Comment by nik9000** [comment]
I was thinking it'd be *lovely* if we could store the field in stored fields if it was over the limit and we could use it for synthesis. That's a bit trickier. It needs #87480 plus some more machinery.

**Review by romseygeek — APPROVED** [review]
LGTM.  Do you think we should add something to the docs to warn about this behaviour, as I think it's reasonable but not necessarily obvious at first thought?

**Comment by nik9000** [comment]
> LGTM. Do you think we should add something to the docs to warn about this behaviour, as I think it's reasonable but not necessarily obvious at first thought?

Yeah. It's going to want docs. Sorry. I forgot.

**Comment by nik9000** [comment]
I'm abandoning this in favor of a real implementation of `ignore_above` based on the work I've put together in #87480.

**Pull request closed without merging**
