### PR TITLE
Reenable Checkstyle's unused import rule

### PR DESCRIPTION
**Pull request by tlrx**
Now most unused imports have been removed in #31207, we can enable the `UnusedImports` check in Checkstyle. It does a good job with latest version of Checkstyle (updated in #31269).

When a `{@link Something}` javadoc comment is used in a comment block (non-javadoc), the class must be fully qualified.

### CODE REVIEW

**Review by jasontedor — APPROVED** [review]
LGTM. Thank you for this!

**Comment by ywelsch** [comment]
I would prefer if we could merge this PR only to master branch. Otherwise we will have even more times that CI fails when backporting stuff... We could revisit this then once we have better support for backport testing.

**Comment by jasontedor** [comment]
I disagree with this. We should already be testing locally before backporting, we shouldn't be punching cherry-picks in without even running the bare minimum. We already have a problem today where we remove an import in master that is still needed in 6.x, and it's clear that cherry-picks get pushed without even running compilation because we see follow-up commits to add back missing imports.

**Comment by tlrx** [comment]
While I understand @ywelsch concerns, I also think that we should enforce this on 6.x too. Many unused imports are also introduced when backporting pull requests, and in the few days I worked on this pull request and #31207 I saw multiple unused imports being introduced in the codebase on both master and 6.x branches.

**Comment by javanna** [comment]
+1 , great to get rid of unused imports once and forever

**Comment by ywelsch** [comment]
> We should already be testing locally before backporting, we shouldn't be punching cherry-picks in without even running the bare minimum.

You mean like this: https://github.com/elastic/elasticsearch/pull/31304 🔥

**Comment by jasontedor** [comment]
I did run tests locally; I have no explanation for why this happened. That said, I am sorry that it happened, I wish I understood why it happened so that I could avoid it in the future.

**Comment by tlrx** [comment]
@jasontedor Well, it happens once in a while for everybody. Don't be sorry, we are humans after all.

I talked to @ywelsch and he's not vetoing this change. I consider that at least four people were in favor of this change for both master and 6.x branches, I merged it to both branches earlier today. I'll manage CI failures for today and if it appears to be counter productive on CI then we'll still be able to revert it.

**Pull request merged**
