### PR TITLE
[CI] Fix year of week formatting when using joda time

### LINKED ISSUE #66907: Reproducible Failure in org.elasticsearch.cluster.metadata.DateMathExpressionResolverTests.testExpression_MixedArray
This fails and reproduces for me locally 100% of the time on master:

```
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.cluster.metadata.DateMathExpressionResolverTests.testExpression_MixedArray" -Dtests.seed=DD523116F9B24D8C -Dtests.security.manager=true -Dtests.locale=is-IS -Dtests.timezone=Europe/Warsaw -Druntime.java=15

org.elasticsearch.cluster.metadata.DateMathExpressionResolverTests > testExpression_MixedArray FAILED
    java.lang.AssertionError: 
    Expected: ".logstash-2021.01"
         but: was ".logstash-2020.01"
        at __randomizedtesting.SeedInfo.seed([DD523116F9B24D8C:794B3FD6F49CA76C]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.cluster.metadata.DateMathExpressionResolverTests.testExpression_MixedArray(DateMathExpressionResolverTests.java:125)


Suite: Test class org.elasticsearch.cluster.metadata.DateMathExpressionResolverTests
  1> [2021-01-02T16:24:50,530][INFO ][o.e.c.m.DateMathExpressionResolverTests] [testExpression_MixedArray] before test
  1> [2021-01-02T16:24:50,617][INFO ][o.e.c.m.DateMathExpressionResolverTests] [testExpression_MixedArray] after test
  2> REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.cluster.metadata.DateMathExpressionResolverTests.testExpression_MixedArray" -Dtests.seed=DD523116F9B24D8C -Dtests.security.manager=true -Dtests.locale=is-IS -Dtests.timezone=Europe/Warsaw -Druntime.java=15
  2> java.lang.AssertionError: 
    Expected: ".logstash-2021.01"
         but: was ".logstash-2020.01"
        at __randomizedtesting.SeedInfo.seed([DD523116F9B24D8C:794B3FD6F49CA76C]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.cluster.metadata.DateMathExpressionResolverTests.testExpression_MixedArray(DateMathExpressionResolverTests.java:125)
  2> NOTE: leaving temporary files on disk at: /home/brownbear/src/elasticsearch/server/build/testrun/test/temp/org.elasticsearch.cluster.metadata.DateMathExpressionResolverTests_DD523116F9B24D8C-002
  2> NOTE: test params are: codec=Asserting(Lucene87): {}, docValues:{}, maxPointsInLeafNode=878, maxMBSortInHeap=6.27231052818936, sim=Asserting(RandomSimilarity(queryNorm=true): {}), locale=is-IS, timezone=Europe/Warsaw
  2> NOTE: Linux 5.8.0-33-generic amd64/AdoptOpenJDK 15.0.1 (64-bit)/cpus=48,threads=1,free=524039296,total=536870912
  2> NOTE: All tests run in this JVM: [DateMathExpressionResolverTests]

Tests with failures:
 - org.elasticsearch.cluster.metadata.DateMathExpressionResolverTests.testExpression_MixedArray

```

### PR DESCRIPTION
**Pull request by ywangd**
Based on the joda-time [documentation](https://www.joda.org/joda-time/key_format.html), the symbol for "year of the week" is `x` as opposed to `Y` (used by java's DateTimeFormatter). This PR fixes the test code to use the correct date formatting symbol.

Resolves: #66907

### CODE REVIEW

**Comment by romseygeek** [comment]
I'm not sure this is the correct fix.  Why is `{now/M{YYYY.MM}}` getting resolved to `2020.01` when we're in 2021?

**Comment by romseygeek** [comment]
OK, having read https://www.alexcorrigan.co.uk/blog/20191231-0644-javas-week-based-year-datetimeformatter/ I understand what the issue is - `{now/M{YYYY.MM}}` is resolving the week-based year as of the first of January, which falls in a week in which the Thursday is in 2020.  I think this might be better fixed by changing the expression to be `{now/M{yyyy.MM}}` which looks like something a user might actually want to do?

**Review by pgomulka — COMMENTED** [review]
This test is based on joda format (was possibly missed when migrating) and Y meant year of era in joda.
It should be changed to uuuu when using java.time

**Comment by pgomulka** [comment]
> I'm not sure this is the correct fix. Why is {now/M{YYYY.MM}} getting resolved to 2020.01 when we're in 2021?

 in week based calendar 01-03.01.2021 are still in 2020. The first week of 2021 starts on Monday 4th. This is because it requires first week to contain minimum 4 days in new year. Also Monday is the first day fo the week per ISO rule.

**Comment by ywangd** [comment]
> This test is based on joda format (was possibly missed when migrating) and Y meant year of era in joda.
> It should be changed to uuuu when using java.time

If the intention is to use "year-of-era", I can change the date-math-expression to use `yyyy` (year-of-era for java DateTimeFormmatter) instead of changing the assertion code, i.e. something like the follows:
```diff
@@ -115,7 +115,7 @@ public class DateMathExpressionResolverTests extends ESTestCase {

     public void testExpression_MixedArray() throws Exception {
         List<String> result = expressionResolver.resolve(context, Arrays.asList(
-                "name1", "<.marvel-{now/d}>", "name2", "<.logstash-{now/M{YYYY.MM}}>"
+                "name1", "<.marvel-{now/d}>", "name2", "<.logstash-{now/M{yyyy.MM}}>"
         ));
         assertThat(result.size(), equalTo(4));
         assertThat(result.get(0), equalTo("name1"));
```

Alternatively, we can change both date-math-expression and the assertion to use simply "year", i.e. `uuuu` for java DateTimeFormatter and `yyyy` for the assertion. Which one would you suggest that is closer to the actual intention?

**Comment by pgomulka** [comment]
@ywangd I would change YYYY in this test to yyyy (in both assertion and the date math expression)

**Comment by ywangd** [comment]
> @ywangd edit - you are right. it should be uuuu in the date math, and yyyy in assertion as the assertion is still using joda. We should migrate this test in another PR

Thanks @pgomulka The PR is updated as discussed.

**Review by pgomulka — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
