### PR TITLE
add missing error type mapping for apm-server

### PR DESCRIPTION
**Pull request by graphaelli**
An additional error type was introduced with APM Server for 6.5 but the corresponding mapping update was missed.

for elastic/apm-server#1614

cc @simitt

### CODE REVIEW

**Review by simitt — APPROVED** [review]

**Comment by not-napoleon** [comment]
@graphaelli - Can you add a version tag to this when you have a chance, please?

**Comment by graphaelli** [comment]
seemingly unrelated failure on `org.elasticsearch.indices.state.RareClusterStateIT.testDelayedMappingPropagationOnPrimary`, just apparently hasn't been a regular issue in years.  Pulled in latest master and hoping for the best.

**Comment by graphaelli** [comment]
jenkins, retest this please

**Comment by graphaelli** [comment]
more unrelated failures, pulled in latest master again

**Review by pickypg — APPROVED** [review]
LGTM

**Comment by graphaelli** [comment]
jenkins, retest this please

**Pull request merged**
