### PR TITLE
Better UUID for reader context

### PR DESCRIPTION
**Pull request by dnhatn**
We can use a single and stronger UUID for all reader contexts created by the same SearchService.

### CODE REVIEW

**Comment by dnhatn** [comment]
run elasticsearch-ci/packaging-sample-windows

**Review by jimczi — APPROVED** [review]
The change makes sense to me. I wonder if we should also enforce a valid session id when removing/getting a reader context:
https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/search/SearchService.java#L608
Currently we return the reader if the provided session id is empty but we should instead throw an error in such a case ? At least on PIT readers since they should always have a session id attached.

**Comment by dnhatn** [comment]
@elasticmachine test this please

**Comment by dnhatn** [comment]
Thanks Jim!

**Pull request merged**
