### PR TITLE
Tribe nodes should apply cluster state updates in batches

### PR DESCRIPTION
**Pull request by jasontedor**
This commit applies the general mechanism for applying cluster state updates in batches to tribe nodes.

Relates #14899, relates #14725

### CODE REVIEW

**Comment by jasontedor** [comment]
@bleskes I'll rebase this pull request on master when #14899 is reintegrated there. The salient commit for this review is thus fca001e665e505f172ba4254794c189a47d03010 pending #14899.

**Comment by jasontedor** [comment]
@bleskes I've rebased this pull request on the latest changes from #14899.

**Comment by jasontedor** [comment]
@bleskes This pull request has been rebased on master since #14899 has been integrated there.

**Comment by bleskes** [comment]
I think we can go further with this one. Now it just saves on cluster state update task, but the work done is the same. I think each executor can pick the latest task (double check that batching maintains order, it should :)) and only apply that. 

We could in theory  also  have a global executor (i.e., for all clients) which takes the tasks, groups them by source cluster and applies them to a shared builder but then we run the risk of exceptions in one client blocking updates from all client. I don't think it's worth it.

**Comment by jasontedor** [comment]
> I think we can go further with this one.

@bleskes Addressed in 74adaca4cebd9c0fde32a5080d7cfbbf2dbe9746.

**Comment by jasontedor** [comment]
@bleskes In addition to 74adaca4cebd9c0fde32a5080d7cfbbf2dbe9746, I also pushed 479e50adb26b2f5453841273c05cdb17c530065e to only return a new cluster state instance in the tribe service if there were changes to the cluster state.

**Comment by bleskes** [comment]
LGTM. Double checking - do we have a test that makes sure tasks are passed in order?

**Comment by jasontedor** [comment]
> LGTM. Double checking - do we have a test that makes sure tasks are passed in order?

I don't think so; should we address that in a separate issue?

**Comment by bleskes** [comment]
> I don't think so; should we address that in a separate issue?

++ on another issue.. It's an important semantics. We should test it under heavy concurrency.

**Comment by jasontedor** [comment]
> ++ on another issue.. It's an important semantics. We should test it under heavy concurrency.

I opened #15483 to track this.

**Comment by jasontedor** [comment]
Integrated to master in 709740efd2dac87f58888c7ef00937a7b2e20776 and backported to 2.x in 8fa5c68d6a245bff864ad6edecfed6b1c3227a34.

**Pull request merged**
