### PR TITLE
[6.2] [Docs] Add example for updating meta field (#35893)

### PR DESCRIPTION
**Pull request by geekpete**
Backports the following commits to 6.2:
 - [Docs] Add example for updating meta field  (#35893)

### CODE REVIEW

**Comment by lcawl** [comment]
The failure of the docs checks in this branch are expected per https://github.com/elastic/infra/issues/8316

**Comment by lcawl** [comment]
When I run ./gradlew -p docs check locally, it fails with this error:
> ...
>  1> [2019-01-31T16:59:46,636][INFO ][o.e.s.DocsClientYamlTestSuiteIT] [test > {yaml=reference/mapping/fields/meta-field/line_9}]: before test
>  1> [2019-01-31T16:59:46,855][INFO ][o.e.s.DocsClientYamlTestSuiteIT] Stash dump on test failure [{
> 1>   "stash" : {
 >  1>     "body" : {
 >  1>       "error" : {
 >  1>         "root_cause" : [
 > 1>           {
 >  1>             "type" : "illegal_argument_exception",
 > 1>             "reason" : "Rejecting mapping update to [my_index] as the final mapping would have more than 1 type: [_doc, user]",
>   1>             "stack_trace" : "[Rejecting mapping update to [my_index] as the final mapping would have more than 1 type: [_doc, user]]; nested: IllegalArgumentException[Rejecting mapping update to [my_index] as the final mapping would have more than 1 type: [_doc, user]];

**Comment by lcawl** [comment]
The book itself builds fine, however, using the docbldesold alias in https://github.com/elastic/docs/blob/master/doc_build_aliases.sh

**Comment by geekpete** [comment]
Looks like I need to adjust for the older version where the type should be /doc and not  /_doc, so I'll fix that.

**Review by lcawl — APPROVED** [review]
LGTM and builds successfully (with docbldes alias)

**Pull request merged**
