### PR TITLE
Remove support for Visio and potm files

### PR DESCRIPTION
**Pull request by dadoonet**
Related to #22077

This PR comes with 2 changes, one for `ingest-attachment` and the other for `mapper-attachments`.
It's essentially a backport of #22079 for 5.x series.

## Ingest Attachment Plugin

* Send a non supported document to an ingest pipeline using `ingest-attachment`
* If Tika is not able to parse the document because of a missing class (we are not importing all jars needed by Tika), Tika throws a Throwable which is not catch.

This commit removes support for Visio and POTM office files.

So elasticsearch is not killed anymore when you run a command like:

```
GET _ingest/pipeline/_simulate
{
  "pipeline" : {
    "processors" : [
      {
        "attachment" : {
          "field" : "file"
        }
      }
    ]
  },
  "docs" : [
    {
      "_source" : {
        "file" : "BASE64CONTENT"
      }
    }
  ]
}
```

The good news is that it does not kill the node anymore and allows to extract the text which is in the Office document even if we have a Visio content (which is not extracted anymore).

## Mapper Attachments Plugin

* Parse a non supported document using `mapper-attachments`
* If Tika is not able to parse the document because of a missing class (we are not importing all jars needed by Tika), Tika throws a Throwable which is not catch.

This commit removes support for Visio and POTM office files.

The good news is that it does not kill the node anymore and allows to extract the text which is in the Office document even if we have a Visio content (which is not extracted anymore).

Note that for this one as we did not apply yet #22963 it hides the fact that we removed the potm sample file from the tika big ZIP file.

### CODE REVIEW

**Comment by dadoonet** [comment]
as #22963 has been merged, I pushed new changes which makes more obvious that we are removing support for `potm` files.

@jasontedor It's ready for review.

@clintongormley I'd like to push it as well in 5.3 and 5.2 branches as it's a bug fix. Do you agree?

**Comment by jasontedor** [comment]
Can you please rebase this as currently there are conflicts with the target branch?

I'm fine with thing going into 5.3, I'm not fine with this going into 5.2.

**Comment by dadoonet** [comment]
> Can you please rebase this as currently there are conflicts with the target branch?

Can you refresh your browser? I don't see the conflict on my side.

**Comment by jasontedor** [comment]
> Can you refresh your browser? I don't see the conflict on my side.

It's not a browser refresh issue.

```
12:54:55 [jason:~/src/elastic/elasticsearch-5.x] 5.x+ ± git fetch origin 5.x
From github.com:elastic/elasticsearch
 * branch                  5.x        -> FETCH_HEAD
12:55:01 [jason:~/src/elastic/elasticsearch-5.x] 5.x+ ± git fetch origin pull/23214/head:pr/23214
remote: Counting objects: 72, done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 72 (delta 12), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (72/72), done.
From github.com:elastic/elasticsearch
 * [new ref]               refs/pull/23214/head -> pr/23214
12:55:27 [jason:~/src/elastic/elasticsearch-5.x] 5.x+ ± git checkout pr/23214
Switched to branch 'pr/23214'
12:55:34 [jason:~/src/elastic/elasticsearch-5.x] pr/23214+ ± git rebase 5.x
First, rewinding head to replay your work on top of it...
Applying: Remove support for Visio and potm files
Applying: Remove support for Visio and potm files
Using index info to reconstruct a base tree...
A	plugins/mapper-attachments/src/test/resources/org/elasticsearch/index/mapper/attachment/test/tika-files.zip
Falling back to patching base and 3-way merge...
CONFLICT (modify/delete): plugins/mapper-attachments/src/test/resources/org/elasticsearch/index/mapper/attachment/test/tika-files.zip deleted in HEAD and modified in Remove support for Visio and potm files. Version Remove support for Visio and potm files of plugins/mapper-attachments/src/test/resources/org/elasticsearch/index/mapper/attachment/test/tika-files.zip left in tree.
error: Failed to merge in the changes.
Patch failed at 0002 Remove support for Visio and potm files
The copy of the patch that failed is found in: /Users/jason/src/elastic/elasticsearch/.git/worktrees/elasticsearch-5.x/rebase-apply/patch

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".

12:55:39 [jason:~/src/elastic/elasticsearch-5.x] 954f7c2add(+0/-0)+ REBASING 128 ± git status
rebase in progress; onto 5ac2f9f311
You are currently rebasing branch 'pr/23214' on '5ac2f9f311'.
  (fix conflicts and then run "git rebase --continue")
  (use "git rebase --skip" to skip this patch)
  (use "git rebase --abort" to check out the original branch)

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	modified:   plugins/mapper-attachments/build.gradle
	modified:   plugins/mapper-attachments/src/main/java/org/elasticsearch/mapper/attachments/TikaImpl.java
	modified:   plugins/mapper-attachments/src/test/java/org/elasticsearch/mapper/attachments/VariousDocTests.java
	new file:   plugins/mapper-attachments/src/test/resources/org/elasticsearch/index/mapper/attachment/test/sample-files/issue-22077.doc
	new file:   plugins/mapper-attachments/src/test/resources/org/elasticsearch/index/mapper/attachment/test/sample-files/issue-22077.docx
	new file:   plugins/mapper-attachments/src/test/resources/org/elasticsearch/index/mapper/attachment/test/sample-files/issue-22077.vsdx

Unmerged paths:
  (use "git reset HEAD <file>..." to unstage)
  (use "git add/rm <file>..." as appropriate to mark resolution)

	deleted by us:   plugins/mapper-attachments/src/test/resources/org/elasticsearch/index/mapper/attachment/test/tika-files.zip

12:55:43 [jason:~/src/elastic/elasticsearch-5.x] 954f7c2add(+0/-0)+ REBASING ± 
```

**Comment by dadoonet** [comment]
Hmmm. Why do you rebase instead of merging?

I understand why rebase is failing on the second commit but it should not be an issue because of the next commits.

**Comment by jasontedor** [comment]
> Hmmm. Why do you rebase instead of merging?

Because that's what you're going to go when you merge the commit it, and that's why GitHub is already showing you the conflict.

**Comment by jasontedor** [comment]
> I understand why rebase is failing on the second commit but it should not be an issue because of the next commits.

Also, that's not how rebasing works. Rebasing replays every commit and halts on conflict.

**Comment by dadoonet** [comment]
img_0182

But GitHub does not show a conflict. But ok I'll look at it tomorrow

**Comment by dadoonet** [comment]
Note that I merged 5.x in my branch with the 3rd commit.

**Comment by jasontedor** [comment]
It does when I look:

screen shot 2017-02-16 at 1 47 02 pm

And anyway, I showed from the command line where the conflict is. :smile:

**Comment by dadoonet** [comment]
I understand why you see this conflict and I don't. You defined rebase and merge as the default way to merge. I didn't.

So if you don't rebase there is no conflict.

**Review by jasontedor — APPROVED** [review]
LGTM. Please squash when merging.

**Comment by dadoonet** [comment]
Thanks @jasontedor. I rebased and merged.

**Comment by dadoonet** [comment]
As discussed with @clintongormley, this has been also pushed to 5.2 branch.

Related commits:

* 76a977a: Remove support for Visio and potm files (ingest-attachment)
* 07a9f29: Remove support for Visio and potm files (mapper-attachments)
* 3fda86a: Replace tika-files.zip by a tika-files dir (ingest-attachment tests)
* 0561d1b: Replace tika-files.zip by a tika-files dir (mapper-attachments tests)

**Comment by dumakant** [comment]
I am using Elasticsearch 5.1.2 and facing the same error 

java.lang.NoClassDefFoundError: com/graphbuilder/curve/Point.
Can your fixes be backported to 5.1.2 as well. Also our instances are in production, how can we consume the fixes?

**Comment by dadoonet** [comment]
@dumakant No it won't be backported.

You need to upgrade to 5.2.2 which is pretty much straightforward [with a rolling upgrade](https://www.elastic.co/guide/en/elasticsearch/reference/current/rolling-upgrades.html) (even easier if you are using elastic cloud).

**Comment by RkirkCBD** [comment]
I'm running 5.30 and I am receiving this error as a fatal error.  Is the fix in the 5.3 release?

[2017-04-22T10:54:58,532][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [es-node-docserver] fatal error in thread [elasticsearch[es-node-docserver][bulk][T#9]], exiting
java.lang.NoClassDefFoundError: com/graphbuilder/curve/Point

**Comment by dadoonet** [comment]
OMG! I did not push that fix in 5.3 branch apparently. So it's fixed in 5.2, 5.4 but not 5.3...

**Comment by dadoonet** [comment]
@RkirkCBD could you open a new issue and I'll push later today the fix in 5.3 which will go hopefully in 5.3.2?

Thanks a lot for reporting !

**Comment by RkirkCBD** [comment]
See 24273.  Thanks, when should 5.3.2 be released.  Is it possible to downgrade my cluster to 5.2.2?

**Comment by dadoonet** [comment]
AFAIK soonish. No you can't downgrade.

**Comment by dadoonet** [comment]
For the record, I pushed the missing commit in 5.3 as well: dc4888e21c06eeccc2e6a27de4c6c82bd6a73958

Apparently I pushed only one of the 2 commits from this PR in the 5.3 branch... :(

**Pull request merged**
