### PR TITLE
Channel buffer support for different page sizes

### PR DESCRIPTION
**Pull request by Tim-Brooks**
Currently the `InboundChannelBuffer` only supports page sizes that are a
power of two. This restriction does not make sense for some situations.
TLS network packet sizes tend to be an awkward size for the byte array
to be a power of two. This commit removes the code that depends on it
being a power of two.

### CODE REVIEW

**Comment by s1monw** [comment]
hmm I wonder what @jpountz thinks here. The code looks fine but I wonder if the power of two limitation is a good thing? It seems like we still use a power of two at this point? The reason why I think it's useful is that power of two pages might be better when it gets to recycling, allocating and reduction of fragmentation?

**Comment by tbrooks8** [comment]
Context for this change: #39972.

**Comment by tbrooks8** [comment]
I want to address this a little more:

> The reason why I think it's useful is that power of two pages might be better when it gets to recycling, allocating and reduction of fragmentation?

In the `PageCacheRecycler` we allocate 16KB byte arrays individually. As far as I can tell, the primary advantage of allocating power of two is improved performance for random access (bitwise operations opposed to `div` and `rem`). Perhaps there is some underlying memory layout advantage? Since we are allocating many individual arrays, we are rely on the JDK for what happens there.

I am not proposing switching the default page cache from 16KB. Our `BigByteArray` will still use the power of two versions. I am only suggesting that we support a non-power of two version for TLS network operations (which use 16709 bytes - our options are non-power of two, or hugely space inefficient 32KB). We will have a dedicated allocator for network level stuff (which is fine as this as transport-nio has memory flexibility as it does not have Netty's pooling).

If there is some memory layout advantage, we can stop allocating individual arrays, allocate a single large array (hypothetically 16MB), and have pages reference 16709 byte regions in that (in TLS case, plaintext will still use power of two 16KB).

It is not a major issue to lose random access performance because there is not much random access for network operations (occasionally figuring out where to slice, etc). 

The motivation for this all and high-level design is in #39972. Where @jpountz is requested as a reviewer for feedback. This PR was just introducing the work for the channel buffer to be ready to support pages of non power of two sizes.

**Comment by tbrooks8** [comment]
Closing. I do not think this work will be necessary.

**Pull request closed without merging**
