### PR TITLE
`type` and `id` are lost upon serialization of `Translog.Delete`.

### PR DESCRIPTION
**Pull request by jpountz**
This was introduced in #24460: the constructor of `Translog.Delete` that takes
a `StreamInput` does not set the type and id. To make it a bit more robust, I
made fields final so that forgetting to set them would make the compiler
complain.

Tagging as a `non-issue` since the bug is not released.

### CODE REVIEW

**Comment by jpountz** [comment]
@elasticmachine please test it

**Review by s1monw — APPROVED** [review]
LGTM

**Comment by jpountz** [comment]
@elasticmachine please test it

**Comment by jpountz** [comment]
@elasticmachine please test it

**Pull request merged**
