### PR TITLE
Use RestStatus.isSuccessful to deduplicate status code checks

### PR DESCRIPTION
**Pull request by nicktindall**
In #113913 I added `RestStatus.isSuccessful` to deduplicate some status code checks. I noticed this logic was duplicated in lots of other places.

https://github.com/elastic/elasticsearch/blob/40bddafd92ea3ed1d3e28e694883b11dfd6516ad/server/src/main/java/org/elasticsearch/rest/RestStatus.java#L575-L585

This PR just uses the utility method instead.

(also open to suggestions on implementation of `isSuccessful`, could also change it to `status / 100 == 2`?)

### CODE REVIEW

**Review by idegtiarenko — APPROVED** [review]

**Review by DaveCTurner — APPROVED** [review]
LGTM but it seems like we could deduplicate this further by adding a `org.elasticsearch.xpack.inference.external.http.HttpResult#isSuccessfulResponse` to operate directly on a `HttpResult`, and maybe also a static `org.elasticsearch.xpack.inference.external.http.HttpUtils#isSuccessfulHttpResponse` to operate directly on a `HttpResponse`.

**Review by DaveCTurner — APPROVED** [review]
LGTM still

**Comment by nicktindall** [comment]
> LGTM but it seems like we could deduplicate this further by adding a `org.elasticsearch.xpack.inference.external.http.HttpResult#isSuccessfulResponse` to operate directly on a `HttpResult`, and maybe also a static `org.elasticsearch.xpack.inference.external.http.HttpUtils#isSuccessfulHttpResponse` to operate directly on a `HttpResponse`.

I don't think the static method is that useful, those calls that pass a `HttpResponse` are actually for two different types of `HttpResponse` in two different packages.

**Review by ywangd — APPROVED** [review]
LGTM

**Pull request merged**
