### PR TITLE
Deprecate fallback to java on PATH

### PR DESCRIPTION
**Pull request by rjernst**
Finding java on the path is sometimes confusing for users and
unexpected, as well as leading to a different java being used than a
user expects.  This commit adds warning messages when starting
elasticsearch (or any tools like the plugin cli) and using java found
on the PATH instead of via JAVA_HOME.

### CODE REVIEW

**Review by alpar-t — APPROVED** [review]
LGTM

**Comment by rjernst** [comment]
@elasticmachine run elasticsearch-ci/default-distro

**Comment by rjernst** [comment]
@elasticmachine run elasticsearch-ci/packaging

**Comment by rjernst** [comment]
@elasticmachine run elasticsearch-ci/packaging

**Comment by Grinnz** [comment]
Is there any explanation or documentation as to why this was deprecated? On RHEL6 the RPM does not appear to set JAVA_HOME, so the fallback seems to be the only way it works out of the box; and I don't see any documentation other than a very brief mention in https://www.elastic.co/guide/en/elasticsearch/reference/current/rpm.html that mentions this needs to be set. I'd also add that using the java from the path is exactly what I would expect, this is why alternatives exists.

**Comment by Grinnz** [comment]
Additionally, setting JAVA_HOME in /etc/sysconfig/elasticsearch did not remove the deprecation warning.

**Comment by jasontedor** [comment]
> On RHEL6 the RPM does not appear to set JAVA_HOME, so the fallback seems to be the only way it works out of the box; and I don't see any documentation other than a very brief mention in https://www.elastic.co/guide/en/elasticsearch/reference/current/rpm.html that mentions this needs to be set.

We bundle a preferred JDK with the RPM now, and that is what is used by default if JAVA_HOME is not set. We can’t set JAVA_HOME to that bundled JDK, because it would override users that have a preference to use a Java that they specify from JAVA_HOME.

> Additionally, setting JAVA_HOME in /etc/sysconfig/elasticsearch did not remove the deprecation warning.

*That* sounds like a bug, can you open a new issue and share a reproduction?

**Comment by Grinnz** [comment]
Thank you, I have opened https://github.com/elastic/elasticsearch/issues/43380.

**Pull request merged**
