### PR TITLE
Encapsulate request, auth, and action name

### PR DESCRIPTION
**Pull request by jaymode**
This change introduces a new class called RequestInfo that encapsulates
the common objects that are passed to the authorization engine methods.
By doing so, we give ourselves a way of adding additional data without
breaking the interface. Additionally, this also reduces the need to
ensure we pass these three parameters in the same order everywhere for
consistency.

### CODE REVIEW

**Review by tvernum — APPROVED** [review]
:+1:

**Comment by jaymode** [comment]
@elasticmachine run gradle build tests 1; run gradle build tests 2; run sample packaging tests

**Comment by jaymode** [comment]
@elasticmachine run gradle build tests 1

```
  MovAvgIT (suite) <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: failure in bulk execution:
   > [2]: index [idx], type [type], id [ox1tXGgB7qPAYICEXfQU], message [ProcessClusterEventTimeoutException[failed to process cluster event (put-mapping) within 11s]]
   > [35]: index [neg_idx], type [type], id [bogus_doc_𝌽𝌫𝌕𝌂aa98], message [ProcessClusterEventTimeoutException[failed to process cluster event (put-mapping) within 11s]]
   > Expected: <false>
   >      but: was <true>
```

**Comment by jaymode** [comment]
@elasticmachine run gradle build tests 1

**Comment by jaymode** [comment]
@elasticmachine run gradle build tests 1

**Pull request merged**
