### PR TITLE
Calculate artifact checksums in maven

### PR DESCRIPTION
**Pull request by s1monw**
Today we calculate the checksums in a python scritp to do the release.
We can also do this way simpler in maven using an ant task.

### CODE REVIEW

**Comment by spinscale** [comment]
should we stick with ant here or check if there is a mvn plugin that takes care of all artifacts and checksums those (which should include the rpm at some point).. I know there is a maven checksums plugin, but dont have personal experience with it TBH. Feels like we are sneaking ant in here and then have two things to maintain.

**Comment by dadoonet** [comment]
Well:

https://maven.apache.org/plugins/maven-install-plugin/examples/installing-checksums.html

```
mvn install -DcreateChecksum=true
```

Do we need a plugin?

**Comment by dadoonet** [comment]
If we change in `/pom.xml`:

```xml
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-install-plugin</artifactId>
                    <version>2.5.2</version>
                    <configuration>
                        <createChecksum>true</createChecksum>
                    </configuration>
                </plugin>
```

I think we are done.

If you do it and then run `mvn install`, your `.m2` dir will have:

```
-rw-r--r--  1 dpilato  staff     57019  7 jul 16:55 elasticsearch-2.0.0-SNAPSHOT.pom
-rw-r--r--  1 dpilato  staff    615374  7 jul 18:19 elasticsearch-2.0.0-SNAPSHOT-tests.jar
-rw-r--r--  1 dpilato  staff   9009779  7 jul 18:19 elasticsearch-2.0.0-SNAPSHOT.jar
-rw-r--r--  1 dpilato  staff   5164015  7 jul 18:19 elasticsearch-2.0.0-SNAPSHOT-sources.jar
-rw-r--r--  1 dpilato  staff   9118928  7 jul 18:19 elasticsearch-2.0.0-SNAPSHOT-test-sources.jar
-rw-r--r--  1 dpilato  staff  13247908  7 jul 18:20 elasticsearch-2.0.0-SNAPSHOT-shaded.jar
-rw-r--r--  1 dpilato  staff  28638178  7 jul 18:20 elasticsearch-2.0.0-SNAPSHOT.tar.gz
-rw-r--r--  1 dpilato  staff  28643294  7 jul 18:20 elasticsearch-2.0.0-SNAPSHOT.zip
-rw-r--r--  1 dpilato  staff  28522768  7 jul 18:20 elasticsearch-2.0.0-SNAPSHOT.deb
-rw-r--r--  1 dpilato  staff        40  7 jul 18:20 elasticsearch-2.0.0-SNAPSHOT.jar.sha1
-rw-r--r--  1 dpilato  staff        32  7 jul 18:20 elasticsearch-2.0.0-SNAPSHOT.jar.md5
-rw-r--r--  1 dpilato  staff        40  7 jul 18:20 elasticsearch-2.0.0-SNAPSHOT-tests.jar.sha1
-rw-r--r--  1 dpilato  staff        32  7 jul 18:20 elasticsearch-2.0.0-SNAPSHOT-tests.jar.md5
-rw-r--r--  1 dpilato  staff        40  7 jul 18:20 elasticsearch-2.0.0-SNAPSHOT-test-sources.jar.sha1
-rw-r--r--  1 dpilato  staff        32  7 jul 18:20 elasticsearch-2.0.0-SNAPSHOT-test-sources.jar.md5
-rw-r--r--  1 dpilato  staff        40  7 jul 18:20 elasticsearch-2.0.0-SNAPSHOT-sources.jar.sha1
-rw-r--r--  1 dpilato  staff        32  7 jul 18:20 elasticsearch-2.0.0-SNAPSHOT-sources.jar.md5
-rw-r--r--  1 dpilato  staff        40  7 jul 18:20 elasticsearch-2.0.0-SNAPSHOT-shaded.jar.sha1
-rw-r--r--  1 dpilato  staff        32  7 jul 18:20 elasticsearch-2.0.0-SNAPSHOT-shaded.jar.md5
-rw-r--r--  1 dpilato  staff        40  7 jul 18:20 maven-metadata-local.xml.sha1
-rw-r--r--  1 dpilato  staff        32  7 jul 18:20 maven-metadata-local.xml.md5
-rw-r--r--  1 dpilato  staff      2033  7 jul 18:20 maven-metadata-local.xml
-rw-r--r--  1 dpilato  staff        40  7 jul 18:20 elasticsearch-2.0.0-SNAPSHOT.zip.sha1
-rw-r--r--  1 dpilato  staff        32  7 jul 18:20 elasticsearch-2.0.0-SNAPSHOT.zip.md5
-rw-r--r--  1 dpilato  staff        40  7 jul 18:20 elasticsearch-2.0.0-SNAPSHOT.tar.gz.sha1
-rw-r--r--  1 dpilato  staff        32  7 jul 18:20 elasticsearch-2.0.0-SNAPSHOT.tar.gz.md5
-rw-r--r--  1 dpilato  staff        40  7 jul 18:20 elasticsearch-2.0.0-SNAPSHOT.pom.sha1
-rw-r--r--  1 dpilato  staff        32  7 jul 18:20 elasticsearch-2.0.0-SNAPSHOT.pom.md5
-rw-r--r--  1 dpilato  staff        40  7 jul 18:20 elasticsearch-2.0.0-SNAPSHOT.deb.sha1
-rw-r--r--  1 dpilato  staff        32  7 jul 18:20 elasticsearch-2.0.0-SNAPSHOT.deb.md5
```

Is it what we we are looking for?

**Comment by dadoonet** [comment]
And same for all plugins:

```
ll ~/.m2/repository/org/elasticsearch/plugin/elasticsearch-analysis-kuromoji/2.0.0-SNAPSHOT/
total 9168
-rw-r--r--  1 dpilato  staff     1373  7 jul 16:55 elasticsearch-analysis-kuromoji-2.0.0-SNAPSHOT.pom
-rw-r--r--  1 dpilato  staff    20877  7 jul 18:20 elasticsearch-analysis-kuromoji-2.0.0-SNAPSHOT.jar
-rw-r--r--  1 dpilato  staff    14128  7 jul 18:20 elasticsearch-analysis-kuromoji-2.0.0-SNAPSHOT-sources.jar
-rw-r--r--  1 dpilato  staff       40  7 jul 18:20 maven-metadata-local.xml.sha1
-rw-r--r--  1 dpilato  staff       32  7 jul 18:20 maven-metadata-local.xml.md5
-rw-r--r--  1 dpilato  staff     1110  7 jul 18:20 maven-metadata-local.xml
-rw-r--r--  1 dpilato  staff       40  7 jul 18:20 elasticsearch-analysis-kuromoji-2.0.0-SNAPSHOT.zip.sha1
-rw-r--r--  1 dpilato  staff       32  7 jul 18:20 elasticsearch-analysis-kuromoji-2.0.0-SNAPSHOT.zip.md5
-rw-r--r--  1 dpilato  staff  4596459  7 jul 18:20 elasticsearch-analysis-kuromoji-2.0.0-SNAPSHOT.zip
-rw-r--r--  1 dpilato  staff       40  7 jul 18:20 elasticsearch-analysis-kuromoji-2.0.0-SNAPSHOT.pom.sha1
-rw-r--r--  1 dpilato  staff       32  7 jul 18:20 elasticsearch-analysis-kuromoji-2.0.0-SNAPSHOT.pom.md5
-rw-r--r--  1 dpilato  staff       40  7 jul 18:20 elasticsearch-analysis-kuromoji-2.0.0-SNAPSHOT.jar.sha1
-rw-r--r--  1 dpilato  staff       32  7 jul 18:20 elasticsearch-analysis-kuromoji-2.0.0-SNAPSHOT.jar.md5
-rw-r--r--  1 dpilato  staff       40  7 jul 18:20 elasticsearch-analysis-kuromoji-2.0.0-SNAPSHOT-sources.jar.sha1
-rw-r--r--  1 dpilato  staff       32  7 jul 18:20 elasticsearch-analysis-kuromoji-2.0.0-SNAPSHOT-sources.jar.md5
```

**Comment by s1monw** [comment]
@dadoonet I mean that solves the problem, I guess we just need to adopt the release script to upload those checksums instead then?

**Comment by dadoonet** [comment]
@s1monw I think so.

**Comment by s1monw** [comment]
@dadoonet I updated the PR

**Comment by dadoonet** [comment]
LGTM. Will you update the release script in another PR?

**Pull request merged**
