### PR TITLE
Remove docIdsToLoad method from SearchContext

### PR DESCRIPTION
**Pull request by romseygeek**
We currently set docIdsToLoad on SearchContext, and then pass the context to
FetchPhase.execute() which reads the docIdsToLoad back out again.  This would
be considerably simpler if it was just a parameter on `execute()`.

### CODE REVIEW

**Comment by javanna** [comment]
@jdconrad could you have a look please?

**Review by jdconrad — APPROVED** [review]
LGTM!

**Comment by jdconrad** [comment]
@javanna This is a good change. Would you like me to get it up-to-date with main and merge it?

**Comment by jdconrad** [comment]
@elasticmachine test this please

**Comment by jdconrad** [comment]
@elasticmachine ok to test

**Comment by jdconrad** [comment]
buildkite test this

**Pull request merged**
