### PR TITLE
[DOCS] Note index rollover is not automatically monitored

### LINKED ISSUE #35624: Docs improvement for Rollover index API
The current [Rollover index API](https://www.elastic.co/guide/en/elasticsearch/reference/6.5/indices-rollover-index.html) description creates confusion.
It leads to think that you can call the API, and Elasticsearch sits there waiting for any of the conditions to be met. Later on, when any of the conditions is met, the rollover automatically acts and creates new indices and changes the alias.
That assumption is of course wrong. What it does instead, is that it acts **only** at the moment you call the API. At that moment it checks the conditions and if any of them is met, it acts. But **only** at particular that moment when the API is called.

I´m not saying this behaviour should be changed, but this should be made more clear in the docs. There are several users getting confused by this.

### PR DESCRIPTION
**Pull request by jrodewig**
This PR specifies that the rollover index API only checks for met conditions **at the time of the API call only**.

Previously, users might assume Elasticsearch would continue monitoring for met conditions after the call.

Resolves #35624.

### CODE REVIEW

**Comment by jrodewig** [comment]
retest this please

**Comment by jrodewig** [comment]
retest this please

**Comment by gwbrown** [comment]
If users are looking for a way to automatically roll over when these conditions are met, we do provide that in Basic+ license levels via [ILM](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-lifecycle-management.html), so we might want to point users that way.

**Comment by jrodewig** [comment]
Great point @gwbrown. Pushed a new commit to direct users to the ILM for automatic rollovers.

**Comment by jrodewig** [comment]
Chatted with @Erni who gave a 👍. Will merge now.

**Pull request merged**
