### PR TITLE
Add missing export for o.e.plugins.scanners

### PR DESCRIPTION
**Pull request by DaveCTurner**
Fixes up an IDE error

### CODE REVIEW

**Comment by pgomulka** [comment]
I would have hoped that those classes are not used outside of server module. They are only used for loading a plugin in server.
Can you share what error in IDE do you get?

**Comment by DaveCTurner** [comment]
My IDE complains about the usage of `StablePluginsRegistry` in tests here:

https://github.com/elastic/elasticsearch/blob/978a5469ceff1f35e3eecdfd240b214d376adc1d/test/framework/src/main/java/org/elasticsearch/test/ESTestCase.java#L1780

**Comment by pgomulka** [comment]
we are not using java modules with testing, but test framework on its own is a 'production code'
it seems that elasticsearch.java is also applied when building it (or importing in IDE?)
here we add the flags to force java modules during compiliation https://github.com/elastic/elasticsearch/pull/81066/files#diff-28123ebb807261889d7b1f9fd2bbe0a059b9d9536b48b826d6bba373aafabaa1R162

was there anything in the logs when IDE failed? I was hoping we could see the jvm args.

I think a temporary fix would be to add --add-exports in the test framework's java compiler task. But I still think this is a bug that test framework is build with modules? 

@ChrisHegarty wdyt?

**Comment by pgomulka** [comment]
@DaveCTurner can you try adding this 
```
tasks.named("compileJava").configure {
  //TODO fix this
  options.compilerArgs.addAll(["--add-exports", "org.elasticsearch.server/org.elasticsearch.plugins.scanners=ALL-UNNAMED"])
}
```
to `test/framework/build.gradle` ?

**Comment by DaveCTurner** [comment]
Like in 4a496d8f0303383b47ecc357c0c2fbfe607b33a3? If so, that doesn't seem to help.

**Comment by rjernst** [comment]
> Fixes up an IDE error

What was the IDE error? Does it occur while running tests (via gradle runner or junit?), or importing the project, or building, or something else?

**Comment by DaveCTurner** [comment]
image

Tests still run and so on, it's just a pain that these things are highlighted similarly to actual errors.

**Comment by rjernst** [comment]
That warning is in ESTestCase, which is part of the test-framework. As Przemek mentioned, we do not run tests modular, so this "error" is not real.

As far as why we see it in IntelliJ or how to quiet it, perhaps @mark-vieira has thoughts on why IntelliJ is thinking the test-framework is modular? It doesn't have a module-info.java that I can see.

**Comment by mark-vieira** [comment]
> As far as why we see it in IntelliJ or how to quiet it, perhaps @mark-vieira has thoughts on why IntelliJ is thinking the test-framework is modular? It doesn't have a module-info.java that I can see.

It is at compile time, just not at runtime. So we still enforce compile time modularity for tests to better emulate how visibility will behave at runtime, but when we execute the tests we just use the classpath.

**Comment by rjernst** [comment]
> we still enforce compile time modularity

The test framework doesn't have a module-info.java, right? If so, where is it getting its "modularity"?

I don't think we should change module exports for production to accommodate tests that don't ever run modular.

**Comment by mark-vieira** [comment]
> The test framework doesn't have a module-info.java, right? If so, where is it getting its "modularity"?

It'll be treated as an automatic module.

**Comment by rjernst** [comment]
Can we avoid compiling test code as automatic modules?

> we still enforce compile time modularity for tests to better emulate how visibility will behave at runtime

While I understand the sentiment, I don't think it actually emulates reality. We don't run tests as modular, so forcing them to compile as modular creates the need to export more things from production code, which shouldn't be necessary.

**Comment by mark-vieira** [comment]
Looks like we already have a list of project we exclude from the module path and place on the classpath instead, the test framework being one of them. We could expand this list, or just ignore all this stuff when compiling any source set other than main.

https://github.com/elastic/elasticsearch/blob/b23e000c30b9f87373837182156a8fad8392346b/build-tools-internal/src/main/java/org/elasticsearch/gradle/internal/ElasticsearchJavaModulePathPlugin.java#L55

**Comment by rjernst** [comment]
Are you sure those excludes are being applied to intellij configuration? The [error](https://github.com/elastic/elasticsearch/pull/101814#issuecomment-1794380454) David noted is in the test framework, which is in the exclude list you referenced.

**Comment by mark-vieira** [comment]
I see now. The "error" in David's screenshot is actually an IntelliJ inspection and our plugin only affects the CLI build. They _mostly_ align but obviously the IDE knows nothing about these excludes. We only apply this inspection to "production" code but that just means code in the `main` sourceset, which is what `:test:framwork` is.

I've opened https://github.com/elastic/elasticsearch/pull/101977 to address this by excluding all projects under `:test` from this inspection. Closing this in favor of that one.

**Pull request closed without merging**
