### PR TITLE
[Transform] Ignore "index not found" error when `delete_dest_index` flag is set but the dest index doesn't exist

### PR DESCRIPTION
**Pull request by przemekwitek**
This PR makes the "index not found" error ignored when `delete_dest_index` flag is set on the transform deletion request and the destination index does not exist.

### CODE REVIEW

**Review by droberts195 — APPROVED** [review]
LGTM

**Comment by przemekwitek** [comment]
run elasticsearch-ci/bwc

**Comment by przemekwitek** [comment]
run elasticsearch-ci/part-1

**Comment by przemekwitek** [comment]
run elasticsearch-ci/bwc

**Pull request merged**
