### PR TITLE
Add chunking settings configuration to CohereService, AmazonBedrockService, and AzureOpenAiService

### PR DESCRIPTION
**Pull request by dan-rubinstein**
## Description
This change introduces:
- Chunking settings as a new setting to provide when creating embedding inference endpoints in CohereService, AmazonBedrockService, and AzureOpenAIService.

These features are currently hidden behind a feature flag for 8.16. 

Note: Chunking currently only runs when large documents are ingested to an index with an inference field.

## Testing
- Ran unit tests and ensured that all succeed
- Tested the following cases with each service with the feature flag enabled:
  - Creating an embedding endpoint with no `chunking_settings` provided generates a model with default chunking settings (keeps existing word based chunking strategy with default configurations).
  - Creating an embedding endpoint with `chunking_settings` for a word based chunking strategy provided generates a model that uses the word based chunking strategy.
  - Creating an embedding endpoint with `chunking_settings` for a sentence based chunking strategy provided generates a model that uses the sentence based chunking strategy.
  - Creating a non-embedding endpoint (when applicable) works.
- Tested the following cases with the feature flag disabled:
  - Creating an embedding endpoint with no `chunking_settings` provided generates a model with null chunking settings and chunking still runs successfully with the previously default word based chunking strategy.
  - Attempting to create an embedding endpoint with `chunking_settings` provided throws an exception.
  - Attempting to create a non-embedding endpoint works.

### CODE REVIEW

**Review by davidkyle — APPROVED** [review]
LGTM

**Comment by dan-rubinstein** [comment]
@elasticmachine merge upstream

**Review by davidkyle — APPROVED** [review]
LGTM

**Comment by dan-rubinstein** [comment]
@elasticmachine merge upstream

**Pull request merged**
