### PR TITLE
Use project dependency instead of substitutions for distributions

### PR DESCRIPTION
**Pull request by rjernst**
Currently integration tests which use either bwc snapshot versions or
the current version of elasticsearch depend on project substitutions to
link to the build of those artifacts. Likewise, vagrant tests use
dependency substitutions to get to bwc snapshots of rpm and debs.
This commit changes those to depend on the relevant project/configuration
and removes the dependency substitutions for distributions we do not
publish.

### CODE REVIEW

**Review by alpar-t — COMMENTED** [review]
This looks good to me, the only think I don't like about it is that we don't have a test to assure us we don't break it again for external plugin authors. 

I'm wondering if given the complexity it adds is it worth downloading trough the download service, or would it be better to continue using our own maven repos.
If my understanding is correct that would not defeat your goals with this set of PRs.

This would help us keep the simplifying assumption that  anything meant for external consumption is published as a maven artifact. That would mean we can fully utilize the simulated local repo in our tests to check that we correctly expose all artifacts meant for consumption and would allow us to avoid duplicating the logic to re-map the distributions to what was built locally - we could continue to use the  substitutions as before. 
Granted, tests would not download dependencies in the same way as  users would, but we can cover that part as a check in the release process or a release test if we must that would only check that  the artifacts are there in the download service and they match the ones in the maven repo.

**Comment by rjernst** [comment]
> would it be better to continue using our own maven repos

I don't like this because it means adding artifacts back to maven which don't really belong in maven. That is about jars, but these are our distributions.

**Comment by rjernst** [comment]
> we could continue to use the substitutions as before.

This won't work when we add classifiers. I found those simply do not work with project substitutions.

**Comment by rjernst** [comment]
> we don't have a test to assure us we don't break it again for external plugin authors

We do have a test, it is the example plugins tests you added! Those failing is what made me realize it was broken for plugin authors.

**Review by alpar-t — APPROVED** [review]
We had a discussion about the change and direction and I'm fine to merge this as is

**Comment by rjernst** [comment]
@elasticmachine run gradle build tests 2

**Comment by rjernst** [comment]
@elasticmachine run elasticsearch-ci/2

**Pull request merged**
