### PR TITLE
Add config namespace in get policy api response

### PR DESCRIPTION
**Pull request by martijnvg**
Currently the policy config is placed directly in the json object
of the toplevel `policies` array field. For example:

```
{
    "policies": [
        {
            "match": {
                "name" : "my-policy",
                "indices" : ["users"],
                "match_field" : "email",
                "enrich_fields" : [
                    "first_name",
                    "last_name",
                    "city",
                    "zip",
                    "state"
                ]
            }
        }
    ]
}
```

This change adds a `config` field in each policy json object:

```
{
    "policies": [
        {
            "config": {
                "match": {
                    "name" : "my-policy",
                    "indices" : ["users"],
                    "match_field" : "email",
                    "enrich_fields" : [
                        "first_name",
                        "last_name",
                        "city",
                        "zip",
                        "state"
                    ]
                }
            }
        }
    ]
}
```

This allows us in the future to add other information about policies
in the get policy api response.

The UI will consume this API to build an overview of all policies.
The UI may in the future include additional information about a policy
and the plan is to include that in the get policy api, so that this
information can be gathered in a single api call.

An example of the information that is likely to be added is:
* Last policy execution time
* The status of a policy (executing, executed, unexecuted)
* Information about the last failure if exists

### CODE REVIEW

**Comment by jbaiera** [comment]
Does it make sense to lift the elasticsearch version field out of config once this is in?

**Comment by martijnvg** [comment]
> Does it make sense to lift the elasticsearch version field out of config once this is in?

Good point. Yes, I think it does. What should be the name of the namespace we put it under? `_meta`?

**Comment by martijnvg** [comment]
@jbaiera I've been thinking about pulling version out of the config and it isn't straightforward because it is part of the `EnrichPolicy` class and we then return it here as different things, one being config and one being something internal. I think this result increased complexity in the code.

I'm not sure what would be best here. I think we can:
* Move the version out of the policy class and store it elsewhere and since policies are going to be stored in an index, it could be stored as a different document in that index.
* We decide to see the version field as something that is part of the config. It is not something that the user configures, but that is something that is implicitly set when creating a policy. We should then always include the version in the get policy api response. 

I'm leaning towards the latter, since the former adds complexity elsewhere. wdyt?

**Comment by jbaiera** [comment]
Hmm, the storage of the policy in an index definitely complicates things. The thing about the version field is that it's not entirely a configuration, because a user cannot change the value of it outside of creating a policy on a specific version of Elasticsearch, so it's always felt a little out of place in the config to me. I think the thing I saw that inspired that feeling is how SLM manages the boundary of its policies and metadata in `SnapshotLifecyclePolicyMetadata`. That said, Enrich policies are not mutable, and I'm not overly keen on making big changes to support pulling the version out of there that would increase the complexity of managing this too much.

**Review by jbaiera — APPROVED** [review]
LGTM

**Comment by martijnvg** [comment]
@elasticmachine upgrade branch

**Comment by martijnvg** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Pull request merged**
