### PR TITLE
resolveHasher defaults to NOOP

### LINKED ISSUE #31697: FileRealmTests#testAuthenticateCaching fails with an assertion error.
The failure reliably reproduces for me locally, and may be related to the recent change to password hashing: https://github.com/elastic/elasticsearch/pull/31234.

---

Link to the build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+g1gc/6006/console

Command to reproduce: 
```
./gradlew :x-pack:plugin:security:test \
  -Dtests.seed=B944BC5A5B893131 \
  -Dtests.class=org.elasticsearch.xpack.security.authc.file.FileRealmTests \
  -Dtests.method="testAuthenticateCaching" \
  -Dtests.security.manager=true \
  -Dtests.jvm.argline="-XX:-UseConcMarkSweepGC -XX:+UseG1GC" \
  -Dtests.locale=fr-BE \
  -Dtests.timezone=Antarctica/Troll
```

Relevant excerpt from the logs:
```
FAILURE 3.40s | FileRealmTests.testAuthenticateCaching <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: sameInstance(<User[username=user1,roles=[role1,role2],fullName=null,email=null,metadata={}]>)
   >      but: was <User[username=user1,roles=[role1,role2],fullName=null,email=null,metadata={}]>
   >    at __randomizedtesting.SeedInfo.seed([B944BC5A5B893131:52FC433DA47C405A]:0)
   >    at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   >    at org.elasticsearch.xpack.security.authc.file.FileRealmTests.testAuthenticateCaching(FileRealmTests.java:103)
   >    at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by jkakavas**
This changes the default behavior when resolving the hashing
algorithm from unrecognised hash strings, which was introduced in
 #31234

A hash string that doesn't start with an algorithm identifier can
either be a malformed/corrupted hash or a plaintext password when
Hasher.NOOP is used(against warnings).
Do not make assumptions about which of the two is true for such
strings and default to Hasher.NOOP. This covers the case for 
malformed hashes also as hash verification will subsequently
fail.
Finally, do not log the potentially malformed hash as this can very
well be a plaintext password.

Resolves #31697
Reverts 58cf95a

### CODE REVIEW

**Comment by albertzaharovits** [comment]
@jkakavas I think it might be better to have a tag for the NOOP hashing algo as well, and not rely on the leniency that any hash string is valid and must be a NOOP hash? Although it will not be NOOP anymore, since the op adds a prefix? I think there might be exceptional debugging cases where you might wonder if a password hash entry is valid or is NOOP since it was randomly generated in a failing test.

I don't see my suggestion impactful in any way, since NOOP hash will be used exclusively for debugging purposes (as only secure options are allowed: https://github.com/elastic/elasticsearch/blob/1dd10fe69f75c979292f3f0db27ef6671d8cce54/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authc/support/Hasher.java#L552)

**Comment by jkakavas** [comment]
Thanks @albertzaharovits. I would like to propose to deprecate the NOOP hasher in a future release and thus didn't want to make any further changes to related behavior but I have no objection going forward with your suggestions. As you said, I don't see this impacting functionality

**Comment by albertzaharovits** [comment]
Gotcha. Thanks for the FYI.

**Review by jaymode — APPROVED** [review]
LGTM

**Comment by jkakavas** [comment]
@albertzaharovits I will merge this as is and depending on the outcome of the discussion on the NOOP hasher, I will raise a new one if deemed necessary. Is this ok with you?

**Comment by albertzaharovits** [comment]
Sure, it was only a thought.

**Pull request merged**
