### PR TITLE
remove `ClusterDeprecationChecks.checkShards` code

### LINKED ISSUE #94079: Move `checkShards` from Deprecation API to Health API
## What?

Currently, in order to upgrade a cluster to a newer version, a set of checks are run validating that it's safe to upgrade. [One of these checks validates](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/deprecation/src/main/java/org/elasticsearch/xpack/deprecation/ClusterDeprecationChecks.java#L23) that there's enough room in the cluster to create new shards for (potential) intermediate indices. 

## How

The main idea it creates a new indicator into the new [Health API](https://www.elastic.co/guide/en/elasticsearch/reference/master/health-api.html), in such a way it'll be displayed on the `Deployment Management > Monitoring > Health page`. Later, the Cluster Upgrade Tool should use this indicator to validate that upgrading the cluster is safe. Also, the check should be removed from the Deprecation API.

## Tasks

- [x] Talk with the UI team to confirm that the new indicator, once exposed in the UI, will automatically appear in the UI or it must be developed involved
- [x] Create all the machinery in Elasticsearch repo to expose the new Health API indicator (ticket tracking this work #91119)
- [x] Start the conversations with the Cloud team about the needed changes on their side to use this indicator –or any other new indicator– to block upgrades in case the cluster is Unhealthy.
- [ ] Removes the old check from the Deprecation API #95177

### Related

* PR introducing the check https://github.com/elastic/elasticsearch/pull/85967

### PR DESCRIPTION
**Pull request by HiDAl**
In #94552 was introduced a new Health Service which checks the shards capacity of the cluster. This method is replacing the Old `ClusterDeprecationChecks#checkShard` used to validate the feasibility of upgrading a cluster.

Closes #94079

### CODE REVIEW

**Review by masseyke — APPROVED** [review]
Looks good to me, assuming the UI team is now using the health API in the upgrade assistant.

**Comment by HiDAl** [comment]
I've talked with @Bamieh about this and he told me that they don't expect they will have this work complete for this release (`v8.8`). Just to keep compatibility with the old mechanism to block upgrades, I'll keep the PR open.

**Comment by HiDAl** [comment]
@elasticmachine update branch

**Comment by HiDAl** [comment]
Hey @Bamieh, is your code merged already? thank you

**Comment by HiDAl** [comment]
waiting on elastic/kibana#153051

**Comment by HiDAl** [comment]
All the changes in Kibana's side are completed. Finally we can merge this PR

**Pull request merged**
