### PR TITLE
Override bulk visit methods of exitable point visitor

### PR DESCRIPTION
**Pull request by vsop-479**
Add visit(DocIdSetIterator iterator, byte[] packedValue) in ExitableDirectoryReader to invoke PointRangeQuery's anonymous inner classes' visit(DocIdSetIterator iterator, byte[] packedValue), which just match packedValue per point. 
Otherwise, it will invoke visit(int docID, byte[] packedValue) which matches packedValue per doc.

This PR can make PointRangeQuery, PointInSetQuery etc more efficent.

### CODE REVIEW

**Comment by dnhatn** [comment]
@vsop-479 Good catch. Can you also override the `visit(DocIdSetIterator iterator)` method? Thank you for your contribution.

**Comment by dnhatn** [comment]
@elasticmachine update branch

**Comment by vsop-479** [comment]
@dnhatn Thank you for your comment. I have overridden the visit(DocIdSetIterator iterator) method, please have a review.

**Comment by javanna** [comment]
Do we need a test for this change? Would it be possible to update the description adding a note on what effect this change has high-level?

**Comment by vsop-479** [comment]
@javanna I have verified that with this PR, ExitableDirectoryReader$ExitableIntersectVisitor can compare packedValue per point, which is efficient. 
Otherwise, it will call PointValues.IntersectVisitor's default method, which must compare packedValue per doc. 

this PR's invoke stack:
image

original invoke stack:
image

**Comment by vsop-479** [comment]
Is there any further progess on this PR?

**Comment by javanna** [comment]
@dnhatn any idea on a test that could be added? Would it make sense to add one? I will leave this for you to decide and get in, thanks!

**Comment by dnhatn** [comment]
@javanna I have some ideas to write a test for this. However, we need to fix [AssertingIntersectVisitor](https://github.com/apache/lucene/blob/34154736c6ed241d7d9d0c6f4a0e6419936490b7/lucene/test-framework/src/java/org/apache/lucene/tests/index/AssertingLeafReader.java#L1242) in Lucene first. These bulk methods may not be called in tests because AssertingIntersectVisitor doesn't override them.

**Comment by dnhatn** [comment]
@elasticmachine update branch

**Comment by dnhatn** [comment]
@elasticmachine ok to test

**Review by dnhatn — APPROVED** [review]
LGTM. Thanks for your contribution @vsop-479.

**Comment by dnhatn** [comment]
@javanna The test for this PR is ad-hoc, and I decided to merge without it.

**Comment by vsop-479** [comment]
@dnhatn Thanks for your review and fix.

**Comment by javanna** [comment]
++ thanks for the heads up and for merging this in @dnhatn

**Pull request merged**
