### PR TITLE
Fix thirdParty audit task for ingest_attachment plugin

### PR DESCRIPTION
**Pull request by cbuescher**
On the 5.6 branch this task fails on Java 9 because
javax/xml/bind/Marshaller.class and
javax/xml/bind/helpers/DefaultValidationEventHandler.class don't seem to need to
be excluded for Java9.

### CODE REVIEW

**Comment by cbuescher** [comment]
See https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request/7038/console for a related PR failure.

**Comment by cbuescher** [comment]
For what its worth, the `build.gradle` on 6.x already doesn't have those two entries.

**Comment by cbuescher** [comment]
Mr. Jenkins want to let us know that:
```
16:17:12 Execution failed for task ':plugins:lang-python:thirdPartyAudit'.
16:17:12 > Invalid exclusions, nothing is wrong with these classes: [javax/xml/datatype/SecuritySupport$5.class, javax/xml/parsers/SecuritySupport$5.class, javax/xml/stream/SecuritySupport$1.class, javax/xml/stream/SecuritySupport$2.class, javax/xml/stream/SecuritySupport$3.class, javax/xml/stream/SecuritySupport$4.class, javax/xml/stream/SecuritySupport$5.class, javax/xml/transform/SecuritySupport$5.class, javax/xml/validation/SecuritySupport$6.class, javax/xml/validation/SecuritySupport$7.class, javax/xml/validation/SecuritySupport$8.class, javax/xml/xpath/SecuritySupport$6.class, javax/xml/xpath/SecuritySupport$7.class, javax/xml/xpath/SecuritySupport$8.class, org/xml/sax/helpers/SecuritySupport$1.class, org/xml/sax/helpers/SecuritySupport$2.class, org/xml/sax/helpers/SecuritySupport$3.class, org/xml/sax/helpers/SecuritySupport$4.class]
```
So I guess I'm also going to update those, unless you see anything wrong with it.

**Comment by jasontedor** [comment]
This represents a bigger problem.

The problem here is that this build you link to is using JDK 9 and that it is not what we want for 5.6. Instead, this build should be using JDK 8 (as that is what we support and use for builds for 5.6, including our dedicated CI builds). Instead, we need to work with our infrastructure team to use JDK 8 when a PR is targeting 5.6 (and 6.1).

**Comment by cbuescher** [comment]
@jasontedor thanks for the note, so I assume there is no issue for this then? Will open one when I'm back at my keyboard then.

**Comment by cbuescher** [comment]
@jasontedor thanks for opening the issue, I think I can close this PR then.

**Pull request closed without merging**
