### PR TITLE
Add new kNN search endpoint

### PR DESCRIPTION
**Pull request by jtibshirani**
This PR adds a new REST endpoint called `_knn_search` that supports retrieving nearest vectors:
```
POST index/_knn_search
{
  "knn": {
    "field": "image_vector",
    "query_vector": [0.3f, 0.1f, ...],
    "k": 10,
    "num_candidates": 100
  },
  "_source": false,
  "fields": [ "name", "date" ]
}
```

The response has the exact same format as a `_search` response. The `k` closest documents to `query_vector` are returned as `hits`, ranked by their proximity. The `num_cands` parameter controls how many candidate vectors are gathered per shard, before these are merged and sorted to produce the final top `k`. For the HNSW algorithm, `num_cands` corresponds to `efSearch`. Increasing `num_cands` usually improves recall at the expense of latency.

Restrictions:
* The `k` parameter must be less than `num_cands`. To prevent very expensive queries, `num_cands` is limited to 10,000.
* Currently only one kNN search is allowed, but later we could extend the `knn` section to accept an array of kNN definitions.

The endpoint also supports these options from `_search`:
* The `routing` parameter
* All options for loading document content, including source filtering and `fields`. For simplicity, it uses the same default as `_search` where we return the whole `_source` for each hit.

Relates to #78473.

### CODE REVIEW

**Review by jpountz — COMMENTED** [review]
> What do you think about the API choices around k and num_cands?

`k` sounds good to me, but I have a slight preference for `num_candidates` over `num_cands`.

**Review by mayya-sharipova — COMMENTED** [review]
@jtibshirani Thanks for your work, this PR overall looks very nice to me. I left some comments

**Review by sethmlarson — COMMENTED** [review]
Some nitty naming feedback on the API spec, mostly LGTM!

**Review by sethmlarson — APPROVED** [review]
LGTM!

**Review by mayya-sharipova — APPROVED** [review]
@jtibshirani Thanks for iterating! This LGTM, I just left a small comment to use `OBJECT_ARRAY_BOOLEAN_OR_STRING` for _source parsing, but addressing it doesn't need any review from me.

**Review by jimczi — COMMENTED** [review]
I left some additional comments but the API looks good to me.

**Review by jimczi — APPROVED** [review]
LGTM

**Pull request merged**
