### PR TITLE
Change byte page size to 16709 bytes

### PR DESCRIPTION
**Pull request by Tim-Brooks**
This commit modifies the byte page size to be 16709 bytes. Using the
java SSLEngine require pages of that size. They big byte array can still
function properly with 16709 sized pages because it just treats the
pages as if they are 1<<14 bytes.

### CODE REVIEW

**Comment by tbrooks8** [comment]
This is a WIP PR based on @jpountz suggestion here https://github.com/elastic/elasticsearch/pull/39972#issuecomment-474030943. I want to see if this is the direction we want to take. This PR will probably need to be merged after some nio changes to support different sized pages (#39983).

**Comment by jpountz** [comment]
This sounds reasonable to me. We'll need a comment next to the page size to explain the trade-off and why other options haven't been considered. Curious to know what others think.

**Comment by tbrooks8** [comment]
@s1monw - thoughts about this approach? If you are okay with it,  #39983 will need to be approved and merged first so that the transport layer supports non-power-of-2 pages (why the tests are failing currently).

**Comment by s1monw** [comment]
@tbrooks8 does [this](https://github.com/elastic/elasticsearch/pull/39972#issuecomment-474805122) relate to this decision

**Comment by tbrooks8** [comment]
@s1monw  Yes @jpountz suggested this approach (https://github.com/elastic/elasticsearch/pull/39972#issuecomment-474030943).

**Comment by tbrooks8** [comment]
Closing. If we go this route, it will be included in different PRs.

**Pull request closed without merging**
