### PR TITLE
NETWORKING: Fix Netty Leaks by upgrading to 4.1.28

### LINKED ISSUE #32478: Cluster stats return fs total / fs avaliable to 8EB
**Describe the feature**:

**Elasticsearch version** : 5.6.4

**Plugins installed**: []

**JVM version** (`java -version`): 1.8.0_151

**OS version** (`uname -a` if on a Unix-like system):
Linux  3.10.0-693.2.2.el7.x86_64 #1 SMP x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
here same issue in discuss

https://discuss.elastic.co/t/es-cluster-stats-api-returning-false-values/84949

```json
"fs" : {
  "total" : "8192pb",
  "total_in_bytes" : 9223372036854775807,
  "free" : "8192pb",
  "free_in_bytes" : 9223372036854775807,
  "available" : "8192pb",
  "available_in_bytes" : 9223372036854775807
}
```

this issue occur by Elasticsearch Tribe node.
tribe node return like this.
```
name                          dt     du       d
dev-estribe001.ncl/es1       -1b     0b     -1b
```

and cluster stats api using this
```java
ClusterStatsNodes(List<ClusterStatsNodeResponse> nodeResponses) {
        this.versions = new HashSet<>();
        this.fs = new FsInfo.Path();
        this.plugins = new HashSet<>();

        Set<InetAddress> seenAddresses = new HashSet<>(nodeResponses.size());
        List<NodeInfo> nodeInfos = new ArrayList<>(nodeResponses.size());
        List<NodeStats> nodeStats = new ArrayList<>(nodeResponses.size());
        for (ClusterStatsNodeResponse nodeResponse : nodeResponses) {
            // if first nodePresponse are tribe node --> it makes return 8EB
            nodeInfos.add(nodeResponse.nodeInfo());
            nodeStats.add(nodeResponse.nodeStats());
            this.versions.add(nodeResponse.nodeInfo().getVersion());
            this.plugins.addAll(nodeResponse.nodeInfo().getPlugins().getPluginInfos());

            // now do the stats that should be deduped by hardware (implemented by ip deduping)
            TransportAddress publishAddress = nodeResponse.nodeInfo().getTransport().address().publishAddress();
            InetAddress inetAddress = null;
            if (publishAddress.uniqueAddressTypeId() == 1) {
                inetAddress = ((InetSocketTransportAddress) publishAddress).address().getAddress();
            }
            if (!seenAddresses.add(inetAddress)) {
                continue;
            }
            if (nodeResponse.nodeStats().getFs() != null) {
                this.fs.add(nodeResponse.nodeStats().getFs().getTotal());   // <-- here tribe node try to add this.fs
            }
        }
        this.counts = new Counts(nodeInfos);
        this.os = new OsStats(nodeInfos, nodeStats);
        this.process = new ProcessStats(nodeStats);
        this.jvm = new JvmStats(nodeInfos, nodeStats);
        this.networkTypes = new NetworkTypes(nodeInfos);
    }

...

// this.fs.add using this logic
 public void add(Path path) {
            total = FsProbe.adjustForHugeFilesystems(addLong(total, path.total));
            free = FsProbe.adjustForHugeFilesystems(addLong(free, path.free));
            available = FsProbe.adjustForHugeFilesystems(addLong(available, path.available));
            if (path.spins != null && path.spins.booleanValue()) {
                // Spinning is contagious!
                spins = Boolean.TRUE;
            }
        }

...

// if first node are tribe node
// current = -1, other = -1
// so it always return -1;
private long addLong(long current, long other) {
            if (other == -1) {
                return current;
            }
            if (current == -1) {
                return other;
            }
            return current + other;
        }
...

// byte are -1 --> it makes return 8eb
    static long adjustForHugeFilesystems(long bytes) {
        if (bytes < 0) {
            return Long.MAX_VALUE;
        }
        return bytes;
    }
```

so it need to fix like this
```java
private long addLong(long current, long other) {
            if (other == -1 && current == -1){
                return 0;
            }
            if (other == -1) {
                return current;
            }
            if (current == -1) {
                return other;
            }
            return current + other;
        }

        private double addDouble(double current, double other) {
            if (other == -1 && current == -1){
                return 0;
            }
            if (other == -1) {
                return current;
            }
            if (current == -1) {
                return other;
            }
            return current + other;
        }
```

**Steps to reproduce**:
hard to re produce it.
because First NodeResponse have to tribe node.

**Provide logs (if relevant)**:

### LINKED ISSUE #32487: [CI] SslIntegrationTests fail with Netty buffer leak
Build failure link: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=java10,ES_RUNTIME_JAVA=java11,nodes=virtual&&linux/208/console

Build failure:

```
   > Expected: an empty collection
   >      but: <[LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
   > WARNING: 4 leak records were discarded because the leak record count is limited to 4. Use system property io.netty.leakDetection.maxRecords to increase the limit.
   > Recent access records: 4
   > #4:
   >    io.netty.buffer.AdvancedLeakAwareByteBuf.internalNioBuffer(AdvancedLeakAwareByteBuf.java:732)
[...]
   >    io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
   >    java.base/java.lang.Thread.run(Thread.java:834)
   > #3:
   >    io.netty.buffer.AdvancedLeakAwareByteBuf.nioBufferCount(AdvancedLeakAwareByteBuf.java:702)
   >    io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:927)
   >    io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:762)
   >    io.netty.handler.ssl.SslHandler.wrapAndFlush(SslHandler.java:731)
   >    io.netty.handler.ssl.SslHandler.flush(SslHandler.java:712)
[...]
   >    java.base/java.lang.Thread.run(Thread.java:834)
   > #2:
   >    io.netty.buffer.AdvancedLeakAwareByteBuf.nioBufferCount(AdvancedLeakAwareByteBuf.java:702)
   >    io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:759)
   >    io.netty.handler.ssl.SslHandler.wrapAndFlush(SslHandler.java:731)
   >    io.netty.handler.ssl.SslHandler.flush(SslHandler.java:712)
[...]
   >    java.base/java.lang.Thread.run(Thread.java:834)
   > #1:
   >    io.netty.buffer.AdvancedLeakAwareByteBuf.writeBytes(AdvancedLeakAwareByteBuf.java:588)
   >    io.netty.handler.ssl.SslHandler$SslHandlerCoalescingBufferQueue.composeFirst(SslHandler.java:1831)
   >    io.netty.channel.AbstractCoalescingBufferQueue.remove(AbstractCoalescingBufferQueue.java:154)
   >    io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:752)
   >    io.netty.handler.ssl.SslHandler.wrapAndFlush(SslHandler.java:731)
   >    io.netty.handler.ssl.SslHandler.flush(SslHandler.java:712)
[...]
   >    io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
   >    java.base/java.lang.Thread.run(Thread.java:834)
   > Created at:
   >    io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:331)
   >    io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:181)
   >    io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:172)
   >    io.netty.handler.ssl.SslHandler$SslHandlerCoalescingBufferQueue.composeFirst(SslHandler.java:1830)
   >    io.netty.channel.AbstractCoalescingBufferQueue.remove(AbstractCoalescingBufferQueue.java:154)
   >    io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:752)
   >    io.netty.handler.ssl.SslHandler.wrapAndFlush(SslHandler.java:731)
   >    io.netty.handler.ssl.SslHandler.flush(SslHandler.java:712)
[...]
   >    java.base/java.lang.Thread.run(Thread.java:834)]>
```

Reproduces locally with:

```
./gradlew :x-pack:plugin:security:test -Dtests.seed=28197402351DB64D -Dtests.class=org.elasticsearch.xpack.security.transport.ssl.SslIntegrationTests -Dtests.method="testThatUnconfiguredCiphersAreRejected" -Dtests.security.manager=true -Dtests.locale=fr-MC -Dtests.timezone=SystemV/MST7
```

Note that one other test failed  as well in the same test run but as the underlying cause appears to be the same I just created one ticket.

Here are all reproduction lines:

```
REPRODUCE WITH: ./gradlew :x-pack:plugin:security:test \
  -Dtests.seed=28197402351DB64D \
  -Dtests.class=org.elasticsearch.xpack.security.transport.ssl.SslIntegrationTests \
  -Dtests.method="testThatTransportClientUsingSSLv3ProtocolIsRejected" \
  -Dtests.security.manager=true \
  -Dtests.locale=fr-MC \
  -Dtests.timezone=SystemV/MST7

REPRODUCE WITH: ./gradlew :x-pack:plugin:security:test \
  -Dtests.seed=28197402351DB64D \
  -Dtests.class=org.elasticsearch.xpack.security.transport.ssl.SslIntegrationTests \
  -Dtests.method="testThatUnconfiguredCiphersAreRejected" \
  -Dtests.security.manager=true \
  -Dtests.locale=fr-MC \
  -Dtests.timezone=SystemV/MST7
```

### PR DESCRIPTION
**Pull request by original-brownbear**
* Upgrade to `4.1.28` since the problem reported in #32487  is a bug in Netty itself (see https://github.com/netty/netty/issues/7337)
* Fixed other leaks in test code that now showed up due to fixes improvements in leak reporting in the newer version
* Needed to extend permissions for netty common package because it now sets a classloader at runtime after changes in https://github.com/netty/netty/commit/63bae0956aeb42e875ad303a2281989ad92acbf2
* Adjusted forbidden APIs check accordingly
* Closes #32487

### CODE REVIEW

**Review by jasontedor — APPROVED** [review]
LGTM. If CI is happy, I am happy. This is so much better than the circus we had in #31232.

**Comment by original-brownbear** [comment]
Jenkins test this
(CI was green, packaging test didn't trigger for some reason)

**Review by Tim-Brooks — APPROVED** [review]
LGTM

The code does not really bother me since it is in unit tests. But it looks like netty does have a facility for releasing RCs in testing without try/finally.

http://netty.io/wiki/reference-counted-objects.html

```
public void testSomething() throws Exception {
    // ReferenceCountUtil.releaseLater() will keep the reference of buf,
    // and then release it when the test thread is terminated.
    ByteBuf buf = ReferenceCountUtil.releaseLater(Unpooled.directBuffer(512));
    ...
}
```

I don't know how effective that is. But something to maybe look at in future fixes.

**Comment by original-brownbear** [comment]
@tbrooks8 thanks!

I'm just fixing those tests, so the leak detector doesn't go red :) `io.netty.util.ReferenceCountUtil#releaseLater(T)` is deprecated (and in my experience/opinion rightfully so). It's just taking too much memory potentially because buffers are kept around for the whole duration of the test run which can really add up in unexpected ways.

**Pull request merged**
