### PR TITLE
Don't spin up a whole node to unit test some data structures

### PR DESCRIPTION
**Pull request by romseygeek**
BytesRefHashTests and LongObjectHashMapTests currently extend ESSingleNodeTestCase,
which builds an entire node just to run some unit tests over entirely in-memory data 
structures.  This commit converts them both to extend ESTestCase.

### CODE REVIEW

**Review by nik9000 — APPROVED** [review]
LGTM

**Comment by romseygeek** [comment]
@elasticmachine run elasticsearch-ci/bwc (wtf?)

**Comment by romseygeek** [comment]
@elasticmachine update branch

**Comment by romseygeek** [comment]
@elasticmachine run elasticsearch-ci/2 (active directory test failure)

**Pull request merged**
