### PR TITLE
Replace failure.get().addSuppressed with failure.accumulateAndGet()

### PR DESCRIPTION
**Pull request by javanna**
Replace failure.get().addSuppressed with failure.accumulateAndGet() in GroupedActionListener, also add a test for concurrent incoming failures.

### CODE REVIEW

**Comment by javanna** [comment]
Actually, failure.get().addSuppressed is fine as-is, as we keep on adding to the same exception (the exception in the reference never changes once set) and addSuppressed is synchronized. I may just merge the test and revert the change to GroupedActionListener.

**Review by s1monw — APPROVED** [review]

**Comment by javanna** [comment]
retest this please

**Comment by javanna** [comment]
run elasticsearch-ci/1

**Comment by jasontedor** [comment]
I backported this to 6.8 since I applied a bug fix on top of it in #53262.

**Pull request merged**
