### PR TITLE
Added include_type_name in API spec for indices.exists

### PR DESCRIPTION
**Pull request by ezimuel**
This PR adds the `include_type_name` in API `6.7` specification for `indices.exists` as discussed in #54292

### CODE REVIEW

**Review by cbuescher — APPROVED** [review]
@ezimuel thanks, the change looks good to me, wondering what the CI failures are about though.
Maybe its difficult running CI on those older branches? Will dig a bit...

**Comment by cbuescher** [comment]
@elasticmachine update branch

**Comment by mark-vieira** [comment]
@ezimuel I read your [comment here](https://github.com/elastic/elasticsearch/issues/54292#issuecomment-606000486) do I understand correctly that the purpose of this PR is to go back and update the specs for 6.7 to include a missing bit that _should_ have been there?

Is this needed for any work or pending release by the clients team itself, or is this purely wanting to update the old specs for posterity?

**Comment by ezimuel** [comment]
@mark-vieira I discovered this issue working on https://github.com/elastic/elasticsearch-perl/issues/169#issuecomment-603977006, when I was working on [elasticsearch-perl 6.8](https://github.com/elastic/elasticsearch-perl/releases/tag/version_6.80) release for the Perl client. The Perl client was not updated since 6.0 and I'm trying to fill the gap with new releases.

**Comment by mark-vieira** [comment]
> The Perl client was not updated since 6.0 and I'm trying to fill the gap with new releases.

So we are retroactively releasing Perl clients for each 6.x version?

**Comment by ezimuel** [comment]
@mark-vieira I'm trying to fill the gap on the elasticsearch-perl client. I released 6.80 and I'm working to release soon 7.3 and hopefully the next minor 7.8. I'm doing this since I've a code generator in place that works until 7.4, when [we changed](https://github.com/elastic/elasticsearch/pull/42346) the API specs. I need to update this generator in order to release the latest version.

**Comment by cbuescher** [comment]
@ezimuel any idea what should happen with this PR? I'm just scanning some of my old issues and wonder if this can be closed or should be moved forward?

**Comment by ezimuel** [comment]
@cbuescher I can close this PR since I managed the `include_type_name` parameter myself. Thanks.

**Pull request closed without merging**
