### PR TITLE
Upgrade to lucene-5.4-snapshot-1708254.

### PR DESCRIPTION
**Pull request by jpountz**

### CODE REVIEW

**Comment by mikemccand** [comment]
LGTM

**Comment by rmuir** [comment]
I don't see regenerated sha1s... did you run `dev-tools/update_lucene.sh` ?

**Comment by jpountz** [comment]
@rmuir good call, I thought I had run verify but apparently not. I just updated the PR

**Comment by rmuir** [comment]
looks good, thanks!

**Pull request merged**
