### PR TITLE
Docs fix- added performance note about plain highlighter

### LINKED ISSUE #11442: Search optimization - Highlighter causes many query rewrites
A user reported very slow performance here https://github.com/elastic/elasticsearch/pull/10391#issuecomment-105466848

The issue is that the query being highlighted does not have its rewritten form cached and consequently is rewritten for every doc x field being highlighted.

### PR DESCRIPTION
**Pull request by markharwood**
Closes #11442

### CODE REVIEW

**Comment by clintongormley** [comment]
LGTM

**Comment by colings86** [comment]
LGTM

**Comment by nik9000** [comment]
+1

**Comment by markharwood** [comment]
Pushed to master https://github.com/elastic/elasticsearch/commit/52fb3c3a09d7f5574cd5bcff912df005466107f0

**Pull request closed without merging**
