### PR TITLE
Upgrade to netty 3.10.6.Final

### PR DESCRIPTION
**Pull request by s1monw**
This upgrades to the latest netty release. @rjernst I ran `gradle check` on the distribution project and nothing failed even when I had not yet upgraded the sha1. Running `gradle dependencyLicenses` did it, maybe something is broken here?

### CODE REVIEW

**Comment by jasontedor** [comment]
LGTM.

**Comment by rjernst** [comment]
@s1monw I made the same change and it failed for me as expected...
```
[11:22:48][~/Code/elasticsearch/distribution]$ git diff
diff --git a/core/build.gradle b/core/build.gradle
index 88c5cc2..2231880 100644
--- a/core/build.gradle
+++ b/core/build.gradle
@@ -75,7 +75,7 @@ dependencies {
   compile "com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:${versions.jackson}"

   // network stack
-  compile 'io.netty:netty:3.10.5.Final'
+  compile 'io.netty:netty:3.10.6.Final'
   // percentiles aggregation
   compile 'com.tdunning:t-digest:3.0'
   // precentil ranks aggregation
[11:22:29][~/Code/elasticsearch/distribution]$ gradle check
...
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':distribution:dependencyLicenses'.
> Missing SHA for netty-3.10.6.Final.jar. Run 'gradle updateSHAs' to create
```

**Comment by salyh** [comment]
Netty 3 is EOL and 3.10.6.Final would be the last release. Looking into https://github.com/elastic/elasticsearch/issues/3226 it does not look like an update to 4.0 or 4.1 is considered for ES 5?

**Comment by s1monw** [comment]
> Netty 3 is EOL and 3.10.6.Final would be the last release. Looking into #3226 it does not look like an update to 4.0 or 4.1 is considered for ES 5?

There is no issue yet but we are working on the future of networking. In a nutshell the plan is to modularize netty3 (build it as a plugin) and have a second module with netty4 such that we can do an experimental phase with the new networking. It's such a crucial part of the system that we want a safety net for the new version since a rather large portion of netty has changed fundamentally and we first need to learn how it affects ES. As a sideeffect this will allow us to do much better code isolation also in terms of security permissions etc. Yet, netty4 might not come with 5.0GA but I am confident it will come soon after.

There is work under way related to this like #19196 #19129 #19125 #19096 so we are actively working on this. I hope that helps... I will open a modularization issue soon too

**Pull request merged**
