### PR TITLE
Run ILM and SLM stopping cluster state updates at IMMEDIATE priority

### LINKED ISSUE #80099: Transport Stop ILM+SLM Actions Should execute at IMMEDIATE Priority
The `OperationModeUpdateTask` states the following which makes sense:

```java
/**
 * This task updates the operation mode state for ILM.
 *
 * As stopping ILM proved to be an action we want to sometimes take in order to allow clusters to stabilise when under heavy load this
 * task might run at {@link Priority#IMMEDIATE} priority so please make sure to keep this task as lightweight as possible.
 */
```

We want to be able to execute this at immediate priority in case of an unstable cluster that is piling up ILM/SLM work and thus blocking CS updates at lower priority. Unfortunately, in practice this always runs at normal priority because we mostly execute it wrapped in another CS update task like in `TransportStopSLMAction`.

```java
clusterService.submitStateUpdateTask("slm_operation_mode_update", new AckedClusterStateUpdateTask(request, listener) {
   @Override
        public ClusterState execute(ClusterState currentState) {
           return (OperationModeUpdateTask.slmMode(OperationMode.STOPPING)).execute(currentState);
        }
});
```

We should actually have this run at immediate priority. Also, this is missing logging for when the tasks is executed successfully, which is really important to have for debugging purposes.

### PR DESCRIPTION
**Pull request by dakrone**
Due to wrapping of the tasks, the update tasks could be executed at `NORMAL` priority by mistake.
This ensures they are run at the `IMMEDIATE` priority. It also adds logging when the cluster state
update has been processed so that an administrator can see what the state has been changed to.

Resolves #80099

### CODE REVIEW

**Review by joegallo — CHANGES_REQUESTED** [review]
For the `ilmMode`/`slmMode` helpers, might it be worth having an assert that verifies that if we're ever pushing through a stopping/stopped through then the priority must be immediate? (This is definitely a question, and not an insistence that's disguised as a question.)

**Comment by dakrone** [comment]
> ... that verifies that if we're ever pushing through a stopping/stopped through then the priority must be immediate?

I can change the decision logic for which priority to use to always just be either `NORMAL` or `IMMEDIATE` and leave it out of the caller's hands, if we would prefer. It would mean that a caller could never change it, but we don't currently have any callers that change it anyway.

**Comment by dakrone** [comment]
Sounds good, I pushed a commit that makes the priority opaque to the caller.

**Review by joegallo — APPROVED** [review]
Ship it!

**Comment by dakrone** [comment]
@elasticmachine update branch

**Pull request merged**
