### PR TITLE
Internal: Change version constant names for already released versions

### PR DESCRIPTION
**Pull request by rjernst**
We have many version constants in master that have already been
released, but are still marked (by naming convention) as unreleased.
This commit renames those version constants.

### CODE REVIEW

**Review by bleskes — APPROVED** [review]
LGTM. Good one.

**Comment by jasontedor** [comment]
These were left unreleased because we have a problem to work out with minimum compatibility version. I think that this is going to cause the build to fail.

**Comment by rjernst** [comment]
@jasontedor I've reverted the change for now.

**Comment by jasontedor** [comment]
Thanks @rjernst!

**Pull request merged**
