### PR TITLE
Fix calling ensureOpen() on the wrong directory

### PR DESCRIPTION
**Pull request by dakrone**
Also removes `ensureCanWrite` since this already passes the
`TRUNCATE_EXISTING` flag when opening.

Adds a REST test that fails without this fix due to the classloader
isolation.

Additionally, move `SmbDirectoryWrapper` into an elasticsearch package instead of a lucene one, so this would be found at compile time instead of runtime.

### CODE REVIEW

**Comment by dakrone** [comment]
This is only for 2.x, since a lot of files were moved all over the place I will forward-port separately.

**Comment by rmuir** [comment]
+1

**Comment by dakrone** [comment]
Actually, I believe this is also a problem is 2.2.0, so I will backport this to the `2.2` branch so it's available in the 2.2.1 release (whenever that is)

**Comment by rmuir** [comment]
It might be beneficial to consider https://github.com/elastic/elasticsearch/pull/16325 as well. IMO its a serious bug :)

**Comment by dakrone** [comment]
@rmuir I agree, I'm going to backport it to 2.2.1

**Pull request merged**
