### PR TITLE
Correctly handle mixed object paths in XContentMapValues

### LINKED ISSUE #65499: Fields API won't extract field that begins with the name of an object
Check it out:
```
curl -XDELETE -HContent-Type:application/json -uelastic:password localhost:9200/test

curl -XPOST -HContent-Type:application/json -uelastic:password localhost:9200/test/_doc?refresh -d'{
  "foo": {
    "cat": "meow"
  },
  "foo.bar": "baz"
}'

curl -XPOST -HContent-Type:application/json -uelastic:password localhost:9200/test/_search?pretty -d'{
  "fields": ["foo.bar"]
}'
```

Makes this:
```
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 1,
      "relation" : "eq"
    },
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "test",
        "_id" : "kyfg_3UBbogJq0WOeKye",
        "_score" : 1.0,
        "_source" : {
          "foo" : {
            "cat" : "meow"
          },
          "foo.bar" : "baz"
        }
      }
    ]
  }
}
```

Notice no `fields` in the response. This seems to be because we found the `foo` object and didn't find `bar` inside it. I'm not sure though. It seems like we should find `foo.bar`.

These kinds of documents are confusing in general and folks probably shouldn't be sending them to us. I think *generally* if we get them it is because someone made a mistake in their application. But we should still handle them.

### PR DESCRIPTION
**Pull request by romseygeek**
When we have an object that looks like this:

```
{
  "foo" : {
    "cat", "meow"
  },
  "foo.bar" : "baz"
```

where the inner objects of `foo` are defined both as json objects and via
dot notation, then XContentMapValues.extractValue() will only descend
through the json object and will not collect values from the dot notated paths.
In these cases, the `foo.bar` values will not be returned in the `fields`
section of a search response.

This commit adds the ability to check both paths, ensuring that all relevant
values get returned as part of `fields`.

Fixes #65499

### CODE REVIEW

**Comment by romseygeek** [comment]
I've marked this for 7.11 but we could conceivably backport it to 7.10.1 as well.

**Comment by romseygeek** [comment]
@elasticmachine update branch

**Review by cbuescher — APPROVED** [review]
I took a look since the case this issue fixes also might be interesting for https://github.com/elastic/elasticsearch/pull/65386 and the change here makes sense to me. LGTM, but maybe you want to wait for a second pair of eyes here.

**Review by nik9000 — APPROVED** [review]
LGTM

**Comment by jtibshirani** [comment]
Thanks @romseygeek for fixing this! I noticed there's a related but slightly different edge case:

```
{
  "foo" : {
    "bar", "meow"
  },
  "foo.bar" : "baz"
}
```

Surprisingly, we allow documents to specify a field both in structured object and dot notation. When parsing, we index both values as if it were specified as an array.


Your PR fixes the problem for `XContentMapValues#extractRawValues` -- maybe we could add a quick test for that. I could file a separate issue about field fetching/ `XContentMapValues#extractValue`, which still doesn't handle this correctly.

**Comment by romseygeek** [comment]
> Your PR fixes the problem for XContentMapValues#extractRawValues -- maybe we could add a quick test for that. I could file a separate issue about field fetching/ XContentMapValues#extractValue, which still doesn't handle this correctly.

I've pushed a test for your second case.  `extractValue` is trickier because it only returns a single value, so let's deal with that in a separate issue.

**Pull request merged**
