### PR TITLE
version bump 6.8.0 -> 6.8.1

### PR DESCRIPTION
**Pull request by jakelandis**

### CODE REVIEW

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by jakelandis** [comment]
Removing 7x and 8x labels in favor of https://github.com/elastic/elasticsearch/pull/42242 which also includes the relevant changes here.

**Comment by jakelandis** [comment]
@elasticmachine test this please

**Comment by jakelandis** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Pull request merged**
