### PR TITLE
[8.x] Only aggregations require at least one shard request (#115314)

### PR DESCRIPTION
**Pull request by piergm**
# Backport

This will backport the following commits from `main` to `8.x`:
 - [Only aggregations require at least one shard request (#115314)](https://github.com/elastic/elasticsearch/pull/115314)

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

### CODE REVIEW

**Comment by piergm** [comment]
@elasticmachine update branch

**Comment by piergm** [comment]
@elasticmachine update branch

**Comment by cbuescher** [comment]
@piergm I was trying to backport https://github.com/elastic/elasticsearch/pull/117649 and am just seeint this backport here is still open. Would you mind adjusting the test in question in case this gets merged?
I also wonder why OldRepositoryAccessIT is muted then on the 8.x branch, I will open a PR to remove that mute given this problem shouldn't exist on 8.x?

**Comment by piergm** [comment]
@elasticmachine update branch

**Pull request merged**
