### PR TITLE
Bubble exceptions up in ClusterApplierService

### PR DESCRIPTION
**Pull request by ywelsch**
Exceptions thrown by the cluster applier service's settings and cluster appliers are bubbled up, and block the state from being applied instead of silently being ignored. In combination with the cluster state publishing lag detector, this will throw a node out of the cluster that can't properly apply cluster state updates.

### CODE REVIEW

**Review by DaveCTurner — CHANGES_REQUESTED** [review]
I left a few nits but otherwise this looks ok to me.

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Comment by ywelsch** [comment]
@elasticmachine please run the elasticsearch-ci/2 tests

**Comment by ywelsch** [comment]
@elasticmachine test elasticsearch-ci/2 please

**Comment by ywelsch** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by ywelsch** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by ywelsch** [comment]
@elasticmachine run elasticsearch-ci/1
@elasticmachine run elasticsearch-ci/2

**Pull request merged**
