### PR TITLE
Prevent normalizer from accidentally not being closed on exception

### PR DESCRIPTION
**Pull request by cbuescher**
Currently AnalysisRegistry#processNormalizerFactory creates a normalizer and
only later checks whether it should be added to the normalizer map passed in. In
case we throw an exception it isn't closed. This can be prevented by moving the
check that throws the exception earlier.

### CODE REVIEW

**Review by romseygeek — APPROVED** [review]
LGTM

**Comment by cbuescher** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by cbuescher** [comment]
@elasticmachine run elasticsearch-ci/default-distro

**Comment by cbuescher** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by cbuescher** [comment]
@elasticmachine run elasticsearch-ci/1

**Pull request merged**
