### PR TITLE
Limit _FILE env var support to specific vars

### LINKED ISSUE #52503: Elasticsearch 7.6.0 cannot be used as service in GitLab pipeline anymore
Starting with version 7.6.0 Elasticsearch cannot be started as service in a Gitlab pipeline anymore.

Gitlab sets a `CI_SERVER_TLS_CA_FILE` variable which contains a path to a file.
It seems that this variable is now expanded to contain the content of the file.

```
Service container logs:
2020-02-19T06:52:56.510497268Z ERROR: File -----BEGIN CERTIFICATE-----
2020-02-19T06:52:56.510521348Z ....
2020-02-19T06:52:56.510608065Z -----END CERTIFICATE-----
2020-02-19T06:52:56.510610718Z  from CI_SERVER_TLS_CA_FILE does not exist
```

I am not completely sure if this is an Elasticsearch issue or not, but I figured out that Elasticsearch [does some environment variable processing](https://github.com/elastic/elasticsearch/commit/2bd3a0589259ffda6caf27bf23bb8ed8813bc4e9) and it could very well be the cause of this issue:

> Also extract the support for `_FILE` env vars into a separate script, so
> that it can be called from more than once place (the behaviour is
> idempotent).

https://github.com/elastic/elasticsearch/blob/v7.6.0/distribution/src/bin/elasticsearch-env-from-file

### PR DESCRIPTION
**Pull request by pugnascotia**
Closes #52503. Implement a list of `_FILE` env vars that will be used to
populate env vars with file content, instead of processing all `_FILE`
vars in the environment.

### CODE REVIEW

**Review by rjernst — APPROVED** [review]
LGTM, but why do we have ES_JAVA_OPTS file when you can already have jvm.options file, especially now that there is jvm.options.d?

**Comment by pugnascotia** [comment]
This short and somewhat poor answer is, an existing test depended on it. I did consider whether we wanted to support `ES_JAVA_OPTS_FILE`, and it didn't seem unreasonable that someone might have a lengthy set of options that they wanted to keep in version control, and therefore pass as a file. However you're quite right, in that case `jvm.options.d` is a better choice, which I had forgotten about. I'll remove that option and the associated test (or rework it if I can).

**Comment by pugnascotia** [comment]
@rjernst I removed `ES_JAVA_OPTS_FILE` and reworked the tests, including adding coverage for `KEYSTORE_PASSWORD_FILE` which was lacking. Can you take another look?

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by pugnascotia** [comment]
@elasticmachine run elasticsearch-ci/packaging-matrix-unix

**Comment by pugnascotia** [comment]
@elasticmachine update branch

**Comment by ywelsch** [comment]
Please use a top-level label (e.g., bug, enhancement, feature, etc.) for each PR, as this is used for generating the release notes.

**Pull request merged**
