### PR TITLE
[Tests] Update skip version for YAML tests

### PR DESCRIPTION
**Pull request by matriv**
Update skip versions upper boundary to match the release
or intended release version of the feature/fix.

### CODE REVIEW

**Comment by ywelsch** [comment]
Why is this PR against 7.x? Should this not also go into master, as as far as I can see, the versions in master are not correct either?

**Comment by matriv** [comment]
> Why is this PR against 7.x? Should this not also go into master, as as far as I can see, the versions in master are not correct either?

I was planning to do it in reverse, Check 7.x for stuff already released and update the versions -> apply to master.

**Review by ywelsch — APPROVED** [review]
ok, sounds good. Perhaps manually run `./gradlew bwcTest` to make sure the tests indeed work with all older versions (CI job does not check this)

**Review by jasontedor — APPROVED** [review]
LGTM.

**Pull request merged**
