### PR TITLE
SQL: Remove restriction for single column grouping

### LINKED ISSUE #31793: SQL: Allow multiple fields inside GROUP BY
Currently, SQL restricts `GROUP BY` to only one field, namely for historical reasons. As there are no technical reasons for this, the restriction should be removed.

### PR DESCRIPTION
**Pull request by costin**
For historical reasons SQL restricts GROUP BY to only one field.
This commit removes the restriction and improves the test suite with
multi group by tests.

Close #31793

### CODE REVIEW

**Review by imotov — COMMENTED** [review]
I think we should either document of fix the limitation that the sequence of fields in GROUP BY and ORDER BY has to be the same. For example, this statement doesn't seem to work:
```
SELECT gender g, languages l FROM "test_emp" GROUP BY gender, languages ORDER BY languages ASC, gender ASC
```

**Review by nik9000 — APPROVED** [review]

**Comment by costin** [comment]
@imotov I've tried reproducing the issue and it works:

```
SELECT gender AS g, languages FROM emp GROUP BY gender, languages ORDER BY languages ASC, gender ASC;

       g       |   languages   
---------------+---------------
F              |1              
F              |2              
F              |3              
F              |4              
F              |5              
M              |1              
M              |2              
M              |3              
M              |4              
M              |5    

SELECT gender AS g, languages FROM emp GROUP BY gender, languages ORDER BY languages ASC, gender DESC;

       g       |   languages   
---------------+---------------
M              |1              
M              |2              
M              |3              
M              |4              
M              |5              
F              |1              
F              |2              
F              |3              
F              |4              
F              |5       

SELECT gender AS g, languages FROM emp GROUP BY gender, languages ORDER BY languages DESC, gender DESC;
       g       |   languages   
---------------+---------------
M              |5              
M              |4              
M              |3              
M              |2              
M              |1              
F              |5              
F              |4              
F              |3              
F              |2              
F              |1              

```

Maybe the error is not about ES or you are using the wrong branch?

**Comment by costin** [comment]
Actually scratch that, the order is incorrect...should be first language and then gender...

**Comment by costin** [comment]
Found the issue - we don't align the order of the groups with that of the order but rather keep them in declaration format which creates the incorrect order.
I'm looking into fixing this as part of this PR.

**Review by astefan — APPROVED** [review]
LGTM

**Comment by costin** [comment]
Pushed the fix and updated the test suite along with the docs.

**Review by bpintea — APPROVED** [review]
LGTM

**Pull request merged**
