### PR TITLE
Add Shrink request source parser to parse create index request body

### PR DESCRIPTION
**Pull request by areek**
This commit enforces that the shrink request body contains only `settings` and `aliases` for underlying create index request

Follow up to https://github.com/elastic/elasticsearch/pull/18732#discussion_r66407196

### CODE REVIEW

**Comment by s1monw** [comment]
Looks good, I think we need to update documentation too?

**Comment by areek** [comment]
@s1monw the documentation looks appropriate:
```
The `_shrink` API is similar to the <<indices-create-index, `create index` API>>
and accepts `settings` and `aliases` parameters for the target index:
```
do you think it makes sense to add anything to it?

**Comment by clintongormley** [comment]
@areek Sorry for the late comment but I think that the rollover API should accept a full create-index body, rather than be limited to settings and aliases, otherwise you have to use index templates regardless.

**Comment by clintongormley** [comment]
Sorry, my last comment was meant for the rollover API, not shrink

**Pull request merged**
