### PR TITLE
Add Flags Parameter for Char Filter

### LINKED ISSUE #18362: Add regex flags to pattern-replace character filter
In the `pattern` tokenizer, we allow setting regex flags via the `flags` parameter.  The same support should be added to the `pattern_replace` character filter.

### PR DESCRIPTION
**Pull request by gfyoung**
Title is self-explanatory.  Closes #18362 .

This is my first PR for the repository, so all comments and critiques are welcome!

### CODE REVIEW

**Comment by gfyoung** [comment]
Tangentially related to this PR, but I had a hard time running individual test suites.  After reading the TESTING doc, I tried the following:
~~~
gradle test "-Dtests.class=*.CharFilterTests"
gradle test -Dtests.class=org.elasticsearch.index.analysis.CharFilterTests

gradle test "-Dtests.class=*.CharFilterTests" "-Dtests.method=testPatternReplaceCharFilter*"
gradle test -Dtests.class=org.elasticsearch.index.analysis.CharFilterTests -Dtests.method=testPatternReplaceCharFilter
~~~
However, all of these failed, with `gradle` complaining that there were no tests run.  What did I do wrong here with these commands?

**Comment by rjernst** [comment]
> However, all of these failed, with gradle complaining that there were no tests run. What did I do wrong here with these commands?

You need to `cd` into the directory of the project the tests are in (in this case, `core/`). If you look carefully at the failure, i would imagine it fails in a different subproject.

**Comment by gfyoung** [comment]
Ah, I see.  Now it works!  Thanks @rjernst !

**Comment by nik9000** [comment]
I think rather than exposing flags you should allow for a couple of booleans:
```
"char_filter": {
  "test": {
    "type": "pattern_replace",
    "pattern": "a*a",
    "replacement": "a",
    "case_sensitive": false,
    "comments": true,
    "multiline": true,
    "dotall": true,
    ...
  }
}
```

My reasoning is that what you have works fine for java but is impossible outside of it. I'd prefer to *just* do it that way so we don't have multiple ways of doing it. I also this it is going to be easier to read the configuration. The way you have it you'll have to mentally AND the flags out of the number which is fine for a few folks but I can't do that with base 10 numbers.

Sorry that that makes it more complicated!

For what it's worth you should be able to run those tests inside Eclipse or IntelliJ if you like. So long as you followed the instructions in CONTRIBUTING.md. **should** work.

**Comment by jasontedor** [comment]
> You need to `cd` into the directory of the project the tests are in (in this case, `core/`).

You can also just run `gradle :core:test` with the additional flags you already had to just run the specific test. The difference is that `gradle test` runs the task `test` across all sub-projects but `gradle :core:test` limits it to just core.

**Comment by nik9000** [comment]
> gradle test runs the task test across all sub-projects

All sub-projects of the directory you are in. You can also do `cd modules; gradle reindex:check` and that'll run `:modules:reindex`'s `check`. Leading the project name with `:` (like `:core:test` instead of `core:test`) means "don't use my path to resolve tasks. Gradle's resolution rules are fun!

**Comment by jasontedor** [comment]
> All sub-projects of the directory you are in.

Sure, I meant from the root since that seems to be where the user was when they encountered their issue. This is an important clarification though, thanks for making it. 😄

**Comment by gfyoung** [comment]
@nik9000 : Okay, but if you read the original issue, this PR is helping to standardize the interface across character filter.  What you're suggesting is a much larger API change that would have to apply across all of the filters.  I would only give that more consideration if more people think that's a good idea.  Otherwise, I would leave it as is.

**Comment by jasontedor** [comment]
It's best to not force push over your commits once your PR has been opened!

**Comment by gfyoung** [comment]
@jasontedor : That's a practice I've carried over from previous work / open source contributions.  I generally rebase and re-run test suites before making such pushes.

**Comment by jasontedor** [comment]
> That's a practice I've carried over from previous work / open source contributions.

Force pushing over publicly visible code is generally something to be avoided. Incremental commits are easier on the reviewers. I'll add a note to our contributing guide about it.

> I generally rebase and re-run test suites before making such pushes.

It's better to push new commits. Rebasing can be replaced with merging which is generally not needed until the end of the review process unless you have to pick up some change from core or will see a merge conflict otherwise.

**Comment by nik9000** [comment]
> I would only give that more consideration if more people think that's a good idea.

Fair enough. I don't think we should keep going this way because flags parameters aren't readable without the constants.

**Comment by jasontedor** [comment]
> I don't think we should keep going this way because flags parameters aren't readable without the constants.

I agree, it's just leaking the Java API into our API.

**Comment by gfyoung** [comment]
Okay, so which way should this go then?  Leave the changes as they are so that we resolve the original issue?  Or attempt to do a rewrite of the API across the filters right now?

**Comment by clintongormley** [comment]
> I think rather than exposing flags you should allow for a couple of booleans:

@nik9000 we expose this as a string `flags` parameter in other regex-related APIs, eg see https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-pattern-analyzer.html

> Flags should be pipe-separated, eg "CASE_INSENSITIVE|COMMENTS". Check Java Pattern API for more details about flags options.

**Comment by gfyoung** [comment]
<b>@Everyone</b>: bump - any updates on this?

**Comment by rmuir** [comment]
> @nik9000 we expose this as a string flags parameter in other regex-related APIs, eg see https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-pattern-analyzer.html

Yes, but keep in mind when adding jdk-specific regex parameters that users complain about the java regex implementation and open bugs in elasticsearch/lucene about it (e.g. https://issues.apache.org/jira/browse/LUCENE-7256). These bugs will never get fixed:  there is nothing we can do about it: other than switching to a different regex impl, since those issues are jdk issues.

**Comment by gfyoung** [comment]
<b>@Everyone</b>: bump - any updates on this?

**Comment by clintongormley** [comment]
> I agree, it's just leaking the Java Pattern API into our API.

These flags are Java Pattern dependent.  Other regex engines (which we don't use today) will only support some of these flags, and may have others that they need adding.  My inclination is to stick with the current syntax used elsewhere until we have plans to change the regex engine or make it pluggable.

**Comment by gfyoung** [comment]
<b>@Everyone</b>: bump - any updates on this?  Would love to get feedback on how I help can get this merged.

**Comment by nik9000** [comment]
> @Everyone: bump - any updates on this? Would love to get feedback on how I can help get this merged.

Sorry! I think if you switched:
```java
+        pattern = Pattern.compile(sPattern, settings.getAsInt("flags", 0));
```
with something more like the way the PatternAnalyzerProvider does it that'd be good enough for me. Like:
```java
+        pattern = Regex.compile(sPattern, settings.get("flags"));
```

Then we can use the same string-based flags that we have for the pattern analyzer.

The problem with these being regex implementation specific is a problem, but we've already bound Elasticsearch to java's regex so I don't think this makes it any worse.

**Comment by gfyoung** [comment]
@nik9000 : changed it `Regex.compile` and modified test appropriately - everything still passes

**Comment by nik9000** [comment]
OK! Looks good to me! I'll pull it locally, check it one last time so I'm 100% sure I don't break the build, and then merge it!

**Comment by nik9000** [comment]
Merged, thanks @gfyoung! I've also pushed 09cc4c449aa16cbc0aa0cb14c3fac6c206f41382 with some docs for it.

**Pull request merged**
