### PR TITLE
update geoip databases to latest

### PR DESCRIPTION
**Pull request by talevy**
we've made an update to the ES hosted geoip databases, this reflects the latest version bump

### CODE REVIEW

**Comment by talevy** [comment]
jenkins, please test this

**Comment by talevy** [comment]
jenkins, please test this

**Comment by talevy** [comment]
jenkins, please test this

**Comment by talevy** [comment]
@martijnvg doesn't look like I did this right :(

**Comment by martijnvg** [comment]
@talevy Tests failed with: `com.maxmind.db.InvalidDatabaseException: The MaxMind DB file's search tree is corrupt: contains pointer larger than the database.` So it was able to retrieve the new version of the db files dependencies. Maybe we need to upgrade `geoip2` library too? I see we use 2.8.0, but 2.9.0 has already been released. Maybe 2.8.0 can't read the never db files.

**Comment by oschwald** [comment]
There have been no changes to the database specification since 2013. New databases, e.g., GeoLite2 ASN, have been released with new contents, but the underly format is static. This exception should only happen on an invalid/corrupt database.

**Comment by oschwald** [comment]
Looking at the `geolite2-databases-20170704.jar` file, it appears that the `.gz` files are actually `.tar.gz` files.

**Comment by talevy** [comment]
😄 thanks @oschwald

**Comment by talevy** [comment]
@martijnvg we need to streamline this geolite db publishing. Second go may have been wrong as well. There is no city information :(

**Comment by talevy** [comment]
closing in favor of https://github.com/elastic/elasticsearch/pull/27897

**Pull request closed without merging**
