### PR TITLE
Execute downsampling after allocate and migrate actions

### LINKED ISSUE #96734: [ILM] The downsample action runs before the allocate and migrate actions
### Elasticsearch Version

8.7+

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Darwin

### Problem Description

In the warm and cold phases the downsample action runs before allocate and migrate https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/TimeseriesLifecycleType.java#L69

This means that if I define a policy with hot and warm like so:
```
      "phases" : {
        "hot" : {
          "actions" : {
            "rollover" : {
              "max_primary_shard_size" : "50gb",
              "max_age" : "30d",
              "max_docs" : 2000000000
            }
          },
        "warm" : {
          "min_age" : "2d",
          "actions" : {
            "allocate" : {
              "number_of_replicas" : 0,
              "include" : { },
              "exclude" : { },
              "require" : { }
            },
            "downsample" : {
              "fixed_interval" : "10h"
            }
          }
        }
```

And index would start in hot, wait to meet the rollover condition, rollover, and then **while still in the hot tier** it will
run the downsample action. Note that **the source index** will still be in the hot tier whilst downsample runs. (the downsample index will also be in hot for reasons detailed here: https://github.com/elastic/elasticsearch/issues/96733)

After downsample is completed, the downsampled index will migrate to the warm tier.

Note that this essentially makes the downsample action definition in the ILM hot and warm phase identical from an execution perspective (there's no difference as to which tier downsample will run on).

Similarly in a deployment with hot/warm/cold tiers, if downsample is defined in the `cold` phase the operation will run on the **warm tier** (i.e. source index is in warm, runs downsample, when downsample is completed it migrates to cold - as it's defined to run before the `migrate` action in cold https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/TimeseriesLifecycleType.java#L79 )

This might be desired in which case we should document this behaviour as it's a bit surprising. But maybe downsample should run after the migrate action? 

### Steps to Reproduce

Run downsample with ILM and check the logs for the source index i.e notice the `downsample-*` index is created whilst the source index is in the tier prior to the tier where the downsample action is defined 
https://www.elastic.co/guide/en/elasticsearch/reference/current/downsampling-ilm.html

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by salvatore-campagna**
Here we change the order of actions executed for downsampling. We make sure
the ILM Allocate and Migrate actions take place before the ILM Downsample action.
This is done to make sure that the index is migrated first to the appropriate tier
before the downsample action is executed. This is useful especially to spare some
additional work that would normally happen on the hot tier (on the warm tier) when
downsampling is performed in the hot to warm (warm to cold) phase transition.

If for example the downsample action operation is done while transitioning from
hot to warm it means the hot tier is already doing different things including serving
query/aggregation requests for recent data, including data stored in indices waiting
for downsampling to complete.

Once downsampling is complete the hot tier will serve query/aggregation requests instead
of the hot tier. Also, the warm tier will run the actual downsampling task sparing the hot
tier from doing additional work. This would result in better workload balance/allocation
between the hot and warm tier.

Similar reasoning applies when downsampling happens while transitioning from warm to
cold tier.

Resolves #96734

### CODE REVIEW

**Review by andreidan — COMMENTED** [review]
Thanks for looking into this Salvatore.

I think the fix needs a bit more work unfortunately.

Namely, existing deployments out there might have indices in the `downsample` action when they stop the cluster to upgrade to, say, `8.10.0` (  a version that contains the fix you propose ). 
So they started executing `downsample` in `8.9.0` when `downsample` executed before the `migrate`action. They now upgraded to `8.10.0`, they're still in the `downsample` action but they receive the new order of actions (`downsample` after `migrate` now). This means that their `migrate` action (`allocate` and `SearchableSnapshot` in `cold`) will now not be executed anymore.

I don't think we've ever done such change before, but I believe we should at least issue a log message informing our users some of their actions will now not be executed.
e.g. upon upgrade, look in the cluster state at the ILM execution state, detect which indices are in the `downsample` action and potentially check their policies for the actions that would be skipped. Log the indices and actions. 

Maybe `IndexMetadataVerifier` is a good place do to such a verification?

**Comment by salvatore-campagna** [comment]
@andreidan I was thinking if checking the version and failing the whole downsampling action is a good idea.

I was thinking that we could add two more steps at the beginning and end of the downsample action or maybe at some other suitable intermediate place, and just fail the whole downsample action forcing the user to retry it in case the start version and end version do not match.

Does it sound reasonable? Would it be feasible?

**Comment by andreidan** [comment]
It seems it's quite different to identify the situation I described [here](https://github.com/elastic/elasticsearch/pull/97014#pullrequestreview-1498069442) 

Namely, the exact scenario we're after is an index being in the middle of executing the downsampling action in Elasticsearch version 1 (before this change). Elasticsearch is updated to version 2 (a version containing this actions re-ordering) and ILM resumes executing the downsample action. 

`IndexMetadataVerifier` and friends execute whenever the cluster state is loaded from disk. 
Also, taking the index creation version into account is not necessarily telling (an index can march into Elasticsearch version 2 without ever being managed by ILM).

It's very rare that we update the order of the actions (this is the first time). I wonder if we need to introduce the version of the phase order ILM is currently executing for a phase in the ILM execution state. 
This means we'll have to maintain multiple execution orders / phase whenever we want to make a change however, we'll gain the execution order determinism we're after for a phase.

E.g. the `LifecycleExecutionState` could have a new field - `phase_action_order_version: 1` (`1` would be our current version for, example, the warm phase). **We will get the most up to date version when transitioning to the next phase, but the current phase will stay on the version it started executing until it completes.**

`ORDERED_VALID_WARM_ACTIONS` ( https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/TimeseriesLifecycleType.java ) would chance to be a Map<Version, List<String>>  and will currently contain only one version. 

e.g.
```
enum ACTION_ORDER_VERSION {
        ONE,
        TWO // downsample executes after migrate
    }

    public static final Map<ACTION_ORDER_VERSION, List<String>> ORDERED_VERSIONED_VALID_WARM_ACTIONS = Map.of(
        ACTION_ORDER_VERSION.ONE,
        Stream.of(
            SetPriorityAction.NAME,
            UnfollowAction.NAME,
            ReadOnlyAction.NAME,
            DownsampleAction.NAME,
            AllocateAction.NAME,
            MigrateAction.NAME,
            ShrinkAction.NAME,
            ForceMergeAction.NAME
        ).filter(Objects::nonNull).toList(),
        ACTION_ORDER_VERSION.TWO,
        Stream.of(
            SetPriorityAction.NAME,
            UnfollowAction.NAME,
            ReadOnlyAction.NAME,
            AllocateAction.NAME,
            MigrateAction.NAME,
            DownsampleAction.NAME,
            ShrinkAction.NAME,
            ForceMergeAction.NAME
        ).filter(Objects::nonNull).toList()
    );
```

`LifecycleType#getOrderedPhases` and friends will have to know about this version. 

@dakrone what do you think?

**Comment by salvatore-campagna** [comment]
I think what we might need here is the ability to know if at some point the order of action and/or steps has changed "in the meanwhile". Wouldn't it be possible to at least be able to detect that?

If I understand how things work we take all ILM phases with all the actions and we use the `toSteps` method to determine the list of ordered steps to execute for a certain ILM policy. This means that `toSteps` before and after the change would return two different orderings. Comparing the two lists we could be able to at least detect that there was an ordering change...right?

**Comment by andreidan** [comment]
We discussed this yesterday and decided we should introduce a way of versioning the order of the actions like the proposed [here](https://github.com/elastic/elasticsearch/pull/97014#issuecomment-1620444902)

At implementation time, we should treat missing versioning in the index lifecycle state as version 1.

**Comment by andreidan** [comment]
@salvatore-campagna  > I think what we might need here is the ability to know if at some point the order of actions and/or steps has changed "in the meanwhile". Wouldn't it be possible to at least be able to detect that?

That's exactly right. This is what having the order of actions versioning in the ILM execution state will give us. Opening an issue for it now.

**Comment by andreidan** [comment]
This PR is blocked by https://github.com/elastic/elasticsearch/issues/97444

**Pull request closed without merging**
