### PR TITLE
[Test] Additional logging for RemoteClusterClientTests

### LINKED ISSUE #41745: [CI] RemoteClusterClientTests#testConnectAndExecuteRequest fails
On master: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=debian-9/369/console

Couldn't reproduce with:
```
./gradlew :server:test --tests "org.elasticsearch.transport.RemoteClusterClientTests.testConnectAndExecuteRequest" \
  -Dtests.seed=5BFCD458F15F6DA4 \
  -Dtests.security.manager=true \
  -Dtests.locale=tr \
  -Dtests.timezone=America/Atka \
  -Dcompiler.java=12 \
  -Druntime.java=11
```

```
java.lang.AssertionError
	at __randomizedtesting.SeedInfo.seed([5BFCD458F15F6DA4:248A7562ED2FB133]:0)
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.elasticsearch.transport.RemoteClusterClientTests.testConnectAndExecuteRequest(RemoteClusterClientTests.java:60)
```

### PR DESCRIPTION
**Pull request by cbuescher**
Use RemoteClusterConnectionTests#startTransport instead of
MockTransportService.createNewService to start the local node transport service.
This implicitely calls `newService.start()` and `newService.acceptIncomingRequests()`
but potentially doesn't run into the same kind of deadlock situation that we occasionally saw
on recent test runs.

Closes #41745

### CODE REVIEW

**Comment by cbuescher** [comment]
@original-brownbear would you mind taking a look at this since we already talked about the problem on the issue? If not let me know if I should ask somebody else to review. I'm not sure this fixed things but it looks like it should do the same as before, maybe the order of execution is somewhat safer than in the existing test.

**Comment by original-brownbear** [comment]
@cbuescher hmm, but the stacktrace we have suggests that the latch was never counted down?
Looking at the code here:
```
                service.start();
                service.acceptIncomingRequests();
                RemoteClusterService remoteClusterService = service.getRemoteClusterService();
                assertTrue(remoteClusterService.isRemoteNodeConnected("test", remoteNode));
```

this currently fails on the last line (the `assertTrue`). So `acceptIncomingRequests` was called for sure?
=> I'm not sure how this solves issue. Maybe instead add some `info` level logging before and after the explicit `service.acceptIncomingRequests();` in the existing code so we can see the timing of when that is called relative to the failure stack traces? (maybe we're hanging before that, that seems like a likely explanation?)

**Comment by original-brownbear** [comment]
I'm also wondering if this might be explained by some port collision, now resolved in https://github.com/elastic/elasticsearch/pull/43983 (I can't immediately see how, but I think if we added the suggested info level logging and waited for the next failure then we can rule out it was a port collision ... because the next failure shouldn't come)

**Comment by cbuescher** [comment]
> So `acceptIncomingRequests` was called for sure?

My guess was that this might happen after the test timeout though. But I will revert and add the logging you suggested to get more information on this question. If this doesn't fail again soon we can also maybe close and blame it on #43983? But I'll add the logging instead of the changes I made earlier.

**Comment by original-brownbear** [comment]
@cbuescher 

>  If this doesn't fail again soon we can also maybe close and blame it on #43983? But I'll add the logging instead of the changes I made earlier.

Thanks, I like that plan :)

**Review by original-brownbear — APPROVED** [review]
LGTM

**Comment by cbuescher** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample

**Comment by cbuescher** [comment]
@elasticmachine run  elasticsearch-ci/bwc

**Comment by cbuescher** [comment]
@elasticmachine update branch

**Pull request merged**
