### PR TITLE
Support of "starts with" when attaching REST handlers

### PR DESCRIPTION
**Pull request by templth**

### CODE REVIEW

**Comment by clintongormley** [comment]
@templth - I still can't find a signed CLA for you. Are you sure that you signed the personal CLA, with your github ID and the same email address?

**Comment by templth** [comment]
@clintongormley Really. I got a confirmation email from echosign... I just checked and both github id and email seem correct. Do you want me to send it by email?

**Comment by clintongormley** [comment]
@templth are you sure you signed the personal CLA? The corporate CLAs have to be checked manually unfortunately.  If it was a personal one, please send it to me so that we can figure out why it isn't working.

**Comment by templth** [comment]
@clintongormley I just sent you by email the CLA I signed...

**Comment by clintongormley** [comment]
Corporate CLA signed

**Comment by jpountz** [comment]
An issue I have with this pull request is that the change is not used in the core. Elasticsearch being already quite a large project, we regularly try to remove functionality that is unused to keep the total amount of complexity manageable. So I would lean towards not merging such a change unless it could help simplify the core...

**Pull request closed without merging**
