### PR TITLE
[Monitoring] Update monitoring template versions

### PR DESCRIPTION
**Pull request by axw**
Update monitoring template versions to 7.12.0, to ensure they are replaced on upgrade.

The "local" (default) monitoring exporter checks the version before replacing the template:

https://github.com/elastic/elasticsearch/blob/125655898ef3a4955a24d50aa352feda50b6b625/x-pack/plugin/monitoring/src/main/java/org/elasticsearch/xpack/monitoring/exporter/local/LocalExporter.java#L365-L377

I made a change to .monitoring_beats in https://github.com/elastic/elasticsearch/pull/65997, which landed in 7.11.0, but did not update the template version. On master, the "last updated version" is 7.0.0, and on 7.x it is 7.0.1. There have been several other template changes since 7.0.1. IIANM, with rolling upgrades, monitoring templates would not have been updated since 7.0.1.

### CODE REVIEW

**Comment by chrisronline** [comment]
cc @jakelandis Do we need to bump this version every time we make mapping changes?

**Comment by jakelandis** [comment]
>  Do we need to bump this version every time we make mapping changes?

@chrisronline - yes

@axw - if you are backporting this to 7.12, can you adjust the version here to 7.12 ?  It shouldn't make a technical difference, but I can imagine someone looking a support diagnostic and scratching their head why on 7.11 the mappings are not installed. Also maybe a comment in the code that source code was updated in 7.11 but not applied until 7.12 and link to this issue ?

**Comment by axw** [comment]
Thanks @jakelandis, I've updated the version as suggested.

**Comment by jakelandis** [comment]
@elasticmachine update branch 
(looks like the test failure has recently been fixed/muted)

**Review by jakelandis — APPROVED** [review]
LGTM.

**Comment by jakelandis** [comment]
@axw - lmk if you bump into any issues merging or backporting.

**Comment by axw** [comment]
Thanks @jakelandis! All done.

**Pull request merged**
