### PR TITLE
Better bytes skipping in FsBlobContainer

### PR DESCRIPTION
**Pull request by tlrx**
This pull request is addressing a `// NORELEASE` tag in `FsBlobContainer` where the `InputStream` opened by the `readBlob(String)` does not efficiently skip bytes under hood. 

This method uses the `Files.newInputStream(resolvedPath)` which uses the `Files.newByteChannel()` which returns a `SeekableByteChannel` instance that allows to efficiently skip bytes but sadly this channel is then wrapped using `Channels.newInputStream()` into a `ChannelInputStream` instance that delegates the `skip()` method execution to the default `InputStream` implementation which reads bytes. 

This pull request changes the implementation of the `readBlob(String, long, long)` to use a more effective manner to skip bytes and adds a test to verify that only the required number of bytes are read. It also swaps how the `buffered` and `limit` streams are combined so that the underlying stream is limited first and the buffered stream will not try to buffer more bytes than necessary.

### CODE REVIEW

**Comment by tlrx** [comment]
@elasticmachine update branch

**Comment by tlrx** [comment]
@elasticmachine update branch

**Review by DaveCTurner — APPROVED** [review]
LGTM. Taught me about a whole other layer of mocking that I didn't know about yet :)

**Comment by tlrx** [comment]
Thanks David

> Taught me about a whole other layer of mocking that I didn't know about yet :)

Like an onion: the more you peel it the more you cry :)

**Pull request merged**
