### PR TITLE
Multi term intervals: increase max_expansions

### PR DESCRIPTION
**Pull request by mayya-sharipova**
Currently multi term interval queries (prefix, wildcard, fuzzy, regexp and range) can 
expand maximum to 128 terms. To reach parity with span queries that we want to deprecate,
 set max expansions to indices.query.bool.max_clause_count which is used in span queries.

Relates to #110491

### CODE REVIEW

**Comment by benwtrent** [comment]
@mayya-sharipova I am trying to find the reason for the original limit. What was the reason for the 128? It seems very specific :/. Did we just pick the value at random?

**Comment by mayya-sharipova** [comment]
@benwtrent Thanks for checking.

>  I am trying to find the reason for the original limit. What was the reason for the 128? It seems very specific :/. Did we just pick the value at random?


The limit came as [default value](https://github.com/apache/lucene/blob/main/lucene/queries/src/java/org/apache/lucene/queries/intervals/Intervals.java#L64) from Lucene.  Lucene also has [warnings](https://github.com/apache/lucene/blob/main/lucene/queries/src/java/org/apache/lucene/queries/intervals/Intervals.java#L196): " Setting.. maxExpansions ..to higher than the default value of can be both slow and memory-intensive".

But outside of intervals, for our default multi-term queries we support different [rewrite params](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-multi-term-rewrite.html) , and allow to rewrite up to `indices.query.bool.max_clause_count`. So my mind, this change should be fine.

**Comment by benwtrent** [comment]
@mayya-sharipova Ah, it was the default value, not the expressed limit in Lucene.

**Review by benwtrent — APPROVED** [review]

**Comment by mayya-sharipova** [comment]
@elasticsearchmachine update branch

**Comment by mayya-sharipova** [comment]
All tests pass, there is a failure in the test: 
REPRODUCE WITH: ./gradlew ":rest-api-spec:yamlRestCompatTest" --tests "org.elasticsearch.test.rest.ClientYamlTestSuiteIT" -Dtests.method="test {yaml=indices.create/21_synthetic_source_stored/index param - nested array within array}" -Dtests.seed=E0452F9AAC92C531 -Dtests.locale=es-Latn-ES -Dtests.timezone=America/Boise -Druntime.java=22
  but it is muted in main.

So I am going to merge in lcuene_snapshot branch this change.

**Pull request merged**
