### PR TITLE
Re-enable bwc after backport of #59317

### PR DESCRIPTION
**Pull request by andreidan**
Reenables bwc after the backport of #59317

### CODE REVIEW

**Comment by andreidan** [comment]
@elasticmachine update branch

**Comment by andreidan** [comment]
@elasticmachine update branch

**Comment by danhermann** [comment]
@elasticmachine update branch

**Comment by danhermann** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample-windows

**Comment by danhermann** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample-windows

**Pull request merged**
