### PR TITLE
Add allow_overlaps parameter to all_of interval producer

### PR DESCRIPTION
**Pull request by romseygeek**
By default, unordered intervals produced by an `all_of` interval rule will 
match even if their sub-intervals are overlapping; for example, the interval
`UNORDERED(ORDERED(take, sea), ORDERED(arms, troubles))` will match
the phrase `take up arms against a sea of troubles`.  In some cases, this
is not wanted.  This commit adds an `allow_overlaps` parameter to the 
`all_of` interval producer that defaults to `true`, and will prevent the above
example matching if set to `false`.

### CODE REVIEW

**Review by jimczi — COMMENTED** [review]
What is the difference with `not_overlapping` ? Is it just a shortcut of the existing rule ?

**Comment by romseygeek** [comment]
The difference is in the intervals returned when applying them.  `all_of` returns an interval spanning all of its subsources, so for the example above you'd get `[0, 8]` as the interval returned.  `not_overlapping` is a filter, so it returns intervals from its main source, not from the filter - searching for `"take up arms"` not overlapping with `"sea of troubles"` would return `[0, 2]`

**Comment by jimczi** [comment]
Should we close this PR @romseygeek ?

**Comment by romseygeek** [comment]
I think it's a useful addition to `intervals`, but there doesn't seem to be any clamour for it.  I'll close, and we can always revisit if it's needed.

**Pull request closed without merging**
