### PR TITLE
Add explicit build flag for experimenting with test execution cacheability

### PR DESCRIPTION
**Pull request by mark-vieira**
This PR addresses the fact that no test execution in our builds will ever be cached due to the implicit variability in test inputs due to our use of randomized tests. There has been extensive discussion about to what degree we want to still leverage random testing, but for the purposes of ongoing experimentation in build cacheability, we simply want to see what the _potential_ gains are here. For that we introduce and explicit build flag (`-Dignore.tests.seed`) that when added to the build will instruct Gradle to ignore the random test seed as a task input. Essentially, if the same code has already been tested with _any_ seed, go ahead and skip the tests. We'll explicitly configure this for our build cache Jenkins build to measure performance benefit.

### CODE REVIEW

**Review by rjernst — APPROVED** [review]
Lgtm

**Comment by atorok** [comment]
@mark-vieira in stead of introducing more configuration to the build, I think you could have fixed the seed in your testing to whatever random value you want.  Also we disable caching explicitly in rest tasks regardless of the seed.

**Comment by mark-vieira** [comment]
Indeed, that would be one way to go about it and probably would have been simpler for this case in hindsight.

We won't want to do that as the final solution however so some kind of config like this will eventually be necessary. Although it'll likely look a bit different.

**Comment by atorok** [comment]
backproted to [7.x](ba81b31b4c8)

**Comment by mark-vieira** [comment]
> backpacked to 7.x

Did I _really_ never backport this to `7.x`? 🤦‍♂

**Pull request merged**
