### PR TITLE
Rename some Docker projects for consistency

### PR DESCRIPTION
**Pull request by pugnascotia**
Apply the `:distribution:archives` naming convention to some of the Docker
sub-projects, so that we have a more consistent naming scheme.

This came from a [suggestion](https://github.com/elastic/elasticsearch/pull/55073#discussion_r407661912) in #55073.

### CODE REVIEW

**Review by mark-vieira — COMMENTED** [review]
Shouldn't this include changes to `settings.gradle`?

**Comment by pugnascotia** [comment]
These projects aren't currently listed in `settings.gradle`. I'm adding them in #55073.

**Review by mark-vieira — APPROVED** [review]
👍

**Comment by pugnascotia** [comment]
Backports:

`7.x` - 18dc2f73300
`7.7` - ef32dc09748

**Pull request merged**
