### PR TITLE
Mute S3 testRepositoryAnalysis

### PR DESCRIPTION
**Pull request by kingherc**
Relates #96162

### CODE REVIEW

**Comment by kingherc** [comment]
@elasticmachine test this please

**Comment by kingherc** [comment]
@pxsalehi thanks, just saw it as well in time and removed the auto-merge label. Will close it then.

**Comment by DaveCTurner** [comment]
Muting is faster and it's easy enough to unmute in the fixing PR, so I'd generally prefer to mute in cases like this.

**Comment by kingherc** [comment]
@DaveCTurner , sure, then I can re-open this PR and merge it.

**Pull request merged**
