### PR TITLE
Rename classes with the same name and package that cause JarHell

### PR DESCRIPTION
**Pull request by matriv**

### CODE REVIEW

**Comment by dadoonet** [comment]
Thanks @matriv.

Do you see JarHell when starting elasticsearch with both plugins? 

Note that #22599 will remove signers at some point.

**Comment by matriv** [comment]
@dadoonet Yep I see it when I start elasticsearch and loading both plugins with the same classloader. The thought is that anyway it's not nice to have classes in separate plugins with the same exact name and path (package).

**Comment by dadoonet** [comment]
Do you mean that you are running elasticsearch embedded somehow?

**Comment by matriv** [comment]
We use elasticsearch as a framework for our product CrateDB and we load these 2 plugins (`discovery-ec2` and `repository-s3`) with the same classloader.

**Comment by s1monw** [comment]
> We use elasticsearch as a framework for our product CrateDB and we load these 2 plugins (discovery-ec2 and repository-s3) with the same classloader.

this is not how these classes are designed to work. They have to have classloader isolation to be used with elasticsearch and JarHell.

**Pull request closed without merging**
