### PR TITLE
Allow custom geo ip database files to be downloaded

### PR DESCRIPTION
**Pull request by jbaiera**
When operating a custom endpoint for geo ip database downloads, a user may be serving a custom database file from that endpoint. This is a bit of an unintended feature of the download service, but it allows users to manage their licensed Maxmind databases in one location for an entire organization. The problem with this kind of deployment is that we only download geo ip databases if a geo ip processor exists in the cluster, and the code currently forbids creating a geo ip processor that uses a non-standard geo ip database name without that database already existing on the node.

This PR addresses this cyclical dependency by extending the assumptions we make about database file eventual availability to all database file names instead of the default ones we host at Elastic. Now, when creating a geo ip processor with a database name that is not recognized we unilaterally convert the processor to one that tags documents with a missing database message until the database file requested is downloaded or provided via the manual configuration route. This allows a pipeline to be created and for the download service to be started, potentially sourcing the needed files. If the files cannot be sourced (because of a typo in the database name or other availability problem), the processor will continue tagging documents with a warning until one is provided or the processor is updated.

### CODE REVIEW

**Comment by jbaiera** [comment]
Relates #96362

**Comment by masseyke** [comment]
Our docs say
```
You can also use custom city, country, and ASN .mmdb files. These files must be uncompressed and use the respective -City.mmdb, -Country.mmdb, or -ASN.mmdb extensions.
```
I think we ought to change that 2nd sentence, maybe to something like
```
These files must be uncompressed. The type (city, country, or ASN) will be pulled from the file metadata, so the filename does not matter.
```

**Comment by jbaiera** [comment]
@elasticmachine updated branch

**Review by masseyke — APPROVED** [review]
LGTM

**Comment by jbaiera** [comment]
@elasticmachine update branch

**Comment by jbaiera** [comment]
@elasticmachine run tests

**Pull request merged**
