### PR TITLE
Build: Move gradle wrapper jar to a dot dir

### PR DESCRIPTION
**Pull request by rjernst**
This commit moves the gradle wrapper jar file to a hidden directory, so
that it does not clutter the top level names seen when doing an ls in
the project. The actual jar file is never manually edited, and only
changed by running `./gradlew wrapper ...` so it is not important for
this directory to be "visible".

### CODE REVIEW

**Review by nik9000 — APPROVED** [review]
Fine by me.

**Review by jasontedor — CHANGES_REQUESTED** [review]
This does not appear to work. I checked out your PR, I execute

```
$ ./gradlew wrapper --gradle-version=4.6
```

I end up with:

```
16:52:32 [jason:~/src/elastic/elasticsearch] pr/30146(+0/-0)+ ± cat .gradle-wrapper/gradle-wrapper.properties 
distributionSha256Sum=9af7345c199f1731c187c96d3fe3d31f5405192a42046bafa71d846c3d9adacb
```

Also:

```
16:53:03 [jason:~/src/elastic/elasticsearch] pr/30146(+0/-0)+ ± git diff --cached
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
modified: .gradle-wrapper/gradle-wrapper.properties
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
@ gradle-wrapper.properties:1 @
distributionUrl=https\://services.gradle.org/distributions/gradle-4.7-all.zip
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStorePath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
distributionSha256Sum=203f4537da8b8075e38c036a6d14cb71b1149de5bf0a8f6db32ac2833a1d1294
distributionSha256Sum=9af7345c199f1731c187c96d3fe3d31f5405192a42046bafa71d846c3d9adacb
```

 I am also concerned about the fact that you had to manually edit the wrapper scripts. I would prefer those to come along with the Gradle wrapper task execution and it appears it does not.

This feels like a hack to me. I would prefer that this be managed upstream and we benefit from it.

**Comment by rjernst** [comment]
> I am also concerned about the fact that you had to manually edit the wrapper scripts.

I did not edit the wrapper scripts. I ran the gradle wrapper task. The diff you see was a side effect of broken runs as I changed things, and ended up doing a git mv of the properties file. I've done the regex again and updated here.

**Comment by rjernst** [comment]
Hrm, I do get an error now a second time running the wrapper task. I will look into this more.

**Comment by jasontedor** [comment]
I am confused, this is still broken.

**Comment by jasontedor** [comment]
Okay, race condition on that last comment. Good luck.

**Comment by rjernst** [comment]
Ok this is all fixed with 20cc208. I was wiping out the properties file when putting in the checksum.

**Review by jasontedor — APPROVED** [review]
LGTM.

**Pull request merged**
