### PR TITLE
Use ES_HOME environment variable on Windows

### PR DESCRIPTION
**Pull request by YoAm**

### CODE REVIEW

**Comment by YoAm** [comment]
I've signed the CLA just before submitting the pull request, perhaps it takes some time to update the status

**Review by cbuescher — COMMENTED** [review]
Hi @YoAm, sorry for the long delay in getting to this, the PR somehow managed to slip through the cracks. I think the change is good, since the documentation currently doesn't correctly point to the right bin directory, but I wonder whether the original documentation author used %PROGRAMFILES% on purpose since it is one of the standard windows directories that everybody knows, whereas %ES_HOME% is set by the installer I believe. I will ping the author to comment.

**Comment by russcam** [comment]
Thanks for opening @YoAm. As @cbuescher says, `%ES_HOME%` is set as part of the installation process, so although correct, it feels a little confusing to point folks at this in order to find out where Elasticsearch has been installed by default. At a minimum, the documentation could indicate that `%ES_HOME%` is set to point at the installation directory too.

The documentation does need to be updated to say that Elasticsearch will be installed to

 `%ProgramW6432%\Elastic\Elasticsearch{backslash}{version}` 

by default, which includes the version directory (`{param}` are substitutions in asciidoc that will be replaced by appropriate values). The cmd prompt and PowerShell commands should also be updated. 

Would you like to submit a PR for that change @YoAm?

**Comment by cbuescher** [comment]
@YoAm hi, checking back in to see if you are interested in making the change that @russcam suggested. Otherwise I think we can close this issue.

**Pull request closed without merging**
