### PR TITLE
[DOCS]Corrections for index-mgmt page.

### PR DESCRIPTION
**Pull request by amyjtechwriter**
Corrections to the [index management page](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-mgmt.html) in ES. An inline compass icon added to page, compass symbol changed to compass symbol, and an old image removed.

Closes: [#150](https://github.com/orgs/elastic/projects/1232/views/4?pane=issue&itemId=35556445)

### CODE REVIEW

**Review by abdonpijpelink — CHANGES_REQUESTED** [review]
Thanks for fixing this @amyjtechwriter ! 

I've left one suggestion to change another "symbol" into "icon".

**Review by abdonpijpelink — APPROVED** [review]
LGTM

**Comment by jrodewig** [comment]
@amyjtechwriter — It looks like you'll need to manually backport this PR. Please reach out to @szabosteve or I if you need help with that.

@szabosteve  Can you provide a post-merge review? @amyjtechwriter please incorporate any feedback into a follow-up PR/ Thanks!

**Review by szabosteve — COMMENTED** [review]
Latest changes LGTM! Please let me know if I can help with manual backporting.

**Pull request merged**
