### PR TITLE
only set `vm.max_map_count` if greater

### PR DESCRIPTION
**Pull request by majormoses**
This fixes some logic that was not quite right in #31285 it should only be changed if the value requested is greater than rather than and should not include equality on that.

Signed-off-by: Ben Abrams <me@benabrams.it>

### CODE REVIEW

**Review by jasontedor — APPROVED** [review]
So the issue here is that we want to avoid setting `vm.max_map_count` if it is already equal to the desired value (the bootstrap check requires 262144). The reason we want to avoid this is because in some use-cases using `sysctl` to set this will fail. In this case, we want to enable users to set this value externally and then allow that to cause using `sysctl` to set the value to be skipped so that cases where using `sysctl` will fail to no longer fail.

LGTM.

**Comment by jasontedor** [comment]
Sorry for the delay @majormoses, I was on vacation last week.

**Comment by jasontedor** [comment]
Thanks for the ping @jtibshirani.

**Comment by jasontedor** [comment]
@elasticmachine test this please

**Comment by jasontedor** [comment]
@elasticmachine test this please

**Comment by majormoses** [comment]
@jasontedor thanks and no worries, I am constantly being pulled off and on that project anyways.

**Comment by majormoses** [comment]
@jasontedor looks like CI passes, let me know if you need anything else from me.

**Comment by jasontedor** [comment]
@majormoses Thanks for the check. You're good here; I will merge this later. I am in the middle of some other tasks right now.

**Pull request merged**
