### PR TITLE
Move MinIO fixture in its own fixture project

### PR DESCRIPTION
**Pull request by tlrx**
This pull request moves the MinIO docker-compose fixture from the `:plugins:repository-s3` to its own `:test:minio-fixture` Gradle project.

The goal here is to make the fixture more easily reusable and also makes the `repository-s3` build Gradle file a bit more comprehensive.

### CODE REVIEW

**Review by original-brownbear — COMMENTED** [review]
I think this needs an @atorok review :) All I can point out is that there's some merge conflict in the build file.
Probably from changing the default parameters for the S3 endpoint (I think you did that in some other PR as well a few days back)

**Comment by tlrx** [comment]
@original-brownbear Just wanted you to be OK with moving this to a fixture :) And sorry for the conflicts, #48849 was merged 2 hours and I did not notice.

**Comment by original-brownbear** [comment]
@tlrx ah ok, thanks for checking -> I'm good with this if Alpar is :)

**Review by alpar-t — APPROVED** [review]
LGTM!

**Comment by tlrx** [comment]
@elasticmachine update branch

**Pull request merged**
