### PR TITLE
Use LTS version of Ubuntu in Dockerfiles

### PR DESCRIPTION
**Pull request by pugnascotia**
We have some Dockerfiles that reference Ubuntu 19.04, which is not an LTS
version and has now appears to have been retired from the Ubuntu repositories.
Switch to 18.04, which is the current long-term support version. This
also requires a switch from OpenJDK 12 to 11.

I didn't change `smb-fixture` as that would have requried changes to the code that the container runs.

### CODE REVIEW

**Comment by pugnascotia** [comment]
@elasticmachine update branch

**Review by jasontedor — APPROVED** [review]
LGTM.

**Review by mark-vieira — APPROVED** [review]
👍

**Comment by jasontedor** [comment]
I merged this because not having it was blocking my attempts test something in the GCS plugin.

**Comment by pugnascotia** [comment]
Thanks for merging and backporting @jasontedor 👍 🙏

**Pull request merged**
