### PR TITLE
Introduces validation to restrict API's to single namespace

### PR DESCRIPTION
**Pull request by Mpdreamz**
To be merged after #51981 lands

cc @elastic/es-clients

### CODE REVIEW

**Comment by Mpdreamz** [comment]
CI failure is on purpose: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-2/15466/testReport/junit/org.elasticsearch.smoketest/XDocsClientYamlTestSuiteIT/test__yaml_en_watcher_example_watches_example_watch_clusterstatus_line_193_/

Will rebase once:  #51981 lands

**Review by benwtrent — COMMENTED** [review]
I am not 100% sure about this. There might very well be good reason to have more than one namespace on the API designation (grouping of plugins, or an exceptionally large space being split up for easier discoverability).

**Comment by Mpdreamz** [comment]
Only 1 level deep namespace was a consensus amongst the clients, the java HLRC is also unlikely to support N level deep name-spacing. 

If the need arises to introduces more levels we can reconsider but having this guard in the interim puts me at ease.

Since these drive code generation we'll need to map out the impact of multiple namespaces should we want them in the future.

**Review by benwtrent — APPROVED** [review]

**Comment by Mpdreamz** [comment]
Thanks for the review @benwtrent 👍 rebased and taking it for another spin on CI before merging.

**Pull request merged**
