### PR TITLE
[ML] [Transform] use feature reset API for transform test cleanup

### PR DESCRIPTION
**Pull request by benwtrent**
This moves all transform cleanup logic to use the feature reset API.

### CODE REVIEW

**Comment by benwtrent** [comment]
run elasticsearch-ci/1
run elasticsearch-ci/2

**Comment by benwtrent** [comment]
run elasticsearch-ci/1
run elasticsearch-ci/2

**Comment by benwtrent** [comment]
run elasticsearch-ci/1
run elasticsearch-ci/2

**Review by droberts195 — APPROVED** [review]
LGTM

**Comment by benwtrent** [comment]
run elasticsearch-ci/1
run elasticsearch-ci/2

**Pull request merged**
