### PR TITLE
Fix Snapshot Delete Needlessly Failing on Concurrent Snapshot

### LINKED ISSUE #55702: [CI] SnapshotResiliencyTests.testConcurrentSnapshotCreateAndDeleteOther failure
This is a new failure since today but it failed 5 times on `master` branch:
* https://gradle-enterprise.elastic.co/s/uallgp4u7igny
* https://gradle-enterprise.elastic.co/s/3yyhml2iknfju
* https://gradle-enterprise.elastic.co/s/u6uzbd7dye5ta
* https://gradle-enterprise.elastic.co/s/ft5l4vg3plocc
* This one has no build scan but jenkins job is https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_RUNTIME_JAVA=zulu11,nodes=general-purpose/649/console

The error message is
```
Expected: an instance of org.elasticsearch.snapshots.ConcurrentSnapshotExecutionException
     but: null
```

> ./gradlew ':server:test' --tests "org.elasticsearch.snapshots.SnapshotResiliencyTests.testConcurrentSnapshotCreateAndDeleteOther" -Dtests.seed=754A50E41B92E9E5 -Dtests.security.manager=true -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dtests.locale=sv-SE -Dtests.timezone=America/Argentina/Cordoba -Dcompiler.java=14 -Druntime.java=11

I cannot reproduce locally.

Sample stacktrace
```
at __randomizedtesting.SeedInfo.seed([754A50E41B92E9E5:C96E97BB010E765E]:0)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at org.elasticsearch.snapshots.SnapshotResiliencyTests.lambda$testConcurrentSnapshotCreateAndDeleteOther$31(SnapshotResiliencyTests.java:541)
at org.elasticsearch.action.ActionListener$1.onFailure(ActionListener.java:71)
at org.elasticsearch.client.node.NodeClient.lambda$executeLocally$1(NodeClient.java:91)
at org.elasticsearch.tasks.TaskManager$1.onFailure(TaskManager.java:167)
at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$1.handleException(TransportMasterNodeAction.java:192)
at org.elasticsearch.transport.TransportService$6.handleException(TransportService.java:580)
at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1111)
at org.elasticsearch.test.transport.MockTransport.handleError(MockTransport.java:149)
at org.elasticsearch.test.transport.MockTransport.handleRemoteError(MockTransport.java:132)
at org.elasticsearch.test.disruption.DisruptableMockTransport$4$2.run(DisruptableMockTransport.java:227)
at org.elasticsearch.cluster.coordination.AbstractCoordinatorTestCase$1.run(AbstractCoordinatorTestCase.java:1234)
at org.elasticsearch.cluster.coordination.DeterministicTaskQueue.runTask(DeterministicTaskQueue.java:132)
at org.elasticsearch.cluster.coordination.DeterministicTaskQueue.runRandomTask(DeterministicTaskQueue.java:126)
at org.elasticsearch.cluster.coordination.DeterministicTaskQueue.runAllRunnableTasks(DeterministicTaskQueue.java:76)
at org.elasticsearch.snapshots.SnapshotResiliencyTests.testConcurrentSnapshotCreateAndDeleteOther(SnapshotResiliencyTests.java:559)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:566)
at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
at java.lang.Thread.run(Thread.java:834)
```

### PR DESCRIPTION
**Pull request by original-brownbear**
We do the delete in three steps here:

1. Get the repository data and find the snapshot ids to delete
2. Put the delete entry in the CS
3. Run the actual delete

The test `testConcurrentSnapshotCreateAndDeleteOther` was failing because
between `1.` and `2.` a full snapshot completed moving the repository generation
ahead by 1 which we chose to fail on because we expect the repository generation from
step `1.` to still be there in step `3.`.
In the past, using the repository generation from step `1.` made sense as a safety measure
because any rapid increase in repository generation could have spelled trouble on eventually
consistent blob stores. Nowadays, it's just needless to fail here though and we can simply
rely on the generation we read from the repository in step `3.` to avoid ever passing a
broken repository generation to the repository when deleting.

NOTE: This exception was always a possibility but became massively more likely due to
improved/faster snapshot finalization via #55276 so it only showed up now.

Closes #55702

### CODE REVIEW

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/2 (opened https://github.com/elastic/elasticsearch/issues/55707 for that failure)

**Comment by ywelsch** [comment]
I'm wondering if this won't create more/other problems. Assume for example two concurrent snapshot deletions, both computing the same set of deletes in step 1, and then one completes step 2 and step 3, and the other gets to step 2 and step 3, with the snapshot suddenly gone. AFAICS `writeUpdatedShardMetaDataAndComputeDeletes` will warn with `failed to read metadata for index`.

The problem here is that we resolve the snapshot IDs early based on the repo, but then, when we actually get to execute the delete on the repo, the set of snapshots might have changed, which is now not taken into account (previously we guaranteed a consistent set of states using the repo version). 

The snapshot path deals with this with the INIT / STARTED dance, rechecking that there is no duplicate snapshot in the repo.

**Comment by original-brownbear** [comment]
Thanks @ywelsch you're making a good point. I thought about it for a bit and I think there's no real point in adding a kind of INIT step to deletes. It's added complexity (in terms of cleaning up on master failover and whatnot) and doesn't really change/improve the user experience.

When creating snapshots I'd probably also like to not have it eventually (it really is just a remnant of the time when we used to write the metadata to the repo in this step at this point.

So I went with this:

If the repo generation concurrently moved, then we simply delete those snapshots that are still left from our delete but don't fail.
-> This gives us consistent behavior in  so far, that we can be sure that any snapshots in a delete-in-progress will be deleted or have been deleted already (except for the corner case of IO issues with the repo). It's strange if we have to start reasoning about broken delete entries IMO.
-> Does not require any changes in the state machine
-> (practically trivial point because both spots, that in the test failure and the one you're mentioning are effectively impossible timing wise) We fix another spot where the repository had to step in on a concurrent operation (which is always undesirable when we do all our concurrency handling in `SnapshotsService` otherwise).

I also added a test for the situation concurrent deletes situation you pointed out to make sure nothing weird happens there.

**Comment by original-brownbear** [comment]
On second thought, so sorry for the noise here. After thinking about this some more I think I found a much better solution that fixes this issue as well as the restore issue. => No point in going this step for now, I'll open a PR for the more general solution shortly.

**Pull request closed without merging**
