### PR TITLE
Updated ilm docs as per the issue

### PR DESCRIPTION
**Pull request by satyyam11**
This PR updates the Elasticsearch ILM tutorial for the newer screenshot and the primary shard update in the text.

### CODE REVIEW

**Comment by leemthompo** [comment]
@elasticmachine test this

**Comment by leemthompo** [comment]
run docs-build

**Comment by satyyam11** [comment]
hi can I do anything?

**Review by leemthompo — APPROVED** [review]
Thanks! This LGTM. @dakrone you happy with this?

**Comment by leemthompo** [comment]
@elasticmachine test this

**Comment by leemthompo** [comment]
run docs-build

**Comment by leemthompo** [comment]
@elasticmachine test this

**Review by dakrone — APPROVED** [review]
LGTM also, thanks!

**Comment by satyyam11** [comment]
Will it self merge or do I need to do something?
Also can I work on more issues?
I know Java and Springboot

**Comment by dakrone** [comment]
buildkite test this

**Comment by dakrone** [comment]
@elasticmachine update branch

**Comment by dakrone** [comment]
> Will it self merge or do I need to do something?

Don't worry about this, I'll take care of merging it.

> Also can I work on more issues? I know Java and Springboot

We don't use spring, but you're welcome to work on other issues!

**Comment by dakrone** [comment]
buildkite test this

**Pull request merged**
