### PR TITLE
[DOCS] Correct URL for searchable snapshot API specs

### PR DESCRIPTION
**Pull request by jrodewig**
The JSON specs for the following APIs link to docs pages that don't exist:

* Mount snapshot API
* Clear cache API
* Searchable snapshot statistics API

This can cause doc build errors for ES client docs, such as the Elasticsearch-JS client.

This updates those links so downstream clients have a valid link.

Link to related broken docs build: https://elasticsearch-ci.elastic.co/job/elastic+docs+master+build/14790/console

### CODE REVIEW

**Comment by tlrx** [comment]
@jrodewig Sorry about that. Can you also update clear_cache and stats that were added at the same time please?

**Comment by jrodewig** [comment]
No worries at all @tlrx. I've updated the clear_cache and stats specs with 1cdbfb22483. Thanks!

**Review by tlrx — APPROVED** [review]
LGTM, thanks for fixing this!

**Comment by jrodewig** [comment]
@elasticmachine update branch

**Comment by jrodewig** [comment]
@elasticmachine update branch

**Comment by jrodewig** [comment]
@elasticmachine update branch

**Pull request merged**
