### PR TITLE
[Connector API] Fix bug with filtering validation toXContent

### PR DESCRIPTION
**Pull request by jedrazb**
### Changes
- Fix bug with `toXContent` representation of FilteringValidation

### CODE REVIEW

**Review by timgrein — APPROVED** [review]

**Comment by jedrazb** [comment]
@elasticsearchmachine run 
elasticsearch-ci/8.14.0 / bwc-snapshots

**Comment by jedrazb** [comment]
@elasticsearchmachine run elasticsearch-ci/8.14.0 / bwc-snapshots

**Comment by jedrazb** [comment]
@elasticsearchmachine run elasticsearch-ci/bwc-snapshots

**Comment by DaveCTurner** [comment]
Note that the 8.12 branch is no longer maintained, no need to (or point in) backporting there. Also the next 8.13 release is 8.13.3. I adjusted the labels accordingly.

**Pull request merged**
