### PR TITLE
Fix and unmute testSetUpgradeMode_ExistingTaskGetsUnassigned

### PR DESCRIPTION
**Pull request by przemekwitek**
This PR wraps `GetDataFrameAnalyticsStatsAction` calls in `assertBusy` so that intermittent search failures do not affect test results.

More insights in the related GH issue linked below.

Relates https://github.com/elastic/elasticsearch/issues/55221

### CODE REVIEW

**Review by droberts195 — APPROVED** [review]
LGTM

**Comment by przemekwitek** [comment]
I've just noticed that `assertBusy` only hides `AssertionError`, not `ElasticsearchException`. So this PR as it is, may not fix the issue.

**Comment by przemekwitek** [comment]
run elasticsearch-ci/bwc

**Comment by przemekwitek** [comment]
> I've just noticed that `assertBusy` only hides `AssertionError`, not `ElasticsearchException`. So this PR as it is, may not fix the issue.

I've fixed that by catching `ElasticsearchException` and calling `Assert.fail` (which throws `AssertionError` making the `assertBusy` retry).

**Pull request merged**
