### PR TITLE
Relax compatibility constraints on sql cursor streams for all versions after 8.8.0

### LINKED ISSUE #93989: Refactor SQL uses of Version.transportVersion
SqlStreamInput/Output use TransportVersion from a read-in Version constant. We need to remove the useage of `transportVersion` field

### PR DESCRIPTION
**Pull request by thecoop**
Existing BwC compatibility constraints are maintained for previous versions, but we allow cross-transport-version deserialization for cursors created after 8.8.0.

No substantive changes to SQL are planned in the near future, so this allows us to close #93989 to make progress on TransportVersion changes.

### CODE REVIEW

**Comment by luigidellaquila** [comment]
Thank you very much @thecoop, this seems reasonable to me, but I'm checking it with the team to make sure that I'm not missing any details. I'll keep you updated

**Comment by thecoop** [comment]
Note that this change adds `transport_version` to the node info structure. As it's just informative, I think that's ok.

**Comment by thecoop** [comment]
I've separated out the node info change to #94669

**Review by luigidellaquila — APPROVED** [review]
LGTM.
Thanks for your patience @thecoop, the checks should be fine for now.

**Pull request merged**
