### PR TITLE
[8.4] [Doc] Correctly cite setup-passwords CLI for minimal security guide (#90579)

### PR DESCRIPTION
**Pull request by ywangd**
Backports the following commits to 8.4:
 - [Doc] Correctly cite setup-passwords CLI for minimal security guide (#90579)

### CODE REVIEW

**Comment by ywangd** [comment]
Failures are unrelated but reproducible. I raised https://github.com/elastic/elasticsearch/issues/90783

**Comment by lockewritesdocs** [comment]
@elasticmachine update branch

**Comment by lockewritesdocs** [comment]
@elasticmachine update branch

**Comment by ywangd** [comment]
@elasticmachine update branch

**Comment by lockewritesdocs** [comment]
@elasticmachine update branch

**Pull request merged**
