### PR TITLE
Support kNN vectors in disk usage action

### LINKED ISSUE #84801: Add support for vectors to the disk usage API
### Description

We now support storing KNN vectors as part of our indexed data.  These vectors should be included in the disk usage API.

### PR DESCRIPTION
**Pull request by jtibshirani**
This change adds support for kNN vector fields to the `_disk_usage` API. The
strategy:
* Iterate the vector values (using the same strategy as for doc values) to
estimate the vector data size
* Run some random vector searches to estimate the vector index size 

Co-authored-by: Yannick Welsch <yannick@welsch.lu>

Closes #84801

### CODE REVIEW

**Comment by jtibshirani** [comment]
I tested this tool on the `dense_vector` rally track, with 1 million dense vectors indexed across 2 shards. The size estimate was quite close to the actual size of the index files:

**disk usage action: 927MB**
`|                                           vectors vector total |                                              |    927.298       |     MB |`

**index files: 929MB**
```
275M	0/index/_8_lucene92HnswVectorsFormat_0.vec
96K	0/index/_8_lucene92HnswVectorsFormat_0.vem
189M	0/index/_8_lucene92HnswVectorsFormat_0.vex

275M	1/index/_6_lucene92HnswVectorsFormat_0.vec
96K	1/index/_6_lucene92HnswVectorsFormat_0.vem
190M	1/index/_6_lucene92HnswVectorsFormat_0.vex
```

**Review by dnhatn — APPROVED** [review]
LGTM. Thanks @jtibshirani.

**Comment by jtibshirani** [comment]
Thanks @dnhatn for the review! I plan to merge tomorrow (unless there are other comments) so that we're sure to make 8.4.

**Review by mayya-sharipova — APPROVED** [review]
@jtibshirani Thanks for making progress on this. LGTM as well!

**Pull request merged**
