### PR TITLE
Throw exception if setting isn't recognized

### LINKED ISSUE #25607: Updating an unrecognized setting should error out with that reason
When updating a bogus setting, the following error is returned:
```
curl -XPUT -H "Content-Type: application/json" localhost:9200/_cluster/settings -d '
{
 "transient": {
   "bogus": true
 }
}'
```

```
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"transient setting [bogus], not dynamically updateable"}],"type":"illegal_argument_exception","reason":"transient setting [bogus], not dynamically updateable"},"status":400}
```
This leads one to believe that this setting is recognized, but not updateable. Not only is this non-updateable, this is unrecognized and not supported.

### PR DESCRIPTION
**Pull request by alexshadow007**
Closes #25607

### CODE REVIEW

**Comment by s1monw** [comment]
@elasticmachine ok to test

**Comment by s1monw** [comment]
@alexshadow007 this looks good to me, can you please merge master into your branch such that we get a CI run for this?

**Comment by alexshadow007** [comment]
@s1monw Done

**Comment by s1monw** [comment]
thanks for the contribution @alexshadow007 much appreciated! I am backporting this to 6.1

**Pull request merged**
