### PR TITLE
Treat system indices with unexpected type as needing upgrade

### LINKED ISSUE #78456: [ML] Using a snapshot with ML job model snapshots in 7.x but created in 6.8 fails to update mappings to .ml-config
In a 6.8 installation I created a few ML jobs in order to trigger snapshots so I could test deprecations logs in 7.x. Upon starting ES with that es snapshot, I see it outputs quite a few info lines saying that mapping updates to `.ml-config` failed:

```
info [o.e.i.SystemIndexManager] [Ignacios-macbook.local] Put mapping request for [.ml-config] failed
     java.lang.IllegalArgumentException: Rejecting mapping update to [.ml-config] as the final mapping would have more than 1 type: [doc, _doc]
     	at org.elasticsearch.cluster.metadata.MetadataMappingService$PutMappingExecutor.applyRequest(MetadataMappingService.java:115) ~[elasticsearch-7.16.0-SNAPSHOT.jar:7.16.0-SNAPSHOT]
```

This is the snapshot I used: [6.8-data-snapshot.zip](https://github.com/elastic/elasticsearch/files/7252323/6.8-data-snapshot.zip)

### PR DESCRIPTION
**Pull request by droberts195**
The system indices code that updates index mappings fails if
a system index was originally created in 6.x and has a type
that's not "_doc".

This change treats such indices as requiring upgrade rather
than requiring a mappings update. The mappings update was
failing anyway, so this doesn't really change functionality,
it just removes log spam that was occurring on every cluster
state update until the index mappings were corrected by some
other code.

It is assumed that every system index that didn't have type
"_doc" in 6.x must have separate mappings update code or full
upgrade code outside of the system indices framework.
Certainly this is true for the ML indices that are affected
by this problem.

Fixes #78456

### CODE REVIEW

**Comment by droberts195** [comment]
This is a 7.x-only PR, because there's no chance that 8.x will need to interact with a 6.x index.

**Comment by droberts195** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by droberts195** [comment]
@elasticmachine update branch

**Comment by droberts195** [comment]
Some background to aid review:

The system index mappings update code is not sufficient for features that might write documents into their system indices in mixed version clusters while the master node is still on the older version but some of the nodes that are indexing documents are on the newer version. Therefore, in addition to the system indices mappings update code ML will check mappings are up-to-date before doing anything that could cause a document to be written into an ML system index. An example is: https://github.com/elastic/elasticsearch/blob/4ef3a58a46cc51abe0fb213d2502f21ad143fc58/x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/JobManager.java#L352-L353

This is why ML can tolerate the system indices mappings update code not working at all.  The same must be true for any other feature that uses a type other than `_doc` for its system indices in 6.x, otherwise we would have had bugs reported for this problem, as it would be far worse than just log spam.

This assertion in the existing ML rolling upgrade tests proves that this PR doesn't stop the ML index mapping update code outside of the system indices framework from running: https://github.com/elastic/elasticsearch/blob/393ab2d813b1fed8e6d69b3b4c4704fc3d93c422/x-pack/qa/rolling-upgrade/src/test/java/org/elasticsearch/upgrades/MlMappingsUpgradeIT.java#L180

**Review by AthenaEryma — APPROVED** [review]
Left one super minor comment on a comment, otherwise LGTM. Thanks for tracking this down and fixing it!

**Pull request merged**
