### PR TITLE
SNAPSHOT: Speed up HDFS Repository Writes

### PR DESCRIPTION
**Pull request by original-brownbear**
* There is no point in hsyncing after every individual write since there is only value in completely written blobs for restores, this is ensures by the `SYNC` flag already and there is no need for separately invoking `hsync` after individual writes

### CODE REVIEW

**Comment by original-brownbear** [comment]
Jenkins test this please

**Comment by original-brownbear** [comment]
Jenkins run gradle build tests 1 please

**Comment by original-brownbear** [comment]
Jenkins run gradle build tests 1 please

**Review by ywelsch — APPROVED** [review]
LGTM

**Comment by ywelsch** [comment]
Update description to say that the SYNC option already ensures that every block is synced when it is closed, and the extra syncing after each write is unnecessary as we are only interested in all-or-nothing semantics.

**Comment by original-brownbear** [comment]
Jenkins run gradle build tests 1 please

**Comment by original-brownbear** [comment]
Jenkins run gradle build tests 1 please

**Pull request merged**
