### PR TITLE
Fix CI error in DenseVectorFieldMapperTests

### LINKED ISSUE #102899: [CI] DenseVectorFieldMapperTests.testVectorSimilarity fails reproducibly
### CI Link

https://gradle-enterprise.elastic.co/s/tl3jqzmzqyktq

### Repro line

./gradlew ':server:test' --tests "org.elasticsearch.index.mapper.vectors.DenseVectorFieldMapperTests.testVectorSimilarity" -Dtests.seed=39343A357A78EC3 -Dtests.locale=zh-CN -Dtests.timezone=Africa/Maseru -Druntime.java=21

### Does it reproduce?

Yes

### Applicable branches

main

### Failure history

_No response_

### Failure excerpt

  2> java.lang.AssertionError: expected:<COSINE> but was:<DOT_PRODUCT>
        at __randomizedtesting.SeedInfo.seed([39343A357A78EC3:75EC84B47EC59CF]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at org.elasticsearch.index.mapper.vectors.DenseVectorFieldMapperTests.testVectorSimilarity(DenseVectorFieldMapperTests.java:776)

### PR DESCRIPTION
**Pull request by carlosdelest**
`randomVersionBetween` is inclusive in both ends - fixed test by fixing interval. This fixes https://github.com/elastic/elasticsearch/issues/102899, related to the change in https://github.com/elastic/elasticsearch/pull/99445.

Closes https://github.com/elastic/elasticsearch/issues/102899

### CODE REVIEW

**Comment by carlosdelest** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by carlosdelest** [comment]
@elasticmachine run elasticsearch-ci/docs

**Review by benwtrent — APPROVED** [review]
Good catch!

**Comment by carlosdelest** [comment]
@elasticmachine update branch

**Pull request merged**
