### PR TITLE
Use weighted random selection for shard allocation

### PR DESCRIPTION
**Pull request by Sartner**
Each of my elasticsearch data node has more than one disk.
When new shards are allocated, they always go to the disk with most free space. This behavior causes disk io overloaded.
Here the weighted random algorithm instead of original is implemented. 
The percentage of free space on every disk acts as the weight of the disk.
If no suitable disk can be found, it will use original algorithm to allocate one.

### CODE REVIEW

**Comment by karmi** [comment]
Hi @Sartner, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/elasticsearch/pull/26621.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by Sartner** [comment]
@karmi OK. It has been added now

**Comment by DaveCTurner** [comment]
Labelling this for discussion.

I'm not sure this really solves the problem it claims to, and the extra nondeterminism it introduces into the allocation process isn't ideal. I think we should work towards distributing shards according to a wider set of parameters than we currently do, including things like (a proxy for) their IO load.

**Comment by DaveCTurner** [comment]
@Sartner thanks for your contribution. We discussed this within the team and decided that this is not something we'd like to pursue right now. Since Elasticsearch makes most of its allocation decisions on a node-by-node basis, it's possible that you would get better-balanced behaviour by having one disk per Elasticsearch node, which could be achieved either by combining your disks together using LVM or RAID or similar, or else by running multiple nodes on each host.

**Pull request closed without merging**
