### PR TITLE
Removed AbstractComponent in remaining classes

### PR DESCRIPTION
**Pull request by jklancic**
Removed extending of AbstractComponent from remaining files classes.

Relates to [#34488](https://github.com/elastic/elasticsearch/issues/34488)

### CODE REVIEW

**Review by cbuescher — APPROVED** [review]
Hi @jklancic,

thanks for the PR, looks good to me as far as I can see, but maybe @nik9000 wants to confirm.
I will kick of the CI tests in the meantime so we can merge this after a full test run.

**Comment by cbuescher** [comment]
@elasticmachine test this please

**Comment by cbuescher** [comment]
@jklancic your branch needed a merge with master to run CI on the current version. I just pushed this merge to your branch, hope you don't mind.
@elasticmachine test this please

**Comment by jklancic** [comment]
thanks @cbuescher I just cloned the repo yesterday, so I thought it should be up-to-date. Thanks for resolving the issue. That might be the reason I had problems running `./gradew check` - but the test passed, when I ran `./gradlew test`.

**Comment by cbuescher** [comment]
> That might be the reason I had problems running `./gradew check` - but the test passed, when I ran `./gradlew test`

Probably, but not likely in this case. The errors I saw earlier were due to the 6.5 release that happened yesteraday and the following version bump.

**Review by nik9000 — APPROVED** [review]
LGTM2

**Pull request merged**
