### PR TITLE
[7.x] Reenable BWC tests for data streams

### PR DESCRIPTION
**Pull request by danhermann**
Relates to #53100 

Backport of #59483

### CODE REVIEW

**Comment by danhermann** [comment]
@elasticmachine update branch

**Comment by danhermann** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample-windows

**Comment by danhermann** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample-windows

**Comment by danhermann** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample-windows

**Comment by danhermann** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by danhermann** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample-windows

**Comment by danhermann** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample-windows

**Comment by tbrooks8** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample-windows

**Pull request merged**
