### PR TITLE
Remove support for yml and json config files

### LINKED ISSUE #19391: Cleanup Elasticsearch configuration files support
Today Elasticsearch can be configured via YAML, JSON, or properties files. The support for properties files is undocumented and should be immediately removed. The support for JSON files should be deprecated and removed in 6.0.0.
- [x] remove support for .properties #19398
- [ ] deprecate support for .json in 2.4.0
- [ ] remove support for .json in 5.0.0
- [ ] deprecate support .yml in 2.4.0
- [ ] fail hard if .yml exists in 5.0.0
- [ ] remove check for existence of .yml in 6.0.0

### PR DESCRIPTION
**Pull request by rjernst**
The elasticsearch config file has had many different extensions it
supports. In 5.5 these older extensions were deprecated, and this commit
enforces only `elasticsearch.yaml` is used. It also converts all docs
and tests to use `elasticsearch.yaml`.

closes #19391

### CODE REVIEW

**Comment by pickypg** [comment]
Did we ever deprecate that back in 2.4 like it originally listed? I'm assuming not since we continued to provide a default `elasticsearch.yml`.

It seems a bit drastic to do this after a single _unreleased_ minor version of deprecation. I have not seen very many non-`yml` variants out in the wild (and literally cannot remember seeing any `yaml` variants), so couldn't we remove all of the non-YAML ones in 6.0 and only remove `yml` support (versus `yaml`) in 7.0?

This removal of `yml` toward `yaml` should also happen across the stack, which should hopefully push for  deprecation in 6.x and removal in 7.0.

/cc @clintongormley

**Comment by rjernst** [comment]
> Did we ever deprecate that back in 2.4 like it originally listed? 

The plan then was to deprecate in 2.4 and remove in 5.0. We ran out of time, so this is now happening for 6.0.

> It seems a bit drastic to do this after a single unreleased minor version of deprecation.

This is something incredibly easy for someone to change, and anyone wanting to upgrade to 6.0 will have to go through 5.5+ anyways in order to get all deprecations (of which they will see this there). Letting users keep old stuff for longer doesn't make them any more motivated to fix the problem, and this one is incredibly easy for them to "fix" (just rename the file), and they have been able to rename to `elasticsearch.yaml` since sometime in 1.x.

> This removal of yml toward yaml should also happen across the stack

This was not a requirement when #19391 was created, so I don't see why it would be now. Other parts of the stack, to my knowledge, have not had multiple config file extensions to deal with (or the craziness we used to have with trying to _merge_ multiple config files).  I think it would be great for kibana, logstash, and beats to switch to the respective `.yaml` extension, but I don't think we need to do so in lock step.

**Comment by pickypg** [comment]
> The plan then was to deprecate in 2.4 and remove in 5.0. We ran out of time, so this is now happening for 6.0.

That does not change the idea that we're basing this on an unreleased minor version without any real transitional period. That hardly qualifies as a deprecation. I think we have been far too quickly deprecating / removing things for the sake of a few lines of code saved.

I completely agree that we should do away with _merging_ these files though; that was craziness. We should prefer `yaml` and allow `yml` and nothing else in 6.0. And then only allow `yaml` in 7.0.

> This is something incredibly easy for someone to change, and anyone wanting to upgrade to 6.0 will have to go through 5.5+ anyways in order to get all deprecations (of which they will see this there).

That's kind of true only if you assume that everyone will go through the rolling restart. I know that many are excited about the prospect of doing it, but not everyone will do it (even if they should). It's only kind of true because not everyone has mechanisms in place to rename files across their cluster, so renaming N `elasticsearch.yml` is going to be very error prone.

> Letting users keep old stuff for longer doesn't make them any more motivated to fix the problem, and this one is incredibly easy for them to "fix" (just rename the file)...

No, it doesn't, but if the user never actually has the opportunity to fix it because they go from -- say 5.4 -- to 6.2 via a full cluster restart, then they're going to be very surprised by this change. We know that not everyone reads the breaking changes documentation either; we can't save everyone and I'm not against this change, only the timing of it.

> Other parts of the stack, to my knowledge, have not had multiple config file extensions to deal with

No, they have not (at least I'm not aware of any stealth support either). But that doesn't change the fact that they _all_ use `yml` because of Elasticsearch. And that really started in 5.0.

**Comment by pickypg** [comment]
> We should prefer yaml and allow yml and nothing else in 6.0.

(My own comment) To clarify, I think we should fail on both, and just prefer the order of those.

**Comment by jasontedor** [comment]
> (My own comment) To clarify, I think we should fail on both, and just prefer the order of those.

We already fail on multiple config files, that's an abomination we got rid of in 2.0.0 (#13043).

**Comment by rjernst** [comment]
> That does not change the idea that we're basing this on an unreleased minor version without any real transitional period. That hardly qualifies as a deprecation. I think we have been far too quickly deprecating / removing things for the sake of a few lines of code saved.

It is not just "a few lines code saved". Removing legacy code also allows broader refactorings. And a deprecation is a deprecation. We can't start making arbitrary time lengths that a setting must be deprecated for or we can never remove anything. A major version is when we *can* make these changes, precisely because we added deprecation in the previous major, regardless of which minor that deprecation went into.

> That's kind of true only if you assume that everyone will go through the rolling restart
> if the user never actually has the opportunity to fix it because they go from -- say 5.4 -- to 6.2 via a full cluster restart

No, even when upgrading using a full cluster restart, we have recommended to first upgrade to the last minor, in order to find all deprecations so the major upgrade does not lead to surprises, like this (and many other settings and features which have been deprecated and removed).

> then they're going to be very surprised by this change

They will be surprised when the first node fails to start, see the clear error message, rename their file, and be able to continue. But it would be no different than if they were using a setting which was removed: the nodes would fail to start because of an unknown setting, they would see the clear error message, check the breaking changes, and decide what to do about their setting.

> not everyone has mechanisms in place to rename files across their cluster

This is not a reason to avoid making any breaking changes in our system. If there was a such a user (and I would contend there is not for any cluster larger than a couple nodes), they would have this problem with *any* breaking change, whether it be this config file name, or a setting that has been deprecated and removed.

**Comment by rjernst** [comment]
> We should prefer yaml and allow yml

By "prefer" I assume you mean change the default config filename. I at first tried to change the default filename in 5.5. However, that can't work without adding hacks to our packages, because the old config file would still be there, the new name will be installed, and then the user gets an error because both yml and yaml are specified. Thus, we can only change the default in a major version since changing the default will cause breakages for existing users and when we error on yml since yml and yaml cannot coexist.

**Comment by rjernst** [comment]
@elasticmachine retest this please

**Comment by dadoonet** [comment]
I'm pretty sure the answer is "no" but I prefer asking.
Would it be possible when we start the shell script or the JVM to first rename `elasticsearch.yml` to `elasticsearch.yaml` and make that way a smooth migration?

**Comment by rjernst** [comment]
> Would it be possible when we start the shell script or the JVM to first rename elasticsearch.yml to elasticsearch.yaml and make that way a smooth migration?

I don't think that is feasible, both because we shouldn't be modifying a users system (we make config dir readonly with SM because we should not writing there), as well as it could be problematic for users who have their config file setup by an automated tool such as puppet.

**Comment by dadoonet** [comment]
> we make config dir readonly with SM because we should not writing there

Yeah. That's why I proposed doing that in the script.

> it could be problematic for users who have their config file setup by an automated tool such as puppet

Ha right. That's true...

**Comment by clintongormley** [comment]
I agree with Ryan's approach here - if we're going to mandate a single file extension then now is as good a time to do it as any.

The bit I'm torn about is the change from `.yml` to `.yaml`. We have used `.yml` since the beginning, so changing to `.yaml` will affect everybody.  

The YAML project [says](http://www.yaml.org/faq.html) _"Please use `.yaml` where possible"_ but neither `.yaml` nor `.yml` are officially registered anywhere.  The [YAML spec](http://www.yaml.org/spec/1.2/spec.html) doesn't mention the file extension.  [Wikipedia](https://en.wikipedia.org/wiki/YAML) lists both as acceptable file extensions, and Google returns twice as many results for `.yml` as for `.yaml`.

I would say that `.yml` is a de facto accepted file extension at this point and would be inclined to standardise on that instead of on `.yaml`

**Comment by rjernst** [comment]
I don't actually care which one it is, only that there is only one. And that means througout the project, not just the default config file. If you want to keep `.yml` can we then change the rest specs to all use that extension as well?

**Comment by clintongormley** [comment]
>  If you want to keep .yml can we then change the rest specs to all use that extension as well?

Certainly!  Also, I've checked with the rest of the stack and the other projects all use `.yml`, so we'd be consistent.

**Comment by rjernst** [comment]
I opened #24663 to updated the deprecation in 5.5 (for .yaml now), #24664 to remove `.yaml` and `.json` support in 6.0, and #24659 to convert rest tests to `.yml`.

**Pull request closed without merging**
