### PR TITLE
Add common SystemD file for RPM/DEB package

### PR DESCRIPTION
**Pull request by tlrx**
Since SystemD is well documented and supported, we don't need to have different files for DEB/RPM packages.

Tested on OpenSUSE13, Fedora 21, Debian 8 and Ubuntu 15.04 beta2.

### CODE REVIEW

**Comment by tlrx** [comment]
@electrical Can you have a look please? thanks

**Comment by tlrx** [comment]
@spinscale Can you have a look please? thanks

**Comment by spinscale** [comment]
when installing on jessie, all the output is occuring in `journalctl` after starting, guess this is not the desired behaviour

```
May 04 06:55:59 debian-800-jessie elasticsearch[664]: [2015-05-04 06:55:59,721][INFO ][node                     ] [Mar-Vell] version[2.0.0-SNAPSHOT], pid[664], build[cf7785d/2015-05-04T06:45:19Z]
May 04 06:55:59 debian-800-jessie elasticsearch[664]: [2015-05-04 06:55:59,723][INFO ][node                     ] [Mar-Vell] initializing ...
May 04 06:55:59 debian-800-jessie elasticsearch[664]: [2015-05-04 06:55:59,729][INFO ][plugins                  ] [Mar-Vell] loaded [], sites []
May 04 06:55:59 debian-800-jessie elasticsearch[664]: [2015-05-04 06:55:59,800][INFO ][env                      ] [Mar-Vell] using [1] data paths, mounts [[/ (rootfs)]], net usable_space [7.1gb], net tota
May 04 06:56:03 debian-800-jessie elasticsearch[664]: [2015-05-04 06:56:03,336][INFO ][node                     ] [Mar-Vell] initialized
May 04 06:56:03 debian-800-jessie elasticsearch[664]: [2015-05-04 06:56:03,400][INFO ][node                     ] [Mar-Vell] starting ...
May 04 06:56:03 debian-800-jessie elasticsearch[664]: [2015-05-04 06:56:03,623][INFO ][transport                ] [Mar-Vell] bound_address {inet[/0:0:0:0:0:0:0:0:9300]}, publish_address {inet[/10.0.2.15:9
May 04 06:56:03 debian-800-jessie elasticsearch[664]: [2015-05-04 06:56:03,641][INFO ][discovery                ] [Mar-Vell] elasticsearch/5OCAmEJIR6C2ALHieIfc7A
May 04 06:56:07 debian-800-jessie elasticsearch[664]: [2015-05-04 06:56:07,423][INFO ][cluster.service          ] [Mar-Vell] new_master [Mar-Vell][5OCAmEJIR6C2ALHieIfc7A][debian-800-jessie][inet[/10.0.2.1
May 04 06:56:07 debian-800-jessie elasticsearch[664]: [2015-05-04 06:56:07,450][INFO ][http                     ] [Mar-Vell] bound_address {inet[/0:0:0:0:0:0:0:0:9200]}, publish_address {inet[/10.0.2.15:9
May 04 06:56:07 debian-800-jessie elasticsearch[664]: [2015-05-04 06:56:07,451][INFO ][node                     ] [Mar-Vell] started
May 04 06:56:07 debian-800-jessie elasticsearch[664]: [2015-05-04 06:56:07,476][INFO ][gateway                  ] [Mar-Vell] recovered [0] indices into cluster_state
May 04 06:57:30 debian-800-jessie elasticsearch[664]: [2015-05-04 06:57:30,514][INFO ][cluster.metadata         ] [Mar-Vell] [foo] creating index, cause [api], templates [], shards [5]/[1], mappings []
```

**Comment by spinscale** [comment]
we also should update docs at http://www.elastic.co/guide/en/elasticsearch/reference/current/setup-repositories.html#_apt - as we always call `update-rc.d` in the apt parapgraph

**Comment by tlrx** [comment]
@spinscale thanks for your review. I updated the code following your comments but I was forced to rebase because of #10986.

Having STDOUT in the journal did not choke me since I find this useful. But we already log everything in the log file so I agree with you, we can skip the journal log: I added option [StandardOutput](https://github.com/elastic/elasticsearch/pull/10725/files#diff-3a8b47152707cc3e2cf528afb30666b7R27) for that.

I also added option [StandardError](https://github.com/elastic/elasticsearch/pull/10725/files#diff-3a8b47152707cc3e2cf528afb30666b7R30) so that if startup failed it will be printed in journal.

I updated the documentation [here](https://github.com/elastic/elasticsearch/pull/10725/files#diff-bf8e9feb408d93bb0d85b3bba1f05ddfR54) and add a one line check in tests [here](https://github.com/elastic/elasticsearch/pull/10725/files#diff-36348e13fcc9bbcc47b1e9af995ad851R75) for #10986.

Tested on OpenSUSE13, Fedora 21, Debian 8 and Ubuntu 15.04 server.

Can you please have a look? I'd like to push this quickly and move forward on SysV init scripts. Thanks :)

**Comment by spinscale** [comment]
Tested on

* debian jessie: works
* ubuntu vivid/trusty: trusty has a perms startup issue, vivid looks fine with a minor thing, see below
* opensuse: works
* fedora 21: works

This is the `journalctl` output on vivid, fedora and opensuse, maybe we should change the name just to `Elasticsearch`?

```
May 22 14:46:33 vagrant-ubuntu-vivid-64 systemd[1]: Started Starts and stops a single elasticsearch instance on this system.
May 22 14:46:33 vagrant-ubuntu-vivid-64 systemd[1]: Starting Starts and stops a single elasticsearch instance on this system...
```

I get this on my ubuntu trusty system, did you change anything there? The process starts, but stops again with this message (added in the `-C` parameter to the `start-stop-daemon` in the init script revealed it)

```
ElasticsearchException[Failed to delete pid file /var/run/elasticsearch.pid]; nested: AccessDeniedException[/var/run/elasticsearch.pid];
	at org.elasticsearch.common.PidFile$1.run(PidFile.java:115)
Caused by: java.nio.file.AccessDeniedException: /var/run/elasticsearch.pid
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244)
	at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:108)
	at java.nio.file.Files.deleteIfExists(Files.java:1165)
	at org.elasticsearch.common.PidFile$1.run(PidFile.java:113)
```

**Comment by tlrx** [comment]
@spinscale thanks for your review!

> This is the journalctl output on vivid, fedora and opensuse, maybe we should change the name just to Elasticsearch?

Done.

> I get this on my ubuntu trusty system, did you change anything there?

No, but in the meanwhile the security manager has been enabled. I fixed few things in #10986 but I did not double check the init.d scripts... The Debian script was referring to `/var/run/elasticsearch.pid` whereas Redhat script was referring to `/var/run/elasticsearch/elasticsearch.pid`. I uniformized this in this pull request (see last commit).

**Comment by spinscale** [comment]
another test

```
# start-stop-daemon --start -C -b --user elasticsearch -c elasticsearch --pidfile /var/run/elasticsearch/elasticsearch.pid --exec /usr/share/elasticsearch/bin/elasticsearch -- -d -p /var/run/elasticsearch/elasticsearch.pid --default.config=/etc/elasticsearch/elasticsearch.yml --default.path.home=/usr/share/elasticsearch --default.path.logs=/var/log/elasticsearch --default.path.data=/var/lib/elasticsearch --default.path.conf=/etc/elasticsearch

Error: You must build the project with Maven or download a pre-built package
before you can run Elasticsearch. See 'Building from Source' in README.textile
or visit http://www.elasticsearch.org/download to get a pre-built package.
```

reason in `/usr/share/elasticsearch/bin/elasticsearch`:

```
IS_PACKAGED_VERSION='Elasticsearch core'
if [ "$IS_PACKAGED_VERSION" != "elasticsearch" ]; then
    cat >&2 << EOF
Error: You must build the project with Maven or download a pre-built package
before you can run Elasticsearch. See 'Building from Source' in README.textile
or visit http://www.elasticsearch.org/download to get a pre-built package.
EOF
    exit 1
fi
```

**Comment by tlrx** [comment]
@spinscale Yes, it has been introduced by commit 6051991 and should be fixed by #11348

**Comment by spinscale** [comment]
rebased against master and tested against older and latest ubuntu, both now start ES.
init.d based startup correctly now has the pid-file in `/var/run/elasticsearch/elasticsearch.pid`

Also nice sideeffect with systemd, one catches stdout/stderr and thus finds out, in case of badly configured heap

```
journalctl -f
-- Logs begin at Tue 2015-05-26 13:48:53 UTC. --
May 26 13:52:41 vagrant-ubuntu-vivid-64 systemd[1]: Started Elasticsearch.
May 26 13:52:41 vagrant-ubuntu-vivid-64 systemd[1]: Starting Elasticsearch...
May 26 13:52:41 vagrant-ubuntu-vivid-64 elasticsearch[1492]: Invalid initial heap size: -Xms2gb
May 26 13:52:41 vagrant-ubuntu-vivid-64 elasticsearch[1492]: Error: Could not create the Java Virtual Machine.
May 26 13:52:41 vagrant-ubuntu-vivid-64 elasticsearch[1492]: Error: A fatal exception has occurred. Program will exit.
May 26 13:52:41 vagrant-ubuntu-vivid-64 systemd[1]: elasticsearch.service: main process exited, code=exited, status=1/FAILURE
May 26 13:52:41 vagrant-ubuntu-vivid-64 systemd[1]: Unit elasticsearch.service entered failed state.
May 26 13:52:41 vagrant-ubuntu-vivid-64 systemd[1]: elasticsearch.service failed.
```

LGTM, thanks so much for taking this up!

**Pull request merged**
