### PR TITLE
Make `routing_nodes` an independent metric option in cluster state api

### LINKED ISSUE #10352: separate /_cluster/state routing_table into routing_table and routing_nodes
currently, specifying routing_table will return both routing_table and routing_nodes. Not sure if this was a thought decision, or something that started of this way and just lingered since then.

Anyway, for me would be awesome being able to control individually if I want routing_table or routing_nodes(or both). This is simply because depending on how many shards you have, the response starts to be pretty big(and being honest, the info given is also redundant, but grouped differently).

I imagine for backwards compatibility, routing_table should cover both values... but would be possible having routing_nodes as an independent metric? Say, extending this Enum here https://github.com/elastic/elasticsearch/blob/master/src/main/java/org/elasticsearch/cluster/ClusterState.java#L263 to include routing_nodes and accepting both routing_table and routing_nodes on the check here https://github.com/elastic/elasticsearch/blob/master/src/main/java/org/elasticsearch/cluster/ClusterState.java#L468 ??

If this is something you guys would be willing to take, I'd also be more than willing to attempt a PR at this.

### PR DESCRIPTION
**Pull request by lmenezes**
closes #10352

### CODE REVIEW

**Comment by javanna** [comment]
I like it @lmenezes , thanks! Makes sense to keep bw comp in 1.x and still return `routing_nodes` too when asking for `routing_table`, I would change that in master probably as a follow-up. @clintongormley want to double check?

**Comment by clintongormley** [comment]
+1 to this change, and yes i'd make it 2.0 only

**Comment by lmenezes** [comment]
@clintongormley great! but for 2.0 only you mean making routing_table routing_table only, right? the routing_nodes as an independent metric could go on 1.X, right? :)

**Comment by clintongormley** [comment]
@lmenezes thinking about it again... it's such an easy change for users to make in 1.6, that i'd be tempted to just go ahead and do it, ie make the change completely in 1.6.

**Comment by lmenezes** [comment]
@clintongormley perfect for me. just thought it could be useful to have a smooth transition, where you could upgrade your nodes and have old behaviour, and then adapt your code on a cluster that already has this change.

anyway, any of the alternatives work for me :)

**Comment by javanna** [comment]
Hi @lmenezes I gave a final look at this, I wonder if we should add the same options to the Java api as well. We would need to add a `routingNodes` flag to `ClusterStateRequest` and handle bw comp on the wire format using version checks. Thoughts?

**Comment by lmenezes** [comment]
@javanna makes sense. Will update the PR with this :)

**Comment by lmenezes** [comment]
@javanna so, just had time to look into this... Does it really make sense to separate that for the Java API? 

On the REST API, routing_nodes and routing_table are 2 completely different entities(even though both are rendered from the same data) and returning them or not might make difference(bytes sent through the wire, and the process of iterating the routing table to built the json representation for each of them).

On the Java API, the RoutingTable object has to be sent over the wire anyway, and the RoutingNodes is actually volatile and built on demand from the RoutingTable(https://github.com/elastic/elasticsearch/blob/master/src/main/java/org/elasticsearch/cluster/ClusterState.java#L134 and https://github.com/elastic/elasticsearch/blob/master/src/main/java/org/elasticsearch/cluster/ClusterState.java#L226-L232). 

So, unless I'm missing something, it would make no difference at all(except from offering the same options on both Java/REST API) being able to control that individually on the Java API, and likely also make it confusing since you cannot really offer RoutingNodes without offering RoutingTable.

Makes sense?

**Comment by javanna** [comment]
hey @lmenezes you are right, this makes perfect sense to me. The routing table is what gets serialized over the wire, routing nodes are built on demand when requested first based on the routing table. I will merge this as-is, thanks a lot for looking into this!

**Comment by lmenezes** [comment]
@javanna thank you for taking the time to merge this :+1:

**Comment by javanna** [comment]
Merged, thanks a lot @lmenezes !

**Pull request closed without merging**
