### PR TITLE
[Doc] missing field name in Upsert api

### PR DESCRIPTION
**Pull request by boliza**
missing filed `name` in Upsert api

### CODE REVIEW

**Comment by clintongormley** [comment]
@dadoonet could you review please

**Comment by dadoonet** [comment]
Thanks for the PR.

I don't think `name` field is missing here. It's an update request and we wanted to only update the `gender` field.

Closing but feel free to reopen if you think differently and explain why.

**Comment by boliza** [comment]
@dadoonet  I still confused. In update.asciidoc, after line 95
> If the document index/type/1 already exists, we will have after this operation a document like:

```
{
    "name"  : "Joe Dalton",
    "gender": "male"
}
```

**Comment by dadoonet** [comment]
What is meant here is the following.

Let say you have an existing document:

```js
{
     "name"  : "Joe Dalton"
}
```

If you apply the upsert call, it will become:

```json
{
    "name"  : "Joe Dalton",
    "gender": "male"
}
```

If the document does not exist, it will be created with the index request content and will be:

```json
{
    "name"  : "Joe Dalton",
    "gender": "male"
}
```

Makes sense?

**Comment by boliza** [comment]
But the example souce code is 

```java
IndexRequest indexRequest = new IndexRequest("index", "type", "1")
                .source(JsonXContent.contentBuilder()
                        .startObject()
                        .field("name", "Joe Smith")
                        .field("gender", "male")
                        .endObject());
UpdateRequest updateRequest = new UpdateRequest("index", "type", "1")
                .doc(JsonXContent.contentBuilder()
                        .startObject()
                        .field("gender", "male")
                        .endObject())
                .upsert(indexRequest);
client.update(updateRequest).get();
```

**Comment by dadoonet** [comment]
So we have an update part:

```java
JsonXContent.contentBuilder()
                        .startObject()
                        .field("gender", "male")
                        .endObject())
```

And an upsert request:

```java
JsonXContent.contentBuilder()
                        .startObject()
                        .field("name", "Joe Smith")
                        .field("gender", "male")
                        .endObject());
```

Does it seem wrong to you?

**Comment by boliza** [comment]
this will be correct if the upsert quest just update the `gender`

**Comment by boliza** [comment]
I have test this code ,this match the update.asciidoc says

```java
IndexRequest indexRequest = new IndexRequest("index", "type", "1")
                .source(JsonXContent.contentBuilder()
                        .startObject()
                        .field("name", "Joe Smith")
                        .field("gender", "male")
                        .endObject());
UpdateRequest updateRequest = new UpdateRequest("index", "type", "1")
                .doc(JsonXContent.contentBuilder()
                        .startObject()
                        .field("name", "Joe Dalton")
                        .field("gender", "male")
                        .endObject())
                .upsert(indexRequest);
client.update(updateRequest).get();
```

**Comment by dadoonet** [comment]
I think that the example I wrote is like:

```sh
curl -XPOST 'localhost:9200/test/type1/1/_update' -d '{
    "doc" : {
      "gender": "male"
    },
    "upsert" : {
      "name"  : "Joe Dalton",
      "gender": "male"
    }
}'
```

Which means to me that if doc `test/type/1` exists, then `gender` field will be merged. If not, the full doc with `gender` and `name` will be added.

Is this wrong?

**Comment by boliza** [comment]
in your comment is right,but update.asciidoc in master branch is 
qq 20151231234624

**Comment by dadoonet** [comment]
I'm probably blind but I don't see what is wrong... May be I need some rest...

**Comment by boliza** [comment]
In a other word. in [update.asciidoc](https://github.com/elastic/elasticsearch/blob/master/docs/java-api/docs/update.asciidoc).  the field `name` in request source is `Joe Smith`, but in document the field `name` has changed to `Joe Dalton`. it' dose't make sense.

**Comment by boliza** [comment]
By the way Happy new year

**Comment by dadoonet** [comment]
I see. So the document was existing first with a name as `Joe Dalton`. We added a `gender` to it.
If it does not exist, it's created with `Joe Smith` and a `gender`.

That what it means.

Happy new year as well.

**Pull request closed without merging**
