### PR TITLE
Make DateFieldMapper extensible

### PR DESCRIPTION
**Pull request by tsouza**
This change is a proposal for making DateFieldMapper extensible. I am proposing this change so it's possible to extend DateFieldMapper into another date type that automatically supports indexing and searching for date parts such as `day_of_week`, `week_of_year`, `year`, etc. The actual DateFieldMapper extension for supporting this feature is implemented in a plugin https://github.com/tsouza/elasticsearch-mapper-dateext [WIP].

The plugin can only possibly be implemented is the changes in this PR can be accepted.

### CODE REVIEW

**Review by jpountz — COMMENTED** [review]
Sorry but I would really like to avoid designing this field for extensibility. I'd rather like the plugin to fork this class.

**Comment by colings86** [comment]
I agree with @jpountz I think plugins should fork the date class rather than us allow it to be extended. Having the date mapper extensible will restrict how we are able to modify the class to improve it

**Comment by tsouza** [comment]
Thanks @jpountz and @colings86 for the review.

So what you are proposing here is that I fork the actual date class code (i.e. copy&paste?) into my plugin and workout it from there?

**Comment by jpountz** [comment]
Yes.

**Comment by tsouza** [comment]
I usually don't think that way, but it's fair enough :).

We can close this, thanks!

**Pull request closed without merging**
