### PR TITLE
Allow for debugging of rest test clusters during test execution

### LINKED ISSUE #48672: Allow debugging yml tests
yml tests are inconvenient to investigate and it would be great to add a possibility to debug them.
These often run on a cluster of nodes, so we could pick which node we want to debug? Or we could enable them all with debug mode (probably even better)
It might be even more useful if we could have another debugging process to the `yml class` as per https://github.com/elastic/elasticsearch/pull/48568 but not a must have.

relates https://github.com/elastic/elasticsearch/issues/47793

### PR DESCRIPTION
**Pull request by mark-vieira**
Add a `--debug-server-jvm` command line option to rest test tasks to allow for debugging the Elasticsearch server as well as tests.

Closes #48672

### CODE REVIEW

**Review by pugnascotia — APPROVED** [review]
Can we add something to `CONTRIBUTING.md` about how and when to use this?

**Comment by mark-vieira** [comment]
> Can we add something to CONTRIBUTING.md about how and when to use this?

Absolutely. I've added a section on debugging tests to `TESTING.asciidoc`.

**Review by pugnascotia — APPROVED** [review]

**Comment by justincr-elastic** [comment]
Does it make sense to add entries in /elasticsearch/.idea/runConfigurations/? Current:
- Debug_Elasticsearch.xml.

For example, I added four local configs. Do you think they might be reusable?.
- Debug_Elasticsearch_Attach_5005_Allow_parallel_run.xml
- Debug_Elasticsearch_Attach_5007_Allow_parallel_run.xml
- Debug_Elasticsearch_Listen_5005_Allow_parallel_run.xml
- Debug_Elasticsearch_Listen_5007_Allow_parallel_run.xml

**Comment by mark-vieira** [comment]
> Does it make sense to add entries in /elasticsearch/.idea/runConfigurations/? Current:

We provide the main one mainly as a template. I know folks like to declare their own for whatever reasons. I think _most_ of the time folks will only ever attach to single nodes.

**Pull request merged**
