### PR TITLE
Set forced_refresh to true when using stateless refresh work-around

### PR DESCRIPTION
**Pull request by pxsalehi**
While checking what would it take to rework the temporary `?refresh` support in https://github.com/elastic/elasticsearch/pull/93160, I realized some YAML tests are failing because we never set the [`forced_refresh` flag in the response](https://www.elastic.co/guide/en/elasticsearch/reference/8.6/docs-refresh.html#refresh_wait_for-force-refresh). This is a simple fix and essentially is similar to what is happening in [BulkShardResponse](https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/action/bulk/BulkShardResponse.java#L46). I think with this, the bulk response now correctly reflects what happened. It also unblocks a bunch of YAML tests for Stateless. Those that explicitly check for `is_false: forced_refresh`, when using `WAIT_UNTIL`, still fail.

### CODE REVIEW

**Comment by pxsalehi** [comment]
To be clear, I think this is just a missing piece from the first PR. At the time, I didn't know about it, and unfortunately there were no yaml tests to catch this.

**Comment by tlrx** [comment]
> unfortunately there were no yaml tests to catch this.

I'm working on enabling them 😓

**Comment by pxsalehi** [comment]
> I'm working on trying to enable some of them 😓

I know, I know! 😃  I just meant, that's why it slipped the tests back then! Also I thought it helps with your effort, and it's good to have as many enabled as possible.

**Review by tlrx — APPROVED** [review]
LGTM

**Comment by pxsalehi** [comment]
Thanks, Tanguy!

**Pull request merged**
