### PR TITLE
CCR: Rename follow-task parameters and stats

### LINKED ISSUE #34703: [CCR] Fetches/indexing/writes/reads/bulks in status fields vs readers in task params
The status reports for the following tasks often refer to fetches (`number_of_successful_fetches`,`number_of_failed_fetches`, `total_fetch_time_millis`,`fetch_exceptions`). We also have a similar term (which is identical in meaning) call reads (`number_of_concurrent_reads`). We also have the generic `operations_received` and `total_transferred_bytes` and `last_requested_seq_no`.

On the write sides we have `bulk` (`number_of_successful_bulk_operations`, `number_of_failed_bulk_operations`) and `writes` (`number_of_concurrent_writes`, `number_of_queued_writes` <-- note the different semantics here).

I think we should align our terminologies across the various places. I personally like the `read` versus `write` and `bulk` vs `ops`. Howabout:

- `number_of_succesful_bulk_reads` 
- `number_of_failed_bulk_reads`
- `total_bulk_read_time`
- `number_of_ongoing_bulk_reads` 
- `total_operations_read`
- `total_bytes_read`
- `last_requested_seq_no_for_reads`
- `number_of_successful_bulk_writes`
- `number_of_failed_bulk_writes`
- `number_of_ongoing_bulk_writes` 
- `number_of_queued_ops_to_write` (not too happy with this one)

/cc @jasontedor @martijnvg

### PR DESCRIPTION
**Pull request by dnhatn**
This commit renames the follow-task parameters and its stats.
Below is the list of the changes:

## Params
- remote_cluster (unchanged)
- leader_index (unchanged)
- max_batch_operation_count -> max_read_request_operation_count
- max_batch_size -> max_read_request_size
- max_write_request_operation_count (new)
- max_write_request_size (new)
- max_concurrent_read_batches -> max_outstanding_read_requests
- max_concurrent_write_batches -> max_outstanding_write_requests
- max_write_buffer_size (unchanged)
- max_write_buffer_count (unchanged)
- max_retry_delay (unchanged)
- poll_timeout -> read_poll_timeout

## Stats
- remote_cluster (unchanged)
- leader_index (unchanged)
- follower_index (unchanged)
- shard_id (unchanged)
- leader_global_checkpoint (unchanged)
- leader_max_seq_no (unchanged)
- follower_global_checkpoint (unchanged)
- follower_max_seq_no (unchanged)
- last_requested_seq_no (unchanged)
- number_of_concurrent_reads -> outstanding_read_requests
- number_of_concurrent_writes -> outstanding_write_requests
- buffer_size_in_bytes -> write_buffer_size_in_bytes (new)
- number_of_queued_writes -> write_buffer_operation_count
- mapping_version -> follower_mapping_version
- total_fetch_time_millis -> total_read_time_millis
- total_fetch_remote_time_millis -> total_read_remote_exec_time_millis
- number_of_successful_fetches -> successful_read_requests
- number_of_failed_fetches -> failed_read_requests
- operation_received -> operations_read
- total_transferred_bytes -> bytes_read
- total_index_time_millis -> total_write_time_millis [?]
- number_of_successful_bulk_operations -> successful_write_requests
- number_of_failed_bulk_operations -> failed_write_requests
- number_of_operations_indexed -> operations_written
- fetch_exception -> read_exceptions
- time_since_last_read_millis -> time_since_last_read_millis

Closes #34703 

/cc @dliappis and @chrisronline

### CODE REVIEW

**Comment by jasontedor** [comment]
@elasticmachine run gradle build tests

**Review by jasontedor — CHANGES_REQUESTED** [review]
The only one that differs from what we discussed is `total_index_time_millis` -> `total_write_time_millis`. I think we should keep `total_index_time_millis`. I don't want to block this PR on another discussion though so I am going to defer to @bleskes to make a decision in the morning. So let's do this:
 - if we want to change back to `total_index_time_millis`, @martijnvg please make the change in the morning, @bleskes dismiss my review and approve the PR, and @martijnvg let us get it merged and backported
 - if we want to keep `total_write_time_millis`, @bleskes dismiss my review and approve the PR, and @martijnvg let us get it merged and backported
 - after this, we need to remove the linked issue as a blocker from the relevant places

That is, this PR LGTM save this one issue.

Thank you @dnhatn for all the work here, this was a big change and it looks thorough to me. I really appreciate that you made all the code changes to align the variable names with the API names. 🙏

**Comment by dliappis** [comment]
Thanks for the heads up @dnhatn , this is immensely helpful for adjusting our benchmarking workflows.

**Comment by martijnvg** [comment]
build oss-distro-docs please

**Comment by martijnvg** [comment]
> The only one that differs from what we discussed is total_index_time_millis -> total_write_time_millis. I think we should keep total_index_time_millis

Personally I think that `total_write_time_millis` is more consistent with the other shard follow stats field names and I'm okay with keeping it.

**Comment by bleskes** [comment]
> Personally I think that total_write_time_millis is more consistent with the other shard follow stats field names and I'm okay with keeping it.

I'm of the same mind.

@martijnvg do you mind pulling it in and back porting?

@dnhatn all the things that Jason and more. thanks!

**Comment by martijnvg** [comment]
> do you mind pulling it in and back porting?

I will pull it in and backport.

**Comment by martijnvg** [comment]
Note that the docs build was successful:

```
08:17:09 BUILD SUCCESSFUL in 3m 32s
08:17:09 275 actionable tasks: 274 executed, 1 up-to-date
08:17:09 
08:17:09 Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
08:17:09 Use '--warning-mode all' to show the individual deprecation warnings.
08:17:09 See https://docs.gradle.org/4.10/userguide/command_line_interface.html#sec:command_line_warnings
08:17:10 runbld>>> <<<<<<<<<<<< SCRIPT EXECUTION END <<<<<<<<<<<<
08:17:10 runbld>>> DURATION: 216536ms
08:17:10 runbld>>> STDOUT: 544135 bytes
08:17:10 runbld>>> STDERR: 5155 bytes
08:17:10 runbld>>> WRAPPED PROCESS: FAILURE (1)
08:17:10 runbld>>> Searching for build metadata in /var/lib/jenkins/workspace/elastic+elasticsearch+pull-request+oss-distro-docs
08:17:12 runbld>>> Storing build metadata: 
08:17:12 runbld>>> Searching for junit test output files with the pattern: TEST-.*\.xml$ in: /var/lib/jenkins/workspace/elastic+elasticsearch+pull-request+oss-distro-docs
08:17:12 runbld>>> Found 4 test output files
08:17:13 runbld>>> Test output logs contained: Errors: 0 Failures: 0 Tests: 1309 Skipped: 159
08:17:13 runbld>>> FAILURES: 0
08:17:13 runbld>>> BUILD: https://c150076387b5421f9154dfbf536e5c60.us-west1.gcp.cloud.es.io:9243/build-1531848254847/t/20181025061331-1E1F8BEC
08:17:13 runbld>>> NO MAIL GENERATED
08:17:19 Build step 'Execute shell' marked build as failure
```

but runbld could not generate an email.

**Review by martijnvg — APPROVED** [review]
Thank you Nhat! 💯

**Comment by dnhatn** [comment]
Thanks everyone :)

**Comment by dliappis** [comment]
Many thanks @dnhatn for the description of the changes; one question:

I guess 

image
in [your description](https://github.com/elastic/elasticsearch/pull/34836#issue-225603799) actually refers to the change:

`max_batch_operation_count` -> `max_read_request_operation_count`

right?

**Comment by dnhatn** [comment]
@dliappis You're correct. I've updated the description.

**Pull request merged**
