### PR TITLE
Allow snapshot deletion concurrent to creation in another repository

### PR DESCRIPTION
**Pull request by jloomis**
Allow snapshot deletion to proceed if the in-progress snapshot is being
created in a different repository.

### CODE REVIEW

**Comment by jloomis** [comment]
Don't know how to clear the check; I signed the CLA after submitting the pull request.

**Comment by jloomis** [comment]
oh hey commenting made it rerun; nevermind:)

**Comment by clintongormley** [comment]
@ywelsch could you take a look at this please?

**Comment by jloomis** [comment]
ping

**Comment by ywelsch** [comment]
@jloomis Sorry for the delay. I'm hesitant on going forward with this PR. The snapshot infrastructure does not currently support any kind of concurrent operations. This PR would create an exception to this rule for this one specific case, possibly creating confusion for users. Introducing more concurrency on the snapshot level is something we have been discussing for some time now and has also been in the back of our minds (as you've probably noticed, the cluster state can hold multiple snapshot entries). We are actively working on improving our test infrastructure for snapshots in preparation for changes like this one. One such example is the work on task management which helps to test snapshot functionality in isolation from other parts of ES. Another one is the mocking of infrastucture so that we can better test our AWS / EC2 / ... plugins. Once we have the proper infrastructure in place, we will feel much safer adding functionality like the one suggested here. I’m going to close this PR for now but we will definitely revisit concurrent snapshot capabilities in the future. Thanks for sending the PR and sorry again for the delay.

**Pull request closed without merging**
