### PR TITLE
Don't re-parse mappings when updating index settings

### PR DESCRIPTION
**Pull request by romseygeek**
When updating index settings, we call `IndicesService.verifyIndexMetadata` with
the old and new index metadata to check that the update is permitted.  This method 
also verifies that the mappings can be built, which can be time-consuming, and is
unnecessary when we know that call is from a method that only updates index
settings, and has no effect on mappings.

This commit adds a boolean `checkMappings` to `verifyIndexMetadata`, which
controls whether or not the method should validate index mappings.  Verification run
when an index is opened will perform this check, but those run from settings update
tasks can skip it.

### CODE REVIEW

**Comment by romseygeek** [comment]
The failure in `GatewayIndexStateIT` suggests that we do in fact need to parse the mappings when we open an index, but we can still avoid it on index setting updates.

**Comment by romseygeek** [comment]
@elasticmachine run elasticsearch-ci/part-1

**Comment by romseygeek** [comment]
@elasticmachine update branch

**Review by original-brownbear — COMMENTED** [review]
The code change looks fine to me.

I wonder if this is completely safe though? We have some mappers that use settings. What if I set a broken value for a setting and the mappers stop building, isn't that a concern?

**Comment by romseygeek** [comment]
The settings that are used by mappers (analysis, ignore_malformed, coerce, etc) are all non-dynamic so can't be updated via this API.  However I can see that this may not apply to plugins or future mappers.  Maybe there's a way of asserting that any setting used by a mapper should be non-dynamic?

**Comment by original-brownbear** [comment]
> Maybe there's a way of asserting that any setting used by a mapper should be non-dynamic?

I guess we'd have to make mappers declare the settings they care about somehow for this to work. Would be nice though if we found a neat way to do it, then we could even statically assert this.

**Comment by stu-elastic** [comment]
This is pretty old, I'm going to close it.  Please reopen if still relevant.

**Pull request closed without merging**
