### PR TITLE
Add cache inference api for azure open ai

### PR DESCRIPTION
**Pull request by jasonroy7dct**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against main? Unless there is a good reason otherwise, we prefer pull requests against main and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by DaveCTurner** [comment]
Hi @jasonroy7dct and thanks for your interest in Elasticsearch! This PR does not meet the standards we expect of contributors as set out in the [contributing guidelines](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md), particularly the section on [getting a contribution accepted](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md#reviewing-and-accepting-your-contribution), so I'm going to close it.

**Comment by jasonroy7dct** [comment]
Hi @DaveCTurner ,

Thanks for letting me know. I would like to know how could I modify this pull request to meet the standards, since it seems fulfilling the standards.

Best,
Jason

**Comment by DaveCTurner** [comment]
Hi @jasonroy7dct. I don't believe you discussed this change first:

> Please discuss your change in a GitHub issue before spending much time on its implementation. We sometimes have to reject contributions that duplicate other efforts, take the wrong approach to solving a problem, or solve a problem which does not need solving. An up-front discussion often saves a good deal of wasted time in these cases.

Also this change includes no supporting tests, and includes changes that would make it fail the existing build too:

> Follow the guidelines listed above when preparing your changes. You should add tests that correspond with your changes, and your PR should pass affected test suites too. It makes it much easier to review if your code is formatted correctly and does not include unnecessary extra changes.

Finally, even a contribution which meets all the standards may just not be accepted because of the time-consuming nature of reviews:

> We really appreciate everyone who is interested in contributing to Elasticsearch and regret that we sometimes have to reject contributions even when they might appear to make genuine improvements to the system. Reviewing contributions can be a very time-consuming task, yet the team is small and our time is very limited. In some cases the time we would need to spend on reviews would outweigh the benefits of a change by preventing us from working on other more beneficial changes instead.

You've already used up significantly more than your fair share of our available review time in your other recent PRs:

- https://github.com/elastic/elasticsearch/pull/109129
- https://github.com/elastic/elasticsearch/pull/109133
- https://github.com/elastic/elasticsearch/pull/109262
- https://github.com/elastic/elasticsearch/pull/108877
- https://github.com/elastic/elasticsearch/pull/109499
- https://github.com/elastic/elasticsearch/pull/109498

Please be mindful of this in future.

**Comment by jasonroy7dct** [comment]
Hi @DaveCTurner ,

Thanks for clarifying what I need to do, and I also apologize for not following the guidelines I should have. I discussed the this change with issue https://github.com/elastic/elasticsearch/issues/106568, and plan to add supporting test later on this pull request. Would it be possible? Thanks!

Best,
Jason

**Comment by DaveCTurner** [comment]
Thanks for the link to the related issue, that is illuminating, although I'm not sure I'd call your comments there a discussion yet. Still, we wouldn't normally expect to spend a lot of time iterating on a PR like this, particularly for problems like missing tests and build failures that you can identify yourself (this is also covered in the contributing guidelines):

> We sometimes reject contributions if we find ourselves performing many review iterations without making enough progress. Some iteration is expected, particularly on technically complicated changes, and there's no fixed limit on the acceptable number of review cycles since it depends so much on the nature of the change. You can help to reduce the number of iterations by reviewing your contribution yourself or in your own team before asking us for a review.

To repeat: please be mindful of the very limited time available to the team to review external contributions, and of the relatively large amount of that time you've already used up with your earlier PRs. If you have a reasonably complete and substantive improvement PR ready, including tests, and have verified that it passes the existing build checks, then that would be welcome. If it's something related to performance then you should also expect to provide some supporting data showing the performance improvement. But please stop opening trivial, incomplete, and/or broken PRs.

**Pull request closed without merging**
