### PR TITLE
Add a basic deprecation warning that the JSON format is changing in v9

### PR DESCRIPTION
**Pull request by thecoop**
V9 has a different non-detailed errors format, modified by #90529

### CODE REVIEW

**Comment by DaveCTurner** [comment]
LGTM except this is a deprecation so it needs a changelog entry - I adjusted the labels but you'll need to tweak the changelog it just added.

**Comment by thecoop** [comment]
The deprecation will be added by #90529

**Comment by DaveCTurner** [comment]
The deprecation changelog needs to go into this PR so it gets backported to 8.x

**Comment by thecoop** [comment]
@elasticmachine update branch

**Review by mosche — APPROVED** [review]
> The deprecation changelog needs to go into this PR so it gets backported to 8.x

The deprecation changelog is in the manual backport PR, so that should be fine 👍 
Have you checked if the failed Serverless check is related, it looks possible. But that shouldn't block this PR.

https://gradle-enterprise.elastic.co/s/vrauj2k6yvf7m/tests/task/:qa:x-pack-rest-test:yamlRestTest/details/co.elastic.elasticsearch.qa.rest.ServerlessXpackRestIT/test%20%7Byaml%3Dprofiling%2F10_basic%2FTest%20flamegraph%20from%20profiling-events%7D?top-execution=1

**Comment by thecoop** [comment]
The serverless failure is an unrelated known issue

**Pull request merged**
