### PR TITLE
Restore MemoryPool Peak getters

### PR DESCRIPTION
**Pull request by mindw**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)? *YES*
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md)? *YES*
- If submitting code, have you built your formula locally prior to submission with `gradle check`? *YES*
- If submitting code, is your pull request against main? Unless there is a good reason otherwise, we prefer pull requests against main and will backport as needed. *YES*
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)? *N/A*
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md#contributing-as-part-of-a-class) for that. *NO*

Restore Stat getters removed in #87664 .

### CODE REVIEW

**Comment by grcevski** [comment]
Hi @mindw, can you please provide a bit more information on why do you want to bring back those two stat methods? They are not used in the Elasticsearch codebase.

**Comment by mindw** [comment]
> Hi @mindw, can you please provide a bit more information on why do you want to bring back those two stat methods? They are not used in the Elasticsearch codebase.

Hi @grcevski Tx for looking at this!. I use(d) it here: https://github.com/mindw/elasticsearch-prometheus-exporter/blob/c4c11f1e47ba64ccf0281a3a7fd56a87287bca6a/src/main/java/org/compuscene/metrics/prometheus/PrometheusMetricsCollector.java#L906 . The plugin exposes ES statistics as Prometheus metrics. Hopefully it answers the question?

**Comment by grcevski** [comment]
@elasticsearchmachine update branch

**Comment by grcevski** [comment]
Hi @mindw, the branch needs to be rebased with main. Can you please do that so we can get a clean test run?

**Comment by mindw** [comment]
> Hi @mindw, the branch needs to be rebased with main. Can you please do that so we can get a clean test run?

@grcevski done!

**Comment by grcevski** [comment]
@elasticsearchmachine test this please

**Comment by grcevski** [comment]
Hi @mindw, there are formatting errors it seems with the code. Can you please run `./gradlew precommit`, fix the issues with our spotless formatter and push an update?

```
    src/main/java/org/elasticsearch/monitor/jvm/JvmStats.java
        @@ -469,7 +469,7 @@
         
         ········public·ByteSizeValue·getPeakMax()·{
         ············return·new·ByteSizeValue(peakMax);
        -········}········
        +········}
         ····}
         
         ····public·static·class·Mem·implements·Writeable,·Iterable<MemoryPool>·{
Run './gradlew :server:spotlessApply' to fix these violations.
```

**Comment by ChrisHegarty** [comment]
I am not opposed to this change (since it's largely benign), but I would like to note that this should not be taken as an indication of support for these server internals - we reserve the right to change internals at will.

@mindw A question, clearly it's trivial to workaround these inaccessible JVM stats (by just not logging them), but is this the sole issue remaining to be solved before running atop 8.x, or just the tip of the iceberg? For one, I note the split package with `org.elasticsearch.action.admin.indices.stats`. I don't see how this will operate successfully in 8.3+ with the move to deploying server on the module path (as a Java module).

**Comment by grcevski** [comment]
@elasticsearchmachine test this please

**Comment by grcevski** [comment]
Upon some more thought, and echoing Chris's comment above, isn't it possible for the prometheus plugin to grab these values directly from the MemoryMXBean instead of relying on Elasticsearch code?

E.g:
```
MemoryUsage memUsage = memoryMXBean.getHeapMemoryUsage();
```

This way we wouldn't have to keep unused code around and we won't break the plugin in the future if this code changes.

**Comment by stu-elastic** [comment]
@mindw This is pretty old, I'm going to close it.  Please reopen if still relevant.

**Comment by mindw** [comment]
It's still relevant.

**Pull request closed without merging**
