### PR TITLE
Fix TransportFieldCapabilitiesAction Blocking Transport Thread

### PR DESCRIPTION
**Pull request by original-brownbear**
Running a request per index could take a very long time here if the request covers
a larger number of shards (especially when security is enabled).
Forking it to the management pool saves the transport thread from getting blocked.
Also, to make this request run quicker (again especially with security enabled)
I removed the redundant index-level request fan-out here as well to save one step
of redundant request handling and authorization (the shard level request is authorized
separately again anyway). In a follow-up to 8.x because of 7.x BwC issues, we can
refactor away the redundant  index-level fan out as well.

### CODE REVIEW

**Comment by original-brownbear** [comment]
@elasticmachine update branch

**Review by jimczi — APPROVED** [review]
LGTM, nice simplification.

**Comment by original-brownbear** [comment]
Thanks Jim!

**Comment by mattkime** [comment]
Any thoughts on how much this will help slow field_caps responses?

**Comment by original-brownbear** [comment]
@mattkime this won't be an order-of-magnitude improvement. I think best case this is a ~2x speedup and the real world will probably see less than 2x due to other noise.

**Pull request merged**
