### PR TITLE
Remove test support for FIPS with JDK 8

### PR DESCRIPTION
**Pull request by ywangd**
We now explicilty require JDK 11 and BC-FIPS for FIPS 140-2 mode. Both
periodic and PR CI jobs have been updated to only test for JDK 11 and
the latest JDK. As a result, the support for testing with JDK 8 is no
longer needed and this PR removes it.

Relates: #77736

### CODE REVIEW

**Comment by ywangd** [comment]
@elasticmachine run elasticsearch-ci/part-1-fips run elasticsearch-ci/part-2-fips

**Comment by ywangd** [comment]
@elasticmachine  run elasticsearch-ci/part-2-fips

**Comment by ywangd** [comment]
@elasticmachine run elasticsearch-ci/part-2-fips

**Comment by ywangd** [comment]
@mark-vieira FIPS jobs are not running for this PR even after I tried to manually trigger them. Could you please take a look? Thanks a lot!

**Comment by mark-vieira** [comment]
@elasticmachine run elasticsearch-ci/part-1-fips

**Comment by mark-vieira** [comment]
@elasticmachine run elasticsearch-ci/part-2-fips

**Comment by mark-vieira** [comment]
Triggered for me :shrug:

**Comment by ywangd** [comment]
@elasticmachine update branch

**Comment by ywangd** [comment]
@elasticmachine update branch

**Review by jkakavas — APPROVED** [review]
LGTM

**Pull request merged**
