### PR TITLE
Deserialising timezones with DateUtils

### LINKED ISSUE #38449: Deserialize timeZone with DateUtils in RangeQueryBuilder
as spotted in this review https://github.com/elastic/elasticsearch/pull/38415#discussion_r253927699
`DateUtil` should be used when serialising/deserializing timezones to allow deprecation logging

### PR DESCRIPTION
**Pull request by LeeTgk**
Using ``DateUtils.of`` method emits a deprecation message when a deprecated timezone was used.
This method was renamed to ``DateUtils.ZoneIdOf``, as the old PR for this issue had a comment suggesting doing it, since it's a method that does not return the containing class.
This method is also no longer normalising the timezone, to keep the timezone text consistent.

In addition, as advised in the old PR, i checked if EQL and Watcher uses of this method didn't depend on the normalized id.
EQL calls it with ``DateUtils.ZoneIdOf("Z");``, wich already gets the ZoneOffset, so it does not need to be normalized.
Watcher does looks like it can work with either type of timezone, but please correct me if i'm wrong so i can correct it.

This closes #38449 
The "old PR" mentioned #66883

Waiting for feedback 😟

### CODE REVIEW

**Comment by LeeTgk** [comment]
Sorry for the question, i already re-signed the CLA, does the status only updates per commit ?
If so, i'll wait some feedback to see if there are changes to be done.

**Comment by pgomulka** [comment]
@elasticmachine test this please

**Comment by pgomulka** [comment]
@elasticmachine update branch

**Comment by pgomulka** [comment]
@elasticmachine test this please

**Comment by pgomulka** [comment]
@LeeTgk thank you for the PR. can you please take a look at the test failures? you need to fix the formatting

**Comment by pgomulka** [comment]
closing due to inactivity

**Pull request closed without merging**
