### PR TITLE
Up required gradle version in contributing instructions

### PR DESCRIPTION
**Pull request by softwaredoug**
ES now requires gradle 4.3, change contributing.md to match

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by softwaredoug** [comment]
FTR my company (opensource connections, github org o19s) has signed the CLA

**Comment by DaveCTurner** [comment]
@elasticmachine please test this

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Comment by DaveCTurner** [comment]
`6.0` -> 7872aaa3321823c3cfbeeb8fc605a631461ecc09
`6.1` -> 1e53212741338570f23490bd15ecc44d8d1f1847
`6.x` -> 3b74b9ae48619ebe163187b9205c636daba7ec6f
`master` -> 507aac44248c7a8ed6c2795bbdce2242556fb70e

**Pull request merged**
