### PR TITLE
Packaging: Update marker used to allow ELASTIC_PASSWORD

### LINKED ISSUE #37240: Cannot set the elasticsearch bootstrap password in docker using environment variable.
**Elasticsearch version** (`bin/elasticsearch --version`):
7.0.0-alpha2

**Description of the problem including expected versus actual behavior**:
Setting the ELASTIC_PASSWORD environment variable should allow to configure the elasticsearch bootstrap password in docker :
https://www.elastic.co/guide/en/elasticsearch/reference/master/configuring-tls-docker.html#CO19-2

**Steps to reproduce**:
docker run --rm -p 9200:9200 -e 'xpack.security.enabled=true' -e 'discovery.type=single-node' -e 'xpack.license.self_generated.type=trial' -e 'ELASTIC_PASSWORD=changeme' docker.elastic.co/elasticsearch/elasticsearch:7.0.0-alpha2

curl http://localhost:9200 -u elastic:changeme

Expected : 
200 OK response

Actual : 
401 Unauthorized

[2019-01-08T22:15:17,981][INFO ][o.e.x.s.a.AuthenticationService] [afb4f96ae58a] Authentication of [elastic] was terminated by realm [reserved] - failed to authenticate user [elastic]

Problem seems to be with the docker-entrypoint.sh on this line https://github.com/elastic/elasticsearch/blob/master/distribution/docker/src/docker/bin/docker-entrypoint.sh#L78 where it validates that the x-pack directory exists under bin, but it does not. Changing it for something like `if [[ -f bin/x-pack-env ]]; then` seems to fix the issue.

### PR DESCRIPTION
**Pull request by rjernst**
This commit updates the file docker's entrypoint script looks for when
deciding to process the ELASTIC_PASSWORD env var. The x-pack subdir
of bin no longer exists in 7.0, where the backcompat layer for x-pack
script locations was removed.

closes #37240

### CODE REVIEW

**Comment by rjernst** [comment]
@elasticmachine run gradle build tests 1

**Review by alpar-t — APPROVED** [review]
LGTM

Would be nice to add some tests to make sure this works. 
The testfixtures plugin with docker-compose would make the startup part fairly straight forward and we would only need a test to make sure we can connect with the specific user.
We should aim to reach a decision on how we want to test the docker images so PRs like these can be accompanied by tests.

**Comment by atorok** [comment]
@elasticmachine  run all packaging tests

**Comment by rjernst** [comment]
Per discussion with @atorok I have spun off the need for docker tests into a separate issue: #37617.

**Pull request merged**
