### PR TITLE
fix composite aggregation tests failing after #76740

### PR DESCRIPTION
**Pull request by Luegg**
Follow up of #77650.

Looks like two issues caused occasional failures:

* `missingOrder` has not been considered in `InternalComposite.InternalBucket#compareKey`
* `reverseMul` has been ignored in one case in `OrdinalValuesSource#compareInternal`

The first problem has clearly been introduced by #76740 but the second point is more interesting. As far as I understand, this might have caused problems before but I couldn't find any according test failures in Gradle before yesterday.

In order to preclude further rare test failures I've run the whole `CompositeAggregatorTests` 3000 times and all tests turned green.

### CODE REVIEW

**Comment by Luegg** [comment]
@elasticmachine run elasticsearch-ci/part-1

**Comment by Luegg** [comment]
Unfortunately, bwc checks are currently failing (https://github.com/elastic/elasticsearch/issues/77711) but maybe you already want to have a look.

**Review by not-napoleon — APPROVED** [review]
LGTM.  Thanks for jumping on this!

**Review by nik9000 — APPROVED** [review]
LGTM. Good luck with the backport dance. That takes a while.

**Pull request merged**
