### PR TITLE
[DOCS] Update FIPS verbiage for the bundled JVM

### PR DESCRIPTION
**Pull request by lockewritesdocs**
This PR updates the [FIPS compliance docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/fips-140-compliance.html) to:

* Remove a statement that users can configure the bundled JVM to run with a FIPS 140-2 certified Java Security Provider
* Add links to the Elastic support matrix and the ESS FedRAMP authorized cloud offering

### CODE REVIEW

**Comment by lockewritesdocs** [comment]
@elasticmachine test this please

**Comment by lockewritesdocs** [comment]
@elasticmachine update branch

**Review by bytebilly — APPROVED** [review]

**Comment by bytebilly** [comment]
@lockewritesdocs should we backport that to all 8.x docs?

**Comment by lockewritesdocs** [comment]
> @lockewritesdocs should we backport that to all 8.x docs?

@bytebilly, if you think it's important to go all the way back, then I can backport to the additional 8.x branches.

**Comment by lockewritesdocs** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.2|[](https://github.com/elastic/elasticsearch/pull/90058)|
|✅|8.1|[](https://github.com/elastic/elasticsearch/pull/90059)|
|✅|8.0|[](https://github.com/elastic/elasticsearch/pull/90060)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
