### PR TITLE
Add additional low-level logging handler

### PR DESCRIPTION
**Pull request by jasontedor**
We have the trace handler which is useful for recording sent messages but there are times where it would be useful to have more low-level logging about the events occurring on a channel. This commit adds a logging handler that can be enabled by setting a certain log level (org.elasticsearch.transport.netty4.ESLoggingHandler) to trace that provides trace logging on low-level channel events and includes some information about the request/response read/write events on the channel as well.

### CODE REVIEW

**Comment by jasontedor** [comment]
This gives logging:

```
[2017-10-04T17:20:20,498][TRACE][o.e.t.n.ESLoggingHandler ] [id: 0x336e1141, L:/127.0.0.1:60072 - R:127.0.0.1/127.0.0.1:9301] [length: 291, request id: 242, type: request, version: 7.0.0-alpha1, action: indices:admin/seq_no/global_checkpoint_sync[r]] WRITE: 297B
[2017-10-04T17:20:20,498][TRACE][o.e.t.n.ESLoggingHandler ] [id: 0x336e1141, L:/127.0.0.1:60072 - R:127.0.0.1/127.0.0.1:9301] FLUSH
[2017-10-04T17:20:20,501][TRACE][o.e.t.n.ESLoggingHandler ] [id: 0x336e1141, L:/127.0.0.1:60072 - R:127.0.0.1/127.0.0.1:9301] [length: 103, request id: 242, type: response, version: 7.0.0-alpha1] READ: 109B
[2017-10-04T17:20:20,501][TRACE][o.e.t.n.ESLoggingHandler ] [id: 0x336e1141, L:/127.0.0.1:60072 - R:127.0.0.1/127.0.0.1:9301] READ COMPLETE
[2017-10-04T17:20:20,895][TRACE][o.e.t.n.ESLoggingHandler ] [id: 0x188bd042, L:/127.0.0.1:9300 - R:/127.0.0.1:45062] [length: 426, request id: 52, type: request, version: 7.0.0-alpha1, action: internal:discovery/zen/fd/master_ping] READ: 432B
[2017-10-04T17:20:20,895][TRACE][o.e.t.n.ESLoggingHandler ] [id: 0x188bd042, L:/127.0.0.1:9300 - R:/127.0.0.1:45062] [length: 99, request id: 52, type: response, version: 7.0.0-alpha1] WRITE: 105B
[2017-10-04T17:20:20,896][TRACE][o.e.t.n.ESLoggingHandler ] [id: 0x188bd042, L:/127.0.0.1:9300 - R:/127.0.0.1:45062] FLUSH
[2017-10-04T17:20:20,896][TRACE][o.e.t.n.ESLoggingHandler ] [id: 0x188bd042, L:/127.0.0.1:9300 - R:/127.0.0.1:45062] READ COMPLETE
```

It works with compressed streams, and over TLS.

**Review by ywelsch — CHANGES_REQUESTED** [review]
Code LGTM. Can you also add an integration test to validate that the logging handler works correctly (i.e. run some requests against cluster and check logging output, both on client and server)?

**Comment by bleskes** [comment]
This is great. Question - I wonder if we should invest in an option to selectively filter the requests we log something. We will still need to parse it to do the filtering, but my goal here is not have gazillion logs messages that may prevent people from using this in production. Like in the case we're chasing I'll only log recovery requests.

**Comment by jasontedor** [comment]
@bleskes I am not sure how we would do that? The action is only available on the request not the responses. We could track the requests in say in an LRU fashion to get the action for a response but this feels like overkill. There are other events on the channel anyway that are not associated with a request/response exchange. We could filter by channel type (recovery, regular, etc.), but that’s a lot of work to get that information here and I’m not sure I see much benefit to it.

**Comment by bleskes** [comment]
@jasontedor I trust you judgment about the trade offs. My concerns are about verbosity preventing this from being used in big production clusters. I'm with you if the potential solutions are just to ugly to consider.

**Review by ywelsch — APPROVED** [review]
LGTM

**Pull request merged**
