### PR TITLE
Fix locahost typo and distro clarifications

### PR DESCRIPTION
**Pull request by dliappis**
As per the commit log:
1. Apart from `locahost` typo, the issue is that localhost is not 100% safe
   for all distros with IPv6.
   For example fedora23 defines localhost4 and localhost6 (among other
   aliases) so `curl localhost:9200` doesn't work.
2. clarify that dnf is mostly for Fedora >=22
   RHEL7 and CentOS 7 are still on yum

### CODE REVIEW

**Comment by nik9000** [comment]
99% of our documentation uses localhost so I'm a bit worried about 127.0.0.1 being safer.

**Comment by nik9000** [comment]
The package manager part of the change LGTM.

**Comment by dliappis** [comment]
I understand the concern @nik9000 and this maybe a bit of a last minute thing after all.
If we revert back to `localhost` we should just keep in mind that the curl command won't work on latest fedora releases.

**Comment by dliappis** [comment]
Or what about adding a note there saying "curl 127.0.0.1:9200 on Fedora releases?" @nik9000

**Comment by jasontedor** [comment]
I'm confused, which Fedora releases does it not work on? My workstation is running Fedora 23 (4.2.3-300.fc23.x86_64) and I do not have any issues pinging localhost or curling localhost:9200 against a running Elasticsearch instance:

```bash
$ uname -r
4.2.3-300.fc23.x86_64
$ curl -XGET localhost:9200
{
  "name" : "Iceman",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "5.0.0-alpha1",
    "build_hash" : "baa2d51",
    "build_date" : "2016-03-31T20:40:01.961Z",
    "build_snapshot" : true,
    "lucene_version" : "6.0.0"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by dliappis** [comment]
@jasontedor do you have ipv6?

**Comment by jasontedor** [comment]
> do you have ipv6?

@dliappis Yes, I showed the output from `ip` and `lsmod`. I can also hit elasticsearch against localhost6:

```
$ curl -XGET localhost6:9200
{
  "name" : "Lizard",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "5.0.0-alpha1",
    "build_hash" : "baa2d51",
    "build_date" : "2016-03-31T20:40:01.961Z",
    "build_snapshot" : true,
    "lucene_version" : "6.0.0"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by dakrone** [comment]
Same here with multiple machines running Fedora, `curl localhost:9200` and `curl localhost6:9200` both work

**Comment by dliappis** [comment]
I actually traced this down to a vagrant bug.
It appears that if you specify a hostname, vagrant overwrites `localhost`

From a systems perspective, `127.0.0.1` is what is guaranteed to always work as it is the address assigned to the loopback device as opposed to `localhost` being just an entry in /etc/hosts.

I already reverted the doc changes and pushed the doc/typo fixo showing up `localhost`.

Thanks @jasontedor and @dakrone

**Comment by dliappis** [comment]
is this mergable now @nik9000 / @jasontedor  ?

**Comment by dakrone** [comment]
LGTM

**Comment by jasontedor** [comment]
LGTM.

**Pull request merged**
