### PR TITLE
add gradle licenseHeaders to precommit

### PR DESCRIPTION
**Pull request by rmuir**
This is a port of the logic from apache lucene that uses Rat. I just brought in all the lucene matchers and category logic, we can refine it later.

Differences:
- adds ES license header to the apache 2.0 matchers
- only works on java sources (vs. also resources). 
- simpler output (vs dumping whole report), since we are in gradle...

There are problems with some source files, i did not fix them. Please help me vet these files so we can add the correct licenses to them. I don't think we should add `exclusions` or any of that capability when we can just have license headers on all of our source code.

```
:core:licenseHeaders

Unapproved licenses:

  /home/rmuir/workspace/elasticsearch/core/src/main/java/org/elasticsearch/http/netty/pipelining/HttpPipeliningHandler.java
  /home/rmuir/workspace/elasticsearch/core/src/main/java/org/elasticsearch/http/netty/pipelining/OrderedDownstreamChannelEvent.java
  /home/rmuir/workspace/elasticsearch/core/src/main/java/org/elasticsearch/http/netty/pipelining/OrderedUpstreamMessageEvent.java
  /home/rmuir/workspace/elasticsearch/core/src/main/java/org/elasticsearch/search/profile/InternalProfileShardResults.java
  /home/rmuir/workspace/elasticsearch/core/src/test/java/org/elasticsearch/action/support/master/IndexingMasterFailoverIT.java
  /home/rmuir/workspace/elasticsearch/core/src/test/java/org/elasticsearch/cluster/routing/PrimaryAllocationIT.java
  /home/rmuir/workspace/elasticsearch/core/src/test/java/org/elasticsearch/cluster/routing/allocation/ActiveAllocationIdTests.java
```

```
:plugins:mapper-attachments:licenseHeaders

Unapproved licenses:

  /home/rmuir/workspace/elasticsearch/plugins/mapper-attachments/src/test/java/org/elasticsearch/mapper/attachments/TikaImplTests.java
```

```
:plugins:repository-hdfs:licenseHeaders

Unapproved licenses:

  /home/rmuir/workspace/elasticsearch/plugins/repository-hdfs/src/main/java/org/elasticsearch/plugin/hadoop/hdfs/Utils.java
  /home/rmuir/workspace/elasticsearch/plugins/repository-hdfs/src/test/java/org/elasticsearch/plugin/hadoop/hdfs/HdfsRepositoryRestIT.java
  /home/rmuir/workspace/elasticsearch/plugins/repository-hdfs/src/test/java/org/elasticsearch/plugin/hadoop/hdfs/HdfsTestPlugin.java
  /home/rmuir/workspace/elasticsearch/plugins/repository-hdfs/src/test/java/org/elasticsearch/plugin/hadoop/hdfs/UtilsTests.java
```

### CODE REVIEW

**Comment by nik9000** [comment]
Gradle work makes sense to me. I believe all the unapproves licenses in :core are just mistakes. I know the pipelining stuff came in via a PR from a community member but I believe they'd signed the CLA. The I only scanned the package names but they don't feel like they should have another license.

**Comment by rmuir** [comment]
I just want to trace each file one by one and make sure they are fine. The mapper attachers one i might have added (my ide is in a perpetual state of disrepair), i will look into it.

**Comment by polyfractal** [comment]
`InternalProfileShardResults` is mine, and indeed just a mistake.  I'll fix it in a few.

**Comment by rmuir** [comment]
I found the easy solution for tracking these (https://chrome.google.com/webstore/detail/github-follow/agalokjhnhheienloigiaoohgmjdpned/). It lets you follow history across renames in the github UI, that was my problem in tracing these back...

mapper attachments one was introduced by me.

**Comment by rmuir** [comment]
I traced back all of these files.

**Pull request merged**
