### PR TITLE
SQL: fix COUNT DISTINCT filtering

### LINKED ISSUE #37086: SQL: HAVING is using _count instead of the specified column
To reproduce, populate create an index with the following data:

```
DELETE test
PUT test
{
  "mappings": {
    "doc": {
      "properties": {
        "name": {
          "type": "keyword"
        },
        "category": {
          "type": "keyword"
        }
      }
    }
  }
}

PUT test/doc/1
{
  "name": "foo",
  "category": "A"
}

PUT test/doc/2
{
  "name": "foo",
  "category": "A"
}

PUT test/doc/3
{
  "name": "bar",
  "category": "A"
}

PUT test/doc/4
{
  "name": "baz",
  "category": "B"
}
```

The following statement returns expected results: 
```
POST _sql?format=text/plain
{
  "query": "SELECT count(DISTINCT name) as names, count(*) cnt, category FROM test GROUP BY category"
}

     names     |      cnt      |   category    
---------------+---------------+---------------
2.0            |3              |A              
1.0            |1              |B              
```

Please note, that category A has count 3 and category B has count of 1, while names have values of 1.0 and 2.0. However if we try to filter by names, the following request will not return us anything

```
POST _sql?format=text/plain
{
  "query": "SELECT count(DISTINCT name) as names, category FROM test GROUP BY category HAVING names = 2"
}
```

while this request returns us category A

```
POST _sql?format=text/plain
{
  "query": "SELECT count(DISTINCT name) as names, category FROM test GROUP BY category HAVING names = 3"
}

     names     |   category    
---------------+---------------
2.0            |A              

```
It is easy to see the reason for this by running translate. As you can see the bucket_selector is using `_count` instead of result of the coordinately aggregation `name`

```
POST _sql/translate
{
  "query": "SELECT count(DISTINCT name) as names, category FROM test GROUP BY category HAVING names = 3"
}

{
  "size" : 0,
  "_source" : false,
  "stored_fields" : "_none_",
  "aggregations" : {
    "groupby" : {
      "composite" : {
        "size" : 1000,
        "sources" : [
          {
            "593" : {
              "terms" : {
                "field" : "category",
                "missing_bucket" : true,
                "order" : "asc"
              }
            }
          }
        ]
      },
      "aggregations" : {
        "594" : {
          "cardinality" : {
            "field" : "name"
          }
        },
        "having.587" : {
          "bucket_selector" : {
            "buckets_path" : {
              "a0" : "_count"
            },
            "script" : {
              "source" : "InternalSqlScriptUtils.nullSafeFilter(InternalSqlScriptUtils.eq(params.a0,params.v0))",
              "lang" : "painless",
              "params" : {
                "v0" : 3
              }
            },
            "gap_policy" : "skip"
          }
        }
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by astefan**
This PR fixes #37086 bug where aggregation filtering (HAVING) on COUNT(DISTINCT) was behaving just like it does for non-DISTINCT version. Also, COUNT(DISTINCT) will try to use an exact version of the field whenever possible (the common scenario is the one of a `text` field), since it's using the `cardinality` aggregation which will not work on `text` fields.

### CODE REVIEW

**Comment by astefan** [comment]
run the gradle build tests 2

**Review by matriv — COMMENTED** [review]
Nice! I would ask to add some tests to the `QueryTranslatorTests` too, on top of the integ tests.

**Review by costin — APPROVED** [review]
Nice fix. Can you please check that we have duplicates in the data and do a test with `COUNT(column)` and `COUNT(DISTINCT column)` to check they return different (and correct) results?
Potentially by using the gender field instead.
COUNT(*) vs COUNT(column) vs COLUMN (DISTINCT column) should all return different results especially since we `NULL` data.

**Comment by astefan** [comment]
@costin while testing COUNT in a separate PR (still WIP), COUNT(column) and COUNT(DISTINCT column) are treated as the same agg. One first issue is that `equals` and `hashCode` doesn't account for `DISTINCT`. I fixed this, but still, the issue persists.

So, at this moment, a test with `COUNT(column), COUNT(DISTINCT column)` will return incorrect results. But the issue is on my radar and working on it. My suggestion, if you agree, would be to push this PR and the follow up one will cover https://github.com/elastic/elasticsearch/issues/34549 and any other issues I encounter (including the `COUNT(column) - COUNT(DISTINCT column)` you mentioned).

**Comment by astefan** [comment]
run the gradle build tests 2

**Comment by costin** [comment]
@astefan +1

**Review by matriv — APPROVED** [review]
LGTM!

**Comment by astefan** [comment]
run the gradle build tests 1

**Comment by astefan** [comment]
run the gradle build tests 1

**Comment by pcsanwald** [comment]
closes #37087

**Pull request merged**
