### PR TITLE
add String sha512() painless function

### LINKED ISSUE #97691: String sha512() painless function
### Description

In the ingest, reindex, update and update_by_query painless API elasticsearch has a String sha1() and String sha256() function that uses the corresponding MessageDigests function to perform the hash.

String sha512() is missing even MessageDigests provides a sha512() function.

Is there any reason that it is missing?
If not, I am happy to create a PR  :) https://github.com/elastic/elasticsearch/compare/main...l4r-s:elasticsearch:feature/painless-sha512

### PR DESCRIPTION
**Pull request by l4r-s**
fixes https://github.com/elastic/elasticsearch/issues/97691

### CODE REVIEW

**Comment by stu-elastic** [comment]
Per the java 17 docs, sha512() may [not be supported](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/security/MessageDigest.html).  Lemme think about how we want to handle that case.  It may be acceptable just to let it raise `NoSuchAlgorithmException`.

**Comment by stu-elastic** [comment]
@elasticmachine ok to test

**Comment by thecoop** [comment]
@elasticmachine ok to test

**Comment by thecoop** [comment]
buildkite test this

**Comment by l4r-s** [comment]
@thecoop thank you for pointing me to those commands! I fixed the formatting, let me know if there is something else that needs to be fixed.

**Review by thecoop — APPROVED** [review]
Great, thanks for addressing the comments. Good to merge now.

**Pull request merged**
