### PR TITLE
Thread falls into infinite loop when processing Indices query

### LINKED ISSUE #24735: Thread falls into infinite loop when processing Indices query
**Elasticsearch version**: 5.3.1, 5.3.2, 5.4.0

**Plugins installed**: None

**JVM version**: 1.8.0_121

**OS version**: Linux alan 4.8.0-41-generic #44-Ubuntu SMP Fri Mar 3 15:27:17 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
Problem and actual behavior: Thread falls into infinte loop in org.elasticsearch.index.query.IndicesQueryBuilder#doRewrite when range query 'from' > max value of the field. 
Expected behavior: Query returns a result

**Steps to reproduce**:

 1. Create an index with mapping having a dateTime field
`PUT some_index_name
{
  "mappings": {
    "some_type": {
      "properties": {
        "someDateTimeField": {
          "type": "date" 
        }
      }
    }
  }
}`
 2. Index at least one document
`PUT some_index_name/some_type/1
{ "someDateTimeField": "2015-01-01T12:10:30Z" } `
 3. Send range query with value 'from' > max value of the field
`{
  "from": 0,
  "size": 20,
  "query": {
    "indices": {
      "indices": [
        "some_index_name"
      ],
      "query": {
        "range": {
          "someDateTimeField": {
            "from": "2017-04-21T22:00:00.000Z",
            "to": "2017-04-22T22:00:00.000Z",
            "include_lower": true,
            "include_upper": true
          }
        }
      }
    }
  }
}`

### PR DESCRIPTION
**Pull request by kbialek**
Fixes #24735 

This pull request is created against branch 5.x since modified class is marked as deprecated and removed from master already.

### CODE REVIEW

**Comment by karmi** [comment]
Hi @kbialek, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/elasticsearch/pull/24736.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by kbialek** [comment]
e-mail added

**Comment by colings86** [comment]
jenkins test this

**Comment by colings86** [comment]
Jenkins retest this

**Review by colings86 — APPROVED** [review]
LGTM, I'll merge once the build has finished. Thanks for providing this fix 😄

**Pull request merged**
