### PR TITLE
Make MappedFieldType responsible for producing its own fieldcaps

### PR DESCRIPTION
**Pull request by romseygeek**
We'd like to start emitting information about intra-field relationships (for example,
nested parents, multifields, flattened roots) as part of the field caps API.  As a first 
step, this commit moves responsibility for the construction of IndexFieldCapabilities
objects directly to the fields themselves.

Relates to #75474

### CODE REVIEW

**Comment by romseygeek** [comment]
The biggest change here is that MappedFieldType implementations now need to say if they are metadata or not.  I think this is a good change though, and we can probably remove things like `SearchExecutionContext.isMetadataField()` in a follow-up.

**Review by jimczi — COMMENTED** [review]
I wonder if this is really needed. As such, there's nothing that prevents a metadata field mapper to create a field type that doesn't override the new `isMetadataField`. 
Why is it problematic to do the lookup through the mapper service ? I like the fact that being a metadata field is not a property of the field type, we don't need this information at this level.

**Comment by romseygeek** [comment]
We could change the signature of `MappedFieldType#fieldCaps()` to take a MapperService and do the lookup there? The main thing I want to do with this is make field types responsible for their own field caps output, so that we can localise parent relationship information within mapper implementations.

**Comment by romseygeek** [comment]
We could change the signature of `MappedFieldType#fieldCaps()` to take a MapperService and do the lookup there? The main thing I want to do with this is make field types responsible for their own field caps output, so that we can localise parent relationship information within mapper implementations.

**Comment by jimczi** [comment]
> We could change the signature of MappedFieldType#fieldCaps() to take a MapperService and do the lookup there?

+1, that seems less error prone, thanks.

**Comment by romseygeek** [comment]
Having thought about this more, I don't think we need to do things this way.  Closing for now.

**Pull request closed without merging**
