### PR TITLE
Docs: change some mistake in align

### PR DESCRIPTION
**Pull request by ramudu63**
change some mistake in align

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by ramudu63** [comment]
change some mistake in align

**Comment by nik9000** [comment]
The change looks good to me @ramudu63. Could you sign our [CLA](https://www.elastic.co/contributor-agreement)? We need it for every change, if one as small as flipping a square bracket.

**Comment by colings86** [comment]
I don't think we should merge this change as is, since the existing text is trying to convey that the value of the random score is between 0 and 1, inclusive on the lower bound and exclusive on the upper bound. So this is not a typo but in fact an intentional notation. We can discuss the merits of using this notation but I think if we want to get rid of the notation for clarity we need to add an explicit description in words instead since `[0,1]` is not correct for the behaviour a user will see (because the upper bound is exclusive)

**Comment by nik9000** [comment]
I've never seen someone use `[0, 1[` for exclusive upper bound. I've seen `[0, 1)` for that. But I agree we should avoid the interval syntax because we get questions about it from time to time.

**Comment by colings86** [comment]
AFAIK both notations are accepted though I'll admit I have seen `[0,1)` more often.

**Comment by nik9000** [comment]
Hey @ramudu63, @colings86 and I talked this through and went with #35093 instead. Thanks for submitting this!

**Pull request closed without merging**
