### PR TITLE
improve RoutingTable calling IndexRoutingTable#shardsWithState

### PR DESCRIPTION
**Pull request by hanbj**
When the cluster state changes, the DelayedAllocationService will process the new cluster state. 
In the scheduleIfNeeded() method, the UnassignedInfo#findNextDelayedAllocation() and UnassignedInfo#getNumberOfDelayedUnassigned() methods will be called. 
In both methods, you need to find the unassigned state shards in all shards.

As the number of shards increases, this process will become more and more time-consuming, which will affect the overall performance of the master#updateTask.

Therefore, when constructing the IndexRoutingTable object, we can match ShardRoutingState and ShardRouting in advance, because we may need to find other ShardRoutingState shards in all shards in the future.

### CODE REVIEW

**Comment by DaveCTurner** [comment]
@hanbj can you add a benchmark showing the improvement that this makes? We won't merge the benchmark but it will help to demonstrate the benefits of this change more clearly.

**Comment by hanbj** [comment]
@DaveCTurner Thank you. I added a benchmark. Is that right?

**Comment by DaveCTurner** [comment]
Ok, just looking at the most expensive benchmark with 300000 shards (1000 indices * 100 shards * (2 replicas + a primary)) I get these results:

```
Benchmark                                    (indicesShardsReplicas)  Mode  Cnt  Score   Error  Units
RoutingTableBenchmark.shardsWithState        1000|     100|        2  avgt   30  0.734 ± 0.003  ms/op
```

For comparison, here's the results from before your change:

```
Benchmark                                    (indicesShardsReplicas)  Mode  Cnt   Score   Error  Units
RoutingTableBenchmark.shardsWithState        1000|     100|        2  avgt   30  18.873 ± 0.228  ms/op
```

The proposed code is ~20x faster, but in absolute terms the savings just aren't worth it. This code only runs a couple of times per cluster state update so we're only talking about saving 40ms or so, and even that is only if the cluster has a rather ludicrous number of shards. On a more reasonably-sized cluster of 30k shards the savings are tiny. Therefore I am closing this.

**Comment by hanbj** [comment]
@DaveCTurner 
I don't think so.
You said that this code only runs a few times during a cluster state update. The time saving in a 300,000-shard cluster is only 40ms. If you update the cluster state multiple times, have you considered the scenario of frequent cluster state updates? . The overall time saved is very much.
The 30k shards you suggested are reasonable. I don’t know if you have encountered PB-level data. If a cluster can only have 30k shards, we will have hundreds of thousands of clusters. Such maintenance costs too big. So we are working hard to optimize the status of the cluster to update this piece. Every place is optimized a little bit. Finally, we hope that a cluster can have millions of shards.
Only a large cluster can make better use of machine resources and save costs.
Is ES positioning just a small cluster.

**Comment by DaveCTurner** [comment]
If you follow the guideline that shards should be many 10s of GBs in size, a 300k-shard cluster should hold of the order of 10PB. That's certainly pushing the limit of what we consider reasonable for a single cluster, but I don't think many people would call that "small".

> If a cluster can only have 30k shards, we will have hundreds of thousands of clusters.

This implies you have 3 billion shards, or ~100EB of data assuming your shards are appropriately sized. That's [rather implausible](https://what-if.xkcd.com/63/).

**Comment by hanbj** [comment]
@DaveCTurner 
many thanks to my friends. In the process of using ES, we found that when about 30,000 shards in the cluster, the processing of pending_tasks is already very slow. If the clusterstate is updated frequently, pending_tasks will accumulate. My friend, we are in every detail To achieve optimal performance, the performance will be better and better. Just like the memory is saved one byte at a time.

**Comment by hanbj** [comment]
@DaveCTurner 
It is not a pessimistic hypothesis, if customers using ES really have more than 30,000 or more shards clusters, at least we have made efforts in performance. This optimization may not be a big deal. But with other optimizations I think it will be a good performance improvement, I am doing this recently.

**Pull request closed without merging**
