### PR TITLE
Limit stats values in tests to prevent long overflow

### LINKED ISSUE #59174: [CI] ClusterStatsNodesTests.testIngestStats failure on master
**Build scan**:
https://gradle-enterprise.elastic.co/s/3rljbxcxeddxq

**Repro line**:
```
./gradlew ':server:test' --tests "org.elasticsearch.action.admin.cluster.stats.ClusterStatsNodesTests.testIngestStats" \
  -Dtests.seed=2B18C0EB83EF536A \
  -Dtests.security.manager=true \
  -Dtests.locale=sq \
  -Dtests.timezone=Asia/Ulan_Bator \
  -Dcompiler.java=14 \
  -Druntime.java=11
```

**Reproduces locally?**:

Yes

**Failure excerpt**:
```
java.lang.IllegalArgumentException: duration cannot be negative, was given [-5167652678572409797]
	at __randomizedtesting.SeedInfo.seed([2B18C0EB83EF536A:B3CC4A8E32729A56]:0)
	at org.elasticsearch.common.unit.TimeValue.<init>(TimeValue.java:51)
	at org.elasticsearch.action.admin.cluster.stats.ClusterStatsNodes$IngestStats.toXContent(ClusterStatsNodes.java:755)
	at org.elasticsearch.common.xcontent.XContentHelper.toXContent(XContentHelper.java:366)
	at org.elasticsearch.common.xcontent.XContentHelper.toXContent(XContentHelper.java:351)
	at org.elasticsearch.action.admin.cluster.stats.ClusterStatsNodesTests.testIngestStats(ClusterStatsNodesTests.java:111)
```

### PR DESCRIPTION
**Pull request by danhermann**
The use of random long values in this test meant that occasionally sufficiently large long values would be selected resulting in long overflow when their values were summed. This change ensures that the random values are less than (Long.MAX_VALUE / numValues) so that their sum will never overflow.

Fixes #59174

### CODE REVIEW

**Comment by danhermann** [comment]
@elasticmachine update branch

**Review by jbaiera — APPROVED** [review]
LGTM

**Comment by danhermann** [comment]
Thanks, @jbaiera!

**Comment by gwbrown** [comment]
@danhermann I don't see any backports linked to this PR, are we still intending to backport this? (or have we already and I'm just missing it)

**Pull request merged**
