### PR TITLE
Avoid capturing cluster state in TBbNA

### PR DESCRIPTION
**Pull request by DaveCTurner**
Similar to #90724, today all `TransportBroadcastByNodeAction` implementations capture the cluster state at invocation time and hold it until completion, but most of them don't need anything from the cluster state and the couple that do certainly don't need the whole thing. This commit avoids that unnecessary capture.

### CODE REVIEW

**Comment by DaveCTurner** [comment]
https://github.com/elastic/elasticsearch/pull/89619 massively reduces the memory usage in the case of this I saw, but IMO this is worth doing too.

**Comment by DaveCTurner** [comment]
Nominating @jbaiera for a review here because the most substantive change is to `DataStreamsStatsTransportAction`.

**Review by jbaiera — APPROVED** [review]
LGTM!

Gotta love that we've been holding on to that cluster state for all these actions that don't even use it. sigh...

**Comment by DaveCTurner** [comment]
@elasticmachine test this please

**Comment by DaveCTurner** [comment]
@elasticmachine update branch

**Pull request merged**
