### PR TITLE
Fix GeoHash PrefixTree BWC

### LINKED ISSUE #38494: geo_shape queries not working anymore after upgrade to 6.6
**Elasticsearch version**: 6.6.0 on ES Cloud 

**Description of the problem including expected versus actual behavior**:

After upgrading from 6.5.4 to 6.6.0 on ES Cloud, none of our geo_shape queries work anymore. Moreover, it is not clear from the [6.6 breaking changes](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-6.6.html#_changed_default_literal_geo_shape_literal_indexing_strategy) what needs to be done to make pre-6.6. shapes compatible with 6.6.

**Steps to reproduce**:

1. Create an index on a pre-6.6 ES containing a field of type `geo_shape`

```
PUT test
{
  "mappings": {
    "doc": {
      "properties": {
        "my_shape": {
          "type": "geo_shape"
        }
      }
    }
  }
}
```

2. index a shape
```
PUT test/doc/1
{
  "my_shape": {
    "type": "Polygon",
    "coordinates": [
      [
        [
          -118.37326599344239,
          34.082247752657956
        ],
        [
          -118.37326637421617,
          34.082384870862526
        ],
        [
          -118.37369602509777,
          34.08238389978479
        ],
        [
          -118.37369564361956,
          34.082246781581595
        ],
        [
          -118.37326599344239,
          34.082247752657956
        ]
      ]
    ]
  }
}
```

3. Find the shape using a `geo_shape` query
```
POST test/_search
{
  "query": {
    "geo_shape": {
      "my_shape": {
        "shape": {
          "type": "point",
          "coordinates": [-118.37345570325851, 34.08231046148952]
        },
        "relation": "contains"
      }
    }
  }
}
```

4. Migrate to ES 6.6

5. Run search from step 3 again and see that there is nothing being returned.

### PR DESCRIPTION
**Pull request by nknize**
`geo_shape` indexes created before 6.6 use `geohash` string encoding as default `tree` parameter and `quadtree` encoding for 6.6 and later. This commit fixes bwc to use `geohash` encoding in `LegacyGeoshapeFieldMapper` for indexes created before 6.6.

closes #38494

### CODE REVIEW

**Comment by iverase** [comment]
My understanding is that the default configuration for 6.6 is BKD-based geoshapes and therefore if you want a SPT tree you will need to specify it in the mapping. For all indexed created previously the default SPT is geohash. 

Would not be an easier fix just to revert the default SPT to geohash as it is not possible to create a mapper with default tree quad?

**Comment by polyfractal** [comment]
It'd be simpler, but I'm not sure we can do that now that 6.6 has shipped. I think we'll need a version check either way :(

E.g. there could be `6.6.0` clusters that indexed a bunch of data and it's now in `quadtree`. We'd have to at least have a version check for `6.6.0` specifically, even if we roll the default back to `geohash` for `6.6.1+`.

**Comment by iverase** [comment]
My understanding is that in 6.6.0 if you do not specify the tree, then it will be indexed as BKD, so you must specify the tree you want to index if you use SPT, is that right? 

Then if there is not tree  and < 6.6.0, the tree is geohash else is BKD.

**Comment by polyfractal** [comment]
Oh, yes, you're right.  I was completely confusing myself :)

**Comment by nknize** [comment]
You can enable PrefixTrees by either setting `tree` or `strategy`. If you enable them by setting `strategy` the default tree (as of 6.6) is `quadtree`.  < 6.6 is `geohash`.

**Comment by nknize** [comment]
retest this please

**Comment by iverase** [comment]
Ouch, I missed that. Then it is possible to create a SPT index using the default in 6.6. Thanks for the clarification @nknize

**Review by iverase — APPROVED** [review]
LGTM

**Review by polyfractal — APPROVED** [review]
LGTM2

**Pull request merged**
