### PR TITLE
[DOCS] Update disk-usage.asciidoc

### PR DESCRIPTION
**Pull request by bradvido**
added missing word

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against main? Unless there is a good reason otherwise, we prefer pull requests against main and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Review by abdonpijpelink — APPROVED** [review]
LGTM. Thanks @bradvido !

**Comment by abdonpijpelink** [comment]
@bradvido To make sure that this change is included in future versions of the documentation, it should also be applied to the `main` branch. Would you like to backport it yourself, or shall I do it for you?

**Comment by bradvido** [comment]
> @bradvido To make sure that this change is included in future versions of the documentation, it should also be applied to the `main` branch. Would you like to backport it yourself, or shall I do it for you?

Go for it. Just trying to fix the typo :)

**Comment by abdonpijpelink** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|main|[](https://github.com/elastic/elasticsearch/pull/89874)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
