### PR TITLE
CORE: Make Pattern Exclusion Work with Aliases

### LINKED ISSUE #33395: Multi-Index pattern exclusions do not work on aliases
**Describe the feature**:

Multi-index exclusion should work for aliases not just aliases.

**Elasticsearch version** (`bin/elasticsearch --version`): master

**Plugins installed**: []

**JVM version** (`java -version`): Java 10.0.1+10

**OS version** (`uname -a` if on a Unix-like system): Win 10

**Description of the problem including expected versus actual behavior**:
[Multi-index](https://www.elastic.co/guide/en/elasticsearch/reference/current/multi-index.html) allows one to specify an enumeration of indices or aliases, wildcards, inclusions and exclusions when selecting an index.
However it looks like the exclusion, works only for concrete indices and not for aliases.

**Steps to reproduce**:

 1.
assume there are 3 indices, 2 having 2 different aliases pointing to both of them:
```json
PUT test_index1
{
    "aliases" : {
        "test_alias1" : {},
        "test_alias2" : {}
        }
}

PUT test_index2
{
    "aliases" : {
        "test_alias1" : {},
        "test_alias2" : {}
        }
}

PUT test_index_noalias
{
}

GET /_cat/aliases?v

alias                  index                     filter routing.index routing.search
test_alias1         test_index2            -      -             -
test_alias2         test_index2            -      -             -
test_alias1         test_index1            -      -             -
test_alias2         test_index1            -      -             -
```

 2.
The following request:
```java
 GetAliasesRequest aliasRequest = new GetAliasesRequest()
                    .local(true)
                    .aliases("test_alias1")
                    .indicesOptions(IndicesOptions.lenientExpandOpen());
   
```
Returns `test_alias1`. 
In a similar fashion, using `.aliases("test_alias*")` returns both `test_alias1` and `test_alias2` as expected.

 3.
However setting `.aliases("test_alias*", "-test_alias1")` still returns `test_alias1` and `test_alias2`.
The expectation is only `test_alias2` is returned.

### PR DESCRIPTION
**Pull request by original-brownbear**
* Adds the pattern exclusion logic to finding aliases
* Closes #33395

### CODE REVIEW

**Review by bleskes — CHANGES_REQUESTED** [review]
I'm afraid this is not good enough. Think about something like `["a*", "-*b", "b*"]` - this should start with adding all the aliases which start with `a`, remove those who end with a `b` and then add all aliases that start with a `b`. This means that an alias `bob` will be added. I believe the current version of the code doesn't do that.

Another problem I see is when people say `["a*", "-ab"]` which should mean - all aliases that start with an by not `ab`. Note that alias names can't start with a `-` for this reason. See `MetaDataCreateIndexService#validateIndexOrAliasName `

**Comment by original-brownbear** [comment]
@bleskes 

>  I believe the current version of the code doesn't do that.

Yea you're right. Sorry didn't think (or know :)) about that case yet :( => will fix very soon.

> Another problem I see is when people say ["a*", "-ab"] which should mean - all aliases that start with an by not ab. Note that alias names can't start with a - for this reason. See MetaDataCreateIndexService#validateIndexOrAliasName

This case works fine already I think (see the added test).

**Comment by original-brownbear** [comment]
@bleskes double checked that we disallow indices starting with `-` starting in `5.0.0` see https://github.com/elastic/elasticsearch/pull/20033/commits/6030acb43b5ccc5cf051052b7241f3330c62a820 that went into `5.0.0` :)

**Comment by original-brownbear** [comment]
@bleskes all fixed now (I hope :)) in https://github.com/elastic/elasticsearch/pull/33518/commits/8b9e76981a9aa805a6be68b238d4df0aa6c40c48 -> good for another review :)

**Review by bleskes — APPROVED** [review]
LGTM. Thanks for the extra iteration.

**Comment by original-brownbear** [comment]
@bleskes np + thanks for the review :)

**Pull request merged**
