### PR TITLE
Fix DateFieldType.isFieldWithinQuery:

### PR DESCRIPTION
**Pull request by jimczi**
- PointValues.size throws an exception if there is no value indexed for the field.

### CODE REVIEW

**Comment by jpountz** [comment]
@jimferenczi what is the exception being thrown? I think it should return 0 rather than throw an exception?

**Comment by jimferenczi** [comment]
@jpountz this is a IllegalArgumentException: https://github.com/apache/lucene-solr/blob/f6c7fc7a26584c92a81b3a6cbca179ca232808a9/lucene/core/src/java/org/apache/lucene/codecs/lucene60/Lucene60PointsReader.java#L123

It's an edge case where the mapping exists in es but the fieldinfo does not exist in any of the Lucene segments.

**Comment by jpountz** [comment]
Thanks. I was under the (wrong!) assumption that `PointValues.size(field)` returns zero if the field does not have points. I opened https://issues.apache.org/jira/browse/LUCENE-7257 to discuss what `PointValues.size` should do with leaves that do not have points.

**Comment by jimferenczi** [comment]
I've opened a more generic PR: #18011

**Pull request closed without merging**
