### PR TITLE
Unmute smoke test monitoring with watcher.

### PR DESCRIPTION
**Pull request by martijnvg**

### CODE REVIEW

**Comment by martijnvg** [comment]
@elasticmachine run elasticsearch-ci/docs

**Review by jakelandis — APPROVED** [review]
LGTM (sorry for the delay, this slipped past me)

**Comment by martijnvg** [comment]
@elasticmachine update branch

**Comment by martijnvg** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample-matrix-windows

**Pull request merged**
