### PR TITLE
Check licenses of jars extracted from the ZIP file

### LINKED ISSUE #11766: license checker should inspect packages
the license checker today looks at `/target/lib/*.jar` I personally would feel better if we would unzip / untar the packages and check that we have license and sha1 hashes for all the jars in there. This would also work for plugins since they don't have a `/target/lib` folder which is es core specific. Note, plugins put their deps on the top level not in `lib`

### PR DESCRIPTION
**Pull request by clintongormley**
This changes the license checker to extract jars from the ZIP file instead of relying on the `target_lib/` directory.  If there is a tar.gz file, it checks to ensure that the JARs are identical to those in the ZIP file.

Also added LICENSE and NOTICE files for each plugin and for their dependencies.

Note: the slf4j jar was in the core/target/lib directory, but it is not included in the ZIP or tar.gz file.  Is this a bug?

Closes #11766

### CODE REVIEW

**Comment by s1monw** [comment]
LGTM

**Comment by clintongormley** [comment]
@kimchy when we build elasticsearch, slf4j is included in the target/libs directory, but not included in the .zip/.tar.gz packages.  Is this correct? Or should we be shipping it too?

**Comment by kimchy** [comment]
@clintongormley no need to ship slf4j as part of any of our distributions

**Comment by clintongormley** [comment]
thanks, pushing

**Comment by s1monw** [comment]
@kimchy should we mark the dependency as provided then?

**Comment by kimchy** [comment]
@s1monw yea, I think it makes sense

**Comment by dadoonet** [comment]
Optional or Provided ?

**Pull request merged**
