### PR TITLE
Add tests progress indicator

### PR DESCRIPTION
**Pull request by rmuir**
Looks like this:

```
Suite: org.elasticsearch.search.aggregations.bucket.HistogramTests
Completed [10/713] on J0 in 8.32s, 27 tests

Suite: org.elasticsearch.indices.state.OpenCloseIndexTests
Completed [11/713] on J2 in 16.23s, 20 tests
```

Upgrades randomizedtesting to 2.1.13.

### CODE REVIEW

**Comment by dakrone** [comment]
Awesome! LGTM

**Comment by jpountz** [comment]
w00t

**Comment by nik9000** [comment]
And seeing this made me upgrade to the newest junit4 plugin as well.

**Comment by tlrx** [comment]
Nice! Now I can see if I have the time to grab a coffee before the end of the tests :)

**Pull request merged**
