### PR TITLE
Set default min heap equal to default max heap

### PR DESCRIPTION
**Pull request by jasontedor**
This commit sets the default min heap equal to the default max
heap. This is to align the default out-of-box settings with the heap
size bootstrap check.

Relates #16334, relates #17728, relates #18311

### CODE REVIEW

**Comment by nik9000** [comment]
I think this puts the minimum ram required to run all the tests at around 5GB, right? 2 x 2GB for two nodes, 512MB for the test runner, and some extra for gradle.

**Comment by abeyad** [comment]
LGTM

**Comment by jasontedor** [comment]
@nik9000 I pushed 13e20e3320941f569efd18e9614bf673aa1b9dee. Can you and @abeyad take a look?

**Comment by abeyad** [comment]
@jasontedor makes sense, LGTM

**Comment by jasontedor** [comment]
Thanks @abeyad and @nik9000.

**Pull request merged**
