### PR TITLE
Add ECS schema for user-agent ingest processor (#37727)

### LINKED ISSUE #37329: Bring the user_agent processor in line with ECS
**Describe the context**

In developing ECS, we took a step back and took a critical look at the information we're looking for, when parsing a user agent. The current user_agent plugin for Ingest Node had a few issues, we found.

Let's start with the default parsing for Chrome 70.0.3538.102 on Mac 10.14.1:

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36`

Is parsed as such:

```JSON
{
  "patch" : "3538",
  "major" : "70",
  "minor" : "0",
  "os" : "Mac OS X 10.14.1",
  "os_minor" : "14",
  "os_major" : "10",
  "name" : "Chrome",
  "os_name" : "Mac OS X",
  "device" : "Other"
}
```

To follow ECS, the structure would ideally be:

```JSON
{
  "name" : "Chrome",
  "original" : "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36",
  "os" : {
    "name" : "Mac OS X",
    "version" : "10.14.1",
    "full" : "Mac OS X 10.14.1"
  },
  "device" : "Other",
  "version" : "70.0.3538.102"
}
```

There's a few things to notice here

- By default, the versions are reported as a complete version string, not broken down. An option is still welcome, to output the breakdown of the version numbers.
  - Also: full version strings make support for pre-release versions trivial (e.g. `-beta1`, `-rc2` etc.)
- The original ua string is kept around, which can be made optional as well.

In translating multiple access log Filebeat modules to match ECS, I've had to repeatedly rename the fields around. Here are some examples:

* Apache - all fields renamed, but the version numbers are still broken down (which is not in ECS). Currently most access log modules are implemented this way.
  * [pipeline](https://github.com/elastic/beats/blob/529feda9377ca6df1da5c8f4bbaed89a7413158e/filebeat/module/apache2/access/ingest/default.json#L40-L80)
  * [result](https://github.com/elastic/beats/blob/529feda9377ca6df1da5c8f4bbaed89a7413158e/filebeat/module/apache2/access/test/test.log-expected.json#L36-L44)
* Traefik - fields renamed, and there's a hacky attempt at reconstructing full version fields :-)
  * [pipeline](https://github.com/elastic/beats/blob/529feda9377ca6df1da5c8f4bbaed89a7413158e/filebeat/module/traefik/access/ingest/pipeline.json#L71-L118)
  * [semi-successful version reconstruction](https://github.com/elastic/beats/blob/529feda9377ca6df1da5c8f4bbaed89a7413158e/filebeat/module/traefik/access/test/test.log-expected.json): Browsing around you'll see completely empty versions (`..`), partially reconstructed ones (`11.2.` instead of `11.2.5`) and successful reconstructions (`7.62.0`). Of course this can be cleaned up further to eliminate the noise.
  * Note that this has not been released yet, and will not be released in its current form, this is an experiment ;-)

I don't mind doing this in order to hit the 7.0 feature freeze in a pinch. But I think this will not be a good experience for users that try to follow ECS, when they use the user agent processor. They would benefit greatly from having the plugin follow ECS by default or via some easy to enable setting(s).

**Describe the feature**

Can we update the user agent parser to:

- output field names following the ECS schema
- output the full version string for the agent and for the OS
- output the original agent string at `.original`

I'm more than happy that we do this via one or more option flags.

cc @ruflin

### PR DESCRIPTION
**Pull request by dakrone**
(This is a forward-port with changes of #37727)

This switches the format of the user agent processor to use the schema from [ECS](https://github.com/elastic/ecs).
So rather than something like this:

```
{
  "patch" : "3538",
  "major" : "70",
  "minor" : "0",
  "os" : "Mac OS X 10.14.1",
  "os_minor" : "14",
  "os_major" : "10",
  "name" : "Chrome",
  "os_name" : "Mac OS X",
  "device" : "Other"
}
```

The structure is now like this:

```
{
  "name" : "Chrome",
  "original" : "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36",
  "os" : {
    "name" : "Mac OS X",
    "version" : "10.14.1",
    "full" : "Mac OS X 10.14.1"
  },
  "device" : "Other",
  "version" : "70.0.3538.102"
}
```

This is now the default for 7.0. The deprecated `ecs` setting in 6.x is not
supported.

Resolves #37329

### CODE REVIEW

**Comment by JoshMock** [comment]
jenkins retest this please

**Review by jakelandis — APPROVED** [review]
LGTM

**Comment by simitt** [comment]
I just tried to use the changed user-agent ingest processor and realized that the `device` implementation differs from the ECS definition:
`device` is implemented as `keyword` but in ECS defined as `object` with a field `name` that is a `keyword`, see https://github.com/elastic/ecs#-user-agent-fields.

**Comment by webmat** [comment]
Oh jeez, I made the mistake in what field I requested 🤦‍♂️Sorry about that!

The nesting of device.name is there to allow for other fields about the device eventually. Like device.category (tablet, mobile, etc).

So the nesting is kind of important, even if there's nothing else under `device.` yet.

**Comment by webmat** [comment]
I created issue https://github.com/elastic/elasticsearch/issues/38094 for this

**Pull request merged**
