### PR TITLE
Give kibana user privileges to create APM agent config index

### PR DESCRIPTION
**Pull request by ogupte**
Addresses elastic/kibana#45610 by giving the kibana user reserved role privileges on `.apm-agent-configuration` to create APM agent config index in Kibana.

### CODE REVIEW

**Comment by ogupte** [comment]
@elasticmachine merge upstream

**Review by sorenlouv — APPROVED** [review]
LGTM
Probably needs a 👍 from @kobelb as well.

**Review by kobelb — APPROVED** [review]
LGTM - but we'll need approval from an ES team member, as this changes their code.

**Comment by ogupte** [comment]
@elasticmachine merge upstream

**Review by jkakavas — APPROVED** [review]
LGTM

**Comment by jkakavas** [comment]
@ogupte you would need to open the relevant PRs for `7.x` and `7.4` too. Let us know if you need any help with that

**Comment by sqren** [comment]
@ogupte `backport --upstream elastic/elasticsearch --branch 7.x --branch 7.4` should do the trick.

**Comment by sqren** [comment]
When I get someone convinced to merge [this](https://github.com/elastic/elasticsearch/pull/38349) it will be possible to simply run `backport`

**Pull request merged**
