### PR TITLE
[DOCS] Reorg monitoring configuration for re-use

### PR DESCRIPTION
**Pull request by lcawl**
This PR reorganizes the information in https://www.elastic.co/guide/en/elasticsearch/reference/master/configuring-metricbeat.html such that its content can be re-used (via tagged regions) from other places (e.g. the Stack Overview).

It also adds fuller configuration file examples and clarifies that the steps related to the Elasticsearch X-Pack module for Metricbeat instead of the Elasticsearch module.

Related to https://github.com/elastic/stack-docs/pull/318

### CODE REVIEW

**Comment by lcawl** [comment]
These changes can be previewed here: https://doc-review-63bf6.firebaseapp.com/es/configuring-metricbeat.html

**Comment by ycombinator** [comment]
The intent behind introducing the `elasticsearch-xpack` module configuration variant in 7.2 was so users wouldn't need to manually edit the elasticsearch module configuration file.

To that end, could we remove the configuration snippet shown in step 6 altogether? We'd still want to mention something about editing the `host` setting in `modules.d/elasticsearch-xpack.yml` if they want to point to an Elasticsearch node other than the default at `http://localhost:9200`.

**Comment by lcawl** [comment]
> To that end, could we remove the configuration snippet shown in step 5 altogether? 

@ycombinator I have updated that step to make it clearer that typically just the hosts, user, and password values need to be updated. Is that acceptable?

**Review by ycombinator — APPROVED** [review]
LGTM. Thanks @lcawl!

**Pull request merged**
