### PR TITLE
Fix permissions for UnboundID LDAP SDK

### LINKED ISSUE #68838: NoClassDefFoundError: Could not initialize class com.unboundid.util.Debug
**Elasticsearch version** (`bin/elasticsearch --version`): 7.11.0 - Docker

**Description of the problem including expected versus actual behavior**:
```
{"type": "server", "timestamp": "2021-02-10T15:32:51,596Z", "level": "ERROR", "component": "o.e.b.ElasticsearchUncaughtExceptionHandler", "cluster.name": "docker-cluster", "node.name": "es02", "message": "fatal error in thread [main], exiting", 
"stacktrace": ["java.lang.NoClassDefFoundError: Could not initialize class com.unboundid.util.Debug",
"at com.unboundid.ldap.sdk.LDAPConnectionOptions.getSystemProperty(LDAPConnectionOptions.java:2278) ~[?:?]",
"at com.unboundid.ldap.sdk.LDAPConnectionOptions.<clinit>(LDAPConnectionOptions.java:213) ~[?:?]",
"at org.elasticsearch.xpack.security.authc.ldap.support.SessionFactory.connectionOptions(SessionFactory.java:122) ~[?:?]",
"at org.elasticsearch.xpack.security.authc.ldap.support.SessionFactory.serverSet(SessionFactory.java:203) ~[?:?]",
"at org.elasticsearch.xpack.security.authc.ldap.support.SessionFactory.<init>(SessionFactory.java:81) ~[?:?]",
"at org.elasticsearch.xpack.security.authc.ldap.PoolingSessionFactory.<init>(PoolingSessionFactory.java:62) ~[?:?]",
"at org.elasticsearch.xpack.security.authc.ldap.ActiveDirectorySessionFactory.<init>(ActiveDirectorySessionFactory.java:68) ~[?:?]",
"at org.elasticsearch.xpack.security.authc.ldap.LdapRealm.sessionFactory(LdapRealm.java:89) ~[?:?]",
"at org.elasticsearch.xpack.security.authc.ldap.LdapRealm.<init>(LdapRealm.java:68) ~[?:?]",
"at org.elasticsearch.xpack.security.authc.InternalRealms.lambda$getFactories$2(InternalRealms.java:113) ~[?:?]",
"at org.elasticsearch.xpack.security.authc.Realms.initRealms(Realms.java:214) ~[?:?]",
"at org.elasticsearch.xpack.security.authc.Realms.<init>(Realms.java:76) ~[?:?]",
"at org.elasticsearch.xpack.security.Security.createComponents(Security.java:480) ~[?:?]",
"at org.elasticsearch.xpack.security.Security.createComponents(Security.java:412) ~[?:?]",
"at org.elasticsearch.node.Node.lambda$new$16(Node.java:560) ~[elasticsearch-7.11.0.jar:7.11.0]",
"at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271) ~[?:?]",
"at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]",
"at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]",
"at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]",
"at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]",
"at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]",
"at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]",
"at org.elasticsearch.node.Node.<init>(Node.java:564) ~[elasticsearch-7.11.0.jar:7.11.0]",
"at org.elasticsearch.node.Node.<init>(Node.java:278) ~[elasticsearch-7.11.0.jar:7.11.0]",
"at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:216) ~[elasticsearch-7.11.0.jar:7.11.0]",
"at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:216) ~[elasticsearch-7.11.0.jar:7.11.0]",
"at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:387) ~[elasticsearch-7.11.0.jar:7.11.0]",
"at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-7.11.0.jar:7.11.0]",
"at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-7.11.0.jar:7.11.0]",
"at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:75) ~[elasticsearch-7.11.0.jar:7.11.0]",
"at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:116) ~[elasticsearch-cli-7.11.0.jar:7.11.0]",
"at org.elasticsearch.cli.Command.main(Command.java:79) ~[elasticsearch-cli-7.11.0.jar:7.11.0]",
"at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115) ~[elasticsearch-7.11.0.jar:7.11.0]",
"at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:81) ~[elasticsearch-7.11.0.jar:7.11.0]"] }
fatal error in thread [main], exiting
java.lang.NoClassDefFoundError: Could not initialize class com.unboundid.util.Debug
        at com.unboundid.ldap.sdk.LDAPConnectionOptions.getSystemProperty(LDAPConnectionOptions.java:2278)
        at com.unboundid.ldap.sdk.LDAPConnectionOptions.<clinit>(LDAPConnectionOptions.java:213)
        at org.elasticsearch.xpack.security.authc.ldap.support.SessionFactory.connectionOptions(SessionFactory.java:122)
        at org.elasticsearch.xpack.security.authc.ldap.support.SessionFactory.serverSet(SessionFactory.java:203)
        at org.elasticsearch.xpack.security.authc.ldap.support.SessionFactory.<init>(SessionFactory.java:81)
        at org.elasticsearch.xpack.security.authc.ldap.PoolingSessionFactory.<init>(PoolingSessionFactory.java:62)
        at org.elasticsearch.xpack.security.authc.ldap.ActiveDirectorySessionFactory.<init>(ActiveDirectorySessionFactory.java:68)
        at org.elasticsearch.xpack.security.authc.ldap.LdapRealm.sessionFactory(LdapRealm.java:89)
        at org.elasticsearch.xpack.security.authc.ldap.LdapRealm.<init>(LdapRealm.java:68)
        at org.elasticsearch.xpack.security.authc.InternalRealms.lambda$getFactories$2(InternalRealms.java:113)
        at org.elasticsearch.xpack.security.authc.Realms.initRealms(Realms.java:214)
        at org.elasticsearch.xpack.security.authc.Realms.<init>(Realms.java:76)
        at org.elasticsearch.xpack.security.Security.createComponents(Security.java:480)
        at org.elasticsearch.xpack.security.Security.createComponents(Security.java:412)
        at org.elasticsearch.node.Node.lambda$new$16(Node.java:560)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at org.elasticsearch.node.Node.<init>(Node.java:564)
        at org.elasticsearch.node.Node.<init>(Node.java:278)
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:216)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:216)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:387)
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159)
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:75)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:116)
        at org.elasticsearch.cli.Command.main(Command.java:79)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:81)
```

**Steps to reproduce**:
 1. Pull the new `7.11.0` Docker image
 2. Restart Elasticsearch container

AD settings (working fine on <= `7.10.2`):
```
xpack.security.authc.realms.active_directory.ad.order: 1
xpack.security.authc.realms.active_directory.ad.domain_name: domain
xpack.security.authc.realms.active_directory.ad.url: ldap://ip:389
```

### PR DESCRIPTION
**Pull request by jasontedor**
We inadvertently removed permissions needed by the UnboundID LDAP SDK during a refactoring. This commit returns them to their rightful place.

These permissions are needed in core because we force the class initializers for two classes from the UnboundID LDAP SDK to load while loading the x-pack-core plugin. We have to do this there because x-pack-core depends on the UnboundID LDAP SDK as some realm classes live in x-pack-core.

Without these permissions, Elasticsearch will fail to start if an AD or LDAP realm is configured.

Relates #64743
Closes #68838

### CODE REVIEW

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by jasontedor** [comment]
@elasticmachine update branch

**Comment by tvernum** [comment]
Based on the failure in ci/2
```

Caused by: java.security.AccessControlException: access denied ("java.util.PropertyPermission" "org.apache.xml.security.ignoreLineBreaks" "write")
```

I think we need to keep property permission in security as well as core.

**Comment by jasontedor** [comment]
> Based on the failure in ci/2
> 
> ```
> 
> Caused by: java.security.AccessControlException: access denied ("java.util.PropertyPermission" "org.apache.xml.security.ignoreLineBreaks" "write")
> ```
> 
> I think we need to keep property permission in security as well as core.

I pushed 7f9eb41ceefb0242858b4d92cb07e6ec49c2545e.

**Review by tvernum — APPROVED** [review]
LGTM
I was able to start up a node with both SAML and LDAP configured, and authenticate with an LDAP user.

**Comment by LeeDr** [comment]
I don't see any mention of automated tests for this issue or LDAP auth.  It is possible?  Any plans for it?

**Comment by tvernum** [comment]
I just repeated my test against master (without this fix) and it fails to start, as expected.

**Comment by tvernum** [comment]
> I don't see any mention of automated tests for this issue or LDAP auth.

They're coming, but they'll take time.
We need to get the fix in as quickly as possible so that we can kick off the builds while the testing is taking place.

**Comment by bevano8** [comment]
+ follow

Hey, glad to see this has been raised. Is there any guide on how to fix, or will I need to wait for 7.11.1 release?

**Comment by jasontedor** [comment]
Yes, there isn't a good workaround. We'll release 7.11.1 as fast as we can.

**Pull request merged**
