### PR TITLE
minor typo

### PR DESCRIPTION
**Pull request by geekpete**
lazi should be lazy

### CODE REVIEW

**Comment by nik9000** [comment]
I wouldn't be surprised if the English andalyzer added lazi to the index.
It has a stemmer and they do things like that.

**Comment by geekpete** [comment]
In which case it would be correct and this isn't a typo?

**Comment by geekpete** [comment]
And you're correct:

```
POST _analyze
{
  "analyzer": "english",
  "text": ["The QUICK brown foxes jumped over the lazy dog!"]
}
```
produces this for lazy:

```
    {
      "token": "lazi",
      "start_offset": 38,
      "end_offset": 42,
      "type": "<ALPHANUM>",
      "position": 7
    }
```

Happy to close this PR, sorry for the noise :)

**Comment by nik9000** [comment]
No problem at all! Thanks for opening it. It is a good thing, really!

**Pull request closed without merging**
