### PR TITLE
[ML] Fix language identification bug when multi-languages are present

### PR DESCRIPTION
**Pull request by benwtrent**
Language identification works fairly well when only one language
and script type is present.

But when multiple are present, it can return some unexpected results

Example:

"행 레이블 this is english text obviously and 생성 tom said to test it"

Which appears to a human to be english text (Latin unicode) with Korean
via Hangul unicode is erroneously categorized as Japanese.

It should be categorized as English as it is the dominate language and
script type.

This commit fixes this bug by doing the following:

 - Input text is partitioned into common, continuous, unicode script
   sections
 - Those sections individual language scores are gathered
 - Each score is then weighted according to the number of characters in
   each section
 - The resulting weight scores are transformed into probabilities
 - The final probabilities are the ones returned to the user.

### CODE REVIEW

**Review by droberts195 — COMMENTED** [review]
> * Each score is then weighted according to the number of utf-8 bytes in
each section

I'd like to know why it's the number of UTF-8 bytes and not the number of characters.  The number of characters seems more natural to me.  If I have 60 characters of English and 40 characters of Russian why would I want to give the Russian weight 80 and the English weight 60?

**Comment by benwtrent** [comment]
> I'd like to know why it's the number of UTF-8 bytes and not the number of characters. The number of characters seems more natural to me. If I have 60 characters of English and 40 characters of Russian why would I want to give the Russian weight 80 and the English weight 60

@droberts195 

Mainly because that is how prior art handles this.

I could switch it to character count pretty simply and make sure all the examples continue to pass.

**Comment by droberts195** [comment]
> Mainly because that is how prior art handles this.

OK fair enough. We can copy that then since we copied the rest of the algorithm. Are there any comments in the code we ported that say why it’s bytes mot characters?

**Comment by benwtrent** [comment]
@droberts195 there are zero comments. I am guessing because the rest of the code works according to UTF-8 bytes. In Java, we more robust text handling. 

I switched it to string length and the tests continued to pass. It makes sense to use string length as usually languages with their own special unicode class have higher confidence than those without. Artificially increasing that confidence by weighing them according to byte length and not string length is unintuitive.

**Review by droberts195 — APPROVED** [review]
LGTM

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Comment by joshdevins** [comment]
See: https://github.com/elastic/sdh-ml/issues/257

**Comment by hendrikmuhs** [comment]
Some conceptual comment. They don't target this PR, but something to think about longer term.

> It should be categorized as English as it is the dominate language and script type.

This depends on the use case, it's not that easy:

- english is a common language and the text you identify as english are often just proper names. You find lots of mixed CJK/English texts like this, I would not classify them as english.
- english is a simple language. If a language identification is used for choosing the tokenizer, it is better to choose the language specific tokenizer. Usually all of them are able to space tokenize the english parts, but vice versa the english tokenizer can not decompound CJK, german, finish, etc.
  - note, this might just be something for the user to be taken care of, all probabilities are returned, so you can choose the tokenizer e.g. from the 2nd language, fortunately we return not just 1 result

>     * Each score is then weighted according to the number of characters in
>       each section

This assumption does not work well for CJK, e.g. '棪' means 'tree'. CJK tends to be shorter in characters (but has a larger alphabet).

**Comment by droberts195** [comment]
> This assumption does not work well for CJK, e.g. '棪' means 'tree'. CJK tends to be shorter in characters (but has a larger alphabet).

This is what I was getting at in:

> [Is the byte count a sneaky heuristic for saying each Chinese character embeds more information than a Roman alphabet character?](https://github.com/elastic/elasticsearch/pull/80675#discussion_r747781054)

But if that's what we end up doing that then we should have a comment saying _why_ we're doing it, because it would be very much a crude heuristic rather than a scientific algorithm.

**Comment by benwtrent** [comment]
> english is a common language and the text you identify as english are often just proper names.

Shorter contiguous sequences of the same unicode script are weighed lower than longer ones. 

> This assumption does not work well for CJK, e.g. '棪' means 'tree'. CJK tends to be shorter in characters (but has a larger alphabet).

Very true, I switched the algorithm to use character length, not byte length.

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Pull request merged**
