### PR TITLE
[rest spec] fill in documentation links for security.{put,delete}_privileges

### PR DESCRIPTION
**Pull request by jbudz**
There's a minor nitpick with the url suffix, privilege(s)?.html happy to update the links if we want.

### CODE REVIEW

**Review by idjevm — APPROVED** [review]

**Review by tvernum — APPROVED** [review]
LGTM

**Comment by jbudz** [comment]
Anything else needed here?  I can merge but not too familiar with the process in this repo

**Comment by jbudz** [comment]
@elasticmachine merge upstream

**Comment by pcsanwald** [comment]
@jbudz as long as you've got a green build, feel free to merge whenever you like. let us know if you need help backporting (can use a PR or commit directly, up to you)

**Comment by jbudz** [comment]
7.x/7.7: 8fa4a40

**Pull request merged**
