### PR TITLE
[WIP] Compile yml tests to classes

### PR DESCRIPTION
**Pull request by probakowski**
This PR provides gradle task for compiling yml REST tests to classes. 
It works by copying whole yml content to test class and creating test methods (with ```@Test``` annotation) for each test inside (identified by line starting with "), infrastructure for actually running test is the same as before.
Content of yml is split to 64k chunks and stored in inner classes to work around hard limit of java class size.
This is initial and still WIP version to discuss solution

Reletes to #47793

### CODE REVIEW

**Comment by rjernst** [comment]
Thanks for picking this up @probakowski! I wonder if it would be simpler to generate source files instead of class. These would be easier for most developers on the team to understand, and debug the output? I'm not opposed to generating class files like this directly, but I wonder if the source files are a better alternative, and would appreciate the thoughts of others, especially @jdconrad @atorok and @mark-vieira.

**Comment by rjernst** [comment]
I also think we should generate one test suite (ie class) per rest test file. This would alleviate the problem of too large of a class file.

**Comment by mark-vieira** [comment]
I tend to agree with @rjernst that source generation might be a better route. The main issue I have with bytecode generation is it's impossible to debug, and any errors produce effectively useless stacktraces. 

That said, while reading #47793 the goals here are very fuzzy. I'd really prefer us to sit down and have a think about exactly what we want to achieve, what the current issues with YAML tests are, and how something like this might solve those problems. It's not completely clear to me what the big advantages of this kind of approach is. We should take some time to explicitly state the problems we want to solve here. There might be multiple ways to attack those problems.

**Comment by probakowski** [comment]
I agree that generating sources could be easier to debug but it comes with few caveats:

-  navigating to source is more tricky (it navigates to generated java file instead of test method in yml file)
- java compiler is way more strict than JVM when it comes to naming classes and methods so it requires more preprocessing + it ends up further from yml making it somewhat harder to connect test failing to place in yml file
- java compiler need access to superclass so we either need to setup source sets correctly for those generated sources or make them somehow available to [getSystemJavaCompiler](https://docs.oracle.com/javase/6/docs/api/javax/tools/ToolProvider.html) as proposed by @atorok in [#47793](https://github.com/elastic/elasticsearch/issues/47793#issuecomment-542189212)
- you can't really write UTs testing that generated classes actually do what they are suppose to do, with current code you just load generated class with custom classloader and you are done
- I really don't like heavy string work in Java :wink: 

I also think that this code will be rather "write and forget", I don't expect it to be modified often. Generated source make more sense for me if they are meant to be used in other java files, like model generated from xml and the referenced from application code.

@mark-vieira I think main point for original issue was to have "real" tests that can be easily picked up by Gradle test runner from classpath. This would remove need for tasks that copy yml files around (```copyRestSpec```) and need for custom test classes that only serves as loaders/runners for yml files (like [IcuClientYamlTestSuiteIT](https://github.com/elastic/elasticsearch/blob/master/plugins/analysis-icu/src/test/java/org/elasticsearch/index/analysis/IcuClientYamlTestSuiteIT.java))

> I also think we should generate one test suite (ie class) per rest test file

@rjernst you mean per .yml file? The code does exactly that but we have some surprisingly large yml files for example in docs with `huge_twitter` setup, which results in over 200kB file

**Comment by rjernst** [comment]
> we have some surprisingly large yml files for example in docs with huge_twitter

Can you point to a specific file yml file to look at?

**Comment by mark-vieira** [comment]
> @mark-vieira I think main point for original issue was to have "real" tests that can be easily picked up by Gradle test runner from classpath. This would remove need for tasks that copy yml files around (copyRestSpec) and need for custom test classes that only serves as loaders/runners for yml files (like IcuClientYamlTestSuiteIT)

I'm struggling to see how this is strong motivation for generating bytecode, and introducing another layer of "magic" in a test framework this is already hard to reason about.

Also we **really** need to start focusing on how this stuff affects **users**. That is, the folks authoring, executing, and debugging these tests. Everything that has been discussed has been about build internals and implementation details. How does this help Elasticsearch developers? How does this provide for a best experience WRT to these kinds of tests? I doubt folks care about classpath handling and extra file copies.

**Comment by probakowski** [comment]
@rjernst sure, check out ```reference/cat/indices.yml``` ```indices/rollover-index.yml``` and ```reference/getting-started.yml``` generated by ```:docs:buildRestTests```

@mark-vieira these are valid points and I'm open for discussion. I can see at least some features for users debugging these tests, for example if you run this from IDE you can go straight to failing yml file by simply clicking like you would for any other test, without navigating through files. We can improve on that to point to specific ```do``` section etc.

**Comment by atorok** [comment]
I started  writing my reply on the linked issue before the discussion here took off
to have it all in a single place, please also check the issue and maybe continue the discussion there ? 
I agree with @mark-vieira that we should be clear on what we want to achieve, 
I think we all have some idea, just have to make sure we are on the same page.

**Comment by mark-vieira** [comment]
I find GitHub issues to be a generally terrible tool for this kind of thing. Here's what I would suggest instead:

1. Start a document for us to collect our ideas and iterate on (I like Google Docs for this, but it could be something else).
2. Enumerate the problems we have with the current YML testing framework. Focus on things from a *user* perspective rather than technical implementation. What about the current experience sucks for users.
3. Enumerate the goals of a new or improved framework. Don't limit yourself to things for which you can envision a technical solution for. Simply, if all things were possible, what would you like this framework to do, how _should_ it work?
4. Share this document with the broader developer audience. This is *really* important. Since these changes affect everyone working with these tests, we should get feedback on these kinds of changes. This includes anyone that interacts with YML-based tests, including docs folks.
5. Once we have a good handle on what the problems we want to solve are, _then_ we should start creating issues to address these things, in which we can start talking about _how_ we might implement those solutions.

I can certainly get such a document _started_ but I'm probably not in the best position to do so since I don't work directly with the YML tests on a regular basis.

**Comment by rjernst** [comment]
@probakowski Thanks for your work here. Given the previous feedback here I don't foresee us moving forward with this approach. I'm going to close this for now but we can always revive the branch if anything changes in our approach.

**Pull request closed without merging**
