### PR TITLE
Remove much ceremony from parsing client yaml test suites

### PR DESCRIPTION
**Pull request by nik9000**
* Remove a checked exception, replacing it with `ParsingException`.
* Remove all Parser classes for the yaml sections, replacing them with static methods.
* Remove `ClientYamlTestFragmentParser`. Isn't used any more.
* Remove `ClientYamlTestSuiteParseContext`, replacing it with some static utility methods.

I did not rewrite the parsers using `ObjectParser` because I don't think it is worth it right now.

### CODE REVIEW

**Comment by nik9000** [comment]
Another cleanup PR that came from #22003. @rjernst, @imotov, @javanna, @martijnvg, or anyone else, want to have a look?

**Review by javanna — APPROVED** [review]
LGTM assuming that tests run, all the parsing code has been copied over to their corresponding new static methods unchanged, and that all the parsing tests have been kept around as well. It is hard to double check all that in the PR, review based on trust :)

**Comment by nik9000** [comment]
> LGTM assuming that tests run, all the parsing code has been copied over to their corresponding new static methods unchanged, and that all the parsing tests have been kept around as well.

Yup, that is pretty much what I did. Thanks for the review! I'll rerun the tests and if they pass again I'll merge.

**Comment by nik9000** [comment]
Thanks for reviewing @javanna!

master: f5f2149ff2c66cbe1d09c57d34fd56ae6d298272
5.x: backporting

**Pull request merged**
