### PR TITLE
Format `AbstractFilteringTestCase`

### PR DESCRIPTION
**Pull request by nik9000**
`AbstractFilteringTestCase` had a ton of carefully formatted
`XContentBuilder` calls that would have been totally unreadable after
the formatter worked its magic. So I formatted a bunch of them by hand
and extracted the rest to json files.

### CODE REVIEW

**Comment by nik9000** [comment]
I tried to extract the json to a file if it was about half a page or so. I figured casual readers wouldn't read a half page of json and an interested reader would be willing to look up the file.

**Comment by nik9000** [comment]
I also added one of the direct subclasses of `AbstractFilteringTestCase` which has a bunch of careful formatting. Like before I manually formatted stuff and then ran formatter to make sure it didn't make a huge mes.

**Review by tlrx — APPROVED** [review]
LGTM - thanks for doing this Nik!

**Comment by nik9000** [comment]
> LGTM - thanks for doing this Nik!

I'm happy to do it! I ran the formatter on the file just to see what would happen. It was made me so very very sad.

**Comment by nik9000** [comment]
> To backport manually run `backport --upstream elastic/elasticsearch --pr 77217`

With great respect, I will do it my own way.

**Comment by nik9000** [comment]
Backport is #77254. Made with good old `git cherry-pick`

**Pull request merged**
