### PR TITLE
Utility methods to add and remove backing indices from data streams

### PR DESCRIPTION
**Pull request by danhermann**
Relates to #75852

### CODE REVIEW

**Comment by danhermann** [comment]
@elasticmachine run elasticsearch-ci/packaging-tests-unix-sample

**Comment by danhermann** [comment]
@elasticmachine update branch

**Review by danhermann — COMMENTED** [review]
Packaging test failure is unrelated.

**Review by martijnvg — APPROVED** [review]
LGTM

**Comment by danhermann** [comment]
Thanks, @martijnvg!

**Pull request merged**
