### PR TITLE
Added quotes around %JAVA% usages to handle spaces in path

### PR DESCRIPTION
**Pull request by seal-mt**
If the java installation path on windows contains spaces (e.g. `c:\Program Files`) and `%JAVA_HOME%` isn't set the batch scripts for startup will fail, because file tests and starting java use only the part before the first space instead of the whole path. I added double quotes around all occurrences of `%JAVA%` where quotes are necessary to handle spaces.

### CODE REVIEW

**Comment by rjernst** [comment]
@seal-mt We have tests for spaces in paths. Can you give a reproduction of this (ie show what concrete paths you have for java which cause the current code to break)?

**Comment by seal-mt** [comment]
@rjernst I installed `OpenJDK 1.8.0_131-1` from https://github.com/ojdkbuild/ojdkbuild. The msi installs java by default into `C:\Program Files\ojdkbuild\java-1.8.0-openjdk-1.8.0.131-1`. After installing `PATH` is changed, but `JAVA_HOME` is not set.
After that downloaded and unzipped `elasticsearch-5.4.1.zip`. When now calling `elasticsearch.bat` from command line the java executable is correct found in `elasticsearch.in.bat` in line 6 (`FOR %%I IN ...`), but the comparison in line 9 (`IF NOT EXIST %JAVA%`) fails until i wrap `%JAVA%` in double quotes.
The next errors occurred when calling java for version checking and running elasticsearch, so in the PR i changed usage of `%JAVA%` throughout the scripts.
Tested on a Windows Server 2012 R2 System.

I hope this helps.

**Comment by rjernst** [comment]
> After installing PATH is changed, but JAVA_HOME is not set

I missed this before. I think the underlying problem is with the loop that finds java when java home is not set.

```
FOR %%I IN (java.exe) DO set JAVA=%%~$PATH:I
```

That line needs to be quoted correctly to handle spaces. Then everything else should work.

**Comment by jasontedor** [comment]
That's correct @rjernst, and all that is needed here is quotes for that case. I want to get this fixed in 5.5.0 which means I elected to push a fix directly:

- master: dc9b67461f239b9b77fc6b497488d310f2048ef5
- 5.x: 242cf8eebc75bbf6faddb376c2ed9070d4d1d5ae
- 5.5: 47f0df73fdf202c80acffddbf60b2246ed62991e

Thanks so much for the report @seal-mt, we would not have caught this one without your [comment above](https://github.com/elastic/elasticsearch/pull/23822#issuecomment-308473106).

**Pull request closed without merging**
