### PR TITLE
Fix NPE in RestPluginsAction

### PR DESCRIPTION
**Pull request by wangkhc**
Fix NPE in _cat/plugins api 

Relates #45321

### CODE REVIEW

**Comment by wangkhc** [comment]
@shoulian-zhao #45321 may be fixed by this PR, please help keep notice, thank you :)

**Comment by wangkhc** [comment]
@dakrone @dadoonet TBR, thanks :)

**Comment by wangkhc** [comment]
TBR :) 
@matriv @dakrone @henningandersen @debadair @dadoonet

**Comment by dakrone** [comment]
@elasticmachine ok to test

**Comment by wangkhc** [comment]
@dakrone It's really weird since I didn't update other logic, still there is some bwc tests failed. Is there any other chance that these test failure are caused by other commits?

**Comment by wangkhc** [comment]
@elasticmachine update branch

**Comment by wangkhc** [comment]
@dakrone Tests are all passed, is there anything further I can do? :)

**Comment by wangkhc** [comment]
@dakrone Is there anything else need me to do before merging this PR? :)

**Review by dakrone — APPROVED** [review]
LGTM, I'll merge this in and backport it.

**Pull request merged**
