### PR TITLE
Typo 'Elastisearch' -> 'Elasticsearch'

### PR DESCRIPTION
**Pull request by maxg203**
Quick typo fix

### CODE REVIEW

**Comment by karmi** [comment]
Hi @maxg203, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/elasticsearch/pull/23633.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by qwerty4030** [comment]
Here are some more instances of the same typo: https://github.com/elastic/elasticsearch/search?utf8=%E2%9C%93&q=Elastisearch

**Comment by maxg203** [comment]
@karmi That is a good point, I added that email as well. Everything should be good now.

**Comment by maxg203** [comment]
@qwerty4030 Thank you, I just updated this pull request to reflect those extra instances that you found.

**Comment by nik9000** [comment]
Thanks @maxg203 and @qwerty4030! I've merged and backported to 5.x.

**Pull request merged**
