### PR TITLE
Default _cat verbose to false

### LINKED ISSUE #13156: _cat should not default to verbose
https://github.com/elastic/elasticsearch/pull/8927 changed _cat apis to be verbose by default in ES 2.0, based on motivation from https://github.com/elastic/elasticsearch/issues/8922.

The motivation for the change was easing the cluster state inspection experience for users unfamiliar with the command line and ES docs. A noble goal. I certainly empathize with these users.

The opposition argued that experience is quickly gained, and experienced users want the non-verbose behavior, such that over time the majority of users will become frustrated with the new, verbose default.

Despite my empathy for new users, I 100% agree with the opposition. I'd also like to point out that this is an api specifically designed for scripting (see its [introduction](https://www.elastic.co/blog/introducing-cat-api)) and every script that uses it will break in unpredictable ways when the behavior changes. Changing the default will generate a lot of unpleasant work and delay upgrades to 2.0.

The argument that every script should have used `v=false` to protect against future breakage is particularly galling, since this usage was undocumented. It demonstrates a cavalier attitude toward breaking changes that doesn't inspire trust.

Breaking changes, especially breaking changes in APIs (_cat is definitely an API) should only be considered when the original behavior was fundamentally broken. That isn't the case here.

A command-line, user-friendly state inspection tool would be very useful, but _cat is not that tool. Wow your users with a top-like dashboard shipped with the distribution. Don't discourage them by changing the _cat default.

/cc @dakrone @drewr @TwP

### PR DESCRIPTION
**Pull request by nik9000**
https://github.com/elastic/elasticsearch/pull/8927 changed the `_cat` APIs to default to verbose.  This was released in 2.0.0-beta1, but then we decided to revert to previous behaviour.

Closes #13156

### CODE REVIEW

**Comment by nik9000** [comment]
I'm still running the tests for this. Its a one line Java change but its far reaching.

Note: this reverts a breaking API change. Its now no longer broken.

**Comment by jasontedor** [comment]
LGTM.

**Comment by nik9000** [comment]
Merged to master.

Rerunning tests in 2.0 and will merge there once they pass.

**Comment by grantr** [comment]
:sparkles: Thanks @nik9000!

**Pull request merged**
