### PR TITLE
Simplify JVM options

### PR DESCRIPTION
**Pull request by jasontedor**
This commit simplifies the default JVM options that ship with
Elasticsearch. In particular, expert settings that were previously
configurable via environment variables have been removed from the
default configuration file. Further, the heap size settings have been
moved to the top of the file with a clearer message that is in
concordance with their importance.

Relates #17675

### CODE REVIEW

**Comment by clintongormley** [comment]
@jasontedor better, but I'd go further to make it really obvious:

    ## JVM configuration


    ####################################################
    ## IMPORTANT: JVM heap size                    
    ####################################################
    ##                                                  
    ##  You should always set the min and max JVM heap  
    ##  size to the same value.  For example, to set    
    ##  the heap to 4GB, set:                           
    ##                                                  
    ##  -Xms4g                                          
    ##  -Xmx4g                                          
    ##                                                  
    ## See https://www.elastic.co/guide/en/elasticsearch/reference/current/heap-size.html
    ## for more information
    ##
    ####################################################

    # Xms represents the initial size of total heap space
    # Xmx represents the maximum size of total heap space

    -Xms${heap.min}
    -Xmx${heap.max}


    ####################################################
    ## Expert settings
    ####################################################
    ##
    ## All settings below this section are considered 
    ## expert settings.  Don't tamper with them unless
    ## you understand what you are doing
    ##
    ####################################################

**Comment by jasontedor** [comment]
@clintongormley Thanks. I pushed 04e77242faf42cfd1e1091dc94c3a4dc9fbf66d5.

**Comment by jpountz** [comment]
LGTM

**Comment by jasontedor** [comment]
Thanks @clintongormley and @jpountz!

**Pull request closed without merging**
