### PR TITLE
Fix template equals when mappings are wrapped

### PR DESCRIPTION
**Pull request by weizijun**
When create template v2. mappings will add _doc. This will cause the created template to be inconsistent with the queried template.

In template class, add mappingsEquals method, to deal with this case.

repreduced:
MetadataIndexTemplateServiceTests.testAddComponentTemplate
when mappings are not null, the case will failed.

```
        Template template = new Template(
            Settings.builder().build(),
            new CompressedXContent("{\"properties\":{\"@timestamp\":{\"type\":\"date\"}}}"),
            ComponentTemplateTests.randomAliases()
        );
        ComponentTemplate componentTemplate = new ComponentTemplate(template, 1L, new HashMap<>());
```

### CODE REVIEW

**Comment by weizijun** [comment]
hi, @leehinman , @martijnvg , can you help to review this PR?

**Comment by dakrone** [comment]
@elasticmachine ok to test

**Comment by dakrone** [comment]
@elasticmachine update branch

**Review by dakrone — APPROVED** [review]
LGTM

**Comment by dakrone** [comment]
@elasticmachine update branch

**Comment by dakrone** [comment]
Thanks for fixing this @weizijun! I'll backport this to 7.x.

**Pull request merged**
