### PR TITLE
Migrate `.tasks` to be managed automatically

### PR DESCRIPTION
**Pull request by pugnascotia**
Re-apply changes from 0c9b9c1cbd7, which migrates the `.tasks` system index
to be managed automatically by the system indices infrastructure.

Changes went into #67114 that, I hope, will avoid the problems we saw before
in the BWC tests in CI.

### CODE REVIEW

**Comment by pugnascotia** [comment]
@elasticmachine test this please

**Comment by pugnascotia** [comment]
@elasticmachine test this please, I want it to fail!

**Comment by pugnascotia** [comment]
@elasticmachine test this please, I want it to fail!

**Comment by pugnascotia** [comment]
@elasticmachine test this please, I want it to fail!

**Comment by pugnascotia** [comment]
@elasticmachine test this please, I want it to fail!

**Comment by mark-vieira** [comment]
@elasticmachine update branch

**Review by jaymode — APPROVED** [review]
LGTM

**Pull request merged**
