### PR TITLE
Remove "force" version type

### LINKED ISSUE #19769: Remove version type `FORCE`
The version type `FORCE` was added as an expert option to allow people to roll back changes in the external version use case where they have made mistakes in their synchronization logic.

It's a very dangerous operation as it forgoes all concurrency guarantees and may leave replicas and primaries out of sync. In hind sight I think we should not have added it and the problem goes far enough to warrant it's removal.

Note that long term, we can support this kind of thing when we move the replication logic to rely on sequence numbers for concurrency.

See for example: https://github.com/elastic/elasticsearch/issues/19692

### PR DESCRIPTION
**Pull request by ywelsch**
It's been deprecated long ago and can be removed.

Relates to #20377

Closes #19769

### CODE REVIEW

**Review by dnhatn — APPROVED** [review]
LGTM

**Comment by Mpdreamz** [comment]
Note `force` was removed from the java enum and therefore should be removed from all the rest-spec json files documenting `version_type`.

cc @elastic/es-clients 

This is a good highlight for the API versioning discussion, ideally this is only removed in major versions. cc @jakelandis

**Comment by ywelsch** [comment]
> This is a good highlight for the API versioning discussion, ideally this is only removed in major versions.

@Mpdreamz note that this parameter had been rejected already since the previous major. I  consider this purely a code clean-up. The only behavioral change here is that a more generic  exception message is provided if someone specifies force version type. The question here rather  is: When should the  REST spec have been adapted? If the system always rejects a  given parameter,  is there a point to keep that parameter in the REST spec?

**Comment by russcam** [comment]
> When should the REST spec have been adapted?

The REST API spec should have been adapted when the version type was deprecated in the server source code; if deprecation results in a validation error, this sounds like good cause to remove from the spec if the deprecation is for a major release, or to be signalled in the REST API spec as deprecated for any other release.

> If the system always rejects a given parameter, is there a point to keep that parameter in the REST spec?

A lot of the Elasticsearch clients generate a large amount of their API surface from the REST API specs, including API params. For those params that constrain the accepted values to a known set, a client may generate code to uphold this constraint, such as an enum of values.

When the REST API spec changes in ways that would violate semantic versioning e.g. removing params in a minor version, removing an accepted value for a param in a minor, etc., it has ramifications for client generation; for statically typed languages like Java<sup>1</sup>, C#, Go and Rust, such a change in the REST API spec can manifest as an API breaking change in the client. Since clients also follow semantic versioning<sup>2</sup> in order to provide guarantees to their consumers, API breaking changes should not happen in minors or patches, and if they do, it results in each client having to independently patch their code generation process to deal with them.

The REST API specs are currently the best specification for the REST API surface of Elasticsearch that we have to work with, and the best representation of the external contract that clients, products and integrations use to communicate with Elasticsearch. I think it's crucially important that it follows the same semantic versioning rigour that I know the Elasticsearch team puts into the public API surface of the server side code.

<sup>1</sup> - _I don't know how the Java client is written, whether it generates the API surface from the REST API specs, and to what extent the API is typed_
<sup>2</sup> - _The extent to which a client follows semantic versioning is language ecosystem dependent to some degree, but the vast majority do. Some clients may provide other guarantees around API changes, such as binary compatibility across major versions._

**Comment by ywelsch** [comment]
Thanks for the explanations @russcam. If this is critical for client development, could we put safeguards in place that check API compatibility with prior versions of the spec, to avoid problems like this in the future?

**Comment by russcam** [comment]
Safeguards would be very welcome! It could start with something more simple such as a diff of *.json files in a PR for changed files in

- /rest-api-spec/src/main/resources/rest-api-spec/api
- /x-pack/plugin/src/test/resources/rest-api-spec/api

and flag when a change is breaking between two known versions.

There is an initiative to [record requests and responses of YAML tests](https://github.com/elastic/clients-flight-recorder) to notify of changes in structure which should also help, but because it is detached from server side changes, it's more "after the fact" rather than flagging when a change will be merged into a main branch.

**Pull request merged**
