### PR TITLE
Add missing double quotes to Index API response example

### PR DESCRIPTION
**Pull request by tatsuya**
Actually all 5.x documents are like this. But I feel it's better to have the correct one at least on the latest.

### CODE REVIEW

**Comment by tvernum** [comment]
@elasticmachine ok to test

**Comment by mayya-sharipova** [comment]
@tatsuyaoiw your change LGTM (looks good to me). Would you like in this PR add corrections to other documents as well?

**Comment by tatsuyaoiw** [comment]
@mayya-sharipova No, only this one is enough for me. I wonder if there's any efficient way to apply the same change to different branches (5.5, 5.4....5.0) though...

**Comment by mayya-sharipova** [comment]
@tatsuyaoiw Thank for your contribution, I will merge this PR. We can backport the changes to other branches, but I am not sure if we are going to make new releases of these branches

**Pull request merged**
