### PR TITLE
docs: fix numbering in restore-snapshot.asciidoc

### PR DESCRIPTION
**Pull request by fbaligand**
Fix numbering in "Restore an entire cluster" section. 
Remove "3." for "Universal Profiling" and add "3." just before "If you use Elasticsearch security features"

### CODE REVIEW

**Comment by abdonpijpelink** [comment]
@elasticsearchmachine test this please

**Review by abdonpijpelink — APPROVED** [review]
Thank you for fixing this @fbaligand !

I've pushed a small change that keeps the `restore-create-file-realm-user` ID (it's used to link to this bullet elsewhere), fixes some asciidoc complex list quirks, and rebases the PR onto the `main` branch (so your change will also appear in future versions of the documentation).

**Comment by abdonpijpelink** [comment]
@elasticsearchmachine test this please

**Comment by fbaligand** [comment]
Hi @abdonpijpelink,

Thanks for the fix on my fix ;)
And thanks for the merge!

**Pull request merged**
