### PR TITLE
Extend probe handshake timeout if security enabled

### PR DESCRIPTION
**Pull request by DaveCTurner**
Today the discovery phase has a short 1-second timeout for handshaking
with a remote node after connecting, which allows it to quickly move on
and retry in the case of connecting to something that doesn't respond
straight away (e.g. it isn't an Elasticsearch node).

If transport security is enabled then our handshake timeout applies to
the TLS handshake followed by the Elasticsearch handshake. If the TLS
handshake alone takes over a second then the whole handshake times out
with a `ConnectTransportException`, but this does not tell us which of
the two individual handshakes took so long.

TLS handshakes have their own 10-second timeout, which if reached yields
a `SslHandshakeTimeoutException` that allows us to distinguish a problem
at the TLS level from one at the Elasticsearch level. Therfore this
commit extends the discovery handshake timeout by 10 seconds if security
is enabled.

### CODE REVIEW

**Review by original-brownbear — APPROVED** [review]
LGTM :) I wonder if we should generally up the timeout here a little. 1s is awfully short for a node whose transport threads are already under pressure isn't it?

**Comment by DaveCTurner** [comment]
I contemplated that too, but a transport thread stuck for >1s would be a bug :wink:

Not sure really. If it takes us 30+ seconds to decide that we're probably not talking to another Elasticsearch node, is it so bad? I guess these numbers were chosen before #42636 happened and we didn't want to block one thread per discovery address for tens of seconds, but now we're async I don't think it matters any more.

**Comment by original-brownbear** [comment]
>  If it takes us 30+ seconds to decide that we're probably not talking to another Elasticsearch node, is it so bad? I guess these numbers were chosen before #42636 happened and we didn't want to block one thread per discovery address for tens of seconds, but now we're async I don't think it matters any more.

++ dropping within a second instead of within 30s to no real downsides. Plus, upping the timeout makes issues with the handshake a bit easier to debug. 

> I contemplated that too, but a transport thread stuck for >1s would be a bug 

Sure, but we only WARN log after burning though 5s of transport thread time also :) There's always going to be GC and random hiccups and having a limit that accounts for that seems like it would at least reduce the noise from these timeouts when other things are already slow.

**Comment by DaveCTurner** [comment]
Ok closing this in favour of #68059.

**Pull request closed without merging**
