### PR TITLE
Fix shell retry generator for shells other than bash

### LINKED ISSUE #77414: `retry_wget` appears to retry on success?
[This build](https://gradle-enterprise.elastic.co/s/z27y5iradm6ck/console-log?task=:distribution:docker:buildDockerImage) failed thusly:

```
|  ---> f83d1a60c1c3
	| Step 8/44 : RUN function retry_wget() {       local URL="$1" ;       local DEST="$2" ;       for iter in {1..10}; do         wget "$URL" -O "$DEST" &&         exit_code=0 && break ||           exit_code=$? && echo "wget error: retry $iter in 10s" && sleep 10;       done;       return $exit_code ;     } ;     retry_wget "https://daniel.haxx.se/mykey.asc" "curl-gpg.pub" &&     retry_wget "${TARBALL_URL}.asc" "${TARBALL_PATH}.asc" &&     retry_wget "${TARBALL_URL}" "${TARBALL_PATH}"
	|  ---> Running in 9083154b848f
	| Connecting to daniel.haxx.se (151.101.2.49:443)
	| saving to 'curl-gpg.pub'
	| curl-gpg.pub         100% |********************************|  4741  0:00:00 ETA
	| 'curl-gpg.pub' saved
	| Connecting to curl.haxx.se (151.101.2.49:443)
	| wget: can't connect to remote host (151.101.2.49): Operation timed out
	| wget error: retry {1..10} in 10s
	| The command '/bin/sh -c function retry_wget() {       local URL="$1" ;       local DEST="$2" ;       for iter in {1..10}; do         wget "$URL" -O "$DEST" &&         exit_code=0 && break ||           exit_code=$? && echo "wget error: retry $iter in 10s" && sleep 10;       done;       return $exit_code ;     } ;     retry_wget "https://daniel.haxx.se/mykey.asc" "curl-gpg.pub" &&     retry_wget "${TARBALL_URL}.asc" "${TARBALL_PATH}.asc" &&     retry_wget "${TARBALL_URL}" "${TARBALL_PATH}"' returned a non-zero code: 1	%
```

Seems suspicious, we apparently succeeded to get the key but then tried a second time and it failed which failed the build?

Relates #63615

### PR DESCRIPTION
**Pull request by pugnascotia**
Closes #77414.

The generated shell logic in `ShellRetry` doesn't work in more basic shells, so instead
of using the `{1..10}` construct, expand the sequence.

### CODE REVIEW

**Comment by pugnascotia** [comment]
@elasticmachine run elasticsearch-ci/part-2

**Review by mark-vieira — APPROVED** [review]
LGTM

**Comment by pugnascotia** [comment]
@elasticmachine update branch

**Comment by pugnascotia** [comment]
I took out the `curl` upgrade because for some reason, the binary that we build wouldn't execute.

**Pull request merged**
