### PR TITLE
Remove jsonp support and associated tests

### LINKED ISSUE #9108: Remove JSONP
We now have comprehensive CORS support.  JSONP has been disabled by default since 1.3.  We should remove JSONP support completely.

### PR DESCRIPTION
**Pull request by reuben-sutton**
Tests are all passing, obviously except the two jsonp related ones which I removed.

Closes #9108

### CODE REVIEW

**Comment by reuben-sutton** [comment]
@clintongormley could you review please?

**Comment by clintongormley** [comment]
Thanks for the PR @reuben-sutton - I've marked it for review.

**Comment by s1monw** [comment]
@reuben-sutton this PR looks pretty good to me, can you bring it up-to-date, I'd love to merge it!

**Comment by reuben-sutton** [comment]
Hi @s1monw, rebased it now, sorry about the delay!

**Comment by s1monw** [comment]
LGTM @kimchy do you wanna take another look?

**Comment by s1monw** [comment]
@reuben-sutton could you do me a favor and add a line to `docs/reference/migration/migrate_2_0.asciidoc` saying that it's not supported anymore.

**Comment by kimchy** [comment]
LGTM

**Comment by reuben-sutton** [comment]
Added it @s1monw

**Comment by s1monw** [comment]
merged thanks!!

**Pull request merged**
