### PR TITLE
Fix leaking searcher when shards are removed or relocated

### LINKED ISSUE #52021: [CI] Multiple tests failing with "some shards are still open" error
This has failed 4 times already today:

```
:modules:reindex:test » org.elasticsearch.index.reindex.ReindexFailureTests » classMethod (0.007s)
Some shards are still open after the threadpool terminated. Something is leaking index readers or store references.
java.lang.IllegalStateException: Some shards are still open after the threadpool terminated. Something is leaking index readers or store references.Open stacktrace
```

Here's are some build scans. Seems to be isolated to `7.x` for now:

https://gradle-enterprise.elastic.co/s/gcnoaw5pepki2/tests/5nfchac5yggnq-rjw76l2zc7kn2
https://gradle-enterprise.elastic.co/s/bqddtyap54zai/tests/5nfchac5yggnq-rjw76l2zc7kn2
https://gradle-enterprise.elastic.co/s/crutz4g7pzhay/tests/5nfchac5yggnq-rjw76l2zc7kn2
https://gradle-enterprise.elastic.co/s/zkfh4z2lj67g2/tests/5nfchac5yggnq-rjw76l2zc7kn2

### PR DESCRIPTION
**Pull request by dnhatn**
We might leak a searcher if the target shard is removed (i.e., its index is deleted) or relocated while we are [creating](https://github.com/elastic/elasticsearch/blob/59368968b698652352be1bb2a60d5a357a01b978/server/src/main/java/org/elasticsearch/search/SearchService.java#L699) a SearchContext from a SearchRewriteContext.

Relates #51708 
Closes #52021 

I labelled this non-issue for an unreleased bug introduced in #51708.

### CODE REVIEW

**Comment by mark-vieira** [comment]
Since this addresses the failures I mentioned in #52021  then we should probably revert the mute I did as part of that in 16afbf91bb8aeb22933d21fe1012e2332468977c in this PR while we're at it.

**Comment by dnhatn** [comment]
@mark-vieira Thanks for the head-up. Since you muted this suite on 7.x only, I will unmute it when backporting this PR.

**Review by jpountz — APPROVED** [review]
LGTM, maybe also update the comment in the finally block so that it doesn't look like the DefaultSearchContext constructor is the only call that may fail?

**Comment by dnhatn** [comment]
> maybe also update the comment in the finally block so that it doesn't look like the DefaultSearchContext constructor is the only call that may fail

++. I've adjusted the comment in https://github.com/elastic/elasticsearch/pull/52099/commits/ad5fe76c69633199fb7acac9e3d9ee7fbc6352a7. Thank you for reviewing, Adrien.

**Comment by mark-vieira** [comment]
@dnhatn I think this needs to be backported to `7.6` as well. I just encountered this failure:

https://gradle-enterprise.elastic.co/s/zhx3wtz3etvxe/tests/kyv2y2z3r4v7m-ncgrhme3gg7g4

**Comment by dnhatn** [comment]
@mark-vieira This PR fixed a bug introduced in https://github.com/elastic/elasticsearch/pull/51708, which got into only 8.0 and 7.7. Anyway, I will take a look at the failure that you linked. Thank you for the ping.

**Pull request merged**
