### PR TITLE
Remove and forbid use of com.google.common.collect.EvictingQueue

### PR DESCRIPTION
**Pull request by jasontedor**
This commit removes and now forbids all uses of
com.google.common.collect.EvictingQueue across the codebase. This is
one of the few remaining steps in the eventual removal of Guava as a
dependency.

Relates #13224

### CODE REVIEW

**Comment by jpountz** [comment]
Wouldn't it be better to change our pipeline aggs to use a regular queue and evict explicitly instead of adding this new queue impl? This would avoid this new abstraction.

**Comment by jasontedor** [comment]
@jpountz I took a look at whether or not manually managing evictions in the pipeline aggregations code would simplify things or not, and frankly I think it doesn't and I think it would lead to code that is harder to maintain. In this case, I think that this (relatively simple) abstraction simplifies the pipeline aggregations code (so that there isn't the noise of manually managing the evictions there) and makes it more maintainable (future maintainers have to take care to properly manage any changes to the add logic). I would be interested in seeing if you have a simple and maintainable way that I'm not seeing?

**Comment by jpountz** [comment]
I haven't really tried or even looked, I was just thinking out loud. If it looks easier with this abstraction, I'm good with the change. Can you just add some minimal javadocs to EvictingQueue before pushing?

**Comment by jasontedor** [comment]
@jpountz Added Javadocs in e61e7463e3e4da13e481de20671c42f196154f1a.

**Comment by jasontedor** [comment]
Thank you for reviewing @jpountz.

**Pull request merged**
