### PR TITLE
add an option for new index allocation ignore current node shard counts

### PR DESCRIPTION
**Pull request by wjp719**
Now when new index created, shard allocations will consider current shard distribution among nodes, and choose nodes with less shard count to assign new index shards. This policy may result in all new index shards allocation to newly added nodes to clusters and all the write workload are direct to these new node.

There are others cases may result in current shard distribution unbalanced: 
1. in cold-warm architecture, the shard migration speed may differ.  
2. once a node down, and than failover
in these cases, if new index crated, the new index shards allocation may unbalance. 

This pr adds an option for new index allocation ignore current node shard counts. so that new index shards will all balanced among all nodes.

### CODE REVIEW

**Comment by wjp719** [comment]
@elasticsearchmachine update branch

**Comment by wjp719** [comment]
@elasticsearchmachine update branch

**Comment by DaveCTurner** [comment]
Thanks for the contribution @wjp719. This approach targets a specific problem with shard allocation, but may not even address that problem fully because rebalancing will move shards onto the new empty node which may cause a hot-spot there anyway. Also it is possible to encounter allocation hot-spots for reasons unrelated to index creation.

We are currently working on some more comprehensive changes to shard allocation to address hot-spotting more generally, rendering changes like this one unnecessary. Therefore I am closing this.

**Comment by wjp719** [comment]
@DaveCTurner thanks for your reply, I think the shard allocation maybe composed of two aspects, the first is to try to assign shards of the new index as balanced as possible, the second is  detect runtime hot-spotting shards, and rebalance the hot-spot shards. This pr is try to solve the first problem and may be you are working on the second problem? 

And may I know is there pr for your working now? Thanks a lot.

**Comment by DaveCTurner** [comment]
We are working on both problems. There is no PR open for this work yet.

**Pull request closed without merging**
