### PR TITLE
[7.x] Move internal index templates to composable templates (#61457)

### PR DESCRIPTION
**Pull request by probakowski**
Backports the following commits to 7.x:
 - Move internal index templates to composable templates (#61457)

### CODE REVIEW

**Comment by probakowski** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample-windows

**Comment by probakowski** [comment]
@jakelandis @andreidan I would be grateful for review on this backport as this is vastly different than the master commit

**Review by andreidan — APPROVED** [review]
LGTM, thanks Przemko

Shall we wait and include https://github.com/elastic/elasticsearch/pull/61973 too?

**Comment by probakowski** [comment]
I've added the fix from #61973 to this PR as well, thanks @andreidan for review!

**Pull request merged**
