### PR TITLE
Networking: Fix test leaking buffer

### LINKED ISSUE #32289: [ci] SimpleNetty4TransportTests.testChannelCloseWhileConnecting
Does not reproduce

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+release-tests/888/console
[build-888.txt](https://github.com/elastic/elasticsearch/files/2220180/build-888.txt)

```
REPRODUCE WITH: ./gradlew :modules:transport-netty4:test \
  -Dtests.seed=493C139EBD4D6E7E \
  -Dtests.class=org.elasticsearch.transport.netty4.SimpleNetty4TransportTests \
  -Dtests.method="testChannelCloseWhileConnecting" \
  -Dtests.security.manager=true \
  -Dbuild.snapshot=false \
  -Dtests.jvm.argline="-Dbuild.snapshot=false" \
  -Dtests.locale=es-PR \
  -Dtests.timezone=Europe/Madrid
```

```
  1> [2018-07-23T16:08:37,101][ERROR][i.n.u.ResourceLeakDetector] LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
  1> WARNING: 3 leak records were discarded because the leak record count is limited to 4. Use system property io.netty.leakDetection.maxRecords to increase the limit.
  1> Recent access records: 4
  1> #4:
  1>    Hint: 'pipelining' will handle the message from this point.
  1>    io.netty.buffer.AdvancedLeakAwareCompositeByteBuf.touch(AdvancedLeakAwareCompositeByteBuf.java:36)
  1>    io.netty.handler.codec.http.HttpObjectAggregator$AggregatedFullHttpMessage.touch(HttpObjectAggregator.java:374)
  1>    io.netty.handler.codec.http.HttpObjectAggregator$AggregatedFullHttpRequest.touch(HttpObjectAggregator.java:454)
  1>    io.netty.handler.codec.http.HttpObjectAggregator$AggregatedFullHttpRequest.touch(HttpObjectAggregator.java:404)
  1>    io.netty.channel.DefaultChannelPipeline.touch(DefaultChannelPipeline.java:116)
```

### PR DESCRIPTION
**Pull request by original-brownbear**
* Test `handler` must release buffer the same way the replaced `org.elasticsearch.http.netty4.Netty4HttpRequestHandler#channelRead0` releases it (our test handler replaces it as the last pipeline item under "handler")
* Closes #32289

### CODE REVIEW

**Review by Tim-Brooks — APPROVED** [review]
LGTM

**Comment by original-brownbear** [comment]
@tbrooks8 thanks!

**Comment by jkakavas** [comment]
@original-brownbear could you please backport this to 6.x ?

**Comment by original-brownbear** [comment]
@jkakavas will do in the morning (midnight around here now :)) and the code is a little different in `6.x` unfortunately so it's not just a cherry pick.

**Comment by jkakavas** [comment]
@original-brownbear thanks ! :heart: I didn't mean to disturb you, I added the comment just so that this doesn't get lost

**Pull request merged**
