### PR TITLE
Fixed missing RUN command from custom docker

### PR DESCRIPTION
**Pull request by vshank77**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?

### CODE REVIEW

**Comment by clintongormley** [comment]
Hi @vshank77 

Thanks for the PR.  Please could I ask you to sign the CLA so that I can merge it in?
http://www.elasticsearch.org/contributor-agreement/

@dliappis could you review please?

**Comment by vshank77** [comment]
I have already signed it.

Transaction ID: CBJCHBCAABAApAK1gmUYIC6fQnZiI2mbl4-IziMnHD_m

**Comment by dliappis** [comment]
Thanks for spotting this @vshank77 !

LGTM

**Comment by karmi** [comment]
Hi @vshank77, I can see that you have signed the CLA, but with a different e-mail than in your [commit](https://patch-diff.githubusercontent.com/raw/elastic/elasticsearch/pull/21808.patch). Can you set your Git client with a real e-mail address, and add that address to your Github profile (it can be hidden), so we can match you against your signature?

**Comment by dliappis** [comment]
@vshank77 did you have any chance to look at @karmi 's [earlier suggestion](https://github.com/elastic/elasticsearch/pull/21808#issuecomment-263215840)?

**Comment by dliappis** [comment]
Addressed in #21973 . Closing this.

**Pull request closed without merging**
