### PR TITLE
fix the version and term field initialization error of NoOpResult

### LINKED ISSUE #66267: term and version fields are not correctly initialized in Engine.NoOpResult class
term and version fields are not correctly initialized in Engine.NoOpResult class, their position should be swapped when invoking the base class's constructor.

```
NoOpResult(long term, long seqNo) {
    super(Operation.TYPE.NO_OP, term, 0, seqNo);
}

NoOpResult(long term, long seqNo, Exception failure) {
    super(Operation.TYPE.NO_OP, failure, term, 0, seqNo);
}
```

Constructors of its base class Engine.Result are:

```
protected Result(Operation.TYPE operationType, Exception failure, long version, long term, long seqNo) {
    this.operationType = operationType;
    this.failure = Objects.requireNonNull(failure);
    this.version = version;
    this.term = term;
    this.seqNo = seqNo;
    this.requiredMappingUpdate = null;
    this.resultType = Type.FAILURE;
}

protected Result(Operation.TYPE operationType, long version, long term, long seqNo) {
    this.operationType = operationType;
    this.version = version;
    this.seqNo = seqNo;
    this.term = term;
    this.failure = null;
    this.requiredMappingUpdate = null;
    this.resultType = Type.SUCCESS;
}
```

### PR DESCRIPTION
**Pull request by asce0705**
term and version fields are not correctly initialized in Engine.NoOpResult class, their position should be swapped when invoking the base class's constructor.

Fixes #66267

### CODE REVIEW

**Comment by asce0705** [comment]
#66269

**Review by dnhatn — APPROVED** [review]
LGTM. Thanks @asce0705 for the contribution.

**Comment by dnhatn** [comment]
@elasticmachine test this please

**Comment by asce0705** [comment]
> LGTM. Thanks @asce0705 for the contribution.

Thanks @dnhatn . The ci has failed, is there something else I can do?

**Comment by asce0705** [comment]
@elasticmachine test this please

**Comment by asce0705** [comment]
@elasticmachine retest this please

**Comment by asce0705** [comment]
It seems that the test has failed for the reason mentioned in #66370, and bwc test is disabled until it is fixed. @dnhatn would you please help restart the test?

**Comment by asce0705** [comment]
Pinging @elastic/es-distributed (Team:Distributed)

**Comment by dnhatn** [comment]
@elasticmachine update branch

**Comment by dnhatn** [comment]
@elasticmachine ok to test

**Comment by dnhatn** [comment]
I added a unit test for this in https://github.com/elastic/elasticsearch/commit/aa4831691ca5d97b495fd866673a43a58cebd10f.

**Pull request merged**
