### PR TITLE
Minor grammar fixes (StreamInput.java)

### PR DESCRIPTION
**Pull request by sabi0**

### CODE REVIEW

**Comment by thecoop** [comment]
@elasticsearchmachine test this please

**Comment by thecoop** [comment]
@sabi0 thanks for the changes - could you update your branch from latest main? Looks like its a bit behind

**Comment by sabi0** [comment]
Is there still anything I could improve about this PR?

**Comment by thecoop** [comment]
@elasticsearchmachine test this please

**Review by thecoop — APPROVED** [review]

**Pull request merged**
