### PR TITLE
Don't fail if an object is specified as a nested value instead of an array.

### PR DESCRIPTION
**Pull request by martijnvg**
PR for #9723

### CODE REVIEW

**Comment by jpountz** [comment]
I'm afraid that this change would hide the actual bug? Nested documents are only useful when there are several of them in order to not flatten the information. Otherwise you are just wasting the docID space and making queries slower.

Maybe the right fix would be instead to fail indexing requests for a nested object when an array is not used?

**Comment by kimchy** [comment]
in different dynamic languages JSON support, an can be dynamically created to wrap a single value if needed, so conceptually, some clients will find it hard to make sure the JSON they send always sends an array, even if there is a single element.

**Comment by jpountz** [comment]
OK, LGTM then.

**Comment by martijnvg** [comment]
@jpountz This is what my initial thought was too, but then I released that a single element being wrapped in a json object is what sometimes happens in practice...

**Pull request merged**
