### PR TITLE
fix percentile aggregation tests

### PR DESCRIPTION
**Pull request by not-napoleon**
This fixes some tests that I broke when merging in changes from master.

### CODE REVIEW

**Review by polyfractal — APPROVED** [review]
:+1:

**Comment by not-napoleon** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by not-napoleon** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by not-napoleon** [comment]
Test failures have been related to #50340, which itself is waiting on this fix to merge.  Since this is landing in the feature branch anyway, going to go ahead and merge this without CI being green.

**Pull request merged**
