### PR TITLE
Missing 1 escape character in example

### PR DESCRIPTION
**Pull request by joelbourbon**

### CODE REVIEW

**Comment by clintongormley** [comment]
Hi @joelbourbon 

Thanks for the PR. Please could I ask you to sign the CLA so that I can merge it in?
https://www.elastic.co/contributor-agreement

**Comment by joelbourbon** [comment]
I did right after I submitted the pull request. I also received the e-mail validation.

Want me to do it again ?

**Comment by clintongormley** [comment]
Hi @joelbourbon 

Sorry, for some reason I'm not seeing your name or github username in the list.  Please could you sign the individual contributor version?

sorry for the runaround

thanks

**Comment by joelbourbon** [comment]
HI @clintongormley,

I just signed the CLA again. Hope it works this time!

**Comment by clintongormley** [comment]
thanks @joelbourbon - merged

**Pull request closed without merging**
