### PR TITLE
Include closed indices as well for filter

### PR DESCRIPTION
**Pull request by debarshiraha**
Fix for #16419

### CODE REVIEW

**Comment by nik9000** [comment]
@debadair you get that CLA check to pass if you sign the [CLA](https://www.elastic.co/contributor-agreement/) with the same email you use for github and that you used for the commit. Then you post a comment on the issue and the checker rechecks automatically.

**Comment by dadoonet** [comment]
@nik9000 You meant @debarshiraha right? :)

**Comment by nik9000** [comment]
> @nik9000 You meant @debarshiraha right? :)

Yup. I'm not doing a good job using the internet this morning....

**Comment by clintongormley** [comment]
@debarshiraha I'm unable to find your signed CLA

**Comment by debarshiraha** [comment]
Our legal mailed elastic to figure out how to add me to the CLA (that they have already done before). He is still waiting for the response.

**Comment by debarshiraha** [comment]
@clintongormley Can someone help to add me to the CCLA? Our open source team has contacted Elastic regarding this.

**Comment by ywelsch** [comment]
superseded by #18545

**Pull request closed without merging**
