### PR TITLE
Update settings.asciidoc

### PR DESCRIPTION
**Pull request by ppf2**
Added example of what the previous setting used to look like for system properties.

### CODE REVIEW

**Comment by jasontedor** [comment]
I'm not sure if this is necessary and anyway it's not quite complete because there use to be a few ways to set system properties and this only shows one of them.

**Comment by ppf2** [comment]
We already have users asking what happened to -D on 5.0 so it will be helpful to at least document the most common ways.  -Des.* is probably the most common one (since it is also used as examples in our pre-5.0 documentation).  So it will be helpful to show one example to start with.

**Comment by jasontedor** [comment]
@ppf2 Fair enough, thank you for opening it on their behalf then. Would you mind including all of the ways that were deprecated then, or would you prefer that I push a commit to this pull request?

**Comment by ppf2** [comment]
Feel free to push a commit to this PR @jasontedor (thx!).  Frankly, I am not sure what are all the other ways folks have been trying to configure ES via system properties out there, I have only seen -Des.* used in the field (which is quite common).

**Comment by jasontedor** [comment]
@ppf2 I opened c95625160a83998286dbad0108a942f80fbb1aca. Please let me know what you think.

**Comment by ppf2** [comment]
LGTM, thx!  Only thing is when viewing the full file of the commit from this site, the * is not getting rendered as separate list item, is it expected, or does it need another new line before the first * item?

**Comment by jasontedor** [comment]
Good catch @ppf2, I pushed 0aaae49a8aee832ad0086a44a3370f18413e8ef0.

**Comment by jasontedor** [comment]
Forward port to 5.x commits: 03a76036e3f82c02272dcbadf948b562786bfba1, 83718a5ff1eb29dad2c0206829f411de7b4dd4d7, and e75752e0e8273207665ec6a0ef6430d7f6b62500.

**Comment by jasontedor** [comment]
Thanks @ppf2. :smile:

**Comment by ppf2** [comment]
No, thank _you_! ❤️

**Pull request merged**
