### PR TITLE
Search shards should not perform can match without query

### PR DESCRIPTION
**Pull request by dnhatn**
If the query cannot be rewritten to match_none, then search_shards API should skip the can_match phase and return all groups of shard copies.

Relates #94534

### CODE REVIEW

**Comment by dnhatn** [comment]
run elasticsearch-ci/bwc

**Review by javanna — APPROVED** [review]
LGTM thanks!

**Comment by dnhatn** [comment]
@elasticmachine update branch

**Comment by dnhatn** [comment]
Thanks Luca!

**Pull request merged**
