### PR TITLE
Search all (_all, *) resolves data streams too

### LINKED ISSUE #58562: [Data streams] Search all requests do not resolve to data streams
**Elasticsearch version** (`bin/elasticsearch --version`): Latest `elasticsearch-8.0.0-SNAPSHOT-darwin-x86_64.tar.gz`

**Plugins installed**: []

**JVM version** (`java -version`):
openjdk version "14" 2020-03-17
OpenJDK Runtime Environment AdoptOpenJDK (build 14+36)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14+36, mixed mode, sharing)

**OS version** (`uname -a` if on a Unix-like system):
Darwin 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

**Description of the problem including expected versus actual behavior**:

The following search requests do not resolve to a data stream:

- `GET /_search`
- `GET /*/_search`
- `GET /_all/search`

**Steps to reproduce**:

 1. Create a composable template for the data stream.

```
PUT /_index_template/logs_data_stream
{
  "index_patterns": [ "logs*" ],
  "data_stream": {
    "timestamp_field": "@timestamp"
  },
  "template": {
    "mappings": {
      "properties": {
        "@timestamp": {
          "type": "date"
        }
      }
    }
  }
}
```

 2. Bulk index some data to the stream to create it. Ensure the data refreshes.

```
PUT /logs/_bulk?refresh=wait_for
{"create":{"_index" : "logs"}}
{ "@timestamp": "2020-12-08T11:04:05.000Z" }
{"create":{"_index" : "logs"}}
{ "@timestamp": "2020-12-08T11:06:07.000Z" }
{"create":{"_index" : "logs"}}
{ "@timestamp": "2020-12-09T11:07:08.000Z" }
```

 3. Search the data using `_all` or `*`. You can also omit the `<target>` in the request path.
```
GET /_all/_search
{
    "query": {
        "match_all": {}
    }
}
```

Results:

```
{
  "took" : 0,
  "timed_out" : false,
  "_shards" : {
    "total" : 0,
    "successful" : 0,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 0,
      "relation" : "eq"
    },
    "max_score" : 0.0,
    "hits" : [ ]
  }
}
```

Targeting the data stream directly (e.g., `GET /logs/_search`) or a backing index (e.g., `GET /.ds-logs-000001/_search`) produces the expected results.

### PR DESCRIPTION
**Pull request by andreidan**
This adds support to expand data streams when resolving `*`, `_all` or missing "include all" wildcards
and resolve the backing indices according to the configured wildcard expansion options (ie. if some
backing indices are closed they will not be resolved if closed indices are not desired).

Relates to #53100
Fixes #58562

### CODE REVIEW

**Comment by andreidan** [comment]
@elasticmachine update branch

**Comment by andreidan** [comment]
@elasticmachine update branch

**Comment by andreidan** [comment]
@elasticmachine run elasticsearch-ci/2

**Review by martijnvg — APPROVED** [review]
LGTM

**Pull request merged**
