### PR TITLE
Remove 2.x backward compatibility of mappings.

### PR DESCRIPTION
**Pull request by jpountz**
For the record, I also had to remove the geo-hash cell and geo-distance range
queries to make the code compile. These queries already throw an exception in
all cases with 5.x indices, so that does not hurt any more.

I also had to rename all 2.x bwc indices from `index-${version}` to
`unsupported-${version}` to make `OldIndexBackwardCompatibilityIT`
happy.

### CODE REVIEW

**Comment by jpountz** [comment]
@elasticmachine retest this please

**Comment by s1monw** [comment]
I am not sure I can review this but I will give it a glance

**Comment by jpountz** [comment]
For the record, there are things that probably need to be done as follow-ups, like adding deprecation warnings to 5.x for the case that eg. a timestamp and/or a ttl are provided as part of indexing requests.

**Comment by jpountz** [comment]
@elasticmachine retest this please

**Comment by jpountz** [comment]
I just rebased to fix conflicts with master.

**Comment by s1monw** [comment]
I went over this again and the changes look good. I think what we need to work on is to prevent that we join a cluster that has any indices allocated that were created with 2.x. We can do that in the handshake routine I will look into this and create an issue

**Pull request merged**
