### PR TITLE
	Normalize registration for SignificanceHeuristics

### PR DESCRIPTION
**Pull request by nik9000**
When I pulled on the thread that is "Remove PROTOTYPEs from
SignificanceHeuristics" I ended up removing SignificanceHeuristicStreams
and replacing it with readNamedWriteable. That seems like a lot at once
but it made sense at the time. And it is what we want in the end, I think.

Anyway, this also converts registration of SignificanceHeuristics to
use ParseFieldRegistry to make them consistent with Queries, Aggregations
and lots of other stuff.

Related to #17085

### CODE REVIEW

**Comment by nik9000** [comment]
Or not. Sadly, this hits "failed to check serialization" because it touches streams. I'm not sure what to do with this now.

**Comment by nik9000** [comment]
> Or not. Sadly, this hits "failed to check serialization" because it touches streams. I'm not sure what to do with this now.

Fixed by adding a shiny new hack.

**Comment by colings86** [comment]
Could you quickly explain why `ElasticsearchAssertions` failed before the fix you added? I am just wondering what the difference between creating a `NamedWriteableRegistry` then populating it using the `SearchModule` and getting the `NamedWriteableRegistry` from the test cluster since I thought both should amount to the same thing?

**Comment by nik9000** [comment]
Plugins! One test failed: it registered a significance heuristic in a
plugin. Since the heuristic is returned in the response this checks it. It
used to work because the registration was static.

**Comment by colings86** [comment]
Ok, that makes sense. This PR LGTM

**Comment by nik9000** [comment]
Thanks for reviewing @colings86 !

**Pull request merged**
