### PR TITLE
Support for eu-west-2 (London) cloud-aws plugin

### PR DESCRIPTION
**Pull request by nicpalmer**
As per issue #22306 I am submitting PR for eu-west-london support for discovery-ec2 and repository-s3.

Thanks! 
Nic

### CODE REVIEW

**Review by dadoonet — APPROVED** [review]

**Comment by andyflatt** [comment]
Is there a good reason for not fixing this is current releases of ES 2 and ES 5?

**Comment by dadoonet** [comment]
Yes. Not a blocker as there is a workaround explained at https://github.com/elastic/elasticsearch/issues/22306#issuecomment-268547104

**Comment by andyflatt** [comment]
Thanks! knew I must have been missing something.

**Comment by dadoonet** [comment]
Well I should have added this information is the PR comment as well. :)

**Pull request merged**
