### PR TITLE
Remove index merge policy `reclaim_deletes_weight` setting.

### PR DESCRIPTION
**Pull request by howardhuanghua**
Remove unsued `index.merge.policy.reclaim_deletes_weight` setting to keep code clean.

### CODE REVIEW

**Comment by gwbrown** [comment]
@elasticmachine update branch

**Comment by gwbrown** [comment]
@howardhuanghua Thanks for your contribution! Apologies for the delay on reviewing this, but it looks like a good change - could you please merge the latest `master` into your branch? There are several changes since this PR was created that will be necessary for our CI to pass.

**Comment by howardhuanghua** [comment]
Hi @gwbrown , thanks for the checking. I have merged the latest master branch.

**Comment by gwbrown** [comment]
@elasticmachine test this please

**Comment by howardhuanghua** [comment]
Update/merge branch again.

**Comment by gwbrown** [comment]
Thanks!

@elasticmachine test this please

**Pull request merged**
