### PR TITLE
Give maven modules nicer names, so they are more readable in the reactor summary

### PR DESCRIPTION
**Pull request by rjernst**
The reactor summary now looks like this:

```
[INFO] Build Resources ................................... SUCCESS [  0.490 s]
[INFO] Rest API Spec ..................................... SUCCESS [  0.214 s]
[INFO] Parent POM ........................................ SUCCESS [  2.899 s]
[INFO] Core .............................................. SUCCESS [ 18.169 s]
[INFO] Distribution: Parent POM .......................... SUCCESS [  0.447 s]
[INFO] Distribution: With all optional dependencies ...... SUCCESS [  0.363 s]
[INFO] Distribution: Shaded .............................. SUCCESS [  0.327 s]
[INFO] Distribution: TAR ................................. SUCCESS [  0.352 s]
[INFO] Distribution: ZIP ................................. SUCCESS [  0.341 s]
[INFO] Distribution: DEB ................................. SUCCESS [  0.930 s]
[INFO] Plugins: Parent POM ............................... SUCCESS [  0.596 s]
[INFO] Plugins: Analysis - Japanese (Kuromoji) ........... SUCCESS [  0.918 s]
[INFO] Plugins: Analysis - Smart Chinese ................. SUCCESS [  0.807 s]
[INFO] Plugins: Analysis - Polish (Stempel) .............. SUCCESS [  0.834 s]
[INFO] Plugins: Analysis - Phonetic ...................... SUCCESS [  1.031 s]
[INFO] Plugins: Analysis - ICU ........................... SUCCESS [  1.127 s]
[INFO] Plugins: Cloud - GCE .............................. SUCCESS [  1.068 s]
[INFO] Plugins: Cloud - Azure ............................ SUCCESS [  1.490 s]
[INFO] Plugins: Cloud - AWS .............................. SUCCESS [  1.225 s]
[INFO] Plugins: Script - Python .......................... SUCCESS [  0.912 s]
[INFO] Plugins: Script - Javascript ...................... SUCCESS [  0.997 s]
[INFO] Plugins: Mapper - _size ........................... SUCCESS [  0.870 s]
[INFO] Plugins: Delete By Query .......................... SUCCESS [  1.208 s]
[INFO] Plugins: Example - JVM ............................ SUCCESS [  0.863 s]
[INFO] Plugins: Example - Site ........................... SUCCESS [  0.169 s]
[INFO] QA: Parent POM .................................... SUCCESS [  0.155 s]
[INFO] QA: Smoke Test Plugins ............................ SUCCESS [  0.565 s]
[INFO] QA: Smoke Test Shaded Jar ......................... SUCCESS [  0.320 s]
[INFO] QA: Smoke Test Multi-Node IT ...................... SUCCESS [  0.202 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
```

### CODE REVIEW

**Comment by dadoonet** [comment]
@rjernst I did the same within this PR: https://github.com/elastic/elasticsearch/pull/12879

**Comment by rjernst** [comment]
@dadoonet It looks like that PR only has it renamed for plugins? I think this could go in first, we don't need to wait on artifact renames?

**Comment by dadoonet** [comment]
I renamed distribution, plugins, dev tools...

**Comment by rjernst** [comment]
Ok, I dont' care, I had only seen the first reactor summary there. I would make them more uniform though...like "Plugins: Parent POM" and the rest still starting with "Plugins"...

**Comment by dadoonet** [comment]
Feel free to comment my PR for better names. I'll be happy to fix.

**Pull request closed without merging**
