### PR TITLE
Fix handling of Windows paths containing parentheses

### LINKED ISSUE #26454: elasticsearch-service.bat that generates an error with install
**Elasticsearch version** (`bin/elasticsearch --version`): 5.5

**Plugins installed**: [] EMC SourceOne 7.2.5 

**JVM version** (`java -version`): jre1.8.0_45
capture

**OS version** (`uname -a` if on a Unix-like system): Windows Server 2012R

**Description of the problem including expected versus actual behavior**:
Unable to install Elastic 5.5 using elasticsearch-service.bat
**Steps to reproduce**:

1. Open CMD in Admin mode
2. cd to "C:\Program Files (x86)\EMC SourceOne\EXPBA\bin\Elastic\elasticsearch\bin\"
3. run service.bat install or elasticsearch-service.bat install (depending on ES version)

Issue is that with 5.5 and elasticsearch-service.bat that generates an error due to spaces in the path.

**Provide logs (if relevant)**: none available

WORKAROUND:

in CMD line, change to cd `C:\PROGRA~2\EMCSOU~1\EXPBA\bin\Elastic\elasticsearch\bin\`
Using 8.3 format folder names solves the problem.

### PR DESCRIPTION
**Pull request by olcbean**
If the ES_HOME contains parentheses, the service cannot be installed.

Fixes #26454

### CODE REVIEW

**Comment by karmi** [comment]
Hi @olcbean, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/elasticsearch/pull/26916.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by jasontedor** [comment]
Thanks @olcbean.

**Comment by olcbean** [comment]
@jasontedor thanks for merging this!

There is a tiny difference between `5.6` and `6.0+`. I just verified that applying only this fix to 5.6 still results in an error when the service in installed (if the path contains parentheses). I opened another PR #27012 which is only applicable to 5.6 (on top of this one). Can you please have a look at it?

**Pull request merged**
