### PR TITLE
Expose roles by default in cat allocation API

### PR DESCRIPTION
**Pull request by DaveCTurner**
In #96994 we added a column for node roles to the `GET _cat/allocation`
API but left it hidden by default to avoid changing behaviour. In fact
it's ok to change the behaviour of the CAT APIs since they're only
intended for human consumption, and it's awfully useful to see the node
roles in this API response, so this commit makes this column display by
default.

### CODE REVIEW

**Comment by DaveCTurner** [comment]
@elasticsearchmachine test this please

**Comment by DaveCTurner** [comment]
@elasticmachine test this please

**Comment by DaveCTurner** [comment]
@elasticmachine test this please

**Comment by DaveCTurner** [comment]
@elasticmachine test this please

**Comment by DaveCTurner** [comment]
@elasticmachine test this please

**Comment by DaveCTurner** [comment]
@elasticmachine test this please

**Review by dakrone — APPROVED** [review]
LGTM

**Pull request merged**
