### PR TITLE
Reenable BWC tests

### PR DESCRIPTION
**Pull request by danhermann**
Follows backport of #58833 in #59064

### CODE REVIEW

**Comment by danhermann** [comment]
@elasticmachine update branch

**Comment by danhermann** [comment]
@elasticmachine update branch

**Comment by droberts195** [comment]
Please can you wait until #59068 is merged before reenabling the BWC tests.  Otherwise they'll fail because of that.  You _might_ get a green build on this PR before then because there's only a 50% chance that lack of #59068 causes a BWC build to fail.

**Comment by danhermann** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by danhermann** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by droberts195** [comment]
#59068 is merged now, so if the BWC fails again an "update branch" should fix it

**Comment by danhermann** [comment]
@elasticmachine update branch

**Pull request merged**
