### PR TITLE
Fix OldRepositoryAccessIT testOldRepoAccess 

### LINKED ISSUE #115631: [CI] OldRepositoryAccessIT testOldRepoAccess failing
**Build Scans:**
- [elasticsearch-intake #11931 / part2](https://gradle-enterprise.elastic.co/s/j6wl5u2tadsui)
- [elasticsearch-pull-request #38421 / part-2](https://gradle-enterprise.elastic.co/s/qj3lzyr6gomqy)

**Reproduction Line:**
```
./gradlew ":x-pack:qa:repository-old-versions:javaRestTestBeforeRestart#5_0_0" --tests "org.elasticsearch.oldrepos.OldRepositoryAccessIT.testOldRepoAccess" -Dtests.seed=360E9472706BB500 -Dtests.locale=de-DE -Dtests.timezone=SystemV/PST8 -Druntime.java=22
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.oldrepos.OldRepositoryAccessIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testOldRepoAccess),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: expected:<1> but was:<0>
```

**Issue Reasons:**
- [main] 2 consecutive failures in test testOldRepoAccess
- [main] 2 failures in test testOldRepoAccess (0.2% fail rate in 1000 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by cbuescher**
This test started failing with the changes made in https://github.com/elastic/elasticsearch/pull/115314 when
we only have one shard in the index. This change adjusts test expectations.

Closes #115631

### CODE REVIEW

**Comment by cbuescher** [comment]
@piergm Opening here to get CI running on it. I'm not entirely sure adjusting the test expectation here is the right thing to do though. 
The search request we are sending a bit earlier in the test is on a date range which should have no hits, without an aggregation, so I'm not quite sure why we still target a shard when its the only one. Maybe you can explain that better since
you authored the change in the test.

**Comment by cbuescher** [comment]
Reading a bit more about how we do pre-filtering, I assume this test if different from others modified in https://github.com/elastic/elasticsearch/pull/115314 it differs in that it targets a read-only index (all archival indices are) and so pre-filter phase should not be executed at all when [this comment is correct](https://github.com/elastic/elasticsearch/blob/588929a0a790a488dc127f2c701f58f89e82f936/server/src/main/java/org/elasticsearch/action/search/SearchRequest.java#L657).
This means `shouldPreFilterSearchShards()` is `true` for cases where the test index has 2 and 3 shards, but `false` for only 1 shard, so the optimization from https://github.com/elastic/elasticsearch/pull/115314 doesn't take effect in that case.
I'm not sure if fixing the test expectation like in this PR is the right solution but I think this explains why running with 1 shard is a special case in this test.

**Comment by javanna** [comment]
Thanks for looking into this test failure!

I am not following the comment above: whenever we have read-only indices, we force the can match phase by setting `prefilter_shard_size` to 1, don't we?

The optimization is based on the fact that whenever we don't have aggs requested, we can avoid going to the data node to create an empty response. That means all shards may be skipped, hence the assertion was changed by Matteo. I wonder if there is more to it, there probably is and adjusting the test expectation may hide a problem.

**Comment by cbuescher** [comment]
I think the difference between 1 and 2/3 shards in this test is happening [here](https://github.com/elastic/elasticsearch/blob/2ed318f21fc015609fa9b09d94115e3465c17615/server/src/main/java/org/elasticsearch/action/search/TransportSearchAction.java#L1388) in `shouldPreFilterSearchShards`. Because we check for "preFilterShardSize < numShards" this won't be true for preFilterShardSize=1 and the `requireAtLeastOneMatch` [optimization isn't be executed](https://github.com/elastic/elasticsearch/blob/2ed318f21fc015609fa9b09d94115e3465c17615/server/src/main/java/org/elasticsearch/action/search/TransportSearchAction.java#L1461C25-L1461C47). I refrained from touching that logic yet but if you think that should be the fix I will change the logic instead of the test expectation.

**Comment by javanna** [comment]
@cbuescher let's wait for @piergm to chime in ;)

**Review by piergm — APPROVED** [review]
While implementing https://github.com/elastic/elasticsearch/pull/115314 we kept the logic to effectively skip can_match phase if `shouldPreFilterSearchShards()` returns `false`.
When this test fails we have only one shard, therefore we skip can_match and directly query the shard since we would need to do two roundtrips to the shard otherwise (a can_match and a query phase). 
The two roundtrips are not performed in two scenarios: 

1. if the data node can_match returns no matches
2. if the coordinator re-write returns match none (only applicable if we filter on timestamp, event.ingested or _tier).

In the first scenario we'd need to perform one roundtrip and therefore is better to directly skip the can_match
In the second scenario we'd avoid to send any requests to the data node.

To me the second scenario is a corner case and I'd opt for changing the test.

If we agree on my point we can merge this (Changes LGTM), otherwise I can work on changing the logic and check coord rewrite even if `preFilterShardSize >= numShards`.

**Comment by cbuescher** [comment]
Thanks, I'll hold off merging before @javanna gets a chance to take another look but would otherwise merge this to main and 8.x (and every other 8 branch where this test was muted for this reason)

**Pull request merged**
