### PR TITLE
Remove xpack dependencies from qa rest modules

### PR DESCRIPTION
**Pull request by martijnvg**
This commit removes xpack dependencies of many xpack qa modules.
(for some qa modules this will require some more work)

The reason behind this change is that qa rest modules should not depend
on the x-pack plugins, because the plugins are an implementation detail and
the tests should only know about the rest interface and qa cluster that is
being tested.

Also some qa modules rely on xpack plugins and hlrc (which is a valid
dependency for rest qa tests) creates a cyclic dependency and this is
something that we should avoid.  Also Eclipse can't handle gradle cyclic
dependencies (see #41064).

### CODE REVIEW

**Comment by martijnvg** [comment]
@elasticmachine run elasticsearch-ci/1

**Review by alpar-t — APPROVED** [review]
LGTM thanks for taking this on!

`project(':x-pack:qa')` seems to be  going into the direction of an x-pack test lib or fw, it might be better to put it in  a project in `x-pack/test` or move it into `test:framework` even if it's c-pack specific I think this is something we have done in the past.

**Comment by martijnvg** [comment]
> project(':x-pack:qa') seems to be going into the direction of an x-pack test lib or fw, it might be better to put it in a project in x-pack/test or move it into test:framework even if it's c-pack specific I think this is something we have done in the past.

Yes, I think we should move to its own xpack/test lib and when xpack qa module are going to get merged with regular qa module then  xpack/test can be merged with test/framework. I can work on that in a followup.

**Comment by martijnvg** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by martijnvg** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by martijnvg** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample

**Pull request merged**
