### PR TITLE
Dry up empty validate methods in + empty implementations of AcknowledgedRequest

### PR DESCRIPTION
**Pull request by original-brownbear**
A lot of the validate methods in AcknowledgedRequest are empty and there's a couple noop implementations of the class as well that can just go away.

### CODE REVIEW

**Comment by joegallo** [comment]
An alternative version of this pull request would keep `AcknowledgedRequest.Plain` mostly as you have it, but move the no-op `validate()` method implementation to there. If you are using `AcknowledgedRequest.Plain` then of course you have no additional fields and so also of course you have no validation to do. This alternative PR would drop a lot of minimally valuable classes in favor of 'just' using `AcknowledgedRequest.Plain`, but it would not remove the many empty `validate()` methods that you have removed. I think this version is the least objectionable pull request, in that I can't personally see how anybody could object to it (but maybe that's just my lack of vision).

Part of me thinks that is preferable: `ActionRequest` makes the `validate()` method `abstract` so that you must override it (no-op or not), and `MasterNodeRequest` doesn't do anything to change that. It seems a bit surprising that `AcknowledgedRequest` pops in with a different opinion on the subject while itself also remaining `abstract`. Or, putting this a different way -- if having a default `validate()` implementation is a good idea for `AcknowledgedRequest`, then why *isn't* it a good idea further up the chain at `MasterNodeRequest` or even `ActionRequest`?

I don't have enough experience with this code to say whether having a default implementation is trappier than the annoyance of having so many empty no-op implementations. So I'm firing up a signal flare for @DaveCTurner to come in with a second set of eyes.

**Comment by DaveCTurner** [comment]
Yeah I've always found that `validate()` method a little irksome, preferring instead to have requests that are immutable and to avoid even constructing them if they aren't in a valid state. I reckon it must have been more useful when we had the transport client and users were creating these objects themselves, with all the mutable fields that this entails, but these days I'd be happy if it were optional all the way up the tree.

**Comment by original-brownbear** [comment]
@DaveCTurner whenever you have a sec, this one still makes sense to save some code IMO :)

**Review by DaveCTurner — APPROVED** [review]
:+1: LGTM

**Comment by original-brownbear** [comment]
Thanks David!

**Pull request merged**
