### PR TITLE
Update term-suggest.asciidoc

### PR DESCRIPTION
**Pull request by akibrhast**
It is really easy to miss the fact, that that's the default setting, since it is not highlighted or called out in anyway

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Review by cbuescher — COMMENTED** [review]
Hi @akibrhast, thanks for your suggestion. 

In other places we tend to use "(default)" in brackets for emphasis. I would prefer that to bold type. Would you mind changing to that?

**Comment by cbuescher** [comment]
Also we'd need you to sign the CLA following the mentioned in the contribution guidelines to proceed with this PR.

**Comment by abdonpijpelink** [comment]
@akibrhast Are you interested in continuing to work on this PR, and apply @cbuescher 's suggestion? The PR also needs to be rebased onto the `main` branch. Otherwise we can take it from here.

**Comment by akibrhast** [comment]
Please take it from here. I will not be continuing.

Thank you

**Review by abdonpijpelink — APPROVED** [review]

**Pull request merged**
