### PR TITLE
Remove unsed deciders in BalancedShardsAllocator for 7.x

### PR DESCRIPTION
**Pull request by howardhuanghua**
Relates to https://github.com/elastic/elasticsearch/pull/62026. Update it for 7.x.

### CODE REVIEW

**Comment by dnhatn** [comment]
@elasticmachine ok to test

**Comment by dnhatn** [comment]
@elasticmachine update branch

**Comment by dnhatn** [comment]
@howardhuanghua You do not need to open a backport PR. We will do it based on the main PR.

**Comment by howardhuanghua** [comment]
OK. Thank you.

**Pull request closed without merging**
