### PR TITLE
Add index privileges for logs-enterprise_search.api-default to the enterprise-search-server service account

### PR DESCRIPTION
**Pull request by jgr**
Gives the `elastic/enterprise-search-server` service account access to the Enterprise Search audit event data stream.

### CODE REVIEW

**Review by brianmcgue — COMMENTED** [review]
LGTM, will obviously wait for the Elasticsearch team to weigh in

**Review by ywangd — APPROVED** [review]
LGTM

**Comment by jgr** [comment]
@carlosdelest or @ioanatia any idea why I saw these CI failures? I'd look into it deeper if I wasn't on PTO. /cc @brianmcgue

**Comment by ywangd** [comment]
Failures are not related. The BWC one probably has something to do with 8.1.1 just got cut. 

@elasticmachine update branch

**Comment by ywangd** [comment]
@elasticmachine update branch

**Pull request merged**
