### PR TITLE
ESQL: Remove esql version from docs

### PR DESCRIPTION
**Pull request by alex-spies**
Follow-up to https://github.com/elastic/elasticsearch/pull/108919. The latter needs to be merged first to have the docs tests pass, as it makes the version parameter optional in requests.

### CODE REVIEW

**Review by nik9000 — APPROVED** [review]

**Comment by nik9000** [comment]
elasticmachine, update branch

**Comment by nik9000** [comment]
elasticmachine update branch

**Comment by nik9000** [comment]
come on magic robot, merge stuff

**Comment by alex-spies** [comment]
> come on magic robot, merge stuff

:robot:

**Pull request merged**
