### PR TITLE
Remove deprecated AUTH_PASSWORD setting

### PR DESCRIPTION
**Pull request by danhermann**
Removes the `auth.password` setting for monitoring HTTP exporters. Users must switch to the secure `auth.secure_password` setting.

Relates to https://github.com/elastic/elasticsearch/pull/50919

Docs preview: http://elasticsearch_54892.docs-preview.app.elstc.co/diff

### CODE REVIEW

**Comment by danhermann** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by lcawl** [comment]
I think the auth.password needs to be removed from the example in https://www.elastic.co/guide/en/elasticsearch/reference/master/http-exporter.html too.

**Comment by danhermann** [comment]
> I think the auth.password needs to be removed from the example in https://www.elastic.co/guide/en/elasticsearch/reference/master/http-exporter.html too.

Thanks for catching that, @lcawl. I'll update that example.

**Comment by danhermann** [comment]
@elasticmachine run elasticsearch-ci/2

**Review by lcawl — APPROVED** [review]
Documentation changes LGTM, thanks!

**Comment by danhermann** [comment]
@elasticmachine update branch

**Review by jakelandis — APPROVED** [review]
LGTM

**Pull request merged**
