### PR TITLE
[Inference API] Consolidate completion expectation methods

### PR DESCRIPTION
**Pull request by timgrein**
Removed some code duplication by moving the generic function to build a completion expectation to `ChatCompletionResultsTests` similar to how the embeddings tests do it.

### CODE REVIEW

**Review by maxhniebergall — APPROVED** [review]
LGTM

**Comment by timgrein** [comment]
@elastichmachine update branch

**Comment by timgrein** [comment]
@elasticmachine update branch

**Comment by timgrein** [comment]
@elasticmachine update branch

**Pull request merged**
