### PR TITLE
Allow a data stream to be downgraded to a regular data stream

### PR DESCRIPTION
**Pull request by martijnvg**
Upon rollover a data stream's index mode is removed if the associated template no longer has `index.mode` setting set to `time_series`.

Closes to #92544

### CODE REVIEW

**Review by dakrone — APPROVED** [review]
LGTM, thanks for the clear PR and tests Martijn

**Comment by martijnvg** [comment]
@elasticmachine update branch

**Comment by martijnvg** [comment]
Thanks Lee for reviewing!

**Comment by ruflin** [comment]
@martijnvg Can you share a bit more details on what the behaviour will be on the query side afterwards for the old data?

**Comment by martijnvg** [comment]
>  It basically means if no time_series aggs were used TSDB can be turned on and off easily without any side effects.

Yes.

**Pull request merged**
