### PR TITLE
Closes #28143 : Modifies the JavaAPI docs related to AggregationBuilder

### LINKED ISSUE #28143: AggregationBuilder related docs of Java API are outdated
Originally reported in #28114:

1. "AggregatorBuilder" should be replaced by "AggregationBuilder" in https://www.elastic.co/guide/en/elasticsearch/client/java-api/master/_bucket_aggregations.html

	> Ip Range Aggregationedit
	> Here is how you can use Ip Range Aggregation with Java API.

	> Prepare aggregation requestedit
	> Here is an example on how to create the aggregation request:

	> AggregatorBuilder<?> aggregation =...

	> Note that you could also use ip masks as ranges:

	> AggregatorBuilder<?> aggregation =...

2. "GeoBoundsBuilder" may be replaced by "GeoBoundsAggregationBuilder" in https://www.elastic.co/guide/en/elasticsearch/client/java-api/master/_metrics_aggregations.html#java-aggs-metrics-geobounds

	> Geo Bounds Aggregationedit
	> Here is how you can use Geo Bounds Aggregation with Java API.

	> Prepare aggregation requestedit
	> Here is an example on how to create the aggregation request:

	> GeoBoundsBuilder aggregation =
    >	    GeoBoundsAggregationBuilder...

These are leftovers from #18377 and we should revisit all related classes and update the Java API related docs for them.

### PR DESCRIPTION
**Pull request by ghost**
1."AggregationBuilder" replaces "AggregatorBuilder" in docs/java-api/aggregations/bucket/iprange-aggregation.asciidoc
2."GeoBoundsAggregationBuilder" replaces "GeoBoundsBuilder" in docs/java-api/aggregations/metrics/geobounds-aggregation.asciidoc

### CODE REVIEW

**Comment by danielmitterdorfer** [comment]
@elasticmachine please test this.

**Comment by danielmitterdorfer** [comment]
Thanks for the PR @SRITANU. The change looks good to me. I just kicked off a verification build.

**Comment by SRITANU** [comment]
Thanks @danielmitterdorfer . Has it been accepted/merged ?

**Comment by danielmitterdorfer** [comment]
The build has finished by now and is green, changes look good to me so I'll merge now.

**Pull request merged**
