### PR TITLE
Avoid building large CompositeByteBuf when sending transport messages

### PR DESCRIPTION
**Pull request by original-brownbear**
We can avoid building composite byte buf instances on the transport layer (they have quite a bit of overhead and make heap dumps more complicated to read). There's no need to add another round of references to the BytesReference components here. Just write these out as they come in. This would allow for some efficiency improving follow-ups where we can essentially release the pages that have passed the write pipeline.
To avoid having this explode the size of the queue for writes per channel, I moved that to a linked list. The slowdown from a linked list is irrelevant I believe. Mostly the queue is empty so it doesn't matter or if it isn't empty, operations other than dequeuing are much more important to performance in this logic anyway (+ Netty internally uses a LL down the line anyway).

I would regard this as step-1 in making the serialisation here more lazy like on the REST layer to avoid copying bytes to the outbound buffer that we already have as `byte[]`.

### CODE REVIEW

**Review by DaveCTurner — COMMENTED** [review]
Hmm is there a way we could do this just for transport channels rather than having this unused code in the HTTP pipeline too? Perhaps we could disaggregate the `BytesReference` into the sequence of `ByteBuf` messages in a separate handler first?

Also shouldn't we stop sending pages down the line if the channel becomes unwriteable? I mean I guess we don't today, we just send it all in a single giant message, but if we did the disaggregation first then the `Netty4WriteThrottlingHandler` would throttle these message chunks properly too.

**Comment by original-brownbear** [comment]
> Also shouldn't we stop sending pages down the line if the channel becomes unwriteable?

We already do that for chunked rest responses where we check the writability of a channel.
It would be nice if we had that for tcp transport messages as well in some form for sure :)
An idea I toyed with here recently was to allow just writable or some other lazy-serialisation mechanism to be passed to this handler as well and then deal with things there.
In general, big yes though if we can, we should throttle earlier to save memory. No point serialising bytes we can't write out.

> Hmm is there a way we could do this just for transport channels rather than having this unused code in the HTTP pipeline too?

I was wondering about that :) My plans were a little different actually. I was thinking, maybe we can be clever here and make use of some zero-copy tricks on the http path as well eventually (thinking of search response sources here mostly, though those could be dealt with some other way as well).

Not really sure it's worth adding another handler here in general. Performance wise, it's definitely not worth it. A simple `instanceOf` is in all likelihood cheaper than a potential virtual call. I'd rather refactor the `ByteBuf` logic to use the same promise approach that I used here and in the chunked http handler to streamline this more than split this up personally :) But not my code anymore :P

**Comment by DaveCTurner** [comment]
Ah sorry, I misread this, I read it as just calling `write()` on each page regardless of the downstream writability. We're queuing up writes here already indeed.

Let's have some tests to demonstrate this in `Netty4WriteThrottlingHandlerTests`, otherwise LGTM

**Comment by original-brownbear** [comment]
Thanks David, test for the composite case added and generalised the other tests to at least cover `BytesArray` :)!

**Review by DaveCTurner — APPROVED** [review]
LGTM

(micronit: these days I'd generally reach for `org.elasticsearch.test.ESTestCase#asInstanceOf` rather than casting in tests, to avoid making the reader think about whether a `ClassCastException` would cause a test failure)

**Pull request merged**
