### PR TITLE
Add XContent Serialization Test to SnapshotShardFailure

### PR DESCRIPTION
**Pull request by original-brownbear**
Adding missing test from #72801 and fix up `equals` and `hashCode` on this class.

### CODE REVIEW

**Review by DaveCTurner — CHANGES_REQUESTED** [review]
Could we have a test that checks the equality methods (i.e. uses `EqualsHashCodeTestUtils.checkEqualsAndHashCode`) too?

**Comment by original-brownbear** [comment]
Thanks David and ++ added the `checkEqualsAndHashCode` based test now :)

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/part-2 known geo issue

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/part-2 known geo issue

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Comment by original-brownbear** [comment]
Thanks David!

**Pull request merged**
