### PR TITLE
Introduce ESTesetCase#safeAcquire

### PR DESCRIPTION
**Pull request by ywangd**
Similar to safeAwait for Barrier and Latch, safeAcquire try acquire permit for a Semaphore within given timeout.

Relates: #94737

### CODE REVIEW

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by ywangd** [comment]
Failure is https://github.com/elastic/elasticsearch/issues/106073

**Comment by ywangd** [comment]
@elasticmachine run elasticsearch-ci/part-1

**Review by DaveCTurner — COMMENTED** [review]
LGTM2 👍

**Pull request merged**
