### PR TITLE
Fix pointless complicated boolean expressions

### PR DESCRIPTION
**Pull request by asdf2014**

### CODE REVIEW

**Review by cbuescher — COMMENTED** [review]
Hi @asdf2014, thanks for openning this PR proposing an overall change in the way we use boolean expressions in the codebase. Although we don't have a proper codestyle guide, this is one of the cases where a lot of folks I see doing reviews will actually point you to using `(foo == false)` instead of `!foo` in the codebase. The reason is readability, not succinctness. I've personally had many cases where a missing "!" was causing a bug that might have been easier to spot with a more verbose boolean expression. Thats why I think most people here are against the code style in this change. 
I will leave this open for a bit to give others the change to raise other opinions but I think we don't want to apply this change.

**Comment by asdf2014** [comment]
Hi, @cbuescher . Thanks for your comment.

> I've personally had many cases where a missing "!" was causing a bug that might have been easier to spot with a more verbose boolean expression.

Emm.. this makes sense. Anyway, this code style doesn't bother me. If this is a general consensus, then we should include it in the contribution guide document, right?

**Comment by rjernst** [comment]
What @cbuescher stated is correct. We have an implicit rule that negative boolean expressions use the form `== false`. I agree it should be in the CONTRIBUTING docs, although I'm not sure exactly where to fit it. The stuff currently in there closest to this is about formatting, and mostly about configuring IntelliJ to get the formatting right. @pugnascotia Do you have any thoughts where this could go given your recent work on formatting?

**Comment by pugnascotia** [comment]
I think we could just add another bullet point in `CONTRIBUTING.md`, under the "Java Language Formatting Guidelines" section. If we add any more other guidelines in the future, then I'd be inclined to pull them out into another section.

**Comment by cbuescher** [comment]
I opened https://github.com/elastic/elasticsearch/pull/49033 to discuss adding a note about negative boolean expressions to the CONTRIBUTING docs and will close here.

**Pull request closed without merging**
