### PR TITLE
Fixing flag name in doc

### PR DESCRIPTION
**Pull request by ycombinator**

### CODE REVIEW

**Comment by kimchy** [comment]
LGTM

**Comment by clintongormley** [comment]
Thanks @ycombinator. For future reference, you should merge these fixes into the other branches as well (at the moment: 1.x and master), otherwise these fixes get lost.  I've done this for this PR.

**Comment by ycombinator** [comment]
Thanks @clintongormley for merging into other branches for me this time. I'll keep that in mind for future PRs.

BTW, as I can only target a PR to a specific branch, how do I accomplish this? Do I merge the PR against the targeted branch first, then merge into other branches using the `git merge ...` CLI? That's how I'd do it unless you have a better way.

**Comment by ycombinator** [comment]
Never mind, @rjernst pointed out to me that I should use `git cherry-pick` instead of `git merge` for backporting to older branches. Makes sense. Thanks!

**Pull request merged**
