### PR TITLE
Update the plugin install CLI help to the new short name for commercial plugins

### PR DESCRIPTION
**Pull request by cbuescher**

### CODE REVIEW

**Comment by clintongormley** [comment]
@cbuescher I thought the help could do with more of a cleanup - it's very long.  How about this instead (removing the EXAMPLES) section:

    DESCRIPTION

        This command installs an elasticsearch plugin. It can be used as follows:

        Officially supported or commercial plugins require just the plugin name:

            plugin install analysis-icu
            plugin install shield

        Plugins from GitHub require 'username/repository' or 'username/repository/version':

            plugin install lmenezes/elasticsearch-kopf
            plugin install lmenezes/elasticsearch-kopf/1.5.7

        Plugins from Maven Central or Sonatype require 'groupId/artifactId/version':

            plugin install org.elasticsearch/elasticsearch-mapper-attachments/2.6.0

        Plugins can be installed from a custom URL or file location as follows:

            plugin install http://some.domain.name//my-plugin-1.0.0.zip
            plugin install file:/path/to/my-plugin-1.0.0.zip

**Comment by cbuescher** [comment]
@clintongormley Great, thanks for the input, will update this PR.

**Comment by cbuescher** [comment]
@clintongormley updated the PR, if there's nothing else to add I'll merge this and backport it to the 2.0 branch.

**Comment by clintongormley** [comment]
LGTM

**Pull request merged**
