### PR TITLE
Upgrade procrun executables to 1.3.1

### PR DESCRIPTION
**Pull request by rjernst**
This commit updates the procrun manager and service exes to 1.3.1. There
are a few bugfixes, but most notably there was an unfiled bug that seems
to be fixed where stderr could get gigabytes of null characters in at
least one case.

relates #85758

### CODE REVIEW

**Comment by williamrandolph** [comment]
It looks like our tests assume that the `remove` command will succeed as a no-op if there's no service to remove, but that this is no longer true in `1.3.1`.

**Review by ChrisHegarty — APPROVED** [review]

**Review by mark-vieira — COMMENTED** [review]
I notice that we don't have any license or notice information for procrun anywhere in the project. This looks to be an oversight, mostly because we're not consuming this as a external binary dependency and instead check these into source control.

**Comment by rjernst** [comment]
Re license/notice: I opened https://github.com/elastic/elasticsearch/pull/86773

**Comment by rjernst** [comment]
@elasticmachine run elasticsearch-ci/rest-compatibility

**Pull request merged**
