### PR TITLE
Upgrade groovy from 2.4.0 to 2.4.4

### PR DESCRIPTION
**Pull request by martijnvg**

### CODE REVIEW

**Comment by jpountz** [comment]
LGTM

I'm attaching changelogs for reference:
 - http://groovy-lang.org/changelogs/changelog-2.4.1.html
 - http://groovy-lang.org/changelogs/changelog-2.4.2.html
 - http://groovy-lang.org/changelogs/changelog-2.4.3.html
 - http://groovy-lang.org/changelogs/changelog-2.4.4.html

**Comment by clintongormley** [comment]
LGTm

**Comment by lup7in** [comment]
I noticed that this problem occurred in the transport protocol,but in the changed files I cannot find these changes,I want to know which Class  uses Java deserialized.

**Comment by smartcat315** [comment]
How to upgrade

**Pull request merged**
