### PR TITLE
Use message as field name

### PR DESCRIPTION
**Pull request by adambro**
Align descriptions with examples that were introduced in commit 4b219d15d2a552a58484e4b18a38a7ac827292ed

### CODE REVIEW

**Comment by adambro** [comment]
I have signed corporate SLA before for Kibana work. I guess it should be valid for ElasticSearch.

**Comment by clintongormley** [comment]
Hi @adambro 

Thanks for the PR.  I've had a look through our CLA list and can't find anything with your name on it.  What was the name used on the corporate CLA?  Either way, we need a CLA with your name on it before we can merge.  Sorry for the bother.

**Comment by adambro** [comment]
Hi @clintongormley the CLA has been signed March 2016 by Future Processing. There should be my GH username and corporate email address (abrodziak prefix) included.

**Comment by clintongormley** [comment]
Thanks @adambro - I've added your details to the CLA checker so it should just work in the future.

**Comment by clintongormley** [comment]
thanks @adambro - merged

**Comment by adambro** [comment]
Thanks @clintongormley for adding me to CLA checker, appreciate that.

**Pull request merged**
