### PR TITLE
Fix rate agg with custom `_doc_count`

### LINKED ISSUE #77734: Incorrect rate agg when used on histogram fields
Versions affected: 7.15 and up

I'm seeing some odd results with the rate agg on histogram fields and wondering if it's a bug, similar to https://github.com/elastic/elasticsearch/issues/74617.

## Reproduce problem
```
PUT histogram-rate-bug
{
  "mappings" : {
    "properties" : {
      "my_histogram" : {
        "type" : "histogram"
      }
    }
  }
}

POST histogram-rate-bug/_doc
{
  "_doc_count": 10,
  "@timestamp": "2021-09-14T22:33:37.477Z",
  "my_histogram": {
    "counts": [
      10
    ],
    "values": [
      20
    ]
  }
}

GET histogram-rate-bug/_search
{
  "size": 0,
  "aggs": {
    "timeseries": {
      "date_histogram": {
        "field": "@timestamp",
        "fixed_interval": "60s"
      },
      "aggs": {
        "throughput": {
          "rate": {
            "unit": "minute"
          }
        }
      }
    }
  }
}
```

**Response**
The search request will return:
```json
{
  "aggregations" : {
    "timeseries" : {
      "buckets" : [
        {
          "key_as_string" : "2021-09-14T22:33:00.000Z",
          "key" : 1631658780000,
          "doc_count" : 10,
          "throughput" : {
            "value" : 1.0
          }
        }
      ]
    }
  }
}
```

**Expectation**
I'd expect that a bucket for 1 minute with 10 documents should have a rate of 10.

**Actual**
Rate is 1.0

### PR DESCRIPTION
**Pull request by csoulios**
When running a `rate` aggregation without setting the `field` parameter, the result is computed based on the bucket `doc_count`.   

This PR adds support for a custom `_doc_count` field.

Closes #77734

### CODE REVIEW

**Review by nik9000 — COMMENTED** [review]
I left some comments about the code, but I wonder if it'd be cleaner to go about this by linking into the value source resolution mechanism that `RateAggregationBuilder#resolveConfig` uses - right now it creates a dummy "unmapped Numeric" values source which resolves missing values to `1`. I wonder if it'd be cleaner to make a `DOC_COUNT` values source type and plug it in here. If that worked you wouldn't need any changes to `AggregatorBase` or even the numeric aggregator. It'd all be plumbing the doc count provider through the values source infrastructure that all other aggs use.

**Review by nik9000 — APPROVED** [review]
I think this a good fix for backporting to 7.16. I like the idea of making a `doc_count` value source type but that's a bigger project I think. It can wait.

**Comment by csoulios** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Review by imotov — COMMENTED** [review]
Added some comments.

**Pull request merged**
