### PR TITLE
Preserve the thread context when waiting for snapshot completion

### LINKED ISSUE #82358: ThreadContext mixup in create snapshot API if `wait_for_completion` is `true`
**Elasticsearch version** (`bin/elasticsearch --version`): 7.16.2

**Plugins installed**: []

**JVM version** (`java -version`): `OpenJDK Runtime Environment Temurin-17.0.1+12`

**OS version** (`uname -a` if on a Unix-like system): MacOS + Docker

**Description of the problem including expected versus actual behavior**:

The http response of the create snapshot API does not contain the `X-Elastic-Product` header if `wait_for_completion=true`. This breaks product check in the client libraries (this was reported in https://github.com/elastic/elasticsearch-java/issues/74)

Debugging the issue, I found that the header is not added because the `ThreadContext`'s thread local in `DefaultRestChannel` is different from the one intialized in `RestController.dispatchRequest`, which contains `X-Elastic-Product` as a response header.

I also found that when `wait_for_completion=true`, the action listener is called from a snapshot thread, which may explain the issue.

**Steps to reproduce**:

1. Start Elasticsearch:
    ```
    docker run -t -p 9200:9200 \
      -e "discovery.type=single-node" -e "xpack.security.enabled=false" -e "path.repo=/tmp" \
      docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    ```

1. Create a snapshot repository:
    ```
    curl -v -XPUT "http://localhost:9200/_snapshot/test" -H 'Content-Type: application/json' \
        -d '{"type":"fs","settings":{"location":"/tmp/backup"}}'
    ```

1. Create a snapshot, _not_ waiting for completion. Response contains `X-Elastic-Product`
    ```
    curl -v -XPUT "http://localhost:9200/_snapshot/test/1
    ```

1. Create a snapshot, waiting for completion. **Response does not contain `X-Elastic-Product`**
    ```
    curl -v -XPUT "http://localhost:9200/_snapshot/test/2?wait_for_completion=true"
    ```

### PR DESCRIPTION
**Pull request by jbaiera**
When using `wait_for_complete` on the create snapshot action, the listener that completes the response to the client is stored to be executed once the snapshot completes on another thread. Currently, the thread context is not preserved and this listener is executed with the thread context of the snapshot thread instead of the context present on the request thread. This PR updates the logic to preserve the thread context when waiting for completion.

fixes #82358

### CODE REVIEW

**Comment by jbaiera** [comment]
I wasn't entirely sure how best to test this change - The SnapshotService tests primarily focus on the service executing the snapshot operations from cluster state changes, and the rest of the tests around the create snapshot api are pretty standard serialization updates.

**Comment by swallez** [comment]
If there are other yet-unidentified endpoints that have the same issues, wouldn't it be simpler and more robust to set the product header in `DefaultRestChannel.sendResponse()`?

This would also avoid the overhead of storing this header in the thread context for each and every request when we know it will always be output.

**Comment by jbaiera** [comment]
@swallez I like this idea. I'll open a PR to refactor where the header is introduced. That said, this still highlights an interesting problem of parts of the Elasticsearch project where ThreadContexts are dropped when doing async work. I've opened another PR (https://github.com/elastic/elasticsearch/pull/83290) to hopefully catch any other API's where this might be happening, then get a quick set of fixes out (along with the header refactor).

**Comment by swallez** [comment]
> this still highlights an interesting problem of parts of the Elasticsearch project where ThreadContexts are dropped when doing async work

Absolutely! I tried to find a pattern that would allow finding the offenders, but my knowledge of how ThreadContexts are used is too limited. PR #83290 will be a welcome addition to find them!

**Comment by jbaiera** [comment]
Closing this in favor of #83290

**Pull request closed without merging**
