### PR TITLE
Fix intermittent failure in InternalEngineTest#testRefreshScopedSearcher

### LINKED ISSUE #27514: AssertionError in InternalEngineTests.testRefreshScopedSearcher
`InternalEngineTests.testRefreshScopedSearcher` threw an `AssertionError` in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/858/console

```
FAILURE 0.12s J0 | InternalEngineTests.testRefreshScopedSearcher <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: expected same:<IndexSearcher(ElasticsearchDirectoryReader(FilterLeafReader(_0(7.1.0):c10) FilterLeafReader(_1(7.1.0):c1)); executor=null)> was not:<IndexSearcher(ElasticsearchDirectoryReader(FilterLeafReader(_0(7.1.0):c10) FilterLeafReader(_1(7.1.0):c1)); executor=null)>
   > 	at __randomizedtesting.SeedInfo.seed([168988A8C61979AC:7115CA98C7335368]:0)
   > 	at org.elasticsearch.index.engine.InternalEngineTests.testRefreshScopedSearcher(InternalEngineTests.java:3950)
   > 	at java.lang.Thread.run(Thread.java:745)
```

```
REPRODUCE WITH: gradle :core:test \
  -Dtests.seed=168988A8C61979AC \
  -Dtests.class=org.elasticsearch.index.engine.InternalEngineTests \
  -Dtests.method="testRefreshScopedSearcher" \
  -Dtests.security.manager=true \
  -Dtests.locale=pt \
  -Dtests.timezone=JST
```

This did not reproduce for me locally.

### PR DESCRIPTION
**Pull request by jimczi**
This change switches the merge policy to none (for this specific test) in order to make sure that refreshes are always triggered by a change in the writer.

 Closes #27514

### CODE REVIEW

**Review by bleskes — APPROVED** [review]
I think this change is good regardless, but can you explain where/how merged segments will be picked up with the current code?

**Comment by jimczi** [comment]
Since we're using a concurrent merge scheduler a new merge can start at any time during the test, when a merge starts the new file name is registered in the writer and this triggers a change in the internal version of the writer which in turns causes the reader to refresh on the next refresh call (the internal version of the writer changed even though the merge is not finished):
https://github.com/apache/lucene-solr/blob/master/lucene/core/src/java/org/apache/lucene/index/IndexWriter.java#L4273

In my machine the test fails when a merge starts just after https://github.com/jimczi/elasticsearch/blob/9c66adab1b10f46567fe8d9574fde6656cc02c66/server/src/test/java/org/elasticsearch/index/engine/InternalEngineTests.java#L4148

**Comment by bleskes** [comment]
Makes sense @jimczi . Thanks for explaining.

**Review by s1monw — APPROVED** [review]
LGTM

**Pull request merged**
