### PR TITLE
Correct bug in ScriptDocValues

### PR DESCRIPTION
**Pull request by mayya-sharipova**
If a field `field_name` was missing in a document,
`doc['field_name'].get(0)` incorrectly retrieved
a value of the previously accessed document.
This happened because `get(int index)` function
was just accessing `values[index]` without
checking the number of values:`count`.

This PR fixes this.

### CODE REVIEW

**Review by rjernst — COMMENTED** [review]
The fix looks fine, but do we really need rest tests? Seems like a lot of overhead for behavior we can check in a unit test, and nothing about actually starting a node would affect this behavior.

**Review by jdconrad — COMMENTED** [review]
Thanks for fixing this.  Looks good from my perspective.  I do agree with @rjernst that it looks like the yaml tests could all become unit tests, so I will let him give the final review approval.

**Comment by mayya-sharipova** [comment]
@rjernst @jdconrad  Thanks for your feedback.  I have removed a yml test. Will a single unit test on ScriptDocValues.Longs be enough?

**Comment by rjernst** [comment]
Longs is good. I would also do the GeoPoints tests. It is unfortunate we don't have unit tests for each script doc values class, but that should not block this work.

**Comment by mayya-sharipova** [comment]
@rjernst Thanks Ryan, I have added a test for GeoPoints as well

**Comment by mayya-sharipova** [comment]
@rjernst  @jdconrad Thanks for your feedback.I have updated the test to use unit tests for available types that we have - Long and Geo.  Can you please continue the review when you have available time

**Review by rjernst — APPROVED** [review]
LGTM

**Pull request merged**
