### PR TITLE
Upgrade XContent to Jackson 2.14.0 and enable Fast Double Parser

### PR DESCRIPTION
**Pull request by ChrisHegarty**
Upgrade the version of Jackson used by XContent to 2.14.0 and enable the [Fast Double Parser](https://github.com/FasterXML/jackson-core/issues/577).

### CODE REVIEW

**Comment by ChrisHegarty** [comment]
@elasticmachine update branch

**Comment by ChrisHegarty** [comment]
@elasticmachine update branch

**Comment by ChrisHegarty** [comment]
@elasticmachine update branch

**Comment by ChrisHegarty** [comment]
@elasticmachine update branch

**Comment by ChrisHegarty** [comment]
@elasticmachine update branch

**Comment by ChrisHegarty** [comment]
@elasticmachine update branch

**Comment by ChrisHegarty** [comment]
@elasticmachine update branch

**Comment by ChrisHegarty** [comment]
@elasticmachine update branch

**Review by grcevski — APPROVED** [review]
LGTM!

**Pull request merged**
