### PR TITLE
[Test] Add missing RCS feature flag check for ApiKey BWC tests

### LINKED ISSUE #95936: [CI] ApiKeyBackwardsCompatibilityIT testCreatingAndUpdatingApiKeys failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/asdl4ohmg4kbo/tests/:x-pack:qa:rolling-upgrade:v7.17.11%23oneThirdUpgradedTest/org.elasticsearch.upgrades.ApiKeyBackwardsCompatibilityIT/testCreatingAndUpdatingApiKeys

**Reproduction line:**
```
./gradlew ':x-pack:qa:rolling-upgrade:v7.17.11#oneThirdUpgradedTest' -Dtests.class="org.elasticsearch.upgrades.ApiKeyBackwardsCompatibilityIT" -Dtests.method="testCreatingAndUpdatingApiKeys" -Dtests.seed=70FA5E0E792F0654 -Dtests.bwc=true -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dtests.locale=sr-Latn-ME -Dtests.timezone=Europe/Vatican -Druntime.java=20
```

**Applicable branches:**
8.8

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.upgrades.ApiKeyBackwardsCompatibilityIT&tests.test=testCreatingAndUpdatingApiKeys

**Failure excerpt:**
```
java.lang.AssertionError: 
Expected: a string containing "all nodes must have version [8.8.0] or higher to support remote indices privileges for API keys"
     but: was "method [POST], host [http://127.0.0.1:32837], URI [/_security/api_key/grant], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"parse_exception","reason":"failed to parse role [my_role]. unexpected field [remote_indices]"}],"type":"x_content_parse_exception","reason":"[7:541] [grant_api_key_request] failed to parse field [api_key]","caused_by":{"type":"x_content_parse_exception","reason":"[7:541] [api_key_request] failed to parse field [role_descriptors]","caused_by":{"type":"x_content_parse_exception","reason":"[7:541] [role_descriptors] failed to parse field [my_role]","caused_by":{"type":"parse_exception","reason":"failed to parse role [my_role]. unexpected field [remote_indices]"}}}},"status":400}"

  at __randomizedtesting.SeedInfo.seed([70FA5E0E792F0654:71D90DD488FB6843]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.junit.Assert.assertThat(Assert.java:923)
  at org.elasticsearch.upgrades.ApiKeyBackwardsCompatibilityIT.testCreatingAndUpdatingApiKeys(ApiKeyBackwardsCompatibilityIT.java:128)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

```

### PR DESCRIPTION
**Pull request by slobodanadamovic**
Resolves https://github.com/elastic/elasticsearch/issues/95936

### CODE REVIEW

**Comment by slobodanadamovic** [comment]
@elasticmachine update branch

**Comment by slobodanadamovic** [comment]
@elasticmachine run elasticsearch-ci/part-1-fips
@elasticmachine run elasticsearch-ci/part-1-fips

**Comment by slobodanadamovic** [comment]
@elasticmachine run elasticsearch-ci/release-tests

**Review by ywangd — APPROVED** [review]
LGTM

**Pull request merged**
