### PR TITLE
Default max concurrent search req. numNodes * 5

### LINKED ISSUE #30994: Query latency increases with multiple shards
**Description of the problem including expected versus actual behavior**:

With https://github.com/elastic/elasticsearch/pull/30783 we have reduced the number of maximum concurrent shard requests to the number of nodes but at most 256. Previously this was dependent on the number of nodes and old default number of shards (5).

In our benchmarks we see an increase of query latency for benchmarks which explicitly set the number of shards to 5 (e.g. [geonames](https://elasticsearch-benchmarks.elastic.co/#tracks/geonames/nightly/30d) or [geopoints](https://elasticsearch-benchmarks.elastic.co/#tracks/geopoint/nightly/30d)). For example, the 50th percentile latency for the polygon query in [geopoints](https://elasticsearch-benchmarks.elastic.co/#tracks/geopoint/nightly/30d) has increased from 59 ms to 153 ms. Similary, for the painless_static query in [geonames](https://elasticsearch-benchmarks.elastic.co/#tracks/geonames/nightly/30d) the 50th percentile service time has increased from 504 ms to 1488 ms (the system is completely saturated in the latter case and it makes no sense to look at latency that's why I mentioned service time here).

**Steps to reproduce**:

The problem can be reproduced with the following Rally benchmarks:

```
# state after PR 30783
esrally --revision=d7040ad7b41 --track="geonames" --include-tasks="create-index,index-append,force-merge,painless_static"
# manually revert https://github.com/elastic/elasticsearch/pull/30783 
cd $(awk -F " = " '$1~/^src\.root\.dir/ {print $2}' ~/.rally/rally.ini)/elasticsearch
git revert 2984734197223003dc80ed1ac4e8366f8d49ed1c
# state before (i.e. d7040ad7b41 without 29847341972)
esrally --revision=current --track="geonames" --include-tasks="create-index,index-append,force-merge,painless_static"
# reset your local state again!
git reset --hard origin/master
```

Unfortunately you have to manually revert the work introduced in https://github.com/elastic/elasticsearch/pull/30783 because we had [yet another regression](https://github.com/elastic/elasticsearch/issues/30801) in between that caused Elasticsearch to OOM (which was fixed by https://github.com/elastic/elasticsearch/pull/30820).

### PR DESCRIPTION
**Pull request by s1monw**
We moved to 1 shard by default which caused some issues in how many
concurrent shard requests we allow by default. For instance searching
a 5 shard index on a single node will now be executed serially per shard
while we want these cases to have a good concurrency out of the box. This
change moves to `numNodes * 5` which corresponds to the default we used to 
have in the previous version.

Relates to #30783
Closes #30994

### CODE REVIEW

**Review by jasontedor — APPROVED** [review]
LGTM.

**Review by jpountz — CHANGES_REQUESTED** [review]
I'm a bit unhappy that it breaks the rule that searching N indices with 1 shard performs the same as searching 1 index with N shards. Since the right value for this parameter doesn't really have anything to do with the number of shards per index, I'd rather like the limit to be the node count times some constant, possibly 5 to avoid changing too much the runtime behavior compared to previous versions.

**Comment by s1monw** [comment]
> I'm a bit unhappy that it breaks the rule that searching N indices with 1 shard performs the same as searching 1 index with N shards. 

this is a very good reason I agree we shouldn't do it. I will open a PR to move it to 5 to not change any thing compared to 6.x and we can discuss if we wanna change it after that.

**Review by jpountz — APPROVED** [review]
Thanks @s1monw.

**Comment by s1monw** [comment]
@jasontedor FYI

**Review by jasontedor — CHANGES_REQUESTED** [review]
This feels odd to me. We are using five as the multiplicative factor because we used five in the past because we used five as the default number of shards because a long time ago someone decided that five a good number of default shards. It feels weird to be stuck to that number now.

**Comment by jpountz** [comment]
I like `num_nodes*5` because it means that we only start trading latency if you query more than 5 shards **per node** on average. It feels like a good default number to me, which I see as completely independent of the number of shards **per index**. Any value in the [4,8] range sounds like a good default to me. I suggested 5 because it minimizes the change in runtime behavior compared to previous versions but I don't see keeping the exact same value as a requirement.

**Comment by s1monw** [comment]
While I do agree with @jpountz I still think it has issues. For instance it doesn't take into account the nodes in a remote cluster which can cause issues in CCS. I think we should look into finding a better default but I see this particular PR rather as rolling back a regression and get the benchmarks back to where they used to be. I suggest the following: 

 * lets merge this PR as it its. I will do that in a bit
 * I will open a new issue and make it a blocker for 6.4 and 7.0 since we also should fix this in the 6.x series if we find a better default.

**Comment by s1monw** [comment]
@jpountz @jasontedor see #31192 I detached the regression from finding a better default which is crucial.

**Comment by jasontedor** [comment]
That works for me, thanks @s1monw.

**Pull request merged**
