### PR TITLE
Benchmark api: removed leftovers

### PR DESCRIPTION
**Pull request by javanna**
Removes any mention of the benchmark api from 1.x, which has been backed out a while ago, but there were still some references to it here and there.

### CODE REVIEW

**Comment by bleskes** [comment]
LGTM. I take it that nothing needs be done on master?

**Comment by javanna** [comment]
thanks for the review @bleskes ! this is only for 1.x, master still contains the benchmark api as a whole.

**Comment by javanna** [comment]
I wonder if we should backport this to `1.5` and `1.4` though

**Comment by bleskes** [comment]
+1 to back port to 1.5 and 1.4 . Code impact is minimal and it's important to remove the docs imho

**Comment by javanna** [comment]
Marked as breaking for `elasticsearch-test` as it changes the constructor signature for `InternalTestCluster` and removes the `numBenchNodes` from `TestCluster`.

**Pull request merged**
