### PR TITLE
Deprecate index audit output type

### PR DESCRIPTION
**Pull request by albertzaharovits**
This PR deprecates the index audit output.
In general, the problem with it is that event indexing can be slower than the rate with which audit events are generated, especially during the daily rollovers or the rolling cluster upgrades. In this  situation audit events will be lost which is a terrible failure case for an audit system.

I will follow-up with the removal PR for 7.0 .

Relates https://github.com/elastic/elasticsearch/issues/29881

CC @ycombinator

### CODE REVIEW

**Comment by ycombinator** [comment]
The beats work to handle this deprecation is close to being done: https://github.com/elastic/beats/pull/8852

**Review by jaymode — APPROVED** [review]
LGTM

**Review by jaymode — CHANGES_REQUESTED** [review]
Sorry I was too quick with the LGTM. This should also add a check in `NodeDeprecationChecks`

**Comment by albertzaharovits** [comment]
Ah, right.
I was planning to add this in the follow-up 7.0 PR that actually removes the output type because the deprecation check will be admonishing that the output type has been removed. But the 7.0 PR does not touch the 6.x branch but the check has to sit in 6.x. I will add the check.

**Comment by albertzaharovits** [comment]
@jaymode  I went for a new PR to add the `NodeDeprecationChecks`. The files for these are only stubs in master so I guess the idiomatic way to add these is a 6.x PR which I have opened here https://github.com/elastic/elasticsearch/pull/37671 . I will follow with a master only PR to remove the output altogether and add the  `/migration/migrate_7_0/settings.asciidoc` notice.

**Pull request closed without merging**
