### PR TITLE
Patch to calculate the no. of physical cores on s390x

### PR DESCRIPTION
**Pull request by Nayana-ibm**
The method used to calculate physical cores on a system in existing code doesn't support s390x. 
 Added a patch to calculate the no. of physical cores on s390x by using the "nproc --all" command to get the number of installed processors on a system (core count)

### CODE REVIEW

**Comment by Nayana-ibm** [comment]
Can someone review the changes

**Comment by mark-vieira** [comment]
I'm a bit hesitant to add any specific handling build just for IBM Z support. Is there a reason why the default fallback to using `Runtime.availableProcessors()` is insufficient?

**Comment by jasontedor** [comment]
We draw a fairly firm line about not adding code for platforms that we do not support. We have no possibility to maintain it, since we do not have CI infrastructure in place to detect when it is that we might break this change, or this platform in other ways.

**Comment by jasontedor** [comment]
Note that our [pull request template](https://raw.githubusercontent.com/elastic/elasticsearch/master/.github/PULL_REQUEST_TEMPLATE.md) indicates this too:

>If submitting code, have you checked that your submission is for an OS and architecture that we support?

**Comment by mark-vieira** [comment]
As Jason says, since we have no practical way to test this behavior and ensure it works I'm going to go ahead and close this. As mentioned, the fallback method should continue to work. Also, you can supply a "manual" value for this via `-Dtests.jvms=` if you want to better tune the build.

**Comment by Nayana-ibm** [comment]
If you are interested adding support for s390x architecture, we are ready to provide vms and support. 
Please let us know.

**Pull request closed without merging**
