### PR TITLE
Scripting: fallback to declaring class javadoc

### PR DESCRIPTION
**Pull request by stu-elastic**
If use the 'declaring' class's version of a method's javadoc if
the current class does not have javadoc for the method.

So, if HashMap.java's toString() has no javadoc, fall back to Object.java.

### CODE REVIEW

**Review by jdconrad — APPROVED** [review]
LGTM. One question - does this handle interfaces to fallback to if necessary?

Edit: one other thing - this may not pick up the correct version of the JavaDoc since the declaring class of a method may be multiple classes away, but the best JavaDoc is only one class away. I think this should be okay for almost all cases, though.

Example - C extends B extends A
B and A both have JavaDocs, but the original declaring class was A, so we lose out on the JavaDoc in B.

**Comment by stu-elastic** [comment]
This uses the painless "delcaring" information to find where an API comes from, while keeping a cache of parsed java files.  It does not use reflection to walk anything.

**Comment by stu-elastic** [comment]
Issue for correctly walking the type hierarchy rather than relying on declaring: https://github.com/elastic/elasticsearch/issues/69072

**Comment by stu-elastic** [comment]
master (v8): 36b6914
7.x (v7.12): 60cb99e

**Pull request merged**
