### PR TITLE
Fields API - add ignored field values to results

### LINKED ISSUE #74121: Fields option in _search API does not returned fields above ignore_above
If you create an mapping containing an `ignore_above` field and ingest values that are above that limit, those are not returned by via the fields API. Since we're using the fields API nowadays in Discover this is a rather severe regression we found. From my experience we often have people having fields containing values above those limits, which were with reading from `_source` available and visible to the users. Using the new fields API, those will simply return as empty and no longer show in Discover.

It would be good if we can include those values in the response (whether behind a request flag, similar to `include_unmapped` or by default).

Related Kibana issue: https://github.com/elastic/kibana/issues/101232

### PR DESCRIPTION
**Pull request by markharwood**
Since Kibana's Discover switched to retrieving values via the fields API rather than source there have been gaps in the display caused by "ignored" fields (those that fall foul of `ignore_above` and `ignore_malformed` size and formatting rules).

This PR retrieves and returns ignored values from source when a user-requested field is mentioned in the `_ignored` field for a document. In these cases the corresponding hit adds a new `ignored_field_values` section in the response.

Closes #74121

### CODE REVIEW

**Comment by markharwood** [comment]
For now I've kept the attempt at de-duplication logic for fields with arrays that mix ignored and unignored values.
This can be removed if we decide that's desirable.

**Review by jimczi — COMMENTED** [review]
I think that the `FieldFetcher` could be made responsible to retrieve these ignored values ?
The deduplication doesn't seem very solid and requires to parse the values twice.
So we could integrate the ignored values as additional informations that the field fetcher can report. Does that make sense ?

**Comment by markharwood** [comment]
Something like this on FieldFetcher?:

   public DocumentField fetchIgnoredValues(SourceLookup sourceLookup, String fieldName) throws IOException 

I assume the caller would pass `foo.keyword` and the mapped field would be responsible for figuring out in needs to access source's `foo`. (Is there a smart way to know that `foo.keyword` or `foo.text` etc is a multi-field derived from `foo` in source?)

**Comment by jimczi** [comment]
Can we plug the logic in the lookup directly, in `FieldFetcher::fetchValues(SourceLookup)` ? We can add a `List<Object> ignoredValues` that the implementation needs to fill ?

**Comment by markharwood** [comment]
>We can add a List<Object> ignoredValues that the implementation needs to fill ?

So using this existing method:

    public Map<String, DocumentField> fetch(SourceLookup sourceLookup) throws IOException {

and adding a map entry keyed on `_ignored` ?

**Comment by jimczi** [comment]
I was more thinking of something like: `FieldFetcher::fetchValues(SourceLookup lookup, List<Object> mutableList)` ?

**Comment by markharwood** [comment]
Closing in favour of https://github.com/elastic/elasticsearch/pull/78697 which uses a different data gathering approach

**Pull request closed without merging**
