### PR TITLE
[client] Fix decompressed response headers

### LINKED ISSUE #63314: [client] Decompressed gzip responses report inconsistent encoding values
Found while working on PR https://github.com/elastic/elasticsearch/pull/63230#discussion_r500103593.

When a gzip-encoded response is received:
* `response.getEntity().getContentEncoding()` is `null` (thanks to `GZIPDecompressingEntity`)
* `response.getHeader("Content-Encoding")` is `gzip`

As the entity presented to the application is no more encoded, both values should be `null`. We should therefore remove the response's `Content-Encoding` header in [`RestClient.convertResponse`](https://github.com/elastic/elasticsearch/blob/847a020e417320f6b1c02b816eda71ce79fe5fae/client/rest/src/main/java/org/elasticsearch/client/RestClient.java#L303-L308) where gzipped responses are decoded.

### PR DESCRIPTION
**Pull request by swallez**
When a gzip-encoded response is decompressed the response should no more
have a content-encoding header and content-length should be set to
"unknown". GzipDecompressingEntity correctly does this for the entity
but the response still reported the original response's content-encoding
and content-length headers.

Fixes #63314

### CODE REVIEW

**Comment by swallez** [comment]
@elasticmachine update branch

**Review by andreidan — APPROVED** [review]
LGTM, thanks for fixing this @swallez

**Comment by horwreed** [comment]
@swallez Did this change ever get built into any 7.x versions? I see this tagged with 7.11.0 but I don't see this change in the 7.11.0 artifact or any other 7.x versions.

**Comment by swallez** [comment]
@horwreed indeed it wasn't backported, which is an oversight. I'll take care of it so that it goes in the next 7.17 patch release.

**Comment by swallez** [comment]
@horwreed done, backported in #84581. It will be part of 7.17.2. Thanks for noticing this!

**Comment by horwreed** [comment]
Great! Thank you for backporting @swallez

**Pull request merged**
