### PR TITLE
Better exception if array passed to `term` query.

### LINKED ISSUE #11246: Better exception if array passed to `term` query
Example: in the query "term" : ["doc1", "doc2", "doc3"] only "doc3" will be searched. 

I think an error message would be more preferable in case of array, as this is not immediately obvious and might take some time to track down why the query is not returning the expected values (as it happened to me). The user probably meant to run a "terms" query. 

Steps to reproduce:

<pre>
curl -XDELETE localhost:9200/test 
curl -XPUT localhost:9200/test/test/1 -d ' { "title": "doc1"} '
curl -XPUT localhost:9200/test/test/2 -d ' { "title": "doc2"} '
curl -XPUT localhost:9200/test/test/3 -d ' { "title": "doc3"} '

// Query will only return doc3
curl -XGET localhost:9200/test/test/_search -d  '{"query":{"term":{"title": ["doc1", "doc2", "doc3"]}}}'
</pre>

### PR DESCRIPTION
**Pull request by spyk**
Added a check that explicitly throws an exception in case of an array, and a small unit test to verify it. 

By the way, the particular test case would not throw an exception before the fix, but would actually only evaluate the last value of the array, so the behavior was indeed erratic in case of an array.

Closes #11246.

### CODE REVIEW

**Comment by javanna** [comment]
Hi @spyk thanks for your PR, would you mind signing our [CLA](http://www.elastic.co/contributor-agreement) so we can merge it in please?

**Comment by spyk** [comment]
Yep, signed yesterday just after the PR, do I need to do anything else to update the status?

**Comment by clintongormley** [comment]
Yes - I see the signature, it uses a different email address.  thanks @spyk

**Comment by javanna** [comment]
Thanks @spyk merged! Also marking as breaking as people who might be sending an array will get errors back now.

**Comment by clintongormley** [comment]
I think this is a bug fix rather than a breaking enhancement - relabelled as such.

**Pull request closed without merging**
