### PR TITLE
Fix OriginationDate parsing tests.

### LINKED ISSUE #47143: IndexLifecycleInitialisationTests.testExplainParseOriginationDate fails on master branch
The failure looks like:

```
  2> java.lang.AssertionError: 
    Expected: is <-15566169600000L>
         but: was <1568419200000L>
        at __randomizedtesting.SeedInfo.seed([847145622A974840:A81C994D7CD6D469]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.xpack.ilm.IndexLifecycleInitialisationTests.lambda$testExplainParseOriginationDate$7(IndexLifecycleInitialisationTests.java:296)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:867)
        at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:840)
        at org.elasticsearch.xpack.ilm.IndexLifecycleInitialisationTests.testExplainParseOriginationDate(IndexLifecycleInitialisationTests.java:294)
```

It reproduces for me with:

```
./gradlew ':x-pack:plugin:ilm:test' --tests "org.elasticsearch.xpack.ilm.IndexLifecycleInitialisationTests.testExplainParseOriginationDate"  -Dtests.seed=847145622A974840  -Dtests.security.manager=true  -Dtests.locale=th-TH-u-nu-thai-x-lvariant-TH  -Dtests.timezone=Libya  -Dcompiler.java=12  -Druntime.java=11
```

A build scan is available here: https://gradle-enterprise.elastic.co/s/66aqfqvmlqrrk

### PR DESCRIPTION
**Pull request by andreidan**
Drop the usage of `SimpleDateFormat` and use the `DateFormatter` instead.

Fixes #47143

### CODE REVIEW

**Review by dakrone — APPROVED** [review]
LGTM

**Comment by andreidan** [comment]
@elasticmachine update branch

**Comment by andreidan** [comment]
retest this please

**Comment by andreidan** [comment]
@elasticmachine update branch

**Comment by andreidan** [comment]
@elasticmachine update branch

**Pull request merged**
