### PR TITLE
Fix line length for aliases and remove suppression

### PR DESCRIPTION
**Pull request by dliappis**
Relates #34884

### CODE REVIEW

**Comment by dliappis** [comment]
jenkins run the gradle build tests 1

**Comment by dliappis** [comment]
jenkins run the default distro tests

**Review by dakrone — APPROVED** [review]
LGTM

**Comment by dliappis** [comment]
jenkins run the gradle build tests 2

**Comment by dliappis** [comment]
jenkins run the gradle build tests 2

**Comment by dliappis** [comment]
Cherry picked 6.x -> 28e8561992167080da3fcbb9018dce197953539a

**Pull request merged**
