### PR TITLE
Accept more ingest simulate params as ints or strings

### PR DESCRIPTION
**Pull request by gaobinlong**
Relates to #65992.

Seem to #23823.

`_version`, `_if_seq_no` and `_if_primary_term` params in the `simulate pipeline` API cannot be parsed correctly when the value is `integer` or`string` type. 

This PR fix the bug and modify the test method to test it.

### CODE REVIEW

**Comment by tvernum** [comment]
@elasticmachine test this please

**Comment by probakowski** [comment]
@elasticmachine ok to test

**Comment by probakowski** [comment]
@elasticmachine update branch

**Review by probakowski — APPROVED** [review]
LGTM, thank you @gaobinlong for fixing this!
I'll get this merged and backported.

**Comment by probakowski** [comment]
I found a problem during backport `version`, `_if_seq_no` and `_if_primary_term` are longs but currently `simulate` will fail if you provide number bigger than max integer. I have fix for that and I'll open PR soon and only merge it to `7.x` after that (that mean it'll probably land in `7.13`)

**Pull request merged**
