### PR TITLE
Fix token Invalidation when retries exhausted

### PR DESCRIPTION
**Pull request by albertzaharovits**
Fixes a glitch that misses to call the index invalidation listener, when retry count is exhausted and there are still tokens to be retried.

_I recommend the split diff to better visualize the change_

### CODE REVIEW

**Review by jaymode — APPROVED** [review]
LGTM

**Comment by albertzaharovits** [comment]
both https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+default-distro/8166/consoleFull and https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-bwc/1448/consoleFull are plagued by:
```
java.lang.IllegalStateException: Message not fully read (request) for requestId [398], action [cluster:monitor/nodes/stats[n]], available [0]; resetting
```
In a multitude of independent tests. I'm going to assume a transient network failure.

**Comment by albertzaharovits** [comment]
@elasticmachine run elasticsearch-ci/default-distro

**Comment by albertzaharovits** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by albertzaharovits** [comment]
The failures were utterly alien and I think they were due to the https://github.com/elastic/elasticsearch/pull/39512 missing in the PR . I have merged master in.

**Review by jkakavas — APPROVED** [review]
LGTM.

**Comment by albertzaharovits** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by albertzaharovits** [comment]
For https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-bwc/1539/console I have raised https://github.com/elastic/infra/issues/9993

**Pull request merged**
