### PR TITLE
Test rpm and deb signing

### PR DESCRIPTION
**Pull request by nik9000**
Adds a dummy gpg key to distribution/src/test/resources and uses it to sign the deb
and rpm every build. Then it tests that they are properly signed in the
vagrant tests.

Also renames `gpg.keyname` to `gpg.key` everywhere. The deb and rpm packages
used `gpg.key` and some other modules used `gpg.keyname`. Now they all use
`gpg.key`.

Finally reset gpg.keypath to ~/.gnupg in the release script to keep it working
after this patch lands. We'll be defaulting gpg.keypath to
`${project.parent.basedir}/src/test/resources/dummyGpg` to test rpm and
deb signing with every package build rather than just on release. The
release should default the keypath back to `~/.gnupg`.

### CODE REVIEW

**Comment by nik9000** [comment]
@spinscale can you have another look at this? Its been too long.

**Comment by nik9000** [comment]
I just reran the tests - it passes on all of the vagrant machines.

**Comment by nik9000** [comment]
@spinscale any chance you can look at this again? It looks like it is still merge-able but its been so long that I think it needs more eyes on it.

**Comment by spinscale** [comment]
ran this on linux and osx (no rpm though), checked the sigs afterwards. Was good.

However when ran with a custom GPG key, it still seemed to fallback to the dummy one (or I named the arguments wrong?)

```
mvn clean verify -Dskip.unit.tests=true -Dgpg.key=ID -Dgpg.passphrase=SECRET -Dgpg.keyring=~/.gnupg/secring.gpg
```

log

```
[INFO] spawn rpm --define _gpg_name B6C6BB45 --define _gpg_path /home/spinscale/x-pack/elasticsearch/distribution/src/test/resources/dummyGpg --addsign elasticsearch-2.2.0-SNAPSHOT20160129130403.noarch.rpm
[INFO] Enter pass phrase:
[INFO] gpg: WARNING: unsafe permissions on homedir `/home/spinscale/x-pack/elasticsearch/distribution/src/test/resources/dummyGpg'
[INFO] gpg: skipped "$KEYID": No secret key
[INFO] gpg: signing failed: No secret key
[INFO] Pass phrase check failed or gpg key expired
```

did I get a parameter wrong?

**Comment by nik9000** [comment]
> `gpg.keyring`

I believe its `gpg.keypath` with this.  The trouble was that we used both of those names for it in different places. I just picked a name.

**Comment by nik9000** [comment]
Maybe I should just do this against master and not maven at all. Its likely that all the build stuff has changed anyway there so any disruption I cause is less likely to matter.

**Comment by spinscale** [comment]
ok, passed on Linux with `gpg.keypath` configured appropriately. Also the custom key was used (important for the release, which uses `gpg.keypath`). IMO we should still add this to 2.x, so it is part of CI. I guess the release process will be different on master, because the release script needs to be changed a lot to do all the gradle calls to build and deploy.

**Comment by nik9000** [comment]
OK! I'm going to give it one last kick on my side and then try and forward port this to master as well.

**Comment by nik9000** [comment]
OK! Passed locally. Hurray! I'll merge now and have a look at forward porting to master.

**Pull request merged**
