### PR TITLE
Fixing typo in node.asciidoc

### PR DESCRIPTION
**Pull request by Leaf-Lin**
TIP block was missing due to the lack of line break prior to the "TIP" line

### CODE REVIEW

**Comment by debadair** [comment]
@elasticmachine Retest this please

**Review by debadair — APPROVED** [review]
LGTM. I think the build failure must have been a transient thing, re-running. 

This should also be applied to the  7.x and master branches.

**Comment by Leaf-Lin** [comment]
Thanks, @debadair , is there an easy way to push the same change to 7.x and master? or should those be done by going to each individual branch and make adjustment independently?

**Comment by debadair** [comment]
I usually cherry-pick & push to the other branches. I'll just go ahead and merge the fix and port it for you.

**Pull request merged**
