### PR TITLE
Bump TransportVersion to first non-Version constant

### PR DESCRIPTION
**Pull request by thecoop**
Use first non-Version TransportVersion CURRENT constant. It needs to be one that is still accepted by 7.17 clusters (so <9,000,000).

Once this is merged, the new procedures for managing transport versions are in effect. A new TransportVersion constant needs to be defined for every separate serialization change within ES.

### CODE REVIEW

**Comment by thecoop** [comment]
@elasticsearchmachine rerun elasticsearch-ci/part-1

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by thecoop** [comment]
@elasticsearchmachine rerun elasticsearch-ci/part-3

**Comment by thecoop** [comment]
@elasticmachine update branch

**Pull request merged**
