### PR TITLE
Unmute and add debug traces to CloseWhileRelocatingShardsIT

### PR DESCRIPTION
**Pull request by tlrx**
Note: this is a work in progress pull request, please do not review. The failing test does not reproduce on master or locally so I'm creating this pull request to have the test run on CI where it reproduces quite often.

This pull request unmutes the CloseWhileRelocatingShardsIT test and add debug traces to better understand why it fails.

### CODE REVIEW

**Comment by tlrx** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by tlrx** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by tlrx** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by tlrx** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by tlrx** [comment]
@elasticmachine run tests

**Comment by tlrx** [comment]
@elasticmachine test this please

**Comment by tlrx** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by tlrx** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by tlrx** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by danielmitterdorfer** [comment]
@tlrx please be aware that we have removed the `6.x` branch in the repository. I have changed the base branch now to point to `6.7`.

**Comment by tlrx** [comment]
Thanks @danielmitterdorfer. I opened this PR in order to reproduce a test failure on our CI (but it always passed) so we can keep this closed :)

**Pull request closed without merging**
