### PR TITLE
SQL: Add backwards-compatibilty frame for clients

### PR DESCRIPTION
**Pull request by bpintea**
This PR adds the framing code used for introducing a backwards-compatiblity breaking change, in respect to SQL's clients.

The PR also adds in a few collateral minor refactorings, meant to ease expanding the existing tests whenever a new feature is added, mostly geared towards new types being added.

### CODE REVIEW

**Comment by bpintea** [comment]
Code is mostly lifted from #65145; that PR might contain some conversations relevant to these changes.

**Comment by bpintea** [comment]
@elasticmachine run elasticsearch-ci/default-distro

**Comment by bpintea** [comment]
@elasticmachine update branch

**Comment by mark-vieira** [comment]
@elasticmachine update branch

**Comment by bpintea** [comment]
PR partially applied along with date nanos introduction.

**Pull request closed without merging**
