### PR TITLE
metadata processing optimization, rebalance and allocation separation.

### PR DESCRIPTION
**Pull request by hanbj**
Our cluster has encountered a bottleneck in metadata operations. so we optimized it. 
In our production environment has been running for about half a year, compared with the previous, there are dozens of times the performance improvement.

### CODE REVIEW

**Review by ywelsch — CHANGES_REQUESTED** [review]
This is an interesting optimization that we wanted to look into as well at some point. One difference I had in mind when it comes to the implementation in this PR was to not reroute based on a schedule, but do the delayed full reroute by submitting a lower priority cluster state update task, so that other tasks with higher priority can make progress. I also don't think it makes sense to separate out `moveShards` as a separate step from `allocateUnassigned` and `rebalance`, as `moveShards` can  be triggered by more events than just setting changes. For example, disk watermarks going above a certain threshold will trigger a move of shards.

Have you run our existing test suite on this changes?

**Comment by hanbj** [comment]
image
I think it makes sense to separate . For example: do we need to rebalance immediately to create or delete an index? Do we need to execute the logic of the moveShards () method to create or delete an index? And so on. Each method traverses all indexes and shards, which has no effect when the number of indexes and shards is relatively small, but our cluster has more than 30,000 indexes and more than 300,000 shards. A metadata change takes several minutes.

The task that led to our cluster piled up hundreds of thousands.

submitting a lower priority cluster state update task is right, So I made priority normal. so that other tasks with higher priority can make progress.

**Comment by hanbj** [comment]
When performing metadata change operations, long-time thread cards are found in balance ByWeights (), shardsWithState (), awaitAllNodes () and other methods by printing stack.

**Comment by hanbj** [comment]
When frequently performing metadata change operations, thread long-time cards are found in balance ByWeights (), shardsWithState (), awaitAllNodes () and other methods by printing stack.
image

**Comment by ywelsch** [comment]
@hanbj I've made some suggestions on how to evolve this PR and also left a specific question about the tests, on which you have not commented. As noted above, we are interested in improving the system along the lines you've suggested, but with some adjustments. Are you interested in exploring that solution and taking this PR forward? If not, I would prefer to close this PR and open an issue instead to track this as an open item.

>  but our cluster has more than 30,000 indexes and more than 300,000 shards

300,000 shards in a single cluster is perhaps a bit too much. Splitting this cluster up into multiple separate clusters will help with the general cluster health, improve fault-tolerance of the system and make operational tasks such as cluster restarts etc. much faster. With that high number of shards, you will also encounter other issues, not only related to shard balancing. Think for example about shard-level stats/metric collection etc.

**Comment by hanbj** [comment]
@ywelsch It is my pleasure and honor to discuss with you the solution to this problem.
Sorry, I'm too busy to follow up on this PR recently. I'm going to improve the code and add some tests. Mr. Dave CTurner's code is great, But I don't work. That's the best way.

**Comment by ywelsch** [comment]
Closing this due to inactivity

**Comment by hanbj** [comment]
@ywelsch  Thank you, I found that this is still a problem, we are planning to implement it from another namespace way, ES cluster can be infinitely expanded, so this is the reason why I have not updated this pr for so long. I am very sorry.

**Pull request closed without merging**
