### PR TITLE
Mute InternalAutoDateHistogramTests.testReduceRandom

### PR DESCRIPTION
**Pull request by hub-cap**
Relates #54540
Relates #39497

### CODE REVIEW

**Review by nik9000 — APPROVED** [review]
:metal:

**Comment by ywangd** [comment]
This fails for [7.6](https://gradle-enterprise.elastic.co/s/l5k2n2rq7sz2k) as well. Do we need backport?

**Comment by nik9000** [comment]
> This fails for [7.6](https://gradle-enterprise.elastic.co/s/l5k2n2rq7sz2k) as well. Do we need backport?

This'll fail for every branch for the past while. If it is a nuisance then we should. The failure seems to have started December 5th. I have no idea why it hasn't shown up until now.

**Comment by nik9000** [comment]
#45796 is where I bisected this failure to last night.

**Comment by nik9000** [comment]
Which enables the test. So it might go back further. I have no idea.

**Comment by nik9000** [comment]
Ok. You'll love this. It doesn't fail for me now. On any commit. *that* makes me think it is related to the current time. I'm going to start there!

**Comment by nik9000** [comment]
[Ha](https://github.com/elastic/elasticsearch/blob/master/server/src/test/java/org/elasticsearch/search/aggregations/bucket/histogram/InternalAutoDateHistogramTests.java#L71)!!!!!!

**Comment by ywangd** [comment]
@nik9000 I have no idea what the tests were doing. How does the current time affect the test results? Could you please elaborate a bit? Thanks

**Comment by nik9000** [comment]
Check it out! https://github.com/elastic/elasticsearch/pull/54602

The short version is that the test data depended on the current time (in
epoch millis) and sometimes it'd hit the bug and sometimes not. The PR I
liked fixes it.

**Pull request merged**
