### PR TITLE
Add local lucene/XGeoPoint* classes

### PR DESCRIPTION
**Pull request by nknize**
This PR adds the new GeoPoint classes to our local lucene package for supporting geo_point version 2 in the 2.1 release. It also removes some of the redundancy in the existing utility classes. This will help in transitioning from current ES GeoPoint indexing classes to those in lucene. They will be removed once all GeoPoint APIs are finalized in lucene.

### CODE REVIEW

**Comment by jpountz** [comment]
These X* classes tend to be very painful to maintain when doing Lucene upgrades. Maybe we should use the GeoPoint classes from Lucene directly on master and 2.x? (and upgrade the snapshot when there are changes we want to integrate in elasticsearch?)

Also maybe we shouldn't try to get those geo improvements on the 2.1 branch to avoid having to maintain a fork there?

**Comment by mikemccand** [comment]
Are the X* classes here identical to what's in Lucene 5.x today?

**Comment by nknize** [comment]
No, these X* classes are not the same as whats in lucene 5.3 (which is the current version for 2.1). LUCENE-6724 is in 5.4, LUCENE-6778 adds the DistanceRangeQuery that still needs to be committed along with LUCENE-6780 (pre BKD test merge).

**Comment by s1monw** [comment]
@nknize I wonder if we should push stuff in here that has not yet been committed to lucene. It might cause some incompatibilities and a the overhead seems pretty high as @jpountz said. I wonder if we should push the stuff that is not yet committed to lucene to 2.2 and only get in what is in lucene 5.3 for now?

**Comment by jpountz** [comment]
>  I wonder if we should push the stuff that is not yet committed to lucene to 2.2 and only get in what is in lucene 5.3 for now?

+1

**Comment by nknize** [comment]
> I wonder if we should push the stuff that is not yet committed to lucene to 2.2 and only get in what is in lucene 5.3 for now?
++ Good plan. The GeoPoint encoding was finalized and pushed to branch_5x this morning. So I'm going to wait until 2.2 for the full GeoPointV2 feature merge.

**Comment by s1monw** [comment]
@nknize I unlabeled it...

**Pull request closed without merging**
