### PR TITLE
Fix ILM HLRC Javadoc->Documentation links

### PR DESCRIPTION
**Pull request by AthenaEryma**
Several links from the ILM HLRC Javadoc to the online documentation were
not updated when the ILM HLRC documentation was written. This commit
fixes those links.

### CODE REVIEW

**Review by dakrone — APPROVED** [review]
LGTM

**Review by hub-cap — APPROVED** [review]
LGTM but the javadoc URLs are broken on 2 lines like the following

```
     *  https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/
     *  java-rest-high-ilm-ilm-delete-lifecycle-policy.html
```

**Comment by dakrone** [comment]
> the javadoc URLs are broken on 2 lines like the following

This is unfortunately because of the 140 character limit. It's a sad side effect.

**Comment by gwbrown** [comment]
Opened https://github.com/elastic/elasticsearch/issues/48089 for the test failure.
@elasticmachine run elasticsearch-ci/2

**Comment by gwbrown** [comment]
@elasticmachine update branch

**Pull request merged**
