### PR TITLE
Make Desired Nodes API operator-only

### LINKED ISSUE #87777: Make desired node operator only
The new Desired Nodes API was introduced it #82975. We need to make it [operator-only](https://www.elastic.co/guide/en/elasticsearch/reference/8.3/operator-only-functionality.html#operator-only-functionality).

### PR DESCRIPTION
**Pull request by arteam**
Resolves #87777.

### CODE REVIEW

**Comment by arteam** [comment]
@elasticmachine update branch

**Review by fcofdez — COMMENTED** [review]
Thanks Artem! I was wondering if we should write a test to ensure that the authorization policy is enforced.

**Comment by arteam** [comment]
Good point! Let me see if can write an intergration test for this use case.

**Review by fcofdez — APPROVED** [review]
LGTM, thanks Artem!

**Comment by arteam** [comment]
Thanks Francisco!

**Comment by fcofdez** [comment]
@arteam I've just noticed that we didn't update the documentation with this change, would you mind opening a PR updating it? thanks!

**Comment by arteam** [comment]
Sure, let me take care of this.

**Comment by arteam** [comment]
Hey @fcofdez. It looks likes you already updated the docs part that lists the operator only APIs: https://github.com/elastic/elasticsearch/pull/82975/files#diff-7348c90a6eb98211295dafd41c39e24fd03f97518dce7c53cd1d8bec814934f1R25

Do you want to see some other mentions of that in the docs?

**Comment by fcofdez** [comment]
You're right 🤦, sorry for the noise and thanks for looking into this!

**Pull request merged**
