### PR TITLE
[8.15] Use deprecation logger for CLDR date format specifiers (#112917)

### PR DESCRIPTION
**Pull request by thecoop**
Backports the following commits to 8.15:
 - Use deprecation logger for CLDR date format specifiers (#112917)

### CODE REVIEW

**Comment by thecoop** [comment]
@elasticmachine rerun elasticsearch-ci/8.15.2

**Comment by thecoop** [comment]
elasticsearch-ci/bwc-snapshots

**Comment by thecoop** [comment]
@elasticmachine update branch

**Review by prdoyle — APPROVED** [review]
Confirmed this is exactly the same as #112917

**Pull request merged**
