### PR TITLE
Update painless and runtime field tests to use a replica

### PR DESCRIPTION
**Pull request by mark-vieira**
Similar to https://github.com/elastic/elasticsearch/pull/99835 we want to run these test in environments where 0 replicas is unsupported.

### CODE REVIEW

**Comment by mark-vieira** [comment]
Hmm, it seems requiring a replica can cause funky stuff here?

**Comment by rjernst** [comment]
> Does this mean that these stateful tests must run on a multi-node cluster?

I think it is somewhat the opposite, that by setting 0 replicas, the test can run on a single node (otherwise the index state would always be yellow).

> How can we author these tests to be agnostic to the topology of the cluster?

In stateful we often will want to run these with 0 replicas for the reason above, but also because if we ran with multiple nodes we have extra cost (another node to startup, plus double the writes for every index operation). I think we should keep the stateful tests as simple as possible, they shouldn't actually care about the replicas, they are trying to test functionality.

I wonder if we could achieve this by removing the number of replicas altogether from these tests. Simultaneously we can adjust the rest test framework to set a global template with the number of replicas to 0. Then in serverless we can adjust this setting for the test framework globally. Wdyt?

**Comment by mark-vieira** [comment]
Excuse my ignorance here in advance.

> I think it is somewhat the opposite, that by setting 0 replicas, the test can run on a single node (otherwise the index state would always be yellow).

Got it. So if I configure an index with 1 shard and 1 replica, I need at least a two node cluster because the replica has to be on a different node than the primary shard. In a single node cluster the replica can never be allocated, therefore the index will never report as green. Yes?

> Then in serverless we can adjust this setting for the test framework globally. Wdyt?

It's not clear to me why configuring an index with 0 replicas isn't supported in serverless. Is this intentional? Are replicas _never_ configured? If so, should we just ignore that setting outright? I agree, I think we should make the stateful tests alone and solve this elsewhere by making the tests compatible with serverless in a more generic way. I'm not sure a global index template in stateful is the right course of action here, as that might not always be appropriate. It might make more sense to change the defaults/assumptions in serverless instead, but I'm not sure exactly what that might be. It could mean some changes to support 0 replicas, ignoring that index setting altogether, or transforming/augmenting the tests in some way to change or omit that setting when executing the tests.

**Comment by masseyke** [comment]
> It's not clear to me why configuring an index with 0 replicas isn't supported in serverless

You can't search without a replica. Here's more information that @tlrx gave me offline:
```
At least 2 nodes are required with appropriate index / search roles, indices must have a replica to be searchable, and stateless plugin must be loaded.
```

**Comment by mark-vieira** [comment]
I'm closing this as I don't think we want to use this strategy long term.

**Pull request closed without merging**
