### PR TITLE
ESQL: Retry test on 403

### PR DESCRIPTION
**Pull request by nik9000**
Retry the async test when you get a 403 - that could be because security has not yet booted. We should have permission to fetch everything.

### CODE REVIEW

**Comment by nik9000** [comment]
I'm somewhat unsure this is right and will dig some more tomorrow.

**Review by alex-spies — APPROVED** [review]
If it's really just an occasional 403 due to the test cluster not being fully up, I think retrying is fine.

**Review by jakelandis — COMMENTED** [review]
LGTM w.r.t. security concerns. However, I do think this might be a latent bug for some error handling w.r.t. getting the translog. More details shard privately (not a security issue, just very long winded)

**Comment by jakelandis** [comment]
Also, don't forget to unmute in the serverless branch.

**Comment by nik9000** [comment]
@elasticmachine, test this please

**Pull request merged**
