### PR TITLE
Fix test examples for nori-analyzer

### PR DESCRIPTION
**Pull request by jso4342**
`C샤프` in English is `C#`, not `C++`.
(`C++` in Korean is `C플플`, `C쁠쁠` or `C플러스플러스`.)

It might be true that the writer used `C샤프` as just an independent example, regardless `C++`, but I think it is better to align them for better understanding.

### CODE REVIEW

**Comment by javanna** [comment]
@elasticmachine test this please

**Comment by javanna** [comment]
I ran tests and there seem to be relevant test failures. @jso4342 would you have time to a look at those?

**Comment by jso4342** [comment]
Sure, I'll have a look at it :) !

**Comment by jso4342** [comment]
@elasticmachine test it please

**Comment by jso4342** [comment]
@javanna I just switched `C샤프` to `C쁠쁠`, instead of changing `c++` to `c#`
and it gives no test failure!

**Comment by jso4342** [comment]
@elasticmachine test this please

**Comment by jso4342** [comment]
@elasticmachine test this please

**Comment by javanna** [comment]
@elasticmachine retest this please

**Comment by jso4342** [comment]
Hi @javanna, I just switched `C샤프` to `C쁠쁠`, instead of changing `c++` to `c#`.
I ran the tests but it has a failure with bwc test for some reasons and I'm trying to fix it now. 

I'll keep you updated and Merry Christmas!

**Comment by jso4342** [comment]
@elasticmachine please retest this

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Comment by benwtrent** [comment]
@elasticmachine retest this please

**Review by javanna — APPROVED** [review]
LGTM, tests are green.

**Pull request merged**
