### PR TITLE
Update BlobCacheBufferedIndexInput::readVLong to correctly handle negative long values

### PR DESCRIPTION
**Pull request by ChrisHegarty**
Update BlobCacheBufferedIndexInput::readVLong to correctly handle negative long values, which can be 10 bytes long.

I'll add a test for this in a followup PR, just wanna quash the bug quickly.

### CODE REVIEW

**Review by original-brownbear — APPROVED** [review]

**Comment by javanna** [comment]
@ChrisHegarty @original-brownbear I believe this affects 8.x as well, it just was not evident so far before https://github.com/apache/lucene/pull/602  which was a Lucene 10 change only. Would it make sense to expand testing and backport?

**Comment by original-brownbear** [comment]
I'd say so yes, no need to keep the inconsistent logic in 8.16 (10 bytes read in the vlong read util, 9 bytes check for the fast-path => that's just broken :))

**Comment by ChrisHegarty** [comment]
Backported to the `8.x` branch.

**Comment by ChrisHegarty** [comment]
For the archeologists; this bug in Elasticsearch's `BlobCacheBufferIndexInput` was uncovered by a Lucene 10 change, namely https://github.com/apache/lucene/pull/602/. `DataInput::readVLong` now reads negative vlongs, where it previously did not in 9.x.  Additionally, the `DataInput::readZLong` delegates to the overridable `DataInput::readVLong` to retrieve the actual bytes, where it previously delegated to a private method. These two subtle changes resulted in uncovering this long standing issue in ES.

**Comment by ChrisHegarty** [comment]
Example failure trace before this bug was fixed:

```
java.lang.IllegalStateException: this writer hit an unrecoverable error; cannot merge
	at org.apache.lucene.core@10.0.0/org.apache.lucene.index.IndexWriter.getNextMerge(IndexWriter.java:2408)
	at org.apache.lucene.core@10.0.0/org.apache.lucene.index.IndexWriter$IndexWriterMergeSource.getNextMerge(IndexWriter.java:6544)
	at org.elasticsearch.stateless@9.0.0/co.elastic.elasticsearch.stateless.engine.ThreadPoolMergeScheduler$1.onAfter(ThreadPoolMergeScheduler.java:119)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.onAfter(ThreadContext.java:996)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:31)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: java.nio.BufferUnderflowException
	at java.base/java.nio.Buffer.nextGetIndex(Buffer.java:713)
	at java.base/java.nio.HeapByteBuffer.get(HeapByteBuffer.java:172)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.common.io.stream.ByteBufferStreamInput.readVLong(ByteBufferStreamInput.java:116)
	at org.elasticsearch.blobcache@9.0.0/org.elasticsearch.blobcache.common.BlobCacheBufferedIndexInput.readVLong(BlobCacheBufferedIndexInput.java:179)
	at org.apache.lucene.core@10.0.0/org.apache.lucene.store.DataInput.readZLong(DataInput.java:213)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.index.codec.tsdb.TSDBDocValuesEncoder.decode(TSDBDocValuesEncoder.java:321)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.index.codec.tsdb.ES87TSDBDocValuesProducer$10.longValue(ES87TSDBDocValuesProducer.java:1140)
	at org.apache.lucene.core@10.0.0/org.apache.lucene.codecs.DocValuesConsumer$2.longValue(DocValuesConsumer.java:262)
	at org.apache.lucene.core@10.0.0/org.apache.lucene.index.SingletonSortedNumericDocValues.nextValue(SingletonSortedNumericDocValues.java:72)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.index.codec.tsdb.ES87TSDBDocValuesConsumer.writeField(ES87TSDBDocValuesConsumer.java:171)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.index.codec.tsdb.ES87TSDBDocValuesConsumer.writeSortedNumericField(ES87TSDBDocValuesConsumer.java:493)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.index.codec.tsdb.ES87TSDBDocValuesConsumer.addSortedNumericField(ES87TSDBDocValuesConsumer.java:483)
	at org.apache.lucene.core@10.0.0/org.apache.lucene.codecs.perfield.PerFieldDocValuesFormat$FieldsWriter.addSortedNumericField(PerFieldDocValuesFormat.java:119)
	at org.elasticsearch.metering@9.0.0/co.elastic.elasticsearch.metering.codec.RAStorageDocValuesFormatFactory$RAStorageDocValuesFormat$RAStorageDocValuesConsumer.addSortedNumericField(RAStorageDocValuesFormatFactory.java:94)
	at org.apache.lucene.core@10.0.0/org.apache.lucene.codecs.DocValuesConsumer.mergeSortedNumericField(DocValuesConsumer.java:394)
	at org.apache.lucene.core@10.0.0/org.apache.lucene.codecs.DocValuesConsumer.merge(DocValuesConsumer.java:151)
	at org.apache.lucene.core@10.0.0/org.apache.lucene.index.SegmentMerger.mergeDocValues(SegmentMerger.java:188)
	at org.apache.lucene.core@10.0.0/org.apache.lucene.index.SegmentMerger.mergeWithLogging(SegmentMerger.java:314)
	at org.apache.lucene.core@10.0.0/org.apache.lucene.index.SegmentMerger.merge(SegmentMerger.java:149)
	at org.apache.lucene.core@10.0.0/org.apache.lucene.index.IndexWriter.mergeMiddle(IndexWriter.java:5283)
	at org.apache.lucene.core@10.0.0/org.apache.lucene.index.IndexWriter.merge(IndexWriter.java:4749)
	at org.apache.lucene.core@10.0.0/org.apache.lucene.index.IndexWriter$IndexWriterMergeSource.merge(IndexWriter.java:6567)
	at org.elasticsearch.stateless@9.0.0/co.elastic.elasticsearch.stateless.engine.ThreadPoolMergeScheduler$1.doRun(ThreadPoolMergeScheduler.java:145)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:1023)
	at org.elasticsearch.server@9.0.0/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:27)
	... 3 more
```

**Comment by javanna** [comment]
Thanks for all the context Chris! It probably makes sense to backport to 8.16 too? :)

**Comment by ChrisHegarty** [comment]
> Thanks for all the context Chris! It probably makes sense to backport to 8.16 too? :)

Done.

**Pull request merged**
