### PR TITLE
Added enrollment_id to fleet-agents

### PR DESCRIPTION
**Pull request by juliaElastic**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)? yes
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md)? yes
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against main? Unless there is a good reason otherwise, we prefer pull requests against main and will backport as needed.  yes
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

Required for https://github.com/elastic/fleet-server/issues/2254

### CODE REVIEW

**Comment by juliaElastic** [comment]
Can someone help me how to fix the build failure?
Seeing this error in the bwc step:
`07:27:30 ERROR: Not all environment variables could be successfully injected. Check for similarly-named environment variables.`

**Comment by juliaElastic** [comment]
@elasticmachine update branch

**Comment by juliaElastic** [comment]
@elasticmachine update branch

**Review by rjernst — APPROVED** [review]
LGTM. Note that I don't think this needs a changelog entry, as it is an implementation detail of fleet, not something an Elasticsearch user will care about. I would remove the changelog and mark this as either `>non-issue` or `>refactoring`

**Pull request merged**
