### PR TITLE
Enhanced segment files sizes information in Nodes Stats/Indices Stats APIs

### PR DESCRIPTION
**Pull request by tlrx**
Since #16661 it is possible to know the total sizes for some Lucene segment files by using the Node Stats or Indices Stats API with the `include_segment_file_sizes` parameter,  and the list of file extensions has been extended in #71416.

This pull request adds a bit more information about file sizes like the number of files (`count`), the `min`, `max` and average file sizes in bytes that share the same extension. Here is a sample:
```
"cfs" : {
  "description" : "Compound Files",
  "size_in_bytes" : 2260,
  "min_size_in_bytes" : 2260,
  "max_size_in_bytes" : 2260,
  "average_size_in_bytes" : 2260,
  "count" : 1
}
```

This pull request also simplifies how compound file sizes were computed: before compound segment files were extracted and  sizes aggregated with regular non-compound files sizes (which I find confusing and out of the scope of the original issue #6728), now CFS/CFE files appears as distinct files.

I think that these information give a better view of the segment files and are useful in many cases, specially with searchable snapshots whose segment stats can now be introspected thanks to the `include_unloaded_segments` parameter.

### CODE REVIEW

**Review by ywelsch — APPROVED** [review]
> I think that these information give a better view of the segment files and are useful in many cases, specially with searchable snapshots whose segment stats can now be introspected thanks to the include_unloaded_segments parameter.

agree. LGTM

**Review by jpountz — APPROVED** [review]
+1 to make index stats about _files_. I think that some users found it useful to extract CFS files because it helped reason about what takes disk space, which hopefully #68508 will address.

**Comment by tlrx** [comment]
Thanks Yannick and Adrien!

**Comment by jpountz** [comment]
Is it breaking enough that it should only go in 8.0?

**Comment by tlrx** [comment]
> Is it breaking enough that it should only go in 8.0?

I think it can go in 7.13.0. The REST response contains more information now but the previous fields are unchanged; the set of files has been already extended in #71416 but existing extensions and descriptions remain the same (just more extensions now); CFS/CFE is computed differently but the memory infos are still the same.

**Comment by tlrx** [comment]
@ywelsch do you have an opinion?

**Comment by ywelsch** [comment]
I think this is not breaking for the reasons that you've outlined, so 7.13 is ok

**Comment by tlrx** [comment]
Thanks Yannick.

@jpountz unless you disagree I'll move forward with the backport (#71725)

**Comment by jpountz** [comment]
@tlrx I trust your judgement, I only wanted to make sure this question had been considered given the change to how CFS files are treated.

**Pull request merged**
