### PR TITLE
API for adding and removing indices from a data stream

### LINKED ISSUE #75852: Add an API for adding and removing indices from a data stream
Similar to the Aliases API, it would be useful to have an expert-level API for adding and removing indices from a data stream. So, copying from the aliases API, something similar to:

```
POST /_data_stream
{
  "actions": [
    {
      "add": {
        "index": "my-index",
        "data_stream": "my-data-stream"
      },
      "remove": {
        "index": "my-other-index",
        "data_stream": "my-data-stream"
      }
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by danhermann**
This PR includes just the REST endpoint. The service itself was added in previous PRs linked to #75852.

Closes #75852

### CODE REVIEW

**Comment by danhermann** [comment]
Pinging @elastic/kibana-stack-management since this is a new API

**Review by dakrone — COMMENTED** [review]
Generally looks good to me! I left a couple of comments but nothing major (I know it's still a draft PR also)

**Review by dakrone — CHANGES_REQUESTED** [review]
Okay I took another look at this, I left a few comments, hopefully nothing too major.

I was also wondering about documentation, are we planning on doing that in a follow-up PR?

**Comment by danhermann** [comment]
@elasticmachine update branch

**Review by dakrone — APPROVED** [review]
LGTM, I left one really minor comment that doesn't need another review after addressing.

Out of curiosity, do you think we should (in future work, not time-constrained) support changing which index is the write index of a data stream the same way that we support it for aliases? Does that even make sense for a data stream?

**Review by sethmlarson — CHANGES_REQUESTED** [review]
Some comments on the API specification:

**Review by sethmlarson — APPROVED** [review]
LGTM

**Pull request merged**
