### PR TITLE
Return an HTTP error code when a suggest request failed instead of 200

### PR DESCRIPTION
**Pull request by obourgain**
The `_suggest` API always returns 200 regardless of the call being successful or not.
This PR sets the http status in a way similar to the SearchResponse https://github.com/elastic/elasticsearch/blob/master/src/main/java/org/elasticsearch/action/search/SearchResponse.java#L71

### CODE REVIEW

**Comment by s1monw** [comment]
I like this change, can we instead of duplicating the functionality add a static method to `RestStatus` that looks like this `public static RestStatus status(int successfulShards, int totalShards, ShardOperationFailedException... failures)` and use it in both places?

**Comment by s1monw** [comment]
@areek I assigned this to you, can you take care of it?

**Comment by obourgain** [comment]
With a quick search, it seems that there are some other place that have a similar loop over failures and could also use a static method.

**Comment by s1monw** [comment]
> With a quick search, it seems that there are some other place that have a similar loop over failures and could also use a static method.

cool, if you could update your PR that would be awesome!

**Comment by obourgain** [comment]
I updated it with the ```status()``` method on ```RestStatus``` as suggested.

```CountResponse```, ```RestSuggestAction```, ```SearchResponse``` and ```SnapshotInfo``` will use this method.

For the record, there are also loops over failures in ```SearchPhaseExecutionException``` and ```DeleteByQueryResponse``` but they are quite different so I didn't try to modify those.

**Comment by areek** [comment]
@obourgain Thanks for the the PR! This looks good to me. I will merge this in early next week

**Comment by s1monw** [comment]
@areek it's pretty low risk and is a bug, should we pull it for 1.5?

**Comment by areek** [comment]
@s1monw makes sense, will merge it in

**Comment by areek** [comment]
Merged to 1.x (https://github.com/elastic/elasticsearch/commit/35fcdf5d0b8d3f29acfe39f6a1f9eb8e8491f5f3) and master (https://github.com/elastic/elasticsearch/commit/deade2eb714f5bfabb3022f5297f29b02be0bd9a)

**Pull request closed without merging**
