### PR TITLE
Fix auto-generated eclipse try/catch to be less trappy

### PR DESCRIPTION
**Pull request by rmuir**
When generating a try-catch block, the eclipse default is something like this:

```
try {
  something();
} catch (Exception e) {
  // TODO: auto-generated stub
  e.printStackTrace();
}
```

which is terrible, so the ES eclipse changes this to rethrow a RuntimeException instead.

```
try {
  something();
} catch (Exception e) {
  throw new RuntimeException();
}
```

Unfortunately, this loses the original exception entirely, instead it should be:

```
try {
  something();
} catch (Exception e) {
  throw new RuntimeException(e);
}
```

### CODE REVIEW

**Comment by rmuir** [comment]
note: its been like this in maven for a while, just now seems like a good time to fix it. its unrelated to gradle changes.

**Comment by nik9000** [comment]
LGTM.

I guess eclipse thinks `\n` is for the weak.

**Comment by jpountz** [comment]
LGTM

**Comment by uschindler** [comment]
LGTM

**Comment by rmuir** [comment]
I added a commit fixing some suspicious places of this in the codebase today (mostly tests)

**Comment by rjernst** [comment]
LGTM

**Pull request merged**
