### PR TITLE
Add delete_data flag to DeleteRollupJob endpoint

### LINKED ISSUE #31347: [Rollup] Add ability to delete rollup data
Deleting rollup data (as opposed to the rollup job) is done manually today.  If there is only a single job per rollup index, this is an easy process: just delete the index.

But if multiple jobs share a single index, the user needs to execute a Delete-By-Query against the job name to purge the relevant rollup docs.  Theoretically, the should also update the `_meta` of the index to remove the job config, so that the job name can be reused.  

This was documented in https://github.com/elastic/elasticsearch/pull/31299, but it's really too much to ask users to do.  

Our DeleteJob API should either have a flag to also delete the data, or a separate endpoint should be added which is dedicated to purging rollup data.

### PR DESCRIPTION
**Pull request by polyfractal**
This adds a flag, `delete_data`, which allows the user to optionally delete the data and job config from the rollup index.

Setting this to true will:

1. Delete the allocated and persistent task (as before)
2. Run a Delete-by-query to purge documents belonging to the job from the rollup index
3. Update the mapping of the rollup index to remove the job's config from the _meta field.

Note: this can only be run for an "active" job that has an existing task.  I think we will want to support deleting "historical" jobs that no longer have an active job (e.g. jobs that were previously deleted with the API, but the data left intact).  But I didn't want to complicate this PR too much, and that can be improved in a followup.

Closes https://github.com/elastic/elasticsearch/issues/31347

### CODE REVIEW

**Comment by polyfractal** [comment]
@elasticmachine run elasticsearch-ci/docbldesx

**Review by jimczi — COMMENTED** [review]
The change looks good. However I wonder if we should check if the index is used by only one rollup job in order to avoid the delete by query. In this case we could simply delete the index instead of running a delete by query that will effectively remove all documents from the index. WDYT ?

**Comment by polyfractal** [comment]
I'd love to do that, but haven't figured out a clean way to do it yet.  Open to suggestions.

The issue is that we need to avoid a secondary PutRollupJob request happening at the same time and accidentally deleting the index right after a different job has been added to it.  It's made complicated because of the flow:

1. Request is rerouted to master so we know where the allocated task is.  Master tells allocated task to shutdown
2. Allocated task shuts down, optionally performing DBQ.  The rationale is that it's better to do DBQ here because it could take a long time and we don't want that on the master if we can avoid it.
3. When done, head back to the master, purge config from _meta

In both step 1 and 3 we're on the master and could definitively know if there is another job.  If we handled that in step 1, we'd still have to go talk to the allocated task so it can shut down, so we'd need some way to "lock" the index and prevent a new job from being allocated to it, then delete it in step 3.

Or we could do it in step 3 (shut down task, return to master, see if there are no more jobs, then delete directly).  A potential problem is _if_ a job got allocated, we're now on the master and need to perform a DBQ.

### Proposal 1
Current PR, always DBQ.  I agree it'd be nice to just delete the index though, as I think most people will have a single job per index

### Proposal 2
In step 1, purge the config from the mapping and put some kind of `"_meta": { "_rollup": "LOCKED" } }` identifier in it's place, preventing other jobs from allocating

### Proposal 3
Just let the master perform a DBQ if needed, might take a while but it's mostly just waiting for the async call to come back.  Maybe not a problem?

### Proposal 4, re-evaluating current architecture
Disallow multiple jobs per index.  Would be a breaking change, but we've talked about it on multiple occasions.  No need for DBQ, no need to edit mappings.  Would simplify rollup search since we only have one job to consider.  Since adding null buckets to composite, we no longer need multiple jobs to represent one dataset.  

The same arguments exist as before though: many jobs could end up being small (after compression) so having many rollup indices is a waste.  That said, I think it's probably going to be common to map one job to one index (especially when we have ILM support)

**Comment by polyfractal** [comment]
Minor update: Jim and I chatted and we're going to investigate "Proposal 4" (single job per index) in more detail.  It would radically simplify several parts of Rollup, and should play nicer with ILM support.

Going to hold off on this PR until I've had a chance to look into the alternative proposal a bit more.

**Pull request closed without merging**
