### PR TITLE
Replace TokenizerFactory with Supplier

### PR DESCRIPTION
**Pull request by original-brownbear**
Handles TODOs from https://github.com/elastic/elasticsearch/pull/24869
* Replaces all occurences of TokenizerFactory with `Supplier<Tokenizer>`
* Remove unused parameter from constructor

### CODE REVIEW

**Comment by jpountz** [comment]
I'm not entirely convinced by this change since it removes existing consistency with the char filter and token filter factories?

**Comment by original-brownbear** [comment]
@jpountz I guess with @nik9000 removing the `name()` methods from those factories those could be turned into `Supplier<?>`s as well? (just guessing here though, I'm fine closing this if it's just noise :))

**Comment by jpountz** [comment]
I see. I guess I'm still a bit torn since this is part of our plugin API so we could regret replacing these factories with a supplier which doesn't allow adding new methods with a default implementation. So this might prevent from introducing new functionality in minor releases. @nik9000 what do you think?

**Comment by nik9000** [comment]
We're still a ways off from semvering the plugin API so I think it'd be fine. Though it looks like I should revive my old PR about removing the names....

**Review by nik9000 — APPROVED** [review]
I'm happy with the change if @jpountz is on board with it.

**Comment by jpountz** [comment]
Even if the plugin API is not officially stable, this change is breaking, doesn't provide much value and could prevent from introducing changes in a backward-compatible way in the future so I'd rather not merge it. Sorry @original-brownbear I hope you didn't spend too much time on this one.

**Comment by original-brownbear** [comment]
@jpountz no worries I didn't :)

... that said, should I maybe just revert all the `Supplier`ish changes in here, keep the `name` removal and just remove the `Supplier` todo?

**Comment by jpountz** [comment]
+1

**Comment by original-brownbear** [comment]
done :)

**Comment by original-brownbear** [comment]
@jpountz can you take another look when you have a minute? <= Should be a really short one now :)

**Review by jpountz — APPROVED** [review]
Sorry I had written a LGTM yesterday but I must have forgotten to hit the "submit" button. Thank you.

**Comment by original-brownbear** [comment]
@jpountz np+thanks! :) label+merge to 7.0 and 6.x right?

**Comment by jpountz** [comment]
I'd only do 7.0 to not break existing analysis plugins.

**Pull request merged**
