### PR TITLE
[TEST] Improve ESSingleNodeTestCase repeatability

### PR DESCRIPTION
**Pull request by javanna**
If we conditionally do random things, e.g. initialize a node only after the first test, we have to make sure that we unconditionally create a new seed calling `random.nextLong()`, then initialize the node under a private randomness context. This makes sure that any random usage through `Randomness.get()` will retrieve the proper random instance through `RandomizedContext.current().getRandom()`. When running under private randomness, the context  will return the `Random` instance that was created with the provided seed (forked from the main random instance) rather than the main `Random` that's exposed to tests as well. Otherwise tests become non repeatable because that initialization part happens only before the first executed test.

### CODE REVIEW

**Review by jpountz — APPROVED** [review]
Good catch!

**Comment by javanna** [comment]
I pushed a new commit and updated the description. I am not using runWithPrivateRandomness which fixes all the issues I've seen with repeatability.

**Review by jpountz — APPROVED** [review]
LGTM.

**Comment by jasontedor** [comment]
Nice one @javanna.

**Pull request merged**
