### PR TITLE
[ESQL] Dependency Injection for the Warnings Collector

### PR DESCRIPTION
**Pull request by not-napoleon**
This lays the groundwork for fixing https://github.com/elastic/elasticsearch/issues/108519, although I don't intend to fix it in this PR.  In order to address that issue, we need to be able to control at call time how we deal with warnings, but, prior to this work, the `ExpressionEvaluators` all hard code their warnings implementation.

~This PR will allow injecting in a different implementation when we create the evaluator.~  Unfortunately, this has fallen slightly short of that ambition.  We need to be able to construct evaluators from within compute, but the `Warnings` class, and it's `Source` dependency, are in the esql package, which we don't want to import into compute.  As result, I've pared this back to just passing in a boolean to toggle warnings collection, via a no-op collector implementation.  This is sufficient to solve the linked issue (still not done in this PR) and preserves our current encapsulation, while leaving a clear path to further refine how we control warnings in the future.

Note that this is changing the code generation, which means it will touch all of the generated files, which are still in source control.  The actual change is much smaller than the diff would imply.

### CODE REVIEW

**Comment by not-napoleon** [comment]
@elasticmachine update branch

**Comment by not-napoleon** [comment]
@elasticmachine update branch

**Review by nik9000 — APPROVED** [review]

**Comment by costin** [comment]
Had a chat with Mark about the logistics behind it - to avoid the noise of having every `ExpressionEvaluator.Factory.get()` method take a bool, the approach is to put the bool inside DriverContext.
This way the Factory can check what type of warning consumer to create based on the DriverContext instance.
Furthermore in case of folding, in ESQL, this is done in EvaluatorMapper inside the mapper package so the "special" create DriverContext used for folding (with the NON_RECYCLING_INSTANCE) could have be set there.
i.e.
```
```

**Comment by not-napoleon** [comment]
Closing in favor of https://github.com/elastic/elasticsearch/pull/108927.  With the requested changes and the large number of conflicts due to the big refactor, it was faster to just start from scratch.

**Pull request closed without merging**
