### PR TITLE
Rename service.bat to elasticsearch-service.bat

### LINKED ISSUE #17528: Rename service.bat to elasticsearch-service.bat
with 5.0 we renamed the plugin executables to elasticsearch-plugin. I think we should do the same with service.bat

@Mpdreamz thoughts?

### PR DESCRIPTION
**Pull request by gfyoung**
This hopefully should be short and sweet.  Closes #17528.

### CODE REVIEW

**Comment by clintongormley** [comment]
@Mpdreamz could you review please?

**Comment by Mpdreamz** [comment]
LGTM 👍 Could not locate other uses of `service.bat` not covered by this PR

**Comment by Mpdreamz** [comment]
Short and sweet thank you @gfyoung backported to `5.0` and `5.x` as well.

**Comment by dakrone** [comment]
@Mpdreamz I think this also needs a mention in the migration guide since it's a breaking change?

**Comment by Mpdreamz** [comment]
@dakrone you're right! will send a PR for this

**Pull request merged**
