### PR TITLE
Support much larger source filters

### PR DESCRIPTION
**Pull request by nik9000**
Kibana's long had a problems sending Elasticsearch thousands of fields
to the source filtering API. It's probably not right to send *thousands*
of fields to it, but, in turn, we don't really have a good excuse for
rejecting them. I mean, we do. We reject them to keep ourselves from
allocating too much memory and crashing. But we can do better. This
makes us tollerate significantly larger field lists much more
efficiently.

First, this changes the way we generate the "guts" of the filter API so
that we use a *ton* less memory thanks to Daciuk, Mihov, Watson,
and Watson: https://www.aclweb.org/anthology/J00-1002.pdf
Lucene has an implementation of their algorithm built right in. We just
have to plug it in. With this a list of four thousand fields generates
thirty four thousand automata states instead of hundreds of thousdands.

Next we replace the algorithm that the source filtering uses to match
dotted field names with one that doesn't duplicate the automata we
build. This cuts that thirty four thousand states to seventeen thousand.

Finally we bump the maximum number of automata states we accept from
10,000 to 50,000 which is *comfortable* enough to handle the number of
state need for that four thousand field list. 50,000 state automata will
likely weigh in around a megabyte of heap. Heavy, but fine. Thanks to
Daciuk, et al, you can throw absolutely massive lists of fields at us
before we get that large. I couldn't do it with copy and paste. I don't
have that kind of creativity. I expect folks will shy away from sending
field lists that are megabytes long. But I never expected thousands of
fields, so what do I know.

Those the are enough for to take most of what kibana's historically sent
us without any problems. They are still huge requests and they'd be
better off not sending massive lists, but at least now the problem isn't
so pressing. That four thousand field list was 120kb over the wire.
That's big request!

### CODE REVIEW

**Review by romseygeek — APPROVED** [review]
This looks great, thanks @nik9000!

**Review by majagrubic — APPROVED** [review]
Can't wait to test it out!

**Comment by jtibshirani** [comment]
@cbuescher with this improvement in place, could we remove the special optimization we added for the `fields` option in #69984?

**Comment by cbuescher** [comment]
@jtibshirani I was going to answer that I don't see significant downsides with the optmizations added in #69984, but now I looked at the implementation in this PR and am not sure anymore. I will need to check with @nik9000 a little bit around the details of what this PR does to see if it is along the same lines as what we tried to achieve in #69984.

**Comment by cbuescher** [comment]
Talked to @nik9000 f2f, if we had this change before implementing adding #69984 we probably wouldn't have needed it. Now however I think its still a bit safer to keep that solution in place since it doesn't really complicate the code much, this PR moves the upper bound for running into automaton sizing problems quite a bit but there still is an upper bound and lastly the performance of direct lookups of concrete field paths in #69984 shouldn't be too bad either. In the very unlikely situation this is happening in reality, the performance of the map lookup is probably the least of your problems. So in summary I don't think its worth removing the other optimization.

**Pull request merged**
