### PR TITLE
Misleading docs

### PR DESCRIPTION
**Pull request by jonny-no1**
The docs are misleading as adding a document would look like this:

``` bash
curl -XPOST 'http://localhost:9200/index/pin?pretty' -d '
{
    "location" : {
         "lat" : 46.8,
         "lon" : -71.2
   }
}'
```

The submitted JSON does not contain the pin node.

Here is a stackoverflow question on the same topic: http://stackoverflow.com/a/21663582/2106834

### CODE REVIEW

**Comment by foaly-nr1** [comment]
Just signed the CLA as well.

**Comment by jpountz** [comment]
I guess the confusion comes from the fact that 'pin' is the name of an outer object  in the docs. Then maybe we should remove references to 'pin' entirely? (even in the mappings definitions)

**Comment by foaly-nr1** [comment]
[Other parts of the docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-term-query.html) show the request to the server for both mapping definitions and documents. That'd be less confusing and still show the full information.

**Comment by clintongormley** [comment]
This has been fixed in the 2.0 docs https://www.elastic.co/guide/en/elasticsearch/reference/2.1/geo-point.html#geo-point

**Comment by foaly-nr1** [comment]
Excellent thanks, @clintongormley!

**Pull request closed without merging**
