### PR TITLE
[Java.time] Support partial parsing

### LINKED ISSUE #45284: Date field does not support partial dates anymore
On ES 6.x and below, date fields (i.e. fields of `"type": "date"`) used to accept values of the form `"2018-09"` (i.e. just year and month) whereas this no longer works on ES 7.x (tested on 7.3.0 and master).

This breaks recoveries from 6.x to 7.x and indexing pipelines.

### LINKED ISSUE #47473: BREAKING CHANGE - Range Query by Date Year returns no results
**Elasticsearch version** (`bin/elasticsearch --version`): 7.4.0

**Plugins installed**: ["mapper-size"]

**JVM version** (`java -version`): using official docker image.

**OS version** (`uname -a` if on a Unix-like system):using official docker image.

**Description of the problem including expected versus actual behavior**:
Date range queries that were working in 5.x latest are no longer when we upgraded to Elastic 7.x
 
# Here are the exact scripts needed to create the sample for 5.x
```
PUT /test
{
    "mappings" : {
        "doc": {
          "properties" : {
              "mydate" : { "type" : "date" }
          }
        }
    }
}

POST /test/doc/
{
  "mydate": "2016-07-23T00:00:00"
}

GET /test/_search

POST /test/_search
{
  "query": {
    "bool": {
      "filter": [
        {
          "bool": {
            "must": [
              {
                "range": {
                  "mydate": {
                    "gte": "2015",
                    "lte": "2017"
                  }
                }
              }
            ]
          }
        }
      ]
    }
  }
}

# This seems to be a bug as well. specifying any value in GTE returns the document.
POST /test/_search
{
  "query": {
    "bool": {
      "filter": [
        {
          "bool": {
            "must": [
              {
                "range": {
                  "mydate": {
                    "gte": "201555",
                    "lte": "2019"
                  }
                }
              }
            ]
          }
        }
      ]
    }
  }
}
```

# Here are the exact scripts needed to create the sample for 7.x

```
PUT /test
{
    "mappings" : {
        "properties" : {
            "mydate" : { "type" : "date" }
        }
    }
}

POST /test/_doc/
{
  "mydate": "2016-07-23T00:00:00"
}

GET /test/_search

POST /test/_search
{
  "query": {
    "bool": {
      "filter": [
        {
          "bool": {
            "must": [
              {
                "range": {
                  "mydate": {
                    "gte": "2015",
                    "lte": "2017"
                  }
                }
              }
            ]
          }
        }
      ]
    }
  }
}
```

The query returns no results on 7.x but returns results on 5.x. Also as shown in the query example above, it seems like you can put any numeric value in 5.x on the `gte` query and it will return results.

Changing the Elasticsearch 7.x query to include the full date format for `lte` returns results (along with invalid `gte` values)

```
POST /test/_search
{
  "query": {
    "bool": {
      "filter": [
        {
          "bool": {
            "must": [
              {
                "range": {
                  "mydate": {
                    "gte": "2015",
                    "lte": "2017-01-01"
                  }
                }
              }
            ]
          }
        }
      ]
    }
  }
}
```
or
```
POST /test/_search
{
  "query": {
    "bool": {
      "filter": [
        {
          "bool": {
            "must": [
              {
                "range": {
                  "mydate": {
                    "gte": "2015-01-01",
                    "lte": "2017-01-01"
                  }
                }
              }
            ]
          }
        }
      ]
    }
  }
}
``` 

or 
```
POST /test/_search
{
  "query": {
    "bool": {
      "filter": [
        {
          "bool": {
            "must": [
              {
                "range": {
                  "mydate": {
                    "gte": "2015555",
                    "lte": "2017-01-01"
                  }
                }
              }
            ]
          }
        }
      ]
    }
  }
}
```

I started digging into the formats and all breaking changes and all looks ok...  Interesting enough I noticed the following docs changed a bit and no longer talk as much about date range queries (between 6.x and 7.x
- https://www.elastic.co/guide/en/elasticsearch/reference/6.0/query-dsl-range-query.html
- https://www.elastic.co/guide/en/elasticsearch/reference/7.0/query-dsl-range-query.html

### PR DESCRIPTION
**Pull request by pgomulka**
Enable partial parsing of date part. This is making the behaviour in java.time implementation the same as with joda.
2018, 2018-01 and 2018-01-01 are all valid dates for `date_optional_time` or `strict_date_optional_time`
closes #45284
closes #47473

### CODE REVIEW

**Comment by niemyjski** [comment]
Any idea when 7.5.0 will be released (weeks/months)? This is somewhat of a blocker for us migrating off 5.x

**Comment by pgomulka** [comment]
@elasticmachine update branch

**Comment by pgomulka** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample-matrix

**Comment by niemyjski** [comment]
I don't want to have to do this on every date field that I have, and then have to reindex every index when this fix is out.

**Review by rjernst — APPROVED** [review]
LGTM

**Pull request merged**
