### PR TITLE
Deprecate ChunkingOptions parameter

### PR DESCRIPTION
**Pull request by ashm-dev**
Marked ChunkingOptions parameter as @Deprecated in multiple methods. Updated method signatures in InferenceService and SenderService classes. No functionality changes, just preparing for future removal.

### CODE REVIEW

**Comment by ashm-dev** [comment]
Closes https://github.com/elastic/elasticsearch/issues/117193

**Comment by ashm-dev** [comment]
Hello! 👋

This is my first PR to the ElasticSearch project, and I’m just starting to learn and explore this amazing system. I’d greatly appreciate any feedback, comments, or suggestions to help improve this PR or my approach to working with ElasticSearch.

Thank you in advance for your time and support!

**Comment by davidkyle** [comment]
@elasticmachine test this please

**Comment by davidkyle** [comment]
@ashm-dev, checking the codebase I don't see any uses of the `ChunkingOptions` parameter. I'm aware the linked issue was to deprecate the parameter but given the parameter is not used in the code I suggest removing the `ChunkingOptions` parameter entirely and skip the deprecation. Please can you make that change.

**Comment by ashm-dev** [comment]
> @ashm-dev, checking the codebase I don't see any uses of the `ChunkingOptions` parameter. I'm aware the linked issue was to deprecate the parameter but given the parameter is not used in the code I suggest removing the `ChunkingOptions` parameter entirely and skip the deprecation. Please can you make that change.

OK, I'll get on it and update the code, thank you for your help!)

**Comment by davidkyle** [comment]
@elasticmachine test this please

**Review by davidkyle — APPROVED** [review]
LGTM

Amazing, great work thank you @ashm-dev

**Comment by ashm-dev** [comment]
@elasticmachine test this please

**Comment by davidkyle** [comment]
@elasticmachine update branch

**Comment by davidkyle** [comment]
@elasticmachine test this please

**Comment by davidkyle** [comment]
@ashm-dev I enabled auto merge on this PR, it will be merged automatically once all the CI checks pass.

Thanks again for your contribution

**Comment by ashm-dev** [comment]
> @ashm-dev I enabled auto merge on this PR, it will be merged automatically once all the CI checks pass.
> 
> Thanks again for your contribution

Understood, thank you for your help!

**Pull request merged**
