### PR TITLE
Use single-char variant of String.indexOf() where possible

### PR DESCRIPTION
**Pull request by sabi0**
`indexOf(char)` is more efficient than searching for the same one-character String.

### CODE REVIEW

**Comment by kingherc** [comment]
@elasticmachine changelog

**Comment by kingherc** [comment]
buildkite test this

**Comment by kingherc** [comment]
Thanks for the PR ! Could you please fix formatting? (see https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md#formatting )

I will let the Core team review this PR to also comment on the performance of using a char vs a string.

**Comment by kingherc** [comment]
buildkite test this

**Comment by williamrandolph** [comment]
Looking at the code in Java's `String`, `StringLatin1`, and `StringUTF16`, the single-character search does go into a simpler algorithm. I don't know how this would hold up in a benchmark, but on the face of things I think the change makes sense.

**Comment by williamrandolph** [comment]
@elasticmachine update branch

**Comment by williamrandolph** [comment]
@elasticsearchmachine update branch

**Comment by williamrandolph** [comment]
buildkite test this

**Review by williamrandolph — APPROVED** [review]
This change looks good and tests pass. I'm going to merge.

**Pull request merged**
