### PR TITLE
Monitoring migration guide updates

### PR DESCRIPTION
**Pull request by jbaiera**
Adds additional documentation for the deprecation of the Monitoring plugin collection and shipping settings.

### Preview

https://elasticsearch_79756.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/7.16/migrating-7.16.html#breaking_716_monitoring_changes

### CODE REVIEW

**Comment by jbaiera** [comment]
@lcawl are we good to merge this PR or is there anything else I should look into updating?

**Review by lcawl — APPROVED** [review]
LGTM, thanks!

**Comment by jbaiera** [comment]
@elasticmachine update branch

**Comment by jbaiera** [comment]
@elasticmachine update branch

**Pull request merged**
