### PR TITLE
Support for weighted average in the 'avg' aggregator based an extensi…

### PR DESCRIPTION
**Pull request by lquerel**
Support for weighted average in the 'avg' aggregator. See a full description of the feature implemented here https://github.com/elastic/elasticsearch/issues/15731.

This commit only contains the implementation of the first approach based on the script attribute.

Below an example of script returning a value and a weight for each document matching the query. These two values are returned as a map and used by the AvgAggregator class to compute the weighted average accordingly.  

{"avg" : { "script" : "[value: doc['latency'].value, weight: doc['transaction'].value]" }}

Laurent

### CODE REVIEW

**Comment by jpountz** [comment]
I'm not against adding a way to compute weighted averages, but this implementation is too hacky in my opinion.

**Comment by lquerel** [comment]
Thank for your response. 
I agree that some modifications in ScriptDoubleValues are a little bit hacky :). But this is the only way that I found to keep additional values returned by the script. Can you provide some guidance to improve that and I'll update this pull request.

**Comment by dakrone** [comment]
@jpountz do you have any guidance to provide for this PR?

**Comment by jpountz** [comment]
Discussed in Fixit Friday: we are not happy with this way that weighted averages are exposed, but we will keep the issue open to try to assess whether the community needs this feature and explore how it could be exposed.

**Pull request closed without merging**
