### PR TITLE
Handles null limits in RangeQuery/Filter builders.

### LINKED ISSUE #9523: RangeFilterBuilder doesn't handle one of "from" or "two" being null
ES range filters allow omitting one of "from", "to". (Actually the docs don't say anything about this but it works in 1.4.3 at least).

RangeFilterBuilder doesn't handle this, though, and emits filters with
"from": "null"
or
"to": "null"

The doXContent method doesn't check the from and to fields for null.

Tested on 1.4.3 but the code is still the same in head: https://github.com/elasticsearch/elasticsearch/blob/master/src/main/java/org/elasticsearch/index/query/RangeFilterBuilder.java

### PR DESCRIPTION
**Pull request by knoxxs**
Checks and sets range limits only if they are not null.

Closes #9523

### CODE REVIEW

**Comment by knoxxs** [comment]
I have signed the CLA. Is there anything else I need to do after signing the CLA?

**Comment by jpountz** [comment]
@knoxxs The CLA validation failed just because you used a different email address to sign the CLA and in your commits. But I can see you in the CLA database so all is fine.

**Comment by jpountz** [comment]
@knoxxs You might want to add the email address that you used to sign the CLA to your github account so that validation works next time that you submit a PR.

**Comment by jpountz** [comment]
@knoxxs The change looks good to me. I am just unsure how useful the helper in ElasticsearchIntegrationTest is as it does not save much typing? (as a side note, you can call `get()` instead of `execute().actionGet()`)

**Comment by cbuescher** [comment]
@jpountz just looking at this PR, in the query refactoring on master we decided to always render null fields as long as the parser understands them, so I think we don't need those null checks on master any more. The integration test works however, so if @knoxxs wants to pick this up we can merge the test (now in SearchQueryIT). Otherwise I'd close this PR and the corresponding issue.

**Comment by knoxxs** [comment]
@cbuescher sure I can do that, if @jpountz confirms

**Comment by jpountz** [comment]
I'm good!

**Comment by knoxxs** [comment]
Sure will do

**Comment by clintongormley** [comment]
No further feedback. Closing

**Comment by karmi** [comment]
Hi @knoxxs, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/elasticsearch/pull/9703.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by karmi** [comment]
@knoxxs, apologies for the notification above, this is a fault from some manual testing... please ignore it.

**Pull request closed without merging**
