### PR TITLE
Fix NumberFieldMapper Referencing its Own Builder

### PR DESCRIPTION
**Pull request by original-brownbear**
Investigating the heap use of mapper instances I found this.
It seems quite a bit of overhead for these instances goes into
the builder field. In other mappers we retain the script service
and the script outright, so I did the same thing here to make these
instances a little smaller.

### CODE REVIEW

**Review by jtibshirani — COMMENTED** [review]
This makes sense to me! I did a search for `this.builder = builder` in classes named `*FieldMapper` and noticed we do this frequently, including popular types like `match_only_text`. Would it make sense to expand this to a broader change?

**Comment by jpountz** [comment]
@romseygeek I think you investigated a very similar issue a few months ago?

**Comment by original-brownbear** [comment]
>  Would it make sense to expand this to a broader change?

Right, didn't even notice that :) Makes sense to me, unless @romseygeek has objections? :)

**Review by romseygeek — APPROVED** [review]
@yannick found a similar problem with `text` fields using this pattern a few weeks ago.  We should definitely fix it - I have a longer term plan to rework how merges are done so that we only use builders and don't need to hold references to all these helper components but in the short term this is a good fix.

**Comment by ywelsch** [comment]
Relates https://github.com/elastic/elasticsearch/issues/73845

**Pull request merged**
