### PR TITLE
[Test] Flush response body for progress

### LINKED ISSUE #115145: [CI] S3BlobContainerRetriesTests testReadRetriesAfterMeaningfulProgress failing
**Build Scans:**
- [elasticsearch-periodic #4492 / openjdk23_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/lt2was7wdz7q4)
- [elasticsearch-periodic #4472 / openjdk23_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/i4g7dc62a5niq)

**Reproduction Line:**
```
./gradlew ":modules:repository-s3:test" --tests "org.elasticsearch.repositories.s3.S3BlobContainerRetriesTests.testReadDoesNotRetryForRepositoryAnalysis" -Dtests.seed=A7AA55C06421ED76 -Dtests.locale=ka -Dtests.timezone=SystemV/YST9YDT -Druntime.java=23
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testReadRetriesAfterMeaningfulProgress'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.repositories.s3.S3BlobContainerRetriesTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure Message:**
```
java.lang.AssertionError: failureCount=1
```

**Issue Reasons:**
- [main] 2 failures in test testReadRetriesAfterMeaningfulProgress (1.4% fail rate in 142 executions)
- [main] 2 failures in step openjdk23_checkpart1_java-matrix (40.0% fail rate in 5 executions)
- [main] 2 failures in pipeline elasticsearch-periodic (40.0% fail rate in 5 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #115164: [CI] S3BlobContainerRetriesTests testReadDoesNotRetryForRepositoryAnalysis failing
**Build Scans:**
- [elasticsearch-periodic #4507 / openjdk23_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/x352itjnopkom)
- [elasticsearch-periodic #4497 / openjdk23_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/m4buopj5qutf4)
- [elasticsearch-periodic #4492 / openjdk23_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/lt2was7wdz7q4)
- [elasticsearch-periodic #4477 / openjdk23_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/nxzzf7k5wycf2)
- [elasticsearch-periodic #4467 / openjdk23_checkpart1_java-matrix](https://gradle-enterprise.elastic.co/s/pqb7mklnocxgu)

**Reproduction Line:**
```
./gradlew ":modules:repository-s3:test" --tests "org.elasticsearch.repositories.s3.S3BlobContainerRetriesTests.testReadDoesNotRetryForRepositoryAnalysis" -Dtests.seed=C761DAFC96E801FE -Dtests.locale=kn-Knda-IN -Dtests.timezone=Europe/Dublin -Druntime.java=23
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testReadDoesNotRetryForRepositoryAnalysis'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.repositories.s3.S3BlobContainerRetriesTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure Message:**
```
java.lang.AssertionError: failureCount=1
```

**Issue Reasons:**
- [main] 5 failures in test testReadDoesNotRetryForRepositoryAnalysis (1.6% fail rate in 319 executions)
- [main] 5 failures in step openjdk23_checkpart1_java-matrix (55.6% fail rate in 9 executions)
- [main] 5 failures in pipeline elasticsearch-periodic (55.6% fail rate in 9 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by ywangd**
In JDK23, response headers are no longer always immediately sent. See also https://bugs.openjdk.org/browse/JDK-8331847
This PR adds flush call for the response body to make progress.

Resolves: #115145
Resolves: #115164

### CODE REVIEW

**Review by pxsalehi — APPROVED** [review]
I guess closes https://github.com/elastic/elasticsearch/issues/115164 too?

**Comment by ywangd** [comment]
Indeed. Thanks!

**Comment by ywangd** [comment]
@elasticmachine update branch

**Comment by pxsalehi** [comment]
This fails also in 8.x. Should we backport it?

**Comment by ywangd** [comment]
Yep done. Thanks for notice.

**Comment by pxsalehi** [comment]
did it backport? mine failed!

**Comment by ywangd** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.x|[](https://github.com/elastic/elasticsearch/pull/115209)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

**Comment by ywangd** [comment]
Odd it did not backport.
Had to do it manually with `backport --upstream elastic/elasticsearch --pr 115177`.

**Comment by ywangd** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.16|[](https://github.com/elastic/elasticsearch/pull/115613)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

**Pull request merged**
