### PR TITLE
Searchable snapshot number of prewarmers

### PR DESCRIPTION
**Pull request by henningandersen**
The number of prewarming workers to spawn was taken from the wrong
thread pool info, fixed to size number of workers after the prewarming
thread pool.

Relates #59313

### CODE REVIEW

**Review by tlrx — APPROVED** [review]
LGTM - Thanks for fixing this

**Comment by henningandersen** [comment]
Failure looks like #63880, so:
@elasticmachine update branch

**Comment by henningandersen** [comment]
@elasticmachine update branch

**Comment by henningandersen** [comment]
Unable to talk to jcenter, let us retry:
@elasticmachine run elasticsearch-ci/default-distro
@elasticmachine run elasticsearch-ci/packaging-sample-unix

**Pull request merged**
