### PR TITLE
Enable the health node and the disk health indicator #84811

### PR DESCRIPTION
**Pull request by gmarouli**
**Depends on https://github.com/elastic/elasticsearch/pull/90041**, the draft status remains to protect from a premature merge.

This PR removes the health node feature flag and enabled the disk health indicator. The following changes were made to ensure a safe rollout:
- Remove the feature flag.
- Bump the minimum version of all writeables to `8.5.0`, this ensures that during a rolling upgrade from `8.4.x` we will not introduce writeables that will be unknown to the older nodes because of the feature flag.
- Adjust tests that did not anticipate the health node persistent task.

### CODE REVIEW

**Comment by gmarouli** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by gmarouli** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by gmarouli** [comment]
Don't merge until https://github.com/elastic/elasticsearch/pull/90041 is merged.

**Review by dakrone — APPROVED** [review]
LGTM for when mergeable (after the required work)

**Comment by andreidan** [comment]
@elasticsearchmachine update branch

**Comment by andreidan** [comment]
@elasticmachine update branch

**Pull request merged**
