### PR TITLE
[DOCS] Reformat lowercase token filter docs

### PR DESCRIPTION
**Pull request by jrodewig**
Reformats the lowercase token filter docs as part of #44726.

### Changes

* Adds a title abbreviation
* Updates the description and adds a Lucene link
* Reformats the parameters section
* Adds analyze, custom analyzer, and custom filter snippets

### CODE REVIEW

**Comment by jrodewig** [comment]
@elasticmachine update branch

**Review by romseygeek — APPROVED** [review]
LGTM

**Comment by jrodewig** [comment]
Thanks @romseygeek.

**Comment by jrodewig** [comment]
master: 4dfc07c9228d1cb3dadee17165c941dae35986ab
7.x: 1186a5dc09432caa8041e2b680136997188a53c8
7.5: e00b303ffc78288295837423efba2c55c50ad3b5

**Pull request merged**
