### PR TITLE
Add index_mode to resolved indices in ESQL

### PR DESCRIPTION
**Pull request by dnhatn**
Add index_mode to the resolved indices in ESQL to enable appropriate planning for METRICS and LOGS commands.

### CODE REVIEW

**Review by astefan — COMMENTED** [review]
I think this PR is ok by itself 👍 .

I've taken a bit of time and looked at what we do with `IndexMode` and I think we can clean up things a bit here and there and probably things will get more clear when more support for index modes starts to be "visible" in functionality.

What I observed:
- `EsRelation` has both an `EsIndex` and an `IndexMode`. But `EsIndex` already contains the index modes.
- `UnresolvedRelation` gets first created in `LogicalPlanBuilder` where, depending on the command that uses the index pattern, the index mode is set to time series or standard. But this doesn't actually reflect the `TableIdentifier` true index mode (the one discovered in the IndexResolver). This is a confusing behavior. Should it maybe stay as `null` until it gets resolved in the Analyzer or is not needed at all in the `UnresolvedRelation`?
  -  when `EsRelation` is created in the `Analyzer` and where it's actually using the index mode from `UnresolvedRelation`, it already has knowledge of the true index modes of the indices. Or the index mode from `UnresolvedRelation` serves a different purpose? (ie this is a `from` or `metrics` command so we want to know the context under which the query runs)
- the same point about `EsRelation` stands for `EsSourceExec` and `EsQueryExec` (both `EsIndex` and `IndexMode` have the same knowledge)
  - like `EsSourceExec` and `EsQueryExec` should `EsStatsQueryExec` have a reference to index mode?

**Comment by dnhatn** [comment]
Thanks, @astefan. You're right. I plan to consolidate all these usages of IndexModes once this PR is merged.

**Review by astefan — APPROVED** [review]
LGTM

**Comment by dnhatn** [comment]
Thank you very much for your thoughtful review, Andrei!

**Pull request merged**
