### PR TITLE
Fix verify versions

### LINKED ISSUE #38708: Branch consistency fails in verifyVersion
```
./gradlew verifyVersions

> Configure project :benchmarks
=======================================
Elasticsearch Build Hamster says Hello!
  Gradle Version        : 5.1.1
  OS Info               : Linux 4.20.6-arch1-1-ARCH (amd64)
  JDK Version           : 11 (Oracle Corporation 11 [OpenJDK 64-Bit Server VM 11+28])
  JAVA_HOME             : /home/alpar/opt/jdk-11-28
  Random Testing Seed   : C94C5C47E0353AB5
=======================================

> Task :verifyVersions FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/home/alpar/work/elastic/elasticsearch/build.gradle' line: 147

* What went wrong:
Execution failed for task ':verifyVersions'.
> out-of-date released versions
  Following versions are not really released, but the build thinks they are: [6.7.0, 6.6.1]
```

### PR DESCRIPTION
**Pull request by alpar-t**
With this change, we filter out any versions more than too versions behind in `VersionCollection`
Also, to better reflect what it does, renamed the class to `BwcVersions`

Closes #38708 
Thanks @rjernst for highlighting the simpler approach.

### CODE REVIEW

**Comment by mark-vieira** [comment]
@atorok can you sort out the merge conflicts and ping for review when that's done?

**Comment by atorok** [comment]
@mark-vieira sorry about that, ready for review now.

**Comment by atorok** [comment]
run elasticsearch-ci/1

**Review by mark-vieira — APPROVED** [review]
:+1:

**Pull request merged**
