### PR TITLE
Bubbling up the mapping exception msg.

### LINKED ISSUE #12839: Mapping conflict exception not bubbling up to root cause
A mapping conflict such as:

    PUT my_index
    {
      "mappings": {
        "type_one": {
          "properties": {
            "text": {
              "type": "string",
              "analyzer": "standard",
              "search_analyzer": "whitespace"
            }
          }
        },
        "type_two": {
          "properties": {
            "text": {
              "type": "string"
            }
          }
        }
      }
    }

throws an exception like:

        {
           "error": {
              "root_cause": [
                 {
                    "type": "mapper_parsing_exception",
                    "reason": "mapping [type_two]",
                    "stack_trace": "MapperParsingException[mapping [type_two]]; ... 6 more\n"
                 }
              ],
              "type": "mapper_parsing_exception",
              "reason": "mapping [type_two]",
              "caused_by": {
                 "type": "illegal_argument_exception",
                 "reason": "Mapper for [text] conflicts with existing mapping in other types:\n[mapper [text] has different analyzer, mapper [text] is used by multiple types. Set update_all_types to true to update [search_analyzer] across all types.]",
                 "stack_trace": "java.lang....\n"
              },
              "stack_trace": "MapperParsingException[mapping [type_two]]; nested: IllegalArgumentException[Mapper for [text] conflicts with existing mapping in other types:\n[mapper [text] has different analyzer, mapper [text] is used by multiple types. Set update_all_types to true to update [search_analyzer] across all types.]];...\n"
           },
           "status": 400
        }

The `error.root_cause.reason` should contain the text from `error.type.caused_by.reason`

### PR DESCRIPTION
**Pull request by xuzha**
Closes #12839.

### CODE REVIEW

**Comment by rjernst** [comment]
We should not do this. The exception message is already there. Structured exceptions must be not following the cause chain all the way?

**Comment by xuzha** [comment]
Yea, pretty duplicated. 
I'm not quite sure if we need to change,  description saying "The error.root_cause.reason should contain the text from error.type.caused_by.reason".

**Comment by xuzha** [comment]
OK, the code follows the cause chain down to the last ES exception. In this case the root cause is MapperParsingException, which caused by IllegalArgumentException. We have full description in IllegalArgumentException rather than in MapperParsingException.

When print root cause, it just get MapperParsingException detail message and print it out.

**Comment by xuzha** [comment]
Close this, we should not do this

**Pull request closed without merging**
