### PR TITLE
Upgrade joda-time to 2.9.4

### LINKED ISSUE #14524: [CI failure] DateHistogramTests, "The datetime zone id 'CET' is not recognised"
Cannot reproduce this so far, but there are test failures in
* org.elasticsearch.messy.tests.DateHistogramTests.testDSTBoundaryIssue9491
* org.elasticsearch.messy.tests.DateHistogramTests.testIssue8209

http://build-us-00.elastic.co/job/es_core_2x_small/1726

```
org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction.raiseEarlyFailure(TransportSearchTypeAction.java:316)
	... 10 more
Caused by: java.lang.IllegalArgumentException: The datetime zone id 'Asia/Jerusalem' is not recognised
	at org.joda.time.DateTimeZone.forID(DateTimeZone.java:229)
	at org.elasticsearch.search.aggregations.support.ValuesSourceParser.token(ValuesSourceParser.java:119)
	at org.elasticsearch.search.aggregations.bucket.histogram.DateHistogramParser.parse(DateHistogramParser.java:97)
	at org.elasticsearch.search.aggregations.AggregatorParsers.parseAggregators(AggregatorParsers.java:198)
	at org.elasticsearch.search.aggregations.AggregatorParsers.parseAggregators(AggregatorParsers.java:103)
	at org.elasticsearch.search.aggregations.AggregationParseElement.parse(AggregationParseElement.java:60)
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:835)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:655)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:621)
	at org.elasticsearch.search.SearchService.executeDfsPhase(SearchService.java:266)
	at 
```

and

```
...
Caused by: java.lang.IllegalArgumentException: The datetime zone id 'CET' is not recognised
	at org.joda.time.DateTimeZone.forID(DateTimeZone.java:229)
	at org.elasticsearch.search.aggregations.support.ValuesSourceParser.token(ValuesSourceParser.java:119)
	at org.elasticsearch.search.aggregations.bucket.histogram.DateHistogramParser.parse(DateHistogramParser.java:97)
	at org.elasticsearch.search.aggregations.AggregatorParsers.parseAggregators(AggregatorParsers.java:198)
	at org.elasticsearch.search.aggregations.AggregatorParsers.parseAggregators(AggregatorParsers.java:103)
	at org.elasticsearch.search.aggregations.AggregationParseElement.parse(AggregationParseElement.java:60)
```

### LINKED ISSUE #18017: Issue with inline script using Joda DateTimeZone.
Using the offical Elasticsearch Docker image for 2.3.1

**Elasticsearch version**: 2.3.1

**JVM version**: java:8-jre

**OS version**: debian jessie

### Actual
Using DateTimeZone with an inline script results in an error. 
```
java.io.IOException: Resource not found: "org/joda/time/tz/data/America/New_York"
```

### Expected
The Correct DateTimeZone instance to be returned.

## **Steps to reproduce**:
1. Start elasticsearch 2.3.1.
1. Pass the startup param `-Des.script.engine.groovy.inline.aggs=true`
1. Create index and mapping with a `date_time_no_millis` field.
1. Run a search query like the one in `Appendix: A`
1. Notice an error like `The datetime zone id 'America/New_York' is not recognised`
1. Run a Date Histogram query like the one in `Appendix: B`
1. The same error will occur
1. Restart the elasticsearch instance
1. Re-run Appendix A and B, they now both work.

### A: Aggregate Query
```json
{
  "size": 0,
  "aggs": {
    "group_by_hour": {
      "terms": {
        "script": "def opDate = new DateTime(doc['operation_date'].date); opDate.withZone(DateTimeZone.forID('America/New_York')).getHourOfDay()",
        "order": {
          "_term": "asc"
        }
      }
    }
  }
}
```

### B: Date Histogram Query
```json
{
  "size": 0,
  "aggs": {
    "group_by_hour": {
      "date_histogram": {
        "field": "date_field",
        "interval": "hour",
        "format": "H",
        "time_zone": "America/New_York"
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by jasontedor**
This commit upgrades joda-time to version 2.9.4 to integrate a bug fix
there into Elasticsearch.

Closes #14524, closes #18017

### CODE REVIEW

**Comment by jpountz** [comment]
LGTM

**Comment by gmoskovicz** [comment]
😀

**Comment by deanobarnett** [comment]
Awesome!

**Comment by s1monw** [comment]
good! thanks @jasontedor

**Comment by jasontedor** [comment]
Backports:
 - 2.3: a9642baffd5e50c51f4b82e2ed6be7645cc7bf64
 - 2.x: 37583581db166fb9c3cd779c779cb5105e9ad66e

**Comment by gmoskovicz** [comment]
@jasontedor will it be included in a 2.2.x release?

**Comment by jasontedor** [comment]
> will it be included in a 2.2.x release?

No, the 2.2.x series will not see a maintenance release for this.

**Pull request merged**
