### PR TITLE
TSDB: Fix error when we sort by `_tsid`

### PR DESCRIPTION
**Pull request by csoulios**
The `SearchSortValues` allows only instances of `Boolean`, `String` and `Number` fields so that it presents the value of the `sort` fields in the results. This results in an error when sorting by `_tsid` 

The following test:

```
  - do:
      search:
        index: test
        body:
          sort:   [ "_tsid", "@timestamp" ]
```

The error  returned is:
```
»  java.lang.AssertionError: {k8s.pod.uid=947e4ced-1786-4e53-9e0c-5c447e959507, metricset=pod} was not formatted
»       at org.elasticsearch.search.SearchSortValues.<init>(SearchSortValues.java:49) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
»       at org.elasticsearch.search.SearchHit.sortValues(SearchHit.java:496) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
»       at org.elasticsearch.action.search.SearchPhaseController.getHits(SearchPhaseController.java:357) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
»       at org.elasticsearch.action.search.SearchPhaseController.merge(SearchPhaseController.java:277) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
»       at org.elasticsearch.action.search.FetchSearchPhase.moveToNextPhase(FetchSearchPhase.java:276) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
»       at org.elasticsearch.action.search.FetchSearchPhase.lambda$innerRun$1(FetchSearchPhase.java:114) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
»       at org.elasticsearch.action.search.FetchSearchPhase.innerRun(FetchSearchPhase.java:124) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
»       at org.elasticsearch.action.search.FetchSearchPhase$1.doRun(FetchSearchPhase.java:98) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
»       at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
»       at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
»       at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:775) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
»       at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
»       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
»       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
»       at java.lang.Thread.run(Thread.java:833) [?:?]
```

This PR fixes this issue by simply adding `Map` as an acceptable instance

Relates to #74660

### CODE REVIEW

**Comment by nik9000** [comment]
It seems fine to me. Does this work with search_after? Maybe ping clients developers to see how if this is ok with them.

**Comment by csoulios** [comment]
A query like this:

```
GET /test/_search
{
  "sort" : [ "_tsid", "@timestamp" ]
}
```

Will produce results similar to the following example:

```
{
 "_index" : "test",
 "_id" : "9fLsn30BuA_D-fdpROsd",
 "_score" : null,
 "_source" : {
   "@timestamp" : "2021-04-28T18:51:03.142Z",
   "k8s" : {
     "pod" : {
       "uid" : "df3145b3-0563-4d3b-a0f7-897eb2876ea9",
       "ip" : "10.10.55.3",
       "name" : "dog",
       "network" : {
         "tx" : 1434595272,
         "rx" : 530605511
       }
     }
   },
   "metricset" : "pod"
 },
 "sort" : [
   {
     "k8s.pod.uid" : "df3145b3-0563-4d3b-a0f7-897eb2876ea9",
     "metricset" : "pod"
   },
   1619635863142
 ]
}
```

Can someone from @elastic/es-clients confirm that adding a map/object to the `sort` section will not break clients in calls such as `search_after`

**Comment by swallez** [comment]
Forbid my ignorance about TSDB inner workings, but why isn't `_tsid` a scalar value, or could it be represented as such? Is there any use case where we have to provide a time series id as part of a path element or query parameter?

Introducing a non-scalar value for `search_after` would indeed be a breaking change for clients in statically-typed languages. I see this is targetting 8.1, so we could introduce this breaking change in 8.0. But even better if we can avoid it altogether!

**Comment by nik9000** [comment]
> could it be represented as such?

by encoding the map into a string, sure. It feels a little silly if we have json here. Do clients expect a scalar here?

> Is there any use case where we have to provide a time series id as part of a path element or query parameter?

I don't believe so.

> Introducing a non-scalar value for `search_after` would indeed be a breaking change for clients in statically-typed languages. I see this is targetting 8.1, so we could introduce this breaking change in 8.0. But even better if we can avoid it altogether!

I'd have figured that widening the type would be ok on the request. I was more worried about the it in the response to be honest.

**Comment by swallez** [comment]
Thanks @nik9000. Thinking further I realize that the `sort` and `search_after` values are really opaque data  from a client application perspective, since all an application should do is hand over the value of `sort` from a search response to the next request's `search_after`.

Currently [this is defined as an array of scalar values](https://github.com/elastic/elasticsearch-specification/blob/8fd55aa23e1a6554262d01db92791004d2c0b40c/specification/_types/sort.ts#L99), hence my question.

We had a quick discussion in the client team and I opened https://github.com/elastic/elasticsearch-specification/issues/1109 to change that type's definition to arbitrary JSON.

So go ahead, this format will be fine once we've introduced this change in the API spec.

**Comment by csoulios** [comment]
@elasticmachine update branch

**Review by nik9000 — APPROVED** [review]

**Pull request merged**
