### PR TITLE
Invalidate Token API enhancements - HLRC

### PR DESCRIPTION
**Pull request by jkakavas**
Adds Invalidate Token API enhancements to HLRC

Depends on: #35388

### CODE REVIEW

**Comment by jkakavas** [comment]
This will keep on failing until https://github.com/elastic/elasticsearch/pull/35388 is merged but I think it can be reviewed nevertheless, I'll ensure CI deities are satisfied before merging.

**Comment by tvernum** [comment]
> Adds Invalidate Token API enhancements to HLRC

and rest tests & API docs

**Review by tvernum — APPROVED** [review]
:+1:

**Comment by jkakavas** [comment]
```
10:24:21  [6.5.4] * What went wrong:
10:24:21  [6.5.4] Could not resolve all files for configuration ':server:compileClasspath'.
10:24:21  [6.5.4] > Could not download t-digest.jar (com.tdunning:t-digest:3.2)
10:24:21  [6.5.4]    > Could not get resource 'https://jcenter.bintray.com/com/tdunning/t-digest/3.2/t-digest-3.2.jar'.
10:24:21  [6.5.4]       > Could not HEAD 'https://jcenter.bintray.com/com/tdunning/t-digest/3.2/t-digest-3.2.jar'. Received status code 504 from server: Gateway Time-out
```

**Comment by jkakavas** [comment]
@elasticmachine test this please

**Comment by jkakavas** [comment]
```

> Task :distribution:bwc:bugfix:buildBwcVersion
 [6.5.4] Found locally available resource with matching checksum: [https://jcenter.bintray.com/com/netflix/nebula/nebula-publishing-plugin/4.4.4/nebula-publishing-plugin-4.4.4.pom, /var/lib/jenkins/.gradle/caches/modules-2/files-2.1/com.netflix.nebula/nebula-publishing-plugin/4.4.4/5679184c34944ef53409e4a2f9e178446319b5f/nebula-publishing-plugin-4.4.4.pom]
 [6.5.4] Invalidating in-memory cache of /var/lib/jenkins/.gradle/caches/journal-1/file-access.bin
 [6.5.4] Failed to get resource: HEAD. [HTTP HTTP/1.1 504 Gateway Time-out: https://jcenter.bintray.com/com/github/jengelman/gradle/plugins/shadow/2.0.4/shadow-2.0.4.pom]
 [6.5.4] Failed to get resource: GET. [HTTP HTTP/1.1 504 Gateway Time-out: https://jcenter.bintray.com/com/carrotsearch/randomizedtesting/randomizedtesting-runner/2.7.0/randomizedtesting-runner-2.7.0.pom]
 [6.5.4] Failed to get resource: HEAD. [HTTP HTTP/1.1 504 Gateway Time-out: https://jcenter.bintray.com/de/thetaphi/forbiddenapis/2.6/forbiddenapis-2.6.pom]
 [6.5.4] 
 [6.5.4] FAILURE: Build failed with an exception.
```
:(

@elasticmachine run the gradle build tests 2

**Pull request merged**
