### PR TITLE
fix_typo_in_IndicesAdminClient

### PR DESCRIPTION
**Pull request by mushao999**
fix typo in IndicesAdminClient

### CODE REVIEW

**Comment by Navanit-git** [comment]
> docs

**Comment by mushao999** [comment]
Pinging @elasticmachine

**Review by nik9000 — APPROVED** [review]

**Comment by nik9000** [comment]
@elasticmachine, ok test test

**Comment by nik9000** [comment]
@elasticmachine, ok to test

**Comment by nik9000** [comment]
@elasticmachine update branch

**Pull request merged**
