### PR TITLE
Add tests around accessing field aliases in scripts.

### PR DESCRIPTION
**Pull request by jtibshirani**

### CODE REVIEW

**Comment by rjernst** [comment]
Can these be unit tests on LeafFieldLookup instead of integration tests?

**Comment by jtibshirani** [comment]
That makes sense -- I took a stab at converting them to unit tests. In addition to `LeafFieldLookup`, I needed to test `LeafDocLookup` (for accessing fields through `doc[...]` in painless scripts), and `ExpressionScriptEngine`, which seems to use its own loading pathway.

**Review by jpountz — CHANGES_REQUESTED** [review]
Do we need to test expressions explicitly? If everything goes through LeafDocLookup, it shouldn't buy more than LeafDocLookupTests?

Not to be done in that PR, but I wonder that we might want to remove `IndexFieldData.getName`, which is one way that the info that an alias is queried rather than a concrete field is leaked, yet it doesn't seem much used.

**Comment by jtibshirani** [comment]
I added the dedicated test for `ExpressionScriptEngine`, because it actually uses its own loading pathway outside of `LeafDocLookup`: https://github.com/elastic/elasticsearch/blob/master/modules/lang-expression/src/main/java/org/elasticsearch/script/expression/ExpressionScriptEngine.java#L194-L200. It would be better if they shared a common code path, but refactoring it to use `LeafDocLookup` looks fairly involved and probably shouldn't be tackled here.

And thanks for the pointer -- I'll take a closer look at `IndexFieldData`.

**Review by jpountz — APPROVED** [review]
Thanks for the explanation. LGTM

**Pull request merged**
