### PR TITLE
[ML] Fix deleting a trained model can emit deprecation warnings related to ingest pipeline configs

### LINKED ISSUE #105004: [ML] Deleting a trained model can emit deprecation warnings related to ingest pipeline configs
### Elasticsearch Version

8.12

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

any

### Problem Description

When a trained model is delete the ingest pipeline configurations are checked to ensure the model is not used in a pipeline. If used the deletion fails and the user is instructed to use the `force` option. 

That check on the pipeline configs causes any deprecation messages related to the pipeline config to be included in the response.
```
DELETE _ml/trained_models/my-model

#! The default [remove_binary] value of 'false' is deprecated and will be set to 'true' in a future release. Set [remove_binary] explicitly to 'true' or 'false' to ensure no behavior change.
{
  "acknowledged": true
}
``` 

Any pipeline processor that contains deprecated config will cause the warning, this is confusing and hard to track down the source of the problem.

### Steps to Reproduce

1. Install any trained model, downloading the builtin `.elser_model_2` is the easy option.
2. Create an ingest pipeline containing the `attachment` processor with deprecated config
```
PUT _ingest/pipeline/attachment
{
  "description" : "Extract attachment information",
  "processors" : [
    {
      "attachment" : {
        "field" : "data"
      }
    }
  ]
}
```
3. Delete `.elser_model_2`

```
DELETE _ml/trained_models/.elser_model_2
```

And observe the deprecation waring in the response
```
#! The default [remove_binary] value of 'false' is deprecated and will be set to 'true' in a future release. Set [remove_binary] explicitly to 'true' or 'false' to ensure no behavior change.
```

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by maxhniebergall**
Fixes https://github.com/elastic/elasticsearch/issues/105004

Manual testing showed that the deprecation warning still occurs on main, and no longer occurs after these changes.

### CODE REVIEW

**Review by jonathan-buttner — APPROVED** [review]

**Comment by maxhniebergall** [comment]
CI failed due to ESQL tests.

@elasticsearchmachine merge upstream

**Comment by maxhniebergall** [comment]
CI failures are from ESQL

**Comment by maxhniebergall** [comment]
@elasticmachine merge upstream

**Comment by maxhniebergall** [comment]
part-1 failure due to node disconnection. Seems unrelated.

**Comment by maxhniebergall** [comment]
@elasticmachine merge upstream

**Pull request merged**
