### PR TITLE
Include node name in EsRejectedExecutionException

### LINKED ISSUE #26007: Include node info in BulkItemResponse
For large deployments with a lot of nodes, sometimes it can be helpful to include node information (eg. node id) as part of the BulkItemResponse.  

```
  {
      "index": {
        "_index": "logstash-2017.08.01",
        "_type": "log",
        "_id": "a2",
        "status": 429,
        "error": {
         "type"=>"es_rejected_execution_exception", "reason"=>"rejected execution of org.elasticsearch.transport.TransportService$7@3f107726 on EsThreadPoolExecutor[bulk, queue capacity = 200, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@74a025a2[Running, pool size = 32, active threads = 32, queued tasks = 212, completed tasks = 7508184]]"
      }
  }
```

While thread pool information can be retrieved from node stats/cat_threadpool, this is filed from the point of view of a Logstash administrator so they can quickly tell if there is a problem ES node (based on historical bulkitemresponse errors that are logged in the LS log over time) vs. across the board.

```
[2017-07-27T00:17:53,108][INFO ][logstash.agent     ] Successfully started Logstash API endpoint {:port=>9600}
[2017-07-27T00:18:19,999][INFO ][logstash.outputs.elasticsearch] retrying failed action with response code: 429 ({"type"=>"es_rejected_execution_exception", "reason"=>"rejected execution of org.elasticsearch.transport.TransportService$7@2d02a4c2 on EsThreadPoolExecutor[bulk, queue capacity = 200, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@74a025a2[Running, pool size = 32, active threads = 32, queued tasks = 212, completed tasks = 7508184]]"})
[2017-07-27T00:18:20,000][INFO ][logstash.outputs.elasticsearch] retrying failed action with response code: 429 ({"type"=>"es_rejected_execution_exception", "reason"=>"rejected execution of org.elasticsearch.transport.TransportService$7@3f107726 on EsThreadPoolExecutor[bulk, queue capacity = 200, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@74a025a2[Running, pool size = 32, active threads = 32, queued tasks = 212, completed tasks = 7508184]]"})
[2017-07-27T00:18:20,000][INFO ][logstash.outputs.elasticsearch] retrying failed action with response code: 429 ({"type"=>"es_rejected_execution_exception", "reason"=>"rejected execution of org.elasticsearch.transport.TransportService$7@28a061bc on EsThreadPoolExecutor[bulk, queue capacity = 200, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@74a025a2[Running, pool size = 32, active threads = 32, queued tasks = 212, completed tasks = 7508184]]"})
[2017-07-27T00:18:20,000][INFO ][logstash.outputs.elasticsearch] retrying failed action with response code: 429 ({"type"=>"es_rejected_execution_exception", "reason"=>"rejected execution of org.elasticsearch.transport.TransportService$7@2d02a4c2 on EsThreadPoolExecutor[bulk, queue capacity = 200, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@74a025a2[Running, pool size = 32, active threads = 32, queued tasks = 212, completed tasks = 7508184]]"})
[2017-07-27T00:18:20,000][INFO ][logstash.outputs.elasticsearch] retrying failed action with response code: 429 ({"type"=>"es_rejected_execution_exception", "reason"=>"rejected execution of org.elasticsearch.transport.TransportService$7@2d02a4c2 on EsThreadPoolExecutor[bulk, queue capacity = 200, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@74a025a2[Running, pool size = 32, active threads = 32, queued tasks = 212, completed tasks = 7508184]]"})
[2017-07-27T00:18:20,001][INFO ][logstash.outputs.elasticsearch] retrying failed action with response code: 429 ({"type"=>"es_rejected_execution_exception", "reason"=>"rejected execution of org.elasticsearch.transport.TransportService$7@3f107726 on EsThreadPoolExecutor[bulk, queue capacity = 200, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@74a025a2[Running, pool size = 32, active threads = 32, queued tasks = 212, completed tasks = 7508184]]"})
```

### PR DESCRIPTION
**Pull request by liketic**
Closes #26007 

I'm not sure if it's possible to merge this because seems there are too many changes..

### CODE REVIEW

**Comment by jasontedor** [comment]
I understand this was the suggestion made in #26007 but I am not a fan of this change. It’s kind of hacky to push down this information that can and should already be being picked up by monitoring. Reading log messages from failed bulk requests does not feel like the right way to find out what node is sick. I am -1.

**Comment by jasontedor** [comment]
There's an alternative way that this can be done which is not so invasive. Instead of pushing this all the way down into the exception, I think we can get by putting this as part of the name in the thread pool executor and exposing it via the string representation of that. Would you be interested in taking this in that direction @liketic?

**Comment by liketic** [comment]
@jasontedor OK, I can take a try. Thanks!

**Comment by jasontedor** [comment]
@liketic Thanks, it's appreciated.

**Comment by liketic** [comment]
@jasontedor I updated the PR, please help to review to make sure it makes sense. Thanks!

**Comment by jasontedor** [comment]
Thanks for getting this started, and sorry for the slow review here. Unfortunately, this change has become more urgent as of late so I have opened #27663 to supersede this one.

**Pull request closed without merging**
