### PR TITLE
Fix verbose logging on plugin install and tidy up log message.

### PR DESCRIPTION
**Pull request by jimhooker2002**
Closes https://github.com/elastic/elasticsearch/issues/12907

### CODE REVIEW

**Comment by jimhooker2002** [comment]
Also added the fix for https://github.com/elastic/elasticsearch/issues/4665 to this pull request as well.

**Comment by dadoonet** [comment]
Why not 2 PR instead of one? I think they are not related, right?

**Comment by jimhooker2002** [comment]
Correct, not related. Happy to submit two separate if that's how it's done.  Sorry for the mess - new to Github and associated workflows.

**Comment by dadoonet** [comment]
:) No problem! 

Yes please remove the commit 66fe490 from this branch and force push it again.

Add the commit in another branch and send a new PR with it so we can review both.

**Comment by jimhooker2002** [comment]
https://github.com/elastic/elasticsearch/commit/66fe490d98a8bb5f15ba595b692100df674d4cae now removed from this pull request - will submit separately.  This pull request should now be clean and ready.

**Comment by dadoonet** [comment]
Was actually already fixed in 2.x (59571749a7e1a544a12a86d919c122285eea76b1) and master (7d6acde) branches with another commit. I just cherry picked for 2.0: 4f7c6a9

**Pull request closed without merging**
