### PR TITLE
optimize duplicated code block in MetadataUpdateSettingsService

### PR DESCRIPTION
**Pull request by mushao999**
We found that almost same update settings logic was used for `openIndices` and `closeIndcies` in `MetadataUpdateSettingService` . So we create a new method executing this logic to avoid duplicated code blocks.

### CODE REVIEW

**Review by grcevski — CHANGES_REQUESTED** [review]
Thank you for the contribution!

I really like the code duplication removal, the only thing I'd request to be changed is the use of the boolean parameter to control the function logic inside `updateIndexSettings`.

The use of a boolean parameter reduces the code readability and it makes things harder to test. I have few ideas how we can make this a bit better, it would be great if you'd consider it:

1. We could reuse only the logic inside the inner most if. This would be less reuse, but it's also reusing the parts where code logic is truly duplicated and where it would be the most of the maintenance burden in the future.

2. We could use a function as an argument to updateIndexSettings and pass updateDynamicSettings or updateSettings. Since it's a multi argument function we'd probably have to declare a functional interface and it might be a bit heavy handed.

Thanks!

**Comment by mushao999** [comment]
> Thank you for the contribution!
> 
> I really like the code duplication removal, the only thing I'd request to be changed is the use of the boolean parameter to control the function logic inside `updateIndexSettings`.
> 
> The use of a boolean parameter reduces the code readability and it makes things harder to test. I have few ideas how we can make this a bit better, it would be great if you'd consider it:
> 
> 1. We could reuse only the logic inside the inner most if. This would be less reuse, but it's also reusing the parts where code logic is truly duplicated and where it would be the most of the maintenance burden in the future.
> 2. We could use a function as an argument to updateIndexSettings and pass updateDynamicSettings or updateSettings. Since it's a multi argument function we'd probably have to declare a functional interface and it might be a bit heavy handed.
> 
> Thanks!

Thank you for your suggestion. I think the second option is better, `indexScopedSettings.updateDynamicSettings` and `indexScopedSettings.updateSettings` have four parameters, but two of them can be set outside the `updateIndexSettings` method. So, we can use BiFunction as parameter to pass those methods. 
I've updated the code by this way. Code formating and master merging are also done in the new commit.

**Comment by mushao999** [comment]
I also removed the empty check, because the `for loop` will still work correctly in this situation.

**Review by grcevski — COMMENTED** [review]
This looks awesome! Thank you.

I know this is very much a refactoring of existing code we have, but since the updating of settings is now nicely extracted into a standalone method, would you please consider adding some unit tests for the new method?

We can remove the `private` modifier from the new method and it will be exposed for testing. We don't have any unit tests for this class, so you'll need to make a new file called MetadataUpdateSettingsServiceTests.java in the test folder.

The unit test needs to confirm that we have indeed added the right settings into the builder. Also, perhaps ensuring the INDEX_NUMBER_OF_REPLICAS_SETTING logic really runs properly.

There are examples of tests similar to what this could look like in IndexSettingsTests.

Thanks again!

**Comment by grcevski** [comment]
@elasticmachine test this please

**Comment by grcevski** [comment]
I kicked off the existing tests to make sure it's all good, but by looking at the test code we have I'm not sure how well tested are all these paths. Unit tests would help a lot.

**Comment by mushao999** [comment]
> This looks awesome! Thank you.
> 
> I know this is very much a refactoring of existing code we have, but since the updating of settings is now nicely extracted into a standalone method, would you please consider adding some unit tests for the new method?
> 
> We can remove the `private` modifier from the new method and it will be exposed for testing. We don't have any unit tests for this class, so you'll need to make a new file called MetadataUpdateSettingsServiceTests.java in the test folder.
> 
> The unit test needs to confirm that we have indeed added the right settings into the builder. Also, perhaps ensuring the INDEX_NUMBER_OF_REPLICAS_SETTING logic really runs properly.
> 
> There are examples of tests similar to what this could look like in IndexSettingsTests.
> 
> Thanks again!

I've added the `MetadataUpdateSettingsServiceTests`. 
- The first test method tests update dynamic settings for open index and override existing settings.
- The second test method tests update dynamic and static settings for closed index and do not override existing settings.
But I can construct an `IndexMetadata` without `INDEX_NUMBER_OF_REPLICAS_SETTING`, because `IndexMetadata.Builder#build()` will check `INDEX_NUMBER_OF_REPLICAS_SETTING`. Is there any way to construct an `IndexMetadata` without `INDEX_NUMBER_OF_REPLICAS_SETTING `  or should we just remove the creatation of `INDEX_NUMBER_OF_REPLICAS_SETTING` in `updateIndexSettings`?

**Review by grcevski — APPROVED** [review]
This looks great! Thanks again for your contribution.

**Comment by grcevski** [comment]
@elasticmachine test this please

**Comment by mushao999** [comment]
@grcevski  I'm sorry for leaving a `sout` in the test code , please invoke test again. And what about the `INDEX_NUMBER_OF_REPLICAS_SETTING` thing ? thanks

**Comment by mushao999** [comment]
@elasticmachine test this please

**Comment by grcevski** [comment]
No problem, I think it's fine for `INDEX_NUMBER_OF_REPLICAS_SETTING`, I think the code is there for upgrading from previous versions, we can't force it now.

**Comment by grcevski** [comment]
@elasticmachine test this please

**Pull request merged**
