### PR TITLE
HLRC: ML %s/Boolean is/Boolean get/g

### PR DESCRIPTION
**Pull request by benwtrent**
Replaces `Boolean is` with `Boolean get` for requests. 

Also changes `DeleteDatafeedRequest#force` to be `Boolean` and updates `DeleteDatafeedRequest#(get|set)Force` accordingly 

closes #33374

### CODE REVIEW

**Review by dimitris-athanasiou — APPROVED** [review]
LGTM

**Comment by dimitris-athanasiou** [comment]
Oh, @benwtrent, it just occurred to me we also need to update the docs.

**Comment by benwtrent** [comment]
@dimitris-athanasiou update the docs where? The HLRC docs get populated with code inserts automatically. Also, from what I can tell, any "getter" that returns a boolean and is in the docs is in reference to a response class. 

Is there something I missed?

**Comment by dimitris-athanasiou** [comment]
No, you're right. We don't use the request getters in the docs. Good to go then!

**Pull request merged**
