### PR TITLE
[SQL] Clean up LogicalPlanBuilder#doJoin

### PR DESCRIPTION
**Pull request by cbuescher**
Currently the local `type` and `condition` variables are unused. After removing
them and connected code inside the method, this method seems always to return an
exception, so I wonder if it can be removed altogether.

### CODE REVIEW

**Comment by costin** [comment]
The parsing is in place in order to tell users using join that it is not supported - without it the grammar would be marked as incorrect which is confusing (since it's not; it's rather that ES SQL doesn't expect JOIN to appear). The type and condition should appear in the error message and it looks like they aren't.

The JOIN without USING is parsed since it's an equi-join which, if applied on the same index, is something we aim to support.
It also provides further validation of the query.

**Comment by costin** [comment]
I think for the moment it's fine to push this PR as is. Thanks for looking into this.

**Review by costin — APPROVED** [review]
LGTM

**Comment by cbuescher** [comment]
@costin thanks for the review

**Pull request merged**
