### PR TITLE
Allow gradle to run the other client's tests

### PR DESCRIPTION
**Pull request by nik9000**
This adds a hack to the `integTest` task to support running external processes. It looks like:

```
mkdir tmp
cd tmp
git clone https://github.com/nik9000/elasticsearch.git
cd elasticsearch
git checkout gradle_runs_clients
cd ..
git clone https://github.com/elastic/elasticsearch-py.git
cd elasticsearch-py
gradle -p ../elasticsearch distribution:integ-test-zip:integTest -Drest.test.executable=python3 -Drest.test.executable.args='setup.py test'
```

That results in a few failures but that is fine because at least it runs. And most things pass which is cool. Now you can run other plugins yaml tests:

```
gradle -p ../elasticsearch modules:reindex:integTest -Drest.test.executable=python3 -Drest.test.executable.args='setup.py test'
gradle -p ../elasticsearch modules:lang-painless:integTest -Drest.test.executable=python3 -Drest.test.executable.args='setup.py test'
gradle -p ../elasticsearch plugins:ingest-user-agent:integTest -Drest.test.executable=python3 -Drest.test.executable.args='setup.py test'
```

The `python3 setup.py test` part isn't quite right because it runs _all_ the tests, not just the REST ones. But I think that is a thing we can address in the clients at some point.

The neat thing about this is that the clients that we run don't have to know about the fixtures required to run the various rest tests.

### CODE REVIEW

**Comment by nik9000** [comment]
I had a look and the php client doesn't seem to support running the yaml from another directory so I can't test it with this. The ruby client doesn't seem to do so either.

**Comment by karmi** [comment]
@nik9000, the Ruby runner supports the `TEST_REST_API_SPEC` environment variable to point it to a specific folder with tests. I haven't had much time to think about it, but I'm quite undecided about the approach though, I think this approaches the problem from a reversed angle.

I would much rather have support for something like `execute` expression in th YAML tests, or in the runners, which would run a command like `gradle test setup whatever`. But again, I haven't had much time to think about it, this is more about describing a "hunch" I have.

**Comment by nik9000** [comment]
Yeah, what I've proposed is very much the path of least resistance. It assumes the clients can adapt to Elasticsearch's build mechanisms.

**Comment by nik9000** [comment]
This came from trouble around #19310. I want to test reindex-from-remote with authentication. But it needs some kind of proxy or a special testing elasticsearch plugin or both. I get bogged down in "how will the clients run these tests?" Something like this will make whatever we do for Elasticsearch just work for the clients too. If we don't do something like this I'm fairly sure the clients just won't be able to run those tests. I don't know if that is ok or not.

**Comment by javanna** [comment]
Can you describe what problem this PR is addressing?  Maybe also what the gradle command that you posted does (runs the rest tests via python, but does some gradle setup beforehand I guess?) and an example of how this feature would be used in practice?

**Comment by javanna** [comment]
Turns out hitting refresh before posting would have made my previous comment almost not needed :)

**Comment by nik9000** [comment]
> Turns out hitting refresh before posting would have made my previous comment almost not needed :)

Sorry! Yeah, it'll setup all the things Elasticsearch's build thinks it needs to run the rest tests for some step and then run *all* of the python client's tests. The idea is that the client could, in future, change its build to run all of its normal tests and then run something like:
```
gradle -p ../elasticsearch integTest -Drest.test.executable=python3 -Drest.test.executable.args='setup.py test'
```
to run all of the rest tests for all of the modules, plugins, core, qa projects, whatever. And gradle would stand up all the dependencies for it. The client would have to adapt to that sort of two phase testing, but the advantage is you get all the dependencies handled in one spot.

**Comment by rjernst** [comment]
Instead of hacking integTest, can we do this with a new gradle task? It can be setup the same way the rest test task is, but call it `externalTest` or something and make the sysprop required?

**Comment by nik9000** [comment]
> Instead of hacking integTest, can we do this with a new gradle task?

Yes, but I wanted to see if this was a thing we actually wanted to do before I spent the time doing that. Extracting the setup from integTest sounds like it'll be a bit fiddly.

> make the sysprop required?

So, like, declare this new task all the time but don't make `check` depend on it?

**Comment by rjernst** [comment]
> So, like, declare this new task all the time but don't make check depend on it?

Yes, same as we do for packagingTest

**Comment by karmi** [comment]
I've been thinking about it and still think that the solution is approaching the problem from the wrong side. I'd like to use this issue as an opportunity to explain the larger topic of how I view the REST (YAML) test suite in the context of Elasticsearch core and language clients.

## The problem

First, let's describe the problem itself we do indeed need to solve: for some tests, we need to execute additional actions, not currently supported by the YAML test suite. This might be, for example, launching another Elasticsearch node, to be able to test reindexing from a remote cluster. But it also might be launching the node with a specific configuration, or installing a specific plugin into Elasticsearch. All in all, actions which cannot be done by calling an Elasticsearch API (which _is_ supported by the YAML nomenclature), but can be done only by running a command (bash, gradle, ...).

## The solutions

The outlined solution views running the tests as something which can be de facto "embedded" into the Gradle infrastructure of Elasticserch core. It is certainly one of valid technical approaches, but I see it as deficient when compared to other potential solutions.

A different approach would "invert" this view, and see running the tests on another platform (Python, Ruby, ...) still as a standalone thing, but add an ability to _call external action_, which quite well might be implemented as a specific Gradle task.

I see couple of benefits of this "inverted" approach. First, running the tests is being left in the discretion of respective developers, letting them do whatever they like and whatever is appropriate on their platform. This is not a small thing, in my opinion, because it gives language developers more freedom to work with the test suite on _their_ platform.

Second, this opens up interesting posibilities, such as adding an `execute` expression to the YAML nomenclature, which would allow the test runner to call some external command. (Question such as "do we really want to run arbitrary bash scripts or just Gradle tasks" are of course further debatable, having significant security implications.)

But the immediate solution for the problem we're trying to solve here, namely launching another Elasticsearch node with a specific configuration, would be trivial to solve in this way: the runners for different languages would have to call something like `gradle test launch_node_for_reindex`, or a wrapper task like `gradle test setup`, before they run the tests, and `gradle test teardown` after they're done.

Explaining the benefit of this "inverted dependency" (_“Don't call us, we'll call you”_) further, this would allow language developers to run that `gradle test setup` task manually, in case they suspect there are problems, inspect the code of that task, and so on and on. In this way, in other words, all the different parts of the whole integration test platform (YAML tests, language runners, bootstrapping tasks) are nicely separated, yet still integrated.

**Comment by karmi** [comment]
CC: @elastic/es-clients

**Comment by nik9000** [comment]
I talked to @clintongormley about this yesterday. Whatever we do, it won't be what I've proposed in this PR.

For now we're reasonably comfortable making the assertion that "there is on command you can use to start Elasticsearch and the yaml tests will only need that as a dependency". That means that some of Elasticsearch's REST testing can't be done with the YAML tests because it'll need dependencies. For example, say discovery-ec2 needs a mock ec2 endpoint to test discovery. Those tests won't be run by the clients. They aren't run now and won't be run in the future.

In addition, I've started adding REST level testing that isn't shared yaml tests to Elasticsearch's test suite in https://github.com/elastic/elasticsearch/pull/19509. That gives us another out for REST based testing - we don't have to involve the clients at all.

Given all that I'm going to close this.

**Pull request closed without merging**
