### PR TITLE
Modernize release tooling

### LINKED ISSUE #56788: Modernise release tooling
We currently rely on some Perl scripts in the `dev-tools` directory to perform a couple of release-related activities:

   1. Relabelling PRs at feature-freeze
   2. Generating release notes from PRs

These scripts are barely maintained, and out-of-step with most of the tooling in the repository. We need to rewrite these scripts to make them easier to maintain.

We could, for example, rewrite them as Gradle tasks, given that most other activities are performed through Gradle.

(Note that there's also the `atomic_push.sh` script, but I don't know if we want to do anything about that right now.)

### PR DESCRIPTION
**Pull request by pugnascotia**
Closes #56788.

This PR implements two new Gradle tasks at the root of the project. These tasks are essentially ports of the scripts in the `dev-tools` directory. I would particularly appreciate feedback on how the Gradle tasks are defined, since I haven't written custom tasks before. Note that some of the custom command line switches are more verbose that I would have chosen, because e.g. `--version` is claimed and processed by Gradle irrespective of where it appears on the command line.

Both tasks require that a GitHub token is available at `~/.elastic/github_auth`, although you can override this with the `github.key_path` system property.

I haven't yet removed the old scripts, so that they are easily available for comparison.

Finally, I am aware that GitHub have v4 API, but I didn't want to confuse matters further by moving to it.

### `:buildReleaseNotes`

This task replaces `dev-tools/es_release_notes.pl`, and can be run as follows:

    ./gradlew :buildReleaseNotes  --release-version 7.8.0 --release-output path/to/notes.asciidoc

Both switches have sensible defaults.

Note that the old script has also been modified in this PR, as follows. These changes were originally made during release preparation for the 7.8 release.

   * Omit `WIP`-labelled PRs
   * Trim area prefixes from PR titles
   * Omit PRs where they are released in an earlier version.

### `:relabelGithubIssues`

This tasks replaces `dev-tools/github_relabel.pl`, and can be run as follows:

    ./gradlew relabelGithubIssues --labels v7.8.0 --remove v7.8.0  --add v7.8.1

While the default repository is `elastic/elasticsearch`, you can override this using the `relabel.repository` system property:

    ./gradlew -Drelabel.repository="foo/bar" relabelGithubIssues # etc

You can also pass `--simulate` to avoid changing anything.

### CODE REVIEW

**Comment by rjernst** [comment]
Thanks for picking this up @pugnascotia. I have a couple general comments/questions:

- Why are there additions to the original perl scripts?
- For relabeling, instead of supporting general add/remove, can we narrow the focus to our releases? ie we know about our version numbers, we could have a single version argument, and verify that is a released version in our Gradle bwcVersions, and that increment that, which should be an unreleased version.
- For release notes, why do we need to have a path given? It should always be the same pattern, based on the version.
- Why do we need the ability to run this on different repositories?

In general, I think we should make this narrowly focused on what we need out of the tooling, not try to have parity with the old tools.

**Comment by pugnascotia** [comment]
@rjernst:

   * I covered the Perl changes in the PR description. The final iteration of this PR should remove those scripts entirely.
   * We certainly can narrow the focus here to releases, that seems appropriate.
   * The path argument is optional for release notes. By default, it writes a file to the usual place under `docs`, though that file will then likely need some manual merging alterations etc as usual.
   * The repository override is there for testing. I didn't want to test these tasks on the real repo!

**Comment by mark-vieira** [comment]
FYI, I have no dug into the detail yet, but what do we think about putting stuff like this in https://github.com/elastic/elasticsearch-infra. I say that because this is internal-release specific logic, and while not necessarily sensitive by nature, it's really not applicable to external contributors unless they needed to perform a release, which I don't think will ever be the case.

The ES build is kind of a hulking beast. It needs a particular JDK, checking out the repo is time consuming, and even just running simple task involved building all of `buildSrc` configuring 100s of projects, etc. In terms of responsiveness, this migration could certainly be considered a regression. We could mitigate this by moving release automation tasks into their own separate build, that need not check out all of Elasticsearch. I also anticipate that would be a good place to put other automation logic as well, as we move forward in automation more and more release steps.

Do we have compelling reasons for keeping this part of the ES build?

**Comment by jasontedor** [comment]
I agree that this should be part of our internal elasticsearch-infra repository.

**Comment by rjernst** [comment]
The one reason I could see is what I already mentioned: we know version info here. However, we could extract it ourself from the scripts as necessary. +1 to move it.

**Comment by mark-vieira** [comment]
That's enough of a quorum for me. @pugnascotia, sorry for the additional work, but do you mind opening a separate PR to create a new 'release-tools' or some such appropriately named project under the elasticsearch-infra repo for this? 

Since this will be a greenfield Gradle build, it might be a good opportunity to experiment more with [Kotlin build scripts](https://docs.gradle.org/current/userguide/kotlin_dsl.html). I'll defer that decision to @pugnascotia for you to decide if you're up to it 😉.

**Comment by pugnascotia** [comment]
OK, I took a stab in the dark with migrating this to a standalone project, but came unstuck. I'll need to sync with someone who actually knows what they're doing 😅

**Comment by mark-vieira** [comment]
@pugnascotia @breskeby will be around in your timezone, otherwise, I can sync up with you first thing my morning tomorrow.

**Comment by pugnascotia** [comment]
I've now migrated this work.

**Pull request closed without merging**
