### PR TITLE
Contradictory type checks (in Debug)

### PR DESCRIPTION
**Pull request by krisds**
As requested, I will split #38033 into separate PRs. Here is the final part.

This one resolves:
* [Contradictory type checks](https://lgtm.com/projects/g/elastic/elasticsearch/snapshot/dist-1916470085-1548143539391/files/x-pack/plugin/sql/jdbc/src/main/java/org/elasticsearch/xpack/sql/jdbc/debug/Debug.java#xe223478b74721d35:1)

### CODE REVIEW

**Comment by jimczi** [comment]
@costin can you take a look ?

**Comment by costin** [comment]
Good catch - the interface type check should be reversed.
Fwiw, the check itself won't ever match since the driver doesn't support `CallableStatement` and thus never returns such an instance of.

**Comment by javanna** [comment]
test this please

**Comment by javanna** [comment]
hi @krisds would you mind merging master in please? We have fixed a number of test failures so that should help getting tests green here.

**Comment by javanna** [comment]
retest this please

**Comment by javanna** [comment]
retest this please

**Review by javanna — APPROVED** [review]

**Comment by javanna** [comment]
thanks @krisds !

**Pull request merged**
