### PR TITLE
Make ILM Steps use Infinite Master Timeout

### PR DESCRIPTION
**Pull request by original-brownbear**
Same as #72085 but for ILM. Having a timeout on these internal "requests"
only adds more noise if master is slow already when timed out steps trigger
moves to the error step.
It seems like it is safe to remove the setting for the timeout outright as well
as it was not used anywhere and never documented as far as I can tell.

### CODE REVIEW

**Review by dakrone — CHANGES_REQUESTED** [review]
Thanks for fixing this Armin, I'm in general agreement and the code looks good for changing the timeout. However, I'm definitely -1 for removing the setting in 7.x. It's a breaking change and I know that we have recommended the setting to some users in the past (it was actually added at the behest of a user's situation), we shouldn't remove it in 7.x even though it isn't documented.

**Review by DaveCTurner — APPROVED** [review]
Code changes LGTM and I think it's ok to backport to 7.x but I think to be on the safe side we should mark this as an enhancement rather than a non-issue. Not really a breaking change but at least in the backport it'll need to be mentioned as a deprecation in the migration docs and also in the deprecation info API.

**Comment by original-brownbear** [comment]
Jenkins run  elasticsearch-ci/packaging-tests-unix-sample  (Jenkins issue)

**Comment by original-brownbear** [comment]
Makes sense brought back the setting now and will document the change in the backport :)

**Review by dakrone — APPROVED** [review]
LGTM, thanks Armin

**Comment by original-brownbear** [comment]
Thanks Lee + David!

**Pull request merged**
