### PR TITLE
Use System.nanoTime() instead of System.currentTimeMillis() for took time

### PR DESCRIPTION
**Pull request by martijnvg**

### CODE REVIEW

**Comment by nik9000** [comment]
LGTM. You may want to mention in the second line of the commit/pr description the whole relative time thing.

**Comment by martijnvg** [comment]
Thanks @nik9000 I've updated the commit description.

**Comment by martijnvg** [comment]
I reverted this PR. `System.nanoTime()` was being called from multiple threads, causing the elapsed time to be incorrect. Fixing this requires a different change, so for now I reverted this PR.

**Comment by nik9000** [comment]
I _think_ we use nanoTime for this kind of thing elsewhere. Are we always on one thread there? @jasontedor would probably know. I use exactly the same pattern in reindex for it's took and I suspect its broken if this is.

**Comment by danielmitterdorfer** [comment]
@martijnvg: Can you elaborate? `System.nanoTime()` uses a monotonic clock under the hood so it should always be safe and more robust than `System.currentTimeMillis()`, even when used from multiple threads. However, `System.nanoTime()` will only work on a single machine, i.e. it reports (totally) different values on different machines.

**Comment by jasontedor** [comment]
> System.nanoTime() was being called from multiple threads, causing the elapsed time to be incorrect. 

Can you elaborate?

**Comment by martijnvg** [comment]
> Are we always on one thread there?

We take the start nanotime snapshot on a netty thread and the elapsed time was computed on a different thread.

@danielmitterdorfer This was assumption after checking online (varies per jvm impl?). The took time in bulk response was locally completely off (100000+ ms for indexing a single doc) and this was the only explanation that made sense to me, so I reverted. But maybe I reacted too quickly...

**Comment by jasontedor** [comment]
> We take the start nanotime snapshot on a netty thread and the elapsed time was computed on a different thread.

That should not matter.

> 100000+ ms for indexing a single doc

Sounds like a unit conversion problem?

> But maybe I reacted too quickly...

Do you have a failed build that we can look at? Do you mind if I take a look?

**Comment by martijnvg** [comment]
> Do you have a failed build that we can look at? Do you mind if I take a look?

We don't have tests for `took` in bulk response, but I noticed this locally when testing something else. Let me dig this up again. I think I may have overreacted.

**Comment by jasontedor** [comment]
@martijnvg There was a missed called to System#currentTimeMillis on line 94, that's the source of the problem.

**Comment by martijnvg** [comment]
@jasontedor oops... thanks for checking! I clearly overreacted.

**Comment by martijnvg** [comment]
I'll revert the revert commit and change line 94.

**Comment by clintongormley** [comment]
@martijnvg please add the version label back when you re-revert

**Comment by martijnvg** [comment]
This change will not re-reverted. #16916 will supersede this change.

**Pull request merged**
