### PR TITLE
SQL: fix use of requestTimeout and pageTimeout query parameters

### LINKED ISSUE #72151: SQL: request timeout is not honoured
All requests, [initial](https://github.com/elastic/elasticsearch/blob/4dc978e840dc89df0569468958ae455de7f32557/x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/execution/search/Querier.java#L115) or subsequent paginations, use the `page_timeout`, whose value's either taken from the config/request or default. 
Expected is to have the `request_timeout` config's value used for the initial request timeout.

### PR DESCRIPTION
**Pull request by Luegg**
Resolves #72151

The _sql endpoint offers a `page_timeout` parameter for customizing how long scroll contexts should be kept open (if needed) and a `request_timeout` parameter which the docs describe as "Timeout before the request fails.".

Currently, the value of the `page_timeout` parameter is used as the `timeout` in subsequent _search requests and not as the timeout in the `scroll` configuration. For the `scroll` configuration, SQL uses the `request_timeout` parameter.

This PR addresses the issue by swapping the uses of `page_timeout` and `request_timeout` in querier.

Additionally, the PR removes some unused artifacts that might have caused some confusion:
- The `timeout` and `keepAlive` fields in `Querier`. Instead, `Querier` directly uses the according fields in `SqlConfiguration`.
- The `SqlConfiguration` parameter from `ScrollCursor.clear`, it's not used but required an instance of `SqlConfiguration` with all default values.
- One overloaded constructor of `SqlConfiguration` that was only used for calling `ScrollCursor.clear` (and some tests) and used default values for an (arbitrary?) subset of the fields.
- The fields related to async requests in `SqlConfiguration`. I'm a bit unsure about this one but the fields are never read and it does not seem like an SQL specific concern. The whole creation of the async tasks is handled in `TransportSqlQueryAction` and the downstream components do not require the information.

### CODE REVIEW

**Review by hgmauri — APPROVED** [review]

**Review by costin — APPROVED** [review]
LGTM.
@bpintea can you please double check the async part and where the properties removed are actually used.

**Review by astefan — APPROVED** [review]
LGTM

**Review by bpintea — COMMENTED** [review]
Besides the general comments left: I'm aware that testing wouldn't be straightforward, but I'm wondering if there's something we could do about it, since I guess lack of them lead here.

**Review by bpintea — APPROVED** [review]
LGTM, thanks @Luegg.

**Pull request merged**
