### PR TITLE
Remove TransformClient from HLRC 

### LINKED ISSUE #83921: [Transform] Remove HLRC Transform client
### Description

Remove HLRC Transform client in 8.x series.

### PR DESCRIPTION
**Pull request by joegallo**
Related to https://github.com/elastic/elasticsearch/issues/83423
Closes #83921

I *think* this one is actually already unused, so it's just a matter of deleting it. If my `grep`ing was not correct, then I suppose Jenkins will tell us that.

### CODE REVIEW

**Review by dakrone — APPROVED** [review]
LGTM

**Review by davidkyle — APPROVED** [review]
LGTM

All usages of the client were removed in #84220, #84347 and #84430.

Actually deleting the code we supposed to be the champagne moment we somehow forgot about. Thanks for picking this up @joegallo

**Review by przemekwitek — APPROVED** [review]
LGTM

**Comment by joegallo** [comment]
> Actually deleting the code we supposed to be the champagne moment we somehow forgot about. 

Ah, nuts, I'm stealing your champagne moment!? Yikes!

**Pull request merged**
