### PR TITLE
[ML] Remove threading from tests

### LINKED ISSUE #112471: [CI] RequestBasedTaskRunnerTests testLoopOneAtATime failing
**Build Scans:**
- [elasticsearch-intake #9326 / part2](https://gradle-enterprise.elastic.co/s/n2kb6zjgzoflq)
- [elasticsearch-intake #9325 / part2](https://gradle-enterprise.elastic.co/s/zpzszvjnmi5yg)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:inference:test" --tests "org.elasticsearch.xpack.inference.external.http.RequestBasedTaskRunnerTests.testLoopOneAtATime" -Dtests.seed=3062999828F1030C -Dtests.locale=nb-NO -Dtests.timezone=Africa/Ndjamena -Druntime.java=22
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testLoopOneAtATime'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.inference.external.http.RequestBasedTaskRunnerTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure Message:**
```
org.mockito.exceptions.verification.TooFewActualInvocations: 
testThreadPool.executor("inference_utility");
Wanted 2 times:
-> at org.elasticsearch.xpack.inference.external.http.RequestBasedTaskRunnerTests.lambda$testLoopOneAtATime$6(RequestBasedTaskRunnerTests.java:108)
But was 1 time:
-> at org.elasticsearch.xpack.inference.external.http.RequestBasedTaskRunner.requestNextRun(RequestBasedTaskRunner.java:48)

```

**Issue Reasons:**
- [main] 2 consecutive failures in test testLoopOneAtATime
- [main] 2 consecutive failures in step part2
- [main] 2 consecutive failures in pipeline elasticsearch-intake
- [main] 2 failures in test testLoopOneAtATime (100.0% fail rate in 2 executions)
- [main] 2 failures in step part2 (100.0% fail rate in 2 executions)
- [main] 2 failures in pipeline elasticsearch-intake (100.0% fail rate in 2 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by prwhelan**
We are getting InterruptedExceptions ~1% of the time when running these tests, but we can remove the threading from this test and still verify the one-by-one behavior.

Fix #112471

### CODE REVIEW

**Comment by prwhelan** [comment]
@elasticmachine update branch

**Comment by prwhelan** [comment]
@elasticmachine update branch

**Review by davidkyle — APPROVED** [review]
LGTM

**Comment by prwhelan** [comment]
@elasticmachine update branch

**Pull request merged**
