### PR TITLE
Fix for mappings->_source example in docs

### LINKED ISSUE #13417: _source false ignored
Hi.
elasticsearch 1.7.1
According to documentation https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-source-field.html
**ES config**
node.name: "m1"
node.local: false
script.inline: off
script.indexed: off
node.master: true
node.data: true
node.max_local_storage_nodes: 1
index.number_of_shards: 3
index.number_of_replicas: 1
bootstrap.mlockall: true
network.host: 0.0.0.0
transport.tcp.port: 9300
http.port: 9200
http.enabled: true
http.cors.enabled: true
gateway.type: local
gateway.recover_after_nodes: 1
gateway.recover_after_time: 5m
gateway.expected_nodes: 2
discovery.zen.minimum_master_nodes: 1
discovery.zen.ping.timeout: 3s
discovery.zen.ping.multicast.enabled: false
index.search.slowlog.threshold.query.warn: 10s
index.search.slowlog.threshold.query.info: 5s
index.search.slowlog.threshold.fetch.warn: 1s
index.indexing.slowlog.threshold.index.warn: 10s
index.indexing.slowlog.threshold.index.info: 5s

**I tried simple test:**

    PUT /tweets
    {
      "mappings": {},
      "employee": {
        "_source": {
          "enabled": false
        }
      }
    }

**Success:**

    {
      "acknowledged": true
    }

**Then add document**

    PUT /tweets/employee/1
    {
      "first_name" :  "Douglas",
      "last_name" :   "Fir",
      "age" :         35,
      "about":        "I like to build cabinets",
      "interests":  [ "forestry" ]
    }

**As it's specified in docs, disabling _source will disable UPDATE API**

Ok, I ran:

    POST /tweets/employee/1/_update
    {
      "doc" : {
        "age": 58
      }
    }

and this query was successfull
Checking:

    GET /tweets/employee/1

**Result**

    {
      "_index": "tweets",
      "_type": "employee",
      "_id": "1",
      "_version": 3,
      "found": true,
      "_source": {
        "first_name": "Douglas",
        "last_name": "Fir",
        "age": 58,
        "about": "I like to build cabinets",
        "interests": [
          "forestry"
        ]
      }
    }

**"age": 58** - it was changed.

Also, when I do simple GET of this doc, I see _source field:

    {
      "_index": "tweets",
      "_type": "employee",
      "_id": "1",
      "_version": 2,
      "found": true,
      "_source": {
        "first_name": "Douglas",
        "last_name": "Fir",
        "age": 58,
        "about": "I like to build cabinets",
        "interests": [
          "forestry"
        ]
      }
    }

It seems disabling of _source field now working

### PR DESCRIPTION
**Pull request by eskibars**
Closes #13417

### CODE REVIEW

**Comment by nik9000** [comment]
Would you mind editing the title so its more descriptive and including Closes #13417 in the description? The title is what I use to scan if I need to review the commit or not.

**Comment by nik9000** [comment]
LGTM otherwise.

**Comment by eskibars** [comment]
Done.  Thanks @nik9000

**Comment by nik9000** [comment]
Cool. I'll merge and backport for you.

**Comment by nik9000** [comment]
Merged to master and cherry-picked into 2.x, 2.0, and 1.7.

**Pull request merged**
