### PR TITLE
Bug fixes for toReleaseVersion implementation

### PR DESCRIPTION
**Pull request by thecoop**
Some bug fixes for #112242 that were only found by the backport #112280

### CODE REVIEW

**Comment by thecoop** [comment]
@elasticmachine rerun elasticsearch-ci/part-1

**Review by prdoyle — APPROVED** [review]
Makes sense.

**Comment by rjernst** [comment]
@thecoop Can you please explain the reasoning behind this tweak? I would expect (though clearly I'm wrong) that current always maps exactly to the latest transport version, but this change seems to imply that's not the case, that the csv might _also_ contain current.

**Comment by thecoop** [comment]
It can be the case that the current transport version id is associated with several release versions - for example when there have been no changes to transport between patch releases. Which means the list needs to be updateable.

**Comment by thecoop** [comment]
@elasticmachine update branch

**Review by rjernst — APPROVED** [review]
LGTM

**Pull request merged**
