### PR TITLE
[Watcher]: Adding Description field to watchers

### LINKED ISSUE #35595: Watcher: Description field added potentially searchable
**Describe the feature**:  I think it would be handy to have a called out description field in the watcher.  I know that it can currently be done somewhat in the metadata field.  But I think it would be handy to have a description field that is searchable in case of a lot of watchers.

### PR DESCRIPTION
**Pull request by abprash**
Closes https://github.com/elastic/elasticsearch/issues/35595
- [x] No existing test fails.
- [ ] Need to confirm if unit test addition or documentation changes are necessary.

### CODE REVIEW

**Comment by abprash** [comment]
@elasticmachine please test this

**Comment by jakelandis** [comment]
@abprash thanks for the contribution. However, after review a dedicated description field doesn't provide much value beyond adding a description field to the metadata. e.g.
```
  "metadata" : {
    "description" : "my description"
  }
```

Closing this PR.

**Comment by abprash** [comment]
Hi @jakelandis , thank you for the feedback. Could you elaborate a bit on what are the intended code changes to be made. Would be helpful for me to progress in the right direction.

**Comment by happyCupcake** [comment]
@jakelandis It seems like we no longer need a description field and hence we should close this issue https://github.com/elastic/elasticsearch/issues/35595 ?

**Pull request closed without merging**
