### PR TITLE
[Tests] Do not use all permits acquisition in replica promotion tests

### LINKED ISSUE #35850: [CI] Failures in IndexShardTests#testRollbackReplicaEngineOnPromotion
Build failure: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+intake/263/console

```
java.lang.AssertionError: 
Expected: <70L>
     but: was <79L>
	at __randomizedtesting.SeedInfo.seed([751069218676973A:B78A6A21D330A536]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.index.shard.IndexShardTests.testRollbackReplicaEngineOnPromotion(IndexShardTests.java:1129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.lang.Thread.run(Thread.java:748)
```

Reproduce line (doesn't reproduce locally for me so far):
```
 ./gradlew :server:test -Dtests.seed=751069218676973A -Dtests.class=org.elasticsearch.index.shard.IndexShardTests -Dtests.method="testRollbackReplicaEngineOnPromotion" -Dtests.security.manager=true -Dtests.locale=en-CA -Dtests.timezone=Australia/Perth -Dcompiler.java=11 -Druntime.java=8
```

### PR DESCRIPTION
**Pull request by tlrx**
The pull request #35540 changed the IndexShardTests to randomize usages between the acquisition of a single permit vs the acquisition of all permits when executing an operation on a replica. Although it works for most tests cases, the tests `testRestoreLocalHistoryFromTranslogOnPromotion()` and `testRollbackReplicaEngineOnPromotion()` promotes a replica and this promotion triggers a primary term bump which requires by nature all permits to be executed. This does not play well if the randomized usage of replica permit acquisition method already acquired all the permits when promoting the replica.

This pull request unmute the tests and replaces the randomized usage with the single permit acquisition method like it was before #35540.

Closes #35850

### CODE REVIEW

**Comment by tlrx** [comment]
@elasticmachine test this please

**Review by s1monw — APPROVED** [review]
LGTM

**Comment by bleskes** [comment]
@trlx I think I need more info. This worries me as we want the exclusive replication action to behave exactly like a normal replication action - with all the rollback semantics etc. Can unpack a bit what you meant with "This does not play well"?

**Comment by tlrx** [comment]
> Can unpack a bit what you meant with "This does not play well"?

@bleskes Sure, and thanks for insisting. The test is testing the rollback of the replica engine when the replica got promoted (ie when the primary term is increased). The logic to bump the primary term and to  rollback the engine requires all the index shard permits, so as soon as we detect that the primary term must be modified the other operations will be delayed (this is a property of the asyncBlockOperations() method). This guarantees that a single permit replication action will be executed after the primary term is bumped/replica engine is rollbacked/global checkpoint updated.

With the change made in #35540, the replication action randomly requires all permits to be executed. In those cases the replication action and the bumping term logic are competing for the acquisition of all permits, without the guarantee that the replication action will be executed after the bump of primary/engine rollback etc.

Now I'm writing this I'm wondering if we should instead change the innerAcquireReplicaOperationPermit() logic to ensure that the replication action is always executed after the bump/rollback of the engine so that it does not rely on the delaying of ops in IndexShardOperationPermits.

**Comment by tlrx** [comment]
> Now I'm writing this I'm wondering if we should instead change the innerAcquireReplicaOperationPermit() logic to ensure that the replication action is always executed after the bump/rollback of the engine so that it does not rely on the delaying of ops in IndexShardOperationPermits.

@bleskes I was thinking of something like https://github.com/tlrx/elasticsearch/commit/57f6c69960c06402f30d199901037d586a61000f . Let me know what you think

**Comment by tlrx** [comment]
Closed in favor of #36116

**Pull request closed without merging**
