### PR TITLE
Ingest Attachment: Upgrade tika to v1.22

### PR DESCRIPTION
**Pull request by imotov**
Upgrades:
Apache Tika: 1.19.1 -> 1.22.
pdfbox : 2.0.12 -> 2.0.16
poi : 4.0.0 -> 4.0.1

WIP: epub test fails for some reason. I am still investigating.

### CODE REVIEW

**Comment by imotov** [comment]
@elasticmachine run elasticsearch-ci/1

**Review by martijnvg — APPROVED** [review]
LGTM

**Comment by imotov** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by imotov** [comment]
@elasticmachine run elasticsearch-ci/1

**Pull request merged**
