### PR TITLE
Fix topDocs.totalHits assignment on scroll queries

### LINKED ISSUE #28611: composite aggregation as child aggregation
The 6.x new composite aggregation provides a way to scroll and page on terms bucket, and it's a good thing.
However, it's not (for now?) possible to set a composite aggregation as a child of another bucket aggregation.
So it's impossible, for example, to composite-aggregate on a nested or a child entity. This request is not allowed :

```
{
        "metadatas" : {
            "nested" : {
                "path" : "metaDatas"
            },
            "aggs" : {
                "msisdn" : {
                  "filter" : { "term": { "metaDatas.name": "msisdn" } },
                  "aggs": {
                    "msisdns": {
                       "composite" : {
                          "size":5,
                          "sources" : [{ "value": { "terms" : { "field": "metaDatas.value.raw" } } }]
                       }
                    }
                  }
                }
            }
        }
    }
```
I don't understand this limitation. 
Furthermore, an ES 6.2 patched without the check seems to work as expected.
 ```
@Override
    protected AggregatorFactory<?> doBuild(SearchContext context, AggregatorFactory<?> parent,
                                           AggregatorFactories.Builder subfactoriesBuilder) throws IOException {
        /*if (parent != null) {
            throw new IllegalArgumentException("[composite] aggregation cannot be used with a parent aggregation");
        }*/
```
any insight ?

### LINKED ISSUE #37179: [CI] SearchStatsIT & IndexingIT failures
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/1090/console

This is a reproducible failure that errors with 

```
  2> java.lang.AssertionError
  2>    at __randomizedtesting.SeedInfo.seed([33185699574722A3]:0)
  2>    at org.elasticsearch.action.search.SearchPhaseController$TopDocsStats.getTotalHits(SearchPhaseController.java:763)
  2>    at org.elasticsearch.action.search.SearchPhaseController.reducedQueryPhase(SearchPhaseController.java:510)
  2>    at org.elasticsearch.action.search.SearchPhaseController.reducedQueryPhase(SearchPhaseController.java:421)
  2>    at org.elasticsearch.action.search.SearchPhaseController.reducedScrollQueryPhase(SearchPhaseController.java:412)
  2>    at org.elasticsearch.action.search.SearchScrollQueryThenFetchAsyncAction$1.run(SearchScrollQueryThenFetchAsyncAction.java:71)
  2>    at org.elasticsearch.action.search.SearchScrollAsyncAction$1.innerOnResponse(SearchScrollAsyncAction.java:189)
  2>    at org.elasticsearch.action.search.SearchActionListener.onResponse(SearchActionListener.java:45)
```

```
./gradlew :server:integTest \
  -Dtests.seed=33185699574722A3 \
  -Dtests.class=org.elasticsearch.search.stats.SearchStatsIT \
  -Dtests.method="testOpenContexts" \
  -Dtests.security.manager=true \
  -Dtests.locale=ga-IE \
  -Dtests.timezone=Africa/Windhoek \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

### PR DESCRIPTION
**Pull request by jimczi**
This change fixes an unreleased bug that assigns the wrong totalHits to scroll
queries.

Closes #37179

### CODE REVIEW

**Comment by jimczi** [comment]
@elasticmachine run gradle build tests 1

**Comment by jimczi** [comment]
Last failure is not related to this bug (jvm crash):

@elasticmachine run gradle build tests 1

**Comment by jimczi** [comment]
Unrelated failure:
```
REPRODUCE WITH: ./gradlew :server:unitTest -Dtests.seed=FEEA6BEE209716B9 -Dtests.class=org.elasticsearch.search.geo.GeoShapeQueryTests -Dtests.method="testQueryRandomGeoCollection" -Dtests.security.manager=true -Dtests.locale=ga -Dtests.timezone=America/Indiana/Indianapolis -Dcompiler.java=11 -Druntime.java=8
```

@elasticmachine run gradle build tests 1

**Review by romseygeek — APPROVED** [review]
LGTM

**Pull request merged**
