### PR TITLE
MINOR: Remove Some Dead Code in Scripting

### PR DESCRIPTION
**Pull request by original-brownbear**
* Method override for mock filter script is redundant (parent is the same method)
* The is default check method is not used in ScriptType
* The removed fields on ExpressionSearchScript are unused

### CODE REVIEW

**Comment by original-brownbear** [comment]
Jenkins test thsi

**Comment by original-brownbear** [comment]
Jenkins test this

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by original-brownbear** [comment]
@rjernst thanks!

**Pull request merged**
