### PR TITLE
[CCR] Added validation for auto follow pattern names and

### PR DESCRIPTION
**Pull request by martijnvg**
changed the auto follow stats api path from `/_ccr/auto_follow/stats` to `/_ccr/auto_follow/_stats`.

### CODE REVIEW

**Comment by bleskes** [comment]
@martijnvg what's the motivation for this? I presume it's to avoid collisions with the get a single auto follow pattern with the id `stats`.  If that's the case, its first time we do this (all sub actions don't include an `_` in their names, including `_node/stats`). I wonder if we should change the ccr stats endpoint to have sections - one for auto follow and one for the shard tasks (I'm aware we're short on time and we can discuss options if we agree on that direction).

**Comment by martijnvg** [comment]
> I presume it's to avoid collisions with the get a single auto follow pattern with the id stats.

That is correct.

> If that's the case, its first time we do this (all sub actions don't include an _ in their names, including _node/stats).

The indices stats api does include an underscore, so I think using `_stats` in auto follow stats api is okay?

>  I wonder if we should change the ccr stats endpoint to have sections - one for auto follow and one for the shard tasks 

I'm not sure. The way auto follow stats and index follow stats are gathered is completely different.

**Comment by bleskes** [comment]
> The indices stats api does include an underscore, so I think using _stats in auto follow stats api is okay?

The indices api only has one `_` and it is the main action. Here we have `_ccr/auto-follow/_stats` (not the `_ccr`)

>> I wonder if we should change the ccr stats endpoint to have sections - one for auto follow and one for the shard tasks
> I'm not sure. The way auto follow stats and index follow stats are gathered is completely different.

I don't think it really matters how we collect them but rather whether it makes sense from a user perspective. My idea was to change the top level ccr stats (`/_ccr/stats`) to return all things ccr and have the `{index}/_ccr/stats` return index specific information (i.e., following stats).

**Comment by martijnvg** [comment]
Closing, because the auto follow stats api is going to be implemented differently.

**Pull request closed without merging**
