### PR TITLE
Remove support for chained multi-fields.

### PR DESCRIPTION
**Pull request by jtibshirani**
Follow-up to #41926, where we deprecated support for multi-fields within
multi-fields.

Addresses #41267.

### CODE REVIEW

**Review by jpountz — APPROVED** [review]

**Comment by jtibshirani** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by jtibshirani** [comment]
Thanks @jpountz for the review. @gwbrown raised the good point that we usually always support reading indexes from the previous major version, but that this change doesn't follow that standard. One option is to hold off on removing support until 9.0, and just emit deprecation warnings for the duration of 8.x. Although I expect it to be quite rare to define chained multi-fields, it seems best to stick with our backwards-compatibility guarantees as much as possible. I'm curious as to both of your opinions.

**Comment by jtibshirani** [comment]
Thanks @jpountz for the review. @gwbrown raised the good point that we usually always support reading indexes from the previous major version, but that this change doesn't follow that standard. One option is to hold off on removing support until 9.0, and just emit deprecation warnings for the duration of 8.x. Although I expect it to be quite rare to define chained multi-fields, it seems best to stick with our backwards-compatibility guarantees as much as possible. I'm curious as to both of your opinions.

**Comment by jpountz** [comment]
Oh, that is a good observation @gibrown ! @jtibshirani We would only fail the parsing of the index creation version is gte 8.0?

**Comment by jtibshirani** [comment]
> We would only fail the parsing of the index creation version is gte 8.0?

Ah right, that is the proper way to do it. I'll update this PR.

**Comment by jtibshirani** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by jtibshirani** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by jtibshirani** [comment]
I'm going to merge this assuming the approval still applies, always happy to make changes in a follow-up if you have comments.

**Review by jpountz — APPROVED** [review]
LGTM :)

**Comment by jtibshirani** [comment]
@jpountz @gwbrown I'll plan to merge this today unless you have further comments.

**Comment by jtibshirani** [comment]
Oops I had a race condition with updating my comment :) Thanks for taking another look!

**Pull request merged**
