### PR TITLE
#27319: Decay score function throws 'unknown field' when filtering wi…

### PR DESCRIPTION
**Pull request by swethapavan**
Please have a look and let me know if any changes are needed.

### CODE REVIEW

**Comment by karmi** [comment]
Hi @swethapavan, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/elasticsearch/pull/27473.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by cbuescher** [comment]
@swethapavan thanks for opening this PR. Judging from the comment in the parseVariable() function the exception we throw here is there for a purpose. Could you please explain what use case you are trying to solve with this PR and what is blocking you currently?

**Comment by cbuescher** [comment]
@swethapavan sorry for the noise, I just saw this was discussed in https://github.com/elastic/elasticsearch/issues/27319 already, I didn't see the issue number this was refering to in the title.

**Review by jimczi — COMMENTED** [review]
It looks good ! Thanks @swethapavan 
When this issue was discovered I though that https://github.com/elastic/elasticsearch/pull/26115 could still fail the query if the strict mode was activated. Though it is not certain that we'll add this strict mode check so I wonder if we need another option in the `decay` function to explicitly ignore unmapped fields: `ignore_unmapped` which defaults to false ? I am afraid that without being explicit about leniency we may hide an issue for users that made a typo in the field name for instance.
@colings86 @jpountz WDYT ?

**Comment by jpountz** [comment]
I agree with you this is a bit trappy. I guess that not getting any matches when searching an unmapped field is expected. Getting scores of zero when a field that is used for scoring does not exist isn't as obvious to me. But then should we also do something for fields that are mapped but do not have a value for a document that needs to be scored?

I dislike adding a per-query option because there are probably use-cases for enforcing that fields are mapped on every query, which would significantly increase the surface area of our API which is already quite complex.

Maybe we should revisit this PR once we are settled on #26115.

**Comment by jimczi** [comment]
> Maybe we should revisit this PR once we are settled on #26115.

Thanks @jpountz , agreed.
@swethapavan sorry I though we'd have a consensus with #26115 in but we are not sure anymore if this strict field mode will be added or not so I am adding the "stalled" label for now and I'll come back when we have a conclusion for #26115.

**Comment by Hindu** [comment]
What is the fate of this PR?

**Comment by colings86** [comment]
This PR is stalled pending the decision on whether to progress with the linked change in #26115. That PR is still being discussed.

**Comment by cbuescher** [comment]
Seems this is still stalled, but cc @elastic/es-search-aggs

**Comment by polyfractal** [comment]
Ran across this in Fixit Thursday.

@jimczi @jpountz is this still something we want to do?  #26115 ended up closing without merging, but on the other hand `function_score` will soon be deprecated.  Not sure what our thoughts are at this point.

**Comment by jpountz** [comment]
Discussed in the search meeting, we agreed to make unmapped fields behave like a mapped field that doesn't have any values.

**Comment by jimczi** [comment]
This PR seems outdated. I am closing it now, feel free to reopen or comment if this change is still needed.

**Pull request closed without merging**
