### PR TITLE
Remove allowTrial flag in license checking

### PR DESCRIPTION
**Pull request by rjernst**
The allowTrial flag is always true, since trial licenses act as though
everything is licensed. This commit removes the allowTrial flag in
license checking helper methods.

### CODE REVIEW

**Review by nik9000 — APPROVED** [review]
LGTM

**Comment by jkakavas** [comment]
Happy to discuss this again and/or drop it if we have consensus yo do so but we intentionally left this be in the previous refactoring work : https://github.com/elastic/elasticsearch/pull/51864#discussion_r374692658

**Comment by rjernst** [comment]
@jkakavas Thanks for the context. I did not know about that previous discussion. However, I still think we should move forward with this. From that discussion:

> I  was just trying to make a point that it is not unheard of to have the need to treat trial differently

Except it is actually unheard of, which is why allowTrial is always true.

Additionally, the ultimate goal of my refactorings is to remove all of the isXXXAllowed methods in favor of a single method that takes an enum, where the enum values represent licensed features, so that only adding a value to this enum is required for a new feature. If a feature in the future is deemed necessary to not be allowed with a trial license, we can easily add it back to the enum and single isAllowed method.

**Comment by rjernst** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample-matrix-unix

**Pull request merged**
