### PR TITLE
Fix split package org.apache.lucene.util

### PR DESCRIPTION
**Pull request by ChrisHegarty**
To allow for the future modularization of Elasticsearch with Java Modules, there are a number preparatory tasks that need be completed. This is one part of one such task: eliminate split packages.

Since recent Lucene upgrades, `CombinedBitSet` no longer requires package-private access. This PR proposes to keep `CombinedBitSet` in sever, but moved it to `org.elasticsearch.lucene.util`. `CombinedBitSet` is used by both server and x-pack-core.

relates #78166

### CODE REVIEW

**Comment by ChrisHegarty** [comment]
@elasticmachine test this please

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by ChrisHegarty** [comment]
@elasticmachine test this please

**Comment by ChrisHegarty** [comment]
@elasticmachine test this please

**Pull request merged**
