### PR TITLE
[Data-Frame] make the config be strictly parsed on _preview

### PR DESCRIPTION
**Pull request by benwtrent**
Simple change, it should have been strictly parsed from the get go....

### CODE REVIEW

**Review by dimitris-athanasiou — APPROVED** [review]
LGTM

**Comment by hendrikmuhs** [comment]
may I play devils advocate?

If we missed this in the 1st place it means we lack a test.

**Comment by benwtrent** [comment]
@elasticmachine
run elasticsearch-ci/1
run elasticsearch-ci/2
run elasticsearch-ci/bwc
run elasticsearch-ci/default-distro

**Comment by benwtrent** [comment]
run elasticsearch-ci/bwc

**Review by hendrikmuhs — APPROVED** [review]
LGTM

**Comment by benwtrent** [comment]
run elasticsearch-ci/bwc

**Comment by benwtrent** [comment]
run elasticsearch-ci/bwc

**Comment by benwtrent** [comment]
run elasticsearch-ci/bwc

**Comment by benwtrent** [comment]
run elasticsearch-ci/bwc

**Pull request merged**
