### PR TITLE
Adding inference endpoint validation for AzureAiStudioService

### PR DESCRIPTION
**Pull request by dan-rubinstein**
## Description
This change introduces:
- Adds new validation logic for creating endpoints in AzureAiStudioService. This requires adding a new validator for chat completion endpoints. This new validator calls to update any chat completion details (ex. max tokens in task settings) if required (currently we only do updates in AzureAiStudioService so for other services this will do nothing).

Note: There is currently a bug preventing calls to AzureAiStudioService completion models. Merging this PR is blocked until we are able to investigate it further and provide a fix so that we can fully test this change.

## Testing
- Ran unit tests and ensured that all succeed
- Valid AzureAiStudioService text embedding endpoint can be created, embedding details are updated, and validation call is made.
- Invalid AzureAiStudioService text embedding endpoint fails creation.
- Valid AzureAiStudioService completion endpoint can be created, chat completion details are updated, and validation call is made.
- Invalid AzureAiStudioService completion endpoint fails creation.
- Valid non-AzureAiStudioService completion endpoint can be created, no chat completion details are updated, and validation call is made.
- Invalid non-AzureAiStudioService completion endpoint fails creation.

### CODE REVIEW

**Comment by dan-rubinstein** [comment]
@elasticmachine merge upstream

**Review by maxhniebergall — APPROVED** [review]
LGTM

**Comment by dan-rubinstein** [comment]
@elasticmachine merge upstream

**Comment by dan-rubinstein** [comment]
@elasticmachine merge upstream

**Pull request merged**
