### PR TITLE
Increment settings version when upgrading index

### PR DESCRIPTION
**Pull request by jasontedor**
When we upgrade an index, we set the settings version upgraded setting. This should be considered a settings change, and therefore we need to increment the settings version. This commit addresses that.

Relates #34429

### CODE REVIEW

**Review by s1monw — APPROVED** [review]
LGTM

**Review by s1monw — APPROVED** [review]

**Review by martijnvg — APPROVED** [review]
LGTM

**Comment by jasontedor** [comment]
@elasticmachine test this please

**Comment by jasontedor** [comment]
@elasticmachine run sample packaging tests

**Pull request merged**
