### PR TITLE
Remove ThreadGroup#allowThreadSuspension from forbidden APIs

### PR DESCRIPTION
**Pull request by williamrandolph**
java.lang.ThreadGroup#allowThreadSuspension(boolean) was removed in JDK 21. See https://www.oracle.com/java/technologies/javase/21all-relnotes.html#JDK-8297295

### CODE REVIEW

**Comment by mark-vieira** [comment]
I assume we don't have any usages of this then otherwise we'd see runtime errors when running on a Java 21 JRE?

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by williamrandolph** [comment]
@elasticsearchmachine please run elasticsearch-ci/part-1

**Comment by williamrandolph** [comment]
@mark-vieira Right. If there were usages, we'd have hit runtime or compilation failures when we moved to JDK 21. And a `git grep` search for the method turned up nothing.

**Pull request merged**
