### PR TITLE
Remove vestiges of animal sniffer

### PR DESCRIPTION
**Pull request by jasontedor**
We no longer need animal sniffer because we use JDK functionality (introduced in JDK 9) to target older versions of the JDK for compilation. This functionality means that the JDK handles the problem of ensuring that we do not use JDK APIs from the version that we are compiling from that are not available in the version that we are compiling to. A previous commit removed this for the REST client (where we target JDK 7) but a few traces were left behind.

Relates #29646

### CODE REVIEW

**Review by javanna — APPROVED** [review]
good one thanks for catching it

**Review by nik9000 — APPROVED** [review]
I think this include the cli which it shouldn't. The animal sniffer stuff looks good. So long as you merge it after the cli move it should be fine.

**Comment by jasontedor** [comment]
Oops, that was an inadvertent pickup. Thanks for noticing @nik9000.

**Comment by jasontedor** [comment]
Relates #31230

**Comment by atorok** [comment]
We have to take it off the buildscript classpath as well, I'll do that in #31271 now.

**Pull request merged**
