### PR TITLE
Increase the number of vector dims to 2048

### PR DESCRIPTION
**Pull request by mayya-sharipova**

### CODE REVIEW

**Comment by mayya-sharipova** [comment]
As there are some neural networks that produce vectors with dims > 1024 (see a discussion [here](https://github.com/elastic/elasticsearch/issues/40492#issuecomment-533225507), we need to increase the max dims to 2048.

**Comment by mayya-sharipova** [comment]
For 7.5 backport a note with increased number of dims will be added to migrate_7_5.asciidoc.

**Comment by mayya-sharipova** [comment]
@jtibshirani This PR is ready for another review.

**Comment by mayya-sharipova** [comment]
@elasticmachine  run elasticsearch-ci/1

**Comment by mayya-sharipova** [comment]
@elasticmachine run  elasticsearch-ci/docs-check

**Comment by mayya-sharipova** [comment]
@elasticmachine run elasticsearch-ci/oss-distro-docs

**Review by jtibshirani — APPROVED** [review]
Looks good to me.

**Comment by jtibshirani** [comment]
For future context, we made the decision to raise the limit because we've encountered a couple well-known models that produce vectors with > 1024 dimensions.

We're not planning to increase the limit further unless we hear from a few users about common models / use cases that require more dimensions.

**Pull request merged**
