### PR TITLE
[DOCS] Fix typo

### PR DESCRIPTION
**Pull request by sasukerui**
According to the source code ,will never trip the breaker if the limit is set to -1

### CODE REVIEW

**Comment by sasukerui** [comment]
It should be changed like this, let me change it.

Add a number of bytes, tripping the circuit breaker if the aggregated
     * estimates are above the limit. Automatically trips the breaker if the
     * memory limit is set to 0. Will never trip the breaker if the limit is
     * set to -1, but can still be used to aggregate estimations.

**Review by jrodewig — APPROVED** [review]
LGTM. Thanks @sasukerui.

**Comment by jrodewig** [comment]
@elasticmachine ok to test

**Comment by jrodewig** [comment]
@elasticmachine update branch

**Pull request merged**
