### PR TITLE
Health api telemetry

### PR DESCRIPTION
**Pull request by gmarouli**
Introduce Health API telemetry. We track the health api responses and count certain characteristics like statuses, indicators etc.

Sample response:
```
  {
    "invocations": {
      "total": 22,
      "verbose_true": 12,
      "verbose_false": 10
    },
    "statuses": {
      "green": 10,
      "yellow": 4,
      "red": 8
    },
    "indicators": {
      "red" : {
        "master_stability": 2,
        "ilm":2,
        "slm": 4
      },
      "yellow": {
        "disk": 1,
        "shards_availability": 1,
        "master_stability": 2
      }
    },
    "diagnoses": {
      "red": {
        "elasticsearch:health:shards_availability:primary_unassigned": 1,
        "elasticsearch:health:disk:add_disk_capacity_master_nodes": 3
      },
      "yellow": {
        "elasticsearch:health:disk:add_disk_capacity_data_nodes": 1
      }
    }
  }

```

### CODE REVIEW

**Comment by gmarouli** [comment]
Considering to add an extra terms field on status, indicator and diagnosis:

```
  {
    "invocations": {
      "total": 22,
      "verbose_true": 12,
      "verbose_false": 10
    },
    "statuses": {
      "green": 10,
      "yellow": 4,
      "red": 8,
      "values": ["green", "yellow", "red"]
    },
    "indicators": {
      "red" : {
        "master_stability": 2,
        "ilm":2,
        "slm": 4,
        "values": ["master_stability", "ilm", "slm"]
      },
      "yellow": {
        "disk": 1,
        "shards_availability": 1,
        "master_stability": 2,
        "values": ["disk", "shards_availability", "master_stability"]
      }
    },
    "diagnoses": {
      "red": {
        "elasticsearch:health:shards_availability:primary_unassigned": 1,
        "elasticsearch:health:disk:add_disk_capacity_master_nodes": 3,
        "values": ["elasticsearch:health:shards_availability:primary_unassigned", "elasticsearch:health:disk:add_disk_capacity_master_nodes"]
      },
      "yellow": {
        "elasticsearch:health:disk:add_disk_capacity_data_nodes": 1,
        "values": [""elasticsearch:health:disk:add_disk_capacity_data_nodes"]
      }
    }
  }
```

**Comment by andreidan** [comment]
>WDYT?

Interesting idea! How does the mapping for `values` look like? 
Will it dynamically handle new health API diagnosis and indicators or do we need those changes to be coupled with telemetry mapping changes?

**Comment by gmarouli** [comment]
@elasticmachine update branch

**Comment by andreidan** [comment]
>I don't fully understand your question about values being in an object field.

**Comment by gmarouli** [comment]
Closed and replaced by two PRs: 
- https://github.com/elastic/elasticsearch/pull/91559
- coming soon

**Pull request closed without merging**
