### PR TITLE
Remove obsolete BWC checks in OS stats

### PR DESCRIPTION
**Pull request by danhermann**
These checks resolve the mixed cluster test failures between 6.8 and 7.x (thanks!) but shouldn't be necessary in 8.x since only 7.latest nodes can form a cluster with 8.x and 7.latest has all the guards against negative stats values in it.

### CODE REVIEW

**Comment by danhermann** [comment]
@elasticmachine run elasticsearch-ci/part-1

**Comment by danhermann** [comment]
@elasticmachine update branch

**Review by dakrone — APPROVED** [review]
LGTM

**Comment by danhermann** [comment]
Thanks, @dakrone!

**Pull request merged**
