### PR TITLE
Cache immutable translog lastModifiedTime

### PR DESCRIPTION
**Pull request by luyuncheng**
`TranslogReader` is an immutable translog file reader. it seems we can read lastModifiedTime once instead of every time.

This PR issue reference #82720

### CODE REVIEW

**Comment by joegallo** [comment]
@luyuncheng this looks great! I added some commits that changed the approach a little bit. 

Would you please sign the contributor agreement? https://github.com/elastic/elasticsearch/pull/82721#issuecomment-1015388885

**Comment by luyuncheng** [comment]
@joegallo  Thanks for reviewing this PR, i have been signed contributor agreement. 
and thanks for format my code. i also added a changelog file.

**Comment by joegallo** [comment]
Jenkins test this

**Comment by original-brownbear** [comment]
Jenkins run  elasticsearch-ci/part-2

**Review by original-brownbear — APPROVED** [review]
Thanks Joe + @luyuncheng ! LGTM

**Pull request merged**
