### PR TITLE
Update certs for PKI tests and re-enable tests

### LINKED ISSUE #97756: Pki test certs expired
### CI Link

https://gradle-enterprise.elastic.co/s/jze725jpxi7ki/console-log?task=:x-pack:plugin:security:internalClusterTest

### Repro line

./gradlew ':x-pack:plugin:security:internalClusterTest' --tests "org.elasticsearch.xpack.security.authc.pki.PkiAuthDelegationIntegTests.testDelegateThenAuthenticate" -Dtests.seed=F5EC1FEFFC2FC08B -Dtests.locale=en-GB -Dtests.timezone=SystemV/PST8PDT -Druntime.java=20

### Does it reproduce?

Yes

### Applicable branches

main

### Failure history

_No response_

### Failure excerpt

The pki integ test began failing today. Looking at the certs the test uses, they are all expired:

```
❯ openssl x509 -enddate -noout -in testClient.crt
notAfter=Jul 18 13:33:41 2023 GMT
❯ openssl x509 -enddate -noout -in testIntermediateCA.crt
notAfter=Jul 18 13:32:34 2023 GMT
❯ openssl x509 -enddate -noout -in testRootCA.crt
notAfter=Jul 18 13:32:20 2023 GMT
```

### PR DESCRIPTION
**Pull request by jakelandis**
The certs for the PKI tests expired and the test was muted. 
This commit follows the instructions in the read to update the certs and unmutes the test. 
The certs will now expire 20 years from now. 

fixes: #97756

### CODE REVIEW

**Review by n1v0lg — APPROVED** [review]

**Comment by jakelandis** [comment]
@elasticsearchmachine run elasticsearch-ci/part-1-fips

(error was environmental: java.lang.OutOfMemoryError: Requested array size exceeds VM limit)

**Comment by jakelandis** [comment]
hmm... [failed](
https://gradle-enterprise.elastic.co/s/i6xnt5zgfpwui/tests/:test:external-modules:test-die-with-dignity:javaRestTest/org.elasticsearch.qa.die_with_dignity.DieWithDignityIT/testDieWithDignity?top-execution=1) twice with `./gradlew ':test:external-modules:test-die-with-dignity:javaRestTest' --tests "org.elasticsearch.qa.die_with_dignity.DieWithDignityIT.testDieWithDignity"  -Dtests.fips.enabled=true` and fails locally.  Updated branch to ensure I don't have a stale base , but the changes over at https://github.com/elastic/elasticsearch/pull/97734 are prime suspect as test was rewritten yesterday and fips mode was not enabled.

**Comment by jakelandis** [comment]
The FIPs test issue will be fixed once https://github.com/elastic/elasticsearch/pull/97776 is merged.

**Review by albertzaharovits — APPROVED** [review]
LGTM
It won't surprise me if some JDK's TLS implementation won't validate certs expiring too far into the future. But if CI is good nothing to worry about.

**Pull request merged**
