### PR TITLE
[ML] fixing tests

### LINKED ISSUE #48082: ClassificationIT.testDependentVariableCardinalityTooHighError failing on master
I've seen this test fail a handful of times over the course of the day, a couple on master and a few times on PR test failures according to build stats. I've not been able to reproduce it locally yet.

```
./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.ClassificationIT.testDependentVariableCardinalityTooHighError" \
  -Dtests.seed=AA98A6F1439DB43E \
  -Dtests.security.manager=true \
  -Dtests.locale=es-BZ \
  -Dtests.timezone=Pacific/Bougainville \
  -Dcompiler.java=12 \
  -Druntime.java=11
```

Scan: https://gradle-enterprise.elastic.co/s/tfir4yhfyz3ja

Failure: 
```
org.elasticsearch.xpack.ml.integration.ClassificationIT > testDependentVariableCardinalityTooHighError FAILED
--
junit.framework.AssertionFailedError: Expected exception ElasticsearchStatusException but no exception was thrown
at __randomizedtesting.SeedInfo.seed([AA98A6F1439DB43E:2EE500419C29C471]:0)
at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2722)
at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2712)
at org.elasticsearch.xpack.ml.integration.ClassificationIT.testDependentVariableCardinalityTooHighError(ClassificationIT.java:267)
```

### LINKED ISSUE #48085: Analytics audit message tests failing
audit message assertions are failing due to a new message now being written to notifications index.

### PR DESCRIPTION
**Pull request by benwtrent**
New audit message is now logged when the model is saved.

Refreshing indexes for better test stability.

closes https://github.com/elastic/elasticsearch/issues/48082

closes  #48085

### CODE REVIEW

**Review by droberts195 — APPROVED** [review]
LGTM

**Review by droberts195 — CHANGES_REQUESTED** [review]
Gah, I wasn't looking closely when I reviewed this last night.

`RunDataFrameAnalyticsIT` (which is basically outlier detection IT) should _not_ have the "Stored trained model with id" messages, as we don't currently store a trained model for outlier detection.  Sorry I didn't notice this yesterday.

Also, this PR should be backported to 7.6 but not 7.5, and we need to take extreme care with that backport to avoid excessive test noise.  The whole of `RegressionIT` and `ClassificationIT` should be muted on the 7.x branch _after_ 7.5 is branched.  Then we backport the C++ change that triggers these extra messages.  Then, once that's built successfully, we unmute `RegressionIT` and `ClassificationIT` on 7.x.

/cc @valeriy42

**Comment by benwtrent** [comment]
@droberts195 yes, I agree :). I have already fixed the outlier detection deal as they are not storing models :D. 

As for muting the tests, yep, I will back port that change after the change for storing the models (Java side) is backported.

**Review by przemekwitek — APPROVED** [review]
LGTM

**Review by droberts195 — APPROVED** [review]
LGTM

**Comment by benwtrent** [comment]
run elasticsearch-ci/packaging-sample-matrix

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Comment by benwtrent** [comment]
run elasticsearch-ci/1
run elasticsearch-ci/2

**Comment by benwtrent** [comment]
run elasticsearch-ci/1
run elasticsearch-ci/2

**Comment by przemekwitek** [comment]
FYI: Classification analysis does not store the model as well.
Fix is here: https://github.com/elastic/elasticsearch/pull/48332

**Pull request merged**
