### PR TITLE
Add cgroup memory usage/limit to OS stats on Linux

### PR DESCRIPTION
**Pull request by droberts195**
This change adds cgroup memory usage/limit to the OS stats section of
the node stats on Linux.  This information is useful because in Docker
containers the standard node stats report the host memory limit, not
taking account of extra restrictions that may have been applied to the
container.

### CODE REVIEW

**Comment by droberts195** [comment]
The mixed cluster tests are failing in the CI build of this PR.  The reason is that I am planning to backport this to 6.1 and have set up the version checks in the serialisation code accordingly, but since this is not yet merged to 6.1 it makes the BWC cluster crash.

**Comment by jasontedor** [comment]
One way to deal with this is to set the serialization version and skips in master to 7.0.0, then backport to 6.x with these set to 6.1.0, then push one more commit to master moving to 6.1.0. With this method, it's possible to have green builds every step of the way. This is preferred.

**Comment by droberts195** [comment]
Thanks for the tip @jasontedor.  I have changed the skips to 7.0.0-alpha1 and now the CI is passing.

**Review by jasontedor — COMMENTED** [review]
As we discussed in another channel, I think we should avoid losing the ability to compare what a user sees in `/sys/fs/cgroup/memory` versus the output from the stats APIs. Otherwise, I'm good with this PR.

**Comment by droberts195** [comment]
@jasontedor as discussed I changed the type of the cgroup memory stats to `String` because the value used for "no limit" doesn't fit in `long` and `BigInteger` isn't supported by `XContent`.

Please could you take another look?

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by droberts195** [comment]
Thanks for reviewing @jasontedor.

**Pull request merged**
