### PR TITLE
Add support for the new Java 9 MethodHandles#arrayLength() factory

### PR DESCRIPTION
**Pull request by uschindler**
Since build 120, Java 9 contains a factory method to get a highly optimized (inlined) MethodHandle for the array length. This PR adds support for it through dynamic lookup.

Once ES is on Java 9, the workaround hack should be removed (same for the StringConcat).

See: https://bugs.openjdk.java.net/browse/JDK-8156915

### CODE REVIEW

**Comment by uschindler** [comment]
This PR was tested with build 121 of Java 9.

**Comment by uschindler** [comment]
In an ideal world, Elasticsearch would create a Multi-Release JAR file, and would compile the new code only against Java 9, while compiling the old code against Java 8 (both in same JAR file); similar for String Concats!

This is another issue. I am investigating the same for Apache Lucene, where we can supply alternative class files for stuff like VarHandles in MMapDirectory or the new Math functions.

**Comment by rmuir** [comment]
> This PR was tested with build 121 of Java 9.

Thanks for doing this! looks like we are currently on 9-ea+120 in jenkins, but it should still be fine right? I see 8156915 in that one: http://download.java.net/java/jdk9/changes/jdk-9+120.html

**Comment by uschindler** [comment]
Yes build 120 has it. I was just not able to test it, because there was no Windows build for the Policeman.

**Comment by rmuir** [comment]
thanks @uschindler

**Pull request merged**
