### PR TITLE
Double-check local checkpoint for staleness

### PR DESCRIPTION
**Pull request by DaveCTurner**
Today, when determining if an operation is stale, we compare the seqno against
the local checkpoint before looking in the version map. However, in between
these two checks the local checkpoint could advance, causing some tombstones to
become stale, and then the stale tombstones could be collected. In this
situation we might incorrectly decide that the operation is fresh and apply it.

To avoid this situation, check the local checkpoint again after calling
getVersionFromMap(). Since it only ever increases, this gives the right result
despite other concurrent activity.

### CODE REVIEW

**Comment by DaveCTurner** [comment]
Actually turning this into something that can reliably fail a test case seems tricky. Your thoughts welcome.

**Comment by DaveCTurner** [comment]
> Instead I would prefer to move all of it into `compareOpToLuceneDocBasedOnSeqNo`

Sure, I like that idea too.

> I was thinking about this this morning. I was hoping that if we add refreshes to testConcurrentOutOfDocsOnReplica and sometimes run it with gc deletes equal to 0, it will reproduce.

🤞 

I was wondering about adding some kind of

    assert randomDelay();

at strategic points in order to expose rare races more frequently.

**Comment by DaveCTurner** [comment]
@bleskes I looked at `testConcurrentOutOfDocsOnReplica` and it already performs refreshes (every 4 operations) but does not simulate GC deletes as per `assertOpsOnPrimary`. I thought it'd be useful to wrap up each operation along with the things to do after applying it (refresh/flush/GC) as per 5d46eee, and then make the tests more consistent about applying these things, but didn't want to go too far down that path without your thoughts. WDYT?

**Comment by bleskes** [comment]
@DaveCTurner shall we close this in favour of https://github.com/elastic/elasticsearch/pull/30121 ?

**Comment by DaveCTurner** [comment]
Yes, lets.

**Pull request closed without merging**
