### PR TITLE
Fix wrong result when executing bulk requests with and without pipeline

### LINKED ISSUE #60437: Bug in bulk requests with mix of requests with and without pipelines
Elasticsearch version: 7.8
Plugins: N/A
OS: Red Hat 8

Posted on discussion forums: https://discuss.elastic.co/t/bug-in-bulk-requests-with-mix-of-requests-with-and-without-pipelines/242973

This bug exists in Elasticsearch 7.8. I know it doesn't exist in 6.8 but I haven't looked at all the in-between versions.

If I put together a bulk request with a mix of indexing requests with some that call an ingest pipeline and some that don't then there exists a problem if either the pipeline fails or the pipeline contains a drop processor. The handling of the request plays around with the wrong "slot" number in the bulk request / response as it counts only requests with pipelines to figure out that "slot" for the callback in the "executeBulkRequest" method of "IngestService". This results in the wrong items being marked as failed or dropped. I haven't played with failures so much so that needs verifying but here are some steps to reproduce for the drop processor.

```
 curl -s -XPUT -H Content-type:application/json localhost:9200/_ingest/pipeline/mypipeline -d '{ "processors": [ { "drop": { } } ] }'
```

My bulk request...
```
{"index":{"_index":"myindex","_type":"_doc","_id":"1"}}
{"test":"1"}
{"index":{"_index":"myindex","_type":"_doc","_id":"2","pipeline":"mypipeline"}}
{"test":"2"}
```
```
curl -s -XPOST -H Content-type:application/json localhost:9200/_bulk --data-binary @bulk_request
```

The response...

```
{
  "took": 242,
  "ingest_took": 11,
  "errors": false,
  "items": [
    {
      "index": {
        "_index": "myindex",
        "_type": "_doc",
        "_id": "1",
        "_version": -3,
        "result": "noop",
        "_shards": {
          "total": 0,
          "successful": 0,
          "failed": 0
        },
        "status": 200
      }
    },
    {
      "index": {
        "_index": "myindex",
        "_type": "_doc",
        "_id": "2",
        "_version": 1,
        "result": "created",
        "_shards": {
          "total": 2,
          "successful": 1,
          "failed": 0
        },
        "_seq_no": 0,
        "_primary_term": 1,
        "status": 201
      }
    }
  ]
}
```

And if you search the index it contains the wrong document...

```
{
  "took": 55,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 1,
      "relation": "eq"
    },
    "max_score": 1,
    "hits": [
      {
        "_index": "myindex",
        "_type": "_doc",
        "_id": "2",
        "_score": 1,
        "_source": {
          "test": "2"
        }
      }
    ]
  }
}
```

I believe the fix should be relatively simple in IngestService but maybe I'm missing something.

### PR DESCRIPTION
**Pull request by gaobinlong**
Closes #60437 .

When executing bulk api, if one request has no ingest pipeline and others have ingest pipeline, then the response is not correct, that's because in `IngestService#executeBulkRequest()` method, the cursor `i` doesn't move to next if the request has no ingest pipeline.

The main changes are:
1. fix the bug in `IngestService#executeBulkRequest()`.
2. add some unit tests.
3. add a yaml test.

### CODE REVIEW

**Review by danhermann — APPROVED** [review]
@gaobinlong, thanks for fixing this. I'll get it merged in for the next release.

**Comment by danhermann** [comment]
@elasticmachine ok to test

**Comment by danhermann** [comment]
@elasticmachine update branch

**Comment by danhermann** [comment]
@elasticmachine update branch

**Comment by danhermann** [comment]
@gaobinlong, after running the tests on this one, it appears that one of the new tests (https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-bwc/6187/testReport/junit/org.elasticsearch.backwards/MixedClusterClientYamlTestSuiteIT/test__p0_bulk_90_pipeline_One_request_has_pipeline_and_another_not_/) is failing. Could you take a look at that one?

**Comment by gaobinlong** [comment]
@danhermann, maybe because we have not done the backport, so the new yaml test executes failed when there is a mixed cluster. I'm not clear about how to handle this situation, maybe we can remove the new yaml test and only execute the newly added unit test ?

**Comment by danhermann** [comment]
@gaobinlong, ah, right. I was not paying attention to the fact that it was a backwards compatibility test that failed. If you will add the following lines (including indentation) to the `90_pipeline.yml` file right after "One request has pipeline and another not":

```
  - skip:
      version: " - 7.99.99"
      reason: "change after backporting"
```

That will skip the mixed cluster tests for now and then after I backport the change for earlier releases, I'll change that so that the mixed cluster tests include that for the appropriate releases.

**Comment by gaobinlong** [comment]
@danhermann, I have done that, and all checks have passed yet.

**Comment by danhermann** [comment]
@gaobinlong, great, thank you! I'll get this merged and backported.

**Comment by tvernum** [comment]
@danhermann I think we can remove `backport pending` now. Right?

**Comment by danhermann** [comment]
Finished the last backport to 7.x and removed "backport pending" label.

**Pull request merged**
