### PR TITLE
Remove link between Version and IndexVersion

### PR DESCRIPTION
**Pull request by thecoop**
Remove the field & method linking `Version` with `IndexVersion`.

The build infrastructure will need to be updated to take account of this change

### CODE REVIEW

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by thecoop** [comment]
For some reason this change is making all the bwc tests disappear from gradle. It should still match the regexes in the build code - @mark-vieira do you have any insight what might be going on here?

**Comment by thecoop** [comment]
@elasticmachine update branch

**Comment by thecoop** [comment]
Ah, it was missing Version constants added whilst this branch was active

**Pull request merged**
