### PR TITLE
Remove frozen cache setting leniency

### PR DESCRIPTION
**Pull request by jasontedor**
We previously allowed but deprecated the ability for the shared cache to be positively sized on nodes without the frozen role. This is because we only allocate shared_cache searchable snapshots to nodes with the frozen role. This commit completes our intention to deprecate/remove this ability.

Relates #70341

### CODE REVIEW

**Comment by dakrone** [comment]
Can you also update `docs/reference/searchable-snapshots/index.asciidoc` to mention that the setting is un-settable on non-frozen nodes?

**Comment by jasontedor** [comment]
@dakrone I pushed.

**Review by dakrone — APPROVED** [review]
LGTM, this means I won't have to merge https://github.com/elastic/elasticsearch/pull/70846 to master and can just backport it directly to 7.x when it's approved \o/

**Review by ywelsch — APPROVED** [review]
LGTM

**Review by henningandersen — APPROVED** [review]
LGTM.

**Comment by jasontedor** [comment]
This is stalled on #71084 to easily get the tests to pass here.

**Comment by jasontedor** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Pull request merged**
