### PR TITLE
[Transform] Use deduced mappings for determining proper fields' format even if `deduce_mappings==false`

### LINKED ISSUE #103115: [Transform] Date fields are not output as ISO strings when `deduce_mappings==false`
### Elasticsearch Version

main

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

n/a

### Problem Description

When `deduce_mappings` is set to `false`, the date fields in the transform's group-by section are written to destination index as epoch millis, despite `dates_as_epoch_millis` being `false`.

### Steps to Reproduce

1. Create an `unattended` transform with `deduce_mappings` set to `false`. Transform's destination index should not exist yet.
2. Start the transform.
3. Observe `date` fields being written to dest index as `long`s

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by przemekwitek**
Until now, when destination index was missing, we did not recognize fields' types properly. For example, we would always render a `date` field (e.g.: `timestamp`) as epoch millis even when `dates_as_epoch_millis` setting was set to `false`. That was confusing to the users and not aligned with our documentation.

This PR fixes that in the following manner:
- the code that deduces destination index mappings based on source index mappings is executed even when `deduce_mappings` is set to `false` (it was not the case until now)
- the code that creates destination index still applies the deduced mapping based on the value of `deduce_mappings` setting
- the code that extracts results and prepares them for ingestion into destination index now takes into account the actual destination index mappings (if dest index exists) **or** falls back to deduced destination index mappings (if dest index does not exist)

Note: This PR is a re-introduction of https://github.com/elastic/elasticsearch/pull/103135 which got reverted.

Closes https://github.com/elastic/elasticsearch/issues/103115

### CODE REVIEW

**Comment by droberts195** [comment]
Since the reason for reverting #103135 was the problems it caused with chained transforms, does #104238 need to be fixed before this is merged?

**Comment by przemekwitek** [comment]
> Since the reason for reverting #103135 was the problems it caused with chained transforms, does #104238 need to be fixed before this is merged?

I think the real problem with SLO transforms was missing `defer_validation` parameter on `PUT`. I'm trying to verify this hypothesis now by running this PR (https://github.com/elastic/elasticsearch/pull/103682) on serverless QA. If I reproduce the same issue (BTW, `defer_validation` was added in the meantime) with this PR on serverless QA, then it will prove that this PR is still the culprit and needs to be fixed.

Failing chaining transforms test is kind of independent here. Of course, I'm trying to fix it too and there may happen to be some overlap.

**Comment by przemekwitek** [comment]
> Since the reason for reverting #103135 was the problems it caused with chained transforms, does #104238 need to be fixed before this is merged?

FYI, #104238 is now fixed.

Even though (as explained above) I'm quite sure these 2 were unrelated problems, I fixed the failing test first to minimize the risk as much as possible.

**Review by droberts195 — APPROVED** [review]
LGTM

**Pull request merged**
