### PR TITLE
HLClient: Add get/delete requests to the HighLevel client

### PR DESCRIPTION
**Pull request by dadoonet**
Tests are not passing yet.

But I start this PR to discuss about the organization of things when it comes to add new endpoints.

Let me know what your initial thoughts are about this.

Note that I'm still implementing here the `Consumer` pattern. Waiting for our decision about this.
I introduced it here after I got some comments on my branch: https://github.com/elastic/elasticsearch/commit/906fb0dec5b551f2cc78679ab816f891b9299ae7

### CODE REVIEW

**Comment by rjernst** [comment]
Why are we creating another client, instead of improving the rest client we already added? AFAIU, the low level client was the start, but it is essentially unusable without a lot of work. Why can't we improve this (in the same artifact)? Having more than one client artifact out there would be confusing (well more than one rest client, it is already confusing enough while we are in this in between state with both a rest client and transport client).

**Comment by javanna** [comment]
@rjernst the high level client wraps the low level one and adds objects for requests and responses. The low level client takes care of http requests, fail-over, sniffing etc. and can send requests to any elasticsearch versions, while the high level one will only be able to talk to a specific major version of elasticsearch. The low level client works with java 1.7, while the high level one will require java 1.8.  The high level client will initially depend on elasticsearch core so we can reuse as much from the current java api, on the long run hopefully on less stuff. There's a big difference between the two, that is why we want to keep them distinct. It is true that the low level one requires some work to be used on itself, but people are already using it as it is today, they can have their own marshalling and unmarshalling solution for requests/responses, so I don't think it's true that it is useless on its own.

Confusion is definitely a concern and we have to be careful, probably address it with documentation, but once the transport client is gone, Java will finally be the same as all the other languages when it comes to REST official clients. I don't see why Java should be different there, too bad it was up until now.

**Comment by rjernst** [comment]
My problem is with having two artifacts. I guarantee some users will try to use both. I think the name "high level" is confusing. I think we should just call the high level one "elasticsearch client", and the low level one "elasticsearch http client" or something like that. Eventually these should be rolled into one artifact right? (if someone did want to do their own marshalling at that point, the underly http wrapper could still be public in the client artifact). I think just sticking with one artifact from the start will avoid confusion in the future. Yes it would mean more stuff gets pulled in for those doing their own unmarshalling, but they can use transitive excludes to remove these extra artifacts that they do no use in the interim.

**Comment by javanna** [comment]
I agree that naming is not the best, we are sticking with the terminology that we had with our language clients. We have yet to find a better name for the high level client and indeed, calling the low-level one rest wasn't probably the best choice.

> Eventually these should be rolled into one artifact right?
 
High level one should depend on the low level one. The low level one should be separately distributed. I don't see why people using the low level one, e.g. on java 1.7, should pull in the high level client as well or play with deps exclude and stuff. But please can we have this discussion again in a few  months when we will have something to release? :)

**Pull request closed without merging**
