### PR TITLE
Add bulkScorer to script score query

### LINKED ISSUE #40837: `script_score` query should have a bulk scorer
Some queries return bulk scorers that can be significantly faster than iterating naively over the scorer. By giving `script_score` a BulkScorer that would delegate to the wrapped query, we could make it faster in some cases.

### PR DESCRIPTION
**Pull request by mayya-sharipova**
Some queries return bulk scorers that can be significantly faster than
iterating naively over the scorer. By giving script_score a BulkScorer
that would delegate to the wrapped query, we could make it faster in some cases.

Closes #40837

### CODE REVIEW

**Review by jimczi — APPROVED** [review]
LGTM

**Comment by mayya-sharipova** [comment]
@jimczi I have revived this PR with the new master change.  I think may be it is worth the second review.

**Review by jimczi — APPROVED** [review]
still LGTM

**Comment by mayya-sharipova** [comment]
@elasticmachine run elasticsearch-ci/1

**Pull request merged**
