### PR TITLE
Include create.json rest api spec

### PR DESCRIPTION
**Pull request by russcam**
Backported from 5.0, including version changes to parameters

### CODE REVIEW

**Comment by clintongormley** [comment]
@russcam why do you want to backport this? The behaviour changed in 5.0 to make the ID required, but that's not the case in 2.4

**Comment by russcam** [comment]
@clintongormley ok, I wasn't aware of the id change. 

I backported the methods in the .NET client and saw that the spec for the endpoint was missing in 2.4, hence the PR 😄 In the .NET client, the id is required but if it makes sense to not include the spec because it is not required on the Elasticsearch side, that's not a problem. Alternatively, I can update the PR to make the id optional?

**Comment by russcam** [comment]
further thoughts on backporting this with a change to make the id optional in the 2.x version?

**Comment by javanna** [comment]
I am not sure what value it would add to backport this to 2.4, where we only backport critical fixes at this point. @russcam would it be a problem for the .NET client if we don't do it?

**Comment by russcam** [comment]
@javanna No problem at all; I'll close this.

**Pull request closed without merging**
