### PR TITLE
Mark data streams stats API as internal-only

### PR DESCRIPTION
**Pull request by dakrone**
This commit marks the data stream stats API as internal

### CODE REVIEW

**Comment by dakrone** [comment]
@elasticmachine update branch

**Comment by dakrone** [comment]
@elasticmachine update branch

**Comment by dakrone** [comment]
@elasticmachine update branch

**Review by mattc58 — APPROVED** [review]
+1

**Comment by dakrone** [comment]
As this was reverted, it will be re-added in https://github.com/elastic/elasticsearch/pull/112712

**Pull request merged**
