### PR TITLE
Fix repeated error save loops in File Settings Service

### LINKED ISSUE #90222: [CI] FileSettingsServiceIT testErrorSaved failing
Some more earlier failures with the same issue (all in Windows builds):
https://gradle-enterprise.elastic.co/s/ic3vf76vlpiho
https://gradle-enterprise.elastic.co/s/7nsuvadgg5bbm
https://gradle-enterprise.elastic.co/s/7kcrezoswrgdg

**Build scan:**
https://gradle-enterprise.elastic.co/s/whgmtqrtovpgu/tests/:server:internalClusterTest/org.elasticsearch.reservedstate.service.FileSettingsServiceIT/testErrorSaved

**Reproduction line:**
`gradlew ':server:internalClusterTest' --tests "org.elasticsearch.reservedstate.service.FileSettingsServiceIT.testErrorSaved" -Dtests.seed=762F971779043BEB -Dtests.locale=es-BO -Dtests.timezone=Africa/Luanda -Druntime.java=18`

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.reservedstate.service.FileSettingsServiceIT&tests.test=testErrorSaved

**Failure excerpt:**
```
org.elasticsearch.cluster.metadata.ProcessClusterEventTimeoutException: failed to process cluster event (delete_repository [*]) within 30s

  at __randomizedtesting.SeedInfo.seed([762F971779043BEB:C5DE1806AEE40E21]:0)
  at org.elasticsearch.cluster.service.MasterService$Batcher.lambda$onTimeout$1(MasterService.java:165)
  at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:825)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  at java.lang.Thread.run(Thread.java:833)

```

### PR DESCRIPTION
**Pull request by grcevski**
There were two bugs that were exposed by a recent Windows failures on File Settings:

- When we process an initial settings file which had errors, the reserved metadata version that was saved was 0, which is wrong because we use 0 to mean we need to touch and reset the file from a snapshot restore. The correct default value should be -1, meaning no successful file settings were ever written. Because we used 0, the code that monitors for 0 version was constantly resetting the modified timestamp on the settings file, which caused a flurry of save activity, eventually leading to very rare failure when we time out waiting on the error state to be saved.
- Windows apparently needs write file permission to be able to touch the settings.json file in the operator directory. This means that this functionality never worked correctly in production on Windows. 

Closes https://github.com/elastic/elasticsearch/issues/90222

### CODE REVIEW

**Comment by grcevski** [comment]
I'll follow-up shortly with additional tests that ensure that the metadata version is -1 when only error was ever saved.

**Review by ChrisHegarty — APPROVED** [review]
LGTM

**Comment by grcevski** [comment]
@elasticsearchmachine run elasticsearch-ci/part-1

**Comment by grcevski** [comment]
@elasticsearchmachine run elasticsearch-ci/part-3-windows

**Pull request merged**
