### PR TITLE
Upgrade 6.x to lucene-7.7.0-snapshot-f2f0110b9a

### PR DESCRIPTION
**Pull request by nknize**
With the release of lucene 7.6 this PR updates the 6.x branch to the latest snapshot of Lucene 7.7.

### CODE REVIEW

**Comment by nknize** [comment]
@elasticmachine run gradle build tests 1

**Review by dnhatn — APPROVED** [review]
LGTM.

**Comment by jpountz** [comment]
Maybe we should wait for this one: merging this PR means that we can't release 6.7 until Lucene 7.7 is released and I suspect that the feature freeze for 6.7 might happen before Lucene 7.7 is out, which might put us at risk. Let's revert and be ready to merge it again if Lucene 7.7 is ready on time?

**Comment by nknize** [comment]
Reverted this PR with commit 565c7f7
Also reverted commit b7f6ee72a68324b8fc6b523b1eafb991544d2278 with commit de962b2  
/cc @jpountz @dnhatn

**Pull request merged**
