### PR TITLE
Add refresh policy to logstash plugin write requests

### LINKED ISSUE #62413: [CI] Failure in LogstashSystemIndexIT.testPipelineCRUD
Several reproducible failures on CI: https://groups.google.com/a/elastic.co/g/build-elasticsearch/search?q=testPipelineCRUD

Reproducible failure:
```
./gradlew ':x-pack:plugin:javaRestTest' --tests "org.elasticsearch.xpack.test.rest.LogstashSystemIndexIT.testPipelineCRUD" -Dtests.seed=E7A729884346CF82 -Dtests.security.manager=true -Dtests.locale=ar-JO -Dtests.timezone=America/Winnipeg -Druntime.java=11
```

Stacktrace:
```
11:32:27   2> java.lang.AssertionError: 
11:32:27     Expected: is "{}"
11:32:27          but: was "{\"test_pipeline\":{\"description\":\"test pipeline\",\"last_modified\":\"2020-03-09T15:42:30.229Z\",\"pipeline_metadata\":{\"version\":1,\"type\":\"logstash_pipeline\"},\"username\":\"john.doe\",\"pipeline\":\"\\\"input\\\": {},\\n \\\"filter\\\": {},\\n \\\"output\\\": {}\\n\",\"pipeline_settings\":{\"pipeline.batch.delay\":50,\"pipeline.batch.size\":125,\"pipeline.workers\":1,\"queue.checkpoint.writes\":1024,\"queue.max_bytes\":\"1gb\",\"queue.type\":\"memory\"}}}"
11:32:27         at __randomizedtesting.SeedInfo.seed([E7A729884346CF82:67B3BE1FAC2C7248]:0)
11:32:27         at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
11:32:27         at org.junit.Assert.assertThat(Assert.java:956)
11:32:27         at org.junit.Assert.assertThat(Assert.java:923)
11:32:27         at org.elasticsearch.xpack.test.rest.LogstashSystemIndexIT.testPipelineCRUD(LogstashSystemIndexIT.java:85)
```

### PR DESCRIPTION
**Pull request by williamrandolph**
We have a Logstash system index integration test that creates, updates, and deletes a document. We have been getting a few test failures after the document deletion stage, where we query for the document and get one result rather than none. I hypothesize that for a test like this to pass we need to add an immediate refresh policy to the logstash plugin's write requests.

Fixes #62413

### CODE REVIEW

**Comment by williamrandolph** [comment]
@elasticmachine test this please

**Comment by williamrandolph** [comment]
@elasticmachine please run elasticsearch-ci/packaging-sample-windows

**Review by AthenaEryma — APPROVED** [review]
LGTM - I also ran the test in question 1000 times locally and didn't hit any failures (though I was able to reproduce without the fix), so I'm pretty confident this fixed it.

**Comment by williamrandolph** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample-windows

**Comment by williamrandolph** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by williamrandolph** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by williamrandolph** [comment]
@elasticmachine run elasticsearch-ci/2

**Pull request merged**
