### PR TITLE
upgrade lucene to 9.4.0-snapshot-f5d0646daa5

### PR DESCRIPTION
**Pull request by iverase**
Upgrade lucene to a new snapshot

### CODE REVIEW

**Review by jpountz — APPROVED** [review]

**Comment by iverase** [comment]
@elasticmachine update branch

**Comment by shahzad31** [comment]
Hello team,Will this be backported to 8.5.0 as well? we are facing the issue related in 8.5 SNAPSHOT?

**Comment by liza-mae** [comment]
I am also waiting on this fix for 8.5, it is blocking testing

**Comment by iverase** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by iverase** [comment]
I disable BWC, the new snapshot is incompatible with the previous one so 8.5 is failing.

**Comment by jpountz** [comment]
The disabling of BWC makes sense to me as the new snapshot comes with a new field infos format for the Lucene94Codec whose format is incompatible with the format used by the Lucene snapshot we were using previously: https://github.com/apache/lucene/compare/923a9f800ae..f5d0646daa5#diff-c65e2fa76b7bd59afa8c34b15b7d15551d395260a73b4a4a1d19461796de1cf2.

**Comment by iverase** [comment]
@shahzad31 @liza-mae the snapshot is backported to 8.5

**Pull request merged**
