### PR TITLE
[DOCS] Remove 8.1.0 coming tag

### PR DESCRIPTION
**Pull request by jrodewig**

### CODE REVIEW

**Comment by jrodewig** [comment]
@elasticmachine update branch

**Comment by jrodewig** [comment]
@elasticmachine update branch

**Comment by pugnascotia** [comment]
@jrodewig should we remove the `coming` tag from the templates for the release notes? We seem to remove them pretty frequently.

**Comment by jrodewig** [comment]
> should we remove the coming tag from the templates for the release notes? We seem to remove them pretty frequently.

Hey @pugnascotia — 

We can omit coming tags for major and minor releases, but we need a coming tag for patch releases (like 8.0.1).

To ensure the pages are available for our download pages, we publish our release notes ahead of the actual release. In the case of patch releases, the docs are already "live." The coming tag ensures users aren't confused about what patch version is currently available.

For major and minor releases, the docs aren't "live" until the actual release day. Until then, we show the following admon at the top of each page:

Screen Shot 2022-02-23 at 10 20 34 AM

Right now, we include a coming tag for all releasees (major, minor, patch) to ensure our "human" processes are consistent. The tags don't hurt, and it reduces exceptions, which reduces mistakes/accidents.

Happy to discuss more offline if wanted.

**Review by KOTungseth — APPROVED** [review]

**Pull request merged**
