### PR TITLE
Tests: Add Fedora-27 to packaging tests

### PR DESCRIPTION
**Pull request by dliappis**
Replace Fedora-25 with Fedora-27 in packaging tests
According to the maintenance schedule[1], Fedora-25 will be EOL one month after Fedora-27 is out i.e. on 20171214.

[1] https://fedoraproject.org/wiki/Fedora_Release_Life_Cycle

### CODE REVIEW

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by dakrone** [comment]
I merged this into master to test and it failed for me: http://termbin.com/tuky (many "not ok"s there)

**Comment by jasontedor** [comment]
@dakrone Those failures are completely unrelated to this PR as they are an ongoing issue.

**Review by dakrone — APPROVED** [review]
So they are, thanks for pointing that out @jasontedor, this LGTM, thanks @dliappis

**Comment by dliappis** [comment]
Backported:

6.x -> 8227dba840d787c14ae8afdb122032dd08f12184
6.0 -> c04b1cc8bdd5b0ff64c99e5140f8e7ecd6f39d16
5.6 -> 7482686ba9cd8a82eb43c31f7afc56f478e746d6

**Pull request merged**
