### PR TITLE
Fix/setting deprecation log level correctly

### PR DESCRIPTION
**Pull request by masseyke**
This commit changes the deprecation logger so that all messages (critical or warning) are written out with "299" as
the level at the beginning of the header in order to be compliant with
https://www.rfc-editor.org/rfc/rfc7234.html#section-5.5.7. The deprecation level (CRITICAL or WARNING) is now
written out in the beginning of the message.

### CODE REVIEW

**Comment by jakelandis** [comment]
@masseyke - is it possible to just use the 299 code and ignore the log level in the output of the header for now ?

**Comment by masseyke** [comment]
> @masseyke - is it possible to just use the 299 code and ignore the log level in the output of the header for now ?

@jakelandis I'm not sure I follow -- do you mean don't put any new information in the message (to avoid breaking compatibility tests)? In that case there would be no way to distinguish WARNING from CRITICAL, right?

**Comment by jakelandis** [comment]
> In that case there would be no way to distinguish WARNING from CRITICAL, right?

Correct. I am not sure if there is _need_ to make that distinction from the header. Ideally we would, but if it comes at the cost of a huge change, then I am not sure it worth the effort. The suggest here is to make this PR align us back the HTTP SPEC w.r.t. 299 even if that means that we can not tell the severity from the header and re-visit the severity in the header discussion.  Also, I am assuming that severity in the logs would remains unchanged with this PR. 

If that suggestion causes more work then ignore me.

**Comment by masseyke** [comment]
Closed in favor of #80304

**Pull request closed without merging**
