### PR TITLE
Change severity of negative stats messages from WARN to DEBUG

### PR DESCRIPTION
**Pull request by danhermann**
Because the incidence of negative stats values reported by the JVM has increased significantly as of JDK14 (at least partially due to this JVM bug: https://bugs.openjdk.java.net/browse/JDK-8242480), this message is ending up in logs fairly frequently and causing some concern and confusion among users. The message is largely harmless because the only effect is that the stats value, usually either free memory or free swap space, reported as negative by the OS will instead be recorded as zero by ES and no user action is necessary or possible. Should the JVM bug be fixed in the future, upgrading to an unaffected JVM may reduce the incidence of these occurrences.

### CODE REVIEW

**Comment by danhermann** [comment]
@elasticmachine run elasticsearch-ci/default-distro

**Comment by danhermann** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by danhermann** [comment]
@elasticmachine update branch

**Comment by danhermann** [comment]
@elasticmachine update branch

**Comment by danhermann** [comment]
@elasticmachine update branch

**Review by jbaiera — APPROVED** [review]
LGTM

**Comment by danhermann** [comment]
Thanks, @jbaiera!

**Comment by RickyLau** [comment]
Why is this patch not backported to 6.8

**Comment by lhzw** [comment]
elasticsearch 6.8.18 docker image, on one of my clusters, repeats this again and again, so annoying:
```
root@cluster3:20211109 17:03:11:itp# kubectl logs --tail 20 -f es-2
[2021-11-09T09:00:00,825][WARN ][o.e.m.o.O.Swap           ] [hU4oOeW] cannot compute used swap when total swap is 0 and free swap is 0
[2021-11-09T09:00:10,697][WARN ][o.e.m.o.O.Swap           ] [hU4oOeW] cannot compute used swap when total swap is 0 and free swap is 0
[2021-11-09T09:00:20,671][WARN ][o.e.m.o.O.Swap           ] [hU4oOeW] cannot compute used swap when total swap is 0 and free swap is 0
[2021-11-09T09:00:30,934][WARN ][o.e.m.o.O.Swap           ] [hU4oOeW] cannot compute used swap when total swap is 0 and free swap is 0
[2021-11-09T09:00:40,653][WARN ][o.e.m.o.O.Swap           ] [hU4oOeW] cannot compute used swap when total swap is 0 and free swap is 0
[2021-11-09T09:00:50,677][WARN ][o.e.m.o.O.Swap           ] [hU4oOeW] cannot compute used swap when total swap is 0 and free swap is 0
[2021-11-09T09:01:01,043][WARN ][o.e.m.o.O.Swap           ] [hU4oOeW] cannot compute used swap when total swap is 0 and free swap is 0
[2021-11-09T09:01:10,678][WARN ][o.e.m.o.O.Swap           ] [hU4oOeW] cannot compute used swap when total swap is 0 and free swap is 0
[2021-11-09T09:01:20,669][WARN ][o.e.m.o.O.Swap           ] [hU4oOeW] cannot compute used swap when total swap is 0 and free swap is 0
[2021-11-09T09:01:30,946][WARN ][o.e.m.o.O.Swap           ] [hU4oOeW] cannot compute used swap when total swap is 0 and free swap is 0
[2021-11-09T09:01:40,677][WARN ][o.e.m.o.O.Swap           ] [hU4oOeW] cannot compute used swap when total swap is 0 and free swap is 0
[2021-11-09T09:01:50,682][WARN ][o.e.m.o.O.Swap           ] [hU4oOeW] cannot compute used swap when total swap is 0 and free swap is 0
[2021-11-09T09:02:00,964][WARN ][o.e.m.o.O.Swap           ] [hU4oOeW] cannot compute used swap when total swap is 0 and free swap is 0
[2021-11-09T09:02:10,695][WARN ][o.e.m.o.O.Swap           ] [hU4oOeW] cannot compute used swap when total swap is 0 and free swap is 0
[2021-11-09T09:02:20,673][WARN ][o.e.m.o.O.Swap           ] [hU4oOeW] cannot compute used swap when total swap is 0 and free swap is 0
[2021-11-09T09:02:31,013][WARN ][o.e.m.o.O.Swap           ] [hU4oOeW] cannot compute used swap when total swap is 0 and free swap is 0
[2021-11-09T09:02:40,695][WARN ][o.e.m.o.O.Swap           ] [hU4oOeW] cannot compute used swap when total swap is 0 and free swap is 0
[2021-11-09T09:02:50,737][WARN ][o.e.m.o.O.Swap           ] [hU4oOeW] cannot compute used swap when total swap is 0 and free swap is 0
[2021-11-09T09:03:00,997][WARN ][o.e.m.o.O.Swap           ] [hU4oOeW] cannot compute used swap when total swap is 0 and free swap is 0
[2021-11-09T09:03:10,707][WARN ][o.e.m.o.O.Swap           ] [hU4oOeW] cannot compute used swap when total swap is 0 and free swap is 0
^C                                                                                                                                                  
```

**Comment by dalei2019** [comment]
> [2021-11-09T09:00:10,697][WARN ][o.e.m.o.O.Swap           ] [hU4oOeW] cannot compute used swap when total swap is 0 and free swap is 0

same issue!

**Comment by brianlukoff** [comment]
I'm also seeing this in a 6.8.21 cloud deployment.

**Comment by StijnArnauts** [comment]
We are suffering from this as well on a 6.8 ElasticCloud environment

**Comment by danhermann** [comment]
The 6.8.22 and later releases of Elasticsearch have this change.

**Pull request merged**
