### PR TITLE
SQL: Add alias DATETRUNC to DATE_TRUNC function

### PR DESCRIPTION
**Pull request by matriv**
To be on the safe side in terms of use cases also add the alias
`DATETRUNC` to the `DATE_TRUNC` function.

Follows: #46473

### CODE REVIEW

**Comment by matriv** [comment]
Not sure if it should be an enhancement (added in the release notes) or non-issue.

**Comment by matriv** [comment]
Not sure if it should be marked as enhancement (for release notes) or non-issue.
@costin ?

**Comment by matriv** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by costin** [comment]
You could mark it as a feature since it's a new function.

**Review by costin — APPROVED** [review]
LGTM

**Pull request merged**
