### PR TITLE
Allow custom service names when installing on windows

### LINKED ISSUE #25231: Windows Service installer ignores custom service names
**Elasticsearch version**: 5.4.0

**Plugins installed**:  Default

**JVM version** (`java -version`): 1.8.0_131

**OS version** (`uname -a` if on a Unix-like system): Win Server 2012 R2

**Description of the problem including expected versus actual behavior**:

Before installing elastic search as a service, set the `SERVICE_ID` environment variable to a custom value.  Based on the documentation at https://www.elastic.co/guide/en/elasticsearch/reference/current/windows.html#windows-service-settings, I expect the service to be installed with the name defined in the 

**Steps to reproduce**:

Run the following powershell to install the elastic search service
```ps
$env:SERVICE_ID = 'SomeService'
.\elasticsearch-service.bat install
```

To fix this:
* If it is not intended to allow the service name to be customised, the docs need to be updated
* If it is intended to allow custom service names, update `elasticsearch-service.bat` to not overwrite any existing `SERVICE_ID` value https://github.com/afscrome/elasticsearch/commit/744bd290822a5dd9404fa1e9cbc1c9ffed0cc4c8 .

### PR DESCRIPTION
**Pull request by afscrome**
Fixes #25231.

### CODE REVIEW

**Comment by dakrone** [comment]
@russcam can you take a look at this PR? I think you're most familiar with the Windows service installation (if I am mistaken let me know if there's someone better suited)

**Comment by jasontedor** [comment]
@afscrome Sorry for the delay on someone reviewing this one; there are conflicts with master (from #25435); can you merge master into your branch and resolve the conflict?

**Comment by afscrome** [comment]
@jasontedor done.

**Comment by jasontedor** [comment]
Thanks for the responsiveness. Now that we have a reviewable PR, my first question would be: what's the reason for wanting to customize the service name? I understand that the feature is documented, but it appears that it's never worked and this is the first time that has come up.

**Review by jasontedor — APPROVED** [review]
LGTM.

**Pull request merged**
