### PR TITLE
Fix parameter value for calling data.advanceExact

### PR DESCRIPTION
**Pull request by maarab7**
While the code works perfectly well for a single segment, it returns the wrong values for multiple segments. E.g. If we have 500 docs in one segment and if we want to get the doc id = 280 then data.advanceExact(topDocs.scoreDocs[i].doc) works fine. If we have two segments, say, with first segment having docs 1-200 and the second segment having docs 201-500, then 280 is fetched from the second segment but is actually 480. Subtracting the docBase (280-200) takes us to the correct document which is 80 in the second segment and actually 280.

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by javanna** [comment]
thanks @maarab7 for your contribution! Could you please sign our CLA so we can review it and merge it?

**Comment by maarab7** [comment]
I have already signed it. Is there an approval that happens?

**Comment by javanna** [comment]
heya @maarab7 have you maybe signed the CLA with an email that differs from the one you have on your github profile? That would explain why the check is not green. I can see your signature though.

**Comment by maarab7** [comment]
I don't think I would have used different emails. Cannot verify it though since there is not email on the signature and I've not received any email either. I have the setting 'Keep my email address private' on though. Would that be causing the issue? If not, would you suggest me signing the contract again making sure it is with the same email address as that of github?

**Comment by javanna** [comment]
test this please

**Comment by javanna** [comment]
@elasticmachine update branch

**Comment by javanna** [comment]
retest this please

**Comment by javanna** [comment]
thanks @maarab7 , merged!

**Pull request merged**
