### PR TITLE
[DOCS] Fix typo in CCS security setup docs

### PR DESCRIPTION
**Pull request by law155**
Handles the local cluster section and therefore should be "local cluster".

### CODE REVIEW

**Comment by jrodewig** [comment]
Hi @law155. Thanks for spotting this and opening a PR.

To merge your changes, we require a signed contributor agreement: 
https://www.elastic.co/contributor-agreement

You must sign the agreement with the same email address used in your commit. You can find that email address here:
https://github.com/elastic/elasticsearch/commit/d90a183acd514a3f300c219dd1b60f3ba368ab1c.patch

Once you sign the agreement, I'll get this change merged in. Thanks again!

**Comment by jrodewig** [comment]
@elasticmachine test this please

**Comment by law155** [comment]
Hi @jrodewig,
thanks for your response.
I have signed the agreement with the email adress from the commit.
Greetings

**Review by jrodewig — APPROVED** [review]
LGTM. Thanks again @law155.

**Comment by jrodewig** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------:|
|✅|master|[](https://github.com/elastic/elasticsearch/pull/82426)|
|✅|8.0|[](https://github.com/elastic/elasticsearch/pull/82427)|
|✅|7.17|[](https://github.com/elastic/elasticsearch/pull/82428)|

**Pull request merged**
