### PR TITLE
Make RBACEngine.resolveAuthorizedIndicesFromRole Return Set for Lookups

### PR DESCRIPTION
**Pull request by TommyWind**
The return of this method appears to only be used for `contains` checks.
Doing contains checks on it in a loop in the indices resolution code
seems broken and shows up in profiling for me.
Fixed the index resolve method to return a set for faster look-ups and
also made the method a little more optimal by extracting loop conditions
and avoiding a redundant list creation.

### CODE REVIEW

**Review by danhermann — COMMENTED** [review]
@TommyWind, thank you for submitting this. I can see the O(1) time for `HashSet::contains` over the O(n) time for `List::contains` making a significant difference in a lot of scenarios. I'll need to leave the full review for someone on the @elastic/es-security team, but I do wonder if the return values for these methods should be `HashSet<String>` rather than `Set<String>` since we're now relying on O(1) operation times and there are other Java `Set` implementations with operation times slower than O(1).

**Comment by tvernum** [comment]
Thanks @TommyWind, we have some in progress work to improve the performance on index authorization, but this looks like low hanging fruit so we'll see if we can move on it quickly.

**Comment by tvernum** [comment]
I don't think we should change it to a `HashSet` - that will prevent us from returning `Set.of` or the keyset from a Map.

**Comment by albertzaharovits** [comment]
Overall looks good to me. Thank you @TommyWind !

As Tim says, we're working on this too. My plan is to [replace the `List` here with a `Predicate`](https://github.com/elastic/elasticsearch/pull/72118#issuecomment-826496034), then use the collection of all indices in the cluster filtered by the predicate because the predicate really needs to be evaluated once for every index abstraction name. 

> Doing contains checks on it in a loop in the indices resolution code seems broken and shows up in profiling for me.

To be fair this is not the common code path. Searches and bulk ingests should not trigger the contains check with default request options.
I think it's much more common to replace the wildcards with the elements of the List/Set. In this case, theoretically, a list is preferable because it is slightly faster to build and iterate for all elements. But, in practice, we actually build a set that we then copy into a list. For this reason, I think the code in this PR is superior in every regard to what we currently have, hence my vote to merge without doing benchmarks.

WDYT @tvernum

**Review by albertzaharovits — APPROVED** [review]

**Review by tvernum — APPROVED** [review]
LGTM

**Comment by tvernum** [comment]
@elasticmachine ok to test

**Comment by tvernum** [comment]
Thanks @TommyWind.

**Pull request merged**
