### PR TITLE
Wrap rest httpclient with doPrivileged blocks

### PR DESCRIPTION
**Pull request by Tim-Brooks**
This is related to #22116. A number of modules (reindex, etc) use the 
rest client. The rest client opens connections using the apache http 
client. To avoid throwing `SecurityException` when using the 
`SecurityManager` these operations must be privileged. This is tricky 
because connections are opened within the httpclient code on its 
reactor thread. The way I confronted this was to wrap the creation 
of the client (and creation of reactor thread) in a `doPrivileged` 
block. The new thread inherits the existing security context.

### CODE REVIEW

**Comment by s1monw** [comment]
the change looks good but where do we grant the permission to this client? is this coming in a different PR?

**Comment by tbrooks8** [comment]
This client is a dependency of the reindex module. So when I modifying the policy files to officially move connect out of core, reindex will get connect. And rest needs to have the doPrivileged block for that.

**Comment by s1monw** [comment]
> This client is a dependency of the reindex module. So when I modifying the policy files to officially move connect out of core, reindex will get connect. And rest needs to have the doPrivileged block for that.

fair enough, so nothing else does a connect in the client? are all connections established once the client is created?

**Comment by tbrooks8** [comment]
So I have not found any other place where connections occur in the rest client. Even when you call the "synchronous" request API it is still using the async API (reactor thread) and you are [just blocking on the future](https://github.com/elastic/elasticsearch/blob/master/client/rest/src/main/java/org/elasticsearch/client/RestClient.java#L212).

 But my change here was mostly influenced by how the reindex module was using the client. Other modules (test framework, x-pack) may have different needs. So I'll take a closer look at the client today and see if I am missing anything.

**Comment by javanna** [comment]
@tbrooks8 that sounds about right I don't think you are missing anything.

**Review by s1monw — APPROVED** [review]

**Comment by s1monw** [comment]
@tbrooks8 wanna pulls this in?

**Comment by tbrooks8** [comment]
Yep. I merged it.

**Pull request merged**
