### PR TITLE
[DOCS]  date math support in aliases

### PR DESCRIPTION
**Pull request by Tommmster**
Adds examples for date math support in aliases
https://github.com/elastic/elasticsearch/pull/67226

### CODE REVIEW

**Comment by martijnvg** [comment]
@elasticmachine test this please

**Comment by martijnvg** [comment]
Thanks @Tommmster!

@jrodewig Do you think this is the right place in the docs to highlight date math in aliases?

**Comment by jrodewig** [comment]
Thanks for raising this @Tommmster. I pushed 5a996f5632d5d1a4002b6a0f9f65e59f23e8d453 to document date math support in a few different areas.

@martijnvg Do you mind taking a look at the new changes? If everything looks alright, I'll get this merged and backported.

Thanks again, @Tommmster!

**Comment by jrodewig** [comment]
@elasticmachine ok to test

**Review by martijnvg — APPROVED** [review]
LGTM

**Pull request merged**
