### PR TITLE
Restructure Aggregation documentation

### PR DESCRIPTION
**Pull request by polyfractal**
First pass at cleaning up the Aggregation documentation.
- Moved Aggregations out of Search and put it as a "top-level" chapter
- De-floated Buckets / Metrics / Reducers in the Aggregations section and made them real sections. 
- Moved individual buckets / metrics / reducers under their appropriate section
- Alphabetized everything emot-toot
- Moved miscellaneous agg topics (caching, metadata, etc) to the end of the chapter
- Centralized some reducer content (`buckets_path` syntax, `_count`, `gap_policy`)
- Standardized the reducers a bit by adding a "agg in isolation" snippet, and a "parameters" table.  This wasn't strictly necessary, but I really think all our APIs should have a parameters table :)

Still more that _should_ be done (e.g. I think the Agg chapter intro is still too long / wordy / technical), but we can tackle content stuff later.

/cc @colings86 @jpountz @clintongormley

### CODE REVIEW

**Comment by dadoonet** [comment]
Hey Zach. When I wrote java-api doc about aggs, I tried to use the same naming as we have in reference doc. Do you think you can also update [java-api doc](https://github.com/elastic/elasticsearch/tree/master/docs/java-api/aggregations) within the same PR?

**Comment by clintongormley** [comment]
Big improvement!  

Not in your PR, but the Controlling Diversity header under the Sample agg should be moved down one level.  

@dadoonet I don't understand your question - the naming hasn't changed, and the html links should still be the same?

**Comment by dadoonet** [comment]
@clintongormley reading the change again, I would now say "ignore me!" :)
I thought we were changing dir names but I was wrong.

Sorry for the noise.

**Comment by polyfractal** [comment]
@clintongormley Sampler agg docs update.

**Comment by clintongormley** [comment]
LGTM

**Pull request merged**
