### PR TITLE
Reenable shard management on IndicesClusterStateService

### PR DESCRIPTION
**Pull request by ywelsch**
The previous commit d8b73e9 changed IndicesClusterStateService and IndicesStore to only run on master and data nodes. IndicesClusterStateService triggers acknowledgments of index deletes to the master. The current code that is waiting for the acknowledgments on the master is however expecting acknowledgements from tribe/client nodes as well. This commit reenables IndicesClusterStateService to run on tribe/client nodes to provide simple backward compatibility (but keeps IndicesStore disabled on tribe/client nodes). This is not an issue in the original patch on v5.x where acknowledgement of index deletes is done through the cluster state acking mechanism.

### CODE REVIEW

**Comment by bleskes** [comment]
LGTM. 

For completion - here is an example failure: https://elasticsearch-ci.elastic.co/view/All/job/elastic+elasticsearch+2.4+periodic/179/console

**Review by bleskes — APPROVED** [review]

**Comment by ywelsch** [comment]
@bleskes I've reworked the PR to re-enable shard management on IndicesClusterStateService for tribe/client nodes so that it properly accounts for the acking of index deletes. I've looked at all the methods that are called by IndicesClusterStateService, and all of them except one boil down to NOOPs on tribe/client nodes: Deleting closed indices. I've added an extra commit to account for this.

**Comment by bleskes** [comment]
LGTM with the updates too. We also decided to benchmark this to double check

**Comment by ywelsch** [comment]
Thanks @bleskes!

**Pull request merged**
