### PR TITLE
Fix a test failure in CompositeRolesStoreTests

### PR DESCRIPTION
**Pull request by bizybot**
Due to missing stubbing for `NativePrivilegeStore#getPrivileges`
the test `testNegativeLookupsAreCached` failed
when the superuser role name was present in the role names.
This commit adds missing stubbing.

Closes: #37657

### CODE REVIEW

**Review by albertzaharovits — APPROVED** [review]
LGTM

**Comment by albertzaharovits** [comment]
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-2/5221/console
> 17:12:14 > Task :x-pack:plugin:core:unitTest FAILED
17:12:14 Tests with failures:
17:12:14   - org.elasticsearch.xpack.core.security.action.role.PutRoleRequestTests.testSerializationBetweenV63AndV70

run gradle build tests 1

**Comment by albertzaharovits** [comment]
run gradle build tests 2

**Review by jkakavas — APPROVED** [review]
LGTM

**Pull request merged**
