### PR TITLE
Fix indices resolver for datemath with colon 

### LINKED ISSUE #92892: DateMath breaks with pipe character (security vs. security-disabled)
### Elasticsearch Version

8.6.0

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Docker

### Problem Description

When testing datemath with complex date strings, I found that some worked and some didn't. I narrowed it down to the existence of the `|` pipe character in the string.

@dakrone seems to think this may be due to how the `IndexNameExpressionResolver` works differently for security-enabled vs. non-security-enabled clusters.

## Security Disabled Cluster
```
curl -XGET 'http://localhost:9200/%3Cdatemath-%7B2001-01-01-13%7C%7C%2B1h%2Fh%7Byyyy-MM-dd-HH%7C-07%3A00%7D%7D%3E'
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Cross-cluster calls are not supported in this context but remote indices were requested: [<datemath-{2001-01-01-13||+1h/h{yyyy-MM-dd-HH|-07:00}}>]"}],"type":"illegal_argument_exception","reason":"Cross-cluster calls are not supported in this context but remote indices were requested: [<datemath-{2001-01-01-13||+1h/h{yyyy-MM-dd-HH|-07:00}}>]"},"status":400}%
```

## Security Enabled Cluster

```
curl -XGET -u sample -p 'https://secure.cluster.io/%3Cdatemath-%7B2001-01-01-13%7C%7C%2B1h%2Fh%7Byyyy-MM-dd-HH%7C-07%3A00%7D%7D%3E'
Enter host password for user 'sample':
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [datemath-2001-01-01-14]","index_uuid":"_na_","index":"datemath-2001-01-01-14"}],"type":"index_not_found_exception","reason":"no such index [datemath-2001-01-01-14]","index_uuid":"_na_","index":"datemath-2001-01-01-14"},"status":404}%
```

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by albertzaharovits**
When resolving concrete indices from expressions, we check that
`ignore_unavailable` is `true` if the expression contains remote names.
The issue is that remote names are recognized when the expression
contains a colon `:`, and that some datemaths can also contain a colon.

The fix here is to run the `ignore_unavailable` check after the
datemath has been evaluated.

Fixes: https://github.com/elastic/elasticsearch/issues/92892

### CODE REVIEW

**Comment by albertzaharovits** [comment]
Actually, after some further thought, I would like to double check if it can be fixed without moving the `ensureRemoteIndicesRequireIgnoreUnavailable` inside the `resolveExpression` method that's called from multiple places, not only the `concreteIndices` method...
I will take back the review request and add it back when I'm ready.
Sorry for the noise.

**Comment by grcevski** [comment]
Happy to review, just let me know when it's ready.

**Comment by albertzaharovits** [comment]
Okay, I now think it's fine to move `ensureRemoteIndicesRequireIgnoreUnavailable` inside the `ExplicitResourceNameFilter`, per the original intent.

The reason is that, without the `ensureRemoteIndicesRequireIgnoreUnavailable` guard, `ExplicitResourceNameFilter#ensureAliasOrIndexExists` will throw "not found" exceptions for remote names (because names with `:` never exist locally).
Therefore, the `ensureRemoteIndicesRequireIgnoreUnavailable` check, which prevents that and which throws a different exception, should run every time before the `ExplicitResourceNameFilter#ensureAliasOrIndexExists` runs. Running it only in the context of "concrete indices" is actually a problem because we assume that remote names are not possible in the other contexts or that the "not found" exception for remote names is OK in those other contexts, which doesn't sound correct to me.

**Comment by albertzaharovits** [comment]
@grcevski this is ready for your attention. I hope my reasoning in https://github.com/elastic/elasticsearch/pull/92973#issuecomment-1385541663 makes sense.

**Review by grcevski — APPROVED** [review]
LGTM!

**Comment by albertzaharovits** [comment]
@elasticmachine update branch

**Comment by albertzaharovits** [comment]
@elasticmachine update branch

**Pull request merged**
