### PR TITLE
Add repository metadata integrity check API

### PR DESCRIPTION
**Pull request by DaveCTurner**
Relates #52622

### CODE REVIEW

**Comment by DaveCTurner** [comment]
Replaces https://github.com/elastic/elasticsearch/pull/92373. This is still WIP, in particular more tests are needed and the output needs to go to a datastream managed with an `IndexTemplateRegistry`, but I don't think there will be too many more fundamental changes.

**Comment by DaveCTurner** [comment]
@sang-elastic please leave this open as a draft, we're still working on it.

**Comment by sang-elastic** [comment]
@DaveCTurner  Sorry. will leave it as it is.

**Comment by DaveCTurner** [comment]
Closing in favour of https://github.com/elastic/elasticsearch/pull/112348.

**Pull request closed without merging**
