### PR TITLE
Index "creation_date" not accurate when created with settings from another index

### PR DESCRIPTION
**Pull request by HarishAtGitHub**
issue_topic - Index "creation_date" not accurate when created with settings from another index
issue_id - 12790
issue_url - https://github.com/elastic/elasticsearch/issues/12790
# PROBLEM STATEMENT:

Create Index operation API is capable of taking the settings as input
and create an index. The problem is that it is also using the
input creation_date and creating new index with same date
# APPROACH:

Find where it accepts the creating_date from the request object and
change it so that it is always generated at the time of index creation.
(it should effectively behave like uuid)
# Files Changed:

```
    modified:   core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataCreateIndexService.java
modified:   core/src/test/java/org/elasticsearch/action/admin/indices/create/CreateIndexIT.java
```

> modified:   core/src/main/java/org/elasticsearch/cluster/metadata/MetaDataCreateIndexService.java

Here the part where it looks for creation_date from request object is removed.

> modified:   core/src/test/java/org/elasticsearch/action/admin/indices/create/CreateIndexIT.java

Removed test case that tests that the date given in settings is same as the creation_date of the
newly created index.
# RESULT AFTER THE CHANGE:

input settings

``` javascript
{
     'settings':
          {  'index':
                       {'number_of_replicas': '1',
                         'version': {'created': '2000010'},
                         'creation_date': '1439384094544'
                         'uuid': 'ayzHgwB3Sgey-Pk_Okgwyg',
                         'number_of_shards': '5',
                       }
          }
}
```

new index settings

``` javascript
{
    'settings':
          {'index':
                     {'number_of_replicas': '1',
                      'version': {'created': '2000010'},
                      'creation_date': '1439456346424',
                      'uuid': 'fddpIVxNTTKPzqDakLAL4A',
                      'number_of_shards': '5'
                     }
         }
}
```

Please give feedback.
# Test case to check result

https://github.com/HarishAtGitHub/elasticsearch-tester/blob/master/12790.py

### CODE REVIEW

**Comment by HarishAtGitHub** [comment]
pull request for the date replication reported in https://github.com/elastic/elasticsearch/issues/12790.

**Comment by HarishAtGitHub** [comment]
I have just commented out the if loop as so that this change can be easily tracked in case it results in some other bug .

**Comment by HarishAtGitHub** [comment]
In the changes made to fix the version.created problem , I went with the "filtering params" in the starting place though this would not be ideal in most of the cases. But in our case I thought it might fit because  fixing in the MetaDataCreateIndexService might not be appropriate because at this point we will not know who set the settings "is he the user" or "from internal code" ... our aim is to block external users and not internal usage. so the logic would be to filter it at the doorsteps.

But this too has a drawback. the drawback is we should find all the possible doors through which users can enter the MetaDataCreateIndexService . one is the fixed one in CreateIndexRequest which is used by RestCreateIndexAction .
Are there any other routes through which users can set settings in CreateIndexRequest and feed it to MetaDataCreateIndexService ? Is CreateIndexRequestBuilder as possible route ?

I am worried about this CreateIndexRequestBuilder which allows a method to

**Comment by s1monw** [comment]
there are more problems like this, you can also fake the `index.version.created` etc. yet, I think we need this ability in our tests so I guess there should be a way to by-pass this by the test infrastructure. I think it would make sense to have some switch on `MetaDataCreateIndexService` to allow overriding these? 
The two I think of are:

* `index.creation_date` 
* `index.version.created`


I can take care of this if you want but I wanted to give you a heads-up first

**Comment by HarishAtGitHub** [comment]
sorry for the delay @s1monw .... I did not notice that you reviewed (pls add the review tag if possible in the issue, I was waiting for review but left it as as there was no tag) ....
I will work on it today(one more day) .... If I cannot find a way out in 1 day I will let you know ....

**Comment by HarishAtGitHub** [comment]
Hi @s1monw, I cannot think of a good acceptable solution for this problem now. Ya may be you are someone else can take it up ... I can look into some other issue ...

**Comment by rjernst** [comment]
I'm going to work on this soon.

**Pull request closed without merging**
