### PR TITLE
Disallow defining the same field twice in a single mapping call.

### PR DESCRIPTION
**Pull request by zacharymorn**
Closes Issue #37437

### CODE REVIEW

**Review by jtibshirani — COMMENTED** [review]
@zacharymorn thanks again for the fix, and for bearing with us as we sort out some details.

As a general comment, I don't think that `CreateIndexRequest` is the right place to make a fix. We want to check mapping definitions however they're supplied -- whether it's through index creation or mapping updates. So it'd be better to make the fix at a lower level. A good place to start would be to look at how object mappers are built (`ObjectMapper#build`), as this is where different mappings with the same key are merged together.

**Comment by zacharymorn** [comment]
@jtibshirani Thanks for the update! Yes after posting my comment on the issue I also realized the changes in this PR are not sufficient, but have been waiting for more update about the approach we would like to take.

I took a look at your latest comment on the discussion result and it makes sense. Quick question though. I don't seems to be able to find the method you mentioned above `org.elasticsearch.index.mapper.ObjectMapper#build`. Are you referring to some other method within that class, or some other class altogether?

On the other hand, I noticed that in `DocumentMapperParser#parse`, there are some mapping validation logic as well (and tested via `CreateIndexIT#testMappingParamAndNestedMismatch`, and this method seems to be on the code path for both CreateIndex and PutMapping operations . Would this be a good place to put the checking logic as well?

**Comment by jtibshirani** [comment]
My mistake, I meant `ObjectMapper.Builder#build`. And yes, you could take a look at `DocumentMapperParser#parse` and trace the logic down from there -- this is a higher-level method that drives the mapping parsing process.

**Comment by zacharymorn** [comment]
@jtibshirani I took a further look. It appears to me that `ObjectMapper` is used for parsing all object declarations in XContent, and the same goes for `DocumentMapper`. Disallowing nested field seems to be a feature / bug fix that should only apply to index creation / update, and hence putting the check in mapper may have larger blast radius. Namely, by doing that we may also disallow nested declarations in other APIs that use object. What do you think?

**Comment by jimczi** [comment]
@jtibshirani can you update the status of this PR ? Is it still relevant ?

**Comment by jtibshirani** [comment]
In retrospect I shouldn't have marked the issue 'help wanted'. From my research the fix may be complex, and we should think through how the it fits with new efforts like runtime fields and supporting dots in field names. We didn't get very far with this PR, I plan to close it and remove the 'help wanted' label. I'm sorry @zacharymorn for the trouble.

**Pull request closed without merging**
