### PR TITLE
Core: Rework epoch time parsing for java time

### PR DESCRIPTION
**Pull request by rjernst**
This commit converts the epoch time parsing implementation which uses
the java time api to create DateTimeFormatters instead of DateFormatter
implementations. This will allow multi formats for java time to be
implemented in a single DateTimeFormatter in a future change.

### CODE REVIEW

**Review by spinscale — APPROVED** [review]
LGTM in general, I am not sure about the test case failure yet.

I could not reproduce the test failure in my IDE using just java11, but only via gradle / maybe there is some bwc issue with older java versions...

**Comment by rjernst** [comment]
I tracked the failure down to a bug in java 8 (the test passes in java 11). According to the javadocs of DateTimeFormatterBuilder, optional sections should only be output when formatting if they are supported. When using our custom TemporalField in java 8, the isSupportedBy never gets called on our nanos field, it is simply retrieved and always output.

I can think about how to workaround this, but I believe it will be difficult and require a change higher up to detect this and choose a different formatter to use. Given that this is fixed in java 11, I am inclined to say this is simply a known issue and amend the test to handle it. @spinscale thoughts?

**Comment by spinscale** [comment]
I created a super small benchmark, which basically uses the date formatter `"year_month_day||ordinal_date||epoch_millis"` and then converts a simple number so that only the last formatter matches

results in the java-time branch (which does not differ too much from master right now in that regard)

```
Benchmark                             Mode  Cnt      Score     Error  Units
DateFormatterBenchmark.parseJavaDate  avgt   30  11586,309 ± 347,316  ns/op
DateFormatterBenchmark.parseJodaDate  avgt   30   1105,384 ±  24,877  ns/op
```

results with this PR

```
Benchmark                             Mode  Cnt     Score    Error  Units
DateFormatterBenchmark.parseJavaDate  avgt   30  1104,080 ± 14,440  ns/op
DateFormatterBenchmark.parseJodaDate  avgt   30  1117,427 ± 21,235  ns/op
```

**Comment by rjernst** [comment]
@elasticmachine run gradle build tests 1

**Pull request merged**
