### PR TITLE
Fix Vector tiles search docs for features.id

### PR DESCRIPTION
**Pull request by iverase**
Vector tiles search documentation claims that the final vector tiles contains for each feature and identifier as an integer in the form of `feature.id`. This is part of the standard and those ids are numeric.

Elasticsearch document ids are not numeric but strings and therefore we are not using the ids from the standards but adding ES ids as a properties of the feature. In the case of the hits layer, each feature contains an `_id` property and for the aggs layer, each feature contains a `_key` property. 

This PR removes the reference to the integer identifier from the docs.

https://elasticsearch_85067.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/search-vector-tile-api.html

### CODE REVIEW

**Review by jrodewig — APPROVED** [review]
LGTM. Thanks for correcting this.

**Review by nreese — APPROVED** [review]
LGTM

**Comment by jrodewig** [comment]
I'll go ahead and merge + backport this. Thanks again @iverase!

**Comment by jrodewig** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.1|[](https://github.com/elastic/elasticsearch/pull/85076)|
|✅|8.0|[](https://github.com/elastic/elasticsearch/pull/85077)|
|✅|7.17|[](https://github.com/elastic/elasticsearch/pull/85078)|
|✅|7.16|[](https://github.com/elastic/elasticsearch/pull/85079)|
|✅|7.15|[](https://github.com/elastic/elasticsearch/pull/85080)|


### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
