### PR TITLE
[ML] adjust change_point to not throw with too few buckets

### PR DESCRIPTION
**Pull request by benwtrent**
It can be frustrating for agg consumers to handle failure modes when we should just indicate that there were too few buckets to calculate the change.

Other aggs simply return NaN or empty results when too few docs are calculated. We should follow suit for continuity of experience.

### CODE REVIEW

**Comment by benwtrent** [comment]
https://github.com/elastic/elasticsearch/pull/87297

**Review by przemekwitek — APPROVED** [review]
LGTM

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Comment by benwtrent** [comment]
run elasticsearch-ci/part-2

**Pull request merged**
