### PR TITLE
Update search-template.asciidoc

### PR DESCRIPTION
**Pull request by Iswaryar**
Felt the documentation for the conditional clauses was not clear and invited questions like http://stackoverflow.com/questions/26606853/elasticsearch-search-templates. I had answered the question in stackoverflow. Also thought it is appropriate to propose improvisation of the documentation.

### CODE REVIEW

**Comment by clintongormley** [comment]
Hi @Iswaryar 

Thanks for the PR.  Please could I ask you to sign the CLA?
http://www.elasticsearch.org/contributor-agreement/

**Comment by Iswaryar** [comment]
done

**Comment by clintongormley** [comment]
Hi @Iswaryar 

I've had a look at the changes and I think they introduce more confusion, by adding too many examples, and in the wrong place.  Let's rethink this.  

What parts did you find confusing?  If we start there, then finding the right solution will be easier.

**Comment by Iswaryar** [comment]
It is mentioned that "the template should either be stored in a file or, when used via the REST API, should be written as a string". And the way to execute the stored template is also given. But it is not mentioned that only the
 {
    "query":{ whatever query }
}
part should be places in the file in config>scripts with .mustache extension.
I din't find it straight forward. Also seeing the question on stackexchange, I knew I was not alone. Also when using the registered template, we use the "id". For the ones stored in the file, we use just the template property.

**Comment by clintongormley** [comment]
Hi @Iswaryar 

Sorry it has taken a while to get back to this.  I've taken another look and still feel that the existing docs are clearer than the proposed changes, so I'm going to close this PR.

thanks anyway

**Pull request closed without merging**
