### PR TITLE
#28692 Added reporting of snapshot status PARTIAL on _status endpoint

### PR DESCRIPTION
**Pull request by redbearsam**
Title says it all.

### CODE REVIEW

**Comment by karmi** [comment]
Hi @redbearsam, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/elasticsearch/pull/28801.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by redbearsam** [comment]
Right thanks @karmi . Right you are. Should be solved now I'd say.

**Comment by tlrx** [comment]
@elasticmachine test this please

**Comment by tlrx** [comment]
@redbearsam Thanks for your contribution, but it does not compile. Also, did you execute the test suite? I'm surprised because I'd expect the tests to be adapted.

**Comment by redbearsam** [comment]
Hi @tlrx , apologies on the big old delay here. Definitely compiling now. I am however having trouble making the trunk pass the entire test suite on my (windows) machines, never mind my own branch. It's a variety of tests failing rather than a single one failing consistently. I shall continue to investigate, but I wonder if it's to do with my ageing hardware or some other anomaly.

**Comment by tlrx** [comment]
@redbearsam Thanks! Yeah, passing all the tests can take some time (specially on Windows). 

The change you made is the first step: it correctly reports partial snapshots as PARTIAL but we must now add backward compatibility tests for this change, because in mixed version cluster one node can have your change while the other does not understand yet what PARTIAL(7) is.

Are you interested in pursuing the required changes? You can expect a bit more work to do and I can help. If you don't want/don't have time then I can pick up your commit and complete the pull request by myself.

**Comment by redbearsam** [comment]
@tlrx Hey there. Yeah, I should have considered that aspect of the change. I'll have a stab at getting backwards compatibility working myself, and implementing tests to demonstrate that. I'll keep this page updated as my efforts continue. Thanks.

**Comment by tlrx** [comment]
@redbearsam That's awesome! Please ping me, I'm here to help.

**Comment by michaelbaamonde** [comment]
@redbearsam Are you still interested in moving this forward? Thanks!

**Comment by original-brownbear** [comment]
Closing here due to inactivity.

**Pull request closed without merging**
