### PR TITLE
Fix edge cases in CompositeKeyExtractorTests

### LINKED ISSUE #30156: CompositeKeyExtractorTest.testExtractDate fails
Test reproducibly fails on elasticsearch 6.3, 6.x, and master on my local Mac laptop:

Last CLI failure on 

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.3+multijob-unix-compatibility/os=fedora/3/console

Reproduce: 
./gradlew :x-pack:plugin:sql:test   -Dtests.seed=56E62F320F1CC3E3   -Dtests.class=org.elasticsearch.xpack.sql.execution.search.extractor.CompositeKeyExtractorTests   -Dtests.method="testExtractDate"   -Dtests.security.manager=true   -Dtests.locale=he   -Dtests.timezone=Atlantic/Faeroe

with an error message:
```
17:16:06 ERROR   0.06s J2 | CompositeKeyExtractorTests.testExtractDate <<< FAILURES!
17:16:06    > Throwable #1: java.lang.IllegalArgumentException: The datetime zone id 'SystemV/YST9' is not recognised
...
17:16:06    > 	at org.joda.time.DateTimeZone.forTimeZone(DateTimeZone.java:380)
17:16:06    > 	at org.elasticsearch.xpack.sql.execution.search.extractor.CompositeKeyExtractorTests.testExtractDate(CompositeKeyExtractorTests.java:65)
```

Or another time zone reproduction line:

/gradlew :x-pack:plugin:sql:test -Dtests.seed=A303E5CA896B87E9 -Dtests.class=org.elasticsearch.xpack.sql.execution.search.extractor.CompositeKeyExtractorTests -Dtests.method="testExtractDate" -Dtests.security.manager=true -Dtests.locale=id-ID -Dtests.timezone=Asia/Dhaka

with an error:
Throwable #1: java.lang.IllegalArgumentException: The datetime zone id 'SystemV/AST4' is not recognised

### PR DESCRIPTION
**Pull request by cbuescher**
Currently the test picks random java.util.TimeZone ids in some places.
Internally we still need to convert back to joda DateTimeZone by id
occassionally (e.g. when serializing to pre 6.3 versions). There are
some deprecated "SystemV/*" time zones that Jodas DateTimeZone refuses
to convert. This change excludes those rare cases from the set of
allowed random time zones. It would be quiet odd for them to appear in
practice.

Closes #30156

### CODE REVIEW

**Comment by cbuescher** [comment]
@dakrone could you take a look please since you seem to have moved the class to java.util.TimeZone.

**Review by dakrone — APPROVED** [review]
LGTM

**Comment by cbuescher** [comment]
@costin the issue mentions this test failing on 6.3 as well. Should the fix also be backported there or did you remove the 6.3 label for a specific reason?

**Comment by costin** [comment]
@cbuescher it should be ported to 6.3 - I'll take care of it. The label was removed by mistake because the BC was cut, once I'll commit I'll add 6.3.1 to it.

**Comment by costin** [comment]
Backported to 6.3 through 982f7d70aa059e7dde6432482e6a3085df52a79f

Thanks again for looking into this!

**Pull request merged**
