### PR TITLE
Allow regexes to be specified as part of rest paths, limiting when handlers are called

### LINKED ISSUE #107425: RestGetIndicesAction matches REST queries that start with _ even when no indicies can ever match that
This came out as an issue due to #106820

All REST API calls that start with `_` match `RestGetIndicesAction` due to the generic catch-all route `/{index}`, even though no index can ever start with `_`. This messes up capability checks on invalid APIs, returning `true` (as it matched a handler) even though that can't ever work. This also causes some odd behaviour with other APIs, with `POST /_typo` returning 405 rather than 404, as it matches `/{index}` even though it could never work.

We should limit wildcards to not match `_`. There are various levels we could do this at.

### PR DESCRIPTION
**Pull request by thecoop**
Add regex support to `PathTrie`. Regexes can be specified as part of a wildcard using syntax `{<regex>|<wildcard>}`. They can only be set once on any path (the same way wildcards themselves work), and once set apply to all uses of that wildcard.

This is part of work for #107425

### CODE REVIEW

**Comment by mosche** [comment]
I like this @thecoop 
Though, I'd propose to change `{<regex>|<wildcard>}` to something that allows us to detect the regex use case more efficiently, e.g. `{[<regex>]<wildcard>}` or similar. Basically rather than searching for `|` all the time, something that allows us to skip if `charAt(1)` doesn't match the expectation.

**Comment by thecoop** [comment]
Ah yes, `|` could be in the regex itself. It could search for the last instance of `|`? Or use another separator, maybe `:`?

**Comment by mosche** [comment]
Searching for the last instance of '|' would certainly work 👍 
Though, it would be great to check if a node contains no regex instantly rather than searching for a separator. We still have to split regex and name in the other case, but most of the time we don't. That's why I suggested wrapping the regex into 2 distinct chars - whatever that is, e.g. `"{[<regex>]<wildcard>}".charAt(1) == '['`

**Comment by thecoop** [comment]
Wilcards are quite short, and this is only done on init. The strings have to be read for putting in the hashmap anyway, so I don't think performance is a big issue here...

**Review by mosche — APPROVED** [review]
LGTM given all tests succeed 🎉

**Comment by thecoop** [comment]
I've tried applying this regex in https://github.com/elastic/elasticsearch/pull/107705. One of the issues is that the regex applies to all methods, not just GET or POST, which means that the regex definition needs to encompass all uses of that wildcard, not just in the single handler its declared. This is a significant information leak...

**Comment by rjernst** [comment]
I'm uneasy about allowing any regex. Since we only care about whether or not a leading underscore is allowed, could we do this with a different wrapper? Eg right now we have `{index}`, could we use something like `[index]` to mean a value with non-leading underscore? Internally it could still use a regex, but as far as specification in the path it wouldn't have a general purpose regex.

**Comment by thecoop** [comment]
Even that wouldn't work here, because `{index}` handlers also need to match `_all` - see https://github.com/elastic/elasticsearch/blob/825d9c4828cdcb3c292051cd64108797f2971d3c/server/src/main/java/org/elasticsearch/rest/action/admin/indices/RestGetIndicesAction.java#L49

**Comment by rjernst** [comment]
> because {index} handlers also need to match _all

Could that be handled by duplicating the routes, so that `/_all` is explicitly handled? It can still be the same RestHandler instance, just  separating the variable index name path (which doesn't allow a leading underscore) from the special `_all` case.

**Comment by thecoop** [comment]
We could go further - change all `{{ }}` wildcards to not accept paths starting with `_`, and then for those that do need `_` we can use syntax like `{{_param}}` or `_{{param}}` to additionally accept params starting with `_` for the same handler

**Comment by rjernst** [comment]
I like that idea, especially if we can make `_{{param}}` work.

**Comment by thecoop** [comment]
Yet again, I am thwarted by the design of PathTrie. It's difficult to have multiple wildcard paths, as everything is shared with nodes further up the trie.

The most recent solution I've come up with is the following:

* By default, `{param}` does not match anything that starts with _
* You can add a list of fixed strings after the param for additional tokens the param will match, for example `{index|_all}`, or `/_nodes/{nodeId|_all|_local|_master}`

This would only need to be specified once, for it to apply to all handlers using that same param in the same place.

**Comment by thecoop** [comment]
I've started this work in https://github.com/elastic/elasticsearch/pull/108188, but there are a **lot** of handlers with params that explicitly or implicitly accept `_all`. I might need to special-case that as accepted by all params

**Comment by thecoop** [comment]
This isn't going to work - we need a re-think

**Pull request closed without merging**
