### PR TITLE
Document REST layer in architecture guide

### PR DESCRIPTION
**Pull request by DiannaHohensee**
This is meant to document the topic of "Rest and Transport Layer" during onboarding.

### CODE REVIEW

**Review by DaveCTurner — COMMENTED** [review]
Looks good. A few other things that might be worth mentioning:

- the `Rest*Action` naming convention is just a convention, not enforced, but still a useful convention to follow.
- `BaseRestHandler#prepareRequest` is there mainly to consume the request parameters - any parameters in the request which aren't consumed during `prepareRequest()` will result in a `400 Bad Request` (and other exceptions thrown here are also passed straight back to the caller).
- The `NodeClient` knows about actions registered via `org.elasticsearch.action.ActionModule#setupActions`; in contrast the `TransportService` knows about actions registered via `TransportService#registerRequestHandler`. Some actions are registered in both places, but definitely not all of them.
- Executing a `TransportAction` (either locally via `NodeClient` or remotely via `TransportService`) is where most of the authorization & other security logic runs.

**Comment by DiannaHohensee** [comment]
> Some actions are registered in both places, but definitely not all of them.

Huh, that sounds interesting. I got as far as `ActionModule#setupActions` going through the plugins and calling `Plugin#getActions()`. It looks like it's pulling into all the actions that plugins define. But, as you say, that doesn't mean we're declaring all the transport actions that call into `TransportService#registerRequestHandler`. I wonder under what circumstances, but haven't explored.

**Comment by DiannaHohensee** [comment]
Thank you for the suggestions. I've incorporated the first two bullets, and half of the third. The rest veer into the Transport layer, which I'm avoiding in this PR, but I've added your points in the transport sections for later elaboration.

Let me know if anything is difficult to follow or missing 👍

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Pull request merged**
