### PR TITLE
update AWS SDK for ECS Task IAM support in discovery-ec2

### PR DESCRIPTION
**Pull request by mohit**
Updating the AWS SDK to the latest released version. In particular this support ECS IAM Task Roles which are very useful when running Elasticsearch in a docker container on ECS.

Fixes https://github.com/elastic/elasticsearch/issues/23039 for `discovery-ec2`. Using this on ECS and tested it locally using docker.

### CODE REVIEW

**Comment by jasontedor** [comment]
There is more to updating dependencies than bumping the version. You need to also update SHAs and maybe grant permissions to the JAR over the old version. It could be the new SDK needs more permissions than the current, and those might be permissions we would not even grant. So I would ask you: please at least run `gradle :plugins:discovery-ec2:check` and update this pull request accordingly.

**Review by dadoonet — CHANGES_REQUESTED** [review]
I think we should update both discovery-ec2 and repository-s3 projects at the same time.

Note that last time I tried to upgrade AWS SDK, I got a SM issue (See #19594). May be it's not the case anymore but @mohit could you try to run your own version of the plugin and see if it does not break anything?

Then, does this upgrade automagically add support for ECS Task? Or is there any other code change need?

Thanks!

**Comment by mohit** [comment]
Thanks for the instructions! I found various Mocks for AwsEc2Service that broke and am in the process of adding the fixes. As for the runtime, I replaced the jars in my Docker container for `discovery-ec2` and it has been running the cluster on ECS successfully over the last couple of weeks with add/remove nodes. 

No code changes (apart from tests) are required for `discovery-ec2` since it uses the `DefaultCredentialsChain` but `repository-s3` requires some changes.

I'll work on pushing the changes for `repository-s3` after I'm done with `discovery-ec2`. 

My current experiments with `repository-s3` have involved using the `DefaultAWSCredentialsProviderChain` instead of the `PrivilegedInstanceProfileCredentialsProvider` in the plugin: https://github.com/elastic/elasticsearch/blob/master/plugins/repository-s3/src/main/java/org/elasticsearch/repositories/s3/InternalAwsS3Service.java#L135

This [comment](https://github.com/elastic/elasticsearch/issues/23039#issuecomment-279510903) suggests not using the `DefaulAWSCredentialsProviderChain` for security reasons but in the code I see `env vars` (or StaticCredentials) are still supported.

In either case, thanks for the help and I'll add the changes in the next 24 hours or so (working with Java after a long time and it's taking some time to bootstrap the JDK/Eclipse environment).

**Comment by mohit** [comment]
@dadoonet Apologies but I've updated the `AmazonEC2Mock` and license SHAs but currently getting the following error when running `gradle plugins:discovery-ec2:check` and not sure what it is referring to. 

```FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':plugins:discovery-ec2:thirdPartyAudit'.
> CLASSES ARE MISSING! [com/amazonaws/jmespath/JmesPathEvaluationVisitor.class, com/amazonaws/jmespath/JmesPathExpression.class, com/amazonaws/jmespath/JmesPathField.class, com/amazonaws/jmespath/JmesPathFlatten.class, com/amazonaws/jmespath/JmesPathIdentity.class, com/amazonaws/jmespath/JmesPathLengthFunction.class, com/amazonaws/jmespath/JmesPathLiteral.class, com/amazonaws/jmespath/JmesPathProjection.class, com/amazonaws/jmespath/JmesPathSubExpression.class, com/amazonaws/jmespath/ObjectMapperSingleton.class, com/amazonaws/jmespath/OpGreaterThan.class, software/amazon/ion/IonReader.class, software/amazon/ion/IonSystem.class, software/amazon/ion/IonType.class, software/amazon/ion/IonWriter.class, software/amazon/ion/Timestamp.class, software/amazon/ion/system/IonBinaryWriterBuilder.class, software/amazon/ion/system/IonSystemBuilder.class, software/amazon/ion/system/IonTextWriterBuilder.class, software/amazon/ion/system/IonWriterBuilder.class]
```

**Comment by jasontedor** [comment]
@mohit Those are classes referenced by dependencies that are not in any of the dependencies on the classpath. You have to figure out if those classes are needed for the functionality we support, or not. If they are needed, you need to add the required dependency. If they are not, they need to be excluded for the audit (in the build.gradle) explaining why. We do not like adding new dependencies so the case must be strong that a new one is needed here.

**Comment by jasontedor** [comment]
Also, I think it will be too much to add upgrading repository-s3 to this PR, please leave it out.

**Comment by mohit** [comment]
I don't think the classes are required on account of me already having used the `InstanceProfile` and `ContainerProfile` features of the AWS SDK library. Following up on other explanations in `build.gradle` to see if I can get more rigorous about these exclusions.

**Comment by mohit** [comment]
With the above commits `gradle plugins:discovery-ec2:check` are passing.

**Comment by dadoonet** [comment]
> Also, I think it will be too much to add upgrading repository-s3 to this PR, please leave it out.

I agree that it's not mandatory. We need to open an issue (or better another PR) to track it IMO.

**Comment by dadoonet** [comment]
@mohit Just checking: did you try to run your version of the plugin on EC2? 
Does it support ECS Task IAM? If so, is there anything to add in the documentation?

**Comment by mohit** [comment]
@dadoonet I have tested by adding the updated AWS dependencies to the `docker.elastic.co/elasticsearch/elasticsearch:5.5.2` docker image and `discovery-ec2` does inherit ECS Task IAM Role assigned.

Unfortunately I've not been able to get a working `elasticsearch:7.0.0-alpha1` container built to install this plugin. The installation of my `discovery-ec2` build on the `elasticsearch:5.5.2` docker container is complaining about a version mismatch. `Exception in thread "main" java.lang.IllegalStateException: /usr/share/elasticsearch/plugins/.installing-5410796145994513969/discovery-ec2-7.0.0-alpha1-SNAPSHOT.jar requires Elasticsearch 7.0.0-alpha1, your system: 5.5.2`

Any advice on how to proceed will be welcome. Thanks again on all your help!

**Comment by jasontedor** [comment]
@mohit I would recommend cherry-picking your changes to the plugin to the v6.0.0-beta2 tag, building that from source, and using the 6.0.0-beta2 version of our Docker container for testing.

**Comment by mohit** [comment]
Okie. So I built a container using `6.0.0-beta1` but it seems that `cloud.aws.region` has been deprecated. This setting however, seems to be required for `discovery-ec2` to work properly in the AWS region I'm testing `us-west-1` when using `5.5`. 

I'm not a 100% sure why the `zen` discovery is failing to find other nodes in `6.0.0` but it seems to show the same behavior as `5.5` when `cloud.aws.region` is not set. I can dig into alternatives and debug level logging but would love to know more about the alternative for setting AWS SDK region in `6.0.0-beta`    

https://www.elastic.co/guide/en/elasticsearch/plugins/current/discovery-ec2-usage.html#discovery-ec2-usage-region

**Comment by mohit** [comment]
okay found https://www.elastic.co/guide/en/elasticsearch/plugins/6.0/_settings.html, will test by setting `endpoint` in `6.0.0-beta2`. I don't think the automatic setting for this is working correctly though.

**Comment by mohit** [comment]
Okay was able to build a docker container using `6.0.0-beta2` and run it on ECS using the commits cherry-picked from this branch. The cluster zen discovery works and checked CloudTrail logs to ensure that the IAM Task Role was being used for the requests to AWS.

```json
...
    "userIdentity": {
        "type": "AssumedRole",
        "principalId": "AAAAAAAA-5d1ff6c2692d",
        "arn": "arn:aws:sts::000000000:assumed-role/elasticsearch-dev/0548c3df-5530-4775-a6ab-5d1ff6c2692d",
        "accountId": "000000000",
        "accessKeyId": "000000000AAA",
        "sessionContext": {
            "attributes": {
                "mfaAuthenticated": "false",
                "creationDate": "2017-09-07T00:12:50Z"
            },
            "sessionIssuer": {
                "type": "Role",
                "principalId": "000000000AAAA",
                "arn": "arn:aws:iam::000000000:role/elasticsearch-dev",
                "accountId": "000000000",
                "userName": "elasticsearch-dev"
            }
        }
    },
    "eventTime": "2017-09-07T00:15:14Z",
    "eventSource": "ec2.amazonaws.com",
    "eventName": "DescribeInstances",
    "awsRegion": "us-west-1",
    "sourceIPAddress": "00.000.000.000",
    "userAgent": "aws-sdk-java/1.11.187 Linux/4.4.41-35.53.amzn1.x86_64 OpenJDK_64-Bit_Server_VM/25.141-b16/1.8.0_141",
    "requestParameters": {
        "instancesSet": {},
        "filterSet": {
            "items": [
                {
                    "name": "instance-state-name",
                    "valueSet": {
                        "items": [
                            {
                                "value": "running"
                            },
                            {
                                "value": "pending"
                            }
                        ]
                    }
                }
            ]
        }
    }
...
```

**Comment by mohit** [comment]
I don't think there is a need to add anything to the documentation but like I mentioned above setting `discovery.ec2.endpoint` was required and it the automatic region detection is not working.

**Comment by mohit** [comment]
@dadoonet any other requirements here?

**Review by dadoonet — APPROVED** [review]
LGTM
I can hopefully merge it next week unless @jasontedor wants to do it?

**Comment by dadoonet** [comment]
Thanks @mohit. I pushed it in master (7.0.0) and 6.x (6.1.0).

**Pull request merged**
