### PR TITLE
Adjust mute for particular condition for 106647

### PR DESCRIPTION
**Pull request by benwtrent**
The test failure occurs when we have a `threshold`. Even when only gathering a single document for a query, because of this line: 

```
    public LeafCollector getLeafCollector(LeafReaderContext context) throws IOException {
        if (hitsThresholdChecker.totalHitsThreshold == Integer.MAX_VALUE) {
            return super.getLeafCollector(context);
        }
        earlyTerminateIfNeeded(); //<-- Terminate on segment before checking if there are any matching docs at all.
```

We will check for earlyTermination even if the leaf has no matching docs. But, this is expected by other tests.

This does a partial unmute allowing for the test to run, but acknowledging we have a strange edge case here that conflicts the expected results for two of our tests:

`testCollectedHitCount()` when threshold==1 vs
`testEarlyTerminatesWithoutCollection()`

### CODE REVIEW

**Comment by benwtrent** [comment]
@javanna I am just going to close this as you expressed interest in fixing this yourself in a different way.

**Comment by javanna** [comment]
I meant to review this and better understand it, but I had no spare cycles yet. Did not necessarily have a different approach in mind. I had the feeling that we may be hiding bugs by adjusting the code, that's it.

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Review by javanna — APPROVED** [review]

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Pull request merged**
