### PR TITLE
Note discovery-file's deprecation in release notes

### PR DESCRIPTION
**Pull request by DaveCTurner**
This change adds a note about the deprecation of the `discovery-file` plugin to
the release notes for 6.5. Relates #33241.

### CODE REVIEW

**Comment by DaveCTurner** [comment]
@lcawl my main concern here is that this PR introduces the 6.5 release notes and removes the commented-out text at the top of the 6.4 release notes. I'm not sure what the process is for that but this seemed like the best thing to do.

**Comment by lcawl** [comment]
@DaveCTurner I ran a build on this content and it looks good to me.  There are some items missing from the 6.4 release notes, but I'll forward-fit those in a separate PR.
Please note: If you haven't already done so, can you add a more verbose description of the breaking changes in this section too?: https://www.elastic.co/guide/en/elasticsearch/reference/6.x/breaking-changes-6.5.html

**Comment by DaveCTurner** [comment]
The failure of the JDK11 build is unrelated to this change; I opened #33579.

**Review by ywelsch — APPROVED** [review]
LGTM

**Comment by DaveCTurner** [comment]
@lcawl I think there are no breaking changes here - the associated breaking change is #33257 which includes its own additions to the release notes.

**Review by lcawl — COMMENTED** [review]
LGTM

**Pull request merged**
