### PR TITLE
Delete differing files in the store before restoring

### PR DESCRIPTION
**Pull request by abeyad**
Ensures that during the restore process, if a file in the snapshot
already has a file of the same name in the Store, but is different
in content (different checksum/length), then those files are first
deleted before restoring the files in question.

We added this deletion before writing the new file in https://github.com/elastic/elasticsearch/pull/20147, but it applied to any files being restored, whether they were different or missing.  In this PR, we ensure this step is only applied on those files that are truly different from what is found in the snapshot.

Relates #20148

### CODE REVIEW

**Comment by mikemccand** [comment]
LGTM, thanks @abeyad .

**Comment by abeyad** [comment]
thanks for the review @mikemccand!

**Comment by s1monw** [comment]
@abeyad that's exactly what we where talking about the other night! thanks for doing this.

**Comment by abeyad** [comment]
@s1monw no problem!  it wasn't until Igor mentioned the potential issue that I dug through and realized we are using `RecoveryDiff` to keep track of the files, so the change was easy :)

**Pull request merged**
