### PR TITLE
Remove the `MockTcpTransport`

### PR DESCRIPTION
**Pull request by Tim-Brooks**
This commit removes all remaining usages of the `MockTcpTransport`.
Additionally it removes the `MockTcpTransport` and its test case.

### CODE REVIEW

**Comment by tbrooks8** [comment]
run gradle tests 1

**Comment by tbrooks8** [comment]
run gradle build tests 1

**Review by original-brownbear — APPROVED** [review]
LGTM, test failure looks unrelated

**Comment by original-brownbear** [comment]
@elasticmachine run gradle build tests 1

**Review by s1monw — APPROVED** [review]

**Pull request merged**
