### PR TITLE
Remove unused routing allocation from disk threshold decider.

### PR DESCRIPTION
**Pull request by howardhuanghua**
Remove unused routing allocation from disk threshold decider.

### CODE REVIEW

**Comment by original-brownbear** [comment]
Jenkins test this

**Comment by howardhuanghua** [comment]
Merged latest master branch.

**Comment by original-brownbear** [comment]
Jenkins test this

**Comment by howardhuanghua** [comment]
Done. Thank you @original-brownbear .

**Comment by original-brownbear** [comment]
Jenkins test this

**Review by original-brownbear — APPROVED** [review]

**Pull request merged**
