### PR TITLE
Force Merge: clarify execution and storage requirements

### PR DESCRIPTION
**Pull request by frederikbosch**
Because of the additional space required you I was wondering how operations are executed: sync or async. Docs did not give me an answer. Using trial and error I found out it is executed synchronously. I thought the information to be useful for others too.

### CODE REVIEW

**Comment by frederikbosch** [comment]
@javanna Then my observation was not correct indeed. The indices I executed the operation on were all having one shard. Therefore I assumed that the operation was synchronous per index, while actually it is synchronous per shard.

**Comment by frederikbosch** [comment]
@javanna I updated the PR. My concern is the storage increase people have to take into account when running this operation. Since the operation is sync per shard, it occurs to me that it is an increase of approx 100% of the largest shard is what could be expected (assuming read-only indices).

**Review by javanna — CHANGES_REQUESTED** [review]
I left a comment, thanks again @frederikbosch

**Comment by javanna** [comment]
hi @frederikbosch let me know if you need help with this, if you don't have time to make the requested changes I can also make them so I can merge your PR. Let me know what you prefer ;)

**Comment by frederikbosch** [comment]
@javanna Yes sorry. At this moment I think I cannot give follow-up to the PR. If you could finish it, please go ahead. I think you are also better in formulating the exact behaviour.

**Comment by frederikbosch** [comment]
Thank you!

**Pull request merged**
