### PR TITLE
[ML] Upgrade to AWS SDK v2

### LINKED ISSUE #110590: Upgrade AWS Bedrock SDK to v2 as SDK v1 will be EOL end of 2025
### Description

The addition of [Amazon Bedrock support for the Inference API](https://github.com/elastic/elasticsearch/pull/110248) uses the AWS SDK v1 for it's underlying connections to Amazon Bedrock. The [AWS SDK v1 for Java will be EoL on December 31, 2025](https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-java-v1-x-on-december-31-2025/). 

Within the next year, this should be updated to use v2 of the AWS SDK before EoL for v1 happens.

### PR DESCRIPTION
**Pull request by prwhelan**
- Replaced AWS 1.12.740 with 2.28.13
- Removed `aws-java-sdk*` and its transitive dependencies.
- Added `awssdk:bedrockruntime` as an `implementations`, all transitive dependencies are added as `api` matching their marked `Compile` in maven.
- Added `awssdk:netty-nio-client` as our client implementation, since our v1 integration is using the respective Async client.
- Added netty packages as `runtimeOnly` since they are only used during runtime.
- Replaced AWS's use of SLF4J-1.7 with our declaration of SLF4J-2.x, since SLF4J includes backwards-compatible bindings.
- Migrated all references from the v1 package (`com.amazonaws`) to the v2 package (`software.amazon.awssdk`).

Notable changes in the SDK:
- *Result objects are renamed to *Response objects.
- Objects are now immutable and require Builders to set fields.
- Getters no longer have the `get*` prefix, e.g. `getModelId()` is now `modelId()`.
- `Future` has been replaced with `CompletableFuture`.
- There is no longer a need to invoke the `IdleConnectionReaper`, this is now done when the client is closed.
- Builders have a consumer mutation pattern for modifying many fields at once.

Security changes:
- The underlying Builder objects always check to see if the `.aws/credentials` and `.aws/config` files exist, even if they are not used, so our `plugin-security.policy` now allows reading these files.
- The Builder always checks for the `http.proxyHost` property before defaulting to the hardcoded Bedrock URL.

Resolve #110590

### CODE REVIEW

**Review by mark-vieira — APPROVED** [review]

**Comment by prwhelan** [comment]
@elasticmachine update branch

**Review by maxhniebergall — APPROVED** [review]
LGTM

**Comment by prwhelan** [comment]
@elasticmachine update branch

**Comment by prwhelan** [comment]
@elasticmachine update branch

**Comment by prwhelan** [comment]
@elasticmachine update branch

**Pull request merged**
