### PR TITLE
Revert tmpdir

### PR DESCRIPTION
**Pull request by alpar-t**
This PR reverts changes to make TMP dirs with spaces work as these have backwards comparability implications and the initial changes don't work on Linux. 
ClusterFormationTasks now uses a tmp dir without spaces so we don't break it on Windows with this revert.

### CODE REVIEW

**Comment by mark-vieira** [comment]
Is there an existing issue to address tmp dirs with spaces? This is still a problem for folks I assume? We are simply reverting the initial fix because it has other side-effects. If folks are running into this we should still at least track it as an issue and perhaps come up with a different solution.

**Comment by jasontedor** [comment]
Yes, see #39965.

**Review by rjernst — COMMENTED** [review]
I see this reverts the changes to the shell scripts, but isn't a real revert to also pass TMP through as we were implicitly doing before? This seems to change which tmp dir is used, but it is still something we are setting up (and still under the build dir, which may or may not have a space, depending if the checkout path has a space).

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by atorok** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample and run elasticsearch-ci/bwc

**Comment by atorok** [comment]
@elasticmachine run elasticsearch-ci/1

**Pull request merged**
