### PR TITLE
Adding ml_settings entry to HLRC and Docs for deprecation_info

### PR DESCRIPTION
**Pull request by benwtrent**
Simple change to add the new `ml_settings` key to the HLRC side of the deprecation info call, and to the related docs.

### CODE REVIEW

**Comment by benwtrent** [comment]
run elasticsearch-ci/2

**Comment by benwtrent** [comment]
run elasticsearch-ci/2

**Comment by benwtrent** [comment]
run elasticsearch-ci/1

**Review by AthenaEryma — APPROVED** [review]
LGTM once CI is happy

**Pull request merged**
