### PR TITLE
Use ActionListenerResponseHandler in more spots to improve logging

### PR DESCRIPTION
**Pull request by original-brownbear**
I saw some slow inbound handler logging form transport single shard action but wasn't able to figure out what listener was slow here because of the anonymous response handler not having a `toString`. -> Using the functionally equivalent ActionListenerResponseHandler saves some code here and gives a proper `toString` so I fixed the single shard action usage and two other spots I could quickly find.

### CODE REVIEW

**Review by idegtiarenko — APPROVED** [review]

**Comment by original-brownbear** [comment]
@elasticmachine update branch

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/part-2  (unrelated)

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/bwc

**Comment by original-brownbear** [comment]
Jenkins run 
elasticsearch-ci/part-1

**Pull request merged**
