### PR TITLE
Fix serialization of PendingClusterTask.timeInQueue.

### PR DESCRIPTION
**Pull request by jpountz**
This parameter is serialized as a vLong while it could sometimes be negative.

### CODE REVIEW

**Comment by s1monw** [comment]
we just hit this in our BWC test here http://build-us-00.elasticsearch.org/job/es_bwc_1x/7637/CHECK_BRANCH=tags%2Fv1.1.2,jdk=JDK7,label=bwc/testReport/junit/org.elasticsearch.snapshots/SnapshotBackwardsCompatibilityTest/testSnapshotAndRestore/

maybe we should make sure the value to vlong is positive?

**Comment by s1monw** [comment]
@jpountz ping

**Comment by bleskes** [comment]
@s1monw we use -1 to signal stuff in the queue which are not updateTasks (as far as I can tell those are timeout notifications). See https://github.com/elasticsearch/elasticsearch/blob/master/src/main/java/org/elasticsearch/cluster/service/InternalClusterService.java#L306

I think this is what is broken. We should have a common queue item base class that gives as the time inserted + a source and only have these in queue (UpdateTask should inherit from it).

**Comment by s1monw** [comment]
I just wanna fix the assertion here. We arlready have new code that transfers it correctly. WE can't fix this differently sorry.

**Comment by s1monw** [comment]
^^ by that I mean for nodes < 1.4.0

**Comment by bleskes** [comment]
My suggestion implies we never write negative values. if we never have to write a negative value, I think the problem is solved for <1.4 as well. 

> maybe we should make sure the value to vlong is positive?

maybe you meant writing a 0 where we see -1 (which is a valid value now). This is also a workaround but is not the "right" thing. Just wanted to share the idea of a proper fix.

**Comment by s1monw** [comment]
again the issue is fixed we use `writeLong` if you wanna communicate this differently that's all fine with me but it won't fix anything.

**Comment by jpountz** [comment]
@s1monw are you suggesting we should fix it by removing the assertion?

**Comment by s1monw** [comment]
> @s1monw are you suggesting we should fix it by removing the assertion?
no I am suggesting to fix the BWC code to send ` out.writeVLong(Math.max(0, timeInQueue));` since the serialization will be broken if you pass a neg value to `writeVLong` no?

**Comment by jpountz** [comment]
Makes sense to me. +1

**Pull request closed without merging**
