### PR TITLE
Use a hardcoded version for the CCS compatibility check

### PR DESCRIPTION
**Pull request by thecoop**
Workaround for #94341 - use a hardcoded version check that needs to be updated on every minor release

### CODE REVIEW

**Review by rjernst — APPROVED** [review]
Looks good by me.

**Comment by thecoop** [comment]
@rjernst Where does this need to be documented to ensure it is bumped on a minor release? (once it is merged)

**Review by javanna — APPROVED** [review]
looks ok to me for now given we can keep the compatibility check. I wish no manual work was required to keep the previous minor up-to-date. Would it be possible to have an assertion and / or have tests fail once we bump to the next minor? That would make sure that we don't forget to update.

**Comment by thecoop** [comment]
Unfortunately not, as the transport versions are independent of the node versions - you have to  update the constant with the transport version at the time of the minor release. We'll have automation that will help with this though.

**Pull request merged**
