### PR TITLE
Use settings infrastructure for shards and replicas

### PR DESCRIPTION
**Pull request by jasontedor**
We get the number of shards and replicas with our bare hands in index metadata, rather than letting the settings infrastructure do the work for us. This commit switches to using the settings infrastructure.

Relates #56712

### CODE REVIEW

**Comment by rjernst** [comment]
I don't think this addresses the problem I was trying to solve in #56712. The problem as I see it is both [MetadataCreateIndexService](https://github.com/elastic/elasticsearch/pull/56712/files#diff-bdd76487858653baa447a7a259011afbL768) and [MetadataUpdateSettingsService](https://github.com/elastic/elasticsearch/pull/56712/files#diff-131e17d728c13ba9e52f2c3f0357cd92L200) both having their own default value logic, instead of using the Setting. Thus the default of 1 is defined in several places.

**Comment by jasontedor** [comment]
@rjernst I took it further.

**Comment by jasontedor** [comment]
@elasticmachine update branch

**Review by rjernst — APPROVED** [review]
Thanks for the changes. It still seems odd to me to be reading and setting back as we do, but as I understand from your comments there are other places constructing IndexMetadata with temporary values for the number of replicas. Is that the case for shards though? Shouldn't that never change, so we could always read it in IndexMetadata and not read+set externally?

Either way, this is better than what existed since the default value no longer exists in multiple places, thank you! LGTM.

**Pull request merged**
