### PR TITLE
Build: set group for client and sniffer, disable publishing for client-test

### LINKED ISSUE #19205: REST client is not released with the right groupId
Apparently we published the REST Client on maven central at https://repo1.maven.org/maven2/org/elasticsearch/rest/5.0.0-alpha4/

Which means that the artifact coordinates are `org.elasticsearch:rest:5.0.0-alpha4`.
But it should be `org.elasticsearch.client:rest:5.0.0-alpha4`.

### PR DESCRIPTION
**Pull request by javanna**
Build: set group for client and sniffer, disable publishing for client-test

Closes #19205

### CODE REVIEW

**Comment by dadoonet** [comment]
It looks good to me (as far as my Gradle knowledge can validate the change :p ). So have another reviewer might be better...

**Comment by javanna** [comment]
@nik9000 can you have a look? I think this should have been part of #19032

**Comment by spinscale** [comment]
Ran `gradle install` locally with this PR, and was put under 

```
~/.m2/repository/org/elasticsearch/client/rest/5.0.0-alpha4-SNAPSHOT
```

++

**Comment by nik9000** [comment]
Lgtm. I should have done it when I moved it.

**Pull request merged**
