### PR TITLE
Clarify IntelliJ IDEA Jar Hell fix

### PR DESCRIPTION
**Pull request by catalin-ursachi**
Clarified the instructions for fixing IntelliJ's `idea_rt.jar` Jar hell issue (as updated by https://github.com/elastic/elasticsearch/pull/27614); specifically, that:

* Setting `Shorten command line` to `classpath file` is only necessary if the launcher is disabled via a JVM option.
* If the launcher is disabled via an `idea.properties` setting, a restart is required (even though IntelliJ doesn't prompt you for one).

### CODE REVIEW

**Comment by rjernst** [comment]
I think the instructions adding the setting to idea.properties should stay next to the clause about 2017.2, and the 2017.3 instructions should be it's own sentence(s) after that.

**Comment by catalin-ursachi** [comment]
So:

> In order to run tests directly from IDEA 2017.2 and above, it is required to disable the IDEA run launcher in order to avoid idea_rt.jar causing "jar hell". This can be achieved by adding the `-Didea.no.launcher=true` JVM option, or by adding `idea.no.launcher=true` to the `idea.properties` file which can be accessed under Help > Edit Custom Properties (this will require a restart of IDEA). For IDEA 2017.3 and above, in addition to the JVM option, you will need to go to Run->Edit Configurations... and change the value for the `Shorten command line` setting from `user-local default: none` to `classpath file`.

?

**Comment by rjernst** [comment]
Yes, but I would separate the "or" portion about idea.properties into a separate sentence (it sounds like a run-on sentence right now). Perhaps begin with ```Alternatively, `idea.no.launcher=true` can be set in the `idea.properties` file...```

**Review by rjernst — APPROVED** [review]
Thanks @catalin-ursachi, looks good now.

**Pull request merged**
