### PR TITLE
Remove `default_field: message` from metrics index templates

### PR DESCRIPTION
**Pull request by felixbarny**
This is a follow-up from https://github.com/elastic/elasticsearch/pull/102456

### CODE REVIEW

**Review by flash1293 — APPROVED** [review]
Changes LGTM, could we get this into 8.15 or should we wait for 8.16?

**Comment by felixbarny** [comment]
Seems like that is something we could back port to 8.15, as it's causing this bug: https://github.com/elastic/kibana/issues/186616. WDYT @dakrone?

**Comment by mattc58** [comment]
++ on backport to `8.15.0` as it's directly related to a downstream bug. However @felixbarny or @flash1293 is there any testing we're able to do here? Or will it be covered by any downstream tests?

**Review by mattc58 — APPROVED** [review]
+1 if CI likes it

**Comment by felixbarny** [comment]
@elasticmachine update branch

**Comment by felixbarny** [comment]
I think this would be mainly tested downstream. We made the same changes for the logs index template in https://github.com/elastic/elasticsearch/pull/102456, so I feel confident in just relying on the existing tests for this follow-up.

**Pull request merged**
