### PR TITLE
ES|QL: pin 'now' as query start time

### PR DESCRIPTION
**Pull request by luigidellaquila**
Use `now` (already present in ESQL Configuration) to determine the start time of the query.
The serialization is already in place, so the value is already shared between the nodes.

### CODE REVIEW

**Review by astefan — APPROVED** [review]
LGTM

**Comment by bpintea** [comment]
FTR: https://github.com/elastic/elasticsearch/pull/103474/files#r1427142330

I'm wondering if this method shouldn't be replaced with what it does on the result of `now()`, at it's sole invocation place in the `ComputeService` class. (Or, less ideal, maybe rename it to `epochNow()`?)

**Comment by astefan** [comment]
My [original suggestion](https://github.com/elastic/elasticsearch/pull/112595#discussion_r1763268489) was to place the `now` initialization time in the constructor of the `Configuration` instead. I don't see why this `now` value should come from "outside", but in that PR things were considered differently and I didn't object.

**Comment by bpintea** [comment]
> My https://github.com/elastic/elasticsearch/pull/112595#discussion_r1763268489 was to place the now initialization time in the constructor

👍 
I guess it should work if all these should just use one nanos value, init'ed in c'tor. And I guess we can have a protected c'tor that takes the value too, for testing? Plus a `now()` method returning zoned time off it.

**Comment by luigidellaquila** [comment]
> My https://github.com/elastic/elasticsearch/pull/112595#discussion_r1763268489 was to place the now initialization time in the constructor of the Configuration

Right now the initialization is in the constructor; I think we made the change when we [removed EsqlConfiguration](https://github.com/elastic/elasticsearch/pull/111653)

About the "zoned" `now`, my understanding is that `now.instant()` will be an absolute value, independent from the zone, so we can rely on it, right?

**Comment by bpintea** [comment]
> the initialization is in the constructor

There are two times now, one init'ed in the c'tor (the old one), the other one passed in, added in the PR Andrei mentioned (a new one). We could/should make just one out of them.

> so we can rely on it, right?

That's my understanding too.

**Comment by luigidellaquila** [comment]
> There are two times now

Oh, I was looking at the wrong place... 🤦 

I'm not sure I fully understand the difference between `absoluteStartedTimeInMillis` and `queryStartTimeNanos` (apart from the precision).
`now` and `absoluteStartedTimeInMillis` are practically instantiated at the same time, and `now` has nanosecond precision, so maybe we can use it for both?

I don't know, I'm confused...

**Review by nik9000 — APPROVED** [review]
Seems right.

**Comment by nik9000** [comment]
> I'm not sure I fully understand the difference between `absoluteStartedTimeInMillis` and `queryStartTimeNanos` (apart from the precision).

I'm not sure why we have the nanosecond one to be honest.

**Comment by nik9000** [comment]
> I'm not sure why we have the nanosecond one to be honest.

Oh! Sorry one second.

**Comment by bpintea** [comment]
> I'd say this is enough to keep now and queryStartTimeNanos separate.

Since `getQueryStartTimeNanos()` is later subtracted again from `System.nanoTime()`, this makes sense.
But having a `now()` method along with `absoluteStartedTimeInMillis()`, which just returns the millis in `now()`, 🤷 .

**Pull request merged**
