### PR TITLE
Refactor geo_point validate_* and normalize_* for 1.7

### LINKED ISSUE #10170: [GEO] Deprecate 'validate_*' options in GeoPointMapping
No need to carry 3 validate options in GeoPointFieldMapping. This is just causing confusion so next version of ES will deprecate the validate_lat, validate_lon option and simply use validate.  The following version will remove validate_{lat|lon} altogether.

### PR DESCRIPTION
**Pull request by nknize**
This PR deprecates validate_\* and normalize_\* options for `geo_point` field mapping in favor of  more straight-forward `validate` and `normalize` parameters. This PR is for 1.7 only. 2.0 will completely remove these parameters.

### CODE REVIEW

**Comment by nknize** [comment]
@clintongormley made the suggested change from normalize/validate to coerce/ignore_malformed, respectively. This PR should be ready to go for 1.71. Will need to make 2.0 changes separately since the mapping logic is completely different.

**Comment by clintongormley** [comment]
@nknize i think in 2.0 we still need to maintain bwc.  So we should accept the old settings when opening old indices, and translate them to the new settings.  New indices should only accept the new settings.

Also, once merged into master, could you open an issue to add a check for this to the [migration plugin](http://github.com/elastic/elasticsearch-migration/issues)

ta

**Comment by clintongormley** [comment]
Closed in favour of #10248

**Comment by nknize** [comment]
So we're keeping this change out of 1.7.x and going straight to 2.0, right?

**Comment by clintongormley** [comment]
Ahh sorry @nknize - when i was doing the release, I saw that #10248 had been merged and this one hadn't.  I didn't look at the contents of the PR.  

OK - let's move this to 2.0. We'll need to support the old normalize* and validate* parameters for bwc, but we should automatically migrate the settings to coerce/ignore_malformed.

**Comment by dakrone** [comment]
We discussed this today, and since these are deprecated already in the docs for 1.7 and already removed in 2.0, there's no need to refactor them for 1.7. Closing this for now, thanks @nknize!

**Pull request closed without merging**
