### PR TITLE
Mute AzureSnapshotRepoTestKitIT testRepositoryAnalysis

### PR DESCRIPTION
**Pull request by cbuescher**
Relates to https://github.com/elastic/elasticsearch/issues/108504

### CODE REVIEW

**Comment by cbuescher** [comment]
@fcofdez since you already did the risk labeling on the issue, are you okay to mute?

**Review by tlrx — APPROVED** [review]
LGTM

**Comment by tlrx** [comment]
Thanks @cbuescher !

**Comment by cbuescher** [comment]
Ups, sorry forgot to merge this one during test triage. Thanks @tlrx

**Pull request merged**
