### PR TITLE
Replace NOT operator with explicit `false` check - part 8

### PR DESCRIPTION
**Pull request by pugnascotia**
Part 8.

We have an in-house rule to compare explicitly against `false` instead
of using the logical not operator (`!`). However, this hasn't
historically been enforced, meaning that there are many violations in
the source at present.

We now have a Checkstyle rule that can detect these cases, but before we
can turn it on, we need to fix the existing violations. This is being
done over a series of PRs, since there are a lot to fix.

### CODE REVIEW

**Comment by pugnascotia** [comment]
The test failure reproduces locally. I'll look into it tomorrow.

**Comment by pugnascotia** [comment]
I think the test failure was unrelated to this PR - I couldn't replicate on master, and it went away with a merge.

**Review by breskeby — APPROVED** [review]
tried to find an issue... with no luck :)

**Comment by pugnascotia** [comment]
Backported to `7.x` in 1b6ad967cb3

**Pull request merged**
