### PR TITLE
Fail query when a sort is provided in conjunction with rescorers

### PR DESCRIPTION
**Pull request by jimczi**
This change fixes a regression introduced in 6 that removes the skipping of the rescore phase
when a sort other than _score is used.
This commit also adds an assert that checks if the topdocs are sorted by _score after the rescoring.
This is the responsibility of the rescorer to make sure that topdocs are sorted after rescore so we
just check that this condition is met in the rescore phase.

### CODE REVIEW

**Comment by jpountz** [comment]
What if the sort includes the score? I'm wondering whether we should fail requests that both provide a `sort` and a `rescore` element?

**Comment by jimczi** [comment]
>  I'm wondering whether we should fail requests that both provide a sort and a rescore element?

Probably better than just skipping the rescore phase even though this is documented:
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-rescore.html
I'll update the PR. 

> What if the sort includes the score?

I think we should fail if there is a sort criteria other than _score. Rescorers need to resort the topdocs and if they do it wrong this can break the merge sort in the coordinating node. With custom rescorers I think it's good to keep it simple, rescorers work only when sort is not provided and fail otherwise ?

**Comment by nik9000** [comment]
> What if the sort includes the score?

I imagine that is pretty broken right now. I wonder if it'd be ok to not allow rescore if the sort isn't *just* on score. Like  you suggest, failing the whole request rather than skipping the rescore.

**Comment by jpountz** [comment]
> I wonder if it'd be ok to not allow rescore if the sort isn't just on score.

+1 to that approach

**Comment by jimczi** [comment]
Thanks @jpountz and @nik9000 
I updated the title of the PR and pushed a change that fails the request when a sort is provided in conjunction with a rescorer.

**Review by jpountz — APPROVED** [review]

**Pull request merged**
