### PR TITLE
Remove unused variable in QueryContainer

### PR DESCRIPTION
**Pull request by krisds**
As requested, I will split #38033 into separate PRs. Here is the fourth part.

This one resolves:
* [Container contents are never accessed](https://lgtm.com/projects/g/elastic/elasticsearch/snapshot/dist-1916470085-1548143539391/files/x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/querydsl/container/QueryContainer.java?sort=name&dir=ASC&mode=heatmap#x581195a77954fd21:1)

### CODE REVIEW

**Comment by costin** [comment]
Hi, thanks for raising the PR.
If I understand correctly this PR is about removing an unused variable, correct? I ask since the PR title is a bit misleading (not sure what "container" you refer to).

**Comment by krisds** [comment]
Correct. The container is `nestedRefs`, which is added to but never read.

PS. You can click the link in the description to see the original alert for more details.

**Comment by javanna** [comment]
test this please

**Comment by javanna** [comment]
Same here @krisds if you could merge master in, that would be fantastic. Thank you.

**Comment by javanna** [comment]
retest this please

**Comment by javanna** [comment]
retest this please

**Comment by javanna** [comment]
run elasticsearch-ci/packaging-sample

**Review by javanna — APPROVED** [review]

**Comment by javanna** [comment]
thanks @krisds !

**Pull request merged**
