### PR TITLE
Fix shadowed vars pt7

### PR DESCRIPTION
**Pull request by pugnascotia**
Part of #19752. Fix more instances where local variable names were shadowing field names.

Also modify our fork of `HiddenFieldCheck` to add the `ignoreConstructorBody` and `ignoredMethodNames` parameters, so that the check can ignore more matches.

### CODE REVIEW

**Comment by pugnascotia** [comment]
@elasticmachine run elasticsearch-ci/part-2

**Comment by pugnascotia** [comment]
@elasticmachine update branch

**Review by mark-vieira — APPROVED** [review]
LGTM

**Comment by pugnascotia** [comment]
Backported to `8.0` in 5d85962b1a9.

**Pull request merged**
