### PR TITLE
Clean up Analyze API test case

### PR DESCRIPTION
**Pull request by johtani**
Using expectThrows instead of using try-catch

### CODE REVIEW

**Comment by dadoonet** [comment]
LGTM

**Comment by nik9000** [comment]
LGTM2. Thanks for cleaning this up. Consistency likes this helps a lot for people aren't working full time on the code. I know it helped me when I contributed every once in a while.

**Comment by johtani** [comment]
retest this please

**Comment by johtani** [comment]
retest this please

**Pull request merged**
