### PR TITLE
Transport client needs to know about pluggable roles

### PR DESCRIPTION
**Pull request by droberts195**
If you call isDataNode() or isMasterNode() on a
DiscoveryNode object returned by an action called
within a program using the transport client then
the code that runs needs to be aware of any pluggable
roles that exist on the node represented by that
DiscoveryNode. For example, if there is an ML node
in a cluster defined by "node.roles: [ ml ]" and you
get a DiscoveryNode for it in your program that's
using the transport client and call its isDataNode()
method then you'll get an exception if your transport
client hasn't registered the pluggable ML role.

This change makes the transport client register all
pluggable roles for the plugins passed to its
constructor. (The code is the same as that used in
Node's constructor.)

### CODE REVIEW

**Comment by droberts195** [comment]
This problem showed up in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-2/17453/, which was the CI build of the first commit of #68211.  The difference introduced by #68211 was that some nodes explicitly have the `ml` role, whereas previously they had it by default.  I guess this problem could affect customers who use the transport client against clusters containing ML or transform nodes in the later 7.x releases.  I assume nobody has reported it yet.  I can backport this to 7.11 if you think it's worthwhile.

**Comment by mark-vieira** [comment]
@elasticmachine update branch

**Review by AthenaEryma — APPROVED** [review]
LGTM, thanks for addressing this.

**Comment by droberts195** [comment]
@elasticmachine update branch

**Comment by droberts195** [comment]
Jenkins run elasticsearch-ci/2

**Comment by droberts195** [comment]
This is causing CI failures, so I reverted the change in 914885bf994495f1cf7891869f0472dc6beddb91.  The related issue is #69693.

**Pull request merged**
