### PR TITLE
Enable enrich internal cluster ITs to run with Security enabled

### PR DESCRIPTION
**Pull request by albertzaharovits**
We now generally endeavor to have all the IT work with Security enabled since this is going to be the default in v8 (unless of course the tests specifically check that some particular thing must work without Security).

This PR enables Security for `EnrichMultiNodeIT` (and `EnrichRestartIT`, but this is not import wrt Security).

Related https://github.com/elastic/elasticsearch/issues/75940
Relates https://github.com/elastic/elasticsearch/pull/76461

### CODE REVIEW

**Comment by albertzaharovits** [comment]
@elasticmachine test this

**Comment by albertzaharovits** [comment]
@elasticmachine test this please

**Review by martijnvg — APPROVED** [review]
LGTM for the test changes (pending successful build (bwc failures look unrelated))

**Review by breskeby — APPROVED** [review]
build setup looks good to me

**Comment by albertzaharovits** [comment]
Closing because it has gotten stale.

**Pull request closed without merging**
