### PR TITLE
Specify security.get_role_mapping name as list

### PR DESCRIPTION
**Pull request by russcam**
This commit updates the rest API spec for
security.get_role_mapping to specify name as a list type.
Multiple values can be specified for name as a comma-separated list.

### CODE REVIEW

**Comment by colings86** [comment]
@russcam are you still wanting to progress this PR or should it be closed?

**Comment by russcam** [comment]
Yes I am @colings86. If it LGTY , I can merge it in and backport

**Comment by colings86** [comment]
@elastic/es-security could someone take this and work with @russcam to get it merged?

**Comment by jkakavas** [comment]
@russcam apologies that this fell through the cracks. Do you mind tackling the `security.get_role` as well in this one so that we have consistency over all the security APIs ?

**Comment by russcam** [comment]
no worries @jkakavas , I'll update `security.get_role` too

**Comment by jkakavas** [comment]
@elasticmachine update branch

**Review by jkakavas — APPROVED** [review]
LGTM

**Comment by ezimuel** [comment]
I just discovered that this PR has not been backported to 7.x and 7.10 branches. This affects the generation of the clients, since we use the API spec. 
/cc @elastic/clients-team

**Pull request merged**
