### PR TITLE
Longer RCS suite timeout due to slow keystore

### LINKED ISSUE #116883: [CI] RemoteClusterSecurityReloadCredentialsRestIT testFirstTimeSetupWithElasticsearchSettings failing
**Build Scans:**
- [elasticsearch-periodic #4921 / openjdk17_checkpart4_java-fips-matrix](https://gradle-enterprise.elastic.co/s/3rwmvqomoiiyu)
- [elasticsearch-periodic #4891 / openjdk17_checkpart4_java-fips-matrix](https://gradle-enterprise.elastic.co/s/r54vuqqow26ay)
- [elasticsearch-periodic #4886 / openjdk17_checkpart4_java-fips-matrix](https://gradle-enterprise.elastic.co/s/uljwwpad2jesu)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:security:qa:multi-cluster:javaRestTest" --tests "org.elasticsearch.xpack.remotecluster.RemoteClusterSecurityReloadCredentialsRestIT.testFirstTimeSetupWithElasticsearchSettings" -Dtests.seed=540C601FBCEE4825 -Dtests.locale=hy-Armn-AM -Dtests.timezone=Asia/Aden -Druntime.java=17 -Dtests.fips.enabled=true
```

**Applicable branches:**
8.x

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.remotecluster.RemoteClusterSecurityReloadCredentialsRestIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testFirstTimeSetupWithElasticsearchSettings),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.Exception: Test abandoned because suite timeout was reached.
```

**Issue Reasons:**
- [8.x] 3 failures in test testFirstTimeSetupWithElasticsearchSettings (1.4% fail rate in 216 executions)
- [8.x] 3 failures in step openjdk17_checkpart4_java-fips-matrix (37.5% fail rate in 8 executions)
- [8.x] 3 failures in pipeline elasticsearch-periodic (37.5% fail rate in 8 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by n1v0lg**
Rather than muting the suite and losing signal, bump the suite timeout to account for very slow keystore operations.

We should follow this up with performance improvements around keystore setup in tests.

Closes: https://github.com/elastic/elasticsearch/issues/116883

### CODE REVIEW

**Review by slobodanadamovic — APPROVED** [review]
LGTM

Let's also unmute muted tests on 8.x branch.

**Comment by n1v0lg** [comment]
@elasticmachine

**Comment by n1v0lg** [comment]
@elasticmachine update branch

**Comment by n1v0lg** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.x|[](https://github.com/elastic/elasticsearch/pull/117173)|
|✅|8.16|[](https://github.com/elastic/elasticsearch/pull/117174)|
|✅|8.15|[](https://github.com/elastic/elasticsearch/pull/117175)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

**Pull request merged**
