### PR TITLE
Ignore failures to set socket options on Mac

### PR DESCRIPTION
**Pull request by ywelsch**
Brings some temporary relief for test failures until #41071 is addressed.

### CODE REVIEW

**Review by Tim-Brooks — APPROVED** [review]
LGTM

**Comment by tbrooks8** [comment]
It's worth noting that the other socket options might fail too?

**Comment by ywelsch** [comment]
> It's worth noting that the other socket options might fail too?

Good point. I've  changed this to all socket options.

**Comment by ywelsch** [comment]
@elasticmachine update branch

**Pull request merged**
