### PR TITLE
Add explanations to script score queries

### PR DESCRIPTION
**Pull request by rjernst**
While function scores using scripts do allow explanations, they are only
creatable with an expert plugin. This commit improves the situation for
the newer script score query by adding the ability to set the
explanation from the script itself.

To set the explanation, a user would check for `explanation != null` to
indicate an explanation is needed, and then call
`explanation.set("some description", true|false)`, where the latter
argument indicates whether `_score` is used in the script.

### CODE REVIEW

**Comment by mayya-sharipova** [comment]
@rjernst  Hi Ryan! Thanks for this PR, this could be very useful.  I am not completely clear about the API for explanation. Is it set in the painless script? something like this?

```js
{
    "query" : {
        "script_score" : {
            "query" : {
                "match": { "message": "elasticsearch" }
            },
            "script" : {
                "source" : "explanation.set("some description", true); doc['likes'].value / 10 "
            }
        }
     }
}
```

About the tests: we have yml tests for `script_score` query  in `80_script_score.yml` in modules:lang-painless. We can add yml tests there.  Or we can add more tests in `ScriptScoreQueryIT`.


I was trying to run the branch, but I am getting the following error:
```
...PainlessExecuteAction.java:530: error: method execute in class ScoreScript cannot be applied to given types;
                    double result = scoreScript.execute();
                                               ^
  required: ExplanationHolder
  found: no arguments
  reason: actual and formal argument lists differ in length
```

**Comment by rjernst** [comment]
> Is it set in the painless script?

Yes, the idea is that ScoreScript has an extra variable, `explanation`, which is `null` for a normal query, but when using explain query it is passed in. This way a script just checks for non-null to decide if it should set the explanation; a separate script is not needed for explain queries.

**Comment by rjernst** [comment]
> I was trying to run the branch

The branch should compile now

**Comment by mayya-sharipova** [comment]
@rjernst  looks like it still doesn't compile

**Comment by rjernst** [comment]
@mayya-sharipova Ok, sorry about that. It should work now (for real!), and I've added some unit tests.

**Comment by mayya-sharipova** [comment]
@rjernst Thank you, it works perfect now.

My main comment is if we really need a second argument in `explanation.set("some description", true|false)`?  It seems to me that is not necessary, and a signature `explanation.set("some description")` should be enough.  In `ScriptScoreQuery`,  we can check `scriptBuilder.needs_score()` and if it is true then `_score` is used in the script, and we can add a sub-explanation from the sub-query. Otherwise, not. Similarly with a default explanation,  only if `needs_score` is true, we can add a sub-explanation from the sub-query. WDYT?

**Comment by rjernst** [comment]
Thanks for the feedback @mayya-sharipova. I hadn't done this before because a script could theoretically have _score in the script, but conditionally choose to use it. However, we don't have any optimizations for that (we always calculate _score if it exists in the script currently), so I've converted the api as you suggested in 6c84bbd.

**Review by mayya-sharipova — APPROVED** [review]
Thanks for addressing the feedback, Ryan. The PR overall looks good for me, nice not to use `ScriptScoreFunction` as well.

I have just two points left:

1.  In cases when a user doesn't set explanation explicitly, the output will always include `subQueryExplanation ` even if `needsScore =false`. Should we omit `subQueryExplanation` in this case?

2. Do we want to add user documentation to `script_score` query describing how to set explanation?

**Comment by rjernst** [comment]
I believe I've addressed all your (good!) points in de07556.

**Comment by mayya-sharipova** [comment]
@rjernst Thanks, the PR looks perfect to me now!!! ready to be merged!!

**Pull request merged**
