### PR TITLE
Retrieve processors instead of checking existence

### PR DESCRIPTION
**Pull request by hub-cap**
The previous hasProcessors method would validate if a processor was
present within a pipeline, but would not return the contents of the
processors. This does not allow a consumer to inspect the processor for
specific metadata. The method now returns the list of processors based
on the class of the processor passed in.

### CODE REVIEW

**Review by martijnvg — APPROVED** [review]
👍

**Review by jbaiera — APPROVED** [review]
LGTM

**Comment by hub-cap** [comment]
@elasticmachine update branch

**Comment by hub-cap** [comment]
@elasticmachine update branch

**Comment by hub-cap** [comment]
@elasticmachine update branch

**Pull request merged**
