### PR TITLE
[Monitoring] APM mapping update

### PR DESCRIPTION
**Pull request by cachedout**
This creates needed mappings for additional APM metrics which were introduced by elastic/apm-server#2142

### CODE REVIEW

**Comment by ycombinator** [comment]
I assume these mappings are needed for https://github.com/elastic/kibana/pull/43998? If so, I'd suggest only mapping the fields we need to index for the new UI queries/aggs introduced in that PR to work correctly.

Reading through https://github.com/elastic/kibana/pull/43998 that looks like `beats_stats.metrics.apm-server.acm.*` are the new fields being introduced. So I think we should only map those for now. I don't think we need to map `beats_stats.metrics.apm-server.root.*` or `beats_stats.metrics.apm-server.sourcemap.*` at this time; we can add mappings for those when we need to use those fields in queries/aggs from the Stack Monitoring UI.

**Comment by cachedout** [comment]
Thanks, @ycombinator. I agree and have removed those two sections.

**Review by ycombinator — APPROVED** [review]
LGTM

**Review by chrisronline — APPROVED** [review]
LGTM. These seem to work fine alongside the Kibana changes

**Pull request merged**
