### PR TITLE
Update search-type.asciidoc

### PR DESCRIPTION
**Pull request by patrickmaynard**
Fixes a typo

### CODE REVIEW

**Comment by jrodewig** [comment]
Thank you for your PR @patrickmaynard.

Could you sign our contributor license agreement? This is necessary before we'll be able to merge your changes.

**Comment by jrodewig** [comment]
@elasticmachine test this please

**Comment by patrickmaynard** [comment]
Thanks. I have now signed the agreement.

**Review by jrodewig — APPROVED** [review]
LGTM. Thanks @patrickmaynard!

**Pull request merged**
