### PR TITLE
[DOCS] Remove duplicate xpack.enabled setting in example

### PR DESCRIPTION
**Pull request by JackScripter**
Remove duplicate xpack.enabled setting in example

### CODE REVIEW

**Review by lcawl — APPROVED** [review]
Thanks for finding this error!  LGTM

**Comment by jrodewig** [comment]
@JackScripter Thanks for your contribution. Would you please sign our [CLA](https://www.elastic.co/contributor-agreement)? Please use the email address associated with your commit. You can find that email address here:

https://github.com/elastic/elasticsearch/commit/a53634abe5b9b969d7e9e1bf8c655840e98a48f4.patch

We'll need a signed CLA before we can merge in your changes. Thanks again!

**Comment by JackScripter** [comment]
Do I need to do something once I signed ?
Thanks

**Comment by jrodewig** [comment]
@JackScripter Nope. Thanks for signing. I'll get this change merged in. Thanks again!

**Comment by jrodewig** [comment]
@elasticmachine ok to test

**Pull request merged**
