### PR TITLE
Use dynamic port ranges for ExternalTestCluster

### PR DESCRIPTION
**Pull request by alpar-t**
Moves methods added in #44213 and uses them to configure the port range
for `ExternalTestCluster` too.
These were still using `9300-9400` ( the default ) and running into
races.

### CODE REVIEW

**Comment by atorok** [comment]
@elasticmachine test this please

**Comment by atorok** [comment]
Here's a build where this failed: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-1/4873/testReport/junit/org.elasticsearch.script.mustache/MultiSearchTemplateIT/testBasic/

**Review by andrershov — APPROVED** [review]
LGTM

**Comment by atorok** [comment]
Since this is expected to improve CI stability I am going to go ahead and merge it, but further feedback is much welcome I will address it in a new PR.

**Pull request merged**
