### PR TITLE
adding field data test

### PR DESCRIPTION
**Pull request by forjonathanwilsonyahoocom**
noticed that there was not a unit test for the rescore plugin example covering the "fieldFactor" mode of operation that pulls data from document fields for use in rescore operation, this test helped me to understand it a bit better, and actually helps reveal some oddities about the example that future developers might not have to wonder about for so many hours.

best of luck and happy coding
jw

### CODE REVIEW

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Comment by benwtrent** [comment]
run elasticsearch-ci*

**Comment by benwtrent** [comment]
buildkite test this

**Comment by benwtrent** [comment]
@forjonathanwilsonyahoocom CI is happy with the change :D. CLA is still not happy :(. I am digging around to see whats going on. One issue might be the email used when signing the CLA might not be present on your github account. I am trying to see if the cause is something else.

**Comment by forjonathanwilsonyahoocom** [comment]
no problem, ill do so

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Review by benwtrent — APPROVED** [review]

**Comment by benwtrent** [comment]
buildkite test this

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Comment by benwtrent** [comment]
buildkite test this

**Comment by benwtrent** [comment]
@forjonathanwilsonyahoocom thank you so much for your contribution!!! Giving plugin authors more examples is exceptionally useful and will help folks in the future. 🎉🎉🎉

**Pull request merged**
