### PR TITLE
Update task names for rest compatiblity

### PR DESCRIPTION
**Pull request by jakelandis**
This commit updates two task names:
```
yamlRestCompatTest -> yamlRestTestV7CompatTest
transformV7RestTests -> yamlRestTestV7CompatTransform 
```

`7` is the N-1 version and calculated, such that when `8` is 
N-1 version the task names will be  `yamlRestTestV8CompatTest` and 
`yamlRestTestV8CompatTransform`

The motivation for `yamlRestCompatTest -> yamlRestTestV7CompatTest`  is that 
many projects have configured `yamlRestCompatTest` 
but that configuration is specific to the N-1 version. For example, 
if we black list tests when running compatibility with v7, we don't also
want to blacklist those tests when running compatibility with v8.

By introducing a version-specific identifier in the name, the task will not
even exist when bumping the version creating the need to (correctly) remove
the version-specific condition.

The motivation for `transformV7RestTests -> yamlRestTestV7CompatTransform` 
is to provide more consistent naming. 

The idea behind the naming is the main task people
are likely familiar with is :

`yamlRestTest` so we will use that as a base.
`yamlRestTestV7CompatTest` to run the version-specific compat tests
`yamlRestTestV7CompatTransform` to run the version-specific transformations for the compat tests

CI should be un-effected since since we introduced a lifecycle task 
name `checkRestCompat` which is what CI should be configured to use.

### CODE REVIEW

**Review by pgomulka — APPROVED** [review]
LGTM

**Review by mark-vieira — CHANGES_REQUESTED** [review]
Can we change `yamlRestTestV7Compat` to `yamlRestTestV7CompatTest`? Generally the convention is that tasks that execute tests have a "test" suffix. This still aligns well (if not better) with the convention of `yamlRestTestV7CompatTransform` as well.

**Review by breskeby — APPROVED** [review]
Lgtm once marks comment is Adressed and conflicts are resolved

**Comment by jakelandis** [comment]
@mark-vieira  - mind taking another look ?

The names have been updated.

**Review by mark-vieira — APPROVED** [review]
Thanks, Jake. LGTM.

**Pull request merged**
