### PR TITLE
Free bytes reserved on request breaker

### LINKED ISSUE #18144: CircuitBreakingException on extremely small dataset
**Elasticsearch version**: alpha2

**JVM version**: build 1.8.0_74-b02

**OS version**: OS X El Capitan 10.11.3 

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1. Install and run elasticsearch-alpha2, topbeat-alpha2, and kibana-alpha2 (Topbeat is only monitoring the node process on a 20 second interval.)
 2. I am using Kibana to monitor a node process. Here is the query Kibana is using to generate the visualization:

  ```javascript
  {
     "size":0,
     "aggs":{
        "2":{
           "date_histogram":{
              "field":"@timestamp",
              "interval":"30s",
              "time_zone":"America/Los_Angeles",
              "min_doc_count":1
           },
           "aggs":{
              "1":{
                 "max":{
                    "field":"proc.mem.rss"
                 }
              }
           }
        }
     },
     "highlight":{
        "pre_tags":[
           "@kibana-highlighted-field@"
        ],
        "post_tags":[
           "@/kibana-highlighted-field@"
        ],
        "fields":{
           "*":{
           
           }
        },
        "require_field_match":false,
        "fragment_size":2147483647
     },
     "query":{
        "bool":{
           "must":[
              {
                 "query_string":{
                    "query":"*",
                    "analyze_wildcard":true
                 }
              },
              {
                 "match":{
                    "proc.cmdline":{
                       "query":"/Users/tyler/.nvm/versions/node/v4.4.3/bin/node ./bin/../src/cli",
                       "type":"phrase"
                    }
                 }
              },
              {
                 "range":{
                    "@timestamp":{
                       "gte":1462389453519,
                       "lte":1462390353519,
                       "format":"epoch_millis"
                    }
                 }
              }
           ],
           "must_not":[
           
           ]
        }
     }
  }
  ```
 3. Run for about 30 minutes.

I have 1027 documents, and the total size is 1.6MB.

**Provide logs (if relevant)**:

```bash
CircuitBreakingException[[parent] Data too large, data for [<http_request>] would be larger than limit of [726571417/692.9mb]]
	at org.elasticsearch.indices.breaker.HierarchyCircuitBreakerService.checkParentLimit(HierarchyCircuitBreakerService.java:211)
	at org.elasticsearch.common.breaker.ChildMemoryCircuitBreaker.addEstimateBytesAndMaybeBreak(ChildMemoryCircuitBreaker.java:128)
	at org.elasticsearch.http.HttpServer.dispatchRequest(HttpServer.java:109)
	at org.elasticsearch.http.netty.NettyHttpServerTransport.dispatchRequest(NettyHttpServerTransport.java:489)
	at org.elasticsearch.http.netty.HttpRequestHandler.messageReceived(HttpRequestHandler.java:65)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.http.netty.pipelining.HttpPipeliningHandler.messageReceived(HttpPipeliningHandler.java:85)
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:83)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Eventually, all requests to ES will fail with this exception including _stats.

### PR DESCRIPTION
**Pull request by danielmitterdorfer**
With this commit we free all bytes reserved on the request circuit breaker.

Closes #18144

### CODE REVIEW

**Comment by danielmitterdorfer** [comment]
I checked all call sites of the problematic constructor `BytesRestResponse(RestStatus status)` but only `RestMainAction` is affected.

I wonder whether we should remove this constructor entirely in order to avoid this problem in the future. I also thought how we might test this. The best thing that came to my mind was a common base class for all REST action (integration) tests that defines the necessary scaffolding for a circuit breaker test. To the reviewer: Wdyt? Depending on the decision I think it makes sense to create a separate issue then instead of solving this in the context of this ticket / PR.

**Comment by danielmitterdorfer** [comment]
Test Scenario:

1. Issue `curl -XHEAD http://localhost:9200/`
2. Check that all breakers are at zero bytes: `curl -s http://localhost:9200/_nodes/stats | jq '.nodes | keys as $node | {breakers: map(.breakers)}'` (requires `jq`)

**Comment by s1monw** [comment]
> I wonder whether we should remove this constructor entirely in order to avoid this problem in the future

++

**Comment by s1monw** [comment]
@danielmitterdorfer is there a place in our code where we can assert that the breaker size is 0 for instance once we shut down the node or anything like this? Maybe something in the test framework or so?

**Comment by danielmitterdorfer** [comment]
@s1monw: We have the necessary asserts already. I was just thinking whether we should enforce that we always have a test and if yes how (btw, the assert is in `InternalTestCluster#ensureEstimatedStats()`). Nevertheless, I added a test for this specific method now and also removed the constructor.

**Comment by jasontedor** [comment]
> We have the necessary asserts already. 

I would think that if we had the necessary asserts then the build would be failing with the leak in place?

**Comment by danielmitterdorfer** [comment]
@jasontedor It would have failed but we didn't have a test for it yet.

**Comment by s1monw** [comment]
>... It would have failed but we didn't have a test for it yet.
 Show all checks

awesome - thanks for the test..

**Comment by s1monw** [comment]
LGTM

**Comment by danielmitterdorfer** [comment]
Thanks for the review. I'll merge soon.

**Pull request merged**
