### PR TITLE
Add text field support in the Painless scripting fields API

### PR DESCRIPTION
**Pull request by jdconrad**
This change adds access to mapped text fields via the Painless scripting fields API. The values returned from a text field via the scripting fields API always use source as described by (https://github.com/elastic/elasticsearch/issues/81246). Access via the old-style through doc will still depend on field data, so there is no change and avoids bwc issues.

### CODE REVIEW

**Comment by jdconrad** [comment]
@elasticmachine run elasticsearch-ci/part-1

**Review by javanna — APPROVED** [review]
LGTM I think that this change closes effectively the issue you linked. Thanks for working on this, it will make accessing text fields from a script much easier!

**Review by romseygeek — APPROVED** [review]
LGTM too!

**Comment by jdconrad** [comment]
@javanna @romseygeek Thank you both for the review!

**Pull request merged**
