### PR TITLE
Remove Migration Upgrade and Assistance APIs

### PR DESCRIPTION
**Pull request by AthenaEryma**
The Migration Assistance API has been functionally replaced by the
Deprecation Info API, and the Migration Upgrade API is not used for the
transition from ES 6.x to 7.x, and does not need to be kept around to
repair indices that were not properly upgraded before upgrading the
cluster, as was the case in 6.

These APIs are deprecated in 6.7 and this commit removes them.

Follow-up to to https://github.com/elastic/elasticsearch/pull/40072
Relates to https://github.com/elastic/elasticsearch/issues/40014

### CODE REVIEW

**Review by jakelandis — APPROVED** [review]
LGTM

**Comment by gwbrown** [comment]
@jakelandis could you also take a look at the changes in https://github.com/elastic/elasticsearch/pull/40075/commits/4a8b69fc648dca989fdbc03e7448cfca3320c1bf as I had to modify a couple BWC tests? The changes basically just make the test fail if the index needs to be upgraded, which should not happen at any point going 6->7->8 unless we make a change that would make reinstating the Upgrade API necessary.

**Comment by jakelandis** [comment]
Still LGTM

**Comment by gwbrown** [comment]
I opened https://github.com/elastic/elasticsearch/issues/40116 about the CI failure, which does not appear to be related to the changes here.

@elasticmachine run elasticsearch-ci/2

**Comment by gwbrown** [comment]
Thanks for the second review @jakelandis!

**Pull request merged**
