### PR TITLE
Update Azure Service Management API to 0.9.0

### LINKED ISSUE #15209: Update Azure Service Management API to 0.9.0
Azure team released new versions of their Java SDK.

According to https://github.com/Azure/azure-sdk-for-java/wiki/Azure-SDK-for-Java-Features, it comes with 2 versions.
We should at least update to `0.9.0` of V1 but also consider moving to the new APIs (V2).

## API V1

```xml
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>azure-svc-mgmt-compute</artifactId>
    <version>0.9.0</version>
</dependency>
```

## API V2

```xml
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>azure-mgmt-compute</artifactId>
    <version>0.9.0</version>
</dependency>
```

### PR DESCRIPTION
**Pull request by dadoonet**
Azure team released new versions of their Java SDK.

According to https://github.com/Azure/azure-sdk-for-java/wiki/Azure-SDK-for-Java-Features, it comes with 2 versions.
We should at least update to `0.9.0` of V1 but also consider moving to the new APIs (V2).

This commit first updates to latest API V1.

``` xml
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>azure-svc-mgmt-compute</artifactId>
    <version>0.9.0</version>
</dependency>
```

Closes #15209

### CODE REVIEW

**Comment by dadoonet** [comment]
@tlrx Really small change. Can you review?

**Comment by tlrx** [comment]
@dadoonet do you have a link to the changelog and an explanation why the library moves to API V2? I'm curious to know the benefit/tradeoffs of the new version.

**Comment by dadoonet** [comment]
Note that my change does not move to the V2.

And for now, I can't find any documentation on how to adapt from V1 to V2. Some APIs are not there anymore :(

**Comment by tlrx** [comment]
> Note that my change does not move to the V2.

Sure, I'm just asking for a changelog of 0.90.0 V1

**Comment by dadoonet** [comment]
@tlrx 

2015.10.21 Version 0.9.0
* New Azure Resource Manager Storage Management library
* Fix a few bugs

2015.9.22 Version 0.8.3
* Fix unexpected exceptions thrown in some long running operations

2015.9.22 Version 0.8.2
* Revert a previous breaking change on enum casing
* Fix string comparison on long running operation status

2015.9.15 Version 0.8.1
* Use commons library for Base64 encoding

2015.8.21 Version 0.8.0
 * Support token based credentials
 * Support Azure Resource Management


The great news is that we might be able to change auth from certificate based auth to token based auth...
I would prefer doing that in another PR though.

**Comment by tlrx** [comment]
"fix few bugs" I guess it motivates an update... LGTM

**Comment by dadoonet** [comment]
haha! Yeah. The changelog is super obvious...

I guess it basically says: read this: https://github.com/Azure/azure-sdk-for-java/commits/master

**Comment by dadoonet** [comment]
After trying to backport to 2.x branch, I found that some transitive dependencies are actually missing. I need to update gradle build file.
Will push another commit.

**Pull request merged**
