### PR TITLE
fix comment in IndicesAdminClient

### PR DESCRIPTION
**Pull request by sliu1013**
fix comment around prepareOpen method

### CODE REVIEW

**Comment by sliu1013** [comment]
I have signed the above mentioned agreement ，See the attached file for details .  But cla-checker check failed again. 













At 2024-03-23 22:25:52, "cla-checker-service[bot]" ***@***.***> wrote:

❌ Author of the following commits did not sign a Contributor Agreement:
c58aa2c

Please, read and sign the above mentioned agreement if you want to contribute to this project

**Comment by arteam** [comment]
@elasticmachine update branch

**Comment by arteam** [comment]
@sliu1013 Thank you for your interest in contributing to Elasticsearch! 

I believe the commit in this PR is attributed to a different email address than the email address you used to sign the CLA. If you change the commit email address, or sign the CLA with the email address used in the commit, I'd happy to accept your contribution!

**Comment by sliu1013** [comment]
> @sliu1013 Thank you for your interest in contributing to Elasticsearch!
> 
> I believe the commit in this PR is attributed to a different email address than the email address you used to sign the CLA. If you change the commit email address, or sign the CLA with the email address used in the commit, I'd happy to accept your contribution!

**Pull request closed without merging**
