### PR TITLE
Fix AzureHttpHandler bytes range requests support

### PR DESCRIPTION
**Pull request by tlrx**
This change fixes the AzureHttpHandler so that it supports range 
byte requests with ending offsets that go beyond the real blob length, 
like the real Azure service supports.

### CODE REVIEW

**Review by fcofdez — APPROVED** [review]
LGTM

**Review by DaveCTurner — COMMENTED** [review]
Looks ok to me too but I'd like to cover this in the third-party tests too to make sure our behaviour aligns with that of Azure here.

**Comment by tlrx** [comment]
> Looks ok to me too but I'd like to cover this in the third-party tests too to make sure our behaviour aligns with that of Azure here.

It's coming, it's coming :)

**Comment by tlrx** [comment]
A common 3rd party test has been implemented in https://github.com/elastic/elasticsearch/pull/106239, which uncovered another bug on parsing integers/longs in this HTTP handler.

**Review by fcofdez — APPROVED** [review]

**Comment by tlrx** [comment]
Thanks Francisco!

**Pull request merged**
