### PR TITLE
Fix version check for product header check

### PR DESCRIPTION
**Pull request by ldematte**
https://github.com/elastic/elasticsearch/pull/84240 introduced a version-based check to skip product header checks for some buggy versions till 7.17.2
This was changed in https://github.com/elastic/elasticsearch/pull/86196/files as the bugs that prevented the product header  from being emitted were solved completely in 8.x. Unfortunately the change makes test code skip the check completely for v8.
This PR fixes it, making the check run again for all 8.x versions too.

### CODE REVIEW

**Review by williamrandolph — APPROVED** [review]
LGTM

**Comment by ldematte** [comment]
Yes, I have opened https://github.com/elastic/elasticsearch/issues/102928
Seems like some Watcher APIs implemented after 8.8 have this issue.
I am considering to mute the failing test, linking the mute to the open issue, so we can merge this and avoid other APIs to slip through the cracks. What do you think @williamrandolph ?

**Comment by ldematte** [comment]
@elasticmachine update branch

**Comment by ldematte** [comment]
@elasticmachine update branch

**Comment by ldematte** [comment]
@elasticmachine update branch

**Pull request merged**
