### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by muffl0n**
elasticsearch-node unsafe-bootstap -> elasticsearch-node unsafe-bootstrap

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Review by cbuescher — APPROVED** [review]
Hi @muffl0n, thanks for catching this. I will run some tests, but before we can merge this we need you to sign the [contributor license agreement](https://www.elastic.co/de/contributor-agreement), even for small typo changes like this. I will run our CI tests already so we can merge once you signed. Make sure to use the same email when signing as you used in the commit on Github.

**Comment by cbuescher** [comment]
@elasticmachine test this please

**Comment by muffl0n** [comment]
"contributor license agreement" signed

**Comment by cbuescher** [comment]
@muffl0n thanks, will merge to later branches and master as well.

**Pull request merged**
