### PR TITLE
[CI] Reactivate 3rd party tests on CI [2nd]

### PR DESCRIPTION
**Pull request by vladimirdolzhenko**
Initial PR #32315 was not sufficient:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+third-party-tests/31/

It is not possible to reproduce it locally - therefore I ran CI for my branch and got green build:

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+third-party-tests/33/

### CODE REVIEW

**Review by ywelsch — APPROVED** [review]
LGTM

**Comment by vladimirdolzhenko** [comment]
@elasticmachine test this please

**Comment by vladimirdolzhenko** [comment]
@elasticmachine test this please

**Comment by vladimirdolzhenko** [comment]
thanks @ywelsch

**Pull request merged**
