### PR TITLE
Remove redundant import and else statement

### PR DESCRIPTION
**Pull request by pgomulka**
In #48209 PR unused import and redundant else statements were missed. This commit cleans this up

### CODE REVIEW

**Comment by pgomulka** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by pgomulka** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample-matrix

**Comment by pgomulka** [comment]
@elasticmachine update branch

**Review by alpar-t — COMMENTED** [review]
LGTM

**Review by alpar-t — APPROVED** [review]

**Pull request merged**
