### PR TITLE
Build: move generated-resources to build

### PR DESCRIPTION
**Pull request by jaymode**
This commit moves the generated-resources directory to be within
the build directory for the openldap-tests and saml-idp-tests
projects. Both projects create a generated-resources directory that
should have been in the build directory but were instead at the same
level as the build directory.

### CODE REVIEW

**Review by jasontedor — COMMENTED** [review]
Would it work to add `generated-resources/` to the root `.gitignore`?

**Comment by rjernst** [comment]
Please don't add it to gitignore. `generated-resources` should be under `build`

**Comment by jaymode** [comment]
good point @rjernst, this now changes the output dir location

**Comment by jasontedor** [comment]
Ah, much better. Thanks @rjernst.

**Review by jasontedor — APPROVED** [review]
LGTM.

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by jaymode** [comment]
run gradle build tests

**Pull request merged**
