### PR TITLE
strict_date_optional_time to print nanoseconds

### LINKED ISSUE #67063: Improve default format for date_nanos fields
By default, `date_nanos` fields use the `strict_date_optional_time` format. Unfortunately `strict_date_optional_time` accepts and parses dates with nanosecond precision, but when it formats it drops the nanoseconds.

Some search options like `fields` and `docvalue_fields` use the field's format by default to format + return values. This leads to confusing behavior for `date_nanos` fields, where the values are missing nanosecond precision.

It would be good to update the default format for `date_nanos` fields to one that always preserves nanoseconds.

Example reproduction:
```
PUT index 
{
  "mappings": {
    "properties": {
      "@timestamp": {
        "type": "date_nanos"
      }
    }
  }
}

PUT index/_doc/1
{
  "@timestamp": "2019-09-22T23:50:13.253123345Z"
}

GET index/_search
{
  "fields": ["@timestamp"]
}
```

### PR DESCRIPTION
**Pull request by pgomulka**
strict_date_optional_time is allowing to parse nanoseconds up to 9digis,
but is only printing up to 3digits.
This is enought for date field, but not sufficient for date_nanos
This commit is chaning the printer in `strict_date_optional_time` to
print up to 9 digits

closes #67063

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by mark-vieira** [comment]
@elasticmachine update branch

**Comment by pgomulka** [comment]
ok to test

**Comment by pgomulka** [comment]
ok to run

**Comment by pgomulka** [comment]
closed in favour of https://github.com/elastic/elasticsearch/pull/70463/files

**Pull request closed without merging**
