### PR TITLE
The `delimited_payload_filter` token filter has been renamed to `delimited_payload`

### LINKED ISSUE #21978: Rename `delimiter_payload_filter` to `delimiter_payload`.
This pre-built token filter is inconsistent with other pre-built token filters since it includes `filter` in its name while the other ones don't.

### PR DESCRIPTION
**Pull request by alexshadow007**
Closes #21978

### CODE REVIEW

**Comment by makeyang** [comment]
very sorry to bother here. but when I take a look at the code, I couldn't stop thinking that tokenFilters.register("stop", StopTokenFilterFactory::new) 
should be refactoried this way:
tokenFilters.register(StopTokenFilterFactory.getName(), StopTokenFilterFactory::new)

**Comment by jpountz** [comment]
@alexshadow007 Thanks, the rename looks good. However I think we should have a backward compatibility layer so that `delimited_payload_filter` can still be used on 5.x indices. In order to not break templates, it should also work on 6.x, but with a deprecation warning recommending to switch to `delimited_payload`.

**Comment by jpountz** [comment]
@makeyang I am personally happy the way things are today. What would the `StopTokenFilterFactory.getName` bring?

**Comment by makeyang** [comment]
@jpountz define once and reference anywhere. if use getName, part of GetTermVectorsIT.java and all the IndexLookupIT.java won't be needed to modified.

**Comment by rjernst** [comment]
@alexshadow007 Are you interested in making the backcompat change @jpountz suggested?

**Comment by dakrone** [comment]
Closing as there has been no feedback, feel free to comment if this was closed erroneously.

**Pull request closed without merging**
