### PR TITLE
For constant_keyword, make sure exists query handles missing values.

### LINKED ISSUE #53545: exists query returns no documents for a no-value constant_keyword
Considering the following mapping

```
{
  "mappings": {
    "properties": {
      "cycle_type": {
        "type": "constant_keyword"
      },
      "name": {
        "type": "text"
      }
    }
  }
}
```

And the following bulk of documents:

```
{"index":{"_id":1}}
{"name":"kawasaki"}
{"index":{"_id":2}}
{"name":"1938"}
{"index":{"_id":3}}
{"name":"1924"}
```

there won't be any value associated with `cycle_type` field. But, running the following query has some unexpected results:

```
{
    "query": {
        "bool": {
            "must_not": [
                {
                    "exists": {
                        "field": "cycle_type"
                    }
                }
            ]
        }
    }
}
```

There won't be any documents returned, whereas it should return all of them because `cycle_type` doesn't have a value.

### PR DESCRIPTION
**Pull request by jtibshirani**
It's possible for a constant_keyword to have a 'null' value before any documents
are seen that contain a value for the field. In this case, no documents have a
value for the field, and 'exists' queries should return no documents.

Fixes #53545.

### CODE REVIEW

**Review by cbuescher — COMMENTED** [review]
The change in itself looks good to me. 

Just a short clarifying question/remark: with this behaviour, the moment the first document is indexed that sets the constant fields value, all previously indexed documents will also show up in an "exists" query for that field. This might be suprising for some users, so maybe a short remark in the docs is in order? I also wonder if the current behaviour (always returning all docs regardless of a set value) isn't less suprising. The act of adding a "constant" field to the mapping by the user might be considered as meaning "this field exists on all documents across the board"? Would that also make sense to you? I'm torn which behaviour I would prefer as a user, maybe someone else should also weigh in on this.

**Comment by jtibshirani** [comment]
Thanks @cbuescher for reviewing! I'd also be happy if others weighed in.

My understanding of exists queries is that they check if a document contains a value for a field. If the value is missing or null, it won't be returned. I think of an exists query as being semantically equivalent to a wildcard query on `*` -- for `constant_keyword`, wildcard queries will always return no documents if the value is not set.

**Review by jimczi — APPROVED** [review]
LGTM, should we add a small note in the docs to explain this behavior ?

**Comment by jtibshirani** [comment]
@elasticmachine run elasticsearch-ci/bwc
@elasticmachine run elasticsearch-ci/default-distro

**Review by cbuescher — APPROVED** [review]
@jtibshirani thanks for your thought, just wanted to run these thoughts past you.

**Pull request merged**
