### PR TITLE
Add delta for double comparison in AvgAggregatorTests.testSummationAccuracy

### LINKED ISSUE #69906: Intermittent failures in AvgAggregatorTests.testSummationAccuracy
**Build scan**: https://gradle-enterprise.elastic.co/s/4bgrkkfsgiqtc

**Repro line**: `./gradlew ':server:test' --tests "org.elasticsearch.search.aggregations.metrics.AvgAggregatorTests.testSummationAccuracy" -Dtests.seed=47E5CB285BFE9D30 -Dtests.security.manager=true -Dtests.locale=ar-OM -Dtests.timezone=Etc/GMT-3 -Druntime.java=11`

**Reproduces locally?**: Yes

**Applicable branches**: failed in 7.12 but likely applies to other branches, too

**Failure history**: Intermittently due to zero delta on double comparison. See [build stats](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-1y,mode:quick,to:now))&_a=(columns:!(project),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:e58bf320-7efd-11e8-bf69-63c8ef516157,key:project,negate:!f,params:(query:elasticsearch,type:phrase),type:phrase,value:elasticsearch),query:(match:(project:(query:elasticsearch,type:phrase))))),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:testSummationAccuracy),sort:!(time,desc))).

**Failure excerpt**:
```

java.lang.AssertionError: expected:<0.9> but was:<0.9000000000000001>
at __randomizedtesting.SeedInfo.seed([47E5CB285BFE9D30:1E2C39F070624343]:0) |  
-- | --
  |   | at org.junit.Assert.fail(Assert.java:88) |  
  |   | at org.junit.Assert.failNotEquals(Assert.java:834) |  
  |   | at org.junit.Assert.assertEquals(Assert.java:553) |  
  |   | at org.junit.Assert.assertEquals(Assert.java:683) |  
  |   | at org.elasticsearch.search.aggregations.metrics.AvgAggregatorTests.lambda$verifyAvgOfDoubles$24(AvgAggregatorTests.java:250) |  
  |   | at org.elasticsearch.search.aggregations.AggregatorTestCase.testCase(AggregatorTestCase.java:545) |  
  |   | at org.elasticsearch.search.aggregations.metrics.AvgAggregatorTests.testAggregation(AvgAggregatorTests.java:566) |  
  |   | at org.elasticsearch.search.aggregations.metrics.AvgAggregatorTests.verifyAvgOfDoubles(AvgAggregatorTests.java:244) |  
  |   | at org.elasticsearch.search.aggregations.metrics.AvgAggregatorTests.testSummationAccuracy(AvgAggregatorTests.java:191)


```

### PR DESCRIPTION
**Pull request by danhermann**
Fixes #69906.

### CODE REVIEW

**Comment by nik9000** [comment]
Should the kahan summation compensation prevent needing this? I don't know enough about the summation to know if merging this is hiding a bug or silencing a bad assumption.

**Comment by danhermann** [comment]
> Should the kahan summation compensation prevent needing this? I don't know enough about the summation to know if merging this is hiding a bug or silencing a bad assumption.

@nik9000, I'd welcome feedback from others on your team because I certainly don't know the answer to that question. This is my relatively naive attempt to resolve what appears to be an intermittent failure on the test.

**Comment by nik9000** [comment]
OK. I tried to tempt folks to learn about Kahan summations and couldn't get any takers. So I'm gonna go read for a bit.

**Comment by danhermann** [comment]
Closing in favor of https://github.com/elastic/elasticsearch/pull/69932

**Pull request closed without merging**
