### PR TITLE
upgrade to lucene-8.6.0-snapshot-6a715e2ecc3

### PR DESCRIPTION
**Pull request by iverase**
New Lucene snapshot. release branch.

### CODE REVIEW

**Review by dnhatn — APPROVED** [review]
LGTM

**Comment by dnhatn** [comment]
@elasticmachine update branch

**Review by jpountz — APPROVED** [review]

**Comment by iverase** [comment]
@elasticmachine update branch

**Comment by iverase** [comment]
@elasticmachine run elasticsearch-ci/2

**Pull request merged**
