### PR TITLE
Shard Started messages should be matched using an exact match

### PR DESCRIPTION
**Pull request by bleskes**
When a node sends a shard started message to the master, the master goes through the routing table looking for the shard to start. At the moment we validate the indexUUID, the node the shard is assigned to and the fact that the shard is initializing. This check goes wrong if a relocating replica shard finishes recovery just at the moment the source node  leaves the cluster. In this case the master will cancel the recovery and will likely assign a new initializing replica to the same target node. In this case the message from the relocation recovery can activate the new replica wrongfully.

Also, the logic for decided whether an incoming shard started message will be applied was split between ShardStateAction and the AllocationService.  
This commit does the following:
1) Let ShardStateAction only filter basic stuff like index existence and indexUUID.
2) Move the trickier shard started matching logic to the AllocationService and make it stricter
3) Unify ShardStateAction filtering logic for both shard started and shard failed.
4) Add unit tests for all of the above.

For an example test failure see: http://build-us-00.elastic.co/job/es_core_16_centos/388/

### CODE REVIEW

**Comment by bleskes** [comment]
@kimchy can you take a look?

**Comment by kimchy** [comment]
LGTM

**Comment by kimchy** [comment]
@bleskes should we backport to 1.7 as well here?

**Comment by bleskes** [comment]
@kimchy I think that makes sense. This is a bug fix and it's good to keep this logic similar as much as we can (give the other work around shard allocation goes into 1.x). I will give @s1monw some time to voice his opinion ...

**Comment by bleskes** [comment]
I pushed this to master. If I don't hear any objection by tomorrow, I'll back port to 1.7 as well...

**Comment by bleskes** [comment]
pushed this to 1.7 as well..

**Pull request closed without merging**
