### PR TITLE
Deprecate Telemetry / APM legacy settings in favor of the new telemetry.* settings

### PR DESCRIPTION
**Pull request by mosche**
#104345 and #104376 introduced new, less ambiguous telemetry / APM settings names.
This PR deprecates the old `tracing.apm.*` legacy settings in favor of `telemetry[.tracing].*`.

### CODE REVIEW

**Review by stu-elastic — APPROVED** [review]
Code is good, approved pending breaking change review

**Comment by mosche** [comment]
Currently pending, depends on breaking change proposal https://github.com/elastic/dev/issues/2481

**Comment by mosche** [comment]
After closing https://github.com/elastic/elasticsearch/pull/106997 as invalid, I'm wrapping up this. 
The deprecation / breaking change is approved (2481).

**Comment by mosche** [comment]
kind ping @pgomulka, could you have a look

**Review by pgomulka — APPROVED** [review]
LGTM

**Pull request merged**
