### PR TITLE
Can we expose keytab location for kerberos-enabled HDFS Repository?

### PR DESCRIPTION
**Pull request by wuyunfeng**
**scenarios**: When ES running on container such as docker or k8s environment through building ES image（already contains `config`、`lib`、`bin` directory etc.）

**problem** : it is difficult or tremendous tedious to put the `keytab file`  into the `hdfs-repository` plugin's `config` folder for our deploy system. 

**Optional way ?**:
Can we specify the location of the `keytab` file explicitly?  In this way, we can put the `keytab` file into ES data path (which always a Volume mounted on container) or somewhere else which mounted on ES container（etc. Apache Ambari can manage keytab file for those service）, ES instance can dynamically load the keytab file for kerberos's authentication, and then we do not need to update our ES image.
Whether it is reasonable for add this configuration item (security.keytab) ?

### CODE REVIEW

**Comment by wuyunfeng** [comment]
@mark-vieira   Whether it is reasonable for add this configuration item (security.keytab) ?

**Comment by mark-vieira** [comment]
> problem : it is difficult or tremendous tedious to put the keytab file into the hdfs-repository plugin's config folder for our deploy system.

@wuyunfeng Could you provide more detail about your particular system that makes this difficult? Why can't you mount the keytab file into the container as you do for other things like the ES data directory?

**Comment by wuyunfeng** [comment]
@mark-vieira  The deploy system is written by ourself which work against the k8s . It is responsible for the deploy-system to generate config file, mount the local data disk into container, and create/start/stop/destroy particular service like Spark, Elasticsearch etc.

  1. Just more flexible(Spark user can submit  keytab file during creating the job)

At the beginning,  the Kerberos Authentication is not enabled on our or our user's HDFS，and we do not realize  someday that our departments or customer would enable the  Kerberos.  Even worse，we  do not mount（which should be done at the container create-phase） other data path into ES container's config direcotry(`keytab` file must exists on the `config/hdfs-repository` directory),  and the we must modify the service's k8s  configuration and add extra mounting path. 

2. Elasticsearch cluster may snapshot their index on different HDFS cluster which on the different      KDC realm

In this way , we can assign different keytab file for different kerberos-enabled HDFS cluster which need not merge those keytab file into one（maybe it is not reasonable merge different realm keytab file into one), because of elasticsearch just read  the `krb5.keytab` named file.

**Comment by atorok** [comment]
I don't think this will work as the security manager won't allow accessing the files outside of the config dir. 
@elasticmachine test this please

**Comment by wuyunfeng** [comment]
@atorok  I  think of the security manager, so I do not know whether  it is  reasonable for add this configuration.

**Comment by wuyunfeng** [comment]
@atorok 
I just put the keytab file on /tmp/* or  ES data path, and the `hdfs-repository` can read it content without other permission.

**Comment by wuyunfeng** [comment]
@atorok Yes Indeed. Sorry for thoughtless, I run `create repo` on  one kerberos-enabled HDFS,  and security exception was throw. 
Why the plugin can read  `$CONFIG_DIR$/repository-hdfs/krb5.keytab` without extra permission?

Maybe I should mount another `path-to-keytab` dir  into  `$CONFIG_DIR$/repository-hdfs/`  during the container creating.

**Comment by atorok** [comment]
@wuyunfeng  Thanks very much for your interest in Elasticsearch.

This appears to have turned into a user question, and we'd like to direct these kinds 
of things to the [forums](https://discuss.elastic.co/). If you can stop 
by there, we'd appreciate it. This allows us to use GitHub for verified 
bug reports, feature requests, and pull requests.

There's an active community in the [forums](https://discuss.elastic.co/)
that should be able to help get an answer to your question. As such, I 
hope you don't mind that I close this.

**Pull request closed without merging**
