### PR TITLE
In asciidoc made the same length of opening and closing lines

### PR DESCRIPTION
**Pull request by greenx**
Hi, 
A few weeks I will experience problems with access to the site elastic.co
So I wanted to compile offline documentation with asciidoctor.
```
asciidoctor -d book -D ./docs/ ./elasticsearch/docs/reference/index.asciidoc
```

The first thing I had to pay attention to was incorrectly designed blocks of code.
In some places, the start and end marker are of different lengths.
Therefore asciidoctor once started a block of code and continued it to the end of the document. Ignore the end marker. Because It is of a different length.

### CODE REVIEW

**Comment by karmi** [comment]
Hi @greenx, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/elasticsearch/pull/23583.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by greenx** [comment]
added

**Comment by nik9000** [comment]
> asciidoctor

We build with `asciidoc`, not `asciidoctor`. I expect all kinds of things to fail with `asciidoctor`.

**Comment by greenx** [comment]
There are not so many of them:
asciidoctor: WARNING: search/request/scroll.asciidoc: line 68: no callouts refer to list item 1
asciidoctor: WARNING: aggregations/bucket/diversified-sampler-aggregation.asciidoc: line -1: no callouts refer to list item 2
asciidoctor: WARNING: indices/flush.asciidoc: line 117: no callouts refer to list item 1
asciidoctor: ERROR: index-modules.asciidoc: line 50: illegal block content outside of partintro bloc

I understand that there is no software without errors. Therefore, I'm still looking for authoritative sources of documentation on asciidoc.

**Comment by greenx** [comment]
So, in asciidoctor burns that, 
1. Delimiter lines must be balanced.
http://asciidoctor.org/docs/user-manual/#delimiter-lines

2. The callout number (at the target) must be placed at the end of the line. 
http://asciidoctor.org/docs/user-manual/#callouts

**Comment by rjernst** [comment]
Thanks @greenx

**Pull request merged**
