### PR TITLE
Avoid breaking add/clear voting exclusions

### PR DESCRIPTION
**Pull request by henningandersen**
Adding and clearing voting exclusions is part of the steps an operator/orchestration
will take to change topology of a cluster. It is therefore important that as much as
possible these do not fail, and we therefore now bypass the circuit breaker for the
associated rest and transport actions.

### CODE REVIEW

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Comment by idegtiarenko** [comment]
Should this also target 8.2.x?

**Review by idegtiarenko — APPROVED** [review]

**Comment by henningandersen** [comment]
Failure looks like #86666, already fixed.

**Comment by henningandersen** [comment]
@elasticmachine update branch

**Comment by henningandersen** [comment]
Thanks David and Ievgen!

**Pull request merged**
