### PR TITLE
Prevent types deprecation warning for indices.exists requests

### LINKED ISSUE #43905: Indices Exists API missing include_type_name in REST API spec
### Issue

Relates: https://github.com/elastic/elasticsearch-net/issues/3901

The REST API spec for indices.exists.json is missing `include_type_name` in 6.8.0:

https://github.com/elastic/elasticsearch/blob/12632795cdeb57a9092da4a0508f58424c5d7fc6/rest-api-spec/src/main/resources/rest-api-spec/api/indices.exists.json#L16-L42

Sending an index exists request without `include_type_name` results in a Deprecation Warning HTTP header being returned:

Request

```
HEAD http://127.0.0.1:9200/foo HTTP/1.1
Accept: application/json
Content-Type: application/json
Host: 127.0.0.1:9200
Connection: Keep-Alive
```

Response

```
HTTP/1.1 200 OK
Warning: 299 Elasticsearch-6.8.1-1fad4e1 "[types removal] The parameter include_type_name should be explicitly specified in get indices requests to prepare for 7.0. In 7.0 include_type_name will default to 'false', which means responses will omit the type name in mapping definitions."
content-type: application/json; charset=UTF-8
content-length: 225
```

Sending a request with `include_type_name=true` or `include_type_name=false` results in no Deprecation Warning.

### Feature

The indices.exists.json REST API spec should include `include_type_name` in the list of params, so that clients that generate API methods from the spec pick this up.

### PR DESCRIPTION
**Pull request by cbuescher**
Currently we log a deprecation warning to the types removal in
RestGetIndicesAction even if the REST method is HEAD, which is used by the
indices.exists API. Since the body is empty in this case we should not show
the deprecation warning.

Closes #43905

### CODE REVIEW

**Comment by cbuescher** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by cbuescher** [comment]
@elasticmachine run elasticsearch-ci/2

**Review by jtibshirani — APPROVED** [review]
Looks good to me!

**Comment by cbuescher** [comment]
@jtibshirani thanks, will backport to the active 7.x branches and 6.8 where I think its mostly needed

**Pull request merged**
