### PR TITLE
Fix ComposableIndexTemplate equals when composed_of is null

### PR DESCRIPTION
**Pull request by weizijun**
when composed_of is null, the ComposableIndexTemplate will return an empty list. it will cause the input and output ComposableIndexTemplate not equals.

reproduce:
in ComposableIndexTemplateTests.randomInstance method, make `List<String> componentTemplates = null;`, there are the failed tests:
```
Tests with failures:
 - org.elasticsearch.cluster.metadata.MetadataIndexTemplateServiceTests.testAddIndexTemplateV2
 - org.elasticsearch.cluster.metadata.MetadataIndexTemplateServiceTests.testRemoveMultipleIndexTemplateV2Wildcards
 - org.elasticsearch.cluster.metadata.MetadataIndexTemplateServiceTests.testUpdateIndexTemplateV2
 - org.elasticsearch.cluster.metadata.MetadataIndexTemplateServiceTests.testRemoveMultipleIndexTemplateV2
```

the PR add a `componentTemplatesEquals` method to make null and empty list equals .

### CODE REVIEW

**Comment by weizijun** [comment]
hi, @dakrone, can you help to review this PR?

 I push a PR(https://github.com/elastic/elasticsearch/pull/77008) before about mapping equals, and I find another not equals case.

**Comment by dakrone** [comment]
@elasticmachine update branch

**Comment by dakrone** [comment]
@elasticmachine ok to test

**Comment by dakrone** [comment]
@elasticmachine update branch

**Review by dakrone — APPROVED** [review]
LGTM, I'll merge this in.

**Comment by weizijun** [comment]
> LGTM, I'll merge this in.

Thanks @dakrone

**Pull request merged**
