### PR TITLE
Default distro run creates elastic-admin user

### PR DESCRIPTION
**Pull request by jaymode**
When using gradle run by itself, this uses the default distro with a
basic license and enables security. There is a setup command to create
a elastic-admin user but only when the license is a trial license. Now
that security is available with the basic license, we should always run
this command when using the default distribution.

### CODE REVIEW

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by jaymode** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by jaymode** [comment]
@elasticmachine update branch

**Comment by jpountz** [comment]
@jaymode I'm removing the "backport pending" label as this seems to have been backported already?

**Pull request merged**
