### PR TITLE
Log and track open/close of transport connections

### PR DESCRIPTION
**Pull request by DaveCTurner**
Transport connections between nodes remain in place until one or other
node shuts down or the connection is disrupted by a flaky network.
Today it is very difficult to demonstrate that transient failures and
cluster instability are caused by the network even though this is often
the case. In particular, transport connections open and close without
logging anything, even at `DEBUG` level, making it very hard to quantify
the scale of the problem or to correlate the networking problems with
external events.

This commit adds the missing `DEBUG`-level logging when transport
connections open and close, and also tracks the total number of
transport connections a node has opened as a measure of the stability of
the underlying network.

### CODE REVIEW

**Review by original-brownbear — APPROVED** [review]
LGTM thanks :) I can see how this will come in handy

**Review by original-brownbear — CHANGES_REQUESTED** [review]
Premature LGTM :) the REST test doesn't parse correctly it seems.

**Comment by DaveCTurner** [comment]
Incorrectly guessed the YAML syntax for an empty map. All ok now @original-brownbear.

**Review by original-brownbear — APPROVED** [review]
LGTM

**Pull request merged**
