### PR TITLE
Minimize USE_ZEN2 setting usage

### PR DESCRIPTION
**Pull request by andrershov**
Since all the tests are migrated to Zen2, we want to minimize USE_ZEN2
setting usage, to make it clear that the default value of true is used.
We still have some tests, that make use of `getUseZen2`, which is set
to true, however, when you look for USE_ZEN2 setting usage, these tests
introduce noise.

This setting should only be used in Zen1IT (which checks the Zen1 -
Zen2 mixed cluster) and in the test framework (and will be completely
removed once Zen1 support is removed).

### CODE REVIEW

**Review by DaveCTurner — APPROVED** [review]
LGTM, but seems to be failing precommit right now.

**Comment by andrershov** [comment]
run elasticsearch-ci

**Comment by andrershov** [comment]
run tests

**Comment by andrershov** [comment]
run elasticsearch-ci/1

**Comment by andrershov** [comment]
run elasticsearch-ci/2

**Comment by andrershov** [comment]
run elasticsearch-ci/default-distro

**Comment by DaveCTurner** [comment]
These changes were incorporated into #38414 it seems.

**Pull request closed without merging**
