### PR TITLE
Refactor IndicesRequestCache to make it testable.

### PR DESCRIPTION
**Pull request by s1monw**
This commit moves IndicesRequestCache into o.e.indics and makes all API in this
class package private. All references to SearchReqeust, SearchContext etc. have been factored
out and relevant glue code has been added to IndicesService. The IndicesRequestCache is not a
simple class without any hard dependencies on ThreadPool nor SearchService or IndexShard. This now
allows to add unittests.
This commit also removes two settings `indices.requests.cache.clean_interval` and `indices.fielddata.cache.clean_interval`
in favor of `indices.cache.clean_interval` which cleans both caches.

### CODE REVIEW

**Comment by s1monw** [comment]
@jpountz  can you review that please

**Comment by jpountz** [comment]
The change looks good.

I'm not too sure about the merge of the clean interval setting. I would rather remove this setting entirely given that it makes little sense since those caches cannot become stale.

**Comment by s1monw** [comment]
> I'm not too sure about the merge of the clean interval setting. I would rather remove this setting entirely given that it makes little sense since those caches cannot become stale.

you mean just have it fixed to 1 min?

**Comment by jpountz** [comment]
Oh sorry, this setting does not do what I thought it did. I thought it would remove all entries from the cache.

LGTM then.

**Pull request merged**
