### PR TITLE
AbstractByteReference: use primitive integer to cache the hash code

### PR DESCRIPTION
**Pull request by arteam**
Instead of using a null reference to `Integer` to check whether the hash code has been calculated, we can use an `int` primitive set to zero. It's very rare that a calculated hash is equal to zero, so that's an acceptable trade-off. `java.lang.String` and Lombok use the same approach for caching hash codes.

Using an int primitive saves 16 bytes of memory for every byte reference with the calculated hash code

With Integer
```
org.elasticsearch.common.bytes.ZeroBytesReference@2a33fae0d footprint:
     COUNT       AVG       SUM   DESCRIPTION
         1        16        16   java.lang.Integer
         1        24        24   org.elasticsearch.common.bytes.ZeroBytesReference
         2                  40   (total)
```

With int
```
org.elasticsearch.common.bytes.ZeroBytesReference@2a33fae0d footprint:
     COUNT       AVG       SUM   DESCRIPTION
         1        24        24   org.elasticsearch.common.bytes.ZeroBytesReference
         1                  24   (total)
```

### CODE REVIEW

**Comment by henningandersen** [comment]
It makes sense to not have an external `Integer` object, but I thinkg if we should add a boolean like `java.lang.String` does to avoid unfortunate degenerate cases. That does eat up 4 of the saved 16 bytes, but I would prefer that.

**Comment by original-brownbear** [comment]
> but I thinkg if we should add a boolean like

++ @arteam let's add that boolean. If we hit a degenerate case for some specific scenario (e.g. when using these as hash keys) we'll never know what hit us otherwise.

**Comment by arteam** [comment]
@elasticmachine run elasticsearch-ci/packaging-tests-unix-sample

**Comment by arteam** [comment]
@elasticmachine update branch

**Comment by arteam** [comment]
@elasticmachine update branch

**Comment by arteam** [comment]
@elasticmachine update branch

**Review by original-brownbear — APPROVED** [review]
LGTM

**Comment by arteam** [comment]
@elasticmachine run elasticsearch-ci/packaging-tests-windows-sample

**Pull request merged**
