### PR TITLE
updated RestAliasAction to take list of aliases

### PR DESCRIPTION
**Pull request by kunal642**
relates to #23661

### CODE REVIEW

**Comment by javanna** [comment]
hi @kunal642 thanks but there's already a PR open (under review) for the same issue. See #23698 .

**Comment by kunal642** [comment]
@javanna Can we have a label which can indicate if the issue is already taken and had a PR for the same.
Or can the issue be assigned to the respective person

**Comment by javanna** [comment]
hi @kunal642 I don't think we can assign issues to external contributors. We discussed before removing the adoptme label once something is taken, but it happened before that the contributor didn't complete the task so we prefer to leave the label. We could introduce another label, but I personally don't see its value. When you start working on an issue, if you scroll through it you can easily see whether there's a PR linked to it or not. What do you think @clintongormley ?

**Comment by clintongormley** [comment]
> When you start working on an issue, if you scroll through it you can easily see whether there's a PR linked to it or not. 

+1

**Pull request closed without merging**
