### PR TITLE
ESQL: Use exact attributes for data source extraction

### LINKED ISSUE #99183: ESQL: Error when loading `text` fields from indexes with synthetic source
ESQL loads `text` fields that are either stored in the index (having `"store": true` in the mapping) or by parsing the `_source` and extracting the text value.  Text fields support [synthetic _source](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-source-field.html#synthetic-source) if one of the two requirements are met:

1. the text field sets  `"store": true`  in the mapping
1. they have a [keyword](https://www.elastic.co/guide/en/elasticsearch/reference/current/keyword.html#keyword-synthetic-source) sub-field that supports synthetic _source 

In the latter case (when `text` field is not stored, but contains a `keyword` sub-field) querying for the `text` field returns an `IllegalArgumentException` with the following error message: `Cannot access source from scripts in synthetic mode`

### Steps to Reproduce

Run the following yaml test:

```yaml
---
"text with synthetic source":
  - do:
      indices.create:
        index: test2
        body:
          mappings:
            _source:
              mode: synthetic
            properties:
              "emp_no":
                type: long
              name:
                type: keyword
              job:
                type: text
                fields:
                  raw:
                    type: keyword

  - do:
      bulk:
        index: test2
        refresh: true
        body:
          - { "index": { } }
          - { "emp_no": 10, "name": "Jenny", "job": "IT Director" }
          - { "index": { } }
          - { "emp_no": 20, "name": "John", "job": "Payroll Specialist" }

  - do:
      esql.query:
        body:
          query: 'from test2 | sort emp_no | keep job'

  - match: { columns.0.name: "job" }
  - match: { columns.0.type: "text" }

  - length: { values: 2 }
  - match: { values.0.0: "IT Director" }
  - match: { values.1.0: "Payroll Specialist" }
```

Returns the following error: 

```
java.lang.IllegalArgumentException: Cannot access source from scripts in synthetic mode
    at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.index.query.SearchExecutionContext.lambda$lookup$2(SearchExecutionContext.java:400)
    at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.search.lookup.SearchLookup.getSource(SearchLookup.java:144)
    at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.index.fielddata.SourceValueFetcherSortedBinaryIndexFieldData$SourceValueFetcherSortedBinaryDocValues.advanceExact(SourceValueFetcherSortedBinaryIndexFieldData.java:113)
    at org.elasticsearch.compute.lucene.BlockDocValuesReader$BytesValuesReader.read(BlockDocValuesReader.java:525)
    at org.elasticsearch.compute.lucene.BlockDocValuesReader$BytesValuesReader.readValuesFromSingleDoc(BlockDocValuesReader.java:520)
    at org.elasticsearch.compute.lucene.ValuesSourceReaderOperator.loadFromManyLeaves(ValuesSourceReaderOperator.java:105)
    at org.elasticsearch.compute.lucene.ValuesSourceReaderOperator.process(ValuesSourceReaderOperator.java:89)
    at org.elasticsearch.compute.operator.AbstractPageMappingOperator.getOutput(AbstractPageMappingOperator.java:67)
    at org.elasticsearch.compute.operator.Driver.runSingleLoopIteration(Driver.java:163)
    at org.elasticsearch.compute.operator.Driver.run(Driver.java:115)
    at org.elasticsearch.compute.operator.Driver$1.doRun(Driver.java:259)
    at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
    at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
    at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983)
    at org.elasticsearch.server@8.11.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
    at java.base/java.lang.Thread.run(Thread.java:1623)
```

### PR DESCRIPTION
**Pull request by luigidellaquila**
Fixes https://github.com/elastic/elasticsearch/issues/99183

ValueSources will now use exact attributes (ie. exact subfields) when available. 
This will make the extraction faster (eg. using a KEYWORD subfield instead of loading a TEXT value from _source) and will avoid failures in case the original field is not available at all, eg. in case of synthetic source.

### CODE REVIEW

**Review by alex-spies — APPROVED** [review]
LGTM

**Comment by astefan** [comment]
The PR looks good, but:
- it is not clear to me what is the range of use cases this change should cover. I see you have modified a single test where the field  starts to be visible in the results in case the source in synthetic. If the range of use cases is more broad, please add more tests.
- the second point is probably similar to the first one. From the test you changed, if `job` has **two exact sub-fields** this query `from test | where job like \"P*\"` will behave differently. If there is a single exact field then the query works and returns something that makes sense and no warnings. If there are two exact sub-fields then the query doesn't return anything and the warning message (in headers) says: `"Field [job] cannot be retrieved, it is unsupported or not indexed; returning null"`. I don't fully agree with this message because the fact that there are two sub-fields it doesn't make this field unsupported, just that **the user needs to be more specific on which sub-field the query should use**. At that point, if the information is more accurate in the warning message, the user can change the query to `from test | where job.raw1 like \"P*\"` and the query succeeds at that point.

**Comment by luigidellaquila** [comment]
Thank you for checking it @astefan 

> it is not clear to me what is the range of use cases this change should cover. I see you have modified a single test where the field starts to be visible in the results in case the source in synthetic. If the range of use cases is more broad, please add more tests.

The problem is very specific to the situation with synthetic source, a `text` field and a keyword subfield. All the other cases are not supported yet (extracting from source types different from `text`) or already managed (no exact subfield, that just returns null).

> if job has two exact sub-fields this query from test | where job like \"P*\" will behave differently. [...]  I don't fully agree with this message because the fact that there are two sub-fields it doesn't make this field unsupported, just that the user needs to be more specific on which sub-field the query should use

There is a generic problem with exact fields in QL: `EsField.getExactInfo()` only tells us if there is an exact subfield, but it takes into account only a "formal exactness", ie. that the subfield is `KEYWORD` and that there is only one, and does not consider other factors (eg. the fact that the subfield could be truncated or not represent the original value exactly). `EsField.getExactInfo/field()` is used in a few other places (eg. in the optimizer), so this specific problem is not strictly related to this PR, that is using the available API correctly; it's a problem of the API itself, that needs to be fixed in QL, and it doesn't seem trivial, so it definitely deserves separate investigation and a dedicated PR.

Even if I try to extract information from EsField.getProperties(), I'll still not have enough information to give the user correct suggestions. None of the subfields could be a valid one if all of them have a different content than the original field; a query like `from test | where job.raw1 like \"P*\"` could have a completely different meaning from the original one; the original value of `job` could be completely lost (ie. `not indexed` as the message says) and there could just be no way to query it.

I still have doubts about that message `"Field [job] cannot be retrieved, it is unsupported or not indexed; returning null"`, there are so many corner cases that can fail, that `it is unsupported or not indexed` seems a bit guessing. We could decide to make it just `"Field [job] cannot be retrieved; returning null"`, but it risks to be even less informative for the end user in the most common cases.

**Comment by astefan** [comment]
>  so it definitely deserves separate investigation and a dedicated PR.
agreed

I know this scenario is very open ended and I hope we can discuss this in a wider audience.
There is another aspect here: the information about the exact variants... should be a warning or an error message. No need to answer now, just something more to discuss.

Please, open an issue about improving the way we deal with exact variants of non-exact fields, plus the warning vs. error message aspect and link it to this PR.

**Comment by luigidellaquila** [comment]
Done https://github.com/elastic/elasticsearch/issues/99899

**Review by astefan — APPROVED** [review]
LGTM

**Pull request merged**
