### PR TITLE
Add parameter update and conflict tests to MapperTestCase

### LINKED ISSUE #61631: Improve testing of mapping parameters
The 7.9 release included some significant refactoring in our mapping code, and this refactoring is ongoing.  After the release, users have found a number of [bugs](https://github.com/elastic/elasticsearch/issues/61393) and [unexpected behaviour changes](https://github.com/elastic/elasticsearch/issues/61563) that really should have been caught by tests.

This meta issue will encompass changes to the mappings test infrastructure that we should make before the refactoring effort continues, to ensure that these unintentional changes get caught early and either fixed or communicated more clearly.

Specifically, we need to test that every mapping parameter is
* serialized correctly
* either updateable or throws an error on update conflicts
* documented with defaults and whether or not it can be updated

### PR DESCRIPTION
**Pull request by romseygeek**
This commit adds a mechanism to MapperTestCase that allows implementing 
test classes to check that their parameters can be updated, or throw conflict
errors as advertised.  Child classes override the `registerParameters` method
and tell the passed-in `UpdateChecker` class about their parameters.  Simple
conflicts can be checked, using the existing minimal mappings as a base to
compare against, or alternatively a particular initial mapping can be provided
to check edge cases (eg, norms can be updated from `true` to `false`, but not
vice versa).  Updates are registered with a predicate that checks that the update
has in fact been applied to the resulting FieldMapper.

Fixes #61631

### CODE REVIEW

**Comment by romseygeek** [comment]
A nice follow up to this would be to get all possible parameters from a mapper (possibly by calling `maximalMapping` and iterating the keys of the resulting map) and checking that we are registering all of them.  There are a few edge cases there though so I want to get this in first as a base to build on.

**Review by nik9000 — APPROVED** [review]
Nice!

**Comment by romseygeek** [comment]
@elasticmachine update branch

**Comment by romseygeek** [comment]
@elasticmachine run elasticsearch-ci/1
@elasticmachine run elasticsearch-ci/2

**Comment by romseygeek** [comment]
@elasticmachine update branch

**Comment by romseygeek** [comment]
@elasticmachine run elasticsearch-ci/2

**Pull request merged**
