### PR TITLE
Fix resolveAllDependencies to ignore testCompile

### PR DESCRIPTION
**Pull request by breskeby**
Fixes https://github.com/elastic/elasticsearch/pull/57921#issuecomment-643725796

### CODE REVIEW

**Comment by mark-vieira** [comment]
What ended up being the actual cause of this? What was adding a dependency to that configuration in the first place?

**Comment by breskeby** [comment]
we just iterate over all resolvable configurations and resolve them. In the aftermath another option would have been to set testCompile to resolvable = false. We can switch to that pattern when porting the other deprecated configurations (testRuntime, compile etc.)

**Comment by mark-vieira** [comment]
Right, but I guess I don't understand what caused the exception. [This](https://github.com/elastic/elasticsearch/blob/680ea07f7ff00e52e15cc5ad250ce5398ce0f0e3/buildSrc/src/main/java/org/elasticsearch/gradle/ElasticsearchJavaPlugin.java#L125) should only fail if `testCompile` actually declares dependencies. Just triggering it to resolve should be fine. So the question is, what dependencies are there and where did the come from? To me this could be indicating that we missed a spot when translating to `testImplementation`?

**Comment by breskeby** [comment]
Aah. Now I see what you mean. I‘lol double check that.

**Comment by breskeby** [comment]
@mark-vieira the failure comes from the fact that we still have usages of `compile` which testCompile extends from. Once we also replaced the deprecated compile configuration usage we should be fine and can remove that specific handling here again.

**Pull request merged**
