### PR TITLE
Couple of typos - various misspellings of `buckets-path`

### PR DESCRIPTION
**Pull request by iantruslove**

### CODE REVIEW

**Comment by colings86** [comment]
@iantruslove thanks for pointing this out. Could I ask you to sign the Contributor Licence Agreement (https://www.elastic.co/contributor-agreement/) so I can merge this fix?

**Comment by iantruslove** [comment]
I signed it right after seeing the note on the PR - I should be good to go
now.

**Comment by colings86** [comment]
Ah so you did. sorry, I missed that

**Comment by colings86** [comment]
Thanks again for the contribution, this has now been merged in :)

**Pull request merged**
