### PR TITLE
Relax limit on max string size in CBOR, Smile, YAML

### LINKED ISSUE #104009: Jackson 2.15: String length exceeds the maximum length (5000000) in SMILE
Jackson 2.15 has a rough max limit on string length.  In https://github.com/elastic/elasticsearch/pull/96031 it was relaxed for JSON, but it appears in Smile, Yaml and CBOR as well.

This artificially limits certain field sizes.

### PR DESCRIPTION
**Pull request by stu-elastic**
Remove the rough limit on string length from Jackson 2.15. The limit was already relaxed for JSON in #96031, this extends that change to other XContent types.

Refs: #96031
Fixes: #104009

### CODE REVIEW

**Review by ldematte — COMMENTED** [review]
Looks good, but there are CI tests failures related to YAML parsing - are those related?

**Comment by stu-elastic** [comment]
> Looks good, but there are CI tests failures related to YAML parsing - are those related?

Yes, they do not appear on main so they need to be addressed.

**Comment by stu-elastic** [comment]
Doing the configuration in the build changes some default behavior, at the very least `YAMLParser.Feature.EMPTY_STRING_AS_NULL` is no longer present in `yamlFactory`.

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by stu-elastic** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.12|[](https://github.com/elastic/elasticsearch/pull/104088)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
