### PR TITLE
Fix typo in docs

### PR DESCRIPTION
**Pull request by GlenRSmith**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?

charachters -> characters

### CODE REVIEW

**Review by nik9000 — APPROVED** [review]
Looks good to me.

**Comment by nik9000** [comment]
@GlenRSmith do you want to do the merging or should I?

**Comment by nik9000** [comment]
Cool. Next step, "do you want to forward port this to the 5.x branch and the master branch or should I?" For Elasticsearch you can just `git cherry-pick` into the branch and push it and leave a note here with the commit hash.

**Comment by GlenRSmith** [comment]
@nik9000 if you're game to do that, I would be grateful.

**Comment by nik9000** [comment]
Looks like this had already been fixed in master. So this is the cherry-pick to 5.x: 34d2defa684c676c81b9add489400ece5b9764a4

**Pull request merged**
