### PR TITLE
 Improve error message of ClassCastExceptions 

### LINKED ISSUE #12135: Improve error handling of ClassCastException
Example in 1.6:

```
POST cast/type/1
{
  "ip_str":"0.0.0.0"
}
PUT cast2
{
  "mappings": {
    "type":{
      "properties": {
        "ip_str":{
          "type":"ip"
        }
      }
    }
  }
}
POST cast2/type/1
{
  "ip_str":"0.0.0.0"
}

GET cast/_mapping
GET cast2/_mapping

GET cast,cast2/_search?search_type=count
{
  "aggs": {
    "NAME": {
      "terms": {
        "field": "ip_str",
        "size": 10
      }
    }
  }
}
```

Returns:

```
{
   "error": "ReduceSearchPhaseException[Failed to execute phase [query], [reduce] ]; nested: ClassCastException[org.elasticsearch.search.aggregations.bucket.terms.LongTerms$Bucket cannot be cast to org.elasticsearch.search.aggregations.bucket.terms.StringTerms$Bucket]; ",
   "status": 503
}
```

Above is a simplified example.  Would be nice to improve the error handling above, eg. tell the user that cast index's type mapping has ip_str defined as a string while cast2 index' type mapping has ip_str defined as an ip type and they will have to reindex to address the type mismatch, etc..

### PR DESCRIPTION
**Pull request by HarishAtGitHub**
Closes #12135 
# What is the problem we are trying to solve ?

When we are doing aggregations against a field name as shown in
https://github.com/HarishAtGitHub/elasticsearch-tester/blob/master/12135.py#L37-L46

``` javascript
search = {
           "aggs": {
             "NAME": {
               "terms": {
                 "field": "ip_str",
                 "size": 10
               }
             }
           }
         }
```

and when the field "ip_str" has values of different types in different indices
. say one is of type StringTerms type and other is of IP(LongTerms type) then
the aggregation fails as the types do not match(incompatible).
The failure throws a class cast exception as follows:

``` javascript
{
   "error": {
      "root_cause": [],
      "type": "reduce_search_phase_exception",
      "reason": "[reduce] ",
      "phase": "query",
      "grouped": true,
      "failed_shards": [],
      "caused_by": {
         "type": "class_cast_exception",
         "reason": "org.elasticsearch.search.aggregations.bucket.terms.LongTerms$Bucket cannot be cast to org.elasticsearch.search.aggregations.bucket.terms.StringTerms$Bucket"
      }
   },
   "status": 503
}
```

which is hard to understand . User cannot infer anything about the cause of the problem and what he should do from seeing the
class cast exception.
# What can be the possible solution ?

Make the exception more readable by showing him the root cause of the problem so that he can
understand which area actually caused the problem, so that he can take necessary steps further.
# Code Analysis

Debugging code shows that:
the query /{indices}/_search?search_type=count involves two phases
1) search phase

---

```
 searchService.sendExecuteQuery(...) [Ref: TransportSearchCountAction]

 what happens here ?
    the phase 1, which is the search phase goes without error.
    In this phase the shards for the given indexes are collected and the search is done on all asynchronously
    and finally collected in the variable "firstResults" and given to meger phase.

    [Flow: .... -> TransportSearchTypeAction -> method performFirstPhase]
```

2) merge phase

---

```
 searchPhaseController.merge(...firstResults...) [Ref: TransportSearchCountAction]

 what happens here ?
    the "firstresults" QuerySearchResults are now to be aggregated and combined.

    [Flow: SearchPhaseController.merge(...) -> ..... -> InternalTerms.doReduce(...)]
```

the phase 1, which is the search phase goes without error.
The problem comes in phase 2, which is merge phase.
Now the individual term buckets are available.
As per the test case , there are two indices cast and cast2, so by default 10 shards.
cast has ip_str of type StringTerms
cast2 has ip_str of type ip which is actually LongTerms

so here two types of Buckets exist. StringTerms_Bucket and LongTerms_Bucket.
Now the aggregation is to be put inside the BucketPriorityQueue(size 2: as out of 10, 2 has hits) finally.
(docs of PriorityQueue: https://lucene.apache.org/core/4_4_0/core/org/apache/lucene/util/PriorityQueue.html#insertWithOverflow(T))

Now first the LongTerms$Bucket is put inside.
then the StringTerms$Bucket is to be put in.
This is the area where exception is thrown. What happens is when adding the StringTerms$Bucket now it has to
goes through the code "lessThan(element, heap[1])"
which finally calls

<code>
     StringTerms$Bucket.compareTerms(other)  <---------------- Area of exception  
</code>

where when comparing one to other a type cast is done and it fails as StringTerms$Bucket and LongTerms$Bucket are
incompatible.
# Approach to solve:

The best way is to make user understand that the problem is when reducing/merging/aggregating the buckets which came as a result of
querying different shards, so that this will make them infer that the problem is because the values of the fields are of different types.
The message is also user friendly and much better than the indecipherable classcastexception.

The only place to infer correctly that the aggregation has failed is in the place where aggregations take place.
so

at InternalTerms.java -> (BucketPriorityQueue)ordered.insertWithOverflow(b);

so here I can throw AggregationExecutionException saying it is because the buckets are of different
types.

<b>But when can I infer at this point that the failure is due to mismatch of types of buckets ???</b>
it can be possible only if at this point it is informed that the problem which occurred deep inside
is due to buckets that were incomparable.
so from just a classCastException we cannot make such a pointed exact inference, because
as class cast exception can be due to a number of scenarios and at a number of places.

so unless we inform the exact problem to InternalTerms it will not be able to infer properly.
so infer the classCastException at the compareTerms function itself that it is a IncomparableTermBucktesTypeException.
This is the best place to infer classCastException as this the place which generated the exception.
Best inference of exceptions can be done only at the source/origin of the exception.

so IncomparableTermBucktesTypeException to InternalTerms-> will make it infer and conclude on why
aggregation failed and give best information to user.
# File changes:

```
new file:   core/src/main/java/org/elasticsearch/IncomparableException.java
new file:   core/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/IncomparableTermBucketsException.java
modified:   core/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/InternalTerms.java
modified:   core/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/StringTerms.java
modified:   core/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/Terms.java
```

Details of changes

```
new file:   core/src/main/java/org/elasticsearch/IncomparableException.java
```

   This is the base class for all incomparable exception type. If the exceptions can be infered just with this
   base class he can very well use this without subclassing.

```
new file:   core/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/IncomparableTermBucketsException.java
```

   This is sub class of IncomparableException.java . This is just to enhance readability as it is same
   as IncomparableException AND inference can be better. because from IncomparableException he can infer
   only that some quantities are incomparable. but if we want to say exactly Bucktes are incomparable this can be
   used. For eg. This resulted in better inference in InternalTerms and we concluded that the buckets differed in types.

```
modified:   core/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/InternalTerms.java
```

   throw AggregationExecutionException on receiveing IncomparableTermBucketsException

```
modified:   core/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/StringTerms.java
```

   infer class cast exception as IncomparableTermBucketsException

```
modified:   core/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/Terms.java
```

   make the abstract method throw IncomparableTermBucketsException so that the implementors can follow the convention.
# Result after the change:

{

```
"error":{

    "root_cause":[

    ],

    "type":"reduce_search_phase_exception",

    "reason":"[reduce] ",

    "phase":"query",

    "grouped":true,

    "failed_shards":[

    ],

    "caused_by":{

        "type":"aggregation_execution_exception",

        "reason":"Merging/Reducing the aggregations failed because the buckets differ in type and they are incomparable",

        "caused_by":{

            "type":"incomparable_term_buckets_exception",

            "reason":"The Buckets cannot be compared as one is of type LongTerms and the other is of type StringTerms",

            "caused_by":{

                "type":"class_cast_exception",

                "reason":"org.elasticsearch.search.aggregations.bucket.terms.LongTerms$Bucket cannot be cast to org.elasticsearch.search.aggregations.bucket.terms.StringTerms$Bucket"

            }

        }

    }

},

"status":503
```

}

### CODE REVIEW

**Comment by HarishAtGitHub** [comment]
Doubts:
 1)   All tests passed except " Failed to execute goal com.carrotsearch.randomizedtesting:junit4-maven-plugin:2.1.16:junit4 (tests) on project elasticsearch" . Why am I getting this ? To check if my code brought in this , I had a same fork without my changes and there too it failed ? what am I to infer from this ?

Note: this is just the basic patch . please comment and give feedback and I can make changes.
I should make changes like making other terms also make this sort of check in compare and throw exception . Is this needed now or what should I do ?

If this approach is ok I can try to solve this similar issue too https://github.com/elastic/elasticsearch/issues/12675 .

Thanks in advance.

**Comment by jpountz** [comment]
Thanks @HarishAtGitHub. This approach works, but I would rather proactively check that the Terms instances are compatibles instead of catching class-cast exceptions. Maybe we could just loop over the aggregations instances in `InternalTerms.doReduce` and raise an error if we find two different impls of InternalTerms (with the exception of UnmappedTerms, which can be merged with any other Terms instance)?

> All tests passed except " Failed to execute goal com.carrotsearch.randomizedtesting:junit4-maven-plugin:2.1.16:junit4 (tests) on project elasticsearch" . Why am I getting this ? To check if my code brought in this , I had a same fork without my changes and there too it failed ? what am I to infer from this ?

I suspect there is the actual error message right before or after this message, can you create a gist of the whole build log?

**Comment by HarishAtGitHub** [comment]
Hi @jpountz  ,
      First of all thanks for the review (I was worried if people will be bored reading my huge commit message. I personally believe that the entire thought process should be in commit message. Thats y this hugeness.sorry if it bothered. ).Thank you very much .  It was great help.

Ok now coming back. ...I thought about your way of checking terms prior ... But I was not confident because of these questions that arose in my mind(may be because I am a beginner for elasticsearch concepts)
1) what if there are many shards on which search occurred . For eg . say I am searching on 10 indices. and people used the default 10 shards per index. in that loop we might end up with 10 * 10 = 100 entries . 
2) what if the 100 entries above had entries with all possible terms .. today may be there are some 5 terms(different) . may tomorrow it might go up to 10 or more (I don't know ..but)...

What I worried was that there are more possibilities of checking the compatibility between terms.
I was worried that this proactive check approach might end up doing more work .
But if we leave it for the normal loop itself to check , it is only one loop or one breakage.
But in proactive check approach will we not end up with (loopcheck + existinglogic) or (loopcheck & breakage) .
The tradeoff made me lean towards the present approach .

And also that these kinds of incompatibility breakage seems to be in a number of places. For eg . I saw this similar one https://github.com/elastic/elasticsearch/issues/12675.

If we follow the present approach all these places can be fixed without any effort(or looping proactively ). I thought that it might be performance efficient as well as we don't bring in any additional looping to check incompatibility and the normal business logic takes care of checking incompatibility.


Please share your thoughts .

**Comment by jpountz** [comment]
> 1) what if there are many shards on which search occurred . For eg . say I am searching on 10 indices. and people used the default 10 shards per index. in that loop we might end up with 10 * 10 = 100 entries .
2) what if the 100 entries above had entries with all possible terms .. today may be there are some 5 terms(different) . may tomorrow it might go up to 10 or more (I don't know ..but)...

1 is right, but I don't see it as an issue, we need to iterate over all aggs anyway if we want to reduce results. Regarding 2, I was not suggesting to iterate over the actual terms, but the aggregation object (which should be a sub-class or the `Terms` class).

I don't think performance would be an issue at all.

**Comment by HarishAtGitHub** [comment]
Ok to get clarity to know if what I am thinking is correct..... 
we already have a loop like
```java
for (InternalAggregation aggregation : aggregations) {  ----> loop 1
  ..... N aggregations takes N loop
}
for (Collection<Bucket> l : buckets.asMap().values()) { ----> loop 2
  ...... M times ...Far less than N as it includes only matches' buckets (in our case with 10 shards only 2 qualifies)
}
```
> 1 is right, but I don't see it as an issue, we need to iterate over all aggs anyway
> Maybe we could just loop over the aggregations instances in InternalTerms.doReduce and raise an error if we find two different impls of InternalTerms

So you are asking me to do the buckets mismatch check in loop-1 itself. Right ?

But to do this I will have to iterate the bucket's again and check for each if there is mismatch.My doubt is why should we do it there when we are already doing it in the M-count loop(loop2).

Another doubt is if there is no mismatch of buckets there will be two iterations of buckets .
one inside loop-1 another in loop-2 .
so net would be something like loop1 + [M*(M+1)/2]*inner bucket loops  + loop2(which already again does this by means of comparison inside BucketPriorityQueue)

But if we do it in the present way it will always be just
loop1 + loop2(which already again does this by means of comparison inside BucketPriorityQueue.)

I can surely understand your point that if we do it your way we can directly interepret the mismatch here itself inside InternalTerms.
But what I cannot understand is just for this exception interpretation(which is done with the present approach in the patch already without extra computation) why should we bring in so many additional loops ?

Please feel free to point out mistakes .

**Comment by HarishAtGitHub** [comment]
> I suspect there is the actual error message right before or after this message, can you create a gist of the whole build log?

Yes. Now I fixed it. It was a org.elasticsearch.ExceptionSerializationTests.testExceptionRegistration test that was failing as my exception was not registered . Now fixed it and pushed it .Thanks.

**Comment by rjernst** [comment]
Do we really need a new exception? I think `IllegalArgumentException` or `IllegalStateException` would suffice?

**Comment by HarishAtGitHub** [comment]
ok @rjernst, I understand your concerns.... But this was my thought process ....

I want to make normal user(who does not know much about coding and exceptions) to even interpret from the exception. I am just targetting users who know about elasticsearch, that is elasticsearch users . May be users who have just read his [elasticsearch documentation link](https://www.elastic.co/guide/en/elasticsearch/reference/1.6/search-aggregations-bucket-terms-aggregation.html) . IllegalArgumentException would be good if it is just going to be in the logs inside the box which is not accessible to common user.
I want to have something that is not too broad and also conveys the meaning to normal elasticsearch user. But at the same time as you say we cannot create exceptions(for every usecase) and this would flood the code base with exception classes.
I want to stand somewhere in the middle satisfying both.
Thats y I chose to introduce new exception.

It is like this. We already have [IndexOutOfBoundsException](http://docs.oracle.com/javase/7/docs/api/java/lang/IndexOutOfBoundsException.html) . But despite having this, we have [ArrayIndexOutOfBoundsException](http://docs.oracle.com/javase/7/docs/api/java/lang/ArrayIndexOutOfBoundsException.html) and [StringIndexOutOfBoundsException](http://docs.oracle.com/javase/7/docs/api/java/lang/StringIndexOutOfBoundsException.html) . This is there just to convey the exact sense. 

I am not saying that we should follow what java community has done . But just that this approach they have taken made sense to me.

And that this exception is to be shown to the user on api failures so I felt it is not a bad choice to be precise and exact and convey the sense and hence introduce a new one as none of the exceptions at purpose satisfied my need.

**Comment by rjernst** [comment]
I personally think the actual exception type is less meaningful (hence just tend to use builtin exceptions; we use `IllegalArgumentException` all over elasticsearch). The message is what is important. The user will quickly look at "reason" in structured exceptions.

**Comment by HarishAtGitHub** [comment]
Ya.. Fine agreed ... you are right ... Your argument makes a lot of sense ...

ok I will do it like this now ?
```java
StringTerms$Bucket
try {
     compareTerm(.... typecast ...)
} catch (TypecastException) {
    IllegalAgrgumentException("the buckets type could not be compared as they were incompatible
}
```

```java
InternalTerms
try{
  ordered.insertWithOverflow(b);
catch(RuntimeException e) {
  throw AggregationExecutionException("merging/reducing the buckets failed", e);
}
```

does the above makes sense ..
Now as you said we just used existing exceptions but still conveyed the meaning with the help of messages inside it.
so what ever runtimeexception is thrown within insertWithOverflow will result in throwing AggregationExecutionException as aggregation failed .
and this AggregationExecutionException will have the cause exception within it for more info ..
Ya this makes sense for me.
you are fine with this @rjernst ?

NOTE: I will make the messages better . but the above is just to convey the idea..

**Comment by HarishAtGitHub** [comment]
But one problem in the above approach which just came to my mind is now I cannot enforce something like 

```java
abstract int compareTerm(Terms.Bucket other) throws IncomparableTermBucketsException;
```

because IllegalAgrgumentException is way to broad to come here in abstract method compareTerm .
If I am not able to make a mention here then the subclasses will not necessarily do it .. then it is a problem maintaining subclasses ...
I am not fine with this problem alone with regard to the new approach...
you can think of some some way around to this problem to inform subclasses to do something like this ?

**Comment by jpountz** [comment]
>for (InternalAggregation aggregation : aggregations) {  ----> loop 1
  ..... N aggregations takes N loop
}
for (Collection<Bucket> l : buckets.asMap().values()) { ----> loop 2
  ...... M times ...Far less than N as it includes only matches' buckets (in our case with 10 shards only 2 qualifies)
}

My point was that you don't need loop2, since an aggregation has all buckets of the same type, you could just do loop1.

**Comment by HarishAtGitHub** [comment]
ok @jpountz , I will give it a try now ...Thanks ...

**Comment by HarishAtGitHub** [comment]
Hi @jpountz , did it as per review comments . 
Please give your review comments .
(0 Test failures ..)

**Comment by HarishAtGitHub** [comment]
@jpountz ,
new error message is like this 

```javascript
{  
    "error":{  
        "root_cause":[  

        ],
        "type":"reduce_search_phase_exception",
        "reason":"[reduce] ",
        "phase":"query",
        "grouped":true,
        "failed_shards":[  

        ],
        "caused_by":{  
            "type":"aggregation_execution_exception",
            "reason":"Merging/Reducing the aggregations failed when computing the aggregation [ Name: NAME, Type: terms ] because: the field you gave in the aggregation query existed as two different types in two different indices"
        }
    },
    "status":503
}
```

**Comment by HarishAtGitHub** [comment]
@jpountz also a doubt, will there be cases when the aggregation and type will not be mandatory ?
I just tried the query and on leaving out either of these it said ""type":"search_parse_exception","reason":"Expected [START_OBJECT] under [field], but got a [VALUE_STRING] in [NAME]","line":1,"col":20}" .
so can I assume it will work ? . or should I have a null pointer check on the params (for safety) I am introducing in aggregation_execution_exception ?

**Comment by jpountz** [comment]
Thank you @HarishAtGitHub

**Comment by HarishAtGitHub** [comment]
May I know what was wrong in the patch ? . just for my learning @jpountz ?

**Comment by jpountz** [comment]
Nothing was wrong, I just squashed the commits.

**Comment by HarishAtGitHub** [comment]
the comments said "closed with UNMERGED commits" thats y I was worried ...

**Comment by HarishAtGitHub** [comment]
Thank you very much for the guidance ... your approach was easier and direct and exactly solved the issue.... learning from u ...Thanks...

**Pull request closed without merging**
