### PR TITLE
Implement human readable indexing pressure stats

### PR DESCRIPTION
**Pull request by Tim-Brooks**
The indexing pressure stats do not currently have human readable
variants. This commit add human readable variants and updates the
documentation.

### CODE REVIEW

**Comment by tbrooks8** [comment]
Thoughts about names such as `primary_in_bytes`, `primary`, `all_in_bytes`, `all`, etc? Should we go with `primary_memory_in_bytes`, `primary_memory`, `all_memory_in_bytes`, `all_memory`, etc? 

Or put it under a `memory` block in the future? It seems weird to just be called `primary`, `replica`, `all`, etc?

**Comment by tbrooks8** [comment]
Disabled BWC as this will have to be back ported for those tests to succeed.

**Comment by ywelsch** [comment]
Let's put it in a `memory` block directly in this PR.

**Comment by tbrooks8** [comment]
@ywelsch - I put this under a `mem` block as that is the terminology we use in other parts of node stats?

**Comment by tbrooks8** [comment]
changed to `memory`

**Review by ywelsch — APPROVED** [review]
One nit: I think I would prefer "current" to be listed before "total" (both in output as well as docs). LGTM o.w., does not need another review.

**Comment by tbrooks8** [comment]
#60063 has been opened to reenable BWC.

**Pull request merged**
