### PR TITLE
LOGGING: Upgrade to Log4J 2.11.1

### LINKED ISSUE #27300: Memory leak upon partial TransportShardBulkAction failure
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`):
5.3.2 -  5.6.3

**Plugins installed**: [None]

**JVM version** (`java -version`):
1.8.0_77-b03

**OS version** (`uname -a` if on a Unix-like system):
Linux SVR14982HW1288 2.6.32-642.6.2.el6.x86_64 #1 SMP Wed Oct 26 06:52:09 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
A production cluster running version 5.3.2 was experiencing very high heap usage after bulk updating some documents.  The search load was very light and the cluster was almost idle.  Old GC could not reclaim memory even after the bulk requests had ceased running.  After some investigation,  log4j seems to be the culprit as it holds strong reference to Bulkshardrequests object whenever any exception was thrown during the bulk request execution.

The problem seems quite similar to [issues#23798](https://github.com/elastic/elasticsearch/issues/23798) .  But I can reproduce the problem on latest stable version 5.6.3, so the root cause could be different.

**Steps to reproduce**:
Update a bunch of documents with bulk API,  but purposely generate some exceptions, for example, leave a couple of requests with non-existence doc_id or with wrong field type.  From ES logs , DEBUG messages pop up showing document missing or mapper parsing exception.   The heap used increased significantly depending on a single bulk size.   Dump the heap and analyze with MAT, the Bulkshardrequests object is referenced by Log4j's ParameterizedMessage. 

The only way I can reclaim the memory is to issue a small bulk request that triggers another exceptions. In which case, the ParameterizedMessage object references the new request with small memory footprint.

Below are the sample heap dump stats for our production cluster:
screen shot 2017-11-07 at 17 41 46
screen shot 2017-11-07 at 17 42 29

### LINKED ISSUE #32537: Heap slowly filling up with org.elasticsearch.index.SearchSlowLog$SlowLogSearchContextPrinter
**Elasticsearch version** (`bin/elasticsearch --version`):

```json
{
   "version" : {
      "number" : "6.3.0",
       "build_flavor" : "default",
       "build_type" : "rpm",
       "build_hash" : "424e937",
       "build_date" : "2018-06-11T23:38:03.357887Z",
       "build_snapshot" : false,
       "lucene_version" : "7.3.1",
       "minimum_wire_compatibility_version" : "5.6.0",
       "minimum_index_compatibility_version" : "5.0.0"
  }
}
```

**Plugins installed**: ['discovery-ec2', 'repository-s3']

**JVM version** (`java -version`):

```
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
```

**OS version** (`uname -a` if on a Unix-like system):
```
Linux es-data-1 4.14.51-60.38.amzn1.x86_64 #1 SMP Tue Jun 26 23:06:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Description of the problem including expected versus actual behavior**:

Garbage collection is able to recover less and less of the heap as time moves on. Eventually this puts a lot of memory pressure on `data-nodes` and we see long pause the world `Old GC collections`

screen shot 2018-08-01 at 11 38 42

**Day 1**

screen shot 2018-08-01 at 11 12 25

**Day 2**

screen shot 2018-08-01 at 11 17 45

**Day 3**

screen shot 2018-08-01 at 11 19 30

On Day 3, we took a heap dump and saw that `6,776 MB == ~30%` of the heap was filled with `org.elasticsearch.index.SearchSlowLog$SlowLogSearchContextPrinter` 

43466021-8679f9f6-94d6-11e8-8e79-7357e64a5b8b

We then turned off slow logging by doing the following

```
curl -XPUT 'localhost:9200/_settings' -H 'Content-Type: application/json' -d '{
  "index.indexing.slowlog.level": null,
  "index.search.slowlog.threshold.query.warn": null,
  "index.search.slowlog.threshold.fetch.warn": null,
  "index.indexing.slowlog.threshold.index.warn": null
}'
```

We restarted each `data-node` in our cluster 12 hours ago and things seem stable since then (really we won't be sure for a few more days).

**Last 12 hours**

screen shot 2018-08-01 at 11 32 14

**Last hour**

screen shot 2018-08-01 at 11 32 45

**Steps to reproduce**:

I haven't tried to reproduce this, but this has happened to all four of our `ES 6.3.0` clusters.

 1. Turn on slow logging
 2. Generate a lot of slow queries
 3. Look at the metric `jvm.mem.heap_in_use` over time. 
 
**Note:** This issue might have the same route cause as: https://github.com/elastic/elasticsearch/issues/27300

### PR DESCRIPTION
**Pull request by original-brownbear**
* Upgrade to `2.11.1` to fix memory leaks in slow logger when logging large requests
   * This was caused by a bug in Log4J https://issues.apache.org/jira/browse/LOG4J2-2269 and is fixed in `2.11.1` via https://git-wip-us.apache.org/repos/asf?p=logging-log4j2.git;h=9496c0c
* Fixes #32537
* Fixes #27300

### CODE REVIEW

**Comment by original-brownbear** [comment]
looks like the third party audit fails on CI (passed locally) ... will fix in a few hours

**Review by jasontedor — APPROVED** [review]
Great find. LGTM assuming that you get a green PR CI build and have third-party audit passing on JDK 8, JDK 10, and JDK 11. I think that we should backport this to 5.6.11 too.

**Comment by jasontedor** [comment]
In fact, I would support merging this to 6.4.0.

**Comment by original-brownbear** [comment]
@jasontedor alrighty got it green :)
Just one trivial change to the tests (that nicely shows that this should fix the problem I think) https://github.com/elastic/elasticsearch/pull/32616/files#diff-d0333c88811865623eb43c70c4e1c14bR49

and conditional excludes to make JDK8 auditing pass.

Can you take another look please? :)

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by original-brownbear** [comment]
@jasontedor thanks! Merging + back porting then :)

**Pull request merged**
