### PR TITLE
Rewrite match_all inside must_not

### PR DESCRIPTION
**Pull request by ywelsch**
A `must_not` with a `match_all` clause inside a `bool` query is currently not rewritten to a match_none query. This means that running a boolean query with `"must_not":[{"terms":{"_tier":["data_frozen","data_cold"]}]` is currently not rewritten as `match_none` on a cold/frozen tier node.

### CODE REVIEW

**Review by dnhatn — APPROVED** [review]
Great catch, LGTM.

**Comment by ywelsch** [comment]
@elasticmachine run tests (github blip)

**Comment by ywelsch** [comment]
@elasticmachine update branch

**Comment by ywelsch** [comment]
Thank you @dnhatn

**Pull request merged**
