### PR TITLE
Fix DiskThresholdDeciderIT.testHighWatermarkNotExceeded

### LINKED ISSUE #62326: DiskThresholdDeciderIT.testHighWatermarkNotExceeded failure
**Build scan**:
https://gradle-enterprise.elastic.co/s/okz2lziucuxkq/tests/:server:internalClusterTest/org.elasticsearch.cluster.routing.allocation.decider.DiskThresholdDeciderIT/testHighWatermarkNotExceeded

**Repro line**:
```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.cluster.routing.allocation.decider.DiskThresholdDeciderIT.testHighWatermarkNotExceeded" -Dtests.seed=60A6AF6A936EF834 -Dtests.security.manager=true -Dtests.locale=ro-RO -Dtests.timezone=America/Pangnirtung -Druntime.java=11
```

**Reproduces locally?**: no

**Applicable branches**: master

**Failure history**:
https://gradle-enterprise.elastic.co/scans/tests?search.buildToolTypes=gradle&search.buildToolTypes=maven&search.relativeStartTime=P7D&search.timeZoneId=Europe/London&tests.container=org.elasticsearch.cluster.routing.allocation.decider.DiskThresholdDeciderIT&tests.sortField=FAILED&tests.test=testHighWatermarkNotExceeded&tests.unstableOnly=true

**Failure excerpt**:
```
java.lang.AssertionError: |  
  | Expected: a collection with size <1> |  
  | but: collection size was <0>

at __randomizedtesting.SeedInfo.seed([60A6AF6A936EF834:89874ED813A831DA]:0) |  
  |   | at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18) |  
  |   | at org.junit.Assert.assertThat(Assert.java:956) |  
  |   | at org.junit.Assert.assertThat(Assert.java:923) |  
  |   | at org.elasticsearch.cluster.routing.allocation.decider.DiskThresholdDeciderIT.testHighWatermarkNotExceeded(DiskThresholdDeciderIT.java:160) |  
  |  

```

### PR DESCRIPTION
**Pull request by tlrx**
I still can't reproduce the CI failure but I think that there's a race between the master node processing the reroute and the master's  ClusterInfoService processing the latest ShardStats response. It case the reroute is processed before the master knows about the latest shards stats then the reroute will have no effect and the rebalance won't happen, unless the reroute is executed another time.

Closes #62326

### CODE REVIEW

**Review by original-brownbear — COMMENTED** [review]
> there's a race between the master node processing the reroute and the master's ClusterInfoService processing the latest ShardStats response

I'm not sure I understand how that would happen. `org.elasticsearch.cluster.InternalClusterInfoService#refresh` is a blocking operation and we trigger a reroute after it was completed? So during the reroute master would always have a view of the latest disk usage when doing the CS work for the reroute wouldn't it?

**Comment by tlrx** [comment]
Grrr you're right @original-brownbear - I've read the code too quickly this morning and what too happy to jump on a non-issue.

I'm going to update this PR to add debug logging as it is not obvious to me what is going wrong, ok?

**Comment by original-brownbear** [comment]
>I'm going to update this PR to add debug logging as it is not obvious to me what is going wrong, ok?

Sounds good :)

**Comment by tlrx** [comment]
@original-brownbear I looked at this again today - I think that the first `refreshDiskUsage()` refreshes the `ClusterInfo` update which in turn calls listeners like `DiskThreshMonitor`. This one triggers a reroute as expected and turns an internal `checkInProgress` flag before submitting a cluster state update to relocate shards (the internal flag is toggled again once the cluster state update is processed).

In the test I suspect that the second `refreshDiskUsage()` may complete before `DiskThreshMonitor`'s internal flag is set back to its initial state, resulting in the second `ClusterInfo` update to be ignored and message like `node_t0] skipping monitor as a check is already in progress` to be logged.

I think that adding another wait for languid events to be processed before executing the second `refreshDiskUsage()` should help here, WDYT?

**Comment by original-brownbear** [comment]
@tlrx jup looks like this does the trick. Your theory about the failure is correct (trivial to reproduce by putting a wait of `2s` into `org.elasticsearch.cluster.routing.allocation.DiskThresholdMonitor#checkFinished` :)

**Review by original-brownbear — APPROVED** [review]
LGTM

**Comment by tlrx** [comment]
Thanks Armin! I merged this change and I'll monitor the CI in the upcoming days to see if the failure occurs again.

**Pull request merged**
