### PR TITLE
[Transform] Add _meta field to TransformConfig

### PR DESCRIPTION
**Pull request by przemekwitek**
This PR adds a new field (called `_meta`) to the `TransformConfig`.
This `_meta` field stores an arbitrary key-value map.
Keys are strings.
Values are arbitrary objects (possibly also maps).
The `_meta` map is updatable via `_update` endpoint in Transform API.

Relates https://github.com/elastic/elasticsearch/issues/77506

### CODE REVIEW

**Review by hendrikmuhs — COMMENTED** [review]
some comments:

- we should add a mapping(`FLATTENED`) to `TransformInternalIndex`, this is not strictly required as dynamic mappings are turned off, but we do the same for other fields -> consistency
- it would be nice to not allow arbitrary sized meta entries, the other parts of the config are somewhat limited by nature (assuming no one is writing a monster aggregation), but meta is unlimited
	- however that's hard to achieve with the current parser
	- we could as alternative limit the Rest Request (`RestPutTransformAction`)
- +1 regarding the idea of using `LinkedHashMap` to preserve order

**Review by przemekwitek — COMMENTED** [review]
> some comments:

> we should add a mapping(FLATTENED) to TransformInternalIndex, this is not strictly required as dynamic mappings are
> turned off, but we do the same for other fields -> consistency

Done.

> it would be nice to not allow arbitrary sized meta entries, the other parts of the config are somewhat limited by nature 
> (assuming no one is writing a monster aggregation), but meta is unlimited
> however that's hard to achieve with the current parser
> we could as alternative limit the Rest Request (RestPutTransformAction)

And also `RestUpdateTransformAction`, right?
What limit do you think makes sense here? Any prior art?

> +1 regarding the idea of using LinkedHashMap to preserve order

Done.

**Review by droberts195 — APPROVED** [review]
LGTM, if you could just fix a couple of field names in the docs

**Comment by hendrikmuhs** [comment]
> And also `RestUpdateTransformAction`, right?
> What limit do you think makes sense here? Any prior art?

no prior art as far as I know.

I think if we limit to `5MB` we still allow a lot of room for super large in-config painless scripts.

Note, I am not concerned about a single put or update request. The real issue is getting the configs in some internal places where we sometimes retrieve 100, sometimes up to 10k at a time.

**Review by benwtrent — APPROVED** [review]

**Review by hendrikmuhs — APPROVED** [review]
LGTM

**Pull request merged**
