### PR TITLE
fix RollupActionIT testRollupIndex failing

### LINKED ISSUE #88949: [CI] RollupActionIT testRollupIndex failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/ziw74nteyvy5e/tests/:x-pack:plugin:ilm:qa:multi-node:javaRestTest/org.elasticsearch.xpack.ilm.actions.RollupActionIT/testRollupIndex

**Reproduction line:**
`./gradlew ':x-pack:plugin:ilm:qa:multi-node:javaRestTest' --tests "org.elasticsearch.xpack.ilm.actions.RollupActionIT.testRollupIndex" -Dtests.seed=CD4D73103F8B5D47 -Dtests.locale=en-PH -Dtests.timezone=Africa/Mbabane -Druntime.java=17`

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.ilm.actions.RollupActionIT&tests.test=testRollupIndex

**Failure excerpt:**
```
java.lang.AssertionError: Cannot retrieve rollup index name

  at __randomizedtesting.SeedInfo.seed([CD4D73103F8B5D47:2B69024656C7548B]:0)
  at org.junit.Assert.fail(Assert.java:88)
  at org.junit.Assert.assertTrue(Assert.java:41)
  at org.junit.Assert.assertNotNull(Assert.java:712)
  at org.elasticsearch.xpack.ilm.actions.RollupActionIT.testRollupIndex(RollupActionIT.java:151)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

```

### PR DESCRIPTION
**Pull request by weizijun**
fix: https://github.com/elastic/elasticsearch/issues/88949

### CODE REVIEW

**Comment by weizijun** [comment]
I will check more detail to find the failed reason.

**Comment by weizijun** [comment]
```
[2022-08-04T11:20:03,041][INFO ][o.e.c.m.MetadataCreateIndexService] [javaRestTest-2] [index-zbqmmovaxz] creating index, cause [api], templates [], shards [1]/[0]
[2022-08-04T11:20:03,411][TRACE][o.e.x.i.IndexLifecycleRunner] [javaRestTest-2] [index-zbqmmovaxz] retrieved current step key: null
[2022-08-04T11:20:03,413][DEBUG][o.e.x.i.IndexLifecycleRunner] [javaRestTest-2] unable to retrieve policy [policy-tCmWb] for index [index-zbqmmovaxz], recording this in step_info for this index java.lang.IllegalArgumentException: policy [policy-tCmWb] does not exist
        at org.elasticsearch.ilm@8.5.0-SNAPSHOT/org.elasticsearch.xpack.ilm.IndexLifecycleRunner.markPolicyDoesNotExist(IndexLifecycleRunner.java:519)
        at org.elasticsearch.ilm@8.5.0-SNAPSHOT/org.elasticsearch.xpack.ilm.IndexLifecycleRunner.runPolicyAfterStateChange(IndexLifecycleRunner.java:398)
        at org.elasticsearch.ilm@8.5.0-SNAPSHOT/org.elasticsearch.xpack.ilm.IndexLifecycleService.triggerPolicies(IndexLifecycleService.java:414)
        at org.elasticsearch.ilm@8.5.0-SNAPSHOT/org.elasticsearch.xpack.ilm.IndexLifecycleService.clusterChanged(IndexLifecycleService.java:317)
        at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateListener(ClusterApplierService.java:558)
        at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateListeners(ClusterApplierService.java:544)
        at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:504)
        at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:428)
        at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:154)
        at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:808)
        at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:257)
        at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:223)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

[2022-08-04T11:20:03,637][INFO ][o.e.c.r.a.AllocationService] [javaRestTest-2] current.health="GREEN" message="Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[index-zbqmmovaxz][0]]])." previous.health="YELLOW" reason="shards started [[index-zbqmmovaxz][0]]"
[2022-08-04T11:20:03,705][TRACE][o.e.x.i.IndexLifecycleRunner] [javaRestTest-2] [index-zbqmmovaxz] retrieved current step key: null
[2022-08-04T11:20:03,705][DEBUG][o.e.x.i.IndexLifecycleRunner] [javaRestTest-2] unable to retrieve policy [policy-tCmWb] for index [index-zbqmmovaxz], recording this in step_info for this index java.lang.IllegalArgumentException: policy [policy-tCmWb] does not exist
        at org.elasticsearch.ilm@8.5.0-SNAPSHOT/org.elasticsearch.xpack.ilm.IndexLifecycleRunner.markPolicyDoesNotExist(IndexLifecycleRunner.java:519)
        at org.elasticsearch.ilm@8.5.0-SNAPSHOT/org.elasticsearch.xpack.ilm.IndexLifecycleRunner.runPolicyAfterStateChange(IndexLifecycleRunner.java:398)
        at org.elasticsearch.ilm@8.5.0-SNAPSHOT/org.elasticsearch.xpack.ilm.IndexLifecycleService.triggerPolicies(IndexLifecycleService.java:414)
        at org.elasticsearch.ilm@8.5.0-SNAPSHOT/org.elasticsearch.xpack.ilm.IndexLifecycleService.clusterChanged(IndexLifecycleService.java:317)
        at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateListener(ClusterApplierService.java:558)
        at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateListeners(ClusterApplierService.java:544)
        at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:504)
        at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:428)
        at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:154)
        at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:808)
        at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:257)
        at org.elasticsearch.server@8.5.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:223)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

[2022-08-04T11:20:03,969][INFO ][o.e.x.i.a.TransportPutLifecycleAction] [javaRestTest-2] adding index lifecycle policy [policy-tCmWb]
[2022-08-04T11:20:04,036][TRACE][o.e.x.i.IndexLifecycleService] [javaRestTest-2] job triggered: ilm, 1659583204032, 1659583204036
[2022-08-04T11:20:04,037][TRACE][o.e.x.i.IndexLifecycleRunner] [javaRestTest-2] [index-zbqmmovaxz] retrieved current step key: null
[2022-08-04T11:20:04,037][DEBUG][o.e.x.i.IndexLifecycleRunner] [javaRestTest-2] unable to retrieve policy [policy-tCmWb] for index [index-zbqmmovaxz], recording this in step_info for this index java.lang.IllegalArgumentException: policy [policy-tCmWb] does not exist
        at org.elasticsearch.ilm@8.5.0-SNAPSHOT/org.elasticsearch.xpack.ilm.IndexLifecycleRunner.markPolicyDoesNotExist(IndexLifecycleRunner.java:519)
        at org.elasticsearch.ilm@8.5.0-SNAPSHOT/org.elasticsearch.xpack.ilm.IndexLifecycleRunner.runPeriodicStep(IndexLifecycleRunner.java:185)
        at org.elasticsearch.ilm@8.5.0-SNAPSHOT/org.elasticsearch.xpack.ilm.IndexLifecycleService.triggerPolicies(IndexLifecycleService.java:416)
        at org.elasticsearch.ilm@8.5.0-SNAPSHOT/org.elasticsearch.xpack.ilm.IndexLifecycleService.triggered(IndexLifecycleService.java:347)
        at org.elasticsearch.xcore@8.5.0-SNAPSHOT/org.elasticsearch.xpack.core.scheduler.SchedulerEngine.notifyListeners(SchedulerEngine.java:185)
        at org.elasticsearch.xcore@8.5.0-SNAPSHOT/org.elasticsearch.xpack.core.scheduler.SchedulerEngine$ActiveSchedule.run(SchedulerEngine.java:219)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

[2022-08-04T11:20:04,043][TRACE][o.e.x.i.PolicyStepsRegistry] [javaRestTest-2] updating cached steps for [policy-tCmWb] policy, new steps: [{"phase":"new","action":"init","name":"init"}, {"phase":"new","action":"complete","name":"complete"}, {"phase":"warm","action":"rollup","name":"check-not-write-index"}, {"phase":"warm","action":"rollup","name":"wait-for-shard-history-leases"}, {"phase":"warm","action":"rollup","name":"cleanup-target-index"}, {"phase":"warm","action":"rollup","name":"readonly"}, {"phase":"warm","action":"rollup","name":"generate-rollup-name"}, {"phase":"warm","action":"rollup","name":"rollup"}, {"phase":"warm","action":"rollup","name":"wait-for-index-color"}, {"phase":"warm","action":"rollup","name":"copy-execution-state"}, {"phase":"warm","action":"rollup","name":"branch-on-datastream-check"}, {"phase":"warm","action":"rollup","name":"replace-datastream-backing-index"}, {"phase":"warm","action":"rollup","name":"delete"}, {"phase":"warm","action":"rollup","name":"swap-aliases"}, {"phase":"warm","action":"migrate","name":"branch-check-skip-action"}, {"phase":"warm","action":"migrate","name":"migrate"}, {"phase":"warm","action":"migrate","name":"check-migration"}, {"phase":"warm","action":"complete","name":"complete"}]
[2022-08-04T11:20:05,036][TRACE][o.e.x.i.IndexLifecycleService] [javaRestTest-2] job triggered: ilm, 1659583205032, 1659583205035
```

When ilm policy setting update, the policy didn't update real-time. So it call 'unable to retrieve policy [policy-tCmWb]'. And the policy will be call when the poll_interval(10m) arrive, so the test failed.

I change the poll_interval = 5s to avoid this corner case.

**Comment by csoulios** [comment]
@elasticmachine ok to test

**Comment by weizijun** [comment]
@elasticmachine  update branch

**Comment by weizijun** [comment]
@elasticsearchmachine update branch

**Comment by weizijun** [comment]
@elasticmachine update branch

**Review by csoulios — APPROVED** [review]
LGTM!

Thanks for fixing this

**Pull request merged**
