### PR TITLE
[ML] Move code specific to the Elasticsearch in cluster services to those sevices

### LINKED ISSUE #113565: [CI] TextEmbeddingCrudIT testPutE5WithTrainedModelAndInference failing
**Build Scans:**
- [elasticsearch-periodic #4190 / openjdk21_checkpart2_java-fips-matrix](https://gradle-enterprise.elastic.co/s/2hmknxjrgh3gq)
- [elasticsearch-intake #10157 / part2](https://gradle-enterprise.elastic.co/s/a2zj5kdictl4m)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:inference:qa:inference-service-tests:javaRestTest" --tests "org.elasticsearch.xpack.inference.TextEmbeddingCrudIT.testPutE5Small_withPlatformAgnosticVariant" -Dtests.seed=3A3EA860650F7298 -Dtests.locale=ar-ER -Dtests.timezone=Europe/Berlin -Druntime.java=21 -Dtests.fips.enabled=true
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testPutE5WithTrainedModelAndInference'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.inference.TextEmbeddingCrudIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure Message:**
```
java.net.SocketTimeoutException: ٦٠٬٠٠٠ milliseconds timeout on connection http-outgoing-1 [ACTIVE]
```

**Issue Reasons:**
- [main] 2 failures in test testPutE5WithTrainedModelAndInference (1.8% fail rate in 113 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by davidkyle**
This moves the specific in cluster service logic from `TransportPutInferenceModelAction` into the services. It also removes the `platformArchitectures` argument from `InferenceService. parseRequestConfig` as that was specific to in cluster services. 

The refactoring makes it easier to reuse the `InferenceService.start()` function as the required logic is no longer mixed up in the transport action.

Additionally the socket timeout in the model download tests is increased to 120s to account for slow tests. 
Closes https://github.com/elastic/elasticsearch/issues/113565

### CODE REVIEW

**Comment by davidkyle** [comment]
@elasticmachine update branch

**Comment by davidkyle** [comment]
@elasticmachine update branch

**Review by prwhelan — APPROVED** [review]
nice, lots of red

**Comment by davidkyle** [comment]
@elasticmachine update branch

**Pull request merged**
