### PR TITLE
ESQL: Fix AttributeSet#add() returning the opposite expected value

### PR DESCRIPTION
**Pull request by ivancea**
Set/Collection#add() is supposed to return `true` if the collection changed (If it actually added something).
In this case, it must return if the old value is null.

Extracted from https://github.com/elastic/elasticsearch/pull/114317 (Where it's being used)

### CODE REVIEW

**Review by alex-spies — COMMENTED** [review]
I agree with this change.

I manually went over the declarations of `AttributeSet` to check for usages of the `add` method's return type. (Local var declarations, field declarations, method parameter declarations)

I only found one: `AttributeSet.add`'s return type is used in `CombineProjections`. (There may be more if I overlooked them, as with every manual check.)

This means there is probably a bug there which we should investigate before merging this.

**Comment by ivancea** [comment]
@alex-spies In `CombineProjections` we aren't using the return value (Until the Categorize PR), so all nice! Thanks for checking!
If tests are ok (And in the other PR, they were), we should be fine then :blob:

**Review by alex-spies — APPROVED** [review]
Argh, sorry - I was looking at your branch where _you_ started using the return value. Of course, this change should be fine then - phew!

**Comment by nik9000** [comment]
Thanks for yanking it into it's own PR!

**Review by costin — APPROVED** [review]
Oopps. LGTM
P.S. Thanks for extracting it into its own PR!

**Pull request merged**
