### PR TITLE
Update allowed inferred versions to include 8.10.

### PR DESCRIPTION
**Pull request by thecoop**
8.10 actually wasn't released with separated index versions, so update the version check for inferred versions to include 8.10.

Also update tests that could pass CURRENT to infer versions from to specify explicit versions

### CODE REVIEW

**Comment by ChrisHegarty** [comment]
>  so update the version check for inferred versions to include 8.11.

typo? ".. to include 8.10", right? If I understand the changes correctly.

**Comment by thecoop** [comment]
> > so update the version check for inferred versions to include 8.11.
> 
> typo? ".. to include 8.10", right? If I understand the changes correctly.

Yes, that should say 8.10

**Review by ChrisHegarty — APPROVED** [review]
LGTM

**Comment by thecoop** [comment]
@elasticmachine update branch

**Pull request merged**
