### PR TITLE
SQL: Refactor binary date time functions

### PR DESCRIPTION
**Pull request by matriv**
Refactor DateTrunc and DatePart to use separate Pipe classes which
allows the removal of the BinaryDateOperation enum.

### CODE REVIEW

**Comment by matriv** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample-matrix

**Comment by costin** [comment]
Isn't this already implemented through #47747 ? Or did you want to keep the two topics separate?

**Review by astefan — APPROVED** [review]
LGTM

**Comment by matriv** [comment]
@costin wanted to make them separate so that the DATE_ADD PR is more clear and only contains the new implementation.

**Review by costin — APPROVED** [review]
LGTM

**Pull request merged**
