### PR TITLE
Update http-core and http-client dependencies

### LINKED ISSUE #45577: RestClientMultipleHostsIntegTests frequently failing in CI
We have had a large number of failures of tests in `org.elasticsearch.client.RestClientMultipleHostsIntegTests` failing in `master` over the last couple of days.

https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(test,class,branch),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:kuery,query:'class:%20"org.elasticsearch.client.RestClientMultipleHostsIntegTests"'),sort:!(time,desc))

Since these tests don't use `ESTestCase` there's no reproduction line so it's hard to determine if this is reproducible with a particular test seed.

### PR DESCRIPTION
**Pull request by javanna**
This PR updates http-core to the latest bugfix release: 4.4.12. Same for http-client that goes to 4.5.10.

A pretty bad bug was fixes which was causing #45577 and made us wait for the fix before backporting #45379 to 7.x.

Relates to #45808
Closes #45577

### CODE REVIEW

**Comment by javanna** [comment]
run elasticsearch-ci/1

**Comment by javanna** [comment]
run elasticsearch-ci/1

**Review by jimczi — APPROVED** [review]
LGTM

**Review by martijnvg — APPROVED** [review]
LGTM

**Pull request merged**
