### PR TITLE
Don't use `_type` field for nested paths

### LINKED ISSUE #24362: Rethink how to index nested documents when types are gone
Currently nested documents reuse the `_type` field in order to identify root documents from children: the value of the `type` field starts with `__` for children. However with types going away, we would probably like to stop indexing the `_type` field so we would need to find other ways to identify root/children.

For efficiency reasons, we need a fast query that identifies root documents. One way we could do that would be by adding a special field/value pair to root documents. However, we would probably only want to do that when there are nested mappings, which means we would have to reject adding `nested` objects to existing mappings.

### PR DESCRIPTION
**Pull request by romseygeek**
The `_type` field is not only used to store types (obsolete in 8.0) but also 
the nested paths of child documents.  This overload prevents us from removing
the `_type` field and `TypeFieldType`.

This commit changes nested field mappers to use a `_nested_path` field instead,
with some backwards-compatibility shims to ensure that pre-8.0 indexes still use
`_type`.

Closes #24362

### CODE REVIEW

**Comment by romseygeek** [comment]
@elasticmachine update branch

**Review by jtibshirani — COMMENTED** [review]
@romseygeek I think it would be helpful to separate this PR into two:
* Switch to `_nested_path` instead of `_type` to store nested paths.
* Then follow-up with a change to remove `TypeFieldMapper`.

This helps in isolating these two big changes, which are related but still distinct. It's also not clear to me whether we can just remove `TypeFieldMapper` in 8.0 -- some of the conversations we've had around API versioning seem to suggest that we need logic to accept (but ignore) references to `_type` in the search request. Separating the PR into two would let us make progress on reviewing the `_nested_path` change while we get clarity on the API versioning questions.

**Comment by romseygeek** [comment]
I've opened #51100 to deal with just adding the nested field mapper.

**Comment by jtibshirani** [comment]
Thanks for splitting this up! I'll let someone else (maybe @jpountz?) review #51100, since I'm not as familiar with the history/ context there.

**Pull request closed without merging**
