### PR TITLE
Fix missing node id prefix in startup logs

### PR DESCRIPTION
**Pull request by tlrx**
When `node.name` is not set, some log traces at startup time does not show the node id. It does not look nice as some traces have the id and some others haven't:

```
[2018-04-16T16:02:14,812][INFO ][o.e.n.Node               ] [] initializing ...
[2018-04-16T16:02:14,847][INFO ][o.e.e.NodeEnvironment    ] [P2NUhLl] heap size [989.8mb], compressed ordinary object pointers [true]
[2018-04-16T16:02:14,848][INFO ][o.e.n.Node               ] node name [P2NUhLl] derived from node ID [P2NUhLlQTkmAHzlNM4HF2A]; set [node.name] to override
[2018-04-16T16:02:14,849][INFO ][o.e.n.Node               ] version[7.0.0-alpha1-SNAPSHOT], ... ]
[2018-04-16T16:02:14,849][INFO ][o.e.n.Node               ] JVM arguments [-Xms1g, -Xmx1g, ...]
[2018-04-16T16:02:14,849][WARN ][o.e.n.Node               ] version [7.0.0-alpha1-SNAPSHOT] is a pre-release version of Elasticsearch and is not suitable for production
...
[2018-04-16T16:02:16,373][INFO ][o.e.d.DiscoveryModule    ] [P2NUhLl] using discovery type [zen]
[2018-04-16T16:02:16,642][INFO ][o.e.n.Node               ] initialized
```

We can improve this a bit in order to make startup logs parsing easier (and to not hurt my eyes):

```
[2018-04-16T16:02:14,812][INFO ][o.e.n.Node               ] [] initializing ...
[2018-04-16T16:02:14,847][INFO ][o.e.e.NodeEnvironment    ] [P2NUhLl] heap size [989.8mb], compressed ordinary object pointers [true]
[2018-04-16T16:02:14,848][INFO ][o.e.n.Node               ] [P2NUhLl] node name [P2NUhLl] derived from node ID [P2NUhLlQTkmAHzlNM4HF2A]; set [node.name] to override
[2018-04-16T16:02:14,849][INFO ][o.e.n.Node               ] [P2NUhLl] version[7.0.0-alpha1-SNAPSHOT], ... ]
[2018-04-16T16:02:14,849][INFO ][o.e.n.Node               ] [P2NUhLl] JVM arguments [-Xms1g, -Xmx1g, ...]
[2018-04-16T16:02:14,849][WARN ][o.e.n.Node               ] [P2NUhLl] version [7.0.0-alpha1-SNAPSHOT] is a pre-release version of Elasticsearch and is not suitable for production
...
[2018-04-16T16:02:16,373][INFO ][o.e.d.DiscoveryModule    ] [P2NUhLl] using discovery type [zen]
[2018-04-16T16:02:16,642][INFO ][o.e.n.Node               ] [P2NUhLl] initialized
```

### CODE REVIEW

**Review by DaveCTurner — COMMENTED** [review]
Good plan! Shame about the first `initializing ...` line :)

Does it make sense to remove the node name from this message, since it now appears twice?

```
[2018-04-16T16:02:14,848][INFO ][o.e.n.Node               ] [P2NUhLl] node name [P2NUhLl] derived from node ID [P2NUhLlQTkmAHzlNM4HF2A]; set [node.name] to override
```

**Comment by tlrx** [comment]
> Shame about the first initializing ... line :)

Well, at least it shows that the node.name is unknown when initializing the node. And it also respects the same log pattern :)



> Does it make sense to remove the node name from this message, since it now appears twice?

Yes, I removed it.

Thanks for the review!

**Review by DaveCTurner — APPROVED** [review]
Brill. LGTM.

**Comment by tlrx** [comment]
Thanks @DaveCTurner :)

**Pull request merged**
