### PR TITLE
Make ActionListener runAfter and runBefore Chainable

### PR DESCRIPTION
**Pull request by original-brownbear**
Doing the same we did for `.map` and `.delegate` methods here
to make using these methods a little less verbose and align
the style of all the delegation types on `ActionListener`.

### CODE REVIEW

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/2  (unrelated ML failure that I opened an issue for)

**Comment by original-brownbear** [comment]
Jenkins update branch

**Comment by original-brownbear** [comment]
@elasticmachine update branch

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/2 (yet again unrelated ML failure)

**Review by rjernst — COMMENTED** [review]
I'm concerned about the semantics implied by making this an instance method rather than a static. One might think that the listener on which runAfter or runBefore is called will be modified, and not realize they need to use the returned listener. What are the problems with keeping this as a static method for composition?

**Comment by original-brownbear** [comment]
Sorry for the delay here @rjernst 

> What are the problems with keeping this as a static method for composition?

Mainly, that doing chaining allowed for some optimisations (keeping stacks shallower and avoiding some memory savings around `.map()` in particular) and now it's weird to have the static calls for some delegation and non-static chaining for other isn't it?

**Comment by rjernst** [comment]
To me the semantic confusion outweighs the simplicity advantage here. It is far too easy to call the method and not use the new returned listener.

**Comment by original-brownbear** [comment]
Fair point :) @rjernst I'll drop this one

**Pull request closed without merging**
