### PR TITLE
Ensure index is green in SimpleClusterStateIT.testIndicesOptions()

### PR DESCRIPTION
**Pull request by tlrx**
SimpleClusterStateIT testIndicesOptions failed in #44817 because it tries to close an index at the beginning of the test. With random index settings, it is possible that the index has a high number of shards (10) and replicas (1), which means that on CI this index can take time to be fully allocated.

The close index request can fail in the case where replicas are still recovering operations. This pull request adds a simple ensureGreen() at the beginning of the test to be sure that all replicas are started before trying to close the index.

### CODE REVIEW

**Review by original-brownbear — APPROVED** [review]
LGTM :)

**Comment by tlrx** [comment]
@elasticmachine run elasticsearch-ci/1
@elasticmachine run elasticsearch-ci/packaging-sample

**Comment by tlrx** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample

**Comment by tlrx** [comment]
@elasticmachine update branch

**Comment by tlrx** [comment]
Thanks @original-brownbear

**Pull request merged**
