### PR TITLE
Add unreleased version 6.3.2

### PR DESCRIPTION
**Pull request by mayya-sharipova**

### CODE REVIEW

**Comment by tomcallahan** [comment]
Shouldn't we also change the version in buildSrc/version.properties?

**Comment by nik9000** [comment]
> Shouldn't we also change the version in buildSrc/version.properties?

Only on the 6.3 branch.

**Comment by tomcallahan** [comment]
Ah OK, thanks

**Review by nik9000 — APPROVED** [review]
I'm *fairly* sure this is right. If `./gradlew verifyVersions :test:framework:test` likes it then so do I.

**Comment by mayya-sharipova** [comment]
Thanks for feedback, I just followed the advice and directly merged.  Closing this PR now

**Pull request closed without merging**
