### PR TITLE
Add to SearchUsages queries generated by the vector tiles API

### PR DESCRIPTION
**Pull request by iverase**
It is possible to get the current the type of queries and how many times the queries has been executed in a cluster by executing the following API command:

```
GET /_cluster/stats?filter_path=indices.search.queries
```

This stats are collected when parsing the search request.

This is not true for the vector tiles search API as it has their own parser and it is not registering their usage. Therefore to be consistent with the search API, let's register the queries used via the vector tiles API.

### CODE REVIEW

**Review by craigtaverner — APPROVED** [review]
LGTM

**Comment by iverase** [comment]
This is failing because of https://github.com/elastic/elasticsearch/pull/113452

**Comment by iverase** [comment]
@elasticmachine update branch

**Comment by iverase** [comment]
@elasticmachine update branch

**Pull request merged**
