### PR TITLE
Remove CompletableContext and replace it with StepListener

### PR DESCRIPTION
**Pull request by original-brownbear**
These two mostly do the same, making `CompletableContext` and the compatibility layer between the context and `ActionListener` redundant.
Removing it here to in part to set up a clean solution for #77999.

### CODE REVIEW

**Review by DaveCTurner — COMMENTED** [review]
Do we even need `StepListener` or could it just be a bare `ListenableFuture`? I don't see any funky chaining here.

**Comment by original-brownbear** [comment]
@DaveCTurner I was planning on doing some chaining here next :) Also, more importantly, I didn't want to bet on the fact that we never double invoke the listener/context (we certainly do in some tests). `ListenableFuture` would throw on double invocation while `StepListener` behaves exactly like the context here, so it seemed much safer.

**Comment by DaveCTurner** [comment]
Maybe use `ActionListener#notifyOnce` then?

I think `StepListener` helped readability when it was introduced but I'm not sure it's really needed any more. I consider it tech debt :)

**Comment by original-brownbear** [comment]
It's a fair point, how about https://github.com/elastic/elasticsearch/pull/90415/commits/6cb0607524d7011bd2d3246036e05fbafe4cf75a doing away with `StepListener` and using either `ListenableFuture` where I'm 100% sure we're safe from double-invocation and manually guarding elsewhere. `notifyOnce` is kind of annoying in most spots, because it hides away the `addListener` and we need a second reference for the listenable future anyway so I liked manually guarding better.

**Review by DaveCTurner — APPROVED** [review]
I like it, yes. LGTM

**Pull request merged**
