### PR TITLE
Ensure rest api specs are always copied before using test classpath

### PR DESCRIPTION
**Pull request by mark-vieira**
This PR fixes an issue with odd cache misses for tasks that track the test runtime classpath as an input, such as checkstyle. Essentially, if the `copyRestSpec` task happens to run before checkstyle, then it would be included as an input, if it ran after, it wouldn't. This means that the hashes for a task like checkstyle would be different for the same inputs (git checkout) simply due to the inherit randomness of task execution order.

I initially started down the path of separating the `copyRestSpec` task such that it had it's own output directory but that rabbit hole got deeper and deeper as x-pack and other projects define their own specs which have to be aggregated. Due to the way our tests search for these on the classpath that was going to turn into more of a refactoring that I wanted just to fix this cache miss issue so for now we just say that the rest specs are a dependency of the `test` sourceset output. This does mean that you'll have to copy the specs to run unit tests, but I'm not sure any of the projects in question even have any unit tests so this is likely a non-issue.

### CODE REVIEW

**Comment by mark-vieira** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by mark-vieira** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by mark-vieira** [comment]
@elasticmachine run elasticsearch-ci/1

**Review by rjernst — APPROVED** [review]
LGTM

**Review by alpar-t — APPROVED** [review]
LGTM

**Pull request merged**
