### PR TITLE
Introduce templating support to timezone/locale in DateProcessor

### LINKED ISSUE #24024: Ingest Date Processor should support templated timezone/locale
There are times that clients ingesting into ES set variable date information.
It would be useful to have these fields in the DateProcessor be template-strings so 
that these clients can appropriately configure the pipeline based on data in the 
document's fields.

For example: Beats supports this now: https://github.com/elastic/beats/pull/3902 (and modules discussion: https://github.com/elastic/beats/issues/3898#issuecomment-292532578)

### PR DESCRIPTION
**Pull request by talevy**
Sometimes systems like Beats would want to extract the date's timezone and/or locale
from a value in a field of the document. This PR adds support for mustache templating
to extract these values.

Closes #24024.

### CODE REVIEW

**Comment by talevy** [comment]
I've debated over-optimizing to bypass the templating for the default use-case... but after running a rally benchmark, I've decided that would just complicate things. I did not see any glaring differences in performance. Probably due to large initial overhead of ingest json deserialization.

**Review by martijnvg — COMMENTED** [review]
In general this looks good. Can you also add instructions how to use this and an example in the docs?

**Comment by martijnvg** [comment]
> but after running a rally benchmark, I've decided that would just complicate things. I did not see any glaring differences in performance. 

I agree. Also for other processors we do not do this either. (set processor and its field parameter)

**Comment by talevy** [comment]
@martijnvg thanks for taking a look. I will add more example docs to the date processor

**Pull request merged**
