### PR TITLE
Switch default logs template to search all fields by default

### LINKED ISSUE #99872: [Logs] Switch default logs templates to use `default_field[*]´
In Elasticsearch, currently for the `logs-*-*` index template, `default_field: ["message"]` is used. This issue is to discuss the removal of [this setting](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/core/template-resources/src/main/resources/logs-settings.json#L10) which means falling back to the default of Elasticsearch which is `default_field: ["*"]`.

In the past there have been issues around using `default_field: ["*"]` for data especially in the context of field explosion. With the introduction of `true_until_limit` (https://github.com/elastic/elasticsearch/pull/96235) this problem will be solved. Instead of users increasing the limit and potentially hit maxClauseCount issue, a soft limit is introduced. More details about what changed in the stack to make this possible can be found [here](https://docs.google.com/document/d/1EA6jeWM1VElGuQwEXzxDZ1hNmVYPCDIGLxU_zl0xeR4/edit).

At first, this would be adopted in the logs template but would expected to eventually make its way into integrations through Fleet. This means logic can be removed to field and will make integrations using dynamice ECS templates work again, see https://github.com/elastic/integrations/issues/7582 for more details.

## Search must always work
 
For a good search experience, it is required that `allow_partial_results: true` is set as otherwise it is possible, that overall search could still fail if a single shard has too many fields inside. It needs to be confirmed in Kibana uses this by default.

## Open question

* Data sing indices: There might be "data sink" indices which might still reach the limit of 1000 fields and a user might want to increase the limit of 1000. It is not clear how a user could do this today or if we need this.
* Breaking change: Could this be considered in any way a breaking change?

## Links

* Dynamic ECS field templates and default_field: https://github.com/elastic/integrations/issues/7582
* [2023-09 Next steps on default fields search](https://docs.google.com/document/d/1EA6jeWM1VElGuQwEXzxDZ1hNmVYPCDIGLxU_zl0xeR4/edit#heading=h.8t1pq71mff4x)
* [Default field docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html#index-query-default-field)
* Reference to [default_field message](https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/core/template-resources/src/main/resources/logs-settings.json#L10)

### PR DESCRIPTION
**Pull request by eyalkoren**
Closes #99872 

Added a test that would fail prior to this change.
This adds the risk of hitting the maxClauseLimit error, so a fix for #102378 should follow up

### CODE REVIEW

**Comment by eyalkoren** [comment]
@elasticmachine run elasticsearch-ci/docs

**Review by ruflin — COMMENTED** [review]
The code change LGTM.

I suggest we also have some docs ready around this that 

1. describes the behaviour when searching on logs-*-* form 8.x on
2. describes how the behaviours could be changed by to `message` only by using logs@custom or similar

**Review by felixbarny — APPROVED** [review]

**Comment by ruflin** [comment]
@mdbirnstiehl Can you help us on where these docs would fit in?

**Comment by mdbirnstiehl** [comment]
@ruflin @eyalkoren We don't really document anything about specific component templates or default index templates aside from the fact that they exist (aside from some small blurbs in the "Parse logs" doc. Adding something about maxClauseLimit and changing the default_field to the troubleshooting could be a short term solution, but it seems like long-term there should be a reference section in the logs docs that explains the templates available to our users and how they can use them.

**Comment by ruflin** [comment]
>  long-term there should be a reference section in the logs docs that explains the templates available to our users and how they can use them. Maybe starting with logs@custom?

Agree. Can you follow up with an issue. +1 on starting with `logs@custom`. Please also have a chat with the docs members from the ingest team as they might already have bits on this or you can collaborate.

**Comment by felixbarny** [comment]
Here are some places in our docs that mention `*@custom` component templates and pipelines: https://github.com/search?q=org%3Aelastic+%40custom+language%3AAsciiDoc&type=code&l=AsciiDoc

**Comment by mdbirnstiehl** [comment]
Sounds good, I'll create an issue, check out the current `@custom` mentions, and reach out to the ingest team.

**Pull request merged**
