### PR TITLE
Remove all @AwaitsFix in CcrRollingUpgradeIT

### PR DESCRIPTION
**Pull request by arteam**
We can enabled all tests after #60054 has been merged

See #76765

### CODE REVIEW

**Review by dnhatn — APPROVED** [review]
LGTM. Thanks @arteam!

**Comment by arteam** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by dnhatn** [comment]
I think we need to wait for https://github.com/elastic/elasticsearch/pull/76786 to fix the BWC issue.

**Comment by dnhatn** [comment]
@elasticmachine update branch.

**Comment by dnhatn** [comment]
@elasticmachine update branch

**Comment by arteam** [comment]
@elasticmachine update branch

**Comment by arteam** [comment]
@elasticmachine update branch

**Pull request merged**
