### PR TITLE
Reindex and friends fail on RED shards

### PR DESCRIPTION
**Pull request by henningandersen**
Reindex, update by query and delete by query would silently disregard
RED/unavailable shards, thus not copying, updating or deleting matching
data in those shards. Now use `allow_partial_search_results=false` to
ensure these operations fail if the search crosses an unavailable chard.

Added the option to explicitly specify `allow_partial_search_results=true`
for reindex only (seemed too strange for update/delete by query).

Relates #45739 and #42612

### CODE REVIEW

**Comment by henningandersen** [comment]
We may want to consider still supporting running reindex with allow_partial_search_results=true, since this could be a partial recovery path for indices that are missing shards

**Comment by henningandersen** [comment]
@elasticmachine update branch

**Comment by zuketo** [comment]
After some investigating, I can't find a use case for using allow_partial_search_results=true for reindex. I think there are valid search use cases for the allow_partial_search_results option, however, when upgrading or migrating data (with reindex), I would focus on correcting the red shards before running reindex.

**Comment by henningandersen** [comment]
Thanks @zuketo , as agreed on another channel, I have now reverted the ability to run with `allow_partial_search_results=true` (except for remote index against versions earlier than 6.3).

**Review by Tim-Brooks — APPROVED** [review]
LGTM

**Pull request merged**
