### PR TITLE
Use any index specified by .watches for Watcher

### PR DESCRIPTION
**Pull request by AthenaEryma**
Previously, Watcher only attached its listener to indices that started
with the prefix `.watches`, which causes Watcher to silently fail to
schedule newly created Watches if the `.watches` alias is redirected to
an index that does not start with `.watches`.

Watcher now attaches the listener to all indices, so that Watcher can
respond to changes in which index has the `.watches` alias.

All tests now randomly use a concrete index which does not start
with `.watches` (same for `.triggered_watches`), as well this behavior
being explicitly tested.

Relates to https://github.com/elastic/elasticsearch/issues/39478

### CODE REVIEW

**Comment by gwbrown** [comment]
I did some basic tests with Rally and this doesn't seem to noticeably impact indexing performance, but I've only done a couple of trials.

**Comment by gwbrown** [comment]
While I've adjusted the tests to randomly use non-prefixed concrete indices for `.watches` and `.triggered_watches`, I've run `:x-pack:plugin:watcher:check` many times locally with this option forced on (that is, using only non-prefixed indices) to ensure that this is stable.

**Comment by gwbrown** [comment]
It's worth noting that the behavior of Watcher when changing the alias is still the same as it was before when it was restricted to prefixed index names: If the new index pointed to by `.watches` contains the same watches as the old index, everything will keep working just fine.  If the contents are different, Watcher will need to be restarted to force it to reload watch definitions from the index.

**Review by jakelandis — APPROVED** [review]
LGTM

**Pull request merged**
