### PR TITLE
Remove working directory

### PR DESCRIPTION
**Pull request by tlrx**
This commit removes the unused working directory and its associated environment variable "WORK_DIR"

### CODE REVIEW

**Comment by s1monw** [comment]
LGTM

**Comment by tlrx** [comment]
I just rebased on master and add few changes due to recent pull request merges.

**Comment by rmuir** [comment]
+1

**Comment by s1monw** [comment]
@tlrx can we pull this in?

**Comment by tlrx** [comment]
@s1monw Done

**Pull request merged**
