### PR TITLE
Allow Lucene directory implementations to estimate their size

### PR DESCRIPTION
**Pull request by tlrx**
This change introduces a ByteSizeDirectory abstract class that can be implemented to expose an estimate of the directory files size in the store stats. 

It allows plugins with custom Lucene directory implementation to extend this class and expose their own estimate of the directory size.

Relates ES-5995

### CODE REVIEW

**Review by kingherc — APPROVED** [review]
Looks straightforward, cannot think of negative implications. LGTM

**Review by henningandersen — APPROVED** [review]
LGTM.

Notice that once we disable the disk threshold decider through `index.routing.allocation.disk.watermark.ignore`, the `size` will be 0, but the total data set size will still contain the full number. Just mentioning in case there is follow-up work or monitoring relying on this.

**Comment by henningandersen** [comment]
Ah, sorry, mixed up the two. I am still ok with this for now, but ideally size would become 0 eventually, since that is how it was defined for frozen tier when we added `total_data_set_size`.

**Comment by tlrx** [comment]
Thanks Iraklis and Henning

**Pull request merged**
