### PR TITLE
Enable _tier based coordinator rewrites for all indices (not just mounted indices)

### PR DESCRIPTION
**Pull request by andreidan**
As part of https://github.com/elastic/elasticsearch/pull/114990 we enabled using the `_tier`
field as part of the coordinator rewrite in order to skip 
shards that do not match a `_tier` filter, but only for 
fully/partially mounted indices. 

This PR enhances the previous work by allowing a coordinator
rewrite to skip shards that will not match the `_tier` query for
all indices (irrespective of their lifecycle state i.e. hot and warm 
indices can now skip shards based on the `_tier` query)

Note however, that hot/warm indices will not automatically
take advantage of the `can_match` coordinator rewrite 
(like read only indices do) but only the search requests that
surpass the `pre_filter_shard_size` threshold will.

Relates to [#114910](https://github.com/elastic/elasticsearch/issues/114910)

### CODE REVIEW

**Comment by andreidan** [comment]
@elasticmachine update branch

**Comment by andreidan** [comment]
@elasticmachine update branch

**Comment by andreidan** [comment]
@elasticmachine update branch

**Comment by andreidan** [comment]
@elasticmachine update branch

**Comment by andreidan** [comment]
@elasticmachine update branch

**Comment by andreidan** [comment]
@elasticmachine update branch

**Comment by andreidan** [comment]
restarting test due to https://github.com/elastic/elasticsearch/issues/116003

**Comment by andreidan** [comment]
@elasticmachine run elasticsearch-ci/part-3

**Comment by andreidan** [comment]
@elasticmachine update branch

**Comment by andreidan** [comment]
@elasticmachine update branch

**Review by javanna — APPROVED** [review]
LGTM thanks!

**Comment by andreidan** [comment]
@elasticmachine update branch

**Pull request merged**
