### PR TITLE
Tests: disable testRandomGeoCollectionQuery on tiny polygons

### PR DESCRIPTION
**Pull request by imotov**
Due to https://issues.apache.org/jira/browse/LUCENE-8634 this test
may fail if a really tiny polygon is generated. This commit checks for
tiny polygons and skips the final check, which is expected to fail
until the lucene bug is fixed and new version of lucene is released.

### CODE REVIEW

**Comment by imotov** [comment]
run the gradle build tests 2

**Review by iverase — APPROVED** [review]
LGTM, just one question, how did you come up with the number 8.4e-8?

**Comment by imotov** [comment]
> LGTM, just one question, how did you come up with the number 8.4e-8?

@iverase that was my interpretation of your comment on the Lucene  issue:

> The encoding is very fine grid with cells of size 8.39e-8 degrees X 8.39e-8 degrees.

Do you think it was a wrong interpretation? Should it be higher?

**Comment by imotov** [comment]
run the gradle build tests 1

**Comment by iverase** [comment]
no, I was wondering if that number came from deep testing. That would probe the comment :)  

Actually is imprecise, I took the values from here:

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-geo-bounding-box-query.html#_notes_on_precision

But we should be ok with the values you give.

**Comment by imotov** [comment]
> if that number came from deep testing.

It didn't come from deep testing, but it was somewhat verified by running these tests for about 10,000 iterations to make sure that this value is sufficiently large for the troublesome polygons to be ignored.

**Comment by imotov** [comment]
run the gradle build tests 1

**Pull request merged**
