### PR TITLE
Properly remove security index recovered state consumer

### PR DESCRIPTION
**Pull request by n1v0lg**
One of the security index state change listeners attempts to remove itself once it has received the expected event.

However, since the consumer is a lambda, `this` in `stateChangeListeners.remove(this);` actually refers to the enclosing class instance (`SecurityIndexManager.this`) which results in a noop and not an actual removal of the relevant consumer. 

This PR fixes this by converting the lambda to an anonymous class.  

It's technically a bug, but so minor that it doesn't warrant a bug changelog IMO; so I'm labelling it a non-issue instead.

### CODE REVIEW

**Comment by n1v0lg** [comment]
@elasticmachine update branch

**Comment by n1v0lg** [comment]
@elasticmachine update branch

**Comment by n1v0lg** [comment]
@elasticmachine update branch

**Review by slobodanadamovic — APPROVED** [review]
LGTM 

Nice catch! 👍

**Pull request merged**
