### PR TITLE
Refactor fielddata mappings.

### PR DESCRIPTION
**Pull request by jpountz**
The fielddata settings in mappings have been refactored so that:
- text and string have a `fielddata` (boolean) setting that tells whether it
  is ok to load in-memory fielddata. It is true by default for now but the
  plan is to make it default to false for text fields.
- text and string have a `fielddata_frequency_filter` which contains the same
  thing as `fielddata.filter.frequency` used to (but validated at parsing time
  instead of being unchecked settings)
- regex fielddata filtering is not supported anymore and will be dropped from
  mappings automatically on upgrade.
- text, string and _parent fields have an `eager_global_ordinals` (boolean)
  setting that tells whether to load global ordinals eagerly on refresh.
- in-memory fielddata is not supported on keyword fields anymore at all.
- the `fielddata` setting is not supported on other fields that text and string
  and will be dropped when upgrading if specified.

### CODE REVIEW

**Comment by bleskes** [comment]
It's great this is moving along

> and will be dropped when upgrading if specified.

I checked and couldn't find any clear indication in the 2.x docs that this is going happen. If people chose to disable doc_values in favor of field data their data will no longer be usable in 5.0 for things like sorting and aggs (right?) . Should we only disable field data on keyword fields for new indices?

**Comment by jpountz** [comment]
String and text fields will keep supporting fielddata (on by default on string fields, off by default on text fields, and this can can changed after the index has been created anyway with a mapping update call).

However numeric and boolean fields will indeed not support fielddata anymore, but this pull request is not related, it was done in #14082.

We have been recommending doc values since 1.3/1.4, then made it the default in 2.0 and the [2.x docs](https://github.com/elastic/elasticsearch/blob/2.x/docs/reference/mapping/params/doc-values.asciidoc#doc_values) are clear I think: `If you are sure that you don't need to sort or aggregate on a field, or access the field value from a script, you can disable doc values in order to save disk space`. So I think it is fine to remove fielddata support in 5.0 (except for string and text fields).

**Comment by clintongormley** [comment]
This PR doesn't include doc changes as @jpountz is planning to redo all the mapping docs in one big review in a different PR.

**Comment by bleskes** [comment]
> If you are sure that you don't need to sort or aggregate on a field, or access the field value from a script, you can disable doc values in order to save disk space

Fair enough, I think we should make it stronger though- something like "note that in 2.x you will still be able to use field data but that option will be removed in the future".

> This PR doesn't include doc changes

Indeed. I was referring to the documentation of 2.x and whether people that have chosen to not index doc values and use field data for sorting have had enough warning that this approach will not work in the next major version and require reindexing.

**Comment by jpountz** [comment]
@bleskes Should we add such a note in the 2.x docs next to the documentation I linked to?

**Comment by bleskes** [comment]
@jpountz I think it's better placed at the field data docs, no?

**Comment by jpountz** [comment]
OK I'll give it a try. I was thinking `doc_values` because users who will be in trouble are those who disabled doc values.

**Comment by rjernst** [comment]
LGTM, this is great!

**Pull request merged**
