### PR TITLE
Upgrade hppc to 0.9.1

### PR DESCRIPTION
**Pull request by rjernst**
This commit upgrades the hppc library. There are some improvements and
bug fixes, but this is also mostly to pull in a version which includes
an Automatic-Module-Name.

### CODE REVIEW

**Comment by rjernst** [comment]
Hppc removed it's seed based mixer methods, which we use in two places, random sampler agg and random score function. @jpountz @benwtrent should we implement our own seeded bit mixing function for those two uses? See https://github.com/carrotsearch/hppc/pull/10

**Comment by jpountz** [comment]
Maybe I'm missing something, but could we fix the few call sites that used a seed by replacing `BitMixer.mix(value, salt)` with `BitMixer.mix(value ^ salt)`?

**Comment by rjernst** [comment]
Thanks @jpountz. You are right, that should work. I will give it a try.

**Comment by rjernst** [comment]
Note though that as we are evaluating whether hppc is even necessary as a dependency anymore, we will likely want to create our own methods, I don't think there is anything special in the hppc versions that we could not implement ourselves, but I will leave that for a separate change.

**Comment by jpountz** [comment]
> I don't think there is anything special in the hppc versions that we could not implement ourselves

Agreed.

**Review by benwtrent — APPROVED** [review]

**Review by ChrisHegarty — APPROVED** [review]
LGTM.

**Review by mark-vieira — APPROVED** [review]

**Comment by rjernst** [comment]
Unfortunately this PR has languished. Looking back at the current test failures, the change in this version of hppc to no longer produce consistent iteration order causes a lot of test failures. While it would be good to weed those test issues out, the upgrade of hppc is not critical. I will close this PR for now, reopening in the future when we have a clear need to upgrade.

**Pull request closed without merging**
