### PR TITLE
Health report supports cluster resilience indicator.

### LINKED ISSUE #106640: Health report warning if fewer than 3 master-eligible nodes
We sometimes encounter on-prem users running with just one or two master-eligible nodes, and many more data-only nodes, despite the [docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/high-availability-cluster-design.html) indicating that a resilient cluster needs three master-eligible nodes. Typically we encounter such users when they've lost the master and their cluster can no longer form, which is a little late to be learning this lesson. Could we add a health indicator to warn users if they should make more of their nodes master-eligible?

More precisely, if there's only one node in the cluster then that's fine, no need to warn, a one-node cluster is clearly not resilient to failure. If there's ≥3 nodes in the cluster and ≥3 of them are master-eligible then that's also fine, but if there's ≥3 nodes in the cluster and <3 of them are master-eligible then that deserves a warning.

The two-node case is a little trickier: a two-node cluster is not totally unreasonable, but I can see how folks might assume such a cluster has enough redundancy to survive the loss of either node even though this isn't the case. In this case we [recommend](https://www.elastic.co/guide/en/elasticsearch/reference/current/high-availability-cluster-small-clusters.html#high-availability-cluster-design-two-nodes) making exactly one of the nodes master-eligible, so I think we should warn if a two-node cluster has two master-eligible nodes. That way folks can avoid the warning if they really want a two-node cluster, but only by doing something that fairly obviously makes the cluster not resilient to master failure.

### PR DESCRIPTION
**Pull request by howardhuanghua**
Fix https://github.com/elastic/elasticsearch/issues/106640, support cluster resilience indicator in health report.

### CODE REVIEW

**Comment by howardhuanghua** [comment]
CLA has been signed.

**Comment by nielsbauman** [comment]
Hi @howardhuanghua, thank you for your patience and for your interest in Elasticsearch!

I had a look at your PR, and I see that it doesn't include the note at the bottom of the issue description -- about having some sort of "grace period" before we alert. I do think that's something we're going to need before we can merge this feature. Unfortunately, there doesn't seem to be any existing functionality in place that could help us achieve this, meaning that we'd have to implement something from scratch to be able to implement that grace period. We'd probably need something along the lines of [CoordinationDiagnosticsService](https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/cluster/coordination/CoordinationDiagnosticsService.java). You're free to give that a go, but we're probably going to want to discuss that internally to align on an approach and I'm not sure yet when we'll be able to do so.

Are you still interested in continuing to work on this?

**Comment by howardhuanghua** [comment]
> Are you still interested in continuing to work on this?

Hi @nielsbauman , thanks for the review. Yes I could continue working on this issue.

**Comment by howardhuanghua** [comment]
> add a service that runs on every node (instead of a one-per-cluster service) that tracks the last time a master-eligible node left the cluster. That way, we can retrieve that timestamp in your indicator and implement a grace period before we actually report a non-green health status.

Hi @nielsbauman , just to clearfy the proposal. So the "grace period" means there is no master-eligible node restarting or left in this period right? For example, if all nodes in cluster are healthy without any restarting or left in like 5mins, then we report non-green health status? 

The proposal is each node run a independent service to track the time since last time successfully joined cluster, and master retrieve this time from each master-eligible node to detect if restart or node left happens?

**Comment by nielsbauman** [comment]
Hi @howardhuanghua, I think your understanding of grace period indeed matches what I had in mind: instead of immediately reporting a non-green health status when the cluster is not deemed resilient anymore, we wait 5 minutes after the last time a master-eligible node left the cluster until we report the non-green health status. We don't necessarily care about the reason why the node left (we probably also don't know in most cases); we can just need to know when a master-eligible node left the cluster (regardless of whether that was for restart/upgrade or some other reason).

Regarding the service, since each node runs the service, there's no need for the master node to retrieve anything from another node -- as every node, including the master, will already have this information (i.e. the latest timestamp when a master-eligible node left).

**Comment by nielsbauman** [comment]
Hi @howardhuanghua, I see there haven't been any updates on this PR for a while now. I hope you don't mind me closing this for now. Feel free to re-open if you're picking this back up again.

**Pull request closed without merging**
