### PR TITLE
Expose cache setting in UserAgentPlugin

### PR DESCRIPTION
**Pull request by spinscale**
The cache size setting was not registered. Also documentation has been added.

Review note: I think merging to master/7.x is fine, please veto if you disagree.

### CODE REVIEW

**Review by martijnvg — APPROVED** [review]
LGTM

**Comment by spinscale** [comment]
@elasticmachine update branch

**Comment by spinscale** [comment]
@elasticmachine update branch

**Comment by spinscale** [comment]
@elasticmachine run elasticsearch-ci/1

**Pull request merged**
