### PR TITLE
[8.x] Remove plugin classloader indirection (#113154)

### PR DESCRIPTION
**Pull request by rjernst**
Backports the following commits to 8.x:
 - Remove plugin classloader indirection (#113154)

### CODE REVIEW

**Comment by brianseeders** [comment]
@elasticmachine merge upstream

**Comment by xuanyuanbao** [comment]
> The Elasticsearch synonymous plugin is not working because the plugin class loader has been removed

I have a question, what can I do to make it work.

**Comment by rjernst** [comment]
Please ask questions on [our forum](https://discuss.elastic.co/c/elasticsearch). Closed issues are not normally tracked by developers and your comments can easily be overlooked.

> the plugin class loader has been removed

Plugins still have their own classloader. All that was removed was an old indirection layer that supported the transport client. If you have an issue building your plugin after this change, I suggest posting on the forums with details.

**Comment by xuanyuanbao** [comment]
ok, thank u,I have resolve it

**Pull request merged**
