### PR TITLE
State the option to reference templates in cluster

### PR DESCRIPTION
**Pull request by sypste**
The option to use templates already defined in the cluster is not explicitly stated in the docs, but can be found out from an error message.

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "x_content_parse_exception",
        "reason" : "[7:7] [script_with_id] failed to parse field [template]"
      }
    ],
    "type" : "x_content_parse_exception",
    "reason" : "[7:7] [rank_eval] failed to parse field [templates]",
    "caused_by" : {
      "type" : "x_content_parse_exception",
      "reason" : "[7:7] [script_with_id] failed to parse field [template]",
      "caused_by" : {
        "type" : "illegal_argument_exception",
        "reason" : "must specify either [source] for an inline script or [id] for a stored script"
      }
    }
  },
  "status" : 400
}
```

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by gwbrown** [comment]
@elasticmachine test this please

**Review by cbuescher — CHANGES_REQUESTED** [review]
Thanks @stemperps for this great addition to the docs and sorry this has slipped the radar for so long. I like the added example and would only suggest adding an additional link as a small change.

**Comment by cbuescher** [comment]
@elasticmachine test this please

**Comment by cbuescher** [comment]
@elasticmachine update branch

**Comment by cbuescher** [comment]
@elasticmachine test this please

**Review by cbuescher — APPROVED** [review]

**Comment by cbuescher** [comment]
@stemperps thanks for the changes, I'm trying to get this through our CI testing but we seem to have a problem with this somewhat older branch. I suspect https://github.com/elastic/elasticsearch/pull/63914 to be missing on this branch since its not actively under development any more. I'd like to port this to master and then merge it back to relevant 7.x branches if you don't mind.

**Comment by stemperps** [comment]
@cbuescher Sure, no worries

**Comment by cbuescher** [comment]
Tests are successful on master in #66169, but I'll merge this here to 7.6 and up to retain author etc...
I will slightly alter the commit message and title though before merging.

**Pull request merged**
