### PR TITLE
Retry failed peer recovery due to transient errors

### PR DESCRIPTION
**Pull request by Tim-Brooks**
Currently a failed peer recovery action will fail an recovery. This 
includes when the recovery fails due to potentially short lived 
transient issues such as network distruptions or circuit breaking 
errors.

This commit adds the concept of a retryable action. A retryable action
will be retryed in face of certain errors. The action will be retried
after an exponentially increasing backoff period. After defined time,
the action will timeout.

### CODE REVIEW

**Comment by tbrooks8** [comment]
As you will note I still need to implement cancellation. And implement the tests. Do we want this for all peer recovery actions @ywelsch? (file chunk, clean files, translog ops, prepare translog, etc, etc)

**Comment by ywelsch** [comment]
I think we should start with the two common ones (FILE_CHUNK and TRANSLOG_OPS). If we retry on disconnect, we will need to make sure that these operations are idempotent (as the operation might have been applied by the receiver before the disconnect). Idempotency will be trickier I think for the other operations, so let's limit ourselves to the two main ones.

**Comment by tbrooks8** [comment]
I have opened https://github.com/elastic/elasticsearch/pull/55091 to build out the framework to test exceptions that happen on the responder side (circuit breaker, rejected, etc).

**Comment by tbrooks8** [comment]
@original-brownbear This is the work I have been doing on adding some basic infrastructure for retrying transport actions. This PR implements it for peer recovery and we plan on adding it at some point for replication. The primary piece of common infrastructure is `RetryableAction`.

@ywelsch I looked into idempotency today. Neither file chunks or translog ops are idempotent. Although translog ops is just stats related. If I retry an already completed translog ops action I get the following assertion:

```
java.lang.AssertionError: total, if known, should be > recovered. total [71], recovered [142]
	at __randomizedtesting.SeedInfo.seed([F7578DA4C1324744]:0)
	at org.elasticsearch.indices.recovery.RecoveryState$Translog.incrementRecoveredOperations(RecoveryState.java:506)
	at org.elasticsearch.indices.recovery.RecoveryTarget.lambda$indexTranslogOperations$2(RecoveryTarget.java:379)
	at org.elasticsearch.action.ActionListener.completeWith(ActionListener.java:325)
	at org.elasticsearch.indices.recovery.RecoveryTarget.indexTranslogOperations(RecoveryTarget.java:340)
	at org.elasticsearch.indices.recovery.PeerRecoveryTargetService$TranslogOperationsRequestHandler.messageReceived(PeerRecoveryTargetService.java:459)
	at org.elasticsearch.indices.recovery.PeerRecoveryTargetService$TranslogOperationsRequestHandler.messageReceived(PeerRecoveryTargetService.java:416)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:63)
	at org.elasticsearch.transport.InboundHandler$RequestHandler.doRun(InboundHandler.java:256)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:691)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

If I retry an already completed file chunk action I get the following exception:

```
Caused by: java.lang.IllegalStateException: output for file [segments_2] has already been created
	at org.elasticsearch.indices.recovery.MultiFileWriter.openAndPutIndexOutput(MultiFileWriter.java:104) ~[classes/:?]
	at org.elasticsearch.indices.recovery.MultiFileWriter.innerWriteFileChunk(MultiFileWriter.java:118) ~[classes/:?]
	at org.elasticsearch.indices.recovery.MultiFileWriter$FileChunkWriter.writeChunk(MultiFileWriter.java:213) ~[classes/:?]
	at org.elasticsearch.indices.recovery.MultiFileWriter.writeFileChunk(MultiFileWriter.java:74) ~[classes/:?]
	at org.elasticsearch.indices.recovery.RecoveryTarget.writeFileChunk(RecoveryTarget.java:471) ~[classes/:?]
	at org.elasticsearch.indices.recovery.PeerRecoveryTargetService$FileChunkTransportRequestHandler.messageReceived(PeerRecoveryTargetService.java:533) ~[classes/:?]
	at org.elasticsearch.indices.recovery.PeerRecoveryTargetService$FileChunkTransportRequestHandler.messageReceived(PeerRecoveryTargetService.java:507) ~[classes/:?]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:63) ~[classes/:?]
	at org.elasticsearch.transport.InboundHandler$RequestHandler.doRun(InboundHandler.java:256) ~[classes/:?]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:691) ~[classes/:?]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[classes/:?]
	... 3 more
```

I think the file chunk action could be fixed in a relatively straightforward manner by modifying the `MultiFileWriter` to no-op respond to chunks that are already written. Since files are written sequentially and single files are not written concurrently, we could assert that the end pointer of a retry is the same as our current (local) pointer. I assume this work would generalize to retrying in bootstrap from remote.

I think the translog ops might be a little trickier? It looks like an `IndexResult` has a `created` field and `DeleteResult` has a found field. I'm not sure if it is safe to interrogate those fields and only count it as a "recovered operation" if it is true?

**Comment by tbrooks8** [comment]
@ywelsch 

I made some adjustments to this PR. I added the concept of a request sequence number to the file chunk requests and the translog ops requests. On the receiving node I used a local checkpoint tracker to mark successful requests received. This was necessary as I assume very large recoveries will include hundreds of thousands of requests. And it would be very memory consuming to keep state about them all around. Additionally, this mechanism could be used for all the various recovery requests. I just only implemented it for translog and file chunks at this time.

Unfortunately after speaking to @dnhatn about some recovery related things, I think that this approach has limited value with our current recovery architecture. It will work fine with rejected exceptions, circuit breaking exceptions, and connection exceptions when only the outgoing sockets from the sending node die. However, I imagine that when the outgoing sockets from the sending node die, the incoming sockets probably often die too. The problem here is that if the incoming sockets die, the receiving node will independently notice a failed recovery due the `START_RECOVERY` request failing. When that fails the receiving node will clean up its state and the existing recovery will not be able to continue.

**Comment by tbrooks8** [comment]
Alright, I opened #55274 which is an additional iteration on the PR. It adds the concept of target node "reestablishing" a peer recovery. Which would work in conjunction with the source node retrying network errors.

**Comment by tbrooks8** [comment]
Closing in favor of #55353 as a first step.

**Pull request closed without merging**
