### PR TITLE
Remove global block factory

### LINKED ISSUE #100105: [CI] EsqlDisruptionIT testFromSortWithTieBreakerLimit failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/lfe6he6gbt5g4/tests/:x-pack:plugin:esql:internalClusterTest/org.elasticsearch.xpack.esql.action.EsqlDisruptionIT/testFromSortWithTieBreakerLimit

**Reproduction line:**
```
gradlew ':x-pack:plugin:esql:internalClusterTest' --tests "org.elasticsearch.xpack.esql.action.EsqlDisruptionIT.testFromSortWithTieBreakerLimit" -Dtests.seed=9EC73CFBC60F4A -Dtests.locale=ar-AE -Dtests.timezone=Atlantic/Madeira -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.esql.action.EsqlDisruptionIT&tests.test=testFromSortWithTieBreakerLimit

**Failure excerpt:**
```
org.elasticsearch.common.breaker.CircuitBreakingException: [request] Data too large, data for [topn] would be [1040/1kb], which is larger than the limit of [1024/1kb]

  at __randomizedtesting.SeedInfo.seed([9EC73CFBC60F4A:828B82120B38619F]:0)
  at org.elasticsearch.common.breaker.ChildMemoryCircuitBreaker.circuitBreak(ChildMemoryCircuitBreaker.java:77)
  at org.elasticsearch.common.breaker.ChildMemoryCircuitBreaker.limit(ChildMemoryCircuitBreaker.java:167)
  at org.elasticsearch.common.breaker.ChildMemoryCircuitBreaker.addEstimateBytesAndMaybeBreak(ChildMemoryCircuitBreaker.java:104)
  at org.elasticsearch.compute.operator.BreakingBytesRefBuilder.grow(BreakingBytesRefBuilder.java:60)
  at org.elasticsearch.compute.operator.topn.SortableTopNEncoder.encodeLong(SortableTopNEncoder.java:20)
  at org.elasticsearch.compute.operator.topn.KeyExtractorForLong.nonNul(KeyExtractorForLong.java:41)
  at org.elasticsearch.compute.operator.topn.KeyExtractorForLong$ForVector.writeKey(KeyExtractorForLong.java:60)
  at org.elasticsearch.compute.operator.topn.TopNOperator$RowFiller.writeKey(TopNOperator.java:148)
  at org.elasticsearch.compute.operator.topn.TopNOperator$RowFiller.row(TopNOperator.java:141)
  at org.elasticsearch.compute.operator.topn.TopNOperator.addInput(TopNOperator.java:327)
  at org.elasticsearch.compute.operator.Driver.runSingleLoopIteration(Driver.java:191)
  at org.elasticsearch.compute.operator.Driver.run(Driver.java:129)
  at org.elasticsearch.compute.operator.Driver$1.doRun(Driver.java:285)
  at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
  at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
  at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983)
  at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
  at java.lang.Thread.run(Thread.java:1583)

```

### PR DESCRIPTION
**Pull request by dnhatn**
The global BlockFactory should work fine in production, where each Elasticsearch node runs in its own JVM process. However, this approach can lead to issues during testing, especially in IT tests. The same JVM process might get reused across multiple tests, resulting in situations where multiple IT tests inadvertently use the same instance of the global BlockFactory.

For instance, EsqlDisruptionIT fails because it accidentally uses the global BlockFactory initialized by [EsqlActionBreakerIT](https://github.com/elastic/elasticsearch/blob/ccc896d1284cb7a5fb7713110aedc1f8976f45c8/x-pack/plugin/esql/src/internalClusterTest/java/org/elasticsearch/xpack/esql/action/EsqlActionBreakerIT.java#L48), which has a limit set to 1KB. Another issue in IT tests is that multiple Elasticsearch nodes can share the same (single) global instance of the BlockFactory.

Closes #100105

This PR suggests removing the global BlockFactory since we are already passing it with the DriverContext.

### CODE REVIEW

**Comment by dnhatn** [comment]
run elasticsearch-ci/part-1

**Comment by dnhatn** [comment]
run elasticsearch-ci/part-2

**Comment by dnhatn** [comment]
Nik: EsqlDisruptionIT seems to fail more frequently on your machine compared to mine, possibly due to differences in CPU resources. I was able to reproduce reliably the problem on my machine using `org.gradle.workers.max=1`.

**Review by costin — APPROVED** [review]
LGTM - less code and easier to track it down.

**Review by ChrisHegarty — APPROVED** [review]
LGTM

**Comment by dnhatn** [comment]
@costin @ChrisHegarty Thanks for reviewing.

**Pull request merged**
