### PR TITLE
Closing a ReleasableBytesStreamOutput closes the underlying BigArray

### PR DESCRIPTION
**Pull request by jaymode**
This commit makes closing a ReleasableBytesStreamOutput release the underlying BigArray so
that we can use try-with-resources with these streams and avoid leaking memory by not returning
the BigArray. As part of this change, the ReleasableBytesStreamOutput adds protection to only
release the BigArray once.

In order to make some of the changes cleaner, the ReleasableBytesStream interface has been
removed. The BytesStream interface is changed to a abstract class so that we can use it as a
useable return type for a new method, Streams#flushOnCloseStream. This new method wraps a
given stream and overrides the close method so that the stream is simply flushed and not closed.
This behavior is used in the TcpTransport when compression is used with a
ReleasableBytesStreamOutput as we need to close the compressed stream to ensure all of the data
is written from this stream. Closing the compressed stream will try to close the underlying stream
but we only want to flush so that all of the written bytes are available.

Additionally, an error message method added in the BytesRestResponse did not use a builder
provided by the channel and instead created its own JSON builder. This changes that method to use
the channel builder and in turn the bytes stream output that is managed by the channel.

Note, this commit differs from 6bfecdf921a1941b48273d76551872df4062cfae in that it updates
ReleasableBytesStreamOutput to handle the case of the BigArray decreasing in size, which changes
the reference to the BigArray. When the reference is changed, the releasable needs to be updated
otherwise there could be a leak of bytes and corruption of data in unrelated streams.

This reverts commit afd45c14327cd0f8d155e5ac9740f48e8e39b09c.

### CODE REVIEW

**Comment by jaymode** [comment]
jenkins test this

**Comment by jaymode** [comment]
jenkins test this

**Comment by jaymode** [comment]
jenkins test this

**Comment by jaymode** [comment]
jenkins test this

**Comment by rjernst** [comment]
This seems odd to me. If there is an underlying stream that we wrap, we should be closing it. The problem then seems to me that we are wrapping/delegating a stream we should not be closing? To be clear, flushing on close seems ok, but only before doing the actual close. Hacking a wrapper to not call close when close is called seems like it could lead to errors in the future where we don't close the underlying stream when we should have.

**Comment by jaymode** [comment]
I agree that this is less than ideal. This is the second approach I have taken and this was given a LGTM in #23572; this PR is here to test in Jenkins because the previous pr had a bug that led to corrupted bytes but it never reproduced locally for me. 

A lot of the ugliness stems from compression and how deflate compressor works and the fact that closing a releasable bytes stream should release its resources, which is what this change does. the deflateoutputstream needs to be closed in order to write all of the bytes and it closes the output stream it is given. The same holds for an xcontentbuilder which closes the stream when getting the bytes. If you have a idea to simplify this that would be great but this fixes a potential leak of bytes that we keep track of.

**Comment by jaymode** [comment]
jenkins test this

**Comment by jaymode** [comment]
jenkins test this

**Pull request merged**
