### PR TITLE
Remove deprecated indices.get_aliases

### PR DESCRIPTION
**Pull request by Mpdreamz**
This has been deprecated since the first release of Elasticsearch 1.0

### CODE REVIEW

**Comment by javanna** [comment]
LGTM thanks @Mpdreamz . I had to do some digging to figure out when we had deprecated the api, it happened as part of #4539. I think it's ok to remove it, but I'd confirm with @rashidkpc to double check that kibana fully relies on the get index api now instead.

**Comment by Mpdreamz** [comment]
It is still used in kibana: https://github.com/elastic/kibana/blob/0186c55d4e6e02b6f2cf593636ae21a6c45eaa41/src/ui/public/index_patterns/_mapper.js#L76

**Comment by javanna** [comment]
@rashidkpc @simianhacker can you please comment on whether this is safe to remove in 3.0?

**Comment by dadoonet** [comment]
+1 to remove. It gives inconsistent results in some cases. See #15817.

**Comment by clintongormley** [comment]
Chatted to @rashidkpc who says that they will change kibana to use get_alias instead of get_aliases, so we can go ahead with this PR.

**Comment by clintongormley** [comment]
@Mpdreamz do you want to pick this up again?

**Comment by Mpdreamz** [comment]
@clintongormley self assigned, will send a PR tomorrow.

**Comment by rashidkpc** [comment]
@Mpdreamz is this going in to 5.0.0?

**Comment by Mpdreamz** [comment]
I rebased and resolved conflcts, @clintongormley is this OK to merge in master?

**Comment by clintongormley** [comment]
Fine by me.  @javanna could you have a look please?

**Comment by javanna** [comment]
I have failing tests with this change. There are REST tests for indices.get_aliases that need to be removed I think, plus these seem to use the api too:

```
  - org.elasticsearch.test.rest.RestIT.test {p0=indices.update_aliases/20_routing/Search Routing}
  - org.elasticsearch.test.rest.RestIT.test {p0=indices.update_aliases/20_routing/Index, Search, Default Routing}
  - org.elasticsearch.test.rest.RestIT.test {p0=indices.update_aliases/20_routing/Index, Default Routing}
  - org.elasticsearch.test.rest.RestIT.test {p0=indices.update_aliases/20_routing/Routing}
  - org.elasticsearch.test.rest.RestIT.test {p0=indices.update_aliases/20_routing/Search, Default Routing}
  - org.elasticsearch.test.rest.RestIT.test {p0=indices.update_aliases/20_routing/Index Routing}
```

@Mpdreamz can you run tests or do you want me to take this over? let me know what's best for you!

**Comment by Mpdreamz** [comment]
@javanna doh! fixing this right now

**Comment by Mpdreamz** [comment]
@javanna rebased, removed the rest tests for get indices and updated `update_aliases` tests and reran those. Apologies for missing those in the first place!

**Comment by javanna** [comment]
LGTM @Mpdreamz if tests are green, go merge it ;)

**Pull request merged**
