### PR TITLE
Update histogram-aggregation.asciidoc

### LINKED ISSUE #26122: Histogram Aggregation for values of long type
This is very similar to https://github.com/elastic/elasticsearch/issues/9545 but on histogram aggregation.

1. We have a field of 64-bit long type in our index. 

2. Suppose that I add a doc with a value of 9223372036854775807 for the field. 

3. With ES 5.x, a histogram aggregation query returns  
`   "aggregations":{
      "longCount":{
         "buckets":[
            {
               "key":9.223372036854776E18,
               "doc_count":1
            }
         ]
      }
   }
`
Whereas, with ES 1.7, below is returned. 
`
   "aggregations":{
      "longCount":{
         "buckets":[
            {
               "key":9223372036854775800,
               "doc_count":1
            }
         ]
      }
   }
`
This issues look similar to https://github.com/elastic/elasticsearch/issues/9545 where a precision problem was reported. I see in HistogramAggregationBuilder.java that double type is used for internal computations. Are these the same issue? Do you plan to fix (or document) it for histogram aggregation? 

Further, I noticed that the keys in the response are of double type regardless of how the type was configured for the field. The behavior seems to have changed from 1.x as well. Is that documented? 

Thanks-

### PR DESCRIPTION
**Pull request by bhupenchn**
Closes #26122

### CODE REVIEW

**Comment by rjernst** [comment]
I'm not sure buried within the histogram agg docs is the best place to note this important detail that is true for all aggregations operating on numerics.  Perhaps there is a more general location in the aggs docs it could be mentioned?

**Comment by colings86** [comment]
I agree with @rjernst that this doesn't just apply to histogram but to all numeric aggregations. We could put it in the [Aggregations overview](https://raw.githubusercontent.com/elastic/elasticsearch/master/docs/reference/aggregations.asciidoc#) section. The only problem I see with putting it there is that its not particularly visible to someone just looking at the documentation for a particular aggregation so I'm worried it will just not be seen and therefore there won't be much value in having added it to the documentation. On the other hand adding the same note to the page for every single aggregation sounds like a worse solution to me so maybe it is the best thing to do?

**Comment by polyfractal** [comment]
We could add a callout on each numeric agg that points to the more extended note in the overview?  Not wonderful, but perhaps a better solution?

**Comment by rjernst** [comment]
@bhupenchn Are you interested in making the alternative change suggested by @colings86?

**Comment by cbuescher** [comment]
@bhupenchn I'm sorry to have to close this PR for lack of response, hope you don't mind.

**Pull request closed without merging**
