### PR TITLE
Just another elasticsearch library

### PR DESCRIPTION
**Pull request by softctrl**
Just another elasticsearch library developed in Golang.

### CODE REVIEW

**Comment by softctrl** [comment]
Sorry, now i sign the CLA document.

**Comment by jimczi** [comment]
The link says that this project is not maintained and advises to use the official one. Are you planning to work on this project again ? If not, I don't think we should add a link to a repo that is not active anymore.

**Comment by softctrl** [comment]
So, to be honest with you at first i have the idea to use the official lib on my Golang projects. But the way that the official library was developed it do not solve all my problems, it ads  a lot of unnecessary complexity, and right now i am returning to evolve my lib.

**Comment by jimczi** [comment]
Ok thanks @softctrl , this is merged.

**Pull request merged**
