### PR TITLE
SQL: Fix bug in REPLACE function. Adds more tests to all string functions

### PR DESCRIPTION
**Pull request by astefan**
The bug made all inline testing with this function to throw exceptions apparently unrelated to the function itself. Added more tests to all other functions targetting the missing inline testing part.

### CODE REVIEW

**Review by nik9000 — APPROVED** [review]
Neat!

**Review by costin — APPROVED** [review]
LGTM

**Comment by astefan** [comment]
@elasticmachine test this, please!

**Review by matriv — APPROVED** [review]
LGTM

**Comment by astefan** [comment]
Pushed to 6.x as well through https://github.com/elastic/elasticsearch/commit/ba8c1d2c5ffc5c5110e56bca1ec3e0bd8d3125ec

**Pull request merged**
