### PR TITLE
Introduce faster approximate sinh/atan math functions

### LINKED ISSUE #41166: Support approximate trigonometric functions in GeoTileUtils
For the initial release of the [geotile_grid](https://www.elastic.co/guide/en/elasticsearch/reference/7.0/search-aggregations-bucket-geotilegrid-aggregation.html) aggregation, the tiles-lat/lon translations uses 
functions like atan(), sinh(), and sin().

org.apache.lucene.util.SloppyMath is used at times when approximate trig functions
using cos/sin tables are sufficient. This issue is open to explore the use of similar 
approximate methods and benchmark whether it makes sense to enable the usage 
of them within the aggregation to help speed the calculations

### PR DESCRIPTION
**Pull request by talevy**
This commit introduces a new class called ESSloppyMath
that is meant to reflect the purpose of Lucene's SloppyMath,
but add additional unimplemented faster alternatives to math functions.

The two that are used by geotile-grid a lot are sinh/atan. This commit also
switches that implementation to use these new functions.

In a quick elasticsearch rally benchmark for geotile-grid on Switzerland
data points, this shows a (1.22x) 22% speed-up over using Math's functions.

closes #41166.

### CODE REVIEW

**Review by iverase — APPROVED** [review]
LGTM

I wonder if we should port as well the function for `exp` and `expm1` but that can be done in a follow up PR.

**Comment by talevy** [comment]
thanks Ignacio. I wondered the same about `exp` and `expm1`. I decided to delay it since I thought these gains would be good enough and the change would be more minimal. I will follow-up and check to see how things change with the less accurate implementations

**Comment by iverase** [comment]
Sounds like a good plan to me

**Review by imotov — APPROVED** [review]
LGTM2. Except I am not 100% about the header treatment here.

**Comment by talevy** [comment]
update branch

**Comment by talevy** [comment]
@elasticmachine update branch

**Pull request merged**
