### PR TITLE
Add a note about using the `retry_failed` flag before accepting data loss

### PR DESCRIPTION
**Pull request by bleskes**
Relates to https://github.com/elastic/elasticsearch/issues/23199#issuecomment-280390691

### CODE REVIEW

**Review by DaveCTurner — COMMENTED** [review]
I think it'd be better to move the "Retry failed shards" section up to line 75, and separate it from the dangerous commands with a suitably scary heading (e.g. "Dangerously forcing primary allocation")

**Comment by bleskes** [comment]
@DaveCTurner I didn't want to break the commands into two sections, but upon further thinking I agree that's the best thing to do. I'll give it a shot.

**Comment by bleskes** [comment]
@DaveCTurner care to take another look?

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Pull request merged**
