### PR TITLE
Update IndexCommitListener.onNewCommit javadoc

### PR DESCRIPTION
**Pull request by tlrx**
The indication of commits being notified out-of-order was added after the comment https://github
.com/elastic/elasticsearch/pull/92017#discussion_r1036843206 has been discussed via another channel. At the time we discussed about calling the commit listener while holding a lock or not in the CombinedDeletionPolicy#onCommit method and we chose to not hold the lock, assuming some instructions reordering could happen.

That being said, the only usage of onCommit() method we really care is the one in org.apache.lucene.index.IndexFileDeleter#checkpoint( SegmentInfos segmentInfos, boolean isCommit) when isCommit is true. And it is only executed in
org.apache.lucene.index.IndexWriter#finishCommit while the intrinsic lock on the index writer instance is held, so commits should be notified
 in order.

This change updates the javadoc accordingly.

### CODE REVIEW

**Review by fcofdez — APPROVED** [review]

**Review by henningandersen — APPROVED** [review]
LGTM2

**Comment by tlrx** [comment]
@elasticmachine run elasticsearch-ci/packaging-tests-unix-sample
@elasticmachine run elasticsearch-ci/packaging-tests-windows-sample

**Comment by tlrx** [comment]
@elasticmachine update branch

**Comment by tlrx** [comment]
Thanks Francisco and Henning

**Pull request merged**
