### PR TITLE
Upgrade to lucene 7.7.2

### PR DESCRIPTION
**Pull request by romseygeek**
This brings in a number of lucene bug-fixes, including:

* LUCENE-8735: FilterDirectory.getPendingDeletions now forwards to the delegate
  even the method is not abstract in the super class. This prevents issues
  where our best effort in carrying on generations in the IndexWriter since pending
  deletions are swallowed by the FilterDirectory.

* LUCENE-8688: TieredMergePolicy#findForcedMerges now tries to create the
  cheapest merges that allow the index to go down to `maxSegmentCount` segments
  or less

* LUCENE-8785: Ensure new threadstates are locked before retrieving the number of 
  active threadstates.  This causes assertion errors and potentially broken field attributes 
  in the IndexWriter when . IndexWriter#deleteAll is called while actively indexing

* LUCENE-8809: Refresh and rollback concurrently can leave segment states unclosed

### CODE REVIEW

**Comment by romseygeek** [comment]
@elasticmachine run elasticsearch-ci/2

**Review by dnhatn — APPROVED** [review]
LGTM. We also need to adjust the Lucene version of 6.8 in 7.4, 7.5, and 8.0.

**Comment by romseygeek** [comment]
Thanks for the review @dnhatn!  I think we only need to adjust the version in 7.4 and 7.5, given that 8.0 has no reference to any 6x versions?

**Comment by dnhatn** [comment]
> I think we only need to adjust the version in 7.4 and 7.5, given that 8.0 has no reference to any 6x versions?

@romseygeek Yes, you're right.

**Pull request merged**
