### PR TITLE
[8.x] [ES|QL] Validate index name in parser (#112081)

### PR DESCRIPTION
**Pull request by fang-xing-esql**
# Backport

This will backport the following commits from `main` to `8.x`:
 - [[ES|QL] Validate index name in parser (#112081)](https://github.com/elastic/elasticsearch/pull/112081)

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

### CODE REVIEW

**Comment by fang-xing-esql** [comment]
@elasticsearchmachine merge upstream

**Comment by fang-xing-esql** [comment]
@elasticmachine merge upstream

**Comment by fang-xing-esql** [comment]
@astefan @bpintea Could either of you approve this backport when you come online on Monday?  Thank you!

**Review by astefan — APPROVED** [review]
LGTM

**Pull request merged**
