### PR TITLE
Windows service: Use JAVA_HOME environment variable in registry

### LINKED ISSUE #13521: Jvm registry string not updated after Java was updated
Hello,

There is an issue with elasticsearch-service if we update Java and we do not reinstall the elasticsearch-service.

In this key:
HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Apache Software Foundation\Procrun 2.0\elasticsearch-service-x64\Parameters\Java

There is a Jvm string value which points to for example: C:\Program Files\Java\jdk1.8.0_45\jre\bin\server\jvm.dll

If you uninstall java u45 and update to a newer java, elastic search service stops working because it has an outdated reference.

### PR DESCRIPTION
**Pull request by gmarz**
This allows for updating Java without having to re-install the service.

Closes #13521

@Mpdreamz @russcam mind reviewing?

### CODE REVIEW

**Comment by russcam** [comment]
LGTM :+1:

**Comment by Mpdreamz** [comment]
Lgtm but we should document that updating across JVM types is still unsupported right?

If this resolves to a JRE and the updated JAVA_HOME is SE the dll ref might still be broken.

**Comment by gmarz** [comment]
@Mpdreamz that's a great point, and yea we should definitely document it.  

Linking https://github.com/elastic/elasticsearch/issues/16455 as a reminder to mention this when we update the docs.

**Comment by gmarz** [comment]
Merged to master and back ported to 2.0-2.x

**Pull request merged**
