### PR TITLE
[Cloud Security]Fix Cloud Security Package indices' deletion step error for ilm policy

### PR DESCRIPTION
**Pull request by Omolola-Akinleye**
[SDH Ticket  Cannot execute ILM policy delete step on CSPM findings logs](https://github.com/elastic/kibana/issues/197390) was created  a few weeks ago.  [Discussion Thread](https://github.com/elastic/kibana/issues/197390#issuecomment-2432697890) between product manager, engineering and sdh engineer on two proposed solutions:
 * Short Term solution:  Add delete privileges for  `logs-cloud_security_posture.-*  to prevent deletion phase execution error when the `logs-cloud_security_posture.-*`  exceeds the retention period(180 days). There are also has been similar [SDH Cannot execute ILM policy delete step ](https://github.com/elastic/kibana/issues/121244) with  elevated deleted privileges on [Endpoint/APM data streams](https://github.com/elastic/elasticsearch/blob/505c54eb94c71b694d44b8cf424be7ab5894e2e5/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/store/KibanaOwnedReservedRoleDescriptors.java#L270). 

 * Long Term solution: Migrate our data streams from ILM to use DLM
 
 This PR focuses on the short term solution which add the `logs-cloud_security_posture.-*` index under the `kibana_system` role with deletion privileges to prevent a failed deletion error when the index enters the [deletion phase for the ILM lifecycle](https://github.com/elastic/integrations/blob/60fcb22e3cbd129e0bbdbb9cb7e5d5ed6bad220c/packages/cloud_security_posture/data_stream/findings/elasticsearch/ilm/default_policy.json#L17).

```
{
"failed_step": "delete",
"step_info": {
"type": "security_exception",
"reason": "action [indices:admin/delete] is unauthorized for user [kibana_system] with effective roles [kibana_system] on indices [.ds-logs-cloud_security_posture.findings-default-2024.03.15-000001], this action is granted by the index privileges [delete_index,manage,all]"
}
}
``` 

[Investigation Ticket ](https://github.com/elastic/security-team/issues/7646#top) to migrate Cloud Security Data streams from ILM to DLM.

### CODE REVIEW

**Comment by SiddharthMantri** [comment]
Hi @Omolola-Akinleye! Can the PR description be updated with links to any discussions and issues around this change? We’d also like to know the reason for the change and the parts of Kibana where this elevated permission will be needed. Thank you!

**Comment by Omolola-Akinleye** [comment]
> Hi @Omolola-Akinleye! Can the PR description be updated with links to any discussions and issues around this change? We’d also like to know the reason for the change and the parts of Kibana where this elevated permission will be needed. Thank you!

Absolutely! Here is the updated description and let me know if you need any questions!

**Review by SiddharthMantri — APPROVED** [review]
Thanks @Omolola-Akinleye for the updated description. LGTM! Can you also add a link to the issue that focuses on the long term solution for this? Not a blocker - just helpful for future revisits when auditing `kibana system` privileges.

**Comment by Omolola-Akinleye** [comment]
@SiddharthMantri  I added the the[ investigation ticket](https://github.com/elastic/security-team/issues/7646#top) in description as well.

**Pull request merged**
