### PR TITLE
Improve efficiency of BoundedBreakIteratorScanner fragmentation algorithm (the 2nd)

### PR DESCRIPTION
**Pull request by thelink2012**
See #73569 for the issue this tries to solve. See PR #73785 for an explanation of the algorithm.

The previous PR had to be reverted due to it causing tests to fail in Kibana (see elastic/kibana#104466).

One of such failures was caused by `targetEndOffset` being a `int` but having a possibility of storing something bigger than that (more precisely for the Kibana tests, `if (targetEndOffset + 1 > textEndIndex)` overflowed). Commit e2635198d023fa0ef4b4c7132909d4da19e45574 in this PR fixes that.

There were still some failing tests after that. Needs investigation.

### CODE REVIEW

**Comment by jimczi** [comment]
@elasticmachine ok to test

**Review by jimczi — APPROVED** [review]
Thanks for fixing the overflow and adding the test @thelink2012.
We should be more strict with the range of passage size that we accept but that's outside of the scope of this PR. I'll merge soon.

**Comment by thelink2012** [comment]
Hey Jim,

Thanks for looking. Though this code isn't ready for merging. This still
produces some failures in Kibana's test suite.

I'd be grateful if you could take a look at these, since I had some trouble
setting up Kibana in order to reproduce.

Best

**Comment by jimczi** [comment]
Ok, thanks. Although Kibana shouldn't rely on the passage size to highlight the text entirely. I'll investigate.

**Comment by thelink2012** [comment]
I see there's this new `Check changelog` but I haven't found any documentation on how to fill these YML fields. I've seen examples in other PRs, but would like to make sure I have to fill `area' with `Search/Highlighting` and `type` with `enhancement`.

**Comment by thelink2012** [comment]
Hi @mark-vieira. Hope you are doing well! Since you switched version labels, i wonder whether you could help me move this PR forward? Perhaps the PR needs an assignee (which was `@jimczi` but I see he no longer works at Elastic). As far as I can see (since `@jimczi` did previously approve, it was me that pushed the merge back for further testing), this PR is pretty much ready for merging.

**Comment by mark-vieira** [comment]
Could someone from @elastic/es-search determine if this pull request is still relevant?

**Comment by romseygeek** [comment]
Hey @thelink2012, thanks for pushing this.  I'm trying to get up to speed on what this is hoping to fix, and I notice that the first of the tests included in the PR, `testTextThatEndsBeforeMaxLen`, actually passes on the current main branch.  Could you explain a bit more what you're trying to do here?

**Comment by romseygeek** [comment]
@elasticmachine generate changelog

**Comment by romseygeek** [comment]
Ah, never mind, I've read the attached issue and see what we're trying to do here.  All looks good, let's get it up to date and merged.

**Comment by romseygeek** [comment]
@elasticmachine update branch

**Comment by romseygeek** [comment]
Can you enable the option "Allow edits and access to secrets by maintainers" for me? Our @elasticmachine bot can automate all sorts of stuff for us, but it needs edit access.

For more information, [see the documentation](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).

**Comment by thelink2012** [comment]
Hi @romseygeek. Thanks for looking at this!! Unfortunately _Allow edits and access to secrets by maintainers_ doesn't work in organization repositories. I have opened this PR again at https://github.com/elastic/elasticsearch/pull/89041 in my personal account such that the option is enabled.

**Pull request closed without merging**
