### PR TITLE
Suggest exact match

### PR DESCRIPTION
**Pull request by BerndGoldschmidt**
Solves #11579.

Picked up from https://github.com/elastic/elasticsearch/pull/15410, rebased and fixed errors

### CODE REVIEW

**Comment by clintongormley** [comment]
@areek could you take a look please?

**Comment by karmi** [comment]
Hi @BerndGoldschmidt, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/elasticsearch/pull/22902.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by BerndGoldschmidt** [comment]
Hi @karmi, if you are referring to the commits by @ricardocerq, that's not me. Because we really could use this feature, I forked his branch, cleaned it up, fixed some bugs and created a new pull request.
Do you need his signature too?

**Comment by clintongormley** [comment]
@BerndGoldschmidt I think we're good on the CLA - @ricardocerq also signed

**Comment by sandyberndt** [comment]
+1

**Comment by BerndGoldschmidt** [comment]
Any progress on this? Is there anything else I can do?

**Comment by jimczi** [comment]
@BerndGoldschmidt sorry for the delay.
I think we can make the `exact` match compete with the other suggestions rather than always returning it with a score of 1. `exact` does not mean anything in the context of a `did_you_mean`, you may have this exact phrase in a singleton document that is mispelled in the first place.
I think the solution proposed in:
https://github.com/elastic/elasticsearch/issues/24655#issuecomment-301827031 
 is a good compromise. @s1monw any plan to pursue this path ? Maybe @BerndGoldschmidt can help ?

**Comment by salper** [comment]
Maybe I'm missing something, but what is the difference between `exactMatch` and `suggest_mode: always` (which does not seem to work as documented) ?

**Comment by jimczi** [comment]
`suggest_mode: always` just means that all terms are considered when searching for suggestions even if the candidates have a frequency lower than the query term. The documentation is correct, the `exactMatch` option as it is in this PR is different. The proposed approach is to always return the query terms that appear at least once in the index and to set their score to 1. I gave some reasons here https://github.com/elastic/elasticsearch/pull/22902#issuecomment-308100830 as of why `exactMatch` is a fuzzy concept when doing suggestions.

**Comment by jimczi** [comment]
No feedback since July, I am closing this pr. We can revisit with https://github.com/elastic/elasticsearch/pull/22902#issuecomment-308100830 if anybody is interested.

**Pull request closed without merging**
