### PR TITLE
Bump master (3.0-snapshot) to java 8

### PR DESCRIPTION
**Pull request by rmuir**

### CODE REVIEW

**Comment by dakrone** [comment]
Wooo! LGTM

**Comment by rjernst** [comment]
Awesome, LGTM too

**Comment by jasontedor** [comment]
Looks beautiful to me.

**Comment by rmuir** [comment]
I added some commits. full mvn verify passes

**Comment by rjernst** [comment]
Still LGTM

**Comment by jasontedor** [comment]
Relates #10799, #13224, #13315

**Comment by jprante** [comment]
Just a note: `mvn javadoc:javadoc` fails, because Java 8 javadoc performs a strict doclint check. See also http://openjdk.java.net/jeps/172

**Comment by dadoonet** [comment]
Thanks @jprante! I opened an issue #13336

**Pull request closed without merging**
