### PR TITLE
Configurable output format for date processor

### LINKED ISSUE #42523: Add option to output nanoseconds in date ingest processor
Since version 7.0 Elasticsearch mappings can support nanosecond precision timestamps via the `date_nanos` type.  But the date ingest processor only outputs millisecond precision, so any nanosecond precision timestamp that is extracted via the date ingest processor is truncated to millisecond precision.

The reason why this happens is that the output format of the date ingest processor is hardcoded to `yyyy-MM-dd'T'HH:mm:ss.SSSXXX`.

Switching the date ingest processor to always output nanosecond precision timestamps might be a step too far - date fields would become more verbose, use more storage and might potentially cause backwards compatibility problems.

However, it would be nice if the ingest date processor had an option to output nanosecond precision timestamps if the user specifically asked for that.

### PR DESCRIPTION
**Pull request by danhermann**
Adds an optional `output_format` setting to the date processor that controls the formatting of the date. Supports the same formats as the `formats` option and can be used to output times including microsecond or nanosecond components.

Resolves #42523.

### CODE REVIEW

**Review by dakrone — APPROVED** [review]
LGTM

**Comment by danhermann** [comment]
Thanks @dakrone!

**Comment by danhermann** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample-unix

**Comment by droberts195** [comment]
@danhermann this is still backport pending.  Would it be possible for you to backport it to 7.x soon?  I have made a change in the file structure finder that uses this and would like that to go into 7.10.

**Comment by danhermann** [comment]
> @danhermann this is still backport pending. Would it be possible for you to backport it to 7.x soon? I have made a change in the file structure finder that uses this and would like that to go into 7.10.

Yes, I'll get that backported today.

**Pull request merged**
