### PR TITLE
Adding elixir bulk processor to community libraries

### PR DESCRIPTION
**Pull request by sashman**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by philkra** [comment]
pinging @elastic/es-clients

**Comment by jrodewig** [comment]
@elasticmachine test this please

**Comment by jrodewig** [comment]
@elasticmachine update branch

**Comment by jrodewig** [comment]
@elasticmachine test this please

**Review by jrodewig — APPROVED** [review]
👍 Thanks @sashman!

**Comment by jrodewig** [comment]
### Backport commits
master: 68a37f4 
7.x: dd419f0ad09
7.6: d9dd323e819c462eb0bbe719efaf2f056328deaf
7.5: cd6a8d7884541ba89253d750f599017f8206695a

**Pull request merged**
