### PR TITLE
Java high-level REST client : minor fixes

### PR DESCRIPTION
**Pull request by olcbean**
Corrected method name and a parameter name

### CODE REVIEW

**Comment by dnhatn** [comment]
@elasticmachine please test this

**Review by dnhatn — APPROVED** [review]
LGTM.

**Comment by olcbean** [comment]
hey @karmi, for the last month or so, it seems like all community contributions are checked twice ( as can be seen above ). I know this is a 'minor, minor non-issue' but is kind of annoying ;) Or maybe it is on purpose?
( I hope you don't mind me contacting you directly )

**Comment by karmi** [comment]
Hi @olcbean, it's perfectly fine, thanks for the ping! 

By "checked twice" you mean the elasticmachine comments, right? I bet it's something in the depthts of the CI system, @leathekd, do you know why this might be happening?

**Review by javanna — APPROVED** [review]
thanks @olcbean

**Pull request merged**
