### PR TITLE
ESQL: Update moved `heap-attack` QA suite's build group

### PR DESCRIPTION
**Pull request by bpintea**
This updates ESQL's `heap-attack` QA suite's build group.

Related: #104133, #104107.

### CODE REVIEW

**Comment by bpintea** [comment]
@elasticsearchmachine run elasticsearch-ci/part-4

**Comment by bpintea** [comment]
@elasticsearchmachine run elasticsearch-ci/docs

**Review by dnhatn — APPROVED** [review]
LGTM.

**Comment by bpintea** [comment]
Thanks, Nhat!

**Pull request merged**
