### PR TITLE
Re-enable concurrent search on script field type tests

### PR DESCRIPTION
**Pull request by romseygeek**
This commit reverts #90712, which disabled concurrency on runtime 
field scripts.  Since #95082 these scripts should be thread-safe, and so
we can use the standard test searcher methods which may randomly
add multi-threaded search.

### CODE REVIEW

**Review by cbuescher — APPROVED** [review]
Yes, thanks. Briefly looking at https://github.com/elastic/elasticsearch/pull/95082 these tests look okay to be enabled again now.

**Review by javanna — APPROVED** [review]

**Comment by romseygeek** [comment]
@elasticmachine run elasticsearch-ci/part-1
@elasticmachine run elasticsearch-ci/bwc

**Comment by romseygeek** [comment]
@elasticmachine update branch

**Comment by romseygeek** [comment]
@elasticmachine run elasticsearch-ci/packaging-tests-windows-sample

**Pull request merged**
