### PR TITLE
[Inference API] Propagate infer trace context to EIS

### PR DESCRIPTION
**Pull request by timgrein**
This PR propagates the infer request trace context to EIS enabling end-to-end tracing. This change only applies to the EIS integration only without changing or adding any additional tracing behavior to the inference API overall.

### CODE REVIEW

**Review by prwhelan — APPROVED** [review]

**Comment by timgrein** [comment]
@elasticsearchmachine update branch

**Comment by timgrein** [comment]
@elasticmachine update branch

**Comment by timgrein** [comment]
@elasticmachine update branch

**Comment by jonathan-buttner** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.x|[](https://github.com/elastic/elasticsearch/pull/119894)|
|✅|8.17|[](https://github.com/elastic/elasticsearch/pull/119895)|
|✅|8.16|[](https://github.com/elastic/elasticsearch/pull/119896)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
