### PR TITLE
Update jackson to 2.14.1

### LINKED ISSUE #92341: Upgrade to jackson 2.14.1
### Description

Spotted by @joegallo, a minor patch release for jackson 2.14 fixes a heap consumption issue https://github.com/FasterXML/jackson-databind/issues/3665. We don't use databind a lot, but it's a dependency to few plugins and test code.

CC @chris

### PR DESCRIPTION
**Pull request by pgomulka**
Closes https://github.com/elastic/elasticsearch/issues/92341

### CODE REVIEW

**Review by stu-elastic — APPROVED** [review]
lgtm

**Review by grcevski — APPROVED** [review]
LGTM!

**Comment by grcevski** [comment]
I updated the comment, since we already had an issue opened for this upgrade. Thanks!

**Review by ChrisHegarty — COMMENTED** [review]
LGTM

**Pull request merged**
