### PR TITLE
Fix args length == 1 case handling in ESLoggerUsageChecker

### PR DESCRIPTION
**Pull request by sabi0**
There was an operator precedence mistake in:
`(lengthWithoutMarker == 1 || lengthWithoutMarker == 2) && lengthWithoutMarker == 2 ? ...`

Logical AND `&&` has higher precedence than ternary operator `?:`. And the above expression is equivalent to `lengthWithoutMarker == 2 ? ...`
I.e. the `lengthWithoutMarker == 1` case was mistakenly sent to the `throw new IllegalStateException()` 'else' block.

### CODE REVIEW

**Comment by williamrandolph** [comment]
I see where it looks like there's a mistake in the order of operations, but I don't think that the `lengthWithoutMarker == 1` case throws the `IllegalStateException`. Rather, it looks to me like the _only_ case that throws an IllegalStateException is when `lengthWithoutMarker == 2` and `argumentTypes[markerOffset + 1].equals(THROWABLE_CLASS) == false`.

I can't think of a way to write a failing test for this in `ESLoggerUsageTests`, because everything that compiles fits one of the cases we're expecting. The intended logic seems like it's supposed to guard a case where there's an addition to the Logger API and but we haven't yet updated our tool to check its usage.

Since the change looks good to me, and I can't think of a way to add tests for it, I'm going to enable tests on this PR and re-review it if they pass. If everything looks good at that point, we should be able to merge this.

Thanks for your contribution!

**Comment by williamrandolph** [comment]
@elasticsearchmachine test this please

**Comment by williamrandolph** [comment]
@elasticsearchmachine update branch

**Comment by williamrandolph** [comment]
@elasticsearchmachine ok to test

**Comment by williamrandolph** [comment]
buildkite ok to test

**Comment by williamrandolph** [comment]
@elasticmachine update branch

**Comment by williamrandolph** [comment]
@elasticmachine ok to test

**Comment by williamrandolph** [comment]
buildkite test this please

**Comment by williamrandolph** [comment]
@sabi0 I'm not sure why our formatter wants the if/else statements indented the way it does, but could you run `./gradlew test:logger-usage:spotlessApply` and commit what the spotless formatter produces?

**Review by williamrandolph — CHANGES_REQUESTED** [review]
Code change is good, but the formatting does not agree with our automatic formatter.

**Comment by sabi0** [comment]
I am sorry, I was absolutely sure the weird 'else if' indentation was a glitch of some kind.
For instance, a similar multi-branch 'else if' block is indented "the usual way" here:
https://github.com/elastic/elasticsearch/blob/main/libs/geo/src/main/java/org/elasticsearch/geometry/simplify/GeometrySimplifier.java#L324

I will reset the formatting.

**Comment by williamrandolph** [comment]
I think we should keep this PR focused on the particular change, since it looks like it will be ready to merge as soon as tests pass.

As a follow-up on the indentation issue, I think there would be some discussion about the tradeoff of the intended effect of setting `keep_else_statement_on_same_line` to false
```
if (isChildOf(symbolicLink, file))
    return true;
```
versus the current effect of:
```
if (isChildOf(symbolicLink, file)) return true;
```

If you issue a PR for the format change, I will happily put it on the agenda for team discussion. I can't promise we'd merge it, but the inconsistent if/else formatting really bugs me and I'd argue for fixing it.

**Review by williamrandolph — APPROVED** [review]
This code change looks good to me, and I'll merge it once tests pass.

**Comment by sabi0** [comment]
> If you issue a PR for the format change, I will happily put it on the agenda for team discussion.

See #103073

**Pull request merged**
