### PR TITLE
Hot inlined methods in your area

### PR DESCRIPTION
**Pull request by jasontedor**
An important optimization that a compiler can make is to inline
methods. The JVM JIT compiler makes decisions about inlining methods
based on method size and how hot the method is. For example, small
methods (less than 35 bytes by default, but tunable via
`-XX:MaxInlineSize=N` ) are automatically inlined. And hot methods are
inlined only if they are not large (less than 325 bytes by default, but
tunable via `-XX:MaxFreqInlineSize=N`). Hot methods that the JVM could
not inline in Elasticsearch can be found by enabling the JVM to trace
method inlining via `-XX:+UnlockDiagnoticVMOptions -XX:+PrintInlining`
and then looking for "hot method too big" for any methods in a
sub-package of `org.elasticsearch`. It is generally recommend to not
tune the inlining flags. Instead, we can enable the JVM to inline these
hot methods by breaking these methods down into smaller methods.

The methods that are hot but could not be inlined while benchmarking
Elasticsearch are:

``` text
org.elasticsearch.action.bulk.TransportShardBulkAction::shardOperationOnPrimary (1918 bytes)   hot method too big
org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase::doRun (344 bytes)   hot method too big
org.elasticsearch.action.support.replication.TransportReplicationAction$ReplicationPhase::<init> (440 bytes)   hot method too big
org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase::doRun (739 bytes)   hot method too big
org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$DateMathExpressionResolver::resolveExpression (740 bytes)   hot method too big
org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$WildcardExpressionResolver::resolve (1110 bytes)   hot method too big
org.elasticsearch.cluster.metadata.MetaData::resolveIndexRouting (351 bytes)   hot method too big
org.elasticsearch.common.Base64::decode (389 bytes)   hot method too big
org.elasticsearch.common.Base64::decode4to3 (350 bytes)   hot method too big
org.elasticsearch.common.Base64::encodeBytesToBytes (456 bytes)   hot method too big
org.elasticsearch.common.breaker.ChildMemoryCircuitBreaker::addEstimateBytesAndMaybeBreak (372 bytes)   hot method too big
org.elasticsearch.common.xcontent.XContentBuilder::writeValue (1203 bytes)   hot method too big
org.elasticsearch.http.netty.NettyHttpChannel::getStatus (388 bytes)   hot method too big
org.elasticsearch.http.netty.NettyHttpChannel::sendResponse (562 bytes)   hot method too big
org.elasticsearch.index.fielddata.ordinals.OrdinalsBuilder$OrdinalsStore::addOrdinal (348 bytes)   hot method too big
org.elasticsearch.index.mapper.DocumentParser::parseObject (687 bytes)   hot method too big
org.elasticsearch.rest.support.RestUtils::decodeComponent (387 bytes)   hot method too big
org.elasticsearch.search.aggregations.AggregationPhase::execute (558 bytes)   hot method too big
org.elasticsearch.search.aggregations.bucket.terms.GlobalOrdinalsStringTermsAggregator::buildAggregation (540 bytes)   hot method too big
org.elasticsearch.search.aggregations.bucket.terms.InternalTerms::doReduce (687 bytes)   hot method too big
org.elasticsearch.search.controller.SearchPhaseController::sortDocs (673 bytes)   hot method too big
org.elasticsearch.search.fetch.FetchPhase::execute (645 bytes)   hot method too big
org.elasticsearch.search.internal.InternalSearchHit::toXContent (890 bytes)   hot method too big
org.elasticsearch.search.query.QueryPhase::execute (1174 bytes)   hot method too big
```

This commit refactors most of the methods that are hot but the JVM could
not inline because they are too large so that they JVM can now inline
them. Simple micro-benchmarking on a few (but not all) of these methods
showed modest performance gains on the order of 5%. This refactoring has
the additional advantage that by breaking these large methods into
smaller methods, they are simpler to understand and maintain.

The methods not addressed by this pull request are:

```
org.elasticsearch.cluster.metadata.IndexNameExpressionResolver$DateMathExpressionResolver::resolveExpression (740 bytes)   hot method too big
org.elasticsearch.search.aggregations.AggregationPhase::execute (558 bytes)   hot method too big
org.elasticsearch.search.aggregations.bucket.terms.GlobalOrdinalsStringTermsAggregator::buildAggregation (540 bytes)   hot method too big
org.elasticsearch.search.aggregations.bucket.terms.InternalTerms::doReduce (687 bytes)   hot method too big
org.elasticsearch.search.controller.SearchPhaseController::sortDocs (673 bytes)   hot method too big
org.elasticsearch.search.fetch.FetchPhase::execute (645 bytes)   hot method too big
org.elasticsearch.search.internal.InternalSearchHit::toXContent (890 bytes)   hot method too big
org.elasticsearch.search.query.QueryPhase::execute (1174 bytes)   hot method too big
```

All other methods are addressed.

### CODE REVIEW

**Comment by bleskes** [comment]
@jasontedor out of curiosity -  do you have any numbers about the performance delta between current code and your PR?

**Comment by jasontedor** [comment]
> do you have any numbers about the performance delta between current code and your PR?

@bleskes I do, and there are issues which I've discussed with @danielmitterdorfer. The issue is that there is variance in the benchmark results due to a large variance in the number of segments; this hides the impact of this change (which is expected to be small but positive).

**Comment by jasontedor** [comment]
@danielmitterdorfer Is there any chance of getting this reviewed before the code base starts moving rapidly again?

**Comment by danielmitterdorfer** [comment]
I left a few minor comments here and there. I also ran the benchmarks multiple times but the changes hide in the run-to-run variance. Nevertheless, I think it is great to have shorter methods and it improves maintainability. Btw, I've also liked very much how you've split your commits for this PR. 

Apart from the minor comments, LGTM.

**Comment by jasontedor** [comment]
Thanks for the review @danielmitterdorfer; I integrated your feedback into the [version that was pushed to master](https://github.com/elastic/elasticsearch/compare/a9eb668497dc...bd5c7f088974).

**Pull request closed without merging**
