### PR TITLE
Minor fix in getting-started.asciidoc (delete POST verb for search API with body)

### PR DESCRIPTION
**Pull request by nevries**
Example code uses POST for the search query with body instead of GET.

### CODE REVIEW

**Review by cbuescher — CHANGES_REQUESTED** [review]
@nevries thanks for opening this. We had a similar pull request lately (#28249) that was closed due to lack of response. @DaveCTurner pointed out that we use GET throughout the rest of this section too, so that should probably stay this way (at least in the getting-started) but the POST Verb on the following line should change. Would you be okay with making that change instead? If so, can you post an update?

**Comment by nevries** [comment]
Hi @cbuescher ,
thanks for feedback. I edited the sentence after the first example instead and rebased the pull request to master...

**Review by cbuescher — APPROVED** [review]
@nevries thanks for the change, LGTM

**Comment by cbuescher** [comment]
@elasticmachine test this please

**Pull request merged**
