### PR TITLE
Add _meta information to built-in ILM policies

### PR DESCRIPTION
**Pull request by dakrone**
We already ship templates that include the `_meta` map for things like component and composable
index templates, and we use the `"managed": true` indicator for many of our built-in items within
Elasticsearch.

This commit adds a description and managed flag to each of the ILM policies we ship by default.

### CODE REVIEW

**Comment by dakrone** [comment]
@elasticmachine update branch

**Review by andreidan — APPROVED** [review]
LGTM, thanks for working on this Lee

**Comment by cjcenizal** [comment]
Thanks Lee, that helps me understand. Do you think we should just hide managed policies entirely in the UI? Is there anything a user could gain from seeing them -- would they learn anything useful about policy configuration? Would seeing them answer any questions they might have about the behavior of the cluster?

**Comment by dakrone** [comment]
> Do you think we should just hide managed policies entirely in the UI?

Not yet, we're not at a point where they can be ignored entirely by the user yet.

> Is there anything a user could gain from seeing them -- would they learn anything useful about policy configuration?

Yes, especially things like the logs, metrics, and synthetics templates that we install out of the box. Those are things that a user should be aware of if they don't use Fleet, for instance.

> Would seeing them answer any questions they might have about the behavior of the cluster?

Yes, especially related to the fleet stuff (like indexing into `logs-*-*` with adding an integration first)

**Comment by cjcenizal** [comment]
Great, thanks Lee. I think these are all strong arguments for surfacing the `description` in the UI, and refining that copy.

**Pull request merged**
