### PR TITLE
Reject legacy `index` values for `text` and `keyword`.

### LINKED ISSUE #21134: Mapping with Index not_analyzed is not working
**Elasticsearch version**: 5.0.0-rc1

**Plugins installed**: [none]

**JVM version**:

```
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
```

**OS version**: Debian 8

**Description of the problem including expected versus actual behavior**:

Creating an example index with its mapping:

```
PUT twitter 
{
  "mappings": {
    "tweet": {
      "properties": {
        "message": {
          "type": "text",
          "index": "not_analyzed"
        }
      }
    }
  }
}
```

Everything went fine:

```
{
  "acknowledged": true
}
```

But now, let's get the actual mapping with `GET twitter/_mapping/tweet`:

```
{
  "twitter": {
    "mappings": {
      "tweet": {
        "properties": {
          "message": {
            "type": "text"
          }
        }
      }
    }
  }
}
```

The `message` field is still analyzed. Why?

### PR DESCRIPTION
**Pull request by jpountz**
Closes #21134

### CODE REVIEW

**Review by nik9000 — CHANGES_REQUESTED** [review]
I think it makes more sense to change `parseIndex` to the new code and put the old version of `parseIndex` into `StringFieldMapper`.

**Comment by jpountz** [comment]
The reason it works this way is that we want `index: not_analyzed` to keep working for numbers, dates, ip addresses, etc. to ease upgrade to 5.0.

**Review by nik9000 — APPROVED** [review]
I'm ok with it then. Can you add a comment to the `index: not_analyzed` part so we know we're keeping it around for 2.x backwards compatibility?

**Comment by johtani** [comment]
How do we support [dynamic template situation](https://github.com/elastic/elasticsearch/blob/ffee9e8833415d4cbdd02280b2b5ed8da63f3680/core/src/test/java/org/elasticsearch/index/mapper/StringMappingUpgradeTests.java#L402-L402)?
Maybe related [DynamicTemplate](https://github.com/elastic/elasticsearch/blob/44ac5d057a8ceb6940c26275d9963bccb9f5065a/core/src/main/java/org/elasticsearch/index/mapper/DynamicTemplate.java#L282-L282)

**Comment by jpountz** [comment]
You are right @johtani, this PR also breaks the desired behaviour that we want for templates (tests actually fail). I started looking what it would mean to be lenient in templates about what we accept as `index` values but not in explicit mappings, but this requires to add even more hacks than we have today in order to handle the upgrade, so I'm leaning towards only fixing this behaviour in 6.0 when we do not have to handle the automatic upgrade of strings anymore.

**Pull request closed without merging**
