### PR TITLE
Do not ignore request analysis/similarity on resize

### PR DESCRIPTION
**Pull request by jasontedor**
Today when a resize operation is performed, we copy the analysis, similarity, and sort settings from the source index. It is possible for the resize request to include additional index settings including analysis, similarity, and sort settings. We reject sort settings when validating the request. However, we silently ignore analysis and similarity settings on the request that are already set on the source index. Since it is possible to change the analysis and similarity settings on an existing index, this should be considered a bug and the sort of leniency that we abhor. This commit addresses this bug by allowing the request analysis/similarity settings to override the existing analysis/similarity settings on the target.

### CODE REVIEW

**Comment by jasontedor** [comment]
test this please

**Comment by jasontedor** [comment]
run sample packaging tests

**Comment by jasontedor** [comment]
run sample packaging tests

**Review by colings86 — APPROVED** [review]
LGTM

**Comment by jasontedor** [comment]
Thanks @colings86.

**Pull request merged**
