### PR TITLE
Java client: Avoid throwing a TimeoutException after the operation wa…

### LINKED ISSUE #24069: TimeoutExceptions on REST Client - with fix proposal
**Elasticsearch version**:

5.3

**Plugins installed**: N/A

**JVM version**: All

**OS version**: Any

While running integration tests for the Hibernate Search project we noticed some requests failing for TimeoutException on rather slow machines. I initially thought it was a "just a timeout", but investigating I actually identified a problem caused by the default configuration applied by the Elasticsearch REST client.

The Apache Async HTTP client being used has a pool for Non-blocking HTTP connections, implemented by `org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager`. This pool has a connection property which can be set via `org.apache.http.client.config.RequestConfig.Builder.connectionRequestTimeout`, but the name seems to have been confusing (it certainly confused me).

This configuration property validates if the Request is stale; for some reason it's also applied to instances of `org.apache.http.nio.pool.LeaseRequest` , and the next lease instance is validated from a queue of requests even after the execution of a successul client Request. When this second request is expired, the whole execution is marked with a TimeoutException.

To clarify: the client code sends a request A to the Elasticsearch server. A is processed fine, and the response is handled fine as well. *after* this, the state of A is marked as "timed out" because the next request in the PoolingNHttpClientConnectionManager is an expired lease instance.
I suspect this is a bug in the Apache Async client code as the error handling is essentially returning an exception which seems out of place.

The solution for us was extremely simple: set this property to zero, to disable this lease mechanism.

This mechanism is disabled by default in the Apache Async Http library, but the Elasticsearch client overrides this with its own default:
 org.elasticsearch.client.RestClientBuilder.DEFAULT_CONNECTION_REQUEST_TIMEOUT_MILLIS

I'd recommend to set this default to zero as well. The name of the property is probably misleading? It's not really applied to the request processing on the Elasticsearch server, it's applied to the "request to the connection pool".

Thanks!

Relates to:
 - https://hibernate.atlassian.net/browse/HSEARCH-2681

I think it's the same problem mentioned here:
 - https://discuss.elastic.co/t/elasticsearch-in-docker-and-the-restclient-often-got-java-util-concurrent-timeoutexception/68118

### PR DESCRIPTION
**Pull request by Sanne**
…s successful

Closes #24069

Please consider backporting, I'm seeing quite some users affected by this.

### CODE REVIEW

**Comment by mayya-sharipova** [comment]
@elasticmachine ok to test

**Comment by Sanne** [comment]
Hi @javanna looks like I passed the paperwork barriers ^ ;) In your hands now?

**Comment by javanna** [comment]
yea @Sanne I'll try to figure out how to test this in the coming days.

**Comment by Sanne** [comment]
yes that's the hard part. I actually feel bad about sending a PR without tests :)

Personally I would use Byteman for such cases, it helps re-create a scenario with parallel threads as you can block them on specific points and control the flow (Byteman was originally created to address the testing needs of our JTA library Narayana, later we started using it on other projects too).
I didn't feel like introducing a Byteman based test as you'd need the new dependency and an agent running: might be a bit intrusive on the build, especially as I wouldn't know how you want things organized.

**Comment by nik9000** [comment]
I was working to reproduce another issue but I think I stumbled into a fairly good test for this one. See this [gist](https://gist.github.com/nik9000/fc4b44a6396c20232b07568df5a7964e).

**Comment by nik9000** [comment]
I'd certainly prefer to have a more targeted test, but without one I think this is fairly useful.

**Comment by javanna** [comment]
hi @Sanne I think it was a mistake on my end to set this timeout, I also misunderstood what it was meant for. I would then prefer to leave the apache http async default if it's already ok, but it seems like its default value is `-1` (system default) and not `0`. Could you comment on this?

**Comment by javanna** [comment]
One more thing, I am ok with the test that @nik9000 proposed above, maybe you can update the PR so we can finally get it in (sorry it took ages, I feel bad about that).

**Comment by nik9000** [comment]
@Sanne, would you like to pick up this PR and add a test, maybe similar to the one I proposed? Would you be OK if I picked it up? I think it is worth fixing this issue and you found the issue so I figure it is only right you get your name in the git history.

**Comment by ricardomthomas** [comment]
In what ES version will this change be targeted? I see the PR is still open.

**Comment by Sanne** [comment]
hi @nik9000 ! I appreciate the kind offer but feel free to take ownership of it.

@javanna : I no longer have the environment which I used to reliably reproduce this so I wouldn't be able to test that. I'm sure my patch resolved the problem, but maybe `-1` would work as well.

**Comment by javanna** [comment]
No worries, we have taken ownership of this. I started working on some changes around timeouts including this one and adding tests, but I need first #29211 to go in otherwise resolving merge conflicts becomes a nightmare.

**Comment by javanna** [comment]
thanks once again @Sanne  for opening this and for the detailed analysis. Sorry that it took so long to integrate the suggested changes. I finally opened a PR with a slightly different change and with tests that fail without the fix. I am closing this PR as it's superseded by #30384 .

**Comment by Sanne** [comment]
awesome, thanks! Looking forward to see this benefit everyone else.

**Comment by rafaelbattesti** [comment]
Hi @javanna . What would you recommend as I have a requirement for 5.6.9? I tried `setConnectionRequestTimeout(0)` and `.setConnectionRequestTimeout(-1)` to no avail.
I am running my application in a docker container on a k8 cluster. Requests are successful when sent from my local environment, but I get the timeout from `org.apache.http.nio.pool.RouteSpecificPool.timeout(RouteSpecificPool.java:168)` when running on the cluster.
Thanks!

**Comment by javanna** [comment]
hi @rafaelbattesti I'd assume it's a different problem if explicitly setting the connection request timeout doesn't help. Could you share your initialization code for the client, and the full stacktrace of the exception please?

**Comment by rafaelbattesti** [comment]
@javanna I found this has to do with the network setup.

**Comment by javanna** [comment]
@rafaelbattesti glad to know you found the cause, would you mind sharing what caused the problem?

**Comment by rafaelbattesti** [comment]
@javanna I wouldn't mind if I had reached a precise diagnostic. I can tell it's a network setup because a basic `curl` from my container timed out, while it gets me the expected response from my local machine. I am contacting the K8 admin team for troubleshooting. Thanks again!

**Pull request closed without merging**
