### PR TITLE
Ignore template warnings in IndexingIT

### LINKED ISSUE #59935: Test failure in IndexingIT::testIndexing
**Build scan**: https://gradle-enterprise.elastic.co/s/4jme3x7byxxve

**Repro line**: `./gradlew ':qa:rolling-upgrade:v7.8.1#oldClusterTest' --tests "org.elasticsearch.upgrades.IndexingIT.testIndexing" -Dtests.seed=12DF798394B5D8E2 -Dtests.security.manager=true -Dtests.locale=ms-MY -Dtests.timezone=SystemV/MST7 -Druntime.java=8`

**Reproduces locally?**: No

**Applicable branches**: `7.9`

**Failure excerpt**:

```
org.elasticsearch.upgrades.IndexingIT > testIndexing FAILED |  -- | --
  | org.elasticsearch.client.WarningFailureException: method [PUT], host [http://[::1]:33059], URI [/test_index], status line [HTTP/1.1 200 OK] |  
  | Warnings: [index [test_index] matches multiple legacy templates [global, prevent-bwc-deprecation-template], composable templates will only match a single template] |  
  | {"acknowledged":true,"shards_acknowledged":true,"index":"test_index"} |  
  | at __randomizedtesting.SeedInfo.seed([12DF798394B5D8E2:F605368AB2C09B69]:0) |  
  | at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:298) |  
  | at org.elasticsearch.client.RestClient.performRequest(RestClient.java:272) |  
  | at org.elasticsearch.client.RestClient.performRequest(RestClient.java:246) |  
  | at org.elasticsearch.upgrades.IndexingIT.testIndexing(IndexingIT.java:99)
```

### PR DESCRIPTION
**Pull request by danhermann**
Fixes #59935 

Depends on #59960

### CODE REVIEW

**Review by dakrone — APPROVED** [review]
LGTM

**Comment by danhermann** [comment]
@elasticmachine update branch

**Comment by danhermann** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample-unix

**Comment by danhermann** [comment]
@elasticmachine run elasticsearch-ci/2

**Pull request merged**
