### PR TITLE
Fix split package org.elasticsearch.client 

### LINKED ISSUE #81984: Fix split package org.elasticsearch.client
REST Clients - split package issue:
1. High Level Rest Client (HLRC) - contains `org.elasticsearch.client`
2. Low Level Rest Client (LLRC) - contains `org.elasticsearch.client`
3. Elasticsearch Java Client (EJC) - contains `co.elastic.clients.XXX`
4. Server - contains `org.elasticsearch.client`
 
1 , 2 and 4 above contain, and have types in, `org.elasticsearch.client` - leading to a split package.

The HLRC is has been replaced by no.3 EJC. There is no planned 8.x artifact of the HLRC, and the only thing holding us back from deleting it from the codebase in master is the use in tests.
 
The LLRC is still active and will continue on. Ultimately the LLRC code base might move to the elastisearch-java repo.
 
LLRC does not have any dependency on server. And in fact is its own thing. Never loaded into the same classloader, etc. It's a separate distribution.
 
HLRC however depends on both server and LLRC. (the HLRC dependence on the server was a large motivation for the EJC)
 
Long story short, we can move things around as we like in 8.x since there won't be HLRC releases anymore with 8.0. But we much avoid doing so in 7.x as it may lead to breaking changes in applications using HLRC. With LLRC some consideration for the package name should be applied to help avoid/document breaking changes - ultimately, we should NOT change the package name.
 
If we need to, we can rename the package in server, from org.elasticserarch.client to something more appropriate and relevant to its purpose “internal client”.

see #78166

### PR DESCRIPTION
**Pull request by ChrisHegarty**
Fixes split packages between server and the LLRC (and HLRC), by renaming
the server package to a more appropriate name that represents the fact
that is in an internal client. That is, rename server's
`org.elasticsearch.client` to `org.elasticsearch.client.internal`.

Offline comments have indicated a preference to retain the disassociation
between the _internal client_ and _transport_. While many of the actions
of the internal client end up sending transport requests, not all do. For this
reason `org.elasticsearch.client.internal` was chosen. 

The package is a perfect split, so the changes largely amount to
import and package statements.

closed #81984

### CODE REVIEW

**Comment by ChrisHegarty** [comment]
Note to reviewers. Much of the changes are related to the shimmer in package and import statements. To more easily see changes not related to the aforementioned shimmer, one can run a cross branch diff, see below.

Highlights:
- fix-up javadoc link and at see comments
- reflow a few long lines to fit into < 140

```
$ git diff -w master..split_package_client | egrep -v '^(\s|diff|rename|similarity|index\s[a-z0-9]{11}\.\.[a-z0-9]{11}|@@|---|\+\+\+)' | egrep -v '^[\+|-]{1}[import|package]{1}'
-     * part of the reindex. For example, a {@link org.elasticsearch.client.FilterClient} can be provided to transform bulk index requests
-     * before they are fully performed.
+     * part of the reindex. For example, a {@link org.elasticsearch.internal.client.FilterClient} can be provided to transform bulk index
+     * requests before they are fully performed.
-            org.elasticsearch.client.transport.NoNodeAvailableException.class,
-            org.elasticsearch.client.transport.NoNodeAvailableException::new,
+            org.elasticsearch.internal.client.transport.NoNodeAvailableException.class,
+            org.elasticsearch.internal.client.transport.NoNodeAvailableException::new,
- * A request to create an index. Best created with {@link org.elasticsearch.client.Requests#createIndexRequest(String)}.
+ * A request to create an index. Best created with {@link org.elasticsearch.internal.client.Requests#createIndexRequest(String)}.
- * @see org.elasticsearch.client.IndicesAdminClient#create(CreateIndexRequest)
- * @see org.elasticsearch.client.Requests#createIndexRequest(String)
+ * @see org.elasticsearch.internal.client.IndicesAdminClient#create(CreateIndexRequest)
+ * @see org.elasticsearch.internal.client.Requests#createIndexRequest(String)
- * A request to delete an index. Best created with {@link org.elasticsearch.client.Requests#deleteIndexRequest(String)}.
+ * A request to delete an index. Best created with {@link org.elasticsearch.internal.client.Requests#deleteIndexRequest(String)}.
- * Best created with {@link org.elasticsearch.client.Requests#flushRequest(String...)}.
+ * Best created with {@link org.elasticsearch.internal.client.Requests#flushRequest(String...)}.
- * @see org.elasticsearch.client.Requests#flushRequest(String...)
- * @see org.elasticsearch.client.IndicesAdminClient#flush(FlushRequest)
+ * @see org.elasticsearch.internal.client.Requests#flushRequest(String...)
+ * @see org.elasticsearch.internal.client.IndicesAdminClient#flush(FlushRequest)
- * @see org.elasticsearch.client.Requests#forceMergeRequest(String...)
- * @see org.elasticsearch.client.IndicesAdminClient#forceMerge(ForceMergeRequest)
+ * @see org.elasticsearch.internal.client.Requests#forceMergeRequest(String...)
+ * @see org.elasticsearch.internal.client.IndicesAdminClient#forceMerge(ForceMergeRequest)
- * {@link org.elasticsearch.client.Requests#putMappingRequest(String...)}.
+ * {@link org.elasticsearch.internal.client.Requests#putMappingRequest(String...)}.
- * @see org.elasticsearch.client.Requests#putMappingRequest(String...)
- * @see org.elasticsearch.client.IndicesAdminClient#putMapping(PutMappingRequest)
+ * @see org.elasticsearch.internal.client.Requests#putMappingRequest(String...)
+ * @see org.elasticsearch.internal.client.IndicesAdminClient#putMapping(PutMappingRequest)
- * @see org.elasticsearch.client.Requests#refreshRequest(String...)
- * @see org.elasticsearch.client.IndicesAdminClient#refresh(RefreshRequest)
+ * @see org.elasticsearch.internal.client.Requests#refreshRequest(String...)
+ * @see org.elasticsearch.internal.client.IndicesAdminClient#refresh(RefreshRequest)
-     * with client::bulk as the first argument, or {@link #builder(org.elasticsearch.client.Client,
+     * with client::bulk as the first argument, or {@link #builder(org.elasticsearch.internal.client.Client,
- * @see org.elasticsearch.client.Client#bulk(BulkRequest)
+ * @see org.elasticsearch.internal.client.Client#bulk(BulkRequest)
- * {@link org.elasticsearch.client.Requests#deleteRequest(String)}.
+ * {@link org.elasticsearch.internal.client.Requests#deleteRequest(String)}.
- * @see org.elasticsearch.client.Client#delete(DeleteRequest)
- * @see org.elasticsearch.client.Requests#deleteRequest(String)
+ * @see org.elasticsearch.internal.client.Client#delete(DeleteRequest)
+ * @see org.elasticsearch.internal.client.Requests#deleteRequest(String)
- * @see org.elasticsearch.client.Client#delete(DeleteRequest)
+ * @see org.elasticsearch.internal.client.Client#delete(DeleteRequest)
- * {@link org.elasticsearch.client.Requests#getRequest(String)}.
+ * {@link org.elasticsearch.internal.client.Requests#getRequest(String)}.
- * @see org.elasticsearch.client.Requests#getRequest(String)
- * @see org.elasticsearch.client.Client#get(GetRequest)
+ * @see org.elasticsearch.internal.client.Requests#getRequest(String)
+ * @see org.elasticsearch.internal.client.Client#get(GetRequest)
- * @see org.elasticsearch.client.Client#get(GetRequest)
+ * @see org.elasticsearch.internal.client.Client#get(GetRequest)
- * created using {@link org.elasticsearch.client.Requests#indexRequest(String)}.
+ * created using {@link org.elasticsearch.internal.client.Requests#indexRequest(String)}.
- * @see org.elasticsearch.client.Requests#indexRequest(String)
- * @see org.elasticsearch.client.Client#index(IndexRequest)
+ * @see org.elasticsearch.internal.client.Requests#indexRequest(String)
+ * @see org.elasticsearch.internal.client.Client#index(IndexRequest)
- * @see org.elasticsearch.client.Client#index(IndexRequest)
+ * @see org.elasticsearch.internal.client.Client#index(IndexRequest)
- * {@link org.elasticsearch.client.Requests#searchRequest(String...)}.
+ * {@link org.elasticsearch.internal.client.Requests#searchRequest(String...)}.
- * @see org.elasticsearch.client.Requests#searchRequest(String...)
- * @see org.elasticsearch.client.Client#search(SearchRequest)
+ * @see org.elasticsearch.internal.client.Requests#searchRequest(String...)
+ * @see org.elasticsearch.internal.client.Client#search(SearchRequest)
- * @see org.elasticsearch.client.Client#admin()
+ * @see org.elasticsearch.internal.client.Client#admin()
-     * @see org.elasticsearch.client.Requests#bulkRequest()
+     * @see org.elasticsearch.internal.client.Requests#bulkRequest()
-     * @see org.elasticsearch.client.Requests#bulkRequest()
+     * @see org.elasticsearch.internal.client.Requests#bulkRequest()
-     * @see org.elasticsearch.client.Requests#nodesInfoRequest(String...)
+     * @see org.elasticsearch.internal.client.Requests#nodesInfoRequest(String...)
-     * @see org.elasticsearch.client.Requests#nodesInfoRequest(String...)
+     * @see org.elasticsearch.internal.client.Requests#nodesInfoRequest(String...)
-     * @see org.elasticsearch.client.Requests#clusterStatsRequest
+     * @see org.elasticsearch.internal.client.Requests#clusterStatsRequest
-     * @see org.elasticsearch.client.Requests#clusterStatsRequest()
+     * @see org.elasticsearch.internal.client.Requests#clusterStatsRequest()
-     * @see org.elasticsearch.client.Requests#nodesStatsRequest(String...)
+     * @see org.elasticsearch.internal.client.Requests#nodesStatsRequest(String...)
-     * @see org.elasticsearch.client.Requests#nodesStatsRequest(String...)
+     * @see org.elasticsearch.internal.client.Requests#nodesStatsRequest(String...)
-     * @see org.elasticsearch.client.Requests#nodesUsageRequest(String...)
+     * @see org.elasticsearch.internal.client.Requests#nodesUsageRequest(String...)
-     * @see org.elasticsearch.client.Requests#nodesUsageRequest(String...)
+     * @see org.elasticsearch.internal.client.Requests#nodesUsageRequest(String...)
-     * @see org.elasticsearch.client.Requests#listTasksRequest()
+     * @see org.elasticsearch.internal.client.Requests#listTasksRequest()
-     * @see org.elasticsearch.client.Requests#listTasksRequest()
+     * @see org.elasticsearch.internal.client.Requests#listTasksRequest()
-     * @see org.elasticsearch.client.Requests#getTaskRequest()
+     * @see org.elasticsearch.internal.client.Requests#getTaskRequest()
-     * @see org.elasticsearch.client.Requests#getTaskRequest()
+     * @see org.elasticsearch.internal.client.Requests#getTaskRequest()
-     * @see org.elasticsearch.client.Requests#cancelTasksRequest()
+     * @see org.elasticsearch.internal.client.Requests#cancelTasksRequest()
-     * @see org.elasticsearch.client.Requests#cancelTasksRequest()
+     * @see org.elasticsearch.internal.client.Requests#cancelTasksRequest()
-     * @see org.elasticsearch.client.Requests#createIndexRequest(String)
+     * @see org.elasticsearch.internal.client.Requests#createIndexRequest(String)
-     * @see org.elasticsearch.client.Requests#createIndexRequest(String)
+     * @see org.elasticsearch.internal.client.Requests#createIndexRequest(String)
-     * @see org.elasticsearch.client.Requests#deleteIndexRequest(String)
+     * @see org.elasticsearch.internal.client.Requests#deleteIndexRequest(String)
-     * @see org.elasticsearch.client.Requests#deleteIndexRequest(String)
+     * @see org.elasticsearch.internal.client.Requests#deleteIndexRequest(String)
-     * @see org.elasticsearch.client.Requests#closeIndexRequest(String)
+     * @see org.elasticsearch.internal.client.Requests#closeIndexRequest(String)
-     * @see org.elasticsearch.client.Requests#closeIndexRequest(String)
+     * @see org.elasticsearch.internal.client.Requests#closeIndexRequest(String)
-     * @see org.elasticsearch.client.Requests#openIndexRequest(String)
+     * @see org.elasticsearch.internal.client.Requests#openIndexRequest(String)
-     * @see org.elasticsearch.client.Requests#openIndexRequest(String)
+     * @see org.elasticsearch.internal.client.Requests#openIndexRequest(String)
-     * @see org.elasticsearch.client.Requests#openIndexRequest(String)
+     * @see org.elasticsearch.internal.client.Requests#openIndexRequest(String)
-     * @see org.elasticsearch.client.Requests#refreshRequest(String...)
+     * @see org.elasticsearch.internal.client.Requests#refreshRequest(String...)
-     * @see org.elasticsearch.client.Requests#refreshRequest(String...)
+     * @see org.elasticsearch.internal.client.Requests#refreshRequest(String...)
-     * @see org.elasticsearch.client.Requests#flushRequest(String...)
+     * @see org.elasticsearch.internal.client.Requests#flushRequest(String...)
-     * @see org.elasticsearch.client.Requests#flushRequest(String...)
+     * @see org.elasticsearch.internal.client.Requests#flushRequest(String...)
-     * @see org.elasticsearch.client.Requests#forceMergeRequest(String...)
+     * @see org.elasticsearch.internal.client.Requests#forceMergeRequest(String...)
-     * @see org.elasticsearch.client.Requests#forceMergeRequest(String...)
+     * @see org.elasticsearch.internal.client.Requests#forceMergeRequest(String...)
-     * @see org.elasticsearch.client.Requests#putMappingRequest(String...)
+     * @see org.elasticsearch.internal.client.Requests#putMappingRequest(String...)
-     * @see org.elasticsearch.client.Requests#putMappingRequest(String...)
+     * @see org.elasticsearch.internal.client.Requests#putMappingRequest(String...)
-     * @see org.elasticsearch.client.Client#index(org.elasticsearch.action.index.IndexRequest)
+     * @see org.elasticsearch.internal.client.Client#index(org.elasticsearch.action.index.IndexRequest)
-     * @see org.elasticsearch.client.Client#delete(org.elasticsearch.action.delete.DeleteRequest)
+     * @see org.elasticsearch.internal.client.Client#delete(org.elasticsearch.action.delete.DeleteRequest)
-     * @see org.elasticsearch.client.Client#get(org.elasticsearch.action.get.GetRequest)
+     * @see org.elasticsearch.internal.client.Client#get(org.elasticsearch.action.get.GetRequest)
-     * @see org.elasticsearch.client.Client#search(org.elasticsearch.action.search.SearchRequest)
+     * @see org.elasticsearch.internal.client.Client#search(org.elasticsearch.action.search.SearchRequest)
-     * @see org.elasticsearch.client.Client#searchScroll(org.elasticsearch.action.search.SearchScrollRequest)
+     * @see org.elasticsearch.internal.client.Client#searchScroll(org.elasticsearch.action.search.SearchScrollRequest)
-     * @see org.elasticsearch.client.IndicesAdminClient#shardStores(IndicesShardStoresRequest)
+     * @see org.elasticsearch.internal.client.IndicesAdminClient#shardStores(IndicesShardStoresRequest)
-     * @see org.elasticsearch.client.IndicesAdminClient#create(org.elasticsearch.action.admin.indices.create.CreateIndexRequest)
+     * @see org.elasticsearch.internal.client.IndicesAdminClient#create(org.elasticsearch.action.admin.indices.create.CreateIndexRequest)
-     * @see org.elasticsearch.client.IndicesAdminClient#delete(org.elasticsearch.action.admin.indices.delete.DeleteIndexRequest)
+     * @see org.elasticsearch.internal.client.IndicesAdminClient#delete(org.elasticsearch.action.admin.indices.delete.DeleteIndexRequest)
-     * @see org.elasticsearch.client.IndicesAdminClient#close(org.elasticsearch.action.admin.indices.close.CloseIndexRequest)
+     * @see org.elasticsearch.internal.client.IndicesAdminClient#close(org.elasticsearch.action.admin.indices.close.CloseIndexRequest)
-     * @see org.elasticsearch.client.IndicesAdminClient#open(org.elasticsearch.action.admin.indices.open.OpenIndexRequest)
+     * @see org.elasticsearch.internal.client.IndicesAdminClient#open(org.elasticsearch.action.admin.indices.open.OpenIndexRequest)
-     * @see org.elasticsearch.client.IndicesAdminClient#putMapping(org.elasticsearch.action.admin.indices.mapping.put.PutMappingRequest)
+     * @see org.elasticsearch.internal.client.IndicesAdminClient#putMapping(PutMappingRequest)
-     * @see org.elasticsearch.client.IndicesAdminClient#refresh(org.elasticsearch.action.admin.indices.refresh.RefreshRequest)
+     * @see org.elasticsearch.internal.client.IndicesAdminClient#refresh(org.elasticsearch.action.admin.indices.refresh.RefreshRequest)
-     * @see org.elasticsearch.client.IndicesAdminClient#flush(org.elasticsearch.action.admin.indices.flush.FlushRequest)
+     * @see org.elasticsearch.internal.client.IndicesAdminClient#flush(org.elasticsearch.action.admin.indices.flush.FlushRequest)
-     * @see org.elasticsearch.client.IndicesAdminClient#forceMerge(org.elasticsearch.action.admin.indices.forcemerge.ForceMergeRequest)
+     * @see org.elasticsearch.internal.client.IndicesAdminClient#forceMerge(ForceMergeRequest)
-     * @see org.elasticsearch.client.ClusterAdminClient#state(org.elasticsearch.action.admin.cluster.state.ClusterStateRequest)
+     * @see org.elasticsearch.internal.client.ClusterAdminClient#state(org.elasticsearch.action.admin.cluster.state.ClusterStateRequest)
-     * @see org.elasticsearch.client.ClusterAdminClient#health(org.elasticsearch.action.admin.cluster.health.ClusterHealthRequest)
+     * @see org.elasticsearch.internal.client.ClusterAdminClient#health(ClusterHealthRequest)
-     * @see org.elasticsearch.client.ClusterAdminClient#nodesInfo(org.elasticsearch.action.admin.cluster.node.info.NodesInfoRequest)
+     * @see org.elasticsearch.internal.client.ClusterAdminClient#nodesInfo(NodesInfoRequest)
-     * @see org.elasticsearch.client.ClusterAdminClient#nodesStats(org.elasticsearch.action.admin.cluster.node.stats.NodesStatsRequest)
+     * @see org.elasticsearch.internal.client.ClusterAdminClient#nodesStats(NodesStatsRequest)
-     * @see org.elasticsearch.client.ClusterAdminClient#nodesStats(org.elasticsearch.action.admin.cluster.node.stats.NodesStatsRequest)
+     * @see org.elasticsearch.internal.client.ClusterAdminClient#nodesStats(NodesStatsRequest)
-     * @see org.elasticsearch.client.ClusterAdminClient#nodesUsage(org.elasticsearch.action.admin.cluster.node.usage.NodesUsageRequest)
+     * @see org.elasticsearch.internal.client.ClusterAdminClient#nodesUsage(NodesUsageRequest)
-     * @see org.elasticsearch.client.ClusterAdminClient#clusterStats(org.elasticsearch.action.admin.cluster.stats.ClusterStatsRequest)
+     * @see org.elasticsearch.internal.client.ClusterAdminClient#clusterStats(ClusterStatsRequest)
-     * @see org.elasticsearch.client.ClusterAdminClient#listTasks(ListTasksRequest)
+     * @see org.elasticsearch.internal.client.ClusterAdminClient#listTasks(ListTasksRequest)
-     * @see org.elasticsearch.client.ClusterAdminClient#getTask(GetTaskRequest)
+     * @see org.elasticsearch.internal.client.ClusterAdminClient#getTask(GetTaskRequest)
-     * @see org.elasticsearch.client.ClusterAdminClient#cancelTasks(CancelTasksRequest)
+     * @see org.elasticsearch.internal.client.ClusterAdminClient#cancelTasks(CancelTasksRequest)
-     * @param client A {@link org.elasticsearch.client.ParentTaskAssigningClient} with the parent task set to the upgrade task. Does not set
-     *               the origin header, so implementors of this method will likely want to wrap it in an
-     *               {@link org.elasticsearch.client.OriginSettingClient}.
+     * @param client A {@link org.elasticsearch.internal.client.ParentTaskAssigningClient} with the parent task set to the upgrade task.
+     *               Does not set the origin header, so implementors of this method will likely want to wrap it in an
+     *               {@link org.elasticsearch.internal.client.OriginSettingClient}.
-     * @param client A {@link org.elasticsearch.client.ParentTaskAssigningClient} with the parent task set to the upgrade task. Does not set
-     *               the origin header, so implementors of this method will likely want to wrap it in an
-     *               {@link org.elasticsearch.client.OriginSettingClient}.
+     * @param client A {@link org.elasticsearch.internal.client.ParentTaskAssigningClient} with the parent task set to the upgrade task.
+     *               Does not set the origin header, so implementors of this method will likely want to wrap it in an
+     *               {@link org.elasticsearch.internal.client.OriginSettingClient}.
-        ids.put(94, org.elasticsearch.client.transport.NoNodeAvailableException.class);
+        ids.put(94, org.elasticsearch.internal.client.transport.NoNodeAvailableException.class);
- * See also {@link NoOpNodeClient} if you need to mock a {@link org.elasticsearch.client.node.NodeClient}.
+ * See also {@link NoOpNodeClient} if you need to mock a {@link org.elasticsearch.internal.client.node.NodeClient}.
-     * A mocked {@link org.elasticsearch.client.node.NodeClient} which can be easily reconfigured to verify arbitrary verification
+     * A mocked {@link org.elasticsearch.internal.client.node.NodeClient} which can be easily reconfigured to verify arbitrary verification
```

**Comment by ChrisHegarty** [comment]
@elasticmachine retest this please

**Comment by ChrisHegarty** [comment]
BWC failure is unrelated and has an issue #82014 already.

**Review by pgomulka — APPROVED** [review]
LGTM, it is an automated refactoring so no point reviewing  every file. Chrome will crash anyway. 
the new name is good to me

**Comment by pgomulka** [comment]
@elasticmachine update branch

**Comment by ChrisHegarty** [comment]
@elasticmachine update branch

**Comment by ChrisHegarty** [comment]
@elasticmachine retest this please

**Pull request merged**
