### PR TITLE
RabbitMQ action for X-Pack Watcher plug-in

### PR DESCRIPTION
**Pull request by martintoshevresolve**
The Elasticsearch Watcher plug-in extension provides a RabbitMQ action as a notification target. Similar to the watcher JIRA action it requires SSL connection to the RabbitMQ host. The action is of type 'rabbitmq' and accepts the following:

- vhost: RabbitMQ virtual host (if ommitted default vhost assumed)
- exchange: exchange for which to send the alerts (supports Mustache templates, if ommmited default exchange assumed)
- routingKey (optional): routing key for the RabbitMQ messages (supports Mustache templates)
- headers: list of header values to send for the message (supports Mustache templates)
- message: the message (supports Mustache templates)

Example:

```
 "actions" : {
    "rabbitmq_action" : {
      "rabbitmq" : {
            "vhost" : "test",
            "exchange" : "test",
            "routingKey" : "test_key",
             "headers" : {
			"test_header" : "test_header_value"
	     },
	     "message" : "Found {{ctx.payload.hits.total}} logs"
      }
    }
  }
```

The following configuration needs to be specified in order to identify the connection to the RabbitMQ host (URL, username and password, similar to the configuration of the JIRA action extension):

```
bin\elasticsearch-keystore add xpack.notification.rabbitmq.account.monitoring.secure_url
bin\elasticsearch-keystore add xpack.notification.rabbitmq.account.monitoring.secure_user
bin\elasticsearch-keystore add xpack.notification.rabbitmq.account.monitoring.secure_password
```

### CODE REVIEW

**Comment by pgomulka** [comment]
@martintoshevresolve please do provide more context in a description

**Comment by martintoshevresolve** [comment]
@pgomulka @danhermann Thank you for the feedback and sorry for delayed response (I just got back from vacation and couldn't respond earlier). I've added more detailed description to the PR.
On the matter of the AMQP client, it is the preferred way of communicating with the RabbitMQ message broker. HTTP API is provided through the management plugin (reference: https://raw.githack.com/rabbitmq/rabbitmq-management/v3.8.4/priv/www/api/index.html) but many production scenarios are not enabling rabbitmq_management plugin (for security reasons). So the two options for this action to be added to the Watcher plugin are:

- still use the AMQP client which is already quite robust (in that particular scenario and in the way customers are going to use it shouldn't be a greater security concern compared to an HTTP-equivalent as more or less it will impose a similar set of concerns and SSL is required by default);

- requiring the RabbitMQ management plug-in to be enabled on the RabbitMQ instance and rewrite the logic to use the sample HTTP client  instead of the AMQP one.

Option 1 would eventually be more general purpose and preferrable. Isn't requiring HTTP(s) only for interaction with external systems too limiting for eventual extensions to the Watcher plug-in ? There is also an email action which is not using HTTP and a perspective to add support for more actions to external systems not providing an HTTP-based API.

**Comment by danhermann** [comment]
@martintoshevresolve, the security concerns that I mentioned were not about the communication between Watcher and RabbitMQ but the fact that any vulnerabilities in the AMQP client libraries could compromise Elasticsearch itself since the AMQP libraries would be loaded in the same JVM as Elasticsearch. For that reason, there's a pretty high bar for adding new third-party dependencies like that to Elasticsearch.

**Comment by martintoshevresolve** [comment]
@danhermann In that case would it make sense to modify the PR to use the current HTTP client and go with the option of using the management REST API (which would require RabbitMQ management plugin to be enabled) ? If yes, is there anything else I should also consider around the PR ?

**Comment by jakelandis** [comment]
@martintoshevresolve - If API's are avilable over HTTP would the [webhook action](https://www.elastic.co/guide/en/elasticsearch/reference/current/actions-webhook.html) work instead ?

**Comment by martintoshevresolve** [comment]
@jakelandis Seems like it will work yes, the only inconvenience I see is the fact that json format would need to be used in the request body. I am closing in that regard the PR for now, if at some point you think it might be beneficial to modify it accordingly in order to have a dedicated rabbitmq action I will be happy to address extra work around it.

**Pull request closed without merging**
