### PR TITLE
[8.x] Rework RRF to be evaluated during rewrite phase (#112648)

### PR DESCRIPTION
**Pull request by pmpailis**
Backports the following commits to 8.x:
 - Rework RRF to be evaluated during rewrite phase (#112648)

### CODE REVIEW

**Comment by andreidan** [comment]
@elasticmachine update branch

**Comment by andreidan** [comment]
@elasticmachine run elasticsearch-ci/8.15.3 / bwc-snapshots

**Comment by andreidan** [comment]
@elasticmachine run elasticsearch-ci/bwc-snapshots

**Comment by pmpailis** [comment]
@elasticmachine update branch

**Pull request merged**
