### PR TITLE
System index deprecation warning is not critical

### PR DESCRIPTION
**Pull request by williamrandolph**
When we planned to fully cut off access to system indices in 8.0, we needed our system index deprecation warning to be critical. Now that we are merely hiding system indices, avoiding system index access is no longer critical, and there is very little that users can do to change their access patterns. Therefore, we should log the warning at `WARN` level, rather than at `CRITICAL`.

### CODE REVIEW

**Review by cjcenizal — COMMENTED** [review]
Thanks for making this change, Will! I think this is an improvement. At the same time, these logs will still show up in Upgrade Assistant due to Kibana accessing these system indices. Elasticsearch will complain to the user about something that Kibana is doing. It makes it look like our products don't play well together. What kind of impression will that leave with our users?

Also, as you pointed out, these logs aren't actionable -- so what's the point? They become noise in the upgrade process. Can we remove them entirely in 7.16?

**Review by AthenaEryma — APPROVED** [review]
Code changes LGTM, pending a decision on the points CJ raised.

**Comment by williamrandolph** [comment]
> Also, as you pointed out, these logs aren't actionable -- so what's the point? They become noise in the upgrade process. Can we remove them entirely in **7.16?**

@cjcenizal Was this question something we needed to discuss before merging, or do we have other issues covering this point of discussion?

**Comment by cjcenizal** [comment]
@williamrandolph No not a a blocker. @sebelga is now looking into this problem from the Kibana/UA side and will re-raise this concern in another context if necessary. Thanks for asking!

**Pull request merged**
