### PR TITLE
Fixed section name and api name in docs

### PR DESCRIPTION
**Pull request by kakakakakku**
I fixed section name, like image bellow.
- https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html

es-docs

Thank you so much.

### CODE REVIEW

**Comment by jpountz** [comment]
Actually I think it is at the right level, but maybe the right fix would be to get this section a better title. @nik9000 what do you think?

**Comment by Kakakakakku** [comment]
@jpountz 
Oh sorry, I understand.

So, how about these title, or any better idea?

* Detect noop
* Detecting noop

>but maybe the right fix would be to get this section a better title.

**Comment by jpountz** [comment]
I like "Detecting noop".

**Comment by Kakakakakku** [comment]
@jpountz 
Thank you for your advise.
I fixed it, and I changed commit message.

Section level is staying `===` now.
Thank you!

**Comment by jpountz** [comment]
I'll wait for @nik9000 to give his opinion but this looks good to me.

**Comment by Kakakakakku** [comment]
Of course :grinning:

**Comment by nik9000** [comment]
Sure! Its fine with me.

**Comment by Kakakakakku** [comment]
:+1:

**Comment by clintongormley** [comment]
thanks @Kakakakakku - merged

**Pull request merged**
