### PR TITLE
add user defined attributes in _cat/nodes output

### LINKED ISSUE #8000: Node attributes in _cat/nodes
It would be useful if `_cat/nodes` can output node attributes like rack_id, aws_zone and other user defined attributes. If users have a large cluster with nodes in multiple AZ's or racks, it would be great to have this info in `_cat/nodes` to understand the topology. 

Even if not displayed by default, we could allow users to pass in `nodes?h=rack_id`

Example:

```
host                     ip          heap.percent ram.percent load node.role master name rack_id
Suyogs-MacBook-Pro.local 192.168.1.6            0                  d         *      Jann rack_1
Suyogs-MacBook-Pro.local 192.168.1.6            0                  d         *      Hoder rack_2
```

### PR DESCRIPTION
**Pull request by bookshelfdave**
This PR allows custom node attributes to be displayed via `/_cat/nodes`.

Because custom node attributes are required to trigger this feature, rest-api-spec doesn't seem to satisfy the testing requirement. What's the best way to test this functionality, and where is a good place for me to start looking?

Here's a sample of the output when running with the following modifications to `elasticsearch.yml`:

```
node.rack: rack314
node.azone: us-east-1
```

Sample output:

```
$ curl -XGET 'http://localhost:9200/_cat/nodes'
host    ip          heap.percent ram.percent load node.role master name
epsilon 192.168.1.8            1          72 3.10 d         *      Alexander Bont
$ curl -XGET 'http://localhost:9200/_cat/nodes?h=node.rack,node.azone'
node.rack node.azone
  rack314  us-east-1
```

Closes #8000

### CODE REVIEW

**Comment by jasontedor** [comment]
This LGTM, but can you add a REST test in rest-api-spec?

**Comment by dakrone** [comment]
I don't think we currently have a way to add node attributes for the REST tests, @clintongormley do you know if that's currently possible?

**Comment by drewr** [comment]
Apologies @metadave, I just added a comment to #8000 about the design here. Would you mind taking a look before merging?

**Comment by jasontedor** [comment]
@dakrone is correct, it is not currently possible. I investigated the possibility of adding it and I do not think it's worthwhile. The underlying issue is that to enable this functionality, we would no longer be able to reuse the cluster across REST tests (i.e., switch to `Scope.TEST` from `Scope.SUITE`). This would take the REST tests from slow to unacceptably slow.

**Comment by metadave** [comment]
I'm going to close this and work on a new API `_cat/nodeattrs` that has denormalized attributes. Thanks!

**Pull request closed without merging**
