### PR TITLE
Remove unused clusterService instance in ActionModule.

### PR DESCRIPTION
**Pull request by howardhuanghua**
Now we don't need clusterService instance in `ActionModule` anymore, remove it.

### CODE REVIEW

**Comment by rjernst** [comment]
@elasticmachine ok to test

**Comment by rjernst** [comment]
@elasticmachine update branch

**Comment by rjernst** [comment]
@howardhuanghua Could you please update your branch with the tip of master? I'm not able to do this due to permissions of your fork.

**Comment by howardhuanghua** [comment]
@rjernst I have merged master branch, thank you.

**Comment by howardhuanghua** [comment]
By the way, is there any settings that we could grant the update branch permissions?  @rjernst

**Comment by rjernst** [comment]
> is there any setting that we could grant the update branch permissions?

I believe you need to check the "Allow edits from maintainers". See https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork.

**Comment by rjernst** [comment]
Thanks for the contribution @howardhuanghua.

**Pull request merged**
