### PR TITLE
[Geo] Integrate Lucene's LatLonShape (BKD Backed GeoShapes) as default `geo_shape` indexing approach

### PR DESCRIPTION
**Pull request by nknize**
This PR exposes lucene's `LatLonShape` field as the default type in `GeoShapeFieldMapper`. To use the new indexing approach, simply set `"type" : "geo_shape"` in the mappings without setting any of the `strategy`, `precision`, `tree_levels`, or `distance_error_pct` parameters. Note the following when using the new indexing approach:

* `geo_shape` query does not support querying by `MULTIPOINT`.
* `LINESTRING` and `MULTILINESTRING` queries do not yet support `WITHIN` relation. This will be added in the future as a `buffered_query`.
* `CONTAINS` relation is not yet supported.
* The `tree`, `precision`, `tree_levels`, `distance_error_pct`, and `points_only` parameters are deprecated.
* This PR will be backported to 6.6 (with deprecation logging included) and a separate parameter removal PR will be opened for 7.0.

All other `geo_shape` features are supported.

relates #35320

### CODE REVIEW

**Comment by nknize** [comment]
backport to 6.6 for PR #35320  /cc @jpountz

**Comment by nknize** [comment]
Note that this is mostly for CI testing. Not much has changed (w/ the exception of differences in some of the overridden mapping methods)

**Comment by nknize** [comment]
retest this

**Comment by nknize** [comment]
retest this please

**Comment by nknize** [comment]
retest this

**Comment by nknize** [comment]
retest this please

**Comment by nknize** [comment]
retest this please

**Review by iverase — APPROVED** [review]
looks good to me

**Comment by nknize** [comment]
Looks like we have some more forbidden api failures similar to #36794  This is not an area of strength for me. Any thoughts @atorok? /cc @jpountz @imotov

**Comment by iverase** [comment]
Note #36834, tags from the forked classes should be removed.

**Review by imotov — COMMENTED** [review]
> Note the following when using the new indexing approach

Sorry, I am a minute too late to submit the review, but I will still ask just for clarification. If a user periodically creates indices using a templates that is using default tree type and any of the functionality that has been changed the first index that they auto create after the upgrade will break their app without a warning?

**Pull request merged**
