### PR TITLE
[DOCS] Replace nested open block for Asciidoctor migration

### PR DESCRIPTION
**Pull request by jrodewig**
Per https://github.com/asciidoctor/asciidoctor/issues/1121, Asciidoctor does not currently allow nested open blocks. This removes the nested open block from the [Index modules](https://www.elastic.co/guide/en/elasticsearch/reference/master/index-modules.html) page and replaces it with a table.

This prevents the following error:
`INFO:build_docs:asciidoctor: ERROR: illegal block content outside of partintro block`

Relates to #41128

### CODE REVIEW

**Comment by nik9000** [comment]
If the table renders well I'm happy with it. I know we usually use definition lists because tables tend to come out poorly when we try to use them for this sort of thing.

**Comment by jrodewig** [comment]
Thanks for the feedback @nik9000. Here's a screenshot from my local build:

index-modules

I agree that tables generally aren't preferred, but I couldn't figure out a way to nest a definition list here. Please feel free to leave a suggestion or point me the right way if I'm overlooking something though.

**Review by nik9000 — APPROVED** [review]
That looks fine to me!

**Comment by lcawl** [comment]
Another possible solution that seems to work for me is this:

> Accepts:
`false`::: (default) Don't check for corruption when opening a shard.
`checksum`::: Check for physical corruption.
`true`::: Check for both physical and logical corruption. This is much more
expensive in terms of CPU and memory usage.
> +
>WARNING: Expert only. Checking shards may take a lot of time on large indices.

**Comment by jrodewig** [comment]
Thanks for the solve @lcawl. Pushed c5b9aa2 to reformat the table to a definition list.

I feel much better about this without a table.

**Review by lcawl — APPROVED** [review]
LGTM and builds successfully

**Pull request merged**
