### PR TITLE
Allow TrimFilter to be used in custom normalizers

### LINKED ISSUE #27310: Normalizer doesn’t like trim filter
When I use trim filter in normalizer I get this exception:

"type" : "illegal_argument_exception",
"reason" : "Custom normalizer [my_normalizer] may not use filter [trim]"

But it's fine to use the lowercase filter instead.

### PR DESCRIPTION
**Pull request by romseygeek**
Closes #27310

### CODE REVIEW

**Comment by romseygeek** [comment]
cc @jpountz

**Comment by jpountz** [comment]
Test fail because they check whether our own factories are in sync with Lucene, which is not the case since Lucene doesn't have MultiTermAwareComponent on its TrimFilterFactory. So we need to add an exception to the test if we want to do that, ideally linking to a Lucene issue so that both factories converge one day.

**Comment by romseygeek** [comment]
I opened https://issues.apache.org/jira/browse/LUCENE-8093 for the upstream fix

**Comment by romseygeek** [comment]
The test failures above seem to be unrelated to the change.  @jpountz is there a standard way of adding version-related test special cases?  I've bodged something together for this one but I'm sure there's a nicer way of doing it.

**Review by jimczi — APPROVED** [review]
LGTM

**Pull request merged**
