### PR TITLE
Updating toXContent implementation for retrievers

### PR DESCRIPTION
**Pull request by pmpailis**
Updating the base implementation  of `toXContent` for all retrievers, so that we also include the retriever type.

Taking the following retriever as an example:
```
{
  "retriever": {
    "knn": {
      "query_vector": [
        3
      ],
      "field": "vector",
      "k": 10,
      "num_candidates": 15
    }
  }
}
```

calling 
```
Strings.toString(retriever);
```

changes the output from
```
{
  "field" : "vector",
  "k" : 10,
  "num_candidates" : 15,
  "query_vector" : [ 3.0 ]
}
```
to 
```
{
  "knn" : {
    "field" : "vector",
    "k" : 10,
    "num_candidates" : 15,
    "query_vector" : [ 3.0 ]
  }
}
```

### CODE REVIEW

**Review by benwtrent — COMMENTED** [review]
Does this break the API at all? I am surprised how a change toXContent still works with fromxcontent and the API remains unchanged :/

**Comment by pmpailis** [comment]
> Does this break the API at all? I am surprised how a change toXContent still works with fromxcontent and the API remains unchanged :/

Retrievers were transient and not a member of `SearchSourceBuilder` , as they were completely flattened out during parsing up until 8.16. (link [here](https://github.com/elastic/elasticsearch/blob/8.15/server/src/main/java/org/elasticsearch/search/builder/SearchSourceBuilder.java#L1660)) due to the parser-only approach we had.  

I could be missing something, but I'm not sure at which point the `toXContent` could actually be called for retrievers, as they were short-lived objects only within  `SearchSourceBuilder#parseXContent`  scope. 

I've tried to capture the bug that this PR targets in these tests -> https://github.com/elastic/elasticsearch/pull/114017/commits/7acb51e74d15e6a06ef895f3dfee028c36e51e3e

**Comment by pmpailis** [comment]
Maybe I should change this from a `non-issue` to a `bug` ? 🤔

**Comment by pmpailis** [comment]
@elasticmachine update branch

**Comment by benwtrent** [comment]
> I could be missing something, but I'm not sure at which point the toXContent could actually be called for retrievers, as they were short-lived objects only within SearchSourceBuilder#parseXContent scope.


My concern is that changing the `toXContent` changes the `fromXContent` parsing and thus changes the API interaction. That is why I was surprised.

**Comment by pmpailis** [comment]
Yeah, I see what you mean. Tbh this change would bring retriever parsing closer to how `QueryBuilders` are currently parsed (through the `AbstractQueryBuilder#parseTopLevelQuery`. 

For example, currently on `main` the following throws: 
```
        TermQueryBuilder termQueryBuilder = new TermQueryBuilder("foo", "bar");
        try (XContentParser parser = createParser(JsonXContent.jsonXContent, Strings.toString(termQueryBuilder))) {
            QueryBuilder parsed = TermQueryBuilder.fromXContent(parser);
        }
```
->
```
[term] query does not support [foo]
org.elasticsearch.common.ParsingException: [term] query does not support [foo]
	at org.elasticsearch.index.query.TermQueryBuilder.fromXContent(TermQueryBuilder.java:141)
```
while the following succeeds
```
        TermQueryBuilder termQueryBuilder = new TermQueryBuilder("foo", "bar");
        try (XContentParser parser = createParser(JsonXContent.jsonXContent, Strings.toString(termQueryBuilder))) {
            QueryBuilder parsed = AbstractQueryBuilder.parseTopLevelQuery(parser);
        }
```

Similarly, for retrievers, we would be able to use the top-level `RetrieverBuilder#parseTopLevelRetrieverBuilder` to properly parse any given retriever (which is also how they're parsed in `SearchSourceBuilder`). 

The idea here is for the retriever itself to emit information on how to parse through XContent, because otherwise, having just (from the description) 
```
{
  "field" : "vector",
  "k" : 10,
  "num_candidates" : 15,
  "query_vector" : [ 3.0 ]
}
```
would not give any information on which retriever/parsing should actually be used.  IMO specific `RetrieverBuilder.fromXContent` implementations should not be called, but should be selected dynamically during parsing based on the registered `RetrieverSpec`.

**Review by benwtrent — APPROVED** [review]

**Comment by pmpailis** [comment]
run elasticsearch-ci/part-1

**Pull request merged**
