### PR TITLE
Reduce InternalSingleBucketAggregation in a streaming fashion

### PR DESCRIPTION
**Pull request by iverase**
For InternalSingleBucketAggregation we are collecting all the subaggregations in memory before reducing them which it can be wasteful. Here we introduce a AggregatorsReducer that reduces InternalAggregations in a streaming fashion. we use it to stream the reduction for the subaggregations of InternalSingleBucketAggregation.

relates https://github.com/elastic/elasticsearch/pull/105207

### CODE REVIEW

**Comment by iverase** [comment]
@elasticmanchine update branch

**Comment by iverase** [comment]
@elasticmachine update branch

**Review by nik9000 — APPROVED** [review]
Oh neat. It looks like you've just lifted the behavior from the top level reduction into a reusable bit. And we can reuse that bit later for the multi-bucket reductions. Just like last time, there shouldn't be any performance degradation with this PR because the single-bucket aggs never did any sort of walking and merging. This just let's us "pass through" the streaming behavior to aggs below.

Neat.

**Comment by iverase** [comment]
The same happens with InternalFilters and InternalRanges: https://github.com/elastic/elasticsearch/pull/105348

**Pull request merged**
