### PR TITLE
SQL: Describe aliases as views

### PR DESCRIPTION
**Pull request by costin**
When reporting metadata, several clients have issues with the 'ALIAS'
type. To improve compatibility and be consistent with the ANSI SQL
expectations and because they are similar, aliases targets are now
reported as views.

Close #37422

### CODE REVIEW

**Comment by costin** [comment]
run gradle test 1

**Comment by costin** [comment]
run the gradle build tests 1

**Review by astefan — APPROVED** [review]
LGTM

**Review by bpintea — APPROVED** [review]
LGTM

**Comment by costin** [comment]
run the gradle build tests 1

**Comment by costin** [comment]
run the gradle build tests 2

**Comment by costin** [comment]
run the gradle build tests 2

**Review by matriv — APPROVED** [review]
LGTM

**Comment by costin** [comment]
run the gradle build tests 2

**Comment by costin** [comment]
run the gradle build tests 2

**Pull request merged**
