### PR TITLE
Added index name to CreateIndexResponse and DeleteIndexResponse.

### PR DESCRIPTION
**Pull request by kunal642**
Added index name to CreateIndexResponse and DeleteIndexResponse.
related to #23044

### CODE REVIEW

**Comment by kunal642** [comment]
Hi guys,
This is still a WIP, just wanted to verify if i am going in the right direction or not.
Please suggest any changes if required

**Comment by jasontedor** [comment]
Thanks for the PR @kunal642. However, there is an open PR for this (#23061) although it's not complete. I think we should let that one either be completed or abandoned before proceeding with this one.

For future guidance, what you have here is not enough. You're missing serialization on the transport layer (with your change, start two nodes, sent a create index request to the non-master node, and then observe that you will not see the index name in the response; this should elucidate why you need serialization on the transport layer). Secondly, you're missing tests.

**Comment by jasontedor** [comment]
I'm going to close this pull request until we have closure on #23061.

**Comment by kunal642** [comment]
@jasontedor thanks

**Pull request closed without merging**
