### PR TITLE
Add link to flood-stage watermark exception message

### PR DESCRIPTION
**Pull request by stefnestor**
👋 howdy, team! This PR
- links `disk usage exceeded flood-stage watermark, index has read-only-allow-delete block` error to [resolution doc](https://www.elastic.co/guide/en/elasticsearch/reference/current/fix-watermark-errors.html) 
- formats doc into sections (monitor, temporary relief, resolve). Expands resolve with moving indices along ILM & notes if want to scale-out in ESS will need Support if status red. 

🙋‍♀️ Question
1. We talk about "index write blocks" and then reference removing `index.blocks.read_only_allow_delete` which I assume is accurate. But Support sometimes finds we need to run `index.blocks.write` against `.kibana*` to recover it. 

    👉 [(Doc+) Recovery ".kibana*" indices write block kibana#189999](https://github.com/elastic/kibana/pull/189999)

### CODE REVIEW

**Review by DaveCTurner — COMMENTED** [review]
Looks good, just a couple of nits in the docs.

**Comment by stefnestor** [comment]
Okay, ready! 💚

**Comment by stefnestor** [comment]
I just noticed the Health API > DiskHealthIndicator Service links to a shorter version of our same page `https://ela.st/fix-disk-space"`, would we potentially want to use that instead? 

https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/health/node/DiskHealthIndicatorService.java#L502C68-L502C97

**Comment by DaveCTurner** [comment]
> links to a shorter version of our same page https://ela.st/fix-disk-space", would we potentially want to use that instead?

No, `ReferenceDocs` is preferred. The `https://ela.st/` links are not versioned or validated so they'll degrade over time.

**Comment by stefnestor** [comment]
@DaveCTurner does this look okay now to approve? Any other feedback? 🙂

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Pull request merged**
