### PR TITLE
Fix ConnectionManagerTests

### LINKED ISSUE #44758: [CI] ConnectionManagerTests failures
This has failed 4 times in the last 4 days, `testConnectFailsDuringValidation` was responsible for 3 of them and `    testConcurrentConnectsAndDisconnects` for the other

https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-90d,mode:quick,to:now))&_a=(columns:!(_source),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:ConnectionManagerTests),sort:!(time,desc))

Log: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob+fast+part1/381/console

Build Scans: https://gradle.com/s/h2fc43mhmbuma

Reproduction lines: 
```
REPRODUCE WITH: ./gradlew :server:test --tests "org.elasticsearch.transport.ConnectionManagerTests.testConcurrentConnectsAndDisconnects" \
  -Dtests.seed=58603A96C6436123 \
  -Dtests.security.manager=true \
  -Dtests.locale=ksf \
  -Dtests.timezone=America/Knox_IN \
  -Dcompiler.java=12 \
  -Druntime.java=11

REPRODUCE WITH: ./gradlew :server:test --tests "org.elasticsearch.transport.ConnectionManagerTests.testConnectFailsDuringValidation" \
  -Dtests.seed=58603A96C6436123 \
  -Dtests.security.manager=true \
  -Dtests.locale=ksf \
  -Dtests.timezone=America/Knox_IN \
  -Dcompiler.java=12 \
  -Druntime.java=11

REPRODUCE WITH: ./gradlew :server:test --tests "org.elasticsearch.transport.ConnectionManagerTests.testConcurrentConnectsAndDisconnects" \
  -Dtests.seed=58603A96C6436123 \
  -Dtests.security.manager=true \
  -Dtests.locale=ksf \
  -Dtests.timezone=America/Knox_IN \
  -Dcompiler.java=12 \
  -Druntime.java=11

REPRODUCE WITH: ./gradlew :server:test --tests "org.elasticsearch.transport.ConnectionManagerTests.testConnectFailsDuringValidation" \
  -Dtests.seed=58603A96C6436123 \
  -Dtests.security.manager=true \
  -Dtests.locale=ksf \
  -Dtests.timezone=America/Knox_IN \
  -Dcompiler.java=12 \
  -Druntime.java=11
```

Failure:
```
16:05:24   2> REPRODUCE WITH: ./gradlew :server:test --tests "org.elasticsearch.transport.ConnectionManagerTests.testConnectFailsDuringValidation" -Dtests.seed=58603A96C6436123 -Dtests.security.manager=true -Dtests.locale=ksf -Dtests.timezone=America/Knox_IN -Dcompiler.java=12 -Druntime.java=11
16:05:24   2> com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=11483, name=elasticsearch[ConnectionManagerTests][generic][T#1], state=RUNNABLE, group=TGRP-ConnectionManagerTests]
16:05:24 
16:05:24         Caused by:
16:05:24         java.lang.NullPointerException
16:05:24             at __randomizedtesting.SeedInfo.seed([58603A96C6436123]:0)
16:05:24             at org.elasticsearch.action.ActionListener.onFailure(ActionListener.java:193)
16:05:24             at org.elasticsearch.transport.ConnectionManager.lambda$connectToNode$4(ConnectionManager.java:187)
16:05:24             at org.elasticsearch.action.ActionListener$1.onFailure(ActionListener.java:70)
16:05:24             at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:64)
16:05:24             at org.elasticsearch.transport.ConnectionManagerTests.lambda$testConcurrentConnectsAndDisconnects$7(ConnectionManagerTests.java:147)
16:05:24   2> ŋ7 23, 2019 8:05:22 SÁRÚWÁ com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException
16:05:24   2> WARNING: Uncaught exception in thread: Thread[elasticsearch[ConnectionManagerTests][generic][T#3],5,TGRP-ConnectionManagerTests]
16:05:24   2> java.lang.NullPointerException
16:05:24   2> 	at __randomizedtesting.SeedInfo.seed([58603A96C6436123]:0)
16:05:24   2> 	at org.elasticsearch.action.ActionListener.onFailure(ActionListener.java:193)
16:05:24   2> 	at org.elasticsearch.transport.ConnectionManager.lambda$connectToNode$4(ConnectionManager.java:187)
16:05:24   2> 	at org.elasticsearch.action.ActionListener$1.onFailure(ActionListener.java:70)
16:05:24   2> 	at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:64)
16:05:24   2> 	at org.elasticsearch.transport.ConnectionManagerTests.lambda$testConcurrentConnectsAndDisconnects$7(ConnectionManagerTests.java:147)
16:05:24   2> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:699)
16:05:24   2> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
16:05:24   2> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
16:05:24   2> 	at java.base/java.lang.Thread.run(Thread.java:834)
```

### PR DESCRIPTION
**Pull request by original-brownbear**
* In both fake connection validators we were potentially executing the listener twice. This lead to the situation that the locking via `connectionLock` that ensures that each listener is only executed once ever
would fail and the lister would run twice (in which case the listeners for that node are already `null` and we get an NPE)
* The fact that two different tests fail is due to the fact that we weren't safely shutting down the threadpool which meant the the task that trips the assertion (on the generic pool) would leak into the next test and fail it
* Closes #44758

### CODE REVIEW

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/1
Jenkins run elasticsearch-ci/2

(unrelated watcher test failures in both ...)

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/2

(watcher ...)

**Review by ywelsch — APPROVED** [review]
LGTM

**Comment by original-brownbear** [comment]
Thanks @ywelsch !

**Pull request merged**
