### PR TITLE
Add resolve_during_rolling_upgrade field to deprecation issue

### LINKED ISSUE #73091: [Deprecation info API] Support for requires_restart field
Related to https://github.com/elastic/kibana/issues/36919.

In Upgrade Assistant, it would be helpful if we could identify any deprecations that can only be resolved offline.

We've received similar feedback for displaying Kibana deprecations, and support for this is being tracked in https://github.com/elastic/kibana/issues/98476.

**Proposal:**
```
{
   "cluster_settings": [],
   "node_settings": [
           {
            "level":"critical",
            "message":"Security realm settings structure changed",
            "url":"/docs",
            "details":"these settings must be updated to the new format while the node is offline during the upgrade to 7.0",
            // name is only a suggestion
            "requires_restart": true
         }
   ],
   "index_settings": {
      "logs:apache": [
         {
            "level":"warning",
            "message":"Index name cannot contain ':'",
            "url":"https://www.elastic.co/guide/en/elasticsearch/reference/7.0/breaking-changes-7.0.html#_literal_literal_is_no_longer_allowed_in_index_name",
            "details":"This index is named [logs:apache], which contains the illegal character ':'.",
            // name is only a suggestion
            "requires_restart": false
         }
      ]
   },
   "ml_settings": []
}
```

### PR DESCRIPTION
**Pull request by martijnvg**
Add an additional boolean field to a deprecation issue to indicate that a deprecation issue can only be resolved during a rolling upgrade when a node is offline (for the upgrade).

No deprecation issue has been marked as restart required as part of this change.

Closes #73091

### CODE REVIEW

**Review by dakrone — APPROVED** [review]
LGTM, though I have one minor question:

Would it be better named `resolve_during_rolling_restart` rather than `resolve_during_rolling_upgrade`? Especially because a user may want to resolve it prior to doing an upgrade rather than during the upgrade itself (separating resolution from upgrade).

What do you think?

**Comment by martijnvg** [comment]
> Would it be better named resolve_during_rolling_restart rather than resolve_during_rolling_upgrade? Especially because a user may want to resolve it prior to doing an upgrade rather than during the upgrade itself (separating resolution from upgrade).

This flag is intended for issues that only can be resolved during the upgrade when a node is offline (as is stated in elastic/kibana#36919). So changing the name to `resolve_during_rolling_restart ` would suggest that these deprecation issues can be resolved prior to the upgrade and this isn't the case. So I think we should stick with the current name?

Maybe we can add `resolve_during_rolling_restart` as an additional flag for issues that can only be resolved when a node is offline (without an upgrade taking place)? I think most deprecation issues around node settings fall into this category. Something along these lines was briefly discussed here: https://github.com/elastic/elasticsearch/issues/73091#issuecomment-863089858

**Comment by dakrone** [comment]
@martijnvg okay, that makes sense why we need the "upgrade" part, thanks for clarifying it. I think it would be useful to have both to indicate ones that must be done during upgrade, and ones that can be done while the node is stopped but not necessarily upgraded. However, I don't think we have to rush to add that right away, but we can revisit it when we need it, what do you think?

**Comment by martijnvg** [comment]
> However, I don't think we have to rush to add that right away, but we can revisit it when we need it, what do you think?

Yes, I agree. We can add `resolve_during_rolling_restart` (or a different name) later when it is needed.

**Pull request merged**
