### PR TITLE
Fix Repository Base Path Matching in Azure ITs (#41457)

### LINKED ISSUE #41405: CI job third-party-tests-azure fails consistently
From Apr. 17th, this junking jobs seems to be always failing, for example: 

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+third-party-tests-azure/8/console

The errors in the logs look like:

```
11:13:24     java.lang.RuntimeException: Failure at [repository_azure/10_repository:6]: 60 000 milliseconds timeout on connection http-outgoing-1 [ACTIVE]
11:13:24 
11:13:24         Caused by:
11:13:24         java.net.SocketTimeoutException: 60 000 milliseconds timeout on connection http-outgoing-1 [ACTIVE]
11:13:24 
11:13:24             Caused by:
11:13:24             java.net.SocketTimeoutException: 60 000 milliseconds timeout on connection http-outgoing-1 [ACTIVE]
```

### PR DESCRIPTION
**Pull request by original-brownbear**
* Added quotes so that "regexy" base paths like `7.0` that we use on CI
don't break matching
* closes #41405

backport of #41457

### CODE REVIEW

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/1 (looks like slow CI made the test cluster setup time out)

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/1 (looks like slow CI made the test cluster setup time out)

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/2

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/1 (looks like slow CI made the test cluster setup time out)

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/1 (looks like slow CI made the test cluster setup time out)

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/2

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/1

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/1

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/1

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/2

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/1

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/1
Jenkins run elasticsearch-ci/2

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/1

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/1

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/2

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/1
Jenkins run elasticsearch-ci/2

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/1

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/1
Jenkins run elasticsearch-ci/2

**Comment by atorok** [comment]
@original-brownbear  can you open an infra issue to make `elasticsearch-ci/1`  run with `--parallel` only on branches > `7.x`. this won't work on older   one since the changes weren't back ported that far.

**Comment by original-brownbear** [comment]
@atorok ah ok thanks :) I though we had just had some infra resource issue. WIllstop retrying this for the time being then :D

**Pull request merged**
