### PR TITLE
Fix Noisy Logging during Snapshot Delete

### PR DESCRIPTION
**Pull request by original-brownbear**
We were logging the cleanup of the snap- and meta- blobs for every snapshot delete
which is needlessly noisy and confusing to users. We should only log actual stale/unexpected
blobs here.

### CODE REVIEW

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/default-distro

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/bwc
Jenkins run elasticsearch-ci/default-distro

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/bwc
Jenkins run elasticsearch-ci/default-distro

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/1

**Review by tlrx — APPROVED** [review]
LGTM

**Comment by original-brownbear** [comment]
Thanks Tanguy!

**Pull request merged**
