### PR TITLE
Extending catch clause in rewriteAndFetch

### PR DESCRIPTION
**Pull request by pmpailis**
This is a spin off of [a comment in this PR](https://github.com/elastic/elasticsearch/pull/112648#discussion_r1755724253). 

It seems that  in `Rewriteable#rewriteAndFetch` we aim to catch very specific exception types, but if something fails with none of the listed exceptions (i.e. `IOException | IllegalArgumentException | ParsingException`) then the listener is not notified of the error, and we could skip releasing resources (or closing a PIT in the above PR). 

This is very narrow-scope, with no tests yet, as it's mostly raised as an inquiry at this point to see if there is a specific reason that we want to limit to just these exceptions.

### CODE REVIEW

**Review by jimczi — APPROVED** [review]

**Comment by javanna** [comment]
Would be good to add tests , especially if there are potential issues that this change fixes around releasing resources. Maybe that even makes it a bugfix rather than a non-issue?

**Comment by pmpailis** [comment]
> Would be good to add tests , especially if there are potential issues that this change fixes around releasing resources. Maybe that even makes it a bugfix rather than a non-issue?

There are a couple of such tests in the linked PR (https://github.com/elastic/elasticsearch/pull/112648) but we raise deliberate exceptions there to ensure that no PIT will be left open. I will look further into this but I'm not aware of other specific issues at the moment, hence why the PR was mostly raised as a discussion point.  

`Rewriteable#rewrite` raises an `IOException` by definition and in some cases where we raise different exceptions (e.g. in the `LearningToRankRescorerBuilder#doCoordinatorNodeRewrite` ([link](https://github.com/elastic/elasticsearch/blob/fe75aa38c9110b3254fcbdfc8ee535cc42f87ac5/x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/inference/ltr/LearningToRankRescorerBuilder.java#L207)), I'm not sure if we have any unaccounted resources, so testing doesn't seem so straightforward.

**Review by benwtrent — APPROVED** [review]
We should just catch everything that is catchable and ensure things are closed in rewrite. I say shipit.

**Comment by pmpailis** [comment]
@javanna do you have any concerns with merging this ?

**Comment by javanna** [comment]
no concerns

**Comment by pmpailis** [comment]
@elasticmachine update branch

**Pull request merged**
