### PR TITLE
Migrate IndicesExistsIT to Zen2

### PR DESCRIPTION
**Pull request by DaveCTurner**
This test was actually passing, for the wrong reason: it asserts a
`MasterNotDiscoveredException` is thrown, expecting this to be due to a failure
to perform state recovery, but in fact it's thrown because the node is not
correctly bootstrapped.

### CODE REVIEW

**Review by ywelsch — APPROVED** [review]

**Comment by DaveCTurner** [comment]
@elasticmachine please run the Gradle build tests 1

**Comment by DaveCTurner** [comment]
@elasticmachine please run the Gradle build tests 1

**Comment by DaveCTurner** [comment]
@elasticmachine please run the Gradle build tests 1

**Comment by DaveCTurner** [comment]
@elasticmachine please run the Gradle build tests 1

**Comment by DaveCTurner** [comment]
@elasticmachine please run the Gradle build tests 1

**Pull request merged**
