### PR TITLE
Flatten package structure for zen discovery

### PR DESCRIPTION
**Pull request by s1monw**
This package had lots of sub-packages with one or two classes each.
This commit flattens this structure for simiplification.

### CODE REVIEW

**Comment by dadoonet** [comment]
At some point we said that our settings maps nicely with package names.
Should we change also settings name in that case like renaming `discovery.zen.fd.ping_interval` to `discovery.zen.ping_interval`?

**Comment by s1monw** [comment]
@dadoonet I don't know what this scheme is but changing a settings is a big deal IMO I am happy to open a different issue for all of these but I will continue to fold packages together since 700 is just too much and not useful. I don't know what this mapping between packaging buys us to be honest. I am all for dropping this relationship on the floor.

**Comment by jpountz** [comment]
> I don't know what this mapping between packaging buys us to be honest.

I think it's useful so that if you change a setting and want to see effects in the logs, you can raise the log level of the logger which is associated with this setting.

However, I wouldn't care too much beyond the two first levels (ie. `discovery` and `discovery.zen`)  which this PR doesn't change so I'm +1 on the change.

**Comment by s1monw** [comment]
outdated - closing for now

**Pull request closed without merging**
