### PR TITLE
test: use the alternate range yaml format

### PR DESCRIPTION
**Pull request by salvatore-campagna**
Some clients break while trying to parse YAML using `{from: ..., to: ...}`. Use this alternate format, which is also the one used by other ranges in yaml tests.

### CODE REVIEW

**Comment by salvatore-campagna** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by salvatore-campagna** [comment]
@elasticmachine update branch

**Comment by salvatore-campagna** [comment]
@elasticmachine update branch

**Review by not-napoleon — APPROVED** [review]
LGTM

**Pull request merged**
