### PR TITLE
[ML] Allow training_percent to be any positive double up to hundred

### PR DESCRIPTION
**Pull request by dimitris-athanasiou**
This changes the valid range of `training_percent` for regression and
classification from [1, 100] to (0, 100].

### CODE REVIEW

**Review by droberts195 — APPROVED** [review]
LGTM

**Comment by dimitris-athanasiou** [comment]
run elasticsearch-ci/packaging-sample-windows

**Comment by dimitris-athanasiou** [comment]
@elasticmachine update branch

**Comment by dimitris-athanasiou** [comment]
run elasticsearch-ci/2 (ILM related test failure)

**Pull request merged**
