### PR TITLE
Also mmap field data (.fdt) files for hybridfs

### PR DESCRIPTION
**Pull request by easyice**
This change adds the terms index (.fdt) to the list of extensions
that are memory-mapped by hybridfs.

When the shard merge to single segments, and there are many concurrent queries, many search thread will wait on `nio.ch.FileChannelImpl.readInternal` for loadStoredFields . Because they using the same file reader.

in this case, the search will be  slower after force merge.

image

so we can mmap the fdt file for hybridfs.

I ran the same benchmark for merged index(_forcemerge?max_num_segments=1) , use `term` operation with size:100，and clients:48 for challenges, the query latency is significantly reduced

```
|                                                        Metric |   Task |    Baseline |   Contender |     Diff |   Unit |
|--------------------------------------------------------------:|-------:|------------:|------------:|---------:|-------:|
|                                                    Store size |        |     89.5487 |     6.61721 | -82.9314 |     GB |
|                                                 Translog size |        | 2.20258e-06 | 7.68341e-07 |       -0 |     GB |
|                                        Heap used for segments |        |     48.5703 |     8.96341 | -39.6069 |     MB |
|                                      Heap used for doc values |        |    0.170841 |   0.0307388 |  -0.1401 |     MB |
|                                           Heap used for terms |        |      23.787 |     7.32935 | -16.4577 |     MB |
|                                           Heap used for norms |        |   0.0970459 |   0.0722046 | -0.02484 |     MB |
|                                          Heap used for points |        |           0 |           0 |        0 |     MB |
|                                   Heap used for stored fields |        |     24.5154 |     1.53112 | -22.9843 |     MB |
|                                                 Segment count |        |         129 |          92 |      -37 |        |
|                                                Min Throughput |   term |     1414.96 |        1996 |  581.037 |  ops/s |
|                                               Mean Throughput |   term |     1442.53 |     2000.07 |  557.539 |  ops/s |
|                                             Median Throughput |   term |     1446.34 |     1999.66 |  553.315 |  ops/s |
|                                                Max Throughput |   term |     1451.13 |     2003.93 |  552.805 |  ops/s |
|                                       50th percentile latency |   term |     6438.94 |     4.87244 | -6434.07 |     ms |
|                                       90th percentile latency |   term |     10012.7 |     5.99424 | -10006.7 |     ms |
|                                       99th percentile latency |   term |     10863.9 |     22.4411 | -10841.5 |     ms |
|                                     99.9th percentile latency |   term |     11084.3 |     50.0183 | -11034.3 |     ms |
|                                    99.99th percentile latency |   term |     11144.5 |     69.8108 | -11074.7 |     ms |
|                                      100th percentile latency |   term |     11163.8 |     70.4458 | -11093.3 |     ms |
|                                  50th percentile service time |   term |     32.0711 |     3.91603 | -28.1551 |     ms |
|                                  90th percentile service time |   term |     39.9306 |     4.89072 | -35.0399 |     ms |
|                                  99th percentile service time |   term |     49.9024 |     16.0866 | -33.8158 |     ms |
|                                99.9th percentile service time |   term |     78.8434 |     38.3506 | -40.4927 |     ms |
|                               99.99th percentile service time |   term |     97.0518 |     68.6928 |  -28.359 |     ms |
|                                 100th percentile service time |   term |     102.925 |     69.2111 |  -33.714 |     ms |
|                                                    error rate |   term |           0 |           0 |        0 |      % |


```

### CODE REVIEW

**Comment by easyice** [comment]
this is jstack  output of runing search ,without this patch 

[s-61.txt](https://github.com/elastic/elasticsearch/files/6091765/s-61.txt)

**Comment by jimczi** [comment]
I am on the fence here because one of the main reason we introduced `hybridfs` was to avoid the mmap on the stored fields.
The read-ahead that mmap does is not appropriate for a file that is accessed randomly. I also wonder if your test is really representative, I understand that mmap might be faster for this cheap query but I wonder how that would degrade with queries that would return more diverse documents (in this test we always return the same set of document ?).

**Comment by jimczi** [comment]
Yannick spotted this discrepancy in the size of the data that is benchmarked:
```
  Store size |        |     89.5487 |     6.61721 | -82.9314 |     GB |
```

Why is it so different ? Are we comparing the same thing ?

**Comment by easyice** [comment]
Thanks for detailed replay. this test always return same set of documents.
the rally use geonames dataset, and the challenges was:

````
        {
          "operation": "term",
          "warmup-iterations": 200,
          "iterations": 1000,
          "target-throughput": 2000,
          "clients": 48
        }
````

The operation of `term` is:

````
    {
      "name": "term",
      "operation-type": "search",
      "body": {
      "size": 100,
        "query": {
          "term": {
            "country_code.raw": "AT"
          }
        }
      }
    },
````

I agree that the read-ahead of mmap is really not appropriate for randomly access,In theory the niofs is better in lower query concurrency. my store device is nvme ssd ,  I think that might be better for mmap

The difference between   `Store size`  is  because i use two single node in the test,  `Store size`  in esrally is cluster level size, one of the node has more indices, So there's this difference, the index size of  geonames with the benchmark Is the same:

````
curl 127.0.0.1:6200/_cat/indices/geonames
green open geonames XciITgd1TA6jc23PSu5xzA 5 0 11396503 0 3.2gb 3.2gb
curl 127.0.0.1:8200/_cat/indices/geonames
green open geonames XciITgd1TA6jc23PSu5xzA 5 0 11396503 0 3.2gb 3.2gb
````

**Comment by henningandersen** [comment]
Are you running this on windows? I believe the JDK will use pread on linux, which supports concurrent reads. See following:

[windows needs positional lock](https://github.com/openjdk/jdk/blob/master/src/java.base/windows/classes/sun/nio/ch/FileDispatcherImpl.java#L48)

[synchronized when positional lock is needed](https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/sun/nio/ch/FileChannelImpl.java#L795)

[default is no positional lock](https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/sun/nio/ch/NativeDispatcher.java#L46)

Additionally, I think we need a larger data set to make this determination, since mmap is always a good fit, if the data set fits entirely into your page cache (which I think this data set might do).

**Comment by easyice** [comment]
the Elasticsearch server is linux:

````
 uname -r
4.19.117.bsk.4-amd64
````

````
lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.13 (stretch)
Release:	9.13
Codename:	stretch
````

I understand the main reason is nio is thread safe:
in sun.nio.ch.FileChannelImpl#readInternal

````
    private int readInternal(ByteBuffer dst, long position) throws IOException {
        try {
            beginBlocking();
            ti = threads.add();
            ...
        } finally {
            threads.remove(ti);
        }
    }
````
in the jstack output, most block is waiting on **threads.remove(ti);**  or  **threads.add();**

**Comment by henningandersen** [comment]
Sorry for the delay here. A few more questions:

1. This looks like a 96 core server, is that correct?
2. I assume the reason you are looking into this is that you have a real-world example where this could be relevant. Can you explain a bit more on the case where this would help? What other options did you explore?
3. There is a risk that focusing on `add` and `remove` is wrong due to safepoint biasing. Can you produce async-profiler or JFR reports to verify that this is not the case?

By increasing the clients number from 8 to 48 you may be exposing a contention issue within the JDK, but changing from nio to mmap for the file seems like a workaround more than a solution in this case. The rally-test could be improved here to pick from a number of different countries and it seems likely that that would not expose the problem. I am uncertain if we are optimizing for a real-world problem or a synthetic benchmark here, hence my question 2 above.

**Comment by easyice** [comment]
@henningandersen Thank you for reply.
1. Yes, the server has 96 core with 1TB RAM, we start 2 elasticsearch nodes on every server.
2. This issue occurs in benchmark environments, and it's not obvious in real-world cluster

The pr is not representative,i thinks it is can be close

**Comment by henningandersen** [comment]
@easyice thanks for coming back to us on this. I want to add that if you do run two Elasticsearch nodes on the same host you should tell Elasticsearch how many cores it is supposed to use. The best way to do that is to add `-XX:ActiveProcessorCount=48` (with 48 being half your node's core count since you have 2 nodes on the host) in a separate jvm options file.

I will go ahead and close this PR.

**Pull request closed without merging**
