### PR TITLE
Removing redundant method in server org.elasticsearch.common.inject.internal.Strings

### PR DESCRIPTION
**Pull request by PDTCCLF**
This is my attempt to remove redundancy in server org.elasticsearch.common.inject.internal.Strings. Given the fact server org.elasticsearch.common.Strings already has a method to capitalize characters, an import should do the same as creating a new method in the previous code. It is a pull request to solve some parts of issue #87610.

### CODE REVIEW

**Comment by rjernst** [comment]
Note that everything under o.e.common.inject should generally be left alone. This is a vendored version of Guice from a decade ago: making changes to it is something we try to avoid.

**Comment by PDTCCLF** [comment]
> Hi @PDTCCLF, it appears that the Strings.capitalize method from the inject.internal package is in use at the moment in `TypeConverterBindingProcessor`. This use would first need to be refactored and then it appears that the whole class can be removed.

I understand. Thanks for pointing me in the right direction.

**Comment by PDTCCLF** [comment]
> Note that everything under o.e.common.inject should generally be left alone. This is a vendored version of Guice from a decade ago: making changes to it is something we try to avoid.

Ok. I guess it is better to close this PR, then?

**Comment by rjernst** [comment]
> I guess it is better to close this PR, then?

Yes, I think so. Thanks for understanding!

**Pull request closed without merging**
