### PR TITLE
ESQL: Add support for TEXT fields in comparison operators and SORT

### PR DESCRIPTION
**Pull request by luigidellaquila**
This fix adds support for TEXT fields in comparison operators (`==`, `!=`, `>`, `>=` etc., including LIKE and RLIKE) and in SORT command.

The fix consists in passing one more parameter to `BinaryComparison`, `Order` and `RegexMatch` constructors (and all the subclasses) to define whether the instance should resolve on TEXT fields (for ESQL) or not (for SQL and EQL).

Operators pushdown (both for filtering and sorting) is enabled only if the property also declares an [exact multi-field](https://www.elastic.co/guide/en/elasticsearch/reference/current/multi-fields.html) that can be used as a fallback, otherwise the optimization gets skipped and the operation is executed in-line.

### CODE REVIEW

**Review by csoulios — APPROVED** [review]
LGTM

**Review by costin — COMMENTED** [review]
I think we'd have to extend the QL operators to incorporate the ESQL particularities, such as operating on blocks (BytesRef, EvalMapper, etc) instead of regular Java objects and dealing with the extended types such as unsigned_long.
Support for TEXT is border-line asking for a refactoring, however what tips the balance on the side is replacing the `BinaryComparisonOperation` enum which is passed for doing the actual comparisons.

To keep the optimization rules working, either the rules would have to updated to use `replaceChildren` method or have a specialized cloning method similar to `Attribute.with` so keep the ESQL operators in place (and not change them into QL operators).

@bpintea In terms of math operations (thinking of underflow/overflow/addExact) we had to branch out - how does this translate to comparisons (think comparing a small in to an unsigned long; without special handling it would return the incorrect response due to overlow: e.g. Long.compareUnsigned vs Long.compareTo()`

**Comment by luigidellaquila** [comment]
Thanks for your feedback @costin 

> I think we'd have to extend the QL operators to incorporate the ESQL particularities

👍 I'll try this approach. I didn't have a strong preference since the beginning TBH, I went for the flag just to avoid rewriting optimization rules, but it also makes sense to extend.
My feeling is that, in the long run, this dependency from QL could create more friction than expected. Wondering if at some point it will be more convenient to just decouple the two modules and copy the QL components we need, so that we can modify them without trouble.

> To keep the optimization rules working, either the rules would have to updated to use replaceChildren method or have a specialized cloning method similar to Attribute.with so keep the ESQL operators in place (and not change them into QL operators).

I'm afraid I'll have to duplicate a few optimization rules, because in some cases comparison operators are instantiated to replace other components (eg. replacing a LIKE without wildcards with an EQUALS), so overriding `with` and `replaceChildren` won't be enough

**Comment by bpintea** [comment]
> @bpintea In terms of math operations (thinking of underflow/overflow/addExact) we had to branch out - how does this translate to comparisons

We started with not using the QL implementations in the first place, so that was easier. But thinking of how it would have been should we have used them, yes, we'd have had to branch quite a bit, mostly b/c SQL/Painless make use of BigInteger to wrap ULs, while ES|QL does mostly without. So comparison would be as tricky, indeed; maybe to the point that it might make sense to keep them separated.

**Comment by luigidellaquila** [comment]
Closing, replaced by #98528

**Pull request closed without merging**
