### PR TITLE
Don't fallback to anonymous for tokens/apikeys

### LINKED ISSUE #50171: Don't fallback to anonymous user when anonymous access is enabled for invalid access token/api key
Currently, when anonymous access is enabled, a request with an invalid/expired/wrong access token or an API Key would fallback to being authenticated as the anonymous user, as if the request wouldn't contain any Authorization header. This might be a confusing behavior for users and we should be explicit in our responses about treating no credentials and wrong credentials differently, even when anonymous access is enabled.

### PR DESCRIPTION
**Pull request by jkakavas**
This commit changes our behavior so that when we receive a
request with an invalid/expired/wrong access token or API Key
we do not fallback to authenticating as the anonymous user even if
anonymous access is enabled for Elasticsearch.

Resolves:  #50171

### CODE REVIEW

**Comment by jkakavas** [comment]
@polyfractal not sure if this was actually you or a bot :robot: , but this is a bug fix and still targets 7.6.0 assuming it is merged in time to be included.

**Comment by tvernum** [comment]
@jkakavas We bulk move every unmerged PR out of a release when it the branch is cut.
It's up to the PR author to relabel back again if needed (the auto update doesn't know whether it should go to the next minor, the next patch, or be marked as a blocker for the current minor).

**Comment by jkakavas** [comment]
> the auto update doesn't know whether it should go to the next minor, the next patch, or be marked as a blocker for the current minor

Makes sense:) I had a suspicion hence the

> not sure if this was actually you or a bot

but I thought we run all our bots as @@elasticmachine.  TIL

**Comment by tvernum** [comment]
It's not a bot, just a script.

**Review by tvernum — APPROVED** [review]
LGTM

**Pull request merged**
