### PR TITLE
Updating assorted integration tests to use BulkProcessor2 instead of BulkProcessor

### PR DESCRIPTION
**Pull request by masseyke**
In https://github.com/elastic/elasticsearch/pull/91238 we rewrote BulkProcessor to avoid deadlock that had been seen in the IlmHistoryStore. At some point we will remove BulkProcessor altogether. This PR ports a couple of integration tests that were using BulkProcesor over to BulkProcessor2.

### CODE REVIEW

**Comment by masseyke** [comment]
@elasticmachine run elasticsearch-ci/eql-correctness

**Comment by masseyke** [comment]
@elasticmachine run elasticsearch-ci/part-2

**Review by dakrone — APPROVED** [review]
LGTM

**Comment by masseyke** [comment]
@elasticmachine update branch

**Comment by masseyke** [comment]
@elasticmachine run elasticsearch-ci/packaging-tests-unix-sample

**Comment by masseyke** [comment]
@elasticmchine run elasticsearch-ci/packaging-tests-windows-sample

**Comment by masseyke** [comment]
@elasticmachine update branch

**Comment by masseyke** [comment]
@elasticmachine update branch

**Pull request merged**
