### PR TITLE
Add runtimeJavaDetails property in BuildParams

### PR DESCRIPTION
**Pull request by jkakavas**
Relates to #61857

### CODE REVIEW

**Review by rjernst — COMMENTED** [review]
Can you also add this to the printout of the version in global build info?

**Comment by jkakavas** [comment]
It's already there @rjernst  :https://github.com/jkakavas/elasticsearch/blob/6c027bdd5a6af7ce1ee7d996f37c391684c3ea03/buildSrc/src/main/java/org/elasticsearch/gradle/info/GlobalBuildInfoPlugin.java#L157

**Comment by jkakavas** [comment]
@elasticmachine update branch

**Comment by rjernst** [comment]
Oh darn, I thought at first this was the additional information we had been wanting (eg build number).

**Review by rjernst — APPROVED** [review]
LGTM

**Review by mark-vieira — APPROVED** [review]
👍

**Pull request merged**
