### PR TITLE
Use separate search execution context for each pipeline

### PR DESCRIPTION
**Pull request by dnhatn**
Synthetic source doesn't seem to work correctly with either inter-segment or intra-segment parallelism. Neither of these parallelisms were available when the synthetic source was developed. The new test fails with the doc or segment data_partitioning. While we are working on a proper fix, this PR introduces a workaround by creating a separate search execution context for each execution pipeline, restoring the sequential execution invariants. I believe that the overhead added by this workaround is minimal.

### CODE REVIEW

**Comment by dnhatn** [comment]
@javanna We might have the same issue with the _search API.

**Comment by dnhatn** [comment]
@nik9000 I can work on the fix, but please feel free to proceed if you prefer. You're way more familiar with the synthetic source than I am.

**Review by nik9000 — APPROVED** [review]
Fair enough. That'll unstick. I don't know what's going on in synthetic source land but I can take a look soon.

**Comment by javanna** [comment]
Thanks for the heads up @dnhatn !

**Comment by dnhatn** [comment]
@nik9000 @javanna Thank you!

**Pull request merged**
