### PR TITLE
Bump major version for feature migration system indices

### PR DESCRIPTION
**Pull request by jfreden**
This PR is in preparation for the ES 9 release. Lucene has BWC with indices created on one version prior to the current version (ES 9.0 is Lucene 10, so can support Lucene 9). To ensure that a system index created on an ES 7 (Lucene 8) can actually run on ES 9 (Lucene 10), the system indices need to be reindexed.

To reindex a system index for ES 9, the cluster need to be ugraded to `8.latest` and then run the [Kibana Upgrade Assistant](https://www.elastic.co/guide/en/kibana/current/upgrade-assistant.html) or use the [Feature MIgration APIs](https://www.elastic.co/guide/en/elasticsearch/reference/current/feature-migration-api.html) directly. The feature migration APIs enable you to see what features require changes, initiate the automatic migration process, and check migration status.

For system indices to show up as "needs upgrade" in the `GET /_migration/system_features` the minimum index and stack version need to be bumped from 7 to 8.  The suffix added to migrated indices also need to use version 9.

### CODE REVIEW

**Comment by jfreden** [comment]
These changes were made to be able to test the migration of the security index. 

The assumption is that 8.17 will be released as 8.last at the same time as 9.0. 

Kibana will need to add the `xpack.upgrade_assistant.featureSet.migrateSystemIndices: true` to enable this feature in the Kibana UI.

**Comment by jfreden** [comment]
To manually test this change to migrate the security system index, I've run this flow (Use kibana setting `xpack.upgrade_assistant.featureSet.migrateSystemIndices: true` to make the system index migration show up in Kibana):
1. Create ES 6 cluster and trigger security index creation
Observe index name: `.security-6` with alias: `.security`
2. Upgrade to ES `7.latest`
3. Run upgrade assistant and observe index name: 
`.security-6-reindexed-for-8` with aliases: `.security-6`, `.security`
4. Upgrade ES to `8.latest`
5. Run upgrade assistant and observe index names 
`.security-6-reindexed-for-8-reindexed-for-9` with aliases: `.security-6-reindexed-for-8`, `.security-6`, `.security`.

**Comment by ldematte** [comment]
> The assumption is that 8.17 will be released as 8.last at the same time as 9.0.

Actually that would be 8.18, but other than that I think the rest of the explanation is good.

**Review by AthenaEryma — APPROVED** [review]
LGTM, apologies for the delay.

At some point we might need to look for the previous prefix to prevent stacking up indexing names like `.security-reindexed-for-8-reindexed-for-9`, but I think we can cross that bridge if we come to it and decide it's worth doing.

**Comment by jfreden** [comment]
Closed this in favour of: https://github.com/elastic/elasticsearch/pull/116383

**Pull request closed without merging**
