### PR TITLE
Unmute Lintian test again

### LINKED ISSUE #88090: [CI] DebMetadataTests test05CheckLintian failing on libtorch_cpu.so
### CI Link

https://gradle-enterprise.elastic.co/s/2bezdlvc2ylgg/tests/:qa:os:destructiveDistroTest.default-deb/org.elasticsearch.packaging.test.DebMetadataTests/test05CheckLintian?top-execution=1

### Repro line

[bash, -c, lintian  /var/lib/jenkins/workspace/elastic+elasticsearch+pull-request+packaging-tests-unix-sample/PACKAGING_TASK/destructiveDistroTest.packages/os/ubuntu-20.04-packaging/distribution/packages/deb/build/distributions/elasticsearch-8.4.0-SNAPSHOT-amd64.deb] 

### Does it reproduce?

Didn't try

### Applicable branches

master

### Failure history

_No response_

### Failure excerpt

I think this issue is similar to https://github.com/elastic/elasticsearch/issues/87632, except this time lintian is complaining about libtorch_cpu.so and libstdc++.so.6.

### LINKED ISSUE #88252: [CI] DebMetadataTests test05CheckLintian failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/qhcumlpvkjrag/tests/:qa:os:destructiveDistroTest.default-deb/org.elasticsearch.packaging.test.DebMetadataTests/test05CheckLintian

**Reproduction line:**
`null`

**Applicable branches:**
master

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.packaging.test.DebMetadataTests&tests.test=test05CheckLintian

**Failure excerpt:**
```
org.elasticsearch.packaging.util.Shell$ShellException: Command was not successful: [bash -c lintian --fail-on-warnings /var/lib/jenkins/workspace/elastic+elasticsearch+main+multijob+packaging-tests-unix/os/debian-10-packaging/distribution/packages/deb/build/distributions/elasticsearch-8.4.0-SNAPSHOT-amd64.deb]
   result: exitCode = [1] stdout = [W: elasticsearch: hardening-no-pie usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/bin/autodetect
W: elasticsearch: hardening-no-pie usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/bin/categorize
W: elasticsearch: hardening-no-pie usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/bin/controller
W: elasticsearch: hardening-no-pie usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/bin/data_frame_analyzer
W: elasticsearch: hardening-no-pie usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/bin/normalize
W: elasticsearch: hardening-no-pie usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/bin/pytorch_inference
N: 354 tags overridden (191 errors, 121 warnings, 42 info); 5 unused overrides] stderr = [warning: the authors of lintian do not recommend running it with root privileges!
warning: --fail-on-warnings is deprecated]

  at __randomizedtesting.SeedInfo.seed([BB3B9D8B6B37758A:7BC50167D1431031]:0)
  at org.elasticsearch.packaging.util.Shell.runScript(Shell.java:143)
  at org.elasticsearch.packaging.util.Shell.run(Shell.java:73)
  at org.elasticsearch.packaging.test.DebMetadataTests.test05CheckLintian(DebMetadataTests.java:44)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:577)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

```

### PR DESCRIPTION
**Pull request by droberts195**
The most recent problem should be fixed by elastic/ml-cpp#2346

Fixes #88090
Fixes #88252

### CODE REVIEW

**Comment by droberts195** [comment]
The pattern of failures is a bit weird, with it working fine on Ubuntu 18.04 and 22.04 but not 20.04.  Also the nature of the failures suggests the previous C++ build was used on the platforms where it failed.

Screenshot 2022-07-06 at 13 50 45

I am going to try re-running the packaging tests in the hope that the problem is the 2 hour cache period specified in https://github.com/elastic/elasticsearch/blob/8e0137ef279ed00f74612d7c763e735bc09c003b/x-pack/plugin/ml/build.gradle#L37

**Comment by droberts195** [comment]
Jenkins run elasticsearch-ci/packaging-tests-unix

**Review by edsavage — APPROVED** [review]
LGTM as long as CI passes

**Comment by droberts195** [comment]
> hope that the problem is the 2 hour cache period

The Lintian tests have passed on all platforms on the later attempt, so I think it was just an older C++ download being cached that caused the failures first time around.

**Pull request merged**
