### PR TITLE
Add forcemerge as an internal API for serverless

### PR DESCRIPTION
**Pull request by inqueue**
This commit adds the force merge API to the internal scope for serverless. forcemerge is necessary for serverless benchmarks for tracking changes in search performance due to ongoing development.

### CODE REVIEW

**Review by masseyke — APPROVED** [review]
LGTM for internal use -- might want to get an opinion from @elastic/es-distributed.

**Comment by inqueue** [comment]
@elasticsearchmachine update branch

**Comment by pxsalehi** [comment]
We do seem to have something ongoing for this: https://github.com/elastic/elasticsearch/pull/97927

**Comment by inqueue** [comment]
> We do seem to have something ongoing for this: #97927

Thanks, @pxsalehi, I missed it. This PR is a dupe, so closing.

**Pull request closed without merging**
