### PR TITLE
Add geo_shape support for the geo_centroid aggregation

### PR DESCRIPTION
**Pull request by talevy**
this commit leverages the new geo_shape doc values
to register a new geo_centroid aggregator that works
on geo_shape field.

### CODE REVIEW

**Comment by talevy** [comment]
test this please

**Comment by talevy** [comment]
Sorry, need to finalize the licensing section before review

**Review by iverase — APPROVED** [review]
LGTM

**Comment by talevy** [comment]
thanks Ignacio!

**Pull request merged**
