### PR TITLE
fixed typo

### PR DESCRIPTION
**Pull request by mohammedbalila**

### CODE REVIEW

**Review by nik9000 — APPROVED** [review]

**Comment by nik9000** [comment]
@mustafabalila could you sign the [cla](https://www.elastic.co/contributor-agreement)? We need it for all contributions, even a typo.

**Comment by mustafabalila** [comment]
Done

**Comment by nik9000** [comment]
> Done

Awesome! The bot is happy.

**Comment by nik9000** [comment]
@elasticmachine, ok to test

**Pull request merged**
