### PR TITLE
Fix some top_metrics tests

### LINKED ISSUE #52409: [CI] XPackRestIT "analytics/top_metrics/sort by string script fails" failure
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-unix-compatibility/os=oraclelinux-7&&immutable/574/console

```
02:31:08 org.elasticsearch.xpack.test.rest.XPackRestIT > test {p0=analytics/top_metrics/sort by string script fails} FAILED
02:31:08     java.lang.AssertionError: Failure at [analytics/top_metrics:247]: expected [400] status code but api [search] returned [200 OK] [{"took":8,"timed_out":false,"_shards":{"total":2,"successful":1,"skipped":0,"failed":1,"failures":[{"shard":0,"index":"test","node":"gtl65pvDSVSvSoO1viU9Lg","reason":{"type":"illegal_argument_exception","reason":"error building sort for [_script]: script sorting only supported on [numeric] scripts but was [string]"}}]},"hits":{"total":{"value":0,"relation":"eq"},"max_score":null,"hits":[]},"aggregations":{"tm":{"top":[]}}}]
02:31:08         at __randomizedtesting.SeedInfo.seed([6ECA51725C63A9D5:E69E6EA8F29FC42D]:0)
02:31:08         at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:405)
02:31:08         at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:382)
02:31:08         at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
```

Couldn't repro, though :-(.

### LINKED ISSUE #52418: [CI] XPackRestIT.test {p0=analytics/top_metrics/sort by double field}"
This doesn't reproduce for me.

```
REPRODUCE WITH: ./gradlew ':x-pack:plugin:integTestRunner' --tests "org.elasticsearch.xpack.test.rest.XPackRestIT.test {p0=analytics/top_metrics/sort by double field}" \
  -Dtests.seed=8F62667C97A80AFD \
  -Dtests.security.manager=true \
  -Dtests.locale=ca-ES \
  -Dtests.timezone=America/Indiana/Winamac \
  -Dcompiler.java=13 \
  -Dtests.rest.blacklist=getting_started/10_monitor_cluster_health/*

REPRODUCE WITH: ./gradlew ':x-pack:plugin:integTestRunner' --tests "org.elasticsearch.xpack.test.rest.XPackRestIT.test {p0=analytics/top_metrics/sort by double field}" \
  -Dtests.seed=8F62667C97A80AFD \
  -Dtests.security.manager=true \
  -Dtests.locale=ca-ES \
  -Dtests.timezone=America/Indiana/Winamac \
  -Dcompiler.java=13 \
  -Dtests.rest.blacklist=getting_started/10_monitor_cluster_health/*
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_RUNTIME_JAVA=openjdk14,nodes=general-purpose/516/console
[7.6.1] https://gradle-enterprise.elastic.co/s/55iyxj2344cy4
[7.7.0] https://gradle-enterprise.elastic.co/s/25tx76dtr3x5a 
[7.6.1] https://gradle-enterprise.elastic.co/s/66qupjuezmduk
[7.7.0] https://gradle-enterprise.elastic.co/s/qse4aijncstnk
https://gradle-enterprise.elastic.co/s/un6vbajxobhja

```
java.lang.AssertionError: Failure at [analytics/top_metrics:91]: aggregations.tm.top.0.metrics.v didn't match expected value:
aggregations.tm.top.0.metrics.v: expected Double [2.718280076980591] but was Double [2.0]

	at __randomizedtesting.SeedInfo.seed([8F62667C97A80AFD:73659A639546705]:0)
	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:405)
	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:382)
```

### PR DESCRIPTION
**Pull request by nik9000**
These tests didn't work properly when run against multi-shard indices.
The `_score` based sorting test expects fairly specific scores which
isn't going to happen with multiple shards so this disables multiple
shards for that test. The other tests were failing due to a fairly
sneaky race condition around `_bulk` and type inference. This fixes them
by always sending metric values as floating point numbers so
Elasticsearch always infers them to be doubles.

Closes #52418 
Closes #52409

### CODE REVIEW

**Comment by nik9000** [comment]
I believe I didn't cover one last case. That doesn't always fail, but will rarely. I'm digging.

**Review by not-napoleon — APPROVED** [review]
This looks good for fixing the tests.  Is the race condition in `_bulk` something that can happen in production? Do we need to address that somehow in the agg itself?

**Review by polyfractal — APPROVED** [review]
:+1: from me too.

Instead of using `default_shards`, we could also explicitly create the index in the setup, which would take care of both the shard count issue and the dynamic mapping issue.

**Comment by nik9000** [comment]
> This looks good for fixing the tests. Is the race condition in `_bulk` something that can happen in production? Do we need to address that somehow in the agg itself?

It can totally happen in production. It is sort of the price you pay for Elasticsearch's schema inference.

**Pull request merged**
