### PR TITLE
Fix connect concurrency, can cause connection nodes to close

### PR DESCRIPTION
**Pull request by kimchy**
Looking at the connect code, if 2 threads at the same time try and connect to a node, and both enter sequentially the connectLock code block, the second one would try and put the connection in the map, and close the replaced channels, which will cause the existing connection to close as well (since it removes the node from the connectedNodes map)
To fix this, simply make sure we properly check the existence of the connection within the connectionLock block, so there won't be concurrent connections going on.
While doing this, also went over all the mutation code that handles disconnections, and made sure they are properly done only within a connection lock.

### CODE REVIEW

**Comment by andreasch** [comment]
Would this issue cause intermittent exceptions with the following messages?

org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes were available 
or
org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available

We are running ES 1.3.2 and seeing intermittent cases where we get these 2 exceptions on the JVMs that run the transport client even though there is no load on the cluster or any sort of networking issues between the JVM running the transport client and cluster.

**Comment by bleskes** [comment]
@andreasch I think it might, if you only have one node configured in your transport client? also if you turn on debugging logging it should see some complaints about node not connected.

**Comment by andreasch** [comment]
We do only have one node in our transport client (points to a VIP/load balancer).

"Node not connected" seems to be the root exception message for all of our exceptions with the message "org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available"

**Comment by bleskes** [comment]
Ok. sounds plausible then. But as these things go - it's hard to be sure..

**Pull request closed without merging**
