### PR TITLE
INGEST: Add Configuration Except. Data to Metdata

### LINKED ISSUE #27728: Add metadata to configuration exceptions
... instead of using headers.

Similarly to #27724, there is some exception metadata that is included in headers rather than using `addMetadata()`, introduced in #19318.

https://github.com/elastic/elasticsearch/blob/2e36f190515b7b3a79a7b1cf380ef8015ffaefae/core/src/main/java/org/elasticsearch/ingest/ConfigurationUtils.java#L346-L354

Under the umbrella of #27672, it'd be preferable to use `addMetadata()` to reduce the number of ways that clients have to handle errors.

/cc @simonw and @talevy for further opinions.

### PR DESCRIPTION
**Pull request by original-brownbear**
* closes #27728

### CODE REVIEW

**Comment by original-brownbear** [comment]
@talevy can you take a look here? I'm only 80% this is what we're looking for here functionally tbh. :)

**Comment by talevy** [comment]
oh woah, apologies for missing this @original-brownbear. changes look good. I think we should tag this as breaking? Although it is a super esoteric part of the response body, some users may be depending on it

**Review by talevy — APPROVED** [review]
LGTM

**Comment by original-brownbear** [comment]
@talevy No worries, this really was low priority :) + yea makes sense, tagged as breaking.
Merging in `master` since it's been a while since I opened this one and will merge once green :)

**Pull request merged**
