### PR TITLE
Cache doPrivileged action for field factories

### PR DESCRIPTION
**Pull request by rjernst**
Advancing the field factories in LeafDocLookup to the current doc requires running a privileged action. Currently this action is created on the fly as a lambda. That could cause heavy object creation in tight scripting loops. This commit adds a wrapper around the field factories, so that the privileged action can be attached and used when advancing to the current docid.

### CODE REVIEW

**Comment by rjernst** [comment]
@iverase I implemented a wrapper to cache the privileged action, much like you suggested in https://github.com/elastic/elasticsearch/pull/93711#issuecomment-1440381876.

/cc @ChrisHegarty

**Review by jdconrad — APPROVED** [review]
LGTM

**Review by ChrisHegarty — APPROVED** [review]
LGTM

**Comment by iverase** [comment]
If @ChrisHegarty is happy, I am happy.

**Pull request merged**
