### PR TITLE
[HLRC] Documentation examples cleanup

### PR DESCRIPTION
**Pull request by lipsill**
While digging into something else I noticed that there are several WARN messages in the high-level REST client integration tests. And most of them are caused by examples in the documentation that use deprecated functionality (i.e. specifying `type` in `_search` requests). While the high level rest client should support the 'deprecated' functionality, I think that the client's documentation must not cover such examples.

This PR modifies the examples so that there are no deprecation warnings. The changes are grouped in separate commits, so it is easy to pick and choose the changes that should be adopted.

### CODE REVIEW

**Comment by javanna** [comment]
this may be outdated with recent changes, @nik9000 can you have a look please?

**Comment by nik9000** [comment]
I'm not following along with the types removal stuff super closely which is the bulk of this. @jtibshirani will probably know it better so I'm pinging her.

@original-brownbear is responsible for the ctx thing and probably should look at this too.

**Comment by jtibshirani** [comment]
The changes around `SearchRequest#types` look good to me, thanks @lipsill for cleaning this up.

**Comment by nik9000** [comment]
I've merged master to fix the merge conflict that I introduced. I tested it locally. I've reached out to @original-brownbear to talk about `ctx` thing but regardless of how that goes this change is good. I'm gonna merge it and backport to the 6.x branch.

**Comment by nik9000** [comment]
All merged now! Thanks again @lipsill!

**Comment by lipsill** [comment]
Thanks everybody! Thanks @nik9000 !

**Pull request merged**
