### PR TITLE
[DOCS] SEO changes to the topic title, heading, and toc entry.

### PR DESCRIPTION
**Pull request by debadair**
Experimenting with some changes to make it easier to search and find the security content. 

@AnneB-SEO

### CODE REVIEW

**Comment by lcawl** [comment]
I did some quick searches in case these changes become permanent.  These files in the master branch will also need to be updated with the new URL at that point:
elasticsearch/x-pack/docs/en/security/configuring-es.asciidoc
kibana/docs/setup/install.asciidoc
kibana/docs/setup/production.asciidoc
kibana/x-pack/docs/en/management/watcher-ui/security.asciidoc
kibana/x-pack/docs/en/security/index.asciidoc
logstash/docs/static/deploying.asciidoc
libbeat/docs/https.asciidoc
libbeat/docs/security/securing-beats.asciidoc
I just looked at these core repos where I know we have security content--there might be a few others. I also haven't done these checks on any other branches, but can do so if this is considered for backporting.

**Review by lcawl — APPROVED** [review]
Per discussions, I'm hoping this will be temporary and not backported. In that case redirects can suffice instead of updating the links in other pages.

**Comment by debadair** [comment]
I'm going to update 6.2 first. I've got the necessary link changes ready to go when we're ready to merge.

**Comment by cbuescher** [comment]
@debadair @lcawl Just going through some stale docs PRs. What are the next steps to get this merged?

**Comment by michaelbaamonde** [comment]
@debadair @lcawl Did you want to move forward with this PR still?

**Comment by rjernst** [comment]
@debadair Is this PR still relevant?

**Comment by debadair** [comment]
Closing. We put this on ice because it was potentially disruptive.

**Pull request closed without merging**
