### PR TITLE
Add a note about upgrading a test/dev cluster with a single master

### PR DESCRIPTION
**Pull request by bleskes**

### CODE REVIEW

**Review by LeeDr — APPROVED** [review]
LGTM

I just found this other doc
https://www."elastic.co/guide/en/elasticsearch/reference/current/modules-node.html

which says;
 "A rolling upgrade, performed without any downtime, also requires at least three master-eligible nodes to avoid the possibility of data loss if a network split occurs while the upgrade is in progress."

But that goes along with the `testing/development environment`.  So I think it's good.

**Comment by LeeDr** [comment]
I approved but my only suggestion is if we could move the "Important" block up higher in the doc to increase the chance that people would actually see it before they start a rolling upgrade.  We should ask @json to review and "View file" in github to see if he thinks he would have seen it at the bottom before proceeding.

**Comment by inqueue** [comment]
> I approved but my only suggestion is if we could move the "Important" block up higher in the doc to increase the chance that people would actually see it before they start a rolling upgrade. We should ask @json to review and "View file" in github to see if he thinks he would have seen it at the bottom before proceeding.

Will check it @LeeDr.

**Comment by bleskes** [comment]
> my only suggestion is if we could move the "Important" block up higher in the doc to increase the chance that people would actually see it before they start a rolling upgrade. 

@LeeDr I see where you're coming from but I'm a bit hesitant to do so. Putting this at the top will distract from other things that are more important. This is really an edge case of already a small deployment (most dev env. will not have dedicated masters nodes)

**Review by debadair — APPROVED** [review]
LGTM

**Pull request merged**
