### PR TITLE
Refresh translog stats after translog trimming in NoOpEngine

### PR DESCRIPTION
**Pull request by tlrx**
This pull request changes `NoOpEngine` so that it refreshes its translog stats once translog is trimmed.

Relates #43156

### CODE REVIEW

**Review by dnhatn — APPROVED** [review]
LGTM

**Review by ywelsch — APPROVED** [review]
LGTM2

**Comment by tlrx** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by tlrx** [comment]
@elasticmachine update branch

**Comment by tlrx** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by tlrx** [comment]
Thanks @dnhatn and @ywelsch

**Pull request merged**
