### PR TITLE
Use ChannelFutureListener in Netty code to reduce capturing lambdas

### PR DESCRIPTION
**Pull request by original-brownbear**
Mainly motivated by simplifying the reference chains for Netty buffers and have easier to analyze heap dumps in some spots but also a small performance win in and of itself.

### CODE REVIEW

**Review by DaveCTurner — COMMENTED** [review]
LGTM but I fear we'll keep making this mistake. Could we forbid the overly-generic `io.netty.channel.ChannelFuture#addListener` and add something to `Netty4Utils` to force the type to be `ChannelFutureListener`?

**Comment by original-brownbear** [comment]
@DaveCTurner 

Thanks for taking a look! 

> io.netty.channel.ChannelFuture#addListener and add something to Netty4Utils to force the type to be ChannelFutureListener?

You mean completely forbidding `addListener` via forbidden APIs and then having a `Netty4Utils.addListener(ChannelPromise, ChannelFutureListener)` or so and only use that? I could do that, but that makes the code one step harder to read and we have a couple of spots where the added listener doesn't need to know about the channel. To me it's not worth the extra indirection step, but it's "your code" now :) Happy to add that, don't feel strongly about it :)

**Comment by DaveCTurner** [comment]
Yeah that's what I mean, I'd prefer that to those over-subtle casts.

**Comment by original-brownbear** [comment]
@DaveCTurner alrighty done with the forbidden APIs :)

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Comment by original-brownbear** [comment]
Thanks David!

**Pull request merged**
