### PR TITLE
[ML] Catch exceptions during pytorch_inference startup

### PR DESCRIPTION
**Pull request by droberts195**
A couple of test failures (#103808 and #103868) reveal that an exception thrown while connecting to the pytorch_inference process can be uncaught and hence cause the whole node to stop.

This change does not fix the underlying problem of failure to connect to the process that those issues relate to, but it converts the error from one that crashes a whole node to one that just fails the affected model deployment.

### CODE REVIEW

**Review by davidkyle — APPROVED** [review]
LGTM

**Comment by droberts195** [comment]
@elasticsearchmachine run elasticsearch-ci/bwc-snapshots

**Comment by droberts195** [comment]
@elasticsearchmachine run elasticsearch-ci/bwc-snapshots

**Comment by droberts195** [comment]
@elasticsearchmachine run elasticsearch-ci/bwc-snapshots

**Pull request merged**
