### PR TITLE
[DOCS] Change `ctx.payload.hits.total.value` to `ctx.payload.hits.total`

### PR DESCRIPTION
**Pull request by Erni**
`ctx.payload.hits.total.value` is no longer valid. The proper way to get the total hits is `ctx.payload.hits.total`

### CODE REVIEW

**Comment by jrodewig** [comment]
@elasticmachine update branch

**Comment by jrodewig** [comment]
Thanks for opening this @erni. I added a few more instances from our Watcher docs with d8ae78f4c72db41a06883c750c62bd4701e06b40.

**Review by jakelandis — APPROVED** [review]
LGTM. FWIW the total.value is what is required if `rest_total_hits_as_int` is set to false. It defaults to true today, but will likely default to false for 8.0: https://github.com/elastic/elasticsearch/issues/38387 

Also, it turns out that you can't actually store a watch with `rest_total_hits_as_int` is set to false today: https://github.com/elastic/elasticsearch/pull/65988

If/when we implement https://github.com/elastic/elasticsearch/issues/38387  we will need to change this documentation back to using .value ...but I agree for now lets document the default

**Comment by jrodewig** [comment]
Thanks @jakelandis.

**Pull request merged**
