### PR TITLE
[DOCS] Update index privileges doc to include data streams

### PR DESCRIPTION
**Pull request by danhermann**
Updates the documents with the changes made in https://github.com/elastic/elasticsearch/pull/59095

Relates to #53100

### CODE REVIEW

**Comment by danhermann** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by danhermann** [comment]
@elasticmachine run elasticsearch-ci/default-distro

**Review by jrodewig — APPROVED** [review]
LGTM. Thanks!

**Comment by danhermann** [comment]
@elasticmachine update branch

**Comment by danhermann** [comment]
@elasticmachine update branch

**Pull request merged**
