### PR TITLE
Update randomizedrunner to 2.7.4

### PR DESCRIPTION
**Pull request by racevedoo**
Updates randomizedrunner from 2.7.1 to 2.7.4, which includes some fixes related to race conditions/deadlocks. Release notes at https://github.com/randomizedtesting/randomizedtesting/releases

### CODE REVIEW

**Comment by pugnascotia** [comment]
@elasticmachine test this please.

**Comment by jasontedor** [comment]
@elasticmachine update branch

**Comment by jasontedor** [comment]
@elasticmachine test this please

**Comment by pugnascotia** [comment]
Thanks @racevedoo!

**Pull request merged**
