### PR TITLE
Fix race conditions in file settings service tests

### LINKED ISSUE #115280: [CI] FileSettingsServiceTests testProcessFileChanges failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #4706 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/aetm2famyyqbw)
- [elasticsearch-intake #12113 / part1](https://gradle-enterprise.elastic.co/s/phni7wjudjos6)

**Reproduction Line:**
```
gradlew ":server:test" --tests "org.elasticsearch.reservedstate.service.FileSettingsServiceTests.testProcessFileChanges" -Dtests.seed=E175BB524F09E5B4 -Dtests.locale=ky -Dtests.timezone=CNT -Druntime.java=23
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.reservedstate.service.FileSettingsServiceTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testProcessFileChanges),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.io.UncheckedIOException: could not write file [C:\bk\server\build\testrun\test\temp\org.elasticsearch.reservedstate.service.FileSettingsServiceTests_E175BB524F09E5B4-001\tempDir-018\config\operator\settings.json]
```

**Issue Reasons:**
- [main] 2 failures in test testProcessFileChanges (6.3% fail rate in 32 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by n1v0lg**
This test resolves two race conditions in `FileSettingsServiceTests#testProcessFileChanges`:

1. The test used `writeTestFile` to update the settings.json file. It did so in multiple steps: first it created a temp file in the operator directory, then moved that file to replace the existing settings.json file. The first step (creating the temp file) triggered the watcher thread in the file settings service to access the settings.json file to check for changes. When this access happened concurrently with the `move` call inside `writeTestFile` the test would throw on a Windows file-system (mocked or real), since you can't move a file while it's open. To fix this, the PR changes `writeTestFile` to creating a temp file elsewhere and simplifies the method. Instead of relying on this method (and multiple file operations) to update the file, the PR instead simply "touches" the settings file with a timestamp update to trigger file processing (more details also in this [comment](https://github.com/elastic/elasticsearch/issues/115280#issuecomment-2457402953)). 
2. The test awaited latches that would count down when `ReservedClusterStateService#process` was invoked. However, at this point in the file settings processing flow, the settings.json file is still open and would therefore likewise block subsequent writes that fall into the small window of the file still being open. This PR instead adds latches based on file-changed listeners which are reliably invoked _after_ the file is closed.  

Resolves: https://github.com/elastic/elasticsearch/issues/115280

### CODE REVIEW

**Comment by n1v0lg** [comment]
@elasticmachine update branch

**Comment by n1v0lg** [comment]
@elasticmachine update branch

**Comment by n1v0lg** [comment]
@elasticmachine update branch

**Review by jfreden — APPROVED** [review]
Nice detective work! I think it makes sense to use a lightweight update of the file metadata to trigger a changed event. This also turned out to be a nice cleanup 💯 

LGTM!

**Comment by n1v0lg** [comment]
@elasticmachine update branch

**Comment by n1v0lg** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.x|[](https://github.com/elastic/elasticsearch/pull/116402)|
|✅|8.16|[](https://github.com/elastic/elasticsearch/pull/116403)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

**Pull request merged**
