### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by kdelchev**

### CODE REVIEW

**Comment by nik9000** [comment]
Change looks good to me. If you sign the [CLA](https://www.elastic.co/contributor-agreement), wait 5 minutes or so, and then make a comment on this issue then the failing check should clear.

The CLA is required for all changes, even single letter ones.

**Comment by kdelchev** [comment]
Signed for CLA, having a :beer: (e.g. wait 5 min), then put this comment. Cheers!

**Comment by nik9000** [comment]
Thanks! I'm finally getting around to merging this. Flying is hard..... Anyway! I'll get this into all the branches that it matters!

**Comment by nik9000** [comment]
2.0: 60d886a0a191f7461c1d419aae6a89229b01d01f
2.1: 83de2dd3820f41b82e31005c5b96ba653807278e
2.2: 5765d27955b7a648623fd5bb45a8cd5966f8030b
2.x: 50e8e6063f23940f2e5c3a452ee9e03cd1bcfdff
master: b451d5eb07b09ea04daef738bbfa6100514e8409

**Comment by nik9000** [comment]
That might have been overkill to go back to 2.0 but it is a documentation fix so it'll show up on the docs for everyone soon-ish.

**Comment by nik9000** [comment]
All done! Thanks @kdelchev !

**Pull request merged**
