### PR TITLE
[DOCS] Fixes indentation in inference processor code snippet

### PR DESCRIPTION
**Pull request by szabosteve**
This PR fixes a wrongly indented line in a code snippet.

Preview available here: http://elasticsearch_51252.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/inference-processor.html

### CODE REVIEW

**Comment by joshdevins** [comment]
Something looks off still. I think the second last } is off. It looks like it mixes 2 and 4-character indents as well, probably because of a mix of tabs and spaces. It should be:

```
{
  "inference": {
    "model_id": "flight_delay_regression-1571767128603",
    "target_field": "FlightDelayMin_prediction_infer",
    "field_mappings": {},
    "inference_config": { "regression": {} },
    "model_info_field": "ml"
  }
}
```

I also notice the other two snippets are not formatted correctly on the page, mostly because of the same problems and the quote marks are the wrong character (not ASCII "). They should be:

`inference_config` example. It should also now be called just `inference`:

```
{
  "inference": {
    "regression": {
      "results_field": "my_regression"
    }
  }
}
```

And

```
{
  "inference": {
    "classification": {
      "num_top_classes": 2,
      "results_field": "prediction",
      "top_classes_results_field": "probabilities"
    }
  }
}
```

**Comment by szabosteve** [comment]
@joshdevins Thanks for the feedback. I amended the snippets accordingly.

**Comment by joshdevins** [comment]
LGTM, all the JSON highlighting now works too! 🎉

**Comment by szabosteve** [comment]
**Backport commits:**
7.x: 30d1587
7.6: e3f6331

**Pull request merged**
