### PR TITLE
Supported Azure Storage account types

### LINKED ISSUE #20765: Azure Cloud plugin does not work against Premium Locally Redundant Storage
**Elasticsearch version**: 2.4.0

**Plugins installed**: []

**JVM version**:

**OS version**: Ubuntu 14.04.4-LTS

**Description of the problem including expected versus actual behavior**:

The azure cloud plugin does not appear to work against Premium Locally Redundant Storage (`Premium_LRS`). Error returned when attempting to create a snapshot repository against Premium_LRS:

``` json
{
   "error": {
      "root_cause": [
         {
            "type": "repository_verification_exception",
            "reason": "[my_backup1] [HuV5ruyRQr6NNtEj46-SMQ, 'RepositoryVerificationException[[my_backup1] a file written by master to the store [elasticsearch-snapshots] cannot be accessed on the node [{master-0}{HuV5ruyRQr6NNtEj46-SMQ}{10.0.0.6}{10.0.0.6:9300}{data=false, master=true}]. This might indicate that the store [elasticsearch-snapshots] is not shared between this node and the master node or that permissions on the store don't allow reading files written by the master node]'], [Gg5kwiRFT728YRHB5bAHlA, 'RemoteTransportException[[data-2][10.0.0.9:9300][internal:admin/repository/verify]]; nested: RepositoryVerificationException[[my_backup1] a file written by master to the store [elasticsearch-snapshots] cannot be accessed on the node [{data-2}{Gg5kwiRFT728YRHB5bAHlA}{10.0.0.9}{10.0.0.9:9300}{master=false}]. This might indicate that the store [elasticsearch-snapshots] is not shared between this node and the master node or that permissions on the store don't allow reading files written by the master node];'], [sX91n37nTVqVJWh_gcGhuQ, 'RemoteTransportException[[data-0][10.0.0.11:9300][internal:admin/repository/verify]]; nested: RepositoryVerificationException[[my_backup1] a file written by master to the store [elasticsearch-snapshots] cannot be accessed on the node [{data-0}{sX91n37nTVqVJWh_gcGhuQ}{10.0.0.11}{10.0.0.11:9300}{master=false}]. This might indicate that the store [elasticsearch-snapshots] is not shared between this node and the master node or that permissions on the store don't allow reading files written by the master node];'], [tc_dxu1WR02fvNwBELzkfg, 'RemoteTransportException[[data-1][10.0.0.10:9300][internal:admin/repository/verify]]; nested: RepositoryVerificationException[[my_backup1] a file written by master to the store [elasticsearch-snapshots] cannot be accessed on the node [{data-1}{tc_dxu1WR02fvNwBELzkfg}{10.0.0.10}{10.0.0.10:9300}{master=false}]. This might indicate that the store [elasticsearch-snapshots] is not shared between this node and the master node or that permissions on the store don't allow reading files written by the master node];'], [xoENYGRRT9-AlFyw_jEqMQ, 'RemoteTransportException[[master-1][10.0.0.7:9300][internal:admin/repository/verify]]; nested: RepositoryVerificationException[[my_backup1] a file written by master to the store [elasticsearch-snapshots] cannot be accessed on the node [{master-1}{xoENYGRRT9-AlFyw_jEqMQ}{10.0.0.7}{10.0.0.7:9300}{data=false, master=true}]. This might indicate that the store [elasticsearch-snapshots] is not shared between this node and the master node or that permissions on the store don't allow reading files written by the master node];'], [ILooIOS6SpeuWOPAn91YVA, 'RemoteTransportException[[master-2][10.0.0.5:9300][internal:admin/repository/verify]]; nested: RepositoryVerificationException[[my_backup1] a file written by master to the store [elasticsearch-snapshots] cannot be accessed on the node [{master-2}{ILooIOS6SpeuWOPAn91YVA}{10.0.0.5}{10.0.0.5:9300}{data=false, master=true}]. This might indicate that the store [elasticsearch-snapshots] is not shared between this node and the master node or that permissions on the store don't allow reading files written by the master node];']]"
         }
      ],
      "type": "repository_verification_exception",
      "reason": "[my_backup1] [HuV5ruyRQr6NNtEj46-SMQ, 'RepositoryVerificationException[[my_backup1] a file written by master to the store [elasticsearch-snapshots] cannot be accessed on the node [{master-0}{HuV5ruyRQr6NNtEj46-SMQ}{10.0.0.6}{10.0.0.6:9300}{data=false, master=true}]. This might indicate that the store [elasticsearch-snapshots] is not shared between this node and the master node or that permissions on the store don't allow reading files written by the master node]'], [Gg5kwiRFT728YRHB5bAHlA, 'RemoteTransportException[[data-2][10.0.0.9:9300][internal:admin/repository/verify]]; nested: RepositoryVerificationException[[my_backup1] a file written by master to the store [elasticsearch-snapshots] cannot be accessed on the node [{data-2}{Gg5kwiRFT728YRHB5bAHlA}{10.0.0.9}{10.0.0.9:9300}{master=false}]. This might indicate that the store [elasticsearch-snapshots] is not shared between this node and the master node or that permissions on the store don't allow reading files written by the master node];'], [sX91n37nTVqVJWh_gcGhuQ, 'RemoteTransportException[[data-0][10.0.0.11:9300][internal:admin/repository/verify]]; nested: RepositoryVerificationException[[my_backup1] a file written by master to the store [elasticsearch-snapshots] cannot be accessed on the node [{data-0}{sX91n37nTVqVJWh_gcGhuQ}{10.0.0.11}{10.0.0.11:9300}{master=false}]. This might indicate that the store [elasticsearch-snapshots] is not shared between this node and the master node or that permissions on the store don't allow reading files written by the master node];'], [tc_dxu1WR02fvNwBELzkfg, 'RemoteTransportException[[data-1][10.0.0.10:9300][internal:admin/repository/verify]]; nested: RepositoryVerificationException[[my_backup1] a file written by master to the store [elasticsearch-snapshots] cannot be accessed on the node [{data-1}{tc_dxu1WR02fvNwBELzkfg}{10.0.0.10}{10.0.0.10:9300}{master=false}]. This might indicate that the store [elasticsearch-snapshots] is not shared between this node and the master node or that permissions on the store don't allow reading files written by the master node];'], [xoENYGRRT9-AlFyw_jEqMQ, 'RemoteTransportException[[master-1][10.0.0.7:9300][internal:admin/repository/verify]]; nested: RepositoryVerificationException[[my_backup1] a file written by master to the store [elasticsearch-snapshots] cannot be accessed on the node [{master-1}{xoENYGRRT9-AlFyw_jEqMQ}{10.0.0.7}{10.0.0.7:9300}{data=false, master=true}]. This might indicate that the store [elasticsearch-snapshots] is not shared between this node and the master node or that permissions on the store don't allow reading files written by the master node];'], [ILooIOS6SpeuWOPAn91YVA, 'RemoteTransportException[[master-2][10.0.0.5:9300][internal:admin/repository/verify]]; nested: RepositoryVerificationException[[my_backup1] a file written by master to the store [elasticsearch-snapshots] cannot be accessed on the node [{master-2}{ILooIOS6SpeuWOPAn91YVA}{10.0.0.5}{10.0.0.5:9300}{data=false, master=true}]. This might indicate that the store [elasticsearch-snapshots] is not shared between this node and the master node or that permissions on the store don't allow reading files written by the master node];']]"
   },
   "status": 500
}
```

All Standard Storage account types tested and work as expected.

**Steps to reproduce**:
1. Deploy an Elasticsearch cluster onto Azure (using the Elastic ARM template), including cloud-azure plugin
2. Set up Premium_LRS storage account to use with cloud-azure plugin and configure plugin to use account name and key
3. Attempt to create a snapshot repository with

``` sh
PUT _snapshot/my_backup1
{
   "type": "azure"
}
```

Observe error comes back.

### PR DESCRIPTION
**Pull request by russcam**
Add important note for supported Azure Storage account types

Closes #20765

### CODE REVIEW

**Review by dadoonet — APPROVED** [review]

**Comment by dadoonet** [comment]
+1 to push this doc in 2.4 branch and 5.0, 5.x and master under `repository-azure` plugin.

**Comment by dakrone** [comment]
@russcam want to push this PR since you have a +1?

**Comment by russcam** [comment]
@dakrone Sure. Am I OK to merge into 2.4 then cherry-pick to 5.0, 5.x and master?

**Comment by rjernst** [comment]
@russcam That is fine to merge first to 2.4 since the PR was opened against it, but in the future it is usually best to always start with master.

**Comment by russcam** [comment]
Thanks @rjernst. Will also port to `master`, `5.x`, `.5.0`, `5.1`, `5.2`, `5.3`, `5.4` and `5.5`

**Pull request merged**
