### PR TITLE
Remove leniency in msearch parsing

### LINKED ISSUE #61771: Make msearch line format less lenient
A user recently discovered that we allow training closing brackets in `_msearch` request lines (see https://github.com/elastic/elasticsearch/pull/61353).
It seems we parse only the first complete JSON object to a map, then discarding the rest of the line in MultiSearchRequest#readMultiLineFormat, allowing requests like the following:

```
GET my-index/_msearch
{"index": "my-index"}}}}
{"query" : {"match_all" : {}}}}}}
{"index": "my-index"}{ "this is" : "ignored as well"}
{"query" : {"match_all" : {}}}
```

While this is just a leniency that shouldn't affect the correct behaviour of the search, maybe we shouldn't allow this and error if we detect anything after parsing the initial json object.

### PR DESCRIPTION
**Pull request by limotova**
Extra characters after msearch request lines are currently ignored. This commit adds a check for extra chars and throws an exception if found.

Fixes #61771

### CODE REVIEW

**Comment by benwtrent** [comment]
jenkins retest this please

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Comment by benwtrent** [comment]
@elasticsearchmachine generate changelog

**Comment by benwtrent** [comment]
buildkite test this

**Comment by benwtrent** [comment]
@elasticmachine generate changelog

**Comment by benwtrent** [comment]
buildkite test this

**Comment by benwtrent** [comment]
buildkite test this

**Comment by benwtrent** [comment]
buildkite test this

**Comment by benwtrent** [comment]
There is a current test failure in the new test:
```
./gradlew ':server:test' --tests "org.elasticsearch.action.search.MultiSearchRequestTests.testFailOnExtraCharacters" -Dtests.seed=CA8A7F82B21E8CDF -Dtests.locale=vi -Dtests.timezone=Africa/Mbabane -Druntime.java=21
```

Trace:
```
  | org.elasticsearch.action.search.MultiSearchRequestTests > testFailOnExtraCharacters FAILED |  
  | org.junit.ComparisonFailure: expected:<...arting at [Source: ([org.elasticsearch.common.io.stream.ByteBufferStreamInput); line: 1, column: 0]) |  
  | at [Source: (org.elasticsearch.common.io.stream.ByteBufferStreamInput)]; line: 1, column: 3...> but was:<...arting at [Source: ([byte[])"{ "query": {"match_all": {}}}}}}different error message"; line: 1, column: 0]) |  
  | at [Source: (byte[])"{ "query": {"match_all": {}}}}}}different error message"]; line: 1, column: 3...> |  
  | at __randomizedtesting.SeedInfo.seed([CA8A7F82B21E8CDF:7CB6C2D0F713F0BC]:0) |  
  | at org.junit.Assert.assertEquals(Assert.java:115) |  
  | at org.junit.Assert.assertEquals(Assert.java:144) |  
  | at org.elasticsearch.action.search.MultiSearchRequestTests.testFailOnExtraCharacters(MultiSearchRequestTests.java:572)
```

@limotova

**Comment by limotova** [comment]
Sorry for the delay, should be fixed now @benwtrent

**Comment by benwtrent** [comment]
buildkite test this

**Review by benwtrent — APPROVED** [review]
🎉  🎉  🎉  Thank you @limotova ! 🎉  🎉  🎉

**Pull request merged**
