### PR TITLE
Log TooManyBucketsException

### PR DESCRIPTION
**Pull request by salvatore-campagna**
Here we just log `TooManyBucketException` to make investigating issues easier.

### CODE REVIEW

**Review by martijnvg — APPROVED** [review]
LGTM

**Comment by iverase** [comment]
I am just wondering if it is possible to get the type of aggregator throwing the error?

**Comment by salvatore-campagna** [comment]
> I am just wondering if it is possible to get the type of aggregator throwing the error?

Not if we log where the exception is thrown.

The way I see it is the following:
* log it from another place where the type or name of the aggregation is available requires us to do "catch>log>re-throw" which is considered an anti-patterns at least for two reasons
1. the same exception might be logged in multiple places which increases the amount of logs we write and makes root cause analysis of the exception difficult
2. exception handling might introduce performance issues especially if we start doing this almost everywhere...not to talk about how difficult to read the code becomes
* instead of logging in another place we might log where the exception is thrown but we have to pass down (through constructors or as method arguments more parameters). This is even worse in my opinion because it means we change our API to accommodate for the need of logging. Ideally we should do the opposite and always log at the top after the exception reaches the top level (Rest layer?).

**Comment by salvatore-campagna** [comment]
Here we just log TooManyBucketException to make investigating issues easier.

**Pull request merged**
