### PR TITLE
[DOCS] Fix list dangling indices documentation

### PR DESCRIPTION
**Pull request by russcam**
This PR fixes the list dangling indices response.
The dangling_indices array is an array of objects
that represent aggregated dangling index information

### CODE REVIEW

**Review by pugnascotia — APPROVED** [review]
LGTM. Apologies for the fumble in the initial docs 🤦

**Comment by ywelsch** [comment]
Can we get this merged?

**Comment by lockewritesdocs** [comment]
Apologies -- I was resolving the merge conflict to help get this change merged, and removed the braces! The 1935f86 commit adds them back and should fix the issue.

**Comment by russcam** [comment]
Yep, I can merge this. I think this should also be ported to 7.9 branch

**Pull request merged**
