### PR TITLE
Make IndexShard#openEngineAndRecoverFromTranslog async

### PR DESCRIPTION
**Pull request by DaveCTurner**
Removes one of the remaining production instances of a sync call to
`Engine#recoverFromTranslog`. Relates #96767, #96607.

### CODE REVIEW

**Comment by DaveCTurner** [comment]
Sorry, this is broken as written, I'm still iterating.

**Comment by DaveCTurner** [comment]
Ah darn it, this isn't going to work because of how the `InternalEngine` uses `ReentrantReadWriteLock`: we are getting stuck trying to upgrade a read lock to a write lock in `org.elasticsearch.index.engine.InternalEngine#fillSeqNoGaps`.

**Comment by DaveCTurner** [comment]
This now works thanks to recent changes such as #103138 and #103871.

**Review by henningandersen — APPROVED** [review]
LGTM.

**Review by fcofdez — APPROVED** [review]

**Pull request merged**
