### PR TITLE
Add .dir-locals.el file for Intellij-style indentation

### PR DESCRIPTION
**Pull request by dakrone**
This is the Emacs equivalent of applying settings to every .java file in the directory for devs that use Emacs.

### CODE REVIEW

**Comment by dakrone** [comment]
@mikemccand @jasontedor can you test this? I tested locally with `emacs -q` and it works great, but it would be good to have additional confirmation.

**Comment by jasontedor** [comment]
I took a look. I think it's really close but it seems to not be handling multi-line the same as IntelliJ in many cases. I don't think we need it to match exactly, but some of the formatting is probably not what we want either way.

Here's what I did. I formatted all files with IntelliJ. I use the standard settings. I made a local commit with these changes. Then, I executed:

    $ find ~/src/elastic/elasticsearch/core \
    > -iname \*.java \
    > -exec emacs -nw {} \
    > --eval \
    >   "(progn \
    >     (mark-whole-buffer) (indent-region (point-min) (point-max) nil) (save-buffer))" \
    > --kill \;

and then

    $ git diff --stat | tail -1

gives

    683 files changed, 9154 insertions(+), 9154 deletions(-)

Most of the examples of oddities are on multi-line handling for example `ActionModule.java`, `TransportGetMappingsAction.java`, `TransportPutRepositoryAction.java`, etc.

**Comment by jasontedor** [comment]
Yeah, commit 490cdfac5c441effaa2148a7325404f24d56d3d1 fixes the issues in `ActionModule.java`. :)

**Comment by dakrone** [comment]
@jasontedor don't forget to run with `-q` or `-Q` to make sure your specific config isn't incorrect!

**Comment by dakrone** [comment]
> 683 files changed, 9154 insertions(+), 9154 deletions(-)

Also this is a little dangerous using for an approximation because there are a lot of files that already have incorrect indentation from Intellij's perspective

**Comment by jasontedor** [comment]
@dakrone Yeah; instead I just temporarily blew away my `.emacs` and `.emacs.d` because otherwise emacs will keep asking me to confirm whether or not to apply maybe-not-safe changes from your `.dir-locals.el`.

**Comment by dakrone** [comment]
@jasontedor you should be able to hit `!` once to save them as "safe" for future sessions.

**Comment by jasontedor** [comment]
> Also this is a little dangerous using for an approximation because there are a lot of files that already have incorrect indentation from Intellij's perspective

That's why I first applied IntelliJ's settings to every file in `core` and committed it locally first.

**Comment by jasontedor** [comment]
> @jasontedor you should be able to hit ! once to save them as "safe" for future sessions.

I think the point is exactly that that doesn't keep if you have `-q`?

**Comment by dakrone** [comment]
> That's why I first applied IntelliJ's settings to every file in core and committed it locally first.

I missed that but I see it now in your original messages, good call! Sorry for the mix up!

> I think the point is exactly that that doesn't keep if you have -q?

Yeah, that's the case, the `-q` is just for testing this.

**Comment by dakrone** [comment]
@jasontedor I went down the path of trying to fix every single indentation problem with this, but it will end up being huge due to tons of special cases. I think for now this is a better alternative than the defaults for indentation. How do you feel about merging this and then I can address further problems if/when they arise?

**Comment by jasontedor** [comment]
Commit 2c16adb78430c544dedf02cc8c8306e3dba1e127 helped with a few more. 

> How do you feel about merging this and then I can address further problems if/when they arise?

I think that sounds like a good plan. LGTM.

**Comment by mikemccand** [comment]
Whoa, I missed this, but I played with it just now and it's really nice!  So I can clean up my .emacs now :)

Thanks @dakrone

+1 to push!

**Pull request merged**
