### PR TITLE
Add Ability to Write a BytesReference to BlobContainer

### PR DESCRIPTION
**Pull request by original-brownbear**
Except when writing actual segment files to the blob store
we always write `BytesReference` instead of a stream.
Only having the stream API available forces needless copies
on us. I fixed the straight-forward needless copying for
HDFS and FS repos in this PR, we could do similar fixes for
GCS and Azure as well and thus significantly reduce the peak
memory use of these writes on master nodes in particular.

### CODE REVIEW

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/1 (unrelated + known)

**Comment by original-brownbear** [comment]
@fcofdez hold off on the review for a sec (or ignore HDFS for now), I made a small mistake there with the write flags and it fails tests now. I'll fix it once I'm back from my lunch break :)

**Comment by original-brownbear** [comment]
@fcofdez fixed my random oversight :) should be good to review now.

**Review by fcofdez — APPROVED** [review]
Thanks for the change! LGTM

**Comment by original-brownbear** [comment]
Thanks Francisco!

**Pull request merged**
