### PR TITLE
[DOCS] Clean up links from SQL client app pages.

### PR DESCRIPTION
**Pull request by debadair**

### CODE REVIEW

**Review by monfera — APPROVED** [review]
Thank you very much @debadair, it looks great to me!

**Comment by astefan** [comment]
@debadair I don't see any more details about the reasons for removing those links and quotes. Can you, please, share some info about this? Thanks.

**Review by astefan — APPROVED** [review]
I agree with these changes, but I would keep somehow the url to the client app. How about using the link in the "Prerequisites" section where the name of the product is being used?

**Comment by debadair** [comment]
Added the links to the prereqs section. That's consistent with the handling of the other prereqs, but avoids the problem of immediately sending folks off somewhere else from the top of the page.

**Pull request merged**
