### PR TITLE
Add cross cluster search test for mvt end point

### PR DESCRIPTION
**Pull request by iverase**
Cross cluster search is supported by the mvt end point. ThisPR adds a test to make sure this does not change and adds a reference on the documentation.

### CODE REVIEW

**Comment by jrodewig** [comment]
Thanks @iverase. I pushed some additional doc changes in 52d135dc26e12f9f90f3c2d0148b4231ebf4af17. However, I wasn't sure how the API handled [network roundtrips][0]. I couldn't find a related `ccs_minimize_roundtrips` option. We should document that somewhere, whether in the API or the CCS docs.

[0]: https://www.elastic.co/guide/en/elasticsearch/reference/7.15/modules-cross-cluster-search.html#ccs-network-delays

**Comment by iverase** [comment]
It is a good point about `ccs_minimize_roundtrips`. It is not exposed so it will use the default (which I believe is true at the moment). I need to to discuss with other people if we should add that parameter to the API.

**Review by jrodewig — APPROVED** [review]
>  It is not exposed so it will use the default (which I believe is true at the moment).

Thanks for clarifying. I pushed https://github.com/elastic/elasticsearch/pull/78054/commits/4f97e0399aede544c18075f0b048fbdff42381b8 to add a related note.

With that change, this LGTM.

**Review by imotov — APPROVED** [review]
LGTM

**Comment by iverase** [comment]
@elasticmachine update branch

**Comment by iverase** [comment]
known unrelated issue

@elasticmachine run elasticsearch-ci/part-1

**Pull request merged**
