### PR TITLE
SQL: Use null schema response

### LINKED ISSUE #46381: SQL: SYS TABLES should return a null schema
Just like `SYS COLUMNS` return `null` for schema name, same should happen for `SYS TABLES` command.

### PR DESCRIPTION
**Pull request by astefan**
`SYS TABLES` should return `null` for schema.
Fixes https://github.com/elastic/elasticsearch/issues/46381.

### CODE REVIEW

**Comment by astefan** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Review by costin — APPROVED** [review]
LGTM.

It's worth checking the change with some of the visualization tools (DbVis & co) to see how they react to it.

**Comment by astefan** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Review by matriv — APPROVED** [review]
LGTM

**Pull request merged**
