### PR TITLE
Remove DFS_QUERY_AND_FETCH as a search type

### PR DESCRIPTION
**Pull request by s1monw**
This commit removes the search type `dfs_query_and_fetch` without a
replacement. We don't allow to use this type via REST since 2.x
but still keep it around for no particular reason. There we no users
complaining about the availability. This should now be removed from the
codebase. `query_and_fetch` is still used internally to safe a roundtrip
if there is only one shard but it can't be used via the rest interface.

### CODE REVIEW

**Review by jpountz — APPROVED** [review]
LGTM

**Comment by s1monw** [comment]
@elasticmachine test this please

**Comment by s1monw** [comment]
@elasticmachine test this please

**Comment by s1monw** [comment]
@elasticmachine test this please

**Comment by s1monw** [comment]
I will port this to 5.x as well. documentation for this stuff has been removed long ago and it's impossible to use it with REST anyway. @jpountz  @clintongormley objections?

**Comment by jpountz** [comment]
No objections, we removed the documentation for it a long time ago.

**Comment by clintongormley** [comment]
+1 I can't imagine why anybody would be using this in java land

**Comment by dadoonet** [comment]
@clintongormley And we wrote that in Java doc 2 years ago: https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/java-search.html

> Although the Java API defines the additional search types QUERY_AND_FETCH and DFS_QUERY_AND_FETCH, these modes are internal optimizations and should not be specified explicitly by users of the API.

So to me it's really clear that people should never use that.

**Comment by gmarz** [comment]
We should also remove `dfs_query_then_fetch` as an option from the REST spec, but since that will leave `query_then_fetch`  as the only option, should we remove the `search_type` parameter altogether?

**Comment by clintongormley** [comment]
@gmarz `dfs_query_AND_fetch`, not `dfs_query_THEN_fetch`

**Comment by gmarz** [comment]
@clintongormley ah! thanks -- totally misread this

**Pull request merged**
