### PR TITLE
Enabling testing against an external cluster

### PR DESCRIPTION
**Pull request by jasontedor**
Today when executing REST tests we take full responsibility for cluster configuration. Yet, there are use cases for brining your own cluster to the REST tests. This commit is a small first step towards that effort by skipping creating the cluster if the tests.rest.cluster and test.cluster system properties are set. In this case, the user takes full responsibility for configuring the cluster as expected by the REST tests. This step is by no means meant to be perfect or complete, only a baby step.

### CODE REVIEW

**Comment by jasontedor** [comment]
retest this please

**Comment by jasontedor** [comment]
retest this please

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by jasontedor** [comment]
retest this please

**Comment by jasontedor** [comment]
run sample packaging tests

**Pull request merged**
