### PR TITLE
Remove deprecated local parameter from alias APIs

### PR DESCRIPTION
**Pull request by PeteGillinElastic**
This removes the `local` parameter from the `GET /_alias`, `HEAD /_alias`, and `GET /_cat/aliases` APIs. This option became a no-op and was deprecated in 8.12 by https://github.com/elastic/elasticsearch/pull/101815.

We continue to accept the parameter (deprecated, with no other effect) in v8 compatibility mode for `GET /_alias` and `HEAD /_alias`. We don't do this for `GET /_cat/aliases` where the [compatibility policy does not apply](https://github.com/elastic/elasticsearch/blob/main/REST_API_COMPATIBILITY.md#when-not-to-apply).

### CODE REVIEW

**Comment by PeteGillinElastic** [comment]
@elasticmachine update branch

**Review by masseyke — APPROVED** [review]
LGTM

**Comment by leemthompo** [comment]
@PeteGillinElastic is this PR relevant to the serverless changelog? [FYI this question is based on [9.0 breaking changes](https://staging-website.elastic.co/docs/release-notes/elasticsearch/breaking-changes)]

**Comment by PeteGillinElastic** [comment]
I think this depends on the policy for the serverless changelog. This property was deprecated and ignored since 8.0.0, so nobody should have been using it in serverless. I don't know whether this should be mentioned or not.


Also, this change was made in October, before serverless GA.

**Pull request merged**
