### PR TITLE
Remove extra check for object existence in repository-gcs read object

### PR DESCRIPTION
**Pull request by tlrx**
This pull request removes another extra blob exist check when reading an object from Google Cloud Storage.

### CODE REVIEW

**Comment by vladimirdolzhenko** [comment]
LGTM

**Review by vladimirdolzhenko — COMMENTED** [review]
_

**Review by ywelsch — APPROVED** [review]
LGTM

**Review by vladimirdolzhenko — APPROVED** [review]
LGTM

**Comment by tlrx** [comment]
Thanks @ywelsch and @vladimirdolzhenko

**Pull request merged**
