### PR TITLE
initial hashmap with suitable size in initial RoutingNodes

### PR DESCRIPTION
**Pull request by GrandFisher**
We believe that when building RoutingNodes,  the average number of shards on the nodes can be calculated based on the existing metadata of the cluster to reduce unnecessary resize of the HashMap, especially when the number of shards is relatively large.
Our code only calculates the initial size of the HashMap, and does not change anything that may affect the logic.

### CODE REVIEW

**Comment by fcofdez** [comment]
@GrandFisher  could you please sign the [Contributor Agreement](https://www.elastic.co/contributor-agreement)? Thanks!

**Comment by GrandFisher** [comment]
> @GrandFisher could you please sign the [Contributor Agreement](https://www.elastic.co/contributor-agreement)? Thanks!

I have signed this, but it doesn’t seem to be effective yet

**Comment by fcofdez** [comment]
It seems like the commit has a different author, maybe that's the problem?

**Comment by GrandFisher** [comment]
> It seems like the commit has a different author, maybe that's the problem?
This is caused by my operation in a different environment, I will solve this problem and notify you later

**Comment by GrandFisher** [comment]
> It seems like the commit has a different author, maybe that's the problem?

I have fixed this problem by setting git username to github name instead of using the default name.

**Comment by DaveCTurner** [comment]
I think we're missing a couple of things here. Firstly I can kind of guess why you're suggesting the formulae you're suggesting, but really we need you to write up the theory behind this change more precisely, including any assumptions on which these formulae are based. Secondly, we need to quantify the benefits of this change with some benchmarking. Are we saving 1ms? 100ms? How do the savings depend on cluster size etc?

**Comment by GrandFisher** [comment]
> I think we're missing a couple of things here. Firstly I can kind of guess why you're suggesting the formulae you're suggesting, but really we need you to write up the theory behind this change more precisely, including any assumptions on which these formulae are based. Secondly, we need to quantify the benefits of this change with some benchmarking. Are we saving 1ms? 100ms? How do the savings depend on cluster size etc?

For the HashMap in Java, the default initialization size is 16, and the default collision factor is 0.75, which means that when it exceeds 12 (16 * 0.75), the HashMap needs to be resized. If you want to expand to thousands, you must expand at least 6 times. If it can be initialized in place at one time, these redundant Resizes can be avoided.

Specifically, the capacity of the HashMap can be calculated by the collision factor and the number of shards, that is, Capcity = Size / factor +1 (rounded up).
In ES, we can assume that the number of shards in each node is almost equal. In the initialization of RoutingNodes, we can know the average number of shards per node, only the number of datanodes and the number of all shards. But for some special cases, for example, there is no datanode at the beginning of the cluster, we need to ensure that the nodes is 1 to avoid ArithmeticException, or the shards of each node are few, but less than 16, then the initial size can be kept at the default 16.
        int totalShards = routingTable.allShards().size();
        int nodes = Math.max(clusterState.nodes().getDataNodes().size(), 1);
        final int initialNodesSize = Math.max((int)(nodes / 0.75) + 1, 16);
        final int initialShardSize = Math.max((int)(totalShards / nodes / 0.75) + 1, 16);

In the initialization of RoutingNode, the size of shardsByIndex depends on the Index size of the node. Here we directly use the index size of the cluster to estimate, so the actual result will be larger. In fact, the index number of a node exceeds 1024, which is a relatively rare situation in practice. So we set the upper limit to 1024.

        this.shardsByIndex = new LinkedHashMap<>(Math.min(1024, Math.max(16, (int) (indexSize / 0.75) + 2)));

When performing some operations on an ES cluster with a node's shards in the thousands, such as creating an index, we observe the flame graph (obtained by this command: ./profiler.sh -d 60 -f ./master.svg -e wall -I'org/elasticsearch/cluster/service/MasterService*' pid) found that the total cost of resizing occupies 3.4%. In fact, these are not needed.

In some relatively large clusters, when the cluster nodes have more shards, our changes will have a better effect. But for some small clusters, the optimization effect is not obvious.

Next, I will  quantify the benefits of this change with some benchmarking and I will notify you when it’s done.

**Comment by GrandFisher** [comment]
After benchmarking, I found that the performance improvement is very limited, or even worse. And it seems that there is no way to further optimize our code for the time being.

**Comment by DaveCTurner** [comment]
:+1: thanks for checking @GrandFisher.

I do believe there are ways to improve performance in this area, although it won't be anything so simple. For example, do we need to recompute the whole `RoutingNodes` from scratch on each cluster state update? Would it be faster to take the `RoutingNodes` from the previous state and adjust it for any changes in the cluster state instead? If you're interested in exploring this sort of idea then go ahead.

**Comment by GrandFisher** [comment]
> 👍 thanks for checking @GrandFisher.
> 
> I do believe there are ways to improve performance in this area, although it won't be anything so simple. For example, do we need to recompute the whole `RoutingNodes` from scratch on each cluster state update? Would it be faster to take the `RoutingNodes` from the previous state and adjust it for any changes in the current state instead? If you're interested in exploring this sort of idea then go ahead.

Thank you very much for your encouragement and suggestions, we will seriously consider your suggestions and continue to try to optimize the logic of this part

**Pull request closed without merging**
