### PR TITLE
Fix anaylze NullPointerException when AnalyzeTokenList tokens is null

### PR DESCRIPTION
**Pull request by weizijun**
GET test_analyze/_analyze api maybe return NullPointerException when AnalyzeTokenList tokens is null.
It appears when get AnalyzeResponse from other es node. because it will cause new AnalyzeResponse from readFrom method.
the NullPointerException case can appear as follow(more then two nodes):

first:

```
PUT test_analyze
{
  "settings": {
    "index": {
      "analysis": {
        "filter": {
          "stopwords_filter": {
            "type": "stop",
            "stopwords": ["the", "over"]
          }
        },
        "analyzer": {
          "standard_syno": {
            "filter": [
              "stopwords_filter"
            ],
            "type": "custom",
            "tokenizer": "standard"
          }
        }
      }
    }
  }
}
```
then:

```
GET test_analyze/_analyze
{
  "text":"the",
  "analyzer":"standard_syno",
  "explain":true
}
```
it sometimes appear(when transport action execute on the other node):

```
{
  "error": {
    "root_cause": [
      {
        "type": "null_pointer_exception",
        "reason": null
      }
    ],
    "type": "null_pointer_exception",
    "reason": null
  },
  "status": 500
}
```
I fixed this bug in the commit.
I also find that when charfilters field is null, the xcontent result is different when execute on local node and on the other node. because this is my fisrt commit, I made this pr simple.

### CODE REVIEW

**Comment by weizijun** [comment]
I have sign CLA, but the check is also failed

**Comment by mayya-sharipova** [comment]
@elasticmachine  test this please

**Comment by mayya-sharipova** [comment]
@weizijun thanks a lot for your contribution.  It still looks like you have not signed the CLA. Can you please make sure the CLA is signed, we will not be able to merge this PR without CLA.

**Review by mayya-sharipova — APPROVED** [review]
Approve after the CLA signed and tests pass.

**Comment by weizijun** [comment]
@mayya-sharipova thanks! CLA signed done, but two ci error.Is it an environmental problem?

**Comment by weizijun** [comment]
I run the failed test in my laptop, it's successful

> Task :x-pack:plugin:ccr:internalClusterTest
==> Test Summary: 1 suite, 5 tests, 1 ignored (1 assumption)
   [junit4] JVM J0:     0.59 ..    13.91 =    13.32s
   [junit4] Execution time total: 13 seconds
   [junit4] Tests summary: 1 suite, 5 tests, 1 ignored (1 assumption)

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.2.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 1m 34s

**Comment by mayya-sharipova** [comment]
@weizijun  Thanks for signing the CLA. I am going to retest this PR.
@elasticmachine test this please

**Comment by mayya-sharipova** [comment]
@weizijun To get rid of unrelated failures, would you be able to rebase your PR against recent master?  or do you want me to do that?

**Comment by weizijun** [comment]
@mayya-sharipova I see commit 931270f6c827faa92b1c5f7f3244eb9ced8a891a(Fix broken CCR retention lease unfollow test) fixed the CcrRetentionLeaseIT exception. Would I only cherry-pick this commit or rebase current master?

**Comment by weizijun** [comment]
@mayya-sharipova I have merged the recent master commit, and now running check

**Comment by weizijun** [comment]
@elasticmachine test this please

**Comment by weizijun** [comment]
@mayya-sharipova maybe there is some wrong with my operate.Would I close the pr and create another?

**Comment by mayya-sharipova** [comment]
@weizijun  We will need to close this PR (it got messy here) and reopen a new one. I will close this PR, would you be able to open a new PR with the same changes?

So, when your branch is behind a `master` and you want to merge `master` into your branch, you need to follow these steps:

```bash
git checkout master
git fetch upstream #get new changes from upstream
git merge upstream/master #merge changes from upstream to your local master
git checkout <your_branch>
git merge master  #merge changes from your local master to your branch
```

**Comment by weizijun** [comment]
@mayya-sharipova ok, thanks!  I will reopen a new pr after gradle check done.

**Pull request closed without merging**
