### PR TITLE
Upgrade to JUnit 4.12

### PR DESCRIPTION
**Pull request by dadoonet**
Release notes: https://github.com/junit-team/junit4/blob/master/doc/ReleaseNotes4.12.md

### CODE REVIEW

**Review by jasontedor — CHANGES_REQUESTED** [review]
You have to grant `java.lang.RuntimePermission "accessDeclaredMembers"` to JUnit 4.12 in test-framework.policy (replace what is already granted to JUnit 4.11). Also, you'll need to check if the junit4-ant dependency is updated and adjust accordingly.

**Comment by dadoonet** [comment]
Thanks @jasontedor 

Something looks strange to me about `junit4-ant`. In master branch, we upgraded already randomized testing fw to 2.5.0 but I think we forgot to upgrade junit4-ant policy as [I can see](https://github.com/elastic/elasticsearch/blob/master/core/src/main/resources/org/elasticsearch/bootstrap/test-framework.policy#L56-L59):

```
grant codeBase "${codebase.junit4-ant-2.3.2.jar}" {
  // needed for stream redirection
  permission java.lang.RuntimePermission "setIO";
};
```

Does it mean that we actually don't need anymore this policy? WDYT?

**Comment by dadoonet** [comment]
I ran `gradle test` and it's passing in elasticsearch master branch.

**Comment by rjernst** [comment]
> In master branch, we upgraded already randomized testing fw to 2.5.0 but I think we forgot to upgrade junit4-ant policy
> Does it mean that we actually don't need anymore this policy?

That permission is still listed in the example security policy for RR:
https://github.com/randomizedtesting/randomizedtesting/blob/c3b588549ede1c3acf8c35f2b6dd66046cdda309/examples/security-manager/security.policy

**Comment by jasontedor** [comment]
The setIO permission is indeed needed, randomized runner tries to set stdout and stderr for the slaves. Please return that permission with the correct version, otherwise we are at risk of losing valuable output.

**Comment by jasontedor** [comment]
@rjernst and I looked at this more closely. The permission would be needed by the JVM that forks the slave JVMs. For us, this JVM does not run with a security manager, only the slave JVMs do in the common case. So, we in fact do not need this permission and it can remain removed.

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by dadoonet** [comment]
Thanks @jasontedor and @rjernst.

Do you think this should also go to 5.x branch?

**Comment by jasontedor** [comment]
> Do you think this should also go to 5.x branch?

Yes.

**Comment by dadoonet** [comment]
Pushed in master/5.x (5.5.0). Thanks!

**Pull request merged**
