### PR TITLE
Upgrade to lucene-7.0.0-snapshot-a0aef2f

### PR DESCRIPTION
**Pull request by nknize**
This PR upgrades master to a current Lucene snapshot with commit id `a0aef2f`.

### CODE REVIEW

**Comment by nknize** [comment]
There is currently a failing test that I could use another set of eyes on. Might be something simple, but its in the hungarian analyzer which I have little experience with. @cbuescher Could you have a look?

``` 
REPRODUCE WITH: gradle :plugins:analysis-ukrainian:test -Dtests.seed=4FA45DF62C3EBDFD -Dtests.class=org.elasticsearch.index.analysis.SimpleUkrainianAnalyzerTests -Dtests.method="testBasicUsage" -Dtests.security.manager=true -Dtests.locale=es-NI -Dtests.timezone=Europe/Paris
ERROR   1.60s J0 | SimpleUkrainianAnalyzerTests.testBasicUsage <<< FAILURES!
   > Throwable #1: java.lang.NullPointerException
   >    at __randomizedtesting.SeedInfo.seed([4FA45DF62C3EBDFD:14B7E413A036E21D]:0)
   >    at morfologik.stemming.Dictionary.read(Dictionary.java:80)
   >    at org.apache.lucene.analysis.uk.UkrainianMorfologikAnalyzer.getDictionary(UkrainianMorfologikAnalyzer.java:154)
   >    at org.apache.lucene.analysis.uk.UkrainianMorfologikAnalyzer.createComponents(UkrainianMorfologikAnalyzer.java:148)
   >    at org.apache.lucene.analysis.Analyzer.tokenStream(Analyzer.java:198)
   >    at org.elasticsearch.index.analysis.SimpleUkrainianAnalyzerTests.testAnalyzer(SimpleUkrainianAnalyzerTests.java:46)
   >    at org.elasticsearch.index.analysis.SimpleUkrainianAnalyzerTests.testBasicUsage(SimpleUkrainianAnalyzerTests.java:37)
   >    at java.lang.Thread.run(Thread.java:745)
```

**Comment by cbuescher** [comment]
@nknize It appears the Ukrainian dictionary resource cannot be loaded by the Analyzer. When debugging this I see that in `UkrainianMorfologikAnalyzer#getDictionary` the resource that should be loaded by `UkrainianMorfologikAnalyzer.class.getClassLoader().getResource("ua/net/nlp/ukrainian.dict")` is null. Since this is internal to Lucene I don't know exactly what might have changed there but will see what happens instead on master where this seems to work.

**Comment by cbuescher** [comment]
There appears to be a packaging problem with the lucene-analyzers-morfologik-7.0.0-snapshot jar. The one that is still used on master (snapshot-89f6d17) contains the `ukrainian.dict`, the one used in this PR (snapshot-a0aef2f) appears to be missing this file. From my gradle cache:
```
~/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-analyzers-morfologik/7.0.0-snapshot-89f6d17/1fe11b45d9f6a68ef1e9994bebd81d26632efc5$ jar -tf lucene-analyzers-morfologik-7.0.0-snapshot-89f6d17.jar
META-INF/
META-INF/MANIFEST.MF
META-INF/services/
org/
org/apache/
org/apache/lucene/
org/apache/lucene/analysis/
org/apache/lucene/analysis/morfologik/
org/apache/lucene/analysis/uk/
META-INF/services/org.apache.lucene.analysis.util.TokenFilterFactory
org/apache/lucene/analysis/morfologik/MorfologikAnalyzer.class
org/apache/lucene/analysis/morfologik/MorfologikFilter.class
org/apache/lucene/analysis/morfologik/MorfologikFilterFactory.class
org/apache/lucene/analysis/morfologik/MorphosyntacticTagsAttribute.class
org/apache/lucene/analysis/morfologik/MorphosyntacticTagsAttributeImpl.class
org/apache/lucene/analysis/morfologik/package-info.class
org/apache/lucene/analysis/uk/UkrainianMorfologikAnalyzer$DefaultSetHolder.class
org/apache/lucene/analysis/uk/UkrainianMorfologikAnalyzer.class
org/apache/lucene/analysis/uk/mapping_uk.txt
org/apache/lucene/analysis/uk/package-info.class
org/apache/lucene/analysis/uk/stopwords.txt
org/apache/lucene/analysis/uk/ukrainian.dict
org/apache/lucene/analysis/uk/ukrainian.info
META-INF/LICENSE.txt
META-INF/NOTICE.txt

~/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-analyzers-morfologik/7.0.0-snapshot-a0aef2f/26d01ae0d15243b30874b2cb609be5d041890459$ jar -tf lucene-analyzers-morfologik-7.0.0-snapshot-a0aef2f.jar
META-INF/
META-INF/MANIFEST.MF
META-INF/services/
org/
org/apache/
org/apache/lucene/
org/apache/lucene/analysis/
org/apache/lucene/analysis/morfologik/
org/apache/lucene/analysis/uk/
META-INF/services/org.apache.lucene.analysis.util.TokenFilterFactory
org/apache/lucene/analysis/morfologik/MorfologikAnalyzer.class
org/apache/lucene/analysis/morfologik/MorfologikFilter.class
org/apache/lucene/analysis/morfologik/MorfologikFilterFactory.class
org/apache/lucene/analysis/morfologik/MorphosyntacticTagsAttribute.class
org/apache/lucene/analysis/morfologik/MorphosyntacticTagsAttributeImpl.class
org/apache/lucene/analysis/morfologik/package-info.class
org/apache/lucene/analysis/uk/UkrainianMorfologikAnalyzer$DefaultSetHolder.class
org/apache/lucene/analysis/uk/UkrainianMorfologikAnalyzer.class
org/apache/lucene/analysis/uk/mapping_uk.txt
org/apache/lucene/analysis/uk/package-info.class
org/apache/lucene/analysis/uk/stopwords.txt
META-INF/LICENSE.txt
META-INF/NOTICE.txt
```

**Comment by jimczi** [comment]
@cbuescher The resource has been moved to an external dependency:
https://issues.apache.org/jira/plugins/servlet/mobile#issue/LUCENE-7785
So you'll need to add the new dependendy in the gradle file for the plugin:
https://git-wip-us.apache.org/repos/asf?p=lucene-solr.git;a=blobdiff;f=lucene/analysis/morfologik/ivy.xml;h=f0cc2343fe3d7176c0c5edeba2fdc0f4671bf88c;hp=1312aabb907404803aa6e137f5600b6488f0e3c5;hb=e62a3ff;hpb=48d54ac45860a1b75bfd79aaffe9d4d24c2ad5a8

**Comment by nknize** [comment]
Ah, I missed that issue! Thanks so much @jimczi 

@cbuescher I can fix this as part of the PR if its easier. No difference to me.

**Comment by cbuescher** [comment]
Great, I think it should be part of this PR. I just tried updating the plugin dependencies to:

```
-  compile "org.carrot2:morfologik-stemming:2.1.0"
-  compile "org.carrot2:morfologik-fsa:2.1.0"
+  compile "org.carrot2:morfologik-stemming:2.1.1"
+  compile "org.carrot2:morfologik-fsa:2.1.1"
+  compile "ua.net.nlp:morfologik-ukrainian-search:3.7.5"
```

And this seems to work. I got the version numbers from https://github.com/apache/lucene-solr/blob/master/lucene/ivy-versions.properties but I'm not entirely sure if these are the correct ones for this snapshot version (its lucene master, I'm not sure about how your branches are organized)

Furthermore I'm wondering how we are usually supposed to track transitive dependency version updates like this (e.g. going from morfologik-fsa:2.1.0 to morfologik-fsa:2.1.1 in this case) for lucene analyzers etc... Any thoughts on this are appreciated.

**Comment by jimczi** [comment]
> Furthermore I'm wondering how we are usually supposed to track transitive dependency version updates like this (e.g. going from morfologik-fsa:2.1.0 to morfologik-fsa:2.1.1 in this case) for lucene analyzers etc... Any thoughts on this are appreciated.

I think it should be part of the upgrade process, I'll add a line in the docs about checking the external dependencies. For instance the upgrade of icu4j is missing in master: 
https://issues.apache.org/jira/browse/LUCENE-7035
No need to add this change in this PR, we can fix the discrepancy in a follow up.

**Review by jimczi — APPROVED** [review]
LGTM
@nknize you'll have to re-run updateSHAS to include the new jars.

**Review by jpountz — APPROVED** [review]
Thanks @nknize !

**Pull request merged**
