### PR TITLE
Report recovered files as recovered from snapshot for fully mounted searchable snapshots

### PR DESCRIPTION
**Pull request by tlrx**
Files recovered for fully mounted searchable snapshots indices are reported in the same manner as files recover from disk for regular indices. This can be confusing for users because we later introduced a `recovered_from_snapshot_in_bytes` (for snapshot based peer recoveries, that is not applicable to searchable snapshots indices) and this field is always `0` for  searchable snapshots indices.

This pull request changes the Recovery file details so that `recovered_from_snapshot_in_bytes` is now populated for files recovered for fully mounted searchable snapshots indices, which I think makes more sense now we have this  `recovered_from_snapshot_in_bytes` field. I also think it qualifies as a bug.

### CODE REVIEW

**Review by fcofdez — APPROVED** [review]
LGTM. I didn't notice this when I added this new field, I see how this can be confusing with searchable snapshots, thanks for fixing it 👍.

**Comment by tlrx** [comment]
@elasticmachine run elasticsearch-ci/part-1

**Review by DaveCTurner — APPROVED** [review]
LGTM2

**Comment by tlrx** [comment]
Thanks Francisco and David

**Pull request merged**
