### PR TITLE
Deprecate common_terms query and cutoff_frequency

### PR DESCRIPTION
**Pull request by cshtdd**
Hello @jimczi

Can you please check this addresses the deprecation.

Also, I wasn't sure if I had to call the deprecationLogger somewhere. Any feedback would be appreciated.

Closes Issue #37096

### CODE REVIEW

**Comment by colings86** [comment]
@camilin87 I hope you don't mind but I've edited the title of this PR so its descriptive about the change that is being made.

**Review by mayya-sharipova — CHANGES_REQUESTED** [review]
@camilin87 Thank you for submitting a PR.
We indeed need a `deprecationLogger` for these change that will output a deprecation warning for common terms query and a cutoff frequency in match query.

You can refer to an example how deprecationLogger is used in [IdsQueryBuilder](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/index/query/IdsQueryBuilder.java).  For example, for `MatchQueryBuilder` during parsing a request `fromXContent` you can issue a deprecation warning, if you encounter `CUTOFF_FREQUENCY_FIELD`.

For the whole PR,  besides code changes, we also would need tests and documentation changes.

**Comment by mayya-sharipova** [comment]
@camilin87 Would you like still to continue working on this PR and address the feedback or should we be closing it?

**Comment by camilin87** [comment]
I would like to keep working on it.
But I won't be able to do it for at least two weeks.

Please do what you think is best.

Thank you very much.

**Comment by mayya-sharipova** [comment]
@camilin87  Thanks.  I think it is unlikely that anyone is going to work on this PR within 2 weeks, so go ahead, when you have time.

**Comment by jimczi** [comment]
I am going to close this pr in case someone else wants to work on this. If the issue is still open when you come back feel free to resume the work here @camilin87.

**Pull request closed without merging**
