### PR TITLE
Create an array-based version of ChunkedToXContentBuilder

### LINKED ISSUE #118647: `ChunkedToXContentBuilder` should be removed
The current idea behind `ChunkedToXContentBuilder` is broken. We create the `ChunkedToXContentBuilder` which is essentially a flat stream of the chunks we're building up-front at the beginning of serialization.
This runs counter to the whole concept of `ChunkedToXContent` which tries to ideally be O(1) in terms of up-front heap and runtime cost by pushing all iterations down to when we actually serialize.
I get how the API looks nicer than manually building iterators but this kind of API when combined with iteration (both internally or at the start of the serialization) breaks chunking.
We see this practically and very visibly in search response (and to a lesser degree also for bulk responses) serialization slowness today and almost more importantly the approach causes stability issues on the transport layer in an unpredictable way.

I don't think the API can be fixed or that it is worthwhile to fix it. The slight improvement in readability of the code comes at the cost of unpredictable and hard to reason about performance here as would probably any solution not built on statically known iteration counts.
Marking this as >bug since I am observing an uptick in transport thread slowness from it and it's easy to construct search use cases that destabilize a cluster since its introduction into the search response handling.

### PR DESCRIPTION
**Pull request by thecoop**
Use fixed-size arrays, but the methods and semantics of `ChunkedToXContentBuilder`

Fixes https://github.com/elastic/elasticsearch/issues/118647

### CODE REVIEW

**Comment by original-brownbear** [comment]
I'm sorry @thecoop but I fail to see what this is trying to achieve.
Yes this is probably somewhat faster than the previous version but also obviously slower than the original version without the builder. Again, the chunked x-content logic is only applicable to a very narrow set of use-cases and any API that makes it look nicer (somewhat subjective to begin with, but I get where this is coming from) by adding more push-style logic before the pull-style iteration will slow things down.
Is it really worth all this noise and cost iterating on a builder implementation when the previous implementation will always be faster and really since this is transport thread logic and about as hot as anything ever gets in ES, that is all that matters pretty much. If anything, I'd rather look into writing custom code for search response and bulk response instead of chaining iterators since both of these are considerable CPU consumers. 
Sorry but looking at benchmarks and profiling in general we want faster here and any abstraction layer means slower (and slower means less stable because we're on transport threads!).
=> in light of the cost of all of this, is there any reason to not just revert to the old version and be done with this? :)

**Comment by thecoop** [comment]
Can you point to how this will be slower? The objects returned are the same types returned by the previous `ChunkedToXContentHelper` methods.

**Comment by original-brownbear** [comment]
This one in isolation isn't much slower but even this still has the negative effect of duplicating existing implementations in `ChunkedToXContentHelper` (and reintroduction of a method previously deleted from that) which is just needless overhead as well (larger table to look up from for the virtual calls).
My point here really was just: we had something that worked reasonably fast why not just go back to that and be happy with it and optimize further rather than go through all this noise? :) Also, note that we started from issues with slow search response serialization, this doesn't remove the slow builder nor addresses search responses in any way?
A fix for https://github.com/elastic/elasticsearch/issues/118647 should deal with the slow builder, not just (re-)add duplicate code for one specific path?

**Comment by original-brownbear** [comment]
@thecoop I finally got around to be profiling this stuff in some detail.
Now I understand why even this PR doesn't get us back to "normal" for search performance. In fact, even though you'd think it'd return to the old numbers, it doesn't.
The reason is that prior to introducing the builder we had a situation where we pretty much always had the array based iterator at the top level of the chunking and it inlined. We already got regressions out of moving to the builder in early October for bulk (regressions in search though!) because that polluted the profile. The regression was just relatively small and we missed it because of the ongoing Lucene 10 work :( 

=> there's no point in messing with this stuff on a per response basis. I'd suggest we asap revert the builder stuff for the time being. Reverting to the old code brings back better than before performance numbers in my testing because part of the Lucene 10 improvements became invisible with the builder introduction on the bulk response.

**Pull request closed without merging**
