### PR TITLE
Does test-full-bwc work?

### PR DESCRIPTION
**Pull request by DaveCTurner**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against main? Unless there is a good reason otherwise, we prefer pull requests against main and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by mark-vieira** [comment]
I'm hitting the same weird failures in a PR of mine as well after #100401. I've seen weird behavior with `AssumptionViolatedExceptions` being thrown before and it makes no sense. That should not result in a test failure.

**Comment by DaveCTurner** [comment]
Henning helped me pin it down, it's this I think: https://github.com/elastic/elasticsearch/pull/100423

**Comment by mark-vieira** [comment]
> Henning helped me pin it down, it's this I think: #100423

👍 Yeah, I'm seeing failures outside of PR builds as well so it does seem like a real issue: https://github.com/elastic/elasticsearch/pull/100413#issuecomment-1751217937

So I think the answer is `test-full-bwc` does indeed work 😉

**Comment by DaveCTurner** [comment]
Yeah sorry https://github.com/elastic/elasticsearch/pull/100401 was a bit of a rush job to get it into a 8.10.x release. Move fast, break things, right?

**Pull request closed without merging**
