### PR TITLE
[DOCS] Document limits for JSON objects with `ignore_malformed` mapping setting

### LINKED ISSUE #36464: [documentation] Document field type limitations of `ignore_malformed`
**Describe the feature**:
The `ignore_malformed` documentation should document which field types that property is applicable to. For example, the following won't work:
```
PUT test-ignore-mapping
{
  "mappings": {
    "_doc": {
      "properties": {
        "address": {
          "type": "keyword"
        },
        "office_id": {
          "type": "integer"
        }
      }
    }
  },
  "settings": {
    "mapping": {
      "ignore_malformed": "true"
    }
  }
}

POST test-ignore-mapping/_doc/1
{
  "address": "123 Main Street",
  "office_id": 123
}

#this one will fail
POST test-ignore-mapping/_doc/2
{
  "address": {
    "street_number": "123",
    "street": "Main Street"
  },
  "office_id": 123
}
```
Despite `"ignore_malformed": "true"`, indexing the second document will fail with:
```
{
  "error": {
    "root_cause": [
      {
        "type": "mapper_parsing_exception",
        "reason": "failed to parse [address]"
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "failed to parse [address]",
    "caused_by": {
      "type": "illegal_state_exception",
      "reason": "Can't get text on a START_OBJECT at 2:14"
    }
  },
  "status": 400
}
```

### PR DESCRIPTION
**Pull request by jrodewig**
As of this writing,`ignore_malformed` has two undocumented limits for JSON objects:

- `ignore_malformed` does not support datatypes intended for JSON objects, like `range` or `object`
- Other field types support `ignore_malformed` for any JSON data format _except_ JSON objects

This documents those limits. As #12366 notes, support for JSON objects may be added later. We can remove this section then.

Resolves #36464.

### CODE REVIEW

**Review by bczifra — CHANGES_REQUESTED** [review]
The change says:
>You can't use `ignore_malformed` to index JSON objects into field datatypes used
for other data formats, like `text` or `integer`.

`ignore_malformed` isn't used to index values. As the docs currently indicate:
>The ignore_malformed parameter, if set to true, allows the exception to be ignored. The malformed field is not indexed, but other fields in the document are processed normally.

Thus, this should be something more like:
```
You can't use `ignore_malformed` to ignore JSON objects submitted for indexing against fields that were not mapped as objects, nested objects, or ranges. The field will not be ignored, the document will not be indexed, and instead an error will be returned for the indexing request.
```

I don't know whether this limitation is restricted to object, nested object, and range mappings, or whether there are any additional types for which this should be documented.

**Comment by jrodewig** [comment]
@bczifra When convenient and if you approve, do you mind changing your review status from `requested changes` to `approved`? Thanks!

**Review by jimczi — APPROVED** [review]
LGTM

**Review by bczifra — APPROVED** [review]
LGTM

**Pull request merged**
