### PR TITLE
Remove some raw from ActionRequest subclasses

### PR DESCRIPTION
**Pull request by nik9000**
Renames "T" used in many subclasses of ActionRequest to "Self" and tightens
the type bounds.

### CODE REVIEW

**Comment by nik9000** [comment]
All the raw types warnings are getting to me. This feels like a first step to clean them up.

I think the name `Self` is more clear in this case than `T`. `T` just makes me think "generic type that I don't really care about" while `Self` makes me think "the type that `this` has".

**Comment by nik9000** [comment]
@jasontedor do you have an opinion on this? I know you are +1 on warning squashing in general, but what about this particular change?

**Comment by jasontedor** [comment]
@nik9000 I'm good with the change to address the raw types, but the change of the generic parameter type name is [breaking with Java convention](http://docs.oracle.com/javase/tutorial/java/generics/types.html) and I'd prefer to just keep `T` if you're okay with that?

**Comment by nik9000** [comment]
> I'd prefer to just keep T if you're okay with that?

`T` is really confusing to me because its so overused. To me it just means "some generic type that invariable isn't documented". I at least get `E`, `K`, `V`, and even `N` from the java convention. That is one of the java conventions I'm happy to ignore intentionally. We actually do it in lots of places, like `TransportAction` and `ActionListener`.

**Comment by jasontedor** [comment]
Fair enough, but is `Request` okay instead of `Self` then?

**Comment by nik9000** [comment]
> Fair enough, but is `Request` okay instead of `Self` then?

Sure.

**Comment by nik9000** [comment]
@jasontedor renamed!

**Comment by jasontedor** [comment]
LGTM.

**Pull request merged**
