### PR TITLE
Data stream support for open index API

### PR DESCRIPTION
**Pull request by danhermann**
Relates to #53100

### CODE REVIEW

**Comment by danhermann** [comment]
@elasticmachine update branch

**Review by martijnvg — COMMENTED** [review]
Change looks good. I do have second thoughts on whether the open index api should support data streams. Given that the close index api doesn't support data streams (write index can't be closed).
wdyt?

**Comment by danhermann** [comment]
> Change looks good. I do have second thoughts on whether the open index api should support data streams. Given that the close index api doesn't support data streams (write index can't be closed).
> wdyt?

I originally thought the same thing. On further reflection, though, it doesn't necessarily hold that just because "close all backing indices" is invalid for a data stream that "open any closed backing indices" should also be invalid for a data stream. I don't feel especially strong about it, though, so either way is fine by me.

**Review by martijnvg — APPROVED** [review]
> it doesn't necessarily hold that just because "close all backing indices" is invalid for a data stream that "open any closed backing indices" should also be invalid

True. Let's merge this.

**Comment by danhermann** [comment]
@elasticmachine update branch

**Comment by danhermann** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample-unix-docker

**Pull request merged**
