### PR TITLE
Fix race condition in SnapshotsService

### PR DESCRIPTION
**Pull request by volodk85**
Root cause: race condition between *masterService#updateTask* and *clusterApplierService#updateTask* threads on concurrent updates of `snapshotDeletionListeners`.

Test failures contain this exception deep in the logs, (e.g. [here](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+8.10+multijob+platform-support-arm/GRADLE_TASK=checkPart1,os=almalinux-8-aarch64&&immutable/122/consoleFull))

```
15:59:51   1> [2023-10-17T09:58:51,223][ERROR][o.e.c.s.MasterService    ] [node_t0] exception thrown by listener notifying of failure
15:59:51   1> java.util.ConcurrentModificationException: null
15:59:51   1> 	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1605) ~[?:?]
15:59:51   1> 	at java.util.HashMap$ValueIterator.next(HashMap.java:1633) ~[?:?]
15:59:51   1> 	at org.elasticsearch.snapshots.SnapshotsService.failAllListenersOnMasterFailOver(SnapshotsService.java:2466) ~[main/:?]
15:59:51   1> 	at org.elasticsearch.snapshots.SnapshotsService$RemoveSnapshotDeletionAndContinueTask.onFailure(SnapshotsService.java:2521) ~[main/:?]
15:59:51   1> 	at org.elasticsearch.cluster.service.MasterService$ExecutionResult.notifyFailure(MasterService.java:975) ~[main/:?]

```

It can happen when a task is being processed in *masterService* and node gets [cluster state update](https://github.com/elastic/elasticsearch/blob/a95fcfa08f9c673d1f146b59042b518d58574a50/server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java#L845) notifying that the node is not master any longer (as per test logic)

If thrown [here](https://github.com/elastic/elasticsearch/blob/509e961bbc0c9218115f1a12ba50b4a13be5da6f/server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java#L2478), it prevents [proper clean up](https://github.com/elastic/elasticsearch/blob/a95fcfa08f9c673d1f146b59042b518d58574a50/server/src/main/java/org/elasticsearch/snapshots/SnapshotsService.java#L2488) of `currentlyFinalizing` set down the road and hence trips over assert logic in IT test.

Fix: make iterator weakly consistent with backing map collection to tolerate concurrent updates.

#99355

### CODE REVIEW

**Review by arteam — APPROVED** [review]
LGTM! I don't know why `snapshotDeletionListeners` wasn't originally made concurrent analogous to `snapshotCompletionListeners`. I guess we are lucky that some operations on it are performed under `runningDeletions` or `currentlyFinalizing` locks.

I think it makes sense to backport this change all the way to 7.x.

**Review by DaveCTurner — APPROVED** [review]
LGTM nice catch.

I suspect this _only_ happens on a master failover. The rest of the time the master service and cluster applier threads are running in lockstep.

**Comment by volodk85** [comment]
Backported manually in #101688

**Comment by DaveCTurner** [comment]
I'm seeing this fail in 8.11 too:

- https://gradle-enterprise.elastic.co/s/szswm2uvtzari

Going to backport it there

**Pull request merged**
