### PR TITLE
Fix - Make percolator accept positionIncrementGap

### LINKED ISSUE #9386: Percolator is ignoring position_offset_gap
I'm testing span queries on percolator and encountered a problem. It seems that percolator is ignoring position_offset_gap. Below there is an example.

    $ curl "localhost:9200/test1/_mapping/type?pretty" -XPUT -d '{"type" : {"properties" : {"field1" : {"type" : "string", "position_offset_gap" : 100}}}}'
    $ curl "localhost:9200/test1/.percolator" -d '{"type" : "type", "query" : {"span_near" : {"slop" : 90, "clauses" : [{"span_term" : {"field1" : "foo"}}, {"span_term" : {"field1":"bar"}}]}}}'
    {"_index":"test1","_type":".percolator","_id":"sK3bC-XYQ9SQ4qC3SpyXfg","_version":1,"created":true}
    $ curl "localhost:9200/test1/type/_percolate?pretty" -XGET -d '{"doc" : {"field1" : ["foo", "bar"]}}'{
      "took" : 3,
      "_shards" : {
        "total" : 5,
        "successful" : 5,
        "failed" : 0
      },
      "total" : 1,
      "matches" : [ {
        "_index" : "test1",
        "_id" : "sK3bC-XYQ9SQ4qC3SpyXfg"
      } ]
    }

To verify the mapping I also run queries on ES index

    $ curl "localhost:9200/test1/type" -d '{"field1" : ["foo", "bar"]}'
    {"_index":"test1","_type":"type","_id":"HPMTUjVtS0utxr2USt6UGA","_version":1,"created":true}
    $     curl "localhost:9200/test1/type/_search?pretty" -d '{"query" : {"span_near" : {"slop" : 90, "clauses" : [{"span_term" : {"field1" : "foo"}}, {"span_term" : {"field1":"bar"}}]}}}'
    {
      "took" : 6,
      "timed_out" : false,
      "_shards" : {
        "total" : 5,
        "successful" : 5,
        "failed" : 0
      },
      "hits" : {
        "total" : 0,
        "max_score" : null,
        "hits" : [ ]
      }
    }

### PR DESCRIPTION
**Pull request by prog8**
Fixes #9386

### CODE REVIEW

**Comment by clintongormley** [comment]
Hi @prog8 

Thanks for the PR.  Please could I ask you to sign the CLA?
http://www.elasticsearch.org/contributor-agreement/

Also, it would be good to have some tests included with this change.

thanks

**Comment by martijnvg** [comment]
Hey @prog8 this change is still relevant. Would you like to sign the CLA, so this PR can get merged in?

**Comment by prog8** [comment]
I think this is still relevant. Unfortunately i cannot sign CLA. This was thing changed during engagement for customer. I'll ask if they can push this change and I'll revert mine.

**Comment by clintongormley** [comment]
Closing as CLA not signed

**Pull request closed without merging**
