### PR TITLE
Better handling of inline scripts in ingest #23824

### PR DESCRIPTION
**Pull request by asettouf**
I have noticed that any time an inline action would be declared in the list of processors, an error will be thrown as a Map is expected in the _ReadProcessor_ method of ConfigurationUtils. As those errors happen at runtime I added a check in ConfigurationUtils that throws an error if the value is not a map. I added a unit test as well to confirm the behaviour is as expected.

Edit: referencing the issue #23824

### CODE REVIEW

**Comment by rjernst** [comment]
@elasticmachine test this please

**Comment by rjernst** [comment]
@talevy Can you look at this? It appears to throw an error in this case, which from the original issue is a last resort. I think we should support the exact same script parsing that other parts ES support, just as @clintongormley suggested in the issue.

**Comment by talevy** [comment]
I'll take a look at this shortly!

**Comment by talevy** [comment]
@asettouf thanks for the PR! What are your thoughts on modifying the ScriptProcessor to support the short-handed script option? Instead of throwing an exception

**Comment by asettouf** [comment]
@talevy  That would definitely be a better option, as @clintongormley mentioned in the issue, provided there is no urgent deadline regarding this, as I am far from being familiar with script handling. 

By the way, I'm pretty ashamed that I did not test it more thoroughly (obviously I should have spotted this failure in the tests), now my problem in running `gradle check` basically kills my computer for a whole night,  am I doing anything wrong?

**Comment by talevy** [comment]
@asettouf If you are up for it, it would be awesome to have you continue on to extend the ScriptProcessor / configurationutils to support the `{"script": "ctx.foo = 2"}` shorthand.

Otherwise, I can pick this up for you!

hehe, `gradle check` eats up my computer just the same 😄.

To test the relevant ingest code you can filter out many of the other tests and call this:

```
gradle :core:test :modules:ingest-common:test -Dtests.class=org.elasticsearch.ingest.*
```

and may be worth adding a smoke test with the script actually being executed end-to-end

with

```
gradle :qa:smoke-test-ingest-with-all-dependencies:check
```

these two checks should take 1-2min to run and would do a good job covering the changes.

**Comment by asettouf** [comment]
@talevy  This time tests pass correctly and inline scripts are "turned" into a map, thus `readProcessorConfigs` won't throw an exception (the modifications made can be amended to take into account more inline processors).

Tests are passing (thanks for the tip) so let me know if this commit is satisfactory.

Another question I would have is, when working on an issue, others obviously are commiting, so is it better to simply work on a branch, push the commits and later merge with the upstream, or merge the upstream before pushing any commit? (not sure if it's clear though)

**Comment by rjernst** [comment]
Why is this not using Script.parse? That should take care of both cases, and that is what other parts of the code accepting scripts use.

**Comment by talevy** [comment]
@rjernst Script.parse cannot be used since the whole pipeline is made into a map-of-maps, so there is not XContentParser to reference for use by `Script.parse`

**Review by talevy — COMMENTED** [review]
Now that I think about it, maybe it does make sense to re-use the `Script.parse` logic here.
we can build an XContent bytes reference and re-use the `parse` function like this in ConfigurationUtils:

```
   @SuppressWarnings("unchecked")
    public static Script readScript(String processorType, String processorTag, Map<String, Object> configuration,
                                            String propertyName) {
        try {
            XContentBuilder builder = XContentBuilder.builder(JsonXContent.jsonXContent);
            Object scriptObject = configuration.remove(propertyName);
            if (scriptObject instanceof String) {
                builder.value(scriptObject);
            } else {
                builder.map((Map<String, Object>) scriptObject);
            }
            JsonXContentParser parser = new JsonXContentParser(NamedXContentRegistry.EMPTY,
                JSON_FACTORY.createParser(builder.bytes().streamInput()));
            return Script.parse(parser);
        } catch (Exception e) {
            throw newConfigurationException(processorType, processorTag, propertyName, e);
        }
    }
```

**Comment by talevy** [comment]
Hi @asettouf, are you still interested in following up with this PR?

**Comment by asettouf** [comment]
@talevy  No my bad, I'm not on it anymore.

**Comment by talevy** [comment]
that is OK. thanks for the work and thought put into the PR, though! I will try and pick it up from here

**Pull request closed without merging**
