### PR TITLE
Add support for ca-central1 region #22454

### LINKED ISSUE #22454: Add support for ca-central1 region
**Elasticsearch version**:
5.1.1
**Plugins installed**: []
repository-s3
**JVM version**:
1.8
**OS version**:
debian 
**Description of the problem including expected versus actual behavior**:
Linux elasticsearch-datanode1 3.10.0-514.2.2.el7.x86_64 #1 SMP Tue Dec 6 23:06:41 UTC 2016 x86_64 GNU/Linux

**Steps to reproduce**:
 1. Register the repository from elasticsearch
 2. get HTTP 500

I looked at the code, I don't see a switch case for ca-central-1 region. Is that something that can be added quickly? The endpoints are located here: http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region

**Provide logs (if relevant)**:
```
{
  "error": {
    "root_cause": [
      {
        "type": "repository_exception",
        "reason": "[essnapshots] failed to create repository"
      }
    ],
    "type": "repository_exception",
    "reason": "[essnapshots] failed to create repository",
    "caused_by": {
      "type": "illegal_argument_exception",
      "reason": "No automatic endpoint could be derived from region [ca-central-1]"
    }
  },
  "status": 500
}
```

### PR DESCRIPTION
**Pull request by nsaiisasidhar**
Fixes #22454 

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?

### CODE REVIEW

**Comment by animageofmine** [comment]
please consider https://github.com/elastic/elasticsearch/pull/22458 instead since I requested this feature earlier.

**Comment by jasontedor** [comment]
Thanks for the interest in contributing but since @animageofmine already expressed interest in contributing a PR for this in #22454 before this PR was opened, I am closing this in favor of #22458.

**Comment by animageofmine** [comment]
Thank you so much for being fair.

**Review by dadoonet — COMMENTED** [review]
Oh! I totally missed that this one was opened by someone else than @animageofmine. Thank you @jasontedor for taking care of this.

@nsaiisasidhar Thanks a lot for your PR! You are welcomed to contribute to any other issue which is labeled as `adoptme`: https://github.com/elastic/elasticsearch/issues?q=is%3Aopen+is%3Aissue+label%3Aadoptme

**Pull request closed without merging**
