### PR TITLE
Update restore-snapshot-api.asciidoc (#102903)

### PR DESCRIPTION
**Pull request by itsagarverma**
Added Clarification about Stored Scripts:

I added a sentence that explicitly mentions that stored scripts, being part of the global state, will be included in the restoration process. This provides users with a clear understanding of what is included when the global state is restored.

### CODE REVIEW

**Review by itsagarverma — COMMENTED** [review]
Feel free to incorporate this suggestion into your documentation, and if you have any specific terminology or conventions used in your project, adjust the wording accordingly. Additionally, consider seeking feedback from other contributors or maintainers of the project to ensure the clarity and accuracy of the documentation.

**Comment by itsagarverma** [comment]
[💯 ,>doc]

**Review by DaveCTurner — CHANGES_REQUESTED** [review]
Could we just add an item to the `cluster-state-contents` list instead? That way it appears everywhere that we re-use that list.

**Comment by itsagarverma** [comment]
> Could we just add an item to the `cluster-state-contents` list instead? That way it appears everywhere that we re-use that list.

@DaveCTurner , thank you for your feedback! I appreciate your suggestion. I will make the necessary changes and add the item to the `cluster-state-contents` list as you recommended. This way, it will be reflected everywhere that we reuse the list. I'll update the pull request accordingly. If you have any further comments or considerations, please let me know. Thanks again!

**Comment by DaveCTurner** [comment]
Duplicates #102966

**Pull request closed without merging**
