### PR TITLE
Encapsulate SequenceIDFields

### PR DESCRIPTION
**Pull request by nik9000**
This makes the fields in `SequenceIDFields` private so we can modify
them more easily without them being accidentally used by other parts of
the application in incompatible ways.

### CODE REVIEW

**Comment by nik9000** [comment]
run 
elasticsearch-ci/packaging-tests-windows-sample

**Comment by nik9000** [comment]
@elasticmachine update branch

**Comment by nik9000** [comment]
run elasticsearch-ci/packaging-tests-unix-sample

**Review by romseygeek — APPROVED** [review]
LGTM

**Comment by nik9000** [comment]
@elasticmachine, update branch

**Comment by nik9000** [comment]
@elasticmachine update branch

**Pull request merged**
