### PR TITLE
Add link to community Rust Client

### PR DESCRIPTION
**Pull request by russcam**
fix Flummi link

### CODE REVIEW

**Comment by KodrAus** [comment]
:tada:

Should also include a link to: https://github.com/benashford/rs-es which is another client for Rust.

**Comment by russcam** [comment]
@KodrAus If you can summarize the difference and suggest the descriptions, I'll update the PR

**Comment by KodrAus** [comment]
How about:

# rs-es
A REST API client with a strongly-typed Query DSL.

# elastic
A modular REST API client that supports freeform queries.

cc: @benashford

Sorry @russcam I don't mean to derail your original fix!

**Comment by russcam** [comment]
No worries 😄 I'll amend

**Comment by rjernst** [comment]
@russcam This LGTM, do you want to merge and backport?

**Comment by russcam** [comment]
Thanks @rjernst, I'll merge now. Which branches should I backport this to - `5.x` and `5.5`?

**Pull request merged**
