### PR TITLE
Lazily retrieve EngineFactory based on IndexSettings

### PR DESCRIPTION
**Pull request by dakrone**
This commit changes the way that `EngineFactory`s are returned, instead of the
EngineFactory being set at time of shard creation, this changes the pluggability
so that an existing `IndexShard` can return a different engine factory depending
on dynamic index settings.

Relates to #31141

### CODE REVIEW

**Comment by bleskes** [comment]
I would really like to try to avoid having an EngineFactoryFactory (effectively). Maybe we can change EngineFactory.newReadWriteEngine to get an index settings too?

**Comment by dakrone** [comment]
> Maybe we can change EngineFactory.newReadWriteEngine to get an index settings too?

Sure, I think that might be an option, I'll make those changes. However, do we want to rename the method at the same time to just be `newEngine(IndexSettings settings)`? It seems strange to me to be providing engines that may not be read/write from a method named "newReadWriteEngine"

**Comment by dakrone** [comment]
Actually, it looks like this is already possible with the `EngineConfig` containing the settings. I'll look into doing what I need without this change.

**Comment by dakrone** [comment]
Okay, I think we can get away without this. I opened #31745 so I'm closing this for now.

**Pull request closed without merging**
