### PR TITLE
Change the downsample naming scheme to still match DS backing index naming

### PR DESCRIPTION
**Pull request by andreidan**
Appending the interval at the end would break the convention that
the backing index ends with the generation number.

This changes the naming scheme for downsampled indices to
`prefix-interval-sourceIndexName`.

### CODE REVIEW

**Comment by andreidan** [comment]
@elasticmachine update branch

**Comment by andreidan** [comment]
CCS failure

@elasticmachine update branch

**Comment by andreidan** [comment]
@elasticmachine update branch

**Comment by andreidan** [comment]
@elasticmachine update branch

**Review by martijnvg — APPROVED** [review]
LGTM

**Comment by andreidan** [comment]
@elasticmachine update branch

**Comment by andreidan** [comment]
@elasticmachine update branch

**Comment by andreidan** [comment]
@elasticmachine run elasticsearch-ci/packaging-tests-windows-sample

**Pull request merged**
