### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by GlenRSmith**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against main? Unless there is a good reason otherwise, we prefer pull requests against main and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by gbanasiak** [comment]
@GlenRSmith Can you please rebase your changes? https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md#submitting-your-changes

**Comment by kingherc** [comment]
@GlenRSmith could you merge main to your PR? It's hard to check now what this PR has changed.

**Comment by andreidan** [comment]
@GlenRSmith It seems that the merge of the main branch has failed? Not sure why the existing commits have been recreated as part of this PR. I believe your [merge base](https://git-scm.com/docs/gitfaq#long-running-squash-merge) might've been incorrect.
 
Can you please look into this?

**Comment by henningandersen** [comment]
@GlenRSmith 
[This](https://github.com/elastic/elasticsearch/pull/102777/commits/3091caa3e00d772f36c05183d53b5634c44f2824#diff-ba6739944cddd620b432a250354c6c5d5f29218d48670ff94f8143c4a598e5d7R5) looks like the main change, can please either rebase to the main branch or open a new PR with the change?

**Comment by pgomulka** [comment]
@GlenRSmith I think it is easier to close and open a new PR for this change. 
I will close and feel free to open a new one.

**Pull request closed without merging**
