### PR TITLE
Add ingest cluster state listeners

### PR DESCRIPTION
**Pull request by martijnvg**
In the case that an ingest processor factory relies on other configuration
in the cluster state in order to construct a processor instance then
it is currently undetermined if a processor factory can be notified about
a change if multiple cluster state updates are bundled together and
if a processor implement `ClusterStateApplier` interface.
(IngestService implements this interface too)

The idea with ingest cluster state listener is that it is guaranteed to
update the processor factory first before the ingest service creates
a pipeline with their respective processor instances.

Currently this concept is used in the enrich branch:
https://github.com/elastic/elasticsearch/blob/enrich/x-pack/plugin/enrich/src/main/java/org/elasticsearch/xpack/enrich/EnrichProcessorFactory.java#L21

In this case it a processor factory is interested in enrich indices' _meta
mapping fields.

This is the third PR that merges changes made to server module from
the enrich branch (see #32789) into the master branch.

Changes to the server module are merged separately from the pr that will
merge enrich into master, so that these changes can be reviewed in isolation.

Original PR for enrich branch: #42038

### CODE REVIEW

**Review by jakelandis — APPROVED** [review]
LGTM (and thanks for the link to the Enrich branch usage)

**Review by jasontedor — APPROVED** [review]
LGTM, modulo a small Javadoc issue.

**Comment by martijnvg** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by martijnvg** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by martijnvg** [comment]
@elasticmachine update branch

**Pull request merged**
