### PR TITLE
[Synthetics] Add synthetics-* read to fleet-server

### PR DESCRIPTION
**Pull request by emilioalvap**
# Summary

Add read `synthetics-*` privilege for `elastic/fleet-server` service account as per this requirement: https://github.com/elastic/beats/issues/33299

### CODE REVIEW

**Comment by jakelandis** [comment]
It looks like the test failure is related, can you take a look ?

To reproduce: `./gradlew ':x-pack:plugin:security:test' --tests "org.elasticsearch.xpack.security.authc.service.ElasticServiceAccountsTests.testElasticFleetServerPrivileges"`

**Comment by jakelandis** [comment]
@joshdover - are you good with this change ?

**Review by juliaElastic — APPROVED** [review]
LGTM

**Comment by emilioalvap** [comment]
@jakelandis Fleet team has given their approval via @juliaElastic, can we proceed to merge this one in?

**Comment by jakelandis** [comment]
@emilioalvap - I merged the change and will now be part of the 8.6 release. LMK if you need you need to back port this to other releases.

**Comment by emilioalvap** [comment]
@jakelandis Thanks! can we backport this to `8.5` too? It's linked to a PR on the beats repo that has also been backported

**Comment by ywangd** [comment]
I raised a backport PR to 8.5 https://github.com/elastic/elasticsearch/pull/91572

**Pull request merged**
