### PR TITLE
Compatible REST API - minor build clean up

### PR DESCRIPTION
**Pull request by jakelandis**
This commit allows the compatible REST API tests to execute on Windows.
They were previously excluded from Windows due to a command line limit
when defining a very large exclusion list. That exclusion list is much 
smaller now and they will now execute properly on Windows. 

Also, an empty exclusion list has been removed from the build config.

### CODE REVIEW

**Comment by jakelandis** [comment]
@elasticmachine update branch

**Review by mark-vieira — APPROVED** [review]
:+1:

**Comment by jakelandis** [comment]
@elasticmachine run elasticsearch-ci/packaging-tests-windows-sample

**Comment by jakelandis** [comment]
Thanks Mark!

**Pull request merged**
