### PR TITLE
First step towards separating individual search phases

### PR DESCRIPTION
**Pull request by s1monw**
At this point AbstractSearchAsyncAction is just a base-class for the first phase of a search where we have multiple replicas
for each shardID. If one of them is not available we move to the next one. Yet, once we passed that first stage we have to work with
the shards we succeeded on the initial phase.
Unfortunately, subsequent phases are not fully detached from the initial phase since they are all non-static inner classes.
In future changes this will be changed to detach the inner classes to test them in isolation and to simplify their creation.
The AbstractSearchAsyncAction should be final and it should just get a factory for the next phase instead of requiring subclasses
etc.

### CODE REVIEW

**Comment by s1monw** [comment]
@elasticmachine test this please

**Review by jpountz — APPROVED** [review]
+1 to detaching phases to make them easier to test/reason about. It is hard to dig into such a change but I got the idea and did not see anything bad, so if tests are passing I'm confident this is good. :+1:

**Comment by s1monw** [comment]
@elasticmachine test this please

**Comment by s1monw** [comment]
@elasticmachine test this please

**Comment by s1monw** [comment]
@elasticmachine test this please

**Comment by s1monw** [comment]
@elasticmachine would you mind to f***ing test this at least once?

**Pull request merged**
