### PR TITLE
Update completion-suggest.asciidoc

### PR DESCRIPTION
**Pull request by gitanupam**
Minor change in the shorthand form text.

### CODE REVIEW

**Review by nik9000 — APPROVED** [review]
Makes sense to me. I'll merge when I get a chance.

**Comment by nik9000** [comment]
Whoops! The CLA check failed. We need a signed CLA before we can merge anything, no matter what. @gitanupam, can you sign the CLA and comment on the PR again when you have?

**Comment by gitanupam** [comment]
Hmm, pretty sure I did it and saw a confirmation here as well. Will try again.

**Comment by nik9000** [comment]
> Hmm, pretty sure I did it and saw a confirmation here as well. Will try again.

Looks fine now. I'm not sure. Maybe I just needed to reload the page. I'll merge now.

**Comment by nik9000** [comment]
Merged to 5.4 and cherry-picked to 5.x and master. Thanks @gitanupam!

**Pull request merged**
