### PR TITLE
[8.0] Reintroduce full index compatible testing of full cluster restart (#82506)

### PR DESCRIPTION
**Pull request by mark-vieira**
Backports the following commits to 8.0:
 - Reintroduce full index compatible testing of full cluster restart (#82506)

### CODE REVIEW

**Comment by mark-vieira** [comment]
@elasticmachine run elasticsearch-ci/full-bwc

**Comment by mark-vieira** [comment]
@elasticmachine update branch

**Comment by mark-vieira** [comment]
@elasticmachine update branch

**Comment by mark-vieira** [comment]
@elasticmachine update branch

**Comment by breskeby** [comment]
@elasticmachine update branch

**Comment by mark-vieira** [comment]
@elasticmachine update branch

**Comment by mark-vieira** [comment]
@elasticmachine update branch

**Comment by mark-vieira** [comment]
@elasticmachine update branch

**Pull request merged**
