### PR TITLE
Fix weighted_avg parser not found for RestHighLevelClient

### PR DESCRIPTION
**Pull request by xpando**
This PR fixes the parser not found exception reported in this issue: https://github.com/elastic/elasticsearch/issues/36861

I created an integration test for weighted average which reproduced the error. The fix is to simply add the missing weighted average parser to the RestHighLevelClient `DefaultNamedXContents`. 

I had to make `ParsedWeightedAvg` public. I'm not sure why it wasn't already when all the other aggregations are public. This is not an issue in the 6.5 branch.

### CODE REVIEW

**Comment by elasticcla** [comment]
Hi @xpando, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/elasticsearch/pull/37027.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by javanna** [comment]
jenkins test this please

**Comment by javanna** [comment]
retest this please

**Comment by xpando** [comment]
Sorry about that. I pushed a commit that fixes the failing unit test.

I had originally modified the 6.5 branch and I missed one line in the InternalAggregationTestCase class when I moved the code over to master before submitting the PR.

**Comment by javanna** [comment]
no worries @xpando thanks for fixing that.

**Comment by javanna** [comment]
retest this please

**Comment by xpando** [comment]
Ok, so it seems that there is not already an InternalWeightedAvg unit test. I'll have to dig into creating that test for this to continue. I'll push another update once I have something.

Do you think it is sufficient to run `./gradlew unitTest`? It seems I don't have all the infrastructure needed to run `./gradlew check`

**Comment by xpando** [comment]
I added the missing InternalWeightedAvgTests and now the server unit test suites pass.

**Comment by javanna** [comment]
retest this please

**Comment by javanna** [comment]
hi @xpando there's a checkstyle violation now that makes the build fail:

```
10:05:02 > Task :server:checkstyleTest FAILED
10:05:02 [ant:checkstyle] [ERROR] /var/lib/jenkins/workspace/elastic+elasticsearch+pull-request-1/server/src/test/java/org/elasticsearch/search/aggregations/metrics/InternalWeightedAvgTests.java:34: Line is longer than 140 characters (found 143). [LineLength]
```

you can run `./gradlew precommit` to check that once you fixed the violation. Thanks!

**Comment by xpando** [comment]
Thanks @javanna. Checkstyle is now passing. Please give it another try,

**Comment by javanna** [comment]
retest this please

**Comment by hub-cap** [comment]
ty for the assign @javanna <3

**Comment by javanna** [comment]
I think it looks good @hub-cap and tests are green, but I wanted to make sure I am not missing anything.

**Review by hub-cap — APPROVED** [review]
yes it does, im just doing the test verification / running some iters before merging it. great work @xpando

**Comment by hub-cap** [comment]
Backported to `6.x` ce9fcc9441099ce58679078d595744e42af854e6

**Pull request merged**
