### PR TITLE
Remove transport client from xpack

### PR DESCRIPTION
**Pull request by rjernst**
his commit removes support for the transport client from xpack.

### CODE REVIEW

**Comment by cjcenizal** [comment]
@rjernst This PR is labeled breaking but I'm not familiar with the code/feature that's being changed. Would you mind adding some details to the PR description to help me understand what's being changed from a consumer's standpoint? I'd like to make sure nothing in our apps will be affected by this change. Thanks!

**Comment by rjernst** [comment]
@cjcenizal This only affects developers interacting with Elasticsearch through Java. There are two clients in java that provide typed requests, the transport client, and the new high level rest client. In 7.0, we deprecated use of the transport client (https://github.com/elastic/elasticsearch/pull/27085), with the intention for users to migrate to the high level rest client. This is the beginning of the followup there to remove the transport client in 8.0. It is such a large task that I am doing it in several PRs. When that is complete, I will add a breaking changes section noting the removal.

**Comment by cjcenizal** [comment]
Thank you @rjernst!

**Comment by rjernst** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by jaymode** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by rjernst** [comment]
@elasticmachine run elasticsearch-ci/1
@elasticmachine run elasticsearch-ci/2

**Review by s1monw — APPROVED** [review]
awesome!

**Comment by s1monw** [comment]
@rjernst should we use `breaking-java` as a label instead?

**Comment by jaymode** [comment]
`PreventFailingBuildIT` failure was real due to the changes made for ExternalTestCluster here. I pushed a fix and also opened #42439 as this QA project is not doing anything and hasn't been for over a year.

**Comment by jaymode** [comment]
@elasticmachine run elasticsearch-ci/1
@elasticmachine run elasticsearch-ci/packaging-sample

**Pull request merged**
