### PR TITLE
Allow deletion of async searches with the manage privilege

### PR DESCRIPTION
**Pull request by jimczi**
This change allows users that do not initiated an async search to delete it
if they have the cluster manage and manage-security privileges.
It is equivalent to the cancellation of tasks through the task manager (same privilege required)
and will allow users with the right permissions to cancel/delete async searches if they know
the async execution id.

### CODE REVIEW

**Comment by mark-vieira** [comment]
@elasticmachine update branch

**Review by albertzaharovits — APPROVED** [review]
LGTM
We discussed that we (Security) must investigate how to do authorization around requests that contain handlers that have ownership, so that we don't pollute the async tasks logic with authorization checks.

I will raise an issue.

**Comment by lizozom** [comment]
@jimczi do we need anything else to grant this permission to the kibana user? Or does it already have it?

**Comment by jimczi** [comment]
@lizozom , not yet. This PR allows any user with the manage privilege to delete async searches. I'll open a follow up to determine how the kibana_system could have this privilege by default.

**Comment by lizozom** [comment]
Please share the PR with me for tracking :pray:

**Comment by jimczi** [comment]
@lizozom I opened https://github.com/elastic/elasticsearch/pull/68679 for the kibana_system role.

**Pull request merged**
