### PR TITLE
Fix Docker image name.

### PR DESCRIPTION
**Pull request by joshuar**
We were still referring to the pre 6.3 image names, adjusted for 6.3+ image names.

### CODE REVIEW

**Review by lcawl — APPROVED** [review]
LGTM

**Comment by joshuar** [comment]
Hmm, this PR seemed to fail CI.  I'm not sure how to fix that.  Any pointers?

**Comment by lcawl** [comment]
The CI errors don't seem to be related to this change. When this happens in my PRs, I typically rebase my work (which causes CI to run again) and find that the problem has been fixed elsewhere.

**Comment by joshuar** [comment]
Hmm, my git-fu is failing me. I tried rebasing on the latest master but I constantly get merge conflicts.  I'm not sure what I can do to resolve these, as they are for files unrelated to the changes made in this PR.  Any advice @lcawl?

**Comment by tvernum** [comment]
@joshuar Did you mean this literally?

> I tried rebasing on the latest master

This PR is against `6.3` so you should be rebasing on that branch.
Although, in general we prefer that you PRs authors merge the upstreeam (in this case `6.3`) into the PR's branch rather than doing an actual `rebase` (it makes it easier to track what has changed between reviews)

All you should need to do is something like
```
git checkout 6.3
git pull
git checkout docs-docker-tls-fix
git merge 6.3
git push
 ```

**Comment by joshuar** [comment]
Thanks @tvernum that seems to have worked!

**Pull request merged**
