### PR TITLE
Sync grok processor patterns with Logstash

### PR DESCRIPTION
**Pull request by danhermann**
Brings over a few new patterns and pattern updates from Logstash's grok filter. Also moves the `httpd` patterns out of the `grok-patterns` file and into their own file so they correspond exactly to the Logstash pattern files and are easier to keep in sync.

### CODE REVIEW

**Comment by danhermann** [comment]
@elasticmachine run elasticsearch-ci/rest-compatibility

**Comment by danhermann** [comment]
@elasticmachine run elasticsearch-ci/rest-compatibility

**Comment by danhermann** [comment]
@elasticmachine update branch

**Comment by danhermann** [comment]
@elasticmachine update branch

**Comment by danhermann** [comment]
@elasticmachine update branch

**Review by martijnvg — APPROVED** [review]
LGTM

**Comment by danhermann** [comment]
Thanks, @martijnvg!

**Pull request merged**
