### PR TITLE
[DOCS] Remove Rollup API docs from ToC in favour of Downsampling

### LINKED ISSUE #90065: [DOCS] Remove Rollup API pages in favour of Downsampling API
The existing Rollup API reference pages should be removed in favour of docs for the new downsampling feature. See [the original comment here](https://github.com/elastic/elasticsearch/pull/88571#issuecomment-1233475660), copied below.

Rel: #88571

---
The existing Rollup API docs are unrelated to the new downsample née rollup API. Recommend adding a new downsample API ref page and removing the existing Rollup API ref pages from the TOC. While they have yet to be deprecated, we don't want additional folks to start using v1 Rollups.

As a follow-on, I think we should promote Transforming data to the top level & move [Rolling up historical data](https://www.elastic.co/guide/en/elasticsearch/reference/current/xpack-rollup.html) to the Appendix & exclude it from the TOC. Should also add a cross reference to the new downsampling info for the folks who do find that page.

To exclude a topic from the TOC, add role="exclude" to the anchor like we do for the [redirects](https://github.com/elastic/elasticsearch/edit/8.4/docs/reference/redirects.asciidoc).

### PR DESCRIPTION
**Pull request by kilfoyle**
This removes entries for the Rollup API and related docs from the Elasticsearch ToC. Since rollups have yet to be deprecated the content is still available in the Appendix section.

This also adds admonitions at the top of the rollups docs.

For the rollup API docs:
Screen Shot 2022-10-18 at 1 06 46 PM

For the other rollup pages:
Screen Shot 2022-10-18 at 1 13 22 PM

 - [x] Move [Rolling up historical data](https://www.elastic.co/guide/en/elasticsearch/reference/current/xpack-rollup.html) and sub-pages to the appendix and remove from ToC.
 - [x] Create redirect for unneeded [Rollup or transform your data](https://www.elastic.co/guide/en/elasticsearch/reference/current/data-rollup-transform.html).
 - [x] Promote [Transforming data](https://www.elastic.co/guide/en/elasticsearch/reference/current/transforms.html) to the top level (fix level offsets, links, etc.).
 - [x] Move [Rollup API docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/rollup-apis.html) to the appendix and remove from ToC (fix links, etc.).
 - [x] Add a note to all Rollup docs referring folks to the downsampling pages.

Closes: #90065

### CODE REVIEW

**Review by lockewritesdocs — APPROVED** [review]
Nice work @kilfoyle! Overall, these changes LGTM. The one change I would consider making is to remove the `experimental[]` admonition from each of the [rollup API](https://elasticsearch_90894.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/rollup-apis.html) pages. I don't think it's necessary now that you've added the admonition that points users to the downsample index API.

**Comment by kilfoyle** [comment]
@csoulios Just wanted to copy you on this PR in case you have any concerns. This hides the old Rollup API docs from the Table of Contents, and updates each of the Rollup API pages to point folks to the new downsampling docs.

**Comment by kilfoyle** [comment]
@elasticmachine update branch

**Review by csoulios — COMMENTED** [review]
@kilfoyle thanks for including me in this PR. 

I find it a very good idea to start pointing to downsampling as the recommended method to reduce disk storage from `v8.5.0` onwards. However, I don't think we are at a point that we can fully decommission the experimental rollups that we have been providing for so long.

Perhaps after the TSDB downsampling feature has been GA-ed (currently it's Tech Preview), we can follow a deprecation process for rollups. Then give our users the time to migrate away from it and finally remove the rollups feature.

cc @giladgal

**Comment by kilfoyle** [comment]
Thanks for the suggestions! Closing in favour of https://github.com/elastic/elasticsearch/pull/91295

**Pull request closed without merging**
