### PR TITLE
Fix BulkItemResponse.Failure.toString

### PR DESCRIPTION
**Pull request by nik9000**
It was busted and causing intermittent test failures.

### CODE REVIEW

**Comment by nik9000** [comment]
Anyone want to have a look a this? @jpountz, I believe Strings.toString is yours?

**Comment by jpountz** [comment]
This looks good as is, but I wonder if we could make BulkItemResponse's toXContent write the outer object (and fix call sites accordingly) so that we do not need this additional boolean?

**Comment by dakrone** [comment]
It looks like @martijnvg just fixed this in master already: https://github.com/elastic/elasticsearch/commit/935ccb13043e1064d512bc3a45ea12e7749f083a

**Comment by nik9000** [comment]
I think the issue is the BulkItemResponse.Failure just loves to be embedded in stuff which is why it doesn't emit the object. I *know* we have others that do that kind of thing which is why I added the boolean rather than tried for a fix right on BulkItemResponse.Failure. I agree it isn't a nice way to behave though.

**Comment by martijnvg** [comment]
@nik9000 I reverted the change. This change looks good. 

@jpountz I think we can't change that without changing the actual format?

**Comment by nik9000** [comment]
Ok! I've merged this but I'd be happy for someone to get us to the point where we don't need it. ToXContent's contract isn't really strict enough I think and I'd love to go on a hunt for all the bad implementers but I'm on other quests right now!

**Comment by jpountz** [comment]
Fine with me.

**Pull request merged**
