### PR TITLE
Support Vagrant 2.x in vagrantVersionCheck

### LINKED ISSUE #26562: vagrantVersionCheck should support Vagrant 2.x
**Describe the feature**:

Vagrant 2.0.0 was released on September 7, 2017. The `vagrantVersionCheck` only checks for 1.8.x and 1.9.x versions.

### PR DESCRIPTION
**Pull request by risdenk**
Closes #26562

### CODE REVIEW

**Comment by jasontedor** [comment]
Thanks for the PR @risdenk. Do the packaging tests pass with this change?

**Comment by jasontedor** [comment]
I ran the packaging tests locally after installing Vagrant 2.0.0 and everything worked as expected.

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by jasontedor** [comment]
Thanks again @risdenk.

**Comment by risdenk** [comment]
Thanks @jasontedor!

**Pull request merged**
