### PR TITLE
Add a Duration Processor implementation

### PR DESCRIPTION
**Pull request by jbaiera**
This processor allows for human readable durations (e.g. `5s`) to be converted into a value representing the duration in milliseconds (e.g. `5000`). The processor can be configured to convert the duration into a time unit other than `milliseconds`. 

This processor makes use of the `TimeValue.parseTimeValue(String, String)` method to parse the given field value into an instance of `TimeValue` before converting it into a number of milliseconds (or other configured time unit).

In order to support some general monitoring use cases, the `TimeValue` class has been modified to accept fractional time values, with additional guards in place to avoid long overflow/underflow when converting large units.

### CODE REVIEW

**Comment by jasontedor** [comment]
>In order to support some general monitoring use cases, the `TimeValue` class has been modified to accept fractional time values, with additional guards in place to avoid long overflow/underflow when converting large units.

It was deliberate that `TimeValue` does not support fractional time values. Can we discuss this?

**Comment by jbaiera** [comment]
> It was deliberate that TimeValue does not support fractional time values. Can we discuss this?

I had a feeling that was the case. One of the main drivers for supporting the fractional time values was that this processor may be used for monitoring Elasticsearch itself, which may occasionally report time values in fractional format. Perhaps it makes sense to move the fractional parsing to the processor only?

**Comment by jasontedor** [comment]
That would be my inclination if we absolutely must do this, but I think we should consider changing Elasticsearch so that it doesn't report fractional time values in these APIs.

**Comment by jbaiera** [comment]
relates #39857

**Comment by jbaiera** [comment]
One of the driving factors, for reference: https://github.com/elastic/beats/pull/9603

Looking into the service, the TimeValue's toString method is relied on for logging these events. I wouldn't be surprised if that were the case in countless other places.

Maybe we should have a discussion about breaking out the `toString` method in `TimeValue` to explicitly report its time unit, but have a separate `prettyPrint()`-like method for rendering the human friendly representation?

**Comment by jbaiera** [comment]
Closing this PR for now. There's quite a bit of contention around parsing fractional time values. In order to solve the original problem it would probably be better to remove the logging of fractional time values and simply log the un-formatted time value in places where it might need to be captured for further processing.

**Pull request closed without merging**
