### PR TITLE
Consolidate some reindex utility classes

### PR DESCRIPTION
**Pull request by nik9000**
Everything that extended `AbstractAsyncBulkByScrollAction` also
extended `AbstractAsyncBulkIndexByScrollAction` so this removes
`AbstractAsyncBulkIndexByScrollAction`, merging it into
`AbstractAsyncBulkByScrollAction`.

I'd like to get this before doing #22616.

### CODE REVIEW

**Review by jasontedor — APPROVED** [review]
Is this just mechanical? It looks mechanical so LGTM in that regard. If it's not mechanical and something deserves a closer review, please let me know?

**Review by tlrx — APPROVED** [review]
I did a 3-ways comparison and it looks good, just things moved here and there and the buildBulk() method that changed a bit.

**Comment by nik9000** [comment]
> Is this just mechanical

Almost entirely mechanical but a bit messy anyway. I hadn't do it for a while because it is so messy but if I'm going to move these into core I'd like to clean them up a bit first.

**Comment by nik9000** [comment]
Thanks for reviewing @tlrx and @jasontedor!

master: ee5f8c452264d47181600d00427b32d08b0d60e2
5.x: 0325ae4b8a31854ca5021030b113387ebe5d3b52

**Pull request merged**
