### PR TITLE
[ML-DataFrame] fix test failure in checkpoint retrieval

### LINKED ISSUE #45238: test failure org.elasticsearch.xpack.dataframe.checkpoint.DataFrameTransformCheckpointServiceNodeTests » testGetCheckpointStats
## Example build failure
https://scans.gradle.com/s/q6iig7skusihw/tests/pzhjuvhaoog6w-fxij42n4odxkk

## Reproduction line 
does not reproduce locally
```
./gradlew :x-pack:plugin:data-frame:test --tests "org.elasticsearch.xpack.dataframe.checkpoint.DataFrameTransformCheckpointServiceNodeTests.testGetCheckpointStats" -Dtests.seed=31B7CC998CFE5D73 -Dtests.security.manager=true -Dtests.locale=fr-MA -Dtests.timezone=Australia/Lindeman -Dcompiler.java=12 -Druntime.java=11
HomeTestsDataFrameTransformCheckpointServiceNodeTests » testGetCheckpointStatsClose test output (esc)
```

## Example relevant log:
```
com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=46, name=elasticsearch[node_s_0][get][T#1], state=RUNNABLE, group=TGRP-DataFrameTransformCheckpointServiceNodeTests]Close stacktrace
at __randomizedtesting.SeedInfo.seed([31B7CC998CFE5D73:1763BD35BF5C2F56]:0)
Caused by: java.lang.AssertionError: got unexpected exception: Failure during source checkpoint info retrievalClose stacktrace
at __randomizedtesting.SeedInfo.seed([31B7CC998CFE5D73]:0)
at org.junit.Assert.fail(Assert.java:88)
at org.elasticsearch.xpack.dataframe.DataFrameSingleNodeTestCase.lambda$assertAsync$2(DataFrameSingleNodeTestCase.java:66)
at org.elasticsearch.action.ActionListener$1.onFailure(ActionListener.java:70)
at org.elasticsearch.action.LatchedActionListener.onFailure(LatchedActionListener.java:50)
at org.elasticsearch.xpack.dataframe.checkpoint.DefaultCheckpointProvider.lambda$getCheckpointingInfo$10(DefaultCheckpointProvider.java:275)
at org.elasticsearch.action.ActionListener$1.onFailure(ActionListener.java:70)
at org.elasticsearch.xpack.dataframe.checkpoint.DefaultCheckpointProvider.lambda$getIndexCheckpoints$4(DefaultCheckpointProvider.java:169)
at org.elasticsearch.action.ActionListener$1.onFailure(ActionListener.java:70)
at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:64)
at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43)
at org.elasticsearch.xpack.dataframe.checkpoint.DataFrameTransformCheckpointServiceNodeTests$MockClientForCheckpointing.doExecute(DataFrameTransformCheckpointServiceNodeTests.java:103)
at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:377)
at org.elasticsearch.xpack.core.ClientHelper.executeAsyncWithOrigin(ClientHelper.java:89)
at org.elasticsearch.xpack.core.ClientHelper.executeWithHeadersAsync(ClientHelper.java:152)
at org.elasticsearch.xpack.dataframe.checkpoint.DefaultCheckpointProvider.getIndexCheckpoints(DefaultCheckpointProvider.java:145)
at org.elasticsearch.xpack.dataframe.checkpoint.DefaultCheckpointProvider.lambda$getCheckpointingInfo$11(DefaultCheckpointProvider.java:283)
at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62)
at org.elasticsearch.xpack.dataframe.persistence.DataFrameTransformsConfigManager.parseCheckpointsLenientlyFromSource(DataFrameTransformsConfigManager.java:393)
at org.elasticsearch.xpack.dataframe.persistence.DataFrameTransformsConfigManager.lambda$getTransformCheckpoint$3(DataFrameTransformsConfigManager.java:158)
at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:62)
at org.elasticsearch.action.support.ContextPreservingActionListener.onResponse(ContextPreservingActionListener.java:43)
at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:70)
at org.elasticsearch.action.support.TransportAction$1.onResponse(TransportAction.java:64)
at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction$2.handleResponse(TransportSingleShardAction.java:261)
at org.elasticsearch.action.support.single.shard.TransportSingleShardAction$AsyncSingleAction$2.handleResponse(TransportSingleShardAction.java:247)
at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1100)
at org.elasticsearch.transport.TransportService$DirectResponseChannel.processResponse(TransportService.java:1178)
at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1158)
at org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:54)
at org.elasticsearch.action.support.ChannelActionListener.onResponse(ChannelActionListener.java:47)
at org.elasticsearch.action.support.ChannelActionListener.onResponse(ChannelActionListener.java:30)
at org.elasticsearch.action.support.single.shard.TransportSingleShardAction.lambda$asyncShardOperation$0(TransportSingleShardAction.java:110)
at org.elasticsearch.action.ActionRunnable$1.doRun(ActionRunnable.java:45)
at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:769)
at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.lang.Thread.run(Thread.java:834)
```

## Frequency

### PR DESCRIPTION
**Pull request by hendrikmuhs**
gracefully handle if index response returns null, increase and assert timeout

closes #45238

### CODE REVIEW

**Comment by hendrikmuhs** [comment]
run elasticsearch-ci/2

**Comment by hendrikmuhs** [comment]
run elasticsearch-ci/2

**Comment by hendrikmuhs** [comment]
run elasticsearch-ci/2

**Comment by hendrikmuhs** [comment]
run elasticsearch-ci/2

**Comment by hendrikmuhs** [comment]
Back to work in progress, the issue happened again, unfortunately now that I put the loglevels back to debug.

**Review by przemekwitek — APPROVED** [review]
LGTM

**Pull request merged**
