### PR TITLE
Make the the number of ports to scan when trying to join a cluster configurable, and set the default to 2.

### LINKED ISSUE #7090: Increase `UnicastZenPing.LIMIT_PORTS_COUNT` to `2`
As described in https://github.com/elasticsearch/elasticsearch-cloud-aws/issues/99, we should increase `UnicastZenPing.LIMIT_PORTS_COUNT` to `2` instead of `1` today.

It should be a modifiable setting in case of users needs to run more instances on the same physical box, for example 2 data nodes on a 128gb RAM machine, one client node and one master only node.

### PR DESCRIPTION
**Pull request by ejain**
Closes #7090

### CODE REVIEW

**Comment by bleskes** [comment]
@ejain sorry for the long wait. Will you be willing to pick this one up again? It looks good,but misses a test (maybe expose configuredTargetNode as a package private getter and add a unit test UnicastZenPingTests).

**Comment by ejain** [comment]
I'd be happy to add a test, but since this isn't a trivial unit test, and I'm not familiar with elasticsearch's test scaffolding, it might be a while before I get to have a look.

**Comment by bleskes** [comment]
@ejain I think we can make it a basic unit test (inheriting from ElasticsearchTestCase ), with my suggestion above: 

> maybe expose configuredTargetNode as a package private getter and add a unit test to UnicastZenPingTests

That means you just need to instantiate UnicastZenPing with two different settings and see that number of hosts is good, plus that the ports is what you expect.

Let me know if you don't have time for this (it has been a while). I can pick it up , but please do sign the CLA so I can take your PR as a base (see https://www.elastic.co/contributing-to-elasticsearch )

**Comment by ejain** [comment]
Signed the CLA. Feel free to pick this up, could be a few weeks before I'm able to get back to this.

**Comment by drekbour** [comment]
I've just followed half a dozen issues through to this one which appears to be the leading edge of this problem. Since the current state of play has not been changed in several years, can you at least correct the public documentation which still clearly describes using port ranges although everyone on the ES side knows they are ignored.
https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-discovery-zen.html

**Comment by bleskes** [comment]
@drekbour agreed the documentation is confusing. Parsing ranges is mostly there to be able to work out of the box with the default transport settings which use 9300-9400 . Not sure much for external configuration. Agreed it's super confusing now. Do you mind opening a new issue as this PR tries to do something else, which is make it configurable. I believe that's the wrong approach. We should document what we do - not support ranges when specified and default to the first 5 local ports when not configured.

**Comment by clintongormley** [comment]
The networking code has changed considerably, and the documentation has been updated to reflect the current state.  Closing

**Pull request closed without merging**
