### PR TITLE
[ML] Swallow the model size stats allocation bytes field

### PR DESCRIPTION
**Pull request by davidkyle**
#109833 added handling for the new `output_memory_allocator_bytes` field in the anomaly detection model size stats. The change was reverted due to an incompatibility in the wire protocol but the C++ side will still write the `output_memory_allocator_bytes` field and it must be parsed by Elasticsearch. This change reintroduces the parsing of the field but it is discarded without any further processing.

### CODE REVIEW

**Review by valeriy42 — APPROVED** [review]
LGTM

**Comment by davidkyle** [comment]
test this please

**Comment by davidkyle** [comment]
@elasticmachine update branch

**Review by edsavage — APPROVED** [review]
LGTM - Thanks Dave

**Pull request merged**
