### PR TITLE
[DOCS] Add 7.13.4 security notice

### PR DESCRIPTION
**Pull request by jrodewig**
### Preview
https://elasticsearch_75538.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/current/release-notes-7.13.4.html

### CODE REVIEW

**Comment by colings86** [comment]
@joshbressers @douglasday Can you review here too?

**Comment by douglasday** [comment]
@jrodewig / @colings86 - Only question is if we want to link to the CVE on Mitre if that link isn't live yet. (I will be issuing the CVE to Mitre today and it will take them a little bit to get it published).

**Comment by douglasday** [comment]
Otherwise, this looks verbatim from the advisory 👍 LGTM

**Comment by jrodewig** [comment]
> Otherwise, this looks verbatim from the advisory

It is. 😄  Thanks @douglasday!

**Pull request merged**
