### PR TITLE
Reenable azure repository tests and lower down max error per request

### LINKED ISSUE #47380: AzureBlobStoreRepositoryTests.testSnapshotWithLargeSegmentFiles fails on 7.x with Internal Server Error
The failure looks like it's coming from the Azure plugin:

```
  1> [2019-10-01T16:32:40,341][WARN ][o.e.r.VerifyNodeRepositoryAction] [node_sd1] [zcsoxknmm] failed to verify repository
  1> org.elasticsearch.repositories.RepositoryVerificationException: [zcsoxknmm] store location [container] is not accessible on the node [{node_sd1}{38kFyoC3RuSBjX_rgphzjQ}{cO84XnveTPafOEcEqSWK3w}{127.0.0.1}{127.0.0.1:39435}{di}]
  1> 	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.verify(BlobStoreRepository.java:1211) ~[elasticsearch-7.5.0-SNAPSHOT.jar:7.5.0-SNAPSHOT]
  1> 	at org.elasticsearch.repositories.VerifyNodeRepositoryAction.doVerify(VerifyNodeRepositoryAction.java:126) ~[elasticsearch-7.5.0-SNAPSHOT.jar:7.5.0-SNAPSHOT]
  1> 	at org.elasticsearch.repositories.VerifyNodeRepositoryAction.access$400(VerifyNodeRepositoryAction.java:49) ~[elasticsearch-7.5.0-SNAPSHOT.jar:7.5.0-SNAPSHOT]
  1> 	at org.elasticsearch.repositories.VerifyNodeRepositoryAction$VerifyNodeRepositoryRequestHandler.messageReceived(VerifyNodeRepositoryAction.java:158) [elasticsearch-7.5.0-SNAPSHOT.jar:7.5.0-SNAPSHOT]
  1> 	at org.elasticsearch.repositories.VerifyNodeRepositoryAction$VerifyNodeRepositoryRequestHandler.messageReceived(VerifyNodeRepositoryAction.java:153) [elasticsearch-7.5.0-SNAPSHOT.jar:7.5.0-SNAPSHOT]
  1> 	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:63) [elasticsearch-7.5.0-SNAPSHOT.jar:7.5.0-SNAPSHOT]
  1> 	at org.elasticsearch.transport.InboundHandler$RequestHandler.doRun(InboundHandler.java:264) [elasticsearch-7.5.0-SNAPSHOT.jar:7.5.0-SNAPSHOT]
  1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:773) [elasticsearch-7.5.0-SNAPSHOT.jar:7.5.0-SNAPSHOT]
  1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.5.0-SNAPSHOT.jar:7.5.0-SNAPSHOT]
  1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_221]
  1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_221]
  1> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
  1> Caused by: java.io.IOException: Can not write blob data-38kFyoC3RuSBjX_rgphzjQ.dat
  1> 	at org.elasticsearch.repositories.azure.AzureBlobContainer.writeBlob(AzureBlobContainer.java:104) ~[main/:?]
  1> 	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.verify(BlobStoreRepository.java:1208) ~[elasticsearch-7.5.0-SNAPSHOT.jar:7.5.0-SNAPSHOT]
  1> 	... 11 more
  1> Caused by: com.microsoft.azure.storage.StorageException: Internal Server Error
  1> 	at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:87) ~[azure-storage-8.0.0.jar:?]
  1> 	at com.microsoft.azure.storage.core.StorageRequest.materializeException(StorageRequest.java:313) ~[azure-storage-8.0.0.jar:?]
  1> 	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:185) ~[azure-storage-8.0.0.jar:?]
  1> 	at com.microsoft.azure.storage.blob.CloudBlockBlob.uploadFullBlob(CloudBlockBlob.java:938) ~[azure-storage-8.0.0.jar:?]
  1> 	at com.microsoft.azure.storage.blob.CloudBlockBlob.upload(CloudBlockBlob.java:768) ~[azure-storage-8.0.0.jar:?]
  1> 	at org.elasticsearch.repositories.azure.AzureStorageService.lambda$writeBlob$15(AzureStorageService.java:333) ~[main/:?]
  1> 	at org.elasticsearch.repositories.azure.SocketAccess.lambda$doPrivilegedVoidException$0(SocketAccess.java:64) ~[main/:?]
  1> 	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_221]
  1> 	at org.elasticsearch.repositories.azure.SocketAccess.doPrivilegedVoidException(SocketAccess.java:63) ~[main/:?]
  1> 	at org.elasticsearch.repositories.azure.AzureStorageService.writeBlob(AzureStorageService.java:332) ~[main/:?]
  1> 	at org.elasticsearch.repositories.azure.AzureBlobStore.writeBlob(AzureBlobStore.java:120) ~[main/:?]
  1> 	at org.elasticsearch.repositories.azure.AzureBlobContainer.writeBlob(AzureBlobContainer.java:102) ~[main/:?]
  1> 	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.verify(BlobStoreRepository.java:1208) ~[elasticsearch-7.5.0-SNAPSHOT.jar:7.5.0-SNAPSHOT]
```

This didn't reproduce for me with:

```
./gradlew ':plugins:repository-azure:test' --tests "org.elasticsearch.repositories.azure.AzureBlobStoreRepositoryTests.testSnapshotWithLargeSegmentFiles" -Dtests.seed=163A499DF6578E5A -Dtests.security.manager=true -Dtests.locale=fr-BE -Dtests.timezone=Europe/Zaporozhye -Dcompiler.java=12 -Druntime.java=8
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+EAR/158/console
https://gradle-enterprise.elastic.co/s/snmdwrgcmvbja

### LINKED ISSUE #47948: CI Failures: AzureBlobStoreRepositoryTests.testIndicesDeletedFromRepository
This test has failed periodically (but consistently):

https://groups.google.com/a/elastic.co/forum/#!searchin/build-elasticsearch/AzureBlobStoreRepositoryTests$20testIndicesDeletedFromRepository%7Csort:date

I have not been able to reproduce but (like #47380) it also looks like its coming from the Azure plugin:

```
13:09:53   1> Caused by: com.microsoft.azure.storage.StorageException: An unknown failure occurred : Unexpected end of file from server
13:09:53   1> 	at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:67) ~[azure-storage-8.4.0.jar:?]
13:09:53   1> 	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:220) ~[azure-storage-8.4.0.jar:?]
13:09:53   1> 	at com.microsoft.azure.storage.blob.CloudBlockBlob.uploadFullBlob(CloudBlockBlob.java:1035) ~[azure-storage-8.4.0.jar:?]
13:09:53   1> 	at com.microsoft.azure.storage.blob.CloudBlockBlob.upload(CloudBlockBlob.java:864) ~[azure-storage-8.4.0.jar:?]
13:09:53   1> 	at com.microsoft.azure.storage.blob.CloudBlockBlob.upload(CloudBlockBlob.java:743) ~[azure-storage-8.4.0.jar:?]
13:09:53   1> 	at org.elasticsearch.repositories.azure.AzureStorageService.lambda$writeBlob$15(AzureStorageService.java:332) ~[main/:?]
13:09:53   1> 	at org.elasticsearch.repositories.azure.SocketAccess.lambda$doPrivilegedVoidException$0(SocketAccess.java:64) ~[main/:?]
13:09:53   1> 	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
13:09:53   1> 	at org.elasticsearch.repositories.azure.SocketAccess.doPrivilegedVoidException(SocketAccess.java:63) ~[main/:?]
13:09:53   1> 	at org.elasticsearch.repositories.azure.AzureStorageService.writeBlob(AzureStorageService.java:331) ~[main/:?]
13:09:53   1> 	at org.elasticsearch.repositories.azure.AzureBlobStore.writeBlob(AzureBlobStore.java:120) ~[main/:?]
13:09:53   1> 	at org.elasticsearch.repositories.azure.AzureBlobContainer.writeBlob(AzureBlobContainer.java:102) ~[main/:?]
13:09:53   1> 	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.snapshotFile(BlobStoreRepository.java:1358) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
13:09:53   1> 	at org.elasticsearch.repositories.blobstore.BlobStoreRepository$2.doRun(BlobStoreRepository.java:1115) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
13:09:53   1> 	... 5 more
```

```13:09:53   2> REPRODUCE WITH: ./gradlew ':plugins:repository-azure:test' --tests "org.elasticsearch.repositories.azure.AzureBlobStoreRepositoryTests.testIndicesDeletedFromRepository" -Dtests.seed=D48C184AD8376ABD -Dtests.security.manager=true -Dtests.locale=lv-LV -Dtests.timezone=Pacific/Pitcairn -Dcompiler.java=12 -Druntime.java=11```

### PR DESCRIPTION
**Pull request by tlrx**
This pull request reenables some repository integration tests, decreases the maximum number of failures per request in Azure tests and sets an `ExecutorService` for the `HttpServer` used in tests.

I wasn't able to reproduce to failures reported in #47948 and #47380 but I suspect that the highest max. errors per request of `3` is picked up and the fact that requests are processed using the same thread that started the HTTP server might be the cause of the failures. I also think that with more parallelization added in snapshot/restore using an executor service in tests makes sense.

Closes #47948 
Closes #47380

### CODE REVIEW

**Comment by tlrx** [comment]
@elasticmachine run elasticsearch-ci/1

(Tests are green but I'd like to have more runs)

**Comment by tlrx** [comment]
@elasticmachine run elasticsearch-ci/1

([Test is green](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-1/9270/) but I'd like to have more runs)

**Comment by original-brownbear** [comment]
@tlrx I'm not so sure about this one. Can slowness due to executing the handlers on the HTTP server's callbacks actually lead to EOF exceptions? (to me it seems no, but I haven't worked much with the `HttpServer` before this) Isn't it more likely we're failing to consume the full input here in some corner case and corrupt the Http/1.1 stream that way?

**Review by original-brownbear — COMMENTED** [review]
See my question, I'm a little unsure about the fix, but if the failures are all due to the 3x retry I think we're looking at the right thing probably.

**Comment by tlrx** [comment]
Well I did not claim it's a fix :)

I tried to reproduce the Azure failures by having the tests run over the weekend but I did not manage to reproduce. Also, by looking at the build stats I've found some GCS failures with read timeouts and assertion errors on server side.

I'd expect any failure related to read timeouts or errors/retries to be reproductible, but actually it is not because of the [`randomBoolean()`](https://github.com/elastic/elasticsearch/blob/c5b9cdac81452e697c788a12f0e105e1a9d152a9/test/framework/src/main/java/org/elasticsearch/repositories/blobstore/ESMockAPIBasedRepositoryIntegTestCase.java#L160) (added to make the tests faster) that randomizes things too much and let requests fail or succeed depending on the order they are executed.

>  Can slowness due to executing the handlers on the HTTP server's callbacks actually lead to EOF exceptions?

Honestly I'm not sure. But the internal HTTP servers are still single threaded and we are adding more parallelization to snapshot/restore so I think we should change that so that it better reflects how storage services are working and it avoid to have one operation to be dependent on how another unrelated operation performs.

> but if the failures are all due to the 3x retry I think we're looking at the right thing probably.

That was my initial guess but the fact that the failures do not reproduce easily and that Azure retries test are testing the max. number of retries let me think that it's maybe a factor but maybe not the root cause of the failures. Since Azure executes more requests (HEAD+GET) maybe they are just failing more often than the others.

At this point I agree that this PR is maybe changing too many things at once.

We could maybe do instead:
- remove the randomBoolean() on the server side
- use an executor service on the server side
- reenable azure tests and see how it performs (also monitor S3/GCS)

Depending of the result, revisit the decrease of 3 to 2 max. errors per request. What do you think?

**Comment by original-brownbear** [comment]
> remove the randomBoolean() on the server side

I like this a lot :) Making things more deterministic sounds like the right move.

> use an executor service on the server side

I don't like this tbh. I can't see how lowering the latency of the IO thread by forking cheap operations will help us here. Also, even if it does help, then it's a strange spot because it basically means that our tests are broken and just accidentally work on fast boxes?

On this topic:
> I think we should change that so that it better reflects how storage services are working and it avoid to have one operation to be dependent on how another unrelated operation performs.

I'm not sure this is a valid point. Even though not using a thread-pool for handling requests does make all the request handling sequential it does not however introduce any artificial ordering as far as I can see. In the same way I argued above, I'd say here: If we fail because of sequential handling of requests, then something must either be seriously wrong with the SDK or with our code mustn't it? :)

> reenable azure tests and see how it performs (also monitor S3/GCS)

Jup let's do suggestion 1 (remove the random boolean) and reenable ? :)

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/bwc

**Review by original-brownbear — APPROVED** [review]
LGTM thanks Tanguy!

**Comment by tlrx** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by tlrx** [comment]
@elasticmachine update branch

**Pull request merged**
