### PR TITLE
New Version for log4j - 2.14

### PR DESCRIPTION
**Pull request by vaibhavkhanduja**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by vaibhavkhanduja** [comment]
Contribution aggrement signed.

**Comment by rjernst** [comment]
@elasticmachine ok to test

**Comment by rjernst** [comment]
@vaibhavkhanduja Is there are particular reason you believe we should update to 2.14? A bug fix you need? Note that this PR needs at least one more thing: the jar sha1 hash files need to be updated. See server/licenses. You can update this programmatically by running `./gradlew updateShas`

**Comment by rjernst** [comment]
We really appreciate your interest in contributing to Elasticsearch and hope you make more contributions in the future. Given the lack of need of upgrading log4j at this time, we've decided to close this pull request. You can read more about our approach to reviewing and accepting contributions in our [contributing guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#reviewing-and-accepting-your-contribution). We would be happy to re-evaluate this if you have more time in the future to work with us interactively on the contribution.

**Pull request closed without merging**
