### PR TITLE
subsitution → substitution typo fix

### PR DESCRIPTION
**Pull request by Cladis**

### CODE REVIEW

**Review by cbuescher — APPROVED** [review]
@Cladis thanks a lot for your help in improving our docs, looks good to me. 
This has already been corrected in 5.5 and any newer version, we typically don't correct all documentation typos in older versions than the last minor of the last major (that would be 5.6 in this case), but since this is a small change I will merge it. Please try to open similar documentation type changes either to master or the current version if possible in the future, if applicable we will backport them to all the currently "active" minor versions.

**Comment by cbuescher** [comment]
@Cladis also, in order to get this merged, I'd ask you to sign the CLA please.

**Comment by Cladis** [comment]
@cbuescher , well, this is clearly below threshold of originality ergo a public domain change. I'll sign the CLA in a couple of hours if absolutely needed, though.

**Comment by cbuescher** [comment]
@Cladis I agree on the "threshold of originality", however we have a policy here for all contributions to code as well as documentation. If you find signing the CLA for this too big a hassle we can also close this issue, the typo is corrected for all versions >5.5

**Comment by Cladis** [comment]
Well, I believe I have signed it now.

**Comment by cbuescher** [comment]
@Cladis thanks a lot, will merge this to the 5.x branches that still have this typo then

**Pull request merged**
