### PR TITLE
Fix passing params to template or script failed in watcher

### PR DESCRIPTION
**Pull request by gaobinlong**
Relates to #57625.

The main changes are:

1. Fix custom params are missing when using template or script in watcher's logging action or jira action.
2. Add yaml tests to test passing params to template or script successfully.

### CODE REVIEW

**Comment by jakelandis** [comment]
@elasticmachine update branch

**Comment by jakelandis** [comment]
@elasticmachine ok to test

**Review by jakelandis — APPROVED** [review]
changes look good. thanks @gaobinlong !

**Comment by fbaligand** [comment]
Nice!
Thanks for the fix!

**Pull request merged**
