### PR TITLE
Add index-time scripts to date field mapper

### PR DESCRIPTION
**Pull request by romseygeek**
This commit allows you to set 'script' and 'on_script_error' parameters
on date field mappers, meaning that runtime date fields can be made indexed
simply by moving their definitions from the runtime section of the mappings
to the properties section.

### CODE REVIEW

**Review by javanna — APPROVED** [review]
LGTM

**Comment by romseygeek** [comment]
@elasticmachine update branch

**Comment by romseygeek** [comment]
@elasticmachine run elasticsearch-ci/eql-correctness

**Review by javanna — APPROVED** [review]
LGTM

**Pull request merged**
