### PR TITLE
Remove usage of internal StorageConnectionString in repository-azure

### PR DESCRIPTION
**Pull request by ChrisHegarty**
This change replaces the usage of the internal Azure API [1], that parses the connection string in order to retrieve the primary and secondary URI's, with our own trivial implementation.

While not an immediate issue today, the usage of the internal API conflicts with the Azure's module-info descriptor and blocks modularizing the component with a module-info.java [2].

[1] com.azure.storage.common.implementation.connectionstring.StorageConnectionString
[2] #94050

### CODE REVIEW

**Review by fcofdez — APPROVED** [review]
LGTM. Thanks for tackling this.

**Comment by ChrisHegarty** [comment]
@elasticmachine retest this please

**Comment by ChrisHegarty** [comment]
@fcofdez Testing has uncovered that we need to derive the endpoint when one is not explicitly specified in the connect string. I added this, as well as removed the randomness from the test so that the scenario is *always* covered.

**Comment by fcofdez** [comment]
> @fcofdez It seems a little unnecessary that we have to do this this kinda thing in the Elasticsearch code, so as to get the retry policy working appropriately. It kinda smacks of a missing abstraction from the Azure SDK. While I'm not advocating just making the internals public, it would seems that some minimal API to retrieve the endpoint URIs would be appropriate in the SDK itself.

@ChrisHegarty I agree, I'll open a ticket for this in the SDK github. But from previous experiences this might take months to get in a release. So let's merge this to unblock the modularization.

**Review by fcofdez — APPROVED** [review]
LGTM

**Pull request merged**
