### PR TITLE
Swithc to jcenter and hope to have fewer network failures in builds

### PR DESCRIPTION
**Pull request by alpar-t**
Jcenter suposedly operates on a CDN.
It should be faster and more reliable.
It's the default in Andorid Studio currently
( it switched from mavenCentral ).

This change is safe because jcenter is a super-set of mavenCentral.

### CODE REVIEW

**Review by jasontedor — APPROVED** [review]
LGTM. There's one comment that needs to be addressed before merging, but no need for another review.

**Comment by atorok** [comment]
@elasticmachine test this please

**Comment by atorok** [comment]
@elasticmachine retest this please

**Comment by atorok** [comment]
@elasticmachine test this please

**Comment by romseygeek** [comment]
We're still seeing a few failures every day due to jcenter downloads timing out, eg:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=zulu8,nodes=virtual&&linux/158/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.6+multijob-unix-compatibility/os=ubuntu&&virtual/30/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+release-tests/290/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+release-tests/291/console

All from today

**Comment by atorok** [comment]
The failures seem to be from when the dependencies of older versions are resolved that do not use Gradle 5 (which adds retries). 
We would either have to cache dependencies for those versions too or start using a maven caching proxy.

**Pull request merged**
