### PR TITLE
No need to inject the ClusterService into IndicesService

### PR DESCRIPTION
**Pull request by bleskes**
It's already available where it's needed. One less guice dependency.

### CODE REVIEW

**Comment by ywelsch** [comment]
ok, can you actually remove it from the IndicesService constructor parameters?

**Comment by bleskes** [comment]
@ywelsch i'm sleeping.  pushed an update.

**Comment by s1monw** [comment]
LGTM

**Comment by ywelsch** [comment]
LGTM2

**Comment by bleskes** [comment]
thx @ywelsch @s1monw

**Pull request merged**
