### PR TITLE
Mapping: add an assertion to verify consistent serialization

### PR DESCRIPTION
**Pull request by bleskes**
We recently run into two issues where mapping weren't serialized in a consistent manner (#10302 and #10318). We rely on this consistency to do a byte level checl that mappings we get from the master are indentical to the one we have locally. Mistakes here can cause endless refresh mapping loops.

This commit adds an assert that verifies this upon every update from the master.

### CODE REVIEW

**Comment by kimchy** [comment]
@bleskes I think your note on concurrency might actually be relevant? what happens if during that time an indexing comes in and introduces a new field? If so, I wonder if we should just wait till mappings are immutable and do it then

**Comment by bleskes** [comment]
@kimchy I think capturing the compressed string and checking it deserializes and serializes back to the same thing is useful? the compressed string it self is immutable? Feels like I'm missing something.

**Comment by bleskes** [comment]
@kimchy ping?

**Comment by rjernst** [comment]
LGTM

**Comment by rjernst** [comment]
I rebased and pushed.
Master: 521f804c
1.x: 7828852

**Comment by bleskes** [comment]
Thx @rjernst !

**Pull request closed without merging**
