### PR TITLE
Fix human readable xcontent for snapshots in progress and deletion

### PR DESCRIPTION
**Pull request by dakrone**
Previously this returned `start_time` as a `TimeValue`, but `start_time` is a timestamp.

This switches from `humanReadableField` to `timeField` during the XContent building.

### CODE REVIEW

**Comment by dakrone** [comment]
@elasticmachine update branch

**Review by original-brownbear — COMMENTED** [review]
It appears we have the same issue in `SnapshotsInProgress` and a few other places. Should way maybe fix this everywhere in one go (or at least also handle `SnapshotsInProgress` in this PR for consistency's sake)?

**Comment by dakrone** [comment]
@original-brownbear I added a commit to fix this  in `SnapshotsInProgress`. I don't mind fixing it elsewhere, but testing it is kind of a pain since it's a human-readable field only, so for this PR I'll leave it at these two.

**Comment by dakrone** [comment]
Ugh. This is what happens when you merge master and also do `pull --rebase` on a branch that already has part of master merged in :|

**Comment by original-brownbear** [comment]
> I added a commit to fix this in SnapshotsInProgress. I don't mind fixing it elsewhere, but testing it is kind of a pain since it's a human-readable field only, so for this PR I'll leave it at these two.

++ sounds good thanks

**Review by original-brownbear — APPROVED** [review]
LGTM :) thanks Lee!

**Pull request merged**
