### PR TITLE
Migrate migration docs from 6.0 to 7.0

### PR DESCRIPTION
**Pull request by dakrone**
Since we only keep one version of migration docs and master is now on 7.0, we
should migrate these so breaking changes can be added in the right place.

### CODE REVIEW

**Review by jasontedor — APPROVED** [review]
LGTM assuming the docs build successfully.

**Comment by dakrone** [comment]
I ran `gradle docs:check` and everything checked out, thanks for the quick review :)

**Comment by dakrone** [comment]
(I'll also build the entire doc set before merging)

**Review by nik9000 — APPROVED** [review]
Makes sense to me.

**Comment by jasontedor** [comment]
I meant an actual docs build with the Perl script.

**Comment by dadoonet** [comment]
I suppose I must close #26111 then?

**Comment by dakrone** [comment]
@dadoonet ah whoops sorry! I totally didn't see your PR for this already, are you okay if I merge this one? I just verified it builds with the `build_docs.pl` without any errors

**Comment by dakrone** [comment]
retest this please

**Comment by dadoonet** [comment]
Sure. Just close mine.

**Pull request merged**
