### PR TITLE
URL param parsing should not be lenient

### LINKED ISSUE #14719: url params parsing should not be lenient
If you use eg the `_analyze` api, and mispell the `tokenizer`, it will happily go on using the standard *analyzer* (if you have filters specified, it will ignore them as well).

We should remove all leniency from url param parsing, it does not help anyone, but only causes confusion. Rest actions should remove parameters as they are parsed, and fail when there are extras left (eg `Unknown parameter "tokenzier" for _analyze`)

### PR DESCRIPTION
**Pull request by martinstuga**
First commit to allow the team to check if this approach is OK.

At this point, I've just implemented the validation do GET requests because it invokes the method on the server and just before returning I check if all parameters have been used. This is Ok for read operations, but not allowed on write operations (there we've to change all single request before server invocation).

Please, let me know if this implementation is fine for GET operations and if the error format is correct.

Closes #14719

### CODE REVIEW

**Comment by clintongormley** [comment]
@rjernst could you review this please?

**Comment by martinstuga** [comment]
Please, consider ONLY this commit: https://github.com/martinstuga/elasticsearch/commit/768da9a7b3934a8f349ac9a64669c95e563b44d0

I've done some mistakes working with GitHub and I don't know how to undo it. Help would be welcome.

**Comment by clintongormley** [comment]
@martinstuga either rebase your branch on master, or just create a new branch and cherry pick the relevant commit, then force push your branch (or create a new PR)

**Comment by martinstuga** [comment]
Thank you @clintongormley , I'm going to do that. Please, wait for my next PR. Sorry for the inconvenience.

**Comment by martinstuga** [comment]
@clintongormley and @rjernst , please, now consider this PR #15462.
Sorry about that.

**Pull request closed without merging**
