### PR TITLE
[8.6] [ML] Use long inference timeout at ingest (#93731)

### PR DESCRIPTION
**Pull request by davidkyle**
Backports of #93731 to 8.6

### CODE REVIEW

**Comment by temiwale88** [comment]
Hello @davidkyle . I'm incredibly green at using ES and I hit the timeout issue 
''
timeout [10s] waiting for inference result
''

I saw a previous comment from you to revert back to 8.6.0. I have 8.6.3. How do roll back to that version? I'm trying to use a pytorch model for a NLP task in an ingest pipeline.

**Comment by davidkyle** [comment]
Hi sorry you have hit this timeout issue. 

If you are using elastic cloud create a new deployment and select the version 8.6.0 then start ingesting your data. 

Otherwise you can download 8.6.0 Elasticseach here
https://www.elastic.co/downloads/past-releases/elasticsearch-8-6-0


And kibana from 
https://www.elastic.co/downloads/past-releases/kibana-8-6-0

Once you have your cluster up and running with the NLP models installed ingest your data once again.

**Comment by temiwale88** [comment]
Thanks David. I'm deploying and testing locally. I think my concern is not knowing how to downgrade my local 8.6.2 cluster by downloading 8.6.0. Do I just 'destroy' the 8.6.2 cluster and if so, how do I do a clean uninstall on a Windows machine?

**Comment by davidkyle** [comment]
>  I think my concern is not knowing how to downgrade my local 8.6.2

I would not recommend trying to downgrade your cluster, just 'destroy' the cluster and rebuild it with 8.6.0. Sorry, I hope it will be quick to rebuild your cluster.

> how do I do a clean uninstall on a Windows machine?

I'm do not have a Windows machine so I don't know sorry. I guess it depends on how you installed Elasticsearch but you should stop Elasticsearch (or the service) first before removing it.

**Comment by temiwale88** [comment]
Thanks David! I'll figure it out.

**Comment by vivek-cactus** [comment]
> Hi sorry you have hit this timeout issue.
> 
> If you are using elastic cloud create a new deployment and select the version 8.6.0 then start ingesting your data.
> 
> Otherwise you can download 8.6.0 Elasticseach here https://www.elastic.co/downloads/past-releases/elasticsearch-8-6-0
> 
> And kibana from https://www.elastic.co/downloads/past-releases/kibana-8-6-0
> 
> Once you have your cluster up and running with the NLP models installed ingest your data once again.

@davidkyle : I can not see 8.6.0 option coming in the Elastic cloud. Just an FYI :(

**Comment by vivek-cactus** [comment]
Thanks a lot @davidkyle, will check and let you know

**Comment by temiwale88** [comment]
@davidkyle . Thanks for the tip to rollback to 8.6.0 on my local Windows machine. I did that and I get a new issue `inference process queue is full`. This [S.O. forum](https://bit.ly/40v7UEd) led me to this `POST` request 
```
POST _ml/trained_models/sentence-transformers__labse/deployment/_start?threads_per_allocation=4&queue_capacity=10000&number_of_allocations=4
```

but I still can't have all my data (approx. 4k) indexed with embeddings. 
Please let me know if there's an issue with 8.6.0 as well or if there's a better way to bulk insert an existing indexing into a new index with embeddings. Thanks!

**Comment by temiwale88** [comment]
Never mind @davidkyle . But for posterity, I'll post my little fix. 
Kept the `POST` request as above but modified my reindex `POST` request `size` parameter (batch-size).

```
POST _reindex?wait_for_completion=false
{
  "source": {
    "index": "show_testimony",
    "size": 10000 //batch-size
  },
  "dest": {
    "index": "show_testimony_with_embeddings",
    "pipeline": "text-embeddings"
  }
}
```

Now I don't know if you have to specify the same number (e.g. 10000) for the batch_size as the `queue_capacity` but I just wanted to be safe. Thanks for your help @davidkyle . All clear!

I will re-do this work in the cloud (ES managed service). Is it best to stick to 8.6 or I can use pytorch models in the updated 8.7?

**Comment by davidkyle** [comment]
@temiwale88 you need to add a Machine Learning node to your cluster. 

In the cloud UI when you create a cluster expand the *Advanced Settings* section then scroll down to *Machine Learning instances* and click the add capacity button. Alternatively you can edit the deployment in the deployments UI and add a Machine Learning node there.

**Comment by temiwale88** [comment]
Thanks @davidkyle . 
I created a new deployment and got this error where trying to start a model deployment

```
{
  "error": {
    "root_cause": [
      {
        "type": "status_exception",
        "reason": "Could not start deployment because no ML nodes with sufficient capacity were found"
      }
    ],
    "type": "status_exception",
    "reason": "Could not start deployment because no ML nodes with sufficient capacity were found",
    "caused_by": {
      "type": "illegal_state_exception",
      "reason": "Could not start deployment because no suitable nodes were found, allocation explanation [Could not assign (more) allocations on node [<xxxxx>]. Reason: This node has insufficient available memory. Available memory for ML [1082130432 (1gb)], free memory [1082130432 (1gb)], estimated memory required for this model [4050681058 (3.7gb)].]"
    }
  },
  "status": 429
}
```

I tried running this (I think this was your response to another user - I don't remember):

```
PUT /_cluster/settings
{
    "transient" : {
        "xpack.ml.max_machine_memory_percent" : 40
    }
}
```

And got this error:

```
{
  "error": {
    "root_cause": [
      {
        "type": "security_exception",
        "reason": "Operator privileges are required for setting [xpack.ml.max_machine_memory_percent]"
      }
    ],
    "type": "security_exception",
    "reason": "action [cluster:admin/settings/update] is unauthorized for user [<xxxxx>] with assigned roles [editor,viewer,superuser] because it requires operator privileges, this action is granted by the cluster privileges [manage,all]",
    "caused_by": {
      "type": "security_exception",
      "reason": "Operator privileges are required for setting [xpack.ml.max_machine_memory_percent]"
    }
  },
  "status": 403
}
```

Is it possible that **a trial version is not suitable for this PyTorch integration**?

Thanks!

**Comment by vivek-cactus** [comment]
@temiwale88 : You have to choose at least 2GB RAM for ML models to run on Elastic cloud. 2 GB RAM machine is available on Elastic cloud trial versions. Please check

**Pull request merged**
