### PR TITLE
Allow set section in setup section of REST tests

### PR DESCRIPTION
**Pull request by jasontedor**
This commit enables using a set section in the setup section of REST tests.

### CODE REVIEW

**Comment by jasontedor** [comment]
@elastic/es-clients Note that your test runners will need to be updated to handle a set section in a setup section (if they do not already allow it). The immediate use-case for this is not in a REST test exposed to the language clients but instead in docs tests so there is not an immediate need for you to update your test runners, but it does now mean that a REST test could be introduced that uses this functionality. If your test runners are not ready when that happens, there will be breakage.

**Comment by nik9000** [comment]
Lgtm

**Comment by jasontedor** [comment]
@elasticmachine run gradle build tests

**Comment by jasontedor** [comment]
@elasticmachine run gradle build tests

**Comment by Mpdreamz** [comment]
@jasontedor ack, thanks for the heads up!

**Comment by HonzaKral** [comment]
Hi @jasontedor, could we add this to the documentation (the `README` in the `test` directory) and possible also add this as a `feature` that will be `skip`-able if it's a breaking change?

Thank you!

**Comment by jasontedor** [comment]
@HonzaKral `set` is documented as a required section. I think it is only a mistake that the Java driver did not support `set` in `setup` sections previously.

**Pull request merged**
