### PR TITLE
Remove Redundant RestoreRequest Class

### PR DESCRIPTION
**Pull request by original-brownbear**
* Same as #37464 but for the restore side

### CODE REVIEW

**Comment by original-brownbear** [comment]
Jenkins runs Gradle build tests 2

**Comment by original-brownbear** [comment]
Jenkins run Gradle build tests 2

**Comment by original-brownbear** [comment]
Jenkins run Gradle build tests 1

**Comment by original-brownbear** [comment]
Jenkins run Gradle build tests 2

**Review by ywelsch — APPROVED** [review]
@tbrooks8 can you have a look as well?

**Review by Tim-Brooks — APPROVED** [review]
LGTM

**Comment by original-brownbear** [comment]
@tbrooks8 @ywelsch thanks!

**Pull request merged**
