### PR TITLE
Remove unnecessary Dockerfile commands

### PR DESCRIPTION
**Pull request by dliappis**
As the Dockerfile evolved we don't need anymore certain commands like
`unzip`, `which` and `wget` allowing us to slightly shrink the images
too.

Relates #38832

### CODE REVIEW

**Comment by dliappis** [comment]
@atorok Note that I added retries in https://github.com/elastic/elasticsearch/pull/39040/commits/6f52008222dc2e9090faa141be425049d9cd37c3, as a separate commit. I am unsure if add this retry logic may affect caching (I think it shouldn't, if it succeeds with the first attempt on the golden image).

**Review by alpar-t — COMMENTED** [review]
This shouldn't affect caching. 
Caching is retried multiple times, so it can only help avoid retries there. 

Are there other use-cases for which this is useful?  The caching solves the problem for our CI, people running on the console can easily retry since this. If there aren't any compelling reasons to have the retries here I think it's better to stick with the much simpler and easier to read command we had before.

**Comment by dliappis** [comment]
> Are there other use-cases for which this is useful? The caching solves the problem for our CI, people running on the console can easily retry since this. If there aren't any compelling reasons to have the retries here I think it's better to stick with the much simpler and easier to read command we had before.

I was thinking that this will primarily help while running inside the release manager VM where network failures can be time consuming and secondarily in case, for whatever reason, the cached layers get removed/don't get utilized in CI.

**Comment by dliappis** [comment]
Just thinking out load, after a brief chat @danielmitterdorfer suggested that we could possibly have release-manager go through the ES dependencies (https://github.com/elastic/elasticsearch/blob/395f3e11bf8df9a279c734142d8b94801ca363d9/.ci/packer_cache.sh#L24) as the first thing. This would remove the need for the retry logic in this commit, wdyt @atorok ?

**Comment by atorok** [comment]
I agree, that would have other benefits. We could also cache the dependencies when we generate RM images and also get performance benefits there.

**Comment by dliappis** [comment]
Thanks, with this in mind I'll revert the retry commit and open an r-m issue.

> We could also cache the dependencies when we generate RM images and also get performance benefits there.

This is potentially dangerous because r-m base images don't get built all too often and we'd like to benefit from things like `yum -y update` etc.

**Comment by dliappis** [comment]
@atorok Is this LGTM?

**Review by alpar-t — APPROVED** [review]
LGTM

**Pull request merged**
