### PR TITLE
Fix percentiles agg in slow log after transport

### PR DESCRIPTION
**Pull request by nik9000**
If you send `percentiles` or `percentiles_ranks` over the transport
client or over cross cluster search it breaks internal components
subtly. They mostly work so we hadn't yet noticed the break. But if you
send the request to the slow log then it'll fail to log. This fixes the
subtle internal break.

### CODE REVIEW

**Comment by nik9000** [comment]
Note: I opened this against 7.x so I could test against the transport client which is where the original problem was reported. I believe its likely good enough just to forward port the randomized unit test and not the internal cluster test.

**Review by polyfractal — APPROVED** [review]
LGTM, nice catch!  Took me a few minutes to figure out how/why this was broken :)

I wonder if we have other, similar things hiding amongst the other aggs?  Percentiles/Ranks is a bit unique in their construction which led to this bug, but if we ever found an easy way to add "slow logging" stringification tests universally to the aggs it'd probably be a good use of time :)

**Comment by nik9000** [comment]
> I wonder if we have other, similar things hiding amongst the other aggs? Percentiles/Ranks is a bit unique in their construction which led to this bug, but if we ever found an easy way to add "slow logging" stringification tests universally to the aggs it'd probably be a good use of time :)

I *think* I added stringification tests after all of the round trips. Not that it'll catch all the sneaky things, but it'll catch some sneaky stuff.

**Comment by jtibshirani** [comment]
Another instance of this just popped up. What would you think about backporting to 7.12.1 as well as the fix looks safe?

**Comment by nik9000** [comment]
I've opened #71562, though I'm not sure it'll make the cut.

**Comment by nik9000** [comment]
> Another instance of this just popped up. What would you think about backporting to 7.12.1 as well as the fix looks safe?

I've just merged #71562 so this should make it into 7.12.1.

**Pull request merged**
