### PR TITLE
Upgrade to Lucene-7.5.0-snapshot-608f0277b0

### PR DESCRIPTION
**Pull request by jimczi**
The main highlight is the removal of the `reclaim_deletes_weight` in the TieredMergePolicy.
The es setting `index.merge.policy.reclaim_deletes_weight` is deprecated in this commit and the value is ignored. The new merge policy setting `setDeletesPctAllowed` should be added in a follow up.

### CODE REVIEW

**Review by jpountz — APPROVED** [review]
LGTM. Thanks @jimczi !

**Comment by jimczi** [comment]
The [last failure](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request/14071) is not related to the upgrade. I opened a separate pr for the fix: https://github.com/elastic/elasticsearch/pull/32396

**Comment by jimczi** [comment]
test this please

**Comment by dnhatn** [comment]
@elasticmachine retest this please

**Comment by dnhatn** [comment]
@jimczi I pushed the fix on https://github.com/elastic/elasticsearch/commit/0ed3458534beb8d93852e57b2ee422324613c528 and merged the master into this PR. I think we are good now. 

P/S: Sorry that I polluted your PR with two wrong commits.

**Comment by jimczi** [comment]
run gradle build tests

**Pull request merged**
