### PR TITLE
Query refactoring: Remove index member from QueryParseContext

### PR DESCRIPTION
**Pull request by javanna**
Given that we are moving to parsing queries on the coordinating node, the index name is not relevant anymore in QueryParseContext, as the parsing phase cannot be related to any specific index. On the contrary, the QueryShardContext is the one that holds mappings etc. and the index name too, as the lucene query creation happens on the data node and can still be related with the index that it happens against.

Changes are mainly around tests that were expecting the index name, moved to using QueryShardException in some of them, removed the index name elsewhere.

### CODE REVIEW

**Comment by javanna** [comment]
@colings86 this is something that we discussed, whicih should help moving forward with the search request refactoring, as the `QueryParseContext` won't depend on an index anymore. The way we currently create it still needs to change once we refactored all the queries, it still gets created internally together with the shard context at index creation, so we have one per index per node, but that will change in the future.  You can simply have your own new parse context and use it for now to call `fromXContent`.

**Comment by s1monw** [comment]
LGTM

**Comment by javanna** [comment]
I just rebased this, turns out it looks a bit different after merging #13631 in. Got rid of `TestQueryParsingException` and `TestQueryShardException`. feel free to have another look.

**Comment by colings86** [comment]
LGTM

**Comment by javanna** [comment]
I had to rebase again. After the changes made in #13631 and this PR, I went ahead and removed any dependency of ParsingException from QueryParseContext. Also taking in the whole XContentParser wasn't needed in the constructors, as @colings86  pointed out, `XContentLocation` is enough.

**Comment by colings86** [comment]
LGTM

**Pull request merged**
