### PR TITLE
Add a note about shard failure in the api

### LINKED ISSUE #13674: exceptions from native search scripts are no longer propagated to client
In ES-2.0.0-beta2 (and also in ES-2.0.0-beta1), when an exception in thrown from a native 
search script, Java node clients no longer seem to receive any indication that something went wrong.

For example, we have a native sort script that takes a parameter and throws an exception in case it is missing:
```java
    private static class MyFactory implements NativeScriptFactory {
        @Override
        public ExecutableScript newScript(final Map<String, Object> params) {
            if (params.get("field")== null) {
                throw new ScriptException("missing parameter: field");
            }
            ...
        }

        @Override
        public boolean needsScores() {
            return false;
        }
    }
```

however, the following integration test, that used to work with ES-1.7.1, now fails:
```java
public abstract class MyScriptIT extends ESIntegTestCase {
    @Rule
    public ExpectedException _exception = ExpectedException.none();

    @Test
    public void testMissingFieldFails() throws Exception {
        createIndex(...);
        ensureGreen(...);

        _exception.expect(SearchPhaseExecutionException.class);
        _exception.expectMessage("missing parameter: field");

        final Map<String, Object> params = new HashMap<>();
        final Script script = new Script("my-script", ScriptType.INLINE, "native", params);
        final ScriptSortBuilder script = SortBuilders.scriptSort(script, "number");
        return _client.prepareSearch(...).addSort(script).execute().actionGet();
    }
}
```

in fact, no exception at all is thrown
```
java.lang.AssertionError: Expected test to throw (an instance of org.elasticsearch.action.search.SearchPhaseExecutionException and exception with message a string containing "missing parameter: field")
...
```

in addition, it appears that 
- scripted fetch fields, scripted metrics also don't propagate any thrown exceptions.
  e.g. AggregationBuilders.sum("sum").script(...)
  e.g. AggregationBuilders.scriptedMetric(...)

- update scripts on the other hand still do return exceptions. 
  e.g. return _client.prepareUpdate("test", "test", id).setScript(...);
  However, the returned message always is "failed to execute script", 
  while it used to contain the message that was generated by our native script.

### PR DESCRIPTION
**Pull request by nik9000**
Closes #13674

### CODE REVIEW

**Comment by nik9000** [comment]
I resisted the urge to be more opinionated in the documentation and make claims like "It is up to you if those failures constitute something worth logging, something worth reporting to the user, or both."

**Comment by nik9000** [comment]
@clintongormley  - want to review this? Its one of the last 2.0 PRs!

**Comment by jpountz** [comment]
LGTM

**Comment by nik9000** [comment]
Merged to master and cherry picked to 2.0, 2.1, and 2.x.

**Pull request merged**
