### PR TITLE
Adapt testPendingTasks() for replicated closed indices

### PR DESCRIPTION
**Pull request by tlrx**
Note: this pull request is aimed to be merged in the `replicated-closed-indices` feature branch

The test `IndicesServiceTests.testPendingTasks()` (muted in #38024) needs to be adapted in order to work with replicated closed indices.

Relates to #33888

### CODE REVIEW

**Comment by tlrx** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by tlrx** [comment]
@elasticmachine test this please

**Comment by tlrx** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by tlrx** [comment]
@elasticmachine run elasticsearch-ci/1

**Review by ywelsch — APPROVED** [review]
LGTM

**Comment by tlrx** [comment]
Thanks @ywelsch

**Pull request merged**
