### PR TITLE
[Backport] [8.4] [94667] add support for javadoc in version >= 8.x

### PR DESCRIPTION
**Pull request by kilfoyle**
Manual backport of #94667 to 8.4

### CODE REVIEW

**Comment by kilfoyle** [comment]
@elasticmachine run elasticsearch-ci/docs

**Review by abdonpijpelink — APPROVED** [review]
LGTM

**Comment by kilfoyle** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by kilfoyle** [comment]
Closing unmerged since it's just this one release that seems to have trouble passing CI checks.

**Pull request closed without merging**
