### PR TITLE
SearchRequestBuilder.toString modifies the SearchRequestBuilder wiping any source set.

### LINKED ISSUE #5555: CountRequestBuilder toString()
SearchRequestBuilder has a friendly toString method, but not same for CountRequestBuilder.
Will be a good to have feature for debugging.

### LINKED ISSUE #5576: SearchRequestBuilder#toString causes the content of the request to change
Using the Java API, If one sets the content of a search request through `SearchRequestBuilder#setSource` methods and then calls `toString` to see the result, not only the content of the request is not returned as it wasn't set through `sourceBuilder()`,  the content of the request gets also reset due to the `internalBuilder()` call in `toString`.

Here is a small failing test that demontrates it:

```
SearchRequestBuilder searchRequestBuilder = new SearchRequestBuilder(client()).setSource("{\n" +
                "            \"query\" : {\n" +
                "            \"match\" : {\n" +
                "                \"field\" : {\n" +
                "                    \"query\" : \"value\"" +
                "                }\n" +
                "            }\n" +
                "        }\n" +
                "        }");
String preToString = searchRequestBuilder.request().source().toUtf8();
searchRequestBuilder.toString();
String postToString = searchRequestBuilder.request().source().toUtf8();
assertThat(preToString, equalTo(postToString));
```

### LINKED ISSUE #7317: SearchRequestBuilder.toString modifies the SearchRequestBuilder wiping any source set.
If you use setSource on a SearchRequestBuilder and then call to string the SearchRequest will appear to be cleared. 

````
SearchRequestBuilder srb = client().prepareSearch().setSource("{\"query\":\"match\":{\"foo\":\"bar\"}}");
srb.execute().get();
```` 
Will execute the correct search, however 
````
SearchRequestBuilder srb = client().prepareSearch().setSource("{\"query\":\"match\":{\"foo\":\"bar\"}}");
logger.debug("About to execute [{}]",srb.toString());
srb.execute().get();
````
Will execute an empty search. 

The problem is that ````toString()```` calls ````internalBuilder()```` which calls ````sourceBuilder()```` 
````
    private SearchSourceBuilder sourceBuilder() {
        if (sourceBuilder == null) {
            sourceBuilder = new SearchSourceBuilder();
        }
        return sourceBuilder;
    }
````
Then when the ````SearchRequestBuilder.execute```` is called the request that was constructed via ````setSource```` is replaced by an empty sourceBuilder.

````
    @Override
    protected void doExecute(ActionListener<SearchResponse> listener) {
        if (sourceBuilder != null) {
            request.source(sourceBuilder());
        }
        client.search(request, listener);
    }
````

### PR DESCRIPTION
**Pull request by GaelTadh**
This fixes #7317.
SearchRequestBuilder.toString now attempts to render the request's source before falling back to using the internal builder.

Closes #5576 
Closes #5555

### CODE REVIEW

**Comment by cooniur** [comment]
Or something like this?:

       @Override
	public String toString() {
	    if (sourceBuilder != null) {
	        return sourceBuilder.toString();
	    }

	    if (request.source() != null) {
	        return request.source().toUtf8();
	    }
	    return "{ }";
	}

**Comment by jprante** [comment]
This is a really subtle and longstanding bug and should be IMHO applied to 1.4 branch asap.

**Comment by cooniur** [comment]
@jprante +1024

We found our current application broken only because we turned on the trace level logger to debug our application, where we use the `toString()` method to trace the request , but unexpectedly step upon this bug.

Thank god it was not in the production environment, but it could cause far more worse issues if it were in production environment.

**Comment by javanna** [comment]
Closing in favour of #9944

**Comment by javanna** [comment]
This will be fixed as soon as #9944 gets in, I am on it. Just wanted to add that #9201 will make all these problems go away on the long run, I invite you all to watch that other issue (aimed for 2.0) if you are using the Java API.

**Pull request closed without merging**
