### PR TITLE
add ILM rolling upgrade tests

### PR DESCRIPTION
**Pull request by talevy**
Adds basic rolling upgrade tests to check that lifecycles are still recognizable between rolling cluster upgrades and managed indices stay managed.

This is a placeholder for discussing types of checks so they are ready once we backported

### CODE REVIEW

**Comment by dakrone** [comment]
@elasticmachine test this please

**Comment by talevy** [comment]
test this please

**Comment by talevy** [comment]
test this please

**Comment by talevy** [comment]
test this please

build was done using a stale worker that had the following argument

```
-Dtests.bwc.refspec=elastic/index-lifecycle-6.x
```

should be

```
-Dtests.bwc.refspec.6.x=elastic/index-lifecycle-6.x
```

**Comment by talevy** [comment]
test this please

**Comment by talevy** [comment]
update from CI: this PR will not be run with the appropriate bwc branch, so it will not go green until after merging

**Review by dakrone — APPROVED** [review]
LGTM

**Comment by talevy** [comment]
thanks for the review @dakrone!

merging after a green run on a local run of 

```
./gradlew :x-pack:qa:rolling-upgrade:with-system-key:check -Dtests.bwc.refspec.6.x=elastic/index-lifecycle-6.x
```

I have confirmed that the CI for the `index-lifecycle` branch is leveraging this new build argument and so it should pass upstream.

**Pull request merged**
