### PR TITLE
Remove all date 'now' methods from Painless

### PR DESCRIPTION
**Pull request by jdconrad**
As the title says.

This closes (#20762).

### CODE REVIEW

**Review by nik9000 — APPROVED** [review]
We should add some documentation about how to actually get `now` in a followup I think.

**Comment by rjernst** [comment]
Lgtm. I don't think we need to document how to get now, as this is something people shouldn't be using in scripts. That is the entire reason for #20762.

**Comment by jdconrad** [comment]
I think @nik9000  might have meant document how to get the equivalent of now by passing it in as a param?  @rjernst Thanks for the review.

**Comment by nik9000** [comment]
> I think @nik9000 might have meant document how to get the equivalent of now by passing it in as a param?

Indeed.

**Comment by s1monw** [comment]
w00t thanks for the quick reaction on this @jdconrad

**Pull request merged**
