### PR TITLE
rename CRUD api REST path prefix _ilm to _ilm/policy

### LINKED ISSUE #34929: Update _ilm policy CRUD APIs to be behind _ilm/policy namespace
there are multiple cluster-level APIs for ILM that reside behind the `_ilm` URL path.

Endpoints like:

- _ilm/start
- _ilm/stop
- _ilm/status

The above conflict with the get-policy API _ilm/<policy-name> where a policy name can be 
"start", "stop", or "status".

This can be fixed by moving the CRUD APIs to be behind the _ilm/policy/ path prefix.

So

 GET/DELETE/PUT _ilm/policy/<index-names>

### PR DESCRIPTION
**Pull request by talevy**
This PR renames the CRUD APIS for ILM

GET _ilm/<policy>, _ilm -> _ilm/policy/<policy>, _ilm/policy
PUT _ilm/<policy> -> _ilm/policy/<policy>
DELETE _ilm/<policy> -> _ilm/policy/<policy>

closes #34929.

### CODE REVIEW

**Comment by dakrone** [comment]
I feel like this is missing the documentation changes also? Shouldn't we have some docs somewhere referencing this that need to change?

**Comment by talevy** [comment]
indeed @dakrone, I forgot to test the docs :(. pushed the doc changes up now!

**Review by dakrone — APPROVED** [review]
LGTM if CI is happy

**Review by AthenaEryma — COMMENTED** [review]
LGTM

**Review by colings86 — APPROVED** [review]
LGTM

**Pull request merged**
