### PR TITLE
Optimize extra global check points in BlobStoreIndexShardSnapshots.

### PR DESCRIPTION
**Pull request by howardhuanghua**
Remove the unused global check points HashMap instance to lower down memory fingerprint.
It's introduced in https://github.com/elastic/elasticsearch/pull/52182 v7.7.0.

### CODE REVIEW

**Comment by original-brownbear** [comment]
Jenkins test this

**Review by original-brownbear — APPROVED** [review]
LGTM, thanks @howardhuanghua

**Comment by howardhuanghua** [comment]
Some tests failed? It seems it's based on the latest master branch.

**Comment by original-brownbear** [comment]
@howardhuanghua yea it's caused by https://github.com/elastic/elasticsearch/pull/62286, we'll have to retriever the build once that's merged.

**Comment by original-brownbear** [comment]
@howardhuanghua could you merge latest master into this branch so we get a green CI run? Thanks!

**Comment by howardhuanghua** [comment]
done.

**Comment by original-brownbear** [comment]
Jenkins test this

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/packaging-sample-windows

**Pull request merged**
