### PR TITLE
Cheaper ActionListener.wrap when error handler is the listener

### PR DESCRIPTION
**Pull request by original-brownbear**
Motivated by looking into allocations of listeners in detail for shared cache benchmarking. Wrapping a listener and using `listener::onFailure` as the failure callback means that we have a reference to the listener from both the failure and the response handler. If we use the approach used by the `.deleteGate*` methods, we can often save allocating a response handler lambda or at least make the response handler cheaper. We also save allocating the failure handler lambda.

### CODE REVIEW

**Review by DaveCTurner — COMMENTED** [review]
I like it, but I don't like the naming clash between `wrapResponse` and `delegateFailure` which are basically the same except for the behaviour if `onResponse` throws. I'd be ok with them both mentioning "response" or "failure" (with a slight preference for "response", history be damned) but having one of each is pretty confusing.

**Comment by original-brownbear** [comment]
@DaveCTurner +1 on the name, sorry that was stupid. Unfortunately, `delegateFailure` is used in a bunch of spots and I didn't want to rename that here. How about `wrapFailure` for now for the new version?

**Comment by DaveCTurner** [comment]
Hm naming this something failure-related is hard; `wrapFailure` is going to cause confusion I think. I can't think of anything particularly short, but I'd really like to fix the naming in this area so how about `delegateFailureAndWrap` as a temporary measure?

**Comment by original-brownbear** [comment]
++ sounds good -> renamed

**Review by DaveCTurner — APPROVED** [review]
LGTM

I left a comment wording suggestion, and also suggest something like this:

```diff
diff --git a/server/src/main/java/org/elasticsearch/action/ActionListener.java b/server/src/main/java/org/elasticsearch/action/ActionListener.java
index 22b1e22e051..68edd8af5d6 100644
--- a/server/src/main/java/org/elasticsearch/action/ActionListener.java
+++ b/server/src/main/java/org/elasticsearch/action/ActionListener.java
@@ -139,6 +139,9 @@ public interface ActionListener<Response> {
     /**
      * Creates a listener that executes the appropriate consumer when the response (or failure) is received. This listener is "wrapped" in
      * the sense that an exception from the {@code onResponse} consumer is passed into the {@code onFailure} consumer.
+     * <p>
+     * If the {@code onFailure} argument is {@code listener::onFailure} for some other {@link ActionListener}, prefer to use
+     * {@link #delegateFailureAndWrap} instead.
      *
      * @param onResponse the checked consumer of the response, executed when the listener is completed successfully. If it throws an
      *                   exception, the exception is passed to the {@code onFailure} consumer.
      *
```

**Comment by original-brownbear** [comment]
Thanks David!

**Pull request merged**
