### PR TITLE
Set network receive predictor size to 32kb

### LINKED ISSUE #23185: Default network buffer size causes higher GC pressure than necessary
`Netty4HttpServerTransport` uses the settings `http.netty.receive_predictor_min` and `http.netty.receive_predictor_max` to provide a properly configured `RecvByteBufAllocator` implementation to Netty. Their default value is controlled by the setting `transport.netty.receive_predictor_size` which varies between 64 kb and 512 kb (per allocated buffer). 

The before-mentioned allocator is responsible for allocating memory buffers when handling incoming network packets and Netty will allocate one buffer per network packet.

We have run comparative benchmarks ([nyc_taxis](https://github.com/elastic/rally-tracks/tree/master/nyc_taxis)) track, once locally (i.e. via loopback) and once distributed (i.e. via a Ethernet) and analyzed the allocation behavior of Elasticsearch.

|   Network Connection Type | Bytes allocated outside of TLABs on network layer |
|----------------------------:|---------------------------------:|
|   Loopback | ~ 78 GB  |
|   Ethernet | ~ 2.13 TB  |

_Note: On this particular machine `transport.netty.receive_predictor_size` was 512kb._

The root cause seems to be related to MTU (which differs greatly between loopback and regular network devices (65536 vs. 1500)). A smaller MTU leads to more network packets (but the buffer size stays the same) thus leading to more GC pressure.

In a custom build of Elasticsearch we set `http.netty.receive_predictor_min` to 5kb and `http.netty.receive_predictor_max` to 64kb and got comparable allocation behavior between local and distributed benchmarks.

_Note: Our analysis focused only `Netty4HttpServerTransport` for a single Elasticsearch node. It is expected that `Netty4Transport` exhibits similar behavior and we should change the buffer size there too._

### PR DESCRIPTION
**Pull request by danielmitterdorfer**
Previously we calculated Netty's receive predictor size for HTTP and transport
traffic based on available memory and worker nodes. This resulted in a receive
predictor size between 64kb and 512kb. In our benchmarks this leads to increased
GC pressure.

With this commit we set Netty's receive predictor size to 32kb. This value is in
a sweet spot between heap memory waste (-> GC pressure) and effect on request
metrics (achieved throughput and latency numbers).

Closes #23185

### CODE REVIEW

**Comment by clintongormley** [comment]
@danielmitterdorfer should we also backport to 5.2?

**Comment by danielmitterdorfer** [comment]
@clintongormley Sure, it's a pretty isolated change.

**Comment by danielmitterdorfer** [comment]
@elasticmachine please test it

**Comment by jasontedor** [comment]
> Sure, it's a pretty isolated change.

It impacts networking requests, I don't think this should be considered an isolated change.

My preference would be for this to bake in master/5.x for a little before pushing anywhere else.

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by danielmitterdorfer** [comment]
> It impacts networking requests, I don't think this should be considered an isolated change.

I meant it's pretty isolated code-wise. ;) But sure, it has global effects (that's why I ran so many benchmarks before implementing the change). I'm fine with your suggestion to only merge to master first. I'll wait a few days with the backport. @clintongormley Is it ok if I remove all 5.x related labels for in the meantime and add them back once I cherry-pick into the 5.x, 5.3 and 5.2?

Thank you for the review @jasontedor!

**Comment by danielmitterdorfer** [comment]
^ I removed the 5.x labels while letting it bake on master. I'll readd once I cherry-pick into 5.x, 5.3 and 5.2.

**Comment by jasontedor** [comment]
@danielmitterdorfer I do think it's okay to take it to 5.x, that will give it more places to bake. :smile:

**Comment by jasontedor** [comment]
@danielmitterdorfer I think this change has baked sufficiently. I'm comfortable with this being integrated into the 5.3 branch now.

**Comment by danielmitterdorfer** [comment]
As discussed in https://github.com/elastic/elasticsearch/issues/23185#issuecomment-282331616 we need to investigate further before backporting.

**Pull request merged**
