### PR TITLE
Hide metric sub-fields from aggregate_metric searches and add support for scripting

### PR DESCRIPTION
**Pull request by talevy**
This commit only adds one searchable field to the aggregate_metric
field mapper. It makes the defaultMetric value searchable under the
same field name as the aggregate_metric.

This should make aggregate_metric behave more like a numeric in
most use-cases.

```
{
    ...
    "fields": {
        "temperature": {
            "aggregate_metric_double": {
                "type": "aggregate_metric_double",
                "searchable": true,
                "aggregatable": true
            }
        }
    }
}
```

Other things in this PR

- `default_metric` is now required and does not default to `max`
- the fields API's valueFetcher for `aggregate_metric_double` now returns the default-metric value
- support for scripting, where the doc-value returned is that of the `default_metric`

### CODE REVIEW

**Review by csoulios — APPROVED** [review]
LGTM!

**Comment by talevy** [comment]
run elasticsearch-ci/default-distro
run elasticsearch-ci/bwc

**Review by csoulios — COMMENTED** [review]
PR looks good in general. However, after our last sync meeting, I had the impression that `aggregate_metric_double` would behave as a `double`.

So, shouldn't it return the `double` family type?

**Comment by talevy** [comment]
@csoulios thanks for that. updated the family type!

**Review by csoulios — APPROVED** [review]
LGTM!

**Pull request merged**
