### PR TITLE
Add validation for synthetic source mode in logs mode indices

### PR DESCRIPTION
**Pull request by lkts**
This is one of test cases in #109801.

### CODE REVIEW

**Review by martijnvg — APPROVED** [review]
LGTM - for tsdb I see this is also tested in `20_mapping.yml` file. Maybe also add yaml test there for logsdb and unsupported source modes?

**Comment by lkts** [comment]
@martijnvg I am not sure how useful that is? It's basically the same test.

**Comment by martijnvg** [comment]
> I am not sure how useful that is? It's basically the same test.

Right it is, but a yaml is kind of an easier test to understand and it is next to the other not supported source mode tests. But let's merge this, it was more of a nit from my side.

**Comment by lkts** [comment]
I realized that this is a slightly different test indeed, i'll add it.

**Comment by lkts** [comment]
@elasticmachine update branch

**Pull request merged**
