### PR TITLE
Delete data stream API accepts multiple names

### PR DESCRIPTION
**Pull request by danhermann**
In order for the delete data stream API to be made an index-level action, it must accept multiple names as an input parameter so that it can implement the `IndicesRequest.Replaceable` interface.

Relates to #53100

### CODE REVIEW

**Review by martijnvg — APPROVED** [review]
LGTM

**Comment by danhermann** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by danhermann** [comment]
@elasticmachine update branch

**Comment by danhermann** [comment]
@elasticmachine update branch

**Comment by danhermann** [comment]
@elasticmachine update branch

**Pull request merged**
