### PR TITLE
Change log level to error for connecting failure #23076

### LINKED ISSUE #23076: TransportClientNodesService swallows exceptions, reports them at DEBUG log level, and maps all to NoNodesAvailableException
**Elasticsearch version**:
2.3.1

**Plugins installed**: [Kibana]

**JVM version**:
1.8.0_112-b15

**OS version**:
Red Hat 6.7

**Description of the problem including expected versus actual behavior**:
Described in detail in my form post: https://discuss.elastic.co/t/nonodeavailableexception-none-of-the-configured-nodes-are-available-error-when-trying-to-push-data-to-elastic-from-a-spark-job/73904

TransportClientNodesService swallows exceptions, reports them at DEBUG log level, and maps all to a generic NoNodesAvailableException, which makes it very hard to uncover the actual underlying problem.

Actual code in the service:

    protected List<DiscoveryNode> validateNewNodes(Set<DiscoveryNode> nodes) {
        for (Iterator<DiscoveryNode> it = nodes.iterator(); it.hasNext(); ) {
            DiscoveryNode node = it.next();
            if (!transportService.nodeConnected(node)) {
                try {
                    logger.trace("connecting to node [{}]", node);
                    transportService.connectToNode(node);
                } catch (Throwable e) {
                    it.remove();
                    logger.debug("failed to connect to discovered node [" + node + "]", e);
                }
            }
        }

        return Collections.unmodifiableList(new ArrayList<>(nodes));
    }

The desired behavior would be to:
a. Log the original exception at the ERROR level into the log.
b. Wrap the original exception into the NoNodeAvailableException or, better, rethrow the original exception, or something that does not lose the cause exception.

**Steps to reproduce**:
 1. Build a Spark uber-jar with Maven Shade plugin, without using the org.apache.maven.plugins.shade.resource.ServicesResourceTransformer transformer.
 2. Deploy the Spark job and kick it off.
 3. Observe that the code trying to connect to Elastic from the Spark job gets a generic NoNodeAvailableException, with no apparent way to tell what's wrong (the cluster is all GREEN).

### PR DESCRIPTION
**Pull request by liketic**
Resolves #23076 . I'm not sure if it's the best resolution. Any comments are appreciated. 😄

### CODE REVIEW

**Comment by javanna** [comment]
I am marking this for discussion. I find it annoying too that connection errors are logged at debug level only, then a `NoNodeAvailableException` may be logged with no information about the root case. If we at least logged failures with a different level they would not be lost. I think warn would be better than error though. Thoughts from others?

**Comment by liketic** [comment]
Thanks @javanna . I think ```WARN``` makes sense.

**Comment by DaveCTurner** [comment]
I'm definitely against raising this to `ERROR` and I think I'm mildly against raising it to `WARN` too. If I understand correctly, you list multiple nodes because you expect some of them not to connect. If they all fail then the resulting `NoNodeAvailableException` seems to include the error from the last failure at least.

**Comment by javanna** [comment]
> If they all fail then the resulting `NoNodeAvailableException` seems to include the error from the last failure at least.

Depends on where it gets thrown, the exception thrown from `ensureNodesAreAvailable` does not contain the root cause, only the one thrown by the retry listener does. 

I can see why WARN can cause problems too, I don't have a strong opinion on this.

**Comment by martijnvg** [comment]
@liketic Sorry for getting back so late. Like mentioned here before changing log level to warn / error can also add unnecessary logging, which I think defeats the purpose of this change. Please comment if you think otherwise.

**Pull request closed without merging**
