### PR TITLE
Make ValueParser.DateMath aware of timezone setting

### LINKED ISSUE #12278: Date Histogram Aggregations w/ `extended_bounds` and `time_zone`
Hey all, 

I'm performing a date histogram aggregation over the past day (`'now/d'` -> `'now/d'`), and would like to get results into hourly buckets. I am using the `extended_bounds` of the aggregation because I would still like to get empty buckets back (as long as they are within my time range).

Everything is working *almost* as expected... except it seems like `extended_bounds` is not respecting the time zone. 

My query returns the UTC "midnight" bucket which becomes 7pm (on the previous day) when I adjust for my timezone (CST). I would expect that `extended_bounds` with `time_zone` would return that timezone's midnight.

So if I were performing a query from `'now/d'` to `'now/d'` in CST (which is GMT-5 currently), I would expect the first bucket to be `'2015-07-15T05:00:00.000Z'` and _not_ `'2015-07-15T00:00:00.000Z'`.

My question is: Is `extended_bounds` not respecting `time_zone`?

I'm having trouble succinctly describing this in English; hopefully my test case below helps to explain:

#### Test Case:

Index a new document with timestamp of 00:00 GMT:

```
curl -XPOST "http://localhost:9200/analytics/event" -d'
{
    "name": "Prince George",
   "event-date": {
      "timestamp": "2015-07-15T00:00:00.000Z"
   }
}'
```

Index a new document with timestamp of 08:00 GMT:

```
curl -XPOST "http://localhost:9200/analytics/event" -d'
{
    "name": "James Madison",
    "event-date": {
        "timestamp": "2015-07-15T08:00:00.000Z"
    }
}'
```

Search!

```
curl -XPOST "http://localhost:9200/analytics/event/_search" -d'
{
   "query": {
      "filtered": {
         "query": {
            "match_all": {}
         },
         "filter": {
            "bool": {
               "must": [
                  {
                     "range": {
                        "timestamp": {
                           "from": "now/d",
                           "to": "now/d",
                           "time_zone": "-5:00",
                           "include_lower": true,
                           "include_upper": true
                        }
                     }
                  }
               ]
            }
         }
      }
   },
   "aggs": {
      "dateagg": {
         "date_histogram": {
            "field": "event-date.timestamp",
            "interval": "1h",
            "time_zone": "-5:00",
            "min_doc_count": 0,
            "extended_bounds": {
               "min": "now/d",
               "max": "now/d"
            }
         }
      }
   }
}'
```

**Result**:

```
{
   "took": 92,
   "timed_out": false,
   "_shards": {
      "total": 5,
      "successful": 5,
      "failed": 0
   },
   "hits": {
      "total": 1,
      "max_score": 1,
      "hits": [
         {
            "_index": "analytics",
            "_type": "event",
            "_id": "AU6S1QrhLJ3RT4VnGs-M",
            "_score": 1,
            "_source": {
               "name": "James Madison",
               "event-date": {
                  "timestamp": "2015-07-15T08:00:00.000Z"
               }
            }
         }
      ]
   },
   "aggregations": {
      "dateagg": {
         "buckets": [
            {
               "key_as_string": "2015-07-15T00:00:00.000Z",
               "key": 1436918400000,
               "doc_count": 0
            },
            {
               "key_as_string": "2015-07-15T01:00:00.000Z",
               "key": 1436922000000,
               "doc_count": 0
            },
            {
               "key_as_string": "2015-07-15T02:00:00.000Z",
               "key": 1436925600000,
               "doc_count": 0
            },
            {
               "key_as_string": "2015-07-15T03:00:00.000Z",
               "key": 1436929200000,
               "doc_count": 0
            },
            {
               "key_as_string": "2015-07-15T04:00:00.000Z",
               "key": 1436932800000,
               "doc_count": 0
            },
            {
               "key_as_string": "2015-07-15T05:00:00.000Z",
               "key": 1436936400000,
               "doc_count": 0
            },
            {
               "key_as_string": "2015-07-15T06:00:00.000Z",
               "key": 1436940000000,
               "doc_count": 0
            },
            {
               "key_as_string": "2015-07-15T07:00:00.000Z",
               "key": 1436943600000,
               "doc_count": 0
            },
            {
               "key_as_string": "2015-07-15T08:00:00.000Z",
               "key": 1436947200000,
               "doc_count": 1
            }
         ]
      }
   }
}
```

As you can see, we are getting the expected hits ("James Madison"), and the document is in the correct bucket. I would prefer the first bucket to start at the beginning of the day in the timezone I specified in the query ("-05:00"), and not at the beginning of the day in UTC.

Thanks for your review, and thanks your hard work!

### PR DESCRIPTION
**Pull request by cbuescher**
This PR adds a timezone field to ValueParser.DateMath that is
set to UTC by default but can be set using the existing constructors.
This makes it possible for extended bounds setting in DateHistogram
to also use date math expressions that e.g. round by day and apply
this rounding in the time zone specified in the date histogram
aggregation request.

Closes #12278

### CODE REVIEW

**Comment by jpountz** [comment]
LGTM

**Comment by feltnerm** [comment]
:100: ! :beers: @cbuescher

**Comment by feltnerm** [comment]
Any chance this will make it into the latest 1.x? Would be great!

**Comment by cbuescher** [comment]
@feltnerm Sadly, I wouldn't count on it. Currently working towards 2.0, only major bugfixes get backported to the 1.x branches.

**Comment by cbuescher** [comment]
@jpountz @clintongormley any opinion if this should be backported to 2.0?

**Comment by jpountz** [comment]
It's a bug fix and risks look low to me so I would say yes.

**Comment by cbuescher** [comment]
Also backported to 2.0 branch with 8ba2c9ba

**Pull request merged**
