### PR TITLE
[DOCS] Document security limitation for terms enum API

### LINKED ISSUE #83632: [Docs update] Document security limitation for _terms_enum
The [_terms_enum](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/search-terms-enum.html) API doesn't return any suggestion when document level security is enabled. This seems to be the intended behavior. Could you please update the [security limitations](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-limitations.html) page to mention this as it's not currently mentioned?

Thanks

### PR DESCRIPTION
**Pull request by abdonpijpelink**
Closes #83632

### CODE REVIEW

**Review by javanna — APPROVED** [review]
LGTM, shall we add a link to the DLS docs?

**Comment by abdonpijpelink** [comment]
I did add a link to https://www.elastic.co/guide/en/elasticsearch/reference/master/search-terms-enum.html 
Is there another page you'd like to link to?

**Comment by javanna** [comment]
> Is there another page you'd like to link to?
No, sorry, I got confused on which page we are updating. Do we also need to list this under the terms enum API docs?

**Comment by abdonpijpelink** [comment]
>Do we also need to list this under the terms enum API docs?

That would be very nice. I notice that we don't do that for other similarly impacted APIs like [suggesters](https://www.elastic.co/guide/en/elasticsearch/reference/master/search-suggesters.html) and [profile](https://www.elastic.co/guide/en/elasticsearch/reference/master/search-profile.html) though. Do we want to make this a larger effort to consistently add a note to all these docs?

**Comment by javanna** [comment]
> Do we want to make this a larger effort to consistently add a note to all these docs?

I think it could be a good idea but in a follow-up PR, thanks for checking that!

**Pull request merged**
