### PR TITLE
vector tiles: Add runtime dependency on slf4j

### PR DESCRIPTION
**Pull request by iverase**
During testing I noticed that sometimes we could hit an exception that was killing the node due to a `ClassNotFoundException`. This is due to some geometries that Elasticsearch accepts but that are illegal for the underlaying topology library that the mvt library is using. For example, Elasticsearch accepts overlapping polygons in a multi polygon which is an illegal geometry for the underlaying library.

When an illegal geometry is sent to the mvt library and fails parsing it, it tries to log an error using slf4j library. Because currently we don't provide this library as a dependency it throws a ClassCastException and the node gets kill. 

This PR adds this dependency to the module.

### CODE REVIEW

**Comment by iverase** [comment]
It seems this issue happens when we feed the library with an invalid geometry. In #75874 I am proposing to add a check on the geometry so that might be enough to get around this issue but I might not be checking all possibilities so still feedback here would be appreciated.

**Review by rjernst — COMMENTED** [review]
The slf4j/log4j change is fine, but it appears there are other unrelated changes in this PR? I see a bunch of renaming and a test.

**Comment by iverase** [comment]
That is just a test to reproduce the issue. I rename a few things to be able to reuse some code for the test.

**Review by rjernst — APPROVED** [review]
LGTM

**Pull request merged**
