### PR TITLE
Logging: Drop another deprecated Loggers method

### PR DESCRIPTION
**Pull request by nik9000**
Drop a method from `Loggers` that we deprecated because it just
delegated to `LogManager`.

### CODE REVIEW

**Comment by nik9000** [comment]
I've marked this as `breaking-java` because plugins will have to switch to `LogManager` as well.

**Comment by nik9000** [comment]
Relates to #32174.

**Comment by nik9000** [comment]
@elasticmachine, retest this please.

**Review by alpar-t — APPROVED** [review]
LGTM

**Comment by nik9000** [comment]
Thanks for reviewing @atorok! I finally merged this.

**Pull request merged**
