### PR TITLE
Add qa/evil-tests 

### PR DESCRIPTION
**Pull request by rmuir**
There are a couple concrete issues this PR tries to address:
- removes guava as a test dependency. A ton of work happened here, but I think users will be happier when its no longer a test dependency, either.
- ensure some "evil tests" like SeccompTests are running in jenkins. Today they are not running in jenkins, and this will fix that.
- remove bogus permissions like "accessUserInformation" that are only needed... to test pluginmanager, which itself does not run under securitymanager anyway (so the whole thing is currently silly).

In general, functionality should be tested in a realistic way. But sometimes we need to break the rules, this gives us a place to do it. Going forwards I would like to explore giving each test its own clean JVM here too (lets just make it a real sandbox for doing evil tests).

Maybe we are getting closer to the point where pluginmanager is really ready to be factored out of core and then those tests can be moved out of here, but for now I think its a better place, since we need to do evil stuff like `chown`/`chmod` but at the same time, we want to know if e.g. third party code is doing that.

### CODE REVIEW

**Comment by s1monw** [comment]
+1

**Comment by jpountz** [comment]
LGTM!

**Comment by rmuir** [comment]
This PR just waits on a tweak by @rjernst so that `test` for this module is called automatically by `check`, for some reason that currently isn't happening, not sure why.

**Comment by rjernst** [comment]
@rmuir I pushed a fix for check depending on test. I also commented out maven local, and added a comment explaining when to uncomment. The other changes LGTM.

**Pull request merged**
