### PR TITLE
Remove lang-python and lang-javascript

### LINKED ISSUE #20698: Remove python and javascript plugins
The  `lang-python` and `lang-javascript` plugins were deprecated in 5.0 and should be removed in 6.0 (along with the docs)

### PR DESCRIPTION
**Pull request by nik9000**
They were deprecated in 5.0. We are concentrating on making
Painless awesome rather than supporting every language possible.

Closes #20698

### CODE REVIEW

**Comment by nik9000** [comment]
This should come after we get #20621 so we can get that in in a way that we can backport to 5.x easilly.

**Comment by nik9000** [comment]
@rjernst and @jdconrad, I've rebased this and I think now might be the right time for this....

**Review by jdconrad — APPROVED** [review]
LGTM!  Thanks for doing this.  I must admit I'm a bit envious of all the negative lines you're accumulating here :).

**Comment by nik9000** [comment]
> LGTM! Thanks for doing this. I must admit I'm a bit envious of all the negative lines you're accumulating here :).

All the folks that worked on painless really earned them. I just swooped in at the last minutes to take all that negative line glory....

**Pull request merged**
