### PR TITLE
Release `TranslogSnapshot` buffer after iteration

### LINKED ISSUE #106390: `MultiSnapshot` should release each `TranslogSnapshot` when no longer needed
Seen in a heap dump from a node that went OOME: we ran out of memory replaying a translog of 83 generations, each of which ended with an enormous document (all over 100MiB, some over 1GiB, see https://github.com/elastic/elasticsearch/issues/106389). It seems that we do not re-use the `TranslogSnapshot#reuse` buffer across generations, but nor do we release it, we just keep the last operation of each generation in memory until the whole translog replay is done.

### PR DESCRIPTION
**Pull request by DaveCTurner**
Closes #106390

### CODE REVIEW

**Comment by DaveCTurner** [comment]
I tried various ideas for testing this change but couldn't really come up with anything. It'd be easier if we were using `BigArrays` rather than just allocating enormous contiguous buffers here but that's a pretty big change with questionable performance implications. Suggestions welcome.

**Comment by Tim-Brooks** [comment]
> Suggestions welcome

In the end we are gong to be reliant on whatever byte implementation the object store client is using. You could use `BigArrays` and do a first copy of the input stream -> pooled bytes. And then use an `StreamInput` to read releasable variant for the actual translog operation. A copy in exchange for no allocations.

I'm agnostic as I doubt either the allocations or copying are overlying expensive for occasional recoveries. You can kind of compute how many bytes will be allocated based on the buffered translog size. This will get bigger as refresh optimizations kick in.

**Review by Tim-Brooks — APPROVED** [review]
LGTM

**Comment by DaveCTurner** [comment]
> This will get bigger as refresh optimizations kick in.

I'm proposing this change because it fixes an OOME we saw in practice when replaying translogs in stateful ES, not stateless.

**Pull request merged**
