### PR TITLE
Add rollover to watcher history ILM policy

### PR DESCRIPTION
**Pull request by probakowski**
In `7.x` watcher history was kept for 7 days with daily index pattern and ILM policy that had only delete phase. In `8.x` we've moved to data stream but policy was not updated so watcher history index would grow forever. This change fixes that by adding rollover. 3 days rollover and 4 days delete mean that data will be kept for 7 days as before.

### CODE REVIEW

**Review by andreidan — CHANGES_REQUESTED** [review]
Thanks for working on this Przemko.

Would we not want to add a `max_primary_shard_size` condition to the rollover action? 

Also, I think we need to create the ILM policy with a different name and update the composable template for the watch history data stream to point to this newly named and updated ILM policy (that contains rollover). 
This is because the 7.x clusters that contain the ILM policy named `watch-history-ilm-policy` without rollover will not get the updated policy when they upgrade to 8.0 because we only PUT ILM policies if they don't exist already https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/template/IndexTemplateRegistry.java#L450

Unless I'm missing something? What do you think?

**Comment by probakowski** [comment]
You are right, it wouldn't be picked up, I've changed name of the policy so it will be added.
With that policy I tried to preserve the same retention period of 7 days. With `max_primary_shard_size` chatty watcher history could be retained for 4 days, right? I'm on the fence here TBH, don't know how much folks depend on the timing here

**Comment by andreidan** [comment]
@probakowski "With max_primary_shard_size chatty watcher history could be retained for 4 days, right?"

That's correct. I'd, personally, prefer reasonably sized shards (and the history index not taking all the space it can find in 3 days) to a reduced history timeframe.

@jakelandis what would you recommend here?

**Review by andreidan — CHANGES_REQUESTED** [review]
Thanks for iterating on this Przemko. I'd finally suggest adding `max_primary_shard_size` to `50GB` to the `rollover` action

**Comment by probakowski** [comment]
Ok, I've added it

**Comment by probakowski** [comment]
@elasticmachine update branch

**Review by andreidan — APPROVED** [review]
LGTM (pending CI :) ), thanks for working on this Przemko

**Pull request merged**
