### PR TITLE
Updates the grok patterns to be consistent with the logstash

### PR DESCRIPTION
**Pull request by austintp**
The changes suggested to the grok patterns file in Elasticsearch are ones already documented for logstash.

https://github.com/logstash-plugins/logstash-patterns-core/commit/02fc1c47e094cbbe3e482754cda95088827da327#diff-5d5996f507c4a9e3bcc205235e2a3ecc

https://github.com/logstash-plugins/logstash-patterns-core/commit/68ee6fdb4ab50280cb97605d1287fed2f50fa234#diff-5d5996f507c4a9e3bcc205235e2a3ecc

https://github.com/logstash-plugins/logstash-patterns-core/commit/939210be0635200ee44418f9af55de254a1ddeb3#diff-5d5996f507c4a9e3bcc205235e2a3ecc

https://github.com/logstash-plugins/logstash-patterns-core/commit/3bb6563facc41a1278aa6a9b86a0610dd3e62fe0#diff-5d5996f507c4a9e3bcc205235e2a3ecc

https://github.com/logstash-plugins/logstash-patterns-core/commit/ad4947d6b7aab0f217bd82cdcc82c47ea42f743e#diff-5d5996f507c4a9e3bcc205235e2a3ecc

### CODE REVIEW

**Comment by talevy** [comment]
thanks for the PR @austintp. mind signing our CLA? Once you do, I will be happy to merge your changes and follow-up with a full-resync of the logstash-patterns-core repo into Ingest Node.

**Comment by austintp** [comment]
Sorry for the delay. I've now signed the CLA.

**Comment by karmi** [comment]
Hi @austintp, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/elasticsearch/pull/27181.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by austintp** [comment]
@karmi Done.

**Comment by pcsanwald** [comment]
@jakelandis will you review this PR?

**Comment by jakelandis** [comment]
@elasticmachine ok to test

**Comment by jakelandis** [comment]
@elasticmachine test this please

**Comment by jakelandis** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by jakelandis** [comment]
@elasticmachine run elasticsearch-ci/1
@elasticmachine run elasticsearch-ci/2

**Comment by jakelandis** [comment]
@elasticmachine run elasticsearch-ci/1

**Review by jakelandis — APPROVED** [review]
thanks for the PR @austintp ! (sorry it took so long to adopt)

One minor change reversal of the change to TIMESTAMP_ISO8601 (i.e. it is not getting updated) to help preserve passivity within the ingest node.

**Pull request merged**
