### PR TITLE
[ML] Trained Model Deployment upgrade tests

### PR DESCRIPTION
**Pull request by davidkyle**
Hint for the reviewer the supporting methods for creating the deployment etc are exactly the same

### CODE REVIEW

**Review by benwtrent — APPROVED** [review]
:shipit:

**Comment by benwtrent** [comment]
@davidkyle it. may be good to run the full bwc suite on this PR before merging to make sure its all good.

**Comment by davidkyle** [comment]
retest this please

**Comment by benwtrent** [comment]
run elasticsearch-ci/full-bwc

**Pull request closed without merging**
