### PR TITLE
Don't index counter and gauge fields by default

### PR DESCRIPTION
**Pull request by martijnvg**
This change alters the default for the `index` option from `true` to `false` for number fields in tsdb indices and if 
`time_series_metric` has been set to `counter` or `gauge`.

The idea behind the change is that in tsdb counter and gauges field are unlikely to get queried, so having point
fields in the Lucene index doesn't make much sense. As it just takes up disk space and other resources. 
With this change counter and gauge fields remain to be queryable, using doc values based queries, but that will
be slower.

### CODE REVIEW

**Review by romseygeek — APPROVED** [review]
LGTM!

**Comment by martijnvg** [comment]
Thanks Alan!

**Comment by jpountz** [comment]
Is `scaled_float` covered by this change?

**Comment by martijnvg** [comment]
> Is scaled_float covered by this change?

Good catch. No, it isn't. I will fix this in a followup pr.

Are there other fields besides this field type, regular numeric field type and aggregate double metric field type that need this change as well?

**Comment by romseygeek** [comment]
I think `unsigned_long` also needs to be covered.

**Pull request merged**
