### PR TITLE
Operator/slm policy

### PR DESCRIPTION
**Pull request by grcevski**
This PR adds support for /_slm/policy in file based settings.

Relates to https://github.com/elastic/elasticsearch/issues/89183

### CODE REVIEW

**Comment by grcevski** [comment]
I plan to document the code a bit more, getting a PR out to ensure I get a start on the testing.

**Comment by grcevski** [comment]
I'm going to split off the repo part into separate PR.

**Comment by grcevski** [comment]
@elasticsearchmachine run elasticsearch-ci/docs

**Review by dakrone — APPROVED** [review]
This LGTM, it's actually not a super complex change, just large due to testing (yay tests). I'm not super close to the file-based settings stuff, but I assume it's totally okay for a single policy failure to fail the entire operation, is that correct?

**Comment by grcevski** [comment]
> I'm not super close to the file-based settings stuff, but I assume it's totally okay for a single policy failure to fail the entire operation, is that correct?

Yes, that's true, any error should fail the entire update, including all other settings that are not SLM specific.

**Comment by grcevski** [comment]
Thanks Lee!

**Pull request merged**
