### PR TITLE
[DOCS] Fix delimited blocks for Asciidoctor migration

### PR DESCRIPTION
**Pull request by jrodewig**
In Asciidoctor, these delimited block resets the nested ordered list (changing `d` to `a` and `6` to `1`). This fixes those breaking changes.

### Asciidoctor output before changes
asciidoctor-before

### Asciidoctor output after changes
asciidoctor-after

### AsciiDoc output after changes
asciidoc-output

### CODE REVIEW

**Review by nik9000 — APPROVED** [review]
LGTM

**Review by nik9000 — COMMENTED** [review]
CI blew up on it! Did you happen to commit half of the fix? Like just the opening of the delimited block but not the closing?

**Comment by jrodewig** [comment]
Yep. That's exactly what happened. Fixed with 7ebb143.

**Review by nik9000 — APPROVED** [review]
Now LGTM

**Pull request merged**
