### PR TITLE
Remove license state listeners on closables

### LINKED ISSUE #35627: LocalExporter leaks a licence state listener
Today, `LocalExporter` removes its `licenseChanged()` method from the licence state listener when closed:

https://github.com/elastic/elasticsearch/blob/816e6f6a08be821d8ec01b51bf383544d1e341b0/x-pack/plugin/monitoring/src/main/java/org/elasticsearch/xpack/monitoring/exporter/local/LocalExporter.java#L155

However in fact this does nothing, because it involves a new `Runnable` that is different from the one we added earlier. The fix is fairly trivial, but writing the test for the fix has overflowed my stack of yaks so I'm spilling it out here.

### LINKED ISSUE #35628: OptOutQueryCache leaks a licence state listener
Today, `OptOutQueryCache` adds a listener for changes to licence state:

https://github.com/elastic/elasticsearch/blob/816e6f6a08be821d8ec01b51bf383544d1e341b0/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/accesscontrol/OptOutQueryCache.java#L46

It does not, however, remove this listener when closed. Possibly this is related to this forum issue: https://discuss.elastic.co/t/post-upgrade-issues-6-4-2-es-heap-running-away-6-5-0-too/151096/24 (although I don't understand the full chain of events that leads from this to an OOM).

### PR DESCRIPTION
**Pull request by jasontedor**
We have a few places where we register license state listeners on transient components (i.e., resources that can be open and closed during the lifecycle of the server). In one case (the opt-out query cache) we were never removing the registered listener, effectively a terrible memory leak. In another case, we were not un-registered the listener that we registered, since we were not referencing the same instance of Runnable. This commit does two things:
  - introduces a marker interface LicenseStateListener so that it is easier to identify these listeners in the codebase and avoid classes that need to register a license state listener from having to implement Runnable which carries a different semantic meaning than we want here
  - fixes the two places where we are currently leaking license state listeners

Relates #33328
Closes #35627 
Closes #35628

### CODE REVIEW

**Review by romseygeek — COMMENTED** [review]
LGTM, thanks @jasontedor

**Comment by DaveCTurner** [comment]
Closes #35627 and #35628

**Comment by jasontedor** [comment]
Oh, thanks @DaveCTurner, I had not seen those! I will add that to the top-level comment so they are closed when this is merged.

**Review by jaymode — APPROVED** [review]
LGTM

**Pull request merged**
