### PR TITLE
Only one of azure key or token can be specified in 3rd party tests

### PR DESCRIPTION
**Pull request by tlrx**
#54803 introduces more QA tests for Azure storage service, but they fail the build is one of the key or token is missing. It should instead work like `repository-azure:qa` tests.

### CODE REVIEW

**Comment by tlrx** [comment]
@elasticmachine run elasticsearch-ci/bwc
@elasticmachine run elasticsearch-ci/default-distro

**Comment by tlrx** [comment]
@elasticmachine update branch

**Comment by tlrx** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Review by original-brownbear — APPROVED** [review]
LGTM, test failures seem unrelated

**Comment by original-brownbear** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by tlrx** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by tlrx** [comment]
@elasticmachine update branch

**Comment by tlrx** [comment]
Thanks Armin!

**Pull request merged**
