### PR TITLE
IndexShard should not return null stats

### PR DESCRIPTION
**Pull request by vladimirdolzhenko**
IndexShard should not return null stats - empty stats or AlreadyClosedException if it's closed is better

that eliminates NPE in [PrimaryReplicaSyncer:87](https://github.com/elastic/elasticsearch/blob/4d7447cb5e67f2739d5edc374e9c7c3a46d414da/server/src/main/java/org/elasticsearch/index/shard/PrimaryReplicaSyncer.java#L87) on closing shard as well

Relates to #30176

### CODE REVIEW

**Comment by bleskes** [comment]
> that eliminates NPE in PrimaryReplicaSyncer as well

Can you give a pointer to what this is? (there are others like this too)

**Comment by vladimirdolzhenko** [comment]
@bleskes I've update PR description

**Comment by vladimirdolzhenko** [comment]
test this please

**Review by dakrone — APPROVED** [review]
LGTM, we discussed more scenarios and this looks like the best one

**Comment by vladimirdolzhenko** [comment]
thanks @dakrone for review

**Pull request merged**
