### PR TITLE
Really drop symlink env test on Windows

### PR DESCRIPTION
**Pull request by sabi0**
Rectification of #102762

`FileSystemException` "message" may also contain a file name:
https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/nio/file/FileSystemException.java#L118

Check "reason" instead.

### CODE REVIEW

**Comment by thecoop** [comment]
@elasticsearchmachine test this please

**Comment by thecoop** [comment]
@elasticmachine ok to test

**Comment by thecoop** [comment]
buildkite test this

**Comment by brianseeders** [comment]
buildkite test this

**Review by thecoop — APPROVED** [review]

**Comment by thecoop** [comment]
Thanks for the PR @sabi0 !

**Pull request merged**
