### PR TITLE
Scripting: Remove Dead Code from Painless Module

### PR DESCRIPTION
**Pull request by original-brownbear**
Neither this method nor the removed class are used anymore.

### CODE REVIEW

**Review by nik9000 — APPROVED** [review]
LGTM though it should wait on @jdconrad because he is the expert here.

**Review by jdconrad — APPROVED** [review]
LGTM as well.  writeBranch was left behind by a performance optimization that was considered unnecessary at the time.  I assume StashingTokenFactory was used as part of regex parsing, but @nik9000 knows the history there better than I do.

**Comment by nik9000** [comment]
> I assume StashingTokenFactory was used as part of regex parsing, but @nik9000 knows the history there better than I do.

I believe I used it for the hacks that inserted semicolons actually but you replaced my hacks with nicer parsing code.

**Comment by original-brownbear** [comment]
@nik9000 @jdconrad thanks guys, this should go into `6.x` too right?

**Comment by jdconrad** [comment]
@original-brownbear Yes, 6.x as well.  Thanks for fixing this!

**Pull request merged**
