### PR TITLE
Remove redundant BytesQueryBuilder in favour of using WrapperQueryBuilder internally

### PR DESCRIPTION
**Pull request by javanna**
BytesQueryBuilder was introduced to be used internally by the phrase suggester and its collate feature. It ended up being exposed via Java api but the existing WrapperQUeryBuilder could be used instead. Added WrapperQueryBuilder constructor that accepts a BytesReference as argument.

One other reason why this query builder should be removed is that it gets on the way of the query parsers refactoring, given that it's the only query builder that allows to build a query through java api without having a corresponding query parser.

### CODE REVIEW

**Comment by javanna** [comment]
Heya @areek can you please double check that I am not missing anything here? :)

**Comment by areek** [comment]
Hey @javanna, this looks good! Thanks for fixing this :)

**Comment by areek** [comment]
Hey @javanna, I have added a test that breaks with this change. The test along with the fix can be found here https://github.com/elastic/elasticsearch/compare/elastic:master...areek:pr/10919?expand=1

**Comment by javanna** [comment]
Hey @areek I did some more testing and compared the two constant score query outputs:

Before:
```
{
  "constant_score" : {
    "filter" : {
      "query" : {
        "match_phrase" : {
          "title" : "united states houses of representatives elections in washington 2006"
        }
      }
    }
  }
}
```

After:
```
{
  "constant_score" : {
    "filter" : {
      "wrapper" : {
        "filter" : "eyJxdWVyeSI6eyJtYXRjaF9waHJhc2UiOnsidGl0bGUiOiJ1bml0ZWQgc3RhdGVzIGhvdXNlcyBvZiByZXByZXNlbnRhdGl2ZXMgZWxlY3Rpb25zIGluIHdhc2hpbmd0b24gMjAwNiJ9fX0="
      }
    }
  }
}
```

where the binary portion contains the following:
```
{"query":{"match_phrase":{"title":"united states houses of representatives elections in washington 2006"}}}
```

There is an additional layer of wrapping, which is expected since we use the wrapper filter, but this looks good to me, I don't see any problem. I pulled in your additional test but didn't seem to fail for me. Let me know what you think.

**Comment by javanna** [comment]
I just rebased this given that #10985 went in and BytesFilterBuilder became BytesQueryBuilder. Change looks similar though, we still have to wrap it into a constant score query. @jpountz can you please have a look too?

**Comment by jpountz** [comment]
LGTM

**Comment by areek** [comment]
LGTM!

**Pull request closed without merging**
