### PR TITLE
Change index removal reason when IndicesService is stopping

### PR DESCRIPTION
**Pull request by tlrx**
When `IndicesService` is stopping on a data node, it closes every `IndexService` instances that are existing by calling the `removeIndex(Index, IndexRemovalReason, String)` method.

The `IndexRemovalReason` that is passed as a parameter in this case is `NO_LONGER_ASSIGNED` which is also the one passed in other situation like removing an index because it got assigned to another data node. The fact that the same reason is used in multiple cases make it difficult for `IndexEventListener` to do the distinction between an index closed because the node is shutting down and an index closed between it moved away.

This pull request changes the `IndexRemovalReason` used when closing the `IndicesService` to be `CLOSED` that, I think, better reflect the reason why `IndexService` are closed.

### CODE REVIEW

**Review by DaveCTurner — COMMENTED** [review]
Hmm today `CLOSED` means `POST /index/_close` and friends, I don't think we should combine that with "shutting down". If we need the distinction, can we add a new value for the `IndexRemovalReason` enum instead?

**Comment by tlrx** [comment]
Maybe `NODE_SHUTDOWN`  ? Or just `SHUTDOWN`?

**Comment by DaveCTurner** [comment]
`SHUTDOWN` sounds good to me

**Comment by tlrx** [comment]
Thanks David, I updated the reason.

**Review by DaveCTurner — APPROVED** [review]
LGTM.

I checked for, but did not find, places where we branch based on the index removal reason which would need updating too.

**Comment by tlrx** [comment]
Thanks David. I checked too before opening the PR and did not found anything that would need to be adapted.

**Pull request merged**
