### PR TITLE
Skip global checkpoint sync for closed indices

### PR DESCRIPTION
**Pull request by dnhatn**
The verifying-before-close step ensures the global checkpoints on all shard copies are in sync; thus, we don' t need to sync global checkpoints for closed indices.

Relate https://github.com/elastic/elasticsearch/issues/33888#issuecomment-489891795

### CODE REVIEW

**Review by henningandersen — COMMENTED** [review]
Would it be an option to skip resync for closed indices? I think we rely on either having a perfect commit to use or doing a file based recovery anyway.

**Comment by dnhatn** [comment]
@henningandersen Thanks for looking.

> Would it be an option to skip resync for closed indices?

Yes, we can skip as resync is a noop for closed indices. I explored this option then prefer other option to avoid adding one more exception for closed indices. I can make this change again - it's pretty contained.

> This looks dangerous, since ReadOnlyEngine.syncTransLog() does nothing. So we will accept the global checkpoint on replica, but it will not be persisted.

We can add an assertion to make sure that the persisted global checkpoint equals to the in-memory value.

**Comment by dnhatn** [comment]
@henningandersen I discussed this with Tanguy and Yannick during GAH. We need to keep resync; otherwise, replicas won't see the new primary term. I updated this PR to skip global checkpoint sync for closed indices. Can you please take another look? Thank you!

**Review by ywelsch — APPROVED** [review]
LGTM

**Comment by dnhatn** [comment]
Thanks @henningandersen @ywelsch.

**Pull request merged**
