### PR TITLE
TransportNodesAction impls are local-only

### PR DESCRIPTION
**Pull request by DaveCTurner**
There are no remote invocations of any actions derived from
`TransportNodesAction` so there is no need to register the top-level
action with the `TransportService`, and that means that all the code
related to de/serialization of the top-level request and response is
unused and can be removed.

Relates #100111
Relates #100878

### CODE REVIEW

**Comment by DaveCTurner** [comment]
I didn't see any of these being used in a cross-cluster context, so as per #100111 I think they're all local-only. Let's see what CI says.

**Comment by DaveCTurner** [comment]
Failure is https://github.com/elastic/elasticsearch/issues/99422.

@elasticmachine please run elasticsearch-ci/part-2

**Review by ldematte — APPROVED** [review]
LGTM. Only a couple of Q: 
- The only reason BaseNodeRequest has not been changed to `TransportAction.localOnly();` is because `super()` is called from inheritors and it shouldn't. After #100878, we can come back and change it, right?
- Is there a place where BaseNodeResponse.readNodesFrom and writeNodesTo are not just `TransportAction.localOnly();`?

**Comment by DaveCTurner** [comment]
> After #100878 we can come back and change it, right?

Right.

> Is there a place where BaseNodeResponse.readNodesFrom and writeNodesTo are not just `TransportAction.localOnly();`?

Yeah there's a couple of places where the base response is wrapped up in another response that I didn't fancy pulling to bits here, see e.g. `org.elasticsearch.xpack.core.analytics.action.AnalyticsStatsAction.Response` or `org.elasticsearch.xpack.core.spatial.action.SpatialStatsAction.Response`, and several more that have nontrivial test suites which I didn't want to unpick here.

**Pull request merged**
