### PR TITLE
cleanup for the internal plugin infrastructure

### PR DESCRIPTION
**Pull request by uboness**
- Introduced the `JvmPlugin` wrapper (to add additional internal functionality to the plugin)
- fixed `hashcode()` on the `PluginInfo`
- extracted the `PluginsInfo` caching logic to `CachableReference` construct in utils
- cleaned up the `PluginsService` class to make the logic there more structured/understandable

### CODE REVIEW

**Comment by javanna** [comment]
Hey @tlrx what's the status here? Is it replaced by the newer refactoring of the `PluginManager` that you just sent?

**Comment by tlrx** [comment]
@javanna this is a clean up from @uboness and it is not replaced by #9998 but I looked quickly at the code and I think this clean up is welcome.

I'll review this - hopefully quicky - since it has already one year old.

**Comment by jpountz** [comment]
@uboness Plugins management having changed a lot recently, do some of the changes in your PR still apply or should we just close it?

**Comment by uboness** [comment]
some things here still apply (e.g. fixing the `PluginInfo#hashcode()`), but obviously this PR needs to be rebased first

**Comment by clintongormley** [comment]
This PR is very out of date.  Closing

**Pull request closed without merging**
