### PR TITLE
[DOCS] Move rollup APIs to docs

### PR DESCRIPTION
**Pull request by lcawl**
Related to https://github.com/elastic/elasticsearch/issues/30665

This PR moves the source files from x-pack/docs/en/rest-api/rollup to docs/reference/rollup

### CODE REVIEW

**Comment by polyfractal** [comment]
Hm, I think some things got lost in the transition over.  The failure from CI reproduces locally (looks like it's trying to recreate the same job which already exists), and I see that there are errors related to the REST spec:

```
Failure at [reference/rollup/apis/get-job:29]: rest api [xpack.rollup.put_job] doesn't exist in the rest spec
```

I think we will have to move the REST spec and yaml tests over too?  Or adjust the runner to look in multiple places for the spec?

**Comment by polyfractal** [comment]
Ok, so the "already exists" job is because we cleanup the rollup state in [`XPackRestIT`](https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/src/test/java/org/elasticsearch/xpack/test/rest/XPackRestIT.java#L264), and there's no equivalent in `DocsClientYamlTestSuiteIT`.

We can move over `RollupRestTestStateCleaner` and friends, but I'm not sure how that will affect things with the OSS doc tests.

I think Monitoring and ML will have similar issues.

@nik9000 thoughts?

**Comment by polyfractal** [comment]
@lcawl sorry, this totally fell off my radar.  I'll take over the PR and get the test stuff fixed up first thing next week!

**Comment by lcawl** [comment]
@polyfractal I've disabled the failing tests for now to enable the files to move.  Is it acceptable to debug the test failures in a new PR after the move?

**Comment by polyfractal** [comment]
:+1:

**Pull request merged**
