### PR TITLE
Update get snapshot status API doc

### PR DESCRIPTION
**Pull request by pxsalehi**
Make it clear that this API should be used only if the detailed shard info is needed and only on ongoing snapshots. Remove incorrectly mentioned `STATE` value.

### CODE REVIEW

**Review by DaveCTurner — COMMENTED** [review]
Looks good but let's also adjust the corresponding comment to match:

https://github.com/elastic/elasticsearch/blob/cfbda244b81a47915f3ea1bedfd40287df2fe380/server/src/main/java/org/elasticsearch/action/admin/cluster/snapshots/status/TransportSnapshotsStatusAction.java#L335-L336

**Comment by pxsalehi** [comment]
I've removed the TODO also. It doesn't seem like something that needs to be done. if that's not the case and you know a more concrete todo, let me know, I can add it back and add the v9 tag.

**Review by DaveCTurner — APPROVED** [review]
LGTM but let's backport this to 8.15 and 8.14 too.

**Comment by pxsalehi** [comment]
@elasticmachine update branch

**Pull request merged**
