### PR TITLE
Synchronize WriteReplicaResult callbacks

### PR DESCRIPTION
**Pull request by ywelsch**
`TransportWriteAction.WriteReplicaResult` is not properly synchronized, which can lead to a data race between the thread that calls `respond` and the `AsyncAfterWriteAction` that calls either `onSuccess` or `onFailure`. This data race results in the response listener not being called, which ultimately results in a stuck replication task on the replica.

### CODE REVIEW

**Review by DaveCTurner — APPROVED** [review]
LGTM. We discussed potential performance implications via another channel and concluded this is ok.

**Review by tlrx — APPROVED** [review]
LGTM - Great catch!

**Review by bleskes — COMMENTED** [review]
good catch

**Comment by ywelsch** [comment]
@elasticmachine run the gradle build tests 1

**Pull request merged**
