### PR TITLE
Fix InternalAutoDateHistogramTests

### LINKED ISSUE #39497: [CI] InternalAutoDateHistogramTests::testReduceRandom fails reproducable for certain seed
The following test failed in a PR-build and is reproducible for me on my local box:

```
./gradlew :server:unitTest -Dtests.seed=24D81295C2796C6C -Dtests.class=org.elasticsearch.search.aggregations.bucket.histogram.InternalAutoDateHistogramTests -Dtests.method="testReduceRandom" -Dtests.security.manager=true -Dtests.locale=el-CY -Dtests.timezone=Europe/Nicosia -Dcompiler.java=11 -Druntime.java=8
```

fails with:

```
  1> [2019-02-28T10:25:36,507][INFO ][o.e.s.a.b.h.InternalAutoDateHistogramTests] [testReduceRandom] before test
  1> [2019-02-28T10:25:36,723][INFO ][o.e.s.a.b.h.InternalAutoDateHistogramTests] [testReduceRandom] after test
  2> REPRODUCE WITH: ./gradlew :server:unitTest -Dtests.seed=24D81295C2796C6C -Dtests.class=org.elasticsearch.search.aggregations.bucket.histogram.InternalAutoDateHistogramTests -Dtests.method="testReduceRandom" -Dtests.security.manager=true -Dtests.locale=el-CY -Dtests.timezone=Europe/Nicosia -Dcompiler.java=11 -Druntime.java=8
FAILURE 1.13s | InternalAutoDateHistogramTests.testReduceRandom <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: expected:<{1548979200000=1700}> but was:<{1548979200000=1569, 1551398400000=131}>
   >    at __randomizedtesting.SeedInfo.seed([24D81295C2796C6C:E4E5BE84E424F53A]:0)
   >    at org.elasticsearch.search.aggregations.bucket.histogram.InternalAutoDateHistogramTests.assertReduced(InternalAutoDateHistogramTests.java:200)
   >    at org.elasticsearch.search.aggregations.bucket.histogram.InternalAutoDateHistogramTests.assertReduced(InternalAutoDateHistogramTests.java:50)
   >    at org.elasticsearch.test.InternalAggregationTestCase.testReduceRandom(InternalAggregationTestCase.java:294)
   >    at java.lang.Thread.run(Thread.java:748)
  2> NOTE: leaving temporary files on disk at: /home/hendrik/work/git-elastic/elasticsearch/server/build/testrun/unitTest/J0/temp/org.elasticsearch.search.aggregations.bucket.histogram.InternalAutoDateHistogramTests_24D81295C2796C6C-001
  2> NOTE: test params are: codec=Asserting(Lucene80): {}, docValues:{}, maxPointsInLeafNode=1501, maxMBSortInHeap=7.215678116490036, sim=Asserting(org.apache.lucene.search.similarities.AssertingSimilarity@5f67521f), locale=el-CY, timezone=Europe/Nicosia
  2> NOTE: Linux 4.18.0-15-generic amd64/Oracle Corporation 1.8.0_191 (64-bit)/cpus=4,threads=1,free=449796568,total=514850816
  2> NOTE: All tests run in this JVM: [InternalAutoDateHistogramTests]
Completed [1/1] in 2.83s, 1 test, 1 failure <<< FAILURES!


> Task :server:unitTest FAILED
```

Tested only on master but likely applies to other versions.

### LINKED ISSUE #54540: org.elasticsearch.search.aggregations.bucket.histogram.InternalAutoDateHistogramTests.testReduceRandom fails
```
REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.search.aggregations.bucket.histogram.InternalAutoDateHistogramTests.testReduceRandom" -Dtests.seed=5D0B922735110573 -Dtests.security.manager=true -Dtests.locale=vi -Dtests.timezone=ACT -Dcompiler.java=13
```

```
Suite: Test class org.elasticsearch.search.aggregations.bucket.histogram.InternalAutoDateHistogramTests
  1> [2020-04-01T07:09:37,652][INFO ][o.e.s.a.b.h.InternalAutoDateHistogramTests] [testReduceRandom] before test
  1> [2020-04-01T07:09:37,773][INFO ][o.e.s.a.b.h.InternalAutoDateHistogramTests] [testReduceRandom] after test
  2> REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.search.aggregations.bucket.histogram.InternalAutoDateHistogramTests.testReduceRandom" -Dtests.seed=5D0B922735110573 -Dtests.security.manager=true -Dtests.locale=vi -Dtests.timezone=ACT -Dcompiler.java=13
  2> java.lang.AssertionError: expected:<{1583020800000=2193, 1585612800000=1561}> but was:<{1583020800000=2193, 1585699200000=1561}>
        at __randomizedtesting.SeedInfo.seed([5D0B922735110573:9D363E36134C9C25]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at org.elasticsearch.search.aggregations.bucket.histogram.InternalAutoDateHistogramTests.assertReduced(InternalAutoDateHistogramTests.java:203)
        at org.elasticsearch.search.aggregations.bucket.histogram.InternalAutoDateHistogramTests.assertReduced(InternalAutoDateHistogramTests.java:49)
        at org.elasticsearch.test.InternalAggregationTestCase.testReduceRandom(InternalAggregationTestCase.java:326)
        at org.elasticsearch.search.aggregations.bucket.histogram.InternalAutoDateHistogramTests.testReduceRandom(InternalAutoDateHistogramTests.java:112)
  2> NOTE: leaving temporary files on disk at: /home/baz/src/elastic/elasticsearch/server/build/testrun/test/temp/org.elasticsearch.search.aggregations.bucket.histogram.InternalAutoDateHistogramTests_5D0B922735110573-001
  2> NOTE: test params are: codec=Asserting(Lucene84), sim=Asserting(org.apache.lucene.search.similarities.AssertingSimilarity@91aab33), locale=vi, timezone=ACT
  2> NOTE: Linux 5.0.0-32-generic amd64/AdoptOpenJDK 14 (64-bit)/cpus=12,threads=1,free=487884488,total=536870912
  2> NOTE: All tests run in this JVM: [InternalAutoDateHistogramTests]

```

### PR DESCRIPTION
**Pull request by nik9000**
The test had errors around time units that have different length - think
leap years or months that aren't 30 days. This fixes those errors. In
the proces I've changed a bunch of things to debug the problem:

* Replace `currentTimeMillis` with a random time. Now the test fails
  randomly! Wonderful. Much better than on random days of the month.
* Generate buckets "closer together" to test random reduction. Without
  this we were super frequently getting stuck in the "year of century"
  rounding because *some* of the of the buckets we built were far apart.
  This generates a much greater variety of tests.
* Implement `toString` on `RoundingInfo` so I can debug without going
  crazy.
* Switch keys in the bucket assertions from epoch millis to `Instant`s
  so we can read the failures.

Closes #54540
Closes #39497

### CODE REVIEW

**Comment by nik9000** [comment]
I don't claim to fully understand how auto date histogram works here, but this test seems much less error prone.

**Comment by nik9000** [comment]
@elasticsearchmachine elasticsearch-ci/packaging-sample-unix-docker

**Comment by nik9000** [comment]
@elasticsearchmachine run elasticsearch-ci/packaging-sample-unix-docker

**Review by not-napoleon — APPROVED** [review]
I think this looks good to merge, but I worry that the test is still brittle.  Maybe we can do a follow up, or at least open a ticket, to just add some known value tests to the suite to cover common case.   Thanks for fixing this!

**Comment by nik9000** [comment]
Thanks for reviewing @not-napoleon! I'll look into building some more exact test cases that are more readable. Even that is fairly complex.

**Pull request merged**
