### PR TITLE
suggest sysctl command for querying vm.max_map_count

### PR DESCRIPTION
**Pull request by drewp**
there might not be an override in /etc/sysctl.conf

### CODE REVIEW

**Review by jasontedor — COMMENTED** [review]
The paragraph above this is explaining that the setting should be set permanently in `/etc/sysctl.conf` and this command shows the contents of `/etc/sysctl.conf` that would lead to the desired outcome. This is part of a larger section on how to set `vm.max_map_count` for Docker, depending on whether or not the user is using Docker on Linux versus macOS. I think the content text is okay in this context then?

**Comment by drewp** [comment]
In my situation, the value is already 262144 as recommended, and I don't have a line in sysctl.conf.  It seems like I don't have to do anything. I don't think I ever changed it, so maybe the default value in ubuntu 18.04 is already correct. We shouldn't ask all the ubuntu users to tweak their /etc files if the OS is already setting the limit high enough.

**Comment by javanna** [comment]
@jasontedor how do we want to proceed here? It seems like this change may be helpful to some, not sure whether it can also cause problems. Would you commenting on it?

**Comment by danielmitterdorfer** [comment]
Thank you very much for your pull request! As explained by @jasontedor above we think that the documentation should stay as is and therefore I hope you don't mind if I close the PR.

**Pull request closed without merging**
