### PR TITLE
Add assertWarnings capabilities to base token stream test case

### PR DESCRIPTION
**Pull request by benwtrent**
We need to be able to assert various warnings and check for such in typical token stream tests. This adds that capability.

### CODE REVIEW

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Comment by cbuescher** [comment]
I agree we should be able to assert warnings in tests extending ESTokenStreamTestCase. I ran into this in https://github.com/elastic/elasticsearch/pull/113614 as well.

However I see disadvantages in duplicating the warnings-related code from ESTestCase here, because it is basically code duplication. The solution I suggested in #113614 is changing ESTokenStreamTestCase to extend ESTestCase instead of 	BaseTokenStreamTestCase. By that we get all the test infrastructure we are used to from other tests. BaseTokenStreamTestCase doesn't give us anything other than static helper methods that can be imported in a one-liner if needed. I would argue that's better than carrying two copies of the warning header test infra around.

**Comment by benwtrent** [comment]
Eh, code duplication ain't that big of a deal, but let me see the impact of doing a switch (in isolation) as you suggest. Maybe its just as simple.

**Comment by benwtrent** [comment]
@cbuescher did it your way, not a huge change actually.

**Review by cbuescher — APPROVED** [review]
Thanks for making that change, LGTM.

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Review by tteofili — APPROVED** [review]

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Pull request merged**
