### PR TITLE
Update snowball document page.

### PR DESCRIPTION
**Pull request by yokotaso**
snowball project page is moved to http://snowballstem.org/

### CODE REVIEW

**Comment by clintongormley** [comment]
Hi @yokotaso 

Thanks for the PR. Please could I ask you to sign the CLA so that I can merge it in?
http://www.elasticsearch.org/contributor-agreement/

**Comment by yokotaso** [comment]
@clintongormley 
Thank you for your information. I have signed.

**Comment by yokotaso** [comment]
@clintongormley 
Thank you for your information. And I'm sorry for your inconvenience.
I have signed CLA. Cloud you check #14610 ?
Thank you!

**Comment by clintongormley** [comment]
thanks @yokotaso - merged

**Pull request merged**
