### PR TITLE
[DOCS] Update CCS compatibility matrix for 8.3

### PR DESCRIPTION
**Pull request by lockewritesdocs**
Updates the CCS compatibility table to include 8.3.

Preview link: https://elasticsearch_88906.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/modules-cross-cluster-search.html#ccs-supported-configurations

### CODE REVIEW

**Comment by lockewritesdocs** [comment]
@DaveCTurner, I think that this table is correct now based on the description of how local and remote clusters relate across versions.

**Comment by lockewritesdocs** [comment]
@DaveCTurner, please let me know if this table is now correct for `8.3`. If so, I'll get this PR merged.

**Comment by lockewritesdocs** [comment]
Can someone from @elastic/es-distributed review this PR? It's been languishing a bit and I'd love to get it merged.

**Comment by lockewritesdocs** [comment]
@elasticmachine update branch

**Review by arteam — APPROVED** [review]
LGTM. Thanks Adam!

**Pull request merged**
