### PR TITLE
SQL: [tests] Fix select csv spec and enable it

### PR DESCRIPTION
**Pull request by matriv**
Replace `||` and `&&` with `OR` and `AND` as the former are not
SQL standard operators.

### CODE REVIEW

**Comment by matriv** [comment]
retest this please

**Review by costin — APPROVED** [review]
LGTM.

**Review by astefan — APPROVED** [review]
LGTM

**Comment by matriv** [comment]
retest this please

**Comment by matriv** [comment]
Backported to `6.x` with ddc70f2d3b305037a0366fdc55cc92b5637e1067

**Comment by matriv** [comment]
Backported to `6.5` with a7c1386b8d9e0e99d16bc9e526659f61fe303e71

**Pull request merged**
