### PR TITLE
unmute 'Test url escaping with url mustache function' and bump logging

### PR DESCRIPTION
**Pull request by jakelandis**
Address test failures on #41172

If (when?) this test fails again please obtain the following information:

* Copy of the relevant failure
* Copy of the reproduce line
* The Jenkins build link 
* The Gradle scan link
* The relevant cluster logs from "Google Cloud Storage Upload Report" (link found in Jenkins build)

### CODE REVIEW

**Comment by jakelandis** [comment]
@elasticmachine run elasticsearch-ci/1

**Review by hub-cap — APPROVED** [review]

**Comment by hub-cap** [comment]
ty for the effort to clean these things up @jakelandis

**Comment by jpountz** [comment]
@jakelandis Is there anything left to backport?

**Comment by jakelandis** [comment]
I am trying to stabilize these tests in master before backporting. I will remove the backport versions and track this via the meta issue #42409

**Pull request merged**
