### PR TITLE
Fix LIMIT pushdown with MV_EXPAND

### LINKED ISSUE #102061: ES|QL: limit + sort + mv_expand is not planned correctly (unknown physical plan node [OrderExec])
Planning of queries with LIMIT + SORT + MV_EXPAND fails with `IllegalArgumentException`

```
row a = 1 | limit 1 | sort a | mv_expand a
```

```
{
    "error": {
        "root_cause": [
            {
                "type": "esql_illegal_argument_exception",
                "reason": "unknown physical plan node [OrderExec]"
            }
        ],
        "type": "esql_illegal_argument_exception",
        "reason": "unknown physical plan node [OrderExec]"
    },
    "status": 500
```

A similar problem was already [reported](https://github.com/elastic/elasticsearch/issues/99971) and fixed, but it seems the fix is not complete.

### LINKED ISSUE #102084: ESQL: Planning of  MV_EXPAND with false condition aborted because rule execution limit reached
```
row  a = 1, b = -15 | where b > 3   | mv_expand b
```

```
{
    "error": {
        "root_cause": [
            {
                "type": "rule_execution_exception",
                "reason": "Rule execution limit [100] reached"
            }
        ],
        "type": "rule_execution_exception",
        "reason": "Rule execution limit [100] reached"
    },
    "status": 500
}
```

The problem seems to be the pushdown of LIMIT:

```
[2023-11-13T15:34:04,962][TRACE][o.e.x.e.o.LogicalPlanOptimizer] [runTask-0] Rule optimizer.LogicalPlanOptimizer$DuplicateLimitAfterMvExpand applied
Limit[500[INTEGER]]                 = Limit[500[INTEGER]]
\_MvExpand[b{r}#332,b{r}#337]       = \_MvExpand[b{r}#332,b{r}#337]
  \_LocalRelation[[b{r}#332],EMPTY] !   \_Limit[500[INTEGER]]
                                    !     \_LocalRelation[[b{r}#332],EMPTY]

...

[2023-11-13T15:34:04,962][TRACE][o.e.x.e.o.LogicalPlanOptimizer] [runTask-0] Rule optimizer.LogicalPlanOptimizer$PropagateEmptyRelation applied
Limit[500[INTEGER]]                   = Limit[500[INTEGER]]
\_MvExpand[b{r}#332,b{r}#337]         = \_MvExpand[b{r}#332,b{r}#337]
  \_Limit[500[INTEGER]]               !   \_LocalRelation[[b{r}#332],EMPTY]
    \_LocalRelation[[b{r}#332],EMPTY] ! 
                                     

...

[2023-11-13T15:34:04,964][TRACE][o.e.x.e.o.LogicalPlanOptimizer] [runTask-0] Rule optimizer.LogicalPlanOptimizer$DuplicateLimitAfterMvExpand applied
Limit[500[INTEGER]]                 = Limit[500[INTEGER]]
\_MvExpand[b{r}#332,b{r}#337]       = \_MvExpand[b{r}#332,b{r}#337]
  \_LocalRelation[[b{r}#332],EMPTY] !   \_Limit[500[INTEGER]]
                                    !     \_LocalRelation[[b{r}#332],EMPTY]
```

### PR DESCRIPTION
**Pull request by luigidellaquila**
Fixes https://github.com/elastic/elasticsearch/issues/102084
Fixes https://github.com/elastic/elasticsearch/issues/102061

Allow proper pushdown of `LIMIT x` command past `MV_EXPAND`, using a two-step strategy:
- first push down the `LIMIT x` and keep the original limit information inside `MV_EXPAND` itself, ie. transform `MV_EXPAND | LIMIT x` into `LIMIT x | MV_EXPAND(with limit x)` 
- (do the normal planning, with batch loops that can trigger the above operation again if there are other LIMIT or MV_EXPAND commands)
- only at the end, and only once, replace all the `MV_EXPAND(with limit)` with `MV_EXPAND | LIMIT x`

All this happens only at logical level; at the end of logical planning, the inner limit is removed from MV_EXPAND (see last step), so that physical plan and operators can ignore it (mv_expand operator implementation is unbounded, this PR doesn't change it)

### CODE REVIEW

**Review by astefan — COMMENTED** [review]
Leaving it here, for the record: I don't think this is the best approach for this.
It may be easy enough, convenient to have the mv_expand "carry" its limit to have it pushed down past it, but conceptually speaking mv_expand doesn't have a "limit". TopN is the best counter-example of a Node that has a "proper" limit associated with it; in this case the limit is in the core of TopN, it's a part of its concept.

**Comment by luigidellaquila** [comment]
Thank for the feedback @astefan 

>  but conceptually speaking mv_expand doesn't have a "limit".

That's true, the concept of limit is not strictly related to MV_EXPAND, but on the other hand MV_EXPAND is peculiar because it's the only non-source command that "produces" records, invalidating the assumptions that allow limit pushdown. Also the operator implementation reflects this peculiarity in some way: it's (currently) the only non-source operator that is paginated, and the reason is very similar (subsequent LIMIT operators would come too late to avoid excessive memory pressure on a single page). 
To be completely honest, I went for this approach also because the logical planner is already very complicated, and I'd like to keep optimization rules local, ie. act on adjacent commands only: having a rule that can manage the `MV_EXPAND | LIMIT` scenario is much easier and much less error prone than having to deal with rules that detect and handle patterns like `<any limiting command> | <any other command> | ... | MV_EXPAND | LIMIT`

**Comment by costin** [comment]
I think this is superseded by #103582 and thus can be closed.

**Comment by luigidellaquila** [comment]
I'd keep this open for now, https://github.com/elastic/elasticsearch/pull/103582 is still in draft and needs some conceptual adjustments

**Comment by luigidellaquila** [comment]
Closing and resubmitting (it's easier than resolving conflicts at this stage)

**Pull request closed without merging**
