### PR TITLE
Ignore dangling indices created in newer versions

### LINKED ISSUE #34264: A higher version of an index can be restored in a cluster but when nodes try to join the cluster, membership fails
A higher version of an index 6.3.2 can be restored on a cluster with node version 6.3.1 however when additional nodes try to join the cluster, their membership is restricted based on compatibility checks
which ensures that all indices in the given metadata will not be created with a newer version of elasticsearch as well as that all indices are newer or equal to the minimum index compatibility version.
based on Version#minimumIndexCompatibilityVersion

**Elasticsearch version** (`bin/elasticsearch --version`): 6.3.1

**Plugins installed**: []

**JVM version** (`java -version`): JDK 10

**OS version** (`uname -a` if on a Unix-like system): Linux ip-10-212-18-25 4.9.70-25.242.amzn1.x86_64

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1. Restore an index of version 6.3.2 on a datanode with version 6.3.1
 2. Spin up a new data node with version 6.3.1
 3. Notice node is unable to join the cluster

**Provide logs (if relevant)**:
`[2018-10-03T00:00:10,030][INFO ][o.e.d.z.ZenDiscovery ] [wowvdMi] failed to send join request to master [{5GZT6AM}{5GZT6AMsSSy2x5vCdDLFXA}{1aYFoazmRXWt2OKoo3Slfg}{10.xx.xxx.xxx}{10.xx.xxx.xxx:9300}], reason [RemoteTransportException[[5GZT6AM][10.xx.xx.xxx:9300][internal:discovery/zen/join]]; nested: IllegalStateException[index [index-docs_2018092113/fKi49vf3TzKDshgg9ydzaQ] version not supported: 6.3.2 the node version is: 6.3.1]; ]
`

### PR DESCRIPTION
**Pull request by RvI101**
Today it is possible that we import a dangling index that was created in a
newer version than one or more of the nodes in the cluster. Such an index would
prevent the older node(s) from rejoining the cluster if they were to briefly
leave it for some reason. This commit prevents the import of such dangling
indices.

Fixes #34264

### CODE REVIEW

**Review by DaveCTurner — COMMENTED** [review]
Thanks @rvl101, this looks like a reasonable approach. I left a couple of small suggestions.

**Comment by RvI101** [comment]
Thanks for the feedback, @DaveCTurner. I've made the changes.

**Comment by DaveCTurner** [comment]
Failure looks unrelated, tracked in https://github.com/elastic/elasticsearch/issues/42577

@elasticmachine please run elasticsearch-ci/1

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Pull request merged**
