### PR TITLE
HTTP GET can't have a body

### PR DESCRIPTION
**Pull request by loekvangool**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?

### CODE REVIEW

**Comment by dadoonet** [comment]
GET can have a body. There have been a lot of issues/prs opened for this already so I guess we won't merge it?

**Comment by loekvangool** [comment]
Yes it works, but its content should not be semantically relevant to answer the request, according to https://tools.ietf.org/html/rfc2616#section-9.3 and https://tools.ietf.org/html/rfc7231#section-4.3.1. I don't consider myself a standards purist, but what advantage does it bring to do it this way?

**Comment by dadoonet** [comment]
In REST world, POST means that you are going to change the server state. Which is not the case when you search. So GET is ok.

**Comment by clintongormley** [comment]
@loekvangool we've had this discussion many times in the past.  See https://github.com/elastic/elasticsearch/issues/16024 for example

**Pull request closed without merging**
