### PR TITLE
Deprecates the standard filter

### PR DESCRIPTION
**Pull request by jimczi**
This change deprecates the noop standard filter. It is already removed in 7 but
the deprecation was missing.

### CODE REVIEW

**Review by cbuescher — COMMENTED** [review]
Change itself looks great, I found several mentions of the standard tokenizer in the docs though that might need to be changed or adapted to account for the warnings that are added here. e.g. I think "reference/analysis/tokenfilters/standard-tokenfilter.asciidoc" could get a note saying this is deprecated in removed already in 7.0. I'll grep a little bit to see if I can find other occurances.

**Comment by cbuescher** [comment]
These are some other docs files that I think might contain references to the standard filter. I think they can stay as they are, but probably it also wouldn't hurt removing the filter since it does nothing:

- asciifolding-tokenfilter.asciidoc
- snowball-tokenfilter.asciidoc
- elision-tokenfilter.asciidoc
- keep-types-tokenfilter.asciidoc
- standard-tokenfilter.asciidoc
- keep-words-tokenfilter.asciidoc
- stemmer-tokenfilter.asciidoc
- phrase-suggest.asciidoc

**Review by cbuescher — APPROVED** [review]
LGTM

**Comment by jimczi** [comment]
Thanks @cbuescher

**Pull request merged**
