### PR TITLE
Upgrade to Lucene 9.9.1

### PR DESCRIPTION
**Pull request by ChrisHegarty**
This commit upgrades to Lucene 9.9.1

### CODE REVIEW

**Comment by ChrisHegarty** [comment]
With the upgrade to 9.9.1 we can now remove the compiler excludes added by #103112

**Comment by ChrisHegarty** [comment]
@elasticmachine update branch

**Comment by ChrisHegarty** [comment]
@elasticmachine update branch

**Comment by ChrisHegarty** [comment]
@elasticmachine update branch

**Comment by ChrisHegarty** [comment]
@elasticmachine update branch

**Comment by ChrisHegarty** [comment]
@elasticmachine update branch

**Comment by ChrisHegarty** [comment]
@elasticmachine update branch

**Review by dnhatn — APPROVED** [review]
LGTM. Thanks, Chris!

**Pull request merged**
