### PR TITLE
Upgrade to lucene 5.5.0-snapshot-850c6c2

### PR DESCRIPTION
**Pull request by nknize**
This PR upgrades ES to latest lucene 5.5.0 RC snapshot. Major change includes refactoring `geo_point` type for 2.x to use newly available `PREFIX` encoding optimizations.

### CODE REVIEW

**Comment by mikemccand** [comment]
Thanks @nknize ... this gives us a nice jump on the upcoming 5.5.0 release.

It looks like much of this was from renaming noise, but there are important back compat changes here (NUMERIC vs PREFIX encoding of the geo terms for ES 2.2.x vs ES 2.3.x indices) that are hard for me to check (out of my area).  Do we have back compat tests that have ES 2.2.x geo indices, confirming they still work correctly in ES 2.3.x?

Also, with this upgrade, since geopoint moved from sandbox to spatial module, can we remove ES's dependency on Lucene's sandbox?  Or does ES use sandbox APIs elsewhere?

**Comment by nknize** [comment]
> Do we have back compat tests that have ES 2.2.x geo indices, confirming they still work correctly in ES 2.3.x?

There aren't any explicit backcompat tests. This [commit] (https://github.com/nknize/elasticsearch/commit/dc778157441fa3528609321d0820030dbaff2033), merged as part of PR #14667, added version randomization to the Geo unit tests to ensure backwards compatibility.

> Since geopoint moved from sandbox to spatial module, can we remove ES's dependency on Lucene's sandbox?

Good question. For spatial we can. I'm not sure if anything else uses sandbox but that's easy enough to check. Should we track that in a separate issue?

**Comment by nknize** [comment]
>  can we remove ES's dependency on Lucene's sandbox?

Looks like we still require sandbox for `DocValuesTermsQuery`

**Comment by mikemccand** [comment]
OK thanks @nknize, LGTM!

**Pull request merged**
