### PR TITLE
Skip REST YAML tests in FIPS 140 mode

### PR DESCRIPTION
**Pull request by jkakavas**
Currently we don't have a way to selectively mute REST YAML tests
in FIPS 140 mode.

This commit introduces a new feature (fips_140) that can be used
in skip blocks to allow that.

### CODE REVIEW

**Comment by jkakavas** [comment]
@elasticmachine update branch

**Comment by javanna** [comment]
This looks good to me, but can can you please check with the clients team that they don't need to do anything about it? Maybe they should be the reviewers of this change.

**Comment by jkakavas** [comment]
@elastic/es-clients can you take a look please ,apologies for the team wide ping :)

**Comment by ezimuel** [comment]
I don't think this will affect the client team since we are not using FIPS 140 mode to run Elaticsearch in our YAML tests.

**Review by Mpdreamz — COMMENTED** [review]
LGTM, clients opt-in to features so will skip on any unknown feature. Thanks for the heads up 👍

**Review by Mpdreamz — APPROVED** [review]

**Pull request merged**
