### PR TITLE
Return result to cluster state ack listener

### PR DESCRIPTION
**Pull request by DaveCTurner**
The `MasterService` executes batches of tasks which compute changes to
the `ClusterState`. After executing each batch the `MasterService`
publishes the updated cluster state and may notify tasks in the batch
when the nodes have acked the state (or failed, or timed out). Many
tasks compute some kind of result during their execution which needs to
be made available to the ack completion handler for subsequent
activities.

Today there's no good general way to pass anything to the ack completion
handler other than the fact that the update was acked or not. Some tasks
work around this by storing their result in the `ClusterState` itself.
Others use the executor to capture the result and pass it through.
Neither solution works well with batching: later tasks in a batch may
overwrite the part of the `ClusterState` containing the results of
earlier tasks, and batching executors are re-used across batches.

This commit adjusts the `ClusterStateTaskExecutor` interface so that now
implementations that wish to listen for acks must supply a listener for
each task they successfully execute. The `MasterService` collects the
listeners for the batch and notifies them as acks are received. This
gives the executor control over the ack handler of each task which lets
it pass in any extra data needed.

Effectively this is the same as #83562 but for ack listeners instead of
publish listeners.

### CODE REVIEW

**Comment by DaveCTurner** [comment]
@elasticmachine update branch

**Comment by DaveCTurner** [comment]
This PR is extracted from https://github.com/elastic/elasticsearch/pull/84170 which also uses these changes to rework `AutoCreateAction` - it might be instructive to look at how it's used there.

**Review by original-brownbear — APPROVED** [review]
LGTM

**Comment by DaveCTurner** [comment]
@elasticmachine please run elasticsearch-ci/part-2 (failure reported at https://github.com/elastic/elasticsearch/issues/84232)

**Pull request merged**
