### PR TITLE
Fix memory leak when double invoking RestChannel.sendResponse

### PR DESCRIPTION
**Pull request by original-brownbear**
When using the resource handling channel we must make sure that if we (by what is IMO a bug) try to double invoke it after having already sent a response (or tried to do so) we at least release the memory in the channel's outbound buffer. Otherwise we will leak any memory from it that was used to create the now failing to send `RestResponse`.

### CODE REVIEW

**Review by Tim-Brooks — APPROVED** [review]
LGTM - was this happening somewhere?

**Comment by DaveCTurner** [comment]
> ... IMO a bug) try to double invoke it

LGTM2, and yes this sounds like a bug to me too. My only question is whether we could assert that this doesn't happen (ofc fixing any cases where it does first).

**Comment by original-brownbear** [comment]
> My only question is whether we could assert that this doesn't happen

It's not entirely trivial unfortunately because of the current tests  we have, but yes we should try to move towards that assertion.

**Comment by DaveCTurner** [comment]
Ok, I opened https://github.com/elastic/elasticsearch/issues/89902 to track that.

**Pull request merged**
