### PR TITLE
ILM the delete action waits for a TSDS index time/bounds to lapse

### PR DESCRIPTION
**Pull request by andreidan**
This adds the `check-ts-end-time-passed` step to the delete action so, for time series indices, we wait until they're not meant to accept new writes anymore before deleting them (i.e. until the time interval that covers the ingestion for `now` has lapsed)

Relates to #99696

### CODE REVIEW

**Review by jbaiera — APPROVED** [review]
LGTM

**Review by martijnvg — APPROVED** [review]
LGTM 👍

**Comment by rodrigc** [comment]
@andreidan for this ILM fix, are there any changes required to the Kibana screens for configuring ILM policies,
or is this fix "under the covers", and not required for configuring ILM policies?

**Comment by andreidan** [comment]
@rodrigc That's a great question. I don't know of a good place where some addition information about the delays that ILM will incour due to the time series `end_time` would be helpful.
Perhaps when creating an index template that has `index.mode: time_series` and an ILM policy (or, in 8.11 onwards a `lifecycle` object) configured? 
@martijnvg what do you think? Is there a more dedicated TSDB screen in Kibana?

**Pull request merged**
