### PR TITLE
Fix bug in parent and child aggregators when parent field not defined

### LINKED ISSUE #42997: Add null check for ParentJoinFieldMapper in ChildrenAggregationBuilder.joinFieldResolveConfig
A user received a NPE. It was reproduced on 6.3.1 with the following stack trace:
```
2019-06-06T13:26:49,963][DEBUG][o.e.a.s.TransportSearchAction] [hamilton] [mi_indice][2], node[ABwM3KQJQdWuKfnzwJ8pxw], [P], s[STARTED], a[id=cRQiXG2DTmijJ2IMjtYq5g]: Failed to execute [SearchRequest{searchType=QUERY_THEN_FETCH, indices=[mi_indice], indicesOptions=IndicesOptions[id=38, ignore_unavailable=false, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, allow_aliases_to_multiple_indices=true, forbid_closed_indices=true, ignore_aliases=false], types=[], routing='null', preference='null', requestCache=null, scroll=null, maxConcurrentShardRequests=15, batchedReduceSize=512, preFilterShardSize=128, allowPartialSearchResults=true, source={"query":{"bool":{"must":[{"bool":{"must":[{"bool":{"should":[{"range":{"posting_date":{"from":"1900-01-01T00:00:00.000Z","to":"2019-05-30T18:25:49.967Z","include_lower":true,"include_upper":true,"boost":1.0}}}],"adjust_pure_negative":true,"boost":1.0}},{"term":{"externaljob_to_child_fields.name":{"value":"externaljob","boost":1.0}}}],"adjust_pure_negative":true,"boost":1.0}}],"adjust_pure_negative":true,"boost":1.0}},"aggregations":{"POSTING_DATES":{"date_range":{"field":"posting_date","ranges":[{"key":"ORA_LT07","from":"2019-05-23T18:25:50.006Z","to":"2019-05-30T18:25:50.006Z"},{"key":"ORA_LT30","from":"2019-04-30T18:25:50.006Z","to":"2019-05-30T18:25:50.006Z"},{"key":"ORA_GT30","from":"1900-01-01T00:00:00.000Z","to":"2019-04-30T18:25:50.006Z"}],"keyed":false}},"LOCATIONS":{"children":{"type":"externaljob_locs"}}}}}] lastShard [true]
org.elasticsearch.transport.RemoteTransportException: [washington][127.0.0.1:9302][indices:data/read/search[phase/query]]
Caused by: java.lang.NullPointerException
	at org.elasticsearch.join.aggregations.ChildrenAggregationBuilder.joinFieldResolveConfig(ChildrenAggregationBuilder.java:122) ~[?:?]
	at org.elasticsearch.join.aggregations.ChildrenAggregationBuilder.resolveConfig(ChildrenAggregationBuilder.java:113) ~[?:?]
	at org.elasticsearch.search.aggregations.support.ValuesSourceAggregationBuilder.doBuild(ValuesSourceAggregationBuilder.java:311) ~[elasticsearch-6.3.1.jar:6.3.1]
	at org.elasticsearch.search.aggregations.support.ValuesSourceAggregationBuilder.doBuild(ValuesSourceAggregationBuilder.java:38) ~[elasticsearch-6.3.1.jar:6.3.1]
	at org.elasticsearch.search.aggregations.AbstractAggregationBuilder.build(AbstractAggregationBuilder.java:139) ~[elasticsearch-6.3.1.jar:6.3.1]
	at org.elasticsearch.search.aggregations.AggregatorFactories$Builder.build(AggregatorFactories.java:329) ~[elasticsearch-6.3.1.jar:6.3.1]
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:766) ~[elasticsearch-6.3.1.jar:6.3.1]
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:575) ~[elasticsearch-6.3.1.jar:6.3.1]
```

in `ChildrenAggregationBuilder.joinFieldResolveConfig`

```
private void joinFieldResolveConfig(SearchContext context, ValuesSourceConfig<WithOrdinals> config) {
        ParentJoinFieldMapper parentJoinFieldMapper = ParentJoinFieldMapper.getMapper(context.mapperService()); 
        ParentIdFieldMapper parentIdFieldMapper = parentJoinFieldMapper.getParentIdFieldMapper(childType, false);
        if (parentIdFieldMapper != null) {
...
        } else {
            config.unmapped(true);
        }

```
`ParentJoinFieldMapper.getMapper` returns null when there is no parent-join field in the mapping. We already check to see if `parentIdFieldMapper` is null and use an unmapped. Should probably be doing the same for `parentJoinFieldMapper` as well.

### PR DESCRIPTION
**Pull request by parthpunkster**
Fixes an NPE the we bump into when the parent field isn't mapped.

Closes #42997

### CODE REVIEW

**Review by nik9000 — COMMENTED** [review]
At first glance this looks right. I'm both officially off today and deep in something. My instinct is that this is right but could use a test somewhere like `ParentAggregatorTests`.

**Comment by parthpunkster** [comment]
Hey,
Thanks for the response. I couldn't find any test class for this one. I also looked up for the test class 
"ParentAggregatorTests" and couldn't find that either. Can you point me to correct test class for the same.

**Comment by nik9000** [comment]
Sorry I didn't get back to you earlier!

It looks like these are in `ChildrenToParentAggregatorTests` and `ParentToChildrenAggregatorTests`.

**Comment by nik9000** [comment]
I'm going to retitle this PR to make it a little more clear what it does for release notes and email subject lines.

**Comment by parthpunkster** [comment]
@nik9000 Aslo the method is Protected. How would we test it.
I also couldn't find any existing test's for this method.

**Comment by nik9000** [comment]
> @nik9000 Also the method is Protected. How would we test it.
> I also couldn't find any existing test's for this method.

For the most part we test methods like this by running the aggregation and making sure it doesn't blow up. I think this'd look like disabling the `join_field` and `_parent_join` mocking in those tests and making sure that you don't get any results rather than blowing up.

**Comment by nik9000** [comment]
@parthpunkster, are you still interested in doing this work? If not, would you mind if I took it from here?

**Comment by parthpunkster** [comment]
> @parthpunkster, are you still interested in doing this work? If not, would you mind if I took it from here?

Hey yes I am. Will raise another revision by this weekend.

**Comment by nik9000** [comment]
The simplest way might be to make a new test that extends `AggregatorTestCase` and use something like `ChildrenToParentAggregatorTests#testNoDocs` as a starting point. `ChildrenToParentAggregatorTests` has `mapperServiceMock` which sets up the mock to make the mapper service - you don't want that. But you would want its `getSearchPlugins` to make sure that the parent join aggregators are registered to the test at all.

That isn't quite as simple as I'd hoped, but I don't see a good way of selectively disabling the join field in the existing `mapperServiceMock` methods.

**Comment by parthpunkster** [comment]
> The simplest way might be to make a new test that extends `AggregatorTestCase` and use something like `ChildrenToParentAggregatorTests#testNoDocs` as a starting point. `ChildrenToParentAggregatorTests` has `mapperServiceMock` which sets up the mock to make the mapper service - you don't want that. But you would want its `getSearchPlugins` to make sure that the parent join aggregators are registered to the test at all.
> 
> That isn't quite as simple as I'd hoped, but I don't see a good way of selectively disabling the join field in the existing `mapperServiceMock` methods.

Hey,
Thanks for a quick reply. I tried writing test's for this using the technique you mentioned. It still seems to be pretty confusing and difficult to write. I don't want to delay more on this issue for you. Can we merge this PR and then you can take it away to complete the test part ?
If possible. I am still interested to work just a bit confused on how would we write test for this one.

**Comment by nik9000** [comment]
>  If possible. I am still interested to work just a bit confused on how would we write test for this one.

I tried to write a unit test for this and it turned out more ticky than I thought! I pushed an integration test to this branch. Since it looks good now I'll merge it to master and 7.x so it'll get released with 7.9.0.

**Comment by nik9000** [comment]
@elasticmachine, ok to test

**Comment by nik9000** [comment]
Let's see what jenkins says first

**Comment by parthpunkster** [comment]
> >  If possible. I am still interested to work just a bit confused on how would we write test for this one.
> 
> 
> 
> I tried to write a unit test for this and it turned out more ticky than I thought! I pushed an integration test to this branch. Since it looks good now I'll merge it to master and 7.x so it'll get released with 7.9.0.

Ya i agree, it’s a bit more tricker but i think you integration test should help.
Sounds good. Let me know what is the next things to be done from my end.

**Comment by parthpunkster** [comment]
@nik9000 hey wanted to know the next steps?

**Comment by nik9000** [comment]
> @nik9000 hey wanted to know the next steps?

Sorry! I got pulled into another thing. I believe the next step is to merge and backport, both of which I'll do now. Thanks!

**Comment by nik9000** [comment]
And I've landed the backport to 7.x! Thanks again for the fix @parthpunkster !

**Comment by parthpunkster** [comment]
> And I've landed the backport to 7.x! Thanks again for the fix @parthpunkster !

@nik9000 Thanks a lot for all the support along way. Also is there some thing which i need to do to get the name on list of contributors?

**Comment by nik9000** [comment]
> Also is there some thing which i need to do to get the name on list of contributors?

Which list are you looking at? I think [this](https://github.com/elastic/elasticsearch/graphs/contributors) only shows the top 100 or so. I don't *think* we maintain another list.

**Comment by parthpunkster** [comment]
> > Also is there some thing which i need to do to get the name on list of contributors?
> 
> 
> 
> Which list are you looking at? I think [this](https://github.com/elastic/elasticsearch/graphs/contributors) only shows the top 100 or so. I don't *think* we maintain another list.

Ohh ohkay. I actually thought there is alist which has all the names of people who have contributed.

**Pull request merged**
