### PR TITLE
flush in case we test against version <=2.0.2 before upgrading

### LINKED ISSUE #17130: BasicBackwardsCompatibilityIT.testIndexRollingUpgrade sometimes fails
Example failure:
http://build-us-00.elastic.co/job/es_core_2x_window-2008/712

Reproduce command (I can't reproduce this locally):

```
REPRODUCE WITH: mvn verify -Pdev -Dskip.unit.tests -pl org.elasticsearch.qa.backwards:2.0 -Dtests.seed=FE8754AE850E4A36 -Dtests.class=org.elasticsearch.bwcompat.BasicBackwardsCompatibilityIT -Dtests.method="testIndexRollingUpgrade" -Des.logger.level=DEBUG -Dtests.nightly=false -Dtests.client.ratio=0.0 -Dtests.heap.size=512m -Des.node.mode=local -Dtests.jvm.argline="-server -XX:+UseG1GC -XX:+UseCompressedOops -Djava.net.preferIPv4Stack=true" -Dtests.locale=sr-BA -Dtests.timezone=Australia/Tasmania
```

Failure:

```
FAILURE 11.8s | BasicBackwardsCompatibilityIT.testIndexRollingUpgrade <<<
   > Throwable #1: java.lang.AssertionError: Count is 96 but 116 was expected.  Total shards: 14 Successful shards: 14 & 0 shard failures:
   > 	at __randomizedtesting.SeedInfo.seed([FE8754AE850E4A36:88FA0EA86CDC10E0]:0)
   > 	at org.elasticsearch.test.hamcrest.ElasticsearchAssertions.assertHitCount(ElasticsearchAssertions.java:244)
   > 	at org.elasticsearch.bwcompat.BasicBackwardsCompatibilityIT.testIndexRollingUpgrade(BasicBackwardsCompatibilityIT.java:371)
   > 	at java.lang.Thread.run(Thread.java:745)
```

### PR DESCRIPTION
**Pull request by brwe**
otherwise we might run into #15832

closes #17130

### CODE REVIEW

**Comment by nik9000** [comment]
LGTM

**Comment by s1monw** [comment]
can you put a comment in there to explain WHY we are doing this?

**Comment by nik9000** [comment]
Good call.

**Comment by brwe** [comment]
@s1monw added a comment

**Comment by s1monw** [comment]
LGTM can you push this to 2.2 and 2.x and maybe also to 2.1?

**Comment by brwe** [comment]
pushed to 2.x, 2.2 and 2.1 (0dfa084 and 2e185ee)

**Pull request merged**
