### PR TITLE
Give vagrant boxes 2gb of ram

### PR DESCRIPTION
**Pull request by nik9000**
This lets them run our tests without oomkiller getting angry.

### CODE REVIEW

**Comment by rmuir** [comment]
+1, our vagrant setup is very useful if you want to try out changes on different linux versions. Just needs a bit more ram to be able to e.g. compile the source code and so on :)

I tested this change and it fixes problems i had on trusty.

**Comment by nik9000** [comment]
Any objections, @brwe or @spinscale or @tlrx ?

**Comment by brwe** [comment]
ok for me

**Comment by nik9000** [comment]
Merged to master and cherry-picked to 2.0 and 2.x.

**Pull request merged**
