### PR TITLE
Remove legacy BWC test infrastructure and tests

### PR DESCRIPTION
**Pull request by s1monw**
We don't use the test infra nor do we run the tests. They might all be
entirely out of date. We also have a different BWC test infra in-place.
This change removes all of the legacy infra.

### CODE REVIEW

**Comment by rjernst** [comment]
LGTM!

**Comment by jpountz** [comment]
nice stats

**Comment by s1monw** [comment]
@elasticmachine test this please

**Comment by javanna** [comment]
is this used in 5.x? I wonder if this commit should have been backported

**Pull request merged**
