### PR TITLE
add copy ingest processor

### PR DESCRIPTION
**Pull request by gaobinlong**
Relates to #55682 and #51046.
The main point of this PR is adding a copy ingest processor which can copy the value of one field to another and even the top level of the document. The supported data types which can be copied are `boolean`, `number`, `array`, `object`, `string`, `date`.

### CODE REVIEW

**Comment by danhermann** [comment]
@gaobinlong, thank you for this contribution. It's useful functionality that we would like to incorporate into ingest pipelines. We are reconsidering how we've organized the processors and are trying to determine whether this fits best as part of the existing set processor or as its own separate processor. If you'll bear with us while we consider that, we will let you know and then work to get this PR refactored if necessary and then merged.

**Comment by gaobinlong** [comment]
@danhermann, I have tried to use `set processor` to copy one field to another, but found that we cannot copy `array`,`object ` and `boolean`, because the `template snippet` always produces `string` value.  I'm eager to know your idea about that and glad to do more work.

**Comment by danhermann** [comment]
@gaobinlong, apologies for the delay on this one. We decided that this is how the `set` processor should work instead of producing string values as you note that it does now. If you would like to continue this PR by modifying the set processor to correctly handle, I would be happy to review it.

**Comment by gaobinlong** [comment]
@danhermann, I'm glad to continue doing that and will refractor the code soon.

**Comment by gaobinlong** [comment]
@danhermann , I have refactored the code  and opened a new PR #63540, this PR can be closed lately.

**Pull request closed without merging**
