### PR TITLE
Add "stats" param to count API

### PR DESCRIPTION
**Pull request by firstprayer**
For issue https://github.com/elastic/elasticsearch/issues/67528

This change will pass into the stats parameter to the search request which will later be consumed.

## Test Plan
Ran ./gradlew localDistro and it compiled successfully.
I also ran ./gradlew check which passed for most of the tests except for "InternalDistributionBwcSetupPluginFuncTest" which seems to be due to flakiness.

### CODE REVIEW

**Comment by henningandersen** [comment]
@firstprayer thanks for your interest in improving Elasticsearch. It looks like you have not signed the contributor agreement. Also, the commits on this PR looks like they have a different author (perhaps yourself).

About the change, it is missing following:
1. A docs change to document the new option.
2. A test validating that it works. I suggest to add a YAML test, something like what is in [this test](https://github.com/elastic/elasticsearch/blob/21e392e95e6ab5b293a46f7a2af84c0fa4778029/rest-api-spec/src/main/resources/rest-api-spec/test/indices.stats/14_groups.yml#L12)

**Comment by mark-vieira** [comment]
@elasticmachine update branch

**Comment by henningandersen** [comment]
@firstprayer are you still interested in working on this?

**Comment by javanna** [comment]
No CLA signed, closing for now. Feel free to reopen if you are still interested in contributing your change.

**Pull request closed without merging**
