### PR TITLE
Support time_zone on composite's date_histogram

### LINKED ISSUE #45199: time_zone parameter in composite aggregation with date_histogram source doesn't work
**Elasticsearch version** (`bin/elasticsearch --version`):

7.2.0

**Description of the problem including expected versus actual behavior**:

Passing a `time_zone` parameter in a date_histogram source in `composite` aggregation returns wrong buckets.

It has been reported in this discussion some months ago, but the problem is still present in master: https://discuss.elastic.co/t/composite-date-aggregation-not-consistent/172666

**Steps to reproduce**:
```
# Create index
curl -XPUT "http://elastic:9200/test_date_histo" -H 'Content-Type: application/json' -d'
{
  "settings": {
    "number_of_shards": 5
  },
  "mappings": {
    "properties": {
      "date": {
        "type": "date"
      }
    }
  }
}'

# Index some data
curl -XPOST "http://elastic:9200/test_date_histo/_doc" -H 'Content-Type: application/json' -d'
{
  "date": "2019-03-01T00:01:00+00:00"
}'

# Perform a comparative query
curl -XGET "http://elastic:9200/test_date_histo/_search?request_cache=false" -H 'Content-Type: application/json' -d'
{
  "size": 0,
  "aggs": {
    "date_histo": {
      "date_histogram": {
        "field": "date",
        "interval": "1d",
        "time_zone": "+02:00",
        "format": "yyyy-MM-dd"
      }
    },
    "composite_date_histo": {
      "composite": {
        "sources": [
          {
            "date_histo": {
              "date_histogram": {
                "field": "date",
                "interval": "1d",
                "format": "yyyy-MM-dd",
                "time_zone": "+02:00"
              }
            }
          }
        ]
      }
    }
  }
}'

```

The result is:

```
{
  "took" : 2,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 0.0,
    "hits" : [ ]
  },
  "aggregations" : {
    "composite_date_histo" : {
      "after_key" : {
        "date_histo" : "2019-02-28"
      },
      "buckets" : [
        {
          "key" : {
            "date_histo" : "2019-02-28"
          },
          "doc_count" : 1
        }
      ]
    },
    "date_histo" : {
      "buckets" : [
        {
          "key_as_string" : "2019-03-01",
          "key" : 1551391200000,
          "doc_count" : 1
        }
      ]
    }
  }
}
```

### PR DESCRIPTION
**Pull request by nik9000**
We've been parsing the `time_zone` parameter on `date_histogram` for a
while but it hasn't *done* anything. This wires it up.

Closes #45199
Inspired by #45200

### CODE REVIEW

**Review by polyfractal — COMMENTED** [review]
Changes look good, but I'm a bit confused why the timezone tests in `CompositeAggregatorTests` pass without modification?

E.g. since DateHistogramValuesSourceBuilder would set it's own timezone before, so the shard rounding math was correct (e.g. in `DateHistogramValuesSourceBuilder#innderBuild()`) but the VS resolution would use null and thus the formatter would be in UTC.  But with this fix the correct formatter should be used, so I'm a little surprised the tests are still passing.

**Comment by nik9000** [comment]
> Changes look good, but I'm a bit confused why the timezone tests in `CompositeAggregatorTests` pass without modification?

I'll see what I can find out!

**Comment by nik9000** [comment]
@polyfractal it looks like we just didn't have any unit tests using time zones. I added some.

**Review by jimczi — APPROVED** [review]
lgtm, thanks @nik9000

**Review by polyfractal — APPROVED** [review]
LGTM2, thanks for adding the test :)

(The test I was looking at before was `testWithDateHistogramAndTimeZone()`, but I'm probably misreading what it's supposed to do, only skimmed over it.)

**Comment by nik9000** [comment]
> (The test I was looking at before was `testWithDateHistogramAndTimeZone()`, but I'm probably misreading what it's supposed to do, only skimmed over it.)

Wow, I can't believe I missed that test! I spent a while staring at it and I think it didn't catch the problem or the change because there weren't any times that changed which interval they are part of with the time zone.

**Comment by nik9000** [comment]
Thanks @polyfractal and @jimczi !

**Pull request merged**
