### PR TITLE
Fix max boundary for rollup jobs that use a delay

### PR DESCRIPTION
**Pull request by jimczi**
Rollup jobs can define how long they should wait before rolling up new documents.
However if the delay is smaller or if it's not a multiple of the rollup interval
the job can create incomplete buckets because the max boundary for a job is computed
from the time when the job started rounded to the interval minus the delay. This change
fixes this computation by applying the delay substraction before the rounding in order to ensure
that we never create a boundary that falls in a middle of a bucket.

### CODE REVIEW

**Review by polyfractal — APPROVED** [review]
LGTM, thanks!

**Comment by polyfractal** [comment]
Note to self: we'll need to adjust this in the future to handle calendar intervals too I think.  E.g. if you're working with calendar intervals, you probably want the delay to match.

Problem for another day though :)  I think we can handle that after the fixed/calendar histo interval PR lands in 7.x

**Comment by jimczi** [comment]
Jenkins run elasticsearch-ci/1

**Comment by jimczi** [comment]
Jenkins run elasticsearch-ci/1

**Pull request merged**
