### PR TITLE
Use unique constant names for index versions

### PR DESCRIPTION
**Pull request by rjernst**
Similar to TransportVersion constants, this commit updates IndexVersion constants to use descriptive names. With descriptive names uuids are no longer needed, so those are also removed.

### CODE REVIEW

**Comment by ldematte** [comment]
I'm not so sure about this: what happens is we want to collapse them in the future, like this: https://github.com/elastic/elasticsearch/pull/100075? There could be no good name for the constant.

**Comment by thecoop** [comment]
When collapsing, I'm imagining we'll name the constants after the release we're collapsing for - so `V_8_11_0` or similar

**Comment by thecoop** [comment]
Will the move to `IndexVersions` come later?

**Comment by ldematte** [comment]
> When collapsing, I'm imagining we'll name the constants after the release we're collapsing for - so V_8_11_0 or similar

Sounds like a good compromise - we gain legibility in the short term. Newer constants will be added with a semantic name, and it is very unlikely 2 persons will collapse at the same time, so merging should still be safe.

**Comment by rjernst** [comment]
> Will the move to IndexVersions come later?

Yes I will do that as a followup (it's more invasive so I wanted it to be more mechanical).

**Review by thecoop — APPROVED** [review]

**Pull request merged**
