### PR TITLE
modify @link

### PR DESCRIPTION
**Pull request by shiwenjie12**
Make @link usable

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Review by cbuescher — CHANGES_REQUESTED** [review]
Thanks for opening the PR, the link correction makes sense to me, but I think the link target should be the `findNewDanglingIndices` thats used in the method, not the method itself? Would you mind changing that as well?

**Comment by shiwenjie12** [comment]
Thank you for your reply. I don't mind. I just think there's something wrong with the way the link connection is written.

**Comment by cbuescher** [comment]
> I just think there's something wrong with the way the link connection is written.

I agree, just asking if you can push an update to also correct the link target not to point to the same method the javadoc is in. Then I will run some final tests and merge this.

**Comment by shiwenjie12** [comment]
I agree. Thank you.

**Pull request closed without merging**
