### PR TITLE
Remove workaround in repository-azure for bug now fixed in Azure SDK

### PR DESCRIPTION
**Pull request by ChrisHegarty**
This commit simply applies an anti-delta of a code change in Elasticsearch that was added to workaround a bug in the Azure Storage SDK, which has since been fixed.

The original Elasticsearch PR that applied the workaround (to allow a sas token with a leading ? in connection string) is #88155. The issue that fixed the underlying bug in Azure is https://github.com/Azure/azure-sdk-for-java/pull/30003, which has been merged into [12.18.0](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-common/CHANGELOG.md#12180-2022-08-12). The Elasticsearch repository-azure component has been updated to 12.20.1, by #92119, so the workaround is no longer needed.

This change effectively just applies the suggestion that arose during the review of #88155, see https://github.com/elastic/elasticsearch/pull/88155/files#r924596359

FYI - I ran across this issue when analysing module dependencies for future Modularization work, see #78744. There is still a dependency on the internals of the Azure SDK, but that can be tackled in a follow-up issue.

### CODE REVIEW

**Comment by ChrisHegarty** [comment]
Assumption: existing tests added by #88155 should be sufficient to verify this change.

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by ChrisHegarty** [comment]
I found it necessary to update the query param assertion in the test. The query params are semantically equivalent, but the order is no identical, so String equality is no longer sufficient.

**Comment by ChrisHegarty** [comment]
@elasticsearchmachine update branch

**Comment by ChrisHegarty** [comment]
@elasticmachine update main

**Comment by ChrisHegarty** [comment]
@elasticsearchmachine please retest

**Comment by ChrisHegarty** [comment]
@elasticmachine please retest

**Comment by ChrisHegarty** [comment]
@elasticmachine retest this please

**Review by fcofdez — APPROVED** [review]
LGTM. Thanks for taking care of this 👍

**Pull request merged**
