### PR TITLE
Adding rolling upgrade KNN search tests

### PR DESCRIPTION
**Pull request by benwtrent**

### CODE REVIEW

**Review by javanna — APPROVED** [review]

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Comment by benwtrent** [comment]
run elasticsearch-ci/full-bwc

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Comment by benwtrent** [comment]
run elasticsearch-ci/full-bwc

**Comment by benwtrent** [comment]
run elasticsearch-ci/full-bwc

**Pull request merged**
