### PR TITLE
Remove Discovery interface

### PR DESCRIPTION
**Pull request by DaveCTurner**
Today there's only one implementation of the `o.e.d.Discovery` interface
in use anywhere, namely `o.e.c.c.Coordinator`. This commit folds the
interface into the implementing class and deletes the associated dead
code in `GatewayService` and friends that was being maintained in 7.x to
preserve compatibility with 6.x.

### CODE REVIEW

**Review by original-brownbear — APPROVED** [review]
LGTM nice :)

**Comment by DaveCTurner** [comment]
Thanks Armin :) Yeah good to be removing code for once...

**Comment by DaveCTurner** [comment]
Failure is #77728 @elasticsearch-ci/part-1

**Comment by DaveCTurner** [comment]
@elasticmachine please run elasticsearch-ci/part-1

**Pull request merged**
