### PR TITLE
Fix NPE in IndexService#getNodeMappingStats

### LINKED ISSUE #91259: _nodes/stats returns failed_node_exception if closed indices exist
### Elasticsearch Version

8.5.0

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Linux 9b4c50a443c1 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Problem Description

In 8.5, _nodes/stats returns a failure message if the node has closed indices. In previous versions, it works.
Please see steps to reproduce.

### Steps to Reproduce

```
$ curl -XPUT http://localhost:9200/test_index
$ curl http://localhost:9200/_nodes/stats  # <- it works
$ curl -XPOST http://localhost:9200/test_index/_close
$ curl http://localhost:9200/_nodes/stats
{
  "_nodes": {
    "total": 1,
    "successful": 0,
    "failed": 1,
    "failures": [
      {
        "type": "failed_node_exception",
        "reason": "Failed node [...]",
        "node_id": "...",
        "caused_by": {
          "type": "null_pointer_exception",
          "reason": "Cannot invoke \"org.elasticsearch.index.mapper.MapperService.mappingLookup()\" because the return value of \"org.elasticsearch.index.IndexService.mapperService()\" is null"
        }
      }
    ]
  },
  "cluster_name": "...",
  "nodes": {}
}
```

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by scampi**
The field mapperService in IndexService can be null, which needs to be handled in getNodeMappingStats. It returns a null in that case, which is already handled by the caller CommonStats.

Close #91259

### CODE REVIEW

**Comment by jbaiera** [comment]
@elasticmachine ok to test

**Comment by kingherc** [comment]
I can review this since it seems related to some [recent changes](https://github.com/elastic/elasticsearch/pull/89807/files#diff-b766a7882dfa6838a843458c46aef970fb39f5b2a18b04639ef2f1b9e31459c1) I did.

**Comment by kingherc** [comment]
@elasticmachine update branch

**Review by kingherc — APPROVED** [review]
Thanks for fixing the bug! I made a commit to rename the test and add the required yml file.

**Comment by kingherc** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Pull request merged**
