### PR TITLE
Remove op.name configuration setting in OIDC

### PR DESCRIPTION
**Pull request by jkakavas**
This setting was eventually not used in the OpenID Connect realm and thus 
can be removed

### CODE REVIEW

**Comment by jkakavas** [comment]
@elasticmachine run elasticsearch-ci/1

**Review by albertzaharovits — APPROVED** [review]
LGTM

**Comment by jkakavas** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by jkakavas** [comment]
@elasticmachine run elasticsearch-ci/1

**Pull request merged**
