### PR TITLE
Add .code_internal-* index pattern to kibana user

### PR DESCRIPTION
**Pull request by mw-ding**
Add the `.code_internal-*` index pattern permission to kibana user.

Addressing [this issue](https://github.com/elastic/code/issues/1183)

### CODE REVIEW

**Review by zfy0701 — APPROVED** [review]

**Comment by mw-ding** [comment]
@tvernum, can you take a look? Also, any ideas on the failing tests? what am I missing here?

**Comment by zfy0701** [comment]
retest

**Comment by zfy0701** [comment]
re test

**Comment by zfy0701** [comment]
jenkins retest

**Comment by tvernum** [comment]
@elasticmachine 
- run elasticsearch-ci/2
- run elasticsearch-ci/bwc

**Comment by tvernum** [comment]
BWC was failing because you were branched from a broken version. I've merged master into this branch.

**Comment by tvernum** [comment]
@elasticmachine run elasticsearch-ci/1

**Review by tvernum — APPROVED** [review]

**Comment by mw-ding** [comment]
@tvernum do we need to backport this change to 7.x or 7.2 as we do in Kibana?

**Comment by mw-ding** [comment]
@tvernum 
I have already created 2 PRs to backport the change to 7.2 and 7.x, https://github.com/elastic/elasticsearch/pull/42386, https://github.com/elastic/elasticsearch/pull/42387

Please take a look

**Pull request merged**
