### PR TITLE
elasticsearch.R is abandoned

### PR DESCRIPTION
**Pull request by nelsonSchwarz**
README file reads: (This project is no longer maintained, if you would like to take over feel free to send me an email)

See here: https://github.com/Tomesch/elasticsearch

### CODE REVIEW

**Comment by nelsonSchwarz** [comment]
Now I signed the CLA, sorry.

**Comment by nik9000** [comment]
Thanks @nelsonSchwarz! I'll merge and backport all over the place in a bit.

**Comment by nelsonSchwarz** [comment]
Awesome. Thanks!

**Comment by nik9000** [comment]
Don't close it yourself! When I merge it'll close. If you close it before I merge that says "I don't want this merged". Which is fine if you don't want it merged, but I think you still do.

**Comment by nelsonSchwarz** [comment]
Oh... whoops

**Comment by nelsonSchwarz** [comment]
'Tis my second time requesting a pull. Such a noob XD

**Comment by nik9000** [comment]
> Such a noob XD

No problem! I've merged this to master, now for the backports.

**Comment by nik9000** [comment]
Master: ee35bba6b640962bd159193091241e35f08aab42
5.x: c2113b099eae4a6133f2481afe2e7c50b9865abd
5.1: 222785320e039ac6642f402264626d832e2a3939
5.0: 976b489e8208142cc404ef11ffd758e115357422

**Comment by nik9000** [comment]
> now for the backports

All done. Thanks again @nelsonSchwarz!

**Comment by nelsonSchwarz** [comment]
No, thank you :D

**Pull request merged**
