### PR TITLE
Allow explain data stream lifecycle to accept a data stream.

### PR DESCRIPTION
**Pull request by gmarouli**
Currently the `GET target/_lifecycle/explain` API only works for indices. In this PR we extend this behaviour to allow the target to be a data stream so we can get the overview lifecycle status for all the backing indices of a data stream.

### CODE REVIEW

**Comment by gmarouli** [comment]
@elasticmachine update branch

**Review by andreidan — APPROVED** [review]
🚀 Thanks for working on this Mary

LGTM

**Comment by gmarouli** [comment]
Happy to!

**Comment by gmarouli** [comment]
@elasticmachine update branch

**Pull request merged**
