### PR TITLE
Fix error log class name issue

### PR DESCRIPTION
**Pull request by howardhuanghua**
Fix error log name issue.

### CODE REVIEW

**Comment by gwbrown** [comment]
@elasticmachine test this please

**Comment by gwbrown** [comment]
@elasticmachine update branch

**Comment by gwbrown** [comment]
@howardhuanghua Could you please merge `master` into your branch? It doesn't appear we have permission to do that automatically.

**Comment by howardhuanghua** [comment]
@gwbrown Thanks, branch has been updated.

**Comment by gwbrown** [comment]
@elasticmachine test this please

**Comment by howardhuanghua** [comment]
@gwbrown Would you please help to merge this simple PR? It seems all checks have hassed.

**Review by pugnascotia — APPROVED** [review]

**Comment by pugnascotia** [comment]
Backported to `7.x` in f0603faf504.

**Pull request merged**
