### PR TITLE
[DOCS] Fix typo in 7.15 release highlights

### PR DESCRIPTION
**Pull request by jessepeterman**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by dliappis** [comment]
@jessepeterman thank you for spotting this! Could you please sign the contributor agreement as requested in https://github.com/elastic/elasticsearch/pull/78426#issuecomment-929830799?

**Comment by jessepeterman** [comment]
I did yesterday, but maybe it didn’t work?

**Comment by jessepeterman** [comment]
@dliappis looks like the signature check through.

**Comment by jrodewig** [comment]
@elasticmachine ok to test

**Review by jrodewig — APPROVED** [review]
Thanks for spotting this @jessepeterman. 🦅 👁️ 

LGTM.

**Pull request merged**
