### PR TITLE
Fix compilation issues in example-plugins

### PR DESCRIPTION
**Pull request by pugnascotia**
Commit 051e1d6c3cc04f325703ca846dc84f58a0ece00e broke a couple of the example plugins
project, so get them working again.

### CODE REVIEW

**Review by arteam — APPROVED** [review]
LGTM!

**Comment by cbuescher** [comment]
Sorry for the noise, just catching up on this. I'm curious about why we didn't get these errors on CI when running it on the PR that introduced this change (i.e. #78621)

**Comment by pugnascotia** [comment]
Looks like CI only builds the example plugins if the directory has changed, or any of the build related directories at the top-level have changed. But that's clearly not working because the example plugins depend on the server code, so we need to look at changing that.

cc @mark-vieira

**Comment by cbuescher** [comment]
@pugnascotia thanks for fixing, I don't think this needs to go to 8.0 and 7.17 though since the change causing this was only merged to 8.1 and we don't intend to backport there.

**Comment by pugnascotia** [comment]
@cbuescher OK, I close the backport PRs. I was partly doing that because the other branches also contain a typo in the example plugins build file, but I'll fix that separately.

**Pull request merged**
