### PR TITLE
Simplify TimeValue Serialization

### PR DESCRIPTION
**Pull request by original-brownbear**
This can be done without map look-ups => less code and much smaller methods => better inlining potentially.

### CODE REVIEW

**Comment by dakrone** [comment]
I'm concerned this will break us in the event that the JDK adds a different timeunit. For example, if they were to add "picoseconds" to TimeUnit some or all of the offsets could shift and make our stream serialization incorrect between JDK versions. Even in the event they decide to sort the enum differently it could cause that. I think I'd rather stick with our safe serialization.

> This can be done without map look-ups => less code and much smaller methods => better inlining potentially.

We could switch this to a static array for the same skip of map lookups, it would still need the static block but the actual performance sensitive part would use array offsets rather than map lookups

**Comment by original-brownbear** [comment]
Makes sense @dakrone :) how about just adding this assert https://github.com/elastic/elasticsearch/pull/62023/commits/05285f4b1afd887c07d4774ca4e435c56df26703 to prevent that problem for occurring going forward?
We could obviously just hand craft our own array but I figured it's a little more natural this way when we use the enum ordinal on one side and the actual `values()` on the other side?

**Comment by dakrone** [comment]
> how about just adding this assert 05285f4 to prevent that problem for occurring going forward?

I think we should throw a real exception and fail the class initialization, otherwise assertions will be silent for folks running an older ES (with the assertions) with a new JDK (where the assertions would normally fail) since assertions are disabled by default.

**Comment by original-brownbear** [comment]
> I think we should throw a real exception and fail the class initialization, otherwise assertions will be silent for folks running an older ES (with the assertions) with a new JDK (where the assertions would normally fail) since assertions are disabled by default.

Good point thanks! I pushed https://github.com/elastic/elasticsearch/pull/62023/commits/2acdab870fa4aa1d2953886aee821017371f0fed :)

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/2

**Review by dakrone — APPROVED** [review]
LGTM, thanks for iterating on this

**Pull request merged**
