### PR TITLE
[7.x] Include hidden indices in snapshots by default (#57325)

### PR DESCRIPTION
**Pull request by AthenaEryma**
Backports the following commits to 7.x:
 - Include hidden indices in snapshots by default (#57325)

### CODE REVIEW

**Comment by gwbrown** [comment]
@original-brownbear There were some problems with the backport on this one - namely, that the `CreateSnapshotRequest` class is used both server-side and for the HLRC. The new default includes the `hidden` value for `expand_wildcards`, which isn't accepted by 6.x versions, which breaks our BWC tests.

In order to solve this, I've adjust `CreateSnapshotRequest#toXContent` to only serialize the `IndicesOptions` if they differ from the default value. This isn't a great solution, and I would be delighted to implement an alternative if you can suggest one (or do more thinking on this if this will have consequences I didn't think of). What do you think?

**Comment by gwbrown** [comment]
BWC failed again, but it looks like it might have been a more general problem. I'm still digging in, but I'd like to see if it reproduces, so:
@elasticmachine run elasticsearch-ci/bwc

**Comment by gwbrown** [comment]
I'm still not sure exactly what the problem was (looks like something to do with data streams?), but merging the latest 7.x branch fixed things locally.

**Comment by original-brownbear** [comment]
@gwbrown 

welcome to the club :) I handled the same issue in a more isolated case in https://github.com/elastic/elasticsearch/pull/57661 already. Maybe you can go for the same fix in the affected tests here as well? 
As far as I understand the YAML tests don't use the HLRC so they shouldn't be affected. So that only leaves a limited number of specific REST tests to adjust. I'm not necessarily against you change philosophically. I think it's technically something we might want to do. 
The downside of it is, that it's a serious change in our BwC philosophy that seems to serialize the defaults into a request so that the defaults of the client version used are used for requests (just like we did in the transport client). Maybe we want to change this to using server side defaults (I can see arguments for that), but this might not be the place to do that => I'd suggest replacing HLRC usages with LLRC usage. We did that in a number of other snapshot REST tests besides the linked PR already so that seems to be the non-controversial solution here to me.

**Comment by gwbrown** [comment]
@original-brownbear Thanks, that's immensely useful. I think I was overestimating the scope of the problem - this appears to be the only test class that's impacted. And actually, with the changes from https://github.com/elastic/elasticsearch/pull/57661, no changes are needed to the PR. The original test failure I found was from before you merged that fix.

Since this appears to address the problem, I've added those changes to the 7.7 (https://github.com/elastic/elasticsearch/pull/57637) & 7.8 (https://github.com/elastic/elasticsearch/pull/57635) backports of this change, and reverted the serialization changes.

---

While writing this comment, there was a test failure ([build scan](https://gradle-enterprise.elastic.co/s/bkiss2niucsbe)) that does not reproduce locally and appears entirely unrelated. I'm going to run it again to see if it reproduces.

@elasticmachine run elasticsearch-ci/1

**Pull request merged**
