### PR TITLE
DFA Get Stats can return multiple responses if more than one error

### PR DESCRIPTION
**Pull request by davidkyle**
If the search for get stats for multiple jobs fail the listener is called for each failure. This change waits for all responses then returns the first error if there was one. 

This solves half the problem reported in #60876 which also serves as test coverage for the change as it is very difficult to test directly

### CODE REVIEW

**Review by droberts195 — APPROVED** [review]
LGTM

**Comment by dimitris-athanasiou** [comment]
We follow the same pattern in `TransportGetJobsStatsAction.gatherStatsForClosedJobs` too. Might be worth fixing the same issue there.

**Comment by davidkyle** [comment]
> We follow the same pattern in TransportGetJobsStatsAction.gatherStatsForClosedJobs

😱 how did we miss that

**Comment by davidkyle** [comment]
@elasticmachine update branch

**Comment by davidkyle** [comment]
run elasticsearch-ci/packaging-sample-windows

**Comment by Mpdreamz** [comment]
@davidkyle was this backported to `7.9`? I only see a commit linked against `7.x`

**Comment by davidkyle** [comment]
>  was this backported to 7.9?

Erm no and I've missed 7.9.1 FF now. 
This isn't a critical bug it can bypass 7.9 and go directly to 7.10 I've updated the labels accordingly.

Thanks for the ping 🙏

**Comment by droberts195** [comment]
> This isn't a critical bug it can bypass 7.9 and go directly to 7.10 I've updated the labels accordingly.

As a result of not backporting this to 7.9 we still have test failures in 7.9, for example https://gradle-enterprise.elastic.co/s/5rmxilu75h5ik

So I think either this fix should be backported to 7.9 regardless of whether it will get released or else that test should be muted in 7.9.

**Comment by davidkyle** [comment]
Those recent failures are caused by a leaking test and should have been fixed by #61180 but that change was also not backported. I've raised #62054 to backport to 7.9.

The failure fixed in this PR is very rare, I don't think the backport is necessary at this stage

**Pull request merged**
