### PR TITLE
Add prefer_v2_templates flag and index setting

### PR DESCRIPTION
**Pull request by dakrone**
This commit adds a new querystring parameter on the following APIs:
- Index
- Update
- Bulk
- Create Index
- Rollover

These APIs now support a `?prefer_v2_templates=true|false` flag. This flag changes the preference
creation to use either V2 index templates or V1 templates. This flag defaults to `false` and will be
changed to `true` for 8.0+ in subsequent work.

Additionally, setting this flag internally sets the `index.prefer_v2_templates` index-level setting.
This setting is used so that actions that automatically create a new index (things like rollover
initiated by ILM) will inherit the preference from the original index. This setting is dynamic so
that a transition from v1 to v2 templates can occur for long-running indices grouped by an alias
performing periodic rollover.

This also adds support for sending this parameter to the High Level Rest Client.

Relates to #53101

### CODE REVIEW

**Comment by dakrone** [comment]
This work does not yet change the default to `true` (will only be done for 8.0 in a subsequent PR). It also doesn't support reindex yet, as that is more complex to pass a flag through (again, will be done in subsequent work).

**Comment by dakrone** [comment]
@elasticmachine update branch

**Review by andreidan — APPROVED** [review]
This looks great Lee. Thanks for working on this. 

I've just marked a few places where using the @Nullable annotation would be a nice readability and IDE aid, super minor though. Nice work!

**Comment by dakrone** [comment]
@elasticmachine update branch

**Pull request merged**
