### PR TITLE
Remove unnecessary shuffle in unassigned shards allocation.

### PR DESCRIPTION
**Pull request by howardhuanghua**
We always sort unassigned shards before allocating them. Here are the sorting logics:

For exsiting shards allocation:
https://github.com/elastic/elasticsearch/blob/caf9cd28804f0f44a01f6f0df6fa07018df3fb8e/server/src/main/java/org/elasticsearch/cluster/routing/allocation/AllocationService.java#L443

For new created shards or peer recovery shards allocation:
https://github.com/elastic/elasticsearch/blob/caf9cd28804f0f44a01f6f0df6fa07018df3fb8e/server/src/main/java/org/elasticsearch/cluster/routing/allocation/allocator/BalancedShardsAllocator.java#L797

So, the shuffle should be unnecessary before allocating them. This PR removes related unassigned shards shuffle operations.

### CODE REVIEW

**Comment by howardhuanghua** [comment]
Hi @matriv thanks for check PRs, would you please also help to find appropriate members to review this https://github.com/elastic/elasticsearch/pull/64753 bug fix? I think it should be omitted.

**Comment by matriv** [comment]
@howardhuanghua 

Both PRs are labeled/routed to the teams, so they'll get to them when they have the capacity to do so.

**Comment by howardhuanghua** [comment]
> @howardhuanghua
> 
> Both PRs are labeled/routed to the teams, so they'll get to them when they have the capacity to do so.

Thanks a lot @matriv .

**Comment by henningandersen** [comment]
@elasticmachine check this please

**Comment by howardhuanghua** [comment]
@henningandersen Would you please help to check this PR? I have updated the master branch. Thanks.

**Review by henningandersen — APPROVED** [review]
LGTM.

**Comment by henningandersen** [comment]
@elasticmachine check this please

**Comment by henningandersen** [comment]
@elasticmachine check this please

**Comment by henningandersen** [comment]
@elasticmachine check this please

**Comment by howardhuanghua** [comment]
Merged latest master branch. Thanks @henningandersen .

**Comment by henningandersen** [comment]
@elasticmachine test this please

**Comment by henningandersen** [comment]
@elasticmachine update branch

**Comment by howardhuanghua** [comment]
Branch has been updated.

**Comment by henningandersen** [comment]
@elasticmachine test this please

**Comment by henningandersen** [comment]
@elasticmachine run elasticsearch-ci/part-2

**Comment by henningandersen** [comment]
Thanks for your contribution @howardhuanghua and sorry for the delay on progressing this.

**Comment by howardhuanghua** [comment]
@henningandersen My pleasure, thank you.

**Pull request merged**
