### PR TITLE
Update lowercase-tokenizer.asciidoc

### PR DESCRIPTION
**Pull request by atorres757**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?

Fixed typo

### CODE REVIEW

**Comment by nik9000** [comment]
@atorres757, the change looks good to me. Can you sign the CLA? We need it for all changes, even single letter changes to the docs.

**Comment by atorres757** [comment]
@nik9000 CLA is signed.

**Comment by nik9000** [comment]
Awesome! I'm replying mostly to make the CLA checker recheck....

**Comment by nik9000** [comment]
Thanks @atorres757! I've merged and now I'll backport.

**Comment by nik9000** [comment]
Master: 887fbb63872989e3c6bde7f67770a23a90b15247
5.x: bfb7c1b3a7efeea8913e4432a8b95a35ad5f452b
5.1: 6c7b11e7f5b35a8ff7847c22dcd67bdb4a4c5772
5.0: 521abcbc7f1f275086239695087567d0fbc922dd

**Pull request merged**
