### PR TITLE
ensure no initializing shards during cluster cleanup

### PR DESCRIPTION
**Pull request by talevy**
the illusive ShardLockObtainFailedException!

there are testing situations where newly created indices
are being wiped before they are fully initialized. This results
in an edge-case in the shard-locking strategy where an index
cannot be deleted.

This should fix these scenarios and reduce noise in the logs.

test examples with this occurring:

- https://github.com/elastic/elasticsearch/issues/30290#issuecomment-411064344
- https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.0+multijob-darwin-compatibility/21/console

I do not believe this to solve any test failures, since I believe these exceptions
in the logs are a side-effect of tests failing early right after a new index is created.

Plus, this exception is suppressed and logged. There is later cleanup by the cluster
to cleanly delete any pending deletes.

### CODE REVIEW

**Comment by talevy** [comment]
should I open an issue to provide better log messages around why a delete failed?

From the looks of it, this exception is logged every time an index isn't fully initialized.

**Comment by dakrone** [comment]
> should I open an issue to provide better log messages around why a delete failed on its first attempt?

I think that would also be helpful

**Review by dakrone — APPROVED** [review]
LGTM

**Comment by talevy** [comment]
run elasticsearch-ci/2

**Comment by talevy** [comment]
build looks like it failed because at least one node shut down unexpectedly

**Comment by talevy** [comment]
@dakrone I've update this to use `adminClient` since some users like the ones in ML tests do not have permissions. that cool?

**Comment by dakrone** [comment]
@talevy seems reasonable to me

**Comment by talevy** [comment]
thanks, agreed!

**Pull request merged**
