### PR TITLE
Remove Uid as an instantiable class

### PR DESCRIPTION
**Pull request by romseygeek**
The `Uid` class encapsulates a document's type and id.  Now that indexes only have a single
type, this extra information is superfluous, and we can just pass around ids as simple
String values.

This commit cuts over the remaining few places that use `Uid` objects to use Strings, 
and also makes the `Uid` class non-instantiable, preserving only some static helper methods
for efficient encoding of numeric values.

### CODE REVIEW

**Review by pugnascotia — APPROVED** [review]

**Comment by romseygeek** [comment]
@elasticmachine update branch

**Comment by romseygeek** [comment]
@elasticmachine update branch

**Comment by romseygeek** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by romseygeek** [comment]
I'd hoped to backport this to 7x as well, but the translog still uses types there so it's not possible.

**Pull request merged**
