### PR TITLE
Fix Edge-Case Threading Bug in TransportMountSearchableSnapshotAction

### PR DESCRIPTION
**Pull request by original-brownbear**
The callback to loading the repository-data may not run on generic in the uncached case
because of the repo data deduplication logic.
The same issue was fixed for the snapshot status API in https://github.com/elastic/elasticsearch/pull/68023

### CODE REVIEW

**Comment by DaveCTurner** [comment]
Ugh this corner case is so trappy. Yeah I know it's in the docs, but clearly we don't read them enough. Maybe always forking would be better?

Anyway yes I'd prefer to merge #73172 and go straight onto the new pool rather than merge 38168a6 as it stands.

**Comment by original-brownbear** [comment]
> Maybe always forking would be better?

You mean in the repository? The annoying thing about that is that it may cause a number of needless context switches where we don't actually have to fork off. But maybe with the new pool that's ok and we could always switch to it even if it causes some needless switches.

For now I just made this thing fork to the new pool though.

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Comment by original-brownbear** [comment]
Thanks David!

**Pull request merged**
