### PR TITLE
Spelling

### PR DESCRIPTION
**Pull request by evanfreed**
Corrected spelling, nothing to special.

### CODE REVIEW

**Comment by clintongormley** [comment]
Thanks for the PR.  Please could I ask you to sign the CLA so that I can merge it in?
http://www.elasticsearch.org/contributor-agreement/

**Comment by evanfreed** [comment]
Done.

**Comment by nik9000** [comment]
OK! Merged to 2.2 with: 727f77d6bd39cbe01423d556a2e338348b5f897d

I'm going to cherry pick it to a few useful branches.

**Comment by nik9000** [comment]
master: 7ed30a9c00cc1d302efc75fa98ba76ebe8260d97
2.x: 64e49b85901e63a8d92ed2ab8f1a6228aa3e234f
2.1: 16ea47b109ab3405eba2e63b1c97217b7d158ddb
2.0: ae2f0787e51f01de6adec382680fb12851396705

**Comment by nik9000** [comment]
All done! Thanks @evanfreed !

**Pull request merged**
