### PR TITLE
Build: Move test framework files to their new location

### PR DESCRIPTION
**Pull request by rjernst**
The test jar was previously built in maven by copying class files. With
gradle we now have a proper test framework artifact. This change moves
the classes used by the test framework into the test-framework module.

See #13930

### CODE REVIEW

**Comment by jpountz** [comment]
LGTM

**Comment by jpountz** [comment]
Unfortunately this causes integration issues with Eclipse, since Eclipse builds both source and test files at once, and so it detects a cyclic dependency between core and the test-framework.

I wouldn't like to revert this change just because of Eclipse, yet it seems important to me to have good eclipse integration (not as much for us as for external contributors). The only work-around I can think of right now would be to generate a single project that contains all modules like Lucene does (and Lucene has the same kind of core <-> test-framework dependency). I can look into it if this looks reasonable and if nobody can't think of an easier option.

**Comment by jpountz** [comment]
Maybe just ignoring this error as described at http://stackoverflow.com/a/17208409/675589 is a sufficient workaround

**Comment by rmuir** [comment]
I think a better fix is to modify our groovy build to configure eclipse properly? You can get access to the generated eclipse data and modify it before it is written:

```
eclipse {
  classpath {
    file {
      //closure executed after .classpath content is loaded from existing file
      //but before gradle build information is merged
      beforeMerged { classpath ->
        //you can tinker with the Classpath here
      }
   }
}  
```

https://docs.gradle.org/current/dsl/org.gradle.plugins.ide.eclipse.model.EclipseClasspath.html

We could e.g. hackishly remove the project dependency on test-framework and replace it with an equivalent ordinary classpath entry pointing to test-framework/src/java, and i think things would mostly work as before? There might be better solutions here too.

**Pull request merged**
