### PR TITLE
Default ec2 endpoint is ec2.us-east-1.amazonaws.com

### LINKED ISSUE #27464: ec2-discovery plugin document is not accurate.
**Elasticsearch version**: 6.0.0

**Plugins installed**: ec2-discovery

**Description of the problem including expected versus actual behavior**:

> [ec2 service endpoint to connect to. This will be automatically figured out by the ec2 client based on the instance location, but can be specified explicitly](https://github.com/elastic/elasticsearch/blob/6.0/docs/plugins/discovery-ec2.asciidoc
)
The document states ec2 service endpoint is automatically figured out by ec2 client, but I need to set the endpoint to make the plugin work. 

This document is correct if the plugin uses AmazonEC2ClientBuilder to build AmazonEC2Client instance. But AmazonEC2Client is created directly, so the endpoint is set to default endpoint, "https://ec2.us-east-1.amazonaws.com."

Related https://github.com/elastic/elasticsearch/issues/25619

### PR DESCRIPTION
**Pull request by dadoonet**
I split #27925 in two parts:

* The documentation fix (this PR)
* The code fix (still in #27925)

Closes #27464.

### CODE REVIEW

**Comment by wedneyyuri** [comment]
Hi @dadoonet, what do you think about changing the statement below?

> The **only necessary** configuration change to enable the plugin is setting the unicast host provider for zen discovery
https://github.com/elastic/elasticsearch/blob/0d11b9fe34c007fddc5cbf2c821ef226b7a0fc75/docs/plugins/discovery-ec2.asciidoc#getting-started-with-aws

**Comment by dadoonet** [comment]
Thanks for the feedback @wedneyyuri! I updated the PR.

**Comment by sadok-f** [comment]
Any update on this PR?

**Comment by bleskes** [comment]
@trlx can you see if this can be folded in and close #27464 ?

**Comment by mdunc** [comment]
Does it normally take this long to fix a documentation bug?  I just spent a good chunk of my weekend trying to figure out why my new cluster in EU wasn't working when I had everything configured according to the documentation.  Wish I found this PR earlier.

**Comment by DaveCTurner** [comment]
Unfortunately there was a typo in [the earlier ping for a review](https://github.com/elastic/elasticsearch/pull/30323#issuecomment-399972798). It should have notified @tlrx.

**Comment by dadoonet** [comment]
@elastic/es-distributed Can we merge this documentation PR? People are still suffering from that because our documentation is not accurate. See https://discuss.elastic.co/t/discovery-ec2-plugin-always-tries-to-ping-localhost-never-finds-the-nodes-that-it-should/160433/8

**Pull request merged**
