### PR TITLE
Watcher: ensure Authorization header is not serialized to xContent

### PR DESCRIPTION
**Pull request by jakelandis**

### CODE REVIEW

**Comment by dakrone** [comment]
@jakelandis is this still applicable?

**Comment by jakelandis** [comment]
@elasticsearchmachine update branch

**Comment by jakelandis** [comment]
whoops test failure is related ... will fix soon.

**Comment by dakrone** [comment]
@jakelandis do you want someone on the DM team to take this one over for now?

**Comment by jakelandis** [comment]
@dakrone - thanks for the nudge, it just needed a minor adjustment to the test

@masseyke - can you take a look now ?

**Comment by masseyke** [comment]
@jakelandis do we need to worry about the other headers [here](https://github.com/elastic/elasticsearch/blame/main/server/src/main/java/org/elasticsearch/common/util/concurrent/ThreadContext.java#L605)?

**Comment by jakelandis** [comment]
> do we need to worry about the other headers [here](https://github.com/elastic/elasticsearch/blame/main/server/src/main/java/org/elasticsearch/common/util/concurrent/ThreadContext.java#L605)?

I don't think so. Those headers are specific to ES for some specific work flows that Watcher is not likely to perform. The main goal of this PR is to handle headers for general purpose HTTP requests.

**Review by masseyke — APPROVED** [review]
LGTM

**Pull request merged**
