### PR TITLE
Update phrase-suggest.asciidoc

### PR DESCRIPTION
**Pull request by ulkas**
small sentence fix

### CODE REVIEW

**Comment by nik9000** [comment]
Much better! Thanks @ulkas. Can you sign the [CLA](https://www.elastic.co/contributor-agreement) so I can merge it? We need the CLA no matter how small the change.

**Comment by ulkas** [comment]
yes, its done already. please merge

**Comment by nik9000** [comment]
> yes, its done already. please merge

Cool. I'll see if I can figure out why the automation is complaining.

**Comment by ulkas** [comment]
dont bother, i didnt sign it before, just right after the automation complained and before you commented

**Comment by nik9000** [comment]
> dont bother, i didnt sign it before, just right after the automation complained and before you commented


Hmm - its not coming through. Is there a chance that you signed it with a different email then you signed the commit?

**Comment by ulkas** [comment]
@nik9000 yes, the license was signed under my company email whereas my github account is personal. but at the signing page there was also a filed for my github username, so it should be able to match my credentials

**Comment by nik9000** [comment]
I found the CLA documentation and manually added you to the checker database and it verified you on that side - this comment should trigger the check again. Regardless of what the check does you are in there and I'll merge this. I just want to see if the check goes green.

**Comment by nik9000** [comment]
OK! Merged to 1.7 and cherry picked to 2.0, 2.x, and master.

**Pull request merged**
