### PR TITLE
Add vector search file extensions to preload info

### PR DESCRIPTION
**Pull request by mayya-sharipova**
Relates to #96955

### CODE REVIEW

**Review by benwtrent — COMMENTED** [review]
I think it would be good to call out the vector focused ones separately to indicate how to optimize for vector search.

**Comment by mayya-sharipova** [comment]
> I think it would be good to call out the vector focused ones separately to indicate how to optimize for vector search.

@benwtrent Thanks for your review, Ben. By this you mean as a separate section called "Optimizing for vector search"?

**Comment by benwtrent** [comment]
No, probably just a separate sentence mentioning these are the specific extensions for vector. All the other ones are specific to text search and aggs.

I think what we honestly need is an enumerated list of all extensions and what each individual extension contributes to... But that is a separate issue :).

**Comment by mayya-sharipova** [comment]
@benwtrent Please check if the new version looks better.

**Review by benwtrent — APPROVED** [review]
Looks good. I added `auto-backport-and-merge` all the way back to when we GA'd. that way folks on older versions have correct documentation.

**Pull request merged**
