### PR TITLE
add desc mappings explosion

### PR DESCRIPTION
**Pull request by TanyaPedersen**
Description of mappings explosion, causes, and effects added to docs/reference/mapping.asciidoc

### CODE REVIEW

**Comment by clintongormley** [comment]
Hi @TanyaPedersen 

Thanks for the PR.  I find the example you give rather confusing.  perhaps a better example would be one which uses an `ip` address as a field name to count page views, with the correct implementation being storing the ip address as a value along with the view count.

Explain that each key represents a separate field (and inverted index) and using values as keys results in sparse data, an excess of fields, a growth in cluster state, and eventually performance issues and potentially OOM.

thanks

**Comment by TanyaPedersen** [comment]
Thanks @clintongormley 

I'm at the ridiculously crazy point of the university semester in terms of work load, I'll make those changes within the week

Regards

**Comment by rjernst** [comment]
@TanyaPedersen Are you still interested in working on this change?

**Comment by dakrone** [comment]
Closing as there has been no feedback, feel free to comment if this was closed erroneously.

**Pull request closed without merging**
