### PR TITLE
Add implicit this for class binding in Painless

### PR DESCRIPTION
**Pull request by jdconrad**
This change allows class bindings to add as their first argument, the base script class.  The ```this``` reference to the base script class will be implicitly passed into a class binding as the first constructor argument upon initialization when specified as the first argument in whitelist entry for the class binding.  This allows a class binding access to additional information added to the base script class such as more information about the current document or current shard.  One extra requirement for this to work is the appropriate script base class must be whitelisted (should be empty).  This should improve the situation for (https://github.com/elastic/elasticsearch/pull/40186) as the user should only have to pass in the initial seed value.

Example:
Whitelist:
```
class org.elasticsearch.painless.BindingsTests$BindingsTestScript {
}

static_import {
int addThisWithState(BindingsTests.BindingsTestScript, int, int, int, double) bound_to org.elasticsearch.painless.BindingsTests$ThisBindingTestClass
}
```
Binding Class:
```
    public static class ThisBindingTestClass {
        private BindingsTestScript bindingsTestScript;
        private int state;

        public ThisBindingTestClass(BindingsTestScript bindingsTestScript, int state0, int state1) {
            this.bindingsTestScript = bindingsTestScript;
            this.state = state0 + state1;
        }

        public int addThisWithState(int istateless, double dstateless) {
            return istateless + state + (int)dstateless + bindingsTestScript.getTestValue();
        }
    }
```
Painless Script:
```
addThisWithState(4, bound, test, 0.0)
```

### CODE REVIEW

**Comment by jdconrad** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Review by rjernst — APPROVED** [review]
LGTM. Can you please add a comment somewhere to this explaining the rationale of using this hack and the desired eventual design?

**Comment by jdconrad** [comment]
@rjernst Thanks for the review!  Will find an appropriate place for and add the requested comment and then commit once CI passes.

**Comment by mayya-sharipova** [comment]
@jdconrad  Jack, thank so much for this change. This is really great. 
I just have a question how to pass my base script class to `ScoreScript`, so that my base script class will be used for scoring?

**Comment by jdconrad** [comment]
@mayya-sharipova Looks to me like the ScoreScript is the base class in this case unless I'm missing something.  I noted that you already have a whitelist resource file specifically for the score context, so I believe (once this is commited) that you can just add ScoreScript to the whitelist as an empty class and then add it as the first argument for the binding and it will be implicitly passed in without the user needing to add it.

Example:
Whitelist:
```
class org.elasticsearch.script.ScoreScript no_import {
}
static_import {
  scoreScriptRandom(org.elasticsearch.script.ScoreScript, int seed) bound_to org.elasticsearch.script.ScoreScriptRandomClass
}
Painless Call:
```
scoreScriptRandom(seed)
```
where seed is considered to be read-only

From here you can add whatever methods you need to ScoreScript and call them directly from the ScoreScriptRandomClass since the ScoreScript will be passed into the constructor.  You can also check out the example in BindingsTests.

Please let me know if you have further questions :)

**Comment by mayya-sharipova** [comment]
@jdconrad  Jack, just tested - everything works fantastic! Thanks for this change

**Pull request merged**
