### PR TITLE
Adds toString() functionality to SuggestRequestBuilder + SuggestBuilder

### PR DESCRIPTION
**Pull request by bly2k**
Just like SearchRequestBuilder, this adds toString() functionality to SuggestRequestBuilder + SuggestBuilder

### CODE REVIEW

**Comment by EdgeCaseBerg** [comment]
Would love to see this merged in. (And if possible back-ported to older versions of ES as well!)

**Comment by nik9000** [comment]
I think the whole "helper method for an xcontent toString" is a good idea. I see us repeat it quite a bit. Anyone involved in the query refactoring like the idea? @abeyad or @colings86?

Personally I'd just do the wrapInObject=true case.

Is it too crazy to implement it with a default method on an interface that extends ToXContent? Heck, it could even be ***on*** ToXContent if we limit the length of the result.

**Comment by colings86** [comment]
As part of the refactoring of SuggestBuilder we should be making SuggestBuilder extend ToXContentToBytes which will solve half of this and I don't see why we can't add toString() to SuggestRequestBuilder too. I think it will end up being done as part of the suggester refactoring PRs rather than merging this PR though. @cbuescher @areek what do you think?

**Comment by abeyad** [comment]
We already have `SuggestBuilder` extending `ToXContentToBytes` as part of the suggest refactoring PRs.  This will end up in master when the feature branch is more complete.  Implementing a `toString()` method on these will be very easy afterward (just a matter of calling `toXContent` on the `SuggestBuilder`).  If this PR can wait, then the feature/suggest-refactoring branch will have these features "built-in".

**Comment by nik9000** [comment]
I believe its safe to have it wait for the suggest-refactoring branch. Its waited this long....

**Comment by colings86** [comment]
++

Just a note that ToXContentToBytes implements toString() for you and calls the abstract ToXContent method so there will be no need to add implementing toString() :)

**Comment by clintongormley** [comment]
Closed in favour of https://github.com/elastic/elasticsearch/tree/feature-suggest-refactoring

**Pull request closed without merging**
