### PR TITLE
Update apm agent to 1.36.0

### LINKED ISSUE #94689: JDK 20 upgrade has broken APM tracing
In PR #94600, we upgraded the bundled JDK to 20. However, it now appears that running ES with JDK 20 breaks APM tracing. JVM metrics are still reported, but no spans appear.

   * @jamesspi reported that he couldn't see traces in Kibana after configuring APM on a branch.
   * I tried configuring APM using the 8.6.2 distribution from the website, and it worked as expected
   * I then tried the branch above, and no spans were reported
   * I tried `main`, same thing.
   * I tried the `8.7` branch, same thing
   * I reverted commit 3b79a4fd3b62a27a84cf18cc5846a10145ce87b0 locally, to downgrade to JDK 19, and now spans were show in Kibana.

### PR DESCRIPTION
**Pull request by SylvainJuge**
fixes #94689

The APM agent version 1.33.0 fails to start on JDK 20, which prevents the APM integration to work as expected.
As a consequence, the tracing does not work.

When setting `ELASTIC_APM_LOG_LEVEL=debug` and `ELASTIC_APM_LOG_FILE=/tmp/log.txt`, the agent log shows that there is an issue with accessing `Unsafe` (sorry I don't have the exact stack trace).

There was a few changes in APM agent regarding the security manager (SM) in recent versions, and updating the agent seems to make it work as expected.

However, there is one known caveat so far (https://github.com/elastic/apm-agent-java/issues/3074), keeping the agent with `debug` log level with `ELASTIC_APM_LOG_LEVEL=debug` makes it trigger another security exception when trying to establish connection with apm-server because the agent prints few details if a proxy is used or not (which is forbidden by default by the SM and isn't yet wrapped in a privileged call.

### CODE REVIEW

**Review by pugnascotia — COMMENTED** [review]
Changes look good. Have you tried configuring ES with tracing enabled?

**Comment by mark-vieira** [comment]
Thanks @SylvainJuge. I've created https://github.com/elastic/elasticsearch/issues/94730 to also put a process in place to ensure we're keeping the bundled agent up to date.

**Comment by pugnascotia** [comment]
@SylvainJuge I built a Docker image from your branch and tested a 3 node ES cluster with Kibana, and it all seems to work, so long as I have agent debug logging disabled. Initially, I didn't notice that I had the agent running with debug logging, and that did indeed seems to break a lot of span recording. But without debugging, all good.

**Review by pugnascotia — APPROVED** [review]

**Comment by SylvainJuge** [comment]
@elasticmachine run elasticsearch-ci/docs

**Pull request merged**
