### PR TITLE
rename ChangePolicyforIndexIT to ChangePolicyForIndexIT

### PR DESCRIPTION
**Pull request by weizijun**
a tiny PR, that rename ChangePolicyforIndexIT to ChangePolicyForIndexIT.

### CODE REVIEW

**Comment by weizijun** [comment]
hi @martijnvg, can you help to merge the PR?

**Comment by martijnvg** [comment]
@weizijun Thanks, but I don't think it is needed to add a change log entry for renaming a test. Only for things like new features, enhancements and bug fixes.

**Comment by weizijun** [comment]
> @weizijun Thanks, but I don't think it is needed to add a change log entry for renaming a test. Only for things like new features, enhancements and bug fixes.

ok, I have removed the change log.

**Comment by martijnvg** [comment]
@elasticmachine test this please

**Pull request merged**
