### PR TITLE
Use VAULT_TOKEN environment variable if it exists

### PR DESCRIPTION
**Pull request by mark-vieira**
As a follow up to https://github.com/elastic/infra/pull/13780#issuecomment-521025910 we should try and use the `VAULT_TOKEN` passed into the build from CI when possible.

### CODE REVIEW

**Comment by mark-vieira** [comment]
This is blocked on #13907.

**Comment by atorok** [comment]
@mark-vieira that issue number looks incorrect. 
/cc @flaper87

**Comment by mark-vieira** [comment]
Thanks, Alpar. I updated that.

**Review by alpar-t — APPROVED** [review]
LGTM

**Comment by flaper87** [comment]
thanks, I had to do this in my fork too. Was planning to send a patch but I was too slow.

lgtm

**Comment by mark-vieira** [comment]
It's actually elasticsearch/infra#13907 that needs to be addressed before this. Right now this PR wouldn't actually do anything since we never set `VAULT_TOKEN` in CI.

**Comment by flaper87** [comment]
> It's actually elastic/infra#13907 that needs to be addressed before this. Right now this PR wouldn't actually do anything since we never set VAULT_TOKEN in CI.


It won't so much but it's a step forward down the right direction. I could also use it in my Zuul tests. I had to hack it in myself but I'd rather use this patch.

**Comment by mark-vieira** [comment]
There seems to be consensus this is worth happening so I've merged this and backported to all active branches.

**Pull request merged**
