### PR TITLE
Adding endpoint creation validation for all task types to remaining services

### PR DESCRIPTION
**Pull request by dan-rubinstein**
## Description
This change introduces:
- Adds new validation logic for creating endpoints in the Alibaba, AmazonBedrock, Anthropic, AzureOpenAi, Cohere, GoogleVertexAI, and IBMWatson services.
   - For text embedding endpoints the logic will make a validation call, update the model's dimensions to match the returned embedding size, and set the default similarity measure value when necessary.
   - For non text embedding models, the validation will ensure that a non-null response is returned when calling the service.

## Testing
- Ran unit tests and ensured that all succeed
- Validated that trying to create valid endpoints for all of the services above makes a validation call and updates the model when necessary.
- Validated that trying to create an invalid endpoint for all of the services above makes a validation call and fails and the endpoint is not created.

### CODE REVIEW

**Review by davidkyle — APPROVED** [review]
LGTM

**Comment by dan-rubinstein** [comment]
@elasticmachine merge upstream

**Review by davidkyle — APPROVED** [review]
LGTM

**Comment by dan-rubinstein** [comment]
@elasticmachine merge upstream

**Pull request merged**
