### PR TITLE
Parallel start node in test cluster

### PR DESCRIPTION
**Pull request by kimchy**
We can start the nodes in parallel when setting up a cluster predefined with specific set of nodes

### CODE REVIEW

**Comment by s1monw** [comment]
LGTM

**Comment by bleskes** [comment]
LGTM2

**Comment by s1monw** [comment]
actually thinking about this I am not sure if this is a good idea... it will make things even harder to reproduces and reason about we maybe should remove all the node starting concurrency instead?

**Comment by jpountz** [comment]
+1 on not starting concurrently if it may prevent failures from reproducing

**Comment by jpountz** [comment]
Should we close?

**Comment by clintongormley** [comment]
No further feedback. Closing

**Pull request closed without merging**
