### PR TITLE
Extract more standard metadata from binary files

### PR DESCRIPTION
**Pull request by dadoonet**
Until now, we have been extracted a few number of fields from the binary files sent to the ingest attachment plugin:

* `content`,
* `title`,
* `author`,
* `keywords`,
* `date`,
* `content_type`,
* `content_length`,
* `language`.

Tika has a list of more standard properties which can be extracted:

* `modified`,
* `format`,
* `identifier`,
* `contributor`,
* `coverage`,
* `modifier`,
* `creator_tool`,
* `publisher`,
* `relation`,
* `rights`,
* `source`,
* `type`,
* `description`,
* `print_date`,
* `metadata_date`,
* `latitude`,
* `longitude`,
* `altitude`,
* `rating`,
* `comments`

This commit exposes those new fields.

Related to #22339.

### CODE REVIEW

**Comment by dadoonet** [comment]
@masseyke Do you know what should I do to fix the test?

**Comment by masseyke** [comment]
@dadoonet sorry for the slow reply. I'm going to take a look at this today. But I think that the problem is that it is actually a breaking change for backwards compatibility so it might be tricky to fix.

**Comment by dadoonet** [comment]
So I could make this configurable? Like having a setting which activates the new feature?

**Comment by masseyke** [comment]
Yeah I think it'll have to be something like that. I believe I had looked previously, and we don't have access to the version of the calling server like we do in a lot of REST calls. That's the way we usually get around this kind of thing -- if the version of the caller is detected as 7.x, we return what 7.x expects to see.

**Comment by masseyke** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Review by masseyke — APPROVED** [review]
Looks good to me.

**Comment by dadoonet** [comment]
Thanks!

**Comment by dadoonet** [comment]
It has not been backported to 8.0 branch. Is there anything to do to trigger the backport action?

**Pull request merged**
