### PR TITLE
ESQL: Switch more tests from version checks

### PR DESCRIPTION
**Pull request by nik9000**
This switches another pile of ESQL's tests from checking the release version to checking for feature markers.

### CODE REVIEW

**Comment by ldematte** [comment]
Besides the error in the ml tests (which I'm trying to figure out, will need a bit of investigation), we are discussing with the team the usage of "real" (non-historical) features for test code (see also https://github.com/elastic/elasticsearch/pull/106296)

@nik9000 may I ask a bit of patience on this? I'll get back to you when we have figured out the best way to proceed.

**Comment by ldematte** [comment]
You should definitely use features, we have removed (almost) all version gates from the codebase; our goal is to eventually remove Version altogether, so we want to avoid introducing new usages. But I understand this breaks the build for you at the moment, so it might be an issue :/

**Comment by ldematte** [comment]
Hey @nik9000, the problem with CI/part-4 should be fixed now (the ml test project mixing testClusters and TestCluster). Can you update branch from main? (there might be a conflict on EsqlFeatures)

**Comment by nik9000** [comment]
@ldematte now that I've got the fixes that were in the VALUES PR merged this should work. I've merged main into it.

**Review by ldematte — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
