### PR TITLE
Only create MatrixStatsResults on final reduction

### LINKED ISSUE #37587: MatrixStatsAggregatorTests#testTwoFields fails if aggs are reduced
As part of https://github.com/elastic/elasticsearch/pull/36020, I accidentally stumbled onto a test bug. [`testTwoFields()`](https://github.com/elastic/elasticsearch/blob/master/modules/aggs-matrix-stats/src/test/java/org/elasticsearch/search/aggregations/matrix/stats/MatrixStatsAggregatorTests.java#L60) fails if it is changed to `searchAndReduce()` instead of `search()`.  The variance of the test's `MultiPassStats` object no longer matches the reduced matrix stats response.

It's not clear if this is because the mock `MultiPassStats` is doing something wrong, or if there's a bug when the matrix agg's reduction is buggy.  MatrixStats uses a per-shard object (`RunningStats`) which is eventually converted into the final response object (`MatrixStatsObject`), at which point the correlation is calculated.  It might be part of this process that is buggy, or perhaps how the stats objects are finalized after reduction.

### PR DESCRIPTION
**Pull request by polyfractal**
`MatrixStatsResults` is the "final" result object, and runs an additional computation in it's ctor to calculate covariance, etc.  This means it should only run on the final reduction instead of on every reduce.  But today each round of reductions will create a new `MatrixStatsResults` object and execute `compute()`, which I think is where the error in https://github.com/elastic/elasticsearch/issues/37587 is coming from.

I'm not 100% certain I understand how MatrixStats works, but based on the test failure and the suggested fix in this PR, I think that's what's going on.

As an aside, we should probably do some refactoring on MatrixStats, so that it doesn't need to pass around a null MatrixStatsResults to distinguish between "intermediate" and "final" status.

Closes https://github.com/elastic/elasticsearch/issues/37587

### CODE REVIEW

**Comment by polyfractal** [comment]
@elasticmachine run elasticsearch-ci/2
@elasticmachine run elasticsearch-ci/default-distro

**Comment by polyfractal** [comment]
@elasticmachine run elasticsearch-ci/2

**Review by colings86 — APPROVED** [review]
I agree that we should refactor this so it doesn't rely on the null results value to differentiate between intermediate and final results especially as null results is also used to indicate an empty result too

**Review by nknize — APPROVED** [review]
:+1:  LGTM

**Comment by polyfractal** [comment]
@elasticmachine run elasticsearch-ci/default-distro

**Comment by polyfractal** [comment]
@elasticmachine test elasticsearch-ci/2

**Comment by polyfractal** [comment]
@elasticmachine run elasticsearch-ci/2

**Pull request merged**
