### PR TITLE
Deprecation check for indices with multiple types

### PR DESCRIPTION
**Pull request by AthenaEryma**
Multiple types can only show up in indices from the 5.x series, but they
can't be reindexed quite as easily as indices from 5.x that only have
one mapping type. Therefore, we want to present a separate message about
indices with multiple mapping types.

Relates to https://github.com/elastic/elasticsearch/issues/36024 and https://github.com/elastic/elasticsearch/issues/35190

/cc @joshdover

### CODE REVIEW

**Comment by jtibshirani** [comment]
Thanks @gwbrown! This seems very helpful.

I think that if the index metadata contains more than one mapping type, there are actually two possibilities:
- There is more than one mapping type for documents, for example `tweets` and `users`. The current deprecation check provides information about this case.
- There is one mapping type for documents, but the user has also defined the `_default_` mapping type. This default mapping type is deprecated in 6.x, and can no longer be used when creating a 7.x index.

It might make sense to call out these two cases separately for clarity, and also because the second one tends to be easier to resolve (the `_default_` mappings can just be folded into the singleton mapping definition).

**Comment by gwbrown** [comment]
@jtibshirani I've updated the check to cover that case - it looks from my testing like if there are two mappings, and one of them is `_default_`, the index can just be reindexed as normal, so I left that case as the standard "This needs to be reindexed" message, but if there are at least two "real" (non-`_default_`) mappings, then the new message calling out multiple types will be returned.  Does that sound right?

**Comment by jtibshirani** [comment]
The check for multiple document types looks good to me. I'm not totally up-to-date on how our migration assistant works , but if a `_default_` mapping is present I don't think that reindex can proceed exactly as normal. In particular, the `_default_` mapping can't be set on 7.0 indices, so users should make sure to fold all mapping items from `_default_` into their single document mapping.

**Comment by gwbrown** [comment]
@joshdover That's also a good point - I'll take a look at things that aren't allowed in indices created in 6.0, but are allowed in 6.0 for indices created in 5.x and see if there's anything else we're missing that should block the reindex assistant.

**Comment by jtibshirani** [comment]
Regarding my comment https://github.com/elastic/elasticsearch/pull/36952#issuecomment-450753360, @gwbrown pointed out that the reindex helper will automatically copy mappings from the old index to the new one. Because the mapping items from `_default_` get copied to the concrete mapping type when that type is created, the reindex helper could simply drop the `_default_` type automatically, and copy over the main document mappings without any user action required. I defer to you all on whether it's okay to do this all automatically, and whether it'd be good to issue a note about it.

**Review by jtibshirani — APPROVED** [review]
👍 for the changes relating to multiple document mapping types.

**Pull request merged**
