### PR TITLE
Updated grok patterns to include `Jän` as in german formatting

### PR DESCRIPTION
**Pull request by philippkahr**
The month grok pattern already catches the german months, but `Jän` for `Jänner` as in `MMM` notation was missing.

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by cbuescher** [comment]
> The month grok pattern already catches the german months, but Jän for Jänner as in MMM notation was missing.

Out of curiosity: is this something common in e.g Austria or Switzerland? I think I have never seen it in contemporary texts in other german-speaking countries? 
Do any of the Java language locales output this short for (Jän) for the MMM format? In that case maybe we should add it, if not I'm on the fence because it doesn't sound very common to me. Also I'm starting to wonder how many languages and variants the grok pattern is supposed to support in the long run. Currently English and German mostly seem to be covered, while other European languages are not. I think its unfeasible to solve all kinds of languages and cariants here on the long run, but I also don't know if any other language support is offered or planned here.

**Comment by danhermann** [comment]
> > The month grok pattern already catches the german months, but Jän for Jänner as in MMM notation was missing.
> 
> Out of curiosity: is this something common in e.g Austria or Switzerland? I think I have never seen it in contemporary texts in other german-speaking countries?
> Do any of the Java language locales output this short for (Jän) for the MMM format? In that case maybe we should add it, if not I'm on the fence because it doesn't sound very common to me. Also I'm starting to wonder how many languages and variants the grok pattern is supposed to support in the long run. Currently English and German mostly seem to be covered, while other European languages are not. I think its unfeasible to solve all kinds of languages and cariants here on the long run, but I also don't know if any other language support is offered or planned here.

@cbuescher, thanks for commenting on this. I agree that while the grok month patterns appear to ([mostly](https://github.com/elastic/elasticsearch/issues/51579)) support both English and German (note, though, that the grok patterns support only English for other fields such as day of week), it isn't feasible to use them broadly for supporting multiple languages. Perhaps a [custom pattern](https://www.elastic.co/guide/en/elasticsearch/reference/current/grok-processor.html#custom-patterns) better suits this use case?

**Comment by danhermann** [comment]
cc: @jethr0null in case you have a perspective on this.

**Comment by danhermann** [comment]
Thanks, @philippkahr. We'll look into removing the German language elements from the patterns for 8.0 as you suggest as that would help to show that supporting multiple languages needs to be done with separate patterns.

**Pull request closed without merging**
