### PR TITLE
NETWORKING: http.publish_host Should Contain CNAME

### LINKED ISSUE #22029: Should http.publish_host resolve the CNAME configured.
`http.publish_host` is resolved while starting the node but I'm not entirely sure this makes sense.

This setting is a great way to advertise CNAME to http clients that might not be resolvable on the network the nodes themselves live on or the firewall they are behind.

```yaml
http.publish_host: elastic.co
```

#### GET /_nodes/http?pretty=true

```json
{
  "_nodes" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "cluster_name" : "testtesttest",
  "nodes" : {
    "PTUZtqXjSY-mjPiQPWGXPg" : {
      "name" : "PTUZtqX",
      "transport_address" : "10.2.42.55:9300",
      "host" : "10.2.42.55",
      "ip" : "10.2.42.55",
      "version" : "5.0.0",
      "build_hash" : "253032b",
      "roles" : [
        "master",
        "data",
        "ingest"
      ],
      "http" : {
        "bound_address" : [
          "127.0.0.1:9200",
          "[::1]:9200",
          "10.2.42.55:9200"
        ],
        "publish_address" : "35.160.254.14:9200",
        "max_content_length_in_bytes" : 104857600
      }
    }
  }
}
```

It also advertises the resolved IP and not the CNAME which might not play well with DNS caching, the lazy transport resolving coming in 5.1 as per #21630 does not seem to extend to these settings.

### PR DESCRIPTION
**Pull request by original-brownbear**
* Restores old 2.x behaviour of prepending the hostname to  `http.publish_host` if available
* closes #22029

### CODE REVIEW

**Review by jasontedor — DISMISSED** [review]
After discussion with @elastic/es-clients we need to take a more careful approach here as this change will break some of the official language clients. Instead, we should:

 - in 6.x we will retain the current behavior of not including the hostname in the publish address
 - however, we will deprecation warn if the publish address would include the hostname with the behavior that we are proposing in elastic/elasticsearch#32806
 - in 6.x we will introduce a system property that will enable users that want the hostname in the publish address to do so by using this system property; this system property can only be set to `true` and not to `false` as the system property is unneeded if the user wants to retain the current behavior
 - in 7.0.0 we will change the behavior to include the hostname in the publish address (if available)
 - in 7.x we can deprecation warn that the system property no longer has any impact

**Comment by original-brownbear** [comment]
@jasontedor sounds good :) => on it :)

**Review by Tim-Brooks — COMMENTED** [review]
I'm not super familiar with the behavior we are looking for here. But this looks alright to me in regards to the API response / deprecation.

However, it is trivial to make it have some weird behavior in regards to IPv6.

```
public void testCorrectDisplayPublishedIpv6() throws Exception {
        InetAddress localhost = InetAddress.getByName(NetworkAddress.format(InetAddress.getByName("0:0:0:0:0:0:0:1")));
        int port = 9200;
        assertPublishAddress(
            new HttpInfo(
                new BoundTransportAddress(
                    new TransportAddress[]{new TransportAddress(localhost, port)},
                    new TransportAddress(localhost, port)
                ), 0L, true
            ), NetworkAddress.format(localhost) + ':' + port
        );
    }
```

`org.junit.ComparisonFailure: expected:<[::1]:9200> but was:<[0:0:0:0:0:0:0:1/[::1]]:9200>`

Are we okay that IPv6 address will be in the host string section if the comparison fails due to address compression?

@jasontedor 

I don't see an easy fix for that. We could always add like a new field for v7.0. But that introduces some backwards compatibility work.

**Comment by original-brownbear** [comment]
@tbrooks8 fixed the test case you pointed out now :) We already had a utility method (probably copied from Guava) that can identify whether or not a String is a valid IP (4 and 6) => just used that => works fine :)

**Review by Tim-Brooks — APPROVED** [review]
LGTM

**Comment by original-brownbear** [comment]
@tbrooks8 thanks!

**Pull request merged**
