### PR TITLE
Add deprecation info check for monitoring exporter password

### PR DESCRIPTION
**Pull request by danhermann**
The `AUTH_PASSWORD` setting for monitoring exporters was deprecated in https://github.com/elastic/elasticsearch/pull/50919 but never added to the deprecation info API. This PR needs to be merged directly to 7.x as the setting has already been removed from the `master` branch.

### CODE REVIEW

**Comment by danhermann** [comment]
@elasticmachine update branch

**Review by dakrone — APPROVED** [review]
LGTM, thanks for adding this Dan!

**Comment by danhermann** [comment]
@elasticmachine update branch

**Comment by danhermann** [comment]
Superseded by https://github.com/elastic/elasticsearch/pull/74156

**Pull request closed without merging**
