### PR TITLE
Allow the query cache to be disabled.

### LINKED ISSUE #15802: Allow Filter Cache to be disabled by index
For most users, having the filter cache being specified across the nodes makes a ton of sense, particularly for hot/cold architectures.

However, at extreme scales, this is sometimes not enough unless you go the extra mile with your cluster to setup a hot/warm/cold (ad nauseam) setup to allow an extra tier(s) of nodes to setup. For a lot of use cases, this extra level of node management adds a lot of complexity that only grows with the size of the cluster.

With that in mind, it would be useful to restrict (on/off only) the memory caches that get used by any index. This would enable curation to disable caches for any given index as it ages, thereby reducing its overall burden as a step before closing them.

### PR DESCRIPTION
**Pull request by jpountz**
This feature already existed but was neither tested nor documented.

Closes #15802

### CODE REVIEW

**Comment by nik9000** [comment]
LGTM

**Comment by rjernst** [comment]
Is having a custom query cache really something we should be promoting? It seems like allowing to disable it is one thing, and should be done with a boolean.

**Comment by jpountz** [comment]
I enabled it the way it was already implemented but I agree we probably want to keep things more contained.

**Comment by jpountz** [comment]
Thanks @rjernst for the suggestion. I replaced the setting with a flag and removed the ability to configure custom query caches.

**Comment by rjernst** [comment]
This LGTM as is. I have 2 thoughts for the future:
* Now that "none" is gone as far as the user is concerned, I wonder if we could rename the impl to a name that makes sense. Perhaps DisabledQueryCache?
* It would be nice if we removed the force method and used a package private member that tests could override, like we do with other test only overrides.

**Comment by jpountz** [comment]
> DisabledQueryCache

I like the name better too so I will rename before merging.

Thanks!

**Pull request merged**
