### PR TITLE
Use default hash setting helper in ApiKeyService

### PR DESCRIPTION
**Pull request by n1v0lg**
Small refactor to re-use the default stored hash setting helper. 

Missed this in #86146.

### CODE REVIEW

**Review by ywangd — APPROVED** [review]
LGTM

**Comment by n1v0lg** [comment]
@elasticmachine update branch

**Comment by n1v0lg** [comment]
@elasticmachine update branch

**Comment by n1v0lg** [comment]
@elasticmachine run elasticsearch-ci/part-1-fips

**Pull request merged**
