### PR TITLE
[Security Solution] Add kibana system permissions for Endpoint action indices (#81953)

### PR DESCRIPTION
**Pull request by ywangd**
* [Security Solution] Add kibana system permissions for Endpoint action indices

backport: #81953

### CODE REVIEW

**Comment by ywangd** [comment]
BWC failure is unrelated and has an issue https://github.com/elastic/elasticsearch/issues/82014 already.

**Comment by ywangd** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by ywangd** [comment]
@elasticmachine run elasticsearch-ci/rest-compatibility

**Comment by ywangd** [comment]
@elasticmachine update branch

**Comment by kevinlog** [comment]
@elasticmachine update branch

**Comment by ywangd** [comment]
@elasticmachine update branch

**Pull request merged**
