### PR TITLE
Add YAML min version setting for transport handshake

### PR DESCRIPTION
**Pull request by justincr-elastic**
For remote clustering, 8.x clusters can pair up with 7.17 clusters. The minimum accepted version is hard-coded.

If a cluster admin wants to raise the minimum accepted version, this PR allows adding a YAML setting to override the hard-coded 7.17 minimum. For example, raise the minimum to 8.4.0.

This setting will not allow lowering the minimum version below 7.17.

### CODE REVIEW

**Comment by justincr-elastic** [comment]
@tbrooks8 can you recommend where to put test coverage? There are a lot of cluster test classes, so I am wondering if you can narrow down the list.

**Comment by gwbrown** [comment]
I don't think we need this under the assumption we're targeting a new port for RCS 2.0, or am I mistaken?

**Comment by justincr-elastic** [comment]
I think you are correct, this is not needed if using new RCS 2.0 port. However, is it needed if using a single port with API Keys?

**Comment by justincr-elastic** [comment]
@elasticmachine update branch

**Comment by justincr-elastic** [comment]
I removed the max version setting, and I updated the title and description.

**Pull request closed without merging**
