### PR TITLE
[DOCS] Correct typo in ICU Analysis plugin desc

### PR DESCRIPTION
**Pull request by jrodewig**

### CODE REVIEW

**Review by cbuescher — APPROVED** [review]
LGTM

**Comment by jrodewig** [comment]
@elasticmachine run elasticsearch-ci/default-distro 

@elasticmachine run elasticsearch-ci/bwc

**Comment by jrodewig** [comment]
@elasticmachine update branch

**Comment by jrodewig** [comment]
@elasticmachine run elasticsearch-ci/default-distro

**Comment by jrodewig** [comment]
@elasticmachine update branch

**Pull request merged**
