### PR TITLE
Add enrich source field mapper.

### PR DESCRIPTION
**Pull request by martijnvg**
The enrich source field mapper stores the source of a document as
binary doc values. This is useful in cases where retrieval speeds
are more important than compact storage (which is what SourceFieldMapper does),
which is the case for the enrich processor.

Prior to this change enrich processor was using _source stored field
to fetch the enrich document to enrich document being ingested.

The enrich policy runner, when creating the enrich index, disables
_source meta field and enables the _enrich_source meta field.

The enrich source field mapper is an internal field, which is only
meant to be used by the enrich feature.

Relates to #41521 and #32789

### CODE REVIEW

**Comment by martijnvg** [comment]
Running benchmark using this [track](https://github.com/martijnvg/enrich-rally-tracks/blob/master/track.json) with this new meta field type already shows good performance improvements:

```
|                                                Min Throughput | insert-messages-with-enrich-pipeline |    11260.4 |       19572 |  8311.57 | docs/s |
|                                             Median Throughput | insert-messages-with-enrich-pipeline |    15292.7 |       23454 |  8161.33 | docs/s |
|                                                Max Throughput | insert-messages-with-enrich-pipeline |    16502.6 |     24143.1 |  7640.51 | docs/s |
|                                       50th percentile latency | insert-messages-with-enrich-pipeline |    553.256 |      356.66 | -196.596 |     ms |
|                                       90th percentile latency | insert-messages-with-enrich-pipeline |    687.964 |     567.713 |  -120.25 |     ms |
|                                      100th percentile latency | insert-messages-with-enrich-pipeline |    814.368 |     763.496 | -50.8725 |     ms |
|                                  50th percentile service time | insert-messages-with-enrich-pipeline |    553.256 |      356.66 | -196.596 |     ms |
|                                  90th percentile service time | insert-messages-with-enrich-pipeline |    687.964 |     567.713 |  -120.25 |     ms |
|                                 100th percentile service time | insert-messages-with-enrich-pipeline |    814.368 |     763.496 | -50.8725 |     ms |
|                                                    error rate | insert-messages-with-enrich-pipeline |          0 |           0 |        0 |      % |
```

**Review by jpountz — COMMENTED** [review]
It looks good. Something I'm wondering is if we can prevent users from using this field on their regular indices?

**Comment by martijnvg** [comment]
Thanks for reviewing @jpountz!

> Something I'm wondering is if we can prevent users from using this field on their regular indices?

Perhaps  enforcing that the index name should start with `.enrich-` is enough? All enrich indices will have this prefix (EnrichPolicy#ENRICH_INDEX_NAME_BASE).

**Comment by jpountz** [comment]
:+1:

**Comment by martijnvg** [comment]
This change is no longer relevant.

**Pull request closed without merging**
