### PR TITLE
Add YAML REST tests for percentile_ranks metric aggregation

### PR DESCRIPTION
**Pull request by polyfractal**
More YAML REST tests for aggregations.  Pretty straightforward :)

Related to #26220

### CODE REVIEW

**Review by tlrx — APPROVED** [review]

**Comment by polyfractal** [comment]
retest this please

**Comment by cbuescher** [comment]
@elasticmachine test this please

**Comment by polyfractal** [comment]
Yes, I agree... these exact-value tests are super flaky and easy to break.

I'll see if I can pare these tests down to something that uses the agg's DSL without checking the actual values.  Although I suspect there won't be a lot to actually test since the parameters directly affect the values and nothing else.

**Comment by colings86** [comment]
I wonder if instead of check for an exact value we could instead check it is within an expected error of the accurate value given the data set is small? e.g. we could check in these tests that it is within 2% of the actual value

**Comment by polyfractal** [comment]
Yep, that'd work.  I thought about it at the time, but the yaml tests don't have an easy way to do it... you have to do use two checks (`gte` + `lte`) for each value, and I was feeling lazy :P

Perhaps just spot check a few values with the gte/lte pairs?

**Comment by colings86** [comment]
> Perhaps just spot check a few values with the gte/lte pairs?

👍

**Comment by polyfractal** [comment]
Closing for now, almost certainly needs updating and don't have time at the moment.

**Pull request closed without merging**
