### PR TITLE
Remove item listed in 6.3 notes that's not in 6.3

### PR DESCRIPTION
**Pull request by malept**
﻿#26659 was closed, not merged. (The followup PR (#28993) didn't make it.)

### CODE REVIEW

**Comment by jasontedor** [comment]
Thanks @malept. Can you sign the CLA?

**Comment by jasontedor** [comment]
@malept I know it's a pain and I am sorry for that, and I know it seems unnecessary for a small change or even a line removal, but it's what the legal people ask us to do.

**Comment by malept** [comment]
Signed.

**Review by colings86 — APPROVED** [review]
@malept thanks for catching this one. LGTM

**Pull request merged**
