### PR TITLE
Use weekyear for consistency

### PR DESCRIPTION
**Pull request by russcam**
Relates: #60044 and https://github.com/elastic/elasticsearch/pull/59555#pullrequestreview-461250791

With the removal of camel case format names,
the format name for `WEEK_YEAR` has been set
to `"week_year"`, but this is inconsistent with the usage
in other formats related to weekyear e.g.

```
WEEKYEAR_WEEK("weekyear_week"),
WEEKYEAR_WEEK_DAY("weekyear_week_day"),
```

This PR

- replaces the snakecase format `"week_year"` with `"weekyear"`
- renames enum constants from `WEEK_YEAR` to `WEEKYEAR` for consistency
  with other constants related to weekyear.

I can open another PR to address the deprecation change in 7.x/7.9 related to #59555

### CODE REVIEW

**Review by Mpdreamz — APPROVED** [review]
LGTM but would love @pgomulka to confirm.

**Comment by rjernst** [comment]
This looks fine, but we should first have a PR to add the deprecation. It should go through the master branch first, and be backported, then this change can apply to master only.

**Review by pgomulka — CHANGES_REQUESTED** [review]
it looks good to me, but I wonder if we should add a WEEKYEAR in 7.x, deprecate WEEK_YEAR in 7.x and remove WEEK_YEAR in master? 
https://github.com/elastic/elasticsearch/pull/60855#pullrequestreview-468232621

**Comment by pgomulka** [comment]
closing in favour of https://github.com/elastic/elasticsearch/pull/63384

**Pull request closed without merging**
