### PR TITLE
Allow token-count type to calculate sum of integer strings

### PR DESCRIPTION
**Pull request by houcheng**
We need this feature for adding customized dictionary information on fields. We are developing project related to Chinese text analysis, and the Chinese text's analysis accuracy is highly depends on content of dictionary, and it is everyday updated, and documents needed re-index periodically.

With dictionary information in field as a integer, we can apply our re-index stragey on per document basics.

### CODE REVIEW

**Comment by clintongormley** [comment]
Hi @houcheng 

Could you provide some more details about the actual change that is being made in the pull request description please?

**Comment by houcheng** [comment]
Hi @clintongormley,

This commit modifies the parsing function, parseCreateField(), of token count mapper. The original function only counts number of tokens from analyzer and store result as integer field. This commit adds a "is_number" option, and if it is enabled, the parsing function would call countSum() function instead to calculate the integer sum of all tokens.

Thanks.

**Comment by clintongormley** [comment]
Similar to https://github.com/elastic/elasticsearch/issues/5417 then?  ie if a field has a value `["one two three", "one two"], today the `token_count` would index `[3,2]`, and with your changes would index `5` instead?

Why the parameter `is_a_number`?  That doesn't really explain what it does I think.  Perhaps `sum_counts: true` instead?

**Comment by houcheng** [comment]
Hi, it parse the integer number string from analyzer. For example, if the field has value [ "1 2 3", "4 5"], the token_count would store it as [6, 9] instead.

The `is_a_number` represents that the tokens from analyzer token streams are all number string.

**Comment by clintongormley** [comment]
OK - thanks for the background.  This behaviour doesn't seem to have anything to do with the intended purpose of the `token_count` field type, and it doesn't seem like a generally useful feature. I'd suggest creating your own Elasticsearch plugin that does what you need instead.

**Comment by houcheng** [comment]
Hi, we already had a plugin to update the dictionary date information. However, the elasticsearch does not support analyzer on integer field. Our plugin's generated result can only stored in text type, and it is not handy. We can not do aggregate or range search on the dictionary tag. Is there any suggestion ? Thanks.

**Comment by clintongormley** [comment]
Can't you create your own field type in the same way as we did with token count?

**Comment by houcheng** [comment]
Yes, we can create another token type, token-sum, for calculating token content's integer sum.
Thanks a lot.

**Pull request closed without merging**
