### PR TITLE
Remove Preconditions class

### PR DESCRIPTION
**Pull request by kimchy**
We don't need our own anymore, since we removed the Elasticsearch illegal argument exception

### CODE REVIEW

**Comment by javanna** [comment]
LGTM

**Comment by s1monw** [comment]
can we use `Objects.requireNonNull(T obj, String message)` instead?

**Comment by kimchy** [comment]
@s1monw I first wanted to remove the Preconditions class first that we don't need anymore

**Comment by s1monw** [comment]
ok not sure if it's worth 2 PRs ?

**Comment by kimchy** [comment]
its a bigger change, since there are other places that use guava preconditions checkNonNull, also, we can't replace most of the ones here, which are for illegal argument

**Comment by s1monw** [comment]
ok fair enough!

**Pull request merged**
