### PR TITLE
Fix 60_enrich/Enrich on keyword (fixes 106507)

### LINKED ISSUE #106507: EsqlClientYamlIT » test {p0=esql/60_enrich/Enrich on keyword}
### CI Link

https://gradle-enterprise.elastic.co/s/doqh4cuavfy7s/console-log?page=3#L2471

### Repro line

./gradlew ':x-pack:plugin:esql:qa:server:mixed-cluster:v8.12.3#yamlRestTest' -Dtests.class="org.elasticsearch.xpack.esql.qa.mixed.EsqlClientYamlIT" -Dtests.method="test {p0=esql/60_enrich/Enrich on keyword}" -Dtests.seed=19C4FD8ABFD05226 -Dtests.bwc=true -Dtests.locale=lv -Dtests.timezone=America/Indiana/Knox -Druntime.java=21

### Does it reproduce?

Yes

### Applicable branches

main

### Failure history

_No response_

### Failure excerpt

```java.lang.AssertionError: Failure at [esql/60_enrich:95]: expected [2xx] status code but api [esql.query] returned [500 Internal Server Error] [{"error":{"root_cause":[{"type":"unsupported_operation_exception","reason":"unsupported_operation_exception: can't load _source as part of enrich",```

### PR DESCRIPTION
**Pull request by craigtaverner**
This test used to work, but now is failing in BWC against 8.12.3. It appears the difference that caused the problem is that the query now returns a field that used to be a keyword, but is now a text field, provided by the enrich lookup. So even though the enrich is still based on a keyword, this query now accesses code paths it did not before, and those have issues before 8.13.0 related to reading text from source.

Fixes #106507

### CODE REVIEW

**Comment by nik9000** [comment]
I believe it's already muted with https://github.com/elastic/elasticsearch/commit/d362517769da0c55df0a36b36733aabfc18a459c - though twice couldn't hurt.

**Comment by craigtaverner** [comment]
> I believe it's already muted with [d362517](https://github.com/elastic/elasticsearch/commit/d362517769da0c55df0a36b36733aabfc18a459c) - though twice couldn't hurt.

I saw that later, but like that my mute is version specific since it only seems to be failing in BWC against 8.12.3, not newer versions. I left a message for Ryan to consider using my mute if he sees fit.

**Review by costin — APPROVED** [review]
👍

**Review by nik9000 — APPROVED** [review]
We are trying to remove these version checks for the yaml. Is there a feature could use for this one? If not, I'll add one at some point when I convert the csv tests and hopefully we can convert this one too.

**Comment by craigtaverner** [comment]
> We are trying to remove these version checks for the yaml. Is there a feature could use for this one? If not, I'll add one at some point when I convert the csv tests and hopefully we can convert this one too.

I'll look around, and if I find one I'll make another PR for that.

**Pull request merged**
