### PR TITLE
make java.version mandatory for jvm plugins

### PR DESCRIPTION
**Pull request by rmuir**
JarHell has a low level check, but its more of a best effort one,
only checking if X-Compile-Target-JDK is set in the manifest. This
is the case for all lucene- and elasticsearch- generated jars, but
lets just be explicit for plugins.

I also reorganized the descriptor file a bit and added a site plugin example.

### CODE REVIEW

**Comment by rmuir** [comment]
cc @clintongormley can you review the docs added in this PR? https://github.com/rmuir/elasticsearch/blob/plugin_java_version/dev-tools/src/main/resources/plugin-metadata/plugin-descriptor.properties

**Comment by clintongormley** [comment]
@rmuir docs look good to me.  perhaps just add a note that `elasticsearch.version` can also be specified for site plugins, as they have dependencies on the APIs in a particular version?

**Comment by rmuir** [comment]
> @rmuir docs look good to me. perhaps just add a note that elasticsearch.version can also be specified for site plugins, as they have dependencies on the APIs in a particular version?

But currently this property is only functional for jvm plugins. If we want to make it optional for site plugins then we need to implement that.

**Comment by jasontedor** [comment]
@rmuir I left a minor comment, otherwise it LGTM.

**Pull request merged**
