### PR TITLE
[DOCS] Fix typo

### PR DESCRIPTION
**Pull request by andreidan**

### CODE REVIEW

**Review by jrodewig — APPROVED** [review]

**Review by tylerperk — CHANGES_REQUESTED** [review]
The review seems to only let me comment on lines in this section, which are fine. On line 199 "We've now make sure" should be "We've now made sure". At line 355 it feels like there should be a heading or something to segue into switching it back to ILM. Line 362, 'configured' should be 'configuring'.

**Comment by andreidan** [comment]
@elasticmachine update branch

**Comment by andreidan** [comment]
@tylerperk thanks for the review. I've changed the typos you mentioned. I'll open a separate PR regarding the headings. Thanks

**Comment by andreidan** [comment]
@tylerperk Opened https://github.com/elastic/elasticsearch/pull/102068 for the headings and a `TL;DR`

**Pull request merged**
