### PR TITLE
Serialize Monitoring Bulk Request Compressed

### PR DESCRIPTION
**Pull request by original-brownbear**
Even with changes from #48854 we're still seeing significant (as in tens and hundreds of MB)
buffer usage for bulk exports in some cases which destabilizes master nodes.
Since we need to know the serialized length of the bulk body we can't do the serialization
in a streaming manner. (also it's not easily doable with the HTTP client API we're using anyway).
=> let's at least serialize on heap in compressed form and decompress as we're streaming to the
HTTP connection. For small requests this adds negligible overhead but for large requests this reduces
the size of the payload field by about an order of magnitude (empirically determined) which is a massive
reduction in size when considering O(100MB) bulk requests.

### CODE REVIEW

**Comment by jakelandis** [comment]
@original-brownbear the changes here look fine technically, however, I wonder about the practicality. Despite bulk and flush separated by methods, it actually does [very little](https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/monitoring/src/main/java/org/elasticsearch/xpack/monitoring/exporter/Exporters.java#L236-L240) between these two methods. This particular workflow does not buffer bulk payloads and flush based on time or size (like other parts of the code base). So here we will compress only to de-compress a few milliseconds later. 

I agree the goal with the reduce the memory usage of the bulk exporters on master, but I am not sure if this buys us much without the ability to send the compressed bits. I wonder if gzip compression the payload for use with the http entity such that we don't need to decompress prior to calling out is feasible ?

**Comment by original-brownbear** [comment]
>  So here we will compress only to de-compress a few milliseconds later.

That still saves us a boatload of memory. We're not decompressing to buffers but decompressing to a stream that is then consumed step by step by the HTTP client. So at no point will we need the full bulk request on heap uncompressed and peak memory use is way reduced isn't it?

**Review by jakelandis — APPROVED** [review]
LGTM - I trust your assessment of the practicality, and no issues with the implementation.

**Comment by original-brownbear** [comment]
Thanks Jake!

**Pull request merged**
