### PR TITLE
Move ccr info/usage actions into ccr module

### PR DESCRIPTION
**Pull request by rjernst**
The ccr info and usage actions provide information through the xpack
usage nad info apis. The implemenation classes should be in each
individual module, yet for ccr they exist in xpack core, splitting the
ccr package. This commit moves the classes into the ccr module to fix
the split package.

### CODE REVIEW

**Comment by rjernst** [comment]
@elasticmachine run elasticsearch-ci/part-2

**Review by henningandersen — APPROVED** [review]
LGTM. I wonder about the 7.x backport though since it looks so different?

**Comment by rjernst** [comment]
> I wonder about the 7.x backport

It should still work in 7.x, just needs a different change. I'll backport it manually.

**Comment by rjernst** [comment]
Oh good news, the backport isn't even needed. In 7.x the info/usage classes are not in the same location, and there is no split package.

**Pull request merged**
