### PR TITLE
Parameterized exception messages

### PR DESCRIPTION
**Pull request by uboness**
Added dynamic arguments to `ElasticsearchException`, `ElasticsearchParseException` and `ElasticsearchTimeoutException`.

This helps keeping the exception messages clean and readable and promotes consistency around wrapping dynamic args with `[` and `]`.

This is just the start, we need to propagate this to all exceptions deriving from `ElasticsearchException`. Also, work started on standardizing on lower case logging & exception messages. We need to be consistent here...
- Uses the same `LoggerMessageFormat` as used by our logging infrastructure.

### CODE REVIEW

**Comment by s1monw** [comment]
LGTM thanks for doing this

**Comment by nik9000** [comment]
Neat idea reusing the logging message formatter for exceptions. Nice for consistency. I see a lot of ```[{}]``` in there. Maybe make something convenient for that? Something along the lines of ```[]``` being interpreted like ```[{}]```.

**Comment by uboness** [comment]
>  I see a lot of [{}] in there. Maybe make something convenient for that? Something along the lines of [] being interpreted like [{}].

now that's a neat idea as well :) I'll get this one in first and take it from there

**Comment by nik9000** [comment]
> now that's a neat idea as well :) I'll get this one in first and take it from there

Cool!

**Pull request merged**
