### PR TITLE
[Inference API] Use randomOtherValueThan to avoid potential flaky ModelSecretsTests

### PR DESCRIPTION
**Pull request by timgrein**
Same reasoning as in https://github.com/elastic/elasticsearch/pull/108605. There's a small chance that two calls to `createRandomInstance` return the same result. Guarding against this case with `randomValueOtherThan`.

### CODE REVIEW

**Comment by timgrein** [comment]
@elasticmachine update branch

**Review by davidkyle — APPROVED** [review]
LGTM

**Comment by timgrein** [comment]
@elasticmachine update branch

**Comment by timgrein** [comment]
@elasticmachine update branch

**Pull request merged**
