### PR TITLE
Remove unused ClusterService dependency from SearchPhaseController

### PR DESCRIPTION
**Pull request by javanna**
The dependency was carried all the way to InternalAggregation but it was never used.

### CODE REVIEW

**Comment by javanna** [comment]
@jpountz can you check this out please?

**Comment by javanna** [comment]
@elasticmachine retest this please

**Comment by javanna** [comment]
@elasticmachine retest this please once again? <3

**Comment by javanna** [comment]
@elasticmachine retest this please sorry to bug you again

**Comment by javanna** [comment]
retest this please

**Comment by javanna** [comment]
retest this please

**Comment by javanna** [comment]
retest this please (I'm feeling lucky)

**Review by jpountz — APPROVED** [review]
LGTM

**Pull request merged**
