### PR TITLE
Enhance search_after documentation

### PR DESCRIPTION
**Pull request by patrykk21**
This solves the [issue](https://github.com/elastic/elasticsearch/issues/34232).

Let me know if the wording and placement is fine.

Thank you ~

### CODE REVIEW

**Comment by elasticcla** [comment]
Hi @patrykk21, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/elasticsearch/pull/36111.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by patrykk21** [comment]
Updated the email

**Comment by jasontedor** [comment]
@elasticmachine test this please

**Review by jimczi — APPROVED** [review]

**Comment by jimczi** [comment]
Thanks @patrykk21

**Pull request merged**
