### PR TITLE
Call real memory circuit breaker in BucketsAggregator#collectBucket instead of BucketsAggregator#collectExistingBucket

### PR DESCRIPTION
**Pull request by iverase**
We currently perform the following check in `BucketsAggregator#collectExistingBucket` to call the real memory circuit breaker:
```
if (docCounts.increment(bucketOrd, docCount) == docCount) {
```

This is only true when the current count in bucketOrd is 0, which means whenever we call `BucketsAggregator#collectBucket`. Therefore lets move the check to that method and remove the comparison here. This is a hot method so it might make some performance difference.

### CODE REVIEW

**Comment by iverase** [comment]
But there are places we always call `collectBucket` regarless if it was already created so. it will call the circuit breaker more often: 
https://github.com/elastic/elasticsearch/blob/ae2aacb66affa098f1e431a296a0dc4898ccd640/server/src/main/java/org/elasticsearch/search/aggregations/bucket/filter/FilterByFilterAggregator.java#L299

**Comment by iverase** [comment]
When calling `BucketsAggregator#collect=Bucket`, we will be executing the same code as we are executing now but when calling `BucketsAggregator#collectExistingBucket` we will execute a slightly faster path.

**Comment by iverase** [comment]
@elasticmachine update branch

**Review by not-napoleon — APPROVED** [review]
Seems reasonable to me.

**Pull request merged**
