### PR TITLE
Remove types from watcher docs

### PR DESCRIPTION
**Pull request by jakelandis**
Types have been deprecated and this commit removes the documentation
for specifying types in the index action, and search input/transform.

Relates #37594 #35190

### CODE REVIEW

**Comment by jtibshirani** [comment]
Thanks @jakelandis for these updates! I saw a couple remaining references to types in `ack-watch` and `transform/search`.

**Review by spinscale — APPROVED** [review]

**Review by spinscale — CHANGES_REQUESTED** [review]
There is one more use of doc_type in `get-watch.asciidoc` on top of what Julie said.. I didnt look in the `rest-api/` directory at first

**Comment by jakelandis** [comment]
@jtibshirani @spinscale thanks for the reviews.  I totally missed the `rest-api/watcher` docs and have now included them in https://github.com/elastic/elasticsearch/pull/38002/commits/5954cda74c66899f2d73e28a4a5815d690c7f6f4.  The reference in `transform/search` is for `search_type` as in `query_then_fetch`, so no changes there. 

Ready for re-review.

**Review by jtibshirani — APPROVED** [review]
For `transform/search`, it looks like document types are mentioned as well (on the lines mentioning `request.types` and `"types" : [ "event" ]`). Looks good to me to merge after that's updated!

**Comment by jakelandis** [comment]
@jtibshirani - I think the `transform/search` changes are already here: https://github.com/elastic/elasticsearch/pull/38002/files#diff-45a5436142c808451924eb4ed19469f0L58 ?

**Comment by jakelandis** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by jtibshirani** [comment]
Sorry @jakelandis, I was reviewing too speedily! Looks good to me.

**Review by spinscale — APPROVED** [review]

**Pull request merged**
