### PR TITLE
Change ingest packages

### PR DESCRIPTION
**Pull request by martijnvg**
In core merge `o.e.ingest.core` with `o.e.ingest`. The core package isn't needed.
In ingest-common added `o.e.ingest.common` module and moved all code to this package. To avoid unneeded bugs if package protected methods outside the module are used, which can't be caught by the compiler.

### CODE REVIEW

**Comment by rmuir** [comment]
I'm not sure you want to do this: I disagree with tons of packages, but I don't think packages should be shared across modules/plugins, especially across classloaders!

Things like package private access are not going to work as you think, there will be bugs not caught by the compiler and only discovered by REST tests and users.

**Comment by martijnvg** [comment]
@rmuir Good point. I didn't realise this.

I will change the PR to only drop the o.e.ingest.core package instead and revert the changes in the plugin modules.

**Comment by martijnvg** [comment]
Also I'll move all code in the ingest-common module to `o.e.ingest.common`. (right now it uses the `o.e.ingest` package)

**Comment by martijnvg** [comment]
I've changed the PR.

**Comment by talevy** [comment]
LGTM, needs rebase

**Pull request merged**
