### PR TITLE
ES|QL: shorten error messages for UnsupportedAttributes (#111973)

### PR DESCRIPTION
**Pull request by luigidellaquila**
Backport of #111973

### CODE REVIEW

**Review by nik9000 — APPROVED** [review]
LGTM. I hope you don't have any test failures on the feature, but I *think* it'll just work now.

**Comment by luigidellaquila** [comment]
@elasticmachine run elasticsearch-ci/part-2

**Comment by alex-spies** [comment]
@elasticmachine run elasticsearch-ci

**Comment by luigidellaquila** [comment]
CI failed again, BWC and packaging this time

**Comment by luigidellaquila** [comment]
@elasticmachine update branch

**Pull request merged**
