### PR TITLE
Update Groovy dependency to 2.4.0

### PR DESCRIPTION
**Pull request by dakrone**
Here are the changelogs:

http://groovy-lang.org/changelogs/changelog-2.3.3.html
http://groovy-lang.org/changelogs/changelog-2.3.4.html
http://groovy-lang.org/changelogs/changelog-2.3.5.html
http://groovy-lang.org/changelogs/changelog-2.3.6.html
http://groovy-lang.org/changelogs/changelog-2.3.7.html
http://groovy-lang.org/changelogs/changelog-2.3.8.html
http://groovy-lang.org/changelogs/changelog-2.3.9.html
http://groovy-lang.org/changelog-2.4.0.html

### CODE REVIEW

**Comment by dadoonet** [comment]
LGTM. Could you also push that change in elasticsearch parent project as well?

**Comment by jprante** [comment]
Why not use the indy jar?

http://groovy.codehaus.org/InvokeDynamic+support

**Comment by dakrone** [comment]
@jprante this already does, see the `<classifier>indy</classifier>` line under the version in the dependency

**Comment by jprante** [comment]
Cool, thanks, I somehow overlooked this...

**Pull request merged**
