### PR TITLE
Limit the max size of bulk and index thread pools to bounded number of processors

### LINKED ISSUE #15582: Don't allow `bulk` and `indexing` thread pools size larger than number of CPU cores
I've seen a couple cases recently where users "tuned" up the number of threads in the thread pools for indexing, and then didn't realize this leads to crazy issues like Lucene writing an insane number of segments and doing an insane number of merges, etc.

I don't see any reason to allow this value to exceed the number of CPU cores?

### PR DESCRIPTION
**Pull request by mikemccand**
I only limit `bulk` and `index` thread pools.

Closes #15582

### CODE REVIEW

**Comment by jpountz** [comment]
I'm also curious if there is a way to give feedback to users without breaking existing installations. Maybe @s1monw has a clue?

**Comment by s1monw** [comment]
@mikemccand to fix this the right way I agree we should be loud. I think we have to upgrade the settings in the clusterstate first and that can on work well if we do it only in a major version? On the other hand what if you have machines with 8 CPUs and others with 80 CPU? I mean this is really a per-node setting and I think we should maybe not allow to set this globally? I think you patch is good as a first step but we should really think about how to expose these settings?

**Comment by mikemccand** [comment]
I talked to @s1monw ... we decided to add a `logger.warn` here if you tried to set to a too-large value, but otherwise be silent for now, and to open a separate issue that this setting should not be global and dynamically updatable.

**Comment by mikemccand** [comment]
OK I pushed another commit w/ the feedback; I think it's ready.

**Comment by s1monw** [comment]
LGTM

**Comment by mikemccand** [comment]
Thanks @s1monw, I'll port to 2.2.0 as well.

**Pull request merged**
