### PR TITLE
SQL: [Test] Fix issues with timezone between JDKs

### PR DESCRIPTION
**Pull request by matriv**
What basically happens is that the server runs on a java version
where a certain timezone has a set of offset rules, while the test
itself runs on a java version where the same timezone has changed
offset rules (think about a country deciding to use utc+x instead
of utc+y).

With this change the timezone used in testGettingTimeWithoutCalendar
is randomly generated by creating a fixed offset timezone
(ie GMT+X or Z instead of Australia/West timezone) so that the offset
is always fixed, thus avoiding the described issue.

Similar fix to #51592

Fixes: #52650

### CODE REVIEW

**Review by costin — APPROVED** [review]
TZs - the gift that keeps on giving. I'm sure this one was not easy to reproduce.
Is this something that can be incorporated into `EsTestCase#randomZone` or potentially manipulate the value it returns?

**Comment by matriv** [comment]
This kind of tests seem to break only for 6.8 where java 8 is still used and probably some CI instance (client side) uses an older jdk with outdate TZ data. If we experience the issue in later versions, definitely worths introducing a method like that.

**Review by astefan — APPROVED** [review]
LGTM. Thank you for taking care of this issue. I kept postponing adding a fix to it for a too long time.

**Comment by matriv** [comment]
@astefan No worries, Thx for providing the solution in the 1st place!

**Pull request merged**
