### PR TITLE
Relax checks on mappings or settings updates

### LINKED ISSUE #68757: TokenBackwardsCompatibilityIT failures
TokenBackwardsCompatibilityIT » testGeneratingTokensInMixedCluster
TokenBackwardsCompatibilityIT » testRefreshingTokensInMixedCluster

**Build scan**: https://gradle-enterprise.elastic.co/s/7wjt3rnujlkae

**Applicable branches**: 7.x

**Failure history**:
Started once #68375 was backported to 7.x

**Failure excerpt**:

```

org.elasticsearch.upgrades.TokenBackwardsCompatibilityIT > testGeneratingTokensInMixedCluster FAILED |  
-- | --
  | org.elasticsearch.client.ResponseException: method [POST], host [http://[::1]:38011], URI [/_security/oauth2/token], status line [HTTP/1.1 500 Internal Server Error] |  
  | {"error":{"root_cause":[{"type":"illegal_state_exception","reason":"Cannot update mappings in [.security-tokens-7]: system indices can only use mappings from their descriptors, but the mappings in the request did not match those in the descriptors(s)"}],"type":"illegal_state_exception","reason":"Cannot update mappings in [.security-tokens-7]: system indices can only use mappings from their descriptors, but the mappings in the request did not match those in the descriptors(s)"},"status":500} |  
  | at __randomizedtesting.SeedInfo.seed([4392CA99489E4B54:BCDB25AF041027C4]:0) |  
  | at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:326) |  
  | at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296) |  
  | at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270) |  
  | at org.elasticsearch.upgrades.TokenBackwardsCompatibilityIT.createTokens(TokenBackwardsCompatibilityIT.java:397) |  
  | at org.elasticsearch.upgrades.TokenBackwardsCompatibilityIT.testGeneratingTokensInMixedCluster(TokenBackwardsCompatibilityIT.java:215) |  
  | REPRODUCE WITH: ./gradlew ':x-pack:qa:rolling-upgrade:v7.10.3#twoThirdsUpgradedTest' -Dtests.class="org.elasticsearch.upgrades.TokenBackwardsCompatibilityIT" -Dtests.method="testGeneratingTokensInMixedCluster" -Dtests.seed=4392CA99489E4B54 -Dtests.security.manager=true -Dtests.bwc=true -Dtests.locale=ja -Dtests.timezone=America/Creston -Druntime.java=8 |  
  |   |  
  | org.elasticsearch.upgrades.TokenBackwardsCompatibilityIT > testRefreshingTokensInMixedCluster FAILED |  
  | org.elasticsearch.client.ResponseException: method [POST], host [http://127.0.0.1:34445], URI [/_security/oauth2/token], status line [HTTP/1.1 500 Internal Server Error] |  
  | {"error":{"root_cause":[{"type":"illegal_state_exception","reason":"Cannot update mappings in [.security-tokens-7]: system indices can only use mappings from their descriptors, but the mappings in the request did not match those in the descriptors(s)"}],"type":"illegal_state_exception","reason":"Cannot update mappings in [.security-tokens-7]: system indices can only use mappings from their descriptors, but the mappings in the request did not match those in the descriptors(s)"},"status":500} |  
  | at __randomizedtesting.SeedInfo.seed([4392CA99489E4B54:A1F36B143CFB8E73]:0) |  
  | at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:326) |  
  | at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296) |  
  | at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270) |  
  | at org.elasticsearch.upgrades.TokenBackwardsCompatibilityIT.refreshToken(TokenBackwardsCompatibilityIT.java:429) |  
  | at org.elasticsearch.upgrades.TokenBackwardsCompatibilityIT.testRefreshingTokensInMixedCluster(TokenBackwardsCompatibilityIT.java:246) |  
  | REPRODUCE WITH: ./gradlew ':x-pack:qa:rolling-upgrade:v7.10.3#twoThirdsUpgradedTest' -Dtests.class="org.elasticsearch.upgrades.TokenBackwardsCompatibilityIT" -Dtests.method="testRefreshingTokensInMixedCluster" -Dtests.seed=4392CA99489E4B54 -Dtests.security.manager=true -Dtests.bwc=true -Dtests.locale=ja -Dtests.timezone=America/Creston -Druntime.java=8

```

### PR DESCRIPTION
**Pull request by pugnascotia**
Closes #68757.

The strict checks of overriding mappings or settings updates is causing
various BWC problems, so relax them to deprecation messages in 7.x

### CODE REVIEW

**Review by jaymode — APPROVED** [review]
LGTM

**Review by droberts195 — APPROVED** [review]
LGTM2

Thanks for fixing it quickly.

I think to get the BWC tests passing reliably for 7.x `TokenBackwardsCompatibilityIT.createTokens` and `TokenBackwardsCompatibilityIT.refreshToken` will need to tolerate (but not require) this deprecation warning.

**Comment by mark-vieira** [comment]
FYI, I'm seeing loads of other failures similarly referencing system indicies mappings. Are these all related? Will this PR address them as well?

https://gradle-enterprise.elastic.co/s/p4ra5r7hsjgbs/tests/:x-pack:qa:rolling-upgrade:v6.8.0%23upgradedClusterTest/org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT/test%20%7Bp0=upgraded_cluster%2F30_ml_jobs_crud%2FTest%20get%20old%20cluster%20job's%20timing%20stats%7D#1

https://gradle-enterprise.elastic.co/s/2oquggsiaqxgg/tests/:x-pack:qa:rolling-upgrade:v7.6.0%23twoThirdsUpgradedTest/org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT/test%20%7Bp0=mixed_cluster%2F120_api_key_auth%2FTest%20API%20key%20authentication%20will%20work%20in%20a%20mixed%20cluster%7D#1

**Comment by pugnascotia** [comment]
@mark-vieira yes, it ought to address those too.

**Pull request merged**
