### PR TITLE
Remove all setAccessible in tests and forbid

### PR DESCRIPTION
**Pull request by rmuir**
As a followup, I will upgrade lucene with a new snapshot when @uschindler has committed his patch on https://issues.apache.org/jira/browse/LUCENE-6795, and we can test the hunspell ignoreCase correctly.

I will also be working on junit4 and randomizedrunner so we can make progress on banning this with securitymanager (we will have to grant it to some test framework jars, but not tests themselves).

But lets get our own house in order first.

### CODE REVIEW

**Comment by uschindler** [comment]
I committed to Lucene.

**Comment by rmuir** [comment]
Thanks for the help here @uschindler !

**Comment by rjernst** [comment]
LGTM

**Comment by rmuir** [comment]
I just backported this to 2.x

**Pull request merged**
