### PR TITLE
MINOR: Some Cleanups in Snapshots

### PR DESCRIPTION
**Pull request by original-brownbear**
* Removed pre-v6 BwC logic + comments
* Removed some dead code

### CODE REVIEW

**Comment by original-brownbear** [comment]
Jenkins run gradle build tests 1

**Comment by original-brownbear** [comment]
Jenkins run gradle build tests 1

**Comment by original-brownbear** [comment]
Jenkins run gradle build tests 1

**Review by tlrx — APPROVED** [review]

**Comment by original-brownbear** [comment]
@tlrx thanks!

**Pull request merged**
