### PR TITLE
Upgrade icu4j for the ICU analysis plugin to 59.1

### LINKED ISSUE #21425: Upgrade ICU Plugin to latest available in Lucene
The ICU plugin currently uses ICU 54.1, while Lucene is on v56.1 and plans to upgrade to v58.1 (https://issues.apache.org/jira/browse/LUCENE-7540)

We should upgrade to the latest available in Lucene for 6.0.

Relates to https://github.com/elastic/elasticsearch/issues/21352

### PR DESCRIPTION
**Pull request by jimczi**
The Lucene library uses 59.1 so we should use the same.

Closes #21425

### CODE REVIEW

**Review by dadoonet — APPROVED** [review]
It looks good to me although I did not test it.
I wonder why it's marked as breaking. If confirmed may be it deserves some content in breaking change doc?

**Comment by jimczi** [comment]
> I wonder why it's marked as breaking.

There is an explanation in the docs:
https://github.com/elastic/elasticsearch/blob/master/docs/plugins/analysis-icu.asciidoc
````
While we restrict ICU upgrades to major versions, you may find that an index created in the previous major version will need to be reindexed in order to return correct (and correctly ordered) results, and to take advantage of new characters.
````

**Comment by dadoonet** [comment]
So we may be need to add to breaking changes that for icu users they need to reindex? Otherwise it will be transparent for them I think.

**Comment by jimczi** [comment]
Thanks @dadoonet 
I pushed https://github.com/elastic/elasticsearch/pull/25243/commits/6e4cefac0e95e3beb5b3325cd092388ef66b02e9

**Review by dadoonet — APPROVED** [review]
Awesome!

**Comment by jimczi** [comment]
Thanks @dadoonet !

**Pull request merged**
