### PR TITLE
[Doc] Add clarification to boosting query

### PR DESCRIPTION
**Pull request by johtani**
Add explanation how each properties woks.

### CODE REVIEW

**Review by nik9000 — APPROVED** [review]
LGTM

**Comment by cbuescher** [comment]
This look like it needs another @elasticmachine test this please.

**Comment by javanna** [comment]
retest this please

**Comment by javanna** [comment]
retest this please

**Comment by javanna** [comment]
@johtani would you like to go ahead and merge this once it's got a green build?

**Comment by johtani** [comment]
@javanna Of course :)

**Comment by johtani** [comment]
retest this please

**Comment by johtani** [comment]
retest this please

**Comment by johtani** [comment]
retest this please

**Comment by johtani** [comment]
retest this please

**Comment by johtani** [comment]
retest this please

**Comment by johtani** [comment]
retest this please

**Comment by cbuescher** [comment]
@johtani looking at the build failure, this one probably just needs a rebase/merge on master. But looking at the change I'd say this is probably okay to merge right away. I ran the docs build locally and everything looks fine. @javanna wdyt?

**Comment by johtani** [comment]
Ah, I try to rebase then push, tomorrow

**Comment by johtani** [comment]
Finally :)

**Comment by javanna** [comment]
thanks @johtani !!!

**Pull request merged**
