### PR TITLE
Fix scripting documentation (groovy -> painless)

### PR DESCRIPTION
**Pull request by olalonde**
Script below states painless as language not groovy

### CODE REVIEW

**Comment by abeyad** [comment]
Thank you for the contribution @olalonde.  Could you kindly sign the CLA so we can merge it?  Also could you kindly change the commit message to something like
```
The script incorrectly states Groovy as the language instead of Painless, so this commit fixes the issue.
```
The commit/PR title is good.

**Review by abeyad — APPROVED** [review]
LGTM

**Comment by olalonde** [comment]
@abeyad signed CLA and changed commit message.

**Comment by abeyad** [comment]
thank you for your contribution @olalonde

**Pull request merged**
