### PR TITLE
Revert "Fix BWC for file-settings based role mappings (#113900)" and related 

### PR DESCRIPTION
**Pull request by n1v0lg**
Revert "Fix BWC for file-settings based role mappings (#113900)" and related changes. Reverted commits:

- 763764c7fac0d5738534e632d7da327711a272d0
- bc8f9dc7f3882a461d4b89d69c7554a4cb3858ac
- ce07060dce69f961c0906079529e91c7dd7d4b48

This is due to a bug in the above fix. We will reintroduce a paired down version of the fix in a subsequent PR.

### CODE REVIEW

**Review by jakelandis — APPROVED** [review]
LGTM (assuming these are git reverts without additional changes)

**Comment by n1v0lg** [comment]
CI failure was unrelated: https://gradle-enterprise.elastic.co/s/npgurfby72vjg

**Comment by n1v0lg** [comment]
> assuming these are git reverts without additional changes

@jakelandis yup, just three reverts

**Comment by n1v0lg** [comment]
@elasticmachine update branch

**Comment by n1v0lg** [comment]
@elasticmachine update branch

**Comment by n1v0lg** [comment]
@elasticmachine update branch

**Comment by n1v0lg** [comment]
Discussed with es-delivery: the CI job is stuck on an non-test-related step so I'm force merging without waiting for job completion.

**Comment by jfreden** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.x|[](https://github.com/elastic/elasticsearch/pull/114404)|
|✅|8.15|[](https://github.com/elastic/elasticsearch/pull/114405)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

**Pull request merged**
