### PR TITLE
Release notes for v7.11.2

### PR DESCRIPTION
**Pull request by danhermann**
Preview: https://elasticsearch_70106.docs-preview.app.elstc.co/diff

### CODE REVIEW

**Review by jrodewig — APPROVED** [review]
LGTM. I left some non-blocking nits but feel free to ignore those if wanted.

~I'm also adding the @elastic/ml-docs team as reviewers so they can check the ML and transform sections.~ nvm. You already have Lisa as a reviewer! 😄

**Comment by danhermann** [comment]
Thank you, @jrodewig!

**Comment by danhermann** [comment]
@elasticmachine update branch

**Review by lcawl — APPROVED** [review]
LGTM too, thanks!

**Pull request merged**
