### PR TITLE
[DOCS] [2 of 5] Change // CONSOLE comments to [source,console]

### PR DESCRIPTION
**Pull request by jrodewig**
Second chunk of a work effort to replace `// CONSOLE` comments.

I can break this up into smaller diffs if wanted.

Relates to #46189.

### CODE REVIEW

**Comment by jrodewig** [comment]
@nik9000  You mind taking a look at this when convenient?

Should be the last of the big magic comment changes. Thanks!

**Comment by nik9000** [comment]
Sure! It had slipped by me.

**Review by nik9000 — APPROVED** [review]
Generated tests look good!

**Comment by jrodewig** [comment]
Thanks!

**Pull request merged**
