### PR TITLE
Add tests for ingesting CBOR data attachments

### PR DESCRIPTION
**Pull request by spinscale**
[Our docs](https://www.elastic.co/guide/en/elasticsearch/plugins/7.4/ingest-attachment.html) specifically mention that CBOR is supported when ingesting attachments. However this is not tested anywhere.

This commit adds a test, that uses specifically CBOR format in its IndexRequest and another one that behaves like CBOR in the ingest attachment unit tests.

### CODE REVIEW

**Comment by spinscale** [comment]
@elasticmachine update-branch

**Review by martijnvg — APPROVED** [review]
👍

**Comment by spinscale** [comment]
@elasticmachine update branch

**Comment by spinscale** [comment]
@elasticmachine update branch

**Pull request merged**
