### PR TITLE
Don't print empty indices_boost

### PR DESCRIPTION
**Pull request by masaruh**

### CODE REVIEW

**Review by jpountz — APPROVED** [review]
LGTM

**Comment by masaruh** [comment]
Thanks @jpountz

**Comment by clintongormley** [comment]
@masaruh does this not need to go to 5.2.0 as well?

**Comment by javanna** [comment]
it did already, I added the missing label.

**Comment by masaruh** [comment]
Ah, yes, pushed to 5.x as well. Forgot to add the label. Thanks @javanna.

**Pull request merged**
