### PR TITLE
Use isAssignableFrom instead of relying on ClassCastException

### PR DESCRIPTION
**Pull request by uschindler**
Title says it all :-)

### CODE REVIEW

**Comment by uschindler** [comment]
I found more of those, updating PR in a minute...

**Comment by uschindler** [comment]
I added more changes around the static casting. It would be good if somebody cross-checks, because some of checks were really crazy!

**Comment by rmuir** [comment]
I agree catching the cast makes the logic hard to understand. personally i find asSubclass much easier to reason about than isAssignableFrom (i think the verb from in the method throws me for a loop every time), but given that we want to return our own exceptions anyway and that there is some "or" logic in here, I think this is better here. Thanks for cleaning it up! cc: @jdconrad

**Comment by uschindler** [comment]
> personally i find asSubclass much easier to reason about than isAssignableFrom (i think the verb from in the method throws me for a loop every time)

I know those arguments - especially the "From" confuses. If you once understood how this method should be used, it is quite easy to understand:

If you have `left.isAssignableFrom(right)` then this only returns true if you could do the following assignment `leftInstance = rightInstance` - you see left stays left and right stays right. It returns false if you would need a cast and you would get a ClassCastException.

So don't think about super- or subclass, just think in terms of this assignment possible or not! :-)

The problem is similar to some people to understand like `compareTo`. It is the same: `left.compareTo(right)` is the same like `Comparator.compare(left, right)`, so its just the order. It also brought me into the same mental loop until you realize this "order of arguments".

For the code in painless, the huge trycatches confuse more than the mental loop :-)

P.S.: If you look at `Class.isSubclass()`'s source, it calls `isAssignableFrom` internally, because it is the one that the JVM implements. It just wraps the ClassCastException afterwards. So In our current code, it does the same thing 2 times and each unwrapping exception. And its unreadable, too.

**Comment by uschindler** [comment]
> and that there is some "or" logic in here

Thats the real reason why I did it!

**Comment by jdconrad** [comment]
Thanks @uschindler!  LGTM.  If I'm being completely honest, asSubclass was the one I found in examples, so I used that, but this is much cleaner.

**Pull request merged**
