### PR TITLE
[DOCS] Add canonical URL to glossary page

### PR DESCRIPTION
**Pull request by gtback**
This commit demonstrates how to
add a canonical URL, which will be included in the HTML <head> metadata
on output.

Depends on elastic/docs#2373

### CODE REVIEW

**Comment by gtback** [comment]
Once the Docs PR is merged, I'll rerun the doc build job and examine the HTML diff, which should show the changes in this PR.

**Comment by gtback** [comment]
cc: @Dinomoe @AnneB-SEO

**Comment by jrodewig** [comment]
@gtback @AnneB-SEO Can we pick another example for this?

As pointed out in https://github.com/elastic/elasticsearch/issues/70192#issuecomment-952294798, frozen indices aren't related to the frozen tier. The two features don't necessarily serve the same use cases.

**Comment by gtback** [comment]
Thanks, @jrodewig , I'm happy to use a different example. Do you have any suggestions?

**Comment by jrodewig** [comment]
> Thanks, @jrodewig , I'm happy to use a different example. Do you have any suggestions?

I pushed https://github.com/elastic/elasticsearch/pull/83752/commits/3a04c013a0f1ebe6451a46969319612d0dd911c7 to use the ES glossary instead. Feel free to revert if that doesn't match the criteria you had in mind. Thanks!

**Comment by gtback** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by gtback** [comment]
I'm running tests again since merging the elastic/docs PR, to confirm in the diff that the link shows up in the `<head>` element correctly.

I don't have a strong stake in where the link goes; I'll leave that up to you 😁

**Review by jrodewig — APPROVED** [review]
LGTM, but @AnneB-SEO will probably want to make sure this is a good example.

Thanks!

**Pull request closed without merging**
