### PR TITLE
Replace problematic bwc indices for 2.3.1 with newly generated one.

### PR DESCRIPTION
**Pull request by jimczi**
Restore the test OldIndexBackwardsCompatibilityIT.testOldIndexes which now works fine with 2.3.1 bwc indices.

### CODE REVIEW

**Comment by jimferenczi** [comment]
@clintongormley I've re-created the bwc indices for 2.3.1 and the test is ok now. It seems that the indices you've created do not contain payloads. Any idea why ?

**Comment by jpountz** [comment]
Maybe it is due to differences between the script that we have on master and 2.3?

LGTM

**Comment by jimferenczi** [comment]
Thanks @jpountz

**Comment by clintongormley** [comment]
yes i may have created the indices from the wrong branch - thanks for fixing @jimferenczi

**Comment by nik9000** [comment]
I pushed a similar fix a week or two ago. I didn't just push the fix again
this time because I figured we should figure out how we made these in the
first place if it happened twice.

**Comment by clintongormley** [comment]
I did this twice? :(  I'll have to be more careful...

**Pull request merged**
