### PR TITLE
EQL: [Tests] Add option to preserve data dir

### PR DESCRIPTION
**Pull request by matriv**
When debugging eql correctness tests, on every new build/run of the test
node the 2.2GB data is restored from the gcs bucket and slows down
productivity. Now a system env var can be set to point to a data dir,
so that the user can only load the data once and use the data dir
across multiple test runs.

### CODE REVIEW

**Comment by matriv** [comment]
@mark-vieira Probably, disallowing to change the `path.data` setting is there for a reason, but this is very helpful for our debugging process. Maybe there is some better way that could get us there though.

**Review by rjernst — COMMENTED** [review]
This makes the test potentially non-deterministic since there is now data/state outside the control of the test. Additionally, it's surprising to see we have data used for a test sitting outside the git codebase. Can we build this data for the test locally? At minimum could we copy it locally and restore from a local file repository so that the caching can be done by gradle itself instead of the developer?

**Comment by mark-vieira** [comment]
Here's a question, the fact that the snapshot we are restoring from lives in a GCP bucket is mostly an implementation detail, yes? Would it be possible to download/cache that snapshot locally, and then just to the restore from the local file? Is the network latency that primary slow spot or is the restore process also very slow?

**Comment by matriv** [comment]
I think both restore and network is an issue, if you have to run this multiple times while debugging, or implementing something and you're constantly testing.

**Comment by matriv** [comment]
@rjernst The path.data is only changed if the user sets a system env variable and is used only for the debugging/local dev purposes. In normal runs the test has the standard behavior so I don't see any real potential issue.

**Comment by mark-vieira** [comment]
> I think both restore and network is an issue

When I tested this locally the vast majority of the time was spent on the download. I think it's worth spiking an effort to cache locally and see if it's really the restore that dominating the time here. I really think caching is going to give developers the best experience as even w/ preserving the data directory as you describe, between runs w/o that toggle, folks are going to have to download that snapshot again. If anything, it might even make sense to do a combination of the two.

Do you mind doing a local experiment of restoring the snapshot from an already downloaded copy of the snapshot vs restoring directly from GCS?

**Comment by matriv** [comment]
@mark-vieira I'll try it and come back with the timing.

**Comment by matriv** [comment]
@mark-vieira I tried restoring the data from a local `fs` snapshot repo and it takes around `57secs` on average.
In my opinion this is not very long but still is something substantial if you have to do it multiple times when debugging and restarting the es node. @astefan @costin What do you think?

**Comment by costin** [comment]
Any improvement to avoid downloading the file is worth it. Each test run downloads 2.2GB. This adds up really fast.

**Comment by astefan** [comment]
Is it possible to re-use the previous runs' ES instance `data` folder as an alternative to pointing the `data.path` to an user defined variable? Cleaning up the test data node, except the `data` folder or better said "if the `data` folder is there, keep it and rebuild the rest of the node's files". This behavior could be controlled with a true/false parameter.

**Comment by mark-vieira** [comment]
Closing this in favor of https://github.com/elastic/elasticsearch/pull/65400.

**Pull request closed without merging**
