### PR TITLE
Feature/replace avl digest with merging digest

### PR DESCRIPTION
**Pull request by not-napoleon**
Relates to #28702

@colings86 had started this conversion in the above referenced PR.  This builds on his work with unit tests for deserializing between the two t-digest implementations.  

This is a work in progress because the testing methodology is ready for feedback, but specific test parameters still need to be tuned.

### CODE REVIEW

**Comment by MirAkram** [comment]
mj1265849@gmail.com
در تاریخ ۲۰ نوامبر ۲۰۱۸ ۹:۲۵ بعدازظهر، "Mark Tozzi" <
notifications@github.com> نوشت:

**Comment by colings86** [comment]
Thanks for running these benchmarks @not-napoleon. Based on the fact that the error introduced in the mixed cluster scenario is pretty low and that we expect mixed clusters to be a short-lived situation I would be happy to proceed with the switchover as is. I'd be interested to hear thoughts from @polyfractal and @jpountz on this though.

Also in terms of the "flaky" test. I think we can do one of two things (again I'm interested to see what you, @polyfractal and @jpountz think here):
1. Don't merge the test but view it as a benchmarking exercise we did to ensure this change would not introduce unacceptable errors in the transition period.
2. Run the test in a different way where it calculates the percentage difference from N requests and calculates e.g. the 90th percentile is within a tolerance instead of hoping a single request is within tolerance. The downside here might be the test time but since it's a unit test hopefully this would not make the test take too long with something like N=50.

**Comment by not-napoleon** [comment]
@colings86 both options for the test seem reasonable.  I was running 10k iterations of the test in less than 120 seconds on my laptop, and a lot of that time is gradle overhead, so 50 shouldn't even be a blip in our test times.

**Comment by polyfractal** [comment]
>  Based on the fact that the error introduced in the mixed cluster scenario is pretty low and that we expect mixed clusters to be a short-lived situation I would be happy to proceed with the switchover as is. 

Gernerally ++ to this.  @not-napoleon and I were chatting last night and another point came up: since the error basically goes to zero when compression is cranked up, if a user is unhappy about the potential cross-version error they could temporarily increase `compression` until the mixed cluster is homogeneous again.  

I did have a few questions about testing methodology after noodling over it a bit.  I'm not sure if any of these are important, they are more half-baked thoughts than anything:

- I wonder if maybe we should be testing that `abs(modern_error) <= abs(legacy_error * 1.05)`, rather than `abs(legacy_error - modern_error) <= 0.05` ?  E.g. we probably don't care if the errors are actually similar, just that it's close-to or better.

- I wonder if we should test the case where many legacy AVL get deserialized and merged?  E.g. I'm thinking of the case where there are a dozen shards in the legacy AVL and a single new MergingTree.  Does the ~1% error start compounding badly?  I suspect it will continue to be a nicely behaved error but maybe not?

> Also in terms of the "flaky" test. I think we can do one of two things (again I'm interested to see what you, @polyfractal and @jpountz think here):

I'm leaning towards option 1), or just cranking the tolerance up a bit and revisiting if it still flakes out on CI.  Since this is a short-lived problem/test that will go away after everyone upgrades, it probably doesn't make a ton of sense to invest lots of time trying to keep the test stable.

**Review by polyfractal — APPROVED** [review]
:+1:

**Comment by not-napoleon** [comment]
I did some more digging into this recently, and I believe there's a bug in the 3.2 version of merging digest which cause `max` and `min` to not be set correctly when adding values, only when merging.  This results in some very weird test failures, and probably would cause actual production issues.  The issue appears to be fixed in 3.3, so this is blocked on https://github.com/elastic/elasticsearch/issues/73928 at this point.

**Comment by martijnvg** [comment]
Looks like continuing to adopt merging digest is worth our while from a performance perspective:

```
|                                                Min Throughput | percentile_cpu_usage_per_container_15_minutes |      0.25977     |     13.8869      |      13.6271      |  ops/s | +5245.83% |
|                                               Mean Throughput | percentile_cpu_usage_per_container_15_minutes |      0.260257    |     14.256       |      13.9958      |  ops/s | +5377.68% |
|                                             Median Throughput | percentile_cpu_usage_per_container_15_minutes |      0.260266    |     14.3062      |      14.0459      |  ops/s | +5396.76% |
|                                                Max Throughput | percentile_cpu_usage_per_container_15_minutes |      0.260605    |     14.3405      |      14.0799      |  ops/s | +5402.76% |
|                                       50th percentile latency | percentile_cpu_usage_per_container_15_minutes |   3818.22        |     68.1857      |   -3750.03        |     ms |   -98.21% |
|                                       90th percentile latency | percentile_cpu_usage_per_container_15_minutes |   3931.99        |     73.0426      |   -3858.95        |     ms |   -98.14% |
|                                       99th percentile latency | percentile_cpu_usage_per_container_15_minutes |   4047.25        |     89.1457      |   -3958.11        |     ms |   -97.80% |
|                                      100th percentile latency | percentile_cpu_usage_per_container_15_minutes |   4054.87        |     90.7218      |   -3964.15        |     ms |   -97.76% |
|                                  50th percentile service time | percentile_cpu_usage_per_container_15_minutes |   3818.22        |     68.1857      |   -3750.03        |     ms |   -98.21% |
|                                  90th percentile service time | percentile_cpu_usage_per_container_15_minutes |   3931.99        |     73.0426      |   -3858.95        |     ms |   -98.14% |
|                                  99th percentile service time | percentile_cpu_usage_per_container_15_minutes |   4047.25        |     89.1457      |   -3958.11        |     ms |   -97.80% |
|                                 100th percentile service time | percentile_cpu_usage_per_container_15_minutes |   4054.87        |     90.7218      |   -3964.15        |     ms |   -97.76% |
|                                                    error rate | percentile_cpu_usage_per_container_15_minutes |      0           |      0           |       0           |      % |     0.00% |
```

The two hour and 24 hour variant of this search showed a similar relative improvement. 

This based on running this search from [a new tsdb rally track](https://github.com/elastic/rally-tracks/pull/373):

```
{
      "aggs": {
        "0": {
          "date_histogram": {
            "field": "@timestamp",
            "fixed_interval": "{{info[0]}}",
            "time_zone": "Europe/Athens",
            "min_doc_count": 1
          },
          "aggs": {
            "1": {
              "percentiles": {
                "field": "kubernetes.container.cpu.usage.nanocores",
                "percents": [
                  95
                ]
              }
            }
          }
        }
      },
      "size": 0,
      "fields": [
        {
          "field": "@timestamp",
          "format": "date_time"
        },
        {
          "field": "event.ingested",
          "format": "date_time"
        },
        {
          "field": "process.cpu.start_time",
          "format": "date_time"
        },
        {
          "field": "system.process.cpu.start_time",
          "format": "date_time"
        }
      ],
      "script_fields": {},
      "stored_fields": [
        "*"
      ],
      "runtime_mappings": {},
      "_source": {
        "excludes": []
      },
      "query": {
        "bool": {
          "must": [],
          "filter": [
            {
              "match_phrase": {
                "data_stream.dataset": "kubernetes.container"
              }
            },
            {
              "range": {
                "@timestamp": {
                  "format": "strict_date_optional_time",
                  "gte": "{{info[1]}}",
                  "lte": "{{end_time}}"
                }
              }
            }
          ],
          "should": [],
          "must_not": []
        }
      }
    } 
}
```

The baseline is main branch and contender this PR.

**Comment by not-napoleon** [comment]
This is no longer relevant

**Pull request closed without merging**
