### PR TITLE
[API] separate tasks.list and tasks.get APIs in the json definition

### PR DESCRIPTION
**Pull request by honzakral**
All variable parts of the URL should be documented.

### CODE REVIEW

**Comment by nik9000** [comment]
Actually the bug is that `"/_tasks/{task_id}"` isn't part of the tasks list API any more - it is the task get API now.

**Comment by HonzaKral** [comment]
Thanks for the note. I was looking for `tasks.get` and didn't find it so I assumed it's just an option for list.

@nik9000 is there any reason why the API is `task.get` as opposed to `tasks.get`? We typically have everything in the same namespace and using plural even for get, like `indices.get`.

Updated the PR to remove this option from `tasks.list`

**Comment by nik9000** [comment]
LGTM.

I just called the task `task.get` instead of `tasks.get`. I have no problem renaming it.

**Comment by HonzaKral** [comment]
Thanks! Added a commit with the rename

**Comment by nik9000** [comment]
LGTM

**Comment by spinscale** [comment]
I am confused by this change (or maybe the YAML spec). The `RestGetTaskAction` states at https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/rest/action/admin/cluster/node/tasks/RestGetTaskAction.java#L40 that an URL parameter to specify the task id is expected. Now the spec has been changed that the `taskId` specified in the YAML spec always is a HTTP parameter? (This works in ES because if the parameter is not part of the URL, the HTTP parameters are tried)

**Comment by HonzaKral** [comment]
@spinscale the specs for `tasks.get` haven't changed at all, we only removed the option for `tasks.list` to get a `task_id` in the URL to align it with the spec at https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/rest/action/admin/cluster/node/tasks/RestListTasksAction.java#L48

Sorry if the wording of the PR was a bit confusing

**Comment by spinscale** [comment]
uh, misread the diff, yaml tests/spec are fine. thx for the clarification

**Pull request merged**
