### PR TITLE
IncludeExclude does not need formatter when converting longs

### LINKED ISSUE #38692: Precision loss of include/exclude filter values in terms aggregation
**Elasticsearch version** (`bin/elasticsearch --version`):
6.4.2

**Plugins installed**: []

**JVM version** (`java -version`):
```
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-2~deb9u1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
```

**OS version** (`uname -a` if on a Unix-like system):
```
Linux 4.18.0-2-amd64 #1 SMP Debian 4.18.10-2 (2018-10-07) x86_64 GNU/Linux
```

**Description of the problem including expected versus actual behavior**:
When trying to filter the values for which buckets are created when using terms aggregation on a long field, it's not possible to use values larger than 53 bits. When specifying one in a list of include values, no bucket is created most of the time, and when specifying one in a list of exclude values, the respective bucket is not excluded. I expect that for fields of the long type, the full 64 bit range works.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. `PUT /test '{"mappings":{"_doc":{"properties":{"field1":{"type":"long"}}}}}'`
 2. `POST /test/_doc '{"field1":0}'`
 2. `POST /test/_doc '{"field1":123456}'`
 2. `POST /test/_doc '{"field1":4094779560956318341}'`
 3. `POST /test/_doc/_search '{"size":0,"aggs":{"by_field1":{"terms":{"field":"field1","include":[0,123456,4094779560956318341]}}}}` returns only buckets for 0 and 123456
 3. `POST /test/_doc/_search '{"size":0,"aggs":{"by_field1":{"terms":{"field":"field1","exclude":[0,123456,4094779560956318341]}}}}` returns only bucket for 4094779560956318341

**Provide logs (if relevant)**:

The reason is apparently here:
https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/search/aggregations/bucket/terms/IncludeExclude.java#L633-L642
and here:
https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/search/DocValueFormat.java#L118-L126

### PR DESCRIPTION
**Pull request by polyfractal**
Using the formatter converts longs (wrapped in a `BytesRef`) to a double, then rounds/truncates back to a long.  This loses precision for large longs.

I might be missing something, but I think we should instead just convert the string value directly to a long.

The disadvantage is that a floating point value will throw a `NumberFormatException`, but it looks like this shouldn't be a problem.  The only two usages are by terms and sigterms aggs, and both check if the number is a float first and use `convertToDoubleFilter()`.  

We could fall back to the old behavior if a `NumberFormatException` is thrown, but this feels wrong to me since we should only be dealing with longs in the long filter, and silently truncating precision is worse than just throwing an exception imo.

Closes #38692

### CODE REVIEW

**Comment by polyfractal** [comment]
Heh, well, I see what I was missing: dates (and presumably IPs, decimals, etc) fail due to `NumberFormatExceptions` now.  

I pushed a fix where we fall back to the formatter for non-RAW formatters.  It's not super elegant, but I wanted to minimize the fallout from a change like this.  Open to suggestions.

**Comment by cyberhuman** [comment]
Shouldn't RAW formatter's parseLong be updated instead? I'm not sure where else it's used, but I imagine that its users may expect 64-bit long values to be supported, don't they?

**Comment by polyfractal** [comment]
Possibly!  I'm not crazy about the currently proposed PR, but admit that I was partially waiting to see if Adrien had an opinion when he got back as well :)  

I feel like there may be some context here that I'm missing.  E.g. I suspect there is (or potentially _was_ but has since been removed) another place where floats are being fed into `parseLong()` and the truncation behavior is expected/desired.

The current setup of converting all the values to `BytesRef`, and then relying on a semi-generic formatter (`RAW` includes both floats and natural numbers) to parse those values back into longs/doubles seems non-ideal in general.  I wonder if we can get rid of this abstraction and just wrap the `ValuesSource` to do the filtering?  Or perhaps differentiate floats vs natural numbers in the formatters?

**Comment by polyfractal** [comment]
Thought about this a bit more, and I think it needs a more thorough refactor than just a simple bandaid patch (not a ton of work, but something a bit more involved).  Gonna close this PR since I don't have bandwidth right now to fix it up, but will try to get back to it soon :)

**Pull request closed without merging**
