### PR TITLE
Store _all payloads on 1 byte instead of 4.

### PR DESCRIPTION
**Pull request by jpountz**
This changes the `_all` field to store per-field boosts using a single byte
similarly to norms.

For some reason I could not regenerate the bw indices for beta and rc
releases. I still need to look into it.

### CODE REVIEW

**Comment by jimferenczi** [comment]
The loss in precision should not affect every user but we should add a small note in the migration docs, don't you think ?

**Comment by jpountz** [comment]
Good point, will do!

**Comment by jpountz** [comment]
@jimferenczi I pushed a new commit.

**Comment by jimferenczi** [comment]
I don't think we should encode a boost value directly. We've started to change index time boost into query time boost in the other field types so I guess it would be nice to have some sort of query time boost in the _all field as well. For instance we could encode the class of score this payload refers to and change the score of each class at query time. 

````
PUT test
{
    "mappings": {
        "type1": {
            "properties": {
                "title": {
                    "type": "string",
                    "boost": 1
                }
            }
        }
    }
}
````

The boost value is an integer (or a short or even a byte but the key point is to have small numbers so that we can use vint to encode the payload) that refers to the first class score. At query time we could remap the payloads with a value of 1 to any float value we want.

@jpountz I am not saying that we should not merge this PR but other solutions that would let the user change the boost for _all fields at query time should be investigated before changing the format ?

**Comment by jpountz** [comment]
+1 on exploring this idea but I think we should merge this PR first as this proposal is a larger change and has some challenges.

**Comment by jimferenczi** [comment]
Ok thanks @jpountz. I'll open a ticket for the index time boosting in _ all fields.
LGTM

**Pull request merged**
