### PR TITLE
Update aggregations reference documentation for parameter 'keyed'

### LINKED ISSUE #23731: Incomplete documentation for 'keyed' parameter in Percentiles Aggs
**Elasticsearch version**: 5.2

**Description of the problem**:
The parameter `keyed`, for associating a unique string key with each bucket and return the ranges as a hash rather than an array, is supported on Percentiles Aggregation and Percentile Ranks Aggregation as can be seen [here](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/search/aggregations/metrics/percentiles/PercentilesAggregationBuilder.java#L167-L173) and [here](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/search/aggregations/metrics/percentiles/PercentileRanksAggregationBuilder.java#L154-L160).

However, the [docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-percentile-rank-aggregation.html) make no mention of it.

### PR DESCRIPTION
**Pull request by sudo-suhas**
The `keyed` parameter is supported by the following aggregations:
- [Percentiles Aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-percentile-aggregation.html)
- [Percentile Ranks Aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-percentile-rank-aggregation.html)
- [Date Histogram Aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-datehistogram-aggregation.html)
- [Geo Distance Aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-geodistance-aggregation.html)
- [Histogram Aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-histogram-aggregation.html)
- [IP Range Aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-iprange-aggregation.html)
- [Range Aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-range-aggregation.html)

However, in the reference guide, the `keyed` parameter is documented only for Range Aggregation. <br>
Closes #23731.

### CODE REVIEW

**Comment by sudo-suhas** [comment]
@javanna Just found that date range aggregation supports `keyed` as well. Will push another commit to this pull request.

**Comment by sudo-suhas** [comment]
Looks like I screwed up. I rebased using steps explained here - http://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository. Any idea how to fix this?

**Comment by javanna** [comment]
@sudo-suhas you can open a new PR. Just create a new branch out of master, add a commit with  your changes and push it to your remote repo, then open the PR based on that.

**Comment by sudo-suhas** [comment]
@javanna Thanks. Did just that. Also squashed the commits as recommended in the contributing guide.  #23758 . Closing. Also, can I delete this branch?

**Comment by javanna** [comment]
sure you can delete your branch.

**Pull request closed without merging**
