### PR TITLE
[Health API] Abstract data tier diagnoses as node roles

### PR DESCRIPTION
**Pull request by gmarouli**
In this PR we would like to generalise the code that is diagnosing the shard availability when it comes to data tier issues. We would like to make it a bit more extensible so in serverless we can introduce new roles.

For this reason, we consider a tier as a more specific kind of a role. Then we expose some methods and some diagnosis definitions in the `ShardsAvailabilityHealthIndicatorService` so they can be extended. This includes the following lookup tables:
- `ACTION_ENABLE_TIERS_LOOKUP` is accessed via `getAddNodesWithRoleAction`
- `ACTION_INCREASE_SHARD_LIMIT_INDEX_SETTING_LOOKUP` is accessed via `getIncreaseShardLimitIndexSettingAction`
- `ACTION_INCREASE_SHARD_LIMIT_CLUSTER_SETTING_LOOKUP` is accessed via `getIncreaseShardLimitClusterSettingAction`
- `ACTION_INCREASE_TIER_CAPACITY_LOOKUP` is accessed via `getIncreaseNodeWithRoleCapacityAction`

And the methods:
- `checkDataTierRelatedIssues`
- `checkDataTierAtShardLimit`
- `checkNotEnoughNodesInDataTier`

We only leave the migrate diagnoses because they refer to data tier migration.

### CODE REVIEW

**Comment by gmarouli** [comment]
After further investigation this won't be necessary

**Comment by gmarouli** [comment]
@elasticmachine update branch

**Review by andreidan — APPROVED** [review]
LGTM, thanks Mary

**Comment by gmarouli** [comment]
Oopsy.... I will create a new PR.

**Pull request closed without merging**
