### PR TITLE
Explicitly configure setgid for RPM and Dep packaging

### PR DESCRIPTION
**Pull request by breskeby**
Fixes CI issue: https://github.com/elastic/elasticsearch/issues/99972

Ran packaging tests as part of this PR:

 https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+packaging-tests-unix-sample/44772/

### CODE REVIEW

**Review by brianseeders — APPROVED** [review]

**Comment by brianseeders** [comment]
Thanks, I hit this in my buildkite pipelines, and suspected it was related to the gradle update, but wasn't sure what the deal was

**Comment by breskeby** [comment]
I don't get why the original PR for updating gradle didn't catch that. I swear I have enabled packaging tests for the PR but somehow they went away. ¯\_(ツ)_/¯

**Comment by breskeby** [comment]
also fixes https://github.com/elastic/elasticsearch/issues/100068

**Comment by andreidan** [comment]
Thanks for fixing this Rene

**Pull request merged**
