### PR TITLE
Compress async search responses before storing

### PR DESCRIPTION
**Pull request by dnhatn**
Related to #67594

### CODE REVIEW

**Review by jimczi — APPROVED** [review]
LGTM, thanks @dnhatn

**Review by mayya-sharipova — APPROVED** [review]
@dnhatn You are super fast!!! Thanks, LGTM!

**Comment by dnhatn** [comment]
@elasticmachine update branch

**Comment by dnhatn** [comment]
Thanks Jim & Mayya!

**Pull request merged**
