### PR TITLE
[DOCS] Change 'X-Pack APIs' section to 'REST APIs'

### PR DESCRIPTION
**Pull request by jrodewig**
## Context
Creates a new general purpose 'REST APIs' section. The goal is to eventually separate and relocate all API reference documentation to this section.

## Changes
* Changes the title, anchor, and description of the [X-Pack APIs](https://www.elastic.co/guide/en/elasticsearch/reference/master/xpack-api.html) page to reflect a general REST APIs section.

* Relocates the REST APIs section to lower in the navigation.

@lcawl  I removed the `[role="xpack"]` macro as part of this. Let me know if that's alright with you. I believe including that at the API level should be okay.

## Before
<details>
 <summary>Nav - Before</summary>
Nav Before
</details>

<details>
 <summary>REST API Overview - Before</summary>
REST API Overview Before
</details>

## After
<details>
 <summary>Nav - After</summary>
Nav After
</details>

<details>
 <summary>REST API Overview - After</summary>
REST API Overview After
</details>

## Related Issues
Relates to https://github.com/elastic/docs/issues/937.

### CODE REVIEW

**Comment by lcawl** [comment]
I will do a full rebuild to ensure this URL change doesn't cause any broken links.  If it does, we can just add a deleted page, so that's no big deal.

**Comment by jrodewig** [comment]
Thanks @lcawl. I went ahead and added a redirect with e08ae7f in case anyone has that page bookmarked, etc.

**Review by lcawl — APPROVED** [review]
LGTM and builds successfully

**Comment by jrodewig** [comment]
@elasticmachine elasticsearch-ci/1

**Comment by jrodewig** [comment]
@elasticmachine run elasticsearch-ci/1

**Pull request merged**
