### PR TITLE
RestController should not consume request content

### PR DESCRIPTION
**Pull request by tlrx**
The change #37504 modifies the `BaseRestHandler` to make it reject all requests that have an unconsumed body. The notion of consumed or unconsumed body is carried by the `RestRequest` object and its `contentConsumed` attribute, which is set to `true` when the `content()` or `content(true)` methods are used. 

In our REST layer, we usually expect the RestHandlers to consume the request content when needed, but it appears that the `RestController` always consumes the content upfront:

`final int contentLength = request.hasContent() ? request.content().length() : 0;`

making the check in BaseRestHandler useless:
```
if (request.hasContent() && request.isContentConsumed() == false) {
  throw new IllegalArgumentException("request [" + request.method() + " " + request.path() + "] does not support having a body");
}
```

This pull request changes the `content()` method used by the RestController to `content(false)` so that it does not mark the content as consumed. It also adds a test for this and changes the `ForceMergeActionTests.testBodyRejection` so that it uses the usual `dispactchRequest()` execution path (as a normal request would do).

Finally, it fixes some Rollup request objects that were generating a request body for APIs that do not require a body.

### CODE REVIEW

**Review by rjernst — COMMENTED** [review]
Instead of using this internal variant of content that takes in whether or not to mark the content as consumed, can we add a `contentLength()` method that will internally check this? I think then `content(boolean)` can be removed as the only user of `content(false)` is the check to content length in `hasContent()`.

**Comment by tlrx** [comment]
@rjernst Thanks for your feedback. I applied your suggestion, can you please have another look?

**Comment by tlrx** [comment]
@elasticmachine update branch

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by tlrx** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by tlrx** [comment]
Thanks @rjernst ! Because this fix might break existing APIs, I don't think it should be backported to 7.x. Thus I'm removing the 7.3/7.4 labels.

**Pull request merged**
