### PR TITLE
Remove unused cluster name in environment.

### PR DESCRIPTION
**Pull request by howardhuanghua**
Remove unused  cluster name in Environment.java.

### CODE REVIEW

**Comment by nik9000** [comment]
@elasticmachine, test this please

**Comment by nik9000** [comment]
Thanks @howardhuanghua! I'll merge this and backport to 7.x.

**Comment by nik9000** [comment]
> Thanks @howardhuanghua! I'll merge this and backport to 7.x.

And checkstyle failed. @howardhuanghua, could you fix it? You can test that locally with `./gradlew precommit`. It'll check about a million more things than checkstyle, but it is nice and paranoid.

**Comment by howardhuanghua** [comment]
@nik9000 thank you. I have fixed the checkstyle issue. And also opened a backport PR to 7.x, please help to check.
https://github.com/elastic/elasticsearch/pull/59681

**Comment by nik9000** [comment]
@elasticmachine, test this please

**Comment by nik9000** [comment]
The tests all passed so I've merged this and the backport. Thanks @howardhuanghua!

**Pull request merged**
