### PR TITLE
Rework bwc snapshot projects to build up to two bwc versions

### PR DESCRIPTION
**Pull request by nik9000**
Removes the `distribution:bwc` project in favor of
`distribution:bwc-release-snapshot` and
`distribution:bwc-stable-snapshot`.
`distribution:bwc-release-snapshot` builds a snapshot of the
latest release branch (5.4 now) if needed for backwards
compatibility. `distribution:bwc-stable-snapshot` builds a
snapshot of the latest stable branch (5.x now) if needed for
backwards compatibility.

I edited the description to match what was actually committed. This was the old description for posterity:

Adds the `:distribution:bwc-stable` project which builds the previous
stable branch when `:distribution:bwc` is building an unreleased
branch. When `:distribution:bwc` builds a released branch then
`:distribution:bwc-stable` is an empty build, not used or depended
on by anything.

Requires #24798

### CODE REVIEW

**Comment by nik9000** [comment]
Let the naming debates begin!

**Comment by rjernst** [comment]
I think you have the names mixed up. We currently have master, which is the unstable branch, 5.x which is the stable branch, and 5.4 which is our current release branch. But with this change, bwc-stable will build 5.4 snapshot, correct?  Can we have bwc-release and bwc-stable? If on stable branch, then versions[-1] should be linked to bwc-release. If on unstable branch, then versions[-1] linked to bwc-stable and versions[-2] to bwc-release.

**Comment by nik9000** [comment]
@rjernst I've reworked the names so they line up. `bwc-stable` is only used when building `5.x`, `bwc-release` is used when building `5.4`.

**Review by rjernst — APPROVED** [review]
Thank you, this looks good! I just have one more very minor request. Upon further reflection, I think it would be good to suffix these projects with `-snapshot`? So `bwc-stable-snapshot` and `bwc-release-snapshot`?

**Comment by nik9000** [comment]
Sure. `-snapshot` is fine. Makes sense because we only need it for
snapshots.

**Comment by nik9000** [comment]
Ok - I've made the changes and will merge in a moment. I plan to just merge to master because we aren't super likely to need it in 5.x. At least I don't think we are....

**Pull request merged**
