### PR TITLE
[DOCS] Add identifier mapping tip to numeric and keyword datatype docs

### LINKED ISSUE #49538: Integer/long mapping is trappy for ID-based fields
Saw [another example ](https://discuss.elastic.co/t/why-is-elasticsearch-sql-excruciatingly-slow/209276/2?u=mark_harwood) of someone falling into the trap of mapping fields as longs when they are queried for exact-values rather than ranges. These are better mapped as keyword fields.

It's a trap that is too easy to fall into - "I have a long field so I just map it as a long-value, right?"

I can think of 4 ways to address the problem:
1) Change documentation - provide bigger, bolder notices that not all longs should be mapped as longs. Nothing mentioned on [numbers docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/number.html) currently, only a [speed-tuning page](https://www.elastic.co/guide/en/elasticsearch/reference/master/tune-for-search-speed.html#map-ids-as-keyword).
2) Change field type names - use `long_quantity` or `long_identifier` to express the usage of a long number (quantities are things like prices or durations and are optimised for range queries whereas identifiers are looked up by exact matches)
3) Better tooling - mapping-generation tools that suggest appropriate mappings given a sample of data (the ML team and me have both worked on these sort of data profiling tools before now).
4) Automated indexing of numerics for both range and exact-match purposes (would require extra disk space)

An advantage of 2) is that I imagine we can have more optimised storage than string-based keyword for long_identifier types?

### PR DESCRIPTION
**Pull request by jrodewig**
Users often mistakenly map numeric IDs to numeric datatypes, such as `integer` or `long`. However, this is often slow for the `term` and other term-level queries.

To prevent this, the "Tune for search speed" docs includes advice for mapping numeric IDs to `keyword` fields. However, this tip is not included in the numeric or `keyword` field datatype doc pages.

This rewords the tip in the "Tune for search speed" docs, relocates it to the `numeric` field docs, and reuses it using tagged regions.

Closes #49538.

### CODE REVIEW

**Comment by jrodewig** [comment]
@elasticmachine update branch

**Comment by markharwood** [comment]
Apologies for the delay responding.
The updates look great but I have a question about the "keywords are incompatible with aggregations" sentiments expressed. It's pretty common to want to do things like find the top-spending customer accounts using aggregations and so keyword fields are appropriate for this task.

One other data-prep tip I have for general analysis of IDs is that users need to address the problem that computers want unique IDs but people want readable labels.  Kibana doesn't have a [translation service](https://github.com/elastic/kibana/issues/17877) so a useful approach is to index `keyword` fields that are a combination of unique ID and a label e.g. `[3246344] John Smith` for a customerID field. Some IDs like email addresses are designed to be both unique and human readable but for many IDs like bank account IDs this is not the case.
This ID+label tip probably doesn't live with the docs in this PR but may be useful to put somewhere else.

**Comment by jrodewig** [comment]
Thanks for your review, @markharwood.

I pushed 204bb71b825e9aa9ea36d9fce63d4ac4a95a3412 to make the following changes:

- Remove instances where I implied keywords weren't suitable for aggs.
- Make the heading more precise

I like the ID+label tip! But I agree that it doesn't really fit with this block. I opened #50148 to track that as a separate issue. In that case, I think it might also be helpful to explain how users could concatenate existing data using a scripted field or do it during ingest.

Thanks again!

**Review by markharwood — APPROVED** [review]
LGTM. Thanks!

**Comment by jrodewig** [comment]
master: 230d476
7.x: 726c35dfd04a30a996802f977aeb353b5bcc754e
7.5: c2192809cea3ea3517ca6a2b75871501f238d126

**Pull request merged**
