### PR TITLE
Improve painless's ScriptException generation

### PR DESCRIPTION
**Pull request by nik9000**
1. Added a few more tests for REST rendering of ScriptException.
2. Centralize generation of the exception to one place so I don't have to make changes in two places. Uses lambdas to plug strategies for snippet segmentation into the exception generation logic.
3. Include the cause of the ScriptException's message in the ScriptException's message. This is useful because ScriptException is often pulled into the `root_cause` element of an error report so this adds the cause of the exception to the `root_cause` element.
4. Include all unfiltered stack trace elements of the in the script_stack starting with the outermost invocation of the script. The old behavior started with the innermost invocation.
5. Moves the offset for errors during invocation back to the offset of the invocation rather than the offset of the last parameter.

Example for the stack trace element included change. Say you pass this script:
```
return Optional.empty().orElseGet(() -> params.a.length())
```
with an empty `params`. It'll `NullPointerException` all day, every day. Before this PR the `script_stack` would look like:
```
"script_stack": [
  "() -> params.a.length())",
  "              ^---- HERE"
]
```

Now it looks like:
```
"script_stack": [
  "... () -> params.a.length())",
  "                  ^---- HERE",
  "java.util.Optional.orElseGet(Optional.java:213)",
  "return Optional.empty().orElseGet( ...",
  "                       ^---- HERE"
]
```

This should make it easier to track down errors, especially in larger scripts with methods because you can find the location of error.

Relates to #21733

### CODE REVIEW

**Comment by nik9000** [comment]
@jdconrad can you have a look at this? Sorry for the extra lambdas but they let me remove a bunch of copy and paste so it is more obvious how those two methods of generating the script_stack differ. I don't think they'll amount to a performance problem because they come up only when there is an error running or compiling the script.

**Comment by rjernst** [comment]
@nik9000 Can you explain more how your example extended script stack is better? I find it very confusing, as before it was very clear the exception (an NPE) was tied to this specific place in the script (where the arrow points). I understand if there are multiple places that contain the same have the same expression then it would be ambiguous, but that seems it could be solved with (1) better context (more characters from the original script/line being exposed) and (2) possibly giving eg character offsets?

**Comment by nik9000** [comment]
> @nik9000 Can you explain more how your example extended script stack is better?

Sure. I'll put together a more obvious example. The gist is that the old way truncate the stack trace at the inner most execution which is fine for a language without method calls of lambdas, but with them you get into situations where you can't figure out how you got where you are.

**Comment by nik9000** [comment]
Here is another example script:
```
def a(def c) {
  return c.length()
}
if (doc.goals.value > 1) {
  return a('test')
} else {
  return a(null)
}
```

If `doc` has a `goals` greater than one the script will fail. The old script_stack would be:
```
      "script_stack": [
         "return c.length()}  ...",
         "           ^---- HERE"
      ],
```

The new one is:
```
      "script_stack": [
         "... return c.length()}  ...",
         "            ^---- HERE",
         "... return a(null)}",
         "           ^---- HERE"
      ],
```

The second line gives you the call site. Without it you have to guess "how did this method receive null". I wouldn't want to debug java or python without the stack trace and I'm not a big fan of debugging painless without it either.

The `...` come from normalizing the rendering logic - I don't really have a preference either way there other than "lets not copy and past 40 lines of code and changing in subtle things".

Would it make more sense if it read:
```
      "script_stack": [
         "at ... return c.length()}  ...",
         "               ^---- HERE",
         "at ... return a(null)}",
         "              ^---- HERE"
      ],
```
like a java stack trace?

**Comment by rjernst** [comment]
The issue I have with the first example is those are not two separate lines. Perhaps if the parent call site is on the same line as the current call site, the trace could be extended to include larger information? I see your point, but isn't it really only an issue with functions? Painless has limited ways to do this type of obfuscation, so I'm not sure a general purpose solution is necessary. Perhaps in this case of functions some context, similar to the "caused by" in stack traces could be added, but I would not reuse the "HERE" arrow, as having two of those is still confusing to me. Perhaps it could be something like:

```
 "script_stack": [
         "return c.length()}  ...",
         "           ^---- HERE"
         "in function: def a(def c)",
         "called as: def(null)"
      ],
```

**Comment by nik9000** [comment]
I'm fine with trashing the second here arrow and going with something more intuitive. `in function: def a(dec c)` sounds good. I wonder if a line number would be better in most situations though.

I'd like to get it closer to the normal java stack trace rather than further so that traces that dip into the jvm like the optional example above can reuse the normal java elements. 

I don't agree that painless has limited ways of obfuscating the call stack. Well, I guess they are limited, but its interoperability with Java means it has all kinds of ways to exchange control with JVM and Elasticsearch classes and so the stack traces can be fairly complex and interleaved with standard java classes. That information is fairly important. It is also quite possible that the exception is thrown by a JVM or Elasticsearch class and it ends up on the top of the stack trace.

**Comment by rjernst** [comment]
>  I wonder if a line number would be better in most situations though.

I remember when Robert worked on improving these error messages, there was an issue with associating character/line numbers back to the source (it could get them wrong, or off a little, but only sometimes). I don't remember if it was just character offsets, or also line numbers.

> I'd like to get it closer to the normal java stack trace

Java stack traces are hard to read for normal users. They are useful for developers, and I understand why we went this route with elasticsearch exceptions, but users find this incredibly hard to deal with. IMO, we should never see such stack traces in "normal" conditions in ES. For example, if there is an illegal argument used in a mapper, we should provide a response that indicates which mapper type, field name, and the unknown option that was found. But right now we do this through wrapping of exceptions and needing to visual filter through deep call stacks. So I do not think we should continue that pattern for painless, but instead experiment with ways to give enough context information about what the error is (and how to fix it), without needing a visually complicated stack. I think a lot of these improvements can be done by mapping known states (eg doing did you mean on variable names when a variable is not found). And also improving error messages for specific types (eg for OOM, we could customize the error message so it explains that the script used more memory than elasticsearch allows, and that they should check for trying to create too large arrays and such).

**Comment by nik9000** [comment]
> Java stack traces are hard to read for normal users

I don't think you can debug scripts without some kind of stack trace. At least, I'd hate trying.

I agree that we can and should remove them from "expected" failure scenarios. One of the things this PR does is to make using the `root_cause` easier for script compilation failures and I think that is an improvement.

The bit about offsets is complex. There are all kinds of intricacies to getting the offsets right and it looks like the code really makes and effort to get them right. I had to fix a small problem with them to get the call site right so I know it is fiddly. I don't know about line number though. I think if we get the offsets right we can turn that into line numbers without too much trouble. And I agree getting the offsets right is difficult though.

**Comment by xy17** [comment]
i love you

**Comment by nik9000** [comment]
> i love you

I know.

**Comment by nik9000** [comment]
@rjernst, would you be ok if I revert the behavior changes to the script_stack but keep the stuff that removes the code duplication?

**Comment by rjernst** [comment]
I can't picture exactly what that would look like, but if you think it satisfies my concerns above, then ok.

**Comment by nik9000** [comment]
> I can't picture exactly what that would look like, but if you think it satisfies my concerns above, then ok.

It would keep script stack nearly identical to how it is now but it'd remove some code duplication.

**Pull request closed without merging**
