### PR TITLE
Upgrade to Gradle 5.6

### PR DESCRIPTION
**Pull request by alpar-t**
Upgrade to 5.6.
The [release notes](https://docs.gradle.org/5.6-rc-1/release-notes.html) show that there was quite some work going into this release.

### CODE REVIEW

**Comment by atorok** [comment]
Will wait for the final release before merging.

**Comment by atorok** [comment]
@elasticmachine update branch

**Comment by mark-vieira** [comment]
@elasticmachine update branch

**Comment by atorok** [comment]
@elasticmachine update branch

**Comment by atorok** [comment]
@mark-vieira are we good to merge this ?

**Comment by mark-vieira** [comment]
Yep. 👍

**Pull request merged**
