### PR TITLE
Add openjdk 15 to Java matrix testing rotation

### LINKED ISSUE #50764: Add JDK 15 EA to testing rotation
The OpenJDK project has an EA (early access) build for JDK 15 available at https://jdk.java.net/15/, which was released on Dec 27, 2019. This issue is to track getting this JDK integrated into CI for testing.

### PR DESCRIPTION
**Pull request by mark-vieira**
Adding the EA release of Java 15 to our Java matrix testing configuration.

Closes #50764

### CODE REVIEW

**Comment by mark-vieira** [comment]
@jasontedor looking at what we've done for other Java versions I assume this needs to be backported to `7.x` as well?

**Comment by jasontedor** [comment]
Yes, and we want to test 6.8 against it as well.

**Comment by jasontedor** [comment]
@mark-vieira Note that we would want to also add JDK 15 to the build matrix, for 7.x and master, so that we ensure that we can compile/build Javadocs with the JDK 15 compiler (since that will be the future compiler that we use, when JDK 15 is released).

**Comment by mark-vieira** [comment]
@jasontedor We aren't even doing this for Java 14 yet and Gradle still doesn't officially support JDK 14 either so far as I can tell. I'm afraid this would just add a lot of noise. I'm not sure testing with a JDK that we know not all of our tooling full supports is particularly valuable.

**Comment by jasontedor** [comment]
Thanks, I forgot that JDK 14 wasn’t functional on Gradle yet.

**Pull request merged**
