### PR TITLE
Add replaceAll and replaceFirst

### PR DESCRIPTION
**Pull request by nik9000**
These are useful methods in groovy that give you control over
the replacements used:

```
'the quick brown fox'.replaceAll(/[aeiou]/,
        m -> m.group().toUpperCase(Locale.ROOT))
```

They mimick two of the augments groovy has for regexes.

### CODE REVIEW

**Comment by uschindler** [comment]
Why not use the official loop for replacements in Matcher? https://docs.oracle.com/javase/8/docs/api/java/util/regex/Matcher.html#appendReplacement-java.lang.StringBuffer-java.lang.String-

**Comment by rmuir** [comment]
I don't know enough about java's regex to know if Uwe's suggestion is strictly equivalent. But I like the PR.

**Comment by nik9000** [comment]
> Why not use the official loop for replacements in Matcher?

I figured those were less than desirable because they were StringBuffer instead of StringBuilder.

**Comment by uschindler** [comment]
> I figured those were less than desirable because they were StringBuffer instead of StringBuilder.

That's not an issue anymore. StringBuilder and StringBuffer are as fast in Java 6+. The introduction of StringBuilder was only needed in older Java versions. This is the reason why the APIs of Matcher were not changed afterwards (issues in OpenJDK closed).

So please don't reimplement the code and be safe and use the Matcher methods! If you look at `String.replaceAll(String, String)` (the regex one) and `Matcher.replaceAll()` source code you see the same loop: http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8u40-b25/java/util/regex/Matcher.java#Matcher.replaceAll%28java.lang.String%29

**Comment by nik9000** [comment]
> That's not an issue anymore

Looks like it. Uncontended synchronization elimination works as expected. Another old habit gone.


> In addition, the Java APIs allow to use \1 and \0 for groups, and can be "disabled" by quoteReplacement

I'll look into it.

**Comment by nik9000** [comment]
> I'll look into it.

And done. It seems silly that they didn't make `quoteReplacement` a boolean parameter but I guess this way covers slightly more cases.

**Comment by uschindler** [comment]
Thanks.

Shouldn't we maybe allow `\1` or `$1` to allow references to groups (means remove `quoteReplacement`)? To me this is a major use-case or search/replace.

**Comment by nik9000** [comment]
Not for the closure form. You can get them from the matcher. You can
certainly use replaceAll on the matcher if you want them.

**Comment by nik9000** [comment]
My reasoning is that `\1` makes sense in `Matcher.replaceAll` because you are sending it a string - but this version you send it a `Function` so if you want a capturing group you can just call `m.group` on it and have the capturing group. `\1` feels like it'd just get in the way and be surprising. I could see someone having the opposite opinion though. For what it is worth, the method this is imitating in groovy doesn't support `\1` either though the javadocs don't go into why.

**Comment by clintongormley** [comment]
@nik9000 i want to be able to do things like:

    /\b(?:\d{12}(\d{4}))\b/.replaceAll("...$1")

I have no idea what this would look like with your syntax?

**Comment by nik9000** [comment]
> I have no idea what this would look like with your syntax?

That is already there with us whitelisting `Matcher#replaceAll`
```
/\b(?:\d{12}(\d{4}))\b/.matcher("string").replaceAll("stuff$1")
```

This proposed syntax if for when you need to manipulate the captures more than just moving them around.

**Comment by rmuir** [comment]
> For what it is worth, the method this is imitating in groovy doesn't support \1 either though the javadocs don't go into why.

I think it would be confusing to diverge from that behavior. For a lot of reasons consistency with whatever it is doing will be easiest on everyone if we can have it.

**Comment by nik9000** [comment]
@clintongormley I can add another example to the docs calling out `Matcher#replaceAll`'s existence and `$1` support and to describe this feature as for when you need "yet more control".

**Comment by nik9000** [comment]
> I can add another example to the docs calling out Matcher#replaceAll's existence and $1 support and to describe this feature as for when you need "yet more control".

I just added that to this PR.

**Comment by 3st384n** [comment]
Disculpen.. Me podrian decir con quien me puedo acercar para preguntar de una duda que tengo? Porfavor y gracias.

**Comment by rmuir** [comment]
What is the status here? this change looks good to me.

**Comment by nik9000** [comment]
> What is the status here? this change looks good to me.

I'm not sure.... I think at this point I'll merge it and we can rework it later if it needs it?

**Pull request merged**
