### PR TITLE
[DOCS] Fix intro for "Encrypt HTTP client communications for Kibana"

### PR DESCRIPTION
**Pull request by Navanit-git**
Updates the intro to the  "Encrypt HTTP client communications for Kibana" section so it aligns with the order of the following subsections.
 
### Preview
https://elasticsearch_84237.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/7.17/security-basic-setup-https.html

### CODE REVIEW

**Comment by jrodewig** [comment]
Thanks @Navanit-git. I believe you're right.

Before I can merge in these changes, you'll need to sign the CLA:
https://www.elastic.co/contributor-agreement

Please use the same email address associated with your commit. You can find that email address here:
https://github.com/elastic/elasticsearch/commit/ad5d7b64fa68875ad4a27c0f45c78c59a332b7be.patch

**Comment by Navanit-git** [comment]
> Thanks @Navanit-git. I believe you're right.
> 
> Before I can merge in these changes, you'll need to sign the CLA: https://www.elastic.co/contributor-agreement
> 
> Please use the same email address associated with your commit. You can find that email address here: https://github.com/elastic/elasticsearch/commit/ad5d7b64fa68875ad4a27c0f45c78c59a332b7be.patch



> Thanks @Navanit-git. I believe you're right.
> 
> Before I can merge in these changes, you'll need to sign the CLA: https://www.elastic.co/contributor-agreement
> 
> Please use the same email address associated with your commit. You can find that email address here: https://github.com/elastic/elasticsearch/commit/ad5d7b64fa68875ad4a27c0f45c78c59a332b7be.patch

Hi, I have signed the contributor agreement on 23/02/2022 at 10:55 IST. Now, waiting for the reply.

**Comment by Navanit-git** [comment]
> Thanks @Navanit-git. I believe you're right.
> 
> Before I can merge in these changes, you'll need to sign the CLA: https://www.elastic.co/contributor-agreement
> 
> Please use the same email address associated with your commit. You can find that email address here: https://github.com/elastic/elasticsearch/commit/ad5d7b64fa68875ad4a27c0f45c78c59a332b7be.patch

Thank you, signed the CLA.

**Comment by jrodewig** [comment]
@elasticmachine ok to test

**Comment by jrodewig** [comment]
Thanks @Navanit-git. I'd like to get a review from the @elastic/es-security team before merging this in.

The [Encrypt HTTP client communications for Kibana][0] section indicates you should encrypt browser⇆Kibana traffic before securing Elasticsearch⇆Kibana traffic:

> ... You encrypt traffic between your browser and Kibana, and then encrypt traffic between Kibana and Elasticsearch.

However, I'm not 100% sure that the order matters. If it doesn't, I'd stick with the existing order and update the preceding text. [Encrypt traffic between Kibana and Elasticsearch][1] references a `elasticsearch-ca.pem` file that's generated in the [Encrypt HTTP client communications][2] section. The current order keeps these sections closer to each other.

[0]: https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-basic-setup-https.html#encrypt-kibana-http
[1]: https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-basic-setup-https.html#encrypt-kibana-elasticsearch
[2]: https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-basic-setup-https.html#encrypt-http-communication

**Comment by jrodewig** [comment]
@elasticmachine update branch

**Comment by Navanit-git** [comment]
@jkakavas @elastic/es-security

**Comment by tvernum** [comment]
> However, I'm not 100% sure that the order matters. If it doesn't, I'd stick with the existing order and update this text instead. 

I think your proposal is best @jrodewig.

Security auto-configuration sets up encryption between Kibana & ES, but not between the Browser & Kibana. (This is by design, due to the implications for using untrusted CAs in browser based communication).

So, most new users will find that encryption between Kibana&ES is already done for them, and any advice that implies they should do Browser&Kibana first will be confusing.

**Comment by Navanit-git** [comment]
> > However, I'm not 100% sure that the order matters. If it doesn't, I'd stick with the existing order and update this text instead.
> 
> I think your proposal is best @jrodewig.
> 
> Security auto-configuration sets up encryption between Kibana & ES, but not between the Browser & Kibana. (This is by design, due to the implications for using untrusted CAs in browser based communication).
> 
> So, most new users will find that encryption between Kibana&ES is already done for them, and any advice that implies they should do Browser&Kibana first will be confusing.

Thankyou for the suggestions but it become more confusing in the above line where it is written and I quote "You encrypt traffic between your browser and Kibana, and then encrypt traffic between Kibana and Elasticsearch."

**Comment by jrodewig** [comment]
Thanks @tvernum. I've pushed https://github.com/elastic/elasticsearch/pull/84237/commits/078309698e9f000934295cdd761563c3bfa399dc to address.

@Navanit-git I think https://github.com/elastic/elasticsearch/pull/84237/commits/078309698e9f000934295cdd761563c3bfa399dc addresses your concerns. Let me know if not. Thanks!

**Comment by jrodewig** [comment]
@elasticmachine update branch

**Comment by Navanit-git** [comment]
> Thanks @tvernum. I've pushed [0783096](https://github.com/elastic/elasticsearch/commit/078309698e9f000934295cdd761563c3bfa399dc) to address.
> 
> @Navanit-git I think [0783096](https://github.com/elastic/elasticsearch/commit/078309698e9f000934295cdd761563c3bfa399dc) addresses your concerns. Let me know if not. Thanks!

yes @jrodewig Thank you. Kindly merge it and if possible approve it.

**Review by jrodewig — APPROVED** [review]
LGTM. Thanks @Navanit-git.

**Comment by jrodewig** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|master|[](https://github.com/elastic/elasticsearch/pull/84386)|
|✅|8.1|[](https://github.com/elastic/elasticsearch/pull/84387)|
|✅|8.0|[](https://github.com/elastic/elasticsearch/pull/84388)|


### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
