### PR TITLE
Reindex: Fixed typo in assertion failure message

### PR DESCRIPTION
**Pull request by ashashwat**
Fix a typo in an assertion failure message.

### CODE REVIEW

**Comment by nik9000** [comment]
Thanks for fixing it @ashashwat!

@elasticmachine, test this please

**Comment by nik9000** [comment]
@ashashwat I believe there is actually a type in the production code too. The tests now fail with:
```
org.junit.ComparisonFailure: expected:<...line] as a query par[am]eter. Specify it in ...> but was:<...line] as a query par[ma]eter. Specify it in ...>
```

I believe you can reproduce it with:
```
./gradlew :modules:reindex:test -Dtests.seed=8A50475951076F01 -Dtests.class=org.elasticsearch.index.reindex.RestReindexActionTests -Dtests.method="testPipelineQueryParameterIsError" -Dtests.security.manager=true -Dtests.locale=fr-CA -Dtests.timezone=America/Argentina/Buenos_Aires
```

Would you like to fix the production code as well?

**Comment by ashashwat** [comment]
@nik9000 Is it ok if I squash these commits in my branch?

**Comment by nik9000** [comment]
Thanks again @ashashwat! I've merged your fix to master and backported to 6.x.

**Pull request merged**
