### PR TITLE
Cat health supports ts=0 option

### LINKED ISSUE #10109: cat health not respecting 'ts' parameter
The _cat/health endpoint [is documented](http://www.elastic.co/guide/en/elasticsearch/reference/current/cat-health.html) that the timestamp can be disabled in the output. This is not working for me in 1.4.4:

```
$ curl localhost:9200
{
  "status" : 200,
  "name" : "lb-1",
  "cluster_name" : "es-example-service",
  "version" : {
    "number" : "1.4.4",
    "build_hash" : "c88f77ffc81301dfa9dfd81ca2232f09588bd512",
    "build_timestamp" : "2015-02-19T13:05:36Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.3"
  },
  "tagline" : "You Know, for Search"
} 

$ curl 'localhost:9200/_cat/health?v'
epoch      timestamp cluster            status node.total node.data shards pri relo init unassign 
1426529705 18:15:05  es-example-service green           7         3      0   0    0    0        0 

$ curl 'localhost:9200/_cat/health?v&ts=0'
epoch      timestamp cluster            status node.total node.data shards pri relo init unassign 
1426529713 18:15:13  es-example-service green           7         3      0   0    0    0        0
```

### PR DESCRIPTION
**Pull request by johtani**
If ts=0, cat health disable epoch and timestamp
 Add rest-api test and test

Closes #10109

### CODE REVIEW

**Comment by nik9000** [comment]
Sorry for the super late review. This makes sense to me but it isn't what @drewr asked for in #10109. I'm fine with it because it is better though. `ts=0` always silences timestamps if they are added but `ts=true` doesn't add them if they aren't already there.

If we are going to go with a change like this I'd replace the strings `"timestamp"` and `"epoch"` in the equals check with a constant. Its not like we're likely to rename them but it would still make it more obvious that those fields are *special*.

I don't think it'd be much harder to do with @drewr wanted though - to remove the time from RestHealthAction and add it to RestTable. Then you'd have to construct the rest table with a boolean telling it whether or not timestamp should default to shown (_cat/health) or hidden (everything else).

**Comment by clintongormley** [comment]
@johtani any plans on revisiting this?

**Comment by johtani** [comment]
@nik9000 @clintongormley I will try to generalize the time. I will change ["Table" class](https://github.com/elastic/elasticsearch/blob/9430e17f707bde61418f31d1b080ed087ed4cd4c/core/src/main/java/org/elasticsearch/common/Table.java)

**Comment by johtani** [comment]
@nik9000 Rebased and fixed some test issue.
And the time move to Table class with ''startHeadersWithTimestamp".
Can you review again?

**Comment by dakrone** [comment]
Pinging @nik9000 again for review

**Comment by nik9000** [comment]
I like it! If we push all the APIs over to returning timestamp we can rename the method back to `startHeaders` but this gets us a migration path. LGTM.

**Pull request merged**
