### PR TITLE
Fix multithreading copies in lib vec

### PR DESCRIPTION
**Pull request by ChrisHegarty**
This commit fixes a potential multithreading issue with the lib vec vector scorer. 

Since the implementation falls back to a lucene scorer which needs to read from the index input, then we need to make a copy of the index input. Otherwise, there is a potential for the stateful index input to be accessed across threads - which would be bad.

The fallback is only used when one or other vector cross a segment boundary, which is 16G by default. So the likelihood of this occurring in practice is small, but the affect is bad. 

The fix is deliberately small and targeted, so that it can be backported. After this change, I'm going to drop the custom VectorScorer and adapter type, in favour of using the Lucene type directly. This custom types were initially used when the code lived inside the native module, where we didn't want to add a dependency on Lucene directly.

### CODE REVIEW

**Review by jimczi — APPROVED** [review]
LGTM

**Comment by ChrisHegarty** [comment]
@elasticmachine update branch

**Comment by ChrisHegarty** [comment]
@elasticmachine update branch

**Comment by ChrisHegarty** [comment]
@elasticmachine update branch

**Comment by ChrisHegarty** [comment]
@elasticmachine update branch

**Comment by ChrisHegarty** [comment]
@elasticmachine update branch

**Comment by ChrisHegarty** [comment]
@elasticmachine run elasticsearch-ci/bwc-snapshots

**Comment by ChrisHegarty** [comment]
@elasticmachine update branch

**Comment by ChrisHegarty** [comment]
@elasticmachine update branch

**Comment by ChrisHegarty** [comment]
@elasticmachine update branch

**Pull request merged**
