### PR TITLE
Avoid listener call under SparseFileTracker#mutex

### LINKED ISSUE #61520: SparseFileTracker sometimes notifies listener under mutex
In #58477 we introduced a more eager notification mechanism for listeners of ranges of sparse files, but unfortunately these changes now mean we sometimes notify listeners (and therefore perform IO) while holding `SparseFileTracker#mutex`.

Spotted while working on something else, and it will be a bit involved to fix, so I'm opening an issue so we don't forget about it.

### PR DESCRIPTION
**Pull request by DaveCTurner**
Today we sometimes notify a listener of completion while holding
`SparseFileTracker#mutex`. This commit move all such calls out from
under the mutex and adds assertions that the mutex is not held in the
listener.

Closes #61520

### CODE REVIEW

**Comment by DaveCTurner** [comment]
Sorry reviewers I had a change of heart after opening this, I prefer the approach in 752e0a8.

**Review by tlrx — APPROVED** [review]
LGTM - Thanks for fixing this David!

**Review by fcofdez — APPROVED** [review]
LGTM 👍

**Comment by DaveCTurner** [comment]
Thanks both!

**Pull request merged**
