### PR TITLE
[Docs]  Semantic field does not support object fields

### PR DESCRIPTION
**Pull request by carlosdelest**
Clarify in docs that semantic_text fields are not currently supported in object fields

### CODE REVIEW

**Review by jimczi — CHANGES_REQUESTED** [review]
What's preventing the field to work inside object fields? We fail if the field is under a `nested` object but normal objects should work fine. We have tests for this.

**Comment by carlosdelest** [comment]
@jimczi

> What's preventing the field to work inside object fields? We fail if the field is under a nested object but normal objects should work fine.

We're not overwriting correctly the object when calculating the inference. The following sequence:

```json
PUT test_semantic

PUT /test_semantic/_mapping
{
  "properties": {
    "level_1": {
      "properties": {
        "level_2": {
          "type": "semantic_text",
          "inference_id": "elser-endpoint"
        }
      }
    }
  }
}

POST test_semantic/_doc/0001
{
  "level_1": {
    "level_2": "text"
  }
}
```

results in an error:

```json
{
  "error": {
    "root_cause": [
      {
        "type": "document_parsing_exception",
        "reason": "[1:29] failed to parse field [level_1.level_2] of type [semantic_text] in document with id '0001'. Preview of field's value: 'null'"
      }
    ],
    "type": "document_parsing_exception",
    "reason": "[1:29] failed to parse field [level_1.level_2] of type [semantic_text] in document with id '0001'. Preview of field's value: 'null'",
    "caused_by": {
      "type": "illegal_argument_exception",
      "reason": "[1:29] [semantic_text] Expected START_OBJECT but was: END_OBJECT"
    }
  },
  "status": 400
}
```

I've been able to reproduce this locally.

> We have tests for this.

 We have tests for copy_to from object fields to (non-object) semantic fields [here](https://github.com/elastic/elasticsearch/blob/d880c76fad39333cae24ad2a3169b7495dcacb95/x-pack/plugin/inference/src/yamlRestTest/resources/rest-api-spec/test/inference/60_semantic_text_inference_update.yml#L185). I haven't found object tests on the [inference tests](https://github.com/elastic/elasticsearch/blob/0cc05448c3f1ae5e1e13ec7b4d110393982f7db4/x-pack/plugin/inference/src/yamlRestTest/resources/rest-api-spec/test/inference/30_semantic_text_inference.yml#L1-L0).

**Comment by jimczi** [comment]
Oh that's a bug then! We should account for objects [here](https://github.com/elastic/elasticsearch/blob/e221c0357eff9d311bd67b1a4b4f15e02b6cf030/x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/action/filter/ShardBulkInferenceActionFilter.java#L400)?

**Comment by carlosdelest** [comment]
> Oh that's a bug then! We should account for objects [here](https://github.com/elastic/elasticsearch/blob/e221c0357eff9d311bd67b1a4b4f15e02b6cf030/x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/action/filter/ShardBulkInferenceActionFilter.java#L400)?

👍 That is correct.

**Comment by jimczi** [comment]
We have tests [here](https://github.com/elastic/elasticsearch/blob/e221c0357eff9d311bd67b1a4b4f15e02b6cf030/x-pack/plugin/inference/src/test/java/org/elasticsearch/xpack/inference/mapper/SemanticTextFieldMapperTests.java#L509) but they don't use the action filter.

**Comment by carlosdelest** [comment]
I'm closing this in favour of opening a GH bug

**Pull request closed without merging**
