### PR TITLE
Update min CCS version for 8.14 release

### PR DESCRIPTION
**Pull request by thecoop**
Manually update min CCS version for the 8.14 release

### CODE REVIEW

**Comment by thecoop** [comment]
@quux00 Updating the min CCS version breaks `TransportResolveClusterActionTests.testCCSCompatibilityCheck`, and I'm not quite sure what the code [here](https://github.com/elastic/elasticsearch/blob/c252b40ea63aa764c4a88e12d37f1e51af9af768/server/src/main/java/org/elasticsearch/action/admin/indices/resolve/TransportResolveClusterAction.java#L188) is doing. Can you provide some more info on how this needs to be modified?

**Comment by quux00** [comment]
@thecoop Sorry about that. The patch below should fix it. I've changed it to act more like the ccs compatibility test in TransportSearchActionTests. I've also fixed a few other minor nits in this patch. Let me know if you want me to do this patch in a separate ticket or if you want to fold it into this ticket.

```diff
diff --git a/server/src/test/java/org/elasticsearch/action/admin/indices/resolve/TransportResolveClusterActionTests.java b/server/src/test/java/org/elasticsearch/action/admin/indices/resolve/TransportResolveClusterActionTests.java
index 2604461d124..2a64fbad975 100644
--- a/server/src/test/java/org/elasticsearch/action/admin/indices/resolve/TransportResolveClusterActionTests.java
+++ b/server/src/test/java/org/elasticsearch/action/admin/indices/resolve/TransportResolveClusterActionTests.java
@@ -10,7 +10,6 @@ package org.elasticsearch.action.admin.indices.resolve;
 
 import org.elasticsearch.TransportVersion;
 import org.elasticsearch.TransportVersions;
-import org.elasticsearch.action.fieldcaps.TransportFieldCapabilitiesActionTests;
 import org.elasticsearch.action.support.ActionFilter;
 import org.elasticsearch.action.support.ActionFilters;
 import org.elasticsearch.action.support.PlainActionFuture;
@@ -50,27 +49,29 @@ public class TransportResolveClusterActionTests extends ESTestCase {
 
     public void testCCSCompatibilityCheck() {
         Settings settings = Settings.builder()
-            .put("node.name", TransportFieldCapabilitiesActionTests.class.getSimpleName())
+            .put("node.name", TransportResolveClusterActionTests.class.getSimpleName())
             .put(SearchService.CCS_VERSION_CHECK_SETTING.getKey(), "true")
             .build();
         ActionFilters actionFilters = mock(ActionFilters.class);
         when(actionFilters.filters()).thenReturn(new ActionFilter[0]);
-        TransportVersion transportVersion = TransportVersionUtils.getNextVersion(TransportVersions.MINIMUM_CCS_VERSION, true);
+        TransportVersion nextTransportVersion = TransportVersionUtils.getNextVersion(TransportVersions.MINIMUM_CCS_VERSION, true);
         try {
             TransportService transportService = MockTransportService.createNewService(
                 Settings.EMPTY,
                 VersionInformation.CURRENT,
-                transportVersion,
+                nextTransportVersion,
                 threadPool
             );
 
             ResolveClusterActionRequest request = new ResolveClusterActionRequest(new String[] { "test" }) {
                 @Override
                 public void writeTo(StreamOutput out) throws IOException {
-                    super.writeTo(out);
-                    if (out.getTransportVersion().before(transportVersion)) {
-                        throw new IllegalArgumentException("This request isn't serializable before transport version " + transportVersion);
-                    }
+                    throw new UnsupportedOperationException(
+                        "ResolveClusterAction requires at least Transport Version "
+                            + TransportVersions.RESOLVE_CLUSTER_ENDPOINT_ADDED.toReleaseVersion()
+                            + " but was "
+                            + out.getTransportVersion().toReleaseVersion()
+                    );
                 }
             };
             ClusterService clusterService = new ClusterService(
```

**Comment by thecoop** [comment]
@quux00 Thanks, I've just applied it here. Test all works, thanks a lot!

**Review by ldematte — APPROVED** [review]
👍

**Pull request merged**
