### PR TITLE
Pass Executor into request handlers

### PR DESCRIPTION
**Pull request by DiannaHohensee**
Pass an Executor into RequestHandleRegistry#registerRequestHandler
calls instead of a String. Ultimately the String executor name passed
through and stashed internally is converted by the ThreadPool into an
Executor on which to execute tasks.

Related to #97879.

### CODE REVIEW

**Review by DaveCTurner — COMMENTED** [review]
Great, thanks for splitting this change out. Doesn't quite pass `./gradlew precommit` yet (spotless, and a handful of trivial test compile errors) and I'm not sure why CI hasn't started to run here either.

**Comment by DiannaHohensee** [comment]
@elasticmachine retest this please

**Comment by DiannaHohensee** [comment]
@elasticmachine retest this please

**Review by DaveCTurner — APPROVED** [review]
LGTM; I think the bwc tests failed because you lost the race against the backport of https://github.com/elastic/elasticsearch/pull/98866 so should pass if you merge latest `main` again.

**Pull request merged**
