### PR TITLE
[Security Solution] Allow `write`, `auto_configure` privileges for `kibana_system` role on endpoint response index

### PR DESCRIPTION
**Pull request by ashokaditya**
Updates privileges for `.logs-endpoint.action.responses-*` index pattern to match privileges for `.logs-endpoint.actions-*` index pattern. The `write` and `auto_configure` privileges are required so that Kibana can write to the response index for third party agents.

### CODE REVIEW

**Review by kc13greiner — APPROVED** [review]
LGTM!

reason: Typically the `kibana_system` user is only allowed `read` access to system indexes not owned by Kibana, however, there is an exception for indexes such as `.logs-endpoint.responses-*`

**Comment by ashokaditya** [comment]
@elasticsearchmachine merge upstream

**Comment by ashokaditya** [comment]
@elasticmachine update branch

**Review by paul-tavares — APPROVED** [review]
thanks Ash for getting this through.

**Pull request merged**
