### PR TITLE
Don't start reindex unless destination index exists

### PR DESCRIPTION
**Pull request by nik9000**
This isn't the same thing "don't reindex create indexes". We don't
have an easy way to prevent index operations from creating indexes
yet and I'm not sure this is important enough to add one. We _can_
do so if we think it is important to prevent reindex from _ever_
creating indexes.

As it stands reindex can create indexes if the index is deleted
after the reindex starts. In can also create indexes if you use
a script to change the destination index.

### CODE REVIEW

**Comment by nik9000** [comment]
Relates to #20465.

I marked this as discuss because:
1. I want to know how far to take this. I could go further and prevent reindex from ever creating new indexes by adding an option to `IndexRequest` and using it. I didn't do that in the first iteration of this because I want to see if we think this is good enough.
2. I want to know if we think we should do this in 5.x and 5.0 as well.

**Comment by jpountz** [comment]
Should we just rely on `action.auto_create_index`? I could be wrong, but I have the feeling that users who do not want reindex to create indices are the same users who don't want index operations to create indices in general?

**Comment by nik9000** [comment]
> Should we just rely on `action.auto_create_index`?

I thought is was OK to do so, but we keep getting issues like #20465 where people don't like that reindex automatically created the index. Maybe we should just improve the documentation? It is convenient to rely on `action.auto_create_index` both from a technical standpoint and a testing standpoint.

**Comment by jpountz** [comment]
I like fixing it through documentation better than adding a new flag to index requests.

**Comment by clintongormley** [comment]
> I like fixing it through documentation better than adding a new flag to index requests.

I feel the same way, but...

>  I have the feeling that users who do not want reindex to create indices are the same users who don't want index operations to create indices in general?

I think there are going to be a lot of users cancelling reindexes because they've forgotten to create the new mappings ahead of time.  Been there done that.

**Pull request closed without merging**
