### PR TITLE
Squash o.e.rest.action.admin.cluster

### PR DESCRIPTION
**Pull request by nik9000**
In an effort to reduce the number of tiny packages we have in the
code base this moves all the files that were in subdirectories of
`org.elasticsearch.rest.action.admin.cluster` into
`org.elasticsearch.rest.action.admin.cluster`.

Also squashes `org.elasticsearch.rest.support` into `org.elasticsearch.rest`.

Also fixes line length in these packages.

### CODE REVIEW

**Comment by nik9000** [comment]
Removes another 20 or so packages.

**Comment by nik9000** [comment]
Found something missing. One moment.

**Comment by nik9000** [comment]
> Found something missing. One moment.

Pushed another commit. Should be ok for review.

**Comment by rjernst** [comment]
LGTM

**Pull request merged**
