### PR TITLE
HLRC: Use nonblocking entity for requests

### PR DESCRIPTION
**Pull request by hub-cap**
Previously the HLRC used a blocking ByteArrayEntity, but the Request
class also allows to set a NByteArrayEntity, and defaults to nonblocking
when calling the createJsonEntity method. This commit cleans up all the
uses of ByteArrayEntity in the RequestConverters to use the nonblocking
entity.

### CODE REVIEW

**Review by nik9000 — APPROVED** [review]
Yeah! That is better. I wonder if we should forbid these classes?

**Review by javanna — APPROVED** [review]
LGTM thanks for catching and fixing. I have fixed in a few places in the past but it's something that I keep forgetting myself here and there. I would be in favour of forbidding these classes.

**Comment by hub-cap** [comment]
I went ahead and added the ByteArrayEntity to the forbidden apis'. Were there other classes i should add as well?

**Comment by hub-cap** [comment]
Just getting around to this, ill go ahead and add StringEntity and clean up any uses of it before merging.

**Comment by javanna** [comment]
@hub-cap feel like merging this one? ;)

**Review by nik9000 — APPROVED** [review]
:heart:

**Pull request merged**
