### PR TITLE
Update Gradle wrapper to 6.4

### PR DESCRIPTION
**Pull request by mark-vieira**
The usual update to the latest Gradle release. This one includes a long awaited fix for forking Scala compilation (https://github.com/gradle/gradle/issues/10685) which will allow elasticsearch-hadoop to finally upgrade to the latest version of our build-tools.

### CODE REVIEW

**Comment by mark-vieira** [comment]
@elasticmachine update branch

**Comment by mark-vieira** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by mark-vieira** [comment]
@elasticmachine update branch

**Comment by mark-vieira** [comment]
@elasticmachine update branch

**Review by breskeby — APPROVED** [review]
lgtm

**Pull request merged**
