### PR TITLE
Add document _count API support to Rest High Level Client. 

### PR DESCRIPTION
**Pull request by mrdjen**
At the moment there are no CountRequest and CountResponse classes, and RestCountAction will return SearchResponse with XContent generated dynamically (inline).
CountRequest and CountResponse are added to HL Rest Client.
CountRequest aggregates SearchRequest and exposes relevant methods to user of CountRequest, and delegates these to the counterparts in SearchRequest.
CountResponse, on the contrary has no relationship with SearchResponse, instead CountResponse will reuese relevant members (SearchShardFailures).
Relates to #27205 
@javanna

### CODE REVIEW

**Comment by hub-cap** [comment]
Oh my im quite sorry, this slipped thru my email filter. Ill be looking at it tomorrow. Sorry @mrdjen !!!

**Comment by hub-cap** [comment]
@mrdjen This is more of a generalized question, so im not going to leave it on the review. Ive decided to wait for a more thorough review until we've sorted this out.

It looks like the `SearchRequest` itself can be used in almost all of the places its currently wrapped. Did you consider not creating a `CountRequest` and just creating and using the `CountResponse::fromXContent` for the RestHighLevelClient? It would appear to me at first glance that if you had a RequestConverter method that took in the `SearchRequest` and added `_count` to the end of that request, that the only additional item to be built would be the `CountResponse::fromXContent`. What do you think of that, instead?

**Comment by mrdjen** [comment]
Hey thanks for response @hub-cap , and no worries about delay, contributors guide says "sit back and wait" :)

Yes its possible to use `SearchRequest` instead of `CountRequest`, still, here's my reasoning for adding `CountRequest`
- as enduser of API I'd expect to send a `CountRequest` to `_count ` endpoint (and believe HL client is more or less rather consistent)
- there are params in `SearchRequest` which are not used in `CountRequest` (and believe because of that should not be exposed to the enduser)
- its easy to hit autocomplete in IDE and set a paramter that is not used
- if  we go with using `SearchRequest` with `_count` endpoint, do we have to describe which params if `SearchRequest` can be used with `_count`?

So in this context I added `CountRequest` - let me know what you think - and you might have different/better perspective than I do.

**Comment by hub-cap** [comment]
Ok, I went ahead and had a conversation with some members on the team that have some prior knowledge about the count API. So a while back we decided to remove the count API from being a TransportAction, since it did / does not need to be. Its effectively a search, like you said, but without the ability to set some things.

After looking at the PR, it would make more sense if we created an actual valid count request/response that is not only used by the client, but that is also used by the server. You gave some good reasons to do so above. So, if you would like to take it on, you can separate this into 2 PRs. The first PR should be the count request/response classes, and using them in the `RestCountAction` instead of the `SearchRequest` thats currently being used. The second PR, naturally, would be the rest of the work that you have already done here. 

I dont think that its a huge undertaking to put the count request/response into server, and get them used in the `RestCountAction`, and id be happy to help guide you if you have questions on that PR.

What do you think?

**Comment by mrdjen** [comment]
Thanks for response @hub-cap , yes I can create another PR with count request/response classes and use them in `RestCountAction.`

Asking from the top of my head - apart from moving these to server (and then using them in `RestCountAction` and HL client), do you have any other comments on their structure or relationship with `SearchReqest` and `SearchResponse?`

**Comment by hub-cap** [comment]
Id say start out leaving them separate and see how different they end up looking. If after an iteration or two it looks like its similar enough, we can talk about just using a `SearchRequest` as internal state. 

<3 for the contribution!

**Comment by mrdjen** [comment]
Hi @hub-cap see the referenced PR #32711 as part one - moving `CountRequest` and `CountResponse` to server and using them in `RestCountAction,` let me know what you think, Thanks.

**Comment by hub-cap** [comment]
@mrdjen we can close this right?

**Comment by mrdjen** [comment]
Right, closing it now @hub-cap 
Thanks

**Pull request closed without merging**
