### PR TITLE
Add ClassWriter to Painless writing pass

### PR DESCRIPTION
**Pull request by jdconrad**
This the first part of a series to allow nodes to write all of their appropriate pieces to the class. Currently, nodes must add their bindings, constants, and functions to main SClass node for delayed writing. This instead adds a Painless version of ClassWriter to the write pass.  The Painless ClassWriter contains an appropriate ClassVisitor that can be accessed in any node during the process along with access to the clinit method, and finally a shortcut for creating new MethodWriter. The next step will be removing the delayed writing in SClass, and instead, delegate all writing responsibilities to the nodes.

Note this PR looks huge, but the important changes are to SClass, SFunction and the new ClassWriter. Everything else is mechanical to make the signatures appropriate for the write pass moving forward.

### CODE REVIEW

**Comment by jdconrad** [comment]
@elasticmachine test this please

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by jdconrad** [comment]
@rjernst Thanks for the review! Will commit as soon as CI passes.

**Comment by jdconrad** [comment]
@elasticmachine test this please

**Comment by jdconrad** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by jdconrad** [comment]
@elasticmachine run elasticsearch-ci/default-distro

**Pull request merged**
