### PR TITLE
[Inference API] Use randomOtherValueThan to avoid potential flaky PutInferenceModelResponseTests

### PR DESCRIPTION
**Pull request by timgrein**
Same reasoning as in https://github.com/elastic/elasticsearch/pull/109857

### CODE REVIEW

**Comment by timgrein** [comment]
@elasticmachine update branch

**Review by davidkyle — APPROVED** [review]
LGTM

**Comment by timgrein** [comment]
@elasticmachine update branch

**Comment by timgrein** [comment]
@elasticmachine update branch

**Pull request merged**
