### PR TITLE
Add retention to Snapshot Lifecycle Management

### PR DESCRIPTION
**Pull request by dakrone**
This commit adds retention to the existing Snapshot Lifecycle Management feature (#38461) as described in #43663. This allows a user to configure SLM to automatically delete older snapshots based on a number of criteria.

An example policy would look like:

```
PUT /_slm/policy/snapshot-every-day
{
  "schedule": "0 30 2 * * ?",
  "name": "<production-snap-{now/d}>",
  "repository": "my-s3-repository",
  "config": {
    "indices": ["foo-*", "important"]
  },
  // Newly configured retention options
  "retention": {
    // Snapshots should be deleted after 14 days
    "expire_after": "14d",
    // Keep a maximum of thirty snapshots
    "max_count": 30,
    // Keep a minimum of the four most recent snapshots
    "min_count": 4
  }
}
```

SLM Retention is run on a scheduled configurable with the `slm.retention_schedule` setting, which supports cron expressions. Deletions are run for a configurable time bounded by the `slm.retention_duration` setting, which defaults to 1 hour.

Included in this work is a new SLM stats API endpoint available through

``` json
GET /_slm/stats
```

That returns statistics about snapshot taken and deleted, as well as successful retention runs, failures, and the time spent deleting snapshots. #45362 has more information as well as an example of the output. These stats are also included when retrieving SLM policies via the API.

### CODE REVIEW

**Comment by jasontedor** [comment]
I think this PR is way too large, and could be split into several smaller ones. For example, integrating with the high-level REST client could be a separate change. Large PRs are incredibly hard to review, I think we all start to lose focus after even a few hundred lines. I also notice there ends up being smaller changes mixed in, for example, the TimeValue change is worth lifting to its own small change, and letting the core/infra team review.

**Comment by gwbrown** [comment]
It's worth noting that this is merging a feature branch, and all the changes have been reviewed as part of smaller PRs. I believe the smaller changes impacting things owned by other areas teams were reviewed by the appropriate team at the time, but we can double-check.

**Comment by jasontedor** [comment]
Okay, thanks for clarifying. That was not clear from the description at all.

**Comment by dakrone** [comment]
I apologize, I should have clarified that more in the PR description. I was writing it to be as close to a commit message as possible for the squash commit and left that out.

**Review by AthenaEryma — APPROVED** [review]
LGTM

**Pull request merged**
