### PR TITLE
indices.open takes a list of indices

### PR DESCRIPTION
**Pull request by Mpdreamz**
not single index

### CODE REVIEW

**Comment by javanna** [comment]
LGTM seems like we have no REST tests using a comma separated list of indices though, shall we add a quick one?

**Comment by Mpdreamz** [comment]
+1 but I rather sent another PR for it, want to get the doc changes in master and 2.x before GA :)

**Comment by Mpdreamz** [comment]
+1 but I rather sent another PR for it, want to get the doc changes in master and 2.x before GA :)

**Comment by Mpdreamz** [comment]
merged to master and cherry-picked to `2.0`. `2.1`, `2.x`.

**Pull request merged**
