### PR TITLE
get tests working on java 9

### LINKED ISSUE #10145: master/1.x branch does not compile with java9
master works fine. Maybe there is a real bug here, e.g. wildcard imports, and a new class in java9 causes a conflict? This is why i hate wildcard imports :)

Otherwise it could be a compiler bug or something:

main:
     [echo] Using OpenJDK Runtime Environment 1.9.0-internal-rmuir_2015_03_18_00_27-b00 Oracle Corporation
[INFO] Executed tasks
[INFO] 
[INFO] --- maven-antrun-plugin:1.7:run (invalid-patterns) @ elasticsearch ---
[INFO] Executing tasks

main:
[INFO] Executed tasks
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.2:create (default) @ elasticsearch ---
[INFO] Checking for local modifications: skipped.
[INFO] Updating project files from SCM: skipped.
[INFO] Executing: /bin/sh -c cd /home/rmuir/workspace/elasticsearch && git rev-parse --verify HEAD
[INFO] Working directory: /home/rmuir/workspace/elasticsearch
[INFO] Storing buildNumber: 78b5a6a7fc6caa61e1af9fb67e9a2ec2df4f831f at timestamp: 1426705014243
[INFO] Executing: /bin/sh -c cd /home/rmuir/workspace/elasticsearch && git rev-parse --verify HEAD
[INFO] Working directory: /home/rmuir/workspace/elasticsearch
[INFO] Storing buildScmBranch: UNKNOWN
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ elasticsearch ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] Copying 5 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ elasticsearch ---
[INFO] Compiling 3171 source files to /home/rmuir/workspace/elasticsearch/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/rmuir/workspace/elasticsearch/src/main/java/org/elasticsearch/common/inject/Scopes.java:[112,23] error: method scope in interface Scope cannot be applied to given types;
[ERROR]   required: Key<T#1>,Provider<T#1>
  found: Key<T#2>,ProviderToInternalFactoryAdapter<CAP#1>
  reason: inferred type does not conform to equality constraint(s)
    inferred: CAP#1
    equality constraints(s): CAP#1,T#2
  where T#1,T#2 are type-variables:
    T#1 extends Object declared in method <T#1>scope(Key<T#1>,Provider<T#1>)
    T#2 extends Object declared in method <T#2>scope(Key<T#2>,InjectorImpl,InternalFactory<? extends T#2>,Scoping)
  where CAP#1 is a fresh type-variable:
    CAP#1 extends T#2 from capture of ? extends T#2
/home/rmuir/workspace/elasticsearch/src/main/java/org/elasticsearch/common/collect/Iterators2.java:[34,63] error: incompatible types: PeekingIterator<CAP#1> cannot be converted to PeekingIterator<T>
[ERROR]   where T is a type-variable:
    T extends Object declared in method <T>deduplicateSorted(Iterator<? extends T>,Comparator<? super T>)
  where CAP#1 is a fresh type-variable:
    CAP#1 extends T from capture of ? extends T
/home/rmuir/workspace/elasticsearch/src/main/java/org/elasticsearch/common/inject/util/Modules.java:[92,58] error: incompatible types: ImmutableSet<CAP#1> cannot be converted to Set<Module>
[ERROR]   where CAP#1 is a fresh type-variable:
    CAP#1 extends Module from capture of ? extends Module
/home/rmuir/workspace/elasticsearch/src/main/java/org/elasticsearch/common/inject/util/Modules.java:[123,50] error: incompatible types: ImmutableSet<CAP#1> cannot be converted to ImmutableSet<Module>
[INFO] 4 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 26.162 s
[INFO] Finished at: 2015-03-18T14:57:07-05:00
[INFO] Final Memory: 23M/531M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project elasticsearch: Compilation failure: Compilation failure:
[ERROR] /home/rmuir/workspace/elasticsearch/src/main/java/org/elasticsearch/common/inject/Scopes.java:[112,23] error: method scope in interface Scope cannot be applied to given types;
[ERROR] required: Key<T#1>,Provider<T#1>
[ERROR] found: Key<T#2>,ProviderToInternalFactoryAdapter<CAP#1>
[ERROR] reason: inferred type does not conform to equality constraint(s)
[ERROR] inferred: CAP#1
[ERROR] equality constraints(s): CAP#1,T#2
[ERROR] where T#1,T#2 are type-variables:
[ERROR] T#1 extends Object declared in method <T#1>scope(Key<T#1>,Provider<T#1>)
[ERROR] T#2 extends Object declared in method <T#2>scope(Key<T#2>,InjectorImpl,InternalFactory<? extends T#2>,Scoping)
[ERROR] where CAP#1 is a fresh type-variable:
[ERROR] CAP#1 extends T#2 from capture of ? extends T#2
[ERROR] /home/rmuir/workspace/elasticsearch/src/main/java/org/elasticsearch/common/collect/Iterators2.java:[34,63] error: incompatible types: PeekingIterator<CAP#1> cannot be converted to PeekingIterator<T>
[ERROR] where T is a type-variable:
[ERROR] T extends Object declared in method <T>deduplicateSorted(Iterator<? extends T>,Comparator<? super T>)
[ERROR] where CAP#1 is a fresh type-variable:
[ERROR] CAP#1 extends T from capture of ? extends T
[ERROR] /home/rmuir/workspace/elasticsearch/src/main/java/org/elasticsearch/common/inject/util/Modules.java:[92,58] error: incompatible types: ImmutableSet<CAP#1> cannot be converted to Set<Module>
[ERROR] where CAP#1 is a fresh type-variable:
[ERROR] CAP#1 extends Module from capture of ? extends Module
[ERROR] /home/rmuir/workspace/elasticsearch/src/main/java/org/elasticsearch/common/inject/util/Modules.java:[123,50] error: incompatible types: ImmutableSet<CAP#1> cannot be converted to ImmutableSet<Module>
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

### PR DESCRIPTION
**Pull request by rmuir**
Fix build for java9.
- add compiler workarounds for java 9 (compiler bug, JI-9019884 filed for this)
- remove permgen specification during tests (this results in an error)

Fixes #10145

### CODE REVIEW

**Comment by s1monw** [comment]
LGTM I guess we need to drop the permgen space from the init scripts as well as some point since java 9 doesn't like it

**Comment by rmuir** [comment]
When running tests on java9 i hit IAE from java.util.concurrent.ThreadPoolExecutor.setCorePoolSize().

Maybe this should be fixed as a separate issue, but I have not seen it before.

Suite: org.elasticsearch.threadpool.UpdateThreadPoolSettingsTests
  1> [2015-03-23 17:52:16,761][INFO ][test                     ] Test testShutdownDownNowDoesntBlock(org.elasticsearch.threadpool.UpdateThreadPoolSettingsTests) started
  1> [2015-03-23 17:52:16,764][INFO ][test                     ] Test testShutdownDownNowDoesntBlock(org.elasticsearch.threadpool.UpdateThreadPoolSettingsTests) finished
  1> [2015-03-23 17:52:16,765][INFO ][test                     ] Test testScalingExecutorType(org.elasticsearch.threadpool.UpdateThreadPoolSettingsTests) started
  1> [2015-03-23 17:52:16,767][INFO ][test                     ] Test testScalingExecutorType(org.elasticsearch.threadpool.UpdateThreadPoolSettingsTests) finished
  1> [2015-03-23 17:52:16,767][INFO ][test                     ] Test testFixedExecutorType(org.elasticsearch.threadpool.UpdateThreadPoolSettingsTests) started
  1> [2015-03-23 17:52:16,769][INFO ][test                     ] Test testFixedExecutorType(org.elasticsearch.threadpool.UpdateThreadPoolSettingsTests) finished
  1> [2015-03-23 17:52:16,769][INFO ][test                     ] Test testCachedExecutorType(org.elasticsearch.threadpool.UpdateThreadPoolSettingsTests) started
  1> [2015-03-23 17:52:16,772][INFO ][test                     ] Test testCachedExecutorType(org.elasticsearch.threadpool.UpdateThreadPoolSettingsTests) finished
  1> [2015-03-23 17:52:16,772][INFO ][test                     ] Test testCustomThreadPool(org.elasticsearch.threadpool.UpdateThreadPoolSettingsTests) started
  1> [2015-03-23 17:52:16,777][ERROR][test                     ] FAILURE  : testCustomThreadPool(org.elasticsearch.threadpool.UpdateThreadPoolSettingsTests)
  1> REPRODUCE WITH  : mvn clean test -Dtests.seed=216A1B2C2D2B1E3C -Dtests.class=org.elasticsearch.threadpool.UpdateThreadPoolSettingsTests -Dtests.method="testCustomThreadPool" -Des.logger.level=INFO -Dtests.heap.size=512m -Dtests.locale=ru_RU -Dtests.timezone=America/Rankin_Inlet -Dtests.processors=8
  1> Throwable:
  1> java.lang.IllegalArgumentException
  1>     __randomizedtesting.SeedInfo.seed([216A1B2C2D2B1E3C:82BF82836AB18119]:0)
  1>     java.util.concurrent.ThreadPoolExecutor.setCorePoolSize(ThreadPoolExecutor.java:1541)
  1>     org.elasticsearch.threadpool.ThreadPool.rebuild(ThreadPool.java:345)
  1>     org.elasticsearch.threadpool.ThreadPool.updateSettings(ThreadPool.java:441)

**Comment by rmuir** [comment]
In java8, javadocs for this method look like:

Throws:
    IllegalArgumentException - if corePoolSize < 0

But in java9 its changed, we are hitting the second condition:

     * @throws IllegalArgumentException if {@code corePoolSize < 0}
     *         or {@code corePoolSize} is greater than the {@linkplain
     *         #getMaximumPoolSize() maximum pool size}

**Comment by rmuir** [comment]
I have no idea how to fix the code to dynamically increase threadpool sizes. 

With the new check, it seems impossible: setCorePoolSize complains if its > maximumPoolSize, but setMaximumPoolSize complains if its < corePoolSize. This check was added here: https://bugs.openjdk.java.net/browse/JDK-7153400

I feel like i'm losing my mind, maybe someone else can take a second look here?

**Comment by rmuir** [comment]
I guess, depending if we are growing or shrinking the pool, we have to do the code either:
    
    setMaximumPoolSize(x);
    setCorePoolSize(y);

or

    setCorePoolSize(y);
    setMaximumPoolSize(x);

This seems pretty crazy to me, i can't imagine its intended. Its just like ConcurrentMergeScheduler in lucene used to be.

**Comment by rmuir** [comment]
I fixed threadpool sizing with https://github.com/rmuir/elasticsearch/commit/88c3934af9f1b9b6c91de2092d5096500376efe9

Please have a look, I think its ready. All tests pass on java9 now:

[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 09:02 min
[INFO] Finished at: 2015-03-23T19:53:03-05:00
[INFO] Final Memory: 38M/1404M
[INFO] ------------------------------------------------------------------------

**Comment by rjernst** [comment]
LGTM

**Comment by rmuir** [comment]
> LGTM I guess we need to drop the permgen space from the init scripts as well as some point since java 9 doesn't like it

I don't think we are setting this anymore. We were only setting it for tests. I grepped for MaxPermSize and don't see it anywhere else, except dependency-reduced-pom.xml, which is under .gitignore?!

**Pull request closed without merging**
