### PR TITLE
fix: corrected example connected with rescore plugin

### PR DESCRIPTION
**Pull request by Arfey**
I had problems connected with `ExampleRescoreBuilder` example.
```
org.elasticsearch.gradle:build-tools = 7.5.1
gradle = 5.6.2
java = 12
```

Screen Shot 2020-01-13 at 17 06 46

this mr should fix that

### CODE REVIEW

**Comment by Arfey** [comment]
I passed CLA.

**Review by cbuescher — COMMENTED** [review]
Hi @Arfey, thanks for opening the PR. While opening up the constructors scope is straight forward and we can do so, may I ask where the code snippet you posted actually is located? The ExampleRescorePlugin in the example project shouldn't have problems accessing the ctor since its in the same package, so I assume you try writing your own plugin? If so, why would you need to use the ExampleRescoreBuilder rather than writing your own implementation?

**Comment by Arfey** [comment]
Hi, u a absolutely right, i write my own plugin.

The first step it's just create a package and copy-paste code from plugin from official repo for test. But without current fix plugin don't work. I spend some time to understand why this so and after that created mr to help other.

if u think that it's not problem or it's so trivial feel free to close this mr. 😅

**Review by cbuescher — APPROVED** [review]
No harm in changing this ctor in example project, LGTM

**Comment by cbuescher** [comment]
@elasticmachine test this please

**Comment by cbuescher** [comment]
@elasticmachine update branch

**Comment by cbuescher** [comment]
@elasticmachine test this please

**Pull request merged**
