### PR TITLE
Replace NestedChildrenQuery with ParentChildrenBlockJoinQuery

### PR DESCRIPTION
**Pull request by martijnvg**
PR for #24009 

Before this change if `NestedChildrenQuery` were to be cached it could lead to memory leak, because this query keeps a reference to the IndexReader. The chance that it would be cached is low, because this query is different for each search request and search hit it is trying to fetch inner hits for.

### CODE REVIEW

**Review by jpountz — APPROVED** [review]
Looks great!

**Comment by jpountz** [comment]
Should it be merged to 5.3.1? cc @clintongormley

**Comment by jpountz** [comment]
`ParentChildrenBlockJoinQuery` only exists in Lucene 6.5 but it should be easy to copy/paste if we wanted that change to be in Elasticsearch 5.3?

**Comment by martijnvg** [comment]
> ParentChildrenBlockJoinQuery only exists in Lucene 6.5 but it should be easy to copy/paste if we wanted that change to be in Elasticsearch 5.3?

If we are ok with backporting this to 5.3 branch, then I'll make it in a different pr.

**Comment by jpountz** [comment]
@martijnvg Can you update the description of this PR so that it better explains the bug it fixes?

> If we are ok with backporting this to 5.3 branch, then I'll make it in a different pr.

+1

**Comment by martijnvg** [comment]
@jpountz updated the description.

**Pull request merged**
