### PR TITLE
Recursive chown in init scripts

### PR DESCRIPTION
**Pull request by robin13**
For some usecases (e.g. mounting existing data into a docker container) recursive chown for the init script is useful.

### CODE REVIEW

**Comment by danielmitterdorfer** [comment]
LGTM, it's just odd that I see three commits in the PR but in the "files changed" it see only the changes from https://github.com/elastic/elasticsearch/pull/19207/commits/e21bea64cb41e1008db41729b0adbb46a0acec45. Can you please check why?

**Comment by robin13** [comment]
I guess a bad fork-merge path on my part... but the lines changed is what matter eh? :)

**Comment by robin13** [comment]
Jenkins test it

**Comment by jasontedor** [comment]
There's not really anything that CI will catch with this change because tests are limited here, I think that instead a test needs to be added to the packaging tests.

**Comment by jasontedor** [comment]
I think this pull request is broken, the diff stats show 1646 commits across 5165 files.

**Pull request closed without merging**
