### PR TITLE
Fixed the documentation of match boolean prefix query

### PR DESCRIPTION
**Pull request by amitmbm**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by amitmbm** [comment]
@cbuescher @markharwood could you please review it?

**Comment by amitmbm** [comment]
@cbuescher Could you please review the PR, or assign it to the correct person.

**Review by jrodewig — COMMENTED** [review]
I'd like to get @cbuescher's feedback, but I don't think these changes are quite accurate.

My understanding is that `match_bool_prefix` does ultimately translate into a `bool` query containing `term` clauses. However, the query string is analyzed first.

We suggest this in the [current text](https://www.elastic.co/guide/en/elasticsearch/reference/master/query-dsl-match-bool-prefix-query.html):

> A `match_bool_prefix` query **analyzes its input** and constructs a
[`bool` query](https://www.elastic.co/guide/en/elasticsearch/reference/master/query-dsl-bool-query.html) from the terms.

> where **analysis** produces the terms `quick`, `brown`, and `f` is similar to the
following `bool` query

Rather than switch the `term` clauses to `match` clauses, I think we should emphasize that the query string is analyzed. We can do this by updating the `message` value in the `match_bool_prefix` snippet and updating some of the surrounding text.

I'm happy to handle those changes if @cbuescher agrees with the approach.

**Comment by amitmbm** [comment]
@jrodewig thanks for your input, I also digged more into the source code of `org.elasticsearch.index.query.MatchBoolPrefixQueryBuilder` and you are right, that ultimately it uses the `term` query instead of `match` query. I am happy to change my PR to handle this change, As mention in the issue I raised https://github.com/elastic/elasticsearch/issues/84181, we can use the message as `QUICK BROWN F` and show the query term as `quick`, `brown` and `f` as these tokens are generated from the analysis on the input text considering the default `standard` analyzer.

**Comment by amitmbm** [comment]
@cbuescher @jrodewig I am wondering, why we named it as `Match` query when only search terms are analyzed and why we choose to use `term` query on the analyzed terms instead of `Match` query, Would be interesting to know it. As normally `match` queries are from a different family than `term` level queries and same analyzer(unless search time analyzer specified) is used at index and search time.

**Comment by cbuescher** [comment]
> My understanding is that match_bool_prefix does ultimately translate into a bool query containing term clauses. However, the query string is analyzed first.

@jrodewig That is correct, and I think the current documentation explains this nicely. As such, I'm not sure the documentation needs any update. I'd also be happy if we close this PR and the issue, but if you have an idea about a small change that would make this clearer that would be fine for me too.

**Comment by amitmbm** [comment]
@cbuescher Thanks for your input, could you also please provide more context on my previous comment?

> I am wondering, why we named it as `Match` query when only search terms are analyzed and why we choose to use `term` query on the analyzed terms instead of `Match` query, Would be interesting to know it. As normally `match` queries are from a different family than `term` level queries and same analyzer(unless search time analyzer specified) is used at index and search time.

**Comment by amitmbm** [comment]
@cbuescher thanks for the explanation, but IMHO and feedback which I got from other ES users, current documentation creates confusion so I guess we should refine the documentation.

**Pull request closed without merging**
