### PR TITLE
Remove the top-level 'mapping type' section.

### PR DESCRIPTION
**Pull request by jtibshirani**
It seemed confusing for users that our top-level mapping page still had a
prominent section named 'Mapping Type'. I've reworked the docs to remove this
reference and add a note about types removal (similar to the note we added to
other APIs  like [put mapping](https://www.elastic.co/guide/en/elasticsearch/reference/7.6/indices-put-mapping.html)).

### CODE REVIEW

**Comment by jtibshirani** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by jtibshirani** [comment]
The build is failing because of a cross-document reference in es-hadoop. I opened https://github.com/elastic/elasticsearch-hadoop/pull/1440 to remove it.

**Review by romseygeek — APPROVED** [review]
LGTM, thanks for picking this one up!

**Comment by romseygeek** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by jtibshirani** [comment]
Thanks for the review!

**Comment by jtibshirani** [comment]
master: 7161bd4
7.x: df7cfb3 
7.6: 0b68c76
7.5: 1f81e27

**Pull request merged**
