### PR TITLE
Fix Eclipse specific type casting issue

### PR DESCRIPTION
**Pull request by cbuescher**
The eclipse compiler needs some help in infering the functions return values.

### CODE REVIEW

**Review by s1monw — APPROVED** [review]
LGTM

**Comment by s1monw** [comment]
@elasticmachine test this please

**Comment by cbuescher** [comment]
@elasticmachine run the gradle build 1

**Comment by cbuescher** [comment]
@elasticmachine run the gradle build tests 1

**Comment by cbuescher** [comment]
@elasticmachine run the gradle build tests 1

**Comment by cbuescher** [comment]
Merging since the current CI error seems temporaty and related to infra, the IDE change should be okay on master regardless.

**Pull request merged**
