### PR TITLE
Update to Azure Storage 5.0.0

### LINKED ISSUE #23448: Update to Azure Storage 5.0.0
We are using `azure-storage:4.0.0` but [latest available version](https://github.com/azure/azure-storage-java) is now 

```
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>azure-storage</artifactId>
    <version>5.0.0</version>
</dependency>
```

Changelog (I highlighted the most important ones IMO):

2017.01.18 Version 5.0.0

 * **Prefix support for listing files and directories.**
 * Added support for setting public access when creating a blob container
 * The public access setting on a blob container is now a container property returned from downloadProperties.
 * Add Message now modifies the PopReceipt, Id, NextVisibleTime, InsertionTime, and ExpirationTime properties of its CloudQueueMessage parameter.
 * Populate content MD5 for range gets on Blobs and Files.
 * Added support in Page Blob for incremental copy.
 * **Added large BlockBlob upload support. Blocks can now support sizes up to 100 MB.**
 * Added a new, memory-optimized upload strategy for the upload* APIs. This algorithm only applies for blocks greater than 4MB and when storeBlobContentMD5 and Client-Side Encryption are disabled.
 * getQualifiedUri() has been deprecated for Blobs. Please use getSnapshotQualifiedUri() instead. This new function will return the blob including the snapshot (if present) and no SAS token.
 * getQualifiedStorageUri() has been deprecated for Blobs. Please use getSnapshotQualifiedStorageUri() instead. This new function will return the blob including the snapshot (if present) and no SAS token.
 * Fixed a bug where copying from a blob that included a SAS token and a snapshot ommitted the SAS token.

### PR DESCRIPTION
**Pull request by dadoonet**
Closes #23448.

### CODE REVIEW

**Comment by dadoonet** [comment]
@tlrx Could you review it please?

**Comment by dadoonet** [comment]
I'm planning to merge this on Friday, March 31st, unless anyone objects.

**Comment by jasontedor** [comment]
> I'm planning to merge this on friday, March 31st, unless anyone objects.

I object to this, this requires a review.

**Review by danielmitterdorfer — APPROVED** [review]
LGTM

**Comment by dadoonet** [comment]
Thanks @danielmitterdorfer!

**Comment by dadoonet** [comment]
Pushed in 5.x with 12dd1b4

**Pull request merged**
