### PR TITLE
Create index request should return the index name #23044

### PR DESCRIPTION
**Pull request by DanielLyons178**
Changed CreateIndexResponse.java and TransportCreateIndexAction.java to include index name.
Tests still need changing to pass with new response info.

### CODE REVIEW

**Review by jasontedor — CHANGES_REQUESTED** [review]
As I mentioned on #23044, the index name has to be serialized as part of the create index response. To understand why, start two nodes and send a create index request to the non-master node and note that the index name will not be correctly populated. You will have to take backwards compatibility into consideration here. We will want to see tests, both units tests and REST tests. I can guide you on this, but please let me know if you're willing to take this work on.

**Comment by DanielLyons178** [comment]
Hi @jasontedor, I would like to take this PR on but as you say may need some guidance at points. I will investigate the issue with regards to serialisation. I will try to reguarly update this PR and look forward to getting more involved with the project.

**Comment by jasontedor** [comment]
@DanielLyons178 Sure, we are happy for your involvement and I'm more than happy to help.

**Comment by DanielLyons178** [comment]
There are three serialization tests which do not pass on my machine for a fresh clone of the repository, these are as follows:
```
org.elasticsearch.action.termvectors.TermVectorsUnitTests.testStreamRequestWithXContentBwc
org.elasticsearch.action.ingest.SimulatePipelineRequestTests.testSerializationWithXContentBwc
org.elasticsearch.action.admin.indices.create.CreateIndexRequestTests.testSerializationBwc
```
I also get an exception trying to run the backwards compatibility testing as follows:
```
* What went wrong:
Execution failed for task ':test:framework:test'.
> There were no executed tests: 23 suites (23 ignored), 0 tests
```

**Comment by jasontedor** [comment]
@DanielLyons178 Are you still interested in completing this PR?

**Comment by jasontedor** [comment]
Relates #23044

**Comment by DanielLyons178** [comment]
@jasontedor I'd be happy to do some more work on this when I have the time but will need some guidance on where to go next as I'm not sure what still needs to be done

**Comment by jasontedor** [comment]
Okay, so at this point we've added the serialization of the index name to the create index response. The problem here is that a node built with this code could be talking to a node built with an earlier version that doesn't have this serialization logic. That means that when we write to such a stream, we have to account for the fact that the node will not understand us if we drop the index name on them. So, we have to check the version on the stream, and only write to it if it's a version that we expect. For now, let's try version 5.4.0 since we might include this change in the 5.4.0 release and thus a node before 5.4.0 will not understand, but a node after and on 5.4.0 will. Similarly, if we are reading from a node, it might not know to send us the index name if it's on a version before 5.4.0. So when reading from the stream you have check if the node is before 5.4.0 in which case we skip trying to read the index name, and if it's after or on 5.4.0, then we can read the index came from the stream. If you check the streams (`in` in the read method, `out` in the write method), there are methods for getting the stream version and then you can compare it to the version constant for 5.4.0. Do you want to give this a go?

**Comment by colings86** [comment]
No further feedback, closing. Please reopen if you have progress on this

**Pull request closed without merging**
