### PR TITLE
Deprecate xpack.eql.enabled setting and make it a no-op

### PR DESCRIPTION
**Pull request by williamrandolph**
We have recently removed the `xpack.*.enabled` settings for basic license level features (#54745). However, that work was being done simultaneously with EQL work, so the `xpack.eql.enabled` setting didn't get included in this work.

This PR deprecates the setting. It will be removed in a follow-up PR. Since the feature is experimental and the `xpack.eql.enabled` setting is undocumented, I don't know if the removal needs to be officially documented.

### CODE REVIEW

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by williamrandolph** [comment]
@elasticmachine update branch

**Comment by williamrandolph** [comment]
@elasticmachine update branch

**Comment by williamrandolph** [comment]
@elasticmachine run elasticsearch-ci/1

**Pull request merged**
