### PR TITLE
Move EC2 Discovery Tests to Mock Rest API

### PR DESCRIPTION
**Pull request by original-brownbear**
Improving these tests like we did for S3 away from mocks:

Move EC2 discovery tests to using the mock REST API introduced in
https://github.com/elastic/elasticsearch/pull/50550 instead of mocking
the AWS SDK classes manually.
Move the trivial remaining AWS SDK mocks to the single test suit that
was using them.

### CODE REVIEW

**Comment by DaveCTurner** [comment]
Thanks @original-brownbear, sorry for missing this when it was opened. Looks good; would you merge master just in case something's changed in the past month-and-a-bit?

**Comment by original-brownbear** [comment]
@DaveCTurner thanks for taking a look :) Merged in `master` now and tests are still passing fine :) (just ran EC2 locally)

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Comment by original-brownbear** [comment]
Thanks David!

**Pull request merged**
