### PR TITLE
fixed the chunk size in the docs

### PR DESCRIPTION
**Pull request by dipika-m**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)? yes
- Have you followed the [contributor guidelines] (https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)? yes
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by elasticcla** [comment]
Hi @dipika-m, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in your Git [commit](https://github.com/elastic/elasticsearch/pull/45173.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Review by dliappis — CHANGES_REQUESTED** [review]
Thank you for the PR! I left some comments for reducing duplication and utilizing the existing documentation for [byte size units](https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#byte-units).

**Comment by original-brownbear** [comment]
@dipika-m are you still interested in working on this?

**Comment by original-brownbear** [comment]
I'm closing this one since it has been inactive for more than two months now. Please reopen if you're still interested in working on this.

**Pull request closed without merging**
