### PR TITLE
Use debian/ubuntu systemd location (#36994)

### PR DESCRIPTION
**Pull request by jsoref**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by jsoref** [comment]
Note: I'm not really sure if this is worth doing. https://www.freedesktop.org/wiki/Software/systemd/TheCaseForTheUsrMerge/

Describes the `/lib` vs. `/usr/lib` stuff, basically, in the long run everything will move to the latter. But in today's debian and ubuntu, the merge hasn't happened, so that makes this package an outlier.

**Comment by atorok** [comment]
@elasticmachine  run all packaging tests

**Comment by atorok** [comment]
I guess it's worth aligning with the distribution in this case. @rjernst what do you think ?

**Comment by danielmitterdorfer** [comment]
Thanks for your pull request and the effort you put into it! However, as per the reasoning in https://github.com/elastic/elasticsearch/issues/36994#issuecomment-452508403 I hope you don't mind that I am closing this unmerged.

**Pull request closed without merging**
