### PR TITLE
Add assertions enabled helper

### PR DESCRIPTION
**Pull request by jasontedor**
Today in the code base we have lots of ugly code blocks like:

```java
  boolean assertionsEnabled = false;
  assert assertionsEnabled = true;
  if (assertionsEnabled) {
    // something
  }
```

These are a nuisance. Instead, we can do this in exactly one place and replace these blocks with

```java
  if (Assertions.ENABLED) {
    // something
  }
```

The cool thing here is that since this is a static final field, the JIT can optimize away the check at runtime if assertions are disabled.

### CODE REVIEW

**Review by abeyad — APPROVED** [review]
LGTM, nice

**Review by bleskes — APPROVED** [review]
Cool.

**Comment by bleskes** [comment]
This can also go to 5.x, no?

**Comment by jasontedor** [comment]
Thanks @abeyad and @bleskes. I backported this to 5.x too.

**Pull request merged**
