### PR TITLE
Remove unnecessary details logged for OIDC

### PR DESCRIPTION
**Pull request by jkakavas**
This change removes unnecessary details logged for OIDC.

Supersedes: https://github.com/elastic/elasticsearch/pull/48271

### CODE REVIEW

**Comment by jkakavas** [comment]
@elasticmachine update branch

**Comment by jkakavas** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by jkakavas** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by jkakavas** [comment]
@elasticmachine update branch

**Review by tvernum — APPROVED** [review]

**Pull request merged**
