### PR TITLE
Upgrade to Lucene-7.4.0-snapshot-bcf9f5c36b

### PR DESCRIPTION
**Pull request by dnhatn**
This snapshot includes LUCENE-8246 which allows to customize the number 
of deletes a merge claims.

### CODE REVIEW

**Review by bleskes — APPROVED** [review]
LGTM

**Review by jpountz — APPROVED** [review]
LGTM. I know who I can ask to upgrade Lucene to a new snapshot next time now. ;)

**Review by s1monw — APPROVED** [review]

**Comment by dnhatn** [comment]
Thanks everyone :)

**Comment by dnhatn** [comment]
>  I know who I can ask to upgrade Lucene to a new snapshot next time now. ;)

@jpountz I am more than happy to do it :).

**Pull request merged**
