### PR TITLE
Add shard size allocation balance function

### LINKED ISSUE #7155: Add shard balance function that tries to equalize similarly sized (on disk) shards
It'd be nice to have a balance function that tries to equalize the number of similarly sized shards on each node.  This would have several advantages for clusters with unevenly sized indexes:
- Help prevent #6168 by making it less likely that lots of large shards end up on a single node, pushing its disk space much much higher then the rest.
- Help balance disk IO load by keeping the large shards away from each other.
- Prevent one node from ending up fallow because it only contains small shards just by luck.

### PR DESCRIPTION
**Pull request by nik9000**
From the docs:
`cluster.routing.allocation.balance.size`::
     Defines a weight factor for the number of similarly sized shards allocated
      on a node (float). Defaults to `0.00f` because it is new and we're not
      yet sure what a good default is.  Raising this raises the tendency to
      equalize the number of similarly sized shards across all nodes in the
      cluster.  "Similarly sized" means that this formula spits out the same
      number:
        size <= 10^7^ bytes ? 0 : floor(log10(size))
      So 1GB and 5GB shards are "similar" and so are 1KB and 40MB.

Side effects:
1.  Enables cluster info collection on all master eligible nodes so that
they can make informed decisions based on shard sizes as soon as they get
elected master.  They don't have to wait for the job to return when they
are elected.
2.  Removes the disabled flag for the cluster info job.  Its now complicate
to know when you can disable it.  Besides, the disk allocation decider is
on by default now and that needs it too.
3.  Reworks BalanceConfigurationTests quite a bit adding a test for the
shard size balance and a test that random balance settings actually converge.
4.  Fixes some of the cluster rebalance docs that were confusing on reread.

Closes #7155

### CODE REVIEW

**Comment by s1monw** [comment]
@nik9000 I love the functionality that this PR adds but I am at the same time pretty scared of it. I spoke to you in person about his briefly to tell you how I feel about it. Yet, I still think making decisions based on disk usage is pretty dangerous and only works if you can somehow predict the ingest rate somehow. For instance if we start making decision on how big the shard is we will almost certainly run into the point where shards get rebalanced out of a sudden and those situations are hard to explain. That said, I really try to keep the balance function pretty static ie. use factors that change rarely like number of shards or replicas. On the other hand it would be very useful to have some usage factors taken into account for this to ensure we don't place high indexing load shard and high search load shards on the same node (which can be an allocation decider already today). 

I wonder if we can take a baby step into this direction that allows you to configure indices in a way that ensures we take it's usage pattern into account when allocating shards. What do you think about the idea to start with a very simple `enum IndexWeight { LOW, MEDIUM, HIGH; }` (we can still extend to  `enum IndexWeight { LOW, MEDIUM, HIGH, MASSIVE, CRAZY, RIDICULOUS; }` later :) or just go with a weight in `[0..1]` ) I think this would be way easier to test and implement and IMO it would take us pretty far. It also has the advantage that we know that ahead of time and therefor can place the shards accordingly on index creation. What do you think! Sorry for taking so long to look at this.

**Comment by s1monw** [comment]
@nik9000 ping

**Comment by nik9000** [comment]
Hey - sorry I seem to be filtering my from github to aggressively.....

Yeah - I don't mind going with something more static and user configured if it gets us to a point where we can merge something. We suffer from this a lot less than we'd used to because we have tons more power now. But it still comes up from time to time.

Maybe its a simple as
```
curl -XPUT localhost:9200/test/_settings -d '{
    "index.routing.allocation.push_apart.tag" : "big"
}'
```
and the balancing algorithm tries to push all indexes that are "big" apart from each other. Its less magical and surprising then what I proposed. And it'd be reasonably simple to rig up something quick in python/perl/your favorite cron job language that implements the "log of index size" thing that I have in this pull request.

You could still tune the weight of the push_apart-ness with one of those balance weights.

**Comment by nik9000** [comment]
I do wonder if it'd be worth implementing a job that you could turn on and off that sets the index size every half hour or something. I suspect it'd be used even if it were off by default. An not super hard to put together. That you could implement as a plugin though.

One way to make size based decisions less scary would be if they were sticky. Meh - better to let that be plugin or otherwise external code.

**Comment by sawyercade** [comment]
For anyone still interested in balancing by shard size, we've created a plugin to do so that replaces ES's default BalancedShardsAllocator. [Here's the repo](/datarank/tempest), and [here is a blog post] (http://engineering.datarank.com/2015/07/08/balancing-elasticsearch-cluster-by-shard-size.html) explaining how it works and demonstrating significant improvements in balance and heap usage across our 17-node cluster.

**Pull request closed without merging**
