### PR TITLE
Fix reindex with a remote source on a version before 2.0.0

### PR DESCRIPTION
**Pull request by jimczi**
Discussed in https://discuss.elastic.co/t/5-3-0-breaks--reindex/80388 and https://github.com/elastic/elasticsearch/pull/22931#issuecomment-290093349

This commit https://github.com/elastic/elasticsearch/commit/7520a107bee67099338813728147d2aee25ed240#diff-0c925d1f41390dd5d7dd09b6ff5d51d1 in master and v5.3 breaks `reindex from remote` when the source is on a version before 2.0.0. The `scroll_id` is always extracted from a plain text body in ES 1.7 (and before) and does not accept the JSON version that appears in 2.0.0.
This change checks the version of the remote cluster and builds the scroll_id in the body depending on the remote version.

### CODE REVIEW

**Review by jasontedor — APPROVED** [review]
LGTM. I think this can safely go into a 5.3 patch release?

**Review by bleskes — COMMENTED** [review]
This is such an important part of our upgrade strategy that i think we need a real integration test for it as well

**Comment by jimczi** [comment]
@bleskes it would be great I agree but it's not low hanging fruit to build an IT that launches a node in 1.7 or maybe I missed something ?

**Comment by nik9000** [comment]
> @bleskes it would be great I agree but it's not low hanging fruit to build an IT that launches a node in 1.7 or maybe I missed something ?

Right. We don't have the infrastructure built to start a 1.7 version of Elasticsearch in the integration test suite. I'd certainly love to have it though.

**Review by nik9000 — APPROVED** [review]
This fixes the issues, yeah.

**Comment by nik9000** [comment]
I filed #23828 to have a look at reindex-from-remote.

**Comment by nik9000** [comment]
> I filed #23828 to have a look at reindex-from-remote.

Sorry, to have a look at *testing* reindex-from-remote more completely.

**Comment by bleskes** [comment]
Thank you Nik. To be clear I by no means meant that the suggested test is a requirement to get this in.

**Comment by nik9000** [comment]
> Thank you Nik. To be clear I by no means meant that the suggested test is a requirement to get this in.

I figured as much. I'm really sorry I didn't write those tests after I wrote reindex-from-remote in the first place. It would have saved so much trouble.

**Pull request merged**
