### PR TITLE
Update snapshots.asciidoc

### PR DESCRIPTION
**Pull request by IsaacHaze**
Adds more determiners.

### CODE REVIEW

**Comment by clintongormley** [comment]
Hi @IsaacHaze 

Thanks for the fixes.  Please could you sign the CLA so that I can merge them in?
http://www.elasticsearch.org/contributor-agreement/

**Comment by IsaacHaze** [comment]
On 12 February 2015 at 13:58, Clinton Gormley <notifications@github.com>
wrote:

> Hi @IsaacHaze <https://github.com/IsaacHaze>
>
> Thanks for the fixes. Please could you sign the CLA so that I can merge
> them in?
> http://www.elasticsearch.org/contributor-agreement/
>
What a hassle for signing away my rights, my guess is that the legal team's
opinion is that a mail with  "i agree" won't suffice?


Isaac

**Comment by clintongormley** [comment]
You guessed correctly :)

**Comment by IsaacHaze** [comment]
New things learned:
- Adobe EchoSign sucks
- Chrome doesn't allow me to add cookie exceptions for third party cookies
(or i'm too dumb to understand how they work.)


Enjoy your day, that it may be filled with buckets of new contributions!

Isaac


On 13 February 2015 at 21:27, Clinton Gormley <notifications@github.com>
wrote:

> You guessed correctly :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elasticsearch/elasticsearch/pull/9673#issuecomment-74321028>
> .
>



-- 
It was me, waiting for me,
hoping for something more.

**Comment by clintongormley** [comment]
thanks @IsaacHaze - merged

**Pull request closed without merging**
