### PR TITLE
[DOCS] Simplifies dense vector mapping in semantic search example

### PR DESCRIPTION
**Pull request by szabosteve**
## Overview

In 8.11 the `dense vector` field type has been simplified and some of the settings now have sensible default values:
* `"index": true` is implicit,
* `similarity` defaults to `cosine`.

This PR adjusts the dense vector mapping example in the semantic search documentation and in. the kNN search docs to make it in line with the changes outlined above.

### Preview

* [Map a field for the text embeddings](https://elasticsearch_102080.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/semantic-search.html#semantic-search-field-mappings)
* [kNN search](https://elasticsearch_102080.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/knn-search.html)

### CODE REVIEW

**Comment by abdonpijpelink** [comment]
I think this needs to be updated in more places:

- https://www.elastic.co/guide/en/elasticsearch/reference/master/knn-search.html#approximate-knn
- https://www.elastic.co/guide/en/elasticsearch/reference/master/knn-search.html#approximate-knn-using-byte-vectors (drop the default settings)
- https://www.elastic.co/guide/en/elasticsearch/reference/master/knn-search.html#nested-knn-search (drop the default settings)
- https://www.elastic.co/guide/en/elasticsearch/reference/master/knn-search.html#knn-indexing-considerations (drop the index parameter)
- https://www.elastic.co/guide/en/elasticsearch/reference/master/knn-search.html#exact-knn (index now needs to be set to false)

Would you be interested in adding that to this PR, or would you prefer a separate PR?

**Comment by szabosteve** [comment]
@abdonpijpelink Thank you for the input, I addressed the kNN search docs via [1fd2eaa](https://github.com/elastic/elasticsearch/pull/102080/commits/1fd2eaac53a257cf3d7e3b5f612461473dd5bd3c). I'll open another PR in `stack-docs` to update the relevant examples there, too!

**Comment by abdonpijpelink** [comment]
For exact kNN, it currently states: _If you don’t intend to use the field for approximate kNN, omit the `index` mapping option or set it to `false`_." If `index` defaults to `true` now, omitting is not good advice. 

Maybe we change that into: _If you don’t intend to use the field for approximate kNN, set the `index` mapping option to `false`._

**Comment by szabosteve** [comment]
@abdonpijpelink [309a9d9](https://github.com/elastic/elasticsearch/pull/102080/commits/309a9d9754bbc1493902356b5125aa0cd63034f6) did the necessary change.

**Review by abdonpijpelink — APPROVED** [review]
LGTM. Thank you @szabosteve !

**Pull request merged**
