### PR TITLE
[Logging] Refactor ESLoggerUsageChecker

### PR DESCRIPTION
**Pull request by tumile**
Refers to #49087

This is a draft PR to refactor ESLoggerUsageChecker, a static analysis tool to verify correct usages of logger. Here are the steps taken to improve the structure of the code

- [x] move `WrongLoggerUsage` class into its own file
- [x] move `ClassChecker` into its own file
- [x] move `MethodChecker` into its own file, along with all static `Type` since this is the only place they are referenced
- [x] move all `BasicValue` and `BasicInterpreter` subclasses into MethodChecker.java as well since they are not used anywhere else

- Inside MethodChecker.java
- [x] refactor `findBadLoggerUsages`, which is where the bulk of checks are
  - [x] make `lineNumber`, `methodNode`, `instructions`, `logMessageFrames`, `arraySizeFrames` instance variables since they are accessed in multiple methods and avoid passing around too much
  - [x] `findBadLoggerUsages` is broken down to 2 methods
    - [x] `analyzeMethod` to populate `instructions`, `logMessageFrames`, `arraySizeFrames`
    - [x] `walkInstructions` to check each instructions 
  - [x] `walkInstructions` checks for Opcode and call `verifyMethodUsage` or `verifyConstructorUsage` with necessary arguments
  - [x] `verifyMethodUsage` is renamed from old `verifyLoggerUsage`
  - [x] `verifyConstructorUsage` is extracted from old `findBadLoggerUsages`
  - the above two will in turn call checkFixedArityArgs or checkArrayArgs
  - the rest is kept semantically the same
- [x] fix SonarLint warnings

### CODE REVIEW

**Comment by tumile** [comment]
Pinging @pgomulka

**Comment by pgomulka** [comment]
ok to test

**Comment by tumile** [comment]
Hi, I'm getting failed tests in `IndexingIT` and `MixedClusterClientYamlTestSuiteIT`, which is odd because they are unrelated to my changes. How should I go about resolving that?

**Review by pgomulka — COMMENTED** [review]
hey @tumile 
thank you for your interest in Elasticsearch, but I will have to close this PR for the time being. As I mentioned in https://github.com/elastic/elasticsearch/issues/49087#issuecomment-650062303 the expectation was to discuss possible solutions first, before making refactoring.
I was hoping that there is a 3rd party lib that would achieve what we do there. The refactoring itself would require a fairly complex DSL, possibly migrating to a different byte manipulation library.

**Comment by tumile** [comment]
Thanks for letting me know. I misunderstood the requirement there. Will be more careful next time!

**Pull request closed without merging**
