### PR TITLE
terminateAfter added to the RequestConverter

### LINKED ISSUE #46446: high level rest client count request fails with 400 Bad Request
**Describe the feature**:

**Elasticsearch version** (`bin/elasticsearch --version`): 6.7.0

**Plugins installed**: []

**JVM version** (`java -version`): official 6.7.0 docker

**OS version** (`uname -a` if on a Unix-like system): linux

**Description of the problem including expected versus actual behavior**:
when executing count request from high level rest client and using "terminate_after", requests fails with this error:
{
        "type": "parsing_exception",
        "reason": "request does not support [terminate_after]",
        "line": 2,
        "col": 2
      }

this is because terminate_after is sent in the request body and not as request param

was able to reproduce with kibana by running this:

PUT /test
POST /test/_count
{
 "terminate_after":1 
}

however this works:

POST /test/_count?terminate_after=1

**Steps to reproduce**:

can reproduce with this code:

`
CountRequest countRequest = new CountRequest(index);
        countRequest.terminateAfter(1);
        CountResponse countResponse = highLevelClient.count(countRequest, RequestOptions.DEFAULT);
`

### PR DESCRIPTION
**Pull request by turackangal**
Fix #46446

### CODE REVIEW

**Comment by turackangal** [comment]
@hub-cap Cav you review ?

**Review by martijnvg — CHANGES_REQUESTED** [review]
Thanks @turackangal for working on this. Can also you modify the `RequestConvertersTests#setRandomCountParams()` method to randomly set terminate after?

Something like:

```
if (randomBoolean()) {
    countRequest.terminateAfter(randomIntBetween(0, Integer.MAX_VALUE));
    expectedParams.put("terminate_after", String.valueOf(countRequest.terminateAfter()));
}
```

This is used by the `testCount()` unit test.

Otherwise this PR looks good!

**Review by martijnvg — COMMENTED** [review]
I left one other comment. Also can you remove the commits that have a different email than you signed the CLA with? I think it is best to do an interactive rebase and then force push to your remote branch.

**Comment by martijnvg** [comment]
@turackangal Thanks for updating the PR. I think that something went wrong when updating your branch, because the PR included over a hundred other commits. I cleaned it up and made a small change (the actual parameter is `terminate_after` instead of `terminateAfter`). I will run the build now and if everything is okay then merge the pr.

**Comment by martijnvg** [comment]
@elasticmachine run build

**Comment by martijnvg** [comment]
@elasticmachine test this please

**Review by martijnvg — APPROVED** [review]

**Comment by martijnvg** [comment]
@elasticmachine test this please

**Pull request merged**
