### PR TITLE
[DOCS] Add placeholder for 7.3.1 release notes

### PR DESCRIPTION
**Pull request by jrodewig**
Adds a placeholder for the 7.3.1 release notes

### CODE REVIEW

**Review by bmorelli25 — APPROVED** [review]
Pending docs ci, LGTM.

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by jasontedor** [comment]
I added the v7.4.0 label since this should be merged there  too.

**Comment by jrodewig** [comment]
Thanks @jasontedor.

**Comment by jrodewig** [comment]
[Ported to 7.x.](https://github.com/elastic/elasticsearch/commit/5dcc00a8b33ddfc5d22a4027e29ea3069126d4e0)

**Pull request merged**
