### PR TITLE
Remove word at

### PR DESCRIPTION
**Pull request by Geesu**

### CODE REVIEW

**Comment by nik9000** [comment]
Change looks good, @Geesu, can you sign the CLA? We can't merge anything, even this tiny delete without it.

**Comment by Geesu** [comment]
Done!

**Comment by nik9000** [comment]
> Done!

Awesome. Every time someone makes a comment on this then check reruns. Looks like it hasn't noticed yet. Lets see if this does it.

**Comment by nik9000** [comment]
I guess the CLA checker doesn't like you for now. I looked you up in it manually and found you so I'll merge. Usually it fails when your email doesn't line up somewhere (patch email, github email, cla signing email) but everything looks right.... It could be that the checker has just fallen over or been rate limited or something.

**Comment by nik9000** [comment]
Github merged to the 2.3 branch. I forward ported:
master: 3c24ea43fdd641f59eee2bf8a2979d7f8ca0a821
2.4: bbdf989be369d2ca9d0850f1c87ae9e63d714651

**Comment by nik9000** [comment]
Thanks for fixing it @Geesu !

**Comment by Geesu** [comment]
np! I intentionally used the public email address linked to my Github account so hopefully it was just rate limited.

**Pull request merged**
