### PR TITLE
add indices pipeline settings check when deleting a pipeline

### PR DESCRIPTION
**Pull request by weizijun**
When deleting a pipeline, check whether the pipeline is actually deleted in the indices settings.
If the indices have the deleting pipeline, fail the delete request.

### CODE REVIEW

**Comment by danhermann** [comment]
@elasticmachine ok to test

**Comment by danhermann** [comment]
@elasticmachine update branch

**Comment by danhermann** [comment]
@elasticmachine run elasticsearch-ci/part-1

**Comment by danhermann** [comment]
@weizijun, thank you for this contribution. It's a helpful improvement and we'd like to get it merged. There are a couple failing tests:
```
org.elasticsearch.ingest.common.IngestCommonClientYamlTestSuiteIT.test {yaml=ingest/240_required_pipeline/Test index with final pipeline}
org.elasticsearch.ingest.common.IngestCommonClientYamlTestSuiteIT.test {yaml=ingest/240_required_pipeline/Test final pipeline when target index is changed}
org.elasticsearch.ingest.common.IngestCommonClientYamlTestSuiteIT.test {yaml=ingest/200_default_pipeline/Test index with default pipeline}
```
Each of those tests is attempting to delete an ingest pipeline that is either default or final on an index. The fix for those will be to delete the index before deleting the ingest pipeline. If you can make those changes, we'll get this reviewed and merged.

**Comment by weizijun** [comment]
> @weizijun, thank you for this contribution. It's a helpful improvement and we'd like to get it merged. There are a couple failing tests:
> 
> ```
> org.elasticsearch.ingest.common.IngestCommonClientYamlTestSuiteIT.test {yaml=ingest/240_required_pipeline/Test index with final pipeline}
> org.elasticsearch.ingest.common.IngestCommonClientYamlTestSuiteIT.test {yaml=ingest/240_required_pipeline/Test final pipeline when target index is changed}
> org.elasticsearch.ingest.common.IngestCommonClientYamlTestSuiteIT.test {yaml=ingest/200_default_pipeline/Test index with default pipeline}
> ```
> 
> Each of those tests is attempting to delete an ingest pipeline that is either default or final on an index. The fix for those will be to delete the index before deleting the ingest pipeline. If you can make those changes, we'll get this reviewed and merged.

ok, I will fix, and passed ./gradlew check

**Comment by weizijun** [comment]
@danhermann I have fixed the failed tests. but the elasticsearch-ci/part-1 is blocked

**Comment by weizijun** [comment]
@elasticmachine run elasticsearch-ci/part-1

**Comment by weizijun** [comment]
@elasticmachine ok to test

**Comment by weizijun** [comment]
@elasticmachine update branch

**Comment by weizijun** [comment]
@elasticmachine update branch

**Comment by weizijun** [comment]
hi, @danhermann, all tests passed. can you help to review this PR?

**Comment by danhermann** [comment]
@weizijun, apologies for the delay on this one. I will review it and help you to get it merged. One suggestion for improvement that I have is to update the error message to include the number of indices from which the pipeline must first be removed. Perhaps  something like this:

`pipeline [my-pipeline] cannot be deleted because it is the default pipeline for <x> indices including [<index1>,<index2>] and the required pipeline for <y> indices including [<index3>, <index4>, <index5>]`

That way a user is informed immediately about the number of places from which the ingest pipeline must be removed before it can be deleted rather than removing it from the first index, attempting to delete it again, finding that it cannot be deleted because it's used on another index, etc. The "including" list of indices might include just the first 3 indices encountered in case it's used on a large number of indices.

**Review by danhermann — APPROVED** [review]
@weizijun, the one remaining test failure is a known flaky test, so this looks good. I'll get it merged and backported for the appropriate release. Thanks for building this feature!

**Pull request merged**
