### PR TITLE
Add information about the snapshot repository

### PR DESCRIPTION
**Pull request by dadoonet**
From https://twitter.com/ddanieltwitt/status/938754761968451585, I think
we should add in our documentation, where users can find the SNAPSHOT
versions we are publishing.

### CODE REVIEW

**Comment by javanna** [comment]
I don't understand from the tweet if there is some wrong link in the docs or not. It looks more like we just don't promote our snapshots, and that is true for the whole Elasticsearch docs. If we do want to add some snapshots info on the high-level REST client docs, let's do it close to the maven coordinates? I also wonder if it's good enough to just publish the main url of the snapshots, I always struggle getting to the actual artifacts because I cannot remember the full path. Maybe tools can just be fed with the main url though.

**Comment by dadoonet** [comment]
IMO The tweet just says that it's impossible by looking at the documentation that someone can use elasticsearch 7.0.0-alpha1. Although we are saying in docs that the following should work. Which is not the case as this version has not been released.

```xml
<dependency>
    <groupId>org.elasticsearch.client</groupId>
    <artifactId>elasticsearch-rest-high-level-client</artifactId>
    <version>7.0.0-alpha1</version>
</dependency>
```

So it's kind of a bug in our docs.

I believe that at least documenting that adding the following would help users to get access to non released yet artifatcs:

```xml
        <repository>
            <id>elastic-snapshots</id>
            <name>Elastic Snapshots</name>
            <url>https://snapshots.elastic.co/maven/</url>
            <releases><enabled>false</enabled></releases>
            <snapshots><enabled>true</enabled></snapshots>
        </repository>
```

**Comment by javanna** [comment]
This is true for all of our artifacts on master though. We have docs against master for non released artifacts. I want to make sure that we solve this properly for all our docs, rather than for a single product.

**Comment by dadoonet** [comment]
> This is true for all of our artifacts on master though. 

What are the other artifacts you are referring to? I mean that AFAIK only the clients and the test framework can be used in Maven? Is that what you are thinking about?

**Comment by javanna** [comment]
yes but I also thought that people who want to run Elasticsearch from master have the same problem of not knowing where the snapshots are.

**Comment by dadoonet** [comment]
@javanna Do you want to close it? Or propose something else?

**Review by javanna — APPROVED** [review]
@dadoonet I am ok with this change, maybe we need it also for the sniffer artifact?

**Comment by dadoonet** [comment]
Thanks @javanna. I added it and pushed the changes to 6.x and master.

**Pull request merged**
