### PR TITLE
Simplify Log4j shutdown hack test

### PR DESCRIPTION
**Pull request by jasontedor**
The Log4j shutdown hack test tests that a hack we have in place to
workaround a bug in Log4j during shutdown is effective. Log4j can use
JMX to control logging levels, but we disable this through the use of a
system property log4j2.disable.jmx (mainly because there is no need for
this feature, but it also means granting additional security
permissions). The bug in Log4j is that during shutdown, it neglects to
check whether or not its usage of JMX is disable and so it attempts to
unregister management beans, leading to a permissions violation. The
test works by attempting to shutdown Log4j and thus triggering the bad
code path. With the Log4j hack in place, we have introduced jar hell so
that its our code running instead of code from the Log4j jar. Our code
correctly checks that the usage of JMX is disabled and thus does not
trip on a permissions violation. The test was a little complicated in
that it attempted to just grant the minimal permissions needed for Log4j
to do its thing, but this can sometimes lead to other unwanted
permissions violations because the permissions put in place are more
restrictive necessary. This commit simplifies this situation by
rewriting the test to only deny Log4j the sole permission needed to
trigger the bug.

Relates #20389

### CODE REVIEW

**Comment by jasontedor** [comment]
The restrictive way of controlling permissions before this change can sometimes lead to failures such as:

```
ERROR   0.05s J1 | EvilLoggerTests.testLog4jShutdownHack <<< FAILURES!
   > Throwable #1: java.security.AccessControlException: access denied ("java.io.FilePermission" "/var/lib/jenkins/.gradle/caches/modules-2/files-2.1/com.carrotsearch.randomizedtesting/randomizedtesting-runner/2.3.2/307965917fe8a22b7ee72deba39ef4b8e6ebc069/randomizedtesting-runner-2.3.2.jar" "read")
   > 	at __randomizedtesting.SeedInfo.seed([5428D32DC53A29A1:78BE5A5B510426D2]:0)
   > 	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
   > 	at java.security.AccessController.checkPermission(AccessController.java:884)
   > 	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
   > 	at org.elasticsearch.common.logging.EvilLoggerTests$1.checkPermission(EvilLoggerTests.java:173)
   > 	at java.lang.SecurityManager.checkRead(SecurityManager.java:888)
   > 	at java.io.File.isDirectory(File.java:844)
   > 	at sun.net.www.ParseUtil.fileToEncodedURL(ParseUtil.java:269)
   > 	at sun.security.provider.PolicyFile.canonicalizeCodebase(PolicyFile.java:1735)
   > 	at sun.security.provider.PolicyFile.access$700(PolicyFile.java:258)
   > 	at sun.security.provider.PolicyFile$5.run(PolicyFile.java:1188)
   > 	at sun.security.provider.PolicyFile$5.run(PolicyFile.java:1186)
   > 	at java.security.AccessController.doPrivileged(Native Method)
   > 	at sun.security.provider.PolicyFile.getPermissions(PolicyFile.java:1185)
   > 	at sun.security.provider.PolicyFile.getPermissions(PolicyFile.java:1132)
   > 	at sun.security.provider.PolicyFile.implies(PolicyFile.java:1086)
   > 	at java.security.ProtectionDomain.implies(ProtectionDomain.java:281)
   > 	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:450)
   > 	at java.security.AccessController.checkPermission(AccessController.java:884)
   > 	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
   > 	at org.elasticsearch.common.logging.EvilLoggerTests$1.checkPermission(EvilLoggerTests.java:173)
   > 	at java.lang.SecurityManager.checkPropertyAccess(SecurityManager.java:1294)
   > 	at org.elasticsearch.common.logging.EvilLoggerTests$1.checkPropertyAccess(EvilLoggerTests.java:182)
   > 	at java.lang.System.getProperty(System.java:717)
   > 	at org.apache.logging.log4j.core.layout.AbstractStringLayout.isPreJava8(AbstractStringLayout.java:97)
   > 	at org.apache.logging.log4j.core.layout.AbstractStringLayout.<init>(AbstractStringLayout.java:157)
   > 	at org.apache.logging.log4j.core.layout.PatternLayout.<init>(PatternLayout.java:104)
   > 	at org.apache.logging.log4j.core.layout.PatternLayout.<init>(PatternLayout.java:58)
   > 	at org.apache.logging.log4j.core.layout.PatternLayout$Builder.build(PatternLayout.java:494)
   > 	at org.apache.logging.log4j.core.config.AbstractConfiguration.setToDefault(AbstractConfiguration.java:548)
   > 	at org.apache.logging.log4j.core.config.DefaultConfiguration.<init>(DefaultConfiguration.java:47)
   > 	at org.apache.logging.log4j.core.LoggerContext.<init>(LoggerContext.java:74)
   > 	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.createContext(ClassLoaderContextSelector.java:171)
   > 	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getDefault(ClassLoaderContextSelector.java:183)
   > 	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:80)
   > 	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:227)
   > 	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
   > 	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:174)
   > 	at org.elasticsearch.common.logging.EvilLoggerTests.testLog4jShutdownHack(EvilLoggerTests.java:187)
   > 	at java.lang.Thread.run(Thread.java:745)
```

which arises due to ordering issues.

**Comment by javanna** [comment]
thanks for the thorough explanation, LGTM although I am not super familiar with this whole thing :)

**Comment by jasontedor** [comment]
retest this please

**Comment by jasontedor** [comment]
Thanks for reviewing @javanna.

**Pull request merged**
