### PR TITLE
Add target_field parameter to ingest processors

### LINKED ISSUE #23682: Add target field to lowercase processor (and others)
From this discussion: https://discuss.elastic.co/t/workaround-alternative-for-normalizer-in-es-5-1/79470/3?u=dadoonet

Could be nice to be able to lowercase a field but target it to another field like "field.raw" for example.

If accepted, I think we should do it for most processors.

### PR DESCRIPTION
**Pull request by alexshadow007**
Parameter was added to gsub, join, lowercase, sort, split, trim and uppercase processors.

Closes #23682 #23228

### CODE REVIEW

**Comment by talevy** [comment]
Hi @alexshadow007, these changes look good! thank you so much. Apologies for the delayed response here. Do you mind rebasing off latest `master` to resolve the conflicting files?

Jenkins, please test this

**Comment by alexshadow007** [comment]
@talevy Done

**Comment by talevy** [comment]
thanks!

jenkins, please test this

**Comment by talevy** [comment]
Merged into `master` and `5.x` for the 6.0 and 5.6 releases!

**Pull request merged**
