### PR TITLE
EQL: Use byte instead of int for stages

### PR DESCRIPTION
**Pull request by matriv**
Memory usage analysis revealed that we use an `int` for the number of
stages of a sequence query, whereas we could use a `byte` instead.
With this opportunity added a check in the `Verifier` which prevents
sequence queries with more than 127 stages.

Screen Shot 2021-04-06 at 14 41 38

### CODE REVIEW

**Comment by costin** [comment]
What's the memory gain in moving from int to byte? 
Additionally, the byte could be treated as unsigned so we actually allow 255 stages - for that the initial value should start at `Byte.MIN_VALUE + 1` (to handle the -1) scenario.
It's doable but it's a complication that we should avoid unless we get a consistent gain.

**Comment by matriv** [comment]
> could be treated as unsigned so we actually allow 255 stages - for that the initial value should start at `Byte.MIN_VALUE + 1` (to handle the -1) scenario.

Will run the test again and check the memory with the new code, Should have done it before asking for the review :( .

**Comment by matriv** [comment]
@costin

Run the tests on a "warm" environment, so the query:
```
"sequence by hostname 
    [network where true]
    [network where true]
    [network where true]
    [network where true]
    [network where true]"
```
was run several times after bootstrapping before taking the measurements.


Before (Numbers are: #Objects & #Waste):
Screen Shot 2021-04-06 at 14 41 38

After:
Screen Shot 2021-04-13 at 12 27 56

From an object allocation view no visible difference,
Before: 
Screen Shot 2021-04-13 at 13 42 25
(marked object allocations before and after):

After:
Screen Shot 2021-04-13 at 13 35 40

**Comment by matriv** [comment]
@costin, Another option could be to use a `short` to avoid the complexity of properly handling an `unsigned byte` which is not supported out of the box by Java, but still set a limit on the stages that can be used on a query, like 512.

**Comment by costin** [comment]
If I'm reading the results correctly, there isn't any significant different. If that is the case I would leave things as they are - the JVM prefers `int` and using byte or short simply complicates things on our end without any visible benefit. Moreover doing math operations are likely to result in an int anyway (for example when doing comparisons).

**Comment by matriv** [comment]
@costin Sure, the difference is only a few kb (marked as "waste").
Should we add still add a restriction to the number of stages though?

**Comment by costin** [comment]
I think having an upper limit is desirable though I don't have any preference for what that would be.
/cc @astefan

**Comment by astefan** [comment]
I would postpone adding such a restriction unless we have a good reason for it. So far, arguments are only hypothetical.
If we were to add it at some time, I think it should be part of https://github.com/elastic/eql/issues/4, where such a limit has more sense.

**Comment by matriv** [comment]
Closing this, if/when we decide on a restriction on the number of stages will come back with a new PR.

**Pull request closed without merging**
