### PR TITLE
Refactor `node_selector`s: remove redundant ones and change to `current`

### PR DESCRIPTION
**Pull request by ldematte**
Node selectors with version ranges are used today just for mixed cluster/rolling upgrade tests, to filter out (or select) the new upgraded nodes that exhibit a change behaviour.
Therefore it is not needed to specify explicitly a version range: selecting nodes that have been upgraded (`version: current`) or not is sufficient.

This PR removes redundant `node_selectors` (already covered by `skip`) and transforms all others using a version range into equivalent `current` version selectors.

Today just `current` exists; one case needs to specify "not `current`" versions. We plan to address this case and add  `original` in a follow-up PR (https://github.com/elastic/elasticsearch/pull/103954).

Running this with full-bwc to see if there are no surprises (e.g. mixed clusters)

### CODE REVIEW

**Comment by ldematte** [comment]
@elasticmachine update branch

**Comment by ldematte** [comment]
@elasticmachine update branch

**Review by williamrandolph — COMMENTED** [review]
I think this LGTM, but I just want to make sure I understand why we've split some test cases in two. It's that node_selector with a version is sufficient to cover cases where only some nodes can be used _and_ cases where any node can be used, but "node_selector: current" only makes sense in the case where nodes have different behaviors?

**Comment by ldematte** [comment]
It's a very good question. Basically yes, node_selector with a version was used in those cases to both select and skip. But there are other practical "future" reasons -- I listed them under the comment for one of the tests I split. Hope it is clear now :)

**Review by williamrandolph — APPROVED** [review]
Thanks for answering my questions. I'm happy to approve now.

**Pull request merged**
