### PR TITLE
Add basic authentication authentication for plugin manager

### PR DESCRIPTION
**Pull request by dadoonet**
The plugin downloader which is invoked by the plugin command line does not support downloading the plugin from a URL which is secured using basic auth.
## Use Case

In the continuous integration process if we want to install a plugin where the plugin artifact is available on the CI server which is restricted with basic auth this is not possible.
## Workaround

Download using wget passing auth details and use the elasticsearch plugin command line passing the _file_ url instead of _http_ url
## Good to have

Plugin command line to have options to take in basic auth credentials and pass it on to the downloader.

Thanks to @katta for the original PR!

Closes #2550.

### CODE REVIEW

**Comment by s1monw** [comment]
ping... what's the status on this @dadoonet

**Comment by clintongormley** [comment]
Or @tlrx?

**Comment by clintongormley** [comment]
This has been stalled a year, and nobody has requested this functionality.  Closing.

**Comment by beiske** [comment]
This would be really convenient for Found

**Pull request closed without merging**
