### PR TITLE
Fix incorrect assumptions for api_key authentication type

### LINKED ISSUE #81425: Review and correct checks for AuthenticationType.API_KEY
ES code has some specially handlings for API key authentication (by checking AuthenticationType.API_KEY). Some of these checks assume API key cannot run-as other users, which is no longer true since #79809. For example,  `GET _security/_authenticate` does not print anonymous roles if the authentication type is API key. But this is incorrect if the API key run-as a regular user. Another example is `Authentication#canAccessResourceOf` which grants access if the API key is the same. But even when the API key is the same, it can run-as different users.

### PR DESCRIPTION
**Pull request by ywangd**
This is essentially a follow-up PR for #79809 which enables run-as for API keys. The code still has a few places where it assumes API keys cannot perform run-as. This PR fixes the incorrect assumptions and adds relevant tests.

Resolves: #81425

### CODE REVIEW

**Comment by ywangd** [comment]
@tvernum I was going to use `AuthenticationContext` for this PR. But then decided against it because there are quite a bit of changes and I don't want complicate the core changes with auxiliary ones. I think it's better to have a separate PR that just replaces `Authentication` with `AuthenticationContext` with no functional changes.

**Review by tvernum — APPROVED** [review]
LGTM

**Comment by ywangd** [comment]
@elasticmachine update branch

**Comment by ywangd** [comment]
@elasticmachine run elasticsearch-ci/part-1-fips

**Pull request merged**
