### PR TITLE
Mention `bbq_hnsw` for `m` and `ef_construction` options

### PR DESCRIPTION
**Pull request by Philippus**
Applying this PR will mention `bbq_hnsw` for the `m` and `ef_construction` options. See https://github.com/elastic/elasticsearch/blob/ea90fbc10d3371e5e3b9921a81a4936c2e39d5f4/server/src/main/java/org/elasticsearch/index/mapper/vectors/DenseVectorFieldMapper.java#L1384.

### CODE REVIEW

**Review by carlosdelest — APPROVED** [review]
LGTM, thanks!

**Comment by leemthompo** [comment]
@elasticmachine test this

**Comment by leemthompo** [comment]
run docs-build

**Comment by carlosdelest** [comment]
Thanks for your contribution, @Philippus !

**Pull request merged**
