### PR TITLE
plugins/repository-gcs: Update google-cloud-storage/core to 1.59.0

### PR DESCRIPTION
**Pull request by wuurrd**
https://github.com/elastic/elasticsearch/issues/39366

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)? Yes
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)? Yes
- If submitting code, have you built your formula locally prior to submission with `gradle check`? Yes
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed. Yes
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)? Yes
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that. Not for a class

### CODE REVIEW

**Review by jasontedor — CHANGES_REQUESTED** [review]
This is not sufficient. Please run `:plugins:repository-gcs:precommit` and you will see that you need to update the SHAs.

**Comment by jasontedor** [comment]
Thanks for the pull request @wuurrd. I left a comment about some additional changes that are needed.

**Comment by wuurrd** [comment]
@jasontedor Hey, thanks for the review - I ran the commands and added a new patch. What else needs to be done?

**Comment by jasontedor** [comment]
@elasticmachine test this please

**Comment by jasontedor** [comment]
@wuurrd Thanks for updating, we will run this through CI now.

**Comment by wuurrd** [comment]
@jasontedor: Is there a simple way to retry the failed job?

```17:08:56 Timed out while waiting for the machine to boot. This means that
17:08:56 Vagrant was unable to communicate with the guest machine within
17:08:56 
17:08:56 the configured ("config.vm.boot_timeout" value) time period.
17:08:56 > Task :qa:vagrant:vagrantCentos7#up FAILED
17:08:56 :qa:vagrant:vagrantCentos7#up (Thread[Daemon worker,5,main]) completed. Took 5 mins 22.898 secs.
```

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/packaging-sample

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by jasontedor** [comment]
Thanks @wuurrd. I have integrated this to the 6.7, 7.0, 7.x, and master branches.

**Pull request merged**
