### PR TITLE
Add an example of dynamic field names

### PR DESCRIPTION
**Pull request by loekvangool**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Review by dakrone — APPROVED** [review]
LGTM, do you want to merge this @loekvangool or should I?

**Comment by loekvangool** [comment]
@dakrone Not sure if the tags mean that the PR will be merged with those specific branches? If so, I though I'd mention that this PR does also work in 5.x.

**Comment by dakrone** [comment]
@loekvangool those indicate which branches this PR should be merged to, so if it goes to 5.6 then it should be merged to: `master`, `6.x`, `6.0`, and `5.6`

**Comment by dakrone** [comment]
I went ahead and cherry-picked this to the respective branches

**Pull request merged**
