### PR TITLE
Update jackson and azure

### LINKED ISSUE #66555: Hex numbers in YAML requests are treated as strings
**Elasticsearch version** (`bin/elasticsearch --version`):

```
{
  "number": "7.11.0-SNAPSHOT",
  "build_flavor": "default",
  "build_type": "docker",
  "build_hash": "00e58bef3ac3f0bd7ab68b90e38e11cac05fb49e",
  "build_date": "2020-12-15T14:29:43.737519Z",
  "build_snapshot": true,
  "lucene_version": "8.7.0",
  "minimum_wire_compatibility_version": "6.8.0",
  "minimum_index_compatibility_version": "6.0.0-beta1"
}
```

**Plugins installed**: []

**JVM version** (`java -version`):

```
{
  "version": "15.0.1",
  "vm_name": "OpenJDK 64-Bit Server VM",
  "vm_version": "15.0.1+9",
  "vm_vendor": "AdoptOpenJDK",
  "bundled_jdk": true,
  "using_bundled_jdk": true,
  "count": 1
}
```

**OS version** (`uname -a` if on a Unix-like system): Our official Docker container based on CentOS Linux 8

**Description of the problem including expected versus actual behavior**:

When Elasticsearch unmarshals YAML scalar values in hexadecimal format it interprets the value as a string, but it should be a number. For example `0x1` becomes `"0x01"` when it should a `1`. This causes problems when you expected the data type to be a number (like when reading the param value within painless).

Reference: https://yaml.org/spec/1.2/spec.html#id2766934

Relates: https://github.com/elastic/kibana/issues/85486

**Steps to reproduce**:

1. Create an ingest pipeline using `Content-Type: application/yaml`. Include a hexidecimal number.

```
curl \
  -u elastic:changeme \
  -H 'Content-Type: application/yaml' \
  -X PUT \
  "localhost:9200/_ingest/pipeline/yaml_test" \
  -d'---

description: YAML unmarshal bug demo
processors:
  - script:
      lang: painless
      params:
        number_base10: 1
        number_base16: 0x1
        string: hello
      source: >
        params.forEach((k, v) -> ctx[k] = v);'
```

2. Read the pipeline.

```
curl -u elastic:changeme -H 'Content-Type: application/yaml' -X GET "localhost:9200/_ingest/pipeline/yaml_test"
---
yaml_test:
  description: "YAML unmarshal bug demo"
  processors:
  - script:
      lang: "painless"
      params:
        number_base10: 1
        number_base16: "0x1"
        string: "hello"
      source: "params.forEach((k, v) -> ctx[k] = v);"
```

```
$ curl -u elastic:changeme -X GET "localhost:9200/_ingest/pipeline/yaml_test?pretty"
{
  "yaml_test" : {
    "description" : "YAML unmarshal bug demo",
    "processors" : [
      {
        "script" : {
          "lang" : "painless",
          "params" : {
            "number_base10" : 1,
            "number_base16" : "0x1",
            "string" : "hello"
          },
          "source" : "params.forEach((k, v) -> ctx[k] = v);"
        }
      }
    ]
  }
}
```

Note that `number_base16` is `"0x1"`. It should a 1.

### LINKED ISSUE #80142: xcontent excludes filter badcase
**Elasticsearch version** (`bin/elasticsearch --version`): master

**Plugins installed**: [] no

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. add a test in `AbstractXContentFilteringTestCase`
```
    public void testExcludesFailed() throws IOException {
        final Builder sample = builder -> builder.startObject().field("bar", "test").field("bbb", "bbb").endObject();
        Builder expected = builder -> builder.startObject().field("bar", "test").field("bbb", "bbb").endObject();
        testFilter(expected, sample, emptySet(), singleton("bar.xxx"));
    }
```
 2. throw the exception:
```
com.fasterxml.jackson.core.JsonGenerationException: Can not write a field name, expecting a value

	at __randomizedtesting.SeedInfo.seed([D5C7EEE02AA53137:388E1895E77A618D]:0)
	at com.fasterxml.jackson.core.JsonGenerator._reportError(JsonGenerator.java:2080)
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator.writeFieldName(UTF8JsonGenerator.java:220)
	at com.fasterxml.jackson.core.JsonGenerator._copyCurrentContents(JsonGenerator.java:1938)
	at com.fasterxml.jackson.core.JsonGenerator.copyCurrentStructure(JsonGenerator.java:1914)
	at org.elasticsearch.xcontent.json.JsonXContentGenerator.copyCurrentStructure(JsonXContentGenerator.java:396)
	at org.elasticsearch.xcontent.XContentBuilder.copyCurrentStructure(XContentBuilder.java:1161)
	at org.elasticsearch.xcontent.support.filtering.AbstractXContentFilteringTestCase.filterOnParser(AbstractXContentFilteringTestCase.java:87)
	at org.elasticsearch.xcontent.support.filtering.AbstractXContentFilteringTestCase.testExcludesFailed(AbstractXContentFilteringTestCase.java:94)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
```
I think the right action is passed the test.

### PR DESCRIPTION
**Pull request by nik9000**
This grabs a new version of jackson and snakeyaml to get some bug fixes.
It also updates azure to stay compatible with the new jackson.

Closes #66555
Closes #67214
Closes #80142

### CODE REVIEW

**Comment by nik9000** [comment]
There were other changes the last time we tried to update azure - https://github.com/elastic/elasticsearch/pull/73837/files#diff-0a3347d8c82d7507fa4507d2fde0f5feb4fa718a0d5025a249afbcde5621c555 - but the tests don't fail and I don't know what they were for.

**Comment by fcofdez** [comment]
Sadly we are still blocked by this issue https://github.com/Azure/azure-sdk-for-java/issues/22042 I've pinged the team several times but it seems like there hasn't been any progress on that

**Comment by nik9000** [comment]
> There were other changes the last time we tried to update azure - https://github.com/elastic/elasticsearch/pull/73837/files#diff-0a3347d8c82d7507fa4507d2fde0f5feb4fa718a0d5025a249afbcde5621c555 - but the tests don't fail and I don't know what they were for.

Adding these back helped the broken tests.

> Sadly we are still blocked by this issue [Azure/azure-sdk-for-java#22042](https://github.com/Azure/azure-sdk-for-java/issues/22042) I've pinged the team several times but it seems like there hasn't been any progress on that

@fcofdez Oh! Is there any way we can get just jackson upgraded? I really do want to get us unstuck and I don't know anything about Azure.

**Comment by nik9000** [comment]
> @fcofdez Oh! Is there any way we can get just jackson upgraded? I really do want to get us unstuck and I don't know anything about Azure.

Do we have any tests that'd fail on upgrade that I can trigger btw?

**Comment by grcevski** [comment]
> Sadly we are still blocked by this issue [Azure/azure-sdk-for-java#22042](https://github.com/Azure/azure-sdk-for-java/issues/22042) I've pinged the team several times but it seems like there hasn't been any progress on that

I know few folks on a related team, I'll reach out.

**Comment by fcofdez** [comment]
> Do we have any tests that'd fail on upgrade that I can trigger btw?

The CI job that runs the problematic test is `elastic+elasticsearch+{branch}+multijob+third-party-tests-azure-sas` but I don't know how to trigger those in a PR.

**Comment by nik9000** [comment]
>  ** elasticsearch-ci/part-1-windows ** — Build finished.

This failure is the same one we had last time we tried to update:
```
»  Caused by: java.security.AccessControlException: access denied ("java.io.FilePermission" "C:\Windows\system32\drivers\etc\hosts" "read")
```

I really don't know anything about the Azure deployment. I'd like to hand this upgrade off to someone that does. I'm many layers deep from the code I was trying to write in the first place and there are much better experts over here.

**Comment by fcofdez** [comment]
@nik9000 I can take care of this once the bug in the azure SDK is fixed

**Comment by nik9000** [comment]
> @nik9000 I can take care of this once the bug in the azure SDK is fixed

Thanks so much. I'm way out of my depth here. Or, at least, it'd take me a lot of reading to catch up.

**Comment by weizijun** [comment]
hi, @nik9000 , is it necessary to update jackson first? as the badcase in exclude exist in the current version?

**Comment by nik9000** [comment]
> hi, @nik9000 , is it necessary to update jackson first? as the badcase in exclude exist in the current version?

For now at least these are stuck together due to a breaking change in Jackson that breaks azure. It's pretty deep so I can see how the folks that made the change didn't think of it as a version change thing.

I think we're waiting on @ChrisHegarty's contacts at Azure to update to the newer version of jackson.

**Comment by ChrisHegarty** [comment]
> I think we're waiting on @ChrisHegarty's contacts at Azure to update to the newer version of jackson.

That would be @grcevski's contact. :-)

**Comment by fcofdez** [comment]
The bug was finally fixed https://github.com/Azure/azure-sdk-for-java/issues/22042 once they release a new version with the fix, I'll upgrade the libraries.

**Comment by costin** [comment]
Fwiw, jackson 2.13.1 was released 6 days ago (at the timing of writing this comment):
https://github.com/FasterXML/jackson-core/releases/tag/jackson-core-2.13.1
https://github.com/FasterXML/jackson-core/milestone/61?closed=1

**Comment by nik9000** [comment]
Once we can upgrade jackson *and* jackson released 2.14 we can fix #63842.

**Comment by nik9000** [comment]
> The bug was finally fixed [Azure/azure-sdk-for-java#22042](https://github.com/Azure/azure-sdk-for-java/issues/22042) once they release a new version with the fix, I'll upgrade the libraries.

@fcofdez do you know what version we're waiting on? I can't really tell from the linked issues.

**Comment by fcofdez** [comment]
@nik9000 We're waiting for `12.15.0`. They released a beta almost a month ago https://github.com/Azure/azure-sdk-for-java/releases/tag/azure-storage-blob_12.15.0-beta.2 I guess the final release should be around the corner.

**Comment by nik9000** [comment]
> @nik9000 We're waiting for `12.15.0`. They released a beta almost a month ago https://github.com/Azure/azure-sdk-for-java/releases/tag/azure-storage-blob_12.15.0-beta.2 I guess the final release should be around the corner.

Thanks!

**Comment by nik9000** [comment]
Overtaken by #83884

**Pull request closed without merging**
