### PR TITLE
Unexpected behavior on range queries intersecting open sets

### PR DESCRIPTION
**Pull request by not-napoleon**
While working on range field aggregations, I spotted some unexpected behavior with how open intervals work in range queries.  I'm not sure if this is a bug, or I'm just not understanding how it's intended to work.   Here's what I'm seeing:

The `RangeFieldMapper.Range` class allows for specifying boolean values `includeFrom` and `includeTo` fields.  I expected that if a document had these fields set to false, and the only intersecting point from a query was one of the end points, that document would not match the query.  E.g. if a range covers(20, 30) exclusive of end points, I would expect the query [11, 20] inclusive of endpoints not to match, because 20 is not included in the document. This is not what happens, for either start or end points.

Interestingly, if both the query and the document are set to be exclusive of the mutual end point, the query works as expected.

I've included unit tests demonstrating the issue for Long and Double range cases.

I'm happy to work on this, but I wanted to get some feedback first and make sure (a) that this is in fact a bug and not just my misunderstanding of the expected behavior, and (b) get on the same page about how we want to address the issue.

/cc @jpountz

### CODE REVIEW

**Comment by jpountz** [comment]
@notnapoleon This is in fact a bug. The index-time logic seems to ignore the value of includeFrom and includeTo, which is wrong.

**Comment by not-napoleon** [comment]
How should we address this? I'm guessing from the `nextUp()` and `nextDown()` methods on `RangeType`, the intention at one point was to convert exclusive ranges to inclusive by tightening one or both end points by one value (a trick that works in programming but not in math).  That in turn would imply that the encoded binary doc values that the query & aggregations will operate on are always inclusive.  We could implement that with relatively little code by normalizing the end points during construction of the `Range` instance, but that would leave already indexed data in an inconsistent state.  I'm not sure how big of an issue that is.

For the range histogram work I'm doing, I don't strictly need to fix this issue,  but I do need to be able to definitively know if an encoded range is inclusive or exclusive.  Since there's nothing in the encoding for that right now, and changing the encoding would be breaking, I think we just need to pick a convention and resolve this ticket in context of that convention whenever we get to it.

Thoughts?

**Comment by jpountz** [comment]
> How should we address this? I'm guessing from the nextUp() and nextDown() methods on RangeType, the intention at one point was to convert exclusive ranges to inclusive by tightening one or both end points by one value

Exactly. This comes from the fact that Lucene only exposes queries on inclusive endpoints and expects callers to do math on top of Lucene if they want to support exclusive endpoints.

> that would leave already indexed data in an inconsistent state. I'm not sure how big of an issue that is.

I don't think there is any way to fix the issue on existing indices without looking at the `_source`, which is a no-go.

**Comment by jimczi** [comment]
Should we close this PR @not-napoleon ?

**Comment by not-napoleon** [comment]
@jimczi AFAIK, this is still broken, and we still don't have a path forward.  I can write a patch to fix new ranges, but that will leave us in a state where new documents behave inconsistently with existing documents, which is possibly worse than where we are now (i.e. consistently doing the same wrong thing).  It might be something where we want to treat it as a breaking change?  IDK.  Or just rip the bandaid off and accept that data will be inconsistent.

If we think that fixing this will cause more harm than good, I'm okay with closing it.  But I've left it open because it wasn't clear to me that we didn't want to fix it.

**Comment by jpountz** [comment]
@not-napoleon I think we should fix the behavior for new ranges and document the problem for old indices since there is not much we can do. I don't think that fixing this bug would cause more harm than good.

**Comment by not-napoleon** [comment]
So I was trying to write a rest test for this, and I can no longer reproduce this behavior.  So either it got fixed at some point, or I messed up when I first had this problem. That second case is pretty likely, I was still learning a lot of how to use elasticsearch when I opened this.

Either way, I don't think there's anything to do here at this point, so I'm going to close this.

**Pull request closed without merging**
