### PR TITLE
Remove support for deprecated params._agg/_aggs for scripted metric aggregations

### PR DESCRIPTION
**Pull request by rationull**
This is the last piece of #29328, removing the behavior that was deprecated in #31597. Presumably to target 7.0.

### CODE REVIEW

**Comment by rjernst** [comment]
@elasticmachine ok to test

**Review by colings86 — APPROVED** [review]
@rationull thanks for working on this. The changes LGTM, @rjernst are you wanting to take a look too?

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by colings86** [comment]
@rationull thanks for all your work on this

**Comment by rationull** [comment]
@colings86 np, thanks for the opportunity to contribute!

**Pull request merged**
