### PR TITLE
"Settings" for IDEA

### PR DESCRIPTION
**Pull request by PnPie**
The "Preferences" dialog in Intellij is called "Settings" :) And I really tried a lot to find "Preferences" in Intellij today...

### CODE REVIEW

**Comment by dadoonet** [comment]
I do see "Preferences".

image

Which version are you using? On which platform?

**Comment by PnPie** [comment]
I used 2016.3 on Ubuntu.

**Comment by dadoonet** [comment]
May be then change `Preferences...` by `Preferences.../Settings...`?
Could you paste a screen capture of your version? Any chance you could check with latest version of IntelliJ?

**Comment by jasontedor** [comment]
This differs by OS.

**Comment by PnPie** [comment]
selection_002
selection_003
I tested on 2016.3 and the newest 2017.2, it's all "Settings". Yeah so I think on Ubuntu it's "Settings" and on Mac it's "Preferences"

**Comment by jasontedor** [comment]
We should check what it is on Windows too. Do you have a Windows machine you can check on @PnPie? If not, I can check but it will be a day until I get to checking this.

**Comment by PnPie** [comment]
Yes @jasontedor I have Windows, I'll check it soon.

**Comment by jasontedor** [comment]
Thanks a lot @PnPie. I’ll leave this to you then and then we can integrate.

**Comment by PnPie** [comment]
@jasontedor it's also "Settings" on Windows. I have Intellij 2017.1.4.

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by jasontedor** [comment]
Thanks @PnPie.

**Pull request merged**
