### PR TITLE
EQL: Clean grammar from `of` and `fork`

### PR DESCRIPTION
**Pull request by matriv**
Since `of` and `fork` are not used and there is no plan atm to implement
those features in the future, remove them from the grammar. User will
get parsing exceptions instead of higher leverl messages about
unsupported features.

### CODE REVIEW

**Comment by rw-access** [comment]
Actually will continue to support the `descendant of [...]` for Endpoint, which will have a larger/different feature set of EQL than Elasticsearch, mostly because the problem is different. We don't want to have a mysterious invalid syntax error here, because it's still EQL syntax, but it's just not a supported feature for Elasticsearch. So we need to continue to recognize this patern.

For `fork=true`, which was behavior we used but never documented officially, we could remove the syntax. But I fallback to my usual question: do we want/have to purely remove this syntax or can we continue to catch it with a custom error message?

Also the changes that were made just remove the keywords but leave stray parts of the syntax. If we did remove `fork=true` (which I think we should still have a discussion on its scoping, and think about EQL beyond just ES), then you would want to do this:
```g4
   : subquery (FORK EQ booleanValue)? (by=joinKeys)?
```

becomes
```g4
   : subquery (by=joinKeys)?
```

**Comment by rw-access** [comment]
It's a similar approach to how we handle SQL: We recognize the full syntax, but with "Not supported" error messages.

**Comment by matriv** [comment]
If `of` has a good chance to be implemented in the future in ES EQL and is already supported for endpoint, I'd agree to continue with the custom error message. For `fork` though I don't like to have support in the grammar for something that's not in the near future plan, I believe "is not supported" produces expectations that it will be supported, that's why is considered valid syntax.

And thx @rw-access  for the grammar fix regarding `fork`.

**Comment by costin** [comment]
There should be no expectation for supporting undocumented and unimplemented features. We can always add things in the features but it's hard to remove them.
Regarding relationships I'm on the fence - it is nice to provide some error message for existing queries yet there are no plans to support this in the near future for Elasticsearch EQL nor does it looks straight-forward considering it's a functionality specific to processes not any type of data.

**Review by costin — APPROVED** [review]
LGTM

**Pull request merged**
