### PR TITLE
Update vector tiles google protobuf to 3.16.1

### PR DESCRIPTION
**Pull request by iverase**
This commit updates the vector tiles google protobuf dependency to 3.16.1

### CODE REVIEW

**Comment by iverase** [comment]
Network issues:

@elasticmachine run elasticsearch-ci/part-1 
@elasticmachine run elasticsearch-ci/part-2

**Comment by iverase** [comment]
More network issues:

@elasticmachine run elasticsearch-ci/packaging-tests-unix-sample

**Review by imotov — APPROVED** [review]
LGTM

**Review by tvernum — APPROVED** [review]
LGTM

**Comment by iverase** [comment]
@elasticmachine update branch

**Pull request merged**
