### PR TITLE
Remove all unused imports and fix CRLF

### PR DESCRIPTION
**Pull request by tlrx**
The X-Pack opening and the recent other refactorings left a lot of unused imports in the codebase. This commit removes them all.

Sadly the Checktyle `UnusedImports` rule does not handle all cases when imports are made just for Javadoc, so I left it disabled for now.

This commit also fixes some CRLF that have been commited in the MultiSearchActionTookTests.java file.

### CODE REVIEW

**Review by jasontedor — APPROVED** [review]
If CI is happy, ship it.

**Comment by tlrx** [comment]
@elasticmachine test this please

**Comment by tlrx** [comment]
@elasticmachine test this please

**Comment by tlrx** [comment]
@elasticmachine test this please

**Comment by tlrx** [comment]
CI finally happy. Thanks @jasontedor

**Comment by tlrx** [comment]
Backported with best effort to 6.x in d728f16de9e6d7b00d7d106d40530b2bb7e3dc14

**Pull request merged**
