### PR TITLE
add support for javadoc in version >= 8.x

### LINKED ISSUE #94666: [Docs] add support for javadocs in version >=8
In https://www.elastic.co/guide/en/elasticsearch/reference/current/logging.html#json-logging we reference to Javadoc. 

The Javadoc root path format seems to have changed after version 8, 
before:
```
https://artifacts.elastic.co/javadoc/org/elasticsearch/elasticsearch/{version}
```
after:
```
https://artifacts.elastic.co/javadoc/org/elasticsearch/elasticsearch/{version}/org.elasticsearch.server
```

Example:
https://artifacts.elastic.co/javadoc/org/elasticsearch/elasticsearch/7.17.9/org/elasticsearch/common/logging/ESJsonLayout.html
https://artifacts.elastic.co/javadoc/org/elasticsearch/elasticsearch/8.6.2/org.elasticsearch.server/org/elasticsearch/common/logging/ESJsonLayout.html

This leads to links pointing to 404 pages.

### PR DESCRIPTION
**Pull request by alstolten**
A first try to fix #94666. Not sure if appropriate, was not able to build the docs for older versions.

### CODE REVIEW

**Review by kilfoyle — APPROVED** [review]
LGTM (just one suggested fix)! 🚀 
@alstolten  I think this will work. My question about the conditionals is that I'm not sure {minor-version} will ever be lower than 8, given that this change will only go into version 8 and higher docs. But, the conditional appears to work, so all is good. :-)

**Comment by alstolten** [comment]
I removed the unnecessary ifeval, if we backport this only to 8.x it should be not needed, as you rightly suggested. Also I added support for the path structure for SNAPSHOT releases.

**Comment by kilfoyle** [comment]
@alstolten  I neglected to add a `auto-backport-and-merge` tag, and doing so after the fact doesn't seem to work. i created a set of backports manually. If you have a free minute would you mind approving them? 

For Version 8.4 the CI checks won't pass, so I think we'd best just skip that one, but for all other 8.0 releases everything looks good.

https://github.com/elastic/elasticsearch/pull/94693
https://github.com/elastic/elasticsearch/pull/94694
https://github.com/elastic/elasticsearch/pull/94695
https://github.com/elastic/elasticsearch/pull/94700
https://github.com/elastic/elasticsearch/pull/94697
https://github.com/elastic/elasticsearch/pull/94698
https://github.com/elastic/elasticsearch/pull/94699

**Comment by rjernst** [comment]
@kilfoyle no need for review on backports unless there is something tricky in the cherry pick. Merge away!

**Comment by kilfoyle** [comment]
Thanks @rjernst! Will do. 👍

**Pull request merged**
