### PR TITLE
Remove FORCE version_type

### LINKED ISSUE #19769: Remove version type `FORCE`
The version type `FORCE` was added as an expert option to allow people to roll back changes in the external version use case where they have made mistakes in their synchronization logic.

It's a very dangerous operation as it forgoes all concurrency guarantees and may leave replicas and primaries out of sync. In hind sight I think we should not have added it and the problem goes far enough to warrant it's removal.

Note that long term, we can support this kind of thing when we move the replication logic to rely on sequence numbers for concurrency.

See for example: https://github.com/elastic/elasticsearch/issues/19692

### PR DESCRIPTION
**Pull request by dakrone**
This was an error-prone version type that allowed overriding previous
version semantics. It could cause primaries and replicas to be out of
sync however, so it has been removed.

Resolves #19769

### CODE REVIEW

**Comment by jasontedor** [comment]
LGTM.

**Comment by s1monw** [comment]
@dakrone what happens if somebody has a VersionType.FORCE document in it's translog? I think that would crash miserably? I don't think we can simply remove the type but need a bwc layer that somehow allows to read these translog entries?

**Comment by dakrone** [comment]
@s1monw good catch! I will revert this and work on some backward compatibility layer

**Comment by dakrone** [comment]
Reverted this on master, 5.x, and 5.0, I'll open a new PR once backwards compatibility logic has been added

**Comment by s1monw** [comment]
@dakrone I think you can push as is to master not since it's 6.x

**Comment by dakrone** [comment]
Okay, re-pushed this to master only

**Pull request merged**
