### PR TITLE
Do not recommend to use the _id field in search_after docs

### LINKED ISSUE #35369: search_after request documentation may be misguiding
Using the search_after request, I did follow the "recommended way" to use the `_id` property as a sorting tiebreaker. Having a string as `_id` for something near 2.000.000.000 documents and using search_after request to scroll fair amounts of documents, if I am correct, my fielddata cache did fill up with data necessary to apply the sort on my documents. To get around this problem, I just went back to sorting on integer properties (that I use to build the `_id` property...).

To me, recommending to use the `_id` property without warning against potential issues using it seems to be problematic: **should the documentation be updated to add more specific information about this case ?**

If I am not mistaken, the recommendation is only valid if using a generated `_id`, or an integer.
Also, those two documentation page seem to be conflicting:
 - https://github.com/elastic/elasticsearch/blob/master/docs/reference/search/request/search-after.asciidoc
 - https://github.com/elastic/elasticsearch/blob/master/docs/reference/mapping/fields/id-field.asciidoc

One says that using `_id` for aggregations and sorting is not recommended, the other recommends using `_id` as part of the sort tiebreaker for search_after requests.

### PR DESCRIPTION
**Pull request by jimczi**
The documentation of `search_after` recommends to use the `_id`
field as a tiebreaker for the sort without warning against the additional memory required.
This change changes the recommandation to use a copy of the `_id` field with doc_values enabled.

Closes #35369

### CODE REVIEW

**Review by cbuescher — COMMENTED** [review]
Great addition, I didn't know about this myself so far, so it is good to have this in the docs.
I like this as a general recommendation, but it requires the user to know about this caveat ahead in time when designing their index mapping. Maybe it would make sense to add a last sentence that using "_id" is still possible but comes at a price and should thus be used only as a last resort? Also maybe add a link to the "copy_to" feature maybe from the "duplicate" verb so people already get a hint what to do to set up this tie breaker field.

**Review by jimczi — COMMENTED** [review]
> Also maybe add a link to the "copy_to" feature maybe from the "duplicate" verb so people already get a hint what to do to set up this tie breaker field.

The `_id` field does not accept `copy_to` and since we have a special encoding for the `_id` field it's not something we can easily add. The duplication must happen on an ingest pipeline or client side.

> Maybe it would make sense to add a last sentence that using "_id" is still possible but comes at a price and should thus be used only as a last resort? 

We say that it is not recommended but that doesn't mean it's impossible ;). We also mention the large memory footprint if you don't follow the recommendation so I don't think we need the `last resort` wording ?

**Comment by cbuescher** [comment]
> The `_id` field does not accept `copy_to` and since we have a special encoding for the `_id` field it's not something we can easily add. The duplication must happen on an ingest pipeline or client side.

This is probably interesting information to add here, since giving the warning raises the question of how to do this instead. My first impulse would have been "copy_to" , so I guess others might think along those lines first as well. Maybe add a short clarification like this just here on the ticket then?

> We say that it is not recommended but that doesn't mean it's impossible ;). We also mention the large memory footprint if you don't follow the recommendation so I don't think we need the `last resort` wording ?

Sure, this covers it, it was more a suggestion because the formulation et least got me thinking what to do instead if I happen to want to use the "search_after" feature if I didn't plan ahead.

**Review by jimczi — COMMENTED** [review]
Thanks @cbuescher . I rephrased the recommendation to include the ingest processor alternative.

**Review by cbuescher — APPROVED** [review]
@jimczi thanks a lot for the addition, LGTM

**Pull request merged**
