### PR TITLE
Fix incorrect term in AD/LDAP docs

### PR DESCRIPTION
**Pull request by hulkk**
The dc container in this context is not domain controller, it is domain component. Schema can be checked from e.g. RFC 4519.

### CODE REVIEW

**Comment by ywangd** [comment]
@elasticmachine test this please

**Comment by ywangd** [comment]
@lockewritesdocs How far should we backport this doc change?

**Comment by lockewritesdocs** [comment]
> @lockewritesdocs How far should we backport this doc change?

@ywangd, back to `8.0` is sufficient. I added the appropriate version labels and the `auto-backport-and-merge` label so that these changes should be automagically backported.

**Comment by lockewritesdocs** [comment]
@elasticmachine update branch

**Review by ywangd — APPROVED** [review]
LGTM

**Pull request merged**
