### PR TITLE
[7.x] [ML][Data Frame] adjust onFinish audit frequency (#44450)

### PR DESCRIPTION
**Pull request by benwtrent**
Backports the following commits to 7.x:
 - [ML][Data Frame] adjust onFinish audit frequency  (#44450)

### CODE REVIEW

**Comment by benwtrent** [comment]
jenkins retest this please

**Comment by davidkyle** [comment]
@elasticmachine update branch

Build failed due to #44517

**Comment by davidkyle** [comment]
@elasticmachine update branch

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Comment by benwtrent** [comment]
run elasticsearch-ci/packaging-sample

**Pull request merged**
