### PR TITLE
Remove Cloud images from 7.16

### PR DESCRIPTION
**Pull request by pugnascotia**
We don't actually need Cloud images before v8.0, so remove all
references and supporting code.

### CODE REVIEW

**Comment by pugnascotia** [comment]
@elasticmachine run elasticsearch-ci/packaging-upgrade-tests

**Review by mark-vieira — APPROVED** [review]
LGTM. We should also be able to remove the bit that downloads beats from the CI release build.

https://github.com/elastic/elasticsearch/blob/7.16/.ci/jobs.t/elastic%2Belasticsearch%2Bperiodic%2Brelease-tests.yml#L19-L25

**Comment by pugnascotia** [comment]
@mark-vieira CI is exploding with BWC testing on version earlier than 6.8.21, and Slack is spamming me like nobody's business - any ideas?

**Comment by pugnascotia** [comment]
Infra have asked that we don't merge this until they've performed additional testing.

**Comment by mark-vieira** [comment]
> @mark-vieira CI is exploding with BWC testing on version earlier than 6.8.21, and Slack is spamming me like nobody's business - any ideas?

Looks like the upgrade tests on 7.16 are failing to download older packages. I'll look into it.

**Comment by mark-vieira** [comment]
https://github.com/elastic/elasticsearch/pull/80775 should sort out the issue with upgrade tests on 7.16.

**Pull request merged**
