### PR TITLE
Include 'sourceUrl' column in dependencies report even when empty

### PR DESCRIPTION
**Pull request by mark-vieira**
As a follow up to #56642, we now include a `sourceURL` column in the generated report for dependencies whose source we need to redistribute. For release manager to properly parse this file, entries in the CSV file which omit this item still need the `,` delimiter. This PR changes the report generation to include the `,` delimiter for the column regardless of whether column contains data.

See https://github.com/elastic/infra/pull/20555#issuecomment-634037543

### CODE REVIEW

**Review by jmlrt — APPROVED** [review]
LGTM⛴

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by mark-vieira** [comment]
@elasticmachine update branch

**Comment by mark-vieira** [comment]
@elasticmachine update branch

**Pull request merged**
