### PR TITLE
Pre-compile inline scripts in Ingest Script processors

### PR DESCRIPTION
**Pull request by talevy**
This commit introduces an optimization for inline scripts.
It keeps the compiled ingest script that the ScriptProcessor.Factory
has been creating for validation purposes. Previously, the Script Service's
cache was leveraged because it was the best way to handle caching of both
stored and inline scripts. Since inline scripts are so widely used in
Ingest Node, it is probably best to ensure we are using the pre-compiled version
from the beginning.

### CODE REVIEW

**Comment by talevy** [comment]
Hey @stu-elastic and @jdconrad 👋! I was speaking to Ryan about this improvement for inline scripts in Ingest, and we thought it would be a welcomed change. I've been away from ingest and painless land for a while and felt like pushing the change through anyways. Mind reviewing it and letting me know if I'm misusing or not using any of the scripting tools right? thanks!

**Review by stu-elastic — APPROVED** [review]
Script changes look good.  Tests look good.  Nice change.

**Review by jdconrad — APPROVED** [review]
LGTM. I wonder if with this change we still need a (large?) cache for the ingest processor scripts since it's now being cached locally.

**Comment by talevy** [comment]
thanks for taking a look team!

>  I wonder if with this change we still need a (large?) cache for the ingest processor scripts since it's now being cached locally.

that is up to you! the only thing I'll add is that caching is still being used for stored scripts. I do not know how much stored scripts are used in Ingest in practice. I suspect not a lot. It may be justified to remove support for stored scripts here entirely, but that will be breaking. Do you have any thoughts on that?

**Comment by jdconrad** [comment]
@talevy I would like to removed stored scripts altogether, but I'm not sure that's a great idea, yet, especially considering some scripts are getting quite large.

**Pull request merged**
