### PR TITLE
Speedup HealthNodeTaskExecutor

### PR DESCRIPTION
**Pull request by original-brownbear**
The introduction of this class introduced a significant regression in cluster state update performance and increased test execution times visibly. The `clusterHasFeature` check is very expensive, lets do it last and do the effectively free checks first.

### CODE REVIEW

**Comment by thecoop** [comment]
Where does the performance regression come from? It's essentially a `Set.contains` and a `NavigableMap.floorEntry` call, both of which are cheap

**Comment by original-brownbear** [comment]
@thecoop the regression comes from the unfortunate implementation of `ClusterFeatures` that builds a new instance of the features on ever CS update and then hits a lazy compute of the features set here.
We should fix that data structure to not be rebuilt on every CS update as well, but even with that fixed, this version is faster because it avoids redundant checks on the non-master nodes.

**Comment by original-brownbear** [comment]
https://github.com/elastic/elasticsearch/pull/112559 this should do it for the above issue with the features datastructure

**Review by thecoop — APPROVED** [review]
That's fair

**Comment by original-brownbear** [comment]
Thanks Simon!

**Pull request merged**
