### PR TITLE
Fixing lucene snapshot failing tests

### PR DESCRIPTION
**Pull request by benwtrent**
fixing failing tests for lucene snapshot branch

### CODE REVIEW

**Comment by benwtrent** [comment]
@ChrisHegarty I am getting a fair number of test failures from various places when reading in shards. 

Something weird with MMAP & the new Lucene snapshots?

The trace looks like: 
```

java.lang.WrongThreadException: Attempted access outside owning thread |  
-- | --
  | at java.base@22.0.1/jdk.internal.foreign.MemorySessionImpl.wrongThread(MemorySessionImpl.java:314) |  
  | at java.base@22.0.1/jdk.internal.misc.ScopedMemoryAccess$ScopedAccessError.newRuntimeException(ScopedMemoryAccess.java:113) |  
  | at java.base@22.0.1/jdk.internal.foreign.MemorySessionImpl.checkValidState(MemorySessionImpl.java:209) |  
  | at java.base@22.0.1/jdk.internal.foreign.ConfinedSession.justClose(ConfinedSession.java:82) |  
  | at java.base@22.0.1/jdk.internal.foreign.MemorySessionImpl.close(MemorySessionImpl.java:232) |  
  | at java.base@22.0.1/jdk.internal.foreign.ArenaImpl.close(ArenaImpl.java:50) |  
  | at app//org.apache.lucene.store.MemorySegmentIndexInput.close(MemorySegmentIndexInput.java:514) |  
  | at app//org.apache.lucene.tests.store.MockIndexInputWrapper.close(MockIndexInputWrapper.java:81) |  
  | at app//org.elasticsearch.core.IOUtils.close(IOUtils.java:71) |  
  | at app//org.elasticsearch.core.IOUtils.close(IOUtils.java:87) |  
  | at app//org.elasticsearch.core.IOUtils.close(IOUtils.java:63)
```

Or another one:

```
» [2024-07-15T15:52:18,429][WARN ][o.e.c.r.a.AllocationService] [javaRestTest-2] failing shard [FailedShard[routingEntry=[index-mivipjavwc-000001][1], node[-WgbV1rYSf21rwVYjwqeEg], relocating [eIpze0qFSpOpB6DVLaBRUw], [R], recovery_source[peer recovery], s[INITIALIZING], a[id=7bFVGIx6TKyEW_FWKglYxw, rId=Q92pOSuUSzaSWbniO_w6Zw], failed_attempts[0], message=failed recovery, failure=org.elasticsearch.indices.recovery.RecoveryFailedException: [index-mivipjavwc-000001][1]: Recovery failed from {javaRestTest-3}{hQQMKh5eSoitAXEcyA-gDA}{Z92lW1rhSluOYbfSPPAO9A}{javaRestTest-3}{127.0.0.1}{127.0.0.1:59224}{cdfhilmrstw}{8.16.0}{7000099-8600000}{transform.config_version=10.0.0, testattr=test, ml.config_version=12.0.0, xpack.installed=true} into {javaRestTest-2}{-WgbV1rYSf21rwVYjwqeEg}{wzEZgVTBQz237twpcadqkQ}{javaRestTest-2}{127.0.0.1}{127.0.0.1:59219}{cdfhilmrstw}{8.16.0}{7000099-8600000}{xpack.installed=true, testattr=test, ml.config_version=12.0.0, transform.config_version=10.0.0}, markAsStale=true]] org.elasticsearch.indices.recovery.RecoveryFailedException: [index-mivipjavwc-000001][1]: Recovery failed from {javaRestTest-3}{hQQMKh5eSoitAXEcyA-gDA}{Z92lW1rhSluOYbfSPPAO9A}{javaRestTest-3}{127.0.0.1}{127.0.0.1:59224}{cdfhilmrstw}{8.16.0}{7000099-8600000}{transform.config_version=10.0.0, testattr=test, ml.config_version=12.0.0, xpack.installed=true} into {javaRestTest-2}{-WgbV1rYSf21rwVYjwqeEg}{wzEZgVTBQz237twpcadqkQ}{javaRestTest-2}{127.0.0.1}{127.0.0.1:59219}{cdfhilmrstw}{8.16.0}{7000099-8600000}{xpack.installed=true, testattr=test, ml.config_version=12.0.0, transform.config_version=10.0.0}
»       at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.indices.recovery.PeerRecoveryTargetService$RecoveryResponseHandler.handleException(PeerRecoveryTargetService.java:862)
»       at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1503)
»       at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.transport.InboundHandler.doHandleException(InboundHandler.java:474)
»       at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.transport.InboundHandler$3.doRun(InboundHandler.java:466)
»       at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)
»       at org.elasticsearch.server@8.16.0-SNAPSHOT/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
»       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
»       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
»       at java.base/java.lang.Thread.run(Thread.java:1570)
»  Caused by: org.elasticsearch.transport.RemoteTransportException: [javaRestTest-3][127.0.0.1:59224][internal:index/shard/recovery/start_recovery]
»  Caused by: org.elasticsearch.common.io.stream.NotSerializableExceptionWrapper: wrong_thread_exception: Attempted access outside owning thread
»       at jdk.internal.foreign.MemorySessionImpl.wrongThread(MemorySessionImpl.java:314)
»       at jdk.internal.misc.ScopedMemoryAccess$ScopedAccessError.newRuntimeException(ScopedMemoryAccess.java:113)
»       at jdk.internal.foreign.MemorySessionImpl.checkValidState(MemorySessionImpl.java:209)
»       at jdk.internal.foreign.ConfinedSession.justClose(ConfinedSession.java:82)
»       at jdk.internal.foreign.MemorySessionImpl.close(MemorySessionImpl.java:232)
»       at jdk.internal.foreign.ArenaImpl.close(ArenaImpl.java:50)
»       at org.apache.lucene.store.MemorySegmentIndexInput.close(MemorySegmentIndexInput.java:514)
»       at org.elasticsearch.core.IOUtils.close(IOUtils.java:71)
»       at org.elasticsearch.core.IOUtils.close(IOUtils.java:87)
»       at org.elasticsearch.core.IOUtils.close(IOUtils.java:63)
»       at org.elasticsearch.indices.recovery.RecoverySourceHandler$2.close(RecoverySourceHandler.java:1426)
»       at org.elasticsearch.core.IOUtils.close(IOUtils.java:71)
»       at org.elasticsearch.core.IOUtils.close(IOUtils.java:87)
»       at org.elasticsearch.indices.recovery.MultiChunkTransfer.onCompleted(MultiChunkTransfer.java:144)
»       at org.elasticsearch.indices.recovery.MultiChunkTransfer.handleItems(MultiChunkTransfer.java:113)
»       at org.elasticsearch.indices.recovery.MultiChunkTransfer$1.write(MultiChunkTransfer.java:72)
»       at org.elasticsearch.common.util.concurrent.AsyncIOProcessor.processList(AsyncIOProcessor.java:97)
»       at org.elasticsearch.common.util.concurrent.AsyncIOProcessor.drainAndProcessAndRelease(AsyncIOProcessor.java:85)
»       at org.elasticsearch.common.util.concurrent.AsyncIOProcessor.put(AsyncIOProcessor.java:73)
»       at org.elasticsearch.indices.recovery.MultiChunkTransfer.addItem(MultiChunkTransfer.java:83)
»       at org.elasticsearch.indices.recovery.MultiChunkTransfer.lambda$handleItems$4(MultiChunkTransfer.java:120)
»       at org.elasticsearch.action.ActionListener$2.onResponse(ActionListener.java:249)
»       at org.elasticsearch.action.ActionListenerImplementations$RunBeforeActionListener.onResponse(ActionListenerImplementations.java:307)
»       at org.elasticsearch.action.ActionListener$3.onResponse(ActionListener.java:392)
»       at org.elasticsearch.action.ActionListenerImplementations$MappedActionListener.onResponse(ActionListenerImplementations.java:95)
»       at org.elasticsearch.action.ActionListenerImplementations$RunBeforeActionListener.onResponse(ActionListenerImplementations.java:307)
»       at org.elasticsearch.action.ActionListener$3.onResponse(ActionListener.java:392)
»       at org.elasticsearch.action.ActionListenerImplementations$RunBeforeActionListener.onResponse(ActionListenerImplementations.java:307)
»       at org.elasticsearch.action.ActionListener$3.onResponse(ActionListener.java:392)
»       at org.elasticsearch.action.ActionListener$3.onResponse(ActionListener.java:392)
»       at org.elasticsearch.action.support.RetryableAction$RetryingListener.onResponse(RetryableAction.java:149)
»       at org.elasticsearch.action.ActionListenerImplementations$RunBeforeActionListener.onResponse(ActionListenerImplementations.java:307)
»       at org.elasticsearch.action.ActionListener$3.onResponse(ActionListener.java:392)
»       at org.elasticsearch.action.ActionListenerResponseHandler.handleResponse(ActionListenerResponseHandler.java:48)
»       at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleResponse(TransportService.java:1493)
»       at org.elasticsearch.transport.InboundHandler.doHandleResponse(InboundHandler.java:432)
»       at org.elasticsearch.transport.InboundHandler$2.doRun(InboundHandler.java:389)
»       at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984)
»       at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
»       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
»       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
»       at java.lang.Thread.run(Thread.java:1570)
```

**Comment by ChrisHegarty** [comment]
This does indeed look like a consequence of making IOContext.READONCE effectively thread-specific. I'll take a look and see what we should do.

**Comment by ChrisHegarty** [comment]
There may be a little game of whac-a-mole here to get the tests clean.  We will need to update call-sites that use `IOContext.READONCE` since we made it single threaded in Lucene by https://github.com/apache/lucene/pull/13535

**Comment by ChrisHegarty** [comment]
Argh!!sorry @benwtrent did I goof up this PR when I merged in _main_? I'm looking into this now.

**Review by ChrisHegarty — APPROVED** [review]
LGTM

**Pull request merged**
