### PR TITLE
Refactor HyperLogLogPlusPlus to separate algorithms and internal data representation

### PR DESCRIPTION
**Pull request by iverase**
The current implementation of the HyperLogLogPlusPlus algorithm mixes up the current algorithms (Linear counting and HyperLogLog) with the internal data representation.

This PR propose to extract the algorithms into abstract class that are independent from the data representation.

### CODE REVIEW

**Review by jpountz — APPROVED** [review]
Do you need the newly introduced abstract classes to be public for follow-up changes, or could they be pkg-private? Otherwise LGTM.

**Comment by iverase** [comment]
@jpountz One of the idea of those classes is that they can be used to generate the HLL structure that can be stored in a document. So I think yes, they need to be public, what I am thinking if we should move those classes to the common package?

**Comment by jpountz** [comment]
I don't have strong feelings, it doesn't sound terrible to me to have an aggregate field type depending on logic that exists in the aggregation package.

**Comment by iverase** [comment]
good point

**Pull request merged**
