### PR TITLE
Set thread name used by REST client

### PR DESCRIPTION
**Pull request by DaveCTurner**
By default the REST client uses a thread factory which names its threads
with the generic pattern `I/O dispatcher %d`. This commit adds the
prefix `elasticsearch-rest-client-`, and a client-instance-specific ID,
to the name of these threads to make them easier to identify.

### CODE REVIEW

**Comment by DaveCTurner** [comment]
@elasticmachine please run elasticsearch-ci/part-3

**Review by swallez — COMMENTED** [review]
Should we have our own thread factory instead of wrapping the default one?

Using the default:
* will lead to having threads named `elasticsearch-rest-client-pool-<pool-counter>-thread-<thread-counter>` which although clearer than the current `I/O dispatcher <thread-counter>` could be clearer/shorter (e.g. `elasticsearch-rest-client-<pool-counter>/<thread-counter>`?)
* the deamon status of newly created threads may be different: the default factory never creates deamon threads, whereas the [current default implementation](https://github.com/apache/httpcomponents-core/blob/4.4.x/httpcore-nio/src/main/java/org/apache/http/impl/nio/reactor/AbstractMultiworkerIOReactor.java#L611), by just using `new Thread()`, will inherit the daemon status of the caller. Not sure many people rely on that, but this could create subtle issues.

**Comment by DaveCTurner** [comment]
> could be clearer/shorter

I'd rather have the `-thread-` infix, although I dropped the `-pool-` bit.

> the daemon status of newly created threads may be different

Oh good point. I thought I _was_ just modifying the default behaviour but I missed something when tracing the code to find the factory in use today. Better to just `new Thread(...) indeed I think.

**Comment by DaveCTurner** [comment]
@swallez this is good for another review now, just making sure it doesn't get lost.

**Review by swallez — APPROVED** [review]
LGTM!

**Pull request merged**
