### PR TITLE
Option to disable device type parsing in user agent processor

### LINKED ISSUE #71408: Option to switch on/off device type categorisation from the user agent processor
This [recent PR](https://github.com/elastic/elasticsearch/pull/69322) added the capability to categorise the device type from the UA string.  Whilst evaluating the accuracy of the categorisation in these early stages, it would be better for this to be controlled via a configuration option where users can opt in/out of this parsing.

ACs:
* An option to control whether or not the device type is categorised as part of the user agent processor
* By default, this will be switched off (i.e. a user has to switch this on to get device type included in the indexed document)
* If this is not switched on, then no additional processing of the device type is done (i.e. there is no additional overhead from the parsing)
* When the existing CI tests run (that expect this categorisation to be done), these should run with this configuration option switched on

### PR DESCRIPTION
**Pull request by danhermann**
Marked as "non-issue" as it updates a not-yet-released feature.

Resolves #71408

### CODE REVIEW

**Comment by danhermann** [comment]
@elasticmachine update branch

**Comment by danhermann** [comment]
@elasticmachine update branch

**Comment by danhermann** [comment]
@elasticmachine update branch

**Comment by danhermann** [comment]
cc: @elastic/es-ui in case auto-complete needs to be updated to accommodate this new option.

**Review by jbaiera — APPROVED** [review]
LGTM

**Comment by danhermann** [comment]
Thank you, @jbaiera!

**Comment by alisonelizabeth** [comment]
> cc: @elastic/es-ui in case auto-complete needs to be updated to accommodate this new option.

Thanks for the heads up @danhermann! Have the docs been updated yet? Does the below request represent how it might be used?

```
PUT _ingest/pipeline/user_agent
{
  "description" : "Add user agent information",
  "processors" : [
    {
      "user_agent" : {
        "field" : "agent",
        "extract_device_type": true
      }
    }
  ]
}
```

**Comment by danhermann** [comment]
@alisonelizabeth, yes, that is correct. The doc update PR is here: https://github.com/elastic/elasticsearch/pull/71626

**Pull request merged**
