### PR TITLE
[ML] Performance improvements for categorization jobs

### PR DESCRIPTION
**Pull request by edsavage**
Categorization of strings which break down to a huge number of tokens can cause the C++ backend process to choke - see https://github.com/elastic/ml-cpp/issues/2403.

This PR adds a limit filter to the default categorization analyzer which caps the number of tokens passed to the backend at 100.

Unfortunately this isn't a complete panacea to all the issues surrounding categorization of many tokened / large messages as verification checks on the frontend can also fail due to calls to the datafeed `_preview` API returning an excessive amount of data.

### CODE REVIEW

**Comment by droberts195** [comment]
> Also, the raw categorization field passed to the backend is truncated at 1000 characters.

Please split this part out into a separate PR so that it can be backported to 8.4 and 7.17 and it's clear what got backported and what didn't.

Also, I realised that we should truncate at 1001 characters on the Java side to preserve the behaviour that we add an ellipsis to the truncated example if truncation is necessary.

**Comment by droberts195** [comment]
There are a couple of YAML tests that need updating to reflect the change:

1. `ml/jobs_crud/Test update job`
2. `reference/ml/common/apis/get-ml-info:15` (in the docs)

**Review by droberts195 — APPROVED** [review]
LGTM

**Comment by edsavage** [comment]
@elasticmachine update branch

**Pull request merged**
