### PR TITLE
Fix test log info

### PR DESCRIPTION
**Pull request by ViggoC**
Correct the message in the log to match the code behavior.

### CODE REVIEW

**Comment by nik9000** [comment]
@elasticmachine, test this please

**Comment by idegtiarenko** [comment]
@elasticmachine ok to test

**Comment by idegtiarenko** [comment]
LGTM! Thanks @ViggoC

**Comment by idegtiarenko** [comment]
@elasticmachine update branch

**Review by idegtiarenko — APPROVED** [review]

**Pull request merged**
