### PR TITLE
Extend fields API geo formats to produce vector tiles features

### PR DESCRIPTION
**Pull request by iverase**
In https://github.com/elastic/elasticsearch/pull/73872 we have introduced a new end point that produces vector tiles. One of the actions on this new end point is to transform geo data expressed in WKT or geojson into vector tiles features. It currently works by sung the fields API to get the geo data in geojson format and then transform it to a vector tile feature while serialising the result of the query into a vector tile. 

This is currently not very efficient; We need to parse twice the shape, the first time the fields API reads the shape from source and serialise it into geojson. Then we parse it again when building the vector tile and transform it to a vector tile feature. Hence we are parsing twice the same geometry.

In this PR we propose to extend the Fields API formats for geo data in order to produce vector tiles features directly, instead of using geojson as intermediate format. It is easy to show that this bring much better performance overall and in particular is very beneficial because the compression of complex geometries when using mvt features (up to 400+ times smaller).

The main changes in this PR are:

* Currently geo formats take one geometry at a time and return an object (a string for WKT and a map for geojson). For mvt we want to access all geometries at once so we can generate the MVT of the whole geometry.  Therefore we change the signature of the geo formatters to take a list of geometries and return a list of objects. In the case of mvt, it returns always a list with one byte array.

* mvt needs some extra information in order to encode the geometry. That is the current tile and the extent (number of pixels) of the tile. The fields API does not allow to add this information easily so we take the following approach. In order to to support extra information, we allow to declare mvt formats with the following formats: `mvt(z/x/y@extent)` or  `mvt(z/x/y)` (in the last one, extent is considered the default one: 4096). 

* A extension hook for new geo formats. In order to generate mvt features, we rely in external dependencies that only exist in the vector-tile plugin. Therefore we need to be able to register the format from this plugin. In order to quickly prototype this change, I added a new method to the MapperPlugin that register new geo formats. 

Some results of this PR.

Using a data set that contains few big polygons with thousand of points each, we have run the following query for` geojson` and `mvt(0/0/0)` formats.

```
curl -X GET "localhost:9200/example/_search"  -H 'Content-Type: application/json' -d '
{
  "size" : 10000,
  "_source" : false,
  "fields" : [{"field" :"location", "format" : "{format}"}],
  "runtime_mappings" : {
      "width" : {
         "script" : "emit(doc[\"location\"].getBoundingBox().bottomRight().getLon() - doc[\"location\"].getBoundingBox().topLeft().getLon())",
         "type" : "double"
      }
   },
   "sort" : [
     {
       "width" : {"order" : "desc"}
     }
   ]
}'
```

When running with geojson, the resulting json output has a size of 438.5Mb. In addition I had to increase the heap size of the one node cluster to 4GB in order not to OOM.
When running with mvt(0/0/0), the resulting json output has a size of 1.1MB. It was run with a heap of 1GB and there was no signs of GC pressure.

When running similar queries through the _mvt endpoint, we can observe that with this change the request is twice as fast as the current one (5 min vs 2.5 min). In addition it takes much less memory to complete.

### CODE REVIEW

**Review by imotov — COMMENTED** [review]
I think this looks cleaner than my previous attempts to implement this using SPI.

**Comment by iverase** [comment]
New approach where we introduce a `GeoExtensionPlugin` instead of adding a method to the mapper plugin. In order to do that we need to add a new parameter to the IndicesModule constructor with a list of GeoExtensionPlugin.

Note that in this case we reach the formatter through the SearchExecutionContext, therefore we need to add a path:

SearchExecutionContext > MapperService > MapperRegistry > IndicesModule

**Comment by cbuescher** [comment]
I tried to get an overview over the changes needed in the core infra (e.g. SearchExecutionContext etc...) and I'm trying to understand where the need to add a new extension point (the GeoExtensionPlugin) comes from. Maybe this was discussed and discarded already, but wouldn't it be possible to always register the "mvt" formatter (and potentially more that might follow) function in core (as far as I can see this is done somewhere in IndicesModule) to make the different Geo field mappers aware of the new "mvt" formatter? 

I think generally it would be great if we didn't have to add a new kind of extension point just for this. I suspect not movin more of this code to core is done to avoid extra dependencies there, but maybe this would be solveable by moving some of the geo mappers to their own module. In general it would be great if the geo field mappers had a more direct access to the formatter functions other that through the SearchExecutionContext.

Please excuse if all of this has been discussed an decided on already in an earlier draft, I'm just trying to understand the decisions on a general level here first.

**Comment by iverase** [comment]
That is a good point @cbuescher, there has not been deeply discussed. Moving mvt into sever is not an option because it will carry some dependencies that we should not have in there. So in my view there are three options:

1) Adding an extension point as we are doing in this PR. The good think is that we don't need to move code around and there are no new dependencies. I agree the downside is that is pretty invasive on the Indices module.

2) Move the registration of geo_point to the spatial module. Note that I think is unrealistic to think we can move all the geo parts out of server easily so I don't see it as an option. On the other hand we can use the same trick we are already doing for geo_shape to move parts of the mapper out of server.  The problem is that some of the test infrastructure  depends on have geo_point in server so you need to work on this. You can check [this PR](https://github.com/elastic/elasticsearch/pull/75151) for what needs to be done. I am not a big fan of splitting the mapper between two module as it makes it very hard to test.

3) The last option is to actually move the generation of point features to server by generating them manually and not use external dependencies. The downside is that we will be forking the behaviour of protobuf into our own code so it requires more maintenance in case something change upstream.

**Comment by cbuescher** [comment]
@iverase thanks for the explanation and putting out the options. I don't have no strong opinion on these yet, so if anyone has preferences lets discuss them.

**Comment by iverase** [comment]
I open https://github.com/elastic/elasticsearch/pull/75232 which modifies the Feature factory class for points so it does not have external dependencies. This make it possible to move the generation of point features to server. This makes option 3) above possible which I am currently leaning towards.

**Comment by iverase** [comment]
superseded by #75367

**Pull request closed without merging**
