### PR TITLE
Fix CreateSnapshotRequestTests Failure

### PR DESCRIPTION
**Pull request by jdconrad**
Original test failure found here: (https://github.com/elastic/elasticsearch/issues/31625) Had to rework the tests to only include options available externally for create snapshot requests.

### CODE REVIEW

**Review by hub-cap — APPROVED** [review]

**Comment by jdconrad** [comment]
@talevy Would you mind taking a look at the toXContent method I added to IndicesOptions and see if it makes sense?  I tried to make it equivalent to the fromMap method as that's what will ultimately parse what's written out in toXContent, but I don't know a huge amount about the index options available.

**Comment by jdconrad** [comment]
@talevy  Would you please review this when you have a chance?  Thanks in advance!

**Review by talevy — APPROVED** [review]
LGTM

**Comment by jdconrad** [comment]
@talevy Thanks for the review!

**Pull request merged**
