### PR TITLE
Revert "Revert "x-pack/plugin/core: make automatic rollovers lazy""

### LINKED ISSUE #104083: Update internal unconditional rollover calls to use lazy rollover
### Description

Currently we have some of our `IndexTemplateRegistry` subclasses that invoke unconditional rollovers after templates have been upgraded. One thing that would be good to do is to make use of the recently merged [lazy rollover flag](https://github.com/elastic/elasticsearch/pull/103309) for these calls.

We can look at uses of the `applyRolloverAfterTemplateV2Upgrade()` flag to see where these are used.

### PR DESCRIPTION
**Pull request by axw**
Reverts elastic/elasticsearch#104734. https://github.com/elastic/elasticsearch/issues/104732 has been fixed, so it's safe to use lazy rollovers now.

Fixes https://github.com/elastic/elasticsearch/issues/104083

### CODE REVIEW

**Review by dakrone — APPROVED** [review]
LGTM

**Comment by axw** [comment]
@elasticmachine update branch

**Comment by axw** [comment]
/run elasticsearch-ci/windows-2019 / default-windows-archive / packaging-tests-windows-sample

**Comment by axw** [comment]
@elasticmachine update branch

**Pull request merged**
