### PR TITLE
Fix typo in AggregationProfiler

### PR DESCRIPTION
**Pull request by boicehuang**
Fix typo in AggregationProfiler

### CODE REVIEW

**Comment by pugnascotia** [comment]
@elasticmachine test this please

**Review by pugnascotia — APPROVED** [review]

**Comment by pugnascotia** [comment]
@elasticmachine update branch

**Comment by pugnascotia** [comment]
@elasticmachine run elasticsearch-ci/1 
@elasticmachine run elasticsearch-ci/bwc
@elasticmachine run elasticsearch-ci/default-distro

**Comment by pugnascotia** [comment]
@boicehuang please update your branch with the current `master`.

**Comment by boicehuang** [comment]
@pugnascotia  i have update my branch

**Comment by pugnascotia** [comment]
@elasticmachine ok to test

**Comment by pugnascotia** [comment]
Backported to `7.x` in 07a58d915dd

**Pull request merged**
