### PR TITLE
Search - reject arrays of values when passed to the Term query. 

### LINKED ISSUE #82183: Term Query syntax does not return documents/throw an error as it should
**Elasticsearch version** (`bin/elasticsearch --version`): 7.16.2

**Description of the problem including expected versus actual behavior**:

Using a term query with an array structure instead of allowed values does neither return documents nor an error message

**Steps to reproduce**:

```
DELETE test 

PUT test
{
  "mappings": {
    "properties": {
      "category": {
        "type": "keyword"
      }
    }
  }
}

PUT test/_doc/1?refresh
{
  "category": "WRITTEN_CONTENT"
}

# does not return anything, but seems a valid query
GET test/_search
{
  "query": {
    "term": {
      "category": {
        "value": [
          "WRITTEN_CONTENT"
        ]
      }
    }
  }
}

# returns document as expected
GET test/_search
{
  "query": {
    "term": {
      "category": {
        "value": "WRITTEN_CONTENT"
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by markharwood**
Use error message as an opportunity to advertise the `terms` query

Closes #82183

### CODE REVIEW

**Comment by markharwood** [comment]
I expect we should consider this a breaking change given it will cause an error in applications that were relying on the old (broken but silent) behaviour

**Comment by romseygeek** [comment]
Could we have a test as well?

Another option might be to automatically rewrite to a boolean disjunction - terms queries aren't quite the same because they are constant scoring.

**Comment by markharwood** [comment]
Thanks for reviewing, @romseygeek !

>Another option might be to automatically rewrite to a boolean disjunction - terms queries aren't quite the same because they are constant scoring.

That would certainly be less verbose than the `bool` query equivalent for those that want scoring but I'm not sure we should go there for the following reasons:
* If `term` was made to support arrays, we'd ideally rename it to make the distinction with `terms` much clearer. A flippant example being `ScoringButLimitedSetOfTermsQuery` versus `NonScoringButCanBeBigSetOfTermsQuery`.
* If `term` singular is changed to support arrays maybe `terms` plural query should similarly be changed to allow single values? These changes are about removing plurality as the distinction and making it more about scoring vs scalabiity.

The above sounds like too much change for what I suspect is a bit of an edge case and simply erroring might be the best approach?

**Comment by romseygeek** [comment]
Yes, the point where we tip from 'this is a reasonable disjunction' to 'scoring isn't helping you here' is not something that's generalizable, so erroring is fine.  I think we should point people to using a bool query rather than a terms query in the error message though, as that will preserve the scoring behaviour they would be expecting to get?

**Comment by markharwood** [comment]
> I think we should point people to using a bool query rather than a terms query in the error message though, as that will preserve the scoring behaviour they would be expecting to get?

I could point to both? Something like 

>[term] query does not support arrays for value - use a `bool` query with multiple term clauses in the `should` section or use a `Terms` query if scoring is not required.

**Comment by romseygeek** [comment]
+1

**Comment by markharwood** [comment]
Good to go with this @romseygeek?
I presume we apply to master, 8.0 and 8.x branches

**Review by romseygeek — APPROVED** [review]
LGTM!

**Pull request merged**
