### PR TITLE
[docs] Line breaks for High-level REST Client

### PR DESCRIPTION
**Pull request by olcbean**
Wrap code snippets for better display in the generated docs

### CODE REVIEW

**Review by nik9000 — CHANGES_REQUESTED** [review]
Can you add a comment to the Javadoc for the classes about the column limit?

Otherwise LGTM.

**Comment by olcbean** [comment]
@nik9000 thanks for the feedback. Can you have a look if this is this what you meant?

**Review by nik9000 — APPROVED** [review]
Perfect!

**Comment by nik9000** [comment]
I'll merge this in a bit.

**Comment by nik9000** [comment]
I've merged this to master and 6.x.

**Pull request merged**
