### PR TITLE
Remove StandardHtmlAnalyzer

### LINKED ISSUE #4704: Remove StandardHtmlAnalyzer
The StandardHtmlAnalyzer has never been documented and has been implemented with limited support for configuration.

Its functionality is easy to replicate (in a more flexible way) using the HTMLStripCharFilter, so we should remove this analyzer.

### PR DESCRIPTION
**Pull request by liketic**
Closes #4704 if this issue is not deprecated.  😄

### CODE REVIEW

**Review by cbuescher — COMMENTED** [review]
@liketic thanks for opening this PR, unfortunately I don't think removing the classes and their use is sufficient here. As  #4704 states, we need to support old indices working with this analyzer before we can entirely remove it. Fist this needs deprecation in some 5.x version, then disallowing to create new indices with this analyzer in 6.x before we can simply remove it.

**Comment by cbuescher** [comment]
@johtani I think I saw some commits where you were working on this, can you comment? If you are already working on a fix, would it can you self assign #4704?

**Comment by jasontedor** [comment]
I think that it's too late to deprecate this in 5.6 and remove in 6.x.

**Comment by liketic** [comment]
@cbuescher @jasontedor I'm OK to close this and send another PR if no one is working this.  Thanks!

**Comment by johtani** [comment]
@liketic Sorry, I will fix this next week. please send another PR...
@cbuescher Thanks for pinging me, I remember it just now.
@jasontedor Good catch. I will make PR for deprecating 6.0 and removing 7.0.

**Pull request closed without merging**
