### PR TITLE
Fix BWC issues for x_pack/usage

### PR DESCRIPTION
**Pull request by imotov**
Fixes several BWC issues in x_pack/usage discovered after introduction of the
bwc test.

Relates to #54847

@jtibshirani and @martijnvg adding you to reviewers since I had to add enrich and some parts for flatten back. 

Even though master no longer reports flatten as a feature we still can receive it from 7.x nodes during upgrade. I wasn't sure if I should add these piece back or just hard code flatten in the reader, read a string, two booleans and an int and be done with it. Please, let me know what you think.

### CODE REVIEW

**Comment by imotov** [comment]
Looks like there are still broken piece we serialize back to 7.x. I will continue digging.

**Comment by imotov** [comment]
@elasticmachine update branch

**Comment by jtibshirani** [comment]
Thanks @imotov for handling this and sorry that you ran into it. To me the approach seems okay -- I find it cleanest to just re-introduce the classes as you've done here. As a small note, perhaps we could mark the classes `@Deprecated` and add a note to remove them in 9.0.

In the PR where I naively removed `flattened` from the usage API, I also removed it from the info API (https://github.com/elastic/elasticsearch/pull/53076). So I think the same BWC issue applies to info as well. We could fix it in this PR, or I'm also happy to do it in a follow-up.

**Comment by imotov** [comment]
> As a small note, perhaps we could mark the classes @Deprecated and add a note to remove them in 9.0.

Yes! Marked them as deprecated. I wonder if we should add a test that would fail if the version is 9.0 and Flattened is still there.

>  So I think the same BWC issue applies to info as well. 

I checked info and it looks like it's all local. The only thing that goes over the wire are sting maps of strings and boolean. So, I think we should be fine. But I have added a test for it just in case I missed something there.

**Review by martijnvg — APPROVED** [review]
The enrich part looks good. Thanks for fixing @imotov.

**Review by jtibshirani — APPROVED** [review]
Looks good to me too.

**Review by polyfractal — APPROVED** [review]
LGTM3!  Thanks again for tackling all of this usage stuff :)

**Pull request merged**
