### PR TITLE
TSDB: Cleaner trigger for tsdb boundary check

### PR DESCRIPTION
**Pull request by nik9000**
This replaces the hard check for "are we in time series mode" with a
check for whether we have declared a time range for the index. It makes
me feel a little better not to have `if (mode == TIME_SERIES)` tests. I
just think they make it harder to reason about what's going on. Instead,
this code says "if there are settings declaring a time range for this
index we should enforce that range".

### CODE REVIEW

**Comment by nik9000** [comment]
@weizijun you might also want to have a look at this. It just makes me feel a little better than the other way. Not super important though.

**Review by imotov — APPROVED** [review]
LGTM.

**Comment by weizijun** [comment]
> @weizijun you might also want to have a look at this. It just makes me feel a little better than the other way. Not super important though.

LGTM. And I left a comment

**Review by martijnvg — APPROVED** [review]
LGTM 👍

**Comment by nik9000** [comment]
> LGTM. And I left a comment

@weizijun I didn't get your comment.

**Comment by weizijun** [comment]
> > LGTM. And I left a comment
> 
> @weizijun I didn't get your comment.

It's that validateTimestamp is a public method, is it to be private?

**Comment by nik9000** [comment]
> It's that validateTimestamp is a public method, is it to be private?

:+1: private is better, yeah.

**Comment by nik9000** [comment]
@elasticmachine update branch

**Comment by nik9000** [comment]
@elasticmachine update branch

**Pull request merged**
