### PR TITLE
Score Test

### PR DESCRIPTION
**Pull request by jdconrad**
Added a test for the use of the variable _score in Painless.

### CODE REVIEW

**Comment by dakrone** [comment]
Now that this is a module, could we make this a REST test instead since this is essentially an integration test? (and rest tests are a good place for those)

**Comment by rjernst** [comment]
@dakrone I don't think this is a rest test? It is testing the internals/java api of painless in how it supports _score. Really this should be a pure unit test, it just needs some more work to have the correct mocks. In the meantime, this is a single node test case (which unfortunately a large number of our unit tests are, but that is still better than having high level tests like fantasy land or rest tests for something as low level as this).

**Comment by nik9000** [comment]
I think this is fine as is. It'd be better as a unit test but I can live with this and I like having _score tested.

**Comment by dakrone** [comment]
Sure, I'm fine either way, LGTM

**Comment by dakrone** [comment]
@jdconrad want to merge this in?

**Comment by jdconrad** [comment]
Oops, forgot to close this.  It actually got merged in with (https://github.com/elastic/elasticsearch/pull/17428).  Closing now.

**Pull request closed without merging**
