### PR TITLE
Prefer joining node with conflicting transport address when becoming master

### PR DESCRIPTION
**Pull request by ywelsch**
PR #22049 changed the node update logic to never remove nodes from the cluster state when the cluster state is not published. This led to an issue electing a master (#22120) based on nodes with same transport address (but different node id) as previous nodes. The joining nodes should take precedence over conflicting ones as these nodes will also be the ones that have to commit the cluster state. Note that this only applies to the action of becoming master. If a master is established and a node joins an existing master, it will still be rejected if there is another node with same transport address.

### CODE REVIEW

**Review by abeyad — APPROVED** [review]
LGTM

**Comment by abeyad** [comment]
retest this please

**Comment by ywelsch** [comment]
Thanks @abeyad

**Comment by ywelsch** [comment]
backported to 5.2.0

**Pull request merged**
