### PR TITLE
[DOCS] Defined es-test-dir in index.asciidoc. 

### PR DESCRIPTION
**Pull request by debadair**
Use this attribute when specifying the location of included tests. 

I also updated the existing test paths.

@nik9000 added you as a reviewer since you're the only one who's using test includes so far. Mostly just want you to know I'm adding the attribute.

### CODE REVIEW

**Review by nik9000 — APPROVED** [review]
Fine by me. I'd probably call it `test-resources`. I don't  think `es` needs to be in the name because these resources are only for the docs not the rest of ES.

**Comment by lcawl** [comment]
When I added that variable in the index*.asciidoc files in https://github.com/elastic/x-pack-elasticsearch/pull/1722 it reduced the errors, however I still get the following:

```
Lisas-MBP:GitRepo lcawley$ buildxesall
*** USING lcawley-xes BRANCH ***
Building HTML from elasticsearch-extra/x-pack-elasticsearch/docs/en/index-all.asciidoc
asciidoc: ERROR: Extracting tag `expert_engine` from file `/Users/lcawley/GitRepo/elasticsearch-extra/x-pack-elasticsearch/docs/en/../../plugins/examples/script-expert-scoring/src/main/java/org/elasticsearch/example/expertscript/ExpertScriptPlugin.java`: [Errno 2] No such file or directory: '/Users/lcawley/GitRepo/elasticsearch-extra/x-pack-elasticsearch/docs/en/../../plugins/examples/script-expert-scoring/src/main/java/org/elasticsearch/example/expertscript/ExpertScriptPlugin.java'
asciidoc: WARNING: engine.asciidoc: line 20: {sys3:/opt/local/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python /Users/lcawley/GitRepo/docs/resources/asciidoc-8.6.8/../extract-tagged.py /Users/lcawley/GitRepo/elasticsearch-extra/x-pack-elasticsearch/docs/en/../../plugins/examples/script-expert-scoring/src/main/java/org/elasticsearch/example/expertscript/ExpertScriptPlugin.java expert_engine}: non-zero exit status
```

**Review by lcawl — APPROVED** [review]

**Comment by debadair** [comment]
@nik9000 Since we're entering the brave new world of cross-repo doc builds, I'm going to leave the `es-test-dir` name as-is. It's a few more characters to type, but will help minimize any confusion when it's referenced/set outside of the elasticsearch repo alongside similar attributes for other repos.

**Comment by lcawl** [comment]
Based on my tests this needs to be cherry-picked to 5.4

**Comment by lcawl** [comment]
I cherry-picked into 5.x successfully

**Comment by lcawl** [comment]
Ditto for 5.5

**Comment by lcawl** [comment]
Ditto for 5.4.  No further cherry-picking required as far as I can see.

**Pull request merged**
