### PR TITLE
Apply workaround for known issue to logsdb test data generation

### LINKED ISSUE #112966: [CI] DataGeneratorTests testDataGeneratorProducesValidMappingAndDocument failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #4055 / amazonlinux-2023_platform-support-aws](https://gradle-enterprise.elastic.co/s/lz4f3itdpdvuk)
- [elasticsearch-periodic-platform-support #4031 / windows-2016_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/gapkoea5cdrtw)

**Reproduction Line:**
```
./gradlew ":test:framework:test" --tests "org.elasticsearch.logsdb.datageneration.DataGeneratorTests.testDataGeneratorProducesValidMappingAndDocument" -Dtests.seed=FDB2A2E4C2078872 -Dtests.locale=fo -Dtests.timezone=MIT -Druntime.java=22
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testDataGeneratorProducesValidMappingAndDocument'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.logsdb.datageneration.DataGeneratorTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure Message:**
```
org.elasticsearch.index.mapper.StrictDynamicMappingException: [1:3434] mapping set to strict, dynamic introduction of [f0] within [_doc] is not allowed
```

**Issue Reasons:**
- [main] 2 failures in test testDataGeneratorProducesValidMappingAndDocument (0.8% fail rate in 252 executions)
- [main] 2 failures in pipeline elasticsearch-periodic-platform-support (28.6% fail rate in 7 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by lkts**
This change adds a workaround for #113049 to data generation in order to not repeatedly fail on it.

Closes #112966.

### CODE REVIEW

**Review by dnhatn — APPROVED** [review]
LGTM. Thanks Sasha!

**Review by martijnvg — APPROVED** [review]
LGTM

**Comment by bitomukesh** [comment]
<div>
<h2>Changelist by Bito</h2>
    <p>This pull request implements the following key changes.</p>

<div>
<table width="100%">
<tbody>
  <tr>
    <th>Key Change</th>
    <th>Files Impacted</th>
  </tr>

<tr>
<td width="30%">
    <b>Bug Fix</b> - Workaround for Copy-To Fields in Dynamic Strict Objects
</td>
<td width="70%">


<div>

-&nbsp;[`muted-tests.yml`](https://github.com/elastic/elasticsearch/pull/113214/files#diff-41386766c394f14f5f205f92bb26eb1420b80af0057c78b2842fcc7ddd3d67aa) - Removed muted test related to data generator
<div>

-&nbsp;[`DataSourceRequest.java`](https://github.com/elastic/elasticsearch/pull/113214/files#diff-231f943f3f1a0a4022a31a6f9140a192605ffee1542ab698f4115e931dab1962) - Added dynamicMapping parameter to LeafMappingParametersGenerator
<div>

-&nbsp;[`DefaultMappingParametersHandler.java`](https://github.com/elastic/elasticsearch/pull/113214/files#diff-84b6694eae3cb05c6ae557ec188dfe6ba81e960c3f0093aa7892d2d8423f9968) - Added condition to check dynamicMapping before applying copy_to
<div>

-&nbsp;[`GenericSubObjectFieldDataGenerator.java`](https://github.com/elastic/elasticsearch/pull/113214/files#diff-525e4caf8023b718f69a9f381b8ec20f5ba549d858d5300014d011980157601f) - Included dynamicMapping in method call
<div>

-&nbsp;[`PredefinedField.java`](https://github.com/elastic/elasticsearch/pull/113214/files#diff-f9f0f366da6d9e7eca6cbd55d438ef33b05f5612ae9ed5581060912fe8f78d87) - Added dynamicMapping to WithType record and LeafMappingParametersGenerator constructor
</div>
</td>
</tr>

</tbody>
</table>
</div>
</div>

**Comment by lkts** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.x|[](https://github.com/elastic/elasticsearch/pull/113305)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

**Pull request merged**
