### PR TITLE
Packaging: Split packages into maven sub-modules

### PR DESCRIPTION
**Pull request by spinscale**
This includes a couple of fixes for #11523 and thus supercedes it. Once we get this in, #11523 will be closed as well.

@tlrx can you take a look, if I missed something, I will test this under an RPM based distro using chkconfig based setup now.

### CODE REVIEW

**Comment by spinscale** [comment]
tested on centos6.5 (init.d), centos 7 (systemd), ubuntu precise (inits), ubuntu vivid (systemd).. looks good

**Comment by rjernst** [comment]
Why are the licenses/sha's under the tar distribution?

**Comment by spinscale** [comment]
maybe @dadoonet can shed some light here, as the maven portion has not been ported, I do not see an obvious reason

**Comment by rmuir** [comment]
I think the license checker just looks to inspect certain extensions?

I haven't done a in-depth picky review of this, but at a glance this PR looks wonderful. 

We can even think in the future about brainstorming how to test the different packages or something in some simple automated way...

I would love to see a followup issue where we make `distribution/shaded-jar` or something and give that tests as well, because currently thats yet another untested artifact. But if we separate it out, we could easily test that it works too.

**Comment by clintongormley** [comment]
I don't understand why the licenses are under `distribution/tar` either.  Also, the license checker will only run if there is a `$project/licenses` directory, so moving the licenses disables this check.

see: https://github.com/elastic/elasticsearch/blob/master/pom.xml#L1126

**Comment by dadoonet** [comment]
IIRC, when I created the original PR, I first decided to create 2 modules to generate `tar` and `zip` (https://github.com/spinscale/elasticsearch/commit/84680eb6fef7d603a8ab0137503e1f2212e1cbe1).

But I found then that the license checker was looking at both distributions tar and zip and was comparing some stuff. So I removed zip module and move it within tar module (https://github.com/spinscale/elasticsearch/commit/2a043c17e2528f17e6e0854915d6cb05760c8f31).

That's why all licenses are in `distribution/tar` dir.

I think we should check for each distribution (tar, zip, rpm, deb, exe)  that we have all the needed licences packaged within each artifact. Unless I totally misunderstand the purpose of the licence checker.

I did not want to touch the licence checker perl script (don't have perl knowledge TBH) but I think that licenses should be moved to `distribution/src/main/resources` so they would be shared for each package if it makes sense.

So the perl script should check if there is a `.zip` or `.tar.gz` in `release` dir and then check if all required license files are packaged. I don't really know how to do it with `rpm` or `deb` packages though.

I hope this makes sense.

**Comment by clintongormley** [comment]
At the moment, the core and plugin modules all produce a zip file, so the licence checker uses the zip file as the canonical source of truth and compares the contents of the zip file with the contents of the licenses directory.  

The core module also produces a .tar.gz.  So if a .tar.gz file exists, it is unpacked and its contents compared to the .zip. Similar functionality could be added to unpack and check the .rpm and .deb.

Is your intention that each package should be buildable independently of the others?  Or that we will always build all 4 packages? If the latter, then the license checker should just run after the packages are built, and so can use the .zip as the source of truth, no?

I don't see the reason for moving licenses into distribution/tar.

**Comment by dadoonet** [comment]
I understand. 

I think we should not have any dependency between tar module and zip module.

So tar can check if everything is correct even if we did not build yet the zip.

If you want to build the zip first, then you most likely need to add a new dependency to the zip artifact in the tar module to make sure that Maven build first the zip then others.
That said, this zip must not be included itself in packages. So may be it should be declared as a test dependency or excluded but TBH I don't like trying to hack Maven.

IMO I would simply add all licenses in distribution/src/main/resources then each distribution (which depends on this distribution parent) should use them as the source of truth.

Why did we compare the zip and tar contents instead of comparing tar and zip against licenses dir. Am I missing something?

**Comment by clintongormley** [comment]
> I think we should not have any dependency between tar module and zip module.

OK - I can modify the script to look for .zip/.tar.gz/.rpm/.deb and unpack and check whatever it finds.  This will make them independent.

> Why did we compare the zip and tar contents instead of comparing tar and zip against licenses dir. Am I missing something?

All modules build a zip.  Only core builds .tar.gz.  Comparing the contents of .tar.gz to the .zip was just easier than to the licenses directory, but easy to change that.

**Comment by tlrx** [comment]
@spinscale sorry for the time it takes me to review this.

Note that I had to change `<version>2.0.0.beta1-SNAPSHOT</version>` by `<version>2.0.0-beta1-SNAPSHOT</version>` to be able to build the packages, but once done I checked the content of every package and everything seems OK.

I tested the TAR and DEB packages on Debian 7.8, Debian 8, Ubuntu 12.04, Ubuntu 14.04 and Ubuntu 15.04: it works like a charm.

The RPM package seems to have a wrong name (see `Name` field):

- on master branch:
```
rpm -qip  elasticsearch-2.0.0-beta1_SNAPSHOT20150720132724.noarch.rpm
Name        : elasticsearch
Version     : 2.0.0
Release     : beta1_SNAPSHOT20150720132724
...
```


- on 1.7.0:
```
rpm -qip /home/tanguy/Logiciels/elasticsearch/elasticsearch-1.7.0.noarch.rpm 
Name        : elasticsearch
Version     : 1.7.0
Release     : 1
...
```

- on this pull request:
```
rpm -qip rpm/target/releases/elasticsearch-2.0.0-beta1-SNAPSHOT.rpm 
Name        : elasticsearch-2.0.0-beta1-SNAPSHOT.rpm
Version     : 2.0.0
Release     : beta1_SNAPSHOT20150720143334
...
```

Sadly it prevents me from running automated tests for RPM package.

**Comment by spinscale** [comment]
@tlrx fixed the naming issue

**Comment by tlrx** [comment]
I still had to change `<version>2.0.0.beta1-SNAPSHOT</version>` by `<version>2.0.0-beta1-SNAPSHOT</version>` to build the packages, otherwise LGTM.

Tested on CentOS6.6, CentOS7, Fedora21 and OpenSUSE13

**Comment by spinscale** [comment]
@tlrx what error did you get if you did not change the version?

**Comment by tlrx** [comment]
@spinscale Maven cannot resolve the `elasticsearch-parent` project in version `<version>2.0.0.beta1-SNAPSHOT</version>`. Anyway the current master is set to [2.0.0-beta1-SNAPSHOT](https://github.com/elastic/elasticsearch/blob/master/pom.xml#L8-9) so it has to be changed before merging.

**Comment by spinscale** [comment]
added the license checks to all distributions...

there is one last blocker, where my maven skills & understanding leave me. Right now the `mvn verify` in the core needs access to the `.zip` disitribution as it is used in the integration tests. However the generation of the zip is not yet done. Two work arounds where

* Just put the zip generation back into the core
* Move the tests ending with `IT` into the zip file distribution and run the tests from there. However there needs more to be done than just moving the class, and I am not a hundred percent sure what and how, as I dont understand what maven is doing/requiring here - maybe we just need a certain dependency here like the unpacked test jar?

@dadoonet @rmuir any pointers are appreciated

**Comment by rmuir** [comment]
Integration tests test these artifacts, that is the point of them... we take the zip of es core, unzip it, bin/plugin install any plugins, and start up bin/elasticsearch in the background and run tests against this external cluster. afterwards we shut it down.

So to me, ideally these tests would run from the .zip module. Off the top of my head:

* look in /pom.xml: maven-dependency-plugin is used to bring in the es-core.zip for the pre-integration-test phase. This dependency needs to be org.elasticsearch.distribution.
* look in /core/pom.xml: the pre-integration-test and post-integration-test logic here needs to be moved to the .zip module. now add `<skip.integ.tests>true</skip.integ.tests>` to the core module as it doesnt have any integration tests (if it is to have any, it should be against the artifacts it produces, e.g. its shaded jar) 
* other distribution formats probably need `<skip.integ.tests>true</skip.integ.tests>` at the moment too, because they are also missing them. we can give them similar tests to the zip one in the future.

Let me know if you have trouble, I can take a look at the branch too.

PS: this PR changes a lot of things like groupids. i would use grep to look for old artifacts and see if they are mentioned anywhere else in the build. otherwise it can be hell to debug when you are bringing in stale shit.

**Comment by spinscale** [comment]
I may be misunderstanding maven again here, but referring to the distribution in `/pom.xml` means, a distribution build must have been finished, which in turn also requires a a successful run integration test in the `distribution/` directory?

I will recheck the groupids,  thanks for the pointer.

**Comment by rmuir** [comment]
> I may be misunderstanding maven again here, but referring to the distribution in /pom.xml means, a distribution build must have been finished, which in turn also requires a a successful run integration test in the distribution/ directory?

It works the same as having a dependency for our purposes here. That means it comes from reactor in a multi-module build, or will download if needed. Note that pom builds don't do the copy because they have no integration tests.

**Comment by rmuir** [comment]
I pushed fixes for integration tests. But this just shows packaging is broken!

for example bin/plugin does not work from the zip.

The only reason we know this is because of integration tests. I think this is complicated enough that we need integration tests for each packaging type, that needs to block the change. otherwise its too scary to touch anything.

I am not familiar enough to know what is happening and why bin/plugin no longer works due to this change, but you can mvn install -DskipTests, then cd plugins/analysis-kuromoji and do 'mvn verify -Dskip.unit.tests' to quickly see.

**Comment by spinscale** [comment]
fixed the `/bin/plugin` issue (the shell script was duplicated), removed the wrong one and fixed the used one... `mvn clean verify` now passes when run in `/`

**Comment by spinscale** [comment]
I also moved the bats scripts around (those still need to get into CI, they are also some part of integrations tests)... 

Tested installation of the packages on ubuntu/centos and looks good

@clint from my point of view this looks ready - another review would be nice

**Comment by spinscale** [comment]
Closed by https://github.com/elastic/elasticsearch/commit/9628d2632fa39fb8aa03f5eb008a65fc4948bb1a

**Comment by dadoonet** [comment]
Thank you @spinscale for moving this PR forward. really excited to see this merged in! :)

**Pull request closed without merging**
