### PR TITLE
Remove last few mentions of Zen discovery

### PR DESCRIPTION
**Pull request by DaveCTurner**
We have a few leftover mentions of `zen` discovery, mostly for
historical/BwC reasons, which this commit removes.

Prior to this commit the default value for `discovery.type` was `zen`
but this was not written down anywhere or officially supported: the two
options were to set it to `single-node` or to omit it entirely. This
commit changes the default to `multi-node` and documents this.

### CODE REVIEW

**Comment by DaveCTurner** [comment]
@lockewritesdocs this commit deprecates setting `discovery.type: zen` which deserves an entry in the migration docs, but today there are no migration docs for 8.1.0. In this case I usually just copy the docs from the previous version but in this case the only migration docs are for 8.0.0 which don't fit the usual pattern for minor releases. Could you help me by adding deprecation docs for this change?

**Comment by lockewritesdocs** [comment]
> Could you help me by adding deprecation docs for this change?

@DaveCTurner, I added a new migration page for 8.1 with the deprecation message for `discovery.type` in 2be7b57b8296e5d5a2bcbc5e87549d7ed229538f.

**Comment by DaveCTurner** [comment]
Great, thanks Adam. Reworded slightly to avoid mentioning the legacy value at all in 9fd7b2d.

**Review by fcofdez — APPROVED** [review]
LGTM

**Comment by arteam** [comment]
Hey @fcofdez! I'd love to see the PR merged, so can I add deprecation warnings for 8.1 in #78876. Do you think it would be possible?

**Comment by fcofdez** [comment]
Sure @arteam, I can take care of merging this PR 👍

**Comment by fcofdez** [comment]
@elasticmachine update branch

**Comment by fcofdez** [comment]
@arteam I've just merged the PR 👍

**Comment by arteam** [comment]
@fcofdez Thank you!

**Pull request merged**
