### PR TITLE
Remove compareAndSet in failure handling

### PR DESCRIPTION
**Pull request by joegallo**
As requested in https://github.com/elastic/elasticsearch/pull/92308#discussion_r1048632033 (which I'm finally getting back to, yikes!).

Instead of a `compareAndSet` followed by an `accumulateAndGet`, just use a single ~`accumulateAndGet`~ `compareAndExchange` for everything.

I'm 97.5% sure the logic of this remains correct, and I think it's simpler this way, but if somebody can point out a bug in the logic or disagrees about it being simpler, I'm happy to change or close this PR.

For a bit of the history on this, see `https://github.com/elastic/elasticsearch/pull/23969` (code highlighting to avoid a github reference being added), as well as #37649 and #53262.

### CODE REVIEW

**Review by DaveCTurner — COMMENTED** [review]
This all seems very complicated compared with the approach in `RefCountingListener`. Either this can be simplified, or `RefCountingListener` has a bug...

https://github.com/elastic/elasticsearch/blob/d875dc29f33e5351658cbbaef8c3beafb9a14d5a/server/src/main/java/org/elasticsearch/action/support/RefCountingListener.java#L215-L218

**Comment by joegallo** [comment]
I'm good with that solution. `addSuppressed` is already synchronized, so I think your approach would work fine.

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Review by thecoop — APPROVED** [review]
Looks sensible!

**Pull request merged**
