### PR TITLE
Rename simple pattern tokenizers

### PR DESCRIPTION
**Pull request by andyb-elastic**
Changed names to be snake case for consistency

For #25159

### CODE REVIEW

**Review by nik9000 — COMMENTED** [review]
I'm fairly sure you have to also change CommonAnalysisFactoryTests and AnalysisFactoryTestCase to get this to work properly.

**Comment by andy-elastic** [comment]
It's AnalysisFactoryTestCase where that SPI lookup is happening so that's why I left it. As far as I can tell it's not really using the factory for anything, just seeing that we've marked it as one that we've implemented somewhere

Re https://github.com/elastic/elasticsearch/pull/25159#issuecomment-309521530 let me take another look and see if I can do that

**Comment by nik9000** [comment]
I *thought* the names had to line up.

**Comment by andy-elastic** [comment]
The test that's failing is [`testMultiTermAware`](https://github.com/andy-elastic/elasticsearch/blob/428e70758ac6895ac995f4315412f4d3729aea9b/test/framework/src/main/java/org/elasticsearch/indices/analysis/AnalysisFactoryTestCase.java#L366). It looks like what it's doing is for each analysis component is finding its Lucene (not ES) factory by SPI lookup and checks to see if the ES counterpart factory class agrees about implementing `MultiTermAwareComponent`.

I don't see an obvious place to hook into the SPI lookup, but maybe I'm missing something. I could change that test so that we specify the Lucene factory class directly rather than looking it up.

I'm happy to change this test and make the names consistent for all the components, I think that would broaden the scope of this PR though.

**Comment by nik9000** [comment]
Ah. I see it. That is weird! For the pre-built components that names have to line up. That is part of what makes the test useful. For the others you are right - the keys need to match watcher the SPI lookup mechanism needs.

**Review by nik9000 — APPROVED** [review]

**Pull request merged**
