### PR TITLE
Add read privileges for observability-annotations for apm_user

### PR DESCRIPTION
**Pull request by dgieselaar**
Closes elastic/kibana#69642. See also elastic/kibana#69881.

In elastic/kibana#64796, we added support for annotations (and a public API to create them) in the APM UI. Annotations are stored (by default, but configurable) in `observability-annotations`. We've documented that users need access to the `observability-annotations` index to create annotations via the API, but neglected to do so for using the UI. 

To ensure a great out-of-the-box experience we'd like to add read privileges for this index by default.

### CODE REVIEW

**Review by sorenlouv — APPROVED** [review]

**Comment by sqren** [comment]
Lgtm but you'll need someone from the ES side to 👍 this too.

**Review by tvernum — COMMENTED** [review]
I'm happy with with the intent of the change, but we need to also update `ReservedRolesStoreTests.testAPMUserRole` to reflect the change.

**Comment by dgieselaar** [comment]
@tvernum I've added a test - LMK if that's good enough.

**Review by tvernum — APPROVED** [review]
LGTM

**Comment by tvernum** [comment]
@dgieselaar I added labels, including version labels. Can you confirm that they reflect the releases you intend to target?

**Comment by dgieselaar** [comment]
@tvernum we'd also like to get this in for 7.8.1, is that possible?

**Comment by tvernum** [comment]
Thanks fine. I've updated the labels.

**Comment by dgieselaar** [comment]
thanks @tvernum! Ok for me to merge & backport?

**Comment by tvernum** [comment]
Yes, go ahead.

**Pull request merged**
