### PR TITLE
Service Accounts - auditing tests for existing fields

### PR DESCRIPTION
**Pull request by ywangd**
This PR ensure existing auditing tests cover service account authentication. It makes sure compatible existing fields also work for service accounts.

### CODE REVIEW

**Comment by ywangd** [comment]
@tvernum We have a task says "auditing for creating API based token". But I don't think it needs any specialised tests. The existing tests in `LoggingAuditTrailTests` are generic and should cover any old or new actions.

**Comment by tvernum** [comment]
> We have a task says "auditing for creating API based token". But I don't think it needs any specialised tests

I think we're good because the name of the token is included in the request so the audit should be fine. It's probably worth looking at the audit log and making sure there's no surprises, but I'm happy not to have specific tests.

**Review by tvernum — APPROVED** [review]
LGTM

**Comment by ywangd** [comment]
@elasticmachine update branch

**Comment by ywangd** [comment]
@elasticmachine update branch

**Pull request merged**
