### PR TITLE
fix object equals

### PR DESCRIPTION
**Pull request by wjwei**
fix object equality issue.

### CODE REVIEW

**Comment by luigidellaquila** [comment]
Thank you for your contribution @wjwei, the fix makes definitely sense.
Out of curiosity, did you identify the problem inspecting the code or is it the result of a runtime failure?
Please, also make sure you sign the CLA, otherwise we won't be able to merge the PR

Thanks

Luigi

**Review by luigidellaquila — APPROVED** [review]

**Comment by wjwei** [comment]
Thanks for your acknowledgment, I found the problem while reading the source code. I have signed the CLA.

**Comment by wjwei** [comment]
> 
image
Hi @luigidellaquila 
I do have the CLA signed, above is the screenshot. I don't know why it's still red, is it wrong that I signed it?

**Comment by wjwei** [comment]
Hi @luigidellaquila 
If there are no other questions, can you help me merge it? thanks~

**Comment by astefan** [comment]
@wjwei Can you include the following releases notes in docs/changelog/87887.yaml?

```
pr: 87887
summary: fix object equals
area: SQL
type: bug
issues:
 - []
```

**Comment by astefan** [comment]
@elasticmachine generate changelog

**Comment by wjwei** [comment]
> @wjwei Can you include the following releases notes in docs/changelog/87887.yaml?
> 
> ```
> pr: 87887
> summary: fix object equals
> area: SQL
> type: bug
> issues:
>  - []
> ```
@astefan I have submitted the changelog. please review, thanks

**Review by astefan — APPROVED** [review]
LGTM

**Pull request merged**
