### PR TITLE
Add ignore_above for message.raw field in notifications index mappings

### PR DESCRIPTION
**Pull request by gaobinlong**
Relates to #63888 .

Setting `ignore_above` to 1024 by default for the `message.raw` field  in `.ml-notifications-*` and `.transform-notifications*` indices's  mappings, in order to prevent indexing failed when the content length of the field exceeds the limit of keyword type.

### CODE REVIEW

**Comment by davidkyle** [comment]
@elasticmachine test this please

**Comment by davidkyle** [comment]
Hi @gaobinlong 

Thanks for creating this PR. I've started the CI tests and once they pass the PR is good to merge

**Review by davidkyle — APPROVED** [review]
LGTM

**Comment by davidkyle** [comment]
The test failure is due a check that the index mappings are the same as the template mappings after a cluster rolling upgrade. In this case the test has done exactly what is should and found the discrepancy.

```
java.lang.AssertionError: Error the template mappings [.ml-notifications-000001] and index mappings [.ml-notifications-000001] are not the same
Keys in the template missing from the index mapping: [properties.message.fields.raw.ignore_above]
```


@gaobinlong can you add an exception to [IndexMappingTemplateAsserter.assertMlMappingsMatchTemplates](https://github.com/elastic/elasticsearch/blob/91f4b58bf71249cf81562bd6069c64aafa46591b/x-pack/qa/src/main/java/org/elasticsearch/xpack/test/rest/IndexMappingTemplateAsserter.java#L56) for the new `ignore_above` parameter. 

Something like 
```
        Set<String> notificationIndexExceptions = new HashSet<>();
        notificationIndexExceptions.add("properties.message.fields.raw.ignore_above");
```

Then pass that set instead of `Collections.emptySet()` to the function called on line 91
```
        assertLegacyTemplateMatchesIndexMappings(client,
            ".ml-notifications-000001", ".ml-notifications-000001", true, notificationIndexExceptions, false);
```

The exception can be removed once this change is backported to 7.x

**Comment by davidkyle** [comment]
@elasticmachine test this please

**Comment by droberts195** [comment]
@elasticmachine update branch

**Comment by davidkyle** [comment]
@elasticmachine test this please

**Comment by davidkyle** [comment]
The full cluster restart test failed again because the exceptions are only applied to the index mappings and not vice versa to the template mapping. 

https://github.com/elastic/elasticsearch/blob/91f4b58bf71249cf81562bd6069c64aafa46591b/x-pack/qa/src/main/java/org/elasticsearch/xpack/test/rest/IndexMappingTemplateAsserter.java#L199 

`keysInTemplateMissingFromIndex.removeAll(exceptions);` should be added to the above code.

Usually we are testing that the index mappings do not contain fields that are not defined in the template as this means those fields have be created dynamically. In this case it is not a problem that the template has `properties.message.fields.raw.ignore_above` as it will be correctly applied to new indices. 

@gaobinlong, I'm sorry this change is proving to be more complicated than expected. Could you please make the change above to remove the exceptions from the template mappings.

**Comment by gaobinlong** [comment]
@davidkyle ， I have done that, and `MlConfigIndexMappingsFullClusterRestartIT` executed successfully on my local computer.

**Comment by davidkyle** [comment]
@elasticmachine test this please

**Comment by davidkyle** [comment]
Yay the tests have passed 🚀 

@gaobinlong thank you very much this PR can be merged now

**Pull request merged**
