### PR TITLE
Dry up AbstractBytesReference.length implementations

### PR DESCRIPTION
**Pull request by original-brownbear**
All the length implementations are the same so we can dry this up which might provide a speedup here and there since it gets us down to only two possible implementations of `BytesReference.length()` (releasable and normal ref) which should inline in most places.

### CODE REVIEW

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/part-1

**Review by idegtiarenko — APPROVED** [review]

**Comment by original-brownbear** [comment]
Jenkins run  elasticsearch-ci/part-1

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/part-2

**Comment by original-brownbear** [comment]
Jenkins run 
elasticsearch-ci/bwc

**Review by arteam — APPROVED** [review]
LGTM

**Comment by original-brownbear** [comment]
Thanks both!

**Pull request merged**
