### PR TITLE
Remove size 0 options in aggregations

### LINKED ISSUE #18838: Remove ability to specify `size: 0` on aggregations
Currently `size: 0` is used as an alias for `get me all the buckets` on the `terms`, `significant_terms` and `geohash_grid` aggregations. This is very trappy as it hides the fact that this is actually a really bad idea which, for high cardinality fields will use a lot of memory and stream huge amounts of data from the shards back to the coordinating node to reduce. It cost huge amounts in CPU (for the reduce), memory (on both the shards and the reduce node) and network bandwidth. It also has the ability to starve the node of resources potentially destabilising the cluster (either through creating a lot of garbage to be collected which could trigger stop the world GC pauses or through tying up the CPU or network and blocking the liveness pings back to the master.

Having `size: 0` as an option makes it look like there is a short cut here and we can do the `give me all the buckets` case in a different very efficient way, which we can't. Internally we rewrite `size:0` to `Integer.MAX_VALUE`

Removing this option (`size: 0`) and requiring the user to specify a number means it becomes more obvious that asking for huge number of bugs will incur a high cost by the very fact that the user actually has to ask for that high number. 

The only case (IMO) for asking for all buckets of a terms agg back which is not a bad idea is when you have a low cardinality and in that case you almost always know, at least to an order of magnitude, how many values you expect (usually <10, 10s or low 100s). In these cases having to specify a size is not a big burden as you can still set it to a number higher than you expect (e.g. for 10s of values set size to 200) and in the case where there is a bug and your low cardinality field accidentally becomes very high cardinality you are protected against doing a very heavy operation. Other use-cases should not be asking for all buckets but instead should be slicing and analysing the data in a way where they do not need to ask for everything (you can't show that much information to a user anyway).

### PR DESCRIPTION
**Pull request by colings86**
This removes the ability to set `size: 0` in the `terms`, `significant_terms` and `geohash_grid` aggregations for the reasons described in https://github.com/elastic/elasticsearch/issues/18838

Closes #18838

### CODE REVIEW

**Comment by colings86** [comment]
@jpountz do you have time to review this?

**Comment by jimferenczi** [comment]
Left one minor comment, LGTM otherwise

**Comment by colings86** [comment]
@jimferenczi thanks for the review. I pushed a commit to address your comment. Waiting for tests to pass but will push to master as soon as they do

**Comment by jpountz** [comment]
LGTM2

**Comment by colings86** [comment]
Deprecation logging added to 2.x in https://github.com/elastic/elasticsearch/commit/ca416f26758c406e948e70703b523423771cf146
Deprecation logging added to 2.4 in https://github.com/elastic/elasticsearch/commit/90d7c685122ae505b0c6f85f609f6051ce207968

**Pull request merged**
