### PR TITLE
[DOCS] disable the ILM history store on full cluster restore

### PR DESCRIPTION
**Pull request by andreidan**
When restoring a full cluster there might be issues with the snapshot containing the
ilm-history data stream and, even though deleted from the elasticsearch cluster and ILM stopped, the history
data stream reappearing due to late processing of ILM history events.

This documents disabling the history index so that the data stream is not recreated and restoring
the snapshot doesn't fail due to the data stream already being present in the cluster.

### CODE REVIEW

**Review by dakrone — CHANGES_REQUESTED** [review]
looks good, but on line 435 we need to add it to the list of settings to re-enable after the restore has completed

**Comment by andreidan** [comment]
> looks good, but on line 435 we need to add it to the list of settings to re-enable after the restore has completed

Crikey! Good spot. I missed that even though I ctrl-f-ed for "start ILM" :)

**Review by dakrone — APPROVED** [review]
LGTM, thanks!

**Comment by andreidan** [comment]
@elasticmachine update branch

**Pull request merged**
