### PR TITLE
Painless: Fix Semicolon Regression

### PR DESCRIPTION
**Pull request by jdconrad**
Trailers (statements following something like an if statement) that don't use brackets currently require a semicolon even if they're the last statement.  This is a regression caused  by (https://github.com/elastic/elasticsearch/pull/29566) and noted by (https://github.com/elastic/elasticsearch/issues/33193).  This change fixes the regression and adds a test for the broken case.

Note most of the lines are ANTLR regeneration and the only relevant files are PainlessParser.g4 and the added/updated tests.

### CODE REVIEW

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by jdconrad** [comment]
@rjernst Thanks for the review, will commit as soon as CI passes.

**Comment by jdconrad** [comment]
@elasticmachine test this please

**Review by nik9000 — APPROVED** [review]
LGTM

**Comment by jdconrad** [comment]
@nik9000 Thanks for the review!

**Pull request merged**
