### PR TITLE
Build: Fix reproduce info for methods with ( or )

### LINKED ISSUE #35692: Task integTest can not run individual tests with parenthesis in name
**Elasticsearch version** (`bin/elasticsearch --version`):  Tested with `6.4.3`.

Say I have rest api test file with the following content:
```
$ head -n 2 src/test/resources/rest-api-spec/test/resthandler/10_Foo.yml
---
"Bar (Hello)"
```

When I run complete integration tests using `gradle clean check`, everything goes fine.

But if I use `integTest` task to run specific test like this:

```
gradle :integTest \
  -Dtests.class=org.elasticsearch.rest.SomeYamlTestSuiteIT \
  -Dtests.method="test {yaml=resthandler/10_Foo/Bar (Hello)}"
```
This ends with:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':integTestRunner'.
> There were no executed tests: 1 suite (1 ignored), 0 tests
```
However, if I remove parenthesis from the test name (i.e. I modify second line in `10_Foo.yml` file) and run:

```
gradle :integTest \
  -Dtests.class=org.elasticsearch.rest.SomeYamlTestSuiteIT \
  -Dtests.method="test {yaml=resthandler/10_Foo/Bar: Hello}"
```
then it works as expected.

### PR DESCRIPTION
**Pull request by nik9000**
Our `REPRODUCE WITH` line wasn't working for tests with `(` or `)` in
the method name. This isn't super common, but happens sometimes for our
yml based rest tests. This is because randomized runner's globbing
mechanism doesn't escape `(` or `)`. We can't escape the `(` or `)` so
we use the single character glob `?` to match them. This isn't perfect,
but it is much better than missing the method entirely.

Closes #35692

Works around an issue I filed upstream as:
https://github.com/randomizedtesting/randomizedtesting/issues/271

### CODE REVIEW

**Review by rjernst — APPROVED** [review]
This looks fine, but I wonder if as a followup we should replace the "method name" from rest tests with something like the `lineNN` that we did with generated docs rest tests? The line number is something I find much easier to jump to than needing to copy past a string with spaces in it to search for in the file.

**Comment by nik9000** [comment]
@rjernst, @dweiss got to this before me and fixed randomizedtesting. I've bumped its version instead.

> This looks fine, but I wonder if as a followup we should replace the "method name" from rest tests with something like the `lineNN` that we did with generated docs rest tests?

We could get the line number, I think. The reason we do it in the docs is that the snippets don't have names so it is all that we *can* do. I'm quite used to finding things by line number and name at this point, but I can see the merit in removing a second way of doing things.

**Comment by nik9000** [comment]
@rjernst, could you have another look at this one?

**Review by rjernst — APPROVED** [review]
LGTM

**Pull request merged**
