### PR TITLE
TransportVerifyShardBeforeCloseAction should force a flush

### PR DESCRIPTION
**Pull request by tlrx**
This commit changes the `TransportVerifyShardBeforeCloseAction` so that it always forces the flush of the shard. It seems that #37961 is not sufficient to ensure that the translog and the Lucene commit share the exact same max seq no and global checkpoint information in case of one or more noop operations have been made.

The `BulkWithUpdatesIT.testThatMissingIndexDoesNotAbortFullBulkRequest` and `FrozenIndexTests.testFreezeEmptyIndexWithTranslogOps` test this trivial situation and they both fail 1 on 10 executions.

Relates to #33888

### CODE REVIEW

**Review by ywelsch — APPROVED** [review]

**Comment by tlrx** [comment]
@elasticmachine run elasticsearch-ci/2
@elasticmachine run elasticsearch-ci/1
@elasticmachine run elasticsearch-ci/default-distro

**Comment by tlrx** [comment]
@ywelsch Sorry, I didn't notice among the recent CI failures that the `restore` REST YAML tests required to be adjusted with this change: now the flush is forced when closing the index, local files differs from the files that have been snapshotted and it shows up in the recovery stats. Can you please have a look at the changes in tests? Thanks

**Review by ywelsch — APPROVED** [review]
LGTM

**Comment by tlrx** [comment]
Thanks @ywelsch

**Pull request merged**
