### PR TITLE
[DOCS] Clarify BWC of monitoring clusters

### LINKED ISSUE #63039: Doc: Backwards compatibility of monitoring clusters
https://www.elastic.co/guide/en/elasticsearch/reference/current/monitoring-production.html#monitoring-production

image

This question comes up a lot from the field (esp. when new versions get released).
We mention that monitoring a 7.x cluster requires a 7.x monitoring cluster.

It is quite common for users to upgrade monitoring clusters first to a newer version.  I believe we intend to support monitoring a 6.x cluster using a 7.x monitoring cluster as well.  In other words, the monitoring cluster is 1 major version backwards compatible with the monitored cluster.  Would be nice to confirm that there are no edge case exceptions and document this accordingly.  Thx!

### PR DESCRIPTION
**Pull request by lcawl**
Fixes https://github.com/elastic/elasticsearch/issues/63039

### Preview

https://elasticsearch_63151.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/monitoring-production.html

### CODE REVIEW

**Comment by ravikesarwani** [comment]
Thanks Lisa for you help on this.
Overall the change looks good. The only thing I was thinking is the usage of 8.x and 7.x. As the release number changes over time I was thinking if we need to write it in more neutral fashion or call out release number only as example, say in parenthesis.

**Comment by lcawl** [comment]
> As the release number changes over time I was thinking if we need to write it in more neutral fashion ...

These numbers are accomplished via attributes, so they'll be automatically updated over time. This is easier than remembering to manually update for each new major release.

**Comment by ravikesarwani** [comment]
Thank you Lisa. It does say 8.0 which we won't have for a little while. Should it say 7 & 6 for now. When 8.0 is released then it can say 8 & 7.

**Comment by lcawl** [comment]
>  It does say 8.0 which we won't have for a little while.

Yup, this is the master branch, so when I backport this to the 7.* branches I'll double-check that it shows the appropriate branches there too.

**Comment by ravikesarwani** [comment]
Makes sense, thanks for the clarification.

**Review by ravikesarwani — APPROVED** [review]
Looks good.

**Pull request merged**
