### PR TITLE
Remove artificial default processors limit

### LINKED ISSUE #20828: Bounding the processors count to 32 still valid?
Following https://github.com/elastic/elasticsearch/issues/3478 we limited the maximum number of processors on which the thread pools are created to 32. Since that version of ES this was observed on, many more versions (with many improvements) were released.

Is this limitation still valid?
I would think yes, but this raises two more issues that might need some thought:
- is there a **minimum** memory size (RAM or HEAP?) above which we can safely increase this count to the real number of cores using the **processors** setting?
- does this issue apply for smaller than 32 values? For example, a machine with 2GB RAM and 16 cores would have similar issues?

### PR DESCRIPTION
**Pull request by jasontedor**
Today Elasticsearch limits the number of processors used in computing
thread counts to 32. This was from a time when Elasticsearch created
more threads than it does now and users would run into out of memory
errors. It appears the real cause of these out of memory errors was not
well understood (it's often due to ulimit settings) and so users were
left hitting these out of memory errors on boxes with high core
counts. Today Elasticsearch creates less threads (but still a lot) and
we have a bootstrap check in place to ensure that the relevant ulimit is
not too low.

There are some caveats still to having too many concurrent indexing
threads as it can lead to too many little segments, and it's not a
magical go faster knob if indexing is already bottlenecked by disk, but
this limitation is artificial and surprising to users and so it should
be removed.

Closes #20828

### CODE REVIEW

**Comment by jasontedor** [comment]
I've targeted this for 5.1.0, but I think that da92de718d933119e5091192a4e0456649dc2537 should be backported to 5.0.0 or users will have a rude awakening when they upgrade to 5.1.0 if they've already adjusted their ulimit to 2048.

**Comment by jasontedor** [comment]
@mikemccand Are you interested in reviewing?

**Comment by bleskes** [comment]
Tracing through history, it seems the original issue was about the transport client. Maybe it makes sense to set a bounded default in the client alone?

**Comment by mikemccand** [comment]
LGTM, thanks @jasontedor!

**Review by jpountz — APPROVED** [review]
LGTM

**Comment by jpountz** [comment]
> I've targeted this for 5.1.0, but I think that da92de7 should be backported to 5.0.0 or users will have a rude awakening when they upgrade to 5.1.0 if they've already adjusted their ulimit to 2048.

How bad would it be to only push this commit to 6.0?

**Comment by jasontedor** [comment]
> How bad would it be to only push this commit to 6.0?

It just means another year of living with this limitation.

**Comment by jpountz** [comment]
I'm not sure I was clear, but I was commenting specifically about the change to the BootstrapCheck. Said otherwise: how about removing the 32 limit in 5.1 and requiring an increase to the ulimit only in 6.0? We could potentially revisit the idea to better share thread pools in 5.1 to make the number of threads less of an issue.

**Comment by bleskes** [comment]
I think that is this stage (rc is out), we need to ask a different question  -  Does it really need to go into 5.0?. I think if we’re honest, the answer is no?

**Comment by jasontedor** [comment]
> I'm not sure I was clear, but I was commenting specifically about the change to the BootstrapCheck. 

It definitely was not clear; I spoke with @s1monw via another channel and I think that he interpreted the same way that I was interpreting it (to keep the limitation until 6.0.0).

> Said otherwise: how about removing the 32 limit in 5.1 and requiring an increase to the ulimit only in 6.0?

It's worth considering.

**Comment by jasontedor** [comment]
@bleskes It's not clear what you're commenting on; the processor limitation removal is not targeted for 5.0, just the bootstrap check change as otherwise users might have to set the ulimit twice: once on upgrade to 5.0, and again on upgrade to 5.1.

**Comment by s1monw** [comment]
What about this, we wait with boostrap checks until 6.0 and make the hardlimit a softlimit in 5.1 then users that have such a high CPU count can set it higher but it's bound by default. We can also to support users print a warning message that they should consider raising this limit. I am not a fan of changing something like this in a minor release

**Comment by bleskes** [comment]
>  @bleskes It's not clear what you're commenting on;  the processor limitation removal is not targeted for 5.0.0, 

I see. Then it's good in that respect.  I'm still hesitant about changing the ulimit as well - I'm not sure bootstrap checks should make everyone account for the largest use case possible.  One other idea I had is to take `Runtime.getRuntime().availableProcessors()` into account when determining the lower bound limit. That said -  we haven't released this yet so I tend to prefer having the least restrictive and simplest option first and see how it goes.

**Comment by jasontedor** [comment]
> I'm not sure bootstrap checks should make everyone account for the largest use case possible.  One other idea I had is to take `Runtime.getRuntime().availableProcessors()` into account when determining the lower bound limit. That said -  we haven't released this yet so I tend to prefer having the least restrictive and simplest option first and see how it goes.

@bleskes Before opening this PR, I did toy with exactly this idea. It's fine, it works, but I opted exactly for the simplest approach because the [default](http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/kernel/fork.c?id=v4.5#n271) on most systems is already quite large (total number of pages / 64); any x86 system with more than 1 GB of memory will have its defaults above the limit enforced here.

**Comment by bleskes** [comment]
>  the default on most systems is already quite large (total number of pages / 64); any x86 system with more than 1 GB of memory will have its defaults above the limit enforced here.

All goed then!

**Comment by jasontedor** [comment]
> What about this, we wait with boostrap checks until 6.0 and make the hardlimit a softlimit in 5.1 then users that have such a high CPU count can set it higher but it's bound by default.

It's a soft limit today.

We discussed this during Fix-it-Friday and agreed to push this to 6.0.0 only since there is a workaround for the limit in the 5.x series already (see #20895).

**Pull request merged**
