### PR TITLE
Fork to MANAGEMENT for ILM cache cleanup operations

### PR DESCRIPTION
**Pull request by original-brownbear**
No need to run this synchronously. The loop setting up the deleted indices list
takes quite a while for large clusters (1%+ of CPU time and more than that in wall time
during many-shards benchmark bootstrapping)
during many shards benchmark bootstrap. There's no value in running the cleanup in-sync
on the applier thread, so we can just fork off and save the time.

relates #77466

### CODE REVIEW

**Comment by dakrone** [comment]
@original-brownbear should the `indicesDeleted()` method on the `ClusterChangedEvent` be memoized so that its computation is not expensive more than once? (The helpfulness would obviously depend on how many times we use it, so we'd need to determine whether it's worth the cost). Are there other event methods that could be memoized?

**Comment by original-brownbear** [comment]
@dakrone currently this is the only spot where we use this list by the master role so it wouldn't help here. Likewise, for the data role we only have one usage as well.
So memoizing would only help if we have both roles, but in that case we probably don't have enough indices for it to matter.

**Review by dakrone — APPROVED** [review]
Makes sense, thanks for the info.

**Comment by original-brownbear** [comment]
Np + Thanks Lee

**Pull request merged**
