### PR TITLE
fix query string example for boolean query

### PR DESCRIPTION
**Pull request by fbaligand**
Replace `(ny OR (new AND york)) city)` by `city:(ny OR (new AND york))`

### CODE REVIEW

**Comment by javanna** [comment]
hi @fbaligand thanks for sending a PR. I think that the example is correct as-is though. `city` in the example query is a word that we are searching for rather than the field name to search against.

**Comment by fbaligand** [comment]
Hi @javanna, 

Why I really think it is a mistake : 
- first, the text below the example which explains it, doesn't mention 'city' and mention only 'ny' and 'new york'
- secondly, with this example query, a document with only "city" term will match the query
- thirdly, if you look at the initial example, there is 3 `)` for 2 `(`

**Comment by javanna** [comment]
heya @fbaligand  thanks for clarifying, I am reopening this. I still think that city was meant to be part of the query, yet even in that case the explanation and the parentheses would need to be fixed. 

@jimczi given that you added this example a while ago, what do you think?

**Comment by fbaligand** [comment]
Thanks for reopening the issue !

Concerning ‘city’, for having tested it on Elasticsearch 6.2.1, a document with « Boston City » will match, which is not the aim.

**Comment by fbaligand** [comment]
@jimczi 
What do you think about this doc fix ?

**Comment by jimczi** [comment]
Sorry for the late reply @fbaligand . `city` is not a field name in this example, it is just to show how the synonyms are merged with normal terms, in this case the default operator is `OR` so it is expected that documents that contain only city are returned. IMO the only problem here is the number of parenthesis ;).

**Comment by fbaligand** [comment]
Hi @jimczi 

Thanks for your answer.
OK, I understand the idea of synonyms with "ny city"  and "new york city".
So that this example query can't return results like "salt lake city" or event "city" alone, what do you think about this fix : 
`(ny OR (new AND york)) AND city`

**Comment by jimczi** [comment]
Sorry but I think that this example is fine, the important block of this example is that `new` and `york` must match together since it's a multi word synonyms even if the default operator is `OR` so I'd prefer to keep it as is to emphasize this relation.

**Comment by fbaligand** [comment]
Hi @jimczi 

OK, no problem.

So I finally only removed last parenthesis.
Is it OK for you ?

**Comment by jimczi** [comment]
Sorry for the late response, I merged your pr in master. Thanks @fbaligand !

**Comment by fbaligand** [comment]
Thanks @jimczi for the merge !

**Pull request merged**
