### PR TITLE
Include hidden indices in DeprecationInfoAction

### LINKED ISSUE #118020: GET _migration/deprecations doesn't show deprecations for hidden indices
### Elasticsearch Version

8.18

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Linux

### Problem Description

The `GET _migration/deprecations` API in 8.18 no longer lists deprecations for hidden indices like `.ml-*` by default:
- if you run `GET _migration/deprecations` the deprecation warnings are not displayed
- if you run GET `.ml*/_migration/deprecations` they are displayed

This is a change from the previous behavior in 7.17, where `GET _migration/deprecations` would list the deprecation for `.ml*` indices in the `index_settings` part and the deprecation for ML model snapshots in the `ml_settings` part.

This change in the API behavior breaks the expected workflow in Kibana Update Assistant in 8.18 since now no ES deprecation warnings for `.ml-*` indices are shown before the major upgrade.

### Steps to Reproduce

1. Set up a cluster in 7.17
2. Create an anomaly detection job, e.g. using kibana flights data
3. Upgrade the cluster to 8.18
4. Run `GET _migration/deprecations` in Dev Console

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by dakrone**
This fixes an issue where the deprecation API wouldn't include hidden indices by default.

Resolves #118020

### CODE REVIEW

**Comment by dakrone** [comment]
@elasticmachine update branch

**Comment by dakrone** [comment]
I haven't been able to find out a good way to test this. In integration tests ES does everything it can not to allow a user to create an index with an explicit `index.created.version`. So I've manually tested that this fixes the issue, but I haven't figured out any way to write an integration test for it.

**Comment by valeriy42** [comment]
@dakrone , is there a way to move forward with this PR? It would help us to test the upgrade workflow end-to-end.

**Review by mattc58 — APPROVED** [review]
+1 LGTM

**Comment by dakrone** [comment]
@elasticmachine update branch

**Pull request merged**
