### PR TITLE
Avoid copying aliases if they already contain target index

### PR DESCRIPTION
**Pull request by idegtiarenko**
We noticed this in the hot thread output:
```
       java.base@22.0.1/java.util.HashSet.<init>(HashSet.java:121)
       app/org.elasticsearch.server@8.15.1/org.elasticsearch.cluster.metadata.Metadata$Builder.putAlias(Metadata.java:2017)
       app/org.elasticsearch.server@8.15.1/org.elasticsearch.cluster.metadata.Metadata$Builder.updateAliases(Metadata.java:1989)
       app/org.elasticsearch.server@8.15.1/org.elasticsearch.cluster.metadata.Metadata$Builder.put(Metadata.java:1889)
       app/org.elasticsearch.server@8.15.1/org.elasticsearch.cluster.metadata.Metadata$Builder.indices(Metadata.java:1981)
       app/org.elasticsearch.server@8.15.1/org.elasticsearch.cluster.metadata.Metadata$MetadataDiff.apply(Metadata.java:1694)
       app/org.elasticsearch.server@8.15.1/org.elasticsearch.cluster.metadata.Metadata$MetadataDiff.apply(Metadata.java:1560)
       app/org.elasticsearch.server@8.15.1/org.elasticsearch.cluster.ClusterState$ClusterStateDiff.apply(ClusterState.java:1217)
       app/org.elasticsearch.server@8.15.1/org.elasticsearch.cluster.ClusterState$ClusterStateDiff.apply(ClusterState.java:1096)
       app/org.elasticsearch.server@8.15.1/org.elasticsearch.cluster.coordination.PublicationTransportHandler.deserializeAndApplyDiff(PublicationTransportHandler.java:205)
```

This change prevents set copy if index is already present in it.

### CODE REVIEW

**Review by original-brownbear — COMMENTED** [review]
Change in isolation seems fine to me but I wonder, why do we have to add this check to the application of a diff? Why is a diff leading to a noop put here, that seems like a bug doesn't it?

**Comment by ywangd** [comment]
Relates #110217. These pieces of code has quite some inefficiency at creating HashSet. This PR removes some of them when the index already presents. It still goes through the HashSet -> unmodifiableSet -> HashSet dance for all unique indices. Something we can improve in separate PRs.

**Comment by idegtiarenko** [comment]
>Change in isolation seems fine to me but I wonder, why do we have to add this check to the application of a diff? Why is a diff leading to a noop put here, that seems like a bug doesn't it?

I would like to remove the unnecessary copy here. I am looking into the diff separately.

**Comment by idegtiarenko** [comment]
Closing in favor of https://github.com/elastic/elasticsearch/pull/115934

**Pull request closed without merging**
