### PR TITLE
Add documentation to deprecate the global retention privileges.

### PR DESCRIPTION
**Pull request by gmarouli**
With https://github.com/elastic/elasticsearch/pull/111972 we changed the approach on how to configure global retention settings meaning that the `monitor_data_stream_global_retention` and `manage_data_stream_global_retention` privileges are not needs.

These two privileges effective were a no-op since they were introduced, so we mark them as deprecated but there is no alternative offered.

Reference that the privileges are already a noop: https://github.com/elastic/elasticsearch/blob/9185056efe15eb1d06a3de04548cf40c904c2f50/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/security/authz/privilege/ClusterPrivilegeResolver.java#L400-L407

### CODE REVIEW

**Comment by gmarouli** [comment]
@elasticmachine update branch

**Review by slobodanadamovic — APPROVED** [review]
LGTM

**Comment by gmarouli** [comment]
@elasticmachine update branch

**Comment by gmarouli** [comment]
@elasticmachine update branch

**Comment by gmarouli** [comment]
Docs pipeline was also successful: https://buildkite.com/elastic/docs-build-pr/builds/131649

**Pull request merged**
