### PR TITLE
[ML] ensure roberta tokenization options are updateable

### PR DESCRIPTION
**Pull request by benwtrent**
This ensures roberta tokenization options are updateable. The previous reberta code missed a case.

Additionally, this commit improves testing robustness to avoid such a mistake again.

### CODE REVIEW

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Comment by benwtrent** [comment]
run elasticsearch-ci/part-2

**Review by davidkyle — APPROVED** [review]
LGTM

**Pull request merged**
