### PR TITLE
Search with failing nodes test

### PR DESCRIPTION
**Pull request by henningandersen**
Add a test case that verifies that searches running while nodes are
failing behave correctly, in particular with
allow_partial_search_results=false.

Fixed MockSearchService concurrency, assertNoInFlightContext could
have false negative result (rarely).

Split out from #45739

### CODE REVIEW

**Comment by henningandersen** [comment]
ci/1 failed due to new issue, reported and fixed here #46064
@elasticmachine run elasticsearch-ci/1

**Comment by henningandersen** [comment]
@elasticmachine update branch

**Comment by henningandersen** [comment]
@elasticmachine update branch

**Comment by jimczi** [comment]
Is it still relevant @henningandersen ?

**Comment by henningandersen** [comment]
@elasticmachine update branch

**Pull request closed without merging**
