### PR TITLE
 Fix binary doc values fetching in _search

### LINKED ISSUE #29565: Doc value get indexed into the wrong document
This issue was reported at https://discuss.elastic.co/t/issue-storing-binary-fields-in-6-2-2/128290 against 6.2 but it also reproduces against master.

Here is a recreation. All documents report the same value in their doc-value field: the value of the last document in the bulk request.

```
PUT blob_test
{
  "settings": {
    "number_of_shards": 1,
    "number_of_replicas": 0
  }, 
  "mappings": {
    "_doc": {
      "properties": {
        "blob": {
          "type": "binary",
          "doc_values": true
        }
      }
    }
  }
}

POST blob_test/_doc/_bulk
{ "index": { "_id": "id_0" } }
{ "blob": "aWRfMCBhbmQgc29tZSB0ZXh0" }
{ "index": { "_id": "id_1" } }
{ "blob": "aWRfMSBhbmQgc29tZSB0ZXh0" }
{ "index": { "_id": "id_2" } }
{ "blob": "aWRfMiBhbmQgc29tZSB0ZXh0" }
{ "index": { "_id": "id_3" } }
{ "blob": "aWRfMyBhbmQgc29tZSB0ZXh0" }
{ "index": { "_id": "id_4" } }
{ "blob": "aWRfNCBhbmQgc29tZSB0ZXh0" }
{ "index": { "_id": "id_5" } }
{ "blob": "aWRfNSBhbmQgc29tZSB0ZXh0" }
{ "index": { "_id": "id_6" } }
{ "blob": "aWRfNiBhbmQgc29tZSB0ZXh0" }
{ "index": { "_id": "id_7" } }
{ "blob": "aWRfNyBhbmQgc29tZSB0ZXh0" }
{ "index": { "_id": "id_8" } }
{ "blob": "aWRfOCBhbmQgc29tZSB0ZXh0" }
{ "index": { "_id": "id_9" } }
{ "blob": "aWRfOSBhbmQgc29tZSB0ZXh0" }


GET blob_test/_search 
{
  "docvalue_fields": ["blob"]
}
```

### PR DESCRIPTION
**Pull request by jimczi**
Binary doc values are retrieved during the DocValueFetchSubPhase through an instance of ScriptDocValues.
 Since 6.0 ScriptDocValues instances are not allowed to reuse the object that they return
 (https://github.com/elastic/elasticsearch/issues/26775) but BinaryScriptDocValues doesn't follow this
 restriction and reuses instances of BytesRefBuilder among different documents.
 This results in `field` values assigned to the wrong document in the response.
 This commit fixes this issue by recreating the BytesRef for each value that needs to be returned.

 Fixes #29565

### CODE REVIEW

**Review by rjernst — APPROVED** [review]
LGTM

**Review by jpountz — COMMENTED** [review]
This approach is going to require additional BytesRef copies for strings. Maybe instead replace the `get` calls in `ScriptDocValues.BytesRefs` with a `toBytesRef`?

**Comment by jimczi** [comment]
Thanks @rjernst @jpountz 
I pushed a commit that removes the additional copy for strings.

**Review by jpountz — APPROVED** [review]

**Comment by s1monw** [comment]
you already merged it which is fine, I just started looking into it and I wonder if we should instead of having a `BytesRefBuilder` that we copy into from `SortedBinaryDocValues` and then copy again when it's consumed. Wouldn't it be simpler to hold on `BytesRef` directly that we `deepCopy` from the incoming values which we do anyway somehow? This would safe on time of copying? @jimczi @jpountz WDYT

**Comment by jpountz** [comment]
This is what the PR did initially but I asked Jim to change it because it added one more object allocation for strings. I suspect that object allocations may be easier to skip thanks to escape analysis this way as well, since we don't put the copies in a long-living array. In the end, I don't feel strongly about it, if you think it's better to change back to performing a deep copy of the BytesRef, I'm good with it.

**Comment by s1monw** [comment]
I wonder if we still need to have a shared version and instead can hold a `String[]` that way we can skip all copies to BytesRef for strings and convert to string on `nextDoc`?

**Comment by jimczi** [comment]
This would save one copy for the `keyword` case and would not affect `binary` .
+1 I can open a new pr for this.

**Comment by s1monw** [comment]
> +1 I can open a new pr for this.

++

**Pull request merged**
