### PR TITLE
REST: Deprecate Settings in BaseRestHandler

### PR DESCRIPTION
**Pull request by nik9000**
`Settings` isn't required by `BaseRestHandler` any more but subclass is
passing it in. This deprecates passing it to the ctor and removes
passing it from all subclasses.

### CODE REVIEW

**Review by jaymode — APPROVED** [review]
LGTM!

**Comment by nik9000** [comment]
@elasticmachine rerun elasticsearch-ci/1

**Comment by nik9000** [comment]
@elasticmachine rerun elasticsearch-ci/1

**Comment by nik9000** [comment]
The failure doesn't occur for me locally.

@elasticmachine, rerun elasticsearch-ci/1

**Comment by nik9000** [comment]
I was never able to get this one to merge cleanly what with concentrating on other projects and there being so much activity other places. I'll close this.

**Pull request closed without merging**
