### PR TITLE
Remove unsafe options

### PR DESCRIPTION
**Pull request by kimchy**
For quite some time now, our networking layer makes sure to create safe messages as in not using the shared buffers. This is great, and we should remove the old support for "unsafe" notion in our codebase.

Note, this will break java code that provided the unsafe flag, it needs to be removed.

### CODE REVIEW

**Comment by bleskes** [comment]
LGTM

**Comment by jpountz** [comment]
LGTM

**Comment by s1monw** [comment]
this made my day +1

**Comment by s1monw** [comment]
btw. not sure if we need to do this on `1.6` unless it's simple?

**Comment by kimchy** [comment]
@s1monw looking at it now for 1.6, so far looks like almost a clean merge, will update

**Pull request closed without merging**
