### PR TITLE
[Transform] Fix failure when resolving indices from CCS 

### LINKED ISSUE #91550: [Transform] Transform can fail resolving indices from CCS clusters
**Affected version:** 8.2-
**Fixed in:** 

### Problem Description

The problem applies to transforms that use more than 1 CCS cluster or 1 local and 1 CCS as source. A typical source could look like this (the important part: `remotes*`):

```
        "index" : [
          "remotes*:filebeat*"
        ],

```

If 2 indices share the same name the transform might fail with an error similar to this:

```
 Failed to retrieve checkpoint due to: Duplicate key logs-2022-11-14 (attempted merging values [... and ...]
```

Similar to the above the `_stats` call is broken for such a transform, it can fail with an error message starting with:

```
Failure during checkpoint retrieval
```

This can happen even if the transform is in state `STOPPED` or `FAILED`.

### Mitigation

Choose _one_ of the following mitigations:

 - split your transforms to use max 1 CCS/local indices

_or_

 - avoid upgrading to 8.2, until the issue got resolved (this is a regression of #80984)

_or_

 - avoid duplicate names for your indices even on remote cluster, e.g. name the index: `remote1-filebeat...`, `remote2-filebeat...`

### Solution

This is a regression of #80984 which introduced a new way of check-pointing. The remote needs to be prefixed to the index name.

### PR DESCRIPTION
**Pull request by hendrikmuhs**
properly prefix remote indices in checkpoints, fixes a failure when more than 1 cluster is used and index names clash

relates #80984
fixes #91550

### CODE REVIEW

**Comment by hendrikmuhs** [comment]
@elasticmachine update branch please

**Review by droberts195 — COMMENTED** [review]
Am I right that every new test is checking the case of the same index name on both local and remote clusters?

I think it would be nice if one of them tested the case of the same index name on multiple remote clusters but no duplicate on the local cluster. Maybe a unit test for this would be the easiest.

**Comment by hendrikmuhs** [comment]
I added a unit test for 3 remotes with same name indices

**Review by droberts195 — APPROVED** [review]
LGTM

**Review by przemekwitek — COMMENTED** [review]
LGTM

**Pull request merged**
