### PR TITLE
[8.x] Move AbstractBWCSerializationTestCase To General Test Framework (#113907)

### PR DESCRIPTION
**Pull request by Mikep86**
# Backport

This will backport the following commits from `main` to `8.x`:
 - [Move AbstractBWCSerializationTestCase To General Test Framework (#113907)](https://github.com/elastic/elasticsearch/pull/113907)

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

### CODE REVIEW

**Review by kderusso — COMMENTED** [review]
🚢

**Review by kderusso — APPROVED** [review]

**Comment by Mikep86** [comment]
@elasticmachine merge upstream

**Comment by Mikep86** [comment]
@elasticmachine merge upstream

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Comment by Mikep86** [comment]
@elasticmachine update branch

**Pull request merged**
