### PR TITLE
Change filter aggregation to execute like filters aggregation

### LINKED ISSUE #90076: `filter` aggregation should run as `filters`
### Elasticsearch Version

main

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

all

### Problem Description

The `filter` agg should run as `filters` because the `filters` agg has tons of optimizations, some of them are even around when running with a single filter. At a minimum we should optimize the `filter` agg in the same way as `filters`, but I think it's easier if we just run it as `filters`.

### Steps to Reproduce

see above

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by martijnvg**
This change attempts to do this by changing the `FilterAggregationBuilder` to use the `FiltersAggregatorFactory` instead of the `FilterAggregatorFactory`. The wrapped by another `AggregatorFactory` instance that uses an `AdaptingAggregator` aggregator translate the results back to `InternalFilter`, so that end result stays the same, but can `filter` aggregation can make use of the optimizations that `filters` provides.

The change also removes the: `FilterAggregatorFactory`, `FilterAggregator` and `FilterAggregatorTests` classes.

Closes #90076

### CODE REVIEW

**Review by nik9000 — APPROVED** [review]
LGTM. It'd be nice to have a quick performance before and after that shows us doing the `filter-by-filter` execution mechanism here. I'm not sure it's worth a lot of work though.

**Comment by martijnvg** [comment]
I worked on adding `filters` and `filter` aggregations to noaa benchmark track ().

Benchmarking the following request and then comparing the results with and without this change:

```
{
    "name": "filter-agg-with-high-cardinality-filter",
    "operation-type": "search",
    "body": {
        "size": 0,
        "aggs": {
            "filter-term-high-cardinality": {
            "filter": {"match": {"station.country_code": "US"}}
            }
        }
    }
}
```

Yielded the following result:

```
                         Min Throughput |   filter-agg-with-high-cardinality-filter |      1.37528     |    352.896       |  351.521   |  ops/s | +25559.99% |
|                                               Mean Throughput |   filter-agg-with-high-cardinality-filter |      1.41648     |    352.896       |  351.48    |  ops/s | +24813.63% |
|                                             Median Throughput |   filter-agg-with-high-cardinality-filter |      1.39956     |    352.896       |  351.497   |  ops/s | +25114.89% |
|                                                Max Throughput |   filter-agg-with-high-cardinality-filter |      1.55431     |    352.896       |  351.342   |  ops/s | +22604.32% |
|                                       50th percentile latency |   filter-agg-with-high-cardinality-filter |    744.625       |      2.0186      | -742.606   |     ms |    -99.73% |
|                                       90th percentile latency |   filter-agg-with-high-cardinality-filter |    749.819       |      2.94691     | -746.872   |     ms |    -99.61% |
|                                      100th percentile latency |   filter-agg-with-high-cardinality-filter |    757.729       |      3.56059     | -754.168   |     ms |    -99.53% |
|                                  50th percentile service time |   filter-agg-with-high-cardinality-filter |    744.625       |      2.0186      | -742.606   |     ms |    -99.73% |
|                                  90th percentile service time |   filter-agg-with-high-cardinality-filter |    749.819       |      2.94691     | -746.872   |     ms |    -99.61% |
|                                 100th percentile service time |   filter-agg-with-high-cardinality-filter |    757.729       |      3.56059     | -754.168   |     ms |    -99.53% |
|                                                    error rate |   filter-agg-with-high-cardinality-filter |      0           |      0           |    0       |      % |      0.00% |
```

and benchmarking this request:

```
{
    "name": "filter-per-10-degrees-interval",
    "operation-type": "search",
    "body": {
        "size": 0,
        "aggs": {
            "group-by-temp": {
                "histogram": {
                    "field": "TAVG",
                    "interval": 10,
                    "min_doc_count": 1
                },
                "aggs": {
                    "in-the-us": {
                        "filter": {
                            "match": {"station.country_code": "US"}
                        }
                    }
                }
            }
        }
    }
}
```

Yielded the following result:

```
Min Throughput |            filter-per-10-degrees-interval |      0.877257    |      0.996935    |    0.11968 |  ops/s |    +13.64% |
|                                               Mean Throughput |            filter-per-10-degrees-interval |      0.877661    |      1.01131     |    0.13365 |  ops/s |    +15.23% |
|                                             Median Throughput |            filter-per-10-degrees-interval |      0.877632    |      1.01332     |    0.13569 |  ops/s |    +15.46% |
|                                                Max Throughput |            filter-per-10-degrees-interval |      0.878086    |      1.01537     |    0.13728 |  ops/s |    +15.63% |
|                                       50th percentile latency |            filter-per-10-degrees-interval |   1137.99        |    977.609       | -160.379   |     ms |    -14.09% |
|                                       90th percentile latency |            filter-per-10-degrees-interval |   1143.41        |    986.521       | -156.889   |     ms |    -13.72% |
|                                      100th percentile latency |            filter-per-10-degrees-interval |   1150.73        |   1020           | -130.734   |     ms |    -11.36% |
|                                  50th percentile service time |            filter-per-10-degrees-interval |   1137.99        |    977.609       | -160.379   |     ms |    -14.09% |
|                                  90th percentile service time |            filter-per-10-degrees-interval |   1143.41        |    986.521       | -156.889   |     ms |    -13.72% |
|                                 100th percentile service time |            filter-per-10-degrees-interval |   1150.73        |   1020           | -130.734   |     ms |    -11.36% |
|                                                    error rate |            filter-per-10-degrees-interval |      0           |      0           |    0       |      % |      0.00% |
```

In case the filter agg is nested then the speedup by using `filters` agg implementation is bit smaller, but still significant. If the `filter` is top level then the speedup is significant.

**Comment by nik9000** [comment]
I reformatted your rally results manually so they'd fit on the page.

> |  50th percentile service time |  744.625   |   2.0186  | -742.606 |     ms |    -99.73% |
> |  90th percentile service time |  749.819   |   2.94691 | -746.872 |     ms |    -99.61% |
> | 100th percentile service time |  757.729   |   3.56059 | -754.168 |     ms |    -99.53% |

Nice.

**Comment by martijnvg** [comment]
@elasticsearchmachine update branch

**Comment by martijnvg** [comment]
@elasticmachine update branch

**Pull request merged**
