### PR TITLE
Make API key actions local-only

### PR DESCRIPTION
**Pull request by n1v0lg**
Refactoring PR to make create, grant, and update API key actions local-only. Also ports a profiles action since it relies on the same base class as grant API key.

### CODE REVIEW

**Comment by n1v0lg** [comment]
@elasticmachine update branch

**Review by slobodanadamovic — APPROVED** [review]
LGTM 👍

**Comment by n1v0lg** [comment]
@elasticmachine update branch

**Comment by n1v0lg** [comment]
@elasticmachine update branch

**Pull request merged**
