### PR TITLE
ESQL: Move all remaining Expression serialization

### PR DESCRIPTION
**Pull request by nik9000**
To line it up with the rest of Elasticsearch.

### CODE REVIEW

**Comment by nik9000** [comment]
This is the last of the `Expression`s. We can remove `writeExpression` and `readExpression` after this. Those should just be `writeNamedWriteable` and `readNamedWriteable`. That's honestly most of `PlanNamedTypes`.

**Comment by nik9000** [comment]
run elasticsearch-ci/part-3

**Review by luigidellaquila — APPROVED** [review]
LGTM, thanks!

**Comment by nik9000** [comment]
Thanks @luigidellaquila !

**Pull request merged**
