### PR TITLE
Safely Close Repositories on Node Shutdown

### LINKED ISSUE #47689: CI Failures for SLMSnapshotBlockingIntegTests testSnapshotInProgress
Reproduce with:
```
REPRODUCE WITH: ./gradlew ':x-pack:plugin:ilm:test' --tests "org.elasticsearch.xpack.slm.SLMSnapshotBlockingIntegTests.testSnapshotInProgress" \
  -Dtests.seed=65DEEE302AEB2E47 \
  -Dtests.security.manager=true \
  -Dtests.locale=hsb-DE \
  -Dtests.timezone=America/Indiana/Petersburg \
  -Dcompiler.java=12 \
  -Druntime.java=12

REPRODUCE WITH: ./gradlew ':x-pack:plugin:ilm:test' --tests "org.elasticsearch.xpack.slm.SLMSnapshotBlockingIntegTests.testSnapshotInProgress" \
  -Dtests.seed=65DEEE302AEB2E47 \
  -Dtests.security.manager=true \
  -Dtests.locale=hsb-DE \
  -Dtests.timezone=America/Indiana/Petersburg \
  -Dcompiler.java=12 \
  -Druntime.java=12
```

from (https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=openjdk12,nodes=general-purpose/251/console)

https://gradle-enterprise.elastic.co/s/cc7dkdd6bvbfs

### PR DESCRIPTION
**Pull request by original-brownbear**
We were not closing repositories on Node shutdown.
In production, this has little effect but in tests
shutting down a node using `MockRepository` and is
currently stuck in a simulated blocked-IO situation
will only unblock when the node's threadpool is
interrupted. This might in some edge cases (many
snapshot threads and some CI slowness) result
in the execution taking longer than 5s to release
all the shard stores and thus we fail the assertion
about unreleased shard stores in the internal test cluster.

Also, this seems to speed up `DedicatedClusterSnapshotRestoreIT`
by `~30s` which closes blocked nodes a in a few spots which.

Fixes #47689

### CODE REVIEW

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/2

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/packaging-sample

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/packaging-sample

**Review by tlrx — APPROVED** [review]

**Comment by original-brownbear** [comment]
Thanks Tanguy!

**Pull request merged**
