### PR TITLE
Add messages for CCR on license state changes

### PR DESCRIPTION
**Pull request by jasontedor**
When a license expires, or license state changes, functionality might be disabled. This commit adds messages for CCR to inform users that CCR functionality will be disabled when a license expires, or when license state changes to a license level lower than trial/platinum/enterprise.

### CODE REVIEW

**Comment by jasontedor** [comment]
@elasticmachine update branch

**Review by martijnvg — APPROVED** [review]
LGTM

Maybe also add a test to `XPackLicenseStateTests` with a `assertAckMessages(...)` to test the messages in case of a license change?

**Review by ywelsch — APPROVED** [review]
LGTM. +1 to what Martijn said

**Comment by jasontedor** [comment]
@elasticmachine update branch

**Pull request merged**
