### PR TITLE
Fix NPE when building exception messages

### LINKED ISSUE #59103: Mismatched value_type on a scripted aggregation can NPE when building exception
If a `date_histo` is specified with a script, no field, and a "mismatched" `value_type` you can hit an NPE when trying to generate an exception text.  This happens because we try to lookup the field context to make a useful exception text... but there is no field here thus NPE.  :)

Edit: I think this probably applies to any agg that accepts a script, I just stumbled into it while investigating a date_histo thing

Reproduction:

```
PUT test/
{
  "mappings": {
    "properties": {
      "timestamp": {
        "type": "date"
      }
    }
  }
}

GET test/_search
{
  "aggs": {
    "the_histo": {
      "date_histogram": {
        "script": {
          "source": "return 123",
          "lang": "painless"
        },
        "value_type": "string",
        "interval": "1d"
      }
    }
  }
}
```

Caused by: https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/search/aggregations/support/ValuesSourceRegistry.java#L135

Perhaps more interesting, if you do supply a field we find the field context and then throw a confusing exception:

`"Field [timestamp] of type [date] is not supported for aggregation [date_histogram]"`

I think we need to include `value_type` in the exception message somewhere, so that it's clear that was part of the reason we couldn't find an aggregator.

### PR DESCRIPTION
**Pull request by not-napoleon**
resolves #59103 

This pushes generating the description string for the values source into the values source config, and does better handling of the various cases of where the config got the values from.

### CODE REVIEW

**Review by nik9000 — APPROVED** [review]
Change LGTM though this probably deserves a unit test around the particular issue where it came up.

**Comment by not-napoleon** [comment]
Yeah, I can whip up a unit test for that.

**Comment by not-napoleon** [comment]
@elasticmachine update branch

**Comment by not-napoleon** [comment]
@elasticmachine run elasticsearch-ci/1

**Pull request merged**
