### PR TITLE
Support GKE Workload Identity for Searchable Snapshots

### LINKED ISSUE #82702: SearchableSnapshot: GKE Workload Identity and GCS repository plugin
It's possible to use GKE Workload Identity to automatically setup the credentials for the GCS repository plugin _(instead of creating a JSON service account file)_.
It works fine as long as snapshots are created or restored "manually" (through the `_snapshot/` API).
It is however no more the case when the bucket must be read from the `SearchableSnapshot` code, for example in the context of a `frozen` or cold `tier`. In this case it fails with the following error:

```json
{
	"type": "server",
	"timestamp": "2022-01-17T16:09:49,963Z",
	"level": "WARN",
	"component": "o.e.r.g.GoogleCloudStorageService",
	"cluster.name": "elasticsearch-sample",
	"node.name": "elasticsearch-sample-es-cold-1",
	"message": "failed to load default project id",
	"cluster.uuid": "lKo5VXDGRGeIg6aQAIEZ5g",
	"node.id": "lC0hhssQRfW9fdow0zYZJg",
	"stacktrace": ["java.security.AccessControlException: access denied (\"java.lang.RuntimePermission\" \"accessDeclaredMembers\")",
		"at java.security.AccessControlContext.checkPermission(AccessControlContext.java:485) ~[?:?]",
		"...",
		"at org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobContainer.readBlob(GoogleCloudStorageBlobContainer.java:63) [repository-gcs-7.16.1.jar:7.16.1]",
		"at org.elasticsearch.common.blobstore.support.FilterBlobContainer.readBlob(FilterBlobContainer.java:48) [elasticsearch-7.16.1.jar:7.16.1]",
		"at org.elasticsearch.xpack.searchablesnapshots.store.SearchableSnapshotDirectory$RateLimitingBlobContainer.readBlob(SearchableSnapshotDirectory.java:763) [searchable-snapshots-7.16.1.jar:7.16.1]"
	]
}
```

See the following ECK issue for more context: https://github.com/elastic/cloud-on-k8s/issues/5230

I would be happy to help/contribute but I'm not familiar with how the security manager is used in this part of the code.

Thanks

### PR DESCRIPTION
**Pull request by arteam**
Searchable snapshots perform naked calls of `GoogleCloudStorageBlobContainer#readBlob` without the Security Manager. The
client fails to get Compute Engine credentials because of that. It does work for for normal snapshot/restore we
do a privileged call of `GoogleCloudStorageBlobStore.writeBlob` during the verification of the repository.

The simplest fix is just to make sure that both `ServiceOptions.getDefaultProjectId` and `GoogleCredentials::getApplicationDefault` get called under the Security Manager (which they should because they perform network calls).

Unfortunately, we can't write an integration test for the issue, because the test framework does the repo verification
automatically which kind works around the bug. Writing a unit test also seems not possible, because
`ComputeEngineCredentials#getMetadataServerUrl` relies on the `GCE_METADATA_HOST` environment variable.

See https://github.com/elastic/cloud-on-k8s/issues/5230

Resolves #82702

### CODE REVIEW

**Comment by tlrx** [comment]
> Unfortunately, we can't write an integration test for the issue, because the test framework does the repo verification
> automatically which kind works around the bug. Writing a unit test also seems not possible, because
> `ComputeEngineCredentials#getMetadataServerUrl` relies on the `GCE_METADATA_HOST` environment variable.

I wonder if we can workaround this and add a QA test for searchable snapshots that would reuse the AbstractSearchableSnapshotsRestTestCase (without verifyng the repository) and the fixture used in `discovery-gce` ?

I think it is worth to have such a test so that we don't reintroduce such bugs in the future. Note that this can be done in a follow up PR. What do you think?

**Comment by arteam** [comment]
> I wonder if we can workaround this and add a QA test for searchable snapshots that would reuse the AbstractSearchableSnapshotsRestTestCase (without verifyng the repository) and the fixture used in discovery-gce ?
I think it is worth to have such a test so that we don't reintroduce such bugs in the future. Note that this can be done in a follow up PR. What do you think?

I think it's a good idea! Unfortunately, I've been unsuccessful in trying to come up with a test reproducing the failure. Even i I disable the repository verification, the client still gets called correctly under the SecurityManager via

```
org.elasticsearch.repositories.gcs.SocketAccess.doPrivilegedVoidIOException(SocketAccess.java:42)
org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobStore.listBlobsByPrefix(GoogleCloudStorageBlobStore.java:156)
org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobContainer.listBlobsByPrefix(GoogleCloudStorageBlobContainer.java:58)
org.elasticsearch.repositories.blobstore.BlobStoreRepository.listBlobsToGetLatestIndexId(BlobStoreRepository.java:2591)
org.elasticsearch.repositories.blobstore.BlobStoreRepository.latestIndexBlobId(BlobStoreRepository.java:2563)
org.elasticsearch.repositories.blobstore.BlobStoreRepository.doGetRepositoryData(BlobStoreRepository.java:1885)
```

We probably need some ILM based test for recovery if want to reproduce the issue to trigger the following failing path
```
"at org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobContainer.readBlob(GoogleCloudStorageBlobContainer.java:63) [repository-gcs-7.16.1.jar:7.16.1]",
"at org.elasticsearch.common.blobstore.support.FilterBlobContainer.readBlob(FilterBlobContainer.java:48) [elasticsearch-7.16.1.jar:7.16.1]",
"at org.elasticsearch.xpack.searchablesnapshots.store.SearchableSnapshotDirectory$RateLimitingBlobContainer.readBlob(SearchableSnapshotDirectory.java:763) [searchable-snapshots-7.16.1.jar:7.16.1]",
"at org.elasticsearch.repositories.blobstore.ChecksumBlobStoreFormat.read(ChecksumBlobStoreFormat.java:88) [elasticsearch-7.16.1.jar:7.16.1]",
"at org.elasticsearch.repositories.blobstore.BlobStoreRepository.loadShardSnapshot(BlobStoreRepository.java:3367) [elasticsearch-7.16.1.jar:7.16.1]",
"at org.elasticsearch.xpack.searchablesnapshots.store.SearchableSnapshotDirectory.lambda$create$15(SearchableSnapshotDirectory.java:667) [searchable-snapshots-7.16.1.jar:7.16.1]",
"at org.elasticsearch.common.util.LazyInitializable.maybeCompute(LazyInitializable.java:92) [elasticsearch-7.16.1.jar:7.16.1]",
"at org.elasticsearch.common.util.LazyInitializable.getOrCompute(LazyInitializable.java:70) [elasticsearch-7.16.1.jar:7.16.1]",
"at org.elasticsearch.xpack.searchablesnapshots.store.SearchableSnapshotDirectory.loadSnapshot(SearchableSnapshotDirectory.java:228) [searchable-snapshots-7.16.1.jar:7.16.1]",
"at org.elasticsearch.xpack.searchablesnapshots.allocation.SearchableSnapshotIndexEventListener.ensureSnapshotIsLoaded(SearchableSnapshotIndexEventListener.java:75) [searchable-snapshots-7.16.1.jar:7.16.1]",
"at org.elasticsearch.xpack.searchablesnapshots.allocation.SearchableSnapshotIndexEventListener.beforeIndexShardRecovery(SearchableSnapshotIndexEventListener.java:67) [searchable-snapshots-7.16.1.jar:7.16.1]",
"at org.elasticsearch.index.CompositeIndexEventListener.beforeIndexShardRecovery(CompositeIndexEventListener.java:276) [elasticsearch-7.16.1.jar:7.16.1]",
"at org.elasticsearch.index.shard.IndexShard.preRecovery(IndexShard.java:1733) [elasticsearch-7.16.1.jar:7.16.1]",
"at org.elasticsearch.index.shard.StoreRecovery.restore(StoreRecovery.java:505) [elasticsearch-7.16.1.jar:7.16.1]",
"at org.elasticsearch.index.shard.StoreRecovery.recoverFromRepository(StoreRecovery.java:301) [elasticsearch-7.16.1.jar:7.16.1]",
"at org.elasticsearch.index.shard.IndexShard.restoreFromRepository(IndexShard.java:2358) [elasticsearch-7.16.1.jar:7.16.1]",
"at org.elasticsearch.index.shard.IndexShard.lambda$startRecovery$17(IndexShard.java:3160) [elasticsearch-7.16.1.jar:7.16.1]",
```

**Review by tlrx — APPROVED** [review]
LGTM, we can merge the fix and work on a more specialized test in a follow up

**Comment by arteam** [comment]
Thanks, Tanguy!

**Pull request merged**
