### PR TITLE
[ML][Data Frame] prevent task from attempting to run when failed

### LINKED ISSUE #44121: [ML] Failed data frame transform is restarted when the node restarts
Spotted in 7.2.0

A data frame transform that enters the `failed` state is supposed to stay in that state until it is force-closed.

Currently, this rule is not respected if you restart the node. The task turns into `started` when the node restarts.

**Steps to reproduce**
1. In a single-node cluster, create a data frame transform
2. Cause a failure in the data frame state: starting the transform then deleting the source data index should do it
3. Restart the node
4. Notice that the data frame that was in the `failed` state has changed to `started` after restarting.

### PR DESCRIPTION
**Pull request by benwtrent**
Similar to how we handle the failed state for anomaly detector jobs, we should not allow the task to execute if it is failed. The failure could have been unrecoverable, or due to cluster load but we have no accurate way to determine this. Consequently, the failed task should not start if it gets assigned to a different node. 

closes #44121

### CODE REVIEW

**Review by hendrikmuhs — APPROVED** [review]
LGTM

**Comment by davidkyle** [comment]
run elasticsearch-ci/bwc

**Comment by davidkyle** [comment]
run elasticsearch-ci/default-distro

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Comment by benwtrent** [comment]
run elasticsearch-ci/2

**Pull request merged**
