### PR TITLE
Add NoOps to Lucene for failed delete operations

### PR DESCRIPTION
**Pull request by dnhatn**
Today we add a NoOp to Lucene and translog if we fail to process an
indexing operation. However, we are only adding NoOps to translog for
delete operations. In order to have a complete history in Lucene, we
should add NoOps of failed delete operations to both Lucene and translog.

Relates #29530

### CODE REVIEW

**Comment by dnhatn** [comment]
CI: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+ccr+feature-branch-periodic/1153/consoleText

**Comment by dnhatn** [comment]
@elasticmachine test this please.

**Comment by s1monw** [comment]
technically I agree with this. But what is the scenario where a delete op fails? I don't necessarily understand how this can happen. Can you explain this a bit?

**Comment by dnhatn** [comment]
@s1monw To be honest, I am not sure if this ever happens. I made this change because:
- We catch this failure in our current implementation but put NoOps into translog only
- A delete with soft-deletes enabled is an index (update DV, then index a new tombstone document); thus deletes may fail like index operations.

**Comment by s1monw** [comment]
I suggest we make this change for correctness and then open an issue to revisit this altogether. I think it's unnecessary we can't recover from any issue during a delete IMO

**Comment by dnhatn** [comment]
@s1monw I opened https://github.com/elastic/elasticsearch/issues/33256. Can you please give this go? Thank you!

**Review by s1monw — APPROVED** [review]
LGTM given that we have a followup

**Comment by dnhatn** [comment]
Thanks @s1monw.

**Pull request merged**
