### PR TITLE
ES|QL: Fix funciton Telemetry tests

### LINKED ISSUE #115231: [CI] XPackRestIT test {p0=esql/60_usage/Basic ESQL usage output (telemetry)} failing
**Build Scans:**
- [elasticsearch-periodic #4512 / release-tests](https://gradle-enterprise.elastic.co/s/mabk35ghwghuo)
- [elasticsearch-pull-request #37359 / release-tests](https://gradle-enterprise.elastic.co/s/ee5bet2q2oetm)
- [elasticsearch-pull-request #36871 / rest-compatibility](https://gradle-enterprise.elastic.co/s/iwfdn36cb2yxk)
- [elasticsearch-pull-request #36567 / release-tests](https://gradle-enterprise.elastic.co/s/uwmhcazz3e7hu)
- [elasticsearch-pull-request #36557 / release-tests](https://gradle-enterprise.elastic.co/s/fljwqpb5q4ok2)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:yamlRestTest" --tests "org.elasticsearch.xpack.test.rest.XPackRestIT.test {p0=esql/60_usage/Basic ESQL usage output (telemetry)}" -Dtests.seed=596578782D59E394 -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dlicense.key=x-pack/license-tools/src/test/resources/public.key -Dtests.locale=agq-CM -Dtests.timezone=America/Costa_Rica -Druntime.java=22
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('test%20%7Bp0%3Desql%2F60_usage%2FBasic%20ESQL%20usage%20output%20(telemetry)%7D'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.test.rest.XPackRestIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure Message:**
```
java.lang.AssertionError: Failure at [esql/60_usage:86]: field [esql.functions] doesn't have length [117]
Expected: <117>
     but: was <115>
```

**Issue Reasons:**
- [main] 2 consecutive failures in step release-tests
- [main] 5 failures in test test {p0=esql/60_usage/Basic ESQL usage output (telemetry)} (0.5% fail rate in 989 executions)
- [main] 4 failures in step release-tests (15.4% fail rate in 26 executions)
- [main] 4 failures in pipeline elasticsearch-pull-request (1.1% fail rate in 364 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #116448: [CI] XPackRestIT test {p0=esql/60_usage/Basic ESQL usage output (telemetry) non-snapshot version} failing
**Build Scans:**
- [elasticsearch-periodic #4781 / release-tests](https://gradle-enterprise.elastic.co/s/hgdgm4j2nd7s6)
- [elasticsearch-periodic #4776 / release-tests](https://gradle-enterprise.elastic.co/s/3mhxgwuhb4e4m)
- [elasticsearch-periodic #4771 / release-tests](https://gradle-enterprise.elastic.co/s/tcq2vfoihxaz6)
- [elasticsearch-periodic #4766 / release-tests](https://gradle-enterprise.elastic.co/s/emt56kql6xcuq)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:yamlRestTest" --tests "org.elasticsearch.xpack.test.rest.XPackRestIT.test {p0=esql/60_usage/Basic ESQL usage output (telemetry) non-snapshot version}" -Dtests.seed=70300202F4AFCC52 -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dlicense.key=x-pack/license-tools/src/test/resources/public.key -Dtests.locale=es-CR -Dtests.timezone=Asia/Oral -Druntime.java=23
```

**Applicable branches:**
8.x

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.test.rest.XPackRestIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(test%20%7Bp0%3Desql%2F60_usage%2FBasic%20ESQL%20usage%20output%20(telemetry)%20non-snapshot%20version%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Failure at [esql/60_usage:165]: field [esql.functions] doesn't have length [118]
Expected: <118>
     but: was <116>
```

**Issue Reasons:**
- [8.x] 4 consecutive failures in test test {p0=esql/60_usage/Basic ESQL usage output (telemetry) non-snapshot version}
- [8.x] 4 consecutive failures in step release-tests
- [8.x] 4 consecutive failures in pipeline elasticsearch-periodic
- [8.x] 4 failures in test test {p0=esql/60_usage/Basic ESQL usage output (telemetry) non-snapshot version} (100.0% fail rate in 4 executions)
- [8.x] 4 failures in step release-tests (100.0% fail rate in 4 executions)
- [8.x] 4 failures in pipeline elasticsearch-periodic (100.0% fail rate in 4 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #116462: [CI] EsqlClientYamlAsyncIT test {p0=esql/60_usage/Basic ESQL usage output (telemetry) non-snapshot version} failing
**Build Scans:**
- [elasticsearch-periodic #4774 / release-tests](https://gradle-enterprise.elastic.co/s/2texotcbftrqe)
- [elasticsearch-periodic #4764 / release-tests](https://gradle-enterprise.elastic.co/s/ncawpusglnc3e)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:qa:server:single-node:yamlRestTest" --tests "org.elasticsearch.xpack.esql.qa.single_node.EsqlClientYamlAsyncIT.test {p0=esql/60_usage/Basic ESQL usage output (telemetry) non-snapshot version}" -Dtests.seed=95195E40179A38FA -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dlicense.key=x-pack/license-tools/src/test/resources/public.key -Dtests.locale=hu-Latn-HU -Dtests.timezone=Atlantic/South_Georgia -Druntime.java=23
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.qa.single_node.EsqlClientYamlAsyncIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(test%20%7Bp0%3Desql%2F60_usage%2FBasic%20ESQL%20usage%20output%20(telemetry)%20non-snapshot%20version%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Failure at [esql/60_usage:165]: field [esql.functions] doesn't have length [118]
Expected: <118>
     but: was <116>
```

**Issue Reasons:**
- [main] 2 consecutive failures in test test {p0=esql/60_usage/Basic ESQL usage output (telemetry) non-snapshot version}
- [main] 2 consecutive failures in step release-tests
- [main] 2 consecutive failures in pipeline elasticsearch-periodic
- [main] 2 failures in test test {p0=esql/60_usage/Basic ESQL usage output (telemetry) non-snapshot version} (66.7% fail rate in 3 executions)
- [main] 2 failures in step release-tests (66.7% fail rate in 3 executions)
- [main] 2 failures in pipeline elasticsearch-periodic (66.7% fail rate in 3 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #116463: [CI] EsqlClientYamlAsyncSubmitAndFetchIT test {p0=esql/60_usage/Basic ESQL usage output (telemetry) non-snapshot version} failing
**Build Scans:**
- [elasticsearch-periodic #4774 / release-tests](https://gradle-enterprise.elastic.co/s/2texotcbftrqe)
- [elasticsearch-periodic #4764 / release-tests](https://gradle-enterprise.elastic.co/s/ncawpusglnc3e)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:qa:server:single-node:yamlRestTest" --tests "org.elasticsearch.xpack.esql.qa.single_node.EsqlClientYamlAsyncSubmitAndFetchIT.test {p0=esql/60_usage/Basic ESQL usage output (telemetry) non-snapshot version}" -Dtests.seed=95195E40179A38FA -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dlicense.key=x-pack/license-tools/src/test/resources/public.key -Dtests.locale=fr-CI -Dtests.timezone=America/Vancouver -Druntime.java=23
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.qa.single_node.EsqlClientYamlAsyncSubmitAndFetchIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(test%20%7Bp0%3Desql%2F60_usage%2FBasic%20ESQL%20usage%20output%20(telemetry)%20non-snapshot%20version%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Failure at [esql/60_usage:165]: field [esql.functions] doesn't have length [118]
Expected: <118>
     but: was <116>
```

**Issue Reasons:**
- [main] 2 consecutive failures in test test {p0=esql/60_usage/Basic ESQL usage output (telemetry) non-snapshot version}
- [main] 2 consecutive failures in step release-tests
- [main] 2 consecutive failures in pipeline elasticsearch-periodic
- [main] 2 failures in test test {p0=esql/60_usage/Basic ESQL usage output (telemetry) non-snapshot version} (66.7% fail rate in 3 executions)
- [main] 2 failures in step release-tests (66.7% fail rate in 3 executions)
- [main] 2 failures in pipeline elasticsearch-periodic (66.7% fail rate in 3 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #116464: [CI] EsqlClientYamlIT test {p0=esql/60_usage/Basic ESQL usage output (telemetry) non-snapshot version} failing
**Build Scans:**
- [elasticsearch-periodic #4774 / release-tests](https://gradle-enterprise.elastic.co/s/2texotcbftrqe)
- [elasticsearch-periodic #4764 / release-tests](https://gradle-enterprise.elastic.co/s/ncawpusglnc3e)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:qa:server:multi-node:yamlRestTest" --tests "org.elasticsearch.xpack.esql.qa.multi_node.EsqlClientYamlIT.test {p0=esql/60_usage/Basic ESQL usage output (telemetry) non-snapshot version}" -Dtests.seed=95195E40179A38FA -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dlicense.key=x-pack/license-tools/src/test/resources/public.key -Dtests.locale=en-MY -Dtests.timezone=Pacific/Wake -Druntime.java=23
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.qa.multi_node.EsqlClientYamlIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(test%20%7Bp0%3Desql%2F60_usage%2FBasic%20ESQL%20usage%20output%20(telemetry)%20non-snapshot%20version%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Failure at [esql/60_usage:165]: field [esql.functions] doesn't have length [118]
Expected: <118>
     but: was <116>
```

**Issue Reasons:**
- [main] 2 consecutive failures in test test {p0=esql/60_usage/Basic ESQL usage output (telemetry) non-snapshot version}
- [main] 2 consecutive failures in step release-tests
- [main] 2 consecutive failures in pipeline elasticsearch-periodic
- [main] 2 failures in test test {p0=esql/60_usage/Basic ESQL usage output (telemetry) non-snapshot version} (66.7% fail rate in 3 executions)
- [main] 2 failures in step release-tests (66.7% fail rate in 3 executions)
- [main] 2 failures in pipeline elasticsearch-periodic (66.7% fail rate in 3 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### LINKED ISSUE #116465: [CI] EsqlClientYamlIT test {p0=esql/60_usage/Basic ESQL usage output (telemetry) non-snapshot version} failing
**Build Scans:**
- [elasticsearch-periodic #4774 / release-tests](https://gradle-enterprise.elastic.co/s/2texotcbftrqe)
- [elasticsearch-periodic #4764 / release-tests](https://gradle-enterprise.elastic.co/s/ncawpusglnc3e)

**Reproduction Line:**
```
./gradlew ":x-pack:plugin:esql:qa:server:single-node:yamlRestTest" --tests "org.elasticsearch.xpack.esql.qa.single_node.EsqlClientYamlIT.test {p0=esql/60_usage/Basic ESQL usage output (telemetry) non-snapshot version}" -Dtests.seed=95195E40179A38FA -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dlicense.key=x-pack/license-tools/src/test/resources/public.key -Dtests.locale=ff-Adlm-GM -Dtests.timezone=Asia/Jakarta -Druntime.java=23
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.xpack.esql.qa.single_node.EsqlClientYamlIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(test%20%7Bp0%3Desql%2F60_usage%2FBasic%20ESQL%20usage%20output%20(telemetry)%20non-snapshot%20version%7D),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.AssertionError: Failure at [esql/60_usage:165]: field [esql.functions] doesn't have length [118]
Expected: <118>
     but: was <116>
```

**Issue Reasons:**
- [main] 2 consecutive failures in test test {p0=esql/60_usage/Basic ESQL usage output (telemetry) non-snapshot version}
- [main] 2 consecutive failures in step release-tests
- [main] 2 consecutive failures in pipeline elasticsearch-periodic
- [main] 2 failures in test test {p0=esql/60_usage/Basic ESQL usage output (telemetry) non-snapshot version} (66.7% fail rate in 3 executions)
- [main] 2 failures in step release-tests (66.7% fail rate in 3 executions)
- [main] 2 failures in pipeline elasticsearch-periodic (66.7% fail rate in 3 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by luigidellaquila**
Wrong update of the number of snapshot functions from https://github.com/elastic/elasticsearch/pull/115792

Fixes: https://github.com/elastic/elasticsearch/issues/115231
Fixes: https://github.com/elastic/elasticsearch/issues/116448
Fixes: https://github.com/elastic/elasticsearch/issues/116462
Fixes: https://github.com/elastic/elasticsearch/issues/116463
Fixes: https://github.com/elastic/elasticsearch/issues/116464
Fixes: https://github.com/elastic/elasticsearch/issues/116465

### CODE REVIEW

**Review by ivancea — APPROVED** [review]
LGTM! How did this pass the CI, or why is this failing now?

**Comment by luigidellaquila** [comment]
It only fails on release tests (ie. non-snapshot), the test is excluded in normal builds. 
The final reason is that we see a different number of functions in Snapshot vs. non-Snapshot, so we need two tests that only run in specific configurations.
To see the failure on a PR, you have to label it `test-release`

**Comment by luigidellaquila** [comment]
`KqlQueryBuilderTests` failing, completely unrelated

**Comment by luigidellaquila** [comment]
@elasticmachine update branch

**Pull request merged**
