### PR TITLE
Disallow `_field_names` enabled setting

### PR DESCRIPTION
**Pull request by cbuescher**
After deprecating the setting starting with 7.5 in #42854, this change disallows
setting enabled for the `_field_names` field on new indices. The setting
continues to work for indices created in 7.x where we still emit a deprecation
warning.

### CODE REVIEW

**Review by jtibshirani — APPROVED** [review]
Looks good to me -- just made a couple notes about typos that would be good to fix before merging.

**Comment by cbuescher** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by cbuescher** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by cbuescher** [comment]
@elasticmachine run elasticsearch-ci/2

**Pull request merged**
