### PR TITLE
TSDB: Automatically add timestamp mapper

### PR DESCRIPTION
**Pull request by weizijun**
If tsdb is enabled we need an @timestamp meta field. This automatically
maps timestamp and enable _data_stream_timestamp field.
 
the PR is base on https://github.com/elastic/elasticsearch/pull/78016 , and add _data_stream_timestamp field.

Another PR will rename DataStreamTimestampFieldMapper to TimestampFieldMapper

### CODE REVIEW

**Comment by imotov** [comment]
@elasticmachine test this please

**Comment by weizijun** [comment]
@imotov I'm running gradle check in our test machine.I will check first.

**Comment by weizijun** [comment]
@imotov I have passed all tests, and merged the master, fixed the failed tests.

**Comment by imotov** [comment]
@elasticmachine test this please

**Review by nik9000 — COMMENTED** [review]
@martijnvg could you have a look at this one please? I don't know much about the timestamp field mapper but this seems like the right way to make it always available and to turn it on for tsdb by default.

**Review by martijnvg — APPROVED** [review]
The change related to timestamp field LGTM.
Also this cleans some test up to now that the timestamp meta field is always available.

**Pull request merged**
