### PR TITLE
Fix Ex. Handling in SnapshotsService#snapshots

### LINKED ISSUE #47442: [CI] SnapshotDisruptionIT testDisruptionOnSnapshotInitialization failed in 6.8
`org.elasticsearch.discovery.SnapshotDisruptionIT testDisruptionOnSnapshotInitialization` failed in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.8+multijob-unix-compatibility/os=ubuntu-16.04&&immutable/299/console (scan https://gradle-enterprise.elastic.co/s/cmj4ig7w72la6)

The error was:

```
13:27:37 ERROR   49.7s J2  | SnapshotDisruptionIT.testDisruptionOnSnapshotInitialization <<< FAILURES!
13:27:37    > Throwable #1: SnapshotException[[test-repo:test-snap-2/0FtjxNKfRQatK_1HB_Ri9g] Snapshot could not be read]; nested: SnapshotMissingException[[test-repo:test-snap-2/0FtjxNKfRQatK_1HB_Ri9g] is missing]; nested: NoSuchFileException[/var/lib/jenkins/workspace/elastic+elasticsearch+6.8+multijob-unix-compatibility/os/ubuntu-16.04&&immutable/server/build/testrun/integTest/J2/temp/org.elasticsearch.discovery.SnapshotDisruptionIT_CCE6937203AE3890-001/tempDir-002/repos/pSFBIYthUy/snap-0FtjxNKfRQatK_1HB_Ri9g.dat];
13:27:37    > 	at __randomizedtesting.SeedInfo.seed([CCE6937203AE3890:E639B5A225B6CB4F]:0)
13:27:37    > 	at org.elasticsearch.snapshots.SnapshotsService.snapshots(SnapshotsService.java:212)
13:27:37    > 	at org.elasticsearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.masterOperation(TransportGetSnapshotsAction.java:136)
13:27:37    > 	at org.elasticsearch.action.admin.cluster.snapshots.get.TransportGetSnapshotsAction.masterOperation(TransportGetSnapshotsAction.java:55)
13:27:37    > 	at org.elasticsearch.action.support.master.TransportMasterNodeAction.masterOperation(TransportMasterNodeAction.java:124)
13:27:37    > 	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$2.doRun(TransportMasterNodeAction.java:211)
13:27:37    > 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:751)
13:27:37    > 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
13:27:37    > 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
13:27:37    > 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
13:27:37    > 	at java.lang.Thread.run(Thread.java:748)
13:27:37    > Caused by: SnapshotMissingException[[test-repo:test-snap-2/0FtjxNKfRQatK_1HB_Ri9g] is missing]; nested: NoSuchFileException[/var/lib/jenkins/workspace/elastic+elasticsearch+6.8+multijob-unix-compatibility/os/ubuntu-16.04&&immutable/server/build/testrun/integTest/J2/temp/org.elasticsearch.discovery.SnapshotDisruptionIT_CCE6937203AE3890-001/tempDir-002/repos/pSFBIYthUy/snap-0FtjxNKfRQatK_1HB_Ri9g.dat];
13:27:37    > 	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.getSnapshotInfo(BlobStoreRepository.java:558)
13:27:37    > 	at org.elasticsearch.snapshots.SnapshotsService.snapshots(SnapshotsService.java:206)
13:27:37    > 	... 9 more
13:27:37    > Caused by: java.nio.file.NoSuchFileException: /var/lib/jenkins/workspace/elastic+elasticsearch+6.8+multijob-unix-compatibility/os/ubuntu-16.04&&immutable/server/build/testrun/integTest/J2/temp/org.elasticsearch.discovery.SnapshotDisruptionIT_CCE6937203AE3890-001/tempDir-002/repos/pSFBIYthUy/snap-0FtjxNKfRQatK_1HB_Ri9g.dat
13:27:37    > 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
13:27:37    > 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
13:27:37    > 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
13:27:37    > 	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
13:27:37    > 	at java.nio.file.Files.newByteChannel(Files.java:361)
13:27:37    > 	at java.nio.file.Files.newByteChannel(Files.java:407)
13:27:37    > 	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
13:27:37    > 	at org.apache.lucene.mockfile.FilterFileSystemProvider.newInputStream(FilterFileSystemProvider.java:192)
13:27:37    > 	at org.apache.lucene.mockfile.FilterFileSystemProvider.newInputStream(FilterFileSystemProvider.java:192)
13:27:37    > 	at org.apache.lucene.mockfile.FilterFileSystemProvider.newInputStream(FilterFileSystemProvider.java:192)
13:27:37    > 	at org.apache.lucene.mockfile.HandleTrackingFS.newInputStream(HandleTrackingFS.java:92)
13:27:37    > 	at org.apache.lucene.mockfile.FilterFileSystemProvider.newInputStream(FilterFileSystemProvider.java:192)
13:27:37    > 	at org.apache.lucene.mockfile.HandleTrackingFS.newInputStream(HandleTrackingFS.java:92)
13:27:37    > 	at java.nio.file.Files.newInputStream(Files.java:152)
13:27:37    > 	at org.elasticsearch.common.blobstore.fs.FsBlobContainer.readBlob(FsBlobContainer.java:120)
13:27:37    > 	at org.elasticsearch.repositories.blobstore.ChecksumBlobStoreFormat.readBlob(ChecksumBlobStoreFormat.java:101)
13:27:37    > 	at org.elasticsearch.repositories.blobstore.BlobStoreFormat.read(BlobStoreFormat.java:90)
13:27:37    > 	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.getSnapshotInfo(BlobStoreRepository.java:556)
13:27:37    > 	... 10 more
```

This did not reproduce locally on the 6.8 branch using:

```
./gradlew ':server:integTest'   -Dtests.seed=CCE6937203AE3890   -Dtests.class=org.elasticsearch.discovery.SnapshotDisruptionIT   -Dtests.method="testDisruptionOnSnapshotInitialization"   -Dtests.security.manager=true   -Dtests.locale=ja-JP-u-ca-japanese-x-lvariant-JP   -Dtests.timezone=America/Santo_Domingo   -Dcompiler.java=12   -Druntime.java=8
```

### PR DESCRIPTION
**Pull request by original-brownbear**
We're needlessly wrapping a `SnapshotMissingException` which
itself is a `SnapshotException` when trying to load a missing
snapshot. This leads to failure #47442 which expects a
`SnapshotMissingException` in this case.

I suggest we backport it to all active branches to fix this test since it was initially reported on `6.8` but will fail the same way on `master` (albeit very unlikely there due to some changes in how things are scheduled).

Closes #47442

### CODE REVIEW

**Review by ywelsch — COMMENTED** [review]
Can you add a test that checks this more reliably, given, as you pointed out, this might only very rarely fail if we were to mistakenly remove this in the future.

**Comment by original-brownbear** [comment]
@ywelsch thanks, added a test that reproduces the exact situation that test ran into https://github.com/elastic/elasticsearch/pull/47507/commits/c15ce0108620560e3d8f02b275f528b77eb9f822 now.

**Review by ywelsch — APPROVED** [review]
LGTM

**Comment by original-brownbear** [comment]
Thanks Yannick!

**Pull request merged**
