### PR TITLE
Update update.asciidoc

### PR DESCRIPTION
**Pull request by githubyyf**
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "[script] unknown field [source], parser not found"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "[script] unknown field [source], parser not found"
  },
  "status": 400
}

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by githubyyf** [comment]
Change “source" to "inline",
"reason": "[script] unknown field [source], parser not found"

**Comment by githubyyf** [comment]
Sorry, I saw the Edit button, just clicked, jumped to this page, and I thought it was submitting my changes and reviewing it for the developer

**Review by cbuescher — CHANGES_REQUESTED** [review]
@githubyyf thanks for opening this issue, but I'm afraid this change doesn't seem to be right with regards to the docs version you are opening this for. In 6.0 the former `inline` is deprecated for `source` and will issue a deprecation warning. You might see the above error you mentioned for a different version. Can you recheck the version and either close this PR or open towards a different branch of the docs please?

**Comment by cbuescher** [comment]
I just rechecked this and believe the docs are alright for versions 6.0 and upwards, so I'm going to close this one. Feel free to reopen if you disagree.

**Pull request closed without merging**
