### PR TITLE
Add HLRC for EQL search

### PR DESCRIPTION
**Pull request by imotov**
Adds EQL HLRC client with the search method.

Relates to #51961
Backport of #52363

### CODE REVIEW

**Comment by aleksmaus** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample-matrix-unix

**Comment by aleksmaus** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample-matrix-unix

**Comment by imotov** [comment]
@elasticmachine update branch

**Comment by imotov** [comment]
It's just a trivial backport. So, no need for a review, I suppose.

**Pull request merged**
