### PR TITLE
DOCS: match-query: fix highlighting in example

### PR DESCRIPTION
**Pull request by rursprung**

### CODE REVIEW

**Review by cbuescher — APPROVED** [review]
Thanks @rursprung, LGTM. Would you mind signing the CLA so we can merge this?

**Comment by cbuescher** [comment]
Hi @rursprung, just re-checking if you can sign the CLA please, otherwise we cannot merge this PR.

**Comment by rursprung** [comment]
sorry, totally forgot about this... i now signed the CLA

**Comment by cbuescher** [comment]
@elasticmachine test this please

**Pull request merged**
