### PR TITLE
Operator factor settings should have the OperatorDynamic setting property

### PR DESCRIPTION
**Pull request by tlrx**
Relates #82819

### CODE REVIEW

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Comment by tlrx** [comment]
@elasticmachine run elasticsearch-ci/part-1

**Comment by tlrx** [comment]
@elasticmachine update branch

**Review by idegtiarenko — APPROVED** [review]

**Comment by tlrx** [comment]
Thanks David and Ievgen

**Pull request merged**
