### PR TITLE
Support dotted field names in counted_keyword

### PR DESCRIPTION
**Pull request by danielmitterdorfer**
With this commit we correctly handle dotted field names in the recently introduced `counted_keyword` field type.

Relates #101826

### CODE REVIEW

**Comment by danielmitterdorfer** [comment]
Marking as `non-issue` because https://github.com/elastic/elasticsearch/pull/101826 has not been released yet (targeted for 8.12.0).

**Comment by danielmitterdorfer** [comment]
there was a transient test failure in the BWC tests:

```
TestClustersException: process was found dead while waiting for ports files, node{:x-pack:qa:rolling-upgrade:v8.12.0-0}
```

@elasticsearchmachine run elasticsearch-ci/bwc-snapshots

**Review by martijnvg — APPROVED** [review]
LGTM

**Comment by danielmitterdorfer** [comment]
@elasticmachine run elasticsearch-ci/bwc-snapshots

**Comment by danielmitterdorfer** [comment]
@elasticmachine run elasticsearch-ci/8.12.0 / bwc-snapshots

**Comment by danielmitterdorfer** [comment]
@elasticmachine merge upstream

**Pull request merged**
