### PR TITLE
Upgrade 7.x to lucene-8.2.0-snapshot-860e0be5378

### PR DESCRIPTION
**Pull request by nknize**
Upgrades 7.x branch to latest snapshot of lucene 8.2.0

### CODE REVIEW

**Comment by dnhatn** [comment]
@nknize I think we need to upgrade the master branch to Lucene 8.2.0-snapshot first; otherwise BWC tests on the master will fail.

**Comment by nknize** [comment]
@dnhatn https://github.com/elastic/elasticsearch/pull/44171  master was upgraded earlier

**Review by dnhatn — APPROVED** [review]
LGTM. Thanks @nknize.

**Comment by dnhatn** [comment]
> @dnhatn #44171 master was upgraded earlier

Sorry I was on an outdated master. I have replaced `7x` label with 7.4 as we don't use 7x for PR.

**Pull request merged**
