### PR TITLE
Remove obsolete check for versions supporting snapshot recovery

### PR DESCRIPTION
**Pull request by thecoop**
Master will always be >=7.17, so this node version check is not needed anymore

### CODE REVIEW

**Comment by thecoop** [comment]
@elasticsearchmachine rerun elasticsearch-ci/part-2

**Comment by thecoop** [comment]
@elasticmachine rerun elasticsearch-ci/part-2

**Review by ldematte — APPROVED** [review]
LGTM

**Comment by thecoop** [comment]
@elasticmachine update branch

**Comment by thecoop** [comment]
@elasticmachine update branch

**Comment by thecoop** [comment]
@elasticmachine update branch

**Review by DaveCTurner — APPROVED** [review]
LGTM2

**Pull request merged**
