### PR TITLE
Security behaves more like core with aliases

### PR DESCRIPTION
**Pull request by jaymode**
This change updates the logic in Security's indices and aliases
resolver to be more like that of the IndexNameExpression resolver
especially when it concerns aliases with closed indices.

### CODE REVIEW

**Comment by albertzaharovits** [comment]
According to my reading of the code, this change makes it so that wildcards (including `empty` and `*`) will not match the _aliases_ that point to at least some indices that should not be visible (e.g. closed indices).

This is different from how _core_ does wildcard expansion, because in core the same wildcard will match the alias, and then the alias will expand to only the visible pointed to indices, in a single step, according to the nefarious `expand_wildcards` request option.

It is of course different from the current behavior, where the wildcard expands to aliases that point to indices that should not be visible, and then the request will fail in the _core_ index name resolver because explicit aliases to invisible indices are not permitted (unless explicitly permitted by request options).

Hoping I'm reading it well, I assume the rationale is to improve on the user experience where a single stray alias, pointing to closed indices, can trip a wildcard indices request (see https://github.com/elastic/elasticsearch/issues/29948), which I believe is a good improvement. It is though disputable, because technically, under this change, wildcards with security enabled expand to a subset of the indices to which wildcards when security is disabled expand to.

I'm on the fence between the two, I could be swayed either way.

Let us know if there is something in particular you wish to discuss, or if we should expect you to join our team meeting to discuss it.

**Comment by jaymode** [comment]
Thanks @albertzaharovits for taking a look.

> According to my reading of the code, this change makes it so that wildcards (including empty and *) will not match the aliases that point to at least some indices that should not be visible (e.g. closed indices).

The code as originally pushed didn't do what I wanted it to do. The logic I am attempting to bring into Security is a distilled version of this logic:

https://github.com/elastic/elasticsearch/blob/f6d89aee38331ebc91669f23acd814dada434873/server/src/main/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolver.java#L181-L245

In the modified code,`isIndexVisible` is called for wildcard and datemath expansion. Historically we've treated datemath like wildcards so for simplicity I do not differentiate now. The modifications make the following changes when evaluating an alias:

1. Take `IndicesOptions#ignoreAliases` into account. If it is an alias, then we respect ignore aliases now.
2. Respect `IndicesOptions#forbidClosedIndices`. If an alias was resolved but contains closed indices, which is forbidden then we say the alias is not visible unless we are *not* ignoring unavailable indices in which case we expect the request to fail.
3. Respect `IndicesOptions#ignoreUnavailable`. If an alias points to indices that should be excluded, we can mark it as visible if we can ignore those that are not available.
4. Respect `IndicesOptions#allowNoIndices`. If an alias points to indices that are all excluded, then there are no indices so the alias will only be visible if we allow no indices.

Ultimately, this is in an attempt to align what indices a request made with and without security would expand to.

> Let us know if there is something in particular you wish to discuss, or if we should expect you to join our team meeting to discuss it.

Unfortunately I will not be able to join the next team meeting. I'd like to see what the team thinks of the behavior change and whether this is something the team would like to have incorporated. Additionally, I have also raised #52663, which opens things up for Security to do its own wildcard resolution in the future. I think in the short term incorporating some version of the changes here is the best path forward for our users.

**Comment by tvernum** [comment]
We discussed this last week in the Security area meeting (sorry for the delayed update).

The general view was this is still different to core, and the tradeoffs are _different_ which might be better for some people but also has some issues, so we didn't think that switching it from one version of "doesn't behave quite the same as core" to a different version of "doesn't behave quite the same as core" was good for users.

**Pro**: This will _break_ less often - currently alias resolution will trigger things like searching closed indices, which then fails

**Con**: There are cases where this will be different to core, but it won't be obvious to users. 
If 
- `my-alias1` points to `open-index1` and `closed-index1`, _and_
- `my-alias2` points to `open-index2`, _then_  
-  then searching `my-*` in core would search `open-index1` and `open-index2`.
-  with this change, securionty would only search `open-index2` and the user might not be aware that their results were excluding an index that they expected to search. They would  have to look at the search result (number of indices) to notice that.

Fundamentally the problem we have is that:

1. Security does expansion early in the action processing
2. Security wants `my-*` to expand to all the things you have access to, subject to indices options, and exclude matches that you don't have access to.
3. Supporting permissions expressed on aliases means that we can't expect alias names to index names during the expansion phase because it happens before the authz phase, so we need to expand to the names that match the permissions.
4. Core treats names expressed explicitly (`my-alias1`) and wildcards (`my-*`) differently, so by expanding wildcards up front security changes the behaviour of core.
5. Expansion and authz need to be considered separately because (a) not all requests require alias expansion and (b) we expand wildcards irrespective of the action. Specifically if you have `read` on `a1` and `all` on `a2` then `DELETE a*` will expand to `DELETE a1,a2` and then fail because you don't have delete on a1. This is intentional, and desired. The wildcard expansion is supposed to take into account _indices that you are aware exist_ not _indices on which you can perform this operation_.  

When an alias points to more than 1 index, and those indices have different properties with respect to indices options, we have no good option:
   - If we expand the wildcard to the real alias, then core will expand it to indices that should not be included (per 4)
   - If we don't include the alias, then an index that would have been included will not be.
   - If we don't expand the wildcard, then we risk core expanding it to something the user doesn't have access to (`my-secret-index`) (per 2)
   - If we replace the alias with the appropriate index names we potentially expand a name that the user does have access to, to something they don't, and security authz will fail (per 3) 


The only solution I can see, other than dropping permissions on aliases (point 3 above), is during expansion, we replace the wildcard with something that meets the following criteria:

1. Authz checks can verify that it is definitively allowed (see point 5 above)
2. Core will expand it as if it were a wildcard not a concrete name (see point 4 above)
3. Core will only expand it to the things security believed it should be expanded to (see point 2 above).

I think something like https://github.com/elastic/elasticsearch/pull/52663 (sorry, I haven't had time to dig into it the implementation yet), could set us up to do that by doing the wildcard replacement much like we do now, except rather than replacing the index names directly, attach something to the thread context to say _`my-*` should expand to `my-alias1` and `my-alias2` (but not `my-secret-index`)_ Then the authz service can do checks on those names (satisfying criteria 1), core will treat it as a wildcard because we didn't replace it directly (satisfying criteria 2), and the security pluggable resolver can control the expansion to be exactly the names that were expanded in the first  phase (satisfying 3).

**Comment by jaymode** [comment]
Given the last response, I am closing this since we believe there is a better solution.

**Pull request closed without merging**
