### PR TITLE
[docs] Fix typo in repository-s3.asciidoc

### PR DESCRIPTION
**Pull request by carsonip**
Same as #113572 but targeting `8.x` and `main`.

### CODE REVIEW

**Review by DaveCTurner — APPROVED** [review]
D'oh

**Comment by carsonip** [comment]
Ooops, race condition on github labels :facepalm:

**Comment by carsonip** [comment]
@DaveCTurner I'll leave the PR to you, thanks!

**Comment by carsonip** [comment]
Removing 8.15 as it is already done in https://github.com/elastic/elasticsearch/pull/113572. I only opened this PR as I noticed https://github.com/elastic/elasticsearch/pull/113572 only covered 8.15.

**Pull request merged**
