### PR TITLE
[Transform] improve TransformRestTestCase robustness

### LINKED ISSUE #54810: [CI] TransformConfigurationIndexIT.testDeleteConfigurationLeftOver failures
Jenkins: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.7+matrix-java-periodic/ES_RUNTIME_JAVA=openjdk14,nodes=general-purpose/23/console

Build scan: https://gradle-enterprise.elastic.co/s/skpba3jxaypqk

Failure:

```
org.elasticsearch.client.ResponseException: 
method [GET], host [http://[::1]:46410], URI [.transform-notifications-000002/_search?ignore_unavailable=true], status line [HTTP/1.1 503 Service Unavailable]
{"error":{"root_cause":[],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[]},"status":503}

at __randomizedtesting.SeedInfo.seed([61CEE881B62A7B54:3FFF0103521740CE]:0)
at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:283)
at org.elasticsearch.client.RestClient.performRequest(RestClient.java:261)
at org.elasticsearch.client.RestClient.performRequest(RestClient.java:267)
at org.elasticsearch.client.RestClient.performRequest(RestClient.java:235)
at org.elasticsearch.xpack.transform.integration.TransformRestTestCase.logAudits(TransformRestTestCase.java:506)
at org.elasticsearch.xpack.transform.integration.TransformRestTestCase.waitForTransform(TransformRestTestCase.java:383)
```

Reproduce with:

```
./gradlew ':x-pack:plugin:transform:qa:single-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.transform.integration.TransformConfigurationIndexIT.testDeleteConfigurationLeftOver" -Dtests.seed=61CEE881B62A7B54 -Dtests.security.manager=true -Dtests.locale=ar -Dtests.timezone=Pacific/Guam -Dcompiler.java=13
HomeTestsorg.elasticsearch.xpack.transform.integration.TransformConfigurationIndexIT » testDeleteConfigurationLeftOver
```

Cannot reproduce locally.

### PR DESCRIPTION
**Pull request by hendrikmuhs**
handles/retries temporary SearchPhaseExecutionErrors

fixes #54810

### CODE REVIEW

**Comment by droberts195** [comment]
I wonder if the root cause of the failure is that https://github.com/elastic/elasticsearch/blob/df44a82e81ebe6383e0b9d9339a497d6860b682e/x-pack/plugin/transform/qa/single-node-tests/src/test/java/org/elasticsearch/xpack/transform/integration/TransformRestTestCase.java#L383 doesn't wait for hidden indices?  The cluster health check in https://github.com/elastic/elasticsearch/blob/87ce139b46c0297c1daebae408f7b8e5e037ab5f/test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java#L1026 doesn't specify any indices options.  This might explain why the failures started when hidden indices were introduced.

**Comment by hendrikmuhs** [comment]
> I wonder if the root cause of the failure is that
> 
> https://github.com/elastic/elasticsearch/blob/df44a82e81ebe6383e0b9d9339a497d6860b682e/x-pack/plugin/transform/qa/single-node-tests/src/test/java/org/elasticsearch/xpack/transform/integration/TransformRestTestCase.java#L383
> doesn't wait for hidden indices? The cluster health check in
> 

I found this:

https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/action/admin/cluster/health/ClusterHealthRequest.java#L42

Looks like hidden indices are part of the default. 
@gwbrown can you confirm?

Regarding `ensureNoInitializingShards`: I moved this in the last attempt to fix this bug:

https://github.com/yyff/elasticsearch/commit/12df0a136717ac36cc2a55eb4f38c5a6b7e6f9ec

I do not want to rule out, its a problem of the test, we

**Comment by hendrikmuhs** [comment]
The test started failing march 26th, this is 6 days after the notification index  was made hidden. 

(The audit logging was added february 18th.)

The logs unfortunately do not show a full picture, because we lack when `ensureNoInitializingShards` has been called. We could add logging.

The cluster health reported in the logs, turns green _after_ the search phase execution exception:

```
     [2020-04-24T09:29:35,602][INFO ][o.e.c.r.a.AllocationService] [integTest-0] current.health="GREEN" message="Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[.transform-notifications-000002][0]]])." previous.health="YELLOW" reason="shards started [[.transform-notifications-000002][0]]"
```

This indicates that the cluster health indeed might have been green at the time `ensureNoInitializingShards` has been called.

LBNL, the failure only happens for `testDeleteConfigurationLeftOver`, but there are many more tests using `TransformRestTestCase`. The test is special in the sense that it does not interact much with the transform API but simulates a corner case situation: It indexes a document and checks whether transform `DELETE` is able to delete the doc. I think there is only 1 audit message in total, send late by the delete call. The audit message is indexed async, so maybe it is indeed a timing issue of parallel threads on a slow host (I was never able to reproduce this issue on my laptop).

Instead of the `assertBusy` loop I added in the log forwarder, I could add a busy loop to check, that the notification index exists, which is a valid assumption for `TransformRestTestCase`.

**Review by droberts195 — APPROVED** [review]
> Looks like hidden indices are part of the default

In that case I am happy to work around this in the test code, so this PR LGTM

**Pull request merged**
