### PR TITLE
Remove timezone validation on rollup range queries

### PR DESCRIPTION
**Pull request by polyfractal**
We enforced the timezone of range queries when using the rollup search endpoint, but this validation is not needed.  Since rollup dates are stored in UTC, and range queries are always converted to UTC (even if specifying a `time_zone`) the validation is not needed and can prevent legitimate queries from running.

### CODE REVIEW

**Review by jimczi — APPROVED** [review]
LGTM

**Comment by polyfractal** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by polyfractal** [comment]
@elasticmachine test this please

**Comment by rayafratkina** [comment]
Note that we have a blocker on Kibana caused by this: https://github.com/elastic/kibana/issues/33974
We don't have a workaround so from out pov, this issue needs to be a blocker or rollups will remain broken in the UI.

**Comment by polyfractal** [comment]
@rayafratkina When I discussed with @jasontedor earlier we decided it didn't qualify as a blocker for the 7.0 train because Rollup is still an experimental feature, and this only impacts dashboards that are using non-UTC timezones.  

Also, this validation has been there since 6.4 so I'm surprised dashboards are/were working at all with non-UTC timezones (from the timepicker range, not the date_histo config).

**Comment by colings86** [comment]
@polyfractal this looks like its still pending the backport for 6.7, is that correct? I'm going to label it assuming this is correct for now

**Comment by polyfractal** [comment]
Sorry yes, still waiting on backport to 6.7

**Comment by jeremygachet** [comment]
Hello, 
we still have the same bug in kibana. 
This fix has been merged  ?

**Pull request merged**
