### PR TITLE
Dry up TransportResponseHandler

### PR DESCRIPTION
**Pull request by original-brownbear**
I keep typing this over and over so I figured I'd dry it up:

The majority of implementations of this interface run on `SAME`.
Drying this up saves some duplication and also makes it a little
easier to understand what callbacks won't fork-off when reading the
code.

### CODE REVIEW

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/bwc
Jenkins run elasticsearch-ci/default-distro

**Review by rjernst — COMMENTED** [review]
This looks fine, but is there any reason this couldn't live as a default implementation of `executor()` on the TransportResponseHandler interface?

**Comment by original-brownbear** [comment]
> This looks fine, but is there any reason this couldn't live as a default implementation of executor() on the TransportResponseHandler interface?


yea that's the cleaner approach indeed -> moved to that now thanks! :)

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/2

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by original-brownbear** [comment]
Thanks Ryan!

**Pull request merged**
