### PR TITLE
Revert "Return error when remote indices are locally resolved (#74762)"

### PR DESCRIPTION
**Pull request by jtibshirani**
This commit is causing searches that use remote patterns like `*:test` to fail
with the error "Cross-cluster calls are not supported in this context but
remote indices were requested: [*:test]". I don't think this was the intention
of the original PR, which targeted APIs like 'get' that do not support
cross-cluster calls.

This is blocking release testing, so I'm reverting for now. We can re-introduce
the PR later along with a test for this search case.

### CODE REVIEW

**Review by dnhatn — APPROVED** [review]
LGTM. Can we also mark the original PR as non-issue so it won't make into the release notes?

**Comment by jtibshirani** [comment]
Will do! Thanks for reviewing.

**Comment by jtibshirani** [comment]
Pinging @javanna @jimczi so you know we reverted this. I wasn't able to figure out a good self-contained fix.

**Comment by javanna** [comment]
Thanks for taking care of this @jtibshirani . I did some digging and I understand better what happened. In our main branch any remote cluster expression will be intercepted and converted directly when resolving remote cluster names, hence such expressions won't ever make it to the index name expression resolver which resolves local indices names. 

In our 7.x branches though, we still account for indices created in 6.x that may contain a `:`, hence if a remote cluster expression does not resolve to any remote cluster it ends up being treated as a local expression. What I have missed in my original PR is a test without remote clusters configured or with a remote cluster expressions that would not match any configured remote cluster. In those two scenarios the search API would also be affected by the error that was only intended for API that don't support executing against remote clusters.

**Pull request merged**
