### PR TITLE
Enable GC logs by default

### PR DESCRIPTION
**Pull request by jasontedor**
For too long we have been groping around in the dark when faced with GC issues because we rarely have GC logs at our disposal. This commit enables GC logging by default out of the box.

@danielmitterdorfer Please review the GC log settings.

@rjernst Please review the packaging changes.

### CODE REVIEW

**Review by danielmitterdorfer — APPROVED** [review]
Great to have this on by default now! The activated options are a good start IMHO. 

Does it make sense to briefly mention this in the docs (that they are on by default, configured in `config/jvm.options` and they take up to 2GB of space)?

LGTM.

**Review by s1monw — APPROVED** [review]
LGTM

**Comment by jasontedor** [comment]
@danielmitterdorfer I pushed docs in a166455b1f357588461e8042e9a0bb6b35daad9e if you want to take a look?

**Comment by danielmitterdorfer** [comment]
> @danielmitterdorfer I pushed docs in a166455 if you want to take a look?

Thanks! LGTM.

**Pull request merged**
