### PR TITLE
Fix VectorsFeatureSetUsage serialization in BWC mode

### LINKED ISSUE #55378: [CI] UpgradeClusterClientYamlTestSuiteIT fails for usage stats on analytics indices
Upgrade tests are still failing after #55181, an illegal argument exception is thrown:

> IllegalArgumentException[Unknown NamedWriteable [org.elasticsearch.xpack.core.XPackFeatureSet$Usage][]];

when the test "Basic test for usage stats on analytics indices" is executed. As there is some background around XPack Usage backward compatibility I prefer to just mute this test and assign the issue.

The failure occurs in the ':x-pack:qa:rolling-upgrade:v7.8.0#twoThirdsUpgradedTest' task.

I've collected the last builds scans:

- https://gradle-enterprise.elastic.co/s/gj5m7daqsm6js
- https://gradle-enterprise.elastic.co/s/hg4zzh2ft5pno
- https://gradle-enterprise.elastic.co/s/7b63xqcokbib2
- https://gradle-enterprise.elastic.co/s/sd6xtj2zhgt66
- https://gradle-enterprise.elastic.co/s/jtfzk6n3w6coo
- https://gradle-enterprise.elastic.co/s/wpfyemdc5o3q2
- https://gradle-enterprise.elastic.co/s/bxa4y6otxlcne

The failure does not reproduce locally.

### PR DESCRIPTION
**Pull request by imotov**
While communicating with an earlier version of elasticsearch,
VectorsFeatureSetUsage is using writeInt instead of writeVInt that 7.x version
is expecting. This commit fixes the issue.

Fixes #55378

### CODE REVIEW

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by imotov** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Review by jtibshirani — APPROVED** [review]
Thanks again @imotov for the fix. It's great we have BWC tests now.

**Comment by imotov** [comment]
@elasticmachine update branch

**Comment by imotov** [comment]
@elasticsearchmachine run elasticsearch-ci/2

**Pull request merged**
