### PR TITLE
[ML] Apply source query on data frame analytics memory estimation

### LINKED ISSUE #49454: [ML] Data Frame Analytics memory estimation ignores Query
The Memory estimation process uses the extractor against the source index before the data frame analytics process runs. But, in doing this, it ignores the the data frame analytics source query. 

Extractor simply does a match_all: https://github.com/elastic/elasticsearch/blob/1dd816f030e256f497c1726695d1209a481b9d8e/x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/dataframe/extractor/DataFrameDataExtractorFactory.java#L42..L58

And the estimation process uses the extractor to determine row and column counts: https://github.com/elastic/elasticsearch/blob/12528b351a99941ffc1d44dd2c0265768ef79635/x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/dataframe/process/MemoryUsageEstimationProcessManager.java#L59..L60

The memory estimator needs to account for a defined query when estimating against the source index.

### PR DESCRIPTION
**Pull request by dimitris-athanasiou**
This is the same fix as #49517 but as the code around the fix has changed
quite a bit, the fix had to be reworked. The idea is the same though.

Closes #49454

### CODE REVIEW

**Review by przemekwitek — APPROVED** [review]
LGTM

**Comment by dimitris-athanasiou** [comment]
Holding off merging this in until 7.5.0 goes out.

**Comment by benwtrent** [comment]
@dimitris-athanasiou does this change also take into account different training percentages? As those should effect memory estimations if they do not.

**Comment by dimitris-athanasiou** [comment]
@benwtrent Regardless of the value of `training_percent` we load both training and non-training rows into the c++ data frame. We do so as predictions are calculated for non-training rows. Thus, I don't think this affects the memory estimation.

**Pull request merged**
