### PR TITLE
Increase chunk_size max to 256 Mb instead of 64 Mb

### LINKED ISSUE #23446: Increase chunk_size max to 256 Mb instead of 64 Mb
While working on an azure issue, I found [this documentation](https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/understanding-block-blobs--append-blobs--and-page-blobs) which says that we can now increase the max block blob to 256mb instead of the default 64mb which has been introduced in #22577

> # About Block Blobs
> Block blobs let you upload large blobs efficiently. Block blobs are comprised of blocks, each of which is identified by a block ID. You create or modify a block blob by writing a set of blocks and committing them by their block IDs. Each block can be a different size, up to a maximum of 100 MB (4 MB for requests using REST versions before 2016-05-31), and a block blob can include up to 50,000 blocks. The maximum size of a block blob is therefore slightly more than 4.75 TB (100 MB X 50,000 blocks). For REST versions before 2016-05-31, the maximum size of a block blob is a little more than 195 GB (4 MB X 50,000 blocks). If you are writing a block blob that is no more than 256 MB (64 MB for requests using REST versions before 2016-05-31) in size, you can upload it in its entirety with a single write operation; see [Put Blob](https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/put-blob).

### PR DESCRIPTION
**Pull request by nmjacob**
Increasing the max size of the chunk from 64mb to 256mb.

Closes #23446.

### CODE REVIEW

**Comment by nmjacob** [comment]
This is my first time doing a public repo pr, please let me know if I need to correct anything.

**Comment by rjernst** [comment]
@nmjacob Since the chunk size is already configurable, I'm not sure why a change to the default is needed. Can you explain why you think 256mb is a better default for most users? @dadoonet thoughts?

**Comment by dadoonet** [comment]
> Can you explain why you think 256mb is a better default for most users?

@rjernst If you want to send to Azure repo a 1Gb file, with the current default, it will require 16 HTTP requests. With that change we can do it with 4 HTTP requests.
I expect it to be a bit faster. Just a guess though. @abeyad WDYT?

**Comment by abeyad** [comment]
Reading the documentation, it appears that 256mb would be the optimal chunk size corresponding to an Azure blob block.  We haven't tested it so its an unknown, but it makes sense to go with the documented recommendation from Azure.  I do think we should run tests on this against an actual Azure storage account to see if it makes a difference.

**Comment by rjernst** [comment]
If it is the recommended then +1 to change (with testing as @abeyad mentions). One thing to double check with that testing is how it performs with default settings (ie from a laptop as a new user would try it out).

**Comment by ywelsch** [comment]
superseded by #32101

**Pull request closed without merging**
