### PR TITLE
Fix a sneaky bug in rare_terms

### LINKED ISSUE #51020: Filter aggregation fails with `index_out_of_bounds_exception` when nested within `rare_terms`
**Elasticsearch version** (`bin/elasticsearch --version`): 7.5 on Elastic Cloud

**Description of the problem including expected versus actual behavior**:

I am nesting a `filter` aggregation within a `rare_terms` aggregation:

```
GET metricbeat-7.5.1-2019.12.26-000001/_search
{
  "size": 0,
  "aggs": {
    "rare": {
      "rare_terms": {
        "field": "process.name",
        "max_doc_count": 3
      },
      "aggs": {
        "filter": {
          "filter": {
            "range": {
              "@timestamp": {
                "gte": "now-15m"
              }
            }
          }
        }
      }
    }
  }
}
```

 Some (or all) shards fail, returning an `index_out_of_bounds_exception`.

```
{
  "error": {
    "root_cause": [
      {
        "type": "index_out_of_bounds_exception",
        "reason": "index_out_of_bounds_exception: -1429505 is out of bounds: [0-1452587["
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": [
      {
        "shard": 0,
        "index": "metricbeat-7.5.1-2019.12.26-000001",
        "node": "NKmctNiHRTmKb2eNEhREIg",
        "reason": {
          "type": "index_out_of_bounds_exception",
          "reason": "index_out_of_bounds_exception: -1429505 is out of bounds: [0-1452587["
        }
      }
    ]
  },
  "status": 500
}
```

Playing with the `range` query, it turns our that this works for some values of `gte`, and not for others. 
In my case, the query above (currently) works for, e.g., `"gte": "2020-01-14T00:00:00"`.

I am on Elastic Cloud and was unable to find additional logs. Please let me know which other information you need and how I can obtain it.

### PR DESCRIPTION
**Pull request by nik9000**
When the `rare_terms` aggregation contained another aggregation it'd
break them. Most of the time. This happened because the process that it
uses to remove buckets that turn out not to be rare was incorrectly
merging results from multiple leaves. This'd cause array index out of
bounds issues. We didn't catch it in the test because the issue doesn't
happen on the very first bucket. And the tests generated data in such a
way that the first bucket always contained the rare terms. Randomizing
the order of the generated data fixed the test so it caught the issue.

Closes #51020

### CODE REVIEW

**Comment by nik9000** [comment]
The bwc test failure is because I haven't backported the fix. I'll suppress it.

**Review by polyfractal — APPROVED** [review]
Sneaky sneaky!  Thanks for tracking this down! :heart:

**Comment by fkelbert** [comment]
Thanks for taking care of this this quickly!

**Comment by nik9000** [comment]
I'm finished backporting but I'm leaving the `backport pending` tag on this until I can fix the skips in the BWC tests. That should be later this afternoon.

**Comment by nik9000** [comment]
> I'm finished backporting but I'm leaving the `backport pending` tag on this until I can fix the skips in the BWC tests. That should be later this afternoon.

All Don!

**Pull request merged**
