### PR TITLE
Plugins: Remove support for onModule

### PR DESCRIPTION
**Pull request by rjernst**
All plugin extension points have been converted to pull based
interfaces. This change removes the infrastructure for the black-magic
onModule methods.

### CODE REVIEW

**Comment by clintongormley** [comment]
w00t.  Do we need breaking java changes in the docs?

**Comment by nik9000** [comment]
> w00t. Do we need breaking java changes in the docs?

Yes.

**Comment by rjernst** [comment]
Regarding the breaking changes, since this will go back to 5.1, should it just go into the backport since there are no 5.1 breaking changes in master?

**Comment by jasontedor** [comment]
> Regarding the breaking changes, since this will go back to 5.1, should it just go into the backport since there are no 5.1 breaking changes in master?

That's exactly how I handle these sorts of things.

**Comment by s1monw** [comment]
hell yeah!

**Comment by rjernst** [comment]
retest this please

**Comment by rjernst** [comment]
@nik9000 @jasontedor @s1monw Do you have any technical comments on this PR or is it just needing the breaking changes docs when backported?

**Comment by jasontedor** [comment]
> Do you have any technical comments on this PR or is it just needing the breaking changes docs when backported?

Just that, the PR looks good to me. I'll leave a formal LGTM.

**Review by jasontedor — APPROVED** [review]
LGTM.

**Review by nik9000 — APPROVED** [review]
Same here. Change looks fine.

**Comment by rjernst** [comment]
With the backport to 5.x, I pushed 2162a6d with a breaking changes note. /cc @clintongormley

**Comment by clintongormley** [comment]
thanks @rjernst

**Pull request merged**
