### PR TITLE
Updating the transport CA name

### LINKED ISSUE #106455: Security Auto-Configuration: Transport CA is named "HTTP CA"
In security auto configuration we generate separate CAs for transport & HTTP
But they have the same name: `CN=Elasticsearch security auto-configuration HTTP CA`
- https://github.com/elastic/elasticsearch/blob/b7eafce32cb1e7dfdcb259aab89b886ff93a1c66/x-pack/plugin/security/cli/src/main/java/org/elasticsearch/xpack/security/cli/AutoConfigureNode.java#L117

The transport CA should be named `CN=Elasticsearch security auto-configuration transport CA` (or something like that)

### PR DESCRIPTION
**Pull request by adityakukankar**
Updated the transport CA in Security Auto-Configuration.

Closes #106455

### CODE REVIEW

**Comment by tvernum** [comment]
@elasticmachine test this please 🙏

**Comment by adityakukankar** [comment]
@tvernum the changelog validation was failing I corrected it (updated area to Security). Correct me if I am wrong. 
Please can you rerun the builds.

**Comment by tvernum** [comment]
@elasticmachine test this please 🙏

**Comment by tvernum** [comment]
This looks good, but we need to add tests.

If it were me, I would add the tests in `AutoConfigureNodeTests`. I would add a method `testSubjectandIssuerForGeneratedCertificates()` that looks like the first block (`// test no publish settings`) from `testGeneratedHTTPCertificateSANs`

To do that we'll need to add a new method derived from `runAutoConfigAndReturnHTTPCertificate` like `Tuple<X509Certificate, X509Certificate> runAutoConfigAndReturnCertificates()` that can return both HTTP and transport certificates.

The existing `runAutoConfigAndReturnHTTPCertificate` method can delegate to the new `runAutoConfigAndReturnCertificates` method, and just return `v1()` (the http cert).

Then you want to check that the subject and issuer identities of each certificate match what we expect.

Are you able to do that, or do you need one of us to pick it up?

**Comment by adityakukankar** [comment]
@tvernum Thanks for explanation. I have added a test case. Please review and let me know if it is in the right direction like you described.

**Comment by tvernum** [comment]
Sorry, @adityakukankar I missed your previous comment.

Your updated changes look good to me.

**Comment by tvernum** [comment]
@elasticsearchmachine test this please

**Comment by tvernum** [comment]
@elasticmachine update branch

**Comment by tvernum** [comment]
@elasticmachine test this please

**Comment by tvernum** [comment]
@elasticmachine test this please

**Review by albertzaharovits — APPROVED** [review]
LGTM

**Pull request merged**
