### PR TITLE
Fix the SQL API documentation in REST specification

### PR DESCRIPTION
**Pull request by karmi**
This patch fixes the SQL REST API documentation to conform to the current schema.

### CODE REVIEW

**Review by costin — APPROVED** [review]
Děkuji! - LGTM

P.S. Not sure what's with the license compliance check.

**Comment by karmi** [comment]
Cu plăcere! :) Not sure about the FOSSA check either, this patch shouldn't introduce any new issues anyway...

I'm not sure what's the merging strategy right now, but it would be nice to merge this patch to `7.x` branch as well — do you know what's the preferred way of doing that?

**Comment by costin** [comment]
I'm not sure either - for large/complicated commits I create a separated PR; for small ones (like this) I simply cherry-pick and push to 7.x after testing locally with a message that refers to the initial commit (so it gets picked by Github as well).

**Comment by costin** [comment]
@karmi anything preventing this PR from being merged? Is it the license check - I think we can ask infra or simply ignore it.

**Comment by karmi** [comment]
No, sorry, @costin, I did the patch during a week of giving trainings and it got more hectic afterwards. I'll merge today or tomorrow.

**Pull request merged**
