### PR TITLE
Rename _audit.log to _audit.json

### PR DESCRIPTION
**Pull request by pgomulka**
As a follow up from [discussion comment](https://github.com/elastic/elasticsearch/issues/32850#issuecomment-458064462)
in order to keep json logs consistent the security aduit logs are renamed from `.log` to `.json`

relates #32850

### CODE REVIEW

**Comment by albertzaharovits** [comment]
@ycombinator what do you think, is this necessary for consistency from the ingest perspective?
It's not clear for me from https://github.com/elastic/elasticsearch/issues/32850#issuecomment-458066346 that it is.

**Comment by ycombinator** [comment]
Strictly speaking, it's not **necessary** from an Ingest perspective as Filebeat can uniquely target `audit.log` as the new, JSON-formatted audit log file. However, from a consistency perspective, it would definitely be very nice if all Elasticsearch logs that emitted JSON entries had `.json` as their extension. So I'm +1 for this change.

**Comment by albertzaharovits** [comment]
Understood, thank you @ycombinator for the input!

**Comment by pgomulka** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by pgomulka** [comment]
@elasticmachine  run elasticsearch-ci/default-distro

**Comment by albertzaharovits** [comment]
Thank you for tackling this one too @pgomulka !

I am OK with the change. I vaguely remember some qa sql tests parsing the audit log so you might encounter some CI failures. In addition I think a breaking change notice is in order. I am not quite sure where to file it, but maybe @lcawl can help? I am thinking, `docs/reference/migration/migrate_7_0/cluster.asciidoc`.

**Review by albertzaharovits — APPROVED** [review]
LGTM

**Comment by pgomulka** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by pgomulka** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by pgomulka** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by pgomulka** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by pgomulka** [comment]
@elasticmachine run elasticsearch-ci/docs-check

**Pull request merged**
