### PR TITLE
Upgrade to lucene- 8.7.0-snapshot-66c49a35402

### PR DESCRIPTION
**Pull request by mayya-sharipova**
This includes fixing a bug in doc iteration during sort optimization

### CODE REVIEW

**Review by dnhatn — APPROVED** [review]
LGTM

**Comment by mayya-sharipova** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by mayya-sharipova** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by mayya-sharipova** [comment]
@elasticmachine update branch

**Comment by mayya-sharipova** [comment]
@elasticmachine update branch

**Comment by mayya-sharipova** [comment]
@elasticmachine run elasticsearch-ci/2

**Pull request merged**
