### PR TITLE
Small code cleanups and refactorings in persistent tasks

### PR DESCRIPTION
**Pull request by tlrx**
This commit consists of small code cleanups and refactorings in the persistent tasks framework. Most changes are in `PersistentTasksClusterService` where some methods have been renamed
or merged together, documentation has been added, and unused code removed in order to (hopefully) improve the readability and testability of the code.

### CODE REVIEW

**Review by imotov — APPROVED** [review]
LGTM

**Comment by tlrx** [comment]
@elasticmachine retest this please

**Comment by tlrx** [comment]
Thanks @imotov !

**Comment by tlrx** [comment]
I backported this to 6.x in a8494252182696fd1cfe0aa2028161e62a588278

**Pull request merged**
