### PR TITLE
Remove unused class MemoryCircuitBreaker

### PR DESCRIPTION
**Pull request by danielmitterdorfer**
The class `MemoryCircuitBreaker` is unused so we remove all its traces
from the code base.

### CODE REVIEW

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by danielmitterdorfer** [comment]
Thanks for the quick review. :)

**Comment by danielmitterdorfer** [comment]
@elasticmachine retest this please

**Comment by danielmitterdorfer** [comment]
Backported to 6.x in a064fd051e07d3004769ae4a7ac4a5fc7de1b0f0.

**Pull request merged**
