### PR TITLE
Add a setting which specifies a list of setting

### PR DESCRIPTION
**Pull request by jimczi**
This change adds a new setting called `listGroup` setting:
 * A setting which specifies a list of settings.

For instance:
````
"foo.bar": [{"value": 10, "another":4}, {"value": 9, "another", 12}]
````

### CODE REVIEW

**Comment by s1monw** [comment]
what is the exact usecase for this?

**Comment by jimczi** [comment]
I want to use it for the index sorting setting (#6720) :
````
"index.sort": [ {"field": "timestamp", "order": "asc"}, {"field": "another_field", "order": "desc", "mode": "max"}]
`````

I could use the listSetting directly but I don't want to introduce a weird parsing like:
````
"index.sort": [ "timestamp:asc", "another_field:desc:max"]
`````

**Comment by s1monw** [comment]
ok thanks I will take a look

**Comment by s1monw** [comment]
I thought about this and I wonder if we should use an affix setting for this rather than this construct, something like this:

```Java

Setting.affixKeySetting("index.sort.",
        "order", (key) -> (key) -> Setting.simpleString(key, Setting.Property.IndexScope),
            Setting.Property.IndexScope));
Setting.affixKeySetting("index.sort.",
        "mode", (key) -> (key) -> Setting.simpleString(key, Setting.Property.IndexScope),
            Setting.Property.IndexScope));
```

that way we can use the fieldname in the settings name and use existing infra? I also like that we can instead of `Setting.simpleString(key, Setting.Property.IndexScope)` we can add a real setting that validates stuff etc. and gives good error messages. WDYT?

**Comment by jimczi** [comment]
We chatted with @s1monw and decided that to keep the things simple and consistent we could use an array of simple strings for each sort setting. So something like:
`````
"index.sort.field": ["timestamp", "another_field"],
"index.sort.order": ["desc", "asc],
"index.sort.mode": ["max", "min"] 
`````
This way we just have to validate that each array have the same size and combine the specs together for each field.
This doesn't require anything more in the existing infra so I'll close this PR.

**Comment by Mpdreamz** [comment]
I was going to reply indicating I was not a fan of the positionally relational settings but it seems as per discussion on https://github.com/elastic/elasticsearch/pull/24055 that the long term plan is to move this to index mappings when types get removed. (for future googlers having the same kneejerk reaction as me :))

**Pull request closed without merging**
