### PR TITLE
Remove Redundant Version Param from Repository APIs

### PR DESCRIPTION
**Pull request by original-brownbear**
This parameter isn't used by any implementation

### CODE REVIEW

**Comment by original-brownbear** [comment]
Jenkins test this

**Comment by original-brownbear** [comment]
Jenkins test this

**Comment by original-brownbear** [comment]
Jenkins test this

**Comment by original-brownbear** [comment]
@elasticmachine update branch

**Review by tlrx — APPROVED** [review]
LGTM, thanks Armin

**Comment by original-brownbear** [comment]
Thanks Tanguy!

**Pull request merged**
