### PR TITLE
Modifying EC2 policy to allow cluster node lookup via tags, etc, ...

### PR DESCRIPTION
**Pull request by owenrh**
See title.

### CODE REVIEW

**Comment by dadoonet** [comment]
Do you mean that it needs other API accesses than `DescribeInstances`? Can you tell which ones exactly are needed?

**Comment by owenrh** [comment]
Hi @dadoonet,

Yeah, it needs more privileges. I think it maybe DescribeInstanceAttributes, to access instance tags. I'll try and verify this later.

**Comment by rjernst** [comment]
I think we should be explicit. If we need DescribeInstances and DescribeInstanceAttributes, let's list both of those in the example, instead of relying on wildcards (which may grant more permissions than necessary).

**Comment by DaveCTurner** [comment]
I think this is unnecessary. Elasticsearch adds a tag filter to the `DescribeInstances` call, and also checks the tags that are returned in the response. I do not see that it makes a subsequent call to `DescribeInstanceAttributes` to check its tags. The only other matching API call is presently `DescribeInstanceStatus` which, again, I do not think Elasticsearch calls.

(Also if this were really needed then I think we would have seen more noise on this issue since it was opened).

**Pull request closed without merging**
