### PR TITLE
Update zen.asciidoc

### PR DESCRIPTION
**Pull request by achilles42**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?

### CODE REVIEW

**Comment by abeyad** [comment]
@shukla-praveen thank you for the pull request!  It looks good, could I ask that you sign the CLA so I can merge it?

**Comment by shukla-praveen** [comment]
@abeyad I have signed the CLA, thanks

**Comment by abeyad** [comment]
thanks @shukla-praveen

**Comment by abeyad** [comment]
master: 2e18f2e8181691eaaa0dffce090dac56c0acd22c
5.x: 96e28e7a06620e3f77d1cd249303d2269b8a3641

**Comment by jasontedor** [comment]
Thanks for integrating this @abeyad; I think this should go to the 5.0 branch too (with a 5.0.1 label).

**Comment by abeyad** [comment]
5.0 commit: 2769c9effa15be22583fb49eb65b7c30ad2c109a

thanks @jasontedor

**Pull request merged**
