### PR TITLE
Add SimpleBatchedAckListenerTaskExecutor

### PR DESCRIPTION
**Pull request by pxsalehi**
A followup to https://github.com/elastic/elasticsearch/pull/90343 for cluster state update tasks that implement `ClusterStateAckListener` (see https://github.com/elastic/elasticsearch/pull/90343#issuecomment-1260638634).

### CODE REVIEW

**Comment by pxsalehi** [comment]
@elasticmachine update branch

**Comment by pxsalehi** [comment]
I could have also changed [this executor](https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/cluster/metadata/MetadataUpdateSettingsService.java#L73), but it seems that `UpdateSettingsTask` has been intentionally changed to not directly implement the `ClusterStateAckListener` (see https://github.com/elastic/elasticsearch/commit/7f2331cdfb08fcd69f1f896b0d41c1b395ca9919). Not sure why though!

**Comment by DaveCTurner** [comment]
Also all the ones in `AutoCreateAction` use a separate `ClusterStateAckListener`. I think I prefer that pattern, it basically creates a channel for the executor to pass information to the final listener. In the case of `AutoCreateAction`, we use it to pass the index name along.

I think that `execute` should return a `Tuple<ClusterState, ClusterStateAckListener>` to enable this.

**Comment by DaveCTurner** [comment]
Just realised that the `AutoCreateAction` ones don't fit this framework because they accumulate the `successfulRequests` map. Not to worry - I still think the idea of returning a `Tuple<ClusterState, ClusterStateAckListener>` is a good one.

**Comment by pxsalehi** [comment]
@DaveCTurner Thanks for the feedback! Please have another look.

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Pull request merged**
