### PR TITLE
[test] add mapper attachments plugin to vagrant tests

### PR DESCRIPTION
**Pull request by brwe**

### CODE REVIEW

**Comment by dadoonet** [comment]
++ thanks @brwe !
LGTM

**Comment by dadoonet** [comment]
Wondering if that is needed for master branch as well? Or already done?

**Comment by rmuir** [comment]
I missed it on backport: master actually does have it in its vagrant tests.

**Comment by rmuir** [comment]
These were added in https://github.com/elastic/elasticsearch/commit/9b0a47d8e315a7bcd41606977278ead9a485581d, thanks for fixing this in 2.x

**Pull request merged**
