### PR TITLE
[DOCS] Fix typo in adapt auto expand replica comments

### PR DESCRIPTION
**Pull request by howardhuanghua**
The original comment has typo also it's hard to understand. Fix typo and optimize the comment.

### CODE REVIEW

**Comment by matriv** [comment]
The proposed change doesn't seem syntactically correct to me, as opposed the current version.

**Comment by howardhuanghua** [comment]
Hi @matriv , I am going to fix the typo only. Please help to check again. Thanks.

**Review by jrodewig — APPROVED** [review]
LGTM. Thanks @howardhuanghua

**Comment by jrodewig** [comment]
@elasticmachine test this please

**Pull request merged**
