### PR TITLE
Added fields for MultiTermVectors (#42232)

### LINKED ISSUE #42232: MTermVector Java High Level Client Misses Fields Property
elasticsearch-rest-high-level-client - 7.0.1

Expected vs Actual Behaviour AND steps to reproduce:

1. Create a MultiTermVectorsRequest and add a single TermVectorsRequest WITH a field. 

```
MultiTermVectorsRequest termVectorsRequest = new MultiTermVectorsRequest();

TermVectorsRequest textRequest = new TermVectorsRequest("index", "id");
textRequest.setFields("text");
textRequest.setTermStatistics(true);
textRequest.setFieldStatistics(false);
textRequest.setPositions(false);
textRequest.setOffsets(false);
termVectorsRequest.add(textRequest);

MultiTermVectorsResponse mtermvectors = client.mtermvectors(termVectorsRequest, RequestOptions.DEFAULT);

```

2. When sending to the Java High Level Client, after transformation to low-level REST client format, the fields property is missing! 

When converting to the low-level REST request in internalPerformRequest() within RestHighLevelClient.java it can be inspected that the body of the request will be the following:

```
{
    "docs": [
        {
            "_index": "index",
            "_id": "id",
            "positions": false,
            "offsets": false,
            "field_statistics": false,
            "term_statistics": true
        }
    ]
}
```

Then this is sent to the server. 

3. The elastic search will return no term vectors, since no field was given. And this renders the High Level Java Client useless for multiple term vector retrieval.

### PR DESCRIPTION
**Pull request by ojasgulati**
Fixes #42232

### CODE REVIEW

**Comment by gwbrown** [comment]
@elasticmachine test this please

It looks like this bug happened because the single termvectors API can take the list of fields as a URL parameter, as an alternative to the fields list in the body, and [the URL parameter method is how the HLRC implements the single termvectors API](https://github.com/elastic/elasticsearch/blob/17581f2f6f52369b93d15fa534ce9c1fa6d0846a/client/rest-high-level/src/main/java/org/elasticsearch/client/RequestConverters.java#L689), but the multi termvectors API can only take the list of fields in the body. This change, as is, will result in the HLRC putting the fields list in both the URL parameters and the request body - I'm not sure if that will cause a problem or not, we may see some failing tests.

We may end up having to change the HLRC implementation of the single termvectors API to *not* use the URL parameters since they will now show up in the body.  If that's the case, we'll have to adjust [this test case](https://github.com/elastic/elasticsearch/blob/a6b5aaa3b466cf4204b80f225787504320f4ed40/client/rest-high-level/src/test/java/org/elasticsearch/client/RequestConvertersTests.java#L1437-L1475) as well.

@mayya-sharipova I'm not very familiar with the term vectors API, is there a reason we decided to have the HLRC put the fields list as a URL parameter rather than in the body?

**Comment by mayya-sharipova** [comment]
@ojasgulati  @gwbrown  Sorry for a late reply. There is no any particular reason to have fields list as a URL parameter, and we can move them into the the body and fix the tests.

**Review by mayya-sharipova — CHANGES_REQUESTED** [review]
@ojasgulati Thanks for submitting a PR. We may need to do several more things here that @gwbrown  pointed out:

-  We don't need  URL parameter of `params.withFields(tvrequest.getFields());` in [here](https://github.com/elastic/elasticsearch/blob/master/client/rest-high-level/src/main/java/org/elasticsearch/client/RequestConverters.java#L689) as we now will pass `fields` in the body
-  We will need to fix the [test](https://github.com/elastic/elasticsearch/blob/a6b5aaa3b466cf4204b80f225787504320f4ed40/client/rest-high-level/src/test/java/org/elasticsearch/client/RequestConvertersTests.java#L1437-L1475) pointed out by @gwbrown to remove all mentions of `fields` parameter
-  Add a test to test that MultiTermVectors indeed work well `fields`.  We can enhance `CrudIT::testMultiTermvectors` for this.

**Comment by ojasgulati** [comment]
@mayya-sharipova Thank you for your reply. I will make changes as you described in your comment.

**Comment by gwbrown** [comment]
@ojasgulati Are you still planning to work on this?

**Comment by gwbrown** [comment]
Given that this hasn't seen any activity for quite a while, I'm going to close this PR. Feel free to reopen this one or open a new one if you want to continue working on this.

**Pull request closed without merging**
