### PR TITLE
Replaced the word 'shards' with 'replicas' in an error message. (#36234)

### PR DESCRIPTION
**Pull request by AlexisWilke**
See #36234 for details.

Fixing a message making a reference to _shards_ instead of _replicas_.

### CODE REVIEW

**Comment by original-brownbear** [comment]
@elasticmachine test this please

**Comment by original-brownbear** [comment]
@AlexisWilke could you please merge `elastic:master` into your branch so we can run tests?
Thanks!

**Comment by javanna** [comment]
retest this please

**Comment by javanna** [comment]
retest this please

**Comment by AlexisWilke** [comment]
I guess that test doesn't work on Dec 31st?

> 18:03:50 FAILURE 0.07s | JdbcSqlSpecIT.test {datetime.testCurrentTimestampYear} <<< FAILURES!

Maybe wait another day and try again...

**Comment by original-brownbear** [comment]
Jenkins run gradle build tests 2

**Review by original-brownbear — APPROVED** [review]
LGTM, thansk @AlexisWilke

**Pull request merged**
