### PR TITLE
Adjust randomization in cluster shard limit tests

### LINKED ISSUE #47107: ClusterShardLimitIT.testIndexCreationOverLimitFromTemplate failing
fails regularly on all active branches

```
junit.framework.AssertionFailedError: Expected exception IllegalArgumentException but no exception was thrown
        at __randomizedtesting.SeedInfo.seed([62DFAF52204E17E9:D84223E9F73D64A2]:0)
        at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2726)
        at org.apache.lucene.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2711)
        at org.elasticsearch.cluster.shards.ClusterShardLimitIT.testIndexCreationOverLimitFromTemplate(ClusterShardLimitIT.java:144)
REPRODUCE WITH: ./gradlew ':server:integTest' --tests "org.elasticsearch.cluster.shards.ClusterShardLimitIT.testIndexCreationOverLimitFromTemplate" -Dtests.seed=62DFAF52204E17E9 -Dtests.security.manager=true -Dtests.locale=ar-YE -Dtests.timezone=America/El_Salvador -Dcompiler.java=12 -Druntime.java=8
```

Build scan: https://gradle-enterprise.elastic.co/s/cotrw72nsi35q

### PR DESCRIPTION
**Pull request by AthenaEryma**
This commit adjusts randomization for the cluster shard limit tests so
that there is often more of a gap left between the limit and the size of
the first index. This allows the same randomization to be used for all
tests, and alleviates flakiness in
`testIndexCreationOverLimitFromTemplate`.

Fixes https://github.com/elastic/elasticsearch/issues/47107

### CODE REVIEW

**Review by danhermann — APPROVED** [review]
LGTM pending successful CI

**Comment by gwbrown** [comment]
@elasticmachine update branch

**Comment by gwbrown** [comment]
Failure is https://github.com/elastic/elasticsearch/issues/47275

@elasticmachine run elasticsearch-ci/2

**Comment by gwbrown** [comment]
@elasticmachine update branch

**Comment by gwbrown** [comment]
Updating because `master` now contains mutes for the (related to this change) failing tests.

**Pull request merged**
