### PR TITLE
[DOCS] Intro for adding nodes

### PR DESCRIPTION
**Pull request by lcawl**
This PR adds an introductory "Adding nodes to your cluster" page in the Elasticsearch Reference under "Set up Elasticsearch". 

It contains content that was developed in https://github.com/elastic/stack-docs/pull/164, since we needed to add multiple nodes to demonstrate a successful TLS security setup.

Finer details about how to add nodes in various development/production environments will be added in subsequent PRs, though they'll differ by version. The final link in this introduction also needs to be omitted when it's backported.

Also related to https://github.com/elastic/elasticsearch/pull/34714/files#r243128799

### CODE REVIEW

**Comment by lcawl** [comment]
You can preview this content here: https://doc-review-63bf6.firebaseapp.com/es3/add-elasticsearch-nodes.html

**Review by DaveCTurner — COMMENTED** [review]
Nice diagrams!

However I feel that the content here would fit better in the `Getting Started -> Basic Concepts` section: most of the other pages under `Set up Elasticsearch` are less explanatory than this one. However I see that you plan followup PRs too, so maybe I'm just missing the bigger picture. Could you combine this with some of the followup work?

**Comment by lcawl** [comment]
Thanks, the diagrams are pilfered from ye old Definitive Guide. 

I actually considered putting this under the "Getting Started", then decided it would be nice to have something essentially equivalent to the "Installing Elasticsearch" task (https://www.elastic.co/guide/en/elasticsearch/reference/master/install-elasticsearch.html).  i.e. This high-level page would be followed by detailed sub-pages that contain specific instructions for adding nodes via diverse methods (e.g. depending on which installation package you're using and whether you're adding them in production or development mode, etc).  The TLS tutorial I referenced only covers adding nodes via targz on the same machine, but I would like to be able to refer people to instructions for other methods.

**Comment by debadair** [comment]
I agree with not burying this in the Getting Started section, but I think we should tweak the content slightly before merging.

**Review by debadair — CHANGES_REQUESTED** [review]

**Comment by lcawl** [comment]
Thanks, @debadair !  I've refreshed the preview on https://doc-review-63bf6.firebaseapp.com/es3/add-elasticsearch-nodes.html

**Review by debadair — APPROVED** [review]
Thanks for the changes @lcawl! Looking at this again, I think it would be worth providing a little more context for the diagrams. (You had that before, my suggested changes lost that.)

**Comment by lcawl** [comment]
Thanks, @debadair I've implemented those changes and refreshed the preview.

**Pull request merged**
