### PR TITLE
[DOCS] Update saml acs with new URL

### PR DESCRIPTION
**Pull request by lockewritesdocs**
Removes the skipped tests from #77038 and updates `build.gradle` with the new 'xpack.security.authc.realms.saml.saml1.sp.acs' URL.

### CODE REVIEW

**Comment by jkakavas** [comment]
let's also fix https://github.com/elastic/elasticsearch/pull/77038/files#diff-3c61752c92cdf941a98a67fb49a65d08a61efe20009bdd4bba8ad229278f7d6eR55

**Comment by lockewritesdocs** [comment]
> https://github.com/elastic/elasticsearch/pull/77038/files#diff-3c61752c92cdf941a98a67fb49a65d08a61efe20009bdd4bba8ad229278f7d6eR55

@jkakavas, what are you wanting to fix in that file? None of the tests were skipped as part of the changes in #77038. Are you suggesting that we uncomment the skipped tests like [this one](https://github.com/lockewritesdocs/elasticsearch/blame/0299a5bc341587b74328b54b23399d237c75a095/x-pack/docs/en/security/authentication/saml-guide.asciidoc#L964)?

**Comment by jkakavas** [comment]
> > https://github.com/elastic/elasticsearch/pull/77038/files#diff-3c61752c92cdf941a98a67fb49a65d08a61efe20009bdd4bba8ad229278f7d6eR55
> 
> @jkakavas, what are you wanting to fix in that file? None of the tests were skipped as part of the changes in #77038. Are you suggesting that we uncomment the skipped tests like [this one](https://github.com/lockewritesdocs/elasticsearch/blame/0299a5bc341587b74328b54b23399d237c75a095/x-pack/docs/en/security/authentication/saml-guide.asciidoc#L964)?

https://github.com/elastic/elasticsearch/pull/77038/files#diff-3c61752c92cdf941a98a67fb49a65d08a61efe20009bdd4bba8ad229278f7d6eR55 is actually a link to a line that you added in 77038 that mutes a doc test in x-pack/docs/en/rest-api/security/saml-sp-metadata.asciidoc

**Comment by lockewritesdocs** [comment]
> https://github.com/elastic/elasticsearch/pull/77038/files#diff-3c61752c92cdf941a98a67fb49a65d08a61efe20009bdd4bba8ad229278f7d6eR55 is actually a link to a line that you added in 77038 that mutes a doc test in x-pack/docs/en/rest-api/security/saml-sp-metadata.asciidoc

Got it! Thanks for clarifying. The link just opened the _entire_ diff, so I wasn't sure what you meant. I'll fix now 👍

**Comment by lockewritesdocs** [comment]
@jkakavas, I think we're good to merge now. Just wanted you to give a 👍 before merging and backporting.

**Review by jkakavas — APPROVED** [review]
LGTM, thanks for the ping!

**Pull request merged**
