### PR TITLE
Adding missing json spec for allow_partial_search_results in point-in-time

### PR DESCRIPTION
**Pull request by pmpailis**
In https://github.com/elastic/elasticsearch/pull/111516 we introduced the `allow_partial_search_results` for when creating a point-in-time, but the json spec was not updated properly.

### CODE REVIEW

**Comment by pmpailis** [comment]
@elasticmachine update branch

**Comment by pmpailis** [comment]
@elasticmachine update branch

**Comment by pmpailis** [comment]
@elasticmachine update branch

**Review by javanna — APPROVED** [review]

**Comment by pmpailis** [comment]
@elasticmachine update branch

**Comment by pmpailis** [comment]
@elasticmachine update branch

**Pull request merged**
