### PR TITLE
Fix superclass functional interface resolution in Painless

### PR DESCRIPTION
**Pull request by jdconrad**
A recent change [1] to how we load our allow list changed the resolution for how Painless looks up methods of super classes. However, functional interface loading was not changed which caused a bug where a functional interface would not look at its super interfaces for the functional interface method [2].

This fixes the issue by going through each super interface until the functional interface method is found when the target interface doesn't have the functional interface method.

[1] https://github.com/elastic/elasticsearch/pull/76955
[2] https://github.com/elastic/elasticsearch/issues/81696

### CODE REVIEW

**Comment by jdconrad** [comment]
@elasticmachine run elasticsearch-ci/docs-check

**Comment by jdconrad** [comment]
@elasticmachine run elasticsearch-ci/part-1

**Comment by jdconrad** [comment]
@elasticmachine run elasticsearch-ci/part-1

**Comment by jdconrad** [comment]
@elasticmachine run elasticsearch-ci/docs-check

**Review by stu-elastic — APPROVED** [review]
Can you add the following test?
```java
    public void testUnaryOperator() {
        assertEquals("doremi", exec("List lst = ['abc', '123']; lst.replaceAll(f -> f.replace('abc', 'doremi')); lst.get(0);"));
        assertEquals("doremi", exec("def lst = ['abc', '123']; lst.replaceAll(f -> f.replace('abc', 'doremi')); lst.get(0);"));
    }
```

Can you thank @megglos and @TheFireCookie in the commit message?

We'll also have to write up a Known issues section in the [7.16 release notes](https://github.com/elastic/elasticsearch/blob/7.16/docs/reference/release-notes/7.16.asciidoc)

**Pull request merged**
