### PR TITLE
Don't Start Redundant ConsistentSettingsService

### PR DESCRIPTION
**Pull request by original-brownbear**
The consistent settings service is only used in tests so far. No need to start it
unless it's actually used. Also, as a result of this many clusters will never use
the `LocalNodeMasterListeners` so only add it if necessary (SLM, Enrich-Processor etc.).

### CODE REVIEW

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/packaging-sample-windows

**Review by albertzaharovits — APPROVED** [review]
LGTM

**Review by jaymode — COMMENTED** [review]
I opened an alternative for the `LocalNodeMasterListeners` aspect of this PR in #62422

**Comment by original-brownbear** [comment]
@jaymode I like your version -> backed that part of the change out of this PR :)

**Comment by original-brownbear** [comment]
Merging the non-starting of the consistent settings service here and leaving cleaning up the master change listeners to Jay's PR that handles it cleaner :)

Thanks Albert + Jay!

**Pull request merged**
