### PR TITLE
Move AnnotationTestObject to test package

### PR DESCRIPTION
**Pull request by jdconrad**
An extraneous test class was part of the spi core package. This change moves it to the test package. Also fixes a typo.

### CODE REVIEW

**Review by stu-elastic — APPROVED** [review]
lgtm once CI passes

**Comment by jdconrad** [comment]
@stu-elastic Thanks! Will commit as soon as CI passes.

**Comment by jdconrad** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by jdconrad** [comment]
@elasticsearchmachine run elasticsearch-ci/packaging-tests-windows-sample

**Pull request merged**
