### PR TITLE
Deprecate transport profile security type setting

### PR DESCRIPTION
**Pull request by jaymode**
This commit deprecates the `transport.profiles.*.xpack.security.type`
setting. This setting is used to configure a profile that would only
allow client actions. With the upcoming removal of the transport client
the setting should also be deprecated so that it may be removed in
a future version.

### CODE REVIEW

**Comment by jaymode** [comment]
@elasticmachine run elasticsearch-ci/1

**Review by tvernum — APPROVED** [review]
LGTM

**Review by jkakavas — APPROVED** [review]
LGTM

**Comment by tvernum** [comment]
@elasticmachine update branch

**Pull request merged**
