### PR TITLE
Remove unneeded test PreventFailingBuildIT

### PR DESCRIPTION
**Pull request by davidkyle**
Ironically `PreventFailingBuildIT.testSoThatTestsDoNotFail` is causing failures as documented in #52197. The test looks like it was added when the other tests in the suite were muted and then forgotten about it can now be removed.

### CODE REVIEW

**Comment by davidkyle** [comment]
Pinging @elastic/es-core-features can I get a review please. The empty test is still causing failures in #52197

**Review by martijnvg — APPROVED** [review]
LGTM

**Comment by martijnvg** [comment]
I think it can be removed in master too.

**Comment by davidkyle** [comment]
Thanks @martijnvg I will remove it from master also.

**Pull request merged**
