### PR TITLE
Backport #21830 to 5.x

### PR DESCRIPTION
**Pull request by s1monw**
This is a pretty straight forward backport of #21830 to 5.x but it changes some behavior in BWC. 
In 5.x we tested BWC against 2.0.0-RC and it's betas but in master we don't allow this anymore, we only guarantee BWC to GA releases. We also do this for 5.0, 5.0.0-RC1 is not in the list of indices we support. Note: with this PR we actively reject these indices when we see on index / snapshot etc. when we upgrade...

To discuss this change I opened this PR just make everybody aware of this change and with the question if we should do it that way.

### CODE REVIEW

**Comment by rjernst** [comment]
+1 to the behavior change, I think prereleases should not be a viable upgrade path.

**Comment by jpountz** [comment]
+1 too

**Comment by s1monw** [comment]
I will merge this in the next 60 min unless anybody objects

**Review by bleskes — APPROVED** [review]
LGTM. For completeness - we decided to special case 2.0.0 pre-releases because not doing so would mean that a running 5.0 cluster may not accept joins from a 5.1 preventing rolling upgrades. We thought we are better off special casing it in the 5.x series and fully enforce from 6.0 onwards.

**Comment by s1monw** [comment]
> For completeness - we decided to special case 2.0.0 pre-releases because not doing so would mean that a running 5.0 cluster may not accept joins from a 5.1 preventing rolling upgrades. We thought we are better off special cases it in the 5.x series and fully enforce from 6.0 onwards.

👍

**Pull request merged**
