### PR TITLE
OpenIdConnectAuthIT's client uses certificate_authorities instead of trustore

### LINKED ISSUE #66879: OpenIdConnectAuthIT and SamlAuthenticationIT  should use a PEM trusted certificate
**Build scan**:
https://gradle-enterprise.elastic.co/s/gsk6sxygbkheg

**Repro line**:

**Reproduces locally?**: yes

**Applicable branches**: master, 7.x, 7.11

**Failure history**:

**Failure excerpt**:

These extend EsRestTestCase and should make use of CERTIFICATE_AUTHORITIES ( https://github.com/elastic/elasticsearch/pull/66559) when building the rest client they use so that they dont have to use a jks keystore which is not allowed in fips mode

### PR DESCRIPTION
**Pull request by albertzaharovits**
This PR makes it so that the test code of OpenIdConnectAuthIT can be run under our FIPS JVM setup.
In particular, the client's SSL context is built from certificate authorities from a crt file instead of from a trustore
from a JKS file.

@jkakavas Should we also ensure that the ES test fixture from the container is run in a JVM configured for FIPS? I assume we need to have a FIPS distribution first. But until then `OpenIdConnectAuthIT`  tests don't add coverage in the FIPS context, am I right?

Closes https://github.com/elastic/elasticsearch/issues/66879

### CODE REVIEW

**Comment by jkakavas** [comment]
Could you please also take care of the facilitator password? see my last comment in #66879

> @jkakavas Should we also ensure that the ES test fixture from the container is run in a JVM configured for FIPS?

Yes, good point. When we moved this to use docker and not testclusters we stopped running the cluster in fips mode. I think we can set es/jvm in fips mode even if we run the cluster with docker and I can take a swing at it Jan  follow up

**Review by jkakavas — APPROVED** [review]
LGTM

**Comment by albertzaharovits** [comment]
> I think we can set es/jvm in fips mode even if we run the cluster with docker and I can take a swing at it in a follow up

I'll leave it to you no problem! When gradle and docker work together they confuse me greatly.

**Review by ywangd — COMMENTED** [review]
LGTM.

I'd probably leave the usage of `.jks` file when the test is _not_ `inFipsJvm()` have a minor better coverage. It's not a big deal since what we are after right now is to have green FIPS runs. Thanks!

**Comment by ywangd** [comment]
I forgot to select "approve" when submitting the above review comment. Now the system does not show me the selection menu anymore even after I self-requested the review again ... The changes LGTM and please feel free to merge. Sorry for the inconvenience.

**Comment by ywangd** [comment]
Errr Just noticed it is already merged. I was blind ...

**Pull request merged**
