### PR TITLE
Remove duplicate disk.threshold_enabled setting.

### PR DESCRIPTION
**Pull request by howardhuanghua**
Remove duplicate disk.threshold_enabled setting for master doc.

### CODE REVIEW

**Comment by howardhuanghua** [comment]
Found same doc issue on 7.x https://github.com/elastic/elasticsearch/pull/62925 and 7.9 https://github.com/elastic/elasticsearch/pull/62926.

**Comment by howardhuanghua** [comment]
image

**Comment by howardhuanghua** [comment]
Hi @jrodewig, would you please help to check this simple dup line doc issue?

**Review by jrodewig — APPROVED** [review]
LGTM. Thanks for catching this @howardhuanghua.

**Comment by jrodewig** [comment]
@elasticmachine test this please

**Pull request merged**
