### PR TITLE
Add methods requiring connect to forbidden apis

### PR DESCRIPTION
**Pull request by Tim-Brooks**
This is related to #22116. This commit adds calls that require
`SocketPermission` `connect` to forbidden APIs.

The following calls are now forbidden:
- java.net.URL#openStream()
- java.net.Socket#connect(java.net.SocketAddress)
- java.net.Socket#connect(java.net.SocketAddress, int)
- java.nio.channels.SocketChannel#open(java.net.SocketAddress)
- java.nio.channels.SocketChannel#connect(java.net.SocketAddress)

### CODE REVIEW

**Review by s1monw — APPROVED** [review]
LGTM but `FileSystemUtils` didn't like it.. feel free to push once the build passes

**Comment by tbrooks8** [comment]
Hey @s1monw - yeah there were a few places where I missed `openStream()`. So I'll submit updates.

For the `FileSystemUtils` do you just want me to suppress forbidden? Another option is to not use URL (I think). Most of the `FileSystemUtils` methods deal with paths. And both callers of `newBufferedReader` originate with a `Path`.

I could change:

```
public static BufferedReader newBufferedReader(URL url, Charset cs) throws IOException {
    CharsetDecoder decoder = cs.newDecoder();
    Reader reader = new InputStreamReader(url.openStream(), decoder);
    return new BufferedReader(reader);
}
```

To:

```
public static BufferedReader newBufferedReader(Path path, Charset cs) throws IOException {
    return Files.newBufferedReader(path, cs);
}
```

Or not have that method and just call `Files.newBufferedReader(path, cs)`. But maybe I am missing a reason that we need to change these `Path` instances to `URL`? Or maybe there is a reason we don't want to use NIO in this case?

**Comment by s1monw** [comment]
> Or not have that method and just call Files.newBufferedReader(path, cs). 

++ just trash that method! good catch

**Comment by tbrooks8** [comment]
@s1monw can you give me an updated review based on my changes please?

**Comment by s1monw** [comment]
@elasticmachine test this please

**Comment by s1monw** [comment]
LGTM provided the tests pass

**Pull request merged**
