### PR TITLE
Aggregation support for Value Scripts that change types

### LINKED ISSUE #54655: Value Scripts that change the field type are broken
In #45395 we changed values source resolution to prioritize field type when we could, but this breaks the case where a user wants to use a value script to change the type of the underlying field, e.g. replacing a number with a string.

### PR DESCRIPTION
**Pull request by not-napoleon**
Resolves #54655 for post-refactor `ValuesSourceConfig`.  Will need a slightly different solution to backport to 7.7.x

### CODE REVIEW

**Comment by not-napoleon** [comment]
@elasticmachine run elasticsearch-ci/2

**Review by polyfractal — COMMENTED** [review]
Changes LGTM, but the test failure also looks real (NPE in stringstats "no matching docs" test), so it feels like we might be missing an edge-case here.  Or maybe just a broken test that is being exposed due to the change :)

**Comment by not-napoleon** [comment]
@polyfractal Neither, really.  I used an Intellij refactoring to pull the generic `TestCase` method we use in a lot of places up into the `AggregatorTestCase` base class, rather than copy it again, but I hadn't noticed that `StringStatsTests` had different behavior in its implementation.  I just pushed a fix that restores the old version of `testcase` in `StringStatsTests` with a TODO note to harmonize it with the base class version.

**Review by polyfractal — APPROVED** [review]
Ah yeah, we have a few of these hanging around, particularly older aggs.  I just converted Terms over to use the base class with a similar pattern, and it requires a bit of reworking some of the tests.

:+1:

**Comment by not-napoleon** [comment]
@elasticmachine update branch

**Comment by not-napoleon** [comment]
@elasticmachine update branch

**Comment by not-napoleon** [comment]
@elasticmachine update branch

**Comment by not-napoleon** [comment]
@elasticmachine update branch

**Comment by not-napoleon** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by not-napoleon** [comment]
@elasticmachine update branch

**Pull request merged**
