### PR TITLE
Fix auto_date_histogram interval

### LINKED ISSUE #56116: Interval value returned by auto_date_histogram is error
Version：
Elasticsearch：7.6.2
Kibana：7.6.2

```json
POST /kibana_sample_data_flights/_search?size=0
{
  "aggs": {
    "age_group": {
      "auto_date_histogram": {
        "field": "timestamp",
        "buckets": 10
      }
    }
  }
}
```

Return：

```
{
  "aggregations" : {
    "age_group" : {
      "buckets" : [
        {
          "key_as_string" : "2020-03-30T00:00:00.000Z",
          "key" : 1585526400000,
          "doc_count" : 2202
        },
        {
          "key_as_string" : "2020-04-06T00:00:00.000Z",
          "key" : 1586131200000,
          "doc_count" : 2177
        },
        {
          "key_as_string" : "2020-04-13T00:00:00.000Z",
          "key" : 1586736000000,
          "doc_count" : 2142
        },
        {
          "key_as_string" : "2020-04-20T00:00:00.000Z",
          "key" : 1587340800000,
          "doc_count" : 2187
        },
        {
          "key_as_string" : "2020-04-27T00:00:00.000Z",
          "key" : 1587945600000,
          "doc_count" : 2188
        },
        {
          "key_as_string" : "2020-05-04T00:00:00.000Z",
          "key" : 1588550400000,
          "doc_count" : 2163
        }
      ],
      "interval" : "1d"
    }
  }
}
```

I think the interval is 7d，why 1d？

### PR DESCRIPTION
**Pull request by nik9000**
`auto_date_histogram` was returning the incorrect `interval` because
of a combination of two things:
1. When pipeline aggregations rewrote `auto_date_histogram` we reset the
   interval to 1. Oops. Fixed that.
2. *Every* bucket aggregation was rewriting its buckets as though there
   was a pipeline aggregation even if there aren't any. This is a bit
   silly so we skip that too.

Closes #56116

### CODE REVIEW

**Review by talevy — APPROVED** [review]
change looks good. did I miss it, or should we add it -- a test with pipeline aggs nested in pipeline aggs so that we know this code still runs in a nested fashion? 

update: given https://github.com/elastic/elasticsearch/pull/56252#issuecomment-624362633, no need to worry about it

**Comment by nik9000** [comment]
> change looks good. did I miss it, or should we add it -- a test with pipeline aggs nested in pipeline aggs so that we know this code still runs in a nested fashion?

I don't believe pipeline aggs [can](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/search/aggregations/PipelineAggregationBuilder.java#L239-L242) have subaggregations.

**Comment by talevy** [comment]
thanks!

**Review by not-napoleon — APPROVED** [review]
Looks good to me too.  Nice catch.

**Comment by polyfractal** [comment]
> I don't believe pipeline aggs can have subaggregations.

Just confirming, pipelines (currently) cannot have sub-aggs.  It's theoretically possible but we havent encountered any reason to do so up to this point :)

**Pull request merged**
