### PR TITLE
Slm set operation mode to RUNNING on first run

### PR DESCRIPTION
**Pull request by andreidan**
Set the SLM operation mode to RUNNING when setting the first SLM lifecycle
policy. Historically, SLM was not decoupled from ILM but now they are
independent components. Setting the SLM operation mode to what the ILM running
mode was when we set the first SLM lifecycle policy was a remain from those
times.

### CODE REVIEW

**Comment by andreidan** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by andreidan** [comment]
@elasticmachine update branch

**Comment by jakelandis** [comment]
Changes look good. However, are there any tests that confirm that SLM can be in a running state without ILM ?

**Comment by andreidan** [comment]
@elasticmachine update branch

**Comment by andreidan** [comment]
@jakelandis we didn't have any tests on this operation mode and I initially thought it's not really worth the costs that come along with an integration test but I added one

**Comment by andreidan** [comment]
@elasticmachine update branch

**Comment by jakelandis** [comment]
@andreidan thanks for the test, however, I think the preferred testing framework to use is `ESSingleNodeTestCase` , which is hopefully trivial to change to. If it is not a trivial change, then what you have here should be plenty sufficient.

**Comment by andreidan** [comment]
@elasticmachine update branch

**Review by jakelandis — APPROVED** [review]
LGTM, thanks for the iterations on the testing.

**Pull request merged**
