### PR TITLE
explain the boost effect plus an example.

### PR DESCRIPTION
**Pull request by adrinjalali**
I guess an example would be helpful to show the effect of boost values.

### CODE REVIEW

**Comment by rjernst** [comment]
@clintongormley Do you think this is an improvement on the docs we should merge?

**Comment by clintongormley** [comment]
I'm not sure the example is required.  In fact I think that the explain output is more intimidating than anything else.

I think the first sentence is fine, but I'd skip the bit about boosts not being meaningful when you don't sort by score - that applies to all queries.

**Comment by dakrone** [comment]
@adrinjalali are you interested in making the changes @clintongormley suggested?

**Comment by adrinjalali** [comment]
I remember when I was reading these documents for the first time 9 months ago, I had a really hard time understanding what boos does here, and I could only understand it with the example.

I would disagree that "boosts not being meaningful when you don't sort by score - that applies to all queries." is obvious to users reading the documentation by the time they get here, hence I'd stand with the PR as is.

**Comment by clintongormley** [comment]
OK, I don't think we should merge this as is.  Thanks anyway @adrinjalali

**Pull request closed without merging**
