### PR TITLE
Move resources to their proper location

### PR DESCRIPTION
**Pull request by rjernst**
We have a a number of resources in the java source tree, mostly for
tests. This change moves them to their proper location.

### CODE REVIEW

**Comment by dadoonet** [comment]
It looks good to me. 

For completeness, IIRC the same idea I submitted 2 years ago, you should probably remove [that](https://github.com/elastic/elasticsearch/blob/master/core/pom.xml#L199-L205).

**Comment by rjernst** [comment]
@dadoonet I removed the now unnecessary maven parts.

**Comment by dadoonet** [comment]
Left a comment. Just run the full test again because I remember hitting issues when filtering/non filtering some resources. Filtering does not work well with zip or gz files :)

**Comment by rjernst** [comment]
I ran verify in core and it passes. To which dir are you referring?

**Comment by rjernst** [comment]
Ok, I see now what is using this. `es-build.properties` is injected with build properties by "filtering". Maybe the thing using this could grab this information from the jar instead. I will take a look as a follow up issue. I'll add back the resources block, but specifically only filtering that file.

**Comment by rjernst** [comment]
@dadoonet I pushed a new commit.

**Comment by rjernst** [comment]
All tests are passing. I'll push now based on the looks good earlier.

**Comment by rjernst** [comment]
2.x commit: db7d797

**Pull request merged**
