### PR TITLE
[Behavioral Analytics] Rewrite flaky tests

### LINKED ISSUE #97360: [CI] BulkProcessorFactoryTests testFlushDelay failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/mclzwalttwijo/tests/:x-pack:plugin:ent-search:test/org.elasticsearch.xpack.application.analytics.ingest.BulkProcessorFactoryTests/testFlushDelay

**Reproduction line:**
```
./gradlew ':x-pack:plugin:ent-search:test' --tests "org.elasticsearch.xpack.application.analytics.ingest.BulkProcessorFactoryTests.testFlushDelay" -Dtests.seed=BAF47521A90D626F -Dtests.locale=mk -Dtests.timezone=Europe/Kyiv -Druntime.java=20
```

**Applicable branches:**
main, 8.9

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.application.analytics.ingest.BulkProcessorFactoryTests&tests.test=testFlushDelay

**Failure excerpt:**
```
org.mockito.exceptions.verification.WantedButNotInvoked: 
Wanted but not invoked:
client.execute(
    <any org.elasticsearch.action.bulk.BulkAction>,
    <custom argument matcher>,
    <any>
);
-> at org.elasticsearch.xpack.application.analytics.ingest.BulkProcessorFactoryTests.lambda$testFlushDelay$1(BulkProcessorFactoryTests.java:65)

However, there were exactly 2 interactions with this mock:
client.settings();
-> at org.elasticsearch.client.internal.FilterClient.<init>(FilterClient.java:34)

client.threadPool();
-> at org.elasticsearch.client.internal.FilterClient.<init>(FilterClient.java:34)


  at __randomizedtesting.SeedInfo.seed([BAF47521A90D626F:CC935BD102AE17C]:0)
  at org.elasticsearch.xpack.application.analytics.ingest.BulkProcessorFactoryTests.lambda$testFlushDelay$1(BulkProcessorFactoryTests.java:65)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1172)
  at org.elasticsearch.xpack.application.analytics.ingest.BulkProcessorFactoryTests.testFlushDelay(BulkProcessorFactoryTests.java:65)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

```

### PR DESCRIPTION
**Pull request by afoucret**
This unit test was testing the feature of the underlying `BulkProcessor2` component instead of focusing on it sole purpose (the component instantiation). This new test now focus on checking if config is correctly used to instantiate the BulkProcessor.

### CODE REVIEW

**Comment by mark-vieira** [comment]
@afoucret Just a heads up on why @elasticsearchmachine seems intent on removing your labels :). Our "Team" labels are bound to area labels. For example, `Team:Search` must accompany an area label such as `:Search/Mapping`. When the area label is added, the bot will add the corresponding team label. When the area label is removed, the team label is also removed. The bot is removing the team label because there are no matching area labels.

**Comment by afoucret** [comment]
@mark-vieira Thank you for the heads up. My original intent was to add the `Team:Enterprise Search` which is not tight to an area to my knowledge. I am sure the bot and me can find some sort of agreement at some point.

**Comment by mark-vieira** [comment]
Adding the `:EnterpriseSearch/Application` label should sort you out.

**Comment by afoucret** [comment]
@mark-vieira Thank you!!!

**Review by kderusso — APPROVED** [review]
Changes LGTM, would appreciate weigh-in from team on some of the dropped test functionality.

**Comment by kderusso** [comment]
Merging this as it hasn't received other feedback.

**Comment by afoucret** [comment]
@elasticsearchmachine backport to 8.11

**Pull request merged**
