### PR TITLE
Update field-names-field.asciidoc

### PR DESCRIPTION
**Pull request by siffash**
Fixed a typo

### CODE REVIEW

**Review by cbuescher — APPROVED** [review]
LGTM

**Comment by cbuescher** [comment]
@elasticmachine test this please

**Comment by cbuescher** [comment]
@siffash thanks for spotting and correcting this, I merged it to 7.3 and newer branches of the docs.

**Comment by pcsanwald** [comment]
@cbuescher I added `v7.3.3`, LMK if this seems incorrect

**Pull request merged**
