### PR TITLE
Allow changing only search_analyzer on existing field

### LINKED ISSUE #15185: changing search_analyzer on existing field returns error
Trying to change the search analyzer for an existing field through put mapping api:

```
PUT test/my_type/1
{
  "field":"value"
}

PUT test/_mapping/my_type
{
  "properties": {
    "field" : {
      "type": "string",
      "search_analyzer": "keyword"
    }
  }
}
```

I get back "analyzer on field [field] must be set when search_analyzer is set". The error seems to imply that I have to add the "analyzer" too, although it is the default one already. Adding `"analyzer": "standard"` as follows:

```
PUT test/_mapping/my_type
{
  "properties": {
    "field" : {
      "type": "string",
      "search_analyzer": "keyword",
      "analyzer": "standard"
    }
  }
}
```

causes a "Merge failed with failures {[mapper [field] has different [analyzer]]}". I am not sure what I am doing wrong or whether there is a bug somewhere, but at least the errors here really need to be improved and clarified.

### PR DESCRIPTION
**Pull request by cbuescher**
When a field and its default mapping already exists, it should be possible to
only change the search_analyzer setting without having to specify the analyzer
setting again. This currently leads to an error because we check that
search_analyzer can only be set when there is an additional analyer setting in
the mapping. This change fixes this by allowing the update if there is already
an analyzer defined for that field.

Closes #15185

### CODE REVIEW

**Comment by jpountz** [comment]
I suspect that it doesn't work if the existing `analyzer` is not the default analyzer, because then Elasticsearch would think that the mapping update is trying to change the index analyzer, which is not permitted.

This isn't only a problem with search analyzers. For instance I believe you would get the same error if you tried to enable `eager_global_ordinals` on a `keyword` field that is not indexed. If the mapping update doesn't reiterate that the `keyword` field is not indexed, then Elasticsearch would understand the mapping update as an attempt to enable indexing on a field that is not indexed.

**Comment by cbuescher** [comment]
@jpountz thanks for your comment, I extended the single node test to the case where you had doubts (existing analyzer is not the default analyzer), that at least seems to work. About your other comment about this not being a problem of only "search_analyzer": was this meant as an argument against fixing this particular issue if it is not solving other cases? I'd argue that while this change might only fix cases like #15185, that behavour is annoying enough to get fixed alone and the code change isn't too involved to immediately justify the need for a general. Wdyt?

**Comment by jpountz** [comment]
I haven't made my mind yet but indeed I'm wondering whether this is the right fix for it. In general specifying a `search_analyzer` without an `analyzer` is a mistake. That said, on an existing field it can make sense to update the search analyzer but retain the same index analyzer (which is how I read #15185). Except that it is not how the update-mappings API works: when we update the mapping of a field, we don't only try to  replace options that have an explicit value, we try to replace all of them. We are already working around this in a couple places (check for usage of the  `Explicit` wrapper in mappings), so this wouldn't be the first one. But this makes me wonder whether we should rethink mapping updates to make Elasticsearch understand them as "patches" rather than new mappings, this would have a much bigger scope than the change that you are suggesting though.

>  that behaviour is annoying enough to get fixed alone and the code change isn't too involved to immediately justify the need for a general fix

Agreed, a general fix would be a much bigger change. Past conversations and now this one are making me think that the general agreement is that the current way that mapping updates work is counter-intuitive and that we should look into making them work like patches instead. The only worry I have at this point is unexpected side-effects, but can't think of any yet.

**Comment by cbuescher** [comment]
@elasticmachine run default-distro

**Comment by jtibshirani** [comment]
I happened to take a look as I was going through some older mapping issues. I found this approach a bit surprising/ tricky because it works outside the usual pattern around mapping updates. Usually the methods `FieldMapper#doMerge` contain the logic for how field mapping updates are applied, but this fix actually operates inside of type parsing. However, I can see the difficulty with trying to use the normal mechanism -- we would have to adjust `doMerge` and also move the analyzer validation to a later phase in the mapping update, so that only a `search_analyzer` is allowed to be provided in an update.

It would be nice if we had a general validation phase *after* mappings are merged, that allows fields to check the final mapping. We already perform a few checks post-merge related to whether fields have valid references to other fields in the mapping (https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/index/mapper/MapperService.java#L496-L499), but those were individual additions and there is no general framework yet.

I wonder if for this particular issue, it'd be best to add a note to the docs explaining the limitation? We could even include the limitation/ workaround as part of the error message. The problem could still be tracked as part of a larger effort to rework mapping updates.

**Comment by jpountz** [comment]
I suspect that a general fix to this issue would introduce other issues so I'm not seeing this happen soon (happy to be proven wrong :) ), so +1 to document that mapping updates replace mappings rather than patch them on a per-field basis.

**Comment by rubesMN** [comment]
Will this ever be merged?    I just had to completely rebuild my index due to search_analyzer being off by a bit.

**Comment by cbuescher** [comment]
Coming back to this after a long time, I'm going to close the issue but opened a PR to improve the documentation (https://github.com/elastic/elasticsearch/pull/69621).
The original issue (#15185) seems to be fixed after our recent mapping refactorings, so now we only need to repeat the "analyzer" definition when updating the "search_analyzer" when it is not the "default" one.

**Pull request closed without merging**
