### PR TITLE
Propagate ?master_timeout query parameter from CCR apis to downstreams

### PR DESCRIPTION
**Pull request by volodk85**
This PR aims to add `?master_timeout` query parameter to listed below CCR APIs:
- RestCcrStatsAction
- RestDeleteAutoFollowPatternAction
- RestFollowInfoAction
- RestGetAutoFollowPatternAction
- RestPauseAutoFollowPatternAction
- RestPauseFollowAction
- RestPutAutoFollowPatternAction
- RestPutFollowAction
- RestResumeAutoFollowPatternAction
- RestResumeFollowAction
- RestUnfollowAction

Explanation:

`MasterNodeRequest#masterNodeTimeout()` is used by APIs either explicitly like here [link1](https://github.com/elastic/elasticsearch/blob/6fa7f600738494391b8ee2241ea8664db259cc95/x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/TransportPutFollowAction.java#L191) or implicitly (by creating timeout aware instances of `ClusterStateUpdateTask`) - [link2](https://github.com/elastic/elasticsearch/blob/2b03368639b269d7f71bb41313fa24cc10961225/x-pack/plugin/ccr/src/main/java/org/elasticsearch/xpack/ccr/action/TransportPutAutoFollowPatternAction.java#L115), also `masterNodeTimeout` is part of `TransportMasterNodeAction` infra [link3](https://github.com/elastic/elasticsearch/blob/b2127ec2f96674b1ec5b2d08a2be9c8ccf0226a1/server/src/main/java/org/elasticsearch/action/support/master/TransportMasterNodeAction.java#L288) meaning it is used whenever master node action is spawned

Following APIs were extended with `?timeout` query parameter, since their corresponding transport actions create background tasks which are also timeout aware
- RestFollowStatsAction
- RestForgetFollowerAction

Related to #105126

### CODE REVIEW

**Comment by volodk85** [comment]
@elasticsearchmachine update branch

**Review by DaveCTurner — COMMENTED** [review]
Looks good, but there's a few more of these to address before we can close https://github.com/elastic/elasticsearch/issues/105126:

- `org.elasticsearch.xpack.ccr.action.TransportGetAutoFollowPatternAction`
- `org.elasticsearch.xpack.ccr.action.TransportPauseFollowAction`
- `org.elasticsearch.xpack.ccr.action.TransportResumeFollowAction`
- `org.elasticsearch.xpack.ccr.action.TransportUnfollowAction`

Also it looks like this commit addresses `org.elasticsearch.xpack.ccr.action.TransportDeleteAutoFollowPatternAction` but doesn't mention it in the description/tests/docs/api spec.

**Review by DaveCTurner — COMMENTED** [review]
`RestPauseFollowAction` and `RestResumeFollowAction` delegate respectively to `RemovePersistentTaskAction` and `StartPersistentTaskAction`, which are also master-node actions so we should propagate the master-node timeout to these requests too (this involves fixing https://github.com/elastic/elasticsearch/issues/105128 first).

Similarly `RestCcrStatsAction` delegates to `FollowStatsAction` which is a `TransportTasksAction` which also has a timeout. By default I think this timeout is infinite, but maybe consider exposing this parameter to users too?

**Comment by volodk85** [comment]
- I agree that `RestPauseFollowAction` and `RestResumeFollowAction` should pass master-node timeout to corresponding tasks and they will pass the param as soon as #105128 is in place.
@DaveCTurner would you like to defer this change until #105128 is done?
(I'd like these two changes checked-in independently and connect them when everything is ready, otherwise fix for #105128 would contain some temporary logic to handle requests with and without timeouts, possibly it is about methods overloading in `PersistentTasksService` or so)

- Updated `RestCcrStatsAction` to accept `timeout` query param and pass it down to FollowStatsAction's request.

**Comment by DaveCTurner** [comment]
Yes I think it makes sense to fix #105128 before fixing `RestPauseFollowAction` and `RestResumeFollowAction` and calling #105126 closed. We can merge the rest of these improvements without fixing #105128 tho, we just need to keep #105126 open.

**Comment by volodk85** [comment]
Depends on https://github.com/elastic/elasticsearch/pull/105676

**Review by DaveCTurner — APPROVED** [review]
LGTM (except would you change the PR title and the commit message since we're fixing a lot more than just the put-follow API here)

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Pull request merged**
