### PR TITLE
GeoBoundingBox query should work on bounding box with equal latitude or longitude

### LINKED ISSUE #77717: GeoBoundingBox query should work on bounding box with equal latitude or longitude
Currently when you try to execute a GeoBoundingBox query like:

```
GET /my-index/_search?pretty
{
  "query": {
    "geo_bounding_box": { 
      "location": {
        "top_left": {
          "lat" : 41.1199999647215,
          "lon" : -71.34000004269183
        },
        "bottom_right": {
          "lat" : 41.1199999647215,
          "lon" : -71.34000004269183
        }
      }
    }
  }
}
```

You get an error like:

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "top cannot be the same as bottom: 41.1199999647215 == 41.1199999647215"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "top cannot be the same as bottom: 41.1199999647215 == 41.1199999647215"
  },
  "status" : 400
}
```

On the other hand using the same bounding box on a geo_shape query works. Lucene actually supports it so I think this limitation should  be removed from the query builder.

### PR DESCRIPTION
**Pull request by jchrys**
This PR removes the validation checkers for latitude/ longitude equality and adds test cases that covers the changes.

fixes #77717

### CODE REVIEW

**Review by iverase — CHANGES_REQUESTED** [review]
This is looking great. For completeness, could we add a test on `GeoBoundingBoxQueryIntegTestCase`?

**Comment by iverase** [comment]
Just checking in here, how are you doing with the requested change?

**Comment by jchrys** [comment]
Hello, @iverase .
Thanks very much for stopping by the issue and my progress.
I added the example test below in the class `GeoBoundingBoxQueryIntegTestCase` but it failed.
I expected that if I query like the test below, I would get the value in the corresponding point.
However, the test below succeeded in some cases(`GeoBoundingBoxQueryLegacyGeoShapeIT`,`GeoBoundingBoxQueryLegacyGeoShapeWithDocValuesIT`) and failed in others(`GeoBoundingBoxQueryGeoPointIT`,`GeoBoundingBoxQueryGeoShapeIT`,`GeoBoundingBoxQueryGeoShapeWithDocValuesIT`).
The actual result was different from what I expected, so I was doing my own research.
But can I get some help with testing?

```Java

    public void testSimpleBoundingBoxTest() throws Exception {
        Settings settings = Settings.builder().put(IndexMetadata.SETTING_VERSION_CREATED, randomSupportedVersion()).build();
        XContentBuilder xContentBuilder = getMapping();
        assertAcked(prepareCreate("test").setSettings(settings).setMapping(xContentBuilder));
        ensureGreen();

        client().prepareIndex("test")
            .setId("1")
            .setSource(jsonBuilder().startObject().field("name", "New York").field("location", "POINT(-74.0059731 40.7143528)").endObject())
            .get();

        client().admin().indices().prepareRefresh().get();

        SearchResponse searchResponse = client().prepareSearch()
            .setQuery(geoBoundingBoxQuery("location").setCorners(40.7143528, -74.0059731, 40.7143528, -74.0059731))
            .get();
        assertThat(searchResponse.getHits().getTotalHits().value, equalTo(1L));
        assertThat(searchResponse.getHits().getHits().length, equalTo(1));
        for (SearchHit hit : searchResponse.getHits()) {
            assertThat(hit.getId(), equalTo("1"));
        }
    }
```

**Comment by iverase** [comment]
Umm, I tried to reproduce it but I cannot. Maybe you need to update your branch with the latest master, there was achange recently that might help here: https://github.com/elastic/elasticsearch/pull/85441

**Comment by jchrys** [comment]
Thank you very much again! 
let me check the update and I will test with lastest master 👍

**Comment by jchrys** [comment]
I rebased PR onto latest master(9ae5885d53f06f7b96f09249eb389862134adcae).
and I have added IntegTests for changes.

**Comment by iverase** [comment]
@elasticmachine test this please

**Comment by iverase** [comment]
It seems some of the checks are failing:
```
10:25:14 > Task :test:framework:checkstyleMain
10:25:14 [ant:checkstyle] [ERROR] /dev/shm/elastic+elasticsearch+pull-request+part-1/test/framework/src/main/java/org/elasticsearch/search/geo/GeoBoundingBoxQueryIntegTestCase.java:233: Line is longer than 140 characters (found 153). [LineLength]
10:25:14 [ant:checkstyle] [ERROR] /dev/shm/elastic+elasticsearch+pull-request+part-1/test/framework/src/main/java/org/elasticsearch/search/geo/GeoBoundingBoxQueryIntegTestCase.java:258: Line is longer than 140 characters (found 152). [LineLength]
10:25:14 [ant:checkstyle] [ERROR] /dev/shm/elastic+elasticsearch+pull-request+part-1/test/framework/src/main/java/org/elasticsearch/search/geo/GeoBoundingBoxQueryIntegTestCase.java:265: Line is longer than 140 characters (found 154). [LineLength]
10:25:14 [ant:checkstyle] [ERROR] /dev/shm/elastic+elasticsearch+pull-request+part-1/test/framework/src/main/java/org/elasticsearch/search/geo/GeoBoundingBoxQueryIntegTestCase.java:354: Line is longer than 140 characters (found 161). [LineLength]
10:25:14 [ant:checkstyle] [ERROR] /dev/shm/elastic+elasticsearch+pull-request+part-1/test/framework/src/main/java/org/elasticsearch/search/geo/GeoBoundingBoxQueryIntegTestCase.java:358: Line is longer than 140 characters (found 164). [LineLength]
```

My advise is to run locally on the PR `./gradlew precommit` and fix the errors that might come up.

**Comment by jchrys** [comment]
Oh, I'm sorry.
Let me check it and fix it.

**Comment by jchrys** [comment]
Hello, @ iverase.
I have checked and fixed it.

**Comment by iverase** [comment]
@elasticmachine test this please

**Review by iverase — APPROVED** [review]
LGTM

**Comment by iverase** [comment]
Thanks @jchrys for the contribution, the PR is now merged.  @glennvill pinging you so you can check the final PR.

**Comment by jchrys** [comment]
@iverase 
Thank you so much for guiding me.
I will keep my eyes on the issues menu and If there are issues that I can contribute,  I will actively pick them up and try to contribute.
Thanks again!

**Pull request merged**
