### PR TITLE
[CCR] Add metadata to keep track of the index uuid of the leader index in the follow index

### LINKED ISSUE #31505: [CCR] Introduce leader index setting for follow index
Associate the uuid of the leader index in the follow index's index settings. 
The follow index api should fail if this index setting in the follow index and
should check if the uuid in the follow index matches with uuid of the leader index.

This validation will prevent a follow index from following an incompatible leader index.

The create and follow api should introduce this setting when it creates the follow index.

Relates to #30086

### PR DESCRIPTION
**Pull request by martijnvg**
The follow index api checks if the recorded uuid in the follow index matches
with uuid of the leader index and fails otherwise. This validation will
prevent a follow index from following an incompatible leader index.

The create_and_follow api will automatically add this custom index metadata
when it creates the follow index.

Closes #31505

### CODE REVIEW

**Review by jasontedor — CHANGES_REQUESTED** [review]
In the course of some discussions with @bleskes last night, we came to the realization that maybe history UUID is all that we need here, and we do not need to track the leader index UUID separately. Are there any cases that you can think of @martijnvg where the leader index UUID gives us something that the history UUID would not?

**Comment by jasontedor** [comment]
@martijnvg This [comment](https://github.com/elastic/elasticsearch/pull/33118/files#diff-1d64a7128507c2a5da6411a37198786bR255) is a potential place where using the index UUID is more natural than using the history UUID. In which case we might want to consider progressing on this PR rather than closing as we discussed earlier this evening.

**Comment by martijnvg** [comment]
@jasontedor Good point. Lets then get this PR in and after that get history uuid validation in. Although leader index uuid valdation in the follow api is not strictly needed in this PR, it is just a small if check that just makes the error message better if someone follows the wrong follow index.

**Review by jasontedor — APPROVED** [review]
LGTM.

**Pull request merged**
