### PR TITLE
Switch default runtime java to version 11

### PR DESCRIPTION
**Pull request by alpar-t**
After seeing some Java 11 and 12 test failures, I think the time is
right to default to runtime Java 11 for CI.
This will cause PR and intake builds to test with JDK 11, it will not
affect the matrix jobs where we will still test against 8.

### CODE REVIEW

**Comment by atorok** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by jasontedor** [comment]
> After seeing some Java 11 and 12 test failures, I think the time is
> right to default to runtime Java 11 for CI.

@atorok Can you elaborate on what the failure rate has to do with switching to JDK 11 being the default?

**Comment by atorok** [comment]
@jasontedor my thinking is that with this change we would catch some java 11+ specific failure earlier, in the PR builds.  I could be wrong but my expectation is that we will have more failures pretending to newer java versions than old ones, so we should run tests in PR and intake with the new, and verify the old in the matrix jobs.

**Comment by atorok** [comment]
Closing in favor of #40531

**Pull request closed without merging**
