### PR TITLE
[DOCS] Update quickstart curl commands

### LINKED ISSUE #85130: [DOCS] Quick start `curl` documentation for http and not https
### Elasticsearch Version

8.0.0

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Linux reinoso 5.8.0-59-generic #66~20.04.1-Ubuntu SMP Thu Jun 17 11:14:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Problem Description

On documentation: https://www.elastic.co/guide/en/elasticsearch/reference/current/getting-started.html#send-requests-to-elasticsearch

You can see to use:
```bash
curl -X GET http://localhost:9200/
```

But if you use default self-management, you have a certificate and credentials.

### Steps to Reproduce

One time installed Elasticsearch 8.1.0 from Docker, you can't use:
```bash
$ curl -X GET http://localhost:9200/
curl: (52) Empty reply from server
```

I'm not sure the correct fix, but it works with `curl:`
```bash
curl -k -u elastic:<password> -X GET https://localhost:9200/
```
Where:
- `-k` is for ignore the credentials from Elasticsearch. I don't think that's a good option, but for now I don't know how to get Elasticsearch credentials.
- https, by default Elasticsearch works with https
- `-u` You need a credential in Elasticsearch by default now.  And the default user is `elastic`.

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by lockewritesdocs**
Updates the `curl` commands in the quick start guide to use the generated security certificate. Because the quickstart uses Docker, these commands reference the security certificate in the Docker container.

Closes #85130

### CODE REVIEW

**Review by bytebilly — COMMENTED** [review]
@lockewritesdocs is it possible to get the final preview somewhere? I think that changes are good, but it is worth to do an end-to-end validation.

We probably also want to make Kibana consistent with names used elsewhere.

**Comment by lockewritesdocs** [comment]
@elasticmachine run @elasticsearch-ci/docs

**Comment by lockewritesdocs** [comment]
@elasticmachine test this please

**Comment by lockewritesdocs** [comment]
> @lockewritesdocs is it possible to get the final preview somewhere? I think that changes are good, but it is worth to do an end-to-end validation.

@bytebilly, here's the [preview link](https://elasticsearch_86145.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/getting-started.html#send-requests-to-elasticsearch). Apologies for not including it previously in the PR description.

**Comment by bytebilly** [comment]
> @bytebilly, here's the [preview link](https://elasticsearch_86145.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/getting-started.html#send-requests-to-elasticsearch). Apologies for not including it previously in the PR description.

Thanks! Is it possible to update the Kibana container name too?

**Comment by lockewritesdocs** [comment]
> Thanks! Is it possible to update the Kibana container name too?
Yes! I just changed the container name to `kibana` so that it's consistent with our Docker docs.

**Review by bytebilly — APPROVED** [review]
LGTM 👍

**Pull request merged**
