### PR TITLE
Wait forever (or one day) for indices to close

### LINKED ISSUE #10680: ES do not wait for all shards being closed before shutdown/restart
Hi!

I have a one node setup and spotted that if I create a lot of indices/shards and then immediatly will try to restart the server, it will come back online in the red state with a couple of unassigned shards and errors in log like this:

```
Caused by: java.io.EOFException: read past EOF:   
NIOFSIndexInput(path="/var/lib/elasticsearch/elasticsearch/nodes/0/indices/intelligence-reports-2014.05.01/3/index/segments_2”)
```
The problem is that ES starts to flush shards to the hard drive, but does not manage to do that in time, so some shards remain unflushed.

Init script that comes bundled with ES gives 20 seconds for it to finish all preparations:
start-stop-daemon --stop --pidfile "$PID_FILE" \ --user "$ES_USER" \ --retry=TERM/20/KILL/5 > /dev/null

If you bump that period, ES have [hardcoded rule to do that in 30 secs](https://github.com/elastic/elasticsearch/blob/master/src/main/java/org/elasticsearch/indices/IndicesService.java#L153), otherwise:
```
[2015-04-21 15:04:03,558][INFO ][node ] [collaboration] stopping ...   
 [2015-04-21 15:04:33,581][WARN ][indices ] [collaboration] Not all shards are closed yet, waited 30sec - stopping service    
[2015-04-21 15:04:33,581][INFO ][node ] [collaboration] stopped    
[2015-04-21 15:04:33,581][INFO ][node ] [collaboration] closing ...    
[2015-04-21 15:04:33,587][INFO ][node ] [collaboration] closed
```

I know that I can "fix" this by send `flush` after massive write is finished, but why ES needs to kill himself after 30 secs and does not wait for shards to close?

### PR DESCRIPTION
**Pull request by s1monw**
Today we wait 30 sec for shards to flush and close and then simply exit the process.
This is often not desired and we should by default wait long enough for shards to
close etc. This commit adds a default timeout of one day which simplifies the code
and gives us _enough_ time to shut down.

Closes #10680

### CODE REVIEW

**Comment by tlrx** [comment]
LGTM

**Comment by clintongormley** [comment]
Should we also (separately) change the default timeout in the init script? It's already configurable by the user but wondering if we should up the default?

**Comment by s1monw** [comment]
@bleskes any comments

**Comment by ivanilves** [comment]
:+1: Great! Finally.

**Comment by bleskes** [comment]
For what it's worth now, LGTM as well.

**Comment by s1monw** [comment]
;)

**Pull request merged**
