### PR TITLE
Fix xpack info and usage reports for operator privileges

### PR DESCRIPTION
**Pull request by ywangd**
This is a follow-up PR for #65256 to fix the xpack info and usage reports for operator privilegs. In summary, this PR ensures:
* `_xpack` does not report operator privileges because it is categorised under security
* `_xpack/usage` reports operator privileges status under the security section
* `_license/feature_usage` reports last used time of operator privileges. It is up to the downstream to filter out this report if necessary.

I tag this PR as `non-issue` because the original changes are not released yet. Also this will not be backported separately because it will be backported along with the main changes (#65256).

### CODE REVIEW

**Comment by ywangd** [comment]
@elasticmachine update branch

**Comment by tvernum** [comment]
> It is up to the downstream to filter out this report if necessary.

I assume you will make sure they know that.

**Review by tvernum — APPROVED** [review]
LGTM

**Comment by ywangd** [comment]
> > It is up to the downstream to filter out this report if necessary.
> 
> I assume you will make sure they know that.

Good point. I will initiate an email for it.

**Pull request merged**
