### PR TITLE
Automatically disable `ignore_malformed` on datastream `@timestamp` fields

### PR DESCRIPTION
**Pull request by romseygeek**
Data-stream mappings require a `@timestamp` field to be present and configured
as a `date` with a specific set of parameters.  The index-wide setting of 
`ignore_malformed` can cause problems here if it is set to `true`, because it needs
to be `false` for the `@timestamp` field.

This commit detects if a set of mappings is configured for a datastream by checking
for the presence of a DataStreamTimestampFieldMapper metadata field, and passes
that information on during Mapper construction as part of the MapperBuilderContext.
DateFieldMapper.Builder now checks to see if it is specifically for a data stream timestamp
field, and if it is, sets `ignore_malformed` to `false`.

Relates to #96051

### CODE REVIEW

**Comment by romseygeek** [comment]
The PR is a bit noisy because of all the changes to tests which require an extra parameter when creating a MapperBuilderContext.  It might be worth creating a separate ESTestCase root builder context that tests can use so any further additions here don't touch so many files.

**Comment by felixbarny** [comment]
This doesn't seem to cover all cases yet. One thing that I think is missing is that it assumes that the `@timestamp` field is defined on the index template that enables a data stream. However, the timestamp field may be in a different component template. So when merging mappings we have to check if either of the mappings that are being merged have a data stream timestamp field. See also https://github.com/elastic/elasticsearch/pull/96081/files#diff-25d9707160d3d2cedcb684cff9aa0d4b724382d6736d51827505fd8912366925

A good way to test this is to remove the `ignore_malformed` parameter in `logs-settings.json` and `data-streams-mappings.json`.

The test `org.elasticsearch.datastreams.mapper.DataStreamTimestampFieldMapperTests#testValidateDefaultIgnoreMalformed` should fail after the change but it currently doesn't. See also https://github.com/elastic/elasticsearch/pull/96081/files#diff-e958f0e9a1ec6d83377799806ad9c2dfd20580474ad8ec82af1b8e56049e4ef4

Feel free to take over https://github.com/elastic/elasticsearch/pull/96081 and extend that PR if it helps, otherwise equally feel free to move over some bits and pieces to this PR.

**Comment by romseygeek** [comment]
I think those cases will actually be covered when #97317 is merged.  That PR changes the way we build component templates so that the various components are merged together before we parse and build the final template mapper.  But I will port those test cases across - thank you for the pointer there.

**Comment by felixbarny** [comment]
Oh, I see. Yes, that could indeed make this much simpler.

**Review by andreidan — APPROVED** [review]
Thanks for fixing this Alan.

LGTM, once CI is happy (just a minor checkstyle complaint at the moment)

**Comment by romseygeek** [comment]
OK, that's interesting - I removed the explicit `ignore_malformed: false` setting from `data-streams-mappings.json` on the assumption that things would fail, because we still need #97317 to be merged to make this work with multiple templates, but tests all pass.  So maybe it doesn't need that as a prerequisite after all?  I think I'll try and add some explicit templating tests here to make sure I understand the code paths properly.

**Comment by felixbarny** [comment]
Don't forget to also remove the setting from `logs-settings.json`. I know that this has some explicit tests. I'm not entirely sure about `data_streams-mappings.json`.

**Comment by romseygeek** [comment]
Yep, it fails if I remove it from logs-mappings.json.  So we are waiting for #97317

**Review by javanna — APPROVED** [review]

**Comment by romseygeek** [comment]
@elasticmachine update branch

**Review by felixbarny — APPROVED** [review]
Thanks a lot! After merging the new mapping merge algorithm, the tests are green now 🎉.
I'm wondering about back porting this. On the one hand, it would be great if we could back port this as it's something that users are struggling with since we made `ignore_malformed` the default in all log data streams. On the other hand, back porting seems risky as we'd also need to back port https://github.com/elastic/elasticsearch/pull/97317 and both are arguably an enhancement/new feature.

**Comment by romseygeek** [comment]
> back porting seems risky

I agree, there's quite a few entangled changes in here and I think it would be very tricky to try and get this into a bug-fix release.

**Pull request merged**
