### PR TITLE
Adapt FullClusterRestartIT on master

### PR DESCRIPTION
**Pull request by cbuescher**
As a follow up to #38795 this PR removes a lot of special case handling that was necessary
for full cluster restart checks going from 6.x to 7.x clusters but are not required anymore going
from 7 to 8.

### CODE REVIEW

**Review by jtibshirani — COMMENTED** [review]
I noticed some other changes that fit with the goal of adapting the test for 8.0. I think it would be good to do all the updates in one PR, if that makes sense to you as well.
- We can remove `type` here, because all the calls in this method are now typeless.
- We can remove all instances of `expectWarnings` and `allowTypesRemovalWarnings`, along with associated version checks.
- I think we can remove `isTypeInTemplateResponse`, and the associated check.
- We no longer need the special check in `extractTotalHits`.

**Comment by cbuescher** [comment]
@jtibshirani thanks for the review, I agree with you to remove the deprecation warnings etc... and pushed some follow up commits for this

**Comment by cbuescher** [comment]
As a note, I think the commit I merged in has bwc tests temporarily disabled, so I'm planning to run tests again after merging in master once again when bwc tests are enabled again.

**Review by jtibshirani — APPROVED** [review]
This looks good to me, assuming the BWC tests pass!

**Pull request merged**
