### PR TITLE
remove string interning

### PR DESCRIPTION
**Pull request by bleskes**
Keep it simple and just use normal strings

Relates #16217

### CODE REVIEW

**Comment by jpountz** [comment]
Thanks! I am tempted to make string interning a forbidden API.

**Comment by s1monw** [comment]
+1 to forbid

**Comment by s1monw** [comment]
make is a release highlight :)

**Comment by jasontedor** [comment]
Why? My intuition is that we should keep this, but at least do a study before making the change.

**Comment by s1monw** [comment]
> Why? My intuition is that we should keep this, but at least do a study before making the change.

I disagree there is no reason for this to be there.

**Comment by s1monw** [comment]
I spoke to jason about this face to face and explained my bad experience with `intern()` on lucene. Yet, we have a bunch of more intern calls here which I personally think we should get rid of as well but from @jasontedor experience it might be wise to visit them case by case so I think this is a bigger issue and we should not block #16217

**Comment by bleskes** [comment]
OK. I went ahead and added string intern to the forbidden API. Also removed all usages in ES. @jasontedor  seems you had some concerns around this - can you check as well?

**Comment by s1monw** [comment]
@bleskes lets discuss this internally first. I think there are some caveats to this

**Comment by dakrone** [comment]
@bleskes how did this turn out? Can we close this PR?

**Comment by bleskes** [comment]
yeah, simon asked me to wait with it post 5.0 and it was controversial how useful it is anyway. I'll close and reopen if it's relevant.

**Pull request closed without merging**
