### PR TITLE
[ESQL] move optimizer rules to a package

### PR DESCRIPTION
**Pull request by not-napoleon**
This moves (most of) the Optimizer Rules from being public static sub-classes of `OptimizerRules` to being public top level classes in the `optimizer.rules` package. The main benefit of this is to reduce git conflicts when touching rules, since they will no longer be all in the same file.  It also improves readability, as short files are easier to read in general.

I would like to move the tests for these rules into class-specific test files, but there's some more general test refactoring that I'd like to get done first, so that'll be in a follow-up PR.

### CODE REVIEW

**Review by astefan — APPROVED** [review]
LGTM
But there are two files - mv_zip.json and mv_zip.asciidoc - that you might not wanted them in this PR?

**Comment by not-napoleon** [comment]
@elasticmachine update branch

**Comment by not-napoleon** [comment]
> But there are two files - mv_zip.json and mv_zip.asciidoc - that you might not wanted them in this PR?

Those are auto-generated docs, and I agree it's weird they changed here.  I wonder if they were committed in a different PR than the one that changed the generating code for some reason, and I happened to branch between them.  I'm pulling in main to see if that reconciles them.

**Comment by not-napoleon** [comment]
> > But there are two files - mv_zip.json and mv_zip.asciidoc - that you might not wanted them in this PR?
> 
> Those are auto-generated docs, and I agree it's weird they changed here. I wonder if they were committed in a different PR than the one that changed the generating code for some reason, and I happened to branch between them. I'm pulling in main to see if that reconciles them.



> > But there are two files - mv_zip.json and mv_zip.asciidoc - that you might not wanted them in this PR?
> 
> Those are auto-generated docs, and I agree it's weird they changed here. I wonder if they were committed in a different PR than the one that changed the generating code for some reason, and I happened to branch between them. I'm pulling in main to see if that reconciles them.

Indeed, merging in main took these two files out of the diff

**Pull request merged**
