### PR TITLE
Updates to changelog processing after docs redesign

### LINKED ISSUE #89441: [DOCS] Release highlights have broken heading links & no code highlighting
The generated release highlights have PR links in the headings. These links conflict with the anchor links added by the doc build and don't work as intended. In addition, the code snippets use Markdown-style code blocks instead of Asciidoc, so there's no code highlighting.

To fix the link issue, let's move the PR links to the end of the descriptions, similar to the way we handle the GH links in the Release notes. For example:

```
[discrete]
[[ingest_performance_improvement]]
=== Ingest performance improvement
We have improved the pipeline execution logic for pipelines with processors that are synchronous
by avoiding (deep) recursion.
On our nightly benchmark that simulates a Logging use-case, this resulted in a 10% reduction of
CPU time spent on ingest pipelines and a 3% overall ingestion speedup. 

{es-pull}84250[#84250]
```
To add code highlighting to the snippets, they need to be formatted as Asciidoc code blocks. For example:

```
[source,yaml]
----
{
  "metrics.time" : 10,
  "metrics.time.min" : 1,
  "metrics.time.max" : 500
}
----
```

### PR DESCRIPTION
**Pull request by pugnascotia**
Closes #89441. We need to make some changes to our release documentation,
following a docs site redesign.

   1. Move the PR links in the release highlights. This one is trivial.
   2. Code blocks need to use the Asciidoc style, not the Markdown
      triple-backtick style. This is now enforced by the changelog
      validatation. I also backfilled the unit tests.

### CODE REVIEW

**Review by mark-vieira — APPROVED** [review]
Thanks, Rory! LGTM.

**Review by debadair — APPROVED** [review]
Thank!

**Comment by mark-vieira** [comment]
@pugnascotia I've noticed the release notes generation code has deviated a good amount between `main` and `7.17`. Is this intentional? Should we get that synced up?

**Comment by mark-vieira** [comment]
@debadair are these changes applicable to 7.17 patch releases as well?

**Comment by mark-vieira** [comment]
@pugnascotia or is a lot of that stuff n/a for 7.17 since we aren't planning any new minors?

**Pull request merged**
