### PR TITLE
Restore xpack.ilm.enabled and xpack.slm.enabled settings

### PR DESCRIPTION
**Pull request by williamrandolph**
In #55592 and #55416, we deprecated the settings for enabling and disabling basic license features and turned those settings into no-ops. Since doing so, we've had feedback that this change may not give users enough time to cleanly switch from non-ILM index management tools to ILM. If two index managers operate simultaneously, results could be strange and difficult to reconstruct. We don't know of any cases where SLM will cause a problem, but we are restoring that setting as well, to be on the safe side.

This PR is not a strict commit reversion. First, we are keeping the new `xpack.watcher.use_ilm_index_management` setting, introduced when `xpack.ilm.enabled` was made a no-op, so that users can begin migrating to using it. Second, the SLM setting was modified in the same commit as a group of other settings, so I have taken just the changes relating to SLM.

Meta issue: #54745

### CODE REVIEW

**Comment by williamrandolph** [comment]
@elasticmachine update branch

**Comment by williamrandolph** [comment]
@elasticmachine update branch

**Comment by williamrandolph** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by williamrandolph** [comment]
Note: this is still under active discussion and may need to be reverted.

**Comment by williamrandolph** [comment]
This should not have been merged; I am going to revert.

**Comment by williamrandolph** [comment]
Reversion commit: dfb6def3da2

**Pull request merged**
