### PR TITLE
EQL: create the search request with a list of indices

### LINKED ISSUE #60793: EQL: multiple indices with commas not working
Docs say we supporting multiple indices
https://github.com/elastic/elasticsearch/blob/dca46c29fff1f77ba4c27f07a33d2895a96a1bba/docs/reference/eql/eql-search-api.asciidoc#L45-L51

**no results found when searching two patterns with a comma**
image

**just one index pattern**
image

### PR DESCRIPTION
**Pull request by astefan**
The EQL query client should use a list of indices when creating the search request, instead of a comma delimited string of these indices' names.

Fixes https://github.com/elastic/elasticsearch/issues/60793.

### CODE REVIEW

**Review by costin — APPROVED** [review]
LGTM

**Review by matriv — APPROVED** [review]
LGTM

**Comment by astefan** [comment]
@elasticmachine update branch

**Comment by astefan** [comment]
@elasticmachine update branch

**Pull request merged**
