### PR TITLE
Fix ConcurrentSnapshotsIT.testMasterFailoverDuringStaleIndicesCleanup

### LINKED ISSUE #88061: Reproducible Failure in ConcurrentSnapshotsIT.testMasterFailoverDuringStaleIndicesCleanup
### CI Link

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+part-1/15849/consoleFull

### Repro line

./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.snapshots.ConcurrentSnapshotsIT.testMasterFailoverDuringStaleIndicesCleanup" -Dtests.seed=E1117F7A8434C9ED -Dtests.locale=es-PR -Dtests.timezone=America/Cancun -Druntime.java=17

### Does it reproduce?

Yes

### Applicable branches

master

### Failure history

_No response_

### Failure excerpt

This is a test bug and a result of #86514. This test simply does not apply any longer in its current form.
I'll fix it.

Failure:

```

REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.snapshots.ConcurrentSnapshotsIT.testMasterFailoverDuringStaleIndicesCleanup" -Dtests.seed=E1117F7A8434C9ED -Dtests.locale=es-PR -Dtests.timezone=America/Cancun -Druntime.java=17

org.elasticsearch.snapshots.ConcurrentSnapshotsIT > testMasterFailoverDuringStaleIndicesCleanup FAILED
    java.lang.Exception: Test abandoned because suite timeout was reached.
        at __randomizedtesting.SeedInfo.seed([E1117F7A8434C9ED]:0)

REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.snapshots.ConcurrentSnapshotsIT.testMasterFailoverDuringStaleIndicesCleanup" -Dtests.seed=E1117F7A8434C9ED -Dtests.locale=es-PR -Dtests.timezone=America/Cancun -Druntime.java=17

org.elasticsearch.snapshots.ConcurrentSnapshotsIT > classMethod FAILED
    java.lang.Exception: Suite timeout exceeded (>= 1200000 msec).
        at __randomizedtesting.SeedInfo.seed([E1117F7A8434C9ED]:0)

```

### PR DESCRIPTION
**Pull request by original-brownbear**
As a result of https://github.com/elastic/elasticsearch/pull/86514 we now
remove the snapshot delete from the cluster state before cleaning up
stale shard level blobs so we have to block master earlier on deleting the
root level index-N blob to get the desired cluster state where delete
and snapshot creation are both in the cluster state at the same time.

closes #88061

### CODE REVIEW

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/part-2

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/packaging-tests-unix-sample

**Comment by original-brownbear** [comment]
Jenkins run  elasticsearch-ci/packaging-tests-unix-sample

**Comment by original-brownbear** [comment]
@elasticmachine update branch

**Review by tlrx — APPROVED** [review]
LGTM

**Comment by original-brownbear** [comment]
Thanks Tanguy!

**Pull request merged**
