### PR TITLE
Update to spatial4j 0.5 for correct Multi-Geometry

### LINKED ISSUE #9904: [GEO] Incorrect bounding box for Multi-geometry
Caught numerous times by our RandomGeoCollection test, the ShapeCollection.BoundingBox calculation in Spatial4j is wrong... this is a known issue that has not yet been corrected in Spatial4j https://github.com/spatial4j/spatial4j/issues/77 

For now Elasticsearch ShapeCollection corrects this, but the fix is not used internally by Spatial4j JtsGeometry.  Therefore any Multi-geometry (e.g., multipoint, multilinestring, multipolygon) which creates a spatial4j ShapeCollection under the hood, suffers from this bug.

There is a near term solution that will be applied until we can fix the fundamental problem within Spatial4j.

### PR DESCRIPTION
**Pull request by nknize**
A long time coming this upgrades to Spatial4J 0.5 which includes the fix for calculating a Multi-geometry bounding box. Duplicate code is removed

closes #9904

### CODE REVIEW

**Comment by s1monw** [comment]
this PR is missing updates for license files can you add it?

**Comment by nknize** [comment]
signature and license files updated.

**Comment by s1monw** [comment]
LGTM - @clintongormley does the notice file etc look good to? why didn't we have one before?

**Comment by nknize** [comment]
@s1monw Spatial4j moved to locationtech.org which is under the Eclipse Foundation. The notice file is the eclipse SUA and needs to be provided along with the "unless otherwise indicated" license file (in this case ASL2.0).

**Comment by clintongormley** [comment]
NOTICE file looks good.

**Pull request merged**
