### PR TITLE
[ML] Uplift model memory limit on job migration

### PR DESCRIPTION
**Pull request by droberts195**
When a 6.1-6.3 job is opened in a later version
we increase the model memory limit by 30% if it's
below 0.5GB. The migration of jobs from cluster
state to the config index changes the job version,
so we need to also do this uplift as part of that
config migration.

Relates #36961

### CODE REVIEW

**Comment by droberts195** [comment]
This is the forward port of #37125 to master

**Review by dimitris-athanasiou — APPROVED** [review]
LGTM

**Comment by dimitris-athanasiou** [comment]
jenkins please test this

**Comment by dimitris-athanasiou** [comment]
run gradle build tests 1

**Comment by dimitris-athanasiou** [comment]
run gradle build tests 2

**Comment by dimitris-athanasiou** [comment]
run default distro tests

**Review by davidkyle — APPROVED** [review]
LTGM2

**Pull request merged**
