### PR TITLE
Use efficient ActionListener.delegateFailureAndWrap in QL code

### PR DESCRIPTION
**Pull request by original-brownbear**
Went through this code for unrelated reasons and found lots of use of `ActionListener.wrap` that could be replaced by `delegateFailureAndWrap` to save some duplication and memory so I fixed those real quick.

### CODE REVIEW

**Review by DaveCTurner — COMMENTED** [review]
Several of these don't even fork so could be a `map` instead.

**Comment by original-brownbear** [comment]
> Several of these don't even fork so could be a map instead.

Maybe, not sure to be honest. We've been burnt here before by QL in particular, that's why QL build its own version of `map` that isn't as strict about what throwing exceptions as `map` is. I didn't feel like I know enough about this code to make that kind of change, though I agree it would be a good idea to go for `map` wherever feasible.

**Comment by DaveCTurner** [comment]
Ugh that must mean we're throwing exceptions from `onResponse()` 😢

**Review by DaveCTurner — APPROVED** [review]
Ok LGTM then

**Comment by original-brownbear** [comment]
Yea sadly we are throwing `onResponse` here and there :/ 

Thanks for the review though :)

**Pull request merged**
