### PR TITLE
Benchmark ShardsAvailabilityHealthIndicatorService#calculate

### PR DESCRIPTION
**Pull request by andreidan**
This adds a jmh benchmark track for the `calculate` method of the 
`shards_availability` indicator.

The test sets up all the shards in the cluster to be unassigned with the 
`UnassignedInfo.AllocationStatus.DECIDERS_NO` reason so each shard is diagnosed 
by the `shards_availability` indicator using the allocation deciders explanations.

Results ( score is average time / op in millis - low is better) : 
```
Benchmark                                                            (indicesShardsReplicasNodes)  Mode  Cnt     Score    Error  Units
ShardsAvailabilityHealthIndicatorBenchmark.measureCalculate       10000|        1|        0|    3  avgt   30   118.698 ±  1.685  ms/op
ShardsAvailabilityHealthIndicatorBenchmark.measureCalculate       20000|        1|        0|    3  avgt   30   239.981 ±  2.856  ms/op
ShardsAvailabilityHealthIndicatorBenchmark.measureCalculate       50000|        1|        0|    3  avgt   30   598.845 ±  1.919  ms/op
ShardsAvailabilityHealthIndicatorBenchmark.measureCalculate       100000|       1|        0|    3  avgt   30  1236.756 ±  3.938  ms/op
ShardsAvailabilityHealthIndicatorBenchmark.measureCalculate       200000|       1|        0|    3  avgt   30  2548.194 ±  8.434  ms/op
ShardsAvailabilityHealthIndicatorBenchmark.measureCalculate       10000|        1|        1|    3  avgt   30   208.038 ±  2.132  ms/op
ShardsAvailabilityHealthIndicatorBenchmark.measureCalculate       20000|        1|        1|    3  avgt   30   428.871 ±  4.952  ms/op
ShardsAvailabilityHealthIndicatorBenchmark.measureCalculate       50000|        1|        1|    3  avgt   30  1098.551 ±  8.853  ms/op
ShardsAvailabilityHealthIndicatorBenchmark.measureCalculate       100000|       1|        1|    3  avgt   30  2199.116 ± 20.421  ms/op
ShardsAvailabilityHealthIndicatorBenchmark.measureCalculate       200000|       1|        1|    3  avgt   30  4504.645 ± 70.244  ms/op
```

I've locally disabled computing the impacts (as it sorts and truncates a large list) and 
ran one track to see the impact:
```
Benchmark                                                            (indicesShardsReplicasNodes)  Mode  Cnt     Score    Error  Units
ShardsAvailabilityHealthIndicatorBenchmark.measureCalculate       200000|       1|        1|    3  avgt   30  2583.231 ± 16.675  ms/op
```

### CODE REVIEW

**Comment by jbaiera** [comment]
Spoke with Andrei separately about the flamegraphs that were produced out of the benchmarking run. It looks like a substantial amount of time for the indicator is spent formatting text in the allocation decider API. I opened https://github.com/elastic/elasticsearch/issues/91167 to discuss some options for making the explain API faster to use.

**Comment by andreidan** [comment]
@elasticmachine update branch

**Comment by gmarouli** [comment]
Hi Andrei, thank you for setting this up in this way so we can reproduce easily! Awesome. Do I understand correctly that all the shards are unassigned?

**Comment by andreidan** [comment]
>Do I understand correctly that all the shards are unassigned?

@gmarouli yes

**Review by gmarouli — APPROVED** [review]
LGTM and I learnt a lot reading it, thank you @andreidan . Would you mind adding a small description of how you set-up the test? I think the set-up of a benchmark is very important so a small description can help onboarding someone.

(Apologies it took me so long to review, it fell through the cracks)

**Comment by andreidan** [comment]
@gmarouli Thanks for the review.

> I think the set-up of a benchmark is very important so a small description can help onboarding someone.

By `set-up` you mean running the benchmark? 

If so I used this to run:
```
./gradlew -p benchmarks run --args 'ShardsAvailabilityHealthIndicatorBenchmark'
```

and this to profile:
```
./gradlew -p benchmarks run --args 'ShardsAvailabilityHealthIndicatorBenchmark -prof "async:libPath=/Users/andrei/opt/async-profiler-2.8.3-macos/build/libasyncProfiler.so;output=collapsed"'
```

We have a comprehensive README on everything running/profiling jmh benchmarks in the `benchmarks` module https://github.com/elastic/elasticsearch/blob/main/benchmarks/README.md

**Comment by andreidan** [comment]
> https://github.com/elastic/elasticsearch/pull/91161#issuecomment-1308481908

Updated the description with the data set-up information the benchmark uses

**Pull request merged**
