### PR TITLE
[8.16] Bool query early termination should also consider must_not clauses (#115031)

### PR DESCRIPTION
**Pull request by piergm**
# Backport

This will backport the following commits from `main` to `8.16`:
 - [Bool query early termination should also consider must_not clauses (#115031)](https://github.com/elastic/elasticsearch/pull/115031)

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

### CODE REVIEW

**Comment by piergm** [comment]
@andreidan I think we have to backport this in order for your other change (https://github.com/elastic/elasticsearch/issues/114910) to work properly even with must_not clauses, right?!

**Comment by andreidan** [comment]
@piergm we don't have to as the branch that will catch my scenario is https://github.com/elastic/elasticsearch/pull/115067/files#diff-44c0badcce0e5ccaebd9bf9b3a86e8b69a3e9d72d94083ecd4abcaf9f6f75ba7R367

Even so, I don't think this hurts to be backported to 8.16

**Comment by piergm** [comment]
@elasticsearchmachine test this

**Comment by piergm** [comment]
@elasticmachine update branch

**Pull request merged**
