### PR TITLE
Add setting to disable read statistics in SharedBytes

### PR DESCRIPTION
**Pull request by original-brownbear**
With recent optimizations the stats tracking for `mmap=true` instances becomes a non-trivial overhead for reads that don't page-fault, taking about 25% of the read wall clock time in this method according to profiling.

As a side note: I think it is generally rather questionable to track the read-bytes number, it doesn't really help much with understanding query performance due to the fact that cache misses are as expensive as they are. I can not recall a single instance of having looked at this number for the frozen tier when investigating its performance.

### CODE REVIEW

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/part-1 (unrelated + known)

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/part-1 (unrelated + known)

**Comment by original-brownbear** [comment]
@elasticmachine update branch

**Comment by original-brownbear** [comment]
@henningandersen we discussed this yesterday, this is the one statistic that really hurts in the real world, this does away with that problem, wdyt?

**Review by JVerwolf — APPROVED** [review]
LGTM

**Review by henningandersen — APPROVED** [review]
LGTM.

I suppose the intention is to then disable this in serverless when using mmap?

I sort of agree that it is not a very interesting number, but it would be nice to find a way to track it still (seems like a pretty core io-stat and could be interesting relative to amount of "search activity"). But we can look at that later, no need to do so now.

**Comment by original-brownbear** [comment]
Thanks both!

> I suppose the intention is to then disable this in serverless when using mmap?

Yea exactly :)

**Pull request merged**
