### PR TITLE
[DOCS] Clarify support for run as in OIDC realms

### PR DESCRIPTION
**Pull request by lcawl**
This PR updates the list of realms in https://www.elastic.co/guide/en/elasticsearch/reference/current/run-as-privilege.html#run-as-privilege to clarify that you cannot use the "run as" feature in OpenID Connect realms.

### Preview

https://elasticsearch_60246.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/run-as-privilege.html

### CODE REVIEW

**Review by ywangd — APPROVED** [review]
LGTM.

I wonder whether we should clarify this feature further. When user A run-as (impersonate) user B, the two users can from the same realm or different realms. Let's say user A's realm is the source realm and user B's realm is the target realm. The support for `run-as` feature is mostly concerned of the target realm. That is, if the target realm is one of kerberos, odic, pki or saml, `run-as` is not supported regardless of which realm that user A is from. 

But if the target realm is native, file, ldap, or ad, it is actually possible to use `run-as` from source realm pki and kerberos. The oidc and saml is a bit different in that you cannot directly issue `run-as` to elasticsearch with user credentials. The authentication process gives back the user a token, which can then be used for `run-as`.

**Comment by lcawl** [comment]
> I wonder whether we should clarify this feature further...The support for `run-as` feature is mostly concerned of the target realm. 

Thanks @ywangd , I've changed the first sentence of the second paragraph to try to make that clearer.  If you think I should go into deeper details, please just let me know!

**Comment by ywangd** [comment]
Thanks @lcawl The new changes read better for me.

**Comment by lcawl** [comment]
@elasticmachine update branch

**Pull request merged**
