### PR TITLE
Remove leftover code from one shard by default

### PR DESCRIPTION
**Pull request by jasontedor**
We had some logic to determine the number of shards, it was based on the index version created. Now that master would only ever see index versions created >= 7.0.0, this logic is no longer needed. This commit removes this dead code.

Relates #38556

### CODE REVIEW

**Comment by jasontedor** [comment]
@elasticmachine test this please

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by jasontedor** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by jasontedor** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by jasontedor** [comment]
@elasticmachine run elasticsearch-ci/1

**Pull request merged**
