### PR TITLE
Fix shard typo in IndicesService

### PR DESCRIPTION
**Pull request by howardhuanghua**
Fix shard typo in IndicesService.

### CODE REVIEW

**Review by cbuescher — APPROVED** [review]
LGTM

**Comment by cbuescher** [comment]
@elasticmachine test this please

**Comment by howardhuanghua** [comment]
Master has been merged, thank you. @cbuescher

**Comment by cbuescher** [comment]
@elasticmachine test this please

**Review by MrHeer — APPROVED** [review]

**Pull request merged**
