### PR TITLE
Downgrade the bundled JDK to JDK 21.0.2

### PR DESCRIPTION
**Pull request by ChrisHegarty**
This commit downgrades the bundled JDK to JDK 21.0.2.

The downgrade is necessary to avoid a serious JDK bug, details of which can be see in #106987. The changes in this PR are an effective revert of the upgrade in #106482.

While it's been possible to workaround JDK / JVM bugs in the past, I see not possible workaround for this particular issue, therefore downgrade is the only option. :-(

### CODE REVIEW

**Comment by ChrisHegarty** [comment]
@elasticmachine update branch

**Review by breskeby — APPROVED** [review]
lgtm.

**Review by mark-vieira — APPROVED** [review]

**Comment by mark-vieira** [comment]
@ChrisHegarty Java 22.0.1 is out. Does this include a fix for the underlying bug? Should we upgrade again?

**Comment by mark-vieira** [comment]
Looking at the [JDK bug report](https://bugs.openjdk.org/browse/JDK-8329528) looks like it was backported, but the fix didn't make it into 22.0.1 so we'll have to wait until 22.0.2.

**Comment by ChrisHegarty** [comment]
> Looking at the [JDK bug report](https://bugs.openjdk.org/browse/JDK-8329528) looks like it was backported, but the fix didn't make it into 22.0.1 so we'll have to wait until 22.0.2.

Correct. The fix will be in 22.0.2. 

I would like for us to get onto 22.0.1. We can do so if we set a couple of JVM flags to workaround the issue. See [107980](https://github.com/elastic/elasticsearch/issues/107980)

**Comment by mark-vieira** [comment]
We would want to figure this out quickly if we want to get this in for 8.14.

**Comment by ChrisHegarty** [comment]
> We would want to figure this out quickly if we want to get this in for 8.14.

I think that it's too late for 814. Probably best to just get it into _main_, and let it bake there until 8.15.

**Comment by ChrisHegarty** [comment]
With the workaround for the G1 bug [merged](https://github.com/elastic/elasticsearch/pull/108571), how do folks feel about bumping to JDK 22.0.1? @mark-vieira @rjernst

**Comment by ChrisHegarty** [comment]
Bumping to JDK 22 again (#108654)

**Pull request merged**
