### PR TITLE
Disallow identical `dynamic_templates` definitions

### LINKED ISSUE #28988: Dynamic templates should be deduplicated
**Bug Report / Feature request**:

Check for identical entries in the list of dynamic templates and deduplicate or reject them to avoid bloating.

**Describe the issue**:

It is currently possible to have the same dynamic template definition appended multiple times in the dynamic templates list of a mapping or a template, which can result to significant performance degradation.

See example [template](https://github.com/elastic/elasticsearch/files/1802117/Metricbeat_template.gz) of an actual problematic 300.000 lines+ configuration installed in a cluster due to a repetition when putting the dynamic templates. This eventually resulted in a slowdown, tasks piling up, causing rejected bulks etc.

**Elasticsearch version**: issue exists up to current - 6.2.2

**Steps to reproduce**:

PUT the same dynamic template definition multiple times when defining a mapping or a template:

```
PUT my_index
{
  "mappings": {
    "_doc": {
      "dynamic_templates": [
        {
          "docker.container.labels": {
            "mapping": {
              "type": "keyword"
            },
            "match_mapping_type": "string",
            "path_match": "docker.container.labels.*"
          }
        },
        {
          "docker.container.labels": {
            "mapping": {
              "type": "keyword"
            },
            "match_mapping_type": "string",
            "path_match": "docker.container.labels.*"
          }
        }
      ]
    }
  }
}
```

### PR DESCRIPTION
**Pull request by cbuescher**
Currently the same dynamic_templates can be defined more than once by error in
the same mappings file. This most certainly is unintentional and can create
issues like those reported in #28988. This change checks for identical duplicates 
while parsing and throws an error if we encounter the same definition twice.

Closes #28988

### CODE REVIEW

**Comment by cbuescher** [comment]
@jtibshirani after your comments on #51817 I marked the original issue for discussion but thought it wouldn't hurt to open this PR as another proposal. I think we can safely disallow definitions that are entirely identical, which we should be able to check at parsing time. The examples given in https://github.com/elastic/elasticsearch/issues/29200#issuecomment-534028143 wouldn't be affected by these checks. Let me know what you think...

**Comment by cbuescher** [comment]
@elasticmachine update branch

**Comment by jtibshirani** [comment]
Thanks @cbuescher, it's nice to know this option is possible. I'll wait to do a detailed review until we discuss #28988.

**Comment by cbuescher** [comment]
Superseded by #53326

**Pull request closed without merging**
