### PR TITLE
ESQL: Array blocks backed by vecs

### PR DESCRIPTION
**Pull request by alex-spies**
Back every block type by a vector for consistency.

This will allow for simple implementations of expand and filter by simply sharing the (refcounted) vector contained in a block.

Relates https://github.com/elastic/elasticsearch/issues/100528

### CODE REVIEW

**Review by nik9000 — COMMENTED** [review]
This makes sense to me. I haven't traced all of the memory accounting, but assuming that works and the perf tests are ok with it I'm happy.

**Comment by ChrisHegarty** [comment]
> This makes sense to me. I haven't traced all of the memory accounting, but assuming that works and the perf tests are ok with it I'm happy.

++

**Comment by alex-spies** [comment]
Alright, took care of the memory accounting and the tests seem to be happy now.

Ran a subset of the block access benchmark with a low number of repetitions to get some numbers already. (Will re-run full bench over night.)

For comparison, take a look at [a previous benchmark run here](https://github.com/elastic/elasticsearch/pull/102872#issuecomment-1864160686).

Nothing points to a performance degradation IMO (note that I have don't have a dedicated, non-noisy machine so minor differences are to be expected).

```
Result "org.elasticsearch.benchmark.compute.operator.BlockBenchmark.run":
  1.340 ±(99.9%) 0.028 ns/op [Average]
  (min, avg, max) = (1.334, 1.340, 1.345), stdev = 0.004
  CI (99.9%): [1.311, 1.368] (assumes normal distribution)


# Run complete. Total time: 00:10:12

REMEMBER: The numbers below are just data. To gain reusable insights, you need to follow up on
why the numbers are the way they are. Use profilers (see -prof, -lprof), design factorial
experiments, perform baseline and negative tests that provide experimental control, make sure
the benchmarking environment is safe on JVM/OS/HW level, ask for reviews from the domain experts.
Do not assume the numbers tell you what you want them to tell.

Benchmark           (accessType)            (dataTypeAndBlockKind)  Mode  Cnt  Score   Error  Units
BlockBenchmark.run    sequential                    BytesRef/array  avgt    4  9.122 ± 0.132  ns/op
BlockBenchmark.run    sequential    BytesRef/array-multivalue-null  avgt    4  7.124 ± 0.160  ns/op
BlockBenchmark.run    sequential                      double/array  avgt    4  1.246 ± 0.043  ns/op
BlockBenchmark.run    sequential      double/array-multivalue-null  avgt    4  0.916 ± 0.436  ns/op
BlockBenchmark.run    sequential                  double/big-array  avgt    4  2.498 ± 0.044  ns/op
BlockBenchmark.run    sequential  double/big-array-multivalue-null  avgt    4  1.399 ± 0.037  ns/op
BlockBenchmark.run    sequential                         int/array  avgt    4  1.374 ± 0.076  ns/op
BlockBenchmark.run    sequential         int/array-multivalue-null  avgt    4  0.768 ± 0.041  ns/op
BlockBenchmark.run    sequential                     int/big-array  avgt    4  2.595 ± 0.062  ns/op
BlockBenchmark.run    sequential     int/big-array-multivalue-null  avgt    4  1.340 ± 0.028  ns/op
```

**Comment by dnhatn** [comment]
I'm okay with this change, but could we use the refCount of the block for filter and expand instead? I feel this PR might be heading in the opposite direction of your previous PR, which removed the enclosing VectorBlock in Vector due to ownership concerns. Anyway, please proceed with merging this PR if Nik or Chris approves. If you don't mind, I would recommend to include this change in the filter or expand work to show a full picture. Thanks, Alex!

**Comment by alex-spies** [comment]
Benchmark results are in:
```
Result "org.elasticsearch.benchmark.compute.operator.BlockBenchmark.run":
  2.163 ±(99.9%) 0.509 ns/op [Average]
  (min, avg, max) = (1.974, 2.163, 2.404), stdev = 0.226
  CI (99.9%): [1.654, 2.672] (assumes normal distribution)


# Run complete. Total time: 02:07:11

REMEMBER: The numbers below are just data. To gain reusable insights, you need to follow up on
why the numbers are the way they are. Use profilers (see -prof, -lprof), design factorial
experiments, perform baseline and negative tests that provide experimental control, make sure
the benchmarking environment is safe on JVM/OS/HW level, ask for reviews from the domain experts.
Do not assume the numbers tell you what you want them to tell.

Benchmark           (accessType)             (dataTypeAndBlockKind)  Mode  Cnt   Score   Error  Units
BlockBenchmark.run    sequential                      boolean/array  avgt    7   1.431 ± 0.015  ns/op
BlockBenchmark.run    sequential      boolean/array-multivalue-null  avgt    7   0.834 ± 0.002  ns/op
BlockBenchmark.run    sequential                  boolean/big-array  avgt    7   1.973 ± 0.007  ns/op
BlockBenchmark.run    sequential  boolean/big-array-multivalue-null  avgt    7   1.305 ± 0.005  ns/op
BlockBenchmark.run    sequential                     boolean/vector  avgt    7   2.331 ± 0.423  ns/op
BlockBenchmark.run    sequential           boolean/vector-big-array  avgt    7   3.265 ± 0.005  ns/op
BlockBenchmark.run    sequential               boolean/vector-const  avgt    7   1.985 ± 0.527  ns/op
BlockBenchmark.run    sequential                     BytesRef/array  avgt    7   8.780 ± 0.080  ns/op
BlockBenchmark.run    sequential     BytesRef/array-multivalue-null  avgt    7   6.652 ± 0.040  ns/op
BlockBenchmark.run    sequential                    BytesRef/vector  avgt    7   7.534 ± 0.028  ns/op
BlockBenchmark.run    sequential              BytesRef/vector-const  avgt    7   2.918 ± 0.024  ns/op
BlockBenchmark.run    sequential                       double/array  avgt    7   1.224 ± 0.006  ns/op
BlockBenchmark.run    sequential       double/array-multivalue-null  avgt    7   0.874 ± 0.010  ns/op
BlockBenchmark.run    sequential                   double/big-array  avgt    7   2.449 ± 0.150  ns/op
BlockBenchmark.run    sequential   double/big-array-multivalue-null  avgt    7   1.364 ± 0.015  ns/op
BlockBenchmark.run    sequential                      double/vector  avgt    7   2.283 ± 0.365  ns/op
BlockBenchmark.run    sequential            double/vector-big-array  avgt    7   3.101 ± 0.013  ns/op
BlockBenchmark.run    sequential                double/vector-const  avgt    7   2.139 ± 0.505  ns/op
BlockBenchmark.run    sequential                          int/array  avgt    7   1.322 ± 0.016  ns/op
BlockBenchmark.run    sequential          int/array-multivalue-null  avgt    7   0.727 ± 0.002  ns/op
BlockBenchmark.run    sequential                      int/big-array  avgt    7   2.546 ± 0.088  ns/op
BlockBenchmark.run    sequential      int/big-array-multivalue-null  avgt    7   1.301 ± 0.087  ns/op
BlockBenchmark.run    sequential                         int/vector  avgt    7   2.304 ± 0.488  ns/op
BlockBenchmark.run    sequential               int/vector-big-array  avgt    7   3.067 ± 0.011  ns/op
BlockBenchmark.run    sequential                   int/vector-const  avgt    7   2.251 ± 0.299  ns/op
BlockBenchmark.run    sequential                         long/array  avgt    7   1.356 ± 0.044  ns/op
BlockBenchmark.run    sequential         long/array-multivalue-null  avgt    7   0.843 ± 0.005  ns/op
BlockBenchmark.run    sequential                     long/big-array  avgt    7   2.469 ± 0.012  ns/op
BlockBenchmark.run    sequential     long/big-array-multivalue-null  avgt    7   1.322 ± 0.029  ns/op
BlockBenchmark.run    sequential                        long/vector  avgt    7   2.288 ± 0.555  ns/op
BlockBenchmark.run    sequential              long/vector-big-array  avgt    7   3.076 ± 0.013  ns/op
BlockBenchmark.run    sequential                  long/vector-const  avgt    7   2.151 ± 0.507  ns/op
BlockBenchmark.run        random                      boolean/array  avgt    7   1.490 ± 0.006  ns/op
BlockBenchmark.run        random      boolean/array-multivalue-null  avgt    7   0.855 ± 0.002  ns/op
BlockBenchmark.run        random                  boolean/big-array  avgt    7   1.990 ± 0.013  ns/op
BlockBenchmark.run        random  boolean/big-array-multivalue-null  avgt    7   1.756 ± 0.192  ns/op
BlockBenchmark.run        random                     boolean/vector  avgt    7   2.402 ± 0.312  ns/op
BlockBenchmark.run        random           boolean/vector-big-array  avgt    7   3.283 ± 0.016  ns/op
BlockBenchmark.run        random               boolean/vector-const  avgt    7   1.998 ± 0.541  ns/op
BlockBenchmark.run        random                     BytesRef/array  avgt    7  11.100 ± 0.045  ns/op
BlockBenchmark.run        random     BytesRef/array-multivalue-null  avgt    7   7.501 ± 0.044  ns/op
BlockBenchmark.run        random                    BytesRef/vector  avgt    7   9.049 ± 0.053  ns/op
BlockBenchmark.run        random              BytesRef/vector-const  avgt    7   3.001 ± 0.009  ns/op
BlockBenchmark.run        random                       double/array  avgt    7   1.808 ± 0.022  ns/op
BlockBenchmark.run        random                   double/big-array  avgt    7   3.248 ± 0.020  ns/op
BlockBenchmark.run        random   double/big-array-multivalue-null  avgt    7   1.670 ± 0.018  ns/op
BlockBenchmark.run        random                      double/vector  avgt    7   2.962 ± 0.008  ns/op
BlockBenchmark.run        random            double/vector-big-array  avgt    7   3.980 ± 0.029  ns/op
BlockBenchmark.run        random                double/vector-const  avgt    7   2.156 ± 0.511  ns/op
BlockBenchmark.run        random                          int/array  avgt    7   1.598 ± 0.013  ns/op
BlockBenchmark.run        random          int/array-multivalue-null  avgt    7   0.864 ± 0.002  ns/op
BlockBenchmark.run        random                      int/big-array  avgt    7   2.903 ± 0.012  ns/op
BlockBenchmark.run        random      int/big-array-multivalue-null  avgt    7   1.477 ± 0.031  ns/op
BlockBenchmark.run        random                         int/vector  avgt    7   2.535 ± 0.137  ns/op
BlockBenchmark.run        random               int/vector-big-array  avgt    7   3.413 ± 0.010  ns/op
BlockBenchmark.run        random                   int/vector-const  avgt    7   2.245 ± 0.247  ns/op
BlockBenchmark.run        random                         long/array  avgt    7   1.943 ± 0.009  ns/op
BlockBenchmark.run        random         long/array-multivalue-null  avgt    7   1.101 ± 0.005  ns/op
BlockBenchmark.run        random                     long/big-array  avgt    7   3.295 ± 0.010  ns/op
BlockBenchmark.run        random     long/big-array-multivalue-null  avgt    7   1.673 ± 0.037  ns/op
BlockBenchmark.run        random                        long/vector  avgt    7   2.959 ± 0.007  ns/op
BlockBenchmark.run        random              long/vector-big-array  avgt    7   3.990 ± 0.012  ns/op
BlockBenchmark.run        random                  long/vector-const  avgt    7   2.163 ± 0.509  ns/op
```

These all look in-line with the previous [benchmark run](https://github.com/elastic/elasticsearch/pull/102872#issuecomment-1864160686).

Note that the `double/array-multivalue-null` type is missing for the `random` access - benchmark run errored due to non-matching checksums, I'm pretty sure due to a rounding error which I'll fix soon.

**Comment by alex-spies** [comment]
> I'm okay with this change, but could we use the refCount of the block for filter and expand instead? I feel this PR might be heading in the opposite direction of your previous PR, which removed the enclosing VectorBlock in Vector due to ownership concerns. Anyway, please proceed with merging this PR if Nik or Chris approves. If you don't mind, I would recommend to include this change in the filter or expand work to show a full picture. Thanks, Alex!

Thanks for the feedback, @dnhatn !

I can happily add the implementation for `expand` to this to give a more complete picture. Filtering is a bit more involved, so I'd like to do this in a follow-up PR after the holidays.

I would prefer not to rely on the blocks' refCounts for a couple of reasons:
- It's not optimal in terms of memory usage; if I start with a block with a lot of multivalues, then expand and/or filter, I need to keep the initial block around (together with its `firstValues` array and nulls mask) even though I _really_ only need the block's array. This is not a problem if we share the underlying array instead, which requires this PR.
- We would either have to have additional block types, like the nested `X-ArrayBlock.Expanded` (my first attempt from[ this PR](https://github.com/elastic/elasticsearch/pull/102776)), or somehow alter existing blocks - giving them a reference to an existing block and make them access it rather than using an own `values` array or vector. What makes it even more complicated is that a blocks values can be represented in different ways (array, vector, bigarray) and each of these would require an additional implementation for the expanded/filtered case, either in the form of a separate class or additional complexity in the existing classes.
- I think sharing the vector models blocks in the most natural way: block = an array + extra info for multivalues + extra info for nulls. When expanding, the extra info for multivalues/nulls is no longer relevant for the new block and the same is true when filtering.

I understand that having multiple levels of refcounting adds some complexity as well - but that can still be remedied by removing the refcount on blocks if we really want to, as the refcount on vectors should be sufficient.

All in all I think this approach provides the simplest solution.

**Comment by dnhatn** [comment]
@alex-spies Thank you for the explanation. Does that mean we need to have separate `firstValues` and `nullMask` for filtered or expanded blocks? As I mentioned before, I am fine with this change if Nik or Chris is okay with it.

**Comment by alex-spies** [comment]
@dnhatn , I implemented expand without deep copies based on this [PR here](https://github.com/elastic/elasticsearch/pull/103681/files/d499f9f474ed6762363f5c47526137a8001d3067..863ee96e7f39dd5da214cf021d06bfc1119336c9).

I think this is a nice and simple change; in contrast, my [first attempt](https://github.com/elastic/elasticsearch/pull/102776) introduced new block types and is already quite involved. That other approach would also require additional tests (even basic stuff like `equals` and `hashCode` would need to be tested again for the `Expanded` blocks), an implementation for the big array blocks - and a very good look at the benchmarks to  make sure access performance doesn't degrade due to megamorphic calls.

**Comment by alex-spies** [comment]
> @alex-spies Thank you for the explanation. Does that mean we need to have separate `firstValues` and `nullMask` for filtered or expanded blocks? As I mentioned before, I am fine with this change if Nik or Chris is okay with it.

For expanded blocks where the original block had nulls, a new null mask is strictly necessary unless we want to compute it on each look up. The first values array becomes obsolete.

For filtered blocks, we may or may not want to keep the original first values array and nulls mask around; one option for implementation would be to re-compute both, so the first values indexes points only to the values we filtered for - in this case, we'd again only need to share the `values` array (resp. vector with this PR).

**Review by ChrisHegarty — APPROVED** [review]
LGTM

**Comment by alex-spies** [comment]
Thanks for the reviews @ChrisHegarty, @dnhatn and @nik9000 !

**Pull request merged**
