### PR TITLE
Remove role mapping block check

### PR DESCRIPTION
**Pull request by n1v0lg**
This method is used in multiple contexts that may not all handle cluster-block exceptions gracefully, esp. since some types of cluster blocks are retryable. Removing this, and may follow up with handling the cluster state block for the affected transport actions instead.

### CODE REVIEW

**Comment by n1v0lg** [comment]
@elasticmachine update branch

**Review by jfreden — APPROVED** [review]
LGTM!

**Comment by n1v0lg** [comment]
@elasticmachine update branch

**Comment by n1v0lg** [comment]
@elasticmachine update branch

**Pull request merged**
