### PR TITLE
Upgrade 6.x to lucene-7.6.0-snapshot-f9598f335b

### PR DESCRIPTION
**Pull request by nknize**
This PR upgrades the 6.x branch to lucene-7.6.0-snapshot-f9598f335b to expose latest BKD backed geoshape improvements.

### CODE REVIEW

**Review by dnhatn — APPROVED** [review]
LGTM.

**Comment by dnhatn** [comment]
It looks like we pulled this in too earlier. We need to upgrade the master first. The BWC build is failing. I will look into this and revert this commit if required.

```
Caused by: org.apache.lucene.index.IndexFormatTooNewException: Format version is not supported (resource BufferedChecksumIndexInput(MMapIndexInput(path="/var/lib/jenkins/workspace/elastic+elasticsearch+master+default-distro-bwc-tests/qa/full-cluster-restart/build/cluster/v6.6.0#oldClusterTestCluster node0/elasticsearch-6.6.0-SNAPSHOT/data/nodes/0/indices/MBIt9YH4Rk--ijCSQbb8Pw/1/index/_0.cfs") [slice=_0.fnm])): 2 (needs to be between 0 and 1)
```

**Comment by dnhatn** [comment]
@nknize I have to revert this commit in 6.x as BWC build is failing. Please re-commit after we upgraded a new Lucene snapshot into the master (https://github.com/elastic/elasticsearch/pull/35224). Thank you!

**Comment by nknize** [comment]
Hrm.. no worries and thx @dnhatn  I reopen a PR after we merge #35224

**Pull request merged**
