### PR TITLE
Plugins: Changing staging property to be the hash instead of a boolean

### PR DESCRIPTION
**Pull request by rjernst**
With the unified release, we will have staged releases based on a
unified hash (hash of all the hashes), so using the elasticsearch hash
for plugins staging will no longer work. This change makes the
`es.plugins.staging` property take the staging hash it should use.

### CODE REVIEW

**Comment by jasontedor** [comment]
LGTM.

**Comment by jasontedor** [comment]
There are a few places where this used so needs to be updated: `prepare_release_candidate.py` and `smoke_test_rc.py`

**Comment by rjernst** [comment]
I pushed an update for `smoke_test_rc.py`. `prepare_release_candidate.py` is not currently used and will be going away soon.

**Comment by jasontedor** [comment]
LGTM.

**Pull request merged**
