### PR TITLE
Add REST API for Painless suggestions

### PR DESCRIPTION
**Pull request by jdconrad**
This adds a new REST action endpoint using /_scripts/painless/_suggestions to support auto-complete for Painless.

The request body supports the standard script notation with source, lang, and params (though lang and params are ignored). and optionally a context to determine what is available for suggestion.

The response is a list of suggestion objects containing type (variable, method, field, etc.) and text for the full completion suggestion.

This API will offer context-sensitive suggestions with the limitation that it cannot fully resolve expressions.

It will offer suggestions for the following script:
```
List test = new ArrayList(); test.
```
where it will suggest all the methods/fields available as part of `List`.

It cannot offer suggestions for the following scripts:
```
List test = new ArrayList(); ((ArrayList)test).
(2 + 2).
```
because it does not process the cast or the addition operator.

### CODE REVIEW

**Comment by jdconrad** [comment]
@ywangd I've added a new REST API endpoint for Painless suggestions here. It's intended to be internal, but should not be restricted from anywhere as it should never be an unsafe operation. I've added this to non-operational constants and was hoping you would be able to confirm if this is the correct thing to do. Thanks!

**Comment by jdconrad** [comment]
@stu-elastic This is ready for review when you have time to take a look. Please ignore the generated ANTLR code for the lexer. I had to create a new lexer specifically for suggestions as it's much easier to parse type as a lexer token than hand-parse this in our state machines. Thanks!

**Comment by ywangd** [comment]
> @ywangd I've added a new REST API endpoint for Painless suggestions here. It's intended to be internal, but should not be restricted from anywhere as it should never be an unsafe operation. I've added this to non-operational constants and was hoping you would be able to confirm if this is the correct thing to do. Thanks!

@jdconrad Thanks for the ping. Based on your description of the API, I think it is OK to have it in the non-operator list, i.e. it does not need to be reserved for the Cloud infrastructure code. That said, I am not really the gatekeeper of this list. I am happy to provide the context about the operator privileges feature. But ultimately it is the developer who owns the specific feature knows the best about the nature of the APIs and is qualified to make the decision.

**Comment by jdconrad** [comment]
Our approach to this needs to be re-evaluated. Closing this for now.

**Pull request closed without merging**
