### PR TITLE
Update to AWS SDK 1.11.223

### PR DESCRIPTION
**Pull request by tlrx**
This pull request updates the version of the AWS SDK dependency used by the `repository-s3` plugin. The current version is old and many bugs have been fixed since 1.10.69.

### CODE REVIEW

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by jasontedor** [comment]
If CI is happy, I'm happy.

**Comment by dadoonet** [comment]
Although not really the same purpose, should we close then #25552 in favor of this one?

**Comment by tlrx** [comment]
Thanks @jasontedor ! I plan to backport this to 6.0.1 and 5.6.5 at the same time as #27280.

> Although not really the same purpose, should we close then #25552 in favor of this one?

I don't think it must be closed. Instead it should be rebased and tests for ECS Task Roles must be added.

**Comment by jasontedor** [comment]
@tlrx When you backport this to the 6.0 branch, can you also backport #27361? And if you backport this to the 5.6 branch, can you take #27361 there too?

**Comment by tlrx** [comment]
This change has been backported to 5.6.5, 6.0.1, 6.1.0 and master.

**Pull request merged**
