### PR TITLE
Remove auto_configure privilege for profiling

### PR DESCRIPTION
**Pull request by danielmitterdorfer**
With this commit we remove the `auto_configure` privilege for the Fleet service account that targets profiling-related indices. This privilege was needed to automatically create indices and data streams in the past but as this managed by the Elasticsearch plugin, there is no need to grant this privilege to Fleet-managed components.

### CODE REVIEW

**Comment by danielmitterdorfer** [comment]
This is a known test failure, see https://github.com/elastic/elasticsearch/issues/100502 which should be addressed by https://github.com/elastic/elasticsearch/pull/101006. We will wait triggering further CI builds until that PR is merged but the test failure is clearly unrelated to this PR.

**Comment by danielmitterdorfer** [comment]
@elasticmachine merge upstream

**Review by albertzaharovits — APPROVED** [review]
LGTM
Thanks for retracting the privilege!
Have you thought about mixed versions scenarios, where an old component (fleet server maybe) might try to create the index the old way (not using the plugin) using the new credential from this PR?

**Comment by danielmitterdorfer** [comment]
>  Have you thought about mixed versions scenarios, where an old component (fleet server maybe) might try to create the index the old way (not using the plugin) using the new credential from this PR?

Thanks for the feedback. We have changed the behavior with https://github.com/elastic/elasticsearch/pull/96268, which is available since 8.9.0 and went GA in 8.10.0. Upgrades from the beta phase to a GA version are not supported (unless users delete all data and start from scratch) so that scenario should not affect us.

**Pull request merged**
