### PR TITLE
Fix some issues developing Elasticsearch with Eclipse

### PR DESCRIPTION
**Pull request by nik9000**
1. Fix importing Elasticsearch into eclipse with `mvn eclipse:clean && mvn eclipse:eclipse`. It was creating projects with the same name which Eclipse was less than happy with.
2. Fix the launch script. It was failing on the security manager among other things. This disables the security manager when launching Elasticsearch using the pre-packaged launch configuration. We can re-enable it later. I just wanted to get it working again because it can really speed development in some areas.

### CODE REVIEW

**Comment by dadoonet** [comment]
LGTM

**Comment by dadoonet** [comment]
Don't you think you should backport it in 2.0 BTW?

**Comment by nik9000** [comment]
> Don't you think you should backport it in 2.0 BTW?

That is probably a good idea, yeah. The issue comes up in 2.0, certainly.

**Comment by nik9000** [comment]
Merged into 2.0 and master.

**Pull request merged**
