### PR TITLE
[Synonyms] Mark Synonyms as GA

### PR DESCRIPTION
**Pull request by kderusso**
Removes the beta flag from Synonyms docs and json definitions, marking the synonyms API as GA.

### CODE REVIEW

**Review by carlosdelest — APPROVED** [review]
💯

**Review by carlosdelest — COMMENTED** [review]
Should making this feature GA have a changelog / release note added to it? @abdonpijpelink, is there anything else we need to provide as part of this?

**Comment by abdonpijpelink** [comment]
You can consider making this a release highlight. Here's a similar recent example: https://github.com/elastic/elasticsearch/pull/95398/files

Note the `release highlight` label and the yaml file with the `highlight` section. That translate into a highlight like this: https://www.elastic.co/guide/en/elasticsearch/reference/8.8/release-highlights.html#ga_release_of_jwt_realm

**Review by Mikep86 — APPROVED** [review]
LGTM

**Comment by kderusso** [comment]
@elasticmachine update branch

**Comment by kderusso** [comment]
@elasticmachine update branch

**Pull request merged**
