### PR TITLE
[ML] Assert that a no-op job creates no results nor state

### PR DESCRIPTION
**Pull request by droberts195**
If a job is opened and then closed and does nothing in
between then it should not persist any results or state
documents. This change adapts the no-op job test to
assert no results in addition to no state, and to log
any documents that cause this assertion to fail.

Relates elastic/ml-cpp#512
Relates #43680

### CODE REVIEW

**Comment by droberts195** [comment]
Note that the PR CI will fail until both elastic/ml-cpp#512 and #43680 are merged.  I will update this PR when those are merged, but wanted to raise this one now so that I can reference it.

**Comment by droberts195** [comment]
Jenkins run elasticsearch-ci/default-distro

**Comment by benwtrent** [comment]
run elasticsearch-ci/2

**Comment by droberts195** [comment]
Jenkins run elasticsearch-ci/2

**Review by edsavage — APPROVED** [review]
LGTM

**Comment by droberts195** [comment]
Jenkins run elasticsearch-ci/bwc

**Pull request merged**
