### PR TITLE
Tests: Move naming convention tests to a test case, so plugins can have the same convention checks

### PR DESCRIPTION
**Pull request by rjernst**
The current plugin setup uses the same test pattern rules we have in
elasticsearch (at least by default). Yet they don't check naming
conventions, so failures can pop up if naming conventions change, and
tests simply start failing. This change makes the naming convention
checks available to plugins that use the test jar.

### CODE REVIEW

**Comment by jpountz** [comment]
LGTM

**Comment by jpountz** [comment]
@rjernst any reason not to merge?

**Comment by nik9000** [comment]
++ This has been on my whiteboard for forever but I've just not done it.

**Comment by rjernst** [comment]
@jpountz @nik9000 I've had this PR sitting here for quite a while, but I'm not sure what to do with it. I have 2 problems with it:

1. It still requires work from end users (ie other plugins in ES) to trigger. I would be much happier if we automatically set up such a test, otherwise the usefulness is lessened and we might miss it on new plugins.
2. The existing rules are really for ES core, which are *not* the same as plugins. In plugins, all tests, even ones that extend ESIntegTestCase, are named with the Tests suffix.

**Comment by nik9000** [comment]
> It still requires work from end users (ie other plugins in ES) to trigger. I would be much happier if we automatically set up such a test, otherwise the usefulness is lessened and we might miss it on new plugins.

I wonder if you can sneak it into the test list somehow or execute this test in its own phase.

> The existing rules are really for ES core, which are not the same as plugins. In plugins, all tests, even ones that extend ESIntegTestCase, are named with the Tests suffix.

I think the right thing to do here is just make it optional and turn it on in our build.gradle file.

And, yeah, I think we should just do this in master so we don't have to solve the problem twice.

**Comment by rjernst** [comment]
I agree we can sneak it in via gradle for executing, that is doable. But I dont want to make it just optional. It is already confusing that currently tests in plugins that extend ESIntegTestCase end with Tests, but those in core must end in IT. I think we should add another task, which is the same as what core currently has for "integTest" which runs the ESIntegTestCase tests. I'm not sure what to call it, or how we should name tests to distinguish them. It's possible we could use a `*RestIT` pattern for rest integ tests. I prefer to call the ESIntegTestCase tests task something like `fantasyTest` as this is a fantasy land of all nodes running in the same jvm. :)

**Comment by nik9000** [comment]
> I think we should add another task, which is the same as what core currently has for "integTest" which runs the ESIntegTestCase tests.

I agree. I think if we're going to make a new phase we should make `restTest` let the `integTest` be the phase in which we run stuff that extends from ESIntegTestCase. I'm all for removing the funky "your allowed to extends from ESIntegTest in plugins" rule entirely.

The thing I wanted to make optional is running the naming rules entirely. We should enable them everywhere but I don't think its our place to force plugin developers to use our (pretty sane but arbitrary) naming conventions. PluginBuildPlugin shouldn't force them to do it, I mean.

**Comment by rmuir** [comment]
Well if its a separate task, then isn't it still optional by definition? `separateTask.enabled = false`

**Comment by rjernst** [comment]
> PluginBuildPlugin shouldn't force them to do it, I mean

Except if we don't force it, tests will not be run. The naming conventions are there so we don't (and so a plugin author would not) unknowingly skip a test simply because it didn't match the pattern the test runner uses.

**Comment by rjernst** [comment]
I also don't like renaming the real integ tests to `restTest`, because they are the real integ tests! Plus eg we have client tests which are not really rest tests, and may not even use the rest test plugin in the future, but should still be considered integTests. Really the integ tests in core are the thing that aren't really testing integration.

**Comment by rjernst** [comment]
@rmuir's point about a separate task is valid too. If we move this to a gradle task, a user can disable it like any other precommit check, just like today they can disable eg the license check if they don't want to follow our license rules.

**Comment by rjernst** [comment]
@nik9000 what do you think about `distributedTest` and renaming `ESIntegTestCase` to `ESDistributedTestCase`? I think it makes it more clear that the point of those tests are really for distributed logic, and eg mappings tests should be written with them.

**Comment by nik9000** [comment]
> Well if its a separate task, then isn't it still optional by definition? separateTask.enabled = false

Good point.

> If we move this to a gradle task, a user can disable it like any other precommit check, just like today they can disable eg the license check if they don't want to follow our license rules.

Sold. If its a gradle task then it can even be "UP-TO-DATE" which is cool.

> I also don't like renaming the real integ tests to restTest, because they are the real integ tests!

It makes a certain kind of sense to call the classes that extend ESIntegTest "mock tests" because they are allowed spin up a cluster with test mocks whereas the REST tests need to deal with Elasticsearch as packaged. They are also allowed to "reach into" the running test cluster and extract anything registered in guice which is pretty funky. So I guess I'm convinced that we should leave the REST tests in `integTest` and I'm proposing that we move the ESIntegTests to `mockTest`. BTW I love that this is possible in gradle.

I'd be quite happy if we could write some tests in java that dealt with elasticsearch the same way the rest tests deal with it - as a black box. I miss loops and other niceties when I write REST tests. It'd give us a way to transition some of the mock tests to more real black box tests. I like that rest tests can be shared and I like that we actually use REST rather than the java Client, though. If only we had a java client that spoke REST.....

**Comment by nik9000** [comment]
> @nik9000 what do you think about distributedTest and renaming ESIntegTestCase to ESDistributedTestCase?

Sorry, I missed that while I was typing my other reply. I still like `mockTest` better because it better lines up with what fixtures are needed to run the tests.

**Comment by s1monw** [comment]
can this test basically be a regular expression of some sort  `class *IT extends (*IT | ESIntegTest)` and `class *Tests extends *Tests|EsTestCase)` I think if we could do that we can simply run a pre-build step like forbidden APIs? Maybe I am missing something?

**Comment by rjernst** [comment]
I don't think we need regexes, we can look at the .class files and determine if a test class follows the rules. The question is what to call this 3rd type of test, since today we overload IT to be both ESIntegTestCase, as well as ESRestTestCase.

**Comment by rjernst** [comment]
This has been superseded by the work in #16811.

**Pull request closed without merging**
