### PR TITLE
Parse aliases at search time and never cache parsed alias filters

### PR DESCRIPTION
**Pull request by martijnvg**
This cleans up the alias code. The time spend on alias filter parsing is significantly lower compared to the execution time of a search request. Pre parsing alias filters and caching the parsed version at alias creation time isn't worth the effort (code complexity and memory).

Also:
- This allows parent/child queries to be specified again in alias filters.
- The work around for resolving `now` in queries doesn't need to be used for aliases, becuase alias filters are parsed at search time. However it can't be removed, because the percolator relies on it.

PR for #10485

### CODE REVIEW

**Comment by clintongormley** [comment]
@jpountz please could you review

**Comment by jpountz** [comment]
Just discussed it with @martijnvg. With this pull request, we make use of two hacks in order to make sure that the parsed filter is what we expect:
 - new flags on QueryParseContext
 - build a first "dummy" query that only rewrites to the correct query

I like parsing aliases filters as late as possible, but I'm not happy with having both these hacks. It seems to me that we could make things work without adding more methods to QueryParseContext and just use the same rewrite hack that we use for date range queries.

**Comment by martijnvg** [comment]
@jpountz I updated the PR and used the dummy query hack in all places where last minute query parsing needs to happen.

**Comment by jpountz** [comment]
LGTM

**Pull request merged**
