### PR TITLE
speedup verifying index output

### PR DESCRIPTION
**Pull request by rhluo**
The LuceneVerifyingIndexOutput implementation has been used in some very important functions, such as PeerRecovery, CCR and Snapshot. The feature will be helpful to speedup the file chunk write process when there are a lot of small files to be recovery or restored. The Comparison Experimentation Based on NIO FS show that the speedup is 10 times. 

     * Comparison Experimentation
     * Before optimization: write times 10000, total cost time: 270827ms, avg cost time: 27.0827ms
     * After optimization: write times 10000, total cost time: 11603ms, avg cost time: 1.1603ms

### CODE REVIEW

**Review by DaveCTurner — CHANGES_REQUESTED** [review]
This seems like somewhere we could improve indeed. I don't think the proposed change is correct however, because `b[offset + i]` does not account for the bytes that were directly written. It does not pass `./gradlew :server:test` for me.

But also I don't see a great reason to write the checksum byte-by-byte either. Can we just rework this to always call `out.writeBytes()` and handle parts of the footer checksum on both paths?

**Review by DaveCTurner — CHANGES_REQUESTED** [review]
Also this is based off a commit from `main` that's a couple of months old, and does not merge cleanly with current `main`. You'll need to do something like `git fetch upstream && git merge upstream/main` and then fix up the errors that `./gradlew precommit` shows

**Comment by rhluo** [comment]
>

**Comment by rhluo** [comment]
> 

Thanks for your suggestion, I think your thinking is writeBytes no need call writeByte to implement footer check, writeBytes just solve the checksum itself is better. I agree with you, I will try in this solution.

**Comment by rhluo** [comment]
@DaveCTurner Thanks for your suggestion, I think your thinking is writeBytes no need call writeByte to implement footer check, writeBytes just solve the checksum itself is better. I agree with you, I will try in this solution.

**Comment by DaveCTurner** [comment]
Thanks @rhluo - I opened https://github.com/elastic/elasticsearch/issues/96614 to track this area of work.

**Pull request closed without merging**
