### PR TITLE
Deprecate _suggest endpoint

### PR DESCRIPTION
**Pull request by areek**
In 5.0, we optimize for suggest-only search requests meaning
using suggest API via _suggest endpoint has the same performance
implication as using _search endpoint with only suggest.

This commit deprecates _suggest endpoint in favour of using suggest API
via _search endpoint. Now the response from _suggest endpoint is identical
to response of a suggest-only search request.

### CODE REVIEW

**Comment by nik9000** [comment]
@areek what is the status on this? I'm happy to review it if you still want to get it in, but it'd have to wait for 5.1/6.0 I think?

**Comment by nik9000** [comment]
If you like to get it in would you like to rebase and resolve conflicts and force push? Then I can review?

**Comment by clintongormley** [comment]
@areek ping?

**Comment by areek** [comment]
@nik9000 sorry for the delay here, could you take a look please? Note that the result of the `_suggest` endpoint now is the same as a suggest-only `_search` api call. This might not be acceptable for 5.x but we can still push it to master and backport the change to 5.x ensuring the `_suggest` result to be same as today?

**Review by nik9000 — APPROVED** [review]
Code looks fine to me.

As far as I see we have three options:
1. Add a breaking changes note to this and merge this only to 6.0. That means that we'll remove support for `_suggest` in 7.0.
2. Merge this to 6.0 and merge a deprecation warning to 5.x. We'll still need a breaking changes note because we changed the output of the API.
3. Throw this away entirely and merge a deprecation for the suggest API into 5.x. Remove support for `_suggest` entirely in 6.0.

All of these work for me because we've already optimized the `_search` API when we're using it in suggest-only mode in 5.0. So we can push people to that in the 5.x branch.

**Comment by clintongormley** [comment]
I didn't quite follow some of @nik9000's options, so here is what i'd like:

* The `_suggest` response should not change in 5.x
* Add deprecation logging to the `_suggest` endpoint now, if we don't have it already.
* The suggest-only search optimization can go in immediately if it hasn't done so already.
* The _suggest endpoint can be removed in 6.0

**Comment by nik9000** [comment]
@clintongormley that was my option number 3 but much more clear. Thanks.

**Comment by areek** [comment]
@nik9000, I agree your number 3.
As @clintongormley suggested, Here is what I plan on doing:
 - change all docs examples to use `_search` api rather than `_suggest` in 5.x, 6 (https://github.com/elastic/elasticsearch/pull/20305)
 - add deprecation logging to `_suggest` in 5.x and remove `_suggest` entirely in 6

> The suggest-only search optimization can go in immediately if it hasn't done so already.

this is already merged to 5.x

**Comment by nik9000** [comment]
Should we close this entirely then? You can deprecate against the 5.x branch without doing the merging and you can remove entirely in master. I think.

**Comment by areek** [comment]
@nik9000 I will close this one, the plan is:
  - add the deprecation logging for 5.x in https://github.com/elastic/elasticsearch/pull/20305
  - then remove the suggest endpoint entirely from 6.0 in a separate PR. 
WDYT?

**Comment by nik9000** [comment]
Makes sense to me.

**Pull request closed without merging**
