### PR TITLE
Fixed references to Multi Index Syntax

### PR DESCRIPTION
**Pull request by shubham391**

### CODE REVIEW

**Comment by sunkuet02** [comment]
I think doc is fine in master branch. This PR should be close.

**Comment by shubham391** [comment]
@sunkuet02 It is not. The change (if accepted) should be applied in master well. Maybe you should check once before downvoting.

**Comment by sunkuet02** [comment]
@shubham391 Sorry, if I hurts you. Please check the link : https://www.elastic.co/guide/en/elasticsearch/reference/master/search-search.html#search-multi-index-type make sure, your changes work. Did you check by generating html from asciidoc ?

**Comment by karmi** [comment]
Hi @shubham391, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/elasticsearch/pull/26956.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by shubham391** [comment]
@karmi The email address in the commit is provided by Github (due to the privacy option enabled on my account). I'm not sure if I can add it to the profile as such (got an error while trying to do so). I have now disabled the privacy option so at least one of the email will be visible to you. Or if there's any other way to validate, please let me know.

**Comment by karmi** [comment]
Hi @shubham391, you don't have to make the e-mail with which you have signed the CLA public at Github, just _add_ it to your Github account and that should be enough for us to match it with your Github profile.

**Comment by javanna** [comment]
hi @shubham391 your change is good and we do need it also in master. Thanks for sending a PR! The 5.0 branch is no longer under active development though, could you please send this PR against master instead? Thank you! I am closing this as we won't merge it in 5.0.

**Comment by shubham391** [comment]
@javanna Thanks. Created a PR against master: https://github.com/elastic/elasticsearch/pull/27283

**Pull request closed without merging**
