### PR TITLE
Upgrade Apache Commons Logging to 1.2

### LINKED ISSUE #40305: Update commons-logging to 1.2
Would be nice if we can upgrade `commons-logging` library.

```
compile group: 'commons-logging', name: 'commons-logging', version: '1.2'
```

Asking that because I have a project which depends on `rest-client:7.0.0-beta1` which is using `commons-logging:1.1.3`.
Of course I can definitely solve the problem on my end but that'd be nice if we can depend on the latest versions (1.2 was released in Jul 05, 2014).

```
Dependency convergence error for commons-logging:commons-logging:1.1.3 paths to dependency are:
+-fr.pilato.elasticsearch.crawler:fscrawler-elasticsearch-client-v7:2.7-SNAPSHOT
  +-org.elasticsearch.client:elasticsearch-rest-high-level-client:7.0.0-beta1
    +-org.elasticsearch.client:elasticsearch-rest-client:7.0.0-beta1
      +-commons-logging:commons-logging:1.1.3
and
+-fr.pilato.elasticsearch.crawler:fscrawler-elasticsearch-client-v7:2.7-SNAPSHOT
  +-fr.pilato.elasticsearch.crawler:fscrawler-framework:2.7-SNAPSHOT
    +-org.apache.logging.log4j:log4j-jcl:2.11.2
      +-commons-logging:commons-logging:1.2
```

### PR DESCRIPTION
**Pull request by yrodiere**
Fixes #40305

### CODE REVIEW

**Comment by yrodiere** [comment]
I just rebased on `main` again.

**Comment by yrodiere** [comment]
Hey @dadoonet , since you're the one who created https://github.com/elastic/elasticsearch/issues/40305, do you think you could have a look and approve the pull request, or suggest how to get someone to have a look? It's been a few months and this PR doesn't seem to spark much interest :)

**Comment by williamrandolph** [comment]
@yrodiere I'm sorry for the oversight! I will route this to someone who can evaluate the change.

**Comment by williamrandolph** [comment]
@elasticmachine ok to test

**Review by breskeby — CHANGES_REQUESTED** [review]
Hey @yrodiere,
thanks for your PR. Can you rebase it again against latest main? We changed our verification mechanism for third party dependencies lately to rely on gradles own dependency metadata verification. This basically means we track sha256 checksums in `gradle/verification-metadata.xml` instead of all these `.*sha1` files. Sorry again for the inconveniences. 
If you don't have the bandwidth to follow up just let me know

**Comment by yrodiere** [comment]
Hey @breskeby , done.

**Review by williamrandolph — APPROVED** [review]
This looks good to me, but I will let @breskeby take another look before we merge.

Thanks for working through these changes with us, @yrodiere.

**Review by breskeby — APPROVED** [review]
@yrodiere looks good to me. thank you for your patience and taking the time to rebase again

**Pull request merged**
