### PR TITLE
Remove Cluster & XPack clients from HLRC (#83423)

### PR DESCRIPTION
**Pull request by gmarouli**

### CODE REVIEW

**Review by dakrone — APPROVED** [review]
LGTM assuming CI is happy, thanks Mary!

**Review by dakrone — APPROVED** [review]
LGTM, thanks Mary!

**Comment by dakrone** [comment]
Oh hah, I liked this PR so much I reviewed it twice, whoops!

**Comment by gmarouli** [comment]
> Oh hah, I liked this PR so much I reviewed it twice, whoops!

I share the excitement, I got to see a bit more of the clients and the tests, it was a good opportunity! Also, cleaning code like this is sooooo awesome! It might be counter intuitive for the people that see developers as code producing machines but it makes total sense in reality ;). 

I am working on tests, 2 failures were my fault. I think I fixed it but let's see.

**Pull request merged**
