### PR TITLE
Introduce authorization for enrich in ESQL

### LINKED ISSUE #98482: Security privileges for ESQL Enrich
Filing this issue to track a question/comment that was raised by @ywangd  here https://github.com/elastic/elasticsearch/pull/98309#discussion_r1294115440

One question I do have is why we chose to [execute the LookupRequest with the enrich origin](https://github.com/elastic/elasticsearch/blob/2e4440ff1c0decf79f8a40688566411f7d518aa7/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/enrich/EnrichLookupService.java#L141C2-L141C2). It means the following query works when the user has access to only the playlist index without access to either the songs enrich policy or its associated index.

```
FROM playlist | ENRICH songs ON song_id
```

It feels a bit weird to me that we have no control on who can use what enrich process. That said, we don't have a good story around enrich and ingest pipeline either, i.e. we have no control over who can use what pipeline where a pipeline can contain an enrich processor. There have been quite a few complaints from users and we have an https://github.com/elastic/elasticsearch/issues/57586 for it. I wonder whether we should not repeat the problem here with ES|QL. On the surface, it might be easier to tackle compared to ingest pipelines since ES|QL is read-only and has no "bulk" operations. What do you think?

### PR DESCRIPTION
**Pull request by dnhatn**
This change introduces a new privilege `monitor_enrich`. Users are required to have this privilege in order to use the enrich functionality in ESQL. Additionally, it eliminates the need to use the `enrich_origin` when executing enrich lookups. The `enrich_origin` will only be used when resolving enrich policies to prevent warnings when accessing system indices directly.

Closes #98482

### CODE REVIEW

**Comment by ywangd** [comment]
@dnhatn I am no longer on the security team. So I'll ping @jakelandis for a formal review.

Briefly looking through the changes, I think the general approach makes sense to me. We might need to tweak exactly what privilege is required for resolving the enrich policy. Right now it is `monitor` which feels a bit off to me. Existing `manage_enrich` cluster privilege does not seem to fit either. We might need add a new and more specific read level cluster privilege for this purpose. That said, I'll defer to Jake for concrete suggestions. Thanks!

**Comment by dnhatn** [comment]
@ywangd No problem. Thank you for taking a look. I've requested @jakelandis to take a look at the PR.

**Comment by tvernum** [comment]
@jakelandis If I understand your comment correctly, I think you might have been mislead by the name of the index in the tests.

`test-enrich` is a [normal index,](https://github.com/elastic/elasticsearch/pull/99646/files#diff-2a2742f4edb51f606a43b463079785ed6c33fbe9295fa03b04fb5db758d544f6L121-L123) that is used as part of the testing of the enrichment command. 
The [enrich index](https://github.com/dnhatn/elasticsearch/blob/b73cc0c52987b759b9091c1f0d423417e66b3811/x-pack/plugin/esql/qa/security/src/javaRestTest/java/org/elasticsearch/xpack/esql/EsqlSecurityIT.java#L170-L172) and [policy](https://github.com/dnhatn/elasticsearch/blob/b73cc0c52987b759b9091c1f0d423417e66b3811/x-pack/plugin/esql/qa/security/src/javaRestTest/java/org/elasticsearch/xpack/esql/EsqlSecurityIT.java#L199) are called `songs`.

So the [ES|QL command](https://github.com/dnhatn/elasticsearch/blob/b73cc0c52987b759b9091c1f0d423417e66b3811/x-pack/plugin/esql/qa/security/src/javaRestTest/java/org/elasticsearch/xpack/esql/EsqlSecurityIT.java#L155-L158) is
 ```
FROM test-enrich | ENRICH songs ON song_id | stats total_duration = sum(duration) by artist | sort artist
```

Which (more or less) translates to

1. Read from the `test-enrich` index
2. Apply the `song` enrich policy to it, joining on `song_id`
3. sum duration by artist
4. sort by artist

The security change is in how step 2 is applied.
- Previously every user would be able to perform the enrich step (against any policy).
- After this change, the ability to perform an ES|QL enrich is restricted by a cluster privilege (currently proposed to be`monitor`, but I agree that it's not a great fit). No specific index level privilege is required.
 
The change to the security setup in [`roles.yml`](https://github.com/elastic/elasticsearch/pull/99646/files#diff-8a910e8c6948e5a5ef7b21556051cdbf9c66ae806892b28d030935c825cb7332) consists of
1. Granting `monitor` to the existing user (`user1`) who should be allowed to perform enrich (and previously could because no privilege was required)
2. Creating a read-only user (`user4`) who should be allowed to run the ES|QL command. (This is helpful because `user1` has additional privileges and we'd like to know that the command works without `write` etc).
3. Creating another read-only user (`user5`) who does not have `monitor` and, therefore, should **not** be allowed to run the ES|QL command. 

None of those users have access to anything named `songs` (neither the source index, nor the enrich policy). This works because the action is `cluster:monitor/esql/resolve_enrich`, so it is authorized as a cluster monitor action.
It's not really an "action" though  - it's all handled as a lightweight [transport request handler](https://github.com/elastic/elasticsearch/pull/99646/files#diff-fcfda3dfbdf0dbe1c2e9e30c6ab46e9ca53e770405a40f20cb1a5815cadce14dR47-R52) inside EnrichPolicyResolver.

Interestingly, despite the PR description, the actual enrichment still happens using the enrich origin which explains why it works
- https://github.com/elastic/elasticsearch/blob/672258b0ef8f6da25596533bbc7e724731442878/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/enrich/EnrichPolicyResolver.java#L114-L122

As @dnhatn  has indicated, the ideal outcome would be to have a way to limit which enrich polices a user may use within ES|QL. It looks like we could probably do that with a `ConfigurableClusterPrivilege` if we wanted. It would require a little bit of rework of this PR (e.g. extracting a `EnrichPolicyRequest` interface), but I can't see any technical reason why it couldn't be done.

**Comment by dnhatn** [comment]
@jakelandis @tvernum Thank you so much for looking.

Tim has summarized this perfectly. In the enrich lookup in ESQL, there are two actions:

1. **Resolve enrich policy:**
Action (cluster:monitor/esql/resolve_enrich): This action doesn't access its Lucene index but only the enrich policies in the cluster state and its index metadata via the field-caps API. Previously, this action didn't require any access permission, meaning any user could access the enrich policies. This PR now requires users to have a 'monitor' permission to perform this step. We can consider introducing a new privilege for enrich-policy-read. Another question is how to integrate this privilege with the enrich ingest without causing any breaking changes. We will still perform the resolution of enrich policies under the 'enrich_origin' to avoid deprecation warnings when accessing the system indices directly.

2. **Lookup enrich data:**
Action (indices:data/read/esql/lookup): This action accesses the Lucene index and performs the actual enrich. This action requires the user to have the index-read permission for the enrich index. This action will no longer execute under the 'enrich_origin' after this PR.


I believe we don't require any extra privilege for ingest-enrich.

**Comment by jakelandis** [comment]
> Do I understand this correctly ?

...no I did not. Thanks Tim and Nhat for the clarifications. One last clarification:

> This action (indices:data/read/esql/lookup) requires the user to have the index-read permission for the enrich index. 

You mean the index being enriched... right ? The enrich index is defined [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/ingest-enriching-data.html) as "A special system index tied to a specific enrich policy". Sorry to be pedantic, but confusing the security requirements of two was the source of my original confusion.  

Assuming we are all on the same page... The only relevant part of the original comment are :

> Ideally we would have a permission model for enrich that is applicable to both ESQL, ingest nodes, and policy execution  

While ideal that would be quite involved. An implementation with `ConfigurableClusterPrivilege` could set us on that path but we would probably want to flesh out the requirements more and consider other options. However, I do think the simpler cluster wide approach is viable and (with a correct understanding of the change) is in line with the existing model even it is not terribly flexible/expressive. 

>   I also have concerns w.r.t. normal users that just want to do some queries needing the cluster:monitor privilege

While it possible to configure a role with the string  `cluster:monitor/esql/resolve_enrich` we generally discourage this (except for tightly controlled internal usecases) since we consider those names implementation details. In practice we would advocate to use the named privileges such as 'monitor' .. as already mentioned that is likely too wide for this usecase. Can we use an ESQL specific named privilege... or change the action name to 'cluster:monitor/xpack/enrich/esql/resolve_enrich` and introduce a `monitor_enrich` with a pattern of `cluster:monitor/xpack/enrich/*` which would also include the ability to read enrich stats. There is always a friction between grouping raw privileges into named privileges lower vs. least privileges. I would advocate for use an EQSL name if you think there will be more than just 1 in the near future, else I would advocate to group in with a new 'monitor_enrich'.

**Comment by dnhatn** [comment]
>  Can we use an ESQL specific named privilege... or change the action name to 'cluster:monitor/xpack/enrich/esql/resolve_enrich` and introduce a `monitor_enrich` with a pattern of `cluster:monitor/xpack/enrich/*` which would also include the ability to read enrich stats.

@jakelandis Thanks so much for your suggestion. It makes sense to me. I will update this PR to introduce a new privilege.

**Comment by dnhatn** [comment]
@jakelandis I've introduced the `monitor_enrich` privilege as you suggested in https://github.com/elastic/elasticsearch/pull/99646/commits/216d267aca73c7ffd9b70798a0b09b5ca3ea1c50. I should have also introduced `enrich_user` but we already have it for `manage_enrich`. Would you please take another look? Thank you!

**Review by jakelandis — APPROVED** [review]
LGTM - however, can you update the doc [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-privileges.html) either as part of this PR or as a followup. 

Thanks again for clarifications and apologies for the noise.

**Comment by dnhatn** [comment]
@jakelandis Thank you for the review + suggestion :).

> however, can you update the doc [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-privileges.html) either as part of this PR or as a followup.

Sure, I will do this in a follow-up.

**Pull request merged**
