### PR TITLE
Fix performance regression caused by cancellation check in vector scripts

### PR DESCRIPTION
**Pull request by benwtrent**
When adding KNN query cancellation in https://github.com/elastic/elasticsearch/pull/90612 it initially checked for query cancellation on every vector value read. 

Vector queries are unique as they go through every matched document without any chance of cancelling early. So, for this specific rally track (10m vectors), cancellation was checked a total of 10,010,000 times. Consequently adding between 30ms - 40ms overhead (or between 12%-20% slow down).

Removing the check on EVERY vector read, but only doing it every 1,000 docs (reducing the number of total checks within the rally track to 10,000), the performance overhead is much more acceptable (see numbers below). 

We can further reduce the impact by increasing the number of documents between checks, but this will reduce the liveliness of cancellation. The impact seems acceptable here and it would be prudent to see how it reacts in the nightly rally build.

# Numbers on M1 mac using Rally track `dense_vector`

Without cancellation:

```
|   50th percentile latency |  script-score-query |  177.911       |     ms |
|   90th percentile latency |  script-score-query |  180.882       |     ms |
|   99th percentile latency |  script-score-query |  199.417       |     ms |
|   100th percentile latency | script-score-query |  202.873       |     ms |
```

With cancellation as implemented in #90612 
```
|   50th percentile latency |  script-score-query |  212.705       |     ms |
|   90th percentile latency |  script-score-query |  220.576       |     ms |
|   99th percentile latency |  script-score-query |  223.889       |     ms |
|   100th percentile latency | script-score-query |  246.995       |     ms |
```

Cancellation implementation when not checking every vector read (This PR):
```
|   50th percentile latency |  script-score-query |  178.852       |     ms |
|   90th percentile latency |  script-score-query |  182.044       |     ms |
|   99th percentile latency |  script-score-query |  203.226       |     ms |
|   100th percentile latency | script-score-query |  214.671       |     ms |
```

### CODE REVIEW

**Review by jtibshirani — COMMENTED** [review]
This makes sense to me, great we tracked down the source of the slowdown. We should also fix this in Lucene, since this class is supposed to be a copy of Lucene's `ExitableDirectoryReader`. It might even be best to do that first, in case there are comments on the Lucene PR about the approach (which we'll want to reflect here).

I also looked at `ExitableVectorValues` more carefully, and noticed we do the checking based on doc ID, versus number of documents checked so far:

```
        private void checkAndThrowWithSampling(int nextDoc) {
            if (nextDoc >= docToCheck) {
                this.queryCancellation.checkCancelled();
                docToCheck = nextDoc + DOCS_BETWEEN_TIMEOUT_CHECK;
            }
        }
```

This seems off to me. Let's say there's an index with 10 million docs and you have a filter that matches 0.1% of documents (instead of using `match_all` like we do here). Then we'd check cancellation roughly every 10th doc. Maybe we should address this too?

**Comment by benwtrent** [comment]
@jtibshirani 

For our performance observations, sure, I can open a PR there first and see what folks say about cancellation liveliness (as that would be the only concern I can think of with removing these checks)



As for `DOCS_BETWEEN_TIMEOUT_CHECK` vs. an actual count, there is prior art within Lucene.
Example:

https://github.com/apache/lucene/blob/4c434b70892c1a66634841f7d5800ec99d6ba54f/lucene/core/src/java/org/apache/lucene/index/ExitableDirectoryReader.java#L111

But, none of our other exitable readers follow this pattern. Instead it is a raw count. So, I am happy to change that here.

**Comment by benwtrent** [comment]
Switched to checking every `8191` calls (number used by other cancellation checks). 

Here are the numbers:
```
| 50th percentile latency | script-score-query |  179.526       |     ms |
| 90th percentile latency | script-score-query |  180.417       |     ms |
| 99th percentile latency | script-score-query |  193.57        |     ms |
|100th percentile latency | script-score-query |  205.468       |     ms |
```

Everything looks pretty much the same except for the higher percentile latencies. Much more inline with what we are expecting without checking for cancellation.

**Review by jtibshirani — APPROVED** [review]
This makes sense to me. It matches the approach in `ExitablePointTree` too.

**Pull request merged**
