### PR TITLE
Typo in x-pack template for thread_pool.management

### PR DESCRIPTION
**Pull request by theredcat**
Fix a typo in x-pack template for the node_stats.thread_pool.management

### CODE REVIEW

**Comment by nik9000** [comment]
@elasticmachine test this please.

**Comment by nik9000** [comment]
It certainly looks like a typo. I wonder why the tests haven't picked it up.....

**Comment by theredcat** [comment]
@nik9000 This is the document in the .monitoring indices 
```json
      {
        "_index": ".monitoring-es-6-2018.10.02",
        "_type": "doc",
        "_id": "...",
        "_score": 1,
        "_source": {
          [...]
          "node_stats": {
            [...]
            "thread_pool": {
              [...]
              "management": {
                "threads": 5,
                "queue": 0,
                "rejected": 0
              },
              [...]
            },
            [...]
        }
      }
```

**Comment by nik9000** [comment]
@elasticmachine, test this please.

**Review by pickypg — APPROVED** [review]
LGTM. Good catch.

**Comment by pickypg** [comment]
> It certainly looks like a typo. I wonder why the tests haven't picked it up.

We do test that this field is returned by the appropriate API call, but we aren't checking that that field is indexed by searching / aggregating on it.

**Comment by nik9000** [comment]
Ok! So I'm going to merge this soon and backport it. But there are some sneaky things going on here:
* We only update the template when there is a "version" bump to it. You can see the version at the top.
* So just updating this file won't fix the template in the system, except
* We've already bumped the version for the 6.x and master branches
* So I can just merge this as is to those branches and it'll "just work"
* This won't fix old indexes full of monitoring data

**Comment by nik9000** [comment]
I've merged master into this PR which should make it more likely the tests will pass.

@elasticmachine, test this please.

**Comment by nik9000** [comment]
@elasticmachine, now that I've merged master, test this please

**Comment by theredcat** [comment]
@nik9000 You're welcome ! Thanks for your reactivity :)

**Pull request merged**
