### PR TITLE
[ML] Move datafeed stats action off of master node

### PR DESCRIPTION
**Pull request by droberts195**
Previously the get datafeed stats action was handled on the
master node. This dated back to the time when datafeed configs
were stored in the cluster state. Now that the action consists
of running a series of searches it can be a handled transport
action.

### CODE REVIEW

**Comment by droberts195** [comment]
Jenkins run elasticsearch-ci/bwc

**Comment by droberts195** [comment]
Jenkins run elasticsearch-ci/bwc

**Comment by droberts195** [comment]
Jenkins run elasticsearch-ci/bwc

**Review by benwtrent — APPROVED** [review]
This is a prudent change. The key will be making sure in a mixed cluster environment all is fine.

++ from me

**Pull request merged**
