### PR TITLE
replacing "\_none_" to correct "_none_"

### PR DESCRIPTION
**Pull request by githubfromgui**

### CODE REVIEW

**Review by cbuescher — CHANGES_REQUESTED** [review]
@githubfromgui so you found those two as well after the last PR ;-) (I opened https://github.com/elastic/elasticsearch/pull/41295 when I found these remaining places after your last pr)
I'm fine merging your PR, but could you merge the two you have open into one to backporting is easier?

**Comment by githubfromgui** [comment]
@cbuescher like that? :)

**Review by cbuescher — APPROVED** [review]
@githubfromgui exactly, thanks. I will close the other PRs and get this one in.

**Comment by cbuescher** [comment]
@elasticmachine test this please

**Pull request merged**
