### PR TITLE
Remove use of AbstractComponent in server

### PR DESCRIPTION
**Pull request by gavlyukovskiy**
Removed extending of AbstractComponent and changed logger usage to
explicit declaration. Abstract classes still have logger
declaration using this.getClass() in order to show implementation class
name in the logs.

See #34488

### CODE REVIEW

**Comment by dliappis** [comment]
cc @nik9000

**Review by nik9000 — APPROVED** [review]
The change looks good to me. I'll kick off a CI job for it once our intake builds have calmed down.

**Comment by nik9000** [comment]
@elasticmachine, test this please

**Comment by nik9000** [comment]
@elasticmachine, test this please

**Comment by nik9000** [comment]
@gavlyukovskiy, the integration test failure looks to have been caused by us bumping the version after releasing 6.5.0. I've merged master into your branch and restarted the build.

**Comment by nik9000** [comment]
Thanks @gavlyukovskiy! I've merged and am backporting now.

**Pull request merged**
