### PR TITLE
Fix double rounding errors for disk usage

### PR DESCRIPTION
**Pull request by kingherc**
Fix double rounding errors for disk usage

### CODE REVIEW

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Comment by kingherc** [comment]
> LGTM

@DaveCTurner you're quick :D thanks! Will try to see if I can carve out more PRs

**Comment by kingherc** [comment]
@elasticsearchmachine changelog

**Comment by kingherc** [comment]
@elasticmachine please add a changelog YAML

**Comment by kingherc** [comment]
Oh as a non-issue, it does not need a changelog YAML. Will just merge it then.

**Comment by DaveCTurner** [comment]
++ yes sorry I thought @elasticmachine was just being slow. I'm pretty sure this is a non-issue anyway, it's definitely true that `a*(b*c) != (a*b)*c` for doubles but I don't think they're meaningfully different here.

**Pull request merged**
