### PR TITLE
Log Blocked IO Thread State

### PR DESCRIPTION
**Pull request by original-brownbear**
* Let's log the state of the thread to find out if it's dead-locked on some system monitor or just stuck after being suspended
* Relates #43392

### CODE REVIEW

**Review by ywelsch — APPROVED** [review]
LGTM

**Comment by henningandersen** [comment]
@original-brownbear thanks for adding this, I added the 7.2.1 label for this since I think this could be beneficial in debugging #24457 too.

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/bwc

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/default-distro

**Pull request merged**
