### PR TITLE
[ML] Pass the randomize_seed DFA parameter to the native code

### PR DESCRIPTION
**Pull request by valeriy42**
We pass the `randomize_seed` configuration parameter for DFA jobs to the native code to ensure the reproducibility of test results.

### CODE REVIEW

**Comment by valeriy42** [comment]
retest

**Comment by valeriy42** [comment]
test

**Comment by valeriy42** [comment]
retest

**Comment by valeriy42** [comment]
retest please

**Comment by valeriy42** [comment]
retest this please

**Comment by valeriy42** [comment]
retest this please

**Comment by valeriy42** [comment]
retest this please

**Comment by davidkyle** [comment]
@elasticsearchmachine update branch

**Review by droberts195 — APPROVED** [review]
LGTM

I think you will need to merge main into your PR branch again to get CI to pass even though you did this 4 hours ago - different tests are failing now that are due to very recent discrepancies between branches

**Comment by valeriy42** [comment]
@elasticmachine update branch

**Comment by valeriy42** [comment]
@elasticmachine update branch

**Pull request merged**
