### PR TITLE
[DOCS] Fixed wrong link to lucene docs in ‘index-modules-similarity’

### PR DESCRIPTION
**Pull request by Yanx0202**
Fixed two wrong links.

### CODE REVIEW

**Comment by Yanx0202** [comment]
Source: https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-similarity.html#dfr

**Review by lockewritesdocs — APPROVED** [review]
LGTM 👍 Thank you for fixing these links!

**Comment by lockewritesdocs** [comment]
@elasticmachine test this please

**Comment by lockewritesdocs** [comment]
master #59646
7.9 #59645
7.x backport #59644

**Pull request merged**
