### PR TITLE
Deprecate X-Pack centric license endpoints

### PR DESCRIPTION
**Pull request by jasontedor**
This commit is part of our plan to deprecate and ultimately remove the use of _xpack in the REST APIs.

Relates #35958

### CODE REVIEW

**Review by jaymode — APPROVED** [review]
LGTM

**Comment by jasontedor** [comment]
@elasticmachine run gradle build tests 2

**Comment by jasontedor** [comment]
@elasticmachine run oss docs tests

**Comment by jasontedor** [comment]
@elasticmachine run gradle build tests 2

**Pull request merged**
