### PR TITLE
[Fleet] Added read privilege to `kibana_system` to `logs-fleet_server.*` index pattern

### PR DESCRIPTION
**Pull request by juliaElastic**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)? yes
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md)? yes
- If submitting code, have you built your formula locally prior to submission with `gradle check`? yes
- If submitting code, is your pull request against main? Unless there is a good reason otherwise, we prefer pull requests against main and will backport as needed. yes
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)? yes
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

Required for https://github.com/elastic/fleet-server/issues/3116, fleet-server will publish output health status on `logs-fleet_server.output_health-default` data stream, and kibana will read it to display state on UI.

### CODE REVIEW

**Comment by juliaElastic** [comment]
Could someone help how to fix the failing test?

**Review by ldematte — APPROVED** [review]
Provided CI passes, LGTM

**Comment by ldematte** [comment]
At first glance they seem unrelated. I would try to re-run them first.

**Comment by juliaElastic** [comment]
> At first glance they seem unrelated. I would try to re-run them first.

Thanks, triggered a retry.

**Pull request merged**
