### PR TITLE
update ingest-attachment to use Tika 1.17 and newer deps

### PR DESCRIPTION
**Pull request by talevy**
- this pr updates tika and its dependencies
- updates the SHAs
- updates the class excludes

### CODE REVIEW

**Review by jasontedor — APPROVED** [review]
LGTM. If it's green, ship it.

**Comment by dadoonet** [comment]
1.17 has been released. Should we keep us up to date ?

**Comment by talevy** [comment]
@dadoonet woops. I saw it was released on their website, but then used mvnrepository.com to let me know if the sources were actually released, and they weren't there. I didn't dive deeper, that was my mistake. You're right. I will update to 1.17

as a side note... is there a sane way to manage the excluded classes list? I am using editor-magic to merge the exception list thrown by thirdPartyAudit and the existing list, then sorting them. Feels odd.

**Comment by dadoonet** [comment]
About thirdPartyAudit, yeah this a lot of manual work. Didn’t find an easy way for doing it.

**Comment by talevy** [comment]
@dadoonet luckily 1.17 doesn't change much between 1.16... updated to latest

**Review by jasontedor — APPROVED** [review]
Still LGTM.

**Comment by talevy** [comment]
apologies for the extra back-and-forth @jasontedor. I thought I ran `check`, but I only ran `precommit`. 1.17 did actually change behavior. It throws an exception when reading empty files. It did not do this before 😄. I've modified the processor to preserve old behavior...

**Comment by jasontedor** [comment]
Okay, I'll review this change.

**Review by jasontedor — COMMENTED** [review]
Any chance of a test for the zero-byte situation?

**Comment by talevy** [comment]
there is a test, that is what caught the change. it was failing.

**Comment by jasontedor** [comment]
Sorry @talevy, I misunderstood. I found what you're referring to:

```
20:45:34 [jason:~/src/elastic/elasticsearch/plugins/ingest-attachment/src/test] master+ ± find . -size 0
./resources/org/elasticsearch/ingest/attachment/test/sample-files/text-empty.txt
```

I am good with this. Thanks.

**Review by jasontedor — APPROVED** [review]
LGTM. Third time is a charm!

**Comment by tlrx** [comment]
I just backported this to 6.x in 4a8f8873f31c067e6f54b489f783a9ec0914b9bf

**Comment by talevy** [comment]
thanks @tlrx!

**Pull request merged**
