### PR TITLE
[Profiling] Rename profile -> profiling

### PR DESCRIPTION
**Pull request by danielmitterdorfer**
Previously we have used `profile` in the plugin name whereas we have used `profiling` in Java package names. With this commit we align both the module and the package name for consistency.

### CODE REVIEW

**Comment by danielmitterdorfer** [comment]
This is a straightforward renaming of the module without any further changes (except to ensure everything is compiling).

**Review by inge4pres — APPROVED** [review]
Thanks ❤️

**Review by rockdaboot — APPROVED** [review]
:+1:

**Comment by danielmitterdorfer** [comment]
This change will not be backported as https://github.com/elastic/elasticsearch/pull/97763, which relates to this one, is not backported either.

**Pull request merged**
