### PR TITLE
`ObjectParser` : replace `IllegalStateException` with `ParsingException`

### PR DESCRIPTION
**Pull request by olcbean**
Relates to #27147

### CODE REVIEW

**Comment by cbuescher** [comment]
@elasticmachine test this please

**Review by cbuescher — COMMENTED** [review]
@olcbean thanks for this PR, at first glance everything looks fine. CI seems to complain about some unrelated test failre, I think the commit you rebased on is just bad. I hope you don't mind rebasing this on master once again?

**Comment by olcbean** [comment]
@cbuescher just rebased to the current master.

**Comment by cbuescher** [comment]
thanks, @elasticmachine test this please

**Review by cbuescher — APPROVED** [review]
@olcbean thanks, LGTM. I also just checked that ParsingException and the former IllegalStateException have the same http error code. Thanks for the PR, I will merge this shortly

**Pull request merged**
