### PR TITLE
Upgrade to Netty 4.1.42

### PR DESCRIPTION
**Pull request by Tim-Brooks**
Upgrades the netty version.

### CODE REVIEW

**Review by original-brownbear — APPROVED** [review]
LGTM if CI likes it :)

**Comment by tbrooks8** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by tbrooks8** [comment]
@elasticmachine run elasticsearch-ci/2

**Review by jasontedor — APPROVED** [review]
LGTM.

**Pull request merged**
