### PR TITLE
Update alias.asciidoc - remove_index

### PR DESCRIPTION
**Pull request by mimol91**
Update Alias Doc to add remove_index

### CODE REVIEW

**Review by john-wagster — APPROVED** [review]
LGTM

**Comment by john-wagster** [comment]
@elasticmachine test this please

**Comment by john-wagster** [comment]
There's a few things we'll need to do on this one @mimol91.  First can you rebase this on main and update the PR.  And then also because of how the documentation testing works we either need to break this change out (so that in the test it's not deleting the index) or probably the easiest thing to do is to move the new section to the bottom of that page of the documentation so that the last thing to happen is the index gets deleted.  I believe that will make the CI happy (at least worth a shot).

**Comment by john-wagster** [comment]
@elasticmachine test this please

**Comment by mimol91** [comment]
I cannot see CI result.
Is there anything that I can do?

**Comment by john-wagster** [comment]
@elasticmachine test this please

**Comment by john-wagster** [comment]
Let me rerun CI and take a look myself and see if I can help; I'll try to do that today if I can find some time

**Comment by john-wagster** [comment]
ok was able to determine the problem.  The index in your docs update is a protected index name.  We just need to change all references in your addition to a different index name something like `index_to_remove` instead of `logs-nginx.access-prod` (there's two references I believe) and it should pass the CI.  I'm happy to do that and validate it works if you want to give me write access to your branch on your fork or feel free to do that and I'll kick off CI as soon as I see you make the change!  Thanks for being patient with me here.

**Comment by mimol91** [comment]
Thanks for guiding me
Fingers crossed this will work

**Comment by mimol91** [comment]
@elasticmachine test this please

**Comment by john-wagster** [comment]
@elasticmachine test this please

**Comment by john-wagster** [comment]
@elasticmachine test this please

**Comment by john-wagster** [comment]
@elasticmachine update branch

**Comment by john-wagster** [comment]
@elasticmachine test this please

**Pull request merged**
