### PR TITLE
Official Gradle Wrapper Validation GitHub Action

### PR DESCRIPTION
**Pull request by JLLeitschuh**
See: https://github.com/gradle/wrapper-validation-action

CC: @mark-vieira

### CODE REVIEW

**Comment by mark-vieira** [comment]
Very interesting. So the existing validation in place is _only_ for the distribution, right? There's currently nothing that actually validates the wrapper itself has not been tampered with?

**Comment by JLLeitschuh** [comment]
There is an implied assumption that you are trusting `services.gradle.org` is serving the correct json at https://services.gradle.org/versions/all

Assuming that the `gradle-wrapper.jar` you have checked into your repository matches at least one of the SHA-512 checksums we publish for all of our releases, this action will pass.

**Comment by JLLeitschuh** [comment]
Ohhhh. I understand. Correct, the checksum verification that you can commit to `gradle-wrapper.properties` does not verify the `gradle-wrapper.jar` hasn't been tampered with.

**Comment by JLLeitschuh** [comment]
Ping @mark-vieira

**Comment by rjernst** [comment]
@mark-vieira can you please review this?

**Review by mark-vieira — APPROVED** [review]
Sorry for the delay on this. Thanks for the submission @JLLeitschuh.

**Pull request merged**
