### PR TITLE
Switch to using refactored SortBuilder instead of using BytesReference in serialization

### LINKED ISSUE #17257: Sort on single field as a list produces parse error
**Elasticsearch version**: `5.0.0` (3ed4ff0)

**JVM version**: OpenJDK 64-Bit Server VM (build 25.74-b02, mixed mode)

**OS version**: Linux 4.1.20-1-lts

**Description of the problem including expected versus actual behavior**:  When sorting on a single field and passing it in a list you get: `Failed to derive xcontent` error

**Steps to reproduce**:
 1. `curl -X PUT localhost:9200/i/t/42 -d '{"number": 123}`'
 2. `curl localhost:9200/_search -d '{"sort": ["number"]}'`

### PR DESCRIPTION
**Pull request by cbuescher**
This is based on #17146 that needs to get in first. It moves the remaining parsing logic for the complete sort-element over to SortBuilder#fromXContent and moves further logic that used to be in SortParseElement concerned with building SortFields and populating the search context with it also to SortBuilder. 
In a last step for the refactoring the current workaround of using opaque BytesReference lists in SearchSourceBuilder and similar places it removed and the refactored SortBuilders used instead.

Closes #17257

### CODE REVIEW

**Comment by cbuescher** [comment]
@MaineC this is still WIP since it relies on first adding the build() methods to the SortBuilders (see linked PR), but I went ahead to see how much is missing to really cut over to using the refactored SortBuilders in the SearchSourceBuilder and was able to get it working by moving over most of the current parsing logic into SortBuilder. Unfortunately this makes it a quiet large PR, but half of the changes come from #17146 and should go away once that is in.

**Comment by cbuescher** [comment]
@MaineC after merging the two related PRs, this PR should only contain the changes that where necessary to make the switch from List<BytesReference> to List<SortBuilder> in SearchSourceBuilder and related similar places where we used List<BytesReference> for the sort. Some IT tests failures revealed problems (like storing "missing" String as BytesRef in FieldSortBuilder) that are also addressed here. I think this is ready to take a look.

**Comment by MaineC** [comment]
Just went over the code. Really love the amount of code that goes away after this is merged. Also like the added tests, even if checks are kept simple at the moment. So here's my LGTM 

Caveats: Didn't run the test suite here. Also we might want to add a ticket that describes where tests could be improved (like e.g. more assertions) so those don't get forgotten.

**Comment by cbuescher** [comment]
@MaineC @colings86 I added the last commit to show that we can now again parse syntax mentioned in https://github.com/elastic/elasticsearch/issues/17257

**Pull request merged**
