### PR TITLE
Remove Monitoring ingest pipelines

### PR DESCRIPTION
**Pull request by jbaiera**
Monitoring installs a number of ingest pipelines which have been historically used to upgrade documents when mappings and document structures change between versions. Since there aren't any changes to the document format, nor will there be by the time the format is completely retired, we can comfortably remove these pipelines.

Relates #50770

### CODE REVIEW

**Comment by jbaiera** [comment]
@elasticmachine update branch

**Comment by jbaiera** [comment]
@elasticmachine run elasticsearch-ci/part-2

**Comment by jbaiera** [comment]
Digging into these test failures. From the looks of things, the order of the pipelines in the expected error message is different now. I do not understand what might have caused that yet.

**Comment by jbaiera** [comment]
Added @lcawl as reviewer since you were suggested for the deprecation PR, and because this one also has docs changes

**Review by danhermann — APPROVED** [review]
LGTM

**Comment by jbaiera** [comment]
@elasticmachine update branch

**Pull request merged**
