### PR TITLE
[DOCS] Add transform breaking changes

### PR DESCRIPTION
**Pull request by lcawl**
Relates to https://github.com/elastic/elasticsearch/pull/77566

This PR adds breaking change documentation for the transform upgrades.
Edits to the deprecation messages were moved to https://github.com/elastic/elasticsearch/pull/79601  .

### Preview

https://elasticsearch_79531.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/migrating-8.0.html#breaking_80_transform_changes

### CODE REVIEW

**Review by hendrikmuhs — COMMENTED** [review]
Thanks for looking into it, this was on my todo list, but I am happy to pass it over.

**Comment by hendrikmuhs** [comment]
@lcawl  I inlined your changes into #79601, I hope that's ok for you. It fixes some more issues of the upgrader.

**Comment by lcawl** [comment]
@elasticmachine update branch

**Review by hendrikmuhs — APPROVED** [review]
LGTM

**Pull request merged**
