### PR TITLE
Fix test and unmute #84617

### PR DESCRIPTION
**Pull request by gmarouli**
I believe that it is a timing issue, sometimes the task is not ready yet. I added a `assertBusy` and run it with `-Dtests.iters=10000` and it didn't fail, so I thought this was good enough. Any thoughts?

I also added all the versions from the initial PR where the test was introduced #84028.

### CODE REVIEW

**Comment by gmarouli** [comment]
@elasticmachine update branch

**Review by martijnvg — APPROVED** [review]
LGTM 👍 

I also suspect that this is timing related. If the persistent task is in the cluster state , then I think there is no guarantee that the node task for this persistent task immediately exists. So assertBusy() seems ok here. Let's keep an eye on this test after this PR has been merged. If it doesn't fail then #84028 can be fully back ported.

Also this PR will close #84617

**Comment by gmarouli** [comment]
Thanks @martijnvg , I added the `backport pending` label here too until we are sure this is stable.

**Comment by gmarouli** [comment]
Backport will be handled by #85014

**Pull request merged**
