### PR TITLE
[ML][Inference] updates specs with new params + docs

### PR DESCRIPTION
**Pull request by benwtrent**
updates rest specs.

### CODE REVIEW

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Review by dimitris-athanasiou — APPROVED** [review]
LGTM

**Comment by benwtrent** [comment]
run elasticsearch-ci/2

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Comment by benwtrent** [comment]
run elasticsearch-ci/packaging-sample-matrix-unix
run elasticsearch-ci/packaging-sample-matrix-windows

**Comment by benwtrent** [comment]
run elasticsearch-ci/packaging-sample-matrix-unix
run elasticsearch-ci/packaging-sample-matrix-windows

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Pull request merged**
