### PR TITLE
Make soft-deletes settings final

### PR DESCRIPTION
**Pull request by dnhatn**
For now, we do not support changing the soft-deletes setting even with
closed indices. Therefore we should make it a final setting.

### CODE REVIEW

**Review by jasontedor — APPROVED** [review]
Good call. LGTM.

**Comment by jasontedor** [comment]
@dnhatn Should we mark this setting as `IndexInternal` as well so that it can only be added to an index at creation time?

**Comment by jasontedor** [comment]
Actually, looking more closely, `Final` gives us that. The salient difference between `Final` and `InternalIndex` is that a `Final` setting can *never* be modified but an `InternalIndex` setting can be modified by dedicated APIs but not the update settings API.

**Review by s1monw — APPROVED** [review]

**Comment by dnhatn** [comment]
Thanks @jasontedor and @s1monw for reviewing!

**Comment by jitianxia68** [comment]
i want to know, why can not open soft_delete setting dynamicly?   
can we support it?

**Pull request merged**
