### PR TITLE
Remove Hipchat support from Watcher

### PR DESCRIPTION
**Pull request by dakrone**
Hipchat has been shut down and has previously been deprecated in
Watcher (#39160), therefore we should remove support for these actions.

### CODE REVIEW

**Comment by dakrone** [comment]
I will open a separate PR for 7.x and 7.0, since it will include a note in the migration guide about this breaking change (the 7.0 migration docs don't exist on the master branch)

**Review by jasontedor — CHANGES_REQUESTED** [review]
We do need to have a solid understanding of what happens if a watch using the Hipchat action is carried from a 6.x to a 7.x cluster, and address accordingly.

**Review by jasontedor — APPROVED** [review]
Oops, wrong radio button. I am LGTM this PR, but let us do anything needed for loading from a previous version as a follow-up.

**Comment by dakrone** [comment]
For documentation purposes, here is what will happen when someone upgrades to a cluster with a hipchat action:

when ES starts up we'll get:
```
[2019-02-25T12:39:44,244][ERROR][o.e.x.w.WatcherService   ] [perelandra] couldn't load watch [hc-test], ignoring it...
org.elasticsearch.ElasticsearchParseException: could not parse action [hc-test/notify-hipchat]. unknown action type [hipchat]
	at org.elasticsearch.xpack.core.watcher.actions.ActionWrapper.parse(ActionWrapper.java:226) ~[x-pack-core-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.xpack.core.watcher.actions.ActionRegistry.parseActions(ActionRegistry.java:61) ~[x-pack-core-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.xpack.watcher.watch.WatchParser.parse(WatchParser.java:169) ~[x-pack-watcher-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.xpack.watcher.watch.WatchParser.parse(WatchParser.java:124) ~[x-pack-watcher-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.xpack.watcher.watch.WatchParser.parse(WatchParser.java:80) ~[x-pack-watcher-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.xpack.watcher.WatcherService.loadWatches(WatcherService.java:344) [x-pack-watcher-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.xpack.watcher.WatcherService.reloadInner(WatcherService.java:228) [x-pack-watcher-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.xpack.watcher.WatcherService.lambda$reload$0(WatcherService.java:191) [x-pack-watcher-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.xpack.watcher.WatcherService$1.doRun(WatcherService.java:401) [x-pack-watcher-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:751) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```
if you attempt to retrieve the watch you get:
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "parse_exception",
        "reason" : "could not parse action [hc-test/notify-hipchat]. unknown action type [hipchat]"
      }
    ],
    "type" : "parse_exception",
    "reason" : "could not parse action [hc-test/notify-hipchat]. unknown action type [hipchat]"
  },
  "status" : 400
}
```
but you *can* delete the watch and everything is happy

**Comment by jakelandis** [comment]
updated labels to properly reflect that this was removed prior 7.0.0

**Pull request merged**
