### PR TITLE
Ensure LuceneChangesSnapshot reads in leaf order

### PR DESCRIPTION
**Pull request by s1monw**
Today we re-initialize DV instances while we read docs
for the snapshot. This is caused by the fact that we sort the
docs by seqID which causes then to be our of order. This change
sorts documents temporarily by docID, fetches the metadata (not source)
into a in-memory datastructure and sorts it back.
This allows efficient reuse of DV instances.

### CODE REVIEW

**Comment by s1monw** [comment]
@bleskes FYI we spoke about this.

**Review by dnhatn — APPROVED** [review]
LGTM.

**Review by jpountz — APPROVED** [review]
Woohoo.

**Review by bleskes — COMMENTED** [review]
Neat! LGTM2. Thanks @s1monw .

**Pull request merged**
