### PR TITLE
Remove escape hatch permitting incompatible builds

### PR DESCRIPTION
**Pull request by masseyke**
The system property "es.unsafely_permit_handshake_from_incompatible_builds" was deprecated and has been removed in 8.0. This adds a deprecation check for that property.
Relates to #42404 and https://github.com/elastic/elasticsearch/pull/65753.

### CODE REVIEW

**Review by jbaiera — CHANGES_REQUESTED** [review]

**Comment by masseyke** [comment]
@elasticmachine merge branch

**Comment by masseyke** [comment]
@elasticmachine update branch

**Review by jbaiera — APPROVED** [review]
I think this is pretty good. I left a suggestion on another way to handle the getProperty call, but otherwise LGTM

**Comment by masseyke** [comment]
@elasticmachine run elasticsearch-ci/part-1

**Pull request merged**
