### PR TITLE
[ML] Disable machine learning on macOS x86_64

### PR DESCRIPTION
**Pull request by droberts195**
As previously advised in #104087, machine learning functionality will no longer be available on macOS x86_64.

Machine learning functionality _is_ still available on macOS by using an arm64 machine (Apple silicon). It is also possible to run Elasticsearch with machine learning functionality within a Docker container on macOS x86_64.

### CODE REVIEW

**Review by valeriy42 — COMMENTED** [review]
You can also remove the deprecation warning in https://github.com/elastic/elasticsearch/blob/546e8e91e6f6f5cd5e5343a0874239026701fff4/x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/MachineLearning.java#L934 as part of this PR.

**Review by edsavage — APPROVED** [review]
LGTM

**Comment by edsavage** [comment]
> Friendly reminder that this PR seems to be a breaking change for 9.0, but is missing from the 9.0 release note. We may want to add an entry to the breaking change section of [9.0 release note](https://github.com/elastic/elasticsearch/blob/cf536f894756f25c7ae874b4211a6b00372b39a1/docs/reference/release-notes/9.0.0.asciidoc#L8).

Thanks @samxbr ... We don't offer official support for any macOS platform, see https://www.elastic.co/support/matrix. So I'm not sure if this counts as a breaking change. I will raise it with the wider team to confirm.

**Comment by leemthompo** [comment]
@droberts195 is this PR relevant to the serverless changelog? [FYI this question is based on [9.0 breaking changes](https://staging-website.elastic.co/docs/release-notes/elasticsearch/breaking-changes)]

**Pull request merged**
