### PR TITLE
Rename client artifacts

### LINKED ISSUE #20248: Artifact IDs under org.elasticsearch.client too generic.
The Maven Artifact IDs under [org.elasticsearch.client](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.elasticsearch.client%22) are very generic and could cause naming conflicts.  Most other elasticsearch artifacts are prefixed with `elasticsearch-`.  These artifacts should follow the same practice.

Version: 5.0.0-alpha5

This issue is related to this [discussion](https://discuss.elastic.co/t/new-client-artifacts-naming-and-packaging-problematic/59228).

### PR DESCRIPTION
**Pull request by javanna**
It was brought up that our current client artifacts have generic names like 'rest' that may cause conflicts with other artifacts.

This commit renames:

- rest -> elasticsearch-rest-client
- sniffer -> elasticsearch-rest-client-sniffer
- rest-high-level -> elasticsearch-rest-high-level-client

This means that users already depending on rest and sniffer will have to update their dependencies when moving to the 5.6.0 and 6.0.0-beta1 artifacts.

A couple of small changes are also preparing the high level client for its first release.

NOTE: I left the transport client untouched as that seemed too breaking of a change for an artifact that will go away and was used as-is for some time now. Happy to update that artifact as well if others think it's better to do so.

Closes #20248

### CODE REVIEW

**Review by jasontedor — APPROVED** [review]
LGTM, and I concur with your decision to leave the transport client alone.

**Review by rjernst — APPROVED** [review]
The changes LGTM too. However, in #20248 we agreed it was too late to get the rename in for 5.0, so would have to delay to 6.0. So I think this should only go into master?

**Comment by javanna** [comment]
@rjernst it is going to be odd to have the high level client with this naming only for one version, but it's also odd to do it differently only for its artifact. Is it such a big deal to upgrade the artifact name for rest and sniffer while also upgrading the version?

**Comment by jasontedor** [comment]
I think since it's only an artifact name change (not packages, etc.) the impact here is pretty minimal and the name change concomitant with a version change would be okay.

**Comment by rjernst** [comment]
I actually don't care either way, I just wanted to be clear the reason we avoided doing this during all of 5.x until now was because of that statement about versioning in #20248.

**Comment by javanna** [comment]
Thanks @jasontedor & @rjernst I will merge this tomorrow my morning, once I get a green build that confirms I made all the necessary changes ;)

**Pull request merged**
