### PR TITLE
[DOCS] Indicate that security is disabled in 7.x

### PR DESCRIPTION
**Pull request by lockewritesdocs**
Updates wording on the main page for securing the Elastic Stack in 7.x that security is not enabled by default.

### CODE REVIEW

**Comment by lockewritesdocs** [comment]
@elasticmachine update branch

**Comment by lockewritesdocs** [comment]
@elasticmachine update branch

**Comment by lockewritesdocs** [comment]
@bytebilly, please let me know if any changes are required for this PR.

**Review by bytebilly — APPROVED** [review]
LGTM! 👍

**Pull request merged**
