### PR TITLE
Datastream: clean up data stream type check in getWriteIndex

### PR DESCRIPTION
**Pull request by weizijun**
Since `getWriteIndex` is implemented in `DataStream` class, so the type is alway `data_stream`, I think the check code can be removed.

### CODE REVIEW

**Comment by martijnvg** [comment]
@elasticmachine test this please

**Comment by martijnvg** [comment]
@elasticmachine update branch

**Comment by weizijun** [comment]
@elasticmachine update branch

**Comment by martijnvg** [comment]
@elasticmachine test this please

**Comment by martijnvg** [comment]
Thanks @weizijun!

**Comment by weizijun** [comment]
Thanks @martijnvg !

**Pull request merged**
