### PR TITLE
Correct file ownership on node reconfiguration

### LINKED ISSUE #80990: bin/elasticsearch-reconfigure-node bugs and enhancements
This is a meta issue to cover identified bugs and enhancements we want to make to `elasticsearch-reconfigure-node`. This CLI tool is introduced in 8.0.0 and the main use case it satisfies is to allow users to reconfigure an elasticsearch node that has been installed via a DEB or RPM package and enroll it into an existing cluster. 
DEB/RPM installations by default make the assumption that the installed node is the first (or only) one in the cluster and configure TLS for transport and http layers accordingly. This CLI tool allows users to revisit the assumption after installation (before the node is ever started), so that it can enroll to an existing, secured cluster.

- [ ]  `elasticsearch-reconfigure-node` should be safer to use. The current behavior is to remove existing configuration and then attempt to enroll to the cluster. We should first attempt to enroll to the cluster and then remove/replace existing configuration, or backup/restore the existing configuration upon failure to enroll, so that we leave the node in a working state in every case. 
- [ ]  `elasticsearch-reconfigure-node` lacks documentation
- [ ] `elasticsearch-reconfigure-node` is expected to be run as root and wrongly sets file owners for generated keystores, so elasticsearch fails to read them on startup.

### PR DESCRIPTION
**Pull request by jkakavas**
When running elasticsearch-reconfigure-node to allow a node that
was installed via a package(RPM/DEB) to enroll to an existing
secured cluster, we should ensure that the file ownership is
proper so that elasticsearch can actually read the files when it
starts after reconfiguration.
This commits sets the group owner of the keystore files to
`elasticsearch` which is the group that we create during
installation.

Partly resolves https://github.com/elastic/elasticsearch/issues/80990

### CODE REVIEW

**Comment by albertzaharovits** [comment]
@jkakavas Please verify my understanding:
* the package installation creates files owned by the root user and group owned by `elasticsearch`
* the node-reconfigure-tool must also be run as root, in order to do its job for package installations
* when the tool is run by root, it will create files owned by root and group-owned by `elasticsearch`, just like the package install

For me, assuming the tools is run as root, while changing the group owner of the files it creates, is the least preferred option.
I would've implemented it by simply complaining, before the tool starts, if the effective user of the tool would create files with different ownership from the ones to be replaced. The user is the free to sudo the tool invocation.
WDYT?

NB: I'm OK with this approach as well, but when we document it we must say that this assumes the instalation is owned by root and group owned by `elasticsearch`, and that the tool must be invoked as root.

**Comment by jkakavas** [comment]
> @jkakavas Please verify my understanding:

That is correct. This is what is happening with the changes of this PR

> For me, assuming the tools is run as root, while changing the group owner of the files it creates, is the least preferred option.
I would've implemented it by simply complaining, before the tool starts, if the effective user of the tool would create files with different ownership from the ones to be replaced. The user is the free to sudo the tool invocation.

Apologies, I didn't follow this.

>  if the effective user of the tool would create files with different ownership from the ones to be replaced.

 The files are meant to be owned by root and group owned by elasticsearch. There is no single user with which the tool can be run so that it produces such an ownership on its own. 

> The user is the free to sudo the tool invocation.

you mean run this as root but with `sudo -g elasticsearch`  ? I think this is more cumbersome ( if it'd work - I need to check ) and less intuitive but I'm open to discuss

> I'm OK with this approach as well, but when we document it we must say that this assumes the instalation is owned by root and group owned by elasticsearch,

We'd need to document that this tool assumes that it's being run _immediately_ after an installation and that it needs to be run as root ( all of our CLI tools have the same requirements in packaged installations due to dir/file ownership ) of a package ( which implies the above ) but I'm ++ to describe this more explicitly.

**Comment by albertzaharovits** [comment]
>> For me, assuming the tools is run as root, while changing the group owner of the files it creates, is the least preferred option.
I would've implemented it by simply complaining, before the tool starts, if the effective user of the tool would create files with different ownership from the ones to be replaced. The user is the free to sudo the tool invocation.

> Apologies, I didn't follow this.

In other words, I dislike that the tool hardcodes the ownership of the files that it generates.
Instead, I would favor that the tool generate the files with the ownership based on the effective user and group id, like any other process, like it does today, but complain if it detects that the would-be generated files have different permissions from the files it is replacing (like it does today for the owner, but not for the group owner).

> > The user is the free to sudo the tool invocation.

> you mean run this as root but with sudo -g elasticsearch ? I think this is more cumbersome ( if it'd work - I need to check ) and less intuitive but I'm open to discuss

Yes, that's what I mean. The command has to be invoked with sudo anyway. I don't see why being explicit with `-g elasticsearch` is cumbersome.

This new code is somewhere between an install script and a cmd line utility. It is not invoked by the system package-manager in the root context, during the install (so it is not 100% an install script), but as you say, we ought document that this be manually invoked only after an install (so if it always follows an install, it is part of an install, hence it is an install script).

I think the above to me sounds closer to a cmd line utility (which shouldn't hardcode file ownership), while to you it sounds closer to an install script (where it is fine to hardcode it). I believe this is what we're arguing around.

**Comment by albertzaharovits** [comment]
Therefore, I'm OK with the proposed change, if what we're building here is an install script in disguise (because it's not quite a "script"), and we document it as such. 

My suggestion is that we don't have to do that, that we instead can consider this a regular cmd line tool that has to be invoked with `sudo -u root -g elasticsearch` (assuming it works).

**Comment by jkakavas** [comment]
I don't feel strongly about this tbh.. I'll bring in @bytebilly for an extra opinion and some insights about the user experience. In essence, the options are two: 

1. We document that this tool needs to be run as root and handle the group ownership behind the curtains ourselves. This means that the user needs to either: 
  - Be root and run `elasticsearch-reconfigure-node` 
  - run `sudo elasticsearch-reconfigure-node` 
2. We document that this tool needs to be run as root with primary group being `elasticsearch`. This means that the user needs to run ( it does work - I tried this just now ) 
  - `sudo -g elasticsearch elasticsearch-reconfigure-node` if they are `root` or
  - `sudo -u root -g elasticsearch elasticsearch-reconfigure-node` if they are logged in as any other user

**Comment by bytebilly** [comment]
I'm a bit hesitant to require running sudo with `-g`, as it is a very uncommon pattern and may be missed by users, leading to an inconsistent result. I understand that documentation will report that, but I suspect that most of the time when people see a command starting with `sudo`, they just run `sudo <command>` because that's what they are used to do all the time.

If the problem is hardcoding the `elasticsearch` group name, can't we just check what the group of the current file to replace is, and set the new file with the same value? It's a bit more tricky but it could avoid hardcoding the group name.

**Comment by jkakavas** [comment]
> If the problem is hardcoding the elasticsearch group name, can't we just check what the group of the current file to replace is, and set the new file with the same value? It's a bit more tricky but it could avoid hardcoding the group name.

We are hardcoding this in the package installation script too, this is why I felt it is ok to do this here. I think @albertzaharovits did an awesome job at capturing my mental model without even discussing it, I consider this a continuation of the installation process, thus in my mind this is ok to do

**Comment by albertzaharovits** [comment]
Thanks for the deliberation @jkakavas , and thanks for the input @bytebilly !
LGTM

**Review by albertzaharovits — APPROVED** [review]

**Comment by jkakavas** [comment]
@elasticmachine update branch

**Pull request merged**
