### PR TITLE
Remove support for the `multi_field` type.

### PR DESCRIPTION
**Pull request by jpountz**
It is officially unsupported since version 1.0.

### CODE REVIEW

**Comment by martijnvg** [comment]
LGTM (nice cleanup!)

**Comment by dadoonet** [comment]
Do we need to add it in breaking changes? Though it was deprecated in 1.0?

**Comment by jpountz** [comment]
It is already in the 1.0 breaking changes so I don't think we need to add it again?

**Comment by dadoonet** [comment]
Indeed. https://www.elastic.co/guide/en/elasticsearch/reference/1.3/_multi_fields.html

> Well, the field type `multi_field` has been removed.

Ignore me then! :D

**Pull request merged**
