### PR TITLE
Add WKB support to lib geo

### PR DESCRIPTION
**Pull request by iverase**
Adds a WKB reader/writer in the same fashion as the existing WKT reader/writer.

### CODE REVIEW

**Comment by iverase** [comment]
@elasticmachine run elasticsearch-ci/part-1

**Review by imotov — COMMENTED** [review]
Could you add some tests for collections and round-tripping random geometries? Where is this going to be used?

**Comment by iverase** [comment]
Added a test for geometry collections.

The idea for adding this support comes from here where it was first discussed: https://github.com/elastic/elasticsearch/issues/32433#issuecomment-430785724

I an hoping that the combination of WKB and a binary format like smile to index documents will reduce the index size and it will speed up fetching of complex shapes, e.g one of the most expensive steps in the vector tile API is parsing geometries from _source.

**Comment by iverase** [comment]
@elasticmachine update branch

**Review by imotov — APPROVED** [review]
LGTM

**Pull request merged**
