### PR TITLE
WIP Add dual stack TLS/Plaintext support

### PR DESCRIPTION
**Pull request by Tim-Brooks**
Add support for a node with security enabled to communicate with both
plaintext and TLS nodes. This PR is a WIP for a high-level overview of
this implementation. It is likely to it will be merged in different,
smaller PRs.

### CODE REVIEW

**Comment by tbrooks8** [comment]
@s1monw - This is what I've come up with. I can break this up into different, smaller PRs. But this is the high level design so if you have any issues with it, let me know.

**Comment by s1monw** [comment]
@tbrooks8 I like the overall idea. I think we need to discuss if this should be implemented on the lower levels like it is here or rather on the `ConnectionManager` level. My intuition says it should be on the `ConnectinManager` since we totally want to differentiate between CCS / CCR connections and within-cluster connections. This is also the place where we account for `connectedNodes` which would allow us to implement this entire logic without touching the entire transport layer. 

I do wonder if we can put a boolean on `ConnectionProfile` and pass it down all the way to `initiateChannel`? This way we don't need to do fancy retry logic in TcpTransport and can do all the tricky part in one place in ConnectionManager?

**Comment by tbrooks8** [comment]
@s1monw Alright I am going to start opening smaller PRs. I will make some adjustments based on your high level comments. For example, I think that we can move the retry into the `ConnectionManager`. And only retry for the intra-cluster connections. 

However, I think that we are still going to need to touch the transport layer (for example: implementing the logic that supports detecting whether an inbound connection is plaintext or tls).

**Comment by s1monw** [comment]
> However, I think that we are still going to need to touch the transport layer (for example: implementing the logic that supports detecting whether an inbound connection is plaintext or tls).

I totally agree, +1 to smaller PRs

**Comment by tbrooks8** [comment]
Closing this as it was WIP and we're past the point where we need high level feedback on this issue.

**Pull request closed without merging**
