### PR TITLE
Delegate xorBitCount to Lucene

### PR DESCRIPTION
**Pull request by ChrisHegarty**
Now that we're on Lucene 9.12 we don't need our own optimized xorBitCount, can just delegate to Lucene's optimized one (which is identical).

relates: #110599

### CODE REVIEW

**Review by benwtrent — APPROVED** [review]

**Comment by ChrisHegarty** [comment]
@elasticmachine update branch

**Comment by ChrisHegarty** [comment]
@elasticmachine update branch

**Comment by ChrisHegarty** [comment]
@elasticmachine update branch

**Comment by ChrisHegarty** [comment]
@elasticmachine update branch

**Comment by ChrisHegarty** [comment]
@elasticmachine run elasticsearch-ci/part-1

**Review by tteofili — APPROVED** [review]

**Pull request merged**
