### PR TITLE
Upgrade to joda 2.10.4

### PR DESCRIPTION
**Pull request by spinscale**
Just a timezone database update, according to the release notes at https://www.joda.org/joda-time/changes-report.html#a2.10.4

### CODE REVIEW

**Review by pgomulka — APPROVED** [review]
LGTM once jenkins is green

**Comment by spinscale** [comment]
@elasticmachine update branch

**Comment by spinscale** [comment]
@elasticmachine update branch

**Comment by spinscale** [comment]
@elasticmachine run elasticsearch-ci/1

**Pull request merged**
