### PR TITLE
Add safer empty variable checking for Windows

### LINKED ISSUE #26261: elasticsearch-env.bat chokes on if not "%JAVA_TOOL_OPTIONS%" == ""
elasticsearch-6.0.0-beta1

**Elasticsearch version** (`bin/elasticsearch --version`):

**Plugins installed**: []

**JVM version** (`java -version`): JRE 1.8

**OS version** (`uname -a` if on a Unix-like system): windows 7 enterprise

**Description of the problem including expected versus actual behavior**:
elasticsearch.bat doesn't start es.  

c:\elk> elasticsearch.bat
Microsystems was unexpected at this time.

**Steps to reproduce**:
c:\elk> elasticsearch.bat
Microsystems was unexpected at this time.

PLEASE NOTE: that I did do a msi installation and uninstall before attempting above.

WORK AROUND:
elasticsearch-env.bat

rem do not let JAVA_TOOL_OPTIONS slip in (as the JVM does by default)
 if not "%JAVA_TOOL_OPTIONS%" == "" (
  echo "warning: ignoring JAVA_TOOL_OPTIONS=$JAVA_TOOL_OPTIONS"
   set JAVA_TOOL_OPTIONS=
 )

change to 

rem do not let JAVA_TOOL_OPTIONS slip in (as the JVM does by default)
rem  if not "%JAVA_TOOL_OPTIONS%" == "" (
rem   echo "warning: ignoring JAVA_TOOL_OPTIONS=$JAVA_TOOL_OPTIONS"
rem    set JAVA_TOOL_OPTIONS=
rem  )

### PR DESCRIPTION
**Pull request by jasontedor**
We need to check if JAVA_TOOL_OPTIONS, and JAVA_OPTS are set, and if ES_PATH_CONF is not set. However, if these variables are defined and contain quotes, the current mechanism busts on them. Instead, we should use safer mechanism for checking if these variable are defined or not. This commit does that.

Closes #26261

### CODE REVIEW

**Comment by jasontedor** [comment]
This relies on command extensions being enabled. I'm not sure if we should enable them in the script or not, or rely on them already being enabled. I am not sure how common it is these days that command extensions are *not* enabled. I would rather leave it out of the script and wait for feedback from the community before doing that.

**Comment by jasontedor** [comment]
I can also see an argument for simply enabling them since we rely on them being enabled, so I welcome feedback on that here too.

**Review by rjernst — APPROVED** [review]
LGTM. I would vote for explicitly enabling them in the script. I see it like `set -e` in bash.

**Comment by jasontedor** [comment]
Thanks @rjernst, I pushed 8562827af66d3f760fb7403360ee820fd857893f to explicitly enable command extensions.

**Pull request merged**
