### PR TITLE
Tests: fix TimeSeriesDataStreamsIT.testShrinkActionInPolicyWithoutHotPhase

### LINKED ISSUE #59399: [CI] TimeSeriesDataStreamsIT.testShrinkActionInPolicyWithoutHotPhase Fails on 7.x
Seeing the following failure in https://gradle-enterprise.elastic.co/s/ejqcdrqr2xyim/console-log?anchor=6235 (7.x)

```
REPRODUCE WITH: ./gradlew ':x-pack:plugin:ilm:qa:multi-node:integTestRunner' --tests "org.elasticsearch.xpack.ilm.TimeSeriesDataStreamsIT.testShrinkActionInPolicyWithoutHotPhase" -Dtests.seed=5D3E4B2F86A913F0 -Dtests.security.manager=true -Dtests.locale=pt -Dtests.timezone=America/Blanc-Sablon -Druntime.java=8
```

fails with:

```
 java.lang.AssertionError: the original index must've been deleted
    Expected: is <false>
         but: was <true>
        at __randomizedtesting.SeedInfo.seed([5D3E4B2F86A913F0:68C0EF502787483F]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.elasticsearch.xpack.ilm.TimeSeriesDataStreamsIT.testShrinkActionInPolicyWithoutHotPhase(TimeSeriesDataStreamsIT.java:96)
```

### PR DESCRIPTION
**Pull request by andreidan**
The ILM policy for the source and shrunk indices run separately (ie. they
are two separate managed indices). This fixes the test which exhibited some
flakiness by allowing some time for the ILM policy for the source index
to finish executing.

Fixes #59399

### CODE REVIEW

**Comment by andreidan** [comment]
@elasticmachine update branch

**Comment by andreidan** [comment]
@elasticmachine update branch

**Comment by andreidan** [comment]
@elasticmachine retest this

**Comment by andreidan** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Review by dakrone — APPROVED** [review]
LGTM, thanks Andrei!

**Pull request merged**
