### PR TITLE
In reverse nested aggregation, fix handling of the same child doc id being processed multiple times.

### PR DESCRIPTION
**Pull request by martijnvg**
PR for #9263

On the master, 1.x and 1.4 PR #9346 should be applied first.

### CODE REVIEW

**Comment by markharwood** [comment]
Working through this and the one thing that looks like it would be beneficial for us and users, particularly given the complexity of these queries, is to have test examples that demonstrate a real use case rather than the very abstract foo/bar/baz examples.

**Comment by markharwood** [comment]
Change to ReverseNestedAggregator looks good.

**Comment by jpountz** [comment]
LGTM

**Comment by martijnvg** [comment]
@markharwood I'll update the test to use a more realistic example example.

**Pull request closed without merging**
