### PR TITLE
Improve transport stats histogram

### PR DESCRIPTION
**Pull request by DaveCTurner**
- omits empty buckets at the start and end of the histogram
- includes human-readable representation of the bucket boundaries if `?human` specified

### CODE REVIEW

**Comment by DaveCTurner** [comment]
Thinking about histograms again in the vicinity of https://github.com/elastic/elasticsearch/issues/88151, I found this histogram kinda annoying to use in practice because of all the zeroes; the lack of human-readable times isn't too big a deal when everything is in milliseconds but still a little nicer this way.

**Comment by DaveCTurner** [comment]
More specifically, the histograms tracking message sizes to resolve #88151 need more buckets (going up to perhaps 100MiB) and there's lots more of them (~250 actions) and therefore need zero-suppression like this. But having some histograms in the stats with zero-suppression and others without seems weird, so I'd rather suppress zeroes here too, and therefore do this first.

**Comment by DaveCTurner** [comment]
Turns out that https://github.com/elastic/elasticsearch/issues/88151 is somewhat important to us, so I'd like to get this in as well (and to do so first).

**Review by henningandersen — APPROVED** [review]
LGTM.

**Comment by DaveCTurner** [comment]
@elasticmachine update branch

**Pull request merged**
