### PR TITLE
Upgrade randomizedrunner to 2.5.2

### LINKED ISSUE #250: Non-bootstrapped ForkedJvmInfo causes NullPointerExceptions
Hello! Perhaps more of a question than an issue. Building Elasticsearch on OS X, I noticed [this issue](https://discuss.elastic.co/t/periodic-nullpointerexceptions-in-heartbeatevent-running-gradle-test-in-os-x/91014) that was driving me crazy, thinking I had a bug in my code :)

In short, I get periodic stack traces:

```
Exception thrown by subscriber method onHeartbeat(com.carrotsearch.ant.tasks.junit4.events.aggregated.HeartBeatEvent) on subscriber com.carrotsearch.gradle.junit4.TestReportLogger@52ca2fa9 when dispatching event: com.carrotsearch.ant.tasks.junit4.events.aggregated.HeartBeatEvent@3fa57c62
java.lang.NullPointerException
        at com.carrotsearch.ant.tasks.junit4.ForkedJvmInfo.getPidString(ForkedJvmInfo.java:85)
        at com.carrotsearch.ant.tasks.junit4.ForkedJvmInfo$getPidString.call(Unknown Source)
        at com.carrotsearch.gradle.junit4.TestReportLogger.onHeartbeat(TestReportLogger.groovy:116)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
```

I've been digging into this, and it seems to perhaps be a randomized testing issue, related to [this log statement](https://github.com/randomizedtesting/gradle-randomized-testing-plugin/blob/master/src/main/groovy/com/carrotsearch/gradle/junit4/TestReportLogger.groovy#L116).

Which ultimately invokes [ForkedJvmInfo::getPidString](https://github.com/randomizedtesting/randomizedtesting/blob/master/junit4-ant/src/main/java/com/carrotsearch/ant/tasks/junit4/ForkedJvmInfo.java#L84) which doesn't check if bootstrapEvent has been set:

```
  public String getPidString() {
    return bootstrapEvent.getPidString();
  }
```

Which is odd, because other parts of ForkedJvmIssue appear to do such null checks, such as [here](https://github.com/randomizedtesting/randomizedtesting/blob/master/junit4-ant/src/main/java/com/carrotsearch/ant/tasks/junit4/ForkedJvmInfo.java#L66).

Further digging lead me to presuppose bootstrap and heartbeat might be independent events, so perhaps heartbeat occurs before bootstrap. And if that happened, the log statement would throw a NullPointerException.

I'm lead to believe either:
- I should be concerned: Something bad happened, and bootstrap event should have been set, and I'm actually in a bad state
- I don't need to worry (my working assumption): that sometimes a heartbeat would fire randomly before a bootstrap event. So I can safely avoid this NullPointerException and this is a minor bug.

I'm using MacOSX, and have seen this with Gradle 3.5/4.0 across two versions of Oracle JDK 8.

### PR DESCRIPTION
**Pull request by s1monw**
An issue causing confusing error messages during test exectuion
has been fixed randomizedtesting/randomizedtesting#250

### CODE REVIEW

**Review by jpountz — APPROVED** [review]
Let's upgrade Lucene too?

**Comment by s1monw** [comment]
> Let's upgrade Lucene too?

you mean update it in lucene as well?

**Comment by jpountz** [comment]
right

**Comment by s1monw** [comment]
[here](https://issues.apache.org/jira/browse/LUCENE-7896) is the lucene issue

**Pull request merged**
