### PR TITLE
Ignore unknown shards in the prevalidate shard path API

### LINKED ISSUE #104807: [CI] PrevalidateShardPathIT testCheckShards failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/cqthpgkneqdvo/tests/:server:internalClusterTest/org.elasticsearch.cluster.PrevalidateShardPathIT/testCheckShards

**Reproduction line:**
```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.cluster.PrevalidateShardPathIT.testCheckShards" -Dtests.seed=4D7C3C7CEAC38430 -Dtests.locale=sv -Dtests.timezone=America/Catamarca -Druntime.java=18
```

**Applicable branches:**
8.12

**Reproduces locally?:**
No

**Failure history:**
[Failure dashboard for `org.elasticsearch.cluster.PrevalidateShardPathIT#testCheckShards`](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('testCheckShards'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.cluster.PrevalidateShardPathIT'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure excerpt:**
```
java.lang.AssertionError: The relocation source node should have removed the shard(s)

  at __randomizedtesting.SeedInfo.seed([4D7C3C7CEAC38430:FC641ADAEFC68041]:0)
  at org.junit.Assert.fail(Assert.java:88)
  at org.junit.Assert.assertTrue(Assert.java:41)
  at org.elasticsearch.cluster.PrevalidateShardPathIT.lambda$testCheckShards$1(PrevalidateShardPathIT.java:80)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1278)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1251)
  at org.elasticsearch.cluster.PrevalidateShardPathIT.testCheckShards(PrevalidateShardPathIT.java:72)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:577)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

```

### PR DESCRIPTION
**Pull request by arteam**
If the node doesn't have metadata about a shard's index, we can't make any assumptions whether the shard is actually located on it.

I believe this should actually fix #104807. In all cases where that test fails, the shard is actually relocated from the `node_2`, but if send a `PrevalidateShardPathRequest` to the node_2, it keeps claiming that the shard is still located on it despite that the node doesn't even know about the index in the metadata.

Resolves #104807

### CODE REVIEW

**Comment by pxsalehi** [comment]
> it keeps claiming that the shard is still located on it despite that the node doesn't even know about the index in the metadata.

IIRC, this is intentional. There is a comment at L101 of `TransportPrevalidateShardPathAction` and also its class comment. Here we care about the local copy on disk. To me the test failure might hint at the clean up process after the shard has been removed didn't work or took too long. The previous fix for this test was also trying to address something similar: https://github.com/elastic/elasticsearch/commit/a7a016f34d50e00e64ebacebed8536d059966e00. Maybe we have a bug in the clean up process. Note that this is not strictly related to the prevalidation code. If you can produce a minimal example (w/o the prevalidate action) where after relocation the shard copy stays around unnecessarily, then that might a bug and the root cause of the test failure too.

**Comment by arteam** [comment]
@pxsalehi You're right, that's not a correct fix! It does seem to we need to force a way to clean up the shard from disk.  Looks like an empty cluster state update doesn't really help :(

```
  1> [2024-06-21T14:18:31,362][INFO ][o.e.c.PrevalidateShardPathIT] [testCheckShards] Triggering an extra cluster state update
  1> [2024-06-21T14:18:31,364][DEBUG][o.e.c.s.MasterService    ] [node_t0] executing cluster state update for [update-settings [[index1/pbc1hXnXTZackj2IUyqffg]][[[index1/pbc1hXnXTZackj2IUyqffg]]{"index.routing.allocation.exclude.name":"non-existentvUlvP"}]]
  1> [2024-06-21T14:18:31,370][DEBUG][o.e.c.s.MasterService    ] [node_t0] took [6ms] to compute cluster state update for [update-settings [[index1/pbc1hXnXTZackj2IUyqffg]][[[index1/pbc1hXnXTZackj2IUyqffg]]{"index.routing.allocation.exclude.name":"non-existentvUlvP"}]]
  1> [2024-06-21T14:18:31,370][DEBUG][o.e.c.s.MasterService    ] [node_t0] cluster state updated, version [16], source [update-settings [[index1/pbc1hXnXTZackj2IUyqffg]][[[index1/pbc1hXnXTZackj2IUyqffg]]{"index.routing.allocation.exclude.name":"non-existentvUlvP"}]]
  1> [2024-06-21T14:18:31,371][DEBUG][o.e.c.s.MasterService    ] [node_t0] publishing cluster state version [16]
  1> [2024-06-21T14:18:31,425][INFO ][o.e.t.s.M.Listener       ] [node_t2] [index1][0] end check index
  1> [2024-06-21T14:18:31,426][DEBUG][o.e.c.s.MasterService    ] [node_t0] took [0s] to notify listeners on successful publication of cluster state (version: 16, uuid: sTWzweWRTcGPMRu5K2SS7w) for [update-settings [[index1/pbc1hXnXTZackj2IUyqffg]][[[index1/pbc1hXnXTZackj2IUyqffg]]{"index.routing.allocation.exclude.name":"non-existentvUlvP"}]]
  1> [2024-06-21T14:18:31,426][DEBUG][o.e.c.s.MasterService    ] [node_t0] executing cluster state update for [reconcile-desired-balance[ReconcileDesiredBalanceTask[lastConvergedIndex=13]]]
  1> [2024-06-21T14:18:31,426][DEBUG][o.e.c.s.MasterService    ] [node_t0] took [0s] to compute cluster state update for [reconcile-desired-balance[ReconcileDesiredBalanceTask[lastConvergedIndex=13]]]
  1> [2024-06-21T14:18:31,427][DEBUG][o.e.c.s.MasterService    ] [node_t0] took [1ms] to notify listeners on unchanged cluster state for [reconcile-desired-balance[ReconcileDesiredBalanceTask[lastConvergedIndex=13]]]
```

**Comment by pxsalehi** [comment]
> It does seem to we need to force a way to clean up the shard from disk.

Or rather we can find out why it doesn't get cleaned up so we either accept it with a good reason or fix it if it is bug. I'd say this test failure is probably just a symptom.

**Comment by arteam** [comment]
> Or rather we can find out why it doesn't get cleaned up so we either accept it with a good reason or fix it if it is bug. I'd say this test failure is probably just a symptom.

I'm going to spend more time trying to reproduce the failure of cleaning up, but it has never failed for me locally. Otherwise maybe it makes sense to increase the timeout on `assertBusy` from 10s to 30s to get more information on CI.

**Comment by pxsalehi** [comment]
IMO, if we can make sure this is not a real bug and just needs a longer timeout for the clean up to work then increasing the timeout on assertBusy would be ok. But it might be worth it to dig into the code that does this sort of clean up and its related tests. (probably somewhere around `IndicesClusterStateService#removeIndicesAndShards`).

**Comment by pxsalehi** [comment]
IIUC, `IndicesStore#deleteShardIfExistElseWhere` is also relevant here. I see that the default timeout there is 30s (`indices.store.delete.shard.timeout`). It seems that also the relevant ITs also use 30s (`IndicesStoreIntegrationIT`). So I'd say it makes sense to bump it to 30s proactively. If it fails, then there is something wrong for sure. I only had a quick look at these, so I might be missing something.

**Pull request closed without merging**
