### PR TITLE
[DOCS] Move snapshot repo types to separate pages

### PR DESCRIPTION
**Pull request by jrodewig**
With https://github.com/elastic/elasticsearch/pull/81870, the Azure, GCS, and S3 repository types have separate, dedicated pages in the Elasticsearch guide. For consistency, this PR creates separate pages for the shared file system, read-only URL, and source-only repository types.

Related changes:

- Adds redirects to the plugins docs
- Fixes a few breaking changes that refer to the Azure, GCS, and S3 repositories as plugins.

### Notes for reviewers

Despite the big diffs, I didn't make any substantive changes to the docs. It's mostly copying and pasting the existing docs over to new pages.

The `elasticsearch-ci/docs` test is also failing due to some broken links in the Kibana UI. This is sort of a chicken-egg situation so we'll likely need to merge without this test passing. I've opened https://github.com/elastic/kibana/pull/123415 to fix the links in Kibana.

### Previews

* Register a repository: https://elasticsearch_82826.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/snapshots-register-repository.html
* Shared file system repository: https://elasticsearch_82826.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/snapshots-filesystem-repository.html
* Read-only URL repository: https://elasticsearch_82826.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/snapshots-read-only-repository.html
* Source-only repository: https://elasticsearch_82826.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/snapshots-source-only-repository.html
* Create snapshot repository API: https://elasticsearch_82826.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/put-snapshot-repo-api.html#put-snapshot-repo-api-request-body

### CODE REVIEW

**Comment by jrodewig** [comment]
@elasticmachine run elasticsearch-ci/docs skiplinkcheck

**Comment by jrodewig** [comment]
@elasticmachine run elasticsearch-ci/docs skiplinkcheck

**Comment by jrodewig** [comment]
@elasticmachine run elasticsearch-ci/docs skiplinkcheck

**Comment by jrodewig** [comment]
@elasticmachine run elasticsearch-ci/docs skiplinkcheck

**Comment by jrodewig** [comment]
@elasticmachine run elasticsearch-ci/docs skiplinkcheck

**Comment by jrodewig** [comment]
@elasticmachine run elasticsearch-ci/docs skiplinkcheck

**Comment by jrodewig** [comment]
@elasticmachine run elasticsearch-ci/docs skiplinkcheck

**Comment by jrodewig** [comment]
@elasticmachine run elasticsearch-ci/docs

**Review by lockewritesdocs — APPROVED** [review]
Great changes @jrodewig! I left some non-blocking changes that you can apply if wanted. I realize that section was a copy+paste, but could be a nice improvement.

**Comment by jrodewig** [comment]
Great suggestions @lockewritesdocs. Thanks!

**Comment by jrodewig** [comment]
@elasticmachine run elasticsearch-ci/docs skiplinkcheck

**Comment by jrodewig** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by jrodewig** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.0|[](https://github.com/elastic/elasticsearch/pull/83185)|


### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
