### PR TITLE
[DOCS] Fix gcloud command typo in discovery-gce.asciidoc

### PR DESCRIPTION
**Pull request by mattayes**
# Changes

Fixes a `gcloud` command typo.

### CODE REVIEW

**Review by dadoonet — APPROVED** [review]

**Comment by mattayes** [comment]
@dadoonet Anything else I need to do before this can be merged?

**Comment by dadoonet** [comment]
@elastic/docs Would you like to merge it?

**Comment by jrodewig** [comment]
I'll merge and backport. Thanks for your contribution @mattayes.

**Comment by mattayes** [comment]
Thanks @dadoonet for the review and @jrodewig for the merge!

**Pull request merged**
