### PR TITLE
[DOCS]Fix bulk request comment grammar issue.

### PR DESCRIPTION
**Pull request by howardhuanghua**
Fix bulk request comment grammar issue.

### CODE REVIEW

**Comment by HiDAl** [comment]
@elasticmachine test this please

**Comment by HiDAl** [comment]
@howardhuanghua can you follow the guideline from [this message](https://github.com/elastic/elasticsearch/pull/95247#issuecomment-1508251664)? thanks

**Review by HiDAl — APPROVED** [review]

**Comment by howardhuanghua** [comment]
> @howardhuanghua can you follow the guideline from [this message](https://github.com/elastic/elasticsearch/pull/95247#issuecomment-1508251664)? thanks
Hi @HiDAl , it seems I don't have the option in my own forked repository. Any enhancement I can do it directly?

**Comment by HiDAl** [comment]
thanks @howardhuanghua !

**Pull request merged**
