### PR TITLE
Remove legacy params from range query

### PR DESCRIPTION
**Pull request by mayya-sharipova**
Remove to, from, include_lower, include_upper range query params.
 These params have been removed from our documentation in v. 0.90.4 (d6ecdec), 
and got deprecated in 8.16 in #113286.

### CODE REVIEW

**Review by john-wagster — APPROVED** [review]
LGTM

**Comment by mayya-sharipova** [comment]
@elasticsearchmachine update branch

**Comment by mayya-sharipova** [comment]
@elasticsearchmachine run elasticsearch-ci/bwc-snapshots

**Comment by mayya-sharipova** [comment]
@elasticsearchmachine run elasticsearch-ci/8.17.0 / bwc-snapshots

**Comment by mayya-sharipova** [comment]
@elasticsearchmachine run "elasticsearch-ci/8.17.0 / bwc-snapshots"

**Comment by leemthompo** [comment]
@mayya-sharipova is this PR relevant to the serverless changelog? [FYI this question is based on [9.0 breaking changes](https://staging-website.elastic.co/docs/release-notes/elasticsearch/breaking-changes)]

**Pull request merged**
