### PR TITLE
Add XContentHelper shims for move to specifying deprecation logger

### PR DESCRIPTION
**Pull request by dakrone**
This adds deprecated shims for the `convertToMap` method in `XContentHelper`.
These shims will be removed once all callers switch to passing in the
`DeprecationHandler` when converting to a map.

Relates to #28504

### CODE REVIEW

**Comment by dakrone** [comment]
I have both the ES and X-pack parts of the removal of the deprecated methods ready, but this is required first not to make Jenkins extremely unhappy.

**Comment by nik9000** [comment]
I think `convertToMap` can't encounter deprecated fields so we'd be safe using `DeprecationHandler.THROW_UNSUPPORTED_OPERATION` there. In that case we don't need these shims at all.

**Comment by dakrone** [comment]
I'll experiment and see if this works for us

**Comment by dakrone** [comment]
@nik9000 so, I ran the tests with the `DeprecationHandler.THROW_UNSUPPORTED_OPERATION` handler passed in for the `convertToMap` methods, and it passed. However, I'm still concerned about doing this for all usages, take for instance

https://github.com/elastic/elasticsearch/blob/7c201a64b539c579654af9a99624f7e88519b2df/server/src/main/java/org/elasticsearch/action/admin/indices/template/put/PutIndexTemplateRequest.java#L369

Where we take the source for a template that is potentially user-provided and convert it to a map. If we throw an `UnsupportedOperationException` for this because they used a deprecated field, I think that would be bad. The tests don't fail because we already have checks that we don't use deprecated things in our tests, but that doesn't mean that `convertToMap` can't encounter deprecated fields.

What do you think?

**Comment by dakrone** [comment]
Another example (there are lots I think) where we don't really know what we're converting into a map:

https://github.com/elastic/elasticsearch/blob/04fe9a9ab573081d3e10ef56864a7de03da072bc/server/src/main/java/org/elasticsearch/action/index/IndexRequest.java#L293-L295

**Comment by nik9000** [comment]
I think `convertToMap` doesn't interact with deprecation at all because when we converting xcontent into a map we can't know whether or not something is deprecated. I think it is the responsibility of the code that accepts the map to decide if something is deprecated. At least as it stands now, their do that by interacting with `DeprecationLogger` directly.

**Comment by nik9000** [comment]
I think in a perfect world we wouldn't do this "convert to a map then parse" thing. We'd just, well, parse the xcontent. The advantage of parsing the xcontent is that we have pre-built stuff to parse the xcontent and handle deprecation. And that stuff can include location information in the deprecation message if it wants to because it has it. Converting to a map throws all that out. But the code isn't perfect and sometimes it just wants to iterate over Maps because that was easier to implement at the time.

**Comment by dakrone** [comment]
> I think it is the responsibility of the code that accepts the map to decide if something is deprecated. At least as it stands now, their do that by interacting with DeprecationLogger directly.

Alright, in that case, do we want to implement a no-op deprecation handler and use it in the `convertToMap` methods?

**Comment by nik9000** [comment]
> do we want to implement a no-op deprecation handler and use it in the convertToMap methods?

We certainly *can*. Maybe it should `assert false: "shouldn't be called";` or something. `convertToMap` could just use the throwing one though because that parser doesn't escape the `convertToMap` method and `convertToMap` never interacts with deprecation.

**Comment by dakrone** [comment]
Okay, I'll close this and we'll keep the current throw unsupported behavior

**Pull request closed without merging**
