### PR TITLE
Allow kibana_system to create and invalidate API keys on behalf of other users

### PR DESCRIPTION
**Pull request by peterschretlen**
This change adds the following privileges to the `kibana_system` role:
- `grant_api_key` recently added in https://github.com/elastic/elasticsearch/pull/53527
- `api_key/invalidate`

This is to support alerting on Kibana, which uses API keys to run scheduled background alert checks on a user's behalf as described in https://github.com/elastic/elasticsearch/issues/48716#issuecomment-574531126

Related: https://github.com/elastic/kibana/issues/49398

### CODE REVIEW

**Comment by peterschretlen** [comment]
Related PR on Kibana side: https://github.com/elastic/kibana/pull/60423

**Comment by peterschretlen** [comment]
Tested locally to confirm the roles are added and working as expected. 

`kibana_system` role includes `grant_api_key` and  `api_key/invalidate`
```sh
$ curl -k -s -u elastic:changeme https://localhost:9200/_security/role/kibana_system | jq .kibana_system.cluster
[
  "monitor",
  "manage_index_templates",
  "cluster:admin/xpack/monitoring/bulk",
  "manage_saml",
  "manage_token",
  "manage_oidc",
  "cluster:admin/xpack/security/api_key/invalidate",   <---- added
  "grant_api_key",                                     <---- added
  "cluster:admin/xpack/security/privilege/builtin/get",
  "delegate_pki",
  "cluster:admin/ilm/get",
  "cluster:admin/ilm/put",
  "cluster:admin/analyze"
]
```

`kibana` user has `kibana_system` role:
```sh
 $ curl -k -s -u elastic:changeme  https://localhost:9200/_security/user/kibana | jq -c .kibana.roles
["kibana_system"]
```

`kibana` user can invalidate API key:
```sh
# create key for elastic user
$ curl -k -s -u elastic:changeme -H content-type:application/json -d '{ "name":"my-key" }'  https://localhost:9200/_security/api_key | jq .
{
  "id": "IEFY9HABM4_s1PGvY_DW",
  "name": "my-key",
  "api_key": "2VVEhxpRSwqq3PV3clHGZg"
}
# kibana user invalidates key
$ curl -k -s -u kibana:changeme -H content-type:application/json -XDELETE -d '{ "name":"my-key" }' https://localhost:9200/_security/api_key | jq .
{
  "invalidated_api_keys": [
    "IEFY9HABM4_s1PGvY_DW"
  ],
  "previously_invalidated_api_keys": [],
  "error_count": 0
}
```

`kibana` user can grant key:
```
# kibana grants key for elastic user
$ curl -k -s -u kibana:changeme -H content-type:application/json -d '{ "grant_type":"password", "username":"elastic", "password":"changeme" }' https://localhost:9200/_security/api_key/grant | jq .
{
  "id": "HEFi9HABM4_s1PGvv_GA",
  "name": null,
  "api_key": "1XI-g2IWRseli9E3G3yazg"
}

# list keys for elastic user
$ curl -k -s -u elastic:changeme https://localhost:9200/_security/api_key?username=elastic | jq .
{
  "api_keys": [
    {
      "id": "HEFi9HABM4_s1PGvv_GA",
      "name": null,
      "creation": 1584648077171,
      "invalidated": false,
      "username": "elastic",
      "realm": "reserved"
    }
  ]
}
```

**Review by legrego — COMMENTED** [review]
Thanks Peter! The additional privileges look good to me. Can we also update the existing test to ensure the `kibana_system` role can perform these actions?

https://github.com/elastic/elasticsearch/blob/9074215f8ccf8b4847d76c599f4aa9763f162980/x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/security/authz/store/ReservedRolesStoreTests.java#L298

**Comment by tvernum** [comment]
Thanks @peterschretlen I was off sick at the end of last week, and was just about to pick this up when I saw you had done it.

**Review by tvernum — APPROVED** [review]
LGTM

**Pull request merged**
