### PR TITLE
Split get data stream api yaml test in two tests.

### LINKED ISSUE #81462: [CI] XPackRestIT test {p0=data_stream/10_basic/Get data stream api check existence of replicated and allow_custom_routing fields} failing
allow_custom_routing is only in 8.0 but the test assumes it's in 7.16.1 and above.

**Build scan:**
https://gradle-enterprise.elastic.co/s/lamn7fwv2wwy2/tests/:x-pack:plugin:yamlRestTest/org.elasticsearch.xpack.test.rest.XPackRestIT/test%20%7Bp0=data_stream%2F10_basic%2FGet%20data%20stream%20api%20check%20existence%20of%20replicated%20and%20allow_custom_routing%20fields%7D

**Reproduction line:**
`./gradlew ':x-pack:plugin:yamlRestTest' --tests "org.elasticsearch.xpack.test.rest.XPackRestIT.test {p0=data_stream/10_basic/Get data stream api check existence of replicated and allow_custom_routing fields}" -Dtests.seed=862835B30F4AEBBB -Dtests.locale=vi -Dtests.timezone=America/Denver -Druntime.java=8`

**Applicable branches:**
7.16

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.test.rest.XPackRestIT&tests.test=test%20%7Bp0%3Ddata_stream/10_basic/Get%20data%20stream%20api%20check%20existence%20of%20replicated%20and%20allow_custom_routing%20fields%7D

**Failure excerpt:**
```
java.lang.AssertionError: Failure at [data_stream/10_basic:652]: field [data_streams.0.allow_custom_routing] is null

  at __randomizedtesting.SeedInfo.seed([862835B30F4AEBBB:E7C0A69A1B68643]:0)
  at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:482)
  at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:455)
  at sun.reflect.GeneratedMethodAccessor15.invoke(null:-1)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at java.lang.Thread.run(Thread.java:748)

  Caused by: java.lang.AssertionError: field [data_streams.0.allow_custom_routing] is null

    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.assertTrue(Assert.java:41)
    at org.junit.Assert.assertNotNull(Assert.java:712)
    at org.elasticsearch.test.rest.yaml.section.MatchAssertion.doAssert(MatchAssertion.java:78)
    at org.elasticsearch.test.rest.yaml.section.Assertion.execute(Assertion.java:65)
    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:471)
    at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:455)
    at sun.reflect.GeneratedMethodAccessor15.invoke(null:-1)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
    at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
    at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
    at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
    at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
    at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
    at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
    at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
    at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
    at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
    at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
    at java.lang.Thread.run(Thread.java:748)

```

### PR DESCRIPTION
**Pull request by martijnvg**
Split yaml test that verifies allow_custom_routing and replicated fields are included in get data stream api.
This is because `allow_custom_routing` field is only included from 8.0 and
`replicated` field is only included from 7.16. Each test has its own skip version section.
The current test was reused in bwc qa tests, which caused test failures.

Closes #81462

### CODE REVIEW

**Review by dakrone — APPROVED** [review]
LGTM

**Comment by martijnvg** [comment]
@elasticmachine update branch

**Comment by martijnvg** [comment]
Full ci failure seems to be caused by a failure to invoke a web hook handler:

```
10:54:12 Sending request to url: https://homer.app.elstc.co/webhook/jenkins/build-finished
10:54:44 Treating class org.apache.http.conn.HttpHostConnectException(Connect to homer.app.elstc.co:443 [homer.app.elstc.co/35.188.12.98] failed: Connection timed out (Connection timed out)) as 408 Request Timeout
10:54:44 ERROR: Build step failed with exception
10:54:44 hudson.AbortException: Fail: Status code 408 is not in the accepted range: 100:399
10:54:44 	at jenkins.plugins.http_request.HttpRequestExecution.responseCodeIsValid(HttpRequestExecution.java:414)
10:54:44 	at jenkins.plugins.http_request.HttpRequestExecution.processResponse(HttpRequestExecution.java:424)
10:54:44 	at jenkins.plugins.http_request.HttpRequestExecution.authAndRequest(HttpRequestExecution.java:329)
10:54:44 	at jenkins.plugins.http_request.HttpRequestExecution.call(HttpRequestExecution.java:260)
10:54:44 Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to elasticsearch-ci-immutable-debian-10-1639387933725322783
10:54:44 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1797)
10:54:44 		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
10:54:44 		at hudson.remoting.Channel.call(Channel.java:1001)
10:54:44 		at jenkins.plugins.http_request.HttpRequest.perform(HttpRequest.java:408)
10:54:44 		at org.jenkinsci.plugins.postbuildscript.processor.Processor.processBuildSteps(Processor.java:180)
10:54:44 		at org.jenkinsci.plugins.postbuildscript.processor.Processor.processScripts(Processor.java:91)
10:54:44 		at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:79)
10:54:44 		at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:73)
10:54:44 		at org.jenkinsci.plugins.postbuildscript.PostBuildScript.perform(PostBuildScript.java:77)
10:54:44 		at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
10:54:44 		at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:806)
10:54:44 		at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:755)
10:54:44 		at hudson.model.Build$BuildExecution.post2(Build.java:178)
10:54:44 		at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:699)
10:54:44 		at hudson.model.Run.execute(Run.java:1913)
10:54:44 		at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
10:54:44 		at hudson.model.ResourceController.execute(ResourceController.java:99)
10:54:44 		at hudson.model.Executor.run(Executor.java:431)
10:54:44 Caused: java.lang.IllegalStateException
10:54:44 	at jenkins.plugins.http_request.HttpRequestExecution.call(HttpRequestExecution.java:263)
10:54:44 	at jenkins.plugins.http_request.HttpRequestExecution.call(HttpRequestExecution.java:79)
10:54:44 	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
10:54:44 	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
10:54:44 	at hudson.remoting.Request$2.run(Request.java:376)
10:54:44 	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
10:54:44 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10:54:44 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
10:54:44 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
10:54:44 	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:122)
10:54:44 	at java.lang.Thread.run(Thread.java:748)
10:54:44 Build step 'Execute scripts' marked build as failure
```

**Comment by martijnvg** [comment]
@elasticmachine run elasticsearch-ci/full-bwc

**Pull request merged**
