### PR TITLE
[TEST] Migrated ccs-unavailable-clusters QA tests

### PR DESCRIPTION
**Pull request by jozala**
Ccs-unavailable-clusters QA tests migrated to the new REST testing framework, using `elasticsearch.internal-java-rest-test` Gradle plugin

### CODE REVIEW

**Review by mark-vieira — APPROVED** [review]
LGTM

**Comment by mark-vieira** [comment]
@jozala I think those CI failures are due to an out of date branch.

**Comment by mark-vieira** [comment]
@elasticmachine update branch

**Comment by jozala** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.x|[](https://github.com/elastic/elasticsearch/pull/114826)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

**Pull request merged**
