### PR TITLE
[ML][TEST] Fix randomly failing HLRC test

### PR DESCRIPTION
**Pull request by edsavage**
Made changes to ensure that unique IDs are generated for model snapshots
used by the deleteExpiredDataTest test in the MachineLearningIT suite.

Previously a sleep of 1s was performed between jobs under the assumption
that this would be sufficient to guarantee that the timestamps used in
the composition of the snapshot IDs would be different.

The new approach is to wait on the condition that the old and new
timestamps are in fact different (to 1s resolution).

### CODE REVIEW

**Comment by droberts195** [comment]
I think we might need a similar `assertBusy` on line 884.  At a glance you'd think this place is OK, because we deliberately hack the timestamp on the old model snapshot document to be from a day ago.  But because we _don't_ hack the `_id` the hacked document can get overwritten by the job that's opened on line 885, if this whole sequence of events runs within the same second.

**Review by droberts195 — APPROVED** [review]
LGTM

**Comment by edsavage** [comment]
Jenkins retest elasticsearch-ci/2

**Comment by edsavage** [comment]
run elasticsearch-ci/2

**Comment by jtibshirani** [comment]
@edsavage would it be possible to backport this to 7.0 and 6.7 as well? The same failures have popped up in CI for these branches.

**Comment by cbuescher** [comment]
Failed again on 6.7, would be nice to get the backport(s) in or mute the test there if it takes longer.

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.7+multijob-unix-compatibility/os=oraclelinux-6/98/console

**Comment by edsavage** [comment]
> Failed again on 6.7, would be nice to get the backport(s) in or mute the test there if it takes longer.
> 
> https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.7+multijob-unix-compatibility/os=oraclelinux-6/98/console

Backported to 6.7 and 7.0 branches - if any further failures are seen this test will be muted

**Pull request merged**
