### PR TITLE
Remove unnecessary optimizations for TermsSetQueryBuilder

### PR DESCRIPTION
**Pull request by gf2121**
Remove unnecessary codes left by #67223. 

cc @jimczi

### CODE REVIEW

**Comment by jimczi** [comment]
@elasticmachine ok to test

**Comment by gf2121** [comment]
> gf2121 force-pushed the gf2121:follow_up_#67223 branch from 7e10aeb to 1bfde74 1 hour ago

I force pushed the branch to rebase this commit on the newest master to fix the failed checks. There is no change on the commit itself :)

**Comment by jimczi** [comment]
@elasticmachine ok to test

**Review by jimczi — APPROVED** [review]
Looks good to me, thanks @gf2121 !

**Pull request merged**
