### PR TITLE
add support to order buckets by `top_hits` aggregation's max score

### PR DESCRIPTION
**Pull request by martijnvg**

### CODE REVIEW

**Comment by jimferenczi** [comment]
I don't like the fact that we need to add a max aggregation to sort the top terms but it can save a lot of memory if the breadth_first mode is used. The change that you propose does not play nicely with the breadth first mode. The good thing about the max aggregation (vs the top hits) is that the memory footprint to compute the max score is bounded. When the breadth_first mode is used we compute the terms aggregation and the max scores in one pass and the top hits are computed in a second pass where only the top terms are replayed. If the terms aggregation needs the top hits then we cannot delay anything and we need to compute the tophits on all the documents that match the query.

**Comment by jpountz** [comment]
I agree the fact that top hits cannot use breadth_first anymore is a concern.

**Comment by martijnvg** [comment]
Wait, my understanding is that the `breadth_first` optimization can't be used when score is required by an agg ( top_hits sort by score by default). So my understanding was incorrect.

I really don't like that we have to use a `max` with a script in order to make the field collapse use case work. This PR looked like an easy way out... I wonder if top_hits can be a bit smarter and kind of do what `max` agg does for selecting the best buckets and then for those buckets compute TopDocs. (maybe keep track of most relevant ScoreDoc/FieldDoc, and then when building shard level response computing TopDocs only for the top buckets)

**Comment by jimferenczi** [comment]
@martijnvg the support for `breadth_first` aggs that require scoring has been added recently:
https://github.com/elastic/elasticsearch/pull/18127

> I wonder if top_hits can be a bit smarter and kind of do what max agg does for selecting the best buckets and then for those buckets compute TopDocs. (maybe keep track of most relevant ScoreDoc/FieldDoc, and then when building shard level response computing TopDocs only for the top buckets)

This sounds like `breadth_first` to me ;) I wonder if we could just add a sort mode in the terms agg directly. As @jpountz says in this PR: https://github.com/elastic/elasticsearch/pull/18112 it has an impact on the API/impls but IMO it would simplify the field_collapsing use case.

**Comment by jpountz** [comment]
I am wondering whether we could find a way for the `top_hits` aggregation and the parent terms aggregation to communicate so that the `top_hits` could know that the parent terms agg both sorts by it and runs with breadth-first so that it would only collect the max scores on the first pass.

Another idea would be to add a dedicated aggregation for the `top_hits` under `terms` sorted by score use-case. It could add the max aggregation under the hood, etc. but keep the request and response clean?

**Comment by martijnvg** [comment]
> the support for breadth_first aggs that require scoring has been added recently:
#18127

That is great @jimferenczi :) I missed that.

> Another idea would be to add a dedicated aggregation for the top_hits under terms sorted by score use-case. It could add the max aggregation under the hood, etc. but keep the request and response clean?

I like this idea. I'll try this out.

**Comment by dakrone** [comment]
@martijnvg ping, is this still applicable?

**Comment by martijnvg** [comment]
@dakrone No, I never got back to this. Closing and will open a new pr when I get back to this.

**Pull request closed without merging**
