### PR TITLE
Only update response headers if we have a new one

### LINKED ISSUE #35754: Script queries using joda time getMillis() slower than using java time toInstant().toEpochMilli()
**Elasticsearch version** (`bin/elasticsearch --version`):
Version: 6.5.0, Build: default/tar/816e6f6/2018-11-09T18:58:36.352602Z, JVM: 1.8.0_191

**Plugins installed**: []
No extra plugins

**JVM version** (`java -version`):
java -version
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

**Description of the problem including expected versus actual behavior**:
I've been using script queries that called `getMillis()` without issues until I upgraded to `6.5.0` after I started noticing serious query time deterioration (I'm talking about tens of seconds up from a few seconds), eventually by reading the changelog I realized that joda time was being deprecated, after switching the `getMillis()` call to `toInstant().toEpochMilli()` I got back the original query times (the ones before the upgrade). See a more detailed description [in this PR](https://github.com/elastic/elasticsearch/pull/31441#issuecomment-439458673). Since I've been asked to open an issue with the steps to reproduce it here they are.

**Steps to reproduce**:
 1. Download and start elasticsearch 6.5.0
 2. Download and start kibana 6.5.0
 3. Load the `Sample web logs` sample datasets
 4. Increase the doc count by copying the sample index (I copied it 40 times):
```
curl -XPOST "http://localhost:9200/_reindex" -H 'Content-Type: application/json' -d'
{
  "source": {
    "index": "kibana_sample_data_logs"
  },
  "dest": {
    "index": "kibana_sample_data_logs_1"
  }
}'
```
 5. Run the fast query:
```
curl -XPOST "http://localhost:9200/kibana_sample_data_logs*/_search" -H 'Content-Type: application/json' -d'
{
  "size": 0,
  "query": {
    "bool": {
      "must": [
        {
          "script": {
            "script": {
              "source": "doc[\"timestamp\"].value.toInstant().toEpochMilli() < params.millis",
              "lang": "painless",
              "params": {
                "millis": 1542747500000
              }
            }
          }
        }
      ]
    }
  }
}'
---
{
  "took" : 38,
  "timed_out" : false,
  "_shards" : {
    "total" : 201,
    "successful" : 201,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 94259,
    "max_score" : 0.0,
    "hits" : [ ]
  }
}
```

 6. Run the slow query:
```
curl -XPOST "http://localhost:9200/kibana_sample_data_logs*/_search" -H 'Content-Type: application/json' -d'
{
  "size": 0,
  "query": {
    "bool": {
      "must": [
        {
          "script": {
            "script": {
              "source": "doc[\"timestamp\"].value.getMillis() < params.millis",
              "lang": "painless",
              "params": {
                "millis": 1542747500000
              }
            }
          }
        }
      ]
    }
  }
}'
---
#! Deprecation: Use of the joda time method [getMillis()] is deprecated. Use [toInstant().toEpochMilli()] instead.
{
  "took" : 1088,
  "timed_out" : false,
  "_shards" : {
    "total" : 201,
    "successful" : 201,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 94259,
    "max_score" : 0.0,
    "hits" : [ ]
  }
}
```

We're talking about 95K documents and the deprecated query is already 30 times slower, one could argue that it is because the deprecation log itself but from my experience with bigger indexes the problem becomes more noticeable, the slow query seems to slow down linearly with the number of documents checked by it.

### PR DESCRIPTION
**Pull request by jasontedor**
Currently when adding a response header, we do some de-duplication, and maybe drop the header on the floor if we have reached capacity. Yet, we still update the thread local tracking the response headers. This is really expensive because under the hood there is a shared reference that we synchronize on. In the case of a request processed across many shards in a tight loop, this contention can be detrimental to performance. We can avoid updating the thread local in these cases though, when the response header is duplicate of one that we have already seen, or when it's dropped on the floor. This commit addresses these performance issues by avoiding the unnecessary set.

Relates #35754
Relates #37530

### CODE REVIEW

**Comment by jasontedor** [comment]
I still need to do benchmarking on this, so consider this ready for review but WIP. I will do the benchmarking and update this thread with the results ASAP.

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by jasontedor** [comment]
@elasticmachine run gradle build tests 1

**Comment by jasontedor** [comment]
@elasticmachine run the docbldesx

**Comment by jasontedor** [comment]
@elasticmachine run the gradle build tests 1

**Review by danielmitterdorfer — APPROVED** [review]
Thanks for addressing this. LGTM

**Pull request merged**
