### PR TITLE
Release aggregations early during the aggregation phase

### PR DESCRIPTION
**Pull request by iverase**
We currently wait until the search is over to release the aggregations objects but we can do it early, just after building the sparse representation. This might be useful when there are a lots of top level aggregations.

### CODE REVIEW

**Review by nik9000 — COMMENTED** [review]
I wonder if it's better to `null` the references to the big things and manually release them once done. Like, at the end of building the aggregation. In that case we can close whenever

**Comment by iverase** [comment]
> I wonder if it's better to null the references to the big things and manually release them once done

That would mean we will need to visit all aggregations to nullify big things? I was trying to avoid changing the aggregations by releasing them using the releasable property.

**Comment by nik9000** [comment]
> That would mean we will need to visit all aggregations to nullify big things?

I was thinking we might nullify when we build the internal context anyway. But to avoid touching all of the code that makes sense.

**Comment by iverase** [comment]
Still that means to visit every aggregation and decide what code deserves to be nullify, not sure about that approach.

**Comment by iverase** [comment]
@elasticmachine update branch

**Review by nik9000 — APPROVED** [review]

**Pull request merged**
