### PR TITLE
Give the kibana system user permission to read security entities

### PR DESCRIPTION
**Pull request by hop-dev**
As part of the entity store feature we need the Kibana system user to be able to read entity store entities.

### What is the entity store? 

The entity store is a new security feature which extracts entities (hosts & users) from logs and metrics data. 

The documents in the `.entities.v1.latest.security*` index each represent an entity extracted from event data, properties are added as we see them over time, for example for a host we store ip, mac, and OS information, for a user we store things like email, name, roles. 

### Why does Kibana system need read access? 

Primarily in 8.16.0 we need read access in order to execute an enrich policy on a regular basis as part of our architecture. 

But going forward we will be building experiences on top of the entities index, for example the Kibana system user will read the entities index in order to perform risk scoring on the entities.

### CODE REVIEW

**Comment by hop-dev** [comment]
@elasticsearchmachine merge upstream

**Comment by hop-dev** [comment]
@elasticmachine merge upstream

**Comment by kkrik-es** [comment]
Oops this was unintended, apologies.

**Comment by azasypkin** [comment]
Hey @hop-dev,

Would you mind updating PR description with more details about the requirements behind this change?

* Why do we need to make this change exactly? What part of Kibana will be leveraging this permission?
* Do you have any discussion or issue you could link to from this PR?
* What does create this index and ingest data to it? 
* Is it a system or hidden index?
* What _kind of data_ is stored in this index? 

The more details, the better. Thanks!

**Comment by hop-dev** [comment]
@azasypkin I've updated the description, let me know if you need any more info.

**Comment by hop-dev** [comment]
@elasticmachine merge upstream

**Review by azasypkin — APPROVED** [review]
> @azasypkin I've updated the description, let me know if you need any more info.

That’s super helpful, @hop-dev, thanks! One last question - are these indices created with `hidden: true`?

**Comment by hop-dev** [comment]
@azasypkin they currently are not, but I have been thinking we should hide them because of the dot prefix, why do you ask?

**Comment by azasypkin** [comment]
> @azasypkin they currently are not, but I have been thinking we should hide them because of the dot prefix, why do you ask?

Yeah, if we don’t want users to interact with these indices directly, then making them hidden or even system indices (depends on your requirements, a bit more involved, but much safer, see https://github.com/elastic/elasticsearch/blob/430ec3b1506c7d4223c4a24cfdb417ef726c1d87/modules/kibana/src/main/java/org/elasticsearch/kibana/KibanaPlugin.java#L25-L53 and https://github.com/elastic/elasticsearch/blob/430ec3b1506c7d4223c4a24cfdb417ef726c1d87/x-pack/plugin/fleet/src/main/java/org/elasticsearch/xpack/fleet/Fleet.java#L284-L292) makes total sense to me.

**Comment by hop-dev** [comment]
Really appreciate the guidance, I'll look into it 👍

**Comment by hop-dev** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.x|[](https://github.com/elastic/elasticsearch/pull/114520)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

**Pull request merged**
