### PR TITLE
[ES|QL] Verify aggregation filter's type is boolean to avoid class_cast_exception

### LINKED ISSUE #116116: [ES|QL] class_cast_exception is thrown when an aggregate filter has non-boolean literal child
I came across this edge case when working on supporting implicit casting from string literals for logical operators.

It happens when a non-boolean literal is provided as an input to a `WHERE` clause. If the `WHERE` clause is not under an aggregation, `VerificationException` is thrown as expected. However if it is under an aggregation, `class_cast_exception` is thrown, some checks might need to be added in `Analyzer`.

```
{
  "query": "row x = 1 | where \"true\""
}
'
{
  "error" : {
    "root_cause" : [
      {
        "type" : "verification_exception",
        "reason" : "Found 1 problem\nline 1:19: Condition expression needs to be boolean, found [KEYWORD]"
      }
    ],
    "type" : "verification_exception",
    "reason" : "Found 1 problem\nline 1:19: Condition expression needs to be boolean, found [KEYWORD]"
  },
  "status" : 400
}

{
  "query": "row x = 1 | stats count(*) where \"true\""
}
'
{
  "error" : {
    "root_cause" : [
      {
        "type" : "class_cast_exception",
        "reason" : "class org.elasticsearch.compute.data.BytesRefVectorBlock cannot be cast to class org.elasticsearch.compute.data.BooleanBlock (org.elasticsearch.compute.data.BytesRefVectorBlock and org.elasticsearch.compute.data.BooleanBlock are in unnamed module of loader java.net.FactoryURLClassLoader @67b8d45)"
      }
    ],
    "type" : "class_cast_exception",
    "reason" : "class org.elasticsearch.compute.data.BytesRefVectorBlock cannot be cast to class org.elasticsearch.compute.data.BooleanBlock (org.elasticsearch.compute.data.BytesRefVectorBlock and org.elasticsearch.compute.data.BooleanBlock are in unnamed module of loader java.net.FactoryURLClassLoader @67b8d45)"
  },
  "status" : 500
}
```

### PR DESCRIPTION
**Pull request by fang-xing-esql**
Resolves: #116116 

Verify aggregation filter's type in `Verifier` to avoid `class_cast_exception`. There is similar checks for a filter that's not under aggregation, the same check needs to be applied to filter under aggregation.

If a filter is not under aggregation, `verification_exception` is thrown for non-Boolean type conditions.
```
{"query": "row x = 1 | where \"true\""}
{
  "error" : {
    "type" : "verification_exception",
    "reason" : "Found 1 problem\nline 1:19: Condition expression needs to be boolean, found [KEYWORD]"
  },
  "status" : 400
}
```
If a filter is under aggregation, the plan passed `Verifier` as `Verifier` didn't check non-Boolean type conditions.
```
{"query": "row x = 1 | stats count(*) where \"true\""}
{
  "error" : {
    "type" : "class_cast_exception",
    "reason" : "class org.elasticsearch.compute.data.BytesRefVectorBlock cannot be cast to class org.elasticsearch.compute.data.BooleanBlock (org.elasticsearch.compute.data.BytesRefVectorBlock and org.elasticsearch.compute.data.BooleanBlock are in unnamed module of loader java.net.FactoryURLClassLoader @67b8d45)"
  },
  "status" : 500
}
```

This PR **doesn't** address the difference for `null` filter, the behavior of `null` filter is different when it is under or not under an aggregation. We might want to evaluate whether we want to make them behave the same way.

Null filter is allowed under aggregation
```
from employees
| stats max = max(salary), max_a = max(salary) where null,
        min = min(salary), min_a = min(salary) where to_string(null) == "abc"  
;

max:integer |max_a:integer|min:integer | min_a:integer
74999       |null         |25324       | null        
;
```

However if a null filter is not under an aggregation, `verification_exception` is thrown
```
{"query": "from sample_data | where null"}
{
  "error" : {
    "type" : "verification_exception",
    "reason" : "Found 1 problem\nline 1:26: Condition expression needs to be boolean, found [NULL]"
  },
  "status" : 400
}
```

### CODE REVIEW

**Review by costin — APPROVED** [review]
LGTM.
Please follow-up regarding the null type - the two should be consistent.
Note that likely we have different behavior since null is typically marked as false but in case of aggs might indicate missing filter.

**Comment by fang-xing-esql** [comment]
> LGTM. Please follow-up regarding the null type - the two should be consistent. Note that likely we have different behavior since null is typically marked as false but in case of aggs might indicate missing filter.

Thank you @costin ! I'll open an issue to keep track of the null filter, postgresql and mysql allow it, `where null` doesn't error out, empty resultset is returned, similar to null filter under aggregation, making it consistent is better.

**Comment by fang-xing-esql** [comment]
@elasticmachine update branch

**Comment by fang-xing-esql** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.x|[](https://github.com/elastic/elasticsearch/pull/116356)|
|✅|8.16|[](https://github.com/elastic/elasticsearch/pull/116360)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

**Pull request merged**
