### PR TITLE
Require System Index Descriptors to allow a specific suffix

### PR DESCRIPTION
**Pull request by AthenaEryma**
This PR:
1) Adjusts all system index descriptors to allow a suffix (currently `-reindexed-for-8`). Only small adjustments were required for this.
2) Implements a check at startup to verify that all system index descriptors from installed plugins allow the above suffix.
3) Modifies all the tests which used system index patterns which did not allow for the above suffix (and thus caused failures) to allow for it.

This ensures that we can safely create new indices within these descriptors' patterns, so that we can reindex them if necessary prior to an upgrade.

### CODE REVIEW

**Review by williamrandolph — CHANGES_REQUESTED** [review]
I'd like to see Javadoc about this requirement in the `SystemIndexDescriptor` class so that there's some kind of developer-facing documentation of the requirement for index patterns.

**Comment by gwbrown** [comment]
Good call @williamrandolph, I added Javadoc in https://github.com/elastic/elasticsearch/pull/78355/commits/6c607e7f262e2b6f3afe6fb4f51ff64e3fa30488 on the constructors, as well as the field itself and associated getter. Thanks!

**Review by williamrandolph — APPROVED** [review]
Javadocs look good! It looks like some tests are still failing, but assuming that those are just more spots to add `*`s, then I think this will be good to go once those are fixed.

**Comment by gwbrown** [comment]
As of this post, this PR contains the contents of https://github.com/elastic/elasticsearch/pull/78492 as well, because this PR needs that one to pass and I'd like to see CI turn green. My plan is to let https://github.com/elastic/elasticsearch/pull/78492 get merged first, then revert d3fd0e4 in this PR, merge master into this PR, get a clean CI run that way, and merge.

**Pull request merged**
