### PR TITLE
Empty mapping to hold null meta

### PR DESCRIPTION
**Pull request by javanna**
With #72616 we have changed the way that empty mappings are created for an index. Accidentally such mappings have been created with an empty meta map instead of null, which causes test failures in tests that compare mappings and are now finding an unexpected empty meta object which was not there before.

This commit fixes the empty mapping to not hold any meta, replacing the empty map with a null argument.

### CODE REVIEW

**Review by romseygeek — APPROVED** [review]
LGTM. Maybe add a specific test to check serialization of the empty mapper?

**Review by tlrx — APPROVED** [review]
LGTM

**Comment by javanna** [comment]
@romseygeek I pushed a test, and I also fixed the empty mappipng lookup to hold null meta instead of empty map.

**Review by romseygeek — APPROVED** [review]
Thanks @javanna

**Pull request merged**
