### PR TITLE
Make Minio Setup more Reliable

### LINKED ISSUE #37680: [CI] minio fails due to port clashes
Looks like minio is failing again due to clashes with already opened port.
This seems to have been already handled through 
https://github.com/elastic/elasticsearch/issues/32701 and https://github.com/elastic/elasticsearch/issues/32208 but it still occurred in master.

For example:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/1411/console
```
Unable to start the server: Port :36076 is already in use.
```

It doesn't seem like the port is hardcoded:
https://github.com/elastic/elasticsearch/blob/7394892b4c36f44d5addb2abd2dbca7453cb2d79/plugins/repository-s3/build.gradle#L205

Maybe it's a race condition when gradle runs in parallel?

### PR DESCRIPTION
**Pull request by original-brownbear**
* Retry starting Minio five times in case we run into a race between finding the free port and starting it up
* Closes #37680

### CODE REVIEW

**Review by alpar-t — CHANGES_REQUESTED** [review]
Are there any downside to creating a `minio-fixture` using `elasticsearch.test.fixtures` plugin ?  I think it would be a cleaner more consistent solution, than having a special case with custom retries, finding free port, parsing output lines etc. 
AFAIK  minio has a docker image that we could readily use. The plugin takes care of providing the ports used for the mapping as system properties. You can check existing uses of the plugin.

**Comment by atorok** [comment]
@original-brownbear I saw your comment on the ticket just now. There's a bit of a learning curve to the plugin for sure, but past that it doesn't seem like a difficult change to go that route directly and have this fixed for good. Let me know what you think, I'm not opposed to merging this in either, it's still better to have the test passing, but wouldn't like to have this complexity in the build for long.

**Comment by original-brownbear** [comment]
@atorok 

I agree with everything you say :). That said: My reasoning here would be I can't fix this using the plugin now/today I'm afraid but tests are still kind of horrible so I tried dealing with this one real quick.
=> maybe merge this one and add an issue for moving this to the plugin?

**Review by alpar-t — APPROVED** [review]
I'm not opposed to merging this to stop the failures. 
I do think that moving this to docker is easier than it looks.

**Comment by original-brownbear** [comment]
@atorok thanks, will add an issue for that move in a sec :)

**Comment by original-brownbear** [comment]
https://github.com/elastic/elasticsearch/issues/37783

**Pull request merged**
