### PR TITLE
Search of remote clusters with no shards results in successful status.

### PR DESCRIPTION
**Pull request by quux00**
ccs_minimize_roundtrips=true was not checking if no shards were present to 
search before setting the cluster search status. If number of shards is zero, 
then cluster search status should be successful. This aligns ccs_minimize_roundtrips=true 
with the false setting and how it worked in earlier versions.

Fixes bug #100350

### CODE REVIEW

**Comment by tylerperk** [comment]
@quux00 Can we backport this to the next 8.10 and 8.11 patches?

**Review by piergm — APPROVED** [review]
LGTM!

**Comment by droberts195** [comment]
Since this problem has such a big impact on ML datafeeds used within a large CCS environment I propose that this fix should be backported to 8.11 and 8.10. I've added the relevant labels, so if the changes backport cleanly hopefully this will involve no extra effort. Let me know if you disagree.

**Comment by quux00** [comment]
Manual backport of 8.10 here: https://github.com/elastic/elasticsearch/pull/100458

**Comment by quux00** [comment]
The 8.11 and 8.10 backports have been completed, so it should be in ES releases for 8.10.4 and 8.11.1 and 8.12.0.

**Comment by andreidan** [comment]
Removing `backport pending` as this was backported to `8.10` with https://github.com/elastic/elasticsearch/pull/100458

**Pull request merged**
