### PR TITLE
Datasketches HllSketch aggregation for ElasticSearch

### PR DESCRIPTION
**Pull request by nooneuse**
Hello,
I wrote this Datasketches HllSketch aggregation plugin for elasticsearch. This plugin is simaliar with hllsketch function of duird's dataskeches module. It do the same job accroding to the design.
I tested it in my online situations for some time and it works well. I want Contribute it so I open an discuss: https://discuss.elastic.co/t/can-i-contribute-a-datasketches-aggregation-plugin-for-elasticsearch-what-should-i-provide/237394/2
You asked me to perpare all the license, codes we need. so I gatherd all license of my dependecies, and put them all in my plugin folder with codes("plugins/search-datasketches"). This is a plugin that only added to the "plugins" folder, and will not change any main code of ElasticSearch.
I have tested this plugin by built a master branch elasticsearch, installed my plugin, wrote some data and ran the aggregation. It seems works well.
but when I put those tests into IntegTest. It failed becasue of security policy problem.
I opened an issue and asked for help, but no one reply for a long time: https://discuss.elastic.co/t/how-to-grant-permission-in-esclientyamlsuitetestcase-integtest/241975

By the way, Here is how the hllsketch plugin use:
{ "aggregations": { "sketches_uv": { "hll_sketch": { "field": "sketches", "default_lgk": 15 } } } }
and it will return the aggregation result for field "sketches".

Please help to review my code and help me solve the integtest problem.

Thank you very much

### CODE REVIEW

**Comment by polyfractal** [comment]
Hi @nooneuse, thanks for the PR!  I'm afraid to say that Elasticsearch already has a HyperLogLog-based aggregation for calculating cardinality.  The [docs are here](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-cardinality-aggregation.html), and the code lives in the [CardinalityAggregator](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/search/aggregations/metrics/CardinalityAggregator.java) (and related classes) and the [HyperLogLogPlusPlus classes](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/search/aggregations/metrics/HyperLogLogPlusPlus.java)

Sorry!  For future reference, if you're planning on a large PR like this it's best to open a ticket first asking.  That way we can either let you know if there's existing functionality implemented (or planned), or if it's something we're not likely to merge for some reason.  That helps avoid wasted effort due to miscommunication.

I'm going to close this since it has already been implemented in the `cardinality` aggregation

**Comment by nooneuse** [comment]
hi,@polyfractal thanks for reply!
I also use cardinality aggregation very often, and i think this hllsketch aggregation is completely not the same thing between cardinality aggregation.
hllsketch is based on apache Datasketches which is a pre-aggregation container can be seriralized in binary data.
hllsketch aggregation is use binary data that user generated.
To use this plugin. User needs generate their own hllsketch binary data and write to a binary data field.
To use cardinality aggregation, User jsut put data to a keyword,long...etc field.

**Comment by nooneuse** [comment]
This function is not coverd by cardinality aggregation.
This plugin is used for pre-aggregation situation.(Pre-aggregation sketch data is generated by user themselves)
Please reconsider this pr. Thank you very much.

**Comment by nooneuse** [comment]
hi, This aggregation plugin is require serialized hllsketch data. which need write as binary field.

**Comment by nooneuse** [comment]
@polyfractal please also see https://github.com/elastic/elasticsearch/issues/61136
this plugin is a extend for cardinality aggregation, not the same...

**Comment by polyfractal** [comment]
Hi @nooneuse, you're right!  I misunderstood the purpose of the PR, sorry about that :)  Is it correct to say this allows the user to index HLL data structures directly, and then use those later in the cardinality aggregation?

If that's accurate, we actually have a WIP PR adding that functionality soon as well: https://github.com/elastic/elasticsearch/pull/60119  The author is on vacation at the moment but we expect it to merge as soon as he's back.

Sorry, again! We definitely agree it's useful functionality and are excited to add it, but will probably use #60119 since it's nearly done.

If I misunderstood the purpose again please let me know! :)

**Comment by nooneuse** [comment]
> #60119

hi, @polyfractal thanks for reply!
I read the #60119 and have 2 questions on it, please help me answer.
1.Does it support the apache datasketches generated data?
    My plugin is support for apache datasketches(see: https://datasketches.apache.org/), and I think #60119 is not based on this.
    If the user's data source is already generated apache datasketches data, which is also be used in druid. How use could use their generated sketches in ES?
2.How does the performance of this feature compare to apache datasketches? 
    Performance, especially QPS and response time, is also an important point for users. I wonder if you have compared it with other similar products?

**Comment by polyfractal** [comment]
> Does it support the apache datasketches generated data?

Not directly, no.  Or at least, I don't think so.  We didn't look at their serialization format, and ours is specifically JSON-based rather than a binary format.  But I believe they have implemented a "canonical" HyperLogLog, so it should be compatible with our HLL implementation too.  Just need a translation layer to convert their format into ours and it should work fine I believe.

We'll be documenting our format pretty extensively (including required hashing scheme, etc).  If a conversion from Apache Datasketch format is widely requested, we could probably add an ingest processor or something to facilitate the conversion

> How does the performance of this feature compare to apache datasketches?

I'm not aware of any specific benchmarks comparing our HLL implementation against other implementations, but I'm not sure a comparison against e.g. Druid is very comparable anyway.  Query latency and throughput are very dependent on system architecture, not just the data structure being used, so the wide difference in how Druid and ES are built will probably affect benchmarks more drastically than the HLL implementation.

I'm not sure if Apache Datasketches was even around [when we added cardinality originally](https://github.com/elastic/elasticsearch/issues/5426), which is probably at least partially why we don't have direct comparisons :)

**Comment by nooneuse** [comment]
> > Does it support the apache datasketches generated data?
> 
> Not directly, no. Or at least, I don't think so. We didn't look at their serialization format, and ours is specifically JSON-based rather than a binary format. But I believe they have implemented a "canonical" HyperLogLog, so it should be compatible with our HLL implementation too. Just need a translation layer to convert their format into ours and it should work fine I believe.
> 
> We'll be documenting our format pretty extensively (including required hashing scheme, etc). If a conversion from Apache Datasketch format is widely requested, we could probably add an ingest processor or something to facilitate the conversion
> 
> > How does the performance of this feature compare to apache datasketches?
> 
> I'm not aware of any specific benchmarks comparing our HLL implementation against other implementations, but I'm not sure a comparison against e.g. Druid is very comparable anyway. Query latency and throughput are very dependent on system architecture, not just the data structure being used, so the wide difference in how Druid and ES are built will probably affect benchmarks more drastically than the HLL implementation.
> 
> I'm not sure if Apache Datasketches was even around [when we added cardinality originally](https://github.com/elastic/elasticsearch/issues/5426), which is probably at least partially why we don't have direct comparisons :)

Hi, @polyfractal thank you for reply.

I understand how #60119 support other formats! but I just have another question, please answer, thank you!
I noticed this function is come with xpack, which can has many different licenses. 
Is this feature included in the free license? Do I need to buy a license in order to use this feature？

**Comment by polyfractal** [comment]
I believe it is currently planned to be a Basic feature, meaning it will be free (like basic security, rollups, etc) :)

**Pull request closed without merging**
