### PR TITLE
fixing examples

### PR DESCRIPTION
**Pull request by georgewallace**
Validating samples across elasticsearch and marking samples as reviewed.

### CODE REVIEW

**Comment by georgewallace** [comment]
Closes https://github.com/elastic/platform-docs-team/issues/526
Closes https://github.com/elastic/platform-docs-team/issues/520

**Comment by leemthompo** [comment]
Two things strike me here:

- we shouldn't need to manually verify anything that is already explicitly tested
- where possible, adding tests would be more sustainable than verifying manually

**Comment by georgewallace** [comment]
@leemthompo Agreed. We are only spot checking the top 20 articles. I added the comments to all examples, not just the untested examples, because I tested all of them. I am ok to not put the comments in and just review each of the 20 articles. That might be best. the plan is to automate this for all the rest. But wanted to fix the top 20 articles.

**Comment by leemthompo** [comment]
Roger that @georgewallace! You can definitely assign a couple of these to writers too :)

**Review by leemthompo — APPROVED** [review]

**Comment by georgewallace** [comment]
They are all under https://github.com/elastic/platform-docs-team/issues/527. Happy to assign some out, but know everyone is busy.

**Comment by georgewallace** [comment]
@leemthompo I was thinking and I will just close this PR. After thinking about it, we can think about comment automation when testing examples or another way to do it, but for now it would only show on 20 of the pages across the repo which doesn't make sense. Thanks for the feedback.

**Pull request closed without merging**
