### PR TITLE
Check that _value is used in aggregations script before setting value to specialValue

### LINKED ISSUE #14262: NullPointerException when combining field and script in aggregation
Using a script in the percentile aggregation in Kibana 4, this results in an Elasticsearch NullPointerException. [Example](https://www.dropbox.com/s/op3kzha6qwjlbpe/Screenshot%202015-10-23%2014.08.17.png?dl=0). This seems to be caused by Kibana including both the field and script property. It is not possible to exclude the field property from Kibana.

For the sake of simplicity I narrowed this down to a plain simple ES query. Elasticsearch 1.7.3 on a bare CentOS 7.1 box installed using the yum repo. No changes have been made to the ES config.

Be sure to have one document in an index with a numerical field.

    $ curl -XDELETE localhost:9200/test
    
    $ curl -XPUT localhost:9200/test/test/1?pretty=true -d '{
        "metric": 100
    }'
    
    {
      "_index" : "test",
      "_type" : "test",
      "_id" : "1",
      "_version" : 1,
      "created" : true
    }

Mapping has become a long value, which is fine for percentile agg

    $ curl -XGET localhost:9200/test/_mapping?pretty=true
    
    {
      "test" : {
        "mappings" : {
          "test" : {
            "properties" : {
              "metric" : {
                "type" : "long"
              }
            }
          }
        }
      }
    }

Running a query with both the field and script properties supplied. Results in a NullPointerException. I expected that the script would have precedence.

    $ curl -XPOST localhost:9200/test/test/_search?pretty=true -d '{
      "size": 0,
      "query": {
        "match_all": {}
      },
      "aggs": {
        "some-agg": {
          "percentiles": {
            "field": "metric",
            "lang": "expression",
            "script": "1"
          }
        }
      }
    }'
    
    {
      "took" : 4,
      "timed_out" : false,
      "_shards" : {
        "total" : 5,
        "successful" : 4,
        "failed" : 1,
        "failures" : [ {
          "index" : "test",
          "shard" : 2,
          "status" : 500,
          "reason" : "QueryPhaseExecutionException[[test][2]: query[ConstantScore(cache(_type:test))],from[0],size[0]: Query Failed [Failed to execute main query]]; nested: NullPointerException; "
        } ]
      },
      "hits" : {
        "total" : 0,
        "max_score" : 0.0,
        "hits" : [ ]
      },
      "aggregations" : {
        "some-agg" : {
          "values" : {
            "1.0" : "NaN",
            "5.0" : "NaN",
            "25.0" : "NaN",
            "50.0" : "NaN",
            "75.0" : "NaN",
            "95.0" : "NaN",
            "99.0" : "NaN"
          }
        }
      }
    }

### PR DESCRIPTION
**Pull request by alexshadow007**
FIx #14262

### CODE REVIEW

**Comment by clintongormley** [comment]
@jdconrad could you review this please?

**Comment by jdconrad** [comment]
@alexshadow007 Thanks for looking into this, and I'm fine with this fix, but do you know why setNextVar is being called at all with _value if it's not part of a script?  If it's possible it may be a better fix in that area of the code to not call setNextVar when it's not necessary.  This seems like a bit of a workaround for some unexpected behavior to me.

**Comment by rjernst** [comment]
I think I see now how this can happen. We init specialValue to null in ExpressionScriptEngineService. If the script does not use _value, then that null is passed through, but setNextVar is always called. An alternative might be to always init specialValue. However, I'm fine with the change as is, but would add a comment to the test to make clear this second case is being tested at the same time (eg something like `// make sure agg that does not use _value works too`).

**Comment by jdconrad** [comment]
@alexshadow007 This has been pushed to master.  Thanks for the contribution.

**Comment by jdconrad** [comment]
Also back ported to 2.3 now.

**Pull request merged**
