### PR TITLE
Update to Lucene 5.1 snapshot r1671277

### PR DESCRIPTION
**Pull request by rmuir**
Upgrades to latest snapshot of lucene 5.1 release branch.

We actually have interesting stuff in 5.2, but I wanted to do this step first. It helps test the lucene release and allows us to deal with changes to the new PostingsEnum api in 5.1, without also having to tackle differences in Spans and other things in 5.2 at the same time.

### CODE REVIEW

**Comment by jpountz** [comment]
+1

**Comment by rmuir** [comment]
this upgrade is stuck on the same tests as the last one got stuck on. These only test via scripts and still have the same problems, still timesinks.

i'm not gonna do awaitsfix, i don't want to do it again. i want git rm.

**Comment by rjernst** [comment]
I fixed the test in question (actually it was a bug in the index lookup stuff since the change in behavior). I will run the full tests a couple more times.

**Comment by dadoonet** [comment]
Also pushed in parent project with this commit: https://github.com/elastic/elasticsearch-parent/commit/24bc54c6597934db60e8949bbc0236f2ef8fa416

**Pull request closed without merging**
