### PR TITLE
Upgrade HDRHistogram to 2.1.9

### LINKED ISSUE #23239: Upgrade HDRHistogram
We are currently on version 2.1.6 while 2.1.9 is out.

### PR DESCRIPTION
**Pull request by martinscholz83**
Fix #23239 

Upgrade HDRHistogram

### CODE REVIEW

**Comment by jpountz** [comment]
@maddin2016 Thanks, I'll make it run through CI and merge it if tests pass!

@elasticmachine test this please

**Comment by jpountz** [comment]
@elasticmachine test this please

**Comment by maddin2016** [comment]
I don't see whats going wrong. Something i have missed? If i run `gradle check` locally on my machine it ends with logs like this 
```
1> [2017-02-20T14:26:01,213][TRACE][o.e.a.b.TransportShardBulkAction] [node_t3] [[test][7]] sending op [indices:data/write/bulk[s]] to replica [test][7], node[U2Ba-LTiQRGkPPY9Qadl_Q], [R], s[STARTED], a[id=UURnQwtXTNqXab_jOK8_AQ] for request [BulkShardRequest
 [[test][7]] containing [delete {[test][RANDOM_BOGUS_TYPE______][a63]}]]
  1> [2017-02-20T14:26:01,213][TRACE][o.e.a.b.TransportShardBulkAction] [node_t3] [[test][7]] sending op [indices:data/write/bulk[s]] to replica [test][7], node[5chc467UTpK_GTtrv3Wk9g], [R], s[STARTED], a[id=OrWhtF84R5CE77j4DAeUGw] for request [BulkShardRequest
 [[test][7]] containing [delete {[test][RANDOM_BOGUS_TYPE______][a63]}]]
  1> [2017-02-20T14:26:01,229][TRACE][o.e.a.b.TransportShardBulkAction] [node_t5] action [indices:data/write/bulk[s][r]] completed on shard [[test][7]] for request [BulkShardRequest [[test][7]] containing [delete {[test][RANDOM_BOGUS_TYPE______][a63]}]]
```

**Comment by jpountz** [comment]
Don't worry, I think the problem is on the CI side. I'll look into it. Those logs are just trace logs indicating that the test framework tried to make the test fail by introducing a new type and some deleted documents (to make sure there are no features that rely on the fact that all docs in the index are live).

**Comment by jpountz** [comment]
@elasticmachine test this please

**Comment by jpountz** [comment]
@elasticmachine test this please

**Comment by jpountz** [comment]
Thanks @maddin2016 !

**Pull request merged**
