### PR TITLE
SQL: Remove the unused CONCAT token

### PR DESCRIPTION
**Pull request by palesz**
The `||` token is a leftover from the original grammar definition.
We don't have a `||` operator, the token is unused in our grammar.
String concatenation is implemented via the `CONCAT` function instead.

### CODE REVIEW

**Review by bpintea — APPROVED** [review]
lgtm

**Review by astefan — APPROVED** [review]
LGTM

**Review by matriv — APPROVED** [review]
LGTM.

Could you please open an issue to add this in the future? maybe a `good first issue`

**Review by costin — APPROVED** [review]
LGTM

**Pull request merged**
