### PR TITLE
Apm system monitoring 7x

### PR DESCRIPTION
**Pull request by cachedout**
This is a fix for the issue described here: https://github.com/elastic/apm-server/issues/2708

This extends changes made here to the `apm_system` user: https://github.com/elastic/elasticsearch/pull/40876

This is specifically made against the 7.x branch because in 8.0, we want to remove internal collectors for monitored services and so the configuration in the original bug report would not be supported. That said, I don't know if this is the preference of the Elasticsearch team and I defer to whatever they would like to do in that regard.

### CODE REVIEW

**Comment by cachedout** [comment]
@axw Can you confirm that this fixes the issue that you described in  elastic/apm-server#2708

@jakelandis Could you please help me find the appropriate reviewers for this change on the Elasticsearch team?

**Comment by jakelandis** [comment]
> This is specifically made against the 7.x branch because in 8.0, we want to remove internal collectors for monitored services and so the configuration in the original bug report would not be supported. That said, I don't know if this is the preference of the Elasticsearch team and I defer to whatever they would like to do in that regard.

@cachedout 
Could you please introduce this to 8.0 and then backport to 7.x.  Unless the conflicting change is already in master, it is preferred to add it and then remove it at the appropriate time.

**Comment by cachedout** [comment]
@jakelandis Will do. Thanks!

**Comment by axw** [comment]
@cachedout I've tested APM Server 7.2 with your ES branch, and it's working. Thanks!

**Pull request closed without merging**
