### PR TITLE
Remove script access to term statistics

### LINKED ISSUE #19359: Remove ability to gather index statistics in scripts (aka IndexLookup)
[IndexLookup](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-advanced-scripting.html) was added to have the ability to access term statistics from scripts. However, it has some limitations and it is not clear whether the effort to maintain the code is worth it (see also https://github.com/elastic/elasticsearch/pull/19334/files/7df2d06eb62dbbc5cc365153088993d70801c286#r70103016). I'll add the pros and cons as far as I know them here:
- when used for scoring IndexLookup cannot make use of sparse postings lists like a similarity and will therefore always be slower than a custom similarity
- IndexLookup always needs the list of tokens used in advance, cannot make use of rewrite query
- when used within a script field and scroll it will be terribly slow because all the caching mechanisms to get for example document frequency are currently broken, see https://github.com/elastic/elasticsearch/issues/17110
- it is rarely used

pros:
- IndexLookup makes it easy to test custom similarities as a script before one actually goes and writes a custom similarity
- there is currently no other way to access term statistics in a script (none that I know of anyway)

I'd be a little sad to see it go because it was useful for some of my experiments. But if I am the only one then so be it. I'd also be willing to work on a replacement.

### PR DESCRIPTION
**Pull request by rjernst**
In scripts (at least some of the languages), the terms dictionary and
postings can be access with the special _index variable. This is for
very advanced use cases which want to do their own scoring. The problem
is segment level statistics must be recomputed for every document.
Additionally, this is not friendly to the terms index caching as the
order of looking up terms should be controlled by lucene.

This change removes _index from scripts. Anyone using it can and should
instead write a Similarity plugin, which is explicitly designed to allow
doing the calculations needed for a relevance score.

closes #19359

### CODE REVIEW

**Comment by clintongormley** [comment]
You should also remove the docs https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-advanced-scripting.html

Please could you change the title to something more meaningful, such as "Remove script access to term statistics"

**Comment by jpountz** [comment]
The code changes LGTM

**Comment by rjernst** [comment]
@clintongormley I removed those docs and updated the title as you suggested.

**Comment by clintongormley** [comment]
There's also a mention and link which you'll need to remove in this section: https://github.com/elastic/elasticsearch/blob/master/docs/reference/modules/scripting/fields.asciidoc#search-and-aggregation-scripts

Would it be possible to add the appropriate deprecation logging in 2.4.0?

**Comment by rjernst** [comment]
> Would it be possible to add the appropriate deprecation logging in 2.4.0?

I'm not sure how to do that without creating potentially very large logs. We only know this is accessed when a script is being run, and it is called *from* the script. So eg if a script runs on a million docs you would get a million deprecation messages?

**Comment by clintongormley** [comment]
Deprecation logging is off by default.  But yes, I see what you mean.  I wonder if we should be rate-limiting duplicate messages in the deprecation log infra itself.

**Comment by jpountz** [comment]
Another way would be to do something like
```
if (logged == false) {
  // log message
  logged = true;
}
```
in LeafIndexLookup in order to have one message per segment, which would make the volume lower.

**Comment by clintongormley** [comment]
I think we should rethink this PR given https://github.com/elastic/elasticsearch/issues/19359#issuecomment-233300053

**Comment by astefan** [comment]
I have seen scripts being used for retrieving terms' statistics and re-scoring the documents based on them (or sorting the documents based on them) in our public community. It is true it is not often being used, but I've seen it. Removing this possibility assumes the user will need to get a hold of Java and write code for the same thing that was possible in queries in a much simpler and accessible way.

**Comment by dakrone** [comment]
@rjernst is this PR still needed given Clint's earlier comment about rethinking it?

**Comment by rjernst** [comment]
@dakrone I think this PR still makes sense, and I left a comment on #19359 explaining why.

**Comment by rjernst** [comment]
@jpountz I've updated this PR now that index lookup is deprecated in 5.5. Can you take a look again?

**Review by jpountz — APPROVED** [review]

**Pull request merged**
