### PR TITLE
[ML] Unmute ClssificationIT.testDependentVariableCardinalityTooHighBu…

### LINKED ISSUE #56240: ClassificationIT can fail with assertion error
The failure doesn't reproduce for me. Command:
```
./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.ClassificationIT.testDependentVariableCardinalityTooHighButWithQueryMakesItWithinRange" \
  -Dtests.seed=8AC525342B38C5D2 \
  -Dtests.security.manager=true \
  -Dbuild.snapshot=false \
  -Dtests.jvm.argline="-Dbuild.snapshot=false" \
  -Dtests.locale=ja-JP \
  -Dtests.timezone=Kwajalein \
  -Dcompiler.java=14 \
  -Druntime.java=11
```

Build scan: https://gradle-enterprise.elastic.co/s/34pg7bs4j4fve

Relevant excerpt from the logs:
```
java.lang.AssertionError: progress is complete: [{"phase":"reindexing","progress_percent":100}, {"phase":"loading_data","progress_percent":100}, {"phase":"feature_selection","progress_percent":100}, {"phase":"coarse_parameter_search","progress_percent":100}, {"phase":"fine_tuning_parameters","progress_percent":100}, {"phase":"final_training","progress_percent":0}, {"phase":"writing_results","progress_percent":100}]
    Expected: is <true>
         but: was <false>
        at __randomizedtesting.SeedInfo.seed([8AC525342B38C5D2:18A81666D35ECE57]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.elasticsearch.xpack.ml.integration.MlNativeDataFrameAnalyticsIntegTestCase.assertProgressComplete(MlNativeDataFrameAnalyticsIntegTestCase.java:211)
        at org.elasticsearch.xpack.ml.integration.ClassificationIT.testDependentVariableCardinalityTooHighButWithQueryMakesItWithinRange(ClassificationIT.java:396)
```

### PR DESCRIPTION
**Pull request by dimitris-athanasiou**
…tWithQueryMakesItWithinRange

Closes #56240

### CODE REVIEW

**Review by przemekwitek — APPROVED** [review]
LGTM

**Comment by dimitris-athanasiou** [comment]
@elasticmachine update branch

**Comment by dimitris-athanasiou** [comment]
@elasticmachine update branch

**Comment by dimitris-athanasiou** [comment]
@elasticmachine update branch

**Pull request merged**
