### PR TITLE
Always show `composed_of` field for composable index templates

### LINKED ISSUE #104627: Response of GET index_templates is missing requiered field composed_of
### Elasticsearch Version

8.12.0

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

_bundled_

### Problem Description

The field `composed_of` is missing in the newest version of elasticsearch when calling `GET /_index_template/` API
This results in MissingRequiredPropertyException in the new Elasticsearch Java-Client as the field is not annotated with `@Nullable`

Elasticsearch 8.11.4
```
{
    "index_templates": [{
            "name": "mytemplate",
            "index_template": {
                "index_patterns": ["pattern_*"],
                "template": {
                    "settings": {
                        "index": {
                            "number_of_shards": "1",
                            "number_of_replicas": "1",
                            "refresh_interval": "1s"
                        }
                    },
                    "mappings": {
                        "dynamic": false
                    }
                },
                "composed_of": [],
                "priority": 0
            }
        }
    ]
}
```

Elasticsearch 8.12.0
```
{
    "index_templates": [{
            "name": "mytemplate",
            "index_template": {
                "index_patterns": ["pattern_*"],
                "template": {
                    "settings": {
                        "index": {
                            "number_of_shards": "1",
                            "number_of_replicas": "1",
                            "refresh_interval": "1s"
                        }
                    },
                    "mappings": {
                        "dynamic": false
                    }
                },
                "priority": 0
            }
        }
    ]
}
```

### Steps to Reproduce

Request  `GET /_index_template/` API with the 8.11.4 versus 8.12.0 Version

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by dakrone**
Prior to e786cfa7061b427cf6185ad907069838dd679574 we inadvertently always added composable index templates with `composed_of: []` beacuse
https://github.com/elastic/elasticsearch/commit/e786cfa7061b427cf6185ad907069838dd679574#diff-5081302eb39033199deb1977d544d1cd7867212a92b8d77e0aa0ded361272b11L618-L630 created a new `ComposableIndexTemplate` from an existing one, and the `.composedOf()` field returned an empty list of no component templates were provided:

https://github.com/elastic/elasticsearch/blob/89e714ee5dc60db8b4979ab6372ff767e108e9da/server/src/main/java/org/elasticsearch/cluster/metadata/ComposableIndexTemplate.java#L172-L177

This meant that before 8.12.0 we would always show `composed_of: []` for composable index templates. This commit recreates this behavior, and always displays the empty list even if no component templates are used by a composable index template.

Resolves #104627

### CODE REVIEW

**Comment by dakrone** [comment]
@elasticmachine update branch

**Comment by dakrone** [comment]
@elasticmachine update branch

**Comment by marcgise** [comment]
It would be nice to have this fix on 8.12.2 version... please. Thanks

**Review by jbaiera — APPROVED** [review]
LGTM!

**Comment by marcgise** [comment]
Will it be solved before 8.14.0?

**Pull request merged**
