### PR TITLE
Forbid Collections.shuffle(List) in favor of Collections.shuffle(List,Random)

### PR DESCRIPTION
**Pull request by tlrx**
One can easily be fooled.

### CODE REVIEW

**Comment by nik9000** [comment]
I thought we already did this? Maybe it is in another file?

**Comment by nik9000** [comment]
Yeah, jdk-signatures.txt. Is the issue that not everyone uses jdk-signatures.txt?

**Comment by jasontedor** [comment]
This was done in #15299, why is it not applying everywhere?

**Comment by tlrx** [comment]
> This was done in #15299, why is it not applying everywhere?

Yes, I just saw it after @nik9000 comments. The thing is I made this mistake in a test in core but nothing warned me... until I ran `gradle clean` for the second time. Sorry for the noise, and thanks.

**Comment by nik9000** [comment]
> until I ran gradle clean for the second time

This could be an issue. We have to be careful in gradle to implement the UP-TO-DATE check properly. If it is wrong then maybe you'd have to clear for the test to run?

**Pull request closed without merging**
