### PR TITLE
Build: Switch jna dependency to an elastic version

### LINKED ISSUE #23640: JNA 4.4.0 requires glibc 2.14
Nothing is ever simple. In #23636, JNA was upgraded from version 4.2.2 to version 4.4.0. Unfortunately, JNA 4.4.0 is linked against glibc 2.14 which is not available on all platforms that we support (e.g., CentOS 6). JNA is not required for Elasticsearch to function, but it not being available means:
 - we can not check if Elasticsearch is running as root
 - we can not install seccomp
 - we can not memory lock
 - we can not perform all the bootstrap checks

The last point is technically not true; the first three are damning anyway. On stable platforms like CentOS 6, glibc 2.14 will never safely be available, and these OS will be around for awhile (we might not support them for their entire life, but we are not retiring them anytime soon). We do not want to be tied to JNA 4.2.2 forever, so this issue is a placeholder for finding a solution to this problem. One idea would be to ship both and set the classpath based on the version of glibc that is available.

### PR DESCRIPTION
**Pull request by rjernst**
This new version of jna is rebuilt from the official release of jna, but
with native libs linked against older glibc in order to support all
platforms elasticsearch supports.

closes #23640

### CODE REVIEW

**Review by jasontedor — APPROVED** [review]
LGTM. Can you mark this as closing #23640?

**Comment by jasontedor** [comment]
Oh, it needs a 5.5.0 label too, we've branched.

**Comment by jasontedor** [comment]
Isn't there a SHA that needs updating too?

**Comment by rjernst** [comment]
> Isn't there a SHA that needs updating too?

Indeed. I only ran packaging tests so far. I will run precommit right now.

**Comment by jasontedor** [comment]
Cool. Push when you're comfortable with it.

**Pull request merged**
