### PR TITLE
[Test] fix concurrency bug in AsyncTwoPhaseIndexerTests

### LINKED ISSUE #42084: AsyncTwoPhaseIndexerTests failure
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/3534/testReport/junit/org.elasticsearch.xpack.core.indexing/AsyncTwoPhaseIndexerTests/testStateMachine/

```
Caused by: java.lang.AssertionError: 
Expected: <3>
     but: was <5>
	at __randomizedtesting.SeedInfo.seed([5119E6D95F3BD4B0]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.xpack.core.indexing.AsyncTwoPhaseIndexerTests$MockIndexer.doSaveState(AsyncTwoPhaseIndexerTests.java:113)
```

Does not reproduce
```
/gradlew :x-pack:plugin:core:test --tests "org.elasticsearch.xpack.core.indexing.AsyncTwoPhaseIndexerTests.testStateMachine" -Dtests.seed=5119E6D95F3BD4B0 -Dtests.security.manager=true -Dtests.locale=xog -Dtests.timezone=CTT -Dcompiler.java=12 -Druntime.java=11
```

### PR DESCRIPTION
**Pull request by hendrikmuhs**
move latch await to doNextSearch, fixes a race condition when the executor thread is faster than the coordinator thread

fixes #42084

### CODE REVIEW

**Review by jimczi — APPROVED** [review]
LGTM

**Comment by hendrikmuhs** [comment]
run elasticsearch-ci/2
run elasticsearch-ci/bwc
run elasticsearch-ci/default-distro

**Comment by hendrikmuhs** [comment]
run elasticsearch-ci/2
run elasticsearch-ci/bwc

**Comment by hendrikmuhs** [comment]
run elasticsearch-ci/2

**Pull request merged**
