### PR TITLE
Avoid duplicate _type fields in v7 compat layer

### PR DESCRIPTION
**Pull request by ywelsch**
Relates https://github.com/elastic/elasticsearch/pull/83195#issuecomment-1023476252

### CODE REVIEW

**Review by romseygeek — APPROVED** [review]
LGTM, thanks @ywelsch

**Review by jtibshirani — APPROVED** [review]
Looks good to me too.

**Comment by ywelsch** [comment]
@elasticmachine update branch

**Comment by ywelsch** [comment]
Thanks @romseygeek and @jtibshirani!

**Pull request merged**
