### PR TITLE
[ESQL] Remove Comparison Mapper

### PR DESCRIPTION
**Pull request by not-napoleon**
More follow-up work from https://github.com/elastic/elasticsearch/pull/105217.  Since the binary comparison operators now implement `EvaluatorMapper`, there is no need for `ComparisonMapper` going forward.

### CODE REVIEW

**Review by alex-spies — APPROVED** [review]
LGTM, but probably it's best to wait for a review from @nik9000 for good measure.

**Review by nik9000 — APPROVED** [review]
LGTM

**Comment by not-napoleon** [comment]
@elasticmachine update branch

**Comment by not-napoleon** [comment]
@elasticmachine update branch

**Pull request merged**
