### PR TITLE
Add common libraries to core/infra codeowners

### PR DESCRIPTION
**Pull request by thecoop**
`org.elasticsearch.common` is a core/infra thing

### CODE REVIEW

**Review by prdoyle — APPROVED** [review]
Makes sense. If there's stuff in there we don't own, then we probably ought to move it out.

**Comment by rjernst** [comment]
IMO o.e.common is too broad right now to give ownership to core/infra. It contains utilities for specific areas of the codebase (eg blobstore). Adding the base package to codeowners will create more noise for core/infra. I think we should decide which utilities should be owned by core/infra, and either move those to a new home, or move out everything else.

**Review by ldematte — APPROVED** [review]
👍

**Review by prdoyle — APPROVED** [review]
Seems reasonable

**Comment by thecoop** [comment]
Merging despite failures, as this is a non-code change

**Pull request merged**
