### PR TITLE
Add docs on HTTP client config

### PR DESCRIPTION
**Pull request by DaveCTurner**
Some notes and recommendations on timeouts and TCP keepalives.

Relates INC-1049

### CODE REVIEW

**Review by henningandersen — APPROVED** [review]
LGTM.

**Comment by pquentin** [comment]
This is definitely not what the Python Elasticsearch client does by default. The connections are persistent, but the default read timeout is 10 seconds! (Although for the default synchronous client the timeout resets every time it receives bytes over the wire, so it can receive large chunked transfers over tens of seconds in practice. For the async client, the entire response needs to be received within 10 seconds.)

I don't think disabling timeouts is something we would want to do though. There are bad reasons for long requests to take minutes or never timeout, and it seems better in that case to notice and bump the timeout as appropriate, and favor using async APIs not requiring keeping a connection opened for minutes.

What do you think?

**Comment by DaveCTurner** [comment]
> I don't think disabling timeouts is something we would want to do though. There are bad reasons for long requests to take minutes or never timeout, and it seems better in that case to notice and bump the timeout as appropriate

That's exactly what we're recommending against. A default 10s timeout is pretty awful UX, and a very big difference between ES client libs and other db libs which typically have no such timeout.

The only situation I've seen in which a client-side timeout has seemed appropriate is where the client has some specific time limit after which a response becomes useless, but typically that's a second or less. In all other cases it's better to wait than to time out, especially if the reaction to a timeout is just to blindly retry. I can't think of any other cases that aren't either (a) really serious ES bugs (likely memory leaks) for which we shouldn't be adding client-side workarounds (b) better-served by TCP-level timeouts such as keepalives. Can you be more precise about the sorts of problems you're talking about?

**Comment by JoshMock** [comment]
> Can you be more precise about the sorts of problems you're talking about?

I can't speak for all clients, but for the JS client, the default behavior is to retry after 30 seconds when:

- a `ConnectionError` occurs; causes:
  - any connection error thrown by Node.js
  - premature connection close
  - malformed certificate
  - certificate fingerprint mismatch
- a request timeout occurs and the `retryOnTimeout` option is set to true (defaults to false)

For all other cases, the error is passed up the stack and the request is not retried.

It's important to note that our clients are built with the assumption that requests may be sent through a reverse proxy, load balancer, etc. So, there may be cases where the client might drift from these recommendations, but they would still apply to a service outside our control that sits in between our clients and ES.

**Comment by DaveCTurner** [comment]
> the default behavior is to retry when [...] a request timeout occurs (default: 30 seconds)

Sure, but we shouldn't.

**Comment by JoshMock** [comment]
As noted, it doesn't retry on timeout by default. Only if the `retryOnTimeout` config is explicitly set to true by the user.

**Comment by DaveCTurner** [comment]
I see, but in that case why time out by default after 30s?

**Comment by JoshMock** [comment]
That's just the default value when `retryOnTimeout` is true.

**Comment by DaveCTurner** [comment]
Ok, and for the avoidance of doubt are you saying that there's no timeout when `retryOnTimeout` is not set to true (which is the default)?

**Comment by DaveCTurner** [comment]
> That first point is what I assume you're concerned about. You're suggesting that no request to ES should timeout by default?

Right, exactly.

**Comment by JoshMock** [comment]
Noted. I'm adding a topic to an upcoming devtools team meeting to discuss this.

**Pull request merged**
