### PR TITLE
Upgrade to Lucene-7.7.2 on 6.8

### PR DESCRIPTION
**Pull request by dnhatn**
This change upgrades Lucene on 6.8 to 7.7.2 to include [LUCENE-8809](https://issues.apache.org/jira/browse/LUCENE-8809) so we can enable the accounting check.

Relates #30290

### CODE REVIEW

**Comment by dnhatn** [comment]
run elasticsearch-ci/1

**Review by jimczi — APPROVED** [review]
LGTM

**Comment by dnhatn** [comment]
Thanks @jimczi.

**Comment by ywelsch** [comment]
As this was reverted, should version labels be removed?

**Comment by dnhatn** [comment]
@ywelsch Thanks for the ping. I've removed the version label.

**Pull request merged**
