### PR TITLE
Created a parameter parser to standardise script options

### PR DESCRIPTION
**Pull request by colings86**

### CODE REVIEW

**Comment by javanna** [comment]
@colings86 this change was backported to 1.x in a bw comp manner but breaks backwards compatibility on master I think, as only the new parameters get read on master now, is that right?

If so this PR might deserve the breaking label (although confusing cause it's breaking only on master branch).

**Comment by colings86** [comment]
This is only a breaking change in 2.0

**Comment by kurtzhong** [comment]
Is there any get around, for 1.4.4? 

When i use the script fields "(`init_script`, `map_script`, `combine_script`, `reduce_script`)" it throws me the following error: 

```
 ScriptException[dynamic scripting for [groovy] disabled]; ]
```

And when i use the `*_script_file` fields, it throws me: 

```
Unable to find on disk script 
```

So now i can't use the scripted metric aggregation on 1.4.4

**Comment by colings86** [comment]
@kurtzhong I just tried the following gist on Elasticsearch 1.4.4 with the default config (apart form enabling CORS and setting the cluster name) and it worked. Could you try this on your cluster and let me know if it works? 

The location of the scripts is very important, they must be in a folder called `scripts` in your config folder (where your elasticsearch.yml file is) and they must have the correct extension for the language you are using (i.e. `.groovy` if you are using the default language, groovy).

**Comment by jveldboom** [comment]
We had to explicitly set the `lang` to groovy for it to work.
```
{
	"script_score": {
		"params": {
			"mult": 1.2
		},
		"script": "sales-ytd",
		"lang":"groovy"
	}
}
```

**Pull request merged**
