### PR TITLE
Move AbstractBWCSerializationTestCase To General Test Framework

### PR DESCRIPTION
**Pull request by Mikep86**
Move `AbstractBWCSerializationTestCase` to the general test framework so that it can be used in `server` code. Cherry-pick of https://github.com/elastic/elasticsearch/pull/113418/commits/0928e92adb050d810e1c4050ebcb98c3bce13d27 & https://github.com/elastic/elasticsearch/pull/113418/commits/a807c1a4f91be763b9a34e3d7b2e9483a709015a from #113418.

### CODE REVIEW

**Review by carlosdelest — APPROVED** [review]
LGTM - Thanks for making this change separate from the main PR

**Comment by Mikep86** [comment]
@elasticmachine update branch

**Review by benwtrent — APPROVED** [review]
I am good with this. The only reason I put them in the xpack core stuff for ML was because I was on that team 4 years ago :). If I did it today, they would be in server.

**Review by kderusso — APPROVED** [review]
LGTM, thanks for breaking this out!

**Comment by Mikep86** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.x|[](https://github.com/elastic/elasticsearch/pull/113977)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
