### PR TITLE
Add documentation for _index property in mvt response

### PR DESCRIPTION
**Pull request by iverase**
Document that we are including a _index property for each hit in _mvt response.

relates #77995

### CODE REVIEW

**Review by jrodewig — APPROVED** [review]
LGTM

**Comment by iverase** [comment]
@elasticmachine please test this

**Comment by iverase** [comment]
@elasticmachine run elasticsearch-ci/docs-check
@elasticmachine run lasticsearch-ci/precommit

**Comment by iverase** [comment]
@elasticmachine run elasticsearch-ci/precommit

**Pull request merged**
