### PR TITLE
Log document id when MapperParsingException occurs

### LINKED ISSUE #37658: Log document id when MapperParsingException occurs
**Elasticsearch version**: ~~5.6~~ 6.x

Indexing a document using the java api may result in a `MapperParsingException`. When bulk-indexing, the problematic field-name is logged by elasticsearch (log-level has to be set to `debug`), but not the document-id. Indexing millions of documents it's hard to track down which specific document has the trouble. So, it would be nice to also have the document's `id` to get straight to the source.

### PR DESCRIPTION
**Pull request by dr0i**
Resolves #37658.

### CODE REVIEW

**Comment by mayya-sharipova** [comment]
@elasticmachine test this please

**Comment by mayya-sharipova** [comment]
@elasticmachine test this please

**Comment by mayya-sharipova** [comment]
@elasticmachine test this please

**Comment by dr0i** [comment]
Uh - `./gradlew check` works now - mo more TransportExceptions. Hopefully these are also gone when the automatic tests by `elasticmachine`  are executed.
(What I changed: 1. rebased to newest master ; 2. used an other machine). Maybe the cause was e.g. #37893 et al, where tests randomly fail and are mow muted in the tip of the newest master.

**Review by mayya-sharipova — APPROVED** [review]

**Comment by mayya-sharipova** [comment]
@elasticmachine test this please

**Comment by mayya-sharipova** [comment]
@dr0i Thank you for your PR, it is approved! I will try to monitor the CI build, and once all the tests are passed, I will merge your PR to the upstream master.

**Comment by dr0i** [comment]
@mayya-sharipova great, thx !

**Pull request merged**
