### PR TITLE
Remove link between Version and IndexVersion

### PR DESCRIPTION
**Pull request by thecoop**
This removes the code link between Version and IndexVersion, so they are now independent classes

This re-applies #97513, reverted by #98501

### CODE REVIEW

**Review by williamrandolph — APPROVED** [review]
LGTM, especially considering it was previously approved and only reverted to try to keep the build clean.

**Comment by thecoop** [comment]
@elasticmachine update branch

**Comment by thecoop** [comment]
@elasticmachine update branch

**Comment by thecoop** [comment]
@elasticsearchmachine rerun elasticsearch-ci/bwc

**Review by rjernst — APPROVED** [review]
LGTM

**Pull request merged**
