### PR TITLE
SQL: Remove slightly used meta commands

### LINKED ISSUE #37409: SQL: Remove SYS TABLE TYPES command
Command `SYS TABLE TYPES` was introduced to support both ODBC and JDBC in discovering the types of tables ES SQL supports.
In practice however only JDBC uses this command directly while ODBC relies on `SYS TABLES` - as such, it makes sense to consolidate them especially since `SYS TABLES` allows for many other params.

In the same vein, `SYS CATALOGS` might be removed since it's not that used and can be replaced with `SELECT DATABASE()` until full catalog behavior is in place.

### PR DESCRIPTION
**Pull request by costin**
Remove SYS CATALOGS and SYS TABLE TYPES as they are a subset of SYS
TABLES (and thus somewhat redundant) and used only by JDBC.

Close #37409

### CODE REVIEW

**Comment by costin** [comment]
run the gradle build tests 1

**Comment by costin** [comment]
run the gradle build tests 2

**Review by astefan — APPROVED** [review]
LGTM.

**Review by matriv — APPROVED** [review]
LGTM

**Review by bpintea — COMMENTED** [review]
LGTM

**Pull request merged**
