### PR TITLE
Update repository-s3.asciidoc

### PR DESCRIPTION
**Pull request by mjwoytowitz**
This documentation used to be in ES 5 docs and was removed from ES 6 docs, because of var name change.

I think it's related to this pull request.

https://github.com/elastic/elasticsearch/pull/24445/files

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by mjwoytowitz** [comment]
Why wasn't this merged?  ES can use S3 implementation other that AWS.  Without this piece of documentation you need a Java programmer to dig through source code to figure it out.

**Comment by tlrx** [comment]
This pull request has been automatically closed because the `6.x` branch was deleted earlier today.

> Why wasn't this merged? ES can use S3 implementation other that AWS. Without this piece of documentation you need a Java programmer to dig through source code to figure it out.

Sorry for the lack of feedback on this. I can understand why one would like to add this piece of documentation but on the other hand it could give a false impression that any S3 compatible service can be used (and is supported) by Elasticsearch and this is not the case. Ceph, for example, is not supported and I've spent numerous hours helping users on Discuss forums that were trying to use it with the epository-s3` plugin. 

Anyway, we can surely improve the doc here and as far as I remember @DaveCTurner (or @zuketo?) proposed to comment/reword this part of the documentation.

**Comment by DaveCTurner** [comment]
Yes, this is on my list for a follow up. It's been a busy few days but I will get to it.

**Comment by DaveCTurner** [comment]
Thanks @mjwoytowitz for raising this. I incorporated this point into a larger change in #38524, see particularly the text following https://github.com/elastic/elasticsearch/pull/38524/files#diff-b72fe98bd1f92abb87c0c78315499e68R101. The addition you proposed was in the section on repository settings, but `endpoint` is a client setting, so we'd prefer the docs to live there.

**Comment by DaveCTurner** [comment]
BTW I can't request a review of #38524 directly from you (@mjwoytowitz) as that functionality seems restricted only to members of the Elastic organisation, but your comments are welcome over there.

**Pull request closed without merging**
