### PR TITLE
convert more admin requests to writeable

### PR DESCRIPTION
**Pull request by talevy**
Another go at converting more Request objects to leverage Writeable.Readers

### CODE REVIEW

**Review by nik9000 — APPROVED** [review]

**Comment by talevy** [comment]
Hey @nik9000, thanks for the review! I've realized I have to modify this PR a little more after you approved it. Specifically, I modified the StreamableTestCase abstract class to include a `createWriteableInstance` method that is used by x-pack test cases. This enabled support for Streamable/Writeable.Reader patterns.

**Comment by nik9000** [comment]
> I modified the StreamableTestCase abstract class to include a

We have an `AbstractWireSerializingTestCase` for `Writeable`. Can you switch to using that instead?

**Comment by talevy** [comment]
uhhhh, I feel stupid. I had no idea that exists.... yeah... much better. thanks! I'll update

**Comment by talevy** [comment]
thanks, I reverted that latest commit that modified the AbstractStreamableTestCase... and I will update the x-pack to use the new class instead

**Review by nik9000 — APPROVED** [review]

**Pull request merged**
