### PR TITLE
ESQL: Push down filters even in case of renames in Evals

### PR DESCRIPTION
**Pull request by alex-spies**
When pushing down filters via `PushDownAndCombineFilters`, we take into account renames from `RENAME`, but not renames in `EVAL`. Let's fix that.

E.g.
```
... | RENAME a AS b | WHERE b > 2

becomes ->

... | WHERE a > 2 | RENAME a AS b
```

But currently we just give up in case of
```
... | EVAL b = a, c = b | WHERE c > 2
```
while this PR enables similarly transforming this into
```
... | WHERE a > 2 | EVAL b = a, c = b
```

This is required to simplify some pushdowns to Lucene that https://github.com/elastic/elasticsearch/pull/112938 aims to tackle.

### CODE REVIEW

**Comment by alex-spies** [comment]
@craigtaverner the current version of this PR propagates (even multiple) renames even in cases where pushing the filter past the eval is not possible. I think this should cut down on the special casing needed for https://github.com/elastic/elasticsearch/pull/112938 some more.

**Comment by alex-spies** [comment]
I just noticed that resolving renames in a predicate that cannot be pushed down can be wrong if the rename points to an attribute that's shadowed, like here:
```
EVAL b_renamed = b, b = something_else | WHERE pow(b_renamed, 2) > 4
```
Rewriting the condition to `pow(b, 2) > 4` is wrong as the attribute `b` (renamed to `b_renamed`) is not in the EVAL's output set, as it was shadowed by `b = something_else`.

**Comment by alex-spies** [comment]
Reverted propagating renames into non-pushed filter conditions as this was not always correct.

**Review by astefan — APPROVED** [review]
LGTM

**Pull request merged**
