### PR TITLE
Suppress Wildfly test in FIPS JVMs

### PR DESCRIPTION
**Pull request by DaveCTurner**
Until #32534 is fixed, this suppresses this failing test on FIPS JVMs, but
allows the suite to pass and includes a dummy @AwaitsFix test too.

### CODE REVIEW

**Comment by jkakavas** [comment]
I'm thinking we could extend the check in 
https://github.com/elastic/elasticsearch/blob/937dcfd716de906e007152aa2e0d9dee2b779672/qa/wildfly/build.gradle#L181 

to 

```
if (!Os.isFamily(Os.FAMILY_WINDOWS) && !inFipsJvm) {
```

so that we skip the integTest in FIPS JVMs

**Comment by DaveCTurner** [comment]
@jkakavas I've done as you suggested (and in the other place that checks for Windows in that file) and it passes `./gradlew precommit` at least. I do not know how to test that this fixes the issue - I don't have a FIPS JVM installed locally. Could you take a look?

**Review by jkakavas — APPROVED** [review]
LGTM, thanks David

**Comment by jkakavas** [comment]
> Could you take a look?
Will do !

>  I do not know how to test that this fixes the issue - I don't have a FIPS JVM installed locally

I have added [instructions](https://github.com/elastic/elasticsearch-team/blob/master/onboarding-and-how-we-work/test-triage.md#test-triage-for-java-8-fips-jvm-failures) on how to troubleshoot test failures in a fips JVM if it ever becomes necessary in the future.

**Comment by jkakavas** [comment]
I can verify this mutes `integTestRunner`. But this is a little trickier. 
`integTestRunner` task doesn't fail for me locally. 
On CI, it fails on 
```
try (CloseableHttpClient client = HttpClientBuilder.create().build()) {
```

We don't pass an sslcontext and the defult behavior for HttpClientBuilder is to use the JVMs default keystore and truststore. We however change the JVM keystore to be a BCFKS one for java8fips and we run in the FIPS JVM ( or does Wildfly run in the Gradle's JVM ? ) so it should be able to read it just fine and not fail with 
``` 
 2> java.io.IOException: Invalid keystore format
```

**Comment by DaveCTurner** [comment]
I think it's right to merge this to mute the failing tests, and have done so, but I will leave #32534 open to track any work towards bringing these tests back into the fold again.

**Pull request merged**
