### PR TITLE
Ensure logging is initialized in CLI tools

### PR DESCRIPTION
**Pull request by jasontedor**
Today when CLI tools are executed, logging statements can intentionally
or unintentionally be executed when logging is not configured. This
leads to log messages that the status logger is not configured. This
commit reworks logging configuration for CLI tools so that logging is
always configured.

### CODE REVIEW

**Review by abeyad — APPROVED** [review]
LGTM

**Comment by jaymode** [comment]
LGTM as well. Thanks @jasontedor for tracking this down

**Comment by jasontedor** [comment]
Thanks for looking @abeyad and @jaymode. Overnight I decided to remove the ability to configure individual loggers for CLI tools, it's the root logger or nothing. I pushed 72d2e06ab1589f1c572a4110111897908916dfd3; can you please take a look? (Note that that feature was never there before, I just added it in the first version of this PR.)

**Comment by jaymode** [comment]
Still LGTM

**Pull request merged**
