### PR TITLE
Fix build cache misses caused by embedded reaper jar

### PR DESCRIPTION
**Pull request by mark-vieira**
This is a follow up to #45347 which didn't actually fix the problem.

Essentially the input normalization technique doesn't work here. Simply including the `reaper.jar` in the `buildSrc.jar` will cause the Gradle build classpath to constantly change. The workaround here is to only embed the JAR when building the `build-tools.jar`. When running inside the Elasticsearch build we instead just find the JAR on the classpath rather then copying it from inside the buildSrc jar itself. To ensure this works for external build-tools users we've introduced some test coverage here for that scenario.

### CODE REVIEW

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by mark-vieira** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by mark-vieira** [comment]
@elasticmachine update branch

**Comment by mark-vieira** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by pcsanwald** [comment]
added `v8.0.0` because I noticed this didn't have version label, if this wasn't the right thing to do, please LMK.

**Comment by mark-vieira** [comment]
Thanks, @pcsanwald! I forgot to put the version labels on this one. This was backported to `7.x` as well so I've added the correct label there too.

**Pull request merged**
