### PR TITLE
Simplify node stopping call

### PR DESCRIPTION
**Pull request by idegtiarenko**
There is no need to use randomNode/predicate combination to stop a node by its
name.

### CODE REVIEW

**Review by DaveCTurner — COMMENTED** [review]
Nicely spotted.

However this loses the check that we're not stopping the last remaining master-eligible node. Could we keep that?

I wonder if we can get rid of `stopRandomNode` entirely, replacing it with a function that selects a random node's name according to the given settings predicate?

**Comment by idegtiarenko** [comment]
>However this loses the check that we're not stopping the last remaining master-eligible node. Could we keep that?

Added the check to existing `stopNode(String nodeName)`.

>I wonder if we can get rid of stopRandomNode entirely, replacing it with a function that selects a random node's name according to the given settings predicate?

Would you mind if I do it in a separate pr to make this change smaller?

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Comment by idegtiarenko** [comment]
@elasticmachine please run elasticsearch-ci/part-1

**Pull request merged**
