### PR TITLE
[Ingest] allow docs to write native `double[]` and `double[][]`

### PR DESCRIPTION
**Pull request by benwtrent**
Related to the work for text-embeddings, ingest documents should allow writing native `double[]` and `double[][]` values in docs. 

This commit enables this by handling these native arrays in `IngestDocument#deepCopy`.

It seems silly to box `double[]` arrays into `List<Double>` especially when they could be as long as `2048`

### CODE REVIEW

**Review by danhermann — COMMENTED** [review]
Could you add some tests to `IngestDocumentTests` for this functionality? Now that this method is public and being used more widely, it makes sense to test it directly.

**Comment by benwtrent** [comment]
@danhermann I simply tested the new `double[]` and `double[][]` support. More tests for that method for all the officially supported types will probably be necessary eventually :).

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Review by danhermann — APPROVED** [review]
Thanks for including the tests. LGTM pending successful CI.

**Pull request merged**
