### PR TITLE
Make sure stored JSON fields are properly decoded.

### PR DESCRIPTION
**Pull request by jtibshirani**

### CODE REVIEW

**Review by colings86 — COMMENTED** [review]
I wonder if we should also have a test that actually indexes the value and checks the value returned from e.g. stored fields is correct? maybe this would fit into one of the existing integration or YAML tests we already have?

**Comment by jtibshirani** [comment]
Thanks for taking a look. Because our existing integration and REST tests are focused on specific query types, there wasn't a great place to add a check for stored fields. I ended up adding an integration test in `SearchFieldsIT` around stored JSON fields.

I have some questions around how we think of unit vs. integration vs. REST tests that I'll follow-up with you about offline.

**Comment by jtibshirani** [comment]
@elasticmachine test this please

**Review by colings86 — APPROVED** [review]
LGTM thanks for adding the extra test

**Pull request merged**
