### PR TITLE
Add dense vector inference mock service for testing

### PR DESCRIPTION
**Pull request by carlosdelest**
Adds a new mock test service for text embedding tasks.

Refactored common methods in the previous test inference service and created an abstract class. Some test methods have been changed to reflect that we now have both sparse and dense vector services.

This is previous work for https://github.com/elastic/elasticsearch/pull/105515

### CODE REVIEW

**Comment by carlosdelest** [comment]
@elasticsearchmachine run elasticsearch-ci/packaging-tests-windows-sample

**Comment by carlosdelest** [comment]
@elasticsearchmachine run elasticsearch-ci/windows-2019

**Review by davidkyle — APPROVED** [review]
LGTM

**Comment by carlosdelest** [comment]
@elasticsearchmachine update branch

**Comment by carlosdelest** [comment]
@elasticmachine update branch

**Pull request merged**
