### PR TITLE
SQL: Simplify certification generation inside SSL test

### LINKED ISSUE #53968: [CI] createNodeKeyStore failed on Jenkins darwin worker due to DNS name
https://gradle-enterprise.elastic.co/s/r3hcjn6yivexe failed with the following error in a darwin build (https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-darwin-compatibility/595):

```
00:08:37 keytool error: java.lang.RuntimeException: java.io.IOException: DNSName components must begin with a letter
00:08:37 
00:08:37 build complete, generating: /private/var/lib/jenkins/workspace/elastic+elasticsearch+master+multijob-darwin-compatibility/build/595.tar.bz2
00:09:40 
00:09:40 FAILURE: Build failed with an exception.
00:09:40 
00:09:40 * What went wrong:
00:09:40 Execution failed for task ':x-pack:plugin:sql:qa:security:with-ssl:createNodeKeyStore'.
00:09:40 > Process '/var/lib/jenkins/.java/openjdk11/bin/keytool [-genkey, -alias, test-node, -keystore, /private/var/lib/jenkins/workspace/elastic+elasticsearch+master+multijob-darwin-compatibility/x-pack/plugin/sql/qa/security/with-ssl/build/keystore/test-node.jks, -keyalg, RSA, -keysize, 2048, -validity, 712, -dname, CN=smoke-test-plugins-ssl, -keypass, keypass, -storepass, keypass, -ext, san=ip:fe80::1,dns:20049.local,ip:::1,dns:localhost,ip:127.0.0.1,dns:localhost]' finished with non-zero exit value 1
```

I am guessing the part of that that `keytool` took offence at is `dns:20049.local`.

I can run `./gradlew ':x-pack:plugin:sql:qa:security:with-ssl:createNodeKeyStore'` without problems on my Macbook.  Presumably there is something different about the way the macOS Jenkins workers are configured that means they have a technically invalid DNS name.

### PR DESCRIPTION
**Pull request by costin**
Fix #53968

### CODE REVIEW

**Comment by costin** [comment]
Folks, I've added you for review to double check whether what I'm doing is not completely off. The build failure happens on macs so likely, once the build passes, I'll merge it since the failures cannot be muted.

Thanks.

**Comment by costin** [comment]
@elasticmachine update branch

**Review by nik9000 — APPROVED** [review]
Sure!

**Comment by costin** [comment]
@nik9000 I don't the fix is enough, the failure in #53968 indicates it's the `-ext san` thing but removing gives errors with the http client not trusting the server certificate. Maybe you can take a look at it?
Thanks

**Comment by costin** [comment]
@matriv tagging you just in case.

**Comment by bpintea** [comment]
fwiw, the PR passed on my osx as well

**Comment by nik9000** [comment]
> fwiw, the PR passed on my osx as well

I don't have OSX. I can certainly look into it at some point if you need though.

**Comment by costin** [comment]
@nik9000 yes please. The issue seems to be caused by one of the address inside san which on MacOs fails (probably because it's not an approved one?).
The logs from the last logs in https://github.com/elastic/elasticsearch/issues/53968 show the actual command line executed which hopefully helps narrow things down.
Not sure what the fix would be though and if running with `-ext san` is an option.

Thanks!

**Comment by mark-vieira** [comment]
The root cause is you cannot have a SAN where the DNS name starts with a numeric character.

```
san=ip:fe80::1,dns:20049.local
```

FWIW, when running this locally with the same arguments I couldn't get the error. It seems this is an issue with `keytool` in JDK11 as I don't have the same problem with JDK13. We can do two things here:

1. Modify `SanEvalutator` to filter out any hostname entries that don't begin with an alpha character.
2. Remove the `executable = "${BuildParams.runtimeJavaHome}/bin/keytool"` so that we just use the build JDK for running keytool. I don't have any reason to believe that using the newer keytool will be incompatible with older runtimes.

**Comment by costin** [comment]
Thanks @mark-vieira . Both make sense to me but timing wise 2 seems faster and if that fixes, we can look at 1 in the future if this a JDK 11-only bug (with JDK 15 scheduled for September).

**Comment by mark-vieira** [comment]
I'm good with either. Can you go ahead and make that change in this PR?

**Comment by costin** [comment]
@elasticmachine update branch

**Review by pugnascotia — APPROVED** [review]

**Pull request merged**
