### PR TITLE
[ML] Adding a timeout parameter to the inference API

### LINKED ISSUE #107241: [ML] Add timeout field to inference API
### Description

The inference plugin's REST API that performs inference should have a `timeout` field to conform to other elasticsearch APIs.

The REST api query parameter should be optional and default to some value.

### PR DESCRIPTION
**Pull request by jonathan-buttner**
This PR adds a timeout field to the inference API request that performs inference.

I wasn't sure what to use as the default. In the ML plugin we default to the largest millisecond value for ingest and 10 seconds for other calls. I chose 30 seconds but I'm happy to change it.

Closes: https://github.com/elastic/elasticsearch/issues/107241

```
POST _inference/text_embedding/cohere?timeout=2nanos
{
    "input": "hello",
    "task_settings": {
        "input_type": "ingest"
    }
}
```

### CODE REVIEW

**Review by jimczi — COMMENTED** [review]
Thanks @jonathan-buttner .
It seems that `Sender#send(ExecutableRequestCreator requestCreator, InferenceInputs inferenceInputs, ActionListener<InferenceServiceResults> listener)` is no longer needed since the request timeout is always required?
I also wonder if `HttpRequestSender#MAX_REQUEST_TIMEOUT` should be deprecated/removed?

**Comment by jonathan-buttner** [comment]
> Thanks @jonathan-buttner . It seems that `Sender#send(ExecutableRequestCreator requestCreator, InferenceInputs inferenceInputs, ActionListener<InferenceServiceResults> listener)` is no longer needed since the request timeout is always required? I also wonder if `HttpRequestSender#MAX_REQUEST_TIMEOUT` should be deprecated/removed?

Yeah good point. I'll clean those up.

**Comment by jonathan-buttner** [comment]
> HttpRequestSender#MAX_REQUEST_TIMEOUT should be deprecated/removed?

We never documented it, maybe I'll just remove it 🤔

**Review by jimczi — APPROVED** [review]
LGTM

**Review by szabosteve — APPROVED** [review]
Docs changes LGTM, thanks!

**Pull request merged**
