### PR TITLE
Fix URL documentation in API specs

### PR DESCRIPTION
**Pull request by ezimuel**
This PR fixes the URL documentation in API specs. I checked the documentation URLs in the API specs and I applied the following changes:
- if a URL returns a 301 redirect, I changed the URL with the redirect (mostly `https` instead of `http`);
- I checked for 404 errors (also in redirect) and proposed the best alternative manually, as follows:
    - `info`: https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html;
    - `ping`: https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html;
    - `render_search_template`:  https://www.elastic.co/guide/en/elasticsearch/reference/current/search-template.html#_validating_templates.

### CODE REVIEW

**Comment by Trisped** [comment]
Looks like there was a problem with [rest-api-spec/src/main/resources/rest-api-spec/api/render_search_template.json ](https://github.com/elastic/elasticsearch/pull/44487/commits/1d72b440bd070284bc7a18f83ccbce0532f1749d#diff-05648c4a70a3673fbecd70ee0bad5fa3)
You put in "https://www.elastic.co" when it should have been "https://www.elastic.co/guide/en/elasticsearch/reference/master/search-template.html"

That is the only issue I saw with the changes.
Of course, the elasticsearch-ci/2 not building issue needs to be reviewed and I did not check if you fixed all of the URLs.

**Comment by ezimuel** [comment]
@Trisped I fixed in the second commit here https://github.com/elastic/elasticsearch/pull/44487/commits/179637457cb201c79e02e83ede44013293c1c0d4. I used the specific paragraph for the render template https://www.elastic.co/guide/en/elasticsearch/reference/current/search-template.html#_validating_templates instead of the one that you proposed https://www.elastic.co/guide/en/elasticsearch/reference/current/search-template.html.

**Comment by Trisped** [comment]
@ezimuel I miss read the commits (I thought newest was on top).  Thanks for the feed back.  Everything looks good.

**Comment by karmi** [comment]
Do we know why the patch is failing on CI?

It would be nice to get this in, so I can fold it into https://github.com/elastic/elasticsearch/pull/42346.

**Comment by Trisped** [comment]
@karmi Not sure, the only changes were made to the documentation.
The logs states: 
> 11:30:42 === Standard error of node `node{:x-pack:qa:smoke-test-watcher:integTest-0}` ===
> 11:30:42 
> 11:30:42 > Task :x-pack:qa:smoke-test-watcher:integTestRunner FAILED
> 11:39:44 
> 11:39:44 FAILURE: Build failed with an exception.
> 11:39:44 
> 11:39:44 * What went wrong:
> 11:39:44 Execution failed for task ':x-pack:qa:smoke-test-watcher:integTestRunner'.
> 11:39:44 > There were failing tests. See the report at: file:///var/lib/jenkins/workspace/elastic+elasticsearch+pull-request-2/x-pack/qa/smoke-test-watcher/build/reports/tests/integTestRunner/index.html

There are some other errors higher up in the log, but they are not as clear to me.  Since we now have merge conflicts, I would suggest merging master into this branch and see if that fixes it.  Especially since the first checkin worked and the second only had the one change.

I guess I should also point out that I am not actually a dev on this.  I was the one who reported the issue and @ezimuel was nice enough to make the changes.

**Comment by karmi** [comment]
Jenkins, retest this please.

**Comment by karmi** [comment]
The docs build appears unrelated to the changes (as expected).

**Comment by jdconrad** [comment]
@elasticmachine run elasticsearch-ci/1

**Review by jdconrad — COMMENTED** [review]
LGTM!

**Comment by russcam** [comment]
Are there any plans to backport these changes to 6.x? Doing so would allow clients to update their libraries with the link changes

**Pull request merged**
