### PR TITLE
Generalize search.remote settings to cluster.remote

### PR DESCRIPTION
**Pull request by jasontedor**
With features like CCR building on the CCS infrastructure, the settings prefix `search.remote` makes less sense as the namespace for these remote cluster settings than does a more general namespace like `cluster.remote`. This commit replaces these settings with `cluster.remote` with a fallback to the deprecated settings `search.remote`.

### CODE REVIEW

**Comment by jasontedor** [comment]
This PR is based on #33412; it was discovered in this work that list settings are not properly deprecated.

**Review by martijnvg — APPROVED** [review]
LGTM, I do think we need a note about this in the migration docs?

**Comment by jasontedor** [comment]
@martijnvg Yup! I will do that in a separate PR targeting 6.5.0 only (for deprecation) and 7.0.0 (for removal).

**Comment by s1monw** [comment]
I have some questions before I go into reviews:

 * how do we upgrade existing settings, is there a plan?
 * if we don't upgrade existing settings how do we make sure we can remove the BWC code at any point?
 * would it make sense to just us a more flexible `AffixKey` and discuss depreciation and upgrades in a separate issue?

**Comment by jasontedor** [comment]
> how do we upgrade existing settings, is there a plan?

Yes, my plan is to address this in a follow-up indeed.

> if we don't upgrade existing settings how do we make sure we can remove the BWC code at any point?

This question is moot since I plan to automatically upgrade the settings.

> would it make sense to just us a more flexible `AffixKey` and discuss depreciation and upgrades in a separate issue?

I would rather not as there are only a handful of settings here, it's straightforward enough to manage them individually. Are you okay with this?

**Comment by s1monw** [comment]
> I would rather not as there are only a handful of settings here, it's straightforward enough to manage them individually. Are you okay with this?

++ LGTM

**Review by s1monw — APPROVED** [review]

**Comment by javanna** [comment]
@jasontedor when I add the deprecated settings to the config file against master, I get the deprecation warning but the setting seems to be ignored, it does not do anything. You can repro this by adding some unreachable cluster, if you use the new settings the node won't start, with the older setting the node starts. If the remote cluster is reachable, using the deprecated settings I can never connect to it through ccs, _remote/info always returns empty.

**Comment by jasontedor** [comment]
@javanna Thank you! I opened #34090.

**Pull request merged**
