### PR TITLE
Fix trailing semicolon

### LINKED ISSUE #116156: ESQL: Docs: REPEAT Function Example
### Elasticsearch Version

8.15.3

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

ESS

### Problem Description

The example code for the repeat function has an error in the documentation (https://www.elastic.co/guide/en/elasticsearch/reference/current/esql-functions-operators.html#esql-repeat)

`ROW a = "Hello!"
| EVAL triple_a = REPEAT(a, 3);`

The sample code block should not have a trailing semicolon.  

### Steps to Reproduce

Copy sample code block from documentation page and insert in Discover - ES|QL search page.  Returns the following error 

`[esql] > Couldn't parse Elasticsearch ES|QL query. Check your query and try again. Error: line 2:31: token recognition error at: ';'`

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by jackpan123**
Remove trailing semicolon in REPEAT function example (Closes #116156 )

### CODE REVIEW

**Comment by bpintea** [comment]
@elasticmachine ok to test

**Comment by leemthompo** [comment]
run docs-build

**Review by bpintea — APPROVED** [review]

**Comment by bpintea** [comment]
@elasticmachine update branch

**Comment by leemthompo** [comment]
@elasticmachine test this

**Comment by leemthompo** [comment]
@elasticmachine run docs-build

**Pull request merged**
