### PR TITLE
Reset queryGeometry in ShapeQueryTests

### LINKED ISSUE #45628: ShapeQueryTests#testFieldAlias returns no hits, fails assertion
Encountered this on a PR build.  Doesn't fail 100% of the time, but seems to fail once every 10-20 iterations.  Fails on this:

```
assertTrue(response.getHits().getTotalHits().value > 0);
```
So I'm assuming the cluster isn't ready yet or something (shards still allocating, refresh not performed, etc).  

Sidebar, we should probably convert this to an ESRestTestCase or a yaml test instead of ESSingleNodeTestCse

```
./gradlew :x-pack:plugin:spatial:test --tests "org.elasticsearch.xpack.spatial.search.ShapeQueryTests.testFieldAlias" -Dtests.seed=DDCE36BAC5FE6F5A -Dtests.security.manager=true -Dtests.locale=es-BR -Dtests.timezone=PRT -Dcompiler.java=12 -Druntime.java=11
```

```
java.lang.AssertionError
	at __randomizedtesting.SeedInfo.seed([DDCE36BAC5FE6F5A:E788A7DFE749FB6E]:0)
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.elasticsearch.xpack.spatial.search.ShapeQueryTests.testFieldAlias(ShapeQueryTests.java:234)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
```

### PR DESCRIPTION
**Pull request by iverase**
`setUp` method is called for every test but the `queryGeometry` is only set up in the first one. Therefore the test `testFieldAlias` might be querying with a shape that does not exist in the index.

This fix reset the `queryGeometry` every time `setUp` is called.

Closes #45628

### CODE REVIEW

**Comment by iverase** [comment]
@elasticmachine test elasticsearch-ci/1 please

**Comment by iverase** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by iverase** [comment]
@elasticmachine update branch

**Review by nknize — APPROVED** [review]
LGTM

**Pull request merged**
