### PR TITLE
TEST: Clone replicas list when compute replication targets

### LINKED ISSUE #33457: [CI] ShardFollowTaskReplicationTests#testFailLeaderReplicaShard failure
Does not reproduce.

```
REPRODUCE WITH: ./gradlew :x-pack:plugin:ccr:test -Dtests.seed=21F92F032FE75068 -Dtests.class=org.elasticsearch.xpack.ccr.action.ShardFollowTaskReplicationTests -Dtests.method="testFailLeaderReplicaShard" -Dtests.security.manager=true -Dtests.locale=fr-BE -Dtests.timezone=Indian/Mahe -Dcompiler.java=10 -Druntime.java=10
05:21:58   2> REPRODUCE WITH: ./gradlew :x-pack:plugin:ccr:test -Dtests.seed=21F92F032FE75068 -Dtests.class=org.elasticsearch.xpack.ccr.action.ShardFollowTaskReplicationTests -Dtests.method="testFailLeaderReplicaShard" -Dtests.security.manager=true -Dtests.locale=fr-BE -Dtests.timezone=Indian/Mahe -Dcompiler.java=10 -Druntime.java=10
05:21:58   1> [2018-09-06T09:21:58,376][INFO ][o.e.x.c.a.ShardFollowTaskReplicationTests] [testFailLeaderReplicaShard] after test
05:21:58 ERROR   11.1s J3 | ShardFollowTaskReplicationTests.testFailLeaderReplicaShard <<< FAILURES!
05:21:58    > Throwable #1: java.lang.AssertionError: 
05:21:58    > Expected: <256>
05:21:58    >      but: was <1>
05:21:58    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
05:21:58    > 	at org.elasticsearch.index.replication.ESIndexLevelReplicationTestCase$ReplicationGroup.assertAllEqual(ESIndexLevelReplicationTestCase.java:398)
```

Build urls:
* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=java10,ES_RUNTIME_JAVA=java10,nodes=virtual&&linux/284/console
* https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-darwin-compatibility/1011/console

### PR DESCRIPTION
**Pull request by dnhatn**
In #34407, we supposed to clone the list of replicas of ReplicationGroup
when computing replication targets, but somehow we missed it. If we
don't clone the list, a WriteReplicationAction may use an old
ReplicationTargets which consists replicas which are removed from the
current list of replicas

Relates #34407
Closes #33457

### CODE REVIEW

**Comment by dnhatn** [comment]
This PR is not ready for review since the current approach is not good enough.

**Comment by dnhatn** [comment]
@martijnvg It's ready :).

**Review by martijnvg — APPROVED** [review]
LGTM 👍

**Comment by dnhatn** [comment]
Thanks @martijnvg.

**Pull request merged**
