### PR TITLE
[TEST] fix two flaky ILM tests

### PR DESCRIPTION
**Pull request by talevy**
* WaitForRolloverReadyStepTests#mutateInstance sometimes did not mutate the instance
  correctly, this commit fixes that
* 40_explain_lifecycle#"Test new phase still has phase_time" is not really a necessary
  integration test. In addition to this, it is flaky due to the asynchronous nature of
  ILM metadata population. Unit tests for this exist in InitializePolicyContextStepTests.

### CODE REVIEW

**Review by AthenaEryma — APPROVED** [review]
Thanks for fixing this, LGTM.

**Comment by talevy** [comment]
I selfishly found out about these issues when digging into CI-failures for unrelated reasons. thanks for the review, Gordon!

**Comment by talevy** [comment]
test gradle build tests 1

**Comment by talevy** [comment]
run gradle build tests 2

**Pull request merged**
