### PR TITLE
Fix numOpenOutputs and modCount in ByteSizeCachingDirectory

### LINKED ISSUE #92434: ByteSizeCachingDirectory can't use cached size because numOpenOutputs is a negative value when close method was invoked more than once
### Elasticsearch Version

7.10.2

### Installed Plugins

repository-hdfs

### Java Version

_bundled_

### OS Version

Linux 4.14.81.bm.26-amd64 #1 SMP Debian 4.14.81.bm.26 Mon Sep 14 09:46:45 UTC 2020

### Problem Description

The size of shard should't  be computed again instead of using cached when no pending write。we migrated a lot of indicess to a new cluster by snapshot, nodes and indices stats api become very slow because some shards that were restored from snapshots always computed shard directory size even no write，not use cached because the numOpenOutputs was decreased to a negative number

### Steps to Reproduce

snapshot a index then restore, the shard that recovery from snapshot will always compute directory size instead of using cached

### Logs (if relevant)

image

### PR DESCRIPTION
**Pull request by loupipalien**
The numOpenOutputs could be decreased to a negative number when a Output close more than once，which will cause estimate size of shard directory never use cache even no pending write 
This PR fix #92434

### CODE REVIEW

**Comment by loupipalien** [comment]
> ❌ Author of the following commits did not sign a [Contributor Agreement](https://www.elastic.co/contributor-agreement): [58530f9](https://github.com/elastic/elasticsearch/commit/58530f9f1598693ee8a664879f85e7ac769b8445)
> 
> Please, read and sign the above mentioned agreement if you want to contribute to this project

CLA has been signed

**Comment by pxsalehi** [comment]
@elasticmachine test this please

**Review by pxsalehi — APPROVED** [review]
LGTM1

**Review by DaveCTurner — APPROVED** [review]
LGTM2, great PR @loupipalien 😄

**Pull request merged**
