### PR TITLE
URL param parsing should not be lenient

### LINKED ISSUE #14719: url params parsing should not be lenient
If you use eg the `_analyze` api, and mispell the `tokenizer`, it will happily go on using the standard *analyzer* (if you have filters specified, it will ignore them as well).

We should remove all leniency from url param parsing, it does not help anyone, but only causes confusion. Rest actions should remove parameters as they are parsed, and fail when there are extras left (eg `Unknown parameter "tokenzier" for _analyze`)

### PR DESCRIPTION
**Pull request by martinstuga**
First commit to allow the team to check if this approach is OK.
Now with the right files.

Closes #14719

### CODE REVIEW

**Comment by rjernst** [comment]
@martinstuga Thanks for the PR! I like the idea here, but I have a couple concerns:
* I don't like that this is only set to work for GET requests. What is the problem with making it work for all request methods?
* I'm not happy with it being inside netty code...
* There are other methods that this does not address: `hasParam(String key)` and `params()`. The first is questionable as to whether it should be considered "consuming" a param by checking if it exists, but searching the codebase shows we do use it like this, for example with `pretty`. The latter method looks like it would not be possible to use, but I also question whether we need that method altogether...some of the usages are odd (we are *setting* params?)

**Comment by martinstuga** [comment]
@rjernst Thanks for your feedback.

*This approach only works with GET requests because it only throws the Exception after the method is invoked on the node. So, for write operations we would need to rollback the write, so for the write operations I'm going to implement it in all single methods (before invoke the node).
*We can move the `consumedParams` field and some methods to the `HttpRequest` class, but I'll still need some code inside `NettyHttpRequest`.
*We can add `hasParams(String key)` as consumer method. About `params()`, I've searched the code, and it's used to set params, but not the get params (that's what we want), so in that case, we could do some easy factoring to hide this method.

My ideia was to go ahead with write operations (doing this check in every single method), but if you don't feel comfortable with this approach, I can do that check also in the GET requests.

**Comment by martinstuga** [comment]
I've added the parameter check to some methods in the commit `a04d3d9`. Please, validate if it's OK.

Thanks.

**Comment by martinstuga** [comment]
Any feedback about this last commit? May I keep going?

**Comment by martinstuga** [comment]
#14719 url params parsing should not be lenient

I've added the parameter check to some methods in the commit a04d3d9. Please, validate if it's OK.

Thanks.

**Comment by rjernst** [comment]
Thanks for the update @martinstuga, sorry for the long delay in looking at this again.

Unfortunately there are still a number of issues I have with this PR. While I think it is important to have this validation, I also think doing it cleanly, in a way that will not be error prone for future rest handlers is important, is extremely important.

Here are some issues I have:
* Each handler must add a call to checkParameters: this is error prone
* It still involves touching netty code, which should not have anything to do with how rest requests are validated.
* The new exception added is not useful. Not only do we not need a new exception (IllegalArgumentException should work great), but the singleton instance of the new exception gives a user zero insight into *which* extra parameters were found.

I think a better approach might be as follows:
* Change the BaseRestHandler abstract method to something like "parseRequest", which returns a runnable. This way the action can be returned and the base class call it, once parameters have been validated (and thus will work for post/put requests).
* Change the RestRequest parameter to separate out the request info, from a separate map/class for the parameters. Each rest handler should remove a parameter as it checks it. Thus any parameters still in the params map after parsing the request are extra parameters for which the base implementation can throw an IAE.

While this is a larger refactoring to the rest handler api, I think it is cleaner for future rest handlers as the api forces rest handler implementations to consume all parameters, regardless of the http method. If you feel this is too complex a task to take on, I completely understand, and in either case, I appreciate the time you've spent working on this issue.

**Comment by martinstuga** [comment]
Hi @rjernst, thanks for your reply.

I'm new to this project and I've adopted this issue because I thought it would be a good entry point. Unfortunately, it's not as straight forward as I thought, and I don't want to be a blocker but the opposite. 
For this reason, I think it would be better to leave this issue, leaving it free for another person.

I'm still eager to collaborate to the project, so I'll be looking for other issues I can help. If you find some, please, feel free to suggest.

Thank you.

**Comment by dakrone** [comment]
Thanks for the explanation @martinstuga, I'm going to close this for now then, but I do hope you find some issues to collaborate on! Check the "adopt-me" label on github or the "low-hanging fruit" label if you need some ideas!

**Pull request closed without merging**
