### PR TITLE
[DOCS] Fix outdated Kibana UI refs and screenshots in security docs

### LINKED ISSUE #59893: Update docs to reflect Kibana 7.8 navigation
**Kibana version:** 7.8

**Describe the bug:**

New Kibana navigation has re-organized modules, and existing documentation on accessing sub-modules are no longer accurate in certain places. For example, https://www.elastic.co/guide/en/elasticsearch/reference/current/get-started-users.html states that User management can be performed in **Management -> Security -> Users**, but this hierarchy no longer exists, and instead (from the Kibana homepage), the navigation becomes **Management -> Stack Management -> Users**:

Screen Shot 2020-07-17 at 3 30 38 PM

Screen Shot 2020-07-17 at 3 32 33 PM

Note that **once the user enters the Management module**, the old navigation structure as documented becomes available again, but that clicking on the left hand side hamburger re-opens the newer navigation and covers it. 

Screen Shot 2020-07-17 at 3 33 32 PM

Aside from existing documentation being potentially misleading (this issue was raised through a Cloud trial user's in-app chat cc: @corkscruff) , the dual-navigation structures experience is also rather confusing - should the breadcrumb be **Management -> Stack Management -> Security -> Users**????  

Tagging @debadair per Kibana docs Slack channel conversation.

### PR DESCRIPTION
**Pull request by jrodewig**
Fixes outdated Kibana screenshots and UI references in the `Create users`
and `Assign roles` pages of the security tutorial docs.

Fixes #59893

### Previews
https://elasticsearch_60023.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/get-started-users.html

https://elasticsearch_60023.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/get-started-roles.html

### CODE REVIEW

**Comment by lcawl** [comment]
Thanks @jrodewig I think the screenshots in the next page (https://www.elastic.co/guide/en/elasticsearch/reference/master/get-started-roles.html) are also out-dated.  If you want to defer those to another PR, let me know and I can grab it.

**Comment by jrodewig** [comment]
Thanks @lcawl. The PR now includes updates for the `Assign roles` page.

**Comment by jrodewig** [comment]
@elasticmachine update branch

**Review by legrego — APPROVED** [review]
LGTM

**Review by lcawl — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
