### PR TITLE
SQL: Add the dataloader gradle task

### PR DESCRIPTION
**Pull request by palesz**
* Ability to execute the DataLoader using the `./gradlew
':x-pack:plugin:sql:qa:server:dataloader'` command

### CODE REVIEW

**Comment by costin** [comment]
Can you explain the reason behind this PR? The DataLoader is called automatically by our tests and I don't see it used that much to warrant a dedicated gradle task

**Comment by palesz** [comment]
Spinning up a node with `./gradlew run ...`, populating with the test data in `DataLoader` and hitting the REST interface manually helps investigations, helps with creating `csv-spec` based integration tests. I usually run the `DataLoader` via the IDE, but would be more convenient (at least for me) to have it available through the command line too.

**Comment by costin** [comment]
How many times are you running the `DataLoader`? If you're using it for manual testing I would refrain from making it a first class citizen in Gradle since it create a maintenance burden. Especially since you mention you are using it for debugging and thus have the IDE opened.

**Comment by palesz** [comment]
I still find this useful, but since everyone else is against it, I will close the PR.

**Pull request closed without merging**
