### PR TITLE
Rename o.e.common in libs/core to o.e.core

### PR DESCRIPTION
**Pull request by rjernst**
When libs/core was created, several classes were moved from server's
o.e.common package, but they were not moved to a new package. Split
packages need to go away long term, so that Elasticsearch can even think
about modularization. This commit moves all the classes under o.e.common
in core to o.e.core.

relates #73784

### CODE REVIEW

**Comment by rjernst** [comment]
Note that the classes here are rarely changed, so the possibility for create backport conflicts should be low. I think we can backport this to 7.x, and if for some reason a change is needed in 7.13 to one of these classes, that can be handled manually if the rename is not picked up in the cherry pick.

**Comment by mark-vieira** [comment]
In a lot of cases I find that git's rename detection and handling for merges/cherry-picks is pretty good so it's probably not too much of a concern.

**Review by mark-vieira — APPROVED** [review]
:+1:

**Comment by dadoonet** [comment]
When upgrading the HLClient to 7.14.0, this is breaking my project as the `BulkProcessor` exposes a `TimeValue` with the `setFlushInterval(TimeValue)` method. 
Note that the BulkProcessor is documented at https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-high-document-bulk.html#java-rest-high-document-bulk-processor

I see several options:

* Do nothing
* Add back a Deprecated `org.elasticsearch.common.unit.TimeValue` class in 7.x branch which extends `org.elasticsearch.core.TimeValue` (and keep it removed in main branch)
* Add a breaking change in the documentation. We don't have such a page in the Rest Client documentation so this can be added to this page https://www.elastic.co/guide/en/elasticsearch/reference/current/migrating-7.14.html?
*

**Comment by rjernst** [comment]
@dadoonet We discussed this in the core/infra sync and decided to do nothing here (your option 1). As you pointed out, the change is trivial. Additionally, there has always been an expectation for HL Client (and transport client and plugins) that because they depend on the server jar, there is always the possibility of needing compile changes on upgrades.

**Comment by hmottestad** [comment]
This broke our code by stopping users from upgrading their own code to use a newer minor version of Elasticsearch than the one we are depending on (7.8.1).

**Pull request merged**
