### PR TITLE
Add a soft limit on index name/mapping type

### LINKED ISSUE #33651: limit field name length
Adding a soft limit to the field name length in case users need to limit the number of characters in a field's name.

### PR DESCRIPTION
**Pull request by MarianaFerrDias**
Added a soft limit on fields that have a hard limit such as index name/mapping type (255 char) and field name (50 chars).

Closes #33651

### CODE REVIEW

**Review by cbuescher — CHANGES_REQUESTED** [review]
Hi  @MarianaFerrDias, 

thanks for opening this PR. Before I dive into a review, could you please briefly state what kind of problem your PR adresses and if it refers to an open issue? From your description and briefly looking at the code I can see you want to limit some index and fieldname lengths, but I would be interest4ed why the existing limits don't work for you.

**Comment by cbuescher** [comment]
@MarianaFerrDias sorry, I overlooked the issue number right in the title of this PR, allow me to edit the title a bit and add the issue number to the description.

**Review by cbuescher — CHANGES_REQUESTED** [review]
Hi @MarianaFerrDias,

after taking a quick first look at this PR I have some general comments:

- could you limit this PR to changes on the limit of the field name length like #33651 suggested? It makes the PR more focused and easier to review, also looking at #33651 I'm not sure we'd want to add a soft limits on index names at this point
- rather than adding new constants (e.g. in MappingMetaData) we are looking for a way for users to be able to configure this limit in the settings. The way your change works those would be fixed again. 
- you are adding changes to the stream serialization, but the field lengths should rather be checked when new mappings are added or updated
- please add some tests that to demonstrate and check what your change is doing

**Comment by tomcallahan** [comment]
@MarianaFerrDias are you still interested in doing this?

**Comment by michaelbaamonde** [comment]
@MarianaFerrDias Closing this out, but feel free to reopen if you're interested.

**Pull request closed without merging**
