### PR TITLE
[DOCS] Fix typos in several REST API specs 

### PR DESCRIPTION
**Pull request by dpickett**

### CODE REVIEW

**Review by cbuescher — APPROVED** [review]
LGTM

**Comment by cbuescher** [comment]
@elasticmachine test this please

**Review by jrodewig — APPROVED** [review]

**Comment by jrodewig** [comment]
### Backport commits
master: c3b5f71 
7.x: 00b0ab2bbe9
7.6: da2277e7f04
7.5: b50163b60c6

**Comment by jrodewig** [comment]
Thanks @dpickett!

**Pull request merged**
