### PR TITLE
Add aditional logging for ILM history store tests

### PR DESCRIPTION
**Pull request by dakrone**
These tests use the same index name, making it hard to read logs when
diagnosing the failures. Additionally more information about the current
state of the index could be retrieved when failing.

This changes these two things in the hope of capturing more data about
why this fails on some CI nodes but not others.

Relates to #50353

### CODE REVIEW

**Comment by dakrone** [comment]
(This PR is so that I can run CI over and over for these tests, it does not yet contain the fix)

**Comment by dakrone** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by dakrone** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by dakrone** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by dakrone** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by dakrone** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by dakrone** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by dakrone** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by dakrone** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by dakrone** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by dakrone** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by dakrone** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by dakrone** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by dakrone** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by dakrone** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by dakrone** [comment]
@elasticmachine run elasticsearch-ci/2

**Review by cbuescher — APPROVED** [review]
Looks like its not failing that often now, I'd be okay to remove the mutes and get the additional logging into the real CI rotation even this isn't a fix (maybe just change the issue title then)...

**Comment by dakrone** [comment]
@elasticmachine update branch

**Pull request merged**
