### PR TITLE
pass the task to broadcast actions

### PR DESCRIPTION
**Pull request by scampi**
Since the task is required as per line 292, give the opportunity to broadcast actions to handle tasks.

### CODE REVIEW

**Comment by bleskes** [comment]
@scampi thanks for picking up this discrepancy, but if we do this, I think we should go further and completely remove `TransportBroadcastAction#shardOperation(ShardRequest)` in favor of `TransportBroadcastAction#shardOperation(ShardRequest, org.elasticsearch.tasks.Task)`. Are you good with doing it?

**Comment by scampi** [comment]
@bleskes sure, see last commit. Can you execute the jenkins test ? I was not able on my local to run the check because of missing java7_home and java9_home envs.

**Comment by javanna** [comment]
@bleskes the last build was green. Is this ready to be merged?

**Comment by bleskes** [comment]
@javanna thanks for the ping. I lost sight of this. Merging..

**Pull request merged**
