### PR TITLE
for avoid startup error

### PR DESCRIPTION
**Pull request by nakaikanako**
[1]: max number of threads [2048] for user [elasticsearch] is too low, increase to at least [4096]

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by albertzaharovits** [comment]
Setting a very large number of threads can mask a potential problem.
Can you describe your configuration, ie `elasticsearch.yml`, OS ? Are there any other processes running under the `elasticsearch` user?
Also, consider using the [forum](https://discuss.elastic.co/c/elasticsearch) because this sounds to me as a deployment configuration issue.

I am going to close this, but feel free to open an `issue ` including the reproduction configuration.

**Comment by jasontedor** [comment]
@albertzaharovits This is a doc bug the community member is proposing a fix for. I will review this later.

**Comment by jasontedor** [comment]
@nakaikanako Can you please sign our CLA?

**Comment by nakaikanako** [comment]
@jasontedor 
sorry for late reply.
I signed CLA.
I setuped using this document page, but elasticsearch6 required 4096 for nproc.
former elasticsearch5 required 2048 for nproc but it seems changed from elasticsearch6.
so please upgrade this document page too.

```
[2017-11-24T14:14:17,918][INFO ][org.elasticsearch.bootstrap.BootstrapChecks] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
[2017-11-24T14:14:17,922][ERROR][org.elasticsearch.bootstrap.Bootstrap] node validation exception
[1] bootstrap checks failed
[1]: max number of threads [2048] for user [elasticsearch] is too low, increase to at least [4096]
```

**Comment by albertzaharovits** [comment]
@nakaikanako Sorry I dismissed you! It did not appear to me that you were referring to the bootstrap exception.
Can you please double check you have signed the CLA, the GH check should turn green: `Commit author has not signed the CLA and is not a member of Elasticsea..`

**Comment by jasontedor** [comment]
@nakaikanako Indeed, this is a bug in the docs since 6.0.0 and thank you for opening a fix for it. I checked our CLA records and I do not see a submission for you. Would you mind trying again?

**Comment by nakaikanako** [comment]
@jasontedor 
I signed the CLA again, please check CLA records.
Thank you.

**Comment by tvernum** [comment]
Thanks @nakaikanako, we have your CLA on record now.

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by jasontedor** [comment]
Relates #20874

**Comment by jasontedor** [comment]
Thanks @nakaikanako!

**Pull request merged**
