### PR TITLE
Added SLES11 support to RPM

### PR DESCRIPTION
**Pull request by winpat**
- Changed Init Script location from "/etc/rc.d/init.d" to "/etc/init.d"
- Removed lockfile mechanism in Init Script
- Implemented SUSE function libaries in Init Script
- Made Init Script functions SUSE compliant

Tested on Centos 6.5 and SLES11 SP3

### CODE REVIEW

**Comment by electrical** [comment]
@spinscale can you take a look at this please?

**Comment by tlrx** [comment]
LGTM.

Tested manually on CentOS6.6 and OpenSUSE 11.4

**Comment by clintongormley** [comment]
@spinscale could you review when you have a moment please

**Comment by deradam** [comment]
I just tested the fixed init config and it is working correctly on SLES 11 SP3 (https://github.com/winpat/elasticsearch/commit/72ffb4c9eb593c2d6526710463c35eec4c3d7324). Thanks for that. I did however notice after the installation of the rpm (version 1.4.4) that the start script was copied to /etc/init.d/init.d/elasticsearch which is one init.d folder too deep :) Maybe you can have a look at this problem.

**Comment by winpat** [comment]
@deradam Glad it worked! I'm not really sure why the init script gets placed in "/etc/init.d/init.d".

I think the RPM is being created by Apache Maven and this PR also includes a fix to place the init script at the right place ("/etc/init.d")... So I guess we need to wait until this gets merged...

**Comment by dakrone** [comment]
I believe this has been supplanted by #12555

**Pull request closed without merging**
