### PR TITLE
Make keep alive of point in time optional in search

### PR DESCRIPTION
**Pull request by dnhatn**
A search request should not be required to extend the keep_alive of a point in time. This change makes that parameter optional.

### CODE REVIEW

**Review by jimczi — APPROVED** [review]
LGTM

**Comment by dnhatn** [comment]
run elasticsearch-ci/2

**Comment by dnhatn** [comment]
run elasticsearch-ci/packaging-sample-windows

**Comment by dnhatn** [comment]
Thanks Jim!

**Pull request merged**
