### PR TITLE
Refactor custom ES814HnswScalarQuantizedVectorsFormat to use the FlatVectorsScorer API

### PR DESCRIPTION
**Pull request by ChrisHegarty**
This commit removes the copy of the ScalarQuantizedVectorsWriter that we added in 8.14, in favour of a custom FlatVectorsScorer.

Previously we maintained the copy of the writer so that we could add a custom scorer implementation when merging scalar quantized vectors. This is not necessary now as we can provide a FlatVectorsScorer implementation that provides the custom scorer.

### CODE REVIEW

**Comment by ChrisHegarty** [comment]
@elasticmachine retest this please

**Comment by benwtrent** [comment]
https://github.com/apache/lucene/pull/13366

This fixes that tiny test vector failure.

**Review by benwtrent — APPROVED** [review]
:godmode:

**Review by tteofili — APPROVED** [review]

**Comment by ChrisHegarty** [comment]
@elasticmachine retest this please

**Comment by ChrisHegarty** [comment]
@elasticmachine test this please

**Comment by ChrisHegarty** [comment]
@elasticmachine test this please

**Comment by ChrisHegarty** [comment]
@elasticmachine test this please

**Comment by ChrisHegarty** [comment]
@elasticmachine test this please

**Comment by ChrisHegarty** [comment]
@elasticmachine test this please

**Pull request merged**
