### PR TITLE
Use current term in initial leases in engine test

### PR DESCRIPTION
**Pull request by dnhatn**
We need to use the current primary term instead of 1L for the initial
retention leases; otherwise, the primary term of the committed
retention-leases won't match the current primary term if the
retention-leases never gets updated.

CI: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+matrix-java-periodic/ES_BUILD_JAVA=openjdk12,ES_RUNTIME_JAVA=zulu8,nodes=immutable&&linux&&docker/220/console

```
./gradlew :server:unitTest \
  -Dtests.seed=D5239BE5D5D26ED3 \
  -Dtests.class=org.elasticsearch.index.engine.InternalEngineTests \
  -Dtests.method="testKeepMinRetainedSeqNoByMergePolicy" \
  -Dtests.security.manager=true \
  -Dtests.locale=ar-BH \
  -Dtests.timezone=Etc/GMT-9 \
  -Dcompiler.java=12 \
  -Druntime.java=8
```

### CODE REVIEW

**Comment by cbuescher** [comment]
@dnhatn can we mute the test while this PR is not merged? I saw this happening again on 6.7 today: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.7+corretto-periodic/ES_BUILD_JAVA=java11,label=amazon/4/console

**Comment by cbuescher** [comment]
Other occurances: 
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.7+multijob-unix-compatibility/os=amazon/3/console
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+g1gc/342/console

Since its also failing on master I assume that 7.x and 7.0 are also affected. Will open a mute-PR against master, please let me know if you are okay muting this.

**Comment by cbuescher** [comment]
@dnhatn I muted this on master (76b32e6d01592a91e743d5a307b773b1ce2cbe8a), 7.x (e3c7b9391788f21334be0b85febeeb01b8ef861e), 7.0 (061fa7b0bdb21472971d19d222a7648e877a8324) and 6.7 (eb965bb10e18e996ea52cd8c20e7c1d1885c922c).

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by dnhatn** [comment]
@cbuescher @jasontedor thanks.

**Pull request merged**
