### PR TITLE
[8.6] Consolidate google-oauth-client to latest version (#91722)

### PR DESCRIPTION
**Pull request by jakelandis**
Backports the following commits to 8.6:
 - Consolidate google-oauth-client to latest version (#91722)

### CODE REVIEW

**Comment by jakelandis** [comment]
@elasticsearchmachine run elasticsearch-ci/part-1

**Comment by gwbrown** [comment]
@elasticsearchmachine update branch

**Comment by n1v0lg** [comment]
@jakelandis this never got merged. Just sanity checking if it should have been.

**Comment by jakelandis** [comment]
> @jakelandis this never got merged. Just sanity checking if it should have been.

Whoops.... I think I misunderstood `auto-merge` actually does. I will update it, let CI run and merge it.

**Comment by jakelandis** [comment]
closing since 8.7 is already released.

**Pull request closed without merging**
