### PR TITLE
Add cluster UUID and name to audit logs

### LINKED ISSUE #72408: Add `cluster.uuid` to audit logs
### Description

Elasticsearch audit logs don't report the `cluster.uuid` field.
```
{
  "type": "audit",
  "timestamp": "2021-04-28T18:13:54,938+0200",
  "node.id": "-l8lCWofT1WiSzbCl5t65w",
  "event.type": "transport",
  "event.action": "access_granted",
  "authentication.type": "REALM",
  "user.name": "elastic",
  "user.realm": "reserved",
  "user.roles": [
    "superuser"
  ],
  "origin.type": "rest",
  "origin.address": "127.0.0.1:53720",
  "request.id": "J4ttGzQFRrWUPcgvQZyPtQ",
  "action": "indices:data/read/search",
  "request.name": "SearchRequest",
  "indices": [
    ".security"
  ]
}
```

### Proposal

Add `cluster.uuid` to audit logs, in the same way other Elasticsearch logs already do (server, deprecation, etc).

### Why

Observability apps rely on the UUID to identify different clusters and show them properly in the UI.
Users can also leverage this field to create alerts for specific deployments.

### PR DESCRIPTION
**Pull request by justincr-elastic**
New config settings:
- xpack.security.audit.logfile.emit_cluster_uuid: Default=true
- xpack.security.audit.logfile.emit_cluster_name: Default=false

Cluster state is initialized asynchronously during startup. Some audit
logs may be emitted before cluster name and UUID are available.
- Ephemeral node init: No UUID until updated by master node.
- Persistent node init: Random UUID before updated by master node.
- Persistent node restart: Cluster UUID read from cache.

Name is fixed in config. UUID normally does not change, but an exception
is ECE disaster recovery; for same ECE deployment ID it will generate a
new cluster UUID.

Closes #72408

### CODE REVIEW

**Review by tvernum — COMMENTED** [review]
I think we also need to test that the new fields are included in the log output.
See existing tests that use `LoggingAuditTrailTests.assertMsg`

**Comment by justincr-elastic** [comment]
@elasticmachine update branch

**Review by tvernum — COMMENTED** [review]
>  think we also need to test that the new fields are included in the log output.
> See existing tests that use LoggingAuditTrailTests.assertMsg

I think these tests are still outstanding.

**Comment by justincr-elastic** [comment]
@elasticmachine update branch

**Review by tvernum — DISMISSED** [review]
LGTM - this does what it's supposed to. But we will need a follow up PR to close the existing gap in testing.

**Review by tvernum — APPROVED** [review]

**Comment by justincr-elastic** [comment]
@elasticmachine update branch

**Pull request merged**
