### PR TITLE
Adjust ldap timeout for idp fixture

### LINKED ISSUE #40025: [CI] SamlAuthenticatorIT. testLoginUserWithAuthorizingRealm failed
SamlAuthenticatorIT. testLoginUserWithAuthorizingRealm failed on
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=ubuntu-16.04&&immutable/297/console

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.x+multijob-unix-compatibility/os=ubuntu-14.04&&immutable/71/console

```
14:08:04 FAILURE 7.55s | SamlAuthenticationIT.testLoginUserWithAuthorizingRealm <<< FAILURES!
14:08:04    > Throwable #1: java.lang.AssertionError: 
14:08:04    > Expected: <302>
14:08:04    >      but: was <200>
14:08:04    > 	at __randomizedtesting.SeedInfo.seed([5906EE65A5BC7239:B7BE11A01110081]:0)
14:08:04    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
14:08:04    > 	at org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT.lambda$submitLoginForm$2(SamlAuthenticationIT.java:376)
14:08:04    > 	at org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT.execute(SamlAuthenticationIT.java:498)
14:08:04    > 	at org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT.submitLoginForm(SamlAuthenticationIT.java:375)
14:08:04    > 	at org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT.loginViaSaml(SamlAuthenticationIT.java:260)
14:08:04    > 	at org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT.testLoginUserWithAuthorizingRealm(SamlAuthenticationIT.java:249)
14:08:04    > 	at java.lang.Thread.run(Thread.java:748)
```
Locally could not reproduce on 7.x or master with following command:
For master:
```
./gradlew :x-pack:qa:saml-idp-tests:integTestRunner \
  -Dtests.seed=5906EE65A5BC7239 \
  -Dtests.class=org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT \
  -Dtests.method="testLoginUserWithAuthorizingRealm" \
  -Dtests.security.manager=true \
  -Dtests.locale=et-EE \
  -Dtests.timezone=America/Miquelon \
  -Dcompiler.java=11 \
  -Druntime.java=8
```
For 7.x:
```
./gradlew :x-pack:qa:saml-idp-tests:integTestRunner \
-Dtests.seed=15C1EC2DCBCEAFF \
-Dtests.class=org.elasticsearch.xpack.security.authc.saml.SamlAuthenticationIT \
-Dtests.method="testLoginUserWithAuthorizingRealm" \
-Dtests.security.manager=true \
-Dtests.locale=ga \
-Dtests.timezone=America/Araguaina \
-Dcompiler.java=11 \
-Druntime.java=8
```

@jkakavas do you think https://github.com/elastic/elasticsearch/pull/39948 might have caused this intermittent failure?

### PR DESCRIPTION
**Pull request by jkakavas**
This change adjusts the LDAP connection timeout for retrieving
attributes while performing the SAML IT to 5 seconds, from 5 ms
that it previously was.

Resolves: #40025

### CODE REVIEW

**Review by jaymode — APPROVED** [review]
LGTM

**Comment by jaymode** [comment]
Given that this is a test change; this should probably be backported to other versions too? Like 6.7 and 7.0?

**Comment by jkakavas** [comment]
I didn't backport the dockerized idp-fixture to 7.0 and 6.7 so this is not applicable there. But if we think it's worth it I can backport it now and include this change too in one commit

**Comment by jaymode** [comment]
hmm, I'd be in favor of backporting that test change so that way we actually get those tests being run in CI, especially for 6.7 maybe staying around for a while as the last bugfix version

**Comment by jkakavas** [comment]
Will do first thing Monday morning!

**Pull request merged**
