### PR TITLE
Fix max file size check to use getMaxFileSize

### LINKED ISSUE #113705: Elasticsearch fails to startup with valid fsize and virtual memory limits
### Elasticsearch Version

8.15

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Linux

### Problem Description

We have found a few issues with the Bootstrap checks on Linux/Unix machines.  The first is that a value of `-1` should be accepted along with `unlimited` and `infinity` based on [this](https://man.archlinux.org/man/limits.conf.5) documentation.

```
All items support the values -1, unlimited or infinity indicating no limit, except for priority, nice, and nonewprivs. If nofile is to be set to one of these values, it will be set to the contents of /proc/sys/fs/nr_open instead (see setrlimit(3)).
```

The second issue is that [this code](https://github.com/elastic/elasticsearch/blob/ee24f84df0265f5b8bc0baa3dadde6516cf3c073/server/src/main/java/org/elasticsearch/bootstrap/BootstrapChecks.java#L429-L431) appears to be incorrect.

It should be checking for the max file size and **NOT** the max memory size

```java
long getMaxFileSize() {
    return NativeAccess.instance().getProcessLimits().maxFileSize();
}
```

### Steps to Reproduce

Set the `fsize` value to `-1` in the `/etc/security/limits.conf ` file then start up Elastic 8.15.x.

### Logs (if relevant)

```
[2024-09-25T17:00:39,398][ERROR][o.e.b.Elasticsearch ] [node-f41036c7-370b-4665-a0d0-679e2bedef84] node validation exception
[2] bootstrap checks failed. You must address the points described in the following [2] lines before starting Elasticsearch. For more information see [https://www.elastic.co/guide/en/elasticsearch/reference/8.15/bootstrap-checks.html]
bootstrap check failure [1] of [2]: max size virtual memory [-1] for user [###] is too low, increase to [unlimited]; for more information see [https://www.elastic.co/guide/en/elasticsearch/reference/8.15/max-size-virtual-memory-check.html]
bootstrap check failure [2] of [2]: max file size [-1] for user [###] is too low, increase to [unlimited]; for more information see [https://www.elastic.co/guide/en/elasticsearch/reference/8.15/_max_file_size_check.html]
```

### PR DESCRIPTION
**Pull request by prdoyle**
Fixes #113705

Current code accidentally called `maxVirtualMemorySize`.

I've also rearranged the code a little so the unit test can tell that we're checking the right limit. I verified that this test now fails if I reintroduce the original bug.

### CODE REVIEW

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by lukasz-jarocki-sonarsource** [comment]
My apologies if I missed something: - is this going to be merged to 8.15 and be part of 8.15.3 release? So far I don't see these commits in 8.15 branch.

**Comment by prdoyle** [comment]
@lukasz-jarocki-sonarsource - my apologies. I did not correctly trigger our backport automation. I'll backport this manually.

**Comment by prdoyle** [comment]
@lukasz-jarocki-sonarsource - another apology! I backported to 8.16 but not 8.15. New backport is underway in #116152.

**Comment by lukasz-jarocki-sonarsource** [comment]
Thanks, we were wondering why we still have issues with 8.15.

**Pull request merged**
