### PR TITLE
Fix a typo in a warning message in TestFixturesPlugin

### PR DESCRIPTION
**Pull request by olcbean**

### CODE REVIEW

**Review by cbuescher — APPROVED** [review]
@olcbean Makes sense, thanks for the correction.

**Comment by cbuescher** [comment]
@elasticmachine test this please

**Comment by atorok** [comment]
@elasticmachine  run the gradle build tests 1

**Comment by atorok** [comment]
#
@elasticmachine  run the gradle build tests 2

**Comment by atorok** [comment]
@elasticmachine run elasticsearch-ci/2

**Pull request merged**
