### PR TITLE
Add compatibility tests to rest resources artifact

### PR DESCRIPTION
**Pull request by mark-vieira**
Include transformed compatibility tests in our `rest-resources-zip` artifact so that client testing can verify REST compatibility as well.

Core and x-pack tests will live in `rest-api-spec/compatTest/free` and `rest-api-spec/compatTest/platinum` respectively.

cc @philkra

### CODE REVIEW

**Review by jakelandis — CHANGES_REQUESTED** [review]
compatibleApi will also need to be included. We don't transform the API, but we do have 2 different sets of API's on the classpath for compatiblitly testing. One directly from 7.x , and another from the `yamlRestCompatTest` sourceset (soon to be [renamed](https://github.com/elastic/elasticsearch/pull/78418)) .  For example, https://github.com/elastic/elasticsearch/tree/master/rest-api-spec/src/yamlRestCompatTest/resources/rest-api-spec/api is only found in master.

**Comment by mark-vieira** [comment]
Good catch, Jake! I've added the compatibility specs into a separate subfolder `compatApi`.

**Comment by mark-vieira** [comment]
@elasticmachine update branch

**Review by jakelandis — APPROVED** [review]
LGTM

**Pull request merged**
