### PR TITLE
[doc]make scroll sample code more reliable

### PR DESCRIPTION
**Pull request by riverbuilding**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by cbuescher** [comment]
@riverbuilding thanks for opening this PR. Can you elaborate a bit on what you think this change to the code example improves over the old version?

**Comment by riverbuilding** [comment]
@cbuescher
https://discuss.elastic.co/t/how-to-cover-all-conditions-when-fetch-all-data-with-scroll/213461/2
the detail is in this discuss thread:
with one shard, when try to iterator scroll to fetch all data, it falls into infinite loop.

**Review by cbuescher — COMMENTED** [review]
Sorry, even after reading the mentioned discuss thread I don't see why we should have an issue here.
The code in the example is run on a mini-index which uses the default number of shards of 1 and it terminates. Adding the `count` complicates the example needlessly. I would rather see how and why you run into the loop you mentioned on the discuss thread but would prefer this discussion to happen in the forum. 
I'll leave this open for a bit for others to review/comment though

**Comment by DaveCTurner** [comment]
I think we can close this. The loop conditions look correct as documented and `searchResponse.getHits().getTotalHits().value` might be an approximation of the true number of hits.

**Pull request closed without merging**
