### PR TITLE
Core: Remove RequestBuilder from Action

### PR DESCRIPTION
**Pull request by rjernst**
This commit removes the RequestBuilder generic type from Action. It was
needed to be used by the newRequest method, which in turn was used by
client.prepareExecute. Both of these methods are now removed, along with
the existing users of prepareExecute constructing the appropriate
builder directly.

### CODE REVIEW

**Review by nik9000 — APPROVED** [review]
Awesome!

**Comment by nik9000** [comment]
The CI failure comes from a commit in master. If you merge again it'll go away.

**Review by s1monw — APPROVED** [review]
you did this! awesome

**Comment by javanna** [comment]
I have a question on the very breaking nature of this (great) change for our transport client users: are we ok with the possibility that the transport client is not removed in 7.0.0 (effectively we don't know yet if we will make it) and this change ends up breaking most of the existing applications out there, to then break them again in the following major version as we will then have removed the transport client?

**Comment by rjernst** [comment]
@javanna IMO that is fine. We are already recommending users move off the transport client. If removing the transport client doesn't happen for 7, then in order for someone to continue using a (long, by then, deprecated) transport client, they will need to update their usage. I have more changes planned which will continue to simplify how actions are setup/used that I will continue to make in 7, which will improve many other internal parts of the system. Note too that this change helps the high level rest client in that we could now use the request builders there (I thought there was an existing issue for this but I could not find it).

**Comment by javanna** [comment]
Thanks for your thoughts @rjernst . I am not sure about using request builders in the high-level REST client. We went for having a single way of doing things (Requests rather than RequestBuilders) and I thought the idea was to remove RequestBuilders completely one day together with the transport client. Let's discuss this elsewhere though, as it's a separate discussion. I just don't see this as a benefit at the moment, but this change is great for many other reasons.

**Comment by javanna** [comment]
Looking at the changes post-merge, I understood that all the prepare* methods were gone, but they are not. Can we have a summary of what this PR breaks for users, and add a note to the migrate guide?

**Comment by hendrikmuhs** [comment]
Just a quick heads up / note:

This change broke a plugin I am writing, no big deal, but I guess there are other 3rdparty plugins out there which will be affected. There will be some migration guide/document for this and other changes?

**Comment by rjernst** [comment]
@javanna I opened #31401

@hendrikmuhs The note I added in the PR above is all I have planned. We don't currently document changes like this for plugins authors because we do not have a stable plugin api.

**Pull request merged**
