### PR TITLE
Fix verbose logging overhead in Async Shard Fetch

### PR DESCRIPTION
**Pull request by mohit0193**
Today, If some error occurs during Async Shard Fetch then verbose logging of stack trace spamming in log files and also creates significant GC overhead.

We are solving this problem as follows:
Move Logging to DEBUG level for following exceptions
NodeClosedException, NodeDisconnectedException, NodeNotConnectedException 

Suppressing stack trace for  CircuitBreakingException and keeping it at WARN level
CircuitBreakingException

For all other exceptions keeping stack trace at WARN level.

https://github.com/elastic/elasticsearch/issues/57804

### CODE REVIEW

**Comment by mohit0193** [comment]
Signed contributor agreement

**Comment by mohit0193** [comment]
@DaveCTurner : This PR for fixing verbose logging for Async Shard Ferch

 https://github.com/elastic/elasticsearch/issues/57804

**Review by DaveCTurner — CHANGES_REQUESTED** [review]
Thanks @mohit0193. This is the easy bit, but you must also add tests for this change in behaviour.

**Comment by DaveCTurner** [comment]
Hi @mohit0193, are you still working on the missing tests here?

**Comment by DaveCTurner** [comment]
No response for many months, closing this.

**Pull request closed without merging**
