### PR TITLE
[DOCS]Fix AbstractDiffable typo

### PR DESCRIPTION
**Pull request by howardhuanghua**
Fix AbstractDiffable comment typo.

### CODE REVIEW

**Review by MrHeer — APPROVED** [review]

**Comment by howardhuanghua** [comment]
Merged the latest master.

**Comment by howardhuanghua** [comment]
Hi @jrodewig , would you please help to review this doc issue? It's my pleasure to open extra backport pr to 7.x if needed. Thank you.

**Review by jrodewig — APPROVED** [review]
LGTM. Thanks @howardhuanghua.

**Comment by jrodewig** [comment]
@elasticmachine test this please

**Pull request merged**
