### PR TITLE
Add ml licence check to the pipeline inference agg. 

### PR DESCRIPTION
**Pull request by davidkyle**
The same logic as in the inference processor is applied. 

Unfortunately we have to load the model to check the licence level and that happens after all the pipeline agg work has run there is not way to short circuit it and check the licence level before the agg starts work.

### CODE REVIEW

**Comment by benwtrent** [comment]
> Unfortunately we have to load the model to check the licence level 

The model loading service could do this. Its a new refactor, but the license level is stored within the model config. This is loaded BEFORE the definition and is WAY faster to load up. If the license level is unsupported or the request does not override the check (i.e. internal inference request was previously licensed), it can fail before loading and parsing the inference definition object.

But this refactor could happen later. Just an optimization.

**Review by benwtrent — APPROVED** [review]
The code is sound. 

- The license check could be moved to the loading service (optimization).
- Would be good to have a test exercising the license check (obviated if license checking is moved to the loading service)

**Comment by davidkyle** [comment]
I added an integration test. 

Good point about checking the licence with the model config in ModelLoadingService

**Comment by davidkyle** [comment]
@elasticmachine update branch

**Pull request merged**
