### PR TITLE
Revert "Return 200 OK response code for a cluster health timeout (#78968)"

### PR DESCRIPTION
**Pull request by arteam**
This reverts following PRs:

* Revert "Deprecate returning 408 for a server timeout on `_cluster/health` (#78180)" 
* Revert "Use query param instead of a system property for opting in for new cluster health response code (#79351)"
* Revert "Adjust the BWC version for the return200ForClusterHealthTimeout field (#79436)" 
* Revert "Drop pre-7.2.0 wire format in ClusterHealthRequest (#79551)"
* Revert "Allow deprecation warning for the return_200_for_cluster_health_timeout parameter (#80178)"
* Revert "Return 200 OK response code for a cluster health timeout (#78968)"

### CODE REVIEW

**Comment by arteam** [comment]
@elasticsearchmachine update branch

**Comment by arteam** [comment]
@elasticmachine update branch

**Comment by arteam** [comment]
@elasticmachine run elasticsearch-ci/part-1

**Review by henningandersen — APPROVED** [review]
LGTM (if/when CI passes).

**Comment by arteam** [comment]
Thanks Henning!

**Pull request merged**
