### PR TITLE
them → then typo fix

### PR DESCRIPTION
**Pull request by Cladis**

### CODE REVIEW

**Comment by nik9000** [comment]
Thanks @Cladis! I agree with the change so I'll fix it and backport it back to the latest release.

**Comment by nik9000** [comment]
Oh, you made this change to the 5.0 branch.... Usually make the changes to master and backport. And we wouldn't usually go as far back as 5.0 because it is fair old.

**Comment by nik9000** [comment]
In fact this is already fixed in master and it looks like it was fixed at least as far back as 6.0. So there is nothing for me to do.

**Comment by Cladis** [comment]
@nik9000 , well I am reading the 5.0 docs (since I have to deal with the 5.0 software) so for me it makes sense to have annoying things fixed in them :)
If it doesn't make sense on your part, well ok, I can try to report only the staff currently persisting like that 22rd thing from another PR :)

**Pull request merged**
