### PR TITLE
Change setting's deprecation message wording

### PR DESCRIPTION
**Pull request by pgomulka**
depending on whether a message is critical or warning a message should
indicate to check breaking changes documentation (critical level) or
deprecation changes documentation (warn level)

relates #79666

### CODE REVIEW

**Comment by pgomulka** [comment]
ok to test

**Comment by pgomulka** [comment]
@elasticmachine upgrade branch

**Comment by grcevski** [comment]
@pgomulka This looks like an older PR, but the change looks good to me. Have we decided if we wanted to proceed with this change? It appears that few other tests need to be adjusted.

**Comment by mosche** [comment]
As discussed, closing to be revisited for v9 (https://github.com/elastic/elasticsearch/pull/107639)

**Pull request closed without merging**
