### PR TITLE
EQL: Add optional fields and limit joining keys on non-null values only

### PR DESCRIPTION
**Pull request by astefan**
Add optional fields, with usage inside queries' filters and as join keys.
Optional fields have a question mark in front of their name (`?some_field`) and can be used in standalone event queries and sequences.

If the field exists in at least one index that's getting queried, that field will actually be used in queries.
If the field doesn't exist in any of the indices, all its mentions in query filters will be replaced with `null`.
For sequences, optional fields as keys can have `null` as a value, whereas non-optional fields will be restricted to non-null values only.

For example, a query like
```
sequence by ?process.entity_id, process.pid
  [process where transID == 2]
  [file where transID == 0] with runs=2
```
can return a sequence with a join key `[null,123]`.
If the sequence will use `process.pid` as an optional field (`sequence by ?process.entity_id, ?process.pid`), as well, the sequence can now return join keys as `[null,123]`, `[null,null]`, `[512,null]`.

### CODE REVIEW

**Review by costin — CHANGES_REQUESTED** [review]
The change can be made less intrusive by mapping the optional key onto existing concepts.
For example for optional attribute construct a special unresolved attribute by initializing the unresolved message with a singleton string (say 'optional' or '?').
Don't keep track of the optional attributes, simply let the analyzer resolve all of them and add a separate rule in `Finish Analysis` that looks for all unresolved attributes that have defined string and replace them with a null literal.

This takes advantage of folding the expressions and also extracting the null constant if defined as a key. The verifier would not be tripped (and just has to be updated to consider the null type for key compatibility) while BoxedQuery & co only need to care about converting null to exists queries.

**Review by Luegg — COMMENTED** [review]
It looks like the `?` syntax will be used for two distinct things: a) treat a non-existing field as null instead of failing the query and b) also use `null` as a join key

I was not part of the discussions around the feature but I'm wondering wether it wouldn't be better to keep these two concerns separated. In total, there are 4 different ways on how nulls and non-existing fields can be treated in join keys:
- don't use nulls as join key, fail on non-existing field (new default)
- use nulls as join key, fail on non-existing field
- don't use nulls as join key, replace non-existing field with null
- use nulls as join key, replace non-existing field with null (`?` syntax)

The second and third option will not be available to the user with this change but I think the second option is the behavior users might usually prefer if they want to use `null` as join keys (and get a proper error if they misspelled the field name).

Hence, would it make sense to have a separate syntax for including nulls as join keys?  Something like `sequence by foo with nulls, bar ...`

**Review by costin — APPROVED** [review]
In the interest of time, after a discussion with @astefan I've pushed an update based on my comments.
Essentially instead of using one attribute that acts both as a literal, resolved attribute and unresolved one, 3 different attribute classes are introduced.
They simply act as markers and don't introduce new behavior. The upside is the Analyzer and Optimizer can perform fine grained replacement:
- the analyzer does the resolution separately and in case things are not found replaces it with a literal (in a filter) or an MissionOptionalAttribute.
- the optimizer adds non-null constraints based on all mandatory keys (the optional fields are excluded).
This simplifies things by avoiding passing any set or list - the boxed query generator can determine that based on the type of keys and add the or query when needed.

git log:
Replace missing field based on a context either with literal or a dedicated attribute. This allows folding to occur without dealing with aliases or making the named expression act as a literal (which can lead to accidental folding).

Make the mandatory key constraint explicit inside each filter query to help in propagating the constraint across sequences without special handling.

**Review by bpintea — APPROVED** [review]
LGTM

**Pull request merged**
