### PR TITLE
Get eclipse working easier with gradle

### PR DESCRIPTION
**Pull request by rmuir**
This prevents recursive dependencies between 'core' and 'test-framework' and updates the docs.

### CODE REVIEW

**Comment by jpountz** [comment]
+1

**Comment by s1monw** [comment]
that's awesome for all eclipse users! small fix but I assume that took a while to figure out :)

**Comment by rjernst** [comment]
lgtm

**Comment by rmuir** [comment]
Well, its still rough and generates some broken projects:
* smoke-test-client
* smoke-test-plugins

I think ideally we would just inhibit those projects (and probably distribution/ projects like `tar`) from being added to IDE configurations in general? So try to ignore those.

Tests also work from elasticsearch core and plugins (some)

Note that there are problems with plugins with a security.policy, but thats also not unique to eclipse and we just need to fix the resource filtering in general there for any IDE.

**Comment by s1monw** [comment]
what I care usually is to run simple unittests in the IDE for fast iteration I think those compromises are ok.

**Comment by jpountz** [comment]
I don't have the gradle plugin, so I tested your patch by running "gradle -Declipse eclipse" and then I could import the project into eclipse without the circular dependency error. I'm wondering if we could automatically add this property if someone runs "gradle eclipse"?

**Comment by rjernst** [comment]
ok, i think we can try a hack to remove the prop. Try using this:
```
if (gradle.startParameter.taskNames.contains('eclipse') == false) {
```

**Comment by ywelsch** [comment]
That's very syntactic, I would prefer something along the lines of `gradle.taskGraph.whenReady { gradle.taskGraph.hasTask(...) }`

**Comment by jpountz** [comment]
@rjernst it worked when generating files from the command line using 'gradle eclipse'

**Comment by rjernst** [comment]
@ywelsch i dont think that works? by the time the task graph is ready, i think it is too late to add dependency substitutions?

**Comment by ywelsch** [comment]
@rjernst I tried it (because I was in doubt suddenly), and it worked

```
// hack so that eclipse doesn't have circular references
// the downside is, if you hack on test-framework, you have to gradle install
subprojects {
  project.gradle.taskGraph.whenReady { taskGraph ->
    configurations {
      all {
        resolutionStrategy {
          dependencySubstitution {
            if (taskGraph.allTasks.any { it.name == 'eclipseClasspath' }) {
              substitute module("org.elasticsearch:test-framework:${version}") with project("${projectsPrefix}:test-framework")
            }
          }
        }
      }
    }
  }
}
```

**Comment by rjernst** [comment]
@ywelsch I tried it as well, and it "works", but it will not for long:
```
Changed strategy of configuration ':core:compile' after task dependencies have been resolved. This behaviour has been deprecated and is scheduled to be removed in Gradle 3.0
```

**Comment by rjernst** [comment]
I don't think we should worry about the task graph here, we certainly wont' be adding something that depends on the eclipse task (which is the only reason the task graph would be better than the listed tasks).

**Comment by rmuir** [comment]
@rjernst the main thing i see is, that logic does not work when invoked from eclipse itself... But the sysprop always works consistently from the command line or the IDE. I think its a good step for now?

**Comment by rmuir** [comment]
`gradle.startParameter.taskNames` is empty when called via eclipse, that's why that logic doesnt work.

**Comment by rmuir** [comment]
I removed the need to specify a sysprop. eclipse itself sets a ton, its easy to detect.

**Comment by jpountz** [comment]
LGTM

**Pull request merged**
