### PR TITLE
Enable bwc tests after backport #80348 to 8.0 branch.

### PR DESCRIPTION
**Pull request by martijnvg**

### CODE REVIEW

**Comment by droberts195** [comment]
The BWC tests are failing because of the problem I am trying to fix in #81054.  I have had to reenable the BWC tests in that PR to get the altered test to run, so I can merge that one instead of this once I've got the ML test working.  I think my original change must have got through PR CI when BWC tests were disabled and I didn't realise 🤦 .

**Comment by martijnvg** [comment]
>  I think my original change must have got through PR CI when BWC tests were disabled and I didn't realise 🤦 .

No worries! I think there is no good way to figure this out and can happen to anyone.

**Comment by droberts195** [comment]
This shouldn't be needed now as the changes in #81054 include it.

**Comment by martijnvg** [comment]
Thanks @droberts195!

**Pull request closed without merging**
