### PR TITLE
[DOCS] EQL: Add 7.12 release highlight for case-insensitive `~` variants

### PR DESCRIPTION
**Pull request by jrodewig**
Adds a release highlight for #68204

### Preview
https://elasticsearch_69561.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/7.12/release-highlights.html#eql-case-insensitivity

### CODE REVIEW

**Comment by jrodewig** [comment]
@elasticmachine update branch

**Comment by jrodewig** [comment]
@elasticmachine update branch

**Review by costin — APPROVED** [review]
LGTM

**Comment by jrodewig** [comment]
Thanks @costin!

**Pull request merged**
