### PR TITLE
Only ignore IOException when fsyncing on dirs

### LINKED ISSUE #42950: CcrRetentionLeaseIT.testRetentionLeaseRenewedWhileFollowing failure
REPRO:
```
./gradlew :x-pack:plugin:ccr:internalClusterTest --tests "org.elasticsearch.xpack.ccr.CcrRetentionLeaseIT.testRetentionLeaseRenewedWhileFollowing" -Dtests.seed=6B45B0EB94E60FBC -Dtests.security.manager=true -Dtests.locale=th-TH -Dtests.timezone=America/Nome -Dcompiler.java=12 -Druntime.java=8
```
```
Caused by:
17:52:11         java.lang.AssertionError: On Linux and MacOSX fsyncing a directory should not throw IOException, we just don't want to rely on that in production (undocumented). Got: java.nio.file.NoSuchFileException: /var/lib/jenkins/workspace/elastic+elasticsearch+7.2+multijob-unix-compatibility/os/fedora-29&&immutable/x-pack/plugin/ccr/build/testrun/internalClusterTest/temp/org.elasticsearch.xpack.ccr.CcrRetentionLeaseIT_6B45B0EB94E60FBC-001/tempDir-002/leaderd1/nodes/0/indices/Z4GVXxQHQnOU8X_KqskUcw/0/_state
```

Log: 
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.2+multijob-unix-compatibility/os=fedora-29&&immutable/8/console
Build Scans:
https://gradle.com/s/fcrkcq7mi433a
https://gradle.com/s/4sefd5lta3pws
https://gradle.com/s/jmdi2vpgy5ikq

### PR DESCRIPTION
**Pull request by jasontedor**
Today in the method IOUtils#fsync we ignore IOExceptions when fsyncing a directory. However, the catch block here is too broad, for example it would be ignoring IOExceptions when we try to open a non-existant file. This commit addresses that by scoping the ignored exceptions only to the invocation of FileChannel#force.

Closes #42950

### CODE REVIEW

**Comment by jasontedor** [comment]
@elasticmachine update branch

**Review by rjernst — APPROVED** [review]
Lgtm

**Comment by rjernst** [comment]
@elasticmachine run elasticsearch-ci/bwc
@elasticmachine run elasticsearch-ci/default-distro

**Review by original-brownbear — APPROVED** [review]
LGTM, much better than what I did :)

**Comment by original-brownbear** [comment]
@elasticmachine run elasticsearch-ci/bwc
@elasticmachine run elasticsearch-ci/default-distro

**Comment by jasontedor** [comment]
@elasticmachine update branch

**Pull request merged**
