### PR TITLE
Add test to verify force primary allocation on closed indices

### PR DESCRIPTION
**Pull request by dnhatn**
This change adds a test verifying that we can force primary allocation on closed indices.

Relates #33888

### CODE REVIEW

**Comment by ywelsch** [comment]
Can you also add a test for force-allocating an empty (closed) primary?

**Comment by dnhatn** [comment]
@ywelsch 

> boolean useStaleReplica = randomBoolean(); // if true, use stale replica, otherwise a completely empty copy

This test randomly allocates a stale replica or an empty copy. Are you okay with this? I can add a new test.

**Review by ywelsch — APPROVED** [review]
Missed that :)

**Comment by dnhatn** [comment]
Thanks @ywelsch.

**Pull request merged**
