### PR TITLE
Set context class loader for plugin initialization to plugin's class …

### PR DESCRIPTION
**Pull request by dweiss**
…loader.

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by rjernst** [comment]
@elasticmachine ok to test

**Comment by dweiss** [comment]
Oh, cool. Can I give this elasticmachine orders? Bring icecream and coffee, elasticmachine. :)

**Comment by dweiss** [comment]
Seems like the core also needs setContextClassLoader permission (or should it be wrapped in access controller)?
```
 Caused by: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "setContextClassLoader")
21:36:25 »  	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:?]
21:36:25 »  	at java.security.AccessController.checkPermission(AccessController.java:895) ~[?:?]
21:36:25 »  	at java.lang.SecurityManager.checkPermission(SecurityManager.java:322) ~[?:?]
21:36:25 »  	at java.lang.Thread.setContextClassLoader(Thread.java:1522) [?:?]
21:36:25 »  	at org.elasticsearch.plugins.PluginsService.loadBundle(PluginsService.java:617) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
21:36:25 »  	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:437) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
21:36:25 »  	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:161) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
21:36:25 »  	at org.elasticsearch.node.Node.<init>(Node.java:319) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
21:36:25 »  	at org.elasticsearch.node.Node.<init>(Node.java:268) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
21:36:25 »  	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:225) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
21:36:25 »  	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:225) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
21:36:25 »  	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:387) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
21:36:25 »  	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170) ~[elasticsearch-8.0.0-SNAPSHOT.jar:8.0.0-SNAPSHOT]
```

**Comment by rjernst** [comment]
>  Can I give this elasticmachine orders?

I don't think it listens to anyone outside the elastic org, but now that I have triggered it, I *think* that it will automatically test any pushes.

> Seems like the core also needs setContextClassLoader permission (or should it be wrapped in access controller)?

I believe we need both. The permission should be in the file `server/src/main/resources/org/elasticsearch/bootstrap/security.policy`. But we don't want to use the bare `grant` statement, since that would give it to all code. Instead, we need a jar specific grant. We don't have one for core at the moment, but I think it will look something like this, which should probably go above the bare grant:

```
grant codeBase "${codebase.elasticsearch}" {
  // so we can set the context class loader when loading plugins
  permission java.lang.RuntimePermission "setContextClassLoader";
};
```

**Comment by dweiss** [comment]
I admit I know very little about ES security policies and internals so I'd be much more confident if you add these required permission grants...

**Comment by rjernst** [comment]
> I'd be much more confident if you add these required permission grants

No problem, I pushed 1018657 to your branch.

**Comment by dweiss** [comment]
Fails with insufficient permissions. Can't tell why.
I tried adding addClassCodebase(codebases, "elasticsearch", "org.elasticsearch.plugins.PluginsService"); to BootstrapForTesting.java but this doesn't help.

**Comment by rjernst** [comment]
> I tried adding addClassCodebase(codebases, "elasticsearch", "org.elasticsearch.plugins.PluginsService")

That should work, and worked for me to fix the tests locally at least (baf809e). Note that in this case it needs to happen outside the tests.gradle check because it needs to be added always, not just when running in IntelliJ.

**Comment by dweiss** [comment]
Ah. I had it inside the if clause - didn't know what that property was
doing and was just blindly following the rest of the code. Thank you!

Dawid

**Comment by rjernst** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by rjernst** [comment]
Thanks @dweiss!

**Comment by dweiss** [comment]
Thank you for helping out, Ryan.

**Pull request merged**
