### PR TITLE
Add support for serialization of Duration and Period

### PR DESCRIPTION
**Pull request by ChrisHegarty**
This commit adds support to stream's read/write generic value for `j.t.Duration` and `j.t.Period` (similar to `j.t.OffsetTime`).

### CODE REVIEW

**Comment by ChrisHegarty** [comment]
An alternative approach is to add explicit support, rather than implicit support through `XXXGenericValue`, e.g. similar to the public `StreamInput::readInstant` method. But in my use case, I do not know the type (without checking it). If we decide to add explicit support, then a simple refactoring with a type check should be sufficient for my use case.    It's not immediately clear that this is worth being explicit, given that stream's currently have both kinds of support for different `java.time` types.

**Review by thecoop — APPROVED** [review]
LGTM. Are there other java.time classes we could do with adding at the same time?

**Comment by ChrisHegarty** [comment]
> Are there other java.time classes we could do with adding at the same time?

I don't have use for any others. And we seem to have reasonable coverage with these additions.

**Review by rjernst — APPROVED** [review]
LGTM

**Pull request merged**
