### PR TITLE
Preserve old serialization for CompletionFieldMapper

### PR DESCRIPTION
**Pull request by romseygeek**
The conversion of CompletionFieldMapper to use parametrized format in
#59291 resulted in a change in the way the mappings were serialized, as
the old implementation would emit all parameters without regard for defaults.
This causes issues in mixed clusters, because we check that a no-op mapping
update leaves the serialized representation of mappings unchanged, and in a
mixed cluster scenario a 7x master could send mappings containing a completion
field with all parameters emitted to an 8x data node, which would then serialize
its own mappings without emitting parameters with default values.

This commit reverts CompletionFieldMapper back to using its old serialization
strategy.  In addition, it adds the ability to set a default value that depends on
the value of another parameter, fixing a bug in how we were setting search
analyzers.

### CODE REVIEW

**Comment by romseygeek** [comment]
The downside of this approach is that it might look weird to users that completion fields appear in some mappings with a bunch of extra parameters.  The upside is that it lets us keep all our assertions about mapping upgrades enabled during the mixed cluster qa tests.

**Comment by nik9000** [comment]
I wonder if we can continue to serialize all of the old stuff all the time. It might be weird, but it feels bad to make these changes while trying to refactor the parsing.

**Comment by romseygeek** [comment]
> I wonder if we can continue to serialize all of the old stuff all the time.

+1, have pushed a change to do this.

**Comment by romseygeek** [comment]
Using the previous serialization strategy revealed a bug in how I was setting up default values for the search analyzer; instead of having a fixed default, it needs to default to the value of another analyzer.  So I've changed the 'default' parameter on `Parameter` from a concrete value to a supplier, meaning that you can say 'the default value of this param is the actual value of this other param'.

**Review by nik9000 — APPROVED** [review]
LGTM

**Pull request merged**
