### PR TITLE
Remove obsolete comment

### PR DESCRIPTION
**Pull request by Philippus**
"docs/java-api/index.asciidoc" does not exist anymore.

### CODE REVIEW

**Comment by mark-vieira** [comment]
Not sure what his comment was even originally referring to. Perhaps @rjernst knows or remembers.

**Comment by rjernst** [comment]
This had to do with the transport client ([here](https://github.com/elastic/elasticsearch/commit/54a996ba875dcb7799adc7d5641b2352bf5dd28c) is the commit that added the comment). Since the transport client is gone, the comment is indeed obsolete.

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by rjernst** [comment]
Thanks @Philippus

**Pull request merged**
