### PR TITLE
Support geo_point fields in lucene expressions

### PR DESCRIPTION
**Pull request by rmuir**
This adds minimal support for geo_point fields to expressions, with a barebones api (`.empty`, `.lat`,  `.lon`).

For example `_score + haversin(38.9072, 77.0369, doc['location'].lat, doc['location'].lon)`

I reorganized the code here significantly. This means expressions now has 3 "types" (numeric, date, and geo) rather than just 2, so we have to organize things better to support that. 

It means more code but IMO simpler code, otherwise we need a ton of conditionals to check that some method call or variable access is really allowed by the specific type.

I tried to also reorganize the expressions docs a bit in the same fashion.

### CODE REVIEW

**Comment by rjernst** [comment]
LGTM. One suggestion is to make all the ValueSource classes pkg private, I think it was an oversight as to why the existing ones are public.

**Comment by rmuir** [comment]
Thanks ryan. I pushed a new commit.

**Comment by rjernst** [comment]
Great, thanks for the cleanups. Still looks good.

**Comment by jdconrad** [comment]
LGTM too.  This is a nice improvement.  Thanks for doing this!

**Pull request closed without merging**
