### PR TITLE
Don't double-wrap expression values

### PR DESCRIPTION
**Pull request by romseygeek**
After commit #53661 converted the `lang-expressions` module to using 
`DoubleValuesSource`, we've seen a performance regression for expressions
that use geopoints.  Some investigation suggests that this may be due to 
`GeoLatitudeValueSource` and `GeoLongitudeValueSource` wrapping their
per-document values in a `DoubleValues.withDefault()` class.  Values exposed
via expressions already have a '0' default value, so this extra wrapping is 
unnecessary, and is directly on the hot path.  This commit removes the extra
wrapping.

### CODE REVIEW

**Comment by romseygeek** [comment]
@elasticmachine update branch

**Review by rjernst — COMMENTED** [review]
Doesn't the default value handling need to be added back into the `doubleValue()` method since it is no longer handled by the wrapper?

**Comment by romseygeek** [comment]
There's actually another wrapper, in `ExpressionValueSource`, although looking at it now I think there's a bug - it's not always returning `true` from `advanceExact`

**Comment by romseygeek** [comment]
Looking closer, the bug in lucene here doesn't affect us because we never actually check the return value of `advanceExact()` in `ScoreScript#execute`

**Review by rjernst — APPROVED** [review]
Thanks for the explanation. I see now in ExpressionValueSource how it handles the default.

**Comment by romseygeek** [comment]
@elasticmachine update branch

**Pull request merged**
