### PR TITLE
Fix CcrRepositoryIT.testCcrRepositoryFetchesSnapshotShardSizeFromIndexShardStoreStats

### PR DESCRIPTION
**Pull request by tlrx**
This test failed sometimes for various reasons: an empty bulk request that can't be validated, a background force-merge that completes after the store stats were collected and finally an assertBusy() that waits 10 seconds while we usually wait 60s on the follower cluster in CCR tests.

Closes #64167

### CODE REVIEW

**Comment by tlrx** [comment]
@original-brownbear would you have some time to review this one? It should be quick. Thanks

**Comment by original-brownbear** [comment]
@tlrx of cause :) Sorry, completely forgot about this one, last week. Will take a look shortly.

**Review by original-brownbear — APPROVED** [review]
LGTM, this was a quick on indeed :) Thanks Tanguy

**Comment by tlrx** [comment]
Thanks Armin!

**Pull request merged**
