### PR TITLE
Move async search yaml tests to x-pack yaml test folder

### PR DESCRIPTION
**Pull request by javanna**
The yaml tests for async search currently sit in its qa folder. There is no reason though for them to live in a separate folder as they don't require particular setup. This commit moves them to the main folder together with the other x-pack yaml tests so that they will be run by the client test runners too.

### CODE REVIEW

**Review by jimczi — APPROVED** [review]
LGTM

**Comment by javanna** [comment]
run elasticsearch-ci/default-distro

**Comment by javanna** [comment]
elasticsearch-ci/bwc

**Comment by javanna** [comment]
run elasticsearch-ci/bwc

**Pull request merged**
