### PR TITLE
Whitelist expansion

### PR DESCRIPTION
**Pull request by rmuir**
Most of these improvements focus on the basic types:
- add compare/compareTo/toHexString/parseX for basic types
- add Integer/Long/Float/Double min/max and remove the imax/lmax stuff
- add Character methods like isWhiteSpace and similar
- add Math E and PI constants.

We need to followup with docs improvements (its already out of date anyway). In general I think the way we present that needs to be re-organized completely. There is a lot more to do here, but these changes are all simple and easy.

### CODE REVIEW

**Comment by jdconrad** [comment]
LGTM.  Thanks for adding more!

**Comment by uschindler** [comment]
Do we also have some real read/write on fields, so we can check painless DefField class? Static fields don't help... Currently there is no way to test the code!

**Comment by rmuir** [comment]
This PR is really just to capture "easy wins". I know the problem there, but we should solve it differently IMO. I also omitted any date apis or similar here for the same reason. They are more complex.

**Comment by jdconrad** [comment]
@uschindler So there were actually tests for this before, but they got removed when we decided to make Definition a singleton.  It should be possible to have a dummy dictionary again for field tests, but this should probably be a separate issue.

**Comment by uschindler** [comment]
@jdconrad thanks for this. I think this is ok for now. I'd suggest to add some "undocumented" fake class for testing that is added to the Definition.

**Pull request merged**
