### PR TITLE
Non-final method invocation in constructor

### PR DESCRIPTION
**Pull request by krisds**
As requested, I will split #38033 into separate PRs. Here is the first part.

This one resolves:

* [Non-final method invocation in constructor](https://lgtm.com/projects/g/elastic/elasticsearch/snapshot/dist-1916470085-1548143539391/files/server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java#x4e06dc48702dac54:1)
* [Non-final method invocation in constructor](https://lgtm.com/projects/g/elastic/elasticsearch/snapshot/dist-1916470085-1548143539391/files/server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java?sort=name&dir=ASC&mode=heatmap#xaeb362a26c0fdaf1:1)
* [Non-final method invocation in constructor](https://lgtm.com/projects/g/elastic/elasticsearch/snapshot/dist-1916470085-1548143539391/files/server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java?sort=name&dir=ASC&mode=heatmap#x5c00888239d02f3a:1)

### CODE REVIEW

**Review by henningandersen — CHANGES_REQUESTED** [review]
Thanks @krisds for this PR. I can see the problem in the constructor and your solution looks like it would solve that. However, I would like to propose to do this in a different way: move the offending parts in `BlobStoreRepository` out of the constructor and into the `doStart` method instead. This should ensure correct initialization in a simpler way.

Did you look into writing a unit test provoking an issue for this? I suspect, we would not error on bad chunksize settings, that should be relatively easy to provoke.

**Comment by krisds** [comment]
Thanks for the tip, @henningandersen. I'll try a rewrite as suggested.

Any suggestions on where a unit test for this should go ? Any existing unit test I could try to base this on ?

**Comment by henningandersen** [comment]
I think this new test belongs in `BlobStoreRepositoryTests`, that class also contains `setupRepo` that sets up a filesystem like store.

**Comment by krisds** [comment]
I hope this is about what you expected. I'm not familiar enough with the project to make sure the expected test result is correct. It rejects bad values for chunksize, which make some sense to me, but please doublecheck.

**Comment by henningandersen** [comment]
Thanks for your update, looks good. Added one more test and a small correction, have pushed this back to your branch for inclusion into this PR.

**Comment by henningandersen** [comment]
test this please

**Comment by henningandersen** [comment]
test this please

**Comment by krisds** [comment]
Looks good to me. Test passes on my machine.

**Comment by henningandersen** [comment]
@elasticmachine test this please

**Comment by henningandersen** [comment]
I have had a second set of eyes on this and our suggestion is to fix the compress problem by instead passing it into the constructor and moving the `compress` boolean to the `BlobStoreRepository`. We should then be able to remove the isCompress method completely. This will furthermore remove the need for the clunky test I added.

@krisds, do you want to carry out this work? If this is larger than what you intended with your contribution, we can also take over this work.

**Comment by krisds** [comment]
@henningandersen, I don't mind if you want to take over. It will be a few days before I can get back to this myself anyway. As long as we get a nice fix, I'm happy.

**Comment by henningandersen** [comment]
@krisds thanks for raising this PR. As agreed above, I have opened a new PR containing the necessary changes here: #39073 . I will therefore close this PR.

**Pull request closed without merging**
