### PR TITLE
Standardized exception messages

### PR DESCRIPTION
**Pull request by ZERDICORP**
Standardized the text of exception messages for parameters of methods of the `SearchSourceBuilder` & `CountRequest` classes.
Messages are reduced to the general structure:
```
[param] <message>, got <value>
```

### CODE REVIEW

**Comment by javanna** [comment]
hi @ZERDICORP thanks for your contribution. Is your PR fixing an existing issue? If so I don't see it linked in the PR description.

**Comment by ZERDICORP** [comment]
hi @javanna, no, this PR is not related to any issue

**Comment by javanna** [comment]
@elasticmachine ok to test

**Comment by javanna** [comment]
@elasticmachine update branch

**Comment by javanna** [comment]
@ZERDICORP I see how you came up with this improvement. I will try to get it merged, though for the next time I'd suggest that you take one of the existing issues marked help wanted or good first issue, so that we make sure that your energy (as well as ours) is spent on tasks that we would like to see prioritized. 

I ran the build and I see some spotless violations. Could you please run `./gradlew spotlessApply` ?

**Comment by javanna** [comment]
It looks like there are also some test errors, could you please look at those and address them? Thanks!

**Comment by javanna** [comment]
Closing for lack of feedback. Feel free to reopen once you are ready to pick this back up.

**Pull request closed without merging**
