### PR TITLE
token_count type : add an option to count tokens (fix #23227)

### LINKED ISSUE #23227: token_count type : add an option to count tokens (and not positions)
**Elasticsearch version**: 2.4.2 and 5.2.1

**Description of the problem including expected versus actual behavior**:
Currently, if I have a "token_count" field, based on an analyzer containing a stop filter, the indexed "token_count" field counts stop words. 
It would be great to have an option to only count analysis result tokens.

**Steps to reproduce**:
 1. I have this index configuration :
``` json
{
  "settings": {
    "index": {
      "analysis": {
        "analyzer": {
          "default": {
            "tokenizer": "standard",
            "filter": [
              "standard",
              "lowercase",
              "stop_words"
            ]
          }
        },
        "filter": {
          "stop_words": {
            "type": "stop",
            "stopwords": [
              "this", "is", "a"
            ]
          }
        }
      }
    }
  },
  "mappings": {
      "properties": {
        "mytext": {
        	"index": "analyzed",
         	"type": "string",
         	"analyzer": "default",
         	"fields": {
         		"length": {
         			"type": "token_count",
         			"analyzer": "default",
         			"store": "yes"
         		}
         	}
        }
      }
    }
  }
}
```
 2. I index this document :
``` json
{
 "mytext": "this is a cat"
}
```
 3. I make this search query :
```
GET _search
{
  "query": {
    "query_string": {
      "query": "mytext.length:1"
    }
  }
}
```
 4. It should return 1 result. But it actually returns 0 result.

### PR DESCRIPTION
**Pull request by fbaligand**
Add option "enable_position_increments" with default value true.
If option is set to false, indexed value is the number of positions
(position increments are not counted)

This is a backport from PR #24175

### CODE REVIEW

**Comment by jimczi** [comment]
We don't backport new features to old branches so is there anything that prevents you to upgrade to 5.x ?

**Comment by fbaligand** [comment]
Hi @jimczi,

There's no "blocking" thing that prevents my company's project to upgrade to 5.x.

**Comment by jimczi** [comment]
Ok thanks @fbaligand, I'll close this pull request then. New features should only be added to the latest branch otherwise people would never upgrade ;)

**Comment by fbaligand** [comment]
that's not false :)

**Pull request closed without merging**
