### PR TITLE
More optimal forced merges when max_num_segments is greater than 1

### PR DESCRIPTION
**Pull request by wjp719**
In Lucene when force merge, it tends to produce some segment whose size is as close to other segments as possible. This behavior will save merge time and is benefit for query performance later.

But In EsTieredMergePolicy, it set forcedMergePolicy.setMaxMergedSegmentMB(Double.POSITIVE_INFINITY) , it break Lucene behavior,  it will produce some very large  segments while other is small if the force merge maxSegmentCount is not 1. 

This PR moves back to Lucene's TieredMergePolicy. This only changes the behavior of forced merges when `max_num_segments` is greater than 1 and a shard is larger than the maximum merged segment size (5GB by default). In that case, `_forcemerge` will try to create evenly sized segments, while it would previously prefer to create segments that are organized in tiers of exponential sizes.

### CODE REVIEW

**Comment by wjp719** [comment]
image

this is the result of force merge one shard of 38GB to 6 segments with current esMerge policy, these sizes of segments are obviously not balanced

**Comment by wjp719** [comment]
@jpountz Hi, can you help to review this pr?

**Comment by wjp719** [comment]
@martijnvg  @danhermann  Hi, can you help to find someone to review this PR?

**Comment by wjp719** [comment]
@elasticmachine update branch

**Comment by jpountz** [comment]
For what it's worth the current behavior is intentional (see the comment above the line that you changed).

Can you give more details around why you would rather like a 50GB index to consist of 10 segments of 5GB each rather than 1 segment of 50GB?

For context, fully force-merged indices work better with some other features such as:
 - The frozen tier and slow storage in general. The number of seeks that searches need to perform is a function of the number of segments.
 - Terms and composite aggregations. Single-segment indices do not need to build global ordinals as segment ordinals are already global.

**Comment by wjp719** [comment]
> intentional

@jpountz Thank you for your reply. 

In kibana discovery scenario, it runs count aggregation and search topN doc in **desc** order both. We indexSort the doc according to  timestamp field in **asc** order to speed up the count aggregation based on [pr#63643](https://github.com/elastic/elasticsearch/pull/63643) and [this lucene issue's idea](https://issues.apache.org/jira/browse/LUCENE-10425). 

While the search topN is in **desc** order, the early termination and Lucene `NumericComparator` skiping non-competitive docs neither workers because the index sort order and search order are opposite. So we prefer to split segment to small and balanced size ones, so the skip non-competitive docs between segments can work well.

Could you help to give some suggestions to us, thanks a lot

**Comment by wjp719** [comment]
@jpountz In the meantime, the segment number of force merge is set by users. If users set it to 10, users usually tends to get 10 segments whose size are close to each other. Are there cases that 10 segments whose size vary much are better than 10 segments whose size are balanced?

**Comment by jpountz** [comment]
> Are there cases that 10 segments whose size vary much are better than 10 segments whose size are balanced?

In general merge policies would create segments of similar sizes because it's cheaper to merge small segments than large segments.

If the use-case you care about is Discover and date histograms without children, https://github.com/elastic/elasticsearch/pull/81322 is going to be a better way to speed up the date histogram aggregation. And then you could disable the index sort on `@timestamp` or use a descending sort rather than ascending to make searches that retrieve most recent matching documents faster?

**Comment by wjp719** [comment]
> #81322 is going to be a better way to speed up the date histogram aggregation

@jpountz yes, we are on the same the way to #81322, but #81322 maybe cannot handle simple query such as a simple `BooleanQuery` with two sub query `pointRangeQuery` and  `termQuery`. But indexSort timestamp in asc order can help to get hit count of  the simple `BooleanQuery` in constant time as described in [LUCENE-10425](https://issues.apache.org/jira/browse/LUCENE-10425). So we do need the indexSort in asc order now.  Of course more complicated query cannot be handled now.

> In general merge policies would create segments of similar sizes because it's cheaper to merge small segments than large segments.

So this PR in general makes sense?

**Comment by jpountz** [comment]
You may be right, I need to look at how TieredMergePolicy works again.

**Comment by wjp719** [comment]
> You may be right, I need to look at how TieredMergePolicy works again.

@jpountz Have you checked whether this PR can work on current `TieredMergePolicy`? thanks.

**Comment by wjp719** [comment]
> You may be right, I need to look at how TieredMergePolicy works again.

@jpountz Hi, may I know any progress for this pr?

**Comment by jpountz** [comment]
Sorry I got busy with other stuff since my last message. Your change is correct, can you remove ESTieredMergePolicy altogether then since the purpose of this class was to override Lucene's behavior for forced merges?

**Comment by wjp719** [comment]
@elasticmachine update branch

**Comment by wjp719** [comment]
> Sorry I got busy with other stuff since my last message. Your change is correct, can you remove ESTieredMergePolicy altogether then since the purpose of this class was to override Lucene's behavior for forced merges?

@jpountz I have removed the `ESTieredMergePolicy` class

**Comment by jpountz** [comment]
@wjp719 Thanks, the change makes sense to me. I updated the issue title/description to better reflect how this change affects forced merges.

**Review by jpountz — APPROVED** [review]

**Comment by jpountz** [comment]
@elasticmachine test this please

**Pull request merged**
