### PR TITLE
_cat/threadpool remove "size" and add "time" params

### LINKED ISSUE #54478: cat thread_pool size enum empty string value
The cat thread_pool rest API spec defines a `"size"` param of type `enum` with possible values:

https://github.com/elastic/elasticsearch/blob/6fcb51dafcd5519937e7169aaec5b499aa88de36/rest-api-spec/src/main/resources/rest-api-spec/api/cat.thread_pool.json#L35-L46

This param is the only example within all the rest API specs with an empty string enum value. An empty string value may require special handling by clients generating source code from the specs, specifically in cases where the client language may represent the possible values as an enum, for example, [the C# (.NET) client](https://github.com/elastic/elasticsearch-net/blob/a0f69f2f93ca446d57926f15af9ba37e053feb85/src/Elasticsearch.Net/Api/Enums.Generated.cs#L290-L305):

```c#
[StringEnum]
public enum Size
{
    [EnumMember(Value = "")]
    Raw,
    [EnumMember(Value = "k")]
    K,
    [EnumMember(Value = "m")]
    M,
    [EnumMember(Value = "g")]
    G,
    [EnumMember(Value = "t")]
    T,
    [EnumMember(Value = "p")]
    P
}
```

[The documentation for size units](https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#size-units) doesn't mention empty string, and it _looks_ like the absence of a size unit value returns sizes in their raw, unmultiplied, values.

With the introduction of a json schema in #54252, the empty string enum value fails validation. Of course, the json schema can be changed to accommodate an empty string value, but since it is the only example and _seems_ to operate the same as specifying no size param, I'm opening this issue to discuss whether the empty string value can be removed.

### PR DESCRIPTION
**Pull request by jakelandis**
The rest spec and documentation for _cat/threadpool supports a "size" parameter.
However, the "size" parameter will have no impact since there are no values
of type "SizeValue" of the return value of this _cat api.

This commit removes the "size" param from the spec and documentation.

This commit also adds support for the "time" param since and support to
format the time param for the "keep_alive" column. By default, the output
should not change since the "TimeValue" rendered default (via RestTable)
is toString(), and the code prior to this also called toString().

closes #54478

### CODE REVIEW

**Review by russcam — APPROVED** [review]
LGTM.

Client generators may use the `params` in REST specs to generate methods/members/types for the allowed parameters for an API. For example

- the .NET client generates [a `Size` enum](https://github.com/elastic/elasticsearch-net/blob/8c3eb48dbb55413577e7e37c53a4c90fc6a958d0/src/Elasticsearch.Net/Api/Enums.Generated.cs#L292-L307) and [a `Size?` property on `CatThreadPoolRequestParameters`](https://github.com/elastic/elasticsearch-net/blob/808969b6ae5f69bddfb04b087d827453465c6ae9/src/Elasticsearch.Net/Api/RequestParameters/RequestParameters.Cat.cs#L1458-L1463)
- the Rust client generates [a `Size` enum](https://github.com/elastic/elasticsearch-rs/blob/7bac8e0ded086b580ec780e45206f07b6564ba64/elasticsearch/src/generated/params.rs#L130-L145) and a [`size()` fn on `CatThreadPool<'a, 'b>`](https://github.com/elastic/elasticsearch-rs/blob/7bac8e0ded086b580ec780e45206f07b6564ba64/elasticsearch/src/generated/namespace_clients/cat.rs#L4660-L4664)
- The go client generates [a `Size` member on `CatThreadPoolRequest`](https://github.com/elastic/go-elasticsearch/blob/e9eb76d55d12256a0777ad825bf25cd5e02fa105/esapi/api.cat.thread_pool.go#L47)

Because of this, I don't believe this change should be backported to 7.x, since it would result in removing these types and members within a major version in clients.

/cc @elastic/es-clients

**Comment by Mpdreamz** [comment]
In the `7.x` branches these parameters can be documented as `deprecated` and the description could read that these parameters are effectively a `noop` or rejected by the server.

**Comment by jakelandis** [comment]
> In the 7.x branches these parameters can be documented as deprecated and the description could read that these parameters are effectively a noop or rejected by the server.

Will do, and will hold up this issue until that is done. (trying to ensure changes go through master first)

**Comment by jakelandis** [comment]
Removed the 7.x labels and will only merge this to 8.x.  I am not adding the >breaking label because this is not technically breaking in ES. Clients (previous to this PR) that sent the "size" param will continue to work as it always did which has no impact on the result. (all the cat APIs support a common set of params and sometimes they are not applicable)

**Comment by jakelandis** [comment]
blocked by https://github.com/elastic/elasticsearch/pull/55984

**Comment by jakelandis** [comment]
@elasticmachine run elasticsearch-ci/bwc 
@elasticmachine run elasticsearch-ci/default-distro

**Comment by jakelandis** [comment]
@elasticmachine update branch

**Comment by jakelandis** [comment]
@elasticmachine update branch

**Pull request merged**
