### PR TITLE
Use System.nanoTime for ThreadPool's estimated time, since it's less likely to go backwards

### PR DESCRIPTION
**Pull request by mikemccand**

### CODE REVIEW

**Comment by s1monw** [comment]
LGTM

**Comment by bleskes** [comment]
does this mean we should add System.currentTimeMillis() to the fobidden APIs?

**Comment by s1monw** [comment]
@bleskes I guess that would make sense... lets see if it's possible though

**Comment by mikemccand** [comment]
> does this mean we should add System.currentTimeMillis() to the fobidden APIs?

+1

We talked about this in #11058 but there are a number of public APIs that expose their System.currentTimeMillis and it wasn't clear if we could change them ... i.e. whether the caller somehow expected to be able to compare results returned from those APIs with their own calls to System.currentTimeMillis.

**Pull request merged**
