### PR TITLE
Remove usage of explicit type in docs

### PR DESCRIPTION
**Pull request by synhershko**
Since Elasticsearch is moving away from index types, here is another piece of docs that was updated to reflect that. Feel free to amend in any way you see fit.

### CODE REVIEW

**Comment by mayya-sharipova** [comment]
@elasticmachine test this please

**Review by mayya-sharipova — APPROVED** [review]

**Review by jpountz — APPROVED** [review]

**Comment by jpountz** [comment]
Looks good. I'm off tomorrow but I'll merge next week unless someone beats me to it.

**Comment by jpountz** [comment]
@elasticmachine test this please

**Comment by synhershko** [comment]
Thanks @jpountz !

**Comment by cjcenizal** [comment]
6.3 7dc484788c9
6.2 868436186a9

**Pull request merged**
