### PR TITLE
[IdP plugin] Surface SP-init flow errors in the same way that IdP-init flow does

### PR DESCRIPTION
**Pull request by lloydmeta**
This PR updates the IdP plugin's /init handler to surface SP-init errors (e.g. with authorisation in) the same way as IdP-init errors, through an Exception that results in a non-200 HTTP status code. At the same , it continues to send the SAML response object with a failed SAML message that that flow is currently returning. In this way, both IdP and SP init flows have unified error handling, while leaving us the flexibility of using a SAML (error) message-based flow if we wish to in the future.

It does this by:
* Introducing a new `SamlInitiateSingleSignOnException` class that can hold a `SamlInitiateSingleSignOnResponse` with the failed SAML message
  * This exception has an override of `metadataToXContent` that serialises its SamlInitiateSingleSignOnResponse if it is present.
* Build `SamlInitiateSingleSignOnException` for handling responses in `TransportSamlInitiateSingleSignOnAction`
* Updating `TransportSamlInitiateSingleSignOnAction` to consistently use the `listener.onFailure(ex)` mechanism for handling failures

Example of the new error response in the SP-init flow from the IT:

```json
{
    "error": {
        "root_cause": [
            {
                "type": "saml_initiate_single_sign_on_exception",
                "reason": "User [es_user] is not permitted to access service [ec:abcdef:123456]",
                "saml_initiate_single_sign_on_response": {
                    "post_url": "https://AVoMOJLJfbru.elastic-cloud.com/saml/acs",
                    "saml_response": "<?xml version=\"1.0\" encoding=\"UTF-8\"?><saml2p:Response xmlns:saml2p=\"urn:oasis:names:tc:SAML:2.0:protocol\" Destination=\"https://AVoMOJLJfbru.elastic-cloud.com/saml/acs\" ID=\"_d73186163618586bd9a671c7ad3d9e399f18b775\" InResponseTo=\"_d7dfe67845acbd717c8f07e7018d99b576d57967\" IssueInstant=\"2023-11-07T08:03:52.193Z\" Version=\"2.0\"><saml2:Issuer xmlns:saml2=\"urn:oasis:names:tc:SAML:2.0:assertion\">urn:elastic:cloud:idp</saml2:Issuer><saml2p:Status><saml2p:StatusCode Value=\"urn:oasis:names:tc:SAML:2.0:status:Requester\"/></saml2p:Status></saml2p:Response>",
                    "saml_status": "urn:oasis:names:tc:SAML:2.0:status:Requester",
                    "error": "User [es_user] is not permitted to access service [ec:abcdef:123456]",
                    "service_provider": {
                        "entity_id": "ec:abcdef:123456"
                    }
                }
            }
        ],
        "type": "saml_initiate_single_sign_on_exception",
        "reason": "User [es_user] is not permitted to access service [ec:abcdef:123456]",
        "saml_initiate_single_sign_on_response": {
            "post_url": "https://AVoMOJLJfbru.elastic-cloud.com/saml/acs",
            "saml_response": "<?xml version=\"1.0\" encoding=\"UTF-8\"?><saml2p:Response xmlns:saml2p=\"urn:oasis:names:tc:SAML:2.0:protocol\" Destination=\"https://AVoMOJLJfbru.elastic-cloud.com/saml/acs\" ID=\"_d73186163618586bd9a671c7ad3d9e399f18b775\" InResponseTo=\"_d7dfe67845acbd717c8f07e7018d99b576d57967\" IssueInstant=\"2023-11-07T08:03:52.193Z\" Version=\"2.0\"><saml2:Issuer xmlns:saml2=\"urn:oasis:names:tc:SAML:2.0:assertion\">urn:elastic:cloud:idp</saml2:Issuer><saml2p:Status><saml2p:StatusCode Value=\"urn:oasis:names:tc:SAML:2.0:status:Requester\"/></saml2p:Status></saml2p:Response>",
            "saml_status": "urn:oasis:names:tc:SAML:2.0:status:Requester",
            "error": "User [es_user] is not permitted to access service [ec:abcdef:123456]",
            "service_provider": {
                "entity_id": "ec:abcdef:123456"
            }
        }
    },
    "status": 403
}
```

While we _are_ changing the response of the SP-init error flow, this does not affect things for our internal use case (and this is an internal plugin), since we were not handling SAML message errors to begin with: the change here would simply make errors flow the same way as the IdP-init flow, which is already handled correctly.

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against main? Unless there is a good reason otherwise, we prefer pull requests against main and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by tvernum** [comment]
I think this implementation is more complex than it needs to be.
One consequence is that you end up with read content embedded inside the standard ES exception output. I don't think you really want that. 

I would, instead, add a `RestStatus` to `SamlInitiateSingleSignOnResponse` and then change `RestSamlInitiateSingleSignOnAction` to set the status code based on that field in the response object.

I can pick that up if you'd like.

**Comment by lloydmeta** [comment]
> I think this implementation is more complex than it needs to be. One consequence is that you end up with read content embedded inside the standard ES exception output. I don't think you really want that.
> 
> I would, instead, add a `RestStatus` to `SamlInitiateSingleSignOnResponse` and then change `RestSamlInitiateSingleSignOnAction` to set the status code based on that field in the response object.

I'd prefer to have the HTTP responses with non-200 HTTP codes (errors) to be the same shape in all cases, so I would actually prefer to have it inside the standard ES exception output. Otherwise, it complicates things and adds work to have to make the client call this endpoint, but then need to handle IdP-init error responses (which are currently in the standard ES exception output) differently from SP-init errors. Accessing the SAML message from the exception an error field is fine for us if we ever plan to use it (no plans now), and it's something that is [already being done with `ScriptException`](https://github.com/elastic/elasticsearch/blob/16cce1fc1a335caa61a764aa843faaffb3e53cbc/server/src/main/java/org/elasticsearch/script/ScriptException.java#L40)

**Review by tvernum — APPROVED** [review]
LGTM

I think the approach of a new special case exception with a custom JSON  output is a bit ugly, but it will do the job, and it's not going to cause any problem.

I think @jakelandis (or someone else from @elastic/es-security) should review because they're going to to be responsbile for maintain the code.

**Comment by tvernum** [comment]
@elasticmachine update branch

**Comment by jakelandis** [comment]
> I think @jakelandis (or someone else from https://github.com/orgs/elastic/teams/es-security) should review because they're going to to be responsbile for maintain the code.

apologies, but I haven't found the time in the past of couple of days. I can review early/mid next week but I am good with @tvernum assessment and don't want to block efforts.

**Review by jakelandis — APPROVED** [review]
LGTM. 

The duplication in the error message is a bit odd, but not a problem. It also sounds like it is intentional ? (If not, happy to help to get look as desired)

**Comment by lloydmeta** [comment]
> The duplication in the error message is a bit odd, but not a problem. It also sounds like it is intentional ? (If not, happy to help to get look as desired)

Do you mean the repetition of `User [es_user] is not permitted to access service [ec:abcdef:123456]` in both the `error.reason` and `error. saml_initiate_single_sign_on_response.error` ? 

If so, it wasn't intentional on my part; IMO we can remove it from the latter, since we won't be consuming it now that it is in `error.reason` as part of the standard ES error format. Shall I remove it?

**Comment by jakelandis** [comment]
Nevermind .... on second look we often have duplicated data serialized here. ElasticsearchException's are their own root causes which causes the duplication between the top level error and root cause array. The duplicated metadata is what stood out here that looked odd, but is actually inline with how we serialize our other exceptions. Sorry for the noise.

**Pull request merged**
