### PR TITLE
re-enable SmokeTestWatcherWithSecurityIT

### PR DESCRIPTION
**Pull request by talevy**
opening this PR to run this on CI a handful of times before deciding if these tests 
really do need to be refactored to be less flaky.

relates to #30777, #35361, #29877.

### CODE REVIEW

**Comment by talevy** [comment]
run tests

**Comment by talevy** [comment]
run elasticsearch-ci/1
run elasticsearch-ci/2

**Review by jakelandis — APPROVED** [review]
LGTM thanks for addressing this.

**Comment by talevy** [comment]
run elasticsearch-ci/1
run elasticsearch-ci/2

**Comment by talevy** [comment]
run elasticsearch-ci/1
run elasticsearch-ci/2

**Comment by talevy** [comment]
run elasticsearch-ci/1
run elasticsearch-ci/2

**Comment by talevy** [comment]
run elasticsearch-ci/1
run elasticsearch-ci/2

**Pull request merged**
