### PR TITLE
Don't document expert segment merge settings

### PR DESCRIPTION
**Pull request by mikemccand**
This is just a baby step to address #13185 by removing the docs for merge settings.

### CODE REVIEW

**Comment by rjernst** [comment]
LGTM

**Comment by s1monw** [comment]
maybe we should just make this a javadoc on the relevant class?

**Comment by mikemccand** [comment]
> maybe we should just make this a javadoc on the relevant class?

OK I'll do that!

**Comment by mikemccand** [comment]
OK I carried over the merge docs as javadocs; I think this is ready!

**Comment by s1monw** [comment]
LGTM

**Comment by radu-gheorghe** [comment]
Just my two cents here: I think removing the docs for this will be a barrier for users trying to understand what merges are about. And experiment with settings to see what works best. Sure, few deployments actually benefit from changes to the merge policy, and I completely get removing support for anything other than the tiered merge policy. But some deployments would benefit, for example, from changing the maximum segment size or the thread count.

I think that simply adding a note that says "hey! changing this is highly unlikely to help!" would be a better option. And then still help them change settings if they want to. Like it was done with the _source field - I think that was an excellent solution (simplify settings + warn users of consequences + possible exceptions).

Somewhat off-topic: there are other places where the same discussion of "people tend to fiddle with them and make things worse". Like thread pool. I think docs are useful in all these cases to make people understand:
- what's going on
- what maaaay need to help their particular case

And I think the only missing piece is to say that people should actually test and see if it works better for them, because more often than not, more segments/threads/etc will not make the cluster fly all of a sudden.

**Pull request merged**
