### PR TITLE
Allow windows hosts file for netty dns resolving

### LINKED ISSUE #73539: [CI] Windows azure repository tests fail with AccessControlException in AzureRepositoryPlugin
**Build scan**: https://gradle-enterprise.elastic.co/s/3n2pftsr72wdm and many others

**Repro line**: None generated, but should be something like:

```./gradlew ':x-pack:plugin:repository-encrypted:qa:azure:internalClusterTest'``` on a Windows machine.

**Reproduces locally?**: yes, on Windows

**Applicable branches**: master, 7.x

**Failure history**:

https://gradle-enterprise.elastic.co/scans?search.relativeStartTime=P7D&search.tags=WINDOWS&search.tags=master&search.tasks=checkPart1&search.timeZoneId=America/New_York

I believe it's been failing since this PR was merged: https://github.com/elastic/elasticsearch/pull/72995

**Failure excerpt**:

```
> Task :x-pack:plugin:repository-encrypted:qa:azure:internalClusterTest
OpenJDK 64-Bit Server VM warning: Option --illegal-access is deprecated and will be removed in a future release.


access denied ("java.io.FilePermission" "C:\Windows\system32\drivers\etc\hosts" "read")
java.security.AccessControlException: access denied ("java.io.FilePermission" "C:\Windows\system32\drivers\etc\hosts" "read")
	at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.base/java.security.AccessController.checkPermission(AccessController.java:1036)
	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:408)
	at java.base/java.lang.SecurityManager.checkRead(SecurityManager.java:747)
	at java.base/java.io.File.exists(File.java:826)
	at io.netty.resolver.HostsFileParser.locateHostsFile(HostsFileParser.java:59)
	at io.netty.resolver.HostsFileParser.parseSilently(HostsFileParser.java:85)
	at io.netty.resolver.DefaultHostsFileEntriesResolver.parseEntries(DefaultHostsFileEntriesResolver.java:75)
	at io.netty.resolver.DefaultHostsFileEntriesResolver.<init>(DefaultHostsFileEntriesResolver.java:37)
	at io.netty.resolver.HostsFileEntriesResolver.<clinit>(HostsFileEntriesResolver.java:28)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at org.elasticsearch.repositories.azure.AzureRepositoryPlugin.lambda$static$0(AzureRepositoryPlugin.java:63)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
	at org.elasticsearch.repositories.azure.AzureRepositoryPlugin.<clinit>(AzureRepositoryPlugin.java:61)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at org.elasticsearch.bootstrap.BootstrapForTesting.<clinit>(BootstrapForTesting.java:169)
	at org.elasticsearch.test.ESTestCase.<clinit>(ESTestCase.java:229)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:466)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$2.run(RandomizedRunner.java:631)
```

Whatever fix we find for this, it is probably relevant to the work needed for issue https://github.com/elastic/elasticsearch/issues/73479

### PR DESCRIPTION
**Pull request by rjernst**
The update of the Azure SDK to 12.11.1 started using the netty dns
resolver. This reads /etc/hosts on nix machines. But we also need to
account for Windows machines, which have a similar hosts file.

closes #73539

### CODE REVIEW

**Comment by mark-vieira** [comment]
@elasticmachine run elasticsearch-ci/part-1-windows

**Comment by rjernst** [comment]
@elasticmachine run elasticsearch-ci/part-2-windows

**Comment by rjernst** [comment]
@elasticmachine run elasticsearch-ci/part-2-windows

**Comment by fcofdez** [comment]
It seems like the SecurityManager is still unhappy about the read permissions 🤔 @rjernst 
```
Caused by: java.security.AccessControlException: access denied ("java.io.FilePermission" "C:\Windows\system32\drivers\etc\hosts" "read")
```

**Comment by rjernst** [comment]
@elasticmachine run elasticsearch-ci/part-2-windows

**Comment by rjernst** [comment]
The Azure upgrade that necessitated this resolving is being reverted (#73837). Closing this PR as it is no longer necessary until Azure is upgraded again.

**Pull request closed without merging**
