### PR TITLE
[HLRC] change GET method to POST in Searchtemplate

### LINKED ISSUE #72073: searchTemplate method doing a GET instead of a POST
https://github.com/elastic/elasticsearch/blob/5f69ee3fbb5090539a49e71783f0ef436bbfff7a/client/rest-high-level/src/main/java/org/elasticsearch/client/RequestConverters.java#L457

Is it possible to modify searchTemplate to have it make a POST instead of a GET?
Our elastic is hosted in GCP. the load-balancer refuses all GET request with an entity which make this method unusable in our environnement. Using POST would fix this issue.

From what I've seen in https://github.com/elastic/elasticsearch/issues/28326 all method were previously migrated to using POST. It seems this one hasn't

### PR DESCRIPTION
**Pull request by chengyang14**
Fix #72073
Close #72397

### CODE REVIEW

**Comment by chengyang14** [comment]
@leehinman please help review this

**Comment by chengyang14** [comment]
@dakrone please help review this

**Comment by dakrone** [comment]
@elasticmachine ok to test

**Review by dakrone — APPROVED** [review]
LGTM, thanks @chengyang14

**Pull request merged**
