### PR TITLE
fix incorrect readonce field value of READONCE_CHECKSUM IOContext

### PR DESCRIPTION
**Pull request by asce0705**
The definition of `READONCE_CHECKSUM` IOContext in Store class is incorrect, whose readonce field value should be true to indicate a readonce IO context.

The definition in Elasticsearch Store class:
```java
public static final IOContext READONCE_CHECKSUM = new IOContext(IOContext.READONCE.context);
```

The IOContext constructor in lucene:
```java
public IOContext(Context context) {
    this(context, null);
}

private IOContext(Context context, MergeInfo mergeInfo) {
    assert context != Context.MERGE || mergeInfo != null : "MergeInfo must not be null if context is MERGE";
    assert context != Context.FLUSH : "Use IOContext(FlushInfo) to create a FLUSH IOContext";
    this.context = context;
    this.readOnce = false;
    this.mergeInfo = mergeInfo;
    this.flushInfo = null;
}
```

### CODE REVIEW

**Comment by asce0705** [comment]
@elasticmachine

**Comment by asce0705** [comment]
@elastic/es-distributed Would you please take a look at this PR, thanks.

**Comment by DaveCTurner** [comment]
@elasticmachine ok to test

**Review by DaveCTurner — APPROVED** [review]
I can't see any places in either Elasticsearch or Lucene where the value of the `readOnce` field affects behaviour so I suspect this doesn't really matter, but yes we should fix it at least so the `toString()` says the right thing.

**Comment by asce0705** [comment]
> I can't see any places in either Elasticsearch or Lucene where the value of the `readOnce` field affects behaviour so I suspect this doesn't really matter, but yes we should fix it at least so the `toString()` says the right thing.

Yes, currently this field is not used in any places in either Elasticsearch or Lucene. However, someone may implement the IndexStorePlugin and have their own lucene Directory implement. The lucene Directory's openInput method needs the IOContext, in which place the readonce value cares.

**Comment by DaveCTurner** [comment]
Yes, that's true (although I haven't heard of such implementations). In any case this LGTM but needs to pass CI before it can be merged. Would you merge latest master to trigger another CI run?

**Review by tlrx — APPROVED** [review]
LGTM 2

**Comment by asce0705** [comment]
@DaveCTurner Thanks David. I have merged the master and now the newly triggered CI has passed.

**Pull request merged**
