### PR TITLE
NETWORKING: MockTransportService Wait for Close

### LINKED ISSUE #33756: RemoteClusterConnectionTests#testCloseWhileConcurrentlyConnecting leaks a connection
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.6+multijob-unix-compatibility/os=oraclelinux/2/console failed as follows:

```
java.lang.AssertionError: still open connections: {{seed_node_1}{CslcNVg2RUmfUOjafi8V-g}{OCHf8nq9Q-afBlEmBTuW8A}{127.0.0.1}{127.0.0.1:10301}=[org.elasticsearch.test.transport.MockTransportService$6@3f3b53e]}
	at __randomizedtesting.SeedInfo.seed([E0882D34B487919C:E6C871A1A79BE13A]:0)
	at org.elasticsearch.test.transport.MockTransportService.doClose(MockTransportService.java:865)
	at org.elasticsearch.common.component.AbstractLifecycleComponent.close(AbstractLifecycleComponent.java:109)
	at org.elasticsearch.transport.RemoteClusterConnectionTests.testCloseWhileConcurrentlyConnecting(RemoteClusterConnectionTests.java:716)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1713)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:907)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:943)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:957)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:916)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:802)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:852)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:863)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.lang.Thread.run(Thread.java:748)
```

Similar failures occurred on other branches (although the logs are no longer accessible)

July 4th 2018: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+java-time+feature-branch-periodic/169/console

June 18th 2018: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+periodic/6511/console

The `REPRODUCE WITH` line does not reproduce this for me:

```
./gradlew :core:test \
  -Dtests.seed=E0882D34B487919C \
  -Dtests.class=org.elasticsearch.transport.RemoteClusterConnectionTests \
  -Dtests.method="testCloseWhileConcurrentlyConnecting" \
  -Dtests.security.manager=true \
  -Dtests.locale=de-LU \
  -Dtests.timezone=America/Argentina/Jujuy
```

### LINKED ISSUE #34990: MockTransportService throws AssertionError: still open connections
This is a failure I have seen recently on the `zen2` branch (quite rarely, and unable to reproduce on `master`). For instance on commit b01d321cfaf2906339f50e8e91528e73ec0a0d12 I ran this in a loop:

```
./gradlew :server:integTest -Dtests.class=org.elasticsearch.action.admin.indices.stats.IndicesStatsBlocksIT -Dtests.iters=200 -Dtests.failfast=true
```

On the 7th time round one of the tests failed with the following stack trace:

```
  2> REPRODUCE WITH: ./gradlew :server:integTest -Dtests.seed=B5E24AD11854BA9B -Dtests.class=org.elasticsearch.action.admin.indices.stats.IndicesStatsBlocksIT -Dtests.method="testIndicesStatsWithBlocks {seed=[B5E24AD11854BA9B:99DFE9CCD7C698F7]}" -Dtests.security.manager=true -Dtests.locale=ig-NG -Dtests.timezone=Africa/Freetown -Dcompiler.java=11 -Druntime.java=11
FAILURE 1.40s | IndicesStatsBlocksIT.testIndicesStatsWithBlocks {seed=[B5E24AD11854BA9B:99DFE9CCD7C698F7]} <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: still open connections: {{127.0.0.1:37253}{nNBmVQAAQACCxD28_____w}{127.0.0.1}{127.0.0.1:37253}=[org.elasticsearch.test.transport.StubbableTransport$WrappedConnection@702fbe9b]}
   >    at __randomizedtesting.SeedInfo.seed([B5E24AD11854BA9B:99DFE9CCD7C698F7]:0)
   >    at org.elasticsearch.test.transport.MockTransportService.doClose(MockTransportService.java:625)
   >    at org.elasticsearch.common.component.AbstractLifecycleComponent.close(AbstractLifecycleComponent.java:100)
   >    at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:103)
   >    at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:85)
   >    at org.elasticsearch.node.Node.close(Node.java:862)
   >    at org.elasticsearch.test.InternalTestCluster$NodeAndClient.closeNode(InternalTestCluster.java:916)
   >    at org.elasticsearch.test.InternalTestCluster$NodeAndClient.close(InternalTestCluster.java:993)
   >    at org.elasticsearch.core.internal.io.IOUtils.closeWhileHandlingException(IOUtils.java:145)
   >    at org.elasticsearch.test.InternalTestCluster.close(InternalTestCluster.java:810)
   >    at org.elasticsearch.test.ESIntegTestCase.afterInternal(ESIntegTestCase.java:587)
   >    at org.elasticsearch.test.ESIntegTestCase.cleanUpCluster(ESIntegTestCase.java:2195)
   >    at jdk.internal.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
   >    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   >    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
   >    at java.base/java.lang.Thread.run(Thread.java:834)
```

This seems to occur when nodes are shutting down - particularly when the master shuts down then the remaining nodes will attempt to elect a new master, which first involves reconnecting to each node (not strictly necessary, see below). The open connection in question is one of these probe connections, since the remote node's name is just its transport address `{127.0.0.1:37253}` and not its real name.

https://github.com/elastic/elasticsearch/blob/a127805b4a6c44741db36c1abf567945dc61e640/server/src/main/java/org/elasticsearch/discovery/HandshakingTransportAddressConnector.java#L72

As far as I can tell there is machinery in place to prevent this from happening so I don't think it's specifically a Zen2 issue; in Zen2 we create a bunch of new connections when a node shuts down, and Zen1 does not do this, which might be why this doesn't reproduce so easily on `master`.

@tbrooks8 my main question to you is whether you think this is a problem in the networking infrastructure or a problem with how we're using it in Zen2.

### PR DESCRIPTION
**Pull request by original-brownbear**
* Make `MockTransportService` wait `30s` for close listeners to run before failing the assertion
* Closes #34990 
* Closes #33756

### CODE REVIEW

**Review by Tim-Brooks — CHANGES_REQUESTED** [review]
Can we just do:

```
            try {
                ESTestCase.assertBusy(() -> {
                    assert openConnections.size() == 0 : "still open connections: " + openConnections;
                });
            } catch (AssertionFailure e) {
                throw e;
            } catch (Exception e) {
                throw new IOException(e);
            }
```

The `wait / notify` semantics are kind of tricky to handle (for example I think you should have the notify call be in a synchronized block). 

You could also add an `assertBusyUnchecked` the takes a `Runnable` opposed to a `CheckedRunnable` if you want to avoid the weird exception handling

**Comment by original-brownbear** [comment]
@tbrooks8 the `notifyAll` is inside the `synchronized block` :)

We would also need to do:

```java
                ESTestCase.assertBusy(() -> {
                    synchronized(openConnections) {
                        assert openConnections.size() == 0 : "still open connections: " + openConnections;
                    }
                });
```

here to release to lock on the `openConnections` between asserts.
=> seems a lot more intuitive to not needlessly busy poll here (and add more locking complication like this) when we can just wait here without polling in a completely deterministic fashion?

**Comment by DaveCTurner** [comment]
I am not 100% convinced that this is the right fix. #34990 seems to affect freshly-opened connections, which to me makes it feel like a race condition between opening connections and closing the transport down, and waiting for some arbitrary timeout makes me a little uneasy.

The synchronisation in `MockTransportService#openConnection` is quite weak and, in particular, looks like it allows for the connection to be closed (and the size of `openConnections` to be checked) before `addCloseListener` is called, and I think this explains the problem.

Would it be sufficient to call `connection.addCloseListener` under the same mutex as the one that protects the call to `openConnections.computeIfAbsent`?

**Comment by original-brownbear** [comment]
@DaveCTurner I think you're 100% right, this def. another possible race. Your suggested sounds just fine too => added it in https://github.com/elastic/elasticsearch/pull/35038/commits/7f5cd241c0eb5176bb4d2567d4449808e0f71f6d

**Comment by DaveCTurner** [comment]
With the extra synchronisation, do we need the wait/notify as well?

**Comment by original-brownbear** [comment]
@DaveCTurner yea because the close callback may be executed in a different thread and hence could run after the assertion if we don't wait for the map to empty.

**Comment by DaveCTurner** [comment]
Do you mean that the call to `super.doClose();` in `MockTransportService#doClose()` can return before all the connections have been fully closed? That sounds bad. I see this comment:

https://github.com/elastic/elasticsearch/blob/cf9aff954ef916aaf1bddea362bcbb91466e60a1/server/src/main/java/org/elasticsearch/transport/ConnectionManager.java#L206-L207

This doesn't look true - I can see a couple of places where we modify `connectedNodes` without protection from `closeLock`:

https://github.com/elastic/elasticsearch/blob/cf9aff954ef916aaf1bddea362bcbb91466e60a1/server/src/main/java/org/elasticsearch/transport/ConnectionManager.java#L131

https://github.com/elastic/elasticsearch/blob/cf9aff954ef916aaf1bddea362bcbb91466e60a1/server/src/main/java/org/elasticsearch/transport/ConnectionManager.java#L182

**Comment by original-brownbear** [comment]
@DaveCTurner no this is my bad (sorry for the confusion). I mixed up the connection and the channel close. The connection close callback is invoked in the same thread that invokes. `doClose()` => no need to wait for the channel list to empty and just synchronizing the connect itself should be fine.

Simplified the PR in fb843f5.
Also, will look into the issue you point out above (that shouldn't be relevant here though, since the connections are just a field managed by `MockTransportService` so as long as the callback and the close run in the same thread we're good I think).

**Review by DaveCTurner — APPROVED** [review]
LGTM but I'd like @tbrooks8's opinion too.

**Comment by original-brownbear** [comment]
@DaveCTurner I think the two concurrency spots in `ConnectionManager` are ok the way they are:

https://github.com/elastic/elasticsearch/blob/cf9aff954ef916aaf1bddea362bcbb91466e60a1/server/src/main/java/org/elasticsearch/transport/ConnectionManager.java#L109

gives us the close lock for https://github.com/elastic/elasticsearch/blob/cf9aff954ef916aaf1bddea362bcbb91466e60a1/server/src/main/java/org/elasticsearch/transport/ConnectionManager.java#L131


And for:

https://github.com/elastic/elasticsearch/blob/cf9aff954ef916aaf1bddea362bcbb91466e60a1/server/src/main/java/org/elasticsearch/transport/ConnectionManager.java#L182

we should be fine too. The iterator from a CHM should be consistent with concurrent removal from the CHM (`remove` one iterator should simply be a noop if the element was concurrently removed?).

**Comment by DaveCTurner** [comment]
I think the issue might just be that the comment is misleading, as comments often are. Both of the calls to `connectedNodes.remove()` look OK; there'd only be a problem if we were to concurrently _add_ a connected node if I'm reading this right. Could you fix the comment so it only talks about adding to `connectedNodes`?

This line isn't under a lock by the way, it's in a handler that may not run until the lock is released:

https://github.com/elastic/elasticsearch/blob/cf9aff954ef916aaf1bddea362bcbb91466e60a1/server/src/main/java/org/elasticsearch/transport/ConnectionManager.java#L131

**Comment by original-brownbear** [comment]
@DaveCTurner 

> This line isn't under a lock by the way, it's in a handler that may not run until the lock is released:

Sorry, you're right my eyes aren't so great today apparently :D

> Could you fix the comment so it only talks about adding to connectedNodes?

Fixed :)

**Comment by tbrooks8** [comment]
> The synchronisation in MockTransportService#openConnection is quite weak and, in particular, looks like it allows for the connection to be closed (and the size of openConnections to be checked) before addCloseListener is called, and I think this explains the problem.

Can someone explain this hypothesis before I review this?

I don't understand how this can lead to this issue. Even if the channel is closed before the listener added, the listener is still called. The listener is just executed by the thread that is adding the listener. 

So I guess my point is that the additional synchronization does not seem to add much here. I'm not opposed to it as this is just test code, I just want to make sure I understand the proposed issues at play here.

> Do you mean that the call to super.doClose(); in MockTransportService#doClose() can return before all the connections have been fully closed?

**YESish.** The assertions introduced in the `MockTransportService` only apply to **_unmanaged_** connections. These connections are not managed by the `ConnectionManager`. Now at a low-level killing the transport service kills event loops which kills all tcp connections. And there are listeners that then close the node connection (which is a collection of tcp connections). But this is a race with other places that could be closing the node connection. And whatever closes the node connection first wins and executes the listener. This is why some type of wait or assert busy is necessary as someone outside of the networking code might concurrently be closing this node connection. Also why we cannot make assumptions about which threads listeners are executed on.

As a separate note, I want to point out that discussions about the `ConnectionManager` are relatively orthogonal to the issues at play here as these assertions apply to unmanaged connections.

**Review by Tim-Brooks — APPROVED** [review]
Okay. I think we are all agreement about the potential problems here and how the PR addresses them.

LGTM

**Comment by original-brownbear** [comment]
@tbrooks8 thanks!

**Pull request merged**
