### PR TITLE
Fix typo in message for variable setup ES_MAX_MEM

### PR DESCRIPTION
**Pull request by radoondas**
Small typo fix in startup script.

### CODE REVIEW

**Comment by nik9000** [comment]
LGTM

**Comment by jasontedor** [comment]
Thanks. The Windows startup script has half of this copy-paste error, so I pushed f1fb6a37c0e348ef0898782d58acf989f2b5c9be.

I'm marking you as eligible for the [Pioneer Program](https://www.elastic.co/blog/elastic-pioneer-program).

**Comment by radoondas** [comment]
@jasontedor Thanks! Thah made my day. :)

**Comment by nik9000** [comment]
> @jasontedor Thanks! Thah made my day. :)

Thanks for fixing it!

**Pull request merged**
