### PR TITLE
Relax limit on max string size

### LINKED ISSUE #96036: Pre-release 8.8.0 cannot work with string fields longer than 5000000 characters
#95641 upgraded Jackson to version 2.15.0.  One of the fixes in this is https://github.com/FasterXML/jackson-core/issues/863.  This new limit of 5000000 characters for a string field then applies to strings in Elasticsearch documents.

To reproduce:

1. `./gradlew run`
2. Download [`big_a.zip`](https://github.com/elastic/elasticsearch/files/11453951/big_a.zip)
3. `unzip big_a.zip`
4. `curl -u elastic:password http://localhost:9200/my-index/_doc/1 -X PUT -d @big_a.json -H 'Content-Type: application/json'`

The response is:

```
{"error":{"root_cause":[{"type":"document_parsing_exception","reason":"[1:20] failed to parse: String length (5043368) exceeds the maximum length (5000000)"}],"type":"document_parsing_exception","reason":"[1:20] failed to parse: String length (5043368) exceeds the maximum length (5000000)","caused_by":{"type":"stream_constraints_exception","reason":"String length (5043368) exceeds the maximum length (5000000)"}},"status":400}
```

I think this is a blocker for release of 8.8.0 because people will have indexed docs in older versions that have strings longer than 5000000 characters, and they won't be able to work with them in 8.8.0 unless we do something about this problem.

### PR DESCRIPTION
**Pull request by rjernst**
Jackson 2.15 introduced a (rough) maximum limit on string length. This commit relaxes that limit to its maximum size, leaving document size constraints to other existing limits in the system. We can revisit whether string length within a document should be independently constrained later.

Fixes #96036

### CODE REVIEW

**Comment by rjernst** [comment]
I've marked this as a non-issue because it will target 8.8.0 where this regression was introduced.

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Comment by dadoonet** [comment]
I'm wondering if this limit is taken into account for the ingest attachment plugin.

According to the discussion here: https://discuss.elastic.co/t/345687 it seems that Jackson is still using its default limit of 5mb (with jackson 2.15.0):

> String length (5046272) exceeds the maximum length (5000000)" appears

Do we need to also modify some code in the ingest pipeline plugin?

BTW, Jackson has modified this limit to 20mb in 2.15.1. May be we should upgrade Jackson? 2.15.3 seems to be the latest stable version...

**Comment by stu-elastic** [comment]
Hi, @dadoonet please cut an issue if this remains a problem.

It's hard for us to track issues if they exist as comments on a PR several months after it's been merged.

**Comment by dadoonet** [comment]
@stu-elastic Sure. It was more like a question actually to see if we need to open an issue or not. But as soon as I have some spare time, I can try to create a reproduction script, test it against the latest release and create an issue if needed.

**Comment by Korzi** [comment]
Was it backported to Elasticsearch 7 as well? Could you please backport it, please?

**Pull request merged**
