### PR TITLE
[DOCS] Document analysis/mapping response for  cluster stats API

### LINKED ISSUE #55030: [DOCS] Document analysis/mapping response in cluster stats API docs
#51260 moved usage information about field types and analysis components to the `_cluster/stats` API.

We should document this information in the response section of the cluster stats API docs.

### PR DESCRIPTION
**Pull request by jrodewig**
PR #51260 moved usage statistics for mapping field datatypes and analysis
components to the `_cluster/stats` API.

This documents those stats in the response section of the cluster stats
API docs.

Closes #55030

### CODE REVIEW

**Comment by danhermann** [comment]
@elasticmachine update branch

**Review by danhermann — APPROVED** [review]
LGTM

**Comment by jrodewig** [comment]
Thanks @danhermann

**Comment by jrodewig** [comment]
### Backport commits
master 399bc86
7.x f87a3f0c48f
7.7 5d9351431ea

**Pull request merged**
