### PR TITLE
Provide an upgrade path from pre 6.2 to oss

### PR DESCRIPTION
**Pull request by alpar-t**
It's not currently possible to upgrade from pre 6.3 `elasticsearch` package to `elaticsearch-oss` as the two are marked to unconditionally conflict. 
This PR adds this missing upgrade path by leveraging the possibility to express version conditioned relationships in both deb and rpm:

- `elasticsearch` and `elasticsearch-oss` only conflicts in versions including and after `6.3` 
- `elasticsearch-oss` and `elasticsearch` both are marked to replace `elaticsearch <6.3`

These two relations make the upgrade from `elasticsearch < 6.3` to both the oss and default distribution without allowing switching from one to the other ` >= 6.3`.

**Unfortunately it doesn't quite work.**

When going from `elasticsearch < 6.3` to `elasticsearch-oss` the scripts are ran by rpm in this order: `%pre (new) %post (new) %preun (old) %postun (old) %posttrans (new)`. 
On other upgrades `%prerun` and `%postun` detect that's an upgrade and don't  do anything, but rpm doesn't flag this as an upgrade and the directories, users and groups are blown away and the services stopped. The only way to fix this is to restore what can be restored in `%posttrans`, or  save some state between the scripts to detect that it's really an upgrade, but that would require fixing in a patch and we would support upgrades only from that patch. 

I think that given this additional information we should reconsider if we want to pursue this further. The PR can't be merged as it is, it just for exemplification purposes and discussion. 

```
centos-7:~$ sudo rpm -i https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.0.rpm
centos-7:~$ rpm -i  /elasticsearch/distribution/packages/oss-rpm/build/distributions/elasticsearch-oss-7.0.0-SNAPSHOT.rpm
error: Failed dependencies:
	elasticsearch < 6.3 is obsoleted by elasticsearch-oss-0:7.0.0_SNAPSHOT-1.noarch
centos-7:~$ rpm -i  /elasticsearch/distribution/packages/oss-rpm/build/distributions/elasticsearch-oss-7.0.0-SNAPSHOT.rpm
error: Failed dependencies:
	elasticsearch < 6.3 is obsoleted by elasticsearch-oss-0:7.0.0_SNAPSHOT-1.noarch
centos-7:~$ sudo rpm -U  /elasticsearch/distribution/packages/oss-rpm/build/distributions/elasticsearch-oss-7.0.0-SNAPSHOT.rpm
 sudo systemctl daemon-reload
 sudo systemctl enable elasticsearch.service
 sudo systemctl start elasticsearch.service
centos-7:~$ sudo rpm -i  /elasticsearch/distribution/packages/rpm/build/distributions/elasticsearch-7.0.0-SNAPSHOT.rpm
error: Failed dependencies:
	elasticsearch-oss conflicts with elasticsearch-0:7.0.0_SNAPSHOT-1.noarch
	elasticsearch >= 6.3 conflicts with (installed) elasticsearch-oss-0:7.0.0_SNAPSHOT-1.noarch
centos-7:~$ sudo rpm -U  /elasticsearch/distribution/packages/rpm/build/distributions/elasticsearch-7.0.0-SNAPSHOT.rpm
error: Failed dependencies:
	elasticsearch-oss conflicts with elasticsearch-0:7.0.0_SNAPSHOT-1.noarch
	elasticsearch >= 6.3 conflicts with (installed) elasticsearch-oss-0:7.0.0_SNAPSHOT-1.noarch
```

```
ubuntu-1804:~$ wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.0.deb
ubuntu-1804:~$ sudo dpkg -i elasticsearch-5.6.0.deb
Selecting previously unselected package elasticsearch.
(Reading database ... 141015 files and directories currently installed.)
Preparing to unpack elasticsearch-5.6.0.deb ...
Creating elasticsearch group... OK
Creating elasticsearch user... OK
Unpacking elasticsearch (5.6.0) ...
Replaced by files in installed package elasticsearch-oss (7.0.0~SNAPSHOT) ...
Setting up elasticsearch (5.6.0) ...
Processing triggers for ureadahead (0.100.0-20) ...
Processing triggers for systemd (237-3ubuntu10.3) ...

ubuntu-1804:~$ sudo  dpkg -i /elasticsearch/distribution/packages/oss-deb/build/distributions/elasticsearch-oss-7.0.0-SNAPSHOT.deb
(Reading database ... 141082 files and directories currently installed.)
Preparing to unpack .../elasticsearch-oss-7.0.0-SNAPSHOT.deb ...
/usr/bin/java
Removing old lib folder
Unpacking elasticsearch-oss (7.0.0~SNAPSHOT) over (7.0.0~SNAPSHOT) ...
Setting up elasticsearch-oss (7.0.0~SNAPSHOT) ...
Created elasticsearch keystore in /etc/elasticsearch
Processing triggers for ureadahead (0.100.0-20) ...
Processing triggers for systemd (237-3ubuntu10.3) ...
```

As far as testing is concerned, before this change we tested upgrade with `bats` for versions starting with `6.3` only for `elasticsearch-oss` and skip them otherwise. 
With this change we cover the full range for both distribution types, including going from pre `6.3` to any of the current distributions.

Relates to #36142

### CODE REVIEW

**Comment by rjernst** [comment]
Thanks for this investigation so far @atorok. I think we should revisit the discussion on this as you suggested.

If this does go in, I think the upgrade tests should first be converted to the java packaging tests, rather than extending the bats based tests which need to go away.

**Comment by dliappis** [comment]
Had a follow up discussion with @atorok and @danielmitterdorfer and using some hooks in the pre/post scripts of the new package and prerm/postrm of an old 6.2.0 package that I injected in both (via `rpmrebuild -ep`) we observed that unfortunately $1 doesn't show the expected values for an upgrade (see the table here: https://fedoraproject.org/wiki/Packaging:Scriptlets) but instead considers it a normal installation. So the [obsoletes line](https://github.com/elastic/elasticsearch/pull/36940/files#diff-345cb010dae37abd8b7ab358caa7c0b5R250) didn't seem to do what we expected for rpm according [to the docs](http://rpm.org/user_doc/dependencies.html):

<details><summary>Output showing states of $1 during upgrade from 6.2 -> 7.0.0 build with this PR</summary>

```
centos-7:~$ sudo rpm -ivh ./elasticsearch-6.2.0-1.noarch.rpm
Preparing...                          ################################# [100%]
Creating elasticsearch group... OK
Creating elasticsearch user... OK
Updating / installing...
   1:elasticsearch-0:6.2.0-1          ################################# [100%]
### NOT starting on installation, please execute the following statements to configure elasticsearch service to start automatically using systemd
 sudo systemctl daemon-reload
 sudo systemctl enable elasticsearch.service
### You can start elasticsearch service by executing
 sudo systemctl start elasticsearch.service
centos-7:~$ sudo rpm -Uvh ./elasticsearch-oss-7.0.0_SNAPSHOT-1.noarch.rpm
Preparing...                          ################################# [100%]
I am in the PRE script of es-oss-7.0.0 and dollar 1 is 1
Updating / installing...
   1:elasticsearch-oss-0:7.0.0_SNAPSHO################################# [ 50%]
I am in the PRE script of es-oss-7.0.0 and dollar 1 is 1
### NOT starting on installation, please execute the following statements to configure elasticsearch service to start automatically using systemd
 sudo systemctl daemon-reload
 sudo systemctl enable elasticsearch.service
### You can start elasticsearch service by executing
 sudo systemctl start elasticsearch.service
I am in PREUN of es 6.2.0 and dollar 1 = 0
Stopping elasticsearch service... OK
Cleaning up / removing...
   2:elasticsearch-0:6.2.0-1          ################################# [100%]
I am in POSTUN  of es 6.2.0 and dollar 1 = 0
Deleting log directory... OK
Deleting plugins directory... OK
Deleting PID directory... OK
Created elasticsearch keystore in /etc/elasticsearch
chown: invalid group: ‘root:elasticsearch’
```
</details>

One alternative that came up is the use of `--nopreun --postun` (or `--noscripts`) to skip the removal tasks like the ones in the current [postrm](https://github.com/elastic/elasticsearch/blob/26cb7466ef93c8b915741a379cb614a3600a5226/distribution/packages/src/common/scripts/postrm#L44-L85).

Unfortunately this will result in `.rpmsave` files for user modified conf files under `/etc/elasticsearch`, so our upgrade instructions need to cover this (e.g. backup `/etc/elasticsearch` first).

Additionally if the user attempts to upgrade a package generated by this PR using `rpm -U newpackage` (without reading the manual steps for rpm), they could end up losing logs so some defensive logic needs to be implemented in the pre/post scripts to e.g. rename the log dir so that it doesn't get wiped away.

**Comment by atorok** [comment]
With the last commit I pushed this works, but the output is very messy as it reflects the scripts thinking this is an install.
```
sudo rpm -U  /elasticsearch/distribution/packages/oss-rpm/build/distributions/elasticsearch-oss-7.0.0-SNAPSHOT.rpm
### NOT starting on installation, please execute the following statements to configure elasticsearch service to start automatically using systemd
 sudo systemctl daemon-reload
 sudo systemctl enable elasticsearch.service
### You can start elasticsearch service by executing
 sudo systemctl start elasticsearch.service
Stopping elasticsearch service... OK
Created elasticsearch keystore in /etc/elasticsearch
Created symlink from /etc/systemd/system/multi-user.target.wants/elasticsearch.service to /usr/lib/systemd/system/elasticsearch.service.
centos-7:~$ systemctl status elasticsearch
● elasticsearch.service - Elasticsearch
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2019-01-23 17:45:49 UTC; 6s ago
     Docs: http://www.elastic.co
 Main PID: 16208 (java)
   CGroup: /system.slice/elasticsearch.service
           └─16208 /bin/java -Xms1g -Xmx1g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -Des.networkaddress.cache.ttl=60 -Des.networkaddress.cache.negative.ttl=10 -XX:+AlwaysPreTouch -Xss1m -Djava.awt.headless=true -Dfile.encoding=UTF-8 -...

Jan 23 17:45:49 localhost.localdomain systemd[1]: Started Elasticsearch.

```

Given how messy this is, the complexity it adds, and the misleading output, I would rather drop this PR and close the associated issue as something we won't support. I don't think we would want to support this on Debian base distributions only.  @rjernst @jasontedor @dliappis do you agree ? If this turns out to be a major complaint we could add a test to show and test the process of removing the old RPM and installing the oss one manually.

**Comment by dliappis** [comment]
@atorok +1 from me too. The working solution is hacky by definition (and hacks are so painful to maintain, aren't they?). Only supporting this upgrade path for deb will also contribute to confusion.

also cc @danielmitterdorfer

**Pull request closed without merging**
