### PR TITLE
Build: Enable testing without magic comments

### PR DESCRIPTION
**Pull request by nik9000**
Previously we only turned on tests if we saw either `// CONSOLE` or
`// TEST`. These magic comments are difficult for the docs build to deal
with so it has moved away from using them where possible. We should
catch up. This adds another trigger to enable testing: marking a snippet
with the `console` language. It looks like this:

```
[source,console]
----
GET /
----
```

This saves a line which is nice, I guess. But it is more important to me
that this is consistent with the way the docs build works now.

Similarly this enables response testing when you mark a snippet with the
language `console-result`. That looks like:
```
[source,console-result]
----
{
  "result": "0.1"
}
----
```

`// TESTRESPONSE` is still available for situations like `// TEST`: when
the response isn't *in* the console-result language (like `_cat`) or
when you want to perform substitutions on the generated test.

Should unblock #46159.

### CODE REVIEW

**Review by jrodewig — APPROVED** [review]
LGTM.

Tested this locally with the changes from #46159 and the gradle build was successful.

**Review by rjernst — APPROVED** [review]
LGTM. Can we eventually get rid of `// CONSOLE` if this is a substitute rather than supporting both?

**Comment by jrodewig** [comment]
@rjernst  The docs team will help with that as part of #46189.

**Comment by nik9000** [comment]
@elasticmachine, run elasticsearch-ci/2

**Pull request merged**
