### PR TITLE
[DOCS] Streamline Docker Compose docs

### PR DESCRIPTION
**Pull request by jrodewig**
**Problem**:
The [Docker Compose docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-compose-file) are overly long. They currently display the entire length of related `.env` and `docker-compose.yml` files.

**Solution**:
- Rewrite the Docker Compose docs as a procedural with ordered steps.
- Provide download links for the `.env` and `docker-compose.yml` files rather than display them.
- Move info about pulling and verifying Docker images into the [Run Elasticsearch in Docker docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-dev-mode). These steps don't apply to the Docker Compose docs.

Closes https://github.com/elastic/platform-docs-team/issues/186
Depends on https://github.com/elastic/enterprise-search-pubs/pull/3788

### CODE REVIEW

**Comment by jrodewig** [comment]
@elasticsearchmachine run elasticsearch-ci/docs

**Review by abdonpijpelink — APPROVED** [review]
LGTM

**Comment by jrodewig** [comment]
Thanks @abdonpijpelink!

**Comment by jrodewig** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.10|[](https://github.com/elastic/elasticsearch/pull/99429)|
|✅|8.9|[](https://github.com/elastic/elasticsearch/pull/99430)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
