### PR TITLE
Fix misspelling of "multiple"

### PR DESCRIPTION
**Pull request by snikch**

### CODE REVIEW

**Comment by tvernum** [comment]
Thanks @snikch.

Could you possibly provide the patch against the `6.x` branch instead of `6.1`? 
We we merge it, we will backport it to `6.1` and `6.0`

**Comment by tvernum** [comment]
@elasticmachine ok to test

**Comment by snikch** [comment]
@tvernum yep, done.

**Comment by tvernum** [comment]
Thanks!

**Comment by tvernum** [comment]
Thanks @snikch.
That fix has gone live in the 6.1 docs, and should be pushed to 6.0 soon.
https://www.elastic.co/guide/en/elasticsearch/reference/6.1/breaking_60_rest_changes.html#_indices_information_apis

**Pull request merged**
