### PR TITLE
Update template v2 api rest spec

### PR DESCRIPTION
**Pull request by andreidan**
This removed the specification of `order` as it is not a parameter of the
v2 put template api (the priority is the equivalent of `order` and is
defined in the body) and add a bit of description for the `cause` parameter
(which is currently used as a cluster update task tracking)

Relates to #53101

### CODE REVIEW

**Comment by andreidan** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by andreidan** [comment]
@elasticmahcine update branch

**Review by dakrone — APPROVED** [review]
LGTM, thanks for fixing this

**Comment by andreidan** [comment]
@elasticmachine update branch

**Pull request merged**
