### PR TITLE
Add runtime geo_point distance_feature query

### LINKED ISSUE #67910: Geo point runtime field does not support distance feature query
When defining a geo_point field as a runtime field, distance feature query returns an error. The same query works fine when the field is defined as an indexed field.

```
curl -XPUT -HContent-Type:application/json -u elastic:password 'localhost:9200/test?pretty' -d'{
  "mappings" : {
    "runtime" : {
        "location" : {
          "type" : "geo_point"
        }
    }
  }
}
'

curl -XPOST -HContent-Type:application/json -u elastic:password 'localhost:9200/test/_doc/1?pretty&refresh=wait_for' -d'{
  "location": [-71.34, 41.14]
}
'

curl -X POST "localhost:9200/test/_search?pretty" -u elastic-admin:elastic-password -H 'Content-Type: application/json' -d'
{
  "query" : {
    "distance_feature" : {
      "field" : "location",
      "pivot" : "1km", 
      "origin" : [-71.35, 41.12]
    }
  }
}
'

{
  "error" : {
    "root_cause" : [
      {
        "type" : "query_shard_exception",
        "reason" : "failed to create query: Illegal data type of [geo_point]![distance_feature] query can only be run on a date, date_nanos or geo_point field type!",
        "index_uuid" : "VP81kfRlRoS7J5ysKA-uig",
        "index" : "test"
      }
    ],
    "type" : "search_phase_execution_exception",
    "reason" : "all shards failed",
    "phase" : "query",
    "grouped" : true,
    "failed_shards" : [
      {
        "shard" : 0,
        "index" : "test",
        "node" : "0kaawQwuTqWd9pnLFpih_w",
        "reason" : {
          "type" : "query_shard_exception",
          "reason" : "failed to create query: Illegal data type of [geo_point]![distance_feature] query can only be run on a date, date_nanos or geo_point field type!",
          "index_uuid" : "VP81kfRlRoS7J5ysKA-uig",
          "index" : "test",
          "caused_by" : {
            "type" : "illegal_argument_exception",
            "reason" : "Illegal data type of [geo_point]![distance_feature] query can only be run on a date, date_nanos or geo_point field type!"
          }
        }
      }
    ]
  },
  "status" : 400
}
```

### PR DESCRIPTION
**Pull request by iverase**
Add support for distance_feature query for runtime geo_point field. This was an oversight when initially added the field.

closes #67910

### CODE REVIEW

**Review by javanna — COMMENTED** [review]
thanks @iverase ! can you remove the related entry from the x-pack/runtime-fields/qa/build.gradle exclusions?

**Review by romseygeek — APPROVED** [review]
LGTM, thanks @iverase 

I wonder if we need to note somewhere that distance feature queries against runtime fields can't make use of hit skipping because there's no index to read max values from? Or is it obvious enough that a runtime field is slow?

**Comment by iverase** [comment]
My idea is that it is assume users should know that runtime fields are slower than indexed fields.

Do you think we should backport this to 7.11?

**Comment by javanna** [comment]
+1 on backporting as it is a bugfix, maybe we would like to hold off until 7.11 is released so it makes it into 7.11.1 ?

**Comment by iverase** [comment]
I hold off backporting to 7.11 for now

**Pull request merged**
