### PR TITLE
Restructure ES|QL docs

### PR DESCRIPTION
**Pull request by abdonpijpelink**
Restructures the ES|QL documentation, modelled after the SQL and EQL docs.

- Moves commands, functions, and operator to one section, with an [overview page](https://elasticsearch_100806.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/esql-commands-functions-operators.html) that lists all of them. Instead of having each command/function on a separate page, they're now listed on a single page per category.
- Adds [reference docs for the query API](https://elasticsearch_100806.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/esql-query-api.html) and an [overview of the API](https://elasticsearch_100806.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/esql-rest.html).
- Breaks out "[Limitations](https://elasticsearch_100806.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/esql-limitations.html)" into its own page.
- Moves syntax, multivalued fields and metadata fields pages under a "[Language](https://elasticsearch_100806.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/esql-language.html)" page.
- Adds placeholders for "Getting started" and "Using ES|QL in Kibana" pages.
- Proposes a standard layout for commands and functions, implemented in this PR for [ACOS](https://elasticsearch_100806.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/esql-math-functions.html#esql-acos), [CASE](https://elasticsearch_100806.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/esql-conditional-functions-and-expressions.html#esql-case), and [DATE_PARSE](https://elasticsearch_100806.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/esql-date-time-functions.html#esql-date_parse).

**Notes for reviewers:**

This PR changes a lot of files. Most changes are trivial, but please take a look at:

- Is the [REST API reference](https://elasticsearch_100806.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/esql-query-api.html) and the [overview of the API](https://elasticsearch_100806.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/esql-rest.html) complete/correct?
- Is [the categorization of functions and operators](https://elasticsearch_100806.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/esql-commands-functions-operators.html) correct? For example, I wasn't sure how to categorize `AUTO_BUCKET`, and I've put it under "Date-time functions".

### CODE REVIEW

**Comment by abdonpijpelink** [comment]
@elasticmachine test this please

**Comment by abdonpijpelink** [comment]
@elasticmachine test this please

**Comment by abdonpijpelink** [comment]
@elasticmachine merge upstream

**Review by abatsakis — APPROVED** [review]
I don't like the "ESQL Language" section title, but I can't think of something better now

**Review by costin — APPROVED** [review]
LGTM.
The structure misses a page on security and the impact it has on the data the users sees.
There is ongoing work around security and enrich that needs to be incorporated (see the work from Nhat).

**Comment by abdonpijpelink** [comment]
I will follow up with a security page (it's an item on the [meta issue](https://github.com/elastic/elasticsearch/issues/99072))

**Pull request merged**
