### PR TITLE
Remove legacy IndexResolver

### PR DESCRIPTION
**Pull request by dnhatn**
Currently, we are using the legacy IndexResolver alongside the updated version to compare their outputs. While this approach helps in bug detection, it adds to the maintenance burden, particularly when adding new features to the field-caps API or the index resolver. This change removes the legacy IndexResolver from the ESQL codebase.

### CODE REVIEW

**Review by nik9000 — APPROVED** [review]
I think now's probably the right time for this. @astefan probably should double check me on this one. @craigtaverner will likely see some conflicts here.

**Review by astefan — APPROVED** [review]
LGTM

**Review by bpintea — APPROVED** [review]
Some of the functionality might need to be brought back (like `resolveAsMergedMapping()`, `RemoteClusterResolver`) if we'll want more extensive `SHOW` support (a la #109815), but we can address that later.

**Comment by dnhatn** [comment]
> Some of the functionality might need to be brought back (like resolveAsMergedMapping(), RemoteClusterResolver) if we'll want more extensive SHOW support (a la #109815), but we can address that later.

Yes, Let's add them back to the new IndexResolver later.

Thanks, everyone, for the quick review!

**Pull request merged**
