### PR TITLE
Fail fast when executing master level write operations via a tribe node

### LINKED ISSUE #13290: Fail quick when executing master level write operations via a tribe node
If a master level write operation is executed via a tribe node then we should fail quick with a descriptive error instead of waiting for the master timeout the expire (1m).

It is clearly documented that master level write operations are not allowed to be executed via a tribe node, but failing how we do currently is not super clear.

Also when indexing into an index that does't exist yet an error is returned when the timeout has expired, which isn't really obvious, especially when you think the index does exist.

### PR DESCRIPTION
**Pull request by ywelsch**
Currently, executing master level write operations against a tribe node leads to MasterNotDiscoveredException after a 1 minute timeout. This PR adds a new mode to TransportMasterNodeAction to fail fast if the action does not specify to always execute locally.

Closes #13290

### CODE REVIEW

**Comment by ywelsch** [comment]
@martijnvg can you have a look?

**Comment by bleskes** [comment]
I looked at this and I like the change from a technical perspective but the error message we will give the user is very cryptic. Another potential change is to check block on the coordinating node as well as on the master  (like we do in replication action). This will cause non-retryable blocks to fail immediately (like the blocks the tribe node adds).

**Comment by dakrone** [comment]
ping @ywelsch, this is a little stale, is it still applicable?

**Comment by ywelsch** [comment]
Opened #20779 instead

**Pull request closed without merging**
