### PR TITLE
Restrict createClassLoader to modules

### PR DESCRIPTION
**Pull request by rjernst**
Creating classloaders is not something plugins really need to do. It is
only necessary for cases of loading dynamic code, which we do within
painless. This commit restricts allowing this permission to modules.

### CODE REVIEW

**Comment by pierre-ernst** [comment]
Moving forward (no backward compatibility), I was wondering if we could de-couple the SM policy file from the actual code:

**Comment by rjernst** [comment]
@pierre-ernst Do you mean the system level policy file?

**Comment by rjernst** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Review by jaymode — APPROVED** [review]
LGTM

**Comment by mark-vieira** [comment]
@elasticmachine update branch

**Comment by nathancday** [comment]
hi @jakelandis wondering if you could provide an guidance on how we could work around this for the ES-LTR plugin (linked issue) as it is blocking the v8.0 release. Looks like ES internal is still using this and for the LTR plugin case we need to compile queries somehow to populate a model's features.

**Comment by grcevski** [comment]
Hi @nathancday, we took a look at the ES-LTR plugin and I have few questions:

- Is the `createClassLoader` permission only needed to be able to invoke the JavascriptCompiler of lucene-expressions?
- If that's the use case, if we were to provide a mechanism to do this from our ScriptService, would that work for you? The only thing standing in the way of being able to do this at the moment, is that we don't support arbitrary ScriptContext's for expressions, but only for painless scripts.
- It also seems like ES-LTR touches a lot of the plugin functionality we provide at the moment, meaning we likely break your code all the time as we change the internals. We are working on creating a stable plugin API, starting with the analysis plugin type, so it would be great to get some feedback from you on the developer experience. Would you be open to discussions on this?

**Comment by nathancday** [comment]
Thanks @grcevski I'm looping my colleague @worleydl in who is closer to the permission changes we'd need.

**Comment by worleydl** [comment]
@grcevski
 
> * Is the `createClassLoader` permission only needed to be able to invoke the JavascriptCompiler of lucene-expressions?

Yes, it's tapped into via our Derived features and the TermStatQuery.

> * If that's the use case, if we were to provide a mechanism to do this from our ScriptService, would that work for you? The only thing standing in the way of being able to do this at the moment, is that we don't support arbitrary ScriptContext's for expressions, but only for painless scripts.

Ideally we want to support both Lucene Expressions and Painless.  I think we can make things work with Painless only but that may come with a slight performance hit.

> * It also seems like ES-LTR touches a lot of the plugin functionality we provide at the moment, meaning we likely break your code all the time as we change the internals. We are working on creating a stable plugin API, starting with the analysis plugin type, so it would be great to get some feedback from you on the developer experience. Would you be open to discussions on this?

We've been running into breaking changes but this permissions change has been the only "show-stopper".  Sometimes it can be difficult to grok the full set of changes with each release.  We often work back from the commit log but a changelog specific to plugins would be nice.  We'd definitely be open to discussions around this.

**Comment by grcevski** [comment]
Thanks @nathancday and @worleydl. It would be good to see what the overhead of painless will be if possible. We also think there will be some performance regression, but if it's not hard to try that would be great.

I'm guessing this PR here https://github.com/o19s/elasticsearch-learning-to-rank/pull/428 is the base for the 8.0 work? We want to take a look to see what it would take to prototype exposing support for Lucene expressions directly, just to see what that would look like and if it's something we can add.

**Comment by worleydl** [comment]
Hi @grcevski.  Yes that is the correct PR, it's ready to go other than the permissions issue.  Thanks for looking into this and please let us know if you need further information from our end.

**Comment by peterbengkui** [comment]
@grcevski follow-up here as active users of the LTR plugin. Is there any particular reason why `classloaders` shouldn't be permitted to plugins? 

As users, we feel like being able to customize the tooling could be a huge benefit of embracing open source technologies (o/w, we could have gone with Google/Bing). From our experience, `painless scripts` may not always be the best choice to support all use cases (CI/CD or testing, to name a few).

**Comment by grcevski** [comment]
Thanks for the feedback @peterbengkui, we understand. The reason we limited the use of create class loader permission is that class loader generated classes can in general circumvent the security manager, and even turn it off completely, with well crafted code. We are looking for ways we can re-enable this functionality.

**Comment by grcevski** [comment]
Hi @nathancday and @worleydl, we are setting up an external plugin developer Slack channel for high bandwidth collaboration, if you would like to be included please send me your email addresses at my email address `(My first Name)(dot)(My last name)@elastic.co`. After that point you should expect a Slack channel invite. Thanks!

**Comment by and-kul** [comment]
Hi @grcevski
Did you manage to find a way?

Features in 8.4 release looks really cool, but we still cannot upgrade from 7.x versions, because LTR plugin is essential for us

**Comment by peterbengkui** [comment]
@grcevski fwiw the `LTR` plugin is among the most widely used plugins on ES, a reason for many to switch from `solr` to `ES` in the first place. Unfortunately, this is a huge deal-breaker for many to upgrade, plus a substantial risk factor for us to plan our search strategies around `ES`. 

What is more, the change is also a deal breaker for many others who have developed plugins on their own. 

Hope y'all could consider it seriously and provide a resolution as soon as possible.

Thanks in advance.

**Comment by grcevski** [comment]
I believe we should be able to put out a PR next week to enable LTR again. The main struggle has been with enabling the integration tests to work the same way. If we can't figure out that piece by next week, we'll at least put out the code that should enable LTR to work.

**Comment by softwaredoug** [comment]
Awesome work @grcevski ! The combination of the LTR plugin plus the vector search features are going to be amazing 🚀

**Comment by and-kul** [comment]
Hi @grcevski 
Are there any updates on this?

**Comment by grcevski** [comment]
Yes, we are working on a change to support what LTR needed here: https://github.com/elastic/elasticsearch/pull/89895. The related LTR plugin branch matching the PR can be found here: https://github.com/o19s/elasticsearch-learning-to-rank/pull/437.

**Pull request merged**
