### PR TITLE
[DOCS] Add `?human` query param in ILM explain API docs

### PR DESCRIPTION
**Pull request by nielsbauman**
The ILM `_explain` API example responses included human-readable (time) fields, but the example URL didn't actually return those human-readable fields (only the raw fields).

### CODE REVIEW

**Review by DaveCTurner — CHANGES_REQUESTED** [review]
I think these fields were already there in the output if you specified the [`?human` query parameter](https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#_human_readable_output), but by default we don't emit human-readable fields. That's the behaviour we want, I don't think we should always output them.

**Comment by nielsbauman** [comment]
> I think these fields were already there in the output if you specified the [`?human` query parameter](https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#_human_readable_output), but by default we don't emit human-readable fields. That's the behaviour we want, I don't think we should always output them.

Ah that explains it; I was confused by [this](https://github.com/nielsbauman/elasticsearch/blob/10ad51a8f1870325d2c834434a584ba568c47424/libs/x-content/src/main/java/org/elasticsearch/xcontent/XContentBuilder.java#L819-L819) block, but now I get the purpose of it. 

What is the convention regarding docs? Do we put the human-readable fields in the API example responses or not? I'd argue not to, as they're not included by default.

**Comment by DaveCTurner** [comment]
In the docs you could reasonably change `GET my-index-000001/_ilm/explain` to `GET my-index-000001/_ilm/explain?human`. I think that'd be a good change, it'd push users towards adding the `?human` parameter here as a matter of course.

**Review by DaveCTurner — APPROVED** [review]
LGTM, although please update the description to be a good commit message before merging. The edit history is available in Github, there's no real need to have anything but the final state in the description, but if you want to do so then it's better to add a comment.

**Review by andreidan — APPROVED** [review]
LGTM, thanks for fixing this Niels !

**Pull request merged**
