### PR TITLE
Test date histogram aggregations using different date field types

### PR DESCRIPTION
**Pull request by salvatore-campagna**
As a result of closing issue #75509 here we test data histogram 
aggregations including auto date histograms and composite aggregations,
running the aggregation on two different indices having the same field but
with different date type.

### CODE REVIEW

**Comment by salvatore-campagna** [comment]
@elasticsearchmachine run elasticsearch-ci/bwc

**Comment by salvatore-campagna** [comment]
@elasticsearchmachine run elasticsearch-ci/bwc

**Comment by salvatore-campagna** [comment]
@elasticsearchmachine update branch

**Review by nik9000 — APPROVED** [review]

**Review by not-napoleon — APPROVED** [review]
LGTM, thanks for adding these.

**Pull request merged**
