### PR TITLE
Correctly handle PKCS#11 tokens for system keystore

### PR DESCRIPTION
**Pull request by jkakavas**
- Ensure we handle the `NONE` keyword for system keystores correctly

  As defined in the PKCS#11 reference guide
  https://docs.oracle.com/javase/8/docs/technotes/guides/security/p11guide.html
  PKCS#11 tokens can be used as the JSSE keystore and truststore and
  the way to indicate this is to set `javax.net.ssl.keyStore` and
  `javax.net.ssl.trustStore` to `NONE` (case sensitive).
  This commits ensures that we honor this convention and do not
  attempt to load the keystore or truststore if the system property is
  set to NONE.

- Ensure we handle password protected `PKCS#11` tokens used as
  system truststores correctly.

  When a PKCS#11 token is used as the system truststore, we need to
  pass a password when loading it, even if only for reading
  certificate entries. This commit ensures that if
  `javax.net.ssl.trustStoreType` is set to `PKCS#11` (as it would
  when a PKCS#11 token is in use) the password specified in
  `javax.net.ssl.trustStorePassword` is passed when attempting to
  load the truststore.

Relates #33459

### CODE REVIEW

**Review by jaymode — APPROVED** [review]
LGTM

**Comment by jkakavas** [comment]
@jaymode I widened the scope of this PR slightly as the changes fitted well together, could you take another look please ?

**Review by jaymode — APPROVED** [review]
LGTM

**Comment by jkakavas** [comment]
CI failed with 
```
FAILURE 0.03s J1 | DateTimeUnitTests.testConversion <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: is <783512977353L>
   >      but: was <783509377353L>
   > 	at __randomizedtesting.SeedInfo.seed([A473697370F6B495:A27BEC495D39EB01]:0)
   > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
   > 	at org.elasticsearch.common.rounding.DateTimeUnitTests.testConversion(DateTimeUnitTests.java:79)
   > 	at java.lang.Thread.run(Thread.java:748)
Completed [958/1128] on J1 in 0.04s, 2 tests, 1 failure <<< FAILURES!
```
This has never failed in the past , this looks unrelated to this PR and possibly related to #32641 (ping @spinscale for visibility), although it doesn't reproduce locally. 
```
./gradlew :server:test -Dtests.seed=A473697370F6B495 -Dtests.class=org.elasticsearch.common.rounding.DateTimeUnitTests -Dtests.method="testConversion" -Dtests.security.manager=true -Dtests.locale=en-NZ -Dtests.timezone=Pacific/Honolulu -Dcompiler.java=10 -Druntime.java=8
```

**Comment by jkakavas** [comment]
Jenkins test this please

**Pull request merged**
