### PR TITLE
Core: Don't verify adler32 for lucene 3.x terms dict/terms index.

### PR DESCRIPTION
**Pull request by rmuir**
These files are not write-once, but the 0.20.x checksum code
didn't handle this properly, so we can't use the adler32.

### CODE REVIEW

**Comment by rjernst** [comment]
LGTM.

**Comment by rjernst** [comment]
Still looks good!

**Comment by rmuir** [comment]
I thought about this .CFS case all day. For now, I would like the additional added logic (see latest commit) to avoid false checksum failures. If we want to throw an error on old versions i would like to separate that from doing the right thing here. Also note again we don't need this cruft on master, just 1.x

**Comment by rmuir** [comment]
Obviously this one is not really easy to test, our backwards tests config currently does not work with such ancient versions. But I know these old segments are still floating around, because I see people still hitting https://issues.apache.org/jira/browse/LUCENE-5975 on 1.3.x versions and so on. Enjoy reviewing :)

**Comment by s1monw** [comment]
looks good though. can we maybe have a simple unittest in StoreTests that checks if your conditionals are working ie with some bogus StoreFileMetadata?

**Comment by rmuir** [comment]
Good idea. We might as well put that fake segmentinfowriter to use.

**Comment by rmuir** [comment]
I added tests for these cases with fake metadata.

**Comment by s1monw** [comment]
very cool thanks rob! LGTM

**Pull request closed without merging**
