### PR TITLE
add Dockerfile to easily build elasticsearch into a runnable linux container

### PR DESCRIPTION
**Pull request by vieux**
It would be nice to have a Dockerfile for this project, to be able to start an ElasticSearch container easily.

1) Instal docker `http://docker.io`
2) Download the Dockerfile `wget https://raw.github.com/elasticsearch/elasticsearch/dockerfile/Dockerfile`
3) Build the container using the Dockerfile `docker build - < Dockerfile`
4) Start ElasticSearch with `docker run <imageid>`

That's it!

### CODE REVIEW

**Comment by bleskes** [comment]
@ESamir did you have a chance to look at this?

**Comment by ESamir** [comment]
@bleskes still discussing the best approach to achieve it

**Comment by clintongormley** [comment]
@ESamir just a ping to remind you about this PR

**Comment by electrical** [comment]
Just to give an update on the thread. We will be having an internal discussion around this subject and hopefully have a more clearer way forward with this.

**Comment by dakrone** [comment]
@ESamir @electrical any update on this? I believe this PR might be so old that it should be re-done with the latest ES changes

**Comment by clintongormley** [comment]
This PR is very old.  Currently there are up to date dockerfiles available from https://github.com/dockerfile/elasticsearch and from Docker Hub Registry, so I'm going to close this for now

**Pull request closed without merging**
