### PR TITLE
Fix ShardGenerations in RepositoryData in BwC Case

### PR DESCRIPTION
**Pull request by original-brownbear**
We were tripping the assertion that the makes sure we only have empty `ShardGenerations` in `RepositoryData` in the BwC case because shard generations were passed to the `Repository` in the BwC case. Fixed by only generating empty shard gen for BwC snapshots in `SnapshotsService`.

Example failure: https://gradle-enterprise.elastic.co/s/p4gcla5uzwqxc/tests/by5gldejueyv2-jascz2copdfni

### CODE REVIEW

**Comment by ywelsch** [comment]
I would prefer to keep the assertion and adapt the call sites. I think this just needs adapting `SnapshotService.buildGenerations` to first do

```
if (snapshot.useShardGenerations()) {
    return ShardGenerations.EMPTY;
}
```

**Comment by original-brownbear** [comment]
@ywelsch right, seems it's only that one spot in fact -> adjusted as suggested :)

**Review by ywelsch — APPROVED** [review]
LGTM
Can you adapt PR title / description?

**Comment by original-brownbear** [comment]
Thanks Yannick!

**Pull request merged**
