### PR TITLE
Limit thread queue during init in ExchangeSource

### PR DESCRIPTION
**Pull request by dnhatn**
ES|QL doesn't work well with 500 clusters or clusters with 500 nodes. The reason is that we enqueue three tasks to the thread pool queue, which has a limit of 1000, during the initialization of the exchange for each target (cluster or node). This simple PR reduces it to one task. I'm considering using AsyncProcessor for these requests, but that will be a follow-up issue for later.

### CODE REVIEW

**Review by nik9000 — APPROVED** [review]
LGTM

**Comment by nik9000** [comment]
> AsyncProcessor

Got a link? I don't see a class called that but I can kind of guess what it'd do here.

**Comment by dnhatn** [comment]
@nik9000 This class: https://github.com/elastic/elasticsearch/blob/573b8a9252e55e24c1c34e9e734b37aafd077e83/server/src/main/java/org/elasticsearch/common/util/concurrent/AsyncIOProcessor.java#L30

**Comment by dnhatn** [comment]
@nik9000 Thanks for review.

**Pull request merged**
