### PR TITLE
Adding cluster alert for ES oversharding

### PR DESCRIPTION
**Pull request by ycombinator**
This PR adds a Stack Monitoring cluster alert for a possibly oversharded Elasticsearch cluster. A cluster is considered to be possibly oversharded if it has more than 20 shards / GB of max heap space.

Related: https://github.com/elastic/kibana/pull/37496.

### Testing this PR

1. Make sure you are running Elasticsearch with a Trial license (as cluster alerts require Alerting).
2. Visit the Stack Monitoring UI in Kibana and make sure Stack Monitoring is enabled for the cluster.
3. Initially, make sure you are running fewer than 20 shards / GB of max. heap space. This should be the case with a default install of a single-node ES cluster.
4. Visit the Stack Monitoring UI > Cluster Overview and make sure there are no cluster alerts about having too many shards.
5. Create a test index with too many shards. For example, for a one-node ES cluster with 1 GB of max. heap space, create this index:

   ```
   PUT oversharder
   {
     "settings": {
       "number_of_shards": 20,
       "number_of_replicas": 0
     }
   }
   ```
6. After a minute or so, visit the Stack Monitoring UI > Cluster Overview and check that a cluster alert like this one shows up:

   Screen Shot 2019-05-29 at 5 26 27 PM

### CODE REVIEW

**Comment by ycombinator** [comment]
TODO: Put up PR in Kibana repo to update this doc: https://www.elastic.co/guide/en/kibana/current/cluster-alerts.html

**Comment by ycombinator** [comment]
A few questions for reviewers:

1. The current implementation in this PR will alert users when they cross 20 shards / GB of max. heap size across the cluster. Is this threshold appropriate or is it too high (i.e. should we alert before they hit this guideline)?

2. The current message of the alert says: 

   > Elasticsearch cluster might have too many shards. Reduce the number of shards, allocate more heap to existing nodes, or increase the number of nodes in the cluster.

   Is this appropriate?

3. The alert currently links to the Elasticsearch Indices page in the Stack Monitoring UI. This page shows the total number of indices, total number of shards, and total heap (used and max) for the cluster. Is this the best place to link the user to?

4. Currently the alert is classified as a high severity alert. Is this level appropriate? Other choice are medium and low.

**Comment by chrisronline** [comment]
ccing @inqueue and @CamiloSierraH for potential thoughts from a support perspective

**Comment by jakelandis** [comment]
The current cluster level watches shipped OOB:

* Cluster status
* Node changed
* Version mismatches
* License expiry

These are pretty concrete states without much room for interpertation or opinion. 

Even though this has the same implementation as the other alerts, imo is new kind of alert. This alert has an opinion, meaning that it is possible to argue if this alert is right or wrong.  IMO, this feel more like a best practice that we could expose through an API/UI.  I am not sure about monitoring as the venue. There are many opinions/best practices that we could encode, shard to memory being one of many. 

I would like to have other people's opinion on this type of alert since (imo) it is taking us into a new direction. 
cc: @eskibars @jasontedor 


Also, if we proceed with this we need to take frozen indices into account too since I believe they are part of the shard count, but should be excluded from the math.

**Comment by ycombinator** [comment]
Thanks for weighing in @jakelandis.

I totally agree that this is much more of an opinionated alert than the ones we have today and that this starts to take Cluster Alerts in a new direction. Making Stack Monitoring more opinionated was one of the strong themes our team discussed at GAH, which is why I felt a bit more comfortable going in this direction than we have ever before. However, if this cluster alert isn't the right vehicle to take a step in the opinionated direction, that's fine with me too — I'm happy to close this PR unmerged.

**Comment by pickypg** [comment]
I'm of the same opinion as @jakelandis. I love the idea of this cluster alert, but we never entered this territory in the past for the reasons that he listed. Inevitably, someone will have a use case where they want this value to be much lower (and certainly many that want it higher).

The key here is that we just need to allow opinions to be configured and our Watcher-based cluster alerts don't really support that because they get created by ES rather than Kibana. _My_ preferred outcome would be to continue with this opinionated approach, but to move it to Kibana Alerting (with the existing cluster alerts!) where these types of things can inherently be presented by a UI and tweaked by the end user. From that point on, we can be as opinionated as we want.

**Comment by ycombinator** [comment]
Thanks @pickypg.

So it sounds like the 20 shards / GB guideline isn't really as official as I perhaps thought it to be. Sounds like there's quite a bit of room for adjustment with that threshold, in either direction, depending on the user's setup.

In that case, I agree our current form of cluster alerts (which are a bit more rigid with their thresholds) isn't the right place to implement such an alert.

So I'm going to close this PR unmerged now.

**Comment by jpountz** [comment]
@ycombinator FYI it's important to remove version labels when closing PRs unmerged, as PRs would otherwise be included in release notes.

**Comment by ycombinator** [comment]
Makes sense, sorry about that @jpountz. Will remember to clean up labels in the future.

**Comment by jpountz** [comment]
No worry!

**Pull request closed without merging**
