### PR TITLE
Upgrade to lucene 5 r1650327

### PR DESCRIPTION
**Pull request by rmuir**
Mostly to cleanup and make use of CodecReader api to make "changing" the index at merge more efficient.

I reimplemented the _uid payloads -> _version docvalues with the new API. It doesn't need to create arrays for all segments up front and keep them around through the whole merge anymore. Additionally other merge optimizations still work, so when upgrading from 0.90.x, you won't need to load all norms up into ram at once, won't decompress stored fields over and over, etc, etc.

I added simple unit tests for this (this scary process seemed completely untested today).

### CODE REVIEW

**Comment by rmuir** [comment]
Ryan added additional tests with our static old indexes in #9207

**Comment by mikemccand** [comment]
LGTM

Very nice to break out the payload -> DV version migration as a FilterCodecReader

**Comment by s1monw** [comment]
LGTM nice test!

**Comment by jpountz** [comment]
LGTM

**Pull request closed without merging**
