### PR TITLE
SQL: Introduce MAD (MedianAbsoluteDeviation) aggregation

### LINKED ISSUE #39597: SQL: Add Median Absolute Deviation (MAD) aggregation
Starting from 6.6, ES provides Median Absolute Deviation (MAD) [aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/7.x/search-aggregations-metrics-median-absolute-deviation-aggregation.html) which SQL can easily support:

`SELECT MAD(rating) FROM reviews GROUP BY year`

### PR DESCRIPTION
**Pull request by costin**
Add Median Absolute Deviation aggregation

Fix #39597

### CODE REVIEW

**Review by matriv — COMMENTED** [review]
Looks good! Could you add a test with using MAD() in a HAVING clause?

**Comment by costin** [comment]
Just did.

**Review by matriv — APPROVED** [review]
LGTM

**Review by astefan — APPROVED** [review]
LGTM

**Pull request merged**
