### PR TITLE
Avoid StackOverflowError due to regex alternate paths 

### LINKED ISSUE #60889: Stackoverflow in Response
**Elasticsearch version** (`bin/elasticsearch --version`): 7.8

**Plugins installed**: [] none

**JVM version** (`java -version`): shipped version

**OS version** (`uname -a` if on a Unix-like system): Windows 10 64bit

**Description of the problem including expected versus actual behavior**:

I am in a migration process from "legacy" index templates to the new composed templates.
As I introduced the composed templates into my application, I will have to remove existing legacy index templates in a "changelog" step.

To test my code, I created a test, that will boot up the actual elasticsearch 7.8 with the actual new composed templates.
Then (in my test only) I create a handful of legacy templates, to allow testing the removal code.

When inserting one of the legacy templates, I get an stackoverflow in some RegEx matching.

In fact, I debugged that to the point, where the response is parsed. The response contains a "warning header", which in my case contains the following error:

(Note: the actual template names are pseudonymized here for company reasons...)

`299 Elasticsearch-7.8.0-757314695644ea9a1dc2fecd26d1a43856725e65 "legacy template [default] has index patterns [*] matching patterns from existing composable templates [templateA, templateB, ...] with patterns (templateA=> [templateA*],templateB=> [templateB*],... => [...*],...); this template [default] may be ignored in favor of a composable template at index creation time"`

To clear this up:
In my legacy templates there was a "default" template with some settings, that are meant to match all actual indices with the old "inheritance" style mechanism with order 0 and so on. Therefore the matching pattern of the "default" template was "*".

The follow up code, see stacktrace below, will try to do some matching of some kind against a monster regexp. 
Somewhere in there, a stackoverflow occurs..

Stacktrace:
`
match:4614, Pattern$Branch (java.util.regex)
match0:4293, Pattern$Curly (java.util.regex)
match:4248, Pattern$Curly (java.util.regex)
match:3812, Pattern$BmpCharProperty (java.util.regex)
match0:4293, Pattern$Curly (java.util.regex)
match:4248, Pattern$Curly (java.util.regex)
match:3812, Pattern$BmpCharProperty (java.util.regex)
match0:4293, Pattern$Curly (java.util.regex)
match:4248, Pattern$Curly (java.util.regex)
match:3986, Pattern$Slice (java.util.regex)
match:1270, Matcher (java.util.regex)
matches:604, Matcher (java.util.regex)
assertWarningValue:194, Response (org.elasticsearch.client)
extractWarningValueFromWarningHeader:185, Response (org.elasticsearch.client)
getWarnings:207, Response (org.elasticsearch.client)
convertResponse:278, RestClient (org.elasticsearch.client)
performRequest:261, RestClient (org.elasticsearch.client)
performRequest:235, RestClient (org.elasticsearch.client)
internalPerformRequest:1611, RestHighLevelClient (org.elasticsearch.client)
performRequest:1581, RestHighLevelClient (org.elasticsearch.client)
performRequestAndParseEntity:1551, RestHighLevelClient (org.elasticsearch.client)
putTemplate:1279, IndicesClient (org.elasticsearch.client)
addLegacyTemplate:59, RemoveLegacyTemplatesIT (my.secret.package)`
`

**Steps to reproduce**:

 1. Boot up an empty cluster of ES 7.8
 2. Insert some composable templates and some index templates with matchPatters like "indexA*", "indexB*" etc.
 3. After that, insert the following LEGACY template:

`
{
  "order": 0,
  "version": 1,
  "index_patterns": [
    "*"
  ],
  "settings": {
    "index": {
      "number_of_shards": "2",
      "auto_expand_replicas": "0-2",
      "number_of_replicas": "0",
      "max_result_window": 5000000,
      "search": {
        "idle": {
          "after": "10s"
        }
      }
    }
  },
  "mappings": {
    "dynamic": false,
    "properties": {
      "createdAt": {
        "type": "date",
        "format": "epoch_millis"
      },
      "lastChange": {
        "type": "date",
        "format": "epoch_millis"
      }
    }
  },
  "aliases": {}
}
`
4. The above mentioned response can be seen in RestClient#convertResponse.
5. When that code invokes Response#getWarnings, the StackOverflow will occur.

### PR DESCRIPTION
**Pull request by andreidan**
Java implements grouping based on patterns that prescribe alternate paths
using recursion. This could lead to StackOverflowError given enough characters
in the target text.

This replaces the "((?:\t| |!|[\\x23-\\x5B]|[\\x5D-\\x7E]|[\\x80-\\xFF]|\\\\|\\\\\")*)\"
group pattern with a lazy "get all characters between quotes" pattern \"(.*?)\"

The `StackOverflowError` occurred only when the assertions were enabled.

Fixes #60889

### CODE REVIEW

**Comment by andreidan** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample-windows

**Review by pgomulka — COMMENTED** [review]
that original regex looks complex.. 
it looks like it was trying to cover some use case with a message containing `\` - it was skiping `\x5C` 
I only speculate, but maybe it expect that message sometimes is an escaped JSON? can we test for this?
Maybe adding a testcase in `HeaderWarningTests`?
WDYT?

**Comment by andreidan** [comment]
@pgomulka I wondered about the regex complexity as well. What I found weird about escaping `\` is that it's added at the end as an escaped literal `\\\\`. 

Adding an escaped json (eg. `{\r\n  \"message\": \"a dummy log\"\r\n}`) in the warning message would not match anymore as we're not escaping any more `"` (quotes) inside the message. We're matching the groups based on surrounding quotes (both before and after this change)

I'm not sure what kind of test to add for this case as it seems it's not designed to have matched.

**Comment by andreidan** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by andreidan** [comment]
Failed test is tracked in https://github.com/elastic/elasticsearch/issues/61261

**Review by pgomulka — APPROVED** [review]
I tested that JSON locally as well and compared with master. The results are the same - both are able to extract that warning value.
LGTM - thank you for fixing this

**Review by dakrone — APPROVED** [review]
LGTM, thanks for tracking this down Andrei

**Comment by jasontedor** [comment]
>that original regex looks complex..

The original regular expression was intended to implement the valid set of characters in a warning message from [3.2.6 of RFC 7230](https://tools.ietf.org/html/rfc7230#section-3.2.6) (cf. [5.5 of RFC 7234](https://tools.ietf.org/html/rfc7234#section-5.5)).

One of the purposes then of the regular expression is to [ensure that we only ever emit warning headers that comply with the RFC](https://github.com/elastic/elasticsearch/blob/bf8b7de05fcef83559807c265119fc40bb07f9f1/server/src/main/java/org/elasticsearch/common/logging/HeaderWarning.java#L175). With this change to `HeaderWarning` we have lost that.

My suggestion would be to revert this change, to preserve that aspect, and investigate dropping the assertions from the REST client parsing of warning headers. Why should that be the consideration? Because in the context of the REST client, we don't have full control over the warning headers that it sees, since it might see some warning headers from a proxy, and that proxy might not be specification compliant, in which case the assertions would be bogus.

**Comment by jasontedor** [comment]
Additionally, as we think about the end-to-end aspects here, we [parse these warning headers in Console](https://github.com/elastic/kibana/blob/edee6543be33bfe61e6a902f62e2e815daebfef2/src/plugins/console/public/lib/utils/index.ts#L62) and we should investigate what impact such a deprecation message has on Console in Kibana.

**Comment by dakrone** [comment]
Ahh I did not see the comment about that being specific to RFC 7234 that is above it :( yes I think it makes sense to only drop it from the REST client side and keep it on the ES side.

For the Console side, should we consider dropping the requirement to parse it in RFC format there as well, since Console could also be talking to a proxy that can return incorrect headers?

**Comment by pgomulka** [comment]
The grammar from https://tools.ietf.org/html/rfc7230#section-3.2.6 totally explains the regex to me now.

But we use non capturing grouping in the original regexp? Shouldn't this prevent us from getting a StackOverflowError?

**Comment by andreidan** [comment]
@jasontedor thanks for the additional context here. I'll revert this and look into disabling the assertion on the rest client side.

**Pull request merged**
