### PR TITLE
Improve exception stacktraces

### PR DESCRIPTION
**Pull request by rmuir**
We can improve our stackframes in exceptions to help with debuggability, errors, hot threads, whatever.
- Give painless the name of the script (stored scripts: the id, file scripts: the filename, inline: null) at compile-time.
- Reduce length of generated class name.
- For inline scripts, we have no "filename" but we include some of the script to help identify it, but truncating with ellipsis if its too big or spans multiple lines.
- Add line number debug information to bytecode. It was added to AST nodes in https://github.com/elastic/elasticsearch/pull/18298. We emit this for all leaf S-nodes.

example:

```
java.lang.NullPointerException
    at org.elasticsearch.painless.Executable$Script.execute(String x = null; boolean y = x.isEmpty(); ... @ <inline script>:1)
```

### CODE REVIEW

**Comment by rjernst** [comment]
LGTM, much nicer looking.

**Comment by jdconrad** [comment]
This is great!  Thanks for doing this. +1

**Comment by rmuir** [comment]
By the way, later we can investigate putting character offsets as line numbers, so the jvm gives us back a more precise location. It is evil but we could do some magic to make it useful.

We gotta start somewhere though, so line numbers seem like walking before running to me.

**Comment by uschindler** [comment]
Looks fine!

**Pull request closed without merging**
