### PR TITLE
Docs: Drop inline callouts from painless book

### PR DESCRIPTION
**Pull request by nik9000**
Drops the inline callouts from the painless reference book. These
callouts are incompatible with Asciidoctor and we'd very much like to
switch to Asciidoctor for building this book, partially because
Asciidoctor is actively developed and AsciiDoc is not, and partially
because it builds the book three times faster.

### CODE REVIEW

**Review by lcawl — APPROVED** [review]
LGTM and builds successfully via both methods

**Comment by nik9000** [comment]
Thanks for reviewing @lcawl! Now for the backport....

**Comment by nik9000** [comment]
While the painless book exists all the way back to 5.5 the inline callouts date back to 6.4. So that is as far as I've backported this change.

**Comment by jdconrad** [comment]
@nik9000 Sorry I missed this review.  Thanks for updating this!  Looking forward to asciidoctor.

**Comment by jpountz** [comment]
@nik9000  I'm assuming there is nothing left to backport and removed the backport pending label.

**Comment by nik9000** [comment]
> @nik9000 I'm assuming there is nothing left to backport and removed the backport pending label.

You are right! Sorry for the trouble!

**Pull request merged**
