### PR TITLE
Upgrade to the latest OWASP HTML sanitizer

### PR DESCRIPTION
**Pull request by jaymode**
This commit upgrades the OWASP HTML sanitizer used by watcher to the
latest version and also upgrades guava, which it depends on. The guava
upgrade also requires the addition of a new dependency that guava
itself requires as of version 27.0.

Relates #50395

### CODE REVIEW

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by jaymode** [comment]
I just pushed a change that removes a test that checks the behavior when the html sanitizer is used with templated values like `{{ctx.metadata.name}}`. The sanitizer's behavior has changed to re-write these templated values with a comment, `{<!-- -->{ctx.metadata.name}}`. This would be an issue if we attempted to sanitize the template, but the code that uses the sanitizer runs the rendered string through the sanitizer, which means that the templated values have been replaced already. The behavior being tested by the test wasn't technically possible or usable based on my understanding.

**Review by rjernst — APPROVED** [review]
Still LGTM

**Comment by jaymode** [comment]
@elasticmachine update branch

**Pull request merged**
