### PR TITLE
Validate IP filter settings

### LINKED ISSUE #72192: IP filter accepts invalid setting but then fails during cluster state application
**Elasticsearch version** (`bin/elasticsearch --version`): observed in 7.11.2 & 7.12.0, but likely others too.

**Plugins installed**: Cloud

**JVM version** (`java -version`): Bundled

**OS version** (`uname -a` if on a Unix-like system): Cloud

**Description of the problem including expected versus actual behavior**:

It is possible to set an invalid value for `xpack.security.transport.filter.allow` via the Put Cluster Settings API, and the invalid value is persisted in the cluster state, but this raises an exception during cluster state application which causes the cluster to enter a loop in which the master node repeatedly fails, wins another election, attempts to apply the invalid value, and fails again. The cluster is effectively unavailable while in this state. If the invalid value is set as a persistent setting then this cannot even be resolved via a full cluster restart.

You can work around this by stopping all the master-eligible nodes, running `elasticsearch-node remove-settings xpack.security.transport.filter.allow` on each of them, and then starting them up again. Alternatively you can disable IP filtering by setting `xpack.security.transport.filter.enabled: false` and `xpack.security.http.filter.enabled: false` in `elasticsearch.yml`, which will allow the cluster to form, and then the persistent setting can be fixed.

Not really sure which area covers this, is it security or distrib? I've guessed distrib.

**Steps to reproduce**:

Execute this on an otherwise healthy cluster:

```
PUT /_cluster/settings
{
  "persistent": {
    "xpack.security.transport.filter.allow": "https://example.com/"
  }
}
```

Observe that the master node is now repeatedly failing.

**Provide logs (if relevant)**:

```
[2021-04-25T14:58:29,074][INFO ][o.e.c.s.ClusterSettings  ] [node-1] updating [xpack.security.transport.filter.allow] from [[]] to [["https://example.com"]]
[2021-04-25T14:58:29,079][WARN ][o.e.c.s.ClusterSettings  ] [node-1] failed to apply settings
org.elasticsearch.ElasticsearchException: unable to create ip filter for rule [allow  https://example.com]
        at org.elasticsearch.xpack.security.transport.filter.SecurityIpFilterRule.getRule(SecurityIpFilterRule.java:174) ~[?:?]
        at org.elasticsearch.xpack.security.transport.filter.SecurityIpFilterRule.<init>(SecurityIpFilterRule.java:63) ~[?:?]
        at org.elasticsearch.xpack.security.transport.filter.IPFilter.createRules(IPFilter.java:277) ~[?:?]
        at org.elasticsearch.xpack.security.transport.filter.IPFilter.parseSettings(IPFilter.java:245) ~[?:?]
        at org.elasticsearch.xpack.security.transport.filter.IPFilter.updateRules(IPFilter.java:232) ~[?:?]
        at org.elasticsearch.xpack.security.transport.filter.IPFilter.setTransportAllowFilter(IPFilter.java:190) ~[?:?]
        at org.elasticsearch.common.settings.Setting$Updater.apply(Setting.java:1160) ~[elasticsearch-7.12.0.jar:7.12.0]
        at org.elasticsearch.common.settings.AbstractScopedSettings$SettingUpdater.lambda$updater$0(AbstractScopedSettings.java:618) ~[elasticsearch-7.12.0.jar:7.12.0]
        at org.elasticsearch.common.settings.AbstractScopedSettings.applySettings(AbstractScopedSettings.java:182) [elasticsearch-7.12.0.jar:7.12.0]
        at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:455) [elasticsearch-7.12.0.jar:7.12.0]
        at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:407) [elasticsearch-7.12.0.jar:7.12.0]
        at org.elasticsearch.cluster.service.ClusterApplierService.access$000(ClusterApplierService.java:57) [elasticsearch-7.12.0.jar:7.12.0]
        at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:151) [elasticsearch-7.12.0.jar:7.12.0]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:673) [elasticsearch-7.12.0.jar:7.12.0]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:241) [elasticsearch-7.12.0.jar:7.12.0]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:204) [elasticsearch-7.12.0.jar:7.12.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.net.UnknownHostException: https:: nodename nor servname provided, or not known
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[?:?]
        at java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:932) ~[?:?]
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1517) ~[?:?]
        at java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:851) ~[?:?]
        at java.net.InetAddress.getAllByName0(InetAddress.java:1507) ~[?:?]
        at java.net.InetAddress.getAllByName(InetAddress.java:1366) ~[?:?]
        at java.net.InetAddress.getAllByName(InetAddress.java:1300) ~[?:?]
        at java.net.InetAddress.getByName(InetAddress.java:1250) ~[?:?]
        at org.elasticsearch.xpack.security.transport.filter.SecurityIpFilterRule.parseSubnetMask(SecurityIpFilterRule.java:95) ~[?:?]
        at org.elasticsearch.xpack.security.transport.filter.SecurityIpFilterRule.getRule(SecurityIpFilterRule.java:170) ~[?:?]
        ... 18 more
[2021-04-25T14:58:29,089][WARN ][o.e.c.s.ClusterApplierService] [node-1] failed to apply updated cluster state in [200ms]:
version [806], uuid [MQYUJMC2TYO119m74nLjgg], source [Publication{term=879, version=806}]
org.elasticsearch.ElasticsearchException: unable to create ip filter for rule [allow  https://example.com]
        at org.elasticsearch.xpack.security.transport.filter.SecurityIpFilterRule.getRule(SecurityIpFilterRule.java:174) ~[?:?]
        at org.elasticsearch.xpack.security.transport.filter.SecurityIpFilterRule.<init>(SecurityIpFilterRule.java:63) ~[?:?]
        at org.elasticsearch.xpack.security.transport.filter.IPFilter.createRules(IPFilter.java:277) ~[?:?]
        at org.elasticsearch.xpack.security.transport.filter.IPFilter.parseSettings(IPFilter.java:245) ~[?:?]
        at org.elasticsearch.xpack.security.transport.filter.IPFilter.updateRules(IPFilter.java:232) ~[?:?]
        at org.elasticsearch.xpack.security.transport.filter.IPFilter.setTransportAllowFilter(IPFilter.java:190) ~[?:?]
        at org.elasticsearch.common.settings.Setting$Updater.apply(Setting.java:1160) ~[elasticsearch-7.12.0.jar:7.12.0]
        at org.elasticsearch.common.settings.AbstractScopedSettings$SettingUpdater.lambda$updater$0(AbstractScopedSettings.java:618) ~[elasticsearch-7.12.0.jar:7.12.0]
        at org.elasticsearch.common.settings.AbstractScopedSettings.applySettings(AbstractScopedSettings.java:182) ~[elasticsearch-7.12.0.jar:7.12.0]
        at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:455) ~[elasticsearch-7.12.0.jar:7.12.0]
        at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:407) [elasticsearch-7.12.0.jar:7.12.0]
        at org.elasticsearch.cluster.service.ClusterApplierService.access$000(ClusterApplierService.java:57) [elasticsearch-7.12.0.jar:7.12.0]
        at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:151) [elasticsearch-7.12.0.jar:7.12.0]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:673) [elasticsearch-7.12.0.jar:7.12.0]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:241) [elasticsearch-7.12.0.jar:7.12.0]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:204) [elasticsearch-7.12.0.jar:7.12.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.net.UnknownHostException: https:: nodename nor servname provided, or not known
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[?:?]
        at java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:932) ~[?:?]
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1517) ~[?:?]
        at java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:851) ~[?:?]
        at java.net.InetAddress.getAllByName0(InetAddress.java:1507) ~[?:?]
        at java.net.InetAddress.getAllByName(InetAddress.java:1366) ~[?:?]
        at java.net.InetAddress.getAllByName(InetAddress.java:1300) ~[?:?]
        at java.net.InetAddress.getByName(InetAddress.java:1250) ~[?:?]
        at org.elasticsearch.xpack.security.transport.filter.SecurityIpFilterRule.parseSubnetMask(SecurityIpFilterRule.java:95) ~[?:?]
        at org.elasticsearch.xpack.security.transport.filter.SecurityIpFilterRule.getRule(SecurityIpFilterRule.java:170) ~[?:?]
        ... 18 more
[2021-04-25T14:58:29,098][INFO ][o.e.c.s.ClusterApplierService] [node-1] master node changed {previous [{node-1}{UEwM9WBVQxOfK7Vrk8HvmA}{YraW7amCTQGGJ5qInTtidw}{127.0.0.1}{127.0.0.1:9301}{cdfhilmrstw}{ml.machine_memory=68719476736, xpack.installed=true, transform.node=true, ml.max_open_jobs=20, ml.max_jvm_s
ize=1073741824}], current []}, term: 879, version: 806, reason: becoming candidate: clusterApplier#onNewClusterState
[2021-04-25T14:58:29,110][INFO ][o.e.c.s.ClusterSettings  ] [node-1] updating [xpack.security.transport.filter.allow] from [[]] to [["https://example.com"]]
```

### PR DESCRIPTION
**Pull request by DaveCTurner**
Today it is possible to set up an IP filter which throws an exception on
creation, which is fatal to the cluster. This commit adds validation to
the IP filtering settings to prevent this.

Closes #72192

### CODE REVIEW

**Review by original-brownbear — APPROVED** [review]
LGTM (Didn't check all the reformatting but I assume it's ok :))

**Review by original-brownbear — CHANGES_REQUESTED** [review]
Ah there's relevant test failures though I think

**Comment by DaveCTurner** [comment]
Yep I guessed wrongly when adding the extra params in the settings declarations, fixed in 60e8f03.

**Review by original-brownbear — APPROVED** [review]
LGTM :)

**Review by jasontedor — APPROVED** [review]
LGTM.

**Pull request merged**
