### PR TITLE
Fix execution of exists query within nested queries on field with doc_values disabled

### LINKED ISSUE #76362: "exists" query in "nested" query never matches for fields without doc_values within nested fields
**Elasticsearch version** (`bin/elasticsearch --version`): 7.14.0 (docker)
Everything works on 7.13.4.

**Plugins installed**: []

**JVM version** (`java -version`): whatever comes with the docker container

**OS version** (`uname -a` if on a Unix-like system):

```
Linux yrodiere.redhat 5.13.6-200.fc34.x86_64 #1 SMP Wed Jul 28 15:31:21 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Description of the problem including expected versus actual behavior**:

Given this mapping:

```json
{
  "mappings": {
    "properties": {
      "mynested": {
        "type": "nested",
        "properties": {
          "mykeyword": {
            "type": "keyword",
            "doc_values": "false"
          }
        }
      }
    }
  }
}
```

The following search query will never match on ES 7.14.0, regardless of the content of the index:

```json
{
  "query": {
    "nested": {
      "path": "mynested",
      "query": {
        "exists": {
          "field": "mynested.mykeyword"
        }
      }
    }
  }
}
```

It used to match on ES 7.13.4 (and many previous versions).

Enabling doc_values makes it match again. Removing the "nested" query around the "exists" query makes it match again.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

```sh
curl -XPUT -H "Content-Type: application/json" 'localhost:9200/test/' -d'{"mappings": {"properties": {"mynested": {"type": "nested", "properties": {"mykeyword": { "type": "keyword", "doc_values": "false" } } } } } }'
curl -XPUT -H "Content-Type: application/json" 'localhost:9200/test/_doc/1' -d '{"mynested": { "mykeyword" : "present" } }'
curl -XPOST -H "Content-Type: application/json" 'localhost:9200/test/_search' -d '{"query": { "nested": { "path": "mynested", "query": { "exists": { "field" : "mynested.mykeyword" } } } } }'
```

Results on 7.14.0:

```json
{
  "took": 5,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 0,
      "relation": "eq"
    },
    "max_score": null,
    "hits": []
  }
}
```

Results on 7.13.4:

```json
{
  "took": 79,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 1,
      "relation": "eq"
    },
    "max_score": 1,
    "hits": [
      {
        "_index": "test",
        "_type": "_doc",
        "_id": "1",
        "_score": 1,
        "_source": {
          "mynested": {
            "mykeyword": "present"
          }
        }
      }
    ]
  }
}
```

**Provide logs (if relevant)**: N/A

### PR DESCRIPTION
**Pull request by yrodiere**
Fixes #76362, which is a regression that first occurred in 7.14.0.

In order to fix the problem, we need to add a `_field_names` field to nested documents. However, just like root documents, this field will only be populated with fields that have no doc values nor norms. Which means that this patch won't change anything, except for users who explicitly opted out of doc values for one of their fields.

I'm sorry if this does not pass the full test suite; I tried running it locally but it fails for some unknown (but unrelated) reason. I executed a few relevant tests manually, and I'll have to wait for CI to give a full report.

If this gets merged, could we please backport this PR to 7.x? That would allow the [Hibernate Search](https://github.com/hibernate/hibernate-search) test suite to pass on something more recent than ES 7.13.

### CODE REVIEW

**Comment by mark-vieira** [comment]
@elasticmachine retest this please

**Comment by yrodiere** [comment]
Thanks. Having a look at the test failures right now.

**Comment by yrodiere** [comment]
It appears `MixedClusterClientYamlTestSuiteIT` was failing because it checks what happens when running the tests I added against a clustering comprising ES 8 nodes and ES 7.16 nodes, and obviously the bug wasn't fixed in ES 7.16 yet: we need a backport for that.

For now I added guards to prevent testing against ES 7.x, like I've seen it done in [that other PR](https://github.com/elastic/elasticsearch/pull/77267/files).

I also fixed the tab that was making the "part-1" build fail.

**Review by romseygeek — CHANGES_REQUESTED** [review]
Thanks for opening @yrodiere!

I think we can do this more simply by changing the implementation of `DocumentParserContext.addToFieldNames()`; instead of collecting the field names and then adding them to the document in postParse(), we can instead add each field name individually as a new Field to the current document directly in `addToFieldNames()`.  We don't store freqs or positions on the field names field so adding duplicate values won't matter, and then the existing logic that copies fields from nested docs to their parents will handle things naturally.

Would you be interested in trying this out?

**Comment by yrodiere** [comment]
Hey @romseygeek ,

Sure, I can do this.

However, I will ask confirmation about a few things before I start:

> we can instead add each field name individually as a new Field to the current document directly in addToFieldNames()

You went out of your way to do the exact opposite, making sure the mapper itself adds the fields names: #71929 (in particular 
https://github.com/elastic/elasticsearch/pull/71929/commits/0c509b4365a62ebe9e9ede4080b4d6b9b40b4768#diff-2996184d1f59c95c1530f925f7308296b84cb7f43fb47aac2845cde01510be5fR159-R166 ).

In fact, that's the main reason I tried to use `FieldNamesFieldMapper`; I thought that was a newly introduced practice that was preferred over the previous one.

Can you confirm you changed your mind and no longer want that?

> the existing logic that copies fields from nested docs to their parents will handle things naturally

By "existing logic", do you mean the one I just added that keeps a reference to the parent in `DocumentParserContext`? Because that's the main driver for the complexity of this patch, so I'm guessing you won't like that. Before my patch, there wasn't any `_field_names` field in nested documents, so I doubt there was anything to copy it to the root.

Or do you mean the [`include_in_parent` parameter of `nested` field mapping](https://www.elastic.co/guide/en/elasticsearch/reference/current/nested.html#nested-include-in-parent-parm)? Because that's optional and disabled by default, so I believe relying on this would change the previous behavior that allowed running an `exists` query without wrapping it into a `nested` query.

Or do you mean another "existing logic" that copies `_field_names` from nested documents to the root document? Because I didn't see that anywhere...

To be clear I *personally* don't need `_field_names` to be copied to the parent document: I always wrap `exists` queries into `nested` queries when necessary, so I have no horse in this game. I just don't want to introduce backwards-incompatible changes that you will have to deal with later, so I thought I'd bring this to your attention.

**Review by romseygeek — CHANGES_REQUESTED** [review]
This looks great, thank you! I think we need one more test scenario to check that `includeInParent` will work as expected, but other than that this is good to go.

**Comment by romseygeek** [comment]
@elasticmachine test this please

**Comment by romseygeek** [comment]
@elasticmachine test this please

**Comment by yrodiere** [comment]
I tried to see if there was something I could do to fix the tests, but I'm not sure the failures I related to my changes. There's something about field caps, something about node discovery, ... I'm wondering if those aren't simply flaky tests?

**Comment by stewi2** [comment]
>  except for users who explicitly opted out of doc values for one of their fields

To clarify, #80309 happened on a *text* field, which doesn't support doc_values in the first place. I think the issue was more that we had also disabled norms, meaning that exists() queries had to fall back to using field_entries, which didn't exist (as far as I understand).

```json
"first": {
    "type": "text",
    "norms": false
},
```

` "type": "text"` basically implies `"doc_values": false`.

**Comment by yrodiere** [comment]
> To clarify, #80309 happened on a _text_ field, which doesn't support doc_values in the first place.

That's right, this is slightly different from #76362, which this PR is supposed to fix.

> Not sure if this PR would fix that case as well?

It should.

I didn't add any code specific to doc_values. Elasticsearch already had code that detects whether a field needs an entry in the `_field_names` field, and that code already took into account both missing doc_values and missing norms. It worked well enough for both.

All this PR does is make sure that, *when* Elasticsearch detects that a field needs an entry in the `_field_names` field, then it adds this entry to the right (nested) document.

So, yes, I think this PR should fix #80309 as well.

If you want to be sure, you can add more tests to `rest-api-spec/src/yamlRestTest/resources/rest-api-spec/test/search/161_exists_query_within_nested_query.yml`. Or... just test a patched version of Elasticsearch locally.

**Pull request merged**
