### PR TITLE
Rename Azure Plugin Packages in 6.8 to align with 7+

### PR DESCRIPTION
**Pull request by original-brownbear**
* Rename Azure repository plugin packages to be in alignment with the code in 7+
  * Deleted dead code in one sub-package (the two exceptions) instead of redundantly moving them
* Completely mechanical refactoring, no manual code changes
  * This is motivated by the need to backport numerous changes to snapshots to 6.8 (SAS token support + repository cleanup logic) and it is safer to mechanically rename this plugin's package names than to manually adjust all necessary changes to fit a different package organization in backports

### CODE REVIEW

**Comment by original-brownbear** [comment]
@ywelsch I didn't have to do any manual changes here (outside of changing the name of plugin class in the Gradle file). This seems a lot safer to me, than manually applying all changes from `master` to the existing structure in 6.8.

**Review by ywelsch — APPROVED** [review]
LGTM

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/default-distro (just random Jenkins connectivity issue)

**Comment by original-brownbear** [comment]
thanks @ywelsch :)

**Pull request merged**
