### PR TITLE
Remove unnecessary shard routing null checks

### PR DESCRIPTION
**Pull request by pxsalehi**
`IndexShard.routingEntry()` doesn't return null anymore, and therefore these checks are not needed.

### CODE REVIEW

**Comment by pxsalehi** [comment]
@elasticmachine elasticsearch-ci/docs

(seems like an infra issue!)

**Comment by pxsalehi** [comment]
hmm...
```
There was an error while communicating with Elasticsearch.   There may be data missing in the Build Stats cluster.   Infra has been notified.
```

**Review by henningandersen — APPROVED** [review]
LGTM. (provided CI passes).

**Review by DaveCTurner — APPROVED** [review]
LGTM2

**Comment by pxsalehi** [comment]
@elasticmachine update branch

**Comment by pxsalehi** [comment]
Failure was https://github.com/elastic/elasticsearch/issues/96374

**Pull request merged**
