### PR TITLE
QL: Rename incorrect plural in method name

### PR DESCRIPTION
**Pull request by costin**
forEachExpressions -> forEachExpression (singular)

### CODE REVIEW

**Comment by costin** [comment]
I was tempted to apply this for `transformPropertiesOnly` however there it makes sense just like `replaceChildren` vs `forEachProperties` which is consistent but grammatically incorrect.

**Review by palesz — APPROVED** [review]
LGTM

**Review by astefan — APPROVED** [review]
LGTM

**Comment by costin** [comment]
Thanks folks!

**Pull request merged**
