### PR TITLE
Fix Noisy Warnings in SecurityIntegTestCase

### PR DESCRIPTION
**Pull request by original-brownbear**
Adding the mapper extras plugin to avoid endless warnings about a
missing scaled_float mapper in these tests.
Also, removed some unrelated dead code that wasn't really worth a separate PR.

### CODE REVIEW

**Review by albertzaharovits — COMMENTED** [review]
I assume you're referring to errors such as:
```
java.lang.IllegalArgumentException: composable template [.monitoring-kibana-mb] template after composition is invalid
	at org.elasticsearch.cluster.metadata.MetadataIndexTemplateService.validateIndexTemplateV2(MetadataIndexTemplateService.java:670) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at org.elasticsearch.cluster.metadata.MetadataIndexTemplateService.addIndexTemplateV2(MetadataIndexTemplateService.java:612) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at org.elasticsearch.cluster.metadata.MetadataIndexTemplateService$4.execute(MetadataIndexTemplateService.java:496) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:51) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:828) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:395) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:235) [elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:167) [elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:146) [elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:202) [elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:716) [elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:262) [elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:225) [elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalArgumentException: invalid composite mappings for [.monitoring-kibana-mb]
	at org.elasticsearch.cluster.metadata.MetadataIndexTemplateService.lambda$validateCompositeTemplate$25(MetadataIndexTemplateService.java:1426) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at org.elasticsearch.indices.IndicesService.withTempIndexService(IndicesService.java:680) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at org.elasticsearch.cluster.metadata.MetadataIndexTemplateService.validateCompositeTemplate(MetadataIndexTemplateService.java:1395) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at org.elasticsearch.cluster.metadata.MetadataIndexTemplateService.validateIndexTemplateV2(MetadataIndexTemplateService.java:664) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	... 15 more
Caused by: org.elasticsearch.index.mapper.MapperParsingException: Failed to parse mapping: No handler for type [scaled_float] declared on field [ms]
	at org.elasticsearch.index.mapper.MapperService.parseMapping(MapperService.java:382) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at org.elasticsearch.index.mapper.MapperService.mergeAndApplyMappings(MapperService.java:359) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:350) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at org.elasticsearch.cluster.metadata.MetadataIndexTemplateService.lambda$validateCompositeTemplate$25(MetadataIndexTemplateService.java:1419) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at org.elasticsearch.indices.IndicesService.withTempIndexService(IndicesService.java:680) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at org.elasticsearch.cluster.metadata.MetadataIndexTemplateService.validateCompositeTemplate(MetadataIndexTemplateService.java:1395) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	at org.elasticsearch.cluster.metadata.MetadataIndexTemplateService.validateIndexTemplateV2(MetadataIndexTemplateService.java:664) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
	... 15 more
```
By my reading of the code these are generated by the templates inserted via  `IndexTemplateRegistry#addLegacyTEmplatesIfMissing` .
These are also generated outside of the ITs that use the `LocalStateSecurityPlugin`; I've tested `MonitoringIT`.
I think the fix with adding the `MapperExtraPlugin` should probably be made in another place so that it covers all the cases (not only Security ITs).

**Comment by original-brownbear** [comment]
> I think the fix with adding the MapperExtraPlugin should probably be made in another place so that it covers all the cases (not only Security ITs).

That would be nice (maybe) but the problem with the approach is that we'd have to add a new module for this or add the mapper extras module to the test framework in general which is quite dirty as well I think.
Since we already explicitly have that plugin in the `build.gradle` I think this is the best we can do here for now (did the same for ML tests already as well and we're using the same pattern all over the place for that matter for plugins).

**Comment by albertzaharovits** [comment]
> with the approach is that we'd have to add a new module for this or add the mapper extras module to the test framework in general which is quite dirty as well I think.

You've lost me here a bit.

I think at a high-level we need to ensure that the the `MapperExtraPlugin` is loaded when the plugins that use an `IndexTemplateRegistry` are loaded as well. Or, more generally when the `.monitoring-kibana-mb` index template is installed the `MapperExtraPlugin` must also be installed.

It looks to me that we don't spend time expressing such dependencies in general.
Hence I don't think we should/can fix something like that in this PR.
But maybe someone from @elastic/es-core-infra can shed some light on the issue?

For now I'm content with jimmying the modules in integ tests because I can't see a better way.
Thanks for fixing Security tests, Armin!

**Review by albertzaharovits — APPROVED** [review]

**Comment by original-brownbear** [comment]
Thanks Albert!

**Pull request merged**
