### PR TITLE
Datastream: _data_stream_timestamp use const variable to replace magic string

### PR DESCRIPTION
**Pull request by weizijun**
a tiny PR to improve _data_stream_timestamp

### CODE REVIEW

**Comment by martijnvg** [comment]
@elasticmachine test this please

**Review by martijnvg — APPROVED** [review]
LGTM, thanks @weizijun!

**Comment by weizijun** [comment]
> LGTM, thanks @weizijun!

Thank you, @martijnvg !

**Comment by weizijun** [comment]
@elasticsearchmachine update branch

**Comment by weizijun** [comment]
@elasticmachine update branch

**Comment by martijnvg** [comment]
@elasticmachine test this please

**Comment by weizijun** [comment]
@martijnvg all checks have passed, can you help to merge this PR?

**Comment by martijnvg** [comment]
> @martijnvg all checks have passed, can you help to merge this PR?

Yes!

**Pull request merged**
