### PR TITLE
Update docs on using case_insensitive field parameter in term query

### LINKED ISSUE #69402: Update docs on using case_insensitive field parameter in term query
Before ES 7.10.0 version, the `case_insensitive` field parameter was not present for the term query. As mentioned in this [Github issue](https://github.com/elastic/elasticsearch/issues/53603) and [PR](https://github.com/elastic/elasticsearch/pull/63218/files), support for the `case_insensitive` field parameter was added in the `7.10.0` version itself.

But in the official documentation, it is **not mentioned explicitly that in which version this field parameter was introduced**, which creates confusion.

### PR DESCRIPTION
**Pull request by bhavyaidr**
Fixes #69402

### CODE REVIEW

**Review by jrodewig — COMMENTED** [review]
Hi @bhavya121999. Thanks for your interest in contributing. However, I feel that the `case_sensitive` parameter is already adequately documented lower on this page.

I'm going to close this PR. Please comment or re-open if you feel I've overlooked anything.

**Comment by bhavya121999** [comment]
@jrodewig As mentioned in this [issue](https://github.com/elastic/elasticsearch/issues/69402), before ES 7.10.0 version, the `case_insensitive` field parameter was not present for the term query.

But in the official documentation, it is **not mentioned explicitly that in which version this field parameter was introduced.** This creates confusion, so I have raised this PR to update the term query doc, **highlighting the version** in which the `case_insensititve` parameter is added.

**Comment by jrodewig** [comment]
Thanks for linking to the issue and providing additional context @bhavya121999.

Rather than an important admonition, I think we can use an `added` admonition to highlight this more discretely. It'll also make it easier for us to remove the admonition after some time has passed.

Screen Shot 2021-02-23 at 11 57 24 AM


Let me know if you feel that addresses your concerns. Thanks again!

**Comment by jrodewig** [comment]
@elasticmachine ok to test

**Comment by bhavya121999** [comment]
@jrodewig yes, now the version is properly highlighted for the `case_insensitive` parameter. Thank you!

**Pull request merged**
