### PR TITLE
Checkstyle: don't require javadoc on test methods

### PR DESCRIPTION
**Pull request by nik9000**
Test methods tend to have descriptive names for the cases that they are
testing. Sometimes they require javadoc, for sure, but not often enough
to add a little "WEAK WARNING" marker on every single test method in my
IDE.

### CODE REVIEW

**Comment by nik9000** [comment]
@elaticmachine update branch

**Comment by nik9000** [comment]
@elaticmachine update branch

**Comment by nik9000** [comment]
@elasticmachine update branch

**Review by mark-vieira — APPROVED** [review]
LGTM

**Comment by nik9000** [comment]
:heart:

**Pull request merged**
