### PR TITLE
Clarified archived cluster settings removal usage

### PR DESCRIPTION
**Pull request by ppf2**
Clarified removal usage where a single request updating both persistent and transient settings is required if there are both persistent and transient archived settings.

### CODE REVIEW

**Review by original-brownbear — COMMENTED** [review]
I'd like someone from the docs team to take a look here. Not 100% sure it's a good idea to adjust the existing documentation only, maybe we'd want to add a separate section here?

**Comment by abdonpijpelink** [comment]
There's a statement on [this page](https://www.elastic.co/guide/en/elasticsearch/reference/master/archived-settings.html) that "Elasticsearch doesn’t archive transient cluster settings [...]". Is that statement incorrect? How would you end up with archived transient cluster settings?

**Comment by abdonpijpelink** [comment]
@ppf2 @original-brownbear How do we move forward with this PR? 

Is it possible to end up with archived transient cluster settings, even though the docs [state](https://www.elastic.co/guide/en/elasticsearch/reference/master/archived-settings.html) that ES does not archive transient cluster settings? 

If so, we should remove that statement. If not, then I think we can close this PR unmerged.

**Review by abdonpijpelink — APPROVED** [review]
LGTM

**Comment by ppf2** [comment]
This one has been opened for some time.  Since it's an edge case, we don't have to merge and this PR will just serve as a reference for those who happen to come across it. Thx!

**Pull request closed without merging**
