### PR TITLE
Add migration docs for Log4j dependency

### PR DESCRIPTION
**Pull request by jasontedor**
The Log4j dependency has been upgraded from version 2.6.2 to version
2.7. This commit adds a note to the migration docs regarding this
change.

Relates #20805

### CODE REVIEW

**Comment by s1monw** [comment]
LGTM

**Comment by clintongormley** [comment]
Does this need to be a breaking change every time we upgrade log4j2?  Won't the IDE flag the problem if the user doesn't upgrade?

**Comment by nik9000** [comment]
> Won't the IDE flag the problem if the user doesn't upgrade?

Maven/Ivy/Gradle/Whatever should update the for anyone who is upgrading and Log4j2 should be backwards compatible but I don't think it hurts to tell people....

**Comment by ywelsch** [comment]
@clintongormley this is related to #21331. ES 5.0.0 doesn't play nicely with log4j 2.7.0 and ES 5.1.0 might not like log4j 2.6.2 (needs to be checked). In general I don't think that every dependency upgrade deserves an entry in the breaking changes docs but in this particular case it totally makes sense.

**Comment by jasontedor** [comment]
@clintongormley The upgrade from 5.0.x to 5.1.x is a special case because we have hacks in place in our code where we intentionally introduced jar hell to hack around some bugs in Log4j that existed in 2.6.2 but were fixed in the 2.7 release. I've already seen instances in the wild of people using the wrong version (Log4j 2.7 with 5.0.0) that are causing problems. The IDE will not flag the problem because the APIs that most people are going to be using are unchanged, so they will not get compile-time errors. It is for these reasons that I think in this case (but not necessarily every case) we should tell people that they need to upgrade this dependency if they are using the transport client.

**Comment by jasontedor** [comment]
I had verified through another channel that @clintongormley is okay with the explanation given here.

**Pull request merged**
