### PR TITLE
[8.x] ES|QL: Fix ResolvedEnrichPolicy serialization (bwc) in >= 8.16 (#112988)

### PR DESCRIPTION
**Pull request by luigidellaquila**
Backports the following commits to 8.x:
 - ES|QL: Fix ResolvedEnrichPolicy serialization (bwc) in >= 8.16 (#112988)

### CODE REVIEW

**Comment by luigidellaquila** [comment]
@elasticmachine update branch

**Review by bpintea — APPROVED** [review]

**Comment by luigidellaquila** [comment]
@elasticmachine update branch

**Comment by luigidellaquila** [comment]
@elasticmachine run elasticsearch-ci/part-4

**Comment by luigidellaquila** [comment]
@elasticmachine update branch

**Comment by luigidellaquila** [comment]
ML tests failing... connection refused...

**Comment by luigidellaquila** [comment]
@elasticmachine run elasticsearch-ci/part-1

**Comment by luigidellaquila** [comment]
@elasticmachine update branch

**Comment by luigidellaquila** [comment]
@elasticmachine update branch

**Pull request merged**
