### PR TITLE
Remove search exists api

### LINKED ISSUE #13682: Remove search-exists API
The search-exists API tells you if there are any matching results, without performing a count. Besides this being an almost-never-useful operation, it could easily be replicated with:

    GET _search?size=0&terminate_after=1

I propose removing this API.

### PR DESCRIPTION
**Pull request by javanna**
With #13910 we deprecate `_search/exists`, we can then remove the api from the master branch.

Closes #13682

### CODE REVIEW

**Comment by jpountz** [comment]
LGTM

**Comment by jpountz** [comment]
Should we add a note to the migration guide?

**Comment by javanna** [comment]
I added the missing note to the migration guide and rebased, should be ready

**Comment by jpountz** [comment]
LGTM again

**Pull request closed without merging**
