### PR TITLE
Remove PROTOTYPE from BulkItemResponse.Failure

### LINKED ISSUE #17086: BulkItemResponse.Failure should have a StreamInput constructor
We usually implement the Writeable interface by delegating to a constructor that takes StreamInput. We should do that here.

### PR DESCRIPTION
**Pull request by nik9000**
Closes #17086

### CODE REVIEW

**Comment by nik9000** [comment]
@javanna this one should be easier.

**Comment by jpountz** [comment]
LGTM

**Comment by javanna** [comment]
how come @jpountz takes all the easy ones from me? ;)  LGTM too!

**Comment by nik9000** [comment]
Thanks for the reviews @jpountz and @javanna !

**Pull request merged**
