### PR TITLE
Introduce Application Privileges with support for Kibana RBAC

### PR DESCRIPTION
**Pull request by tvernum**
This commit introduces "Application Privileges" to the X-Pack security model.

Application Privileges are managed within Elasticsearch, and can be tested with the _has_privileges API, but do not grant access to any actions or resources within Elasticsearch.
Their purpose is to allow applications outside of Elasticsearch to represent and store their own privileges model within Elasticsearch roles.

Access to manage application privileges is handled in a new way that grants permission to specific application names only. This lays the foundation for more OLS on cluster privileges, which is implemented by allowing a cluster permission to inspect not just the action being executed, but also the request to which the action is applied.
To support this, a "conditional cluster privilege" is introduced, which is like the existing cluster privilege, except that it has a Predicate over the request as well as over the action name.

Specifically, this adds
- GET/PUT/DELETE actions for defining application level privileges
- application privileges in role definitions
- application privileges in the has_privileges API
- changes to the cluster permission class to support checking of request objects
- a new "policy" element on role definition to provide cluster object level security (only for manage application privileges)
- changes to `kibana_user`, `kibana_dashboard_only_user` and `kibana_system` roles to use and manage application privileges

### CODE REVIEW

**Comment by tvernum** [comment]
We need to merge two more PRs in this feature branch before merging it to master, but I wanted to get this up, and running through CI as is.
- https://github.com/elastic/elasticsearch/pull/32272 (@tvernum)
- https://github.com/elastic/elasticsearch/pull/32137 (@kobelb)

**Comment by tvernum** [comment]
> dpkg: error: dpkg status database is locked by another process

@elasticmachine run sample packaging tests

**Comment by Mpdreamz** [comment]
This PR introduces:

* `xpack.security.put_privilege.json`
* `xpack.security.put_privileges.json`

Do we need both variants can we get by with just the plural accepting multiple privileges in one go? This would be the first API that has two different endpoints for the put operation.
If we do need both should we rename `xpack.security.put_privileges.json` to `xpack.security.update_privileges.json` in the same vein as `indices.update_aliases.json`? It would help to distinguish between the two API's.
 
###  `xpack.security.put_privileges.json` 

Has the prefix `put_*` but defines:

```json
    "methods": [ "POST"],
````
Which makes me feel a rename is in order even more.

### `xpack.security.put_privilege.json`

defines the methods:

```json
    "methods": [ "POST", "PUT" ],
````

I think this method should only accept `PUT` or document this as

```json
    "methods": [ "PUT", "POST" ],
````

The only API documenting `POST, PUT` is the `index` API which has a quirk in that not all `paths` are valid for all `methods` something the spec currently does not catch.

**Comment by jaymode** [comment]
@kobelb is Kibana using both APIs?

@Mpdreamz does the ordering of PUT/POST in the spec matter? Without knowledge of why the order matters it seems like a nit.

@tvernum when you're available can you chime in?

**Comment by kobelb** [comment]
> @kobelb is Kibana using both APIs?

Kibana is using `POST` to create multiple privileges.

**Comment by jaymode** [comment]
After thinking about this and confirming the current usage by Kibana, I raised #32879 to remove the put privilege API and only have the put privileges API that supports both PUT and POST. I labeled this issue for team discussion @elastic/es-security in case others oppose this approach.

**Comment by Mpdreamz** [comment]
> does the ordering of PUT/POST in the spec matter? Without knowledge of why the order matters it seems like a nit.

Total nit, it doesn't matter in my code generator but it could potentially in others.  Just be a shame to break our consistency here. #32879 addresses this though 🎈 🍰

**Comment by codebrain** [comment]
The documentation links in the REST JSON spec files are reading as `TODO`.

E.g. https://github.com/elastic/elasticsearch/blob/d09ed171365f603a276fbd903ffafdf758b1ed4e/x-pack/plugin/src/test/resources/rest-api-spec/api/security.put_privileges.json#L3

Not a big deal, but with the documentation now available on the site, was there an intention to update the spec?

**Pull request merged**
