### PR TITLE
Add `rewrite` query parameter to the `indices.validate_query` API spec

### PR DESCRIPTION
**Pull request by gmarz**
Added in #10147

### CODE REVIEW

**Comment by javanna** [comment]
thanks @gmarz maybe add a REST test that uses it too?

**Comment by gmarz** [comment]
@javanna thanks for the review, I added it to the basic yaml test.  Let me know if your prefer that I squash these two commits.

**Comment by javanna** [comment]
LGTM thanks @gmarz

**Comment by gmarz** [comment]
Merged to master (https://github.com/elastic/elasticsearch/commit/8dd7dae5b986148be126a336c937e4c29c0bfd49) 1.x (https://github.com/elastic/elasticsearch/commit/a351f4388497434786b735e467162ec14f719676) and 1.6 (https://github.com/elastic/elasticsearch/commit/a647e1a702b901cafdb4e7c362e4ef1193854772)

**Pull request closed without merging**
