### PR TITLE
Allow index and data stream aliases to share the same alias name.

### PR DESCRIPTION
**Pull request by martijnvg**
Relates to #66163

### CODE REVIEW

**Comment by dakrone** [comment]
@martijnvg is this one missing something to be in the draft state?

**Comment by dakrone** [comment]
@elasticsearchmachine update branch

**Comment by martijnvg** [comment]
I opened this PR in draft mode, because mainly I wanted this approach to be validated by someone else as well.
Also I think this change needs tests and of course the PR build needs to pass :) . (it did when I opened the PR a while ago)

Currently a name needs to be unique across indices, data streams, index aliases and data stream aliases. Index aliases and data stream aliases are stored in different places in cluster state. What this change changes is that the same name can be used in data stream and index aliases. This way an expression can both expanded to index and data stream aliases and creating an index alias with the same name as a data stream alias is allowed (and visa versa).

**Comment by dakrone** [comment]
Cool, thanks for the background Martijn, I'm going to close this for now, and we will re-open it when we get back to the data stream alias work (which I hope to do sooner rather than later).

**Pull request closed without merging**
