### PR TITLE
Rollup job creation should support comma delimited index patterns

### LINKED ISSUE #45591: Rollup job creation fails when using comma delimitated indices/index patterns
I have two indices, `kibana_sample_data_logs` and `kibana_sample_data_flights`. Both of these indices have a date field `timestamp`.

Attempting to create a rollup job for both of these indices using comma delimitated pattern fails with different errors depending on if wildcards are used.

We should [document this limitation](https://www.elastic.co/guide/en/elasticsearch/reference/master/rollup-job-config.html#_logistical_details) more clearly by specifying that only a **single** index or index pattern is allowed. (Or enhance the feature to allow comma separated list 🙂, but I'm not sure if that enhancement is urgent? When @silne30 and I ran into this, it wasn't under real use case scenarios.)

**No wildcards**
```
PUT _rollup/job/test2
{
  "id": "test2",
  "index_pattern": "kibana_sample_data_logs,kibana_sample_data_flights",
  "rollup_index": "rollup_samples",
  "cron": "0 * * * * ?",
  "page_size": 1000,
  "groups": {
    "date_histogram": {
      "interval": "2h",
      "delay": "1d",
      "time_zone": "UTC",
      "field": "timestamp"
    }
  }
}
```
fails with
```
[index_not_found_exception] no such index [kibana_sample_data_logs,kibana_sample_data_flights], with { resource.type="index_or_alias" & resource.id="kibana_sample_data_logs,kibana_sample_data_flights" & index_uuid="_na_" & index="kibana_sample_data_logs,kibana_sample_data_flights" }
```

**With wildcards**
```
PUT _rollup/job/test2
{
  "id": "test2",
  "index_pattern": "*data_logs,*data_flights",
  "rollup_index": "rollup_samples",
  "cron": "0 * * * * ?",
  "page_size": 1000,
  "groups": {
    "date_histogram": {
      "interval": "2h",
      "delay": "1d",
      "time_zone": "UTC",
      "field": "@timestamp"
    }
  }
}
```
fails with
```
[rollup_action_request_validation_exception] Validation Failed: 1: Could not find any fields in the index/index-pattern that were configured in job;
```

### PR DESCRIPTION
**Pull request by alexshadow007**
Closes #45591

### CODE REVIEW

**Comment by polyfractal** [comment]
Thanks @alexshadow007! Had a quick look, think the current changes look good.

I think we'll probably want to extend this change a bit.  E.g. in RollupJobConfig's constructor (and the client version of `RollupJobConfig#validate()`) we check to make sure the index pattern isn't `_all` or `*`, that it doesn't match the rollup index, etc.  So we'll probably want to incorporate this change there, so that someone can't do `_all,_all`.

I think there are a few other places that use the index pattern directly too.

Perhaps we should just remove `getIndexPattern()` and only allow fetching the array of strings (and all the associated changes needed to support that)?

**Comment by alexshadow007** [comment]
Hi, @polyfractal.
What about rollup job capabillities. According to documentation
```
So while the index belongs to the pattern, the rollup job is only valid across the entirety of the pattern not just one of it’s containing indices. So for that reason, the Rollup Capabilities API only returns information based on the originally configured index name or pattern.
``` 
we must verify rollup job capabillities against original index pattern not array of strings.

**Comment by alexshadow007** [comment]
@polyfractal Updated PR

**Comment by alexshadow007** [comment]
@polyfractal ping

**Comment by alexshadow007** [comment]
@polyfractal ping

**Comment by alexshadow007** [comment]
@polyfractal ping

**Comment by polyfractal** [comment]
Hi @alexshadow007, apologies for neglecting this PR :(  Been busy around here, and it slipped off my radar.  I'll try to get this reviewed this week so we can get it moving again.

Sorry for the delay!

**Comment by cuff-links** [comment]
@alexshadow007 Is there something further that this needs?

**Comment by cuff-links** [comment]
@polyfractal Hey. This has been sitting waiting to be murged a while. Not sure if this should still be merged or not.

**Comment by cuff-links** [comment]
@polyfractal ^

**Comment by polyfractal** [comment]
Thanks for bugging me on this @cuff-links, my code time has been limited and I've been a bad community-PR steward in this case :(

Gonna fire up CI tests, we might need to merge in master too

@elasticmachine test this please

**Comment by polyfractal** [comment]
@elasticmachine update branch

**Comment by polyfractal** [comment]
@elasticmachine test this please

**Comment by polyfractal** [comment]
@elasticmachine test this please

**Comment by cuff-links** [comment]
@polyfractal We may need to update this one as there are conflicts now.

**Comment by cuff-links** [comment]
@polyfractal Should we close this issue and reopen if needed?

**Comment by csoulios** [comment]
@elasticmachine test this please

**Comment by csoulios** [comment]
@elasticmachine test this please

**Comment by csoulios** [comment]
@elasticmachine test this please

**Comment by csoulios** [comment]
@elasticmachine test this please

**Comment by csoulios** [comment]
This PR adds support for comma-delimited index patterns, a bug often reported by our users. 

@polyfractal  identified another problem that already existed. 

> I think we'll probably want to extend this change a bit. E.g. in RollupJobConfig's constructor ... we check to make sure the index pattern isn't `_all` or `*`, that it doesn't match the rollup index, etc. So we'll probably want to incorporate this change there, so that someone can't do `_all,_all`.

I think we should merge this PR and fix the problem of accidentaly matching the rollup index with a separate PR or just create a new bug issue to document this as a known issue.

I am adding the `team-discuss` label so that we discuss this with the team.

**Review by csoulios — COMMENTED** [review]
This PR adds support for comma-delimited index patterns, a bug often reported by our users. 

@polyfractal  identified another problem that already existed and never worked correctly.

> I think we'll probably want to extend this change a bit. E.g. in RollupJobConfig's constructor ... we check to make sure the index pattern isn't `_all` or `*`, that it doesn't match the rollup index, etc. So we'll probably want to incorporate this change there, so that someone can't do `_all,_all`.

I think we should merge this PR and fix the problem of accidentaly matching the rollup index with a separate PR or just create a new bug issue to document this as a known issue.

I am adding the `team-discuss` label so that we discuss this with the team.

**Comment by csoulios** [comment]
@elasticmachine update branch

**Comment by csoulios** [comment]
@elasticmachine test this please

**Review by csoulios — APPROVED** [review]
The change LGTM!

Regarding this comment:

> I think we'll probably want to extend this change a bit. E.g. in RollupJobConfig's constructor (and the client version of RollupJobConfig#validate()) we check to make sure the index pattern isn't _all or *, that it doesn't match the rollup index, etc. So we'll probably want to incorporate this change there, so that someone can't do _all,_all.

This is a problem we already have without support for comma delimeted index patterns. Nothing stops a user from setting `_all`. I think we should deal with this problem in another PR. Since the lack of support for comma delimited index patterns has been reported multiple times, I will go ahead and merge the PR.

**Comment by csoulios** [comment]
@alexshadow007 thank you for this contribution and apologies for delay

@cuff-links thank you for bringing this to our attention

**Pull request merged**
