### PR TITLE
deprecate percolate in api spec

### PR DESCRIPTION
**Pull request by roelandvanbatenburg**
As requested in https://github.com/elastic/elasticsearch-js/pull/713

### CODE REVIEW

**Comment by mayya-sharipova** [comment]
@nik9000 Nik, I would like to get your advice - what is a way we want to indicate that certain endpoint/fields are deprecated in the REST API speciations?  Do we want to you a new api versioning for that?

**Comment by nik9000** [comment]
> I would like to get your advice - what is a way we want to indicate that certain endpoint/fields are deprecated in the REST API speciations?

I don't know! I'm asking some clients folks to see if they have any preference. I suspect we don't have a standard.

>  Do we want to you a new api versioning for that?

I don't think we need anything fancy for this because it is against 5.6.

**Comment by mayya-sharipova** [comment]
Adding a "discuss" label to discuss with the team how to indicate in the REST API specifications that an API is deprecated.

**Comment by javanna** [comment]
@mayya-sharipova can you remind me if we discussed this? What is the plan with this PR? Thanks!

**Comment by mayya-sharipova** [comment]
@javanna  We have not yet finalized the standards for documenting deprecated REST API. I will mark #35262 for discuss in the next fixit Friday.

**Comment by romseygeek** [comment]
The `percolate` endpoints are long gone from both elasticsearch and the rest api spec, so we can close this.

**Pull request closed without merging**
