### PR TITLE
[Transform] fix sporadic test failure due to unavailable notification index

### LINKED ISSUE #54810: [CI] TransformConfigurationIndexIT.testDeleteConfigurationLeftOver failures
Jenkins: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+7.7+matrix-java-periodic/ES_RUNTIME_JAVA=openjdk14,nodes=general-purpose/23/console

Build scan: https://gradle-enterprise.elastic.co/s/skpba3jxaypqk

Failure:

```
org.elasticsearch.client.ResponseException: 
method [GET], host [http://[::1]:46410], URI [.transform-notifications-000002/_search?ignore_unavailable=true], status line [HTTP/1.1 503 Service Unavailable]
{"error":{"root_cause":[],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[]},"status":503}

at __randomizedtesting.SeedInfo.seed([61CEE881B62A7B54:3FFF0103521740CE]:0)
at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:283)
at org.elasticsearch.client.RestClient.performRequest(RestClient.java:261)
at org.elasticsearch.client.RestClient.performRequest(RestClient.java:267)
at org.elasticsearch.client.RestClient.performRequest(RestClient.java:235)
at org.elasticsearch.xpack.transform.integration.TransformRestTestCase.logAudits(TransformRestTestCase.java:506)
at org.elasticsearch.xpack.transform.integration.TransformRestTestCase.waitForTransform(TransformRestTestCase.java:383)
```

Reproduce with:

```
./gradlew ':x-pack:plugin:transform:qa:single-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.transform.integration.TransformConfigurationIndexIT.testDeleteConfigurationLeftOver" -Dtests.seed=61CEE881B62A7B54 -Dtests.security.manager=true -Dtests.locale=ar -Dtests.timezone=Pacific/Guam -Dcompiler.java=13
HomeTestsorg.elasticsearch.xpack.transform.integration.TransformConfigurationIndexIT » testDeleteConfigurationLeftOver
```

Cannot reproduce locally.

### PR DESCRIPTION
**Pull request by hendrikmuhs**
move no initializing shards check before dumping audit messages

fixes #54810

### CODE REVIEW

**Comment by hendrikmuhs** [comment]
run elasticsearch-ci/bwc

**Review by przemekwitek — APPROVED** [review]
LGTM

**Comment by hendrikmuhs** [comment]
run elasticsearch-ci/bwc

**Comment by hendrikmuhs** [comment]
run elasticsearch-ci/bwc

**Comment by hendrikmuhs** [comment]
@elasticmachine update branch

**Comment by hendrikmuhs** [comment]
@elasticmachine update branch

**Comment by hendrikmuhs** [comment]
@elasticmachine update branch

**Comment by hendrikmuhs** [comment]
run elasticsearch-ci/2

**Pull request merged**
