### PR TITLE
Upgrade to lucene-8.7.0-snapshot-72d8528c3a6

### PR DESCRIPTION
**Pull request by iverase**
Upgrade to new lucene snapshot.

### CODE REVIEW

**Review by jpountz — APPROVED** [review]

**Comment by iverase** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by iverase** [comment]
elasticmachine run elasticsearch-ci/1

**Comment by iverase** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by iverase** [comment]
@elasticmachine run elasticsearch-ci/1

**Pull request merged**
