### PR TITLE
Remove obsolete version check for autoid creates

### PR DESCRIPTION
**Pull request by thecoop**
8.x can only connect to 7.17, so this version check is obsolete

### CODE REVIEW

**Comment by henningandersen** [comment]
Looks like this duplicates work in #101605 ?

**Comment by joegallo** [comment]
To the extent that this duplicates work, I think this version of the work is the superior one (mine was very naive and mechnical, this version is more a meaningful change). I'm happy to eat the merge/rebase overload and have this one be merged first.

**Comment by joegallo** [comment]
@elasticmachine update branch

**Review by kingherc — APPROVED** [review]
LGTM

**Comment by thecoop** [comment]
@elasticmachine update branch

**Pull request merged**
