### PR TITLE
Log default locale at node startup

### PR DESCRIPTION
**Pull request by ChrisHegarty**
This commit logs the default locale at node startup. This is useful when diagnosing issues, like string and char conversions, that may be affected by the default locale. Or even to help determine if compact strings may be in use.

### CODE REVIEW

**Comment by ChrisHegarty** [comment]
@elasticmachine update branch

**Comment by ChrisHegarty** [comment]
@elasticmachine update branch

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by ChrisHegarty** [comment]
This commit logs the default locale at node startup. 

This is useful when diagnosing issues, like string and char conversions, that may be affected by the default locale. Or even to help determine if compact strings may be in use.

**Pull request merged**
