### PR TITLE
Convert some action.execute cases to using NodeClient

### PR DESCRIPTION
**Pull request by rjernst**
There are several cases where execute is called on actions directly,
mostly within other action implementations. Now that transport client is
gone, these internal actions can be registered just like normal actions,
and called with the NodeClient to execute locally on the same node. This
commit converts a few of these cases for shard level actions to use this
approach.

### CODE REVIEW

**Comment by rjernst** [comment]
Note that I added a simpler base Action class simply called Action2, which forces the newer pattern of implementing Writeable for the Response class. I could not come up with some non confusing name, so I went with a simple number suffix. I think this new class will simplify boilerplate (much easier to create an instance without creating a new class) and assist with the conversion to Writeable, and they can be collapsed together once that work is complete.

**Comment by rjernst** [comment]
@elasticmachine run elasticsearch-ci/2

**Review by imotov — COMMENTED** [review]
Do you think it might be more helpful to remove `newResponse()` from `Action` and create a deprecated `MutableResponseAction` inheriting from `Action` that implements  `newResponse()` and switch 50+ actions that are not currently overriding `getResponseReader()` to use this `MutableResponseAction` instead of `Action`? This way it will be very clear that `MutableResponseAction` is deprecated and shouldn't be used and it will provide a nice TODO list for handling refactoring - all you have to do is to check `MutableResponseAction` hierarchy.

**Comment by rjernst** [comment]
I like that idea a lot. Are you ok with it as a follow-up? This PR going in doesn't really add any more meaningful work to that refactoring.

**Review by imotov — APPROVED** [review]
Yes, doing it as a follow-up is ok. As long as some called `Action2` doesn't live there for to long I am ok with it. But if it stays, I would like to come up with a better name :D

**Pull request merged**
