### PR TITLE
Rename CONF_DIR to ES_PATH_CONF

### LINKED ISSUE #26154: Rename CONF_DIR to ES_PATH_CONF
The environment variable `CONF_DIR` was previously inconsistently used in our packaging to customize the location of Elasticsearch configuration files. The importance of this environment variable has increased starting in 6.0.0 as it's now used consistently to ensure Elasticsearch and all secondary scripts (e.g., `elasticsearch-keystore`) all use the same configuration. The name `CONF_DIR` is there for legacy reasons yet it's too generic. This issue proposes renaming `CONF_DIR` to `ES_PATH_CONF` for 6.0.0. This would be a breaking change but it's a smaller break now than it would be in the future after this environment variable becomes baked-in through the ecosystem.

### PR DESCRIPTION
**Pull request by jasontedor**
The environment variable CONF_DIR was previously inconsistently used in our packaging to customize the location of Elasticsearch configuration files. The importance of this environment variable has increased starting in 6.0.0 as it's now used consistently to ensure Elasticsearch and all secondary scripts (e.g., elasticsearch-keystore) all use the same configuration. The name CONF_DIR is there for legacy reasons yet it's too generic. This commit renames CONF_DIR to ES_PATH_CONF.

Closes #26154

### CODE REVIEW

**Comment by sophiec20** [comment]
cc @lcawl Please check if this has documentation implications across the many books and wip.

**Comment by rjernst** [comment]
I understand the reasoning for calling it `ES_PATH_CONF` (to match the former `--path.conf` and/or `path.conf` settings), but since this is a new env var, I think we should make it make sense on its own. I also think using "path" is confusing, as we used to have the env var for the ES config file, so I would keep "dir" in the name. Thus I propose `ES_CONF_DIR`.

**Comment by jasontedor** [comment]
I think the place to discuss the name was on the issue: #26154. It was already agreed that `ES_PATH_CONF` is okay.

**Comment by rjernst** [comment]
> I think the place to discuss the name was on the issue: #26154. It was already agreed

That was agreed on fix it friday, which I was not a part of, and I did not see this issue until now. I am happy to comment on the issue instead of the PR, but stating that the name cannot be discussed because there was already "prior agreement" seems rather rigid for no reason (this name has not been committed, yet alone released), and is also counter to the notion that something "decided" in fix it friday can always be discussed afterwards, since not everyone can be present.

**Comment by jasontedor** [comment]
I did not say nor imply that it can not be discussed: I'm merely saying the name was already discussed and the context is on that issue. I welcome your thoughts there.

**Comment by lcawl** [comment]
@sophiec20 Thanks for the cc. CONF_DIR is used in both the Elasticsearch Reference and the X-Pack Reference, so when the new name is finalized we'll need to update about 8 pages in the former and about 2 in the latter.

**Review by rjernst — APPROVED** [review]
> I feel strongly that ES_PATH_CONF is the right name

I don't feel that strongly. LGTM.

**Comment by jasontedor** [comment]
Thanks @rjernst.

**Comment by jasontedor** [comment]
@lcawl They were already addressed by this PR and a sibling PR for X-Pack.

**Comment by javasgl** [comment]
elasticsearch version : 6.0.0 
when start es , `bin/elastcsearch -EES_PATH_CONF= /path/to/my/config` dont`t work

**Comment by jasontedor** [comment]
@javasgl Please check the [docs](https://www.elastic.co/guide/en/elasticsearch/reference/6.0/settings.html#config-files-location); `ES_PATH_CONF` is not a setting, it is an environment variable.

**Pull request merged**
