### PR TITLE
Two speedups to IndexNameExpressionResolver

### PR DESCRIPTION
**Pull request by original-brownbear**
Two obvious speedups to the IndexNameExpressionResolver where we can defer an expensive lookup from either the indices lookup or the thread context to if and when we actually need it.

### CODE REVIEW

**Review by nielsbauman — APPROVED** [review]
LGTM, thanks @original-brownbear!

**Comment by original-brownbear** [comment]
npnp + thanks Niels!

**Comment by original-brownbear** [comment]
@elasticmachine update branch

**Comment by original-brownbear** [comment]
Thanks Niels!

**Pull request merged**
