### PR TITLE
Check array size before returning array item in script doc values

### LINKED ISSUE #104998: [Script fields] Using script fields to get the second value of an array in a document may get the value in the previous document.
### Elasticsearch Version

elasticsearch8.11

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

centos7

### Problem Description

When all test documents are in the same segment, using script fields to get the second value of an array in a document,
the previous doc has a field named domain_id with value [1, 8], the next doc has the field which has the value [1]
when use
```
"script_fields": {
	"val": {
		"script": {
			"source": "doc.domain_id.values[1]",
			"lang": "painless"
		}
	}
}
```
to get domain_id's second value, the result is 8,8, but 8,0 is right.

### Steps to Reproduce

1、create an index as follows
```
PUT localhost:9200/test
{
	"settings": {
		"refresh_interval": "120s",#ensure all documents is written to the same segment "number_of_shards": 1,
		"number_of_replicas": 0
	},
	"mappings": {
		"arrays": {
			"dynamic": false,
			"properties": {
				"domain_id": {
					"type": "integer"
				}
			}
		}
	}
}

```
2、write some data
```
PUT localhost:9200/_bulk
{ "index" : { "_index" : "test", "_type": "arrays", "_id": 1}}
{"domain_id":[1]}
{ "index" : { "_index" : "test", "_type": "arrays", "_id": 2}}
{"domain_id":[1]}
{ "index" : { "_index" : "test", "_type": "arrays", "_id": 3}}
{"domain_id":[2]}
{ "index" : { "_index" : "test", "_type": "arrays", "_id": 4}}
{"domain_id":[3]}
{ "index" : { "_index" : "test", "_type": "arrays", "_id": 5}}
{"domain_id":[1]}
{ "index" : { "_index" : "test", "_type": "arrays", "_id": 6}}
{"domain_id":[1]}
{ "index" : { "_index" : "test", "_type": "arrays", "_id": 7}}
{"domain_id":[1,8]}
{ "index" : { "_index" : "test", "_type": "arrays", "_id": 8}}
{"domain_id":[1]}
{ "index" : { "_index" : "test", "_type": "arrays", "_id": 9}}
{"domain_id":[1]}
```

3、execute the query
```
GET localhost:9200/test/_search
{
	"_source": "domain_id",
	"script_fields": {
		"val": {
			"script": {
				"source": "doc.domain_id[1]",
				"lang": "painless"
			}
		}
	}
}
```

4、the result is wrong
```
{
	"took": 105,
	{
		"_index": "test3",
		"_type": "arrays",
		"_id": "6",
		"_score": 1.0,
		"_source": {
			"domain_id": [
				1
			]
		},
		"fields": {
			"val": [
				0
			]
		}
	},
	{
		"_index": "test3",
		"_type": "arrays",
		"_id": "7",
		"_score": 1.0,
		"_source": {
			"domain_id": [
				1,
				8
			]
		},
		"fields": {
			"val": [
				8
			]
		}
	},
	{
		"_index": "test3",
		"_type": "arrays",
		"_id": "8",
		"_score": 1.0,
		"_source": {
			"domain_id": [
				1
			]
		},
		"fields": {
			"val": [
				8
			]
		}
	}
}
```
.....
the result in the last hit should be 0,but 8,we think it uses the previous hit result.
### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by javanna**
When accessing array elements from a script, if the backing array has enough items, meaning that there has previously been a doc with enough values, we let the request go through, and we end up returning items from the previous doc that had a value at that position if the current doc does not have enough elements.

We should instead validate the length of the array for the current doc and eventually throw an error if the index goes over the available number of values.

Closes #104998

### CODE REVIEW

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by javanna** [comment]
Thanks @rjernst for the review. I was wondering if as a follow-up, we should consider as a safety measure, zero-ing the array elements beyond the docValuesCount for the current doc. What do you think?

**Comment by ldematte** [comment]
>I was wondering if as a follow-up, we should consider as a safety measure, zero-ing the array elements beyond the docValuesCount for the current doc. What do you think?

As a general concept I like the idea, but I'm wondering if this is really useful - we should not be able to read beyond docValuesCount anymore, right? So we would never read the 0-ed array elements.

**Comment by javanna** [comment]
> As a general concept I like the idea, but I'm wondering if this is really useful - we should not be able to read beyond docValuesCount anymore, right? So we would never read the 0-ed array elements.

Correct, but we rely on the assumption that we have added, and we will keep, the check in all the possible scenarios where we call getInternal. That is perhaps fragile. An alternative is to check at a lower level as well, but that requires changing all the implementations of `getInternal`, whether that be to zero array elements or check the index argument.

**Comment by rjernst** [comment]
I would be concerned with the cost of zeroing between documents, it seems like it could be significant over queries with a lot of matches?

**Comment by javanna** [comment]
> I would be concerned with the cost of zeroing between documents, it seems like it could be significant over queries with a lot of matches?

Yes, that is a true as well. Let's leave things as they are then.

**Pull request merged**
