### PR TITLE
Change Lucene Snapshot example for 7.0.0

### PR DESCRIPTION
**Pull request by dadoonet**
That's a change proposal just to update to a more recent version our example.

### CODE REVIEW

**Review by cbuescher — APPROVED** [review]
Great idea I think! LGTM

**Comment by dadoonet** [comment]
@cbuescher Is it ok to merge even though CI is complaining?

**Comment by cbuescher** [comment]
> Is it ok to merge even though CI is complaining?

I don't see how the current failure could be caused by this change, but I'd still prefer to re-run it (potentially with merging in master, but master-intake seems a bit broken right now). I'd rather wait a bit until master is stable again, merge it in and then re-run, even though in this case it seems unproblematic, just to avoid accidentally pushing anything broken to an already broken master. I can later re-check and merge in master if you don't want to monitor it today if that helps.

**Comment by cbuescher** [comment]
@dadoonet just merged in master lets see if CI likes it better ;-) Btw, I was suprised to see this is on a branch in the elasticsearch repo, not your private one, was that intentional? Just asking out of curiosity.

**Pull request merged**
