### PR TITLE
Bool query early termination should also consider must_not clauses

### PR DESCRIPTION
**Pull request by piergm**
We early terminate a bool query re-write if we have 0 must clauses, 0 filters, all should clauses that can be rewritten to match_none and, with this PR, if we have 0 must_not clauses.

If this is not the case we continue with the rewrite logic and check if the bool clauses could be rewritten to match none (or all for must_not).

### CODE REVIEW

**Review by andreidan — APPROVED** [review]
Thanks for fixing this Matteo!

LGTM

**Comment by piergm** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.16|[](https://github.com/elastic/elasticsearch/pull/115067)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Comment by javanna** [comment]
Thanks! This needs to be backported to 8x as well, hence I added the 8.17 label.

**Comment by piergm** [comment]
You are right, created, thanks @javanna!

**Pull request merged**
