### PR TITLE
Provide 'system' attribute when resolving system indices

### LINKED ISSUE #82671: GET /_resolve/index should identify system indices
**Elasticsearch version** 8.1

**Kibana version**: 8.1

When creating an SLM policy, kibana currently calls the `GET /_resolve/index` to allow the users to select which indices they want to backup (this API includes system indices). It seems that there's no way right now of making this API resolve only non-system indices. And if a user were to select one of these system indices the following error would be returned from ES:

```
the [indices] parameter includes system indices [.kibana_8.1.0_001]; to include or exclude system indices from a snapshot, use the [include_global_state] or [feature_states] parameters
```

<details>
<summary>API calls for testing</summary>

```
# create repository
PUT /_snapshot/my_backup
{
  "type": "fs",
  "settings": {
    "location": "/tmp/es-backups",
    "chunk_size": "10mb"
  }
}

# create policy
PUT _slm/policy/test-policy
{
  "name": "test-snapshot",
  "schedule": "0 30 1 * * ?",
  "repository": "my_backup",
  "config": {
    "indices": [
      ".kibana_8.1.0_001",
      "kibana_sample_data_flights"
    ]
  }
}

# executing the previous policy should fail
POST _slm/policy/test-policy/_execute
GET _slm/policy/test-policy
```
</details>

### PR DESCRIPTION
**Pull request by williamrandolph**
If a user is able to view system indices, they will see system indices in relevant results from the `GET _resolve/indices/*` endpoint. However, they may be limited in how they can use those indices. This PR adds a new "attribute" to the results of a call to that endpoint that will identify system indices.

```
$ curl --user elastic:password 'localhost:9200/_resolve/index/.s*' | jq '.'

{
  "indices": [
    {
      "name": ".security-7",
      "aliases": [
        ".security"
      ],
      "attributes": [
        "hidden",
        "open",
        "system"
      ]
    }
  ],
  "aliases": [
    {
      "name": ".security",
      "indices": [
        ".security-7"
      ]
    }
  ],
  "data_streams": []
}
```

Fixes #82671

### CODE REVIEW

**Review by sabarasaba — APPROVED** [review]
Output of the api as in the PR description lgtm, haven't tested locally. I was wondering whether it makes sense to also update the api docs in order to include this new attribute?

**Review by grcevski — COMMENTED** [review]
This looks good to me!

Does it make sense for us to add a YML test that checks this attribute to ensure we truly get this back in a REST response?

**Comment by williamrandolph** [comment]
@grcevski @sabarasaba I've added some documentation and a yaml rest test. How does it look?

**Comment by sabarasaba** [comment]
docs look good, thanks @williamrandolph!

**Review by grcevski — APPROVED** [review]
Looks great! Thanks

**Pull request merged**
