### PR TITLE
Cluster state role mapper file settings service

### PR DESCRIPTION
**Pull request by albertzaharovits**
Note: Currently, this PR includes the changes from https://github.com/elastic/elasticsearch/pull/107410 (which introduces the `ClusterStateRoleMapper`). This is simpler to review **after** #107410 is merged in.

This PR simplifies the `ReservedRoleMappingAction` implementation, which is part of the `FileSettingsService` infrastructure, such that it stores the role mappings it parses from the `settings.json` file into the cluster state custom metadata that's used by the new `ClusterStateRoleMapper`. The native role mappings (stored in the .security index)
are left untouched by the `ReservedRoleMappingAction`.

### CODE REVIEW

**Review by rjernst — APPROVED** [review]
The changes to ReservedRoleMappingAction LGTM.

**Review by AthenaEryma — APPROVED** [review]
LGTM, thanks!

**Comment by albertzaharovits** [comment]
@elasticsearchmachine run elasticsearch-ci/part-4-fips

**Comment by albertzaharovits** [comment]
@elasticsearchmachine test elasticsearch-ci/part-4-fips

**Comment by albertzaharovits** [comment]
@elasticsearchmachine run elasticsearch-ci/part-4

**Comment by albertzaharovits** [comment]
@elasticsearchmachine test this please

**Comment by DaveCTurner** [comment]
Reverting this, hopefully temporarily, in https://github.com/elastic/elasticsearch/pull/108346. It's not that this change is bad, but it's exposing a bug in the file-based settings service that we need to fix first.

**Pull request merged**
