### PR TITLE
Add is_write_index column to cat.aliases

### PR DESCRIPTION
**Pull request by talevy**
Aliases have had the option to set `is_write_index` since 6.4,
but the cat.aliases action was never updated.

example:

```
alias            index                              filter routing.index routing.search  is_write_index
filebeat-7.0.1   filebeat-7.0.1-2019.07.23-000011   -      -             -               -
metricbeat-7.0.1 metricbeat-7.0.1-2019.07.23-000005 -      -             -               true
metricbeat-7.0.1 metricbeat-7.0.1-2019.07.21-000003 -      -             -               false
```

### CODE REVIEW

**Review by AthenaEryma — APPROVED** [review]
LGTM (assuming CI is happy), thanks @talevy!

**Comment by talevy** [comment]
run elasticsearch-ci/bwc

**Review by AthenaEryma — APPROVED** [review]
Still LGTM - I don't love the duplication of the test cases, but I don't know of a better way to do it either.

**Comment by talevy** [comment]
thanks Gordon

run elasticsearch-ci/bwc
run elasticsearch-ci/default-distro

**Pull request merged**
