### PR TITLE
Move construction of custom analyzers into AnalysisRegistry

### PR DESCRIPTION
**Pull request by romseygeek**
Both `TransportAnalyzeAction` and `CategorizationAnalyzer` have logic to build
custom analyzers for index-independent analysis.  A lot of this code is duplicated,
and it requires the `AnalysisRegistry` to expose a number of internal provider 
classes, as well as making some assumptions about when analysis components are
constructed.

This commit moves the build logic directly into `AnalysisRegistry`, reducing the
registry's API surface considerably.  This should free us up to make loading of
analysis components lazy, helping with #42349

### CODE REVIEW

**Comment by romseygeek** [comment]
The changes in AnalysisRegistry have altered the name given to custom-built components from `_anonymous_[component-type]` to `__anonymous__[implementation]`, which is why the BWC tests are failing - it's expecting `_anonymous_tokenfilter` and instead getting `__anonymous__stop`.  I think the latter is more informative, and it's also purely an implementation detail, so I'm minded to just remove the name check from the BWC rest test.

**Review by droberts195 — COMMENTED** [review]
This looks much better in terms of code duplication - thanks for rationalising it!

Obviously the only worry here is whether the ML categorization configs created in older versions will still work in mixed version clusters via wire serialization and when reloaded from the config index.  I could not see any reason why these things wouldn't work but I realised we don't have any tests that prove it.  I have just added some in #42981.  Therefore, would you mind waiting until that PR is merged and then merge master into this PR to pick it up and run one more PR CI cycle with categorization config BWC test coverage?

**Comment by romseygeek** [comment]
> would you mind waiting until that PR is merged and then merge master into this PR

No problem, and thanks for the review.

**Review by droberts195 — APPROVED** [review]
LGTM assuming the BWC tests pass

**Comment by romseygeek** [comment]
@elasticmachine update branch

**Comment by romseygeek** [comment]
Time out in the docs tests, looks like a node just took too long to come up

@elasticmachine run elasticsearch-ci/1

**Pull request merged**
