### PR TITLE
Move `BulkItemRequest` BWC to 5.x

### PR DESCRIPTION
**Pull request by bleskes**
The current BWC code in `BulkItemRequest` mutates the underlying `DocWriteRequests` which causes test failures and unexpected state (our test infra checks bwc serialization on the fly). This PR removes this logic from master. Another PR will add a BWC layer to 5.x only.

This PR contains the logic in https://github.com/elastic/elasticsearch/pull/25510 , which is needed to run the tests.

### CODE REVIEW

**Review by dakrone — APPROVED** [review]
LGTM (with of course the 5.x counterpart)

**Comment by bleskes** [comment]
@jasontedor I also removed the version constant as requested.

**Comment by bleskes** [comment]
#25510 is merged. This is now clean. I will merge it as soon as #25512 gets approved.

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by bleskes** [comment]
Thx @jasontedor

**Pull request merged**
