### PR TITLE
Rename 'json' to 'embedded_json'.

### PR DESCRIPTION
**Pull request by jtibshirani**
A concern around the name `json` is that because the entire document is JSON,
new users may see this field and think that they should always use it. We
thought that a more verbose name like `embedded_json` would help convey that the
field type has a special, non-obvious purpose.

This commit updates documentation references to `embedded_json`, but leaves the
`JsonField` naming in the code to avoid very long class names.

### CODE REVIEW

**Comment by jtibshirani** [comment]
@elasticmachine run elasticsearch-ci/2 
@elasticmachine run elasticsearch-ci/bwc

**Review by jimczi — APPROVED** [review]
LGTM

**Comment by jtibshirani** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by jtibshirani** [comment]
Thanks @jimczi for the review.

**Pull request merged**
