### PR TITLE
Implement Lucene EstonianAnalyzer, Stemmer

### LINKED ISSUE #48895: [feature request] Implement Lucene Estonian analyzer in Elasticsearch
A new analyzer for the Estonian language was added in lucene-solr 8.x:
https://github.com/apache/lucene-solr/commit/2df6ea2305f5df77671e07bb3ad9b999818f9910
It would be nice to have this analyzer in Elasticsearch aswell.

### PR DESCRIPTION
**Pull request by gpaimla**
This PR adds a new analyzer and stemmer for the Estonian language.
Closes #48895

### CODE REVIEW

**Comment by gpaimla** [comment]
@elasticcla refresh

**Review by cbuescher — CHANGES_REQUESTED** [review]
Hi @gpaimla, thanks a lot for your contribution and adding this Lucene analyzer to ES. The change looks great to me in general. I have just one minor ask. Could you add the new analyzer to the documentation page for language analyzers over at `docs/reference/analysis/analyzers/lang-analyzer.asciidoc` and maybe add the stop word filter to `docs/reference/analysis/tokenfilters/stop-tokenfilter.asciidoc`?
For the language analyzer page please adapt one of the existing sections about how to reimplement the language analyzer for the case that users need to customize them. 
Thanks again, looking forward for these changes after which I will run our CI test suite on the change.

**Review by cbuescher — APPROVED** [review]
Great, thanks for the update. I will run the CI tests and merge if they pass or get back to you if the PR needs some more changes (which I doubt).

**Comment by cbuescher** [comment]
@elasticmachine test this please

**Comment by cbuescher** [comment]
Thanks again @gpaimla for working on this. I merged the PR to master and our 7.x branch which should be used for the 7.6 release.

**Pull request merged**
