### PR TITLE
DO NOT MERGE. Dummy change to trigger CI.

### PR DESCRIPTION
**Pull request by prdoyle**
TESTING TESTING TESTING

### CODE REVIEW

**Comment by prdoyle** [comment]
Thanks @ldematte for this: https://github.com/elastic/elasticsearch/pull/108490

**Comment by prdoyle** [comment]
Hmm I'm a bit confused.

[This build](https://buildkite.com/elastic/elasticsearch-pull-request/builds/26046), which contains errors, is based on SHA 154a78dfe2ba, which I think isn't the most relevant. I'll have to double check where that one came from.

[This build](https://buildkite.com/elastic/elasticsearch-pull-request/builds/26129) contains no errors, and is based on SHA 02f96060cae4, which is the one I meant to test, based on the latest `main`.

Based on that latter build, we might be able to conclude that this failure is no longer occurring. Perhaps it was already fixed upstream.

**Comment by prdoyle** [comment]
Running again on @rjernst's advice [here](https://github.com/elastic/elasticsearch/issues/108474#issuecomment-2233473505).

**Comment by prdoyle** [comment]
I'm not sure the change Ryan suggested is actually in `main` so this re-run probably isn't achieving much.

**Comment by rjernst** [comment]
Ah, I thought the mute in https://github.com/salvatore-campagna/elasticsearch/commit/34295b4aca30ece552cb66264a1efb08d85f9a46 was on main, but I see now it's just in Salvatore's fork...

**Comment by prdoyle** [comment]
buildkite test this

**Comment by prdoyle** [comment]
Ok @rjernst has [suggested](https://github.com/elastic/elasticsearch/issues/108474#issuecomment-2233760419) this might already be fixed up stream. Let's close it.

**Pull request closed without merging**
