### PR TITLE
Publish CI build scans to Gradle Enterprise

### PR DESCRIPTION
**Pull request by mark-vieira**
Update the CI Gradle init script such that build scans are configured to be published to our internal Gradle Enterprise instance.

### CODE REVIEW

**Comment by mark-vieira** [comment]
@elasticmachine run elasticsearch-ci/1

**Review by rjernst — APPROVED** [review]
Lgtm. No auth needed?

**Comment by mark-vieira** [comment]
No auth for publishing, only viewing.

**Review by alpar-t — COMMENTED** [review]
we could probably clean up the code to accept the ToC, maybe move all of that configuration here ?

**Comment by mark-vieira** [comment]
Yep, I'll open a separate PR to ditch the ToS stuff.

**Pull request merged**
