### PR TITLE
Remove legacy bootstrap plugins

### PR DESCRIPTION
**Pull request by rjernst**
Bootstrap plugins were an internal mechanism added to allow a
filesystemprovider for cloud with the quota-aware-fs plugin. Since that
was removed, bootstrap plugins no longer serve a purpose. They were
never officially documented because they were for internal use only.
This commit removes the bootstrap plugins infrastructure.

### CODE REVIEW

**Comment by rjernst** [comment]
Note that I have explicitly *not* marked this as breaking, because we were very explicit in never documenting this internal capability of plugins.

**Review by pugnascotia — COMMENTED** [review]
The changes look good but there's a number of CI failures to address.

**Comment by rjernst** [comment]
@pugnascotia The remaining CI failure is expected right now. The example plugin build is broken due to unrelated reasons.

**Review by pugnascotia — APPROVED** [review]

**Review by pugnascotia — APPROVED** [review]
Still LGTM

**Comment by rjernst** [comment]
@elasticmachine update branch

**Pull request merged**
