### PR TITLE
Core: Add backcompat for joda time formats

### PR DESCRIPTION
**Pull request by rjernst**
This commit adds deprecation warnings when using format specifiers with
joda data formats that will change with java time. It also adds the "8"
prefix which may be used to force the new java time format parsing.

### CODE REVIEW

**Comment by spinscale** [comment]
@elasticmachine retest this please

**Comment by spinscale** [comment]
Did a first pass, will do another one later today. 

On the danger of starting huge bike shedding: Do you think the `8` prefix is a good one? I think java8 is an implementation detail that noone needs to care about (and many of our non java users dont have an idea about that change). Would it make more sense to use `7` (for the major version upgrade) and also add an `_` to make it easier to, as long as underscores are used instead of camelcase for the format name?

**Comment by spinscale** [comment]
just to understand your argument above (seems my java time knowledge is fading again). The only time the remaining `yyyy` would be an issue, is when you are using that in combination with the weeks based dates, like `yyyy'W'ww`, correct?

**Comment by rjernst** [comment]
> Do you think the 8 prefix is a good one? I think java8 is an implementation detail that noone needs to care about

I think it is pertinent for users to know, in the same way they currently need to know it is joda time, so that they know what format specifiers are valid (by looking at the respective documentation).

> The only time the remaining yyyy would be an issue, is when you are using that in combination with the weeks based dates, like yyyy'W'ww, correct?

I don't think week has anything to do with it.  `yyyy` would be different than `uuuu` if you were printing dates before before year 0. For example, the year Julius caesar died would be -44 with `uuuu` and `44` with `yyyy`. It only comes up with looking at years in different eras.

**Review by spinscale — APPROVED** [review]
LGTM! Docs are needed for a small mention about the new `8` prefixed format, but that can easily be done in a separate PR.

**Pull request merged**
