### PR TITLE
QL: Move Node transform type argument to the front

### LINKED ISSUE #67174: QL: Improve readability of node rules by moving the type token in the front
Currently `Node` hierarchy allows for `typed` transformations using the signature `transform(Function<I,O> f, Class<I> token)`. In practice for non-trivial lambdas, the type token ends up at the end of the method call and thus unclear on the argument type.
Shifting the two arguments around improves readability as it's clear the type of node on which the lambda gets applied.

### PR DESCRIPTION
**Pull request by costin**
Improve readability of Node transform/forEach typed methods by moving
the "type token" to the front of the method, before the lambda
declaration.

Fix #67174

### CODE REVIEW

**Review by palesz — APPROVED** [review]
LGTM. (some extra whitespace changes, but those are fine)

**Review by bpintea — APPROVED** [review]
LGTM

**Comment by costin** [comment]
@elasticmachine run elasticsearch-ci/default-distro

**Comment by costin** [comment]
@elasticmachine update branch

**Pull request merged**
