### PR TITLE
add function submitDeleteByQueryTask in class RestHighLevelClient

### PR DESCRIPTION
**Pull request by qianyuxiang01**
add function submitDeleteByQueryTask in class RestHighLevelClient and an unit test for submitDeleteByQueryTask

### CODE REVIEW

**Comment by martijnvg** [comment]
@elasticmachine test this please

**Comment by martijnvg** [comment]
@qianyuxiang01 Thanks for working on this! This looks good to me. I will merge this when the build passes.

**Comment by martijnvg** [comment]
@qianyuxiang01 The check style task failed in the build:

```
13:08:15 > Task :client:rest-high-level:checkstyleMain FAILED
13:08:15 [ant:checkstyle] [ERROR] /run/shm/elastic+elasticsearch+pull-request-1/client/rest-high-level/src/main/java/org/elasticsearch/client/RequestConverters.java:576: Line is longer than 140 characters (found 145). [LineLength]
13:08:15 [ant:checkstyle] [ERROR] /run/shm/elastic+elasticsearch+pull-request-1/client/rest-high-level/src/main/java/org/elasticsearch/client/RestHighLevelClient.java:601: Line is longer than 140 characters (found 151). [LineLength]
```

Can you make sure that these lines are no longer than 140 characters? After you make the change you can run locally: `./gradlew -p client/rest-high-level/ precommit` to verify that checkstyle task succeeds.

**Comment by martijnvg** [comment]
@elasticmachine test this please

**Comment by martijnvg** [comment]
@qianyuxiang01 The `RequestConvertersTests.testDeleteByQuery(...)` fails. I think it needs to be modified to take into account that `wait_for_completion` param is now also provided. Could you make this change in this test?

**Comment by qianyuxiang01** [comment]
ok. I will fix this today




| |
钱宇翔
邮箱：qianyuxiang01@126.com
|

签名由 网易邮箱大师 定制

On 09/24/2019 01:57, Martijn van Groningen wrote:

@qianyuxiang01 The RequestConvertersTests.testDeleteByQuery(...) fails. I think it needs to be modified to take into account that wait_for_completion param is now also provided. Could you make this change in this test?

**Comment by martijnvg** [comment]
@elasticmachine test this please

**Comment by martijnvg** [comment]
@qianyuxiang01 Thanks for fixing the test. I've started a new build.

**Pull request merged**
