### PR TITLE
Upgrade to JNA 5.7.0-1

### PR DESCRIPTION
**Pull request by jasontedor**
This commit upgrades our JNA dependency to 5.7.0-1. The highlight of this upgrade is that the Darwin native libraries are now universal including support for both Intel-based and Apple Silicon-based Mac hardware.

### CODE REVIEW

**Comment by jasontedor** [comment]
This change means that our usage of JNA will now work on Apple Silicon Macs.

**Comment by jasontedor** [comment]
@elasticmachine update branch

**Review by mark-vieira — APPROVED** [review]
LGTM. This also reminds me we should probably move to using Gradle's built-in capability for [verifying dependency checksums](https://docs.gradle.org/current/userguide/dependency_verification.html#sec:checksum-verification).

**Comment by jasontedor** [comment]
@mark-vieira The [Windows failures](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+packaging-tests-windows-gcp/18/) on this change seem related to the removal of the OSS distribution and unrelated to this change. Therefore, I'm going to merge this change ignoring these failures. Is that okay with you? Is is this good enough to notify you of the need to evolve the Windows packaging jobs?

**Comment by mark-vieira** [comment]
The Windows failures being specific to the OSS variant is only coincidental. It looks like Jenkins lost contact with the workers on those builds and that was the root cause of the failure. Given those jobs are going away so we frankly don't care if the OSS distros are busted I'm :+1: on pushing forward.

**Pull request merged**
