### PR TITLE
Assert no exceptions during state application

### PR DESCRIPTION
**Pull request by DaveCTurner**
Today we log and swallow exceptions during cluster state application, but such
an exception should not occur. This commit adds assertions of this fact, and
updates the Javadocs to explain it.

Relates #47038

### CODE REVIEW

**Review by original-brownbear — APPROVED** [review]
LGTM, this makes a lot of sense to me :)

**Review by original-brownbear — DISMISSED** [review]
Seems this needs some test removal/adjustment still though, tests that are simulating exceptions in the CS applier fail now:

```
FDE 25, 2019 10:43:28 COMME com.carrotsearch.randomizedtesting.RandomizedRunner$QueueUncaughtExceptionsHandler uncaughtException
WARNING: Uncaught exception in thread: Thread[elasticsearch[test_node][clusterApplierService#updateTask][T#1],5,TGRP-ClusterApplierServiceTests]
java.lang.AssertionError
	at __randomizedtesting.SeedInfo.seed([FA241879CEA2DA83]:0)
	at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:452)
	at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:176)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:699)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by DaveCTurner** [comment]
Thanks @original-brownbear I would wait for a green CI run before looking too hard at this, in case it shakes out anything else.

**Comment by DaveCTurner** [comment]
Failure is unrelated, I opened #47098.

@elasticmachine please run elasticsearch-ci/1

**Review by original-brownbear — APPROVED** [review]
LGTM :)

It is a little weird though to test the case that we `assert` doesn't happen ever, but I can see how we still want to handle those exceptions properly and keep the coverage :)

**Pull request merged**
