### PR TITLE
[DOCS] TLS file resources are reloadable

### PR DESCRIPTION
**Pull request by jkakavas**
Make clearer that file resources that are used as key or trust material
are polled periodically and will be reloaded upon modification.

### CODE REVIEW

**Review by tvernum — APPROVED** [review]
👍

**Review by lcawl — APPROVED** [review]
I changed it from a note to an optional step.  If you're satisfied with this change, it LGTM

**Comment by tvernum** [comment]
I don't think we should be encouraging users to change the reload interval.
They _can_ change if needed, but this step reads as though it's a good idea to do so and I don't think that's true. 

Maybe the alternative is to have instructions on how to _update_ certs. 

_If you need to change your certificates (for example your hostnames change, or your certificates are due to expire) then ...._

**Comment by jkakavas** [comment]
I agree with @tvernum. The intention was to make users aware of a default behavior that they wouldn't - most probably - need to change. As such, it doesn't feel right to reference this only with regards to changing the default behavior. 

How about we introduce a small paragraph in https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html and/or mark the relevant settings as `(Reloadable)` in the same manner we do for `(Secure)` ?

**Comment by lcawl** [comment]
@jkakavas The use of the term "reloadable" with respect to settings is described here: https://www.elastic.co/guide/en/elasticsearch/reference/6.4/secure-settings.html i.e. they're settings that you can reload by using POST _nodes/reload_secure_settings.  It seems to me that's different than what we're talking about here, isn't it?  We can nonetheless add a comment to each setting. (Similar to what appears in the idp.metadata.path here: https://www.elastic.co/guide/en/elasticsearch/reference/6.4/security-settings.html#ref-saml-settings)

NOTE: if we don't want to encourage people to change the reload interval, it should likely be removed from the following places too:
https://www.elastic.co/guide/en/elastic-stack-overview/6.4/mapping-roles.html
https://www.elastic.co/guide/en/elasticsearch/reference/6.4/configuring-file-realm.html

**Comment by tvernum** [comment]
> if we don't want to encourage people to change the reload interval, it should likely be removed from the following places too:

I'm quite happy for those to be revised as well, but the difference to my reading is that they explain that you _can_ change this if you have a reason to, but the new proposed wording suggested that it might be a good idea to do so when setting up TLS for the first time.
I easily envisage users changing that setting to a very small or very large time period, getting themselves into trouble, and then rightly asking us _why_ we advised them to change it as part of TLS setup.


> The use of the term "reloadable" with respect to settings is ... (big snip) ... different than what we're talking about here, isn't it?

I agree. I think it would be misleading to describe these settings as reloadable. We don't reload the _setting_; you cannot change the yml file (or call an API) to point at a new certificate path (/keystore/etc), but we will reload the contents of those files if they change.

**Comment by lcawl** [comment]
Thanks for the clarification!  I've reverted to a bulleted list of notes and added in Tim's examples of when you might want to update the files.

**Comment by jkakavas** [comment]
git merging woes. I'll close this and reopen since I believe it is the easiest way to clean up.

**Pull request closed without merging**
