### PR TITLE
Only include relevant platform files from modules

### PR DESCRIPTION
**Pull request by rjernst**
This commit adds a filter to the files include from modules to only
include platform specific files relevant to the distribution being
built. For example, the deb files on linux would now only include linux
ML binaries, and not windows or macos files.

### CODE REVIEW

**Comment by rjernst** [comment]
@elasticmachine run elasticsearch-ci/packaging

**Comment by rjernst** [comment]
@elasticmachine run elasticsearch-ci/oss-distro-docs

**Review by alpar-t — COMMENTED** [review]
LGTM 

Would be nice to check this in some packaging tests.

**Review by alpar-t — APPROVED** [review]

**Review by jaymode — APPROVED** [review]

**Comment by rjernst** [comment]
@elasticmachine run elasticsearch-ci/1

**Pull request merged**
