### PR TITLE
Update disk-usage.asciidoc

### PR DESCRIPTION
**Pull request by vanessa-bell**
Grammar - change less to fewer.

### CODE REVIEW

**Review by cbuescher — APPROVED** [review]
Hi @vanessa-bell, makes sense and sounds better to me. 
Would you please sign our CLA so I can merge this? Unfortunately we need it also for documentation changes.

**Comment by vanessa-bell** [comment]
Hi @cbuescher - thought I did that already, but just signed again!

**Comment by cbuescher** [comment]
Thanks.
@elasticmachine test this please

**Comment by cbuescher** [comment]
@vanessa-bell thanks, I merged to 7.6 and newer branches.

**Pull request merged**
