### PR TITLE
Upgrade to lucene- 8.7.0-snapshot-66c49a35402

### PR DESCRIPTION
**Pull request by mayya-sharipova**
This includes fixing a bug in doc iteration during sort optimization

Backport for #63349

### CODE REVIEW

**Comment by mayya-sharipova** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by mayya-sharipova** [comment]
@elasticsearch-ci/2 takes a lot of time, and often fails due to timeouts. Given this is a backport, I will merge PR without @elasticsearch-ci/2 passing.

**Comment by droberts195** [comment]
> @elasticsearch-ci/2 takes a lot of time, and often fails due to timeouts

I think it is the upgrade to lucene-8.7.0-snapshot-66c49a35402 that is causing the timeouts.  There is an analysis of the pattern of failures in https://github.com/elastic/elasticsearch/issues/63379#issuecomment-704781965.

**Comment by mayya-sharipova** [comment]
@droberts195  We have fixed a bug in Lucene, and currently building a new Lucene snapshot for ugprade.

**Pull request merged**
