### PR TITLE
Fix sort values coming from unrelated documents in certain multi-level sorts #31554

### PR DESCRIPTION
**Pull request by dbevacqua**
Root filter of `Nested` returned from `SortBuilder` produces no docs due to incorrect `MUST` clause. By removing it and just using `ToParentBlockJoinQuery` on its own the correct docs are produced.

### CODE REVIEW

**Comment by martijnvg** [comment]
test this please

**Comment by dbevacqua** [comment]
@martijnvg done (though no new build so far...)

**Comment by martijnvg** [comment]
test this please

**Comment by martijnvg** [comment]
@dbevacqua Thanks! I'm going to add some more tests, so that there is more test coverage for multi level nested sorting. Right now that test coverage is poor. I think your fix is good, but having more tests should also increase confidence in this fix and whether multi level nested sorting is actual working.

**Comment by martijnvg** [comment]
test this please

**Comment by martijnvg** [comment]
@jpountz Would you like to take a look at this when you have time?

**Comment by jimczi** [comment]
I am very sorry @dbevacqua, I tried to push to your branch to update this pr like @martijnvg did but I made something wrong and the pr got closed automatically. We discussed with @martijnvg about a simplification that should also fix https://github.com/elastic/elasticsearch/issues/31783.
I opened a new pr with your commits and this additional change in https://github.com/elastic/elasticsearch/pull/32204 which should add you as a co-author. Again sorry for the trouble.

**Pull request closed without merging**
