### PR TITLE
Fixed inconsistent Setting.exist()

### LINKED ISSUE #41830: Setting.exists reflects secure settings but .get doesnt
`Setting.exists` is implemented by checking whether the key is in `Settings.keySet()`
But keySet returns the union of standard settings and secure settings, so this means that a setting is considered to exist if it is in _either_ `elasticsearch.yml` or `elasticsearch.keystore`
However `Setting.get()`  does not read secure settings, so code that tries to do
```
if (setting.exists()) {
  return setting.get();
} else {
 // ...
}
```
Will do the wrong thing if the setting has been (presumably incorrectly) added to the keystore.

My proposal would be to add a `keySet(boolean includeSecureSettings)` to Settings, and have exists (in non-secure `Setting`) call that with `false`.

### PR DESCRIPTION
**Pull request by probakowski**
Setting.exist() will no longer return true if there's setting in keystore with the same name.

Closes #41830

### CODE REVIEW

**Comment by rjernst** [comment]
I think having this alternate version of `keySet` will further confuse things. Please see my [comments](https://github.com/elastic/elasticsearch/issues/41830#issuecomment-489717183) on the original issue. We should be able to make the behavior consistent within the current methods.

**Comment by probakowski** [comment]
I've seen the comments there, but I don't see how we can get both `get` and `exist` behave consistently with current methods. 
`Setting.get` and `SecureSetting.get` now do the same thing - throw exception when setting is in wrong place (keystore or yaml respectively) after checks added in #42209
Still, `Setting.exist` will be happy with both keystore (where `get` will throw exception) and yaml, where `SecureSetting.exist` will only accept keystore. As we don't have public access right now to unsecure settings only we can't fix `Setting.exist`. So we can either:

1. "Break" `SecureSetting.exist` to behave as `Setting.exist` - can be done without adding/opening anything but doesn't look like good idea
2. Add `Settings.unsecureKeySet` that skip secure settings
3. Add `Settings.keySet` with parameter as in this PR
4. Add explicit `Settings.containsSecureSetting` and `Settings.containsUnsecureSetting` and skip `keySet` altogether in both `exist` methods
For me the best is either 3 or 4, WDYT?

**Review by rjernst — APPROVED** [review]
One more nit, then LGTM

**Comment by probakowski** [comment]
@elasticmachine test this please

**Comment by probakowski** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by probakowski** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by probakowski** [comment]
@elasticmachine run elasticsearch-ci/default-distro

**Comment by probakowski** [comment]
@elasticmachine run elasticsearch-ci/docs

**Pull request merged**
