### PR TITLE
Fix wrong reused file bytes in Recovery API reports

### LINKED ISSUE #11876: Recovery API reports wrong reused file bytes during snapshot restore
The snapshot restore procedure copies over all the bytes. The output however is: (note `reused_in_bytes` == `total_in_bytes`):

```
 "index": {
               "size": {
                  "total_in_bytes": 4390745019,
                  "reused_in_bytes": 4390745019,
                  "recovered_in_bytes": 31053339,
                  "percent": "0.7%"
               },
               "files": {
                  "total": 136,
                  "reused": 0,
                  "recovered": 3,
                  "percent": "2.2%"
               },
               "total_time_in_millis": 131455,
               "source_throttle_time_in_millis": 0,
               "target_throttle_time_in_millis": 0
```

### PR DESCRIPTION
**Pull request by szroland**
Calling the correct method, `reusedBytes()` when creating json output.
This fixes #11876.

### CODE REVIEW

**Comment by pickypg** [comment]
I think that we should keep the POST option in the REST spec and add it to the code rather than removing it from what we deem to be the code contract (a non-backwards compatible change, even though we don't technically do it). We can create a separate issue for that and fix/remove it there, which should simplify your this pull request.

**Comment by bleskes** [comment]
@pickypg the code actually supports PUT without a _create and POST with :

```
        controller.registerHandler(PUT, "/_snapshot/{repository}/{snapshot}", this);
        controller.registerHandler(POST, "/_snapshot/{repository}/{snapshot}/_create", this);
```

@szroland I agree this is confusing. Can you separate the snapshot create change into another PR/issue so we can discuss things over there? It's different from the RecoveryState change which is good and should go in as is ...

**Comment by szroland** [comment]
@pickypg, I know that the code does support the POST with _create. But the semantics of the original spec, at least as implemented in the Rest Test infrastructure, is as if the controller registered all these handlers (since the json format cannot limit a HTTP method to a particular path):

```
   controller.registerHandler(PUT, "/_snapshot/{repository}/{snapshot}", this);
   controller.registerHandler(POST, "/_snapshot/{repository}/{snapshot}", this);

   controller.registerHandler(PUT, "/_snapshot/{repository}/{snapshot}/_create", this);
   controller.registerHandler(POST, "/_snapshot/{repository}/{snapshot}/_create", this);
```
So in this sense, the spec was actually incorrect. With this approach, the portion it describes is correct, only it does not fully describe the available endpoints. As I commented on the main issue, I did open a separate issue to resolve this particular problem:  #11897.

@bleskes, while I could pull that out to a separate PR, that would break the test. Without this change it is not possible to use the snapshot.create API in a Rest Test. I think it is a better option overall to at least temporarily fix the spec, make it work in tests, and in the context of a dedicated issue, #11897, figure out what the best way to resolve this for good is.

As I noted in #11897, the same thing (omitting the POST / _create endpoint) has been done with other APIs as well. Also the spec currently is not comprehensive anyway, for instance it misses many of the documented arguments on snapshot restore, whereas POST / _create does not seem to be mentioned in the documentation as an option.

**Comment by bleskes** [comment]
@szroland fair enough. I would still prefer to separate the two changes for future reference. I just left a comment on #11897 +1'ing one of your suggestions. Let's get #11897 fixed first and then pull the RecoveryState fix immediately afterwards. Makes sense?

**Comment by szroland** [comment]
Sure, I added the pull request over at #11897, if that looks good and gets merged I can fix this PR up

**Pull request closed without merging**
