### PR TITLE
Replace SearchExtRegistry with namedObject

### PR DESCRIPTION
**Pull request by nik9000**
This is the last thing in `SearchRequestParsers`. After this
is merged we should be able to drop it.

Breaks java plugins registering `SearchExtParser`s by making
the registration more standard.

### CODE REVIEW

**Comment by nik9000** [comment]
@javanna, yet more fun for you, if you want it.

**Review by s1monw — APPROVED** [review]
LGTM

**Comment by s1monw** [comment]
@elasticmachine test this please

**Comment by nik9000** [comment]
Thanks for reviewing @s1monw!

master: f4884e0726d305f3edeb449a2f72318c6f25967f
5.x: backporting

**Pull request merged**
