### PR TITLE
UNICODE_CHARACTER_CLASS fix

### LINKED ISSUE #10146: rename UNICODE_CHAR_CLASS to UNICODE_CHARACTER_CLASS in regex flags
The documentation states that one should use the Java Pattern API flags for ES regex. However I received an error when I used ```UNICODE_CHARACTER_CLASS```. Looking at the source, ```UNICODE_CHAR_CLASS``` is used instead. Can this be renamed to match the Java Pattern API?

See #2895 for the source code.

### PR DESCRIPTION
**Pull request by srogljan**
Closes #10146

### CODE REVIEW

**Comment by clintongormley** [comment]
Sorry this was lost. Are you still interested in this?  If so, could I ask you to sign the CLA?  http://www.elasticsearch.org/contributor-agreement/

**Comment by clintongormley** [comment]
I wonder if this should go through parseFields and we can deprecate the old form.

/cc @MaineC

**Comment by srogljan** [comment]
Sure you can. :-) I hope I will sign it at the evening. Can you wait, that long?

**Comment by MaineC** [comment]
Yeah, sure.

**Comment by MaineC** [comment]
@clintongormley wrt. to passing this through ParseField: while the deprecation handling of ParseField would indeed be handy to have here, ParseField comes with a bit more logic for supporting both, underscore based and camel case names, inferring one from the other. 

Switching things like this to a vanilla ParseField would make things more confusing. Might be worthwhile to extract the deprecation logic from it though if there are more bugs/ requests for improvement like this one.

**Comment by srogljan** [comment]
signed! feel free to use this code :)

**Pull request merged**
