### PR TITLE
 Bump 6.6 branch to 6.6.2

### PR DESCRIPTION
**Pull request by hendrikmuhs**

### CODE REVIEW

**Comment by hendrikmuhs** [comment]
This likely fails because https://github.com/elastic/elasticsearch/pull/39121 isn't merged yet

**Comment by hendrikmuhs** [comment]
run elasticsearch-ci/bwc

**Comment by hendrikmuhs** [comment]
run elasticsearch-ci/default-distro

**Comment by hendrikmuhs** [comment]
run elasticsearch-ci/1

**Comment by hendrikmuhs** [comment]
run elasticsearch-ci/2

**Review by jakelandis — APPROVED** [review]
LGTM

**Comment by jakelandis** [comment]
@elasticmachine run elasticsearch-ci/1  
@elasticmachine run elasticsearch-ci/2

**Comment by jakelandis** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by jakelandis** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by talevy** [comment]
build was aborted due to CI being restarted

**Comment by talevy** [comment]
run elasticsearch-ci/2

**Comment by talevy** [comment]
I'm going to go ahead and merge this to quiet the builds

**Pull request merged**
