### PR TITLE
Simplify InternalTopHits

### PR DESCRIPTION
**Pull request by original-brownbear**
The main motivation for this is coming from #102030 since the aggregations hold references to `SearchHit` which means we need reference counting here. This is much easier to implement and reason about if the `SearchHits` aren't needlessly moved into a fresh array. Either way, this change should be an improvement in memory use and performance in isolation.
So improvements:
* no extra loop for finding max score any longer
* no extra `SearchHits[]` array
* less code duplication for the loop collecting top-docs by shard

### CODE REVIEW

**Review by martijnvg — APPROVED** [review]
LGTM

**Comment by martijnvg** [comment]
Test failure is unrelated (`org.elasticsearch.xpack.test.rest.XPackRestIT.test {p0=esql/100_bug_fix/Coalesce and to_ip functions}`).

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/part-3

**Comment by original-brownbear** [comment]
Thanks Martijn!

**Pull request merged**
