### PR TITLE
ESQL: Fix CSV tests

### LINKED ISSUE #106501: ESQL CSVTests failing
Pretty much every test in this suite fails from time to time.

### CI Link

https://gradle-enterprise.elastic.co/s/ojn7nl2reehnu/tests/task/:x-pack:plugin:esql:test/details/org.elasticsearch.xpack.esql.CsvTests/test%20%7Bgrok.TypeConversions%7D?top-execution=1

### Repro line

```./gradlew ':x-pack:plugin:esql:test' --tests "org.elasticsearch.xpack.esql.CsvTests" -Dtests.method="test {grok.TypeConversions}" -Dtests.seed=673DAFB9C9F716F9 -Dtests.locale=ms-MY -Dtests.timezone=America/Toronto -Druntime.java=21```

### Does it reproduce?

No

### Applicable branches

main

### Failure history

https://es-delivery-stats.elastic.dev/app/r/s/ph4sk

### Failure excerpt

```java.lang.IllegalArgumentException: Unrecognized class type class [Lorg.apache.lucene.util.BytesRef;```

### PR DESCRIPTION
**Pull request by nik9000**
When we use `ROW` in ESQL we pick a random data set by just iterating the `Map`. It's random. Yay! And some of them don't work in this place. This just picks one that we know works.

Closes #106501

### CODE REVIEW

**Review by costin — APPROVED** [review]
LGTM

**Comment by nik9000** [comment]
run elasticsearch-ci/8.12.3 / bwc-snapshots

**Comment by craigtaverner** [comment]
Wow! I tried to figure this out before dinner, and failed. Fantastic that you fixed this! It was a mystery to me!

**Comment by nik9000** [comment]
It was so weird.

**Pull request merged**
