### PR TITLE
Change `percolator.getTime` -> `percolator.time`

### PR DESCRIPTION
**Pull request by martijnvg**

### CODE REVIEW

**Comment by jpountz** [comment]
I feel a bit bad about changing the response format. Would be nice to implement something like https://github.com/elastic/elasticsearch/issues/11184 before doing such changes?

**Comment by kimchy** [comment]
I think it is ok for this change...

**Comment by martijnvg** [comment]
the name is just wrong, but it was never noticed... also it is a small change and only gets added to the next major version and therefore I think versioning is not necessary.

**Comment by jpountz** [comment]
LGTM then :)

**Pull request merged**
