### PR TITLE
Tiny typo to Painless dispatch justification

### PR DESCRIPTION
**Pull request by chrisivens**

### CODE REVIEW

**Comment by nik9000** [comment]
Thanks @chrisivens! This is correct. Can you sign the CLA so I can merge it? We need the CLA for all changes regardless of their size.

**Comment by chrisivens** [comment]
I signed it shortly before the PR. Let me know if you can't find it.

**Comment by nik9000** [comment]
> I signed it shortly before the PR. Let me know if you can't find it.

Sometimes things take some time to go through the pipe. Commenting on the issue causes it to recheck so that did the trick.

**Comment by nik9000** [comment]
Thanks @chrisivens! I've merged to master and cherry-picked to 5.x and 5.4 so it should be live in the docs in a half hour or so!

**Pull request merged**
