### PR TITLE
Adding deprecation logging and deprecation info API for ILM freeze ation

### PR DESCRIPTION
**Pull request by masseyke**
As part of deprecating frozen indices in favor of the frozen tier, this commit deprecates the ILM freeze action. This
includes a deprecation log message at runtime, as well as a deprecation info API check.
Relates #70192 #42404

### CODE REVIEW

**Comment by masseyke** [comment]
@elasticmachine update branch

**Comment by dakrone** [comment]
These messages mention that the freeze action has been deprecated in favor of the frozen tier, but that is incorrect. Actually, frozen indices are no longer necessary due to heap improvements (see the header on https://www.elastic.co/guide/en/elasticsearch/reference/7.14/freeze-index-api.html for an example of how we describe it in the documentation)

**Review by dakrone — APPROVED** [review]
LGTM, though, is it expected that the current link to the documentation does not work? Has it just not been set up yet?

**Comment by masseyke** [comment]
> LGTM, though, is it expected that the current link to the documentation does not work? Has it just not been set up yet?

Yeah I have a script to generate those links once the documentation is written. Related, @jakelandis told me that you and he will be writing that documentation @dakrone.

**Comment by jakelandis** [comment]
@masseyke - I did indeed say that :) However, after re-review of how the documentation is arranged, can you link to https://www.elastic.co/guide/en/elasticsearch/reference/master/migrating-8.0.html#breaking_80_ilm_changes.  The removal of the API will have it's own entry and pointing to just the ILM doc I think makes sense here since the warning is just about ILM.

**Pull request merged**
