### PR TITLE
Fix plumbing in double and keyword runtime fields for the scripting fields API

### PR DESCRIPTION
**Pull request by jdconrad**
This adds the necessary plumbing for the double and keyword runtime field types to access the scripting fields API.

This also adds a number of tests to Painless for the gap in runtime fields including testing each of the runtime fields type except composite with both field and doc at both index time and query time.

### CODE REVIEW

**Review by stu-elastic — APPROVED** [review]
Great catch!

**Comment by stu-elastic** [comment]
@elasticsearchmachine run elasticsearch-ci/bwc

**Comment by stu-elastic** [comment]
@elasticsearchmachine run elasticsearch-ci/part-2

**Comment by stu-elastic** [comment]
@elasticmachine update branch

**Comment by jdconrad** [comment]
@stu-elastic Thanks for the review!

**Pull request merged**
