### PR TITLE
Bumping ES Version to 6.4.1

### PR DESCRIPTION
**Pull request by vladimirdolzhenko**

### CODE REVIEW

**Comment by lcawl** [comment]
I think it's too soon to update the :version: attribute in the Versions.asciidoc file.  We use it in the documentation in places like this: https://www.elastic.co/guide/en/elasticsearch/reference/6.4/zip-targz.html

**Comment by vladimirdolzhenko** [comment]
@lcawl a bit confused here - we're going to update build version - it has to be reflected in doc as well - but it has to be merged after release of 6.4

@davidkyle could you pls advice ?

**Comment by lcawl** [comment]
@vladimirdolzhenko I don't think they usually touch the Versions.asciidoc.  For example, it's still 6.3.2 in the 6.3 branch: https://raw.githubusercontent.com/elastic/elasticsearch/6.3/docs/Versions.asciidoc

**Review by davidkyle — APPROVED** [review]
LGTM

**Pull request merged**
