### PR TITLE
Fix references of ESQL enrich lookup requests

### PR DESCRIPTION
**Pull request by dnhatn**
The EnrichIT suite failed because enrich lookup requests are released while a driver is still executing. While we can extend the lifecycle of the transport requests, this PR extends the lifecycle of enrich lookup requests only to minimize the impact of the fix.

### CODE REVIEW

**Comment by DaveCTurner** [comment]
I don't think we should make this change. If a request handler needs to keep a transport request alive after it's been invoked, it should call `incRef()` itself.

**Comment by DaveCTurner** [comment]
i.e. something like this:

```diff
diff --git a/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/enrich/EnrichLookupService.java b/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/enrich/EnrichLookupService.java
index 7dd9f01a9d6..384563cb815 100644
--- a/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/enrich/EnrichLookupService.java
+++ b/x-pack/plugin/esql/src/main/java/org/elasticsearch/xpack/esql/enrich/EnrichLookupService.java
@@ -335,7 +335,8 @@ public class EnrichLookupService {
     private class TransportHandler implements TransportRequestHandler<LookupRequest> {
         @Override
         public void messageReceived(LookupRequest request, TransportChannel channel, Task task) {
-            ActionListener<LookupResponse> listener = new ChannelActionListener<>(channel);
+            request.incRef();
+            ActionListener<LookupResponse> listener = ActionListener.runBefore(new ChannelActionListener<>(channel), request::decRef);
             doLookup(
                 request.sessionId,
                 (CancellableTask) task,
```

We want the handler to be able to release the request as soon as it's no longer needed, which might be well before we send the response. Or it could be later too, if the request is being processed as a background task. But in any case the transport layer doesn't need to retain a reference to the request once it's invoked the request handler, so it should `decRef()` right away.

**Comment by dnhatn** [comment]
Thanks for looking @DaveCTurner. Yes, that was the option that I considered too. This change has a broader impact than I thought. I think I will go with the smaller change for the enrich request.

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Comment by dnhatn** [comment]
Thanks David!

**Pull request merged**
