### PR TITLE
Reindex restart from checkpoint

### PR DESCRIPTION
**Pull request by henningandersen**
Now restart from last stored checkpoint (seqno currently) when a reindex
job is failed over to another node.

Relates #42612

### CODE REVIEW

**Review by Tim-Brooks — COMMENTED** [review]
This is looking pretty good. I think there will be some conflicts between this and the work I am doing. Is this still WIP?

**Comment by henningandersen** [comment]
I removed the WIP label though a few tests could be added and parts of it done in master too. I agree that there could be conflicts to your PR and thus it may make sense to push this to the FB and do the rest in follow-ups?

**Review by Tim-Brooks — APPROVED** [review]
LGTM

**Comment by henningandersen** [comment]
Thanks @tbrooks8

**Pull request merged**
