### PR TITLE
Remove unused version in range field type constructor arguments

### PR DESCRIPTION
**Pull request by liketic**
The argument ```indexVersionCreated``` is not needed any more. Just remove it.

### CODE REVIEW

**Comment by colings86** [comment]
@elasticmachine test this please

**Comment by jpountz** [comment]
@elasticmachine test this please

**Review by cbuescher — APPROVED** [review]
@liketic makes sense. I will kick of another test run and merge once green.

**Comment by cbuescher** [comment]
@elasticmachine test this please

**Comment by cbuescher** [comment]
@elasticmachine test this please

**Comment by cbuescher** [comment]
Jenkins, test this please with a new version of master.

**Comment by cbuescher** [comment]
@liketic thank you, merged to master now. Correct me if I'm wrong but I believe this ctor argument is still needed in the 6.x branches, so I don't think this needs backporting.

**Pull request merged**
