### PR TITLE
Apply 2-space indent to all gradle scripts

### LINKED ISSUE #48727: Reformat Gradle build script to use consistent indent
Our `build.gradle` files use a mix of 2 spaces and 4 spaces for indent width making it really frustrating when editing these files in an IDE configured one way or the other. Because this isn't consistent across all files it's not easily fixable by just reconfiguring IDE settings. Let's pick one and do the one-time step of reformatting all `.gradle` files. 

FWIW, my vote is for 4 spaces since it's consistent with existing conventions we use for Groovy and Java.

### PR DESCRIPTION
**Pull request by pugnascotia**
Closes #48727.

Update `.editorconfig` to make the Java settings the default for all
files, and then apply a 2-space indent to all `*.gradle` files. Then
reformat all the files.

If you view the diff ignoring whitespace, you'll see hardly any diffs.

### CODE REVIEW

**Comment by atorok** [comment]
I'm on the fence with this one. Might be better to apply it when we do the other formatting changes as it's a substantial change. @mark-vieira what do you think  ?

**Comment by mark-vieira** [comment]
@pugnascotia what's the IDE experience here? Does IntelliJ properly respect the editorconfig and use 2-space indent only for `.gradle` files?

I'm generally fine with just pulling the trigger on this. I'm not sure there's much benefit to deferring this until some later time. Given this is a very targeted reformatting I think that helps limit the disruption.

**Comment by pugnascotia** [comment]
@mark-vieira I tried vim and IntelliJ, and both respect the Editorconfig settings, so it pretty much works exactly like you want. Actually, to reformat the files in this PR, I defined a scope in IntelliJ for all Gradle scripts, and did a mass-reformat in the IDE. Easy. Given the [wide support](https://editorconfig.org/#download) for Editorconfig, we should be good to go.

**Review by mark-vieira — APPROVED** [review]
I'm 👍 on this. The current situation is a big annoyance of mine and when it comes to bulk reformatting, there's no "good" time to do it. I say we pull the trigger on this but I'd like to confirm there are no strong objections from @atorok @rjernst or @jasontedor.

**Comment by atorok** [comment]
I don't have strong objections, I'm ok with it if everyone else feels like merging it.

**Comment by mark-vieira** [comment]
@pugnascotia We should backport this to `7.x` at least to make future backports less painful.

**Comment by pugnascotia** [comment]
Raised #49071 for the backport.

**Pull request merged**
