### PR TITLE
#32478 fixed cluster stats return 8EB

### LINKED ISSUE #32478: Cluster stats return fs total / fs avaliable to 8EB
**Describe the feature**:

**Elasticsearch version** : 5.6.4

**Plugins installed**: []

**JVM version** (`java -version`): 1.8.0_151

**OS version** (`uname -a` if on a Unix-like system):
Linux  3.10.0-693.2.2.el7.x86_64 #1 SMP x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:
here same issue in discuss

https://discuss.elastic.co/t/es-cluster-stats-api-returning-false-values/84949

```json
"fs" : {
  "total" : "8192pb",
  "total_in_bytes" : 9223372036854775807,
  "free" : "8192pb",
  "free_in_bytes" : 9223372036854775807,
  "available" : "8192pb",
  "available_in_bytes" : 9223372036854775807
}
```

this issue occur by Elasticsearch Tribe node.
tribe node return like this.
```
name                          dt     du       d
dev-estribe001.ncl/es1       -1b     0b     -1b
```

and cluster stats api using this
```java
ClusterStatsNodes(List<ClusterStatsNodeResponse> nodeResponses) {
        this.versions = new HashSet<>();
        this.fs = new FsInfo.Path();
        this.plugins = new HashSet<>();

        Set<InetAddress> seenAddresses = new HashSet<>(nodeResponses.size());
        List<NodeInfo> nodeInfos = new ArrayList<>(nodeResponses.size());
        List<NodeStats> nodeStats = new ArrayList<>(nodeResponses.size());
        for (ClusterStatsNodeResponse nodeResponse : nodeResponses) {
            // if first nodePresponse are tribe node --> it makes return 8EB
            nodeInfos.add(nodeResponse.nodeInfo());
            nodeStats.add(nodeResponse.nodeStats());
            this.versions.add(nodeResponse.nodeInfo().getVersion());
            this.plugins.addAll(nodeResponse.nodeInfo().getPlugins().getPluginInfos());

            // now do the stats that should be deduped by hardware (implemented by ip deduping)
            TransportAddress publishAddress = nodeResponse.nodeInfo().getTransport().address().publishAddress();
            InetAddress inetAddress = null;
            if (publishAddress.uniqueAddressTypeId() == 1) {
                inetAddress = ((InetSocketTransportAddress) publishAddress).address().getAddress();
            }
            if (!seenAddresses.add(inetAddress)) {
                continue;
            }
            if (nodeResponse.nodeStats().getFs() != null) {
                this.fs.add(nodeResponse.nodeStats().getFs().getTotal());   // <-- here tribe node try to add this.fs
            }
        }
        this.counts = new Counts(nodeInfos);
        this.os = new OsStats(nodeInfos, nodeStats);
        this.process = new ProcessStats(nodeStats);
        this.jvm = new JvmStats(nodeInfos, nodeStats);
        this.networkTypes = new NetworkTypes(nodeInfos);
    }

...

// this.fs.add using this logic
 public void add(Path path) {
            total = FsProbe.adjustForHugeFilesystems(addLong(total, path.total));
            free = FsProbe.adjustForHugeFilesystems(addLong(free, path.free));
            available = FsProbe.adjustForHugeFilesystems(addLong(available, path.available));
            if (path.spins != null && path.spins.booleanValue()) {
                // Spinning is contagious!
                spins = Boolean.TRUE;
            }
        }

...

// if first node are tribe node
// current = -1, other = -1
// so it always return -1;
private long addLong(long current, long other) {
            if (other == -1) {
                return current;
            }
            if (current == -1) {
                return other;
            }
            return current + other;
        }
...

// byte are -1 --> it makes return 8eb
    static long adjustForHugeFilesystems(long bytes) {
        if (bytes < 0) {
            return Long.MAX_VALUE;
        }
        return bytes;
    }
```

so it need to fix like this
```java
private long addLong(long current, long other) {
            if (other == -1 && current == -1){
                return 0;
            }
            if (other == -1) {
                return current;
            }
            if (current == -1) {
                return other;
            }
            return current + other;
        }

        private double addDouble(double current, double other) {
            if (other == -1 && current == -1){
                return 0;
            }
            if (other == -1) {
                return current;
            }
            if (current == -1) {
                return other;
            }
            return current + other;
        }
```

**Steps to reproduce**:
hard to re produce it.
because First NodeResponse have to tribe node.

**Provide logs (if relevant)**:

### PR DESCRIPTION
**Pull request by hgword**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

fixed #32478 issue.
tribe node make that cluater stats api return 8EB.
so add thouse case;

### CODE REVIEW

**Comment by hgword** [comment]
@karmi 
sorry, now I just agree that contribute Elasticsearch.

**Comment by karmi** [comment]
@hgword , great, the check is now green, thanks!

**Comment by javanna** [comment]
@elastic/es-core-infra thoughts about this one?

**Review by dakrone — APPROVED** [review]
LGTM

**Comment by dakrone** [comment]
@elasticmachine ok to test

**Comment by dakrone** [comment]
@elasticmachine update branch

**Pull request merged**
