### PR TITLE
Fix ShrinkIndexIT

### LINKED ISSUE #44164: [CI] Various tests in ShrinkIndexIT fail with "expected at least one master-eligible node left"
This failure has occurred many times in the last 36 hours: https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:relative,to:now))&_a=(columns:!(test,build-id,build_url,branch),filters:!(),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'class:%20%22org.elasticsearch.action.admin.indices.create.ShrinkIndexIT%22'),sort:!(time,desc))

Often the failing test is `ShrinkIndexIT.testCreateShrinkWithIndexSort`, see for example https://gradle.com/s/fglguuelmqobe

More recently a failure of `ShrinkIndexIT.testShrinkCommitsMergeOnIdle` was seen but with the same error message: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-1/2405/testReport/junit/org.elasticsearch.action.admin.indices.create/ShrinkIndexIT/testShrinkCommitsMergeOnIdle/

In both cases the error message is something like:

```
java.lang.AssertionError: expected at least one master-eligible node left in {node_sc1=org.elasticsearch.test.InternalTestCluster$NodeAndClient@2de106c0}
```

A REPRO command for 7.x is:

```
./gradlew :server:integTest --tests "org.elasticsearch.action.admin.indices.create.ShrinkIndexIT.testCreateShrinkWithIndexSort" -Dtests.seed=50AF68DFDA0BACBE -Dtests.security.manager=true -Dtests.locale=zh-TW -Dtests.timezone=America/North_Dakota/Center -Dcompiler.java=12 -Druntime.java=8
```

A REPRO command for master is:

```
./gradlew :server:integTest --tests "org.elasticsearch.action.admin.indices.create.ShrinkIndexIT.testShrinkCommitsMergeOnIdle" -Dtests.seed=C57BD4CF13C2F399 -Dtests.security.manager=true -Dtests.locale=fo -Dtests.timezone=Europe/Zagreb -Dcompiler.java=12 -Druntime.java=11
```

Neither of these reproduce locally for me.

I will mute the suite.

### PR DESCRIPTION
**Pull request by original-brownbear**
* Move this test suit to cluster scope. Currently, `testShrinkThenSplitWithFailedNode` stops a random node which randomly turns out to be the only shared master node so the cluster reset fails on account of the fact that no shared master node survived.
* Closes #44164

@DaveCTurner can you take a look since you added that assertion in reset in 034c7655b782d6006be7ac4dc0aa02970e8f17fe? :)

### CODE REVIEW

**Review by DaveCTurner — COMMENTED** [review]
Good catch.

I note that the CI issue was complaining about multiple tests failing - is this because the `reset()` is associated with the test _after_ the one that broke the cluster? If so, can we catch this in the right test in future by asserting in `stopRandomDataNode` that it isn't stopping the last-remaining shared master-eligible node (if `autoManageMasterNodes == true` at least)?

Also can we fix this while keeping a suite-wide cluster by choosing a node other than the unique shared master-eligible node in the offending test?

**Comment by original-brownbear** [comment]
@DaveCTurner 

> I note that the CI issue was complaining about multiple tests failing - is this because the reset() is associated with the test after the one that broke the cluster?

Yes.

> If so, can we catch this in the right test in future by asserting in stopRandomDataNode that it isn't stopping the last-remaining shared master-eligible node (if autoManageMasterNodes == true at least)?

Sweet idea, done in 4a59fc0, that does indeed fail a lot nicer :)

> Also can we fix this while keeping a suite-wide cluster by choosing a node other than the unique shared master-eligible node in the offending test?

Sure, also done in 4a59fc0. Just fired up a new data only node for this. As far as I can see that doesn't change the test's behavior and makes things super safe without complicating things?

**Review by DaveCTurner — APPROVED** [review]
LGTM thanks for the second round @original-brownbear.

**Comment by original-brownbear** [comment]
thanks @DaveCTurner !

**Pull request merged**
