### PR TITLE
Update similarity.asciidoc

### PR DESCRIPTION
**Pull request by blueSky1825821**
DFRSimilarity -> DFR similarity

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Review by cbuescher — COMMENTED** [review]
Thanks for the correction @blueSky1825821, the change is good, but could you please sign the CLA so we can merge this?

**Comment by blueSky1825821** [comment]
> Thanks for the correction @blueSky1825821, the change is good, but could you please sign the CLA so we can merge this?

I signed the CLA, please recheck it

**Comment by cbuescher** [comment]
@blueSky1825821 sorry, I cannot find the email you used in this commit in our recods. You might have signed the CLA with a different e-mail than the one used in yout Git commit. Can you add this e-mails into your Github profile (can be hidden), so we can match your e-mails to your Github profile for the CLA checker?

**Review by cbuescher — APPROVED** [review]
LGTM

**Comment by cbuescher** [comment]
Thanks for signing, looks good now. 
I will run the tests.
@elasticmachine test this please

**Comment by cbuescher** [comment]
Thanks @blueSky1825821, merged to 7.5 and up.

**Pull request merged**
