### PR TITLE
Use non-deprecated Kibana SAML callback URL in tests

### LINKED ISSUE #99985: Unit test should replace /api/security/v1/saml with /api/security/saml/callback
### Description

In [TransportSamlInitiateSingleSignOnActionTests.java](https://github.com/elastic/elasticsearch/pull/98882/files#diff-26733d11b06442213a040cc3d5c89595300ec813bb31076874afa38ef2ad3b91),  `/api/security/v1/saml` (deprecated) should be replaced with /api/security/saml/callback

In https://github.com/elastic/kibana/blob/b33effa182bcb7c9620c5435ab252d8067732655/x-pack/plugins/security/server/routes/authentication/saml.ts#L27

/api/security/saml/callback is the correct URL,
while /api/security/v1/saml is the deprecated URL.

Related to https://github.com/elastic/cloud-on-k8s/issues/7118

### PR DESCRIPTION
**Pull request by rodrigc**
In https://github.com/elastic/kibana/blob/b33effa182bcb7c9620c5435ab252d8067732655/x-pack/plugins/security/server/routes/authentication/saml.ts#L27

/api/security/saml/callback is the correct URL,
while /api/security/v1/saml is the deprecated URL.

See also: https://github.com/elastic/kibana/issues/81733

Fixes: #99985

### CODE REVIEW

**Comment by gwbrown** [comment]
@elasticmachine test this please

**Comment by gwbrown** [comment]
@elasticmachine update branch

**Comment by gwbrown** [comment]
@elasticmachine test this please

**Comment by gwbrown** [comment]
@elasticmachine test this please

**Review by AthenaEryma — APPROVED** [review]

**Review by AthenaEryma — APPROVED** [review]

**Pull request merged**
