### PR TITLE
Fix comment in default `jvm.options` configuration file

### PR DESCRIPTION
**Pull request by niiiibl**

### CODE REVIEW

**Comment by mark-vieira** [comment]
@nibbl Thanks for the PR. Do you mind signing our [CLA](https://www.elastic.co/contributor-agreement) so that we can get this merged?

**Comment by mark-vieira** [comment]
@elasticmachine test this please

**Comment by nibbl** [comment]
> @nibbl Thanks for the PR. Do you mind signing our [CLA](https://www.elastic.co/contributor-agreement) so that we can get this merged?

Yes, no problem, if this need for merging
I'm glad to contribute, thanks

**Comment by nibbl** [comment]
Okay, I signed CLA, let's merge

**Comment by mark-vieira** [comment]
@elasticmachine update branch

**Comment by mark-vieira** [comment]
@elasticmachine test this please

**Comment by pugnascotia** [comment]
@elasticmachine update branch

**Comment by pugnascotia** [comment]
@elasticmachine ok to test

**Comment by pugnascotia** [comment]
Thanks @nibbl!

**Pull request merged**
