### PR TITLE
Show open and closed indices in _cat/indices

### PR DESCRIPTION
**Pull request by dadoonet**
When asking for `GET /_cat/indices?v`, you can now retrieve closed indices in addition to opened ones.

```
health status index              pri rep docs.count docs.deleted store.size pri.store.size
yellow open   .marvel-2014.05.21   1   1       8792            0     21.7mb         21.7mb
       close  test
yellow open   .marvel-2014.05.22   1   1       3871            0     10.7mb         10.7mb
red    open   .marvel-2014.05.27   1   1
```

Closes #7907.

### CODE REVIEW

**Comment by michaelsalmon** [comment]
This doesn't seem to have made it into the guide yet.

**Comment by clintongormley** [comment]
@dadoonet please could you document this change?

**Comment by dadoonet** [comment]
@michaelsalmon thanks for raising it. I totally missed that.
@clintongormley done in master, 1.x and 1.4 branches.

**Comment by michaelsalmon** [comment]
It looks good but I'm pretty sure that line 44 should end -rnk8 now.

**Comment by dadoonet** [comment]
So true! Will fix. Thanks.

**Pull request closed without merging**
