### PR TITLE
Fix slow sync test clustres artifacts task

### PR DESCRIPTION
**Pull request by alpar-t**
The task was mistakenly adding a combinational explosion of task
actions  all doing the same thing.
With this PR this is fixed and each version - distribution pair is only
extracted once.
I appologieze for the SSD wear.

### CODE REVIEW

**Review by mark-vieira — APPROVED** [review]
LGTM 👍

**Comment by mark-vieira** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by mark-vieira** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by mark-vieira** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by mark-vieira** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by mark-vieira** [comment]
@atorok for some reason this PR seems highly susceptible to some odd CI issue where `BuildExamplePluginsIT` is hanging while trying to copy the example plugin directory for `security-authorization-engine`. I'm trying to track this down bit it's a bit intermittent.

**Comment by mark-vieira** [comment]
I'm not completely sure why this started happening recently, or why this particular PR seems to hit this issue more than others but I think I potentially found the problem. When we copy the example plugin directory into the test temp directory we are indiscriminately taking everything in that directory. If that plugin has already been built, the `/build` directory includes all kinds of stuff, including symlinks to ES clusters downloaded by testclusters. I suspect this is where things are going haywire. I've added a simple filter here so that we simple exclude the contents of the build directory. If nothing else, this should make the tests faster as we are copying a lot less stuff when setting up the example plugin tests.

**Comment by mark-vieira** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by atorok** [comment]
@elasticmachine run elasticsearch-ci/1

**Pull request merged**
