### PR TITLE
[DOCS] 6.5 highlights: source-only snapshots, cond tokenfilter, ODBC

### PR DESCRIPTION
**Pull request by debadair**
Also edited 6.5 RN heading to match previous releases.

Note: The other changes marked in the diff are due to the removal of trailing spaces. Sorry for the noise.

### CODE REVIEW

**Review by lcawl — APPROVED** [review]
LGTM

**Comment by colings86** [comment]
Please remember to add all relevant labels (area label, version label(s) and change type label) on all PRs and please look for this as part of reviews. The release note generation process is made much harder when PRs are not labelled correctly and its much harder to work out where PRs have been merged to.

**Comment by debadair** [comment]
@colings86 I see you added both the >docs and :Docs labels...had I not spaced, I wouldn't have added the :Docs label for a content change like this. What are the cases where :Docs should be applied?

**Comment by colings86** [comment]
@debadair we should add `:Docs` area label for any changes to docs infrastructure or any changes that are for release prep documentation like release notes (if a PR is created for that) or release highlights. In general we should make sure we have an area label for all issues and PRs (except backport PRs) so we have an area team identified as responsible for all issues and PRs. For docs changes that are specific to a particular area (like changing the aggs docs for example) we should use the appropriate other area labels.

Do that make sense?

**Pull request merged**
