### PR TITLE
Use correct system index bulk executor

### PR DESCRIPTION
**Pull request by henningandersen**
In one place we would always use the Write threadpool, which could let write thread pool queuing lead to increased system index write latency.

### CODE REVIEW

**Comment by henningandersen** [comment]
Failure looks like #106192

**Comment by henningandersen** [comment]
@elasticmachine update branch

**Review by Tim-Brooks — APPROVED** [review]
LGTM

**Review by idegtiarenko — APPROVED** [review]

**Comment by henningandersen** [comment]
@elasticmachine update branch

**Comment by ywangd** [comment]
I think this fixes #89073

**Comment by williamrandolph** [comment]
Thanks for finding and fixing this. I can see how it was causing problems.

**Comment by StephanErb** [comment]
Could that one be backportet to 8.13? We are currently seeing some flakiness on 8.12 clusters with heavy write load and rejections and I am wondering if this change here could help to increase overall cluster stability.

**Comment by StephanErb** [comment]
Could that one be backportet to 8.13? We are currently seeing some flakiness on 8.12 clusters with heavy write load and rejections and I am wondering if this change here could help to increase overall cluster stability.

**Pull request merged**
