### PR TITLE
[ML] Reenable integration test and relax test tolerance for Linux

### PR DESCRIPTION
**Pull request by tveasey**
Following on from elastic/ml-cpp#491 we need to relax the assertion for the maximum memory used slightly in this integration test. (I've also added on some additional leeway to reduce instability of this test with changes to ml-cpp.)

### CODE REVIEW

**Comment by davidkyle** [comment]
run elasticsearch-ci/default-distro

**Comment by tveasey** [comment]
run elasticsearch-ci/default-distro

**Comment by davidkyle** [comment]
@elasticmachine update branch

**Comment by davidkyle** [comment]
run elasticsearch-ci/default-distro

**Comment by davidkyle** [comment]
@elasticmachine update branch

**Review by davidkyle — APPROVED** [review]
LGTM

**Pull request merged**
