### PR TITLE
Fix node close stopwatch usage

### PR DESCRIPTION
**Pull request by jaymode**
The close method in Node uses a StopWatch to time to closing of
various services. However, the call to log the timing was made before
any of the services had been closed and therefore no timing would be
printed out. This change moves the timing log call to be a closeable
that is the last item closed.

### CODE REVIEW

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by jaymode** [comment]
@elasticmachine run elasticsearch-ci/1
@elasticmachine run elasticsearch-ci/packaging-sample

**Comment by jaymode** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by jaymode** [comment]
@elasticmachine run elasticsearch-ci/1
@elasticmachine run elasticsearch-ci/docbldesx

**Comment by jaymode** [comment]
@elasticmachine run elasticsearch-ci/1

**Pull request merged**
