### PR TITLE
Restart tests with data streams

### PR DESCRIPTION
**Pull request by probakowski**
This change adds full restart test and rolling restart test that include data streams

Relates #53100

### CODE REVIEW

**Comment by probakowski** [comment]
@elasticmachine update branch

**Comment by probakowski** [comment]
@elasticmachine update branch

**Comment by probakowski** [comment]
@elasticmachine update branch

**Review by martijnvg — APPROVED** [review]
LGTM

**Comment by probakowski** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by probakowski** [comment]
@elasticmachine update branch

**Review by danhermann — COMMENTED** [review]
Looks like a bunch of generated code was reintroduced with commit https://github.com/elastic/elasticsearch/pull/58330/commits/e674f665c86c934ca602f13b56f17e4a4fd6d26c?

**Comment by probakowski** [comment]
Thanks @danhermann, good catch. I've removed them

**Pull request merged**
