### PR TITLE
Ensure all resoruces are closed on Node#close()

### LINKED ISSUE #13685: Possibly leak of lock, if plugin hits exception on close()
here is how to reproduce (i know, kinda crazy):
1. force GroovyScriptEngineService to make NPE on close:
```
+++ b/core/src/main/java/org/elasticsearch/script/groovy/GroovyScriptEngineService.java
@@ -99,17 +99,19 @@ public class GroovyScriptEngineService extends AbstractComponent implements Scri
         }
 
         // Groovy class loader to isolate Groovy-land code
-        this.loader = new GroovyClassLoader(getClass().getClassLoader(), config);
+        this.loader = null; //new GroovyClassLoader(getClass().getClassLoader(), config);
```

2. mvn install -DskipTests from core/
3. mvn test from plugins/cloud-azure. 

LeakFS detects a file leak:
```
Throwable #1: java.lang.RuntimeException: file handle leaks: [FileChannel(/home/rmuir/workspace/elasticsearch/plugins/cloud-azure/target/J0/temp/org.elasticsearch.index.store.SmbMMapFsTests_2C60FEE3D73A0680-001/tempDir-001/d0/SUITE-CHILD_VM=[0]-CLUSTER_SEED=[-1301520842927563395]-HASH=[11EC1C68B1C5F]-cluster/nodes/2/node.lock), 
```

The issue might just be our test harness stuff, but my concern is it could happen "for real" too. In the case of SimpleFSLock it could be annoying (user has to then remove lock file).

### PR DESCRIPTION
**Pull request by s1monw**
We are leaking all kinds of resources if something during Node#close() barfs.
This commit cuts over to a list of closeables to release resources that
also closed remaining services if one or more services fail to close.

Closes #13685

### CODE REVIEW

**Comment by rmuir** [comment]
+1, I like the list-of-closeables approach.

**Comment by clintongormley** [comment]
@s1monw what happened to this PR?

**Comment by s1monw** [comment]
@clintongormley I guess it got some heavy bikeshedding not visible to this PR?

**Comment by s1monw** [comment]
I opened a new PR for this https://github.com/elastic/elasticsearch/pull/16316

**Pull request closed without merging**
