### PR TITLE
Packaging: Remove windows bin files from the tar distribution

### PR DESCRIPTION
**Pull request by rjernst**
This commit removes windows specific files from the tar distribution.
Windows users use the zip, linux users use the tar.

### CODE REVIEW

**Comment by rjernst** [comment]
@andyb-elastic why is it not surprising then when rpm and deb don't also have these same contents?

**Comment by jasontedor** [comment]
@rjernst It would not be reasonable for a Windows user to think that the RPM or Deb package is compatible with Windows. With the Linux subsystem and Git Bash, there are ways for a Windows user to easily consume a .tar.gz. Our download page does not give any indication that the .tar.gz is not compatible with Windows (and today it is). I can support this change if we change our download page to indicate that the zip distribution is for Windows only and the .tar.gz is for macOS/Linux (and it needs to be macOS/Linux as we support these OS and no other Unix-like OS). Today we display the downloads as:

screen shot 2018-05-15 at 5 44 59 pm

This is how the Kibana downloads appear:

screen shot 2018-05-15 at 5 46 23 pm

And while Kibana has architecture-specific downloads (because of the Node binary), there is no confusion on Windows which artifact to download whereas there is possibility of confusion with our artifacts.

I will fully support this change if we change our download page to remove this ambiguity.

**Comment by andyb-elastic** [comment]
Right, on Windows even without WSL, extracting the tgz with 7zip and running it seems to work fine and would be a pretty normal thing to do (at least I think). 

That said, I agree that making it explicit which platform these distributions are intended for is most helpful. Is the idea to take the bash scripts out of the zip distribution at some point as well?

**Comment by rjernst** [comment]
> Is the idea to take the bash scripts out of the zip distribution at some point as well?

I would not be opposed to that. The only caveat is we would then need to select which distribution to use based on the system we are running tests on. And eg `-Dtests.distribution` would have to be different by selecting whether the oss or default is used, but not the actual distribution.

**Comment by rjernst** [comment]
> I can support this change if we change our download page to indicate that the zip distribution is for Windows only and the .tar.gz is for macOS/Linux (and it needs to be macOS/Linux as we support these OS and no other Unix-like OS).

With each release we add the new download artifacts and their link contents, so this would need to be done with the 6.4.0 release (assuming this is merged to 6.x before 6.4 is cut). Is that sufficient?

**Comment by droberts195** [comment]
Are there some major benefits in making the `.zip` distribution not work on Linux/Mac?

It will cause a certain amount of rework in @dolaru's QA test framework for ML, as currently this uses the `.zip` distribution on all platforms.  Obviously it's not impossible to change this, but it does show that this change is going to cause people to have to spend time that could instead be spent on new features.  So if there are benefits to making this change that outweigh the costs downstream then I think it would be good to list them on the PR.

**Comment by dolaru** [comment]
just to be clear on what we're trying to achieve with this PR: 
 - `.zip` distribution contains Windows only binaries
 - `.tar.gz` contains macOS/Linux only binaries

 Also, when i say binaries i mean not just what's in `bin/` but nested module binaries too.

is this right?

**Comment by jasontedor** [comment]
This PR only changes the packaging content of the tar.gz distribution. It does not change the content of the zip distribution (there is discussion of it here), and it does not change the content of what executables are distributed under the ML plugin.

**Comment by droberts195** [comment]
Thanks for clarifying @jasontedor.  I think making the `.tar.gz` distribution not work on Windows is much less of a problem than making the `.zip` distribution not work on Mac/Linux.

**Comment by sophiec20** [comment]
Why are we making this change to the `.tar.gz`?  It doesn't take us all the way to OS specific distributions, which would align with Kibana and be more intuitive. Am curious if we are aiming towards this?

**Comment by rjernst** [comment]
@sophiec20 There are multiple motivations here:

* Remove inconsistency across packages (we ship .bat files in rpm/deb right now, but only for xpack scripts)
* Make it more clear tar.gz is for linux. I want to add (in a followup) our systemd service files to the tar.gz, but I don't think we should add them to the zip too.

> It will cause a certain amount of rework in @dolaru's QA test framework for ML, as currently this uses the .zip distribution on all platforms

As Jason mentioned, this PR only removes the windows files from the tar.gz. To me, it is less important to remove the bash scripts from windows, since they will run on windows. That would not preclude labeling the zip and tar.gz files as windows and macos/linux though.

**Review by jasontedor — APPROVED** [review]
LGTM.

**Pull request merged**
