### PR TITLE
Update painless-operators-numeric.asciidoc

### PR DESCRIPTION
**Pull request by riverbuilding**
Fixes the incorrect description of the bitwise operators.

### CODE REVIEW

**Comment by nik9000** [comment]
This looks right to me, @riverbuilding. Could you sign the CLA so we can merge it?

**Comment by nik9000** [comment]
@elasticmachine, ok to test

**Comment by riverbuilding** [comment]
@nik9000  already singed riverbuilding

**Review by jrodewig — APPROVED** [review]
LGTM. Thanks @riverbuilding.

**Comment by jrodewig** [comment]
### Backport commits
master: 66959be69ecdf3098dbe3d03d9ed261f35ea1803
7.x: e7d5443bf550a62c9a775062ca31ad397b83e9c5
7.5: 057d727706615a119ef71838d53a1fc628410253
6.8: b1e06274b22d93732854134def2877fca4b22cc1

**Pull request merged**
