### PR TITLE
Make 7.0 like 6.7 user agent ecs

### PR DESCRIPTION
**Pull request by jakelandis**
This PR moves the user_agent processor to share a code base with 6.7 as discovered in https://github.com/elastic/beats/issues/10650 is required for Beats migration to 7.0. This re-introduces the `ecs` option and the optional legacy behavior. 

This change is largely a set of revert's and cherry-picks, of which only the the most recent commits (ones without a #number) is net new code. This change is intended to be merged to 7.0.0 and then 7.x to allow the `ecs` option to live during the 7.x timeframe. 

Additionally, this changes the default from `false` to `true` for the `ecs` option.

6.7: `ecs` : default `false`
7.x: `ecs` : default `true`
8.0: no option, but behaves as `true`

The first 5 commits here:
git revert 5b008a34aa3c07e37b12b415d3c22a44da491329 (Lee's initial 7.x implementation of user_agent ecs)
git revert cac6b8e06f051d68919faf6081f1c87fa5b6757d  (Jake's minor change applied to 7.x)
git cherry-pick 5dfe1935345da3799931fd4a3ebe0b6aa9c17f57 (Lee's initial 6.x implementation of user_agent ecs)
git cherry-pick ec8ddc890a34853ee8db6af66f608b0ad0cd1099 (Jake's minor change applied to the 6.x )   
git cherry-pick f63cbdb9b426ba24ee4d987ca767ca05a22f2fbb (Gordon's 6.x deprecation info API, with manual merge fixes)

### CODE REVIEW

**Comment by ruflin** [comment]
@jakelandis I tested this branch against my branch here with Filebeat 6.7 and the output seems to be as expected: https://github.com/elastic/beats/pull/10688

**Comment by gwbrown** [comment]
With this change, do we also want to adjust the deprecation warning in 6.7? It will currently warn on pipelines with `ecs: false` or `ecs` unset, whereas if we're going to support `ecs: false` in 7.0, it should only warn on `ecs` unset.

**Comment by jakelandis** [comment]
> With this change, do we also want to adjust the deprecation warning in 6.7? It will currently warn on pipelines with `ecs: false` or `ecs` unset, whereas if we're going to support `ecs: false` in 7.0, it should only warn on `ecs` unset.

@gwbrown 
I think we are good.  The [specific message](https://github.com/elastic/elasticsearch/blob/6.7/x-pack/plugin/deprecation/src/main/java/org/elasticsearch/xpack/deprecation/ClusterDeprecationChecks.java#L92) says "Ingest pipelines [pipeline_x, pipeline_y] will change to using ECS output format in 7.0" which is still true ! (this PR changes the default to true, but leaves the option)

**Comment by jakelandis** [comment]
@dakrone @gwbrown Could I get your reviews on this ?

The only commits that should require a review are:
https://github.com/elastic/elasticsearch/pull/38757/commits/0786e7615ce090fda32d80e3c22144ffa1aaf484 - cherry pick, but manually fixed merge conflicts 
https://github.com/elastic/elasticsearch/pull/38757/commits/3a0993e2bb880e50d35a4d630335bb6fad1e6a08 - actual changes here , sets default to true tweaks the deprecation 
https://github.com/elastic/elasticsearch/pull/38757/commits/0bc518601e2a1b49c5a46aad7f2300dcadbeb887 - fixes the integration test.

**Comment by gwbrown** [comment]
@jakelandis and I talked synchronously about this and we now agree that with this change to 7.0, the Deprececation Info API in 6.7 will give a misleading deprecation warning for pipelines with `ecs: false` set: in particular, it will return a message that says this:
`Ingest pipelines [pipeline_with_ecs_false] will change to using ECS output format in 7.0`

Even though, with this PR, `pipeline_with_ecs_false` will continue to work the same way in 7.0 as in 6.7. In order to be in line with this PR, the Deprecation API should warn only about pipelines with the `user_agent` processor that do not have `ecs` set explicitly.

**Review by dakrone — APPROVED** [review]
LGTM assuming CI is happy

**Review by AthenaEryma — APPROVED** [review]
LGTM as well.

**Pull request merged**
