### PR TITLE
Migrate wait for pending tasks helper to server

### PR DESCRIPTION
**Pull request by jasontedor**
In some of our X-Pack REST tests we have to wait for pending tasks to complete. We are now needing this functionality in ESRestTestCase for the docs tests where we run against X-Pack features. This commit moves the helper method that we have in X-Pack to ESRestTestCase, and removes duplicate logic from waiting for rollup tasks to complete.

### CODE REVIEW

**Comment by jasontedor** [comment]
@elasticmachine run gradle build tests

**Comment by jasontedor** [comment]
@nik9000 Could you take a quick peek at this one?

**Comment by nik9000** [comment]
I thought I had last night.... Anyway! I don't think we need to pass in the
adminClient here. I think it is all the same client. Other than that, lgtm.

**Comment by jasontedor** [comment]
I made the method static, so we do. And the value of `client()` and `adminClient()` are often different in the X-Pack tests.

**Comment by jasontedor** [comment]
Thanks for peeking @nik9000.

**Comment by jasontedor** [comment]
They are different because in many of the tests we want the `client()` to run with reduced privileges and the `adminClient()` often has the full privileges needed to perform cleanup and administrative tasks.

**Comment by nik9000** [comment]
Oh the tests run this! Not just clenaup.

**Comment by jasontedor** [comment]
@elasticmachine run gradle build tests

**Comment by jasontedor** [comment]
@elasticmachine run gradle build tests

**Pull request merged**
