### PR TITLE
Introduce Delegating ActionListener Wrappers

### PR DESCRIPTION
**Pull request by original-brownbear**
* Dry up use cases of ActionListener that simply pass through the response or exception to another listener

### CODE REVIEW

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/bwc
Jenkins run elasticsearch-ci/default-distro

**Review by jaymode — COMMENTED** [review]
Overall, I like this change because I know that it is pretty common to delegate at least one aspect of a listener. The thing I do not like is that we lose some context since this refactoring uses `(l, r)` and it makes the reader have to look into what `l` and `r` actually are. Can you preserve the response variable name like `getResponse`? Then maybe replace `l` with `delegatedListener` or something else?

**Comment by original-brownbear** [comment]
@jaymode thanks for taking a look fixed the naming as requested in https://github.com/elastic/elasticsearch/pull/40129/commits/1f0a804438209136bd617365883acc143e57fbae :)

**Review by jaymode — APPROVED** [review]
LGTM. Thanks for the quick iteration @original-brownbear

**Comment by original-brownbear** [comment]
@jaymode np + thanks for the review!

**Pull request merged**
