### PR TITLE
promote longs to strings to make the internal aggs compatible in terms aggregation

### PR DESCRIPTION
**Pull request by garyelephant**
Before keyword type was added to elasticsearch, we use long type for terms query and terms aggregation.After thousands of indices have been created in production environment, we discovered that keyword is the most suitable type for terms query/aggregations, so we wanted to change long type to keyword type, so we created indices using keyword the same field. But unfortunately, term aggregation queries combined with long and keyword will occur the following error which is raise in AbstractInternalTerms or InternalTerms(for old version):

```
Merging/Reducing the aggregations failed when computing the aggregation ["terms_aggs"] because the field you gave in the aggregation query existed as two different types in two different indices
```

It is an incredibly huge work for us to reindex the existing indices for migrating the field type from long to keyword.For most case, it is reasonable to promote longs to strings to make the internal aggs compatible in terms aggregation, just as promote longs to doubles shown in `DoubleTerms`. So I do the same thing in StringTerms.

With this feature, term aggregation queries combined with long and keyword can live in harmony and we can migrate the existing indices field type from long to keyword step by step.

related ISSUE: https://github.com/elastic/elasticsearch/issues/69168

### CODE REVIEW

**Comment by garyelephant** [comment]
Hi，@nik9000 sorry to disturb you, can you give me some advice for this PR ?

**Comment by nik9000** [comment]
The idea made sense to me at first glance. I was hoping to check in with
some more folks familiar with the agg in a few days. I should be able to
get back to you then. Sorry for the delay!

**Comment by nik9000** [comment]
Bad news! I talked to a few folks about this and they seemed to like the idea, but thought that we'd really need to spend more time thinking about sneaky promotion cases that might come from partial reductions. There is a lot to do with `format` in this area too and its somehow related to this promotion. None of us are really sure how, but *somehow*. So we're probably going to wait "a while" before getting to this. Sadly, that might be like six months. I'm really sorry.

You could probably work around this by adding a runtime field to the old index that just `emit(Integer.toString(doc['old'].value))`. Its not as fast as what you've proposed, but it'd get you unstuck.

**Comment by garyelephant** [comment]
@nik9000 Really bad news, is there something I can do to speed up this ? Looks like you folks want to think of a generic implementation that apply for most similar cases, other than just long --> keyword.

**Comment by nik9000** [comment]
I think we're just worried that it'll get all twisted up in the weirdness that is `format` right now. @not-napoleon might be able to talk more precisely about what we're worried about here. And if we have any plans about how to portion out the work we need.

I think in the short run you probably are best off looking at runtime fields. I'd be happy to help with that. It's sort of the least I could do given that you opened this PR.

**Comment by not-napoleon** [comment]
So, to be clear, I haven't done enough digging to be 100% sure about this.  But here are the issues I think we're going to have to resolve:

First off, understand that we have one format parameter, but it's used for multiple things (see #47469).  The format the user passes in gets validated against the field mappings per shard being aggregated, so shards with a long would use the numeric validation logic and shards with the string would use the string validation logic.  But when it gets applied, it will of course be applied to the coerced final type.

A second, related, concern is around the `missing` parameter to the aggregation, which allows users to supply a default value for documents that don't have the relevant field set.  This missing value is supplied once for the whole aggregation, and parsed using format.  Having a string `missing` on a shard that resolves to a long field will (probably, again I haven't tested this) end up with a `NumberFormatException`.  And even if it works now, in general allowing string `missing` values for numeric fields isn't something I would rely on.  And casting the the whole aggregation to string just because the user typed `"missing": "42"` instead of `"missing": 42` seems bad.   Ideally, I think, on a numeric field we'd parse "42" to 42, and throw a format exception for "no value", or other unparsable strings.

The runtime field, on the other hand, has to declare a type which the aggregations framework will be able to read and follow the correct path, no matter what the backing data look like.  This is why I say that's an easier solution than promoting internally - from the aggregation's perspective, it's the same as both fields having the same type.

That said, if you want to explore those edge cases and write some unit tests showing that this change does something sensible with formats and missing values, I'd be happy to take another look.  I don't expect to have time to do that testing myself for a couple of months though.

**Comment by wchaparro** [comment]
closing per https://github.com/elastic/elasticsearch/issues/69168

**Pull request closed without merging**
