### PR TITLE
Fix ignoring require_alias parameter in high level rest client

### PR DESCRIPTION
**Pull request by gaobinlong**
Relates to #67819.

The main changes are:
1. Set the `require_alias` parameter in the `reindex`, `index` and  `update` methods in `RequestConverters` class.
2. Test that the parameter can be parsed correctly.

### CODE REVIEW

**Comment by jakelandis** [comment]
@elasticmachine ok to test

@swallez - can you please take a look at this PR ?

**Comment by mark-vieira** [comment]
@elasticmachine update branch

**Comment by gaobinlong** [comment]
@martijnvg, can this PR be merged now?

**Comment by martijnvg** [comment]
@gaobinlong Thanks for the ping, I will look into this today.

**Comment by martijnvg** [comment]
@elasticmachine update branch

**Comment by martijnvg** [comment]
@elasticmachine run elasticsearch-ci/2

**Review by martijnvg — APPROVED** [review]
Thanks @gaobinlong for fixing this! And apologies to the delay.
I will merge this once pr ci is green.

**Pull request merged**
