### PR TITLE
Logging: tests: clean up logging

### PR DESCRIPTION
**Pull request by lipsill**
Replace internal deprecated calls to `Loggers.getLogger(Class)`
with direct calls to log4j `LogManager.getLogger(Class)`

Relates to: #32174

### CODE REVIEW

**Comment by andyb-elastic** [comment]
Thanks for the pull request @lipsill 

Jenkins, test this please

**Comment by lipsill** [comment]
Ops! CI found a checkstyle error `[ERROR] /var/lib/jenkins/workspace/elastic+elasticsearch+pull-request/plugins/mapper-murmur3/src/main/java/org/elasticsearch/index/mapper/murmur3/Murmur3FieldMapper.java:84: Line is longer than 140 characters (found 141).`
Merging master into the PR: the issue should be fixed by f11a23be2f8cbb3241f63f66df4aabed83ca7080.

**Comment by andyb-elastic** [comment]
Jenkins, ok to test

**Review by nik9000 — APPROVED** [review]
LGTM. I'll try and merge this later today.

**Comment by nik9000** [comment]
Thanks for doing this @lipsill!

**Comment by nik9000** [comment]
Backport complete, thanks @lipsill!

**Pull request merged**
