### PR TITLE
[ML] Remove exceptions from mapping test after backport

### PR DESCRIPTION
**Pull request by davidkyle**
With the backport of the change to add the `ignore_above` parameter the exception in the mapping upgrade test can be removed

### CODE REVIEW

**Review by droberts195 — APPROVED** [review]
LGTM

**Comment by davidkyle** [comment]
run elasticsearch-ci/bwc

**Comment by davidkyle** [comment]
The BWC tests will pass only when run against 7.11 but until 7.10 is released the tests run against 7.10. This will have to be parked until the release

**Comment by droberts195** [comment]
@elasticmachine update branch

**Comment by droberts195** [comment]
@elasticmachine update branch

**Comment by davidkyle** [comment]
Closing as it cannot be merged now. I will reopen when the 7.11 branch is cut

**Comment by droberts195** [comment]
> Closing as it cannot be merged now. I will reopen when the 7.11 branch is cut

Is the problem that it's failing on full cluster restart, not rolling upgrade?  That would explain why master is still testing against pre-7.x branches.  If so I think it will have to wait until the 8.x branch is cut, and master is only doing full cluster restart tests against 8.0...8.x.

**Comment by davidkyle** [comment]
Yes it is the full cluster restart test I didn't spot that even though there was a comment in the code saying so 🤦 

Looking at the code there isn't a simple way to refactor the assertions for full cluster upgrade. Not having this change makes the test lenient in a small way for one field added in 7.10, the work to keep that assertion is not worth the payoff. 

I won't be reopening this PR but will review the assertions once we have an 8.x branch

**Pull request closed without merging**
