### PR TITLE
fix: change visibility of SearchService#ResultsType to protected

### LINKED ISSUE #95670: Change visibility of SearchService$ResultsType to protected
### Description

In [siren federate](https://siren.io/federate/) we extend the `SearchService` to create `SearchContext` instances. In 8.8 this is not possible anymore because the `createContext` method takes the `ResultsType` enum which is package private.

https://github.com/elastic/elasticsearch/blob/b640c217cccab67dce7d954bc92b6b519c102b16/server/src/main/java/org/elasticsearch/search/SearchService.java#L992-L998

In order to be able to keep on calling that method from another package, the visibility of the enum `ResultsType` should be increased to `protected`.

### PR DESCRIPTION
**Pull request by scampi**
Close #95670

### CODE REVIEW

**Comment by javanna** [comment]
heya @scampi this change is trivial, yet it makes me nervous because nothing prevents us from reverting your fix or making other changes that end up breaking your code. We generally keep an eye on the different extension points for plugin developers, but extending `SearchService` is really not something we'd expect users to do. Your usecase sounds more like using Elasticsearch as a library which is something that we can't guarantee will work in the future. Am I misunderstanding? 

I would like to have more info here and clarify whether we can support your usecase moving forrward.

**Comment by scampi** [comment]
We need to extend `SearchService` because we have to create a `SearchContext` instance from a given `ShardSearchContextId`. From a `SearchContext` we can then access different information from the index and perform the following operations:
- Collect document IDs matching a search, not just the top-K.
- Process fields of search-matching documents by accessing docvalues or some index data structure like the k-d tree from the `LeafReader`.
In essence, we need to perform tasks at the segment level, i.e., for a `LeafReaderContext` instance. We need to search a segment or perform other tasks for a given segment with the help of custom services. In some places, we retrieve services via an extension of the `SearchExecutionContext`.

> Your usecase sounds more like using Elasticsearch as a library

This could be a point of view I guess, Federate is still an Elasticsearch plugin but extends it in ways that the plugin API doesn't offer.

**Comment by javanna** [comment]
@elasticmachine test this please

**Comment by javanna** [comment]
thanks for sharing more context @scampi .  This does look like an oversight as the method is protected but has a package private argument, it makes sense to address this. I will merge your PR.

**Comment by javanna** [comment]
@elasticmachine update-branch

**Comment by javanna** [comment]
@elasticmachine retest this please

**Comment by javanna** [comment]
run elasticsearch-ci/part-3

**Comment by scampi** [comment]
@javanna is there anything I can do regarding the test failure ? It looks like a memory leak unrelated to the changes in this PR. I tried running the failed test `testHttpHeaderAuthnFaultyHeaderValidator` but I couldn't find it.

**Comment by scampi** [comment]
@javanna would this be backported to 8.8.x ?

**Comment by javanna** [comment]
Nothing to do on our end, I will merge on Monday, I think that test will either be muted or fixed by then.

We are past feature freeze for 8.8, I don't think this will make it in.

**Review by javanna — APPROVED** [review]
LGTM

**Comment by javanna** [comment]
Thanks @scampi !

**Comment by torito** [comment]
> We are past feature freeze for 8.8, I don't think this will make it in.

Is it possible for this to be included in a patch release (eg 8.8.1 or 8.8.2) ?
Thanks @javanna

**Pull request merged**
