### PR TITLE
support only string format for date, root object & date range

### LINKED ISSUE #23650: Mapping: Specifying a date format as array creates invalid mapping
... yet it is allowed. See this example

**Elasticsearch version**: 5.2.1

```
DELETE test
DELETE test2

PUT test
{
  "mappings": {
    "foo": {
      "properties": {
        "x": {
          "type": "date",
          "format": "yyyy-MM-dd"
        }
      }
    }
  }
}

PUT test2
{
  "mappings": {
    "foo": {
      "properties": {
        "x": {
          "type": "date",
          "format": [ "yyyy-MM-dd" ]
        }
      }
    }
  }
}

GET test/foo/_mapping

GET test2/foo/_mapping

PUT _bulk
{ "index" : {"_index" : "test", "_type" : "foo" } }
{ "x" : "2017-03-20" }
{ "index" : {"_index" : "test2", "_type" : "foo" } }
{ "x" : "2017-03-20" }
```

the mapping calls return

```
GET test/foo/_mapping
{
  "test": {
    "mappings": {
      "foo": {
        "properties": {
          "x": {
            "type": "date",
            "format": "yyyy-MM-dd"
          }
        }
      }
    }
  }
}

GET test2/foo/_mapping
{
  "test2": {
    "mappings": {
      "foo": {
        "properties": {
          "x": {
            "type": "date",
            "format": "[yyyy-MM-dd]"
          }
        }
      }
    }
  }
}
```

Trying to index the same document in both indices results in

```
PUT _bulk
{ "index" : {"_index" : "test", "_type" : "foo" } }
{ "x" : "2017-03-20" }
{ "index" : {"_index" : "test2", "_type" : "foo" } }
{ "x" : "2017-03-20" }

{
  "took": 5,
  "errors": true,
  "items": [
    {
      "index": {
        "_index": "test",
        "_type": "foo",
        "_id": "AVrq5TOq1NgG2ZBFgd-y",
        "_version": 1,
        "result": "created",
        "_shards": {
          "total": 2,
          "successful": 1,
          "failed": 0
        },
        "created": true,
        "status": 201
      }
    },
    {
      "index": {
        "_index": "test2",
        "_type": "foo",
        "_id": "AVrq5TOq1NgG2ZBFgd-z",
        "status": 400,
        "error": {
          "type": "mapper_parsing_exception",
          "reason": "failed to parse [x]",
          "caused_by": {
            "type": "illegal_argument_exception",
            "reason": """Invalid format: "2017-03-20""""
          }
        }
      }
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by nikoncode**
Limit date `format` attribute to String values only (to avoid serialization issues)
Closes #23650

### CODE REVIEW

**Comment by cbuescher** [comment]
@nikoncode sorry for the delay on this, I just found this in unanswered PR while scanning issues. I will update the branch by merging in master if you don't mind and will take a first look then.

**Review by cbuescher — CHANGES_REQUESTED** [review]
@nikoncode thanks again for opening this, I think the PR looks quite good already but I left a suggestion for a change. Would you be interested in making this change? I understand that after waiting for quite some time you might not be interested in working on this any longer. Let me know if you want to pick it up or would like somebody else to work on it. I think its a good change to get in.

**Comment by nikoncode** [comment]
@cbuescher I'll handle it and mention you again to review.

**Comment by nikoncode** [comment]
@cbuescher I don't think that your suggestion is relevant. 

Problem of the original issue is using `format.toString()` method on `List` to convert input into string value. As you know, this method produce comma separated values wrapped in square brackets (for example `[el1]`) and Jodas parser successfully parse this format and threat square brackets as part of user input. We need to differentiate cases when we have `List` separately from when we have `String`. To do it I have added additional validation condition. Just to implement validation in single place. 

If I need to implement your recommendation:
* Instead of generic validation (1 method) I will need to put the same condition to filter out this case before any usage (from 1 to 3 places).
* I have two option how to convert parameter value: 
  * `String.toString()` - just doesn't solve the problem;
  * `(String) format` - solves problem but throws `ClassCastException` instead of meaningful message, we can add 3 more catches to produce good message (see point one);
* `parseDateTimeFormatter` method is part of `TypeParsers` class - the responsibility of this class is to extract useful objects from untyped values (and validate if required). Just look on any other method in this class, all of them get `Object` as input parameter and then going through validation + conversion chain we got useful value as the result.

**Comment by cbuescher** [comment]
> Problem of the original issue is using String.toString() method on List to convert input into string value.

I see. I was trying to avoid adding the `instanceof` check and thought that simply using "toString()" at the call site would work. But I agree this is a bit awkward in Lists, although they would still be rejected by Joda then due to the contained square brackets, for example. But the exception messages are not very descriptive in that case, which is why you convinced me that your solution is better. I will run CI now and merge once that has passed sucessfully.

**Review by cbuescher — APPROVED** [review]

**Comment by cbuescher** [comment]
@elasticmachine test this please

**Comment by cbuescher** [comment]
@nikoncode would you mind adding a bit more detail to the [first comment](https://github.com/elastic/elasticsearch/pull/28117#issue-161483884), since this is what the final commit message will be based on? Otherwise I can also write a few lines, but I think its better if the commit author adds a few words.

**Comment by cbuescher** [comment]
@nikoncode I took the liberty to merge in the current state of the master branch because CI was failing without it. Hope you don't mind.
@elasticmachine test this please

**Comment by nikoncode** [comment]
@cbuescher I have changed my message.
Does it specific enough?

**Review by cbuescher — APPROVED** [review]
Still looking good. I will merge this in shortly

**Pull request merged**
