### PR TITLE
Move pre-configured "keyword" tokenizer to the analysis-common module

### PR DESCRIPTION
**Pull request by nik9000**
Moves the `keyword` tokenizer to the analysis-common module. The `keyword` tokenizer is special because it is used by `CustomNormalizerProvider` so I pulled it out into its own PR. To get the move to work I've reworked the lookup from static to one using the `AnalysisRegistry`. This seems safe enough.

Part of #23658.

### CODE REVIEW

**Comment by nik9000** [comment]
@jpountz, can you have a look at this one?

**Comment by jpountz** [comment]
Does it mean we can't get normalization to work if analysis-common is not on the classpath?

**Comment by nik9000** [comment]
> Does it mean we can't get normalization to work if analysis-common is not on the classpath?

Yes.

**Comment by jpountz** [comment]
The change looks correct to me, but I'm a bit confused about how integration tests that rely on normalization work with this change? We don't put analysis-common on the classpath when running integ tests, do we?

**Comment by nik9000** [comment]
I suspect we don't actually test custom normalizers without analysis-common installed. We have unit tests but they don't need run this particular code. I could only find some documentation that builds a custom normalizer. I didn't see anything in the rest-api-spec.

**Review by jpountz — APPROVED** [review]
OK I got it now, existing tests that make sure we apply normalization are done on predefined analyzers such as the `standard` analyzer, this is why it keeps working. Sorry for the confusion. LGTM.

**Comment by nik9000** [comment]
> OK I got it now, existing tests that make sure we apply normalization are done on predefined analyzers such as the standard analyzer, this is why it keeps working. Sorry for the confusion. LGTM.

Thanks for reviewing! I'll see about  removing the conflicts later today.

**Comment by nik9000** [comment]
Thanks for reviewing @jpountz!

**Pull request merged**
