### PR TITLE
Revert unneeded desired balance changes

### PR DESCRIPTION
**Pull request by DaveCTurner**

### CODE REVIEW

**Comment by DaveCTurner** [comment]
@elasticmachine please run elasticsearch-ci/part-2

**Comment by DaveCTurner** [comment]
@elasticmachine please run elasticsearch-ci/part-3

**Comment by DaveCTurner** [comment]
Hmm I suspect we need to merge `main` into the feature branch to get this to pass. I'll do that after https://github.com/elastic/elasticsearch/pull/89109 is merged.

**Review by idegtiarenko — APPROVED** [review]

**Comment by DaveCTurner** [comment]
@elasticmachine update branch

**Pull request merged**
