### PR TITLE
add support for resetting dynamic cluster settings

### PR DESCRIPTION
**Pull request by seut**
This PR implements support for resetting transient & persistent cluster settings to, either the configuration file value defined at node startup, or if it does not existed, the default value.

Resetting settings is done using the normal cluster update settings API, by just assigning a JSON `null` to the setting one want to reset. See `update-settings.asciidoc` for details.

There are maybe other/smarter ways to do that, but I think this is just straight-forward and it works ;)
This is related to https://github.com/elasticsearch/elasticsearch/issues/6732, but does only apply to cluster settings not custom analyzer.

### CODE REVIEW

**Comment by seut** [comment]
any updates on this?

**Comment by clintongormley** [comment]
Hi @seut 

Sorry for the delay - it's tricky finding time to review big PRs.  We haven't forgotten about it.  Also need to make sure it plays nicely with the changes planned in #6732

**Comment by seut** [comment]
@clintongormley I understand. Will save my time with rebasing the current master until you'll accept the general logic of this code. Or otherwise, please poke me to rebase it.

**Comment by clintongormley** [comment]
thanks @seut

**Comment by s1monw** [comment]
FYI - I opened #15278 which basically supersedes this PR. @seut if you don't mind I will take some REST tests from you and steal some ideas? :)

**Comment by seut** [comment]
@s1monw sure take what you need ;)

**Comment by s1monw** [comment]
closing since https://github.com/elastic/elasticsearch/pull/15278 is merged

**Pull request closed without merging**
