### PR TITLE
Remove deprecated search.remote settings

### PR DESCRIPTION
**Pull request by jasontedor**
We deprecated these settings awhile ago, in favor of cluster.remote. In 7.x we were gentle and provided automatic upgrade of these settings to the new settings. Now it is time for them to go. This commit removes the deprecated search.remote settings.

Relates #33413
Relates #38556

### CODE REVIEW

**Review by rjernst — APPROVED** [review]
Hooray for good comments on what the code should be when fallback is removed! LGTM

**Comment by jasontedor** [comment]
> Hooray for good comments on what the code should be when fallback is removed!

Thanks past self!

**Review by s1monw — APPROVED** [review]
LGTM 2

**Comment by jasontedor** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by jasontedor** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by jasontedor** [comment]
@elasticmachine run elasticsearch-ci/1

**Pull request merged**
