### PR TITLE
Remove PROTO-serialization from IndexMetaData.Custom

### PR DESCRIPTION
**Pull request by imotov**
Switches IndexMetaData.Custom to standard named serialization. In
order to achieve this it also removes support for specifying custom
index metadata on create index and put template requests.

@dakrone as per our discussion

### CODE REVIEW

**Comment by jasontedor** [comment]
> In order to achieve this it also removes support for specifying custom index metadata on create index and put template requests.

This change ruins plans that we have in CCR to use the index metadata to store a UUID (either the index UUID of the leader, or hopefully the history UUID of the leader). We would do this on create and follow requests, for example. What is the motivation for this change and breaking custom index metadata in this way?

**Review by jasontedor — CHANGES_REQUESTED** [review]
I have a concern, which I left as a top-level comment on the PR.

**Comment by imotov** [comment]
@jasontedor I have removed it because I thought that it will not used as part of the templates of create index requests. Supporting custom parsing in templates creates additional complexity (for example, we need to know how to parse both Map and XContent and we parse the template in HL REST response). So, I was trying to avoid this unnecessary complexity mistakenly thinking that we are not going to have any users for it.

**Comment by jasontedor** [comment]
We intend to use custom index metadata in both CCR and ILM. I would prefer that we proof out what our needs are there before we make any changes to custom index metadata. This feature was on its way out (deprecated!) but we are going to resurrect it.

**Comment by imotov** [comment]
I am fine with resurrecting it, I am just not OK with resurrecting it based on PROTO serialization. I left it as is when I was converting the rest of the cluster state to NamedObject serialization because it wasn't used so we marked it as deprecated instead. So, I feel responsible for finishing PROTO off :) I will see if I can migrate it without significant loss of functionality, now that I know that it is needed by more than one efforts.

**Pull request closed without merging**
