### PR TITLE
Reindex max_docs parameter name

### PR DESCRIPTION
**Pull request by henningandersen**
Previously, a reindex request had two different size specifications in the body:
* Outer level, determining the maximum documents to process
* Inside the source element, determining the scroll/batch size.
The outer level size has now been renamed to max_docs to
avoid confusion and clarify its semantics, with backwards compatibility and
deprecation warnings for using size.

Similarly, the size parameter has been renamed to max_docs for
update/delete-by-query to keep the 3 interfaces consistent.

Finally, all 3 endpoints now support max_docs in both body and URL.

Relates #24344

A follow-up to this will remove support for the old name in 8.0 as well as add
breaking changes documentation for 8.0.

### CODE REVIEW

**Review by Tim-Brooks — APPROVED** [review]
LGTM

**Comment by henningandersen** [comment]
Ping @elastic/es-clients since this contains external API changes.

**Comment by russcam** [comment]
Thanks for the ping @henningandersen.

> Same goes for update/delete-by-query except that we no longer support
specifying max_docs inside the body, only as URL query param.

is `max_docs` inside the body also deprecated, to be removed in 8.0?

**Comment by henningandersen** [comment]
Thanks for looking into this @russcam 

> Thanks for the ping @henningandersen.
> 
> > Same goes for update/delete-by-query except that we no longer support
> > specifying max_docs inside the body, only as URL query param.
> 
> is `max_docs` inside the body also deprecated, to be removed in 8.0?

I can see that this was poorly written, let me elaborate. Previously, you could specify `size` either as query parameter directly in the URL or on the root object in the body. Both are deprecated and will be removed in 8.0. The newly introduced `max_docs` (which has same semantics as deprecated `size`) were only added as a query parameter directly in the URL, i.e., you can no longer limit the max documents to process in the body from 8.0.

**Comment by henningandersen** [comment]
Discussed this with @ywelsch on another channel and he rightfully pointed out that the `max_docs` specification is now inconsistently specified in body for reindex and in URL param for update/delete-by-query.

Will update this PR to allow specifying it in both places for all 3 APIs.

**Review by Tim-Brooks — APPROVED** [review]
LGTM - I like the many improvements to the related tests.

**Pull request merged**
