### PR TITLE
Support must and should for context query in context suggester

### LINKED ISSUE #24421: Add option for boolean 'AND' logic to Context Suggester
There are some scenarios where a user might like to filter suggestions via several contexts. However, today the context suggester uses `OR` logic when specifying multiple contexts. For example, a search for:

```
GET myindex/mytype/_search
{
  "suggest": {
    "my_suggestion": {
      "prefix": "sta",
      "completion": {
        "field": "suggest",
        "contexts": {
          "context1": [
            "A"
          ],
          "context2": [
            "11"
          ]
        }
      }
    }
  }
}
```

Will return suggestions that have a context of `"context1" : "A"` OR `"context2" : "11"`. This poses a problem if you'd like to return suggestions to the user for a specific combination of contexts.

As a workaround today, you can concatenate the contexts to simulate the logic:

```
"contexts": {
      "context1_and_2": [
        "A:11"
      ]
    }
```

### PR DESCRIPTION
**Pull request by jimczi**
This is a spin off of #24565

Currently, when multiple contexts are provided for a context
suggester query, the contexts are 'OR'ed. This commit adds
support for specifying `must` operation for contexts, allowing
querying suggestions that have all the contexts.

At first I thought that `must_not` operation would be trivial to add with `must` support but
this operation would require to access all contexts that match at once in order to determine
if a specific suggestion matches or not. Unfortunately we can access only one context at a time
which makes impossible to determine if an excluded context will match or not.

Closes #24421

### CODE REVIEW

**Comment by jimczi** [comment]
While playing a bit with this PR I realized that the method implemented on this PR to handle `must` clause contexts can go OOM in no time. If more than one `must` clause is provided the suggest collection needs to check all matching contexts for a specific document in order to know if the suggestion matches.
Suggestions are collected in a sorted manner, the best score comes first. If all suggestions have the same score (default behavior) this PR would keep all suggestions in memory until all clauses are met for at least N suggestions (the size of the suggest request).  
Moreover if different contexts for the same documents have different scores the method implemented in this PR could skip valid suggestions because the collector would not see all contexts for a specific document.
Because of this findings I don't think we should pursue in this direction even if this feature seems important for some users. The memory consumption and the exactness of the feature are big concerns so I'll mark this with a discuss label for now and we should of course not try to merge this PR as is.
I'll try to think more of this in the next couple of days but I don't see how we could protect against memory explosion or invalid results for now.

**Comment by jpountz** [comment]
+1 to not implement it this way if it can lead to OOMEs

**Comment by speedplane** [comment]
What are the factors determining the memory explosion? From your description, it seems like it's O(M*N), where M=number of contexts and N=number of suggestions in each context.

If that's the case, couldn't we limit the number of contexts to 2 or 3? That would be enough for the vast majority of users until a better solution is worked out.

**Comment by chrisvariety** [comment]
We only need 1 context, and I'm sure most folks could get away with just 1 as well. This is functionality that existed in 2.3 and without it my company and I'm sure scores others are not able to upgrade Elasticsearch 😦 

We do appreciate everything you all are doing, just trying to give some perspective from the enduser perspective.

**Comment by jimczi** [comment]
@speedplane yes the worst case for this solution is to visit all suggestions in the contexts that needs to match. Suppose you have 3 `must` contexts: `red`, `blue` and `green` and all suggestions have the same score then the suggest collector will need to visit all matching suggestions for these 3 contexts to retrieve the best N.
We could limit the number of `must` contexts per query but that would not be enough because the  number of suggestions per context is unbounded. The only solution I see for now if we really want this feature is to limit the number of suggestions to visit per segment but this would mean that some  matching suggestions would not be returned for some queries.

> We only need 1 context, and I'm sure most folks could get away with just 1 as well. This is functionality that existed in 2.3 and without it my company and I'm sure scores others are not able to upgrade Elasticsearch 😦

If you want to search suggestions within a single context this PR is not needed and the current suggester in 5.x works. This PR adds the ability to match suggestions only if they appear in multiple contexts (`must` context clause).

**Comment by elyobo** [comment]
We need three contexts.  The docs were unclear and we incorrectly read them to mean that multiple contexts _were_ ANDed together rather than ORed; some extra clarity there would be helpful.

It's possible to work around this by creating additional pseudo contexts when indexing and querying that instead (e.g. if you have contexts `x` and `y` and need to sometimes match _both_, then also create a context `x_y` and query that instead when you need to match both, using `x` and `y` only when you need to match one or the other).  That doesn't scale well up to a large number of contexts but is doable for a handful.

Definitely keen to see a fix for this, but without OOM errors would be great :D

**Comment by jimczi** [comment]
Some more findings about this issue:
First of all the memory consumption is not an issue. I saw an OOME in a test that  I wrote but I realized that it's not due to this PR and was just related to a small heap size. Lucene sets the maximum suggestions to visit to 5000 per segment and this patch only visits numContexts*size documents at most so memory should not be a problem.
Though I am still not convinced that this solution for doing conjunctions on context values is acceptable because we cannot guarantee that a document with all required contexts will always be found. This means that some query may return no result depending on the number of must contexts and the requested size. This probability grows with the number of duplicate weights in the suggestions.

> It's possible to work around this by creating additional pseudo contexts when indexing and querying that instead (e.g. if you have contexts x and y and need to sometimes match both, then also create a context x_y and query that instead when you need to match both, using x and y only when you need to match one or the other). 

This is what the suggester in 2.x is doing. The only difference is that it restricts the combinations to named contexts so values within a single context are not combined. I think it's the best solution because it allows precise matching at query time and if the number of contexts to combine is low the cost at indexing time is acceptable. We could try to implement this solution in the suggest V2 but you described a workaround that is not difficult to implement as long as the number of contexts to combine is low. Since combinations can explode rapidly I don't think we should handle this natively like 2.x does. We had a lot of problems with too many contexts indexed in 2.x because of this so I think it's better to keep this feature external. 

Because of this restrictions I am closing this PR. There is a workaround that is fine for 2 or 3 contexts that should be preferred since it does not require a lot of work and ensure that the conjunctions query always work. 
 
In the mean time I've started to work on https://github.com/elastic/elasticsearch/issues/23364 which seems to block a lot of users to upgrade to the new suggester. This is the other difference with 2.x completion suggester which returns suggestions and not documents. I'll open a PR soon.

**Comment by adamhadani** [comment]
@jimczi re the above suggested workaround - how does one go about creating a synthetic context composite of two fields? or is the idea to create a synthetic field first (e.g. some mapping that defines the field in terms of the original two fields?) and then use that named field directly as a category context?

**Comment by kgeographer** [comment]
Glad to hear there is a workaround, but can the composite include a category context and a geo context? I can't see how to compose this, got this far...any ideas?
```
        "place_type": { "type": "keyword" },
        "location" : { "type" : "geo_point" },
        "suggest": {  
          "type": "completion",
          "contexts": [
            { "name": "place_type",
              "type": "category",
              "path": "place_type"
            },
            { "name": "loc",
              "type": "geo",
              "path": "location"
            },
            { "name": "type_loc",
              "type": "???",
              "path": "???"
            }
          ]
        }
```

**Pull request closed without merging**
