### PR TITLE
Use SecureSetting to store RCS remote access key

### PR DESCRIPTION
**Pull request by ywangd**
The remote access key is a secret. As such it should be stored in the ES keystore instead of a filtered setting in cluster state.

### CODE REVIEW

**Review by jakelandis — APPROVED** [review]
LGTM

**Comment by ywangd** [comment]
Put this back to draft since we'd like more time to understand the implications.

**Comment by ywangd** [comment]
@jakelandis The code base has evolved since this PR was approved last time and it required quite a bit effort to bring this PR up to date. I'd appreciate if you could give this another look. Apologies that previous commit history is no longer preserved since I force pushed to the branch. Thanks!

**Comment by jakelandis** [comment]
I'll wait to review until the conflicts are resolved.

**Comment by ywangd** [comment]
@jakelandis Merge conflicts are now resolved. Thanks!

**Review by jakelandis — APPROVED** [review]
LGTM (and really nice job on the tests!)

**Comment by ywangd** [comment]
Failure is unrelated and tracked at https://github.com/elastic/elasticsearch/issues/93852

**Pull request merged**
