### PR TITLE
Rewrite SourceToParse with resolved docType

### LINKED ISSUE #36769: [CI] TranslogWriter assertion failed: `seqNo was processed twice`
See https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/827/console

The `:qa:smoke-test-multinode:integTestRunner` task failed while running, non reproducibly (neither Linux nor osx). However the following was in the logs, and I think that might be the trigger for some followup problems

```
[2018-12-18T09:32:35,413][INFO ][o.e.g.GatewayService     ] [node-0] recovered [0] indices into cluster_state
... SKIPPED 26 LINES ...
[2018-12-18T09:32:42,162][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [node-0] fatal error in thread [elasticsearch[n
ode-0][generic][T#3]], exiting
java.lang.AssertionError: seqNo [1] was processed twice in generation [2], with different data. prvOp [Index{id='9LCpwGcBkJN7
eZxaB54L', type='_doc', seqNo=1, primaryTerm=1, version=1, autoGeneratedIdTimestamp=1545125562123}], newOp [Index{id='9LCpwGc
BkJN7eZxaB54L', type='not_doc', seqNo=1, primaryTerm=1, version=1, autoGeneratedIdTimestamp=-1}]
        at org.elasticsearch.index.translog.TranslogWriter.assertNoSeqNumberConflict(TranslogWriter.java:217) ~[elasticsearch
-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
        at org.elasticsearch.index.translog.TranslogWriter.add(TranslogWriter.java:182) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.
0.0-SNAPSHOT]
        at org.elasticsearch.index.translog.Translog.add(Translog.java:543) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT
]
        at org.elasticsearch.index.engine.InternalEngine.index(InternalEngine.java:863) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.
0.0-SNAPSHOT]
        at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:755) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPS
HOT]
        at org.elasticsearch.index.shard.IndexShard.applyIndexOperation(IndexShard.java:729) ~[elasticsearch-7.0.0-SNAPSHOT.j
ar:7.0.0-SNAPSHOT]
        at org.elasticsearch.index.shard.IndexShard.applyTranslogOperation(IndexShard.java:1293) ~[elasticsearch-7.0.0-SNAPSH
OT.jar:7.0.0-SNAPSHOT]
        at org.elasticsearch.index.shard.IndexShard.applyTranslogOperation(IndexShard.java:1280) ~[elasticsearch-7.0.0-SNAPSH
OT.jar:7.0.0-SNAPSHOT]
        at org.elasticsearch.indices.recovery.RecoveryTarget.indexTranslogOperations(RecoveryTarget.java:410) ~[elasticsearch
-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
        at org.elasticsearch.indices.recovery.PeerRecoveryTargetService$TranslogOperationsRequestHandler.messageReceived(Peer
RecoveryTargetService.java:462) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
        at org.elasticsearch.indices.recovery.PeerRecoveryTargetService$TranslogOperationsRequestHandler.messageReceived(Peer
RecoveryTargetService.java:452) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:63) ~[elasti
csearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
        at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1288) ~[elasticsearch-7.0.0-SNAPSH
OT.jar:7.0.0-SNAPSHOT]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:
759) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-7.0.0-SNAP
SHOT.jar:7.0.0-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.RuntimeException: stack capture previous op
        at org.elasticsearch.index.translog.TranslogWriter.assertNoSeqNumberConflict(TranslogWriter.java:222) ~[elasticsearch
-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
        at org.elasticsearch.index.translog.TranslogWriter.add(TranslogWriter.java:182) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.
0.0-SNAPSHOT]
        at org.elasticsearch.index.translog.Translog.add(Translog.java:543) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT
]
        at org.elasticsearch.index.engine.InternalEngine.index(InternalEngine.java:863) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
        at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:755) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
        at org.elasticsearch.index.shard.IndexShard.applyIndexOperation(IndexShard.java:729) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
        at org.elasticsearch.index.shard.IndexShard.applyIndexOperationOnReplica(IndexShard.java:700) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
at org.elasticsearch.action.bulk.TransportShardBulkAction.performOpOnReplica(TransportShardBulkAction.java:427) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
        at org.elasticsearch.action.bulk.TransportShardBulkAction.performOnReplica(TransportShardBulkAction.java:395) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnReplica(TransportShardBulkAction.java:382) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnReplica(TransportShardBulkAction.java:79) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncReplicaAction.onResponse(TransportReplicationAction.java:618) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncReplicaAction.onResponse(TransportReplicationAction.java:578) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
        at org.elasticsearch.index.shard.IndexShard$4.onResponse(IndexShard.java:2478) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
        at org.elasticsearch.index.shard.IndexShard$4.onResponse(IndexShard.java:2456) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
        at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:269) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
        at org.elasticsearch.index.shard.IndexShardOperationPermits.acquire(IndexShardOperationPermits.java:236) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
        at org.elasticsearch.index.shard.IndexShard.lambda$acquireReplicaOperationPermit$11(IndexShard.java:2418) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
        at org.elasticsearch.index.shard.IndexShard.innerAcquireReplicaOperationPermit(IndexShard.java:2523) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
        at org.elasticsearch.index.shard.IndexShard.acquireReplicaOperationPermit(IndexShard.java:2417) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
        at org.elasticsearch.action.support.replication.TransportReplicationAction.acquireReplicaOperationPermit(TransportReplicationAction.java:982) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$AsyncReplicaAction.doRun(TransportReplicationAction.java:688) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$ReplicaOperationTransportHandler.messageReceived(TransportReplicationAction.java:561) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
        at org.elasticsearch.action.support.replication.TransportReplicationAction$ReplicaOperationTransportHandler.messageReceived(TransportReplicationAction.java:546) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
        ... 7 more
```

Plain text log file is at https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/827/consoleText

### PR DESCRIPTION
**Pull request by dnhatn**
We introduce a typeless API in #35790 where we translate the default docType "_doc" to the user-defined docType. However, we do not rewrite the SourceToParse with the resolved docType. This leads to a situation where we have two translog operations for the same document with different types:

- prvOp [Index{id='9LCpwGcBkJN7eZxaB54L', type='_doc', seqNo=1, primaryTerm=1, version=1, autoGeneratedIdTimestamp=1545125562123}]

- newOp [Index{id='9LCpwGcBkJN7eZxaB54L', type='not_doc', seqNo=1, primaryTerm=1, version=1, autoGeneratedIdTimestamp=-1}]

Closes #36769

### CODE REVIEW

**Comment by dnhatn** [comment]
We may have a BWC issue with the Typeless API if the primary is on 7.0 while replicas on 6.x. I'll test that scenario and post the result.

**Comment by markharwood** [comment]
>We may have a BWC issue with the Typeless API if the primary is on 7.0 while replicas on 6.x. I'll test that scenario and post the result.

I'm working on a PR for the bulk API which just hit this. @mayya-sharipova recently changed `IndexRequest` to default `type` to `_doc` but in my PR I need to set it to null so that I know a choice hasn't been made by the user and can inherit any default "global" type given to the containing `BulkRequest`. I found serializing a null type from 7.x to 6.x nodes was causing a null pointer so I had to make sure that the serialized type was defaulted to "_doc" if null. 

The above detail may not change the status quo on the receiving 6.x end which you're tackling here (provided IndexRequest = _doc but mapping = custom type) but it may be useful to know the related work going on and the CI reproduce line that uncovered my issue: https://github.com/elastic/elasticsearch/pull/36549/commits/2db6753f7510997108725e1d8b820ae06cb5fdae

**Review by jpountz — APPROVED** [review]
The change looks good to me.

Yannick talked to me about this issue earlier today and I do agree that we need to find a more robust way to make typeless APIs work on indices that still have a type whose name is different from _doc.

**Comment by dnhatn** [comment]
run Gradle build tests 1

**Comment by dnhatn** [comment]
Thanks @jpountz for reviewing and @markharwood for the heads-up.

**Pull request merged**
