### PR TITLE
Update Painless Fields API design to use mapped types

### PR DESCRIPTION
**Pull request by jdconrad**
This change updates the Painless fields API to use mapped types instead of Java types. For this initial release we only support unsigned long field.

As we now intend to do conversions solely on the field classes themselves, converters and field values have been removed. Instead of using field values potentially as source fallback we will now rely on whatever class is passed into the script to support the `field` method. In the future, this method will need to check if a field exists on doc and if not, then do source fallback itself once that feature is supported.

The path to retrieve a field is also different. Instead of using script doc values we now have our own way to retrieve the fields with a `getScriptField` method added to `LeafDocLookup`. This allows us less restrictive design space to generate the field type based the type in the leaf doc lookup; however, this will still require additional information that we need to plumb through for certain field types. Once we support all the field types this makes it easier to deprecate and remove script doc values.

### CODE REVIEW

**Review by stu-elastic — APPROVED** [review]
We can reuse a lot of the removed tests when we implement basic types in the new design, so let's save those (as requested above).

**Review by stu-elastic — CHANGES_REQUESTED** [review]
Can you find a way to share the same doc values across `ScriptDocValues` and and `DocValuesField`?  Having a penalty for using the fields API and `doc` in the same script is pretty rough for adoption and is surprising behavior.

**Review by stu-elastic — APPROVED** [review]
lgtm

**Comment by jdconrad** [comment]
@stu-elastic @rjernst Thanks for the in depth reviews! I'm still working toward addressing all the feedback, and will commit once that's done.

**Pull request merged**
