### PR TITLE
Follow stats api should return a 404 when requesting stats for a non existing index

### LINKED ISSUE #37021: [CCR] The stats for an unknown index return a 200 status
When we try to access the stats for a follower index that does not exist, we receive a `200` status with the following response

```
GET /unknown/_ccr/stats

Status 200
{
    "indices": []
}
```

To be consistent with other APIs and follow REST standards, it should return a `404` status.

If we try the same with the `/_stats` API we do get the correct status

```sh
GET /unknown/_stats

Response
{
    "error": {
        "root_cause": [
            {
                "type": "index_not_found_exception",
                "reason": "no such index [unknown]",
                "resource.type": "index_or_alias",
                "resource.id": "unknown",
                "index_uuid": "_na_",
                "index": "unknown"
            }
        ],
        "type": "index_not_found_exception",
        "reason": "no such index [unknown]",
        "resource.type": "index_or_alias",
        "resource.id": "unknown",
        "index_uuid": "_na_",
        "index": "unknown"
    },
    "status": 404
}
```

### PR DESCRIPTION
**Pull request by martijnvg**
Currently it returns an empty response with a 200 response code.

Closes #37021

### CODE REVIEW

**Review by dnhatn — APPROVED** [review]
LGTM. Thanks @martijnvg.

**Comment by martijnvg** [comment]
@dnhatn I've changed the implementation to resolve follower index names in the persistent tasks. I realized that using `IndexNameExpressionResolver`, it a bad idea, because it would also resolve non follower indices and then the response would still be empty with a 200 response code.

**Comment by martijnvg** [comment]
@elasticmachine run elasticsearch-ci-1

**Comment by martijnvg** [comment]
@elasticmachine run gradle build tests 1

**Review by dnhatn — APPROVED** [review]
LGTM. I left a minor comment.

**Pull request merged**
