### PR TITLE
Test housekeeping: Remove error message check from sparse_vector yaml tests

### PR DESCRIPTION
**Pull request by kderusso**
The `sparse_vector` yaml tests require requests to specify one of `inference_id` or `query_vector` to be considered a valid request. 

This is not correct behavior for multiple reasons: 

- Defaulting to built-in ELSER models 
- https://github.com/elastic/elasticsearch/pull/118617 will infer the `inference_id` from the `semantic_text` field when applicable. 

This test alters some specific error checking so that backward compatibility tests continue to run (returning bad request but not validating errors) and specific error message validation will be added in https://github.com/elastic/elasticsearch/pull/118617. 

This felt like a better option than muting tests.

### CODE REVIEW

**Review by pquentin — APPROVED** [review]
For what it's worth, this looks good to me!

**Comment by kderusso** [comment]
@elasticsearchmachine test this please

**Comment by kderusso** [comment]
@elasticmachine test this please

**Review by Mikep86 — APPROVED** [review]

**Comment by kderusso** [comment]
@elasticsearchmachine test this please

**Comment by kderusso** [comment]
Closing this PR as the team disagrees that the old error messaging needs to be changed.

**Pull request closed without merging**
