### PR TITLE
Add unit tests for DateHistogramAggregator

### PR DESCRIPTION
**Pull request by tlrx**
Adds unit tests for the date histogram aggregator.

Relates #22278

### CODE REVIEW

**Comment by tlrx** [comment]
@jpountz you might be interested in reviewing this one (because in #22278 you've been assigned to  HistogramAggregator unit tests)

**Comment by jimczi** [comment]
LGTM

**Review by jpountz — APPROVED** [review]
LGTM

**Comment by tlrx** [comment]
Thanks @jimczi @jpountz

**Pull request merged**
