### PR TITLE
ilm test - allow more time for policy completion

### PR DESCRIPTION
**Pull request by jakelandis**
This was found while testing out the new --parallel changes.

### CODE REVIEW

**Comment by jakelandis** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by jakelandis** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by jakelandis** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by jakelandis** [comment]
@elasticmachine update branch

**Review by AthenaEryma — APPROVED** [review]
LGTM once CI is happy (which might be a while...)

**Comment by jakelandis** [comment]
@elasticmachine update branch

**Comment by jakelandis** [comment]
@elasticmachine update branch

**Pull request merged**
