### PR TITLE
SQL: document the use of a filter on _routing

### PR DESCRIPTION
**Pull request by astefan**
Added a TIP for searching using a routing key, since the `routing` URL parameter is not supported in SQL.
Also, polished some sections of the documentation (especially the functions ones) to fix the Description's way of being displayed.

### CODE REVIEW

**Comment by astefan** [comment]
http://elasticsearch_52355.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/xpack-sql.html for live preview.

**Review by matriv — COMMENTED** [review]
LGTM. Nice find and addition with the `_routing`
From a quick look I couldn't see any change in the resulting HTML regarding the `description` changes, what am I missing?

**Comment by astefan** [comment]
> LGTM. Nice find and addition with the `_routing`
> From a quick look I couldn't see any change in the resulting HTML regarding the `description` changes, what am I missing?

@matriv 

image
VS.
image

**Review by bpintea — APPROVED** [review]

**Comment by bpintea** [comment]
> what am I missing?

the space introduced between `Description:` and following text.

**Review by matriv — APPROVED** [review]
LGTM, I guess we could backport it to 7.6 as well?

**Pull request merged**
