### PR TITLE
[ML] Exclude analysis fields with core field names from anomaly results

### LINKED ISSUE #39406: Can't create anomaly detector that uses "_index" as "partition_field_name"
**Elasticsearch version** (`bin/elasticsearch --version`):
```
Version: 6.5.0, Build: default/tar/816e6f6/2018-11-09T18:58:36.352602Z, JVM: 10.0.1
```

**Plugins installed**: []

**JVM version** (`java -version`):
```
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)
```

**OS version** (`uname -a` if on a Unix-like system):
```
Darwin ElasticMBP 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
```

**Description of the problem including expected versus actual behavior**:
It is not possible to create an anomaly detector that uses `_index` as `partition_field_name`. This can be a valid use case if one wants to find anomalies in document count per index, for instance.

The workaround is to use another field to carry the index name. The field can be created by either reindexing or creating a field alias.

**Steps to reproduce**:

 1. Try to create an anomaly detector with:
```
PUT _xpack/ml/anomaly_detectors/test
{
  "description": "",
  "established_model_memory": 218234,
  "analysis_config": {
    "bucket_span": "15m",
    "detectors": [
      {
        "detector_description": "low count",
        "function": "low_count",
        "partition_field_name": "_index",
        "detector_index": 0
      }
    ]
  },
  "analysis_limits": {
    "model_memory_limit": "100mb",
    "categorization_examples_limit": 4
  },
  "data_description": {
    "time_field": "@timestamp",
    "time_format": "epoch_ms"
  },
  "results_index_name": "shared"
}
```
 2. Results in:
```
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "Field [_index] is defined twice in [doc]"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "Field [_index] is defined twice in [doc]"
  },
  "status": 400
}
```

**Provide logs (if relevant)**:
```
[2019-02-26T13:44:27,696][DEBUG][o.e.c.m.MetaDataCreateIndexService] [gzsj5Rv] [.ml-anomalies-shared] failed to create
java.lang.IllegalArgumentException: Field [_index] is defined twice in [doc]
	at org.elasticsearch.index.mapper.MapperMergeValidator.lambda$checkFieldUniqueness$0(MapperMergeValidator.java:86) ~[elasticsearch-6.5.0.jar:6.5.0]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1492) ~[?:?]
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[?:?]
	at org.elasticsearch.index.mapper.MapperMergeValidator.checkFieldUniqueness(MapperMergeValidator.java:81) ~[elasticsearch-6.5.0.jar:6.5.0]
	at org.elasticsearch.index.mapper.MapperMergeValidator.validateMapperStructure(MapperMergeValidator.java:58) ~[elasticsearch-6.5.0.jar:6.5.0]
	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:479) ~[elasticsearch-6.5.0.jar:6.5.0]
	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:399) ~[elasticsearch-6.5.0.jar:6.5.0]
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:323) ~[elasticsearch-6.5.0.jar:6.5.0]
	at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService$IndexCreationTask.execute(MetaDataCreateIndexService.java:451) ~[elasticsearch-6.5.0.jar:6.5.0]
	at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:45) ~[elasticsearch-6.5.0.jar:6.5.0]
	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:639) ~[elasticsearch-6.5.0.jar:6.5.0]
	at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:268) ~[elasticsearch-6.5.0.jar:6.5.0]
	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:198) [elasticsearch-6.5.0.jar:6.5.0]
	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:133) [elasticsearch-6.5.0.jar:6.5.0]
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) [elasticsearch-6.5.0.jar:6.5.0]
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) [elasticsearch-6.5.0.jar:6.5.0]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:624) [elasticsearch-6.5.0.jar:6.5.0]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:244) [elasticsearch-6.5.0.jar:6.5.0]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:207) [elasticsearch-6.5.0.jar:6.5.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:844) [?:?]
```

### PR DESCRIPTION
**Pull request by yana2301**
Added "_index", "_type", "_id" to list of reserved fields.

Closes #39406

### CODE REVIEW

**Comment by droberts195** [comment]
Jenkins test this please

**Comment by droberts195** [comment]
@yana2301 the elasticsearch-ci/2 CI check is showing that another change is required in the unit tests: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-2/11822/testReport/junit/org.elasticsearch.xpack.core.ml.job.persistence/ElasticsearchMappingsTests/testResultsMapppingReservedFields/

Try running this locally and I think you'll get the same failure:

```
./gradlew :x-pack:plugin:core:test --tests org.elasticsearch.xpack.core.ml.job.persistence.ElasticsearchMappingsTests
```

Then you can fix it and confirm the fix locally.

**Comment by yana2301** [comment]
@droberts195 fixed the test

**Comment by droberts195** [comment]
Jenkins test this please

**Comment by droberts195** [comment]
@yana2301 now different tests are failing because it's not correct to add the core ES fields like `_id` and `_index` into index mappings.  You can see which tests by clicking the "Details" links next to the various Jenkins jobs in the "Some checks were not successful" section.

There is a section in `ElasticsearchMappingsTests.java` that looks like this:

```
    // These are not reserved because they're Elasticsearch keywords, not
    // field names
    private static List<String> KEYWORDS = Arrays.asList(
```

I think the correct fix is to revert your second commit on this PR and then add the 3 extra internal field names into that `KEYWORDS` list.  See if that fixes the test that was failing originally without breaking any other tests.

**Comment by yana2301** [comment]
@droberts195 the test checks that
 ReservedFieldNames.RESERVED_CONFIG_FIELD_NAMES(where I added 3 new fields)  = 
 collectConfigDocFieldNames() - KEYWORDS set. 
 Now it fails because collectConfigDocFieldNames()  does not contain 3 added fields. 
Adding new fields to KEYWORDS won't help - since KEYWORDS are excluded from collectConfigDocFieldNames() before comparison(line 97 of ElasticsearchMappingTests). 
I tried to fix the test by adding new fields inside collectConfigDocFieldNames() method - as a result multiple tests failed. 
Could you tell me please, maybe it makes sense to add these 3 fields just inside the testConfigMapppingReservedFields()?

**Comment by droberts195** [comment]
> Could you tell me please, maybe it makes sense to add these 3 fields just inside the testConfigMapppingReservedFields()?

I think it makes sense to add the 3 extra fields to `ReservedFieldNames.RESERVED_CONFIG_FIELD_NAME_ARRAY`, because they shouldn't be added as dynamic fields in the config index as well as the results index.  If you do that then the test should be OK with the 3 extra fields in `KEYWORDS`.

**Comment by yana2301** [comment]
@droberts195 pushed the change you suggested, however now testConfigMapppingReservedFields test fails - because collectConfigDocFieldNames() doesn't return _id, _index, _type. Also adding fields to KEYWORDS doesn't help - because fields in KEYWORDS are removed from the result of collectConfigDocFieldNames() before comparison

**Comment by droberts195** [comment]
@yana2301 please try pushing a third commit to add the 3 extra fields to `RESERVED_CONFIG_FIELD_NAME_ARRAY` in `ReservedFieldNames.java`.

(In the first commit you added them to `RESERVED_RESULT_FIELD_NAME_ARRAY`, but I think the test is showing that they should be in `RESERVED_CONFIG_FIELD_NAME_ARRAY` too.)

**Comment by yana2301** [comment]
@droberts195 added fields to RESERVED_CONFIG_FIELD_NAME_ARRAY

**Comment by droberts195** [comment]
Jenkins test this please

**Comment by droberts195** [comment]
Jenkins test this please

**Comment by droberts195** [comment]
@yana2301 sorry, my suggestion of putting the extra fields in `KEYWORDS` was wrong.  It needs to be a different list that is added to the expected results, not one that is taken away.  I pushed another commit that does this and the tests are running for longer without failing than they did before.  Let's leave them to run and see if anything fails in the more complex integration tests later on.

**Comment by droberts195** [comment]
Jenkins run elasticsearch-ci/default-distro

**Comment by droberts195** [comment]
Jenkins run elasticsearch-ci/bwc

**Comment by droberts195** [comment]
Jenkins run elasticsearch-ci/1

**Comment by droberts195** [comment]
Jenkins test this please

**Review by droberts195 — APPROVED** [review]
LGTM

The tests have passed after merging in the latest changes on the master branch.

Thanks for the contribution @yana2301 - I'll merge this now.

**Pull request merged**
