### PR TITLE
Manage Fleet system indices within Elasticsearch

### PR DESCRIPTION
**Pull request by jaymode**
This commit moves the management of seven system indices that are used
by Fleet to an Elasticsearch plugin. The mappings were taken largely
untouched from the Fleet server project, with the exception of adding
a _meta field with a version key to enable the system indices
infrastructure to manage these indices.

### CODE REVIEW

**Comment by aleksmaus** [comment]
Thank you!

**Comment by williamrandolph** [comment]
@jaymode What are your thoughts on adding tests that verify the configuration and mappings of these system indices? On the one hand, we're adding some untested code here; on the other, this might be covered by the fleet tests already.

**Comment by jaymode** [comment]
@williamrandolph I agree that we want to add a basic verification test and I am planning to add one. I wanted to get this up sooner rather than later for the fleet team to verify

**Review by williamrandolph — APPROVED** [review]
Looks good to me!

**Comment by aleksmaus** [comment]
@jaymode we made some changes to mappings. will push the update later today.

**Comment by aleksmaus** [comment]
Jay, I tested e2e with the agent. There are couple of follow up PRs in the Kibana and Fleet Server. Should be good to merge now.

**Pull request merged**
