### PR TITLE
Make `ParentTaskAssigningClient.getRemoteClusterClient` method also return `ParentTaskAssigningClient`

### PR DESCRIPTION
**Pull request by przemekwitek**
Currently, if we use `ParentTaskAssigningClient` and want to spawn a remote request, we need to:
1. get remote client using `.getRemoteClusterClient` method
2. call `.setParentTask` on the remote request method manually

This PR makes it so the remote client obtained by calling `.getRemoteClusterClient` method is also a `ParentTaskAssigningClient` so there is no need to call `.setParentTask` on the child request anymore.

### CODE REVIEW

**Comment by przemekwitek** [comment]
> Pinging the distributed team. This involves remote clusters so I'd appreciate your thoughts.

Just a note that from the ML team perspective this PR is not needed anymore as we were able to manage our issue differently (using `getParentTask` accessor introduced in https://github.com/elastic/elasticsearch/pull/101103).
I just thought it will be cleaner to carry the property of parent task also to remote sub-clients.
But if you think the risk of breaking the existing code is too big, I can drop this PR.

**Review by DaveCTurner — APPROVED** [review]
LGTM (I fixed up the merge issues)

**Comment by przemekwitek** [comment]
> LGTM (I fixed up the merge issues)

Thanks for the review.
FYI: I still needed to do the rebase on `main`.

**Comment by DaveCTurner** [comment]
Thanks Przemek. Not sure what exactly happened there, the commits you pushed appear to duplicate what I did?

**Comment by przemekwitek** [comment]
> Thanks Przemek. Not sure what exactly happened there, the commits you pushed appear to duplicate what I did?

The tests were failing, so I did the following:
1. rebase on `main`
```
git rebase -i main  
```
2. pull your changes from this PR
```
git pull przemekwitek parent_task_assigning_client 
```
3. resolve conflicts
4. push merged version 

This version passed the test and it seems the end state of the code is as it should be.

**Pull request merged**
