### PR TITLE
Docs: Fix watcher main title

### PR DESCRIPTION
**Pull request by spinscale**
The docs list a confusing paragraph named `Watch for cluster and index events` which contains the whole watcher documentation. That should probably be named with something like watcher in its name.

image

### CODE REVIEW

**Comment by jrodewig** [comment]
Thanks @spinscale. I pushed fbdd38cd57d03143e8a0cf3b80fc61aa684940a4 to change the title and include "Watcher" in the intro paragraph.

From what I understand, Kibana Alerting is now preferred. We likely don't want to confuse users by using "Alerting" in the title here.

I'd like to get @debadair's feedback before merging this in. Thanks again for raising this!

**Comment by spinscale** [comment]
side note: In the Kibana docs it gets referred as 'Elasticsearch Alerting', so we should probably just make sure that nomenclature is in sync. See https://www.elastic.co/guide/en/kibana/7.x/alerting-getting-started.html#alerting-concepts-differences

**Comment by jrodewig** [comment]
Thanks @spinscale. I agree. If we make this title change, we should also update that reference in the Kibana docs.

**Comment by jrodewig** [comment]
@elasticmachine update branch

**Comment by jrodewig** [comment]
Talk with @debadair offline, and she's good with these changes. I'm going to merge this in and backport it.

I've opened https://github.com/elastic/kibana/pull/106565 to update the reference in the Kibana docs. Thanks again @spinscale!

**Comment by jrodewig** [comment]
@elasticmachine update branch

**Review by jrodewig — APPROVED** [review]

**Pull request merged**
