### PR TITLE
Fix watcher HttpClient URL creation

### LINKED ISSUE #44970: Watcher webhook actions returning 302 response code in 7.2 and above.
**Elasticsearch version** (`bin/elasticsearch --version`): 7.2, 7.3

**Plugins installed**: []

**JVM version** (`java -version`): Bundled JDK

**OS version** (`uname -a` if on a Unix-like system): ESS and Darwin Kernel Version 18.6.0

**Description of the problem including expected versus actual behavior**: Watcher web hook actions do not return a 200 status code for POST requests.

**Steps to reproduce**: Execute a watch with a webhook action.

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Create watch with a webhook action.
 2. Force execute watch, or wait for it to trigger

As of `7.2`, webhook actions are are returning a `302` http status code for POST requests, as opposed to `200`. After some initial discussions with @jakelandis, there is nothing obvious in the codebase that would cause this.

The same exact webhook action in `7.1` and below works fine. All other http clients (tested with curl, wget and postman) all return the expected response. 

This has been tested (an initially spotted) in ESS, and also on my MBP.

### PR DESCRIPTION
**Pull request by spinscale**
The http client could end up creating URLs, that did not resemble the
original one, when encoding. This fixes a couple of corner cases, where
too much or too few slashes were added to an URI.

Closes #44970

### CODE REVIEW

**Review by jakelandis — APPROVED** [review]
LGTM

**Comment by spinscale** [comment]
@jakelandis any objections of putting this into the 7.3 branch?

**Comment by jakelandis** [comment]
@spinscale - no objections, let me know if you want me to handle the merge and/or backports

**Comment by spinscale** [comment]
@elasticmachine update branch

**Pull request merged**
