### PR TITLE
[DOC] Air gapped environments and GEOIP

### PR DESCRIPTION
**Pull request by lucabelluccini**
Closing https://github.com/elastic/elasticsearch/issues/85542

Please review/amend the text and formatting if necessary.

Also, backport to previous version (up to 7.14 I suppose).

### CODE REVIEW

**Review by dakrone — APPROVED** [review]
LGTM

**Review by dakrone — CHANGES_REQUESTED** [review]
Actually, @lucabelluccini no PRs should be targeting the `main` branch directly yet. Could you change where this PR targets please?

**Comment by lucabelluccini** [comment]
Sorry @dakrone should I target branch 8.2 and then we backport?

**Comment by dakrone** [comment]
@lucabelluccini target `master` and then backport from there

**Comment by lucabelluccini** [comment]
Should be targeting `master` now - I thought they were the same 🤦

**Comment by wallrik** [comment]
Please do not put this in the documentation. I think there's a misunderstanding somewhere... You cannot access the internet across an air gap. **That's the whole point.** If you connect your network to the internet you no longer have an air gap.

If you want to put a similar note in the documentation it should probably say something like,

> If your cluster is behind a default denying firewall, or the software firewall on your nodes deny outbound traffic, the Elasticsearch nodes require access to `https://geoip.elastic.co` and `https://storage.googleapis.com`.

Please see the most well-established definition of an air gap in [RFC 4949](https://datatracker.ietf.org/doc/html/rfc4949#section-4). Also, see [Wikipedia](https://en.wikipedia.org/wiki/Air_gap_(networking)).

**Comment by lucabelluccini** [comment]
I am not a technical writer and thank you @wallrik for the suggestion.

**Comment by lockewritesdocs** [comment]
@lucabelluccini, should this PR also target previous versions back to 8.0? If so, I can add those version labels and also add the label to backport this PR automatically.

**Comment by lucabelluccini** [comment]
I think we can backport in all versions back to 7.14

**Review by lockewritesdocs — APPROVED** [review]
LGTM 🦖 I added the appropriate version labels and the auto-backport label, so this is ready to merge.

**Pull request merged**
