### PR TITLE
Cleanup versioned deprecations in analysis

### PR DESCRIPTION
**Pull request by rjernst**
This commit removes versioned logic in analyzer creation that is no
longer relevant for 8.0.

relates #41164

### CODE REVIEW

**Review by romseygeek — APPROVED** [review]
LGTM

**Comment by rjernst** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample

**Comment by rjernst** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by rjernst** [comment]
@elasticmachine run elasticsearch-ci/default-distro

**Pull request merged**
