### PR TITLE
 Add integration tests to verify CCS output

### PR DESCRIPTION
**Pull request by javanna**
We recently introduced the option to minimize network roundtrips when
executing cross-cluster search requests. All the changes made around
that are separately unit tested, and there are some yaml test that
exercise the new code-path which involves multiple coordination steps.
This commit adds new integration tests that compare the output given by
CCS when running the same queries using the two different execution
modes available.

Relates to #32125

### CODE REVIEW

**Review by cbuescher — APPROVED** [review]
LGTM

**Comment by javanna** [comment]
@jimczi this is ready, would you mind having a look too?

**Review by jimczi — APPROVED** [review]
LGTM

**Comment by javanna** [comment]
run elasticsearch-ci/bwc

**Comment by javanna** [comment]
run elasticsearch-ci/default-distro

**Comment by javanna** [comment]
run elasticsearch-ci/packaging-sample

**Pull request merged**
