### PR TITLE
Aggregations: Add 'offset' option to date_histogram

### PR DESCRIPTION
**Pull request by cbuescher**
Add offset option to 'date_histogram', deprecating the previous 'pre_offset' and 'post_offset' options.
This change is part of a larger clean up task for `date_histogram` from issue #9062.

### CODE REVIEW

**Comment by cbuescher** [comment]
Related to #9062, only on 1.x branch the `offset` option should be added alongside the old `pre_offset` and `post_offset` option on the REST layer, these should use ParseField and be marked as deprecated in the migration notes.

**Comment by jpountz** [comment]
This looks good. Maybe also annotate the pre/postOffset methods as deprecated in `DateHistogramBuilder`?

**Comment by cbuescher** [comment]
Added the deprecation annotations and also the offset method to Builder.

**Comment by jpountz** [comment]
LGTM

**Comment by cbuescher** [comment]
Thanks, pushed this to 1.x with d4de973.

**Pull request closed without merging**
