### PR TITLE
Fix setting by time unit

### PR DESCRIPTION
**Pull request by jasontedor**
This commit fixes an issue with a settings builder method that allows setting a duration by time unit. In particular, this method can suffer from a loss of precision. For example, if the input duration is 1500 microseconds then internally we are converting this to "1ms", demonstrating the loss of precision. Instead, we should internally convert this to a TimeValue that correctly represents the input duration, and then convert this to a string using a method that does not lose the unit. That is what this commit does.

### CODE REVIEW

**Comment by jasontedor** [comment]
This is related to #37171.

**Comment by jasontedor** [comment]
@dnhatn Oops, thanks. I missed it in `git add`.

**Review by dnhatn — APPROVED** [review]
LGTM.

**Comment by jasontedor** [comment]
@elasticmachine run gradle build tests 1

**Pull request merged**
