### PR TITLE
Synthetic _source: fix extra fields in GET

### PR DESCRIPTION
**Pull request by nik9000**
The fields loaded to support synthetic `_source` were all coming back in
the `fields` response of `GET` which was confusing. This removes them
from the results unless they are explicitly asked for.

### CODE REVIEW

**Review by romseygeek — APPROVED** [review]
LGTM

**Comment by nik9000** [comment]
Thanks @romseygeek !

**Comment by javanna** [comment]
Heya @nik9000 , it looks like this PR changed behaviour around GET returning `_ignored` by default. Was that on purpose? It is marked bugfix but I think it ended up introducing a breaking change around `_ignored` handling, what do you think? See https://github.com/elastic/elasticsearch/issues/107750#issuecomment-2475737576 for more context.

**Comment by nik9000** [comment]
> Heya @nik9000 , it looks like this PR changed behaviour around GET returning `_ignored` by default. Was that on purpose?

Sorry for missing this ping!

I didn't mean to change the behavior of `_ignored`, no. I was just looking to not return the stored fields that synthetic_source used to rebuild itself as `fields`. Sorry!

**Pull request merged**
