### PR TITLE
Add Persian language stemmer

### LINKED ISSUE #98911: Add Persian language stemmer (token filter)
### Description

Hi,
It would be great if you could add the Persian (Farsi) language to the list of supported stemmers.
The Lucene project has a stemmer for Persian as of May 2022 that you can use.
https://github.com/apache/lucene/tree/main/lucene/analysis/common/src/java/org/apache/lucene/analysis/fa

### PR DESCRIPTION
**Pull request by rezatorabi**
This pull request adds a stemmer for the Persian (Farsi) language. It is trying to fix #98911.

### CODE REVIEW

**Comment by rezatorabi** [comment]
@mayya-sharipova 
Hi Mayya.
Could you please review this pull request? It won't take long.
Sorry if I mentioned you wrong. You were the only one who had any kind of interaction with the related issue.

**Comment by romseygeek** [comment]
@elasticmachine ok to test

**Comment by romseygeek** [comment]
Thanks for opening this PR @rezatorabi!  It looks good to me overall.  I've triggered CI on it which may find some nits, let's see what it comes up with.

**Review by romseygeek — COMMENTED** [review]
CI is happy and so am I!

**Review by romseygeek — APPROVED** [review]

**Comment by romseygeek** [comment]
Thanks @rezatorabi

**Comment by rezatorabi** [comment]
Thanks @romseygeek for the fast review and merge.

**Pull request merged**
