### PR TITLE
Port lucene fix github-11986 to Elasticsearch 7.17

### PR DESCRIPTION
**Pull request by iverase**
This change changes the iteration to make sure we compute the tangent for all nodes of the polygon which seems to help 
finding always the right bridge. 

see https://github.com/apache/lucene/pull/11988

### CODE REVIEW

**Comment by iverase** [comment]
@elasticsearchmachine update branch

**Comment by iverase** [comment]
@elasticmachine please test this

**Comment by iverase** [comment]
@elasticsearchmachine run elasticsearch-ci/part-2

**Comment by iverase** [comment]
@elasticsearchmachine run elasticsearch-ci/eql-correctness

**Comment by iverase** [comment]
@elasticsearchmachine run elasticsearch-ci/docs

**Review by craigtaverner — APPROVED** [review]
LGTM

**Pull request merged**
