### PR TITLE
Replace OpenFollowerIndexStep with OpenIndexStep

### PR DESCRIPTION
**Pull request by andreidan**
This replaces OpenFollowerIndex step with OpenIndexStep.

### CODE REVIEW

**Review by dakrone — APPROVED** [review]
So this looks good, but I have a concern about preexisting indices that are in the `open-follower-index` step when the cluster is shut down. This isn't going to cause them to be orphaned and unable to proceed when the cluster is started back up but the step doesn't exist any more is it?

**Comment by andreidan** [comment]
@dakrone thanks for bringing this up. I went ahead and tested this and indeed if we change the name of the step and at upgrade time some managed indices were in the (previously named) `open-follower-index` step the ILM policies will not be able to make progress but get 
```
[o.e.x.i.IndexLifecycleRunner] [dracula] current step [{"phase":"hot","action":"unfollow","name":"open-follower-index"}] for index [.ds-testing-2021.01.12-000001] with policy [testing_policy] is not recognized
```

I've kept the name `open-follower-index` (https://github.com/elastic/elasticsearch/pull/67254/commits/75789ba0737dc1c97f36bbac886e54f84caa19e8) to aid with this. 
I tested this and the ILM policies that are in the `open-follower-index` step at upgrade time will be resumed successfully if we maintain the name.

There is a small gotcha (took me quite a bit of time to figure this one out - probably because I was testing with one node) but in order for the policy execution to be resumed after the upgrade I had to force it using 
```
POST _ilm/move/.ds-testing-2021.01.12-000001
{
  "current_step": { 
    "phase": "hot",
    "action": "unfollow",
    "name": "open-follower-index"
  },
  "next_step": { 
    "phase": "hot",
    "action": "unfollow",
    "name": "open-follower-index"
  }
}
```
as the `open-follower-index` step is an `AsyncActionStep` which would be executed after a cluster state update. 
I wonder if we can be more verbose around this behaviour somehow? (documentation?) What do you think?

**Comment by andreidan** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by andreidan** [comment]
> @elasticmachine run elasticsearch-ci/2

opened https://github.com/elastic/elasticsearch/issues/67427 for the failure

**Comment by dakrone** [comment]
> as the open-follower-index step is an AsyncActionStep which would be executed after a cluster state update.
> I wonder if we can be more verbose around this behaviour somehow? (documentation?) What do you think?

This step should still be run on a restart though, because we invoke it in `onMaster` in `IndexLifecycleService`. Maybe I am misunderstanding the issue?

**Comment by andreidan** [comment]
> This step should still be run on a restart though, because we invoke it in `onMaster` in `IndexLifecycleService`. Maybe I am misunderstanding the issue?

@dakrone I opened https://github.com/elastic/elasticsearch/issues/67506 for this situation

**Review by dakrone — APPROVED** [review]
LGTM, thanks for the manual testing and fixing the other bug Andrei

**Pull request merged**
