### PR TITLE
Filtered Auto Suggest on Nested Model

### PR DESCRIPTION
**Pull request by nilabhsagar**
# Filtered Auto Suggest for Nested Data Model

The filtered auto suggester provides auto-complete/search-as-you-type functionality like completion/context suggester and adds on flexible filtering capability which works even on nested model. The input and the filter field both can reference the existing fields in the document. 

**Features**

- **Flexible Filtering:** Suggestions can now be filtered with fields specified as filters in the mapping.
- **Read Input from other Fields:** This enables the suggester field values to be picked from other input fields in the documents, however the old behavior of inline input values being specified in the suggest field is supported as well.
- **Nested Support:** Both the suggest field and the filters can be nested to any level.

Mapping, Query and Response interfaces follow/extend the interfaces of context suggester.

**Background:** This feature has originated from a business requirement at Optum. Elasticsearch was being used for searching and aggregating providers represented by deeply nested models. Eventually, we required filtered auto suggestion on the same model. This feature has been tested on a real data set of 8 million provider documents(5 nested level) in-turn having a total of 1.3 billion entities.

**Addresses this:** https://discuss.elastic.co/t/context-suggestor-in-elastic-search-applied-on-the-nested-fields/44946

@sergbass The use case which you have you pointed out in an issue [#18657](https://github.com/elastic/elasticsearch/issues/18657#issuecomment-234236466) can also be solved by indexing your document as nested model and using this pull request for auto suggestion.

**Our observation:**
We developed this first using XAnalysingSuggester and later ported it to NRTSuggester.Differences which we noticed are as below

- **Memory utilization:** The benchmark which was done using 1 million nested documents inturn having a total of ~200 million entities. The mapping had
                   - 4 filteredsuggest fields at different nested level
                   - 3 filters per suggest field
            Observed completion size
            NRTSuggester: ~3 GB
            XAnalysingSuggester: ~0.6 GB

	*Note: Current filteredsuggest implementation is done using NRTSuggester.

- The number of suggestions in the suggest response were less than the actual matches: It seems many people have identified this issue as below
	[#22912](https://github.com/elastic/elasticsearch/issues/22912)
	[#21676](https://github.com/elastic/elasticsearch/issues/21676)
        [#23012](https://github.com/elastic/elasticsearch/issues/23012)
	http://stackoverflow.com/questions/41744712/word-oriented-completion-suggester-elasticsearch-5-x 

## Mapping
For this functionality to work a field of type "filteredsuggest" has to be defined at mapping time.
**Format:**
```
{
       ...
      "suggest_field_name": {
      "type": "filteredsuggest",
      "parent_path": <Nested path for this suggestion field>,
      "input_fields": "Read suggestion value from field/(s),
      "filters": {
        <Category filters>
      }
    }
}
```
**Filters**
Filters suggestions by criteria considering the nested hierarchy. At present the supported filter type is "category". This can be defined as below:
```
"filters": {
	"Name-of-filter": {
	  "type": "category",
	  "path": "Field path reference to read the filter value"
	},
	...
}
```
### Example
Following shows a field mapping for a filteredsuggest field named "name_suggest" defined at root level:

```
PUT {INDEX_NAME}  
{
  "mappings": {
    "Provider": {
      "properties": {
        "name": {
          "type": "text"
        },
        "Products": {
          "type": "nested",
          "properties": {
            "ProdName": {
              "type": "text"
            },
            "ProdType": {
              "type": "text"
            },
            "Hospitals": {
              "type": "nested",
              "properties": {
                "HospName": {
                  "type": "text"
                },
                "HospType": {
                  "type": "text"
                }
              }
            }
          }
        },
        "name_suggest": {
          "type": "filteredsuggest",
          "parent_path": "",
          "input_fields": "name",
          "filters": {
            "ProdType": {
              "type": "category",
              "path": "Products.ProdType"
            },
            "HospType": {
              "type": "category",
              "path": "Products.Hospitals.HospType"
            }
          }
        }
      }
    }
  }
}
```

Following shows a field mapping for a filteredsuggest field named "hosp_name_suggest" defined at Hospital level:

```
PUT {INDEX_NAME} 
{
  "mappings": {
    "Provider": {
      "properties": {
        "name": {
          "type": "text"
        },
        "Products": {
          "type": "nested",
          "properties": {
            "ProdName": {
              "type": "text"
            },
            "ProdType": {
              "type": "text"
            },
            "Hospitals": {
              "type": "nested",
              "properties": {
                "HospName": {
                  "type": "text"
                },
                "HospType": {
                  "type": "text"
                },
                "hosp_name_suggest": {
                  "type": "filteredsuggest",
                  "parent_path": "Products.Hospitals",
                  "input_fields": "Products.Hospitals.HospName",
                  "filters": {
                    "ProdType": {
                      "type": "category",
                      "path": "Products.ProdType"
                    },
                    "HospType": {
                      "type": "category",
                      "path": "Products.Hospitals.HospType"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

## Indexing

At index time a document may or may not have suggest field instance. By default the suggest field input and filter values will be picked from the referenced fields as per mapping. This can be overridden by explicitly specifying the suggest field at document level and providing values for input.

Index Document with explicit input values for name_suggest mapping - document 1
```
POST {INDEX_NAME}/{TYPE_NAME}
{
  "name": "Simon",
  "Products": [
    {
      "ProdName": "Health Plan One",
      "ProdType": "TypeA",
      "Hospitals": [
        {
          "HospName": "Sakara hospital",
          "HospType": "MultiSpec"
        }
      ]
    },
    {
      "ProdName": "Health Plan One EEE",
      "ProdType": "TypeB",
      "Hospitals": [
        {
          "HospName": "Sagar hospital",
          "HospType": "Specialist-Heart"
        }
      ]
    }
  ],
  "name_suggest": {
    "input": ["Simon","Simon Robinson","Samuel"]
  }
}
```

Suggest Field Input Derived from other fields for name_suggest, hosp_name_suggest mapping- document 2
```
POST {INDEX_NAME}/{TYPE_NAME}
{
  "name": "Simon",
  "Products": [
    {
      "ProdName": "Health Plan One",
      "ProdType": "TypeA",
      "Hospitals": [
        {
          "HospName": "Sakara hospital",
          "HospType": "MultiSpec"
        }
      ]
    },
    {
      "ProdName": "Health Plan One EEE",
      "ProdType": "TypeB",
      "Hospitals": [
        {
          "HospName": "Sagar hospital",
          "HospType": "Specialist-Heart"
        }
      ]
    }
  ]
}
```

## Querying

Without filters - name_suggest; with document 1 indexed
```
POST {INDEX}/_search
{
  "suggest": {
    "name_suggestion": {
      "prefix": "sim",
      "filteredsuggest": {
        "field": "name_suggest",
        "size": 10
      }
    }
  }
}
```

The response is as below:
```
{
	...
	"suggest" : {
    "name_suggestion" : [
      {
        "text" : "sim",
        "offset" : 0,
        "length" : 3,
        "options" : [
          {
            "text" : "Simon",
            "score" : 1.0
          },
          {
            "text" : "Simon Robinson",
            "score" : 1.0
          }
        ]
      }
    ]
  }
}
```

With filters - name_suggest; with document 2 indexed
```
POST {INDEX}/_search
{
  "suggest": {
    "name_suggestion": {
      "prefix": "sim",
      "filteredsuggest": {
        "field": "name_suggest",
        "size": 10,
        "filters": {
          "ProdType": "TypeB",
          "HospType": "Specialist-Heart"
        }
      }
    }
  }
}
```

The response is as below:
```
{
	...
	"suggest" : {
    "name_suggestion" : [
      {
        "text" : "sim",
        "offset" : 0,
        "length" : 3,
        "options" : [
          {
            "text" : "Simon",
            "score" : 1.0
          }
        ]
      }
    ]
  }
}
```

With filters and fuzziness - name_suggest; with document 1 indexed
```
POST {INDEX}/_search
{
  "suggest": {
    "name_suggestion": {
      "prefix": "sim",
      "filteredsuggest": {
        "field": "name_suggest",
        "size": 10,
        "fuzzy": {
          "fuzziness": 2
        },
        "filters": {
          "ProdType": "TypeB",
          "HospType": "Specialist-Heart"
        }
      }
    }
  }
}
```

The response is as below:
```
{
	...
	"suggest" : {
    "name_suggestion" : [
      {
        "text" : "sim",
        "offset" : 0,
        "length" : 3,
        "options" : [
          {
            "text" : "Samuel",
            "score" : 2.0
          },
          {
            "text" : "Simon",
            "score" : 2.0
          },
          {
            "text" : "Simon Robinson",
            "score" : 2.0
          }
        ]
      }
    ]
  }
}
```

Without filters - hosp_name_suggest; with document 2 indexed
```
POST {INDEX}/_search
{
  "suggest": {
    "name_suggestion": {
      "prefix": "sa",
      "filteredsuggest": {
        "field": "Products.Hospitals.hosp_name_suggest",
        "size": 10
      }
    }
  }
}
```

The response is as below:
```
{
	...
	"suggest" : {
    "name_suggestion" : [
      {
        "text" : "sa",
        "offset" : 0,
        "length" : 2,
        "options" : [
          {
            "text" : "Sagar hospital",
            "score" : 1.0
          },
          {
            "text" : "Sakara hospital",
            "score" : 1.0
          }
        ]
      }
    ]
  }
}
```

With filters - hosp_name_suggest; with document 2 indexed
POST {INDEX}/_search
```
{
  "suggest": {
    "name_suggestion": {
      "prefix": "sa",
      "filteredsuggest": {
        "field": "Products.Hospitals.hosp_name_suggest",
        "size": 10,
        "filters": {
          "ProdType": "TypeB",
          "HospType": "Specialist-Heart"
        }
      }
    }
  }
}
```

The response is as below:
```
{
	...
	"suggest" : {
    "name_suggestion" : [
      {
        "text" : "sa",
        "offset" : 0,
        "length" : 2,
        "options" : [
          {
            "text" : "Sagar hospital",
            "score" : 1.0
          }
        ]
      }
    ]
  }
}
```

## Query Benchmark

The filtered auto suggester is benchmarked on a below hardware/software configuration
**Cluster Configuration**		
No of VMs - 8
RAM/VM - 64 GB
CPU/VM - 8 core
Disk Size/VM - 200 GB
No of ES Nodes/VM - 2
Per Node RAM	 - 16 GB
Shard size - 16
No of Replica - 1
Total Docs Indexed - 8 M
Total Entities Indexed - 1366 M

The following shows the query performance under different load with response size fixed to 25

image

### CODE REVIEW

**Comment by clintongormley** [comment]
Hi @nilabhsagar 

Thank you for the PR and sorry it has taken a while to respond.  There are two problems with this PR:  First, it includes an incompatible license which would prevent us from merging it. Second, it is 4,000 lines with many changes - nobody is going to review that as it is just too much code at once.  

If you want to rework the PR to remove the code using the incompatible license, then I would suggest breaking up the changes into small manageable PRs , each of which can be explained and reviewed more easily. You may want to start by opening an issue discussing the changes you would like to make and why.

thanks

**Comment by clintongormley** [comment]
An alternative would be for you to release your suggester as a community supported plugin

**Comment by nilabhsagar** [comment]
Hi @clintongormley

We could not follow "the incompatible license" part. Are you referring to "combinatoricslib" or the CLA which we have signed or anything else? 

This PR is a complete feature implementation like Context suggester for "Filtered Auto Suggester on Nested Model". It has type configuration, indexing and query module implementations and hence has that many lines of code. We understand the review challenges but are not sure as how these modules could be created and validated as multiple independent PRs. Could you suggest the way forward?

**Comment by abhishek5678** [comment]
mapping is not working when i am putting the mapping then it is showing like that "No handler for type [filteredsuggest] declared on field [name_suggest]" please help me to resolve this issue

**Comment by nilabhsagar** [comment]
Hi @abhishek5678 This pull request is still under discussion and not merged into the current development master. Will it be possible for you to share the requirement for which you wanted to use the above [filteredsuggest] feature?

**Comment by abhishek5678** [comment]
hi nilabhsagar i want to fetch the nested data and autosuggestion but when i am trying like this then i am not able to fetch the nested data and autosuggestion also please help me to resolve this issue.i also sending my document data also

POST /test_word14/doc/1
{
    "name": "Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism (D50-D89)",
    "depth": 1,
	"children": [{
		"name": "Nutritional anemias (D50-D53)",
		"depth": 2,
		"children": [{
			"code": "D50",
			"name": "Iron deficiency anemia",
			"depth": 3,
			"children": [{
				"code": "D50.0",
				"name": "Iron deficiency anemia secondary to blood loss (chronic)",
				"depth": 4
			}, {
				"code": "D50.1",
				"name": "Sideropenic dysphagia",
				"depth": 4
			}, {
				"code": "D50.8",
				"name": "Other iron deficiency anemias",
				"depth": 4
			}, {
				"code": "D50.9",
				"name": "Iron deficiency anemia, unspecified",
				"depth": 4
			}]
		}]
	}]

**Comment by abhishek5678** [comment]
Hi @nilabhsagar problem is that when i am fetching the name:Sideropenic dysphagia then all data will be coming but i want only whatever i am searching only that data are coming and also auto suggestion will be provided

**Comment by nilabhsagar** [comment]
Hi @abhishek5678 I can help you to solve it. I request you to post this problem in [Discuss at Elastic](https://discuss.elastic.co) as this is not the right place to discuss about the problem.

Thanks

**Comment by abhishek5678** [comment]
Hi @nilabhsagar i am waiting for your reply

**Pull request closed without merging**
