### PR TITLE
Tests: Change rest test extension from .yaml to .yml

### PR DESCRIPTION
**Pull request by rjernst**
This commit renames all rest test files to use the .yml extension
instead of .yaml. This way the extension used within all of
elasticsearch for yaml is consistent.

see https://github.com/elastic/elasticsearch/pull/24633#issuecomment-301096471

### CODE REVIEW

**Review by bleskes — APPROVED** [review]

**Comment by nik9000** [comment]
Makes sense to me.

**Comment by rjernst** [comment]
@clintongormley I assume the clients will need to be updated before pushing this?

**Comment by clintongormley** [comment]
> I assume the clients will need to be updated before pushing this?

I don't think the clients have CI enabled atm, so you should be able to go ahead and merge.

Ping: @elastic/es-clients - the YAML test files are being renamed from `.yaml` to `.yml`

**Comment by karmi** [comment]
I've checked and I load [both .yml and .yaml files](https://github.com/elastic/elasticsearch-ruby/blob/master/elasticsearch-api/test/integration/yaml_test_runner.rb#L333), so Travis should continue to work...

**Pull request merged**
