### PR TITLE
[8.x] Bool query early termination should also consider must_not clauses (#115031)

### PR DESCRIPTION
**Pull request by piergm**
# Backport

This will backport the following commits from `main` to `8.x`:
 - [Bool query early termination should also consider must_not clauses (#115031)](https://github.com/elastic/elasticsearch/pull/115031)

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

### CODE REVIEW

**Comment by piergm** [comment]
@elasticsearchmachine test this

**Comment by javanna** [comment]
You are good merging this without a review, unless you think it needs a specific review because the backport was problematic ;)

**Comment by piergm** [comment]
@elasticsearchmachine test this

**Comment by piergm** [comment]
@elasticmachine update branch

**Pull request merged**
