### PR TITLE
LuceneChangesSnapshot doesn't need reference to MapperService

### PR DESCRIPTION
**Pull request by romseygeek**
LuceneChangesSnapshot currently takes a field type lookup lambda so that
it can call `FieldsVisitor#postProcess()` once it has read a document from
its lucene index.  However, this `postProcess()` call is unnecessary - the only
fields loaded for the document are `_source`, `_id` and `_routing`, none of
which require post-processing.  Deleting this call allows us to remove the
fieldtype lookup from a number of places, with the result that various Engine
tests no longer need to create a MapperService (quite a heavy operation) to
test the transaction log.

### CODE REVIEW

**Comment by romseygeek** [comment]
@elasticmachine run elasticsearch-ci/1

**Review by henningandersen — APPROVED** [review]
LGTM, nice simplification.

**Comment by romseygeek** [comment]
@elasticmachine update branch

**Comment by romseygeek** [comment]
@elasticmachine update branch

**Comment by romseygeek** [comment]
NB this ends up being 8.x only, because getting the UID in 7.x *does* require some post-processing.

**Pull request merged**
