### PR TITLE
Update link to Jepsen related test class

### PR DESCRIPTION
**Pull request by josegonzalez**

### CODE REVIEW

**Comment by josegonzalez** [comment]
I've signed the CLA, how do I get the check to pass now?

**Comment by nik9000** [comment]
There are a few async processes that have to happen first and then every time a new comment comes in it should rerun. I just confirmed that you signed it manually though so I'll merge it.

**Comment by nik9000** [comment]
And my comment triggered the check to rerun and it passed. Its neat when things like that work.

**Comment by josegonzalez** [comment]
<3

**Comment by nik9000** [comment]
Thanks for catching it! A link checker is just one more thing to add to the list of doc validations.....

**Pull request merged**
