### PR TITLE
Reduce complexity of plugin cli

### PR DESCRIPTION
**Pull request by rjernst**
The plugin cli currently is extremely lenient, allowing most errors to
simply be logged. This can lead to either corrupt installations (eg
partially installed plugins), or confused users.

This change rewrites the plugin cli to have almost no leniency.
Unfortunately it was not possible to remove all leniency, due in
particular to how config files are handled.

The following functionality was simplified:
- The format of the name argument to install a plugin is now an official
  plugin name, maven coordinates, or a URL.
- Checksum files are required, and only checked, for official plugins
  and maven plugins. Checksums are also only SHA1.
- Downloading no longer uses a separate thread, and no longer has a timeout.
- Installation, and removal, attempts to be atomic. This only truly works
  when no config or bin files exist.
- config and bin directories are verified before copying is attempted.
- Permissions and user/group are no longer set on config and bin files.
  We rely on the users umask.
- config and bin directories must only contain files, no subdirectories.
- The code is reorganized so each command is a separate class. These
  classes already existed, but were embedded in the plugin cli class, as
  an extra layer between the cli code and the code running for each command.

### CODE REVIEW

**Comment by rjernst** [comment]
Note that testing of installing official plugins by name, or plugins via maven coordinates is still TODO, and will require an https fixture. However, this was not really tested before (the tests were skipped and relied on actually hitting eg github or our real download service). This can happen in a follow up.

**Comment by rjernst** [comment]
Also note that this PR is the beginning of what will allow us to separate the plugin cli into its own jar, which will allow us to run plugin cli under security manager, as well as better test it (eg move tests which need extra permissions like modifying file permissions from evil-tests next to the plugin cli code).

**Comment by s1monw** [comment]
I love the strictness and how structured this is now.This is a huge improvement. I looked over the code in src/main and I think we should get it in as is. It's a huge improvemnet! thanks LGTM

**Comment by dadoonet** [comment]
Nice stats! And much easier to read.

**Pull request merged**
