### PR TITLE
[DOCS] Add info about GET/POST to the API conventions.

### PR DESCRIPTION
**Pull request by debadair**
Note that Elasticsearch GET APIs that support a request body can also be submitted as POST requests.

### CODE REVIEW

**Comment by debadair** [comment]
@elasticmachine run docs

**Comment by debadair** [comment]
@elasticmachine run docs

**Comment by debadair** [comment]
@elasticmachine retest this please

**Comment by debadair** [comment]
@elasticmachine retest this please

**Review by jrodewig — APPROVED** [review]
LGTM. I left some minor feedback but nothing blocking. Thanks!

**Comment by debadair** [comment]
Thanks for the review! I streamlined things a bit more, moved the rest of the conventions to the conventions, and organized them in more logical groupings.

**Comment by debadair** [comment]
@elasticmachine retest this please

**Comment by debadair** [comment]
@elasticmachine retest this please

**Comment by debadair** [comment]
@elasticmachine retest this please

**Comment by debadair** [comment]
@elasticmachine retest this please

**Comment by debadair** [comment]
@elasticmachine retest this please

**Pull request merged**
