### PR TITLE
Add listeners for postIndex, postCreate, and postDelete, backport to 1.7

### PR DESCRIPTION
**Pull request by kiryam**
Backport of #13203.
Related to #13202

### CODE REVIEW

**Comment by clintongormley** [comment]
Hi @kiryam 

How is this related to #13203?  There is nothing in the PR description. Is this just the backport? (normally we take care of the backport)

**Comment by kiryam** [comment]
@clintongormley Hello, yes! it is backport only. Tests pending

**Comment by s1monw** [comment]
@kiryam don't worry about backporting I will take care of this if we decide it should go in that branch!

**Comment by kiryam** [comment]
Thx!

**Comment by s1monw** [comment]
this can be closed it has been backported afaik

**Pull request closed without merging**
