### PR TITLE
Rename Custom to MetadataExtension

### PR DESCRIPTION
**Pull request by thecoop**
MetadataExtension is a clearer name than Custom.

See ES-8878 for background.

### CODE REVIEW

**Review by prdoyle — APPROVED** [review]
What was the thought process behind choosing `MetadataExtension` versus `ExtensionMetadata` in each case?

**Comment by thecoop** [comment]
That was what the IDE did when I changed the name...

**Comment by rjernst** [comment]
I do not think we should use "Extension" as that is already taken by plugins (see eg PainlessExtension), which is a plugin which uses ES's SPI. I don't have an alternative currently, but I am strongly against the use of Extension because of the ambiguity and confusion it would cause ("what _kind_ of extension do you mean?")

**Comment by thecoop** [comment]
Extension is the wrong term here

**Pull request closed without merging**
