### PR TITLE
Reduce mocking in ClusterStateChanges

### PR DESCRIPTION
**Pull request by DaveCTurner**
Today in `ClusterStateChanges` we use mocks to capture tasks submitted
to the master service in order to compute the relevant cluster state
updates ourselves. In fact there's no need to do this, we can use the
real master service with a customized executor. This commit does that.

### CODE REVIEW

**Comment by DaveCTurner** [comment]
@elasticmachine please run elasticsearch-ci/packaging-tests-unix-sample (looks transient)

**Comment by DaveCTurner** [comment]
@elasticmachine please run elasticsearch-ci/part-2 (https://github.com/elastic/elasticsearch/issues/85697)

**Comment by DaveCTurner** [comment]
@elasticmachine please run elasticsearch-ci/part-2 (https://github.com/elastic/elasticsearch/issues/79621)

**Review by joegallo — APPROVED** [review]
Awesome. Great stuff. Ship it!

**Pull request merged**
