### PR TITLE
Added filter doc to aggregation structure

### PR DESCRIPTION
**Pull request by a-schuurman**
I've expanded the aggregation documentation, added the filter to the structure of an aggregation.

### CODE REVIEW

**Comment by a-schuurman** [comment]
Contributor agreement has been signed.

**Comment by colings86** [comment]
@a-schuurman thank you for the PR but the syntax you added is not supported. There is an `aggregation_type` called `filter` but one cannot add a `filter` to any arbitrary aggregation.

**Comment by cbuescher** [comment]
@colings86 looks like this can be closed then?

**Comment by colings86** [comment]
Yes I believe so @cbuescher

**Pull request closed without merging**
