### PR TITLE
Zen2: Rename voting tombstones to exclusions

### PR DESCRIPTION
**Pull request by ywelsch**
Relates to 0973de86778 and e8d9656d073

### CODE REVIEW

**Comment by ywelsch** [comment]
@elasticmachine retest this please

**Comment by ywelsch** [comment]
@elasticmachine retest this please

**Comment by ywelsch** [comment]
@elasticmachine retest this please (known issue, see 
https://github.com/elastic/elasticsearch/commit/a3c1c6938a374dda7de0ad48ae35d3842c6805fe)

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Pull request merged**
