### PR TITLE
Only check inactive replicas in cancelling existing recoveries.

### PR DESCRIPTION
**Pull request by howardhuanghua**
Currently we check and process existing recoveries once we have `INITIALIZING` shards. `ReplicaShardAllocator.processExistingRecoveries` would be expensive as it will for-loop all the shards overall the nodes. Actually we only need to do this checking if we do have replicas in `INITIALIZING` state. If we only have primaries in this state, we could skip. For example:
1. Creating a index, allocate primaries first, some of the primaries got started first would trigger reroute, now would still have some `INITIALIZING` primaries, we don't need to process existing recoveries, as no replicas would be allocated at the begining.
2. Creating index that only have primries no replica, we also don't need to process existing recoveies in the whole allocation process.

### CODE REVIEW

**Comment by dliappis** [comment]
Related to #46520

**Comment by henningandersen** [comment]
@elasticmachine update branch

**Comment by henningandersen** [comment]
@elasticmachine test this please

**Comment by howardhuanghua** [comment]
Branch has been updated. Thank you @henningandersen .

**Comment by howardhuanghua** [comment]
Hi @henningandersen would you please help to check this PR again? Thank you.

**Comment by henningandersen** [comment]
@elasticmachine test this please

**Comment by howardhuanghua** [comment]
Merged latest master.

**Comment by henningandersen** [comment]
@elasticmachine test this please

**Review by henningandersen — APPROVED** [review]
LGTM, thanks for your contribution.

**Pull request merged**
