### PR TITLE
ESQL: Split usage tests in snapshot and release tests

### PR DESCRIPTION
**Pull request by astefan**

### CODE REVIEW

**Review by mark-vieira — APPROVED** [review]

**Comment by astefan** [comment]
@mark-vieira my approach above doesn't seem to work. I reproduced the failure from CI locally and put some logging in it and the content of `REST_TESTS_BLACKLIST` is empty here https://github.com/elastic/elasticsearch/blob/main/test/yaml-rest-runner/src/main/java/org/elasticsearch/test/rest/yaml/ESClientYamlSuiteTestCase.java#L178.

Do you know what am I doing wrong? Thanks 🙏 

Essentially, what I wanted to do is simulate `isSnapshot()` inside an yaml file. There doesn't seem such a mechanism to exist, so I went for the `tests.rest.blacklist` in the `gradle` file.

**Comment by mark-vieira** [comment]
> Essentially, what I wanted to do is simulate `isSnapshot()` inside an yaml file. There doesn't seem such a mechanism to exist, so I went for the `tests.rest.blacklist` in the `gradle` file.

Should we be using the features/capabilities API for this sort of thing? Don't we already have a mechanism to skip tests if a feature is not available?

**Comment by astefan** [comment]
> > Essentially, what I wanted to do is simulate `isSnapshot()` inside an yaml file. There doesn't seem such a mechanism to exist, so I went for the `tests.rest.blacklist` in the `gradle` file.
> 
> Should we be using the features/capabilities API for this sort of thing? Don't we already have a mechanism to skip tests if a feature is not available?

I've tried this instead https://github.com/elastic/elasticsearch/pull/115402. Not ideal, but it's closer to the capabilities API you mentioned.

**Comment by mark-vieira** [comment]
> > > Essentially, what I wanted to do is simulate `isSnapshot()` inside an yaml file. There doesn't seem such a mechanism to exist, so I went for the `tests.rest.blacklist` in the `gradle` file.
> > 
> > 
> > Should we be using the features/capabilities API for this sort of thing? Don't we already have a mechanism to skip tests if a feature is not available?
> 
> I've tried this instead #115402. Not ideal, but it's closer to the capabilities API you mentioned.

Not all ESQL test work the same regarding features it seems. Specifically the CsvTests behave a bit different (see https://github.com/elastic/elasticsearch/issues/114536). You might want to confirm locally or add `test-release` to that PR to confirm.

**Pull request closed without merging**
