### PR TITLE
[DOCS] Relocate "Plugins" page

### LINKED ISSUE #53310: [DOCS] Move reference to plugin docs out of modules
As part of the Modules reorg to improve discovery and navigation, find a better place to xref the plugins documentation.

### PR DESCRIPTION
**Pull request by jrodewig**
Moves the [Plugins][0] page under [Set up Elasticsearch][1] from the [Modules][2] section.

Closes #53310

[0]: https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-plugins.html
[1]: https://www.elastic.co/guide/en/elasticsearch/reference/master/setup.html
[2]: https://www.elastic.co/guide/en/elasticsearch/reference/master/modules.html

### CODE REVIEW

**Review by rjernst — COMMENTED** [review]
This looks fine. I have two questions:
* why is this only targeted for 8.0?
* Most of the content in the linked plugins documentation is related to how to install plugins and which are available, but there is also some there that is for plugin authors on developing plugins, which doesn't seem like linking from setup gives the best visibility. Why are plugins in their own section (book?) and would splitting that book up into managing plugins vs developing plugins better serve users? This is more a question for the long term future and only semi related to this particular change.

**Comment by jrodewig** [comment]
Hey @rjernst! Thanks for raising these questions.

> why is this only targeted for 8.0?

This PR is part of a larger effort to move content out of the [Modules](https://www.elastic.co/guide/en/elasticsearch/reference/master/modules.html) section.

While this particular change doesn't involve any redirects/removed pages, many related to that effort will. Going forward, we're trying to treat redirects/removed pages as "breaking changes" and only include them in major releases.

My original thought was to try to group all modules-related content relocations under the 8.0 release, but I don't have an issue backporting this particular PR if wanted.

> Why are plugins in their own section (book?)

I don't have much info about the history of that decision. @debadair might be able to help us out though?

> ... would splitting that book up into managing plugins vs developing plugins better serve users?

That would be outside the scope of this PR, but I agree. The link here would primarily benefit end users rather than plugin authors. Since the bulk of the Plugin's guide content is aimed at end users, I think this link/location is okay.

I created https://github.com/elastic/elasticsearch/issues/54982 to address and plan to discuss it in our next ES docs meeting. Please feel free to comment on that issue or attend the meeting. I'd love to hear any other thoughts you have.

**Review by debadair — APPROVED** [review]
I agree that the information for plugin developers is a bit buried, and organizing content around the intended audience is generally a helpful pattern. I think we should hold off on trying to move it until we sort the doc nav changes, though. For now, it might be worth updating the description to explicitly link to the information about building your own plugins.

**Comment by jrodewig** [comment]
Note: we decided to backport these changes to 7.x, 7.8, and 7.7 as well. This will help avoid backport pain and make changes available to users in earlier versions.

### Backport commits
master 600ccc0 
7.x 8c0e7c8 
7.8 fdbf8e2 
7.7 f832fd1

**Pull request merged**
