### PR TITLE
Fix build on sles with new docker version

### LINKED ISSUE #36414: Docker images failing build
CI is tripping all over the newly added Docker images build.

```
> Task :distribution:docker:buildDockerImage FAILED
invalid reference format
Task ':distribution:docker:buildDockerImage' is not up-to-date because:

FAILURE: Build failed with an exception.
  Task has not declared any outputs despite executing actions.
Starting process 'command 'docker''. Working directory: /var/lib/jenkins/workspace/elastic+elasticsearch+6.x+multijob-unix-compatibility/os/opensuse/distribution/docker Command: docker build build/docker --pull --tag elasticsearch:6.6.0-SNAPSHOT --tag docker.elastic.co/elasticsearch/elasticsearch:6.6.0-SNAPSHOT --tag docker.elastic.co/elasticsearch/elasticsearch-full:6.6.0-SNAPSHOT
Successfully started process 'command 'docker''
Sending build context to Docker daemon  147.1MB


* What went wrong:
Step 1/30 : FROM centos:7 AS builder
Execution failed for task ':distribution:docker:buildDockerImage'.
> Process 'command 'docker'' finished with non-zero exit value 1
:distribution:docker:buildDockerImage (Thread[Execution worker for ':' Thread 11,5,main]) completed. Took 0.652 secs.
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=opensuse/108/console

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+release-tests/195/console

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-darwin-compatibility/108/console

and many many more.

Relates to #36246

### PR DESCRIPTION
**Pull request by alpar-t**
The build hash for this version is longer,

Closes #36414

### CODE REVIEW

**Review by jasontedor — COMMENTED** [review]
I left a couple of comments.

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by atorok** [comment]
@elasticmachine run gradle tests 1

**Comment by atorok** [comment]
@elasticmachine run gradle build tests 1

**Comment by atorok** [comment]
@elasticmachine run gradle build tests 1

**Comment by atorok** [comment]
@elasticmachine run gradle build tests 1

**Comment by droberts195** [comment]
I think this should be backported to 6.x and 6.6 too, as the same problem is failing some builds on those branches?  Or is there a reason why the fix would need to be different on these branches?

**Pull request merged**
