### PR TITLE
 Rename core module to server

### PR DESCRIPTION
**Pull request by Tim-Brooks**
This is related to #27933. It renames the core module to server. This is
the first step towards introducing an elasticsearch-core jar.

### CODE REVIEW

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by s1monw** [comment]
is this something that we want to do in a minor? I mean we are changing the artifacts name with can potentially cause a hell lot of confusion?

**Comment by jasontedor** [comment]
@s1monw We are not changing the artifact name. It is still mapped to “elasticsearch” just as core is today.

**Comment by s1monw** [comment]
> @s1monw We are not changing the artifact name. It is still mapped to “elasticsearch” just as core is today.

thanks!

**Review by s1monw — APPROVED** [review]
LGTM

**Pull request merged**
