### PR TITLE
Upgrade to lucene-5.3.0.

### PR DESCRIPTION
**Pull request by jpountz**
From a user perspective, the main benefit from this upgrade is that the new
Lucene53Codec has disk-based norms. The elasticsearch directory has been fixed
to load these norms through mmap instead of nio.

Other changes include the removal of `max_thread_states`, the fact that
PhraseQuery and BooleanQuery are now immutable, and that deleted docs are now
applied on top of the Scorer API.

This change introduces a couple of `AwaitsFix`s but I don't think it should
hold us from merging.

### CODE REVIEW

**Comment by rmuir** [comment]
looks great, +1

**Comment by dpursehouse** [comment]
:+1: I just did this change myself locally but you beat me to it.

**Comment by dpursehouse** [comment]
Is there any possibility to include this in the 2.0.0 release?

**Comment by jpountz** [comment]
@dpursehouse We are in the process of stabilizing 2.0 and this is a big change, so it won't be backported. The good news however is that we aim at releasing 2.1 relatively soon after 2.0.

**Pull request merged**
