### PR TITLE
Clean up XPackInfoResponse class and related tests

### PR DESCRIPTION
**Pull request by javanna**
This is a follow-up of something that I raised [in a previous PR](https://github.com/elastic/elasticsearch/pull/33176#discussion_r231881620). 

Response classes in Elasticsearch (and xpack) only need to implement ToXContent, which is needed to print their output put in the REST layer and return the response in json (or others) format. On the other hand, response classes that are added to the high-level REST client, need to do the opposite: parse xcontent and create a new object based on that.

At the moment, both variants of XPackInfoResponse (xpack and client) do both: parsing and printing. This is redundant, it leads to code duplication, and redundant testing too. Now that we have a way to test these classes from a single test (see `AbstractHlrcStreamableXContentTestCase` base class), we should remove code duplication and only maintain the needed portions in each response class.

This PR removes the parsing code from the `XPackInfoResponse` server variant, and the `toXContent` portion from the corresponding client variant. It also removes a client specific test class that looks redundant now that we have a single test class for both classes. I will mark this for discussion to see whether this is the approach that we want to take moving forward.

### CODE REVIEW

**Review by nik9000 — APPROVED** [review]
LGTM

**Comment by nik9000** [comment]
You marked it as discuss, but I think this is the right way to do it. We need to make sure we don't accidentally remove tests for parsing at all, but I love that we're testing if the client can parse stuff sent from the server now.

**Comment by javanna** [comment]
> We need to make sure we don't accidentally remove tests for parsing at all, but I love that we're testing if the client can parse stuff sent from the server now.

Agreed, please double check that I have only removed duplicated tests, that was my intention, but I may have missed some subtleties.

**Comment by javanna** [comment]
retest this please

**Review by nik9000 — COMMENTED** [review]
It looks right.

I don't really that the test is in x-pack instead of the client, but I think it kind of has to be.

**Comment by nik9000** [comment]
> I don't really that the test is in x-pack instead of the client, but I think it kind of has to be.

And that isn't a thing you changed, either.

**Comment by javanna** [comment]
@vladimirdolzhenko are you ok with this?

**Comment by vladimirdolzhenko** [comment]
@javanna sure, please go ahead 💯

**Pull request merged**
