### PR TITLE
Remove `_shutdown` API

### PR DESCRIPTION
**Pull request by s1monw**
Thsi commit removes the `_shutdown` API entirely without any replacement.
Nodes should be managed from the operating system not via REST APIs.

### CODE REVIEW

**Comment by kimchy** [comment]
LGTM

**Comment by rmuir** [comment]
+1, I would like to remove exitVM permissions too. I can look into it as a followup.

**Comment by s1monw** [comment]
> +1, I would like to remove exitVM permissions too. I can look into it as a followup.

++

**Comment by TwP** [comment]
visa

Seriously, though, thank you for doing this. My future self awoken at 3:15AM by our pager system will appreciate not making things worse by accidentally shutting down a node.

**Comment by beiske** [comment]
The shutdown api was actually really convenient for clusters running on Found as we have mechanisms in place that restarts any Elasticsearch process that stops. It would be nice if there would still be a way to restart an instance through the api.

**Comment by dhohle** [comment]
It must be me, but how should I stop the ES node? kill process? There is, at least not in version 1.7.x a 'stop' option in the bin/elasticsearch... "Let the OS handle" seems a bit too (argh, lack of English skill, there should be a good word for it) ¿harsh?

**Comment by dadoonet** [comment]
There is one if you install elasticsearch as a service.

     service elasticsearch stop 

Will do it.

If you start elasticsearch with

      bin/elasticsearch 

Just CTRL C then.

**Comment by nik9000** [comment]
Letting the OS handle it is what well behaved services should do.  It's
good that elasticsearch does the right thing when killed. Kill isn't
supposed to be harsh. Kill -9 is. Kill gives elasticsearch plenty of leeway
to shutdown properly.

**Pull request merged**
