### PR TITLE
[DOCS] Fix broken link to Elasticsearch Docker source code

### LINKED ISSUE #40813: Wrong docker repo link in installation guide
In https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html we are saying:

> A list of all published Docker images and tags is available at www.docker.elastic.co. The source code is in GitHub.

The GitHub link is https://github.com/elastic/elasticsearch-docker/tree/6.7 which does not exist anymore since 6.6 I think.

### PR DESCRIPTION
**Pull request by jrodewig**
In our [Docker installation instructions](https://www.elastic.co/guide/en/elasticsearch/reference/master/docker.html), we link to the source code for the official Elasticsearch Docker image in the elastic/elasticsearch-docker repo.

With 6.6, we relocated the Docker files to the elastic/elasticsearch repo at https://github.com/elastic/elasticsearch/tree/master/distribution/docker. This points the link to that new location.

Resolves #40813.

### CODE REVIEW

**Review by jasontedor — CHANGES_REQUESTED** [review]
We would want a different change here. The idea is that since the 6.6 release, the Docker images are managed from this repository (instead of the `elastiscearch-docker` repository).

**Comment by jrodewig** [comment]
Thanks @jasontedor. 

With 374e27b, I updated the link to point to the Dockerfile at https://github.com/elastic/elasticsearch/blob/master/distribution/docker/src/docker/Dockerfile.

That link also incorporates an attribute to use the appropriate branch in the link.

**Review by jasontedor — COMMENTED** [review]
Yeah, that's much better. Although I wonder if we should point to https://github.com/elastic/elasticsearch/blob/{branch}/distribution/docker as the full source for the build process (the Dockerfile alone is not enough, since it has some templated values that need to be filled in during the build).

**Comment by jrodewig** [comment]
Thanks again @jasontedor. I changed the link to the `/distribution/docker` dir with a1fafd4. Appreciate your feedback!

**Review by jasontedor — APPROVED** [review]
LGTM.

**Pull request merged**
