### PR TITLE
Update searchable snapshot to clarify

### PR DESCRIPTION
**Pull request by kunisen**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)? Yes
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md)? Yes
- If submitting code, have you built your formula locally prior to submission with `gradle check`? Not code
- If submitting code, is your pull request against main? Unless there is a good reason otherwise, we prefer pull requests against main and will backport as needed. Not code
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)? Not code
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md#contributing-as-part-of-a-class) for that. Not code

Update searchable snapshot to clarify it's not a backup of index data and deleting it will result in permanent data loss. 

It's a follow up of https://github.com/elastic/elasticsearch/pull/108451

### CODE REVIEW

**Review by geekpete — COMMENTED** [review]
LGTM

**Review by DaveCTurner — CHANGES_REQUESTED** [review]
IME it doesn't work very well to start sections with `WARNING` admonitions like this. Maybe one is ok, but then we add another, and another, and it ends up pushing the actual content of the section out of view.

Also, this warning is kind of confusing (what does it have to do with frozen/cold data?) and also kind of ambiguous (deleting the searchable snapshot index does not cause permanent data loss, it's only deleting the underlying snapshot while it's still mounted that causes problems).

Instead, maybe we should make this whole section into a `WARNING`, and add some more detail to each of the bullet points in the list about the consequences of ignoring the advice.

**Comment by kunisen** [comment]
Thank you @DaveCTurner so much for the quick and detailed guidance!
I didn't want to break the whole text so I only added a piece of warning, but indeed as you said, it's good to make the whole section a warning to bring the best awareness. 

We are good with this change. If you don't mind, may I also ask your help to see if we can merge this PR, or if you can kindly forward this to doc team for doc-related reviews? 🙏 

Thanks again!

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Comment by kunisen** [comment]
thanks!
sorry forgot to add backport label.

**Pull request merged**
