### PR TITLE
[DOCS] Document missing `flag` values for `regexp` query

### LINKED ISSUE #81978: RegExp optional operations documentation fails to mention `NONE`
**Elasticsearch version** (`bin/elasticsearch --version`): 7.16

See documentation at https://www.elastic.co/guide/en/elasticsearch/reference/current/regexp-syntax.html#regexp-optional-operators. It should specify the `NONE` option for disabling all the flags.

Also, the implementations accepts `flags: ""` as a value which apparently maps to `ALL` (which I find quite illogical). I think `""` should either give an exception or maybe mean `NONE`.

### PR DESCRIPTION
**Pull request by jrodewig**
Documents the `EMPTY` and `NONE` `flag` values for the `regexp` query.

Also documents the `""` (empty string) value, which is an alias for `ALL`.

Closes #81978.

### Preview
https://elasticsearch_82265.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/regexp-syntax.html#_valid_values

### CODE REVIEW

**Review by kirakoki — APPROVED** [review]

**Review by ywelsch — APPROVED** [review]
LGTM. Sorry for taking so long, I missed the review request.

**Comment by jrodewig** [comment]
No worries. Thanks @ywelsch!

**Comment by jrodewig** [comment]
@elasticmachine update branch

**Comment by jrodewig** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------:|
|✅|8.0|[](https://github.com/elastic/elasticsearch/pull/82760)|
|✅|7.17|[](https://github.com/elastic/elasticsearch/pull/82761)|
|✅|7.16|[](https://github.com/elastic/elasticsearch/pull/82762)|

**Pull request merged**
