### PR TITLE
Infra for deprecation logging

### PR DESCRIPTION
**Pull request by spinscale**
This is an enhancement to #11033

It adds a test, some documentation and allows to retrieve the logger via the `ESLoggerFactory`.

### CODE REVIEW

**Comment by spinscale** [comment]
@kimchy @rjernst can you take a look?

**Comment by rjernst** [comment]
@spinscale I left comments directly on your commit. My only concern is checking in with an ignore on that test?

**Comment by spinscale** [comment]
@rjernst thanks for checking, agreed on the check in of a ignored test, removed it for now, I think the other one is sufficient

**Comment by rjernst** [comment]
LGTM

**Pull request merged**
