### PR TITLE
Add enrich stats api

### PR DESCRIPTION
**Pull request by martijnvg**
The enrich api returns enrich coordinator stats and
information about currently executing enrich policies.

The coordinator stats include per ingest node:
* The current number of search requests in the queue.
* The total number of outstanding remote requests that
  have been executed since node startup. Each remote
  request is likely to include multiple search requests.
  This depends on how much search requests are in the
  queue at the time when the remote request is performed.
* The number of current outstanding remote requests.
* The total number of search requests that `enrich`
  processors have executed since node startup.

The current execution policies stats include:
* The name of policy that is executing
* A full blow task info object that is executing the policy.

Relates to #32789

### CODE REVIEW

**Comment by martijnvg** [comment]
This is what the response looks like when a policy is executing:

```json
{
  "executing_policies" : [
    {
      "name" : "my-policy",
      "task" : {
        "node" : "0oDKNFboSFyx1C8sK-1Zcg",
        "id" : 124,
        "type" : "transport",
        "action" : "cluster:admin/xpack/enrich/execute",
        "description" : "my-policy",
        "start_time_in_millis" : 1568016012984,
        "running_time_in_nanos" : 1624202943,
        "cancellable" : false,
        "headers" : { }
      }
    }
  ],
  "coordinator_stats" : [
    {
      "node_id" : "0oDKNFboSFyx1C8sK-1Zcg",
      "queue_size" : 0,
      "remote_requests_current" : 0,
      "remote_requests_total" : 0,
      "executed_searches_total" : 0
    }
  ]
}
```

**Comment by martijnvg** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by martijnvg** [comment]
@elasticmachine run elasticsearch-ci/2

**Review by jbaiera — APPROVED** [review]
LGTM

**Comment by martijnvg** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by martijnvg** [comment]
@elasticmachine update branch

**Pull request merged**
