### PR TITLE
Fix assertion catching in aggregation supported type test

### PR DESCRIPTION
**Pull request by polyfractal**
At some point, we changed the supported-type test to also catch assertion errors.  This has the side effect of also catching the `fail()` call inside the try-catch, which silently smothered some
failures.

This modifies the test to throw at the end of the try-catch block to prevent from accidentally catching itself.

Catching the AssertionError is convenient because there are other locations that do throw an assertion in tests (due to hitting an assertion before an exception would normally be thrown for validation, notably in the new usage stuff for multi-VS aggs) so I think we should keep it around.  In most cases it's inline with goal of the test anyway: if an assertion is tripped, it failed that field and would also fail the test as expected.

The PR includes a variety of fixes to other tests which were failing but being silently smothered.

### CODE REVIEW

**Comment by polyfractal** [comment]
@elasticmachine update branch

**Review by not-napoleon — APPROVED** [review]
Nice catch!

**Comment by polyfractal** [comment]
@elasticmachine update branch

**Comment by polyfractal** [comment]
Fine, be that way @elasticmachine :stuck_out_tongue:

**Pull request merged**
