### PR TITLE
Extract a common base class to allow services to listen to remote cluster config updates

### PR DESCRIPTION
**Pull request by s1monw**
RemoteClusterService is an internal service that should not necessarily be exposed
to plugins or other parts of the system. Yet, for cluster name parsing for instance
it is crucial to reuse some code that is used for the RemoteClusterService. This
change extracts a base class that allows to share the settings related code as well
as cluster settings updates to `search.remote.*` to be observed by other services.

### CODE REVIEW

**Comment by s1monw** [comment]
@javanna @tvernum can you look at this?

**Review by tvernum — CHANGES_REQUESTED** [review]
Two small changes, but otherwise it seems good.

I've done some testing and this makes it simple for a plugin to track + parse remote cluster names.

**Comment by s1monw** [comment]
@tvernum can you look again...

**Review by tvernum — APPROVED** [review]
LTGM.

**Pull request merged**
