### PR TITLE
Throw exception if no `elasticsearch.yml` file is found

### PR DESCRIPTION
**Pull request by saschamarkus**
Log message to indicate that no `elasticsearch.yml` file was found

Added a warning despite other methods throw an exception to avoid breaking the former behaviour.
Closes https://github.com/elastic/elasticsearch/issues/11510

### CODE REVIEW

**Comment by clintongormley** [comment]
Hi @saschamarkus 

Thanks for the PR. I think we should go for the exception instead of the warning.  Anybody disagree?

**Comment by metadave** [comment]
@saschamarkus would you mind rebasing against master to see if that helps with merge conflicts?

**Comment by clintongormley** [comment]
Hi @saschamarkus 

Just pinging in case you didn't see this before.

**Comment by saschamarkus** [comment]
Hi,
Sorry for not answering to your messsage. I'll try to rebase this week.
Right now I've a bit busy but I think I'll manage it by the weekend.

Hi @saschamarkus <https://github.com/saschamarkus>

Just pinging in case you didn't see this before.

—
Reply to this email directly or view it on GitHub
<https://github.com/elastic/elasticsearch/pull/11592#issuecomment-127924122>
.

**Comment by saschamarkus** [comment]
Hi,
I created another pull request with me changes on top of the current sources: 
https://github.com/elastic/elasticsearch/pull/12833

**Pull request closed without merging**
