### PR TITLE
Generate a release notes page per patch version

### LINKED ISSUE #85250: Create individual release notes source files
### Description

Per https://github.com/elastic/ml-cpp/issues/2217#issuecomment-1074915751, there have been some issues with the release notes that are generated by the `./gradlew generateReleaseNotes` command. In particular, if there are changes that were manually added to the release notes (either during the PR review or via subsequent edits), it seems easy to accidentally overwrite/lose those edits the next time there's a release that touches the same file.

IMO one simple solution would be to generate a new output file for each release.  For example, 
https://www.elastic.co/guide/en/elasticsearch/reference/8.1/release-notes-8.1.1.html and https://www.elastic.co/guide/en/elasticsearch/reference/8.1/release-notes-8.1.0.html are currently being generated from a single source file (https://github.com/elastic/elasticsearch/blob/8.1/docs/reference/release-notes/8.1.asciidoc), but there's no reason why they can't be generated from individual files (e.g. 8.1.1.asciidoc and 8.1.0.asciidoc) instead.

It would mean the need to add a new "include" statement in https://github.com/elastic/elasticsearch/blob/master/docs/reference/release-notes.asciidoc every time, but since you're already adding a new link to that file anyway (e.g. <<release-notes-8.1.1>>) that doesn't seem like it should be too taxing.

### PR DESCRIPTION
**Pull request by pugnascotia**
Closes #85250. The approach of generating a single asciidoc page for all
releases in a minor series makes it harder to preserve any manual edits
that we have to make. Instead, generate a page per-version. It should
make little difference to the final documentation that users see.

I'll forward-port the task changes once this is merged.

### CODE REVIEW

**Review by mark-vieira — APPROVED** [review]
LGTM

**Review by lcawl — APPROVED** [review]
Output docs LGTM

**Comment by lcawl** [comment]
Will these changes be backported to the 7.17 branch as well?  We have some ml-cpp PRs in https://github.com/elastic/elasticsearch/blob/7.17/docs/reference/release-notes/7.17.asciidoc too, for example.

**Comment by mark-vieira** [comment]
We've been using the "old" release notes process for 7.17 releases I believe. We're going to be releasing off that branch for awhile though so maybe we should move over?

**Comment by mark-vieira** [comment]
What do you think @pugnascotia? How much effort would it be to start using the new process for 7.17?

**Comment by pugnascotia** [comment]
Given that we'd be generating a file per patch version, it'd be much easier to adopt the new process for 7.17 (and 8.0!). I can sort that out after merging this.

**Pull request merged**
