### PR TITLE
Remove redundant check in RestNodesAction

### PR DESCRIPTION
**Pull request by danhermann**
The check in `BaseRestHandler` (lines 87-93) handles the check that was removed from `RestNodesAction`.

https://github.com/elastic/elasticsearch/blob/e735d46bf227c1aede454a2a77b4354bb65fb7c5/server/src/main/java/org/elasticsearch/rest/BaseRestHandler.java#L87

### CODE REVIEW

**Comment by danhermann** [comment]
@elasticmachine test this please

**Comment by danhermann** [comment]
@elasticmachine update branch

**Comment by danhermann** [comment]
@elasticmachine update branch

**Review by dakrone — APPROVED** [review]
LGTM assuming CI is happy

**Comment by danhermann** [comment]
Thanks, @dakrone!

**Pull request merged**
