### PR TITLE
Don't add CWD to classpath when ES_CLASSPATH isn't set.

### PR DESCRIPTION
**Pull request by rmuir**
See #12000 for what this does.

We may need equivalent fix for the .bat file, too

### CODE REVIEW

**Comment by nik9000** [comment]
Looks right to me.

**Comment by rmuir** [comment]
I added fix to the .bat file and it works on windows. I think this is ready.

**Comment by nik9000** [comment]
> I added fix to the .bat file and it works on windows. I think this is ready.

Can anyone check the windows change?

**Comment by rmuir** [comment]
I ran it on a windows VM.

**Comment by nik9000** [comment]
> I ran it on a windows VM.

Cool. I saw the commit message and thought you needed someone. Sorry for the trouble.

**Comment by rmuir** [comment]
Yeah, i edit and pushed from linux to do the minimal work in the windows vm. its too slow :)

**Comment by nik9000** [comment]
> Yeah, i edit and pushed from linux to do the minimal work in the windows vm. its too slow :)

Ah! Makes sense now.

**Comment by rjernst** [comment]
LGTM

**Pull request merged**
