### PR TITLE
Check all actions preventing snapshot delete during retention run

### PR DESCRIPTION
**Pull request by dakrone**
Previously we only checked to see if a snapshot was currently running,
but it turns out that more things can block snapshot deletion. This
changes the check to be a check for:

- a snapshot currently running
- a deletion already in progress
- a repo cleanup in progress
- a restore currently running

This was found by CI where a third party delete in a test caused SLM
retention deletion to throw an exception.

Relates to #43663

### CODE REVIEW

**Review by AthenaEryma — COMMENTED** [review]
Code LGTM, do you think this is worth writing tests for? Normally I'd want tests for something like this, but the logic is very trivial and getting a test to work reliably for some of these might be more trouble than it's worth.

**Comment by dakrone** [comment]
@gwbrown thanks for taking a look. I think the existing tests cover part of this since that is what uncovered it, the other part would be introducing some very troublesome tests since we have to be able to block restore/deletes/cleanup during the retention run. So, I don't think we should add integration tests for this. I did add a unit test for this to check the cluster state in these cases.

**Review by AthenaEryma — APPROVED** [review]
LGTM, thanks!

**Comment by dakrone** [comment]
@elasticmachine update branch

**Pull request merged**
