### PR TITLE
Remove generics from ActionRequest

### LINKED ISSUE #21368: Remove generic on ActionRequest
While reading #3889 it reminds me that `ActionRequest` is a generic class

`public abstract class ActionRequest<Request extends ActionRequest<Request>> ...`

But I don't think it is necessary any more. It could be a simple non-generic abstract class and it would avoid repeating the type everywhere.

### PR DESCRIPTION
**Pull request by rjernst**
closes #21368

### CODE REVIEW

**Comment by rjernst** [comment]
I do not think this is actually a `breaking-java` change as marked in the linked issue as no user would ever use ActionRequest directly?

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by tlrx** [comment]
Thanks @rjernst, I'm happy to see these gone.

**Comment by s1monw** [comment]
👍

**Comment by nik9000** [comment]
👏

**Pull request merged**
