### PR TITLE
EQL: Adjust the bwc tests for multi-value fields support after 7x merge

### LINKED ISSUE #76618: [CI] EqlSearchIT testMultiValueFields failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/xjdf5a7swa5sq/tests/:x-pack:plugin:eql:qa:mixed-node:v7.15.0%23mixedClusterTest/org.elasticsearch.xpack.eql.qa.mixed_node.EqlSearchIT/testMultiValueFields

**Reproduction line:**
`./gradlew ':x-pack:plugin:eql:qa:mixed-node:v7.15.0#mixedClusterTest' -Dtests.class="org.elasticsearch.xpack.eql.qa.mixed_node.EqlSearchIT" -Dtests.method="testMultiValueFields" -Dtests.seed=720B9D4892B62FD9 -Dtests.bwc=true -Dtests.locale=es-US -Dtests.timezone=EST -Druntime.java=11`

**Applicable branches:**
master

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.eql.qa.mixed_node.EqlSearchIT&tests.test=testMultiValueFields

**Failure excerpt:**
```
java.lang.AssertionError: For query [PROCESS where between(process_name, \"w\", \"s\") : \"indow\"]
Response does not match:
                             0: expected String [121] but was String [120]
received [1] more entries than expected

  at __randomizedtesting.SeedInfo.seed([720B9D4892B62FD9:7BAB01D6F0A15323]:0)
  at org.junit.Assert.fail(Assert.java:88)
  at org.elasticsearch.xpack.eql.qa.mixed_node.EqlSearchIT.assertResponse(EqlSearchIT.java:355)
  at org.elasticsearch.xpack.eql.qa.mixed_node.EqlSearchIT.assertMultiValueFunctionQuery(EqlSearchIT.java:324)
  at org.elasticsearch.xpack.eql.qa.mixed_node.EqlSearchIT.testMultiValueFields(EqlSearchIT.java:134)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:566)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:834)

```

### LINKED ISSUE #76632: [CI] EqlSearchIT testMultiValueFields failing
This reproduced locally for me. The failure seem to be specific to mixed node clusters with 7.10.x or 7.11.x nodes.

**Build scan:**
https://gradle-enterprise.elastic.co/s/7i3e2pqrc5uds/tests/:x-pack:plugin:eql:qa:mixed-node:v7.11.2%23mixedClusterTest/org.elasticsearch.xpack.eql.qa.mixed_node.EqlSearchIT/testMultiValueFields

**Reproduction line:**
`./gradlew ':x-pack:plugin:eql:qa:mixed-node:v7.11.2#mixedClusterTest' -Dtests.class="org.elasticsearch.xpack.eql.qa.mixed_node.EqlSearchIT" -Dtests.method="testMultiValueFields" -Dtests.seed=8C02DAC5D1268002 -Dtests.bwc=true -Dtests.locale=ar-QA -Dtests.timezone=Europe/Busingen -Druntime.java=8`

**Applicable branches:**
7.x

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.eql.qa.mixed_node.EqlSearchIT&tests.test=testMultiValueFields

**Failure excerpt:**
```
java.lang.AssertionError: For query [PROCESS where multiply(pid, 10) == 120]
Response does not match:
                             0: same [116]
                             1: same [117]
                             2: same [118]
                             3: same [119]
expected [2] more entries

  at __randomizedtesting.SeedInfo.seed([8C02DAC5D1268002:85A2465BB331FCF8]:0)
  at org.junit.Assert.fail(Assert.java:88)
  at org.elasticsearch.xpack.eql.qa.mixed_node.EqlSearchIT.assertResponse(EqlSearchIT.java:357)
  at org.elasticsearch.xpack.eql.qa.mixed_node.EqlSearchIT.assertMultiValueFunctionQuery(EqlSearchIT.java:326)
  at org.elasticsearch.xpack.eql.qa.mixed_node.EqlSearchIT.testMultiValueFields(EqlSearchIT.java:169)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:817)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:468)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:947)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:832)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:883)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:894)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
  at java.lang.Thread.run(Thread.java:748)

```

### PR DESCRIPTION
**Pull request by astefan**
Change the test code after 7.x has the same code as well. Also, change one of the queries as the old version had issues on versions on or after 7.12.0.
Fixes https://github.com/elastic/elasticsearch/issues/76618.
Fixes https://github.com/elastic/elasticsearch/issues/76632.

### CODE REVIEW

**Review by Luegg — COMMENTED** [review]
Lgtm in general but I don't understand how this PR also fixes https://github.com/elastic/elasticsearch/issues/76618. The according assertion is not changed.

**Comment by astefan** [comment]
@Luegg I think it's [these lines](https://github.com/elastic/elasticsearch/pull/76846/files#diff-940774fa6093399c59f99441931c291126b65ddd51a26802c2ce3a0e3c1dce39L123-L125) that should have been removed and the fact that at the test time it's likely the 7.x code being used in test didn't use the latest PR code. Not 100% sure, but from my tests now, that failure doesn't repro anymore.

**Review by Luegg — APPROVED** [review]
Got it, thanks for elaborating 👍

**Review by bpintea — APPROVED** [review]
Lgtm

**Pull request merged**
