### PR TITLE
Fix Start Trial API output acknowledgement header for features

### LINKED ISSUE #111739: Trial license inconsistencies between the doc and _license/start_trial API
### Description

If you refer to the Elastic documentation for [Start Trial API](https://www.elastic.co/guide/en/elasticsearch/reference/current/start-trial.html), there is the following being mentioned:
> The start trial API enables you to start a 30-day trial, which gives access to **all subscription features**.

Whereas, if you execute `POST /_license/start_trial` in your cluster:
> ”"This API initiates a free 30-day trial for **all platinum features**. By starting this trial, you agree that it is subject to the terms and conditions at https://www.elastic.co/legal/trial_license/. To begin your free trial, call /start_trial again and specify the “acknowledge=true” parameter.“”"

My understanding is that Enterprise features can be used with a trial license so the documentation seems to be accurate on the topic with:  "_which gives access to **all subscription features**_".

The documentation and the `POST /_license/start_trial` output should reflect the same information.

### PR DESCRIPTION
**Pull request by renshuki**
Fixes #111739

### CODE REVIEW

**Review by szabosteve — APPROVED** [review]
Thank you for this change, LGTM!

**Comment by tvernum** [comment]
@elasticmachine update branch

**Review by jakelandis — APPROVED** [review]
LGTM (via es-security)

**Comment by renshuki** [comment]
Thanks all 🙏

**Pull request merged**
