### PR TITLE
Reindex from Remote allow date math

### PR DESCRIPTION
**Pull request by henningandersen**
Previously, reindexing from remote using date math in the source index
name did not work if the math contained / or ,. A workaround was to
then URL escape the index name in the request.

With this change, we now support any index name in the remote request
that the remote source supports, doing the URL escape when sending the
request.

The change still allows escaped requests to allow rolling upgrades. This will be removed in an 8.0 only follow-up.

Related to #23533

### CODE REVIEW

**Comment by henningandersen** [comment]
@elasticmachine test this please

**Comment by henningandersen** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample

**Review by Tim-Brooks — APPROVED** [review]
LGTM

**Comment by henningandersen** [comment]
Thanks @tbrooks8

**Pull request merged**
