### PR TITLE
Remove only node preference

### PR DESCRIPTION
**Pull request by jasontedor**
This commit removes the search preference _only_node as the same
functionality can be obtained by using the search preference
_only_nodes. This commit also adds a test that ensures that _only_nodes
will continue to support specifying node IDs.

Relates #18822

### CODE REVIEW

**Comment by clintongormley** [comment]
With this change, `_only_node` would be silently ignored.  I think we should (at least for 5.x) throw an exception instead?

**Comment by jasontedor** [comment]
I don't think so, I think it will throw as an unrecognized preference.

**Comment by clintongormley** [comment]
Ah sorry, I confused myself with silently ignored unknown QS params.

**Comment by abeyad** [comment]
LGTM

**Comment by jasontedor** [comment]
Thanks @abeyad!

**Pull request merged**
