### PR TITLE
Add clear deprecation around legacy role settings

### PR DESCRIPTION
**Pull request by jasontedor**
We've deprecated the legacy role settings. Individually, when you use such a setting, you will get an individual log message informing you that you've used a legacy role setting. What the deprecation does not tell you though, is the equivalent `node.roles` setting that you should be using to achieve identical functionality to what you have today. This creates a bad user experience. Suppose that you've configured a node (e.g., `node.data: true`, `node.ingest: false`, `node.master: false`, `node.remote_cluster_client: false`), but never explicitly set the legacy `node.transform` setting. In this case, we'll use the default value of `true`. You see the deprecation message informing you that `node.data`, `node.ingest`, `node.master`, and `node.remote_cluster_client` are deprecated. So you do some searching in the docs and discover the `node.roles` setting. So you dutifully set `node.roles: [data]` because this is the only legacy role setting that you've enabled. Well, now you're having a bad time because this will also disable the transform role, which was implicitly enabled. This commit provides a cleared deprecation message in this case:

```
legacy role settings [node.data, node.ingest, node.remote_cluster_client, node.master] are deprecated, use [node.roles=[transform, data_frozen, data_hot, data_content, data_warm, data, data_cold]
```

This should help users transition between the legacy role settings and the new role setting.

Relates #54998

### CODE REVIEW

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by jasontedor** [comment]
@elasticmachine update branch

**Comment by jasontedor** [comment]
The failing test here is #71147, so I've updated my branch to pull in the latest commits that address the failures there.

**Review by przemekwitek — COMMENTED** [review]
LGTM

Thanks for fixing it!

**Pull request merged**
