### PR TITLE
When putHeaders, Order problem.

### PR DESCRIPTION
**Pull request by hanbj**
1、The parameter headers does not have the same key, so the checksum doesn't make sense
2、When checking that key already exists in requestHeaders, you should first put

### CODE REVIEW

**Comment by karmi** [comment]
Hi @hanbj, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/elasticsearch/pull/26037.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by javanna** [comment]
Hi @hanbj , may I ask how you found out about this? Was this a problem that you ran into or something that you noticed while looking at the code?

**Comment by javanna** [comment]
jenkins test this please

**Comment by hanbj** [comment]
@javanna Thank you for verifying the patch, I found this when I read the code

**Comment by hanbj** [comment]
@karmi I've always been using this email on GitHub. How can there be a different signature?

**Comment by hanbj** [comment]
[https://github.com/elastic/elasticsearch/pull/26037/commits/1018a114972dd56a8851dc0b10490801b1e43dd5](1018a11) 
@javanna Accidentally put together, please test together, thank you.

**Comment by karmi** [comment]
@hanbj, this commit was failing the check, https://github.com/elastic/elasticsearch/pull/26037/commits/dbd62062c30c006e5599615eb9e0c0bce87f556b

I think you should `git rebase` instead of merge the upstream commits, that way the PR is cleaner to read...

**Comment by hanbj** [comment]
@karmi  OK, Thanks. I resubmit it.

**Comment by hanbj** [comment]
#26070  #26068
@karmi  I'm sorry to trouble you.  I resubmit it. Thank you

**Pull request closed without merging**
