### PR TITLE
Add second level of field collapsing

### LINKED ISSUE #24855: Multiple levels of field collapse
**Describe the feature**:
Currently, we support 1 level of field collapse + inner hits (https://www.elastic.co/guide/en/elasticsearch/reference/5.4/search-request-collapse.html#_expand_collapse_results).  However, some users need to collapse multiple levels (while still providing features provided by field collapse, e.g. pagination), e.g. to simply provide the top item for 2 tiers of collapsing.  For those users, they  have a few options:

1. Ignore the pagination requirement and do terms+terms+top_hits (which will be fine for some users)
2. In a single query, ask for a very large `inner_hits` `size` and then reduce the set client-side
3. Perform multiple queries: 1 for the first collapse level and then iterate through these for secondary queries

When 1 is not an option for business purposes, this leaves you with options 2 and 3.  2 is a fairly abusive/expensive way to solve it when you're looking for just the top result under each of the top-level collapse.  3 adds a lot of client code as well as round trips (which increase overall query latency).

Unfortunately, opening up multiple levels also opens the query up for abuse in different ways (asking for high depth)

I wanted to open up for discussion the possibility of having multiple levels of field collapse, even if there were additional restrictions (e.g. only 2 levels, only can return a much smaller result set from the second level, etc)

### PR DESCRIPTION
**Pull request by mayya-sharipova**
Closes #24855

### CODE REVIEW

**Review by jimczi — COMMENTED** [review]
It looks good @mayya-sharipova but I wonder if the second `collapse` should be under `inner_hits` ? I know we discussed the proposed format already but I forgot that we can have multiple `inner_hits` in a single collapse so it would be more flexible and consistent to define the `collapse` field there ?

**Comment by mayya-sharipova** [comment]
@jimczi  Thanks Jim, I will try to implement `collapse` under `inner_hits`

**Comment by mayya-sharipova** [comment]
@jimczi  I have modified the PR to make the second level collapse under `inner_hits`.  Now potentially `inner_hits` for nested and parent/child operations can have `collapse` field, but I think it is harmless,  as they will be processed if there is a mail collapse. What do you think?

**Review by jimczi — APPROVED** [review]
Thanks @mayya-sharipova, it looks great !

**Pull request merged**
