### PR TITLE
Limit the number of expanded fields it query_string and simple_query_string

### LINKED ISSUE #25105: Throw error when all_fields mode queries over a certain number of fields
The automatic expansion of fields to query on for the `query_string` and `simple_query_string` queries has been found to have some performance issues for users with a large numbers of fields. See: https://github.com/elastic/kibana/issues/12097

Should we limit the number of fields the auto-expansion is limited to, throwing an error if a query searches more than that many fields? If so, what should the limit be? @jimczi mentioned 100 fields in the original issue as perhaps a good starting point.

### PR DESCRIPTION
**Pull request by dakrone**
This limits the number of automatically expanded fields for the "all fields"
mode (`"default_field": "*"`) for the `query_string` and `simple_query_string`
queries to 1024 fields.

Resolves #25105

### CODE REVIEW

**Review by jimczi — APPROVED** [review]
LGTM
Can you add a small warning in the `query_string` and `simple_query_string` docs regarding this limit ?

**Comment by Bargs** [comment]
@dakrone is there a limit for `multi_match` queries as well?

**Comment by jimczi** [comment]
@bargs Yes I changed the docs in https://github.com/elastic/elasticsearch/commit/792641a6e3992691c3908d011cdafb4201be62cc
The limit is applied to `query_string`, `simple_query_string` and `multi_match` queries.

**Comment by Bargs** [comment]
@jimczi so metricbeat creates more than 1024 fields, which is causing ES [to return errors](https://github.com/elastic/beats/issues/5275) when Kibana sends search requests that expand to all fields. Initially we thought setting the `default_field` in the index pattern settings would be a good solution since metricbeat can handle that without asking the user to do anything. But multi_match doesn't use `default_field`. 

Any ideas how we can handle this gracefully for multi_match?

**Comment by dakrone** [comment]
> Any ideas how we can handle this gracefully for multi_match?

Can you grab the existing value of `default_field` and use that for the `fields` parameter in the `multi_match` query?

**Comment by simianhacker** [comment]
@dakrone They would need to figure out which index to grab it from based on the pattern.

**Comment by Bargs** [comment]
And the `default_field` could potentially be different for different indices that match that index pattern :/

**Pull request merged**
