### PR TITLE
Improve cluster health waiting not found index

### PR DESCRIPTION
**Pull request by weizijun**
when calling cluster health with a not found index, request will block until timeout.
e.g GET /_cluster/health/xxx.
I add a param to control this blocked action. Default case, request will not block. set `wait_for_indices_exists` to true, to block request.

### CODE REVIEW

**Comment by dliappis** [comment]
A few comments:

1. This PR is changing the default behavior which is to wait until timeout. Changing any default behavior needs to be done carefully, as it will impact existing users.

2. I am not certain about what problem gets solved here; the blocking problem can be circumvented e.g. by directly reducing the [timeout](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-health.html#cluster-health-api-query-params) cluster health param (which defaults to 30s).

3. You can always use a HEAD request against the index which you aren't sure about it's presence before probing via the `_cluster/health` API.

**Comment by weizijun** [comment]
> A few comments:
> 
> 1. This PR is changing the default behavior which is to wait until timeout. Changing any default behavior needs to be done carefully, as it will impact existing users.
> 2. I am not certain about what problem gets solved here; the blocking problem can be circumvented e.g. by directly reducing the [timeout](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-health.html#cluster-health-api-query-params) cluster health param (which defaults to 30s).
> 3. You can always use a HEAD request against the index which you aren't sure about its presence before probing via the `_cluster/health` API.

yeah，It change the default behavior, and can be circumvented by set timeout=0. But  the default behavior is a little not so good experience, as It will block 30s if index not found.

**Comment by weizijun** [comment]
@dnhatn hi, can you help to review this pr?

**Comment by stu-elastic** [comment]
Hi @weizijun can you cut an issue discussing the problem you're trying to work around here?

It's a high cost to perform a backwards incompatible change and there may be better designs (eg changing what cluster health returns) to resolve the issue.

**Pull request closed without merging**
