### PR TITLE
Refactor ComposableIndexTemplate construction to use builder

### PR DESCRIPTION
**Pull request by felixbarny**
From #101760:

> Changing all constructor call to use the builder everywhere is not feasible as there are too many usages.

Turns out it was not too difficult with some creative use of inline refactorings and simple search/replace to refactor all usages of the constructor to use the builder instead.

This PR is independent but related to #101760

### CODE REVIEW

**Comment by felixbarny** [comment]
@elasticsearchmachine test this please

**Comment by felixbarny** [comment]
@elasticsearchmachine test this please

**Comment by felixbarny** [comment]
@elasticsearchmachine update branch

**Review by dakrone — APPROVED** [review]
LGTM assuming CI is happy :)

**Pull request merged**
