### PR TITLE
Include root-cause exception when we fail to change shard's index buffer

### PR DESCRIPTION
**Pull request by mikemccand**

### CODE REVIEW

**Comment by rjernst** [comment]
LGTM

**Comment by rmuir** [comment]
Can we remove the variants of error, warn, hell maybe all logger methods that *dont* take throwable? 

Means you gotta think about it, pass null in the cases you don't have one.

**Comment by rmuir** [comment]
and +1 to this fix, lets just make another issue. i think we still want to ban Throwable.toString()/getMessage() there too and just clean house. no fancy IDE refactoring tools, just a lot of beer and old fashioned cleanup grunt work, that's the only to hunt down and fix all these.

**Comment by mikemccand** [comment]
> Can we remove the variants of error, warn, hell maybe all logger methods that dont take throwable?

+1

**Comment by mikemccand** [comment]
> Can we remove the variants of error, warn, hell maybe all logger methods that dont take throwable?

OK I'm gonna give this a shot ...

**Comment by nik9000** [comment]
> OK I'm gonna give this a shot ...

*All* of them? I get removing error that doesn't take one - its pretty rare to have a genuine error without an exception and in those cases we can just call it with null but I figure its reasonably common to have warnings and most trace and info logs won't have an exception to log.

**Comment by mikemccand** [comment]
> All of them? 

Yeah, unfortunately: we use all log levels (even TRACE!) in ES when logging an exception, so I'm exploring making it a required argument to all of them now.

Having to think about it and pass `null` if you don't have an exception seems like the lesser evil than the 2 dozen or so places I've found so far (including this original one, from #14866) that were failing to include the caught exception in their logging ...

**Pull request merged**
