### PR TITLE
Use EWMATrackingEsThreadPoolExecutor for WRITE

### PR DESCRIPTION
**Pull request by pxsalehi**
Relates ES-6248

### CODE REVIEW

**Comment by pxsalehi** [comment]
There are some caveats to using EWMA of the write threadpool as average runtime of indexing request (ARR):

- Obviously it doesn't include writes to system indices. I'm guessing we don't care about this.
- The following two non-write cases are forked to the WRITE threadpool: 
  - failing a shard if necessary in ReplicationOperation:L385/L336.
  -  We've recently moved GlobalCheckpointSync from Management to the Write
    pool. (https://github.com/elastic/elasticsearch/commit/0cf80f4f2d87091860214d9b1d0725fad2833d1d)
- EWMA's weight for newer vs. older data is not configurable (0.3). Not sure if we need to change it.

My understanding is that while both of the extra tasks that use the WRITE threadpool could skew the results a bit, they are not frequent or in case of `GlobalCheckpointSync` happen during periods of inactivity (and probably in stateless different than stateful). Considering the simplicity of just using `EWMATrackingEsThreadPoolExecutor` to get an estimate for ARR, this might be negligible.

**Review by fcofdez — APPROVED** [review]
LGTM 👍

**Comment by fcofdez** [comment]
> EWMA's weight for newer vs. older data is not configurable (0.3). Not sure if we need to change it.

I've added a note to check if the default weight is valid for this use case, otherwise we should make that value configurable.

**Comment by pxsalehi** [comment]
@elasticmachine update branch

**Pull request merged**
