### PR TITLE
[TEST] Mute RoleReferenceIntersectionTests.testBuildRoleForListOfRoleReferences

### PR DESCRIPTION
**Pull request by valeriy42**
Relates #97085

### CODE REVIEW

**Review by thecoop — APPROVED** [review]

**Comment by ChrisHegarty** [comment]
If I understand correctly, then this test only fails on JDK 21. If so, then we should "reduce" the mute to just the version, e.g.

```diff
 public void testBuildRoleForListOfRoleReferences() {
+   // @AwaitsFix(bugUrl = "https://github.com/elastic/elasticsearch/issues/97085")
+   if (Runtime.version().feature() >= 21) {
+      return;
+   }
+
```

**Comment by rjernst** [comment]
>  then we should "reduce" the mute to just the version

We can use assumes, so this shows up as a skipped test in junit
```
assumeFalse("does not work with jdk 21", Runtime.version().feature() >= 21);
```

**Comment by ChrisHegarty** [comment]
A local test shows that this issue is not present in a more recent Mockito, 5.4.0, so update is a good idea, see #97285

**Comment by ChrisHegarty** [comment]
This change is no longer needed. The test passes now with Mockito 5.4.0.

**Pull request closed without merging**
