### PR TITLE
Give the engine the whole index buffer size on init.

### PR DESCRIPTION
**Pull request by jpountz**
Currently the engine is initialized with a hardcoded 256MB of RAM. Elasticsearch
may never use more than that for a given shard, `IndexingMemoryController` only
has the power to flush segments to disk earlier in case multiple shards are
actively indexing and use too much memory.

While this amount of memory is enough for an index with few fields and larger
RAM buffers are not expected to improve indexing speed, this might actually be
little for an index that has many fields.

Kudos to @bleskes for finding it out when looking into a user who was reporting
a **much** slower indexing speed when upgrading from 2.x to 5.6 with an index
that has about 20,000 fields.

### CODE REVIEW

**Comment by jpountz** [comment]
This change would probably be worth backporting to `5.6` though we should probably make it an opt-in via a setting or a JVM command-line argument.

**Comment by jpountz** [comment]
For the record this was introduced in 5.0 via #14121.

**Comment by jpountz** [comment]
I like having protection too, but the fact it doesn't really help anymore once you have several shards that are actively indexing per node makes me wonder whether it is any useful?

**Comment by s1monw** [comment]
> I like having protection too, but the fact it doesn't really help anymore once you have several shards that are actively indexing per node makes me wonder whether it is any useful?

I mean I agree it won't help much. I am still hesitating to open it up all the way without an escape hatch. Can we have a sys property to set it explicitly if shit hits the fan?

**Comment by jpountz** [comment]
I added an escape hatch.

**Review by s1monw — APPROVED** [review]

**Comment by bleskes** [comment]
Lgtm2. Thx @jpountz

**Pull request merged**
