### PR TITLE
Search Queries in parallel - part 2

### PR DESCRIPTION
**Pull request by drempapis**
please see #116812

### CODE REVIEW

**Comment by drempapis** [comment]
@elasticmachine update branch

**Comment by drempapis** [comment]
@elasticmachine update branch

**Comment by drempapis** [comment]
@elasticmachine update branch

**Review by original-brownbear — APPROVED** [review]
LGTM, thanks nice work!

**Comment by drempapis** [comment]
Thank you @original-brownbear for reviewing this pr

**Pull request merged**
