### PR TITLE
Add Watcher to available rest resources

### PR DESCRIPTION
**Pull request by jakelandis**
Prior to this commit Watcher explicitly copied test between two
projects with a copy task. This commit removes the explicit copy in favor
of adding the Watcher tests to the available restResources that may be
copied between projects.

This is how inter-project dependencies should be modeled. However, only
Watcher is included here since it is (currently) the only project with
inter-project test dependencies.

### CODE REVIEW

**Comment by jakelandis** [comment]
failure looks related :( , looking into this.

**Comment by jakelandis** [comment]
@elasticmachine update branch

**Review by mark-vieira — APPROVED** [review]
This is awesome. LGTM 👍

**Comment by jakelandis** [comment]
Before merging, need to re-run tests through CI after https://github.com/elastic/elasticsearch/pull/53447 is merged.

**Comment by jakelandis** [comment]
@elasticmachine update branch

**Comment by jakelandis** [comment]
This failed the intake test and was reverted.  removing labels and will re-reintroduce in a different PR

```
Caused by: 
org.gradle.api.InvalidUserDataException
: 
Cannot change dependencies of dependency configuration ':x-pack:plugin:restXpackSpecs' after it has been included in dependency resolution.
Close stacktrace
at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.preventIllegalMutation(DefaultConfiguration.java:1131)
at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.validateMutation(DefaultConfiguration.java:1093)
at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.lambda$validateMutationType$1(DefaultConfiguration.java:297)
at org.gradle.internal.ImmutableActionSet$SingletonSet.execute(ImmutableActionSet.java:225)
at org.gradle.api.internal.DefaultDomainObjectSet.assertMutableCollectionContents(DefaultDomainObjectSet.java:70)
at org.gradle.api.internal.DefaultDomainObjectCollection.add(DefaultDomainObjectCollection.java:252)
at org.gradle.api.internal.DelegatingDomainObjectSet.add(DelegatingDomainObjectSet.java:110)
at org.gradle.api.internal.artifacts.DefaultDependencySet.add(DefaultDependencySet.java:68)
at org.gradle.api.internal.artifacts.DefaultDependencySet.add(DefaultDependencySet.java:36)
at org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.doAdd(DefaultDependencyHandler.java:132)
at org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.add(DefaultDependencyHandler.java:107)
at org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.add(DefaultDependencyHandler.java:102)
```

**Pull request merged**
