### PR TITLE
[TEST] More MetadataStateFormat tests

### PR DESCRIPTION
**Pull request by grcevski**
* Add test about partial failure on multi-paths. Having stale metadata is expected and OK with cleanUp set to false
* Add test for deleteMetaState

Relates to https://github.com/elastic/elasticsearch/pull/78475

### CODE REVIEW

**Review by rjernst — APPROVED** [review]
The new tests look good to me. @henningandersen do you have any thoughts?

**Comment by rjernst** [comment]
The CI failure is https://github.com/elastic/elasticsearch/issues/78783, syncing with master should mute it.

**Comment by grcevski** [comment]
@elasticmachine run elasticsearch-ci/part-2

**Review by henningandersen — COMMENTED** [review]
Thanks for improving our test coverage, Nikola. I left some smaller comments, otherwise this looks good.

**Review by henningandersen — APPROVED** [review]
LGTM.

**Pull request merged**
