### PR TITLE
[docs] Remove repeating words

### PR DESCRIPTION
**Pull request by lipsill**
Trivial change removing repeating words from a few docs

### CODE REVIEW

**Comment by jtibshirani** [comment]
@elasticmachine test this please

**Comment by lipsill** [comment]
@jtibshirani thanks for starting a build!

I see that the CI failed with an error. I am not familiar with the build process, but going out on a limb, I would assume that the failure is not caused by this PR (only .asciidoc changes).

Can somebody have a look why the build failed? Agent running out of space? Another issue bubbling up? Thanks!

```
> Task :distribution:bwc:staged-minor-snapshot:buildBwcVersion FAILED
FAILURE: Build failed with an exception.

* Where:
Build file '/var/lib/jenkins/workspace/elastic+elasticsearch+pull-request/distribution/bwc/build.gradle' line: 193
:distribution:bwc:staged-minor-snapshot:buildBwcVersion (Thread[Task worker for ':',5,main]) completed. Took 2 mins 5.066 secs.

3094 actionable tasks: 2012 executed, 1082 up-to-date
* What went wrong:
Execution failed for task ':distribution:bwc:staged-minor-snapshot:buildBwcVersion'.
> Building bwc version didn't generate expected files [/var/lib/jenkins/workspace/elastic+elasticsearch+pull-request/distribution/bwc/staged-minor-snapshot/build/bwc/checkout-6.4/distribution/archives/oss-zip/build/distributions/elasticsearch-oss-6.4.0-SNAPSHOT.zip, /var/lib/jenkins/workspace/elastic+elasticsearch+pull-request/distribution/bwc/staged-minor-snapshot/build/bwc/checkout-6.4/distribution/archives/zip/build/distributions/elasticsearch-6.4.0-SNAPSHOT.zip, /var/lib/jenkins/workspace/elastic+elasticsearch+pull-request/distribution/bwc/staged-minor-snapshot/build/bwc/checkout-6.4/distribution/packages/oss-deb/build/distributions/elasticsearch-oss-6.4.0-SNAPSHOT.deb, /var/lib/jenkins/workspace/elastic+elasticsearch+pull-request/distribution/bwc/staged-minor-snapshot/build/bwc/checkout-6.4/distribution/packages/deb/build/distributions/elasticsearch-6.4.0-SNAPSHOT.deb, /var/lib/jenkins/workspace/elastic+elasticsearch+pull-request/distribution/bwc/staged-minor-snapshot/build/bwc/checkout-6.4/distribution/packages/oss-rpm/build/distributions/elasticsearch-oss-6.4.0-SNAPSHOT.rpm, /var/lib/jenkins/workspace/elastic+elasticsearch+pull-request/distribution/bwc/staged-minor-snapshot/build/bwc/checkout-6.4/distribution/packages/rpm/build/distributions/elasticsearch-6.4.0-SNAPSHOT.rpm]
```

**Comment by lipsill** [comment]
@hub-cap thanks for looking into this! And explaining what went wrong:)

PR updated.

**Review by cbuescher — APPROVED** [review]
LGTM, I don't think this needs another CI run since there are no changes here that affect any tests or docs tests. I just built the docs itself and that looks okay. Will merge this in.

**Comment by lipsill** [comment]
Thanks @cbuescher :)

**Pull request merged**
