### PR TITLE
Always Emit Inference ID in Semantic Text Mapping

### PR DESCRIPTION
**Pull request by Mikep86**
Always emit the `inference_id` param when writing a `semantic_text` field mapping to XContent.

### CODE REVIEW

**Review by jimczi — APPROVED** [review]
LGTM

**Review by kderusso — COMMENTED** [review]
Changes LGTM but I'd like to request two additional things: 
1. A Yaml test that shows the default mapping 
2. Documentation update that says the inference ID is always returned (that can come in a followup due to time)
Thanks for addressing this so quickly.

**Comment by Mikep86** [comment]
@elasticmachine update branch

**Review by carlosdelest — APPROVED** [review]

**Review by kderusso — APPROVED** [review]
LGTM! Thank you!

**Pull request merged**
