### PR TITLE
Remove redundant response of empty result in AsyncShardFetch to avoid OOM issue

### PR DESCRIPTION
**Pull request by maosuhan**
In the process of full restart, OOM problems are often encountered. After dump analysis and we found the following problems.

image

In the process of fetching data, the master will ask each data whether it owns the shard, and all the returned results of the node will be saved in the map<nodeId, nodeResponse> in AsyncShardFetch. In most cases, a shard only has data on several nodes, but the intermediate result map will still save the return results of all nodes.

In this MR, we only save valid intermediate result of node responses and ignore the node responses that does not hold the shard at all.

It is proved to be successfully in our company and the OOM issue is gone after the optimization.

### CODE REVIEW

**Comment by DaveCTurner** [comment]
What version are you using @maosuhan? I think this excessive memory usage was addressed by https://github.com/elastic/elasticsearch/pull/77991.

**Comment by maosuhan** [comment]
@DaveCTurner We already backport the #77991, but the OOM issue still exists.
We use 7.6.2 in production. The shard number is 1 million, and the nodes number is nearly 400.

The main part which occupy the memory is not DiscoveryNode but StoreFilesMetadata which is a node response content and is relatively large.

**Comment by DaveCTurner** [comment]
Can you help me understand why an empty `StoreFilesMetadata` is still "relatively large". I get that there are a lot of them, but each one should be small. Is that not the case?

I think this will be addressed by some bigger changes related to https://github.com/elastic/elasticsearch/issues/77466, particularly https://github.com/elastic/elasticsearch/issues/80694 and friends.

**Comment by DaveCTurner** [comment]
Also would you [sign the CLA](https://www.elastic.co/contributor-agreement)?

**Comment by maosuhan** [comment]
CLA Done @DaveCTurner

**Comment by maosuhan** [comment]
@DaveCTurner  As you can see in the screenshot, there was totally 32927024 objets in the dump and they occupied more than 15GB. 
So each object size is 0.45KB.

**Comment by DaveCTurner** [comment]
> So each object size is 0.45KB.

i.e. 450 bytes. That's a lot more than I expect. Can you explain why it's so much?

**Comment by DaveCTurner** [comment]
Are you sure you signed the CLA with the address `maosuhan@bytedance.com` attached to your commits? I don't see this address in the list.

**Comment by DaveCTurner** [comment]
On reflection I'd rather avoid allocating these objects entirely rather than creating them and then filtering them out as proposed here. https://github.com/elastic/elasticsearch/pull/84034 should do what we want.

**Comment by maosuhan** [comment]
Thanks for your effort! I think it is more reasonable to do that.
I just debugged in IDE, below is the screenshot.
image

metadata and commitUserData are all empty HashMap which is read through streamInput. And each hashmap will occupy 64 bytes each. So the object is at least 128 bytes.
The non-empty result is definitely much larger than the empty ones but the accumulated wasted memory will be very large if the cluster and node number are both large.
Feel free to close this issue.

**Comment by DaveCTurner** [comment]
Sounds good, thanks. Closing this, will proceed with https://github.com/elastic/elasticsearch/pull/84034 instead.

**Pull request closed without merging**
