### PR TITLE
Update Execute Watch to allow unknown fields

### PR DESCRIPTION
**Pull request by hub-cap**
ExecuteWatchResponse did not allow unknown fields. This commit fixes the
test and ConstructingObjectParser such that it does now allow unknown
fields. It also creates a new client side test for the response.

Relates #36938

### CODE REVIEW

**Review by jakelandis — APPROVED** [review]
LGTM

**Comment by hub-cap** [comment]
@elasticmachine run gradle build tests 1
@elasticmachine run gradle build tests 2

**Comment by hub-cap** [comment]
@elasticmachine run gradle build tests 1

**Comment by hub-cap** [comment]
@elasticmachine run gradle build tests 1

**Pull request merged**
