### PR TITLE
[Docs] add missing snapshot restore reference

### PR DESCRIPTION
**Pull request by hub-cap**

### CODE REVIEW

**Comment by hub-cap** [comment]
one Q for docs, how far do we backport things like this? Is it thru every minor back to 6.8?

**Comment by hub-cap** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by jrodewig** [comment]
@hub-cap Yes. We typically backport doc changes through every minor to the last supported version (currently 6.8).

Let me know if you'd like any help testing doc builds for the backports.

**Comment by hub-cap** [comment]
ty @jrodewig for the confirm Ive added the versions to the label.

**Review by jdconrad — APPROVED** [review]
LGTM

**Comment by hub-cap** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by hub-cap** [comment]
oh as for testing the docs @jrodewig, is the same command for all of the branches? I know there was a bunch of work done in the docs repo with docker etc, and i used the updated command to test against master, but im curious if I can use that all the way back to 6.8 or not.

**Comment by jrodewig** [comment]
@hub-cap Yes. You can use the `docbldesx` command from the [doc build aliases](https://github.com/elastic/docs/blob/master/doc_build_aliases.sh) to locally test branches back to 6.8.

The command changes for 6.2 and earlier, but we rarely need to touch those docs nowadays.

**Comment by hub-cap** [comment]
@elasticmachine update branch

**Comment by hub-cap** [comment]
@elasticmachine update branch

**Comment by hub-cap** [comment]
@elasticmachine update branch

**Pull request merged**
