### PR TITLE
Max doc frequency percentage in More Like This query

### LINKED ISSUE #14114: Max doc frequency percentage in More Like This query
More Like This Query has max_doc_freq settings that can be used to remove high-frequency words from search. It is not a frequency but an absolute value. The problem that actual value for index depends on number of documents in the index - larger indexes requires larger values to filter out domain specific stop words. 

I found that XMoreLikeThis actually has `setMaxDocFreqPct(int maxPercentage)` method that recalculates percentage to actual number of documents in index.

However, this method is not available to client. I would be great if you add it to java client and HTTP API.

### PR DESCRIPTION
**Pull request by Michael-karn-ivanov**
Closes #14114

### CODE REVIEW

**Comment by Michael-karn-ivanov** [comment]
Just signed CLA ..

**Comment by danielmitterdorfer** [comment]
@Michael-karn-ivanov: Sorry, that we did not come back to you before. I have checked what's wrong with your CLA. You have signed the CLA with your gmail address but have committed the change with your work address (Microsoft domain). Can you please check whether your work email appears in the [email settings of your Github profile](https://github.com/settings/emails)? If not, can you please add it as secondary email (which is hidden by Github)? We will then rerun the CLA check again and it should then work.

**Comment by clintongormley** [comment]
@danielmitterdorfer the CLA is now signed.  Could you take a look at this again?

**Comment by danielmitterdorfer** [comment]
@Michael-karn-ivanov: I had a quick look at it. Can you please rebase on current master and also add documentation for the new parameter in `docs/reference/query-dsl/mlt-query.asciidoc`? After the rebase I'll have a closer look.

**Comment by dakrone** [comment]
Closing as there has been no feedback, feel free to comment if this was closed erroneously.

**Pull request closed without merging**
