### PR TITLE
Add upper and lower max chunk size limits to ChunkingSettings

### PR DESCRIPTION
**Pull request by dan-rubinstein**
## Description
We currently do not have an upper limit the max chunk size provided by the user in either word or sentence boundary chunking settings. The lower limit is currently 1 which is not a useful chunk size to set. To provide more reasonable limits to the users this change introduces a lower limit of 10 words for word based strategies and 20 words for sentence based strategies as well as an upper limit of 300 for word and sentence based strategies.

## Testing
- Unit tests
- Ensured that creating embedding endpoints with valid chunking strategies succeeds and endpoints successfully chunk large documents.
- Ensured that attempting to create embedding endpoints with max chunk sizes that are too low or too high fails.

Note: There is still an outstanding question of whether we want to allow 0 overlap on word based chunking settings. We currently force the user to provide a positive integer so 0 is not an option. We should hold off on merging this PR until we decide on this.

### CODE REVIEW

**Comment by dan-rubinstein** [comment]
@elasticmachine merge upstream

**Review by davidkyle — APPROVED** [review]
LGTM, left a suggestion on the tests if they pass it's good to merge

**Comment by dan-rubinstein** [comment]
@elasticmachine merge upstream

**Review by davidkyle — APPROVED** [review]
LGTM

**Pull request merged**
