### PR TITLE
Lazily initialize template model - take II

### LINKED ISSUE #76346: `IngestDocument::createTemplateModel` impacts ingest performance
I did some profiling while executing an ingest node pipeline. Turns out, a lot of CPU cycles and allocations are due to `IngestDocument::createTemplateModel`. 
https://github.com/elastic/elasticsearch/blob/3cbc948d75f91221312ddefc0f3652fee71a08a3/server/src/main/java/org/elasticsearch/ingest/IngestDocument.java#L662-L669
The culprit is `new HashMap<>(sourceAndMetadata)` and that `createTemplateModel` may be called multiple times in the same ingest pipeline.

For example, if there are multiple `set` processors, each one calls `IngestDocument#hasField(TemplateScript.Factory)` and `IngestDocument#setFieldValue(TemplateScript.Factory fieldPathTemplate, ValueSource valueSource)` which, in turn, call `createTemplateModel`.
https://github.com/elastic/elasticsearch/blob/da29bb028f4edd71f2a0e5e778943cca727f8307/modules/ingest-common/src/main/java/org/elasticsearch/ingest/common/SetProcessor.java#L74-L81

Is it possible to cache the value of `createTemplateModel` so that the price has to be paid only once vs multiple times for every `set` processor? I guess one issue with that is how to keep the model in sync with changes in the source document.

I've noticed that `sourceAndMetadata` is added to the map twice: one to the root and another time under the `_source` key. 

https://github.com/elastic/elasticsearch/blob/da29bb028f4edd71f2a0e5e778943cca727f8307/server/src/main/java/org/elasticsearch/ingest/IngestDocument.java#L663-L664

Any way we could get rid of adding it to the root, which is the main source of the overhead? When doing so, the template model may even be eagerly created as keeping it in sync with changes is not an issue then.

### PR DESCRIPTION
**Pull request by felixbarny**
Fixes #76346

Similar to https://github.com/elastic/elasticsearch/pull/76356 but takes a different approach without API changes. This makes the compatibility tests pass and requires fewer code changes overall.

Before:
flamegraph

After:
flamegraph_lazy_model

### CODE REVIEW

**Comment by felixbarny** [comment]
Another interesting alternative would be `org.apache.commons.collections4.map.CompositeMap` but it's not available in the classpath and I'm not sure it's worth adding the dependency.

**Comment by felixbarny** [comment]
Hey @danhermann, did you have a chance to look at this approach?

**Comment by danhermann** [comment]
> Hey @danhermann, did you have a chance to look at this approach?

Not yet. It will probably be the end of next week or so before I have time to review it.

**Comment by felixbarny** [comment]
This is not super urgent, just wanted to check in.
Thanks for the heads up 🙂

**Review by danhermann — APPROVED** [review]
Thanks, @felixbarny, this LGTM.

**Pull request merged**
