### PR TITLE
Rename string_field script context to keyword_field

### PR DESCRIPTION
**Pull request by javanna**
Up until now, the name of the script contexts that runtime fields use was internal only. They recently got exposed through the painless execute API. This commit fixes the discrepancy between the field type used to define a runtime field of type keyword and the script context needed to simulate its corresponding script: string_field should be keyword_field.

### CODE REVIEW

**Review by nik9000 — APPROVED** [review]
LGTM.

I figure if we end up adding other string-valued runtime fields we can figure out what to do then.

**Review by jdconrad — APPROVED** [review]
Thanks for updating this!

**Comment by javanna** [comment]
the rest-compat tests here are expected to fail, because the tests from 7.x use string_field that we are renaming to keyword_field in master with this change. This is ok though because painless execute does not support the runtime fields context in any public release, so we are ok breaking this between 7.x and master.

**Comment by javanna** [comment]
run elasticsearch-ci/rest-compat

**Pull request merged**
