### PR TITLE
add 7.1.1 and 6.8.1 versions

### PR DESCRIPTION
**Pull request by jakelandis**
Related: #42240
Related: #42242
Related: #42251

### CODE REVIEW

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by jakelandis** [comment]
@elasticmachine run elasticsearch-ci/1
@elasticmachine run elasticsearch-ci/packaging-sample

**Comment by jakelandis** [comment]
@elasticmachine run elasticsearch-ci/bwc 
@elasticmachine run elasticsearch-ci/default-distro

**Comment by jakelandis** [comment]
BWC failure is https://github.com/elastic/elasticsearch/issues/42258 ... trying again 

@elasticmachine run elasticsearch-ci/bwc

**Comment by polyfractal** [comment]
Muted the date_histo bwc failure (https://github.com/elastic/elasticsearch/commit/570e8edc1e25f1c5197307f40fd4f73e0950620f), as I suspect it will fail again :(

**Comment by jakelandis** [comment]
> Muted the date_histo bwc failure (570e8ed), as I suspect it will fail again :(

Indeed. Merged in master and trying again.

**Comment by jakelandis** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by jakelandis** [comment]
bwc failed [1], trying again..  (my local setup failed but for what appears to be a different reason)

@elasticmachine run elasticsearch-ci/bwc

[1]
```
    org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT.test {p0=mixed_cluster/40_ml_datafeed_crud/Test old cluster datafeed with aggs}
    org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT.test {p0=mixed_cluster/50_token_auth/Get the indexed token and use if to authenticate}
    org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT.test {p0=mixed_cluster/50_token_auth/Get the indexed refresh token and use it to get another access token and authenticate}
    org.elasticsearch.upgrades.UpgradeClusterClientYamlTestSuiteIT.test {p0=mixed_cluster/50_token_auth/Get the indexed refreshed access token and use if to authenticate}
    org.elasticsearch.upgrades.TokenBackwardsCompatibilityIT.testTokensStayInvalidatedInMixedCluster
    org.elasticsearch.upgrades.TokenBackwardsCompatibilityIT.testRefreshingTokensInMixedCluster
    org.elasticsearch.upgrades.TokenBackwardsCompatibilityIT.testGeneratingTokensInMixedCluster
    org.elasticsearch.upgrades.TokenBackwardsCompatibilityIT.testAccessTokensWorkInMixedCluster
    org.elasticsearch.upgrades.TokenBackwardsCompatibilityIT.testInvalidatingTokensInMixedCluster
```

**Comment by jakelandis** [comment]
If the tests pass feel free to merge

**Comment by tvernum** [comment]
The BWC failure in `:x-pack:qa:rolling-upgrade` looks real. I'm investigating.

**Comment by tvernum** [comment]
The BWC failure is real, due to master and 7.x being out of sync after a backport. @jkakavas will fix.

**Comment by jkakavas** [comment]
Sorry for the trouble, https://github.com/elastic/elasticsearch/commit/49bd667cbd156fbd588d867c40f8b760c47281e1 should fix this

**Comment by tvernum** [comment]
I've merged master into this PR. With any luck the next build should be green.

**Comment by jkakavas** [comment]
```
"org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT.test {yaml=reference/mapping/types/date_nanos/line_29}"
```

failed but doesn't reproduce locally, I'll respin

@elasticmachine run elasticsearch-ci/1

**Comment by jkakavas** [comment]
BWC failed now because of https://github.com/elastic/elasticsearch/blob/290c8b8256fc4da512e7bbe1c727005c21d55a67/x-pack/qa/rolling-upgrade/src/test/java/org/elasticsearch/upgrades/RollupDateHistoUpgradeIT.java#L37

I'll push to master and here and re-spin this

**Comment by jkakavas** [comment]
Looks like https://github.com/elastic/elasticsearch/issues/39105

Failure: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-1/14172/

@elasticmachine run elasticsearch-ci/1

**Pull request merged**
