### PR TITLE
Remove PageCacheRecycler.

### PR DESCRIPTION
**Pull request by jpountz**
PageCacheRecycler is a sort of memory manager on top of the JVM that tries to
reuse fixed-sized pages of memory. I am unhappy about it because I don't think
it is elasticsearch's job to provide a memory management framework. Reusing
memory may be useful at times, but then it should be contained in the component
that needs to reuse memory.

By trying to be general-purpose, PageCacheRecycler also needs to allocate memory
to the JVM (10% by default), which is memory that the JVM cannot get back, even
in case of memory pressure.

Also allocations which are performed through PageCacheRecycler are only large
arrays, which should already be GC-friendly without recycling.

### CODE REVIEW

**Comment by s1monw** [comment]
I am +1 on this I think it's the right thing todo

**Comment by rjernst** [comment]
Big +1!

**Comment by jpountz** [comment]
I created a (terrible) [benchmark](https://gist.github.com/jpountz/a08fb6f8c9c0e2d90b23) and compared memory usage profiles with jconsole. The above profile is the one with page cache recycling disabled and the below one has the recycler enabled.

Maybe it's because it did not run long enough (20 min each) but I can't see much that would convince me that one is better than the other. Maybe a slight difference is that with the cache recycler on, memory usage looks a bit higher, which I guess is related to the fact that it can reserve up to 10% of the JVM memory for recycling.

jconsole

**Comment by jpountz** [comment]
I re-ran the benchmark with gc logging enabled this time in order to be able to perform a better comparison. And also with a fixed heap and ParNew/CMS instead of the default throughput collector.

I ran the experiment twice with the page cache recycler enabled and twice with the page cache recycler disabled, 20 min. every time. Unfortunately statistics about major collections were very inconsistent from run to run, so I only report here information about pauses in ParNew which looked consistent:

 | Without PageCacheRecycler | With PageCacheRecycler
------------- | ------------- | -------------
Pause time in ParNew / min | 2.31 sec - 2.19 sec  | 1.65 sec - 1.60 sec
Number of ParNew pauses / min | 20.8 - 21.4 | 12.47 - 11.60

The page cache recycler seems to actually help ParNew, but by less than one second per minute. I was hoping to see the impact with major garbage collections, but given that runs do not reproduce at all, I don't think we can draw any conclusions... In case someone would like to analyze gc logs, I added them to https://gist.github.com/jpountz/a08fb6f8c9c0e2d90b23

**Comment by nik9000** [comment]
Parnew was always my problem anyway.

**Comment by s1monw** [comment]
it's hard to see any real difference to make any decision. @kimchy any idea where we are moving towards?

**Comment by nik9000** [comment]
I'm of the opinion that anything you can do to cause fewer ParNew allocations the better. Those stop the world and they only get longer the bigger your heap because of that card check phase. From that perspective this looks like a pretty bad change.

**Comment by jpountz** [comment]
Closing then.

**Pull request closed without merging**
