### PR TITLE
Run packaging tests on RHEL 8

### PR DESCRIPTION
**Pull request by ghost**
Run the packaging tests on RHEL 8 Beta.

A suitable Vagrant box is [now available](https://app.vagrantup.com/elastic/boxes/rhel-8-x86_64).

### CODE REVIEW

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by jarpy** [comment]
Is it correct to infer from those labels that this patch should be backported to `7.0` but not `7.1`?

**Comment by jasontedor** [comment]
@jarpy That’s a result of some gymnastics taken on the labels today. It would be great to backport this to 7.0, 7.1, and 7.x.

**Comment by jarpy** [comment]
Thanks. I just didn't want to mess it up! :+1:

**Comment by jarpy** [comment]
`7.1`: 5cd2d3af6bc
`7.0`: ada1e9de287
`7.x`: 81163455a83

**Pull request merged**
