### PR TITLE
Javadocs for Painless processor methods

### PR DESCRIPTION
**Pull request by danhermann**
Relates to #72722 and future ingest methods that will be exposed in Painless

### CODE REVIEW

**Comment by danhermann** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by danhermann** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by danhermann** [comment]
Unrelated BWC test failure

**Review by jakelandis — APPROVED** [review]
LGTM

**Comment by danhermann** [comment]
Thanks, @jakelandis!

**Pull request merged**
