### PR TITLE
[8.x] Adding chunking settings to MistralService, GoogleAiStudioService, and HuggingFaceService (#113623)

### PR DESCRIPTION
**Pull request by dan-rubinstein**
Backports the following commits to 8.x:
 - Adding chunking settings to MistralService, GoogleAiStudioService, and HuggingFaceService (#113623)
 - Removing unnecessary platfromArchitectures from InferenceService tests (https://github.com/elastic/elasticsearch/pull/113890)
 - https://github.com/elastic/elasticsearch/pull/114061

### CODE REVIEW

**Comment by dan-rubinstein** [comment]
@elasticmachine merge upstream

**Comment by dan-rubinstein** [comment]
@elasticmachine merge upstream

**Review by maxhniebergall — APPROVED** [review]
LGTM

**Comment by dan-rubinstein** [comment]
@elasticmachine merge upstream

**Comment by dan-rubinstein** [comment]
@elasticmachine merge upstream

**Review by maxhniebergall — APPROVED** [review]
LGTM

**Pull request merged**
