### PR TITLE
Tests: Avoid unicode strings in alternative query builder tests

### PR DESCRIPTION
**Pull request by cbuescher**
When testing alternative versions of the json syntax for the term queries (SpanTermQueryBuilder and TermQueryBuilder) we don't go trough the doXContent json rendering, so having a unicode value creates problems for the parser later, causing those tests to fail rarely. Since Unicode values are generally tested elsewhere, I suggest we make sure we always have ascii here.

### CODE REVIEW

**Comment by tlrx** [comment]
I think we should only escape `"` and control chars as required by the JSON specification and allow unicode to be part of the randomized string value.

**Comment by cbuescher** [comment]
@tlrx thanks, added quoting for unicode strings in the test setup. Care to take another look?

**Comment by tlrx** [comment]
LGTM

**Comment by cbuescher** [comment]
Merged with affe2f2

**Pull request closed without merging**
