### PR TITLE
Wire concurrent top docs collector managers when size is 0

### PR DESCRIPTION
**Pull request by javanna**
We recently introduced a collector manager for PartialHitCountCollector. This commit enables top docs collection to use it (when size is set to 0). This effectively makes collection support concurrency when size is set to 0. 

Note: We don't yet set an executor to the index searcher, so no concurrency is enabled with this change.

### CODE REVIEW

**Review by cbuescher — APPROVED** [review]
LGTM

**Comment by javanna** [comment]
run elasticsearch-ci/part-3

**Review by iverase — APPROVED** [review]
LGTM

**Comment by iverase** [comment]
Actually I think we should not push this change until we address issues with timeouts. In that case the reduce method is not called and we might end up with strange results: https://github.com/elastic/elasticsearch/pull/97769#issuecomment-1641249894

**Review by iverase — DISMISSED** [review]
This PR expects that the reduce method will be always called. When there is a timeout, we are currently not calling the reduce method, therefore this approach will not work . We need to address that first.
It is a bit worrying there were not failing tests.

**Comment by javanna** [comment]
@iverase you are correct. terminate after is no longer exception driven, so we are good there. But timeouts are. I have an idea to work around it. In the long run we will need to move to lucene timeout support. I don't yet understand how the build can be green though, because effectively we are not exposing partial results after a timeout. That gave me the false impression that we need to fix timeout handling only before setting the executor. i agree with your assessment that we need to address that before getting this PR in, and get some tests to fail with my changes.

**Comment by iverase** [comment]
I noticed when implementing the reduce method for aggregations. Interestingly the failing test is unrelated to testing aggregations so we are not good in that area either.

**Comment by javanna** [comment]
Great to see `QueryPhaseTimeoutTests` fail now that #97945 is merged. That is expected and #97771 will address that problem.

**Pull request merged**
