### PR TITLE
Forbid guava group instead of artifact name

### PR DESCRIPTION
**Pull request by rjernst**
We disallow including guava on the compile classpaths, but currently
this only forbids the main guava artifact. Yet there are other artifacts
(eg failureaccess) provided by guava. This commit changes the dependency
check to use the guava group instead of artifact name.

### CODE REVIEW

**Comment by rjernst** [comment]
@elasticmachine run elasticsearch-ci/example-plugins

**Review by pugnascotia — APPROVED** [review]

**Review by mark-vieira — APPROVED** [review]
LGTM

**Comment by rjernst** [comment]
@elasticmachine update branch

**Comment by rjernst** [comment]
@elasticmachine run 
elasticsearch-ci/part-2

**Pull request merged**
