### PR TITLE
Fix mutateInstance for SearchTemplateRequestTests

### PR DESCRIPTION
**Pull request by jdconrad**
A seed was hit in (https://github.com/elastic/elasticsearch/issues/43157) that caused mutateInstance to generate an identical instance. This change prevents that.

### CODE REVIEW

**Comment by jdconrad** [comment]
@jtibshirani Requested your review as you were the last person to work on this.  Thanks in advance!

**Review by hub-cap — APPROVED** [review]
:shipit:

**Comment by jdconrad** [comment]
@baz Thanks for the review! @jtibshirani Sorry to ping you on this - just realized that you're on vacation, so I found a different reviewer.

**Comment by mayya-sharipova** [comment]
backported to 6.8 as well as there were failures of this test there.

**Comment by jtibshirani** [comment]
Also backported to 7.x. In general we can pre-emptively backport these fixes to all branches that are actively tested.

**Pull request merged**
