### PR TITLE
Make circuit breaker mutations debuggable

### PR DESCRIPTION
**Pull request by Tim-Brooks**
This commit is related to #25891. It adds a new abstract class
`DebuggingBreaker` that circuit breaker implementations extend. This
class requires mutations to the circuit breaker use a "breaker key".
This allows the breaker to track modifications and where they occur.

The modifications will be tracked if the setting "*.debug" is set to
true for a breaker instance. The stacktraces of modifications will be
tracked if the setting "*.debug.stacktrace" is set to true for a breaker
instance.

This commit implements this functionality for the "request" breaker when
used by `BigArrays`. The functionality remains the same for other
breaker usages.

### CODE REVIEW

**Comment by tbrooks8** [comment]
This is some initial work. Before I implemented this work beyond `BigArrays` I wanted some feedback.

Currently it tracks:
1. Changes in bytes
2. Stacktraces (if setting enabled).

I have not made this data accessible. I assume we will want that under the "cat" api? Also, do we want the stracktraces to be automatic if we are in debug mode? I added an extra setting for that but maybe it is not needed?

**Comment by rjernst** [comment]
I wonder if we could look at this instead from a different angle. Often in Lucene, we have "AssertingXXX" classes, which wrap the real class, and add accounting plus assertions, and the test framework does the wrapping automatically. We already having a MockBigArrays which is used by tests. If we had an AssertingBreaker, which could wrap any breaker, then we could hammer it with randomized testing, and ensure it always releases etc.  While additional debugging seems nice to some extent, I think we should strive for how to avoid these problems through testing, instead of investigate them when it is too late.

**Comment by s1monw** [comment]
I agree with what @rjernst said.

**Comment by dakrone** [comment]
I agree, I think the asserting wrapper would be good. I do think that perhaps we may want to leave something that allows us to debug the breaker in a production case, rather than making the wrapper test-only (or we could have two wrappers).

**Comment by rjernst** [comment]
Couldn't the logging be done at the consumer sites, so the implementation doesn't matter? Otherwise the interface should just be changed to an abstract class, so that all implementations get it.

**Comment by dakrone** [comment]
> Couldn't the logging be done at the consumer sites, so the implementation
> doesn't matter? Otherwise the interface should just be changed to an abstract
> class, so that all implementations get it.

It's not just logging though, we could add a stack-trace capturing wrapper that
captures the first 5 frames of the stack trace of when the breaker was
incremented, removing the capture when it is decremented with the same key (this
would require the keyed version Tim added). This would allow seeing where a leak
is coming from. It's not something we'd want all the time, since breaker
incrementing happens in performance-sensitive code, but something we still may
want to be able to use in production (rather than test-only).

The stack-trace capture idea is just an idea, not something that would have to
be implemented here

**Comment by rjernst** [comment]
> It's not something we'd want all the time, since breaker
incrementing happens in performance-sensitive code, but something we still may
want to be able to use in production (rather than test-only).

It's exactly because this is performance-sensitive code that I think we should not engineer in this advanced debugging capabilities for production code. Let's focus on randomized testing and debuggability there. It is just too late to find these things in production, and too error prone to have a bunch of extra code there that could *cause* performance issues with a misconfiguration or even a bug in the extra debugging code.

**Comment by jasontedor** [comment]
Here's how I feel about this. I chased down a circuit breaker leak that led to #23310. It was very difficult to chase down, I ultimately chased it down by adding circuit breaker stack trace capturing in a custom build of Elasticsearch and having it deployed to Cloud (where there was a reproducible leak). From there, the leak became obvious. That's where the genesis for this entire idea was born (that we should do this, roughly how we should do this, etc.). Yet, I still think that we should not do this! I think this is too much of a one time it was useful so let's make production code out of it thing, but maybe we will never need it again. If it happens a second time, maybe. A third, probably.

**Comment by tbrooks8** [comment]
The are multiple levels of work described in the issue, in other people's comments, and this PR.

Here is how I see it:

1. Modifications to our existing circuit breakers to ensure that on the completion of a test they are all back to 0. This is described by Ryan. It is not really in conflict with any of the work in this PR. But more generally is orthogonal to the question of whether circuit breakers should be more debuggable. 
2. A keyed version of circuit breakers. That work is in this PR. This work means that specific contexts (a big array, a request, etc) would need a key to request stuff from a breaker. This PR presents a version that is backwards compatible. Hence, only `BigArrays` use the key right now. The other usages still use the existing increment methods. This is useful because it allows the work to be implemented in multiple stages.
3. Specific tracing for keyed accesses. This PR implements capturing of stacktraces along with the deltas. This work requires the keyed version. It is currently implemented as inheritance with an abstract class. But it could be relegated to testing using delegation. In you want to eliminate the keyed access, there could be a test wrapper class that captures a buffer of stacktrace accesses. If there was a memory leak you would know the stacktraces, but you would not know which was the leak.
4. Settings to enabled the tracing in real production elasticsearch instances. This is included in this PR.
5. Ways to access the tracing data in real production elasticsearch instances. This is not implemented in this PR.

I think we all agree we want number 1 at the end of this issue. It also seems like most people do not want number 4 or 5. Which is fine with me, I mainly went with that approach because the issue seemed more "production debugging" oriented. I guess the main question that is necessary for me to advance this work is if we are interested in 2/3. @rjernst refers to `MockBigArrays` which does have some form of traceable access. If we want the access to be traceable some of the circuit breaker interface changes in this PR are probably necessary (I think).

**Comment by dakrone** [comment]
> 1. Modifications to our existing circuit breakers to ensure that on the completion of a test they are all back to 0. This is described by Ryan. It is not really in conflict with any of the work in this PR. But more generally is orthogonal to the question of whether circuit breakers should be more debuggable.

We already do this in `InternalTestCluster`, see: https://github.com/elastic/elasticsearch/blob/bf177952fa696331c4a4957ded59015a4a917858/test/framework/src/main/java/org/elasticsearch/test/InternalTestCluster.java#L2018-L2057

and https://github.com/elastic/elasticsearch/blob/bf177952fa696331c4a4957ded59015a4a917858/test/framework/src/main/java/org/elasticsearch/test/TestCluster.java#L91-L93

Perhaps the approach is what is debated since it seems to be a choice of either a wrapper or the way we currently check?

**Comment by s1monw** [comment]
> Perhaps the approach is what is debated since it seems to be a choice of either a wrapper or the way we currently check?

I wonder if we should first expand this stats based check to our real integration tests to get more coverage. I think we can / should do that from our test framework.

**Comment by dakrone** [comment]
> I wonder if we should first expand this stats based check to our real integration tests to get more coverage. I think we can / should do that from our test framework.

+1 to doing that check

**Comment by tbrooks8** [comment]
Closing as I think we are not interested in the bulk of this work.

**Pull request closed without merging**
