### PR TITLE
BACKPORT 7x Fix auditing of API Key authn without the owner realm name (#59470)

### LINKED ISSUE #59425: [CI] Auditing log fails for API key realm name during BWC with version prior to v7.5
The failed test `UpgradeClusterClientYamlTestSuiteIT.test {p0=mixed_cluster/120_api_key_auth/Test API key authentication will work in a mixed cluster}`.

ApiKey realm name is not available in Authentication metadata till [v7.5](https://github.com/elastic/elasticsearch/commit/7b6246ec670040e8e5dfef05b33bb2b39f8a9357). Hence auditing log fails to [retrieve it](https://github.com/elastic/elasticsearch/blob/7.x/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/audit/logfile/LoggingAuditTrail.java#L464) for older versions. 

The failed test has been configured to run only for v7.5 and up. Once this issue is fixed, it can be renabled for older versions by removing [these two lines](https://github.com/elastic/elasticsearch/blob/master/x-pack/qa/rolling-upgrade/src/test/resources/rest-api-spec/test/mixed_cluster/120_api_key_auth.yml#L6-L7).

Build scan: https://gradle-enterprise.elastic.co/s/zyiwyg5feg74a

### PR DESCRIPTION
**Pull request by albertzaharovits**
Backport of https://github.com/elastic/elasticsearch/pull/59470

The `Authentication` object that gets built following an API Key authentication
contains the realm name of the owner user that created the key (which is audited),
but the specific field used for storing it changed in #51305 .

This PR makes it so that auditing tolerates an "unfound" realm name, so it doesn't
throw an NPE, because the owner realm name is not found in the expected field.

Closes #59425

### CODE REVIEW

**Comment by albertzaharovits** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by albertzaharovits** [comment]
Stalled by https://github.com/elastic/elasticsearch/pull/59531 .
This PR also enables BWC tests that are now tripping on auditing of nameless API keys: https://gradle-enterprise.elastic.co/s/qsejyftepivog .

**Comment by ywangd** [comment]
> Stalled by #59531 .
> This PR also enables BWC tests that are now tripping on auditing of nameless API keys: https://gradle-enterprise.elastic.co/s/qsejyftepivog .

Aha, the API key name was also added to authentication metadata with my PR #51305. It is not available for v6.8. Thanks for fixing it.

**Comment by albertzaharovits** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample-windows

**Comment by albertzaharovits** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample-windows

**Comment by albertzaharovits** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample-windows

**Pull request merged**
