### PR TITLE
Logging: add the ability to specify an alternate logging configuration location

### LINKED ISSUE #2044: Feature request: Be able to specify logger.yml path
I'd like to be able to specify the `logger.yml` path when booting up elasticsearch, similar to the `-Des.config=<path>` option.

Use case: booting up a ES for testing purposes, want to be able to specify a custom logger.yml without having to edit the system-wide one.

### PR DESCRIPTION
**Pull request by javanna**
Replaces #7395 , which introduced support for a system property that allows to override the logging config location. This PR moves the logic to `Environment` from `LogConfigurator` and replaces `es.logging` with `path.logging`, which can be set from either sysprop (with `es.` prefix) or from the `elasticsearch.yml` config file. If `path.logging` is not set, behaviour is the same as before, it takes the same value as `path.config`.

Closes #2044

### CODE REVIEW

**Comment by javanna** [comment]
Suggestions are welcome about the new config parameter, especially naming. The original PR made it a sysprop only (ala `es.config`) but I thought it would be useful to expose it as a `path.logging` parameter.

Also not sure about security policies, I think we can't do much right now given that logging gets initialized before extending security policy, but can you double check @rmuir ? let me know if you have any suggestions!

**Comment by rmuir** [comment]
> Also not sure about security policies, I think we can't do much right now given that logging gets initialized before extending security policy, but can you double check @rmuir ? let me know if you have any suggestions!

I think based on your PR its fine, since logger config is currently "read once". We could be defensive too and just add a addPath line for it in Security.java and a test in SecurityTests, in case reconfiguration of logging is ever supported. 

My only reason for suggesting this paranoia is just that if we ever supported reconfiguration of logging in the future, then it would not always have correct permissions, and might be hard to track down since the default value inside config/ would probably be fine due its location.

**Comment by javanna** [comment]
@bleskes can you please review this?

**Comment by bleskes** [comment]
@javanna the change looks good to me (though this is no my area of expertise). My only concern is the name of the property. We already have `path.logs` which dictates where to put the logs. `path.logging` is confusing in that context. How about `path.config.logging` (if we want a future config path) or `path.logging_config_file`. Maybe even better is to have a `config.logging` property which is equivalent the general `config` properties (which maps to the es.yml file).

Also I think the suggestion made by @rmuir still need to be added?

**Comment by javanna** [comment]
Thanks for looking @bleskes . We already have `path.conf`, hence I went for `path.conf.logging`. Can you have another look? I also added the security permission, maybe @rmuir wants to have a look too.

**Comment by rmuir** [comment]
The logic all looks good to me, but i echo @bleskes concern about logs vs logging. `path.conf.logging` looks different than `path.logs` but that does not help the code itself (e.g. Environment.loggingFile vs Environment.logsFile). 

I feel this is certain to cause us bugs in the future. If someone asked me the difference between the two, i would not have a good answer for them. So I think we should try to adjust the naming.

**Comment by clintongormley** [comment]
Just been talking about this on FixItFriday - the original request #2044 wants to be able to choose between a test logging config and a production logging config.  This can already be done today by having two config directories: one for production and one for testing.

Of course, you still need to keep eg the elasticsearch.yml files in sync, but this proposed include functionality will help with that: https://github.com/elastic/elasticsearch/issues/11362

**Comment by rmuir** [comment]
We really need to be careful of overengineering around this stuff. I'm worried about where this is going. 

Elasticsearch already has *SO MUCH OVERENGINEERED CODE*, we are literally drowning under the pressure of it. 

I'm seriously worried about where this is going. I think now its the wrong direction. We need to keep it as simple as possible instead.

**Comment by s1monw** [comment]
I agree with robert here I think this is going in the wrong direction for little benefit.

**Comment by javanna** [comment]
> Of course, you still need to keep eg the elasticsearch.yml files in sync

That was what this PR (or better, the original one #7395) tries to avoid, allowing to specify only the `logging.yml` location by still using the same `elasticsearch.yml`. If people don't like it because we are adding yet another config option I can understand, then we can just close it.

**Comment by rmuir** [comment]
Mainly my issue is now we have alternative proposal #11362

Without a doubt, having both is silliness. So we should be looking at what is really needed and what is the simplest solution.

*Not* what is the most flexible solution
*Not* what is the most user friendly solution

But what keeps the codebase smallest and easiest to maintain.

Definitely having both this and #11362 is a huge no-go, we don't need so many ways to do the same thing.

This is the wrong place in our codebase to have unnecessary complexity. Configuration today is already crazy? no.... ABSOLUTELY FUCKING BONKERS with its reading of environment variables, sysprops, you name it.

Again my problem is not this PR in particular, and sorry @javanna for the comments ending up here, but they gotta go somewhere, we need to sort out what we want to do and not add lots of config options that then nobody will ever remove for back compat reasons.

**Comment by javanna** [comment]
Agreed, let's take a step back and decide how we want to move forward in general. Marking for discussion then.

**Comment by rjernst** [comment]
Regardless of whether #11362 is finished, I don't think this PR should happen. Right now, if you need different logging, but the same elasticsearch.yml, then use symlinks to a shared elasticsearch.yml within 2 different config dirs.

**Comment by clintongormley** [comment]
We've had a long discussion about this in our FixItFriday session.  Our feeling is that we're trying to remove complication from the code base.  Having one way to do things just makes it simpler to understand and debug.  So for now, we're going to close this PR.  We may revisit this in the future if there is popular demand and the change makes life easier for the majority of users.

thanks anyway

**Pull request closed without merging**
