### PR TITLE
Busily assert in testCreateSearchContextFailure

### LINKED ISSUE #64052: SearchServiceTests#testCreateSearchContextFailure
**Build scan**:

https://gradle-enterprise.elastic.co/s/mb4fxdioop3sk

**Repro line**:

```
./gradlew ':server:test' --tests "org.elasticsearch.search.SearchServiceTests" -Dtests.seed=3513A4B213D3E47A -Dtests.security.manager=true -Dtests.locale=ko -Dtests.timezone=Africa/Niamey -Druntime.java=11
```

**Reproduces locally?**:

No

**Applicable branches**:

master

**Failure history**:

I haven't found any other occurrence. 

**Failure excerpt**:

```
java.lang.AssertionError: should have 2 store refs (IndexService + InternalEngine) expected:<2> but was:<4>
        at __randomizedtesting.SeedInfo.seed([3513A4B213D3E47A:D9C6D58E7791BD50]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
```

### PR DESCRIPTION
**Pull request by dnhatn**
If the [background refresh](https://github.com/elastic/elasticsearch/blob/7feb19a74fe68e39538f16eeeb6ccfb4e54a7fde/server/src/main/java/org/elasticsearch/index/shard/IndexShard.java#L3201) is running, then the refCount assertion will fail as [Engine#refreshIsNeeded](https://github.com/elastic/elasticsearch/blob/7feb19a74fe68e39538f16eeeb6ccfb4e54a7fde/server/src/main/java/org/elasticsearch/index/engine/Engine.java#L971) can increase the refCount by 2.

Closes #64052

### CODE REVIEW

**Comment by dnhatn** [comment]
run elasticsearch-ci/default-distro

**Review by jimczi — APPROVED** [review]
LGTM, thanks @dnhatn

**Comment by dnhatn** [comment]
run elasticsearch-ci/default-distro

**Review by henningandersen — APPROVED** [review]
LGTM2

**Pull request merged**
