### PR TITLE
Move xpack template resources to an isolated module

### PR DESCRIPTION
**Pull request by rjernst**
Xpack core contains dozens of templates. These files are loaded via a shared template utils method. While they should ideally be moved to their appropriate modules, that would be large undertaking. This commit moves these resources to a single module for xpack core (which may be overriden by serverless).

### CODE REVIEW

**Comment by rjernst** [comment]
@ChrisHegarty This is as we discussed. There is an issue though with the new module and IntelliJ that I'm hoping you could look at. For some reason IntelliJ thinks the TemplateResources class is in the unnamed module. If you open TemplateUtils you will see IntelliJ complaining about the import, but Elasticsearch runs fine (gradle can find the module and ./gradlew run works).

IntelliJ import screenshot

**Comment by rjernst** [comment]
Seems like the intellij issue could be this:
https://youtrack.jetbrains.com/issue/IDEA-291860/Package-xxx-is-declared-in-the-unnamed-module-but-module-yyy-does-not-read-it

**Comment by ChrisHegarty** [comment]
> @ChrisHegarty This is as we discussed. There is an issue though with the new module and IntelliJ that I'm hoping you could look at. For some reason IntelliJ thinks the TemplateResources class is in the unnamed module. If you open TemplateUtils you will see IntelliJ complaining about the import, but Elasticsearch runs fine (gradle can find the module and ./gradlew run works).
> 
> IntelliJ import screenshot

I checked out the branch and loaded it into my IDE (2023.1.2). The module worked without any issues - navigation, usage, etc all fine - not red squiggly lines.

**Comment by ChrisHegarty** [comment]
The changes look good to me.

Just a trailing note to check the `processResources` task in `x-pack/plugin/core/build.gradle`, since there will be no resources directory left in the core Gradle module after this change. It seems unrelated, but I dunno.

**Review by ChrisHegarty — APPROVED** [review]

**Review by klacabane — APPROVED** [review]
Infra Monitoring UI changes LGTM

**Comment by rjernst** [comment]
> Just a trailing note to check the processResources task in x-pack/plugin/core/build.gradle, since there will be no resources directory left in the core Gradle module after this change.

The processResources task handles selecting the public key embedded in xpack, which licensing uses. The existence of the resources *src* directory is not important to this task.

**Pull request merged**
