### PR TITLE
SQL: Fix RLIKE bug and improve testing for RLIKE statement

### LINKED ISSUE #34609: SQL: add tests for RLIKE
At the moment, there are no tests for RLIKE. Testing quickly few things, seems to work, but would be good to have tests to ensure nothing breaks in the meantime.

### PR DESCRIPTION
**Pull request by astefan**
This PR mainly fixes a bug similar with https://github.com/elastic/elasticsearch/issues/39931 (but for RLIKE statement) by slightly refactoring RegexMatch/Like/RLike classes and adds integration tests for RLIKE.

Fixes https://github.com/elastic/elasticsearch/issues/34609.

### CODE REVIEW

**Comment by astefan** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample

**Comment by astefan** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample

**Review by matriv — APPROVED** [review]
LGTM

**Comment by astefan** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample

**Review by matriv — APPROVED** [review]
LGTM

**Review by costin — APPROVED** [review]
LGTM

**Pull request merged**
