### PR TITLE
[bug] fuzziness custom auto

### PR DESCRIPTION
**Pull request by MuffinUser**
in the toXContent Method, the fuzziness is now with custom LOW and High values
https://github.com/elastic/elasticsearch/issues/33454

### CODE REVIEW

**Comment by elasticcla** [comment]
Hi @MuffinUser, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/elasticsearch/pull/33462.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by cbuescher** [comment]
@MuffinUser thanks for opening this PR for the issue you reported in #33462. I was also looking at the state that we currently implement the custom values for the auto-fuzziness and I am not completely sure we shouldn't consider making some general changes here rather than parsing some custom syntax like we currently do. In any Outputting the string representation like suggested here would certainly work for the case you described in the issue, but I'll have to take a better look if that wouldn't tie us to support some custom syntax that we are not happy with on the long run. In any case, I would ask you to add some unit tests to FuzzinessTests that we get can parse back any custom Fuzziness object we output with `toXContent` using`fromXContent`. So basically a round-trip test that creates a randomized Auto-Fuzziness, writes it out to XContent, parses is back and then checks that the limits are the same. There is already some code in FuzzinessTests#testParseFromXContent that does something slightly similar, maybe that can be extended, but I think I'd prefer a separate test method.

**Review by cbuescher — CHANGES_REQUESTED** [review]
@MuffinUser thanks for opening this PR for the issue you reported in #33462. I was also looking at the state that we currently implement the custom values for the auto-fuzziness and I am not completely sure we shouldn't consider making some general changes here rather than parsing some custom syntax like we currently do. In any Outputting the string representation like suggested here would certainly work for the case you described in the issue, but I'll have to take a better look if that wouldn't tie us to support some custom syntax that we are not happy with on the long run. In any case, I would ask you to add some unit tests to FuzzinessTests that we get can parse back any custom Fuzziness object we output with toXContent usingfromXContent. So basically a round-trip test that creates a randomized Auto-Fuzziness, writes it out to XContent, parses is back and then checks that the limits are the same. There is already some code in FuzzinessTests#testParseFromXContent that does something slightly similar, maybe that can be extended, but I think I'd prefer a separate test method.

**Comment by javanna** [comment]
Also, @MuffinUser is you want us to move forward with this we'd need you to fix the CLA problem like we have explained above. Thanks!

**Comment by MuffinUser** [comment]
Hey @javanna, I am planning on adding tests as discribed by @cbuescher. But I do not Intend to change the fuzziness Representation as @cbuescher demanded. In this Issue the Bug should be Fixed.

Although I think the Fuzziness Respresentation should be revised, but in a diffrent place. But I intend to particitpate in that.

**Comment by cbuescher** [comment]
@MuffinUser just checking in if you can update this PR with some tests and sign the CLA, then I can continue reviewing it.

**Comment by cbuescher** [comment]
@MuffinUser sorry, I will close this PR since it is missing tests and a signed CLA. The issue is still open and will be adressed as soon as possible. Please reopen if you feel like you want to still work on this.

**Pull request closed without merging**
