### PR TITLE
Skip noop normalizing

### PR DESCRIPTION
**Pull request by nik9000**
It looks like we'd intended to skip noop normalizing to save on building
a bunch of lucene components that ultimately just return the same
string. But we didn't really test it and, sadly, we made the wrong null
check. This fixes the check.

### CODE REVIEW

**Comment by nik9000** [comment]
Well darn - I'm not sure of a real way to write a test for this.....

**Comment by nik9000** [comment]
I don't know a good way to test this. If anyone has any ideas I'm all ears. If we think that this skip isn't worth doing then I think we should remove the null checks currently around the normalizer - its never null and that is confusing.

**Review by romseygeek — APPROVED** [review]
Oh good catch.

**Comment by nik9000** [comment]
@elasticmachine, update branch

**Comment by nik9000** [comment]
@elasticmachine update branch

**Pull request merged**
