### PR TITLE
Increase maximum forecast interval to 10 years.

### LINKED ISSUE #41103: [ML] Extend ML Forecast beyond 8 weeks in the REST API
Borrowed from @boutcher:

"
Describe the feature:

Would like to be able to use the ML Forecast feature to forecast beyond 8 weeks. We understand that confidence in the predictions will be impacted as you move further into the future, but we have some data sets that have many years of historical data points that we believe could yield acceptable results without bumper guards at 8w.

Describe a specific use case for the feature:

We have ~10 years of daily event volume, and would like to do a forecast out 1-2 years to see what the model predicts. We understand that the accuracy isn't golden as you move further into the future.
"

### PR DESCRIPTION
**Pull request by przemekwitek**
Increase maximum forecast interval from 8 weeks (56 days) to ~10 years (3650 days).
Add a YML test for the validation being modified.

Closes #41103

### CODE REVIEW

**Comment by przemekwitek** [comment]
Closes #41103

**Review by droberts195 — APPROVED** [review]
LGTM

**Review by hendrikmuhs — APPROVED** [review]
LGTM technically, we should ensure the kibana change lands on the same version if this goes in

**Comment by droberts195** [comment]
> we should ensure the kibana change lands on the same version if this goes in

That's a nice-to-have, but not critical.  We can build up the layers as time goes by.

**Pull request merged**
