### PR TITLE
Use more precise does S3 bucket exist method

### PR DESCRIPTION
**Pull request by jasontedor**
We are using a deprecated method for checking if an S3 bucket exists. This deprecated method has a limitation that it can not distinguish between invalid credentials and a lack of permissions. This commit switches to using a method that correctly surfaces if invalid credentials are supplied when checking for the existence of a bucket.

### CODE REVIEW

**Review by tlrx — APPROVED** [review]

**Review by ywelsch — CHANGES_REQUESTED** [review]
I don't think that we can or that we should be doing this change: `doesBucketExist()` is implemented as a [`HEAD bucket` request](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketHEAD.html) while `doesBucketExistV2()` is implemented as [`GET bucket acl` request](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGETacl.html), which requires different bucket permissions than [what we've been recommending](https://www.elastic.co/guide/en/elasticsearch/plugins/current/repository-s3-repository.html#repository-s3-permissions). The reason why `doesBucketExistV2()` got introduced can be [found here](https://github.com/aws/aws-sdk-java/issues/1256). I'm not sure if this is the method that we actually want to check. We are less interested in knowing whether the bucket exists (but we might not be able to access it), but rather interested whether it exists and we can access it. The request to check this is just the plain old `headBucket` request. If you want to improve this code section, I therefore recommend changing it to a plain `clientReference.client().headBucket(new HeadBucketRequest(bucket))`, then catch the `AmazonServiceException` and wrap it with an exception saying something along the lines of `bucket does not exist or cannot be accessed`, and the more detailed cause will then be provided by the `AmazonServiceException`.

**Comment by jasontedor** [comment]
That is a shame, as the [Javadocs](https://github.com/aws/aws-sdk-java/blob/1.11.406/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3.java#L1054) here indicate that `AmazonS3#doesBucketExist` is deprecated by `AmazonS3#doesBucketExistV2`. This was something I noticed while working on #33793. Thanks for digging the extra level @ywelsch.

**Comment by tlrx** [comment]
Two important things:
- it would have been caught by our third party tests on CI 
- _Magic Yannick_ strikes again, thanks a lot.

**Comment by jasontedor** [comment]
@ywelsch I pushed.

**Review by ywelsch — APPROVED** [review]
LGTM

**Pull request merged**
