### PR TITLE
Move CAS deprecation to TransportShardBulkAction

### LINKED ISSUE #42796: [CI] Deprecation warnings cause failures for 2 tests in MixedClusterClientYamlTestSuiteIT in 6.8
Build link: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.8+bwc-tests/112/console

Two tests failed:

Reproduce 1:

```
./gradlew :qa:mixed-cluster:v5.6.0#mixedClusterTestRunner -Dtests.seed=50C77143AD9C6ABC -Dtests.class=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT -Dtests.method="test {p0=update/11_shard_header/Update check shard header}" -Dtests.security.manager=true -Dtests.locale=es-CL -Dtests.timezone=Asia/Atyrau -Dcompiler.java=12 -Druntime.java=8
```

Failure 1:

```
FAILURE 0.30s | MixedClusterClientYamlTestSuiteIT.test {p0=update/11_shard_header/Update check shard header} <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: Failure at [update/11_shard_header:23]: got unexpected warning header [
   > 	299 Elasticsearch-6.8.1-SNAPSHOT-8c087df "Usage of internal versioning for optimistic concurrency control is deprecated and will be removed. Please use the `if_seq_no` and `if_primary_term` parameters instead. (request for index [foobar], type [baz], id [1])"
   > ]
   > 	at __randomizedtesting.SeedInfo.seed([50C77143AD9C6ABC:D8934E9903600744]:0)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:412)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:389)
   > 	at java.lang.Thread.run(Thread.java:748)
   > Caused by: java.lang.AssertionError: got unexpected warning header [
   > 	299 Elasticsearch-6.8.1-SNAPSHOT-8c087df "Usage of internal versioning for optimistic concurrency control is deprecated and will be removed. Please use the `if_seq_no` and `if_primary_term` parameters instead. (request for index [foobar], type [baz], id [1])"
   > ]
   > 	at org.elasticsearch.test.rest.yaml.section.DoSection.checkWarningHeaders(DoSection.java:330)
   > 	at org.elasticsearch.test.rest.yaml.section.DoSection.execute(DoSection.java:258)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:405)
   > 	... 37 more
```

Reproduce 2:

```
REPRODUCE WITH: ./gradlew :qa:mixed-cluster:v5.6.0#mixedClusterTestRunner -Dtests.seed=50C77143AD9C6ABC -Dtests.class=org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT -Dtests.method="test {p0=update/60_refresh/refresh=wait_for waits until changes are visible in search}" -Dtests.security.manager=true -Dtests.locale=es-CL -Dtests.timezone=Asia/Atyrau -Dcompiler.java=12 -Druntime.java=8
```

Failure 2:

```
FAILURE 1.16s | MixedClusterClientYamlTestSuiteIT.test {p0=update/60_refresh/refresh=wait_for waits until changes are visible in search} <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: Failure at [update/60_refresh:99]: got unexpected warning header [
   > 	299 Elasticsearch-6.8.1-SNAPSHOT-8c087df "Usage of internal versioning for optimistic concurrency control is deprecated and will be removed. Please use the `if_seq_no` and `if_primary_term` parameters instead. (request for index [update_60_refresh_1], type [test], id [update_60_refresh_id1])"
   > ]
   > 	at __randomizedtesting.SeedInfo.seed([50C77143AD9C6ABC:D8934E9903600744]:0)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:412)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:389)
   > 	at java.lang.Thread.run(Thread.java:748)
   > Caused by: java.lang.AssertionError: got unexpected warning header [
   > 	299 Elasticsearch-6.8.1-SNAPSHOT-8c087df "Usage of internal versioning for optimistic concurrency control is deprecated and will be removed. Please use the `if_seq_no` and `if_primary_term` parameters instead. (request for index [update_60_refresh_1], type [test], id [update_60_refresh_id1])"
   > ]
   > 	at org.elasticsearch.test.rest.yaml.section.DoSection.checkWarningHeaders(DoSection.java:330)
   > 	at org.elasticsearch.test.rest.yaml.section.DoSection.execute(DoSection.java:258)
   > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:405)
   > 	... 37 more
```

I could not reproduce the first but I do reproduce the second reliably on my machine.

### PR DESCRIPTION
**Pull request by dnhatn**
If the primary on 6.6+ but replicas on older versions, we can not use CAS using ifSeqNo since it requires all nodes on 6.6+. In this case, we have to fall back to use CAS with _version and should not issue a deprecation warning log during validation. This change moves the CAS deprecation to TransportShardBulkAction and only issues deprecation when the cluster is ready for ifSeqNo.

Closes #42796
Relates #42596

### CODE REVIEW

**Comment by dnhatn** [comment]
CI instance: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.8+bwc-tests/89/console

**Comment by dnhatn** [comment]
@ywelsch This is ready. Please have a look. Thank you!

**Comment by dnhatn** [comment]
This change is not water tight. An update request can still fail if the primary shard which resolves the update request gets relocated before it executes the request while replicas are still on old nodes.

**Comment by ywelsch** [comment]
> This change is not water tight. An update request can still fail if the primary shard which resolves the update request gets relocated before it executes the request while replicas are still on old nodes.

only in case of a single update request (TransportUpdateAction), not an update that's done as part of the bulk APIs (TransportShardBulkAction), right?

**Comment by ywelsch** [comment]
How about moving the deprecation logging that's currently done by `DocWriteRequest.logDeprecationWarnings` to `TransportShardBulkAction` and then only do it if all nodes are on 6.6+?

**Comment by dnhatn** [comment]
> How about moving the deprecation logging that's currently done by DocWriteRequest.logDeprecationWarnings to TransportShardBulkAction and then only do it if all nodes are on 6.6+?

Yes, it would be a good option.

**Comment by dnhatn** [comment]
> How about moving the deprecation logging that's currently done by DocWriteRequest.logDeprecationWarnings to TransportShardBulkAction and then only do it if all nodes are on 6.6+?

I made changes for this. However, there is still a case where we issue an unwanted deprecation warning for a single update request. If the cluster has an old node when TransportUpdateAction processes the request but that old node left when TransportShardBulkAction executes it. 

How about moving this deprecation to the rest layer?

**Comment by ywelsch** [comment]
> I made changes for this. However, there is still a case where we issue an unwanted deprecation warning for a single update request.

I think that's fine, this should be sufficient for our REST tests. It does not need to be perfect, but has to pass our tests.

> How about moving this deprecation to the rest layer?

This means that requests from the transport client won't be logged, and also internal requests which mistakenly might use versioning would not be logged either. I prefer the previously proposed solution.

**Comment by dnhatn** [comment]
@ywelsch This is ready again. Can you please take a look? Thank you!

**Review by ywelsch — APPROVED** [review]
LGTM

**Comment by dnhatn** [comment]
@elasticmachine test this please

**Comment by dnhatn** [comment]
@ywelsch Thanks for reviewing!

**Pull request merged**
