### PR TITLE
Distinguish `LicensedFeature` by family field

### PR DESCRIPTION
**Pull request by n1v0lg**
This PR fixes unintentional licensed feature overlaps for features with the same name but different family fields.

### CODE REVIEW

**Comment by n1v0lg** [comment]
@elasticmachine update branch

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by n1v0lg** [comment]
@elasticmachine update branch

**Comment by n1v0lg** [comment]
@elasticmachine update branch

**Comment by n1v0lg** [comment]
@elasticmachine update branch

**Pull request merged**
