### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by justincr-elastic**
Manual steps to setup ECF in the Formatting section did not work for me.

Added a set of alternative steps which allowed me to import build-conventions/formatterConfig.xml into IntelliJ 2021.2.3 Ultimate on Windows.

### CODE REVIEW

**Review by mark-vieira — COMMENTED** [review]
:+1:

**Review by mark-vieira — APPROVED** [review]

**Comment by jkakavas** [comment]
@justincr-elastic can we merge this ?

**Comment by justincr-elastic** [comment]
@elasticmachine update branch

**Comment by justincr-elastic** [comment]
@elasticmachine update branch

**Comment by justincr-elastic** [comment]
Ignoring false positive warning "Check labels - Missing [:Team]". There is a Team label, so merging this PR.

**Pull request merged**
