### PR TITLE
ESQL: Replace AssertionErrors in mappers

### PR DESCRIPTION
**Pull request by alex-spies**
Re-opening #98538 against `main`, now that `feature/esql` was merged and the initial PR was auto-closed.

We want to avoid throwing errors; AssertionErrors are thrown in some ESQL expression mappers whenever an operation is not supported for whatever reason, like unsupported data types. This can bring down the whole server instead of the correct behavior of just returning a 500 response.

* Add `EsqlUnsupportedOperationException`.
* Add helper methods in case of unsupported/illegal data types.
* Replace `AssertionErrors` by `EsqlIllegalArgumentException` or `EsqlUnsupportedOperationException`.
* Also replace usages of `UnsupportedOperationException` by `EsqlUnsupportedOperationException` (or `EsqlIllegalArgumentException` where appropriate) throughout the `esql` package (except tests and the `compute` subpackage).

### CODE REVIEW

**Comment by alex-spies** [comment]
@elasticsearchmachine run elasticsearch-ci/part-2

**Comment by alex-spies** [comment]
@elasticsearchmachine run elasticsearch-ci/bwc

**Review by bpintea — APPROVED** [review]
It LGTM, but wondering if having an `EsqlUnsupportedOperationException` wouldn't be more appropriate for some of these cases. I'm thinking of unsupported methods (`asScript()`, `replaceChildren()` and some others), wrapping other exceptions, but potentially some other cases too, like "end of method reached and no appropriate operation found".

**Review by costin — APPROVED** [review]
LGTM

**Comment by alex-spies** [comment]
> It LGTM, but wondering if having an `EsqlUnsupportedOperationException` wouldn't be more appropriate for some of these cases. I'm thinking of unsupported methods (`asScript()`, `replaceChildren()` and some others), wrapping other exceptions, but potentially some other cases too, like "end of method reached and no appropriate operation found".

I agree, unsupported operations are now conflated with things like illegal data types.

I'll give this a final do-over, introducing `EsqlUnsupportedOperationException` and refactoring a bit before merging this.

**Comment by alex-spies** [comment]
@bpintea , added `EsqlUnsupportedOperationException` + some convenience methods and aligned the exception types as well as I could with the application logic. (Many places where exceptions are thrown are in-between an illegal argument or unsupported operation.)

If you want to give it another look, I'd be very happy; otherwise this is probably good to go and I'd like to merge this some time tomorrow.

**Comment by alex-spies** [comment]
@elasticsearchmachine run elasticsearch-ci/packaging-tests-unix-sample

**Review by ChrisHegarty — APPROVED** [review]
LGTM

**Pull request merged**
