### PR TITLE
Remove oss handling in docker distribution project

### PR DESCRIPTION
**Pull request by breskeby**
Follow up on #69775
Related to #68797

### CODE REVIEW

**Comment by pugnascotia** [comment]
There's still some OSS references in `distribution/docker/build.gradle` that you could also remove, since they're related to the removed file.

**Comment by breskeby** [comment]
@pugnascotia did some further cleanup here

**Comment by breskeby** [comment]
@pugnascotia can we also get rid of the oss images in the docker compose?

**Comment by pugnascotia** [comment]
> @pugnascotia can we also get rid of the oss images in the docker compose?

Definitely, the oss container definitions have apparently been broken for a long time because they're not even using the oss images 🤷‍♂️

**Comment by breskeby** [comment]
@elasticmachine test this please

**Comment by breskeby** [comment]
@elasticmachine test this please

**Comment by breskeby** [comment]
@elasticmachine run elasticsearch-ci/packaging-unix

**Pull request merged**
