### PR TITLE
Goodbye and thank you synced flush!

### PR DESCRIPTION
**Pull request by dnhatn**
Synced flush was a brilliant idea. It supports instant recoveries with a quite small implementation. However, with the presence of sequence numbers and retention leases, it is no longer needed. This change removes it from 8.0.

Depends on #50835
Relates #50776

### CODE REVIEW

**Comment by dnhatn** [comment]
@elastic/es-clients FYI, we are working to remove synced flush on 8.0

**Comment by cjcenizal** [comment]
@dnhatn What will the effect of this change be upon ES's APIs? Just checking to see if we will need to plan for any changes on the Kibana side.

**Comment by dnhatn** [comment]
@cjcenizal Are we using the synced flush on Kibana? We should replace it with a [normal flush](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-flush.html) on 7.6 or later as they have the same effect.

**Comment by cjcenizal** [comment]
@dnhatn I believe Index Management uses a regular flush. Thanks!

@jloleysens FYI it looks like the [{index}/_flush/synced](https://www.elastic.co/guide/en/elasticsearch/reference/7.5/indices-synced-flush-api.html)  autocomplete definition is automatically generated. However, we'll need to be careful not to backport that change to 7.x since this is a breaking change targeted for 8.0 only.

**Comment by dnhatn** [comment]
> INFO:build_docs:Bad cross-document links:
> INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/elasticsearch/client/javascript-api/master/api-reference.html:
> INFO:build_docs:   - en/elasticsearch/reference/master/indices-synced-flush-api.html

The doc build fails because the javascript client still refers to the synced flush api.

**Comment by cjcenizal** [comment]
BTW I just got the title of this PR and I ❤️ it!

**Comment by philkra** [comment]
pinging @delvedor , please see https://github.com/elastic/elasticsearch/pull/50882#issuecomment-573273447

**Review by delvedor — COMMENTED** [review]
Hello! I've removed the offending lines in https://github.com/elastic/elasticsearch-js/commit/fc5156dbff6df103d4c668a8222899663671b8f7, let me know if I can do something more!

**Comment by dnhatn** [comment]
run elasticsearch-ci/docs

**Comment by dnhatn** [comment]
It's good now. Thanks @delvedor and @philkra :).

**Comment by dnhatn** [comment]
@ywelsch Thank you for reviewing. It's ready for another round. I have made these changes:

1. Reverted the engine part. I will make a separate PR for it.

2. If a synced flush hits a coordinating node on 7.x and the target shards are on 8.x, that request will fail without a clear reason. Perhaps it's okay to remove this transition entirely? I've made the transition smoother https://github.com/elastic/elasticsearch/pull/50882/files#diff-eaa7db6ff53e33de863f8bd1dfc5467dR58 and a test https://github.com/elastic/elasticsearch/pull/50882/files#diff-205fa41307cd5a7b21ecca1185715ba5R281

3. Restore synced-flush code in upgrade tests.

**Review by ywelsch — APPROVED** [review]
LGTM

> If a synced flush hits a coordinating node on 7.x and the target shards are on 8.x, that request will fail without a clear reason. Perhaps it's okay to remove this transition entirely? I've made the transition smoother

I think we could go without that. The overhead is pretty slim though, so I'm fine keeping it in. It helps the user in an upgrade situation, which is typically already stressful.

**Comment by dnhatn** [comment]
Thanks Yannick!

**Pull request merged**
