### PR TITLE
Add a feature spec that adds test features to the cluster features

### PR DESCRIPTION
**Pull request by thecoop**
Enable test features to be declared that are only added when a test plugin is added to the cluster

### CODE REVIEW

**Comment by thecoop** [comment]
@ldematte how much does this obsolete our existing infrastructure around test historical features? It seems like its not actually used...

**Comment by ldematte** [comment]
I had to navigate the code a little, lots has changed. Probably you want to ask @mosche too, but here it's what I remember.
We do not have "real" cluster features in tests (I think we actually forbid their usage atm - we throw); we have lots of historical cluster features, used both in tests and inside test framework classes (e.g. `ESRestTestCase` and inheritors).
They are defined in `RestTestLegacyFeatures`. These historical features should eventually "dry out"; it seems we were actually quite good on this area, nothing past V_8_11_0 was added.

The other part that we have is to have features (also historical) loaded from plugins - build task load them, dumps them to json, we load them in `ESRestTestCase` to expose them to rest tests.
I don't know how much these are used; given the resistance to use cluster features for testing and the preference to use synthetic features instead, I would say these might have been totally ignored?

**Review by ldematte — COMMENTED** [review]
A couple of questions:
- the new plugin will be distributed with ES; how can we make sure it is not installed/loaded by default, but just when we are running tests?
- how do we install/load this plugin in the various cases? 
  - For internal cluster tests we would have to specify it in the nodePlugins (can we do this automatically? should we?). 
  - For the BwC/ tests that use a distribution? And what if the plugin is not present? (I think we assume this is an older version and the features are not present?)

**Comment by mosche** [comment]
> how much does this obsolete our existing infrastructure around test historical features? It seems like its not actually used...

I've previously raised (in our sync) if we want to keep historical features. I don't think they are used beyond our team (during the transition). And there's a check to prevent the addition of historical features for more recent ES versions. It's some legacy we're just carrying forward at the moment.

> the new plugin will be distributed with ES; how can we make sure it is not installed/loaded by default, but just when we are running tests?

I agree, this is something we'll have to be very careful about and protect against. If accidentally enabled once, it can't be removed from the cluster anymore :/ It's rather unfortunate that we have to distribute the plugin with the release this way (unless massively increasing the scope of this).

An alternative might be do this entirely in the test infrastructure, a bit similar to historical features but semi-automated. For instance, imagine a long text file where devs would append their test features on top. During the release process we'll simply append a release marker to that file. For bwc tests, the orchestration code runs on main so we know about all versions that way.

**Comment by thecoop** [comment]
> I agree, this is something we'll have to be very careful about and protect against. If accidentally enabled once, it can't be removed from the cluster anymore :/ It's rather unfortunate that we have to distribute the plugin with the release this way (unlesss massively increasing the scope of this).

Yes, it's not great. I can add logger warnings to say this should only be used in test clusters (run from ES tests), or also check for other test-associated settings being set to be more certain it's running in a test context.

**Comment by thecoop** [comment]
@mark-vieira Looks like the test-features module still isn't accessible from quite a few othe r modules...

**Comment by mark-vieira** [comment]
> @mark-vieira Looks like the test-features module still isn't accessible from quite a few other modules...

I pushed a fix for this.

**Comment by thecoop** [comment]
This has been done using #113108 instead

**Pull request closed without merging**
