### PR TITLE
Shrink API should ignore templates

### PR DESCRIPTION
**Pull request by fred84**
@jasontedor fix only for #25035

### CODE REVIEW

**Comment by rjernst** [comment]
I don't know enough about this to properly review, but I think there should be a unit test, not a rest test. /cc @jasontedor 

@elasticmachine ok to test

**Comment by fred84** [comment]
@rjernst Unit test requires converting anonymous class to inner class. @jasontedor recommended to fix bug first and then make this code unit testable. You can view initial PR with unit test in #25373

**Comment by jasontedor** [comment]
Thanks @fred84, I'll review this next week.

**Comment by jasontedor** [comment]
test this please

**Comment by jasontedor** [comment]
retest this please

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by jasontedor** [comment]
Thank you @fred84!

**Comment by clintongormley** [comment]
@jasontedor This should be backported to 5.6, no?

**Comment by jasontedor** [comment]
@clintongormley I backported this in 4df868f4b7861bda954654a252b45a3ff42b1b8a.

**Comment by DennisDyallo** [comment]
So, is there a workaround for 5.3?

**Comment by jasontedor** [comment]
You could remove the offending template, execute the shrink, and then put the template back.

**Pull request merged**
