### PR TITLE
Update the MrjarPlugin test task to depend upon the jar

### PR DESCRIPTION
**Pull request by ChrisHegarty**
This commit updates the MrjarPlugin so that test tasks depend upon the jar. Tests need the jar since it contains the versioned sections, and the java launcher requires this to load classes from such.

After this change tests in the same project as the source can run successfully.

relates #104883

### CODE REVIEW

**Comment by ChrisHegarty** [comment]
I have no test for this change, but have verified it in a local branch where I'm using the mister jar plugin.

**Comment by ChrisHegarty** [comment]
@elasticmachine update branch

**Review by rjernst — APPROVED** [review]
LGTM but Mark or Rene should verify the gradle magic.

**Review by mark-vieira — CHANGES_REQUESTED** [review]
I think the preferable thing to do would just be to add the output of the additional source set to the test task classpath. This avoids having to unnecessarily bundle a jar when we can just use the classes directory instead. In fact, `GradleUtils.extendSourceSet()` does exactly this if you simply pass it a task provider for the test task. We can make this a one line change by just passing `project.getTasks().withType(Test.class).named(JavaPlugin.TEST_TASK_NAME)` to that call on line 77.

**Comment by ChrisHegarty** [comment]
@mark-vieira

While that may work, adding to the class path, it means that the test can only exercise a single version specific source. If we ever extend this to `main21`, `main22`, etc there will be mayhem on the class path. The "real" mrjar will allow for this.

I made the suggested change, but it fails with :

```
The automatic loading of test framework implementation dependencies has been deprecated. This is scheduled to be removed in Gradle 9.0. Declare the desired test framework directly on the test suite or explicitly declare the test framework implementation dependencies on the test's runtime classpath. Consult the upgrading guide for further information: https://docs.gradle.org/8.5/userguide/upgrading_version_8.html#test_framework_implementation_dependencies
No test executed. This behavior has been deprecated. This will fail with an error in Gradle 9.0. There are test sources present but no test was executed. Please check your test configuration. Consult the upgrading guide for further information: https://docs.gradle.org/8.5/userguide/upgrading_version_8.html#test_task_fail_on_no_test_executed
```

**Comment by mark-vieira** [comment]
> With the MR jar we most likely have the same class (package and name).

Ah, right, this makes sense. Yes, in this case testing against the MR jar makes sense as then all the magic runtime-dependent classloading will be taken care of for us.

**Review by mark-vieira — APPROVED** [review]

**Comment by ChrisHegarty** [comment]
@elasticmachine update branch

**Pull request merged**
