### PR TITLE
Remove obsolete version check for system index migrations

### PR DESCRIPTION
**Pull request by thecoop**
7.16 is no longer a valid version to connect to for 8.x

### CODE REVIEW

**Comment by thecoop** [comment]
@elasticsearchmachine test this please

**Comment by thecoop** [comment]
@elasticmachine update branch

**Review by ldematte — APPROVED** [review]
LGTM but I have one small Q:
It is safe to remove this because upgrade to 8.x is now allowed only from 7.16 or after? And this is checked/enforced somewhere else in the code?

**Comment by thecoop** [comment]
Only 7.17 can connect to 8.x, to perform rolling upgrades. This is enforced by `Version.minimumCompatibleVersion()`

**Pull request merged**
