### PR TITLE
Deprecate types in get, exists, and multi get.

### PR DESCRIPTION
**Pull request by jtibshirani**
For each API, the following updates were made:
- Add deprecation warnings to `Rest*Action`, plus tests in `Rest*ActionTests`.
- For each REST yml test, make sure there is one version without types, and another legacy version that retains types (called *_with_types.yml).
- Deprecate relevant methods on the Java HLRC requests/ responses.
- Update documentation (for both the REST API and Java HLRC).

### CODE REVIEW

**Review by jpountz — APPROVED** [review]

**Comment by jpountz** [comment]
Can you add a description to the pull request here as well?

**Comment by jtibshirani** [comment]
@elasticmachine run gradle build tests 2

**Comment by jtibshirani** [comment]
@elasticmachine test this please

**Comment by jtibshirani** [comment]
@elasticmachine test this please

**Comment by jtibshirani** [comment]
@elasticmachine test this please

**Comment by jtibshirani** [comment]
I force-pushed because this PR was getting a bit messy, but it contains the same changes from when it was first reviewed, plus several fixes in integration tests to replace custom types with `_doc`.

**Pull request merged**
