### PR TITLE
[Transforms] remove direct reference to SearchResponse in integration tests

### PR DESCRIPTION
**Pull request by benwtrent**
Removes direct reference to SearchResponse in transforms. This was the only one I could find that was generated from a client call.

All the other ones are created directly or mocks.

In general Transforms does a ton of work while holding a reference to SearchResponse. We will need to make sure it correct decRefs.

related to: https://github.com/elastic/elasticsearch/issues/102030

### CODE REVIEW

**Comment by benwtrent** [comment]
run elasticsearch-ci/part-2

**Review by droberts195 — APPROVED** [review]
LGTM

**Review by przemekwitek — APPROVED** [review]
LGTM

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Pull request merged**
