### PR TITLE
Deprecate geo_point mapping params

### PR DESCRIPTION
**Pull request by nknize**
Adds deprecation logging to geo_point validate and normalize parameters per #16910

### CODE REVIEW

**Comment by rjernst** [comment]
LGTM

**Comment by hadoopmonica** [comment]
I used to use geopoint field in elasticsearch 1.7 to 2.2, but when I upgrade to elasticsearch 2.3.1, geopoint type is not recognized. I posted the issue in elastic.co, please take a look.
https://discuss.elastic.co/t/geopoint-type-field-in-template-is-not-recognized-after-upgrading-to-elasticsearch-2-3-1/48686

**Comment by mohitsikri** [comment]
Couldn't find a reason for deprecating mapping options got geoPoint, specifically : "normalize" and "validate". Any pointers explaining it would be helpful. How would ES handle co-terminal angles for lat/long now? Thanks for quick help.

**Comment by mohitsikri** [comment]
On 2.3.1 , "ignore_malformed" : true allows to store out of range geo point data(say for ex : 
  "location" : {
            "lat" : 23.23061994988693,
            "lon" : 437.3666667938232 // coterminal angle
        }
, but it returns the same result back (upon _search) , when do normalization kicks in i.e. when doc is stored or searched? Also I expected a result of bounding box query but found empty.
{
    "query": {
        "bool" : {
            "must" : {
                "match_all" : {}
            },
            "filter" : {
                "geo_bounding_box" : {
                    "pin.location" : {
                        "top_left" : [77.36005783081049, 23.227859403521386],
                        "bottom_right" : [77.37276077270508, 23.23440574921077]
                    }
                }
            }
        }
    }
}

**Comment by nknize** [comment]
Two separate topics:

1. Normalization happens at index time. The query results displayed (from `_search`) are the same as what is provided in source; normalization doesn't change the incoming source, it just indexes in the normalized coordinate.
2. The `lat` values in your example bounding box are incorrect. `top_left` lat value is < `bottom_right` lat value - they need to be swapped.

**Pull request merged**
