### PR TITLE
[Security Solution] Add `read` permission for third party agent indices for `kibana_system`

### PR DESCRIPTION
**Pull request by ashokaditya**
Allow `read` privilege for `kibana_system` role on `logs-sentinel_one*` and `logs-crowdstrike*` index patterns
closes elastic/security-team/issues/9046

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`? yes

### CODE REVIEW

**Review by paul-tavares — APPROVED** [review]
Looks good. Thank you for getting this in.

**Comment by azasypkin** [comment]
> Third party agent info logs indices. Kibana reads from these to display agent status/info to the user.

What is the "third party agent" in this case? The linked issue doesn't seem to explain what these index patterns are for and who or what writes to them exactly. Can you please clarify that? 

The reason we always ask to provide answers to these questions is that `logs-sentinel_one*` and `logs-crowdstrike*` aren't hidden or system indices and might potentially collide with custom user data indices that `kibana_system` should _never_ be able to read or write to.

**Comment by ashokaditya** [comment]
> > Third party agent info logs indices. Kibana reads from these to display agent status/info to the user.
> 
> What is the "third party agent" in this case? The linked issue doesn't seem to explain what these index patterns are for and who or what writes to them exactly. Can you please clarify that?

Thanks for raising this @azasypkin. Third party agents are those that use third-party agent integrations (as opposed to Elastic Defend). Filebeat writes to these indices for such agents and this data is ingested by Fleet integrations in order to support response actions (respond to malicious events) on non-elastic (third-party) agents. Let me know if I should update the comment or this explanation is good to merge.

**Review by azasypkin — APPROVED** [review]
> Thanks for raising this @azasypkin. Third party agents are those that use third-party agent integrations (as opposed to Elastic Defend). Filebeat writes to these indices for such agents and this data is ingested by Fleet integrations in order to support response actions (respond to malicious events) on non-elastic (third-party) agents. 

Good, thanks for explaining, that makes sense. One last question: I see many similar index patterns ending with `-*` to ensure they match only a specific dataset. Is there any reason we cannot or don't want to do that for these patterns (`logs-sentinel_one-*` vs `logs-sentinel_one*` to match only the `sentinel_one` dataset and not `sentinel_one_legacy` or anything like that)?

> Let me know if I should update the comment or this explanation is good to merge.

Yeah, it'd be helpful for future readers if you can include this info in the PR description as well.

**Pull request merged**
