### PR TITLE
ESQL: Standardize font used in railroad diagrams

### PR DESCRIPTION
**Pull request by nik9000**
Locks the railroad diagrams to always use the same font, this one named `roboto mono`. This makes sure that when we render the railroad diagrams we always size them the same way. Because everyone has a copy of roboto mono. Because gradle resolves that dependency.

### CODE REVIEW

**Comment by nik9000** [comment]
The docs for this won't render correctly until we land a change to the docs build. I'll open a PR for that soon.

**Comment by nik9000** [comment]
This needs https://github.com/elastic/docs/pull/2744

**Review by costin — APPROVED** [review]
LGTM

**Comment by nik9000** [comment]
It's live:
image

I'm glad that worked! I don't make many changes to the docs build stuff.

**Pull request merged**
