### PR TITLE
Aggs must specify a `field` or `script` (or both)

### PR DESCRIPTION
**Pull request by polyfractal**
With https://github.com/elastic/elasticsearch/pull/49661 merged, we can now add validation to VSParserHelper to ensure that a field or script or both are specified by the user.  

This is technically required today already, but throws an exception much deeper in the agg framework and has a very unintuitive error for the user (as well as eating more resources instead of failing early)

Also removes a bit of out-dated documentation which does not work, and has not been supported for a while.

### CODE REVIEW

**Review by nik9000 — APPROVED** [review]
LGTM, though I think it'd be nice to have a integ test somewhere that asserts the exception you are looking for. Just one for all the aggs, but something to prove that nothing tricky is happening/ever happens in the exception flow.

**Comment by polyfractal** [comment]
@elasticmachine update branch

**Comment by polyfractal** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by polyfractal** [comment]
@elasticmachine update branch

**Pull request merged**
