### PR TITLE
Remove support for query_binary and filter_binary

### PR DESCRIPTION
**Pull request by javanna**
query_binary and filter_binary are unused at this point, as we only parse on the coordinating node and the java api only holds structured java objects for queries and filters, meaning they all implement Writeable and get natively serialized.

Relates to #14308

### CODE REVIEW

**Comment by dakrone** [comment]
LGTM, but should be marked as "breaking" and noted in the migration guide?

**Comment by javanna** [comment]
> should be marked as "breaking" and noted in the migration guide?

not really, we are just removing support for something that is at this time unused and was never documented. Last bit of the actual removal was part of #14384 with the removal of `QuerySourceBuilder`, which used `query_binary` internally and required it to be supported in core.

**Comment by dakrone** [comment]
>  we are just removing support for something that is at this time unused and was never documented

From the code it looks like someone could send `query_binary` or `queryBinary` at the REST layer, is that correct? If so, I definitely think we should mark/document this as breaking, because even though we don't *think* anyone uses it, someone could be.

**Comment by javanna** [comment]
Sure the feature is exposed to the outside world, I can mark breaking just to make sure, but it feels very weird to document that we removed it given that we never documented before, which we couldn't even deprecate in 2.x for the very same reason. This feature made sense only internally since the java api allowed to provide queries as binary objects, it should be treated as an internal thing as it was up until now.

**Pull request merged**
