### PR TITLE
Add Logging to Mock Repo API Server

### PR DESCRIPTION
**Pull request by original-brownbear**
While we log exception in the handler, we may still miss exceptions
hgiher up the execution chain. This adds logging of exceptions to all
operations on the IO loop including connection establishment.

Relates #49401

### CODE REVIEW

**Comment by original-brownbear** [comment]
@tlrx my best guess is that we have some exception further up the stack (above the handler that has all the logging now) that's killing connections here (any exception on the IO loop causes a connection close right now).

**Review by tlrx — APPROVED** [review]
LGTM, thanks Armin

**Comment by tlrx** [comment]
I merged this and backported it to 7.x and 7.5 so that we have this change on CI asap :)

**Comment by original-brownbear** [comment]
Thanks Tanguy!

**Pull request merged**
