### PR TITLE
Make array value parsing flag more robust.

### PR DESCRIPTION
**Pull request by jtibshirani**
When constructing a value fetcher, the 'parsesArrayValue' flag must match
`FieldMapper#parsesArrayValue`. However there is nothing in code or tests to
help enforce this.

This PR splits out a class `ArraySourceValueFetcher` that handles array values
directly and removes the flag. That way most field types can use the default
`SourceValueFetcher`. Field types that handle array values opt to use
`ArraySourceValueFetcher` and ensure the behavior is covered by tests.

Follow-up to #62974.

### CODE REVIEW

**Review by nik9000 — COMMENTED** [review]
Makes sense to me! I'll let @romseygeek review because it sounds like he understands the problem better.

**Comment by jtibshirani** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample-windows

**Review by romseygeek — APPROVED** [review]
LGTM, much nicer.  Thanks @jtibshirani!

**Comment by jtibshirani** [comment]
Thank you both for the reviews !

**Pull request merged**
