### PR TITLE
Suppress this-escape warning for JDK21

### PR DESCRIPTION
**Pull request by benwtrent**
follow up to: https://github.com/elastic/elasticsearch/pull/99848

### CODE REVIEW

**Comment by nik9000** [comment]
`DocVector` is fine to change. The lexer and parser are automatically generated. But I don't think you added a warning there.

**Comment by benwtrent** [comment]
@nik9000 where is the code that generates `EsqlBaseLexer` & `EsqlBaseParser`? Those will cause the warnings to trip every time they are regenerated as the generated code doesn't suppress the warnings. I did indeed add suppression to those two classes.

**Comment by nik9000** [comment]
> @nik9000 where is the code that generates `EsqlBaseLexer` & `EsqlBaseParser`? Those will cause the warnings to trip every time they are regenerated as the generated code doesn't suppress the warnings. I did indeed add suppression to those two classes.

It's in `x-pack/plugin/esql/build.gradle` and starts with `tasks.register("regen") {` er, well, it's actually in antlr, but you can modify the generated files with that gradle code.

**Comment by benwtrent** [comment]
@nik9000 I added some regex to that `regen` task. It now adds `@SuppressWarnings("this-escape")` to every ctor it can find. This seemed easier than trying to figure out the exact ones that had issues, and since its generated, I didn't think that would be an issue.

I re-ran regen locally, and that is what is in the PR now.

**Review by nik9000 — APPROVED** [review]
LGTM

**Pull request merged**
