### PR TITLE
ESQL: Improve signature gen ergonomics

### PR DESCRIPTION
**Pull request by nik9000**
Changes the behavior of syncing generated function signatures:
1. If the test run didn't generate any signatures, don't sync anything. This prevents stuff like `./gradlew test --tests "*Csv*"` from blowing away all of the signatures.
2. If there's a single test signature just copy it into the list without blowing away the others. This means that `./gradlew test --tests "*Ceil*"` will patch your new signature into place.
3. If there is more than one signature then sync the directories as before. That way adding or removing functions will remove the generated signatures.

This should make it so the function signature work is *mostly* invisible to users. It's not perfect - if you generate two signatues it'll make a bit of a mess, but that's pretty rare.

### CODE REVIEW

**Review by nik9000 — COMMENTED** [review]
Hold on a second. This isn't quite working...

**Comment by nik9000** [comment]
> Hold on a second. This isn't quite working...

Ok! All better now. Not sure what happened. Was working locally and then stopped. This fixes it.

**Review by luigidellaquila — APPROVED** [review]
LGTM, thanks!

**Comment by nik9000** [comment]
Approved offline.

**Pull request merged**
