### PR TITLE
[ML] Use weights with non-zero decimal in weighted_tokens

### PR DESCRIPTION
**Pull request by pquentin**
Those YAML tests are used to validate the Elasticsearch specification. Unfortunately, validation is done using JavaScript and JSON which only have a number type and no integer type. Which means 1.0 is treated as 1, which gives a validation failure as the specification expects floats.

### CODE REVIEW

**Comment by pquentin** [comment]
Sorry this is not ready yet!

**Review by benwtrent — COMMENTED** [review]
We should instead fix the parser to allow whole numbers that are just deserialized into floats. I think using whole numbers without decimal points should be valid.

**Comment by benwtrent** [comment]
My comment stands for sparse vector as well.

**Comment by pquentin** [comment]
In JSON and JavaScript, 1 and 1.0 are the same, there's no way around that. I'll try adding a special case to the validation logic then, thanks.

**Pull request closed without merging**
