### PR TITLE
Remove insecure settings

### PR DESCRIPTION
**Pull request by jasontedor**
This commit removes the oxymoron of insecure secure settings from the code base. In particular, we remove the ability to set the access_key and secret_key for S3 repositories inside the repository definition (in the cluster state). Instead, these settings now must be in the keystore. Thus, it also removes some leniency where these settings could be placed in the elasticsearch.yml, would not be rejected there, but would not be consumed for any purpose.

Relates #45947

### CODE REVIEW

**Review by rjernst — APPROVED** [review]
Thank you!! LGTM

**Comment by jasontedor** [comment]
@elasticmachine update braqnch

**Comment by jasontedor** [comment]
@elasticmachine update branch

**Comment by jasontedor** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by nik9000** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by jasontedor** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by jasontedor** [comment]
@elasticmachine run elasticsearch-ci/default-distro

**Comment by jasontedor** [comment]
@elasticmachine update branch

**Pull request merged**
