### PR TITLE
Add Ability to Infer Index Name from Alias When Using Index Templates

### PR DESCRIPTION
**Pull request by eladmena**
Implementation for ability to infer index name from alias when using index templates.

What was implemented:
- add inferIndexNameFromAlias to IndexTemplateMetaData, MetaDataIndexTemplateService.PutRequest, PutIndexTemplateRequest, RestPutIndexTemplateAction, builders, etc.
- Logic to infer index name from alias is in TransportCreateIndexAction
- Testing: Added InferIndexNameFromAliasTemplateIT
- Docs: Updated templates.asciidoc

What was not changed:
- org.elasticsearch.rest.action.cat.RestTemplatesAction#getTableWithHeader and corresponding rest-api-spec/test/cat.templates/10_basic.yaml as I didn't thought it should be exposed.

Note: that the code sets this feature to be active only for Elasticsearch 7 (see IndexTemplateMetaData & PutIndexTemplateRequest), it would be better if those can be changed to an earlier release

Implements [#22446](https://github.com/elastic/elasticsearch/issues/22446)

### CODE REVIEW

**Comment by eladmena** [comment]
@clintongormley any chance you can review this patch?
It's related to index templates, adding the ability to create the index from a template using the alias name from the start, removing the need to first create the index by name and then accessing it using the alias

**Comment by clintongormley** [comment]
See https://github.com/elastic/elasticsearch/issues/22446#issuecomment-349273681

**Comment by eladmena** [comment]
See my [response](https://github.com/elastic/elasticsearch/issues/22446#issuecomment-349278810)

**Comment by clintongormley** [comment]
Closing - see discussion in https://github.com/elastic/elasticsearch/issues/22446

**Pull request closed without merging**
