### PR TITLE
Upgrade to Gradle 5.4.1

### PR DESCRIPTION
**Pull request by alpar-t**
https://docs.gradle.org/5.4/release-notes.html

Notable: Support for JDK12 , API for incremental tasks

### CODE REVIEW

**Review by mark-vieira — APPROVED** [review]
When I upgraded before I started to see some really odd failures in CI so I reverted. Let's keep an eye out again when this gets merged.

**Comment by atorok** [comment]
#41357 was for `5.4` so figured it's worth another shot, but  if my memory serves me right, the checkstyle failure from the PR check is the one we ran into.

**Comment by mark-vieira** [comment]
It was indeed the odd checkstyle failure with compiling the line length regex.

**Comment by atorok** [comment]
Looks like the checkstyle upgrade didn't help.

**Comment by atorok** [comment]
I always disliked how checkstyle is slow and make the `precommit` slow, maybe this is a good time to look at replacing ti with say PMD.

**Comment by mark-vieira** [comment]
I think most source-based static analysis tools are going to be relatively slow. I'm not sure if PMD is necessarily better than Checkstyle. I wonder if there is some other way to implement this particular rule?

**Comment by atorok** [comment]
I'm not sure which regexp rule triggers it as we have multiple, doesn't seem easy to replace, at least not with a custom rule. I looked at `JavadocStyle` but  it's more strict that what we have, ad doesn't allow `/** @return ... */` which we have lots of. 

I'm going to try increasing the stack for Gradle ( as we run checkstyle in the same JVM ) to see if it helps. The theory is that we were on the edge with these large files and the new Gradle version tripped it by calling check-style slightly deeper.

**Comment by mark-vieira** [comment]
When it happened to me last time it was specifically [this rule](https://github.com/elastic/elasticsearch/blob/ad3218b4abd3aafdad0f7fb50ac05cfc74d8b34b/buildSrc/src/main/resources/checkstyle.xml#L27-L32) that it was barfing on.

> I'm going to try increasing the stack for Gradle ( as we run checkstyle in the same JVM ) to see if it helps. The theory is that we were on the edge with these large files and the new Gradle version tripped it by calling check-style slightly deeper.

Potentially. I'd be curious in seeing what it is about Checkstyle regex rules that's leveraging recursion though. We must have already been awfully close to the threshold.

**Comment by atorok** [comment]
@elasticmachine test this please so we know it wasn't just luck

**Comment by atorok** [comment]
@elasticmachine test this please, one last time

**Comment by mark-vieira** [comment]
LGTM @atorok. I say we merge :)

**Pull request merged**
