### PR TITLE
Improve EC SAN otherName CN support in ES docs, trust_restrictions, and elasticsearch-certutil

### PR DESCRIPTION
**Pull request by justincr-elastic**
The goal of this PR is to improve `EC SAN otherName CN` support and visibility in Elasticsearch. This includes:
1. Doc updates for `elasticsearch-certutil` and Security Settings
2. Tweaks to RestrictedTrustManager log messages, to clarify `CN` is from SAN otherName (i.e. `not Subject DN`)
3. Add `-cn` parameter to `elasticsearch-certutil` for `cert` and `csr` modes (i.e. not `ca` or `http` modes).

A `CN` moniker is ambigious. In Cross Cluster context, it means `Elastic Cloud SAN otherName type-id=commonName` with an associated UTF8 string value. The contents of the string are determined by Elastic Cloud. See https://www.elastic.co/guide/en/cloud/current/ec-trust-management.html#ec-trust-self-managed for format and examples.

The role of Elasticsearch is to provide a utility to create certs which may include the optional SAN otherName CN extension, and to enforce a list of match patterns (i.e. YAML list) in a file specified by setting `xpack.security.transport.ssl.trust_restrictions.path`. This feature was internal-only until recently, so there was no need to include it in user-facing Elasticsearch docs until now.

Recently, Elastic Cloud added support for CCS/CCR between deployments in ESS/ECE versus self-managed clusters. Cluster admin configuration is `not` required if CCS/CCR is 100% between Elastic Cloud deployments, or 100% between self-managed clusters. The only use case where cluster admins need to be aware of this extension is when bridging CCR/CCS between Elastic Cloud and self-managed. Bridging is useful for migrations from self-managed clusters to Elastic Cloud deployments, or for use cases where one or some clusters must remain self-managed (e.g. regulatory requirements).

Note: SAN otherName is for proprietary extensions. It is defined in [PKIX RFC 5280 Section 4.2.1.5: Subject Alt Name](https://www.rfc-editor.org/rfc/rfc5280#page-38). It is a tuple of a type-id and value. Third-party tools like OpenSSL can parse 8 of the 9 SAN types, but not the SAN otherName type because it is reserved for proprietary tuples. In the Elastic Cloud use case, SAN otherName uses type-id=commonName and explicit value=Utf8String. Other examples of proprietary SAN otherName usage include Kerberos PKINIT, and Microsoft AD CS issuing certs with SAN otherName type-id=UPN read from AD DS.

Note: If a third-party CA does not support `Elastic Cloud SAN otherName type-id=commonName` out-of-the-box, then a CA admin may be able to create a custom Certificate Template (aka Certificate Profile) to accept a CSR created by `elasticsearch-certutil` with the `-cn` parameter. Alternatively, use a CSR utility provided by the CA (e.g. OpenSSL CAs, Microsoft CAs, etc) to create the CSR, but populate SAN otherName with type-id=commonName and explicit value of type Utf8String.

### CODE REVIEW

**Comment by justincr-elastic** [comment]
@elasticmachine update branch

**Comment by justincr-elastic** [comment]
@elasticmachine run elasticsearch-ci/part-1

**Comment by justincr-elastic** [comment]
Manual test to illustrate how to create a certificate using the new `-cn` parameter:
```
./gradlew -p ./distribution/archives/linux-tar assemble
ls -l ./distribution/archives/linux-tar/build/distributions/elasticsearch-8.7.0-SNAPSHOT-linux-x86_64.tar.gz
mkdir -p ~/san_othername_test/
cp ./distribution/archives/linux-tar/build/distributions/elasticsearch-8.7.0-SNAPSHOT-linux-x86_64.tar.gz ~/san_othername_test
cd ~/san_othername_test/
tar xfz elasticsearch-8.7.0-SNAPSHOT-linux-x86_64.tar.gz
cd elasticsearch-8.7.0-SNAPSHOT/
echo "transport-ca.p12"             | bin/elasticsearch-certutil ca                                                        --days 7320 --keysize 3072 --ca-dn CN=transport-ca        --pass transport-ca
echo "transport-elasticsearch1.p12" | bin/elasticsearch-certutil cert -cn elasticsearch1.node.cluster1.cluster.123.account --days 398  --keysize 2048 --ca       transport-ca.p12 --ca-pass transport-ca --pass transport-elasticsearch1 --name transport-elasticsearch1 --dns transport-elasticsearch1 --dns localhost --dns localhost.localdomain --ip 127.0.0.1 --ip ::1
```
OpenSSL printouts of the P12 contents:
```
openssl pkcs12 -in transport-ca.p12             -passin pass:transport-ca                                                    -nokeys  -info -clcerts 2>/dev/null | openssl x509 -noout -text
openssl pkcs12 -in transport-elasticsearch1.p12 -passin pass:transport-elasticsearch1                                        -nokeys  -info -clcerts 2>/dev/null | openssl x509 -noout -text
openssl pkcs12 -in transport-ca.p12             -passin pass:transport-ca             -passout pass:transport-ca             -nocerts -info          2>/dev/null | openssl rsa -inform pem -noout -text --passin pass:transport-ca
openssl pkcs12 -in transport-elasticsearch1.p12 -passin pass:transport-elasticsearch1 -passout pass:transport-elasticsearch1 -nocerts -info          2>/dev/null | openssl rsa -inform pem -noout -text --passin pass:transport-elasticsearch1
```
This is the cert for `transport-elasticsearch1`:
```
-----BEGIN CERTIFICATE-----
MIIENDCCApygAwIBAgIUD9QpkTVzc05K3Hqby0NtDaZiB9wwDQYJKoZIhvcNAQEL
BQAwFzEVMBMGA1UEAxMMdHJhbnNwb3J0LWNhMB4XDTIyMTEyOTIyNTcyMFoXDTI0
MDEwMTIyNTcyMFowIzEhMB8GA1UEAxMYdHJhbnNwb3J0LWVsYXN0aWNzZWFyY2gx
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqwiRTtEEgoP4ZyFufSjh
VT93/6ecvDzve2pDrK4+QVhbEZRoUMwDSJzap488yRDyBZVRkYR0FQDtkqfSoQgK
tloF5KoI8BLtAMIPR6UQ+HbUSA5S9haFtGwDQotV22F51LDVHp6WhZ+9vZwbI7HW
8FfnLlzfqmT+Qyr37K/BBPdwh/EDtocgGsF6BoCOBtS2DbTllQLY7nLy9GlMesIJ
sx11IQYsGrONgA8GVbg+V088dFWay4bi9DLxbX2/N5F1Xk8FkYo0Huem7pM/4aQn
y/bB5t+c6QW9Avx7a7UelrjAB+bMafhvjgdtkB3TAWMVkzuZz/jjQOpYzoWEfXkt
bQIDAQABo4HrMIHoMB0GA1UdDgQWBBRV46j6aacD5COUhrvMK+3k9pOgHTAfBgNV
HSMEGDAWgBR9nli8ODw/BYFHcRZ981mtLVnMIzCBmgYDVR0RBIGSMIGPgglsb2Nh
bGhvc3SCGHRyYW5zcG9ydC1lbGFzdGljc2VhcmNoMYcEfwAAAYcQAAAAAAAAAAAA
AAAAAAAAAaA5BgNVBAOgMgwwZWxhc3RpY3NlYXJjaDEubm9kZS5jbHVzdGVyMS5j
bHVzdGVyLjEyMy5hY2NvdW50ghVsb2NhbGhvc3QubG9jYWxkb21haW4wCQYDVR0T
BAIwADANBgkqhkiG9w0BAQsFAAOCAYEAEAFEOvwat7ZrSYYGXNTLlxA7VnYL7CPw
iS3KiCjTKnEyXbECQssJ1CPhX6pYnRw5wCz7yuZK/XymQ1XY6mmZLjmHDQGzcGtY
DHzshzBRVjQtf8e4TLwtTMkHFPtEeRrhEdzklQ8LyIvcHD2iPOAloGKdLEud5slH
LuSEWbkEI/UZjNmiS5Ev7K3yEdK/bxwI7Ha/MVyPGoT0EkJLWtedSI28pubxKu4B
BQLRqjUb4wxF4iuTRvn4MsH/4eGCwUKk06ECfRF82H/01WNnGxlNfc+zN0YLIseB
S050prCU/GGwFGbs+3X/Sikvx5giy/q/SP89QEY+obN9Y+TB3La0fZwT2ARfDBsT
Cu2fEPaSOdne3N30GtQJX2vdu55Ryd4O11CaLIulatu1VoVS+Q439d8xJUJyrF3W
JNV5LfQxnicA8odupL4G/2Xf2AyHXQS/vjIc3/HyJBA5PKyhObvOS0RNtMfVlRRj
VuTAiBOL0nAhiqL5/hcWH2JSJ3mX+p2B
-----END CERTIFICATE-----
```
This is the above cert content for `transport-elasticsearch1`:
```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            0f:d4:29:91:35:73:73:4e:4a:dc:7a:9b:cb:43:6d:0d:a6:62:07:dc
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN = transport-ca
        Validity
            Not Before: Nov 29 22:57:20 2022 GMT
            Not After : Jan  1 22:57:20 2024 GMT
        Subject: CN = transport-elasticsearch1
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:ab:08:91:4e:d1:04:82:83:f8:67:21:6e:7d:28:
                    e1:55:3f:77:ff:a7:9c:bc:3c:ef:7b:6a:43:ac:ae:
                    3e:41:58:5b:11:94:68:50:cc:03:48:9c:da:a7:8f:
                    3c:c9:10:f2:05:95:51:91:84:74:15:00:ed:92:a7:
                    d2:a1:08:0a:b6:5a:05:e4:aa:08:f0:12:ed:00:c2:
                    0f:47:a5:10:f8:76:d4:48:0e:52:f6:16:85:b4:6c:
                    03:42:8b:55:db:61:79:d4:b0:d5:1e:9e:96:85:9f:
                    bd:bd:9c:1b:23:b1:d6:f0:57:e7:2e:5c:df:aa:64:
                    fe:43:2a:f7:ec:af:c1:04:f7:70:87:f1:03:b6:87:
                    20:1a:c1:7a:06:80:8e:06:d4:b6:0d:b4:e5:95:02:
                    d8:ee:72:f2:f4:69:4c:7a:c2:09:b3:1d:75:21:06:
                    2c:1a:b3:8d:80:0f:06:55:b8:3e:57:4f:3c:74:55:
                    9a:cb:86:e2:f4:32:f1:6d:7d:bf:37:91:75:5e:4f:
                    05:91:8a:34:1e:e7:a6:ee:93:3f:e1:a4:27:cb:f6:
                    c1:e6:df:9c:e9:05:bd:02:fc:7b:6b:b5:1e:96:b8:
                    c0:07:e6:cc:69:f8:6f:8e:07:6d:90:1d:d3:01:63:
                    15:93:3b:99:cf:f8:e3:40:ea:58:ce:85:84:7d:79:
                    2d:6d
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Subject Key Identifier: 
                55:E3:A8:FA:69:A7:03:E4:23:94:86:BB:CC:2B:ED:E4:F6:93:A0:1D
            X509v3 Authority Key Identifier: 
                7D:9E:58:BC:38:3C:3F:05:81:47:71:16:7D:F3:59:AD:2D:59:CC:23
            X509v3 Subject Alternative Name: 
                DNS:localhost, DNS:transport-elasticsearch1, IP Address:127.0.0.1, IP Address:0:0:0:0:0:0:0:1, othername: commonName::elasticsearch1.node.cluster1.cluster.123.account, DNS:localhost.localdomain
            X509v3 Basic Constraints: 
                CA:FALSE
    Signature Algorithm: sha256WithRSAEncryption
    Signature Value:
        10:01:44:3a:fc:1a:b7:b6:6b:49:86:06:5c:d4:cb:97:10:3b:
        56:76:0b:ec:23:f0:89:2d:ca:88:28:d3:2a:71:32:5d:b1:02:
        42:cb:09:d4:23:e1:5f:aa:58:9d:1c:39:c0:2c:fb:ca:e6:4a:
        fd:7c:a6:43:55:d8:ea:69:99:2e:39:87:0d:01:b3:70:6b:58:
        0c:7c:ec:87:30:51:56:34:2d:7f:c7:b8:4c:bc:2d:4c:c9:07:
        14:fb:44:79:1a:e1:11:dc:e4:95:0f:0b:c8:8b:dc:1c:3d:a2:
        3c:e0:25:a0:62:9d:2c:4b:9d:e6:c9:47:2e:e4:84:59:b9:04:
        23:f5:19:8c:d9:a2:4b:91:2f:ec:ad:f2:11:d2:bf:6f:1c:08:
        ec:76:bf:31:5c:8f:1a:84:f4:12:42:4b:5a:d7:9d:48:8d:bc:
        a6:e6:f1:2a:ee:01:05:02:d1:aa:35:1b:e3:0c:45:e2:2b:93:
        46:f9:f8:32:c1:ff:e1:e1:82:c1:42:a4:d3:a1:02:7d:11:7c:
        d8:7f:f4:d5:63:67:1b:19:4d:7d:cf:b3:37:46:0b:22:c7:81:
        4b:4e:74:a6:b0:94:fc:61:b0:14:66:ec:fb:75:ff:4a:29:2f:
        c7:98:22:cb:fa:bf:48:ff:3d:40:46:3e:a1:b3:7d:63:e4:c1:
        dc:b6:b4:7d:9c:13:d8:04:5f:0c:1b:13:0a:ed:9f:10:f6:92:
        39:d9:de:dc:dd:f4:1a:d4:09:5f:6b:dd:bb:9e:51:c9:de:0e:
        d7:50:9a:2c:8b:a5:6a:db:b5:56:85:52:f9:0e:37:f5:df:31:
        25:42:72:ac:5d:d6:24:d5:79:2d:f4:31:9e:27:00:f2:87:6e:
        a4:be:06:ff:65:df:d8:0c:87:5d:04:bf:be:32:1c:df:f1:f2:
        24:10:39:3c:ac:a1:39:bb:ce:4b:44:4d:b4:c7:d5:95:14:63:
        56:e4:c0:88:13:8b:d2:70:21:8a:a2:f9:fe:17:16:1f:62:52:
        27:79:97:fa:9d:81
```

**Comment by jakelandis** [comment]
Closing out this issue, we may revisit at later point in time.

**Pull request closed without merging**
