### PR TITLE
Bumping up the version of jackson to 2.12.0

### LINKED ISSUE #66555: Hex numbers in YAML requests are treated as strings
**Elasticsearch version** (`bin/elasticsearch --version`):

```
{
  "number": "7.11.0-SNAPSHOT",
  "build_flavor": "default",
  "build_type": "docker",
  "build_hash": "00e58bef3ac3f0bd7ab68b90e38e11cac05fb49e",
  "build_date": "2020-12-15T14:29:43.737519Z",
  "build_snapshot": true,
  "lucene_version": "8.7.0",
  "minimum_wire_compatibility_version": "6.8.0",
  "minimum_index_compatibility_version": "6.0.0-beta1"
}
```

**Plugins installed**: []

**JVM version** (`java -version`):

```
{
  "version": "15.0.1",
  "vm_name": "OpenJDK 64-Bit Server VM",
  "vm_version": "15.0.1+9",
  "vm_vendor": "AdoptOpenJDK",
  "bundled_jdk": true,
  "using_bundled_jdk": true,
  "count": 1
}
```

**OS version** (`uname -a` if on a Unix-like system): Our official Docker container based on CentOS Linux 8

**Description of the problem including expected versus actual behavior**:

When Elasticsearch unmarshals YAML scalar values in hexadecimal format it interprets the value as a string, but it should be a number. For example `0x1` becomes `"0x01"` when it should a `1`. This causes problems when you expected the data type to be a number (like when reading the param value within painless).

Reference: https://yaml.org/spec/1.2/spec.html#id2766934

Relates: https://github.com/elastic/kibana/issues/85486

**Steps to reproduce**:

1. Create an ingest pipeline using `Content-Type: application/yaml`. Include a hexidecimal number.

```
curl \
  -u elastic:changeme \
  -H 'Content-Type: application/yaml' \
  -X PUT \
  "localhost:9200/_ingest/pipeline/yaml_test" \
  -d'---

description: YAML unmarshal bug demo
processors:
  - script:
      lang: painless
      params:
        number_base10: 1
        number_base16: 0x1
        string: hello
      source: >
        params.forEach((k, v) -> ctx[k] = v);'
```

2. Read the pipeline.

```
curl -u elastic:changeme -H 'Content-Type: application/yaml' -X GET "localhost:9200/_ingest/pipeline/yaml_test"
---
yaml_test:
  description: "YAML unmarshal bug demo"
  processors:
  - script:
      lang: "painless"
      params:
        number_base10: 1
        number_base16: "0x1"
        string: "hello"
      source: "params.forEach((k, v) -> ctx[k] = v);"
```

```
$ curl -u elastic:changeme -X GET "localhost:9200/_ingest/pipeline/yaml_test?pretty"
{
  "yaml_test" : {
    "description" : "YAML unmarshal bug demo",
    "processors" : [
      {
        "script" : {
          "lang" : "painless",
          "params" : {
            "number_base10" : 1,
            "number_base16" : "0x1",
            "string" : "hello"
          },
          "source" : "params.forEach((k, v) -> ctx[k] = v);"
        }
      }
    ]
  }
}
```

Note that `number_base16` is `"0x1"`. It should a 1.

### PR DESCRIPTION
**Pull request by jamesrowe08**
This will close #66555

API calls mentioned in that bug now work correctly:

```
curl -u elastic:password -H 'Content-Type: application/yaml' -X GET "localhost:9200/_ingest/pipeline/yaml_test"

yaml_test:
  description: "YAML unmarshal bug demo"
  processors:
  - script:
      lang: "painless"
      params:
        number_base10: 1
        number_base16: 1
        string: "hello"
      source: "params.forEach((k, v) -> ctx[k] = v);"
```

```
curl -u elastic:password -X GET "localhost:9200/_ingest/pipeline/yaml_test?pretty"
"yaml_test" : {
    "description" : "YAML unmarshal bug demo",
    "processors" : [
      {
        "script" : {
          "lang" : "painless",
          "params" : {
            "number_base10" : 1,
            "number_base16" : 1,
            "string" : "hello"
          },
          "source" : "params.forEach((k, v) -> ctx[k] = v);"
        }
      }
    ]
  }
}
```

### CODE REVIEW

**Comment by rjernst** [comment]
I believe `snakeyaml` needs to be bumped as well. It looks like `jackson-dataformat-yaml` 2.12.0 uses `snakeyaml` with version 1.27.

**Comment by jamesrowe08** [comment]
This change has been made @rjernst

**Comment by rjernst** [comment]
@elasticmachine ok to test

**Comment by rjernst** [comment]
@jamesrowe08 I've pushed an update to the SHAs that needs to go along with this version bump. Note, however, that it is generally inadvisable to use the `master` branch as the source of a pull request. I recommend for any future pull requests you create a branch off of `master`.

**Comment by rjernst** [comment]
@elasticmachine update branch

**Comment by mark-vieira** [comment]
@elasticmachine update branch

**Comment by fcofdez** [comment]
@elasticmachine update branch

**Comment by fcofdez** [comment]
There's recent change in Jackson (https://github.com/FasterXML/jackson-dataformat-xml/issues/411) that changed a default behaviour that would prevent upgrading to this version, as it produces an endless loop in the azure sdk code. See 
 https://github.com/Azure/azure-sdk-for-java/issues/9465#issuecomment-775044143 for more context.

**Comment by rjernst** [comment]
Thanks for tracking that down @fcofdez. I don't think we can upgrade yet to Jackson 2.12.0 because of this. The Azure SDK still depends on 2.11.3. Unfortunately because Jackson is still a dependency of the Elasticsearch server, any use of it in plugins must match the version provided (otherwise we would get jar hell). While it is a goal to continue to not force these dependencies to match, it likely won't happen before this is simply fixed upstream. In the meantime I am marking this PR as stalled.

**Comment by joshbressers** [comment]
@rjernst If I'm correctly reading the tangle of bugs in that azure issue, I think this is fixed now in the current version 12.11.0
https://github.com/Azure/azure-sdk-for-java/issues/18881#issuecomment-826830353

**Comment by rjernst** [comment]
Thanks @joshbressers. I opened #72833. That requires upgrading Jackson as well in the same commit, so this PR becomes unnecessary. Thanks @jamesrowe08

**Pull request closed without merging**
