### PR TITLE
Unsigned long should accept value with zero fraction

### LINKED ISSUE #67565: Unsigned long field mapping behaviour is inconsistent with other numeric fields
**Elasticsearch version**: 7.11.0
**Plugins installed**: []
**JVM version**: n/a
**OS version**: n/a

**Description of the problem including expected versus actual behavior**:
There is a discrepancy for `unsigned_long` vs. other numeric fields when providing a `null_value` in the mapping. Currently, integer for example, accepts a `null_value` of 1.0 which is checked for empty fractal parts. It will correctly reject a null value of 1.5. `unsigned_long` mappings return a "mapper_parsing_exception" when 1.0 is specified.

Ideally, the `unsigned_long` field should behave in the same way as other numeric fields and check for empty fractal parts.

**Steps to reproduce**:

 1. Attempt to create an index with the following mapping

```
PUT my_index
{
  "mappings": {
    "properties": {
      "my_counter": {
        "type": "unsigned_long",
        "null_value": 1.0
      },
      "my_int": {
        "type": "integer",
        "null_value": 1.0
      },
      "my_short": {
        "type": "short",
        "null_value": 1.0
      }
    }
  }
}
```

 2. Only the my_counter field causes a "mapper_parsing_exception".

### PR DESCRIPTION
**Pull request by dnhatn**
Closes #67565

### CODE REVIEW

**Review by mayya-sharipova — CHANGES_REQUESTED** [review]
@dnhatn Thanks for this fix, and sorry for a late reply. The change and the tests overall look great to me, but we should also address a case where a zero decimal comes in a numeric form, as current the following test will fail:

```java
ParsedDocument doc = mapper.parse(source(b -> b.field("field", 100.0)));
assertThat(doc.rootDoc().getFields("field")[0].numericValue().longValue(), equalTo(Long.MIN_VALUE + 100L));

```

**Comment by dnhatn** [comment]
Thanks Mayya! I pushed https://github.com/elastic/elasticsearch/pull/75646/commits/fdf023b3493d0ae0440c7420f39c0fac17d65852.

**Comment by dnhatn** [comment]
@elasticmachine update branch

**Review by mayya-sharipova — APPROVED** [review]
Thanks Nhat, this LGTM

**Comment by dnhatn** [comment]
@mayya-sharipova Thanks for reviews.

**Pull request merged**
