### PR TITLE
Sum aggregations for long values precision

### PR DESCRIPTION
**Pull request by hackerwin7**
Create long type for `InternalSum` and `SumAggregator` to process the long field type of values without loosing precision.

relates #50503

### CODE REVIEW

**Comment by elasticcla** [comment]
Hi @hackerwin7, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in your Git [commit](https://github.com/elastic/elasticsearch/pull/50538.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by hackerwin7** [comment]
retest

**Comment by hackerwin7** [comment]
ping @colings86

**Comment by polyfractal** [comment]
Hi @hackerwin7, thanks for the PR :)  Please don't ping individual members though, when tickets are labeled it will ping the correct team to take a look.

I'm going to mark this ticket for team discussion, but I suspect we won't be able to merge it.  There is some discussion about supporting more precise aggregations in this issue, for background: https://github.com/elastic/elasticsearch/issues/46934

There are a few issues which make this problematic:

- Doubles are used everywhere in aggregations for several reasons, but one prominent reason is that it reduces the chance of overflows.  With this change, a user could easily overflow the `long` and not realize
- Consistency.  Since doubles are used everywhere, having just the `sum` agg switch behavior would be very confusing
- This breaks backwards compatibility, both at the wire transport level (fixable) but also in behavior.  E.g. a `sum` agg would start to behave differently on the same data after upgrading.  This is also fixable with flags and such, but again goes back to consistency... if we start to introduce "precise" aggs we should really support it for _all_ metrics which is a much larger undertaking.
- Better, but potentially not good enough.  E.g. the discussion in https://github.com/elastic/elasticsearch/issues/46934 shows that some folks want/need much more robust control over metric precision.  Introducing a change like this is more of a bandaid than a fix that would satisfy many use-cases, but still carries maintenance cost.

Marking as team-discuss to see what the rest of the analytics team has to say!

**Comment by polyfractal** [comment]
Related: https://github.com/elastic/elasticsearch/issues/9545 and https://github.com/elastic/elasticsearch/issues/43258

**Comment by hackerwin7** [comment]
@polyfractal 
Thanks for your reply, after reviewing the discuss #46934 , what the future works in Elastic for support to     **compelete accuracy** of long field type sum aggregations or just have no plan on this?

**Comment by polyfractal** [comment]
@hackerwin7 at the moment, no plans at all... just something we've been discussing.  That's the main reason I didn't close this PR but marked it as team-discuss to see what the rest of the team thought. Sometimes small incremental improvements are better than nothing at all :)

**Comment by Laurianti** [comment]
Any news here?

**Comment by nik9000** [comment]
Actually yes! ESQL supports `sum` using `long` precision. `FROM foo | STATS SUM(long_field)` will sum a long.

**Pull request closed without merging**
