### PR TITLE
Use Decimal formatter for Numeric ValuesSourceTypes

### LINKED ISSUE #54365: MultiValuesSource Aggregations (including weighted_avg) ignore format
To reproduce:

```
DELETE test

POST test/_bulk
{"index":{}}
{"foo":[15.2, 13], "bar":15.9}
{"index":{}}
{"foo":15.3, "bar":15.9}

POST test/_search
{
  "size": 0,
  "aggs": {
    "a": {
      "avg": {
        "field":"foo",
        "format": "000000.0%"
      }
    },
    "wa": {
      "weighted_avg": {
        "value": {"field":"foo"},
        "weight": {"field":"bar"},
        "format": "000000.0%"
      }
    }
  }
}
```

response:

```
{
   .... 
  "aggregations" : {
    "a" : {
      "value" : 14.5,
      "value_as_string" : "001450.0%"
    },
    "wa" : {
      "value" : 14.5
    }
  }
}
```

It looks like the problem is caused by [MultiValuesSourceAggregationBuilder.resolveFormat](https://github.com/elastic/elasticsearch/blob/a90c1de8745681356a6516f4f22a8c40f71f6b12/server/src/main/java/org/elasticsearch/search/aggregations/support/MultiValuesSourceAggregationBuilder.java#L186) method that always returns RAW format. 

Since the response type in the weighted_avg aggregation is always double and doesn't depend on the types of input value sources, we might need to address #47469 before addressing this issue.

### PR DESCRIPTION
**Pull request by not-napoleon**
I think this resolves #54365 and probably a few other places we were picking the wrong formatter.

### CODE REVIEW

**Review by imotov — COMMENTED** [review]
That fixes both weighted_avg and t_test. We just need to make sure we don't pass time zone in SQL. Thanks!

**Comment by not-napoleon** [comment]
@imotov What do you want to do with this?  As you say, it's currently stuck on SQL's formatting behavior, which, honestly, I'm not sure how that was working before.  The code I'm using here is taken directly from the field formatter, so I'm shocked it wasn't throwing from there before.  Do you want to fix this SQL side and I'll pull the fix in here and see what we have?

Alternatively, I can change this to accept and ignore a timezone, which should get the tests passing.  I don't love ignoring parameters, it seems excessively lenient, but it wouldn't be worse than it is now.

**Comment by imotov** [comment]
I have done some digging. Here is the reproduction of the issue that doesn't involve SQL:

```
DELETE test
PUT test
{
  "mappings": {
    "properties": {
      "start": {
        "type": "date"
      }
    }
  }
}

PUT test/_doc/1
{
  "start": "2020-01-01T00:00:00"
}

PUT test/_doc/2
{
  "start": "2020-01-02T00:00:00"
}

POST test/_search
{
  "aggs": {
    "agg1": {
      "date_histogram": {
        "script": {
          "source": "doc['start'].value"
        },
        "calendar_interval": "1y",
        "value_type": "long",
        "time_zone" : "-04"
      }
    }
  }
}
``` 

That works without this PR and I feel like it is a valid use-case and it should work. I think we are again dealing with overloaded parameters here.

**Comment by imotov** [comment]
@elasticmachine update branch

**Comment by not-napoleon** [comment]
@elasticmachine test this please

**Comment by not-napoleon** [comment]
@elasticmachine update branch

**Comment by not-napoleon** [comment]
@elasticmachine update branch

**Review by imotov — APPROVED** [review]
LGTM

**Pull request merged**
