### PR TITLE
Avoid creating GeometryFormat when parsing points.

### PR DESCRIPTION
**Pull request by jtibshirani**
Previously we constructed a GeometryFormat object and delegated point parsing
to it. This isn't necessary and isn't a good fit conceptually because each
GeometryFormat instance doesn't represent a distinct point format.

### CODE REVIEW

**Comment by nik9000** [comment]
> isn't not

is not?

**Comment by jtibshirani** [comment]
> isn't not

An edit gone wrong. I corrected the PR description.

**Comment by jtibshirani** [comment]
@elasticmachine test this please

**Review by talevy — APPROVED** [review]
good catch! definitely not its intended usage here. I believe this was picked up doing a refactor to keep things similar across implementations

**Comment by jtibshirani** [comment]
Thanks @talevy for the review !

**Pull request merged**
