### PR TITLE
Remove superfluous HTML start element at end of body

### PR DESCRIPTION
**Pull request by ChrisHegarty**
In JDK 17, doclint invoked by javac warns of constructs that lead to empty paragraphs in the generated documentation. We have a handful of these, redundant use of `<p>` at the end of a block of text, which trips up the build. This a preparatory change intended to help smoothen the eventual transition to 17. 

The JDK issue that introduced this stricter doclint check in 17 is https://bugs.openjdk.java.net/browse/JDK-8258957.

### CODE REVIEW

**Comment by ChrisHegarty** [comment]
There is no test for this change, other than compiling with JDK 17 - which complete successfully on "my machine" ;-).

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by ChrisHegarty** [comment]
@elasticmachine update branch

**Pull request merged**
