### PR TITLE
Upgrade to lucene-8.7.0-snapshot-cdfdc1e0851.

### PR DESCRIPTION
**Pull request by jpountz**
Upgrade to a new Lucene snapshot that (at least partially) addresses the
indexing rate regression when index sorting is enabled.

### CODE REVIEW

**Review by dnhatn — APPROVED** [review]
LGTM

**Comment by jpountz** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample-windows

**Comment by jpountz** [comment]
@elasticmachine run elasticsearch-ci/bwc
@elasticmachine run elasticsearch-ci/default-distro

**Comment by jpountz** [comment]
@elasticmachine run elasticsearch-ci/1

**Pull request merged**
