### PR TITLE
Code cleanup in TransportRolloverAction and added concurrent rollover test.

### PR DESCRIPTION
**Pull request by martijnvg**
Code cleanups around rollover executor in `TransportRolloverAction` and added an integration test that tests rollover concurrently.

Relates to #79945

### CODE REVIEW

**Review by henningandersen — COMMENTED** [review]
Thanks for improving this. Can we also add more testing, to check that the batched case works (perhaps just an integ test doing X rollovers concurrently)?

**Comment by martijnvg** [comment]
@henningandersen I've added an integration test: 3ac70fa2dead77fa99b2bb3610a2b55dc5fefeff

**Comment by dakrone** [comment]
@martijnvg can you update the title and description of this PR so we can tell what it's doing? I want to make sure we can find it in the future using keywords for what this PR is actually changing.

**Comment by martijnvg** [comment]
> Can we add a CyclicBarrier(numOfThreads) that ensures all threads start the rollovers at the same time, just to increase the chance of failure.

@henningandersen I've added this here: 829cd2d4c7a2e4acda36bf7ee3d18085d3bc57cb

**Review by henningandersen — APPROVED** [review]
LGTM, thanks for addressing this.

**Comment by martijnvg** [comment]
@elasticmachine update branch

**Comment by martijnvg** [comment]
> LGTM, thanks for addressing this.

Thanks for bringing this up!

**Pull request merged**
