### PR TITLE
Filter node.roles setting in transport client

### PR DESCRIPTION
**Pull request by jasontedor**
This commit filters out the node.roles setting from the transport client, since the transport client does not take on these roles.

Relates #64260

### CODE REVIEW

**Comment by jasontedor** [comment]
This is a deliberately sloppy PR, merely to see if we can get away with not registering all the roles in the transport client, that the problem we are seeing in #64260 is that we're trying to set a setting in tests that doesn't even make sense for the transport client.

**Comment by jasontedor** [comment]
I've cleaned this implementation up by filtering the offensive setting in the test infrastructure, removing the need that we register these roles in the transport client. This will keep the transport client from clobbering the node roles when running the same shared VM during tests.

**Review by nik9000 — APPROVED** [review]
I see that this does two things:
1. Stops us from sending node.roles to the transport client. This makes sense because it doesn't really have a role. It isn't a node. Its a client.
2. Stops us from initializing roles in the transport client at all. Which is fine now that we're not sending the roles to it.

That static state in DiscoveryNode.setAdditionalRoles looks like it's been around a while. I'm surprised it hasn't got us in trouble before.

**Comment by jasontedor** [comment]
It has gotten us into trouble, and we have some technical debt (hacks) in the codebase to work around some of the trouble.

**Pull request merged**
