### PR TITLE
Unmute SecurityWithBasicLicenseIT

### PR DESCRIPTION
**Pull request by slobodanadamovic**
Test failure issue got closed without actually unmuting this test. Locally, this test passes.

Relates https://github.com/elastic/elasticsearch/issues/99169

### CODE REVIEW

**Review by jfreden — APPROVED** [review]

**Comment by slobodanadamovic** [comment]
@elasticmachine update branch

**Comment by slobodanadamovic** [comment]
@elasticmachine update branch

**Comment by slobodanadamovic** [comment]
@elasticmachine update branch

**Comment by slobodanadamovic** [comment]
@elasticmachine update branch

**Comment by slobodanadamovic** [comment]
@elasticmachine update branch

**Comment by slobodanadamovic** [comment]
@elasticmachine update branch

**Comment by slobodanadamovic** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.x|[](https://github.com/elastic/elasticsearch/pull/116568)|
|✅|8.16|[](https://github.com/elastic/elasticsearch/pull/116569)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
