### PR TITLE
SQL: Allow whitespaces in escape patterns

### LINKED ISSUE #47401: SQL: allow spaces in escape sequences
Elasticsearch/SQL now supports JDBC/ODBC escape sequences at server level.
However, the current parser requires the `{` escape begin character to be followed by the escape discriminator with no white space allowed in-between. Example: `FUNCTION_ESC: '{FN';`.
The [BNF specification](https://docs.microsoft.com/en-us/sql/odbc/reference/appendixes/scalar-function-escape-sequence) suggests white spaces would be allowed (maybe an **A**BNF would have made that explicit) and in support for that, other DBs supporting these escape sequences at server level do allow for spaces too (like MSSQL, DB2, MariaDB/MySQL).
Furhermore, also some applications - like PowerBI - generate escape sequences with spaces:
`select { fn name(params) } etc.`

### PR DESCRIPTION
**Pull request by matriv**
Previously, we supported only the format `{fn <FUNCTION_NAME>()}`
but other DBs like MSSQL, DB2, MariaDB/MySQL alos allow whitespaces
between `{` and `fn`. Furhermore, also some applications - like PowerBI -
generate escape sequences with spaces: `select { fn name(params) } etc.`

Add support for white spaces between `{` and the escape pattern definition
like `fn`, `ts`, `d`, `guid` etc.

Closes: #47401

### CODE REVIEW

**Comment by matriv** [comment]
I'm considering to backport it to earlier versions too, more like a fix.
What would you think?

**Comment by matriv** [comment]
There is another possibility to refactor the grammar like this: https://github.com/matriv/elasticsearch/compare/impl-47401...matriv:refactor-grammar?expand=1#diff-14b1f1a74854b9993f46da9467f6abcb so that we avoid the explicit `(WS)*`.

Personally I prefer the solution as is currently in the PR, which distinguishes the `LIMIT` from the `LIMIT_ESC` and the `ESCAPE` from the `ESCAPE_ESC`.

**Review by astefan — APPROVED** [review]
LGTM

**Review by bpintea — APPROVED** [review]
LGTM

**Comment by costin** [comment]
LGTM
For the record, the JDBC spec mandates that there should be no whitespace in the header (e.g. `{fn` NOT `{ fn `).

**Review by costin — APPROVED** [review]
LGTM

**Comment by matriv** [comment]
> I'm considering to backport it to earlier versions too, more like a fix.
> What would you think?

@costin what's your opinion on this ^ ?

**Comment by matriv** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample

**Pull request merged**
