### PR TITLE
Adds ILMClient for use with transport client

### PR DESCRIPTION
**Pull request by colings86**

### CODE REVIEW

**Review by AthenaEryma — APPROVED** [review]
Does this need tests? I think I recall a conversation where it was noted that transport client stuff isn't really tested, but just asking in case.

Otherwise, LGTM.

**Comment by colings86** [comment]
Good point @dakrone I'll add the sync methods

**Comment by colings86** [comment]
@dakrone I pushed a commit with the sync methods

**Review by dakrone — CHANGES_REQUESTED** [review]
I believe this needs to be added to `XPackClient` similar to how we have the other `MonitoringClient`, `WatcherClient`, etc, that way it is accessible rather than instantiating it ourselves

**Review by dakrone — APPROVED** [review]
LGTM, thanks Colin

**Pull request merged**
