### PR TITLE
Deprecate Indices query

### LINKED ISSUE #12017: Deprecate `indices` query in favour of making `_index` queryable
The `indices` query allows the user to run different queries on different indices, eg to create a union of docs from different indices, where the conditions to be applied to each index are different.

A simpler way to write this query would be to make `_index` usable in the `term`, `terms`, `match`, `query_string`, and `simple_query_string`queries (see #3316).

However, this change also depends on the changes in #12016 to allow unmapped fields to be handled gracefully across all queries.

### PR DESCRIPTION
**Pull request by colings86**
This is in favour of just searching the _index field

Closes #12017

### CODE REVIEW

**Comment by jpountz** [comment]
This looks good to me. Let's maybe add a concrete example to the docs that shows how an IndicesQuery can be replaced with a BooleanQuery using the `_index` field?

**Comment by clintongormley** [comment]
Hmmm...  not quite replaceable.   Queries in the indices query are only parsed on the listed indices - the same is not true for bool, eg, this example creates a parent mapping on one index, but not the other:

    DELETE one,two
    
    PUT one 
    {
      "mappings": {
        "parent": {},
        "child": {
          "_parent": {
            "type": "parent"
          }
        }
      }
    }
    
    PUT two
    
The `indices` query allows you to query two indices with different mappings:
    
    GET _search
    {
      "query": {
        "indices": {
          "indices": [
            "one"
          ],
          "query": {
            "has_child": {
              "type": "child",
              "query": {"match_all": {}}
            }
          },
          "no_match_query": {"match_all": {}}
        }
      }
    }
    
While this query will throw an exception about missing the parent type:

    GET _search
    {
      "query": {
        "bool": {
          "should": [
            {
              "bool": {
                "must": [
                  {
                    "term": {
                      "_index": "one"
                    }
                  },
                  {
                    "has_child": {
                      "type": "child",
                      "query": {
                        "match_all": {}
                      }
                    }
                  }
                ]
              }
            },
            {
              "bool": {
                "must_not": [
                  {
                    "term": {
                      "_index": "one"
                    }
                  }
                ]
              }
            }
          ]
        }
      }
    }

That's why this change depends on https://github.com/elastic/elasticsearch/issues/12016

**Comment by colings86** [comment]
@clintongormley now we have https://github.com/elastic/elasticsearch/pull/17751 and https://github.com/elastic/elasticsearch/pull/17748 to deal with the above, are you ok for me to merge this?

**Comment by clintongormley** [comment]
+1

**Pull request merged**
