### PR TITLE
Report JVM stats for all memory pools (97046)

### LINKED ISSUE #97046: Report JVM stats for all memory pools
Today we report stats on certain JVM memory pools (munging their names according to `org.elasticsearch.monitor.jvm.GcNames#getByMemoryPoolName`) but we omit stats on other pools on the grounds that they are ["not interesting"](https://github.com/elastic/elasticsearch/blob/d6b80c0b335cd1a2f75378a03b87d4d49f1885b1/server/src/main/java/org/elasticsearch/monitor/jvm/JvmStats.java#L67). In practice these not-interesting pools can be sizeable, and we should expose all their sizes in our stats.

### PR DESCRIPTION
**Pull request by alexey-ivanov-es**
This fix allows reporting of all JVM memory pools sizes in JVM stats

Fixes #97046

### CODE REVIEW

**Comment by mosche** [comment]
The new pool names will be includes in the `_nodes/stats` response, meaning `pool` will contain keys such as `CodeHeap 'non-profiled nmethods'` which aren't really api friendly. But I can see this is already the case for `buffer_pools` as well (`mapped - 'non-volatile memory'`), so not sure if we care.

You can use `http://localhost:9200/_nodes/stats?metric=jvm` to test locally.

**Comment by mosche** [comment]
@alexey-ivanov-es could you add some basic assertions to `JvmStatsTests`, e.g. that young, old and survivor exist plus more

**Comment by alexey-ivanov-es** [comment]
@mosche I've added some assertions

**Comment by alexey-ivanov-es** [comment]
@elasticmachine update branch

**Review by mosche — APPROVED** [review]
thanks @alexey-ivanov-es , LGTM 🎉

**Pull request merged**
