### PR TITLE
Fix rollup on date fields that don't support epoch_millis

### PR DESCRIPTION
**Pull request by jimczi**
The rollup indexer uses a range query to select the next page
of results based on the last time bucket of the previous round
and the `delay` configured on the rollup job. This query uses
the `epoch_millis` format implicitly but doesn't set the `format`.
This result in errors during the rollup job if the field
definition doesn't allow this format. It can also miss documents
if the format is not accepted but another format in the field
definition is able to parse the query (e.g.: `epoch_second`).
This change ensures that we use `epoch_millis` as the only format
to parse the rollup range query.

### CODE REVIEW

**Comment by polyfractal** [comment]
The change looks good, although I'm curious how the bug is triggered?  It's not clear to me how you'd bump into this problem.  Is the issue if the timestamp field has a mixture of formatting across different indices?

Could we add this as a yaml REST test or unit test somewhere?  I have a strong desire to delete RollupIT entirely (will touch base with you online about that)

**Comment by polyfractal** [comment]
@jimczi Just merged #31977 into master (backports to follow shortly).  Thanks for your patience while we sorted out that weird CI issue :)

**Comment by jimczi** [comment]
Thanks @polyfractal ! I pushed a change to test the fix in the rest tests and in the unit tests. Can you take another look ?

**Review by polyfractal — APPROVED** [review]
LGTM!  ++ randomizing the page size too, good call.

**Pull request merged**
