### PR TITLE
Using HPPC longhashset for SetBackedScalingCuckooFilter

### PR DESCRIPTION
**Pull request by gf2121**
`SetBackedScalingCuckooFilter` used to use `java.util.set<Long>` to store hashes, `com.carrotsearch.hppc.LongHashSet` could be a better choice here.

(Serialization and Deserialization are compatible with previous versions.)

### CODE REVIEW

**Comment by gf2121** [comment]
@nik9000 Hi! sorry to disturb you. I looked into the commit history and find that you are one of the contributors of this file. So i guess that you must be familiar with these code. Would you please help take a look at this tiny enhancement when you are free? Thanks!

**Comment by nik9000** [comment]
> @nik9000 Hi! sorry to disturb you. I looked into the commit history and find that you are one of the contributors of this file. So i guess that you must be familiar with these code. Would you please help take a look at this tiny enhancement when you are free? Thanks!

Hi! This should probably have got triaged over to either @iverase or myself by someone on a daily rota for this sort of thing. Looks like it's not happening! Oh well, I'll assign it to both of us now.

I'm away the next two days. And when I come back I'm going to have a bit of a backlog. But I'll try and get to this as soon as I can. Or @iverase will beat me to it.

**Comment by gf2121** [comment]
Thanks for your reply!

> IIRC the original reasoning around Set<Long> here was that we thought this would migrate into Lucene where they don't have hppc.

I guess lucene's [longhashset](https://github.com/apache/lucene/blob/d5d6dc079395c47cd6d12dcce3bcfdd2c7d9dc63/lucene/sandbox/src/java/org/apache/lucene/sandbox/search/LongHashSet.java) could be a good choice if we migrate this to lucene one day, but it has not been public by now.

>  It might be better to use our LongHash here instead of hppc's LongHashSet because our version is backed by BigArrays which does automatic usage tracking.

I also struggled between hppc's `LongHashSet` and `LongHash`, and the reason why I finally chose hppc was that it would be a bit strange if we only tracked when the data was small (isSetMode=true) but stopped after the data was huge (isSetMode=false). It would be difficult if the cuckoo filter needs to be tracked completely because it relies on `org.apache.lucene.util.packed.PackedInts.Mutable`.

**Comment by iverase** [comment]
Not sure of the benefit of doing this change, do we have some performance numbers that show an improvement?

 I wonder if we should try to move the implementation to BigArrays (together with cuckoo filter). I had a look and before it was not possible as we were using a packed array implementation from Lucene, but now that we have our own implementation we might better try. 

if we use BigArrays, we might loose is the ability to unpack longs efficiently but looking how we are using it, it might no be too bad.

**Comment by nik9000** [comment]
My general instinct is to get more stuff on `BigArrays` if possible. If we're ever going to do off heap *stuff* in ES, that'd be how.

**Comment by gf2121** [comment]
@nik9000 @iverase Thanks a lot for the great advice! 
> Not sure of the benefit of doing this change, do we have some performance numbers that show an improvement?

I did not do a benchmark for this change before, just thought HPPC should be theoretically better than Set<Long> and the change seems not Invasive. Actually, I believe this tiny optimization can not obviously improve the performance of the whole query :)

I'd like to do some jop to make the `SetBackedScalingCuckooFilter` and  `CuckooFilter` base on BigArrays and benchmark for them. But I find that `BigArrays` is not available in the context of deserialization. Would you please teach me how to sovle this problem?

```
public SetBackedScalingCuckooFilter(StreamInput in, Random rng) throws IOException {
        this.threshold = in.readVInt();
        this.isSetMode = in.readBoolean();
        this.rng = rng;
        this.capacity = in.readVInt();
        this.fpp = in.readDouble();

        if (isSetMode) {
            int size = in.readVInt();
            // how to new a LongHash based on BigArrays here?
            this.hashes = new LongHashSet(size);
            for (int i = 0; i < size; i++) {
                this.hashes.add(in.readZLong());
            }
        } else {
            ...
        }
    }
 ```

**Comment by iverase** [comment]
Hi @gf2121,

Sorry it took so long to come back to you. We discussed this issue internally and we are leaning to the idea to remove usages of exotic HPPC classes. The idea of moving the infrastructure to `BigArrays` still is attractive.

If you want to keep working on it please feel free. About your question above, in that case you will need to get a non recycle instance via ` BigArrays.NON_RECYCLING_INSTANCE`

**Comment by iverase** [comment]
Hi @gf2121,

We are removing all dependencies on HPPC so this PR is no relevant any more.If you are still willing to pursue the idea of using BigArrays to backup the long hashet, please open a new PR.

Thanks you and sorry!

**Pull request closed without merging**
