### PR TITLE
[DOCS] Reformats cluster update settings API

### PR DESCRIPTION
**Pull request by szabosteve**
Relates to elastic/docs#937 and https://github.com/elastic/elasticsearch/issues/45197.

This PR updates the cluster update settings API to align with the new [API reference template](https://github.com/elastic/docs/blob/master/shared/api-ref-ex.asciidoc).

Resources:
* [Cluster update settings API spec](https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/api/cluster.get_settings.json)
* [Cluster update settings API doc](https://www.elastic.co/guide/en/elasticsearch/reference/7.3/cluster-update-settings.html)

### CODE REVIEW

**Review by jrodewig — CHANGES_REQUESTED** [review]
Although it's currently documented together and uses the same resources, I think we should split this one into **two** API pages:

* Get cluster settings
* Update cluster settings

We can model this off of the rollup jobs APIs:
* https://www.elastic.co/guide/en/elasticsearch/reference/master/rollup-put-job.html
* https://www.elastic.co/guide/en/elasticsearch/reference/master/rollup-get-job.html

**Comment by szabosteve** [comment]
@jrodewig https://github.com/elastic/elasticsearch/pull/45337/commits/e6f59dd5d49c8949e39d42d203ba018766a93993 addresses your feedback.

**Comment by jrodewig** [comment]
@szabosteve  This looks good.

We need to add the new `update-settings.asciidoc` file to `cluster.asciidoc` so it'll show up in the nav.

**Comment by szabosteve** [comment]
@jrodewig Both `update-settings.asciidoc` and `get-settings.asciidoc` have been already added to `cluster.asciidoc` and they are shown in the nav.

**Review by jrodewig — APPROVED** [review]
LGTM. Thanks @szabosteve.

**Comment by szabosteve** [comment]
Backported to 7.x and 7.3.

**Pull request merged**
