### PR TITLE
Upgrade to Jackson 2.5.1

### PR DESCRIPTION
**Pull request by s1monw**

### CODE REVIEW

**Comment by rjernst** [comment]
LGTM

**Comment by s1monw** [comment]
I did get some test failures with this.. need to look more into it

**Comment by kimchy** [comment]
I suggest we get #10026 in for latest 2.4 version with better cbor support, I can then look into the jackson upgrade for 2.5 if nobody picks it up

**Comment by kimchy** [comment]
seems like we have places where we don't call "startObject" before adding fields, and 2.5 is not lenient around it (which is great!). Will try and chase those up.

**Comment by kimchy** [comment]
I create a pull request fixing it where applicable, closing in favor of #10210

**Comment by s1monw** [comment]
thx @kimchy

**Pull request closed without merging**
