### PR TITLE
[DOCS] Fix typo in nodes stats docs

### PR DESCRIPTION
**Pull request by Bubba74**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by jrodewig** [comment]
Thanks for catching this @Bubba74. Could you please sign the CLA:

https://www.elastic.co/contributor-agreement

A signed CLA is required before we can merge this change. You must sign the CLA using the email address associated with your commit. You can find that email address here:

https://github.com/elastic/elasticsearch/commit/d35a352712a9452d125741e2659fe4377c373052.patch

After that's signed, I'll merge this change in. Thanks again!

**Comment by Bubba74** [comment]
Signed.

**Review by jrodewig — APPROVED** [review]
LGTM. Thanks @Bubba74

**Comment by jrodewig** [comment]
@elasticmachine test this please

**Pull request merged**
