### PR TITLE
Require JDK 11 for compilation

### PR DESCRIPTION
**Pull request by jasontedor**
Now that JDK 11 is GA, we would switch our 6.x and master branches to the JDK 11 compiler. This commit makes this change, as well as removes JDK 10 from the CI configuration.

### CODE REVIEW

**Comment by jasontedor** [comment]
@elasticmachine run gradle build tests

**Review by alpar-t — APPROVED** [review]
LGTM. We'll also have to remove the additional JDK11 compile step from the PR checks as it no longer makes sense to have it with this change.

**Comment by jasontedor** [comment]
@elasticmachine run gradle build tests

**Comment by danielmitterdorfer** [comment]
> I'm no lawyer, but if this is true - is Elastic's advice of not using OpenJDK will still be in effect post this PR?

I don't understand? In our [docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/setup.html#jvm-version) we state:

> Elasticsearch is built using Java, and requires at least Java 8 in order to run. Only Oracle’s Java and the OpenJDK are supported.

Which of those is more appropriate for you is up to you to decide. So if you want to have commercial support for Java you can use Oracle JDK but Elasticsearch does not force you to do that?

> On that note, what is the reason for upgrading to JDK 11 as soon as it's GA?

As you noted correctly, this is only about compiling Elasticsearch. You can still run it with Java 8.

**Pull request merged**
