### PR TITLE
[DOCS] Fix double-slash in link

### PR DESCRIPTION
**Pull request by jrodewig**
**Problem:** The [Watching the status of an Elasticsearch cluster](https://www.elastic.co/guide/en/elasticsearch/reference/8.9/watch-cluster-status.html) page contains a broken link to the Cluster Health API.

**Solution:** Fix the link.

Closes https://github.com/elastic/platform-docs-team/issues/195

### CODE REVIEW

**Review by kilfoyle — APPROVED** [review]
LGTM!

**Comment by jrodewig** [comment]
@elasticsearchmachine run elasticsearch-ci/packaging-tests-unix-sample

**Comment by jrodewig** [comment]
@elasticsearchmachine update branch

**Comment by jrodewig** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.10|[](https://github.com/elastic/elasticsearch/pull/99242)|
|✅|8.9|[](https://github.com/elastic/elasticsearch/pull/99243)|
|✅|7.17|[](https://github.com/elastic/elasticsearch/pull/99244)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
