### PR TITLE
[doc] Reorganize and clean Java documentation

### LINKED ISSUE #7826: Docs: java add missing queries / filters
Since 1.0, new queries and filters has been added to elasticsearch but were not documented in Java guide:

Queries:

* commonTerms
* functionScoreQuery
* simpleQueryString
* regexpQuery
* spanMultiTermQueryBuilder
* TemplateQueryBuilder

Filters:

* geoHashCellFilter
* regexpFilter

### PR DESCRIPTION
**Pull request by dadoonet**
This commit reorganizes the docs to make Java API docs looking more like the REST docs.
Also, with 2.0.0, FilterBuilders don't exist anymore but only QueryBuilders.
## Remove removed queries/filters
- Remove Constant Score Query with filter
- Remove Fuzzy Like This (Field) Query (flt and flt_field)
- Remove FilterBuilders
## Move filters to queries
- Move And Filter to And Query
- Move Bool Filter to Bool Query
- Move Exists Filter to Exists Query
- Move Geo Bounding Box Filter to Geo Bounding Box Query
- Move Geo Distance Filter to Geo Distance Query
- Move Geo Distance Range Filter to Geo Distance Range Query
- Move Geo Polygon Filter to Geo Polygon Query
- Move Geo Shape Filter to Geo Shape Query
- Move Has Child Filter by Has Child Query
- Move Has Parent Filter by Has Parent Query
- Move Ids Filter by Ids Query
- Move Limit Filter to Limit Query
- Move MatchAll Filter to MatchAll Query
- Move Missing Filter to Missing Query
- Move Nested Filter to Nested Query
- Move Not Filter to Not Query
- Move Or Filter to Or Query
- Move Range Filter to Range Query
- Move Ids Filter to Ids Query
- Move Term Filter to Term Query
- Move Terms Filter to Terms Query
- Move Type Filter to Type Query
## Add missing queries
- Add Common Terms Query
- Add Filtered Query
- Add Function Score Query
- Add Geohash Cell Query
- Add Regexp Query
- Add Script Query
- Add Simple Query String Query
- Add Span Containing Query
- Add Span Multi Term Query
- Add Span Within Query
## Reorganize the documentation
- Organize by full text queries
- Organize by term level queries
- Organize by compound queries
- Organize by joining queries
- Organize by geo queries
- Organize by specialized queries
- Organize by span queries
- Move Boosting Query
- Move DisMax Query
- Move Fuzzy Query
- Move Indices Query
- Move Match Query
- Move Mlt Query
- Move Multi Match Query
- Move Prefix Query
- Move Query String Query
- Move Span First Query
- Move Span Near Query
- Move Span Not Query
- Move Span Or Query
- Move Span Term Query
- Move Template Query
- Move Wildcard Query

Also closes #7826
Related to https://github.com/elastic/elasticsearch/pull/11477#issuecomment-114745934

### CODE REVIEW

**Comment by dadoonet** [comment]
@clintongormley WIP here. I just need to run the doc generation and check that everything is still ok.
In the mean time, could you tell me what you think about it?

Thanks!

**Comment by dadoonet** [comment]
@clintongormley I pushed a new change which fix errors while building docs. So it's now ready for review...

When I rendered html docs, I did not get the smart and cool menu you made for the REST doc. Could you tell me if I need to change something on my end?

**Comment by clintongormley** [comment]
> When I rendered html docs, I did not get the smart and cool menu you made for the REST doc. Could you tell me if I need to change something on my end?

You just need to build with `--open --web` to view it via a web server

I had a brief skim. In general looks good, although I'd make it a bit more structured, eg make Match All, Full text queries, Term level queries etc use `=== Header` instead of `== Header`.

Same thing could be done for Index, delete, get, update, bulk.

**Comment by dadoonet** [comment]
I meant that I get this:

term level queries google chrome aujourd hui at 15 35 03

 instead of this

queries google chrome aujourd hui at 15 35 18

Opening with `--open --web` gives the same result.

> I'd make it a bit more structured

Ok. Will update. Thanks!

**Comment by dadoonet** [comment]
@clintongormley I think it's ok now in term of layout. Thanks for the comment. It's more readable now.
May be you could then check how to render a tree menu as you did for the reference guide but for  the java guide?

@rjernst Wanna review the Java content itself?

**Comment by rjernst** [comment]
Java content looks fine to me. However, long term I think we should work towards having the client classes cleanly separated from the rest of the server, and making sure they are all documented, so that javadocs can be all the documentation we need for the java api.

**Comment by dadoonet** [comment]
You have no idea how much I agree with you!

**Comment by clintongormley** [comment]
@dadoonet ah ok - add `--chunk 1` when building.  You need to add that option here as well: https://github.com/elastic/docs/blob/master/conf.yaml#L136

LGTM

**Pull request merged**
