### PR TITLE
Include compiler options explicitly with building on aarch64 with clang

### LINKED ISSUE #108936: Performance regression in libvec on ARM
Seems there was an inadvertent issue with libvec.dylib (maybe Linux ARM too), between 1.0.6 and 1.08. Probably resulting from the build refactoring in #108088.

For example,

with 1.0.6, on my Mac M2  I see:
```
$ ./gradlew -p benchmarks run --args "org.elasticsearch.benchmark.vector.VectorScorerBenchmark.dotProductNative -p dims=1024"
...
VectorScorerBenchmark.dotProductNative    1024  thrpt    5  29.125 ± 0.683  ops/us
```

with 1.0.8:
```
VectorScorerBenchmark.dotProductNative    1024  thrpt    5  1.422 ± 0.015  ops/us
```

 Looks like the compiler is not using SIMD instructions.
```
objdump --disassemble-symbols=_dot7u libs/native/libraries/build/platform/darwin-aarch64/libvec.dylib 

libs/native/libraries/build/platform/darwin-aarch64/libvec.dylib:	file format mach-o arm64

Disassembly of section __TEXT,__text:

0000000000003570 <_dot7u>:
    3570: d100c3ff     	sub	sp, sp, #48
    3574: a9027bfd     	stp	x29, x30, [sp, #32]
    3578: 910083fd     	add	x29, sp, #32
    357c: f81f83a0     	stur	x0, [x29, #-8]
    3580: f9000be1     	str	x1, [sp, #16]
    3584: f90007e2     	str	x2, [sp, #8]
    3588: b90007ff     	str	wzr, [sp, #4]
    358c: b90003ff     	str	wzr, [sp]
    3590: f94007e8     	ldr	x8, [sp, #8]
    3594: f1008108     	subs	x8, x8, #32
    3598: 1a9f87e8     	cset	w8, ls
    359c: 370001a8     	tbnz	w8, #0, 0x35d0 <_dot7u+0x60>
    35a0: 14000001     	b	0x35a4 <_dot7u+0x34>
    35a4: f94007e8     	ldr	x8, [sp, #8]
    35a8: 927be909     	and	x9, x8, #0xffffffffffffffe0
    35ac: b98003e8     	ldrsw	x8, [sp]
    35b0: 8b090108     	add	x8, x8, x9
    35b4: b90003e8     	str	w8, [sp]
    35b8: f85f83a0     	ldur	x0, [x29, #-8]
    35bc: f9400be1     	ldr	x1, [sp, #16]
    35c0: b98003e2     	ldrsw	x2, [sp]
    35c4: 9400001d     	bl	0x3638 <_dot7u_inner>
    35c8: b90007e0     	str	w0, [sp, #4]
    35cc: 14000001     	b	0x35d0 <_dot7u+0x60>
    35d0: 14000001     	b	0x35d4 <_dot7u+0x64>
    35d4: b98003e8     	ldrsw	x8, [sp]
    35d8: f94007e9     	ldr	x9, [sp, #8]
    35dc: eb090108     	subs	x8, x8, x9
    35e0: 1a9f37e8     	cset	w8, hs
    35e4: 37000228     	tbnz	w8, #0, 0x3628 <_dot7u+0xb8>
    35e8: 14000001     	b	0x35ec <_dot7u+0x7c>
    35ec: f85f83a8     	ldur	x8, [x29, #-8]
    35f0: b98003e9     	ldrsw	x9, [sp]
    35f4: 38e96908     	ldrsb	w8, [x8, x9]
    35f8: f9400be9     	ldr	x9, [sp, #16]
    35fc: b98003ea     	ldrsw	x10, [sp]
    3600: 38ea6929     	ldrsb	w9, [x9, x10]
    3604: 1b097d09     	mul	w9, w8, w9
    3608: b94007e8     	ldr	w8, [sp, #4]
    360c: 0b090108     	add	w8, w8, w9
    3610: b90007e8     	str	w8, [sp, #4]
    3614: 14000001     	b	0x3618 <_dot7u+0xa8>
    3618: b94003e8     	ldr	w8, [sp]
    361c: 11000508     	add	w8, w8, #1
    3620: b90003e8     	str	w8, [sp]
    3624: 17ffffec     	b	0x35d4 <_dot7u+0x64>
    3628: b94007e0     	ldr	w0, [sp, #4]
    362c: a9427bfd     	ldp	x29, x30, [sp, #32]
    3630: 9100c3ff     	add	sp, sp, #48
    3634: d65f03c0     	ret
```

### PR DESCRIPTION
**Pull request by ChrisHegarty**
This commit Includes the compiler options explicitly with building on aarch64 with clang.

closes  #108936

### CODE REVIEW

**Comment by ChrisHegarty** [comment]
I can confirm that with this change the perf of the benchmark has been restored, e.g.

```
VectorScorerBenchmark.dotProductNative    1024  thrpt    5  28.798 ± 2.056  ops/us
```

**Review by ldematte — APPROVED** [review]
LGTM, thanks for the fix!

**Comment by ChrisHegarty** [comment]
@elasticmachine update branch

**Comment by ChrisHegarty** [comment]
@elasticmachine run elasticsearch-ci/bwc-snapshots

**Pull request merged**
