### PR TITLE
[HealthAPI] Use plural consistently in resource types

### PR DESCRIPTION
**Pull request by andreidan**

### CODE REVIEW

**Comment by andreidan** [comment]
@elasticmachine ok to test

**Review by gmarouli — APPROVED** [review]
Good catch!

**Comment by andreidan** [comment]
@elasticmachine update branch

**Comment by andreidan** [comment]
@elasticmachine ok to test

**Comment by andreidan** [comment]
@elasticsearchmachine  update branch

**Comment by andreidan** [comment]
@elasticmachine update branch

**Pull request merged**
