### PR TITLE
Add test for item-level error when no write index defined for an alias in bulk API

### LINKED ISSUE #54549: Inconsistent errors in bulk API
**Elasticsearch version** (`bin/elasticsearch --version`): 7.6.1

**Plugins installed**: []

**JVM version** (`java -version`): Elastic Cloud

**OS version** (`uname -a` if on a Unix-like system): Elastic Cloud

**Description of the problem including expected versus actual behavior**:

The bulk API may respond with errors per bulk request item, or it may fail the entire request, and it's unclear and undocumented when each might happen. The structure of bulk response for failed items is AFAICT completely undocumented. The only mention about the response structure I found [in the docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html) is:

> The response to a bulk action is a large JSON structure with the individual results of each action performed, in the same order as the actions that appeared in the request. The failure of a single action does not affect the remaining actions.

As an example of inconsistent behavior in this respect if I attempt to index a document into an index that does not exist (and automatic index creation is disabled) the bulk response will look like:

```json
{
    "took": 0,
    "errors": true,
    "items": [
        {
            "index": {
                "_index": "bar-4",
                "_type": "_doc",
                "_id": null,
                "status": 404,
                "error": {
                    "type": "index_not_found_exception",
                    "reason": "no such index [bar-4]",
                    "resource.type": "index_expression",
                    "resource.id": "bar-4",
                    "index_uuid": "_na_",
                    "index": "bar-4"
                }
            }
        }
    ]
}
```

however if I try to index into an alias that does not have a write alias defined I get an overall request failure, even though other bulk request items _could_ have been processed:

```
{
    "error": {
        "root_cause": [
            {
                "type": "illegal_argument_exception",
                "reason": "no write index is defined for alias [bar]. The write index may be explicitly disabled using is_write_index=false or the alias points to multiple indices without one being designated as a write index"
            }
        ],
        "type": "illegal_argument_exception",
        "reason": "no write index is defined for alias [bar]. The write index may be explicitly disabled using is_write_index=false or the alias points to multiple indices without one being designated as a write index"
    },
    "status": 400
}
```

I would expect missing "index not found" and "no write index for an alias" to be treated the same: the request would succeed, but the individual response item would show the failure. Both errors are predicated on server state. It contradicts the documentation that says a failure of a single action does not affect the remaining actions.

As a further example of inconsistency, consider when a mapping is `dynamic: strict`, and using the bulk API I attempt to index a field that is not in the mapping:

```json
{
    "took": 1,
    "errors": true,
    "items": [
        {
            "index": {
                "_index": "foo",
                "_type": "_doc",
                "_id": "zC4WM3EBVwMmsGyRIIsp",
                "status": 400,
                "error": {
                    "type": "strict_dynamic_mapping_exception",
                    "reason": "mapping set to strict, dynamic introduction of [otherfield] within [_doc] is not allowed"
                }
            }
        }
    ]
}
```

As part of this issue, can we:
1. Document the bulk API response object and expectations for when the entire request will fail
2. Make item-level errors consistent with documentation

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. `PUT /bar-1`
 2. `PUT /bar-2`
 3. Create an alias that points to two indices
   ```
   POST /_aliases
   {
     "actions": [
       { "add": { "index": "bar-1", "alias": "bar" } },
       { "add": { "index": "bar-2", "alias": "bar" } }
     ]
   }
   ```
4. Attempt to index a document using `bar` alias
   ```
   POST /_bulk
   { "create": { "_index": "bar" } }
   { "message": "hello, world" }
   ```

**Provide logs (if relevant)**:

### PR DESCRIPTION
**Pull request by gaobinlong**
Closes #54549.

When no write index defined for the alias used in bulk request, we get  an overall request failure but not an item-levle error.
The main changes are:
1. Catch the IllegalArgumentException and add a individual error in the response.
2. Add a yaml test for the change.

### CODE REVIEW

**Comment by gaobinlong** [comment]
@martijnvg ，can you help to review the change?

**Comment by jakelandis** [comment]
@gaobinlong thanks for the contribution (and sorry it has taken so long to get to review).  This certainly a reasonable PR and thank you for the associated test! I have marked this issue for further internal discussion, mostly to gauge others opinion on the exception type caught here. (i.e catch `IllegalArgumentException` vs. introduce a custom exception and catch that for the no write index case). There are other cases where `IllegalArgumentException` can be thrown as you mention this results in the difference between an overall failure and item level failure.

**Comment by jakelandis** [comment]
@elasticmachine ok to test

**Comment by jakelandis** [comment]
@gaobinlong - it looks like the primary change was already implemented, so all that is left here is the test.  I will get that merged in. Thanks for the contribution!

**Comment by jakelandis** [comment]
packaging-sample-windows failure is un-related, merging.

**Pull request merged**
