### PR TITLE
[7.17] Block specific config files from being read after startup

### PR DESCRIPTION
**Pull request by thecoop**
Backport #107481 to 7.17

`ESPolicy` has changed a bit, requiring some minor adaptions

### CODE REVIEW

**Comment by thecoop** [comment]
@elasticsarchmachine rerun ci buildkite/docs-build-pr

**Comment by thecoop** [comment]
@elasticsearchmachine rerun ci buildkite/docs-build-pr

**Comment by thecoop** [comment]
@elasticsearchmachine rerun buildkite/docs-build-pr

**Review by mosche — APPROVED** [review]
LGTM given that tests pass

**Pull request merged**
