### PR TITLE
Let OSX build rpms for linux

### LINKED ISSUE #12701: RPMs build on osx won't install on centos
```bash
[vagrant@localhost releases]$ sudo rpm -if elasticsearch-2.0.0-beta1-SNAPSHOT.rpm 
warning: elasticsearch-2.0.0-beta1-SNAPSHOT.rpm: Header V4 RSA/SHA1 Signature, key ID cd27c2b4: NOKEY
	package elasticsearch-2.0.0-beta1_SNAPSHOT20150806181247.noarch is intended for a different operating system
[vagrant@localhost releases]$ man rpm
[vagrant@localhost releases]$ sudo rpm -i --ignoreos elasticsearch-2.0.0-beta1-SNAPSHOT.rpm 
warning: elasticsearch-2.0.0-beta1-SNAPSHOT.rpm: Header V4 RSA/SHA1 Signature, key ID cd27c2b4: NOKEY
Creating elasticsearch group... OK
Creating elasticsearch user... OK
### NOT starting on installation, please execute the following statements to configure elasticsearch service to start automatically using systemd
 sudo systemctl daemon-reload
 sudo systemctl enable elasticsearch.service
### You can start elasticsearch service by executing
 sudo systemctl start elasticsearch.service
[vagrant@localhost releases]$ sudo service elasticsearch start
Starting elasticsearch (via systemctl):                    [  OK  ]
[vagrant@localhost releases]$ 
```

### PR DESCRIPTION
**Pull request by nik9000**
Closes #12701

### CODE REVIEW

**Comment by rmuir** [comment]
+1, make it platform independent.

**Comment by nik9000** [comment]
> +1, make it platform independent.

I think I declared the rpm to only work on linux.... But at least it'll build on osx. I don't know that that targetOS is anything but an inString comparison. My google-foo is failing me when I try to look that up because rpm just calls that field `os` but that appears on 12312325489134 pages about rpm already that have nothing to do with the field.

**Comment by clintongormley** [comment]
@nik9000 looks like your PR includes a few too many commits?

**Comment by nik9000** [comment]
> @nik9000 looks like your PR includes a few too many commits?

It didn't yesterday....

**Comment by nik9000** [comment]
> It didn't yesterday....

So fixed.

**Comment by nik9000** [comment]
Ping @spinscale  - I can't really test on my laptop without something like this.

**Comment by spinscale** [comment]
ok, tested this

on master (using centos7 VM)

```
# rpm -i /elasticsearch/distribution/rpm/target/releases/elasticsearch-2.0.0-beta1-SNAPSHOT.rpm
warning: /elasticsearch/distribution/rpm/target/releases/elasticsearch-2.0.0-beta1-SNAPSHOT.rpm: Header V4 RSA/SHA1 Signature, key ID e3038d9c: NOKEY
	package elasticsearch-2.0.0-beta1_SNAPSHOT20150810093838.noarch is intended for a different operating system
```

with this PR

```
asticsearch-2.0.0-beta1_SNAPSHOT20150810093838.noarch is intended for a different operating system
[root@localhost ~]# rpm -i /elasticsearch/distribution/rpm/target/releases/elasticsearch-2.0.0-beta1-SNAPSHOT.rpm
warning: /elasticsearch/distribution/rpm/target/releases/elasticsearch-2.0.0-beta1-SNAPSHOT.rpm: Header V4 RSA/SHA1 Signature, key ID 4e5bfbf2: NOKEY
Creating elasticsearch group... OK
Creating elasticsearch user... OK
### NOT starting on installation, please execute the following statements to configure elasticsearch service to start automatically using systemd
 sudo systemctl daemon-reload
 sudo systemctl enable elasticsearch.service
### You can start elasticsearch service by executing
 sudo systemctl start elasticsearch.service
```

Checking the arch and the OS of the RPM

```
rpm -qp --qf 'Arch:%{ARCH}\nOS:%{OS}\n'  distribution/rpm/target/releases/elasticsearch-2.0.0-beta1-SNAPSHOT.rpm
Arch:noarch
OS:linux
```

LGTM

**Comment by nik9000** [comment]
Rock on! Merging.

**Pull request merged**
