### PR TITLE
Exposed hit/miss counters on filter cache

### PR DESCRIPTION
**Pull request by favoretti**
Quick and dirty exposing of hit/miss counters on the filter caches. Comments/suggestions are welcome.

### CODE REVIEW

**Comment by favoretti** [comment]
CLA signed, re-opening PR didn't help CLA validation though..

**Comment by clintongormley** [comment]
Hi @favoretti 

You know the filter cache has been removed in 2.0?

**Comment by favoretti** [comment]
Yes sir. I do :) we are, however, running on 1.7 for now and hitting
interesting CPU sinks, hence just looking at the amount of evictions
doesn't really give insights in cache effectiveness. Exposing hit/miss
doesn't greatly enhance it either though, but gives a tad bit more to look
at.

**Comment by clintongormley** [comment]
@favoretti 1.7 is our last branch in the 1.x series, so only critical bug fixes will be considered for this branch I'm afraid.

If you need this locally, you'll have to either add it as a plugin or run a custom version.

thanks for the PR anyway!

**Pull request closed without merging**
