### PR TITLE
WIP - Make recovery source async

### PR DESCRIPTION
**Pull request by dnhatn**
I made this draft, so we have something to evaluate the async option. Since this PR is on top of #32512, please check out and review it locally or have a look at [the last commit](https://github.com/elastic/elasticsearch/commit/db26be331943a244528ad48ca00d7a403b2498dc). If we agree to proceed, I will break down this into smaller PRs.

### CODE REVIEW

**Review by DaveCTurner — COMMENTED** [review]
Seems like a nice approach. As in #37076 I'm unclear about whether we still need `CancellableThreads` here, but that doesn't need resolving right now.

**Comment by s1monw** [comment]
I think we should start step by step making things async. I don't necessarily understand why we depend this on the work on CompleteableFuture. I don't think we should use futures unless absolutely necessary and should use callbacks / listeners instead, consistently across the codebase. There are many things that I personally dislike about futures, the main issue here is that you need to be explicit on the return value and it's not obvious that the method is async. I would really like to prevent this and rather get rid of futures where we can.

**Review by s1monw — COMMENTED** [review]
see my comment above

**Comment by dnhatn** [comment]
> I think we should start step by step making things async.

Yes, that's my plan if we agree to make recovery async.

> I don't necessarily understand why we depend this on the work on CompleteableFuture. I don't think we should use futures unless absolutely necessary and should use callbacks / listeners instead, consistently across the codebase.

Sure, I will use listeners for this. With CompleteableFuture, the flow of the async code is somehow similar to the sequential flow. That's the only reason I prefer CompleteableFuture over callback.

**Pull request closed without merging**
