### PR TITLE
Use default methods in Client

### PR DESCRIPTION
**Pull request by obourgain**
Use default methods in Client instead of dumb overrides in AbstractClient.
If there is interest in this PR, I can do the same for ClusterAdminClient and IndicesAdminClient.

This would remove a lot of code from AbstractClient, that was close to 1800 lines and move this code to several interfaces.
Also, it also may become easier to implement Client because you would need to implement a lot less methods

### CODE REVIEW

**Comment by jasontedor** [comment]
I'm not sure if we should do this, this assumes behavior on all `Client` implementations (which exist outside of core elasticsearch). `AbstractClient`, though, is exactly for those that do want the behavior here.

**Comment by javanna** [comment]
Is there anywhere a `Client` implementation that doesn't subclass `AbstractClient` as well? I cannot think of any, which makes me think this change is ok. Probably if java had default methods in the first place we would have used them from the beginning?

**Comment by jasontedor** [comment]
@javanna There exist [implementations](https://github.com/jprante/elasticsearch-server/blob/7a1e5da71b36ae2bc50eef9c7a34707300466155/elasticsearch-server-node/src/main/java/org/elasticsearch/client/support/DecoratingClient.java) outside of core Elasticsearch. I  think this is the wrong use of `default`.

**Comment by obourgain** [comment]
I am still not sure my PR is of interest, because on one hand, the current status makes it mandatory for third party implementations to do new versions to follow ES versions adding/removing method, with the risk of fragmenting the ecosystem if some people are stuck with older ES version or with forked and not maintained libs. On the other hand, default methods may cause those implementations to miss new methods 

If you think it is a bad idea, fee free to close it.

**Comment by jasontedor** [comment]
> On the other hand, default methods may cause those implementations to miss new methods

Yes, that is exactly my concern which I tried to express in my first [comment](https://github.com/elastic/elasticsearch/pull/18468#issuecomment-220391312).

> If you think it is a bad idea, feel free to close the PR.

I do not think that it's a bad idea, just one that requires care and caution. We truly welcome the PRs, please keep them coming! :smile:

**Comment by javanna** [comment]
thanks for the link @jasontedor I was not aware of that implementation.

**Comment by khatchad** [comment]
@javanna Out of curiosity, did you perform this refactoring manually or via an automated refactoring tool?

**Comment by obourgain** [comment]
I did it by hand, with a few shortcuts from the IDE

**Comment by khatchad** [comment]
Thanks, @javanna!

On Thu, Jun 30, 2016 at 09:31:48AM -0700, Olivier Bourgain wrote:
> I did it by hand, with a few shortcuts from the IDE
> Le 30 juin 2016 5:31 PM, "Raffi Khatchadourian" <notifications@github.com>
> a écrit :
> 
> > @javanna <https://github.com/javanna> Out of curiosity, did you perform
> > this refactoring manually or via an automated refactoring tool?
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/elastic/elasticsearch/pull/18468#issuecomment-229694522>,
> > or mute the thread
> > <https://github.com/notifications/unsubscribe/
> AA7j0rUjdvRZxfnDOlCfpAxcbmuoUGIPks5qQ-B3gaJpZM4IibpG>
> > .
> >
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.*
> 

-- 
Raffi Khatchadourian, PhD
Assistant Professor and Open Educational Resources (OER) Fellow
Computer Systems Technology
New York City College of Technology
City University of New York
300 Jay St., Room N913
Brooklyn, NY 11201-1909
United States
+1 (718) 260-5325
rkhatchadourian@citytech.cuny.edu
http://cuny.is/khatchad

**Comment by obourgain** [comment]
i am not @javanna ;)

**Comment by khatchad** [comment]
@obourgain Oh sorry about that! The mentions are a bit difficult to do via email.

**Pull request closed without merging**
