### PR TITLE
[Test] Bump password length to meet FIPS requirement

### LINKED ISSUE #74641: Elasticsearch-users CLI tool results in error when run with FIPS enabled
Looks like tests that depend on setting up a user fail with FIPS enabled because of an error thrown by the `elasticsearch-users` CLI tool.

**Build scan**:
https://gradle-enterprise.elastic.co/s/5qs3ehfyskhf4/console-log?task=:qa:system-indices:javaRestTest

**Repro line**:
I suspect just try running the CLI tool directly to repro this.

**Reproduces locally?**:
Didn't try.

**Applicable branches**:
master

**Failure excerpt**:
```
:qa:system-indices:javaRestTest FAILED
Exec output and error:
| Output for ./bin/elasticsearch-users:ERROR: Error storing the password for the new user
```

### PR DESCRIPTION
**Pull request by ywangd**
Resolves: #74641

### CODE REVIEW

**Comment by ywangd** [comment]
@elasticmachine update branch

**Comment by ywangd** [comment]
The `elasticsearch-ci/part-2-fips` is having a different failure and I raised https://github.com/elastic/elasticsearch/issues/74664

I believe this PR has fixed the original problem it tried to address. But its merge is now blocked by this new failure.

**Review by jkakavas — APPROVED** [review]

**Comment by jkakavas** [comment]
https://github.com/elastic/elasticsearch/issues/66840 would have helped with master but this would have failed in 7.x on backport

**Comment by ywangd** [comment]
@elasticmachine update branch

**Comment by ywangd** [comment]
FIPS failures are due to configuration issue. We agreed to not let them block merges for the time being.

**Pull request merged**
