### PR TITLE
Reset registeredNextDelaySetting on reroute

### PR DESCRIPTION
**Pull request by kimchy**
Need to reset the registered setting in order to make sure the nex round will capture the right delay interval

### CODE REVIEW

**Comment by s1monw** [comment]
can there be race in between updating and checking this setting? I guess not though just double checking...

**Comment by kimchy** [comment]
yea, I was thinking about that :), I don't think so, it follows "happens before" like semantics, so its conservative and makes sure to reset it before reroute happens (which will trigger the next callback afterwards if there are still delayed unassigned)

**Comment by s1monw** [comment]
fair enough... I will likely look at this logic again, it's too complicated ATM IMO and need to be simplified eventually IMO but lets move forward here

**Comment by kimchy** [comment]
cool, @s1monw I pushed another small change, to make sure we randomize this setting, and that we name it properly in our constant, looks good?

**Comment by s1monw** [comment]
LGTM

**Comment by kimchy** [comment]
thanks!, I am also working on simplifying RoutingService and writing unit tests for it, just keep finding stuff along the way...

**Comment by bleskes** [comment]
Late to the party but LGTM. Good catch

**Pull request closed without merging**
