### PR TITLE
Refactor SnapshotsInProgress to Use RepositoryId for Concurency Logic

### LINKED ISSUE #75423: AssertionError: Missing assignment for [[index-0][4]] during snapshot
**Elasticsearch version** (`bin/elasticsearch --version`): https://github.com/DaveCTurner/elasticsearch/tree/2021-07-16-snapshot-finalization-order-testing-WIP which includes #75362 plus some extra stress tests.

After many iterations of `SnapshotStressTestsIT` on the linked branch we tripped an assertion in `SnapshotsService$RemoveSnapshotDeletionAndContinueTask`, see below.

**Provide logs (if relevant)**:

```
        java.lang.AssertionError: Missing assignment for [[index-0][4]]
            at __randomizedtesting.SeedInfo.seed([A599955E699077CA]:0)
            at org.elasticsearch.snapshots.SnapshotsService$RemoveSnapshotDeletionAndContinueTask.updatedSnapshotsInProgress(SnapshotsService.java:2662)
            at org.elasticsearch.snapshots.SnapshotsService$RemoveSnapshotDeletionAndContinueTask.execute(SnapshotsService.java:2502)
            at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:48)
            at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:701)
            at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:323)
            at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:218)
            at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:155)
            at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:139)
            at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:177)
            at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:678)
            at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:259)
            at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:222)
            at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
            at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
            at java.base/java.lang.Thread.run(Thread.java:831)
```

[testoutput-1626444817.tar.gz](https://github.com/elastic/elasticsearch/files/6831375/testoutput-1626444817.tar.gz)

### PR DESCRIPTION
**Pull request by original-brownbear**
This refactors the snapshots-in-progress logic to work from `RepositoryShardId` when working out what parts of the repository are in-use by writes for snapshot concurrency safety. This change does not go all the way yet on this topic and there are a number of possible follow-up further improvements to simplify the logic that I'd work through over time.
But for now this allows fixing the remaining known issues that snapshot stress testing surfaced when combined with the fix in https://github.com/elastic/elasticsearch/pull/75530.

These issues all come from the fact that `ShardId` is not a stable key across multiple snapshots if snapshots are partial. The scenarios that are broken are all roughly this:
* snapshot-1 for index-A with uuid-A runs and is partial
* index-A is deleted and re-created and now has uuid-B
* snapshot-2 for index-A is started and we now have it queued up behind snapshot-1 for the index
* snapshot-1 finishes and the logic tries to start the next snapshot for the same shard-id
  * this fails because the shard-id is not the same, we can't compare index uuids, just index name + shard id
  * this change fixes all these spots by always taking the round trip via `RepositoryShardId`
 
planned follow-ups here are:
* dry up logic across cloning and snapshotting more as both now essentially run the same code in many state-machine steps
* serialize snapshots-in-progress efficiently instead of re-computing the index and by-repository-shard-id lookups in the constructor every time
    * refactor the logic in snapshots-in-progress away from maps keyed by shard-id in almost all spots to this end, just keep an index name to `Index` map to work out what exactly is being snapshotted
 * refactoring snapshots-in-progress to be a map of list of operations keyed by repository shard id instead of a list of maps as it currently is to make the concurrency simpler and more obviously correct

closes #75423 

relates (#75339 ... should also fix this, but I have to verify by testing with a backport to 7.x)

### CODE REVIEW

**Comment by DaveCTurner** [comment]
I rebased the stress tests on top of this branch, see  3ea18f80f99ec5f420e8f91f921d9eb0a862c850, and I still got the same `Missing assignment` assertion to trip 😢 

[testoutput-1626863771.tar.gz](https://github.com/elastic/elasticsearch/files/6854928/testoutput-1626863771.tar.gz)

**Comment by original-brownbear** [comment]
@DaveCTurner that one should be fixed by https://github.com/elastic/elasticsearch/pull/75530 I believe. The index lookup there is broken and incorrectly interprets a re-created index with changed UUID as a deleted index still existing.

**Comment by DaveCTurner** [comment]
Hmm I merged #75530 into my branch, see 8fe45fa32f15a0687a3522d7dde38a2e60d97c9d, and still the `Missing assignment` assertion trips:

[testoutput-1626866221.tar.gz](https://github.com/elastic/elasticsearch/files/6855161/testoutput-1626866221.tar.gz)

**Comment by original-brownbear** [comment]
The above was caused by 064f45a06c1.

Also I unfortunately found  https://github.com/elastic/elasticsearch/issues/75598 as a result of going through this

**Comment by original-brownbear** [comment]
@DaveCTurner to me it looks like this branch fixes the stress test now with the recent changes to master merged in. I couldn't reproduce any failures that didn't seem to be issues with the test (trying to clone indices that weren't successfully snapshotted).
Maybe take a look when you have a chance :)? This PR would be the minimal changset that I can see that would deal with the various issues around index uuids changing across snapshots but there's more cleanup planned to this code. We really should get away from the list of maps data structure we're currently using to make it obvious what operation touches what shard at any point without doing a bunch of looping to figure it out.

**Review by DaveCTurner — APPROVED** [review]
Sure, this LGTM (and to a fixed version of the stress tests too it seems)

**Comment by original-brownbear** [comment]
Thanks David!

**Pull request merged**
