### PR TITLE
Use standard bit set impl in cardinality

### PR DESCRIPTION
**Pull request by nik9000**
This replaces a specialized bit set implementation used in cardinality
with our standard `BitArray` which works exactly the same way. Its also
tracked by `BigArrays` which is great!

### CODE REVIEW

**Comment by nik9000** [comment]
run elasticsearch-ci/2

**Review by iverase — COMMENTED** [review]
I like the change but I am not happy with the ceremony of checking the range on the BucketOrds. 

I had a look into the usage of BitArray and it seems we have a similar ceremony in `TopMetricsAggregator`. The situation is worst in `BucketedSort` and `ParentJoinAggregator` where we are doing a blind cast.

On the other hand there are other usages like in `LongValuesSource` where working on int make sense. I wonder if we should introduce a  `BigBitArray` that works on long and avoid this ceremony?

We can do that in a follow up PR.

**Comment by nik9000** [comment]
I was thinking about that! I believe all of the usages would prefer we
support longs. At least, all of the important usages. I'll have a look.

**Comment by nik9000** [comment]
@iverase I've updated this one now that we support longs. We may not need it at all given what we talked about this morning. But if you think we do I'd be happy to merge it.

**Review by iverase — APPROVED** [review]
We might still need it, lets merge it from now as it is an improvement of what we have now.

LGTM

**Comment by nik9000** [comment]
Thanks @iverase !

**Pull request merged**
