### PR TITLE
Remove Strings#splitStringToArray

### PR DESCRIPTION
**Pull request by jasontedor**
This commit removes the method `Strings#splitStringToArray` and replaces
the call sites with invocations to `String#split`. There are only two
explanations for the existence of this method. The first is that
String#split is slightly tricky in that it accepts a regular expression
rather than a character to split on. This means that if `s` is a string,
`s.split(".")`  does not split on the character '.', but rather splits on
the regular expression '.' which splits on every character (of course,
this is easily fixed by invoking `s.split("\\.")` instead). The second
possible explanation is that (again) `String#split` accepts a regular
expression. This means that there could be a performance concern
compared to just splitting on a single character. However, it turns out
that `String#split` has a fast path for the case of splitting on a single
character and microbenchmarks show that `String#split` has 1.5x--2x the
throughput of `Strings#splitStringToArray`. There is a slight behavior
difference between `Strings#splitStringToArray` and `String#split`: namely,
the former would return an empty array in cases when the input string
was null or empty but `String#split` will just NPE at the call site on
null and return a one-element array containing the empty string when the
input string is empty. There was only one place relying on this behavior
and the call site has been modified accordingly.

### CODE REVIEW

**Comment by jpountz** [comment]
This is great! LGTM.

**Comment by nik9000** [comment]
This might also have had something to do with removing empty strings caused by repetitions of the split character. It looks like `splitStringToArray` didn't add them to the array and I'm pretty sure `String#split` does. This isn't an objection to doing this. It is just worth looking into.

**Comment by jasontedor** [comment]
> This might also have had something to do with removing empty strings caused by repetitions of the split character. It looks like `splitStringToArray` didn't add them to the array and I'm pretty sure `String#split` does.

If that's the case we were either not testing for it or not relying on it, but I will investigate carefully before merging.

**Comment by jasontedor** [comment]
@jpountz @nik9000 Because of the behavior that @nik9000 mentioned, today this is legal:

```bash
$ curl -XGET localhost:9200/i//t/1 -d '{"f":"v"}'
```

Note the double '/' between the index and type names.

With this change, this is no longer legal:

```bash
$ curl -XGET localhost:9200/i//t/1 -d '{"f":"v"}'
No handler found for uri [/i//t/1?pretty=1] and method [POST]
```

This behavior appears to be undocumented and is definitely untested. I think it's okay to proceed with the PR as is, but what do you think?

**Comment by nik9000** [comment]
> Note the double '/' between the index and type names.

Eep. Those double path separators is just the kind of thing someone is going to accidentally rely on. I think we should continue with your change, but maybe add something to the breaking changes doc?

**Comment by jpountz** [comment]
I know we have been doing it in the past, but maybe we have been too far with documenting this kind of things as breaking changes. Then it looks like everything broke backward compatibility when it is only really about catching user errors.

**Comment by jasontedor** [comment]
> I know we have been doing it in the past, but maybe we have been too far with documenting this kind of things as breaking changes.

+1

**Comment by jasontedor** [comment]
While investigating @nik9000's observation, I did notice one thing about `PathTrie` that bothered me. Namely, we have a constructor that is only used internally that allows for arbitrary separator/wildcard pairs but it is unused and not tested. I removed it. Do you take a look at 9fe5ce934279a274abdf67b417aae8d1566cde63 @jpountz and @nik9000?

**Comment by nik9000** [comment]
LGTM

**Comment by jpountz** [comment]
This commit looks good to me.

**Pull request merged**
