### PR TITLE
Provides a response body for _enable, _disable

### PR DESCRIPTION
**Pull request by auspicacious**
Partial implementation of https://github.com/elastic/elasticsearch/issues/29738

I'm fairly new to the Elastic stack and I decided to make a first attempt at this issue in order to get some insight into how the API is implemented. I've added a new field to the response, which now looks like this `{ "enabled": true }`

This in itself isn't particularly useful and I wonder if the requester had something more in mind, for instance, indicating whether this action actually changed the state?

I have run `gradlew precommit` and have specifically run the test that I modified; however, when I tried to run the complete Elasticsearch test suite I can't seem to get past a failure in the `server` module, and when I specifically ran `:x-pack:plugin:security:test` my system ran out of memory. I'm not exactly sure which other tests should be updated or whether the changes already made are sufficient to make the docs re-render with the new response.

Some other questions that I have thought about along the way: should a corresponding change be made in other clients? Will modifying the binary response format break clients? Would it be better to go deeper into `usersStore` to get back a value in `onResponse`?

Thank you.

### CODE REVIEW

**Comment by gwbrown** [comment]
@elasticmachine test this please

**Comment by ywangd** [comment]
@elasticmachine update branch

**Comment by ywangd** [comment]
@elasticmachine test this please

**Comment by tvernum** [comment]
@ywangd Are you able to take on this PR and see if we can get something merged?

**Comment by ywangd** [comment]
Hi @auspicacious Thanks for raising this PR. It took us quite a while to get to it. The codebase has evovled quite a log since last year and the PR needs to be updated to match the current state first.
Are you still interested in working on this? Please let me know and I will provide further reviews if you are still up for it. Thanks!

**Comment by auspicacious** [comment]
@ywangd Thanks for asking, I appreciate it. I don't think that I can put the necessary time into it right now, however, if this code is useful to you, please feel free to take it and use it. I'll close the PR for now.

**Pull request closed without merging**
