### PR TITLE
Remove the index thread pool

### PR DESCRIPTION
**Pull request by jasontedor**
Now that single-document indexing requests are executed on the bulk thread pool the index thread pool is no longer needed. This commit removes this thread pool from Elasticsearch.

### CODE REVIEW

**Comment by jpountz** [comment]
Should we rename `bulk` to `index` at the same time? I think this would be a better name for this threadpool?

**Comment by jasontedor** [comment]
@jpountz I was thinking something similar last nightexcept renaming it to the `write` thread pool. What do you think?

**Comment by jpountz** [comment]
:+1: I had done something similar at https://github.com/elastic/elasticsearch/pull/12939/files#diff-28405cdd8e4973b90f711084352459be. It also merged the get and search threadpools into a `read` threadpool.

**Comment by nik9000** [comment]
> I was thinking something similar last night except renaming it to the write thread pool. What do you think?

Maybe it makes sense to do it in a follow up?

**Review by nik9000 — APPROVED** [review]
Makes sense to me.

**Comment by jasontedor** [comment]
> Maybe it makes sense to do it in a follow up?

I already have a change queued locally ready to go in a follow-up once this PR is in. :innocent:

**Pull request merged**
