### PR TITLE
[DOCS] Split common cluster issues page into separate pages

### LINKED ISSUE #85610: [DOCS] Split the page Fix common cluster issues into separate pages
The page [Fix common cluster issues](https://www.elastic.co/guide/en/elasticsearch//reference/master/fix-common-cluster-issues.html) is one of the [troubleshooting links](https://github.com/elastic/cloud/issues/92183#issuecomment-1017303716) that are going to be created on the deployment health banner to link error messages to relevant doc pages.

This page is too long and requires lots of scrolling. We can get a better user experience if we:
- link from the UI to the specific sections of this page
or
- split the page into separate pages (better for SEO)

CC @debadair 

Relates to https://github.com/elastic/cloud/issues/92183

### PR DESCRIPTION
**Pull request by abdonpijpelink**
Closes #85610

### CODE REVIEW

**Comment by debadair** [comment]
@elasticmachine run elasticsearch-ci/docs rebuild

**Comment by debadair** [comment]
The build is failing because of a link from the Kibana docs that linked to one of the headings on the common cluster issues page. It should be updated to link to the new standalone page. To get clean builds before merging, you'll have to update the Kibana page twice. Change it to link to the top of the common clusters page, merge this PR, and then update the Kibana page to link to the new page.

**Review by debadair — APPROVED** [review]
There's a "chicken-and-egg" issue with the cross-doc link from Kibana that's causing the build to fail, but otherwise these changes look good.

**Comment by abdonpijpelink** [comment]
@elasticmachine run elasticsearch-ci/docs rebuild

**Comment by lockewritesdocs** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.3|[](https://github.com/elastic/elasticsearch/pull/88612)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
