### PR TITLE
Ensure plugin class scanner always closes its directory stream

### LINKED ISSUE #93005: [CI] ClassReadersTests classMethod failing
Maybe related to: https://github.com/elastic/elasticsearch/issues/92936

**Build scan:**
https://gradle-enterprise.elastic.co/s/xnay2gtnbk67u/tests/:libs:elasticsearch-plugin-scanner:test/org.elasticsearch.plugin.scanner.ClassReadersTests

**Reproduction line:**
```
./gradlew ':libs:elasticsearch-plugin-scanner:test' --tests "org.elasticsearch.plugin.scanner.ClassReadersTests" -Dtests.seed=62A93F3353484C1B -Dtests.locale=en-US -Dtests.timezone=Atlantic/Reykjavik -Druntime.java=19
```

**Applicable branches:**
8.6, main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.plugin.scanner.ClassReadersTests&tests.test=classMethod

**Failure excerpt:**
```
java.io.IOException: Could not remove the following files (in the order of attempts):
   C:\Users\jenkins\workspace\platform-support\125\libs\plugin-scanner\build\testrun\test\temp\org.elasticsearch.plugin.scanner.ClassReadersTests_62A93F3353484C1B-001\tempDir-003: java.nio.file.DirectoryNotEmptyException: C:\Users\jenkins\workspace\platform-support\125\libs\plugin-scanner\build\testrun\test\temp\org.elasticsearch.plugin.scanner.ClassReadersTests_62A93F3353484C1B-001\tempDir-003
   C:\Users\jenkins\workspace\platform-support\125\libs\plugin-scanner\build\testrun\test\temp\org.elasticsearch.plugin.scanner.ClassReadersTests_62A93F3353484C1B-001\tempDir-003\jars-dir: java.nio.file.AccessDeniedException: C:\Users\jenkins\workspace\platform-support\125\libs\plugin-scanner\build\testrun\test\temp\org.elasticsearch.plugin.scanner.ClassReadersTests_62A93F3353484C1B-001\tempDir-003\jars-dir
   C:\Users\jenkins\workspace\platform-support\125\libs\plugin-scanner\build\testrun\test\temp\org.elasticsearch.plugin.scanner.ClassReadersTests_62A93F3353484C1B-001: java.nio.file.DirectoryNotEmptyException: C:\Users\jenkins\workspace\platform-support\125\libs\plugin-scanner\build\testrun\test\temp\org.elasticsearch.plugin.scanner.ClassReadersTests_62A93F3353484C1B-001

  at __randomizedtesting.SeedInfo.seed([62A93F3353484C1B]:0)
  at org.apache.lucene.util.IOUtils.rm(IOUtils.java:341)
  at org.apache.lucene.tests.util.TestRuleTemporaryFilesCleanup.afterAlways(TestRuleTemporaryFilesCleanup.java:209)
  at com.carrotsearch.randomizedtesting.rules.TestRuleAdapter$1.afterAlways(TestRuleAdapter.java:31)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1589)

```

### PR DESCRIPTION
**Pull request by ChrisHegarty**
Ensure directory stream is closed. (another instance of #92890)

Additionally, use the test name in the temporary directory, which helps with failure diagnosis.

closes #93005

### CODE REVIEW

**Review by thecoop — APPROVED** [review]
Good find

**Review by pgomulka — APPROVED** [review]
LGTM, thank you

**Comment by ChrisHegarty** [comment]
@elasticmachine run elasticsearch-ci/part-1-windows

**Comment by pgomulka** [comment]
@elasticmachine run elasticsearch-ci/part-1-windows

**Comment by ChrisHegarty** [comment]
The CI is running into a different test failure in elasticsearch-ci/part-1-windows. Going to merge this PR - since local Windows testing has been successful.

**Pull request merged**
