### PR TITLE
Throw error when create is used with  external

### PR DESCRIPTION
**Pull request by ivange94**
op_type create should only be used with version_type
external

Closes #37855

### CODE REVIEW

**Comment by ivange94** [comment]
I have not added unit tests yet. This is only because I'm not able to run unit tests from InteliJ. When I try to run ReindexRequestTests I get a build error. 

screen shot 2019-01-26 at 1 43 54 pm

**Comment by ivange94** [comment]
@ywelsch sorry for my delayed response on this. Not been on my laptop for a while now. 

I was finally able to run ReindexRequestTests. Not sure what fixed it but before doing that I first ran a test in the server module which succeeded then running ReindexRequestTests succeeded too so I'm not sure if that was the fix but I'm moving ahead with the issue

**Comment by ivange94** [comment]
@ywelsch I've added test for this. Patiently awaiting your review 😄

**Comment by ivange94** [comment]
@ywelsch seeing that you just pushed a commit that fixes this. Should I close this PR?

**Comment by ywelsch** [comment]
I'm exploring a more generic solution in https://github.com/elastic/elasticsearch/pull/38504, taking into account some of the other version-based checks as well (so that we can avoid problems like this in the future), and dealing with the very recent changes around compare-and-set style versioning. I'm not sure yet whether that solution all works out, so let's keep this one open until I complete #38504.

**Comment by ywelsch** [comment]
@ivange94 unfortunately the solution explored in #38504 did not work. Can you merge latest master into this branch and I will trigger a CI run.

**Comment by ivange94** [comment]
> Can you merge latest master into this branch

Done

**Comment by ywelsch** [comment]
@elasticmachine test this please

**Comment by ivange94** [comment]
@ywelsch I'm not sure why the two builds above are failing.

**Comment by ywelsch** [comment]
@elasticmachine test this please

**Comment by ywelsch** [comment]
I've merged latest master into your branch, which will hopefully fix the CI issue

**Comment by ywelsch** [comment]
This looks to be a relevant test failures:

> ERROR   0.32s | CRUDDocumentationIT.testReindex <<< FAILURES!
   > Throwable #1: org.elasticsearch.action.ActionRequestValidationException: Validation Failed: 1: create operations only support internal versioning. use index instead;
   > 	at __randomizedtesting.SeedInfo.seed([B4C3EF6C5B9EEEAC:27B9B180D9CB54FE]:0)
   > 	at org.elasticsearch.action.ValidateActions.addValidationError(ValidateActions.java:26)
   > 	at org.elasticsearch.index.reindex.ReindexRequest.validate(ReindexRequest.java:110)
   > 	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1399)
   > 	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1373)
   > 	at org.elasticsearch.client.RestHighLevelClient.reindex(RestHighLevelClient.java:499)
   > 	at org.elasticsearch.client.documentation.CRUDDocumentationIT.testReindex(CRUDDocumentationIT.java:877)
   > 	at java.lang.Thread.run(Thread.java:748)

reproduce with `./gradlew :client:rest-high-level:integTestRunner -Dtests.seed=B4C3EF6C5B9EEEAC -Dtests.class=org.elasticsearch.client.documentation.CRUDDocumentationIT -Dtests.method="testReindex" -Dtests.security.manager=true -Dtests.locale=es-MX -Dtests.timezone=America/El_Salvador -Dcompiler.java=11 -Druntime.java=8`

**Comment by ivange94** [comment]
@ywelsch I'm having a bit of a trouble here. I can't see my commits locally anymore. I had some trouble with my virtual machine so I had to setup a new one. I've cloned this repo and fetched this branch but when I do `git checkout issue-37855`, the only commit I see at the top is your merge commit **Merge remote-tracking branch 'elastic/master' into pr/37900**.

**Comment by henningandersen** [comment]
@ivange94 I checked your branch and found both the previous commits. They are somewhat down the list since they were from jan 27 and feb 5:

https://github.com/ivange94/elasticsearch/commits/issue-37855?before=5f0d8e7459ac87e6504320cca19a088d76f6e0e4+70

(search in page for ivange94).

Do you want to pick this up again and look into above test failure? It is probably advisable to merge in master first.

**Comment by ivange94** [comment]
@henningandersen yes I'd look at this some more. I wasn't able to run the failed tests from my IDE so I can debug. I'll try again.

**Comment by ywelsch** [comment]
Any updates on this?

**Comment by ywelsch** [comment]
I'm closing this because of inactivity. @ivange94 We can reopen the PR whenever you would like to pick this up again.

**Pull request closed without merging**
