### PR TITLE
If no perBucketSample has been allocated for the parent bucket return a doc count of 0

### LINKED ISSUE #49072: Array Index Out of Bounds Exception - Elastic 6.8.2
On executing the following curl command:

```
curl -H'content-type:application/json' 'http://localhost:9220/_msearch?error_trace=true&pretty' -d '
{"index":["companiestable"],"ignore_unavailable":true,"preference":1572975891903}
{"aggs":{"topicFilters":{"filters":{"filters":[{"span_near":{"clauses":[{"span_term":{"description":"compani"}},{"span_term":{"description":"technolog"}}],"slop":2,"in_order":false}},{"span_near":{"clauses":[{"span_term":{"description":"market"}},{"span_term":{"description":"technolog"}}],"slop":2,"in_order":false}}]},"aggs":{"sampler":{"sampler":{"shard_size":1000},"aggs":{"subtopics":{"terms":{"field":"description","size":48,"include":["market","technolog", "compani"]}}}}}}},"size":0,"_source":{"excludes":[]},"query":{"bool":{"must":[{"match_phrase":{"description":"Real Estate"}},{"wildcard":{"description":"*"}}]}}}
'
```

we get the following error:

```
{
  "responses" : [
    {
      "took" : 12,
      "timed_out" : false,
      "_shards" : {
        "total" : 5,
        "successful" : 1,
        "skipped" : 0,
        "failed" : 4,
        "failures" : [
          {
            "shard" : 1,
            "index" : "companiestable",
            "node" : "y2dEMXn3Sd6qaR4jYByMow",
            "reason" : {
              "type" : "array_index_out_of_bounds_exception",
              "reason" : "1"
            }
          }
        ]
      },
...
```
despite the query being a valid query. This is happening for elasticsearch version 6.8.2 for [this](https://drive.google.com/drive/folders/1R_IFv-c0SqMYpZDUNHY22zQ34J2cBbbj?usp=sharing) data folder.

### PR DESCRIPTION
**Pull request by fabiocorneti**
Fixes #49072

### CODE REVIEW

**Comment by not-napoleon** [comment]
@elasticmachine test this please

**Comment by not-napoleon** [comment]
Hi @fabiocorneti 

Thanks for submitting this PR!  It looks good to me, so I've asked our CI system to test it.  Once everything's green, I can get this merged & back-ported.

**Review by not-napoleon — APPROVED** [review]
LGTM

**Comment by not-napoleon** [comment]
@elasticmachine update branch

**Comment by not-napoleon** [comment]
@fabiocorneti Can you please pull in the lastest from master?  For some reason the bot isn't doing it for me.  The test failures look unrelated, and I want to see if it's just a version missmatch that can be fixed with a fresh copy of master before I dig in more.

**Comment by nik9000** [comment]
> @fabiocorneti Can you please pull in the lastest from master? For some reason the bot isn't doing it for me. The test failures look unrelated, and I want to see if it's just a version missmatch that can be fixed with a fresh copy of master before I dig in more.

If the bot can't pull it is usually because it doesn't have permission. I tend to try locally just so I can see the error message.

**Comment by fabiocorneti** [comment]
@not-napoleon I rebased on latest master and re-run server tests locally.

**Comment by not-napoleon** [comment]
@elasticmachine test this please

**Comment by not-napoleon** [comment]
@fabiocorneti Thanks!  Hopefully that'll fix things

@nik9000 yeah, I know I can pull it locally to get more info, but after looking at the test failure in Gradle Enterprise, I was pretty sure it was a stale copy of master, so I want to try refreshing before I dig any deeper.  BWC was failing on not finding a module.

**Pull request merged**
