### PR TITLE
[ESQL] Fix ToDateNanos tests to not run when the FF is disabled

### LINKED ISSUE #113661: [CI] ToDateNanosTests class failing
**Build Scans:**
- [elasticsearch-periodic #4226 / release-tests](https://gradle-enterprise.elastic.co/s/36chl6mrk2tmm)
- [elasticsearch-pull-request #33424 / release-tests](https://gradle-enterprise.elastic.co/s/xjjhnjqldnsbm)
- [elasticsearch-periodic #4222 / release-tests](https://gradle-enterprise.elastic.co/s/uhviiicmtmqom)
- [elasticsearch-periodic #4218 / release-tests](https://gradle-enterprise.elastic.co/s/bawp3kdvsp5co)
- [elasticsearch-periodic #4214 / release-tests](https://gradle-enterprise.elastic.co/s/6f5i5s6qlambk)
- [elasticsearch-periodic #4210 / release-tests](https://gradle-enterprise.elastic.co/s/xl7z4qselti2o)
- [elasticsearch-periodic #4206 / release-tests](https://gradle-enterprise.elastic.co/s/oeu7cxosjmwmw)
- [elasticsearch-periodic #4202 / release-tests](https://gradle-enterprise.elastic.co/s/4oxguwuvaqp6m)

**Reproduction Line:**
```
undefined
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupInput:(chainingSystem:HIERARCHICAL,controlStyle:twoLine,ignoreParentSettings:(ignoreFilters:!f,ignoreQuery:!f,ignoreTimerange:!f,ignoreValidations:!t),panels:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:task.keyword,grow:!t,id:'0c0c9cb8-ccd2-45c6-9b13-96bac4abc542',searchTechnique:wildcard,selectedOptions:!(),singleSelect:!t,title:'Gradle%20Task',width:medium),grow:!t,order:0,type:optionsListControl,width:small),'144933da-5c1b-4257-a969-7f43455a7901':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:name.keyword,grow:!t,id:'144933da-5c1b-4257-a969-7f43455a7901',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.esql.expression.function.scalar.convert.ToDateNanosTests'),title:Test,width:medium),grow:!t,order:2,type:optionsListControl,width:medium),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(explicitInput:(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,enhancements:(),fieldName:className.keyword,grow:!t,id:'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850',searchTechnique:wildcard,selectedOptions:!('org.elasticsearch.xpack.esql.expression.function.scalar.convert.ToDateNanosTests'),title:Suite,width:medium),grow:!t,order:1,type:optionsListControl,width:medium)))))

**Failure Message:**
```
undefined
```

**Issue Reasons:**
- [main] 8 consecutive failures in step release-tests
- [main] 8 failures in class org.elasticsearch.xpack.esql.expression.function.scalar.convert.ToDateNanosTests (2.4% fail rate in 338 executions)
- [main] 8 failures in step release-tests (100.0% fail rate in 8 executions)
- [main] 7 failures in pipeline elasticsearch-periodic (100.0% fail rate in 7 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by not-napoleon**
Fixes https://github.com/elastic/elasticsearch/issues/113661

Don't run the tests when the feature is disabled.

### CODE REVIEW

**Review by nik9000 — APPROVED** [review]

**Comment by not-napoleon** [comment]
@elasticmachine update branch

**Comment by not-napoleon** [comment]
@elasticmachine update branch

**Comment by not-napoleon** [comment]
@elasticmachine update branch

**Comment by not-napoleon** [comment]
@elasticmachine update branch

**Comment by not-napoleon** [comment]
@elasticmachine update branch

**Pull request merged**
