### PR TITLE
[FEATURE] Adjust ML memory tracker to include data frame analytics jobs

### PR DESCRIPTION
**Pull request by droberts195**
This change is a step towards assigning persistent
tasks for data frame analytics jobs to nodes based
on their memory usage and the memory usage of
other ML jobs of all types.

Included in this change:

1. ML memory tracker knows about both anomaly
   detector jobs and data frame analytics jobs
2. Starting a data frame analytics job refreshes
   the ML memory tracker
3. Deleting a data frame analytics job removes
   its entry from the ML memory tracker

Deferred to a subsequent change:

1. Assigning anomaly detector jobs based on the
   location of previously assigned data frame analytics
   jobs as well as previously assigned anomaly detector
   jobs
2. Assigning data frame analytics jobs based on
   memory requirement

### CODE REVIEW

**Review by dimitris-athanasiou — COMMENTED** [review]
Looks good. Just left one comment.

**Review by dimitris-athanasiou — APPROVED** [review]
LGTM

**Comment by droberts195** [comment]
Jenkins run elasticsearch-ci/packaging-sample

**Comment by droberts195** [comment]
Jenkins run elasticsearch-ci/1

**Pull request merged**
