### PR TITLE
Remove include_type_name from the REST API spec and docs.

### PR DESCRIPTION
**Pull request by jtibshirani**
In #48632 we removed support for `include_type_name` in the REST API. This PR
removes it from the API spec and documentation.

### CODE REVIEW

**Comment by jtibshirani** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by jtibshirani** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by jtibshirani** [comment]
@romseygeek this is ready for a look (the test failures aren't related to my changes).

**Review by romseygeek — APPROVED** [review]
LGTM, thanks @jtibshirani

**Pull request merged**
