### PR TITLE
Add 'monitor_snapshot' cluster privilege

### LINKED ISSUE #50210: Add 'monitor_snapshot' cluster privilege
**Describe the feature**:

Currently retrieving repository and snapshot metadata from Elasticsearch requires at least the `create_snapshot` privilege, which is too permissive for just monitoring the existing repositories and snaphots.

For read-only access to repositories and snapshots metadata (possibly via unauthenticated users) it would be preferable to allow more fine-grained control by adding an additional `monitor_snapshot` cluster privilege.

### PR DESCRIPTION
**Pull request by AntonShuvaev**
PR adds 'monitor_snapshot' cluster privilege.

Closes #50210

### CODE REVIEW

**Comment by dnhatn** [comment]
@elasticmachine ok to test

**Review by albertzaharovits — CHANGES_REQUESTED** [review]
Thank you again for the contribution @j-bean !

I see you've added a new cluster privilege `monitor_snapshot` as well as a new built-in role `monitor_snapshot_user` . But I don't think adding a built-in role is appropriate. We have too many of those and the addition of a new one, without a reasonable motivation, hurts the discoverability of the others. When we add a new built-in role we think of privileges that justifiably should go together, such as the privileges required to use a distinct Kibana feature (transform) or an Elastic Stack integration (Beats).

The case for the `snapshot_user` role, on which you've based your new role, is [Curator](https://github.com/elastic/curator). Curator requires that it can snapshot as well as _list_ all the indices. In addition to supporting Curator, it would be incongruous for any other users to be able to snapshot indices that they cannot _list_. Given that at the moment we cannot limit the indices a user can snapshot, the next best alternative was to create a built-in role that grants snapshot and _list_ permissions for all indices.

Given the above, I don't think there is a case for a new snapshot monitoring built-in role.

Other than that, the changes look good to me!

**Review by albertzaharovits — APPROVED** [review]
Thank you @j-bean !
LGTM
We should wait for Tim to have his say before merging.

**Comment by tvernum** [comment]
I think this change highlights a gap in our testing.
We don't have any tests that are able to check the difference between `create_snapshot` and `monitor_snapshot` because we only really run an integration test for that.

Separate to this PR, we need a non-integration `ClusterPrivilege` test that either goes privilege-by-privilege or action-by-action and verifies the correct access.

**Review by tvernum — APPROVED** [review]
LGTM.

**Comment by albertzaharovits** [comment]
@elasticmachine update branch

**Pull request merged**
