### PR TITLE
[DOCS] Update casing in FIPS docs

### PR DESCRIPTION
**Pull request by bytebilly**
Changes `fips` to `FIPS` and `elasticsearch` to `{es}` in FIPS docs.

### CODE REVIEW

**Comment by bytebilly** [comment]
@jkakavas I'm not sure if this change is valid, could you please take a look? Thanks!

**Comment by jkakavas** [comment]
I think "fips mode" is fine as it refers to a term that is elasticsearch related. The same way the config option is `xpack.security.fips_mode.enabled` and not `xpack.security.FIPS_mode.enabled`.

Is this originating from some comment or feedback? Do we think that it's not clear as is ? I don't have a strong preference, just trying to understand.  If we do change this, I think we should call it "FIPS 140-2 mode" instead of "FIPS mode" though

**Comment by bytebilly** [comment]
It was my sentiment while reading the docs, as lowercase `fips` sounded wrong as we have FIPS everywhere else.
I agree it could be `FIPS 140-2 mode`, I see it is used elsewhere in the same page.
I don't think it really creates confusion, but just for consistency.

The configuration option is fine as they are generally turned all lowercase (e.g. `ssl`).

**Review by jkakavas — APPROVED** [review]
LGTM

**Pull request merged**
