### PR TITLE
string.asciidoc: fix for `position_increment_gap`

### PR DESCRIPTION
**Pull request by golubev**
Remove  outdated and duplicate description for the `position_increment_gap` parameter.

### CODE REVIEW

**Comment by golubev** [comment]
My company - LUN UA LLC - signed the CCLA and had listed me as a contributor. And I've signed the ICCLA under that one above.

**Comment by nik9000** [comment]
@golubev the change looks good. Thanks for pointing me to the corporate CLA. I found it and synced it into the CLA checker. By making this comment I'm triggering it to check again.

**Comment by nik9000** [comment]
Merged!
Master: 8430b379d889b7db6172f38548e5422044fd0766
2.x: ece74c048260050b4dbeb60a5a8a54140716f21b
2.3: 0ad79285422cfff11d9d6cd012e18daa32a21e1d

Thanks @golubev !

**Comment by golubev** [comment]
Thanks @nik9000 !

**Pull request merged**
