### PR TITLE
Add note to migration docs on silent batch mode

### PR DESCRIPTION
**Pull request by jasontedor**
A previous change removed silent batch mode for the plugin installer. This commit adds a note to the migration docs regarding this change.

Relates #29359

### CODE REVIEW

**Review by spinscale — APPROVED** [review]
LGTM

Not a hundred percent sure about having a snippet like `foo bar` starting in one line and ending in the other, but I think that works (using `deprecated[]` does not IIRC)

**Review by dolaru — APPROVED** [review]
LGTM

**Comment by jasontedor** [comment]
Thanks for thinking of that @spinscale. I built the docs and they render fine as-is.

screen shot 2018-04-04 at 9 38 05 am

**Comment by jasontedor** [comment]
Thanks @spinscale and @dolaru.

**Pull request merged**
