### PR TITLE
WIP draft for logging 

### PR DESCRIPTION
**Pull request by pgomulka**
a draft for adding new logging messages
```
{
  "type": "server",
  "timestamp": "2019-07-15T10:46:18,533+02:00",
  "level": "INFO",
  "component": "o.e.c.r.a.AllocationService",
  "cluster.name": "distribution_run",
  "node.name": "node-0",
  "message": "Cluster health status changed.",
  "previous.health": "RED",
  "current.health": "YELLOW",
  "reason": "shards started [[user][0]] ...",
  "cluster.uuid": "jasQmjPGSouvwlq2uCi5mw",
  "node.id": "YG5tq4N-QbWalE7VN2yjmA"
}
```

### CODE REVIEW

**Comment by cachedout** [comment]
This is exciting! Thank you for starting on this, @pgomulka !

**Comment by cachedout** [comment]
Hi @pgomulka!

Thanks again for taking this one on. I just wanted to check in with you and see what the next steps were on this proposal. It would be very helpful for us to have this on the Stack Monitoring side and if there's anything we can do to help this along, we're happy to. :) Thanks!

**Comment by pgomulka** [comment]
@cachedout my goal would be to combine this effort together with Elastic Common Schema support. I will create an issue to track progress and will link it here later

**Comment by cachedout** [comment]
@pgomulka That's a very intriguing idea. Thanks for the update. I look forward to seeing what you come up with.

**Comment by pgomulka** [comment]
I will close this as is being discussed in https://github.com/elastic/elasticsearch/issues/46119

**Pull request closed without merging**
