### PR TITLE
SQL: add support for index aliases for SYS COLUMNS command

### PR DESCRIPTION
**Pull request by astefan**
Backport of https://github.com/elastic/elasticsearch/pull/53525.

### CODE REVIEW

**Comment by astefan** [comment]
@elasticmachine run elasticsearch-ci/2

**Review by costin — APPROVED** [review]
LGTM

**Comment by astefan** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by astefan** [comment]
@elasticmachine update branch

**Pull request merged**
