### PR TITLE
Skip installation of pre-bundled integ-test modules

### PR DESCRIPTION
**Pull request by mark-vieira**
Second attempt at resolving #42532. It turns out the "fix" in #42879 was insufficient because `DuplicatesStrategy` actually only applies to duplicate files in the same `CopySpec` and has no effect on overwriting files that already exist in the target destination.

We now take a different approach and simply skip installation of any modules that are already included in the test distribution. At the moment this is only `transport-netty4`.

### CODE REVIEW

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by atorok** [comment]
@mark-vieira @rjernst I initially had an Os ( filesystem  to be exact) dependent implementation that would remove write permission to the initial file after hard-linking.
This would have made this one much easier to spot and fix. 
The reason I did not include that it is that it was fairly complex so I used it only while implementing the hard-linking and to run some tests but it did not seem worth to keep. 
Seeing this issue that might not have been the right call. What do you think ? Should we put it back ?

**Comment by mark-vieira** [comment]
> Seeing this issue that might not have been the right call. What do you think ? Should we put it back ?

I'm a bit on the fence. Having filesystem-dependent implementations is going to be really hard to properly test and might have it's own strange issues that are hard to track down should things start going wrong again. At least we know this is a thing, and it's pretty easy to detect if this is what is happening just be looking at last-modified times on the hardlinked files.

Rather than going the read-only route we could do something like add an action to every task the "uses" a cluster which checks the last-modified times on the extracted directory to ensure they haven't changed and if they have, throw an error.

**Comment by atorok** [comment]
I like that idea, only problem I see it adds overhead each time even when everything works as it should, we have to cycle trough all files, including the JDK. I think that will add up and be significant for our build. We would have to do the check when the cluster starts, that's when we set up the working copies.  I think Gradle has a native wrapper so already dealing with platform dependent stuff, might be worth thinking about contributing a  `HardLinkTask` ?

**Comment by mark-vieira** [comment]
> only problem I see it adds overhead each time even when everything works as it should

Agreed. I'm still not convinced it's strictly necessary at this point.

> We would have to do the check when the cluster starts

If we were to implement this, we should do the check when the task _finishes_ as it's possible anything during task execution could have modified those files so we want to check that when everything is done, things are left as they were when the task started.

>  I think Gradle has a native wrapper so already dealing with platform dependent stuff, might be worth thinking about contributing a HardLinkTask ?

Gradle uses [this](https://github.com/adammurdoch/native-platform) library for platform dependent stuff which doesn't support symlinks on non-posix platforms nor hardlinks at all.

**Pull request merged**
