### PR TITLE
Add a note about the source size parameter

### PR DESCRIPTION
**Pull request by roidelapluie**

### CODE REVIEW

**Comment by clintongormley** [comment]
thanks for the PR @roidelapluie - just one fix, the batch size has been changed to 1000 in https://github.com/elastic/elasticsearch/pull/18340

**Comment by roidelapluie** [comment]
What do you think of this?

**Comment by nik9000** [comment]
LGTM

**Comment by clintongormley** [comment]
thanks @roidelapluie - i'll use this as a base and add different commits to 2.3, 2.x, and master

**Comment by roidelapluie** [comment]
Thanks.

**Comment by roidelapluie** [comment]
@clintongormley wait, this was already present in the docs. I idi not see it because it is not present in 2.3 docs.

Backporting the doc part of #18340 to 2.3 looks better than this.

**Comment by clintongormley** [comment]
ah doh!  good spot

**Comment by clintongormley** [comment]
Done

**Pull request closed without merging**
