### PR TITLE
Change data stream timestamp parsing use const variable to replace magic

### PR DESCRIPTION
**Pull request by weizijun**
a tiny PR to change data stream timestamp parsing use const variable to replace magic.

### CODE REVIEW

**Comment by martijnvg** [comment]
@elasticmachine test this please

**Review by martijnvg — APPROVED** [review]
Thanks @weizijun 👍

**Comment by martijnvg** [comment]
@elasticmachine test this please

**Comment by martijnvg** [comment]
@elasticmachine run elasticsearch-ci/part-2

**Comment by martijnvg** [comment]
@elasticmachine run elasticsearch-ci/part-2

**Comment by weizijun** [comment]
> Thanks @weizijun 👍

Thanks @martijnvg

**Pull request merged**
