### PR TITLE
[8.16][ML] Move code specific to the Elasticsearch in cluster services to those services

### PR DESCRIPTION
**Pull request by davidkyle**
Backport of https://github.com/elastic/elasticsearch/pull/113749/ incorporating the bug fix in https://github.com/elastic/elasticsearch/pull/113898

### CODE REVIEW

**Review by maxhniebergall — APPROVED** [review]
LGTM

**Comment by maxhniebergall** [comment]
@elasticmachine merge upstream

**Comment by davidkyle** [comment]
@elasticmachine merge upstream

**Comment by maxhniebergall** [comment]
slack threads indicate backports are passing now

@elasticmachine merge upstream

**Comment by maxhniebergall** [comment]
@elasticmachine merge upstream

**Pull request merged**
