### PR TITLE
Upgrade to Jackson 2.10.3

### PR DESCRIPTION
**Pull request by jasontedor**
This commit upgrades our Jackson dependency to 2.10.3. We intentionally exclude ingest-geoip, we will handle that one separately.

Relates #27032
Relates #45225

### CODE REVIEW

**Review by dakrone — APPROVED** [review]
This LGTM, but it appears that the failure is actually valid and changes now that Jackson returns Float instead of Double, is this liable to cause us any actual problems down the road? Is this breaking for HLRC users?

**Review by rjernst — COMMENTED** [review]
How can upgrading jackson separately in ingest-geoip work when jackson is a core dependency? We do not package core dependencies in modules/plugins, so jackson-core does not existing within the ingest-geoip module (but jackson-databind does).

**Comment by jasontedor** [comment]
@rjernst Good catch. Let me see about updating ingest-geoip in this pull request then.

**Comment by mark-vieira** [comment]
This was reverted after it started causing a number of test failures in CI. See the linked issues ☝️

**Pull request merged**
