### PR TITLE
Shard CLI tool always check shards

### PR DESCRIPTION
**Pull request by henningandersen**
The shard CLI tool would not do anything if a corruption marker was not
present. But a corruption marker is only added if a corruption is
detected during indexing/writing, not if a search or other read fails.

Changed the tool to always check shards regardless of corruption marker
presence.

Related to #41298

### CODE REVIEW

**Comment by henningandersen** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by henningandersen** [comment]
Unrelated failure, same as: https://github.com/elastic/elasticsearch/issues/41549

**Comment by henningandersen** [comment]
@elasticmachine run elasticsearch-ci/1

**Review by ywelsch — APPROVED** [review]
LGTM

**Comment by csoulios** [comment]
@DaveCTurner can we merge this PR  to 6.x branch?

**Pull request merged**
