### PR TITLE
Packaging: Ensure upgrade_is_oss flag file is always deleted

### LINKED ISSUE #30682: Packaging test fails on fedora 27, centos 7  in verify that the documents are there after restart
Running 
`./gradlew :qa:vagrant:packagingTest -Pvagrant.boxes=fedora-27` Fails with:

```
ok 236 [UPGRADE] check elasticsearch version is version under test
not ok 237 [UPGRADE] verify that the documents are there after restart
# (in test file /project/build/packaging/bats/tests/80_upgrade.bats, line 111)
#   `curl -s localhost:9200/library/book/1?pretty | grep Elasticsearch' failed
ok 238 [UPGRADE] stop version under test
ok 239 [REINSTALL] install
ok 240 [REINSTALL] purge elasticsearch
ok 241 [REINSTALL] chown directories
ok 242 [REINSTALL] reinstall elasticsearch
ok 243 [REINSTALL] check ownership
REPRODUCE WITH: ./gradlew :qa:vagrant:vagrantFedora27#batsPackagingTest -Dtests.seed=858B8891E728527A
```

I got the same on `centos-7` as well as `fedora-28` ( from #30579 ).

### PR DESCRIPTION
**Pull request by rjernst**
This commit ensures the delete of the upgrade_is_oss indicator for
the packaging tests is always deleted before each run. It works by
moving the check on version which skips the task into the doFirst block,
replacing the onlyIf.

closes #30682

### CODE REVIEW

**Review by alpar-t — APPROVED** [review]
LGTM. 
Might be worth adding some logging so one can tell what happened. With `onlyif` the task would be marked with `SKIPPED` but that's no longer the case with `StopExecutionException`. One can easily be mislead when readin task output / build log, as the task name does not convey the conditional on it's own.

**Comment by rjernst** [comment]
Thanks @atorok. I added a message to the StopExcecutionException, which is printed at info level.

**Comment by jpountz** [comment]
@rjernst the backport_pending label doesn't seem useful as it seems like this change was backported already?

**Comment by jpountz** [comment]
@rjernst Thanks for checking.

**Pull request merged**
