### PR TITLE
Add options for indices.get feature

### PR DESCRIPTION
**Pull request by gmarz**
As described here https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-get-index.html?q=get%20index#_filtering_index_information

### CODE REVIEW

**Comment by nik9000** [comment]
LGTM

**Comment by clintongormley** [comment]
Hmmm doesn't this clash with eg the `GET index/_settings` API etc?

**Comment by gmarz** [comment]
I think the difference is that indices.get allows you to retrieve multiple features (_settings, _aliases, etc..) all in the same call, which isn't possible with the other APIs since they are feature specific.

**Comment by clintongormley** [comment]
ah right, i wasn't aware of that!

**Pull request merged**
