### PR TITLE
Update Semantic Search Tutorial to Use Elasticsearch Service and Remove References to Deprecated ELSER Service

### PR DESCRIPTION
**Pull request by eshaffer321**
Added a deprecation warning to the “Tutorial: semantic search with semantic_text” to inform users that the elser service is deprecated as of version 8.16 and will be removed in a future release. The warning advises users to use the Elasticsearch inference service with model_id in service_settings instead. This update aligns the tutorial with the existing deprecation notice on the ELSER documentation page, ensuring clarity for users following the tutorial.

[x] Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
[x] Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md)?
[N/A] If submitting code, have you built your formula locally prior to submission with `gradle check`?
[N/A] If submitting code, is your pull request against main? Unless there is a good reason otherwise, we prefer pull requests against main and will backport as needed.
[N/A] If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
[N/A] If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by eshaffer321** [comment]
Issue raised here
https://github.com/elastic/elasticsearch/issues/117829

**Review by maxhniebergall — CHANGES_REQUESTED** [review]
I think that rather than using a deprecation warning here, we should just change this tutorial to use the elasticsearch service. There is an example of this here: https://www.elastic.co/guide/en/elasticsearch/reference/current/infer-service-elasticsearch.html#inference-example-elasticsearch-elser

**Comment by eshaffer321** [comment]
> I think that rather than using a deprecation warning here, we should just change this tutorial to use the elasticsearch service. There is an example of this here: https://www.elastic.co/guide/en/elasticsearch/reference/current/infer-service-elasticsearch.html#inference-example-elasticsearch-elser

Thank you for the feedback! I’ve updated the tutorial to use the Elasticsearch service as suggested and removed the deprecation warning. Please let me know if there’s anything else you’d like adjusted.

**Comment by leemthompo** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by leemthompo** [comment]
run docs-build

**Review by maxhniebergall — APPROVED** [review]
LGTM, thanks for iterating!

**Pull request merged**
