### PR TITLE
Preserve Task Id for ML Datafeed

### PR DESCRIPTION
**Pull request by albertzaharovits**
Task ids are a way to express a relationship between related internal requests.
This change preserves the task id for internal requests of the `StartDatafeedPersistentTask`, similarly to how `RollupJobPersistentTask` does it.

Relates https://github.com/elastic/elasticsearch/issues/52314

### CODE REVIEW

**Comment by davidkyle** [comment]
Hi @albert we have other places we are using a client - specifically indexing the results and model state- should we be using `ParentTaskAssigningClient` everywhere. 

For example: https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/persistence/JobResultsPersister.java#L84

**Comment by droberts195** [comment]
> should we be using `ParentTaskAssigningClient` everywhere

Maybe we should in theory, but I think this is a far reaching and high risk change.  I suspect we will be spending a lot of time clearing up side effects.  Our tasks are very complex, fire off numerous sub-tasks, and we have dedicated open/close/stop/start APIs for orchestrating them.  I strongly suspect we will get into a mess with task cancellation if we try to link our controlling job/datafeed tasks to every sub-operation they perform.  @dimitris-athanasiou has already run into this with the reindex task that data frame analytics jobs kick off.

**Comment by albertzaharovits** [comment]
I have not yet looked into the data frame analytics tasks and the transform tasks, but I will do that in a follow-up. My end goal is to track all client requests for all persistent tasks in the same way, but I don't see an overarching way to achieve it, without looking into every case. Do you reckon this is a valid strategy?

This PR is only for the DataFeed persistent task, do you reckon this achieves the scope?

I wonder how should we test it, I don't have a good plan for it.

**Comment by davidkyle** [comment]
In terms of tracking tasks I think this is a very useful change and valuable for debugging Datafeed issues as we should now know which queries belong to which datafeed.

We already handle task cancellation for the [Datafeed](https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportStartDatafeedAction.java#L455)  and [AD jobs](https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/action/TransportOpenJobAction.java#L517) which gracefully stops the datafeed waiting any executing query to finish. 

How does task cancellation work? If you cancel the parent task are all child tasks then cancelled or is it up to the cancellation handler of the parent task to manage the children? 

I agree managing the AD tasks and processes is a very complicated can of worms and echo @droberts195 caution about side effects but if this change is just about tracking and doesn't affect how task cancellation works then it is good

**Comment by davidkyle** [comment]
I don't see anything in the docs but looking at [TransportCancelTasksAction](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/action/admin/cluster/node/tasks/cancel/TransportCancelTasksAction.java#L114)  I think we have a problem in that the child tasks are also cancelled if `CancellableTask.shouldCancelChildrenOnCancellation() == true` unfortunately the implementation in `AllocatedPersistentTask.shouldCancelChildrenOnCancellation()` returns true.

My understanding of the current situation for datafeeds is that because the search tasks are not child tasks of the datafeed they will not be cancelled automatically and the graceful shutdown works. 

We could change `shouldCancelChildrenOnCancellation()` to return false for the DatafeedTasks which should preserve the graceful shutdown behaviour once the search becomes a child task.

@albertzaharovits @droberts195 what do you think? I think it is worth trying for the benefit of tracking which tasks are started by the datafeed

**Comment by albertzaharovits** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by albertzaharovits** [comment]
> My understanding of the current situation for datafeeds is that because the search tasks are not child tasks of the datafeed they will not be cancelled automatically and the graceful shutdown works.
We could change shouldCancelChildrenOnCancellation() to return false for the DatafeedTasks which should preserve the graceful shutdown behaviour once the search becomes a child task.

Good point @davidkyle ! I also agree that because Datafeeds already implement graceful task cancellation we should make `shouldCancelChildrenOnCancellation()` return false, i.e. use task ids only for tracking, and not cancellation purposes.

**Comment by droberts195** [comment]
Going back to the reason why this change is being done, #52314, it looks like it's most important that the sub-tasks that get parented to the persistent task are the ones that run with the credentials of the user that created the configuration.  The sub-tasks that run as an internal user don't need to be changed to assist with accurate auditing, but maybe could be changed for consistency.

We have had so many problems over the years with obscure edge cases causing ML jobs/datafeeds to not stop.  Ironically the failure in `elasticsearch-ci/2` in the latest PR CI run for this PR is an example of this in `org.elasticsearch.xpack.ml.integration.ClassificationIT.testStopAndRestart` - since that's in data frame analytics rather than anomaly detection it's almost certainly not caused by the changes in this PR, so it's an example of the general problems we have with starting and stopping tasks that have extremely complex internal states.

> we should make `shouldCancelChildrenOnCancellation()` return false

Yes, I agree.  This is the least risky change from where we are today.  Please can you try adding that to this PR and see if any tests related to datafeeds fail as a result.  If not then I think this PR is good.

To clean the audit logs similar PRs will probably be needed for data frame analytics and transforms.

**Comment by albertzaharovits** [comment]
Thank you for the feedback @droberts195 ! Very much appreciated.

> it looks like it's most important that the sub-tasks that get parented to the persistent task are the ones that run with the credentials of the user that created the configuration. The sub-tasks that run as an internal user don't need to be changed to assist with accurate auditing, but maybe could be changed for consistency.

Yes, this is what I had in mind as well. Trace the requests using the client's credentials, but don't try too hard to avoid the other internal requests doing the same.

> We have had so many problems over the years with obscure edge cases causing ML jobs/datafeeds to not stop. Ironically the failure in elasticsearch-ci/2 in the latest PR CI run for this PR is an example of this in org.elasticsearch.xpack.ml.integration.ClassificationIT.testStopAndRestart - since that's in data frame analytics rather than anomaly detection it's almost certainly not caused by the changes in this PR, so it's an example of the general problems we have with starting and stopping tasks that have extremely complex internal states.

LOL

**Comment by albertzaharovits** [comment]
@droberts195 I've made the changes as suggested.

**Review by droberts195 — APPROVED** [review]
LGTM

**Pull request merged**
