### PR TITLE
Metadata of API key authentication must have roleDescriptor keys

### PR DESCRIPTION
**Pull request by ywangd**
This PR removes conditional check for metadata keys related to API key
role descriptors. API key authentication must always have these keys for
it to work. The PR adds assertions for these keys and fixes relevant
tests.

Relates: #82639

### CODE REVIEW

**Comment by ywangd** [comment]
@elasticmachine run elasticsearch-ci/full-bwc

**Review by albertzaharovits — APPROVED** [review]
LGTM

**Comment by ywangd** [comment]
@elasticmachine update branch

**Comment by ywangd** [comment]
Label as `>non-issue` since previous change of adding conditional check is not released.

**Comment by ywangd** [comment]
@elasticmachine run elasticsearch-ci/full-bwc

**Pull request merged**
