### PR TITLE
Resolve cluster alias for opened remote connections

### PR DESCRIPTION
**Pull request by n1v0lg**
https://github.com/elastic/elasticsearch/pull/91724 introduced the ability to resolve the cluster alias, given a connection towards a remote cluster. This works for connections obtained via `RemoteConnectionManager::getConnection`. However, connections can also be initiated via `openConnection` (e.g., in `SniffConnectionStrategy`). This PR adds support to correctly resolve the cluster alias for such connections, by wrapping them in an `InternalRemoteConnection` instance. This is necessary to support the new remote cluster security model.

### CODE REVIEW

**Review by slobodanadamovic — APPROVED** [review]
LGTM

**Comment by n1v0lg** [comment]
Build failure unrelated and tracked here: https://github.com/elastic/elasticsearch/issues/92930

**Review by Tim-Brooks — APPROVED** [review]
LGTM

**Comment by n1v0lg** [comment]
@elasticsearchmachine run elasticsearch-ci/part-2-fips

**Pull request merged**
