### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by DimaGashko**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by jrodewig** [comment]
Hi @DimaGashko 

Thanks for opening this PR.

Before we can merge your changes, we need a signed CLA: https://www.elastic.co/contributor-agreement

Please ensure you sign the CLA using the email address associated with your commit. You can find that address here:
https://github.com/elastic/elasticsearch/commit/1e9c8a8f40cc41976ea82cb72fe7437f053b79d9.patch

**Comment by jrodewig** [comment]
Superseded by #65822

**Comment by DimaGashko** [comment]
@jrodewig Yes, I noticed that after I sent the PR, but it requires more time than I have now to examine the agreement and all that signature system.
Thanks for moving it to another PR

**Comment by jrodewig** [comment]
No worries at all. Thanks again for raising the issue @DimaGashko!

**Pull request closed without merging**
