### PR TITLE
Fail shard if search execution uncovers corruption

### PR DESCRIPTION
**Pull request by kimchy**
If, as part of the search execution, a corruption is uncovered, we should fail the shard
relates to #11419

### CODE REVIEW

**Comment by rmuir** [comment]
+1. Its never ideal for it to go down in this way, but we should do the right thing when it happens.

**Comment by bleskes** [comment]
LGTM. Can't figure out why we weren't doing it until now :)

**Comment by s1monw** [comment]
LGTM too

**Comment by kimchy** [comment]
pushed to master and 1.x

**Pull request closed without merging**
