### PR TITLE
Migrate Streamable to Writeable for WatchStatus

### PR DESCRIPTION
**Pull request by liketic**
Migrate Streamable to Writeable for class ```WatchStatus```. 

Relates to #34389

### CODE REVIEW

**Review by jdconrad — APPROVED** [review]
LGTM

**Comment by jdconrad** [comment]
@elasticmachine test this please

**Comment by jdconrad** [comment]
@liketic Thank you for the contribution!

**Comment by javanna** [comment]
@jdconrad I added the v8.0.0 label. Can you backport this to 7.x?

**Comment by jdconrad** [comment]
@javanna Sorry I missed this.  Will back port this today.

**Pull request merged**
