### PR TITLE
Removed differencies between text and code

### PR DESCRIPTION
**Pull request by akadko**
Text says about 'author' but there was 'type' in code snippet

### CODE REVIEW

**Comment by DaveCTurner** [comment]
@akadko Please could you sign the [contributor license agreement (CLA)](https://www.elastic.co/contributor-agreement)?

**Comment by DaveCTurner** [comment]
Also, could you open this against the `master` branch rather than `6.1`? Once accepted and merged it will be backported as appropriate.

**Comment by DaveCTurner** [comment]
@elasticmachine please test this.

**Comment by polyfractal** [comment]
@akadko Sorry for delay, was out on holiday.  

So I think we should actually change the descriptive text, rather than the snippets.  The code snippets are working against a test dataset so that our doc testing framework can verify the syntax and response.  It is using the [`sales` dataset here](https://github.com/elastic/elasticsearch/blob/master/docs/build.gradle#L161-L193), so we can't just change the field without also altering the test parameters.

I'd vote changing the text to something like: `"Assume you are indexing store sales and would like to count the unique number of sold products that match a query:"`.  Or something similar :)

Also just FYI, 6.x and master have diverged a fair amount already, so you'll need to rebase your branch off master in addition to changing the target (e.g. right now the PR is "forward-porting" around 30k lines of changed code :) ).  

The easiest solution is to probably rest the branch to master, then cherry-pick your commit on top.

**Comment by dakrone** [comment]
This appears to have been opened in error.

**Comment by akadko** [comment]
@polyfractal @DaveCTurner thank you for your help! I'm new to open source so it was not so easy for me to get all that techniques. Standards and processes in this repo are really awesome!

**Comment by polyfractal** [comment]
LGTM!  Thanks for making the change, and welcome to the community! :)

**Pull request merged**
