### PR TITLE
Increase default heap size to 2g

### PR DESCRIPTION
**Pull request by jasontedor**
Benchmarking with the geonames data set shows that Elasticsearch truly
needs 2g of heap or the heap is a bottleneck for indexing rates. If our
goal is to satisfy the out-of-the-box-experience, we should prioritize
the out-of-the-box performance experience. Thus, the default heap should
be 2g until smaller heaps are not the bottleneck for indexing small data
sets.

Relates #16334, relates #17686, relates #18309

### CODE REVIEW

**Comment by rmuir** [comment]
+1, it makes the defaults honest. 512MB is just not enough.

**Comment by dadoonet** [comment]
+1

**Comment by s1monw** [comment]
lets do it! +1

**Comment by s1monw** [comment]
since we now increase the heap size should we add benchmarks with lower heap size to track if stuff gets better / worse?

**Comment by danielmitterdorfer** [comment]
@s1monw We can do this. I can pin one setup to 1gb but I'd say we don't include the (moving) default heap size in the benchmarks (i.e. now the 2gb setting) from now on. Wdyt?

**Comment by s1monw** [comment]
yeah why not

**Comment by danielmitterdorfer** [comment]
Provided nobody else objects, the default setup will run the benchmark candidate with 1GB heap as of the next nightly run (i.e. tomorrow).

**Comment by jasontedor** [comment]
I think that we *should* be benchmarking the 2g configuration because below that we are just hamstringing the benchmarks by the heap. Also, I've come to the view that we should be benchmarking the defaults so we can watch for regressions there.

**Comment by mikemccand** [comment]
I think it's vital that we DO benchmark at the default settings: many users will do just that and draw conclusions.  In fact, I think it's the most important curve in the nightly benchmarks ;)

We can also benchmark at other fixed heap sizes so we know the impact, of either too little or too big heap sizes.

**Comment by danielmitterdorfer** [comment]
Ok, then I'll revert.

**Comment by s1monw** [comment]
I misunderstood - of course we have to benchmark defaults. I though you are saying you are not adding 2GB explicitly

**Comment by jasontedor** [comment]
@clintongormley I pushed bc46517f7e941bd09336652338bce6396769b6f8 to set unequal defaults of 256m and 2g.

**Comment by djschny** [comment]
While the change itself is obviously trivial, this change is a __big__ deal IMO. There are tons of users who use elasticsearch in limited resource environments. Before they could use the defaults and not worry about consuming too many resources.

For these reasons I feel this should be labelled as a breaking change.

**Comment by clintongormley** [comment]
@djschny nobody should be using the default heap size in production.  In fact, we fail if min heap != max heap in production mode

**Comment by djschny** [comment]
@clintongormley what is this "production mode" spoke of? If it is the startup checks that happen when not bound to localhost, then those did not exist in 2.x so people could have been running in "production mode" with defaults. Or are you implying that since the new "production mode" stuff is a breaking change, it will force people to set ES_HEAP_SIZE so hence making it a moot point?

**Comment by clintongormley** [comment]
> Or are you implying that since the new "production mode" stuff is a breaking change, it will force people to set ES_HEAP_SIZE so hence making it a moot point?

Precisely

**Comment by jasontedor** [comment]
> set ES_HEAP_SIZE

Note that `ES_HEAP_SIZE` does not exist in >= 5.0.0.

**Comment by anhlqn** [comment]
Just a note about heap size settings on Windows that could be on documentation. After installing ES as a service on Windows, if we want to change the heap size, changing the value in jvm.options won't work. Need the change the value after running `service.bat manager`

**Comment by jasontedor** [comment]
@anhlqn That's always been the case, I'm surprised it's not documented but it definitely does not seem to be. Thanks for the comment, will add.

**Comment by jasontedor** [comment]
@anhlqn I opened #18606.

**Pull request merged**
