### PR TITLE
issue #53129: add null check with described message 

### PR DESCRIPTION
**Pull request by shay123g**
added user-friendly message in null check. issue #53129

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)? yes
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)? yes
- If submitting code, have you built your formula locally prior to submission with `gradle check`? yes
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed. against master
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by shay123g** [comment]
signed again on the Contributor Agreement

**Comment by jdconrad** [comment]
@shay123g I still see the member agreement as not signed. Maybe try signing again?

**Comment by shay123g** [comment]
signed again. Im attaching the file
[Please_DocuSign_Individual_Contributor_Licen (1).pdf](https://github.com/elastic/elasticsearch/files/5765602/Please_DocuSign_Individual_Contributor_Licen.1.pdf)

**Comment by jdconrad** [comment]
@elasticmachine run CLA

**Comment by rjernst** [comment]
@shay123g It looks like you signed the agreement with a gmail address, but the commits are authored with a different address. They need to be the same address to pass the CLA check.

**Comment by shay123g** [comment]
Signed

**Comment by rjernst** [comment]
@shay123g It looks like you added another commit with a different email address, but the old commit still exists. I recommend you do a force push with a single commit.

**Comment by shay123g** [comment]
@rjernst I tried to do the process all over again: delete the branch and open new one with single commit, after signing again.
can u pls write which email address is the commit email and which email address is the licenese agreement email?

i have only one email so i'm confused here..

**Comment by rjernst** [comment]
@shay123g I see two emails that the CLA was signed with. I don't want to paste them here, but one is a gmail address, and the other is a GitHub automated address (xxx@@users.noreply.github.com). This PR currently has 2 commits, the first being with a verint.com address (see https://github.com/elastic/elasticsearch/commit/3a495ddf1a1289cda126c4c278b04eb875104741.patch). The second is with the GitHub automated address (see https://github.com/elastic/elasticsearch/commit/419e4e5720de31144ecc1b7ea71c12ef73e43862.patch). I believe the automated address is from setting up commit signing with GitHub. Therefore, if you rebase and force push to your branch, you should get a single, signed and verified commit, which should then pass the CLA check.

**Pull request closed without merging**
