### PR TITLE
Remove version from FieldCapabilitiesIndexResponse

### PR DESCRIPTION
**Pull request by dnhatn**
We no longer need this BWC version in 8.2 or later.

### CODE REVIEW

**Comment by dnhatn** [comment]
run elasticsearch-ci/part-1

**Review by javanna — APPROVED** [review]

**Review by ywelsch — APPROVED** [review]
LGTM

**Comment by romseygeek** [comment]
Can we hold off merging this for a bit? The field caps filtering I have been working on uses this, although I may be able to get that information from the transport channel instead.

**Comment by dnhatn** [comment]
@romseygeek No problem.

**Comment by dnhatn** [comment]
Closing as the version is now used to filter fields.

**Pull request closed without merging**
