### PR TITLE
Add basic linear combination retriever

### PR DESCRIPTION
**Pull request by jdconrad**
This adds an initial linear combination retriever using a similar strategy to RRF. This prototype will allow us to cover all existing use cases for standard search, and should make it easier to implement retrievers at more than a superficial level.

### CODE REVIEW

**Comment by jdconrad** [comment]
@elasticsearchmachine test this

**Comment by jdconrad** [comment]
@elasticmachine test this please

**Comment by jdconrad** [comment]
@elasticmachine run elasticsearch-ci

**Review by mayya-sharipova — APPROVED** [review]
@jdconrad Thanks Jack, LGTM. Would nice to add some tests.

**Comment by jdconrad** [comment]
@mayya-sharipova Thanks for the review!

**Pull request merged**
