### PR TITLE
Fix #38623 remove xpack namespace REST API

### LINKED ISSUE #38623: Remove the "xpack" namespace from the REST API
@Mpdreamz noticed that some APIs still include the "xpack" namespace in their name. We should remove it. See https://github.com/elastic/elasticsearch/tree/7.x/x-pack/plugin/src/test/resources/rest-api-spec/api.

Relates #35958

### PR DESCRIPTION
**Pull request by Mpdreamz**
Except for xpack.usage and xpack.info API's, this moves the last remaining API's out of the xpack namespace.

Need to distinguish `xpack.info` from `info` https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/api/info.json

Since both these API's are quite clearly relay details about `x-pack` I am fine with leaving these in the x-pack namespace.

cc @elastic/es-clients 

Closes #38623

### CODE REVIEW

**Comment by Mpdreamz** [comment]
@jasontedor @jakelandis preferences for updating the YAML tests? Can do a follow up PR or add commits to this one to do so.

**Comment by Mpdreamz** [comment]
Closing for now, realized I need to do more due diligence as I stepped outside. Don't want to waste anyone's time while I'm out. Will reopen later today when ready.

**Comment by Mpdreamz** [comment]
Updated the names inside the yaml files as well as their references in the various yaml test suites. 

This shoul now be ready for review.

**Comment by Mpdreamz** [comment]
run elasticsearch-ci/1

**Review by danielmitterdorfer — COMMENTED** [review]
Looks fine overall. I found a few more references in https://github.com/elastic/elasticsearch/blob/7b907c1bf5233878b1f7c9e03de237c8b99c5476/docs/build.gradle#L843 (and the following lines) that I think need to be changed as well?

**Comment by Mpdreamz** [comment]
Correct @danielmitterdorfer thought i caught all of those 👍  Updated the PR.

**Review by danielmitterdorfer — APPROVED** [review]
Thanks for iterating. If CI is happy then I'm happy. LGTM.

**Comment by Mpdreamz** [comment]
run elasticsearch-ci/bwc
run elasticsearch-ci/default-distro

**Comment by atorok** [comment]
@Mpdreamz I think you'll need to merge master in to get `elasticsearch-ci/bwc` passing.
You're missing the commit that adds the task called by this check,

**Comment by Mpdreamz** [comment]
Thanks @atorok rebased against master 🤞

**Comment by Mpdreamz** [comment]
run elasticsearch-ci/2

**Pull request merged**
