### PR TITLE
Added more information to the "deprecation" log for `skip: feature`

### PR DESCRIPTION
**Pull request by ldematte**
The log we introduced in https://github.com/elastic/elasticsearch/pull/104140 to warn about the deprecation of `skip: features` in favour of the less ambiguous `requires: test_runner_features` is not very useful on a test suite with many files and/or many tests (it just repeats the same message over and over again).

This PR changes the log to include the test name and the section location, so the info can be used to track down the exact place where to update the test.

For the reviewers: should I include other information, like the file name (or the test suite name)?
Or would it be better to keep the log message generic but include it just once per file/per test run?

### CODE REVIEW

**Comment by ldematte** [comment]
@elasticmachine update branch

**Comment by mosche** [comment]
Including the qualified test name would be helpful I think 👍 

Another idea, could we gather any parsing warning per test case and log those in a `@Before`. That way such warnings are associated with the corresponding test case when viewing using any kind of tool.

**Comment by ldematte** [comment]
That's an interesting idea, let me try something out.

**Comment by ldematte** [comment]
Closing this for now as it is too early - see https://github.com/elastic/elasticsearch/pull/104468

**Pull request closed without merging**
