### PR TITLE
Docs: Add ccr to the cat thread pool doc test

### PR DESCRIPTION
**Pull request by dnhatn**
Since #31251, we use the default distribution to test docs. With this
distribution, the cat thread-pool response will include the ccr
thread-pool. This commit adjusts `/_cat/thread_pool` doc to include ccr.

Relates #31251

### CODE REVIEW

**Comment by dnhatn** [comment]
The failed test is the one that I changed.

```
 REPRODUCE WITH: ./gradlew :docs:integTestRunner -Dtests.seed=5A6C4250CE63D6F6 -Dtests.class=org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT -Dtests.method="test {yaml=reference/cat/thread_pool/line_8}" -Dtests.security.manager=true -Dtests.locale=ru -Dtests.timezone=America/Rainy_River
ERROR   1165s | DocsClientYamlTestSuiteIT.test {yaml=reference/cat/thread_pool/line_8} <<< FAILURES!
   > Throwable #1: java.lang.Exception: Test abandoned because suite timeout was reached.
```

The regex becomes longer, but I am not sure if it's the cause of the timeout.

**Comment by dnhatn** [comment]
@elasticmachine  test this please

**Review by bleskes — APPROVED** [review]

**Review by martijnvg — APPROVED** [review]
LGTM

**Comment by dnhatn** [comment]
I think the test was timeout because of the presence of the two `.+` expressions.  A `.+`  regex is slow because it is greedy and matches all input (then backs off char by char). I replaced `.+` with `\S+`, we are good now.

**Comment by dnhatn** [comment]
Thanks @bleskes and @martijnvg for reviewing

**Pull request merged**
