### PR TITLE
Fix split package org.elasticsearch.cli

### PR DESCRIPTION
**Pull request by ChrisHegarty**
Fix the split package org.elasticsearch.cli, between server and the cli library. Move the server org.elasticsearch.cli package to org.elasticsearch.common.cli. Removing split packages is a prerequisite to modularization.

relates #78166

### CODE REVIEW

**Comment by ChrisHegarty** [comment]
@elasticmachine retest this please

**Comment by ChrisHegarty** [comment]
@elasticmachine retest this please

**Comment by ChrisHegarty** [comment]
@elasticmachine retest this please

**Review by grcevski — APPROVED** [review]
LGTM!

**Pull request merged**
