### PR TITLE
Fix S3HttpHandler chunked-encoding handling

### LINKED ISSUE #72358: AbstractSnapshotRepoTestKitRestTestCase#testRepositoryAnalysis fails with "Unable to verify integrity of data upload"
**Build scan**:

- https://gradle-enterprise.elastic.co/s/ug55b2ghwin2a
- https://gradle-enterprise.elastic.co/s/u56mg6brfudq6
- https://gradle-enterprise.elastic.co/s/5rfr4d7f7ywae
- https://gradle-enterprise.elastic.co/s/ujwp6yv2cxbnw
- https://gradle-enterprise.elastic.co/s/znj4ezd67y3kg

**Repro line**: e.g. `REPRODUCE WITH: ./gradlew ':x-pack:plugin:snapshot-repo-test-kit:qa:s3:integTest' --tests "org.elasticsearch.repositories.blobstore.testkit.S3SnapshotRepoTestKitIT.testRepositoryAnalysis" -Dtests.seed=987C4B3C71034593 -Dtests.locale=fr-CA -Dtests.timezone=Atlantic/Faeroe -Druntime.java=11`

**Reproduces locally?**: No

**Applicable branches**: 7.12, master (probably 7.13 and 7.x too)

**Failure history**: https://build-stats.elastic.co/goto/ec1e3eb777247512d6089a2fe118056c

**Failure excerpt**:

```
org.elasticsearch.repositories.blobstore.testkit.S3SnapshotRepoTestKitIT > testRepositoryAnalysis FAILED
            org.elasticsearch.client.ResponseException: method [POST], host [http://127.0.0.1:36341], URI [/_snapshot/repository/_analyze?blob_count=10&max_blob_size=1mb&timeout=120s&concurrency=4], status line [HTTP/1.1 500 Internal Server Error]
{
  "error": {
    "root_cause": [
      {
        "type": "uncategorized_execution_exception",
        "reason": "Failed execution"
      }
    ],
    "type": "repository_verification_exception",
    "reason": "[repository] analysis failed, you may need to manually remove [temp-analysis-DRAYv4byTmeQ9WrF8qKuzQ]",
    "caused_by": {
      "type": "repository_verification_exception",
      "reason": "[repository] failure processing [blob analysis [repository:temp-analysis-DRAYv4byTmeQ9WrF8qKuzQ/test-blob-7-6Sn4wUgZQXuaBegKSwPCjA, length=262144, seed=-3175868635373160859, readEarly=false, writeAndOverwrite=false]]",
      "caused_by": {
        "type": "uncategorized_execution_exception",
        "reason": "Failed execution",
        "caused_by": {
          "type": "execution_exception",
          "reason": "java.io.IOException: Unable to upload object [base_path/temp-analysis-DRAYv4byTmeQ9WrF8qKuzQ/test-blob-7-6Sn4wUgZQXuaBegKSwPCjA] using a single upload",
          "caused_by": {
            "type": "i_o_exception",
            "reason": "Unable to upload object [base_path/temp-analysis-DRAYv4byTmeQ9WrF8qKuzQ/test-blob-7-6Sn4wUgZQXuaBegKSwPCjA] using a single upload",
            "caused_by": {
              "type": "sdk_client_exception",
              "reason": "Unable to verify integrity of data upload. Client calculated content hash (contentMD5: 4J5vz4CfLgJcHZYO3qGtsw== in base 64) didn't match hash (etag: 93131e5ff888533a740cc7c0913276eb in hex) calculated by Amazon S3.  You may need to delete the data stored in Amazon S3. (metadata.conte
ntMD5: null, md5DigestStream: com.amazonaws.services.s3.internal.MD5DigestCalculatingInputStream@75d4ac01, bucketName: bucket, key: base_path/temp-analysis-DRAYv4byTmeQ9WrF8qKuzQ/test-blob-7-6Sn4wUgZQXuaBegKSwPCjA)"
            }
          }
        }
      }
    }
  },
  "status": 500
}
```

There is a mismatch between the MD5 checksum computed by the client and by the server, which in these cases seems to be our own internal `S3Fixture`. The server-side checksum computation is a little tricky because of all the different ways the data might be encoded and chunked -- it contains no obvious bugs but nor does it obviously contain no bugs.

I opened https://github.com/elastic/elasticsearch/pull/72321 to try and improve the reproducibility of these failures.

### PR DESCRIPTION
**Pull request by DaveCTurner**
The `S3HttpHandler` reads the contents of the uploaded blob, but if the
upload used chunked encoding then the reader would skip one or more
`\r\n` sequences if they appeared at the start of a chunk.

This commit reworks the reader to be stricter about its interpretation
of chunks, and removes some indirection via streams since we can work
pretty much entirely on the underlying `BytesReference` instead.

Closes #72358

### CODE REVIEW

**Review by original-brownbear — APPROVED** [review]
I think https://github.com/elastic/elasticsearch/pull/72365 is the simpler option, but this one LGTM as well.
If we want to go with this one, can we add https://github.com/elastic/elasticsearch/pull/72365/files#diff-47fd5429e7187cd1b173e53b38a5896c3810c6b89890b84e89334536288c6b84R124 to it to get more (and easier to debug) coverage on this though? :)

**Comment by DaveCTurner** [comment]
Ok I shamelessly pinched some of your ideas from #72365.

**Review by tlrx — APPROVED** [review]
LGTM, thanks for fixing this David

**Comment by DaveCTurner** [comment]
Thanks both 🚀

**Pull request merged**
