### PR TITLE
Makes the same_shard host dynamically updatable

### LINKED ISSUE #22992: cluster.routing.allocation.same_shard.host is not a dynamic setting (?)
**Elasticsearch version**:
2.4

Documentation 

https://www.elastic.co/guide/en/elasticsearch/reference/2.3/shards-allocation.html#_shard_allocation_settings

```
The following dynamic settings may be used to control shard allocation and recovery:

cluster.routing.allocation.same_shard.host
Allows to perform a check to prevent allocation of multiple instances of the same shard on a single host, based on host name and host address. Defaults to false, meaning that no check is performed by default. This setting only applies if multiple nodes are started on the same machine.
```

VS

https://github.com/elastic/elasticsearch/issues/17693#issuecomment-209121270

```
The reason for this is that is "cluster.routing.allocation.same_shard.host" is not a dynamic setting, it needs to be set at startup time currently.
```

not sure if the story applies to v5.x too.

also on a slightly different note it'd be great to clarify explicitly on which node types should this be set (data/master/client/ingest). 
https://github.com/elastic/elasticsearch/issues/17693#issuecomment-209182043
seems to point out the answer is: "set to all nodes belonging to the cluster regardless of their role"

### PR DESCRIPTION
**Pull request by abeyad**
Previously, cluster.routing.allocation.same_shard.host was not a dynamic
setting and could not be updated after startup.  This commit changes the
behavior to allow the setting to be dynamically updatable.  The
documentation already states that the setting is dynamic so no
documentation changes are required.

Closes #22992

### CODE REVIEW

**Review by dakrone — APPROVED** [review]
LGTM, but I think we should add a blurb in the documentation for the setting that it can be dynamically updated

**Comment by abeyad** [comment]
@dakrone thanks for the review!  The docs already mention this setting in the list of dynamically updatable ones for shard allocation - hence the docs were wrong all this time up until this fix.  Is that what you meant?

**Comment by dakrone** [comment]
> hence the docs were wrong all this time up until this fix. Is that what you meant?

Ohh cool, glad we're fixing ES to reflect the docs then! Thanks!

**Comment by abeyad** [comment]
5.x commit: 388501ec41be86207bf610c9eb1f15d3a185245b

**Comment by jpcarey** [comment]
I think we should still fix the docs for the versions where it was not dynamically updatable.

**Pull request merged**
