### PR TITLE
Exclude unsearchable shards in search API

### PR DESCRIPTION
**Pull request by dnhatn**
Relates #93010

### CODE REVIEW

**Comment by dnhatn** [comment]
I talked to @Tim-Brooks on this PR. We agreed to proceed with his PR (https://github.com/elastic/elasticsearch/pull/93612) as we are not ready to use only searchable shards for the GET API yet. I have removed the changes for the GET API from this.

**Comment by dnhatn** [comment]
run elasticsearch-ci/part-2

**Review by Tim-Brooks — APPROVED** [review]
LGTM

**Comment by dnhatn** [comment]
Thanks Tim!

**Pull request merged**
