### PR TITLE
 Ensure SHA256 is not used in tests

### LINKED ISSUE #42267: Test failure: org.elasticsearch.xpack.security.authc.support.CachingUsernamePasswordRealmTests.testCacheSettings
```
org.elasticsearch.xpack.security.authc.support.CachingUsernamePasswordRealmTests > testCacheSettings FAILED
    java.lang.IllegalArgumentException: unknown hash function [sha256]
        at __randomizedtesting.SeedInfo.seed([183260F6BD6AF4D7:455D85248CE5C0FB]:0)
        at org.elasticsearch.xpack.core.security.authc.support.Hasher.resolve(Hasher.java:454)
        at org.elasticsearch.xpack.security.authc.support.CachingUsernamePasswordRealm.<init>(CachingUsernamePasswordRealm.java:40)
        at org.elasticsearch.xpack.security.authc.support.CachingUsernamePasswordRealmTests$1.<init>(CachingUsernamePasswordRealmTests.java:81)
        at org.elasticsearch.xpack.security.authc.support.CachingUsernamePasswordRealmTests.testCacheSettings(CachingUsernamePasswordRealmTests.java:81)
```
It reproduces ! (against master / commit: 570e8edc1e25f1c5197307f40fd4f73e0950620f) 
```
./gradlew :x-pack:plugin:security:test --tests "org.elasticsearch.xpack.security.authc.support.CachingUsernamePasswordRealmTests.testCacheSettings" -Dtests.seed=183260F6BD6AF4D7 -Dtests.security.manager=true -Dtests.locale=shi-Latn-MA -Dtests.timezone=Asia/Kathmandu -Dcompiler.java=12 -Druntime.java=11
```

### PR DESCRIPTION
**Pull request by jkakavas**
SHA256 was recently added to the Hasher class in order to be used
in the TokenService. A few tests were still using values() to get
the available algorithms from the Enum and it could happen that
SHA256 would be picked up by these.
This change adds an extra convenience method
(Hasher#getAvailableAlgoCacheHash) and enures that only this and
Hasher#getAvailableAlgoStoredHash are used for getting the list of
available password hashing algorithms in our tests.

Resolves #42267

### CODE REVIEW

**Comment by jaymode** [comment]
my two cents is that we should probably make values for hasher a forbidden API or just remove it from being an enum. It seems like it would be too easy for this to pop back up.

**Comment by jkakavas** [comment]
I contemplated other options too. I attempted to change this from an Enum when doing #31234 but circled back, not really sure what was the issue though. I also thought about moving the `SHA256` to the TokenService as this is the only option with no salt ( well, `NOOP` too ). 
I see your point and I think making `values()` a forbidden API makes sense. I don't worry that this will make it into a password hashing code since we use `resolve` and `SHA256` is not available there, but it might well creep up to a test case with someone getting a random from `Hasher.values()` .

**Comment by jaymode** [comment]
> but it might well creep up to a test case with someone getting a random from Hasher.values() .

This is what I was thinking of.

**Comment by talevy** [comment]
fyi, I found another test that relates to this and muted two related tests in #42304

**Review by tvernum — APPROVED** [review]
LGTM

**Pull request merged**
