### PR TITLE
Do not release safe commit with CancellableThreads

### LINKED ISSUE #39585: CI failures due to file handle leaks
CI link: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+intake/2317/console

This has failed a few times with similar errors recently, the earliest being Jan. 7 2019. 

Does not reproduce locally, reproduce line:
```
./gradlew :server:integTest \
  -Dtests.seed=F5F3A811C4C7323A \
  -Dtests.class=org.elasticsearch.action.admin.indices.create.SplitIndexIT \
  -Dtests.security.manager=true \
  -Dtests.locale=en-US \
  -Dtests.timezone=UTC \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

Stack Trace:
```
java.lang.RuntimeException: file handle leaks: [FileChannel(/var/lib/jenkins/workspace/elastic+elasticsearch+master+intake/server/build/testrun/integTest/J1/temp/org.elasticsearch.action.admin.indices.create.SplitIndexIT_F5F3A811C4C7323A-001/tempDir-002/custom/FmRRWOOIXe/2/wyqeqwxnS2a6pcZROod50w/1/index/_1.fdt), FileChannel(/var/lib/jenkins/workspace/elastic+elasticsearch+master+intake/server/build/testrun/integTest/J1/temp/org.elasticsearch.action.admin.indices.create.SplitIndexIT_F5F3A811C4C7323A-001/tempDir-002/custom/FmRRWOOIXe/2/wyqeqwxnS2a6pcZROod50w/1/index/_1_Asserting_0.pos), FileChannel(/var/lib/jenkins/workspace/elastic+elasticsearch+master+intake/server/build/testrun/integTest/J1/temp/org.elasticsearch.action.admin.indices.create.SplitIndexIT_F5F3A811C4C7323A-001/tempDir-002/custom/FmRRWOOIXe/2/wyqeqwxnS2a6pcZROod50w/1/index/_1_Asserting_0.doc), FileChannel(/var/lib/jenkins/workspace/elastic+elasticsearch+master+intake/server/build/testrun/integTest/J1/temp/org.elasticsearch.action.admin.indices.create.SplitIndexIT_F5F3A811C4C7323A-001/tempDir-002/custom/FmRRWOOIXe/2/wyqeqwxnS2a6pcZROod50w/1/index/_1_Asserting_0.tip), FileChannel(/var/lib/jenkins/workspace/elastic+elasticsearch+master+intake/server/build/testrun/integTest/J1/temp/org.elasticsearch.action.admin.indices.create.SplitIndexIT_F5F3A811C4C7323A-001/tempDir-002/custom/FmRRWOOIXe/2/wyqeqwxnS2a6pcZROod50w/1/index/_1.dim)]
	at __randomizedtesting.SeedInfo.seed([F5F3A811C4C7323A]:0)
	at org.apache.lucene.mockfile.LeakFS.onClose(LeakFS.java:63)
	at org.apache.lucene.mockfile.FilterFileSystem.close(FilterFileSystem.java:77)
	at org.apache.lucene.mockfile.FilterFileSystem.close(FilterFileSystem.java:78)
	at org.apache.lucene.util.TestRuleTemporaryFilesCleanup.afterAlways(TestRuleTemporaryFilesCleanup.java:228)
	at com.carrotsearch.randomizedtesting.rules.TestRuleAdapter$1.afterAlways(TestRuleAdapter.java:31)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:43)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception
	at org.apache.lucene.mockfile.LeakFS.onOpen(LeakFS.java:46)
	at org.apache.lucene.mockfile.HandleTrackingFS.callOpenHook(HandleTrackingFS.java:81)
	at org.apache.lucene.mockfile.HandleTrackingFS.newFileChannel(HandleTrackingFS.java:197)
	at org.apache.lucene.mockfile.HandleTrackingFS.newFileChannel(HandleTrackingFS.java:166)
	at java.nio.channels.FileChannel.open(FileChannel.java:287)
	at java.nio.channels.FileChannel.open(FileChannel.java:335)
	at org.apache.lucene.store.NIOFSDirectory.openInput(NIOFSDirectory.java:81)
	at org.elasticsearch.index.store.FsDirectoryService$HybridDirectory.openInput(FsDirectoryService.java:157)
	at org.apache.lucene.store.FilterDirectory.openInput(FilterDirectory.java:100)
	at org.apache.lucene.store.FilterDirectory.openInput(FilterDirectory.java:100)
	at org.apache.lucene.codecs.compressing.CompressingStoredFieldsReader.<init>(CompressingStoredFieldsReader.java:150)
	at org.apache.lucene.codecs.compressing.CompressingStoredFieldsFormat.fieldsReader(CompressingStoredFieldsFormat.java:121)
	at org.apache.lucene.codecs.lucene50.Lucene50StoredFieldsFormat.fieldsReader(Lucene50StoredFieldsFormat.java:173)
	at org.apache.lucene.codecs.asserting.AssertingStoredFieldsFormat.fieldsReader(AssertingStoredFieldsFormat.java:43)
	at org.apache.lucene.index.SegmentCoreReaders.<init>(SegmentCoreReaders.java:126)
	at org.apache.lucene.index.SegmentReader.<init>(SegmentReader.java:83)
	at org.apache.lucene.index.ReadersAndUpdates.getReader(ReadersAndUpdates.java:172)
	at org.apache.lucene.index.BufferedUpdatesStream$SegmentState.<init>(BufferedUpdatesStream.java:271)
	at org.apache.lucene.index.FrozenBufferedUpdates.openSegmentStates(FrozenBufferedUpdates.java:329)
	at org.apache.lucene.index.FrozenBufferedUpdates.forceApply(FrozenBufferedUpdates.java:222)
	at org.apache.lucene.index.FrozenBufferedUpdates.tryApply(FrozenBufferedUpdates.java:160)
	at org.apache.lucene.index.IndexWriter.lambda$publishFrozenUpdates$3(IndexWriter.java:2589)
	at org.apache.lucene.index.IndexWriter.processEvents(IndexWriter.java:5112)
	at org.apache.lucene.index.IndexWriter.getReader(IndexWriter.java:507)
	at org.apache.lucene.index.StandardDirectoryReader.doOpenFromWriter(StandardDirectoryReader.java:294)
	at org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:269)
	at org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:259)
	at org.apache.lucene.index.FilterDirectoryReader.doOpenIfChanged(FilterDirectoryReader.java:112)
	at org.apache.lucene.index.DirectoryReader.openIfChanged(DirectoryReader.java:140)
	at org.apache.lucene.search.SearcherManager.refreshIfNeeded(SearcherManager.java:156)
	at org.apache.lucene.search.SearcherManager.refreshIfNeeded(SearcherManager.java:58)
	at org.apache.lucene.search.ReferenceManager.doMaybeRefresh(ReferenceManager.java:176)
	at org.apache.lucene.search.ReferenceManager.maybeRefreshBlocking(ReferenceManager.java:253)
	at org.elasticsearch.index.engine.InternalEngine$ExternalSearcherManager.refreshIfNeeded(InternalEngine.java:319)
	at org.elasticsearch.index.engine.InternalEngine$ExternalSearcherManager.refreshIfNeeded(InternalEngine.java:294)
	at org.apache.lucene.search.ReferenceManager.doMaybeRefresh(ReferenceManager.java:176)
	at org.apache.lucene.search.ReferenceManager.maybeRefresh(ReferenceManager.java:225)
	at org.elasticsearch.index.engine.InternalEngine.refresh(InternalEngine.java:1559)
	at org.elasticsearch.index.engine.InternalEngine.maybeRefresh(InternalEngine.java:1536)
	at org.elasticsearch.index.shard.IndexShard.scheduledRefresh(IndexShard.java:2936)
	at org.elasticsearch.index.IndexService.maybeRefreshEngine(IndexService.java:759)
	at org.elasticsearch.index.IndexService.access$200(IndexService.java:99)
	at org.elasticsearch.index.IndexService$AsyncRefreshTask.runInternal(IndexService.java:883)
	at org.elasticsearch.common.util.concurrent.AbstractAsyncTask.run(AbstractAsyncTask.java:141)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:681)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
```

Logs: 
[consoleText.txt](https://github.com/elastic/elasticsearch/files/2921002/consoleText.txt)

### PR DESCRIPTION
**Pull request by dnhatn**
We are leaking a FileChannel in #39585 if we release a safe commit with CancellableThreads. Although it is a bug in [Lucene](https://github.com/elastic/elasticsearch/issues/39585#issuecomment-654995186) where we do not [close](https://github.com/apache/lucene-solr/blob/d3f4b21deb0056098e9e888a6b9d72e0bf2d0834/lucene/core/src/java/org/apache/lucene/store/NIOFSDirectory.java#L81-L82) a FileChannel if we [failed](https://github.com/apache/lucene-solr/blob/82692e76e054d3e6938034e96a4e9632bd9f7a70/lucene/core/src/java/org/apache/lucene/store/NIOFSDirectory.java#L107) to create a NIOFSIndexInput, I think it's safer if we release a safe commit using the generic thread pool instead.

Closes #39585
Relates #45409

### CODE REVIEW

**Review by original-brownbear — APPROVED** [review]
LGTM thanks Nhat :) could we add a reasonable TODO that asks to simplify things again once the Lucene situation is fixed maybe?

**Comment by dnhatn** [comment]
@original-brownbear Thanks for reviewing. I've added a comment explaining why we prefer releasing a safe commit using the generic thread pool (see https://github.com/elastic/elasticsearch/pull/59182/commits/ff0f8f812844a8eccad21879d8928a9d9513fa6e).

**Comment by dnhatn** [comment]
> testSendSnapshotSendsOps was fixed in https://github.com/elastic/elasticsearch/commit/865b6b5880ddca4b2b05cb9c28d343a528b92437.

@elasticmachine update branch.

**Comment by dnhatn** [comment]
@elasticmachine update branch

**Pull request merged**
