### PR TITLE
[DOCS] Adds release highlight pages

### PR DESCRIPTION
**Pull request by lcawl**
This PR creates the file structure for a new set of "release highlight" pages. 

These highlight pages will summarize the most significant changes in each release (starting in 6.3.0). 

At this time I have created the highlights at the same level as the release notes in the Elasticsearch Reference's table of contents:  
toc

However, once we know the final implementation for the changelog files, we can restructure the table of contents as necessary.

NOTE: At this time, these highlight pages are not meant to replace the blogs that go out with releases (e.g. https://www.elastic.co/blog/elasticsearch-6-2-0-released) though some of the same items might be covered in both places.

### CODE REVIEW

**Review by pcsanwald — COMMENTED** [review]
These changes LGTM, but don't we also need 6.3 and 6.4? or were you going to do those in their respective branches?

**Comment by lcawl** [comment]
I was going to create similar pages in the 6.4, 6.3, and 5.6 branches at this point. If that's not what you had in mind, let me know!

**Review by pcsanwald — APPROVED** [review]
that sounds fine to me. reason I ask is there's an item we wanted to add for 6.4

**Comment by javanna** [comment]
This collided with the removal or the changelog, see #30593 . I pushed a quick fix to master but I am pretty sure it is only a temporary work-around to make the docs build work again. See 098b3b7fb4a9964aec8530948d66424f4612db9e

**Comment by javanna** [comment]
See also e1d675c690b0b4d5d224205968c463d7a0dc7525 for master, and the corresponding e40b88476e7999b233d770bbf97065b9724b76cf for 6.x, 35a61de89ff0e9b8d4d953718c5e2dba5b016cb3 for 6.3 and ada81476d00604007ff3bdd68e623c10dcaee84d for 5.6. I took the highlights page out of the inclusions as it caused problems.

**Comment by lcawl** [comment]
Thanks, I've re-added it now that the builds are clean again: elastic/elasticsearch@ c0d639e2778a076e22a88b02028d7fb64bc915eb

**Pull request merged**
