### PR TITLE
Remove generic on AggregatorFactory

### PR DESCRIPTION
**Pull request by polyfractal**
`AggregatorFactory` was generic over itself, but it doesn't appear we use this functionality anywhere (e.g. to allow the super class to declare arguments/return types generically for subclasses to override).  Most places use a wildcard constraint, and even when a concrete type is specified it wasn't used.

But since AggFactories are widely used, this led to the generic touching many pieces of code and making type signatures fairly complex

It's possible I'm totally missing something, but after the replace everything still compiles, tests seem to run fine, I don't see any missing functionality, etc.

### CODE REVIEW

**Review by jpountz — APPROVED** [review]
<3

**Comment by polyfractal** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by polyfractal** [comment]
@elasticmachine update branch

**Comment by polyfractal** [comment]
@elasticmachine update branch

**Pull request merged**
