### PR TITLE
DOCS: Mention compile-time script options

### PR DESCRIPTION
**Pull request by wetneb**
The documentation about scripts does not mention the existence of compile-time options, so I think it would be good to add some insights about how this works. I have added the description at the very end since I expect it is not many people will look for, but such that it can still be found with Ctrl-F.

### CODE REVIEW

**Comment by wetneb** [comment]
(I have signed the CLA a few minutes ago.)

**Review by jrodewig — COMMENTED** [review]
@wetneb Thanks for this PR. Your changes look good to me, but I want input from an engineer more familiar with scripting before moving forward.

@stu-elastic @jdconrad Would you mind taking a look at your convenience?
While I don't think it should block this PR, I also wonder if we should document the `options` param higher on the page, similar to `lang`, `source`, etc. Is there a reason we've avoided this?

**Comment by jrodewig** [comment]
@elasticmachine test this please

**Review by jdconrad — COMMENTED** [review]
I don't really want to add this documentation, yet. `options` is currently only used internally for content-type. Adding this implies there are actual behavioral changes users can make which I find confusing since there are no actual options to work with.

**Comment by jrodewig** [comment]
That makes sense to me. I'll close this PR for the time being. Thanks @jdconrad.

**Pull request closed without merging**
