### PR TITLE
[DOCS] Fix docs for user profiles

### PR DESCRIPTION
**Pull request by bytebilly**
Fixes:
- `POST /_security/user/_has_privileges` should be `POST /_security/profile/_has_privileges`
- Privileges must be contained into `privileges`

### CODE REVIEW

**Review by slobodanadamovic — APPROVED** [review]
LGTM 

Thanks for fixing this 🙏

**Comment by bytebilly** [comment]
@slobodanadamovic whoops, I found another problem in the same snippet and fixed in this PR, do you mind reviewing again? Thanks!

**Review by slobodanadamovic — APPROVED** [review]

**Comment by slobodanadamovic** [comment]
> @slobodanadamovic whoops, I found another problem in the same snippet and fixed in this PR, do you mind reviewing again? Thanks!

Nice catch! 👍

**Comment by abdonpijpelink** [comment]
@elasticsearchmachine run elasticsearch-ci/docs-check

**Review by abdonpijpelink — APPROVED** [review]
LGTM from the docs side too.

**Comment by abdonpijpelink** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.11|[](https://github.com/elastic/elasticsearch/pull/102517)|
|✅|8.10|[](https://github.com/elastic/elasticsearch/pull/102518)|
|✅|8.9|[](https://github.com/elastic/elasticsearch/pull/102519)|
|✅|8.8|[](https://github.com/elastic/elasticsearch/pull/102520)|
|✅|8.7|[](https://github.com/elastic/elasticsearch/pull/102521)|
|✅|8.6|[](https://github.com/elastic/elasticsearch/pull/102522)|
|✅|8.5|[](https://github.com/elastic/elasticsearch/pull/102523)|
|✅|8.4|[](https://github.com/elastic/elasticsearch/pull/102524)|
|✅|8.3|[](https://github.com/elastic/elasticsearch/pull/102525)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
