### PR TITLE
Docs: fix typo in datehistogram

### PR DESCRIPTION
**Pull request by JimiHFord**

### CODE REVIEW

**Comment by nik9000** [comment]
The fix looks good to me. Let's see if a comment is enough to pick up the CLA.

**Comment by JimiHFord** [comment]
Whoopsies- just signed the agreement - not sure if there's a way to re-kick that check

**Comment by JimiHFord** [comment]
🎉

**Comment by nik9000** [comment]
Commenting kicks it off!

**Comment by JimiHFord** [comment]
sweet - do we know if it was your comment that kicked it off or mine?

**Comment by nik9000** [comment]
> sweet - do we know if it was your comment that kicked it off or mine?

I have no idea and I'm not really sure how to tell....

I'll merge this in a few hours if no other committer gets to it first.

**Comment by nik9000** [comment]
Merged and forward ported to 6.x and master. Thanks @JimiHFord !

**Pull request merged**
