### PR TITLE
Set meta data for pipeline aggregations

### LINKED ISSUE #16484: Pipeline aggregations do not return metadata
https://www.elastic.co/guide/en/elasticsearch/reference/2.2/agg-metadata.html

This works fine for bucket and metrics aggregations, but for pipeline aggregations the supplied metadata isn't returned with the result.

This is a blocker for the .NET client as we're trying to leverage aggregation metadata for deserialization.

### PR DESCRIPTION
**Pull request by gmarz**
Closes #16484

### CODE REVIEW

**Comment by colings86** [comment]
LGTM we should probably back port this to 2.x and 2.2 as well

**Comment by colings86** [comment]
Actually, one minor thing, could you add a test to MetaDataIT to test metadata with pipeline aggs?

**Comment by gmarz** [comment]
@colings86 thanks for the review.  Definitely, I'll add a test shortly.

**Comment by gmarz** [comment]
@colings86 mind giving this another review?

I've changed MetaDataIT completely so that we test meta data on all three aggregation types.  While doing this though, I discovered that there wasn't a way to set meta data via MetricsAggregationBuilder, so fixed that as well.

**Comment by colings86** [comment]
@gmarz LGTM, thanks for fixing this. The test looks good too and is going to be important as the aggregation refactoring I am doing at the moment will change the builders quite a bit so it's good that I have something to catch it if I break this in that refactoring :)

**Comment by gmarz** [comment]
Merged to master and back ported to 2.0-2.x

**Pull request merged**
