### PR TITLE
[DOCS] Fix typo in take snapshot docs

### PR DESCRIPTION
**Pull request by Yzzzi**

### CODE REVIEW

**Comment by jrodewig** [comment]
@Yzzzi Do you mind signing our CLA so that we can merge this change:
https://www.elastic.co/contributor-agreement

Please ensure you sign using the same email address associated with your commit. You can find that email address here:
https://github.com/elastic/elasticsearch/commit/f14df537b527aaa7ccc01cdf96e7ed4bdd96ba5c.patch

A signed CLA is required before we can accept this PR. Thanks!

**Comment by Yzzzi** [comment]
Singed with wrong e-mail, sorry, now all done. At least I think so. How can i check it?

**Comment by jrodewig** [comment]
@Yzzzi. Looks good now. Thanks!

**Comment by jrodewig** [comment]
@elasticmachine test this please

**Review by jrodewig — APPROVED** [review]

**Pull request merged**
