### PR TITLE
Remove redundant method from StoreKeyConfig

### PR DESCRIPTION
**Pull request by jkakavas**
StoreKeyConfig#x509Certificates was introduced in #72207 in order
to retrieve all certificates from the keystore used for HTTP TLS
and then filter out to get the CA certificate. Since we explicitly
add the CA key/cert as a PrivateKeyEntry on startup, we can
iterate on the PrivateKeyEntry objects instead.

### CODE REVIEW

**Review by tvernum — APPROVED** [review]
LGTM.

**Comment by jkakavas** [comment]
@elasticmachine update branch

**Comment by jkakavas** [comment]
@elasticmachine update branch

**Comment by jkakavas** [comment]
FIPS checks failures are irrelevant and we're working on them, will merge this nevertheless

**Pull request merged**
