### PR TITLE
Upgrade lucene to 5.5.2

### PR DESCRIPTION
**Pull request by dpursehouse**

### CODE REVIEW

**Comment by jpountz** [comment]
Thanks @dpursehouse, this looks good. I'll merge.

**Comment by jpountz** [comment]
Changing the Lucene version on a patch release is a bit scary so  I will only merge it to the 2.4 branch (which should be released "soon".

**Comment by rmuir** [comment]
I have two concerns about upgrading 2.x to this release:

https://github.com/apache/lucene-solr/commits/branch_6x/lucene/core/src/java/org/apache/lucene/util/Version.java

So 5.5.2 does not even exist until *after* the 6.2 release. All it takes is a bug around version handling to create a big problem. This is not unheard of. 

More concerning is, its unclear to me if the situation has ever been tested (which would easily alleviate both my concerns!). For that we have two mechanisms: TestBackwardsCompatibility (junit test) and smoketester (python). But the latter just uses the test indexes from the former, and doesn't have any additional version coverage, only the test indexes committed to the tree are tested:

https://github.com/apache/lucene-solr/blob/releases/lucene-solr/6.1.0/dev-tools/scripts/smokeTestRelease.py#L1292-L1294

So if previous version M was released after newer version N, we can be sure its never ever been tested (N reading index of M)?

**Comment by jpountz** [comment]
This is valid concern indeed. 5.5.2 indices are already on the 6.0/6.1 branches and TestBackwardsCompatibility passes on both branches so I think we're good?

**Comment by rmuir** [comment]
I will relent but i still insist its not the same thing. Those changes were done after the release, along with other changes which have been backported to those branches, such as addition of version constants :)

I know its been changed to no longer be an enum, and really many of these changes are just helpful and minor, I'm just saying this is how bugs can happen.

**Comment by jpountz** [comment]
I played with TestBackwardCompatibility and the actual 6.0/6.1 releases and all seemed fine. There are some good fixes in this bugfix release (eg. LUCENE-7132) so I will merge this PR tomorrow if there are no objections.

**Comment by jpountz** [comment]
Merged via 39869b54f5a2b83af2d94e573670d7bf287d7672

**Pull request closed without merging**
