### PR TITLE
Change default value for data stream lifecycle poll interval to 5 mins

### PR DESCRIPTION
**Pull request by andreidan**

### CODE REVIEW

**Review by mattc58 — APPROVED** [review]
+1, as discussed. Do we need to make any documentation update to this though? Do we mention the poll interval there?

**Comment by gmarouli** [comment]
Good catch @mattc58 , indeed we document the default value here: https://www.elastic.co/guide/en/elasticsearch/reference/master/data-stream-lifecycle-settings.html

**Review by gmarouli — APPROVED** [review]
LGTM + @mattc58's comment about documentation. Thanks for addressing this so quickly @andreidan

**Comment by andreidan** [comment]
@elasticmachine update branch

**Pull request merged**
