### PR TITLE
Removing top-level filter parameter from search API.

### LINKED ISSUE #8862: Remove top level `filter` parameter
Let's remove top level filter (https://github.com/elasticsearch/elasticsearch/issues/4119) from the product.  It can be confusing to end users given that we no longer document the top level filter in our guides (we only talk about post_filter now), but Marvel auto-fill still shows it as a valid clause at the top level.

### PR DESCRIPTION
**Pull request by ycombinator**
Closes #8862.

### CODE REVIEW

**Comment by jpountz** [comment]
Thanks for taking care of this! The change to QueryPhase looks good however I don't think we should keep tests for features we removed, so I think we should just push the change to QueryPhase.

**Comment by ycombinator** [comment]
@jpountz Thanks. I was wondering about "negative" tests. I'll remove it.

**Comment by jpountz** [comment]
LGTM

**Comment by clintongormley** [comment]
@ycombinator you want to merge it in? master branch only, thanks

**Pull request merged**
