### PR TITLE
Create fallback settings only once in Netty4Transport

### PR DESCRIPTION
**Pull request by hanbj**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by cbuescher** [comment]
@hanbj thanks, I will kick of a CI test run
@elasticmachine test this please

**Comment by cbuescher** [comment]
@elasticmachine test this again please

**Comment by cbuescher** [comment]
@hanbj thanks, this looks good to me. I only want to ping @jasontedor before merging this in case he has anything to add, since he's most knowledgable in this area.

**Comment by cbuescher** [comment]
@hanbj I also took the liberty to rephrase the topic slightly, let me know if you disagree in any way.

**Review by cbuescher — APPROVED** [review]

**Comment by hanbj** [comment]
@cbuescher  Yes, of course， I agree，Thank you.  I'm just beginning to study Es's source code and there are many directions for you to learn.

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by cbuescher** [comment]
@hanbj I was going to merge this but just saw the current merge conflict. It seems the class has changed. Would you mind checking if the change you proposed still applies and update the PR in this case?

**Comment by hanbj** [comment]
@cbuescher ok，thanks

**Comment by cbuescher** [comment]
@hanbj thanks for the PR and sorry this didn't make it in.

**Pull request closed without merging**
