### PR TITLE
[DLM] Extend the simulate template API to support include defaults

### PR DESCRIPTION
**Pull request by gmarouli**
In this PR we are extending the following endpoints to support the query param `include_defaults`:

- `POST /_index_template/_simulate/<index-template>`
- `POST /_index_template/_simulate_index/<index>`

Part of: https://github.com/elastic/elasticsearch/issues/93596

### CODE REVIEW

**Review by andreidan — COMMENTED** [review]
Thanks for adding this Mary

Could we illustrate this parameter in the yaml tests? 
There're two `10_basic.yml` files under `indices.simulate_index_template` and `indices.simulate_template` folders. I believe these tests will reveal we also need to update the json rest spec

**Comment by gmarouli** [comment]
> Please reference the meta issue in the description ( #93596 )

Done, I will remember to add it from now on.

> Could we illustrate this parameter in the yaml tests? There're two `10_basic.yml` files under `indices.simulate_index_template` and `indices.simulate_template` folders. I believe these tests will reveal we also need to update the json rest spec

Ah good catch, yes I will.

**Comment by gmarouli** [comment]
@elasticmachine run elasticsearch-ci/part-1

**Comment by gmarouli** [comment]
Opened https://github.com/elastic/elasticsearch/issues/94896 for the test failure because it appeared to be reproducible.

**Comment by gmarouli** [comment]
@elasticmachine  update branch

**Review by andreidan — APPROVED** [review]
LGTM, thanks for working on this Mary 🚀

**Pull request merged**
