### PR TITLE
Fix double lookup failure on ESQL

### LINKED ISSUE #111398: ESQL: double lookup failure
### Description

```
PUT localhost:9200/test
{
    "mappings": {
        "properties": {
            "foo": {
                "type": "keyword"
            },
            "field11": {
                "type": "integer"
            },
            "field12": {
                "type": "long"
            }
        }
    }
}
```

```
POST localhost:9200/_bulk
{"index": {"_index":"test"}}
{"foo": "bar","field11":"123","field12":5}
{"index": {"_index":"test"}}
{"foo": "bar","field11":"123","field12":5}
```

```
{
    "query": "from test | lookup test2 on foo | lookup test3 on foo",
    "tables": {
        "test2": {
            "foo": {"keyword": ["bar"]},
            "field21": {"long": [123]},
            "field22": {"long": [123]}
        },
        "test3": {
            "foo": {"keyword": ["bar"]},
            "field31": {"long": [5]},
            "field32": {"long": [5]}
        }
    }
}
```

throws

```
[2024-07-29T12:35:05,516][WARN ][r.suppressed             ] [runTask-0] path: /_query, params: {format=txt, error_trace=true}, status: 500 java.lang.ArrayIndexOutOfBoundsException: Index 7 out of bounds for length 7
        at org.elasticsearch.compute.data.Page.getBlock(Page.java:135)
        at org.elasticsearch.xpack.esql.planner.LocalExecutionPlanner.lambda$alignPageToAttributes$1(LocalExecutionPlanner.java:302)
        at org.elasticsearch.compute.operator.OutputOperator.doAddInput(OutputOperator.java:66)
        at org.elasticsearch.compute.operator.SinkOperator.addInput(SinkOperator.java:32)
        at org.elasticsearch.compute.operator.Driver.runSingleLoopIteration(Driver.java:255)
        at org.elasticsearch.compute.operator.Driver.run(Driver.java:178)
        at org.elasticsearch.compute.operator.Driver$1.doRun(Driver.java:364)
```

### PR DESCRIPTION
**Pull request by jackpan123**
Fix double lookup failure on ESQL (Closes #111398 ).
I also try three times LOOKUP, it is fine, result like below:
```
 curl -XPOST "http://localhost:9200/_query?format=txt" -H "kbn-xsrf: reporting" -H "Content-Type: application/json" -d'                                                                                                                                                                   ─╯
{
    "query": "from test | lookup test2 on foo | lookup test3 on foo | lookup test4 on foo",
    "tables": {
        "test2": {
            "foo": {"keyword": ["bar"]},
            "field21": {"long": [123]},
            "field22": {"long": [123]}
        },
        "test3": {
            "foo": {"keyword": ["bar"]},
            "field31": {"long": [5]},
            "field32": {"long": [5]}
        },
        "test4": {
            "foo": {"keyword": ["bar"]},
            "field41": {"long": [6]},
            "field42": {"long": [6]}
        }
    }
}'
    field11    |    field12    |      foo      |    field21    |    field22    |    field31    |    field32    |    field41    |    field42    
---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------+---------------
123            |5              |bar            |123            |123            |5              |5              |6              |6              
123            |5              |bar            |123            |123            |5              |5              |6              |6 
```

### CODE REVIEW

**Comment by jackpan123** [comment]
Can someone help me assign some labels?

**Review by alex-spies — APPROVED** [review]
Thanks a lot for your contribution, @jackpan123, nice find!

The fix looks good to me. We will not be able to _close_ https://github.com/elastic/elasticsearch/issues/111398 with this, though. Because we'd have to add tests to avoid regressions in the future - but more importantly because `LOOKUP` is still under development and currently changing a lot, so that the corresponding tests are disabled right now.

**Comment by alex-spies** [comment]
@elasticsearchmachine test this please

**Comment by alex-spies** [comment]
@elasticsearchmachine generate changelog

**Comment by alex-spies** [comment]
@elasticsearchmachine test this please

**Pull request merged**
