### PR TITLE
[TEST] Don't assert order of data frame analytics audit messages

### LINKED ISSUE #48035: [CI] RunDataFrameAnalyticsIT.testLazyAssignmentWithModelMemoryLimitTooHighForAssignment fails
The test `org.elasticsearch.xpack.ml.integration.RunDataFrameAnalyticsIT.testLazyAssignmentWithModelMemoryLimitTooHighForAssignment` failed on master today:

https://gradle-enterprise.elastic.co/s/duk42yubl5ziw

With the error:

> Expected: a string starting with "No node found to start analytics. Reasons [persistent task is awaiting node assignment.]"
     but: was "Started analytics"

and does not reproduce with:

```
./gradlew ':x-pack:plugin:ml:qa:native-multi-node-tests:integTestRunner' --tests "org.elasticsearch.xpack.ml.integration.RunDataFrameAnalyticsIT.testLazyAssignmentWithModelMemoryLimitTooHighForAssignment" -Dtests.seed=AC41692FCCC06627 -Dtests.security.manager=true -Dtests.locale=th -Dtests.timezone=Pacific/Honolulu -Dcompiler.java=12 -Druntime.java=11
```

### PR DESCRIPTION
**Pull request by droberts195**
Audit messages are stored with millisecond timestamps.  If two
messages have the same millisecond timestamp then asserting on
their order is impossible given the information available.

This PR changes the assertion on audit messages in the native
data frame analytics tests to assert that the expected audit
messages exist in any order.

Fixes #48035

### CODE REVIEW

**Review by dimitris-athanasiou — APPROVED** [review]
LGTM

**Review by benwtrent — APPROVED** [review]
Works for me. It might be faster to sort both the prefixes and the resultant audit messages and then iterate over them as before two O(nlg(n)) operations vs a O(n^2) operation. But this is a minor thing.

**Review by przemekwitek — APPROVED** [review]
LGTM

**Comment by droberts195** [comment]
> It might be faster to sort both the prefixes and the resultant audit messages

Both lists are very close to being sorted into time order, so the inner iteration almost always matches the first element it checks - only in the unusual cases indicated by the rare failures of #48035 are the two lists in different orders.  And when reporting failures it's nicer to see the messages in time order rather than alphabetical order.

Part of what I was trying to achieve with the first commit was good diagnostics on failure, as I suspect there will be problems in the future that are found by this method.  For the failure in #48035 I had to guess what happened - the diagnostics from the old version of the method didn't spell it out.  The second commit on this PR uses off-the-shelf matchers to achieve what I did in the first commit but still gives good diagnostics (printing _all_ the messages in time order) if there's a failure.

**Review by dimitris-athanasiou — APPROVED** [review]
LGTM Nice!

**Comment by droberts195** [comment]
Jenkins run elasticsearch-ci/packaging-sample

**Pull request merged**
