### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by grajewsky**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by jrodewig** [comment]
Hi @grajewsky. Would you sign our [CLA](https://www.elastic.co/contributor-agreement), giving us permission to use your commit? A signed CLA is required before we can merge this change.

Please ensure you use the same email address associated with your commit. You can find that email address here:
https://github.com/elastic/elasticsearch/commit/d3edbae6d00a174e4743e52ac2e12a328488770e.patch

Thanks for your contribution!

**Comment by grajewsky** [comment]
@jrodewig Already done. Sorry for the late

**Review by jrodewig — APPROVED** [review]
Thanks @grajewsky!

**Comment by jrodewig** [comment]
@elasticmachine ok to test

**Pull request merged**
