### PR TITLE
Refactor IndexAbstraction to not use IndexMetadata

### PR DESCRIPTION
**Pull request by martijnvg**
Most users of an `IndexAbstraction` instance doesn't need to use the
`IndexMetadata` instances that `getIndices()` and `getWriteIndex()` returns.

Cluster state variables/parameters can be used in places that access to
`IndexMetadata` is required.

By changing the `getIndices()` and `getWriteIndex()` methods to return `Index`
instance, the indices lookup can be reused across different cluster states.
This should be possible in cases that don't change an index hidden status or
 open and closes indices or when adding / removing aliases, data streams or indices.

This change should allow for #79004

### CODE REVIEW

**Review by original-brownbear — COMMENTED** [review]
Thanks @martijnvg this looks really good. I just have a couple of smaller suggestions/questions on performance. Maybe they're irrelevant but I'm paranoid now :)

**Review by original-brownbear — APPROVED** [review]
LGTM, thanks for the iterations @martijnvg !

**Comment by original-brownbear** [comment]
@elasticmachine run elasticsearch-ci/bwc (unrelated failure that reproduces on master also)

**Comment by martijnvg** [comment]
@elasticmachine update branch

**Pull request merged**
