### PR TITLE
Fix wrong totalIterationCount when running BulkIndexBenchmark

### PR DESCRIPTION
**Pull request by gaobinlong**
Relates to #61451.

When running BulkIndexBenchmark in benchmark client, the `totalIterationCount` is not calculated correctly. For example, if `totalDocs` is less than `bulkSize `, `totalIterationCount` should be 1 but not 0.

### CODE REVIEW

**Comment by jakelandis** [comment]
@elasticmachine ok to test

@swallez Can you take a look at this PR ?

@gaobinlong  Sorry the slow response, this one slipped through the cracks.

**Comment by swallez** [comment]
@elasticmachine update branch

**Review by swallez — APPROVED** [review]
LGTM. Thanks for the bugfix!

**Comment by swallez** [comment]
Backported in #68398

**Pull request merged**
