### PR TITLE
Upgrade Tika to 1.23

### PR DESCRIPTION
**Pull request by jkakavas**
Also updates commons-compress to 1.19, pdfbox to 2.0.17, and
poi 4.1.1

### CODE REVIEW

**Comment by dadoonet** [comment]
FYI I found a regression in the way keywords are extracted from PDF documents. I'd avoid upgrading before 1.24 is released.

More context in:

* https://issues.apache.org/jira/projects/TIKA/issues/TIKA-3006
* https://github.com/dadoonet/fscrawler/pull/865

Test that is not passing anymore:

https://github.com/dadoonet/fscrawler/pull/865/commits/bdd1bb658662130f1cddf51044b26f6bcb02c136

**Comment by jkakavas** [comment]
Bummer.. Thanks @dadoonet , I will close this and re-open when tika 1.24 is released

**Comment by dadoonet** [comment]
I should think one day to send most of the integration tests I have for FSCrawler into this plugin so we can more easily detect that type of regression.

**Comment by jkakavas** [comment]
> I should think one day to send most of the integration tests I have for FSCrawler into this plugin so we can more easily detect that type of regression.

There were unit tests failing in this one too so hopefully we could have caught it before merging

**Comment by dadoonet** [comment]
@jkakavas  Tika 1.24 has been released so it's safe to upgrade now.

**Pull request closed without merging**
