### PR TITLE
Wait for cluster to become quiescent between REST tests

### PR DESCRIPTION
**Pull request by abeyad**
[TEST] ensures REST tests wait for cluster state updates to finish
processing before moving to the next test

### CODE REVIEW

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by javanna** [comment]
hey @abeyad could you clarify why this is needed? I guess there were build failures around this? I am particularly interested in whether this should have been there forever or some recent change required this new check between tests. Thanks!

**Comment by abeyad** [comment]
hey @javanna, this was the result of an x-pack test failure (https://github.com/elastic/x-pack-elasticsearch/issues/1093) that had to do with the fact that one of the "wait for active shard" tests had a very short timeout to process a cluster state event (because we expect it to fail).  The problem is, it couldn't even get to the timeout phase because there was a cluster state update that failed to be processed and was potentially interfering with all subsequent tests.  So the idea here is to make sure all cluster state updates have been processed in a test REST test run before moving on to the next test.  Does that help clarify?

**Comment by javanna** [comment]
thanks for explaining @abeyad

**Comment by abeyad** [comment]
thanks for the review @rjernst

**Comment by abeyad** [comment]
5.x commit: bbcb5807332b471402adbb0eedfdc47e530c614a
5.4 commit: 09fe5e3ef9d667fadf92e45c6670677b086382cc
5.3 commit: 035709b42a63cc9e1b3fe9f63618abefdcba15d6

**Pull request merged**
