### PR TITLE
Rivers: Add back deletion of river content on river removal.

### PR DESCRIPTION
**Pull request by rjernst**
In #8877, the deletion of the type associated with a river was
removed. This change adds back the removal using a scan search
along with bulk delete requests.

### CODE REVIEW

**Comment by rjernst** [comment]
@kimchy Is this what you were thinking? Can you suggest how to test? The tests for rivers seem...light.

**Comment by s1monw** [comment]
@rjernst take a look at `IndicesTTLService.PurgerThread#purgeShards` I think we should use the bulk to drive the deletion?

**Comment by dadoonet** [comment]
Ha! I think I now understand why I can see a test failing in couchdb river in master.
As the river is not really removed when we remove `_meta` document, test is failing.

Related code in couchdb-river is https://github.com/elastic/elasticsearch-river-couchdb/blob/master/src/test/java/org/elasticsearch/river/couchdb/CouchdbRiverIntegrationTest.java#L456-457

I guess the test will be fix automagically when this PR will be merged.

**Comment by rjernst** [comment]
Closing since rivers have been removed from master.

**Pull request closed without merging**
