### PR TITLE
Fix plugin script to allow spaces in ES_HOME

### LINKED ISSUE #12504: Space in directory structure fails plugin binary
When one of the parent directories has a space in there the plugin binary can't find the correct path.

```
$ pwd
/home/richard/temp dir/elasticsearch-1.7.0
$ ./bin/plugin
Error: Could not find or load main class dir.elasticsearch-1.7.0.config
```

### PR DESCRIPTION
**Pull request by nik9000**
Fixes ES_HOME with spaces and installing plugins from a local directory
with spaces.

Closes #12504

### CODE REVIEW

**Comment by nik9000** [comment]
This is pretty much a clean forward port of #12544. It was difficult to test because the tests require a 2.0 compatible version of watcher which you have to build from source. And to do that you have to be past of the Elastic organization because that is a closed source plugin. That's certainly going to have to change.

Ping @tlrx, @spinscale, and @electrical who looked at the 1.7 version of this.

**Comment by electrical** [comment]
Looks good to me as far as i can see.

**Comment by tlrx** [comment]
> It was difficult to test because the tests require a 2.0 compatible version of watcher which you have to build from source.

Are you talking about the BATS tests? If so, maybe we should move them apart.

**Comment by jaymode** [comment]
LGTM

**Comment by nik9000** [comment]
> Are you talking about the BATS tests? If so, maybe we should move them apart.

They already have this problem because the plugin installer tries to fetch watch for 1.7 and can't. Since it isn't making anything worse I'll just merge this as is.

I'll create a followup issues to the bats tests not being consistent.

**Pull request merged**
