### PR TITLE
Fix SLMSnapshotBlockingIntegTest

### LINKED ISSUE #47937: SLMSnapshotBlockingIntegTest.testBasicFailureRetention Test Failure
6 test failures in the last couple of days; 4 in the last 24 hours:

https://gradle-enterprise.elastic.co/s/mincoicognogu
https://gradle-enterprise.elastic.co/s/mrohbk4i4iwws
https://gradle-enterprise.elastic.co/s/mco4ecfbd4y2a
https://gradle-enterprise.elastic.co/s/ihc36gbyz3ikg
https://gradle-enterprise.elastic.co/s/koqqsa2ljdbqi
https://gradle-enterprise.elastic.co/s/httug57evnq5e

### PR DESCRIPTION
**Pull request by original-brownbear**
The after snapshot action is interfering with SLM deleting snapshots
here it seems, causing concurrent delete exceptions.
Since these tests are now test-scoped there is no reason to run
snapshot deletes after each test so we can remove them to avoid this issue.

Closes #47937

### CODE REVIEW

**Review by AthenaEryma — APPROVED** [review]
LGTM, thanks Armin!

**Comment by gwbrown** [comment]
Packaging failure looks like a network and/or vagrant blip.

@elasticmachine run elasticsearch-ci/packaging-sample

**Comment by original-brownbear** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample

(vagrant ...)

**Comment by original-brownbear** [comment]
elasticsearch-ci/2

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/2

**Comment by original-brownbear** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample

**Comment by original-brownbear** [comment]
Thanks @gwbrown !

**Pull request merged**
