### PR TITLE
Remove UnsortedNumericDoubleValues

### LINKED ISSUE #24086: Remove UnsortedNumericDoubleValues
This class is a work-around for the fact that multi-valued numerics expect values to be delivered in order. However this attempt to not deliver values in sorted order has the downside of adding a new abstraction that also needs to support computing the min or max values per document. We should remove it and sort values on the fly.

### PR DESCRIPTION
**Pull request by liketic**
Resolves #24086 

@jpountz Thanks for your patient for this fix. There still a test failed because the test expects the `nextValue()` of `NumericDoubleValues ` can be called several times. But the `SortingNumericDoubleValues ` cannot be reused. So I need to fix the test or allow reset the `SortingNumericDoubleValues`'s state? Thanks.

### CODE REVIEW

**Comment by jpountz** [comment]
@liketic what is the failing test? maybe the bug is in the test?

**Comment by liketic** [comment]
@jpountz I found the root cause is `doubleValue()` was called twice after called `advanceExact()`. I already fixed it, could you help to review this. Thanks very much!

**Comment by liketic** [comment]
@jpountz Could you please help review this PR if you're available? 😅

**Comment by jpountz** [comment]
Sorry I had other priorities over the past week. I should have time to give it a look tomorrow if not today.

**Review by jpountz — APPROVED** [review]
Your changes look good, thanks! I'll make them run through CI.

However I think you found a bug: it should be legal to call doubleValue() twice. Have you already looked into what impl had the issue?

**Comment by jpountz** [comment]
@elasticmachine please test it

**Comment by liketic** [comment]
@jpountz From now I only sure `SortingNumericDoubleValues` has this problem, because a `SortingNumericDoubleValues` instance will keep all values in a internal array, and use a `cursor` to  access elements in this array. Which means after the `cursor` exceeds the size of array, a error wil thrown. And if a `NumericDoubleValues` wrapped a `SortingNumericDoubleValues`, then the `doubleValue()` of `NumericDoubleValues` cannot called more then once bacause we have no api to reset the `SortingNumericDoubleValues`'s cursor. 

Seems like the testing is failed, can I rebase it? Thanks for reviewing this PR.

**Comment by jpountz** [comment]
I see. So we should change those wrappers to cache the value when advanceExact is called.

**Comment by liketic** [comment]
@jpountz If you don't mind I can send another PR with that fix.

**Comment by jpountz** [comment]
Please do! :)

**Pull request merged**
