### PR TITLE
Add force merge step to Enrich Policy execution

### PR DESCRIPTION
**Pull request by jbaiera**
This PR adds a step in the policy execution that forcemerge's a new enrich index after reindex completes.

### CODE REVIEW

**Review by martijnvg — APPROVED** [review]
LGTM

**Comment by jbaiera** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by jbaiera** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by martijnvg** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by hub-cap** [comment]
3rd time is a charm?

@elasticmachine run elasticsearch-ci/2

**Review by hub-cap — APPROVED** [review]
:+1:

**Pull request merged**
