### PR TITLE
Removed a few names that could be misleading; the original one I spotted

### PR DESCRIPTION
**Pull request by dweiss**
was this:

[node                     ] [Fatale] started

which I thought was a fatal error or something. The Terror node name would
yield an interesting message too...

### CODE REVIEW

**Comment by dakrone** [comment]
@clintongormley personally I don't think we should remove any (or else we are basically inviting anyone to critique the list of names), but what do you think?

**Comment by dweiss** [comment]
The 'fatale' is confusing, it's not just a personal bias. It actually caused me to check the log looking for errors.

**Comment by clintongormley** [comment]
Yeah, while I understand your reaction @dweiss, I'm not crazy about setting a precedent of editing the nodes list either.  We did remove `Master`, which was seriously confusing, but I'm not sure `Fatale`, `Terror`,  and `Nuke - Frank Simpson` are quite the same level. There are lots of Marvel names that are quite edgy and, with the precedent in place, someone somewhere will insist on those being removed. 

There's an easy solution for this: set your own meaningful node names.

**Comment by dweiss** [comment]
Sure, it's debatable what's appropriate, confusing, etc. But I seriously don't understand the resistance to accept hints (and pull requests) that would modify those entries. I mean: if you don't care about the node names then why prevent people who do care from changing them?

Also, ask @s1monw -- we've edited node names before... there are some hidden gems in there that really best be avoided.

Finally, sure, you can override but I think the default list should make some sense without being potentially confusing.

**Comment by danielmitterdorfer** [comment]
@clintongormley What about this PR given that #19456 is now in master?

**Comment by nik9000** [comment]
> What about this PR given that #19456 is now in master?

Since the names are gone I think this isn't needed.

**Pull request closed without merging**
