### PR TITLE
Remove managing ds by default for now

### PR DESCRIPTION
**Pull request by andreidan**
This removes the DSL functionality that would automatically
configure the `lifecycle` to all new data streams in preparation
for marking Data stream lifecycle as ready for Technical Preview.

A PR marking the feature as Tech Preview in the docs and creating the
needed changelog will follow.

### CODE REVIEW

**Comment by masseyke** [comment]
Looks pretty straightforward, but do we need to remove the use of the default lifecycle from TransportSimulateIndexTemplateAction? I'm not very familiar with that code.

**Comment by andreidan** [comment]
@masseyke good catch, I removed `DataStreamLifecycle.DEFAULT` completely.

**Comment by andreidan** [comment]
@elasticmachine update branch

**Review by masseyke — APPROVED** [review]
LGTM (if CI is happy)

**Pull request merged**
