### PR TITLE
Add option to avoid BootstrapCheck

### PR DESCRIPTION
**Pull request by YaSuenag**
I've created [HSLoader](https://github.com/YaSuenag/hsloader) . This tool uses transport protocol to push [HeapStats](https://github.com/HeapStats/heapstats) data to Elasticsearch.

I develop this tool on Windows, and I run Elasticsearch on Linux on Client Hyper-V. So I need to open the port for transport protocol on Elasticserach.
However, Elasticsearch (I configured ```network.host``` to ```0.0.0.0``` ) could not startup because BootstrapCheck was failed.

I read [the document for Bootstrap Checks](https://www.elastic.co/guide/en/elasticsearch/reference/master/bootstrap-checks.html) and I understand it. However, for more ease of development, I want to add the facility to avoid this check.
So I added system property ```skipBootstrapCheck``` .  I'm sure this option helps many tool developers who use virtual machine for development.

Would you merge this PR?

### CODE REVIEW

**Comment by jasontedor** [comment]
Thank you for @YaSuenag for using Elasticsearch and opening this PR, but I'm sorry to tell you that we will not merge it. You can read more about our reasoning on our [blog post](https://www.elastic.co/blog/bootstrap_checks_annoying_instead_of_devastating) about the checks and why it's a hard check, and why we are opposed to adding a flag to avoid the bootstrap checks when a node is able to be part of a cluster.

> This tool uses transport protocol to push [HeapStats](https://github.com/HeapStats/heapstats) data to Elasticsearch.

I'm curious why you don't use HTTP?

**Comment by YaSuenag** [comment]
@jasontedor Hmm... okay I see. IMHO bootstrap check is too bad to complex development environment!

> I'm curious why you don't use HTTP?

[HeapStats](https://github.com/HeapStats/heapstats) dumps binary data and provides parser API for Java. I need to use it with Java.
I found [Java Client API](https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/client.html) at first, and it seems to match for me. So I use it.

**Comment by jasontedor** [comment]
> Hmm... okay I see. IMHO bootstrap check is too bad to complex development environment!

A complex development environment is a problem in and of itself. :smile:

In all seriousness, we run integration tests against standalone instances of Elasticsearch that listen on localhost (and thus do not trigger the bootstrap checks); is there a reason that you can not do the same for your development environment?

**Comment by YaSuenag** [comment]
> is there a reason that you can not do the same for your development environment?

I have Windows 10 laptop for development. I have Linux VM on Hyper-V. I usually run ES on Linux in production system, so I use this VM for debugging.
OTOH, I can run IDE on Windows only. So I need to connect HostOS (Windows) to Linux VM (Hyper-V guest).

**Comment by jasontedor** [comment]
> I have Windows 10 laptop for development. I have Linux VM on Hyper-V. I usually run ES on Linux in production system, so I use this VM for debugging.

Elasticsearch runs on Windows.

**Pull request closed without merging**
