### PR TITLE
ILM/SLM history policies forcemerge in hot and dsl configuration.

### PR DESCRIPTION
**Pull request by andreidan**
This configures the ILM and SLM data streams to forcemerge
in the hot tier, to avoid a large number of segments. 

This also bumps the version of the managed index templates and configures
 `lifecycle` as the management system - this would have the effect of 
having new data streams due to the version bump that are managed by 
data stream lifecycle (i.e. `ilm-history-6` and `slm-history-6` will be
created on the next Elasticsearch version)

### CODE REVIEW

**Comment by dakrone** [comment]
I think we also want to bump the registry version in both `ILMHistoryTemplateRegistry` and `SnapshotLifecycleTemplateRegistry` so that these new policies get installed, right? Or is there a reason we don't want to apply this on upgrade?

**Comment by andreidan** [comment]
@elasticmachine update branch

**Comment by andreidan** [comment]
> Unfortunately I think removing any ILM policy that is pre-installed would be a breaking change, so we'll still want to install it for a long while.

@dakrone hm, this is a bit surprising to me. Can you elaborate a bit on why you think this is a breaking change? Note that the existing data streams would continue to be managed "as they are" (with the shipped `ilm-history` ILM policy or with a custom one if it was manually changed) - the change in behaviour is that Elasticsearch would stop trying to re-install it on every cluster state change event if it's missing from the system - I'd argue it's the equivalent change of https://github.com/elastic/elasticsearch/pull/99975/files#diff-703bbc949a11c72b7a95f18065b29c367afca456ae829b0403987070089b5f34

**Comment by dakrone** [comment]
> Can you elaborate a bit on why you think this is a breaking change?

Any policy we install *could* be used by a user by referring to it by id, so not installing it (or changing the id) would be breaking because they could upgrade (or create a new cluster) no longer have the policy installed. It's an edge case, but still one that is breaking.

**Comment by andreidan** [comment]
> Any policy we install could be used by a user by referring to it by id, so not installing it (or changing the id) would be breaking because they could upgrade (or create a new cluster) no longer have the policy installed.

@dakrone  Thanks for your thoughts. Just to make sure we're on the same page here: 

A bit of context on upgrades: upgrading would **not** remove _the existing_ policy in the system. Going from, say 8.12 to 8.13, the `ilm-history-ilm-policy` would still exist in 8.13 until the user manually deletes it. 

The breaking change here would be if a user depends on the ILM policy _being re-installed after manual deletion_ .

On a new 8.13 cluster, indeed the `ilm-history-ilm-policy` would not exist anymore but in this case there would be no scenario where a user can reference this ILM policy, except by logic being derived at the application level based on the perpetual existence of these resources.  
(I believe in CCR the data streams need to be bootstrapped independently on both clusters so I don't think we'd have a concern here)

IMO both the above scenarios are extending what we would consider a breaking change but happy to stay on the safe side and keep them. 

I've re-added the ILM policies, although not referenced from the index templates anymore - however, I'm wondering if we should continue to reference them from the index templates too since we're keeping them? 
If we do NOT reference them from the index template, this will mean that the existing `ilm-history-5` data streams would be backed by an index template that doesn't configure ILM anymore (this would not be a problem under normal feature behaviour as the `ilm-history-6` data stream will be created, managed, and taking over the storage of history entries). However, a manual `rollover` of the `ilm-history-5` data stream would yield a data stream with an unmanaged write index. 

Should we reference the ILM policy from the index template, together with `prefer_ilm: false` to cover this scenario too?

**Comment by dakrone** [comment]
> IMO both the above scenarios are extending what we would consider a breaking change but happy to stay on the safe side and keep the ILM policies.

I think this is the safest option. The scenario I have in mind is this:

A user spins up 8.12.0, they play around, and create their own template and data stream. They want to try ILM and pick an ILM policy that they see there's already one they can use `ilm-history-ilm-policy` (pretend the user doesn't know any better about why they may not want to use this one). So they set their template to use `ilm-history-ilm-policy` and then store that configuration somewhere, because they're a good user and want to have a repeatable system.

The user then takes their stored settings, and applies them to a new 8.13.0 cluster because they want to try out the new version, however, the `ilm-history-ilm-policy` ILM policy doesn't exist, because we stopped installing it. Uh-oh, this is breaking because we broke the assumption that a user had about what a consistent installation includes.

On the safe side, I think we should keep it for 8.x, mark it deprecated, and remove it once that deprecation period is up.

**Review by dakrone — APPROVED** [review]
LGTM (we can handle the ILM policy stuff separately also), thanks Andrei

**Pull request merged**
