### PR TITLE
[DOCS] Remove major release references from migration guide

### PR DESCRIPTION
**Pull request by jrodewig**
Updates the language in our migration guides to remove references to major releases.

### Previews
* Migration guide: https://elasticsearch_83555.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/breaking-changes.html
* 8.0 migration guide: https://elasticsearch_83555.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/migrating-8.0.html
* 8.1 migration guide: https://elasticsearch_83555.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/migrating-8.1.html

### CODE REVIEW

**Comment by jrodewig** [comment]
@pugnascotia I'm not exactly sure what's causing elasticsearch-ci/example-plugins to fail, but I remember you hit something similar in https://github.com/elastic/elasticsearch/pull/83341. Any pointers for fixing the test?

**Comment by pugnascotia** [comment]
@jrodewig there's a missing Java client dependency that's causing the example plugins failure. Don't worry about it for now.

**Review by pugnascotia — APPROVED** [review]

**Review by lockewritesdocs — APPROVED** [review]
LGTM 👍 -- thanks @jrodewig!

**Comment by jrodewig** [comment]
@elasticmachine update branch

**Pull request merged**
