### PR TITLE
Corrected typo in node.asciidoc

### PR DESCRIPTION
**Pull request by nicomak**
Corrected typo in documentation

### CODE REVIEW

**Comment by dakrone** [comment]
Hi, thanks for the submission!

Could I ask you to sign the [CLA](https://www.elastic.co/contributor-agreement/) so we can merge this in?

**Comment by nicomak** [comment]
Hi, I had already signed it before your message, and now I've signed it another 2 times. But the check is still failing. Don't understand how this is supposed to work ...

**Comment by nicomak** [comment]
Yes it's the same e-mail address ..

**Comment by clintongormley** [comment]
I think that's because your email is hidden on github - the CLA checker can't access it to check

**Comment by nicomak** [comment]
I tried twice again after making my e-mail visible, still doesnt work.
I'm tired of this, you guys can just copy my change and commit it yourselves, it's just a small typo fix.

**Comment by clintongormley** [comment]
Hi @nicomak 

I see the problem - the git commit is noreply@github, but i see your signature with your current email.  I'll merge this in.  Sorry for the runaround

**Pull request merged**
