### PR TITLE
Remove Log4j 1 jar hell exemption

### PR DESCRIPTION
**Pull request by jasontedor**
When Elasticsearch depended on Log4j 1, there was jar hell from the
log4j and the apache-log4j-extras jar. As these dependencies are gone,
the jar hell exemption for Log4j 1 can be removed.

Relates #20235

### CODE REVIEW

**Comment by jasontedor** [comment]
retest this please

**Comment by nik9000** [comment]
LGTM

**Comment by jasontedor** [comment]
retest this please

**Comment by jasontedor** [comment]
Thanks @nik9000.

**Pull request merged**
