### PR TITLE
Convert 'routing' values in REST API tests to strings

### PR DESCRIPTION
**Pull request by sethmlarson**
The Elasticsearch specification is failing multiple REST API tests due to usage of integers instead of strings for `routing` values.

The API accepts integers for these fields either due to being encoded in the query string over the transport thus being encoded as a string or the XContent parser being lenient for some string values and converting whatever is passed to a string before use.

Since the Elasticsearch specification uses the REST API tests as one of the sources of truth we'd like the types to match up with the documentation as is done here.

This PR was created with the following command:
`$ find . -type f -name "*.yml" -print0 | xargs -0 sed -i -r 's/routing:\s*([0-9]+)/routing: "\1"/g'`

### CODE REVIEW

**Comment by sethmlarson** [comment]
The only failing `rest-compatibility` test (`ml/preview_datafeed/Test preview datafeed where time field is data_nanos`) appears to be unrelated.

**Comment by pgomulka** [comment]
@sethmlarson I agree that it should be string as everything on the url path. But shouldn't this also apply for `id` in those tests? 
Could you point me to those failing API Specs? Do you see this in CI?

**Comment by sethmlarson** [comment]
@pgomulka We also agree that `id` should be string we could handle that here or separately if you'd like.

The failures are on a private repository, I'll ping you on Slack.

**Comment by pgomulka** [comment]
@elasticmachine update branch

**Review by pgomulka — APPROVED** [review]
LGTM, I still wonder if we should follow up with `id` changes
but if the specification tests are passing then I guess we don't have to do it now

**Comment by delvedor** [comment]
@pgomulka updating the `id` as well would be great! The specification tests are passing because we are manually casting to string every `id` before running the actual test.

**Comment by sethmlarson** [comment]
@pgomulka I'll open another PR for `id` since this one is passing now.

**Pull request merged**
