### PR TITLE
Remove types from client-benchmark-noop-api-plugin URLs

### PR DESCRIPTION
**Pull request by romseygeek**
Part of https://github.com/elastic/elasticsearch/issues/41059

### CODE REVIEW

**Review by danielmitterdorfer — APPROVED** [review]
Thanks! LGTM

**Comment by romseygeek** [comment]
@elasticmachine test this please

**Comment by romseygeek** [comment]
@elasticmachine upgrade branch

**Comment by romseygeek** [comment]
@elasticmachine update branch

**Pull request merged**
