### PR TITLE
mistyping in one of the highlighting examples comment -> content

### PR DESCRIPTION
**Pull request by akramarev**

### CODE REVIEW

**Comment by dnhatn** [comment]
@akramarev Could you please sign our CLA?

**Comment by akramarev** [comment]
@dnhatn I did sign it.. twice, not sure why it's not propagated here.

image

**Comment by dnhatn** [comment]
@elasticmachine please test this.

**Review by mayya-sharipova — APPROVED** [review]

**Comment by mayya-sharipova** [comment]
@akramarev Thanks for your contribution. Branches 6.x and 7.x will also benefit from this fix.

**Pull request merged**
