### PR TITLE
Remove (deprecated) support for '+' in index expressions

### PR DESCRIPTION
**Pull request by javanna**
Relates to #24515

### CODE REVIEW

**Review by dakrone — APPROVED** [review]
this LGTM, thanks @javanna!

**Comment by javanna** [comment]
retest this please

**Comment by olcbean** [comment]
Hey @javanna, looks like this change is addressing #5341 as well. Or is there another usecase in which '+' should be supported in the path?

**Comment by javanna** [comment]
hi @olcbean '+' is still a valid character in index and alias names, just not in their first character. So I'm afraid #5341 is still a valid issue.

**Pull request merged**
