### PR TITLE
Improve error message if a setting is not found

### PR DESCRIPTION
**Pull request by s1monw**
Today we only emit that the setting wasn't found unless we have
some DYM suggestions. Yet, if a setting is not found at all and there
are no suggestions due to typos it's likely a removed setting or the plugin
that is supposed to be configured is not installed.
This commit adds some info text to the exception to help the user debugging
the problem before opening bug-reports.

Instead of emitting:

`unknown setting [foo.bar]`

we now emit:

`unknown setting [foo.bar] please check the migration guide for removed settings and ensure that the plugin you are configuring is installed`

Relates to #18663

@clintongormley can you take a look

### CODE REVIEW

**Comment by litong01** [comment]
Is it all possible to indicate where the migration guide might be? I understand that the change wants to be helpful when there is a problem, but this change feels like the error message "Contact your administrator". If have a link to the migration guide is not possible, then this change at least provides some hints, so still a good effort, just my 2 cents. Thanks.

**Comment by s1monw** [comment]
> Is it all possible to indicate where the migration guide might be? I understand that the change wants to be helpful when there is a problem, but this change feels like the error message "Contact your administrator". If have a link to the migration guide is not possible, then this change at least provides some hints, so still a good effort, just my 2 cents. Thanks.

I try to not have version dependent links in the code. I think that will only lead to stale links?

**Comment by clintongormley** [comment]
I agree with not having the doc links, but we don't really have something called the migration guide. perhaps:

    please check that any required plugins are installed, or check the breaking changes documentation for removed settings

**Comment by litong01** [comment]
@clintongormley good suggestion. Can we even improve the message a bit more? I think in many cases probably it is just a misspell.

"please check that any required plugins are installed, removed settings are not used and settings are correctly spelled"

**Comment by s1monw** [comment]
> @clintongormley good suggestion. Can we even improve the message a bit more? I think in many cases probably it is just a misspell.


@litong01 if its a spelling you get a did you mean message with the right setting instead of this message

**Comment by litong01** [comment]
@s1monw thanks for your response, I just think in many cases, the misspell of a setting is to blame. Not really sure you can guess what the right setting is though.

**Comment by s1monw** [comment]
> @s1monw thanks for your response, I just think in many cases, the misspell of a setting is to blame. Not really sure you can guess what the right setting is though.

we can! try it out it's pretty good though. We use the same technology as used for the spellchecker.

**Comment by s1monw** [comment]
@clintongormley I updated the msg...

**Comment by jpountz** [comment]
LGTM

**Pull request merged**
