### PR TITLE
Incorrect Parameter value in watcher.stats tests

### PR DESCRIPTION
**Pull request by philkra**
In the integration tests for the `watcher.stats` endpoint, the parameter `metric` is set to `all` which is an incorrect value according to the [docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/watcher-api-stats.html#watcher-api-stats-path-params), as it should be `_all`.

### CODE REVIEW

**Review by danhermann — CHANGES_REQUESTED** [review]
There are several problems beyond the specification of `all` rather than `_all` in this test case. One is that the endpoint tolerates invalid values and another is that this test specifies a value for the `metric` parameter even though it is irrelevant to the test. While all those problems don't need to be resolved in this PR, I would prefer that the `metric` parameter be removed completely since it isn't necessary for this test.

**Comment by philkra** [comment]
@danhermann , I agree that it's likely best to remove the `metric` param in this case (removed with https://github.com/elastic/elasticsearch/pull/73006/commits/d1f3143536c3b942e5e586d22a896e0305e053b7) and address the acceptance of invalid values separately.

**Comment by danhermann** [comment]
Thanks, @philkra. LGTM. I've asked for some input from the people working on REST compatibility because I don't see a reason why the one test in that suite failed.

**Comment by joegallo** [comment]
I merged in master since there was a conflict here due to my recently merged PR (#72823).

**Review by joegallo — APPROVED** [review]

**Pull request merged**
