### PR TITLE
suggest_mode is per shard

### PR DESCRIPTION
**Pull request by nik9000**

### CODE REVIEW

**Comment by nik9000** [comment]
Sorry for the whitespace changes. My editor eats trailing whitespace and I hate trailing whitespace enough to not work to stop it. You can open up the changes with `?w=true` on the url and only get the actual, real edits.

**Comment by nik9000** [comment]
Ping @clintongormley and @s1monw to make sure this all makes sense.

**Comment by s1monw** [comment]
LGTM - thanks nik

**Comment by nik9000** [comment]
Merged to master and pushed to the 2.x, 2.2, and 2.1 branches.

**Pull request merged**
