### PR TITLE
Add known issue for 6.4

### PR DESCRIPTION
**Pull request by jkakavas**
Regarding the inability to use PEM keys exported from PKCS#12
containers as discussed in #33168

### CODE REVIEW

**Review by lcawl — APPROVED** [review]
LGTM

**Comment by lcawl** [comment]
If additional information is available, we can go into greater detail in the "Troubleshooting security" section here: https://www.elastic.co/guide/en/elastic-stack-overview/current/security-troubleshooting.html

**Review by jaymode — APPROVED** [review]
LGTM. I think with a fix going into 6.4.1 we don't really need troubleshooting docs

**Comment by jkakavas** [comment]
jenkins test this please

**Pull request merged**
