### PR TITLE
Lower zstd blockDocCount for best_speed from 128 to 96

### PR DESCRIPTION
**Pull request by martijnvg**
Query latencies are more important for best speed use cases. Zstd stored fields have shown some increase in query latencies when limited number of stored field data is fetched (in case of get by id like queries). By decreasing the blockDocCount we try to reduce these latencies at the cost of using a little bit more storage. 

Based on the shared results below, setting blockDocCount to 96.

Note that zstd is still behind a feature flag and this is the last things we like to tune before removing the feature flag. In all other cases zstd has shown to be the better trade of compared to lz4 and deflate (which get used depending on `index.codec` setting).

After merging this change, we should monitor the nightly benchmarks and see the total effect before removing the feature flag.

### CODE REVIEW

**Comment by martijnvg** [comment]
Running the elastic/logs track query latencies look like this compared to lz4 (the compression library used with released versions of Elasticsearch):

```
|                                                    Store size |                                        |   113.604       |   112.502       |     -1.10276 |     GB |   -0.97% |
|                                       50th percentile latency |                             bulk-index |  1750.72        |   311.226       |  -1439.49    |     ms |  -82.22% |
|                                       90th percentile latency |                             bulk-index |  2965.47        |   653.104       |  -2312.37    |     ms |  -77.98% |
|                                       99th percentile latency |                             bulk-index |  4276.98        |   932.948       |  -3344.03    |     ms |  -78.19% |
|                                     99.9th percentile latency |                             bulk-index |  6010.93        |  1898.95        |  -4111.98    |     ms |  -68.41% |
|                                    99.99th percentile latency |                             bulk-index |  7844.7         |  3179.62        |  -4665.09    |     ms |  -59.47% |
|                                      100th percentile latency |                             bulk-index |  9718.48        |  5156.6         |  -4561.88    |     ms |  -46.94% |
|                                       50th percentile latency |      discovery-search-request-size-100 |  1458.15        |  3038.62        |   1580.47    |     ms | +108.39% |
|                                       90th percentile latency |      discovery-search-request-size-100 |  1516.48        |  3085.49        |   1569       |     ms | +103.46% |
|                                      100th percentile latency |      discovery-search-request-size-100 |  1869.3         |  3462.72        |   1593.42    |     ms |  +85.24% |
|                                       50th percentile latency |      discovery-search-request-size-500 |  1562.66        |  1556.28        |     -6.37738 |     ms |   -0.41% |
|                                       90th percentile latency |      discovery-search-request-size-500 |  1634.72        |  1578.41        |    -56.3097  |     ms |   -3.44% |
|                                      100th percentile latency |      discovery-search-request-size-500 |  1890.45        |  1632.44        |   -258.004   |     ms |  -13.65% |
|                                       50th percentile latency |     discovery-search-request-size-1000 |  1693.52        |  1687.59        |     -5.92932 |     ms |   -0.35% |
|                                       90th percentile latency |     discovery-search-request-size-1000 |  1717.31        |  1705.97        |    -11.3401  |     ms |   -0.66% |
|                                      100th percentile latency |     discovery-search-request-size-1000 |  1853.05        |  1777.65        |    -75.3966  |     ms |   -4.07% |
|                                       50th percentile latency |                        discover/search |   760.797       |   951.122       |    190.325   |     ms |  +25.02% |
|                                       90th percentile latency |                        discover/search |  2042.18        |  2569.2         |    527.015   |     ms |  +25.81% |
|                                      100th percentile latency |                        discover/search |  2428.58        |  2998.33        |    569.745   |     ms |  +23.46% |
|                                       50th percentile latency |                     discover/visualize |   576.205       |   573.46        |     -2.74411 |     ms |   -0.48% |
|                                       90th percentile latency |                     discover/visualize |  9670.48        | 10441.6         |    771.135   |     ms |   +7.97% |
|                                      100th percentile latency |                     discover/visualize | 12262.2         | 12889.2         |    627.064   |     ms |   +5.11% |
|                                       50th percentile latency |                                  kafka |   438.432       |   438.117       |     -0.31558 |     ms |   -0.07% |
|                                       90th percentile latency |                                  kafka |   779.353       |   776.968       |     -2.3849  |     ms |   -0.31% |
|                                      100th percentile latency |                                  kafka |  1085.6         |  1070.76        |    -14.8436  |     ms |   -1.37% |
|                                       50th percentile latency |                                  nginx |  1726.62        |  1726.56        |     -0.06073 |     ms |   -0.00% |
|                                       90th percentile latency |                                  nginx |  4389.83        |  4455.59        |     65.7571  |     ms |   +1.50% |
|                                      100th percentile latency |                                  nginx | 10210.4         |  9747.18        |   -463.255   |     ms |   -4.54% |
|                                       50th percentile latency |                                 apache |   363.002       |   375.141       |     12.1395  |     ms |   +3.34% |
|                                       90th percentile latency |                                 apache |   978.327       |   942.576       |    -35.7509  |     ms |   -3.65% |
|                                      100th percentile latency |                                 apache |  1970.13        |  1949.45        |    -20.6814  |     ms |   -1.05% |
|                                       50th percentile latency |                            system/auth |   325.808       |   325.109       |     -0.69925 |     ms |   -0.21% |
|                                       90th percentile latency |                            system/auth |   426.179       |   656.018       |    229.839   |     ms |  +53.93% |
|                                       99th percentile latency |                            system/auth |  4752           |  5106.42        |    354.418   |     ms |   +7.46% |
|                                      100th percentile latency |                            system/auth |  4891.44        |  5440.98        |    549.542   |     ms |  +11.23% |
|                                       50th percentile latency |                system/syslog/dashboard |   393.13        |   397.157       |      4.02692 |     ms |   +1.02% |
|                                       90th percentile latency |                system/syslog/dashboard |  1360.45        |  1288.98        |    -71.4656  |     ms |   -5.25% |
|                                      100th percentile latency |                system/syslog/dashboard |  3892.67        |  3469.68        |   -422.989   |     ms |  -10.87% |
|                                       50th percentile latency |                     system/syslog/lens |   853.748       |   853.039       |     -0.70886 |     ms |   -0.08% |
|                                       90th percentile latency |                     system/syslog/lens |  2075.03        |  2078.97        |      3.94116 |     ms |   +0.19% |
|                                      100th percentile latency |                     system/syslog/lens |  4155.92        |  3696.73        |   -459.188   |     ms |  -11.05% |
|                                       50th percentile latency |                        mysql/dashboard |   317.356       |   318.227       |      0.87108 |     ms |   +0.27% |
|                                       90th percentile latency |                        mysql/dashboard |   801.353       |   827.013       |     25.6598  |     ms |   +3.20% |
|                                      100th percentile latency |                        mysql/dashboard |  1550.73        |  1597.31        |     46.5758  |     ms |   +3.00% |
|                                       50th percentile latency |                                  redis |   621.144       |   641.677       |     20.5335  |     ms |   +3.31% |
|                                       90th percentile latency |                                  redis |  2244.7         |  1953.38        |   -291.322   |     ms |  -12.98% |
|                                      100th percentile latency |                                  redis |  3057.48        |  2776.39        |   -281.092   |     ms |   -9.19% |
|                                       50th percentile latency |                             mysql/lens |  1003.95        |  1004.04        |      0.08768 |     ms |    0.01% |
|                                       90th percentile latency |                             mysql/lens |  2460.98        |  2398.28        |    -62.6962  |     ms |   -2.55% |
|                                      100th percentile latency |                             mysql/lens |  3186.96        |  2892.75        |   -294.212   |     ms |   -9.23% |
|                                       50th percentile latency |                    postgresql/overview |  1023.16        |  1022.79        |     -0.37115 |     ms |   -0.04% |
|                                       90th percentile latency |                    postgresql/overview |  1114.29        |  1110.09        |     -4.20618 |     ms |   -0.38% |
|                                       99th percentile latency |                    postgresql/overview |  1675.19        |  1674.62        |     -0.57046 |     ms |   -0.03% |
|                                      100th percentile latency |                    postgresql/overview |  1675.82        |  1676.43        |      0.60669 |     ms |   +0.04% |
|                                       50th percentile latency |                    postgresql/duration |   320.598       |   321.209       |      0.61102 |     ms |   +0.19% |
|                                       90th percentile latency |                    postgresql/duration |   639.049       |   648.275       |      9.22614 |     ms |   +1.44% |
|                                      100th percentile latency |                    postgresql/duration |  4171.85        |  4022.45        |   -149.406   |     ms |   -3.58% |
```

**Comment by martijnvg** [comment]
Running the elastic/logs track query latencies with index.codec set to default, with 8.15.0 as baseline and 8.16.0-SNAPSHOT with blockDocCount set to 96 as contender:

```
|                                                    Store size |                                        |   113.604       |   112.827       |      -0.7772  |     GB |   -0.68% |
|                                       50th percentile latency |                             bulk-index |  1750.72        |   311.153       |   -1439.56    |     ms |  -82.23% |
|                                       90th percentile latency |                             bulk-index |  2965.47        |   663.097       |   -2302.38    |     ms |  -77.64% |
|                                       99th percentile latency |                             bulk-index |  4276.98        |   950.986       |   -3325.99    |     ms |  -77.76% |
|                                     99.9th percentile latency |                             bulk-index |  6010.93        |  1983.73        |   -4027.2     |     ms |  -67.00% |
|                                    99.99th percentile latency |                             bulk-index |  7844.7         |  3412.41        |   -4432.29    |     ms |  -56.50% |
|                                      100th percentile latency |                             bulk-index |  9718.48        |  5171.33        |   -4547.15    |     ms |  -46.79% |
|                                       50th percentile latency |      discovery-search-request-size-100 |  1458.15        |  1528.78        |      70.6295  |     ms |   +4.84% |
|                                       90th percentile latency |      discovery-search-request-size-100 |  1516.48        |  1611.26        |      94.7769  |     ms |   +6.25% |
|                                      100th percentile latency |      discovery-search-request-size-100 |  1869.3         |  1876.97        |       7.67139 |     ms |   +0.41% |
|                                       50th percentile latency |      discovery-search-request-size-500 |  1562.66        |  1637.23        |      74.5695  |     ms |   +4.77% |
|                                       90th percentile latency |      discovery-search-request-size-500 |  1634.72        |  1669.79        |      35.0713  |     ms |   +2.15% |
|                                      100th percentile latency |      discovery-search-request-size-500 |  1890.45        |  1883.5         |      -6.94641 |     ms |   -0.37% |
|                                       50th percentile latency |     discovery-search-request-size-1000 |  1693.52        |  1722.16        |      28.6375  |     ms |   +1.69% |
|                                       90th percentile latency |     discovery-search-request-size-1000 |  1717.31        |  1775.45        |      58.1456  |     ms |   +3.39% |
|                                      100th percentile latency |     discovery-search-request-size-1000 |  1853.05        |  1872.31        |      19.265   |     ms |   +1.04% |
|                                       50th percentile latency |                        discover/search |   760.797       |   853.444       |      92.6468  |     ms |  +12.18% |
|                                       90th percentile latency |                        discover/search |  2042.18        |  2122.39        |      80.2061  |     ms |   +3.93% |
|                                      100th percentile latency |                        discover/search |  2428.58        |  2596.35        |     167.771   |     ms |   +6.91% |
|                                       50th percentile latency |                     discover/visualize |   576.205       |   578.13        |       1.92581 |     ms |   +0.33% |
|                                       90th percentile latency |                     discover/visualize |  9670.48        | 10102.8         |     432.355   |     ms |   +4.47% |
|                                      100th percentile latency |                     discover/visualize | 12262.2         | 12685.2         |     423.054   |     ms |   +3.45% |
|                                       50th percentile latency |                                  kafka |   438.432       |   438.783       |       0.35112 |     ms |   +0.08% |
|                                       90th percentile latency |                                  kafka |   779.353       |   784.081       |       4.72791 |     ms |   +0.61% |
|                                      100th percentile latency |                                  kafka |  1085.6         |  1082.97        |      -2.63171 |     ms |   -0.24% |
|                                       50th percentile latency |                                  nginx |  1726.62        |  1726.72        |       0.09998 |     ms |    0.01% |
|                                       90th percentile latency |                                  nginx |  4389.83        |  4207.92        |    -181.911   |     ms |   -4.14% |
|                                      100th percentile latency |                                  nginx | 10210.4         |  9931.94        |    -278.498   |     ms |   -2.73% |
|                                       50th percentile latency |                                 apache |   363.002       |   375.098       |      12.0963  |     ms |   +3.33% |
|                                       90th percentile latency |                                 apache |   978.327       |   925.498       |     -52.8288  |     ms |   -5.40% |
|                                      100th percentile latency |                                 apache |  1970.13        |  1962.91        |      -7.21631 |     ms |   -0.37% |
|                                       50th percentile latency |                            system/auth |   325.808       |   326.071       |       0.26346 |     ms |   +0.08% |
|                                       90th percentile latency |                            system/auth |   426.179       |   413.367       |     -12.8124  |     ms |   -3.01% |
|                                       99th percentile latency |                            system/auth |  4752           |  4498.64        |    -253.364   |     ms |   -5.33% |
|                                      100th percentile latency |                            system/auth |  4891.44        |  4941.63        |      50.1865  |     ms |   +1.03% |
|                                       50th percentile latency |                system/syslog/dashboard |   393.13        |   398.04        |       4.90939 |     ms |   +1.25% |
|                                       90th percentile latency |                system/syslog/dashboard |  1360.45        |  1242.51        |    -117.94    |     ms |   -8.67% |
|                                      100th percentile latency |                system/syslog/dashboard |  3892.67        |  3332.79        |    -559.882   |     ms |  -14.38% |
|                                       50th percentile latency |                     system/syslog/lens |   853.748       |   853.623       |      -0.12582 |     ms |   -0.01% |
|                                       90th percentile latency |                     system/syslog/lens |  2075.03        |  1993.69        |     -81.3424  |     ms |   -3.92% |
|                                      100th percentile latency |                     system/syslog/lens |  4155.92        |  3642.19        |    -513.733   |     ms |  -12.36% |
|                                       50th percentile latency |                        mysql/dashboard |   317.356       |   318.044       |       0.68797 |     ms |   +0.22% |
|                                       90th percentile latency |                        mysql/dashboard |   801.353       |   792.353       |      -9.00096 |     ms |   -1.12% |
|                                      100th percentile latency |                        mysql/dashboard |  1550.73        |  1622.64        |      71.91    |     ms |   +4.64% |
|                                       50th percentile latency |                                  redis |   621.144       |   648.674       |      27.5309  |     ms |   +4.43% |
|                                       90th percentile latency |                                  redis |  2244.7         |  1780.33        |    -464.374   |     ms |  -20.69% |
|                                      100th percentile latency |                                  redis |  3057.48        |  2879.81        |    -177.674   |     ms |   -5.81% |
|                                       50th percentile latency |                             mysql/lens |  1003.95        |  1004.35        |       0.3992  |     ms |   +0.04% |
|                                       90th percentile latency |                             mysql/lens |  2460.98        |  2327.43        |    -133.551   |     ms |   -5.43% |
|                                      100th percentile latency |                             mysql/lens |  3186.96        |  2818.12        |    -368.834   |     ms |  -11.57% |
|                                       50th percentile latency |                    postgresql/overview |  1023.16        |  1023.56        |       0.39728 |     ms |   +0.04% |
|                                       90th percentile latency |                    postgresql/overview |  1114.29        |  1115.39        |       1.09889 |     ms |   +0.10% |
|                                       99th percentile latency |                    postgresql/overview |  1675.19        |  1676.1         |       0.9188  |     ms |   +0.05% |
|                                      100th percentile latency |                    postgresql/overview |  1675.82        |  1676.86        |       1.04187 |     ms |   +0.06% |
|                                       50th percentile latency |                    postgresql/duration |   320.598       |   319.708       |      -0.88968 |     ms |   -0.28% |
|                                       90th percentile latency |                    postgresql/duration |   639.049       |   649.694       |      10.6451  |     ms |   +1.67% |
|                                      100th percentile latency |                    postgresql/duration |  4171.85        |  4067.99        |    -103.86    |     ms |   -2.49% |
```

**Comment by martijnvg** [comment]
Running the elastic/logs track query latencies with index.codec set to default, with 8.15.0 as baseline and 8.16.0-SNAPSHOT with blockDocCount set to 64 as contender:

```
|                                                    Store size |                                        |   113.604       |   113.058       |     -0.54661     |     GB |   -0.48% |
|                                       50th percentile latency |                             bulk-index |  1750.72        |   311.573       |  -1439.14        |     ms |  -82.20% |
|                                       90th percentile latency |                             bulk-index |  2965.47        |   656.171       |  -2309.3         |     ms |  -77.87% |
|                                       99th percentile latency |                             bulk-index |  4276.98        |   934.025       |  -3342.95        |     ms |  -78.16% |
|                                     99.9th percentile latency |                             bulk-index |  6010.93        |  1932.93        |  -4078           |     ms |  -67.84% |
|                                    99.99th percentile latency |                             bulk-index |  7844.7         |  3240.48        |  -4604.22        |     ms |  -58.69% |
|                                      100th percentile latency |                             bulk-index |  9718.48        |  5510.77        |  -4207.71        |     ms |  -43.30% |
|                                       50th percentile latency |      discovery-search-request-size-100 |  1458.15        |  2934.4         |   1476.25        |     ms | +101.24% |
|                                       90th percentile latency |      discovery-search-request-size-100 |  1516.48        |  3155.96        |   1639.47        |     ms | +108.11% |
|                                      100th percentile latency |      discovery-search-request-size-100 |  1869.3         |  3755.56        |   1886.26        |     ms | +100.91% |
|                                       50th percentile latency |      discovery-search-request-size-500 |  1562.66        |  1542.67        |    -19.9835      |     ms |   -1.28% |
|                                       90th percentile latency |      discovery-search-request-size-500 |  1634.72        |  1601.83        |    -32.8942      |     ms |   -2.01% |
|                                      100th percentile latency |      discovery-search-request-size-500 |  1890.45        |  1692.39        |   -198.053       |     ms |  -10.48% |
|                                       50th percentile latency |     discovery-search-request-size-1000 |  1693.52        |  1639.03        |    -54.4911      |     ms |   -3.22% |
|                                       90th percentile latency |     discovery-search-request-size-1000 |  1717.31        |  1667.72        |    -49.5883      |     ms |   -2.89% |
|                                      100th percentile latency |     discovery-search-request-size-1000 |  1853.05        |  1727.96        |   -125.09        |     ms |   -6.75% |
|                                       50th percentile latency |                        discover/search |   760.797       |   914.38        |    153.583       |     ms |  +20.19% |
|                                       90th percentile latency |                        discover/search |  2042.18        |  2125.56        |     83.3749      |     ms |   +4.08% |
|                                      100th percentile latency |                        discover/search |  2428.58        |  2625.85        |    197.271       |     ms |   +8.12% |
|                                       50th percentile latency |                     discover/visualize |   576.205       |   589.464       |     13.2594      |     ms |   +2.30% |
|                                       90th percentile latency |                     discover/visualize |  9670.48        | 11363.9         |   1693.38        |     ms |  +17.51% |
|                                      100th percentile latency |                     discover/visualize | 12262.2         | 13907.8         |   1645.69        |     ms |  +13.42% |
|                                       50th percentile latency |                                  kafka |   438.432       |   435.931       |     -2.50108     |     ms |   -0.57% |
|                                       90th percentile latency |                                  kafka |   779.353       |   747.71        |    -31.6431      |     ms |   -4.06% |
|                                      100th percentile latency |                                  kafka |  1085.6         |  1008.64        |    -76.9656      |     ms |   -7.09% |
|                                       50th percentile latency |                                  nginx |  1726.62        |  1726.49        |     -0.13483     |     ms |   -0.01% |
|                                       90th percentile latency |                                  nginx |  4389.83        |  4273.19        |   -116.639       |     ms |   -2.66% |
|                                      100th percentile latency |                                  nginx | 10210.4         |  9482.55        |   -727.885       |     ms |   -7.13% |
|                                       50th percentile latency |                                 apache |   363.002       |   379.09        |     16.0885      |     ms |   +4.43% |
|                                       90th percentile latency |                                 apache |   978.327       |   925.636       |    -52.6907      |     ms |   -5.39% |
|                                      100th percentile latency |                                 apache |  1970.13        |  1909.62        |    -60.5059      |     ms |   -3.07% |
|                                       50th percentile latency |                            system/auth |   325.808       |   325.612       |     -0.19592     |     ms |   -0.06% |
|                                       90th percentile latency |                            system/auth |   426.179       |   412.91        |    -13.2686      |     ms |   -3.11% |
|                                       99th percentile latency |                            system/auth |  4752           |  4729.08        |    -22.9176      |     ms |   -0.48% |
|                                      100th percentile latency |                            system/auth |  4891.44        |  5199.63        |    308.187       |     ms |   +6.30% |
|                                       50th percentile latency |                system/syslog/dashboard |   393.13        |   393.623       |      0.493       |     ms |   +0.13% |
|                                       90th percentile latency |                system/syslog/dashboard |  1360.45        |  1274.03        |    -86.4237      |     ms |   -6.35% |
|                                      100th percentile latency |                system/syslog/dashboard |  3892.67        |  3363.56        |   -529.105       |     ms |  -13.59% |
|                                       50th percentile latency |                     system/syslog/lens |   853.748       |   853.351       |     -0.39737     |     ms |   -0.05% |
|                                       90th percentile latency |                     system/syslog/lens |  2075.03        |  2014.54        |    -60.4871      |     ms |   -2.92% |
|                                      100th percentile latency |                     system/syslog/lens |  4155.92        |  3682.25        |   -473.664       |     ms |  -11.40% |
|                                       50th percentile latency |                        mysql/dashboard |   317.356       |   318.442       |      1.08632     |     ms |   +0.34% |
|                                       90th percentile latency |                        mysql/dashboard |   801.353       |   776.493       |    -24.8602      |     ms |   -3.10% |
|                                      100th percentile latency |                        mysql/dashboard |  1550.73        |  1586.76        |     36.0261      |     ms |   +2.32% |
|                                       50th percentile latency |                                  redis |   621.144       |   637.224       |     16.0809      |     ms |   +2.59% |
|                                       90th percentile latency |                                  redis |  2244.7         |  1773.32        |   -471.383       |     ms |  -21.00% |
|                                      100th percentile latency |                                  redis |  3057.48        |  2575.3         |   -482.178       |     ms |  -15.77% |
|                                       50th percentile latency |                             mysql/lens |  1003.95        |  1004.12        |      0.16513     |     ms |   +0.02% |
|                                       90th percentile latency |                             mysql/lens |  2460.98        |  2346.44        |   -114.538       |     ms |   -4.65% |
|                                      100th percentile latency |                             mysql/lens |  3186.96        |  2647.6         |   -539.363       |     ms |  -16.92% |
|                                       50th percentile latency |                    postgresql/overview |  1023.16        |  1022.58        |     -0.58295     |     ms |   -0.06% |
|                                       90th percentile latency |                    postgresql/overview |  1114.29        |  1110.52        |     -3.77412     |     ms |   -0.34% |
|                                       99th percentile latency |                    postgresql/overview |  1675.19        |  1674.96        |     -0.22703     |     ms |   -0.01% |
|                                      100th percentile latency |                    postgresql/overview |  1675.82        |  1675.07        |     -0.75452     |     ms |   -0.05% |
|                                       50th percentile latency |                    postgresql/duration |   320.598       |   320.463       |     -0.13458     |     ms |   -0.04% |
|                                       90th percentile latency |                    postgresql/duration |   639.049       |   635.513       |     -3.53601     |     ms |   -0.55% |
|                                      100th percentile latency |                    postgresql/duration |  4171.85        |  4166.67        |     -5.18555     |     ms |   -0.12% |

```

**Comment by jpountz** [comment]
I'm good with the change, lowering the max docs per block should generally improve retrieval latencies, and it's a backward-compatible change.

The benchmark results are a bit surprising to me, it looks like `discovery-search-request-size-100`'s median latency halves when going from 128 docs per block to 96 docs per block and then doubles again when going from 96 docs per block to 64 docs per block.

**Comment by martijnvg** [comment]
> The benchmark results are a bit surprising to me, it looks like discovery-search-request-size-100's median latency halves when going from 128 docs per block to 96 docs per block and then doubles again when going from 96 docs per block to 64 docs per block.

This is unexpected to me as well. Additionally the `discover/visualize` and `discover/search` use cases performed worse, while disk usage was slightly higher. I think evaluating this change in nightly benchmarks should be the next step.

**Review by jpountz — APPROVED** [review]
This works for me.

**Pull request merged**
