### PR TITLE
Remove accept SocketPermissions from core

### PR DESCRIPTION
**Pull request by Tim-Brooks**
This is related to #22116. Core no longer needs `SocketPermission` 
`accept`. This permission is relegated to the transport-netty4 module 
and (for tests) to the mocksocket jar.

### CODE REVIEW

**Comment by tbrooks8** [comment]
On the reindex module needing `accept` for tests issue:

One option would be to add the following permissions to the test-framework.policy file:
```
grant codeBase "${codebase.netty-transport-4.1.7.Final.jar}" {
   permission java.net.SocketPermission "*", "accept";
};

grant codeBase "${codebase.transport-netty4-6.0.0-alpha1-SNAPSHOT.jar}" {
  permission java.net.SocketPermission "*", "accept";
};
```

Unfortunately, that does not work with IDE junit test runners. As I [mentioned](https://github.com/elastic/elasticsearch/issues/22116#issuecomment-269269119), I had worked on adding support for parsing the directory code paths. The downside of that is you would need to duplicate permissions for the jar version of transport-netty4 (gradle runner) and the directory version of transport-netty4 (idea/probably eclipse runner).

The second option, is that the `doPrivileged` blocks move down to the netty level (netty/netty#6146). Then transport-netty4 module will not need permissions.

Or maybe someone else has a better idea on this?

**Comment by tbrooks8** [comment]
Also I see that this broke the integration tests. So I'll need to resolve that before it is merged.

**Comment by tbrooks8** [comment]
I opened PR #22646 which I believe will be necessary for the integration tests to pass in relation to this PR.

**Comment by tbrooks8** [comment]
Alright @jasontedor and @s1monw - with the build updates to master this should be ready for review.

The build changes also removed the need for reindex to have `SocketPermission`.

**Review by s1monw — APPROVED** [review]
LGTM hell yeah

**Review by jasontedor — APPROVED** [review]
LGTM.

**Pull request merged**
