### PR TITLE
Throw parsing errors on unknown keys in warmers configuration json

### PR DESCRIPTION
**Pull request by bleskes**
The Index Warmers code is too lenient w.r.t unknown configuration options. Accepting them lead to other parsing problems, for example wrongfully setting the source to null.

### CODE REVIEW

**Comment by s1monw** [comment]
+1 to @spinscale suggestion - @bleskes will you pick this up at any point or should I find somebody?

**Comment by bleskes** [comment]
@s1monw - I'll give it another shot..

**Comment by nik9000** [comment]
Is this intentionally now ```adoptme```?  @bleskes if you don't want this you can assign it to me and I'll finish it up.

**Comment by bleskes** [comment]
@nik9000 erhm - this is so long ago I don't remember .. my bad for not getting to it. Do feel free to pick it up

**Comment by clintongormley** [comment]
Warmers have been removed so this is no longer needed.  Closing

**Pull request closed without merging**
