### PR TITLE
Add DownsampleMetrics

### PR DESCRIPTION
**Pull request by kkrik-es**
A single instance gets created by the `Downsample` plugin and injected to related actions.

### CODE REVIEW

**Comment by kkrik-es** [comment]
Another option is to return (inject) the `DownsampleMetrics` object in `Downsample::createComponents`, so that it can be retrieved in actions. This lifts the need for a singleton but will still require updating a number of intermediate classes until we get to the code that records a metric value.

**Review by martijnvg — APPROVED** [review]
LGTM - I thought we have some sort of a unit test infrastructure that we can use for metrics. @salvatore-campagna do you remember?

**Comment by kkrik-es** [comment]
> LGTM - I thought we have some sort of a unit test infrastructure that we can use for metrics. @salvatore-campagna do you remember?

https://github.com/elastic/elasticsearch/blob/main/modules/apm/METERING.md#testing says we use `TestTelemetryPlugin`, not sure if there's a better way..

**Comment by martijnvg** [comment]
> says we use TestTelemetryPlugin, not sure if there's a better way..

Ok, I see. And this is already tested in the changes to the unit test in this pr.

**Pull request merged**
