### PR TITLE
[DOCS] Use `s` parameter in cat API overview example

### PR DESCRIPTION
**Pull request by jrodewig**
Updates a snippet to use the `s` query string parameter rather than piping the output to a separate `sort` command.

This ensures the snippet is tested and available in clients other than curl (Kibana console, etc.).

Issue was originally raised by @hackaholic in #40926.

### CODE REVIEW

**Comment by jrodewig** [comment]
Hmmm... I suspect this has something to do with the store size numbers and the test response regex. Throwing a `WIP` label on here until that's fixed.

**Comment by jrodewig** [comment]
Managed to simplify and fix the regex for the test response. Should be ready for review now.

**Review by martijnvg — APPROVED** [review]
LGTM

**Comment by jrodewig** [comment]
Thanks @martijnvg!

**Comment by jrodewig** [comment]
### Backport commits
master: 9c192ca037df54f0ac9483d8c28ba2a8f13282b4
7.x: f028ab08d16ca0f6c5ce65b68157bb3794668033
7.5: 1a96cb99d4c266f4d58077ee0518c877ade5a4d3

**Pull request merged**
