### PR TITLE
Include murmur3 client side reference

### PR DESCRIPTION
**Pull request by RubieV**
Using the murmur3 mapper that is available on git. Have looked for it for a while, saw many people who where asking why it wasn't in the docs.

### CODE REVIEW

**Comment by clintongormley** [comment]
Hi @RubieV 

Thanks for the PR, but I don't understand why you're linking to the code for the murmur3 plugin?  The docs already link to to murmur3 plugin docs here https://www.elastic.co/guide/en/elasticsearch/plugins/current/mapper-murmur3.html

**Comment by RubieV** [comment]
Hi Clinton,

The guide mentions doing hashing client side, but don't give any reference
implementation on how to do that. The murmur3 docs are just documentation
on how to use ElasticSearch murmur3 plugin.

Therefore I linked that actual integration to the guide so it is clear how
to implement it without searching the whole Internet and finding many
others looking for reference implementation.

Maybe the link isn't the most fashionable way of linking those two together
but will certainly be useful.  What do you suggest?

Ruben
Op 17 nov. 2015 12:01 schreef "Clinton Gormley" <notifications@github.com>:

**Comment by clintongormley** [comment]
Ah OK. Thanks for the explanation.  I'm leaning towards thinking that either you know how to hash something, or you'd just use the plugin.  Why would just copy/paste the code from the plugin?

**Comment by RubieV** [comment]
@clintongormley Sorry for the late response! So, in our solution we calculate a hash the moment a nested document comes in. We have to calculate a hash for that document for the processes that are to be executed on that document, before it is indexed. 

However we want to be exactly consistent with ElasticSearch in creating a hash, therefore I want the exact same implementation. 

I think it might help to include the way ES is creating the hash in the documentation of ES, under the section client side hashing. After all, that is what we're doing, and I was expecting to find an example implementation there as well.

**Comment by clintongormley** [comment]
Hi @RubieV 

That sounds pretty use case specific to me.  I'm loathe to add a link to this code because there is a good chance it'll 404 pretty soon, and we won't know about it.

Thanks, but I think I'm not going to merge this.

**Pull request closed without merging**
