### PR TITLE
Don't pass feature flag to non-snapshot artifacts

### LINKED ISSUE #78219: Mixed cluster tests failing in release builds due to feature flag
We have an issue which I believe is fallout from #77626. The root issue is that we are passing a feature flag, but when doing BWC tests, the BWC distribution isn't built in release mode.

```
»  Caused by: java.lang.IllegalArgumentException: es.index_mode_feature_flag_registered is only supported in non-snapshot builds
»  	at org.elasticsearch.index.IndexSettings.<clinit>(IndexSettings.java:351) ~[elasticsearch-7.16.0-SNAPSHOT.jar:7.16.0-SNAPSHOT]
»  	... 13 more
```

So in this case we are testing 8.0.0 against 7.16.0-SNAPSHOT. We pass `-Dbuild.snapshot=true` when bulding `master` (8.0.0) but not when building the BWC snapshot version (`7.x` or `7.16` in this case).

What we _should_ do I suppose depends on what we're trying to test here. Our options are:

1. We carry forward the `-Dbuild.snapshot` flag to the BWC builds so we are testing mixed "released" versions.
2. We only enable the feature flag on `master` nodes and omit it when configuring the BWC nodes.

### PR DESCRIPTION
**Pull request by mark-vieira**
When configuring BWC tests to use feature flags, we need to ensure we
don't inadvertently enable the flag on the old version nodes, as those
are NOT release builds and therefore fail if the feature flag is
present. This commit tweaks our config here to ensure we explicitly
enable the flag only on the upgraded nodes.

Closes #78219

### CODE REVIEW

**Review by breskeby — APPROVED** [review]

**Comment by mark-vieira** [comment]
@elasticmachine update branch

**Comment by mark-vieira** [comment]
@elasticmachine run elasticsearch-ci/release-tests

**Comment by mark-vieira** [comment]
@elasticmachine run elasticsearch-ci/release-tests

**Comment by mark-vieira** [comment]
@elasticmachine update branch

**Comment by mark-vieira** [comment]
@elasticmachine run elasticsearch-ci/release-tests

**Comment by mark-vieira** [comment]
@elasticmachine run elasticsearch-ci/release-tests

**Comment by mark-vieira** [comment]
@elasticmachine update branch

**Comment by mark-vieira** [comment]
@elasticmachine run elasticsearch-ci/release-tests

**Comment by mark-vieira** [comment]
@elasticmachine update branch

**Comment by mark-vieira** [comment]
@elasticmachine run elasticsearch-ci/release-tests

**Comment by hendrikmuhs** [comment]
@mark-vieira does this fix #80479?

**Comment by mark-vieira** [comment]
> @mark-vieira does this fix #80479?

Yep, this addresses that issue as well. Thanks.

**Pull request merged**
