### PR TITLE
Reduce the number of calls to document() from LeafStoredFieldsLookup

### PR DESCRIPTION
**Pull request by romseygeek**
LeafStoredFieldsLookup currently uses a SingleFieldsVisitor to load values, which
will be inefficient if a script references more than one stored field.  This commit 
refactors the lookup to remember all the fields that are requested, along with the
ability to pre-register fields so that the first lookup will also only read from disk
once.

Relates to #66256

### CODE REVIEW

**Comment by romseygeek** [comment]
The idea here is that in future SourceLookup can depend on LeafStoredFieldsLookup to load its values, allowing us to consolidate loading source and stored fields together in a single place rather than spread across the Fetch phase.

**Comment by jtibshirani** [comment]
I still need to ponder the refactor in detail, but had an initial thought.

> The idea here is that in future SourceLookup can depend on LeafStoredFieldsLookup to load its values,

I see these `Leaf*Lookup` classes as specifically designed for scripting. They make sure to implement `Map<String, Object>`, sometimes add an extra caching layer, etc. I wonder if we should keep script data structures separate from the general lookup case for flexibility/ clarity. The fact that `SourceLookup` is used in both cases has actually caused complexity, see [this comment](https://github.com/elastic/elasticsearch/blob/7.11/server/src/main/java/org/elasticsearch/search/lookup/SourceLookup.java#L67-L70) for example.

**Comment by mark-vieira** [comment]
@elasticmachine update branch

**Comment by anupamgogoi0907** [comment]
Hi Team,
Is the issue solved? I don't see any further comments.
Thanks.

**Pull request closed without merging**
