### PR TITLE
Remove some usages of MapBuilder#immutableMap

### PR DESCRIPTION
**Pull request by jasontedor**
This method can be replaced by some convenience collection factory methods available in the JDK now. This commit does not attempt to replace all usages, only enough that the size of the commit is kept to a reasonable size.

### CODE REVIEW

**Comment by jasontedor** [comment]
@elasticmachine run elasticsearch-ci/1

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by jasontedor** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by jasontedor** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by jasontedor** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by jasontedor** [comment]
The failure in the packaging sample will be addressed by #41626.

**Pull request merged**
