### PR TITLE
Don't use a static QueryShardResult for a null instance

### LINKED ISSUE #52042: [CI] ArraySearchPhaseResults shardIndex is already set
I've come across various apparently unrelated integration tests with the following error stacktrace:
```
        Caused by:	
        java.lang.AssertionError: shardIndex: 3 is already set	
            at __randomizedtesting.SeedInfo.seed([A373DD6CE0DE449A]:0)	
            at org.elasticsearch.action.search.ArraySearchPhaseResults.consumeResult(ArraySearchPhaseResults.java:43)	
            at org.elasticsearch.action.search.SearchPhaseController$1.consumeResult(SearchPhaseController.java:745)	
            at org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardResult(AbstractSearchAsyncAction.java:471)	
            at org.elasticsearch.action.search.AbstractSearchAsyncAction.access$000(AbstractSearchAsyncAction.java:67)	
            at org.elasticsearch.action.search.AbstractSearchAsyncAction$1.innerOnResponse(AbstractSearchAsyncAction.java:235)
```

Example build scans:
7.x DateHistogramIT https://gradle-enterprise.elastic.co/s/wgy33s2eh6emy
7.x FieldSortIT https://gradle-enterprise.elastic.co/s/nwzskgzmeycmq
7.x MachineLearningLicensingTests https://gradle-enterprise.elastic.co/s/twukyytwyk2vg

It's tedious to find all occurrences of it as this part of the stacktrace is not indexed in build-stats .

### PR DESCRIPTION
**Pull request by romseygeek**
Fixes #52042

### CODE REVIEW

**Comment by romseygeek** [comment]
Marked as `non-issue` because it's a fix for an unreleased bug.

**Review by jtibshirani — APPROVED** [review]
This change makes sense to me, and it seems plausible it could be causing the failures in #52042.

**Comment by jtibshirani** [comment]
We are seeing this failure pop up fairly frequently on master intake -- @romseygeek gave the okay to merge this fix now.

**Comment by tvernum** [comment]
This is still failing on 7.x builds, I won't mute them, but if we can get the 7.x backport done quickly that would help.

**Comment by romseygeek** [comment]
I backported to 7.x in 9b7e688f5b023af399819b9600c0a7a6908723a9

**Pull request merged**
