### PR TITLE
Clean up BoxplotAggregator to reuse AbstractTDigestPercentilesAggregator

### PR DESCRIPTION
**Pull request by imotov**
Refactors BoxplotAggregator to reuse parts that are already available in
AbstractTDigestPercentilesAggregator

Follow up for #51948

### CODE REVIEW

**Review by nik9000 — APPROVED** [review]
Neat! I haven't given it a super in depth look but as long as you aren't trying to sneak something tricky in I think I get it and I'm all for it.

**Comment by polyfractal** [comment]
I was just about to LGTM as well, but remembered the histo field in VS branch (and thus soon master) will be changing: https://github.com/elastic/elasticsearch/pull/53298/

E.g. the Histo VSType and related are moving to XPack where they belong and the histo-specific aggregating logic is getting pulled out of Core.  Which means `AbstractTDigestPercentilesAggregator` is now specifically just about numeric percentiles, and the histo'y bits are separated into a different aggregator in XPack.

I think if we merge we'll end up undoing this in a few weeks.  There still might be a way to share code though, haven't looked super closely at how it will mesh up with the VS stuff.

**Comment by imotov** [comment]
Interesting. So, should we close this and then revisit again when #53298 lands?

**Comment by polyfractal** [comment]
Yeah that might be for the best.  Sorry, when I suggested code sharing in the last PR I didn't think about us also moving histo around too :(

**Comment by imotov** [comment]
Well, technically, we didn't have histo support in the PR where reuse was suggested :) I added it later. So, your suggestions was correct at a time and I didn't revisit it later on. Good catch!

**Pull request closed without merging**
