### PR TITLE
Allowed indices matcher supports nested limited roles

### PR DESCRIPTION
**Pull request by n1v0lg**
This PR modifies the `allowedIndicesMatcher` method to work with nested `LimitedRole` instances (i.e., limited roles that have a base role or limited by role that is itself a limited role). Prior to this fix, the method would throw an unsupported operation exception. This change is necessary to support remote access roles under the new remote cluster security model. 

Note: there are other methods with the same issue, however, those are not relevant to remote cluster security work. Instead, they are only relevant to the HasPrivilege check which currently does not require nested role support. As such, I'm not addressing them in this PR. I will add a Jira issue to track these, but they are not a priority right now.

### CODE REVIEW

**Review by ywangd — APPROVED** [review]
LGTM

**Comment by n1v0lg** [comment]
Failure unrelated and tracked here: https://github.com/elastic/elasticsearch/issues/93335

**Comment by n1v0lg** [comment]
@elasticmachine update branch plz

**Comment by n1v0lg** [comment]
@elasticsearchmachine run elasticsearch-ci/part-1-fips

**Comment by n1v0lg** [comment]
@elasticmachine update branch

**Pull request merged**
