### PR TITLE
[test-framework] Delete repositories after all snapshots have been wiped out

### LINKED ISSUE #90557: [CI] DocsClientYamlTestSuiteIT test {yaml=reference/snapshot-restore/register-repository/line_167} failing
Looks like a SLM hourly policy that was running when tearing down the test.

**Build scan:**
https://gradle-enterprise.elastic.co/s/rkufuj4sgudwq/tests/:docs:yamlRestTest/org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT/test%20%7Byaml=reference%2Fsnapshot-restore%2Fregister-repository%2Fline_167%7D

**Reproduction line:**
`./gradlew ':docs:yamlRestTest' --tests "org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT.test {yaml=reference/snapshot-restore/register-repository/line_167}" -Dtests.seed=5612AF44C2CEA45F -Dtests.locale=cs -Dtests.timezone=JST -Druntime.java=17`

**Applicable branches:**
8.5

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT&tests.test=test%20%7Byaml%3Dreference/snapshot-restore/register-repository/line_167%7D

**Failure excerpt:**
```
java.lang.AssertionError: Found in progress snapshots [{my_repository=[{metadata={policy=hourly-snapshots}, failures=[], include_global_state=true, end_time=1970-01-01T00:00:00.000Z, duration_in_millis=0, version_id=8050099, repository=my_repository, uuid=Ot6_ywoORMWMTG6SrzkJ1g, version=8.5.0, start_time=2022-09-30T10:59:59.950Z, shards={total=0, failed=0, successful=0}, indices=[], feature_states=[], start_time_in_millis=1664535599950, data_streams=[], state=IN_PROGRESS, snapshot=hourly-snapshot-2022.09.30-xelmht9qs6g56_2jshdepq, end_time_in_millis=0}]}].
Expected: a map with size <0>
     but: map size was <1>

  at __randomizedtesting.SeedInfo.seed([5612AF44C2CEA45F:DE46909E6C32C9A7]:0)
  at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
  at org.junit.Assert.assertThat(Assert.java:956)
  at org.elasticsearch.test.rest.ESRestTestCase.wipeCluster(ESRestTestCase.java:820)
  at org.elasticsearch.test.rest.ESRestTestCase.cleanUpCluster(ESRestTestCase.java:405)
  at jdk.internal.reflect.GeneratedMethodAccessor15.invoke(null:-1)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:1004)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

```

### PR DESCRIPTION
**Pull request by arteam**
Instead of deleting repositories on the go, delete them in one call after all snapshots have been wiped out. This reduce the probability a race condition between deleting a repository a potential new snapshot being added to the repository after we cleaned it.

Fixes #90557

### CODE REVIEW

**Comment by arteam** [comment]
@elasticmachine run elasticsearch-ci/part-3

**Comment by arteam** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by original-brownbear** [comment]
> This reduce the probability a race condition between deleting a repository a potential new snapshot being added to the repository after we cleaned it.

Isn't it technically more likely that a new snapshot has been created now that we don't delete a repo asap but instead wait for cleaning up all the snapshots before we delete the repos?
Not that it matters much for the default case I think, we mostly only have a single repo in these tests, not sure this even changes anything for those?

**Comment by arteam** [comment]
> Isn't it technically more likely that a new snapshot has been created now that we don't delete a repo asap but instead wait for cleaning up all the snapshots before we delete the repos?
Not that it matters much for the default case I think, we mostly only have a single repo in these tests, not sure this even changes anything for those?

There used to be no check whether there were in-progress snapshots for the repo being deleted. I previously tried to fix it in #88135 where Tanguy suggested move deleting of repositories out of the `wipeSnapshots` method.

**Pull request closed without merging**
