### PR TITLE
Show concrete error when enrich index not exist rather than NPE

### PR DESCRIPTION
**Pull request by puppylpg**
There should be NullPointerException check and throw index not found exception to the response so the user can understand what happens with the enrich index, rather than just "Caused by: java.lang.NullPointerException: Cannot invoke "org.elasticsearch.cluster.metadata.IndexAbstraction.getIndices()" because "ia" is null", which is confusing for user.

To solve #96122

### CODE REVIEW

**Comment by jbaiera** [comment]
Thanks for contributing this! I don't know if this is for sure related to https://github.com/elastic/elasticsearch/issues/96122 or if it just simply has the same error message, so I've left the issue unlinked in the change log entry.

**Comment by jbaiera** [comment]
@elasticmachine ok to test

**Comment by jbaiera** [comment]
@elasticmachine update branch

**Comment by puppylpg** [comment]
> Thanks for contributing this! I don't know if this is for sure related to #96122 or if it just simply has the same error message, so I've left the issue unlinked in the change log entry.

I'm sure that's the same problem because that's a colleague of mine. 😸 He met the issue but have no controll of that cluster(7.17.7), then after a while I encounter the same problem in data center migration(7.12.0 -> 7.17.6) and get the detailed error log.

Plus, [after upgrading to latested 7.17.13](https://github.com/elastic/elasticsearch/pull/94702), the problem is solved indeed. Thanks for your effort.

**Comment by jbaiera** [comment]
> I'm sure that's the same problem because that's a colleague of mine. 😸

Oh nice, didn't realize. Consider my previous suspicion invalidated 😄 

It looks like there's just a couple of check style issues that I should be able to clear on my own. The change LGTM, I can merge it after we get a green CI build.

**Review by jbaiera — APPROVED** [review]
LGTM pending green CI

**Comment by joegallo** [comment]
@elasticmachine run elasticsearch-ci/part-1

**Comment by jbaiera** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|7.17|[](https://github.com/elastic/elasticsearch/pull/100155)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
