### PR TITLE
Simplify Block/Vector Serialization

### PR DESCRIPTION
**Pull request by ChrisHegarty**
This commit reworks and simplifies the serialization of Block and Vectors. Rather than having a separate NamedWritable for block views of vectors, we instead just encode a boolean bit into the stream. This allows for different backing implementations to be used without triggering the assertion that the NamedWritable registry entry of the deserialised instance must be the same as that of the name in the stream.

### CODE REVIEW

**Review by nik9000 — APPROVED** [review]
Makes sense to me but I didn't scan too closely. Anyone else want to review?

**Review by luigidellaquila — APPROVED** [review]
LGTM, thanks Chris!

**Review by dnhatn — APPROVED** [review]
LGTM. Thanks, Chris!

**Review by costin — APPROVED** [review]
LGTM

**Pull request merged**
