### PR TITLE
Unmute RollupActionSingleNodeTests and watch CI

### LINKED ISSUE #69506: RollupActionSingleNodeTests.testTemporaryIndexDeletedOnRollupFailure
**Build scan**:
https://gradle-enterprise.elastic.co/s/naqu7x7qvcw6q

**Repro line**:
> ./gradlew ':x-pack:plugin:rollup:test' --tests "org.elasticsearch.xpack.rollup.v2.RollupActionSingleNodeTests.testTemporaryIndexDeletedOnRollupFailure" -Dtests.seed=609D1DD31C78D15E -Dtests.security.manager=true -Dtests.locale=nn-NO -Dtests.timezone=Asia/Bahrain -Druntime.java=11

**Reproduces locally?**:
No

**Applicable branches**:
master

**Failure history**:
Only [once in past 30 days](https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(_source),index:b646ed00-7efc-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:testTemporaryIndexDeletedOnRollupFailure),sort:!(process.time-start,desc))). So it could be transient. 

**Failure excerpt**:
```
java.lang.AssertionError: test leaves indices that were not deleted: jzklrm |  
-- | --
  | Expected: [] |  
  | but: was ["jzklrm"]
```

### PR DESCRIPTION
**Pull request by talevy**
this commit unmutes the tests so that more CI runs with
new code that includes better error messages will highlight why
tests are flaky.

relates #69506, #69799, #69733.

Closes #69506.

### CODE REVIEW

**Comment by talevy** [comment]
please test this

**Comment by talevy** [comment]
run elasticsearch-ci/2

**Comment by talevy** [comment]
run elasticsearch-ci/2

**Review by csoulios — APPROVED** [review]
LGTM!

**Pull request merged**
