### PR TITLE
[DOCS] Add CCR docs to the Elasticsearch Reference Guide

### PR DESCRIPTION
**Pull request by jrodewig**
### Changes

- Changes "Administering Elasticsearch" to "Set up a cluster for high availability," including renaming and moving several related files.
- Moves a several intro paragraphs from "Back up a cluster's data" to "Set up a cluster for high availability."
- Include cross-cluster replication (CCR) docs in "Set up a cluster for high availability."
Previously, cross-cluster replication (CCR) documentation was located only in
the Stack Overview. This inclusion requires level-offsets, which will be removed in a later PR.
- Adds a redirect for "Administering Elasticsearch."

Relates to #45703

### Preview
http://elasticsearch_45704.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/xpack-ccr.html

### CODE REVIEW

**Review by lcawl — APPROVED** [review]
LGTM

**Review by debadair — CHANGES_REQUESTED** [review]
We need to be consistent about where we put admin topics--having some under "Administration" and some at the top level is confusing. CCS has both an admin configuration element and a search usage element, where CCR is more purely an admin topic. If we opt to bump the admin topics to the top level, I think we need to group them. Putting CCR in between the Query DSL and Scripting and Mapping sections doesn't seem like the right place. One option might be to split the info on how to write a query to search multiple clusters from how to set up remotes and enable cross-cluster search and cross-cluster replication.

**Comment by jrodewig** [comment]
@debadair @lcawl  I've edited the PR message and added a few commits based on docs architecture discussion.

This changes "Administering Elasticsearch" to "Set up a cluster for high availability." It also moves several paragraphs from "Back up a cluster's data" to this new chapter.

**Comment by lcawl** [comment]
I suggest moving these pages so they're peers with the "Overview" page, since otherwise they're being merged into it:

http://elasticsearch_45704.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/ccr-overview.html#ccr-requirements
http://elasticsearch_45704.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/ccr-overview.html#ccr-auto-follow

Otherwise, the links here https://github.com/elastic/stack-docs/pull/464 (and anywhere else that link to those pages) will need to be updated to avoid broken links.

**Comment by jrodewig** [comment]
Thanks for the suggestion @lcawl. I've moved those pages up one level with 99facb8.

**Review by lcawl — APPROVED** [review]
LGTM and builds successfully when combined with stack-docs PR

**Review by debadair — APPROVED** [review]
LGTM

**Pull request merged**
