### PR TITLE
Remove component settings from AbstractComponent

### PR DESCRIPTION
**Pull request by s1monw**
Today we have two ways of getting a setting, either with the full settings key or with only
the last part of the key where the prefix is implicit depending on the package the class is in via
component settings. this is trappy as well as confusing for users and can break easily if a class is moved
to a new package since the prefix then implicitly changes.
This commit removes the component settings from the codebase.

### CODE REVIEW

**Comment by dadoonet** [comment]
Note that this will have of course consequences in plugins.

Now that we use full path for setting names, could we define static final String for those?
So we can reuse them in tests and plugins?

**Comment by s1monw** [comment]
@dadoonet there are no consequences in plugins you always had to specify the full key in the settings.

**Comment by mikemccand** [comment]
+1 to have just one way to get settings.

**Comment by martijnvg** [comment]
+1 the bwc issues that can happen from moving a class makes component settings trappy.

**Comment by dadoonet** [comment]
Forgot to say that I'm +1 as well.
About consequences I meant that we need only to fix the code and use fullpath there as well.

**Pull request merged**
