### PR TITLE
Avoid scaling empty tier unnecessarily

### PR DESCRIPTION
**Pull request by henningandersen**
Autoscaling supports data tiers using attributes. This commit refines
the check to avoid bootstrapping a tier when a non-filter decider says
NO.

### CODE REVIEW

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Comment by henningandersen** [comment]
@elasticmachine update branch

**Comment by henningandersen** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by anmironov** [comment]
@DaveCTurner @henningandersen 
Is it fix also related to below setting? (no ILM policies  with warm/cold phase and no exclude attribute in indices settings , but during autoscalling warm and cold nodes were unexpectedly created)

  "transient" : {
    "cluster.routing.allocation.enable" : "all",
    "cluster.routing.allocation.exclude._name" : "no_instances_excluded"
  }

**Comment by henningandersen** [comment]
@anmironov having those settings with those values should not relate to this issue. If you had them set differently, it might though (i.e., disabling allocation or excluding an actual node).

**Pull request merged**
