### PR TITLE
[DOCS] Fix typo in index and search analysis docs

### PR DESCRIPTION
**Pull request by rhymes**
Fixing a typo in https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-index-search-time.html

### CODE REVIEW

**Comment by rhymes** [comment]
@markharwood I signed the CLA but the bot doesn't seem to recognize it, what can I do to fix that?

**Comment by jrodewig** [comment]
@elasticmachine  test this please

**Review by jrodewig — APPROVED** [review]
Thanks for the fix @rhymes.

**Comment by jrodewig** [comment]
### Backport commits
master 74b9878f69987250ed2df8e5278e22b51014acac
7.x 7eb4c07f1f1
7.6 1b3aa86

**Pull request merged**
