### PR TITLE
Do not refresh fast_refresh unpromotables

### PR DESCRIPTION
**Pull request by Tim-Brooks**
Currently the TransportShardRefreshAction waits for the unpromotables to
be refreshed in all circumstances where they exist. However, when the
index is marked as fast_refresh, this is not an expectation. This
commit removes this wait.

### CODE REVIEW

**Comment by volodk85** [comment]
Just for my understanding when you say `this is not an expectation` is it implied by this or something else?
https://github.com/elastic/elasticsearch/blob/4aa4a0d6b1bef463f0ed02429a24dff9090c3f5d/server/src/main/java/org/elasticsearch/action/admin/indices/refresh/TransportRefreshAction.java#L58-L62

**Comment by Tim-Brooks** [comment]
> Just for my understanding when you say this is not an expectation is it implied by this or something else?

The code you're linking is unrelated. That is just describing how many shards need to be active for a replication request to execute.

It's just the semantics of fast_refresh. Our basic rule is that a refresh action against an index must wait for all all unpromotables to be refreshed before the api returns. However, we've introduced this fast_refresh setting to side step this requirement for plugins implementing this setting.

**Review by kingherc — APPROVED** [review]
LGTM

You mentioned you may add a test for fast refresh in stateless, feel free to also assert counting any TransportUnpromotableShardRefreshAction messages there to be 0.

**Comment by Tim-Brooks** [comment]
@elasticsearchmachine run elasticsearch-ci/part-3

**Pull request merged**
