### PR TITLE
Rename AbstractKeywordDocValuesField to BaseKeywordDocValuesField and make it abstract

### PR DESCRIPTION
**Pull request by stu-elastic**
`AbstractKeywordDocValuesField` should not be directly instantiated.

### CODE REVIEW

**Review by rjernst — COMMENTED** [review]
Since there aren't any abstract methods, would it make more sense to rename this class, eg with the common "Base" prefix"?

**Comment by stu-elastic** [comment]
@elasticsearchmachine run elasticsearch-ci/part-1

**Comment by stu-elastic** [comment]
Changed name to BaseKeywordDocValuesField

**Review by rjernst — APPROVED** [review]
Looks good. The PR title should be adjusted.

**Pull request merged**
