### PR TITLE
Build: Upgrade min gradle to 3.3

### PR DESCRIPTION
**Pull request by rjernst**
This will allow us to get rid of deprecation warnings that appear when
using 3.3, and also get rid of extra logic for 2.13 required because of
the progress logger. This commit simply upgrades the minimum version to 3.3, and those other cleanups will be done as followups.

### CODE REVIEW

**Comment by nik9000** [comment]
Lgtm. Fire when ready.

**Comment by jasontedor** [comment]
There is a reference to version 2.13 in the CONTRIBUTING.md, and a reference to version 2.13 in README.textile. I think those should be changed with this change.

**Review by jasontedor — CHANGES_REQUESTED** [review]
There are a few places in the docs that should be updated with this.

**Comment by rjernst** [comment]
@jasontedor @nik9000 I updated the readme and contributing docs.

**Review by jasontedor — APPROVED** [review]
LGTM.

**Pull request merged**
