### PR TITLE
Suppress checkstyle on generated files in painless

### LINKED ISSUE #16387: Fix Imports Automatically in Painless
The ANTLR generated files currently have star imports in them when the files are regenerated.  Need to make it part of the ANT task to replace these imports automatically with non-star imports.

### PR DESCRIPTION
**Pull request by nik9000**
Closes #16387

### CODE REVIEW

**Comment by jasontedor** [comment]
LGTM. Thanks for doing this.

**Comment by nik9000** [comment]
@jdconrad is this ok?

**Comment by jdconrad** [comment]
@nik9000 Great!  Thanks for fixing this.

**Comment by nik9000** [comment]
Thanks for the reviews @jasontedor and @jdconrad! I'm glad I could help!

**Pull request merged**
