### PR TITLE
DocsStats: Add human readable bytesize

### PR DESCRIPTION
**Pull request by spinscale**
This adds support for the `human` parameter for DocsStats, as it was missing. Sample

```
GET _cluster/stats?human&filter_path=indices.docs
```

### CODE REVIEW

**Comment by spinscale** [comment]
Done.

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Comment by DaveCTurner** [comment]
@elasticmachine test this please

**Comment by DaveCTurner** [comment]
@elasticmachine test this please

**Comment by DaveCTurner** [comment]
@elasticmachine test this please

**Comment by DaveCTurner** [comment]
@elasticmachine test this please

**Pull request merged**
