### PR TITLE
SQL: Return functions in JDBC driver metadata

### LINKED ISSUE #33671: SQL: JDBC metadata advertised functions
Currently, the JDBC Database metadata returns empty strings for the methods indicating what SQL functions are supported. This is clearly not the case and needs to be fixed.

### PR DESCRIPTION
**Pull request by costin**
Update JDBC database metadata to advertised the supported functions
Add aliases to some date/time functions to match the ODBC spec

Fix #33671

### CODE REVIEW

**Review by astefan — COMMENTED** [review]
MONTHNAME and DAYNAME also have MONTH_NAME and DAY_NAME aliases. The spec mentions only the name without underscore, but I kept those as well since there are other functions that have un-spec'd aliases.

**Comment by costin** [comment]
The names with the underscore are not a problem (consistency) - the issue was that there weren't the aliases without the underscore, that the spec expects.

**Review by astefan — APPROVED** [review]
LGTM

**Review by matriv — APPROVED** [review]
LGTM

**Pull request merged**
