### PR TITLE
Improve network docs

### PR DESCRIPTION
**Pull request by rmuir**
This makes some minor improvements (does not fix all problems!)

It reorders unicast disco in elasticsearch.yml to be right after the network host,
for better locality.

It removes the warning (unreleased) about publish addresses, lets try to really discourage setting
that unless you need to (behind a proxy server). Most people should be fine with `network.host`

Finally it reorganizes the network docs page a bit:

We add a table of 4 "basic" settings at the very beginning:
- network.host
- discovery.zen.ping.unicast.hosts
- http.port
- transport.tcp.port

The first two being the most important, which addresses to bind and talk to, and the other two
being the port numbers.

The rest of the stuff I tried to simplify and reorder under "advanced" headers.

This is just a quick stab, I still think we need more effort into this thing, but we gotta start somewhere.

### CODE REVIEW

**Comment by dadoonet** [comment]
I love the new doc! :D

+1. Just wondering if we should keep the log as debug instead of removing but not a big deal...

**Comment by dakrone** [comment]
LGTM

**Comment by rmuir** [comment]
docs changes are invalid. hard to tell what's wrong... but i think something about one of the tables confuses asciidoc
```
asciidoc: modules.asciidoc: line 88: reading: /home/rmuir/workspace/elasticsearch/docs/reference/modules/network.asciidoc
asciidoc: ERROR: network.asciidoc: line 35: [tabledef-default] total width less than 100%: 0
asciidoc: ERROR: network.asciidoc: line 35: [tabledef-default] missing leading separator: (?msu)((?<!\S)((?P<span>[\d.]+)(?P<op>[*+]))?(?P<align>[<\^>.]{,3})?(?P<style>[a-z])?)?\|
asciidoc: WARNING: network.asciidoc: line 73: table row 1: empty spanned row
```

**Comment by nik9000** [comment]
LGTM if you can get asciidoc happy.

**Comment by rmuir** [comment]
I pushed commits fixing table and added a missing header and grammar fix.

Now you can see a reasonable approximation of the structure when you view the whole file in the review: https://github.com/rmuir/elasticsearch/blob/improve_network_docs/docs/reference/modules/network.asciidoc

**Comment by rmuir** [comment]
ok, i think i am done tweaking the wording for now :)

**Comment by nik9000** [comment]
LGTM

**Pull request closed without merging**
