### PR TITLE
[TEST] Remove redundant cluster checks

### PR DESCRIPTION
**Pull request by DiannaHohensee**
For the type label, would this be `>test` or `>non-issue`? I was perusing the [type labels here](https://docs.elastic.dev/elasticsearch-team/onboarding/elasticsearch-github-repo#type-labels)

### CODE REVIEW

**Review by DaveCTurner — COMMENTED** [review]
> For the type label, would this be >test or >non-issue? I was perusing the [type labels here](https://docs.elastic.dev/elasticsearch-team/onboarding/elasticsearch-github-repo#type-labels)

The difference is fairly subtle, but `>non-issue` is normally some kind of small or user-invisible change but may alter production code so we wouldn't backport it in general, whereas `>test` changes only touch test code and are fine to backport. Since there's no backport proposed here, it doesn't really matter. I'd call it `>test`.

Change itself LGTM but I have a couple of tiny admin nits (also from the [team docs](https://docs.elastic.dev/elasticsearch-team/onboarding/development-process#detour-commit-messages)):

- It's good to aim for a commit title of ~50 chars (not always possible, but we can definitely get closer to 50 here)

- It's almost always worth adding a longer body to the commit message with some extra context and links and so on. Here it would be good to link to the issues I mentioned in the [comment](https://github.com/elastic/elasticsearch/pull/98550#discussion_r1297499213) that gave rise to this PR:

> I think they were necessary when they were added in https://github.com/elastic/elasticsearch/pull/22182, but https://github.com/elastic/elasticsearch/pull/49248 changed that.

**Comment by DaveCTurner** [comment]
Oh and one other thing: you're free to choose whatever branch-naming convention you want, but I find `yyyy/mm/dd/some-words-and-hyphens` integrates best with IntelliJ's branch browser:

image

I have this in my `~/.zshrc` to help:

```
function git-new-branch() {
(
  set -euxo pipefail
  name="$*"
  branchname=$(date +%Y/%m/%d)/$(echo $name | sed -e 's/ /-/g')
  git checkout -b $branchname
)
}
```

That way I can type `git-new-branch some words and spaces` and it adds the date and hyphens for me.

**Comment by DiannaHohensee** [comment]
Thanks for the pointers! How about this commit message:
```
[TEST] Remove redundant cluster checks

Removes ensureStableCluster() calls in ClusterAllocationExplainIT
testing after startNode*() calls. The stabilization calls were
originally necessary when the tests were added in #22182. However,
#49248 later enhanced validateClusterFormed(), which startNode*()
implicitly calls, to perform similar checks to ensureStableCluster()
```
I believe I'll have to add the body when I click the merge button, at this point. I expect people usually include all of this in the first commit message when publishing a PR? Only way I can think to have it reviewed.

**Comment by DiannaHohensee** [comment]
> but I find yyyy/mm/dd/some-words-and-hyphens integrates best with IntelliJ's branch browser

Ahh, that does look nicer. Thanks for the script!
Yeah, I was browsing one of your PRs and liked how you named your branches, but I fiddled with the date ordering.

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Comment by DaveCTurner** [comment]
> I believe I'll have to add the body when I click the merge button, at this point. I expect people usually include all of this in the first commit message when publishing a PR? Only way I can think to have it reviewed.

Ideally it matches the title and description of the PR - that's the default behaviour in Github (if the branch has one commit when you open the PR) but it can be updated if needed.

If you press the merge button manually then you can adjust things, but if you want to use the `auto-merge` label then the bot will just copy the title and description of the PR into the commit message.

**Pull request merged**
