### PR TITLE
Compatible API Reindex size field

### PR DESCRIPTION
**Pull request by pgomulka**
The commit #43373 has removed outer level size field  in version 7.
This commit allows for the use of the size field in server ES8 using compatible REST API.

relates https://github.com/elastic/elasticsearch/issues/51816

### CODE REVIEW

**Comment by pgomulka** [comment]
test run
./gradlew ':modules:reindex:yamlRestCompatTest' --tests "org.elasticsearch.index.reindex.ReindexClientYamlTestSuiteIT.test {yaml=reindex/30_search/Sorting and size combined}" -Dtests.seed=D9A0CABA96A1A0E1 -Dtests.security.manager=true -Dtests.locale=fi -Dtests.timezone=Navajo -Druntime.java=15

**Comment by mark-vieira** [comment]
@elasticmachine update branch

**Comment by pgomulka** [comment]
@elasticmachine update branch

**Comment by pgomulka** [comment]
closing in favour of surgical approach https://github.com/elastic/elasticsearch/pull/69037

**Pull request closed without merging**
