### PR TITLE
[8.5] [Doc] Fix typo in the JWT realm doc (#92779)

### PR DESCRIPTION
**Pull request by ywangd**
Backports the following commits to 8.5:
 - [Doc] Fix typo in the JWT realm doc (#92779)

### CODE REVIEW

**Comment by ywangd** [comment]
@elasticmachine run elasticsearch-ci/rest-compatibility

**Comment by ywangd** [comment]
@elasticmachine update branch

**Comment by ywangd** [comment]
@elasticmachine update branch

**Comment by ywangd** [comment]
@elasticmachine update branch

**Comment by abdonpijpelink** [comment]
@elasticmachine update branch

**Pull request closed without merging**
