### PR TITLE
the transport/http worker thread will not be released for a long time

### PR DESCRIPTION
**Pull request by hanbj**
When the cluster is very large, when you call interfaces such as _cat/shards or _cat/indices or _all/_mapping, there is no response for a long time, and sometimes even gateway timeout, which is caused by the response is too large.
For example, the rest request method requests _all/_mapping. ES finally calls the toXContent() method to construct a json return. This is a very time-consuming operation and is executed in the http_server_worker thread.
A special thread pool is the same. When submitting tasks to the same thread pool, the worker thread is still the transport_worker / http_server_worker thread. If the task submitted to the same thread pool is a large task, it will cause the worker thread to not be released for a long time. Reduce overall system throughput.

### CODE REVIEW

**Comment by dliappis** [comment]
@hanbj Thank you for the PR. Can you please sign the [Contributor Agreement](https://www.elastic.co/contributor-agreement)?

**Comment by tbrooks8** [comment]
Can you provide the context behind this PR? My understanding here is that you are concerned that the XContent response is serialized on the transport thread for  _cat/shards or _cat/indices or _all/_mapping calls. How large of responses are we discussing and what type of latency does that introduce?

**Comment by hanbj** [comment]
@tbrooks8 thank you review this pr

**Comment by hanbj** [comment]
> @hanbj Thank you for the PR. Can you please sign the [Contributor Agreement](https://www.elastic.co/contributor-agreement)?
@dliappis Yes, I have signed the [Contributor Agreement](https://www.elastic.co/contributor-agreement)，Why all checks still fail?

**Comment by dliappis** [comment]
> > @dliappis Yes, Thank you. I have signed the [Contributor Agreement](https://www.elastic.co/contributor-agreement)，Why all checks still fail?

@hanbj the problem is that your first commit used a different email (`hanbj <hanbaojun@didi<REDACTING>.com>`) to your GitHub email (`@163.com`). 

One easy option is to resign with the email you committed with.

**Comment by hanbj** [comment]
@tbrooks8 @dliappis Do you have any other ideas about PR, I see  _cat/indices interface is submitted to the manager thread pool for execution, or we can add a thread pool in the ThreadPool class to handle large response.

**Comment by original-brownbear** [comment]
@hanbj how did you measure those 6s time and interpret it as the time to serialize (mainly wondering if your measurement includes non-blocking IO time as well)? Even though there's some expensive operations going on when serializing the mapping response, I find it somewhat unlikely that it will take 6s, even in the case of almost 100MB in mappings.

I think if we decide to fix this it would be fine to simply move the serialization to the generic pool and be done with it but I'm having a hard time reproducing a multi-second time to serialize.

**Comment by original-brownbear** [comment]
I hope you don't mind that I'll close this one for now since the change in this PR isn't something we want to go with as explained above. 
There is a possible (though still debatable and debated) mitigation open in #57937 and a performance improvement for compression in #60953 that should also help here.

Thanks so much for bringing this to our attention @hanbj

**Pull request closed without merging**
