### PR TITLE
Unmute testSupportedFieldTypes, fix Percentiles/Ranks/Terms tests

### PR DESCRIPTION
**Pull request by polyfractal**
The test was muted while merging master, because the differences felt too large to fix in a merge commit.  After this merges, master and this branch should be more closely aligned wrt this test, so it should be more straightforward in the future (:crossed_fingers: )

Also fixes `Percentiles` factory which was incorrectly specified to only accept numeric, but in fact also accepts Boolean and Date (because those are numeric on master - thanks `testSupportedFieldTypes` for catching it!)

### CODE REVIEW

**Review by not-napoleon — APPROVED** [review]
LGTM.  At some point, we should talk about removing support for some of these parings, like percentiles over booleans.

**Comment by polyfractal** [comment]
Github hiccuped and these tests succeeded but failed to update status :(  Gonna rerun just for the warm green CI fuzzies

@elasticmachine run elasticsearch-ci/2
run elasticsearch-ci/packaging-sample-matrix-unix
run elasticsearch-ci/packaging-sample-matrix-windows

**Review by csoulios — APPROVED** [review]
LGTM

**Comment by polyfractal** [comment]
Thanks all!

**Pull request merged**
