### PR TITLE
Modify link of install Elasticsearch

### PR DESCRIPTION
**Pull request by y-vectorfield**
Link of install.asciidoc is not correct. I modified this link.

### CODE REVIEW

**Review by cbuescher — COMMENTED** [review]
Looking at the version of this page [on master that is online](https://www.elastic.co/guide/en/elasticsearch/reference/master/getting-started-install.html), the link works for me and is pointing to https://www.elastic.co/guide/en/elasticsearch/reference/master/install-elasticsearch.html.
Would you mind sharing what you are seeing? I think the link is correct as is.

**Comment by y-vectorfield** [comment]
@cbuescher 
Thank you very much for your comment. I'm sorry, this modify arose from my misunderstanding.
I am going to close this pull request.

By the way, I have a question. Why do you use {es} attribution of asciidoc in reference/setup/install.asciidoc? If it is necessary to modify, I am going to submit a pull request.

**Comment by cbuescher** [comment]
> Why do you use {es} attribution of asciidoc in reference/setup/install.asciidoc

Thanks for asking, to be honest I don't know but @jrodewig might have an answer to that. I don't think it needs changing though.

**Comment by jrodewig** [comment]
Hi @y-vectorfield,

The `{es}` attribute expands to `Elasticsearch` in our final HTML output. We maintain a similar list of common and branded terms here:
https://github.com/elastic/docs/blob/master/shared/attributes.asciidoc#L88

We use attributes to stay [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) and consistent if we change a product name in the future. Updating the expanded term in a single place makes that much easier. It also reduces the likelihood of typos and misspellings.

**Comment by y-vectorfield** [comment]
Hello, @jrodewig ,
Thank you very much for your comments and useful information.

**Pull request closed without merging**
