### PR TITLE
Remove license_mode from Licensing codebase

### PR DESCRIPTION
**Pull request by jakelandis**
The license_mode / file configuration has never been used and 
represents a way to configure the license that is not compatible 
with future plans.  This commit removes the unused functionality.

---

My approach to this removal was to first delete the obvious parts and ensure it still compiles (https://github.com/elastic/elasticsearch/pull/93798/commits/1c866792ce7dd85c46c1daa84b4358d8e2b3c168) , then walk through the changes introduced in https://github.com/elastic/elasticsearch/commit/6a2d788e45a4d28a48833e4e3784700983dacce9 and manually remove anything missed (https://github.com/elastic/elasticsearch/pull/93798/commits/5bb7cb7dc8d23c8dd59b012c3ccd19175783a33a and https://github.com/elastic/elasticsearch/pull/93798/commits/14474179b400d5c6d95ed0379fb5a1a59af7ee17) and ensure the tests still pass.

### CODE REVIEW

**Comment by jakelandis** [comment]
@elasticsearchmachine update branch

(adding fips label to get CI to run fips tests just in case)

**Review by tvernum — APPROVED** [review]
LGTM.
But it might be worth getting a 👍 from someone in cloud.

**Comment by tvernum** [comment]
@AlexP-Elastic & @beiske  I know that you were involved when this "license_mode" file was introduced to ES.
Our understanding is that it was never something you relied on and we're good to remove it. Can you confirm?

**Comment by AlexP-Elastic** [comment]
I confirm Cloud does not in any way rely on or know about `license_mode`

**Pull request merged**
