### PR TITLE
updated log4j to version 2.13.2

### PR DESCRIPTION
**Pull request by tobias-trabelsi-sonarsource**
Hello there :wave: 

it looks like we have a common CVE justification for the DoD, so maybe we could update log4j to fix it. Looks like you already justified it [here](https://repo1.dsop.io/dsop/elastic/elasticsearch/elasticsearch/-/issues/4) but this might be a quick win :) 

Also there is [another PR](https://github.com/elastic/elasticsearch/pull/47298) that seems stale for ~ a year now that also wanted to update log4j.

We at SonarSource would prefer if this gets backported to the 7.x branch as well 

This would fix https://github.com/advisories/GHSA-vwqq-5vrc-xw9h as well as https://github.com/elastic/elasticsearch/issues/45523

### CODE REVIEW

**Comment by pgomulka** [comment]
ok to test

**Comment by pgomulka** [comment]
@tobias-trabelsi-sonarsource can you try running `./gradlew precommit` locallly and update the PR?
feel free to try with latest 2.14.0

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @pgomulka 
i tried again with `2.14.0` but got the same error as jenkins. i am not very familiar with the gradle plugin that you are using here and can not find any information about this specific error. can you give me some hints on where to look to make the tests pass? 

currently there is a bunch of forbidden APIs and one missing class: `javax.jms.Message`

**Comment by pgomulka** [comment]
@tobias-trabelsi-sonarsource you made the right changes, thank you. 
the CI is failing now because log4j is being configured before the security manager is being set.
log4j thinks it can use `getClassLoader` LoaderUtil:57 but in fact, we later set security manager to prevent that. hence the errors.
I will take a look into this..

**Comment by pgomulka** [comment]
this is what I found out so far about this failure. There is more failures like this, but the build failed early. (for instance ESJsonLayoutTests)
The test fails because we set the securityManager (ESTestCase:232) and then try to create log4j PatternLayout which in log4j 2.13.2 is using `getClassLoader`. That classloading log4j behaviour was introduced in https://issues.apache.org/jira/browse/LOG4J2-2779

This do not fail in production as we initialise our testing before security manager.

@rjernst do you think there is a workaround?

**Comment by rjernst** [comment]
I think this needs to be fixed upstream in log4j. There are a few problems in `LoaderUtil.getClassLoaders()`. First, it tries to check for the context classloader being aware of the security manager. But it determines whether a security manager exists statically when the class is initialized. Second, it tries to traverse the context classloader hierarchy, as well as get the system class loader, without accounting for security manager.

The only workaround would be patching the LoaderUtil class at build time, but we should try to fix this upstream before considering that as an interim solution.

**Comment by tobias-trabelsi-sonarsource** [comment]
Urgh this is a little bit out of my knowledge area. Will any of you look into the log4j codebase to propose the fix upstream? Should i leave this PR open until this is patched or should i close the PR?

**Comment by pgomulka** [comment]
@tobias-trabelsi-sonarsource I will try to raise a log4j issue and possibly work on a fix there.
I suspect if it will be released it would be latest version, so we would have to add substantially to this PR.
I suppose we can close this one in favour of https://github.com/elastic/elasticsearch/pull/47298
I will ping you once we make more progress

**Comment by tobias-trabelsi-sonarsource** [comment]
Okay then i will close this one for now. Good luck on your journey :)

**Pull request closed without merging**
