### PR TITLE
Make the rollover API respect the request's master_timeout

### LINKED ISSUE #81762: Rollover doesn't respect the timeouts configured in the rollover request
**Elasticsearch version** (`bin/elasticsearch --version`): 7.16 (earlier too), 8.0, 8.1

**Plugins installed**: []

**JVM version** (`java -version`):

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:
The rollover API doesn't respect that master timeout configured in the request. We document
that we support the `master_timeout` [here](https://www.elastic.co/guide/en/elasticsearch/reference/7.16/indices-rollover-index.html), however when submitting the rollover task we do not configure the timeout:
eg: 
https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/action/admin/indices/rollover/TransportRolloverAction.java#L60)

This could have the unwanted effect of having old `rollover` tasks processed by the master at a later point (with clients re-trying in the meantime). 
Note that this could end up with multiple rollovers as specifying the rollover `conditions` is optional.

### PR DESCRIPTION
**Pull request by joegallo**
Closes #81762.

Threads the RolloverRequest's masterNodeTimeout into the ClusterStateTaskConfig so rather than ignoring it.

### CODE REVIEW

**Review by dakrone — APPROVED** [review]
LGTM

**Review by andreidan — APPROVED** [review]
LGTM thanks for fixing this Joe

**Comment by joegallo** [comment]
Backported to 8.0, but 7.17 is still pending (might be another day).

**Comment by joegallo** [comment]
7.17 backport is a from-scratch PR -- https://github.com/elastic/elasticsearch/pull/82386.

**Pull request merged**
