### PR TITLE
Update jackson-databind to 2.8.11.4

### PR DESCRIPTION
**Pull request by racevedoo**
Upgrade to 2.8.11.4 for security reasons. From [jackson release notes](https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.8): 

image

### CODE REVIEW

**Comment by cbuescher** [comment]
Maybe related: https://github.com/elastic/elasticsearch/issues/45225

**Comment by davydotcom** [comment]
any update on this? This is holding up closing critical CVEs for highly secure environments

**Comment by davydotcom** [comment]
I was able to merge this into 7.4.2 tag branch and build myself and verify functionality works. I'd happily live with building my own non snapshot 7.4.2 with this fix but it wants a license key for xpack to do that

**Comment by jakelandis** [comment]
@elasticmachine test

**Comment by jakelandis** [comment]
@elasticmachine ok to test

**Comment by jakelandis** [comment]
@elasticmachine update branch

**Comment by jakelandis** [comment]
@racevedoo thanks for the PR. I updated the SHA hashes and will get this merged and backported. 

FWIW, it does not appear that Elasticsearch is susceptible to any of the CVEs referenced.

**Comment by davydotcom** [comment]
Yay Thanks. While it may not be susceptible, it still shows up on a scan for CAT 1 level security issues. This can cause immediate rejection even if the software is not vulnerable directly.

**Comment by ywelsch** [comment]
The backport PR seems to have been merged. I'm therefore removing the backport pending label here. Please shout if this is incorrect

**Pull request merged**
