### PR TITLE
Painless: Add whitelist extensions

### PR DESCRIPTION
**Pull request by rjernst**
This commit adds a PainlessExtension which may be plugged in via SPI to
add additional classes, methods and members to the painless whitelist on
a per context basis. An example plugin adding and using a whitelist is
also added.

### CODE REVIEW

**Comment by rjernst** [comment]
@debadair I'm really not sure where to link/mention this in the docs. The example plugin I've added here is the "source of truth" for this feature, so I don't really want to add any code to docs, but referencing the file and mentioning it is possible somewhere might be good. Can you suggest a place (or it could be done as a followup)?

**Review by jdconrad — APPROVED** [review]
LGTM.  We've worked closely enough on this together that any changes I would have requested have already been made.  Thanks for doing this!

**Comment by jdconrad** [comment]
@rjernst Looked into the failure - noting here.  We either need to move the resource files to the same package as Whitelist was moved to or we need to update the WHITELIST_FILES constant to point to the appropriate files.

**Comment by jdconrad** [comment]
I pushed a fix.

**Comment by jdconrad** [comment]
@elasticmachine Please test this.

**Comment by byoungb** [comment]
Any chance on allowing these newly whitelisted Painless extensions in aggregation scripts?
```
{
  "query": {
    "match_all": {}
  },
  "aggregations": {
    "statuses": {
      "terms": {
        "script": {
          "source": "def e = new ExampleWhitelistedClass(64, 42); return e.publicMember + e.privateMemberAccessor + ExampleWhitelistedClass.CONSTANT;",
          "lang": "painless"
        }
      }
    }
  }
}
```

**Comment by rjernst** [comment]
@byoungb 
Please ask questions on [our forum](https://discuss.elastic.co/c/elasticsearch). We use github for feature requests and confirmed bug reports. Commenting on a closed PR is a likely way to have your problem overlooked.

**Comment by byoungb** [comment]
I already had but thought it might fit here since this was where the code originated.
https://discuss.elastic.co/t/how-do-you-use-the-examplewhitelistextension-in-terms-aggregations/120551/2

**Pull request merged**
