### PR TITLE
Use external version type for history ops from Lucene

### PR DESCRIPTION
**Pull request by dnhatn**
Today we use version_type INTERNAL for the history operations from Lucene index. However, this does not cover the case in which the original operation has the version type EXTERNAL and version number 0.

### CODE REVIEW

**Comment by dnhatn** [comment]
We hit this assertion several times since using Lucene in peer-recovery.

```
Caused by: java.lang.AssertionError: invalid version for writes: 0
    at org.elasticsearch.index.translog.Translog$Index.<init>(Translog.java:1052) ~[elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
    at org.elasticsearch.index.translog.Translog$Index.<init>(Translog.java:1024) ~[elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
    at org.elasticsearch.index.translog.Translog$Operation.readOperation(Translog.java:978) ~[elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
    at org.elasticsearch.index.translog.Translog.readOperation(Translog.java:1484) ~[elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
    at org.elasticsearch.index.translog.Translog.readOperations(Translog.java:1461) ~[elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
```

CI: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+ccr+feature-branch-periodic/889/consoleText

**Comment by dnhatn** [comment]
@elasticmachine test this please

**Review by bleskes — COMMENTED** [review]
LGTM. All things coming from the translog should have the external version type and I think it makes sense to use external here. 

As follow up, and now that we use seq# to resolve out of order collision, I think we can remove the version type from the translog and lucene. The type of versioning is inherit to how you do indexing (and control the version). It's not relevant for storage. If you agree I'll add that to the road map.

**Review by bleskes — APPROVED** [review]

**Review by s1monw — APPROVED** [review]

**Comment by dnhatn** [comment]
Thanks @bleskes and @s1monw.

**Pull request merged**
