### PR TITLE
Change interval notation

### PR DESCRIPTION
**Pull request by wilder**

### CODE REVIEW

**Comment by nik9000** [comment]
This comes up every few months. This is intentional because 1 is not included in the range. This is written in [interval notation](https://en.wikipedia.org/wiki/Interval_(mathematics)#Including_or_excluding_endpoints). We keep closing the PRs to change this without merging.

The that fact that folks submit PRs for this every few months to "fix" the bracket implies to me that using interval notation at all is confusing. Maybe not to everyone, but to enough people that we should stop doing it.

**Comment by colings86** [comment]
Agreed, I think we should fix the places int he code that we use interval notation to instead talk about the range and inclusiveness of the bounds in words rather than in notation. @wilder would you mind changing this PR to this effect?

**Comment by wilder** [comment]
@colings86 No, I don't mind. I'm just not sure what would be the best way to do that. I'm familiar with the interval notation. I just didn't realize you were using it. 

Do you think you would still have the same problem if you used for example: ```interval [0,1[``` instead of ```range [0..1)```?

**Comment by colings86** [comment]
We have had similar issues with the `[0,1[` notation as well where users have mistaken the notation for a typo. 

Maybe we should be explicit and say something like `in the range from 0 (inclusive) to 1 (exclusive)`?

**Comment by mayya-sharipova** [comment]
@wilder  Would you still like to continue fixing this documentation?

**Comment by javanna** [comment]
@wilder as discussed above, we would welcome your contributions on this. Let us know if we can help in any way. For now I am closing this PR as it does not hold the changes that we would like to get merged. Please do open a new PR once you have time to get back to this.

**Comment by wilder** [comment]
Are you still willing to change the interval notation to something else? If so, may I make the changes on the code and documentation?

**Pull request closed without merging**
