### PR TITLE
Change Painless function node to use a block instead of raw statements

### PR DESCRIPTION
**Pull request by jdconrad**
This change improves the node structure of SFunction. SFunction now uses an SBlock instead of a List of AStatments reducing code duplication and gives a future target for symbol table scoping.

### CODE REVIEW

**Comment by jdconrad** [comment]
@elasticmachine elasticsearch-ci/default-distro

**Comment by jdconrad** [comment]
@elasticmachine run elasticsearch-ci/default-distro

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by jdconrad** [comment]
@rjernst Thanks for the review! Will commit as soon as CI passes.

**Pull request merged**
