### PR TITLE
Ensure clean thread context in `MasterService`

### PR DESCRIPTION
**Pull request by DaveCTurner**
`ThreadContext#stashContext` doesn't guarantee to give a clean thread
context, but it's important we don't allow the callers' thread contexts
to leak into the cluster state update. This commit captures the desired
thread context at startup rather than using `stashContext` when forking
the processor.

### CODE REVIEW

**Review by albertzaharovits — DISMISSED** [review]
LGTM

**Review by idegtiarenko — APPROVED** [review]

**Comment by DaveCTurner** [comment]
Thanks Ievgen!

**Comment by czjxy881** [comment]
In this PR #114512, clusterStateUpdateContext.restore() is introduced to ensure a clean thread context in MasterService. However, this causes the traceId to be lost.

Could you please advise:

Is there a recommended way to retain or propagate the traceId while ensuring a clean thread context?
During the execution of a master task, how can we reliably access the traceId for traceability purposes?
Any insights or suggestions on maintaining trace information in this context would be highly appreciated!

**Comment by DaveCTurner** [comment]
Thanks very much for your interest in Elasticsearch @czjxy881.

This appears to be a user question, and we'd like to direct these kinds of things to the [Elasticsearch forum](https://discuss.elastic.co/c/elasticsearch). If you can stop by there, we'd appreciate it. This allows us to use GitHub for verified bug reports, feature requests, and pull requests.

**Pull request merged**
