### PR TITLE
[Transform] Rename data frame plugin to transform: classes in xpack.core

### PR DESCRIPTION
**Pull request by hendrikmuhs**
rename classes in xpack.core of transform plugin from "data frame transform" to "transform"

### CODE REVIEW

**Review by droberts195 — APPROVED** [review]
LGTM

**Comment by hendrikmuhs** [comment]
run elasticsearch-ci/1
run elasticsearch-ci/bwc

**Comment by hendrikmuhs** [comment]
run elasticsearch-ci/1

**Comment by hendrikmuhs** [comment]
run elasticsearch-ci/bwc

**Pull request merged**
