### PR TITLE
ESQL: Load text field from parent keyword field

### LINKED ISSUE #102473: ESQL: Load non-stored text sub field
### Elasticsearch Version

main

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

whatever

### Problem Description

If you make a mapping like this:
```
"properties": {
  "foo": {
    "type": "keyword",
    "fields": {
      "text": { "type": "text" }
    }
  }
}
```

Then you can enable synthetic _source on it because the top level field is enough to store the value. But the sub-field will fail to load. In fact, ESQL will give up because it doesn't think it should be possible to get a text field in synthetic source mode without either storing the field or using a synthetic _source storage delegate. Well, in this case there is a delegate - but we don't find it.

### Steps to Reproduce

see above

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by nik9000**
This adds support for loading a text field from a parent keyword field. The mapping for that looks like:
```
"properties": {
  "foo": {
    "type": "keyword",
    "fields": {
      "text": { "type": "text" }
    }
  }
}
```

In this case it's safe to load the `text` subfield from the doc values for the `keyword` field above.

Closes #102473

### CODE REVIEW

**Review by dnhatn — APPROVED** [review]
I thought you would add a YAML test from the PR description as a showcase, but it's fine to merge this change without it. LGTM, thanks Nik!

**Comment by nik9000** [comment]
Ah! I should do that.

**Comment by nik9000** [comment]
run elasticsearch-ci/rest-compatibility

**Comment by nik9000** [comment]
@elasticmachine, test this please

**Comment by nik9000** [comment]
@elasticmachine test this please

**Pull request merged**
