### PR TITLE
Override jackson's TextBuffer to avoid NPE in SmileParser

### PR DESCRIPTION
**Pull request by v1ctor**
If you send a smile request with an empty value in the term query in ES 1.4.4, NPE may occur.
There is a bug in jackson https://github.com/FasterXML/jackson-core/issues/182.
But they haven't released it yet. 
That's why I proposed you to use a fixed version of this file until they release it.

Anyway you'd better know about this problem.

### CODE REVIEW

**Comment by masaruh** [comment]
FYI, there's an issue for this, #8629.

**Comment by s1monw** [comment]
I am kind of hesitating to do this. Not sure if it's worth adding a fork of this file or if we should just wait for a 2.6.0 release? @kimchy opinions?

**Comment by masaruh** [comment]
@s1monw Not mean to hijack this PR but I created a PR(#10333) to fix the issue in a different way in case overriding TextBuffer isn't feasible.

**Comment by kimchy** [comment]
agreed its tricky, and I think this should be solved in Jackson and for now we can do #10333

**Comment by masaruh** [comment]
Closing in favor of #10333.

**Pull request closed without merging**
