### PR TITLE
[DOCS] Clean up 8.0 deprecations

### PR DESCRIPTION
**Pull request by jrodewig**
* Removes a duplicate breaking change/deprecation for `indices.query.bool.max_clause_count`.

* Relocates the `index.merge.policy.max_merge_at_once_explicit` deprecation content to a breaking changes section.

* Adds remediation steps for removing the settings. While they no longer have an effect, specifying these settings will issue a deprecation warning.

Relates to https://github.com/elastic/elasticsearch/pull/83412

### Preview
https://elasticsearch_83548.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/migrating-8.0.html#breaking_80_cluster_node_setting_changes

### CODE REVIEW

**Review by kirakoki — APPROVED** [review]

**Review by romseygeek — APPROVED** [review]
LGTM

**Review by dnhatn — APPROVED** [review]
LGTM. Thanks James!

**Comment by jrodewig** [comment]
Thanks @dnhatn and @romseygeek!

**Comment by jrodewig** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.1|[](https://github.com/elastic/elasticsearch/pull/83611)|
|✅|8.0|[](https://github.com/elastic/elasticsearch/pull/83612)|


### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
