### PR TITLE
ESQL: Enable grok and dissect tests with stats

### PR DESCRIPTION
**Pull request by luigidellaquila**
These tests were disabled recently because STATS command did not release blocks correctly.
Now the problem is fixed, so we can enable them again

### CODE REVIEW

**Comment by luigidellaquila** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Review by alex-spies — APPROVED** [review]
LGTM

**Comment by luigidellaquila** [comment]
@elasticmachine update branch

**Review by nik9000 — COMMENTED** [review]
Awesome!

**Pull request merged**
