### PR TITLE
Add type hint for LicenseOverrides

### PR DESCRIPTION
**Pull request by arteam**
Type inference tends to be quite slow on vararg methods with a big amount of arguments.  Compiling `LicenseOverrides` on my machine without the type token takes:
`[INFO] Total time:  2.426 s`
With type token:
`[INFO] Total time:  1.341 s`

See https://bugs.openjdk.java.net/browse/JDK-8221301

### CODE REVIEW

**Comment by arteam** [comment]
@elasticmachine update branch

**Comment by arteam** [comment]
@elasticmachine update branch

**Review by grcevski — APPROVED** [review]
LGTM!

**Comment by arteam** [comment]
Thanks Nikola!

**Pull request merged**
