### PR TITLE
22rd → 22nd typo fix

### PR DESCRIPTION
**Pull request by Cladis**

### CODE REVIEW

**Comment by Cladis** [comment]
It seems it is the other way round.

**Comment by Cladis** [comment]
Ok, now that I've read to what /d is, it seems it is 22nd indeed.

**Comment by nik9000** [comment]
@Cladis can you open these against a modern release of the docs like 6.2? A lot of these things have been fixed already but not backported all the way to 5.0. This is one of the problems with having branches for our docs versions: typos don't get fixed too far back.

**Comment by karmi** [comment]
Hi @Cladis, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/elasticsearch/pull/28566.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by javanna** [comment]
hi @Cladis as Nik mentioned above, we would be happy to merge your PR but we can't do so with this one as it was sent against an old branch that no longer receives updates. Please send your change against master and we will happily merge it.

**Pull request closed without merging**
