### PR TITLE
Upgrade Centos version in Dockerfile to 8

### PR DESCRIPTION
**Pull request by stevengoossensB**

### CODE REVIEW

**Comment by ebadyano** [comment]
Related to https://github.com/elastic/elasticsearch/issues/51481

**Comment by ebadyano** [comment]
@elasticmachine test this please

**Comment by pugnascotia** [comment]
@elasticmachine update branch

**Comment by pugnascotia** [comment]
@elasticmachine test this please

**Comment by pugnascotia** [comment]
@elasticmachine update branch
@elasticmachine ok to test

**Comment by pugnascotia** [comment]
@elasticmachine run elasticsearch-ci/packaging-windows

**Comment by pugnascotia** [comment]
Thanks @stevengoossensB!

**Comment by stevengoossensB** [comment]
No thanks :) Any idea when the official (published) docker image will also run CentOS 8 so I can return back and follow your releases and be compliant with out internal vulnerability management policies?

**Comment by pugnascotia** [comment]
It'll go out with `v7.10.0`.

**Pull request merged**
