### PR TITLE
Fail with a better error when providing null as processor config.

### PR DESCRIPTION
**Pull request by gaobinlong**
Relates to #57793.

When executing PUT pipeline API, if the config of one processor is `null`, then NPE is throwed. This PR fix the NPE and add a test for the change.

### CODE REVIEW

**Review by martijnvg — COMMENTED** [review]
If this pr should protect against npe from config like this:

```
{
  "description": "describe pipeline",
  "processors": [
    {
      "set": null
    }
  ]
}
```

Then a better would be change the `readProcessorConfigs(...)` method to fail with a descriptive error  if `entry.getValue()` is `null`. Maybe something like `null` processor config is not allowed.

**Comment by gaobinlong** [comment]
@martijnvg, I have done that , can you take a look at the code change?

**Comment by martijnvg** [comment]
Thanks @gaobinlong, that looks good to me.

**Comment by martijnvg** [comment]
@elasticmachine test this please

**Pull request merged**
