### PR TITLE
Remove the migrate tool

### PR DESCRIPTION
**Pull request by rjernst**
This commit removes the deprecated migrate tool which was used to
migrate users from the file realm to native realm when the native realm
was first created.

### CODE REVIEW

**Review by jaymode — APPROVED** [review]
LGTM

**Comment by rjernst** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample

**Review by tvernum — APPROVED** [review]
👍

**Comment by rjernst** [comment]
@elasticmachine run elasticsearch-ci/1

**Pull request merged**
