### PR TITLE
Allow to configure analyzers on keyword fields.

### PR DESCRIPTION
**Pull request by jpountz**
This commit allows an analyzer to be configured on a keyword field. The analyzer
must generate exactly one token for any input string. This is not something that
can be checked easily so the approach I used is to run the analyzer on a couple
test inputs and check that it generates one token as expected.

One expected use-case for this feature is to normalize case, so for ease of use
I made `lowercase` a built-in analyzer which puts a lowercase filter on top of
a keyword tokenizer.

### CODE REVIEW

**Comment by dakrone** [comment]
> The analyzer must generate exactly one token for any input string.

Out of curiosity, what will happen if it generates more than one token? I can easily think of analyzers where the test inputs will be a single token but indexing real docs will provide multiple tokens. Are we going to hard fail documents that do that? Truncate them to the first term?

**Comment by jpountz** [comment]
If that happens, the document will be rejected, similarly to what would happen if you provide a string value for a numeric field. I agree the current validation of analyzers is a bit of a hack.

**Comment by dakrone** [comment]
If the document will be rejected, do we need to pre-test the analyzer with the test inputs? Is that intended to give feedback at the mapping field creation time?

**Comment by jpountz** [comment]
I think it is still useful: given that mappings are append-only (you cannot remove fields) this gives you an error before the field is added to the mapping, so that you have an opportunity to fix the field definition. If we only checked at indexing time, then you could easily create fields that cannot be used and the only way to get rid of them would be to regenerate the whole index.

**Comment by dakrone** [comment]
> I think it is still useful: given that mappings are append-only (you cannot remove fields) this gives you an error before the field is added to the mapping, so that you have an opportunity to fix the field definition.

That makes sense.

How hard would it be to "blacklist" certain token filters from the `keyword` type? I'm thinking we could just blacklist things where the test wouldn't catch it, like decompounders

**Comment by jpountz** [comment]
I think the main issue if we want to implement such a black list is that analyzers do not expose the components that they are made of.

**Comment by jpountz** [comment]
If we want to start totally safe, one option would be to only accept a finite state of predefined analyzers, eg. only `keyword` and `lowercase`.

**Comment by dakrone** [comment]
Personally, I'd rather start strict and (if deemed necesarry) go lenient later (or never), so I vote for a pre-defined number of analyzers (keyword and lowercase, as you said).

**Comment by dakrone** [comment]
It's way harder to remove leniency than it is to add it at a later time.

**Comment by jpountz** [comment]
@rmuir just sent me a note that Lucene has the `MultiTermAwareComponent` marker interface that we could leverage here, but unfortunately elasticsearch does not use the lucene factories, it has its own. So I think starting with a very limited set of supported analyzers makes sense and later we can look into hooking onto this `MultiTermAwareComponent` if it makes sense.

**Comment by dakrone** [comment]
+1, that sounds great!

**Comment by rmuir** [comment]
We can always test things are not out of sync by iterating the list in AnalysisFactoryTests and asserting our list is in sync with ones matching that interface?

This same list could be used to automatically apply a subset of the TokenFilters/CharFilters for "wildcard" etc terms. Basically the subset that won't screw everything up. And then parameters like lowerCaseWildCards can go away.

https://github.com/elastic/elasticsearch/blob/master/core/src/test/java/org/elasticsearch/index/analysis/AnalysisFactoryTests.java#L36

**Comment by jpountz** [comment]
Closing, I will revisit it with the approach that is discussed above.

**Pull request closed without merging**
