### PR TITLE
Enforce no-op setWeight on collectors that filter docs out

### PR DESCRIPTION
**Pull request by javanna**
MinimumScoreCollector and FilteredCollector filter documents out as part of their collection. The have an inner collector to delegate to, but they should never propagate the Weight to them otherwise the total hit count may not reflect the filtering. This commit clarifies this through an empty final setWeight method on both collectors and additional javadocs.

### CODE REVIEW

**Comment by javanna** [comment]
run elasticsearch-ci/bwc

**Review by dnhatn — APPROVED** [review]
LGTM.

**Comment by javanna** [comment]
These collectors did not have any existing unit tests, so I added simple ones where we can now also test that weight does not get propagated. This way we catch it if it ever happens. There is already a more end-to-end test for this in QueryPhaseTests but these are more specific to the individual collectors.

**Comment by javanna** [comment]
run elasticsearch-ci/bwc

**Pull request merged**
