### PR TITLE
Replace org.elasticsearch.common.lucene.search.MatchNoDocsQuery with its Lucene version (org.apache.lucene.search.MatchNoDocsQuery)

### PR DESCRIPTION
**Pull request by jimczi**
Now that MatchNoDocsQuery has landed in Lucene we can safely replace our forked (org.elasticsearch.common.lucene.search.MatchNoDocsQuery) with the original Lucene query. 

relates #18030

### CODE REVIEW

**Comment by nik9000** [comment]
@jimferenczi can you add an explanation to the PR about why we can do the replacement now? I suspect we've upgraded to the version of Lucene that has the fix the we forked to get?

**Comment by jimferenczi** [comment]
@nik9000 I've updated the description on why we can do the replacement.

**Review by jpountz — APPROVED** [review]
LGTM

**Comment by jimferenczi** [comment]
Thanks @jpountz !

**Pull request merged**
