### PR TITLE
Migrate `cat` YAML tests from version to cluster_features

### PR DESCRIPTION
**Pull request by ldematte**
This PR starts the effort of moving version-based checks in YAML tests to cluster_features-based checks.

It also introduces a separate `FeatureSpecification` for YAML tests (`YamlTestLegacyFeatures`), to avoid dumping all legacy features in a single `FeatureSpecification`. 
I'm not 100% convinced an additional parameter to `createTestFeatureService` is the right thing to do; I think providing a separate protected method to override in derived classes, e.g. `createAdditionalFeatureSpecifications()`, and call it from `createTestFeatureService` is a better design, but I did not want to over-engineer. Thoughts?

### CODE REVIEW

**Comment by thecoop** [comment]
I think having a protected method that is overridden is more like the other implementations in `ESRestTestCase` (see the many boolean-returning methods)

**Comment by ldematte** [comment]
Yeah, I did not like this at all, already changing it 👍

**Review by thecoop — APPROVED** [review]

**Comment by ldematte** [comment]
Thanks Simon!

**Comment by ldematte** [comment]
BwC tests pass, removing the tag to minimize CI time and cost

**Comment by ldematte** [comment]
@elasticmachine update branch

**Pull request merged**
