### PR TITLE
Remove Dead MinVersion Parameter in SearchService

### PR DESCRIPTION
**Pull request by original-brownbear**
Just a random simplification I found while researching other things: 
This parameter isn't used anymore -> removed it.

### CODE REVIEW

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/packaging-sample

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/packaging-sample

**Review by cbuescher — APPROVED** [review]
Looks indeed unused on master to me, not sure about the backport though. It seems the version is still used there for a bwc switch in `SliceBuilder#toFilter()` (version>=6.4) which could happen in mixed 6.x/7.x clusters on upgrade. Let me know what you think, changes on master LGTM.

**Comment by original-brownbear** [comment]
Thanks @cbuescher ! My bad with the `7.5.0` label that was just a case of instinctively labeling :) -> only merging to `master`

**Pull request merged**
