### PR TITLE
[ML] Rename evaluation metric result fields to value

### PR DESCRIPTION
**Pull request by dimitris-athanasiou**
Renames data frame analytics _evaluate API results as follows:

  - per class accuracy renamed from `accuracy` to `value`
  - per class precision renamed from `precision` to `value`
  - per class recall renamed from `recall` to `value`
  - auc_roc `score` renamed to `value` for both outlier detection and classification

### CODE REVIEW

**Review by benwtrent — APPROVED** [review]

**Comment by benwtrent** [comment]
Looks like you need to update all the yaml tests :).

**Comment by dimitris-athanasiou** [comment]
@benwtrent Ah, I forgot those. Will do.

**Comment by dimitris-athanasiou** [comment]
@elasticmachine update branch

**Comment by dimitris-athanasiou** [comment]
@wwang500 @alvarezmelissa87 Hi! This PR is renaming some fields in the response of the evaluate API. Could you take a look and let me know when it'd be ok for me to merge it?

**Comment by wwang500** [comment]
> @wwang500 @alvarezmelissa87 Hi! This PR is renaming some fields in the response of the evaluate API. Could you take a look and let me know when it'd be ok for me to merge it?

thanks for the heads-up. feel free to merge it.

**Comment by alvarezmelissa87** [comment]
@dimitris-athanasiou - thanks for letting us know! Okay to go ahead and merge it 👌

**Pull request merged**
