### PR TITLE
Remove the changelog

### PR DESCRIPTION
**Pull request by jasontedor**
We are starting over on the changelog with a different approach. This commit removes the existing incarnation of the changelog to remove confusion that we need to continue adding entries to it.

### CODE REVIEW

**Comment by rjernst** [comment]
LGTM

**Review by pcsanwald — APPROVED** [review]
goodbye, changelog. we hardly knew ye.

**Comment by lcawl** [comment]
It needs to be removed from the table of contents too.  I'll open a new PR to fix the build.

**Comment by javanna** [comment]
@lcawl I have done this: https://github.com/elastic/docs/commit/89be326423f6daea5d98e08490c1b0b836e7afc3 not sure it's what you mean.

**Comment by lcawl** [comment]
The doc build failure was related to the reference to the changelog in the table of contents in 6.2 branches.  I'll check earlier releases too.  I'll also put the changelog content back into the release-notes folder, since I don't think we want to lose that old info.
FYI the commits were elastic/elasticsearch@a74f4ff542c5ce210ba8d5910bdceb4efaa33764 and elastic/x-pack-elasticsearch@495907c6df24fd690650812f39fc1fb3f123552a

**Comment by lcawl** [comment]
I've moved the old changelog content into a file in the release-notes folder to address the doc build errors and broken links for now.  When we decide where/if we'll use the changelog content in the docs in the future, we can revisit/remove the release notes.   Here are the commits:

elastic/elasticsearch:
master: commit c0d639e2778a076e22a88b02028d7fb64bc915eb 
6.x: commit 7f1a15b3aab94f6a52cb9e6ed0fb38d64da4cadd 
6.3: commit 60f2dba1de131ed95803c9de5914dde8faa250c1 
6.2: commit 0cb7b544c37a437ed5f064f9c34e73eadc8cf146

**Pull request merged**
