### PR TITLE
Move DataTierFieldMapper from x-pack/core to server

### PR DESCRIPTION
**Pull request by andreidan**
This moves the `_tier` field mapper to `server` so it can be 
available for server-specific operations (like coordinator rewrites)

This is a pre-requisite for https://github.com/elastic/elasticsearch/pull/114990

### CODE REVIEW

**Review by martijnvg — COMMENTED** [review]
LGTM from my side.

**Comment by andreidan** [comment]
@mark-vieira any concerns about making the `_tier` field available in `server` from a distribution perspective?

**Comment by mark-vieira** [comment]
> @mark-vieira any concerns about making the `_tier` field available in `server` from a distribution perspective?

I don't have much insight into whether this would be a problem but this would now be licensed under the SSPL and AGPL licenses, making it "open source". It's not a problem unless we have a specific reason for this to be solely licensed under the ElasticV2 license.

**Comment by rjernst** [comment]
Unrelated to any licensing concerns, this should still exist in a module, even if moved from xpack. Server needs to have less concrete mappings, not more.

**Comment by andreidan** [comment]
Closing this for now.

**Pull request closed without merging**
