### PR TITLE
Suggest git commands for tracking down transport versions

### PR DESCRIPTION
**Pull request by DaveCTurner**
Adds a few examples of git commands that might be useful if trying to
work out which transport versions correspond to which release versions.

### CODE REVIEW

**Comment by thecoop** [comment]
I get errors running these commands:

`fatal: invalid object name 'v8.9.1'`
`fatal: bad revision '8.9..main'`

**Comment by DaveCTurner** [comment]
That indicates that your local development environment is not set up as per [the team docs](https://docs.elastic.dev/elasticsearch-team/onboarding/development-process) - in particular you don't have local branches tracking all the upstream ones and you are missing upstream tags too.

**Comment by thecoop** [comment]
Ah yes, that's it. Could we also have these comments on `IndexVersion`, now that works the same way?

**Comment by DaveCTurner** [comment]
Not quite yet, there's no history to query so the example commands won't actually work yet. I added a TODO in d4ca30660d2 at least.

**Review by thecoop — APPROVED** [review]

**Comment by DaveCTurner** [comment]
@elasticmachine please run elasticsearch-ci/packaging-tests-unix-sample
@elasticmachine please run elasticsearch-ci/packaging-tests-windows-sample

**Pull request merged**
