### PR TITLE
Bad ref to 'node_id' parameter in Task Mgt doc

### PR DESCRIPTION
**Pull request by jpmat296**
Here in documentation:
https://www.elastic.co/guide/en/elasticsearch/reference/8.4/tasks.html#tasks-api-query-params

Name of parameter to filter node is `nodes`.

### CODE REVIEW

**Comment by jpmat296** [comment]
I've update source branch of this PR. I had forgotten `git add` on a file. It's good now.

**Review by abdonpijpelink — CHANGES_REQUESTED** [review]
@jpmat296 Thanks for contributing to the Elasticsearch documentation! However, this change does not look correct to me. The result would be that the parameter is listed as `<node_id>`, while it should be `nodes`.

I think we should keep the original tag section, but change `node_id` into `nodes` instead.

**Comment by abdonpijpelink** [comment]
@jpmat296 are you interested in continuing to work on this PR? Otherwise I can take it from here.

**Comment by jpmat296** [comment]
Yes please take it. I'm not comfortable at all with the documentation build system. Thanks a lot !

**Comment by abdonpijpelink** [comment]
@elasticmachine test this please

**Review by abdonpijpelink — APPROVED** [review]

**Pull request merged**
