### PR TITLE
Format build-tools and build-tools-internal

### PR DESCRIPTION
**Pull request by pugnascotia**
Our spotless configuration wasn't being applied to `build-tools` and `build-tools-internal`. Move the Spotless configuration to a Java plugin in `build-conventions`, and apply it everywhere.

This resulted in a lot more Java files being subject to formatting, so I added more exclusions to the list.

Also remove the `paddedCell` stuff, we've never needed it.

### CODE REVIEW

**Review by mark-vieira — CHANGES_REQUESTED** [review]

**Comment by pugnascotia** [comment]
@mark-vieira @breskeby this PR is now configuring formatter via a `build-conventions` plugin. PTAL.

**Review by breskeby — CHANGES_REQUESTED** [review]
just a minor request to handle precommit wiring better that I'd really would like to have instead of that hack. otherwise looks good to me. thanks for taking care of this

**Review by breskeby — APPROVED** [review]
Nice!

**Comment by pugnascotia** [comment]
Backported to `7.x` in 562440a950c.

**Pull request merged**
