### PR TITLE
[8.0] fix: backward compatibility with version 8.0.0 (#83509)

### PR DESCRIPTION
**Pull request by salvatore-campagna**
Backports the following commits to 8.0:
 - fix: backward compatibility with version 8.0.0 (#83509)

### CODE REVIEW

**Comment by salvatore-campagna** [comment]
@elasticsearchmachine test this please

**Comment by salvatore-campagna** [comment]
This is to address #83904 and #83822.

**Comment by salvatore-campagna** [comment]
@elasticsearchmachine run elasticsearch-ci/full-bwc

**Comment by salvatore-campagna** [comment]
@elasticsearchmachine test this please

**Comment by salvatore-campagna** [comment]
@elasticsearchmachine run elasticsearch-ci/full-bwc

**Comment by salvatore-campagna** [comment]
@elasticsearchmachine update branch

**Comment by salvatore-campagna** [comment]
@elasticsearchmachine run elasticsearch-ci/full-bwc

**Comment by salvatore-campagna** [comment]
@elasticmachine run elasticsearch-ci/full-bwc

**Comment by salvatore-campagna** [comment]
@elasticsearchmachine run elasticsearch-ci/full-bwc

**Comment by salvatore-campagna** [comment]
@elasticsearchmachine run elasticsearch-ci/full-bwc

**Comment by salvatore-campagna** [comment]
@elasticsearchmachine update branch

**Comment by salvatore-campagna** [comment]
I need to wait for #83876 before being able to merge this. The full-bwc test is failing because of some issues fixed by that PR.

**Comment by salvatore-campagna** [comment]
@elasticsearchmachine update branch

**Comment by mark-vieira** [comment]
Backports of https://github.com/elastic/elasticsearch/pull/83876 have been complteted.

**Comment by salvatore-campagna** [comment]
@elasticsearchmachine update branch

**Comment by salvatore-campagna** [comment]
@elasticsearchmachine update branch

**Pull request merged**
