### PR TITLE
Add several context examples for Painless date documentation

### PR DESCRIPTION
**Pull request by jdconrad**
Add steps to load data and execute several new date examples.

### CODE REVIEW

**Comment by jdconrad** [comment]
@elasticmachine run elasticsearch/ci-1

**Comment by jdconrad** [comment]
@elasticmachine elasticsearch-ci/1

**Comment by jdconrad** [comment]
@elasticmachine run elasticsearch-ci/1

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by jdconrad** [comment]
@rjernst Thanks for the review!

**Pull request merged**
