### PR TITLE
Async status response should set is_partial that same way that async response does

### PR DESCRIPTION
**Pull request by quux00**
This bug rarely manifests, since the correct value of is_partial gets written to the .async-search index.
To reproduce it, I had to set `keep_on_completion=false`, having a partial failure in one cluster (say one shard
failed) and hit the `GET _async_search/status/<id>` endpoint several times to get just the right moment of
time when the search is done but the final result has not yet been written to the .async-search index.

So there are no new tests for this change. Because this is so rare it is unlikely to negative
affect any existing parsing logic. But being a bug we should fix it even if it would.

### CODE REVIEW

**Review by piergm — APPROVED** [review]
LGTM!

**Review by javanna — COMMENTED** [review]
Is this a thing that needs an additional test?

**Comment by quux00** [comment]
> Is this a thing that needs an additional test?

See my comment on the PR (description area). This is extremely difficult bug to uncover. I don't know of a way to automate testing of it and make the test dependable.

**Comment by javanna** [comment]
> See my comment on the PR (description area). This is extremely difficult bug to uncover. I don't know of a way to automate testing of it and make the test dependable.

Do we need unit tests for MutableSearchResponse perhaps for this type of internal behaviour instead of relying on more complex integration alike tests?

**Pull request merged**
