### PR TITLE
Avoid unnecessary eager creation of Gradle tasks

### PR DESCRIPTION
**Pull request by mark-vieira**
This PR makes a number of fixes and optimizations to our build to help avoid eager creation of tasks. Gradle supports [lazy task creation](https://docs.gradle.org/current/userguide/task_configuration_avoidance.html) in such that it will not actually instantiate tasks that are not needed or part of the task execution graph. Since task creation is quite expensive, and our build defines over 17,000 tasks, it's a significant configuration time penalty to eagerly realize all our tasks.

This PR is just a first stab at this, reducing the number of eagerly realized tasks for a `gradle help` build by just over 10,000. We can do better, but it will involve some more considerable refactoring and effort.

### CODE REVIEW

**Comment by mark-vieira** [comment]
@elasticmachine run elasticsearch-ci/1

**Review by rjernst — APPROVED** [review]
Awesome reduction! LGTM

**Review by alpar-t — APPROVED** [review]
LGTM

**Comment by mark-vieira** [comment]
@elasticmachine update branch

**Comment by mark-vieira** [comment]
@elasticmachine run elasticsearch-ci/1

**Pull request merged**
