### PR TITLE
Read the index.number_of_replicas from template so that wait_for_active_shards is interpreted correctly

### PR DESCRIPTION
**Pull request by tninokehoe**
Setting `wait_for_active_shards` to a value larger than 1 causes the operation to fail.
```
cat template_single_shard_single_replica.json
{
   "index_patterns":[
      "test_*"
   ],
   "settings":{
      "index.number_of_shards":"1",
      "index.number_of_replicas":"1",
      "index.write.wait_for_active_shards":"2"
   }
}
```
```
curl -H'content-type:application/json' -u elastic:password -XPUT 'http://localhost:9200/_template/t2' -d@template_single_shard_single_replica.json

{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"invalid index.write.wait_for_active_shards[2]: cannot be greater than number of shard copies [1]"}],"type":"illegal_argument_exception","reason":"invalid index.write.wait_for_active_shards[2]: cannot be greater than number of shard copies [1]"},"status":400}
```
Proposed change: Read the number of replica shards from the template object:
```
curl -H'content-type:application/json' -u elastic:password -XPUT 'http://localhost:9200/_template/t2' -d@template_single_shard_single_replica.json

{"acknowledged":true}%
curl -H'content-type:application/json' -u elastic:password -XPUT 'http://localhost:9200/test_wait_for_active_shards'
{"acknowledged":true,"shards_acknowledged":false,"index":"test_wait_for_active_shards"}%

curl -s -u elastic:password -XGET 'http://localhost:9200/test_wait_for_active_shards/_settings' | jq .

{
  "test_wait_for_active_shards": {
    "settings": {
      "index": {
        "number_of_shards": "1",
        "provided_name": "test_wait_for_active_shards",
        "creation_date": "1585174159914",
        "number_of_replicas": "1",
        "uuid": "hQmbmbm2S0aIogT-TOdKaw",
        "version": {
          "created": "8000099"
        },
        "write": {
          "wait_for_active_shards": "2"
        }
      }
    }
  }
}
```

This set of changes reads the index.number_of_replicas value from the template body (defaults to 0 - no replicas- )value when setting an index template. This enables the index.wait_for_active_shards value to be interpreted correctly

*read number of replicas from template
*added tests to validate with default and specified replicas
*rename replicas variable

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by jasontedor** [comment]
Yeah, that's a bug. Nice catch, and the production code change looks good. I will leave this someone on @elastic/es-core-features to go over the details and work with you to get this integrated.

**Comment by andreidan** [comment]
@elasticmachine ok to test

**Comment by andreidan** [comment]
@elasticmachine update branch

**Comment by andreidan** [comment]
Thanks for fixing this @tninokehoe Great catch. 

Can you please merge the latest master into your branch? We should be getting all our checks green and be able to merge this.

**Comment by tninokehoe** [comment]
Thanks @andreidan. Feels great to contribute, looking forward to the next one.

**Pull request merged**
