### PR TITLE
SNAPSHOTS: Allow Parallel Restore Operations (#36397)

### PR DESCRIPTION
**Pull request by original-brownbear**
* Enable parallel restore operations
* Add uuid to restore in progress entries to uniquely identify them
* Adjust restore in progress entries to be a map in cluster state
* Added tests for:
   * Parallel restore from two different snapshots
   * Parallel restore from a single snapshot to different indices to test uuid identifiers are correctly used by `RestoreService` and routing allocator
   * Parallel restore with waiting for completion to test transport actions correctly use uuid identifiers

### CODE REVIEW

**Comment by original-brownbear** [comment]
@elasticmachine run gradle build tests 1 please

**Comment by original-brownbear** [comment]
@elasticmachine run gradle build tests 1 please

**Comment by original-brownbear** [comment]
@elasticmachine run gradle build tests 1 please

**Comment by DaveCTurner** [comment]
This is a backport of #36397 - the number is in the title but you can't click on it there :)

**Pull request merged**
