### PR TITLE
return Cancellable in RestHighLevelClient

### PR DESCRIPTION
**Pull request by jillesvangurp**
Addresses #44802 

Makes all the async methods in the high level client return the cancellable object that the low level client now exposes.

### CODE REVIEW

**Comment by javanna** [comment]
heya @jillesvangurp thanks for working on this change! I think that to make sure that we don't miss any method, now and in the future, we could enhance RestHighLevelClientTests , where we already have some convention tests, and check that every method that has async in its name also returns a `Cancellable`.  Given that #45379 has not been backported yet, and we will backport it only when the fix for https://issues.apache.org/jira/browse/HTTPASYNC-152 is released, we can still merge this PR to master in the meantime and delay only backporting it.

**Comment by jillesvangurp** [comment]
@javanna already did this on Saturday; that's how I found all the missing endpoints.

**Comment by javanna** [comment]
nice @jillesvangurp sorry I did not notice! Let me run tests and properly review this ;)

**Comment by javanna** [comment]
test this please

**Comment by javanna** [comment]
retest this please

**Comment by jillesvangurp** [comment]
I reran the test. It seems the snapshot client gained a new method since saturday. Also merged master again

**Comment by jillesvangurp** [comment]
@javanna it seems github is not updating the pr with the commits I added on my branch?! Maybe because you pushed a merge commit. Can you pull the new commits from rhl-cancellable-async-calls branch on jillesvangurp/elasticsearch?

**Comment by jillesvangurp** [comment]
Never mind seems to be a UI bug on github. It updated after I switched to a different PR and back.

**Comment by javanna** [comment]
thank you @jillesvangurp , there is some delay between a push and when you see the commits in the UI today, somehow. Not sure why :)

**Comment by javanna** [comment]
retest this please

**Comment by jillesvangurp** [comment]
Again? I see no changes since the last time I ran the tests.

**Comment by javanna** [comment]
Sorry that's a message to our bot :) I need a green build here to be able to merge the PR, that's all

**Comment by jillesvangurp** [comment]
Ah got it :-). Yay chatops.

**Comment by javanna** [comment]
run elasticsearch-ci/1

**Comment by javanna** [comment]
run elasticsearch-ci/bwc

**Comment by javanna** [comment]
run elasticsearch-ci/default-distro

**Comment by javanna** [comment]
run elasticsearch-ci/docs

**Review by javanna — APPROVED** [review]
LGTM thanks a lot @jillesvangurp ! Would you mind opening a follow-up docs PR where we add a note to the high-level client docs saying that all the async methods return a `cancellable` and what to do with it?

**Pull request merged**
