### PR TITLE
Fix a grammatical error in the 'search type' documentation.

### PR DESCRIPTION
**Pull request by fernando-mc**
Simple grammatical fix to documentation.

Edit - Just signed the CLA a few min before submitting this. That's probably why the check is failing?

### CODE REVIEW

**Comment by jtibshirani** [comment]
Thank you @fernando-mc for the fix. It looks like the CLA check is now green -- I'll kick off a build and merge when everything passes.

**Comment by jtibshirani** [comment]
test this please

**Comment by fernando-mc** [comment]
Thanks @jtibshirani, no rush.

I'm reading through all the docs this week so I probably should have waited to include anything else I found. Might do another PR later this week. Thanks for the great product, the docs are pretty great!

**Comment by jtibshirani** [comment]
Would you be able to rebase once more against master and re-push your changes? Our build was temporarily broken yesterday and I think you need to pull in a fix for this PR to go green. And great, looking forward to more fixes :)

**Review by Sue-Gallagher — APPROVED** [review]
LGTM

**Comment by fernando-mc** [comment]
@jtibshirani Done. Let me know if this works for you!

**Comment by jtibshirani** [comment]
test this please

**Comment by jtibshirani** [comment]
test this please

**Pull request merged**
