### PR TITLE
Prevent long value saturation within scaled_float mappings

### LINKED ISSUE #105361: scale_float does not honor limits for long values
### Elasticsearch Version

7.17 / 8.x

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

N/A

### Problem Description

When using `scaled_float`, there is no range check on the value and scaling factor to be outside the `long` value range.

According to [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/number.html) for `scaled_float`:

> scaled_float - A floating point number that is backed by a long, scaled by a fixed double scaling factor

However, that assumption is not checked on document ingestion. The following mapping:

"properties": {
  "a_scaled_float": {
    "scaling_factor": 1000000,
    "type": "scaled_float"
  }
There's a scaled_float mapping configuration with value 1000000.
So, why did the number 1707339753294418 become 9223372036854.775? Shouldn't it be 1707339753294418000000?

{
  "_index": "test-index",
  "_id": "Z5t_iY0BLRoRMvLbP6e3",
  "_score": 1,
  "_source": {
    "a_scaled_float": 1707339753294418
  },
  "fields": {
    "a_scaled_float": [
      9223372036854.775
    ]
  }
}

This is due to the rounding up done [here](https://github.com/elastic/elasticsearch/blob/17bc83f481ddcfc032f6743a7a64c64000d55740/modules/mapper-extras/src/main/java/org/elasticsearch/index/mapper/extras/ScaledFloatFieldMapper.java#L388), which produces a `long` value which is outside range, and thus returns `MAX_LONG`.

As this provides an incorrect result, and the value is outside of the `long` range, the correct behaviour should be to error on the value as other numeric types do.

### Steps to Reproduce

Set a mapping with properties:

```json
PUT test-index
{
      "mappings": {
        "properties": {
            "scaled_float": {
              "type": "scaled_float",
              "scaling_factor": 1000000
            }
        }
      }
}
```

Ingest a document:

```json
PUT test-index/_doc/1
{
  "scaled_float": 1707339753294418
}
```

This should return an error, as the number is outside the `long` range.

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by benwtrent**
It is easy to have long value saturation and overflow with `scaled_float` and allowing users to  saturate longs seems dangerous and confusing.

I would generally expect any saturation to be an input error by the user as it will then break subsequent queries against the field (see example range query in the issue).

This commit allows saturation to occur if the index was created in a previous version or if `ignore_malformed: true`. 

closes: https://github.com/elastic/elasticsearch/issues/105361

### CODE REVIEW

**Review by javanna — COMMENTED** [review]
I was wondering if we consider this a bugfix or an enhancement (the corresponding label is missing), as that would affect the bwc strategy.

**Review by nik9000 — COMMENTED** [review]
I like the idea of failing but I don't know if we're ok with the semi-breaking nature. Opting folks into rejecting documents just by upgrading seems like something dangerous at this point.

**Comment by benwtrent** [comment]
> Opting folks into rejecting documents just by upgrading seems like something dangerous at this point.

I understand these concerns. 

We can just document, "Hey, don't do this". 

I definitely don't want to add a new parameter, and `ignore_malformed` seemed to fit this situation.

What do y'all think of adding a deprecation here? Seems like we should warn users and they shouldn't be doing this and if they want to keep doing it, they gotta allow `ignore_malformed`. @nik9000 @javanna

**Comment by benwtrent** [comment]
For now, I am going to close this PR and create another one that is a docs update. We should be very clear, that saturation can happen and can return weirdness. Simply saying "hey, these fit in a long value" isn't enough for typical users.

**Pull request closed without merging**
