### PR TITLE
Increase max chunk size to 256Mb for repo-azure

### LINKED ISSUE #12448: [cloud-azure] Support repository length > 64mb
Coming from https://github.com/elastic/elasticsearch-cloud-azure/issues/6

We currently only support repository with length <= 64mb.

To support larger blobs, we need to implement http://msdn.microsoft.com/en-us/library/windowsazure/dd135726.aspx

### PR DESCRIPTION
**Pull request by vladimirdolzhenko**
* upgrade azure storage to 8.0.0
* adjust MAX_CHUNK_SIZE to 256Mb

Closes #12448 

Note: Despite of Azure SDK has its own internal chunking - it is limited here to chunking on ES level up to max single Azure chunk size (=256Mb). Moving to Azure chunking requires more testing and could be done in follow up PR.

### CODE REVIEW

**Comment by vladimirdolzhenko** [comment]
I ran a manual test for the real azure storage with this change:

* indexed ~1M docs to make snapshot size several times more than chunk size:
```
"total": {
          "file_count": 140,
          "size": "1.9gb",
          "size_in_bytes": 2108996617
        }
```
* made snapshot :white_check_mark:
* restore from snapshot :white_check_mark:
* made 2nd snapshot and compare to the 1st one  :white_check_mark:

**Comment by dadoonet** [comment]
That looks great!

**Review by ywelsch — APPROVED** [review]
LGTM. Let's get this into 6.5 as well.

**Comment by vladimirdolzhenko** [comment]
just a note - I've increased chunk size for azure to 2gb (to utilize internal chunking) made snapshot and restored from it - looks good as well.

**Pull request merged**
