### PR TITLE
Add 7.1 and 8.0 version constants to master

### PR DESCRIPTION
**Pull request by jasontedor**
This commit adds the 7.1 and 8.0 version constants to the master branch, and bumps the master branch to 8.0.0.

### CODE REVIEW

**Comment by jasontedor** [comment]
This will have the same problem as #38513.

**Comment by tbrooks8** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by tvernum** [comment]
**elasticsearch-ci/2**
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-2/7692/console
```
02:04:14 > Task :x-pack:qa:rolling-upgrade:with-system-key:v7.1.0#upgradedClusterTestRunner
02:04:14 Tests with failures:
02:04:14   - org.elasticsearch.upgrades.IndexingIT.testIndexing
```
```
02:03:53    > 	at org.elasticsearch.upgrades.IndexingIT.testIndexing(IndexingIT.java:44)
02:03:53    > 	at java.lang.Thread.run(Thread.java:748)
02:03:53    > Caused by: java.net.SocketTimeoutException: 30.000 milliseconds timeout on connection http-outgoing-9 [ACTIVE]
02:03:53    > 	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.timeout(HttpAsyncRequestExecutor.java:387)
02:03:53    > 	at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:92)
02:03:53    > 	at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:39)
02:03:53    > 	at org.apache.http.impl.nio.reactor.AbstractIODispatch.timeout(AbstractIODispatch.java:175)
02:03:53    > 	at org.apache.http.impl.nio.reactor.BaseIOReactor.sessionTimedOut(BaseIOReactor.java:263)
02:03:53    > 	at org.apache.http.impl.nio.reactor.AbstractIOReactor.timeoutCheck(AbstractIOReactor.java:492)
02:03:53    > 	at org.apache.http.impl.nio.reactor.BaseIOReactor.validate(BaseIOReactor.java:213)
02:03:53    > 	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:280)
02:03:53    > 	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
02:03:53    > 	at 
```
That's not great, but is probably transient and not version related.

@elasticmachine run elasticsearch-ci/2

**Comment by tvernum** [comment]
**elasticsearch-ci/1**
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-1/7792/console
```
01:37:19 > Task :distribution:tools:plugin-cli:unitTest FAILED
01:37:19 Tests with failures:
01:37:19   - org.elasticsearch.plugins.RemovePluginCommandTests.testRemoveOldVersion
```
```
01:36:58 ERROR   0.04s J3 | RemovePluginCommandTests.testRemoveOldVersion <<< FAILURES!
01:36:58    > Throwable #1: java.lang.IllegalArgumentException: maxVersion [6.6.0] cannot be less than minVersion [7.0.0]
01:36:58    > 	at __randomizedtesting.SeedInfo.seed([CA8283935EE0B9C3:C1FE6E052C7BDD6E]:0)
01:36:58    > 	at org.elasticsearch.test.VersionUtils.randomVersionBetween(VersionUtils.java:222)
01:36:58    > 	at org.elasticsearch.plugins.RemovePluginCommandTests.testRemoveOldVersion(RemovePluginCommandTests.java:142)
01:36:58    > 	at java.lang.Thread.run(Thread.java:748)
01:36:58   1> [2562-02-08T03:36:57,856][INFO ][o.e.p.RemovePluginCommandTests] [testPurgeNothingExists] before test
01:36:58   1> [2562-02-08T03:36:57,861][INFO ][o.e.p.RemovePluginCommandTests] [testPurgeNothingExists] after test
01:36:58 Completed [3/4] on J3 in 1.83s, 14 tests, 1 error <<< FAILURES!
```
REPRODUCE WITH: ./gradlew :distribution:tools:plugin-cli:unitTest -Dtests.seed=CA8283935EE0B9C3 -Dtests.class=org.elasticsearch.plugins.RemovePluginCommandTests -Dtests.method="testRemoveOldVersion" -Dtests.security.manager=false -Dtests.locale=th-TH-u-nu-thai-x-lvariant-TH -Dtests.timezone=ART -Dcompiler.java=11 -Druntime.java=8

The reproduces, I'm investigating.

**Review by tvernum — APPROVED** [review]
LGTM, but it includes changes I made, so we'll need another approval before merging.

**Review by alpar-t — APPROVED** [review]
LGTM

**Pull request merged**
