### PR TITLE
Upgrade azure SDK to 0.9.3

### LINKED ISSUE #17042: Upgrade azure SDK to 0.9.3
We are ATM using azure SDK 0.9.0.

Azure latest release is now 0.9.3 (released in February 2016).

the central repository search engine google chrome aujourd hui at 08 41 12

Artifacts are on [maven central](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.microsoft.azure%22%20AND%20(a%3Aazure-serviceruntime%20OR%20a%3Aazure-servicebus%20OR%20a%3Aazure-svc-*))

Change log:

## 2016.2.18 Version 0.9.3

* Fix enum bugs in azure-svc-mgmt-websites

## 2016.1.26 Version 0.9.2

* Fix HTTP Proxy for Apache HTTP Client in Service Clients
* Key Vault: Fix KeyVaultKey to not attempt to load RSA Private Key

## 2016.1.8 Version 0.9.1

* Support HTTP Proxy
* Fix token expiration issue #557
* Service Bus: Add missing attributes: partitionKey, viaPartitionKey
* Traffic Manager: Update API version, add MinChildEndpoints for NestedEndpoints
* Media: Add support for Widevine (DRM) dynamic encryption

### PR DESCRIPTION
**Pull request by dadoonet**
We are ATM using azure SDK 0.9.0.

Azure latest release is now 0.9.3 (released in February 2016).

the central repository search engine google chrome aujourd hui at 08 41 12

Artifacts are on [maven central](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.microsoft.azure%22%20AND%20%28a%3Aazure-serviceruntime%20OR%20a%3Aazure-servicebus%20OR%20a%3Aazure-svc-*%29)

Change log:
## 2016.2.18 Version 0.9.3
- Fix enum bugs in azure-svc-mgmt-websites
## 2016.1.26 Version 0.9.2
- Fix HTTP Proxy for Apache HTTP Client in Service Clients
- Key Vault: Fix KeyVaultKey to not attempt to load RSA Private Key
## 2016.1.8 Version 0.9.1
- Support HTTP Proxy
- Fix token expiration issue #557
- Service Bus: Add missing attributes: partitionKey, viaPartitionKey
- Traffic Manager: Update API version, add MinChildEndpoints for NestedEndpoints
- Media: Add support for Widevine (DRM) dynamic encryption

Closes #17042.

### CODE REVIEW

**Comment by s1monw** [comment]
LGTM

**Comment by s1monw** [comment]
@dadoonet do we also wanna upgrade `2.x`?

**Comment by dadoonet** [comment]
Was wondering the same. I agree it makes sense to upgrade for 2.3.0

**Comment by dadoonet** [comment]
Also applied in `2.x` branch with 728eec2

**Pull request merged**
