### PR TITLE
Remove unnecessary DocumentMapperForType class

### PR DESCRIPTION
**Pull request by romseygeek**
This class was previously used to carry around dynamic mapping updates
between document types; now that we have a single document type, it is
unnecessary.  Removing it also allows us to make the dynamic mapping 
update field on ParsedDocument final.

### CODE REVIEW

**Comment by romseygeek** [comment]
@elasticmachine run elasticsearch-ci/2 (seems unrelated?)

**Comment by romseygeek** [comment]
Some `/get` tests are failing, which looks like I've messed up in the translog somewhere.  Digging.

**Comment by nik9000** [comment]
Neat!

**Comment by jimczi** [comment]
Is still useful @romseygeek ?

**Comment by javanna** [comment]
For what it's worth, we said introducing a no-op document mapper should help removing DocumentMapperForType. This is one of the tasks in #64663

**Comment by romseygeek** [comment]
Yes, it's still useful but has a few dependencies and the underlying code has changed sufficiently that I don't think it's worth keeping this version of it open.

**Pull request closed without merging**
