### PR TITLE
Fix Fast Vector Highlighter NPE on match phrase prefix

### LINKED ISSUE #25088: No highlights returned using dis_max with multi_match queries
**Elasticsearch version**: 5.4.0 and 5.4.1
**Regression**: Yes, works fine in ES 2.x
**Plugins installed**: []

**JVM version**: 1.8

**OS version** : Windows 7 

**Description of the problem**:

No highlights returned when searching using dis_max with a multi_match queries. 
Elasticsearch fails with 'null_pointer_exception' 

**Steps to reproduce**:

Create the following index
```
PUT blog 
{
  "mappings": {
    "blogpost": { 
      "properties": { 
        "title":    { "type": "text", "term_vector": "with_positions_offsets"}, 
        "body":     { "type": "text", "term_vector": "with_positions_offsets"  }
      }
    }
  }
}
```

Add a new document

```
PUT blog/blogpost/1
{
  "title": "welcome test",
  "body": "foo"
}
```
Run the following query to search 'test' string. 

```
GET blog/_search
{
  "query": {
    "bool": {
      "must": {
        "dis_max": {
          "queries": [
            {
              "multi_match": {
                "fields": [
                  "title"
                ], 
                "slop": 0, 
                "type": "phrase_prefix", 
                "max_expansions": 10, 
                "query": "test"
              }
            }, 
            {
              "multi_match": {
                "fields": [
                  "body"
                ], 
                "slop": 0, 
                "type": "phrase_prefix", 
                "max_expansions": 10, 
                "query": "test"
              }
            }]
        }
      }
    }
  },
  "highlight": {
    "fields": {
      "title": {
        "number_of_fragments": 0, 
        "matched_fields": [
          "title",
          "body"
        ], 
        "type": "fvh"
      }
    }, 
    "require_field_match": false
  }
}
```
Result: 

```
{
  "took": 1,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 4,
    "failed": 1,
    "failures": [
      {
        "shard": 3,
        "index": "blog",
        "node": "eMbzhELBQSO9kiRwVss65A",
        "reason": {
          "type": "null_pointer_exception",
          "reason": null
        }
      }
    ]
  },
  "hits": {
    "total": 1,
    "max_score": 0.25811607,
    "hits": []
  }
}
```
Now, let's update the same document and replace 'foo' with 'test' in the body attribute: 

```
PUT blog/blogpost/1
{
  "title": "welcome test",
  "body": "test"
}
```

Re-execute the search query above, it will successfully return the result
```
{
  "took": 1,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 1,
    "max_score": 0.2876821,
    "hits": [
      {
        "_index": "blog",
        "_type": "blogpost",
        "_id": "1",
        "_score": 0.2876821,
        "_source": {
          "title": "welcome test",
          "body": " test"
        },
        "highlight": {
          "title": [
            "w<em>elco</em>me <em>test</em>"
          ]
        }
      }
    ]
  }
}
```
As you can see, the query will always fail if the document does not find a match in both attributes. 

--Cheers!

### PR DESCRIPTION
**Pull request by jimczi**
The FVH fails with an NPE when a match phrase prefix is rewritten in an empty phrase query.
This change makes sure that the multi match query rewrites to a MatchNoDocsQuery (instead of an empty phrase query) when there is
a single term and that term does not expand to any term in the index.

Fixes #25088

### CODE REVIEW

**Review by jpountz — APPROVED** [review]

**Comment by jimczi** [comment]
Thanks @jpountz 

@v1r the fix will be available in 5.5.0 but you can also workaround this bug in 5.4 by replacing phrase_prefix query with a simple `prefix` query when there is a single term.

**Comment by v1r** [comment]
Thank you very much!!

**Comment by v1r** [comment]
@jpountz sadly the prefix query is not able to highlight underscored words.. for instance if you look for 'SQ0' in 'SQ05_H04_WorldTour'.. it will return nothing. any thought?

**Comment by v1r** [comment]
@jpountz sadly the prefix query is not able to highlight underscored words.. for instance if you look for 'SQ0' in 'SQ01_H04_Test'.. it will return nothing. any thought on what filter or tokenizer to use in this case?

**Comment by v1r** [comment]
@jpountz The prefix query is not analyzer, do you have any idea how I can get around that ? Thanks in advance!

**Pull request merged**
