### PR TITLE
Fix accounting in ModelLoadingServiceTests 

### PR DESCRIPTION
**Pull request by davidkyle**
In the test after the first load event is is not known which models are cached as loading a later one will evict an earlier and the order is not known. The first fix in #55008 recognised this error but got the counting wrong. The models could have been loaded 1 or 2 times not exactly twice

### CODE REVIEW

**Review by benwtrent — APPROVED** [review]

**Review by benwtrent — COMMENTED** [review]
test failures? org.elasticsearch.xpack.ml.inference.loadingservice.ModelLoadingServiceTests.testMaxCachedLimitReached(ModelLoadingServiceTests.java:193)
Actually, there were zero interactions with this mock.

Mockito seems a bit sassy

**Comment by davidkyle** [comment]
run elasticsearch-ci/1
run elasticsearch-ci/2

**Comment by davidkyle** [comment]
run elasticsearch-ci/2

**Comment by davidkyle** [comment]
run elasticsearch-ci/2

**Comment by davidkyle** [comment]
run elasticsearch-ci/2

**Comment by davidkyle** [comment]
run elasticsearch-ci/2

**Review by benwtrent — APPROVED** [review]
ran each test over 10k times. 

even when tests are green, Jenkins finds, uh, a way. :)

I think this is safe to merge.

**Pull request merged**
