### PR TITLE
Fix: Update geo-bounding-box-query.asciidoc

### PR DESCRIPTION
**Pull request by adnanashraf1**
There are some redundant words so I just removed those words. Please accept this change.

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Review by abdonpijpelink — APPROVED** [review]
Thanks @adnanashraf1 ! To ensure your change ends up in the most recent documentation, your PR should target the `main` branch. Do you need a hand backporting it to `main`, or shall I do that for you?

**Comment by adnanashraf1** [comment]
Thank you @abdonpijpelink for letting me know, I just changed my target branch to `main`.
Can you please look into it or help me contribute to it?
I would really appreciate your efforts.

**Comment by abdonpijpelink** [comment]
Thanks @adnanashraf1 . I have merged your change into the `8.2` branch and will backport it to `main`.

**Comment by abdonpijpelink** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|main|[](https://github.com/elastic/elasticsearch/pull/89301)|
|✅|8.4|[](https://github.com/elastic/elasticsearch/pull/89302)|
|✅|8.3|[](https://github.com/elastic/elasticsearch/pull/89303)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Comment by adnanashraf1** [comment]
Thank you @abdonpijpelink
I really appreciate your efforts.

**Pull request merged**
