### PR TITLE
[7.17] Add delete privilege to kibana_system for APM and Endpoint ILM policies (#81811)

### PR DESCRIPTION
**Pull request by joshdover**
Backports the following commits to 7.17:
 - Add delete privilege to kibana_system for APM and Endpoint ILM policies (#81811)

### CODE REVIEW

**Comment by joshdover** [comment]
Seems to be failing on all 7.17 backports right now: https://github.com/elastic/elasticsearch/pulls?q=is%3Aopen+label%3Av7.17.0+is%3Apr+label%3Abackport

**Comment by joshdover** [comment]
@elasticmachine merge upstream

**Comment by ywangd** [comment]
@elasticmachine update branch

**Comment by ywangd** [comment]
@elasticmachine update branch

**Comment by joshdover** [comment]
@elasticmachine update branch

**Pull request merged**
