### PR TITLE
speed up the process in LuceneVerifyingIndexOutput

### PR DESCRIPTION
**Pull request by rhluo**
As mentioned in [#96614](https://github.com/elastic/elasticsearch/issues/96614), The feature will be helpful to speedup the file chunk write process when there are a lot of small files to be recovery or restored. The Comparison Experimentation Based on NIO FS show that the speedup is 10 times.

       * Comparison Experimentation
       * Before optimization: chunk size 512KB, write times 10000, total cost time: 270827ms, avg cost time: 27.0827ms
       * After optimization: chunk size 512KB, write times 10000, total cost time: 11603ms, avg cost time: 1.1603ms

### CODE REVIEW

**Review by DaveCTurner — CHANGES_REQUESTED** [review]
Thanks @rhluo. I admit that I find the correctness of the existing code pretty hard to justify, and while you've done a good job at accurately reflecting its style (and your code now passes relevant tests) I don't think I can accept this change as written because I cannot justify spending the time it would take to convince myself it has no subtle flaws.

I'm certain there's a way to write this which is much more obviously correct.

**Comment by rhluo** [comment]
if we define thes writeByte process as functionA(), now we consider the writeBytes process.
The original solution is as follows:

	for (int i = 0; i < length; i++)
		functionA()
I think you mean wo can just do as follows:
	
	out.writeBytes() //direct write parts before checksum position
	for(int i = checksumPosition; i < length; i++)
		functionA()

**Comment by DaveCTurner** [comment]
I don't have much to add to my preceding review - I sort of see why this is correct but that's not enough for me. The existing code is already too complicated (I wouldn't accept it if it were something we were adding today) and this change makes it worse.

I will open a PR to clean this area up, and address https://github.com/elastic/elasticsearch/issues/96614, in the next few weeks.

**Comment by rhluo** [comment]
@DaveCTurner Thank you very much for taking up a lot of your time to help me review the code. I try to provide a more understandable solution. the new solution contains three main steps: 
1) fill checksum using array copy
2) verify when writtenBytes reached file end
3) write through by call out.writeBytes

Finally, thanks again anyway, I learned a lot from communicating with you. I will also contribute my ideas to ES community at the next opportunity.

**Review by DaveCTurner — COMMENTED** [review]
Thanks @rhluo, I like this more, but the more I look at this area of the code the more tech debt I am finding. I won't have time to work on this in the next week or so, but I have a plan for a more substantial cleanup in the near future.

**Comment by DaveCTurner** [comment]
I opened https://github.com/elastic/elasticsearch/pull/96975 (and marked @rhluo as a co-author) so I'm closing this.

**Pull request closed without merging**
