### PR TITLE
Remove norelease comments in test classes

### PR DESCRIPTION
**Pull request by cbuescher**
We added these comments to enhance our randomized test infrastructure, but since they are in tests they don't seem to serve their purpose of blocking a release. I propose we should turn these into issues rather than leave them in the code base.

### CODE REVIEW

**Comment by cbuescher** [comment]
@colings86 @javanna opened this mainly for a brief discussion.

**Comment by javanna** [comment]
++ thanks @cbuescher

**Comment by colings86** [comment]
I have no problem with opening issues for these but I am surprised that NORELEASE comments in tests don't affect the release. They probably should since the lack of something in tests may be a legitimate reason for not being able to release (I'm not saying in this case it should stop a release but I can imagine we might want that to happen at some point). Maybe we should open an issue for that too?

**Comment by cbuescher** [comment]
This is probably the main issue:
https://github.com/elastic/elasticsearch/issues/14414

There's a mini-solution to at least be able to test from a small set of random queries, but I haven't looked into it for some time now. Maybe we should close this and start a fresh attempt:
https://github.com/elastic/elasticsearch/pull/16055

Random Aggregations and random Ext probably need separate issues, or does something like this exist already?

**Comment by cbuescher** [comment]
I created two new issues regarding the randomized tests that would be nice to have for SearchSourceBuilder. @javanna @colings86 any objections that I merge this then and remove the comments in the test code now?

**Comment by javanna** [comment]
I am good ;)

**Pull request merged**
