### PR TITLE
Field caps api  - report back if fields are single-valued or not.

### PR DESCRIPTION
**Pull request by markharwood**
Inspects index contents for each requested field to reveal if all docs hold single values or not.
Expected to be useful information for clients e.g. helping Kibana understand if it ever makes sense to AND different values from the same field when constructing drill-down queries.

Relates to #58523

### CODE REVIEW

**Comment by markharwood** [comment]
One consideration @cbuescher raised is that inspecting index stats in this way will have some inaccuracies when it comes to deleted docs. The worst-case scenario is that an index with a rogue multi-valued doc that was changed to be single-valued will still report the whole index as multi-valued until the old deleted doc is merged out.

**Comment by markharwood** [comment]
#### Performance feedback
@original-brownbear was kind enough to perform some benchmarking on a large installation (15k shards) and was not able to measure any performance difference on the field caps api between this PR and previous versions.

**Comment by jpountz** [comment]
> @original-brownbear was kind enough to perform some benchmarking on a large installation (15k shards) and was not able to measure any performance difference on the field caps api between this PR and previous versions.

Out of curiosity how many mapped fields per shard did the benchmark have, and did the index have actual data for each of these fields?

**Comment by original-brownbear** [comment]
> Out of curiosity how many mapped fields per shard did the benchmark have, and did the index have actual data for each of these fields?

This was Beats indices (mix of Audit, Metric- etc.) so I'd say on average ~2k fields per index.

> index have actual data for each of these fields?

This was benchmarked using a variation of the Observability logging track. I do not believe that there was data present for all fields. Looking at the code again now that you mention it (sorry completely missed checking the number field mapper implementation here), whether or not we have data (and also how much of it?) seems to be massively important here.
We don't have a benchmark ready to go for this kind of thing right now (and it's not entirely trivial to set up because of the raw amount of data it would have to index) but maybe it's time to set that up to be safe here?

**Comment by cbuescher** [comment]
Closing here since in this form the PR is outdated.

**Pull request closed without merging**
