### PR TITLE
match processor should handler values other than string properly

### PR DESCRIPTION
**Pull request by martijnvg**
Currently if the document being ingested contains another field value
than a string then the processor fails with an error.

This commit changes the match processor to handle number values
and array values correctly.

If a json array is detected then the `terms` query is used instead
of the `term` query.

### CODE REVIEW

**Comment by talevy** [comment]
sorry about the conflict @martijnvg! Luckily I don't think it'll be too big a deal to move this to the Abstract Processor

**Review by jbaiera — APPROVED** [review]
LGTM

**Comment by martijnvg** [comment]
@elasticmachine update branch

**Comment by martijnvg** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by martijnvg** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample-matrix

**Pull request merged**
