### PR TITLE
[Inference API] Avoid potential flaky wire serialization test cases

### PR DESCRIPTION
**Pull request by timgrein**
AFAIU there's some small likelihood for `createTestInstance` and `mutateInstance` to return two equal instances if you don't wrap `createRandom` calls with `randomValueOtherThan`, which would lead to a flaky test failure. I've adjusted this for all wire serialization test cases and also implemented `mutateInstance` where `null` was returned. Some of these classes were records, so we strictly don't need to test this, but we already had instances, where we've converted a `record` to a `class` and implemented `equals` and `hashCode` again manually, so preempting this.

### CODE REVIEW

**Review by davidkyle — APPROVED** [review]
LGTM

Thanks @timgrein

**Comment by timgrein** [comment]
@elasticmachine update branch

**Comment by timgrein** [comment]
@elasticmachine update branch

**Comment by timgrein** [comment]
@elasticmachine update branch

**Pull request merged**
