### PR TITLE
fix query profile

### LINKED ISSUE #108116: Query and query profile show different execution path for some queries like conjunctions
### Elasticsearch Version

8.12.2

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Linux 2022 x86_64 GNU/Linux

### Problem Description

my index settings
```json
{
 "settings": {
  "analysis": {
   "tokenizer": {
    "ngram2": {
     "type": "ngram",
     "min_gram": 1,
     "max_gram": 2
    }
   },
   "analyzer": {
    "ngram2": {
     "tokenizer": "ngram2"
    }
   }
  },
  "number_of_replicas": "0"
 },
 "mappings": {
  "properties": {
   "name": {
    "type": "text",
    "analyzer": "ngram2"
   }
  }
 }
}
```

query1: 
```json
{
  "query": {
    "match": {
      "name": {
        "query": "12",
        "operator": "and"
      }
    }
  },
  "profile": false,
  "track_total_hits": false
}
```
query2: 
```json
{
  "query": {
    "match": {
      "name": {
        "query": "12",
        "operator": "and"
      }
    }
  },
  "profile": true,
  "track_total_hits": false
}
```
The query1  that profile params is `false` get `BlockMaxConjunctionBulkScorer`, and the debug in code as follow: 
image

The query2  that profile params is `true` get `ConjunctionScorer`, and the debug in code as follow: 
image

Query2 should get `BlockMaxConjunctionScorer`, i think, but it does not.

I want to track some`ImpactsEnum` profile like  `shallow_advance_count` or `shallow_advance` for some tune reason.

I looked into the `weight.bulkScorer` code, and found the different reason and got solution.

Lucene has some optimization on ImpactsDISI, and the pull request: https://github.com/apache/lucene/pull/12490

The request introduce a  idea call top-level score:
> Term queries would then only wrap with ImpactsDISI when they produce the top-level score. 

Then I found `ProfileWeight.scorerSupplier` didn't override `setTopLevelScoringClause` method. 

`Weight` will call `scorerSupplier.setTopLevelScoringClause()` in `bulkScorer` method.

I override the method `setTopLevelScoringClause`  in `ProfileWeight.scorerSupplier`, the code as follow:
```java
new ScorerSupplier() {
            // ...
            
            @Override
            public void setTopLevelScoringClause() throws IOException {
                subQueryScorerSupplier.setTopLevelScoringClause();
            }
}
```
After the above modification, Query2 got `BlockMaxConjunctionScorer` as expected.
 

### Steps to Reproduce

1. create test-index
```curl
curl -H 'Content-type: application/json' -XPUT 'http://localhost:9200/test-index/' -d '{
 "settings": {
  "analysis": {
   "tokenizer": {
    "ngram2": {
     "type": "ngram",
     "min_gram": 1,
     "max_gram": 2
    }
   },
   "analyzer": {
    "ngram2": {
     "tokenizer": "ngram2"
    }
   }
  },
  "number_of_replicas": "0"
 },
 "mappings": {
  "properties": {
   "name": {
    "type": "text",
    "analyzer": "ngram2"
   }
  }
 }
}'
```
2. index some data
```curl
for i in {1..1000}; do curl -H 'Content-type: application/json' -XPOST 'http://localhost:9200/test-index/_doc' -d "{\"name\":  \"${i}\"}"; done

```
3. debug query
```curl 
curl -H 'Content-type: application/json' -XGET 'http://localhost:9200/test-index/_search' -d '{
  "query": {
    "match": {
      "name": {
        "query": "12",
        "operator": "and"
      }
    }
  },
  "profile": false,
  "track_total_hits": false
}'
```

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by zhongshanhao**
For related information, please see the issues: https://github.com/elastic/elasticsearch/issues/108116

### CODE REVIEW

**Review by benwtrent — APPROVED** [review]
This is a nice bugfix! Thank you for the in depth analysis and simple fix!

Now to get CI happy...

**Comment by benwtrent** [comment]
@elasticmachine generate changelog

**Comment by benwtrent** [comment]
buildkite test this please

**Comment by benwtrent** [comment]
🎉 🎉 🎉  Thank you for your contribution @zhongshanhao 🎉 🎉 🎉

**Comment by javanna** [comment]
heya, should we add a test to verify this behaviour and make sure it's not forgotten in the future?

**Comment by benwtrent** [comment]
https://github.com/elastic/elasticsearch/pull/108160

**Pull request merged**
