### PR TITLE
Remove some unused parameters/methods/fields

### PR DESCRIPTION
**Pull request by tlrx**
This PR removes some unused parameters, methods and private fields here and there. 

Warning: most boring spring-cleaning PR to review

### CODE REVIEW

**Comment by rmuir** [comment]
looks great

**Comment by nik9000** [comment]
You may want to have a look at [RedundantModifier](http://checkstyle.sourceforge.net/config_modifier.html#RedundantModifier).

**Comment by tlrx** [comment]
> You may want to have a look at RedundantModifier.

I didn't know about it, thanks. I think we can activate it even if it's just a matter of style.

**Comment by jasontedor** [comment]
> You may want to have a look at [RedundantModifier](http://checkstyle.sourceforge.net/config_modifier.html#RedundantModifier).

+1

**Comment by jpountz** [comment]
LGTM

**Comment by tlrx** [comment]
Thanks @jpountz

**Pull request merged**
