### PR TITLE
Use TriangleTree for GeoShape Doc Values

### PR DESCRIPTION
**Pull request by talevy**
After lots of evaluation and benchmarking, it seems
the TriangleTree is preferred over the GeometryTree
for the following reasons

- simpler to model all shapes as one tree instead of
  specializing and optimizing for edge-cases. (GeometryCollection
  of Points is stored the same as a MultiPoint)
- Although there are more situations where the EdgeTree out-performs
  the TriangleTree, the times it is faster it is faster by a lot
  because it is these times that the EdgeTree must traverse O(n) of
  the edges to determine a queried tile is outside of the shape.
  https://gist.github.com/talevy/f06ef43be1e97afb1ee53f25b980a4a0

Downsides of the Triangle when compared to Geometry Tree

- it is not possible to reverse-engineer into the original geometry
  for use in scripting
- Points cannot be stored as compactly as in the GeometryTree
- not faster on every single relate query

### CODE REVIEW

**Comment by talevy** [comment]
ah @iverase. I forgot the bounds issue is still open so `GeoBoundsAggregatorTests.testFiji` is failing.

**Comment by talevy** [comment]
@imotov we reviewed all the performance characteristics of the TriangleTree and prioritized tiling performance over support certain SQL geo functions. Since you were not present for our discussion, would you mind sharing your thoughts on this issue/PR so that we appropriately weigh the decision better since the TriangleTree makes it difficult to reverse-engineer the geometry for use in scripts

**Comment by iverase** [comment]
@talevy I open #49847 to address the issue of the test. I thought we did not need the extent but er do for supporting geo bounds properly when there is a multi-shape.

What I found is that now another test fails: GeoBoundsIT#testSingleValuedFieldNearDateLine.

After digging a bit I realise that is a problem in the test (and in the Geometry tree). The test assumes that the extent of a line is the extent of the points which is not true. The line `LINE(-179 0, 179 0)` crosses the whole world so the extent should be the whole world. If you only consider the points you get the wrong extent.

**Comment by talevy** [comment]
> After digging a bit I realise that is a problem in the test

I'll take a look at this. thanks for bringing it up

**Review by iverase — APPROVED** [review]
lgtm

**Review by imotov — COMMENTED** [review]
@talevy I agree we have very compelling reasons of going with this solution. However, I am concerned that this will make it difficult if not impossible to implement may geosql functionality that we were hopping for without implementing an option of storing the original shape as a doc value. Perhaps, it would be the best to discuss this with @elastic/es-sql team.

**Comment by talevy** [comment]
thank you @imotov! I will move forward with this change

**Pull request merged**
