### PR TITLE
add "Best Practices" section to the cloud-aws docs

### PR DESCRIPTION
**Pull request by djschny**
Per discussion about collecting best practices and various other AWS lore and then including it in the documentation for the AWS Cloud Plugin.

### CODE REVIEW

**Comment by dadoonet** [comment]
Looks very good. If you push that in master branch, please could you change cloud plugin with discovery plugin. It has been renamed in 3.0.

**Comment by djschny** [comment]
Thanks for looking @dadoonet 

Yes I will do a different structure organization for master as it doesn't match up. Should I push this to `2.0` and `2.x` or should this wait based upon the current timing with the release?

**Comment by dadoonet** [comment]
Yes. You can push changes to documentation to 2.0 (and 2.1 & 2.x).

**Comment by dakrone** [comment]
@djschny ping reminder for you to merge this (assuming it's still needed)

**Comment by djschny** [comment]
Sorry, but excuse my ignorance, it seems really silly/dangerous, but this actually has to be independently pushed to all the branches labeled above?

**Comment by dadoonet** [comment]
I'd push this to master, 2.x and 2.2 branches.

**Comment by djschny** [comment]
This has been added to the recommended branches:

* 2.x - https://github.com/elastic/elasticsearch/commit/65faab6935a27342ae2442e85c089638285a297b
* 2.2 - https://github.com/elastic/elasticsearch/commit/50b87fd861c97f3afacfbbe119ec1b530187a5e7
* master - https://github.com/elastic/elasticsearch/commit/c42149ebe2a1993db6b6937116d0bd01e7b10c3a

**Pull request closed without merging**
