### PR TITLE
[DOCS] Clarify breaking changes for realm settings

### PR DESCRIPTION
**Pull request by rwaight**
Update the breaking changes realm settings to align with the realm documents.  The current breaking changes document is not consistent with our realm documents.

### CODE REVIEW

**Comment by rwaight** [comment]
This should also be applied to 7.1 and newer

**Review by psanz-estc — APPROVED** [review]
LGTM

**Comment by jrodewig** [comment]
Will merge and forwardport after CI passes.

**Comment by lcawl** [comment]
It seems to me that the original format matches the example here: https://www.elastic.co/guide/en/elasticsearch/reference/7.x/security-settings.html#realm-settings

**Comment by tvernum** [comment]
Can we hold off on merging this please.
The format used there was chosen for a reason, and I'd like to discuss it further before we change it.

**Comment by tvernum** [comment]
Sorry, for delaying this. We discussed it within @elastic/es-security a couple of weeks ago, but I didn't bring the conversation back here.

The breaking changes docs was formatted the way it is because that is the smallest & safest change needed to convert an old config format into the new format. You remove one line (the `type` setting) and edit one line (to prefix the realm name with the type) but nothing else needs to be changed.

The proposed doc requires reindenting the whole block of YAML, and we know that it's easy to make mistakes with YAML indenting.
I worry that this change swaps one set of problems (confusion amongst those who are not familiar with the variety of different ways to structure the same piece of YAML) for another, potentially worse, issue (nodes failing to start because the YAML was not indented correctly).

I'd be happy to expand the breaking changes doc to include a more explanation about the format, but I don't think a wholesale switch will actually leave us in a better state.

**Comment by jrodewig** [comment]
I'm closing this PR. Please re-open if you feel more discussion is needed. Thanks!

**Pull request closed without merging**
