### PR TITLE
Disable testingConventions in build tools in fips

### PR DESCRIPTION
**Pull request by jkakavas**
Necessary since we also disable test and testingConventions would
fail in FIPS 140 mode.

### CODE REVIEW

**Comment by jkakavas** [comment]
@elasticmachine update branch

**Review by rjernst — APPROVED** [review]
LGTM, although it would be nice if there were a comment explaining why tests were disabled here in the first place

**Comment by jkakavas** [comment]
Fair ! I should have done this when originally muting these, but will add now

**Review by mark-vieira — APPROVED** [review]
👍

**Pull request merged**
