### PR TITLE
Allow to enable annotation processing explicitly

### PR DESCRIPTION
**Pull request by danielmitterdorfer**
In 1e91f3b we disabled annotation processors globally. However, some
projects like JMH need annotation processing, so we add an ability to
selectively enabled annotation processing for certain projects by
setting the compile option `-processor` in the corresponding 
Gradle build script. If it is present, the specified processor(s) will be
enabled for this project. By default, we still disable all annotation
processors.

### CODE REVIEW

**Comment by danielmitterdorfer** [comment]
I'll now work on a reproduction scenario for the bug in Gradle that I've mentioned above.

**Comment by danielmitterdorfer** [comment]
I've created a [reproduction scenario](https://github.com/danielmitterdorfer/gradle-ap-repro) and [made the Gradle team aware of the problem](https://discuss.gradle.org/t/gradle-erroneously-quotes-javac-flag-processor/19136).

**Comment by danielmitterdorfer** [comment]
I got a hint from the Gradle team that we need to specify it as `compileJava.options.compilerArgs.addAll(["-processor",  "org.openjdk.jmh.generators.BenchmarkProcessor"])`. Verified locally and updated the PR and the description.

**Comment by jasontedor** [comment]
Thank you for addressing the concern that we discussed via another channel (we still do not want arbitrary unspecified annotation processors running).

LGTM

**Comment by danielmitterdorfer** [comment]
Thanks for your review Jason.

**Pull request merged**
