### PR TITLE
Fix Eclipse compilation issue in Java string blocks

### PR DESCRIPTION
**Pull request by cbuescher**
The bulk change to multiline Java String blocks caused comilation issues in two
classes. Reformatting the Strings differently solved this for me.

### CODE REVIEW

**Comment by cbuescher** [comment]
For posterity: bug on the Eclipse side is https://bugs.eclipse.org/bugs/show_bug.cgi?id=577856

**Comment by nik9000** [comment]
Another option is to use Eclipse 2021-12 #81833

**Review by mark-vieira — APPROVED** [review]
No strong objections but seems like just upgrading Eclipse is a better solution here if that's feasible.

**Comment by cbuescher** [comment]
Thanks @mark-vieira, I also updated to Eclipse 2021-12 which seems to be good advice if we use the new language features going forward. I'll close this issue without merging but folks who need these small changes if they cannot update have them here if needed.

**Pull request closed without merging**
