### PR TITLE
Add bad_request to the rest-api-spec catch params

### PR DESCRIPTION
**Pull request by hub-cap**
This adds another request to the catch params. It also makes sure that
the generic request param does not allow 400 either.

### CODE REVIEW

**Comment by hub-cap** [comment]
Please note I did not change the lower bounds on the generic `request` param check. I thought it more concrete to say "anything 400 and above except for this list" rather than "anything above 401 but not these" since we now check for 400 and 401.

**Review by jasontedor — APPROVED** [review]
LGTM assuming that @elastic/es-clients is good with the addition.

**Comment by jasontedor** [comment]
Yes, I prefer the way that you've done it here.

**Comment by hub-cap** [comment]
@elasticmachine test this please

for some reason I dont see the integration for CI on this PR anymore?

image

**Comment by polyfractal** [comment]
You might consider adding a "feature skip" to these tests, otherwise every client is going to get whacked with 20+ failures until client authors can update their test runner.

E.g.

```yaml
 - skip:
      features: bad_request
```

I guess it depends how urgently you want client authors to update.  Skip == when they get a chance, no skip == lotsa failures == asap.

**Comment by hub-cap** [comment]
oh my. Thats not good. Let me sync w/ the client team and see how they would like to proceed. Id *love* to not break builds for them. Ty for the heads up @polyfractal

**Comment by polyfractal** [comment]
OTOH, I think most of the client team uses breakages as a signal that something needs updating.  It's easier than trying to closely track upstream changes (and we're lazy)  :)

I'm ++ on the `bad_request` addition btw, but would be good to run it by the rest of the client team.

**Comment by Mpdreamz** [comment]
@hub-cap informed the #lang-clients room and @polyfractal raised the possible breakage during the last clients meeting which did not seem to rattle anyone :smile:. I feel enough time has passed for anyone from @elastic/es-clients to object to the breakage.

**Comment by hub-cap** [comment]
@elasticmachine test this please

**Pull request merged**
