### PR TITLE
ignore 409 conflict in reindex responses

### PR DESCRIPTION
**Pull request by andyb-elastic**
The reindex family of APIs (reindex, update-by-query, delete-by-query) can sometimes return responses that have an error status code (409 Conflict in this case) but still have a body in the usual `BulkByScrollResponse` format. When the HLRC tries to handle such responses, it blows up because it tris to parse it expecting the error format that errors in general use. This change prompts the HLRC to parse the response using the expected `BulkByScrollResponse` format.

I wasn't sure how to test this, since the HLRC tests run against a live cluster, and the circumstance under which a response with conflicts occurs is difficult to reproduce. I wrote a test that just tested the response handler, but it involved basically unwinding the whole call stack of HLRC performing a request. @hub-cap is there a better way I'm not aware of?

### CODE REVIEW

**Comment by javanna** [comment]
@andyb-elastic would it be possible to simulate the 409 scenario by e.g. mocking the http client, or even the low-level client? See `RestClientSingleHostTests` for something along those lines.

**Comment by dakrone** [comment]
> I wasn't sure how to test this, since the HLRC tests run against a live cluster, and the circumstance under which a response with conflicts occurs is difficult to reproduce.

Perhaps you could reindex with an ingest pipeline that rewrote the ID and version of the doc so that the Nth document conflicted with a previous one?

**Comment by andyb-elastic** [comment]
> See `RestClientSingleHostTests` for something along those lines.

Thanks for the pointer @javanna, I was looking for something like this 

>Perhaps you could reindex with an ingest pipeline that rewrote the ID and version of the doc so that the Nth document conflicted with a previous one?

I like this idea because it gives us a real conflict response and it's not too much of a hack, thanks @dakrone. I did this for reindex and update by query - unfortunately delete by query doesn't take a pipeline, but it's using the same deserializer as the other two

I also moved the tests for update by query and delete by query from CrudIT to ReindexIT because these APIs are usually grouped together, as they share an implementation

**Review by hub-cap — APPROVED** [review]
too bad about not being able to find a way to test the delete case. I cannot think of a better way than what @dakrone mentioned. That being said, ill still approve the PR. Great work.

Also, thanks for the suggestions and review so far while i was on vacation, and sorry for the late response!

**Comment by andyb-elastic** [comment]
Thanks @hub-cap I'll merge master back in and run ci again before merging

**Comment by andyb-elastic** [comment]
From the bwc job

```

:client:rest-high-level:compileTestJava FAILED
--
/var/lib/jenkins/workspace/elastic+elasticsearch+pull-request-bwc/client/rest-high-level/src/test/java/org/elasticsearch/client/CustomRestHighLevelClientTests.java:139: error: incompatible types: inference variable C has incompatible bounds
.collect(Collectors.toCollection(TreeSet::new));
^
equality constraints: Object,R
lower bounds: Set<String>,Object,Collection<T#1>
where C,T#1,R,A,T#2 are type-variables:
C extends Collection<T#1> declared in method <T#1,C>toCollection(Supplier<C>)
T#1 extends Object declared in method <T#1,C>toCollection(Supplier<C>)
R extends Object declared in method <R,A>collect(Collector<? super T#2,A,R>)
A extends Object declared in method <R,A>collect(Collector<? super T#2,A,R>)
T#2 extends Object declared in interface Stream
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
```

Not seeing it locally, @elasticmachine run elasticsearch-ci/bwc please

**Comment by andyb-elastic** [comment]
master - 2b2bd8fd3fbc67a50a19f4333c4b84af40f1cada
7.x - c0c6d702a2638f4ce65bf01ebab44b8515084d6e

**Pull request merged**
