### PR TITLE
Add time_zone setting for query_string

### PR DESCRIPTION
**Pull request by dadoonet**
Query String query now supports a new `time_zone` option based on JODA time zones.
When using a range on date field, the time zone is applied.

``` json
{
"query": {
  "query_string": {
    "text": "date:[2012 TO 2014]",
    "timezone": "Europe/Paris"
  }
 }
}
```

Closes #7880.

### CODE REVIEW

**Comment by im-denisenko** [comment]
@dadoonet Could you have a look please? Either this option not working or I don't understand how it should work.

I have following code: 
```bash
curl -XPUT 'http://localhost:9200/foo/?pretty' -d '{"mapping": {"tweets": {"properties": {"tweet_date": {"type": "date"}}}}}'
curl -XPOST 'http://localhost:9200/foo/tweets/1/' -d '{"tweet_date": "2015-04-05T23:00:00+0000"}'
curl -XPOST 'http://localhost:9200/foo/tweets/2/' -d '{"tweet_date": "2015-04-06T00:00:00+0000"}'
curl -XPOST 'http://localhost:9200/foo/_refresh?pretty'

curl -XGET 'http://localhost:9200/foo/tweets/_search?pretty' -d '{
    "query": {
        "query_string": {
            "query": "tweet_date:[2015-04-06T00:00:00+0200 TO 2015-04-06T23:00:00+0200]"
        }
    }
}'

curl -XGET 'http://localhost:9200/foo/tweets/_search?pretty' -d '{
    "query": {
        "query_string": {
            "query": "tweet_date:[2015-04-06T00:00:00 TO 2015-04-06T23:00:00]",
            "time_zone": "+0200"
        }
    }
}'

```
First query result:
```
{
  "hits" : {
    "total" : 2,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "foo",
      "_type" : "tweets",
      "_id" : "2",
      "_score" : 1.0,
      "_source":{"tweet_date": "2015-04-06T00:00:00+0000"}
    }, {
      "_index" : "foo",
      "_type" : "tweets",
      "_id" : "1",
      "_score" : 1.0,
      "_source":{"tweet_date": "2015-04-05T23:00:00+0000"}
    } ]
  }
}
```
Second query result:
```
{
  "hits" : {
    "total" : 1,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "foo",
      "_type" : "tweets",
      "_id" : "2",
      "_score" : 1.0,
      "_source":{"tweet_date": "2015-04-06T00:00:00+0000"}
    } ]
  }
}
```

Shouldn't this results be the same?

**Comment by dadoonet** [comment]
@im-denisenko I think they should. If you are using Elasticsearch 1.5.0, I'd open an issue with this great full reproduction script.

**Comment by im-denisenko** [comment]
@dadoonet Yes, this is 1.5.0
Thanks for answer. It resolves all my "wtf" for last few hours :)

**Comment by dadoonet** [comment]
@im-denisenko Could you open an issue so we won't forget to add some tests and fix it?

**Pull request closed without merging**
