### PR TITLE
Remove duplicate text

### PR DESCRIPTION
**Pull request by umutuz7**
Same sentence from 1 paragraph above

### CODE REVIEW

**Comment by jtibshirani** [comment]
Thanks @umutuz7 ! Could you please sign the CLA so I can merge this? Sorry for the inconvenience, we require a CLA for all changes, even if they're small.

**Comment by umutuz7** [comment]
Hi @jtibshirani ,
I actually signed the CLA right after but will check again.
Thanks!

**Comment by umutuz7** [comment]
Ah I think it's fine now.

**Comment by jtibshirani** [comment]
@elasticmachine run docs tests

**Comment by jtibshirani** [comment]
@elasticmachine run elasticsearch-ci/docs

**Review by jtibshirani — APPROVED** [review]

**Pull request merged**
