### PR TITLE
Fix serverless scope for distrib APIs

### PR DESCRIPTION
**Pull request by henningandersen**
Mark APIs public/internal/unavailable as per prior discussion.

### CODE REVIEW

**Review by kingherc — COMMENTED** [review]
One question to confirm about clone.

**Review by kingherc — APPROVED** [review]
LGTM

**Comment by henningandersen** [comment]
CI failure reported in #97182

@elasticmachine run elasticsearch-ci/part-2

**Comment by henningandersen** [comment]
Thanks Iraklis!

**Pull request merged**
