### PR TITLE
Adds release notes for 6.7.1

### PR DESCRIPTION
**Pull request by colings86**

### CODE REVIEW

**Review by jasontedor — APPROVED** [review]
LGTM.

**Review by tomcallahan — APPROVED** [review]

**Comment by dongs0104** [comment]
@colings86 will https://github.com/elastic/elasticsearch/pull/40723 apply to 6.7.1?

**Comment by jasontedor** [comment]
@dongs0104 That is what we are currently planning, but nothing is guaranteed until the software actually ships. 😇

**Comment by dongs0104** [comment]
@jasontedor When does 6.7.1 ship? when i rolling up to 6.5.4 to 6.7.0 issue is occured on production... ;( i test is on single-node. i hope to it ship asap ;)

**Comment by jasontedor** [comment]
@dongs0104 I am sorry, but we do not give any indications on releases as we do not want to disappoint our users when we miss our indications. We do recognize the impact that an issue like this has on our users, so we are aiming to release as fast as is reasonable, but beyond that would not give any indication. Sorry for the bug, and I hope you understand and can bear with us while we try to get a fix out!

**Pull request merged**
