### PR TITLE
Manually Craft CreateSnapshotRequest to fix BwC Test

### LINKED ISSUE #57650: :qa:repository-multi-version BWC tests failing with
**Build scan**:

Lots, see e.g. https://gradle-enterprise.elastic.co/s/nrzcy2j2l4ivo

**Repro line**:

```
./gradlew ':qa:repository-multi-version:v7.4.0#Step1OldClusterTest' --tests "org.elasticsearch.upgrades.MultiVersionRepositoryAccessIT.testReadOnlyRepo" \
  -Dtests.seed=55743EAD1D5D0105 \
  -Dtests.security.manager=true \
  -Dtests.locale=hu-HU \
  -Dtests.timezone=America/Buenos_Aires \
  -Dtests.distribution=default \
  -Druntime.java=11
```

**Reproduces locally?**:

Yep

**Applicable branches**:

Master

**Failure history**:

Looks to be caused by 7d3a7afd16a44f2c5dbdf24954986ffeda8b58e4 (i.e. #57325)

**Failure excerpt**:

```

2> REPRODUCE WITH: ./gradlew ':qa:repository-multi-version:v7.4.0#Step1OldClusterTest' --tests "org.elasticsearch.upgrades.MultiVersionRepositoryAccessIT.testCreateAndRestoreSnapshot" -Dtests.seed=55743EAD1D5D0105 -Dtests.security.manager=true -Dtests.locale=hu-HU -Dtests.timezone=America/Buenos_Aires -Dtests.distribution=default -Druntime.java=11 |  
-- | --
  | 2> org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=illegal_argument_exception, reason=No valid expand wildcard value [hidden]] |  
  | at __randomizedtesting.SeedInfo.seed([55743EAD1D5D0105:D3CC1CF3805C60B8]:0) |  
  | at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:177) |  
  | at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1888) |  
  | at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1865) |  
  | at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1622) |  
  | at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1579) |  
  | at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1549) |  
  | at org.elasticsearch.client.SnapshotClient.create(SnapshotClient.java:221) |  
  | at org.elasticsearch.upgrades.MultiVersionRepositoryAccessIT.createSnapshot(MultiVersionRepositoryAccessIT.java:291) |  
  | at org.elasticsearch.upgrades.MultiVersionRepositoryAccessIT.testCreateAndRestoreSnapshot(MultiVersionRepositoryAccessIT.java:121)

```

### PR DESCRIPTION
**Pull request by original-brownbear**
We can't use the high level create snapshot request any longer
since we changed some of its default parameters in `8` and those
are not understood by older versions like `7.4`.

Closes #57650

### CODE REVIEW

**Review by DaveCTurner — CHANGES_REQUESTED** [review]
There's something fishy about needing to drop to the LLRC here, but I'm not really sure where the bug lies. As an alternative I tried setting `indicesOptions(null)` but this fails validation, despite the fact that we do have null checks in `CreateSnapshotRequest#toXContent` and HTTP clients are permitted to omit this field. Are we sure we want the default to be a function of the client version rather than something that's decided on the server?

Could we at least use the HLRC if we know the version under test is compatible, so that this change has a limited lifespan?

**Comment by original-brownbear** [comment]
> Are we sure we want the default to be a function of the client version rather than something that's decided on the server?

Good question :) I guess this is not necessarily the place to discuss this, but I guess that's how the transport client behaves as well. 

> Could we at least use the HLRC if we know the version under test is compatible, so that this change has a limited lifespan?

I'm not sure that is all that helpful here? If we add some version check to using HLRC client it's just a lot more brittle and may break again in the future if anything changes. (+ we already use the LLRC for all the other requests precisely because of the compatibility issue so it would be weird to single out this one request).

In the end our [docs](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/master/java-rest-high-compatibility.html) say:

> The 6.0 client is able to communicate with any 6.x Elasticsearch node, while the 6.1 client is for sure able to communicate with 6.1, 6.2 and any later 6.x version, but there may be incompatibility issues when communicating with a previous Elasticsearch node version, for instance between 6.1 and 6.0, in case the 6.1 client supports new request body fields for some APIs that are not known by the 6.0 node(s).

... so we don't really have many guarantees or a defined check for version compatibility with the HLRC whenever new fields are added -> I'd rather stick with the LLRC here (especially when the next change to the defaults in this request is on the horizon with data streams).

**Review by DaveCTurner — APPROVED** [review]
Ok, thanks for the discussion. LGTM then :)

**Comment by original-brownbear** [comment]
Thanks David!

**Pull request merged**
