### PR TITLE
ILM MountSnapshotStep: use correct logic operator

### PR DESCRIPTION
**Pull request by andreidan**

### CODE REVIEW

**Review by dakrone — APPROVED** [review]
Whoops, good catch, is there any way we can test this so we don't break it again accidentally in the future?

**Comment by andreidan** [comment]
@elasticmachine update branch

**Comment by andreidan** [comment]
@elasticmachine update branch

**Comment by andreidan** [comment]
@dakrone good shout. added a couple of tests and fix some leftover assertions on this occasion

**Pull request merged**
