### PR TITLE
INGEST: Clean up Java8 Stream Usage

### PR DESCRIPTION
**Pull request by original-brownbear**
* GrokProcessor: Rationalize the loop over the map to save allocations and indirection
* IngestDocument: No need for the `Stream` -> loop magic for a simple `addAll()`
* KeyValueProcessor: Remove unnecessary Stream(s) usage when looping over a simple array 
   *Also, pre-build execution instead of redundantly evaluating null checks and string concatenation (for `fieldPathPrefix`)

### CODE REVIEW

**Comment by talevy** [comment]
@original-brownbear did you want to update this after changing the KeyValueProcessor?

**Comment by original-brownbear** [comment]
@talevy right, thanks for the ping :) Now this one is kinda trivial ... still why not clean this up while we can :)

**Comment by original-brownbear** [comment]
@talevy can you take another look here? :)

**Review by talevy — APPROVED** [review]
LGTM

**Pull request merged**
