### PR TITLE
Avoid creating new sets for individual wildcard expansions for authz

### PR DESCRIPTION
**Pull request by albertzaharovits**
This is a simple PR that avoids creating a hash set when expanding each wildcard in an indices expression.
This should slightly enhance performance.

Related https://github.com/elastic/elasticsearch/pull/76481/files

### CODE REVIEW

**Review by jeremythen — APPROVED** [review]

**Comment by albertzaharovits** [comment]
@elasticmachine merge master

**Comment by albertzaharovits** [comment]
@elasticmachine update branch

**Comment by albertzaharovits** [comment]
@elasticmachine test this

**Comment by albertzaharovits** [comment]
@elasticmachine test this please

**Comment by albertzaharovits** [comment]
ping @ywangd 
What do you think, is this still worth pursuing?

**Review by ywangd — APPROVED** [review]
LGTM

Previous experiences have shown that set creation and expansion can be expensive. So it's great that we can avoid them when possible. But I am curious about how well `List.add` and `List.remove` responds to this change as opposed to `List.addAll` and `List.removeAll`. It might be possible that the later forms are somewhat more performant. With `List.add`, there could be multiple grow in the process. `List.remove` is a linear scan, how would the performance change for an index expression like `*,-a*,-a*` (assuming both `*` and `a*` matches many indices). 

It would be great if we could have some benchmarks for above and related situations. I approved because I think for simple scenario such as single wildcard `*` or `a*`, it should definitely help because it basically replaces a Set expansion with List expansion which should be slightly faster and it also avoid copying the Set into List which is another allocation and iteration. This simple scenario is also likey to be quite popular in practice.

**Comment by albertzaharovits** [comment]
@ywangd 
> Previous experiences have shown that set creation and expansion can be expensive. So it's great that we can avoid them when possible. But I am curious about how well List.add and List.remove responds to this change as opposed to List.addAll and List.removeAll. It might be possible that the later forms are somewhat more performant.

For the "add" case, ie expressions containing wildcards without the leading minus, eg "a*", the `addAll` implementation of `ArrayList` (the type of \finalIndices`) is from `AbstractCollection#addAll`, which repeatedly calls `add` for every element of the argument collection.
Hence, in the current codebase, a new hash set is constructed, and then iterated over to call add for every item on the `finalIndices` array list.
I think the proposed change, to directly call add and avoid creating the intermediate hash set, is unequivocally better. I don't think we need a benchmark for this.

However, I think you have a point about the "remove" case. In this case, the `ArrayList#removeAll` is implemented with `ArrayList#batchRemove` , which in most cases is probably more performant. The batch remove implementation, uses the `contains` method on the argument collection, in order to remove all the elements in one pass and avoid the excessive shifting of the elements.

So, I think we should keep the old behavior for the "remove" case, use the proposed behavior for the "add" case, and no benchmarks. WDYT?

**Comment by ywangd** [comment]
> the `addAll` implementation of `ArrayList` (the type of `finalIndices`) is from `AbstractCollection#addAll`, which repeatedly calls `add` for every element of the argument collection.

No `ArrayList` has its own `addAll` implementation 
https://github.com/openjdk/jdk17u/blob/aa11a935373686bf5d67afb89368931c995824f6/src/java.base/share/classes/java/util/ArrayList.java#L669-L682

I think above should be more efficient than calling `add` repeatedly. But it is just my guess. The code should save on the single `grow` call, but it does allocate an array in the begining (`Object[] a = c.toArray()`). These nitty gritty details make it hard to tell whether the overall performance in our use case is better or not. That's why I suggested benchmarks.

**Comment by albertzaharovits** [comment]
Meh... you're right, I don't know how I missed the specialization for `ArrayList#addAll`.

Under these conditions, I'm actually reluctant to merge this PR, moreso without benchmarks.
I fear that after investing in benchmarking the results will be inconclusive because it all rests on the type of expresions to resolve.
I don't think it is worth spending that time with this PR in particular.

Hence closing. Thanks for your time, Yang!

**Pull request closed without merging**
