### PR TITLE
Separate out some node constructor object bindings that don't reference anything else

### PR DESCRIPTION
**Pull request by thecoop**
Separate out some objects that are not referenced by anything else into their own `Module`s for binding

### CODE REVIEW

**Comment by thecoop** [comment]
@elasticsearchmachine rerun elasticsearch-ci/part-2

**Review by ldematte — APPROVED** [review]
Looks cleaner to me. There is some change in the order of creation, which you never know if it may cause issues with dependency injection,  but that should be covered by tests.

**Comment by thecoop** [comment]
@elasticmachine update branch

**Comment by thecoop** [comment]
@elasticmachine update branch

**Pull request merged**
