### PR TITLE
[Test] Re-enable rest compat tests for service accounts

### PR DESCRIPTION
**Pull request by ywangd**
Tests for Get service accounts and Get service account tokens were
disabled for rest compat before backports. Now the backports are
complete, these tests can be re-enabled.

Relates: #75995, #76502

### CODE REVIEW

**Comment by ywangd** [comment]
@jkakavas I was unmuting a rest compat test for service account and noticed there was another one muted for the kibana service account change. So I unmuted for both of them.

**Review by jkakavas — APPROVED** [review]
LGMT ,thanks Yang I had totally missed it

**Comment by ywangd** [comment]
@elasticmachine update branch

**Comment by ywangd** [comment]
@elasticmachine run elasticsearch-ci/part-2-fips

**Pull request merged**
