### PR TITLE
[ESQL] Remove double "the" from median absolute deviation description

### PR DESCRIPTION
**Pull request by timgrein**
Just a small typo fix I found while reading the docs. `the the median absolute deviation` -> `the median absolute deviation`

### CODE REVIEW

**Review by craigtaverner — APPROVED** [review]
LGTM, although a search for ` the the ` yields many other places this mistake has been made.

**Comment by timgrein** [comment]
@elasticmachine update branch

**Comment by timgrein** [comment]
@elasticmachine update branch

**Comment by timgrein** [comment]
@elasticmachine update branch

**Pull request merged**
