### PR TITLE
Add ReindexTaskStateDoc tests

### PR DESCRIPTION
**Pull request by henningandersen**
Added xcontent serialization tests for ReindexTaskStateDoc

Related to #42612
Depends on #49278 (todo)

### CODE REVIEW

**Review by Tim-Brooks — APPROVED** [review]
LGTM

**Comment by henningandersen** [comment]
@elasticmachine update branch

**Comment by henningandersen** [comment]
@elasticmachine update branch

**Comment by henningandersen** [comment]
@elasticmachine update branch

**Comment by henningandersen** [comment]
@elasticmachine update branch

**Comment by henningandersen** [comment]
@elasticmachine update branch

**Pull request merged**
