### PR TITLE
Drop rewriting in date_histogram

### PR DESCRIPTION
**Pull request by nik9000**
The `date_histogram` aggregation had an optimization where it'd rewrite
`time_zones` who's offset from UTC is fixed across the entire index.
This rewrite is no longer needed after #56371 because we can tell that a
time zone is fixed lower down in the aggregation. So this removes it.

### CODE REVIEW

**Comment by nik9000** [comment]
I'm benchmarking this now just to be sure it doesn't change performance. It *shouldn't*.

**Comment by nik9000** [comment]
> I'm benchmarking this now just to be sure it doesn't change performance. It _shouldn't_.

The performance doesn't change with this PR.

**Review by not-napoleon — APPROVED** [review]
LGTM.  Love net negative code PRs :)

**Comment by polyfractal** [comment]
image

**Comment by nik9000** [comment]
Thanks for the review @not-napoleon! These were hard-fought negative lines, that is for sure!

**Pull request merged**
