### PR TITLE
Disk indicator change details

### PR DESCRIPTION
**Pull request by gmarouli**
Change the details of the disk indicator to provide an overview of the impact of the disk space health instead of a comprehensive list. For example:
```
"details": {
  "blocked_indices": 1,
  "red_nodes": 1,
  "yellow_nodes": 2,
  "unknown_nodes": 0,
  "green_nodes": 3
}
```

### CODE REVIEW

**Review by andreidan — APPROVED** [review]
LGTM, thanks Mary

Can you please add an example output to the PR description?

**Comment by masseyke** [comment]
I'm too late to this, but if we're getting rid of which nodes report which status, we probably also ought to include a count for `missing_nodes` right? Otherwise we're losing useful information we had previously.

**Comment by gmarouli** [comment]
@masseyke We count the nodes that have reported unknown. I would prefer to leave the missing nodes for now, because that shouldn't happen, apart from initialization. If it does, I would prefer to fix the bugs and not bother the user about it. What do you think about this approach?

**Comment by masseyke** [comment]
Oh we definitely need to fix the bugs (if they exist). I'm just worried we'll never know they exist. The more I think about it, the more information I realize we're losing with this change. For example right now we have no way of knowing which nodes were red vs yellow, right? And we have no way of knowing from the impacts which ones are reporting red for a blocked index vs reported disk usage. Maybe it would be best to have 2 sections in the details? Summary and nodes, or something like that.

**Comment by andreidan** [comment]
>For example right now we have no way of knowing which nodes were red vs yellow, right? 

I believe we'll see the nodes listed in the diagnosis right? 
ie. "Disk is full" for affected resources "node-1", "node-2" would mean these nodes are RED 
"Nodes are  running low on disk space" would mean the affected resources are YELLOW

**Comment by gmarouli** [comment]
In the diagnosis we list all the unhealthy data nodes, all unhealthy dedicated masters, all unhealthy "other" nodes. So all unhealthy nodes will be reported. 

But as @masseyke points out yellow and red status is not visible any more. Is this really necessary? What do you think it adds as information?

**Comment by andreidan** [comment]
I think the fact that we label nodes are RED/YELLOW w.r.t disk usage is an implementation detail. 
The diagnosis and impacts is what our users will consume IMO.

I'm also curious what would the RED/YELLOW status/node add when it comes to consuming the response and reacting to the API RED/YELLOW health status?

**Pull request merged**
