### PR TITLE
Add Debug Log for Successful Remote Cluster Connections

### PR DESCRIPTION
**Pull request by LoggingResearch**
This PR introduces a new debug log statement in the method. The added log statement will output a message when a connection is successfully established to all configured remote clusters.

This enhancement will provide valuable debugging information, making it easier to track and understand the connection status of remote clusters, especially in scenarios where network or cluster connectivity may be an issue.

### CODE REVIEW

**Comment by pxsalehi** [comment]
@elasticmachine test this please

**Comment by pxsalehi** [comment]
@LoggingResearch Thanks for your contribution. I think the changelog file is not necessary. Could you please remove it?

**Comment by LoggingResearch** [comment]
> @LoggingResearch Thanks for your contribution. I think the changelog file is not necessary. Could you please remove it?

Of course. I have deleted the changelog file.

**Review by DaveCTurner — CHANGES_REQUESTED** [review]
Not requesting any actual changes, I'm just marking this as `Request changes` to block merging it while we discuss internally.

**Comment by DaveCTurner** [comment]
Ok, thanks @LoggingResearch, we've discussed this internally and decided not to proceed with this change. It doesn't really help the debugging experience in practice, and (quoting the [contribution guidelines](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md#reviewing-and-accepting-your-contribution)) "the time we would need to spend on reviews would outweigh the benefits". While it may seem like a small thing to accept trivial changes like this one, we are keen not to set a precedent for doing so because of the nontrivial amount of review time these things could absorb in aggregate.

If you feel you have a specific need for this log message to troubleshoot a problem you're having then please head over to the [discussion forums](https://discuss.elastic.co/c/elastic-stack/elasticsearch/6) for help. Once we have understood the problems you're facing on the forums, we may reconsider this change and/or come up with a different solution.

**Pull request closed without merging**
