### PR TITLE
Close query cache on index service creation failure

### LINKED ISSUE #48186: Query cache is not cleaned up in case of an index creation failure
Creating an index with `index.mapper.dynamic` setting will fail in 7.x with something like
```
java.lang.IllegalArgumentException: Setting index.mapper.dynamic was removed after version 6.0.0
	at org.elasticsearch.index.mapper.MapperService.<init>(MapperService.java:165) ~[elasticsearch-7.4.0.jar:7.4.0]
	at org.elasticsearch.index.IndexService.<init>(IndexService.java:180) ~[elasticsearch-7.4.0.jar:7.4.0]
	at org.elasticsearch.index.IndexModule.newIndexService(IndexModule.java:411) ~[elasticsearch-7.4.0.jar:7.4.0]
	at org.elasticsearch.indices.IndicesService.createIndexService(IndicesService.java:550) ~[elasticsearch-7.4.0.jar:7.4.0]
	at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:499) ~[elasticsearch-7.4.0.jar:7.4.0]
```

But this seems to introduce a leak by creating the query cache before the index is created, and not cleaning the cache in case of failure. This manifests itself as `OptOutQueryCache` instances kept alive in heap, each of them referencing the non-existent, attempted-to-be-created-and-failed `indexName`.

### PR DESCRIPTION
**Pull request by DaveCTurner**
Today it is possible that we create the `QueryCache` and then fail to create
the owning `IndexService` and this means we do not close the `QueryCache`
again. This commit addresses that leak.

Fixes #48186

### CODE REVIEW

**Review by original-brownbear — APPROVED** [review]
LGTM :)

**Review by jimczi — COMMENTED** [review]
It looks like we can have another leak [here](https://github.com/elastic/elasticsearch/blob/36431bf1da968787be6b76fe0b166ea1762ca28f/server/src/main/java/org/elasticsearch/index/mapper/MapperService.java#L149) ? The index analyzers are created by the [IndexService](https://github.com/elastic/elasticsearch/blob/36431bf1da968787be6b76fe0b166ea1762ca28f/server/src/main/java/org/elasticsearch/index/IndexService.java#L182) so the build could move to the IndexModule ? These constructors are also not supposed to throw exceptions so it should also be possible to delay the `IllegalArgumentException` to `MapperService#merge` ? The exception should be removed in master since it is not applicable anymore so we probably don't need to spend too much time on it but I wonder if the model is safe here since we cannot protect all constructors with closeable object against random runtime exceptions ?

**Comment by DaveCTurner** [comment]
Thanks @jimczi, see ccdc259. I'm wondering about moving the creation of `MapperService`/`IndexFieldDataService`/`BitsetFilterCache`/`IndexCache` out as well, even though I don't think these leak meaningfully. Makes this change quite a bit larger and adds a bunch more constructor parameters. WDYT?

**Review by jimczi — APPROVED** [review]
LGTM

>  I'm wondering about moving the creation of MapperService/IndexFieldDataService/BitsetFilterCache/IndexCache out as well, even though I don't think these leak meaningfully. Makes this change quite a bit larger and adds a bunch more constructor parameters. WDYT?

Agreed, maybe add a comment explaining why we expect an exception here and we can clean up when we remove the `IllegalArgumentException` in MapperService on master ?

**Review by astefan — APPROVED** [review]
LGTM

**Comment by DaveCTurner** [comment]
@jimczi Are you sure this exception handling stops being necessary when the obvious `IllegalArgumentException` goes away? If so, it would be better just to handle that one case. But there's a lot of code here, some of it pluggable, so I would lean towards being defensive and keeping it.

**Comment by jimczi** [comment]
> Are you sure this exception handling stops being necessary when the obvious IllegalArgumentException goes away?

I am not sure, maybe this is the right protection but I wonder if throwing a runtime exception in a constructor is a bug or a feature and if all constructors that handle closeable objects should take care of these exceptions that are not declared. I am maybe overthinking this but we had the case in another constructor [recently](https://github.com/elastic/elasticsearch/pull/46258/files) so I am fine keeping the protection if this is something that we do everywhere ?

**Pull request merged**
