### PR TITLE
Add Snapshot Lifecycle Management

### PR DESCRIPTION
**Pull request by dakrone**
ILM has been included in Elasticsearch, which allows us to manage the lifecycle
of an index, however, this lifecycle management does not currently include
periodic snapshots of the index.

In order to provide a full replacement for other cluster periodic management
tools out there (such as Curator), this commit adds snapshot management to
Elasticsearch.

An example of creating a snapshot lifecycle policy:

```
PUT /_slm/policy/snapshot-every-day
{
  // Run this every day at 2:30am
  "schedule": "0 30 2 * * ?",

  // What the snapshot should be named, supporting date-math
  "name": "<production-snap-{now/d}>",

  // Which snapshot repository to use for the snapshot
  "repository": "my-s3-repository",

  // "config" is a map of all the options that the regular snapshot API takes
  "config": {
    "indices": ["foo-*", "important"],
    "ignore_unavailable": true,
    "include_global_state": false
  }
}
```

Policies can be created/updated, retrieved, deleted, or executed. Executing a 
snapshot policy immediately creates a snapshot based on the provided policy.

Relates to #38461

### CODE REVIEW

**Review by AthenaEryma — APPROVED** [review]
All of this has been reviewed piecemeal previously, but I've looked through this again and LGTM.

**Comment by fbaligand** [comment]
Does this feature allow to specify snapshot duration?
I mean: after this duration, the snapshot is automatically deleted by slm policy.

**Comment by gwbrown** [comment]
@fbaligand Not in this PR, but work to support that is in progress, see https://github.com/elastic/elasticsearch/issues/43663.

**Comment by fbaligand** [comment]
Great! Thanks for the info!

**Comment by dakrone** [comment]
@elasticmachine update branch

**Comment by fbaligand** [comment]
Great! 👍

**Pull request merged**
