### PR TITLE
Remove the query builder serialization from QueryShardException message

### LINKED ISSUE #48910: SearchShardFailure handling results in OOM
This is either the same or closely related to #27596 reported by @mattweber - which was hoped fixed in 6.1+ but was closed for lack of feedback in the end. It likely was not fixed.

* ES 6.6.2 (and 5.6.x)
* latest OpenJDK 1.8
* CentOS 7
* ES heap 31GB
* log-level: info
(This is at a client site and I don't have direct access to some details but can obtain if really needed.)

Problem is reproducible in various clusters, ranging from 8 to 50+ nodes, with thousands of shards. As long as a query fails (or more precisely is rejected) on each shard, e.g. because it trips _too_many_clauses_, an OOM will occur eventually when:
    `free_heap < 2 * (serialized_query_string_size) * num_shards`
where `serialized_query_string_size` is at least as big as the user-submitted query. 

So this is a case of the remedy being worse than the disease: in ES 6.6, the term**s** query now allows up to 64K terms (hence eventual clauses) by default, finally in line with the default terms-lookup limit, but if you write the query with (1K < separate _term_ clauses < 64K), it's the protective mechanism that kills the coordinating node (just as in v 5.6 with a terms query with >1K terms)

I have analyzed the heap dumps and can provide reports. The reason seems to be that `ShardSearchFailure` holds on to two error strings that contain the whole pretty-printed query. One inside the `cause [QueryShardException]` and the other in the `reason`. In our ES 5.6 test, these strings were about the same size as the user query; in the ES 6.6 test, a simple 4MB user query (on-disk-size) such as:
```
{
  "query": {
    "bool": {
      "should": [
        {
          "term": {
            "from.email.keyword": "foo1"
          }
        }, 
        {
          "term": {
            "from.email.keyword": "foo2"
          }
...
```
led to a 11.5 MB in-heap size for `cause` and `reason` (each)

2 *11.5MB * 1061 shards ~= 24 GB => OOM

Questions:

* if the query trips a global limit, can't this be short-circuited at the query-coordinating node before sending it out to all data nodes (at least if that's not a coordinating-only node?). If not, detect that one of the incoming failures is of a global-tripwire type and drop the rest? 
* trying to return more than the first x bytes of the user query is clearly not useful
* we have users and automated clients that can always submit (or programmatically generate!) queries with too many term clauses etc. 

I will next submit screenshots and reports from the heap analysis.

NOTE: I don't think the issue is specific to _logging_ the error, but to preparing a query response to return to the client. This contains at least one shard failure per index as seen in a response when the query is limited to a small number of indexes/shards and returns without OOM.

### LINKED ISSUE #51843: Don't serialize the entire query when query parsing fails
Today when the query parsing [fails](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/index/query/QueryShardContext.java#L315) on a shard, we create a `QueryShardException` that serializes the entire `QueryBuilder` in the message. All these exceptions are kept on a per-shard basis by the coordinating node so we except them to be light weight. For very large boolean queries (with lots of clauses that trip the `max_clause_count` for instance) this can cause memory pressure on the coordinating node since we don't de-duplicate exceptions coming from different shards.
The simplest fix would be to limit the size of the `QueryShardException`'s message by truncating the QueryBuilder serialization if it is above a certain threshold (1k ?).

### PR DESCRIPTION
**Pull request by jimczi**
QueryBuilders that throw exceptions on shards when building the Lucene query
returns the full serialization of the query builder in the exception message.
For large queries that fails to execute due to the max boolean clause, this means
that we keep a reference of these big messages for every shard that participate
in the request. In order to limit the memory needed to hold these query shard
exceptions in the coordinating node, this change removes the query builder
serialization from the shard exception. The query is known by the user so
there should be no need to repeat it on every shard exception. We could also
omit the entire stack trace for known bad request exception but it would deserve
a separate issue/pr.

Closes #51843
Closes #48910

### CODE REVIEW

**Review by pugnascotia — APPROVED** [review]

**Review by dnhatn — APPROVED** [review]
LGTM

**Comment by dnhatn** [comment]
@elasticmachine update branch

**Comment by altinp** [comment]
Would this also deal with cases when the long query is quoted in the Lucene `ParseException`, e.g. in case of [`too many boolean clauses`](https://github.com/apache/lucene-solr/blob/master/lucene/queryparser/src/java/org/apache/lucene/queryparser/classic/QueryParserBase.java#L118) in a `query_string` query? Lucene does:
```
    } catch (TooManyClauses tmc) {
      ParseException e = new ParseException("Cannot parse '" +query+ "': too many boolean clauses");
```
In such a case, the shard failure reason currently looks like the below and the specific reason of TooManyClauses, _boolean_, is (only) shown in `reason.caused_by.reason`:
```javascript
{
  "reason": {
    "type": "query_shard_exception",
    "reason": "Failed to parse query [(\"phrase 1\") OR (\"phrase 2\") OR ...  (\"phrase 1030\")]",
    "index_uuid": "ejeEEpE0QeCnyWgXOsXQrw",
    "index": "foo",
    "caused_by": {
      "type": "parse_exception",
      "reason": "parse_exception: Cannot parse '(\"phrase 1\") OR (\"phrase 2\") OR ... (\"phrase 1030\")': too many boolean clauses",
      "caused_by": {
        "type": "too_many_clauses",
        "reason": "too_many_clauses: maxClauseCount is set to 1024"
      }
    }
  }
}
```

**Comment by altinp** [comment]
also, would this be backported to ES 6?

**Comment by jimczi** [comment]
> Would this also deal with cases when the long query is quoted in the Lucene ParseException mesg, e.g. in case of too many boolean clauses in a query_string query? Lucene does:

No, this doesn't cover this case. We have another [issue](https://github.com/elastic/elasticsearch/issues/51403) opened for the `query_string` specifically.

> also, would this be backported to ES 6?

I don't think so, as you noticed there are other cases that we don't cover so this is more a bandage than a real fix.

**Pull request merged**
