### PR TITLE
Disable data tiers allocation deciders

### PR DESCRIPTION
**Pull request by tlrx**
When specific settings are set, we don't want existing data tiers allocation deciders to be enabled (otherwise we can't allocate shards to nodes with `index` or `search` roles when x-pack core module is present).

### CODE REVIEW

**Comment by tlrx** [comment]
@elasticmachine update branch because of #91553

**Review by idegtiarenko — APPROVED** [review]

**Review by Tim-Brooks — APPROVED** [review]
LGTM

**Review by henningandersen — APPROVED** [review]
LGTM.

**Comment by tlrx** [comment]
Thanks everyone

**Pull request merged**
