### PR TITLE
Make ActionListener.notifyOnce a little cheaper

### PR DESCRIPTION
**Pull request by original-brownbear**
This is used on the rather hot path now due to #97301, lets apply the optimization of saving one level of indirection here as well to make GC etc. a little cheaper on these.

### CODE REVIEW

**Review by DaveCTurner — COMMENTED** [review]
Hm subclassing `AtomicReference` feels like a bit of a hack to me, I'd kinda prefer us to use a `VarHandle` directly. If you have strong reasons not to do so, they deserve a comment.

**Comment by original-brownbear** [comment]
@DaveCTurner it's just less code and we have the thing package private here now anyway, so why blow up the code size when we won't be leaking that implementation detail? (we did the same thing elsewhere for private classes like `ReleaseOnce`)

**Comment by DaveCTurner** [comment]
Yeah I have the same feeling about `ReleaseOnce` :grin:

I'd rather be explicit even if it is a few more lines of code - these things are a little subtle already.

**Review by DaveCTurner — APPROVED** [review]
LGTM (for some value of "G" at least 😉)

**Comment by original-brownbear** [comment]
Thanks David :)

**Pull request merged**
