### PR TITLE
[ML] Set type on index requests in 6.x

### PR DESCRIPTION
**Pull request by droberts195**
This is a followup to #36796 that is only required
for 6.x.  The type must be specified in the index
request.  This is not necessary in 7.x, hence the
functionality works in the master build.

### CODE REVIEW

**Comment by droberts195** [comment]
Marked as `>non-issue` as it will be release noted as part of #36796

**Review by dimitris-athanasiou — APPROVED** [review]
LGTM

**Comment by droberts195** [comment]
run gradle build tests 2

**Comment by droberts195** [comment]
It seems that the changes of #36856 need to be merged into this PR before it will pass CI

**Comment by droberts195** [comment]
run default distro tests

**Comment by droberts195** [comment]
run gradle build tests 1

**Comment by droberts195** [comment]
run default distro tests

**Review by benwtrent — APPROVED** [review]
Simple enough :). Sorry for not doing this myself :)

**Comment by droberts195** [comment]
run gradle build tests 1

**Pull request merged**
