### PR TITLE
Rollup: Consolidate rollup cleanup for http tests

### PR DESCRIPTION
**Pull request by nik9000**
This moves the rollup cleanup code for http tests from the high level rest
client into the test framework and then entirely removes the rollup cleanup
code for http tests that lived in x-pack. This is nice because it
consolidates the cleanup into one spot, automatically invokes the cleanup
without the test having to know that it is "about rollup", and should allow
us to run the rollup docs tests.

Part of #34530

### CODE REVIEW

**Comment by nik9000** [comment]
Note to self and others: we skip the rollup tests using gradle configuration in `docs/build.gradle` starting with the comment "// Broken code snippet tests". I'd like to reenable those tests in a follow up.

**Comment by nik9000** [comment]
This issue tracks the rollup docs tests being disabled: #33319.

**Comment by nik9000** [comment]
@polyfractal, could you have a look at this when you get a chance? I think this is the last thing I need before I can fix the rollup docs tests.

**Review by polyfractal — APPROVED** [review]
LGTM!  Thanks for shuffling all this around @nik9000 :)

**Comment by nik9000** [comment]
Thanks for reviewing @polyfractal! I've merged to master and am running the backport tests now.

**Comment by nik9000** [comment]
All backported!

**Pull request merged**
