### PR TITLE
ML: changing automatic check_window calculation

### PR DESCRIPTION
**Pull request by benwtrent**
Removes unused ML message and changes how the default check_window is calculated. 

Relates to: https://github.com/elastic/elasticsearch/issues/35131

### CODE REVIEW

**Review by dimitris-athanasiou — APPROVED** [review]
LGTM

**Comment by dimitris-athanasiou** [comment]
Didn't check if docs mention anything about how we calculate the default. If they do we need to update that too.

**Comment by benwtrent** [comment]
@dimitris-athanasiou the docs just mention that we calculate a default, not how it is calculated.

**Comment by sophiec20** [comment]
Be good for the docs to mention how it is calculated. It's a useful detail.

**Comment by benwtrent** [comment]
@sophiec20 we don't really do that for our other default calculations. Though I can write something up if it is necessary.

**Comment by sophiec20** [comment]
> we don't really do that for our other default calculations.

We probably should.

**Pull request merged**
