### PR TITLE
Revert usage of SafeMustacheFactory in CustomMustacheFactory

### LINKED ISSUE #95421: Cannot change default delimiters in mustache search templates
### Elasticsearch Version

8.7.0

### Installed Plugins

_No response_

### Java Version

n/a

### OS Version

n/a

### Problem Description

If a search template changes the default mustache delimiter using `{{=`, rendering the template will fail with a `MustacheException`, `Disallowed: changing defaul delimiters`.

### Steps to Reproduce

```
PUT _scripts/test_search_template
{
  "script": {
    "lang": "mustache",
    "source": """
    {
      "query": {
        "match": {
          "content": "{{query_string}}"
        }
      },
      "highlight": {
        {{=<% %>=}}
        "pre_tags": [
          "{{{{"
        ],
        "post_tags": [
          "}}}}"
        ],
        <%={{ }}=%>
        "fields": {
          "content": {},
          "title": {}
        }
      }
    }
    """
  }
}
```

```
POST _render/template
{
  "id": "test_search_template",
  "params": {
    "query_string": "test"
  }
}
```

Result:
```
{
  "error": {
    "root_cause": [
      {
        "type": "script_exception",
        "reason": "Disallowed: changing defaul delimiters",
        "script_stack": [],
        "script": """
    {
      "query": {
        "match": {
          "content": "{{query_string}}"
        }
      },
      "highlight": {
        {{=<% %>=}}
        "pre_tags": [
          "{{{{"
        ],
        "post_tags": [
          "}}}}"
        ],
        <%={{ }}=%>
        "fields": {
          "content": {},
          "title": {}
        }
      }
    }
    """,
        "lang": "mustache"
      }
    ],
    "type": "script_exception",
    "reason": "Disallowed: changing defaul delimiters",
    "script_stack": [],
    "script": """
    {
      "query": {
        "match": {
          "content": "{{query_string}}"
        }
      },
      "highlight": {
        {{=<% %>=}}
        "pre_tags": [
          "{{{{"
        ],
        "post_tags": [
          "}}}}"
        ],
        <%={{ }}=%>
        "fields": {
          "content": {},
          "title": {}
        }
      }
    }
    """,
    "lang": "mustache",
    "caused_by": {
      "type": "mustache_exception",
      "reason": "Disallowed: changing defaul delimiters"
    }
  },
  "status": 400
}
```

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by stu-elastic**
`SafeMustacheFactory` does not allow changing the default delimiter, triggering "Disallowed: changing defaul delimiters" MustacheExceptions when attempted.

This is a partial revert of #92211.

Fixes: #95421

### CODE REVIEW

**Review by thecoop — APPROVED** [review]
LGTM.

What's the long-term plan for doing this change?

**Comment by stu-elastic** [comment]
> What's the long-term plan for doing this change?

It would have to be part of a security manager removal effort.

It seems we can do a change of the same shape by implementing a version of `SafeMustacheFactory` that does not disable default delimiters.

**Comment by rjernst** [comment]
> It seems we can do a change of the same shape by implementing a version of SafeMustacheFactory that does not disable default delimiters.

After a brief look at SafeMustacheFactory, it seems this would require copying the entire class since disabling the delimiter is set within a private method called from ctors. Perhaps we should look to change this upstream to be settable by subclasses.

**Comment by stu-elastic** [comment]
We'll follow up in https://github.com/elastic/elasticsearch/issues/95636

**Pull request merged**
