### PR TITLE
bump to 6.8.9

### PR DESCRIPTION
**Pull request by jakelandis**
_DO NOT MERGE UNTIL 6.8.8 is RELEASED_

### CODE REVIEW

**Review by bpintea — COMMENTED** [review]
LGTM

**Review by bpintea — APPROVED** [review]

**Comment by jakelandis** [comment]
@elasticmachine run elasticsearch-ci/1
@elasticmachine run elasticsearch-ci/1
@elasticmachine run elasticsearch-ci/1

**Comment by jakelandis** [comment]
@elasticmachine run elasticsearch-ci/2
@elasticmachine run elasticsearch-ci/elasticsearch-ci/default-distro
@elasticmachine run elasticsearch-ci/oss-distro-docs

**Comment by jakelandis** [comment]
@elasticmachine run elasticsearch-ci/

**Comment by jakelandis** [comment]
@elasticmachine run elasticsearch-ci/default-distro

**Comment by jakelandis** [comment]
@elasticmachine run elasticsearch-ci/1
@elasticmachine run elasticsearch-ci/2
@elasticmachine run elasticsearch-ci/default-distro
@elasticmachine run elasticsearch-ci/oss-distro-docs

**Comment by jakelandis** [comment]
@elasticmachine run elasticsearch-ci/1
@elasticmachine run elasticsearch-ci/2
@elasticmachine run elasticsearch-ci/oss-distro-docs

**Comment by jakelandis** [comment]
@elasticmachine run elasticsearch-ci/1
@elasticmachine run elasticsearch-ci/2
@elasticmachine run elasticsearch-ci/default-distro
@elasticmachine run elasticsearch-ci/oss-distro-docs

**Pull request merged**
