### PR TITLE
[ML] Add description to DF analytics

### PR DESCRIPTION
**Pull request by dimitris-athanasiou**
Adds `description` to data frame analytics.

### CODE REVIEW

**Review by przemekwitek — APPROVED** [review]
LGTM

**Review by szabosteve — APPROVED** [review]
LGTM. Thank you for adding the description of the `description` to the docs. :)

**Comment by dimitris-athanasiou** [comment]
@elasticmachine update branch

**Comment by dimitris-athanasiou** [comment]
@elasticmachine update branch

**Comment by dimitris-athanasiou** [comment]
@elasticmachine update branch

**Comment by dimitris-athanasiou** [comment]
run elasticsearch-ci/1

**Pull request merged**
