### PR TITLE
[Docs] Update cross-document links to Kibana Alerting docs

### PR DESCRIPTION
**Pull request by ymao1**
Some recent PRs have moved around some of the alerting docs within the Kibana docs, so some of the links need to be updated.

Relevant PRs:
* https://github.com/elastic/kibana/pull/101323
* https://github.com/elastic/kibana/pull/101498

### CODE REVIEW

**Review by gchaps — COMMENTED** [review]
The change looks good to me.  

There is a link in the second paragraph to "Alerting and Actions".  Should that be changed to "Alerting"?

**Comment by ymao1** [comment]
> The change looks good to me.
> 
> There is a link in the second paragraph to "Alerting and Actions". Should that be changed to "Alerting"?

@gchaps Updated!

**Review by gchaps — APPROVED** [review]
LGTM

**Review by lcawl — APPROVED** [review]
LGTM too, thanks!

**Pull request merged**
