### PR TITLE
Adjust encoding of Azure block IDs

### PR DESCRIPTION
**Pull request by DaveCTurner**
Today we represent block IDs sent to Azure using the URL-safe base-64
encoding. This makes sense: these IDs appear in URLs. It turns out that
Azure rejects this encoding for block IDs and instead demands that they
are represented using the regular, URL-unsafe, base-64 encoding instead,
then further wrapped in %-encoding to deal with the URL-unsafe
characters that inevitably result.

Relates #66489

### CODE REVIEW

**Comment by DaveCTurner** [comment]
Unfortunately I don't have a good way to test this against a real Azure account right now, and `./gradlew :plugins:repository-azure:check` doesn't seem to do anything useful for me so I'm just opening this as a draft for now.

**Comment by DaveCTurner** [comment]
> `./gradlew :plugins:repository-azure:check` doesn't seem to do anything useful for me

I worked this out, it's because I was running it on a machine that doesn't have Docker.

**Comment by DaveCTurner** [comment]
@elasticmachine please run elasticsearch-ci/2

**Review by fcofdez — APPROVED** [review]
LGTM. Thanks for fixing this @DaveCTurner! I've run the test suites a few times agains azure (using a really small multi-block size threshold) and it passed.

**Comment by DaveCTurner** [comment]
Merged despite unrelated CI failures, with approval from @jasontedor.

**Comment by idegtiarenko** [comment]
Hello @DaveCTurner , I believe according to the [merge commit](https://github.com/elastic/elasticsearch/commit/b3d5d32209f3ca5dfd5fb47ded6b9b55e034df45) this is not yet in any releases, is it?
Is it scheduled to be part of 7.11.2?

**Pull request merged**
