### PR TITLE
Add an index option recording the highest index version that has read an index

### PR DESCRIPTION
**Pull request by thecoop**
This option will be needed to decide index shard allocations in an updated https://github.com/elastic/elasticsearch/pull/102708

### CODE REVIEW

**Comment by thecoop** [comment]
This seems suspiciously simple - are there any other places this option needs to be updated?

**Review by rjernst — COMMENTED** [review]
Could we avoid storing this as an index setting? I think we have 2 levels, the index wide view (what was the index version the last time mappings were updated), and the shard level view (what index version was the last segment written to the shard). We'll definitely need this in cluster state, but could it be in index metadata?

**Comment by thecoop** [comment]
So we need to store both at the index level and the shard level? In the allocation decider, we'll then need to look at both, the index updated version and the shard updated version, to ensure we allocate correctly.

**Comment by thecoop** [comment]
IndexMetadata mappings version added in https://github.com/elastic/elasticsearch/pull/106748

**Comment by thecoop** [comment]
IndexShard implementation added in https://github.com/elastic/elasticsearch/pull/106779

**Pull request closed without merging**
