### PR TITLE
[DOCS] Correct `query` datatype in enrich policy definition

### LINKED ISSUE #56218: [DOC] Wrong Enrich policy "query" field description
The documentation at [Enrich policy definition](https://www.elastic.co/guide/en/elasticsearch/reference/current/enrich-policy-definition.html) describes the `query` field as `string` but it should be a valid query object instead.

### PR DESCRIPTION
**Pull request by jrodewig**
Corrects the datatype for the `query` property of an enrich policy
object. The `query` property is a query object, not a string.

Closes #56218

### CODE REVIEW

**Comment by jrodewig** [comment]
@martijnvg Do you mind taking a look at this when convenient? Thanks!

**Comment by jrodewig** [comment]
@elasticmachine run elasticsearch-ci/docs

**Review by martijnvg — APPROVED** [review]
Thanks @jrodewig! LGTM

**Comment by jrodewig** [comment]
### Backport commits
master 2f930f1
7.x c859fafcbdd
7.8 551c981a866
7.7 323f5dcc1ae
7.6 7414498fbe4f07ac33ae98613a757ed3bd9bc18b

**Pull request merged**
