### PR TITLE
fast_refresh setting for stateless

### PR DESCRIPTION
**Pull request by kingherc**
Introduces fast_refresh setting for indices, which is only allowed on stateless nodes.

Relates ES-6234

### CODE REVIEW

**Comment by kingherc** [comment]
@elasticmachine please run elasticsearch-ci/bwc

**Comment by kingherc** [comment]
@Tim-Brooks should we also change the default refresh interval value here as well?

**Comment by Tim-Brooks** [comment]
> should we also change the default refresh interval value here as well?

I don't think that is necessarily straightforward to do. Maybe we can branch on node type but it is messy to make an index setting rely on a node setting. We should have this default be it's own discussion.

**Review by Tim-Brooks — APPROVED** [review]
LGTM - Please add an actual PR description when merging including the fact that this setting is only allowed with stateless node types.

For example:

**Pull request merged**
