### PR TITLE
Optimize instance creation in LambdaBootstrap

### PR DESCRIPTION
**Pull request by uschindler**
This PR allows Hotspot's escape analysis to work correctly, preventing us from creating many instances stressing GC.

I was talking with @forax two days ago on the Jax 2017 Conference (where we had a panel discussion about Java 9). We discussed about Hotspot internals and the `LambdaMetaFactory`'s implementation details. He was very impressed about the work of @jdconrad and @rmuir (and my work) on implementing painless. FYI: He suggest that we should have a blog post about painless in regards to lambdas, but he was also impressed about the fact that we also use Java 9's indified string concats (as first scripting language in the wild). He also liked our PIC, MIC implementations. I will open a separate PR, because he suggested to invert the PIC guardWithTest chain to have the first receiver on top of all guards (as the first seen type is likely the one you see most often).

Also, the `MethodHandle#asType()` invokedynamic was in Rémi's original implementation of `LambdaMetaFactory` (and in reality it should do the same). So Rémi thinks that the recent changes in LambdaMetaFactory of Java 9 are buggy! We should really open a bug report with a test case: **@jdconrad your turn!!! Please do this!** The OpenJDK LambdaMetaFactory instead implements all the conversions for performance reasons for the case where you have a lambda only called once (happens very often in Java code). This does not affect us, as our lambdas are called on every document of an index :-) So the asType trick by @jdconrad is great and this is how it should look like - Congrats!

He was also able to explain to me, why the OpenJDK meta factory creates a static factory for the capturing lambdas - this is the reason for this PR. Of course, the current code is correct, and in an ideal world it should be like that, BUT: Hotspot is currently unable (even in Java 9) to look through a MethodHandles.findConstructor() method handle and allow escape analysis to work. Because our lambdas have only final fields and each instance does not allow to escape any shit from it, it can optimize away the object creation. But the code in hotspot only works if it sees a real chain of newinstance bytecode folowed up by invokespecial. For the method handle this is not the case, breaking the escape analysis and then it creates a new lambda capturing instance on heap! With the static factory this works, as the bytecode matches the pattern.

This PR will fix this by readding the static factory. I reused the same code that I used for newinvokedynamic, so we have no code duplication. I also removed a lot of "<init>" hardcoded strings.

### CODE REVIEW

**Comment by s1monw** [comment]
@elasticmachine ok to test

**Comment by uschindler** [comment]
Sorry, a too long line, I'll fix.

**Comment by uschindler** [comment]
This damn line length limitation is soooo stupid because it sometimes makes code unreadable! :-)

**Comment by uschindler** [comment]
Fixed in PR. Build should pass.

**Comment by nik9000** [comment]
@elasticmachine, test this please.

**Comment by jdconrad** [comment]
@uschindler Thank you for following up on this!  Really interesting information about the use of the factory method.  I'm happy to file a bug report, but I think this is already covered by (https://bugs.openjdk.java.net/browse/JDK-8174983).  Please let me know if I'm missing something here.  Looks like it's in progress now too which is great.

**Review by jdconrad — APPROVED** [review]
LGTM!  Let's commit as soon as we get a clean build.

**Comment by jdconrad** [comment]
Last failure was unrelated -- trying again (if it fails again I'll test locally against the painless tests).  @elasticmachine please test this.

**Comment by jdconrad** [comment]
This passes for me locally on both the latest builds of Java 8 and 9.  I'm going to go ahead and commit.  @uschindler Thanks again for continuing to fix up Painless!

**Comment by uschindler** [comment]
@s1monw Why did you revert one of the commits?

**Comment by s1monw** [comment]
@uschindler that might be confusing.. It's a reference from a PR that I deleted. I think you are fine.

**Comment by jdconrad** [comment]
@uschindler I just checked the log and it's still in master.  Looks like GitHub picked up on something incorrectly.

**Comment by uschindler** [comment]
> Thank you for following up on this! Really interesting information about the use of the factory method. I'm happy to file a bug report, but I think this is already covered by (https://bugs.openjdk.java.net/browse/JDK-8174983). Please let me know if I'm missing something here. Looks like it's in progress now too which is great.

Thanks! I will ask Rory to add a comment to refer to this issue. The problem we have seen with the LambdaMetaFactory will affect Scala soon! Rémi told me that Scala is planning to use LambdaMetaFactory, too, so he is very interested to fix bugs like this one. Especially if it implements the spec in a wrong way. But that is what the above issue is about.

> It's also nice to see your indified string concats get some recognition :)

:-) We should really write some blog post with some technical details about invoke dynamic about this. Rémi did not even know that painless is a scriptimg engine implemented from scratch and one that is only using invokedynamic for a lot of stuff.

**Comment by jdconrad** [comment]
@uschindler On the blog post -- seems like a good idea :).  How would you like to go about splitting it up to work on?

Also, received a suggestion that we possibly do something evil and use Unsafe to create the lambda classes to avoid issues with GC.  I was going to do some reading about the implications of the current implementation.  I'd be very interested in your thoughts on this specific issue.

**Comment by uschindler** [comment]
Hi @jdconrad 
I am happy to help you. You got not all information that I had with Rémi, so using Unsafe is not the best thing to do (and would be horrible, as it would require internal APIs). The anonymous classes are indeed handled differently, but this alone does not help. To make our meta factory as fast as OpenJDKs, we also need to add the `@ForceInline` annotation. But this is impossible for code outside of the JDK. Hotspot only respect this when it is in code created and running by the base module in a java package, not anywhere else. The same applies to annotations like `@Hidden`.
We should really use the offical LambdaFactory provided by the runtime, as this one has special atention. According to Rory, the bug you mentioned is going to be fixed soon (in progress).

**Comment by jdconrad** [comment]
@uschindler That's great to hear on the bug fix.  As soon as it's working again we can go back to the previous implementation.  I saw your report to Oracle get added to the bug, so thanks for  doing that.

**Comment by uschindler** [comment]
The fix version is currently "Java 10", so
Do you see GC issues. Rémi said, that static factory is important. If you still see GC issues, use LambdaMetaFactory only. No way to do different.
So question: Do you see GC issues with capturing lambdas? I don't thinks so! If the script ends the stuff is garbage collected anyways.

**Comment by jdconrad** [comment]
I don't seem them specifically.  I think I'm just the middle man between you and @rmuir :)

**Comment by uschindler** [comment]
I am discussing with him already. As said before, I was discussing the whole thing already. Anonymous classes are special, but the main difference is only that they are in no security context, they run without any extra checks. Also Unsafe can define them without any overhead while loading the class (e.g. it seems to not do some security and verifier checks, because it assumes that machine-generated code is correct by definition!) :-) So it is risky to inject "incorrect" bytecode into the JVM with Unsafe. We should not risk any issues when doing this.

So unless you see any issues in integration testing with large indexes, keep it like that. We should still push Oracle to fix the issue.

We already build the lambda classes in our own classloader that solely runs the script, so it is easy for GC to get rid of them - togteher with the script. If we would have problems with that, we should have seen issues already with the script class itsself!

**Comment by jdconrad** [comment]
@uschindler Thanks for all the information on this.  Every time you fix something in Painless I end up learning a lot :).  It's clear the ideal situation is Oracle will fix the bug and we revert to the code before.  I guess we may have to wait until Java 10 to do that.

**Comment by uschindler** [comment]
I was thinking about some "hack": We could make our LambdaBoostrap first delegate the call to LambdaMetaFactory (we just have to adjust the elements a bit and choose the "right" method of both: bridges and/or captures?). If this causes an IllegalArgumentException, we then call our own code and save the state of a "broken" marker to "true". Later calls will then delegate to our own code directly to save time...

But we should investigate this separately and I don't think we should do this unless we see GC issues.

**Comment by jdconrad** [comment]
I really like that idea if we do end up seeing GC issues!

**Comment by uschindler** [comment]
IMHO, if OpenJDK fixes the bug, we should stay with our invokedyns statement an do the bridge/no bridge decisions in our own bootstrap that adapts for delegation. This way we can separate the painless specific decisions how to create a callsite from the script bytecode generator. So we always create same invokedyn.

**Comment by jdconrad** [comment]
I;m happy to go with whatever you think is best for us on the lambda issues.

**Pull request merged**
