### PR TITLE
Fix typo in circuit breaker docs

### PR DESCRIPTION
**Pull request by leejones**
The previous description had a part that didn't fit and was probably from a copy/paste of the in flight requests description above.

### CODE REVIEW

**Comment by leejones** [comment]
Sorry, I signed the CLA but maybe it was too soon before I opened the PR?

**Review by cbuescher — APPROVED** [review]
@leejones sorry for just getting to this now, seems to have slipped through the cracks. The change makes sense to me, thanks a lot. I will merge this once running tests was successful.

**Comment by cbuescher** [comment]
test this please

**Comment by cbuescher** [comment]
test this please

**Pull request merged**
