### PR TITLE
Add ability to retrieve _id via fields option

### PR DESCRIPTION
**Pull request by cbuescher**
While looking into #75836 the idea came up to include retrieval of metadata fields like `_id` etc into the `fields` search option when the field is explicitely asked for. We would still continue to exclude any metadata field from matching patterns like "*", but they should be retrievable via an exact name or if you define an alias with a path to a metadata field like in #75836. 
This PR adds an implementation of a value fetcher that gets stored field values and replaces the current valueFetcher implementation in IdFieldMapper to return a value fetcher for the "_id" field instead. Excluding metadata fields when we are seeing a wildcard pattern is already implemented in FieldFetcher.
If this approach is okay I'd like to follow up with changing other metadata mappers like the ones for `_version`, `_seq_no`, `_ignore` etc that currently throw an UnsupportedOperationException.

### CODE REVIEW

**Review by romseygeek — APPROVED** [review]
LGTM. And will extend nicely to `_ignored` as well I think.

**Review by jtibshirani — COMMENTED** [review]
It's great this approach fits nicely into the `FieldFetcher` framework.

One thing I noticed: loading stored fields is quite expensive, and with this simple approach, we load them several times (once early in `FetchPhase` to grab `_id`, `_source`, etc. then here when fetching fields, potentially for a few different fields). We're usually pretty careful to load stored fields just once in the fetch phase. For context, when we load a single stored field from Lucene, we load and decompress a large block that may contain the entire document.

This might be an okay compromise, since loading `_id` and `_version` through 'fields' won't be too common, but wanted to raise it in case you had ideas for making this more efficient.

**Review by jtibshirani — APPROVED** [review]
Thanks for reminding me about #66256. Sounds good to me to merge as-is.

**Comment by cbuescher** [comment]
Thanks for the review, I will backport these changes to 7.x once I have opened and merged follow up PRs for other metadata fields to
avoid having to change with skip version on the bwc rest tests every time.

**Pull request merged**
