### PR TITLE
Allow comma separated ids in get enrich policy API

### PR DESCRIPTION
**Pull request by hub-cap**
This commit changes the GET REST api so it will accept an optional comma
separated list of enrich policy ids. This change also modifies the
behavior of the GET API in that it will not error if it is passed a bad
enrich id anymore, but will instead just return an empty list.

### CODE REVIEW

**Review by martijnvg — APPROVED** [review]
👍 We should also update the docs that the get policy api also accepts a comma-separated list of policy names.

**Comment by hub-cap** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by hub-cap** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by hub-cap** [comment]
@elasticmachine update branch

**Pull request merged**
