### PR TITLE
fix cluster health rest api wait_for_no_initializing_shards bug

### PR DESCRIPTION
**Pull request by weizijun**
fix RestClusterHealthAction, wait_for_no_initializing_shards's default param bug.

### CODE REVIEW

**Comment by dliappis** [comment]
Related to https://github.com/elastic/elasticsearch/pull/27489

**Comment by dnhatn** [comment]
@elasticmachine update branch

**Comment by dnhatn** [comment]
@weizijun The fix looks good to me. Can you extract a utility method that parses a request and add a randomized unit test using FakeRestRequest? Thank you for your contribution.

**Comment by ywelsch** [comment]
@weizijun are  you still interested in working on this?

**Comment by weizijun** [comment]
> @weizijun are you still interested in working on this?

yeah, I will commit unit test as soon as possible

**Comment by weizijun** [comment]
> @weizijun The fix looks good to me. Can you extract a utility method that parses a request and add a randomized unit test using FakeRestRequest? Thank you for your contribution.

@dnhatn @ywelsch done!

**Comment by dnhatn** [comment]
@elasticmachine update branch

**Comment by dnhatn** [comment]
@elasticmachine ok to test

**Review by dnhatn — APPROVED** [review]
LGTM. Thanks @weizijun.

**Pull request merged**
