### PR TITLE
[7.x] [DOCS] Add PIT to search after docs (#61593)

### PR DESCRIPTION
**Pull request by jrodewig**
Backports the following commits to 7.x:
 - [DOCS] Add PIT to search after docs (#61593)

### CODE REVIEW

**Comment by dnhatn** [comment]
@jrodewig FYI, PIT [hasn't backported ](https://github.com/elastic/elasticsearch/pull/61872)to 7.x yet.

**Comment by jrodewig** [comment]
@dnhatn Roger that. I was holding off until #61872 is backported. I'll revert this back to a draft until then.

**Comment by dnhatn** [comment]
@jrodewig I've backported the PIT.

@elasticmachine update branch

**Comment by dnhatn** [comment]
@elasticmachine update branch

**Comment by jrodewig** [comment]
Thanks @dnhatn. I'll go ahead and include the PIT API docs with this PR as well.

**Pull request merged**
