### PR TITLE
optimise content path

### PR DESCRIPTION
**Pull request by keshav08**
This PR optimises calls to ContentPath#pathAsText. Instead of iterating through the array I have made the array returning the path for the current index.

Addresses https://github.com/elastic/elasticsearch/issues/94544

### CODE REVIEW

**Comment by benwtrent** [comment]
@keshav08 please merge in the latest changes from main and resolve conflicts. Then we can run CI and see whats broken

**Comment by benwtrent** [comment]
> @benwtrent I have merged the latest changes. Can you guide me how to resolve this conflict?

I resolved for you, but you may need to dig a bit deeper on your string builder. `index` is the "next index for the path" as we set it on every new path element and then increment to capture the "end".

**Comment by benwtrent** [comment]
jenkins retest this please

**Comment by benwtrent** [comment]
@keshav08 there are two failures that need addressing:

For formatting:

```
./gradlew spotlessApply
```

Additionally, I think your change breaks tests.

Here is one that is failing now.
```
./gradlew ':rest-api-spec:yamlRestTest' --tests "org.elasticsearch.test.rest.ClientYamlTestSuiteIT.test {yaml=get/100_synthetic_source/flattened field}"
```

You can run the test with above command to see what is expected and what is failing.

Thanks!

**Comment by keshav08** [comment]
@benwtrent 
Will look into the test failures. What is this formatting for? And these 4 failing checks are all because of the breaking of test cases of have some other issue?

**Comment by benwtrent** [comment]
I chose just one example of a failing test that I know for sure is a result of this PR. Some of the other failures are the same test ran in a different way (BWC, with or without security, etc.).

I didn't look deeply at any other possible failures.

**Comment by cbuescher** [comment]
Sorry, just wanted to mention this PR addresses the same issue as https://github.com/elastic/elasticsearch/pull/98244 which precedes this and to me looks closer to getting to a state that is mergeable. I think that one should take precedence over this fix.

**Comment by cbuescher** [comment]
Should be adressed by #98244 now, so closing here.

**Pull request closed without merging**
