### PR TITLE
Fix BulkRejectionIT

### LINKED ISSUE #41363: Sporadic failure of BulkRejectionIT. testBulkRejectionAfterDynamicMappingUpdate
This test has failed three times in a single day so there might be something going on.

https://build-stats.elastic.co/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now%2Fd,mode:quick,to:now%2Fd))&_a=(columns:!(_source),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:kuery,query:'test%20:%20%22testBulkRejectionAfterDynamicMappingUpdate%22'),sort:!(time,desc))

https://scans.gradle.com/s/4hnxzwvhv2cly/tests/kyv2y2z3r4v7m-jic22iqysng2u

### PR DESCRIPTION
**Pull request by original-brownbear**
* Due to #40866 one of the two parallel bulk requests can randomly be
rejected outright when the write queue is full already, we can catch
this situation and ignore it since we can still have the rejection for
the dynamic mapping udate for the other reuqest and it's somewhat rare
to run into this anyway
* Closes #41363

### CODE REVIEW

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/1

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/1

**Review by dnhatn — APPROVED** [review]
LGTM

**Comment by original-brownbear** [comment]
thanks @dnhatn !

**Pull request merged**
