### PR TITLE
Fix Test Failure in testCorrectCountsForDoneShards

### LINKED ISSUE #60247: [CI] Failure in org.elasticsearch.snapshots.SnapshotStatusApisIT.testCorrectCountsForDoneShards
This failed 3 times over the last month on `master`.

```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.snapshots.SnapshotStatusApisIT.testCorrectCountsForDoneShards" -Dtests.seed=B18A21A71F791680 -Dtests.security.manager=true -Dtests.locale=ar-MA -Dtests.timezone=Europe/Prague -Druntime.java=11
```

fails as:

```
  2> REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.snapshots.SnapshotStatusApisIT.testCorrectCountsForDoneShards" -Dtests.seed=B18A21A71F791680 -Dtests.security.manager=true -Dtests.locale=ar-MA -Dtests.timezone=Europe/Prague -Druntime.java=11
  2> java.lang.AssertionError: 
    Expected: is <DONE>
         but: was <FAILURE>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.elasticsearch.snapshots.SnapshotStatusApisIT.testCorrectCountsForDoneShards(SnapshotStatusApisIT.java:231)
```

example failure: https://gradle-enterprise.elastic.co/s/fypm6bjxyhz5m/console-log/raw 

=> looking into it

### PR DESCRIPTION
**Pull request by original-brownbear**
Fixing the freak edge case where the node shard status request returns before
the node was able to send the state update request to master and update the cluster state.
Without this change, the snapshot shard status would report as `DONE` once the data node
has finished updating the shard in the cluster state.
If the data node then drops out of the cluster before the state has been updated, then
the status will jump to "FAILURE" because the master updates the state once the data node
leaves the cluster.

the alternative fix here would have been to just wait for the status via the cluster state instead of via the snapshot status APIs but I figured it's nicer to fix the status reporting to be consistent and not allow for a jump from `DONE` to `FAILURE` which is confusing and unexpected.

Closes #60247

### CODE REVIEW

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/packaging-sample-unix (Jenkins restart yesterday)

**Review by ywelsch — COMMENTED** [review]
I wonder if we should introduce a new stage that denotes master notification. This could also possibly help troubleshoot snapshots hanging in this stage. The  FINALIZE  stage does not really cover the situation described here (it's Javadocs say "Snapshot metadata is being written"), so if you want to go with the route chosen here, you will at least need to update the docs.

**Comment by original-brownbear** [comment]
@ywelsch thanks for taking a look, I opted for just updating the docs for now. Note that the state enum updated here is different from the one used by the `SnapshotShardsService` internally (that one uses org.elasticsearch.index.snapshots.IndexShardSnapshotStatus.Stage) ... I'm all for adding another state there and simplifying things that way but that's a bigger change and does not require adding a new state to the enum adjusted here.

Adding a new state to this enum would be a bit of a pain for BwC and probably just needlessly complicate things on the API level.

=> I'd open a follow up to add a new stage to `org.elasticsearch.index.snapshots.IndexShardSnapshotStatus.Stage` to simplify this (and use it to optimize state handling in `SnapshotShardsService`) in a follow up if that's ok?

**Review by ywelsch — APPROVED** [review]
LGTM

**Comment by original-brownbear** [comment]
Thanks Yannick!

**Pull request merged**
