### PR TITLE
[8.4] [Docs] Update remove processor with 'keep' option (#92836)

### PR DESCRIPTION
**Pull request by kilfoyle**
Backports the following commits to 8.4:
 - [Docs] Update remove processor with 'keep' option (#92836)

### CODE REVIEW

**Comment by kilfoyle** [comment]
@elasticmachine update branch

**Comment by kilfoyle** [comment]
@elasticmachine update branch

**Comment by kilfoyle** [comment]
@elasticmachine update branch

**Comment by abdonpijpelink** [comment]
@elasticmachine update branch

**Comment by abdonpijpelink** [comment]
Closing unmerged, as 8.4 is an old version.

**Pull request closed without merging**
