### PR TITLE
Fix wrong comment

### PR DESCRIPTION
**Pull request by daixiang0**
With note in `Shards & Replicas`, the docs in an index has max number rather that limitless.

Signed-off-by: Xiang Dai <764524258@qq.com>

### CODE REVIEW

**Comment by daixiang0** [comment]
any update?  @elastic/es-docs

**Comment by DaveCTurner** [comment]
Thanks for the PR @daixiang0. Arguably the original sentence is correct, although it is certainly a bit open to misinterpretation. There is a hard limit to how many documents you can have in each shard, but there is no limit to the number of shards you can have in an index, and this means that you can create an index to store as many documents as you want by giving it sufficiently many shards.

This documentation has been substantially reworked in https://github.com/elastic/elasticsearch/commit/66ce3f2b246a40bd27123269dbbfd0964b2f1d3b and the sentence you're correcting no longer exists in any maintained versions of the docs (≥6.8) so I think this has already been addressed.

**Comment by daixiang0** [comment]
@DaveCTurner hi, where can i know which version dose no longer maintained?

**Comment by jrodewig** [comment]
Hi @daixiang0,

Our product end of lifecycle is available here: https://www.elastic.co/support/eol
Check the *Elasticsearch* table under the *Maintained Until* column.

We ended maintenance of 6.2 with the release of 6.3.0.

**Pull request closed without merging**
