### PR TITLE
Move custom checkstyle rule implementations to build-conventions project

### PR DESCRIPTION
**Pull request by mark-vieira**
Since we bumped the target runtime version for `build-tools-internal` to Java 16, we've broken our IntelliJ checkstyle integration. SInce IntelliJ uses Java 11 as it's runtime we can't compile the Checkstyle rules with Java 16. This PR moves the rule implementations into `build-tools-conventions` which uses Java 11 as the target version. We've also committed the Checkstyle IDE configuration file into source control so that this no longer has to be manually configured by developers.

### CODE REVIEW

**Comment by pugnascotia** [comment]
It's great to have the IntelliJ config checked into source control. I struggled to get that to work before - does it work with a brand new checkout i.e first time that IntelliJ sees the project?

**Comment by breskeby** [comment]
nice! good to see manually steps been removed from the IDE setup

**Review by breskeby — APPROVED** [review]
lgtm

**Comment by mark-vieira** [comment]
> It's great to have the IntelliJ config checked into source control. I struggled to get that to work before - does it work with a brand new checkout i.e first time that IntelliJ sees the project?

Yep. I blew away my workspace and reimported and the plugin was configured as expected.

**Pull request merged**
