### PR TITLE
Fix NPE when CumulativeSum agg encounters null value/empty bucket

### LINKED ISSUE #27544: Cumilative Sum doesn't work with other pipeline aggregations
Cumulative sum aggregation returns an error when using it with other pipeline aggregations. This happens consistently with both bucket_scripts and derivatives.

Steps to Reproduce:

1. Index some Metricbeat data
2. Run the following query:

```
GET metricbeat-*/_search
{
  "size": 0,
  "query": {
    "range": {
      "@timestamp": {
        "gte": "now-15m/m",
        "lte": "now"
      }
    }
  },
  "aggs": {
    "timeseries": {
      "date_histogram": {
        "field": "@timestamp",
        "interval": "10s"
      },
      "aggs": {
        "maxTX": {
          "max": {
            "field": "system.network.out.bytes"
          }
        },
        "calculation": {
          "bucket_script": {
            "buckets_path": {
              "maxTX": "maxTX"
            }, 
            "script": { 
              "source": "params.maxTX" 
            }
          }
        },
        "cumsum": {
          "cumulative_sum": {
            "buckets_path": "calculation"
          }
        }
      }
    }
  }
}
```
3. Receive following response:

```
{
  "error": {
    "root_cause": [],
    "type": "search_phase_execution_exception",
    "reason": "",
    "phase": "fetch",
    "grouped": true,
    "failed_shards": [],
    "caused_by": {
      "type": "null_pointer_exception",
      "reason": null
    }
  },
  "status": 503
}
```

### PR DESCRIPTION
**Pull request by polyfractal**
If the cumulative sum agg encounters a null value, it's because the value is missing (like the first value from a derivative agg), the path is not valid, or the bucket in the path was empty.

Previously cusum would just explode on the null, but this changes it so we only increment the sum if the value is non-null and finite. This is safe because even if the cusum encounters all null or empty buckets, the cumulative sum is still zero (like how the sum agg returns zero even if all the docs were missing values)

I went ahead and tweaked AggregatorTestCase to allow testing pipelines, so that I could delete the IT test and reimplement it as AggTests.

I think this closes #27544

### CODE REVIEW

**Review by colings86 — APPROVED** [review]
LGTM

**Comment by polyfractal** [comment]
Jenkins, retest this please.

**Comment by polyfractal** [comment]
Jenkins, retest this please

**Comment by polyfractal** [comment]
Jenkins, run gradle build tests

**Pull request merged**
