### PR TITLE
HttpHandlers should return correct list of objects

### LINKED ISSUE #48978: [CI] AzureBlobStoreRepositoryTests.testIndicesDeletedFromRepository
Looks like a service unavailable but since the issue was raised before (#47120) I'm raising it for consistency.

CI https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+g1gc/483/
Scan: https://gradle-enterprise.elastic.co/s/2nryv35jtn7lo/tests/lgycqkw2bfw46-kysdm6ag7igo6

```
Caused by: com.microsoft.azure.storage.StorageException: Service Unavailable
	at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:87) ~[azure-storage-8.4.0.jar:?]
	at com.microsoft.azure.storage.core.StorageRequest.materializeException(StorageRequest.java:305) ~[azure-storage-8.4.0.jar:?]
	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:196) ~[azure-storage-8.4.0.jar:?]
	at com.microsoft.azure.storage.blob.CloudBlockBlob.uploadFullBlob(CloudBlockBlob.java:1035) ~[azure-storage-8.4.0.jar:?]
	at com.microsoft.azure.storage.blob.CloudBlockBlob.upload(CloudBlockBlob.java:864) ~[azure-storage-8.4.0.jar:?]
	at com.microsoft.azure.storage.blob.CloudBlockBlob.upload(CloudBlockBlob.java:743) ~[azure-storage-8.4.0.jar:?]
	at org.elasticsearch.repositories.azure.AzureStorageService.lambda$writeBlob$15(AzureStorageService.java:333) ~[main/:?]
	at org.elasticsearch.repositories.azure.SocketAccess.lambda$doPrivilegedVoidException$0(SocketAccess.java:69) ~[main/:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at org.elasticsearch.repositories.azure.SocketAccess.doPrivilegedVoidException(SocketAccess.java:68) ~[main/:?]
	at org.elasticsearch.repositories.azure.AzureStorageService.writeBlob(AzureStorageService.java:332) ~[main/:?]
	at org.elasticsearch.repositories.azure.AzureBlobStore.writeBlob(AzureBlobStore.java:119) ~[main/:?]
	at org.elasticsearch.repositories.azure.AzureBlobContainer.writeBlob(AzureBlobContainer.java:101) ~[main/:?]
	at org.elasticsearch.repositories.blobstore.ChecksumBlobStoreFormat.lambda$write$1(ChecksumBlobStoreFormat.java:1
```

### PR DESCRIPTION
**Pull request by tlrx**
This pull request fixes the server side logic of "List Objects" operations of Azure and S3 fixtures. Until today, the fixtures were returning a "flat" view of stored objects and were not correctly handling the `delimiter` parameter. This causes some objects listing to be wrongly interpreted by the snapshot deletion logic in Elasticsearch which relies on the ability to list child containers of BlobContainer (#42653) to correctly delete stale indices.

As a consequence, the blobs were not correctly deleted from the emulated storage service and stayed in heap until they got garbage collected, causing CI failures like #48978 where OOM errors happen in the test JVM (but it took me a while to figure this out...).

This pull request fixes the server side logic of Azure and S3 fixture when listing objects so that it now return correct common blob prefixes as expected by the snapshot deletion process. It also adds an after-test check to ensure that tests leave the repository empty (besides the root index files).

Closes #48978

### CODE REVIEW

**Review by original-brownbear — COMMENTED** [review]
This looks good I think. Could we add a test for S3 and Azure where we make sure that `BlobContainer` listing child directories and listing all children never picks up blobs from nested "directories" to make sure this continues to work?

**Comment by tlrx** [comment]
> Could we add a test for S3 and Azure where we make sure that `BlobContainer` listing child directories and listing all children never picks up blobs from nested "directories" to make sure this continues to work?

That sounds like the responsibility of `ESBlobStoreContainerTestCase` suite? Where we could maybe get rid of `AzureStorageServiceMock` to also rely on HTTP handlers? Or maybe you were thinking of something different?

**Comment by original-brownbear** [comment]
> That sounds like the responsibility of ESBlobStoreContainerTestCase suite? Where we could maybe get rid of AzureStorageServiceMock to also rely on HTTP handlers?

Jup exactly, that's what we should do. I guess we even have an issue that is asking for that https://github.com/elastic/elasticsearch/issues/30424 :)

**Comment by tlrx** [comment]
@original-brownbear Would it be acceptable to do this as a follow up pr?

**Review by original-brownbear — APPROVED** [review]
LGTM, yea ofc follow-up is just fine :) Let's just do it at some point IMO.

**Comment by tlrx** [comment]
Thanks @original-brownbear !

**Pull request merged**
