### PR TITLE
Add RandomAccessInput#length to SeekTrackingDirectoryWrapper

### PR DESCRIPTION
**Pull request by iverase**
Fix compiling error after adding a new method to RandomAccessInput interface.

### CODE REVIEW

**Review by romseygeek — APPROVED** [review]
LGTM

**Comment by iverase** [comment]
@elasticsearchmachine run elasticsearch-ci/part-1

**Comment by iverase** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by iverase** [comment]
@elasticsearchmachine run elasticsearch-ci/part-1

**Pull request merged**
