### PR TITLE
Correctly pre-size HashMaps

### PR DESCRIPTION
**Pull request by arteam**
The HashMap(int) constructor the _capacity_ of the map rather than the _size_. Unfortunately, the HashMap requires N/0.75 capacity to hold N elements. So, if we call `new HashMap(N)` to hold N elements, the map will be too small and need to be resized/rehashed midway. We add a new method `Maps.newMapWithExpectedSize` which calculates the correct capacity
for the specified expected size

See

* https://stackoverflow.com/questions/52671362/why-does-hashmap-resize-again-when-specifying-a-precise-capacity
* https://stackoverflow.com/questions/30220820/difference-between-new-hashmapint-and-guava-maps-newhashmapwithexpectedsizein
* https://bugs.openjdk.java.net/browse/JDK-8186958

### CODE REVIEW

**Comment by arteam** [comment]
@elasticmachine update branch

**Comment by arteam** [comment]
@elasticmachine update branch

**Comment by grcevski** [comment]
I wonder if we can split this PR. Github doesn't want to render it for me :).

**Comment by arteam** [comment]
I've pushed the `Maps.newLinkedHashMapWithExpectedSize` change out, let's see if the diff becomes more readable.

**Review by ChrisHegarty — APPROVED** [review]
LGTM

**Comment by arteam** [comment]
@elasticmachine update branch

**Comment by arteam** [comment]
@elasticmachine update branch

**Review by grcevski — APPROVED** [review]
LGTM!

**Comment by arteam** [comment]
Thank you both!

**Pull request merged**
