### PR TITLE
Adding two missing entries to the deprecation info api

### PR DESCRIPTION
**Pull request by masseyke**
Adding indices.lifecycle.step.master_timeout and xpack.eql.enabled to the deprecation info API. These two checks
were also added to the 7.16 line in #80233.

### CODE REVIEW

**Comment by masseyke** [comment]
@elasticmachine update branch

**Review by dakrone — COMMENTED** [review]
LGTM, but since this is still a draft are there other changes coming?

**Comment by masseyke** [comment]
> LGTM, but since this is still a draft are there other changes coming?

@dakrone no sorry that was a mistake!

**Comment by masseyke** [comment]
@elasticmachine run elasticsearch-ci/part-2

**Review by dakrone — APPROVED** [review]

**Pull request merged**
