### PR TITLE
PluginManager: Move plugin manager into its own project

### PR DESCRIPTION
**Pull request by spinscale**
The plugin manager now is its own subproject and not part
of the core anymore and will be the base for further refactoring.

Requires some changes in the packaging to include the jar as
well as some minor test modifications.

### CODE REVIEW

**Comment by dadoonet** [comment]
Would this make sense to put it within `plugins` module?
I think we will end up with many modules and we should try to keep them organized.

Or may be put it under a new `modules` module. So we have:

```
core
modules
plugins
distribution
...
```

WDYT?

**Comment by rmuir** [comment]
I dont think we should commit any packaging changes until builds are green again.

**Comment by spinscale** [comment]
@dadoonet I dont know if we are going to have more. Does it make sense to wait and only create something like that, once we add more modules?

**Comment by dadoonet** [comment]
Moving stuff in git is easy so I guess we can wait.
Changing the groupId has more implications IMO but still doable.

**Comment by spinscale** [comment]
so I have spent some more time with this PR and keep thinking, that this is not the route to go, given that the next step is to merge the `PluginManagerCliParser` with the `BootstrapCliParser`, so that we can run

```bash
bin/elasticsearch plugin install elasticsearch/marvel/latest
```

With this PR in place, we would need to load the `PluginManagerCliParser` dynamically in the `core` project, without actually being sure that it is there - as this would requite the `plugin-manager` jar to be in the `lib/` directory and we might need to fail gracefully, if it is not.

Even though I see sense in modularization, I do not see sense to do this for the plugin manager, if we have those kind of circular dependencies. The current workaround is using `Class.forName()`to load the `PluginManagerCliParser`  in my local branch, which I really dislike.

An interesting workaround for this problem could be the possibility to register custom commands on startup in `core`, so that one could register commands like `bin/elasticsearch whatever` - however this is currently not supported and requires some more work. In addition this would also require us to change the CLI parser to support the construct of not only commands (like `whatever`, but also some kind of sub commands (like `plugin install ...`), because right now the CliTool is limited to only accept one word at the top-level and then expect parameters. I will try to come up with something.

/cc @clintongormley

**Comment by spinscale** [comment]
closing and postponing for now as this requires more work on the testing side

**Pull request closed without merging**
