### PR TITLE
Replace some ActionListener.wrap with more efficient delegateFailureAndWrap in ml module

### PR DESCRIPTION
**Pull request by original-brownbear**
There's loads of these spots in the ml codebase. We can save some code, memory and improve readability here by moving to the new delegateFailureAndWrap. This should not have any functional changes.

### CODE REVIEW

**Comment by davidkyle** [comment]
@original-brownbear the change looks good, can you resolve the conflicts please

**Comment by original-brownbear** [comment]
done! @davidkyle :)

**Review by davidkyle — APPROVED** [review]
LGTM

Thanks @original-brownbear

**Comment by original-brownbear** [comment]
npnp + thanks David!

**Pull request merged**
