### PR TITLE
Remove Log4j 1.2 API as a dependency

### PR DESCRIPTION
**Pull request by jasontedor**
We had this as a dependency for legacy dependencies that still needed the Log4j 1.2 API. This appears to no longer be necessary, so this commit removes this artifact as a dependency.

To remove this dependency, we had to fix a few places where we were accidentally relying on Log4j 1.2 instead of Log4j 2 (easy to do, since both APIs were on the compile-time classpath).

Finally, we can remove our custom Netty logger factory. This was needed when we were on Log4j 1.2 and handled logging in our own unique way. When we migrated to Log4j 2 we could have dropped this dependency. However, even then Netty would still pick up Log4j 1.2 since it was on the classpath, thus the advantage to removing this as a dependency now.

Relates #42591

### CODE REVIEW

**Review by original-brownbear — APPROVED** [review]
Sweet :) => LGTM (assuming CI likes it)

**Comment by original-brownbear** [comment]
Looks like we need a few more recommit exclusions here:

```
'javax.servlet.ServletContextEvent'). Please fix the classpath!
12:42:09 WARNING: Class 'javax.servlet.ServletContextEvent' cannot be loaded (while looking up details about referenced class 'javax.servlet.ServletContextEvent'). Please fix the classpath!
12:42:09 WARNING: Class 'javax.servlet.ServletContextListener' cannot be loaded (while looking up details about referenced class 'org.apache.commons.logging.impl.ServletContextCleaner'). Please fix the classpath!
12:42:09 ==end of forbidden APIs==
12:42:09 Missing classes:
12:42:09   * org.apache.log4j.Category
12:42:09   * org.apache.log4j.Level
12:42:09   * org.apache.log4j.Logger
12:42:09   * org.apache.log4j.Priority
```

**Review by pgomulka — APPROVED** [review]
I just left a minor comment, but it LGTM anyway

**Review by rjernst — APPROVED** [review]
LGTM. Note that the fact you needed to add the log4j license in so many places seems broken. We shouldn't be checking licenses in each plugin for transitive dependencies pulled in by server. I opened https://github.com/elastic/elasticsearch/issues/42721 to track that.

**Comment by rjernst** [comment]
I see now why you had to add the log4j license files, since you had to add log4j 1.2 api to the plugins in question. So I've closed #42721.

**Pull request merged**
