### PR TITLE
Remove cache key renderer argument from IndicesRequestCache

### LINKED ISSUE #55837: Remove cacheKeyRenderer from IndicesRequestCache
IndicesRequestCache has [this comment](https://github.com/elastic/elasticsearch/blob/f8413eb07ae200fc49732f2343008affdc93ac62/server/src/main/java/org/elasticsearch/indices/IndicesRequestCache.java#L117-L121):

```
    // NORELEASE The cacheKeyRenderer has been added in order to debug
    // https://github.com/elastic/elasticsearch/issues/32827, it should be
    // removed when this issue is solved
```

Since #32827 is closed, can we drop the `cacheKeyRenderer` argument (or remove the comment if we've decided to keep it permanently)?

### PR DESCRIPTION
**Pull request by javanna**
In the context of of a recurring test failure tracked by #32827, we added trace logging and an extra cache key renderer argument to IndicesRequestCache#getOrCompute (see #39475 and #34180).

We addressed the issue with #54071, but the extra argument was left behind, with a NORELEASE comment saying it should be removed.

With this commit, we remove the extra cache key rendered argument and the corresponding log lines which are not so useful without it.

Closes #55837

### CODE REVIEW

**Comment by javanna** [comment]
run elasticsearch-ci/bwc

**Comment by javanna** [comment]
run elasticsearch-ci/default-distro

**Review by jimczi — APPROVED** [review]
LGTM

**Comment by javanna** [comment]
thanks @jimczi !

**Pull request merged**
