### PR TITLE
Rename the RenderSearchTemplateAction to be a cluster level action

### PR DESCRIPTION
**Pull request by jaymode**
The RenderSearchTemplateAction is currently a "indices" action, but the action does not really apply to
indices, it is more of a general action that is used to validate the search template. With our current
categorization of actions, `cluster:` and `indices:`, `cluster:` is a more appropriate type as this action
is not associated with indices. The classes are also moved to a cluster package.

### CODE REVIEW

**Comment by clintongormley** [comment]
@colings86 thoughts?

**Comment by colings86** [comment]
Sounds good to me

**Comment by s1monw** [comment]
@jaymode can I merge this?

**Comment by s1monw** [comment]
LGTM

**Pull request merged**
