### PR TITLE
ValuesSource refactoring: Wire up ExtendedStats aggregation

### PR DESCRIPTION
**Pull request by csoulios**
Wire up ExtendedStats aggregation for #42949

### CODE REVIEW

**Review by not-napoleon — APPROVED** [review]
LGTM.  We've seen that CI failure on a few PRs, and I think Tal pulled in the fix from master.  If you merge the feature branch, it should go to green.

**Comment by csoulios** [comment]
@elasticmachine run elasticsearch-ci/bwc
@elasticmachine run elasticsearch-ci/default-distro

**Comment by csoulios** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by csoulios** [comment]
@elasticmachine run elasticsearch-ci/bwc
@elasticmachine run elasticsearch-ci/default-distro

**Pull request merged**
