### PR TITLE
Format a selection of server snapshot dirs

### PR DESCRIPTION
**Pull request by pugnascotia**
Opt-in directories related to snapshots and repositories under
`./server` for formatting with Spotless.

### CODE REVIEW

**Comment by DaveCTurner** [comment]
For team discussion: I was doing some work in this area recently and found all the long lists of arguments to various things to be hard to work with. We'll be spotlessifying this eventually so I asked Rory whether we could opt-in some specific packages now. What do we think?

**Comment by henningandersen** [comment]
I think I would prefer to either format all of the server module or wait until we make the cut-over to spotless formatting everything. It is difficult already that we have some modules with and some without spotless, but then having mixed modules too I worry will be more disturbing than helpful.

**Comment by DaveCTurner** [comment]
I'm not sure I see the distinction between module boundaries and package boundaries in this context -- at least for large package sets like snapshots that would be separate modules if it weren't for a relatively small collection of interdependencies with the rest of `server`, and which have relatively well-defined teams working on them.

I also worry about the scale of a big-bang reformat of all of `server`, which will affect a large number of in-flight PRs. There simply won't be a good time to do it. Working more incrementally will let us pick a convenient moment for each area.

**Comment by henningandersen** [comment]
We discussed this as a team based and decided we want to move ahead with this. Additionally, this does open up the possibility of more incrementally adding files to spotless, something we may want to use for backporting when the newer branch is either totally formatted or has formatting of more files.

**Comment by DaveCTurner** [comment]
I've refreshed this PR by merging in master ignoring conflicts (1e32e87) then reverting all files except the spotless config (15ff4bc), then reformatting all the things again (f7cd974), and finally fixing one over-long string (3939d99).

**Review by original-brownbear — APPROVED** [review]
Thanks David+Rory, I'm fine with merging this :)

**Pull request merged**
