### PR TITLE
[Fix] Immediately clear the filter cache when requested

### LINKED ISSUE #8285: Immediately clear the filter cache when requested
Currently, a `/_cache/clear?filter` request marks entries to be invalidated, but they only get cleared after a maximum delay of `cleanedInterval`.

We should force the cache to be cleaned in these conditions, as was done for the fielddata cache in https://github.com/elasticsearch/elasticsearch/commit/65ce5acfb41b4abd0c527aa0e870c2a1076d76cd

### PR DESCRIPTION
**Pull request by ghost**
Fixes #8285

@dakrone splitting up my previous pull request #10178 as requested.

### CODE REVIEW

**Comment by clintongormley** [comment]
@jpountz is this change still relevant given the reworking of queries/filters in master?

**Comment by kimchy** [comment]
this fix is problematic, since it clears all the filters on the node level, not only the ones relating to a this specific index. Also, the reference to #8285 is incorrect, as its a different case of problem, its not the fact that `cleanup` is not called on the guava cache.

We can make `IndicesFilterCache#ReaderCleaner` a instance variable and explicitly call something like "forceCleanup" (synchronized) that calls the the parts of the run method (without scheduling another run) that ends up cleaning the respective parts relating to that index.

**Comment by jpountz** [comment]
@clintongormley If we move to the Lucene filter cache, this should not be necessary since it has synchronous removals.

**Comment by clintongormley** [comment]
thanks @jpountz.

thanks for the PR @Myll but I think we won't fix it as the whole mechanism is changing with Lucene 5

**Pull request closed without merging**
