### PR TITLE
Add a dedicated threadpool for node connections

### PR DESCRIPTION
**Pull request by PnPie**
Add a new dedicated threadpool for establishing node connections, instead of using management thread pool as it's a small and important threadpool used by many other operations.

Relates to #29023

### CODE REVIEW

**Comment by PnPie** [comment]
Hi @javanna I added a test to check using the new threadpool.

**Comment by javanna** [comment]
thanks @PnPie !  @elastic/es-core-infra this is ready for review

**Review by DaveCTurner — COMMENTED** [review]
I didn't realise this was open so I opened 
#31546. This looks better, however, so I closed it again. I left a couple of comments. The only other thing is that there are docs to update - see https://github.com/elastic/elasticsearch/pull/31546/files#diff-7bb7428e5b1712bb358a0bb44321d9a6

**Comment by DaveCTurner** [comment]
This looks ok to me but I'm not intimately familiar with this area of the code so I'd rather not give it a final LGTM. Could someone from @elastic/es-core-infra take a look at this please?

**Comment by danielmitterdorfer** [comment]
Hi @PnPie! Thank you very much for your pull request and the work that you put into it. I am sorry that it fell through the cracks.

We recently implemented a change in https://github.com/elastic/elasticsearch/pull/35144 that will enable us to open connections asynchronously. This means that there is no need for a dedicated threadpool anymore which in turn makes this PR, unfortunately, obsolete. Therefore, I hope that you understand I close this PR without merging.

**Comment by PnPie** [comment]
Thanks @danielmitterdorfer for replying and explaning the context, so that I can also have a look at the related changes :)

**Comment by danielmitterdorfer** [comment]
You are welcome and thanks for your understanding. Glad that you find the additional information helpful. :)

**Pull request closed without merging**
