### PR TITLE
Add support for S3 intelligent tiering (#38836)

### PR DESCRIPTION
**Pull request by pedrostil**
Related to #38836

### CODE REVIEW

**Comment by original-brownbear** [comment]
Jenkins test this

**Comment by original-brownbear** [comment]
@pedrostil could you fix the dependency SHA files, please? Just run `./gradlew updateSHAs`  and commit+push the result.

**Comment by pedrostil** [comment]
Done @original-brownbear thanks for reviewing

**Comment by original-brownbear** [comment]
Jenkins test this

np + thanks @pedrostil

**Review by original-brownbear — APPROVED** [review]
LGTM thanks @pedrostil!

**Comment by original-brownbear** [comment]
@ywelsch maybe take a look here, since you had some apprehension about it in the issue?

**Comment by ywelsch** [comment]
Note that we'll need to actually test this (not just a unit test) before merging.

**Comment by pedrostil** [comment]
@ywelsch makes sense. I couldn't find any test other than these unit tests that tests the storage class. Can you elaborate on what do you want to test and how? Do you want to validate that the S3BlobStore works with intelligent tiering against a real S3 bucket? Should we also add tests for the other storage classes?

Unlike Glacier, intelligent tiering doesn't change the behaviour, as it will be either Standard or IA, which we already support.

**Comment by ywelsch** [comment]
@pedrostil I meant running a manual test against a real S3 bucket, just to make sure that it actually works (i.e. take snapshot, and then check on AWS UI that files have the appropriate storage class).

**Comment by pedrostil** [comment]
@ywelsch I can do that. Can you point me to how to install the S3 repository plugin when running from source?

**Comment by ywelsch** [comment]
@pedrostil you can build the Elasticsearch distribution with `./gradlew distribution:archives:linux-tar:assemble` (and similar for the other distributions in that folder). The resulting distribution will then be in `distribution/archives/linux-tar/build/distributions`.

You then also have to build the `repository-s3` plugin with `./gradlew plugins:repository-s3:assemble` which gives you the plugin in `plugins/repository-s3/build/distributions/`.

**Comment by pedrostil** [comment]
Thanks for the help @ywelsch, I did a snapshot and all S3 objects are created using the intelligent tiering storage class.

**Review by ywelsch — APPROVED** [review]
Thank you @pedrostil. LGTM

**Comment by original-brownbear** [comment]
@pedrostil @ywelsch thanks! I'll merge this :)

**Pull request merged**
