### PR TITLE
REST tests for variable width historam

### PR DESCRIPTION
**Pull request by nik9000**
This expands on the super basic REST tests for variable width histogram
with some ever so slightly less basic tests. They are still pretty
basic, but they do a good job of making sure that we don't break
backwards compatibility with the API.

### CODE REVIEW

**Comment by nik9000** [comment]
@elasticmachine, update branch

**Comment by nik9000** [comment]
@elasticmachine update branch

**Comment by nik9000** [comment]
@elasticmachine update branch

**Review by not-napoleon — APPROVED** [review]
LGTM

**Pull request merged**
