### PR TITLE
Whitelist Class in painless and document it

### LINKED ISSUE #20263: Support println in Painless
Without a full debugger, the fallback approach for Painless is currently to throw exceptions with messages that the scripting engine has to catch. This can be limiting without planning (maintaining a string and throwing at the end) ahead since it's one-and-done.

It would be convenient to support `println` as a pass-thru to `System.out` (if not a the internal logger, but that touches the file system and therefore may need extra permissions, which creates different risks).

### PR DESCRIPTION
**Pull request by nik9000**
This whitelists `java.lang.Class`, `Class#getName` and
`Class#getSimpleName` and documents using `getName` to find the
class you are working with.

Closes #20263

### CODE REVIEW

**Comment by nik9000** [comment]
While this doesn't add the logging capability we talked about in #20263 it *does* document the "debug by throwing exception" paradigm we currently support fairly well.

**Comment by nik9000** [comment]
@jdconrad can you have a look at this? I know we didn't expose Class because we were afraid of reflection stuff but I think we're ok here because we don't expose any of the reflection bits.

**Comment by nik9000** [comment]
I tagged this with 5.1. I'm not sure if it'll make it there but if possible I'd like to get it in.

**Comment by s1monw** [comment]
is this really necessary, can't we just use `toString` for this?

**Comment by nik9000** [comment]
> is this really necessary, can't we just use toString for this?

`toString` on Maps and things doesn't return the class though.

**Comment by s1monw** [comment]
I really think we are jumping the gun here, we build this language to expose a limited set of methods etc. and keep things simple. Can we think about debugging in a broader scope before we just whitelist stuff like this?

**Comment by s1monw** [comment]
like the entire thing of throwing an exception etc. is like a workaround no? I mean I am just thinking about this for 5 min but this look wrong. We should rather think about some kind of `explain` method for debugging? like this

```Java

explain(doc.goals)

```

that can throw a specific exception that we can render in a special way and can give you nice information about the object in a structured way?

**Comment by nik9000** [comment]
> We should rather think about some kind of explain method for debugging?

I can do that instead. Sure. I expect I still have to throw an exception to get it working. Honestly I came at this from the perspective of documenting the way you can do things now and found that you couldn't get the class which limits the kind of debugging you can do. Something like `explain` would just be better because we could build structured output. Do you think it should just return the `toString` and the `getClass`? There isn't much else we could do without specializing on the argument type.

**Comment by s1monw** [comment]
@nik9000 yeah I mean we can have a special exception `ScriptExplainException` that we throw and then structure the response somehow? @jdconrad WDYT

**Comment by jdconrad** [comment]
I am strongly against whitelisting anything class related, safe or not, simply because it's scary to let Class float around at all as part of scripts.  We have talked about an explain api before, so I'm definitely on board with that.  I thought before we had wanted to add a rest query that could trigger this?  But, as a faster fix, this suggestion makes a lot of sense to me.  It also allows the user to only trigger explain as part of a branch if they want to which is nice (say if something unexpected is null).

**Pull request closed without merging**
