### PR TITLE
Adding cat api for component template

### PR DESCRIPTION
**Pull request by SivagurunathanV**
Details:
- Adding cat api for component template e.g `/_cat/component_templates/` and  #`/_cat/component_templates/{name}` as part of this https://github.com/elastic/elasticsearch/issues/68941

Testing:

- Ran ES locally, hit the API manually to verify it. [API Testing](https://drive.google.com/file/d/1ZIlwvxoZI6h_Dq8Ps3oteiG3hCYdjxUc/view?usp=sharing)
- Added a file called `RestCatComponentTemplateActionTests.java` with test cases.

### CODE REVIEW

**Comment by danhermann** [comment]
@elasticmachine ok to test

**Comment by danhermann** [comment]
@elasticmachine update branch

**Review by danhermann — CHANGES_REQUESTED** [review]
@SivagurunathanV, thanks, this looks pretty close to what we want. One change here is that the content in each field should be plaintext and not JSON as you currently have in the `template` and `meta_data` fields. After thinking about this one in a little more detail, I think it might make sense to have `name` and `version` as the first two fields. After that, it might be useful just to have count fields (e.g., `alias_count`, `mapping_count`, etc.) for the number of aliases, mappings, settings, and meta fields defined on each component template since we can't put structured content in CAT APIs.

**Comment by SivagurunathanV** [comment]
@elasticmachine update branch

**Comment by danhermann** [comment]
@elasticmachine update branch

**Comment by danhermann** [comment]
@SivagurunathanV, it looks like the test failures were transient errors unrelated to your code. I'll make another review pass over this later this week.

**Comment by danhermann** [comment]
@SivagurunathanV, it occurred to me that one more field would be useful in this API -- something along the lines of an `included_in` list that contains the names of any composable templates that refer to the component template. Does that sound like something you can add?

**Comment by SivagurunathanV** [comment]
Sure, will work on it 👍

**Comment by SivagurunathanV** [comment]
Hi @danhermann, I added the `included_in` field in the response.

```
name             version alias_count mapping_count settings_count metadata_count included_in
metrics-mappings 0       0           1             0              2              [metrics]
```

Let me know if this looks good.

**Comment by danhermann** [comment]
@dakrone, what do you think about the implementation of `mappings_count` here for a component template such as `.deprecation-indexing-mappings` where `mappings_count` is 3 because there are 3 child objects under `mappings` for `dynamic_templates`, `date_detection`, and `properties` (which itself defines 5 different fields).

**Comment by danhermann** [comment]
@SivagurunathanV, I tested this with some component templates and it was always showing a `mappings_count` of 3 since there were three child objects under mappings rather than three field mappings. I think the API needs to dig further into the mappings object to find the number of field mappings.

**Comment by SivagurunathanV** [comment]
@elasticmachine run elasticsearch-ci/part-1

**Comment by danhermann** [comment]
Hi @SivagurunathanV, to resolve the build error above, you need to change `area: Data Management/Indices APIs` to `area: Indices APIs` in the changelog file.

**Comment by SivagurunathanV** [comment]
> Hi @SivagurunathanV, to resolve the build error above, you need to change `area: Data Management/Indices APIs` to `area: Indices APIs` in the changelog file.

Thanks Dan, updated the file.

**Pull request merged**
