### PR TITLE
[ML] Add reason to DataFrameAnalyticsTask updateState log message

### PR DESCRIPTION
**Pull request by davidkyle**
When setting the state to FAILED the reason isn't logged. Debugging would be simpler if it was.

It looks to me like `DataFrameAnalyticsTask.updateState()` is only ever called with `DataFrameAnalyticsState.FAILED` the non failure updates call `AllocatedPersistentTask.updatePersistentTaskState()`.   @przemekwitek what do you think of renaming this method to `setFailed` as this method has the extra logging we are not really interesting in when setting the state to STARTED etc. 

For #52654

### CODE REVIEW

**Review by benwtrent — APPROVED** [review]
100% we should include the reason :)

**Comment by przemekwitek** [comment]
> @przemekwitek what do you think of renaming this method to setFailed

SGTM if that's what the method is used for.

**Review by przemekwitek — APPROVED** [review]
LGTM

**Comment by davidkyle** [comment]
@przemekwitek I made the refactor of renaming the method to `setFailed` and removed the \@nullable annotation from the `reason` parameter. Can you take another look please

**Comment by przemekwitek** [comment]
LGTM2

**Pull request merged**
