### PR TITLE
Upgrade to Jackson 2.7.1

### LINKED ISSUE #16294: Upgrade to Jackson 2.7.0
Jackson 2.7.0 has been released.

Release notes: https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.7

### PR DESCRIPTION
**Pull request by jbertouch**
Closes #16294.

The previous duplicate key test assertion in JsonSettingsLoaderTests was failing to catch the exception. The background - Jackson 2.7.0 altered the logic for the getTokenLocation method in the JSON parser, it now points to the first character that is logically part of the token. See [https://github.com/FasterXML/jackson-core/issues/229](https://github.com/FasterXML/jackson-core/issues/229).

### CODE REVIEW

**Comment by dakrone** [comment]
@jbertouch thanks for the PR! I think we may want to bump it to Jackson 2.7.1 while we're at it: https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.7.1

Do you want to make that change?

**Comment by jbertouch** [comment]
Hi @dakrone, done!

**Comment by dakrone** [comment]
@jbertouch thanks, for these we also need to run `gradle updateSHAs`, do you want to do that? Or I can do it when I merge this

**Comment by jbertouch** [comment]
Hi @dakrone, I ran the task and committed the updated hash values.

**Comment by dakrone** [comment]
Merged, thanks @jbertouch !

**Pull request merged**
