### PR TITLE
Remove animal sniffer from low-level REST client

### PR DESCRIPTION
**Pull request by jasontedor**
The low-level REST client targets JDK 7. To avoid compiling against JDK functionality not available in JDK 7, we use animal sniffer. However, when we switched to using the JDK 9 and now the JDK 10 compiler which has built-in support for targeting previous JDKs, we no longer need to use animal sniffer. This is because the JDK is now packaged with the signatures needed to ensure that when we target JDK 7 at compile-time it is detected that we are only using JDK 7 functionality. This commit removes the use of animal sniffer from the low-level REST client build.

### CODE REVIEW

**Comment by jasontedor** [comment]
Here are the compiler arguments that we use today when building the low-level REST client:

```
-d
/home/jason/src/elastic/elasticsearch/client/rest/build/classes/java/main
-encoding
UTF-8
-g
-sourcepath
""
-proc:none
-XDuseUnsharedTable=true
-classpath
/home/jason/.gradle/caches/modules-2/files-2.1/org.apache.httpcomponents/httpclient/4.5.2/733db77aa8d9b2d68015189df76ab06304406e50/httpclient-4.5.2.jar:/home/jason/.gradle/caches/modules-2/files-2.1/org.apache.httpcomponents/httpcore/4.4.5/e7501a1b34325abb00d17dde96150604a0658b54/httpcore-4.4.5.jar:/home/jason/.gradle/caches/modules-2/files-2.1/org.apache.httpcomponents/httpasyncclient/4.1.2/95aa3e6fb520191a0970a73cf09f62948ee614be/httpasyncclient-4.1.2.jar:/home/jason/.gradle/caches/modules-2/files-2.1/org.apache.httpcomponents/httpcore-nio/4.4.5/f4be009e7505f6ceddf21e7960c759f413f15056/httpcore-nio-4.4.5.jar:/home/jason/.gradle/caches/modules-2/files-2.1/commons-codec/commons-codec/1.10/4b95f4897fa13f2cd904aee711aeafc0c5295cd8/commons-codec-1.10.jar:/home/jason/.gradle/caches/modules-2/files-2.1/commons-logging/commons-logging/1.1.3/f6f66e966c70a83ffbdb6f17a0919eaf7c8aca7f/commons-logging-1.1.3.jar
-Werror
-Xlint:all,-path,-serial,-options,-deprecation
-Xdoclint:all
-Xdoclint:-missing
-proc:none
--release
7
/home/jason/src/elastic/elasticsearch/client/rest/src/main/java/org/elasticsearch/client/HttpDeleteWithEntity.java
/home/jason/src/elastic/elasticsearch/client/rest/src/main/java/org/elasticsearch/client/ResponseListener.java
/home/jason/src/elastic/elasticsearch/client/rest/src/main/java/org/elasticsearch/client/HttpGetWithEntity.java
/home/jason/src/elastic/elasticsearch/client/rest/src/main/java/org/elasticsearch/client/Response.java
/home/jason/src/elastic/elasticsearch/client/rest/src/main/java/org/elasticsearch/client/HeapBufferedAsyncResponseConsumer.java
/home/jason/src/elastic/elasticsearch/client/rest/src/main/java/org/elasticsearch/client/HttpAsyncResponseConsumerFactory.java
/home/jason/src/elastic/elasticsearch/client/rest/src/main/java/org/elasticsearch/client/RestClientBuilder.java
/home/jason/src/elastic/elasticsearch/client/rest/src/main/java/org/elasticsearch/client/DeadHostState.java
/home/jason/src/elastic/elasticsearch/client/rest/src/main/java/org/elasticsearch/client/RequestLogger.java
/home/jason/src/elastic/elasticsearch/client/rest/src/main/java/org/elasticsearch/client/RestClient.java
/home/jason/src/elastic/elasticsearch/client/rest/src/main/java/org/elasticsearch/client/ResponseException.java
```

The relevant component here is the `--release 7`.

**Review by javanna — APPROVED** [review]
LGTM thanks @jasontedor

**Review by nik9000 — APPROVED** [review]

**Comment by jasontedor** [comment]
test this please

**Comment by jasontedor** [comment]
run gradle build tests

**Comment by jasontedor** [comment]
test this please

**Comment by jasontedor** [comment]
Thanks @javanna and @nik9000.

**Pull request merged**
