### PR TITLE
Move test framework under a "test" top level dir

### PR DESCRIPTION
**Pull request by rjernst**
This allows adding more test projects, eg integ test fixtures that will
be coming soon.

### CODE REVIEW

**Comment by nik9000** [comment]
LGTM

**Comment by dadoonet** [comment]
@rjernst Does it mean that this test framework is now published as an artifact so anyone (even if using maven) would be able to use it?

**Comment by s1monw** [comment]
I think so! @dadoonet see https://oss.sonatype.org/content/repositories/snapshots/org/elasticsearch/test-framework/3.0.0-SNAPSHOT/

**Comment by dadoonet** [comment]
Fantastic! I missed it! Thanks @s1monw

**Comment by rjernst** [comment]
@dadoonet That was already the case. With this change the coordinates are slightly different:
https://oss.sonatype.org/content/repositories/snapshots/org/elasticsearch/test/framework/3.0.0-SNAPSHOT/

**Pull request merged**
