### PR TITLE
Fix parsing RareTerms aggregation response failed in RestHighLevelClient

### PR DESCRIPTION
**Pull request by gaobinlong**
Relates to #63025.

The main changes are:
1. Add `LongRareTerms` and `StringRareTerms` to the `DefaultNamedXContents`, ensure that the response of RareTerms aggregation can be parsed correctly.
2. Add `testSearchWithRareTermsAgg` method to test the response of RareTerms aggregation can be parsed correctly.
2. Add some test code to ensure the `AggregationsTests` can execute successfully.

### CODE REVIEW

**Comment by swallez** [comment]
Thanks for your contribution @gaobinlong. Overall it looks pretty good.

**Comment by swallez** [comment]
Jenkins test this please

**Comment by gaobinlong** [comment]
@elasticmachine test this please

**Comment by gaobinlong** [comment]
@swallez, some test failures here, I have merged the master branch into this branch, can you help to trigger the test again?

**Comment by swallez** [comment]
Jenkins test this please

**Comment by gaobinlong** [comment]
@swallez， the test failure may not relates to the code change of this pr? I'm confused about that. https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-2/12303/testReport/junit/org.elasticsearch.xpack.datastreams/DataStreamRestIT/testDSXpackUsage/

**Comment by jakelandis** [comment]
@elasticmachine update branch

**Comment by jakelandis** [comment]
@elasticmachine ok to test

**Review by swallez — APPROVED** [review]
LGTM! Thanks @gaobinlong!

**Comment by swallez** [comment]
Backported to 7.x and 7.10.

**Pull request merged**
