### PR TITLE
Fix pipeline id not present in ingest metadata inside on_failure block

### PR DESCRIPTION
**Pull request by dakrone**
This commit fixes an issue where inside of an `on_failure` block the `_ingest.on_failure_pipeline`
metadata was not being propagated. The root cause seems to be an off-by-one error where we were
checking for at least two pipelines, when we should be checking for only a minimum of a single
pipeline that has been executed before adding the metadata.

### CODE REVIEW

**Comment by dakrone** [comment]
@elasticmachine run elasticsearch-ci/part-1

**Review by seanstory — APPROVED** [review]
Thanks for the super quick investigation and fix!

**Review by jbaiera — APPROVED** [review]
LGTM

**Comment by dakrone** [comment]
@elasticmachine update branch

**Comment by dakrone** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|7.17|[](https://github.com/elastic/elasticsearch/pull/89740)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
