### PR TITLE
Use the correct key when checking the map.

### PR DESCRIPTION
**Pull request by raraujosc**
Bug caught during compilation by ErrorProne: http://errorprone.info/docs/installation

### CODE REVIEW

**Comment by jasontedor** [comment]
Thanks for the PR @raraujosc. This is indeed wrong. However, can you:
 - update the PR description (it's currently empty)
 - explain the impact of this bug
 - add a test
 - sign the CLA

**Comment by jasontedor** [comment]
No further feedback, closing.

**Comment by jasontedor** [comment]
@abeyad Can you follow-up here and address this, and in particular see what the impact of this is.

**Comment by abeyad** [comment]
I opened #24289 to fix this bug

**Pull request closed without merging**
