### PR TITLE
Expose discard_compound_token option to kuromoji_tokenizer

### PR DESCRIPTION
**Pull request by johtani**
In Lucene 8.5, Japanese Tokenizer introduced new option `DiscardCmpoundToken`([LUCENE-9123](https://issues.apache.org/jira/browse/LUCENE-9123))

This PR exposes new option to Elasticsearch kuromoji plugin.

And I found 2 bug around Kuromoji Tokenizer.
1. Fix typo(`discartPunctuation`) in KuromojiTokenizerFactory
2. Fix documentation bug in kuromoji_tokenizer `extended` mode
    - The `extended` mode output of `関西国際空港` is same as `search` mode output.

Please let me know, if I should split this PR to new feature and fix typo.

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)? Yes
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)? Yes
- If submitting code, have you built your formula locally prior to submission with `gradle check`? Yes, with ` -p plugins/analysis-kuromoji` option
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed. Yes, against master
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)? Yes
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that. Yes

### CODE REVIEW

**Comment by jimczi** [comment]
@elasticmachine ok to test

**Comment by jimczi** [comment]
@elasticmachine update branch

**Review by jimczi — APPROVED** [review]
LGTM, It's nice to see you around here again @johtani ;)

**Comment by johtani** [comment]
@jimczi Thanks for reviewing my PR :D

**Pull request merged**
