### PR TITLE
Dump a truncated file if over limit in packaging tests

### PR DESCRIPTION
**Pull request by rjernst**
The packaging tests run many shell commands, and capture the stdout and
stderr of those commands into files. If the file is extremely large, the
shell omits reading the file. That makes debugging any issue with large
output difficult. This commit adds handling to read up to the max file
size worth of characters from the file.

### CODE REVIEW

**Review by mark-vieira — COMMENTED** [review]
What do we end up doing with the returned output? Maybe we should provide a way to grab these things as streams instead?

**Comment by rjernst** [comment]
We have various assertions on the output/error string values. It would be a lot of work to convert these all to read the output themselves. I think the approach here is pragmatic: if we have  more than 100k output, something is wacky, let's just get what we can, otherwise the test is impossible to debug (we don't know what the file is filled with).

**Comment by mark-vieira** [comment]
> if we have more than 100k output, something is wacky, let's just get what we can

Would it probably make more sense then to _tail_ the output? Perhaps we'll see how it goes in practice and see if just getting the head is enough to debug these issues.

**Comment by rjernst** [comment]
I don't think tail or head particularly matters. In the case that I experienced this issue, procrun was outputting gigabytes of null characters (ie not printable). But I had no idea, I only saw that the file size was 8GB, and didn't know anything about the content.

**Comment by rjernst** [comment]
@mark-vieira Do you have any other thoughts here? I don't have that strong of an opinion here, I can drop this PR, but I do think it's wrong to just print the existing cryptic "the file was too long". If that ever fails, as it did for me, it makes debugging extremely difficult, and ultimately I had to add this to see what was going on.

**Review by mark-vieira — APPROVED** [review]
This is certainly an improvement. Let's push forward with this.

**Pull request merged**
