### PR TITLE
[Transform] Reset max page size to settings value

### LINKED ISSUE #109308: [Transform] Page search size does not increase when resources become available
### Description

Transforms supports `max_page_search_size` during the search request.  While the Transform is encountering a circuit breaker exception due to out of memory, it will automatically lower the `max_page_search_size` and retry the request until it succeeds.  Transforms will then reuse that lowered search size until the node is restarted or the user updates the `max_page_search_size` setting.

We need to determine if it's wise to have the Transform try to raise the search size back up to the user's configured `max_page_search_size` after some amount of time, risking another round of circuit breaker exceptions.

1. What is the impact of causing a circuit breaker exception?
2. How much time does it add to the checkpoint to try to increase the search size to `max_page_search_size`?
3. Do we increase it to the configured `max_page_search_size` or to some value less than that on each checkpoint?
4. Do we instead want to save the lowered search size and/or inform the user that the transform is running under a lowered configured value?

### PR DESCRIPTION
**Pull request by prwhelan**
When a circuit breaker exception causes the transform checkpoint to fail, the transform will reduce the max page size to the value specified by the circuit breaker.  Transform will retry the checkpoint until the search succeeds.

When the search succeeds, the Transform will now reset the max search size to the value specified in the Transform settings rather than the now-deprecated value in the Latest/Pivot config.

Fix #109308

### CODE REVIEW

**Review by przemekwitek — APPROVED** [review]
LGTM

**Comment by syepes** [comment]
Any news on when this is going to get included into a release, our production environments are currently getting impacted by this issue.

It would also be interesting to expose in a metric the actual currently used max page size, in this way it could be monitored.

**Comment by prwhelan** [comment]
Backport: https://github.com/elastic/elasticsearch/pull/109532

**Comment by prwhelan** [comment]
> Any news on when this is going to get included into a release, our production environments are currently getting impacted by this issue.

It will be in 8.15.0+, and it will be in 8.14.1 or 8.14.2+ (depending on when the build team cuts the branch).  I do not have an accurate ETA on when those will be released.  In the meantime, I included a workaround in https://github.com/elastic/elasticsearch/issues/109308

> It would also be interesting to expose in a metric the actual currently used max page size, in this way it could be monitored.

We can maybe include this in future telemetry improvements: https://github.com/elastic/elasticsearch/issues/109555

**Pull request merged**
