### PR TITLE
Logstash Pipeline REST api spec and documentation

### LINKED ISSUE #67360: Documentation needed for Logstash pipeline APIs
The Logstash Pipeline APIs are APIs added as part of the system indices project to provide application specific APIs that encapsulate system index access. The original plan was that these APIs were not going to be documented or have a REST API spec file as they are for internal use. However, upon further thought since these APIs could be useful outside of inter-stack use and there would be benefits for the stack use such as type safety in the client used within Kibana, a decision was made that the APIs should be documented and have a REST API spec.

### PR DESCRIPTION
**Pull request by jaymode**
This commit adds REST api specifications for the Logstash Pipeline APIs
and documentation of the APIs.

Closes #67360

### CODE REVIEW

**Comment by williamrandolph** [comment]
@elasticmachine please run elasticsearch-ci/docs

**Review by williamrandolph — CHANGES_REQUESTED** [review]
The text and the examples look great, but it all seems to be showing up in the Watcher section of the docs, which I don't think is intended. 
image

I think the fix involves moving every section up a level and making the new `===` sections `[discrete]`, but perhaps there's a better way.

**Comment by jaymode** [comment]
I put the include statement in the wrong file; it should be correct now. Good catch.

**Review by williamrandolph — APPROVED** [review]
LGTM!

**Pull request merged**
