### PR TITLE
Don't extend AbstractIndexComponent in AbstractTokenFilter

### PR DESCRIPTION
**Pull request by original-brownbear**
No need for this extension, we don't make use of the settings or deprecation logger
in production any more. Also, this slows down CS operations that require a
temporary index service which builds quite a bit slower when the loggers
need to be set up via reflective calls.

I left the existing tests around deprecations in place though they seem somewhat pointless now, should we just remove them?

### CODE REVIEW

**Comment by romseygeek** [comment]
> I left the existing tests around deprecations in place though they seem somewhat pointless now, should we just remove them?

+1 to remove these as well

**Comment by original-brownbear** [comment]
Alright, thanks @romseygeek dropped the tests that became redundant now.

**Review by romseygeek — APPROVED** [review]
LGTM, thanks @original-brownbear

**Comment by original-brownbear** [comment]
np + thanks Alan!

**Pull request merged**
