### PR TITLE
[ML-DataFrame] add special aggregations and count function for transforms

### PR DESCRIPTION
**Pull request by hendrikmuhs**
add a way to define special aggregations. This allows us to extract values from aggregations we could not extract before. As a first special aggregation this change adds a count aggregation which extracts the doc count

## API

The special aggregation looks like a normal aggregation:

```
"pivot": {
   "group_by": {},
   "aggregations": {
      "max_price": {
         "max": { "field" : "price"}
      },
      "number_of_purchased_items": {
         "count": {} <--- including the empty braces is only necessary due to how aggs are usually defined
      }
   }
}
```

In future we might want to have more special aggregations, however `count` is very simple, to enable others we might need further changes to expose access to certain state.

### CODE REVIEW

**Review by benwtrent — COMMENTED** [review]
I don't like adding a "special" aggregation inside the "aggregations" object in the API definition. It seems to me that this is what the API will look like:
```
"pivot": {
   "group_by": {},
   "aggregations": {
      "max": {...},
      "count": {} <--- including the empty braces is only necessary due to how aggs are usually defined
   }
}
``` 
Where "count" is not an aggregation at all. It is more of a "apply this function after aggs". 

Also, do we have any other ideas for "special aggs"? `count` seems like not only a "special agg" but a "special case of special aggs" that is not an aggregation at all. I think we are putting ourselves in a bind by using the wrong abstraction too early.

Additionally, it does not behave at all as any of the defined metric aggregations: it cannot be nested into sub-buckets (when we support them eventually), cannot be referenced by `bucket_script`, or `bucket_selector` (when we support them). 

It makes more sense to me to have an `include_count` flag as an option inside of `pivot`.

**Comment by hendrikmuhs** [comment]
@benwtrent 

just correcting your example, you missed the destination fieldname:

```
"pivot": {
   "group_by": {},
   "aggregations": {
      "max_price": {
         "max": { "field" : {}}
      },
      "number_of_purchased_items": {
         "count": {} <--- including the empty braces is only necessary due to how aggs are usually defined
      }
   }
}
```

It has been the idea to make it feel like an aggregation - I think we discussed this earlier - anyway, now that an implementation is actually there it's not a "what if" discussion so I am all for revisiting.

I am putting this on the agenda for the next team sync.

Regarding the empty parameter object: As you said, this is by design, if we ever have other special aggs we might have parameters. I think we either have to go with the DSL or do it completely different as you suggested.

**Comment by hendrikmuhs** [comment]
run elasticsearch-ci/1

**Comment by hendrikmuhs** [comment]
I am putting this PR on hold until we decided about the proposed design, aiming for 7.4.

**Comment by hendrikmuhs** [comment]
I re-factored the code as suggested and combined the 2 extraction methods into 1 as they were used in 1 place anyway.

The PR is ready, the question remains if the API is the direction we want to go.

**Pull request closed without merging**
