### PR TITLE
Remove Unused Dependencies from S3 Repo Plugin

### PR DESCRIPTION
**Pull request by original-brownbear**
* None of these are actually in use

### CODE REVIEW

**Comment by tlrx** [comment]
As far as I remember these dependencies are declared by the aws-sdk-java-s3 project or its parent project as non optional dependencies. Why do we want to remove them?

**Comment by original-brownbear** [comment]
@tlrx as far as I can tell these are only used transitively by `aws-java-sdk-core` (which itself is not directly used by us as far as I can see). So I figured we don't really need to manage these ourselves?

I'm not a big expert on our dependency checking infra here, but if we add these 2nd level transitive dependencies here why not add all other non-optional deps. of say `aws-java-sdk-core` as well (e.g. ION which we currently don't track)?

**Comment by tlrx** [comment]
The dependencies that are declared here will be the ones bundled within the plugin archive and later loaded as part of the plugin's classloader.

I think we need to include all non-optional dependencies declared by the AWS SDK as long as they are not already provided by Elasticsearch (like Jackson) or declared but unused (like jmspath). We should rely on the thirdPartyAudit task to detect any missing class... but actually I noticed that this task is always disabled for this plugin.

**Comment by original-brownbear** [comment]
@tlrx thanks for being careful here :)! I'll wait for the fix to the 3rd party audit task that seems to be incoming before continuing here then.

**Comment by original-brownbear** [comment]
Closing this in favor of https://github.com/elastic/elasticsearch/pull/44089

**Pull request closed without merging**
