### PR TITLE
Ensure TestHttpChannel.close() is idempotent

### PR DESCRIPTION
**Pull request by thecoop**
`Closeable.close` states that `close` is idempotent - you can call it on an already-closed object and it doesn't do anything. This change makes `TestHttpChannel.close()` follow this contract.

### CODE REVIEW

**Comment by thecoop** [comment]
I can see an argument for leaving it as-is - it's for testing purposes only, and `close` _shouldn't_ be called multiple times, as that might indicate a bug. But it is _valid_ to call `close` multiple times, so `TestHttpChannel` should allow it.

**Review by DaveCTurner — CHANGES_REQUESTED** [review]
While I agree that throwing an ISE is the wrong reaction to double-closing, I'd rather we asserted that this never happens. Yes technically these things should be idempotent according to the JDK docs, but in practice we should consider it a logic error if we're double-closing stuff.

**Comment by thecoop** [comment]
I've added an assertion failure to the close.

In practice, asserts are always turned on for tests, so this will still fail, but it turns the failure into an `AssertionError` which is more fitting what we want here

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Comment by thecoop** [comment]
@elasticmachine update branch

**Pull request merged**
