### PR TITLE
Simplify securitymanager init

### PR DESCRIPTION
**Pull request by rmuir**
Today we create a temp file, concatenate our template with some dynamically generated rules, and then set a sysprop to the new temp file.

A custom java.security.Policy is cleaner and easier to understand: we can avoid the sysprop, temp files, path escaping, etc.

### CODE REVIEW

**Comment by kimchy** [comment]
nice, much cleaner! I think that on a different change we should see how we can separate the test rules from the security.policy, since it will allow us to get read of create security manager permission?

LGTM

**Comment by rmuir** [comment]
The whole idea is that the system can only do what its tested to do. If we want to do a bunch of untested shit, thats cool, but id rather stay out in that case.
So for better security, clean up the tests. No cheating.

**Comment by kimchy** [comment]
I see, I thought it was needed in the tests only the test the security manager feature itself...

**Comment by rmuir** [comment]
I dont think creating an sm is particularly harmful.  as opposed to setting it. But there is some reason tests need it. Like many of the many permissions here that need to be cleaned up

**Pull request merged**
