### PR TITLE
[Scripting] Make Max Script Length Setting Dynamic

### PR DESCRIPTION
**Pull request by jdconrad**
This changes the current script.max_size_in_bytes to be dynamic so it can be set through the cluster settings API.  This setting is also applied to inline scripts in the compile method of ScriptService to prevent excessively long inline scripts from being compiled.  The script length limit is removed from Painless as this is no longer necessary with the protection in compile.

Relates #23209

### CODE REVIEW

**Comment by jdconrad** [comment]
@elasticmachine please test this

**Comment by jdconrad** [comment]
@elasticmachine test this please

**Review by martijnvg — APPROVED** [review]
Left one comment. LGTM otherwise.

**Comment by jdconrad** [comment]
@elasticmachine test this please

**Comment by jdconrad** [comment]
@elasticmachine test this please

**Pull request merged**
