### PR TITLE
version bump 7.1.0 -> 7.1.1 (includes 6.8.1 too)

### PR DESCRIPTION
**Pull request by jakelandis**
Related: #42240
Related: #42251
Related: #42253

### CODE REVIEW

**Comment by jakelandis** [comment]
removing `7.2.0` label in favor of https://github.com/elastic/elasticsearch/pull/42251

**Review by rjernst — APPROVED** [review]
I think the PR title/commit message is incorrect (7.0 instead of 7.1), otherwise LGTM.

**Comment by jakelandis** [comment]
removed `8.0.0` label in favor of https://github.com/elastic/elasticsearch/pull/42253

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by jakelandis** [comment]
@elasticmachine run elasticsearch-ci/bwc 
@elasticmachine run elasticsearch-ci/default-distro

**Pull request merged**
