### PR TITLE
Update AWS SDK for repository-s3 plugin to support IAM Roles for Service Accounts

### PR DESCRIPTION
**Pull request by seanmcrw**

### CODE REVIEW

**Comment by original-brownbear** [comment]
@seanmcrw thanks for opening this PR. You'll have to run ` ./gradlew updateSHAs` and commit the result to make a dependency upgrade work though. Can you do that please?
You can verify that everything worked out correctly by ensuring that `./gradlew precommit` passes.

**Comment by original-brownbear** [comment]
Jenkins test this

**Review by original-brownbear — APPROVED** [review]
LGTM thanks @seanmcrw

**Review by original-brownbear — CHANGES_REQUESTED** [review]
Sorry my bad ... we don't want to diverge between S3 and the EC2 discovery here.

Can you update the dep. version in the EC2 discovery (`discovery-ec2` plugin) to the same value you used here please as well?
Thanks

**Comment by seanmcrw** [comment]
No problem. discovery-ec2 plugin updated ```./gradlew updateSHAs``` run and passed.

**Comment by original-brownbear** [comment]
Jenkins test this

**Review by original-brownbear — APPROVED** [review]
LGTM, Thanks @seanmcrw !

**Comment by seanmcrw** [comment]
Hi, any idea when this will be released?
Thanks

**Comment by original-brownbear** [comment]
@seanmcrw this is labelled `7.5.0` so it'll be released in that version. I can't give you an exact release date for that though I'm afraid.

**Pull request merged**
