### PR TITLE
Tidy up some ILM and SLM packages

### PR DESCRIPTION
**Pull request by joegallo**
There are a few tiny packages that seem like they might be out of place. This PR moves their contents around so that they vanish.

### Before
```
joegallo@galactic:~/Code/elastic/elasticsearch $ for dir in $((find x-pack -type d -name ilm; find x-pack -type d -name slm) | grep src | sort | sed -e "s/^\\.\\///g" | grep -v -E '(^docs|^client)' | grep -v build | grep -v -E '(qa|Test)'); do echo $dir $(ls $dir/*.java | wc -l); done
x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm 83
x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/slm 8
x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/slm 1 # tiny!
x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ilm 85
x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/slm 4
x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/slm 2 # tiny!
x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm 15
x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/slm 8
x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/core/ilm 1 # tiny!
x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/ilm 18
x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/slm 5
```
### After
```
joegallo@galactic:~/Code/elastic/elasticsearch $ for dir in $((find x-pack -type d -name ilm; find x-pack -type d -name slm) | grep src | sort | sed -e "s/^\\.\\///g" | grep -v -E '(^docs|^client)' | grep -v build | grep -v -E '(qa|Test)'); do echo $dir $(ls $dir/*.java | wc -l); done
x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm 83
x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/slm 9
x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/ilm 85
x-pack/plugin/core/src/test/java/org/elasticsearch/xpack/core/slm 6
x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/ilm 15
x-pack/plugin/ilm/src/main/java/org/elasticsearch/xpack/slm 8
x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/ilm 19
x-pack/plugin/ilm/src/test/java/org/elasticsearch/xpack/slm 5
```

### CODE REVIEW

**Review by joegallo — COMMENTED** [review]
[edit: this is accidentally a review comment, and so I can't delete it!]

**Comment by joegallo** [comment]
@elasticmachine update branch

**Review by dakrone — APPROVED** [review]
LGTM once CI is happy

**Comment by joegallo** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample-windows

**Pull request merged**
