### PR TITLE
Simplify Snapshot Resiliency Test

### PR DESCRIPTION
**Pull request by original-brownbear**
* Thanks to #39793 dynamic mapping updates don't contain blocking operations anymore so we don't have to manually put the mapping in this test and can keep it a little simpler

### CODE REVIEW

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/2

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/1

**Review by DaveCTurner — APPROVED** [review]
LGTM, took me a while to understand it tho :)

The call-backs in these tests are rather too heavily nested for my taste, but that's a debate for another time.

**Comment by original-brownbear** [comment]
@DaveCTurner  thanks!

> The call-backs in these tests are rather too heavily nested for my taste, but that's a debate for another time.

+1, but at least we got rid of one of them now :D

**Pull request merged**
