### PR TITLE
[ML] Handle Errors and pre-streaming exceptions

### PR DESCRIPTION
**Pull request by prwhelan**
If we fail to establish a connection to bedrock, the error is returned in the client's CompletableFuture.  We will forward it to the listener via the stream processor.  Any Errors are thrown on another thread.

### CODE REVIEW

**Review by maxhniebergall — APPROVED** [review]
LGTM

**Comment by prwhelan** [comment]
@elasticmachine update branch

**Comment by prwhelan** [comment]
@elasticmachine update branch

**Review by maxhniebergall — APPROVED** [review]
LGTM

**Pull request merged**
