### PR TITLE
Update secure-settings.asciidoc

### PR DESCRIPTION
**Pull request by moljac024**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by DaveCTurner** [comment]
@elasticmachine please test this

**Comment by DaveCTurner** [comment]
I'm not a fan of this change, although I understand why it's been suggested. The point of this example is to show how to pass a value into a setting through `stdin`, and `cat` is one of the simplest ways to do that. I'm not a fan because the point isn't the `cat` invocation, it's the `--stdin` flag, and I feel this extra paragraph will cause more confusion than it solves.

I've thought about alternatives and haven't come up with one that clarifies it in my mind. How about changing `cat /file/containing/setting/value` to `script-that-outputs-setting-value-on-stdout.sh` for instance? Or `cat /file/containing/encrypted/setting/value | openssl enc -aes-256-cbc -d`?

Additionally, this PR is against `6.1` because (I'm guessing) it was made using the [✎ Edit] link that appears on each page in the docs.

**Comment by rjernst** [comment]
I don't think this change is necessary, but if there is that much of a concern, then I would simply rename the path to `/path/to/temporary/file/with/password` to make it a little more clear it is expected in this case to remove the file afterwards (which I would expect any sysadmin to already know). But I think the added note will just add confusion.

**Comment by moljac024** [comment]
I agree that the disclaimer can add confusion. Maybe then just best to change the command to a script invocation, like @DaveCTurner suggested.

Additionally, I hastily added this line before realizing that the keystore currently only adds obfuscation so the whole point is moot at the moment anyway. Still it makes sense to think about this for future-proofing.

**Comment by javanna** [comment]
Closing as we did not reach agreement on this one.

**Pull request closed without merging**
