### PR TITLE
Merge pull request #2 from elastic/master

### PR DESCRIPTION
**Pull request by elijahdjmarshall**
Update

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?

### CODE REVIEW

**Comment by jasontedor** [comment]
This is the third no-content PR you've opened the last four days. If there's something we can help you with, please let us know. Yet, please stop so that people stop receiving unnecessary notifications.

**Comment by elijahdjmarshall** [comment]
@jasontedor 

My apologies. I'm new to GIT and am having a lot of trouble trying to pull the latest changes into my fork from your Master. I've been pouring over Google searches trying to find how exactly to do a rebase but cannot find information on what I'm doing wrong. 
I'm working directly from the github website.
If you could provide me with a link to a tutorial that states exactly how I"m to do pulls to get my fork in sync I'd greatly appreciate it.

**Comment by jasontedor** [comment]
@elijahdjmarshall I would be happy to help you with that. Would you please open a topic on the [forum](https://discuss.elastic.co) and link to it from here? We reserve GitHub for bug reports and feature requests, and prefer to keep general discussion on the forum. One question that I have immediately if you could please answer in your post: do you have changes in your fork or are you just trying to get your fork up to date with the latest changes in our master branch?

**Comment by elijahdjmarshall** [comment]
@jasontedor 
Okay, I've posted onto the forum as you requests. https://discuss.elastic.co/t/need-guidance-on-using-github-git-to-manage-my-fork/71866

Thank you

**Pull request closed without merging**
