### PR TITLE
Append priv for _aliases over metricbeat-* for monitoring agent

### LINKED ISSUE #65315: Metricbeat errors due to missing `manage` permission for `remote_monitoring_user` user
This bug is similar to #63203.

Metricbeat configured with user `remote_monitoring_user` fails on fresh Elasticsearch 7.10 install with security enabled with error:

```
Failed to connect to backoff(elasticsearch(http://localhost:9200)): Connection marked as failed because the onConnect callback failed: failed to create alias: {"error":{"root_cause":[{"type":"security_exception","reason":"action [indices:admin/aliases] is unauthorized for user [remote_monitoring_user]"}],"type":"security_exception","reason":"action [indices:admin/aliases] is unauthorized for user [remote_monitoring_user]"},"status":403}: 403 Forbidden: {"error":{"root_cause":[{"type":"security_exception","reason":"action [indices:admin/aliases] is unauthorized for user [remote_monitoring_user]"}],"type":"security_exception","reason":"action [indices:admin/aliases] is unauthorized for user [remote_monitoring_user]"},"status":403}
```

Here is the request:

```HTTP
PUT /%3Cmetricbeat-7.10.0-%7Bnow%2Fd%7D-000001%3E HTTP/1.1
Host: localhost:9200
User-Agent: Go-http-client/1.1
Content-Length: 58
Accept: application/json
Authorization: Basic xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Content-Type: application/json; charset=UTF-8
Accept-Encoding: gzip

{"aliases":{"metricbeat-7.10.0":{"is_write_index":true}}}
```

And response:

```HTTP
HTTP/1.1 403 Forbidden
content-type: application/json; charset=UTF-8
content-encoding: gzip
content-length: 156

{"error":{"root_cause":[{"type":"security_exception","reason":"action [indices:admin/aliases] is unauthorized for user [remote_monitoring_user]"}],"type":"security_exception","reason":"action [indices:admin/aliases] is unauthorized for user [remote_monitoring_user]"},"status":403}
```

Creating another user with roles `remote_monitoring_agent` and `remote_monitoring_collector` and temporary role with `manage` permission for index `metricbeat-*` solves the problem. I think that `remote_monitoring_agent` should have `manage` permission added.

### PR DESCRIPTION
**Pull request by albertzaharovits**
This adds the privilege for the `_aliases` action for the `metricbeat-*` index
namespace to the `remote_monitoring_agent` built-in role (used by metricbeat
agents). This is required (at least) when creating ingest indices that have aliases.

Notably, this change permits metricbeat agents to delete indices via the
`remove_index` action, which is undesirable but we have no way around it.

~This adds the `manage` index privilege instead of the `create_index` and `view_index_metadata`
over the `metricbeat-*` namespace for the `remote_monitoring_agent` built-in role (used
by metricbeat agents).~

~Looks like metricbeat creates indices with aliases, which are authorized like an `CreateIndex` followed
by an `IndicesAndAliases` action~
https://github.com/elastic/elasticsearch/blob/164d9911897c3925f1173b3629d27a71446db6be/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authz/AuthorizationService.java#L333 
~The `IndicesAndAliases` action allows to delete indices, so at this point we're probably better off granting
the whole `manage` to the `metricbeat-*` index namespace, lest we discover the next metricbeat version requires
some monitoring privileges...~

cc @ycombinator 

Closes https://github.com/elastic/elasticsearch/issues/65315

### CODE REVIEW

**Comment by ycombinator** [comment]
cc: @sayden as the stack monitoring Metricbeat and Filebeat modules are now being primarily tended to by him.

**Review by ywangd — COMMENTED** [review]
IIUC, the choice is between granting `manage` (proposed by the PR) or `create_index, view_index_metadata, indices:admin/aliases` for the `metricbeat-*` namespace.

The `IndicesAndAliases` action (`indices:admin/aliases`) allows to delete indices, but it does *not* allow deletion for data streams. A `manage` privilege, on the contrary, is able to do that. It currently may not be a real issue since the `metricbeat-*` indices are not yet a data stream (as of 7.11). But granting `manage` privilege does have the potential to cause future surprises given metricbeat may adopt data stream and our development processes are not synced all the time.

Other than the above, by closely comparing the privileges granted by `manage` vs `create_index, view_index_metadata, indices:admin/aliases`, I see the following differences:

* Extra privileges granted by `manage`:
```
indices:admin/analyze
indices:admin/block/add
indices:admin/cache/clear
indices:admin/close
indices:admin/data_stream/delete
indices:admin/data_stream/migrate
indices:admin/data_stream/promote
indices:admin/flush
indices:admin/forcemerge
indices:admin/freeze
indices:admin/ilm/remove_policy
indices:admin/ilm/retry
indices:admin/mapping/auto_put
indices:admin/mapping/put
indices:admin/open
indices:admin/refresh
indices:admin/reload_analyzers
indices:admin/resize
indices:admin/rollover
indices:admin/seq_no/global_checkpoint_sync
indices:admin/seq_no/retention_lease_background_sync
indices:admin/seq_no/retention_lease_sync
indices:admin/settings/update
indices:admin/shrink
indices:admin/xpack/ccr/forget_follower
indices:admin/xpack/ccr/put_follow
indices:admin/xpack/ccr/unfollow
indices:admin/xpack/rollup
indices:admin/xpack/rollup_indexer
```
The `manage` privilege grants many more actions than the alternative. One can argue many of them are not an issue given you can already delete the index. For an example, if you can delete an index, being able to close the index is not going to be any worse. But there are also a few actions that are unclear to me. For example, the data stream as discussed above. Or maybe `indices:admin/refresh`,  `indices:admin/forcemerge` because they can potentially destablise a cluster which is a different risk than data integrity.

* Extra privileges granted by `create_index, view_index_metadata, indices:admin/aliases`:
```
indices:monitor/settings/get
indices:data/read/field_caps*
```
This list is much smaller and I don't even know whether they are truely needed by metricbeat (they could just be an artefact because the named privileges are not granular enough). But it might be better to add them for safety? If so, we will need to keep `view_index_metadata`.

**Overall**, I prefer *not* granting the `manage` privilege, but instead adding `indices:admin/aliases` to the existing list. The downside is that we may get yet another bug asking for more privileges. But I think it is generally better to fail closed than fail open.

**Comment by ywangd** [comment]
PS: I just noticed that work is underway to support adding and removing alias for data stream (#69044). From the brief look at it, [deleting data stream through alias actions will not be supported](https://github.com/elastic/elasticsearch/pull/69044/files#diff-c6ad76cc788572a57cc01c1eae376a0e5de9f67f0e3c3dc852a3e10fb21552fd). I think it is the right choice. Maybe we should deprecate deleting index with alias action, but that's a seperate topic.

**Comment by albertzaharovits** [comment]
Thank you for looking closely at it Yang!

I've made the change, per your suggestion, to only add the `indices:admin/aliases` action.

**Comment by albertzaharovits** [comment]
@elasticmachine update branch

**Review by ywangd — APPROVED** [review]
LGTM

**Pull request merged**
