### PR TITLE
Documents applicability of term query to range type

### PR DESCRIPTION
**Pull request by davidbkemp**
Addressing elastic#27030

### CODE REVIEW

**Comment by karmi** [comment]
Hi @davidbkemp, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/elasticsearch/pull/28165.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by davidbkemp** [comment]
@karmi I accidentally committed that using my work email.  I am submitting this as a private individual.  Is it OK if I force push that commit using my personal email address?

**Comment by davidbkemp** [comment]
I will create a new PR with the correct email address.

**Comment by karmi** [comment]
Hi @davidbkemp, changing the e-mail in Git with `git commit --amend --reset-author`, and force pushing the branch is completely OK! (Also, it should suffice to just add the other e-mail to your Github profile — can be hidden —, so the Github API can match the e-mail to your profile.)

**Comment by davidbkemp** [comment]
Replaced this PR with a new one that has the right email address in the commit.  Sorry for the inconvenience. https://github.com/elastic/elasticsearch/pull/28166

**Pull request closed without merging**
