### PR TITLE
New mapping signature and mapping string source fixed.

### PR DESCRIPTION
**Pull request by farchanjo**
This merge make easy to mapping a new index on RolloverRequestBuilder from a client and fix the mapping main signature.

### CODE REVIEW

**Comment by farchanjo** [comment]
Why? I have sign the CLA.

**Comment by farchanjo** [comment]
It's worked!!

```java
    private void addMapping(RolloverRequestBuilder builder, PropertiesConfig.RollOver roll) {
        GetMappingsResponse response = client.admin()
                .indices()
                .prepareGetMappings(getIndexFormat(roll.getAlias()))
                .execute().actionGet();
        /*
         * Mapping a new index.
         */
        response.getMappings().get(getIndexFormat(roll.getAlias()))
                .forEach(m -> {
                    try {
                        builder.mapping(m.value.type(), m.value.source().string(), XContentType.JSON);
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                });

    }
```
```json
{
  "products-000001" : {
    "mappings" : {
      "product" : {
        "properties" : {
          "barcode" : {
            "type" : "long"
          },
          "category" : {
            "type" : "text",
            "analyzer" : "main_index_noacc_analyzer",
            "search_analyzer" : "main_search_analyzer"
          },
          "mongoId" : {
            "type" : "keyword",
            "ignore_above" : 256
          },
          "title" : {
            "type" : "text",
            "similarity" : "BM25",
            "analyzer" : "main_index_noacc_analyzer",
            "search_analyzer" : "main_search_analyzer"
          }
        }
      }
    }
  },
  "products-000002" : {
    "mappings" : {
      "product" : {
        "properties" : {
          "barcode" : {
            "type" : "long"
          },
          "category" : {
            "type" : "text",
            "analyzer" : "main_index_noacc_analyzer",
            "search_analyzer" : "main_search_analyzer"
          },
          "mongoId" : {
            "type" : "keyword",
            "ignore_above" : 256
          },
          "title" : {
            "type" : "text",
            "similarity" : "BM25",
            "analyzer" : "main_index_noacc_analyzer",
            "search_analyzer" : "main_search_analyzer"
          }
        }
      }
    }
  }
}
```
Now we can rolling a index copying a mapping!!

**Comment by dakrone** [comment]
@elasticmachine ok to test

**Comment by farchanjo** [comment]
@dakrone I'm looking the CI result, is failing, but I'm not seeing relation with my commit. Is something wrong with that? 

Thanks,

**Comment by dakrone** [comment]
@farchanjo I don't believe either of the failures is related to your code, don't worry I will work on getting it passed, nothing you need to change :)

**Pull request merged**
