### PR TITLE
Convert AntTask from Groovy to Java

### PR DESCRIPTION
**Pull request by edh-oss**
Relates to #34459

### CODE REVIEW

**Comment by breskeby** [comment]
@elasticmachine test this please

**Comment by edh-oss** [comment]
The details are no longer available, but I did look at them earlier this week.  My impression was that the two failing checks appeared to be failing for reasons unrelated to the changes in this CR.  Can we try the tests again?

**Comment by breskeby** [comment]
@elasticmachine test this please

**Comment by breskeby** [comment]
@edh-oss can you please rebase your branch against latest master please?

**Comment by edh-oss** [comment]
Sure.  Done.

**Comment by edh-oss** [comment]
Rebased against the latest master.  Can we test?

**Pull request closed without merging**
