### PR TITLE
update aggregations.asciidoc

### PR DESCRIPTION
**Pull request by diwasjoshi**
Closes [#26122](https://github.com/elastic/elasticsearch/issues/26122)

### CODE REVIEW

**Review by cbuescher — CHANGES_REQUESTED** [review]
This seems to be almost identical to another open PR: https://github.com/elastic/elasticsearch/pull/26346
If you agree I would close this issue and merge the former PR once it is reviewd.

**Comment by cbuescher** [comment]
@diwasjoshi sorry, my bad, I just realized this seems to be the same content, but in a different location. Not sure if we should wait for @bhupenchn to make the change in #26346

**Comment by diwasjoshi** [comment]
@cbuescher I made this pr based on discussion on the other PR, since there was no progress on the other PR in a long time, I made these changes, if this is not ok you may close the pr.

**Comment by cbuescher** [comment]
@diwasjoshi no problem, the PR is good, I just missed the context when looking at it first, and it would have been great to have the crosslink to the original PR in the description. This helps us keeping track of those issues. I just closed #26346 because there was no feedback in a long time, I think we can go with this one. I'm just going to check the page in question and run our full CI tests on this before I merge it.

**Review by cbuescher — APPROVED** [review]

**Comment by cbuescher** [comment]
@elasticmachine test this please

**Comment by diwasjoshi** [comment]
@cbuescher sorry my bad, I understand I should have mentioned it in the description. This is my first PR, will keep in mind such things for future PRs.

**Comment by cbuescher** [comment]
The PR is based on some older commit from February, so CI packaging tests cannot pass, but since this only touches docs and those tests ran sucessfully I think I will merge without rebasing in current master.

**Pull request merged**
