### PR TITLE
[ML] binary classification per-class feature importance for model inference

### PR DESCRIPTION
**Pull request by benwtrent**
This commit addresses two issues:

- per class feature importance is now written out for binary classification (logistic regression)
- The `class_name` in per class feature importance now matches what is written in the `top_classes` array.

### CODE REVIEW

**Review by dimitris-athanasiou — APPROVED** [review]
LGTM

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Comment by benwtrent** [comment]
run elasticsearch-ci/1

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Pull request merged**
