### PR TITLE
Clean up allowPartialSearchResults serialization

### PR DESCRIPTION
**Pull request by javanna**
When serializing allowPartialSearchResults to the shards through ShardSearchTransportRequest, we use an optional boolean field, though
the corresponding instance member is declared `boolean` which can never
be null. We also have an assert to verify that the incoming search
request provides a non-null value for the flag, and a comment explaining
that null should be considered a bug.

This commit makes the allowPartialSearchResults method in
ShardSearchRequest return a `boolean` rather than a `Boolean` and
changes the serialization from optional to non optional, in a bw comp manner.

### CODE REVIEW

**Review by jimczi — APPROVED** [review]
Good catch, LGTM

**Comment by javanna** [comment]
run elasticsearch-ci/default-distro please

**Comment by javanna** [comment]
run elasticsearch-ci/1 please

**Comment by javanna** [comment]
run elasticsearch-ci/2 please, green please.

**Pull request merged**
