### PR TITLE
Docs: Clarify constraints on scripted similarities.

### PR DESCRIPTION
**Pull request by jpountz**
Scripted similarities provide a lot of flexibility but they still need to obey
some rules to not confuse Lucene.

### CODE REVIEW

**Review by nik9000 — APPROVED** [review]
I'd be nice if we could enforce this kind of thing. This seems like a good way to really confuse folks. Reminds me of `transform` a little.

**Review by jimczi — APPROVED** [review]
LGTM
Can we at least ensure that scores are positive in a follow up ?

**Comment by jpountz** [comment]
> I'd be nice if we could enforce this kind of thing.

Yeah, do you have ideas how to do it?

> Can we at least ensure that scores are positive in a follow up ?

Do you mean something like adding assertions to ScriptedSimilarity that scores are positive?

**Comment by nik9000** [comment]
> Yeah, do you have ideas how to do it?

Not really.... Sorry! It'd be nice but I don't really know.

**Comment by jimczi** [comment]
> Do you mean something like adding assertions to ScriptedSimilarity that scores are positive?

Yes or even an hard exception to ensure that we don't miss documents if `track_total_hits` is false ?

**Comment by jpountz** [comment]
Unfortunately, we'd also miss documents if the function does not honor the constraints on freq and norm. Which is much harder to check.

**Pull request merged**
