### PR TITLE
Move parentTaskId into TransportRequest 

### PR DESCRIPTION
**Pull request by nik9000**
Now everything can have a parent if it wants one!

### CODE REVIEW

**Comment by nik9000** [comment]
@imotov this feels too easy....

**Comment by nik9000** [comment]
Going to clean it up a bit more, but the idea is ready....

**Comment by nik9000** [comment]
@imotov I think this is ready for review.

**Comment by imotov** [comment]
LGTM

**Comment by nik9000** [comment]
For anyone watching from the sidelines: both @imotov and I thought "this is too easy" and spent a while poking at it. Surprisingly, neither of us could find anything wrong. Which makes us both suspicious.

**Pull request merged**
