### PR TITLE
Handle Null in FetchSourceContext#fetchSource

### PR DESCRIPTION
**Pull request by jkakavas**
This change ensures that when null is passed as the value to one of
UpdateRequest#fetchSource `@Nullable` parameters, it is not wrapped in a 
String array. That would in turn cause a NPE when attempting to serialize 
FetchSourceContext as its constructor checks explicitly for Null and not for
arrays of Null objects.

In master, the problematic behavior was corrected as part of #29293

### CODE REVIEW

**Review by jakelandis — APPROVED** [review]
LGTM

**Comment by jkakavas** [comment]
@elasticmachine please run the gradle build tests 2 once more as the first time the worker run out of memory :panda_face:

**Comment by jkakavas** [comment]
@elasticmachine please run the gradle build tests 2, hopefully for the last time

**Comment by jkakavas** [comment]
Unstable network is unstable
```
 [6.5.5] 
 [6.5.5] FAILURE: Build failed with an exception.
 [6.5.5] 
 [6.5.5] * What went wrong:
 [6.5.5] A problem occurred configuring project ':distribution:packages'.
 [6.5.5] > Could not resolve all artifacts for configuration ':distribution:packages:classpath'.
 [6.5.5]    > Could not download xz.jar (org.tukaani:xz:1.5)
 [6.5.5]       > Could not get resource 'https://plugins.gradle.org/m2/org/tukaani/xz/1.5/xz-1.5.jar'.
 [6.5.5]          > Could not HEAD 'https://plugins.gradle.org/m2/org/tukaani/xz/1.5/xz-1.5.jar'. Received status code 504 from server: Gateway Time-out
 [6.5.5] 
 [6.5.5] * Try:
 [6.5.5] Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.
 [6.5.5] 
 [6.5.5] * Get more help at https://help.gradle.org
 [6.5.5] 
 [6.5.5] BUILD FAILED in 2m 54s
```
@elasticmachine please run the gradle build tests 2

**Pull request merged**
