### PR TITLE
Move ObjectPath, XContentSource and XContentUtils to core

### PR DESCRIPTION
**Pull request by romseygeek**
These are used by Watcher to return arbitrary JSON from third-party sources.  In order to use them
from the high-level rest client, they should be moved into core.

### CODE REVIEW

**Review by dakrone — APPROVED** [review]
LGTM

**Review by hub-cap — CHANGES_REQUESTED** [review]
moving things like this to `:server` is *not* going to work for us long term. A goal for us is to remove all dependency on `:server`, so it can be split up. If these need to be used by HLRC, then we should consider adding a dep to HLRC that is not `:server`, so that we can continue to use it once we split HLRC out.

**Comment by romseygeek** [comment]
> A goal for us is to remove all dependency on :server

I hadn't spotted the xcontent library module, I'll move it there instead.

**Comment by nik9000** [comment]
I don't think libs/x-content should have a lucene dependency. I think we should limit it to jackson if we can get away with it. 

Do we want them in the high level rest client at all?

**Comment by dakrone** [comment]
> I don't think libs/x-content should have a lucene dependency. I think we should limit it to jackson if we can get away with it.

Yes, we definitely don't want anything in `libs` to have any dependencies.

> Do we want them in the high level rest client at all?

If we *have* to have them for HLRC, we'll either have to have Lucene be a dep (which it is) and maybe just duplicate them there?

**Comment by nik9000** [comment]
I think the point of rewriting the request objects is that we don't need to add the deps if we can get away with it. I suspect we could represent them in another way on the high level rest client. Hopefully!

**Comment by romseygeek** [comment]
XContentSource is going to be tricky.  However, ObjectPath and XContentUtils have no dependencies, so how about I change this to move those two to lib/core.  For XContentSource, @nik9000 suggests that I move a cut-down version with no deps to HLRC, which I'll do separately.

**Comment by romseygeek** [comment]
> move those two to lib/core

By which I mean `lib/x-content`, of course.

**Review by hub-cap — APPROVED** [review]

**Pull request merged**
