### PR TITLE
Expose CheckedFunction and use it in a few places

### PR DESCRIPTION
**Pull request by javanna**
We already have `CheckedConsumer`, `CheckedFunction` is useful too. I exposed it and used it in a few places. It could be used in more places and replace some more custom functional interfaces, but it would also make things slightly less readable I'm afraid (e.g. ScoreFunctionParser, QueryParser where the method would be called apply instead of parse etc.).

### CODE REVIEW

**Review by nik9000 — APPROVED** [review]
Fine by me.

**Comment by javanna** [comment]
@jasontedor are you ok with this?

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by jasontedor** [comment]
I'm good with it, thanks for soliciting my input @javanna.

**Review by tlrx — APPROVED** [review]

**Pull request merged**
