### PR TITLE
URI parts processor handles URLs containing spaces

### PR DESCRIPTION
**Pull request by danhermann**
The URI parts processor uses the `java.net.URI` class to parse the input string which is fairly strict in its interpretation of the URI spec and it rejects such characters as non-URI-encoded spaces. In the interest of handling as broad a range of input data as possible, this change attempts to parse the input string using the `java.net.URL` class which is more lenient if the first attempt to parse with `java.net.URI` fails.

This fixes the issue raised in #70947.

### CODE REVIEW

**Comment by danhermann** [comment]
@elasticmachine update branch

**Review by jbaiera — APPROVED** [review]
LGTM

**Comment by danhermann** [comment]
Thanks, @jbaiera!

**Comment by gwbrown** [comment]
@danhermann Looks like we're good to remove `backport pending` from this PR, yes?

**Comment by danhermann** [comment]
> @danhermann Looks like we're good to remove `backport pending` from this PR, yes?

Not yet. I have a stack of PRs that I backported for 7.12.x ahead of the FF but I still need to backport them to 7.x. I'll get that done shortly.

**Pull request merged**
