### PR TITLE
Set prompts to be more consistent

### PR DESCRIPTION
**Pull request by nik9000**
Also a small amount of cleanup in the way we create VMs - just a bit less
repetition.

Prompts are always of the form "box:cwd$ ". Even for root. Which is ok because
you don't have to be that careful with root because these are VMs that you
can destroy and recreate quickly.

### CODE REVIEW

**Comment by nik9000** [comment]
Ping @tlrx or @dakrone for review - just a tiny bit of vagrant cleanup.

**Comment by dakrone** [comment]
@nik9000 you're just trying to get our Ruby percentage up over 0.1% so we can be truly polyglot right? Let me try to remember all the ruby I used to do for reviewing this... :)

**Comment by nik9000** [comment]
> @nik9000 you're just trying to get our Ruby percentage up over 0.1% so we can be truly polyglot right? Let me try to remember all the ruby I used to do for reviewing this... :)

Thanks! Its mostly shell in heredocs in ruby though. Which probably confuses github.

**Comment by tlrx** [comment]
LGTM

**Comment by dakrone** [comment]
Prompt stuff looks good to me too, however, I do get Vagrant failures for RPM removal on centos-7 - https://gist.github.com/dakrone/b499a9de41e76008a48b

**Comment by nik9000** [comment]
> Prompt stuff looks good to me too, however, I do get Vagrant failures for RPM removal on centos-7 - https://gist.github.com/dakrone/b499a9de41e76008a48b

I'm reasonably sure that is fixed in master and we'd have to rebase to get that passing on this pr. Or I could just merge it and master should just pass. Rather, master passes for me right now and should continue to do so with this merged in.

**Comment by dakrone** [comment]
+1, that's fine, this is only to change prompts

**Comment by nik9000** [comment]
Merged.

**Comment by colings86** [comment]
@nik9000 this doesn't seem to have been backported to the 2.0 branch. Should it be backported?

**Comment by nik9000** [comment]
Ahk. No it was supposed to be 2.1 only. I have no idea why I labeled it that way. There isn't really any advantage to pulling this into 2.0.

**Pull request merged**
