### PR TITLE
Log document id when MapperParsingException occurs

### LINKED ISSUE #37658: Log document id when MapperParsingException occurs
**Elasticsearch version**: ~~5.6~~ 6.x

Indexing a document using the java api may result in a `MapperParsingException`. When bulk-indexing, the problematic field-name is logged by elasticsearch (log-level has to be set to `debug`), but not the document-id. Indexing millions of documents it's hard to track down which specific document has the trouble. So, it would be nice to also have the document's `id` to get straight to the source.

### PR DESCRIPTION
**Pull request by dr0i**
Resolves #37658.

### CODE REVIEW

**Comment by mayya-sharipova** [comment]
@elasticmachine  test this please

**Comment by jasontedor** [comment]
This change is an enhancement targeting 5.6. We are no longer accepting enhancements to 5.6, only bug fixes. Please retarget your change to master so we can consider this pull request there. Note that this doesn’t imply we will pull this in, it still requires consideration after it targets an active development branch.

**Comment by mayya-sharipova** [comment]
@dr0i Would you be able to open a similar PR against master?  After that we can backport it to 6.x as well. 
I am going to close this PR, as not enhancements are accepted for 5.6

**Comment by dr0i** [comment]
@mayya-sharipova: opened against master, see #37800.

**Pull request closed without merging**
