### PR TITLE
Remove needless termsQuery implementation from StringFieldType

### PR DESCRIPTION
**Pull request by javanna**
The base class `TermBasedFieldType` already implements exactly the same `termsQuery` method, hence there is no need to override it.

### CODE REVIEW

**Review by romseygeek — APPROVED** [review]
LGTM, thanks Luca

**Comment by deepak5127** [comment]
Hi @javanna . I am new to GitHub contributions. Shall i work on this issue ?

**Comment by javanna** [comment]
hi @deepak5127 this is a reviewed PR, only waiting to be merged, so there isn't much left to be done. I would recommend looking at the [good first issue](https://github.com/elastic/elasticsearch/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) label if you have to contribute to Elasticsearch

**Comment by deepak5127** [comment]
Thanks @javanna

**Pull request merged**
