### PR TITLE
Re-enable EsqlActionBreakerIT

### LINKED ISSUE #100681: EsqlActionBreakerIT test failures
EsqlActionBreakerIT fails in a number of different ways. This issue intends to be a place to capture such failures, so that they can be analysed and worked on separately.

### PR DESCRIPTION
**Pull request by dnhatn**
Closes #100681

### CODE REVIEW

**Comment by dnhatn** [comment]
@elasticsearchmachine update branch

**Comment by dnhatn** [comment]
@elasticmachine update branch

**Comment by dnhatn** [comment]
It seems that we are not ready yet :(. It still fails after few iterations.

**Comment by ChrisHegarty** [comment]
I think that the changes to the test are good.   If you like you can leave the AwaitsFix, but merge the improvement to the test. That way we'll benefit from the test improvements during future debugging.

**Comment by dnhatn** [comment]
@ChrisHegarty I've pushed two more fixes in OrdinalsGroupingOperator, and this suite passed after 100 iterations. I am going to merge this PR. Thank you for your great collaboration as always.

**Pull request merged**
