### PR TITLE
Terms Lookup by Query/Filter (aka. Join Filter)

### PR DESCRIPTION
**Pull request by mattweber**
This PR adds support for generating a terms filter based on the field values
of documents matching a specified lookup query/filter.  The value of the 
configurable "path" field is collected from the field data cache for each 
document matching the lookup query/filter and is then used to filter the main 
query.  This is can also be called a join filter.

This PR abstracts the TermsLookup functionality in order to support multiple
lookup methods.  The existing functionality is moved into FieldTermsLookup and
the new query based lookup is in QueryTermsLookup.  All existing caching 
functionality works with the new query based lookup for increased performance.

During testing of I found that one of the performance bottlenecks was 
generating the Lucene TermsFilter on large sets of terms (probably since
it sorts the terms).  I have created a FieldDataTermsFilter that uses the
field data cache to lookup value of the field being filtered and compare it to
the set of gathered terms.  This significantly increased performance at the 
cost of higher memory usage.  Currently a TermsFilter is used when the number
of filtering terms is less than 1024 and the FieldDataTermsFilter is used
for everything else.  This should eventually be configurable or we need to
perform some test to find the optimal value.

Examples:

Replicate a has_child query by joining on the child's "pid" field to the
parent's "id" field for each child that has the tag "something".

```
curl -XPOST 'http://localhost:9200/parentIndex/_search' -d '{
    "query": {
        "constant_score": {
            "filter": {
                "terms": {
                    "id": {
                        "index": "childIndex",
                        "type": "childType",
                        "path": "pid",
                        "query": {
                            "term": {
                                "tag": "something"
                            }
                        }
                    }
                }
            }
        }
    }
}'
```

Lookup companies that offer products or services mentioning elasticsearch.
Notice that products and services are kept in their own indices.

```
curl -XPOST 'http://localhost:9200/companies/_search' -d '{
    "query": {
        "constant_score": {
            "filter": {
                "terms": {
                    "company_id": {
                        "indices": ["products", "services"],
                        "path": "company_id",
                        "filter": {
                            "term": {
                                "description": "elasticsearch"
                            }
                        }
                    }
                }
            }
        }
    }
}'
```

### CODE REVIEW

**Comment by eeeebbbbrrrr** [comment]
Is there still interest from ES in this becoming a real thing?

**Comment by kimchy** [comment]
@eeeebbbbrrrr there is, the main problem here is the probabilistic nature of it, by using a bloom filter (to reduce the overhead of data on the wire), I am personally still conflicted if this is the right way to go, since it can provide misleading results

**Comment by eeeebbbbrrrr** [comment]
(paid customer here).  I've told our support contact within ES that we're definitely interested in seeing this feature land.

Right now we're mimicking the functionality by executing SCAN+SCROLL queries and generating giant term queries inline with the primary query -- definitely inefficient.

Regarding the idea that "it can provide misleading results", that's definitely a deal breaker.  It doesn't matter how quickly or efficiently ES returns the wrong (or incomplete) answer.

However, I suspect that whatever this PR does, it's going to be WAY more efficient than our naive approach, even with something less network friendly than a bloom filter.

I intend to checkout this PR this weekend, get it current with 1.4, and see how it performs.  Since we already have something similar that is known to work, I'll port our code to use this feature (should be easy based on example DSL) and use that as a baseline for some benchmarks.

**Comment by kimchy** [comment]
@eeeebbbbrrrr I think your assumption that it will do something more efficient might be wrong, I mean, what happen is this request returns a 10 millions terms that needs to be filtered by? its making this feature generic that makes it difficult, and this is why @mattweber made an effort to work around this problem by using a bloom filter. Its not bad, just problematic in certain use cases.

I don't view a scan scroll and then a search to be a workaround, since it works in your specific case, compared to trying to provide a feature in the product itself that is simply tricky to implement in a generic fashion.

**Comment by eeeebbbbrrrr** [comment]
@kimchy This sort of thing is also quite tricky to implement out-of-product too (you should talk to Chris Earle offline about what we're doing).

Our implementation, and this is by design, is going to pull back all 10M terms if that is what is returned from the fielddata, so the idea that a similar ability that's built into ES would also do that is not bothersome (we also set ```index.query.bool.max_clause_count``` really high for this reason).

Anyways, ES could really benefit from a feature like this and I'm happy to do a bit of legwork to bring this PR current (with 1.4) and see what happens.

**Comment by rmuir** [comment]
Can we restrict the join operation per-shard? Meaning you have to do the right thing with document routing in order to use it? 

Because then that means such joins can be implemented more efficiently with respect to the number of terms, e.g. bitsets marking found ordinals and so on.

**Comment by kimchy** [comment]
@rmuir thats the spirit of parent child feature in ES, which tends to be enough in the context of relationships within shards. @mattweber when he opened this issue faced the need to do it cross shard as I assume the cost of denormalization was high (and the bloom filter constraint was good enough for that use case)

**Comment by rmuir** [comment]
Right, but the restriction can still apply, even if the indexes are separate, as long as the join is on the same node. For example, you can build global ordinals across the "termsenums" of two indexes... a form of join index so you can use ordinals everywhere.

**Comment by kimchy** [comment]
@rmuir aye, join between "ES" indices (and Lucene indices) is an option, this means a deployment of an index with 1 shard and replicas spanning all the nodes that another index that is partitioned is deployed on.

I remember bouncing that idea with @martijnvg and @imotov, we called this feature "follow index" (where an ES index follows another index in terms of allocation). It ended up being tricky as lifecycle issues proved to be hard to nail down (you need to have "atomic" availability of both shards of the different indices) and we just let it go for now as other matters were more pressing...

**Comment by kutchar** [comment]
@kimchy the "follow index" model could work if we were to narrow the scope of this to just being able to do cross shard parent/child queries (say all the parent docs are in 1 shard and the children could be in other shards, but all still located on the same node)? This way we might be able to share the parent ID cache between the shards.

**Comment by kimchy** [comment]
@kutchar yea, that was the idea, or even a 1 shard (partition) with N replicas, that holds reference data to do the join with, the follow index could conceptually allow for different deployment. It is an interesting feature to try and explore, but at least for now, the feeling is that its worth doing it down the road, and first figure out things like sequence ids and such

**Comment by mattweber** [comment]
@kimchy This supports the expensive send all terms approach as well.  The bloom filter is an optional and I added that with options for the user to control the settings thinking this might be acceptable for some use cases.  I can always take this out if it will move the PR forward.

If there is still interest in this PR still, I can get it up to date with the latest master.  I *think* all the recent circuit breaker work thats been done might have everything I need to integrate it into this patch.  If there is no hope of ever getting the PR merged, I could investigate moving it out into a plugin as well.

I like the "follow index" idea, but my original goal for this PR was to be able to do cross-node/shard/index parent/child queries without any special mappings or risk of "hot" shards.

/cc @eeeebbbbrrrr

**Comment by rbraley** [comment]
For what it’s worth, I am definitely still interested in this PR :)


Ryan Braley  |  Founder 
http://traintracks.io/
US: +1 (206) 866 5661



CN: +86 185 1129 5661



Coding the future. Decoding the game.

**Comment by kimchy** [comment]
@mattweber the problem with the full mode is that people can ask for something that returns millions of terms, which means streaming, representing it in memory, and using a terms / boolean query out of it, this is concerning... .

**Comment by rbraley** [comment]
I am ok with approximate results with tunable parameters. Presumably people who need exact results can pay for the hardware to make that happen and just set the precision really high, like use very large bloom filters. Perhaps there could be an indication of the false positive rate in the output.


Ryan Braley  |  Founder 
http://traintracks.io/
US: +1 (206) 866 5661



CN: +86 185 1129 5661



Coding the future. Decoding the game.

**Comment by mattweber** [comment]
@kimchy I agree, that's why @martijnvg and I wanted to get breakers integrated but it turned out to be easier said than done.

**Comment by kimchy** [comment]
@mattweber agreed, that would help a lot with breakers controlling it, probably the request circuit breaker, ping us when/if you get a chance to update the PR, I would love to have a look

**Comment by gomesla** [comment]
FWIW I would like to see this functionality as well as this is a fairly common use case in the E-Discovery world. Often for each document a "family" hash is calculated. There can be multiple hashes per document 
- one for document relationships i.e. parent child, typically children get the root parent hash. Useful in container like documents like email
- one for email thread relationships
- custom ones based of various field for duplicate detection
The idea is at search time you want not only the current document but it's related "family" documents based on the specified field. Typically speed while important is not as much of an issue as accuracy in this case, and memory consumption would not be as big of an issue either for the users of this functionality.

Thus common queries would be find all email's containing xyz and pull in all attachments or parent emails if the hit is a attachment, or find all documents containing "xyz" and the related threads. This is a pretty basic and fundamental piece of functionality. Doing the join at the application layer means paging and facets get messy.

**Comment by hiro4848** [comment]
Is there any update on this PR? (timeline, roadmap, etc)

**Comment by kerwin** [comment]
+1

**Comment by thihy** [comment]
+1

**Comment by pwain** [comment]
+1

**Comment by yehosef** [comment]
It seems SIREn has implemented joins as a plugin based on this request.  See 
https://github.com/sirensolutions/siren-join  
http://siren.solutions/relational-joins-for-elasticsearch-the-siren-join-plugin/

**Comment by mrkamel** [comment]
+1

**Comment by pwain** [comment]
Thanks for the heads-up regarding Siren @yehosef . I took it for a quick spin and it seems to work well!   At the very least it cuts out a round trip between the cluster and the client for single join scenarios.

**Comment by dakrone** [comment]
@mattweber now that a lot of the query refactoring work has been done, is there still interest in pursuing this pull request? (it may need to be rewritten with all the changes in master lately)

**Comment by jezell** [comment]
Please. I'm sure a lot of people would love to see this added. Siren works well, but would be very nice to have this out of the box.

**Comment by vsizov** [comment]
Yes, I would love to see it out of the box as well.

**Comment by dakrone** [comment]
Closing this as we didn't receive any feedback from the author

**Comment by JDvorak** [comment]
noooooo

**Comment by brusic** [comment]
Either way, I want to thank @mattweber for this PR and trying. I am sure this type of functionality will eventually be part of Elasticsearch.

**Comment by gcampbell-epiq** [comment]
+1
There's lots of interest. Reopen?
https://github.com/elastic/elasticsearch/issues/23713

**Comment by clintongormley** [comment]
@gcampbell-epiq not until somebody comes up with a way to do this that is horizontally scalable

**Comment by yehosef** [comment]
@clintongormley  - I'm not sure if this a viable option or totally related, but here is a way I had been considering adding joins to ES that is horizontally scalable (I think..).  It's a different approach that this - you can decide if it's helpful/relevant/crazy.

You have the ability to insert with a query (sort of - the reindex api) and update with a query.   If you had the ability to do an UPSERT with a query you could relatively easily do large joins.

Let's say I have a index (“sales”) with products users have bought and I want to find people that bought product x and product y (not in the same purchase).  You can do an upsert by query of the mem_ids that bought product x, with the mem_id as the doc_id in a new index (call it “tmp_join_sales_123”).  The doc json would look like {product_x:true}.  You would then do the same thing for product y - the data would be {product_y:true}. 

The data would be one of three forms {product_x:true}, {product_y:true}, or {product_x:true,product_y:true}. 

The join query would then be like:
GET tmp_join_sales_123/_search?q=product_x:true%20AND%20product_y:true

It is a little more indirect because you are actually creating a temp index for the join, but I think that's what saves it for large data sets.  It seems to me the general approach would be very powerful.  The main functionality that missing is UPSERT by query.

This obviously doesn’t need the two indices to be the same, just that they have a common element - which is the basis of any join.  If the join conditions are complex you could serialize or hash it.  If you need extra data in the results of the query other than the mem_id, you could add it to data both queries write to the tmp index.

**Comment by clintongormley** [comment]
@yehosef yes, this is similar to an approach we have been considering (/cc @costin ) but is quite different to what has been proposed in this PR

**Comment by yehosef** [comment]
@clintongormley - great to hear.  It seems to me that it shouldn't be too complicated to implement, but I'm not sure.  

There's a different product I'm playing with now (under NDA - can't say what) that can do broad joins in elasticsearch, but I think having this capability internal would probably perform better for big data sets.

**Pull request closed without merging**
