### PR TITLE
Reindex avoid public cancel method

### PR DESCRIPTION
**Pull request by henningandersen**
CancellableTask.cancel is no longer public (as it used to be).

Relates #42612 and #47335

### CODE REVIEW

**Comment by henningandersen** [comment]
DNS issues caused failures.
@elasticmachine run elasticsearch-ci/1
@elasticmachine run elasticsearch-ci/bwc
@elasticmachine run elasticsearch-ci/default-distro

**Review by Tim-Brooks — COMMENTED** [review]
I guess I'm not clear if this works? I understand that the `Reindexer` will interrogate the `isCancelled()` method which means that it will know if assignment conflict has occurred. 

But there is `onCancelled` behavior in the `BulkByScrollTask` which will not be triggered?

```java
    @Override
    public void onCancelled() {
        /*
         * If this task is a leader, we don't need to do anything extra because the cancel action cancels child tasks for us
         * If it's is a worker, we know how to cancel it here
         * If we don't know whether it's a leader or worker yet, we do nothing here. If the task is later set to be a worker, we cancel the
         * worker at that time.
         */
        if (isWorker()) {
            workerState.handleCancel();
        }
    }
```

**Comment by henningandersen** [comment]
Thanks for catching that @tbrooks8. I have amended this to ensure `onCancelled` is called (also for regular cancel) and clarified the slicing behaviour through an assert. I think this is ready for another round (though CI might prove me wrong).

**Review by Tim-Brooks — APPROVED** [review]
LGTM

**Comment by henningandersen** [comment]
Yet another instance of TransportStopped, we will need to fix this soon'ish...
@elasticmachine run elasticsearch-ci/1

**Pull request merged**
