### PR TITLE
Avoid NPE in `more_like_this` when field has zero tokens

### LINKED ISSUE #30148: More Like This queries return 0 results if field in source document has 0 tokens in analyzed field
**Elasticsearch version**: 6.2.4

**Plugins installed**: []

**JVM version**: 1.8.0_101

**OS version**: MacOS (Darwin Kernel Version 15.6.0)

**Description of the problem including expected versus actual behavior**:
"More Like This" queries do not return any results when a field on the source document produces no tokens at index time. Using a keyword field and manually specifying the analyzer at query time works as expected.

**Steps to reproduce**:
```
PUT test
{
  "mappings": {
    "type": {
      "properties": {
        "myField": {
          "type": "text"
        },
        "empty": {
          "type": "text"
        }
      }
    }
  }
}
```

```
POST /_bulk
{ "index":  { "_index": "test", "_type": "type","_id":1}}
{"myField":"and_foo", "empty":""}
{ "index":  { "_index": "test", "_type": "type","_id":2}}
{"myField":"and_foo", "empty":""}
```

This query correctly returns 1 result:
```
GET /_search
{
  "query": {
    "more_like_this": {
      "fields": [
        "myField"
      ],
      "like": [
        {
          "_index": "test",
          "_type": "type",
          "_id": "1"
        }
      ],
      "min_term_freq": 1,
      "min_doc_freq": 1
    }
  }
}
```

This query returns no results when using both fields:
```
GET /_search
{
  "query": {
    "more_like_this": {
      "fields": [
        "myField", "empty"
      ],
      "like": [
        {
          "_index": "test",
          "_type": "type",
          "_id": "1"
        }
      ],
      "min_term_freq": 1,
      "min_doc_freq": 1
    }
  }
}
```

If you update the "empty" field in document 1 to contain non-analyzable characters (like punctuation), the first query still gives 0 results. Changing the "empty" field to be a keyword field works as expected.

### PR DESCRIPTION
**Pull request by aditya-agrawal**
Closes #30148 
 
At this point ->
https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/action/termvectors/TermVectorsWriter.java#L69
fieldTermVector is getting null in case of empty field. I initialized fieldTermVector with EMPTY_TERMS in case of null. This solves both the given issue given in the ticket.

### CODE REVIEW

**Comment by karmi** [comment]
Hi @aditya-agrawal, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/elasticsearch/pull/30365.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by aditya-agrawal** [comment]
Done.

**Comment by aditya-agrawal** [comment]
@karmi can you please review the PR and let me know if I need to change anything?

**Review by cbuescher — CHANGES_REQUESTED** [review]
Hi @aditya-agrawal, thanks for opening this PR. In order to get this merged, we would need at least some unit tests that show that this fixes the reported issue. I'm not sure if TermVectorsWriter#setFields can be tested individually, for the NPE this might be possible.
For the whole two fields scenario described in the issue it probably makes sense to add something similar to MoreLikeThisIT, although a unit test would be prefered as well if possible.

**Comment by aditya-agrawal** [comment]
Okay @cbuescher I am working on it.

**Comment by aditya-agrawal** [comment]
@cbuescher I have written the integration test for the two field scenario given in the ticket. 
Since I have given a default value to the field that was giving null it will no more throw NPE. Not sure how can I write unit test here to prove this.

**Review by cbuescher — APPROVED** [review]
Thanks for the test, LGTM. I left one super tiny nit-pick, nothing to really worry about. I will kick of a full CI test run to see if anything else turns up.
Could you add a line mentioning this PRs title and number similar to e.g. https://github.com/elastic/elasticsearch/pull/29641/files#diff-297418c07078d2b31d8e94a7d34b5255 to the docs/CHANGELOG.asciidoc. I think this fix should also be backported to the next 6.x branches. At the moment I believe this means putting the same entry in two places (under 7.0 and 6.4). I will edit the title slightly so make it a bit shorter. Thanks a lot.

**Comment by cbuescher** [comment]
@elasticmachine test this please

**Comment by aditya-agrawal** [comment]
@cbuescher I have made the suggested changes.

**Comment by cbuescher** [comment]
@elasticmachine test this please

**Comment by cbuescher** [comment]
@aditya-agrawal thanks a lot, merged to master and the upcoming 6.4 branch.

**Pull request merged**
