### PR TITLE
Retain word based chunking strategy as default for endpoints created before 8.16

### PR DESCRIPTION
**Pull request by dan-rubinstein**
A bug was found where we were not retaining the old word based chunking strategy that was the default for endpoints created pre-8.16. This change fixes the logic so that the pre-8.16 endpoints remain untouched.

### CODE REVIEW

**Review by maxhniebergall — APPROVED** [review]
LGTM

**Review by prwhelan — APPROVED** [review]

**Comment by dan-rubinstein** [comment]
@elasticmachine merge upstream

**Comment by dan-rubinstein** [comment]
@elasticmachine merge upstream

**Comment by davidkyle** [comment]
@dan-rubinstein should this PR be in the main branch too? I don't see the change in main and this looks like a good fix

**Comment by dan-rubinstein** [comment]
> @dan-rubinstein should this PR be in the main branch too? I don't see the change in main and this looks like a good fix

Yes, I've added it as part of the [feature flag removal PR](https://github.com/elastic/elasticsearch/pull/115675/)

**Pull request merged**
