### PR TITLE
Fix Painless def [char] to String casts

### PR DESCRIPTION
**Pull request by jdconrad**
This fix allows def [char] to be explicitly cast to String and def [String] to be explicitly cast to char as per our spec documentation.  This also adds appropriate tests and cleans up some of the error messages for def casting.

### CODE REVIEW

**Comment by jdconrad** [comment]
@elasticmachine run elasticseearch-ci/1 elasticsearch-ci/bwc

**Comment by jdconrad** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by jdconrad** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by jdconrad** [comment]
@elasticmachine run elasticsearch-ci/default-distro

**Comment by jdconrad** [comment]
@elasticmachine run elasticsearch-ci/default-distro

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by jdconrad** [comment]
@rjernst Thanks for the review!

**Pull request merged**
