### PR TITLE
[6.8] Upgrade to log4j 2.17.1

### PR DESCRIPTION
**Pull request by costin**
Relates #82111

### CODE REVIEW

**Comment by costin** [comment]
@elasticmachine run elasticsearch-ci/rest-compatibility

**Comment by costin** [comment]
@elasticmachine run elasticsearch-ci/eql-correctness

**Comment by costin** [comment]
@elasticmachine update branch

**Comment by ChadJessup** [comment]
@costin - will this be 6.8.23 or is the release note on 6.8.22 listing 2.17.0 incorrect at: https://www.elastic.co/guide/en/elasticsearch/reference/6.8/release-notes-6.8.22.html

Thank you for all the awesome work on this!

**Comment by costin** [comment]
6.8.22 has already been released (Dec 19th) and the release notes are accurate.
See https://www.elastic.co/blog/new-elasticsearch-and-logstash-releases-upgrade-apache-log4j2 for more information.
log4j 2.17.1 was released on Dec 28th and while this PR incorporates it, there hasn't any official ES release that incorporates the change. Do note the CVE fixed in log4j 2.17.1 is significantly less serious than those fixed in 2.17.0.

Hope this helps.

**Comment by vimalk78** [comment]
@costin is there a plan to release a 6.8.z release which uses log4j 2.17.1 ?

**Comment by costin** [comment]
@vimalk78 yes, see the latest updates at https://ela.st/log4j

**Pull request merged**
