### PR TITLE
Make classes+methods that can be static static in many spots

### PR DESCRIPTION
**Pull request by original-brownbear**
Just some quick static analysis+fixing here after seeing warnings about this stuff left and right for years :) Not much in terms of code changes besides adding the `static` keywords with the exception of some simplifications
to some of the search objects that don't need the search controller instance
passed down in many spots.
This was done mostly automatically by the IDE but some quick manual inspection shows
quite a few spots where this should make things behave better via things like making lambdas
non-capturing and it just generally makes the code easier to follow.

### CODE REVIEW

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/packaging-tests-windows-sample (random Jenkins issue)

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/packaging-tests-windows-sample (random Jenkins issue)

**Comment by original-brownbear** [comment]
elasticsearch-ci/packaging-tests-windows-sample

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/packaging-tests-windows-sample

**Comment by rjernst** [comment]
I skimmed this, and the premise seems good as long as it compiles and tests pass. LGTM.

**Comment by original-brownbear** [comment]
Thanks Ryan!

**Pull request merged**
