### PR TITLE
Eclipse gradle build ElasticSearch problem (Not found JAVA_HOME)

### LINKED ISSUE #17554: Eclipse gradle build ElasticSearch problem (Not found JAVA_HOME)
In my console, echo $JAVA_HOME is correct path.
I changed 
buildSrc/src/main/groovy/org/elasticsearch/gradle/BuildPlugin.groovy

eclipse can not set JAVA_HOME, like intellij. but the following code only judge intellij. is it a bug?

+                   if (System.getProperty("idea.active") != null) {
+                       // intellij doesn't set JAVA_HOME, so we use the jdk gradle was run with
+                   } else {
+                       throw new GradleException('JAVA_HOME must be set to build Elasticsearch')
+                   }

### PR DESCRIPTION
**Pull request by chilly**
@nik9000 I fixed #17554.

### CODE REVIEW

**Comment by nik9000** [comment]
@rjernst do you have an opinion on this? My understanding is that it gets the Eclipse gradle plugin's launcher working properly in the same way that IntelliJ's works. I've never encountered this because I, and presumably all the other Eclipse folks, run gradle on the command line. I don't think it can hurt but we don't want to spend forever supporting some unsupported way of running gradle when there is a perfectly good other way (the console) otoh we already do this for IntelliJ and it is simple so why not?

**Comment by rjernst** [comment]
I'm fine with adding the same check for eclipse, but note that when I tried buildship many months ago (shortly after it was released, when first working on the gradle migration) there were lots of problems.  There is really no way for us to test this check (for eclipse or intellij) so it will always be at risk of "breaking".

**Comment by rjernst** [comment]
Also note that eclipse should be a better user of java and actually set JAVA_HOME. It is ridiculous that IntelliJ does not.

**Comment by chilly** [comment]
It is not Eclipse or Intellij's mistake for JAVA_HOME. It may be a bug of gradle plugin. When I run java application to print System.getenv("JAVA_HOME") in eclipse or Intellij, it will not be null. But when I execute gradle plugin, groovy script only get null from System.getenv("JAVA_HOME").

**Comment by dakrone** [comment]
@rjernst do you know if this still applies and if this should be merged?

**Comment by rjernst** [comment]
I don't use eclipse so I'm not the best to check this.

**Comment by dakrone** [comment]
Okay, I *think* @nik9000 uses Eclipse, Nik do you know?

**Comment by nik9000** [comment]
> Okay, I think @nik9000 uses Eclipse, Nik do you know?

I do indeed use Eclipse. I don't use Eclipse's built in launcher for gradle though. I just tried and indeed it fails because it doesn't have JAVA_HOME.

**Comment by nik9000** [comment]
> I just tried and indeed it fails because it doesn't have JAVA_HOME.

And when I apply this patch it works.

I don't expect to start using the launcher more now that it isn't broken, but I'm happy to merge this now that I know it helps.

**Comment by nik9000** [comment]
Merged! Thanks for fixing it @chilly. I'm sorry this took so long to get to!

Master: 4cf4683a64b26bf12365dbe46abac177fe66efbd
5.x: 88fa4840cb385dd78b7702e53918d6d4efeec796
5.0: c59fd49d053e15c30fb0b0803dfa19d162871376

**Comment by arastoul** [comment]
Hi,

Just to mention a workaround for people who want to run elasticsearch gradle build from intellij and still run into the 'JAVA_HOME' not set error, even with this patch.

I had to add an option in IntelliJ Gradle settings to take into account this plugin modification:
In IntelliJ File menu/Settings/Gradle/VM Options 
add option: -Didea.active=true
I prefer to add it here instead of some other properties files  because I sometimes run gradle from command line.
HTH

**Pull request merged**
