### PR TITLE
Drop references to deprecated logger

### PR DESCRIPTION
**Pull request by nik9000**
This drops all remaining references to `BaseRestHandler.logger` which
has been deprecated for something like a year now. I replaced all of the
references with locally declared loggers which is so much less spooky
action at a distance to me.

### CODE REVIEW

**Comment by nik9000** [comment]
This is a migration that I started more than a year ago. It looks like for the most part folks have finished it off but there is just a little left. I hope I'm not stepping on anyone's toes!

**Comment by nik9000** [comment]
Compilation error is real. Serves me right for opening a PR without finishing up precommit.

**Review by tvernum — APPROVED** [review]
LGTM

**Comment by nik9000** [comment]
Thanks @tvernum !

**Pull request merged**
