### PR TITLE
Sometimes use token authc in RCS tests

### PR DESCRIPTION
**Pull request by n1v0lg**
Boosting test coverage by randomly using token authentication to initiate cross cluster search in remote cluster security REST test.

### CODE REVIEW

**Review by slobodanadamovic — APPROVED** [review]
LGTM

**Comment by n1v0lg** [comment]
@elasticmachine update branch

**Comment by n1v0lg** [comment]
@elasticmachine update branch

**Comment by n1v0lg** [comment]
@elasticmachine update branch

**Comment by n1v0lg** [comment]
@elasticmachine update branch

**Pull request merged**
