### PR TITLE
[DOCS][ESQL] Include bucket in STATS...BY supported functions

### PR DESCRIPTION
**Pull request by leemthompo**
This omission was flagged by @stratoula 🙏

### CODE REVIEW

**Review by nik9000 — APPROVED** [review]

**Review by alex-spies — CHANGES_REQUESTED** [review]
Heya, sorry for the blocking review but bucket is included in the grouping functions, displayed right below the agg functions.

Bucket is not an agg function and cannot be used in places where an agg function can be used. Are we sure we want to mention it in the docs next to the other agg functions?

**Comment by stratoula** [comment]
This feedback was given to me by people who were looking the stats by command and could not locate the date histogram. As it is used for grouping (and I am expecting to be a popular operation) I think it should be mentioned there. Or a reference to it. Because bucket in the agg functions doesnt help the users to understand

**Comment by leemthompo** [comment]
@alex-spies you're totally right in that case. It's because I'm including the same list of functions here, but what I can do is just add `bucket` to the STATS....BY list manually so it doesn't show up in both the agg and group functions.

**Comment by alex-spies** [comment]
Ah, I see the problem! Agree, as a user I'd expect to find this here
image

@leemthompo adding this manually under the STATS ... BY ... list sounds good to me!

**Comment by leemthompo** [comment]
@alex-spies thanks for the eagle eye. Should be good now!

**Review by alex-spies — APPROVED** [review]
Thanks for the iteration @leemthompo , looks great!

**Comment by leemthompo** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.15|[](https://github.com/elastic/elasticsearch/pull/112550)|
|✅|8.14|[](https://github.com/elastic/elasticsearch/pull/112551)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
