### PR TITLE
Normalize paths for stable plugin test

### LINKED ISSUE #90793: [CI] StableBuildPluginPluginFuncTest can scan and create named components file failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/3zut2ls7dbaeo/tests/:integTest/org.elasticsearch.gradle.plugin.StableBuildPluginPluginFuncTest/can%20scan%20and%20create%20named%20components%20file

**Reproduction line:**
`null`

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.gradle.plugin.StableBuildPluginPluginFuncTest&tests.test=can%20scan%20and%20create%20named%20components%20file

**Failure excerpt:**
```
org.gradle.testkit.runner.UnexpectedBuildFailure: Unexpected build execution failure in C:\Users\jenkins\AppData\Local\Temp\junit14268935253052567477 with arguments [:assemble, -Dtest.external=true]

Output:

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\jenkins\AppData\Local\Temp\junit14268935253052567477\build.gradle' line: 13

* What went wrong:
Could not compile build file 'C:\Users\jenkins\AppData\Local\Temp\junit14268935253052567477\build.gradle'.
> startup failed:
  build file 'C:\Users\jenkins\AppData\Local\Temp\junit14268935253052567477\build.gradle': 13: Unexpected character: '\'' @ line 13, column 38.
                     implementation files('C:\Users\jenkins\AppData\Local\Temp\junit14268935253052567477\jars\plugin-api.jar')
                                          ^
  
  1 error


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 129ms

  at org.gradle.testkit.runner.internal.DefaultGradleRunner.lambda$build$2(DefaultGradleRunner.java:264)
  at org.gradle.testkit.runner.internal.DefaultGradleRunner.run(DefaultGradleRunner.java:338)
  at org.gradle.testkit.runner.internal.DefaultGradleRunner.build(DefaultGradleRunner.java:262)
  at org.elasticsearch.gradle.internal.test.InternalAwareGradleRunner.build(InternalAwareGradleRunner.java:145)
  at org.elasticsearch.gradle.internal.test.ConfigurationCacheCompatibleAwareGradleRunner.build(ConfigurationCacheCompatibleAwareGradleRunner.java:153)
  at org.elasticsearch.gradle.internal.test.NormalizeOutputGradleRunner.build(NormalizeOutputGradleRunner.java:147)
  at org.elasticsearch.gradle.plugin.StableBuildPluginPluginFuncTest.can scan and create named components file(StableBuildPluginPluginFuncTest.groovy:99)

```

### PR DESCRIPTION
**Pull request by pgomulka**
gradle on windows does not like `\`. Normalized method should replace it with `/` 
closes #90793

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against main? Unless there is a good reason otherwise, we prefer pull requests against main and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by craigtaverner** [comment]
Looking at the actual error message in the failing builds, it looks like it is not complaining about the backslash, but about the single quote.

```
build file 'C:\Users\jenkins\AppData\Local\Temp\junit7764138547418743194\build.gradle': 13: Unexpected character: '\'' @ line 13, column 38. |  
  | implementation files('C:\Users\jenkins\AppData\Local\Temp\junit7764138547418743194\jars\plugin-api.jar') |  
                                       ^
```

The Unexpected character is described as the single quote: `'\''`
Since they quote the single quote with more single quotes, they also escape it with a backslash, so it is hard to read. But they repeat this in the last line of the error by putting the caret under the first single-quote.

Perhaps this PR should instead replace single-quotes with double-quotes?

**Comment by breskeby** [comment]
I've added the 'test-windows' tag to check the test is passing on windows indeed. At the moment it seems to not even compile correctly @pgomulka

**Comment by pgomulka** [comment]
@elasticmachine run elasticsearch-ci/part-2-windows

**Comment by pgomulka** [comment]
@elasticmachine update branch

**Comment by pgomulka** [comment]
@elasticmachine update branch

**Review by breskeby — APPROVED** [review]
I'd use File.pathSeparator to simplify things but not deal breaker

**Comment by pgomulka** [comment]
> The Unexpected character is described as the single quote: '\''
Since they quote the single quote with more single quotes, they also escape it with a backslash, so it is hard to read. But they repeat this in the last line of the error by putting the caret under the first single-quote.

I think the message in gradle error is misleading. The underlying problem is about `/` but it points at the single quote `'`

**Pull request merged**
