### PR TITLE
More actionable error for ancient indices

### PR DESCRIPTION
**Pull request by DaveCTurner**
We've had a few reports of failed upgrades caused by deleting the last ancient index just before stopping the first node, which may not have allowed enough time for the deletion to complete. Today the resulting error message doesn't say how to address this, which leaves users struggling mid-upgrade. This commit makes the error message more actionable.

### CODE REVIEW

**Review by thecoop — APPROVED** [review]
LGTM

**Review by rjernst — APPROVED** [review]
One minor suggestion on wording.

**Review by grcevski — APPROVED** [review]
LGTM!

**Comment by emilynunity3d** [comment]
Thank you! This will be really helpful for folks that run into this 😃

**Pull request merged**
