### PR TITLE
[Connector API] Remove deprecated feature fields

### PR DESCRIPTION
**Pull request by jedrazb**
### Changes

`filtering_advanced_config` and `filtering_rules` properties have been deprecated a long time ago, we can remove them from internal Connector representation. Note, if those fields are present under `features` property of a Connector document, the parser will just ignore them as they are unknown.

This is a cleanup PR,  I will follow up with implementation of `_features` endpoint to set connector features. 

### Valdiation
- Unit tests adapted
- No changes in e2e tests
- Tested locally

### CODE REVIEW

**Comment by jedrazb** [comment]
@elasticsearchmachine run elasticsearch-ci/part-1

**Review by artem-shelkovnikov — APPROVED** [review]
I think it's a good change, but might be also worth to check with the team to acknowledge that we might have SDH in case something is migrated incorrectly. Maybe also possible to collect get telemetry data about it? I have a feeling that we were at least talking about it back then.

**Comment by jedrazb** [comment]
> I think it's a good change, but might be also worth to check with the team to acknowledge that we might have SDH in case something is migrated incorrectly. Maybe also possible to collect get telemetry data about it? I have a feeling that we were at least talking about it back then.

@artem-shelkovnikov just for clarity, this PR won't purge any the deprecated features from the index. The connector API will still return deprecated features from GET / LIST endpoints. We just won't support modifying the deprecated features via the API call. This means cleaner code and less documentation for us to support

**Comment by artem-shelkovnikov** [comment]
Thanks for the explanation, makes a lot of sense!

**Comment by jedrazb** [comment]
@elasticsearchmachine merge upstream

**Pull request merged**
