### PR TITLE
Remove a copy of IndexNameGenerator.generateValidIndexName()

### PR DESCRIPTION
**Pull request by sabi0**
`GenerateUniqueIndexNameStep` contained the exact copies of the `generateValidIndexName()` and `generateValidIndexSuffix()` methods from the `IndexNameGenerator` utility class.

I removed the duplicates and changed the code to use the utility method instead.
Also added javadoc and switched to a pre-compiled `Pattern`.

The test was also broken as it checked the suffix to consist of _only_ illegal characters.
Replacing `matches()` with `find()` makes it check for presence of _at least one_ illegal character.

### CODE REVIEW

**Comment by pgomulka** [comment]
can you provide description of the PR?

**Comment by williamrandolph** [comment]
buildkite test this

**Comment by williamrandolph** [comment]
@elasticsearchmachine update branch

**Comment by williamrandolph** [comment]
@elasticmachine update branch

**Comment by williamrandolph** [comment]
@elasticsearchmachine ok to test

**Comment by williamrandolph** [comment]
buildkite test this

**Comment by williamrandolph** [comment]
buildkite test this

**Review by williamrandolph — APPROVED** [review]
This PR looks good -- improves our code and fixes a small bug in test code.

**Pull request merged**
