### PR TITLE
x-pack:apm-data module should mention it is for APM Server

### PR DESCRIPTION
**Pull request by pgomulka**
apm-data module should be more explicit that it is for the apm server usage. It is confusing when starting up ES to see `APM is disabled` log line. Especially since we also have :modules:apm which is meant to be for sending apm metrics and traces

This commit rephrases the log messages and rename APMPlugin class to mention APM Server.

### CODE REVIEW

**Review by ldematte — APPROVED** [review]
LGTM, much clearer now

**Review by stu-elastic — APPROVED** [review]
lgtm

**Review by axw — COMMENTED** [review]
I avoided "APM Server" because it will be used in serverless too, by MIS. It has more to do with the data (hence why it's called the "APM data" plugin) and less to do with the data source.

Would it be clear enough to change the plugin name to APMDataPlugin? And the message to "APM Data plugin is {}"?

**Comment by pgomulka** [comment]
> I avoided "APM Server" because it will be used in serverless too, by MIS. It has more to do with the data (hence why it's called the "APM data" plugin) and less to do with the data source.
Would it be clear enough to change the plugin name to APMDataPlugin? And the message to "APM Data plugin is {}"?

I personally find APMData not clear enough. It is used by apm server to store its data after all, right?
why the use of this plugin in serverless be conflicting with the name `apm server` ? (I see the contradiction in 'server-less' and apm-server :) ). It is serverless for the users, for Elasticserach node it is a data needed for 'apm server'.

**Review by axw — APPROVED** [review]
Thanks @pgomulka, and sorry for causing confusion!

**Pull request merged**
