### PR TITLE
Upgrade repository-hdfs to Hadoop 3

### PR DESCRIPTION
**Pull request by masseyke**
This upgrades the repository-hdfs plugin to hadoop 3. Tests are performed against both hadoop 2 and hadoop 3 HDFS. The advantages of using the hadoop 3 client are:
Over-the-wire encryption works (tests coming in an upcoming PR).
We don't have to add (or ask customers to add) additional jvm permissions to the elasticsearch jvm
It's compatible with java versions higher than java 8
Relates #76897

### CODE REVIEW

**Comment by masseyke** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by jbaiera** [comment]
Are there any spots you would like double checked in this backport?

**Comment by masseyke** [comment]
> Are there any spots you would like double checked in this backport?

Oh right, I should have mentioned that. I think that the only real difference was that we're supporting java 8 here, so the test fixture's build.gradle required some work that was not in the original PR to avoid using the jvm flags that did not exist in java 8.
I also ran into #78703 locally with this one, but created that as a separate PR so you can ignore it for this.

**Review by jbaiera — APPROVED** [review]
If that's the only change I think this is fine to go in (assuming happy CI)

**Pull request merged**
