### PR TITLE
Remove -Xlint:-deprecation from all but core

### LINKED ISSUE #15829: Remove deprecated ec2 proxy settings
The following settings have been deprecated for a while and can likely be removed in 3.0:

* cloud.aws.proxy_host --> cloud.aws.proxy.host
* cloud.aws.proxy_port --> cloud.aws.proxy.port
* cloud.aws.ec2.proxy_host --> cloud.aws.ec2.proxy.host
* cloud.aws.ec2.proxy_port --> cloud.aws.ec2.proxy.port

### PR DESCRIPTION
**Pull request by nik9000**
Gets a few other Xlints while I'm in there but mostly just deprecation. For the most part I isolate the deprecation and leave a comment. Either the comment is an admission of why we still need to use the deprecated method or a link to an issue.

Closes #15829

### CODE REVIEW

**Comment by rjernst** [comment]
LGTM

**Comment by dadoonet** [comment]
Does this change mean that we won't see anymore in the IDE when we are using deprecated fields/methods?
I found it was useful seeing that and reporting that when coding.

**Comment by nik9000** [comment]
> Does this change mean that we won't see anymore in the IDE when we are using deprecated fields/methods?

It means you won't see the warnings in the scopes that I've annotated with `@SuppressWarnings("deprecation")` but you'll still see them if you use them in a new place. To me `@SuppressWarnings("deprecation")` means "I know I'm using deprecated methods in here and I'm ok with that. So I tried to keep the scope of those annotations pretty small. I didn't do it very well in some cases though.

I think if we want something to remind us to remove the deprecated fields on upgrade we can add a unit test that fails if the version is too great. That way when we bump the version number we **know** we have to remove the code. We might not be able to remove it in the commit that bumps the version numbers but we can `@AwaitsFix` the test then if we have to. Right now we forget to remove deprecated stuff.

**Comment by dadoonet** [comment]
It looks like a fantastic plan to me. That's great to have unit test as reminder... :)

**Comment by nik9000** [comment]
@dadoonet I removed the deprecated settings in this PR. Do you see any others that I should make one of those tests for? I can do that as part of this PR so I don't feel bad about suppressing the warnings.

**Comment by dadoonet** [comment]
@nik9000 I guess that you can remove in master:

* `AzureStorageService#ACCOUNT_DEPRECATED` 
* `AzureStorageService#KEY_DEPRECATED` 

As they have been deprecated in 2.2.0 with #13779

**Comment by nik9000** [comment]
@dadoonet done!

**Comment by dadoonet** [comment]
LGTM

**Pull request merged**
