### PR TITLE
Refine Checkstyle for method Javadoc

### PR DESCRIPTION
**Pull request by pugnascotia**
The contribution guide's Javadoc section suggests writing Javadoc on
test methods. However the extra Checktyle rules for IDEs flag up missing
test method Javadoc at "warning", which is too severe. Since the
Checktyle rule is not very configurable, fork it and add more
configuration parameters, then add more targetted rules so that test
method Javadoc violations are only reported at "info" level.

### CODE REVIEW

**Comment by mark-vieira** [comment]
What's the level of visibility on "info" messages? I guess my point being, if adding javadocs to test methods is already very loosely enforced, is there all that much benefit to adding this lenient check vs the cost of forking another checkstyle rule implementation?

**Comment by pugnascotia** [comment]
Well right now, Javadoc on methods (and classes, etc) isn't enforced at all. Obviously enforcing that would require a massive effort across the codebase. So instead, we add warnings instead for the IDE version of the checkstyle config, thereby giving developers a nudge, without failing the build.

Some developers aren't too thrilled about it, and find it distracting. These changes are intended to keep the warnings in non-test code, while dropping the severity in test code so that it's still present in the IDE, but less obtrusive.

I've been trying to find a way to make it possible to disable adding in the extra Javadoc rules in `build-tools-internal/src/main/groovy/elasticsearch.ide.gradle` without success - if you thought this idea had more merit, then I'd appreciate any tips.

I should reiterate that our `CONTRIBUTING.md` guidance says that Javadoc should be added to public methods, and used on test methods so that we're not reliant on longAndHardToReadMethodNamesToUnderstandTheTest.

**Comment by pugnascotia** [comment]
@elasticmachine update branch

**Comment by mark-vieira** [comment]
> I should reiterate that our CONTRIBUTING.md guidance says that Javadoc should be added to public methods, and used on test methods so that we're not reliant on longAndHardToReadMethodNamesToUnderstandTheTest.

That makes sense, I'm good with pressing forward with this change.

**Comment by pugnascotia** [comment]
Developers have reported issues in IntelliJ with this change, so I've reverted it.

**Pull request merged**
