### PR TITLE
Use the built image in docker tests

### PR DESCRIPTION
**Pull request by alpar-t**
Instead of allowing docker-compose to rebuild it.
With this change we tag the image with a test label, and use that
in the testing as this is simpler that dealing with a dynamically
generated docker-compose file.

@jasontedor is it possible these new tags will confuse the release process in any way?

### CODE REVIEW

**Comment by mark-vieira** [comment]
> @jasontedor is it possible these new tags will confuse the release process in any way?

There's no need to use the same image name as the standard distribution so we could avoid any confusion by just building the image with some other name. We could then use any arbitrary tag w/o risk of folks inadvertently using this image for other purposes.

**Comment by jasontedor** [comment]
> is it possible these new tags will confuse the release process in any way?

No, it shouldn't, as we explicitly look for images tagged with the version being built in the release-manager builds. Additional tags landing in the registry would be ignored.

**Comment by atorok** [comment]
@elasticmachine run elasticsearch-ci/default-distro  and run elasticsearch-ci/bwc

**Comment by atorok** [comment]
@mark-vieira @rjernst ready for review

**Review by mark-vieira — APPROVED** [review]
👍

**Review by rjernst — APPROVED** [review]

**Pull request merged**
