### PR TITLE
[IndexShard] Use ReentrantLocks instead of mutexes

### PR DESCRIPTION
**Pull request by arteam**
Mutexes are already explicit, but are defined as plain `Object` locks. We can use explicit `ReentrantLock`s which are more natural and flexible for this use case.

### CODE REVIEW

**Comment by arteam** [comment]
@elasticmachine update branch

**Comment by arteam** [comment]
I was exploring the `IndexShard` internals and created this PR mostly for getting more familairized with the codebase/contribution process/running tests/etc. Feel free to close it if you feel that it's superficial!

**Comment by arteam** [comment]
@elasticmachine test bwc

**Comment by arteam** [comment]
@elasticmachine update branch

**Comment by arteam** [comment]
@elasticmachine update branch

**Comment by arteam** [comment]
@elasticmachine update branch

**Review by original-brownbear — COMMENTED** [review]
I don't think I'm a big fan of this change. It seems to only make the code more complex so long as we don't make any use of the flexibility of reentrant locks and in 2021 there isn't really any performance advantage to using reentrant locks any more either.
Looking into this I'm almost wondering if we shouldn't turn the remaining uses of the releasable lock that just wrap a standard reentrant lock into synchronized blocks instead to simplify the code.

Other may have a different opinion here though and this discussion may be better suited to Slack or so?

**Pull request closed without merging**
