### PR TITLE
[ML] Marginal gains in slow multi node tests

### PR DESCRIPTION
**Pull request by davidkyle**
Working on the principle that the QA multi node tests should be a place for large tests where ml jobs are run on actual data I removed CloseJobsIT and ReopenJobResetsFinishedTimeIT as both can be trivially tested in the yml rest tests. 

ForecastIT was posting data in a tight loop, it turns out post data is an expensive call and it was made 101 * 15 times. A quick calculation showed that approx 6.5MB of data was being generated which is easily accommodated in a single post data call. This was the biggest saving trimming ~ 20 seconds of the time to run ForecastIT on my machine. 

Unfortunately this does not much of a difference in the time it takes to run the entire task

For #37339

### CODE REVIEW

**Review by dimitris-athanasiou — APPROVED** [review]
LGTM

**Comment by davidkyle** [comment]
run elasticsearch-ci/1

**Review by hendrikmuhs — APPROVED** [review]
LGTM

**Comment by davidkyle** [comment]
run elasticsearch-ci/2

**Pull request merged**
