### PR TITLE
Remove `getTestName()` from the index name

### PR DESCRIPTION
**Pull request by csoulios**
This PR removes the test name from the source index name and replaces it with a 14 char long random alphanumeric.

In the past, we had chosen to include the test name in the index name so that there are no naming conflicts between indexes of different tests. However, some times test names include invalid characters that make index creation fail. 

For example when we run the following test: 

```sh
./gradlew ':x-pack:plugin:rollup:test' \
    --tests "org.elasticsearch.xpack.rollup.v2.RollupActionSingleNodeTests" \
    -Dtests.iters=10
```

We get the following failures:
```
org.elasticsearch.xpack.rollup.v2.RollupActionSingleNodeTests > testCannotRollupToExistingIndex {seed=[9814B01249EAC77D:A37B1C4ACB1DD2F0]} FAILED
    [testcannotrolluptoexistingindex {seed=[9814b01249eac77d:a37b1c4acb1dd2f0]}-lypa] org.elasticsearch.indices.InvalidIndexNameException: Invalid index name [testcannotrolluptoexistingindex {seed=[9814b01249eac77d:a37b1c4acb1dd2f0]}-lypa], must not contain the following characters ['\','/','*','?','"','<','>','|',' ',',']
        at __randomizedtesting.SeedInfo.seed([9814B01249EAC77D:A37B1C4ACB1DD2F0]:0)
        at app//org.elasticsearch.cluster.metadata.MetadataCreateIndexService.validateIndexOrAliasName(MetadataCreateIndexService.java:219)
        at app//org.elasticsearch.cluster.metadata.MetadataCreateIndexService.validateIndexName(MetadataCreateIndexService.java:165)
        at app//org.elasticsearch.cluster.metadata.MetadataCreateIndexService.validate(MetadataCreateIndexService.java:1316)
        at app//org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequest(MetadataCreateIndexService.java:338)
        at app//org.elasticsearch.cluster.metadata.MetadataCreateIndexService.applyCreateIndexRequest(MetadataCreateIndexService.java:407)
        at app//org.elasticsearch.cluster.metadata.MetadataCreateIndexService$1.execute(MetadataCreateIndexService.java:294)
        at app//org.elasticsearch.cluster.service.MasterService$UnbatchedExecutor.execute(MasterService.java:515)
        at app//org.elasticsearch.cluster.service.MasterService.innerExecuteTasks(MasterService.java:959)
        at app//org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:929)
        at app//org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:261)
        at app//org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:165)
        at app//org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:110)
        at app//org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:148)
        at app//org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:808)
        at app//org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:257)
        at app//org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:223)
        at java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base@17.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base@17.0.1/java.lang.Thread.run(Thread.java:833)

REPRODUCE WITH: ./gradlew ':x-pack:plugin:rollup:test' --tests "org.elasticsearch.xpack.rollup.v2.RollupActionSingleNodeTests.testCannotRollupToExistingIndex {seed=[9814B01249EAC77D:563AF41119A1F028]}" -Dtests.seed=9814B01249EAC77D -Dtests.locale=en-SG -Dtests.timezone=Africa/Windhoek -Druntime.java=17
```

### CODE REVIEW

**Review by iverase — APPROVED** [review]
LGTM

**Comment by nik9000** [comment]
Lol getTestName can have the seed in it?

I'm a little sad that this'd make it possible for collisions. It'd be super rare, but sad. I'd probably have sliced out everything after the first space. But It's all good.

**Review by nik9000 — APPROVED** [review]

**Comment by csoulios** [comment]
> Lol getTestName can have the seed in it?
> 
> I'm a little sad that this'd make it possible for collisions. It'd be super rare, but sad. I'd probably have sliced out everything after the first space. But It's all good.

I thought about manipulating the output of `getTestName()` too, but I was not sure what other surprises may appear down the road. So, I followed what seems to be the standard for index names (long random alphanumerics).

**Review by nik9000 — APPROVED** [review]
Makes sense to em.

**Comment by csoulios** [comment]
@elasticmachine run elasticsearch-ci/packaging-tests-unix-sample

**Comment by csoulios** [comment]
@elasticmachine update branch

**Pull request merged**
