### PR TITLE
[DOCS] Moves machine learning APIs to docs folder

### PR DESCRIPTION
**Pull request by lcawl**
Related to https://github.com/elastic/elasticsearch/issues/30665

This PR moves the rest-api/ml folder and its contents from
x-pack/docs/en to docs/reference in the elasticsearch repo

In particular, it moves the API source files that have code snippet testing enabled.  The rest of the files can be moved as their examples are fixed.

It also adds info about the minimum required subscription level for testing purposes.

### CODE REVIEW

**Comment by nik9000** [comment]
I think this one will have to wait on my changes to the distribution for testing the docs repo. But it looks about right to me otherwise. Granted I only skimmed it and I figure the docs build is better at reviewing this kind of change than I am.

**Comment by lcawl** [comment]
Thanks @nik9000 I'll work on enabling code snippet testing in the remaining ML API pages while I wait.

**Comment by nik9000** [comment]
That'd be great!

**Comment by lcawl** [comment]
The latest refresh disables code snippet testing in the ML API pages until it can be made to work for gold- and platinum-level features.

**Comment by lcawl** [comment]
retest this please

**Pull request merged**
