### PR TITLE
Fix TimeSeriesRateAggregatorTests file leak

### LINKED ISSUE #115238: [CI] TimeSeriesRateAggregatorTests fails with file handle leak
### CI Link

https://gradle-enterprise.elastic.co/s/4r6lsclc3lrou/tests/overview?outcome=FAILED

### Repro line

./gradlew ":x-pack:plugin:analytics:test" --tests "org.elasticsearch.xpack.analytics.rate.TimeSeriesRateAggregatorTests" -Dtests.seed=509E2AFA17E6D235 -Dtests.locale=en -Dtests.timezone=Etc/UTC -Druntime.java=22	

### Does it reproduce?

Yes

### Applicable branches

main

### Failure history

_No response_

### Failure excerpt

First seen on Lucene Snapshot brand now merged into "main", reproduced for this particular seed:

```
1> [2024-10-21T14:15:12,018][INFO ][o.e.x.a.r.TimeSeriesRateAggregatorTests] [testNestedWithinAutoDateHistogram] after test
  2> java.lang.RuntimeException: file handle leaks: [FileChannel(/Users/christoph/workspace/elasticsearch/x-pack/plugin/analytics/build/testrun/test/temp/org.elasticsearch.xpack.analytics.rate.TimeSeriesRateAggregatorTests_509E2AFA17E6D235-001/index-MMapDirectory-001/write.lock)]
        at __randomizedtesting.SeedInfo.seed([509E2AFA17E6D235]:0)
        at org.apache.lucene.tests.mockfile.LeakFS.onClose(LeakFS.java:63)
        at org.apache.lucene.tests.mockfile.FilterFileSystem.close(FilterFileSystem.java:69)
        at org.apache.lucene.tests.mockfile.FilterFileSystem.close(FilterFileSystem.java:70)
        at org.apache.lucene.tests.mockfile.FilterFileSystem.close(FilterFileSystem.java:70)
        at org.apache.lucene.tests.util.TestRuleTemporaryFilesCleanup.afterAlways(TestRuleTemporaryFilesCleanup.java:223)
        at com.carrotsearch.randomizedtesting.rules.TestRuleAdapter$1.afterAlways(TestRuleAdapter.java:31)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:43)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
        at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
        at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
        at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
        at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
        at java.base/java.lang.Thread.run(Thread.java:1570)

        Caused by:
        java.lang.Exception
            at org.apache.lucene.tests.mockfile.LeakFS.onOpen(LeakFS.java:46)
            at org.apache.lucene.tests.mockfile.HandleTrackingFS.callOpenHook(HandleTrackingFS.java:82)
            at org.apache.lucene.tests.mockfile.HandleTrackingFS.newFileChannel(HandleTrackingFS.java:202)
            at org.apache.lucene.tests.mockfile.HandleTrackingFS.newFileChannel(HandleTrackingFS.java:171)
            at org.apache.lucene.tests.mockfile.FilterFileSystemProvider.newFileChannel(FilterFileSystemProvider.java:206)
            at java.base/java.nio.channels.FileChannel.open(FileChannel.java:309)
            at java.base/java.nio.channels.FileChannel.open(FileChannel.java:369)
            at org.apache.lucene.store.NativeFSLockFactory.obtainFSLock(NativeFSLockFactory.java:112)
            at org.apache.lucene.store.FSLockFactory.obtainLock(FSLockFactory.java:43)
            at org.apache.lucene.store.BaseDirectory.obtainLock(BaseDirectory.java:44)
            at org.apache.lucene.store.FilterDirectory.obtainLock(FilterDirectory.java:106)
            at org.apache.lucene.tests.store.MockDirectoryWrapper.obtainLock(MockDirectoryWrapper.java:1105)
            at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:955)
            at org.apache.lucene.tests.index.RandomIndexWriter$2.<init>(RandomIndexWriter.java:109)
            at org.apache.lucene.tests.index.RandomIndexWriter.mockIndexWriter(RandomIndexWriter.java:108)
            at org.apache.lucene.tests.index.RandomIndexWriter.mockIndexWriter(RandomIndexWriter.java:78)
            at org.apache.lucene.tests.index.RandomIndexWriter.<init>(RandomIndexWriter.java:162)
            at org.apache.lucene.tests.index.RandomIndexWriter.<init>(RandomIndexWriter.java:141)
            at org.elasticsearch.search.aggregations.AggregatorTestCase.testCase(AggregatorTestCase.java:754)
            at org.elasticsearch.xpack.analytics.rate.TimeSeriesRateAggregatorTests.lambda$testNestedWithinAutoDateHistogram$6(TimeSeriesRateAggregatorTests.java:158)
            at org.apache.lucene.tests.util.LuceneTestCase._expectThrows(LuceneTestCase.java:3044)
            at org.apache.lucene.tests.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2884)
            at org.apache.lucene.tests.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2875)
            at org.elasticsearch.xpack.analytics.rate.TimeSeriesRateAggregatorTests.testNestedWithinAutoDateHistogram(TimeSeriesRateAggregatorTests.java:158)
```

### PR DESCRIPTION
**Pull request by cbuescher**
With Lucene 10, [IndexWriter requires a parent document field](https://github.com/apache/lucene/pull/12829) in order to use index sorting with document blocks. In production code, we already use "setParentField" when creating an index writer configuration in [InternalEngine](https://github.com/elastic/elasticsearch/blob/a8de5545d82120ce316d12e4372e145f1d5a2fa4/server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java#L2745), but some aggregation tests with nested docs still seem to use index writers without the parent field set. The IAE exception we get here now that Lucene 10 is merged hides another IAE that was tested for in `TimeSeriesRateAggregatorTests#testNestedWithinAutoDateHistogram` and on top of that occasionally leads to test failures due to file leaks as observed in https://github.com/elastic/elasticsearch/issues/115238.

Closes #115238

### CODE REVIEW

**Comment by cbuescher** [comment]
@kkrik-es you seem to be familiar with the Lucene changes in this area, is my reasoning above correct?
The IAE we get without this change now satisfies expected exception class in the test in question but since its thrown earlier can lead to the IndexWriter not being closed properly, which occasionally gets detected by the test infra as a file leak.

**Comment by cbuescher** [comment]
@kkrik-es I saw you fixed the Leak issue with the change in https://github.com/elastic/elasticsearch/pull/115345, however I believe that we are now throwing a different IAE than before the merge of Lucene 10 (in a different location), so I think this change here still applies. When the parent field is set we don't need to add documents separately and get back the "old" IAE  from before the Lucene 10 update. Would you mind taking a look and let me know if my thinking here is right?

**Comment by kkrik-es** [comment]
I am really not familiar with these changes, just noticed that @iverase applied them elsewhere.. 

If Ignacio is fine with it and the following test passes, I've no objection:

```
./gradlew ":x-pack:plugin:analytics:test" --tests "org.elasticsearch.xpack.analytics.rate.TimeSeriesRateAggregatorTests" -Dtests.seed=509E2AFA17E6D235 -Dtests.locale=en -Dtests.timezone=Etc/UTC -Druntime.java=22
```

**Comment by cbuescher** [comment]
> ./gradlew ":x-pack:plugin:analytics:test" --tests "org.elasticsearch.xpack.analytics.rate.TimeSeriesRateAggregatorTests" -Dtests.seed=509E2AFA17E6D235 -Dtests.locale=en -Dtests.timezone=Etc/UTC -Druntime.java=22

That passes. I asked you because [this change in InternalEngine](https://github.com/elastic/elasticsearch/blame/a8de5545d82120ce316d12e4372e145f1d5a2fa4/server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java#L2745) that also sets the parent field was made by you. I think the change in the IAE that is being thrown went unnoticed because we don't check it message so far (which I added here)

**Comment by kkrik-es** [comment]
> I asked you because [this change in InternalEngine](https://github.com/elastic/elasticsearch/blame/a8de5545d82120ce316d12e4372e145f1d5a2fa4/server/src/main/java/org/elasticsearch/index/engine/InternalEngine.java#L2745) that also sets the parent field was made by you. I think the change in the IAE that is being thrown went unnoticed because we don't check it message so far (which I added here)

I see, so we were missing setting the parent doc so there was a mismatch in Lucene land that led to errors? At any rate, I've no objection here.

**Review by kkrik-es — APPROVED** [review]

**Comment by cbuescher** [comment]
@elasticmachine elasticsearch-ci/part-2

**Pull request merged**
