### PR TITLE
[DOCS] Deprecate `geo_bounding_box` query's `type`  param (#74009)

### PR DESCRIPTION
**Pull request by jrodewig**
The `geo_bounding_box` query's `type` parameter is currently ignored and has no
effect on the query. This documents the deprecation of the parameter in 7.14.0.
The parameter will be removed in 8.0.0.

Relates to #70561. Backport of #74008.

### Preview
* 7.14 migration guide: https://elasticsearch_74009.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/7.x/migrating-7.14.html#breaking_714_search_deprecations
* Geo-bounding box query: https://elasticsearch_74009.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/7.x/query-dsl-geo-bounding-box-query.html#_query_options

### CODE REVIEW

**Comment by iverase** [comment]
Parameter type has been deprecated in Elasticsearch. I think we can update the docs now.

**Comment by jrodewig** [comment]
Thanks @iverase. This is ready for a review at your convenience.

**Review by iverase — APPROVED** [review]
LGTM

**Comment by jrodewig** [comment]
Thanks @iverase.

**Pull request merged**
