### PR TITLE
Add support for FreeBSD

### PR DESCRIPTION
**Pull request by amishHammer**
Add support for reading configuration variables from FreeBSD's
/etc/rc.conf and related service specific configuration files.

### CODE REVIEW

**Comment by nik9000** [comment]
@amishHammer is the maintainer of the freebsd port, of Elasticsearch ([here](https://www.freshports.org/textproc/elasticsearch) and [here](https://www.freshports.org/textproc/elasticsearch2)). Freebsd ports use the untar from upstream, patch, repackage mechansim. We talked at Elastic{on} Chicago and whittled down what he had to patch in to this adapter layer between rc.conf and Elasticsearch. This is how the Elasticsearch 2 port that he published last night works.

**Comment by rmuir** [comment]
how will it work with plugins? AFAIK, unfortunately `bin/plugin` does not look at elasticsearch.in.sh

**Comment by nik9000** [comment]
> how will it work with plugins? AFAIK, unfortunately bin/plugin does not look at elasticsearch.in.sh

Yeah - I was just checking on that. I'm now kind of wondering why we don't do at the `/etc/sysconfig` sorcery in `elasticsearch.in.sh` and always source it. I suspect he's got something else for `bin/plugin`.

Otherwise, the nice thing about this change is that many of the scripts that we do ship already source `elasticsearch.in.sh` - the shield scripts do for example.

**Comment by amishHammer** [comment]
Ok bin/plugin does seem to need a little work plugins seem to get some
files in the wrong place (config).  However plugins (well shield) scripts
that get installed in bin/shield look at elasticsearch.in.sh so get the
correct configuration.

**Comment by rmuir** [comment]
OK, if most scripts are already sourcing this file, I think we should just make a separate issue to fix the rest of the scripts to do it too? It seems like it can only bring better consistency.

**Comment by clintongormley** [comment]
Hi @amishHammer 

Sorry this appears to have fallen between the cracks.  We'll pick it up again soon.  In the meantime, could I ask you to sign the CLA? http://www.elasticsearch.org/contributor-agreement/

**Comment by dakrone** [comment]
Hi @amishHammer, is there still interest in supporting this PR?

**Comment by amishHammer** [comment]
Yes sorry for the delay had to do some internal button clicking to register the contribution due to the CLA

**Comment by jasontedor** [comment]
Since we do not officially support FreeBSD, I would prefer that we not integrate this PR. But I wonder if this can be solved by just using `ES_INCLUDE` to source an alternate file from `elasticsearch.in.sh` that includes these changes and just source `elasticsearch.in.sh` from that other file? Note that on master `elasticsearch.in.sh` [does not really do anything other than set the classpath in master](https://github.com/elastic/elasticsearch/blob/f600c4ab9c4a575a269287bb5aaa22d828c56496/distribution/src/main/resources/bin/elasticsearch.in.sh).

**Comment by clintongormley** [comment]
> Since we do not officially support FreeBSD, I would prefer that we not integrate this PR.

Closing

**Pull request closed without merging**
