### PR TITLE
Test: remove hardcoded list of unconfigured ciphers

### PR DESCRIPTION
**Pull request by jaymode**
This commit removes the hardcoded list of unconfigured ciphers in the
SslIntegrationTests. This list may include ciphers that are not
supported on certain JVMs. This list is replaced with code that
dynamically computes the set of ciphers that are not configured for
use by default.

### CODE REVIEW

**Comment by hub-cap** [comment]
This fixed my issue locally. <3 @jaymode

**Review by hub-cap — APPROVED** [review]
:shipit:

**Comment by jaymode** [comment]
run gradle build tests

**Comment by jaymode** [comment]
@jasontedor thank you for merging master to get a green build for me ❤️

**Comment by jasontedor** [comment]
@jaymode You're welcome. ❤️

**Pull request merged**
