### PR TITLE
Increase snapshot pool max size to 10

### LINKED ISSUE #89608: Increase SNAPSHOT threadpool size to that of the snapshot_meta pool?
We currently have two separate thread-pools for interaction with the snapshot repo, the snapshot pool and the snapshot_meta pool.
The snapshot pool is sized much smaller than the snapshot meta pool at half the processors, max-5 vs. the snapshot_meta pool which is sized at 3 x processors, max-50.
The reasoning behind sizing the meta_pool the way we did was that most of the time on it would be spent blocked on repository IO anyway and thus using more threads than CPUs is reasonable.
Profiling snapshotting via the many-shards benchmarks paints a similar picture for the snapshot write side. Most of the time is spent waiting on IO on the snapshot pool for both master and data nodes. Serialization etc. user time CPU cost is hardly 5% of the overall time on data nodes and at the most 10% on master nodes.
-> it seems reasonable to increase the size of the snapshot (write) pool to that of the snapshot_meta (read) pool since the reasoning about relative IO vs. compute time should be about the same for both?

Practically speaking, increasing the pool size is a massive throughput improvement in the many shards snapshot-taking benchmarks since they are mostly bound by repository IO latency at the moment.

### PR DESCRIPTION
**Pull request by original-brownbear**
As discussed, we can be up to twice as fast without increasing CPU use much on high latency blob stores so increasing the pool size to 10 here to better utilise larger data nodes.

closes #89608

### CODE REVIEW

**Review by henningandersen — APPROVED** [review]
LGTM.

**Comment by henningandersen** [comment]
Can we change label to enhancement?

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/part-1  (apm docker thingy ...)

**Comment by original-brownbear** [comment]
Thanks Henning!

**Pull request merged**
