### PR TITLE
Query evaluation: Add Discounted Cumulative Gain ranking metric

### PR DESCRIPTION
**Pull request by cbuescher**
Similar to #19300, this adds another query ranking  evaluation metric to the `rank_eval` feature branch. Computation follows the alternative (2nd) formulation of DCG in https://en.wikipedia.org/wiki/Discounted_cumulative_gain. Documents not rated by the user are assumed to have a rating of 0. I didn't add normalization (nDCG) so far but this should be easily extendable, maybe with an added `normalize` option.

Relates to #19195

### CODE REVIEW

**Comment by cbuescher** [comment]
@MaineC and another metric, can you take a look when you are back?

**Comment by cbuescher** [comment]
@MaineC I added a "normalize" option which should now calculate the Normalized DCG. I also added an option for providing a rating for "unknown" documents, but I'm not sure how useful this is. Also there are some edge cases that need some more attention (e.g. what if there's more rated docs than returned docs in search (because of e.g. size limit), how should this affect the metric), but I think this is good for a first review.

**Comment by MaineC** [comment]
Checked the changes, LGTM

**Comment by MaineC** [comment]
As discussed on Slack: LGTM, trusting your rebasing skills. The test you adjusted looks pretty much like the test that occasionally failed for me when running the tests for #19648 - so looking forward to getting the fix.

**Pull request merged**
