### PR TITLE
Fix DesiredNodesUpgradeIT upgrade from 8.2

### LINKED ISSUE #89877: [CI] DesiredNodesUpgradeIT » testUpgradeDesiredNodes
### CI Link

https://gradle-enterprise.elastic.co/s/ff35boj3dy3qo/tests/:qa:rolling-upgrade:v8.2.0%23oneThirdUpgradedTest/org.elasticsearch.upgrades.DesiredNodesUpgradeIT/testUpgradeDesiredNodes

### Repro line

`./gradlew ':qa:rolling-upgrade:v8.2.0#oneThirdUpgradedTest' -Dtests.class="org.elasticsearch.upgrades.DesiredNodesUpgradeIT" -Dtests.method="testUpgradeDesiredNodes" -Dtests.seed=E0D4B6781946820C -Dtests.bwc=true -Dtests.locale=it-IT -Dtests.timezone=America/Sao_Paulo -Druntime.java=17`

### Does it reproduce?

Yes

### Applicable branches

main

### Failure history

https://gradle-enterprise.elastic.co/scans/tests?search.timeZoneId=Europe/Berlin&tests.container=org.elasticsearch.upgrades.DesiredNodesUpgradeIT&tests.test=testUpgradeDesiredNodes#

### Failure excerpt

```
junit.framework.AssertionFailedError: Expected exception ResponseException but no exception was thrown	
	at __randomizedtesting.SeedInfo.seed([E0D4B6781946820C:9680725C48C340A9]:0)	
	at org.apache.lucene.tests.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2854)	
	at org.apache.lucene.tests.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2840)	
	at org.elasticsearch.upgrades.DesiredNodesUpgradeIT.assertDesiredNodesWithFloatProcessorsAreRejectedInOlderVersions(DesiredNodesUpgradeIT.java:117)	
	at org.elasticsearch.upgrades.DesiredNodesUpgradeIT.testUpgradeDesiredNodes(DesiredNodesUpgradeIT.java:51)
```

### LINKED ISSUE #90004: [CI] DesiredNodesUpgradeIT testUpgradeDesiredNodes failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/ut6mplayk6lf2/tests/:qa:rolling-upgrade:v8.1.0%23oneThirdUpgradedTest/org.elasticsearch.upgrades.DesiredNodesUpgradeIT/testUpgradeDesiredNodes

And a number of other failures from the BWC builds
https://gradle-enterprise.elastic.co/s/4khmaxwf7yjsg (v8.1.1)
https://gradle-enterprise.elastic.co/s/k5ayyrfweyphm (v8.2.3)
https://gradle-enterprise.elastic.co/s/54k2gbug2jpmk (v8.2.2)

**Reproduction line:**
`./gradlew ':qa:rolling-upgrade:v8.1.0#oneThirdUpgradedTest' -Dtests.class="org.elasticsearch.upgrades.DesiredNodesUpgradeIT" -Dtests.method="testUpgradeDesiredNodes" -Dtests.seed=33809BF03E709502 -Dtests.bwc=true -Dtests.locale=es-AR -Dtests.timezone=America/Port_of_Spain -Druntime.java=17`

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.upgrades.DesiredNodesUpgradeIT&tests.test=testUpgradeDesiredNodes

**Failure excerpt:**
```
junit.framework.AssertionFailedError: Expected exception ResponseException but no exception was thrown

  at __randomizedtesting.SeedInfo.seed([33809BF03E709502:45D45FD46FF557A7]:0)
  at org.apache.lucene.tests.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2854)
  at org.apache.lucene.tests.util.LuceneTestCase.expectThrows(LuceneTestCase.java:2840)
  at org.elasticsearch.upgrades.DesiredNodesUpgradeIT.assertDesiredNodesWithFloatProcessorsAreRejectedInOlderVersions(DesiredNodesUpgradeIT.java:117)
  at org.elasticsearch.upgrades.DesiredNodesUpgradeIT.testUpgradeDesiredNodes(DesiredNodesUpgradeIT.java:51)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:833)

```

### PR DESCRIPTION
**Pull request by fcofdez**
Doubles get casted to int during parsing in 8.2. Use 0.5f as we used before.

Closes #89877
Closes https://github.com/elastic/elasticsearch/issues/90004

### CODE REVIEW

**Comment by fcofdez** [comment]
@elasticmachine run elasticsearch-ci/part-1

**Comment by fcofdez** [comment]
@elasticmachine update branch

**Review by arteam — APPROVED** [review]
LGTM! Thanks Francisco!

**Comment by fcofdez** [comment]
Thanks Artem!

**Pull request merged**
