### PR TITLE
Replace bespoke parser for significance heuristics

### LINKED ISSUE #25519: Construct the significant terms aggregation builder's parser statically
Right now we build a new ObjectParser every time we want get a significant terms aggregation. We do this because we had to pass in `ParseFieldRegistry<SignificanceHeuristicParser>`. I think we can avoid this by moving `ParseFieldRegistry<SignificanceHeuristicParser>` to `NamedXContentRegistry` style parsing.

### PR DESCRIPTION
**Pull request by nik9000**
This replaces the hand written xcontent parsers for significance
heristics with `ObjectParser` and parsing named xcontent.

As a happy accident, this was the last user of `ParseFieldRegistry` so
this PR entirely removes that class.

Closes #25519

### CODE REVIEW

**Comment by nik9000** [comment]
`+160 −404` Yay!

**Comment by nik9000** [comment]
I've added `breaking-java` because his requires plugins that provide significance heuristics to declare them in a different way. It doesn't change how they implement that heuristic though, so it should be a pretty light lift. Changes like this have traditionally been ok in minor releases.

**Comment by polyfractal** [comment]
@markharwood mind having a look at this?  I gave it a skim and it LGTM, but not super familiar with the guts of Sig* aggs myself

**Review by markharwood — COMMENTED** [review]
LGTM, thanks Nik

**Comment by nik9000** [comment]
Thanks @markharwood and @polyfractal!

**Pull request merged**
