### PR TITLE
Set tarLongFileMode to posix in maven-assembly-plugin config

### LINKED ISSUE #11824: Build fails with maven-assembly-plugin version 2.5.5
Running the command `mvn install -pl core -DskipTests` on the master branch results in a failure:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 39.880s
[INFO] Finished at: Tue Jun 23 19:50:18 JST 2015
[INFO] Final Memory: 52M/1462M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.5.5:single (default) on project elasticsearch: Execution default of goal org.apache.maven.plugins:maven-assembly-plugin:2.5.5:single failed: group id '2060452353' is too big ( > 2097151 ). Use STAR or POSIX extensions to overcome this limit -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

If I remove the `version` of the maven-assembly-plugin in `pom.xml` like this:

```
$ git diff
diff --git a/pom.xml b/pom.xml
index 6083089..8df98e2 100644
--- a/pom.xml
+++ b/pom.xml
@@ -482,7 +482,6 @@
                 <plugin>
                     <groupId>org.apache.maven.plugins</groupId>
                     <artifactId>maven-assembly-plugin</artifactId>
-                    <version>2.5.5</version>
                 </plugin>
                 <plugin>
                     <groupId>org.apache.maven.plugins</groupId>
```

then it uses version 2.2-beta-5 of the plugin, and the build succeeds.

### PR DESCRIPTION
**Pull request by dpursehouse**
Fixes #11824

Change-Id: I61bdee6c96cdfa8fbf26e3d654eaa78d6a303526

### CODE REVIEW

**Comment by dadoonet** [comment]
w00t! Thank you !

Wondering if we should set that in parent pom instead ?

https://github.com/elastic/elasticsearch/blob/master/pom.xml#L482

**Comment by dpursehouse** [comment]
I put it in the core's pom because that's where the existing configuration is, and the core build was the only one failing due to this anyway.

**Comment by dpursehouse** [comment]
@dadoonet do you want me to move it to the parent pom, or is it OK to merge like this?

**Comment by dadoonet** [comment]
I don't have a strong opinion here. I was just thinking that it might happen also on other modules at some point.

I'd also like to understand if it's a temporary fix (do we expect a new version of the assembly plugin?) so it worths a comment in the pom like "remove when version X will be released"...

I'll look at this hopefully soonish. And probably merge it as is...

**Comment by dpursehouse** [comment]
Any progress on this?

**Comment by dadoonet** [comment]
@dpursehouse I was looking at it this morning and get through the maven issue https://issues.apache.org/jira/browse/MASSEMBLY-479 and came to http://www.delorie.com/gnu/docs/tar/tar_114.html

> So, a future tar will have a --posix flag forcing the usage of truly POSIX headers, and so, producing archives previous GNU tar will not be able to read. So, once pretest will announce that feature, it would be particularly useful that users test how exchangeable will be archives between GNU tar with --posix and other POSIX tar.

If I understand this correctly, it means that when filenames will have more than 100 characters, they just won't be readable by older `tar` versions. Is that how you read this as well?

So there is no real consequence of having that option set for artifacts we produce but those might not be readable on older systems?

I wonder if you have this issue because you are running `mvn` in a subdir like `/home/thisisaverylongdirname/thisiswhereiputgitrepos/andiwanttoputelasticsearchhere/elasticsearch`? :)

Where do you run maven from?

**Comment by dpursehouse** [comment]
> If I understand this correctly, it means that when filenames will have more than 100 characters, they just won't be readable by older tar versions. Is that how you read this as well?

Yes, that's how it seems to me.

> Where do you run maven from?

`/home/corporate/username/git/elasticsearch`

**Comment by dadoonet** [comment]
I think this should be a common option to all modules. Could you update your PR and move this setting to the parent pom?

@rmuir WDYT of this? Any side effect I can't see? I wonder why it's not set by default in maven assembly plugin... Probably because they prefer to have compatibility out of the box for older tar versions???

**Comment by dpursehouse** [comment]
@dadoonet I've rebased it on the latest head of master, and moved the setting into the parent pom as requested.

**Comment by dpursehouse** [comment]
@dadoonet any chance of getting this merged?

**Comment by rmuir** [comment]
> @rmuir WDYT of this? Any side effect I can't see? I wonder why it's not set by default in maven assembly plugin... Probably because they prefer to have compatibility out of the box for older tar versions???

sorry i havent had time to dig into this. Why is it really needed? Why isn't it the default.

All tests pass for me without it.

**Comment by dpursehouse** [comment]
@rmuir 

> Why is it really needed?

I need it because otherwise the mvn build fails for me.  There may be some underlying root cause, but I haven't been able to find it.

**Comment by dpursehouse** [comment]
Ping.  I'm still unable to build without this patch.

> All tests pass for me without it.

The test pass for me too (without the patch).  It's `mvn package` that fails on the `maven-assembly-plugin` part of the core build.

**Comment by dpursehouse** [comment]
This is no longer a blocker for me.  Since 2.0.0-beta1 was released I can get it off Maven Central instead of building it myself.

It doesn't look like it's going to get merged, so I will just close this PR.

**Comment by dpursehouse** [comment]
FWIW I was able to build on my Macbook Pro without this fix.

**Pull request closed without merging**
