### PR TITLE
Authentication.token now uses version from the existing authentication

### LINKED ISSUE #85902: TokenServiceTests.testInvalidateRefreshTokenThatIsAlreadyInvalidated fails with ClassCastException
### CI Link

https://gradle-enterprise.elastic.co/s/72jn3jmotbelc/console-log?task=:x-pack:plugin:security:test

### Repro line

./gradlew ':x-pack:plugin:security:test' --tests "org.elasticsearch.xpack.security.authc.TokenServiceTests.testInvalidateRefreshTokenThatIsAlreadyInvalidated" -Dtests.seed=4C8C62EC8BC30D4A -Dtests.locale=sr-Latn -Dtests.timezone=America/Fortaleza -Druntime.java=17

### Does it reproduce?

Yes

### Applicable branches

master

### Failure history

_No response_

### Failure excerpt

```
org.elasticsearch.xpack.security.authc.TokenServiceTests > testInvalidateRefreshTokenThatIsAlreadyInvalidated FAILED
  java.lang.ClassCastException: class java.util.HashMap cannot be cast to class org.elasticsearch.common.bytes.BytesReference (java.util.HashMap is in module java.base of loader 'bootstrap'; org.elasticsearch.common.bytes.BytesReference is in unnamed module of loader 'app') |  
  | at __randomizedtesting.SeedInfo.seed([4C8C62EC8BC30D4A:CD4EFA933E0F14A5]:0) |  
  | at org.elasticsearch.xpack.core.security.authc.Authentication.maybeRewriteMetadataForApiKeyRoleDescriptors(Authentication.java:706) |  
  | at org.elasticsearch.xpack.core.security.authc.Authentication.maybeRewriteForOlderVersion(Authentication.java:165) |  
  | at org.elasticsearch.xpack.security.authc.TokenService.createOAuth2Tokens(TokenService.java:372) |  
  | at org.elasticsearch.xpack.security.authc.TokenService.createOAuth2Tokens(TokenService.java:319) |  
  | at org.elasticsearch.xpack.security.authc.TokenServiceTests.testInvalidateRefreshTokenThatIsAlreadyInvalidated(TokenServiceTests.java:605)
```

### PR DESCRIPTION
**Pull request by ywangd**
The token method creates a new authentication based on the existing one.
It changes only the authentication type. Hence it should use the version
of the existing authentication as well instead of CURRENT.

Resolves: #85902

### CODE REVIEW

**Comment by ywangd** [comment]
NOTE: this is technically a bug but should not happen in production because we always create a token authentication from an update-to-date (i.e. Version.CURRENT) authentication. It only manifests itself in tests because the new test helper for randomizing authentication provides more variants.

**Comment by ywangd** [comment]
@elasticmachine update branch

**Comment by ywangd** [comment]
@elasticmachine update branch

**Review by albertzaharovits — APPROVED** [review]
LGTM

**Pull request merged**
