### PR TITLE
Mute testBasicFailureRetention

### PR DESCRIPTION
**Pull request by nknize**
see #47937

### CODE REVIEW

**Comment by original-brownbear** [comment]
@nknize @dakrone no need to mute this one, I'll have a fix up in a few minutes :)

**Comment by original-brownbear** [comment]
https://github.com/elastic/elasticsearch/pull/47941 should do the trick here :)

**Review by original-brownbear — APPROVED** [review]
LGTM after all, @dakrone is out today so review on my PR will take a bit. Let's make tests green here asap  :)

**Comment by nknize** [comment]
Thank you @original-brownbear

**Pull request merged**
