### PR TITLE
Change the method of search from POST to GET

### PR DESCRIPTION
**Pull request by wangzhenhui1992**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

issue #35116

### CODE REVIEW

**Review by cbuescher — COMMENTED** [review]
Hi @wangzhenhui1992,

first of all, thanks a lot for opening this pull request. Concerning the requested change, please note that both POST and GET are valid as documented in the [Request Body Search](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-body.html). The discussion whether GET or POST is "right" has been going back and forth here and in other places many times. In out own documentation we use both in different locations with respect to "_search". 

While I understand your motifs for proposing this change I'm hesitant to accept it simply because it would continue in a chain of back-and-forth changes like this that I think in this case are not necesarry. I hope you agree and will leave this PR open a bit for others to comment but would otherwise like to close this PR.

**Comment by wangzhenhui1992** [comment]
Thank you for replying.
What about the opinion and idea I write in  
[https://github.com/elastic/elasticsearch/issues/35116#issuecomment-434889347](https://github.com/elastic/elasticsearch/issues/35116#issuecomment-434889347)

**Review by cbuescher — CHANGES_REQUESTED** [review]
> What about the opinion and idea I write in

Sorry, I understand your point but I'm not convinced. We have another occasion of POST with "_search" later on the same documentation page, that would have to be changed too to make it at least consistent on one page. Second of all, the "/reference/search" page isn't even part of an "introduction" chapter specially designed for beginners, but rather a general reference page. People should be aware of the exchangability of GET/POST in the "_search" endpoint when reading this.

**Comment by colings86** [comment]
One other point to note here and another reason this documentation list the method as `POST` is that some HTTP clients do not allow GET requests with a body. By showing the example as `POST` here we can be sure that whatever HTTP client the reader is using they are able to run the request as written. I do not think we should change this,

**Comment by cbuescher** [comment]
@colings86 thanks for the additional argument.
@wangzhenhui1992 I will close this issue but thanks for raising it and feel free to open pull requests for any other change you might want to suggest for the documentation in the future.

**Pull request closed without merging**
