### PR TITLE
[7.17] Avoid NPE in DiskThresholdMonitor (#93699)

### PR DESCRIPTION
**Pull request by pxsalehi**
Backports the following commits to 7.17:

- Avoid NPE in DiskThresholdMonitor (https://github.com/elastic/elasticsearch/pull/93699)

### CODE REVIEW

**Comment by pxsalehi** [comment]
@elasticmachine update branch

**Comment by pxsalehi** [comment]
@DaveCTurner not sure why this is stuck. Could you please give it an approval?

**Comment by pxsalehi** [comment]
@elasticmachine update branch

**Review by DaveCTurner — APPROVED** [review]
LGTM as long as CI is happy :)

Not sure why it didn't auto-merge, but it wasn't because of the lack of a review.

**Pull request merged**
