### PR TITLE
Improve reliability of elections with message delays

### LINKED ISSUE #97909: Election scheduler should not reset before publication complete
Today we close the election scheduler when the coordinator leaves mode `CANDIDATE`, before even starting the publication that establishes the election winner as the cluster master. If this publication subsequently fails then we start a new election scheduler with the original, short, timeout, and do not back off. With very high numbers of master-eligible nodes this can lead to constant election clashes that never resolve. We must count such failed publications as failed election attempts for election scheduling and backoff purposes.

More precisely, I think a node in mode `LEADER` should not count an election as truly successful until we've received join votes from all nodes in the cluster (see `org.elasticsearch.cluster.coordination.CoordinationState#containsJoinVoteFor`) at the end of a fully-acked publication. That should be equivalent to `currentTerm() == maxTermSeen` at the end of a fully-acked publication, since we increase `maxTermSeen` on a missing join vote.

I'm not sure how a node in mode `FOLLOWER` should detect that the cluster is completely stable. The master could broadcast another message when it decides things are stable perhaps? Or maybe it would be good enough to base it on elapsed time (i.e. if we've been `FOLLOWER` in the same term for 60s)?

---

### Workaround

The simplest workaround is not to have so many master-eligible nodes. See [these docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/high-availability-cluster-small-clusters.html#high-availability-cluster-design-three-plus-nodes) for more information:

> However, it is good practice to limit the number of master-eligible nodes in the cluster to three. Master nodes do not scale like other node types since the cluster always elects just one of them as the master of the cluster. If there are too many master-eligible nodes then master elections may take a longer time to complete.

### PR DESCRIPTION
**Pull request by DaveCTurner**
Today we close the election scheduler when the coordinator leaves mode
`CANDIDATE`, before even starting the publication that establishes the
election winner as the cluster master. If this publication subsequently
fails then we start a new election scheduler with the original, short,
timeout, and do not back off. With very high numbers of master-eligible
nodes this can lead to constant election clashes that never resolve. We
must count such failed publications as failed election attempts for
election scheduling and backoff purposes.

This commit keeps the election scheduler open until a published state is
applied, which means we continue to back off until a publication has
completed.

Closes #97909

### CODE REVIEW

**Comment by DaveCTurner** [comment]
Note that this situation is pretty delicate to achieve, because we suppress election attempts on our peers with follower checks as soon as we become `LEADER`. That's why the test delays both publications and follower checks. It was very hard to reproduce this with 3 nodes, and even with the 7 nodes used in the test here it would eventually stabilise with a long enough timeout.

Closes ES-6502

**Review by henningandersen — APPROVED** [review]
LGTM.

A single question though for my education: could we not have closed the election scheduler as soon as we know the publication is committed rather than wait until after state has been applied? What is the benefit of waiting?

**Review by fcofdez — APPROVED** [review]
LGTM

**Comment by DaveCTurner** [comment]
> A single question though for my education: could we not have closed the election scheduler as soon as we know the publication is committed rather than wait until after state has been applied? What is the benefit of waiting?

It's a good question. This never becomes truly (i.e. 100% provably) reliable, but the general principle is that longer we wait the more reliable it becomes. We just have to be sure to reset the scheduler when the cluster is "stable", whatever that might mean. I suspect you're right that waiting for commit would be about as strong as waiting for apply.

Formally speaking, the liveness argument is based on the protocol being [eventually quiescent](https://davecturner.github.io/2017/08/17/paxos-pre-voting.html), which we achieve by extending the timeout whenever an election fails before reaching a quiescent state. We could probably come up with a more refined liveness argument if we tried (e.g. being more discriminating about which messages are or aren't part of the election process) but I don't see the need.

In fact even the implementation given here isn't quite enough to satisfy eventual quiescence, for at least a couple of reasons:

- the followers reset their schedulers once _they_ have locally applied the state, but there are still other messages in flight at this point so we have not yet reached the quiescent state.
- if we are missing a join vote from a node (i.e. it voted for a different master in the current term) then we bump the term and run another election. Note that this happens after the previous state is applied everywhere, which is kind of why I consider the apply-commit messages to be important for quiescence.

Fixing these is possible too, but adds quite some complexity, and given how tricky it is to reproduce the problem fixed here I don't believe it will be necessary in practice.

**Comment by DaveCTurner** [comment]
NB subtle change in 28b7d58e691051b469b4b8730100038a36a854da: if we have discovered a quorum and are running elections, and then we lose contact with the nodes we discovered, we have more fundamental problems than election collisions, so we should stop the election scheduler.

**Comment by henningandersen** [comment]
Thank for the explanation and the link to your excellent blog post, it all makes sense to me.

**Comment by DaveCTurner** [comment]
> NB subtle change in https://github.com/elastic/elasticsearch/commit/28b7d58e691051b469b4b8730100038a36a854da: if we have discovered a quorum and are running elections, and then we lose contact with the nodes we discovered, we have more fundamental problems than election collisions, so we should stop the election scheduler.

Bah, unfortunately this breaks things again. When we become `LEADER` we clear out the `PeerFinder`, so if the election fails and we go back to `CANDIDATE` then we start discovery from scratch again which (with this change) resets the election scheduler. Yet I think we do need something like this change to avoid keeping the election scheduler running if discovery is broken for an extended period.

I think it should be possible to restore the previous `PeerFinder` state in this situation. I'll explore that next week.

**Comment by DaveCTurner** [comment]
Oh, I forgot to remove the `auto-merge` label, I was going to ask for another final review. Nothing major has changed tho, apart from things reviewed elsewhere:

- 28b7d58e691051b469b4b8730100038a36a854da - Reset scheduler if discovery fails, as mentioned [above](https://github.com/elastic/elasticsearch/pull/98354#issuecomment-1674433579)
- #98420 - add test for previous point
- #98434 - fixes problem mentioned [above](https://github.com/elastic/elasticsearch/pull/98354#issuecomment-1675139150)
- 4b16d2c381bee59b1963f54a62ede6e0faed031b - fixes test failure found during soak testing

I'll leave it merged unless I hear any objections.

**Comment by henningandersen** [comment]
Still LGTM.

**Pull request merged**
