### PR TITLE
Update pipeline.asciidoc

### PR DESCRIPTION
**Pull request by andrewbanchich**
adds letters

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Review by colings86 — COMMENTED** [review]
I actually think the existing version is correct here, because the thing there are multiple of are `types of pipeline aggregation` each type related to a single pipeline aggregation but there are multiple types

**Comment by andrewbanchich** [comment]
@colings86 I'm not fully understanding. From what I understood, "Pipeline Aggregations" are an overarching class of aggregation, like "birds" are an overarching class of animal, for which you'd say "there are multiple types of birds."

**Comment by colings86** [comment]
@andrewbanchich I would actually say "there are multiple types of bird". I think in this case I'll defer to one of our tech writers @debadair since I could very well be incorrect although I think both ways read ok.

**Comment by DaveCTurner** [comment]
This seems to be is a difference between US and British English, but [both are acceptable](http://languagelog.ldc.upenn.edu/nll/?p=20940). The singular is more common in British English and they're about equally prevalent in US English.

**Comment by nik9000** [comment]
> This seems to be is a difference between US and British English, but both are acceptable. The singular is more common in British English and they're about equally prevalent in US English.

Yeah, if I wrote this I'd write it `aggregations`. But I didn't write this. Some silly British people did. We have a long tradition of writing documentation in our voice so I think it is right to keep the silly British way. But I'm sure not going to start writing like that. It sounds funny.

Elastic does have a style guide in google docs which would be a useful reference for this sort of thing because it kind of overrides our "your own voice" tradition in specific cases but it is silent about this particular issue.

**Pull request closed without merging**
