### PR TITLE
[DOCS] Fix a couple of docs typos

### PR DESCRIPTION
**Pull request by pionCham**
### fix  a couple of docs typos
- `nonsignificant` to `insignificant`
- ` of all of ` to `of all `

### CODE REVIEW

**Comment by pionCham** [comment]
@jonathan-buttner  Hello~ can you help me review the code？

**Comment by kingherc** [comment]
buildkite test this

**Review by szabosteve — APPROVED** [review]
Thank you for your contribution!

**Comment by szabosteve** [comment]
I think `nonsignificant` is the better word to use in this context though. `Nonsignificant` has the meaning of not statistically significant while the meaning of `insignificant` doesn't have mathematical connotations. I'm not a native speaker though.
@leemthompo What's your opinion?

**Comment by pionCham** [comment]
> I think `nonsignificant` is the better word to use in this context though. `Nonsignificant` has the meaning of not statistically significant while the meaning of `insignificant` doesn't have mathematical connotations. I'm not a native speaker though. @leemthompo What's your opinion?

Thanks for pointing out! But in this context ```Tokens whose weight is less than tokens_weight_threshold are considered nonsignificant and pruned. This value must be between 0 and 1. Default: 0.4``` , i think  the author does not highlight the salience ，so i'm more inclined to use the word `insignificant`  @szabosteve  😊

**Comment by kingherc** [comment]
Sounds good, since there's an approval I'm going ahead and merge this. If there are any comments in the future, we can discuss changing the nuances again.

**Pull request merged**
