### PR TITLE
[8.x] x-pack/plugin/otel-data: Fix dynamic template summary and summary_minmax (#113868)

### PR DESCRIPTION
**Pull request by carsonip**
# Backport

This will backport the following commits from `main` to `8.x`:
 - [x-pack/plugin/otel-data: Fix dynamic template summary and summary_minmax (#113868)](https://github.com/elastic/elasticsearch/pull/113868)

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

### CODE REVIEW

**Review by lahsivjar — APPROVED** [review]

**Comment by felixbarny** [comment]
@elasticmachine update branch

**Comment by felixbarny** [comment]
@elasticmachine test this please

**Comment by lahsivjar** [comment]
@elasticmachine update branch

**Comment by felixbarny** [comment]
@elasticmachine update branch

**Comment by john-wagster** [comment]
@elasticmachine update branch

**Comment by john-wagster** [comment]
@elasticmachine test this please

**Comment by carsonip** [comment]
@elasticmachine update branch

**Comment by felixbarny** [comment]
@elasticmachine update branch

**Comment by john-wagster** [comment]
@elasticmachine update branch

**Comment by john-wagster** [comment]
@elasticmachine update branch

**Pull request merged**
