### PR TITLE
Watcher: Remove cron eval CLI tool in favor of API endpoint

### PR DESCRIPTION
**Pull request by spinscale**
The cron evaluation CLI tool can just be an API. This commit
removes the CLI tool and adds a _xpack/watcher/_croneval REST endpoint
and its corresponding transport action.

The transport action has not implemented any serialization because the
request is always considered local and never sent across the network.

### CODE REVIEW

**Review by rjernst — APPROVED** [review]
Awesome! LGTM

**Comment by uboness** [comment]
+1 on exposing it as API, but why not still keep the cli (change it to use the API), at least until we have a user friendly UI for it in kibana?

**Review by martijnvg — APPROVED** [review]
LGTM

**Comment by hub-cap** [comment]
once this API is merged, can you add it to the high level rest client checklist @spinscale ? #29827

**Comment by spinscale** [comment]
@uboness the difference between the CLI tool and the dev-tools output is pretty small in the good case (a JSON list of expressions). Do you reckon that a BWC layer is necessary, which also includes code for JSON parsing, auth/SSL issues, exception handling?

From my point of view the cost of that above code is higher than not keeping a BWC layer and point users to the endpoint and use kibana dev-tools.

**Comment by spinscale** [comment]
@elasticmachine retest this please

**Comment by uboness** [comment]
> From my point of view the cost of that above code is higher than not keeping a BWC layer and point users to the endpoint and use kibana dev-tools.

when are we going to see a tool for it in Kibana? is there an issue open for it? When do we expect it to be available?

**Comment by spinscale** [comment]
stale. closing.

**Pull request closed without merging**
