### PR TITLE
SQL: Relax StackOverflow circuit breaker for constants

### LINKED ISSUE #38571: SQL: StackOverflow circuit breaker kicks in for IN with a long list of numbers
Long list of numbers (positive and negative) inside `IN` kicks in when 200 numbers are encountered.
This shouldn't be the case as constants (numbers or strings) don't contribute to the increase of the stack.

### PR DESCRIPTION
**Pull request by matriv**
Constant numbers (of any form: integers, decimals, negatives,
scientific) and strings shouldn't increase the depth counters
as they don't contribute to the increment of the stack depth.

Fixes: #38571

### CODE REVIEW

**Review by costin — APPROVED** [review]
LGTM. Thanks for the quick turnaround.

**Comment by matriv** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by matriv** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by matriv** [comment]
Backported to `7.x` with 871036bd2161f5cdc22ee9727a21cd69323ccd07
to `7.0` with b81dff6929b57b914a11a1df84344db5bf3d4bc6
to `6.7` with 7881639689d2f808f2dff77a23db5257fc018673

**Pull request merged**
