### PR TITLE
Upgrade remote cluster settings

### PR DESCRIPTION
**Pull request by jasontedor**
This commit adds settings upgraders for the `search.remote.*` settings that can be in the cluster state to automatically upgrade these settings to `cluster.remote.*`. Because of the infrastructure that we have here, these settings can be upgraded when recovering the cluster state, but also when a user tries to make a dynamic update for these settings.

Relates #33413, relates #33536

### CODE REVIEW

**Review by martijnvg — APPROVED** [review]
LGTM

**Comment by jasontedor** [comment]
@elasticmachine test this please

**Comment by jasontedor** [comment]
@elasticmachine run gradle build tests

**Comment by jasontedor** [comment]
@elasticmachine run sample packaging tests

**Review by s1monw — APPROVED** [review]

**Comment by jasontedor** [comment]
This is broken right now, and so is the work in #33536 for list settings. I added a full cluster restart test for this and found this issue. I discussed a possible path forward with @original-brownbear because this relates to #33503 too and he is going to run with it for now.

**Comment by jasontedor** [comment]
I pushed a full cluster restart test but it can not pass until #33589 and #33590 are in.

**Pull request merged**
