### PR TITLE
Switch default batch size for reindex to 1000

### PR DESCRIPTION
**Pull request by nik9000**
1000 is likely to perform much better.

### CODE REVIEW

**Comment by nik9000** [comment]
@tlrx want to review this?

@clintongormley we discussed this earlier today.

**Comment by clintongormley** [comment]
LGTM

**Comment by tlrx** [comment]
LGTM too :)

**Comment by nik9000** [comment]
Thanks for reviewing @clintongormley and @tlrx !

**Comment by clintongormley** [comment]
@nik9000 Would you backport this to 2.x as well please?

**Comment by nik9000** [comment]
Sure. I'll head back to the 2.x branch later today if possible.

**Comment by clintongormley** [comment]
thanks - btw i've already doc'ed the batch size as 1000 in 2.x (see https://github.com/elastic/elasticsearch/pull/18484)

**Comment by clintongormley** [comment]
@nik9000 scratch my previous comment - i've reverted that commit as I see you include the docs in this PR

**Comment by nik9000** [comment]
2.x: 62bf6c89644e0a220d8e6a56902c76aab0566bcb

**Comment by clintongormley** [comment]
thanks @nik9000

**Comment by persiarash** [comment]
Thanks @nik9000, but out of necessity, is there a way to configure the batch size, even if it isn't through the Java API? What I mean is that even something like a server-side configuration would do.

**Comment by nik9000** [comment]
You can't change the default but you can set it on each request. Of hand I
believe it is called batch_size in update_by_query and it is the "size"
field in the "source" object of a redirect.

**Comment by persiarash** [comment]
@nik9000 thanks for the quick reply.

I'm aware of the ability to change the batch size via the HTTP REST API, I believe it is called "scroll_size" there, however I don't see a way to set the same parameter via the Java API. All I see through the Java API is a "size", which is actually the hard cap on the total number of objects to process, not the batch size.

That's why I was hoping that there might be a way to configure this value on the server itself, via the yaml properties file. Because I don't think as a Java consumer of ES I have any other option (unless of course I write my own Java HTTP client to interface w/ ES via its HTTP API).

**Comment by nik9000** [comment]
In the Java API it is the size parameter on the search request.

**Comment by persiarash** [comment]
@nik9000 Are you sure? I tested this earlier today by setting size to 1000, what I got was an update which updated exactly 1000 items, and did so in 19 batches (1000 updates + 835 conflicts = 1835 total / 19 batches = batch-size of 100, which is the default for ES 2.3)

**Comment by nik9000** [comment]
This ought to work:
```
UpdateByQueryRequestBuilder requestBuilder = UpdateByQueryAction.INSTANCE.newRequestBuilder(CLIENT)
.source(toStringArray(indexIds))
.filter(queryBuilder)
.abortOnVersionConflict(false)
.consistency(WriteConsistencyLevel.DEFAULT)
.script(updateScript);
requestBuilder.source().size(1000);
```

**Comment by persiarash** [comment]
Thank you very much @nik9000, that (almost) did the trick! The solution for anyone else who is interested ended up being:
requestBuilder.source().setSize(1000);

Just FYI the Javadocs are VERY misleading about this, i.e.:
.setSize() => "The number of search hits to return. Defaults to 10."
Of course in this scenario it is actually the batch size, and it defaults to 100 (or 1000 in 2.4+)

**Comment by nik9000** [comment]
> Javadocs are VERY misleading

Yeah, part of the reason for that is that reindex is reusing SearchRequestBuilder to give you control over the search request it uses to start the scroll. So everything under `source()` from a scrolling perspective. But SearchRequestBuilder javadocs don't think about scrolling.

**Pull request merged**
