### PR TITLE
Inject `host.name` field without relying on (component) templates

### PR DESCRIPTION
**Pull request by salvatore-campagna**
We do not want to rely on templates or component templates to include
the `host.name` field in indices using LogsDB. The `host.name` field is a field
we sort on by default when LogsDB is used. As a result, we just inject it
by default, the same way we do for the `@timestamp` field. This prevents
sorting errors due to missing `host.name` field in mappings.

The `host.name` is a keyword field and depending on the value of `subobjects` it will
be mapped as a `name` keyword nested inside a `host` or as a flat `host.name` keyword.
We also include `ignore_above` as we normally do for keywords in observability mappings.

### CODE REVIEW

**Comment by salvatore-campagna** [comment]
I will add a test checking the different behaviour around injecting por not the field depending on whether the index is created as part of a data stream or as a standalone index. When created as a standalone index a missing `host.name` field in mappings results in a error due to a missing sort field.

**Review by martijnvg — APPROVED** [review]
LGTM

**Comment by salvatore-campagna** [comment]
@elasticsearchmachine test this please

**Review by felixbarny — APPROVED** [review]
LGTM. Depending on how we'll implement https://github.com/elastic/elasticsearch/issues/110792, we may not need to inject the `host.name` field in the future anymore.

**Comment by salvatore-campagna** [comment]
So I disabled the failing CI test `10_settings.yaml/missing hostname field` just to make the CI green and backport to 8.15. After the PR is backported and merged I will re-enable the test in 8.16 too. Of course I will enable the failing test in the backport PR before merging it.

**Pull request merged**
