### PR TITLE
Add inner hits to nested and parent/child queries

### PR DESCRIPTION
**Pull request by martijnvg**
Inner hits allows to embed nested inner objects, children documents or the parent document that contributed to the matching of the returned search hit as inner hits, which would otherwise be hidden.

Example search request w/ nested query:

``` bash
curl -XGET "http://localhost:9200/stack/question/_search" -d'
{
  "query": {
    "nested": {
      "path": "comments",
      "query": {
        "match": {
          "comments.text": "elasticsearch"
        }
      }
    }
  },
  "_source": {
    "include": "title"
  },
  "inner_hits": {
    "comments": {
      "path": {
        "comments": {
          "_source": {
            "include": "text"
          },
          "query": {
            "match": {
              "comments.text": "elasticsearch"
            }
          }
        }
      }
    }
  }
}'
```

Example response:

``` json
{
   "took": 16,
   "timed_out": false,
   "_shards": {
      "total": 5,
      "successful": 5,
      "failed": 0
   },
   "hits": {
      "total": 3,
      "max_score": 2.1920953,
      "hits": [
         {
            "_index": "stack",
            "_type": "question",
            "_id": "485316",
            "_score": 2.1920953,
            "_source": {
               "title": "timestamp +5 hours logstash"
            },
            "inner_hits": {
               "comments": {
                  "hits": {
                     "total": 1,
                     "max_score": 2.1920953,
                     "hits": [
                        {
                           "_index": "stack",
                           "_type": "question",
                           "_id": "485316",
                           "_nested": {
                              "field": "comments",
                              "offset": 2
                           },
                           "_score": 2.1920953,
                           "_source": {
                              "text": "So my timezone is EST which shows in the log, but the agent stamps 2013-03-06T17:03:56.934Z before it sends to elasticsearch."
                           }
                        }
                     ]
                  }
               }
            }
         },
         {
            "_index": "stack",
            "_type": "question",
            "_id": "107518",
            "_score": 1.8563976,
            "_source": {
               "title": "Web based file search in the lan?"
            },
            "inner_hits": {
               "comments": {
                  "hits": {
                     "total": 1,
                     "max_score": 1.8563976,
                     "hits": [
                        {
                           "_index": "stack",
                           "_type": "question",
                           "_id": "107518",
                           "_nested": {
                              "field": "comments",
                              "offset": 2
                           },
                           "_score": 1.8563976,
                           "_source": {
                              "text": "Did you ever settle on something? I am looking for something similar. Does Solr work? that seems to be the most common suggestion. I tried elasticsearch but didn't know how to add a network path as an index to it."
                           }
                        }
                     ]
                  }
               }
            }
         },
         {
            "_index": "stack",
            "_type": "question",
            "_id": "419532",
            "_score": 1.2994784,
            "_source": {
               "title": "How to silently buffer tunnel traffic on network split, and automatically renew the connection when possible?"
            },
            "inner_hits": {
               "comments": {
                  "hits": {
                     "total": 1,
                     "max_score": 1.2994784,
                     "hits": [
                        {
                           "_index": "stack",
                           "_type": "question",
                           "_id": "419532",
                           "_nested": {
                              "field": "comments",
                              "offset": 4
                           },
                           "_score": 1.2994784,
                           "_source": {
                              "text": "Let me elaborate. I'm using ElasticSearch replication, when network disconnects, it puts all \"cluster\" into \"yellow\" state, means writes are postponed. I want to use \"localhost\" as replica nodes' host setting in config, both in China and in Germany. Under this there will be daemons acting as tcp proxy buffer and handling disconnections nicely. That's the outline of the idea, however maybe it would better to just leave it to ElasticSearch's protocol and handle yellow state in my app."
                           }
                        }
                     ]
                  }
               }
            }
         }
      ]
   }
}
```

For documentation and more examples check the: `inner-hits.asciidoc` file.

Closes #3022, #3152

### CODE REVIEW

**Comment by aminakhan85** [comment]
Hi, has this feature of inner hits been implemented in ES Java API?

**Comment by martijnvg** [comment]
@aminakhan85 Yes, from version 1.5 on the nested, has_child and has_parent query/filter there is a new method with the name `innerHit(...)` that allows one to define inner hits. You can just pass a `QueryInnerHitBuilder` instance with no options set.

**Comment by aminakhan85** [comment]
@Martijnvg. Thanks for the info. Right now im using version 1.4. Ill upgrade to 1.5 and will check it out. Thanks

**Comment by aminakhan85** [comment]
Hello, looks like 1.5 official release is not available . When is it expected to be available? the latest I could find is 1.4.2

**Comment by martijnvg** [comment]
@aminakhan85 There is no date set on a release yet, but I expect it to be released in the coming months.

**Comment by aamirl** [comment]
Hi there, if my understanding of this new feature is correct, this will solve the following issue:

For example, let's say that a document has four objects in a nested field. Querying on the required filters results in only matching objects 1 and 3, but when we get the results via _source, we will pull back the entire document along with all four objects 1,2,3,4.

This new feature will allow us to exclude objects 2 and 4 from the results and pull back only 1 and 2 as part of the 'inner_objects' field. Does that sound correct?

**Comment by martijnvg** [comment]
(I think you meant 1 and 3 instead of 1 and 2 being returned?)
In your example inner_hits will return objects 1 and 3 since those inner
object are the matching ones.

On 21 January 2015 at 15:17, Aamir Latif <notifications@github.com> wrote:

> Hi there, if my understanding of this new feature is correct, this will
> solve the following issue:
>
> For example, let's say that a document has four objects in a nested field.
> Querying on the required filters results in only matching objects 1 and 3,
> but when we get the results via _source, we will pull back the entire
> document along with all four objects 1,2,3,4.
>
> This new feature will allow us to exclude objects 2 and 4 from the results
> and pull back only 1 and 2 as part of the 'inner_objects' field. Does that
> sound correct?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elasticsearch/elasticsearch/pull/8153#issuecomment-70844005>
> .
>



-- 
Met vriendelijke groet,

Martijn van Groningen

**Comment by aamirl** [comment]
Indeed yes, that's exactly what I meant - I updated my edited answer to that but you ended up responding to the email! Thanks a lot :+1: That's a great feature to have.

**Comment by tstibbs** [comment]
Just been trying this out (built from the head of the 1.x branch), looks great, really useful.

Quick bug report (don't want to raise a new issue for this as the feature isn't released yet, but will raise one if you think I should): if using a 'nested' type and you specify your child document as an object rather than an array, you get a classcast. i.e. your doc looks like this
```json
{
  "nested_field": {
    "make": "ford"
  }
}
```

When searching you will get a classcast like this:

> java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to java.util.List
>         at org.elasticsearch.search.fetch.FetchPhase.createNestedSearchHit(FetchPhase.java:294)
>         at org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:178)
>         at org.elasticsearch.search.fetch.innerhits.InnerHitsFetchSubPhase.hitExecute(InnerHitsFetchSubPhase.java:96)
>         at org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:190)
>         at org.elasticsearch.search.SearchService.executeFetchPhase(SearchService.java:501)

You can fix it by giving the child as an array, but I think that either the nested hits stuff should support this single child, or it should throw an error when you try to index a document using that syntax.

I'm also interested to know what the rules are for constructing the query that goes in the 'inner_hits' section?

**Comment by martijnvg** [comment]
@tstibbs Great to hear you're trying it out! This looks like a bug, so can you open issue for it?

All options defined here can be defined on a `inner_hits` element on a query:
http://www.elasticsearch.org/guide/en/elasticsearch/reference/1.x/search-request-inner-hits.html#_options

Beyond that it is also possible to define a top level `inner_hits` section in the body of the search request, as a standalone element it then also accepts a `query` element and a `inner_hits` element for nesting purposes: http://www.elasticsearch.org/guide/en/elasticsearch/reference/1.x/search-request-inner-hits.html#top-level-inner-hits

Top level `inner_hits` are useful if one requires inner hits outside of the scope of the query.

**Comment by serj-p** [comment]
The much-anticipated feature

**Comment by bkuraku** [comment]
I have an issue with usage of inner_hits. Version 1.7.1
My structure is parent: style and child: product. I tried this query: 
```
{
  "query": {
    "filtered": {
      "filter": {
        "or": [
          {
            "and": [
              {
                "term": {
                  "name": "embellished"
                }
              },
              {
                "has_child": {
                  "inner_hits": {
                    "size": 100
                  },
                  "query": {
                    "filtered": {
                      "filter": {
                        "term": {
                          "color": "black"
                        }
                      }
                    }
                  },
                  "type": "product"
                }
              }
            ]
          },
          {
            "and": [
              {
                "term": {
                  "name": "cutout"
                }
              },
              {
                "has_child": {
                  "inner_hits": {
                    "size": 100
                  },
                  "query": {
                    "filtered": {
                      "filter": {
                        "term": {
                          "color": "white"
                        }
                      }
                    }
                  },
                  "type": "product"
                }
              }
            ]
          }
        ]
      }
    }
  }
}

```
This gives me inner_hits for the styles that are result of the second part of "or" (name: cutout color: white) but not for the styles that are result of the the first "or" query (name: embellished color: black). All the hits for the first or query are 0. 

If I reverse the first and second query in "or" there are inner_hits for query (name: embellished color: black) but not for (name: cutout color: white). I am not sure why this happens. ISs my query wrong?

**Comment by clintongormley** [comment]
@bkuraku both your inner hits are using `product` as the name, so one overwrites the other.  Just specify distinct names, eg:

    GET _search
    {
      "query": {
        "filtered": {
          "filter": {
            "or": [
              {
                "and": [
                  {
                    "term": {
                      "name": "embellished"
                    }
                  },
                  {
                    "has_child": {
                      "inner_hits": {
                        "size": 100,
                        "name": "embellished"
                      },
                      "query": {
                        "filtered": {
                          "filter": {
                            "term": {
                              "color": "black"
                            }
                          }
                        }
                      },
                      "type": "product"
                    }
                  }
                ]
              },
              {
                "and": [
                  {
                    "term": {
                      "name": "cutout"
                    }
                  },
                  {
                    "has_child": {
                      "inner_hits": {
                        "size": 100,
                        "name": "cutout"
                      },
                      "query": {
                        "filtered": {
                          "filter": {
                            "term": {
                              "color": "white"
                            }
                          }
                        }
                      },
                      "type": "product"
                    }
                  }
                ]
              }
            ]
          }
        }
      }
    }

**Comment by bkuraku** [comment]
@clintongormley Thanks. That worked like a charm!!

**Comment by bkuraku** [comment]
As said before I have style (parent), product (child) and vendors (nested under product). when I try to query styles to get both product inner hits and vendors inner hits it seems to give olny one

 ```
{
  "query": {
    "filtered": {
      "filter": {
        "or": [
          {
            "and": [
              {
                "has_child": {
                  "filter": {
                    "or": [
                      {
                        "term": {
                          "color": "green"
                        }
                      },
                      {
                        "nested": {
                          "path": "vendors",
                          "filter": {
                            "terms": {
                              "vendors.vendorId": [
                                1046,
                                1288,
                                1280
                              ]
                            }
                          },
                          "inner_hits": {
                            "size": 100,
                            "name": "vendors1"
                          }
                        }
                      }
                    ]
                  },
                  "inner_hits": {
                    "name": "products1",
                    "size": 100
                  },
                  "type": "product"
                }
              }
            ]
          }
        ]
      }
    }
  }
}
```
When I do this I only get inner hits of products1 and always the vendors1 hits are 0. There are matching only because of vendorId attribute. Even in that case the inner_hits are in products1 and not in vendors1. Is this expected behavior?

**Comment by clintongormley** [comment]
@bkuraku Providing just a query without the related mapping and document makes it pretty hard to debug what you're doing.  Given that your previous issue was resolved by changing the document structure, I'd suggest asking the full question in the forum first: http://discuss.elastic.co/

Then, if the result of the discussion in the forum indicates that this is a bug, have a look at existing open issues, eg:

* [Nested docs](https://github.com/elastic/elasticsearch/issues?q=is%3Aopen+is%3Aissue+label%3A%22%3ANested+Docs%22)
* [Inner hits](https://github.com/elastic/elasticsearch/issues?utf8=✓&q=is%3Aopen+is%3Aissue+label%3A"%3AInner+Hits")

If you don't find anything related, then open a new issue with a full recreation

**Pull request merged**
