### PR TITLE
Re-enable lintian packaging test

### LINKED ISSUE #58730: [CI] DebMetadataTests test05CheckLintian failure
**Build scan**: https://gradle-enterprise.elastic.co/s/b2c54hdwwhm2y/console-log?task=:qa:os:destructiveDistroTest.default-deb

**Repro line**: packaging test, so no repro line

**Reproduces locally?**: packaging test, so no reproduction

**Applicable branches**: master

**Failure history**: Failed on master only, for both Ubuntu and Debian packaging tests.  Has failed in the past (see #52554) due to changes in `ml-cpp` but was fixed in February and has not failed since.

**Failure excerpt**:

```
org.elasticsearch.packaging.test.DebMetadataTests > test05CheckLintian FAILED |  
-- | --
  | org.elasticsearch.packaging.util.Shell$ShellException: Command was not successful: [bash -c lintian --fail-on-warnings /var/lib/jenkins/workspace/elastic+elasticsearch+master+multijob+packaging-tests-unix-gcp/os/debian-10-packaging/distribution/packages/deb/build/distributions/elasticsearch-8.0.0-SNAPSHOT-amd64.deb] |  
  | result: exitCode = [1] stdout = [<<Too large to read: 1039698 bytes>>] stderr = [warning: the authors of lintian do not recommend running it with root privileges! |  
  | warning: --fail-on-warnings is deprecated]
```

### PR DESCRIPTION
**Pull request by rjernst**
It appears the odd permission problems of NOTICE and the lintian
overrides file have disappeared, probably through further build cleanup.
This commit re-enables the lintian tests.

closes #58730

### CODE REVIEW

**Comment by rjernst** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by rjernst** [comment]
@elasticmachine run elasticsearch-ci/packaging-windows

**Review by mark-vieira — APPROVED** [review]
👍

**Comment by rjernst** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by rjernst** [comment]
@elasticmachine run elasticsearch-ci/2

**Pull request merged**
