### PR TITLE
Add ScriptCompiler interface

### PR DESCRIPTION
**Pull request by romseygeek**
TypeParser.ParserContext exposes a ScriptService allowing type parsers to
compile scripts from runtime fields (and in future, index-time scripts).  However,
ScriptService itself is a fairly heavyweight object, and you can only add script
parsers to it via the Plugin mechanism.

To make testing easier, this commit extracts a ScriptCompiler interface and makes
that available from ParserContext instead.

### CODE REVIEW

**Review by rjernst — COMMENTED** [review]
Thanks for opening this @romseygeek! This falls in line nicely with the future separations I had in mind for a stable plugin API.

I have one thought: can ScriptService implement ScriptCompiler? I think that will make using it easier, since a method reference won't be necessary, and no null checks will be needed as you have in IndexMetadataVerifier. The script service can be passed in, but it is effectively reduced to the narrower interface.

**Comment by romseygeek** [comment]
> can ScriptService implement ScriptCompiler?

Oh yes, that makes things much simpler.  I've pushed a change.

**Review by nik9000 — APPROVED** [review]
It makes me happy. Its one of those things where I don't trust myself to be a good judge so I asked you to bring in @rjernst. I'm glad he likes it.

**Review by rjernst — APPROVED** [review]
LGTM, thanks!

**Review by javanna — APPROVED** [review]
LGTM

**Pull request merged**
