### PR TITLE
Remove CompletableFuture from SSLConfigurationReloader

### PR DESCRIPTION
**Pull request by DaveCTurner**
Replaced with a `PlainActionFuture`, since it is never completed exceptionally.

### CODE REVIEW

**Comment by ywangd** [comment]
@DaveCTurner I think this could potentially re-introduce the issue fixed by #54999 (see also #54867). In summary, the use of the future isn't because SslService being unavailable but to ensure update to relevant SSL files are always handled.

**Comment by DaveCTurner** [comment]
I see. This is pretty trappy, and doesn't seem to be covered by a test? Even a comment would have helped. Ok, I'll do something different here.

**Comment by DaveCTurner** [comment]
Thanks @ywangd, this is ready for another look

**Review by ywangd — APPROVED** [review]
LGTM

> This is pretty trappy, and doesn't seem to be covered by a test? Even a comment would have helped. 

Yeah I agree a comment would have been good. It does have a [test](https://github.com/elastic/elasticsearch/blob/d031dea2693d20eff6ae1392d0a5eaad7a55df3d/x-pack/plugin/security/src/internalClusterTest/java/org/elasticsearch/xpack/ssl/SSLReloadDuringStartupIntegTests.java#L93). But due to the racing nature and how close the two statements are at each other (with no place to inject something in between), it happens only very rarely so that the test is not guaranteed to fail when the main code changes. It's more of a best effort.

**Comment by DaveCTurner** [comment]
:+1: I see, thanks Yang

**Pull request merged**
