### PR TITLE
Refactor file settings watcher to allow reuse of file watching logic

### PR DESCRIPTION
**Pull request by williamrandolph**
File-based settings should potentially support use cases besides operator settings. We plan to create an extension point that would allow alternate implementations. As a step towards that extension, we factor out the file-watching logic so that we can pass in the name of the file to watch, and potentially watch multiple files.

### CODE REVIEW

**Review by grcevski — COMMENTED** [review]
This looks pretty good. I think one thing that needs to be updated is the naming of the variables and methods in FileWatchService, such that they are not specific to the operator and settings. 

Namely, we want to reuse this for other directory and file pairs, so the naming should be purpose agnostic.

We also need a way to make the logging make sense. The purpose for the watcher should be supplied by the user of the watch service and not be hardcoded to file settings.

**Comment by williamrandolph** [comment]
@grcevski Good call! I've updated the variable names.

**Review by rjernst — COMMENTED** [review]
I think this might be cleaner as inheritance instead of delegation. A lot of the usage of the fileWatcheService once created is to just delegate to a similarly named method (doStart, etc). As an abstract class, this would all be unnecessary, so the concrete implementation can just have the method to process a file. The super constructor can still take the dir/filename, and the concrete implementation can determine that as it already does. Wdyt?

**Comment by williamrandolph** [comment]
@rjernst You're right that inheritance works much better here: there is much less repetition and coordination between classes. I'm going to close this PR and open a new one using the other approach.

**Pull request closed without merging**
