### PR TITLE
 Use settings from the context in BootstrapChecks

### PR DESCRIPTION
**Pull request by jkakavas**
instead of passing them in the constructor.

See https://github.com/elastic/elasticsearch/pull/32903#pullrequestreview-146812329

### CODE REVIEW

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by jkakavas** [comment]
Jenkins test this please

**Comment by jkakavas** [comment]
Jenkins run sample packaging tests

**Comment by jkakavas** [comment]
jenkins test this please

**Pull request merged**
