### PR TITLE
remove unused class `MainRequestBuilder`

### PR DESCRIPTION
**Pull request by chengyang14**
remove unused class `MainRequestBuilder`

### CODE REVIEW

**Review by rjernst — APPROVED** [review]
LGTM for 8.0, but I believe this may be necessary to keep in 7.x because of the transport client? I could be misremembering though

**Comment by chengyang14** [comment]
@rjernst can you help merge this ?

**Comment by rjernst** [comment]
@elasticmachine ok to test

**Comment by rjernst** [comment]
@elasticmachine update branch

**Comment by pugnascotia** [comment]
@rjernst did you resolve whether this can be backported or not?

**Comment by rjernst** [comment]
It should not be backported, since the transport client still exists in 7.x. I'll remove the label.

**Pull request merged**
