### PR TITLE
[DOCS] Add missing HTML anchors to CCR and ML

### PR DESCRIPTION
**Pull request by ugosan**
HTML anchors are really useful when we need to reference a specific setting for a customer in consulting/support, specially if the list of parameters is long.

Same as [PR #76194](https://github.com/elastic/elasticsearch/pull/76194), adding some HTML anchors for some parameters in the CCR and ML.

PS: It would be even more useful if the anchors for the specific parameters are also "hoverable/clickable" like the titles are, as it would be easier to copy (I'm currently copying the anchor reference from the html itself)

### CODE REVIEW

**Comment by lockewritesdocs** [comment]
@elasticmachine update branch

**Comment by lockewritesdocs** [comment]
There are some odd Java-related errors in the [docs-check](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+docs-check/430/console) build:

```
16:29:18 > Task :distribution:packages:aarch64-deb:spotlessJava FAILED
16:29:18 You need to add a repository containing the '[com.google.googlejavaformat:google-java-format:1.12.0]' artifact in 'distribution/packages/aarch64-deb/build.gradle'.
...
16:29:24 Execution failed for task ':distribution:packages:aarch64-deb:spotlessJava'.
16:29:24 > Cannot add a configuration with name 'spotless865452459' as a configuration with that name already exists.
```

**Comment by lcawl** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by lcawl** [comment]
@elasticmachine run elasticsearch-ci/docs-check

**Review by lcawl — APPROVED** [review]
LGTM

**Pull request merged**
