### PR TITLE
Introduce skipping on known_issues and awaits_fix for YAML specs

### PR DESCRIPTION
**Pull request by mosche**
Introduce skipping on known_issues and awaits_fix for YAML Rest tests to match the expressiveness of previous version based skipping.

For instance:
```yaml
"Buggy test with known issues":
 - skip:
      known_issues:
        - cluster_feature: feature_y
          fixed_by:        feature_y_fix
      reason: Intermittently skipped with buggy feature_y until fixed by feature_y_fix
```

```yaml
"Muted test using awaits fix":
 - skip:
      awaits_fix: https://github.com/elastic/elasticsearch/issues/xyz
      reason:     Muted due to #xyz
```

### CODE REVIEW

**Review by ldematte — COMMENTED** [review]
Overall this looks good, and it is a very useful feature to have!
I would only recommend to introduce a couple of tests to `ClientYamlTestSuiteTests`; the parser can behave differently based on context, I would try to add at least one test with the new keywords (ideally one for the test section, plus a small one for setup, teardown)

**Comment by mosche** [comment]
I suppose you mean `PrerequisiteSectionTests`? I've added one missing test case, everything else should be covered

**Comment by mosche** [comment]
ok, done

**Review by ldematte — APPROVED** [review]
Thank you! LGTM, provided CI passes

**Comment by mosche** [comment]
@elasticmachine update branch

**Pull request merged**
