### PR TITLE
[vagrant] packaging tests: add parametrized retries for dnf install

### PR DESCRIPTION
**Pull request by dliappis**
Given that dnf doesn't do retries, installation of openjdk can sometimes be affected by checksum or network issues with mirrors offered by metalink.

This PR adds up to 5 retries for dnf based distros (Fedora for the moment).
The retry mechanism can be used by other distros too, by just setting the variable `install_command_retries` to any integer >0 in the corresponding section. At the moment this PR enables retries only for dnf based distros, as `install_command_retries` is set to `0` by default at the `provision()` level.

This PR has been extensively tested on Fedora 24: https://devops-ci.elastic.co/job/elastic+elasticsearch+master+fc24-retrytests/

### CODE REVIEW

**Review by jasontedor — APPROVED** [review]
LGTM.

**Review by nik9000 — APPROVED** [review]
LGTM as well. Do you want me to merge and backport or would you like to do so?

**Comment by dliappis** [comment]
@nik9000 would be great if you the bandwidth to merge and backport! (otherwise just let me know)

**Comment by nik9000** [comment]
Sure! I'm merging and backporting some small docs changes I've been tinkering with lately so I'll backport this when I backport those.

**Comment by nik9000** [comment]
master: 02dd1ba61a6bdc2163eaee327a6938f8517c7f41
5.x: 9d7af2a8ac45b656eafb63773c01b16cdaf32ff2
5.0: 388f65a639d5086597de77ca53bdaa5b720ff4e0

**Comment by dliappis** [comment]
Thank you @nik9000 !

**Comment by nik9000** [comment]
Thanks for fixing it! Even if dnf has mostly fixed this issue it'll be nice to have the infrastructure to retry if we need it.

**Pull request merged**
