### PR TITLE
[7.2][DOCS] Update data frame transform URLs (#46940)

### PR DESCRIPTION
**Pull request by lcawl**
Backports #46940

### CODE REVIEW

**Comment by lcawl** [comment]
@elasticmachine, run elasticsearch-ci/bwc

**Comment by lcawl** [comment]
@elasticmachine, run elasticsearch-ci/default-distro

**Comment by lcawl** [comment]
@elasticmachine, run elasticsearch-ci/bwc

**Comment by jasontedor** [comment]
@elasticmachine update branch

**Pull request merged**
