### PR TITLE
Upgrade to Netty 4.1.38

### PR DESCRIPTION
**Pull request by original-brownbear**
* A number of fixes to buffer handling in the .37 and .38 -> we should stay up to date

### CODE REVIEW

**Review by Tim-Brooks — COMMENTED** [review]
LGTM, but this should not be released in a release version of Elasticsearch without https://github.com/elastic/elasticsearch/pull/44837. 4.1.37 starts using direct buffers on the read path and we need to mitigate that.

**Review by Tim-Brooks — APPROVED** [review]

**Comment by original-brownbear** [comment]
@tbrooks8 thanks, I'll hold off merging this one until  #44837  is merged then :)

**Comment by original-brownbear** [comment]
@elasticmachine update branch

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/2

**Pull request merged**
