### PR TITLE
[7.15] [DOCS] Update remote cluster docs (#77043) (#78212)

### PR DESCRIPTION
**Pull request by lockewritesdocs**
Backports the following commits to 7.15:
 - [DOCS] Update remote cluster docs (#77043) (#78212)

### CODE REVIEW

**Comment by gtback** [comment]
@elasticmachine run elasticsearch-ci/docs rebuild

**Comment by lockewritesdocs** [comment]
@elasticmachine update branch

**Comment by lockewritesdocs** [comment]
@elasticmachine update branch

**Comment by gtback** [comment]
@elasticmachine run elasticsearch-ci/docs rebuild

**Pull request merged**
