### PR TITLE
Remove LegacyCTRAListener from ShardStateAction

### PR DESCRIPTION
**Pull request by DaveCTurner**
Relates #83784

### CODE REVIEW

**Review by joegallo — APPROVED** [review]
LGTM, but I find the `.success(task, task)` a bit bleh -- if this ends up being a popular pattern for handling these, then a `.success(task)` arity that juggles the types just so might be handy.

I like this pattern, though! It makes me want to revisit my two previous PRs and give them the same treatment.

**Comment by DaveCTurner** [comment]
Changed my mind, I think this pattern is tricksy for the general reason that re-using listeners is tricksy. It'd be worth it if profiling shows we create too many objects here but otherwise I would like to keep things clear - see 5f93f8e0a88feeb89859cca1d09c35e5408021d0.

**Comment by DaveCTurner** [comment]
@elasticmachine please run elasticsearch-ci/bwc

**Comment by joegallo** [comment]
Still LGTM.

**Comment by DaveCTurner** [comment]
Hit https://github.com/elastic/elasticsearch/issues/83567 twice :(

@elasticmachine please run elasticsearch-ci/bwc

**Pull request merged**
