### PR TITLE
[API] spelling: input

### PR DESCRIPTION
**Pull request by jsoref**
`intputSet`/`inputSet` appears to be an API which should get a distinct review. (Note: similar spelling changes that aren't technically part of the API are included as well.)
split from #37035

### CODE REVIEW

**Comment by javanna** [comment]
test this please

**Comment by jsoref** [comment]
Sorry @javanna , please retest

**Comment by javanna** [comment]
retest this please

**Comment by javanna** [comment]
run gradle build tests 1

**Review by javanna — APPROVED** [review]

**Comment by javanna** [comment]
thanks @jsoref !

**Pull request merged**
