### PR TITLE
Remove unused index store in directory service

### PR DESCRIPTION
**Pull request by danielmitterdorfer**
With this commit we remove the unused field `indexStore` from all
implementations of `FsDirectoryService`.

### CODE REVIEW

**Comment by danielmitterdorfer** [comment]
@elasticmachine test this please

**Comment by danielmitterdorfer** [comment]
@elasticmachine test this please

**Comment by danielmitterdorfer** [comment]
@elasticmachine run default distro tests

**Review by ywelsch — APPROVED** [review]

**Comment by danielmitterdorfer** [comment]
Backported to 6.x in https://github.com/elastic/elasticsearch/commit/7627b5163378cc37b7f6f7d8fe963b3b68213e03.

**Pull request merged**
