### PR TITLE
Remove reading Lucene version from bwc versions build logic

### PR DESCRIPTION
**Pull request by rjernst**
Version.java currently contains mappings to the Lucene version for each Elasticsearch version. The only use of this in the build logic is for filtering based on index compatibility. However, that compatibility can be inferred based on the Elasticsearch major version since there is a one to one mapping between Elasticsearch major and Lucene major. This commit removes Lucene version extraction from the build bwc logic.

### CODE REVIEW

**Comment by mark-vieira** [comment]
Given the conversation around `IndexVersion` I'm wonder if we should defer and just use that instead here rather than going back to relying on the implicit "lucene version matches major version" semantic that we wanted to make more explicit with this change.

**Comment by rjernst** [comment]
I don't think IndexVersion would work here. The bwc tests are specifically designed to test backcompat of Elasticsearch stateful versions. IndexVersion is something that will be attached to an index (the index version created property which already exists), but it's not a property of a node (other than "latest" that new indices would use). So we would not be able to infer Elasticsearch versions based on reading which IndexVersion constants we know about.

**Comment by mark-vieira** [comment]
> I don't think IndexVersion would work here. The bwc tests are specifically designed to test backcompat of Elasticsearch stateful versions. IndexVersion is something that will be attached to an index (the index version created property which already exists), but it's not a property of a node (other than "latest" that new indices would use). So we would not be able to infer Elasticsearch versions based on reading which IndexVersion constants we know about.

My presumption would be similar to what we do today in that we'd support a minimum index version, and each stack version would have what index version it uses. Similar to what we've done with `TransportVersion` we retroactively went back and just created versions for each stack version.

**Comment by rjernst** [comment]
> each stack version would have what index version it uses

This is exactly what we want to avoid. We don't need this mapping except for tests. If we want to keep it for testing (say in a separate file in the build) that would be fine, we could even update it when we bump stack version based on IndexVersion.CURRENT. However, IndexVersion will not imply anything about compatibility between versions. It's purpose is to a capture the behavior regarding index/search operations at a point in time, so that we can maintain that behavior for indexes created then.

**Review by mark-vieira — APPROVED** [review]
LGTM

**Pull request merged**
