### PR TITLE
IndexNameExpressionResolver refactoring

### PR DESCRIPTION
**Pull request by gmarouli**
The goal of this PR is to increase the maintainability of the `IndexNameExpressionResolver`. The actions we took to achieve it are the following:

- Switched the expression resolution, from taking a list of expressions through each steps, to taking each expression through all the steps. 
- We collected all the system accessibility related code to one class. We found discrepancies between in different places. For now, we preserved this differentiation in behaviour but we do want to double check as a follow up.
- As a result of the first bullet the scope of the `DateMathExpressionResolver` and the `WildcardExpressionResolver` reduced significantly and the same happened to their unit tests. Some test cases were moved, or they were already covered in the `IndexNameExpressionResolverTests`.

The commits are not standalone, but the changes in each commit are "themed" and there is a small explanation in the commit message to help with reviewing.

### CODE REVIEW

**Comment by gmarouli** [comment]
@elasticmachine update branch

**Review by jbaiera — APPROVED** [review]
LGTM

Sorry for the long review, the refactoring moved a lot of code around and it was hard for my brain to follow everything in the diffs. I put up a quick test typo fix and once CI is green either of us can hit the merge button so we can start checking this on benchmarks.

**Comment by jbaiera** [comment]
@elasticmachine update branch

**Comment by gmarouli** [comment]
@elasticmachine update branch

**Comment by gmarouli** [comment]
@jbaiera thank you, I understand that reviewing this is probably harder than coding it. Thank you for fixing the typo as well!

**Comment by gmarouli** [comment]
@elasticmachine update branch

**Comment by gmarouli** [comment]
@elasticmachine update branch

**Comment by gmarouli** [comment]
@elasticmachine update branch

**Comment by gmarouli** [comment]
@elasticmachine update branch

**Comment by gmarouli** [comment]
@elasticmachine update branch

**Comment by gmarouli** [comment]
Tests have passed but somehow this did not get notified. I will merge it.

**Comment by gmarouli** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.x|[](https://github.com/elastic/elasticsearch/pull/117267)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

**Pull request merged**
