### PR TITLE
Introduce RefCounted#mustIncRef

### PR DESCRIPTION
**Pull request by DaveCTurner**
In several places we acquire a ref to a resource that we are certain is
not closed, so this commit adds a utility for asserting this to be the
case. This also helps a little with mocks since boolean methods like
`tryIncRef()` return `false` on mock objects by default, but void
methods like `mustIncRef()` default to being a no-op.

### CODE REVIEW

**Review by original-brownbear — COMMENTED** [review]
Hmm I like this but now I'm wondering, maybe `incRef` should just assert this? It's always a bug to try and inc an already release resource pretty much. I couldn't think of a non-bug scenario where that's a good pattern (to inc and fail and handle failure)?

**Comment by DaveCTurner** [comment]
I don't think that's true, we rely on the acquire-or-throw behaviour actually throwing in various places, typically in less async code that's doing things like IO so exceptions are expected anyway. At least, I couldn't see obvious arguments for replacing all the `incRef()` calls I didn't replace in this PR.

Not sure `IllegalStateException` is the right choice tho, surely `AlreadyClosedException` is better?

**Comment by DaveCTurner** [comment]
I could, however, see an argument for making this the default behaviour and converting all the inc-or-throw cases into something else.

**Review by original-brownbear — APPROVED** [review]
LGTM, sorry for the delay GH must have eaten my review earlier or something ... :D

**Pull request merged**
