### PR TITLE
Handle upserts failing when document has already been created by another process

### PR DESCRIPTION
**Pull request by vedil**
fix for #11506 and https://github.com/elastic/elasticsearch/issues/9821

### CODE REVIEW

**Comment by vedil** [comment]
now the failures are down to 1 
Tests with failures:
  - org.elasticsearch.index.engine.InternalEngineTests.testVersioningCreateExistsExceptionWithFlush

checking if the version is sent as parameter and throwing exception only in that case

**Comment by vedil** [comment]
now i got a clean build and also got my test to run and succeed by using mvn test -Des.node.mode=local -Dtests.class=org.elasticsearch.action.IndicesRequestTests "-Dtests.method=*Update*" -Dtests.filter="@slow"  -e

**Comment by vedil** [comment]
just to re-iterate, there is nothing more that i can do to get this merged?

**Comment by clintongormley** [comment]
@vedil we just need to get it reviewed. sorry for the delays

@jasontedor could you take a look please?

**Comment by jasontedor** [comment]
@vedil Thank you for raising this to our attention; it does seem like there might be a race condition here. Before we take any action on this, would you mind 

* removing the [commit 1c5f8de](https://github.com/vedil/elasticsearch/commit/1c5f8deccc14b55a670e05550ca3b82bb8a1f47d) from this pull request that is germane to #9821 as that issue is closed
* removing the [commit e15e2a2] (https://github.com/vedil/elasticsearch/commit/e15e2a2cded61dc19f10a708073ea4c6bd1c486a) as it's only code formatting
* squashing the remaining commits into one

Thanks!

**Comment by vedil** [comment]
messed up some thing while re-basing, so created another pull request with just the change and the test case https://github.com/elastic/elasticsearch/pull/12137

**Pull request closed without merging**
