### PR TITLE
Include the resolve index action in the view_index_metadata privilege

### PR DESCRIPTION
**Pull request by danhermann**
The resolve index action was never explicitly included in any existing index privileges, so because of its name (`indices:admin/resolve/index`) it was available only in relatively elevated privileges such as `manage`. The endpoint exposes no more information than is available in the get index, get alias, and get data stream endpoints which are already included in the lesser `view_index_metadata` privilege. As such, it makes sense to explicitly include resolve index in the `view_index_metadata` privilege.

Relates to https://github.com/elastic/kibana/issues/72219

### CODE REVIEW

**Review by probakowski — APPROVED** [review]
LGTM, do we we want to add some test for it as well maybe?

**Comment by liza-mae** [comment]
@danhermann when will this be back ported?  It needs to make the next 7.9.0 BC.

**Comment by droberts195** [comment]
Since elastic/kibana#72219 is a blocker for 7.9.0 and this is the fix for it I think this should also be labelled as a blocker for 7.9.0 so that the importance of fully completing the work is clearer.

**Comment by danhermann** [comment]
This has been backported to 7.9 and will be picked up in the next BC.

**Pull request merged**
