### PR TITLE
[DOCS] Document 200 http code response for partial results

### LINKED ISSUE #23059: http 200 response code for partial result
**Elasticsearch version**: 2.4.0
A _search partial response comes back with http code `200: OK`.  I would have expected this to be a `206: Partial Content`. 

I did not find this behavior documented, and only a short paragraph that states we can return a partial response: https://www.elastic.co/guide/en/elasticsearch/reference/5.1/docs-replication.html#_failure_handling_2

```
{
  "took": 9918,
  "timed_out": false,
  "_shards": {
    "total": 64,
    "successful": 27,
    "failed": 37,
    "failures": [
      {
        "shard": 1,
        "index": "data-20170101",
        "node": "dqqZ8_s7Q7CKzABoyJjLAg",
        "reason": {
          "type": "es_rejected_execution_exception",
          "reason": "rejected execution of org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler@47e9a0ad on EsThreadPoolExecutor[search, queue capacity = 1000, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@5f83d265[Running, pool size = 48, active threads = 48, queued tasks = 1000, completed tasks = 10576391]]"
        }
      },
      ...
    ]
  },
  "hits": {
    ...
  }
}
```

### PR DESCRIPTION
**Pull request by jrodewig**
Documents that API responses with partial results will provide a `200 OK` HTTP status code.

Makes a few other supporting changes:
- Wraps lines to ~80 characters
- Renames heading to `Shard failures` (page has another `Failure handling` heading).
- Notes Document APIs that can return partial results.
- Notes that shard failure is indicated by the `timed_out` and `_shards` response header fields

Closes #23059

### CODE REVIEW

**Comment by jrodewig** [comment]
Hi @jpcarey 

Let me know if this addresses your concerns from #23059.

Here's the particular note about the 200 http status code:
https://github.com/elastic/elasticsearch/pull/40367/commits/1f6766055ac1d82f06990acb19ab9b944d2e24c7#diff-1adb53bf3287b1537ac0d9c042cf1fb9R119

**Comment by jrodewig** [comment]
@ywelsch Do you mind taking a look and letting me know your thoughts?

Happy to close or rewrite if needed.

**Review by ywelsch — APPROVED** [review]
Might be good to add or cross-link this as well in some of the other sections (e.g. the main search page `search.asciidoc`)

**Comment by jrodewig** [comment]
Thanks @ywelsch. 1c70fc3 adds cross-links in the mentioned APIs.

**Pull request merged**
