### PR TITLE
SQL: Added SSL configuration options tests

### PR DESCRIPTION
**Pull request by astefan**
This PR adds tests for the SSL configuration options and checks they can be specified in both a Properties object and in the URL of a JDBC connection. They were already supported in the URL, this PR only adds tests specifically for them.

Also, the `allow.self.signed` option from the documentation is removed to keep the settings consistent with the rest of projects around Elasticsearch (which don't have such an option) and because it's somewhat redundant to allow this option, as it's somehow obvious that if an user added the server's self-signed certificate to the keystore, that user is aware what type the respective certificate is.

Fixes https://github.com/elastic/elasticsearch/issues/37711.

### CODE REVIEW

**Review by matriv — APPROVED** [review]
LGTM

**Review by costin — APPROVED** [review]
Can you please add a test where the driver itself is initialized either through the DataSource or the DriverManager.getDriver api.
Also one with typos to the correct SSL configuration is being shown?

**Comment by astefan** [comment]
@elasticmachine run elasticsearch-ci/1
@elasticmachine run elasticsearch-ci/2
@elasticmachine run elasticsearch-ci/default-distro

**Comment by astefan** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by astefan** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by astefan** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by astefan** [comment]
@elasticmachine run elasticsearch-ci/default-distro

**Comment by astefan** [comment]
@elasticmachine run elasticsearch-ci/1
@elasticmachine run elasticsearch-ci/2

**Comment by astefan** [comment]
@elasticmachine run elasticsearch-ci/default-distro

**Comment by astefan** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by astefan** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by astefan** [comment]
@elasticmachine run elasticsearch-ci/1
@elasticmachine run elasticsearch-ci/2

**Comment by astefan** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by astefan** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by astefan** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by astefan** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by astefan** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by astefan** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by astefan** [comment]
@elasticmachine run elasticsearch-ci/docs-check

**Comment by astefan** [comment]
@elasticmachine run elasticsearch-ci/docs-check
@elasticmachine run elasticsearch-ci/1

**Comment by costin** [comment]
@elasticmachine run elasticsearch-ci/docs-check
@elasticmachine run elasticsearch-ci/1

**Pull request merged**
