### PR TITLE
[DOCS] Remove `testenv` annotations from doc snippet tests

### PR DESCRIPTION
**Pull request by jrodewig**
Removes `testenv` annotations and related code. These annotations originally let you skip x-pack snippet tests in the docs. However, that's no longer possible.

Relates to #79309, #31619

### CODE REVIEW

**Comment by jrodewig** [comment]
After taking a closer look and running some local tests, I'm pretty sure that `testenv` doesn't do anything. I pushed 571090a6552f10fd99f33162e8c04522f9bc659f to remove the supporting code and the remaining annotations.

Most the file changes are annotations. For easier review, I'll flag the actual code changes.

**Comment by jrodewig** [comment]
@elasticmachine update branch

**Comment by jrodewig** [comment]
@elasticmachine update branch

**Review by mark-vieira — APPROVED** [review]
LGTM

**Comment by jrodewig** [comment]
Thanks @mark-vieira!

**Pull request merged**
