### PR TITLE
[DOCS] Add verify parameter to snapshot documentation

### PR DESCRIPTION
**Pull request by tlrx**
The `verify` parameter is not documented.

### CODE REVIEW

**Comment by dadoonet** [comment]
Should we remove it from here then? 

http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html#_shared_file_system_repository

**Comment by dadoonet** [comment]
Ignore my comment. I think it's OK to have it on both places.
May be a link from the FS part to the section you just updated?

**Comment by tlrx** [comment]
@dadoonet no you're right, the `verify` setting in FS repository must be removed because it's not supported.

**Comment by dadoonet** [comment]
LGTM. +1 to push

**Comment by s1monw** [comment]
LGTM too

**Pull request merged**
