### PR TITLE
Add Tests for findSamlRealm

### PR DESCRIPTION
**Pull request by jkakavas**

### CODE REVIEW

**Comment by tvernum** [comment]
I think this is a bad idea.
I'll review properly tomorrow, but if Kibana has a realm name, then it shouldn't send an ACS. There's no reason for ES to ignore what is sent, just don't send it.

**Comment by jkakavas** [comment]
Thanks for the quick feedback Tim. I'll leave the findSamlRealms as is so that if a request contains an ACS URL, it also needs to match. 
I'll rephrase the PR as adding a test.

**Comment by tvernum** [comment]
Thanks @jkakavas. Sorry if my response was too direct, it was late and I wanted to get something to you before I went to bed.

**Review by tvernum — APPROVED** [review]
👍

**Pull request merged**
