### PR TITLE
Fix indentation in has-parent-query

### PR DESCRIPTION
**Pull request by nodkz**

### CODE REVIEW

**Comment by nik9000** [comment]
Makes sense to me. Thanks!

**Comment by nodkz** [comment]
@nik9000 Can you help me to find all descriptions for the Elastic API outputs - fields and types?
All input arguments already parsed from https://github.com/elastic/elasticsearch-js/blob/master/src/lib/apis/ 
Will be cool if I typed all outputs in GraphQL. 

Writing a GraphQL wrapper over Elastic REST API:
https://github.com/nodkz/graphql-compose-elasticsearch

**Comment by nik9000** [comment]
So we track the inputs pretty well. I believe the files you linked are generated from the REST suite files in Elasticsearch's code base. The output we aren't as careful to track. The https://github.com/elastic/elasticsearch-net folks track it pretty carefully though.


5.2: 40c221ef31e9a5b968e493d39055df53b4a93f4e
5.3: 2abe7a3f04d0e7c4674eae5a7b965c60059053af
5.x: 53da3d70ed7ea5099f3c5a5e43bd7c133a52875b
master: 5da7cefbe2eb7f009af937a337866dd8ee743057

**Comment by nodkz** [comment]
Inputs are generated from installed `elasticsearch` module when graphql server starts. So API absolutely compatible with the installed module. 

So think that better to keep outputs polymorphic for now. If it can not be obtained directly from server or `elasticsearch` module.

**Pull request merged**
