### PR TITLE
JvmService use SingleObjectCache

### PR DESCRIPTION
**Pull request by mushao999**
In [[[STORE] Add simple cache for StoreStats]](https://github.com/elastic/elasticsearch/commit/85c611a1b70627b2d1a6fbd254668b4ae64dff2b), @s1monw  introduced a simple cache for `StoreStats`, `FsStats`, `NetworkStats`, `OsStats`, `ProcessStats`, but not `JvmStats`.
This PR  we introduce the `SingleObjectCache` into `JvmService`.
I also remove the useless `synchronized` in `OsService#stats()`.

### CODE REVIEW

**Comment by dakrone** [comment]
@elasticmachine ok to test

**Comment by dakrone** [comment]
@mushao999 out of curiosity, is this is something that you ran into problems with, or are you just bringing it into parity with the other stats pieces?

**Comment by dakrone** [comment]
@elasticmachine update branch

**Comment by mushao999** [comment]
> @mushao999 out of curiosity, is this is something that you ran into problems with, or are you just bringing it into parity with the other stats pieces?

@dakrone No problems found actually. I was writing an elasticsearch plugin that may use MonitorService and then found that small difference between JvmService and other stats service.

**Review by dakrone — APPROVED** [review]
LGTM, thanks for doing this!

**Pull request merged**
