### PR TITLE
Add sort optimization with after from Lucene

### PR DESCRIPTION
**Pull request by mayya-sharipova**
Lucene 8.7 introduces numeric sort optimization directly in comparators.
This means we don't need to have it in ES.
This removes the sort optimization code in ES, and
the only thing that is needed is setCanUsePoints on sortField.

This also will introduce sort optimization with search_after,
as Lucene directly supports sort optimization with search_after.

As previously, we enable sort optimization only when there is 
Long sort on Long or Date fields.

There could be a regression on desc sort, for example on 
@timestamp desc field. In this case, we suggest to 
convert these indices to data stream indices, as 
datatastream indices have their desc sort on 
@timestamp field optimized

### CODE REVIEW

**Comment by mayya-sharipova** [comment]
Rally benchmarking results for geonames (http_longs to follow):

baseline: master branch
contender: this PR

```
|                                                        Metric |                           Task |    Baseline |   Contender |     Diff |   Unit |
|--------------------------------------------------------------:|-------------------------------:|------------:|------------:|---------:|-------:|
|                                  50th percentile service time |           desc_sort_population |     52.4295 |     4.67878 | -47.7508 |     ms |
|                                  90th percentile service time |           desc_sort_population |     53.9994 |     4.79027 | -49.2092 |     ms |
|                                  99th percentile service time |           desc_sort_population |     54.9973 |     4.98468 | -50.0127 |     ms |
|                                 100th percentile service time |           desc_sort_population |     55.0597 |      5.2847 |  -49.775 |     ms |

|                                  50th percentile service time |            asc_sort_population |     53.3332 |     3.91246 | -49.4207 |     ms |
|                                  90th percentile service time |            asc_sort_population |     55.0845 |     4.00362 | -51.0809 |     ms |
|                                  99th percentile service time |            asc_sort_population |     74.9326 |     5.11153 |  -69.821 |     ms |
|                                 100th percentile service time |            asc_sort_population |     78.6209 |     9.93631 | -68.6846 |     ms |

|                                  50th percentile service time | asc_sort_with_after_population |     76.1371 |     7.88222 | -68.2549 |     ms |
|                                  90th percentile service time | asc_sort_with_after_population |     80.8901 |     8.05058 | -72.8395 |     ms |
|                                  99th percentile service time | asc_sort_with_after_population |     97.8003 |     8.35941 | -89.4409 |     ms |
|                                 100th percentile service time | asc_sort_with_after_population |     104.533 |     8.39089 | -96.1425 |     ms |

|                                  50th percentile service time |            desc_sort_geonameid |     8.13857 |     5.62399 | -2.51459 |     ms |
|                                  90th percentile service time |            desc_sort_geonameid |     10.3497 |     5.72067 | -4.62899 |     ms |
|                                  99th percentile service time |            desc_sort_geonameid |     13.5153 |     7.49825 | -6.01707 |     ms |
|                                 100th percentile service time |            desc_sort_geonameid |     19.6222 |     7.61355 | -12.0086 |     ms |

|                                  50th percentile service time | desc_sort_with_after_geonameid |     67.1275 |     20.2335 |  -46.894 |     ms |
|                                  90th percentile service time | desc_sort_with_after_geonameid |     68.6301 |     20.8645 | -47.7656 |     ms |
|                                  99th percentile service time | desc_sort_with_after_geonameid |      69.694 |     23.5649 | -46.1291 |     ms |
|                                 100th percentile service time | desc_sort_with_after_geonameid |     69.9783 |      25.656 | -44.3223 |     ms |
                                            
|                                  50th percentile service time |             asc_sort_geonameid |     6.21184 |      4.4267 | -1.78514 |     ms |
|                                  90th percentile service time |             asc_sort_geonameid |     6.35723 |     4.49574 | -1.86149 |     ms |
|                                  99th percentile service time |             asc_sort_geonameid |     6.62406 |     5.30552 | -1.31854 |     ms |
|                                 100th percentile service time |             asc_sort_geonameid |     6.85049 |     10.6745 |  3.82397 |     ms |
|                                                    
|                                  50th percentile service time |  asc_sort_with_after_geonameid |     62.5055 |     8.91216 | -53.5934 |     ms |
|                                  90th percentile service time |  asc_sort_with_after_geonameid |     64.3278 |     9.06383 | -55.2639 |     ms |
|                                  99th percentile service time |  asc_sort_with_after_geonameid |     67.5103 |     9.42481 | -58.0855 |     ms |
|                                 100th percentile service time |  asc_sort_with_after_geonameid |     67.6121 |     10.0498 | -57.5624 |     ms |
```

**Comment by mayya-sharipova** [comment]
http_logs results:
```
|                                                        Metric |                                                   Task |    Baseline |   Contender |     Diff |    Unit |
|--------------------------------------------------------------:|-------------------------------------------------------:|------------:|------------:|---------:|--------:|
|                                  50th percentile service time |                                    desc_sort_timestamp |     79.2801 |     728.161 |   648.88 |      ms |
|                                  90th percentile service time |                                    desc_sort_timestamp |     80.9543 |     736.429 |  655.475 |      ms |
|                                  99th percentile service time |                                    desc_sort_timestamp |     82.3793 |     746.271 |  663.892 |      ms |
|                                 100th percentile service time |                                    desc_sort_timestamp |      82.682 |     750.077 |  667.395 |      ms |

|                                  50th percentile service time |                                     asc_sort_timestamp |     4.03299 |     3.17632 | -0.85667 |      ms |
|                                  90th percentile service time |                                     asc_sort_timestamp |     4.10074 |     3.23543 | -0.86532 |      ms |
|                                  99th percentile service time |                                     asc_sort_timestamp |     4.17642 |     3.41485 | -0.76157 |      ms |
|                                 100th percentile service time |                                     asc_sort_timestamp |     4.20957 |     3.49393 | -0.71565 |      ms |
|                                                   
|                                  50th percentile service time |                         desc_sort_with_after_timestamp |     876.889 |     463.023 | -413.866 |      ms |
|                                  90th percentile service time |                         desc_sort_with_after_timestamp |     889.537 |     486.986 | -402.552 |      ms |
|                                  99th percentile service time |                         desc_sort_with_after_timestamp |     898.211 |     500.279 | -397.932 |      ms |
|                                 100th percentile service time |                         desc_sort_with_after_timestamp |     932.299 |     512.597 | -419.703 |      ms |
|                                                   
|                                  50th percentile service time |                          asc_sort_with_after_timestamp |     895.285 |     479.242 | -416.043 |      ms |
|                                  90th percentile service time |                          asc_sort_with_after_timestamp |     905.272 |     484.133 | -421.139 |      ms |
|                                  99th percentile service time |                          asc_sort_with_after_timestamp |     926.605 |      495.05 | -431.554 |      ms |
|                                 100th percentile service time |                          asc_sort_with_after_timestamp |     959.878 |     497.233 | -462.645 |      ms |
|                                                   
|                                  50th percentile service time |            desc-sort-timestamp-after-force-merge-1-seg |     1489.91 |     1146.95 | -342.962 |      ms |
|                                  90th percentile service time |            desc-sort-timestamp-after-force-merge-1-seg |     1515.51 |     1188.47 | -327.038 |      ms |
|                                  99th percentile service time |            desc-sort-timestamp-after-force-merge-1-seg |     1548.66 |     1413.39 |  -135.27 |      ms |
|                                 100th percentile service time |            desc-sort-timestamp-after-force-merge-1-seg |     1560.97 |     1520.52 |  -40.449 |      ms |
|                                                                                 
|                                  50th percentile service time |             asc-sort-timestamp-after-force-merge-1-seg |     3.77088 |     2.78592 | -0.98496 |      ms |
|                                  90th percentile service time |             asc-sort-timestamp-after-force-merge-1-seg |     3.87459 |     2.84127 | -1.03332 |      ms |
|                                  99th percentile service time |             asc-sort-timestamp-after-force-merge-1-seg |     3.99381 |     3.06374 | -0.93007 |      ms |
|                                 100th percentile service time |             asc-sort-timestamp-after-force-merge-1-seg |        4.02 |      3.1414 |  -0.8786 |      ms |
|                                                   
|                                  50th percentile service time | desc-sort-with-after-timestamp-after-force-merge-1-seg |     917.005 |     549.546 | -367.459 |      ms |
|                                  90th percentile service time | desc-sort-with-after-timestamp-after-force-merge-1-seg |     957.561 |     563.502 | -394.059 |      ms |
|                                  99th percentile service time | desc-sort-with-after-timestamp-after-force-merge-1-seg |     997.819 |     590.614 | -407.205 |      ms |
|                                 100th percentile service time | desc-sort-with-after-timestamp-after-force-merge-1-seg |     998.564 |     664.574 |  -333.99 |      ms |
|                                                   
|                                  50th percentile service time |  asc-sort-with-after-timestamp-after-force-merge-1-seg |     929.596 |     637.683 | -291.913 |      ms |
|                                  90th percentile service time |  asc-sort-with-after-timestamp-after-force-merge-1-seg |      962.94 |     655.426 | -307.513 |      ms |
|                                  99th percentile service time |  asc-sort-with-after-timestamp-after-force-merge-1-seg |     981.428 |     675.017 | -306.411 |      ms |
|                                 100th percentile service time |  asc-sort-with-after-timestamp-after-force-merge-1-seg |     1019.66 |     676.265 | -343.397 |      ms |
```

**Comment by mayya-sharipova** [comment]
Here are the benchmarks for sorted-reader:

baseline: master branch; contender: [sorted-reader branch](https://github.com/mayya-sharipova/elasticsearch/commits/sorted-reader)

```
|                                                        Metric |                           Task |    Baseline |   Contender |     Diff |   Unit |
|--------------------------------------------------------------:|-------------------------------:|------------:|------------:|---------:|-------:|
|                                  50th percentile service time |           desc_sort_population |     52.4295 |     4.69856 |  -47.731 |     ms |
|                                  90th percentile service time |           desc_sort_population |     53.9994 |     4.86827 | -49.1312 |     ms |
|                                  99th percentile service time |           desc_sort_population |     54.9973 |     5.20856 | -49.7888 |     ms |
|                                 100th percentile service time |           desc_sort_population |     55.0597 |      5.7289 | -49.3308 |     ms |

|                                  50th percentile service time |            asc_sort_population |     53.3332 |     3.22252 | -50.1106 |     ms |
|                                  90th percentile service time |            asc_sort_population |     55.0845 |     3.30176 | -51.7828 |     ms |
|                                  99th percentile service time |            asc_sort_population |     74.9326 |     3.41648 | -71.5161 |     ms |
|                                 100th percentile service time |            asc_sort_population |     78.6209 |     3.54624 | -75.0747 |     ms |
|                                                   
|                                  50th percentile service time | asc_sort_with_after_population |     76.1371 |     6.98233 | -69.1548 |     ms |
|                                  90th percentile service time | asc_sort_with_after_population |     80.8901 |     7.23916 | -73.6509 |     ms |
|                                  99th percentile service time | asc_sort_with_after_population |     97.8003 |     7.34614 | -90.4541 |     ms |
|                                 100th percentile service time | asc_sort_with_after_population |     104.533 |     7.34691 | -97.1865 |     ms |

|                                  50th percentile service time |            desc_sort_geonameid |     8.13857 |     7.19367 | -0.94491 |     ms |
|                                  90th percentile service time |            desc_sort_geonameid |     10.3497 |     7.46943 | -2.88024 |     ms |
|                                  99th percentile service time |            desc_sort_geonameid |     13.5153 |     7.68365 | -5.83167 |     ms |
|                                 100th percentile service time |            desc_sort_geonameid |     19.6222 |     7.71474 | -11.9074 |     ms |

|                                  50th percentile service time | desc_sort_with_after_geonameid |     67.1275 |     25.3947 | -41.7328 |     ms |
|                                  90th percentile service time | desc_sort_with_after_geonameid |     68.6301 |     26.9443 | -41.6858 |     ms |
|                                  99th percentile service time | desc_sort_with_after_geonameid |      69.694 |     28.2522 | -41.4417 |     ms |
|                                 100th percentile service time | desc_sort_with_after_geonameid |     69.9783 |     30.6242 | -39.3541 |     ms |

|                                  50th percentile service time |             asc_sort_geonameid |     6.21184 |     6.35076 |  0.13892 |     ms |
|                                  90th percentile service time |             asc_sort_geonameid |     6.35723 |     6.71775 |  0.36052 |     ms |
|                                  99th percentile service time |             asc_sort_geonameid |     6.62406 |     6.85819 |  0.23413 |     ms |
|                                 100th percentile service time |             asc_sort_geonameid |     6.85049 |     6.94722 |  0.09673 |     ms |

|                                  50th percentile service time |  asc_sort_with_after_geonameid |     62.5055 |     8.86973 | -53.6358 |     ms |
|                                  90th percentile service time |  asc_sort_with_after_geonameid |     64.3278 |     9.52665 | -54.8011 |     ms |
|                                  99th percentile service time |  asc_sort_with_after_geonameid |     67.5103 |     10.8724 | -56.6379 |     ms |
|                                 100th percentile service time |  asc_sort_with_after_geonameid |     67.6121 |     17.2646 | -50.3475 |     ms |
```

**Comment by jimczi** [comment]
We took another approach for this, hence closing.

**Comment by YohanSciubukgian** [comment]
@jimczi Do you have any other issue/PR to follow improvements related to this topic ?

**Comment by mayya-sharipova** [comment]
@jimczi  I am reviving this PR with merging the latest master here, can you please continue the review when you have time. 

Here are the latest benchmarks for `http_logs` dataset, provided that it is a **data stream**.
For non data streams, we expect regression  on  desc_sort_timestamp for multiple segments.

Here are the results of the 99th percentile service time.
Baseline: master branch
Contender: this PR

Surprisingly, this time I also see the regression on desc_sort_with_after_timestamp. I will investigate what could be a reason for it.


```diff
+|                                                   Task |    Baseline |   Contender |     Diff |   Unit |
+|                                    desc_sort_timestamp |     79.6757 |     66.9085 | -12.7672 |     ms |
+|                                     asc_sort_timestamp |     4.51976 |     3.58597 | -0.93378 |     ms |
-|                         desc_sort_with_after_timestamp |     748.949 |     878.057 |  129.108 |     ms |
+|                          asc_sort_with_after_timestamp |     754.128 |     459.698 |  -294.43 |     ms |
+|            desc-sort-timestamp-after-force-merge-1-seg |     1485.43 |     985.803 | -499.632 |     ms |
+|             asc-sort-timestamp-after-force-merge-1-seg |     4.17577 |     3.23124 | -0.94453 |     ms |
+| desc-sort-with-after-timestamp-after-force-merge-1-seg |     866.316 |     519.599 | -346.717 |     ms |
+|  asc-sort-with-after-timestamp-after-force-merge-1-seg |     790.108 |     604.906 | -185.202 |     ms |
```

**Review by jimczi — APPROVED** [review]
LGTM !

**Pull request merged**
