### PR TITLE
Rework beats artifacts resolution in docker build

### PR DESCRIPTION
**Pull request by breskeby**
It seems gradle behaviour has changed in 8.3 or let's say resolution logic is broken as it reports misguiding error messages as reported in https://github.com/elastic/elasticsearch/issues/100152 
This workaround fixes the exclusive group filtering by ensuring only the beats repo is tried for beats artifacts.
I couldn't reproduce the resolution issue as we see in https://github.com/elastic/elasticsearch/issues/100152 locally.
Will follow up with the gradle team on the issue.

### CODE REVIEW

**Review by mark-vieira — APPROVED** [review]
We should add the `test-release` label to this PR to validate this if we weren't able to repro locally.

**Comment by breskeby** [comment]
The release tests keep breaking but work locally and they work on a Jenkins ci image I spun up. I wonder if gradle 8.3 now keeps caching the information that the beats release versions not being available in that expected folder. I'll try some experiments around that setting those artefact to changing. We probably should do that anyhow

**Comment by mark-vieira** [comment]
I think it may not like that there are `+` characters in the "URL". It's interpreting those as spaces, even though those are legitimate parts of the checkout path.

https://gradle-enterprise.elastic.co/s/7zqtlraulqxmm/dependencies/repositories?repoToggled=W1s5XV0#focusedRepository=beats

So I think it's just looking in the wrong direction and it works for you locally because you're using a workspace directory that doesn't have `+` in the folder name. We could consider URL encoding the directory name so we replace the `+` characters or change the checkout directory of the CI job.

**Comment by breskeby** [comment]
Turns out parsing of URI strings have changed and having + in the path problematic as described above. The workaround for now is simple by passing a file object instead. Also better as more typed the better. 
I'll raise an issue with the gradle team anyhow as seems definitely like unintended behaviour

**Pull request merged**
