### PR TITLE
Fix InternalEngineTests#assertOpsOnPrimary

### LINKED ISSUE #37684: [CI] InternalEngineTests#testInternalVersioningOnPrimary failure
Occurs in the 6.x line 
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=opensuse/195/console

```
Expected: <4L>
     but: was <5L>
	at __randomizedtesting.SeedInfo.seed([E35F24F40F87E9B9:DB326DAF801E8211]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.index.engine.InternalEngineTests.assertOpsOnPrimary(InternalEngineTests.java:1908)
	at org.elasticsearch.index.engine.InternalEngineTests.testInternalVersioningOnPrimary(InternalEngineTests.java:1802)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```
Might be affected by an index refresh:

```
  1> [2019-01-22T08:33:28,902][WARN ][o.e.i.e.Engine           ] [[Thread-98]] [index][0] failed engine [refresh failed source[test]]
  1> org.apache.lucene.store.MockDirectoryWrapper$FakeIOException: null
  1> 	at org.elasticsearch.index.engine.InternalEngineTests$11.afterRefresh(InternalEngineTests.java:3782) ~[test/:?]
  1> 	at org.apache.lucene.search.ReferenceManager.notifyRefreshListenersRefreshed(ReferenceManager.java:285) ~[lucene-core-7.6.0.jar:7.6.0 719cde97f84640faa1e3525690d262946571245f - nknize - 2018-12-07 14:44:20]
  1> 	at org.apache.lucene.search.ReferenceManager.doMaybeRefresh(ReferenceManager.java:190) ~[lucene-core-7.6.0.jar:7.6.0 719cde97f84640faa1e3525690d262946571245f - nknize - 2018-12-07 14:44:20]
  1> 	at org.apache.lucene.search.ReferenceManager.maybeRefreshBlocking(ReferenceManager.java:253) ~[lucene-core-7.6.0.jar:7.6.0 719cde97f84640faa1e3525690d262946571245f - nknize - 2018-12-07 14:44:20]
  1> 	at org.elasticsearch.index.engine.InternalEngine.refresh(InternalEngine.java:1621) ~[main/:?]
  1> 	at org.elasticsearch.index.engine.InternalEngine.refresh(InternalEngine.java:1602) ~[main/:?]
  1> 	at org.elasticsearch.index.engine.InternalEngineTests.lambda$testFailEngineOnRandomIO$35(InternalEngineTests.java:3807) ~[test/:?]
  1> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
```

### PR DESCRIPTION
**Pull request by dnhatn**
The assertion `assertOpsOnPrimary` does not store seq_no and primary
term of successful deletes to the `lastOpSeqNo` and `lastOpTerm`. This
leads to failures of the subsequent CAS deletes or indexes with seq_no
and term. Moreover, this assertion trips [a translog assertion](https://github.com/elastic/elasticsearch/blob/b63f9b967c544c972ff674e22eb671b98c966c7e/server/src/main/java/org/elasticsearch/index/translog/Translog.java#L536-L541) because it
bumps the primary term of some operations but does not the primary term
of the engine.

Relates #36467
Closes #37684

### CODE REVIEW

**Comment by dnhatn** [comment]
run elasticsearch-ci/default-distro

**Review by ywelsch — APPROVED** [review]

**Review by bleskes — APPROVED** [review]
LGTM. good catch.

**Comment by dnhatn** [comment]
Thanks @ywelsch and @bleskes.

**Comment by talevy** [comment]
I do not think this was ever backported to the 6.6 branch, opened https://github.com/elastic/elasticsearch/pull/38990 to do that

**Pull request merged**
