### PR TITLE
[Docs] Remove "coming" notification

### PR DESCRIPTION
**Pull request by JVerwolf**
Removes the "coming" notifications now that the final release of 8.10.0 is cut.

### CODE REVIEW

**Review by jrodewig — APPROVED** [review]

**Comment by JVerwolf** [comment]
This fails with or without the seed, and it also fails on branch `8.10`, so this is a pre-existing bug.  However, it does not fail on main.

e.g.:
```
./gradlew ':docs:yamlRestTest' --tests "org.elasticsearch.smoketest.DocsClientYamlTestSuiteIT.test {yaml=reference/indices/shard-stores/line_150}" -Dtests.seed=A212D1FB2DD52FC4 -Dtests.locale=ru -Dtests.timezone=America/Montreal -Druntime.java=20
```
This triggers the failure by executing this test: 
https://github.com/JVerwolf/elasticsearch/blob/b5e06da143bebe9aa0ecba8a7ddddccb3be21c7c/docs/reference/indices/shard-stores.asciidoc#L149-L154

I'll run a git bisect to find the offending commit.

**Comment by JVerwolf** [comment]
git biesect output:
```
b61a2561d4f177f74216b45870ba5f8f0c993956 is the first bad commit
commit b61a2561d4f177f74216b45870ba5f8f0c993956
Author: Mark Vieira <portugee@gmail.com>
Date:   Tue Sep 12 10:07:38 2023 -0700

    Bump versions after 8.10.0 release

 .backportrc.json                                             |  4 ++--
 .buildkite/pipelines/intake.yml                              |  2 +-
 .buildkite/pipelines/periodic-packaging.yml                  | 12 ++++++------
 .buildkite/pipelines/periodic.yml                            | 12 ++++++------
 .ci/bwcVersions                                              |  2 +-
 .ci/snapshotBwcVersions                                      |  3 +--
 build-tools-internal/version.properties                      |  2 +-
 server/src/main/java/org/elasticsearch/Version.java          |  4 ++--
 .../src/main/java/org/elasticsearch/index/IndexVersion.java  |  4 ++--
 9 files changed, 22 insertions(+), 23 deletions(-)
bisect found first bad commit%
```

This is referencing this commit: https://github.com/elastic/elasticsearch/commit/b61a2561d4f177f74216b45870ba5f8f0c993956

I believe this is the commit to finalize the release.

**Comment by jrodewig** [comment]
@elasticsearchmachine update branch

**Comment by jrodewig** [comment]
@JVerwolf I'm pretty sure this is related to https://github.com/elastic/elasticsearch/pull/99495. Updating the branch should fix it. If not, I'll push another commit to fix the failing test.

**Comment by jrodewig** [comment]
@JVerwolf Checks have passed now. Sorry for causing the delay here.

**Pull request merged**
