### PR TITLE
ESQL: Added Median and MedianAbsoluteDeviation aggregations tests and kibana docs

### PR DESCRIPTION
**Pull request by ivancea**

### CODE REVIEW

**Review by nik9000 — APPROVED** [review]

**Comment by nik9000** [comment]
Hmmmm.... Maybe we're duplicating something.
image

**Review by not-napoleon — APPROVED** [review]
LGTM

**Comment by ivancea** [comment]
> Hmmmm.... Maybe we're duplicating something. image

@nik9000 Yeah, not sure about that one. Happens in multiple aggs (That screenshot is from the old docs), so for now I did the same for them all: Move the warning part to the "appendix" (At the end).

I'm not sure it's duplicated tho, as one talks about approximation and the other about determinism. We could merge them in the notes, or move both to a warning. As I don't have a strong opinion about which one, I just kept them that way for now (?)

**Comment by nik9000** [comment]
I think we should probably try for one WARNING. Something like "MAD is approximate and non-deterministic."

**Pull request merged**
