### PR TITLE
Always fork to the generic threadpool for _msearch requests

### LINKED ISSUE #109447: Consider forking to generic tp for every msearch request
### Elasticsearch Version

8.15

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

_any_

### Problem Description

It has been observed when running many parallel searches via _msearch, we can potentially tie up transport threads. 

The logic is that if we forked the request to a different thread pool, we can simply recurse the request. However, if there is anything semi-expensive at all, and the node is under duress, we can make things worse by tying up a transport thread. 

We should consider always forking to the generic thread pool instead of recursing on the response thread.

### Steps to Reproduce

_na_

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by benwtrent**
closes: https://github.com/elastic/elasticsearch/issues/109447

### CODE REVIEW

**Review by john-wagster — APPROVED** [review]
Makes sense to me and all looks good.

**Review by original-brownbear — COMMENTED** [review]
Could we hold off on this? I think https://github.com/elastic/elasticsearch/pull/109497 if we were to go with it would resolve this issue in a much cleaner way.
Forking to GENERIC is troublesome here as explained in Slack. Heavily concurrent msearch requests have the potential of overloading a node among other concerns.

**Comment by benwtrent** [comment]
@original-brownbear I agree on https://github.com/elastic/elasticsearch/pull/109497 being potentially the main way to do this. 

I can wait until we figure that other PR out and I can close this one if we end up fixing all the search transport thread issues :)

**Comment by benwtrent** [comment]
I am closing in deference to https://github.com/elastic/elasticsearch/pull/109497 as the transport search action should just do things correctly.

**Pull request closed without merging**
