### PR TITLE
[DOCS] Updates Elasticsearch monitoring tasks

### PR DESCRIPTION
**Pull request by lcawl**
Related to https://github.com/elastic/stack-docs/issues/86 and https://github.com/elastic/elasticsearch/pull/34369

This PR updates the monitoring configuration tasks in the Elasticsearch Reference to include the usage of Metricbeat.

### CODE REVIEW

**Comment by lcawl** [comment]
On second thought, @ycombinator should the architecture diagram be something more like this (i.e. reflecting the recommendation that Metricbeat exist on each node)?:
es-nodes-metricbeat

**Comment by ycombinator** [comment]
@lcawl I like where you are going with the new diagram, but unfortunately it has raised more questions than answers for me about how to interpret some of the symbols in these diagrams.

My interpretation/assumptions:

* The outermost boxes represent Elasticsearch clusters. The one on the left is the Production cluster and the one on the right is the Monitoring cluster.

* The horizontal rectangular boxes inside the cluster boxes represent Elasticsearch nodes. Since a cluster can contain multiple nodes, I imagine the stacking of the boxes represents multiple nodes. If this assumption is correct, then I wonder what the two stacks were meant to represent in the Production Cluster box, even in the original diagrams before Metricbeat entered this world.

* Finally, since an Elasticsearch node is a running JVM process, I don't know if it makes sense to show a Metricbeat box _inside_ an Elasticsearch node box. I think it should be shown along side it, as its peer (since Metricbeat will also be a process).

--

If I may, here is an alternative layout proposal:

* Keep the outermost cluster boxes as-is.

* Remove the stacking of the node boxes.

* Within a cluster box, show 3 un-stacked node boxes, laid out vertically, with ellipses in between the 2nd and 3rd boxes to indicate an arbitrary number of nodes.

* In the Production cluster diagram, right next to each node box, show a Metricbeat box with a "read metrics" or simply "metrics" arrow going from the node box to the metricbeat box.

WDYT?

**Comment by lcawl** [comment]
Thanks @ycombinator.  I did another mock-up here:
monitoring-elasticsearch
If it's a clearer representation, I'll clean it up.

**Comment by lcawl** [comment]
You can preview the updated information here: https://doc-review-63bf6.firebaseapp.com/es3/configuring-metricbeat.html

**Review by ycombinator — APPROVED** [review]
Changes in PR LGTM.

**Comment by lcawl** [comment]
Verified that gradle checks complete successfully.

**Pull request merged**
