### PR TITLE
Add basic documentation for Searchable Snapshots REST APIs

### PR DESCRIPTION
**Pull request by tlrx**
This pull request adds basic documentation for the searchable snapshots REST APIs. The main motivations are to not break downstream projects (see #53871) and to provide a simple example of how to mount a snapshot.

It adds a new "Searchable Snapshots APIs" sub section in the REST APIs section. The "Mount Snapshot API" is the more complete documentation and provides an example of how to create a new index backed by a snapshot. 

Those API are experimental and marked as such. I've not seen any mention of the license, except the `[testenv="basic"] ` tags that I copied from other doc.

### CODE REVIEW

**Comment by DaveCTurner** [comment]
@elasticmachine please run elasticsearch-ci/docs

(the build logs are gone, I can't work out how to see the preview)

**Review by DaveCTurner — APPROVED** [review]
Looks OK as far as I can see; I don't understand why I can't see a preview of these docs from CI however, so we may need to follow up once the docs become properly available.

**Comment by tlrx** [comment]
@elasticmachine update branch

**Comment by tlrx** [comment]
Thanks David!

> I don't understand why I can't see a preview of these docs from CI

I did not know that CI was exposing a preview of the docs. I built the docs locally and ran the docs tests, but there's always a room for breaking doc after that :)

**Pull request merged**
