### PR TITLE
Remove groovy sandbox

### LINKED ISSUE #10156: What should we do with groovy sandboxing?
Our groovy engine supports sandboxing, which can be enabled/disabled through settings. Sandboxing was disabled by default from `1.4.3` on though since we found out that it could be worked around (see also https://www.elastic.co/blog/running-groovy-scripts-without-dynamic-scripting).

At this point I wonder if it makes sense to maintain the sandboxing that we currently have, as we know it's not effective. I would vote for just stating that groovy is not sandboxed and remove all the sandboxing shenanigans from master (2.0), unless we have a better idea for safe sandboxing... especially once we got #10116 in.

Thoughts?

### PR DESCRIPTION
**Pull request by javanna**
Closes #10156

### CODE REVIEW

**Comment by javanna** [comment]
@dakrone can you have a look please?

**Comment by dakrone** [comment]
@javanna there are still a lot of references to the sandbox in `docs/reference/modules/scripting.asciidoc` (near the beginning of the file)

Code-wise this looks good to me

**Comment by javanna** [comment]
> there are still a lot of references to the sandbox in docs/reference/modules/scripting.asciidoc (near the beginning of the file)
@dakrone I left those references on purpose at the beginning of the file, I thought we wanted to have the security alert on all branches. It mentions explicitly the versions that are vulnerable that require to turn off the sandbox.

@clintongormley shall we remove this part from the scripting docs on master?

**Comment by clintongormley** [comment]
@javanna I'd remove that section from the scripting page and add a note to the migration page.

**Comment by javanna** [comment]
@clintongormley I left the dyanmic scripts note aat the beginning of the page, but removed references to groovy sandbox and settings. I had already added a note to the migration page, is that not enough?

**Comment by clintongormley** [comment]
LGTM

**Pull request closed without merging**
