### PR TITLE
Update tests to reflect recent IndexOrDocValuesQuery#toString changes

### PR DESCRIPTION
**Pull request by javanna**
Relates to https://github.com/apache/lucene/pull/12791

### CODE REVIEW

**Review by benwtrent — APPROVED** [review]
:shipit:

**Comment by javanna** [comment]
run elasticsearch-ci

**Comment by benwtrent** [comment]
jenkins retest this please

**Comment by javanna** [comment]
I think that CI is driving me crazy :) I will approve yours.

**Pull request closed without merging**
