### PR TITLE
Deprecate single-tier allocation filtering settings

### PR DESCRIPTION
**Pull request by masseyke**
Adding deprecation info API checks for the following properties that were removed in 8.0:
cluster.routing.allocation.require._tier
cluster.routing.allocation.include._tie;
cluster.routing.allocation.exclude._tier
index.routing.allocation.require._tier
index.routing.allocation.include._tier
index.routing.allocation.exclude._tier

### CODE REVIEW

**Comment by masseyke** [comment]
@elasticmachine run elasticsearch-ci/part-2

**Comment by masseyke** [comment]
@elasticmachine run elasticsearch-ci/packaging-tests-unix-sample

**Review by jbaiera — CHANGES_REQUESTED** [review]

**Review by jbaiera — APPROVED** [review]
LGTM once the documentation links are fixed in `IndexDeprecationChecks`. 

Thanks @masseyke!

**Comment by masseyke** [comment]
@elasticmachine update branch

**Pull request merged**
