### PR TITLE
Update zen.asciidoc to say discovery.fd settings require restart

### PR DESCRIPTION
**Pull request by tomryanx**
Took me a while to figure this out for myself, as it wasn't mentioned explicitly.

### CODE REVIEW

**Comment by jasontedor** [comment]
This is true for any non-dynamic setting. If you try to set this setting dynamically you'll run into a message that says the setting is not dynamically updatable. Can you tell us a little more about the trouble that you ran into?

**Comment by tomryanx** [comment]
eg:

    curl -sXPUT localhost:9200/_cluster/settings -d '{
    "transient:{"discovery.zen.fd.ping_retries":10}
    }'
    {"acknowledged":true,"persistent":{},"transient":{}}

I got @warkolm's attention on irc - he suggested it was usually clearly documented (whether a setting was dynamic or not) and that I should probably raise an issue or PR if it wasn't. I didn't think about the broader style or whether it's helpful to handhold with every static setting - ignore me if it's not :construction_worker_man:

**Comment by jasontedor** [comment]
What version of Elasticsearch is this? That should fail with

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "transient setting [discovery.zen.fd.ping_retries], not dynamically updateable"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "transient setting [discovery.zen.fd.ping_retries], not dynamically updateable"
  },
  "status" : 400
}
```

> I got @warkolm's attention on irc - he suggested it was usually clearly documented (whether a setting was dynamic or not) and that I should probably raise an issue or PR if it wasn't. I didn't think about the broader style or whether it's helpful to handhold with every static setting - ignore me if it's not 👷

The convention is to say if a setting is dynamic, and if not, it's static.

My concern here is that the software is not giving you the correct guidance though, because it should, and that's what needs to figured out here.

**Comment by tomryanx** [comment]
This was on 2.4.4 - I've just tried it on our newer 5.3.0 cluster and I get a helpful

    "reason":"transient setting [discovery.zen.fd.ping_retries], not dynamically updateable"

Therefore closing, apologies for the noise!

**Comment by jasontedor** [comment]
> Therefore closing, apologies for the noise!

No apologies necessary at all!

**Pull request closed without merging**
