### PR TITLE
Handle NULL arithmetic operations with INTERVALs

### LINKED ISSUE #49297: SQL: multiply operation between INTERVALs and NULL is not possible
`SELECT NULL * INTERVAL 1 DAY` results in:

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "verification_exception",
        "reason" : "Found 1 problem(s)\nline 1:8: [*] has arguments with incompatible types [NULL] and [INTERVAL_DAY]"
      }
    ],
    "type" : "verification_exception",
    "reason" : "Found 1 problem(s)\nline 1:8: [*] has arguments with incompatible types [NULL] and [INTERVAL_DAY]"
  },
  "status" : 400
}
```

### PR DESCRIPTION
**Pull request by astefan**
Up until this change, NULL (as a data type) was not permitted in *, +, - operations involving intervals, an error message being generated.

Fixes https://github.com/elastic/elasticsearch/issues/49297.

### CODE REVIEW

**Review by matriv — APPROVED** [review]
LGTM. Minor suggestion: Combine all null +/-/* interval in one query in integ tests.
Maybe two queries one for null on the left side one on the right, or maybe even 3 queries
each testing one operator.

**Comment by matriv** [comment]
@astefan thx! Adding the numeric-null operations will catch any future bugs in that area.

**Review by costin — APPROVED** [review]
LGTM - do the other operators handle Null accordingly?
I wonder if going forward we could generalize this a bit since all operators would have to take into account null so maybe instead of checking explictly for null, we can do the check in the base `TypeResolver` base class and act accordingly so children would only have to worry about actual values.

**Comment by astefan** [comment]
@costin the other operators seem to handle NULL properly. There is a test I added for all the math operators with NULL combinations here https://github.com/elastic/elasticsearch/pull/49633/files#diff-c579a8eae7dda4bd86f6ce71c5bc0c36R24.

**Pull request merged**
