### PR TITLE
aggregate metric double add a  max min validation

### PR DESCRIPTION
**Pull request by weizijun**
aggregate metric double add a  max min validation, to check if min value is greater than max value.

### CODE REVIEW

**Review by csoulios — APPROVED** [review]

**Comment by csoulios** [comment]
@elasticmachine ok to test

**Review by csoulios — COMMENTED** [review]
@weizijun thanks for this PR. Can you please merge the conflicts and update the changelog

**Comment by weizijun** [comment]
> @weizijun thanks for this PR. Can you please merge the conflicts and update the changelog

done!

**Review by csoulios — APPROVED** [review]
LGTM!

**Pull request merged**
