### PR TITLE
Warn when searching a frozen index.

### PR DESCRIPTION
**Pull request by martijnvg**
The coordinating node should warn when a search request
is targeting a frozen index.

Relates to #70192

### CODE REVIEW

**Review by danhermann — APPROVED** [review]
LGTM

**Review by dakrone — APPROVED** [review]
LGTM also!

**Comment by martijnvg** [comment]
Thanks for checking @dakrone and @danhermann!

**Comment by martijnvg** [comment]
@elasticmachine update branch

**Pull request merged**
