### PR TITLE
Force property expansion for security policy

### PR DESCRIPTION
**Pull request by rjernst**
When resolving the security policy files for server and components of
Elasticsearch, each jar file location is put into a special system
property value so that policy files may contain codeBase specific
grants. The mechanism for substituting system properties is part of the
JDK's policy parser. However, a security property exists,
policy.expandProperties, which controls whether properties will actually
be expanded. If a user ends up setting this, Elasticsearch will fail to
start.

This commit forces the value of the security property to ensure the
policy files can always be parsed correctly.

### CODE REVIEW

**Review by ChrisHegarty — COMMENTED** [review]
The source code changes look good to me. Are the doc changes accidentally or a bad merge?

**Comment by rjernst** [comment]
Not sure why those docs changes were showing up. I synced master and it seems to be ok now.

**Review by ChrisHegarty — APPROVED** [review]
LGTM

**Review by grcevski — APPROVED** [review]
LGTM!

**Pull request merged**
