### PR TITLE
gradle cleanEclipse should completely nuke .settings.

### PR DESCRIPTION
**Pull request by rmuir**
Today this will only remove `.settings/org.eclipse.jdt.core.prefs`,
leaving a bunch of stale eclipse configuration everywhere.

### CODE REVIEW

**Comment by rmuir** [comment]
@jpountz can you look at this, as it will remove your configuration here (https://github.com/elastic/elasticsearch/commit/1954f770a1415c4ac2cc2f679ab3b68a3c4778d7).

I think we should generate them from the build consistently. I know this will temporarily make things worse (since we havent yet added this to gradle), but today its confusing.

**Comment by jpountz** [comment]
I don't mind merging this fix temporarily until we can get gradle to re-generate those files when running 'gradle eclipse'.

**Comment by rmuir** [comment]
Lemme take a stab at doing the copy in this PR as well.

**Comment by jpountz** [comment]
I can at least confirm that generating the config and importing into eclipse still works fine with this parth.

**Comment by rmuir** [comment]
@jpountz can you try with my latest commit? it adds all the previous settings from the maven build, so it should properly setup source code formatting, 4-space indent, all that stuff.

**Comment by jpountz** [comment]
:+1: I tried the change, and everything looked fine (license headers, indentation).

**Comment by rmuir** [comment]
thanks for testing.

**Pull request merged**
