### PR TITLE
Add {} to ifs in org.apache.lucene

### PR DESCRIPTION
**Pull request by nik9000**

### CODE REVIEW

**Comment by jasontedor** [comment]
I'm fine either way but I wonder why not just make all of these:

```java
if (clauses.size() == 0) return null;
```

**Comment by nik9000** [comment]
Habit. I'll pick it up in the morning and make them the short way.

**Comment by danielmitterdorfer** [comment]
I wonder why not use `if clauses.isEmpty())` instead? I think it is easier to read and describes the intention better.

**Comment by jasontedor** [comment]
I'm fine with not changing it in a formatting PR.

**Comment by nik9000** [comment]
Thanks for looking @jasontedor and @danielmitterdorfer! I did switch it to isEmpty() on a single line.

**Pull request merged**
