### PR TITLE
[ML] Remove model snapshot legacy doc ids

### PR DESCRIPTION
**Pull request by dimitris-athanasiou**
Removes methods that were no longer used regarding version 5.4 doc ids of `ModelState`.

Also adds clean up of 5.4 model state and quantile docs in the daily maintenance.

### CODE REVIEW

**Comment by droberts195** [comment]
We have never done anything to force users to delete jobs they created in 5.4, so I think documents with these IDs _could_ still exist in the index if users still have old jobs left over from 5.4.  Having said that, we don't let people open 5.4 jobs, so there isn't any need to keep the state.  We could just unconditionally delete state documents for 5.4 jobs in our nightly maintenance.

**Comment by droberts195** [comment]
Just looking at this again, I see the method literally wasn't used.  That means we've had a bug for a long time that if someone deletes a 5.4 job then we don't delete its state documents.  So there will be users who have these orphaned 5.4 state documents in their state indices.  We could clean up current and future cases by deleting all 5.4 state documents during the nightly maintenance.

**Comment by dimitris-athanasiou** [comment]
@elasticmachine  update branch

**Comment by dimitris-athanasiou** [comment]
@elasticmachine update branch

**Review by droberts195 — APPROVED** [review]
LGTM

**Pull request merged**
