### PR TITLE
Bump minimum compiler version to Java 16

### PR DESCRIPTION
**Pull request by mark-vieira**
Now that we've upgrade to Gradle 7.0 we can bump the minimum compiler version to Java 16 to be in line with the bundled JDK and put us back on a supported version (Java 15 is EOL).

I've also relaxed the JDK requirement for builds run via IntelliJ. The idea here being that the JDK is set by the build, but the build in turn requires a certain JDK. To avoid this awkward chicken/egg situation we just ignore the requirement when running in the IDE. We still fail on the CLI in these scenarios though.

### CODE REVIEW

**Comment by mark-vieira** [comment]
Gonna need to get https://github.com/elastic/infra/pull/28480 merged in first since we only have Java 16 on our Linux workers.

**Review by pugnascotia — APPROVED** [review]

**Review by breskeby — APPROVED** [review]
yay 👍

**Comment by mark-vieira** [comment]
@elasticmachine update branch

**Comment by mark-vieira** [comment]
I think this might also be blocked on the release of 6.2.0 of the Gradle shadow plugin.

https://github.com/johnrengelman/shadow/issues/658

**Comment by mark-vieira** [comment]
Windows builds are failing due to the lack of JDK 16 on the agents. The ansible playbooks have been updated but there's another issue blocking the new images being build. Have an issue open with infra for this.

**Comment by mark-vieira** [comment]
@elasticmachine update branch

**Comment by mark-vieira** [comment]
@elasticmachine update branch

**Pull request merged**
