### PR TITLE
Add version 6.6.1 (6.6.0 released)

### PR DESCRIPTION
**Pull request by matriv**

### CODE REVIEW

**Comment by matriv** [comment]
@elasticmachine run elasticsearch-ci/1 
@elasticmachine run elasticsearch-ci/2
@elasticmachine run elasticsearch-ci/default-distro

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by matriv** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by matriv** [comment]
@elasticmachine run elasticsearch-ci/1
@elasticmachine run elasticsearch-ci/2
@elasticmachine run elasticsearch-ci/default-distro

**Comment by matriv** [comment]
@elasticmachine run elasticsearch-ci/1
@elasticmachine run elasticsearch-ci/2
@elasticmachine run elasticsearch-ci/default-distro

**Comment by matriv** [comment]
@elasticmachine run elasticsearch-ci/oss-distro-docs

**Comment by matriv** [comment]
The merged commit is empty as I missed that it was already cherry-picked here: 313fef6c4b1c6d0468957fd82f60061bc8add111

**Pull request merged**
