### PR TITLE
Switch AggregationSpec to ContextParser

### PR DESCRIPTION
**Pull request by nik9000**
We seem to have settled on the `ContextParser` interface for parsing
stuff, mostly because `ObjectParser` implements it. We don't really
*need* the old `Aggregator.Parser` interface any more because it
duplicates `ContextParser` but with the arguments reversed.

This adds support to `AggregationSpec` to declare aggregation parsers
using `ContextParser`. This should integrate cleanly with
`ObjectParser`. It doesn't drop support for `Aggregator.Parser` or
change the plugin interface at all so it *should* be safe to backport to
7.x. And we can remove `Aggregator.Parser` in a follow up which is only
targeted to 8.0.

### CODE REVIEW

**Comment by nik9000** [comment]
woops that looks like it upset the compiler.

**Review by polyfractal — APPROVED** [review]
LGTM.  

@not-napoleon I don't think this affects or will-affect any of the VS refactor work, but since it's touching agg registration I thought I'd ping you just as an FYI.

**Comment by nik9000** [comment]
@not-napoleon would you prefer that I hold off on merging this?

**Comment by not-napoleon** [comment]
Thanks for asking, but there's no reason I can see to hold off merging this for the values source stuff.  I have a couple of changes in `SearchModule`, but it should still be a trivial merge for me.

**Comment by nik9000** [comment]
:heart:

**Pull request merged**
