### PR TITLE
Add positive_score_impact to rank_features type

### LINKED ISSUE #68619: positive_score_impact does not work with rank_features field
So the `rank_feature` field has a `positive_score_impact` parameter to make it have a negative correlation with the score. However, this parameter does not work on `rank_features` fields.
When I try it, I get the following error: `unknown parameter [positive_score_impact] on mapper [rank_features] of type [rank_features]`

### PR DESCRIPTION
**Pull request by mayya-sharipova**
rank_features field type misses positive_score_impact parameter
that rank_feature type has. This adds this parameter.

Closes #68619

### CODE REVIEW

**Comment by mayya-sharipova** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Review by cbuescher — APPROVED** [review]
Looks pretty similar to what `rank_feature`does, nice to get some insight how this is working. LGTM

**Comment by jpountz** [comment]
I had left it out on purpose on the first release of `rank_features` because my mental model is that `rank_features` is about sparse features. In that situation, `positive_score_impact:false` doesn't work well because it would contribute a higher score to a document that has the feature than to a document that doesn't have the feature, which feels a bit counter-intuitive? The example works around this problem by setting the same features on all documents but if this is something that is possible, I wonder if users wouldn't naturally go to `rank_feature` instead?

**Comment by mayya-sharipova** [comment]
@jpountz Thank you for the feedback, it makes sense, but it looks to me this should be clarified in the documentation.

>  by setting the same features on all documents but if this is something that is possible, I wonder if users wouldn't naturally go to rank_feature instead

But for the `rank_feature` field type as well, we don't enforce that all documents have this field. And similarly, if this field is used in the`rank_feature` query as a part of `should` bool query,  a doc that has this feature will have a higher score than a doc that doesn't have.

**Comment by jpountz** [comment]
+1 to clarify the documentation and recommend that `rank_feature` fields have a value for every document when `positive_score_impact` is set to `false`.

**Pull request merged**
