### PR TITLE
Watcher: Fix check for currently executed watches

### PR DESCRIPTION
**Pull request by spinscale**
The ack watch action has a check for currently executed watches, to make
sure that currently running watches cannot be acknowledged. This check
only checked on the coordinating node for watches being executed, but should
have checked the whole cluster using a WatcherStatsRequest, which is
being switched to in this commit.

### CODE REVIEW

**Review by hub-cap — APPROVED** [review]
good catch. My only nit would be to change the `anyMatch`'s to `noneMatch` and change the conditional to a positive case conditional (`noWatchRunning`) instead of a negative case, to move the bulk of the code that triggers the negative branch in that if statement `if (isWatchRunning)` into the top of the statement, and have a `else { listener.onFailure... }`. But this code does what is advertised so i will let you decide.

**Comment by spinscale** [comment]
`anyMatch()` would exit early compared to `noneMatch`, this is why I went this way.

**Comment by hub-cap** [comment]
fair, :shipit:

**Comment by spinscale** [comment]
@elasticmachine retest this please

**Pull request merged**
