### PR TITLE
Fix document field generation for vnd_cbor and vnd_smile

### LINKED ISSUE #67009: GetResultsTests#testToAndFromXContentEmbedded fails reproducibly
**Build scan**:

Not available, only seen locally.

**Repro line**:

```./gradlew :server:test --tests "org.elasticsearch.index.get.GetResultTests.testToAndFromXContentEmbedded" -Dtests.seed=3205E115CC20EB17 -Dtests.locale=pl-PL -Dtests.timezone=EST -Druntime.java=14```

**Reproduces locally?**:

Yes, 100%.

**Applicable branches**:

`master` (a904c7014ebcaeecc0305c956d38a53c46808da5)

**Failure history**:

Not seen in CI

**Failure excerpt**:

```
org.elasticsearch.index.get.GetResultTests > testToAndFromXContentEmbedded FAILED
    java.lang.AssertionError: expected: org.elasticsearch.index.get.GetResult<{
      "_index" : null,
      "_id" : null,
      "_seq_no" : 6646957961986097284,
      "_primary_term" : 7,
      "_routing" : "zEne",
      "found" : true,
      "_source" : {
        "lARIVmJe" : -8033289809137462302,
        "gjHzQtFcg" : [
          {
            "gffbiDUCb" : "HSoJwgpi",
            "sIBprepwOS" : 0.4510828074110138,
            "LDaaGAMJEW" : "dsZUiS",
            "VhULAmxZo" : 0.24047737661153457,
            "cQMWfNK" : "WQIzxlgRO"
          }
        ]
      },
      "fields" : {
        "ogBeX" : [
          {
            "wMFIY" : true,
            "Aglsj" : "KzFHPZmZed",
            "JjSfA" : 2022698992
          }
        ],
        "HnuSo" : [
          [
            -994235075
          ]
        ],
        "GCVqkHMBYi" : [
          -9,
          57,
          37,
          -87
        ],
        "KroFx" : [
          [
            -1732302012,
            -1883312517,
            -1367228499
          ],
          [
            921807463
          ],
          [
            -1791885005,
            1461412019
          ]
        ],
        "TByBh" : [
          0.86527264,
          0.8043281
        ]
      }
    }> but was: org.elasticsearch.index.get.GetResult<{
      "_index" : null,
      "_id" : null,
      "_seq_no" : 6646957961986097284,
      "_primary_term" : 7,
      "_routing" : "zEne",
      "found" : true,
      "_source" : {
        "lARIVmJe" : -8033289809137462302,
        "gjHzQtFcg" : [
          {
            "gffbiDUCb" : "HSoJwgpi",
            "sIBprepwOS" : 0.4510828074110138,
            "LDaaGAMJEW" : "dsZUiS",
            "VhULAmxZo" : 0.24047737661153457,
            "cQMWfNK" : "WQIzxlgRO"
          }
        ]
      },
      "fields" : {
        "ogBeX" : [
          {
            "wMFIY" : true,
            "Aglsj" : "KzFHPZmZed",
            "JjSfA" : 2022698992
          }
        ],
        "HnuSo" : [
          [
            -994235075
          ]
        ],
        "GCVqkHMBYi" : [
          -9,
          57,
          37,
          -87
        ],
        "KroFx" : [
          [
            -1732302012,
            -1883312517,
            -1367228499
          ],
          [
            921807463
          ],
          [
            -1791885005,
            1461412019
          ]
        ],
        "TByBh" : [
          0.86527264,
          0.8043281
        ]
      }
    }>
        at __randomizedtesting.SeedInfo.seed([3205E115CC20EB17:626C2A5B9F6A3F6F]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at org.elasticsearch.index.get.GetResultTests.testToAndFromXContentEmbedded(GetResultTests.java:120)
```

In case it's not obvious, `0.86527264` is a `Float` in one object and a `Double` in the other 😬 .

Test was added for the HLRC in #22586 so I'm labelling this to match.

### LINKED ISSUE #67018: [CI] DocumentFieldTests.testToAndFromXContent fails reproducibly on master
**Build scan**:
https://gradle-enterprise.elastic.co/s/okfzo7ptu7dpu

**Repro line**:
```
./gradlew ':server:test' --tests "org.elasticsearch.index.get.DocumentFieldTests.testToAndFromXContent" -Dtests.seed=F175C551A1255CE3 -Dtests.security.manager=true -Dtests.locale=mk-MK -Dtests.timezone=Mexico/BajaNorte -Druntime.java=11
```

**Reproduces locally?**:
Yep!

**Applicable branches**:
Master

**Failure history**:
This was a local failure while working on different work

**Failure excerpt**:

```
org.elasticsearch.index.get.DocumentFieldTests > testToAndFromXContent FAILED
    java.lang.AssertionError: expected: org.elasticsearch.common.document.DocumentField<DocumentField{name='nTVya', values=[0.69425505, 0.79453, 0.9221062, 0.24998319, 0.9083719]}> but was: org.elasticsearch.common.document.DocumentField<DocumentField{name='nTVya', values=[0.69425505, 0.79453, 0.9221062, 0.24998319, 0.9083719]}>
        at __randomizedtesting.SeedInfo.seed([F175C551A1255CE3:DF5C6FDBC35A271F]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:144)
        at org.elasticsearch.index.get.DocumentFieldTests.testToAndFromXContent(DocumentFieldTests.java:77)
```

### PR DESCRIPTION
**Pull request by pgomulka**
there is a special case for creating expected value for Floats when
xcontentType is CBOR or SMILE

closes #67009
closes #67018

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Review by DaveCTurner — CHANGES_REQUESTED** [review]
Would you unmute the test I muted too? See https://github.com/elastic/elasticsearch/commit/a0c090a2afacd271fd8388aad2d5f338f7f97a4b.

**Review by dakrone — APPROVED** [review]
LGTM (with un-muting comment as David mentioned)

**Review by DaveCTurner — APPROVED** [review]
LGTM2 (empirically at least, I've no idea why this fixes anything but can confirm that it does)

**Comment by pgomulka** [comment]
@DaveCTurner 
the problem was with random test data generation. Looks like there is a special logic to handle Float data types for cbor and smile. Previously we only had one `XcontentType` (i.e. `XContentType.CBOR`) per each `XContent` (i.e. `CborXContent`)
Now we also have versioned XContentTypes (think of this as an allowed media type) like `VND_CBOR` - `application/vnd.elasticsearch+cbor`. This also uses `CborXContent` so should be included into this conditional test data generation logic.
Let me know if this clarifies a little

**Pull request merged**
