### PR TITLE
Bundle TestShardRouting in test jar

### LINKED ISSUE #14133: Elasticsearch should bundle TestShardRouting in its test jar
`TestShardRouting` is a test utility for building `ShardRouting`, part of the routing state and plugins want to use it to run their tests.

### PR DESCRIPTION
**Pull request by nik9000**
Plugins want to use this too.

Closes #14133

### CODE REVIEW

**Comment by nik9000** [comment]
@rjernst, if this is merged here it'll need reflecting in the burn_maven_with_fire branch so... want to review it in both places?

**Comment by nik9000** [comment]
BTW - I think that its weird that we have such intense rules around what we package in our test jar but I think that is a more fundamental issue. IIRC you've got it rigged differently in gradle so this might not be an issue at all there?

**Comment by s1monw** [comment]
LGTM

**Comment by nik9000** [comment]
Merged to master and backported to 2.x and 2.1.

**Pull request merged**
