### PR TITLE
Fix a downsample persistent task assignment bug

### PR DESCRIPTION
**Pull request by martijnvg**
If as part of the persistent task assignment the source downsample index no longer exists, then the persistent task framework will continuously try to find an assignment and fail with IndexNotFoundException (which gets logged as a warning on elected master node).

This fixes a bug in resolving the shard routing, so that if the index no longer exists any node is returned and the persistent task can fail gracefully at a later stage.

The original fix via #98769 didn't get this part right.

### CODE REVIEW

**Review by kkrik-es — APPROVED** [review]

**Comment by martijnvg** [comment]
Failure looks unrelated. Starting the upgraded node failed in rolling upgrade integration tests: 


```
[2024-03-12T16:16:18,173][ERROR][o.e.b.Elasticsearch      ] [v8.13.0-0] fatal exception while booting Elasticsearch java.lang.IllegalStateException: failed to obtain node locks, tried [/dev/shm/bk/bk-agent-prod-gcp-1710258034806935985/elastic/elasticsearch-pull-request/x-pack/qa/rolling-upgrade/build/testclusters/v8.13.0-0/data]; maybe these locations are not writable or multiple nodes were started on the same data path?
--
  | »       at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:293)
  | »       at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.node.NodeConstruction.validateSettings(NodeConstruction.java:504)
  | »       at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.node.NodeConstruction.prepareConstruction(NodeConstruction.java:255)
  | »       at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.node.Node.<init>(Node.java:192)
  | »       at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.bootstrap.Elasticsearch$2.<init>(Elasticsearch.java:240)
  | »       at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.bootstrap.Elasticsearch.initPhase3(Elasticsearch.java:240)
  | »       at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:75)
  | »  Caused by: org.apache.lucene.store.LockObtainFailedException: Lock held by another program: /dev/shm/bk/bk-agent-prod-gcp-1710258034806935985/elastic/elasticsearch-pull-request/x-pack/qa/rolling-upgrade/build/testclusters/v8.13.0-0/data/node.lock
  | »       at org.apache.lucene.core@9.10.0/org.apache.lucene.store.NativeFSLockFactory.obtainFSLock(NativeFSLockFactory.java:117)
  | »       at org.apache.lucene.core@9.10.0/org.apache.lucene.store.FSLockFactory.obtainLock(FSLockFactory.java:43)
  | »       at org.apache.lucene.core@9.10.0/org.apache.lucene.store.BaseDirectory.obtainLock(BaseDirectory.java:44)
  | »       at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.env.NodeEnvironment$NodeLock.<init>(NodeEnvironment.java:231)
  | »       at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.env.NodeEnvironment$NodeLock.<init>(NodeEnvironment.java:206)
  | »       at org.elasticsearch.server@8.14.0-SNAPSHOT/org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:285)
  | »       ... 6 more

****
```

**Comment by martijnvg** [comment]
@elasticmachine run elasticsearch-ci

**Comment by martijnvg** [comment]
@elasticmachine run elasticsearch-ci/bwc-snapshots

**Comment by martijnvg** [comment]
@elasticmachine run elasticsearch-ci/8.13.0 / bwc-snapshots

**Pull request merged**
