### PR TITLE
add ipv6 field support

### LINKED ISSUE #3714: Support for IPv6 mapping type
Currently I can't use the ip mapping type as I have fields that can be either IPv4 or IPv6. However, being able to use range queries is really useful but I can't make use of them because I have to treat the field as a string to handle the case when the field contains an IPv6 value.

Obviously this causes extra hassle as storage would then require 128 bits and when searching, range queries using IPv6 addresses shouldn't match IPv4 addresses, unless you're using the ::ffff:d.d.d.d notation, and IPv6 addresses shouldn't match IPv4 range queries at all.

(I found [this thread](http://elasticsearch-users.115913.n3.nabble.com/Support-for-first-class-IPv6-address-type-td3960748.html) when this has been raised previously)

### PR DESCRIPTION
**Pull request by kzwang**
What I've done is copied the `NumericTokenStream`, `NumericRangeFilter`, `NumericRangeQuery` and `NumericUtils` from lucene and change those to support `BigInteger`

the term query and range query/filter are both working, but there are still other things like field data need to do

@kimchy @jpountz @dadoonet can you have a quick look just to make sure I've done the correct thing so far?

closes #3714

### CODE REVIEW

**Comment by vvaradhan** [comment]
@jrideout https://issues.apache.org/jira/browse/LUCENE-5879 got fixed recently in trunk and 5.2 of Lucene.  Is it possible to provide an update now for ipv6 support in ip field type?

**Comment by clintongormley** [comment]
@vvaradhan Auto-prefixed terms in Lucene has been exposed as an experimental postings format, so it's not safe for us to use until the feature makes it to the default postings format (which is backward compatible)

**Comment by mikemccand** [comment]
I think we could alternatively use the new (just released in Lucene 5.3.0) NumericRangeTree to implement this?

See https://github.com/elastic/elasticsearch/pull/5683#issuecomment-136890281 for some ideas on how it would work for BigInteger/Decimal ... I think the basic idea would be similar: any value that can be converted into a "same sort order" byte[] should work.

**Comment by uschindler** [comment]
Regarding #5683: Converting of the ipv6 addresses to BigDecimal would be a waste here? Just use the byte[] directly: <http://docs.oracle.com/javase/7/docs/api/java/net/Inet6Address.html#getAddress()>

All signs are correct from the beginning, because its just 16 bytes (0-255), highest byte first. So order is correct by default. Theoretically we can index it as is (if we could use the new AutoPrefix terms), but for NumericRangeTree it should also be simple.

**Comment by mikemccand** [comment]
@uschindler right, we should go straight to the byte[]!  It ought to work very well.

**Comment by SKumarMN** [comment]
@kimchy @jpountz @dadoonet  @kzwang   

Hi,

I have used the above fix in my 1.4.4 code to support big integer by changing the IPV6 Mapper. Search and range queries works fine. Our application needs support for Bigdecimal too. Could you please provide me pointers about how can i implement big decimal support with range functionality as well..

**Comment by clintongormley** [comment]
Closing in favour of https://github.com/elastic/elasticsearch/issues/17007

**Pull request closed without merging**
