### PR TITLE
Fix bug 94733 geo_line not respecting sort_order

### LINKED ISSUE #94733: When running geo_line aggregation, the sort_order has no effect
### Elasticsearch Version

all supported versions

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

MacOSX (Darwin Kernel Version 22.3.0 arm64)

### Problem Description

The [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-geo-line.html) for `geo_line` claims that the option `sort_order` can be either `ASC` (default) or `DESC`:

>This option accepts one of two values: "ASC", "DESC".
>The line is sorted in ascending order by the sort key when set to "ASC", and in descending with "DESC".

However, when testing this, no matter which you choose the actual order of points in the result is always `ASC` by the value of the `sort` field.

### Steps to Reproduce

Create an index with a geo_point and a 

```
PUT /locations
{
  "mappings": {
    "properties": {
      "location":    { "type": "geo_point" },
      "rank":  { "type": "double"  }
    }
  }
}
```

Add data with appropriate rank values:

```
POST /locations/_bulk?refresh
{"index":{}}
{"location": [13.37139831, 47.82930284], "rank": 2.0 }
{"index":{}}
{"location": [13.3784208402, 47.88832084022], "rank": 0.0 }
{"index":{}}
{"location": [13.371830148701, 48.2084200148], "rank": 1.2 }
```

Query with `ASC` sort order:

```
POST /locations/_search?filter_path=aggregations
{
  "aggs": {
    "line": {
      "geo_line": {
        "point": {"field": "location"},
        "sort": {"field": "rank"},
        "include_sort": true,
        "sort_order": "ASC"
      }
    }
  }
}
```

And get expected result:

```
{
  "aggregations": {
    "line": {
      "type" : "Feature",
      "geometry" : {
        "type" : "LineString",
        "coordinates" : [
          [
            13.378421,
            47.888321
          ],
          [
            13.37183,
            48.20842
          ],
          [
            13.371398,
            47.829303
          ]
        ]
      },
      "properties" : {
        "complete" : true,
        "sort_values": [0.0, 1.2, 2.0]
      }
    }
  }
}
```

Query with `DESC` sort order:

```
POST /locations/_search?filter_path=aggregations
{
  "aggs": {
    "line": {
      "geo_line": {
        "point": {"field": "location"},
        "sort": {"field": "rank"},
        "include_sort": true,
        "sort_order": "DESC"
      }
    }
  }
}
```

But you get exactly the same result as the previous query. However, we expect the sort order to have been reversed and we expect the following result instead:

```
{
  "aggregations": {
    "line": {
      "type" : "Feature",
      "geometry" : {
        "type" : "LineString",
        "coordinates" : [
          [
            13.371398,
            47.829303
          ],
          [
            13.37183,
            48.20842
          ],
          [
            13.378421,
            47.888321
          ]
        ]
      },
      "properties" : {
        "complete" : true,
        "sort_values": [2.0, 1.2, 0.0]
      }
    }
  }
}
```

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by craigtaverner**
Fixes bug where `geo_line` did not support `sort_order`, silently ignoring the `DESC` option.

The [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-geo-line.html) for `geo_line` claims that the option `sort_order` can be either `ASC` (default) or `DESC`:

>This option accepts one of two values: "ASC", "DESC".
>The line is sorted in ascending order by the sort key when set to "ASC", and in descending with "DESC".

However, when testing this, no matter which you choose the actual order of points in the result is always `ASC` by the value of the `sort` field.

Fixes #94733

### CODE REVIEW

**Comment by craigtaverner** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by craigtaverner** [comment]
The original PR that created `geo_line` aggregation and added the explicit sort, has a feature description claiming that `sort_order: DESC` is supported (gives this as the first example). However, that PR was created in April 2019, and only merged in Nov 2020 with 34 commits, so there is a lot of hidden history. It is hard to see what the reasoning was for deliberately killing this behaviour. The code that forces `ASC` on the sort says:

```
        // the final reduce should always be in ascending order
        if (reduceContext.isFinalReduce() && SortOrder.DESC.equals(sortOrder)) {
            new PathArraySorter(mergedGeoLines.getFinalPoints(), mergedGeoLines.getFinalSortValues(), SortOrder.ASC).sort();
        }
```

See https://github.com/elastic/elasticsearch/pull/41612

**Comment by craigtaverner** [comment]
I've found the commit that added the final sort. It has the commit message:
> add size param

https://github.com/elastic/elasticsearch/pull/41612/commits/baaea0eb995e49d47cba9df60ee53347f710adca#diff-cc94b6c97b605e29bde7bb31a0d4af9b1a368818e7261c48a34590c93195ee8e

**Comment by craigtaverner** [comment]
The kibana team feel that this was not done for Kibana reasons. The most likely remaining reason was that it was something done during the work on `add size param`. My suspicion was that it was an unnecessary change based on a misunderstanding. Quite possibly a temporary situation during development. In any case as long as we have tests that assert correct behaviour of the combination of `size` and `sort_order` we should be good. I will verify and add any missing tests.

**Review by iverase — APPROVED** [review]
LGTM

**Pull request merged**
