### PR TITLE
Collapse transport versions 8,500,021-8,500,039 to 8,500,040

### PR DESCRIPTION
**Pull request by thecoop**
Clean up transport versions 8,500,021-8,500,039

### CODE REVIEW

**Review by ldematte — APPROVED** [review]
LGTM, but I have one question. 
My understanding is that it is safe to collapse these because there is no released version and no serverless instance dunning nodes with transport version between .021 and .039. How did you determine that?

**Comment by thecoop** [comment]
The oldest qa serverless deployment I could find was from 2 weeks ago, version 70-odd, so we can clean up 21-39 ok

**Comment by thecoop** [comment]
@elasticmachine update branch

**Comment by thecoop** [comment]
@elasticmachine update branch

**Pull request merged**
