### PR TITLE
Adding an example in the Set processor documentation to address #30604

### PR DESCRIPTION
**Pull request by ajoshbiol**
Adding an example in the Set processor documentation to address #30604

### CODE REVIEW

**Comment by jtibshirani** [comment]
Thanks @ajoshbiol for the PR! It looks like one of the docs tests is failing, because the `_type` in the response doesn't match. Other than that, this looks good to me (although I'll let @talevy weigh in as well before approving).

**Comment by ajoshbiol** [comment]
Thanks @jtibshirani! I updated the response document type to `_doc` to pass the builds.

**Review by talevy — APPROVED** [review]
thanks @jtibshirani.

looks great! thank you for iterating and contributing
to better documentation!

**Comment by talevy** [comment]
thanks @ajoshbiol. I went ahead and merged into master and deleted the branch. I will go forward with backports to 7.0 and 7.x

**Pull request merged**
