### PR TITLE
Enable trace log in FollowerFailOverIT

### PR DESCRIPTION
**Pull request by dnhatn**
This suite still fails one per week sometimes with a worrying assertion. Sadly we are still unable to find the actual source.

```   
Expected: <SeqNoStats{maxSeqNo=229, localCheckpoint=86, globalCheckpoint=86}>
but: was   <SeqNoStats{maxSeqNo=229, localCheckpoint=-1, globalCheckpoint=86}>
```

This change enables trace log in the suite so we will have a better picture if this fails again.

Relates #33337

### CODE REVIEW

**Review by jasontedor — APPROVED** [review]
LGTM.

**Review by martijnvg — APPROVED** [review]
LGTM

**Comment by dnhatn** [comment]
@jasontedor and @martijnvg I've added more log around the already-processed situation in 
https://github.com/elastic/elasticsearch/pull/38148/commits/959e00a55f14a220357503d44be875c4f0580ecf. Can you please have another look? Thank you!

**Review by martijnvg — APPROVED** [review]
Still LGTM

**Comment by dnhatn** [comment]
Thanks @jasontedor and @martijnvg.

**Pull request merged**
