### PR TITLE
Remove duplicated test

### PR DESCRIPTION
**Pull request by DaveCTurner**
These two tests are (character-for-character) identical, except for the name, which I don't think is important. Can this be removed?

### CODE REVIEW

**Comment by jasontedor** [comment]
Perhaps the intent was to have two slightly different tests, this one testing a timeout situation? Maybe we can suss out what the intent was and fix this by reworking this test to test for that situation?

**Comment by imotov** [comment]
@jasontedor that's what my thinking as well, but unfortunately I don't remember what my intent was when I added this test 3+ years ago :) However, after checking the code, I think this is a leftover of the origin design of this feature where the master node was supposed to wait for test files from data nodes to appear in the test folder in the repository to make sure they use the same directory. So, the intent was to timeout if files don't show up in time. I vaguely remember, that during the early development of this feature we flipped this logic around and now data nodes verify that the file written by master is visible to them instead. So, I think there is really no point in having this test anymore, since we don't really timeout.

**Review by imotov — APPROVED** [review]
LGTM.

**Comment by jasontedor** [comment]
Thanks @imotov.

**Pull request merged**
