### PR TITLE
watcher: Fix integration tests to ensure correct start/stop of Watcher

### LINKED ISSUE #29877: [CI] SmokeTestWatcherWithSecurityIT.* failing
*Original comment by @ywelsch:*

The tests in SmokeTestWatcherWithSecurityIT have been failing daily for the last few weeks.

- testSearchInputWithInsufficientPrivileges:
LINK REDACTED

- testIndexActionHasPermissions:
LINK REDACTED

Output:

```
12:09:37 [2018-03-14T12:08:40,747][ERROR][o.e.x.w.a.i.IndexActionFactory] [node-0] failed to execute action [my_watch/index]
12:09:37 org.elasticsearch.ElasticsearchSecurityException: action [indices:data/write/bulk[s]] is unauthorized for user [watcher_manager]
12:09:37 	at org.elasticsearch.xpack.core.security.support.Exceptions.authorizationError(Exceptions.java:42) ~[?:?]
12:09:37 	at org.elasticsearch.xpack.security.authz.AuthorizationService.denialException(AuthorizationService.java:595) ~[?:?]
12:09:37 	at org.elasticsearch.xpack.security.authz.AuthorizationService.denial(AuthorizationService.java:565) ~[?:?]
12:09:37 	at org.elasticsearch.xpack.security.authz.AuthorizationService.authorize(AuthorizationService.java:310) ~[?:?]
12:09:37 	at org.elasticsearch.xpack.security.action.filter.SecurityActionFilter.lambda$authorizeRequest$4(SecurityActionFilter.java:176) ~[?:?]
12:09:37 	at org.elasticsearch.xpack.security.authz.AuthorizationUtils$AsyncAuthorizer.maybeRun(AuthorizationUtils.java:185) ~[?:?]
12:09:37 	at org.elasticsearch.xpack.security.authz.AuthorizationUtils$AsyncAuthorizer.setRunAsRoles(AuthorizationUtils.java:179) ~[?:?]
12:09:37 	at org.elasticsearch.xpack.security.authz.AuthorizationUtils$AsyncAuthorizer.authorize(AuthorizationUtils.java:167) ~[?:?]
....
```

### LINKED ISSUE #30705: [CI] SmokeTestWatcherClientYamlTestSuiteIT "Test Jira Action with Error" failure
This test fails periodically because watcher is not started. This is likely because the node is considered green even when watcher is not started. So on a slow node, the test could start before watcher gets to the started state.

https://internal-ci.elastic.co/job/elastic+x-pack-elasticsearch+5.6+multijob-unix-compatibility/1568/console

### LINKED ISSUE #33291: [CI] SmokeTestWatcherWithSecurityIT.testSearchTransformInsufficientPermissions Failure
```
REPRODUCE WITH: ./gradlew :x-pack:qa:smoke-test-watcher-with-security:integTestRunner \
  -Dtests.seed=9861B17A9382A49D \
  -Dtests.class=org.elasticsearch.smoketest.SmokeTestWatcherWithSecurityIT \
  -Dtests.method="testSearchTransformInsufficientPermissions" \
  -Dtests.security.manager=true \
  -Dtests.locale=sr-Latn-ME \
  -Dtests.timezone=America/Cambridge_Bay \
  -Dcompiler.java=10 \
  -Druntime.java=8
```

stacktrace

```
3:45:09 FAILURE 12.0s | SmokeTestWatcherWithSecurityIT.testSearchTransformInsufficientPermissions <<< FAILURES!
23:45:09    > Throwable #1: java.lang.AssertionError: 
23:45:09    > Expected: is a value equal to or greater than <1>
23:45:09    >      but: <0> was less than <1>
23:45:09    > 	at __randomizedtesting.SeedInfo.seed([9861B17A9382A49D:514B584B289A370]:0)
23:45:09    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
23:45:09    > 	at org.elasticsearch.smoketest.SmokeTestWatcherWithSecurityIT.lambda$getWatchHistoryEntry$3(SmokeTestWatcherWithSecurityIT.java:326)
23:45:09    > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:847)
23:45:09    > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:821)
...
23:45:30 org.elasticsearch.ElasticsearchSecurityException: action [indices:data/write/bulk[s]] is unauthorized for user [watcher_manager]
```

### LINKED ISSUE #34448: [CI] XDocsClientYamlTestSuiteIT failed because of no `.watches` index
Two seemingly-unrelated tests failed for the same reason in the same run:

```
   > Throwable #1: java.lang.AssertionError: 4 active tasks found:
   > indices:data/write/update      YJDcklJoRF-6apksAvIohw:845 -                          transport 1539506880310 08:48:00 10.4s       127.0.0.1 node-0 
   > indices:data/write/update[s]   YJDcklJoRF-6apksAvIohw:846 -                          direct    1539506880321 08:48:00 10.4s       127.0.0.1 node-0 
   > indices:data/write/bulk        YJDcklJoRF-6apksAvIohw:847 -                          transport 1539506880322 08:48:00 10.4s       127.0.0.1 node-0 requests[1], indices[.watches]
   > indices:data/write/bulk[s]     YJDcklJoRF-6apksAvIohw:848 YJDcklJoRF-6apksAvIohw:847 transport 1539506880322 08:48:00 10.4s       127.0.0.1 node-0 requests[1], index[.watches]
   >  expected:<0> but was:<4>
   > 	at __randomizedtesting.SeedInfo.seed([8E320CEFCF5C0656:666333561A06BAE]:0)
   > 	at org.elasticsearch.xpack.test.rest.XPackRestTestHelper.lambda$waitForPendingTasks$3(XPackRestTestHelper.java:134)
   > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:847)
   > 	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:821)
   > 	at org.elasticsearch.xpack.test.rest.XPackRestTestHelper.waitForPendingTasks(XPackRestTestHelper.java:110)
   > 	at org.elasticsearch.xpack.test.rest.XPackRestTestHelper.waitForPendingTasks(XPackRestTestHelper.java:97)
   > 	at org.elasticsearch.xpack.test.rest.XPackRestIT.cleanup(XPackRestIT.java:246)
   > 	at java.lang.Thread.run(Thread.java:748)
   > 	Suppressed: java.lang.AssertionError: 4 active tasks found:
   > indices:data/write/update      YJDcklJoRF-6apksAvIohw:845 -                          transport 1539506880310 08:48:00 410ms       127.0.0.1 node-0 
   > indices:data/write/update[s]   YJDcklJoRF-6apksAvIohw:846 -                          direct    1539506880321 08:48:00 399.1ms     127.0.0.1 node-0 
   > indices:data/write/bulk        YJDcklJoRF-6apksAvIohw:847 -                          transport 1539506880322 08:48:00 397.9ms     127.0.0.1 node-0 requests[1], indices[.watches]
   > indices:data/write/bulk[s]     YJDcklJoRF-6apksAvIohw:848 YJDcklJoRF-6apksAvIohw:847 transport 1539506880322 08:48:00 397.8ms     127.0.0.1 node-0 requests[1], index[.watches]
   >  expected:<0> but was:<4>
   > 		at org.elasticsearch.xpack.test.rest.XPackRestTestHelper.lambda$waitForPendingTasks$3(XPackRestTestHelper.java:134)
   > 		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:835)
   > 		... 38 more
```

The server logs indicate that the `.watches` index does not exist:

```
[2018-10-14T08:48:21,707][WARN ][o.e.a.b.TransportShardBulkAction] [node-0] unexpected error during the primary phase for action [indices:data/write/bulk[s]], request [BulkShardRequest [[.watches][0]] containing [index {[.watches][doc][my-watch], source[{"trigger":{"schedule":{"cron":"0 0/1 * * * ?"}},"input":{"search":{"request":{"search_type":"query_then_fetch","indices":["logstash*"],"types":[],"body":{"query":{"bool":{"filter":{"range":{"@timestamp":{"from":"{{ctx.trigger.scheduled_time}}||-5m","to":"{{ctx.trigger.triggered_time}}"}}},"must":{"match":{"response":404}}}}}}}},"condition":{"compare":{"ctx.payload.hits.total":{"gt":0}}},"actions":{"email_admin":{"email":{"profile":"standard","to":["admin@domain.host.com"],"subject":"404 recently encountered"}}},"status":{"state":{"active":true,"timestamp":"2018-10-14T08:47:59.870Z"},"actions":{"email_admin":{"ack":{"timestamp":"2018-10-14T08:47:59.870Z","state":"awaits_successful_execution"}}},"headers":{"_xpack_security_authentication":"s6LxAgAKdGVzdF9hZG1pbgEJc3VwZXJ1c2VyCgAAAAEABm5vZGUtMAxkZWZhdWx0X2ZpbGUEZmlsZQA="},"version":-1,"last_checked":"2018-10-14T08:48:00.169Z","execution_state":"execution_not_needed"}}]}]]
org.elasticsearch.index.IndexNotFoundException: no such index
	at org.elasticsearch.cluster.routing.RoutingTable.shardRoutingTable(RoutingTable.java:137) ~[elasticsearch-6.5.0-SNAPSHOT.jar:6.5.0-SNAPSHOT]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase.primary(TransportReplicationAction.java:795) [elasticsearch-6.5.0-SNAPSHOT.jar:6.5.0-SNAPSHOT]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase.doRun(TransportReplicationAction.java:730) [elasticsearch-6.5.0-SNAPSHOT.jar:6.5.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.5.0-SNAPSHOT.jar:6.5.0-SNAPSHOT]
	at org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase$2.onNewClusterState(TransportReplicationAction.java:881) [elasticsearch-6.5.0-SNAPSHOT.jar:6.5.0-SNAPSHOT]
	at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onNewClusterState(ClusterStateObserver.java:303) [elasticsearch-6.5.0-SNAPSHOT.jar:6.5.0-SNAPSHOT]
	at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.clusterChanged(ClusterStateObserver.java:191) [elasticsearch-6.5.0-SNAPSHOT.jar:6.5.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.ClusterApplierService.lambda$callClusterStateListeners$7(ClusterApplierService.java:492) [elasticsearch-6.5.0-SNAPSHOT.jar:6.5.0-SNAPSHOT]
	at java.util.concurrent.ConcurrentHashMap$KeySpliterator.forEachRemaining(ConcurrentHashMap.java:3566) [?:?]
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735) [?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) [?:?]
	at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateListeners(ClusterApplierService.java:489) [elasticsearch-6.5.0-SNAPSHOT.jar:6.5.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:472) [elasticsearch-6.5.0-SNAPSHOT.jar:6.5.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:416) [elasticsearch-6.5.0-SNAPSHOT.jar:6.5.0-SNAPSHOT]
	at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:160) [elasticsearch-6.5.0-SNAPSHOT.jar:6.5.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:624) [elasticsearch-6.5.0-SNAPSHOT.jar:6.5.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:244) [elasticsearch-6.5.0-SNAPSHOT.jar:6.5.0-SNAPSHOT]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:207) [elasticsearch-6.5.0-SNAPSHOT.jar:6.5.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

The run was 
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=amazon/60/console and apparently this can be reproduced with

```
REPRODUCE WITH: ./gradlew :x-pack:docs:integTestRunner \
  -Dtests.seed=8E320CEFCF5C0656 \
  -Dtests.class=org.elasticsearch.smoketest.XDocsClientYamlTestSuiteIT \
  -Dtests.method="test {yaml=en/security/authorization/role-templates/line_53}" \
  -Dtests.security.manager=true \
  -Dtests.locale=es-UY \
  -Dtests.timezone=America/Argentina/Tucuman \
  -Dcompiler.java=11 \
  -Druntime.java=8

REPRODUCE WITH: ./gradlew :x-pack:docs:integTestRunner \
  -Dtests.seed=8E320CEFCF5C0656 \
  -Dtests.class=org.elasticsearch.smoketest.XDocsClientYamlTestSuiteIT \
  -Dtests.method="test {yaml=en/security/authentication/saml-guide/line_636}" \
  -Dtests.security.manager=true \
  -Dtests.locale=es-UY \
  -Dtests.timezone=America/Argentina/Tucuman \
  -Dcompiler.java=11 \
  -Druntime.java=8
```

However this does not reproduce for me.

I searched for similar issues and found https://github.com/elastic/elasticsearch/issues/34013 and https://github.com/elastic/elasticsearch/issues/33864 which relate to the security index. Perhaps this is similar? Pinging @nik9000, since you're looking at X-pack test cleanup code?

### LINKED ISSUE #34462: [CI] SmokeTestWatcherWithSecurityIT.testSearchInputHasPermissions fails
See this build
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.x+multijob-unix-compatibility/os=centos/58/console

There are 2 test failures, but the reasons seem to be different. testSearchInputHasPermissions fails with 503 HTTP response. Unable to reproduce locally.

```
REPRODUCE WITH: ./gradlew :x-pack:qa:smoke-test-watcher-with-security:integTestRunner \
  -Dtests.seed=484163AFA937AD5E \
  -Dtests.class=org.elasticsearch.smoketest.SmokeTestWatcherWithSecurityIT \
  -Dtests.method="testSearchInputHasPermissions" \
  -Dtests.security.manager=true \
  -Dtests.locale=it \
  -Dtests.timezone=Antarctica/Mawson \
  -Dcompiler.java=11 \
  -Druntime.java=8

```

Probably related to https://github.com/elastic/elasticsearch/issues/33320

### PR DESCRIPTION
**Pull request by jakelandis**
Ensure that Watcher is correctly started and stopped between tests for
SmokeTestWatcherWithSecurityIT,
SmokeTestWatcherWithSecurityClientYamlTestSuiteIT,
SmokeTestWatcherTestSuiteIT, WatcherRestIT,
XDocsClientYamlTestSuiteIT, and XPackRestIT

The change here is to throw an `AssertionError` instead of `break;` to
allow the `assertBusy()` to continue to busy wait until the desired
state is reached.

closes #33291, closes #29877, closes #34462, closes #30705, closes #34448

more details: https://github.com/elastic/elasticsearch/issues/33291#issuecomment-435200954

Note - I wasn't able to reproduce the actual test failures, but this is a strong candidate as the root cause and optimistically closing the open issues

EDIT: updated list of impacted classes
EDIT2: added XDocsClientYamlTestSuiteIT, and XPackRestIT and optimistically closing #34448

### CODE REVIEW

**Review by spinscale — APPROVED** [review]

**Comment by jakelandis** [comment]
@spinscale - thanks for the review. I just realized I missed the same issue in two different classes, **can you take another look** ? https://github.com/elastic/elasticsearch/pull/35271/commits/e2307323dde4cb8cae5496ceb6ddc322e8961960

> how did you relate #34462 to this?

The association is merely that it is the impacted class and 503 hints at something not started. However, there isn't enough information on the issue to take any action (the stack trace is gone) and it is not reproducible, so I think it best to close it with this change since it impacts the this class and something to do with a service not started. If it occurs again, we can re-open. 

FWIW, this is generally the logic I applied to all in the closes list.

**Comment by spinscale** [comment]
LGTM if CI is happy, thanks for peeking into it!

**Comment by jakelandis** [comment]
@spinscale - apologies for the death by a thousand pin pricks here... I found two more places. https://github.com/elastic/elasticsearch/pull/35271/commits/8d754792be0b250f6483231b7457e214b879908a

Also, add #34448 to the optimistic list of closes.

**Review by spinscale — APPROVED** [review]

**Comment by atorok** [comment]
@jakelandis I saw this failure on `6.5` also, please consider back-porting there as well. 
I was about to do the back-ports but held off as there's a possibly related failure I described in #35361.

**Comment by jakelandis** [comment]
@atorok pushed this back to 6.5 and 6.x, as on https://github.com/elastic/elasticsearch/issues/35361#issuecomment-437102473 the linked failure was for build prior to including these changes. While not perfectly confident this change fixes all the issue, I am confident it does not introduce new issues.

**Comment by jkakavas** [comment]
@jakelandis does this : https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+6.5+matrix-java-periodic/ES_BUILD_JAVA=java11,ES_RUNTIME_JAVA=java8fips,nodes=virtual&&linux/68/console

look like it is the manifestation of the same issue ?

**Comment by jakelandis** [comment]
@jkakavas - I had optimistically closed a few of the non-reproducible issue that _may_ have been fixed with this change. I re-opened https://github.com/elastic/elasticsearch/issues/29877#issuecomment-442577630 which has the same signature as the referenced build failure.

**Pull request merged**
