### PR TITLE
Cleanup bootstrap package.

### LINKED ISSUE #13044: make Bootstrap package private, Elasticsearch.main() calls Bootstrap.doMain()
Today its Elasticsearch.main() -> Bootstrap.main() -> Bootstrap.doMain(), and they are all public.

Its too much and adds a unnecessary stack frame to any exceptions to the console. We can also reduce exposed surface area of the scary stuff in Bootstrap by making the whole class package private.

And we should only have one entry point to start ES.

### PR DESCRIPTION
**Pull request by rmuir**
Cleanup the bootstrap package a bit:
- makes most classes final and package private
- removes duplicate and confusing multiple entry points
- adds javadocs to some classes like JarHell,Security
- adds a public class BootStrapInfo that exposes any stats
  needed by outside code.

Closes #13044

### CODE REVIEW

**Comment by dakrone** [comment]
Looks good to me

**Comment by vinhn** [comment]
Privatizing these kinds of things may make it harder for users to extend/customize the ES code, or to support other creative use cases like ES embedded inside another app/container.

**Comment by rmuir** [comment]
This code is not extendable. Its not intended for extension.
Embedding inside a container is not supported.

**Comment by bleskes** [comment]
@vinhn if you want to embed an ES node, `org.elasticsearch.node.NodeBuilder` is the way to go.

**Pull request merged**
