### PR TITLE
add privileges in vulnerabilities index

### PR DESCRIPTION
**Pull request by Omolola-Akinleye**
Add privileges for `kibana_system` user to allow support in Cloud Security Posture's vulnerabilities indices

### CODE REVIEW

**Comment by breskeby** [comment]
@elasticsearchmachine run please

**Comment by breskeby** [comment]
@elasticsearchmachine test this please

**Comment by ywangd** [comment]
Ping @elastic/kibana-security for awareness

**Review by CohenIdo — APPROVED** [review]
LGTM

**Pull request merged**
