### PR TITLE
Move to POST when calling API to retrieve which support request body

### LINKED ISSUE #28326: High Level Rest client should use POST when we have body
When elasticsearch is behind a Proxy and this Proxy does not support GET with body (which might be seen as a bug of the Proxy), people can't use our Java Rest Client as explained in https://discuss.elastic.co/t/es-cluster-via-proxy-ip-but-listener-timeout-after-waiting-for-30000-ms/116192/6

For example, the search Request here uses a GET method: https://github.com/elastic/elasticsearch/blob/b98514c6d905e70853d5316f823df38974f98739/client/rest-high-level/src/main/java/org/elasticsearch/client/Request.java#L424

I think we should may be switch to POST instead anytime we might have a body.

Thoughts?

### PR DESCRIPTION
**Pull request by javanna**
It has been pointed out that GET with body may cause problems to some proxies. We are then switching to POST the API that retrieve info and support a request body.

Closes #28326

### CODE REVIEW

**Review by dadoonet — APPROVED** [review]
LGTM

**Review by jasontedor — APPROVED** [review]
LGTM.

**Review by nik9000 — APPROVED** [review]

**Comment by javanna** [comment]
retest this please

**Comment by javanna** [comment]
I am marking this as a bug and backporting, given that it's a blocker for some users.

**Comment by javanna** [comment]
this is merged to master, 6.x and 5.6. Pending backport to 6.2 until 6.2.0 is released.

**Pull request merged**
