### PR TITLE
DayName SQL function #29981

### PR DESCRIPTION
**Pull request by mP1**
- couldnt add an optional <Timezoneid> parameter to function because
DateTimeFunction extends UnaryScalarFunction which forces only ONE
parameter. Abandoned attempt VariableArgumentsScalarFunction,
because that would change entire DTF hierarchy.

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
SIGNED

- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
YES

- If submitting code, have you built your formula locally prior to submission with `gradle check`?
YES - passed, unrelated failures, must have appeared in the last day or two, was fine with "previous master".

>> rch.transport.RemoteTransportException: [node-0][127.0.0.1:51406][indices:data/read/search[phase/query]]
Caused by: org.elasticsearch.search.aggregations.AggregationExecutionException: Aggregation [ip_terms] cannot support regular expression style include/exclude settings as they can only be applied to string fields. Use an array of values for include/exclude clauses
        at org.elasticsearch.search.aggregations.bucket.significant.SignificantTermsAggregatorFactory.doCreateInternal(SignificantTermsAggregatorFactory.java:219) ~[elasticsearch-7.0.0-alpha1-SNAPSHOT.jar:7.0.0-alpha1-SNAPSHOT]
        at org.elasticsearch.searc

- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
master

- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
OSX - shouldnt matter, no native stuff

- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

DONE

### CODE REVIEW

**Comment by mP1** [comment]
Im enhancing this to add support for passing timezone and locale to ALL datetime functions (optional params) with fallback to system defaults. Just need to fix dayName to work as a "date" prop in painless. sql query with parameters is working.

**Comment by mP1** [comment]
Done some more work on this ...

The ticket mentions it would be nice to support passing "timezones" to sql functions, so something like "hoursOfDay" will honour a timezone different to the system. Ive made changes to honour this (not pushed here yet).

All sql date functions now accept an optional timezone.

image

Ive also updated the sql function for dayName to accept a third optional timezone.

image

This of course means it makes sense to have "optional" timezones for all "date" properties, and an optional timezone and optional locale for dayName. The problem is the jodatime ReadableDateTime does not include any of these methods, theres not even method to "get" dayName, and currently theres no way too "attach" extension methods or fields to a built in type.

All this can be achieved by inserting equivalent expressions, but that is rather horrible and "long", it should be possible for the user to call a single method..

doc[$field].value.dayName($AustraliaEasternTimeZoneId, $Locale)

and that should just work, and it now does...

image


To achieve this ive had to introduce a new sub class of ReadableDateTime and add (overloaded methods) to support the features mentioned above. That means my new RDT adds methods like

-getDayName()
-getDayName(String timeZoneId)
-getDayName(String timeZoneId, String locale)

behind the scenes i do the right thing, so the "final value" matches the same as the sql function gave.

More when its ready for review, but it would be nice if someone gave some comment about my approach of adding "extension mehtods/fields" so values work in painless just like they do in sql.

Its almost done, hopefully will wrap up in a day or two (need to add more tests)

**Comment by mP1** [comment]
In short ive taken liberties to support additional overloads for the built in types, in my case the datetimes stuff. There are basically two ways i can quickly think of and someone really needs to comment about this.

- support mapping extension methods/field to the current types
- introduce new sub classes of build in types(delegate etc) with the extra methods and field getters that we want/need.

**Comment by mP1** [comment]
The only problem is currently only timezone is passed around as "context" to all functions, ive replaced that with a FunctionContext which now holds timezone and locale. The problem is of course the system settings only has a timezone, im not sure where i should pull locale or just call Locale get default.

**Comment by costin** [comment]
Hi @mP1,

Thanks for raising the PR.  There are a number of comments so hopefully I haven't missed too much.
My understanding is that you'd like to add the SQL function `DAY_NAME` - please confirm whether that's the case since it's not clear from the PR description.

As far as I can see that's a MySQL specific function.There's [DATENAME](https://docs.microsoft.com/en-us/sql/t-sql/functions/datename-transact-sql?view=sql-server-2017) but even seems specific to MS-Server which is not ideal.
Postgres also has its own approach.

The lack of standardization makes such functions a low priority. Sorry..

Implementation wise, each SQL query is bound to a `TimeZone` which is implicit to all `DateTimeFunction`s.  The `Locale` likely would use the same approach - however since it's currently not used, there's no reason to add one (yet).
Any formatting function would either have to work in the same timezone or accept one as a parameter.

**Comment by mP1** [comment]
@costin 

> Thanks for raising the PR. There are a number of comments so hopefully I haven't missed too much.
My understanding is that you'd like to add the SQL function DAY_NAME - please confirm whether that's the case since it's not clear from the PR description.

Yes -> DAY_NAME is correct. The "exact" name is of course easily changed (literals always are :)

> As far as I can see that's a MySQL specific function.There's DATENAME but even seems specific to MS-Server which is not ideal.
Postgres also has its own approach.

Unfortunately thats true, so ive taken some liberties in my implementation for ES. The ticket is a little vague on the exact details so ive made some assumptions.

> Implementation wise, each SQL query is bound to a TimeZone which is implicit to all DateTimeFunctions. The Locale likely would use the same approach - however since it's currently not used, there's no reason to add one (yet).

Im not looking for guidance, ive done what you describe and it works as you can see from my kibana screenshots.

My comment regarding "where" the system gets its locale is because the timezone is taken from ES Settings class, but no similar property exists for locale, soim using LocalegetDefaultlocale(). This seemed "different" 

> Any formatting function would either have to work in the same timezone or accept one as a parameter.

Thats already done, my code honours the optional timezone/locale parameters or uses the "default" .

Its basiscally all done, hopefully my stuff hasnt broken too many tests and i can push this new commit tomorrow.

**Comment by mP1** [comment]
@costin 

My questions where more for "how" it should "add" extra properties to enable "dayName" for date values in painless. Ive got it working but ive had to add an extra class to the whitelist of "supported" classes. It also means that painless methods on date/time can now take a timezone when the real joda-time ReadableDateTime only supports getters. Ive added "extra" getters for each property and do the right thing.

As mentioned above, this is one possible answer, but it might not be what others envision.

**Pull request closed without merging**
