### PR TITLE
Disable bwc tests for #76475

### PR DESCRIPTION
**Pull request by imotov**
Disabling bwc tests to merge #76475

### CODE REVIEW

**Comment by imotov** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by imotov** [comment]
Looks like CI cannot quite figure out which nodes are part of it and which nodes are not, will have to wait until Monday. cc @mark-vieira

**Comment by mark-vieira** [comment]
I think CI in general is having problems. I don't think this is in any way specifically related to BWC tests.

**Comment by imotov** [comment]
@elasticmachine run elasticsearch-ci/docs

**Pull request merged**
