### PR TITLE
Add status field to MultiSearchTemplateResponse

### PR DESCRIPTION
**Pull request by AbeleMM**
Addresses  #83029.
Adds `status` field to `MultiSearchTemplateResponse`, as is already the case for `MultiSearchResponse`. Tried to touch as little code as necessary to allow for the change, while also mimicking the structure of  `MultiSearchResponse` and `SearchResponse` as much as possible.

### CODE REVIEW

**Comment by cbuescher** [comment]
Hi @AbeleMM, thanks for your help with this issue and apologies that it took a bit to pick up your PR. I looked at the change and it looks good. We will need some sort of test however. There are two options for this. First, there are unit test "MultiSearchTemplateRequestTests" and "MultiSearchResponseTests", both of which so far unfortunately don't test the xContent output. I would probably use a fixed response object and write the json output to a String, something like in "org.elasticsearch.index.rankeval.RankEvalResponseTests#testToXContent" maybe.
The second option would be to modify the rest test we have under `modules/lang-mustache/src/yamlRestTest/resources/rest-api-spec/test/lang_mustache/50_multi_search_template.yml`. These are request/response pairs written in yaml. You can take a look at how the corresponding `_msearch` tests look like at `rest-api-spec/src/yamlRestTest/resources/rest-api-spec/test/msearch/11_status.yml`. They already test the existence of the status field, something that would have to be added to the tests under `modules/lang-mustache/src/yamlRestTest/resources/rest-api-spec/test/lang_mustache`.
If you need more pointers or help adding or running the test let me know, I can also take care of it if you don't have the time to do so.

**Comment by AbeleMM** [comment]
> Hi @AbeleMM, thanks for your help with this issue and apologies that it took a bit to pick up your PR. I looked at the change and it looks good. We will need some sort of test however. There are two options for this. First, there are unit test "MultiSearchTemplateRequestTests" and "MultiSearchResponseTests", both of which so far unfortunately don't test the xContent output. I would probably use a fixed response object and write the json output to a String, something like in "org.elasticsearch.index.rankeval.RankEvalResponseTests#testToXContent" maybe. The second option would be to modify the rest test we have under `modules/lang-mustache/src/yamlRestTest/resources/rest-api-spec/test/lang_mustache/50_multi_search_template.yml`. These are request/response pairs written in yaml. You can take a look at how the corresponding `_msearch` tests look like at `rest-api-spec/src/yamlRestTest/resources/rest-api-spec/test/msearch/11_status.yml`. They already test the existence of the status field, something that would have to be added to the tests under `modules/lang-mustache/src/yamlRestTest/resources/rest-api-spec/test/lang_mustache`. If you need more pointers or help adding or running the test let me know, I can also take care of it if you don't have the time to do so.

@cbuescher Thank you for the helpful comment! I have added checks for the status of response items to the existing tests in `modules/lang-mustache/src/yamlRestTest/resources/rest-api-spec/test/lang_mustache/50_multi_search_template.yml`. Please let me know about any further changes/updates required.

**Comment by cbuescher** [comment]
Thanks @AbeleMM, that looks great. I will probably need to push a few minor changes myself to the branch if that is okay to make the test work with the backward compatibility checks of our CI, but want to spare you the details. Hope its okay if me / our bot pushes to this branch a bit. Will run the tests after merging in master.

**Comment by AbeleMM** [comment]
> Thanks @AbeleMM, that looks great. I will probably need to push a few minor changes myself to the branch if that is okay to make the test work with the backward compatibility checks of our CI, but want to spare you the details. Hope its okay if me / our bot pushes to this branch a bit. Will run the tests after merging in master.

Sounds great!

**Comment by cbuescher** [comment]
@elasticmachine update branch

**Review by cbuescher — APPROVED** [review]
LGTM

**Comment by cbuescher** [comment]
@elasticmachine update branch

**Comment by cbuescher** [comment]
@elasticmachine test this please

**Comment by cbuescher** [comment]
@elasticmachine test this please

**Comment by cbuescher** [comment]
@elasticmachine run elasticsearch-ci/packaging-tests-windows-sample

**Comment by cbuescher** [comment]
@AbeleMM thanks a lot for your contribution an the quick replies, much appreciated.

**Comment by AbeleMM** [comment]
> @AbeleMM thanks a lot for your contribution an the quick replies, much appreciated.

Thank you for the guidance!

**Pull request merged**
