### PR TITLE
Rename ILM package to ilm

### PR DESCRIPTION
**Pull request by jasontedor**
This commit renames the ILM package from indexlifecycle to ilm. We have all come to know index lifecycle management as ILM, the APIs and settings use ilm, and it would be nice of the package did too. This commit makes that change.

Relates #44608

### CODE REVIEW

**Comment by jasontedor** [comment]
For further background, see my [comment] on the PR renaming the SLM packages. This change here could be seen as breaking, since it would change the name of loggers. Since we don't offer any backwards compatibility guarantees about loggers and logging, I don't think we should consider it as breaking, but I want to make sure that we have a proper discussion about this.

**Review by dakrone — APPROVED** [review]
LGTM, I think it's okay since as you said, we don't have backwards compatibility guarantees for logging names

**Comment by jasontedor** [comment]
@dakrone @gwbrown I do not intend to backport this change to any branches that are in maintenance mode: 6.8, 7.2, and 7.3. This is because I expect backports to not be numerous (we aren't adding new features), and rename detection should be fine in nearly all cases. For 6.8 which will be longer running than 7.2 and 7.3, I could see an argument to backport but am for now going to hold off. Let me know if you think otherwise, and of course, we can revisit this in the future too should backports prove more frequent or comprehensive than we currently think they will be.

**Comment by dakrone** [comment]
I agree that this should only be backported to 7.4, I don't think not backporting it will cause any problems.

**Pull request merged**
