### PR TITLE
make slow tests more obvious

### PR DESCRIPTION
**Pull request by rmuir**

### CODE REVIEW

**Comment by nik9000** [comment]
Very cute. If we're not wiling to add a jar file for the gradle launcher though I wonder about a wav file for a cute sound.

**Comment by nik9000** [comment]
Also my poor macbook air keeps making noises! I know its a slow machine....

**Comment by mikemccand** [comment]
LGTM, this is nice.  I tested on my mac and it worked very well :)

**Comment by jdconrad** [comment]
Seconded on the LGTM.  We seem to have quite a few slow tests.

**Comment by jpountz** [comment]
+1

**Comment by purbon** [comment]
I like this idea, we should do something alike in Logstash! :+1:

**Comment by rjernst** [comment]
LGTM

**Comment by rmuir** [comment]
@nik9000 I think a sound or image is quite different than executable code? If you are opposed, I will not push the commit though. I figure, I wait on these tests day and night, we could use a little fun.

**Comment by nik9000** [comment]
Fine by me. I don't want to block anyone's fun.

**Comment by drewr** [comment]
I like this in theory, but it's causing a lot of failures in the build environment, for example:

```
HEARTBEAT J1 PID(7647@slave-ffa9f226.build.us-west-2b.elasticnet.co): 2016-01-11T15:40:48, stalled for 11.7s at: IndexedExpressionTests.testAllOpsDisabledIndexedScripts
[ant:junit4] PulseAudioMixer: got interrupted while waiting for the EventLoop to initialize
```

We're getting that with about a third of the tests on Debian-derived EC2 systems:

* Debian 8.2, Linux 3.16.0-4-amd64, 1.8.0_66-internal-b17
* Ubuntu 14.04, Linux 3.13.0-74-generic, 1.8.0_72-internal-b05
* Ubuntu 15.04, Linux 3.19.0-42-generic, 1.8.0_45-internal-b14

Anybody happen to know a thread to pull here on a solution? Searching around I only see references to the exception text in the source.

**Comment by nik9000** [comment]
> Anybody happen to know a thread to pull here on a solution? Searching around I only see references to the exception text in the source.

I'd make a system setting that lets you disable it entirely and configure it on the build nodes. I'd do the same on my headless build box.

**Comment by rmuir** [comment]
Its not the cause. The cause is whoever is calling thread.interrupt. we should stay completely focused on that.

**Comment by drewr** [comment]
After unsetting `PULSE_SERVER` in the calling env we haven't seen this in a few days.

**Pull request merged**
