### PR TITLE
update `readMap` to avoid resizing map during reading

### PR DESCRIPTION
**Pull request by idegtiarenko**
This commit updates readMap to use helper method that presizes map
correctly. It guarantees no resizing when adding given numbers of
entries to a hashmap.

### CODE REVIEW

**Comment by DaveCTurner** [comment]
Could we do the same thing for `readOrderedMap` too?

Is there any trickery we can perform to assert that the map really doesn't get resized while we're reading it?

**Comment by arteam** [comment]
I believe I didn't integrate the factory method for creating sized `LinkedHashMaps` https://github.com/elastic/elasticsearch/commit/9e6def305f6f1561b9fd38eb1ee10a2257ba00b6 which I should have done!

**Comment by idegtiarenko** [comment]
>Could we do the same thing for readOrderedMap too?

Will update. Looks like it has only 6 usages.

**Comment by idegtiarenko** [comment]
>Is there any trickery we can perform to assert that the map really doesn't get resized while we're reading it?

I am not sure. `java.util.HashMap#capacity` is not public and in recent jdks we could not easily make it accessible if we would like to access it via reflection.

**Comment by arteam** [comment]
Submitted https://github.com/elastic/elasticsearch/pull/84054

**Review by DaveCTurner — APPROVED** [review]
LGTM, let's come back to the question about asserting no resizing later

**Pull request merged**
