### PR TITLE
Add the possibility to transform WKB to WKT directly

### PR DESCRIPTION
**Pull request by iverase**
Currently, if we want to generate WellKnownText (WKT) from WellKnownBinary( WKB) we need first to create a Geometry object from the WKB and then generate WKT from the WKB. This seems wasteful as it is not difficult to generate the WKT directly.

This PR adds such a logic which can be useful for ES|QL, which it might use WKB as the transform format for geometries.

### CODE REVIEW

**Comment by iverase** [comment]
@elasticmachine run elasticsearch-ci/part-2

**Review by craigtaverner — APPROVED** [review]
LGTM

**Comment by iverase** [comment]
@elasticmachine run elasticsearch-ci/part-3

**Comment by iverase** [comment]
@elasticmachine pleases test this

**Comment by iverase** [comment]
@elasticmachine please test this

**Comment by iverase** [comment]
@elasticmachine update branch

**Comment by iverase** [comment]
@elasticmachine run elasticsearch-ci/part-4

**Comment by iverase** [comment]
@elasticmachine update branch

**Comment by iverase** [comment]
@elasticmachine run elasticsearch-ci/part-4

**Comment by iverase** [comment]
@elasticmachine update branch

**Pull request merged**
