### PR TITLE
Return API key name in _authentication response

### LINKED ISSUE #70306: Return API key name as part of _authenticate response
### Problem statement

When the `_authenticate` API is called using an API key, the response includes information about the user but no details about the API key itself.

The API key name could be useful to get, as it can be used to identify the key without using a separate call.

### Proposed solution

Return the API key `name` field as part of the `_authenticate` response payload.

### PR DESCRIPTION
**Pull request by justincr-elastic**
Responses to POST /_security/api_key includes id, name, metadata,
api_key (shared secret), and encoded (base64 of id:api_key).

Requests to GET /_security/_authenticate returns data about the user,
but not the API KEY.

When authenticating using an API KEY, return API KEY info map in the
response. The initial feature request asked for 'name'. However, the
request's Authentication header contains 'encoded', so the decoded
'id' will be returned for convenience too.

When authenticating using any other method, API KEY info map is
omitted.

Closes #70306

Example request:
```
curl -s -X GET -H "Authorization: ApiKey base64(id:api_key)" "localhost:9200/_security/_authenticate?pretty"
```

Example response:
```
{
  "username" : "my-username",
  "roles" : [ ],
  "full_name" : null,
  "email" : null,
  "metadata" : { },
  "enabled" : true,
  "authentication_realm" : {
    "name" : "_es_api_key",
    "type" : "_es_api_key"
  },
  "lookup_realm" : {
    "name" : "_es_api_key",
    "type" : "_es_api_key"
  },
  "authentication_type" : "api_key",
  "token" : {
  },
  "api_key" : {
    "id": "jdgWKXwBtdtKDGAHT5OX"
    "name": "my-api-key"
  }
}
```

### CODE REVIEW

**Review by ywangd — COMMENTED** [review]
I didn't really look into the client side code. But here are a few things on the server side.

**Comment by justincr-elastic** [comment]
@elasticmachine update branch

**Review by ywangd — COMMENTED** [review]
This might be a personal preference, but I'd avoid using trailing comments especially when they are long. They do not play very nicely with refactoring and 140 char formatting rule.

**Review by ywangd — COMMENTED** [review]
A few more comments. I think we are almost there. Thanks!

**Comment by justincr-elastic** [comment]
@elasticmachine update branch

**Review by ywangd — APPROVED** [review]
LGTM pending green CI

Thanks for the iterations Justin. I appreciate your patience.

**Review by ywangd — APPROVED** [review]
LGTM. (Not sure why my previous disappeared. But I approved already a couple days back.)

**Pull request merged**
