### PR TITLE
Fix multi level nested sort

### LINKED ISSUE #31554: Under certain conditions, sort values for a hit come from an unrelated document
**Elasticsearch version** (`bin/elasticsearch --version`):

6.3.0 (from docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.0)

**Plugins installed**: []

**JVM version** (`java -version`):

```
openjdk version "10.0.1" 2018-04-17
OpenJDK Runtime Environment (build 10.0.1+10)
OpenJDK 64-Bit Server VM (build 10.0.1+10, mixed mode)
```

**OS version** (`uname -a` if on a Unix-like system):

```
Linux f076156ce113 4.4.0-128-generic #154-Ubuntu SMP Fri May 25 14:15:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Description of the problem including expected versus actual behavior**:

Under certain conditions, sort values for a hit come from an unrelated document. The specific case illustrated below involves two documents on the same shard, one of which is PUT both before and after the other without a refresh in between. 

Expected behaviour: a search with multi-level nested sort targeting that document returns "missing" sort value.

Actual behaviour: a search with multi-level nested sort targeting that document returns the sort value from the other document.

We believe the problem is wider-reaching than this as we have observed the behaviour with many (or most) of our searches which use multi-level nested sorts.

**Steps to reproduce**:

Execute following bash script.

```
#!/bin/bash

function http {
  curl -Ss -H 'Content-Type: application/json' -X "$@"
  echo
}

http DELETE "localhost:9200/test"

http PUT "localhost:9200/test"  -d '{
    "mappings": {
      "test-type": {
        "dynamic": "strict",
        "properties": {
          "nested1": {
            "type": "nested",
            "properties": {
              "nested2": {
                "type": "nested",
                "properties": {
                  "nested2_keyword": {
                    "type": "keyword"
                  },
                  "sortScore": {
                    "type": "integer"
                  }
                }
              },
              "nested1_keyword": {
                "type": "keyword"
              }
            }
          },
          "key": {
            "type": "keyword"
          }
        }
      }
    },
    "settings": {
      "index": {
        "number_of_shards": "1"
      }
    }
}
'

http PUT "localhost:9200/test/test-type/1" -d '{ "key": 1 }'

http PUT "localhost:9200/test/test-type/2" -d '{
  "key": 2,
  "nested1": [      
    {
      "nested2": [
        {
          "nested2_keyword": "nested2_bar",
          "sortScore": 1234
        }
      ],
      "nested1_keyword": "nested1_foo"
    }      
 ]
}
'

# works with refresh here (but not earlier)
#http POST "localhost:9200/test/_refresh"

#works with update instead of PUT
#http POST "localhost:9200/test/test-type/1/_update" -H 'Content-Type: application/json' -d '{ "key": 1 }'

http PUT "localhost:9200/test/test-type/1" -d '{ "key": 1 }'

http POST "localhost:9200/test/_refresh"

http GET "localhost:9200/test/_search?pretty" -d '{
  "query": {
    "bool": {
      "filter": [
        {
          "term": {
              "key":  1
          }
        }
      ]
    }
  },
  "sort": [
    {
      "nested1.nested2.sortScore": {
        "order": "desc",
        "mode": "max",
          "missing" : -1,
          "nested": {
          "path": "nested1",
          "filter": {
            "term": {
              "nested1.nested1_keyword": "nested1_foo"
            }
          },
          "nested": {
            "path": "nested1.nested2",
            "filter": {
              "term": {
                "nested1.nested2.nested2_keyword": "nested2_bar"
              }
            }
          }
        }
      }
    }
  ]
}
'
```

The search returns something like this:

```
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : null,
    "hits" : [
      {
        "_index" : "test",
        "_type" : "test-type",
        "_id" : "1",
        "_score" : null,
        "_source" : {
          "key" : 1
        },
        "sort" : [
          1234
        ]
      }
    ]
  }
}
```

the sort value of `1234` is defined in doc 2, not doc 1.

**Provide logs (if relevant)**:

### LINKED ISSUE #31783: Multi level nested sorting incorrectly using bitset filter cache
While looking into #31554, I noticed that in case multi level nested sorting is used and levels use a nested filter then the nested field type filter AND specified nested filter by the user are cached in the bitset filter cache. 

In the case of #31554 this ended up being cached: `+_type:__nested1 #ToParentBlockJoinQuery (nested1.nested1_keyword:nested1_foo)`. I would only expect `+_type:__nested1` to be cached by the bitset filter cache. 

I think this is not intended and if many different nested sort filter where to be specified in separate search requests then this could cause the bitset filter cache to consume a lot of jvm heap space.

The problem is in `SortBuilder` class line 251 where this happens: `context.bitsetFilter(parentQuery)`
and in the case of multi level sorting `parentQuery` could be set to the nested filter of the parent nested sort definition.

I'm not sure how this can be best be fixed. I'm opening this issue to track the problem.

### LINKED ISSUE #32130: Broken sort on multiple-level nested documents
**Elasticsearch version** : 6.3.1 and below

**JVM version** : 1.8.0_171

**OS version** : Ubuntu 16.04 LTS

**Expected behaviours** : 
correct sort. The family with id=2 should get a sort value of 30 in the example below.

**Problem description** : 
faulty sort when querying on a 3-levels nested objects model, and sorting parent objects on a field from the lower level. In the example below, family with id=2 is getting a sort value of 10 while it should be 30 (the value 10 doesn't even appear in the document with id=2).

**Steps to reproduce**:

1. Create index
``
PUT tree 
{ "settings": {"number_of_shards": 1,"number_of_replicas": 0 } }
``

2. Put mapping
``
PUT tree/family/_mapping
{"properties":{"name":{"type":"keyword"},"members":{"type":"nested","properties":{"firstname":{"type":"keyword"},"color":{"type":"keyword"},"levels":{"type":"nested","properties":{"strength":{"type":"integer"}}}}}}}
``

3. Insert data (bulk index API)
``
POST _bulk
{ "index" : { "_index" : "tree", "_type" : "family", "_id" : "1" } }
{"name":"Doe","members":[{"firstName":"John","color":"brown","levels":{"strength":10}},{"firstName":"Serge","color":"brown","levels":{"strength":15}},{"firstName":"Marie","color":"brown","levels":{"strength":20}}]}
{ "index" : { "_index" : "tree", "_type" : "family", "_id" : "2" } }
{"name":"Simpson","members":[{"firstName":"Homer","color":"brown","levels":{"strength":30}},{"firstName":"Lisa","color":"brown","levels":{"strength":40}},{"firstName":"Marge","color":"brown","levels":{"strength":60}}]}
{ "index" : { "_index" : "tree", "_type" : "family", "_id" : "3" } }
{"name":"Simpson","members":[{"firstName":"Bart","color":"yellow","levels":{"strength":70}},{"firstName":"Snowball","color":"yellow","levels":{"strength":80}},{"firstName":"Maggie","color":"yellow","levels":{"strength":90}},{"firstName":"Gandpa","color":"brown","levels":{"strength":95}}]}
``

4. Query
``
GET tree/_search
{
  "query": {
    "bool": {
      "filter": [
        {
          "term": {
            "name": {
              "value": "Simpson"
            }
          }
        },
        {
          "nested": {
            "path" : "members",
  					"query": {
  					    "bool" : {
  					      "filter" : [
  					          {
          							"term" : {
          								"members.color" :  {
          								  "value" : "brown"
          								}
          							}
  					          }
  					       ]
  					    }
  						}
  				}
				}
       ]
    }
  },
  "sort": [
    {
      "members.levels.strength": {
        "order": "asc",
  			"nested": {
  				"path": "members",
  				"filter": {
  					"term" : {
  						"members.color" : {
  							"value" : "brown"
  						}
  					}
  				},
  				"nested": {
  					"path": "members.levels"
  				}
  			}
      }
    }
  ]
}
``

5. Results
``
{
  "hits": {
    "total": 2,
    "max_score": null,
    "hits": [
      {
        "_index": "tree",
        "_type": "family",
        "_id": "2",
        "_score": null,
        "_source": {
          "name": "Simpson",
          "members": [
            {
              "firstName": "Homer",
              "color": "brown",
              "levels": {
                "strength": 30
              }
            },
            {
              "firstName": "Lisa",
              "color": "brown",
              "levels": {
                "strength": 40
              }
            },
            {
              "firstName": "Marge",
              "color": "brown",
              "levels": {
                "strength": 60
              }
            }
          ]
        },
        "sort": [
          10
        ]
      },
     ...
    ]
  }
}
``
---
**Note that the result of the query above is correct if the index API was used instead of the bulk API, using the commands below :**
``
POST tree/family
{"name":"Doe","members":[{"firstName":"John","color":"brown","levels":{"strength":10}},{"firstName":"Serge","color":"brown","levels":{"strength":15}},{"firstName":"Marie","color":"brown","levels":{"strength":20}}]}
POST tree/family
{"name":"Simpson","members":[{"firstName":"Homer","color":"brown","levels":{"strength":30}},{"firstName":"Lisa","color":"brown","levels":{"strength":40}},{"firstName":"Marge","color":"brown","levels":{"strength":60}}]}
POST tree/family
{"name":"Simpson","members":[{"firstName":"Bart","color":"yellow","levels":{"strength":70}},{"firstName":"Snowball","color":"yellow","levels":{"strength":80}},{"firstName":"Maggie","color":"yellow","levels":{"strength":90}},{"firstName":"Gandpa","color":"brown","levels":{"strength":95}}]} 
``

_See following discussion : https://discuss.elastic.co/t/issue-sorting-nested-documents-indexed-via-bulk/139164_

### PR DESCRIPTION
**Pull request by jimczi**
Multi level nested sort produces an invalid parent filter that contains a required clause at the wrong level. This can lead to document picking values from other documents. This change fixes this bug by removing the child query entirely from the parent filter.
Multi level nested sort now creates a single parent query that match the level of documents that needs to be sorted and a child query that contains the nested filters at the deepest level (where the sort field exists). This change also ensures that we cache only nested type filters in the bitset filter cache.(https://github.com/elastic/elasticsearch/issues/31783)

Supersedes #31776
Closes #31554
Closes #32130
Closes #31783

### CODE REVIEW

**Review by martijnvg — APPROVED** [review]
Thanks @jimczi for fixing! LGTM

**Comment by JulienColin** [comment]
Hello,
I've tested the 6.3.2 release against the #32130 issue, and from what I see this is not fixed. I still run into the same issue when using bulk indexing. Is it possible to re-open the issue ?

Thank you

**Comment by jimczi** [comment]
@JulienColin the fix is not in the 6.3.2 release, I thought that it would be part of it but the merge was too late. I'll update the release notes and bumped the fixed version to 6.3.3. Thanks for checking.

**Comment by JulienColin** [comment]
Alright @jimczi , indeed I was mislead by the release not. Thank you very much !

**Pull request merged**
