### PR TITLE
Add support for Gradle 4.3

### LINKED ISSUE #26840: Build is failing with Gradle 4.2
Not sure what causes it but when I run:

```sh
gradle :plugins:repository-azure:check
```

I'm getting (tested on 5.6, 6.0 and 6.x branches):

```
* What went wrong:
Execution failed for task ':plugins:repository-azure:integTestCluster#installRepositoryAzurePlugin'.
> A problem occurred starting process 'command '/Users/dpilato/Documents/Elasticsearch/dev/elasticsearch/es-5.x/elasticsearch/plugins/repository-azure/build/cluster/integTestCluster node0/elasticsearch-5.6.3-SNAPSHOT/bin/elasticsearch-plugin''
```

Note that on 6.0 and 6.x the message is a bit different as it fails when running `bin/elasticsearch-keystore`. I checked manually the directory and I'm able to run `bin/elasticsearch-plugin` or `bin/elasticsearch-keystore` manually.

```sh
$ gradle -version

------------------------------------------------------------
Gradle 4.2
------------------------------------------------------------

Build time:   2017-09-20 14:48:23 UTC
Revision:     5ba503cc17748671c83ce35d7da1cffd6e24dfbd

Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_144 (Oracle Corporation 25.144-b01)
OS:           Mac OS X 10.12.6 x86_64
```

Running with `gradlew` works:

```sh
./gradlew :plugins:repository-azure:check
```

gradlew reports a 3.3 version of Gradle.

### PR DESCRIPTION
**Pull request by dadoonet**
Closes #26840
Related to #27087

### CODE REVIEW

**Review by jasontedor — APPROVED** [review]
This seems to work for me on macOS and Linux. LGTM.

**Comment by dadoonet** [comment]
Thansk @jasontedor. Where should I backport it to? I guess same branches as #27087? 5.6, 6.0, 6.1 and master, right?

**Comment by jasontedor** [comment]
@dadoonet The same branches indeed.

**Comment by dadoonet** [comment]
I wonder if we should reopen #26840 and revert this patch.
With `Gradle 4.3.1`, I'm still hitting this problem from time to time.

**Comment by ywelsch** [comment]
@dadoonet I've figured out the remaining Gradle >= 4.2 issue with our build and will create a fix later today.

**Pull request merged**
