### PR TITLE
Docs: Rework close ml section

### PR DESCRIPTION
**Pull request by nik9000**
Reworks the close ml section to work properly in Asciidoctor. It
renders a little funny in AsciiDoc but AsciiDoc is on its way out
anyway....

Relates to #41128

### CODE REVIEW

**Comment by nik9000** [comment]
Neat! I didn't see that failure locally.

**Comment by nik9000** [comment]
I didn't commit one part of my original change.....

**Review by jrodewig — APPROVED** [review]
LGTM and builds successfully.

As @nik9000 noted, the rendering in the Asciidoc version is a little wonky but doesn't break functionality.

Screen Shot 2019-04-23 at 10 54 36 AM

**Comment by nik9000** [comment]
OOh. That extra +....

**Comment by nik9000** [comment]
> OOh. That extra +....

Oh well. I can live with it for the next few days until we do the conversion. I'm hoping it'll be days.

**Comment by nik9000** [comment]
I've backported this. master and 7.0 can now be built with asciidoctor. 7.x is still busted. I'll see if I can fix it.

**Pull request merged**
