### PR TITLE
BACKPORT 7x Move "allows remote indices" to a request property (#74630)

### PR DESCRIPTION
**Pull request by albertzaharovits**
Backport of https://github.com/elastic/elasticsearch/pull/74630

Some requests can reference index names on a remote cluster, yet most don't.
When (locally) authorizing requests that can NOT reference remote indices, the
security code takes a (cached) shortcut to first check if the request is authorized
for any index, before doing the in-detail authorization on the actual indices.

This PR moves the "allows remote indices" property to the indices request away from Security code,
with the goal that it's useful to non-security code as well (rather than duplicating it in the other places).

### CODE REVIEW

**Comment by albertzaharovits** [comment]
@elasticmachine test this please

**Comment by mark-vieira** [comment]
@elasticmachine retest this please

**Comment by mark-vieira** [comment]
@elasticmachine update branch

**Comment by mark-vieira** [comment]
@elasticmachine retest this please

**Comment by mark-vieira** [comment]
@elasticmachine run elasticsearch-ci/docs

**Pull request merged**
