### PR TITLE
lang-expressions should use DoubleValuesSource

### PR DESCRIPTION
**Pull request by romseygeek**
DoubleValuesSource is the type-safe replacement for ValueSource in the lucene
core.  Most of elasticsearch has moved to use these, but lang-expressions is still
using the old version.  This commit migrates lang-expressions as well.

### CODE REVIEW

**Comment by romseygeek** [comment]
Note that this also means that we don't need to depend on `lucene-queries` here any more, but I'm not sure where that dependency is declared as it doesn't appear in the `build.gradle` for `lang-expressions`

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by rjernst** [comment]
> we don't need to depend on lucene-queries

This dependency is in `:server`.

**Review by jdconrad — APPROVED** [review]
LGTM too. Thanks for changing this.

**Pull request merged**
