### PR TITLE
Remove irrelevant nodeHotThreads comment above nodeUsage method in ClusterAdminClient

### PR DESCRIPTION
**Pull request by mushao999**
This PR remove the irrelevant `nodeHotThreads` comment above `nodeUsage` mehotd which was introduce by #24169.

### CODE REVIEW

**Comment by mushao999** [comment]
@colings86 @jaymode Please help to review this.

**Comment by mushao999** [comment]
@pquentin please help to review this

**Comment by mushao999** [comment]
Pinging @pquentin @elastic/es-distributed @elastic/es-docs

**Comment by mushao999** [comment]
Pinging @pquentin, please help to find an assignee, thanks

**Comment by mushao999** [comment]
Pinging @colings86 @jaymode , please help to reivew this.

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Comment by DaveCTurner** [comment]
@elasticmachine ok to test

**Comment by DaveCTurner** [comment]
@elasticmachine update branch

**Pull request merged**
