### PR TITLE
Record instead of Tuple for checkMisspelledPlugin

### PR DESCRIPTION
**Pull request by prdoyle**
I came across this and I wondered if we ought to be moving away from `Tuple`.

Do people consider this an improvement?

Really, records are just tuples with proper names for the components, plus they support primitive types.

### CODE REVIEW

**Comment by thecoop** [comment]
I'm not sure this adds much - if it was exposed outside the method, then definitely, but this is just an internal implementation detail. I'm in the middle, with a slight lean towards leave-as-is, given we use `Tuple` in plenty of other places too.

**Comment by ldematte** [comment]
I'm in the middle bit leaning slightly towards change-it :) because I really dislike Tuple, they are so opaque with their v1() and v2(). But in this case, the use is very local (you get them and immediately transform them), so they might be OK.

**Comment by prdoyle** [comment]
Agreed with @thecoop that this kind of change only makes sense if we also agree that `Tuple` is sort of deprecated and we start preferring records everywhere. If that's not a position we're willing to take, then this change doesn't make much sense on its own.

**Comment by rjernst** [comment]
> if we also agree that Tuple is sort of deprecated

Tuple is used _all over_ in ES. Deprecating that would be a large change on it's own. While I understand the desire for more meaningful names than v1/v2, I don't think such a change would be worthwhile, it's just noise. We can certainly use records as desired on newer code (and even change code in PluginsService/etc to use recoreds in place of Tuple). But mandating/aligning on replacing Tuple doesn't seem worth the time (maybe once we have Valhalla value types, but even then, Tuple could be made a value type).

**Pull request closed without merging**
