### PR TITLE
Update put-mapping.asciidoc

### PR DESCRIPTION
**Pull request by CharlesBunders**
Nothing was specifying it was the user mapping.

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by mayya-sharipova** [comment]
@CharlesBunders  Thanks for your contribution.
You rightly noticed that there is a disagreement between the code examples provided and the following texts that explain them.  
But the error is not in the code examples, you don't need to correct them. In fact, your corrections are wrong. 
If you want to resolve the disagreement, please correct the texts explaining the code examples.

**Review by mayya-sharipova — CHANGES_REQUESTED** [review]
You rightly noticed that there is a disagreement between the code examples provided and the following texts that explain them.
But the error is not in the code examples, you don't need to correct them. In fact, your corrections are wrong.
If you want to resolve the disagreement, please correct the texts explaining the code examples.

**Comment by CharlesBunders** [comment]
Why is _doc used?

If I was to perform what that section was intended (to my understanding) to be doing I would do:

`PUT twitter/user/_mapping <2>
{
  "user": {
    "properties": {
      "name": {
        "type": "text"
      }
    }
  }
}

PUT twitter/user/_mapping <3>
{
  "user": {
    "properties": {
      "email": {
        "type": "keyword"
      }
    }
  }
}
`

**Comment by mayya-sharipova** [comment]
@CharlesBunders  We are deprecating types in an  index. So in 6.x, an index can have a single type. It can be called `user` or any other name. `_doc` is a way for us to show that it will be deprecated eventually.
In `6.2`, you can use `user` to name a type. But I don't think that your syntax is correct. It should be `<indexname>/_mapping/<typename>`.  
Have you tried to run your requests against Elastic 6.2 before submitting a correction?

**Comment by CharlesBunders** [comment]
No, 5.6.3.

**Pull request closed without merging**
