### PR TITLE
TEST: Update settings should go through cluster state

### LINKED ISSUE #24491: Index service test suite should go through the system
I discovered this while working on inlining global checkpoints. The IndexServiceTests#testRescheduleAsyncFsync test failed on my branch. The idea behind this test is that we set the translog durability to async, index a document, and then busily check that the translog does not need to be synced. The expectation is that an async fsync task should fire and at some point fsync the translog. This test was passing on master, failing on my branch. It was passing on master for the wrong reason. The problem is that setting durability to async never stuck but were instead on request durability. Thus, a request fsync had already fired so it did not matter if an async fsync never fired. The details of exactly why are explained in cb46e97a046b61a20bc237b9d49fa30d2aef9edf. The reason this fails on my branch is because with inlining global checkpoints, the translog does indeed need another fsync after the replication operation completes because we persist the global checkpoint into the translog checkpoint. Since we were stuck on request durability, this fsync never fired and the test failed.

I pushed cb46e97a046b61a20bc237b9d49fa30d2aef9edf to fix this test so the test goes through the system and the async durability setting sticks. There are other tests in this test suite doing the same thing. I think that should be updated, but I would rather spend my immediate time on inlining global checkpoints so this issue is a placeholder for addressing these tests in the future.

### PR DESCRIPTION
**Pull request by dnhatn**
Today we update index settings directly via IndexService instead of the
cluster state in IndexServiceTests. However, those changes will be lost
if there is a cluster state update. In general, we should update index
settings via client and limit the direct usage in only special tests.

This commit replaces direct usages by the updateSettings API.

Closes #24491

### CODE REVIEW

**Comment by dnhatn** [comment]
@jasontedor Can you please have a look? I am unable to make a review request. Thank you!

**Review by bleskes — APPROVED** [review]
Thx nhat.

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by dnhatn** [comment]
@elasticmachine test this please.

**Comment by dnhatn** [comment]
Thanks @bleskes and @jasontedor for reviewing!

@jasontedor Your commit message at https://github.com/elastic/elasticsearch/commit/cb46e97a046b61a20bc237b9d49fa30d2aef9edf is really helpful 💯.

**Pull request merged**
