### PR TITLE
DOCS Auditing search queries

### PR DESCRIPTION
**Pull request by albertzaharovits**
This documents how to include the search queries in the audit log.

There is a catch, that even if enabling `emit_request_body`, which should
output queries included in request bodies, search queries were not output
because, implicitly, no REST layer audit event type was included.

This folk knowledge is herein imprinted.

### CODE REVIEW

**Review by lcawl — APPROVED** [review]
I edited the page and verified it by building the Stack Overview.
LGTM

**Comment by albertzaharovits** [comment]
Thank you Lisa!

**Review by jaymode — APPROVED** [review]
LGTM

**Comment by albertzaharovits** [comment]
Thank you Jay.

_trying the build once more:_
_run gradle build tests_

**Comment by albertzaharovits** [comment]
run gradle build tests

**Comment by albertzaharovits** [comment]
run gradle build tests

**Comment by albertzaharovits** [comment]
run gradle build tests

**Comment by albertzaharovits** [comment]
run gradle build tests

**Comment by albertzaharovits** [comment]
run gradle build tests

**Pull request merged**
