### PR TITLE
Fix wrong pipeline name in debug log

### PR DESCRIPTION
**Pull request by gaobinlong**
Relates to #58478.

When the ingest pipeline processes failed in bulk API, we can find a debug log which prints `failed to execute pipeline [_none] for document...`, the pipeline name is always `_none`. That's because  `pipeline` in `indexRequest` is set to `_none` when executing the ingest pipeline: https://github.com/elastic/elasticsearch/blob/cc3bd3974fac25c1deca4699a1a2129cc2f601ef/server/src/main/java/org/elasticsearch/ingest/IngestService.java#L366.

The main point of this PR is moving the logging to IngestService#executePipelines(), so we can get the real pipeline name when printing the debug log.

### CODE REVIEW

**Comment by danhermann** [comment]
@elasticmachine update branch

**Review by danhermann — APPROVED** [review]
Thanks, @gaobinlong. This looks good and I'll get it merged in.

**Comment by gaobinlong** [comment]
@danhermann, thanks for your review.

**Comment by danhermann** [comment]
@elasticmachine ok to test

**Comment by danhermann** [comment]
@elasticmachine update branch

**Comment by danhermann** [comment]
@elasticmachine update branch

**Comment by danhermann** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample-windows

**Pull request merged**
