### PR TITLE
Only ack index store deletion on data nodes

### PR DESCRIPTION
**Pull request by bleskes**
When an index is deleted we wait on all nodes to ack the delete. Data nodes are expected to both ack the remove of the index from their IndicesService and also the deletion of the store from disk. At the moment all nodes sends this ack which causes wrong counting on the master side. On top of this, we currently have an unneeded WARN message in the logs when client nodes try to acquire locks but do not have a data folder.

Relates to #9605

### CODE REVIEW

**Comment by bleskes** [comment]
@s1monw can you have a look?

**Comment by s1monw** [comment]
if we don't need to ack do we need to fire up the threads at all? can we do the check earlier?

**Comment by bleskes** [comment]
a very valid point. Changing.

**Comment by s1monw** [comment]
LGTM

**Comment by bleskes** [comment]
thx

**Pull request closed without merging**
