### PR TITLE
SQL: Fix classpath discovery on Java 10+

### PR DESCRIPTION
**Pull request by costin**
Makes  #40388 work on Java 10+

### CODE REVIEW

**Review by matriv — APPROVED** [review]
LGTM. Thx for the quick fix!

**Review by imotov — APPROVED** [review]
LGTM2. Thanks for the quick turnaround!

**Comment by costin** [comment]
run elasticsearch-ci/1  elasticsearch-ci/2 elasticsearch-ci/bwc elasticsearch-ci/default-ditro

**Comment by costin** [comment]
run elasticsearch-ci/2 
run elasticsearch-ci/bwc 
run elasticsearch-ci/default-ditro

**Comment by costin** [comment]
run elasticsearch-ci/default-distro

**Review by astefan — APPROVED** [review]
LGTM

**Comment by costin** [comment]
run elasticsearch-ci/1

**Pull request merged**
