### PR TITLE
[ML] Improve uniqueness of result document IDs

### LINKED ISSUE #50613: [ML] Result document IDs are not sufficiently unique
* In order to ensure we don't get duplicate results if a job does the same work multiple times (for example after failing over from one node to another), our results documents have IDs generated from their contents, such that if two identical results are indexed the second will overwrite the first and we won't get a duplicate
* Since we cannot literally have the document ID be the whole result, because the document IDs are limited to 512 bytes and the result could contain more data than this, we create an ID using a formula that we thought was likely to avoid ID collisions for different results
  * In particular, since by/over/partition field values can be long, the document ID includes a combination of the hashes of these values, plus the total length - the assumption was that it would be unlikely for there to be a hash collision unless the total length was different
* Unfortunately, some by/over/partition values do produce hash collisions for identical total lengths of by/over/partition field values.  An example is:
  * by field value = L018, over field value = null, partition field value = 128
  * by field value = L017, over field value = null, partition field value = 228
  * Both produce a hash of -2073230751

More variation is needed in the document IDs.  However, before making the change an analysis of the possibilities for duplicate documents caused by the change is required.  We need to consider all the places where we're assuming that duplicate results will overwrite one another and the likelihood of occurrence.

The problem affects at least model plot, forecast and anomaly record results.  Other types of results, for example, influencer results, contain a hash of just one string.  We should consider consistency in the way IDs are created across the different types.

### PR DESCRIPTION
**Pull request by droberts195**
Switch from a 32 bit Java hash to a 128 bit Murmur hash for
creating document IDs from by/over/partition field values.
The 32 bit Java hash was not sufficiently unique, and could
produce identical numbers for relatively common combinations
of by/partition field values such as L018/128 and L017/228.

Fixes #50613

### CODE REVIEW

**Comment by benwtrent** [comment]
In the case of a job re-running from a snapshot, we delete results directly correct? And do not rely on the IDs to be the same between the two runs?

**Comment by droberts195** [comment]
> In the case of a job re-running from a snapshot, we delete results directly correct?

We do if it's an explicit revert with `delete_intervening_results` set to `true`.  If not then we try to start off from after the last observed input or result, which will generally mean we don't create duplicate results - see https://github.com/elastic/elasticsearch/blob/197d5e7768c2ac3fc75f27392f788c1e7f9e3cf5/x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/datafeed/DatafeedJob.java#L95

This latter scenario will always be the case during a failover from one node to another.

It is actually possible for a model plot document to exist that's more recent than the restart time.  This is because model plot documents are written before bucket documents - see https://github.com/elastic/ml-cpp/blob/a9c468cf8b991b8d30f1a9ba2846ff90edaa8bcc/lib/api/CAnomalyJob.cc#L626-L629

So in the worst case we'd persist some model plot documents that would get indexed due to a bulk request filling up, then the node would be killed before the corresponding bucket or data counts documents could be indexed, then the job would restart on a different node, redo the same bucket and we'd get duplicate model plot documents for one bucket.  This would only be a problem in the case where the old node was running a version before this fix and the new node was running a version after this fix.  I think it's probably worth tolerating this unlikely/single bucket problem to fix the problem of entire partitions never having any model plot.

We do explicit deletes in the case of interim results, so those won't be a problem - see https://github.com/elastic/elasticsearch/blob/5c3dd571a5126e84a2820d892fc63958f49fa91b/x-pack/plugin/ml/src/main/java/org/elasticsearch/xpack/ml/job/process/autodetect/output/AutodetectResultProcessor.java#L204-L208

**Review by benwtrent — COMMENTED** [review]
I think it would be nice to have a ID length worst case test where every possible value is at its configurable max. 

Looking at the maximum value possible for murmur hash bytes: `"170141183460469231722463931679029329919"` which is two `Long.MAX_VALUE` bytes. That as a length of UTF_8 bytes is: `39`.

I think we are way under the limit, but it would be nice for such a test to cover that extreme (and unlikely) case.

**Review by benwtrent — APPROVED** [review]

**Comment by droberts195** [comment]
> I think we are way under the limit, but it would be nice for such a test to cover that extreme

I added a test and we're under 200 bytes in total in the worst case.

**Pull request merged**
