### PR TITLE
add params properly when using wildcard

### LINKED ISSUE #8071: PathTrie wrongly adds params
For instance, PathTrie builds two tries: "/a/{x}/b", "/{y}/c/d".  While retrieving "/a/c/d", it breaks for the params are {x=c, y=a} instead of {y=a}. We should push params before retrieving next token and pop them if we have to use wildcard to retrieve again.

### PR DESCRIPTION
**Pull request by wy96f**
fix #8071

### CODE REVIEW

**Comment by colings86** [comment]
Sorry it's taken so long to reply on this. We are keen to get this merged in, would you mind [signing the Contributor Licence Agreement](http://www.elasticsearch.org/contributor-agreement/) so we can do a final review and merge

**Comment by colings86** [comment]
@wy96f sorry, I just noticed your comment above saying that you had signed it already.

**Comment by clintongormley** [comment]
CLA is signed.  @wy96f apologies for the delay

**Comment by clintongormley** [comment]
This has been hanging around for so long because the PathTrie code is so hairy that nobody wants to touch it...  This particular change doesn't seem to solve any bugs, but might it prevent future bugs?

@colings86 @javanna @jasontedor any thoughts about what we should do here?

**Comment by jasontedor** [comment]
> any thoughts about what we should do here?

@clintongormley I've left a note on linked issue to see if we can get a better understanding of what this is suppose to be addressing in Elasticsearch. At a minimum, this code will require a rebase on master (Guava is gone, for example), and the CLA check is failing but I'd like to understand if there is an actual bug in Elasticsearch that the contributor is trying to address before merging.

**Comment by clintongormley** [comment]
No further feedback.  Closing

**Comment by karmi** [comment]
Hi @wy96f, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/elasticsearch/pull/8072.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by karmi** [comment]
@wy96f Apologies for the comment above, this was a manual fault from some local testing...

**Pull request closed without merging**
