### PR TITLE
Reset failed allocation counter before executing routing commands

### PR DESCRIPTION
**Pull request by vigyasharma**
Reset failed allocation counter before executing allocation commands. 
Fixes Issue #39546

### CODE REVIEW

**Comment by henningandersen** [comment]
hi @vigyasharma  thanks for opening this PR. Would you mind signing our CLA before we take a closer look?

**Comment by vigyasharma** [comment]
Will do, thanks.

**Comment by DaveCTurner** [comment]
@vigyasharma this is still awaiting your acceptance of the CLA

**Comment by vigyasharma** [comment]
@DaveCTurner @henningandersen There's a custom CLA between my company and Elasticsearch. I mailed the signed agreement (a few days back), and am waiting on Elasticsearch to get added.

**Comment by DaveCTurner** [comment]
Ok thanks for the update @vigyasharma.

**Comment by vigyasharma** [comment]
@DaveCTurner Got added to CLA. PR checks have passed now.

**Review by DaveCTurner — CHANGES_REQUESTED** [review]
Test looks good, but I'm suspicious about having to create a new `RoutingAllocation` in `resetFailedAllocationCounter()`. I investigated further and see the problem is that ~all~ some of the routing commands incorrectly look at the (immutable) `RoutingTable` rather than the (mutable) `RoutingNodes`. I think this needs fixing first, then it'll no longer be necessary to recreate the `RoutingAllocation` like this.

**Comment by vigyasharma** [comment]
Thanks for reviewing @DaveCTurner. You're right, that is why I had to create RoutingAllocation again.

Allocation commands are currently using RoutingTable to get the relevant shard directly from `IndexShardRoutingTable`.  e.g. 
```java
// uses for routingTable() across commands
primaryShardRouting = allocation.routingTable().shardRoutingTable(index, shardId).primaryShard();
allocation.routingTable().shardRoutingTable(index, shardId).replicaShardsWithState(ShardRoutingState.UNASSIGNED);
```

From what I could find, the RoutingNodes counterpart for this would be to call `shards(Predicate <ShardRouting> predicate)`. This will however loop through all shards on all nodes every time. Is there a better way to get shards from RoutingNodes?

```java
public List<ShardRouting> shards(Predicate<ShardRouting> predicate) {
...
}
```

If not, is it really better than creating RoutingAllocation again?

**Comment by DaveCTurner** [comment]
> This will however loop through all shards on all nodes every time.

I don't really see the problem here. Can you elaborate?

> is it really better than creating RoutingAllocation again?

Yes, I think this is a bug in the routing commands. If you execute a sequence of commands then each command will ignore the results of the previous ones so that you cannot, for instance, reliably allocate all the replicas of a shard in a single API call.

**Comment by vigyasharma** [comment]
> I don't really see the problem here. Can you elaborate?

My concern was mainly around increased computation, as opposed to getting the shard directly from maps maintained in routing table.

>  If you execute a sequence of commands then each command will ignore the results of the previous ones so that you cannot, for instance, reliably allocate all the replicas of a shard in a single API call.

Yes, this is a bigger issue. Will modify commands to use RoutingNodes. We can't keep updating allocation after each command, that's not maintainable. Should this be a separate issue? (although I'll make the change in this PR itself)

**Comment by vigyasharma** [comment]
Interestingly, the `move` command [uses](https://github.com/elastic/elasticsearch/blob/f5200e34ad6c3614457b5fe6577b71268922c2a8/server/src/main/java/org/elasticsearch/cluster/routing/allocation/command/MoveAllocationCommand.java#L118-L125) routingNodes.

RoutingTable is only used by `AllocateEmptyPrimaryAllocationCommand`, `AllocateStalePrimaryAllocationCommand` and `AllocateReplicaAllocationCommand`. These commands do not have duplicate <node, shard> combinations since we can't have two copies of the same shard on one node (and hence don't need updated information). 

Was using RoutingTable here a conscious choice here then?

**Comment by vigyasharma** [comment]
> RoutingTable is only used by `AllocateEmptyPrimaryAllocationCommand`, `AllocateStalePrimaryAllocationCommand` and `AllocateReplicaAllocationCommand`. These commands do not have duplicate <node, shard> combinations since we can't have two copies of the same shard on one node (and hence don't need updated information).

I think this is not really isolated and can break in scenarios like `move -> allocateReplica` in the same API. We should just keep it simple by using mutable routing nodes everywhere.

**Comment by DaveCTurner** [comment]
> My concern was mainly around increased computation, as opposed to getting the shard directly from maps maintained in routing table.

I see, yes, I don't think it really matters. These commands only run rarely, and it doesn't take _that_ long to iterate across all the shards in a cluster even if there are thousands of them.

> Should this be a separate issue?

I think it'd make sense to open a separate PR for this, but there's no need to open an issue first.

> These commands do not have duplicate <node, shard> combinations since we can't have two copies of the same shard on one node (and hence don't need updated information).

I don't follow this reasoning. If you perform a sequence of commands then each command should perform its checks based on the results of earlier commands.

> Was using RoutingTable here a conscious choice here then?

It's hard to say. This code is over three years old and I can find no evidence either way.

**Comment by vigyasharma** [comment]
@DaveCTurner Raised [PR#42066](https://github.com/elastic/elasticsearch/pull/42066) to move allocation commands to use routing nodes. I'll update this PR once we have those changes in place.

**Comment by vigyasharma** [comment]
This branch's history got messed up in trying to rebase a remote branch. Creating a new PR on top of changes from master

**Comment by vigyasharma** [comment]
@DaveCTurner I've made changes to avoid creating RoutingAllocation on each counter reset. Raised a new PR (messed up history on this branch). Please see [PR#42658](https://github.com/elastic/elasticsearch/pull/42658)

**Comment by DaveCTurner** [comment]
Thanks. For future reference, it's better to `git merge master` rather than trying to rebase anything once you've opened a PR. Rebasing loses comments and reviews and other context which is important to preserve.

**Pull request closed without merging**
