### PR TITLE
Add PathHierarchy type back to path_hierarchy tokenizer for backward compatibility with 1.x

### PR DESCRIPTION
**Pull request by ywelsch**
Relates to #15756

### CODE REVIEW

**Comment by jpountz** [comment]
Is there a way that we could only support it for indices created before 2.0 to ensure that new indices will use the lowercase version?

**Comment by jpountz** [comment]
Maybe we could register a subclass of PathHierarchyTokenizerFactory whose constructor fails if the version in the index settings is >= 2.0? The error message could even point to the replacement to use?

**Comment by jpountz** [comment]
Hmm after all we will have to do it for others analysis components (eg. edgeNGram) so let's push it as-is and work on a migration path as part of #8988

**Comment by s1monw** [comment]
@ywelsch this went into 2.2 as well can you label it accordingly?

**Comment by ywelsch** [comment]
@s1monw done

**Pull request merged**
