### PR TITLE
Upgrade to Gradle 6.0

### LINKED ISSUE #49192: Upgrade to Gradle 6.0
Gradle 6.0 has been released and it contains some specific items that we want in order to implement some improvements in our build such as JDK 13 support, and [shared resources](https://docs.gradle.org/current/javadoc/org/gradle/api/execution/SharedResource.html).

There are a number of deprecations and incompatibilities with third-party plugins, namely the ospackage plugin that will have to be resolved.

### PR DESCRIPTION
**Pull request by mark-vieira**
This upgrade required a few significant changes. Firstly, the build
scan plugin has been renamed, and changed to be a Settings plugin rather
than a project plugin so the declaration of this has moved to our
settings.gradle file. Second, we were using a rather old version of the
Nebula ospackage plugin for building deb and rpm packages, the migraiton
to the latest version required some updates to get things working as
expected as we had some workarounds in place that are no longer
applicable with the latest bug fixes.

Closes #49192

### CODE REVIEW

**Comment by mark-vieira** [comment]
@elasticmachine run elasticsearch-ci/1

**Review by alpar-t — APPROVED** [review]
LGTM 

I would run PR checks a few times over for this one.

**Comment by mark-vieira** [comment]
Something is definitely funky with those test worker failures. I'm going to have to track that down before we merge this.

**Comment by mark-vieira** [comment]
@elasticmachine test this please

**Comment by mark-vieira** [comment]
Still running into issues with the Gradle daemon failing to get a connection to the test worker. Working with folks at Gradle to try and troubleshoot this.

**Comment by original-brownbear** [comment]
@mark-vieira I think we can add a "closes #49253" here as well? :) Gradle 6 should resolve any JDK 13 issues right?

**Comment by mark-vieira** [comment]
> @mark-vieira I think we can add a "closes #49253" here as well? :) Gradle 6 should resolve any JDK 13 issues right?

Not necessarily. Gradle 6.0 simply adds support for running the build with JDK 13 but we could still have test failures when using a JDK 13 test runtime. This PR isn't meant to specifically address those issues, simply to get us on the latest version and then take it from there.

**Comment by mark-vieira** [comment]
@jbaiera Heads up that I'm in the process of getting us on Gradle 6.0. It might be worth some experiments to see how elasticsearch-hadoop plays with Gradle 6.0 so we can coordinate and make sure we don't break stuff.

**Comment by mark-vieira** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by mark-vieira** [comment]
@elasticmachine update branch

**Comment by mark-vieira** [comment]
@elasticmachine run elasticsearch-ci/packaging-matrix

**Comment by mark-vieira** [comment]
@elasticmachine test this please

**Comment by mark-vieira** [comment]
@elasticmachine run elasticsearch-ci/packaging-matrix

**Comment by mark-vieira** [comment]
@elaslticmachine update branch

**Comment by mark-vieira** [comment]
@elasticmachine update branch

**Comment by mark-vieira** [comment]
@elasticmachine run elasticsearch-ci/packaging-matrix

**Pull request merged**
