### PR TITLE
Fix SearchableSnapshotActionIT.testConvertingSearchableSnapshotFromFullToPartial

### LINKED ISSUE #73706: [CI] SearchableSnapshotActionIT testConvertingSearchableSnapshotFromFullToPartial failing
It's the first failure in last 7 days. But the error message looks legit enough.

**Build scan:**
https://gradle-enterprise.elastic.co/s/kkeggcanhv3ks/tests/:x-pack:plugin:ilm:qa:multi-node:javaRestTest/org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT/testConvertingSearchableSnapshotFromFullToPartial

**Reproduction line:**
`./gradlew ':x-pack:plugin:ilm:qa:multi-node:javaRestTest' --tests "org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT.testConvertingSearchableSnapshotFromFullToPartial" -Dtests.seed=BA9C66979C640768 -Dtests.locale=en-GB -Dtests.timezone=America/Danmarkshavn -Druntime.java=11`

**Applicable branches:**
master

**Reproduces locally?:**
No

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.ilm.actions.SearchableSnapshotActionIT&tests.test=testConvertingSearchableSnapshotFromFullToPartial

**Failure excerpt:**
```
org.elasticsearch.client.ResponseException: method [DELETE], host [http://[::1]:43375], URI [restored-myindex-lfqc], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"The provided expression [restored-myindex-lfqc] matches an alias, specify the corresponding concrete indices instead."}],"type":"illegal_argument_exception","reason":"The provided expression [restored-myindex-lfqc] matches an alias, specify the corresponding concrete indices instead."},"status":400}

  at __randomizedtesting.SeedInfo.seed([BA9C66979C640768:E9794DE67AE7774F]:0)
  at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:330)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296)
  at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270)
  at org.elasticsearch.test.rest.ESRestTestCase.wipeSearchableSnapshotsIndices(ESRestTestCase.java:815)
  at org.elasticsearch.test.rest.ESRestTestCase.wipeCluster(ESRestTestCase.java:574)
  at org.elasticsearch.test.rest.ESRestTestCase.cleanUpCluster(ESRestTestCase.java:342)
  at jdk.internal.reflect.GeneratedMethodAccessor13.invoke(null:-1)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:566)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:1004)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
  at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
  at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:834)

```

### PR DESCRIPTION
**Pull request by tlrx**
In #73650 I modified `EsRestCase` in order to delete searchable snapshots indices in the after test clean up logic. This deletion should occur before repositories are deleted, otherwise the after test logic would fail now we prevent to delete repositories that are still used by searchable snapshots indices (#73714).

The deletion of searchable snapshots indices after test sometimes fail in `testConvertingSearchableSnapshotFromFullToPartial` with the error:
> The provided expression [restored-myindex-afys] matches an alias, specify the corresponding concrete indices instead

I suspect that this failure can happen if the after test logic correctly found a searchable snapshot index to delete but that index was deleted and converted to an alias in the meanwhile, by the last step of the ILM searchable snapshot action for frozen phase. This last step is asynchronous so I think the frozen phase can happen as completed but there are still the alias swap request in-flight.

So I added an assertBusy() at the end of the step to verify that the index has been deleted and converted to an alias, so that the after test clean up logic won't pick the searchable snapshot index as it should be already deleted at that time.

Closes #73706

### CODE REVIEW

**Comment by tlrx** [comment]
@elasticmachine run elasticsearch-ci/packaging-tests-windows-sample (unrelated [failure](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+pull-request/job/elastic+elasticsearch+master+pull-request+packaging-tests-windows-sample/1182/))

**Review by andreidan — COMMENTED** [review]
Thanks for working on this @tlrx 

I don't think the situation you're describing can happen though. The test waits for the frozen phase to move to the `complete` step and in the `swap-aliases` step we only move forward once the response is received - so even though it is an async step, ILM waits for the response. 

I wonder if the flakiness is due to the fact that the response might not be acked by all nodes - is this logging present in the logs? https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/SwapAliasesAndDeleteSourceIndexStep.java#L94 
Could it be that the metadata call that reads the indices is going to a non-master node? (one that didn't yet see the alias swap CS update)

**Comment by tlrx** [comment]
> I wonder if the flakiness is due to the fact that the response might not be acked by all nodes - is this logging present in the logs? https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/SwapAliasesAndDeleteSourceIndexStep.java#L94

I've checked some CI failures logs and I did not find this specific warning.

> Could it be that the metadata call that reads the indices is going to a non-master node? (one that didn't yet see the alias swap CS update)

The cluster state metadata read should be executed on the master node (ie, `local` is `false`) so it should see the latest committed state.


> I don't think the situation you're describing can happen though. The test waits for the frozen phase to move to the `complete` step and in the `swap-aliases` step we only move forward once the response is received - so even though it is an async step, ILM waits for the response.

I looked at this again this morning and I still think that the situation I described can happen but not for the reason I gave in the description of the PR :) I initially thought that the in-flight alias swap could happen because it was asynchronously executed. But after looking at the code of `SearchableSnapshotAction` again I noticed those [lines](
https://github.com/elastic/elasticsearch/blob/63012c8a40742829806b44cb6577b05d9ab25a83/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ilm/SearchableSnapshotAction.java#L217-L218):

```java
 CopyExecutionStateStep copyMetadataStep = new CopyExecutionStateStep(copyMetadataKey, copyLifecyclePolicySettingKey,
      (index, executionState) -> getRestoredIndexPrefix(copyMetadataKey) + index, nextStepKey);
```

And I think this will update the `partial-restored-myindex-` as completed in the frozen phase in the index metadata while the alias swap is not yet executed. WDYT?

**Review by dakrone — APPROVED** [review]
Okay, thanks for the explanation @tlrx, I was able to walk through the execution and see how this can happen. I think adding the assertion is an okay way of waiting here

**Review by andreidan — APPROVED** [review]
Great catch @tlrx Thanks for fixing this

**Comment by tlrx** [comment]
Thanks Andrei and Lee!

**Pull request merged**
