### PR TITLE
rpm uses non-portable `--system` flag to `useradd`

### PR DESCRIPTION
**Pull request by girirajsharma**
This PR provides a fix for https://github.com/elastic/elasticsearch/issues/14211

### CODE REVIEW

**Comment by dakrone** [comment]
@nik9000 I remember we spoke about the `-r` versus `--system` for older debian systems, do you remember what we said?

**Comment by nik9000** [comment]
@dakrone I don't remember. Sorry!

**Comment by dakrone** [comment]
As far as I could tell this is legitimate with older versions. We do have vagrant tests so I am going to merge this for the 5.0 release.

**Comment by Roguebantha** [comment]
Glad to see this is getting fixed. Is it possible that we could fix this for 2.3.4 as well?

**Comment by ahelten** [comment]
Yes, please get this in 2.3.4 as well! Thank you.

**Pull request merged**
