### PR TITLE
Refactor RollupAction to leverage a shard-based indexing strategy

### PR DESCRIPTION
**Pull request by talevy**
Note to reviewers

**TODO items for PR after merging**

- [ ] validate thread pool configuration
- [ ] validate directory usage
- [ ] keep track of memory usage in circuit-breaker
- [ ] check file creation against watermarks

---

This commit refactors the rollup action in order to execute on a per shard basis.
Each shard is responsible for sending its local buckets to the target rollup index.
The shard action is executed in the rollup thread pool in order to limit the
number of shards that can rollup concurrently per node.
Buckets are computed on the fly using the index searcher and they are sorted
using a compressed offline sorter.

This commit also removes the rollup thread pool usage in the RollupAsyncIndexer that is used by
the legacy rollup and transforms. All actions performed by this indexer are asynchronous so
using the generic thread pool to fire search and bulk requests is ok.

This commit also adds RollupActionSingleNodeTests for verifying the behavior of the indexer.

This commit also has various other small cleanup tasks of the config classes

### CODE REVIEW

**Comment by talevy** [comment]
run elasticsearch-ci/2

**Comment by jrodewig** [comment]
FYI I pushed 19bed12391b560dd60ccc57505814e8b816b88ed so we can preserve the current field names in the docs snippet.

**Comment by talevy** [comment]
thanks @jrodewig

**Review by csoulios — APPROVED** [review]
LGTM!
That's indeed huge improvement to the rollup action.

**Pull request merged**
