### PR TITLE
Remove close method in PageCacheRecycler/Recycler

### LINKED ISSUE #41683: [CI] ConcurrentModificationException in DequeRecycler.close
The error happened in the `afterClass` method in `IPHostnameVerificationTests`, I doubt it is related to the test

```
java.util.ConcurrentModificationException
	at __randomizedtesting.SeedInfo.seed([26CFB3C362D0C58B]:0)
	at java.base/java.util.ArrayDeque.nonNullElementAt(ArrayDeque.java:271)
	at java.base/java.util.ArrayDeque$DeqIterator.next(ArrayDeque.java:701)
	at org.elasticsearch.common.recycler.DequeRecycler.close(DequeRecycler.java:42)
	at org.elasticsearch.common.recycler.FilterRecycler.close(FilterRecycler.java:39)
	at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:103)
	at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:85)
	at org.elasticsearch.common.lease.Releasables.close(Releasables.java:36)
	at org.elasticsearch.common.lease.Releasables.close(Releasables.java:46)
	at org.elasticsearch.common.lease.Releasables.close(Releasables.java:67)
	at org.elasticsearch.common.lease.Releasables.close(Releasables.java:75)
	at org.elasticsearch.common.util.PageCacheRecycler.close(PageCacheRecycler.java:78)
	at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:103)
	at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:85)
	at org.elasticsearch.node.Node.close(Node.java:852)
	at org.elasticsearch.test.InternalTestCluster$NodeAndClient.close(InternalTestCluster.java:995)
	at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:103)
	at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:85)
	at org.elasticsearch.test.InternalTestCluster.close(InternalTestCluster.java:816)
	at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:103)
	at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:85)
	at org.elasticsearch.test.ESIntegTestCase.clearClusters(ESIntegTestCase.java:541)
	at org.elasticsearch.test.ESIntegTestCase.afterClass(ESIntegTestCase.java:2184)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:901)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:368)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-unix-compatibility/os=ubuntu-18.04&&immutable/364/console

Does not reproduce and not a lot to work with sorry
```
./gradlew :x-pack:plugin:security:test --tests "org.elasticsearch.xpack.security.transport.netty4.IPHostnameVerificationTests.null" \
  -Dtests.seed=26CFB3C362D0C58B \
  -Dtests.security.manager=true \
  -Dtests.locale=en-US \
  -Dtests.timezone=Etc/UTC \
  -Dcompiler.java=12 \
  -Druntime.java=11
``` 

Note the repo command lists the test `IPHostnameVerificationTests.null`, null is not a test this must be a result of the failure occurring in the after class method

### PR DESCRIPTION
**Pull request by jaymode**
The changes in #39317 brought to light some concurrency issues in the
close method of Recyclers as we do not wait for threads running in the
threadpool to be finished prior to the closing of the PageCacheRecycler
and the Recyclers that are used internally. #41695 was opened to
address the concurrent close issues but upon review, the closing of
these classes is not really needed as the instances should be become
available for garbage collection once there is no longer a reference to
the closed node.

Closes #41683

### CODE REVIEW

**Comment by jpountz** [comment]
There are some unrelated changes, maybe due to the recent force-push, can you undo them? I looked at the commit about removing close and it looks good at first sight.

**Comment by jaymode** [comment]
> There are some unrelated changes, maybe due to the recent force-push, can you undo them

Done. It was from the force push

**Comment by jaymode** [comment]
@elasticmachine run elasticsearch-ci/1

**Review by jpountz — APPROVED** [review]
Thanks @jaymode !

**Pull request merged**
