### PR TITLE
Correct version on repository-hdfs Guava dependency

### PR DESCRIPTION
**Pull request by jasontedor**
This commit sets the version on the repository-hdfs Guava dependency to version 11.0.2. This change is made to align the version here with the version that is [defined in the POM for Hadoop 2.7.1](https://github.com/apache/hadoop/blob/release-2.7.1/hadoop-project/pom.xml#L396-L400), the version of Hadoop that the repository-hdfs plugin is based on. See [HADOOP-10101](https://issues.apache.org/jira/browse/HADOOP-10101) and [HADOOP-11319](https://issues.apache.org/jira/browse/HADOOP-11319) for the ridiculous history of trying to upgrade Guava past this version in the Hadoop project.

### CODE REVIEW

**Comment by jasontedor** [comment]
I have personally seen trouble arise when trying to use a different version of Guava with Hadoop than the version specified in the [Hadoop POM](https://github.com/apache/hadoop/blob/release-2.7.1/hadoop-project/pom.xml#L396-L400).

**Review by rjernst — APPROVED** [review]
I think the 16.0.1 originally came from when we had transitive deps, which caused apache curator to be included, and which forces a resolve to 16.0.1.  Downgrading the version seems fine to me.

**Comment by jbaiera** [comment]
LGTM - "Guava version mismatches" are a leading cause of Hadoop related injuries.

**Review by jbaiera — APPROVED** [review]
Approving explicitly instead of just leaving a comment...

**Comment by jasontedor** [comment]
Thanks @jbaiera and @rjernst.

**Pull request merged**
