### PR TITLE
Remove setting index.optimize_auto_generated_id (#27583)

### LINKED ISSUE #27583: Remove `index.optimize_auto_generated_id`
We are happy with auto-ID optimization and we can now remove the `index.optimize_auto_generated_id` setting.

### PR DESCRIPTION
**Pull request by liketic**
Closes #27583

### CODE REVIEW

**Review by jasontedor — CHANGES_REQUESTED** [review]
I am pretty sure this is not enough. This setting can be on indices created in 6.x and we will support them in 7.x.

**Comment by s1monw** [comment]
@jasontedor why can't we remove it? it will just be archived since you never pushed https://github.com/elastic/elasticsearch/pull/26995 maybe I miss something

**Comment by s1monw** [comment]
@elasticmachine ok to test

**Comment by liketic** [comment]
Thanks for your review. I can address @jasontedor 's comments by deprecating the setting `index.optimize_auto_generated_id` and reject it for 7.x instead if needed. 👍

**Comment by liketic** [comment]
Hi @jasontedor Shall I update the PR by deprecating the setting? 👍  Thanks very much!

**Comment by jasontedor** [comment]
@liketic Yes, here is what we need to do:
 - deprecate in 6.x (one PR)
 - prevent the ability to modify this setting on indices created since 7.0.0 (another PR)
 - remove this setting completely in 8.0.0 (this PR)

**Comment by liketic** [comment]
Thanks @jasontedor . I opened #28862 for the first one.

**Comment by liketic** [comment]
And #28895 for the second one.

**Comment by jasontedor** [comment]
@liketic Now that 7.0 and 7.x are branched from master and #28895 is integrated, we can get this change in. Can you bring this change up to date with the master branch?

**Comment by liketic** [comment]
@jasontedor Please review again.

**Comment by jasontedor** [comment]
@elasticmachine test this please

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by jasontedor** [comment]
Thanks @liketic.

**Pull request merged**
