### PR TITLE
Fixing typo in request method of 7.X stats documentation

### PR DESCRIPTION
**Pull request by AngelaFabregues**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by AngelaFabregues** [comment]
Contributor Agreement Signed

**Comment by AngelaFabregues** [comment]
Done

**Comment by nik9000** [comment]
The search API works for either GET or POST.

**Comment by AngelaFabregues** [comment]
True, but it has no sense for POST. It is better to use GET in the documentation. Using POST looks like it is wrong.

**Comment by jrodewig** [comment]
Thanks for your suggestion @AngelaFabregues.

I took a quick inventory of our docs, comparing instances of `POST .*?_search` vs. `GET .*?_search`. `POST` is used 206 times (~27%  of `_search` API examples). `GET` is used 567 times (~73% of `_search` API examples).

While I agree that the `GET` verb is a bit more intuitive, `POST` is still a supported http method for the `_search` API.

I don't see much benefit in changing this particular example or changing our examples across the board.
I'm going to close this PR, but thank you again for contribution. Please feel free to submit other changes in the future.

**Pull request closed without merging**
