### PR TITLE
Add a template parameter to override auto_create_index value

### LINKED ISSUE #20640: Replace `action.auto_create_index` with a template setting
In https://github.com/elastic/elasticsearch/issues/9359 we discussed the possibility of extending the `action.auto_create_index` setting to automatically recognise index names which match templates, and to allow those to be auto-created without having to maintain both the template and the setting.

In FixitFriday we came up with a better solution:
- Remove the `action.auto_create_index` setting
- Add an `auto_create_index` setting to index templates - if true, then an index can be auto-created
- Ship with a default match `*` index with `auto_create_index: true` - this can be overridden by the user
- If multiple templates match, the `auto_create_index` setting is merged just like all other template settings - the highest `order` wins

When upgrading, the user will see an exception if they set `action.auto_create_index` and will need to update their templates to reflect the same logic.

Possibly, we could add a deprecation period where the `action.auto_create_index` setting continues to work, but also accepts a `_template` value which switches to use the template-based logic instead.

### PR DESCRIPTION
**Pull request by pugnascotia**
Backport of #61858.

Closes #20640.

This PR introduces a new parameter to v2 templates, `allow_auto_create`,
which allows templates to override the cluster setting `auto_create_index`.
Notes:

   * `AutoCreateIndex` now looks for a matching v2 template, and if its
     `allow_auto_create` setting is true, it overrides the usual logic.
   * `TransportBulkAction` previously used `AutoCreateIndex` to check
     whether missing indices should be created. We now rely on
     `AutoCreateAction`, which was already differentiating between creating
     indices and creating data streams.  I've updated `AutoCreateAction` to
     use `AutoCreateIndex`. Data streams are also influenced by
     `allow_auto_create`, in that their default auto-create behaviour can
     be disabled with this setting.
   * Most of the Java file changes are due to introducing an extra
     constructor parameter to `ComposableIndexTemplate`.
   * I've added the new setting to various x-pack templates
   * I added a YAML test to check that watches can be created even when
     `auto_create_index` is `false`.

### CODE REVIEW

**Comment by pugnascotia** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by pugnascotia** [comment]
@elasticmachine update branch

**Comment by pugnascotia** [comment]
@elasticmachine update branch

**Review by martijnvg — APPROVED** [review]
LGTM 👍

**Pull request merged**
