### PR TITLE
[DOCS] Add 'Troubleshooting an unstable cluster' to nav

### PR DESCRIPTION
**Pull request by abdonpijpelink**
Adds 'Troubleshooting an unstable cluster' to the 'Troubleshooting' navigation, making it easier to find. The content is also duplicated at its original location (https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-fault-detection.html#cluster-fault-detection-troubleshooting), so any incoming links won't break.

### CODE REVIEW

**Review by jrodewig — APPROVED** [review]

**Review by DaveCTurner — CHANGES_REQUESTED** [review]
I'm going to push a commit which adjusts the links emitted in logs etc, bear with me a sec.

**Comment by DaveCTurner** [comment]
Ah wait that won't work when backported. I'll open a separate PR to do that just in `main`.

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Comment by abdonpijpelink** [comment]
FWIW, this PR doesn't change the existing docs location. Those will continue to exist. This will just introduce an additional location where these docs are published.

**Comment by DaveCTurner** [comment]
Yep, that's great, there's lots of links to the old location in existence already. But we may as well start using the new location where possible.

**Pull request merged**
