### PR TITLE
Use unique ports per test worker

### PR DESCRIPTION
**Pull request by ywelsch**
A recent PR [to replace the randomized testing task by Gradle's test task](https://github.com/elastic/elasticsearch/pull/40978) broke a property used by our tests to distinguish between different parallel test processes and allocate separate port ranges for those parallel JVMs so that the tests would not communicate with each other. This has caused failures like https://github.com/elastic/elasticsearch/issues/41067 where tests from different JVMs are now interacting with each other.

As tests are now executed with the regular Gradle runner, this PR now switches to the logic that recognizes different test processes with the help of the `org.gradle.test.worker` system property, which is unique for each process, see https://docs.gradle.org/current/userguide/java_testing.html

### CODE REVIEW

**Review by henningandersen — APPROVED** [review]
LGTM

**Review by rjernst — COMMENTED** [review]
Great find! I wonder if we could fail if we can't find this property? If gradle changes something, we should fail fast instead of silently going on like we have for these months since moving the runner from randomized testing.

**Comment by ywelsch** [comment]
> I wonder if we could fail if we can't find this property?

I've added testing for this now. As I wasn't exactly sure where to put what, please have a look and let me know what you think.

**Comment by rjernst** [comment]
I don't think we should care about the tests.gradle sysprops. Iirc we set that ourselves. Why couldn't we error if the sysprop you are checking for the gradle worker doesn't exist?

**Comment by ywelsch** [comment]
> I don't think we should care about the tests.gradle sysprops. Iirc we set that ourselves.

alright, I missed that.

> Why couldn't we error if the sysprop you are checking for the gradle worker doesn't exist?

We still want to be able to run tests from the IDE. If we always require `org.gradle.test.worker`, that's going to be a pain.

**Review by alpar-t — APPROVED** [review]
LGTM 
Great find !

**Comment by ywelsch** [comment]
I forgot to say here that the credits go to @henningandersen. He pointed me to this while looking at #43970.

**Comment by mark-vieira** [comment]
> As tests are now executed with the regular Gradle runner, this PR now switches to the logic that recognizes different test processes with the help of the org.gradle.test.worker system property, which is unique for each process, see https://docs.gradle.org/current/userguide/java_testing.html

This is awesome. Great find indeed. I had no idea that Gradle injected that system property into tests.

**Pull request merged**
