### PR TITLE
Cleanup vagrant setup

### PR DESCRIPTION
**Pull request by rjernst**
Though bats tests were recently removed, there remains a few unnecessary
setups needed for those tests in our vagrant files, as well as CI setup.
Additionally, we no longer rely on the vagrant images setting a
JAVA_HOME, instead relying on DistroTestPlugin to pull the appropriate
jdk when testing with no-jdk distributions.

### CODE REVIEW

**Comment by rjernst** [comment]
@elasticmachine run elasticsearch-ci/default-distro

**Review by pugnascotia — APPROVED** [review]

**Review by mark-vieira — APPROVED** [review]
LGTM

**Comment by rjernst** [comment]
@elasticmachine run elasticsearch-ci/packaging-windows

**Comment by rjernst** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by rjernst** [comment]
@elasticmachine run elasticsearch-ci/2

**Pull request merged**
