### PR TITLE
Move runtime fields classes into common packages

### PR DESCRIPTION
**Pull request by romseygeek**
Runtime fields currently live in their own java package.  This is really
a leftover from when they were in their own module; now that they are 
in core they should instead live in the common packages for classes of
their kind.

This commit makes the following moves:
`org.elasticsearch.runtimefields.mapper` => `org.elasticsearch.index.mapper`
`org.elasticsearch.runtimefields.fielddata` => `org.elasticsearch.index.fielddata`
`org.elasticsearch.runtimefields.query` => `org.elasticsearch.search.runtime`

### CODE REVIEW

**Review by javanna — APPROVED** [review]
LGTM, one question I have is whether the FieldScript classes deserve their own package, they are shared between field types and queries. Not too sure.

**Comment by romseygeek** [comment]
> whether the FieldScript classes deserve their own package

Maybe they should go into `org.elasticsearch.script` along with sort scripts and similarity scripts, etc?

**Comment by javanna** [comment]
> Maybe they should go into org.elasticsearch.script along with sort scripts and similarity scripts, etc?

Yes, shall we also rename them to e.g. LongRuntimeFieldScript or is it overkill?

**Comment by romseygeek** [comment]
> Yes, shall we also rename them to e.g. LongRuntimeFieldScript or is it overkill?

We decided against this, as they're going to be used at index time as well, so `XFieldScript` is descriptive enough.

**Pull request merged**
