### PR TITLE
Mark Component template APIs as experimental

### PR DESCRIPTION
**Pull request by russcam**
This commit marks the Component template APIs as experimental.

### CODE REVIEW

**Comment by dakrone** [comment]
I think this is missing the simulate APIs? `indices.simulate_template` and `indices.simulate_index_template`

**Comment by russcam** [comment]
> I think this is missing the simulate APIs? indices.simulate_template and indices.simulate_index_template

I didn't know if these also needed to be marked experimental. I can update this PR for these. This PR will need to be ported to 7.x and 7.8 I think too, as `indices.simulate_index_template` is marked `stable` in 7.8:

https://github.com/elastic/elasticsearch/blob/202a15e8c6168c9ab7cb988afbf01b7f774b46a5/rest-api-spec/src/main/resources/rest-api-spec/api/indices.simulate_index_template.json#L7

**Comment by russcam** [comment]
@dakrone should it include all the `indices.*_index_template` APIs?

**Comment by dakrone** [comment]
> @dakrone should it include all the `indices.*_index_template` APIs?

Yep.

**Review by dakrone — APPROVED** [review]
LGTM

**Comment by russcam** [comment]
ported to 7.x and 7.8

**Pull request merged**
