### PR TITLE
Build: Merge xpack checkstyle config into core

### PR DESCRIPTION
**Pull request by nik9000**
Merges the xpack checkstyle_suppressions.xml file into the core
checkstyle_suppressions.xml file. We needed two files in the past
because we had two repositories. Now that we have one we can use just
one.

### CODE REVIEW

**Review by rjernst — APPROVED** [review]
LGTM

**Review by jasontedor — CHANGES_REQUESTED** [review]
This list is so short, we could conceivably clean these up and remove the suppressions rather than moving them to core where they will be lost? At least then a major part of our codebase (x-pack) would be free of suppressions?

**Comment by nik9000** [comment]
> This list is so short, we could conceivably clean these up and remove the suppressions rather than moving them to core where they will be lost?

I'll check.

**Comment by nik9000** [comment]
> I'll check.

Done.

**Review by jasontedor — APPROVED** [review]
That's awesome! LGTM.

**Comment by nik9000** [comment]
> That's awesome! LGTM.

I am, indeed, awesome.

**Comment by nik9000** [comment]
Thanks for reviewing @rjernst and @jasontedor .

**Pull request merged**
