### PR TITLE
Fix DLS using runtime fields and synthetic source

### PR DESCRIPTION
**Pull request by original-brownbear**
Somewhat of a tortured test but applying the same fix from #112260 to synthetic source which was running into the same bug as a stored field source.

### CODE REVIEW

**Review by javanna — APPROVED** [review]
LGTM

**Comment by original-brownbear** [comment]
Thanks Luca!

**Review by kkrik-es — APPROVED** [review]
Thanks!

**Comment by original-brownbear** [comment]
Thanks all!

**Pull request merged**
