### PR TITLE
Restore behavior for force parameter

### PR DESCRIPTION
**Pull request by jkakavas**
Turns out that the behavior of `-f` for the `add` and `add-file` sub
commands where it would also forcibly create the keystore if it
didn't exist, was by design - although undocumented.
This change restores that behavior auto-creating a keystore that
is not password protected if the force flag is used. The force
OptionSpec is moved to the BaseKeyStoreCommand as we will presumably
want to maintain the same behavior in any other command that takes
a force option

### CODE REVIEW

**Comment by jkakavas** [comment]
```

* What went wrong:
--
Execution failed for task ':qa:vagrant:vagrantCentos7#batsPackagingTest'.
> Process 'vagrant [ssh, centos-7, --command, export SYSTEM_JAVA_HOME="/elasticsearch/build/jdks/openjdk-11.0.2_linux"; cd $PACKAGING_ARCHIVES && sudo bats --tap $BATS_TESTS/*.bats]' finished with non-zero exit value 255
```

@elasticmachine run elasticsearch-ci/packaging-sample

**Comment by jkakavas** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample

**Review by rjernst — APPROVED** [review]
We originally had these commands fail if the keystore didn't exist, but added this behavior to make it easier on users (see https://github.com/elastic/elasticsearch/pull/26126). But that was before we had the keystore automatically created on package installation. We can certainly revisit that decision. My problem with the behavior introduced by your recent change is -f is supposed to be something for preventing user interaction. Perhaps we should discuss whether the keystore not existing should simply be an error now? I'm fine either with that discussion or this PR.

LGTM.

**Comment by jkakavas** [comment]
> My problem with the behavior introduced by your recent change is -f is supposed to be something for preventing user interaction. Perhaps we should discuss whether the keystore not existing should simply be an error now? 

Understood. I believe it's more important to not break users current setups and I'd be really surprised if someone isn't using `elasticsearch=keystore add -f something` now in order to a) create the keystore and b) set `something` in a script. We could have this discussion again for 8.0 and do a breaking change there? I'll go ahead and merge this.

**Pull request merged**
