### PR TITLE
Unmute HeapAttack#testHugeManyConcat

### PR DESCRIPTION
**Pull request by dnhatn**
The heap attack recent failures are because of #104240. Analyzing 2000 fields took more than 5 minutes in CI. With the fix in #104246, we can enable this test now.

Relates #104240

### CODE REVIEW

**Review by nik9000 — APPROVED** [review]
LGTM.

I'd love to fix the analyzer, but that's a problem for another time.

**Comment by dnhatn** [comment]
> I'd love to fix the analyzer, but that's a problem for another time.

Yes, I will take a look tomorrow morning if I come up with a quick fix. Otherwise, we will leave with this for sometime.

**Comment by dnhatn** [comment]
@nik9000 I have opened https://github.com/elastic/elasticsearch/pull/104246 to fix the slow analyzer.

**Comment by dnhatn** [comment]
@nik9000 I have restored the number of fields. This pull request now simply unmutes `testHugeManyConcat`. I have also updated the title and description of the PR.

**Pull request merged**
