### PR TITLE
[DOCS] Remove approximate document counts example from term agg docs

### LINKED ISSUE #52377: [DOCS] Terms agg doc counts are more precise than documented.
The terms aggregation docs include a [_Document count are approximate_](https://www.elastic.co/guide/en/elasticsearch/reference/master/search-aggregations-bucket-terms-aggregation.html#search-aggregations-bucket-terms-aggregation-approximate-counts) section.

When [reproduced on 6.8 or 7.x](https://gist.github.com/geekpete/38c06b2eaf2745c3b7312d329acb01fd), the actual results are more precise than documented in last table and paragraphs of the section.

### Steps to reproduce
https://gist.github.com/geekpete/38c06b2eaf2745c3b7312d329acb01fd

Thanks to @geekpete for raising and putting together the reproduction steps.

### PR DESCRIPTION
**Pull request by abprash**
Resolves #52377

### CODE REVIEW

**Comment by abprash** [comment]
This is my first PR to ElasticSearch.
This resolves https://github.com/elastic/elasticsearch/issues/52377

**Comment by jrodewig** [comment]
@elasticmachine test this please

**Review by jrodewig — CHANGES_REQUESTED** [review]
Thanks for putting this together @abprash. However, I wonder if it even makes sense to include this example anymore as it's not demonstrating that document counts are approximate.

It may be more appropriate to remove the "Document counts are approximate" section entirely or the example in the section following this text:

> This is because each shard provides its own view of what the ordered list of terms should be and these are combined to give a final view. Consider the following scenario:

@elastic/es-analytics-geo Do any of you have an insight into why the document counts no longer seem approximate?

**Comment by jrodewig** [comment]
@elasticmachine test this please

**Review by jrodewig — APPROVED** [review]
@abprash I pushed a45d1db21b2d37048b476922e8605d29870b69ed to remove the example entirely.

I also opened #56025 so we can re-add an example once we get some more context.

Thanks again for your contribution. I'll merge and backport this PR once the CI tests pass.

**Comment by jrodewig** [comment]
@elasticmachine test this please

**Comment by jrodewig** [comment]
### Backport commits
master 785527b 
7.x e4e02e1
7.7 8846ffd
7.6  c0a9975 
6.8 ce1aaec

**Comment by abprash** [comment]
Thank you @jrodewig . I apologize for the delay, you're right, that paragraph which still mentioned the reason for counts being approximate wasn't necessary. Thank you very much for merging after making some additional changes. :)

**Pull request merged**
