### PR TITLE
_nodes/stats should not fail due to concurrent AlreadyClosedException

### PR DESCRIPTION
**Pull request by pickypg**
This catches `AlreadyClosedException` during `stats` calls to avoid failing a `_nodes/stats` request because of the ignorable, concurrent index closure.

Part of #23099

### CODE REVIEW

**Comment by pickypg** [comment]
please test this

**Review by bleskes — APPROVED** [review]
Code is good. Any chance we can have a test for this?

**Comment by pickypg** [comment]
@bleskes I'll refactor the method so that one exists that accepts the iterator for the `IndexService`s and then test it that way.

**Comment by bleskes** [comment]
@pickypg where do we stand on this one?

**Comment by pickypg** [comment]
@bleskes Sorry, let this one linger. I've updated to add a test, which required refactoring the code to allow it to be a little more testable.

**Comment by pickypg** [comment]
5.x/5.6: b526704
5.5: b71f3c0
5.4: 1320a31

**Pull request merged**
