### PR TITLE
Deprecate dots in aggregation names

### PR DESCRIPTION
**Pull request by polyfractal**
Dots in aggregation names can lead to tricky parsing situations, like being unable to sort by agg names with dots.  Rather than introducing a lot of complex parsing code, we should just deprecate dots in agg names.  This puts them inline with the restrictions on field names too.

This PR adds a deprecation logger and a note in the docs, letting us remove them in 8.0.

It isn't strictly a 7.0 deprecation (I would like to backport it to 6.4), but I thought it made sense to include in the 7.0 migration guide in case people upgrade directly from 6.3 to 7.0

Related to #17600 and #19040

### CODE REVIEW

**Comment by rjernst** [comment]
Given that 7.0 is still a long way out, why isn't the deprecation intended for 6.4 long enough to remove in 7.0? Waiting until 8.0 is a very long time.

**Comment by polyfractal** [comment]
The thinking was that it's a relatively low-priority deprecation (cleans things up, but isn't necessarily blocking anything), but might affect a lot of users.  So someone upgrading directly from 6.3 to 7.0 wouldn't see the deprecations and would be hit with the break.

/cc @jpountz might have some thoughts.

**Comment by colings86** [comment]
@polyfractal is this still something we should do?

**Comment by polyfractal** [comment]
Stale, closing for now.  We should probably still do this but I don't have bandwidth at the moment to revisit this.

**Pull request closed without merging**
