### PR TITLE
ShardActiveResponseHandler shouldn't hold to an entire cluster state

### LINKED ISSUE #21394: [bug report]lots of memory consumption in clientHandlers
**Elasticsearch version**:
2.1 
**Plugins installed**: []
delete-by-query
elasticsearch-analysis-ik
repository-hdfs
**JVM version**:
jdk1.8.0_60
**OS version**:
CentOS Linux release 7.1.1503
**Description of the problem including expected versus actual behavior**:
our cluster is with 6.7T*2 and 17 data nodes with 30G heap and 17 gateway nodes with 8G heap and 3 master with 6G heap
we use fielddata which consump about 6G memory per data node.
and with about 400 search/seconds, the nodes with great memory presure and some of them even out of the cluster.
the I stop read/write and delete all the data.
but there are some data nodes still with over 90 heap usage and wouldn't drop even with heap dump which will force full-gc.
and then I take a look at the heap dump and found out that clientHandlers holds many many objects.
below is the pic of heap dump:
https://github.com/makeyang/grocery/blob/master/heapdump.png

please let me know if u need anything

### PR DESCRIPTION
**Pull request by imotov**
ShardActiveResponseHandler doesn't need to hold to ab entire cluster state since it only needs to know the cluster state version. It seems that on overloaded systems where nodes are unresponsive holding onto a lot of different cluster states can make the situation worse.

Closes #21394

Not sure how far back should we go in propagating this fix.

### CODE REVIEW

**Review by jasontedor — APPROVED** [review]
Nice, LGTM.

**Comment by bleskes** [comment]
LGTM2. good catch

**Comment by clintongormley** [comment]
@imotov Back to 2.4.2 i'd say

**Comment by njustyq** [comment]
I have a similar problems@imotov, Can you check it out for me. 
 https://github.com/elastic/elasticsearch/issues/50241

**Comment by njustyq** [comment]
@imotov I have a similar problems Can you check it out for me.
#50241

**Comment by njustyq** [comment]
@imotov @bleskes @clintongormley @jasontedor I have a similar problems, would you please check it out for me?
#50241

**Pull request merged**
