### PR TITLE
[Profiling] Remove superfluous flamegraph response fields

### PR DESCRIPTION
**Pull request by rockdaboot**
The removed fields are redundant, have not yet been released and the Kibana side does not use these values.

### CODE REVIEW

**Review by danielmitterdorfer — APPROVED** [review]

**Comment by rockdaboot** [comment]
Closing because it turned out that these fields are used for the differential flamegraph view.

**Comment by rockdaboot** [comment]
Meanwhile, Kibana really doesn't use these fields any more. So I reopened this PR and rebased it on main.

**Comment by rockdaboot** [comment]
@elasticsearchmachine merge upstream

**Comment by rockdaboot** [comment]
@elasticmachine merge upstream

**Pull request merged**
