### PR TITLE
[DOCS] Add azure storage secure settings while the node is running

### LINKED ISSUE #100777: [DOCS] No need to restart nodes when adding reloadable secure settings
### Elasticsearch Version

8.10.2

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

Darwin iMac.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64

### Problem Description

In the official documentation that explains how to [set up a repository on Azure Storage](https://www.elastic.co/guide/en/elasticsearch/reference/current/repository-azure.html), the following sentence can create confusion (emphasis added where the confusion resides):

> To enable Azure repositories, you have first to define your azure storage settings as [secure settings](https://www.elastic.co/guide/en/elasticsearch/reference/8.10/secure-settings.html), **before starting up the node:**

Further down the page, we can read this (emphasis is mine):

> The account, key, and sas_token storage settings are **reloadable secure settings**, which you add to the Elasticsearch keystore

The confusion stems from the fact that we first read that the secure settings must be added to the keystore **before starting the node** and later we learn that those settings are reloadable, without having to restart the node.

I think that **before starting up the node** should be removed as it is not correct since secure settings can be reloaded without restarting the nodes.

### Steps to Reproduce

1. Go to https://www.elastic.co/guide/en/elasticsearch/reference/current/repository-azure.html
2. Read the **Setup** section and notice the confusion

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by shainaraskas**
Fixes https://github.com/elastic/elasticsearch/issues/100777

Updates Azure repo snapshot/restore setup instructions to indicate that azure secure settings don't need to be added before the node is started

Confirmed that you can both add + reload reloadable settings while the node is running with the es security team

| Before | After |
| --- | --- | 
| image|image |

### CODE REVIEW

**Review by chriscressman — APPROVED** [review]

**Review by DaveCTurner — COMMENTED** [review]
Makes sense, but note that this is true of all secure settings for all cloud repositories (Azure, GCS and S3). Could we align this information across all these repository types?

**Comment by DaveCTurner** [comment]
In fact it'd be useful to include this on the [page about reloadable secure settings](https://www.elastic.co/guide/en/elasticsearch/reference/8.13/secure-settings.html#reloadable-secure-settings) too. That way it's clear that it apples to every reloadable secure setting, not just the ones related to the Azure repository.

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Comment by shainaraskas** [comment]
## 💔 Some backports could not be created

| Status | Branch | Result |
|:------:|:------:|:------|
|❌|8.14|Conflict resolution was aborted by the user|
|✅|8.13|[](https://github.com/elastic/elasticsearch/pull/109703)|
|❌|7.17|Conflict resolution was aborted by the user|

Note: Successful backport PRs will be merged automatically after passing CI.

### Manual backport
To create the backport manually run:
```
backport --pr 107163
```

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

**Pull request merged**
