### PR TITLE
Remove some more unused XContent parsers

### PR DESCRIPTION
**Pull request by original-brownbear**
Remove some more of these parsers that have become obsolete with the HLRC going away.

### CODE REVIEW

**Comment by ldematte** [comment]
Hey, new join here :) Any docs/wiki/etc. that could help me review this? It looks good on the surface, but I feel I miss some context to understand why these can be removed. Thanks!

**Comment by original-brownbear** [comment]
@ldematte these were all used by the high level rest client, see deprecated class `org.elasticsearch.client.RestHighLevelClient`. See https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-high.html here as well.

That logic needed parsing for various JSON-like objects. Now that many bits of the high level rest client have gone away, a lot of the parsing logic for the responses ES sends has become unused.

**Comment by stu-elastic** [comment]
I'm going to ping the clients team on this.

**Comment by swallez** [comment]
@stu-elastic delete at will! The HLRC is gone in 8.x. We still release 7.17.x versions though.

**Review by breskeby — APPROVED** [review]
build-tools-internal changes look good

**Review by ldematte — APPROVED** [review]
As long as there are no more external usages, I don't see why they should stay. Looks good to me!

**Comment by original-brownbear** [comment]
Thanks you two!

**Pull request merged**
