### PR TITLE
remove 6.3.x constants

### PR DESCRIPTION
**Pull request by talevy**
relates to refactoring effort #41164.

### CODE REVIEW

**Comment by talevy** [comment]
run elasticsearch-ci/2

**Review by jpountz — APPROVED** [review]

**Comment by talevy** [comment]
run all tests

**Comment by talevy** [comment]
run elasticsearch-ci/1
run elasticsearch-ci/default-distro

**Comment by talevy** [comment]
run elasticsearch-ci/1

**Comment by talevy** [comment]
run elasticsearch-ci/1

**Comment by talevy** [comment]
thanks for the review Adrien!

**Pull request merged**
