### PR TITLE
Remove setuid,setgid bits on all files in Docker image

### PR DESCRIPTION
**Pull request by pugnascotia**
Add a step the docker build that removes the setuid and setgid bits on all files. This is a a very small partial backport from #50277.

### CODE REVIEW

**Comment by mieciu** [comment]
Thanks a lot @pugnascotia !!

**Review by dliappis — APPROVED** [review]
LGTM! Did you consider a test for it, or is it too complex?

**Comment by pugnascotia** [comment]
@elasticmachine update branch

**Comment by pugnascotia** [comment]
@elasticmachine update branch

**Pull request merged**
