### PR TITLE
Hack in bytebuddy settings for apm

### PR DESCRIPTION
**Pull request by stu-elastic**
Avoids lots of errors in `apm-agent.json`

```
{"@timestamp":"2024-02-01T16:59:07.633Z","log.level": "WARN","message":"Error on transformation org.elasticsearch.search.aggregations.bucket.terms.GlobalOrdinalsStringTermsAggregator$ResultStrategy$1", "ecs.version": "1.2.0","event.dataset":"elasticsearch.apm-agent","process.thread.name":"elasticsearch[index-qnxQEfg][search_worker][T#9]","log.logger":"co.elastic.apm.agent.bci.bytebuddy.ErrorLoggingListener","error.type":"java.lang.NoClassDefFoundError","error.message":"Could not initialize class net.bytebuddy.utility.QueueFactory","error.stack_trace":"java.lang.NoClassDefFoundError: Could not initialize class net.bytebuddy.utility.QueueFactory
	at net.bytebuddy.matcher.HasSuperTypeMatcher.doMatch(HasSuperTypeMatcher.java:60)
	at net.bytebuddy.matcher.HasSuperTypeMatcher.doMatch(HasSuperTypeMatcher.java:32)
	at net.bytebuddy.matcher.ElementMatcher$Junction$ForNonNullValues.matches(ElementMatcher.java:249)
```

### CODE REVIEW

**Comment by mark-vieira** [comment]
Do we have any insight as to why these permissions are suddenly needed. It sure sounds like _something_ has been switched on that wasn't before. If we were already using tracing, then it sounds like we've enabled some other kind of instrumentation that wasn't previously enabled.

**Comment by mark-vieira** [comment]
@mosche brought [this](https://github.com/elastic/elasticsearch/blame/a72b403afbed5c6ad2ae785231394821ce69124f/modules/apm/src/main/java/org/elasticsearch/telemetry/apm/internal/APMAgentSettings.java#L76) up. What was the motivation for this change?

https://www.elastic.co/guide/en/apm/agent/java/current/config-core.html#config-instrument

**Comment by mark-vieira** [comment]
It seems to me that enabling instrumentation isn't required for manual instrumentation (which I presume is what we're using). If tracing was working before, then enabling this setting clearly isn't required. Given the issue above, as well as the overhead it likely incurs, we should probably just disable instrumentation again.

**Comment by stu-elastic** [comment]
I tested the old otel version 1.17.0 at f11ed3c596244da97b6939120a7e389f149cda94 and the new one at c11c2afc39711df9928d6968e2c7ecc1cbb3a414, the logs aren't showing yet.  We still had the "instrument" setting for tracing.

Continuing to investigate.

**Comment by mark-vieira** [comment]
@stu-elastic I think we can close this PR, yes?

**Pull request closed without merging**
