### PR TITLE
Remove shard multiple data path selections.

### PR DESCRIPTION
**Pull request by howardhuanghua**
Clean up mutiple data path selections for new shard creation.
Relates #71205.

### CODE REVIEW

**Comment by rjernst** [comment]
@elasticmachine ok to test

**Comment by rjernst** [comment]
Thanks for the PR @howardhuanghua, I missed this in my previous work in MDP removal.

It looks like checkstyle is failing due to unused imports. Could you please fix that and I will then be happy to merge once tests pass.

**Comment by howardhuanghua** [comment]
@rjernst Thanks for checking. I have updated the branch.

**Review by rjernst — APPROVED** [review]
LGTM, thanks @howardhuanghua

**Pull request merged**
