### PR TITLE
Adds SpanGapQueryBuilder. Feature #27862

### LINKED ISSUE #27862: ES equivalent of lucene SpanNearQuery.Builder.addGap(int)
Lucene's SpanNearQuery.Builder.addGap(int) serves an important search criteria. Especially with slop=0, it acts as arbitrary gap between two clauses just like the gaps created by removal of stop words in a phrase search. ES does not provide a similar Java API. Infact, even the lucene's way of introducing a gap in phrase search by PhraseQuery.Builder.add(Term term, int gap), used after filtering stop words, is missing in ES. Have I overlooked any existing ES way of introducing such behaviour?

### PR DESCRIPTION
**Pull request by Chandan83**
SpanGapQueryBuilder is unlike any other QueryBuilder because it cannot be used to generate a SpanGapQuery which is private to SpanNearQuery. More details in the code comments. To the best of my intentions, I have adhered to all contributing guidelines except writing new unit tests. Before starting to write unit tests, I thought it will be useful to get some feedback on the general approach of the solution since it is little unusual compared to existing code.   

Closes #27862

### CODE REVIEW

**Comment by karmi** [comment]
Hi @Chandan83, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/elasticsearch/pull/28636.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by Chandan83** [comment]
@jimczi  I had already signed CLA before submitting. Do you match anything other than github username?

**Comment by Chandan83** [comment]
@karmi I have added the email which was used during commit to my github profile.

**Review by jimczi — COMMENTED** [review]
Thanks @Chandan83 !
The approach looks good to me. I'd remove the `field` parameter of the `span_gap`, it's needed for the other `span_query` but I think we can omit it for gaps.
I agree that it's not ideal that we need to wait to build the final Lucene query to fail a request that contains a `span_gap` in a wrong place but I can live with it.
@jpountz any thoughts about this leniency ?

**Comment by Chandan83** [comment]
@jimczi If the approach is fine, I would start adding unit test cases. 
Each clause of a `span_near` should have the same field (otherwise lucene throws error) and for the current change, I am using the field of the first clause as the field passed to `SpanNearQuery.Builder(String field, boolen ordered)`.  Since the first clause can be a `span_gap`, I felt having `field` parameter will be an uniform approach.  Even the Lucene's `SpanNearQuery` uses `field`. 
There is no harm in redundant sanity checks but I will go by what you suggest.

**Comment by jimczi** [comment]
> @jimczi If the approach is fine, I would start adding unit test cases.

Thanks

> Since the first clause can be a span_gap, I felt having field parameter will be an uniform approach. Even the Lucene's SpanNearQuery uses field.

I think you're right, for consistency we should probably always require a `field` for a `span_query` so no need to remove it from the `span_gap`. We should probably make the change to `SpanQueryBuilder` to enforce it but it can be done in a follow up.

**Comment by javanna** [comment]
@Chandan83 did you have a chance to get back to this?

**Comment by Chandan83** [comment]
@javanna I could not find time to write the test cases. I might get to it in the first 2 weeks of April or most likely in May.

**Comment by Chandan83** [comment]
@jimczi I have added the requires test cases.

**Comment by jimczi** [comment]
jenkins, test this

**Comment by jimczi** [comment]
jenkins, test this

**Comment by Chandan83** [comment]
@jimczi The console log seems to suggest that the failure is unrelated to the commits. Please guide me here.

**Comment by jimczi** [comment]
The pr is quite old so you should merge with master to pull the changes. Just do `git merge master`, 
 then push the changes here and I'll try the tests again.

**Review by jimczi — APPROVED** [review]
Looks good to me. Thanks @Chandan83.
The tests are still failing but this pr is not the cause. Can you merge with master again and I'll merge if the tests pass.

**Comment by jimczi** [comment]
jenkins retest this please

**Comment by jimczi** [comment]
Thanks @Chandan83 !

**Comment by russcam** [comment]
This query is undocumented in the [span queries documentation](https://www.elastic.co/guide/en/elasticsearch/reference/6.3/span-queries.html); it'll be exposed in the .NET client, so I'll base the implementation on how it's used in SpanGapQueryBuilderTests.java

**Pull request merged**
