### PR TITLE
Remove redundant wrapping of ActionListener in NodeClient

### PR DESCRIPTION
**Pull request by original-brownbear**
In production we don't need to wrap this listener, it just needlessly makes stack-traces and heap dump analysis one step more complicated.

### CODE REVIEW

**Comment by DaveCTurner** [comment]
I wonder should we make `org.elasticsearch.action.ActionListener#assertOnce` assert that its delegate doesn't throw? We should be using `assertOnce` here right?

**Comment by original-brownbear** [comment]
Ah nice idea! Done :)

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Comment by original-brownbear** [comment]
Thanks David!

**Pull request merged**
