### PR TITLE
Adding `Exceptions` utility to enable code contracts that fail fast

### LINKED ISSUE #6289: Exception management for internal code contracts
Exception management for some of the internal code is repetitive across the entire codebase, requiring a lot of boilerplate code that is sensitive to copy/paste issues as well as a lot of unintended `NullPointerException`s in places that mean to check for `null` while checking other conditions. I propose creating a utility to handle this boilerplate for the most common cases.

In the forthcoming pull request, I have created an `Exceptions` utility that works like the `Preconditions` utility in Guava (and others that I have used/written), which just gives a very simple and readable mechanism for failing fast with expected exceptions (in this case, `ElasticsearchIllegalArgumentException`s). I have been using things like this for years on projects and I have found that they make code shorter, more readable and more predictable.

It turns code like:

    if (value1 == null) {
      throw new ElasticsearchIllegalArgumentException("value1 cannot be null");
    }
    if (Strings.isNullOrEmpty(value2)) {
      throw new ElasticsearchIllegalArgumentException("value2 cannot be empty");
    }
    if (value3 < 0) {
      throw new ElasticsearchIllegalArgumentException("value3 cannot be negative");
    }

    // required
    this.value1 = value1;
    this.value2 = value2;
    this.value3 = value3;
    // optional
    this.value4 = value4;

into:

    // required
    this.value1 = Exceptions.ifNull(value1, "value1 cannot be null");
    this.value2 = Exceptions.ifEmpty(value2, "value2 cannot be empty");
    this.value3 = Exceptions.ifNegative(value3, "value3 cannot be negative");
    // optional
    this.value4 = value4;

I also tend to use a few other functions not specified by `Preconditions`, such as inclusive and exclusive range checks and latitude/longitude checks, which I have implemented here. If they are actually embraced, it should make a simple way to provide predictable code contracts with minimal code.

### PR DESCRIPTION
**Pull request by pickypg**
Provides `Exceptions` utility to enable fail fast behavior with minimal boilerplate code.

Closes #6289

### CODE REVIEW

**Comment by javanna** [comment]
Hi @pickypg do you have time now? If not I am happy to take this over, you let me know ;)

**Comment by pickypg** [comment]
@javanna I think I'm going to have to pass this to you. Thanks! Let me know if you have any questions (doubt it).

**Comment by javanna** [comment]
I had another look at this to refresh my memory, I still think it is a good addition but it requires some more work, addressing comments review and adapting existing code to use the new api, to make sure it works out well. That is why I am marking it as adoptme and low-hanging-fruit.

**Comment by clintongormley** [comment]
Closing for lack of interest :)

**Pull request closed without merging**
