### PR TITLE
Fixed missing space

### PR DESCRIPTION
**Pull request by avshiav**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Review by lcawl — APPROVED** [review]
LGTM.  Thanks for catching this!

**Comment by javanna** [comment]
hi @avshiav could you please sign our CLA so we can merge your PR? Thanks again for opening it.

**Comment by avshiav** [comment]
sure, just let me know how

**Comment by javanna** [comment]
@avshiav here: http://www.elasticsearch.org/contributor-agreement/

**Comment by javanna** [comment]
jenkins test this please

**Review by javanna — APPROVED** [review]

**Comment by javanna** [comment]
thanks @avshiav !

**Pull request merged**
