### PR TITLE
EQL: Change result_position default value from head to tail

### PR DESCRIPTION
**Pull request by costin**

### CODE REVIEW

**Comment by costin** [comment]
Something fishy is going on - I get failures with the message "indices.upgrade API does not declare its visibility explicitly in ... [indices.upgrade.json]" which throws the YAML tests off. Raising the PR anyway to see whether the CI catches something else.

**Comment by costin** [comment]
Marking this is as a bug since some correctness tests are failing.

**Comment by costin** [comment]
Incorporated the bug fix in #66493 and updated the PR to get the builds running.

**Review by astefan — APPROVED** [review]
LGTM

**Comment by costin** [comment]
@elasticmachine update branch

**Comment by costin** [comment]
Backported to 7.x and 7.11. /cc @jrodewig

**Pull request merged**
