### PR TITLE
Cache API key hashing results on creation time

### PR DESCRIPTION
**Pull request by ywangd**
The API key hashing result is now cached on the creation time of an API key, i.e. pre-warm the cache. Previously it is cached when the API key is authenticated for the first time. Since it is reasonable to assume that an API key will be used shortly after its creation, this change has following advantages:
* It removes the need for expensive pbkdf2 hashing computation on authentication time and therefore reduces overall server load
* It makes the first authentication faster

~~Currently, hashing on authentication time is performed in a dedicated thread pool. Since we expect the usage of authentication time hashing to be greatly reduced, this PR also moves the creation time hashing to the dedicate thread pool.~~
(edit: This will be a separate PR)

We also expect all keys to be used, that is, caching on creation time does not change the total number of keys need to be cached. Hence this PR does **not** introduce any extra logic to fine tune whether a key should be cached (for example, only cache if the load factor is lower than certain threshold etc.).

### CODE REVIEW

**Comment by ywangd** [comment]
@lloydmeta

**Comment by tvernum** [comment]
> Currently, hashing on authentication time is performed in a dedicated thread pool. Since we expect the usage of authentication time hashing to be greatly reduced, this PR also moves the creation time hashing to the dedicate thread pool.

This feels like a quite separate change.
It seems reasonable to do, but I'm not sure that _"we expect the usage of authentication time hashing to be greatly reduced"_. Since we only cache on the node on which the API was created "greatly reduced" seems optimistic. On a 3 node cluster with round-robin request dispatch, that's - at best - a 33% drop. As clusters grow, the % goes down.

**Comment by ywangd** [comment]
> > Currently, hashing on authentication time is performed in a dedicated thread pool. Since we expect the usage of authentication time hashing to be greatly reduced, this PR also moves the creation time hashing to the dedicate thread pool.
> 
> This feels like a quite separate change.
> It seems reasonable to do, but I'm not sure that _"we expect the usage of authentication time hashing to be greatly reduced"_. Since we only cache on the node on which the API was created "greatly reduced" seems optimistic. On a 3 node cluster with round-robin request dispatch, that's - at best - a 33% drop. As clusters grow, the % goes down.

Thanks, that's a good point. The statement of "we expect the usage of authentication time hashing to be greatly reduced" is inaccurate. It really means that certain/fair amount of authentication time hashing will be replaced by creation time hashing. And **if** we want to maintain the same usage level of the crypto thread pool, we should change the creation time hashing to use the thread pool. This also has the benefit to **not** performing creation time hashing in the `transport_worker` thread. 

With that being said, I agree this change can be considered as a separate piece because it affects creation time thread usage pattern in addition to authentication time. I am happy for it to be evaluated separately.

**Comment by ywangd** [comment]
@tvernum I reverted the changes related thread pool which makes this PR much simpler. Thanks!

**Comment by ywangd** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Review by tvernum — APPROVED** [review]
LGTM

**Comment by tvernum** [comment]
> I reverted the changes related thread pool which makes this PR much simpler. 

Thanks. It's definitely a nicer PR to review.

Will you open a new PR for the thread pool changes?

**Comment by ywangd** [comment]
> > I reverted the changes related thread pool which makes this PR much simpler.
> 
> Thanks. It's definitely a nicer PR to review.
> 
> Will you open a new PR for the thread pool changes?

Yes I will raise another PR after this one is merged.

**Pull request merged**
