### PR TITLE
Update api-conventions.asciidoc

### PR DESCRIPTION
**Pull request by dlindeque**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by dlindeque** [comment]
I’m not too sure what you need from me...
If you’re asking whether to build the change, I say ‘Yes’!

**Review by cbuescher — APPROVED** [review]
> I’m not too sure what you need from me...

Hi @dlindeque, thanks for the pull request and sorry for the confusion. The mails is a reminder to manually run our CI infrastructure on community PRs, which is not needed here because its a documentation change.
The change looks good to me. Can you sign the [CLA](https://www.elastic.co/contributor-agreement) so I can merge it? We need it for any contributions, even small typos like this.

**Comment by dlindeque** [comment]
I understand. Yes – I’ve signed it.

**Comment by cbuescher** [comment]
@dlindeque thanks for this PR

**Pull request merged**
