### PR TITLE
[Fleet] Allow kibana to create Fleet Server indices

### PR DESCRIPTION
**Pull request by nchaulet**
## Context
Related to https://github.com/elastic/fleet-server/issues/51

We recently added the permissions for the Kibana to read and read to `.fleet-*`

We decided that Kibana will also create these indexes so we need more permissions.

## Description

Add `all` permission to `.fleet*` to the kibana system role to allow Kibana to create the indexes for Fleet server, the indexes will be managed in Kibana similarly to the `.kibana` index

### CODE REVIEW

**Review by kobelb — APPROVED** [review]

**Comment by ruflin** [comment]
@nchaulet I'm a bit hesitant to just make it `.fleet-*` instead of specifying each one but I see how it simplifies the development and also allows us to create "subindices" for aliasing etc.

**Comment by nchaulet** [comment]
@ruflin yes it makes things a lot easier, otherwise we will have to give permissions for each indices like this `.fleet-agents*` for each indices and to update this again if we need new indices. 
If kibana manage these indices I think it's okay to have some permissive  permissions.

**Comment by nchaulet** [comment]
@ruflin Are we okay with moving forward with these permissions for now?

**Comment by mark-vieira** [comment]
@elasticmachine update branch

**Review by ruflin — APPROVED** [review]

**Review by albertzaharovits — APPROVED** [review]

**Pull request merged**
