### PR TITLE
Add 3rd party tests for reading blobs with larger lengths

### PR DESCRIPTION
**Pull request by tlrx**
This change adds a 3rd party test to validate that Azure, GCS and S3 allow requesting bytes ranges that exceed the real length of a blob.

Note: CI will probably fail until each HTTP handler are fixed in fixtures.

### CODE REVIEW

**Review by DaveCTurner — COMMENTED** [review]
In https://github.com/elastic/elasticsearch/pull/106180/files#diff-7c71f797d018b40ccaa4f3973cf6f529a44d7152c14fc285aec9e2af7c4a5eaaR280 we're even starting the read past the end of the blob; could we have coverage for that case too?

**Comment by DaveCTurner** [comment]
> Note: CI will probably fail until each HTTP handler are fixed in fixtures.

I'd be ok with combining all these changes together into one PR I think, it should still be easy enough to review.

**Comment by tlrx** [comment]
> In https://github.com/elastic/elasticsearch/pull/106180/files#diff-7c71f797d018b40ccaa4f3973cf6f529a44d7152c14fc285aec9e2af7c4a5eaaR280 we're even starting the read past the end of the blob; could we have coverage for that case too?

Somehow I managed to lost that. I reintroduced the test and updated the code.

> I'd be ok with combining all these changes together into one PR I think, it should still be easy enough to review.

I did not expect all the changes, but we should be good once the HTTP handlers PRs are merged. Sorry for the hassle.

**Review by fcofdez — APPROVED** [review]
LGTM. Apologies for the delay on the review

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Comment by tlrx** [comment]
Thanks Francisco and David!

**Pull request merged**
