### PR TITLE
Add rest tests for `get_alias`

### PR DESCRIPTION
**Pull request by olcbean**
Currently if *no* aliases are provided to `get_alias`, the response will contain *all* indices ( even the ones without aliases )
However if all aliases are requested ( by providing `_all` or `*` ), then *only*  the indices with aliases are returned ( the ones without aliases are filtered out )

### CODE REVIEW

**Comment by javanna** [comment]
possibly related to #29538 . I need to catch up and look at both, will do soon-ish.

**Comment by olcbean** [comment]
This PR is just 'documenting' a strange filtering on the REST layer.
@javanna just reading the msg of #29538, it should not have an affect on this PR ... But it may simplify some of the filtering done on the REST layer.

**Review by javanna — APPROVED** [review]
LGTM thanks @olcbean

**Comment by javanna** [comment]
Relates to #30536 , as it documents some of the strange behaviour of get aliases response.

**Pull request merged**
