### PR TITLE
Fix typo in returned response

### PR DESCRIPTION
**Pull request by samidhtalsania**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)? Yes
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)? Yes

### CODE REVIEW

**Review by cbuescher — APPROVED** [review]
LGTM

**Comment by cbuescher** [comment]
@samidhtalsania could you sign the CLA so we can merge this?
@elasticmachine test this please

**Comment by samidhtalsania** [comment]
@cbuescher I did sign it. I am not sure why the bot thinks I have not.

**Comment by cbuescher** [comment]
>  I did sign it. I am not sure why the bot thinks I have not.

Seems it just turned green. Sorry to bother. Will merge and thanks for the correction!

**Pull request merged**
