### PR TITLE
ExchangeBuffer should release inbound page when no more input is expected 

### LINKED ISSUE #100145: ESQL: fix ForkingOperatorTestCase.testManyInitialManyPartialFinalRunne
This test fails intermittently, run with @Repeat

The new MockBlockFactory finds that a block has not been released. The test deliberately throws exceptions in driver operators, to ensure that things are handled correctly. It's likely that the we're missing a catch or something in Driver. Or maybe the 
MockBlockFactory is not reporting correctly? But the breaker is not 0, so it would appear correct, no?

e.g.

REPRODUCE WITH: ./gradlew 'null' --tests "org.elasticsearch.compute.aggregation.CountDistinctIntGroupingAggregatorFunctionTests.testManyInitialManyPartialFinalRunnerThrowing" -Dtests.seed=FE599591D0DD394 -Dtests.locale=it-CH -Dtests.timezone=Pacific/Truk -Druntime.java=19

java.lang.RuntimeException: 1 blocks have not been released

	at __randomizedtesting.SeedInfo.seed([FE599591D0DD394:D7EBD475D4DF81E]:0)
	at org.elasticsearch.compute.data.MockBlockFactory.ensureAllBlocksAreReleased(MockBlockFactory.java:50)
	at org.elasticsearch.compute.operator.AnyOperatorTestCase.allBreakersEmpty(AnyOperatorTestCase.java:130)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:1004)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
	at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
	at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
	at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.RuntimeException: Block allocated from test: org.elasticsearch.compute.aggregation.CountDistinctIntGroupingAggregatorFunctionTests
	at org.elasticsearch.compute.data.MockBlockFactory.trackDetail(MockBlockFactory.java:30)
	at org.elasticsearch.compute.data.MockBlockFactory.newLongArrayVector(MockBlockFactory.java:273)
	at org.elasticsearch.compute.data.BlockFactory.newLongArrayVector(BlockFactory.java:230)
	at org.elasticsearch.compute.aggregation.blockhash.LongBlockHash.getKeys(LongBlockHash.java:101)
	at org.elasticsearch.compute.aggregation.blockhash.LongBlockHash.getKeys(LongBlockHash.java:30)
	at org.elasticsearch.compute.operator.HashAggregationOperator.finish(HashAggregationOperator.java:146)
	at org.elasticsearch.compute.operator.Driver.runSingleLoopIteration(Driver.java:202)
	at org.elasticsearch.compute.operator.Driver.run(Driver.java:129)
	at org.elasticsearch.compute.operator.Driver$1.doRun(Driver.java:290)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:983)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	... 1 more

### PR DESCRIPTION
**Pull request by ChrisHegarty**
This commit updates ExchangeBuffer to release inbound page when no more input is expected.

closes #100145

### CODE REVIEW

**Comment by ChrisHegarty** [comment]
There could still be a small window for a race here, but the failing test did reproduce the issue quite frequently (before the fix), while with the fix the test passes successfully when run several 100s of thousands of times.

**Review by alex-spies — APPROVED** [review]
LGTM, but probably someone with more experience with exchanges should take a look as well.

**Comment by ChrisHegarty** [comment]
@elasticmachine retest elasticsearch-ci/bwc

**Comment by ChrisHegarty** [comment]
@elasticmachine test elasticsearch-ci/bwc

**Review by dnhatn — APPROVED** [review]
LGTM. Thanks, Chris!

**Pull request merged**
