### PR TITLE
Harden search context id

### PR DESCRIPTION
**Pull request by dnhatn**
Using a Long alone is not strong enough for the id of search contexts because we reset the id generator whenever a data node is restarted. This can lead to two issues:

- Fetch phase can fetch documents from another index
- A scroll search can return documents from another index

This commit avoids these issues by adding a UUID to the search context Id.

### CODE REVIEW

**Comment by dnhatn** [comment]
@jimczi I looked into how we can reopen readers on other nodes in case the current node crashes. We can use commit_id or seq_id for this. However, we won't be able to utilize it until we have reader contexts as search contexts are still stateful on the master branch. I add a TODO for this. I think it's ready for review. Can you please take a look? Thank you!

**Review by jpountz — APPROVED** [review]
The change looks good to me.

**Review by jimczi — APPROVED** [review]
LGTM2

**Comment by dnhatn** [comment]
@jpountz @jimczi Thank you for reviews.

**Pull request merged**
