### PR TITLE
SQL: Skip the nested and object field types in case of an ODBC request

### PR DESCRIPTION
**Pull request by astefan**
This PR adds a change to how `SYS COLUMNS` behaves in case of a request coming from an ODBC client, by not returning the root `nested` or `object` fields.

Fixes https://github.com/elastic/elasticsearch/issues/37801.

### CODE REVIEW

**Review by costin — APPROVED** [review]
LGTM

**Comment by astefan** [comment]
@elasticmachine run elasticsearch-ci/default-distro

**Comment by astefan** [comment]
@elasticmachine run elasticsearch-ci/2

**Review by matriv — APPROVED** [review]
LGTM

**Comment by astefan** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by astefan** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by costin** [comment]
@bpintea ^^ - should we backport this one to 6.6 and maybe 6.5 as well?

**Comment by bpintea** [comment]
@costin yes, 6.6 makes sense. Debatable if 6.5 is worth it.

**Pull request merged**
