### PR TITLE
Check if an analytics event data stream exists before installing pipeline.

### PR DESCRIPTION
**Pull request by afoucret**
The geoip work done for behavioral analytics is undoing an optimization done in 8.7 where the geoip database is only downloaded when there's a geoip processor in the cluster 

This is because we are deploying our pipeline when the cluster start. This PR allow to defer the install of the pipeline until a behavioral analytics collection is created.

### CODE REVIEW

**Comment by afoucret** [comment]
@elasticsearchmachine run elasticsearch-ci/bwc

**Comment by jimczi** [comment]
You can use the `UPGRADE_FROM_VERSION` to disable the test conditionally, see an example [here](https://github.com/elastic/elasticsearch/blob/main/x-pack/qa/rolling-upgrade/src/test/java/org/elasticsearch/upgrades/MLModelDeploymentsUpgradeIT.java#L101)

**Comment by jimczi** [comment]
> I've created a changelog YAML for you.

It's an unreleased bug so we shouldn't use the bug label here which is misleading. In general unreleased bugs are marked as `non-issue` so that no changelog is required/created.

**Review by jimczi — APPROVED** [review]
LGTM

**Pull request merged**
