### PR TITLE
Update ForceMergeAction's BWC constants

### PR DESCRIPTION
**Pull request by dakrone**
Once #51819 is merged the `codec` parameter will be available in the 7.x branch. This updates the
version constants so master (8.0) and 7.7 can talk to each other.

### CODE REVIEW

**Review by probakowski — APPROVED** [review]

**Comment by dakrone** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by dakrone** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by dakrone** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by dakrone** [comment]
@elasticmachine update branch

**Comment by dakrone** [comment]
@elasticmachine update branch

**Comment by jtibshirani** [comment]
@elasticmachine update branch

**Pull request merged**
