### PR TITLE
Implement support for partial search results in SQL CLI

### LINKED ISSUE #86082: SQL: add partial search results support to the CLI
### Description

The ask is to build on top of #85897 to allow CLI to enable fetching partial results.

### PR DESCRIPTION
**Pull request by luigidellaquila**
Add support for

```
allow_partial_search_results = true/false
```

command in SQL CLI. 

If true, returns partial results if there are shard request timeouts or shard failures.
If false, returns an error with no partial results.

Fixes #86082

### CODE REVIEW

**Comment by luigidellaquila** [comment]
@elasticmachine update branch

**Review by astefan — COMMENTED** [review]
Looks good, but the tests can be improved.
Apart from the comments inside the PR, please create a `CliPartialResultsTestCase` instead of the `CliShardFailureIT` (in `single_node` project). This class should go in `sql:qa:server` project. Two other `IT` classes will extend this `TestCase` and they should go in `single_node` and `security`. Take `FetchSizeTestCase` as an example. Also, the name of the class - `CliShardFailure` - is not in line with other similar test classes for other Cli commands.

**Review by Luegg — APPROVED** [review]
Lgtm 👍

**Review by astefan — APPROVED** [review]
LGTM. Thank you

**Review by costin — APPROVED** [review]
Please update the docs as well. LGTM

**Review by bpintea — APPROVED** [review]
LGTM!

**Comment by luigidellaquila** [comment]
@elasticmachine update branch

**Pull request merged**
