### PR TITLE
Fix Test Failure in BlobStoreRepositoryCleanupIT#testMasterFailoverDuingCleanup

### PR DESCRIPTION
**Pull request by original-brownbear**
This only really triggers with https://github.com/elastic/elasticsearch/pull/73190
merged but is technically possible in the current code already. The master failover
for cleanups works error free in almost all cases, except for the rare case
where the removal of the cleanup due to master failover (we never keep going here) did not yet
happen and a new cleanup is attempted.
I do not think it's worth fixing this corner case when we have similar retry noise
for other snapshot- and master-actions in general so I made the test survive this.

### CODE REVIEW

**Comment by original-brownbear** [comment]
@elasticmachine  update branch

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/rest-compatibility  (unrelated)

**Comment by original-brownbear** [comment]
@elasticmachine update branch

**Comment by original-brownbear** [comment]
@elasticmachine update branch

**Comment by original-brownbear** [comment]
@DaveCTurner @tlrx ping if one of you has a sec, should be a simple one and I bet this is going to start failing at some rate eventually if it hasn't already :)

**Review by tlrx — APPROVED** [review]
LGTM

**Review by DaveCTurner — APPROVED** [review]
LGTM2

**Comment by original-brownbear** [comment]
Thanks Tanguy & David!

**Pull request merged**
