### PR TITLE
[Stack Monitoring] Add missing logstash capacity mappings

### PR DESCRIPTION
**Pull request by klacabane**
### Summary

Part of https://github.com/elastic/beats/issues/38164

Add missing logstash `queue.capacity.*` mappings in the Stack Monitoring `.monitoring-logstash-mb` mappings

### CODE REVIEW

**Comment by klacabane** [comment]
@elasticmachine run elasticsearch-ci

**Comment by klacabane** [comment]
@elasticmachine run elasticsearch-ci/bwc-snapshots

**Comment by klacabane** [comment]
@elasticsearchmachine run elasticsearch-ci/8.13.0

**Comment by klacabane** [comment]
@elasticmachine update branch

**Review by miltonhultgren — APPROVED** [review]

**Pull request merged**
