### PR TITLE
Remove LeafSearchScript.runAsFloat(): Nothing calls it.

### PR DESCRIPTION
**Pull request by rmuir**
Nothing calls this method, I think we should remove it?

See https://github.com/elastic/elasticsearch/pull/18359 for the background. 

The fact we don't know our script's return type until runtime is a big problem for us. It causes boxing on every value for painless right now, but prevents us from removing boxing internally too.

I would love future ideas on how to clearly separate the stuff that returns Object (e.g. ExecutableScript) vs the stuff returning a double for scoring or something like that, because it is something we really need to fix. We really need to know the return type at compile-time. But runAsFloat is clearly useless, so this is an easy step :)

cc @uschindler

### CODE REVIEW

**Comment by rjernst** [comment]
LGTM.

> I would love future ideas on how to clearly separate the stuff that returns Object (e.g. ExecutableScript) vs the stuff returning a double for scoring or something like that

One idea I have been thinking about is having separate compile methods for each context a script can be used in. Right now, execution of scripts requires passing back to the script engine. Instead, if the object returned by compile was the thing that would be executed, and specific to the context, then we would have the info you seek (for example, search scripts will always return a double). Eventually we can improve the compile methods to take extra arguments specific to each context, for example search scripts or script fields taking mappings. The idea needs a lot more thought (like how this works with the current caching), but I think separating out each place a script can be used with separate requirements is the only way to get the proper info to script compilation.

**Comment by uschindler** [comment]
Aout painless: I would make 2 or more abstract Executables: One that returns Object and one that returns double or the other types. Painless checks while compiling which one to implement and returns the double one if possible. I think this should be possible to implement with some logic in the Writer if the "actual" type of the root node is primitive.

**Comment by rmuir** [comment]
> About painless: I would make 2 or more abstract Executables: One that returns Object and one that returns double or the other types. Painless checks while compiling which one to implement and returns the double one if possible. I think this should be possible to implement with some logic in the Writer if the "actual" type of the root node is primitive.

yes of course. To me that part is easy :) The hard part is this scripting API. It is what holds us back constantly and harder to make changes to: that is why I made a small step here.

**Comment by jdconrad** [comment]
LGTM as well. Nuke it all!

**Pull request merged**
