### PR TITLE
Add a deprecation notice to shadow replicas

### PR DESCRIPTION
**Pull request by bleskes**
See #22024

### CODE REVIEW

**Review by jasontedor — APPROVED** [review]
LGTM. Take it to 5.0 too?

**Comment by bleskes** [comment]
> Take it to 5.0 too?

I felt we can't mark deprecated in hind sight...  on the other hand it does make it for people. Doubting. Do others have opinions?

**Comment by javanna** [comment]
don't we usually include in the deprecation note the first version that had the feature deprecated? I think it can't be 5.0.0 although it would be technically possible as there are no code changes involved.

**Comment by jasontedor** [comment]
> I felt we can't mark deprecated in hind sight... on the other hand it does make it for people. 

There is a word missing here so I'm not sure what you're saying (sorry), but my thinking is that people might land on the 5.0 docs from a search engine or elsewhere and not necessarily think to click to 5.1 or current. I'd hate for someone impacted by this to miss the notice.

**Comment by bleskes** [comment]
>  you're saying (sorry)

It's me who should be saying sorry (the missing word is visible). I was torn between your point of view (let as many people as possible know) and the one of Luca.

@clintongormley it looks like you removed some labels - do you have an opinion here?

**Comment by javanna** [comment]
Maybe we should also log deprecation warnings when the feature is used? (not sure how feasible that is, and should not flood the logs, but at least we would make sure that people notice without having to look at the docs)

**Comment by clintongormley** [comment]
@bleskes re labels, just preparing the 5.1.1. release notes

I'm OK with deprecating it now (as in whichever version it lands in) but let's make sure there is deprecation logging

**Comment by bleskes** [comment]
@clintongormley I added deprecation logging and updated the messages a bit. It now looks like this (when you create a shadow replicas index):

image

@jasontedor can you take another look?

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by bleskes** [comment]
Thx @jasontedor

**Comment by bleskes** [comment]
I reverted this PR as it triggers warnings about usage of deprecated features. My bad for not catching it before merging

**Comment by bleskes** [comment]
This PR deprecates shadow replicas settings *and* the custom data path support. Upon discussion we have decided not to deprecate  the custom data path settings. In order to avoid confusion I opened a new PR  - #22647 - and remove the labels from this one.

**Pull request merged**
