### PR TITLE
Ensure unregister child node if failed to register task

### LINKED ISSUE #55875: [CI] org.elasticsearch.action.admin.cluster.node.tasks.CancellableTasksIT.testDoNotWaitForCompletion
This failed on 7.x with a time out.

Build scan: https://gradle-enterprise.elastic.co/s/4slsedxex4eei

Repro line:
```
./gradlew ':server:integTest' --tests "org.elasticsearch.action.admin.cluster.node.tasks.CancellableTasksIT.testDoNotWaitForCompletion" -Dtests.seed=8B437416A10AF044 -Dtests.security.manager=true -Dbuild.snapshot=false -Dtests.jvm.argline="-Dbuild.snapshot=false" -Dtests.locale=be -Dtests.timezone=Africa/Algiers -Dcompiler.java=14 -Druntime.java=8
```

### PR DESCRIPTION
**Pull request by dnhatn**
We fail to unregister the child node in `registerAndExecute` if the parent task is being canceled. This leads to a bug where a cancel request never [completes](https://github.com/elastic/elasticsearch/blob/2fa9988a251c609067b9f3b8090a4f4ebf54861e/server/src/main/java/org/elasticsearch/action/admin/cluster/node/tasks/cancel/TransportCancelTasksAction.java#L123).

Closes #55875
Relates #54312

~I labelled this non-issue for an unreleased bug in #54312.~

### CODE REVIEW

**Comment by dnhatn** [comment]
@elasticmachine test this please

**Review by henningandersen — APPROVED** [review]
LGTM.

**Comment by dnhatn** [comment]
@elasticmachine update branch

**Comment by dnhatn** [comment]
Thanks Henning.

**Pull request merged**
