### PR TITLE
QA: Switch xpack rolling upgrades to three nodes

### LINKED ISSUE #25336: Rolling upgrade tests with 3 nodes
TL;DR: I'm adding a BWC layer in #24841 that will only be triggered in a mixed-version cluster with at least 3 nodes and an index with at least 3 shard copies (i.e. `index.number_of_replicas` > 1). Q: **Should we change our existing `qa/rolling-upgrade` tests to run with 3 nodes?**

Details: When a primary fails and a replica is promoted to primary, the new primary will trigger a primary-replica resync, making sure that all the replicas are realigned with the new primary. This is a transport action that will only go into 6.0, not into 5.x. As such I added a BWC layer to the transport action that it will not send these resync requests to 5.6 nodes (i.e. replicas on 5.6 nodes won't be realigned with the new 6.0 primary, same as we do today in < 6.0).

### PR DESCRIPTION
**Pull request by nik9000**
This is much more realistic and can find more issues. This causes the
"mixed cluster" tests to be run twice so I had to fix the tests to work
in that case. In most cases I did as little as possible to get them
working but in a few cases I went a little beyond that to make them
easier for me to debug while getting them to work. My test changes:

1. Remove the "basic indexing" tests and replace them with a copy of the
tests used in the OSS. We have no way of sharing code between these two
projects so for now I copy.
2. Skip the a few tests in the "one third" upgraded scenario:
  * creating a scroll to be reused when the cluster is fully upgraded
  * creating some ml data to be used when the cluster is fully ugpraded
3. Drop many "assert yellow and that the cluster has two nodes"
assertions. These assertions duplicate those made by the wait condition
and they fail now that we have three nodes.
4. Switch many "assert green and that the cluster has two nodes" to 3
nodes. These assertions are unique from the wait condition and, while
I imagine they aren't required in all cases, now is not the time to
find that out. Thus, I made them work.
5. Rework the index audit trail test so it is more obvious that it is
the same test expecting different numbers based on the shape of the
cluster. The conditions for which number are expected are fairly
complex because the index audit trail is shut down until the template
for it is upgraded and the template is upgraded when a master node is
elected that has the new version of the software.
6. Add some more information to debug the index audit trail test because
it helped me figure out what was going on.

Closes #25336

### CODE REVIEW

**Review by ywelsch — APPROVED** [review]
LGTM. The index audit trail functionality not being available during a rolling restart does not sound great. Looking at the code, it looks like it's silently dropping events on the floor. Should we raise a separate issue for this?

**Comment by nik9000** [comment]
> The index audit trail functionality not being available during a rolling restart does not sound great. Looking at the code, it looks like it's silently dropping events on the floor. Should we raise a separate issue for this?

Yeah. #31139.

**Comment by nik9000** [comment]
There are half a dozen conflicts on the backport cherry pick so I'm marking this `backport pending` because I expect it'll take some time.

**Comment by nik9000** [comment]
OK! So I was able to backport to 6.x without much trouble. After I fixed the conflicts everything ran fine so I pushed. 6.3 is not running fine. And this is starting to fail on the master branch in CI but I'm not sure why yet.

**Comment by nik9000** [comment]
One ray of sunshine, sort of: it looks like the tests were failing in 6.x just like in 6.3 but I didn't catch it locally. That removes one mystery.

I'm skipping those tests in 6.x for now while I figure out what is up with them.

So the state of this backport now is:
* Merged to 6.x but with some tests disabled
* Not merged to 6.3 at all

**Comment by nik9000** [comment]
The backport to 6.3 was clean! But new and interesting tests fail!

**Comment by nik9000** [comment]
Backported.

**Pull request merged**
