### PR TITLE
Ensure enrich executes on master node only

### PR DESCRIPTION
**Pull request by hub-cap**
The previous transport action was a read action, which under the right
set of circumstances can execute on a coordinating node. This commit
ensures that cannot happen.

### CODE REVIEW

**Review by martijnvg — APPROVED** [review]
The base class of `ExecuteEnrichPolicyAction.Request` should also be changed to `MasterNodeRequest`, otherwise LGTM.

**Comment by hub-cap** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by hub-cap** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by hub-cap** [comment]
@elasticmachine update branch

**Pull request merged**
