### PR TITLE
Cat shards bytes

### PR DESCRIPTION
**Pull request by GlenRSmith**
Add `bytes` to the JSON REST spec for cat.shards

### CODE REVIEW

**Comment by rjernst** [comment]
It looks like bytes is supported by all cat apis (at least, any that output byte size values). This change looks fine, but we should have an issue to fix the rest of the specs as well?

**Comment by GlenRSmith** [comment]
@rjernst I ran through all the cat APIs, cat.segments is the only other endpoint that outputs a byte value but was missing that param from its spec. Added.

**Review by rjernst — APPROVED** [review]
Lgtm. Thanks Glen.

**Comment by s1monw** [comment]
@GlenRSmith @rjernst what versions did this go into? Also why do we have backport-pending on this?

**Pull request merged**
