### PR TITLE
[Fleet] Specify individual rules for Fleet indices

### PR DESCRIPTION
**Pull request by jillguyonnet**
### Context

Fleet team is currently implementing phase 1 of storing Fleet secrets ([meta issue](https://github.com/elastic/ingest-dev/issues/1000), [phase 1 issue](https://github.com/elastic/kibana/issues/154715)), where a a new system index was created to store the secrets (cf. [this schema](https://user-images.githubusercontent.com/1813008/218431667-079a6ca8-b046-4a88-b085-4ac522c33e9e.png)).

The access expectations are as follows:
   - Kibana system should only have write and delete access, NOT read access.
   - Fleet server should have read access only.

The `.fleet-secrets` system index was added in https://github.com/elastic/elasticsearch/pull/95625; delete privilege was added in https://github.com/elastic/elasticsearch/pull/96080.

Upon testing, Mark found out that the `kibana_system` user has all privileges on `.fleet-*` indices, thus breaking the requirements; the initial proposed fixed was to rename the index to `.secrets-fleet` in https://github.com/elastic/elasticsearch/pull/96172. Following discussion on this PR, an alternative approach was decided that will allow better clarity on the different Fleet-related system indices as well as introducing fine-grained access to `.fleet-secrets`:
1. Break down access rules for each individual index (cf. [this comment](https://github.com/elastic/elasticsearch/pull/96172#issuecomment-1551180846)). This is what this PR does.
2. Make the `.fleet-secrets` index internal (cf. [this comment](https://github.com/elastic/elasticsearch/pull/96172#issuecomment-1553554429)). This change is implemented in https://github.com/elastic/elasticsearch/pull/97728.

### What this PR does

Remove the generic `.fleet-*` index privileges for Kibana and Fleet Server, break them down into the specific indices defined in x-pack/plugin/fleet/src/main/java/org/elasticsearch/xpack/fleet/Fleet.java.

### How to test this PR

1. Build and run ES along with Kibana.
2. In Kibana's Dev Tools, run `GET /_security/service/elastic/kibana`: the Fleet individual indices should be listed in the response.
3. Same with `GET /_security/service/elastic/fleet-server`.

### CODE REVIEW

**Review by ioanatia — APPROVED** [review]
following the conversations from https://github.com/elastic/elasticsearch/pull/96172 this change looks good from my side.

**Review by kc13greiner — APPROVED** [review]
LGTM!

**Review by juliaElastic — APPROVED** [review]
LGTM 🚀

**Comment by azasypkin** [comment]
I wish all PRs that update the Kibana system role descriptor had such a detailed description. Thanks a lot for taking the time to describe the rationale behind the change, @jillguyonnet!

/cc @elastic/es-security since the PR touched ES security plugin code (sorry for the late after-merge ping).

**Pull request merged**
