### PR TITLE
[ML] JIndex: Restore finalize job action

### PR DESCRIPTION
**Pull request by davidkyle**
Feature branch PR for the master feature branch

`TransportFinalizeJobExecutionAction` has already been restored to 6.x and its use simplifies the code in `AutoDetectResultsProcessor`. 

Plus some small non-functional changes to match the 6.x branch

### CODE REVIEW

**Comment by davidkyle** [comment]
run gradle build tests

**Comment by davidkyle** [comment]
test this please

**Review by droberts195 — APPROVED** [review]
LGTM

**Comment by davidkyle** [comment]
run gradle build tests 2

**Comment by davidkyle** [comment]
Closing due to a git snafu, will reopen the change in another PR

**Pull request closed without merging**
