### PR TITLE
Fix `_as_string` output to only show when format specified

### LINKED ISSUE #10284: Aggregations: formatted string values are always returned in 1.5
In ES 1.5, many aggregations now return a formatted `<foo>_as_string` version of the return values by default, even without specifying a `format` in the request, or regardless of the field type.

For instance:

```json
"aggregations": {
      "my_stats": {
         "count": 54,
         "min": 10148,
         "max": 19602,
         "avg": 15151.611111111111,
         "sum": 818187,
         "min_as_string": "10148.0",
         "max_as_string": "19602.0",
         "avg_as_string": "15151.611111111111",
         "sum_as_string": "818187.0"
      }
   }
```

Aggregations where I've observed this:

`as_string` always present:
- min
- max
- sum
- avg
- stats
- extended_stats
- value_count
- percentiles
- percentiles_ranks
- cardinality

`as_string` only present if the field is a date, regardless if `format` is specified or not:
- terms
- histogram
- date_histogram

Does it ever make sense to return a formatted version of a numeric field?  For dates, should we only return a formatted version if `format` is specified in the request?

### PR DESCRIPTION
**Pull request by colings86**
Closes #10284

### CODE REVIEW

**Comment by jpountz** [comment]
Seeing the fix, it looks like we should either remove ValueFormatter.RAW or enforce valueFormatter to be non-null?

**Comment by colings86** [comment]
@jpountz Good point. I tend to agree. I had a look into removing ValueFormatter.RAW and I'm not sure that's the way to go since if we remove it we will end up just recreating what it is doing inside `if (valueFormatter == null)` statements which feels like a step backwards to me.

I also had a look at enforcing that the valueFormatter is not null. This should be ok providing that we are ok with using ValueFormatter.Raw in the case where we cannot determine the valueType for the field? (see https://github.com/elastic/elasticsearch/blob/7bd7ea8f138d2f6c5e330c5abc8e98b8d4cfb419/src/main/java/org/elasticsearch/search/aggregations/support/ValuesSourceParser.java#L192-200). WDYT?

**Comment by jpountz** [comment]
@colings86 It sounds good to me!

**Comment by colings86** [comment]
@jpountz is it worth applying the fix as is to 1.5.2, 1.6, and 2.0 and then work on a new PR to force the valueFormat to be non-null? I am a bit worried about maintaining backwards compatibility if we force the ValueFormat to be non-null as there are a number of cases where we currently set the ValueFormat, ValueFormatter and/or ValueParser to null.

**Comment by jpountz** [comment]
@colings86 +1

**Pull request merged**
