### PR TITLE
Restrict the priority of `ShardSnapshotTask` to the same snapshot only

### PR DESCRIPTION
**Pull request by pxsalehi**
Give shard snapshot metadata work priority over file snapshot work ONLY within the same snapshot. After some discussion with Armin and some benchmarks, this seems to prevent many overlapping snapshots prolonging each other due to constant prioritization of snapshot metadata work.

### CODE REVIEW

**Review by original-brownbear — APPROVED** [review]
LGTM this benchmarks far superior to the previous order of operations. Lets remove the changelog entry and make it a non-issue though since its on top of unreleased work.

**Comment by pxsalehi** [comment]
CI failure was due to https://github.com/elastic/elasticsearch/issues/89776 and unrelated.

**Comment by pxsalehi** [comment]
@elasticmachine update branch

**Comment by pxsalehi** [comment]
@elasticmachine run elasticsearch-ci/bwc
(https://github.com/elastic/elasticsearch/issues/89994)

**Comment by pxsalehi** [comment]
Thanks, Armin!

**Pull request merged**
