### PR TITLE
Reduce allocations in TransportGetSnapshotsAction

### PR DESCRIPTION
**Pull request by DaveCTurner**
Today `TransportGetSnapshotsAction` accumulates a list of tuples representing responses-or-exceptions, which is a little inefficient and needs some awkward post-processing. This commit moves to accumulating the responses and exceptions directly, avoiding the need for intermediate lists and tuple wrappers and so on.

### CODE REVIEW

**Comment by DaveCTurner** [comment]
Although this is a good refactoring IMO, this change is motivated by wanting to introduce `RefCountingListeners#acquire(Consumer<>)` for use in the stateless module.

**Comment by DaveCTurner** [comment]
Sorry, looks like I broke something in the ITs. Don't review until CI is green.

**Comment by DaveCTurner** [comment]
@elasticmachine please run elasticsearch-ci/docs

**Comment by DaveCTurner** [comment]
Ok this is good to review now.

**Review by idegtiarenko — APPROVED** [review]

**Pull request merged**
