### PR TITLE
Update frequent-items-aggregation.asciidoc

### PR DESCRIPTION
**Pull request by GlenRSmith**
Fix type togeher > together

### CODE REVIEW

**Review by inqueue — DISMISSED** [review]
👋🏼 LGTM

**Review by kilfoyle — DISMISSED** [review]
LGTM! Thanks for fixing this!

**Comment by kilfoyle** [comment]
Actually...  I will (try to) rebase this onto main so that from there we can backport it into the current docs.

**Comment by kilfoyle** [comment]
@elasticmachine ok to test

**Comment by kilfoyle** [comment]
run CLA

**Review by kilfoyle — APPROVED** [review]

**Pull request merged**
