### PR TITLE
Always use bundled JDK for external cluster nodes when BWC testing

### LINKED ISSUE #51361: Unrecognized VM option 'UseConcMarkSweepGC' on OpenJDK 15
Node failed to boot because `UseConcMarkSweepGC` isn't supported, presumably because it was removed in OpenJDK 15?

https://gradle-enterprise.elastic.co/s/kloq36r7j4e3w

```
ES_BUILD_JAVA=openjdk13,ES_RUNTIME_JAVA=openjdk15,nodes=general-purpose

OS | openSUSE Leap 15.1, Linux 4.12.14-lp151.28.36-default

Specs | 32 CPUs, 94.4GB RAM
java.version | 13.0.2
java.vm.name | OpenJDK 64-Bit Server VM
java.vm.version | 13.0.2+8
java.runtime.version | 13.0.2+8
java.home | /var/lib/jenkins/.java/openjdk-13.0.2-linux

```

```
12:31:34 » Exception in thread "main" java.lang.RuntimeException: starting java failed with [1]
12:31:34 »  output:
12:31:34 »  
12:31:34 »  error:
12:31:34 »  Unrecognized VM option 'UseConcMarkSweepGC'
12:31:34 »  Error: Could not create the Java Virtual Machine.
12:31:34 »  Error: A fatal exception has occurred. Program will exit.
12:31:34 »  	at org.elasticsearch.tools.launchers.JvmErgonomics.flagsFinal(JvmErgonomics.java:118)
12:31:34 »  	at org.elasticsearch.tools.launchers.JvmErgonomics.finalJvmOptions(JvmErgonomics.java:86)
12:31:34 »  	at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:59)
12:31:34 »  	at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:92)
```

### PR DESCRIPTION
**Pull request by mark-vieira**
Currently we use the configured runtime Java home when running Elasticsearch nodes used for BWC testing. This can cause issues when a BWC version doesn't support running with the current branches runtime Java. For example, we want to test `master` on Java 15 but existing `7.x` releases explode due to the removal of CMS garbage collector options in Java 15. Realistically, we should just be running those nodes using their bundled JDK. This pull request does exactly that, and simply removes all setting of `JAVA_HOME` for test clusters that are not the current elasticsearch version.

Note: Backporting this will involve some extra work since in `7.x`, we spin up BWC test clusters that **do not** bundle a JDK, so we will need to boostrap one somehow.

Closes #51361

### CODE REVIEW

**Comment by mark-vieira** [comment]
@elasticmachine update branch

**Comment by mark-vieira** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by mark-vieira** [comment]
@elasticmachine run elasticsearch-ci/default-distro

**Comment by mark-vieira** [comment]
@elasticmachine run elasticsearch-ci/1

**Review by jasontedor — APPROVED** [review]
LGTM.

**Pull request merged**
