### PR TITLE
Don't refresh on `_flush` `_force_merge` and `_upgrade`

### PR DESCRIPTION
**Pull request by s1monw**
Today all these API calls have a sideeffect of making documents visible
to search requests. While this is sometimes desired it's an unnecessary sideeffect
and now that we have an internal (engine-private) index reader (#26972) we artificially
add a refresh call for bwc. This change removes this sideeffect in 7.0.

### CODE REVIEW

**Review by clintongormley — COMMENTED** [review]
Looks good to me, and I think it is the right way to go.  It needs a note in the breaking changes docs.

**Review by bleskes — APPROVED** [review]

**Comment by s1monw** [comment]
@clintongormley I pushed a migration guide note

**Review by jasontedor — APPROVED** [review]
LGTM.

**Review by jpountz — APPROVED** [review]
A W E S O M E

**Review by clintongormley — APPROVED** [review]

**Comment by s1monw** [comment]
@elasticmachine test this please

**Pull request merged**
