### PR TITLE
[backport] Adds a minimum interval to `auto_date_histogram`. (#42814)

### PR DESCRIPTION
**Pull request by pcsanwald**
Adds a minimum interval to `auto_date_histogram`. We do this by
restricting the roundings passed into to the aggregator.

### CODE REVIEW

**Comment by pcsanwald** [comment]
this PR is a backport for #42814

**Comment by pcsanwald** [comment]
@elasticmachine please test this

**Comment by pcsanwald** [comment]
@elasticmachine test this please

**Review by colings86 — APPROVED** [review]
LGTM, I assume this will be followed up with a change in master to make the Version check against 7.3?

**Comment by pcsanwald** [comment]
@colings86 yes, doing that right away

**Pull request merged**
