### PR TITLE
Improve Documentation

### PR DESCRIPTION
**Pull request by wangzhenhui1992**
This is a new PR of mater branch for the old PR #34727
> Refer to an inner class as an inner class in the documentation so it is easier to read.
> Issue: #34700

### CODE REVIEW

**Comment by wangzhenhui1992** [comment]
@javanna  This is the new one and would you like to help me trigger the CI ?

**Comment by javanna** [comment]
test this please

**Comment by wangzhenhui1992** [comment]
@javanna 
It seems that some error occured but not due to what I have modified,,,,,

**Comment by javanna** [comment]
thanks for the ping @wangzhenhui1992 , I agree. I will trigger another build. Really sorry that it takes this long to get your change in. I will make sure it gets merged though!

**Comment by javanna** [comment]
retest this please

**Comment by javanna** [comment]
I am merging this despite of the red build, which is caused by intermittent CI issues and not relevant test failures. The client build is green locally, so this change should not break anything.

**Pull request merged**
