### PR TITLE
Fix the package upgrade tests for 5.0.0

### PR DESCRIPTION
**Pull request by nik9000**
5.0+'s deb and rpm packages aren't pushed to maven cnertral so
instead we have to download them from artifacts.elastic.org.

### CODE REVIEW

**Review by abeyad — APPROVED** [review]
LGTM, thanks for fixing this @nik9000

**Comment by abeyad** [comment]
Is there a reason not to put 5.0.0 GA on maven central, other than the unified build release doesn't yet automatically do it?

**Comment by nik9000** [comment]
> Is there a reason not to put 5.0.0 GA on maven central

Most of 5.0.0 is on maven central but the rpm and deb are not. I'm not 100% sure of the reasoning, but I suspect it has to do with central being a repository for JVM artifacts and the rpm and deb are quite distro specific. I'm not sure I 100% agree with that reasoning but it isn't my call to make. If we do put the deb and rpm in central we can drop the fake ivy repo in the future.

**Comment by nik9000** [comment]
Thanks for the review! I've merged to 5.x and I'll port it to 5.0 and master branches.

master: 267a7b427b044efada3fb4c94aa1c495b83842dc
5.x: 749d06cc9e06e367db14d349d406b41ef52ccd3d
5.0:

**Comment by nik9000** [comment]
Jenkins did not [approve](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+packaging-tests/238/consoleFull) of this so I pushed f11a217546587c2b41147b5eb2b378913517886f which seemed to work on Jenkins and locally. It is much cleaner which is nice.

**Pull request merged**
