### PR TITLE
Fix typo in IndicesAdminClient#prepareOpen Javadoc

### PR DESCRIPTION
**Pull request by sliu1013**
Fixes a typo in the IndicesAdminClient#prepareOpen Javadoc.

### CODE REVIEW

**Review by AthenaEryma — APPROVED** [review]
LGTM, thanks!

**Comment by gwbrown** [comment]
@elasticmachine test this please

(just for completeness' sake, this shouldn't really need a test run)

**Comment by gwbrown** [comment]
@elasticmachine update branch

**Comment by gwbrown** [comment]
@elasticmachine test this please

**Pull request merged**
