### PR TITLE
Allow terms query in _rollup_search

### PR DESCRIPTION
**Pull request by jimczi**
This change adds the `terms` query to the list of accepted queries
for the _rollup_search endpoint.

### CODE REVIEW

**Comment by epixa** [comment]
cc @jen-huang since this might impact your work on rollups in Kibana

**Review by colings86 — COMMENTED** [review]
Should we have the index side of rollup copy any normalisers from keywords fields into the rollup index so the match query will normalise the query text?

I realise this is makes this change bigger but it means that the match query will work the same across live and rollup indexes. With the change as it is now if I have a field that has a lowercasing normaliser on the live index and do a rollup search across live and rollup indexes for `mySQL`, it will find documents in the live index and return them but it will look like there are no matching documents in the rollup index because the same normalisation was not applied on the rollup index.

**Review by colings86 — APPROVED** [review]
@jimczi and I discussed my concerns offline and we agreed that we would merge this PR as is into master and 6.4 and would open https://github.com/elastic/elasticsearch/issues/30996 which is a blocker for 6.4 so the behaviour is consistent by the time 6.4 is released

**Comment by jimczi** [comment]
I updated the pr to handle `terms` queries only. `match` queries would not bring anything compared to `term` queries because rollup doesn't accept `text` field and normalizers are not copied in the rollup index. We can revisit the limitation if https://github.com/elastic/elasticsearch/issues/30996 is implemented.

**Review by polyfractal — APPROVED** [review]

**Comment by polyfractal** [comment]
LGTM, thanks @jimczi!

**Pull request merged**
