### PR TITLE
Docs: Cut down on high level rest client copy-and-paste-ness

### PR DESCRIPTION
**Pull request by nik9000**
This introduces a mechanism to slightly reduce the copy-and-paste-ness of
the documentation for the High Level REST Client. It pulls out the entire
"execution" portion of the page that we can include in every page. Doing
this requires the introduction of a few attributes. It then uses these
attributes to further cut down on some copy-and-paste-ness.

This also standardizes some of the `id`s in the search documentation to
the naming scheme that we seem to be using in the newer docs.

### CODE REVIEW

**Comment by nik9000** [comment]
This is what it'd look like to cut down on the asciidoc ritual for each high level rest client API. I don't think it is really enough, but maybe it is a good start. I'm not sure. I marked it discuss so we'll talk about it some.

**Comment by nik9000** [comment]
Ah! I forgot to mention in the description that this also standardizes some of the `id`s in the search page documentation to look more like the ids that we've been using for newer docs. I'll update the description.

**Review by dimitris-athanasiou — APPROVED** [review]
LGTM This is definitely a step forward!

**Comment by nik9000** [comment]
@elasticmachine, retest this please

**Review by hub-cap — APPROVED** [review]

**Comment by nik9000** [comment]
image

**Comment by nik9000** [comment]
oooops misclick. I meant to rewrite the commit message before merge but merged too quickly. That is a shame.

**Pull request merged**
