### PR TITLE
Remove plugin classloader indirection

### PR DESCRIPTION
**Pull request by rjernst**
Extensible plugins use a custom classloader for other plugin jars. When extensible plugins were first added, the transport client still existed, and elasticsearch plugins did not exist in the transport client (at least not the ones that create classloaders). Yet the transport client still created a PluginsService. An indirection was used to avoid creating separate classloaders when the transport client had created the PluginsService.

The transport client was removed in 8.0, but the indirection still exists. This commit removes that indirection layer.

### CODE REVIEW

**Comment by rjernst** [comment]
I'm a bit fuzzy because it was a looong time ago, but I believe it worked like this: the transport client creates a plugin service, but it would not load modules. However, by creating a PluginsService, it would end up looking for the ExtendedPluginClassLoader. But the transport client didn't have the separate jar that the classloader exists in (separate jar so that we could isolate the create classloader permission). The indirection worked by making looking for that class lazy, until we were actually creating the class loader, which we never did in the transport client.

The removal here gives up on separating the classloader permission. The reason is that we already do another classloader creation within the server jar (for module layers), so it's kind of pointless to have this one still be separated.

**Comment by ldematte** [comment]
> The indirection worked by making looking for that class lazy, until we were actually creating the class loader, which we never did in the transport client.

Ah! I see, it makes sense. So, not a different implementation, but no implementation at all by "hiding" the missing class so it's loaded only when the method is called.

**Comment by ldematte** [comment]
@elasticmachine update branch

**Comment by ldematte** [comment]
(I update the branch because there where some unrelated tests failures)

**Review by ldematte — APPROVED** [review]
LGTM

**Pull request merged**
