### PR TITLE
Fix stackoverflow in AggregationProfileShardResult.toString

### PR DESCRIPTION
**Pull request by original-brownbear**
This would obviously recurse until SO -> since it's a toXContent we can use the string utility to get a reasonable string should this ever be used.

### CODE REVIEW

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/packaging-tests-windows-sample

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/bwc

**Comment by original-brownbear** [comment]
@elasticmachine update branch

**Review by martijnvg — APPROVED** [review]
LGTM, thanks for fixing this!

**Comment by original-brownbear** [comment]
npnp.+ thank Martijn! :)

**Pull request merged**
