### PR TITLE
Fix logger Strings.format calls

### PR DESCRIPTION
**Pull request by joegallo**
`Strings.format(...)` uses `%` format specifiers, but `logger.whatever(...)` uses `{}` for arguments. There's a couple of places where we used the latter for a call to the former. (Note: or so I think!)

Please review this adversarially: it's late and my brain is fried and I probably forgot to carry a two or something.

### CODE REVIEW

**Review by DaveCTurner — APPROVED** [review]
LGTM. This is so trappy, especially since we don't have any validation for these format strings any more.

**Review by idegtiarenko — APPROVED** [review]

**Review by pugnascotia — COMMENTED** [review]
Can we raise an issue to improve the existing logger usage check?

**Comment by joegallo** [comment]
> Can we raise an issue to improve the existing logger usage check?

I found #103186 and #87166 which mention adding static analysis for `Strings.format` and `String.format` respectively, so I added some comments onto them in order to get some fresh GH notifications and cross reference links.

**Comment by joegallo** [comment]
@elasticmachine update branch

**Comment by joegallo** [comment]
@elasticmachine update branch

**Pull request merged**
