### PR TITLE
Default ESQL data partitioning to DOC

### PR DESCRIPTION
**Pull request by dnhatn**
The DOC data partitioning typically outperforms SEGMENT data partitioning. Since we've capped the number of concurrent operators to the number of threads in the ESQL worker as a safeguard, we should consider changing the default data partitioning from SEGMENT to DOC.

Relates #99189

### CODE REVIEW

**Review by nik9000 — APPROVED** [review]

**Review by ChrisHegarty — APPROVED** [review]
LGTM

**Comment by jpountz** [comment]
I haven't run benchmarks to confirm, but in theory this change makes latency potentially better but throughput worse until we add support for doc partitioning to Lucene: https://github.com/apache/lucene/issues/9721. This is because some queries like range queries have no option but to evaluate the filter across the entire segment anyway. If you have a segment that you want to partition in, say, 10 partitions and evaluate a range filter across 10 threads (one per partition), each thread will actually evaluate the filter against the entire segment - not what we want.

Given how range queries on the `@timestamp` field are common, my preference would be to wait until we address this Lucene issue before we enable doc partitioning by default in ES|QL.

**Comment by dnhatn** [comment]
@jpountz Thank you for the feedback. I will take a look at the issue that you linked and leave this PR unmerged as you suggested.

**Review by costin — APPROVED** [review]
LGTM

**Pull request closed without merging**
