### PR TITLE
[DOCS] Document query support for metadata fields

### LINKED ISSUE #60553: [DOCS] Document search-ability of meta fields
In some cases, [meta fields](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-fields.html) can be searched, for example `"exists": { "field": "_routing" }`.  We should update our documentation somewhere (if it doesn't exist already) to indicate that this is reliable.

### PR DESCRIPTION
**Pull request by jrodewig**
Documents queries that support metadata field searches, such as `_id` and `_routing`.

Closes #60553.

### CODE REVIEW

**Review by mayya-sharipova — APPROVED** [review]
@jrodewig  Thanks, this LGTM.

I am just wondering, are we concentrating only on _id and _routing field for this PR? 
As some  queries can run on other metafields. For example match query be run on _index field, range query on `_seq_no` (not sure if these types of queries make sense though).

**Comment by jrodewig** [comment]
> ... some queries can run on other metafields. For example match query be run on _index field, range query on _seq_no (not sure if these types of queries make sense though).

Thanks @mayya-sharipova. As you pointed out, I didn't see obvious use cases for those metadata fields. However, I can amend the PR to include those if wanted. Let me know!

**Review by jtibshirani — COMMENTED** [review]
I think it's indeed useful to query other metadata fields like `_index`, `_size`, and `_ignored`. 

We usually describe a field type's capabilities in its dedicated docs instead of the query types. And in the docs for `_routing`, `_index`, etc. it looks like we already mention they can be searched. So I wonder if we need these extra references?

**Comment by jrodewig** [comment]
> We usually describe a field type's capabilities in its dedicated docs instead of the query types. And in the docs for _routing, _index, etc.

Ah. I overlooked this initially. I agree we probably don't need the extra docs. I'll close out this PR. Thanks @jtibshirani.

**Pull request closed without merging**
