### PR TITLE
[Monitoring] Add `usage` mapping for `monitoring-kibana` index

### PR DESCRIPTION
**Pull request by Bamieh**
Needed for this PR https://github.com/elastic/kibana/pull/34609, Since we will start filtering if this field `exists`.

Context: https://github.com/elastic/kibana/issues/32519

CC @chrisronline

### CODE REVIEW

**Review by tsullivan — APPROVED** [review]
LGTM

**Comment by tsullivan** [comment]
I tested a build off this branch and verified that filtering for usage data works with this:
image

**Review by chrisronline — APPROVED** [review]
LGTM!

**Comment by pickypg** [comment]
Was this backported to 7.x, 7.0, and 6.7?

**Comment by pickypg** [comment]
Backports:

7.x / 7.1: #41601 / 858e7f4
7.0: #41602 / 94211dc
6.7: #41606 / 31c49ff

**Pull request merged**
