### PR TITLE
Fix file settings service test on windows

### LINKED ISSUE #115280: [CI] FileSettingsServiceTests testProcessFileChanges failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #4706 / windows-2022_checkpart1_platform-support-windows](https://gradle-enterprise.elastic.co/s/aetm2famyyqbw)
- [elasticsearch-intake #12113 / part1](https://gradle-enterprise.elastic.co/s/phni7wjudjos6)

**Reproduction Line:**
```
gradlew ":server:test" --tests "org.elasticsearch.reservedstate.service.FileSettingsServiceTests.testProcessFileChanges" -Dtests.seed=E175BB524F09E5B4 -Dtests.locale=ky -Dtests.timezone=CNT -Druntime.java=23
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.reservedstate.service.FileSettingsServiceTests),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testProcessFileChanges),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.io.UncheckedIOException: could not write file [C:\bk\server\build\testrun\test\temp\org.elasticsearch.reservedstate.service.FileSettingsServiceTests_E175BB524F09E5B4-001\tempDir-018\config\operator\settings.json]
```

**Issue Reasons:**
- [main] 2 failures in test testProcessFileChanges (6.3% fail rate in 32 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by n1v0lg**
Fix unit test on windows: it looks like the replace-existing flag is necessary to avoid AccessDeniedExceptions like this [example failure](https://gradle-enterprise.elastic.co/s/4tjgx5vzblv36/tests/task/:server:test/details/org.elasticsearch.reservedstate.service.FileSettingsServiceTests/testProcessFileChanges?top-execution=1).

Resolves: https://github.com/elastic/elasticsearch/issues/115280

### CODE REVIEW

**Comment by n1v0lg** [comment]
Okay nvm it looks like the windows tests simply didn't run the first time so I guess this is not a sufficient fix. Moving back to draft...

**Comment by n1v0lg** [comment]
@elasticmachine update branch

**Comment by n1v0lg** [comment]
@jfreden this is ready for review now, when you have a sec!

**Review by jfreden — APPROVED** [review]
LGTM!

**Pull request merged**
