### PR TITLE
convert ConcatFilesTask.groovy to .java

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by alpar-t — COMMENTED** [review]
Thanks for working on this @mara2701 ! We appreciate your effort. 
I think this is a good starting point, I added some comments. 
I also added more details to #34459  as to what we expect with this transition,
sorry I should have added these to begin with.

**Comment by akki** [comment]
@mara2701 Are you planning to work further on this?
Since there is no activity on this thread for more than 2 months, is it fine if I take this task ahead?

**Comment by akki** [comment]
Picking this task due to long inactivity.

**Comment by danielmitterdorfer** [comment]
This PR might be obsolete due to https://github.com/elastic/elasticsearch/pull/37497.

**Comment by atorok** [comment]
Closing since  #37497 was merged.

**Pull request closed without merging**
