### PR TITLE
Note that no http settings are dynamic

### LINKED ISSUE #13364: "http.max_content_length" setting ignored?
I'm unable to specify the `http.max_content_length` setting via either of the following:

```sh
curl -XPUT localhost:9200/_cluster/settings -d '{ "transient" : { "http.max_content_length" : "400mb" } }'
{"acknowledged":true,"persistent":{},"transient":{}}

curl -XPUT localhost:9200/_cluster/settings -d '{ "persistent" : { "http.max_content_length" : "400mb" } }'
{"acknowledged":true,"persistent":{},"transient":{}}
```

If changing HTTP settings dynamically is prohibited, can this be documented please?

**Update**. Just found from logs that it's indeed not dynamically updatable:

```
[2015-09-06 19:49:54,552][WARN ][action.admin.cluster.settings] [Griffin] ignoring transient setting [http.max_content_length], not dynamically updateable
```

Please, **update the documentation or close the ticket at will**.

### PR DESCRIPTION
**Pull request by nik9000**
Closes #13364

### CODE REVIEW

**Comment by nik9000** [comment]
Ping @clintongormley for doc review.

Backport to 1.7, 2.0, 2.1 as well?

**Comment by clintongormley** [comment]
LGTM, although I'd probably move it up to just after the "Settings" header.

And backport list is good too

thanks!

**Comment by nik9000** [comment]
@clintongormley - moved. Had to reword a sentence to make the flow work though.

**Comment by clintongormley** [comment]
thanks @nik9000 - merged

**Pull request merged**
