### PR TITLE
Avoid IpStringToBytes Called Twice

### PR DESCRIPTION
**Pull request by GrandFisher**
We found that `InetAddresses#IpStringToBytes`  may  be called twice in  `DiscoveryNodeFilters#matchByIP` 
If the parameter  is ip. 
The specific code for repeated calls is here:
`String value = InetAddresses.isInetAddress(ipOrHost) ? NetworkAddress.format(InetAddresses.forString(ipOrHost)) : ipOrHost;`
`InetAddresses.isInetAddress` calls `InetAddresses#IpStringToBytes` and  `InetAddresses.forString(ipOrHost)` calls again.
In our case, when master exclude some nodes ,  the code will be hot at some point.
image

We found that `InetAddresses#IpStringToBytes`  could easily be implemented as calling only once.

### CODE REVIEW

**Comment by kingherc** [comment]
@elasticmachine please test this

**Comment by kingherc** [comment]
@elasticmachine update branch

**Comment by kingherc** [comment]
Hi @GrandFisher thank you for the PR! I took the liberty and made some minute changes to it, please review them in case there's anything we need to discuss. If it passes tests, I will merge it.

**Review by kingherc — APPROVED** [review]
LGTM

**Comment by GrandFisher** [comment]
> Pinging @elastic/es-distributed (Team:Distributed)

Thanks a lot

**Pull request merged**
