### PR TITLE
Remove support for delaying state recovery pending master

### LINKED ISSUE #51806: Remove support for delaying state recovery pending master nodes
It is useful to be able to delay state recovery until enough data nodes have joined the cluster, since this gives the shard allocator a decent opportunity to re-use as much existing data as possible. However we also have the option to delay state recovery until a certain number of master-eligible nodes have joined, and this seems unnecessary: we require a majority of master-eligible nodes for state recovery, but there is no advantage in waiting for more.

We should deprecate the following settings in `7.x` and remove them in `8.0`:

- `gateway.expected_nodes`
- `gateway.expected_master_nodes`
- `gateway.recover_after_nodes`
- `gateway.recover_after_master_nodes`

### PR DESCRIPTION
**Pull request by ShawnLi1014**
The following settings are deprecated:
* `gateway.expected_nodes`
* `gateway.expected_master_nodes`
* `gateway.recover_after_nodes`
* `gateway.recover_after_master_nodes`
This pull request removed these settings.

Closes #51806

### CODE REVIEW

**Comment by DaveCTurner** [comment]
@elasticmachine test this please

**Review by DaveCTurner — COMMENTED** [review]
Thanks @ShawnLi1014. Before I dive into the code in detail, there's a couple of points for the docs:

- would you document this change in docs/reference/migration/migrate_8_0/settings.asciidoc since it's a breaking change? Note the settings that were removed and name the settings that users should use instead.
- the docs themselves deserve a bit more of an overhaul, since there's now only one `expected_` setting and one `recover_after_`. I think we can explain what they do a bit more clearly now that we don't have to account for people using some combination of all the different settings.

You can see a preview of the docs here: http://elasticsearch_53845.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/modules-gateway.html  which hopefully helps.

I think an example would be useful too. See the end of `docs/reference/setup/important-settings/discovery-settings.asciidoc` for an example of the syntax for a YAML example with callouts to explain each part. Would you add an example?

I'll help with the details of the docs at a later date if needed.

**Comment by DaveCTurner** [comment]
Also note the check style failure from CI:

```
11:54:21 [ant:checkstyle] [ERROR] /dev/shm/elastic+elasticsearch+pull-request-1/server/src/test/java/org/elasticsearch/gateway/GatewayServiceTests.java:24:8: Unused import - org.elasticsearch.common.settings.Setting. [UnusedImports]
```

**Comment by DaveCTurner** [comment]
@ShawnLi1014 how are you getting on with addressing the review comments?

**Comment by ShawnLi1014** [comment]
> @ShawnLi1014 how are you getting on with addressing the review comments?

Sry for the delay. I have committed the changes, please take a look. If there's anything need to be improved please let me know

**Comment by DaveCTurner** [comment]
@elasticmachine ok to test

**Comment by DaveCTurner** [comment]
Thanks for your patience here @ShawnLi1014. I've brought this branch up to date with recent changes in `master`, but there are still some places where we mention `gateway.recover_after_nodes` in tests and these tests now fail. I've enabled CI on this PR; would you work through any failures it encounters please?

**Comment by ywelsch** [comment]
@ShawnLi1014 are you still interested in working on this?

**Comment by DaveCTurner** [comment]
I opened https://github.com/elastic/elasticsearch/pull/68316 for the failure.

@elasticmachine please run elasticsearch-ci/1

**Review by ywelsch — APPROVED** [review]
LGTM

**Pull request merged**
