### PR TITLE
Fix cluster.routing.allocation.enable and cluster.routing.rebalance.enable case

### LINKED ISSUE #28007: cluster.routing.allocation.enable and cluster.routing.rebalance.enable should be lowercase
According to the documentation, the values of `cluster.routing.rebalance.enable` and `cluster.routing.allocation.enable` are lowercase, however the defaults in the code are uppercase,

Ref: https://www.elastic.co/guide/en/elasticsearch/reference/current/shards-allocation.html

### PR DESCRIPTION
**Pull request by liketic**
Fixes the default value of `cluster.routing.allocation.enable` and `cluster.routing.rebalance.enable` to be lower-case.

Closes #28007

### CODE REVIEW

**Comment by ywelsch** [comment]
@elasticmachine test this please

**Comment by ywelsch** [comment]
@liketic I think there's no need to change the parsing here. The only issue is that the default value is shown in upper-case. It's good enough to add the `toString()` that does lower-casing and then use `toString()` for the default value.

**Comment by liketic** [comment]
Thanks @ywelsch

**Comment by ywelsch** [comment]
@elasticmachine retest this please

**Review by ywelsch — APPROVED** [review]

**Comment by ywelsch** [comment]
Thanks @liketic

**Pull request merged**
