### PR TITLE
Make noop template updates be cluster state noops

### LINKED ISSUE #57662: Streamline no-op template updates
Today every put-template request (both composable and legacy) results in a cluster state update, even if the cluster state already contains exactly the template that we're trying to put. There's no need to update the cluster state if the template is already there, so it would be preferable to skip any such requests without needing to publish a new cluster state version.

### PR DESCRIPTION
**Pull request by dakrone**
When updating an existing component or composable template that is identical to the existing
template, we now skip doing a cluster state update.

Resolves #57662

### CODE REVIEW

**Review by probakowski — APPROVED** [review]
LGTM, thanks Lee!

**Review by andreidan — APPROVED** [review]
LGTM nice optimisation

**Comment by ywelsch** [comment]
Maybe we should backport this to 7.8 given the relation to SDH cases.

**Comment by jhughes-mc** [comment]
It's our understanding this will help out our problem, but Elastic Cloud support seems to think it won't. If our filebeat agents are all set to automatically publish the template, won't this significantly reduce the cluster workload since it won't be trying to update the cluster state after each agent attempts to push a template that isn't changing?

**Comment by dakrone** [comment]
@jhughes-mc it will help with the workload, however, this work only applies to composable and component templates, not legacy templates, so I couldn't say whether this will help you, it would depend on which templates were being used.

**Pull request merged**
