### PR TITLE
[Java.time] Retain prefixed date pattern in formatter

### LINKED ISSUE #48698: [Java.time] Retain prefixed date pattern in formatter
in a mixed cluster environment, when a 6.8 node is a master it will send out a cluster state update where a mapping has a pattern with an` 8 prefix` (i.e. 8E, d MMM yyyy HH:mm:ss Z) it will then be applied on 7.x node. 
It will work for the first cluster state update, but on the second update it will notice a difference as  it will strip the `8` and will compare the `8E, d MMM yyyy HH:mm:ss Z` received vs `E, d MMM yyyy HH:mm:ss Z` As in reality the mapping has not changed, it will have same version. 
This is causing the assertion in `MappingService` to fail
```
  if (currentIndexMetaData.getMappingVersion() == newIndexMetaData.getMappingVersion()) {
                // if the mapping version is unchanged, then there should not be any updates and all mappings should be the same
                assert updatedEntries.isEmpty() : updatedEntries;
```

This should be fixed and the original date format should be retained, but the stripped format should be used on the enclosed java.time `DateTimeFormatter`

This is failing at the moment on https://github.com/elastic/elasticsearch/pull/47983

### PR DESCRIPTION
**Pull request by pgomulka**
JavaDateFormatter should keep the pattern with the prefixed `8` as it will be used for serialisation. The stripped pattern should be used for the enclosed formatters.
 
closes #48698

### CODE REVIEW

**Comment by pgomulka** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by pgomulka** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by pgomulka** [comment]
ok to test

**Comment by pgomulka** [comment]
@elasticmachine update branch

**Comment by pgomulka** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by pgomulka** [comment]
@rjernst the master-fwc is failing, but this is most likely because of https://github.com/elastic/elasticsearch/issues/49378

**Review by rjernst — APPROVED** [review]
The change looks good. Can you clarify which versions this is intended for? I see the v8.0.0 label, but the PR is against 7.x (which I believe is correct).

**Comment by pgomulka** [comment]
@rjernst this I think should go to v8, v7.x and v6.8
I had this problem reproduced when running a bwc test on 7.x (this pr). Master node on 6.8 and non-master node on 7.x was stripping the 8.

I wasn't able to confirm this failing same way when Master node was on 7 and non-master node was on 6.8. It was always passing for me. I still think this should go to 6.8 branch as well.

I am yet to try to reproduce this on v8 and v7 mixed cluster.

**Comment by rjernst** [comment]
If this goes to master, what is the plan to remove it? We need a cutoff, which seemed like 7.x. At some point we need to convert these back to removing the 8 prefix, and between master and 7.x it should not be necessary since all formats are java 8 format.

**Comment by pgomulka** [comment]
@rjernst you are right, this is not needed in master. When upgrading from 7.x to master users are not meant to have `8prefix` in their formats.
In that case only 6.8 and 7.x should have this fix.

**Comment by mark-vieira** [comment]
@elasticmachine run elasticsearch-ci/fwc

**Pull request merged**
