### PR TITLE
ESQL: Make settings dynamic

### PR DESCRIPTION
**Pull request by alex-spies**
* Return `QUERY_RESULT_TRUNCATION_DEFAULT_SIZE` in `EsqlPlugin::getSettings`.
* Make ESQL settings `Dynamic`.
* Add tests.

### CODE REVIEW

**Comment by alex-spies** [comment]
Tested this manually by assigning this setting in `...esql/qa/server/single-node/build.gradle`; before the change, Elasticsearch errors on startup because of an unknown setting.

Not sure if we currently have a good way of automatically testing our settings - this would require starting nodes with different configs and running some rudimentary tests.
If anyone has an idea of how to achieving this with little work, please let me know!

**Comment by alex-spies** [comment]
Also shoutout to @dnhatn who found this bug in the first place while showing me around in our settings!

**Comment by alex-spies** [comment]
> Not sure if we currently have a good way of automatically testing our settings - this would require starting nodes with different configs and running some rudimentary tests. If anyone has an idea of how to achieving this with little work, please let me know!

Never mind, found that `ESIntegTestCase` is a good fit for this and added a test.

**Comment by dnhatn** [comment]
Unrelated to this PR, but I believe these settings should be made dynamic, as they currently are not. Can you please make them dynamic? Once we've made this change, could you also write a test to confirm that the TRUNCATION_DEFAULT_SIZE setting actually takes effect? You can add that test to EsqlActionIT.

**Comment by alex-spies** [comment]
> Unrelated to this PR, but I believe these settings should be made dynamic, as they currently are not. Can you please make them dynamic? Once we've made this change, could you also write a test to confirm that the TRUNCATION_DEFAULT_SIZE setting actually takes effect? You can add that test to EsqlActionIT.

That makes sense (as a separate PR). Unfortunately, I don't have capacity for this right now, but I opened https://github.com/elastic/elasticsearch/issues/101620.

**Comment by alex-spies** [comment]
> > Unrelated to this PR, but I believe these settings should be made dynamic, as they currently are not. Can you please make them dynamic? Once we've made this change, could you also write a test to confirm that the TRUNCATION_DEFAULT_SIZE setting actually takes effect? You can add that test to EsqlActionIT.
> 
> That makes sense (as a separate PR). Unfortunately, I don't have capacity for this right now, but I opened #101620.

Never mind - after discussion with @dnhatn we concluded that this should be a trivial change and will be folded into this PR.

**Comment by alex-spies** [comment]
Alright @dnhatn , all ESQL settings are dynamic now and registered.

Rewrote the test to make it a bit smaller; it fails if our existing settings are either unregistered or non-dynamic.

**Review by dnhatn — COMMENTED** [review]
Thanks, Alex! The production change looks good. I think it's more reasonable to add a test that verifies that responses are capped at QUERY_RESULT_TRUNCATION_DEFAULT_SIZE. We can add that test to the EsqlActionEsql.

**Comment by alex-spies** [comment]
> Thanks, Alex! The production change looks good. I think it's more reasonable to add a test that verifies that responses are capped at QUERY_RESULT_TRUNCATION_DEFAULT_SIZE. We can add that test to the EsqlActionEsql.

You are right, @dnhatn ; added the tests to `EsqlActionIt` and it turns out that using the injected `Settings` during execution was not enough - we needed to access the cluster settings, otherwise dynamically set settings are ignored. (I was not expecting this.)

Changed `TransportEsqlQueryAction` - now it works; tested manually as well (using cluster settings API) for good measure.

**Review by dnhatn — APPROVED** [review]
LGTM. Thanks, Alex!

**Pull request merged**
