### PR TITLE
Make extraConfig task works with multiple files

### PR DESCRIPTION
**Pull request by tlrx**
This commit fixes the `configureExtraConfigFilesTask` so that it works when multiple files are specified in a build.gradle file like in:

```
extraConfigFile nodeKeystore.name, nodeKeystore
extraConfigFile clientTruststore.name, clientTruststore
```

Right now, only the latest processed file is copied over.

Not sure this is the best way to fix this, but it seems that a `Copy` task must be created for every extra config file to copy + keep a reference to the file in the `node.config.extraConfigFiles` (and not a ref to the `Map.Entry` object).

### CODE REVIEW

**Comment by rjernst** [comment]
Copy tasks can handle many files fine. I think this is just a misconfiguration because we keep calling into at the top level of the copy config. We need to instead call from first, then into.

**Comment by tlrx** [comment]
> Copy tasks can handle many files fine.

I agree. But it didn't work.

> I think this is just a misconfiguration

Can you please then provide a good configuration? I'll be happy to use it.

**Comment by rjernst** [comment]
I opened a PR: #16782

**Comment by tlrx** [comment]
closed in favor of #16782

**Pull request closed without merging**
