### PR TITLE
fix typo in Exception Response in GeoJson

### PR DESCRIPTION
**Pull request by boicehuang**
fix typo in Exception Response in GeoJson

### CODE REVIEW

**Comment by pugnascotia** [comment]
@elasticmachine test this please

**Review by pugnascotia — APPROVED** [review]

**Comment by pugnascotia** [comment]
@elasticmachine run elasticsearch-ci/bwc
@elasticmachine run elasticsearch-ci/default-distro

**Comment by pugnascotia** [comment]
@boicehuang please update your branch with the current `master`.

**Comment by boicehuang** [comment]
@pugnascotia Thanks. I have updated it.

**Comment by pugnascotia** [comment]
@elasticmachine ok to test

**Comment by pugnascotia** [comment]
Backported to `7.x` in ef26c1739b9

**Pull request merged**
