### PR TITLE
SAML: Process only verified signed data

### PR DESCRIPTION
**Pull request by jkakavas**
As conformance to best practices, this changes ensures that if a
SAML Response is signed, we verify the signature before processing
it any further. We were only checking the InResponseTo and
Destination attributes before potential signature validation but
there was no reason to do that up front either.

### CODE REVIEW

**Review by tvernum — APPROVED** [review]
LGTM

**Comment by jkakavas** [comment]
You mean `Destination`, right? The `Issuer` was checked after the Response Signature was validated. 

The useful error message argument still stands for `InRepsonseTo` and `Destination` checking might offer more helpful messages in a multiple saml realm setup, but 
a) I don't think this is a setup that we'll be seeing much.
b) I think it's better to future-proof our approach from a security perspective, even if it incurs a minor hit to ease of troubleshooting.

**Comment by tvernum** [comment]
> You mean Destination, right? The Issuer was checked after the Response Signature was validated.

I guess I do. It was a while ago :)
I don't especially care - but the premise was if things are totally misconfigured and we're getting the wrong messages, provide a useful error message.

**Comment by jpountz** [comment]
@jkakavas I'm not seeing this PR on the 6.3 branch, is this PR mislabeled? I removed the 6.3.1 label for now.

**Pull request merged**
