### PR TITLE
ESQL Move serialization of MV_ functions

### PR DESCRIPTION
**Pull request by nik9000**
This moves the serialization of the `MV_` functions from `PlanNamedTypes` to their `NamedWriteable` to line up better with the way the rest of Elasticsearch works.

### CODE REVIEW

**Comment by nik9000** [comment]
run  elasticsearch-ci/packaging-tests-unix-sample

**Comment by ChrisHegarty** [comment]
@elasticmachine update branch

**Review by ChrisHegarty — APPROVED** [review]
LGTM

**Comment by ChrisHegarty** [comment]
@elasticmachine update branch

**Comment by nik9000** [comment]
> @elasticmachine update branch

thanks!

**Pull request merged**
