### PR TITLE
documenting plugins custom install location

### PR DESCRIPTION
**Pull request by nellicus**
documenting use of -Des.plugins.path with regards to plugin script

### CODE REVIEW

**Comment by clintongormley** [comment]
@spinscale / @tlrx could you review this please?  Is this still true in master?

**Comment by tlrx** [comment]
@nellicus I'm not sure why you add this documentation.

In 1.7 & master, the custom plugins folder must be set in the `elasticsearch.yml` file under the `path.plugins` entry. When executed, the `bin/plugin` looks for the configuration file in the `$ES_HOME/config` then it loads this file and finally resolves the `path.plugins` folder. So if the configuration file is found and loaded, you don't need to specify `-Des.plugins.path` in the command.

Related to #10673

**Comment by nellicus** [comment]
@tlrx and what if you use a custom -Des.config.path ?

**Comment by tlrx** [comment]
In this case you still need to update the `elasticsearch.yml` file with the custom `path.plugins` entry and you need to pass the location of the configuration dir and/or file to the `bin\plugin` script.

You can pass the location as an environment variable like this:
```
CONF_DIR="/tmp/config" bin/plugin install elasticsearch/shield/latest
```
or use the `es.path.conf` property:
```
bin/plugin -Des.path.conf=/tmp/config/ install elasticsearch/shield/latest
```
or directly the configuration file:
```
/bin/plugin -Des.config=/tmp/config/elasticsearch.yml remove shield
```

Note that the plugin manager is changing for 2.0, hopefully this behavior will remain for 2.0

**Comment by nellicus** [comment]
is this anywhere in the documentation? @tlrx

**Comment by tlrx** [comment]
@nellicus I don't think so

**Comment by nellicus** [comment]
ok the purpose of this PR was to clarify a scenario we don't document which leads users to problem where installing/uninstalling plugins using the custom script fails when using both custom config and plugin path.

@tlrx do you suggest a complete rewrite explaining how plugins config paths work or just leaving this to address this dark corner?

**Comment by tlrx** [comment]
> @tlrx do you suggest a complete rewrite explaining how plugins config paths work or just leaving this to address this dark corner?

I think we should update the doc to make things easier to understand, yes.

**Comment by nellicus** [comment]
@tlrx sure I agree

so 
>do you suggest a complete rewrite explaining how plugins config paths work or just leaving this to address this dark corner or anything else?

I do not want this to get stalled.

CC @palecur @debadair

**Comment by clintongormley** [comment]
@nellicus I'm doing a big rewrite of the plugins documentation: see https://github.com/elastic/elasticsearch/pull/12040

Want to check that and see if anything needs updating there?

**Comment by nellicus** [comment]
ok @clintongormley I guess I don't have enough knowledge on 2.0 plugins however I'll take a look FWIW

**Comment by palecur** [comment]
Thanks for taking this on, Clinton. I'll take some time to review.

pe

**Pull request closed without merging**
