### PR TITLE
Block readiness on file settings being applied

### PR DESCRIPTION
**Pull request by rjernst**
The readiness service is supposed to wait on the cluster being formed as well as file settings being applied. Yet file settings application is only checked on the master node. Since master election itself does not guarantee file settings have been applied, non-master nodes may mark themselves as ready even though they should not yet accept requests.

This commit reworks how the readiness service looks ofr file settings being applied. Previously it only worked on the master node where it got a callback directly from the file settings service. With this change we now only look at cluster state. Note that this means the readiness service and file based settings are tightly coupled. In practice this was always the case as they are both meant to be used in cloud environments, but the coupling is a bit tighter now since the readiness service will never report ready unless file based settings exist.

### CODE REVIEW

**Review by williamrandolph — APPROVED** [review]
LGTM! It's a nice clean fix.

**Comment by williamrandolph** [comment]
Looks like a few related tests are failing here. Hopefully the fixes are not too bad.

**Review by ldematte — APPROVED** [review]
LGTM 2!

**Comment by rjernst** [comment]
> Looks like a few related tests are failing here. Hopefully the fixes are not too bad.

I've made a few adjustments. Primarily I changed the file settings reserved state to write an empty (-1) version when the file settings do not exist on the master node. That allows the readiness service to always look for the reserved state metadata, and check if there are any errors in the initial application.

**Review by williamrandolph — APPROVED** [review]
Oh, there was a lot going on with the tests.

Still LGTM.

**Pull request merged**
