### PR TITLE
Increase the minimum size of the management pool to 2

### PR DESCRIPTION
**Pull request by arteam**
Make sure that individual `wait_for_completion=true` requests don't block concurrent stats and cat requests.

See https://github.com/elastic/elasticsearch/issues/89564

### CODE REVIEW

**Review by DaveCTurner — DISMISSED** [review]
I don't think this fixes the bug that #89564 exposes unfortunately - if there were two concurrent calls to the list-tasks API then they could both deadlock within `TaskManager#waitForTaskCompletion` even after this change.

Instead, I think we should make `TaskManager#waitForTaskCompletion` async rather than blocking the management thread as it does today..

**Review by henningandersen — APPROVED** [review]
LGTM as a short term fix, provided that we follow up with a proper fix for the task management wait and in that fix lower the minimum again to 1.

**Comment by droberts195** [comment]
> Instead, I think we should make `TaskManager#waitForTaskCompletion` async rather than blocking the management thread as it does today.

I agree that is the ideal fix.  However, if that cannot be done in time for 8.5.0 then increasing the minimum number of threads to 2 at least keeps ESS in the same situation as it was in in 8.4 and earlier.  In 8.4 and earlier ESS told every node it had at least 2 processors to avoid strange lockups, and those strange lockups (undiagnosed at the time they were originally mentioned) were almost certainly the same problem as #89564.  In 8.5 ESS is going to tell nodes with one processor that they have one processor, so the strange lockups will be seen by ESS users on small nodes unless _something_ is done in Elasticsearch.  So by all means fix this properly for 8.5.0 if there's time, but _something_ has to be done for 8.5.0 even if that's a quick workaround.

**Comment by arteam** [comment]
@elasticmachine run elasticsearch-ci/packaging-tests-windows-sample

**Comment by arteam** [comment]
The commit went to the master branch before the 8.5 branch was cut, so this change *is* included in 8.5 and doesn't need a backport.

**Pull request merged**
