### PR TITLE
Squash the rest of o.e.rest.action

### PR DESCRIPTION
**Pull request by nik9000**
Squashes all the subpackages of `org.elasticsearch.rest.action` down to
the following:
- `o.e.rest.action.admin` - Administrative actions
- `o.e.rest.action.cat` - Actions that make tables for `grep`ing
- `o.e.rest.action.document` - Actions that act on documents
- `o.e.rest.action.ingest` - Actions that act on ingest pipelines
- `o.e.rest.action.search` - Actions that search

I'm tempted to merge `search` into `document` but the `document`
package feels fairly complete as is and `Suggest` isn't actually always
about documents either....

I'm also tempted to merge `ingest` into `admin.cluster` because the
latter contains the actions for dealing with stored scripts.

I've moved the `o.e.rest.action.support` into `o.e.rest.action`.

### CODE REVIEW

**Comment by nik9000** [comment]
I believe this is a net loss of about 10 packages. Mostly consolidating tiny packages into medium sized packages.

**Comment by nik9000** [comment]
Also package descriptions to all the packages in `org.elasticsearch.rest`.

**Comment by nik9000** [comment]
Marking it breaking-java because it moves some utility classes for handling REST. Plugins will have to change the import locations if they use them

**Comment by cbuescher** [comment]
LGTM

**Comment by nik9000** [comment]
Thanks for reviewing @cbuescher !

**Pull request merged**
