### PR TITLE
Fix BulkProcessor hangs for threads deadlocked (#44556)

### PR DESCRIPTION
**Pull request by suxinglee**
In #44556 bulk processor threads gets deadlocked, and Java application using BulkProcessing hangs without any data flush. This problem have been discussed in two issues. One way to solve this deadlock is add a single ScheduledThreadPoolExecutor instance for `FlushTask`.

### CODE REVIEW

**Comment by javanna** [comment]
hi @SuXingLee thanks for opening this PR! Would it be possible to add a test that recreates the scenario of the issue you have encountered, which fails without your fix and succeeds once you made your changes?

**Comment by jakelandis** [comment]
@SuXingLee - could you please review the latest comment ?

**Comment by codersky** [comment]
do we have any updates on this issue and what's the case this issue reproduced? thanks

**Comment by SuXingLee** [comment]
@jakelandis due to the modified of base branch, I close the current PR and open another PR  #46790 
  can you review this for me sometime?

**Pull request closed without merging**
