### PR TITLE
Adding example of running tests without a snapshot build

### PR DESCRIPTION
**Pull request by benwtrent**
It can be difficult to know how to run release builds. Certain changes require that tests run without a snapshot build (consider testing a feature behind a feature flag).

This adds a small doc line specifying what args to pass to run tests without a snapshot build.

### CODE REVIEW

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Comment by rjernst** [comment]
@benwtrent Is that line sufficient for you? I believe non snapshot builds will fail immediately because no public key is specified.

**Comment by rjernst** [comment]
In the past I've run this by pointing the sys prop for the key to the test public key under x-pack/license-tools

**Comment by benwtrent** [comment]
@rjernst It worked for me just recently on master. If you think there is a more appropriate command (that also works on past version), please feel free to update :). I am definitely no expert on our various combinations of gradlew test options.

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Review by rjernst — APPROVED** [review]
Thanks for the update. LGTM.

**Pull request merged**
