### PR TITLE
Introduce ordinal bytesref block

### LINKED ISSUE #106387: Ordinal-based BytesRef block for TSID
For large BytesRef tsid blocks, containing one or a few tsid, it may be more efficient to implement a dictionary and an array of ordinals instead of storing the BytesRef multiple times. Also, when designing such blocks, we might consider using the artificial 'global' ordinals (generated by the TimeSeriesSortedSourceOperator) so that consumers can take advantage of them.

Relates #105397

### PR DESCRIPTION
**Pull request by dnhatn**
This PR introduces ordinal-based blocks for BytesRef. These blocks consist of a pair: an IntBlock for ordinals and a BytesRefVector for the dictionary. Compared to the regular BytesRefBlock, these blocks are slower due to indirect access and consume more memory because of the additional ordinals block. However, they offer significant speed improvements and reduced memory usage when byte values are frequently repeated.

There are several use cases where these blocks can be beneficial:

1. Storing TSIDs of time series data streams.
2. Storing docvalues when the number of values exceeds the number of ordinals. This change has already been included in this PR.
2. Using in PackedValuesBlockHash for both hashing and reading keys.
3. Using in lookup execution in enrich
4. Faster filtering BytesRefBlock

Closes #106387

### CODE REVIEW

**Comment by dnhatn** [comment]
This change speeds up the multi_terms-keyword aggregation ~20%.

```
| multi_terms-keyword_esql_segment_partitioning |      0.371803    |      0.443191    |     0.07139 |  ops/s |  +19.20% |
| multi_terms-keyword_esql_segment_partitioning |      0.381713    |      0.467891    |     0.08618 |  ops/s |  +22.58% |
| multi_terms-keyword_esql_segment_partitioning |      0.382758    |      0.471101    |     0.08834 |  ops/s |  +23.08% |
| multi_terms-keyword_esql_segment_partitioning |      0.38536     |      0.476118    |     0.09076 |  ops/s |  +23.55% |
| multi_terms-keyword_esql_segment_partitioning |   2571.35        |   2066.35        |  -505.005   |     ms |  -19.64% |
| multi_terms-keyword_esql_segment_partitioning |   2596.37        |   2089.59        |  -506.789   |     ms |  -19.52% |
| multi_terms-keyword_esql_segment_partitioning |   2603.81        |   2108.53        |  -495.278   |     ms |  -19.02% |
| multi_terms-keyword_esql_segment_partitioning |   2571.35        |   2066.35        |  -505.005   |     ms |  -19.64% |
| multi_terms-keyword_esql_segment_partitioning |   2596.37        |   2089.59        |  -506.789   |     ms |  -19.52% |
| multi_terms-keyword_esql_segment_partitioning |   2603.81        |   2108.53        |  -495.278   |     ms |  -19.02% |
| multi_terms-keyword_esql_segment_partitioning |      0           |      0           |     0       |      % |    0.00% |
|     multi_terms-keyword_esql_doc_partitioning |      0.711119    |      0.895476    |     0.18436 |  ops/s |  +25.92% |
|     multi_terms-keyword_esql_doc_partitioning |      0.716804    |      0.898711    |     0.18191 |  ops/s |  +25.38% |
|     multi_terms-keyword_esql_doc_partitioning |      0.716807    |      0.898126    |     0.18132 |  ops/s |  +25.30% |
|     multi_terms-keyword_esql_doc_partitioning |      0.719157    |      0.903031    |     0.18387 |  ops/s |  +25.57% |
|     multi_terms-keyword_esql_doc_partitioning |   1385.86        |   1114.17        |  -271.691   |     ms |  -19.60% |
|     multi_terms-keyword_esql_doc_partitioning |   1445.26        |   1169.93        |  -275.333   |     ms |  -19.05% |
|     multi_terms-keyword_esql_doc_partitioning |   1504.46        |   1237.13        |  -267.326   |     ms |  -17.77% |
|     multi_terms-keyword_esql_doc_partitioning |   1385.86        |   1114.17        |  -271.691   |     ms |  -19.60% |
|     multi_terms-keyword_esql_doc_partitioning |   1445.26        |   1169.93        |  -275.333   |     ms |  -19.05% |
|     multi_terms-keyword_esql_doc_partitioning |   1504.46        |   1237.13        |  -267.326   |     ms |  -17.77% |
```

**Comment by nik9000** [comment]
I'll have a closer look soon. I'm worried that this could cause a slow down for other, non-ordinal BytesRef blocks. But maybe it'll be fine.

On the other hand, I think there's a ton of neat improvement we could make by having ordinal blocks in general - we load by ordinals, we could process those ordinals for something like `string_length` or comparisons. Or aggs. Lovely aggs.

**Review by nik9000 — APPROVED** [review]
I think it's worth doing.

**Comment by dnhatn** [comment]
Thanks @nik9000.

**Pull request merged**
