### PR TITLE
Remove snapshot build restriction for match and qstr functions

### PR DESCRIPTION
**Pull request by carlosdelest**
Includes `match` and `qstr` functions in non-snapshot buids, in order to provide tech preview access for users.

This removes checks on tests and lexer / parser grammar

### CODE REVIEW

**Review by ChrisHegarty — APPROVED** [review]
The removal of the snapshot flag looks correct to me.  Where do we say in docs that the functions are Tech Preview? Is it covered by `"preview" : true` ?

**Review by ioanatia — APPROVED** [review]

**Comment by carlosdelest** [comment]
@elasticmachine test this please

**Comment by drewdaemon** [comment]
Am I correct in understanding that `match` is only applicable in a `WHERE` command?

**Comment by carlosdelest** [comment]
The release test CI failure us caused by an unrelated test failure: https://buildkite.com/elastic/elasticsearch-pull-request/builds/36049#01928140-b187-4821-bd89-e4c08c244e72/6-2132

This failure is tracked in https://github.com/elastic/elasticsearch/issues/114135

**Comment by carlosdelest** [comment]
> Am I correct in understanding that `match` is only applicable in a `WHERE` command?

@drewdaemon correct. Both `match` and `qstr` functions can only be used as part of `WHERE`.

**Comment by carlosdelest** [comment]
> The removal of the snapshot flag looks correct to me. Where do we say in docs that the functions are Tech Preview? Is it covered by "preview" : true ?

@ChrisHegarty yes - you can see in the [generated docs](https://github.com/elastic/elasticsearch/blob/main/docs/reference/esql/functions/layout/match.asciidoc#L7) that there's a reference to the tech preview because of that.

**Comment by carlosdelest** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.x|[](https://github.com/elastic/elasticsearch/pull/114793)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

**Pull request merged**
