### PR TITLE
Use pre-JDK9 style FilePermissions on JDK9

### PR DESCRIPTION
**Pull request by ywelsch**
JDK9 removed pathname canonicalization when constructing FilePermission objects, which breaks some of the FilePermissions added by Elasticsearch. This commit adds the system property `jdk.io.permissionsUseCanonicalPath` which makes JDK9 behave like JDK8 w.r.t. FilePermissions (see also discussion on #21534).

Successfully ran `gradle clean check` on JDK9 b144 with this.

### CODE REVIEW

**Comment by s1monw** [comment]
LGTM

**Comment by rjernst** [comment]
Shouldn't we add this property to the default `jvm.options` as well? It will just be ignored for java 8?

**Comment by ywelsch** [comment]
yes, it's just ignored for java 8 (as any unknown system property). Good catch with the `jvm.options`. I've pushed 6f69f54 to add it there as well.

**Comment by rjernst** [comment]
LGTM too.

**Comment by rjernst** [comment]
Also, I don't think this needs to go into 5.0.2.

**Comment by jasontedor** [comment]
> Also, I don't think this needs to go into 5.0.2.

We do 5.0 branch builds on JDK 9, so I think it should.

**Comment by rjernst** [comment]
Oh good point @jasontedor

**Comment by ywelsch** [comment]
Thanks @s1monw @rjernst @jasontedor

**Pull request merged**
