### PR TITLE
[Watcher] Log timestamps related to watcher start and schedule times

### PR DESCRIPTION
**Pull request by gmarouli**
**Bug**
We have observed that after an upgrade Watcher uses an older date in the query and falsely triggers. Unfortunately, we have not enough information to find out where did this false date come from. 

Because we were not able to reproduce it we wanted to add some extra logging that might help us understand what's going on.

These logging includes:
- Log the observed time by the system when Watcher loaded the components.

### CODE REVIEW

**Comment by gmarouli** [comment]
@elasticmachine update branch

**Review by joegallo — APPROVED** [review]
LGTM, @masseyke is there any other logging you think would be helpful to have here?

**Comment by gmarouli** [comment]
> I added `v8.12.0` to the labels, the risk of a little additional logging is very low, and I think it would be worthwhile to get this out sooner rather than later -- just my opinion, though, feel free to overrule me.

I was planning to backport it but I thought we add the label `v8.12.1` and when the next BC is build the release person is changing the label, right?

**Comment by gmarouli** [comment]
@elasticmachine update branch

**Comment by joegallo** [comment]
> I was planning to backport it but I thought we add the label v8.12.1 and when the next BC is build the release person is changing the label, right?

There's automation that should fuss with the labels appropriately on PRs (both open and merged!) -- it'll choose the right patch label based on what actually does end up in the last 8.12.0 BC. But yes, I think you're quite right, the expectation is that `v8.12.1` is the right label to have on this PR right now, I'm not sure whether it existed when I added the label earlier. 🤷

**Comment by masseyke** [comment]
Sorry for the delayed response -- yeah those seem like the places to me where it makes sense to log the time. I'm actually wondering if we ought to make the one in Watcher info-level since it only happens once at startup, and it might be really useful to have if some other customer runs into this problem and doesn't have debug logging enabled.

**Review by masseyke — APPROVED** [review]
LGTM

**Pull request merged**
