### PR TITLE
Avoid `shallowSizeOfInstance` in closure

### LINKED ISSUE #101502: [CI] LeastTests testEvaluateInManyThreads {TestCase=(<mv_boolean>, <mv_boolean>, <mv_boolean>, <mv_boolean>, <mv_boolean>, <mv_boolean>, <mv_boolean>, <mv_boolean>) null in 4} failing
Only seems to be a problem on Windows? Reproduced on a second attempt of the same PR.

**Build scan:**
https://gradle-enterprise.elastic.co/s/35sfdkqihafki/tests/:x-pack:plugin:esql:test/org.elasticsearch.xpack.esql.expression.function.scalar.conditional.LeastTests/testEvaluateInManyThreads%20%7BTestCase=(%3Cmv_boolean%3E,%20%3Cmv_boolean%3E,%20%3Cmv_boolean%3E,%20%3Cmv_boolean%3E,%20%3Cmv_boolean%3E,%20%3Cmv_boolean%3E,%20%3Cmv_boolean%3E,%20%3Cmv_boolean%3E)%20null%20in%204%7D
**Reproduction line:**
```
gradlew ':x-pack:plugin:esql:test' --tests "org.elasticsearch.xpack.esql.expression.function.scalar.conditional.LeastTests.testEvaluateInManyThreads {TestCase=(<mv_boolean>, <mv_boolean>, <mv_boolean>, <mv_boolean>, <mv_boolean>, <mv_boolean>, <mv_boolean>, <mv_boolean>) null in 4}" -Dtests.seed=EDCD919EFFF3F9E4 -Dtests.locale=es-PA -Dtests.timezone=Pacific/Marquesas -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.esql.expression.function.scalar.conditional.LeastTests&tests.test=testEvaluateInManyThreads%20%7BTestCase%3D(%3Cmv_boolean%3E,%20%3Cmv_boolean%3E,%20%3Cmv_boolean%3E,%20%3Cmv_boolean%3E,%20%3Cmv_boolean%3E,%20%3Cmv_boolean%3E,%20%3Cmv_boolean%3E,%20%3Cmv_boolean%3E)%20null%20in%204%7D

**Failure excerpt:**
```
java.lang.Exception: Test abandoned because suite timeout was reached.

  at __randomizedtesting.SeedInfo.seed([EDCD919EFFF3F9E4]:0)

```

### PR DESCRIPTION
**Pull request by dnhatn**
```
  2> "pool-409-thread-5" ID=2115 RUNNABLE
  2> 	at java.base@21.0.1/java.security.AccessController.getStackAccessControlContext(Native Method)
  2> 	at java.base@21.0.1/java.security.AccessController.isPrivileged(AccessController.java:754)
  2> 	at java.base@21.0.1/java.security.AccessController.executePrivileged(AccessController.java:777)
  2> 	at java.base@21.0.1/java.security.AccessController.doPrivileged(AccessController.java:319)
  2> 	at app//org.apache.lucene.util.RamUsageEstimator.shallowSizeOfInstance(RamUsageEstimator.java:598)
  2> 	at app//org.elasticsearch.compute.data.BlockRamUsageEstimator.sizeOfBitSet(BlockRamUsageEstimator.java:24)
  2> 	at app//org.elasticsearch.compute.data.BytesRefArrayBlock.ramBytesEstimated(BytesRefArrayBlock.java:108)
  2> 	at app//org.elasticsearch.compute.data.BytesRefArrayBlock.ramBytesUsed(BytesRefArrayBlock.java:113)
  2> 	at app//org.elasticsearch.compute.data.BytesRefArrayBlock.close(BytesRefArrayBlock.java:147)
  2> 	at app//org.elasticsearch.compute.data.Block$Ref.close(Block.java:250)
  2> 	at app//org.elasticsearch.xpack.esql.expression.function.AbstractFunctionTestCase.lambda$testEvaluateInManyThreads$1(AbstractFunctionTestCase.java:446)
  2> 	at app//org.elasticsearch.xpack.esql.expression.function.AbstractFunctionTestCase$$Lambda/0x000000313d602f28.run(Unknown Source)
  2> 	at java.base@21.0.1/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
  2> 	at java.base@21.0.1/java.util.concurrent.FutureTask.run(FutureTask.java:317)
  2> 	at java.base@21.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
  2> 	at java.base@21.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
  2> 	at java.base@21.0.1/java.lang.Thread.runWith(Thread.java:1596)
  2> 	at java.base@21.0.1/java.lang.Thread.run(Thread.java:1583)

```

The test failure relates to the security manager, and this PR calculates the base RAM usage of BitSet statically, similar to other instances.

Closes #101502

### CODE REVIEW

**Comment by alex-spies** [comment]
@dnhatn , I think you dropped a digit when linking the issue - https://github.com/elastic/elasticsearch/issues/10150 is from 2015 :)

**Review by alex-spies — APPROVED** [review]
The change itself LGTM.

**Comment by dnhatn** [comment]
Thanks Alex. This issue should be #101502 instead.

**Review by nik9000 — APPROVED** [review]

**Comment by dnhatn** [comment]
@alex-spies @nik9000 Thanks for reviews.

**Pull request merged**
