### PR TITLE
SQL: Switch JDBC driver to libs/geo objects for geo_points

### LINKED ISSUE #35767: SQL: representation of geo objects in JDBC
When a geo_shape or a geo_point is sent to the JDBC client, we need to represent it as some sort of the object when it is returned by JDBC's JdbcResultSet.getObject(int column) method. There are several possible alternatives here including

- **WKT String**. Currently, geo points and geo shapes are serialized as WKT-formatted strings and we don't do any additional transformations on the JDBC side, so we are returning them as string. This is the simplest and the most straightforward solution, however, it provides minimal benefit for the users since they will have to load this string into some other object in order to do anything with it.

- **JTS Geometry**. This is what H2 is currently using. One problem with this solution is that we will have to require or ship JTS library and we will not be able to release GEOSQL until H2GIS 1.5.0 is released. We are using H2GIS for testing it and it is still using JTS 1.14 at the moment, the rest of ES is using JTS 1.15. So, if we cannot ship JDBC with JTS 1.14, but we cannot test it with JTS 1.15. 

- **Lucene's geo objects**. Lucene now has its own set of Geometry objects that we could use. However, there are 2 missing pieces that prevent me from going ahead with this solution. 1) We will need to include these objects into our JDBC library and while the objects themselves are quite lean they have some dependencies on org.apache.lucene.geo.GeoUtils that pulls tons of other stuff. So, we would need to do some cleanup on the Lucene level to remove unnecessary dependencies. 2) we will need a way to deserialize the objects on the JDBC side and currently all reasonable parser (for WKT and GeoJSON) are integrated with ShapeBuilders that also have tons of dependencies including JTS. So, if we go with this solution, we need to start a massive refactoring of GeoShape to extract WKT or GeoJSON parser from it.

- **lib/geo minimum dependency Geometry class hierarchy**. After additional discussions with @nknize another option came up with adding a minimal class hierarchy to `lib/geo` with just data classes and parsers (WKT and WKB). It might be possible to also reuse this hierarchy in other places, but that requires further investigation.

### PR DESCRIPTION
**Pull request by imotov**
Switches JDBC driver to use libs/geo objects when server returns a
geo_point. It also removes separate functions for geo points and geo
shapes, which should simplify developing of geo functions.

Closes #35767

### CODE REVIEW

**Comment by imotov** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by costin** [comment]
If I understand correctly, this PR unifies the aswkt function across geo points and geo shape.
Is it correct to assume going forward that geo functions will support both types as input?

**Review by costin — APPROVED** [review]
LGTM.
I'd like @bpintea opinion as well to make sure the type format is supported on the ODBC side as well.
Besides WKT, are there any plans for other formats (WKB or geojson)?

**Comment by bpintea** [comment]
> LGTM.
> I'd like @bpintea opinion as well to make sure the type format is supported on the ODBC side as well.
> Besides WKT, are there any plans for other formats (WKB or geojson)?

@costin I've added a comment to  https://github.com/elastic/elasticsearch/pull/39204#discussion_r261556565.

JDBC allows shipping the defined private extensions along with the driver. In ODBC this concept doesn't exist: the interface is defined in the standard and any new extension is described [through its characteristics](https://docs.microsoft.com/en-us/sql/odbc/reference/develop-app/retrieving-data-type-information-with-sqlgettypeinfo), not by its [format](https://docs.microsoft.com/en-us/sql/odbc/reference/appendixes/c-data-types). 

So, IMO we're free to pick whatever ways to encode the data, for as long as we can export it into a common format, either directly (by maybe using WKT/B or GeoJSON) or indirectly through function transformations.

**Comment by imotov** [comment]
> Is it correct to assume going forward that geo functions will support both types as input?

Yes, and it will be easier now since we will have to write only one function. When I started implementing other functions earlier, having 2 sets of functions was a bit problematic. 

>  Besides WKT, are there any plans for other formats (WKB or geojson)?

We are planning to eventually add ST_ functions that will support WKB and maybe other formats. However, I think it would make sense to stick with WKT to transport geo data between server and client for now. I think if we will switch to CBOR as a protocol, we can switch to WKB at that moment. For now, it makes little sense, I think.

**Pull request merged**
