### PR TITLE
[Profiling] Add status API

### PR DESCRIPTION
**Pull request by danielmitterdorfer**
With this commit we add a new REST API to the profiling plugin that allows to retrieve its current status.

### CODE REVIEW

**Comment by danielmitterdorfer** [comment]
The API can be called as follows: `GET /_profiling/status` and will return three boolean flags:

```json
{
  "enabled" : true,
  "active" : false,
  "resources_created" : false
}
```

* `enabled` indicates whether the plugin is enabled at all
* `active` indicates whether index management is active
* `resources_created` indicates whether all resources (index templates) have been created successfully

**Review by jbcrail — COMMENTED** [review]
No specific feedback about the code, which looks good.

My only comment so far is about the response and how a client would use it. For instance, given that `resources_created` states whether all templates, indices, etc have been created, I can imagine that we may eventually want a way to capture additional resource states, such as "creation in-progress" or "creation failed".

Relatedly, is there an existing way for us to surface errors in the bootstrapping process to users via Kibana?

**Comment by danielmitterdorfer** [comment]
Thanks for the feedback. Due to the way this is handled in the underlying infrastructure it's not possible to surface errors (or show progress). However, I'd also argue that cases where it's not possible to create index templates are rather rare and that would warrant a support case.

**Comment by rockdaboot** [comment]
Just in case of future extensions and also for readability of the answer, I prefer more verbose keywords.
"enabled" (what is enabled ?) -> "profiling_enabled"
"active" (what is active ?) -> "index_mgmt_active"
"resources_created" (which resources ?) -> "index_templates_created"

Another option is to extend the JSON schema like (example, maybe over the top :))
```
{
  "profiling": {
    "enabled": true
  },
  "index_management": {
    "active": true
  },
  "resources": {
    "index_templates": {
      "created": true
    }
  }
}
```

**Comment by danielmitterdorfer** [comment]
The field names were loosely inspired by the XPack Status API that we'll need to implement for licensing at a later point but I see your point. How about this?

* `enabled` stays as is because that API is already called in the context of profiling and there should not be any doubt what is enabled when we call that API?
* `active` -> `resources_managed`
* `resources_created`

I'd like to keep a more abstract term (here "resources") because we don't only manage index templates but also indices and ILM policies. Wdyt?

**Review by rockdaboot — APPROVED** [review]
LGTM

**Review by jbcrail — APPROVED** [review]
Looks good :+1:

**Pull request merged**
