### PR TITLE
Cleanup some redundancies around DfsQueryPhase

### PR DESCRIPTION
**Pull request by original-brownbear**
Just 2 simple cleanups: 
No need to add the result consumer to the context another time, it's already added to it in the constructor of `SearchDfsQueryThenFetchAsyncAction`. Also, no need to feed `this` and `this.results` to `getNextPhase` explicitly, there's only a single call to this method so we can safely clean up the redundant arguments.

### CODE REVIEW

**Review by javanna — APPROVED** [review]

**Comment by original-brownbear** [comment]
@elasticmachine update branch

**Comment by original-brownbear** [comment]
@elasticmachine update branch

**Comment by original-brownbear** [comment]
Merging with the Windows thing failing, someone just explained in Slack that this is a CI only issue for sure.

**Comment by original-brownbear** [comment]
@elasticmachine update branch

**Pull request merged**
