### PR TITLE
Don't run snapshot/restore tests for proxy support testing of GCS

### PR DESCRIPTION
**Pull request by arteam**
We don't need to run tests for snapshot/restores to verify that the proxy works, just basic tests for reading/writing should be enough. They generate quite a big stress on the proxy server which uses blocking APIs and isn't supposed to be very performant.

See #93824

### CODE REVIEW

**Comment by arteam** [comment]
@elasticmachine update branch

**Review by original-brownbear — COMMENTED** [review]
Not sure I understand why the server would run into EOF here because it's not very performant. Wouldn't it be nice to have full validation that all request types go through the proxy correctly?

**Comment by arteam** [comment]
> Not sure I understand why the server would run into EOF here because it's not very performant. Wouldn't it be nice to have full validation that all request types go through the proxy correctly?

@original-brownbear Sorry for not being clear! I have no evidence that these tests cause #93824, I just find that these tests are excessive and create some complex HTTP scenarios which might contribute to HTTP parsing issues if requests are parsed manually.

**Comment by fcofdez** [comment]
@arteam I agree with Armin, I think we should validate that this repository works with a proxy in all scenarios. I think that if we merge the new proxy implementation this shouldn't be an issue anymore?

**Comment by arteam** [comment]
Yeah, that's fine! I think these tests were quite slow with a handwritten HTTP server, but it's much better with a proper HTTP server.

**Pull request closed without merging**
