### PR TITLE
Support removing multiple plugins at once in the CLI

### LINKED ISSUE #66476: Support installing and removing plugins when a Docker container starts
Our current advice regarding plugins and running Elasticsearch in Docker is to extend the image and install all the required plugins. However, this may not be practical if there is a need to add or remove plugins dynamically.

We would therefore like to have a mechanism to specify the desired plugins when a container starts. Note that in the case where the `plugins` directory has been persisted across restarts, e.g. as a bind-mounted volume, then plugins may be installed that now need to be removed.

### PR DESCRIPTION
**Pull request by pugnascotia**
Closes #66476. Add support for removing multiple plugins at the same time to `elasticsearch-plugin`. Also change references from "plugin name" to "plugin id", to align better with the installer class.

### CODE REVIEW

**Comment by mark-vieira** [comment]
I think the key bit that came from our discussion with the Cloud folks regarding https://github.com/elastic/elasticsearch/issues/66476 is that they need a convenient way to remove _all_ plugins, that way "syncing" plugins becomes a two step operation where where we first (a) remove all currently installed plugins and then (b) install (potentially reinstalling ones we just removed) the set of plugins we want.

I suppose some combination of list + compare with final set + remove + install would work but it definitely complicates things. @alpar-t @mieciu I think as we discussed the request was for a "remove all plugins" flag, yes? Is that still what we want or is what @pugnascotia has provided in the PR sufficient?

**Comment by mark-vieira** [comment]
Thinking about this more, if we have to do multiple invocations anyway couldn't we _today_ simply do something like `elasticsearch-plugin list | xargs elasticsearch-plugin remove && elasticsearch-plugin install <list of plugins>`? Realistically some kind of `elasticsearch-plugin remove --all` is just a convenience for that first bit.

**Comment by alpar-t** [comment]
I've looked at it some more following our initial discussion. What @mark-vieira is suggesting would work, it's essentially similar tow hat we are doing: 
```
export ALREADY_INSTALLED=$(${ELASTICSEARCH_HOME}/bin/elasticsearch-plugin list | grep -v "^warning:" | sed '/^\t/d' | sort)
```  
We want to remove the custom script, and I don't want to hard code the text output of the CLI in the allocator, as that effectively means that the text has to stay compatible throughout a major. It would seem to me that we need more formal  interfaces for anything that gets hard coded in the allocator for this reason.

Also note, that we are sensitive to the number of cli calls due to JVM startup cost that's not trivial and it delays the time it takes to set up a deployment in cloud. I think we still have __potentially__ 3 Today (list, add, remove) in the worst case scenario,  but there's custom logic to detect if we can only add (first boot) and will only ever run the add and remove both if a plugin is actually being added and removed.

The fundamental requirement is to give cloud a __fast__ way to declare the plugins that need to be installed, using a flow that you are conferrable having in the allocator. As ECE 3.0 goes out, it has to support 8.0 and all future 8.x versions too, we only require an ECE upgrade to support new features. It would be good to make sure that the way cloud does things is explicitly covered in the ES code base to catch any incompatible change early.

**Comment by pugnascotia** [comment]
That approach would help for #61385 as well.

**Comment by mark-vieira** [comment]
> Also note, that we are sensitive to the number of cli calls due to JVM startup cost that's not trivial

Indeed, but attributing this to "JVM startup" is a common misconception. You can create very responsive Java CLI tools. JVM startup is actually quite minimal for "lightweight" applications.

```
$ time java Main
Hello World!

real	0m0.045s
user	0m0.030s
sys	0m0.010s
```

The problem is (as with most everything in Elasticseach) these tools bring in `:server` which in turn brings in all sorts of other cruft. We don't _use_ a lot of this but just having all that stuff on the classpath adds a ton of startup overhead. We could make these much more efficient by eliminating those dependencies but that's a whole other ordeal probably.

**Comment by mark-vieira** [comment]
> The fundamental requirement is to give cloud a **fast** way to declare the plugins that need to be installed

Sure, but we're talking 500ms per invocation here.

```
$ time build/distribution/local/elasticsearch-8.0.0-SNAPSHOT/bin/elasticsearch-plugin list
warning: ignoring JAVA_HOME=/home/mark/.sdkman/candidates/java/current; using bundled JDK

real    0m0.540s
user    0m1.485s
sys     0m0.125s
```

So adding a `remove --all` option would reduce startup time by 500ms and adding some kind of "sync" command which simply does the diffing for us so we could do this in a single invocation would buy us 1s. I'm not sure to what degree we track this kind of thing in our perf testing but I suspect there are loads of things that could contribute 1s to Elasticsearch startup time that don't come close to landing on our radar.

**Comment by mark-vieira** [comment]
https://github.com/elastic/elasticsearch/issues/61385 is a compelling use case but I don't think it necessarily helps here if we indeed want to ensure that _only_ the plugins supplied are installed. That is yet another use case.

**Comment by mark-vieira** [comment]
> The fundamental requirement is to give cloud a fast way to declare the plugins that need to be installed, using a flow that you are conferrable having in the allocator. As ECE 3.0 goes out, it has to support 8.0 and all future 8.x versions too, we only require an ECE upgrade to support new features. It would be good to make sure that the way cloud does things is explicitly covered in the ES code base to catch any incompatible change early.

I'm not sure I understand the concern here. As described you can accomplish today what is required, although we can quibble over what we define as "fast". Obviously changing how the CLI tools operate would be a breaking change like any other. Is you concern that we change the way the `elasticsearch-plugin` tool works such that stringing these command together will no longer work?

**Comment by mark-vieira** [comment]
FWIW, I think we should consider CLI tool output a contractual aspect same as we do any other behavior of it. This shouldn't change in a major version, we could also add explicit test coverage for this use case.

Your example above is unnecessarily complex. There's no need to filter out the "warning" messages as these are sent to stderr and I'm not sure what the purpose of sending things through `sed` or sorting the resultant list is for. I tested the locally and it works just fine. As mentioned, we can add explicit testing for this, but maybe that's just as much work as adding `remove --all`.

```
./bin/elasticsearch-plugin list | xargs -r -L 1 ./bin/elasticsearch-plugin remove
```

**Comment by alpar-t** [comment]
@mark-vieira 
I did a few more tests, the invocation of the cli is indeed faster than I interpolated from how long it takes to install a plugin.
I'm not concerned about 1 second or less, nor think we should make this effort about improving this.  Perhaps @mieciu  could help with some exact measurement of how long things take now: e.g. when a deployment is created and when a deployment is restarted (I suspect these will be different because we only run a list operation or maybe not even that if nothing needs to be changed). I'm ok with not making things worse than they are.  

My other concern was that the textual output of the cli is not something that topically has a backwards compatibility attached to it.  If you're saying that you'll make sure to keep it so that piping works, I have no concern, just wanted to make it explicit. 

@mark-vieira @pugnascotia for clarity, could you call out the specific steps cloud would need to do; e.g. create ES container, wait for something, like ES to start up or can we race with container startup ? Then the commands to run with docker exec, then probably restart the container.  Also think of what happens if any of the steps fails and the process retries from the start (calling it out just for completeness).  If we're no worse off time wise it's all good from my side,  I can start a discussion to get feedback about implementing it in the allocator  from the relevant teams (it's not my domain).  If it's something we end up doing might be worth adding it to docs and/or tests,  from a quick google search of "elasticasearch docker plugin" there seems to be a lot of interest on the topic but only a relatively old elastic blog post.

**Comment by pugnascotia** [comment]
I think we want to avoid anything involving racing with container startup.

I was thinking about whether the problem, in general terms, is the need to perform actions in the container before ES starts. We _could_ support a startup hook in the Docker image so that a user-provided script is called by our entrypoint script before it calls ES. Now, clearly this gives a lot of scope to break, well, everything, but then give that you can override anything about how ES runs in Docker, it might not be that bad overall.

So you could have a script:

```shell
#!/bin/bash
set -euo pipefail
$ES_HOME/bin/elasticsearch-plugin list | xargs $ES_HOME/bin/elasticsearch-plugin rm
$ES_HOME/bin/elasticsearch-plugin install --batch repository-s3 quota-aware-fs # ... etc
```

Then e.g.

```shell
docker run \
  -e ES_USER_SCRIPT=/install-plugins.sh \
  -v $PWD/install-plugins.sh:/install-plugins.sh \
  elasticsearch:test
```

The downside with this approach is that's kind of abdicating responsibility for startup - but if we provide the right tools, and an opportunity to use them at the right point, maybe that's OK?

**Comment by mark-vieira** [comment]
> I was thinking about whether the problem, in general terms, is the need to perform actions in the container before ES starts.

Haha, I just mentioned such a thing in our email thread. What I suggested was a general place you can mount in "setup" scripts. There is precedent for this kind of pattern, for example, postgres allows you to define ["initialization scripts"](https://github.com/docker-library/docs/blob/master/postgres/README.md#initialization-scripts) for things like creating users, etc.

I like this pattern because we provide CLI tools for these things for a reason and we risk going down the path of introducing awkward Docker idioms for the same thing, rather than just pointing people to the already thoroughly tested and documented CLI tools. Understandably what we are describing in this issue is providing _conveniences_ for those things, but we risk due to constraints these things starting to diverge.

**Comment by alpar-t** [comment]
Echoing this from the email thread, I'm fine with the approach, but I think to meet the initial goal of stack teams owning how products run in cloud, the ES team would need to provide such a script, so the deliverables would be a docker image + a startup script. Both of them would have the same lifecycle in terms of builds and versions.

**Comment by pugnascotia** [comment]
@alpar-t can you elaborate on what you mean when you say "script"? I ask because looked again at the logic that Cloud uses in their custom entrypoint for installing plugins, and I don't see the ES team being able to build an equivalent.

**Comment by mark-vieira** [comment]
> but I think to meet the initial goal of stack teams owning how products run in cloud

There's a lot of ambiguity in such a statement, and perhaps this becomes a better discussion for a dev issue. I'm not sure the line here is well defined.

>  ES team would need to provide such a script, so the deliverables would be a docker image + a startup script

Yeah, I don't think this would be completely appropriate depending on the script. What stack should own is _behavior_ and the integration points. To me, I consider the scripts/cli-tools the integration point. I'm not sure how the stack would provide a startup script whose job is to install cloud user configured plugins. Where do we get the list of plugins? How/when should we decide to install them, etc? These IMO are clearly cloud concerns.

We still seem to be struggling to come to agreement on what the real requirement is here, as we've now gotten distracted by this "no more cloud scripts" requirement. Realistically my preference is to lean more towards things that make it easier for cloud to inject customization into the image, rather than build very cloud specific features into the image. I believe this approach is going to be better for both parties, as it also means much less version-specific logic in cloud to deal with stuff like "oh, ES version x doesn't support env var y".

I'm perfectly fine with syncing up again on this, perhaps bringing @bleskes into the conversation. I think we need some clarification on where to draw the lines of responsibility between stack and cloud so we can have a consistent approach to implementing things like this. I think once we do that we can then objectively look at a use case and say "yep, that should go in the stack image".

**Comment by mark-vieira** [comment]
Also back to the point of this PR, now thinking about it I think this _is_ useful given the current workflow in Cloud. Specifically because plugins are removed with `--purge`, so doing a `remove -all --purge` + `install` would go very badly :wink: 

I think this at the very least improves the JVM startup concern as now this is at least a constant time operation in terms of JVM overhead as we have list -> remove -> add. And even then we could potentially skip some of those steps if there a) nothing to remove or b) nothing to add. This at least makes removal consistent with installation in that we don't have to do these things in a loop.

My vote is to move forward with adding the capability in this PR, and if need be, continue the discussion on how this integrates with cloud elsewhere.

**Review by mark-vieira — APPROVED** [review]

**Comment by pugnascotia** [comment]
@elasticmachine update branch

**Comment by pugnascotia** [comment]
Backported to `7.x` in 119ba5ac655.

**Pull request merged**
