### PR TITLE
[ML][HLRC] adds new running_state field to datafeed stats (#73926)

### PR DESCRIPTION
**Pull request by benwtrent**
Adds the new `running_state` field to the High Level REST client. 

The new field is introduced in 7.14 through PR: https://github.com/elastic/elasticsearch/pull/73926

### CODE REVIEW

**Comment by benwtrent** [comment]
ping @elastic/ml-core

**Review by droberts195 — APPROVED** [review]
LGTM

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Comment by benwtrent** [comment]
run elasticsearch-ci/part-1

**Pull request merged**
