### PR TITLE
Rename Search Template REST spec names

### PR DESCRIPTION
**Pull request by tlrx**
Many REST API specs are named according to their domain of competence: `snapshot.*.json`, `indices.*.json`, `tasks.*.json` etc

This commit renames Search Template specs so that they now start with `search.template.` prefix. It also removes a duplicate `search_template.json` (replaced by `search.template.json`)

### CODE REVIEW

**Comment by clintongormley** [comment]
@tlrx I wouldn't do this. The dotted portions of the name represent namespaces in the client. By changing `search_template` to `search.template` we now need to add yet another namespace, which contains very few methods.

**Comment by tlrx** [comment]
I wanted to improve the naming because files like `get_template.json` actually refers to /_search/template/ endpoint and I think it's not obvious at the first sight.

There's still a duplicate between `search_template.json` and `template.search.json` so if I follow your point I should remove the latter, as well as renaming `template.msearch.json` to `msearch_template.json`... right?

**Comment by clintongormley** [comment]
OK I've just looked through all of the various template APIs.  I think we leave get/put/delete_template as they are, leave search_template as it is, and rename template.msearch -> msearch_template

**Comment by tlrx** [comment]
Thanks @clintongormley . I updated the tests and specs according to your comment.

**Comment by clintongormley** [comment]
LGTM - I would just rename the `template.msearch` test folder to `msearch_template`

**Comment by tlrx** [comment]
Thanks @clintongormley !

**Pull request merged**
