### PR TITLE
Do not refresh all indices in TransportBulkAction

### PR DESCRIPTION
**Pull request by tlrx**
Since we know which indices were involved in the Bulk request we can refresh only those instead of all indices.

Relates #93160

### CODE REVIEW

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Comment by tlrx** [comment]
Thanks David. Actually I think the refresh should also use indices options that expands to lenient open and hidden indices.

**Review by DaveCTurner — APPROVED** [review]
LBTM (good -> better :grin: )

Do we have test coverage for this? We should add some if not.

**Comment by tlrx** [comment]
Thanks David. I'll add a test in a follow up.

**Pull request merged**
