### PR TITLE
[Inference API] Add completion task type docs

### PR DESCRIPTION
**Pull request by timgrein**
This PR adds docs for the new `completion` task type

### CODE REVIEW

**Review by davidkyle — COMMENTED** [review]
Please can you add an example of using completion in POST

**Comment by timgrein** [comment]
> Please can you add an example of using completion in POST

Added an example for a completion to the `POST` docs 👍

**Review by davidkyle — APPROVED** [review]
LGTM

**Review by szabosteve — APPROVED** [review]
Thank you for adding the docs, LGTM!

**Pull request merged**
