### PR TITLE
Internal external monitoring docs

### PR DESCRIPTION
**Pull request by cachedout**
This is a DRAFT pull-request to serve as point of discussion for an overhaul of some of the monitoring docs.

This is *not* a final proposal by any means but more of an experiment to see how the docs would look if we radically pared them back from their current state.

### CODE REVIEW

**Comment by cachedout** [comment]
jenkins re-test this

**Comment by cachedout** [comment]
@lcawl Have you had a chance to look at this? Also, could you walk me through the steps I'd need to follow in order to get a preview of these changes online or point me instructions for how to do so?

**Comment by debadair** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Comment by lcawl** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Comment by lcawl** [comment]
You can preview these changes now here: http://elasticsearch_47818.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/monitor-elasticsearch-cluster.html

**Comment by lcawl** [comment]
I agree that if we can stop having both methods in the documentation (i.e. either Beats or exporters), it makes the instructions much simpler. There are two pages that I think we should consider still including, however:
1) https://www.elastic.co/guide/en/elasticsearch/reference/master/monitoring-production.html
This page was intended to cover the bigger picture of monitoring a cluster (in particular one where you're sending data to a separate monitoring cluster) and has pointers to steps required on Kibana, Logstash, etc.  I think that big picture procedure still has value.
2) https://www.elastic.co/guide/en/elastic-stack-overview/master/esms.html
I haven't moved this page to its new home yet (due to some dependencies I need to clean up), but it's also a higher-level procedure about how to collect monitoring data from various products and route it to ESMS. Hopefully it can have a home in this revamped documentation set too.

**Comment by cachedout** [comment]
I'm going to close this for now since it was just a proposal. If anybody would like to take over ownership of this, feel free to grab these commits or use them as you see fit. Thanks!

**Pull request closed without merging**
