### PR TITLE
[DOCS] Move sql to docs

### PR DESCRIPTION
**Pull request by lcawl**
Related to https://github.com/elastic/elasticsearch/issues/30665

This PR moves the content from x-pack/docs/en/sql to docs/reference/sql

### CODE REVIEW

**Review by costin — APPROVED** [review]
LGTM

**Review by nik9000 — COMMENTED** [review]
I think this'll break the docs build because `sql-tests` will be in the wrong spot.

**Comment by lcawl** [comment]
@nik9000 It worked locally for me.  Did you encounter an error?

**Comment by nik9000** [comment]
> @nik9000 It worked locally for me. Did you encounter an error?

No, I was just eyeballing it. I think I made a mistake. It should work.

**Review by nik9000 — APPROVED** [review]

**Comment by lcawl** [comment]
Backported to 6.x and 6.3 via https://github.com/elastic/elasticsearch/commit/70357934d5d770d02b4b57e4ce4b81e040e8d674 and https://github.com/elastic/elasticsearch/commit/240ae2395d92331edf0148e753dd27c36b1f93a5

**Pull request merged**
