### PR TITLE
[Style] Fix line length violations for threadpool, indexing, and script packages

### PR DESCRIPTION
**Pull request by jdconrad**
This fixes line length violations in several files across the threadpool, indexing, and script packages.

### CODE REVIEW

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by jdconrad** [comment]
@rjernst Thanks for the review!  Will commit as soon as CI completes.

**Comment by jdconrad** [comment]
@elasticmachine test this please

**Comment by jdconrad** [comment]
@elasticmachine test this please

**Comment by jdconrad** [comment]
@elasticmachine run gradle build tests 2

**Comment by jdconrad** [comment]
@elasticmachine run gradle build tests 1

**Comment by jdconrad** [comment]
@elasticmachine run gradle build tests 2

**Comment by jdconrad** [comment]
@elasticmachine test this please

**Comment by jdconrad** [comment]
@elasticmachine run gradle build tests 1

**Comment by jdconrad** [comment]
@elasticmachine run gradle build tests 2

**Comment by jdconrad** [comment]
@elasticmachine run gradle build tests 1

**Comment by jdconrad** [comment]
@elasticmachine run gradle build tests 2

**Comment by jdconrad** [comment]
@elasticmachine run gradle build tests 1

**Comment by jdconrad** [comment]
@elasticmachine run gradle build tests 1

**Pull request merged**
