### PR TITLE
Preserve half_float's precision in fields API

### LINKED ISSUE #70260: Fields API on half_float doesn't lose precision
Usually the fields fetch API functions similarly to loading field values from doc values. *Usually*. It differs in a few cases like `text`. But whenever it does differ from `doc_values` we want to make that choice intentionally. So it turns out that when you use the `fields` API on a `half_float` field we'll parse the value from the `_source` as a 32 bit float and return it with that precision. But `docvalue_fields` for `half_float` returns 16 bit of precision. Do we really want that or did we do it by accident?

### PR DESCRIPTION
**Pull request by nik9000**
This modifies the fields API to return values with half_float's
precision. This makes the fields API better reflect what we've indexed
which we'd like to to do in general. It does make the values that come
back "uglier" because things like `3.14` end up becoming `3.140625`. But
that is what is actually in the index so itsmore "real".

Closes #70260

### CODE REVIEW

**Comment by nik9000** [comment]
@elasticmachine update branch

**Review by jimczi — APPROVED** [review]
LGTM

**Review by astefan — APPROVED** [review]
LGTM

**Review by jpountz — APPROVED** [review]

**Comment by nik9000** [comment]
Thanks for the reviews folks!

**Pull request merged**
