### PR TITLE
Deprecate accepting malformed requests in stored script API

### LINKED ISSUE #27612: Stored scripts API accepting malformed requests
The stored scripts API today accepts malformed requests instead of throwing an exception.  For instance:

```
POST _scripts/foo
{
  "source": "return"
}

GET _scripts/foo
```

returns

```
{
  "_id": "foo",
  "found": true,
  "script": {
    "lang": "mustache",
    "source": """{"source":"return"}"""
  }
}
```

### PR DESCRIPTION
**Pull request by sohaibiftikhar**
The stored scripts API today accepts malformed requests instead of throwing an exception. 
This PR deprecates accepting malformed put stored script requests (requests not using the official script format).

Relates to #27612

### CODE REVIEW

**Comment by martijnvg** [comment]
@elasticmachine test this please

**Comment by martijnvg** [comment]
cc/ @elastic/es-core-infra

**Comment by sohaibiftikhar** [comment]
Rebased with master and fixed conflicts.

**Comment by nik9000** [comment]
Reading the issue related to this, I think we need to deprecate the "take the entire request as a template" behavior and the "template" field rather than fail the request.

**Comment by sohaibiftikhar** [comment]
Quoting @rjernst here
> The fix here is to deprecate/remove support for this leniency.

I believed I removed support for storing the entire request as a stored script.

> Additionally, "template" should also be deprecated/removed, but that is a separate issue.

Hence I left the "template" field intact. Or maybe I am getting something wrong? Is there a specific response for deprecating an API?

**Comment by rjernst** [comment]
@sohaibiftikhar Sorry if my comments were confusing. I meant what @nik9000 suggested. We need to *first* deprecate these uses, which should be a separate PR. We will back port that change to 6.x. Then, this PR can go in (removing the deprecation) in master.

The way deprecation works is with the DeprecationLogger, which you can have a static final instance of on whatever class needs it. Just search in the codebase for uses of it and you will see how it is often used like that.

**Comment by sohaibiftikhar** [comment]
@nik9000 @rjernst Could you have a look now?

**Review by rjernst — APPROVED** [review]
This looks ok to me, but I would like @martijnvg to look as well. Additionally, I think the deprecation messages would be better if they also suggest what to use instead.

**Comment by rjernst** [comment]
We try not to put links into log message as they can become stale and outdated. I recommend adding something like `specify templates in a "script" element instead`.

**Comment by imotov** [comment]
@elasticmachine add to whitelist

**Comment by nik9000** [comment]
@martijnvg, could you have another look at this one when you get a chance?

**Review by martijnvg — APPROVED** [review]
Apologies, I missed the updates in this PR.
This change looks good to me.

**Comment by martijnvg** [comment]
@sohaibiftikhar Thanks for your contribution!

**Pull request merged**
