### PR TITLE
[Test] Add SQL yaml tests to CCS common yaml test suite

### PR DESCRIPTION
**Pull request by ywangd**
This PR adds support for CCS common YAML test suite to run SQL yaml tests with both the existing and new remote cluster models.

Relates: #94265, #93720

PS: SQL does not send its own actions across clusters and relies only on the generic search, field_caps actions. Hence it is automatically supported without touching production code, i.e. changes are test only.

### CODE REVIEW

**Comment by ywangd** [comment]
Failure is unrelated and tracked at https://github.com/elastic/elasticsearch/issues/94357

**Comment by ywangd** [comment]
@elasticmachine run elasticsearch-ci/part-1-fips

**Comment by ywangd** [comment]
@elasticmachine update branch

**Comment by ywangd** [comment]
@elasticmachine update branch

**Review by slobodanadamovic — APPROVED** [review]
LGTM

**Comment by ywangd** [comment]
@elasticmachine update branch

**Pull request merged**
