### PR TITLE
Remove `gateway.initial_meta` and always rely on min master nodes

### PR DESCRIPTION
**Pull request by bleskes**
During initial cluster forming, when  a master is elected, it reaches out to all other masters nodes and ask the last cluster state they persisted. To make sure we select the right state, we must successfully read from a `min_master_nodes` nodes. The gateway currently have specific settings to override this behavior, but I don't think they are ever used. We can drop them and reach out to the discovery layer, the single source of truth for the min master nodes settings.

### CODE REVIEW

**Comment by bleskes** [comment]
@s1monw @beiske can you take a look?

**Comment by s1monw** [comment]
LGTM thanks this is so much simpler

**Comment by beiske** [comment]
LGTM

**Comment by s1monw** [comment]
@bleskes does this mean we can drop the pluggability of Gateway entirely and make it final etc?

**Comment by bleskes** [comment]
@s1monw I think I can fold into GatewayService. I'll give it a shot in another PR

**Pull request closed without merging**
