### PR TITLE
[Docs] rectified typo in BUILDING.md

### PR DESCRIPTION
**Pull request by Razdeep**
This PR rectifies some typos in the documentation.

Signed-off-by: Rajdeep Roy Chowdhury <rrajdeeproychowdhury@gmail.com>

### CODE REVIEW

**Comment by Razdeep** [comment]
I have signed the contributor agreement now.

**Review by kingherc — APPROVED** [review]
Thank you for the correction. As this is a small docs change, I do not believe it needs a PR .yml, so I removed that.

**Comment by kingherc** [comment]
@elasticmachine test this please

**Comment by kingherc** [comment]
@elasticsearchmachine run elasticsearch-ci/part-3

**Comment by kingherc** [comment]
@elasticmachine update branch

**Comment by kingherc** [comment]
@elasticmachine test this please

**Pull request merged**
