### PR TITLE
Typo in example of the filter_path option

### PR DESCRIPTION
**Pull request by scampi**

### CODE REVIEW

**Review by Navanit-git — COMMENTED** [review]
@jrodewig kindly check seems good to me

**Comment by Navanit-git** [comment]
@elasticsearchmachine  kindly add the label

**Review by jrodewig — APPROVED** [review]
LGTM. Thanks @scampi.

**Comment by jrodewig** [comment]
@elasticmachine test this please

**Comment by jrodewig** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|master|[](https://github.com/elastic/elasticsearch/pull/84661)|
|✅|7.17|[](https://github.com/elastic/elasticsearch/pull/84663)|


### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Comment by jrodewig** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.1|[](https://github.com/elastic/elasticsearch/pull/84664)|


### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
