### PR TITLE
fixed propagation of autoGeneratedId on document creation

### PR DESCRIPTION
**Pull request by seut**
canHaveDuplicates was used as autoGeneratedId and so no DocumentAlreadyExists exception was thrown (optimization introduced here: https://github.com/elastic/elasticsearch/commit/f45e6ae3f9643161424a4169d272bfa8588c202e) even when the id was not auto generated.

### CODE REVIEW

**Comment by bleskes** [comment]
Good catch. Note though that it wasn't an optimization but rather a protection against throw an DocumentAlreadyExists where we shouldn't. This entire construction is too brittle and was removed in master. 

It also seems we have a gap in our testing as this wasn't caught. We should fix that as well.. Looking the test that was added in the commit you mention, I think the easierst would be to replcae the code [here](https://github.com/elastic/elasticsearch/commit/f45e6ae3f9643161424a4169d272bfa8588c202e#diff-38d197a0e6b168e3ca10ca0553b238adR94), up and including the refersh command with 

```
        ArrayList<IndexRequestBuilder> requests = new ArrayList<>();
        for (int i = 0; i < numDocs; i++) {
            XContentBuilder doc = jsonBuilder().startObject().field("foo", "bar").endObject();
            requests.add(client().prepareIndex("index", "type").setSource(doc));
        }

        indexRandom(true, false, requests);

```

Can you modify the test and see it fails without your fix?

**Comment by seut** [comment]
@bleskes 
The test you mention is using autoGeneratedId's so this test will never hit the bug.
Also the bug was problematic for us in a different use-case, it was not happening during network failures like the fix tries to protect one from (retrying without bubbling the exception). In our case it was happening on the 2.1 release during concurrent inserts on a shard which was in post_recovery state so this code was run (retry due to illegal shard state): https://github.com/elastic/elasticsearch/blob/2.1/core/src/main/java/org/elasticsearch/action/support/replication/TransportReplicationAction.java#L585

Seems like this code was removed on 2.x so I'm not able to write a test to reproduce this issue.

In case of network failures, I don't really get why retrying without exception bubbling is only done for records with autoGeneratedId's. I think if something like this exists, it should kick in always.
But as you mentioned (and I already knew) this was removed at the master so we don't have to discuss about this anymore ;)

**Comment by bleskes** [comment]
Oh, I see. To add a test for retrying documents that already exist, you'd need to add some documents before the partition and add create operations to the indexing for those. Last you need to check the response for those documents and test that they indeed fail. Does that make sense?

**Comment by seut** [comment]
I've added a simple test which tests my fix.

btw. yeah I know how to create docs with custom id's ;)
the ExceptionRetryIT test is a bit flaky, the exception is not always thrown (e.g. if the unlucky node has no shard, the unlucky node is the client node and so no remote transport, etc.) and also the edge-case is not always hit (document must be created before exception is triggered). This flakiness is maybe ok if the test is expecting no failures, but if another test should expecting failures, the test scenario must not be flaky. I wasn't able to create a non-flaky scenario in an easy way, and also the test I added is more concrete for the test, no matter where the request flags are coming from.

**Comment by bleskes** [comment]
> document must be created before exception is triggered

That's why I suggested creating some docs in advance. Anyway, I'm good with the test and I'll pull it in. Thanks again..

**Comment by bleskes** [comment]
@seut the new file misses a license header which make our test fail. If you would like to add it (and rebase/squash on top on 2.x) that would be great. If not I'm happy to do it for you, but that will make git hub not see this PR as merged (but rather closed). If I don't hear otherwise by tomorrow I'll assume the latter and pull this in...

**Comment by seut** [comment]
> That's why I suggested creating some docs in advance.
Ah damn didn't thought about that, simple solutions are always the best ;)

**Comment by seut** [comment]
@bleskes added license header and squashed commits

**Comment by bleskes** [comment]
merged. Thanks @seut

**Pull request merged**
