### PR TITLE
check for null argument is already done in splitStringByCommaToArray

### PR DESCRIPTION
**Pull request by scampi**

### CODE REVIEW

**Comment by javanna** [comment]
test this please

**Comment by scampi** [comment]
Something went wrong when compiling:

```
20:17:42   [bwc] A problem occurred evaluating project ':benchmarks'.
20:17:42   [bwc] > Failed to apply plugin [id 'elasticsearch.build']
20:17:42   [bwc]    > the compiler java.home must be set to a JDK installation directory for Java 11 but is [/var/lib/jenkins/.java/java10] corresponding to [1.10]
```

**Comment by rjernst** [comment]
We switched our builds to use java 11 today. This looks like it was caught in the middle. I will trigger another build.

@elasticmachine test this please

**Comment by scampi** [comment]
@rjernst I think the same error happened again, isn't it ?

**Comment by javanna** [comment]
retest this please

**Comment by javanna** [comment]
retest this please

**Comment by javanna** [comment]
retest this please

**Comment by javanna** [comment]
retest this please

**Comment by javanna** [comment]
thanks @scampi !

**Pull request merged**
