### PR TITLE
Support ignore_above on keyword dimensions

### PR DESCRIPTION
**Pull request by felixbarny**
At the moment, it's not possible to set `ignore_above` on `keyword` dimension fields. This flag is used a lot in our integrations and in ECS. It helps to reduce the number of logs/metrics we need to reject.

This is also somewhat inconsistent as it's possible to set `ignore_malformed` on numeric dimension fields. Both options end up adding malformed values to `_ignored` and don't add doc_values and postings.

I'd like to propose adding support for `ignore_above` to be consistent with allowing `ignore_malformed` on numeric fields. The other option would be to take away the support for `ignore_malformed` but that seems to be a breaking change.

I've added a test that verifies that ignoring those dimensions is safe in the sense that it doesn't lead to document rejections due to duplicate detection if the only dimensions that differ are ignored.

### CODE REVIEW

**Review by kkrik-es — APPROVED** [review]
Fine by me, please wait for the other reviewers to double-check.

**Review by martijnvg — APPROVED** [review]
lgtm

**Comment by lkts** [comment]
Do you want to mention this in documentation?

**Comment by felixbarny** [comment]
Certainly, sorry for missing this. Here's a PR to adjust the docs: https://github.com/elastic/elasticsearch/pull/110385.

**Pull request merged**
