### PR TITLE
Increment google cloud apis to 1.52

### LINKED ISSUE #35229: Snapshot
**Elasticsearch version** (`bin/elasticsearch --version`): 6.4.1

**Plugins installed**: [analysis-kuromoji, analysis-icu, repository-gcs]

**JVM version** (`java -version`): 10.0.2

**OS version** (`uname -a` if on a Unix-like system): Linux 4.14.56+

**Description of the problem including expected versus actual behavior**:
Expected: Creating a snapshot for a large index (> 8TB) with high number of shards (>800) on a cluster that has dedicated master nodes completes successfully even if a master election occurs mid snapshot. 

Actual: Creating a snapshot for a large index (> 8TB) with high number of shards (>800) on a cluster that has dedicated master nodes fails on some shards with `IndexShardSnapshotFailedException[Failed to perform snapshot (index files)]; nested: FileAlreadyExistsException` if a master election occurs during the snapshot. 

I think that this issue may be known and handled in the case that an election occurs during the `finalizeSnapshot` step as seen here https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/repositories/blobstore/BlobStoreRepository.java#L550. This seems like a similar bug. Perhaps the new master attempts to also create a snapshot of the shard, overwriting the successful snapshot with the failed? 

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) index creation, mappings, settings, query etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. Create a cluster with dedicated master nodes
 2. Create a large index pointed at a GCS repo with specs higher than above (>8TB index size and >800 shards)
 3. Perform a snapshot (snapshots at this size will take between 30m and 2 hours)

**Provide logs (if relevant)**:
Snapshot status in `_cat/snapshots/<repo name>`
`2018-10-16t19-57-07 PARTIAL 1539719828  19:57:08   1539722642 20:44:02    46.8m      70              2716             4         2720`

Snippet of errors seen in logs from viewing snapshot status in API
```
{
          "index" : "<index_name>",
          "index_uuid" : "<index_name>",
          "shard_id" : 178,
          "reason" : "IndexShardSnapshotFailedException[Failed to perform snapshot (index files)]; nested: FileAlreadyExistsException[indices/Y0qyoa00TuaVx0iYLpVbXw/178/__1oc: Precondition Failed]; ",
          "node_id" : "lkwyayn5QVGh8okWvRIJpg",
          "status" : "INTERNAL_SERVER_ERROR"
        },
        {
          "index" : "<index_name>,
          "index_uuid" : "<index_name>",
          "shard_id" : 45,
          "reason" : "IndexShardSnapshotFailedException[com.google.cloud.storage.StorageException: Error writing request body to server]; nested: StorageException[Error writing request body to server]; nested: IOException[Error writing request body to server]; ",
          "node_id" : "xlJM3LeIS2SlitmN71R6fA",
          "status" : "INTERNAL_SERVER_ERROR"
        },
}
```

### PR DESCRIPTION
**Pull request by clandry94**
A bug was fixed in the google cloud java API that caused IOExceptions when uploading snapshots to GCS. Namely, this issue https://github.com/googleapis/google-cloud-java/issues/3410 and this PR fixing it 
https://github.com/googleapis/google-cloud-java/pull/3433. There have been reports of this bug appearing in Elasticsearch https://github.com/elastic/elasticsearch/issues/35229. Let's bump to the latest release of those google cloud java APIs. 

Closes https://github.com/elastic/elasticsearch/issues/35229 

cc @ywelsch

### CODE REVIEW

**Comment by ywelsch** [comment]
@elasticmachine test this please

**Comment by atorok** [comment]
@clandry94 you have to run `updateSHAs` and check the results in when updating dependencies.

**Comment by clandry94** [comment]
@elasticmachine test this please

**Comment by ywelsch** [comment]
@elasticmachine retest this please

**Comment by imrimt** [comment]
what workaround do you guys recommend around resolving the `IOException` issue since 6.7 is not out yet and we won't be able to upgrade to it anytime soon. This issue is particularly more likely when we are taking a snapshot at scale (~80gb of data) -- I have tried running it 4 times and they all failed.

We are currently on Elasticsearch 6.4.2. Would replacing the client jars directly in the plugins resolve this issue (i.e would ES 6.4.2 work with a newer GCS java client?)

Here's an example of the stacktrace that we are seeing:
```
[2019-02-04T22:37:33,028][WARN ][o.e.s.SnapshotShardsService] [localhost] [[tamr_datasets][13]][test_snapshot1:snapshot_1/ZMzfA4DUTB6y_NolLaL2_Q] failed to snapshot shard
org.elasticsearch.index.snapshots.IndexShardSnapshotFailedException: com.google.cloud.storage.StorageException: Error writing request body to server
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.snapshotShard(BlobStoreRepository.java:858) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.snapshots.SnapshotShardsService.snapshot(SnapshotShardsService.java:410) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.snapshots.SnapshotShardsService.access$200(SnapshotShardsService.java:97) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.snapshots.SnapshotShardsService$1.doRun(SnapshotShardsService.java:354) [elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:723) [elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.4.2.jar:6.4.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: com.google.cloud.storage.StorageException: Error writing request body to server
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:220) ~[?:?]
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.write(HttpStorageRpc.java:703) ~[?:?]
	at com.google.cloud.storage.BlobWriteChannel$1.run(BlobWriteChannel.java:51) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_111]
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:89) ~[?:?]
	at com.google.cloud.RetryHelper.run(RetryHelper.java:74) ~[?:?]
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:51) ~[?:?]
	at com.google.cloud.storage.BlobWriteChannel.flushBuffer(BlobWriteChannel.java:47) ~[?:?]
	at com.google.cloud.BaseWriteChannel.flush(BaseWriteChannel.java:122) ~[?:?]
	at com.google.cloud.BaseWriteChannel.write(BaseWriteChannel.java:149) ~[?:?]
	at org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobStore$2.lambda$write$0(GoogleCloudStorageBlobStore.java:238) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_111]
	at org.elasticsearch.repositories.gcs.SocketAccess.doPrivilegedIOException(SocketAccess.java:44) ~[?:?]
	at org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobStore$2.write(GoogleCloudStorageBlobStore.java:238) ~[?:?]
	at java.nio.channels.Channels.writeFullyImpl(Channels.java:78) ~[?:1.8.0_111]
	at java.nio.channels.Channels.writeFully(Channels.java:101) ~[?:1.8.0_111]
	at java.nio.channels.Channels.access$000(Channels.java:61) ~[?:1.8.0_111]
	at java.nio.channels.Channels$1.write(Channels.java:174) ~[?:1.8.0_111]
	at org.elasticsearch.core.internal.io.Streams.copy(Streams.java:55) ~[elasticsearch-core-6.4.2.jar:6.4.2]
	at org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobStore.writeBlobResumable(GoogleCloudStorageBlobStore.java:224) ~[?:?]
	at org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobStore.writeBlob(GoogleCloudStorageBlobStore.java:203) ~[?:?]
	at org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobContainer.writeBlob(GoogleCloudStorageBlobContainer.java:68) ~[?:?]
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository$SnapshotContext.snapshotFile(BlobStoreRepository.java:1331) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository$SnapshotContext.snapshot(BlobStoreRepository.java:1266) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.snapshotShard(BlobStoreRepository.java:852) ~[elasticsearch-6.4.2.jar:6.4.2]
	... 8 more
Caused by: java.io.IOException: Error writing request body to server
	at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.checkError(HttpURLConnection.java:3518) ~[?:?]
	at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.write(HttpURLConnection.java:3501) ~[?:?]
	at com.google.api.client.util.ByteStreams.copy(ByteStreams.java:55) ~[?:?]
	at com.google.api.client.util.IOUtils.copy(IOUtils.java:94) ~[?:?]
	at com.google.api.client.http.AbstractInputStreamContent.writeTo(AbstractInputStreamContent.java:72) ~[?:?]
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:80) ~[?:?]
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:981) ~[?:?]
	at com.google.cloud.storage.spi.v1.HttpStorageRpc.write(HttpStorageRpc.java:684) ~[?:?]
	at com.google.cloud.storage.BlobWriteChannel$1.run(BlobWriteChannel.java:51) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_111]
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:89) ~[?:?]
	at com.google.cloud.RetryHelper.run(RetryHelper.java:74) ~[?:?]
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:51) ~[?:?]
	at com.google.cloud.storage.BlobWriteChannel.flushBuffer(BlobWriteChannel.java:47) ~[?:?]
	at com.google.cloud.BaseWriteChannel.flush(BaseWriteChannel.java:122) ~[?:?]
	at com.google.cloud.BaseWriteChannel.write(BaseWriteChannel.java:149) ~[?:?]
	at org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobStore$2.lambda$write$0(GoogleCloudStorageBlobStore.java:238) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_111]
	at org.elasticsearch.repositories.gcs.SocketAccess.doPrivilegedIOException(SocketAccess.java:44) ~[?:?]
	at org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobStore$2.write(GoogleCloudStorageBlobStore.java:238) ~[?:?]
	at java.nio.channels.Channels.writeFullyImpl(Channels.java:78) ~[?:1.8.0_111]
	at java.nio.channels.Channels.writeFully(Channels.java:101) ~[?:1.8.0_111]
	at java.nio.channels.Channels.access$000(Channels.java:61) ~[?:1.8.0_111]
	at java.nio.channels.Channels$1.write(Channels.java:174) ~[?:1.8.0_111]
	at org.elasticsearch.core.internal.io.Streams.copy(Streams.java:55) ~[elasticsearch-core-6.4.2.jar:6.4.2]
	at org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobStore.writeBlobResumable(GoogleCloudStorageBlobStore.java:224) ~[?:?]
	at org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobStore.writeBlob(GoogleCloudStorageBlobStore.java:203) ~[?:?]
	at org.elasticsearch.repositories.gcs.GoogleCloudStorageBlobContainer.writeBlob(GoogleCloudStorageBlobContainer.java:68) ~[?:?]
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository$SnapshotContext.snapshotFile(BlobStoreRepository.java:1331) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository$SnapshotContext.snapshot(BlobStoreRepository.java:1266) ~[elasticsearch-6.4.2.jar:6.4.2]
	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.snapshotShard(BlobStoreRepository.java:852) ~[elasticsearch-6.4.2.jar:6.4.2]
	... 8 more
[2019-02-04T22:47:03,848][INFO ][o.e.s.SnapshotsService   ] [localhost] snapshot [test_snapshot1:snapshot_1/ZMzfA4DUTB6y_NolLaL2_Q] completed with state [PARTIAL]
```

**Pull request closed without merging**
