### PR TITLE
Make EsPolicy.implies a little Faster

### PR DESCRIPTION
**Pull request by original-brownbear**
Just some random speedups from investigating many-shard's benchmarks.

Extract cold paths + build a more efficient permissions collection for the hot
data path permissions that don't need the generic collection because it's all
file permissions only.

### CODE REVIEW

**Comment by original-brownbear** [comment]
Jenkins run 
elasticsearch-ci/part-2

**Review by rjernst — APPROVED** [review]
LGTM but I'd like Chris to double check this

**Review by ChrisHegarty — APPROVED** [review]
LGTM.

I see that the data path file permission is checked first, which is good. It is not clear to me how much the other refactoring helps with performance or how performance has been analysed, but the change looks fine as it is.

**Comment by original-brownbear** [comment]
Thanks Ryan + Chris!

**Pull request merged**
