### PR TITLE
Streamline primary recovery code

### PR DESCRIPTION
**Pull request by ywelsch**
Primary recoveries all follow the same pattern: prepare some files on disk, then open the engine and recover. When restoring from snapshot, the same pattern is used. In contrast to store recovery, it's not sharing the same code path though. This PR (imo) simplifies the snapshot restore code by using the same recovery mechanics. I also fixes the`bootstrapNewHistory` method to not override the local checkpoint on the indexcommit. When using the force allocate stale primary command, we would previously replace the local checkpoint by the max sequence number. I'm not aware of any direct bad consequences of this but this sounds dangerous for the future (where perhaps when we change the store recovery code to skip translog entries that supposedly are already in the Lucene commit, we end up missing some documents).

### CODE REVIEW

**Review by dnhatn — APPROVED** [review]
LGTM.

**Comment by dnhatn** [comment]
> I also fixes the bootstrapNewHistory method to not override the local checkpoint on the index commit.

Thanks for fixing this :).

**Comment by tlrx** [comment]
@ywelsch would you like to revive this or should we close?

**Comment by ywelsch** [comment]
Some of the changes here have made it into our code base in subsequent PRs. The remaining pieces are not that urgent, so I'm closing this.

**Pull request closed without merging**
