### PR TITLE
Fix ShardFollowNodeTask.Status equals and hash code

### PR DESCRIPTION
**Pull request by jasontedor**
These were broken when fetch exceptions were introduced to the status object but equals and hash code were not updated then. This commit addresses that.

### CODE REVIEW

**Review by dnhatn — APPROVED** [review]
LGTM.

**Review by martijnvg — APPROVED** [review]
LGTM

**Comment by jasontedor** [comment]
@dnhatn @martijnvg This ended up being a little sneakier because `ElasticsearchException` does not implement `equals` and `hashCode`. This led to a test failure in `ShardFollowNodeTaskStatusTests`. I pushed an iteration. Would you take another look?

**Review by martijnvg — APPROVED** [review]
That is sneaky indeed. LGTM

**Review by dnhatn — APPROVED** [review]
LGTM.

**Pull request merged**
