### PR TITLE
Removed setting index.optimize_auto_generated_id from related files.

### PR DESCRIPTION
**Pull request by gokberksahin**
Closes https://github.com/elastic/elasticsearch/issues/27583

### CODE REVIEW

**Comment by bleskes** [comment]
Thx @gokberksahin . Can you please sign the CLA at https://www.elastic.co/contributor-agreement ?

**Comment by bleskes** [comment]
test this please

**Comment by jasontedor** [comment]
There is an open PR for this already: #27600

**Comment by bleskes** [comment]
@jasontedor thx for the ping. 

@gokberksahin since @liketic opened his first, I'm going to close this as a duplicate.

@liketic if you don't intend (or can't) push your PR through, please let us know so we can take this one instead.

**Pull request closed without merging**
