### PR TITLE
Adjust port ranges for tests and test fixtures

### PR DESCRIPTION
**Pull request by breskeby**
- Do not use general ephermal port range
- Cleanup available port finder logic

### CODE REVIEW

**Review by mark-vieira — APPROVED** [review]
LGTM

**Comment by breskeby** [comment]
@elasticmachine update branch

**Comment by mark-vieira** [comment]
@breskeby this needs to get ported back to `7.11` as well since that branch was cut shortly after this change.

**Comment by breskeby** [comment]
back ported this and https://github.com/elastic/elasticsearch/pull/66440 back to 7.11

**Pull request merged**
