### PR TITLE
Fix potential listener leak in TransportBulkAction

### PR DESCRIPTION
**Pull request by Tim-Brooks**
Currently we manually call `doInternalExecute` when returning from the
ingest service if we are still on the write threadpool. Unforunately, if
this throws an exception, it will be lost and the listener not
completed. This commit resolves this by using an action runnable same as
if we were dispatching back to the WRITE thread.

### CODE REVIEW

**Review by henningandersen — APPROVED** [review]
LGTM, nice catch.

I wonder if we could add a test that provokes this?

Also, should this not also go to 8.0 and 7.latest?

**Review by idegtiarenko — APPROVED** [review]

**Review by masseyke — APPROVED** [review]
Agree that a test would be good, but LGTM.

**Comment by tbrooks8** [comment]
@elasticmachine run elasticsearch-ci/packaging-tests-unix-sample

**Comment by tbrooks8** [comment]
@elasticmachine run elasticsearch-ci/part-1

**Comment by tbrooks8** [comment]
@elasticmachine run elasticsearch-ci/part-2

**Pull request merged**
