### PR TITLE
Add `beats_stats.metrics.apm-server.sampling.tail` to stack monitoring templates

### LINKED ISSUE #6581: Monitoring data is not indexed in ES
**APM Server version** (`apm-server version`): v7.16.0-SNAPSHOT

**Description of the problem including expected versus actual behavior**:

Data captured in `.monitoring-beats*` indices under `beats_stats.metrics.apm-server.sampling.*` is not indexed and can not be queried in the Console or charts.  

**Steps to reproduce**:

 1. enable tail-based sampling in the apm-server
e.g.:
```
apm-server:
  data_streams:
    enabled: true
  sampling:
    keep_unsampled: false
    tail:
      enabled: true
      ttl: 30s
      interval: 1s
      policies: 
        - sample_rate: 0.1 

```
 2. enable stack monitoring
 3. try to query beats_stats.metrics.apm-server.sampling.*
e.g.: 
```
GET .monitoring-beats-7-2021.11.11/_search
{
  "query": {
    "bool": {
      "filter": [
        { 
          "exists": {
            "field": "beats_stats.metrics.apm-server.sampling"
          }
        }
      ]
    }
  }
}
```

**Provide logs (if relevant)**:

### PR DESCRIPTION
**Pull request by axw**
Add mappings for `beats_stats.metrics.apm-server.sampling.tail` to the monitoring templates.

Closes https://github.com/elastic/apm-server/issues/6581

### CODE REVIEW

**Comment by axw** [comment]
@elasticmachine update branch

**Comment by jbaiera** [comment]
@axw are these meant to be fields added to the legacy monitoring templates or are these meant to be added to the templates used by stack monitoring?

**Comment by axw** [comment]
@jbaiera both I think?

My understanding is that legacy templates are used when libbeat is configured with internal (legacy) monitoring, and the Metricbeat templates are used for the current/recommended Metricbeat approach.

**Review by klacabane — APPROVED** [review]
Apm server [supports internal and metricbeat](https://www.elastic.co/guide/en/apm/server/current/monitoring.html) collection methods so both templates have to be updated.
LGTM

**Comment by axw** [comment]
Thanks for taking a look @klacabane!

@jbaiera if it looks good to you, would you kindly merge so it can make it for 8.1?

**Review by jbaiera — APPROVED** [review]
Sorry for the delay here - we didn't expect there to be any changes landing in the legacy monitoring formats at all going forward as they are expected to be removed. That said, I don't see any major issues at the moment with bumping the last updated version since it's just used for updating the mappings, and nothing has broken between the versions.

**Comment by jbaiera** [comment]
It looks like there's still some issues with CI?

@elasticmachine update branch

**Comment by axw** [comment]
@elasticmachine run elasticsearch-ci/part-1

**Comment by axw** [comment]
@jakelandis how would you feel about backporting this to 8.1? Seems very low risk to me at this early stage. The feature that these metrics are related to is going GA in 8.1, so it would be very helpful for us to be able to query them.

**Pull request merged**
