### PR TITLE
Update core-types.asciidoc

### PR DESCRIPTION
**Pull request by mcku**
Fix a trivial typo hes --> has

### CODE REVIEW

**Comment by nik9000** [comment]
Nice! Thanks for that.

@mcku our CLA checker is choking on this because you used a different email to sign the commit than you signed the CLA. Which I'm told is fine if you put the email that you used on the commit in your github profile. Can you try that and leave a comment to trigger the check again?

Sorry for the trouble.

**Comment by mcku** [comment]
Hi Nik! 

Could you check that again? I liked the CLA and stuff. You guys are doing serious things.. hope to send more useful commits in the future. 

Take care..

**Comment by nik9000** [comment]
Cool! Yes, the CLA check passed. Thanks so much. I'll try to merge this this afternoon.

**Comment by nik9000** [comment]
Thakns @mcku! I've merged it.

**Comment by nik9000** [comment]
Looks like it doesn't apply to 2.x or master because those docs have been rewritten. So no cherry-picking this morning.

**Pull request merged**
