### PR TITLE
Dissect parsing: An `%` occurring in the delimiter causes incorrect capture of the `${key}` that follows

### PR DESCRIPTION
**Pull request by mjmbischoff**
**Problem description**
A literal % is not correctly caught by the dissect processor in Elasticsearch. See sample below.

```
PUT /_ingest/pipeline/test
{
  "processors": [
    {
      "dissect": {
        "field": "message",
        "pattern": "%foo %{bar}"
      }
    }
  ]
}

POST /_ingest/pipeline/test/_simulate
{
  "docs": [ {"_source": {"message": "%foo test"}} ]
}
```

Expected output would be:

```
        {
          "bar" : "test",
          "message" : "%foo test"
        }
```

Actual output is:

```
        {
          "bar" : "%foo test",
          "message" : "%foo test"
        }
```
**Implemented solution**
Changed the regex that captures the tokens denoted by `%{}` and the surrounding delimiters to lookahead and match on `%{` vs simply the first occurrence of `%`

**Workarounds (if any)**:
At the moment, use of additional processors to replace the % in the log message with a supported character.

### CODE REVIEW

**Comment by jakelandis** [comment]
@mjmbischoff Can you update this PR with the contents of the description, or normal GH issue and reference that ? We try to avoid linking to private repo's.

**Comment by martijnvg** [comment]
The change looks good to me. @mjmbischoff would you like to update the issue title and description?

**Comment by martijnvg** [comment]
@elasticmachine update branch

**Comment by mjmbischoff** [comment]
jenkins retest this please

**Comment by mjmbischoff** [comment]
retest this please

**Pull request merged**
