### PR TITLE
[DOCS] Document 8.0 BWC support for CCS

### LINKED ISSUE #80782: [DOCS] Update BWC support for cross-cluster search
As of 8.0, the compatibility window for cross-cluster search (CCS) to an earlier release will be one minor release. CCS to a later release will be supported to any minor in the current and the next major release.

To document this change, we need to update the [supported configurations][0] section of the cross-cluster search docs. We also need to add a related item to the [8.0 breaking changes][1].

[0]: https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-cross-cluster-search.html#ccs-supported-configurations
[1]: https://www.elastic.co/guide/en/elasticsearch/reference/master/migrating-8.0.html#breaking-changes-8.0

CC @giladgal

### PR DESCRIPTION
**Pull request by jrodewig**
As of 8.0, the compatibility window for cross-cluster search (CCS) to an earlier release will be one minor release. This updates the CCS docs and adds a related 8.0 breaking change.

Closes https://github.com/elastic/elasticsearch/issues/80782

### Preview
* Supported CCS configurations: https://elasticsearch_80809.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/modules-cross-cluster-search.html#ccs-supported-configurations
* 8.0 breaking change: https://elasticsearch_80809.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/migrating-8.0.html#breaking_80_rest_api_changes

### CODE REVIEW

**Comment by jrodewig** [comment]
@giladgal @jimczi Apologies for the noise and additional revisions. This is ready for review at your convenience.

**Review by giladgal — DISMISSED** [review]
Looks good to me. My only comment is that we may have a 7.x release after 7.16, and then we will need to revise the example.

**Comment by jrodewig** [comment]
As someone pointed out, this doesn't align with our current [remote cluster compatibility table](http://localhost:8000/guide/remote-clusters.html). I'm going to take this back into draft until we get that sorted.

**Comment by jrodewig** [comment]
@elasticmachien test this please

**Comment by jrodewig** [comment]
@giladgal I updated these docs to align with the supported configurations outlined in our [remote clusters docs](https://www.elastic.co/guide/en/elasticsearch/reference/master/remote-clusters.html#sniff-mode). It updates the table from those docs and reuses it in the CCS section.

I've opened https://github.com/elastic/elasticsearch/pull/81327 to add a similar clarification to our 7.16 docs.

**Review by giladgal — APPROVED** [review]
lgtm

**Comment by jrodewig** [comment]
Thanks for the reviews @giladgal!

**Comment by jrodewig** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------:|
|✅|8.0|[](https://github.com/elastic/elasticsearch/pull/82429)|

**Pull request merged**
