### PR TITLE
Remove fedora 26, add 28

### LINKED ISSUE #30579: Drop Fedora 26 from and add Fedora 28 to packaging tests
Fedora 26 is going end-of-life, and Fedora 28 is the new kid in town. This issue is a placeholder issue to drop Fedora 26 from the packaging tests, and add Fedora 28 to the packaging tests.

### PR DESCRIPTION
**Pull request by alpar-t**
Closes #30579

Tested with local images, will have to wait for vagrantcloud before merge. 
I get the same failure as with fedora 27 locally, assuming that's  not related to the image.
```
ok 236 [UPGRADE] check elasticsearch version is version under test
not ok 237 [UPGRADE] verify that the documents are there after restart
# (in test file /project/build/packaging/bats/tests/80_upgrade.bats, line 111)
#   `curl -s localhost:9200/library/book/1?pretty | grep Elasticsearch' failed
ok 238 [UPGRADE] stop version under test
ok 239 [REINSTALL] install
ok 240 [REINSTALL] purge elasticsearch
ok 241 [REINSTALL] chown directories
ok 242 [REINSTALL] reinstall elasticsearch
ok 243 [REINSTALL] check ownership
REPRODUCE WITH: ./gradlew :qa:vagrant:vagrantFedora27#batsPackagingTest -Dtests.seed=858B8891E728527A
```
I logged #30682 for tracking the test failure.

### CODE REVIEW

**Review by jasontedor — CHANGES_REQUESTED** [review]
The changes to enable the tests look good but I think that also a change is needed in TESTING.asciidoc.

**Comment by jasontedor** [comment]
run all packaging tests

**Comment by atorok** [comment]
@jasontedor images are up, tests are passing and docs were updated, please take another look.

**Review by jasontedor — APPROVED** [review]
LGTM.

**Pull request merged**
