### PR TITLE
Use `Strings.format` instead of `String.format(Locale.ROOT, ...)` in tests

### PR DESCRIPTION
**Pull request by arteam**
~#90624 introduced a `formatted` utility method in ESTestCase as a safe version of the `String.formatted` method which is forbidden by the forbidden API checker.~

~We can replace `String.format(Locale.ROOT)` calls with it as well as `String.formatted` calls that were replaced in #90624.~

Use local-independent `Strings.format` method instead of `String.format(Locale.ROOT, ...)`. Also inline `ESTestCase.forbidden` calls with `Strings.format` for the consistency sake.

### CODE REVIEW

**Comment by thecoop** [comment]
There's also `Strings.format` method, which does the same thing.

**Comment by pgomulka** [comment]
> There's also Strings.format method, which does the same thing.

I would rather use the libs/core Strings.format - the one that @thecoop mentions. 
I wonder if ESTestCase#formatted will not will cause more confusion on what method to use. Perhaps we should refactor  ESTestCase#formatted to use libs/core Strings.format and then inline it?

**Review by breskeby — APPROVED** [review]

**Comment by arteam** [comment]
Hey @pgomulka! I've replaced `String.format(Local.ROOT` calls in tests to `Strings.format` and also inlined the `formatted` method in `ESTestCase` to direct `Strings.format` calls

**Review by pgomulka — APPROVED** [review]
LGTM, thank you @arteam

**Comment by arteam** [comment]
Thank you both!

**Pull request merged**
