### PR TITLE
Refactors ClientHelper to combine header logic

### PR DESCRIPTION
**Pull request by colings86**
This change removes all the `*ClientHelper` classes which were
repeating logic between plugins and instead adds
`ClientHelper.executeWithHeaders()` and
`ClientHelper.executeWithHeadersAsync()` methods to centralise the
logic for executing requests with stored security headers.

I have request reviews from everyone I think this refractor affects and also @jaymode since this is really a security change in essence.

### CODE REVIEW

**Review by droberts195 — APPROVED** [review]
LGTM

**Review by jaymode — APPROVED** [review]
LGTM

**Review by polyfractal — APPROVED** [review]

**Comment by polyfractal** [comment]
LGTMToo :)

**Review by spinscale — APPROVED** [review]
LGTM.

You could remove `Watcher.HEADER_FILTERS` and replace with the ClientHelper ones, or I can do that as a follow up.

**Comment by colings86** [comment]
@elasticmachine retest this please

**Comment by colings86** [comment]
Yes, sorry it got forgotten but thanks very much for catching this @jpountz

**Pull request merged**
