### PR TITLE
Move redact ingest processor into x-pack

### PR DESCRIPTION
**Pull request by joegallo**
Follow up to https://github.com/elastic/elasticsearch/pull/92951

The [`redact` processor](https://www.elastic.co/guide/en/elasticsearch/reference/8.7/redact-processor.html) was originally introduced as a part of the `ingest-common` module, this PR promotes it to its own new `x-pack-redact` plugin.

### CODE REVIEW

**Review by dakrone — APPROVED** [review]
LGTM assuming CI is happy

**Review by davidkyle — APPROVED** [review]
LTGM thanks @joegallo

**Comment by joegallo** [comment]
@elasticmachine run elasticsearch-ci/part-1

**Comment by sophiec20** [comment]
Thank you for this change...

The redact processor is now [Elastic License 2.0](https://www.elastic.co/licensing/elastic-license) which is a pre-req for enabling [Platinum](https://www.elastic.co/subscriptions) license checks.

**Pull request merged**
