### PR TITLE
upgrade randomizedrunner to 2.7.0

### PR DESCRIPTION
**Pull request by vladimirdolzhenko**
Targets https://github.com/randomizedtesting/randomizedtesting/issues/268 + many other [bug fixes](https://github.com/randomizedtesting/randomizedtesting/blob/master/CHANGES.txt)

### CODE REVIEW

**Review by s1monw — APPROVED** [review]
LGTM

**Comment by jasontedor** [comment]
@vladimirdolzhenko Can you add version labels, and maybe the `>upgrade` label?

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by vladimirdolzhenko** [comment]
thanks @s1monw, @jasontedor

**Pull request merged**
