### PR TITLE
Support metrics time-series bucket

### PR DESCRIPTION
**Pull request by dnhatn**
This PR introduces support for time-series buckets for metrics in ES|QL. Since the keyword `bucket()` is already in use and cannot be used here, we've opted for `tbucket` to represent time-series buckets as it also filters out data. Currently, the `ts()` function only supports the bucket internal; support for the filtered internal (from and to) will be added later.

In this change, `METRICS ... BY TBUCKET(interval)` is translated to `... | STATS ... by BUCKET(@timestamp, interval)`

Some examples:

```
METRICS k8s max(bytes_in) BY bucket=tbucket(5m) | SORT bucket DESC
METRICS k8s sum(bytes_in), sum(bytes_out) BY host, bucket=tbucket(5m) | SORT bucket DESC, host
```

### CODE REVIEW

**Comment by kkrik-es** [comment]
Is this the bucket function that exists: https://www.elastic.co/guide/en/elasticsearch/reference/master/esql-functions-operators.html#esql-bucket ?

It doesn't look too bad imho, would it be possible to restrict it in our case and apply to timestamp, if no field is specified? e.g

```
METRICS k8s max_bytes=max(to_long(network.total_bytes_in)) BY cluster, BUCKET("5m", "1d");
```

If that is too tricky, maybe use something like `TBUCKET` or `INTERVAL`:

```
METRICS k8s max_bytes=max(to_long(network.total_bytes_in)) BY cluster, INTERVAL("5m", "-2d", "-1d");

METRICS k8s max_bytes=max(to_long(network.total_bytes_in)) BY cluster, INTERVAL("5m", "2020-01-01T00:00:00Z", "2020-01-02T00:00:00Z", "5m");

METRICS k8s max_bytes=max(to_long(network.total_bytes_in)) BY cluster, INTERVAL( "5m", "1d");

METRICS k8s max_bytes=max(to_long(network.total_bytes_in)) BY cluster, INTERVAL("5m");
```

TS refers to time series, which is somewhat confusing as it doesn't help pick a time series, but rather filter and aggregate on the selected one(s).

**Comment by dnhatn** [comment]
Thanks @kkrik-es! The subtle part is that the function `BUCKET()` doesn't filter out data with `FROM`, but it will filter data out with `METRICS`.

**Comment by dnhatn** [comment]
TBUCKET and INTERVAL also work for me.

**Comment by dnhatn** [comment]
@kkrik-es I pushed https://github.com/elastic/elasticsearch/pull/109326/commits/b895abcd59eef8772b6403159c8539f9784b3d68 to use `tbucket`.

**Comment by kkrik-es** [comment]
@costin any thoughts on this one? We're thinking of TBUCKET or something similar for the bucket spec (with range) on metrics.

**Pull request closed without merging**
