### PR TITLE
Only include settings file for working ES versions

### PR DESCRIPTION
**Pull request by n1v0lg**
To avoid failed cluster starts due to https://github.com/elastic/elasticsearch/issues/91939 in upgrade tests, we should only include `settings.json` file if we are above the buggy version. I missed "forward-porting" this to main. 

A follow-up PR will port the suite over to the new parametrized upgrade test class and remove the settings file from the generic upgrade test flow altogether.

### CODE REVIEW

**Review by jfreden — APPROVED** [review]
LGTM! Thanks for addressing this!

**Comment by n1v0lg** [comment]
@elasticmachine update branch

**Comment by n1v0lg** [comment]
@elasticmachine update branch

**Comment by n1v0lg** [comment]
@elasticmachine update branch

**Comment by n1v0lg** [comment]
@elasticmachine update branch

**Comment by n1v0lg** [comment]
@elasticmachine update branch

**Comment by n1v0lg** [comment]
@elasticmachine update branch

**Comment by n1v0lg** [comment]
@elasticmachine update branch

**Pull request merged**
