### PR TITLE
DateMath: Use time zone when rounding. 

### LINKED ISSUE #9814: Range filters, date math and time_zone
Hi guys. 

I've stumbled upon an issue. When specifying the ```time_zone``` parameters in a range filter where ```gte``` and ```lt``` are set using datemath, the time zone is not taken into account when rounding!

The following is part of a filters aggregation, and I expect to be given the week 4 weeks ago, starting on a
sunday at 23:00 UTC time, and ending on sunday 23:00 UTC time with a full week in between. 
```
{
  "filters": {
    "4w": {
      "range": {
        "timestamp": {
          "lt": "now-4w+1w/w",
          "gte": "now-4w/w",
          "time_zone": "+01:00"
        }
      }
    }
  }
}
```
But no, after inspecting the docs that are returned, there are no documents returned between the first sunday 23:00 and monday 00:00 UTC. There are however documents returned between sunday 23:00 and monday 00:00 UTC at the end of the interval.

Is this a bug? Should not timezones be included when doing rounding in date math?

### PR DESCRIPTION
**Pull request by cbuescher**
Currently rounding in DateMathParser is always done in UTC, even 
when another time zone is specified. This is fixed by passing the time zone 
down to the rounding logic when it is specified.

Closes  #9814

### CODE REVIEW

**Comment by rjernst** [comment]
LGTM

**Comment by cbuescher** [comment]
On 1.x with 8391b51.

@rjernst I ran into a bit of a mess trying to backport the tests in DateMathParserTests for this PR to the 1.4 branch. The diff between the two branches is quiet big for that test class, so adding just the new lines for this fix is difficult. I tried backporting the the whole test class form 1.x to 1.4, but in that case I had to change  a lot of the actual tests to the current behaviour of DateMath on 1.4. 
Any suggestions how to procede here? Keep the orginal DateMathParserTests from 1.4 and only try to add the new tests there or try to update the whole thing according to the current state of tests in 1.x?

**Comment by rjernst** [comment]
If the backport is too complicated, we should not do it.  I don't think this is critical enough that it must be in a bugfix release.

**Comment by cbuescher** [comment]
@rjernst The backport is not difficult, would be nice to have on 1.4. Just the test class changed a lot from 1.4 to 1.x, so the tests will have to be adapted and be slightly different from this PR. Would you mind having another look if I push to my repo before merging?

**Comment by rjernst** [comment]
@cbuescher Sure, let me know where to look.

**Comment by cbuescher** [comment]
I pushed the changes agains 1.4 branch to https://github.com/cbuescher/elasticsearch/commit/997b8ce3c488fc3ed23789a0874c7d7cbf32f8c7. Basically it's the same fix as in 1.x, I only backportet the rounding tests and had to adapt them to the "old" rounding logic on 1.4. (I think you changed the edge inclusions on the 1.x branch)

**Comment by rjernst** [comment]
@cbuescher +1 to the backport

**Comment by cbuescher** [comment]
Great, pushed to 1.4 branch with dff19cb

**Pull request closed without merging**
