### PR TITLE
Improve the out-of-the-box experience

### LINKED ISSUE #21783: Jre x86 on Win x64
Good evening, ❄️ ElasticSearch dev team ❄️ !

I have a problem:
Why I can't run elasticsearch.bat on Windows 10 x64 with jre1.8.0_111 x86? After some research I found out that bin folder doens't have server folder and elasticsearch.in.bat requires it. Could you handle this situation?

Thanks in advance

### PR DESCRIPTION
**Pull request by jasontedor**
Elasticsearch can be run in a few different ways:
 - from the command line on Linux and Windows
 - as a service on Linux and Windows

on both 32-bit client and 64-bit server VMs. We strive for a great
out-of-the-box experience any of these combinations but today it is
lacking on 32-bit client JVMs and on the Windows service. There are two
deficiencies that arise:
 - on any 32-bit client JVM we fail to start out of the box because we
   force the server JVM in jvm.options
 - when installing the Windows service, the thread stack size must be
   specified in jvm.options

This commit attempts to address these deficiencies.

We should continue to force the server JVM because there are systems
where the server JVM is not active by default (e.g., the 32-bit JDK on
Windows). This does mean that if a user tries to run with a client JVM
they will see a failure message at startup but this is the best that we
can do if we want to continue to force the server JVM. Thus, this commit
at least documents this situation.

To improve the situation with installing the Windows service, this
commit adds a default setting for the thread stack size. This default is
chosen based on the default thread stack size across all 64-bit server
JVMs. This means that if a user tries to run with a 32-bit JVM they
could otherwise see significantly higher memory usage (this situation is
complicated, it's really only on Windows where the extra memory usage is
egregious, but cutting into the 32-bit address space on any system is
bad). So this commit makes it so that the out-of-the-box experience is
improved for the Windows service on 64-bit server JVMs and we document
the need to adjust this setting on 32-bit JVMs.

Again, we are focusing on the out-of-the-box experience here and this
means optimizing for the best experience on any 64-bit server JVM as
this covers the vast majority of the user base. The users that are on
32-bit JVMs will suffer a little bit but at least now any user on any
64-bit server JVM can start Elasticsearch out of the box.

Finally, we fix some references to the jvm.options documentation.

Relates #18317, Closes #21783

### CODE REVIEW

**Comment by gmarz** [comment]
LGTM

**Comment by s1monw** [comment]
LGTM

**Comment by jasontedor** [comment]
Thanks @gmarz and @s1monw.

**Comment by anhlqn** [comment]
> when installing the Windows service, the thread stack size must be
specified in jvm.options
I believe this is no longer necessary on ES 5.2.x?

**Comment by anhlqn** [comment]
I kept the thread stack size setting in `jvm.options` from 5.0.0 beta version when trying to install ES as a service for ES 5.2.0 on Windows 10, and after running `elasticsearch-service.bat install`, the cmd prompt disappeared right away without any error message. After a few minutes trying, it turned out that `-Xss1m` is no longer needed and would cause the issue I encountered.

Is there anywhere in the documentation that mentions this change?

**Comment by jasontedor** [comment]
It's covered in the [setup](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/setup.html) docs (see the note towards the bottom).

**Comment by anhlqn** [comment]
So the document says that

> Elasticsearch ships with default configuration for running Elasticsearch on 64-bit server JVMs.

Does it also mean that we can no longer add thread stack size config in jvm.options?

**Comment by jasontedor** [comment]
> Does this mean that we can no longer add thread stack size config in jvm.options?

It means that you no longer have to.

**Pull request merged**
