### PR TITLE
	Improve handle of spaces on Windows by using shorten paths

### PR DESCRIPTION
**Pull request by TheFireCookie**
Adding S in the %~d something to use shorter names (
https://www.microsoft.com/resources/documentation/windows/xp/all/proddocs/en-us/percent.mspx?mfr=true
)

### CODE REVIEW

**Comment by rjernst** [comment]
@TheFireCookie Sorry for the long delay on looking at this. @russcam can you review?

**Comment by russcam** [comment]
@TheFireCookie I'm curious to understand the impetus for using SFNs here; was there a particular issue that you've hit with using Long File Names?

One potential issue I can see with using SFNs is that [their generation can be disabled with a registry key ](https://support.microsoft.com/en-gb/help/210638/how-to-disable-automatic-short-file-name-generation?wa=wsignin1.0%3Fwa%3Dwsignin1.0) although in practice, I don't know how often this tends to be disabled. Worth pointing out however.

**Comment by TheFireCookie** [comment]
Yep, we are working in the Program Files (x86) directory and the bat were not starting because of the (x86) in the path.

**Comment by russcam** [comment]
This has been fixed for ES_JVM_OPTIONS in https://github.com/elastic/elasticsearch/pull/24731, but your PR points out other places where this also needs to be applied. 

Given the potential for disabling SFNs, I'm inclined to quote variable assignments as per the https://github.com/elastic/elasticsearch/pull/24731 to overcome this issue instead of using SFNs. What do you think @TheFireCookie?

**Comment by TheFireCookie** [comment]
Pull this other request, pull out a new ElasticSearch version and I'll try it without usings the shorten name and if it works, we could close this PR I guess :) what do you think?

**Comment by rjernst** [comment]
@TheFireCookie #24731 was already merged and released in 5.4.1 and 5.3.3. Can you try it out?

**Comment by dakrone** [comment]
Closing as there has been no feedback, feel free to comment if this was closed erroneously.

**Pull request closed without merging**
