### PR TITLE
Make sure to close XContentParser in more spots

### PR DESCRIPTION
**Pull request by original-brownbear**
We're leaking quite a few of these parsers. That doesn't seem to be much of a problem but results in some memory inefficiencies in Jackson here and there. This PR bulk fixes a bunch of instances that I could easily automatically fix but is not exhaustive by any means. It covers most of the production spots that were left though.

### CODE REVIEW

**Comment by ldematte** [comment]
In general looks good, but I'm a bit worried by exactly the case you find in the "fix" commit: we create a parser and pass "ownership" to someone that will use it after it exits the scope of the try-with-resource block. These are hard to spot unless checked one by one... should we do that?

**Comment by original-brownbear** [comment]
> These are hard to spot unless checked one by one... should we do that?

Not sure it's worth it. I went over them quickly now and it seems to me that this really is the only spot that isn't some sort of parse method behind the scenes. If we do something this tricky we really should have  (and to be fair had) tests for it :)

**Comment by ldematte** [comment]
> If we do something this tricky we really should have (and to be fair had) tests for it :)

++
And/or have big clues in names to make all aware of what's happening

**Review by ldematte — APPROVED** [review]
I scanned over the other usages, and the Iterator (the one you already fixed) was the only case I found where ownership was transferred. LGTM!

**Comment by original-brownbear** [comment]
Thanks Lorenzo!

**Pull request merged**
