### PR TITLE
Fix LogsDB plugin initialisation of `cluster.logsdb.enabled`

### PR DESCRIPTION
**Pull request by salvatore-campagna**
When initialising LogsDB plugin we need to retrieve the `cluster.logsdb.enabled` setting
from cluster settings as it is written by the `stateless` plugin.

### CODE REVIEW

**Comment by salvatore-campagna** [comment]
@elasticmachine update branch

**Comment by salvatore-campagna** [comment]
@elasticmachine update branch

**Review by martijnvg — APPROVED** [review]
LGTM

**Comment by salvatore-campagna** [comment]
@elasticmachine update branch

**Comment by salvatore-campagna** [comment]
@elasticmachine update branch

**Pull request merged**
