### PR TITLE
Calculate SHA256 fingerprint for enrollment token

### PR DESCRIPTION
**Pull request by BigPandaToo**
Calculate SHA256 fingerprint for enrollment token

A follow up PR for:
#73573

### CODE REVIEW

**Review by jkakavas — APPROVED** [review]
LGTM

**Comment by jkakavas** [comment]
Changed the label to non-issue because this is unreleased code

**Comment by BigPandaToo** [comment]
@elasticmachine update branch

**Comment by jkakavas** [comment]
You need to update your assertions as https://github.com/elastic/elasticsearch/pull/72207 updated the httpCa.p12 that we use for the enrollment tests

**Comment by BigPandaToo** [comment]
@elasticmachine update branch

**Pull request merged**
