### PR TITLE
Fix incorrect mutex used in QueryPhaseResultConsumer

### LINKED ISSUE #115716: [CI] IndexActionIT testAutoGenerateIdNoDuplicates failing
**Build Scans:**
- [elasticsearch-periodic-platform-support #4701 / debian-11_platform-support-unix](https://gradle-enterprise.elastic.co/s/d6ejkqj6pwryk)
- [elasticsearch-periodic-platform-support #4634 / ubuntu-1804_platform-support-unix](https://gradle-enterprise.elastic.co/s/xatz76s7avjzu)
- [elasticsearch-pull-request #39164 / part-1-windows](https://gradle-enterprise.elastic.co/s/eleqwql4xdmqq)

**Reproduction Line:**
```
./gradlew ":server:internalClusterTest" --tests "org.elasticsearch.indexing.IndexActionIT.testAutoGenerateIdNoDuplicates" -Dtests.seed=8A25C118553F09E1 -Dtests.locale=nl-Latn-NL -Dtests.timezone=ECT -Druntime.java=23
```

**Applicable branches:**
main

**Reproduces locally?:**
N/A

**Failure History:**
[See dashboard](https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(refreshInterval:(pause:!t,value:60000),time:(from:now-7d%2Fd,to:now))&_a=(controlGroupState:(initialChildControlState:('0c0c9cb8-ccd2-45c6-9b13-96bac4abc542':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:task.keyword,order:0,selectedOptions:!(),title:'GradleTask',type:optionsListControl),'4e6ad9d6-6fdc-4fcc-bf1a-aa6ca79e0850':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:className.keyword,order:1,selectedOptions:!(org.elasticsearch.indexing.IndexActionIT),title:'Suite',type:optionsListControl),'144933da-5c1b-4257-a969-7f43455a7901':(dataViewId:fbbdc689-be23-4b3d-8057-aa402e9ed0c5,fieldName:name.keyword,order:2,selectedOptions:!(testAutoGenerateIdNoDuplicates),title:'Test',type:optionsListControl)))))

**Failure Message:**
```
java.lang.Exception: Test abandoned because suite timeout was reached.
```

**Issue Reasons:**
- [main] 3 failures in test testAutoGenerateIdNoDuplicates (0.9% fail rate in 336 executions)
- [main] 2 failures in pipeline elasticsearch-periodic-platform-support (33.3% fail rate in 6 executions)

**Note:**
This issue was created using new test triage automation. Please report issues or feedback to es-delivery.

### PR DESCRIPTION
**Pull request by original-brownbear**
Everything synchronizes on PendingMerges, this was just a typo. 

Non-issue since this hasn't been released yet. This likely fixes a bunch of other tests, I'll open a separate PR for those after going through them 1 by 1. 

closes #115716

### CODE REVIEW

**Comment by benwtrent** [comment]
Looking at the PR that originally added the sync, https://github.com/elastic/elasticsearch/pull/113355

Seems like it is only in v9? Not sure why this has a `v8.` tag.

Also, I don't understand why we would `synchronize` on `QueryPhaseResultConsumer.this` at all, maybe I am misreading the code, but all the elements inside those two blocks are local to `PendingMerges`? Could you clarify a bit there?

**Comment by original-brownbear** [comment]
Thanks for taking a look Ben!

> Also, I don't understand why we would synchronize on QueryPhaseResultConsumer.this at all, maybe I am misreading the code

sorry that was just me being stupid, just spotted the first mistake and got too happy that it made the failures go away ... fixed both spots now.

> Seems like it is only in v9? Not sure why this has a v8. tag.

My bad yet again, should back port the other PR too. Will fix this up after.

**Review by benwtrent — APPROVED** [review]
All locking is now done on `PendingMerges` & `MergeTask` object instances. This seems better. 

I do not fully know if this will fix the overall issues. But its an obvious bug in the previous refactoring. So let's first fix this. If this doesn't work, then I suggest we revert the refactoring @original-brownbear https://github.com/elastic/elasticsearch/pull/113355 

this code is tricky :)

**Comment by original-brownbear** [comment]
Thanks Ben! I think this code just shouldn't be so tricky. I'm gonna follow-up here with some serious simplification now. All this does is queue and once we queued enough, merge + some checks on the stuff queued. There's no need for this to be hard :)

**Comment by original-brownbear** [comment]
Actually @benwtrent turns out the remaining issue here is the result of https://github.com/elastic/elasticsearch/pull/113230 (also mine though, sorry :/ ...) fixing it.

**Pull request merged**
