### PR TITLE
[TEST] Address ExplainableScriptIT failure

### PR DESCRIPTION
**Pull request by javanna**
ExplainableScriptIT tests the output of an explainable score script. The script declares that it does not need the score, in fact it returns the score as the value of a field from each document. The explain output though includes the explanation of the sub query, whose score is completely replaced by function score. The test assertson the sub query explanation which is thought inaccurate as the script declares that it needs no score.

This test issue was made more evident by
https://github.com/apache/lucene/pull/12383  as the sub query score became 0 . The solution is to not include the sub query explanation in the script explain output and remove the assertions that depend on that part of the output.

### CODE REVIEW

**Comment by jpountz** [comment]
It looks good to me, but should it go to the `main` branch rather than `lucene_snapshot`?

**Comment by javanna** [comment]
> but should it go to the main branch rather than lucene_snapshot?

I was wondering too, yea that's a good idea to push it to main.

**Comment by javanna** [comment]
I rebased and targeted main.

**Comment by javanna** [comment]
run elasticsearch-ci/part-1

**Review by jpountz — APPROVED** [review]

**Pull request merged**
