### PR TITLE
Change behavioral analytics API Spec naming

### PR DESCRIPTION
**Pull request by carlosdelest**
Following the conversation in https://github.com/elastic/elasticsearch-specification/pull/2110, changing the API Spec file names to differentiate them from search applications.

### CODE REVIEW

**Review by sethmlarson — COMMENTED** [review]
In order to follow the API design guidelines the root path segment would need to be updated to match the API namespace:

ie: `/_application/analytics/...` -> `/_behavioral_analytics/...`

**Comment by carlosdelest** [comment]
> In order to follow the API design guidelines the root path segment would need to be updated to match the API namespace:
> 
> ie: `/_application/analytics/...` -> `/_behavioral_analytics/...`

Search Applications don't currently do this either - they are on `_application/search_applications`. Is this something we want to fix as well?

**Comment by sethmlarson** [comment]
@carlosdelest That could be done as well, it all depends on the future plans for the API namespace. An example to look at might be snapshots and snapshot repositories, the top-level API namespace is `snapshot` but the APIs are either `snapshots.get_repository` -> `GET /_snapshot/<repo>` or `snapshots.get` -> `GET /_snapshot/<repo>/<snapshot>`. Doesn't have to be a mapping of API model -> API namespace, but the API namespace should match the root path segment for sure.

**Comment by carlosdelest** [comment]
@sethmlarson We're still not sure about the future of the APIs, for now that's what we have:

```
_application/search_application
_application/analytics
```

We can either use a common `application` namespace, or leave it as is - it just feels wrong to me to have analytics on `search_application` namespace.

What would you propose to do to adhere to standards, and provide a meaningful namespace for our clients?

**Review by joemcelroy — APPROVED** [review]

**Comment by sethmlarson** [comment]
I'd also be okay with renaming the API namespace to be `application` and then changing the Search Application API names to be along the lines of `application.put_search_application`, and `application.get_search_application`, etc.

**Review by kderusso — APPROVED** [review]

**Pull request closed without merging**
