### PR TITLE
Refactor bootstrap checks

### PR DESCRIPTION
**Pull request by jasontedor**
This commit refactors the bootstrap checks into a dedicated class. The
refactoring provides a model for different limits per operating system,
and provides a model for unit tests for individual checks.

Relates #16733, relates #16835

### CODE REVIEW

**Comment by rmuir** [comment]
I guess for me what is broken, is the implication that if i want to bind to some address other than the default, that this means i'm gonna overload my machine with thousands of shards.

I don't change things like file descriptors limits on my computer because i really don't want to have non-default values here as a developer. Now what to do... I suppose this effectively stops me from working on the networking code at the very least.

**Comment by s1monw** [comment]
@jasontedor  I guess we should go with an explicit setting for now? I think it's less controversial? the other option is to move to an opt out setting?

**Comment by jaymode** [comment]
> the other option is to move to an opt out setting?

+1. If the error message tells you that you can disable this check with setting `foo` but never do it in production, I think that would be a good compromise?

**Comment by nik9000** [comment]
> +1. If the error message tells you that you can disable this check with setting foo but never do it in production, I think that would be a good compromise?

I prefer opt out as well. You have to intentionally think "I don't care about safe stuff, just do things". And `gradle run` can just set it all the time.

**Comment by jaymode** [comment]
I'll caveat my earlier comment, **if** we are adding a setting then I prefer opt-out. I think its a fine line between preventing users from shooting themselves in the foot and making it harder to do development when a change is made like setting `network.host` so two developers could collaborate on a change together.

**Comment by s1monw** [comment]
to be honest I don't like either way. The fact that OSX is a pain to get this configured correctly is concerning and given the fact that OSX is unlikely a production env we can maybe opt out automatically if we run on OSX? I mean all these checks are best effort so I guess that's not that much of a problem. what do you think @jasontedor  just use this constant: `Constants.MAC_OS_X`

**Comment by jasontedor** [comment]
> The fact that OSX is a pain to get this configured correctly is concerning and given the fact that OSX is unlikely a production env we can maybe opt out automatically if we run on OS X?

I am not in favor of opting out automatically on OS X, but I am in favor of reduced limits for the file descriptor check on OS X. I think that future checks can be handled on a case-by-case basis.

**Comment by jasontedor** [comment]
@rmuir @s1monw I pushed 5ab639a6341bdd7466fd0d89d83225c56b199dae which drops the file descriptor check on OS X to the default setting, and removed the different checks between snapshot and release builds.

**Comment by s1monw** [comment]
LGTM

**Pull request closed without merging**
