### PR TITLE
Handle RejectedExecutionException in ShardFollowTasksExecutor

### PR DESCRIPTION
**Pull request by original-brownbear**
Follow-up to #65415. We can't have this exception bubble up in an exception
handler any longer due to the new assertion so we must handle it here.

### CODE REVIEW

**Comment by original-brownbear** [comment]
Fixes https://gradle-enterprise.elastic.co/s/qy5rojufgdefw/tests/:x-pack:plugin:ccr:internalClusterTest/org.elasticsearch.xpack.ccr.RestartIndexFollowingIT/testFollowIndex

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/2

**Review by dnhatn — APPROVED** [review]
LGTM.

**Comment by original-brownbear** [comment]
Thanks Nhat!

**Pull request merged**
