### PR TITLE
HLRC: UpdateByQuery API with wait_for_completion being false

### LINKED ISSUE #46350: shouldStoreResult is not set correctly
**Elasticsearch version** (`bin/elasticsearch --version`): 6.5.3

**Plugins installed**: []

**JVM version**: 1.8

**OS version** (`uname -a` if on a Unix-like system): Darwin Kernel Version 18.6.0

**Description of the problem including expected versus actual behavior**: 

When trying to make an updateByQuery call with the Java RestHighLevelClient, `shouldStoreResult` is always false, even if you explicitly set the request object to true. The updateByQuery tasks are not stored when they have finished or failed and when you try to retrieve them, and exception is thrown.

**Steps to reproduce**: 

 1. Create an UpdateByQueryRequest and set `shouldStoreResult`:
```
UpdateByQueryRequest request = UpdateByQueryRequest("index").setShouldStoreResult(true).setScript(new Script(ScriptType.STORED, null, scriptId, params));
```
 2. Call updateByQueryAsync:
```
restClient.updateByQueryAsync(request, RequestOptions.DEFAULT, listener);
```
 3. Get the list of tasks, and then try to retrieve the task by id in Kibana:
```
ListTasksRequest request = new ListTasksRequest().setActions("*byquery").setDetailed(true);
ListTasksResponse response = esRestClient.tasks().list(request, RequestOptions.DEFAULT);
```
```
// kibana
GET _tasks/:taskId
```
**Provide logs (if relevant)**:
Kibana error when you try to fetch
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "resource_not_found_exception",
        "reason" : "task [24XlcEQtRfa1FI5rkpioGw:65213] isn't running and hasn't stored its results"
      }
    ],
    "type" : "resource_not_found_exception",
    "reason" : "task [24XlcEQtRfa1FI5rkpioGw:65213] isn't running and hasn't stored its results"
  },
  "status" : 404
}
```

### PR DESCRIPTION
**Pull request by tumile**
Extend support for wait_for_completion=false to UpdateByQuery API by adding `submitUpdateByQueryTask`. Similar to prior art #35202.

Closes: #46350.

### CODE REVIEW

**Comment by andreidan** [comment]
@elasticmachine ok to test

**Comment by andreidan** [comment]
@tumile Thank you for the contribution and sorry it took us so long to get to this. This generally looks very good 🎉 

Would you mind merging master into your branch and fixing the conflict?

**Comment by tumile** [comment]
Yes I'm on it 🙌

**Comment by tumile** [comment]
@andreidan ready for review

**Review by andreidan — APPROVED** [review]
LGTM, thanks for working on this

**Pull request merged**
