### PR TITLE
[8.8] Warn if allocation diverged from the desired allocation

### PR DESCRIPTION
**Pull request by idegtiarenko**
Backports the following commits to 8.8:

 - Warn if allocation diverged from the desired allocation (#95458)

### CODE REVIEW

**Comment by idegtiarenko** [comment]
@elasticmachine please run elasticsearch-ci/example-plugins

**Comment by idegtiarenko** [comment]
@elasticmachine please run elasticsearch-ci/example-plugins

**Comment by breskeby** [comment]
@elasticmachine run elasticsearch-ci/example-plugins

**Comment by idegtiarenko** [comment]
@elasticmachine please run elasticsearch-ci/example-plugins

**Pull request merged**
