### PR TITLE
Fix Temporarily Leaking Shard Level Metadata Blobs in some Cases

### PR DESCRIPTION
**Pull request by original-brownbear**
When doing out of order finalizations we would leak shard level metadata blobs at times.
This commit enhances the cleanup logic after finalization to catch these leaked blobs
and adds a test that would without this fix trip the leaked blobs assertion in the test
infrastructure.

This is a bit of a brute force-solution and it would be nicer to integrate collecting the generations to delete while we compute the finalization state update but I think it's good enough and I found this easiest for reviewers. Mainly did it this way since the finalization state update has some in-flight work for refactoring it for readability. Maybe we can later join this in there.

### CODE REVIEW

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/part-2

**Comment by original-brownbear** [comment]
@DaveCTurner @tlrx ping in case you have a second. This one isn't terribly important/urgent though, take your time :)

**Review by DaveCTurner — APPROVED** [review]
LGTM; I think this was something else the stress tests were hitting too, so it'll help to fix this.

**Review by tlrx — APPROVED** [review]
LGTM - sorry for the delay

**Comment by original-brownbear** [comment]
No worries Tanguy! And thanks you two!

**Pull request merged**
