### PR TITLE
Fix a mistake

### PR DESCRIPTION
**Pull request by arashlayeghi**

### CODE REVIEW

**Comment by jrodewig** [comment]
@arashlayeghi Please sign our CLA so we can accept these changes:
https://www.elastic.co/contributor-agreement

This is required before we can merge this PR. Please ensure you use the same email address
associated with your commit. You can find that address here:
https://github.com/elastic/elasticsearch/commit/7178a20d3432d44f6a5e07c1e7a18be631774151.patch

Thanks!

**Comment by arashlayeghi** [comment]
> @arashlayeghi Please sign our CLA so we can accept these changes:
> https://www.elastic.co/contributor-agreement
> 
> This is required before we can merge this PR. Please ensure you use the same email address
> associated with your commit. You can find that address here:
> https://github.com/elastic/elasticsearch/commit/7178a20d3432d44f6a5e07c1e7a18be631774151.patch
> 
> Thanks!

@jrodewig I signed it just know with my email address associated with my commit.

**Review by jrodewig — APPROVED** [review]
LGTM. Thanks @arashlayeghi

**Comment by jrodewig** [comment]
@elasticmachine test this please

**Pull request merged**
