### PR TITLE
SQL: Fix qualified attribute resolution with CCS

### PR DESCRIPTION
**Pull request by bpintea**
In case the fields are qualified only by the index name in a
CCS SQL query, the field resolution was failing since an
attribute's qualification contains the cluster name, while a field's doesn't.

This changes the existing  `Attribute#qualifiedName()` to return a qualification
including the index name only and adds (for completion) a new method,
`fullyQualifiedName()`, which will return the 'cluster:index' qualification.

This will allow queries like this to work:
 `SELECT remote_index.field FROM remote_cluster:remote_index`
or
 `SELECT remote_index.field FROM remote_index` when the cluster is provided
through the xDBC "cluster" parameter.

### CODE REVIEW

**Review by costin — APPROVED** [review]
Left some minor comments - LGTM otherwise.

**Comment by bpintea** [comment]
@elasticmachine run elasticsearch-ci/part-2

**Comment by bpintea** [comment]
@elasticmachine update branch

**Review by astefan — APPROVED** [review]
LGTM

**Pull request merged**
