### PR TITLE
Enhance Get Tokens API docs

### LINKED ISSUE #36946: Document the supported use cases for the `Get Token` API
Our current [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-get-token.html) doesn't clarify that the `password` grant requires additional permissions and that it implements the `Resource Owner Password Credentials Grant`. As such users often tend to think that this can be used as a replacement of Basic Authentication where they can make an unauthenticated request with their credentials and get an access token to use for subsequent ones.

### PR DESCRIPTION
**Pull request by jkakavas**
Add some details to make more obvious that neither `password` nor
`client_credentials` grant types are designed to be used for self
service user creation of tokens as this comes up quite often in
forums and users trying to use them for that reason.

Resolves: #36946

### CODE REVIEW

**Comment by jkakavas** [comment]
@elasticmachine update branch

**Comment by jkakavas** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by tvernum** [comment]
Do we want to add a reference for API Keys as an alternative for the use cases that tokens are not intended to support?

**Comment by jkakavas** [comment]
> Do we want to add a reference for API Keys as an alternative for the use cases that tokens are not intended to support?

:+1: 

I have a note to do this once https://github.com/elastic/elasticsearch/issues/40031 is resolved. I didn't want to suggest API keys now when it still requires at least `manage_api_key` ( that allows users to delete api keys of others )

**Review by tvernum — APPROVED** [review]
LGTM

**Comment by jkakavas** [comment]
:man_facepalming: @lcawl apologies, I saw the green tick and failed to see you haven't gone through it yet. I'll wait for your input before backporting this

**Comment by lcawl** [comment]
No worries, @jkakavas I've drafted some suggested changes in https://github.com/elastic/elasticsearch/pull/45312

**Pull request merged**
