### PR TITLE
Propagate mapper builder context flags across nested mapper builder context creation

### PR DESCRIPTION
**Pull request by javanna**
MapperBuilderContext includes information about whether synthetic source is configured, we are in a data streams and there are dimensions. This info is currently not propagated across the constructor of NestedMapperBuilderContext, which means that the builder context for the nested type receives hardcoded (false) info. This commit fixes that.

One symptom of this, due to not propagating the info about whether synthetic source is configured, is that numeric fields that have `ignore_malformed` set to `true`, mapped under a `nested` type, will cause shard failures whenever a document with ignored values is retrieved in the fetch phase:

```
[2024-06-21T19:31:11,839][WARN ][o.e.a.s.TransportSearchAction] [node_s0] TransportSearchAction shard failure (partial results response)
org.elasticsearch.action.search.ShardSearchFailure: null
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:562) ~[main/:?]
	at org.elasticsearch.action.search.CountedCollector.onFailure(CountedCollector.java:57) ~[main/:?]
	at org.elasticsearch.action.search.FetchSearchPhase$2.onFailure(FetchSearchPhase.java:233) ~[main/:?]
	at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:53) ~[main/:?]
	at org.elasticsearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:672) ~[main/:?]
	at org.elasticsearch.transport.TransportService$UnregisterChildTransportResponseHandler.handleException(TransportService.java:1766) ~[main/:?]
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1490) ~[main/:?]
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1624) ~[main/:?]
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1599) ~[main/:?]
	at org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:44) ~[main/:?]
	at org.elasticsearch.action.support.ChannelActionListener.onFailure(ChannelActionListener.java:44) ~[main/:?]
	at org.elasticsearch.search.SearchService$2.onFailure(SearchService.java:1241) ~[main/:?]
	at org.elasticsearch.action.ActionRunnable.onFailure(ActionRunnable.java:151) ~[main/:?]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:28) ~[main/:?]
	at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33) ~[main/:?]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984) ~[main/:?]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[main/:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: com.fasterxml.jackson.core.JsonGenerationException: Can not start an object, expecting field name (context: Object)
	at com.fasterxml.jackson.core.JsonGenerator._reportError(JsonGenerator.java:2849) ~[?:?]
	at com.fasterxml.jackson.core.json.JsonGeneratorImpl._reportCantWriteValueExpectName(JsonGeneratorImpl.java:262) ~[?:?]
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator._verifyValueWrite(UTF8JsonGenerator.java:1179) ~[?:?]
	at com.fasterxml.jackson.core.json.UTF8JsonGenerator.writeStartObject(UTF8JsonGenerator.java:375) ~[?:?]
	at org.elasticsearch.xcontent.provider.json.JsonXContentGenerator.writeStartObject(JsonXContentGenerator.java:148) ~[?:?]
	at org.elasticsearch.xcontent.XContentBuilder.startObject(XContentBuilder.java:329) ~[elasticsearch-x-content-8.15.0-SNAPSHOT.jar:8.15.0-SNAPSHOT]
	at org.elasticsearch.index.mapper.SourceLoader$Synthetic$SyntheticLeaf.write(SourceLoader.java:216) ~[main/:?]
	at org.elasticsearch.index.mapper.SourceLoader$Synthetic$LeafWithMetrics.write(SourceLoader.java:158) ~[main/:?]
	at org.elasticsearch.index.mapper.NestedObjectMapper$NestedSyntheticFieldLoader.write(NestedObjectMapper.java:456) ~[main/:?]
	at org.elasticsearch.index.mapper.ObjectMapper$SyntheticSourceFieldLoader.write(ObjectMapper.java:875) ~[main/:?]
	at org.elasticsearch.index.mapper.SourceLoader$Synthetic$SyntheticLeaf.write(SourceLoader.java:214) ~[main/:?]
	at org.elasticsearch.index.mapper.SourceLoader$Synthetic$SyntheticLeaf.source(SourceLoader.java:181) ~[main/:?]
	at org.elasticsearch.index.mapper.SourceLoader$Synthetic$LeafWithMetrics.source(SourceLoader.java:146) ~[main/:?]
	at org.elasticsearch.search.fetch.FetchPhase.prepareNonNestedHitContext(FetchPhase.java:289) ~[main/:?]
	at org.elasticsearch.search.fetch.FetchPhase.prepareHitContext(FetchPhase.java:232) ~[main/:?]
	at org.elasticsearch.search.fetch.FetchPhase$1.nextDoc(FetchPhase.java:161) ~[main/:?]
	at org.elasticsearch.search.fetch.FetchPhaseDocsIterator.iterate(FetchPhaseDocsIterator.java:71) ~[main/:?]
	at org.elasticsearch.search.fetch.FetchPhase.buildSearchHits(FetchPhase.java:190) ~[main/:?]
	at org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:80) ~[main/:?]
	at org.elasticsearch.search.SearchService.lambda$executeFetchPhase$10(SearchService.java:907) ~[main/:?]
	at org.elasticsearch.action.ActionRunnable$3.accept(ActionRunnable.java:78) ~[main/:?]
	at org.elasticsearch.action.ActionRunnable$3.accept(ActionRunnable.java:75) ~[main/:?]
	at org.elasticsearch.action.ActionRunnable$4.doRun(ActionRunnable.java:100) ~[main/:?]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[main/:?]
	... 6 more
	Suppressed: java.lang.IllegalStateException: Failed to close the XContentBuilder
		at org.elasticsearch.xcontent.XContentBuilder.close(XContentBuilder.java:1281) ~[elasticsearch-x-content-8.15.0-SNAPSHOT.jar:8.15.0-SNAPSHOT]
		at org.elasticsearch.index.mapper.SourceLoader$Synthetic$SyntheticLeaf.source(SourceLoader.java:180) ~[main/:?]
		at org.elasticsearch.index.mapper.SourceLoader$Synthetic$LeafWithMetrics.source(SourceLoader.java:146) ~[main/:?]
		at org.elasticsearch.search.fetch.FetchPhase.prepareNonNestedHitContext(FetchPhase.java:289) ~[main/:?]
		at org.elasticsearch.search.fetch.FetchPhase.prepareHitContext(FetchPhase.java:232) ~[main/:?]
		at org.elasticsearch.search.fetch.FetchPhase$1.nextDoc(FetchPhase.java:161) ~[main/:?]
		at org.elasticsearch.search.fetch.FetchPhaseDocsIterator.iterate(FetchPhaseDocsIterator.java:71) ~[main/:?]
		at org.elasticsearch.search.fetch.FetchPhase.buildSearchHits(FetchPhase.java:190) ~[main/:?]
		at org.elasticsearch.search.fetch.FetchPhase.execute(FetchPhase.java:80) ~[main/:?]
		at org.elasticsearch.search.SearchService.lambda$executeFetchPhase$10(SearchService.java:907) ~[main/:?]
		at org.elasticsearch.action.ActionRunnable$3.accept(ActionRunnable.java:78) ~[main/:?]
		at org.elasticsearch.action.ActionRunnable$3.accept(ActionRunnable.java:75) ~[main/:?]
		at org.elasticsearch.action.ActionRunnable$4.doRun(ActionRunnable.java:100) ~[main/:?]
		at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[main/:?]
		at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33) ~[main/:?]
		at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:984) ~[main/:?]
		at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[main/:?]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
		at java.lang.Thread.run(Thread.java:1570) ~[?:?]
	Caused by: java.io.IOException: Unclosed object or array found
		at org.elasticsearch.xcontent.provider.json.JsonXContentGenerator.close(JsonXContentGenerator.java:599) ~[?:?]
		at org.elasticsearch.xcontent.XContentBuilder.close(XContentBuilder.java:1279) ~[elasticsearch-x-content-8.15.0-SNAPSHOT.jar:8.15.0-SNAPSHOT]
		... 19 more
```

### CODE REVIEW

**Review by martijnvg — APPROVED** [review]
LGTM

**Review by martijnvg — COMMENTED** [review]
Maybe add a yaml test with a mapping that uses a nested field type, which has a sub field of type date or long with ignore_malformed enabled. Also enable index.mode=logs. Index a document with that structure and with a malformed value. Then assert that the malformed value can be retrieved from _source. I expect this to fail without this fix.

**Review by martijnvg — APPROVED** [review]
Thanks for adding the integration test that shows how this bug breaks synthetic source.
LGTM2

**Comment by javanna** [comment]
@elasticmachine run elasticsearch-ci/part-1

**Pull request merged**
