### PR TITLE
Remove TypeFieldMapper

### PR DESCRIPTION
**Pull request by romseygeek**
We don't need a special TypeFieldMapper for anything in master; all access 
to the type field can be done via a TypeFieldType that issues appropriate
deprecation warnings.

Relates to #41059

### CODE REVIEW

**Comment by romseygeek** [comment]
@elasticmachine run elasticsearch-ci/1

**Review by mayya-sharipova — APPROVED** [review]
@romseygeek thanks, this PR LGTM.  Just wanted to confirm with you that in 8.0 we still want to allow queries and aggs on _type field? Didn't we want to completely disallow this?

**Comment by romseygeek** [comment]
> Didn't we want to completely disallow this?

Yes, we'll disallow it in a follow up but I wanted to get the deprecations into master and 7x first.

**Comment by romseygeek** [comment]
Hm, it looks like we can't actually backport this to 7x because the type field mapper is still used in various places, and the neat field type improvements don't work because the type itself is not necessarily known when then mapper is built.  So we need to wait until 9x to remove things fully, unfortunately.

**Pull request merged**
