### PR TITLE
Fix bitset filter cache loading in Stateless

### PR DESCRIPTION
**Pull request by kingherc**
As recognized in [this comment discussion](https://github.com/elastic/elasticsearch/pull/113478/files#r1788052333), the bitset filter cache was wrongly eagerly loaded only for fast refresh indices on index nodes in PR https://github.com/elastic/elasticsearch/pull/105791 . However, it should be eagerly loaded for any index that can be searched. This PR fixes this. After https://github.com/elastic/elasticsearch/pull/113478 , searches can happen only on search nodes (irrespective of whether an index is fast refresh or not), so doing that in this PR.

### CODE REVIEW

**Comment by kingherc** [comment]
Gentle reminder for reviewing this! Hopefully it's a very small PR to review. And will unblock https://github.com/elastic/elasticsearch/pull/113478 .

**Review by henningandersen — APPROVED** [review]
LGTM (but we should have a search team review here).

Ideally we'd merge #113478 first, then this PR simplifies even more.

**Comment by kingherc** [comment]
Gentle reminder for search team to review this. cc @original-brownbear , @JVerwolf

**Comment by kingherc** [comment]
Gentle reminder for review by @elastic/es-search-foundations , @original-brownbear , @JVerwolf

**Review by JVerwolf — COMMENTED** [review]
This looks good to me.  Thanks for fixing this @kingherc !

**Review by JVerwolf — APPROVED** [review]

**Pull request merged**
