### PR TITLE
Row-centric output for _cat/fielddata

### LINKED ISSUE #10249: Change output of _cat/fielddata to be row-centric
Currently `_cat/fielddata` adds a column per field:

```
id                     host        ip         node          total title disambiguation 
lFPaYAUQTUGKOIKiRYZOeg hotel.local 10.0.1.200 raphael          0b    0b             0b 
qfsKN3rAQ0q9Ef1eUF-fvA hotel.local 10.0.1.200 splinter         0b    0b             0b 
djZlGw6qQcGBNCqW5iFoIA hotel.local 10.0.1.200 michaelangelo 9.7kb 8.2kb          1.4kb 
OsBOGm9UQFypK10Kx4r99A hotel.local 10.0.1.200 donatello        0b    0b             0b 
3YEw8s0KTTaLrn3HVNkXCg hotel.local 10.0.1.200 leonardo         0b    0b             0b 
```

which isn't really the spirit of the cat api.  In order to find out how many fields are in the cache on `michaelangelo`, eg, you'd have to count the columns. In order to sort the fields in descending order by bytes, you'd have to do some significant processing (read: something more than counting some lines) outside the api, rather than just a `?bytes=b | sort -rnk999`.

I propose something like:

```
id                     host        ip         node          field           size
lFPaYAUQTUGKOIKiRYZOeg hotel.local 10.0.1.200 raphael       total             0b
djZlGw6qQcGBNCqW5iFoIA hotel.local 10.0.1.200 michaelangelo total          9.7kb
djZlGw6qQcGBNCqW5iFoIA hotel.local 10.0.1.200 michaelangelo title          8.2kb
djZlGw6qQcGBNCqW5iFoIA hotel.local 10.0.1.200 michaelangelo disambiguation 1.4kb
```

Then you can ask questions like:

```
curl -s 'localhost:9200/_cat/fielddata?h=node,field,size&bytes=b' | fgrep -v ' total' | sort -rnk3 | head
```

to get a snapshot of the biggest offenders and where they live.  This denormalization is the heart of the API, like with `segments` and `shards`.

### PR DESCRIPTION
**Pull request by alexshadow007**
I deleted field `total`, because I think it's bad idea to mix aggregate size with individual field sizes. You can get total field data usage per node by `_cat/nodes` API.

Closes #10249

### CODE REVIEW

**Comment by clintongormley** [comment]
@dakrone could you review this please?

**Comment by dakrone** [comment]
@alexshadow007 this looks good to me, can you drop a note into `docs/reference/migration/migrate_5_0.asciidoc` mentioning this breaking change? After that I will happily merge, thanks!

**Comment by alexshadow007** [comment]
@dakrone Done

**Comment by dakrone** [comment]
Merged, thanks @alexshadow007!

**Pull request merged**
