### PR TITLE
Test that Jayatana is ignored

### PR DESCRIPTION
**Pull request by nik9000**
Installs javatana in vivid, emulates its on-login actions when starting
elasticsearch and verifies that elasticsearch turns off javatana.

Relates to #13813

### CODE REVIEW

**Comment by rmuir** [comment]
awesome

**Comment by nik9000** [comment]
@brwe or @spinscale, want to review?

**Comment by spinscale** [comment]
nice. one. Ran the tests

LGTM

**Comment by nik9000** [comment]
Merged to 3.0 and cherry-picked to 2.x, 2.1, and 2.0. So much cherry-pick.

**Pull request merged**
