### PR TITLE
Add test coverage for Painless general casting of boolean and Boolean

### PR DESCRIPTION
**Pull request by jdconrad**
This adds test coverage for general casts in Painless between boolean and other types and Boolean and other types.

### CODE REVIEW

**Comment by jdconrad** [comment]
@elasticmachine test this please

**Comment by jdconrad** [comment]
@elasticmachine test this please

**Comment by jdconrad** [comment]
@elasticmachine run elasticsearch-ci/1

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by jdconrad** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by jdconrad** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by jdconrad** [comment]
@rjernst Thanks for the review!

**Pull request merged**
