### PR TITLE
SQL: add "fuzziness" option to QUERY and MATCH function predicates

### LINKED ISSUE #40495: SQL: Fuzziness option for QUERY predicate
At the moment, QUERY (through its `match` and `multi_match` usages) doesn't support the `fuzziness` option.

### PR DESCRIPTION
**Pull request by astefan**
This PR adds `fuzziness` option to QUERY and MATCH function predicates and removes unused "locale" and "lowercase_expanded_terms" options from QUERY.

Once https://github.com/elastic/elasticsearch/pull/40494 is merged, I will update the documentation regarding removed options.

Fixes https://github.com/elastic/elasticsearch/issues/40495.

### CODE REVIEW

**Comment by astefan** [comment]
@elasticmachine run elasticsearch-ci/1

**Review by matriv — COMMENTED** [review]
Looks good, waiting for the docs update.

**Review by matriv — APPROVED** [review]
LGTM

**Review by costin — APPROVED** [review]
LGTM

**Pull request merged**
