### PR TITLE
Fix Eclipse compilation problems

### PR DESCRIPTION
**Pull request by cbuescher**
Eclipse is not so good at doing type inference inside lambdas it seems. The class compiles well using the java compile but Eclipse compiler complains. This change just pulls out the argument into a local variable to avoid the problem.

### CODE REVIEW

**Comment by nik9000** [comment]
LGTM but I think you should add a comment explaining why you've pulled the lists out. If you can reference the eclipse bug that'd be even butter. I don't know which bug it is. It is fixed in Oxygen though.

**Comment by cbuescher** [comment]
@nik9000 thanks, I added a comment

**Comment by jasontedor** [comment]
Are we going to move away from supporting Eclipse Neon so we stop having to make these changes?

**Comment by cbuescher** [comment]
Yes, I also changed to Oxygen now. Hope it works better in cases like these.

**Comment by jasontedor** [comment]
I opened #26194.

**Pull request merged**
