### PR TITLE
Enable grok processor to support long, double and boolean

### PR DESCRIPTION
**Pull request by kiawin**
It would be useful to allow grok processor to support long, double, and boolean type.

### CODE REVIEW

**Comment by martijnvg** [comment]
@elasticmachine test this please

**Comment by talevy** [comment]
thanks @kiawin, Looks good!

**Comment by talevy** [comment]
This is pending a backport to `6.x` because we'd like to see these changes reflected in Logstash's implementation of Grok. I plan to push a PR for that soon

**Comment by jpountz** [comment]
@talevy Is the backport pending label still relevant?

**Comment by talevy** [comment]
:shame: I did not do a good job following up on this. It would be a simple backport to 6.7, but I waited
because I intended to make sure we have feature-parity in Logstash.

@jakelandis what do you think? Would you think this should go into 6.x?

**Comment by jakelandis** [comment]
@talevy - I think it is good to go back to 6.x.  Logstash grok uses `.to_i` and `.to_f` to coerce the values, which transparently handle values larger then Java's Integer/Float.  I believe support for boolean is the only difference this introduces (and difference are OK).

**Comment by talevy** [comment]
thanks @jakelandis. I'll go ahead and backport to 6.x!

and thanks again @jpountz for bouncing this back up!

**Pull request merged**
