### PR TITLE
Transition Transforms to using hidden indices for notifcations index

### LINKED ISSUE #53762: Transition `.transform-notifications*` to be hidden indices
Now that we have hidden indices (https://github.com/elastic/elasticsearch/pull/50452) and hidden aliases (https://github.com/elastic/elasticsearch/pull/52547) to prevent accidental operations on semi-internal indices, new indices in the `.transform-notifications*` and (if we're still creating new indices in this pattern) `.data-frame-notifications*` patterns should be hidden indices.

Because hidden indices/aliases are still fairly readily accessible, the transition shouldn't involve too much work - in some cases the only work that's been necessary has been adding the `index.hidden` setting to the index template - but I'm happy to take on any work involved, and wanted to make sure we were communicating clearly on the topic. We'd like to do this before the next feature freeze if possible, and I'll put up a PR shortly with some work on the change.

/cc @hendrikmuhs since I hear you're the one to talk to about this.

### PR DESCRIPTION
**Pull request by AthenaEryma**
This commit changes the Transforms notifications index to be hidden
index, with a hidden alias.

This commit also removes the temporary hack in
MetaDataCreateIndexService that prevents deprecation warnings for known
dot-prefixed index names which are not hidden/system indices, as this
was the last index pattern to need that hack.

/cc @jaymode 

Fixes https://github.com/elastic/elasticsearch/issues/53762

### CODE REVIEW

**Review by hendrikmuhs — APPROVED** [review]
LGTM

**Comment by gwbrown** [comment]
@elasticmachine update branch

**Comment by gwbrown** [comment]
Something appears to have happened in master recently and deprecation warnings seem to no longer being emitted over the REST interface when indices are created with dot-prefixed names (despite the unit tests for the deprecation warnings still working), and the test that failed did so because the deprecation warning it expected is not emitted. Going to hold off on merging this until I figure out what's going on there.

**Comment by gwbrown** [comment]
Per some discussion in Slack, looks like the change in behavior is related to https://github.com/elastic/elasticsearch/pull/53785.

**Comment by DaveCTurner** [comment]
That's correct @gwbrown, sorry for leaving `master` in this state. The effects on deprecation warnings weren't apparent until I started to backport the change. I'm reverting it in #53842.

**Comment by DaveCTurner** [comment]
@elasticmachine update branch

**Comment by gwbrown** [comment]
Thanks @DaveCTurner, much appreciated! No worries, stuff happens. Just wanted to make sure I didn't have to make some other adjustment.

**Pull request merged**
