### PR TITLE
Remove DEBUG-level logging from actions in docker

### PR DESCRIPTION
**Pull request by rjernst**
In #51459 DEBUG-level logging was removed from the default log4j
configuration. However, our docker build has its own log4j configuration
which was missed in that change. This commit removes the same from the
docker log4j configuration.

relates #51459
relates #51198

### CODE REVIEW

**Review by nik9000 — APPROVED** [review]
LGTM. I think it is also in the docker/config/oss version of the file too.

**Review by DaveCTurner — APPROVED** [review]
LGTM2, but echoing Nik's comment that `distribution/docker/src/docker/config/oss/log4j2.properties` wants the same treatment.

**Review by nik9000 — COMMENTED** [review]
:metal:

**Comment by rjernst** [comment]
@elasticmachine run elasticsearch-ci/packaging-matrix-windows

**Pull request merged**
