### PR TITLE
Remove apm_user role

### PR DESCRIPTION
**Pull request by cauemarcondes**
Meta issue: https://github.com/elastic/kibana/issues/116760
The `apm_user` role was [marked as deprecated](https://github.com/elastic/elasticsearch/pull/68749) in 7.13 and was supposed to be removed in 8.0.
All mentions of `apm_user` role were finally removed in https://github.com/elastic/kibana/pull/132790 and this PR removes the actual role.

### CODE REVIEW

**Review by n1v0lg — APPROVED** [review]
LGTM

**Comment by n1v0lg** [comment]
@elasticmachine update branch

**Review by n1v0lg — APPROVED** [review]
LGTM take two, pending a successful BWC test suite run 👍

**Comment by n1v0lg** [comment]
Failure unrelated (CrossClusterSearchUnavailableClusterIT > testSkipUnavailableDependsOnSeeds thread leak)

**Comment by n1v0lg** [comment]
@elasticmachine update branch

**Comment by n1v0lg** [comment]
@elasticmachine update branch

**Comment by cauemarcondes** [comment]
@elasticmachine update branch

**Comment by samxbr** [comment]
Friendly reminder that this PR seems to be a breaking change for 9.0, but is missing from the 9.0 release note. We may want to add an entry to the breaking change section of [9.0 release note](https://github.com/elastic/elasticsearch/blob/cf536f894756f25c7ae874b4211a6b00372b39a1/docs/reference/release-notes/9.0.0.asciidoc#L8).

**Pull request merged**
