### PR TITLE
Migrate legacy/v2/component templates away from custom attributes routing

### LINKED ISSUE #82170: Migrate to data tiers routing API updates all templates in a system to not use custom attribute routing
Currently, the migrate to data tiers routing [API](https://www.elastic.co/guide/en/elasticsearch/reference/7.16/ilm-migrate-to-data-tiers.html) only deletes a legacy template (if one is specified). It doesn't inspect the index templates in the system.

However there might still be the case that templates relying on node attributes are installed in the system via a restore of an old snapshot or accidentally. This would conflict with a system that is already using data tiers.

This proposes that the migrate to data tiers API iterates over all the legacy tempates, composable templates, and component templates and removes the occurrences of the `include`, `required`, and `excludes` routing configuration for the configurated node attribute. 

eg. the following template 
```
 "test_timplate": {
   "order": 0,
   "index_patterns": [
     "*"
   ],
   "settings": {
     "index": {
       "routing": {
         "allocation": {
           "require": {
             "data": "hot"
           }
         }
       }, 
       "lifecycle": {
          "name" : "the_index_lifecycle_policy"
        }
     }
   },
   "mappings": {},
   "aliases": {}
 }
```

would be updated to
```
 "test_timplate": {
   "order": 0,
   "index_patterns": [
     "*"
   ],
   "settings": {
     "index": { 
       "lifecycle": {
          "name" : "the_index_lifecycle_policy"
        }
     }
   },
   "mappings": {},
   "aliases": {}
 }
```

### PR DESCRIPTION
**Pull request by andreidan**
This enhances the migrate to data tiers routing API to also iterate over
the existing legacy, composable, and component templates and look if
they define a custom node attribute routing in their settings for either
`index.routing.allocation.require.{nodeAttrName}` or
`index.routing.allocation.include.{nodeAttrName}`. If any does, we
update them to remove all the routings settings for the provided
`nodeAttrName`.

eg. any template with the following setting configuration:
```
"settings": {
  index.routing.allocation.require.data: "warm",
  index.routing.allocation.include.data: "rack1",
  index.routing.allocation.exclude.data: "rack2,rack3"
}
```
will have its settings updated to:
```
"settings": {}
```

Closes #82170

### CODE REVIEW

**Comment by andreidan** [comment]
@elasticmachine update branch

**Comment by andreidan** [comment]
@elasticmachine update branch

**Comment by andreidan** [comment]
@elasticmachine update branch

**Review by dakrone — APPROVED** [review]
LGTM, thanks for doing this Andrei

**Comment by andreidan** [comment]
@elasticmachine run elasticsearch-ci/packaging-tests-windows-sample

**Pull request merged**
