### PR TITLE
Cut remaining pipeline aggregations registerPipelineAggregation

### PR DESCRIPTION
**Pull request by nik9000**
Relates to #17085

### CODE REVIEW

**Comment by nik9000** [comment]
@colings86 these are the last of the aggregations. The next step is to remove the bits I added for the migration marked by NORELEASEs. Then remove the remaining PROTOTYPEs from aggregations.

**Comment by colings86** [comment]
LGTM. Awesome, looks like we are almost done then 😄

**Comment by nik9000** [comment]
> LGTM. Awesome, looks like we are almost done then

Thanks! I'll merge in a bit!

**Comment by nik9000** [comment]
Thanks for reviewing @colings86 !

**Pull request merged**
