### PR TITLE
Change default Java Util Logging format

### PR DESCRIPTION
**Pull request by pgomulka**
Currently Elasticsearch is not setting a JUL configuration, so JUL is defaulting a format to
```
static final String DEFAULT_FORMAT =
            "%1$tb %1$td, %1$tY %1$tl:%1$tM:%1$tS %1$Tp %2$s%n%4$s: %5$s%6$s%n";
```
https://github.com/AdoptOpenJDK/openjdk-jdk9u/blob/master/jdk/src/java.base/share/classes/jdk/internal/logger/SimpleConsoleLogger.java#L404

this means it contains a New Line in the middle. That results in log messages being split and interleaved.
This is also preventing the [filtering messages with MMapDirectory](https://github.com/elastic/elasticsearch/blob/fd854e09850c78d2808d53b8f8dce1f4413aa584/server/src/main/java/org/elasticsearch/common/logging/LogConfigurator.java#L273) in LogConfigurator to work correctly

This commit sets a simple default format `[level][loggerName] message exceptionIfAny\n`

Example of current behaviour:
`        log.info("Using MemorySegmentIndexInput with Java 19; to disable start with -Dorg.apache.lucene.store.MMapDirectory.enableMemorySegments=false");`

will result in (when filtering removed):
```
[2023-06-01T14:32:20,944][WARN ][stderr                   ] [runTask-0] Jun 01, 2023 2:32:20 PM org.apache.lucene.store.MemorySegmentIndexInputProvider <init>
[2023-06-01T14:32:25,641][WARN ][stderr                   ] [runTask-0] INFO: Using MemorySegmentIndexInput with Java 20; to disable start with -Dorg.apache.lucene.store.MMapDirectory.enableMemorySegments=false
```

and with filtering we end up with just single line:
```
[2023-06-01T14:32:20,944][WARN ][stderr                   ] [runTask-0] Jun 01, 2023 2:32:20 PM org.apache.lucene.store.MemorySegmentIndexInputProvider <init>
```

with this change we will get the message fully filtered out or in single line (when filtering disabled):
```
[2023-06-02T11:49:38,172][WARN ][stderr                   ] [runTask-0] [INFO][org.apache.lucene.store.MemorySegmentIndexInputProvider] Using MemorySegmentIndexInput with Java 20; to disable start with -Dorg.apache.lucene.store.MMapDirectory.enableMemorySegments=false
```

### CODE REVIEW

**Comment by pgomulka** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by ChrisHegarty** [comment]
I think that this is good. A few comments:

1. Can you please check the output of the vector message, e.g. "Java vector incubator API enabled; uses preferredBitSize". I want to ensure that we do not inadvertently do something "bad" to it. Just a sanity to check it.

2. Can the filter for stderr in LogConfiguration should be able to be simplified - I added to entries for the vector log message,  we should only need one now, right?   Also, can we make this filter a static final which I overlooked here https://github.com/elastic/elasticsearch/pull/96453#discussion_r1213750716

**Comment by pgomulka** [comment]
> I think that this is good. A few comments:
> 
> Can you please check the output of the vector message, e.g. "Java vector incubator API enabled; uses preferredBitSize". I want to ensure that we do not inadvertently do something "bad" to it. Just a sanity to check it.
I can still see the message 
```
[2023-06-02T15:02:06,887][WARN ][stderr                   ] [yamlRestTest-0] [INFO][org.apache.lucene.util.VectorUtilPanamaProvider] Java vector incubator API enabled; uses preferredBitSize=128
```


> Can the filter for stderr in LogConfiguration be simplified - I added two entries for the vector log message, we should only need one now, right? Also, can we make this filter a static final which I overlooked here https://github.com/elastic/elasticsearch/pull/96453#discussion_r1213750716

on main (with your commit) when I remove the two filters you added I still cannot see the warning with VectorUtilProvider
I am running:
```
 ./gradlew ':modules:lang-painless:yamlRestTest' --tests "org.elasticsearch.painless.LangPainlessClientYamlTestSuiteIT.test {yaml=painless/180_knn_and_binary_dv_fields_api/*}"  -Dtests.rest.cluster=localhost:9200 -Dtests.cluster=localhost:9300 -Dtests.clustername=elasticsearch
```
and a cluster is running with JDK20
perhaps those filters are not needed?

**Comment by pgomulka** [comment]
agree, that https://github.com/elastic/elasticsearch/issues/94613 would be a better choice. Can you leave your notes/thoughts on the #94613? Was exposing jul bridge the only concern?  
 I will happily take that task over and look into it at some point later.

**Comment by rjernst** [comment]
@pgomulka I think this can be closed now that https://github.com/elastic/elasticsearch/pull/96683 is complete?

**Comment by pgomulka** [comment]
closing as https://github.com/elastic/elasticsearch/pull/96683 is merged

**Pull request closed without merging**
