### PR TITLE
Remove unnecessary joda-convert dependency (issue #10290)

### PR DESCRIPTION
**Pull request by marko-asplund**

### CODE REVIEW

**Comment by bleskes** [comment]
thx @marko-asplund . It looks like this was put in on purpose to solve another issue (#4660) . This problem might be better fixed in the shading side of things. Still researching..

**Comment by marko-asplund** [comment]
We're actually building custom ES plugins using Scala and bundling custom code with ES code in one jar. This worked well up-to ES 1.4.4, but because we're using joda-convert there's a naming clash when I tried upgrading to ES 1.5.0. If I build ES 1.5.0 (in ES sandbox) without the joda-convert dependency ES compiles. So, it seems that joda-convert is not required at compile-time. Also,  I don't get any additional test failures when I run the tests. With the ES 1.5.0 jar built this way, I'm also able to build and run our customized ES bundle.

I'm using Scala 2.11.6, Java 8 and sbt 0.13.7.

**Comment by kimchy** [comment]
I mused admit I am confused now :), we added this and shaded it to fix a bug in Scala compiler, and now it complains again and we need to take it out? Won't it cause the break that it was first added to fix in the first place?

**Comment by marko-asplund** [comment]
Just to clarify: The issue I'm seeing is not a Scala compiler error, it's an error with the sbt assembly plugin. The plugin gets confused when classes mentioned in #10290 are available from two different sources). This could be worked around in our sbt build config, but I think including the classes in es.jar will result in classpath / namespace collision issues for other developers when custom plugin code needs to use joda-convert directly or indirectly through a dependency. From the perspective of this issue (though I'm not familiar with issue #4660), I think a good solution would be to place the repackaged joda-convert classes in a different namespace (such as org.elasticsearch).

**Comment by marko-asplund** [comment]
added detailed description on how to reproduce this problem on issue #10290.

**Comment by l15k4** [comment]
Possible fix until this is resolved : 
```scala
      assemblyExcludedJars in assembly := {
        val cp = (fullClasspath in assembly).value
        cp filter {_.data.getName == "joda-convert-1.7.jar"}
      }
```
This is the only way I found to work this around...

**Comment by marko-asplund** [comment]
What's the status with this issue?

Just tried it with the latest version and it still affects ES 1.5.2 preventing us from upgrading.
To re-iterate: this is a regression introduced after ES 1.4.4 and it's reproducible with code found in #10290.

Has someone else been able to reproduce issue #4660? Where can I find instructions or code for reproducing it?

**Comment by fcofdez** [comment]
I'm having the same problem with ES 1.7.1

**Comment by emmekappa** [comment]
Any updates?

**Comment by clintongormley** [comment]
Closing in favour of #12829

**Pull request closed without merging**
