### PR TITLE
Fix sorting agg buckets by doc_count

### PR DESCRIPTION
**Pull request by nik9000**
I broke sorting aggregations by `doc_count` in #51271 by mixing up true
and false. This flips that comparison and adds a few tests to double
check that we don't so this again.

### CODE REVIEW

**Comment by nik9000** [comment]
I'm using the `>non-issue` label for this because it fixes a bug in 7.7.0 that hasn't been released yet. I'm not sure if that is the right label, but it is what I'm doing now.

**Review by not-napoleon — APPROVED** [review]
LGTM

**Comment by nik9000** [comment]
Merged and backported, thanks @not-napoleon !

**Comment by lizozom** [comment]
@nik9000 did the backport go through?

**Comment by nik9000** [comment]
> @nik9000 did the backport go through?

I believe https://github.com/elastic/elasticsearch/commit/9845dbb7d6d426dba717fb1310d18d024b303682 is the commit that backported it to 7.x. So the fix will go out with 7.7.0.

**Pull request merged**
