### PR TITLE
Use merge sort instead of hashing to avoid performance issues with many buckets

### PR DESCRIPTION
**Pull request by iverase**
We made some changes to use hashing to merge buckets for some bucket aggregations. This works well when merging small number of buckets (<100K) but unfortunately hashing performance degrees quickly with size. So if you are merging several million of buckets, the performance can be terrible. This is currently possible in the way we are merging buckets.

Therefore here we propose to use again merge sort, the side effect is we are keeping those buckets in memory so we need other means to reduce memory usage,

### CODE REVIEW

**Comment by iverase** [comment]
@elasticsearchmachine update branch

**Comment by iverase** [comment]
@elasticmachine update branch

**Review by nik9000 — APPROVED** [review]
Code seems fine given tests are happy. Do we have some performance tests to prove its the right way to go? And, better, to show us if we break it?

**Comment by iverase** [comment]
@elasticmachine update branch

**Review by nik9000 — APPROVED** [review]
Tada

**Pull request merged**
