### PR TITLE
REST hl client: cluster health to default to cluster level

### PR DESCRIPTION
**Pull request by javanna**
With #29331 we added support for the cluster health API to the
high-level REST client. The transport client does not support the level
parameter, and it always returns all the info needed for shards level
rendering. We have maintained that behaviour when adding support for
cluster health to the high-level REST client, to ease migration, but the
correct thing to do is to default the high-level REST client to
`cluster` level, which is the same default as when going through the
Elasticsearch REST layer.

### CODE REVIEW

**Comment by javanna** [comment]
This is a breaking change for REST high-level client users, I need to add a note to the migrate guide, just waiting for #31200 to be merged so I can add it to the same file that's being created there.

**Review by nik9000 — APPROVED** [review]

**Comment by nik9000** [comment]
I think this should have a line in the breaking changes docs, right?

**Comment by javanna** [comment]
yes @nik9000 I will add that, I commented above on that, I will add it as soon as I managed to merge #31200 in.

**Comment by nik9000** [comment]
> yes @nik9000 I will add that, I commented above on that, I will add it as soon as I managed to merge #31200 in.

:heart: my fault for not reading everything. More coffee required I think.....

**Pull request merged**
