### PR TITLE
added .fleet-file-data* to kibana_system privileges

### PR DESCRIPTION
**Pull request by juliaElastic**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)? yes
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md)? yes
- If submitting code, have you built your formula locally prior to submission with `gradle check`? yes
- If submitting code, is your pull request against main? Unless there is a good reason otherwise, we prefer pull requests against main and will backport as needed. yes
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)? yes
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

Closes https://github.com/elastic/kibana/issues/167479

Added missing privileges to `kibana_system` to clean up indices [here](https://github.com/elastic/kibana/blob/main/x-pack/plugins/fleet/server/services/setup/clean_old_fleet_indices.tsx#L11-L15).

### CODE REVIEW

**Comment by juliaElastic** [comment]
Tried to fix the formatting, but couldn't run spotlessApply, any idea how to fix it? Running in VS Code, on a new Mac M2.

```
juliabardi@Julias-MacBook-Pro elasticsearch % ./gradlew :x-pack:plugin:fleet:spotlessApply
Starting a Gradle Daemon, 2 incompatible Daemons could not be reused, use --status for details

FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.For more details on the daemon, please refer to https://docs.gradle.org/8.3/userguide/gradle_daemon.html in the Gradle documentation.
Process command line: /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java -XX:+HeapDumpOnOutOfMemoryError -Xss2m --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED -Dfile.encoding=UTF-8 -Duser.country=NL -Duser.language=en -Duser.variant -cp /Users/juliabardi/.gradle/wrapper/dists/gradle-8.3-all/6en3ugtfdg5xnpx44z4qbwgas/gradle-8.3/lib/gradle-launcher-8.3.jar -javaagent:/Users/juliabardi/.gradle/wrapper/dists/gradle-8.3-all/6en3ugtfdg5xnpx44z4qbwgas/gradle-8.3/lib/agents/gradle-instrumentation-agent-8.3.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 8.3
Please read the following process output to find out more:
-----------------------
Unrecognized option: --add-exports
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
```

**Comment by williamrandolph** [comment]
@juliaElastic What version of Java are you using? I think `--add-exports` was introduced in Java 9, but the new Mac might have shipped with an old Java.

**Comment by juliaElastic** [comment]
Thank you, I deleted the old java and recreated the symlink for the new one, the issue is fixed.

**Review by jeramysoucy — APPROVED** [review]
Approving, as `.fleet*` indices are Kibana-owned system indices.

**Pull request merged**
