### PR TITLE
Don't Circuit Break Shard Started/Failed Requests

### PR DESCRIPTION
**Pull request by boicehuang**
## Problem

Shard Started/Failed requests are likely to trip the circuit breaker under heavy load
which might lead to unfortunate side-effects in nodes under pressure. 

1. Shards that should have been removed and rerouted, are not processed and not in the right state.
2. The index requests to the shards will be stuck and wait for a retry. It will result in more pressure on memory, making the situation worse.
3.  [updateFailedShardsCache](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/indices/cluster/IndicesClusterStateService.java#L209) can find out the previously failed shard had not been removed and resending shard failure. But it depends on cluster state updates and if there is no cluster state update task or the master is under heavy pressure, the previously failed shard  would never be handled

## Solution

Turn off the circuit breaker for shard failed and started. It will make shards recover faster and reduce the pressure from disaster at the same time.

### CODE REVIEW

**Comment by DaveCTurner** [comment]
These requests are only handled on the elected master and I would expect you see them tripping the real memory circuit breaker when the master's heap exceeds 95% capacity. With this change we would ignoring the heap pressure and continue to accept more work, so that the master would struggle on until it completely fails with an OOM. That doesn't sound like it'll solve anything.

Can you explain more clearly why your master was so close to going OOM? Can you share a heap dump? If there's a bug that leads to excessive heap usage on the master then we should work to address it rather than doing this, but we'll need to understand the source of the heap pressure before we can do that.

**Comment by boicehuang** [comment]
@DaveCTurner  In my case, master is also a data node, processing write and query requests. If there are some heavy aggregations or heavy bulk operations at the same time, it may consume a lot of memory.  Using dedicated masters can help, but the risk still exists.

**Comment by DaveCTurner** [comment]
> In my case, master is also a data node, processing write and query requests.

I think the behaviour you describe is to be expected if using mixed master/data nodes in a cluster under heavy load. We strongly recommend using dedicated masters in a situation like this.

> Using dedicated masters can help, but the risk still exists.

That's my question: how does the risk still exist? We should be working to address high heap usage rather than just ignoring it as proposed here.

**Comment by DaveCTurner** [comment]
> If there are some heavy aggregations or heavy bulk operations at the same time, it may consume a lot of memory.

I don't think indexing can be the explanation, that's limited to at most 15% of the total heap size. I opened https://github.com/elastic/elasticsearch/issues/76145 to discuss whether we can push back on aggs earlier on mixed master/data nodes to avoid getting into this situation.

**Comment by boicehuang** [comment]
@DaveCTurner  Very appreciated.  In my case, dedicated masters are usually built for large-scale clusters, but not for the small or medium cluster to reduce costs, which put them at risk. I hope we can optimize this situation.

**Comment by DaveCTurner** [comment]
:+1: it would help enormously for you to share more details, ideally a heap dump, so we can see exactly what we're missing.

**Comment by DaveCTurner** [comment]
No further details were forthcoming so I am closing this PR.

**Pull request closed without merging**
