### PR TITLE
Reduce memory usage in SimpleClusterStateIT#testLargeClusterStatePublishing

### LINKED ISSUE #73050: [CI] SimpleClusterStateIT has long GCs in 7.13 and below
**Build scan**: 
https://gradle-enterprise.elastic.co/s/npxmfxjlxapby/tests/failed

**Repro line**:
```
./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.cluster.SimpleClusterStateIT.testLargeClusterStatePublishing" \
   -Dtests.seed=24365114AC556D09 -Dtests.security.manager=true -Dtests.locale=fr \
   -Dtests.timezone=America/Managua -Druntime.java=8 -Dtests.fips.enabled=true
```

**Reproduces locally?**: Yes

**Applicable branches**: 7.13 and below

**Failure history**:
First occurred January 3rd 2021, 03:02:56.
https://build-stats.elastic.co/goto/554daa67f31c18a514a0e61ce2ac2530
image

**Failure excerpt**:
```
[2021-05-13T03:20:28,282][INFO ][o.e.c.m.MetadataCreateIndexService] [node_s2] [baz] creating index, cause [auto(bulk api)], templates [random_index_template], shards [1]/[1]
[2021-05-13T03:20:28,470][INFO ][o.e.c.m.MetadataMappingService] [node_s2] [baz/54oXPOAFQwWf9Pa1pc8Mgw] create_mapping [baz]
[2021-05-13T03:20:28,557][INFO ][o.e.c.r.a.AllocationService] [node_s2] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[baz][0]]]).
[2021-05-13T03:20:33,199][INFO ][o.e.c.SimpleClusterStateIT] [testLargeClusterStatePublishing] number of fields [24603], estimated bytes [246027]
[2021-05-13T03:20:34,762][INFO ][o.e.m.j.JvmGcMonitorService] [node_s4] [gc][15] overhead, spent [270ms] collecting in the last [1s]
[2021-05-13T03:20:35,188][INFO ][o.e.c.m.MetadataCreateIndexService] [node_s2] [test] creating index, cause [api], templates [random_index_template], shards [2]/[0]
[2021-05-13T03:20:36,408][WARN ][o.e.t.n.MockNioTransport ] [node_s0] Slow execution on network thread [643 milliseconds]
java.lang.RuntimeException: Slow exception on network thread
	at org.elasticsearch.transport.nio.MockNioTransport$TransportThreadWatchdog.maybeLogElapsedTime(MockNioTransport.java:396) ~[framework-7.12.2-SNAPSHOT.jar:7.12.2-SNAPSHOT]
	at org.elasticsearch.transport.nio.MockNioTransport$TransportThreadWatchdog.unregister(MockNioTransport.java:388) ~[framework-7.12.2-SNAPSHOT.jar:7.12.2-SNAPSHOT]
	at org.elasticsearch.transport.nio.TestEventHandler.acceptChannel(TestEventHandler.java:43) ~[framework-7.12.2-SNAPSHOT.jar:7.12.2-SNAPSHOT]
	at org.elasticsearch.nio.NioSelector.processKey(NioSelector.java:217) ~[elasticsearch-nio-7.12.2-SNAPSHOT.jar:7.12.2-SNAPSHOT]
	at org.elasticsearch.nio.NioSelector.singleLoop(NioSelector.java:163) ~[elasticsearch-nio-7.12.2-SNAPSHOT.jar:7.12.2-SNAPSHOT]
	at org.elasticsearch.nio.NioSelector.runLoop(NioSelector.java:120) ~[elasticsearch-nio-7.12.2-SNAPSHOT.jar:7.12.2-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
[2021-05-13T03:20:36,522][WARN ][o.e.m.j.JvmGcMonitorService] [node_s1] [gc][17] overhead, spent [750ms] collecting in the last [1s]
[2021-05-13T03:20:36,522][WARN ][o.e.m.j.JvmGcMonitorService] [node_s0] [gc][17] overhead, spent [750ms] collecting in the last [1s]
[2021-05-13T03:20:36,523][WARN ][o.e.m.j.JvmGcMonitorService] [node_s2] [gc][17] overhead, spent [750ms] collecting in the last [1s]
[2021-05-13T03:20:36,649][WARN ][o.e.m.j.JvmGcMonitorService] [node_s3] [gc][17] overhead, spent [802ms] collecting in the last [1s]
[2021-05-13T03:20:36,822][WARN ][o.e.m.j.JvmGcMonitorService] [node_s4] [gc][17] overhead, spent [840ms] collecting in the last [1s]
[2021-05-13T03:20:37,523][INFO ][o.e.m.j.JvmGcMonitorService] [node_s0] [gc][18] overhead, spent [256ms] collecting in the last [1s]
[2021-05-13T03:20:37,524][INFO ][o.e.m.j.JvmGcMonitorService] [node_s2] [gc][18] overhead, spent [256ms] collecting in the last [1s]
[2021-05-13T03:20:37,560][INFO ][o.e.m.j.JvmGcMonitorService] [node_s1] [gc][18] overhead, spent [291ms] collecting in the last [1s]
[2021-05-13T03:20:37,686][INFO ][o.e.m.j.JvmGcMonitorService] [node_s3] [gc][18] overhead, spent [274ms] collecting in the last [1s]
[2021-05-13T03:20:38,600][WARN ][o.e.m.j.JvmGcMonitorService] [node_s1] [gc][19] overhead, spent [925ms] collecting in the last [1s]
[2021-05-13T03:20:38,600][WARN ][o.e.m.j.JvmGcMonitorService] [node_s0] [gc][19] overhead, spent [960ms] collecting in the last [1s]
```

### PR DESCRIPTION
**Pull request by fcofdez**
In order to produce a large cluster state this test creates 1000s
of text fields mappings. The in memory representation for
these mappings can consume all the heap causing OOMs. This commit
changes the mapping type for a boolean that's more lightweight.

Closes #73050

### CODE REVIEW

**Comment by fcofdez** [comment]
I captured a couple of heapdumps to measure the difference running the test with a cluster state size of `~256kb`

### Text fields
Screenshot 2021-06-04 at 16 27 26

### Boolean fields
Screenshot 2021-06-04 at 16 29 52

**Comment by fcofdez** [comment]
@elasticmachine update branch

**Review by original-brownbear — APPROVED** [review]
LGTM

**Comment by fcofdez** [comment]
@elasticmachine update branch

**Comment by fcofdez** [comment]
Thanks Armin!

**Pull request merged**
