### PR TITLE
Add min_doc_count option to geo grid bucket aggregations

### PR DESCRIPTION
**Pull request by yutaka-nakano**
This PR introduces `min_doc_count` option to geo grid aggregations.  
`min_doc_count` will help us to mask privacy and to exclude outliers.

Relates to: #50481

### CODE REVIEW

**Comment by talevy** [comment]
hi @yutaka-nakano, I apologize for the delayed response here. we've been out due to the holidays.

I question the value of min-docs as a way to obfuscate the privacy of the actual individual data points when these could be returned in the `hits` of the search response.

Another option for filtering out these buckets is to do so using the [bucket selector pipeline aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-pipeline-bucket-selector-aggregation.html). have you explored this option as a way to filter out buckets with only some minimum count?

**Comment by yutaka-nakano** [comment]
Hi @talevy, thank you for the response.
We use Kibana coordinate map for geo analytics dashboard. Kibana does not seem to support filtering buckets out based on response, and I couldn't find the way to apply pipeline aggregations on the coordinate map.
We can easily filter out buckets if geogird aggregations have min_doc_count option.
default_kibana_geohash_grid_agg
geohash_grid_with_min_doc_count

**Comment by talevy** [comment]
I see, thank you @yutaka-nakano. We discussed this in our team meeting and thought it would be best handled by either using the bucket-select pipeline aggregation, or done on the client. Do you feel a solution for this can exist directly in Kibana?

**Comment by yutaka-nakano** [comment]
@taleby
If Kibana maps support pipeline aggregation, it would be best solution. Filtering bucket at client(browser) does not seem to be so good because the user can see filtered bucket in browser developer tools.

**Comment by talevy** [comment]
> If Kibana maps support pipeline aggregation, it would be best solution

@yutaka-nakano, I agree. I've opened https://github.com/elastic/kibana/issues/55520 against the Kibana repository to see if we can work on a solution on the visualization side since I think it would be best done there.

Let me know what you think and please leave a comment on the kibana issue further explaining your feature request if you think my description is lacking!

**Comment by talevy** [comment]
since there as not been a comment in a while, I'm going to go ahead and close this. feel free to re-open if you disagree and would like to continue the conversation.

Will track this feature in the kibana issue here: https://github.com/elastic/kibana/issues/55520

**Pull request closed without merging**
