### PR TITLE
Renaming inference rescorer feature flag to learn to rank.

### PR DESCRIPTION
**Pull request by afoucret**
Changing the name of the feature flag (inference_rescorer -> learn_to_rank) will make the doc more comprehensive.

### CODE REVIEW

**Review by benwtrent — APPROVED** [review]
I think all code references to `inference_rescore` should be updated. There are some yaml test names that should be updated as well. 

`x-pack/plugin/ml/qa/ml-with-security/build.gradle` has an old reference to block the test:

```
    'ml/inference_rescore/Test rescore with missing model',
```

Could you remove that trailing reference as well? Other than that, this is PR is 👍

**Comment by joshdevins** [comment]
Small nitpick. For this and all the code in general, we should use the verbiage: "learning to rank" or just "ltr", as opposed to "learn to rank". That's typically how it's spelled.

Regarding this name, do we want to change it really to `learning_to_rank` and not `ltr_rescorer`? The latter is a bit clearer about where it's to be used.

**Comment by benwtrent** [comment]
@joshdevins & @afoucret 

I am fine with the way it is or `ltr` or whatever.

I personally don't care about the name at all, especially since the goal is eventual removal ;)

**Comment by joshdevins** [comment]
The flag I also don't care much about, but I do want to get the naming of "public and unchangeable" things right 😄

**Comment by afoucret** [comment]
@elasticsearchmachine run buildkite/docs-build-pr

**Comment by afoucret** [comment]
@elasticsearchmachine update branch

**Comment by afoucret** [comment]
@elasticsearchmachine run elasticsearch-ci/docs

**Comment by afoucret** [comment]
@elasticsearchmachine run elasticsearch-ci/docs

**Pull request merged**
