### PR TITLE
Fix failure in IndexingIT::testIndexing

### LINKED ISSUE #72012: [CI] IndexingIT fails with legacy index templates deprecation warning
**Build scan**:

https://gradle-enterprise.elastic.co/s/7tdbwdl5an6ic

**Repro line**:

```shell
./gradlew ':qa:rolling-upgrade:v7.13.0#oldClusterTest' -Dtests.class="org.elasticsearch.upgrades.IndexingIT" -Dtests.method="testIndexing" -Dtests.seed=EAD03C763012343E -Dtests.bwc=true -Dtests.locale=en -Dtests.timezone=Africa/Lagos -Druntime.java=8
```

**Reproduces locally?**:

Yes

**Applicable branches**:

`7.x`

**Failure history**:

🤷 

**Failure excerpt**:

```
org.elasticsearch.upgrades.IndexingIT > testIndexing FAILED	
    org.elasticsearch.client.WarningFailureException: method [PUT], host [http://[::1]:46381], URI [/_template/prevent-bwc-deprecation-template], status line [HTTP/1.1 200 OK]	
    Warnings: [Legacy index templates are deprecated and will be removed completely in a future version. Please use composable templates instead.]	
    {"acknowledged":true}	
        at __randomizedtesting.SeedInfo.seed([EAD03C763012343E:E0A737F166777B5]:0)	
        at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:322)	
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296)	
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270)	
        at org.elasticsearch.upgrades.IndexingIT.testIndexing(IndexingIT.java:88)
```

### PR DESCRIPTION
**Pull request by danhermann**
Fixes #72012

### CODE REVIEW

**Comment by danhermann** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Review by martijnvg — APPROVED** [review]
👍

**Comment by danhermann** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by danhermann** [comment]
@elasticmachine update branch

**Pull request merged**
