### PR TITLE
Fix CoordinatorTests.testUnresponsiveLeaderDetectedEventually

### LINKED ISSUE #63918: CoordinatorTests.testUnresponsiveLeaderDetectedEventually reproducible failure:
This fail in one PR but I seem to be able to reproduce it in master.

**Build scan**:

https://gradle-enterprise.elastic.co/s/d5pmmsn5fz3bi

**Repro line**:

```
 ./gradlew ':server:test' --tests "org.elasticsearch.cluster.coordination.CoordinatorTests.testUnresponsiveLeaderDetectedEventually" -Dtests.seed=5C32928A3DFC7F15 -Dtests.security.manager=true -Dtests.locale=bg-BG -Dtests.timezone=Mexico/General -Druntime.java=11

```
**Reproduces locally?**:

yes

**Applicable branches**:

Only tried on master

**Failure history**:

Seems not to have fail in a long time.

**Failure excerpt**:

```
  1> [2020-10-20T04:56:15,000][INFO ][o.e.c.c.CoordinatorTests ] [testUnresponsiveLeaderDetectedEventually] after test
  2> REPRODUCE WITH: ./gradlew ':server:test' --tests "org.elasticsearch.cluster.coordination.CoordinatorTests.testUnresponsiveLeaderDetectedEventually" -Dtests.seed=5C32928A3DFC7F15 -Dtests.security.manager=true -Dtests.locale=bg-BG -Dtests.timezone=Mexico/General -Druntime.java=11
  2> java.lang.AssertionError: node1 has applied its state 
    Expected: <10L>
         but: was <9L>
        at __randomizedtesting.SeedInfo.seed([5C32928A3DFC7F15:265B95CAD8EEBC04]:0)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.elasticsearch.cluster.coordination.AbstractCoordinatorTestCase$Cluster.stabilise(AbstractCoordinatorTestCase.java:537)
        at org.elasticsearch.cluster.coordination.CoordinatorTests.testUnresponsiveLeaderDetectedEventually(CoordinatorTests.java:532)
  2> NOTE: leaving temporary files on disk at: /Users/ivera/forks/elasticsearch-fork/server/build/testrun/test/temp/org.elasticsearch.cluster.coordination.CoordinatorTests_5C32928A3DFC7F15-003
  2> NOTE: test params are: codec=Asserting(Lucene87): {}, docValues:{}, maxPointsInLeafNode=984, maxMBSortInHeap=7.724307660680699, sim=Asserting(RandomSimilarity(queryNorm=false): {}), locale=bg-BG, timezone=Mexico/General
  2> NOTE: Mac OS X 10.15.6 x86_64/N/A 11.0.8 (64-bit)/cpus=12,threads=1,free=506481344,total=536870912
  2> NOTE: All tests run in this JVM: [CoordinatorTests]
```

### PR DESCRIPTION
**Pull request by fcofdez**
Take into account messy scenarios of 5 node clusters elections
where multiple nodes can trigger an election concurrently, meaning
that it takes longer to stabilize the cluster and elect a leader.

Fixes #63918

### CODE REVIEW

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Review by DaveCTurner — CHANGES_REQUESTED** [review]
Hmm actually I think we need another `defaultMillis(PUBLISH_TIMEOUT_SETTING)` too -- the failing elections all try and publish to the unresponsive leader and must therefore wait for a timeout.

**Comment by fcofdez** [comment]
I'm not sure if we need the additional publish timeout as those publications go through as expected (since they have quorum) or fail due to term bumps. Am I missing something?

**Comment by DaveCTurner** [comment]
Yes, until the master is properly established each publication will go to the unresponsive node and therefore wait for the publish timeout before proceeding. That node is only removed from the cluster once the elections have settled down.

In the failing test, we blackhole `node4` at `433835372ms`, and then attempt the following publications:

```
[433867822ms][+    32450ms][node4][o.e.c.c.C.CoordinatorPublication          ] publishing PublishRequest{term=3, version=6, state=cluster uuid: H5lUTwAAQACNnOGK_____w [committed: true]
[433868232ms][+    32860ms][node3][o.e.c.c.C.CoordinatorPublication          ] publishing PublishRequest{term=5, version=6, state=cluster uuid: H5lUTwAAQACNnOGK_____w [committed: true]
[433897846ms][+    62474ms][node4][o.e.c.c.C.CoordinatorPublication          ] publication ended unsuccessfully: Publication{term=3, version=6}
[433898290ms][+    62918ms][node3][o.e.c.c.C.CoordinatorPublication          ] publication ended successfully: Publication{term=5, version=6}
[433898645ms][+    63273ms][node3][o.e.c.c.C.CoordinatorPublication          ] publishing PublishRequest{term=8, version=7, state=cluster uuid: H5lUTwAAQACNnOGK_____w [committed: true]
[433898735ms][+    63363ms][node3][o.e.c.c.C.CoordinatorPublication          ] publication ended unsuccessfully: Publication{term=8, version=7}
[433899213ms][+    63841ms][node1][o.e.c.c.C.CoordinatorPublication          ] publishing PublishRequest{term=10, version=8, state=cluster uuid: H5lUTwAAQACNnOGK_____w [committed: true]
[433929341ms][+    93969ms][node1][o.e.c.c.C.CoordinatorPublication          ] publication ended successfully: Publication{term=10, version=8}
[433929686ms][+    94314ms][node1][o.e.c.c.C.CoordinatorPublication          ] publishing PublishRequest{term=13, version=9, state=cluster uuid: H5lUTwAAQACNnOGK_____w [committed: true]
[433959731ms][+   124359ms][node1][o.e.c.c.C.CoordinatorPublication          ] publication ended successfully: Publication{term=13, version=9}
[433959731ms][+   124359ms][node1][o.e.c.c.C.CoordinatorPublication          ] publishing PublishRequest{term=13, version=10, state=cluster uuid: H5lUTwAAQACNnOGK_____w [committed: true]
[433989746ms][+   154374ms][node1][o.e.c.c.C.CoordinatorPublication          ] publication ended successfully: Publication{term=13, version=10}
[433989826ms][+   154454ms][node1][o.e.c.c.C.CoordinatorPublication          ] publishing PublishRequest{term=13, version=11, state=cluster uuid: H5lUTwAAQACNnOGK_____w [committed: true]
[433989975ms][+   154603ms][node1][o.e.c.c.C.CoordinatorPublication          ] publication ended successfully: Publication{term=13, version=11}
[433990058ms][+   154686ms][node1][o.e.c.c.C.CoordinatorPublication          ] publishing PublishRequest{term=13, version=12, state=cluster uuid: H5lUTwAAQACNnOGK_____w [committed: true]
[433990366ms][+   154994ms][node1][o.e.c.c.C.CoordinatorPublication          ] publication ended successfully: Publication{term=13, version=12}
```

(second column is times relative to the blackhole time)

Until version 11, all publications go to `node4` and therefore take ≥30 seconds because of hitting the publish timeout. In particular, this includes the clashing publication of version 6 which we're wanting to account for here.

**Comment by fcofdez** [comment]
Thanks for the explanation @DaveCTurner ! I was missing that publications wait up until the timeout to succeed even if they got a Quorum. I've updated the PR.

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Pull request merged**
