### PR TITLE
Add Pes Plugin to the misc page

### PR DESCRIPTION
**Pull request by ozlerhakan**
I do not know normally whether this section is the right place or not, please let me know.

Here is the pes plugin's GitHub site :https://github.com/kodcu/pes

### CODE REVIEW

**Comment by javanna** [comment]
HI @ozlerhakan thaks for your PR. Trying to find the best place for your project. I believe it is not what we'd call a plugin, hence I would lean towards adding it to the community page. How about adding it [here](https://github.com/elastic/elasticsearch/blob/master/docs/community/misc.asciidoc)?

**Comment by ozlerhakan** [comment]
Hi @javanna , I actually do not call it as a plug-in either, your suggestion seems fine by me :+1:

**Comment by javanna** [comment]
cool, do you feel like updating your PR then?

**Comment by ozlerhakan** [comment]
Yep, I will add it to that page instead of the plugin

**Comment by clintongormley** [comment]
thanks @ozlerhakan - merged

**Comment by ozlerhakan** [comment]
You're welcome @clintongormley

**Pull request closed without merging**
