### PR TITLE
Fix dup word in ShardRouting hashcode method.

### PR DESCRIPTION
**Pull request by howardhuanghua**
Fix comment issue in ShardRouting.java.

### CODE REVIEW

**Review by jrodewig — APPROVED** [review]
LGTM. Thanks @howardhuanghua.

**Comment by jrodewig** [comment]
@elasticmachine test this please

**Comment by howardhuanghua** [comment]
Thanks @jrodewig , the latest master has been updated.

**Comment by jrodewig** [comment]
@elasticmachine test this please

**Comment by jrodewig** [comment]
There is an unrelated issue with our tests causing CI to fail. I'll rerun the tests once those get resolved.

**Comment by jrodewig** [comment]
@elasticmachine test this please

**Pull request merged**
