### PR TITLE
show a full ingest example in the index page

### PR DESCRIPTION
**Pull request by weizijun**
show a full ingest example in the index page, to let user fast understand ingest node.
when I first read ingest guide. I don't understand pipeline, processor. the demo run with pipeline_id not found. If the index page give a full example, user meybe easilyunderstand  ingest.

### CODE REVIEW

**Comment by weizijun** [comment]
@martijnvg can you help to deal this pr?

**Comment by martijnvg** [comment]
@elasticmachine test this please

**Comment by martijnvg** [comment]
@weizijun Thanks for improving the docs! This will be merged shortly.

**Comment by weizijun** [comment]
@martijnvg Thanks you!

**Pull request merged**
