### PR TITLE
Ignore null value for range field (#27845)

### LINKED ISSUE #27845: Failure inserting document with explicit null in range field
in 5.6.4 the last PUT statement fails, although it is equivalent to the previous insertions

`DELETE model_range_index`

`PUT model_range_index
{
  "mappings": {
    "my_type": {
      "properties": {
        "my_int": {
          "type": "integer"
        },
        "my_int_range": {
          "type": "integer_range"
        }
      }
    }
  }
}`

`PUT model_range_index/my_type/1
{
  "my_int": 7
}`

`PUT model_range_index/my_type/2
{
  "my_int": 7,
  "my_int_range": []
}`

`PUT model_range_index/my_type/3
{
  "my_int": 7,
  "my_int_range": null
}`

This is the error response:
```
{
  "error": {
    "root_cause": [
      {
        "type": "mapper_parsing_exception",
        "reason": "error parsing field [my_int_range], expected an object but got my_int_range"
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "failed to parse [my_int_range]",
    "caused_by": {
      "type": "mapper_parsing_exception",
      "reason": "error parsing field [my_int_range], expected an object but got my_int_range"
    }
  },
  "status": 400
}
```

### PR DESCRIPTION
**Pull request by liketic**
Closes #27845

### CODE REVIEW

**Comment by cbuescher** [comment]
@elasticmachine test this please

**Review by cbuescher — CHANGES_REQUESTED** [review]
@liketic thanks a lot, the fix looks good to me at first glance. However, I'd prefer to add unit test to the rest test you added since they are much more controllable. I looked at RangeFieldMapperTests and the tests `doTestNullValue()` seem to be a good place to extend to add the case where there is no json object at all following the field name. Could you take a look and try to extend that test instead of adding another case to the rest tests? Let me know if you have questions.

**Comment by liketic** [comment]
Thanks @cbuescher

**Review by cbuescher — APPROVED** [review]
@liketic thanks for adding the test, LGTM.

**Comment by cbuescher** [comment]
@elasticmachine test this please

**Comment by cbuescher** [comment]
@liketic thanks, I merged this to master and the 6.x branches, so it will be included in 6.2.

I took the liberty to add a slightly more informative commit message, hope you don't mind.
It would be great if you could add a slightly more descriptive initial comment in future PRs,
since those will end up as commit messages. Ideally the comment includes a more verbose 
message explaining the reasoning behind the change. You can find some more thorough 
examples this [here](https://chris.beams.io/posts/git-commit/). This helps us reviewing PRs 
and later when scanning older commits in the log.

Thanks again for all your contributions, they are greatly appreciated.

**Comment by liketic** [comment]
Thanks @cbuescher . It's my miss. I will take more attention on the description. Thanks again.

**Pull request merged**
