### PR TITLE
Remove all HLRC tests

### PR DESCRIPTION
**Pull request by dakrone**
We are in the process of removing the High Level Rest Client from the ES codebase. This starts by
removing all the HLRC tests themselves so that the other usages can be removed incrementally.

Relates to #83423

### CODE REVIEW

**Comment by dakrone** [comment]
@elasticmachine update branch

**Comment by dakrone** [comment]
@elasticmachine run elasticsearch-ci/packaging-tests-unix-sample

**Review by martijnvg — APPROVED** [review]
LGTM, awesome line delete count!

**Comment by mark-vieira** [comment]
I've run into some gotchas backporting stuff due to these tests still existing in older branches. Since the HLRC is "gone" in 8.0+ should we go ahead and backport this as well?

**Pull request merged**
