### PR TITLE
Add pid file to Environment

### PR DESCRIPTION
**Pull request by tlrx**
This commit adds the path of the PID file to the Environment. It also add it to the Security Manager since the PID file is deleted by a shutdown hook when the JVM is exited.

### CODE REVIEW

**Comment by tlrx** [comment]
@rmuir Can you have a look please? I spotted it when testing #10725. Thanks

**Comment by rmuir** [comment]
Hey this is great. is there anyway we coudl add a unit test in SecurityTests? (just create a fake pid file in tests temp dir like the other tests and assert it has permissions)

**Comment by tlrx** [comment]
@rmuir I updated the code after your last comment

**Comment by rmuir** [comment]
Looks good. When pushing, can we add a small javadoc for the Environment.pidFile() that mentions it returns null if no pid file is configured? Other paths do not return null, but here callers need to check.

**Pull request merged**
