### PR TITLE
Metricbeat monitoring collection suggest to enable local exporters

### PR DESCRIPTION
**Pull request by philippkahr**
ES Version: 7.14.1

**Steps to reproduce**
* Use this docker-compose.yml
<details> <summary> docker-compose.yml </summary>

```
version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - elastic
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic
  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.1
    container_name: kibana
    networks:
      - elastic
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: '["http://es01:9200","http://es02:9200","http://es03:9200"]'
networks:
  elastic:
    driver: bridge
```

</details>

1. Start it with `docker-compose up -d --force-recreate` (this forces docker to recreate the container, since we don't map any data volume into the container, we always start with a fresh install).
2. It is a cluster without security enabled.
3. browse to localhost:5601 and you should see Kibana coming alive after a few seconds.

**There are multiple things going on.**

1. It seems that xpack.monitoring.collection.enabled should be false by default.
2. It seems unnecessary apply the cluster settings.
3. I can start a default fresh cluster without security and activate the metricbeat module `xpack.elasticsearch` and it just works, as shown in the screencast `Metricbeat works out of the box`.

https://user-images.githubusercontent.com/12175559/132470617-f20c9b7d-95c7-4e6c-b466-23cdab04132f.mov

**Combining everything from above together:**

1. We enable the xpack.monitoring exporters. <-- not needed
2. In the last step, we disable the local _legacy_ exporters again. <-- not needed

### CODE REVIEW

**Comment by debadair** [comment]
@elasticmachine retest this please

**Comment by thbkrkr** [comment]
I see the same thing. I have the impression that Monitoring works out of the box without configuring `xpack.monitoring.*` settings.

Historically the reason step 1 in the ["Monitoring with Metricbeat" docs](https://www.elastic.co/guide/en/elasticsearch/reference/7.16/configuring-metricbeat.html) ask users to set the `xpack.monitoring.collection.enabled` flag to `true` in ES is so the `.monitoring-*` index templates get installed before any monitoring data is sent to ES. The monitoring exporters (local or http) are in charge of creating index templates on the appropriate monitoring cluster (local or remote). It's because of this coupling between setting -> exporters -> index template creation that the setting needs to be enabled even if Metricbeat is going to collect monitoring data and index it into `.monitoring-*` indices.
Starting 8.0, monitoring templates are automatically installed at plugin initialization (https://github.com/elastic/elasticsearch/pull/78350).

I wonder if this explanation is still valid in 7.x or if we've been wrong since a while. There is something not clear for me. I see that the `.monitoring-*` index templates are created with `xpack.monitoring.collection.enabled` set to `false`. I test with a 7.1.0 Elasticsearch cluster deployed by ECK. Only setting `xpack.monitoring.enabled` to `false` seems to disable the creation of templates (up to version 7.7).

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: test
spec:
  version: 7.1.0
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
      #xpack.monitoring.enabled: false
      xpack.monitoring.collection.enabled: false
      xpack.monitoring.elasticsearch.collection.enabled: false
```

```sh
> eckurl test '/_cat/templates/.monitoring-*'        
.monitoring-logstash [.monitoring-logstash-7-*] 0 7000199
.monitoring-beats    [.monitoring-beats-7-*]    0 7000199
.monitoring-kibana   [.monitoring-kibana-7-*]   0 7000199
.monitoring-es       [.monitoring-es-7-*]       0 7000199
.monitoring-alerts-7 [.monitoring-alerts-7]     0 7000199
```

Or is there something else that is not installed for Monitoring without the setting?

**Comment by jakelandis** [comment]
I think @philippkahr and @thbkrkr are correct that these additional settings are not needed. I also did a quick test and they are installed by default. They are installed by default due to how ES creates a "dummy" exporter when one is not defined.  You can prevent the implicit dummy exporter by creating an explicit dummy exporter and explicitly disabling it. For reasons that are unclear ECK/Cloud did just (but no longer does). 

I am pretty certain we can remove these settings from the doc.  I will work towards to getting this PR merged.

**Comment by philippkahr** [comment]
@jakelandis can we get some movement on this PR? How could I help?

**Review by debadair — APPROVED** [review]
This slipped by. LGTM with the verified changes. @jakelandis

**Review by jbaiera — APPROVED** [review]
LGTM

**Comment by abdonpijpelink** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.6|[](https://github.com/elastic/elasticsearch/pull/91843)|
|✅|8.5|[](https://github.com/elastic/elasticsearch/pull/91844)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
