### PR TITLE
More deterministic ESQL CSV tests

### PR DESCRIPTION
**Pull request by luigidellaquila**
More on https://github.com/elastic/elasticsearch/pull/99086

Some tests did not have a completely deterministic behavior, because queries did not have an explicit ordering.
This PR makes the behavior deterministic by adding a proper SORT

### CODE REVIEW

**Comment by luigidellaquila** [comment]
@elasticmachine run 
elasticsearch-ci/packaging-tests-unix-sample

**Comment by luigidellaquila** [comment]
@elasticmachine update branch

**Review by alex-spies — APPROVED** [review]
LGTM!

Only, highly optional nitpick: Maybe we could add comments to explain why the specific sort fields were chosen. I can see someone in the future (like myself) adapting a test case (or using them as base for a new test) and being surprised that it fails.

**Review by costin — APPROVED** [review]
LGTM

**Comment by luigidellaquila** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by luigidellaquila** [comment]
@elasticmachine run elasticsearch-ci/part-2

**Pull request merged**
