### PR TITLE
Upgrade to Netty 4.1.8

### PR DESCRIPTION
**Pull request by Tim-Brooks**
This commit upgrades the Netty dependency to version 4.1.8.Final.

### CODE REVIEW

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by jasontedor** [comment]
I'm assuming that handling the permissions changes we get from this release will be done in a follow-up? To be clear, I'm fine with that.

**Comment by tbrooks8** [comment]
Yeah. I did an "upgrade only" commit so that it can be cherry-picked onto 5.x.

**Comment by jasontedor** [comment]
> Yeah. I did an "upgrade only" commit so that it can be cherry-picked onto 5.x.

+1

**Pull request merged**
