### PR TITLE
Fixing the custom object serialization bug in diffable utils.

### PR DESCRIPTION
**Pull request by backslasht**
While serializing custom objects, the length of the list is computed after
filtering out the unsupported objects but while writing objects the filter
is not applied thus resulting in writing unsupported objects which will fail
to deserialize by the receiever. Adding the condition to filter out unsupported
custom objects.

### CODE REVIEW

**Comment by ywelsch** [comment]
@backslasht can you add tests as well?

**Comment by backslasht** [comment]
@ywelsch added a unit test to validate the custom object serialization.

**Comment by ywelsch** [comment]
@elasticmachine test this please

**Comment by ywelsch** [comment]
@elasticmachine retest this please

**Review by ywelsch — APPROVED** [review]
LGTM

**Pull request merged**
