### PR TITLE
Remove flavor field from Distribution packaging tests (#70132) (7.x backport)

### PR DESCRIPTION
**Pull request by breskeby**
backporting #70132 to 7.x branch

### CODE REVIEW

**Comment by breskeby** [comment]
@elasticmachine test this please

**Comment by breskeby** [comment]
@elasticmachine test this

**Comment by breskeby** [comment]
@elasticmachine test this please

**Review by pugnascotia — APPROVED** [review]

**Comment by breskeby** [comment]
@elasticmachine test this please

**Comment by breskeby** [comment]
@elasticmachine test this please

**Comment by breskeby** [comment]
@elasticmachine run elasticsearch-ci/packaging-unix

**Comment by breskeby** [comment]
@elasticmachine run elasticsearch-ci/packaging-unix

**Comment by breskeby** [comment]
@elasticmachine run elasticsearch-ci/packaging-windows

**Pull request merged**
