### PR TITLE
Scripting: Convert CompiledTemplate to a ScriptContext

### PR DESCRIPTION
**Pull request by rjernst**
This commit creates TemplateScript and associated classes so that
templates no longer need a special ScriptService.compileTemplate method.
The execute() method is equivalent to the old run() method.

relates #20426

### CODE REVIEW

**Comment by talevy** [comment]
With this change, would it make sense to revisit `ingest/InternalTemplateService.java`.
I can investigate how much of a performance difference there is from that extra regex/is_mustache check. If it is not significant, may make sense to remove. What do you think? cc @martijnvg

**Comment by rjernst** [comment]
@talevy yes InternalTemplateService should go and I'm happy to do that as a followup.

**Comment by talevy** [comment]
@rjernst I can do it

**Review by jdconrad — APPROVED** [review]
LGTM

**Pull request merged**
