### PR TITLE
Add node priority to LLRC

### PR DESCRIPTION
**Pull request by alexeydubinin**
Hi!
 
Please review implementation of this feature https://github.com/elastic/elasticsearch/issues/48717 
We already use it inside hh.ru (prioritize nodes inside same datacenter).

Feel free to ask any questions.
Thank you.

### CODE REVIEW

**Comment by alexeydubinin** [comment]
Signed a Contributor Agreement.

**Comment by swallez** [comment]
Thanks @alexeydubinin, this is an interesting feature. I'm a bit worried however about the computational cost, as the node priority strategy is run on every request (just as the node selector). There's quite a bit of list copying and shuffling in there, and on large clusters and busy applications this may lead to some non negligible overhead.

Something that could be worth considering is:
* merging node selection and prioritization in a single interface. We would need however to keep the current `NodeSelector` for backwards compatibility purposes (it could be implemented as a single-group priority list)
* have this new interface receive an immutable list of nodes rather than a mutable copy of the current node list, so that it can memoize its result and have a very fast happy path if the provided node list hasn't changed.

Out of curiosity, can you tell us how many groups you build in your application? Is this just two groups (i.e. the one you really want and everything else) or do you have something more fine-grained like local availability zone / region / other regions?

That being said, although very valuable, this PR doesn't exactly answer #48717 which is about _per-request_ prioritisation. @jbaiera can you tell us your feedback on this?

**Comment by alexeydubinin** [comment]
@swallez Thanks for detailed reply. Yes, there are many optimizations possible, i will try to implement them. 

> Out of curiosity, can you tell us how many groups you build in your application?

We have three datacenters with two elastic nodes in each. So each client works with two groups: local(2 elastic nodes) and remote(4 elastic nodes).

**Comment by jbaiera** [comment]
Agreed on the not solving #48717 entirely. The root of the issue there is that there may be a single client shared by multiple tasks, and each task may have its own node prioritization. While prioritizing nodes based on their attributes likely has valuable uses for a client wide node selector, I think it might make more sense if we interrogate the selector's usage a bit more. 

Agreed on the performance concerns as well: Perhaps priority groups can be calculated when the current list of nodes change (either when sniffing completes or an update to the node list). The problem with this though is that it is inherently at odds with the need to manage multiple priorities across different requests.

The furthest I had ever brain stormed on the issue was allowing to provide a custom node selector for each request, remove the node ordering invariants on the node selectors, and modify the shuffling logic to allow using pre-sorted node lists from the selectors. That second and third part has been a point of contention though, as they can very easily break the client's ability to round robin requests through the cluster when node prioritization is not a current goal.

**Comment by alexeydubinin** [comment]
@swallez @jbaiera please, review some optimizations i made in last commit.

> merging node selection and prioritization in a single interface. We would need however to keep the current NodeSelector for backwards compatibility purposes (it could be implemented as a single-group priority list)

Current implementation receives mutable list (called selectedLivingNodes), so it can be used for selection and prioritization.

> have this new interface receive an immutable list of nodes rather than a mutable copy of the current node list, so that it can memoize its result and have a very fast happy path if the provided node list hasn't changed.

Unfortunately we can't memoize result because we test nodes for liveness and create new initial livingNodes list on each request.

> The furthest I had ever brain stormed on the issue was allowing to provide a custom node selector for each request, remove the node ordering invariants on the node selectors, and modify the shuffling logic to allow using pre-sorted node lists from the selectors.

Interesting feature. If i understand your correctly we can implement it using current NodeSelector design and some related ThreadLocal logic.

**Comment by jbaiera** [comment]
@alexeydubinin Heya, just checking in. We haven't heard from you in a while so we're going to close this PR for now. If you find you have time to return to it please feel free to reopen it and we can pick it up again!

**Pull request closed without merging**
