### PR TITLE
Some Cleanup in o.e.gateway Package

### PR DESCRIPTION
**Pull request by original-brownbear**
* Removing obvious dead code
* Removing redundant listener interface

### CODE REVIEW

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/1

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Comment by DaveCTurner** [comment]
As a followup, I think `AllocateDangledResponse` can be easily `Writeable`ified and it doesn't look like it needs that `ack` field at all.

**Comment by original-brownbear** [comment]
thanks @DaveCTurner !

**Pull request merged**
