### PR TITLE
Fixing HistoryActionConditionTests for async watcher history writes

### LINKED ISSUE #102070: [CI] HistoryActionConditionTests testActionConditionWithFailures failing
Failed on a PR branch but not one which touched anything relevant to this failure. Also failing in CI occasionally.

**Build scan:**
https://gradle-enterprise.elastic.co/s/crj3se3oy3r6a/tests/:x-pack:plugin:watcher:internalClusterTest/org.elasticsearch.xpack.watcher.history.HistoryActionConditionTests/testActionConditionWithFailures
**Reproduction line:**
```
./gradlew ':x-pack:plugin:watcher:internalClusterTest' --tests "org.elasticsearch.xpack.watcher.history.HistoryActionConditionTests.testActionConditionWithFailures" -Dtests.seed=B79730F66090F9DC -Dtests.locale=nl -Dtests.timezone=Asia/Yekaterinburg -Druntime.java=21
```

**Applicable branches:**
main

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.watcher.history.HistoryActionConditionTests&tests.test=testActionConditionWithFailures

**Failure excerpt:**
```
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0

  at __randomizedtesting.SeedInfo.seed([B79730F66090F9DC:420C8B4F31B8064]:0)
  at org.elasticsearch.search.SearchHits.getAt(SearchHits.java:134)
  at org.elasticsearch.xpack.watcher.history.HistoryActionConditionTests.testActionConditionWithFailures(HistoryActionConditionTests.java:188)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  at java.lang.reflect.Method.invoke(Method.java:580)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1583)

```

### PR DESCRIPTION
**Pull request by masseyke**
This test fails occasionally (twice in the last 4 weeks). From what I can tell, this is another symptom of watcher history being written asynchronously. See #95643 for the first attempt at a fix. I assume what is going wrong now is that the history is available from the perspective of one node we query, but when we query another node for that history it is not available yet. This change moves the logic that reads the response into the same assertBusy block as the logic that has validated that we have some hits in the response, so we're using the same response that we have validated is good.
Closes #102070

### CODE REVIEW

**Review by DaveCTurner — COMMENTED** [review]
This makes the test a little weaker - it will retry until it sees a search hit that matches all our assertions, rather than stopping the loop as soon as it gets a hit and _then_ checking the hit is what we want.

I'd suggest instead having an `AtomicReference<SearchResponse>` so you can capture it within the `assertBusy()` loop and then check its properties without.

**Comment by masseyke** [comment]
> This makes the test a little weaker - it will retry until it sees a search hit that matches all our assertions, rather than stopping the loop as soon as it gets a hit and _then_ checking the hit is what we want.
> 
> I'd suggest instead having an `AtomicReference<SearchResponse>` so you can capture it within the `assertBusy()` loop and then check its properties without.

I thought about doing that, but thought it would make the test a little bit harder to read with no value added. I see what you're saying though.

**Comment by DaveCTurner** [comment]
IMO this is a common-enough pattern that we should have a utility for it:

```
diff --git a/test/framework/src/main/java/org/elasticsearch/test/ESTestCase.java b/test/framework/src/main/java/org/elasticsearch/test/ESTestCase.java
index 5589e1b9428..e9e95d08352 100644
--- a/test/framework/src/main/java/org/elasticsearch/test/ESTestCase.java
+++ b/test/framework/src/main/java/org/elasticsearch/test/ESTestCase.java
@@ -45,6 +45,7 @@ import org.elasticsearch.bootstrap.BootstrapForTesting;
 import org.elasticsearch.client.internal.Requests;
 import org.elasticsearch.cluster.ClusterModule;
 import org.elasticsearch.cluster.metadata.IndexMetadata;
+import org.elasticsearch.common.CheckedSupplier;
 import org.elasticsearch.common.UUIDs;
 import org.elasticsearch.common.bytes.BytesArray;
 import org.elasticsearch.common.bytes.BytesReference;
@@ -1192,6 +1193,23 @@ public abstract class ESTestCase extends LuceneTestCase {
      * Runs the code block for the provided interval, waiting for no assertions to trip.
      */
     public static void assertBusy(CheckedRunnable<Exception> codeBlock, long maxWaitTime, TimeUnit unit) throws Exception {
+        assertBusyAndReturn(() -> {
+            codeBlock.run();
+            return null;
+        }, maxWaitTime, unit);
+    }
+
+    /**
+     * Runs the code block for the provided interval, waiting for no assertions to trip.
+     */
+    public static <T> T assertBusyAndReturn(CheckedSupplier<T, Exception> codeBlock) throws Exception {
+        return assertBusyAndReturn(codeBlock, 10, TimeUnit.SECONDS);
+    }
+
+    /**
+     * Runs the code block for the provided interval, waiting for no assertions to trip.
+     */
+    public static <T> T assertBusyAndReturn(CheckedSupplier<T, Exception> codeBlock, long maxWaitTime, TimeUnit unit) throws Exception {
         long maxTimeInMillis = TimeUnit.MILLISECONDS.convert(maxWaitTime, unit);
         // In case you've forgotten your high-school studies, log10(x) / log10(y) == log y(x)
         long iterations = Math.max(Math.round(Math.log10(maxTimeInMillis) / Math.log10(2)), 1);
@@ -1200,8 +1218,7 @@ public abstract class ESTestCase extends LuceneTestCase {
         List<AssertionError> failures = new ArrayList<>();
         for (int i = 0; i < iterations; i++) {
             try {
-                codeBlock.run();
-                return;
+                return codeBlock.get();
             } catch (AssertionError e) {
                 failures.add(e);
             }
@@ -1212,7 +1229,7 @@ public abstract class ESTestCase extends LuceneTestCase {
         timeInMillis = maxTimeInMillis - sum;
         Thread.sleep(Math.max(timeInMillis, 0));
         try {
-            codeBlock.run();
+            return codeBlock.get();
         } catch (AssertionError e) {
             for (AssertionError failure : failures) {
                 e.addSuppressed(failure);
```

**Comment by masseyke** [comment]
I'm also trying to understand if these `response.decRef()` calls actually do anything in this test. I don't think that they do for this response class (which will simplify things when I pull the logic back out of the assertBusy).

**Comment by DaveCTurner** [comment]
They don't _yet_ but they're part of a big old refactoring that will require every `SearchResponse` instance to be released properly.

**Comment by masseyke** [comment]
> They don't _yet_ but they're part of a big old refactoring that will require every `SearchResponse` instance to be released properly.

Ha I will put back in the code I just deleted then!

**Review by mattc58 — APPROVED** [review]
+1 LGTM

**Pull request merged**
