### PR TITLE
Deprecate X-Pack centric watcher endpoints

### PR DESCRIPTION
**Pull request by hub-cap**
This commit is part of our plan to deprecate and ultimately remove the use of _xpack in the REST APIs.

Relates #35958

### CODE REVIEW

**Review by jasontedor — CHANGES_REQUESTED** [review]
The endpoint can not be `/watcher`, that is not a reserved name. It needs to be `/_watcher` so that it can not possibly conflict with existing indices that users might have today.

**Comment by hub-cap** [comment]
oh my, thank you for that clarification @jasontedor

**Comment by hub-cap** [comment]
@jasontedor updated, as well as reverted any changes i made to the transport layer.

**Review by jasontedor — CHANGES_REQUESTED** [review]
I am missing where the existing endpoints are deprecated?

**Comment by hub-cap** [comment]
Because I am an idiot and I was trying to do this before finishing other work I should have finished first, and did not pay attention in the process... Let me properly do this and then Ill ping you. Im sorry for causing this many re-reviews on what should've been an easy PR.

**Comment by hub-cap** [comment]
@elasticmachine run the gradle build tests 1

**Comment by hub-cap** [comment]
This depends on #36269 merging before the tests will go green.

**Review by jasontedor — APPROVED** [review]
LGTM now.

**Comment by hub-cap** [comment]
@elasticmachine run the gradle build tests 1

**Comment by hub-cap** [comment]
@elasticmachine run the gradle build tests 1

**Comment by hub-cap** [comment]
@elasticmachine run the gradle build tests 2

**Comment by hub-cap** [comment]
@elasticmachine run the gradle build tests 2

**Pull request merged**
