### PR TITLE
Minor refactor of MultiValueMode removing apply and reduce

### PR DESCRIPTION
**Pull request by jdconrad**
Simplification of MultiValueMode by removing the apply and reduce
methods for each mode.  This creates a more consistent environment for
sorting methods since all sorting must now go through select methods.
This allows for better error handling and better encapsulation for
sorting fields with multiple values.

Note that apply and reduce had inconsistencies in the code base
prior to this change since different calls were assuming that the
accumulator for apply was the first input versus the second input.

Also added is an UnsortedNumericDoubleValues interface to allow
customized values to be input into the different sort modes.  This 
prevents the need for apply/reduce outside of MultiValueMode.

### CODE REVIEW

**Comment by jpountz** [comment]
This looks great.

One minor concern I have is whether the introduction of `UnsortedNumericDoubleValues` is worth it or if we should just reuse the `SortedNumericDoubleValues` api instead and sort on the fly. But I don't feel too strongly about it so if you like the `UnsortedNumericDoubleValues` approach better, feel free to ignore.

**Comment by jdconrad** [comment]
I thought about sorting on the fly because it certainly seems cleaner to me as well; however, sorting on the fly could potentially eat up a lot of memory if there's a large number of values in a field, so it didn't seem worth it to me.  I also avoided allowing sorting on inner doc select methods with median because you'd have to sort on *all* of the inner document values which could take a large amount of memory as well.

**Comment by jpountz** [comment]
OK. Thanks for the explanation. LGTM

**Comment by jdconrad** [comment]
@jpountz Thanks for the review!

**Pull request merged**
