### PR TITLE
Add support for API keys to access Elasticsearch

### LINKED ISSUE #34383: Long lived api keys/tokens
The security codebase already supports the use of access tokens for
interactive access. These tokens are based on the OAuth2 spec; there is
a short-lived access token and a refresh token with a lifetime of 24 hours.
These tokens are not suitable for Hadoop jobs or recurring scheduled tasks.

Hadoop jobs typically require a token that may need to be refreshed but
the token needs to remain the same after refresh; our current tokens
always generate a new access and refresh token upon refresh. Another
pattern of Hadoop jobs is that once they are complete the tokens are
not invalidated but instead rely on a expiration time of something like
a week.

The security tokens are not a fit for recurring/scheduled jobs as they
can only be refreshed for 24 hours. If the system that would refresh the
token is down for greater than 24 hours, which could be possible over a
weekend or holiday, the jobs would require updating to function again.

After discussion, we've settled upon adding long lived tokens that would
be akin to API tokens. The properties of these tokens are as follows:

* Tokens will store the authentication information of the user that
created them
* By default, tokens have no expiration. A cluster level setting will
be available to specify a maximum lifetime
* When creating a token, a maximum lifetime can be specified for cases
where the token is expected to stop working after a certain amount of
time

In terms of APIs, we will be adding:

Create a token with optional expiration, which is a `TimeValue`.

```
POST /_security/token
{
  "expiration": "7d"
}
```

List security tokens. Optionally restrict by username and/or realm.

```
GET /_security/token
{
  "username": "john.doe",
  "realm": "ldap1"
}
```

List specific token

```
GET /_security/token/<token>
```

Remove a token.

```
DELETE /_security/token/<token>
```

In order to use these tokens, they will be passed over HTTP using the
`Authorization` header. The value must be prefixed with `Bearer `.

In order to use this token, security must take the value and find the 
document with this id. If the document does not exist or the search fails,
the token may not be used. Once security has retrieved a document with
this ID, it must make sure to verify the token has not expired.

Invalidation or a removal of a token should remove the token document
from the security index.

Tokens must store enough information to re-build authentication and
support determining if the token has expired.

Future considerations:

* The ability to limit the scope of a token
* keep track of last used time

### PR DESCRIPTION
**Pull request by bizybot**
X-Pack security supports built-in authentication service `token-service` that allows
access tokens to be used to access Elasticsearch without using Basic authentication.
The tokens are generated by `token-service` based on OAuth2 spec. The access token
is a short-lived token (defaults to 20m) and refresh token with a lifetime of 24 hours,
making them unsuitable for long-lived or recurring tasks where the system might go
offline thereby failing refresh of tokens.

This commit introduces a built-in authentication service `api-key-service` that
adds support for long-lived tokens aka API keys to access Elasticsearch. The `api-key-service`
is consulted after `token-service` in the authentication chain. By default, if TLS is enabled
then `api-key-service` is also enabled. The service can be disabled using the configuration
setting.

The API keys:-
- by default do not have an expiration but expiration can be configured
   where the API keys need to be expired after a certain amount of time.
- when generated will keep authentication information of the user that
   generated them.
- can be defined with a role describing the privileges for accessing
   Elasticsearch and will be limited by the role of the user that generated
   them
- can be invalidated via invalidation API
- information can be retrieved via a get API
- that have been expired or invalidated will be retained for 1 week before
   being deleted. The expired API keys remover task handles this.

Following are the API key management APIs:-
1. Create API Key - `PUT/POST /_security/api_key`
2. Get API key(s) - `GET /_security/api_key`
3. Invalidate API Key(s) `DELETE /_security/api_key`

The API keys can be used to access Elasticsearch using `Authorization`
header, where the auth scheme is `ApiKey` and the credentials, is the 
base64 encoding of API key Id and API key separated by a colon.
Example:-
```
curl -H "Authorization: ApiKey YXBpLWtleS1pZDphcGkta2V5" http://localhost:9200/_cluster/health
```

Closes #34383

### CODE REVIEW

**Review by tvernum — COMMENTED** [review]
I haven't reviewed enough of the API Key PRs to be able to say whether this is ready or not, but I have no objections.

**Review by jaymode — APPROVED** [review]
LGTM

**Review by jkakavas — APPROVED** [review]
I didn't go through the whole changeset here but I've reviewed enough of the individual PRs so LGTM

**Comment by karmi** [comment]
I was recently adding support for the API Key authentication to the Go client (https://github.com/elastic/go-elasticsearch/commit/3b68c0f89287c1bd3dd03d810217de06d7616c9c), and I think there's a small, but nice usability optimization: it would help if the API would return also the base64-encoded value for the key, so the users (or the client) doesn't have to perform the encoding themselves.

**Comment by albertzaharovits** [comment]
@karmi I see in the ES code that the key (`api_key` field in the response to `POST` `_security/api_key`) **is** base64 url encoded. Are we talking about the same thing?

**Comment by karmi** [comment]
@albertzaharovits , what I mean is the _output_ (ie. result) of the "Create API Key" API:

```bash
docker run \
  --env "discovery.type=single-node" \
  --env "xpack.security.enabled=true" \
  --env "xpack.security.authc.api_key.enabled=true" \
  --env "xpack.license.self_generated.type=trial" \
  --env "ELASTIC_PASSWORD=elastic" \
  --publish 9200:9200 \
  --rm -it \
  docker.elastic.co/elasticsearch/elasticsearch:8.0.0-SNAPSHOT

curl -s -X POST \
        -H 'Content-Type: application/json' \
        http://elastic:elastic@localhost:9200/_security/api_key -d \
        '{"name":"test-key", "role_descriptors":{}}' \
| jq '.'
```

Output:
```json
{
  "id": "ZquG-WsBx1ePiPP47oig",
  "name": "test-key",
  "api_key": "ipRxILiWT7udFhKgb69O4Q"
}

```

Ie. the API returns the `id` and `api_key` value, but not the base64-encoded version which has to be passed in the `Authorization` header. Is it more clear?

**Comment by albertzaharovits** [comment]
Thank you @karmi .
I understand that in this case you have to concatenate `id` with `:` and `api_key` , encode base64, and then append to `ApiKey ` to get the value of the `Authorization` header. And you are asking why isn't there a value in the response that I can put in the header as is.

I was under the impression that `ApiKey ` concatenated with `$api_key` was the way to build the credentials in this case. But I am wrong.

@bizybot Do you think it would be feasible to achieve what @karmi is asking for? Either by adding another field in the response or make ES not require the `id` to be concatenated to the `api_key`, and only use the `api_key`?

**Comment by karmi** [comment]
> And you are asking why isn't there a value in the response that I can put in the header as is.

Yes, exactly — with the goal of increasing the usability. If the response contains the fully-encoded value, the user can just copy&paste that value into the client in a single step.

> Either by adding another field in the response (...)

Yes, that's what I had in mind — adding a property like `value`, `encoded`, `credentials` (not sure about the naming in this case...) in addition to existing properties.

**Comment by karmi** [comment]
> We can create a discuss issue and take it forward if everyone agrees, wdyt?

Yes, please! Thanks for catching it, @bizybot !

**Pull request merged**
