### PR TITLE
Update analysis.asciidoc

### PR DESCRIPTION
**Pull request by edjw**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by danielmitterdorfer** [comment]
Thank you for your PR @edjw! Can you please [sign the contributor license agreement](https://www.elastic.co/contributor-agreement) so we can merge your change?

**Review by cbuescher — APPROVED** [review]
Change looks good, just waiting for CLA before merging. Thanks @edjw for spotting this.

**Review by cbuescher — CHANGES_REQUESTED** [review]
@edjw sorry, actually, I have to correct myself. "lazi" is a stemmed version of "lazy", so the output is correct like it currently is. You can check this using:

```
POST _analyze
{
  "analyzer": "english", 
  "text": ["The QUICK brown foxes jumped over the lazy dog!"]
}
```

I think this doesn't need correction in the docs, so I hope you don't mind if we close this.

**Comment by edjw** [comment]
Think it makes sense to close and explain why it is the way it is.

(By the way, I went to sign the contributor license agreement twice and couldn't because I block third party cookies. And if I'm honest, I wasn't motivated enough to go in and make an exception for these domains just for a typo PR. Just a bit of feedback on the CLA stuff.)

**Comment by cbuescher** [comment]
@edjw no problem, I can understand you don't want to sign the CLA just for a tiny change like this.

> I'm sure you have your reasons for asking people to sign the agreement but it was a bit more friction in the process than I'm used to.)

Yes, we require a CLA also just for documentation changes. I'd be curious to learn what the process looks like for other open source projects (maybe with a commercial entity in the back) when there is less perceived friction. Do you have any examples? 

Thanks for pointing this out anyway, I will close the issue.

**Pull request closed without merging**
