### PR TITLE
Explain disk headroom settings more in docs

### PR DESCRIPTION
**Pull request by kingherc**
Relates to #81406

### CODE REVIEW

**Comment by kingherc** [comment]
Reminder for reviews

**Review by repantis — APPROVED** [review]
Thanks a lot for this clarification, @kingherc, and apologies for the delayed review.

**Comment by kingherc** [comment]
Thanks! I'll wait a couple of days for any additional feedback from @henningandersen , else I think I can merge this with one approval.

**Comment by kingherc** [comment]
Merging. Can do another PR if there are future comments.

**Pull request merged**
