### PR TITLE
Minor enhancements to compatible test tranformations task

### PR DESCRIPTION
**Pull request by jakelandis**
This commit adds support to transform the value of the `value` field in the `close_to` assertion. 
For example, with the following configuration:
```
tasks.named("yamlRestCompatTestTransform").configure({ task ->
   task.replaceValueInCloseTo("get.fields._routing", 9.5, "my test name")
})
```
will transform the following in "my test name" from:
```
 close_to:   { get.fields._routing: { value: 5.1, error: 0.00001 } }
```
to
```
 close_to:   { get.fields._routing: { value: 9.5, error: 0.00001 } }
```

This commit also adds supports to specify a specific test name to apply the `replaceIsTrue` task configuration. 
Before this commit, you could replace the values in the `is_true`, but it only supported doing so for all tests subject to the configuration.

### CODE REVIEW

**Review by mark-vieira — APPROVED** [review]
LGTM. Thanks, Jake.

**Comment by jakelandis** [comment]
The build failed due https://gradle-enterprise.elastic.co/s/qnbwvbdxn57be [1]. I added https://github.com/elastic/elasticsearch/pull/112840/commits/85e1a1ba7d618ddd83f772c59f2cfb3f421070af to this PR to attempt to fix it. I assume that this PR is failing since it is the first change to the build-internal files since the Java version bump and it can't use it's cached version for the examples (which were not version bumped) and is running into issues. If this test passes, I will pull that commit to it's own PR before I merge this one. 

[1]
```
* What went wrong:
Could not determine the dependencies of task ':security-authorization-engine:compileJava'.
> Could not resolve all dependencies for configuration ':security-authorization-engine:compileClasspath'.
   > Could not resolve org.elasticsearch.plugin:x-pack-core:9.0.0-SNAPSHOT.
     Required by:
         project :security-authorization-engine
      > The consumer was configured to find a library for use during compile-time, compatible with Java 17, preferably in the form of class files, preferably optimized for standard JVMs, and its dependencies declared externally. There are several available matching variants of project :elasticsearch-pull-request:x-pack:plugin:core
        The only attribute distinguishing these variants is 'artifactType'. Add this attribute to the consumer's configuration to resolve the ambiguity:
          - Value: 'directory' selects variant: 'explodedBundleZip'th
          - Value: 'features-metadata-json' selects variant: 'featuresMetadata'
          - Value: 'zip' selects variant: 'zip'
```

**Comment by mark-vieira** [comment]
That failure can be safely ignored. It won't pass until we have a successful unified snapshot build on `main` after the version bump.

**Comment by jakelandis** [comment]
> That failure can be safely ignored. It won't pass until we have a successful unified snapshot build on main after the version bump.

OK .. i think this PR and https://github.com/elastic/elasticsearch/pull/112843 will need to wait till we get that unified snapshot. I can't get a clean build here until we bump the example version, and can't get a clean build with the examples version bumped (https://github.com/elastic/elasticsearch/pull/112843) until we get the unified snapshot.

**Comment by mark-vieira** [comment]
This issue only effects the example plugin builds, which only run periodically or on PRs that touch build-tools. I think if this PR has value we can merge it now.

**Comment by jakelandis** [comment]
@elasticmachine merge upstream

**Pull request merged**
