### PR TITLE
Don't Ping on Handshake Connection

### PR DESCRIPTION
**Pull request by original-brownbear**
* It does not make sense to run pings on the handshake connection
   * Set the ping interval to `-1` to deactivate pings on it

### CODE REVIEW

**Review by DaveCTurner — COMMENTED** [review]
The only other place we use `buildSingleChannelProfile(TransportRequestOptions.Type, TimeValue, TimeValue)` is in `UnicastZenPing`. I think this should be adjusted similarly (it's used in `Zen1IT` today) and we can then remove that overload entirely. Also `buildSingleChannelProfile(TransportRequestOptions.Type, boolean)` is unused.

**Comment by DaveCTurner** [comment]
> it's used in `Zen1IT` today

Oh wait, that's gone in `master`. It still exists in `7.x`.

**Comment by original-brownbear** [comment]
@DaveCTurner alright, adjusted the other spot as well and removed the unused overloads :)

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Pull request merged**
