### PR TITLE
Add extra checkstyle checks in an IDE

### PR DESCRIPTION
**Pull request by pugnascotia**
Now that Checkstyle can be made useful in an IDE, add extra rules only when checking in the IDE so that a contributor is given extra help when editing files, without having the checkstyle task spam the console when running gradle.

Apart from the `BooleanNegation` rule below, the new rules have the `warning` severity level. The new Javadoc rules reflect the guidelines in `CONTRIBUTING.md` that we've had for some time.

   * I upgraded Checkstyle, so now it interprets the config file in the same was as the IntelliJ plugin. That means that I could move the `LineLength` rule up a level and remove its special handling in the `:configureIdeCheckstyle` task
   * I added the `SuppressWarningsFilter` and `SuppressWarningsHolder` rules so that the `@SuppressWarnings` annotation can be used to silence Checkstyle checks. We shouldn't typically need this, but it seemed like a useful thing to configure. In contrast to the suppressions file, this approach makes the suppression obvious.
   * I changed the `:configureIdeCheckstyle` task to pull in rules from `checkstyle_ide_fragment.xml` and merged them into the generated config. The rules are as follows:
      * `BooleanNegation` - a task defined using `DescendantToken` that detects cases of `!` being used negate a boolean expression. This ought to be in the main config, but at present we have a number of violations in the source
      * `MissingJavadocMethod` - requires that public methods are documented. I set `minLineCount` to 2 so that the rule doesn't trigger on simple methods.
      * `MissingJavadocPackage` - require Javadoc in `package-info.java`
      * `MissingJavadocType` - require types to be documented
      * `JavadocMethod` - require params and return type to be documeted

### CODE REVIEW

**Comment by pugnascotia** [comment]
@elasticmachine update branch

**Review by mark-vieira — APPROVED** [review]
We should work towards enforcing `== false`. This is almost like tribal knowledge and we enforce it inconsistently. It's a very strait forward rule, and we could update instances of it pretty easily.

Also related to that, IntelliJ itself has a conflicting inspection. Basically, it highlights instances of `== false` and indicates those could be simplified. Would be nice if we could configure that inspection to be disabled for folks somehow.

**Comment by pugnascotia** [comment]
Ack on updating the code proactively. It affects hundreds of files though, so we'll need to do that proactively.

I can see that the IntelliJ inspection is already disabled in `.idea/inspectionProfiles/Project_Default.xml` but I can't remember if IntelliJ picks that up or not when you import the project.

**Comment by pugnascotia** [comment]
Backported to `7.x` in 770d9cd0591

**Comment by pugnascotia** [comment]
I started working towards enforcing `== false` in #67817.

**Pull request merged**
