### PR TITLE
Only fetch mapping updates when necessary

### PR DESCRIPTION
**Pull request by jasontedor**
Today we fetch the mapping from the leader and apply it as a mapping update whenever the index metadata version on the leader changes. Yet, the index metadata can change for many reasons other than a mapping update (e.g., settings updates, adding an alias, or a replica being promoted to a primary among many other reasons). This commit builds on the addition of a mapping version to the index metadata to only fetch mapping updates when the mapping version increases. This reduces the number of these fetches and application of mappings on the follower to the bare minimum.

Relates #33147

### CODE REVIEW

**Comment by jasontedor** [comment]
@elasticmachine run the oss docs tests

**Comment by dnhatn** [comment]
@jasontedor I am fixing the oss doc issue.

**Review by dnhatn — APPROVED** [review]
LGTM.

**Comment by jasontedor** [comment]
Okay, thanks @dnhatn.

**Review by martijnvg — APPROVED** [review]
LGTM

**Pull request merged**
