### PR TITLE
Add YAML REST tests for filters bucket agg

### PR DESCRIPTION
**Pull request by polyfractal**
REST tests for filters (plural) bucket.

Should I keep PR'ing these or just push them directly?  They seem pretty straightforward so far...

Related to #26220

### CODE REVIEW

**Review by tlrx — APPROVED** [review]
LGTM

**Comment by tlrx** [comment]
> Should I keep PR'ing these or just push them directly? They seem pretty straightforward so far...

I think that it's important to have reviews. Maybe you could group multiple tests in a single PR?

Also, CI failed for this PR

**Comment by polyfractal** [comment]
Thanks @tlrx!  I'll keep putting these up for PRs then...just wanted to make sure it wasn't irritating people :)

(Sorry for delay, was out training all last week)

**Comment by polyfractal** [comment]
retest this please

**Comment by polyfractal** [comment]
Looks to be a completely unrelated test failure.  

retest this please

**Pull request merged**
