### PR TITLE
[WIP] [DOCS] Update EQL docs for default event type and timestamp fields

### PR DESCRIPTION
**Pull request by jrodewig**
Updates several references to the default event type (`event_type`) and
timestamp (`timestamp`) fields for the EQL search API throughout the EQL
docs.

Also updates EQL example log data to better align with the default fields.

Depends on #53004.

### CODE REVIEW

**Comment by jrodewig** [comment]
CI is expected to fail until #53004 is merged.

**Comment by jrodewig** [comment]
@elasticmachine update branch

**Comment by costin** [comment]
@jrodewig Please wait a bit - there are discussions on changing event_type to event.category and it's likely the same will happen for `@timestamp`.

**Comment by jrodewig** [comment]
Sounds good. I'll keep this PR as a draft until #52941 is sorted out. Thanks @costin.

**Comment by jrodewig** [comment]
Closed due to #53073. Will open another PR related to that one.

**Pull request closed without merging**
