### PR TITLE
Improve allocation-disabling instructions

### PR DESCRIPTION
**Pull request by DaveCTurner**
Clarify the “one minute” in the instructions to disable the shard allocation
when doing maintenance to say that it is configurable.

Add a note about making sure that no rebalancing occurs until the maintenance
is complete.

Relates #19739.

### CODE REVIEW

**Review by ywelsch — COMMENTED** [review]
I'm not sure if the extra paragraph solves an actual problem. There's a tradeoff here between the extra information and keeping the upgrade procedure not too lengthy. I'm not aware of anyone having ever changed the `allow_rebalance` setting, so I'm not sure if it's a good idea to add this to the docs. Let's get one more reviewer on this.

**Comment by DaveCTurner** [comment]
@elasticmachine please run sample packaging tests

**Comment by DaveCTurner** [comment]
(looks like the sample packaging tests timed out - retrying as I don't think I made any infinite loops here)

**Comment by DaveCTurner** [comment]
Pinging @elastic/es-distributed since @elasticmachine seems to be asleep. Anyone else on the team have opinions about the second paragraph?

**Comment by bleskes** [comment]
I tend to agree that we can drop the para about rebalancing. Most people won't change the default which is what we recommend. Otherwise LGTM.

**Comment by tomsommer** [comment]
If you don't change `allow_rebalance` during an upgrade, you can end up with a very unbalanced cluster which leads to poor performance and thus a slow/impossible upgrade. The default for `allow_rebalance` makes no sense to me and IMO it makes even more sense to change it during an upgrade.

My two cents.

**Comment by DaveCTurner** [comment]
Ok, I removed the extra para.

@tomsommer I'm interested to hear more about the effect you describe, but not on this thread. Please could you ask a question about this behaviour on https://discuss.elastic.co and link to it here. Details we'd need include the versions you were upgrading from/to, what kind of upgrade (rolling vs full-cluster-restart), and any logs you have from around this time.

**Review by bleskes — APPROVED** [review]

**Comment by DaveCTurner** [comment]
@elasticmachine test this please

**Review by ywelsch — APPROVED** [review]

**Pull request merged**
