### PR TITLE
Fix integer overflow in native scalar quantizer

### PR DESCRIPTION
**Pull request by jimczi**
To prevent integer overflow on large segments, offsets in memory segments should be computed as longs. 
Although I'm not sure about the proper testing for this, I'm opening the fix early to raise awareness.

### CODE REVIEW

**Review by ChrisHegarty — APPROVED** [review]
Thanks @jimczi LGTM

**Comment by ChrisHegarty** [comment]
@elasticmachine update branch

**Comment by jimczi** [comment]
@elasticmachine run elasticsearch-ci

**Comment by jimczi** [comment]
@elasticmachine  run elasticsearch-ci/part-2-arm

**Comment by ChrisHegarty** [comment]
@elasticmachine run elasticsearch-ci/part-2-arm

**Comment by ChrisHegarty** [comment]
@elasticmachine update branch

**Pull request merged**
