### PR TITLE
Update field-mapping.asciidoc  Correcting a spelling mistake

### PR DESCRIPTION
**Pull request by LeonardGC**
Correcting a spelling mistake

### CODE REVIEW

**Comment by clintongormley** [comment]
Hi @LeonardGC 

Thanks for the PR.  Please could I ask you to sign the CLA so that I can merge it in?
http://www.elasticsearch.org/contributor-agreement/

**Comment by LeonardGC** [comment]
The CLA was signed.

**Comment by clintongormley** [comment]
Hi @LeonardGC 

Sorry, but I can't find any CLA containing Leonard or `leonardgc`

**Comment by LeonardGC** [comment]
Hi @clintongormley 
Sorry to hear this. What can I do to resolve this? 

In the history of the pdf I see that:
Signed document emailed to CLA Committers (committers@elasticsearch.com)...
04/13/2016 - 7:30:11 PDT

**Comment by clintongormley** [comment]
Hi @LeonardGC 

Could you email it to me please? (clinton at elastic dot co)

**Comment by clintongormley** [comment]
thanks @LeonardGC

**Pull request merged**
