### PR TITLE
Migrate to max line length of 100

### PR DESCRIPTION
**Pull request by jasontedor**
This commit moves the checkstyle rule of max line length from 140 characters to 100 characters. We whitelist all existing violations and will address them in follow-ups.

### CODE REVIEW

**Comment by nik9000** [comment]
Do it.

**Comment by rjernst** [comment]
Lgtm

**Comment by sscarduzio** [comment]
Hey, why was this necessary?

**Comment by olcbean** [comment]
That is a good question!

@jasontedor line width of a mere 100 for a language as verbose as Java is rather unusual. But I am sure that there is a good reason for this decision. It would be great to modify the description to include this information.

**Comment by sscarduzio** [comment]
Haha I know, super futile, yet interesting question, right?
100 chars is crazy short given the high def monitors we have nowadays.

**Comment by s1monw** [comment]
> @jasontedor line width of a mere 100 for a language as verbose as Java is rather unusual. But I am sure that there is a good reason for this decision. It would be great to modify the description to include this information.

the reason was that we wanted to limit the javadocs to 100 chars to make it easier to read. Yet, it's an all or nothing decision. We btw. decided to go back to 140 which will come rather soon.

**Comment by olcbean** [comment]
@s1monw thanks for the clarification
Great news that the code is back to 140 :smiley:

Btw the default setting for the comments (in Eclipse) is even 80. But I think you are right, for checkstyle it is all or nothing.

**Pull request merged**
