### PR TITLE
[Test] Enable logging for AmazonHttpClient

### PR DESCRIPTION
**Pull request by ywangd**
If sending request fails locally without reaching the server, the retryable exception is logged differently. This PR enables the logging for this scenario.

Relates: #88841
Relates: #101608

### CODE REVIEW

**Review by DaveCTurner — COMMENTED** [review]
LGTM (any good reason for `trace` instead of `TRACE`?)

**Comment by ywangd** [comment]
No great reason. I pushed 206e54141a20f9f187122db94c5c9d01f3302d6d to change them to uppercase.

Btw, you said "LGTM", but the formal GitHub level approval is still needed. Thanks!

**Review by DaveCTurner — APPROVED** [review]
Oh sorry I forgot to press the right button. LGTM for realsies this time.

**Comment by ywangd** [comment]
@elasticmachine update branch

**Comment by ywangd** [comment]
@elasticmachine update branch

**Comment by ywangd** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.x|[](https://github.com/elastic/elasticsearch/pull/116702)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

**Pull request merged**
