### PR TITLE
[7.x] Add category field to deprecation logs

### PR DESCRIPTION
**Pull request by pgomulka**
Deprecation logs in 7.x are using ESJsonLayout and it requires
additional fields to be declared in a log4j config in order to emit
values to logs.
This commit adds category field to deprecation log pattern

context: in 8.0 we use ECSLayout which do not require to declare additional fields upfront. In 7.x we have to declare them in the logging config. The PR introducing categories in master #67443. A backport to 7.x which missed this field https://github.com/elastic/elasticsearch/pull/68061

### CODE REVIEW

**Comment by pgomulka** [comment]
ok to test

**Comment by pgomulka** [comment]
@elasticmachine test this please

**Review by grcevski — APPROVED** [review]
LGTM! This looks good to me, I just had a question for my own better understanding, does the order of the fields declared in the .properties files matter? I can see that DeprecationIndexingComponent sets them in this order `category,key,x-opaque-id`, which is reversed from the properties files.

**Review by ChrisHegarty — APPROVED** [review]
LGTM.

**Pull request merged**
