### PR TITLE
Cut significant_terms to registerAggregation

### PR DESCRIPTION
**Pull request by nik9000**
and remove its PROTOTYPE.

Relates to #17085

### CODE REVIEW

**Comment by nik9000** [comment]
I wasn't able to test this because the build doesn't work on my machine any more after something merged a few minutes ago. So I'll hunt that down before I do any more of these....

**Comment by colings86** [comment]
LGTM

**Comment by colings86** [comment]
oh, thats possibly the new points stuff? I know Adrien was mentioning that sig terms on long fields would break following that change so maybe its related to that?

**Comment by nik9000** [comment]
> oh, thats possibly the new points stuff? I know Adrien was mentioning that sig terms on long fields would break following that change so maybe its related to that?

It was #17788. I think the points stuff is probably going to be transparent. Hopefully!

**Comment by nik9000** [comment]
Merged! Thanks for the review @colings86 !

**Pull request merged**
