### PR TITLE
Mark enrich stats API as internal instead of public

### PR DESCRIPTION
**Pull request by dakrone**
This was previously publicly available, however it exposes node counts and IDs. After discussion we've decided it's unnecessary on Serverless.

### CODE REVIEW

**Review by joegallo — APPROVED** [review]

**Review by masseyke — APPROVED** [review]
LGTM

**Comment by dakrone** [comment]
@elasticmachine update branch

**Comment by dakrone** [comment]
@elasticmachine update branch

**Comment by dakrone** [comment]
@elasticmachine update branch

**Pull request merged**
