### PR TITLE
Make `static final Set` constants immutable

### PR DESCRIPTION
**Pull request by sabi0**
`EnumSet` is mutable and is a poor fit for `static final Set` constants => wrap with `Collections.unmodifiableSet()`.
For other cases use the wrapping, `Set.of()` or `Collectors.toUnmodifiableSet()` as appropriate.

### CODE REVIEW

**Comment by pxsalehi** [comment]
Thank you for your contribution @sabi0. I think `EnumSet` usages have their own use-cases and advantages. I do not think we should replace all of them in one PR like this. If you have a specific part of the code in mind that benefits from using something else other than `EnumSet`,  I encourage you to open smaller and more targeted PRs, and instead close this PR.

**Comment by sabi0** [comment]
`Collections.unmodifiableSet()` is just a thin wrapper disabling the "mutator" methods. It does not cancel any of the EnumSet benefits (very small memory overhead, blazing speed).

And I don't have to explain the danger of having mutable constants. They could be updated unknowingly in some other place in the code, affecting every single place that happens to use it.

Consider this example:
```
new WeekTimes().days().add(SUNDAY);
// now every instance of WeekTimes created with default "days" has MONDAY _and_ SUNDAY
```

**Comment by pxsalehi** [comment]
I mostly agree, but this is changing quite a lot of code and is difficult to review. Please break it off into smaller pieces preferably by module/package which can then be reviewed independently by the separate teams.

**Comment by sabi0** [comment]
How do you suggest slicing this PR?
There are changes in:
- libs
- modules/ingest-attachment
- modules/ingest-geoip
- server
- test/framework
- and 10 x-pack plugins

Creating 15 PRs is way too much "bookkeeping overhead" IMO.

How about extracting `Collections.unmodifiableSet()` wrapping in one PR and sending the rest of the changes in the other?

**Comment by DaveCTurner** [comment]
> Creating 15 PRs is way too much "bookkeeping overhead" IMO.

That's why we tend to just reject this kind of "cleanup" PR. It's just too much overhead to review vs the benefits of the change, especially if the review needs coordination across multiple subteams. Indeed the [contributing guidelines](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md#reviewing-and-accepting-your-contribution) say specifically to avoid this kind of thing:

> We normally immediately reject isolated PRs that only perform simple refactorings or otherwise "tidy up" certain aspects of the code. We think the benefits of this kind of change are very small, and in our experience it is not worth investing the substantial effort needed to review them.

**Comment by sabi0** [comment]
Thank you for the explanation. I must admit I overlooked that paragraph.

But I do not agree with the "tidy up" classification here.
Mutable constants are a source of very hard to find bugs. And I do believe the codebase will be healthier with these changes.

**Pull request closed without merging**
