### PR TITLE
Add correct way to reference params

### PR DESCRIPTION
**Pull request by mayya-sharipova**

### CODE REVIEW

**Comment by mayya-sharipova** [comment]
@jdconrad Jack, do you know from what version we have changed how to use params? I can correct all version docs accordingly?

**Comment by jdconrad** [comment]
@mayya-sharipova I believe from 6.0 onward <- is this correct @rjernst?  Painless has always used params.<some var> instead of just straight <some var> because it allows us stricter compile-time checking.  I think any docs remaining without were referencing Groovy.

**Review by jdconrad — APPROVED** [review]
LGTM, thanks for tracking this down.

**Comment by mayya-sharipova** [comment]
@jdconrad Thanks for the background, Jack. I think with `groovy` being default script lang before these examples were valid. But with default `painless` lang, they break. I will correct other 6.x and master versions as well.

**Pull request merged**
