### PR TITLE
Stop Running Replication Action Retries on Transport or CS Threads

### PR DESCRIPTION
**Pull request by original-brownbear**
If the cluster state changes between creating the observer and getting to the
`retry` then we will retry on the current thread which could be the transport thread.
If the state changes later, the retry will run on the CS thread which is also a problem if its
slow.
Since we have to respect forced executions here for some operations we can't reuse the original
executor because we don't want to e.g. wait on the `WRITE` pool while on a thread that we may
not block ever like the transport thread => using the generic pool here for now as a workaround.

### CODE REVIEW

**Comment by original-brownbear** [comment]
Jenkins run  elasticsearch-ci/packaging-sample-windows

**Review by DaveCTurner — COMMENTED** [review]
For posterity, it looks like you can end up on a transport thread here if you try and execute an action on a remote primary, it fails retryably, and meanwhile a local shard has been promoted to primary, since we handle the response to remote actions on the transport thread and we don't dispatch local actions to a different thread. Seems pretty rare.

Running these things on the cluster applier thread seems a whole lot more likely.

Dispatching them to a generic thread isn't ideal, I'd prefer to send them off to the appropriate threadpool instead given that all the implementations have a specific threadpool in mind. However this means we also need to think much harder about whether to force-execute these actions or not.

---

Addendum, you can also end up on a transport thread if a remote action fails but late enough that the timeout has elapsed, because then we handle the timeout as part of handling the response to the remote action => on the transport thread. That seems likely too.

**Comment by original-brownbear** [comment]
@DaveCTurner thanks for taking a look with me! Adjusted this to use the proper executors now and reused the force execute flag to proper force or not force the retried action.

**Review by DaveCTurner — COMMENTED** [review]
Hmm:

- We've _always_ run the reroute phase on `SAME` even without a retry.
- Handling the first part of the primary/replica phases of a `TransportWriteAction` on `SAME` is deliberate since #57573, it's dispatched properly later on.
- `transportService.sendRequest()` dispatches properly too even on the local node.

The only weirdness around retries here seems to be that it can lead to running the reroute phase on the cluster applier thread rather than a transport thread, but that seems ok since the transport thread is the usual place for it so it must be fast.

Maybe that last bit is wrong and it's sometimes not fast? If so that's the real bug here.

**Comment by original-brownbear** [comment]
Yea I'm retracting this one. The reroute seems to never actually be that expensive. We do a bit of synchronization in `org.elasticsearch.index.shard.IndexShardOperationPermits` which threw me off (for whatever reason I associated this with IO) though it does does show up as somewhat costly but as you mention we do that regardless of whether its a retry or not in many cases.

> Maybe that last bit is wrong and it's sometimes not fast? If so that's the real bug here.

I could see how for remote nodes this isn't always super fast pre https://github.com/elastic/elasticsearch/pull/56961 but for a local retry it should have little overhead.

=> the fact that we do synchronization on the IO loop here isn't great but not unique to this spot as => sorry for the noise :(

**Pull request closed without merging**
