### PR TITLE
Remove stray back tick that's messing up table format

### PR DESCRIPTION
**Pull request by GlenRSmith**

### CODE REVIEW

**Comment by atorok** [comment]
@elasticmachine test this please

**Review by jrodewig — APPROVED** [review]
LGTM. I'll merge and backport. Thanks for the fix!

**Comment by colings86** [comment]
@jrodewig could you add the version labels for the versions you backported this to please?

**Comment by jrodewig** [comment]
@colings86  Added. Thanks @colings86

**Pull request merged**
