### PR TITLE
Don't expand ChunkedXContent objects until we actually iterate

### PR DESCRIPTION
**Pull request by thecoop**
Keep `ChunkedXContent` objects for as long as we can, only iterate them when we actually need to.

Relates https://github.com/elastic/elasticsearch/issues/118647

### CODE REVIEW

**Review by original-brownbear — COMMENTED** [review]
This still has the same issue for the map use case at least (the two `map.forEach` callsites).
We should fix those as well at the very least to have a quick fix. Long-term this class is still conceptually broken IMO. It's more expensive than the iterator chaining approach with all the stream indirection and it's easy to misuse it in a way that makes starting serialization heavier than O(1).

=> lets fix all the iterations in this class here and revisit the need for this thing with less urgency (i.e. don't close the issue linked to this)?

**Comment by thecoop** [comment]
I've pushed the map iteration fixes - there are other uses of `Iterator` I could make more explicit too.

I think there is significant benefit to this API, compared to the various random methods in `ChunkedToXContentHelper` - it was very unclear exactly what each method does. The builder is more structured, with clearer and more consistent method names. If there is still a performance drop in some situations, there are further ways we can make it more efficient - for example, using a pre-allocated backing `List` instead of a `Stream`

**Comment by original-brownbear** [comment]
I think the overhead of wrapping in a stream is effectively unfixable. Profiling suggests that most of the cost for chunked serialization is currently coming out of having a megamorphic type on the iterator as well as the toXContent on the individual elements. Wrapping into another layer of stream probably doubles that cost + we have a lot more allocations here.
If anything we should probably go the other direction and customize the iterators more to avoid those megamorphic calls IMO.

**Comment by thecoop** [comment]
I've removed the use of streams, which should also reduce the number of different objects used. Running locally with rally, this shows a small improvement, but there's a lot of noise. I suggest we merge this in, and see what overall effect it has.

**Comment by original-brownbear** [comment]
@thecoop some quick benchmarking shows that this indeed gives a small speedup, but in terms of just the serialization this version is more than 2x slower than the previous version for the search response. This is somewhat obvious from the theory as well, the runtime cost here mainly comes out of method calls and we add a ton of method calls via the builder indirection wrapping the iterator more (and really any layer of wrapping is up to a 2x slowdown).
I'll do some cleaner profiling later and will post flame graphs, I wouldn't merge this. It just adds to the noise of the situation IMO. If we fix it lets do a 100% fix and not a 20% one that ups variance and makes it harder to reason about the remaining 80% :)

**Comment by thecoop** [comment]
How about #119063 ? Taking the methods from `ChunkedXContentBuilder`, but using the array-based semantics of `ChunkedToXContentHelper`

**Pull request closed without merging**
