### PR TITLE
Rename PlainTransportFuture -> TransportFuture

### PR DESCRIPTION
**Pull request by original-brownbear**
* The plain transport future is the only transport future we have as a result of #45756 -> renamed

### CODE REVIEW

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/2

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/2

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by original-brownbear** [comment]
Thanks @rjernst !

**Pull request merged**
