### PR TITLE
Remove Dead Code in Transport Package

### PR DESCRIPTION
**Pull request by original-brownbear**
* None of this stuff is used

### CODE REVIEW

**Comment by tbrooks8** [comment]
Looks good to me. But I think that it needs to be updated due to other code changes.

**Comment by original-brownbear** [comment]
@tbrooks8 thanks for taking a look, resolved the conflict now :)

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/bwc

**Review by Tim-Brooks — APPROVED** [review]
LGTM

**Comment by original-brownbear** [comment]
thanks @tbrooks8 !

**Pull request merged**
