### PR TITLE
[DOCS] Add Java to list of client libraries for basic HTTP authentication

### LINKED ISSUE #29743: Add cross reference links to Java rest client auth and encryption setup
*Original comment by @ppf2:*

Somewhere in here (https://www.elastic.co/guide/en/x-pack/current/http-clients.html#_client_libraries_over_http) we should start cross referencing the auth and encryption pages for the new Java REST client, eg.

https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/_basic_authentication.html
https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/_encrypted_communication.html

### PR DESCRIPTION
**Pull request by jrodewig**
### Changes

- Converts series to unordered list
- Updates several of the client links
- Sorts clients alphabetically
- Fixes missing `{wikipedia}` attribute
- Changes heading to sentence case

Closes #29743

Preview: http://elasticsearch_48647.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/http-clients.html

### CODE REVIEW

**Comment by jrodewig** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by jrodewig** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by jrodewig** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by jrodewig** [comment]
@elasticmachine update branch

**Review by lcawl — APPROVED** [review]
LGTM

**Pull request merged**
