### PR TITLE
Let ingest intercept bulk requests at the bulk shard transport level.

### PR DESCRIPTION
**Pull request by martijnvg**
Today ingest intercepts bulk requests at the bulk transport level. All the bulk items get preprocessed one by one at the coordinating node and there is no parallelism. After that the bulk api splits the requests up in shard bulk requests and then bulk indexing happens in parallel. It would be nice if ingest also preprocesses bulk requests in parallel.

I have been playing around with this idea and come up with this PR for discussion.
Without this change the amount of time spent on ingestion is pretty high chuck on time comparing it to the total time spent (when indexing into indices with a few shards and higher). With this change the relative ingest time compare to the total time spent drops significantly. The change does look sane to me, but perhaps I overlooked something.

### CODE REVIEW

**Comment by clintongormley** [comment]
One problem I foresee with this... what happens if the pipeline changes the `_id`, `_routing`, `_index`, or `_parent`?

**Comment by martijnvg** [comment]
@clintongormley Good point, I didn't take this into account when thinking about this optimization.

My goal is to achieve parallelism by using existing infrastructure. This approach fits nicely with how things already work. I need to think a bit more how can increase the parallelism for bulk requests in order to also make this work when `_routing` or `_index` is changed.

**Comment by bleskes** [comment]
I share @clintongormley concerns and some more. This parallelism is only needed where people are using a single client. On top of that, the client does round robin on multiple nodes but rather sends all traffic to a single ES node. IMO this is a very specialized situation. Things like our clients, beats and logstash do not fall under category. Sadly simple benchmarks do. All in all, I'm not sure we should embark on this adventure until we see some real ingest usage and evaluate if it's needed.

Second, if we do want to this, I suggest introducing the parallelism in `PipelineExecutionService` and how it interacts with the bulk thread pool. @martijnvg and I discussed some options there which will allow us to keep all the flexibility we have today (but are still tricky, mostly around deciding things like queue size, parallelism levels etc.)

**Comment by martijnvg** [comment]
> Second, if we do want to this, I suggest introducing the parallelism in PipelineExecutionService and how it interacts with the bulk thread pool. @martijnvg and I discussed some options there which will allow us to keep all the flexibility we have today (but are still tricky, mostly around deciding things like queue size, parallelism levels etc.)

My hope was that intercepting requests at the bulk shard level would solve this problem with introducing any complexity elsewhere. (both for clients sending data to a single node and official clients that round robin)

> All in all, I'm not sure we should embark on this adventure until we see some real ingest usage and evaluate if it's needed.

Agreed, we should be cautious adding this. I'm in no rush at all to push this. I see this PR as a small experiment on how potentially things can be changed to improve things in certain scenarios. The official clients already to the right thing and this change wouldn't improve things as much as for the single client case in a multi node cluster.

**Comment by martijnvg** [comment]
Closing, we shouldn't push for this single bulk request optimization, how things are okay as they are now, when clients send bulk requests is parallel

**Pull request closed without merging**
