### PR TITLE
Calculate the rate bucket value using the current bucket data

### LINKED ISSUE #94223: rate agg on tsdb counter field seems to return wrong data
### Elasticsearch Version

8.7

### Installed Plugins

_No response_

### Java Version

_bundled_

### OS Version

macos

### Problem Description

when running a rate aggregation on tsdb counter field the results i get don't seem correct. 

To test this i created a dataset with `bytes` field which logs the number of bytes transfered per document and `bytes_counter` which logs the ever increasing total of bytes transfered. There are no resets in the counter field. there is also a `request` field which is set as tsdb dimension.

Then i try to run the following: (for all below there is a date histogram aggregation on a top level)
- `rate (bytes)`
- `sum_bucket(high cardinality terms on my `request field`, rate(bytes))` which as expected gives me same results
- `sum_bucket(timeseries, rate(bytes_counter))` which unexpectedly gives me different results

screenshot-localhost_5601-2023 03 01-12_33_33

full request:
```
{
  "aggs": {
    "4": {
      "date_histogram": {
        "field": "@timestamp",
        "calendar_interval": "1d",
        "time_zone": "Europe/Ljubljana",
        "min_doc_count": 1
      },
      "aggs": {
        "8": {
          "sum_bucket": {
            "buckets_path": "8-bucket>8-metric"
          }
        },
        "9": {
          "sum_bucket": {
            "buckets_path": "9-bucket>9-metric"
          }
        },
        "10": {
          "rate": {
            "field": "bytes_gauge",
            "unit": "second"
          }
        },
        "8-bucket": {
          "terms": {
            "field": "request",
            "order": {
              "_key": "desc"
            },
            "size": 500
          },
          "aggs": {
            "8-metric": {
              "rate": {
                "field": "bytes",
                "unit": "second"
              }
            }
          }
        },
        "9-bucket": {
          "time_series": {},
          "aggs": {
            "9-metric": {
              "rate": {
                "field": "bytes_counter",
                "unit": "second"
              }
            }
          }
        }
      }
    }
  },
  "size": 0,
  "fields": [
    {
      "field": "@timestamp",
      "format": "date_time"
    },
    {
      "field": "timestamp",
      "format": "date_time"
    },
    {
      "field": "utc_time",
      "format": "date_time"
    }
  ],
  "script_fields": {},
  "stored_fields": [
    "*"
  ],
  "runtime_mappings": {},
  "_source": {
    "excludes": []
  },
  "query": {
    "bool": {
      "must": [],
      "filter": [
        {
          "range": {
            "@timestamp": {
              "format": "strict_date_optional_time",
              "gte": "2023-02-03T04:00:00.000Z",
              "lte": "2023-02-08T04:00:00.000Z"
            }
          }
        }
      ],
      "should": [],
      "must_not": []
    }
  }
}
```

### Steps to Reproduce

already described above

### Logs (if relevant)

_No response_

### PR DESCRIPTION
**Pull request by salvatore-campagna**
When a rate aggregation is nested inside a parent aggregation
it needs to calculate the per-bucket rate before actually updating
time and value. This is because, if the parent aggregation is on a
new bucket, using the new bucket value means the rate aggregation
is using data of the new parent bucket.

Think about a date histogram aggregation that is aggregating data
on a day (`calendar_interval: 1d`) or on an hour (`calendar_interval: 1h`).
When calculating the rate you need to use time and value for that day (or hour),
including the timestamp, not the value and timestamp of the following
bucket which is on another day or another hour.

Put it another way. We do the same when the `tsid` changes. We calculate
the bucket first and then we update values used for the bucket calculation.
In this case the `tsid` does not change but the bucket is changing.

This bug is difficult to observe since it is triggered only when calculation
happens at the boundary between two buckets in the parent aggregator.

Resolves #94223

### CODE REVIEW

**Comment by salvatore-campagna** [comment]
@elasticsearchmachine test this please

**Comment by romseygeek** [comment]
Handling boundaries here is an area where I think there isn't necessarily a 'right' answer.  The advantage of waiting until you've moved to the next bucket before updating the values is that you are then taking into account the gap between the final value of the first bucket, and the first value of the next one.

Let's say we are recording a value every 15 seconds, and bucketing per minute.  We have the following values:

| 00:00:00 | 00:00:15 | 00:00:30 | 00:00:45 | 00:01:00 | 00:01:15 | 00:01:30 | 00:01:45 | 00:02:00 |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
|  1 | 2 | 3 | 4 | 6 | 7 | 8 | 9 | 10 |

Note the jump in value from 4 to 6 over a bucket boundary.  Currently this jump will be included in the calculated rate for the `00:00:00 - 00:01:00` bucket, but with this change the jump will not be included in the rate for either bucket.

**Comment by salvatore-campagna** [comment]
> Handling boundaries here is an area where I think there isn't necessarily a 'right' answer. The advantage of waiting until you've moved to the next bucket before updating the values is that you are then taking into account the gap between the final value of the first bucket, and the first value of the next one.
> 
> Let's say we are recording a value every 15 seconds, and bucketing per minute. We have the following values:
> 
> 00:00:00	00:00:15	00:00:30	00:00:45	00:01:00	00:01:15	00:01:30	00:01:45	00:02:00
> 1	2	3	4	6	7	8	9	10
> Note the jump in value from 4 to 6 over a bucket boundary. Currently this jump will be included in the calculated rate for the `00:00:00 - 00:01:00` bucket, but with this change the jump will not be included in the rate for either bucket.

I see. But then, let's say the parent histogram aggregation is on 1 minute interval...we are using data that belongs to another parent bucket to do the calculation...in Kibana this seems to lead to issues.

See #94223

**Comment by salvatore-campagna** [comment]
I am going to close this without merging. We discussed this in a TSDB sync and agreed to keep the existing behaviour.

There are two main reasons to keep the current implementation:
1. if we use only values within a bucket (parent bucket) as done in this PR we do not compute the rate across buckets. This might result in missing some values (possibly even spikes) and eventually in steps or "holes" in the UI;
2. Calculating the rate as done in this PR might result in not being able to calculate it in some scenarios. Imagine you have a histogram parent aggregation using a daily interval and that you just have a single document per each bucket...in that case, since we do not have at least two documents per bucket, we would be in a weird situation...we basically have data about the metric but we are not able to calculate it...or put it another way we would not be able to calculate the rate using the data we have unless we adjust the parent date histogram interval.

**Pull request closed without merging**
