### PR TITLE
[7.x] Extract a create index method that only manipulates the ClusterState (#50240)

### PR DESCRIPTION
**Pull request by andreidan**
* Extract IndexCreationTask execute into applyCreateIndexRequest

This is the first step in preparation for separating the index creation into a few
steps that only deal with the cluster state mutation and removing the IndexCreationTask
altogether.

* Split applyCreateIndexRequest

This breaks down the logic in applyCreateIndexRequest into multiple
steps that will hopefully make the service more readable and unit testable.
The service creation process now goes through a few well defined steps,
namely find the templates that possibly match the new index, parse the
requested and template matching mappings, process the index and template
matching settings, validate the wait for active shards request and
create the `IndexService`, update the mappings in the `MapperService` (which
is grouped together with creating the sort order for validation purposes),
validate the requested and templated matching aliases and finally update
the `ClusterState` to reflect the requested changes.

This also removes the `IndexCreationTask` as it was a shallow
indirection and migrates the tests from `IndexCreationTaskTests` to
`MetaDataCreateIndexServiceTests` (making them "real" unit tests
operating on the `ClusterState` rather than mocks).

* Add more unit tests.

* Add IT to verify we cleanup in case of failure

(cherry picked from commit 57e6269f750471f05a1a79539ca45361b9e3c2b5)
Signed-off-by: Andrei Dan <andrei.dan@elastic.co>

# Conflicts:
    #       server/src/main/java/org/elasticsearch/cluster/metadata/MetaDataCreateIndexService.java
    #       server/src/test/java/org/elasticsearch/action/admin/indices/create/CreateIndexIT.java
    #       server/src/test/java/org/elasticsearch/cluster/metadata/IndexCreationTaskTests.java

Backport of https://github.com/elastic/elasticsearch/pull/50240

### CODE REVIEW

**Comment by andreidan** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Review by dakrone — APPROVED** [review]
LGTM

**Comment by andreidan** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by andreidan** [comment]
@elasticmachine upgrade branch

**Comment by andreidan** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by andreidan** [comment]
@elasticmachine run elasticsearch-ci/default-distro

**Comment by andreidan** [comment]
@elasticmachine update branch

**Comment by andreidan** [comment]
@elasticmachine run elasticsearch-ci/1

**Pull request merged**
