### PR TITLE
Fix ElasticsearchException getRootCause infinit loop (#33930)

### LINKED ISSUE #33930: ElasticsearchException getRootCause can result in infinite loop
**Elasticsearch version** (`bin/elasticsearch --version`): master

**Plugins installed**: []

**JVM version** (`java -version`): openjdk version "10.0.2"

**OS version** (`uname -a` if on a Unix-like system): Linux 4.15.0-33-generic

**Description of the problem including expected versus actual behavior**:

The [ElasticsearchException#getRootCause](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/ElasticsearchException.java#L264) can result in an infinite loop if there is cycle in the causes.
We run into such case because the ElasticsearchException was serialized at some point in our code.

**Steps to reproduce**:
I will create a PR
**Provide logs (if relevant)**:

### PR DESCRIPTION
**Pull request by bdelbosc**
Adapt getRootCause to detect cyclic causes.

Closes #33930

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)? yes
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)? I guess
- If submitting code, have you built your formula locally prior to submission with `gradle check`? in progress, the updated unit test pass
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)? no
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by jasontedor** [comment]
I am not convinced this is the right fix. I would like to understand how the cyclic cause that you are defending against arose first. Maybe the bug is elsewhere. Additionally, I would not want to protect against cyclicality this way. Instead, I would want to protect by counting iterations (as it would also protect against unreasonably long chains of causes).

**Review by jasontedor — CHANGES_REQUESTED** [review]
I am not convinced this is the right fix. I would like to understand how the cyclic cause that you are defending against arose first. Maybe the bug is elsewhere. Additionally, I would not want to protect against cyclicality this way. Instead, I would want to protect by counting iterations (as it would also protect against unreasonably long chains of causes).

**Comment by bdelbosc** [comment]
Hi, indeed I didn't get into such infinite loop,
I thought it was one because the exception has been serialized by mistake and I got:
```
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Direct self-reference leading to cycle (through reference chain: org.elasticsearch.ElasticsearchStatusException["cause"]->org.elasticsearch.ElasticsearchException["cause"]->org.elasticsearch.ElasticsearchException["rootCause"])
```
But this simply means that `getRootCause` returns itself when the exception is the root cause.

Nevertheless, cyclic causes do exist and `getRootCause` should be fixed.
Up to you for the implementation, the provided one is similar to the apache common lib ExceptionUtils.

**Comment by VamshiNaidi** [comment]
I am facing the same issue while serializing ElasticsearchException. Was any fix provided for this?
CC: @jasontedor @bdelbosc

**Comment by jasontedor** [comment]
@VamshiNaidi No. I want to know how this arising in practice before we commit any (if) code changes. What is your reproduction.

**Comment by VamshiNaidi** [comment]
@jasontedor 
Below is the ExceptionWrapper and we are trying to publish this to Kafka whenever there are any failures sending Employee data to ES.

`public class EmployeeExceptionWrapper {
    private final Employee employee;
    private final Exception exception;

    public EmployeeExceptionWrapper(Employee employee, Exception exception) {
        this.employee = employee;
        this.exception = exception;
    }

    public employee getEmployee() {
        return employee;
    }

    public Exception getException() {
        return exception;
    }
}`

Here is the exception I am getting while serializing this. ..

> org.apache.kafka.common.errors.SerializationException: Can't serialize data [com.xxx.model.EmployeeExceptionWrapper@2a772668] for topic [employee.failures]
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Direct self-reference leading to cycle (through reference chain: com.xxx.model.EmployeeExceptionWrapper["exception"]->org.elasticsearch.ElasticsearchException["rootCause"])

**Comment by jasontedor** [comment]
That is not the same as the reported issue at all @VamshiNaidi. That is using Jackson serialization. You need to deal with that client side and not generate a circular chain.

**Comment by danielmitterdorfer** [comment]
As explained in a previous comment, this issue needs to be addressed on the client-side so I hope you do not mind that I'll close this PR.

**Pull request closed without merging**
