### PR TITLE
ESQL: Allow custom delimiters in CsvTestsDataLoader

### PR DESCRIPTION
**Pull request by iverase**
It is currently not possible to generate datasets if any of the fields contain a comma. To avoid this limitation we can allow each dataset to define its own delimiter so they can overcome this limitation.

### CODE REVIEW

**Review by costin — APPROVED** [review]
LGTM.
What kind of dataset and delimiter do you have in mind?

**Comment by iverase** [comment]
The idea is a dataset containing countries and their bounding box (having polygons is too much), like:
```
id:keyword|name:keyword|shape:geography
ESP|Spain|BBOX(-18.169864, 4.316945, 43.764300, 27.637500)
```

But still does not work because the loader thinks the BBOX is multivalued. I am not sure the approach in this PR is the right one.

**Comment by luigidellaquila** [comment]
How are these CSV generated? Would it be easy to have something like

```
id:keyword,name:keyword,shape:geography
ESP,Spain,"BBOX(-18.169864, 4.316945, 43.764300, 27.637500)"
```

(see the `"` around WKT)

**Comment by iverase** [comment]
The data come from a test file un lucene spatial extra module: https://github.com/apache/lucene/blob/main/lucene/spatial-extras/src/test-files/data/countries-bbox.txt

It should be trivial to modify it.

**Comment by iverase** [comment]
not needed

**Pull request closed without merging**
