### PR TITLE
[Fix] _cat APIs add space at the end of a line

### LINKED ISSUE #9464: _cat APIs add space at the end of a line
I was trying to use the _cat/master API to get the name of the current master in a shell script, and then to determine whether the current host is the master.

~~~~
#!/bin/sh

name=`curl -sf 'http://localhost:9200' | jq --raw-output .name`
master=`curl -sf 'http://localhost:9200/_cat/master?h=node' `

[ "${name}" = "${master}" ]
~~~~

The problem here is that `master` will actually contain the name of the node *and a space character*, so the line needs to be fixed to look like this:
~~~~
master=`curl -sf 'http://localhost:9200/_cat/master?h=node' | xargs echo`
~~~~

This was very surprising, and makes using these APIs for scripting harder (without adding anything for the human reader).

Quick reading through the code: this space seems to come from `org.elasticsearch.rest.action.support.RestTable#buildTextPlainResponse()`.

PS: Is there a "nicer" way to determine whether the current node is a master from shell script, without having to parse JSON?

### PR DESCRIPTION
**Pull request by ghost**
Fixed #9464

### CODE REVIEW

**Comment by spinscale** [comment]
when running the rest tests against this branch after rebasing they are failing and one test is hanging somewhat...

```
HEARTBEAT J1 PID(14574@kryptic-2.local): 2015-05-29T18:32:11, stalled for  162s at: Rest6Tests.test {yaml=cat.nodes/10_basic/Test cat nodes output}
```

You can reproduce if you want via `mvn test -Dtests.slow=false -Dtests.filter=@Rest`

I will try to take a closer look at this soonish, but would be happy for any help.

**Comment by spinscale** [comment]
so I fixed the outstanding tests here, and refactored your patch a tiny bit, my commit is at https://github.com/spinscale/elasticsearch/commit/e599ae6b5b46678c3171cc4bed381212ae9bf5b4

If you want you can include that in your PR, rebase it against the current master and get it in. I can also just do it myself, whatever your prefer, @Myll

**Comment by clintongormley** [comment]
@spinscale want to get this rebased and merged?

**Comment by clintongormley** [comment]
Closed by #15250

**Pull request closed without merging**
