### PR TITLE
Upgrade junit to 4.13

### PR DESCRIPTION
**Pull request by racevedoo**
There should be no breaking changes. Release notes at: https://github.com/junit-team/junit4/blob/master/doc/ReleaseNotes4.13.md

### CODE REVIEW

**Comment by pugnascotia** [comment]
@elasticmachine ok to test

**Comment by pugnascotia** [comment]
@racevedoo CI has reported test failes, and there are merge conflicts now too.

**Comment by rjernst** [comment]
@elasticmachine update branch

**Comment by rjernst** [comment]
There are 2 failures that need to be investigated/worked on:
* buildSrc's testKit tests have an embedded ES build, which for some reason is running dependencyLicenses on tests deps, and has a sha1 for the junit jar within the test source
* There are dozens of uses of an existing `assertThrows` method from `ElasticsearchAssertions`. This method is statically imported, and is now being masked by the static method from `Assert` which we pick up because LuceneTestCase extends from Assert. These methods should possibly be converted to the new `assertThrows`, but give their signatures, for now we should either rename or qualify with the classname.

**Comment by rjernst** [comment]
We discussed this PR in the core/infra weekly and while we appreciate the attempt, we don't think it is worth merging at this time. The main reason is that we would like to stay in sync with RandomizedRunner and Lucene as to which junit version we are using. However, we would like to be prepared for that eventuality, so Jay has opened a PR (https://github.com/elastic/elasticsearch/pull/52582) to rename the offending method name collisions.

**Pull request closed without merging**
