### PR TITLE
Make force merge warning more precise

### PR DESCRIPTION
**Pull request by jtibshirani**
We tell users not to force merge unless their index is read-only. This PR
proposes to soften the warning and make it more precise. This way, more users
can consider force merging for their use case, like those with append-only
indices, or those with a small number of updates that can regularly perform a
force merge. One particular case have in mind is vector search, where users may
want to regularly force merge their index to improve search performance.

### CODE REVIEW

**Comment by DaveCTurner** [comment]
I think it would be worth mentioning write-amplification as another reason to avoid force-merging.

Also, could we improve our merging heuristics to make better decisions in these cases instead of pushing this kind of subtle decision onto the user?

**Review by mayya-sharipova — APPROVED** [review]
@jtibshirani Thanks, nice correction!

**Comment by mayya-sharipova** [comment]
@DaveCTurner 

> I think it would be worth mentioning write-amplification as another reason to avoid force-merging.

Can you please explain this?  Does it mean that we discourage any writes that are not strictly necessary?

**Comment by DaveCTurner** [comment]
> Can you please explain this? Does it mean that we discourage any writes that are not strictly necessary?

By "write amplification" I mean that each time a user force merges a (say) 50GiB shard to a single segment they will see 50GiB of write traffic to disk on each shard copy, and 50GiB more space consumed in their snapshot repository, even if they only wrote a single tiny doc to the shard since the last force-merge. I think this will be surprising to some users (and not the good kind of surprise)

**Review by imlakshay08 — COMMENTED** [review]
A great PR

**Comment by jtibshirani** [comment]
We can definitely mention write amplification (maybe just explaining how force merging to one segment needs to rewrite all the data).

> Also, could we improve our merging heuristics to make better decisions in these cases instead of pushing this kind of subtle decision onto the user?

I don't see this clarification as pushing a subtle decision to the user. Rather, it's just accurately describing the concern around force merging. Personally I had trouble understanding the current warning -- why is read-only necessary? It seems users have been confused too:
* https://stackoverflow.com/questions/60226215/why-segment-merge-in-elasticsearch-requires-stopping-the-writes-to-index/60231745#60231745
* https://stackoverflow.com/questions/71241525/elastic-search-force-merging-and-mergingto-do-or-not-to-do-force-merge

We also plan to look into a better default configuration for vector search (for example a different merge policy), so most users won't need to worry about this. But for some users, force merge is a helpful tool, and it seemed off to have the blanket statement of "never force merge if an index receives writes". This includes some vector search users, users who need to regularly expunge deletes, etc.

**Comment by DaveCTurner** [comment]
> I don't see this clarification as pushing a subtle decision to the user.

I know what you mean, but at the same time I do see users being confused with the effects of force-merging. It's very opaque, and quite a blunt tool. The reason we say to avoid force-merging before subsequent writes is indeed mainly simplicity of explanation, but I am still concerned that relaxing this guidance will cause more problems than it solves. Another point we should raise is that if you artificially reduce the number of segments then the automatic merge heuristics kind of stop working so in practice you have to trigger force-merges yourself rather frequently from then on.

> users who need to regularly expunge deletes

Force-merging is AIUI a rather unfriendly way for users to expunge deletes because it either does nothing or reduces the number of segments, and this is what leads to the over-large segments that break the automatic merge heuristics. Often I think it would be more appropriate to rewrite the existing segments in-place (minus deleted docs) but that's not an option today.

If vector search requires more aggressive merging to work well then it feels like a bit of a usability bug that we're not doing so automatically. I see that we might need folk to use force-merge in this case for now but I wonder if it would be better to offer that guidance specifically to vector search users instead of making it as general as this PR proposes.

**Comment by jtibshirani** [comment]
@DaveCTurner and I caught up through another channel and sorted out his concerns. I hadn't appreciated the point about write amplification before, specifically how regularly force merging can make snapshotting significantly more expensive. It's much simpler to recommend only force-merging an index when it's read-only.

I updated the change to be less extreme:
* Still only recommend force merging read-only indices, but soften the warning. Previously it sounded like something horrible would happen if you ever force merged an index being written to.
* Clarify the actual concerns around updates and snapshots. Now super advanced users can understand the details and make a judgement call about whether it's safe to use.

**Comment by DaveCTurner** [comment]
:+1: thanks Julie

**Review by mayya-sharipova — APPROVED** [review]
@jtibshirani thanks Julie, new changes LGTM

**Pull request merged**
