### PR TITLE
Use the SIMD optimized SQ vector scorer at search time

### PR DESCRIPTION
**Pull request by ChrisHegarty**
This commit extends the custom SIMD optimized SQ vector scorer to include search time scoring.

When run on JDK22+ vector scoring with be done with the custom scorer. The implementation uses the JDK 22+ on-heap  ALLOW_HEAP_ACCESS Linker.Option so that the native code can access the query vector directly.

### CODE REVIEW

**Comment by benwtrent** [comment]
@ChrisHegarty do we know what rally says? We should see a nice improvement with kNN searchs on arm.

**Comment by jimczi** [comment]
Running a benchmark using `msmarco-v2-vector` (130M vectors of 1024 dimensions) with 4 vector optimized nodes (arm) shows between 10 to 50% improvements on the search operations.
See for instance the result for the default 10-100 (baseline is main, contender is this branch):

```
|                                                        Metric |                                          Task |      Baseline |     Contender |      Diff |   Unit |   Diff % |
|--------------------------------------------------------------:|----------------------------------------------:|--------------:|--------------:|----------:|-------:|---------:|
|                                                Min Throughput | standalone-search-knn-10-100-multiple-clients | 312.705       | 451.463       | 138.758   |  ops/s |  +44.37% |
|                                               Mean Throughput | standalone-search-knn-10-100-multiple-clients | 319.622       | 466.929       | 147.307   |  ops/s |  +46.09% |
|                                             Median Throughput | standalone-search-knn-10-100-multiple-clients | 320.028       | 466.41        | 146.382   |  ops/s |  +45.74% |
|                                                Max Throughput | standalone-search-knn-10-100-multiple-clients | 322.269       | 476.279       | 154.01    |  ops/s |  +47.79% |
|                                       50th percentile latency | standalone-search-knn-10-100-multiple-clients |  22.3877      |  14.5363      |  -7.85141 |     ms |  -35.07% |
|                                       90th percentile latency | standalone-search-knn-10-100-multiple-clients |  26.3218      |  16.4792      |  -9.84261 |     ms |  -37.39% |
|                                       99th percentile latency | standalone-search-knn-10-100-multiple-clients |  33.5137      |  20.4893      | -13.0243  |     ms |  -38.86% |
|                                     99.9th percentile latency | standalone-search-knn-10-100-multiple-clients | 230.891       | 183.792       | -47.0989  |     ms |  -20.40% |
|                                    99.99th percentile latency | standalone-search-knn-10-100-multiple-clients | 287.355       | 228.732       | -58.623   |     ms |  -20.40% |
|                                      100th percentile latency | standalone-search-knn-10-100-multiple-clients | 328.72        | 266.904       | -61.816   |     ms |  -18.81% |
|                                  50th percentile service time | standalone-search-knn-10-100-multiple-clients |  22.3883      |  14.5336      |  -7.85467 |     ms |  -35.08% |
|                                  90th percentile service time | standalone-search-knn-10-100-multiple-clients |  26.3116      |  16.481       |  -9.83066 |     ms |  -37.36% |
|                                  99th percentile service time | standalone-search-knn-10-100-multiple-clients |  33.506       |  20.6267      | -12.8793  |     ms |  -38.44% |
|                                99.9th percentile service time | standalone-search-knn-10-100-multiple-clients | 230.81        | 183.961       | -46.8494  |     ms |  -20.30% |
|                               99.99th percentile service time | standalone-search-knn-10-100-multiple-clients | 287.072       | 228.772       | -58.3002  |     ms |  -20.31% |
|                                 100th percentile service time | standalone-search-knn-10-100-multiple-clients | 328.72        | 266.904       | -61.816   |     ms |  -18.81% |
|                                                    error rate | standalone-search-knn-10-100-multiple-clients |   0           |   0           |   0       |      % |    0.00% |
```

**Review by jimczi — APPROVED** [review]
LGTM

**Comment by ChrisHegarty** [comment]
Thanks for the benchmark results @jimczi 🙏

**Comment by ChrisHegarty** [comment]
@elasticmachine update branch

**Pull request merged**
