### PR TITLE
Increase stateless refresh thread pool

### PR DESCRIPTION
**Pull request by henningandersen**
The refresh thread pool is sized too aggressively low for current state of stateless, so increasing it.

Relates ES-7633 and ES-7631

### CODE REVIEW

**Review by Tim-Brooks — APPROVED** [review]
LGTM

**Review by tlrx — APPROVED** [review]
LGTM 2

**Review by arteam — APPROVED** [review]
Awesome, thanks Henning!

**Comment by henningandersen** [comment]
@elasticmachine update branch

**Review by fcofdez — APPROVED** [review]

**Pull request merged**
