### PR TITLE
Change ScriptException status to 400 (bad request)

### LINKED ISSUE #12315: Search template render API returns 500 error on malformed template
see https://github.com/elastic/elasticsearch/issues/12292

This should return a 400 error instead

### PR DESCRIPTION
**Pull request by cbuescher**
Currently failures to compile a script usually lead to a ScriptException, which
inherits the 500 INTERNAL_SERVER_ERROR from ElasticsearchException if it does
not contain another root cause. Issue #12315 suggests this should be a 400
instead for template compile errors, but I assume more generally for script
compilation errors. This changes ScriptException to return 400 (bad request) as
the status code and changes MustacheScriptEngine to convert any internal
MustacheException to the more general ScriptException.

Closes #12315

### CODE REVIEW

**Comment by cbuescher** [comment]
@colings86 found this while looking at old search related issues, since you opened this one maybe you can comment if it is still relevant? I'm not entirely sure what this means for bwc since this changes the return codes for several kinds of script errors. I think that a "bad request" is more appropriate than a 500 for all of them since its usually a bad user input on the request side that is triggering the error, rather than a server problem.

**Review by colings86 — COMMENTED** [review]
This is actually a bit tricky. Because we have two ways of using scripts:
1. inline scripts - Here I agree that a script compilation error should be a 400 since the user that made the request provided the script that can compile so the burden is on them to fix the request so the script compiles
2. Stored scripts - If a request uses a stored script then the user making the request is not really to blame for the script compilation and doesn't really have the burden of fixing it since they are just using a resource form the server. In this case I think throwing back a 400 is wrong because the user can't change the request to fix the compilation error. In practice I am not sure if this happens as we may well compile stored scripts before we accept them to be stored, in which case the script exception would be throw back to the client that tried to put the script with a 400, but I am not sure on this.

**Comment by cbuescher** [comment]
> In practice I am not sure if this happens as we may well compile stored scripts before we accept them to be stored, in which case the script exception would be throw back to the client that tried to put the script with a 400, but I am not sure on this.

I thought about this too, will check what happens when storing scripts/templates. Even then, I'm on the fence if this couldn't also be served with a 400, its basically still a user error, just one the is kind of delayed by using the stored resource. Its less of a system problem IMHO.

**Comment by cbuescher** [comment]
> we may well compile stored scripts before we accept them to be stored

I just checked. Unfortunaltely we don't (at least not for mustache templates, painless). Its possible to store broken scripts using the `_script` endpoint, we will error when first using then.
I assume this is a concious decision, probably we can check on that. The question remains if this shouldn't be regarded as a user input error still.

**Comment by colings86** [comment]
Ok, it might be a good idea to open an issue for whether we should compile scripts on the PUT stored script API so we can discuss if we should do that.

> The question remains if this shouldn't be regarded as a user input error still.

I don't think it should be regarded as a 400 as that error code's description is:
> The HyperText Transfer Protocol (HTTP) 400 Bad Request response status code indicates that the server could not understand the request due to invalid syntax

Which this case doesn't match with. In the case where the stored script does not compile the request itself is completely valid and does not contain any bad syntax so I think a 400 is not appropriate here.

**Comment by jasontedor** [comment]
400 status codes are broader than syntax issues, they are for general client errors. From [RFC 7231](https://tools.ietf.org/html/rfc7231#section-6.5.1), the authoritative source:

> The 400 (Bad Request) status code indicates that the server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).

I think that it is a client error to try to use a broken script, whether or not it its the fault of the user that the script is broken to begin with.

**Comment by colings86** [comment]
Ok in which case I am fine with us making this a 400 error

**Review by colings86 — APPROVED** [review]
LGTM

**Comment by cbuescher** [comment]
@colings86 thanks for the review. 
I'm still wondering about the bwc aspect of this change. I expect a few test still needing changes before CI is green, I guess having this on master at first if fine for closing #12315, but I'm not sure if this needs a note in the migration guide or not. (Its still an error, not sure if we have documented http status code changes in the past.

**Comment by colings86** [comment]
Hmmm, I don't know what we have done in the past for bwc on status code changes. @jasontedor @clintongormley any thoughts on how we need to handle bwc here?

**Comment by cbuescher** [comment]
test this please

**Comment by rjernst** [comment]
> Ok, it might be a good idea to open an issue for whether we should compile scripts on the PUT stored script API so we can discuss if we should do that.

This is not currently done because we don't know which context to try to compile for. Since contexts can make different variables and classes available, there is no way to compile scripts without knowing a context. One idea we had was to try compiling for all contexts, and fail if none succeed, but that is yet to be implemented.

**Comment by clintongormley** [comment]
> Hmmm, I don't know what we have done in the past for bwc on status code changes. 

In the past we have just changed them.  My assumption in this case is that, if anybody is catching exceptions on a search request, then they are probably catching 400's and 500's, so changing this to 400 would still allow their code to work.

**Comment by jasontedor** [comment]
I also think that we can change this (as we have in the past); a note in the migration docs should suffice.

**Pull request merged**
