### PR TITLE
use ES_PLUGINS env variable to Install external plugin to elastic docker at the time of start

### LINKED ISSUE #75864: use ES_PLUGINS env variable to  Install external plugin to elastic docker at the time of start
As a User, I like to install list of external plugins before starting up the docker cluster.
use env variable ES_PLUGINS to assign list of plugin need to install at the time of start
first install list of plugin assign in env variable and then start the elastic docker

### PR DESCRIPTION
**Pull request by ajaykumar4**
Fixes #75864 
use ES_PLUGINS env variable to Install external plugin to elastic docker at the time of start

### CODE REVIEW

**Comment by AjayKumar4** [comment]
I have signed CLA agreement, even then it is failing

**Comment by AjayKumar4** [comment]
@elasticmachine test this please

**Comment by jasontedor** [comment]
Thanks for the contribution. However, see #70219. I think we want a solution broader than the one here, that applies also to the non-Docker images.

**Comment by AjayKumar4** [comment]
@jasontedor so do i need to close this PR and issue

**Comment by pugnascotia** [comment]
@AjayKumar4 yes, thank you for your contribution 🙏 but as Jason says, we're going to address this more comprehensively.

**Pull request closed without merging**
