### PR TITLE
Fixed typo in documentation

### PR DESCRIPTION
**Pull request by msancho**
The option in "gap_policy" "insert_zeros" was missing a trailing "s"

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?

### CODE REVIEW

**Comment by clintongormley** [comment]
Hi @msancho 

Thanks for the PR.  Please could I ask you to sign the CLA so that I can merge it in?
http://www.elasticsearch.org/contributor-agreement/

Also, further down the page there is the same typo. Please could you correct that too?

**Comment by msancho** [comment]
Sure thing, wanted to do it yesterday but had no internet at home. Will fix also the other typo

**Comment by clintongormley** [comment]
thanks @msancho  - merged!

**Comment by msancho** [comment]
Happy to help! :)

**Pull request merged**
