### PR TITLE
Prepare the codebase for new Auditor subclasses cont'd

### PR DESCRIPTION
**Pull request by przemekwitek**
This PR refactors auditor-related classes a bit to prepare for the new subclasses coming:
- extracted AbstractAuditMessageFactory interface

Additionally:
- added unit test for AnomalyDetectionAuditMessage.java
- replaced "assertEquals" with "assertThat" in auditor-related unit tests

Relates elastic/ml-team#184

### CODE REVIEW

**Comment by przemekwitek** [comment]
run elasticsearch-ci/1

**Comment by przemekwitek** [comment]
run elasticsearch-ci/1

**Comment by przemekwitek** [comment]
run elasticsearch-ci/1

**Comment by przemekwitek** [comment]
run elasticsearch-ci/2
run elasticsearch-ci/bwc
run elasticsearch-ci/default-distro

**Comment by przemekwitek** [comment]
run elasticsearch-ci/1

**Review by dimitris-athanasiou — APPROVED** [review]
LGTM

**Pull request merged**
