### PR TITLE
Update to to Gradle wrapper 7.5

### LINKED ISSUE #85123: Update Gradle wrapper to 7.5
Gradle 7.5 (snapshot) comes with(at least)  two breaking changes in our build.

1) The api of `SharedResource#getResourceLock()` that we use in `StandaloneRestIntegTestTask` has changed
2) Checkstyle tasks are not ran as separate process using the Gradle worker API. That is giving us a huge benefit as it allows us multiple checkstyle tasks for the same gradle project can been run in parallel now. However, how this initially work has finally ended up in Gradle master broke `:server:precommit` as the checkstyleMain and checkstyleTest require more than the default heap. We provided a fix for this to the Gradle team via this PR already: https://github.com/gradle/gradle/pull/20198

### PR DESCRIPTION
**Pull request by breskeby**
This updates the gradle wrapper to a 7.5

Fixes #85123

### CODE REVIEW

**Comment by breskeby** [comment]
run elasticsearch-ci/build-benchmark-part1

**Comment by breskeby** [comment]
elasticsearch-ci/build-benchmark-part2

**Comment by breskeby** [comment]
@elasticmachine run elasticsearch-ci/build-benchmark-part2

**Comment by breskeby** [comment]
@elasticmachine run elasticsearch-ci/build-benchmark-part1

**Comment by breskeby** [comment]
@elasticmachine run elasticsearch-ci/build-benchmark

**Comment by breskeby** [comment]
7.5 has finally landed. The change in checkstyle using the worker api seems to have quite an impact on the performance.

The benchmark results compared to 7.4.2 we run:
Screenshot 2022-07-15 at 08 30 29
Screenshot 2022-07-15 at 08 31 30

**Review by pugnascotia — APPROVED** [review]
LGTM

**Pull request merged**
