### PR TITLE
corrected formatting in global-aggregation.asciidoc

### PR DESCRIPTION
**Pull request by shree675**
Corrected a very minor indentation error in the multiline code block of global-aggregation.asciidoc.

### CODE REVIEW

**Comment by shree675** [comment]
Is signing the CLA absolutely necessary even for a small documentation change?

**Comment by abdonpijpelink** [comment]
@shree675 Thank you for contributing to the Elasticsearch documentation! Unfortunately, we can only accept your contribution after you've signed the CLA.

**Comment by abdonpijpelink** [comment]
@shree675 Do you plan to sign the CLA? Otherwise, I'll close this PR.

**Comment by shree675** [comment]
@abdonpijpelink Sorry, you can go ahead and close this. It was just a minor change.

**Pull request closed without merging**
