### PR TITLE
Add issue template

### PR DESCRIPTION
**Pull request by jasontedor**
This pull requests adds an issue template for contributors that open bug
reports or feature requests.

Additionally, this pull request adds a `.github` subdirectory to the project
and moves the `CONTRIBUTING.md` file to that directory.

### CODE REVIEW

**Comment by jasontedor** [comment]
Thanks to @dakrone for early feedback and iteration on this. Let's get *something* posted and see how it works out.

**Comment by dakrone** [comment]
+1, LGTM

**Comment by bleskes** [comment]
I don't know the intricacies of how this will influence the github UI , but +1 - it looks great. Let's just see.

**Comment by shreejay** [comment]
Link to TESTING.asciidoc is broken. Move it to .github folder or change the path?

**Comment by jasontedor** [comment]
@shreejay The `.github` folder is meant *only* for `CONTRIBUTING.md`, `ISSUE_TEMPLATE.md`, and `PULL_REQUEST_TEMPLATE.md` as this is a feature provided by GitHub. I'll fix the broken link in the `CONTRIBUTING.md` doc; thank you for reporting.

**Comment by shreejay** [comment]
Cool. Did not know about .github folder. Thanks.

**Pull request closed without merging**
