### PR TITLE
Add doc values support to the _size field, with fallback to fielddata for older index versions

### LINKED ISSUE #18334: _size doesn't support doc values
The documentation for the `mapper-size` plugin claims you can use `_size` in sorts, aggregations, and in scripts but I don't imagine any of those work because it doesn't support doc_values. Is it intentional that it doesn't?

### PR DESCRIPTION
**Pull request by jimczi**
Since fielddata for numerics is not available in ES anymore this change adds a simple LongFieldCacheIndexFieldData that uses the
UninvertingReader to create the FieldCache. This class is only available in the mapper size plugin.

Closes #18334

### CODE REVIEW

**Comment by rmuir** [comment]
Is this an april fools? We definitely shouldn't do this.

**Comment by jimferenczi** [comment]
@rmuir lol ! Maybe we should not do it but this would mean no aggs or sort on the _size field unless the index has been created after alpha4. @clintongormley WDYT ?

**Comment by rmuir** [comment]
Yes, please. My concern is definitely use of the lucene fieldcache (UninvertingReader). I cannot think of any possible reason why we'd ever want to do that: simply put, nothing can justify its use. This is not even in lucene's trunk anymore!

**Comment by nik9000** [comment]
As I see it we have a couple of options:
1. Remove the ability to sort and aggregate on size or
2. Have a way of building the appropriate data structures in 2.x so that aggregations and sorting keep working on upgrade to 5.0 or
3. Tell people that if they use aggregations or sorts on size they'll have to reindex once they upgrade or
4. Support the structures we have for indexes built in 2.x.

Am I missing something?

**Comment by rmuir** [comment]
I'm confused why we wouldnt just try to recommend these users move to `ingest-attachments` anyway?

Either way: please, lets not bring UninvertingReader into this. I don't care what the consequences are.

**Comment by clintongormley** [comment]
> I'm confused why we wouldnt just try to recommend these users move to ingest-attachments anyway?

This is not to do with attachments (issue was incorrectly labelled), but with the `_size` metafield, which didn't support doc-values in 2.x.  This renders the field useless when upgrading to 5.x, unless we have a fallback to fielddata for old indices.

Chatting to @jpountz he says we could resurrect fielddata just for this plugin, but it would require a sizeable amount of effort to do so.  This is not a widely used plugin and we're not entirely sure how it is being used, so I suggest that we add doc values to `_size` now (if not there already), and we wait on adding the bwc layer until users ask for it.

**Comment by nik9000** [comment]
> I suggest that we add doc values to _size now (if not there already), and we wait on adding the bwc layer until users ask for it.

+1. So long as we leave a note that it is a breaking change and tell users how to get around it. I think the only option is to reindex.

**Comment by jimferenczi** [comment]
> I suggest that we add doc values to _size now (if not there already)

I opened a new PR here:
https://github.com/elastic/elasticsearch/pull/19217

> and we wait on adding the bwc layer until users ask for it.

... so I am going to close this one until users ask for it.

**Pull request closed without merging**
