### PR TITLE
Make sure file accesses in DnRoleMapper are done in stack frames with permissions

### PR DESCRIPTION
**Pull request by thecoop**
The Settings method doesn't have permissions to access secured files

### CODE REVIEW

**Comment by thecoop** [comment]
This fixes the bug - we can look at improving the testing as part of https://github.com/elastic/elasticsearch/pull/112411

**Review by mosche — APPROVED** [review]
lgtm 🥇

**Comment by ppf2** [comment]
@thecoop I believe this is now targeted for 8.15.2, should we update the version label? Also, should we add a known issue entry to 8.15.0 and 8.15.1 (upcoming) release notes? Thx!

**Comment by thecoop** [comment]
Good idea - created https://github.com/elastic/elasticsearch/pull/112506

**Pull request merged**
