### PR TITLE
Convert BucketScript to static parser

### PR DESCRIPTION
**Pull request by polyfractal**
I was wanting to make some changes to BucketScript to support "empty" buckets, but the old style parser was getting in the way.  This converts it over to the new(er) static parser.  It also adds a test for GapPolicy enum serialization since that was lacking.

### CODE REVIEW

**Comment by polyfractal** [comment]
@elasticmachine update branch

**Review by iverase — APPROVED** [review]
LGTM

**Comment by tylersmalley** [comment]
We're seeing issues with Kibana that we have tracked back to this commit. 

```
{
  "error": {
    "root_cause": [
      {
        "type": "x_content_parse_exception",
        "reason": "[61:33] [bucket_script] buckets_path doesn't support values of type: VALUE_STRING"
      }
    ],
    "type": "x_content_parse_exception",
    "reason": "[61:33] [bucket_script] buckets_path doesn't support values of type: VALUE_STRING"
  },
  "status": 400
}
```

Here is an example of a query throwing the exception:

```
POST /_all/_search?ignore_throttled=true&timeout=30000ms
{
  "query": {
    "bool": {
      "must": [
        {
          "range": {
            "@timestamp": {
              "gte": "2019-07-20T02:38:31.637Z",
              "lte": "2019-07-20T02:53:31.637Z",
              "format": "strict_date_optional_time"
            }
          }
        }
      ],
      "filter": {
        "bool": {
          "must": [],
          "filter": [
            {
              "match_all": {}
            }
          ],
          "should": [],
          "must_not": []
        }
      }
    }
  },
  "aggs": {
    "q": {
      "meta": {
        "type": "split"
      },
      "filters": {
        "filters": {
          "*": {
            "query_string": {
              "query": "*"
            }
          }
        }
      },
      "aggs": {
        "time_buckets": {
          "meta": {
            "type": "time_buckets"
          },
          "date_histogram": {
            "field": "@timestamp",
            "interval": "1s",
            "time_zone": "America/Los_Angeles",
            "extended_bounds": {
              "min": 1563590311637,
              "max": 1563591211637
            },
            "min_doc_count": 0
          },
          "aggs": {
            "count": {
              "bucket_script": {
                "buckets_path": "_count",
                "script": {
                  "source": "_value",
                  "lang": "expression"
                }
              }
            }
          }
        }
      }
    }
  },
  "size": 0
}
```

Is there an intentional breaking change here, or something we should be doing differently in this Timelion request?

**Comment by iverase** [comment]
This is not an intentional break. I have opened a PR toads back the possibility of defining `buckets_path` as a string or as an array.

**Pull request merged**
