### PR TITLE
Remove ignored fallback option on GeoIP processor

### PR DESCRIPTION
**Pull request by PeteGillinElastic**
This removes the option `fallback_to_default_databases` on the `geoip` ingest processor has been deprecated and ignored since 8.0.0.

### CODE REVIEW

**Review by joegallo — CHANGES_REQUESTED** [review]
Do any uses of `DEFAULT_DATABASES_DEPRECATION_MESSAGE` remain after this change? If not, I think you should remove the variable definition, too.

**Comment by PeteGillinElastic** [comment]
> Do any uses of `DEFAULT_DATABASES_DEPRECATION_MESSAGE` remain after this change? If not, I think you should remove the variable definition, too.

Good call, done.

**Review by joegallo — APPROVED** [review]

**Comment by leemthompo** [comment]
@PeteGillinElastic is this PR relevant to the serverless changelog? [FYI this question is based on [9.0 breaking changes](https://staging-website.elastic.co/docs/release-notes/elasticsearch/breaking-changes)]

**Comment by PeteGillinElastic** [comment]
> @PeteGillinElastic is this PR relevant to the serverless changelog? [FYI this question is based on [9.0 breaking changes](https://staging-website.elastic.co/docs/release-notes/elasticsearch/breaking-changes)]

I think this depends on the policy for the serverless changelog. This property was deprecated and ignored since 8.0.0, so nobody should have been using it in serverless. I don't know whether this should be mentioned or not.

**Comment by PeteGillinElastic** [comment]
Also, this change was made in November, before serverless GA.

**Pull request merged**
