### PR TITLE
Correction of the names of numirals

### PR DESCRIPTION
**Pull request by Nomadzy**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?

What was called Arabic numirals is actually Hindu - Eastern Arabic notation. And the Latin numirals you refer to is the Arabic numbers. Please see wikipedia for more informations 
Regards.

### CODE REVIEW

**Comment by nik9000** [comment]
This looks right to me. Could you sign the CLA so we can merge it? I need it even for docs changes.

**Comment by Nomadzy** [comment]
Done 👍

**Comment by clintongormley** [comment]
thanks @Nomadzy - merged

**Comment by Nomadzy** [comment]
thx all.

**Pull request merged**
