### PR TITLE
Wait for task completion in IndexLifecycleRunnerTests

### LINKED ISSUE #94900: [CI] IndexLifecycleRunnerTests testRunStateChangePolicyWithNextStep failing
#94325 exposes some raciness in these tests that was hidden before.

**Build scan:**
https://gradle-enterprise.elastic.co/s/usugfk2dh6rti/tests/:x-pack:plugin:ilm:test/org.elasticsearch.xpack.ilm.IndexLifecycleRunnerTests/testRunStateChangePolicyWithNextStep

**Reproduction line:**
```
./gradlew ':x-pack:plugin:ilm:test' --tests "org.elasticsearch.xpack.ilm.IndexLifecycleRunnerTests.testRunStateChangePolicyWithNextStep" -Dtests.seed=58594895CA2093F1 -Dtests.locale=fr-BE -Dtests.timezone=US/Aleutian -Druntime.java=20
```

**Applicable branches:**
main

**Reproduces locally?:**
Yes

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.xpack.ilm.IndexLifecycleRunnerTests&tests.test=testRunStateChangePolicyWithNextStep

**Failure excerpt:**
```
java.lang.AssertionError: failed to register ILM history

  at __randomizedtesting.SeedInfo.seed([58594895CA2093F1:CD17BBC3898946E8]:0)
  at org.elasticsearch.xpack.ilm.IndexLifecycleRunnerTests.lambda$testRunStateChangePolicyWithNextStep$11(IndexLifecycleRunnerTests.java:376)
  at java.util.Optional.orElseThrow(Optional.java:403)
  at org.elasticsearch.xpack.ilm.IndexLifecycleRunnerTests.testRunStateChangePolicyWithNextStep(IndexLifecycleRunnerTests.java:376)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:578)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:843)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:490)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:390)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:850)
  at java.lang.Thread.run(Thread.java:1623)

```

### PR DESCRIPTION
**Pull request by DaveCTurner**
These tests submit tasks to the master service and wait for the state to be applied, but not for the publication to complete, and without that wait they may clean up too soon. This commit makes them wait for the master service to finish its work before cleaning up.

Relates #94325
Closes #94900

### CODE REVIEW

**Review by gmarouli — APPROVED** [review]
Thank you for fixing this @DaveCTurner, much appreciated. LGTM, I have one comment and a nit :). 

As I was going through the change I noticed one more attempt to close things at line 309. Should we add it there too?

Nit: This test already has a set up  and a tear down method, I am wondering if we could use them instead of doing the same things in many of these tests. I am happy to look into this as a follow up of this PR, if you think it's a good idea.

**Comment by DaveCTurner** [comment]
> As I was going through the change I noticed one more attempt to close things at line 309. Should we add it there too?

Thanks, yes I think that makes sense too. Added in 980f90e.

**Comment by DaveCTurner** [comment]
> I am happy to look into this as a follow up of this PR, if you think it's a good idea.

Yes please. In fact I think that it'd be simpler if most of these tests just waited for the master service to complete its work instead of using the per-task latch as done at the moment.

**Comment by gmarouli** [comment]
> > I am happy to look into this as a follow up of this PR, if you think it's a good idea.
> 
> Yes please. In fact I think that it'd be simpler if most of these tests just waited for the master service to complete its work instead of using the per-task latch as done at the moment.

Makes sense, I will look into it.

**Pull request merged**
