### PR TITLE
Remove extraneous test from Painless lambda tests

### PR DESCRIPTION
**Pull request by jdconrad**
This test has been awaiting a fix that isn't currently relevant because incoming lambda parameters are read-only.  If this ever changes a new set of tests can be added that are up-to-date.

### CODE REVIEW

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by jdconrad** [comment]
@rjernst Thanks for the review.  Will commit as soon as CI passes.

**Comment by jdconrad** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by jdconrad** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by jdconrad** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample

**Pull request merged**
