### PR TITLE
Fork Building Aggregate Index Capabilities Response to Management Pool

### PR DESCRIPTION
**Pull request by original-brownbear**
It's in the title. It has been observed that the merge step can run for
non-trivial amounts of time for very large states so we should fork
it to guard the transport threads.

### CODE REVIEW

**Review by DaveCTurner — APPROVED** [review]
LGTM, at least it's off the transport worker this way.

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/part-1

**Review by henningandersen — APPROVED** [review]
LGTM2

**Comment by original-brownbear** [comment]
Thanks David & Henning :)

**Pull request merged**
