### PR TITLE
`Setting` should not catch `AssertionError`

### PR DESCRIPTION
**Pull request by DaveCTurner**
We shouldn't be catching `AssertionError` in the production code here,
because that will suppress certain kinds of test failure. Instead we
should allow it to bubble up and fail the test.

### CODE REVIEW

**Comment by DaveCTurner** [comment]
These lines of code are pretty old and deeply suspicious. I'm removing them to see if anything fails. I hope nothing does.

**Review by nik9000 — COMMENTED** [review]
I like the idea. Catching this is indeed scary.

**Comment by DaveCTurner** [comment]
Looks like we were relying on this as a way of signalling invalid values, but only in unit tests. So this looks good to go.

**Review by nik9000 — APPROVED** [review]

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by DaveCTurner** [comment]
@elasticmachine please run elasticsearch-ci/part-1

**Pull request merged**
