### PR TITLE
Move memory locking into NativeAccess

### PR DESCRIPTION
**Pull request by rjernst**
This commit moves the implementations of locking virtual memory into RAM into NativeAccess.

relates https://github.com/elastic/elasticsearch/pull/104876

### CODE REVIEW

**Review by mark-vieira — APPROVED** [review]

**Review by ldematte — COMMENTED** [review]
Overall looks good, longer but much cleaner than before.
I only have a Q about testing: how can we test this? Maybe a test of where we spawn a different Java process (may even be the test runner itself), we lock, and then we check pages are effectively locked.
On Windows, that would be relatively easy (we already have VirtualQuery); on Linux, we could look at the `/proc/<pid>/mem` or `/proc/<pid>/maps files`.
Wdyt?

**Comment by ldematte** [comment]
Also, I'd suggest adding the `test-windows` label (and maybe test-arm, just in case) to test everything on windows too.

**Comment by rjernst** [comment]
> how can we test this?

This is very difficult, hence why we don't have any current _unit_ tests. We do indirectly test this with docker packaging tests, which have the appropriate bootstrap setting set. We don't have anything for windows. And testing error cases is even more difficult.

I wonder if we could defer adding additional tests. I agree they are needed, I just don't want to block refactoring on developing a testing strategy for this special case since it's not worse than the current situation (ie we have a little testing with packaging tests).

**Review by ldematte — APPROVED** [review]
> I wonder if we could defer adding additional tests. I agree they are needed, I just don't want to block refactoring on developing a testing strategy for this special case since it's not worse than the current situation (ie we have a little testing with packaging tests).

I think that's fair 
👍

**Pull request merged**
