### PR TITLE
Lenient default parameters

### PR DESCRIPTION
**Pull request by alexksikes**
The default parameters of the MLT query are set to be as lenient as possible
to ensure results are always returned. For example, in the common case of MLT
on a tag field (unique keywords per document), the default of `min_term_freq`
set to `2` would return no result. This change affects the defaults for
`min_term_freq`, `min_doc_freq` and `minimum_should_match`.

### CODE REVIEW

**Comment by jpountz** [comment]
Has someone been complaining about it? My concern is that even if it increases the likelyhood to get matches, it would also degrade the quality of the results and make the query slower to execute?

**Comment by clintongormley** [comment]
I've never used MLT in anger, but in older versions, the out of the box config didn't seem to work at all.  I had to make the above changes manually just to experiment with it.

it's arguable which would be the better default: something which works out of the box or something tuned for better performance (which of course the user can decide to do once they are more familiar with the API).

**Comment by synhershko** [comment]
It is easy to get MLT to break (aka return 0 results) and I have experienced this myself several times - but I don't think lowering the bar so much is the answer. Better docs probably, not bad defaults.

The current defaults are pretty good unless you have a very small dataset, or you are using MLT with short sentences. And that is solvable via better docs.

**Comment by alexksikes** [comment]
The parameter which affects the most performance is `max_query_terms` which hasn't been changed. As a user, I would definitely prefer an experience that works out of the box. Tuning the parameters for better performance is something that could be done afterwards. Also this should not affect the quality of the search results, as only more terms are inspected for inclusion in the final query.

**Comment by jpountz** [comment]
For the record, I am not against the change, just wanted to make sure that we are aware of the trade-off.

To echo @synhershko 's comments, the doc currently explains well how we use parameters, but maybe it could also try to better reflect how parameters affect quality and number of results?

**Comment by alexksikes** [comment]
I can't think of a reason why `min_doc_freq` was defaulted to `5`, and `min_term_freq` set to `2` would simply fail to return any result in the case of tags. These parameters only save us on the computation of the tf-idf, which could be expensive. But it seems that where most the time is spent is in executing a potentially long query governed by `max_query_terms`, which hasn't been changed.

Still, I added a small section to discuss how parameters affect quality vs. number of results, if the user wants to later on get more speed out at the expense of accuracy.

**Comment by jpountz** [comment]
OK. The change looks good, but I would like us to change the defaults on top of XMoreLike this so that we give it a chance to eventually converge with Lucene's MoreLikeThis.

**Comment by alexksikes** [comment]
I created a patch to make the two more in sync.

https://issues.apache.org/jira/browse/LUCENE-6283

**Comment by s1monw** [comment]
@alexksikes  what is the status of this?

**Comment by alexksikes** [comment]
The plan is to change `min_doc_freq` to `2` and `minimum_should_match` to `0%`, and skip the `min_term_freq` filter for when all terms have frequency of `1`. Sounds good?

**Comment by clintongormley** [comment]
+1

**Comment by alexksikes** [comment]
Closing in favor of #10619

**Pull request closed without merging**
