### PR TITLE
Introduce since field in the json spec

### PR DESCRIPTION
**Pull request by delvedor**
Hello team!
This pr introduces a new field in the JSON spec, the field name is `since`. As you can imagine, the field will show in which version of Elasticsearch an API has been added.
Our customers would benefit immensely from this addition as we could include this information in client documentation and the method's docblock's.

For now, there are a few caveats. For the OSS APIs the lowest version you can find is `v2.1.0`, because the JSON spec has been introduced in `v2.0.0` and we can't be sure when an API has been introduced before that version *(without manually checking the source code)*.
The same applies to the xPack APIs, which are tracked from `v5.4.0` and above. Where we can't define when an API has been introduced, you will find `null` instead of the version number.

Example:
```json
{
  "indices.clone": {
    "documentation": {
      "url": "https://www.elastic.co/guide/en/elasticsearch/reference/master/indices-clone-index.html",
      "description": "Clones an index",
      "since": "7.4.0"
    },
...
```
```json
{
  "bulk": {
    "documentation": {
      "url": "https://www.elastic.co/guide/en/elasticsearch/reference/master/docs-bulk.html",
      "description": "Allows to perform multiple index/update/delete operations in a single request.",
      "since": null
    },
...
```

We know that supporting this additional field could be uncomfortable when writing the JSON spec, but we think that it's very useful, and the resulting documentation quality will improve.

cc @elastic/es-clients

### CODE REVIEW

**Comment by Mpdreamz** [comment]
The `rest-api-spec` has been around since `0.90` so we could make this more complete if needs be

https://github.com/elastic/elasticsearch/tree/0.90/rest-api-spec/api

However the main goal is to signal API's introduced after the oldest still supported version to our users so I think going back as far back as 2.0 suffices.

**Comment by nik9000** [comment]
Neat!

**Comment by philkra** [comment]
pinging @elastic/es-core-infra

**Comment by mark-vieira** [comment]
I now struggle to remember where we landed on this. I know we are now validating our JSON specs inside the ES build. This is still something we want to add, yes?

**Comment by mark-vieira** [comment]
@Mpdreamz it looks like we've forgotten about this. Do we still intend to merge this?

**Comment by delvedor** [comment]
Hello @mark-vieira, this pr has been superseded by https://github.com/elastic/elastic-client-generator/pull/113. Sorry for the noise!

**Comment by mark-vieira** [comment]
Not a problem. Thanks for the update!

**Pull request closed without merging**
