### PR TITLE
Update IndexTemplateMetaData to allow unknown fields

### PR DESCRIPTION
**Pull request by martijnvg**
Update IndexTemplateMetaData to use ObjectParser
The IndexTemplateMetaData class used old parsing logic and was not
resiliant to new fields. This commit updates it to use the
ConstructingObjectParser and allow unknown fields.

Also a test was added that randomly generates a response that an ES node would returns and 
this test verifies that HLRC can parse it. This gives us the test coverage and confidence that
new parsing code is working well.

Relates #36938

### CODE REVIEW

**Review by hub-cap — APPROVED** [review]
LGTM but i wrote 1/2 the code so id like an independent set of 👓

**Review by dakrone — APPROVED** [review]
LGTM

**Review by jakelandis — APPROVED** [review]
LGTM for 7.x only

However, I would encourage a test that explicitly tests that "template" is no longer supported.  

I just realized this is only for the client code (not server side), so no need to add to breaking changes for server. I am OK with the client being more aggressive here then the server w/r/t to support for the deprecated field. (A test here would help to communicate that too).

**Comment by jakelandis** [comment]
@martijnvg - if you merge this is 7.x, could you please log a follow up issue to remove support for "template" in the server side parsers, targeted at 8.0 ?

**Comment by martijnvg** [comment]
@jakelandis The `IndexTemplateMetaData.Builder#toInnerXContent(...)` method never serializes the index patterns under the `pattern` key, always under the `index_patterns` key. Since what this method generates, is what the hrlc will parse, I think this PR can be backported to 6.7? I'm not saying we should, but there is no harm in backporting it? 

The logic that with the `pattern` key is only used for reading xcontent from the client on the server side. This parsing code was copied to hlrc, but can safely be removed.

> if you merge this is 7.x, could you please log a follow up issue to remove support for "template" in the server side parsers, targeted at 8.0 ?

Yes, I will open an issue for this.

**Pull request merged**
