### PR TITLE
Add flag to force external connections obtained from TransportService

### PR DESCRIPTION
**Pull request by polyfractal**
This adds a small flag which can force the TransportService to open/connect/return connections which are explicitly remote, essentially side-stepping the local node optimization on purpose.  This can be useful in certain situations, such as a plugin wanting to send a request to another plugin or module (i.e. the request needs to be serialized to avoid classloader problems)

The change is done in a way that doesn't affect existing code... it just gives an escape hatch for future consumers that need it.

### CODE REVIEW

**Comment by s1monw** [comment]
@polyfractal this looks like a massive hack around a different issue. Can you elaborate what you are trying to fix?

**Comment by polyfractal** [comment]
Hehe, yeah, i'll try again:

Basically, one plugin/module cannot communicate with another plugin/module without using an external client (TransportClient, or the new HTTP when it's ready).  I want to use DeleteByQuery from another module but can't because of classloader issues.  The options are A) use a bigger hack (`setLocalNode(null)` for a small duration of time) or B) maintain a TransportConnection to the local node.  Perhaps I missed another option?

A case could be made for lifting the DBQ interfaces into core, but that's a different discussion I think.

Ultimately this felt like an innocuous change because it's a performance optimization, not a safety/consistency/purity feature.

If the view is "All plugins/modules are 100% isolated, everything must go through REST" I understand, although it significantly complicates the life of plugins/modules.  Especially as the ecosystem grows and things become more inter-dependent. :)

**Comment by s1monw** [comment]
@polyfractal you can't depend on another plugin / module in the way that you require it to be loaded and you access it's classes from another plugin. If you want to use some functionality form another plugin today you have to depend on it's jar and duplicate it's classes, load it in your plugin and use it from there. How are you accessing the delete by query classes if you haven't the classes in your classpath?

**Comment by polyfractal** [comment]
Chatted on slack, going to attempt a different route (instantiating the a DBQTransportAction directly).  Closing :)

**Pull request closed without merging**
