### PR TITLE
Upgrade Lucene to 9.1.0-snapshot-949752

### PR DESCRIPTION
**Pull request by jtibshirani**
This PR upgrades Lucene to a newer snapshot `9.1.0-snapshot-9497524cc2d`.

Changes:
* Adapt to `LeafReader#searchNearestVectors` signature change
* Adapt checks in `GeometryIndexerTests`, `SearchServiceTests`, `FiltersAggregatorTests`, `AggregationProfilerIT`
* Address highlighting failures in `MultiPhrasePrefixQuery` and `HasChildQueryBuilder.LateParsingQuery`

### CODE REVIEW

**Comment by jtibshirani** [comment]
I am hoping for some help resolving test failures/ issues.

@nik9000 could you please take a look at the `FiltersAggregatorTests` and `AggregationProfilerIT` failures? I think it's just a matter of adapting test expectations, now that we rewrite `DocValueFieldExistsQuery` to `MatchAllDocsQuery` whenever every document has a value (https://issues.apache.org/jira/browse/LUCENE-10084), but it'd be great if you could double check.

@romseygeek do you have insights on the highlight failures? I wrote up my understanding here: https://github.com/elastic/elasticsearch/pull/83667#issuecomment-1054952323. It turns out that not only `MultiPhrasePrefixQuery` causes problems, also `HasChildQueryBuilder.LateParsingQuery`. In fact it could be any query that rewrites to `MatchNoDocsQuery` -- when it's part of a boolean query, it now makes the whole query rewrite to `MatchNoDocsQuery` and the unified highlighter cannot extract any terms. It is not straightforward to reproduce within Lucene because it is rare for core queries to rewrite to `MatchNoDocsQuery`.

**Comment by nik9000** [comment]
> @nik9000 could you please take a look at the `FiltersAggregatorTests` and `AggregationProfilerIT` failures? I think it's just a matter of adapting test expectations, now that we rewrite `DocValueFieldExistsQuery` to `MatchAllDocsQuery` whenever every document has a value (https://issues.apache.org/jira/browse/LUCENE-10084), but it'd be great if you could double check.

I believe that's so. I'll pull it locally and check.

**Comment by nik9000** [comment]
> I believe that's so. I'll pull it locally and check.

I've pushed an update to the aggs test. One is really testing a path for `DocValueFieldsExists` queries. The other one just needed expectations fixed.

**Comment by jtibshirani** [comment]
@elasticsearchmachine run elasticsearch-ci/part-1

**Review by mayya-sharipova — APPROVED** [review]
@jtibshirani This LGTM, looks like a difficult upgrade.  I liked how you've created a Lucene highlighter issue to be addressed later.

**Comment by jtibshirani** [comment]
Thanks everyone for the fixes and reviews!

**Pull request merged**
