### PR TITLE
Allow removing replicas setting on closed indices

### LINKED ISSUE #56675: UpdateSettingsIT.testDefaultNumberOfReplicas failure
New feature and test failed.
Didn't reproduce locally. 

https://gradle-enterprise.elastic.co/s/aieofxifyllmi

```
java.lang.IllegalStateException: Shard [2] routing table has wrong number of replicas, expected [1], got [7]
	at __randomizedtesting.SeedInfo.seed([263350F27C2AB0C7:41520057E38551CD]:0)
	at org.elasticsearch.cluster.routing.IndexRoutingTable.validate(IndexRoutingTable.java:127)
	at org.elasticsearch.cluster.routing.RoutingTable.validate(RoutingTable.java:171)
	at org.elasticsearch.cluster.routing.allocation.AllocationService.buildResult(AllocationService.java:147)
```

    >REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.indices.settings.UpdateSettingsIT.testDefaultNumberOfReplicas" -Dtests.seed=263350F27C2AB0C7 -Dtests.security.manager=true -Dtests.locale=da -Dtests.timezone=Asia/Sakhalin -Dcompiler.java=14 -Druntime.java=8

### PR DESCRIPTION
**Pull request by jasontedor**
This is similar to a previous change that allowed removing the number of replicas settings (so setting it to its default) on open indices. This commit allows the same for closed indices.

It is unfortunate that we have separate branches for handling open and closed indices here, but I do not see a clean way to merge these two together without making a rather unnatural method (note that they invoke different methods for doing the settings updates). For now, we leave this as-is even though it led to the miss here.

Relates #56656 
Closes #56675

### CODE REVIEW

**Review by dnhatn — APPROVED** [review]
LGTM. Thanks Jason

**Comment by jasontedor** [comment]
@elasticmachine update branch

**Comment by jasontedor** [comment]
@elasticmachine update branch

**Comment by jasontedor** [comment]
@elasticmachine update branch

**Comment by jasontedor** [comment]
@elasticmachine update branch

**Comment by jasontedor** [comment]
@elasticmachine update branch

**Pull request merged**
