### PR TITLE
Removes FieldStats API

### LINKED ISSUE #25577: Remove _field_stats endpoint
_field_stats endpoint has been deprecated in 5 and should be removed in 6.

### PR DESCRIPTION
**Pull request by colings86**
Closes #25577

### CODE REVIEW

**Review by jimczi — APPROVED** [review]
LGTM

**Comment by s1monw** [comment]
@colings86 @jimczi @clintongormley I think we can merge this now given https://github.com/elastic/kibana/pull/12814 and  #25658 /cc @epixa @spalger ?

**Comment by colings86** [comment]
@s1monw agreed, I just rebased to fix a merge conflict so as soon as the build passes I'll merge this

**Comment by s1monw** [comment]
@colings86 lets wait for thumbs-up from  @epixa or @spalger

**Comment by colings86** [comment]
ok will do

**Comment by epixa** [comment]
Thanks

Thumbs up

**Comment by colings86** [comment]
Thanks @epixa, this is now merged into master 😄

**Pull request merged**
