### PR TITLE
Adds pagination support to cat APIs and X-Total-Count header on response

### PR DESCRIPTION
**Pull request by dbbaughe**
This adds pagination support to _cat APIs along with X-Total-Count header.

Ideally I would of used from/size instead of from/limit, but size is already used by one of the _cat APIs.

Looking into the other APIs that support pagination, there seems to be a convention of allowing -1 as values to mean _no pagination_ (equivalent of not providing parameters), so this follows the same pattern. And similarly throws an IllegalArgumentException if it's -2 or less.

```
curl "localhost:9200/_cat/indices"
yellow open test_4 Mw4ss8WST8i3Ip9GYd4cDQ 1 1 0 0 283b 283b
yellow open test_3 r9nybkLLRAy9BOnSHY5haQ 1 1 0 0 283b 283b
yellow open test_2 oGaLXFiKQfi70cr1_JTFPA 1 1 0 0 283b 283b
yellow open test_1 poun91pISi2hcRvd5jSJsA 1 1 0 0 283b 283b
yellow open test_0 xFWp8cW5TcSB1TLI6Fd7pw 1 1 0 0 283b 283b
yellow open test_9 nExns3QRQh60MAzUDlPg9w 1 1 0 0 283b 283b
yellow open test_8 VvW51vHGTrqlii1EldUvKA 1 1 0 0 283b 283b
yellow open test_7 2De4AM40SauLU7FNjAEsfw 1 1 0 0 283b 283b
yellow open test_6 es2DStS6TZu4dboZT6783Q 1 1 0 0 283b 283b
yellow open test_5 Q8vDTS9iRF2klRm1VJFy1w 1 1 0 0 283b 283b

curl "localhost:9200/_cat/indices?from=3"
yellow open test_1 poun91pISi2hcRvd5jSJsA 1 1 0 0 283b 283b
yellow open test_0 xFWp8cW5TcSB1TLI6Fd7pw 1 1 0 0 283b 283b
yellow open test_9 nExns3QRQh60MAzUDlPg9w 1 1 0 0 283b 283b
yellow open test_8 VvW51vHGTrqlii1EldUvKA 1 1 0 0 283b 283b
yellow open test_7 2De4AM40SauLU7FNjAEsfw 1 1 0 0 283b 283b
yellow open test_6 es2DStS6TZu4dboZT6783Q 1 1 0 0 283b 283b
yellow open test_5 Q8vDTS9iRF2klRm1VJFy1w 1 1 0 0 283b 283b

curl "localhost:9200/_cat/indices?from=3&limit=2"
yellow open test_1 poun91pISi2hcRvd5jSJsA 1 1 0 0 283b 283b
yellow open test_0 xFWp8cW5TcSB1TLI6Fd7pw 1 1 0 0 283b 283b

curl "localhost:9200/_cat/indices?s=index"
yellow open test_0 xFWp8cW5TcSB1TLI6Fd7pw 1 1 0 0 283b 283b
yellow open test_1 poun91pISi2hcRvd5jSJsA 1 1 0 0 283b 283b
yellow open test_2 oGaLXFiKQfi70cr1_JTFPA 1 1 0 0 283b 283b
yellow open test_3 r9nybkLLRAy9BOnSHY5haQ 1 1 0 0 283b 283b
yellow open test_4 Mw4ss8WST8i3Ip9GYd4cDQ 1 1 0 0 283b 283b
yellow open test_5 Q8vDTS9iRF2klRm1VJFy1w 1 1 0 0 283b 283b
yellow open test_6 es2DStS6TZu4dboZT6783Q 1 1 0 0 283b 283b
yellow open test_7 2De4AM40SauLU7FNjAEsfw 1 1 0 0 283b 283b
yellow open test_8 VvW51vHGTrqlii1EldUvKA 1 1 0 0 283b 283b
yellow open test_9 nExns3QRQh60MAzUDlPg9w 1 1 0 0 283b 283b

curl "localhost:9200/_cat/indices?s=index&from=2"
yellow open test_2 oGaLXFiKQfi70cr1_JTFPA 1 1 0 0 283b 283b
yellow open test_3 r9nybkLLRAy9BOnSHY5haQ 1 1 0 0 283b 283b
yellow open test_4 Mw4ss8WST8i3Ip9GYd4cDQ 1 1 0 0 283b 283b
yellow open test_5 Q8vDTS9iRF2klRm1VJFy1w 1 1 0 0 283b 283b
yellow open test_6 es2DStS6TZu4dboZT6783Q 1 1 0 0 283b 283b
yellow open test_7 2De4AM40SauLU7FNjAEsfw 1 1 0 0 283b 283b
yellow open test_8 VvW51vHGTrqlii1EldUvKA 1 1 0 0 283b 283b
yellow open test_9 nExns3QRQh60MAzUDlPg9w 1 1 0 0 283b 283b

curl "localhost:9200/_cat/indices?s=index&from=2&limit=4"
yellow open test_2 oGaLXFiKQfi70cr1_JTFPA 1 1 0 0 283b 283b
yellow open test_3 r9nybkLLRAy9BOnSHY5haQ 1 1 0 0 283b 283b
yellow open test_4 Mw4ss8WST8i3Ip9GYd4cDQ 1 1 0 0 283b 283b
yellow open test_5 Q8vDTS9iRF2klRm1VJFy1w 1 1 0 0 283b 283b

curl "localhost:9200/_cat/indices?s=index&from=0"
yellow open test_0 xFWp8cW5TcSB1TLI6Fd7pw 1 1 0 0 283b 283b
yellow open test_1 poun91pISi2hcRvd5jSJsA 1 1 0 0 283b 283b
yellow open test_2 oGaLXFiKQfi70cr1_JTFPA 1 1 0 0 283b 283b
yellow open test_3 r9nybkLLRAy9BOnSHY5haQ 1 1 0 0 283b 283b
yellow open test_4 Mw4ss8WST8i3Ip9GYd4cDQ 1 1 0 0 283b 283b
yellow open test_5 Q8vDTS9iRF2klRm1VJFy1w 1 1 0 0 283b 283b
yellow open test_6 es2DStS6TZu4dboZT6783Q 1 1 0 0 283b 283b
yellow open test_7 2De4AM40SauLU7FNjAEsfw 1 1 0 0 283b 283b
yellow open test_8 VvW51vHGTrqlii1EldUvKA 1 1 0 0 283b 283b
yellow open test_9 nExns3QRQh60MAzUDlPg9w 1 1 0 0 283b 283b

curl "localhost:9200/_cat/indices?s=index&from=-1"
yellow open test_0 xFWp8cW5TcSB1TLI6Fd7pw 1 1 0 0 283b 283b
yellow open test_1 poun91pISi2hcRvd5jSJsA 1 1 0 0 283b 283b
yellow open test_2 oGaLXFiKQfi70cr1_JTFPA 1 1 0 0 283b 283b
yellow open test_3 r9nybkLLRAy9BOnSHY5haQ 1 1 0 0 283b 283b
yellow open test_4 Mw4ss8WST8i3Ip9GYd4cDQ 1 1 0 0 283b 283b
yellow open test_5 Q8vDTS9iRF2klRm1VJFy1w 1 1 0 0 283b 283b
yellow open test_6 es2DStS6TZu4dboZT6783Q 1 1 0 0 283b 283b
yellow open test_7 2De4AM40SauLU7FNjAEsfw 1 1 0 0 283b 283b
yellow open test_8 VvW51vHGTrqlii1EldUvKA 1 1 0 0 283b 283b
yellow open test_9 nExns3QRQh60MAzUDlPg9w 1 1 0 0 283b 283b

curl "localhost:9200/_cat/indices?s=index&from=-2"
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"[from] parameter cannot be negative, found [-2]"}],"type":"illegal_argument_exception","reason":"[from] parameter cannot be negative, found [-2]"},"status":400}

curl "localhost:9200/_cat/indices?s=index&limit=-2"
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"[limit] parameter cannot be negative, found [-2]"}],"type":"illegal_argument_exception","reason":"[limit] parameter cannot be negative, found [-2]"},"status":400}

curl "localhost:9200/_cat/indices?s=index&from=2&limit=4&format=yaml"
---
- health: "yellow"
  status: "open"
  index: "test_2"
  uuid: "oGaLXFiKQfi70cr1_JTFPA"
  pri: "1"
  rep: "1"
  docs.count: "0"
  docs.deleted: "0"
  store.size: "283b"
  pri.store.size: "283b"
- health: "yellow"
  status: "open"
  index: "test_3"
  uuid: "r9nybkLLRAy9BOnSHY5haQ"
  pri: "1"
  rep: "1"
  docs.count: "0"
  docs.deleted: "0"
  store.size: "283b"
  pri.store.size: "283b"
- health: "yellow"
  status: "open"
  index: "test_4"
  uuid: "Mw4ss8WST8i3Ip9GYd4cDQ"
  pri: "1"
  rep: "1"
  docs.count: "0"
  docs.deleted: "0"
  store.size: "283b"
  pri.store.size: "283b"
- health: "yellow"
  status: "open"
  index: "test_5"
  uuid: "Q8vDTS9iRF2klRm1VJFy1w"
  pri: "1"
  rep: "1"
  docs.count: "0"
  docs.deleted: "0"
  store.size: "283b"
  pri.store.size: "283b"

curl -i "localhost:9200/_cat/indices?s=index&from=2&limit=4"
HTTP/1.1 200 OK
X-Total-Count: 10
content-type: text/plain; charset=UTF-8
content-length: 240

yellow open test_2 oGaLXFiKQfi70cr1_JTFPA 1 1 0 0 283b 283b
yellow open test_3 r9nybkLLRAy9BOnSHY5haQ 1 1 0 0 283b 283b
yellow open test_4 Mw4ss8WST8i3Ip9GYd4cDQ 1 1 0 0 283b 283b
yellow open test_5 Q8vDTS9iRF2klRm1VJFy1w 1 1 0 0 283b 283b
```

### CODE REVIEW

**Comment by dbbaughe** [comment]
Hey @DaveCTurner,

Could you label this as ":Core/Features/CAT APIs", also looking for feedback to get this merged in.

Thanks,
Drew

**Comment by DaveCTurner** [comment]
@dbbaughe yep I've done that. However I don't understand the motivation for this change. I think the `cat` APIs do not yield enough information to make it worth implementing pagination. The only benefit I can think of is to save network traffic delivering the responses, but I can't really think of any conditions under which a client not want to paginate through the whole table. Also as implemented today you recalculate the table on each request, so a sequence of N requests to paginate through a whole table would require N times as much server-side work and would not yield a consistent sequence of pages so it wouldn't be very useful.

On the plus side, including tests with your PR is most welcome, thanks. If we were to proceed with this idea then we'd also require the docs to be updated. But that's a big "if" right now. I'm marking this for team discussion to get some more opinions.

**Comment by dbbaughe** [comment]
Hey @DaveCTurner,

The main motivation behind this change was for paginating over the cluster indices, but the change applies to all _cat APIs because of the location of the change (and it seems like it would benefit all _cat APIs). As you said, this benefits saved network traffic from the responses along with latency, mainly for large clusters that can have thousands of indices.

This came about while looking for a way to fill out a Kibana table with cluster indices, I noticed that it was not possible to pass from/size to the _cat API. I ended up looking at the OSS source for the Create Index Pattern on Kibana and noticed it was doing an expensive (for large clusters with a lot of documents) [_index aggregation](https://github.com/elastic/kibana/blob/master/src/legacy/core_plugins/kibana/public/management/sections/index_patterns/create_index_pattern_wizard/lib/get_indices.js#L57) to get back a list of unique indices in the cluster.  This was taking ~4 seconds per request (as you type in the input box) on a cluster with 50 billion documents. If this was moved to use _cat API with pagination support (which also supports index wildcard matching), then it would only need to iterate over each index (thousands at worst) and return a small subset based on the limit.

I could not find any other OSS examples of bringing back a list of indices, but I can see that you have [Elasticsearch Monitoring](https://www.elastic.co/what-is/elasticsearch-monitoring) which has a table of indices. If you're using the aggregation from Create Index Pattern or the _cat API, this seems to be waste of network bandwidth and an increase in latency for large clusters. Once adding something like auto refresh (which it looks like you have on the GIF) and the fact that a user can be looking at a page of 10 indices (out of thousands of indices), it seems like pagination would be useful.

As for recalculating the table on each request, that seems to be needed to provide accurate results. Requesting _cat/indices from=10/size=10 sorted by document count needs to calculate the table to provide the correct results. Going to the next page (i.e. from=20/size=10) would still need to recalculate as the last table calculation has become stale and indices could of moved around based on a provided sort field (or whatever the default sort is).

Definitely interested in hearing your opinions on this. As far as I can tell, this would have no impact on the current usage of _cat APIs while providing the ability to paginate.

Thanks,
Drew

**Comment by DaveCTurner** [comment]
I'm not sure exactly what optimisations are in place for a search that aggregates by `_index` like Kibana is doing there, but perhaps we can make that more efficient or come up with a different search that does the same thing. There is no need to retrieve pages after the first for this use case for this UI: a list of any 200 matching indices will do (and frankly 200 seems like a lot).

The `_cat` APIs are inappropriate for the table in the monitoring UI because this table shows data according to your currently-selected time range and yet there is no facility to obtain historical data from the `_cat` API.

> Going to the next page (i.e. from=20/size=10) would still need to recalculate as the last table calculation has become stale and indices could of moved around based on a provided sort field (or whatever the default sort is).

That's exactly my point.

**Comment by dakrone** [comment]
We discussed this and decided that for now, we'd rather not implement paging for cat APIs. The cat APIs are intended for human consumption, and they aren't intended to have consistent ordering for pagination between requests. If a human needs to paginate them, piping them into a file and paging with `less`/`more` is a better idea.

**Pull request closed without merging**
