### PR TITLE
Accept ingest simulate params as ints or strings

### PR DESCRIPTION
**Pull request by sneivandt**
Update Ingest simulate to accept _id, _index, _type, _routing and _parent as either strings or ints.

Issue #23823.

### CODE REVIEW

**Comment by talevy** [comment]
hey @sneivandt, apologies for the late response. these changes look good overall!
mind rebasing off latest `master` to resolve the newly created file conflicts?

Jenkins, please test this

**Comment by talevy** [comment]
@sneivandt thanks for the rebase. think you can add tests around this for `parseDocs`? either in the rest-spec tests or simulate unite tests

other than that, changes look good!

**Comment by talevy** [comment]
Hi @sneivandt sorry for the late response. I see you added tests (that I missed) Think you can rebase off the latest changes so that we can continue with your PR?

**Comment by sneivandt** [comment]
Hey @talevy take a look now. Should be up to date.

**Comment by talevy** [comment]
thanks @sneivandt. looks good! I'll just have our CI run through the checks

jenkins, please test this.

**Review by talevy — APPROVED** [review]
LGTM

**Pull request merged**
