### PR TITLE
Updating testing and logging for dense_vector dynamic dims

### PR DESCRIPTION
**Pull request by benwtrent**
This adds a test for dynamic dims update mapping merges.

Also, this adds logging to help investigate a periodically failing test.

related to: https://github.com/elastic/elasticsearch/issues/100502

### CODE REVIEW

**Comment by benwtrent** [comment]
jenkins retest this please

**Comment by benwtrent** [comment]
run elasticsearch-ci/1
run elasticsearch-ci/2
run elasticsearch-ci/3

**Comment by benwtrent** [comment]
run elasticsearch-ci/part-1
run elasticsearch-ci/part-2
run elasticsearch-ci/part-3

**Comment by benwtrent** [comment]
run elasticsearch-ci/part-1
run elasticsearch-ci/part-2
run elasticsearch-ci/part-3

**Comment by benwtrent** [comment]
run elasticsearch-ci/part-1
run elasticsearch-ci/part-2
run elasticsearch-ci/part-3

**Comment by benwtrent** [comment]
run elasticsearch-ci/part-1
run elasticsearch-ci/part-2
run elasticsearch-ci/part-3

**Comment by benwtrent** [comment]
please fail test! I need the logging!!!!

run elasticsearch-ci/part-1
run elasticsearch-ci/part-2
run elasticsearch-ci/part-3

**Review by mayya-sharipova — APPROVED** [review]
@benwtrent Thanks Ben!

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Pull request merged**
