### PR TITLE
Expose Japanese completion filter to kuromoji analysis plugin

### PR DESCRIPTION
**Pull request by mocobeta**
This adds analysis factories of JapaneseCompletionFilter and JapaneseCompletionAnalyzer  (https://issues.apache.org/jira/browse/LUCENE-10102) to kuromoji plugin.

This is expected to be used in combination with Completion Suggester. For example:

```
# working example (we are running this setting on 7.x)
"mappings": {
    "properties": {
      "suggest_ja": {
        "type": "completion",
        "analyzer": "kuromoji_completion_index",
        "search_analyzer": "kuromoji_completion_query",
        "preserve_separators": false,
        "preserve_position_increments": true,
        "max_input_length": 50
      },
      "suggest_en": {
        "type": "completion",
        "analyzer": "standard",
        "preserve_separators": false,
        "preserve_position_increments": true,
        "max_input_length": 50
      }
    }
  }
```

Or, for searching use-cases, this could be used as a replacement of kuromoji_readingform; though we have not used it for searching.

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by mocobeta** [comment]
I'd be happy if I could get your feedback.

**Comment by romseygeek** [comment]
@elasticmachine ok to test

**Review by romseygeek — APPROVED** [review]
Thanks @mocobeta, this looks great! Assuming that CI is happy I am good to merge this.

**Comment by romseygeek** [comment]
@elasticmachine update branch

**Comment by mocobeta** [comment]
Thanks for merging!

**Pull request merged**
