### PR TITLE
[ML] fixing MlJobSnapshotUpgradeIT.testSnapshotUpgrader test

### LINKED ISSUE #67059: Failure in MlJobSnapshotUpgradeIT.testSnapshotUpgrader
**Build scan**: https://gradle-enterprise.elastic.co/s/4uehhhrcq3vq4

**Repro line**: `./gradlew ':x-pack:qa:rolling-upgrade:v8.0.0#oldClusterTest' -Dtests.class="org.elasticsearch.upgrades.MlJobSnapshotUpgradeIT" -Dtests.method="testSnapshotUpgrader" -Dtests.seed=2958ACA06B5F0E77 -Dtests.security.manager=true -Dtests.bwc=true -Dtests.locale=fi -Dtests.timezone=SystemV/PST8 -Druntime.java=11`

**Applicable branches**: `master`

**Failure history**: once immediately after https://github.com/elastic/elasticsearch/pull/67037

**Failure excerpt**:

```
org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=x_content_parse_exception, reason=[1:401] [job_details] failed to parse field [analysis_config]]
at __randomizedtesting.SeedInfo.seed([2958ACA06B5F0E77:357BB5CF6C2AA5F9]:0) |  
  |   | •••
  |   | at org.elasticsearch.upgrades.MlJobSnapshotUpgradeIT.putJob(MlJobSnapshotUpgradeIT.java:279) |  
  |   | at org.elasticsearch.upgrades.MlJobSnapshotUpgradeIT.buildAndPutJob(MlJobSnapshotUpgradeIT.java:247) |  
  |   | at org.elasticsearch.upgrades.MlJobSnapshotUpgradeIT.createJobAndSnapshots(MlJobSnapshotUpgradeIT.java:190) |  
  |   | at org.elasticsearch.upgrades.MlJobSnapshotUpgradeIT.testSnapshotUpgrader(MlJobSnapshotUpgradeIT.java:99)
Caused by: org.elasticsearch.ElasticsearchException: Elasticsearch exception [type=status_exception, reason=categorization_field_name must be set for mlcategory to be available]
at org.elasticsearch.ElasticsearchException.innerFromXContent(ElasticsearchException.java:496) |  
  |   | •••
  |   | at org.elasticsearch.upgrades.MlJobSnapshotUpgradeIT.putJob(MlJobSnapshotUpgradeIT.java:279) |  
  |   | at org.elasticsearch.upgrades.MlJobSnapshotUpgradeIT.buildAndPutJob(MlJobSnapshotUpgradeIT.java:247) |  
  |   | at org.elasticsearch.upgrades.MlJobSnapshotUpgradeIT.createJobAndSnapshots(MlJobSnapshotUpgradeIT.java:190) |  
  |   | at org.elasticsearch.upgrades.MlJobSnapshotUpgradeIT.testSnapshotUpgrader(MlJobSnapshotUpgradeIT.java:99)
```

### PR DESCRIPTION
**Pull request by benwtrent**
fixes a minor typo that causes test flakiness.

closes https://github.com/elastic/elasticsearch/issues/67059

### CODE REVIEW

**Review by davidkyle — APPROVED** [review]
LGTM

**Comment by martijnvg** [comment]
The test that this pr fixes, also fails in 7.x and 7.11 branches: https://build-stats.elastic.co/app/kibana#/discover/0d588210-3843-11ea-a7eb-15e193b310ea?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-60d,mode:quick,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:e58bf320-7efd-11e8-bf69-63c8ef516157,key:project,negate:!f,params:(query:elasticsearch,type:phrase),type:phrase,value:elasticsearch),query:(match:(project:(query:elasticsearch,type:phrase))))),index:e58bf320-7efd-11e8-bf69-63c8ef516157,interval:auto,query:(language:lucene,query:'project:elasticsearch%20AND%20(branch:%227.x%22%20OR%20branch:%22master%22%20OR%20branch:%227.11%22%20OR%20branch:%227.10%22%20OR%20branch:%226.8%22)%20AND%20test:%22testSnapshotUpgrader%22'),sort:!(time,desc))

I think this fix should be backported to the 7.x and 7.11 branches. @benwtrent Do you think this as well?

**Comment by martijnvg** [comment]
Recent failure: https://gradle-enterprise.elastic.co/s/xmgtcufihtnde/tests/:x-pack:qa:rolling-upgrade:v6.8.14%23upgradedClusterTest/org.elasticsearch.upgrades.MlJobSnapshotUpgradeIT/testSnapshotUpgrader#1

**Comment by benwtrent** [comment]
> I think this fix should be backported to the 7.x and 7.11 branches. @benwtrent Do you think this as well?

The Backport PRs were in flight when the bug was found. So the backport PRs didn't suffer from the same problem (had the change applied while their PRs were opened). 

These failures seem like something completely different. I will open a new issue.

**Comment by benwtrent** [comment]
@martijnvg specifically, I think the two recent failures are the valid ones: 

```
ElasticsearchStatusException[Elasticsearch exception [type=exception, reason=Unexpected state [failed] while waiting for to be assigned to a node; recorded reason [[ml-snapshots-upgrade-job] autodetect process stopped unexpectedly: SubLevel mismatch in restore at b
Failed to restore CONTROLLER_OLD_TAG, got 1
Fatal error: 'si_signo 11, si_code: 1, si_errno: 0, address: 0x7ffb03edaf3e, library: /dev/shm/elastic+elasticsearch+7.11+matrix-java-periodic/ES_RUNTIME_JAVA/zulu11/nodes/general-purpose/distribution/archives/linux-tar/build/install/elasticsearch-7.11.0-SNAPSHOT/modules/x-pack-ml/platform/linux-x86_64/bin/../lib/libMlMaths.so, base: 0x7ffb038a2000, normalized address: 0x638f3e', version: 7.11.0-SNAPSHOT (build 9a819d67d56a96)
]]]
```

All the others seem to be caused by version bumps, or by this bug in master that is now fixed. I will open a new issue.

**Pull request merged**
