### PR TITLE
Update Painless AST Catch Node

### PR DESCRIPTION
**Pull request by jdconrad**
This makes two changes to the catch node:
1. Use SDeclaration to replace independent variable usage.
2. Use a DType to set a "minimum" exception type - this allows us to require users to continue using Exception as "minimum" type for catch blocks, but for us to internally catch Error/Throwable. This is a required step to removing custom try/catch blocks from SClass.

### CODE REVIEW

**Review by rjernst — APPROVED** [review]
LGTM. Can we please have a more specific commit message? This seems to give no more information than the fact the catch node is being changed, but not what is being changed.

**Comment by jdconrad** [comment]
@rjernst Thanks for the review. I usually change the commit message to the description from this issue when I push.

**Review by stu-elastic — APPROVED** [review]
lgtm

**Comment by jdconrad** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by jdconrad** [comment]
@stu-elastic Thanks for the review. Will commit once CI passes.

**Comment by jdconrad** [comment]
@elasticmachine run elasticsearch-ci/default-distro

**Pull request merged**
