### PR TITLE
SQL: Propagate a doc-value `format` with inner hits.

### PR DESCRIPTION
**Pull request by jpountz**
While sql passes a doc-value `format` when asking for doc-value fields, it
doesn't do it when asking for fields via inner hits. This change makes inner
hits use `epoch_millis` for dates and the default based on mappings otherwise,
like SQL does for docvalue_fields otherwise.

### CODE REVIEW

**Review by costin — APPROVED** [review]
LGTM. Thanks for the PR and apologies it took so long to review it.

**Comment by jpountz** [comment]
Thanks @costin !

**Review by astefan — APPROVED** [review]
LGTM

**Review by matriv — APPROVED** [review]
LGTM

**Comment by jpountz** [comment]
@elasticmachine run the gradle build tests 2 and run the sample packaging tests

**Pull request merged**
