### PR TITLE
[7.x] [DOCS] Add index alias conversion to data stream setup docs (#65979)

### PR DESCRIPTION
**Pull request by jrodewig**
Backports the following commits to 7.x:
 - [DOCS] Add index alias conversion to data stream setup docs (#65979)

### CODE REVIEW

**Comment by jrodewig** [comment]
Depends on 7.x backport of #65017.

**Comment by jrodewig** [comment]
@elasticmachine ok to test

**Comment by jrodewig** [comment]
:doh:

@elasticmachine update branch

**Comment by jrodewig** [comment]
@elasticmachine update branch

**Comment by andreidan** [comment]
Added the `7.11.0` label so we don't forget to backport it to the `7.11` branch too (as the feature was is present there)

**Comment by jrodewig** [comment]
@elasticmachine update branch

**Pull request merged**
