### PR TITLE
[ML] Make categorize_text aggregation GA

### PR DESCRIPTION
**Pull request by droberts195**
Removes the experimental tag from the categorize_text aggregation.

### CODE REVIEW

**Review by dimitris-athanasiou — APPROVED** [review]
LGTM

**Comment by droberts195** [comment]
We've decided to do this in 8.5 instead of 8.4.

**Comment by droberts195** [comment]
Postponing again, to 8.6 now

**Comment by droberts195** [comment]
@elasticmachine update branch

**Pull request merged**
