### PR TITLE
Clarify RemoteClusterService#groupIndices behaviour

### PR DESCRIPTION
**Pull request by javanna**
When executing a cross-cluster search, we need to search against all local indices (and no remote indices) in case no indices are specified. Also, if only remote indices are specified, no local indices will be queried. We previously added empty local indices whenever they were not present in the map of the grouped indices, then we would act differently later based on the extracted remote indices. Instead, we now add the empty array for local indices only in case we need to search all local indices; the entry for local indices is not added when local indices should not be searched. This way the grouped indices reflect reality and provide a better indication of what indices will be searched.

### CODE REVIEW

**Comment by javanna** [comment]
retest this please

**Comment by javanna** [comment]
retest this please

**Review by jimczi — APPROVED** [review]
LGTM

**Comment by javanna** [comment]
thanks @jimczi !

**Comment by javanna** [comment]
cc @martijnvg I double checked and I think this change does not affect CCR as it modifies `RemoteClusterService#groupIndices` rather than `RemoteClusterAware#groupClusterIndices` which is called by both `groupIndices` and CCR. So the green tests were not a lie ;)

**Pull request merged**
