### PR TITLE
Deprecate EOL'ed Ubuntu 15.04 from Vagrantfile

### PR DESCRIPTION
**Pull request by dliappis**
This PR references issue https://github.com/elastic/elasticsearch/issues/20920

### CODE REVIEW

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by jasontedor** [comment]
Thanks @dliappis! For future reference, PRs do not need corresponding issues; you can just open the PR directly and give the reasoning in the commit message/PR body. If a corresponding issue exists, great, but no need to create one. :smile:

**Comment by nik9000** [comment]
Also remove from `qa/vagrant/build.gradle`?

**Comment by jasontedor** [comment]
> Also remove from `qa/vagrant/build.gradle`?

Oh, good catch @nik9000.

**Comment by jasontedor** [comment]
@dliappis When this is ready, are you going to do the merge and backport dance, or would you like us to?

**Review by nik9000 — APPROVED** [review]

**Comment by dliappis** [comment]
@nik9000 Good catch, I fixed lingering references via https://github.com/elastic/elasticsearch/pull/20921/commits/eece4517cba2e90ef6c50d06f23639a2575c3a3d also part of TESTING.asciidoc.

@jasontedor I would like to do the merge/backport dance at least once myself! I will probably need some handholding on the preferred procedure (squash+merge I believe), but will reach out for the details on that.

Thank you!

**Comment by jasontedor** [comment]
> I would like to do the merge/backport dance at least once myself!

:tada:

> I will probably need some handholding on the preferred procedure (squash+merge I believe), but will reach out for the details on that.

Yes, squash and merge is preferred. I like to modify the commit message to refer to the PR (I usually put Relates #20291 at the bottom of the commit message). This is so that people looking at git annotations can immediately find the PR that a commit was derived from, and so that backport commits automatically appear in the GitHub UI linked to the PR. I'm happy to guide as needed.

**Pull request merged**
