### PR TITLE
Align cat thread pool info to thread pool config

### PR DESCRIPTION
**Pull request by jasontedor**
Today we report thread pool info using a common object. This means that we use a shared set of terminology that is not consistent with the terminology used to the configure thread pools. This holds in particular for the minimum and maximum number of threads in the thread pool where we use the following terminology:
```
 thread pool info | fixed | scaling
  min                core    size
  max                max     size
```

A previous change addressed this for the nodes info API. This commit changes the display of thread pool info in the cat thread pool API too to be dependent on the type of the thread pool so that we can align the terminology in the output of thread pool info with the terminology used to configure a thread pool.

Relates #29123

### CODE REVIEW

**Comment by jasontedor** [comment]
I would like to integrate this change, then I will update the docs change in #29192 to reflect the changes here too.

**Review by spinscale — CHANGES_REQUESTED** [review]
there is a `docs/reference/cat/thread_pool.asciidoc`, that refers to the `size` parameter. I am not sure if we should maintain the fields in the docs, because that's what the help is for - maybe just get rid of that table?

**Comment by jasontedor** [comment]
Thanks @spinscale, I have updated the docs. For now I elect to keep the table and we can consider removing it in a follow-up separate from this change as I think making such a change to the docs should be more visible. Would you take another look?

**Review by spinscale — APPROVED** [review]
LGTM

**Comment by jasontedor** [comment]
Thanks @spinscale.

**Pull request merged**
