### PR TITLE
Fold BaseFuture into PlainActionFuture

### PR DESCRIPTION
**Pull request by DaveCTurner**
Following #93145 and #93146, a `PlainActionFuture` is now just a `BaseFuture` plus a few utility `actionGet(...)` methods. The only (non-test) subclass of `BaseFuture` that doesn't inherit these methods is `ListenableFuture`, and there's no problem with adding them there, so this commit makes `ListenableFuture` inherit from `PlainActionFuture` and folds the now-unnecessary `BaseFuture` into `PlainActionFuture`.

### CODE REVIEW

**Comment by DaveCTurner** [comment]
> this commit makes `ListenableFuture` inherit from `PlainActionFuture`

This introduces some tension because after this change `ListenableFuture` and `ListenableActionFuture` are both `ActionFuture` derivatives. IMO these names are just awful, these two things are _almost_ the same as each other, except for a few subtle yet meaningful differences that mean we can't just replace either one with the other.

**Comment by DaveCTurner** [comment]
@elasticmachine update branch

**Comment by DaveCTurner** [comment]
The assertions added in #93187 show us that in fact we will be able to replace `ListenableActionFuture` with `ListenableFuture` in due course. Not done here, but it'll be a great followup.

**Review by original-brownbear — APPROVED** [review]
LGTM, nice :)

**Pull request merged**
