### PR TITLE
Properly mark reindex's child tasks as child tasks

### PR DESCRIPTION
**Pull request by nik9000**
They weren't being marked before.

### CODE REVIEW

**Comment by nik9000** [comment]
@imotov I'm wondering why all ActionRequests don't support setParentTaskId. It is kind of hard to know up front if your task is going to be part of a request.

If we did that we'd probably want to make the serialization for empty task ids smaller.

**Comment by nik9000** [comment]
I'm going to rework this after #17872.

**Comment by nik9000** [comment]
> I'm going to rework this after #17872.

Done. Running tests against it now but all is looking good.

**Comment by imotov** [comment]
LGTM

**Comment by nik9000** [comment]
Thanks for reviewing @imotov !

**Pull request merged**
