### PR TITLE
 Migrate Streamable to Writeable for cluster block package

### PR DESCRIPTION
**Pull request by liketic**
Migrate Streamable to Writeable for cluster block package. 

Relates to #34389

### CODE REVIEW

**Review by jdconrad — APPROVED** [review]
LGTM

**Comment by jdconrad** [comment]
@liketic Would you please resolve the conflicts and commit once that is done?  Thanks!

**Comment by liketic** [comment]
@jdconrad Please review again.

**Comment by jdconrad** [comment]
@elasticmachine please test this

**Comment by jdconrad** [comment]
@elasticmachine test this

**Comment by jdconrad** [comment]
@elasticmachine test this please

**Comment by jdconrad** [comment]
@liketic Thank you for the contribution!

**Comment by javanna** [comment]
@jdconrad can you add version labels? I guess it would be good if this went to 7.x as well?

**Comment by danielmitterdorfer** [comment]
As @jdconrad is out at the moment, I went ahead, added the labels on his behalf and also created https://github.com/elastic/elasticsearch/pull/39236 to backport this to `7.x`.

**Comment by javanna** [comment]
++ thanks @danielmitterdorfer !

**Comment by jdconrad** [comment]
@danielmitterdorfer Realize this is a bit late -- thanks for backporting!

**Comment by danielmitterdorfer** [comment]
No worries @jdconrad. You're welcome. :)

**Pull request merged**
