### PR TITLE
it's a `noop` operation, not a `none` operation.

### PR DESCRIPTION
**Pull request by adrinjalali**

### CODE REVIEW

**Comment by nik9000** [comment]
Thanks @adrinjalali. This looks good to me. I'll merge now and backport as appropriate.

**Comment by nik9000** [comment]
Actually it "works" because we don't hit that branch. It'd be nice to have the docs hit the branch and then the build would catch this.

**Comment by nik9000** [comment]
2.4: 97e1cbbb31780cc457475d202a96646c69096adb
5.0: c42384d8059bd57ab0dd8554111190b679a87116
5.x: ba870354de36290c4052c203b4c08f24d731f3a3
master: 7f77214cedbc927347241670be140b54185752c6

**Comment by jasontedor** [comment]
I'm don't think this change is correct. See for example [UpdateHelper.java](https://github.com/elastic/elasticsearch/blob/67f02363cebf1f6cb3e18fd5beea27ebc8d2a605/core/src/main/java/org/elasticsearch/action/update/UpdateHelper.java#L111). Can you please double check @nik9000?

**Comment by adrinjalali** [comment]
@jasontedor could it be the case that the code there is also a typo? I couldn't easily find other instances of using "none" as an operation in the code, and it's mostly refered to as "noop". Also, in the [update by query API](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/docs-update-by-query.html) `nope` is explicitly mentioned as the desired operation type.

**Comment by jasontedor** [comment]
It's not a typo in the comment, the string `"none"` is explicitly parsed from the op (search the rest of the source file that I linked to for `"none"`)

**Comment by adrinjalali** [comment]
Ok, fair enought. I see that in that file the operation is looked for as `none`. But there are two things which confused me:

1. The operation is the update by query API is explicitly refered to as `noop`. So I'd expect that would be the same for update API.
2. The operations in the code are mostly refered to as `noop` operation, and not `none` operation, eventhough `none` is the string that the given operation is compared to in some cases.

I was just hoping we could have one operation in the code and everywhere in the documentation.

**Comment by nik9000** [comment]
Yeah, @jasontedor's right. Here it is indeed called `none`. I'll revert the change.

@adrinjalali is right that we call it `noop` everywhere else. Which is why I got confused.

**Comment by nik9000** [comment]
Reverted with:
2.4: a0aa582bdaa769fa4d81085e55c964ecce9ebacb
5.0: d322c3a20655d2167c4768342f9eaee6b799c441
5.1: d852676ef87773aca0ced5d7e24ae6a9c8ff9a0d
5.x: e4688d94490e7ff6c1bb1884f815639a45147b69
master: 76a804e589d66562c5e0a5a0d64eca46a1780ad1

**Comment by jasontedor** [comment]
Thanks @nik9000.

**Pull request merged**
