### PR TITLE
Use historical features for Yaml REST tests for bulk api

### PR DESCRIPTION
**Pull request by mosche**
Use historical features for Yaml REST tests for bulk api

### CODE REVIEW

**Review by ldematte — APPROVED** [review]
LGTM once CI passes

**Comment by mosche** [comment]
@elasticmachine update branch

**Comment by mosche** [comment]
@elasticmachine update branch

**Comment by mosche** [comment]
Remaining failure is unrelated, merging
```
elasticsearch-ci/8.10.1 / bwc
Test failures:
DataTierMixedIT » testMixedTierCompatibility
```

**Pull request merged**
