### PR TITLE
Add Tracing APM integration test

### PR DESCRIPTION
**Pull request by pgomulka**
this commit adds an integration test where ES is run with
apm-java-agent and sending traces.
Traces are then received by a fake http server and could be asserted on.

### CODE REVIEW

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by pgomulka** [comment]
@elasticmachine update branch

**Comment by pugnascotia** [comment]
Are you intending to delete the old APM integration tests separately, then?

**Review by pugnascotia — APPROVED** [review]

**Comment by pgomulka** [comment]
> Are you intending to delete the old APM integration tests separately, then?

I wasn't planning to remove it yet. I think we should rewrite it into something that can be deployed in QA as an e2e test.
I don't know what kind of test would it be though

**Review by stu-elastic — APPROVED** [review]
lgtm

**Pull request merged**
