### PR TITLE
Use activeShards to get all active shards

### PR DESCRIPTION
**Pull request by mrkm4ntr**
No need to iterate over shard routings.

### CODE REVIEW

**Comment by henningandersen** [comment]
@elasticmachine test this please

**Comment by mrkm4ntr** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by henningandersen** [comment]
@elasticmachine update branch

**Comment by henningandersen** [comment]
@elasticmachine test this please

**Comment by henningandersen** [comment]
@mrkm4ntr, this change makes sense to me, thanks for your contribution (and sorry for the delay).

**Pull request merged**
