### PR TITLE
REST : deprecate `field_data` for Clear Indices Cache API

### PR DESCRIPTION
**Pull request by olcbean**
Throughout the code and the documentation `fielddata` is used. Only for the Clear Indices Cache API `field_data` has been used : 
https://github.com/elastic/elasticsearch/blob/95a13ea01cfefac372e0d1b69de595b9aac0d603/server/src/main/java/org/elasticsearch/rest/action/admin/indices/RestClearIndicesCacheAction.java#L104
 ( if `fielddata` is used as a url param, a deprecation warning is logged and also returned in the response headers ) 

Also the [reference docs](https://github.com/elastic/elasticsearch/blob/95a13ea01cfefac372e0d1b69de595b9aac0d603/docs/reference/indices/clearcache.asciidoc) are referring only to `fielddata`.

For consistency reasons this PR deprecates ` field_data` in favor of `fielddata`.

---
For context,  a few usages of `fielddata` :
```
GET /_cat/fielddata
```
```
GET /_nodes/stats/indices/fielddata
```
Index setting : `index.fielddata.cache`

---
The change from `fielddata` to `field_data` has been done in e2c8ff92ba1f49b4314cba35c5792a74fe4efe20 ( at this point the two names were interchangeable : no deprecation logging ) 

Since b927cfe1de6f573f443ebd58f492b759cf939093 (#17804) a http warning header is sent for the deprecated usage

### CODE REVIEW

**Comment by jasontedor** [comment]
FYI @elastic/es-core-infra.

**Comment by nik9000** [comment]
Makes sense to me.

@olcbean, could you add a yaml test for this API that just calls it with the new parameter to make sure the new preferred name? That'd make sure that we parse it and should be quite quick.

I think the right thing to do is, once this is ready, to merge it to master and 6.x and, in a followup, remove the now-deprecated name. @olcbean, would you like to do the follow-up?

@elasticmachine, test this please.

**Comment by javanna** [comment]
do we want to deprecate in 6.x and remove in 7.0? If so the migrate guide has to be updated.

**Comment by olcbean** [comment]
Hm... 
When a param is removed it should be documented ( in the followup PR )
In some cases when a deprecation is introduced, it is also documented. But I am not sure when. 

The question is how to handle the docs ? Should I add a deprecation msg and if so, if I open the PR against master I do not have access to the 6.x migration docs ... I see two possible ways to proceed.
* no deprecation note 
* open a separate migration doc PR against 6.x ( once this PR is backported to 6.x )

**Comment by olcbean** [comment]
@nik9000 @javanna thanks for the reviews!
The PR is ready for another round ;)

**Comment by nik9000** [comment]
> When a param is removed it should be documented ( in the followup PR )

We'll generate a changes list automatically. The script should pick up anything with `breaking` and `deprecation` labels and group them into the right section.

**Comment by nik9000** [comment]
@elasticmachine, test this please

**Review by nik9000 — APPROVED** [review]

**Comment by spinscale** [comment]
I have pushed 9f2c4df94d98eed886ad283c1348d6528bc2af11 to fix failing tests until the backport is done.

**Comment by nik9000** [comment]
> I have pushed 9f2c4df to fix failing tests until the backport is done.

I pushed the backport and reverted this. Sorry for the noise.

**Pull request merged**
