### PR TITLE
[DOCS] Add basic EQL search tutorial docs

### PR DESCRIPTION
**Pull request by jrodewig**
Adds a basic tutorial and example for performing an EQL search.

I plan to add additional sections (specifying timestamp/event type, joins, pagination) with
future PRs. See #51057.

Also adds missing `experimental::[]` macro to the EQL requirements page.

### CODE REVIEW

**Comment by jrodewig** [comment]
This will fail CI until #51537 is merged.

**Comment by jrodewig** [comment]
@elasticmachine update branch

**Review by rw-access — APPROVED** [review]

**Review by aleksmaus — APPROVED** [review]
Thank you!

**Comment by jrodewig** [comment]
### Backport commits
master be8ae97
7.x 20453d3ac84

**Pull request merged**
