### PR TITLE
FIx misleading repository-s3 type

### PR DESCRIPTION
**Pull request by jeanfabrice**
in 8.x, `repository-s3` type has been replaced by `s3` type. Fixing remaining reference to `repository-s3` in the documentation.

### CODE REVIEW

**Comment by leemthompo** [comment]
@DaveCTurner probably can confirm this is correct?

**Review by leemthompo — APPROVED** [review]
LGTM!

**Review by DaveCTurner — COMMENTED** [review]
Could we use the phrase "`s3` repository type" rather than just "`s3` type"? Otherwise LGTM

**Comment by jeanfabrice** [comment]
Done! thank you @DaveCTurner

**Review by DaveCTurner — APPROVED** [review]
LGTM thanks @jeanfabrice

**Pull request merged**
