### PR TITLE
[DOCS] Add 8.0.1 release notes

### PR DESCRIPTION
**Pull request by salvatore-campagna**
Updating docs for version 8.0.1 BC2.

### Preview
https://elasticsearch_84213.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/8.0/release-notes-8.0.1.html

### CODE REVIEW

**Comment by jrodewig** [comment]
Thanks @salvatore-campagna.

Since 8.0.1 is a patch release, we don't need to make any updates to the 8.0 release highlights or the migration guide. I undid those changes with https://github.com/elastic/elasticsearch/pull/84213/commits/ca45f13f31162c9434b2f6f5d9ecc1de5c356672.

I also pushed https://github.com/elastic/elasticsearch/pull/84213/commits/5d5d744638f1cf6d82a43344b7cd7515592b4c46, which contains my edits to the 8.0.1 release notes.

Before we merge this in, I'd like to get a review from @elastic/mlr-docs for the ML-related sections.

I'll also close https://github.com/elastic/elasticsearch/pull/84211 since those changes are now incorporated into this PR.

**Review by jrodewig — APPROVED** [review]
LGTM.

**Review by lcawl — APPROVED** [review]
MLR PRs LGTM, thanks!

**Comment by salvatore-campagna** [comment]
@jrodewig I see you added labels `8.1.1` and `8.2.0`. According to this: https://github.com/elastic/elasticsearch-team/blob/master/onboarding-and-how-we-work/release/elasticsearch-release-manager.md#raise-a-pr ("Once the PR is merged, you need to cherry-pick it to any later branches in the same major version only") I understand after merging this PR I need to cherry pick the commit into branch `8.1` and `8.2`. I guess, anyway, also label `8.1.0` is required because the cherry-pick I will do into branch `8.1` will also affect the next `8.1.0` BC. Right?

**Comment by jrodewig** [comment]
> I understand after merging this PR I need to cherry pick the commit into branch 8.1 and 8.2.

Yes. We'll need to forward-port this to the `8.1` and `master` (8.2) branches. You can use the `auto-backport` labels or the [backport tool](https://github.com/sqren/backport) to handle those if wanted.

> I guess, anyway, also label 8.1.0 is required because the cherry-pick I will do into branch 8.1 will also affect the next 8.1.0 BC. Right?

Docs-only changes, like this PR, don't affect our build candidates. Any 8.1 label will work, but I typically use the latest one (`8.1.1` in this case).

**Comment by salvatore-campagna** [comment]
@jrodewig so the reason why we don't do `auto-backport-and-merge` is that we need to wait for release time and not merging when this PR is merged, right?

**Comment by jrodewig** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|master|[](https://github.com/elastic/elasticsearch/pull/84292)|
|✅|8.1|[](https://github.com/elastic/elasticsearch/pull/84293)|


### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
