### PR TITLE
Add scripting, unmapped, supported-type tests to Boxplot

### PR DESCRIPTION
**Pull request by polyfractal**
These were added in https://github.com/elastic/elasticsearch/pull/53132, but I forgot to merge them to master first :scream: 

Adds some unit tests for scripting, unmapped fields and "supported types"

### CODE REVIEW

**Review by andyb-elastic — APPROVED** [review]
LGTM

Only thing I'd suggest (maybe in another pr since these are already on the feature branch) is testing the `missing` parameter with a field that is mapped, I think all the ones here use an unmapped field

**Comment by polyfractal** [comment]
Ooh good catch, didn't notice that.  I'll go ahead and add to this PR

**Comment by polyfractal** [comment]
@elasticmachine update branch

**Review by imotov — COMMENTED** [review]
For some reason I thought these are not needed for this aggregation since we are testing these code paths already in a few others. But I guess I could have messed up handling here. So, good catch!

**Comment by polyfractal** [comment]
Yah, it's mostly that we're just dotting i's and crossing t's to make sure the VS refactor, when it merges, doesn't change anything that we didn't expect.  So trying to add test parity across all the aggs ahead of time to prevent any surprises :)

**Pull request merged**
