### PR TITLE
Don't be lenient if JarHell is found

### LINKED ISSUE #13404: Remove intellij jar hell leniency
Its confusing to people that we are lenient to jar hell when running under intellij: thats totally an intellij bug, but by allowing it, people think that jar hell check is "optional" or that we don't execute it in tests, which we totally do in maven and jenkins.

This leniency needs to be removed.

### PR DESCRIPTION
**Pull request by s1monw**
Closes #13404

### CODE REVIEW

**Comment by s1monw** [comment]
running this patch with IntelliJ 14 passes without a jarhell. I think 13 is still broken but hey, we have to move on...

**Comment by jpountz** [comment]
LGTM. Great to remove exceptions.

**Comment by dadoonet** [comment]
@s1monw @rmuir When I run RestIT tests for plugins from IntelliJ I'm getting JarHell issue.
Is it expected?
Should I change something in the IDE?

Running `jvm-example` plugin tests for example gives me:

```
/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/bin/java -ea -Didea.launcher.port=7532 "-Didea.launcher.bin.path=/Applications/IntelliJ IDEA 14.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Applications/IntelliJ IDEA 14.app/Contents/lib/idea_rt.jar:/Applications/IntelliJ IDEA 14.app/Contents/plugins/junit/lib/junit-rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/tools.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Users/dpilato/Documents/Elasticsearch/dev/es-master/elasticsearch/plugins/jvm-example/target/test-classes:/Users/dpilato/Documents/Elasticsearch/dev/es-master/elasticsearch/plugins/jvm-example/target/classes:/Users/dpilato/.m2/repository/org/hamcrest/hamcrest-all/1.3/hamcrest-all-1.3.jar:/Users/dpilato/.m2/repository/org/apache/lucene/lucene-test-framework/5.4.0-snapshot-1702855/lucene-test-framework-5.4.0-snapshot-1702855.jar:/Users/dpilato/.m2/repository/org/apache/lucene/lucene-codecs/5.4.0-snapshot-1702855/lucene-codecs-5.4.0-snapshot-1702855.jar:/Users/dpilato/.m2/repository/com/carrotsearch/randomizedtesting/randomizedtesting-runner/2.2.0-snapshot-pr202/randomizedtesting-runner-2.2.0-snapshot-pr202.jar:/Users/dpilato/.m2/repository/junit/junit/4.11/junit-4.11.jar:/Users/dpilato/.m2/repository/org/apache/ant/ant/1.8.2/ant-1.8.2.jar:/Users/dpilato/Documents/Elasticsearch/dev/es-master/elasticsearch/core/target/test-classes:/Users/dpilato/.m2/repository/org/hdrhistogram/HdrHistogram/2.1.6/HdrHistogram-2.1.6.jar:/Users/dpilato/Documents/Elasticsearch/dev/es-master/elasticsearch/core/target/classes:/Users/dpilato/.m2/repository/org/apache/lucene/lucene-core/5.4.0-snapshot-1702855/lucene-core-5.4.0-snapshot-1702855.jar:/Users/dpilato/.m2/repository/org/apache/lucene/lucene-backward-codecs/5.4.0-snapshot-1702855/lucene-backward-codecs-5.4.0-snapshot-1702855.jar:/Users/dpilato/.m2/repository/org/apache/lucene/lucene-analyzers-common/5.4.0-snapshot-1702855/lucene-analyzers-common-5.4.0-snapshot-1702855.jar:/Users/dpilato/.m2/repository/org/apache/lucene/lucene-queries/5.4.0-snapshot-1702855/lucene-queries-5.4.0-snapshot-1702855.jar:/Users/dpilato/.m2/repository/org/apache/lucene/lucene-memory/5.4.0-snapshot-1702855/lucene-memory-5.4.0-snapshot-1702855.jar:/Users/dpilato/.m2/repository/org/apache/lucene/lucene-highlighter/5.4.0-snapshot-1702855/lucene-highlighter-5.4.0-snapshot-1702855.jar:/Users/dpilato/.m2/repository/org/apache/lucene/lucene-queryparser/5.4.0-snapshot-1702855/lucene-queryparser-5.4.0-snapshot-1702855.jar:/Users/dpilato/.m2/repository/org/apache/lucene/lucene-sandbox/5.4.0-snapshot-1702855/lucene-sandbox-5.4.0-snapshot-1702855.jar:/Users/dpilato/.m2/repository/org/apache/lucene/lucene-suggest/5.4.0-snapshot-1702855/lucene-suggest-5.4.0-snapshot-1702855.jar:/Users/dpilato/.m2/repository/org/apache/lucene/lucene-misc/5.4.0-snapshot-1702855/lucene-misc-5.4.0-snapshot-1702855.jar:/Users/dpilato/.m2/repository/org/apache/lucene/lucene-join/5.4.0-snapshot-1702855/lucene-join-5.4.0-snapshot-1702855.jar:/Users/dpilato/.m2/repository/org/apache/lucene/lucene-grouping/5.4.0-snapshot-1702855/lucene-grouping-5.4.0-snapshot-1702855.jar:/Users/dpilato/.m2/repository/org/apache/lucene/lucene-spatial/5.4.0-snapshot-1702855/lucene-spatial-5.4.0-snapshot-1702855.jar:/Users/dpilato/.m2/repository/org/apache/lucene/lucene-spatial3d/5.4.0-snapshot-1702855/lucene-spatial3d-5.4.0-snapshot-1702855.jar:/Users/dpilato/.m2/repository/org/apache/lucene/lucene-expressions/5.4.0-snapshot-1702855/lucene-expressions-5.4.0-snapshot-1702855.jar:/Users/dpilato/.m2/repository/org/antlr/antlr4-runtime/4.5/antlr4-runtime-4.5.jar:/Users/dpilato/.m2/repository/org/ow2/asm/asm/5.0.4/asm-5.0.4.jar:/Users/dpilato/.m2/repository/org/ow2/asm/asm-commons/5.0.4/asm-commons-5.0.4.jar:/Users/dpilato/.m2/repository/com/spatial4j/spatial4j/0.4.1/spatial4j-0.4.1.jar:/Users/dpilato/.m2/repository/com/vividsolutions/jts/1.13/jts-1.13.jar:/Users/dpilato/.m2/repository/com/github/spullara/mustache/java/compiler/0.8.13/compiler-0.8.13.jar:/Users/dpilato/.m2/repository/com/google/guava/guava/18.0/guava-18.0.jar:/Users/dpilato/.m2/repository/com/carrotsearch/hppc/0.7.1/hppc-0.7.1.jar:/Users/dpilato/.m2/repository/joda-time/joda-time/2.8.2/joda-time-2.8.2.jar:/Users/dpilato/.m2/repository/org/joda/joda-convert/1.2/joda-convert-1.2.jar:/Users/dpilato/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.5.3/jackson-core-2.5.3.jar:/Users/dpilato/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-smile/2.5.3/jackson-dataformat-smile-2.5.3.jar:/Users/dpilato/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.5.3/jackson-dataformat-yaml-2.5.3.jar:/Users/dpilato/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.5.3/jackson-databind-2.5.3.jar:/Users/dpilato/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.5.0/jackson-annotations-2.5.0.jar:/Users/dpilato/.m2/repository/org/yaml/snakeyaml/1.12/snakeyaml-1.12.jar:/Users/dpilato/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-cbor/2.5.3/jackson-dataformat-cbor-2.5.3.jar:/Users/dpilato/.m2/repository/io/netty/netty/3.10.3.Final/netty-3.10.3.Final.jar:/Users/dpilato/.m2/repository/com/ning/compress-lzf/1.0.2/compress-lzf-1.0.2.jar:/Users/dpilato/.m2/repository/com/tdunning/t-digest/3.0/t-digest-3.0.jar:/Users/dpilato/.m2/repository/commons-cli/commons-cli/1.3.1/commons-cli-1.3.1.jar:/Users/dpilato/.m2/repository/org/codehaus/groovy/groovy-all/2.4.4/groovy-all-2.4.4-indy.jar:/Users/dpilato/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar:/Users/dpilato/.m2/repository/log4j/apache-log4j-extras/1.2.17/apache-log4j-extras-1.2.17.jar:/Users/dpilato/.m2/repository/org/slf4j/slf4j-api/1.6.2/slf4j-api-1.6.2.jar:/Users/dpilato/.m2/repository/net/java/dev/jna/jna/4.1.0/jna-4.1.0.jar:/Users/dpilato/.m2/repository/org/apache/httpcomponents/httpclient/4.3.6/httpclient-4.3.6.jar:/Users/dpilato/.m2/repository/org/apache/httpcomponents/httpcore/4.3.3/httpcore-4.3.3.jar:/Users/dpilato/.m2/repository/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar:/Users/dpilato/.m2/repository/commons-codec/commons-codec/1.6/commons-codec-1.6.jar" com.intellij.rt.execution.application.AppMain com.intellij.rt.execution.junit.JUnitStarter -ideVersion5 org.elasticsearch.plugin.example.JvmExampleRestIT
[2015-09-21 17:24:49,039][WARN ][org.elasticsearch.bootstrap] Unable to lock JVM Memory: error=78,reason=Function not implemented
[2015-09-21 17:24:49,041][WARN ][org.elasticsearch.bootstrap] This can result in part of the JVM being swapped out.

java.lang.RuntimeException: Error collecting parameters from: public static java.lang.Iterable org.elasticsearch.plugin.example.JvmExampleRestIT.parameters() throws java.io.IOException,org.elasticsearch.test.rest.parser.RestTestParseException
	at com.carrotsearch.randomizedtesting.RandomizedRunner.collectFactoryParameters(RandomizedRunner.java:1514)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.collectTestCandidates(RandomizedRunner.java:1341)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.<init>(RandomizedRunner.java:394)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:29)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:21)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:26)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:41)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.ExceptionInInitializerError
	at org.elasticsearch.test.ESTestCase.<clinit>(ESTestCase.java:103)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.collectFactoryParameters(RandomizedRunner.java:1508)
	... 20 more
Caused by: java.lang.RuntimeException: found jar hell in test classpath
	at org.elasticsearch.bootstrap.BootstrapForTesting.<clinit>(BootstrapForTesting.java:64)
	... 26 more
Caused by: java.lang.IllegalStateException: jar hell!
class: jdk.packager.services.UserJvmOptionsService
jar1: /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/ant-javafx.jar
jar2: /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/packager.jar
	at org.elasticsearch.bootstrap.JarHell.checkClass(JarHell.java:248)
	at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:152)
	at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:87)
	at org.elasticsearch.bootstrap.BootstrapForTesting.<clinit>(BootstrapForTesting.java:62)
	... 26 more


Process finished with exit code 255
```

**Comment by s1monw** [comment]
I'd remove `ant-javafx.jar` from the CP which version of intelliJ are you using?

**Comment by rmuir** [comment]
The intellij bug is more, the bug looks like it adds the whole jdk to the ordinary classpath...

**Comment by jasontedor** [comment]
I stripped the SDK classpath in IntelliJ down to the default `sun.boot.class.path` and I'm not seeing jar hell failures anymore. Specifically:

    jre/lib/charsets.jar
    jre/lib/jce.jar
    jre/lib/jfr.jar
    jre/lib/jsse.jar
    jre/lib/resources.jar
    jre/lib/rt.jar

**Comment by dadoonet** [comment]
So I probably misconfigured my JDK8 on IntelliJ.

project structure intellij idea aujourd hui at 00 16 49

Thanks guys. I'll fix that on my end.

**Comment by rmuir** [comment]
I just backported this to 2.x

**Pull request merged**
