### PR TITLE
[ML] Hyperparameter names should match config

### PR DESCRIPTION
**Pull request by dimitris-athanasiou**
Java side of elastic/ml-cpp#1096

### CODE REVIEW

**Comment by dimitris-athanasiou** [comment]
run elasticsearch-ci/default-distro

**Comment by dimitris-athanasiou** [comment]
run elasticsearch-ci/2

**Review by przemekwitek — APPROVED** [review]
LGTM

**Comment by dimitris-athanasiou** [comment]
run elasticsearch-ci/2

**Comment by dimitris-athanasiou** [comment]
@elasticmachine update branch

**Pull request merged**
