### PR TITLE
Fix typo re: bootstrap.memory_lock in Docker docs.

### PR DESCRIPTION
**Pull request by michaelbaamonde**
`bootstrap_memory_lock` should be `bootstrap.memory_lock`.

### CODE REVIEW

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by jasontedor** [comment]
Please cherry-pick to 5.5, 5.6, 6.0, and 6.x.

**Review by dliappis — APPROVED** [review]
Good catch! LGTM!

**Comment by michaelbaamonde** [comment]
Thanks, @dliappis and @jasontedor! @fxdgear actually caught it; I'm but the committer.

**Pull request merged**
