### PR TITLE
[TEST] Cleanup Direcotry and Searcher mock code

### PR DESCRIPTION
**Pull request by s1monw**
We deployed our own code to check if directories are closed etc an d
if serachers are still open. Yet, since we don't have a global cluster
anymore we can just use lucene's internal mechanism to do that. This commit
removes all special handling and usese LuceneTestCase.closeAfterSuite to
fail if certain resources are not closed

### CODE REVIEW

**Comment by rmuir** [comment]
+1 for the cleanup. I think the suiteFailureMarker stuff should be handled internally by LuceneTestCase.closeAfterSuite, for any closeable (separate from any isOpen check and unrelated to whether its a directory or not).

**Comment by s1monw** [comment]
> +1 for the cleanup. I think the suiteFailureMarker stuff should be handled internally by LuceneTestCase.closeAfterSuite, for any closeable (separate from any isOpen check and unrelated to whether its a directory or not).

we did get this before anyway since we delete the index after the test anyway so I think there is no regression?

**Comment by rmuir** [comment]
yeah, it does not make anything worse

**Comment by s1monw** [comment]
@rmuir I added some reflection hack - wanna take anotehr look?

**Comment by rmuir** [comment]
hack looks fine to me. we will straighten this out in LTC so its cleaner and upgrade.

**Pull request merged**
