### PR TITLE
Remove copy-pasted code

### PR DESCRIPTION
**Pull request by tomcallahan**
We had two instances of copy-pasted code with a bad license from
another website.  The code was doing something rather simple, so
I simply re-implemented it.

### CODE REVIEW

**Comment by tomcallahan** [comment]
@elasticmachine test this please

**Review by jpountz — CHANGES_REQUESTED** [review]
In that case, it's probably even easier to remove this method and fix the call site to invoke `assertEquals("error message in case of failure", a, b, epsilon)`.

**Comment by tomcallahan** [comment]
Hah, I was not aware that was baked into junit - thanks!

**Review by jpountz — APPROVED** [review]

**Comment by polyfractal** [comment]
I'm at fault for this snippet and bad license, sorry about that. :(

That said, the method that JUnit uses is an absolute error margin which is sub-optimal for all the reasons listed at that site where I got the snippet:  http://floating-point-gui.de/errors/comparison/ 

We just had a failure in https://github.com/elastic/elasticsearch/issues/29456 for that reason.  The values were:

- -3.472856236891249x10<sup>11</sup>
- -3.4728562185648425x10<sup>11</sup>

With an abs difference of 1832.640625 ... quite a bit larger than 0.1 :) The relative difference is only 0.0000005% though, which is why the `nearlyEquals()` code was used.

I see that the website itself is licensed as [CC-BY](https://creativecommons.org/licenses/by/3.0/) which only requires proper attribution.  Could this code be re-added with the appropriate license and attribution?

Alternatively, perhaps the tests should be revisited.  The randomized nature of the tests means you can get large values like this (or very small values), but without randomization it's very hard to test all the different aspects of these mov avgs due to many different parameters and behaviors (alpha, beta, gamma, gaps in data, etc)

@tomcallahan @jpountz thoughts?

**Comment by jpountz** [comment]
Would it be enough to do something like `assertEquals(a, b, epsilon * Math.abs(a))`?

**Comment by polyfractal** [comment]
I'm not sure that will give what we want.  It'll go the opposite direction and add huge margins if `a` is large but `b` is small.  But I think I can adjust the MovAvg tests to use relative errors directly, and just hope we don't run into the other edge-cases (both values are very close to zero but on opposite sides, etc).

If we run into those situations it's probably just best to revisit the tests and see about making them a little less random anyway

**Comment by jpountz** [comment]
> It'll go the opposite direction and add huge margins if a is large but b is small

Does it matter? We are expecting a and b to be close, so either they are and then using a to got an error of magnitude of the error is fine, or they are not close and then we will get a failure anyway if epsilon is small?

**Comment by polyfractal** [comment]
Mmm, I think you're right.  I played around with a few scenarios and it behaved differently than I expected.  I'll give it a shot and unmute the test. :)

**Pull request merged**
