### PR TITLE
[8.4] [Doc] Fix typo in the JWT realm doc (#92779)

### PR DESCRIPTION
**Pull request by ywangd**
Backports the following commits to 8.4:
 - [Doc] Fix typo in the JWT realm doc (#92779)

### CODE REVIEW

**Comment by ywangd** [comment]
@elasticmachine update branch

**Comment by ywangd** [comment]
@elasticmachine update branch

**Comment by ywangd** [comment]
@elasticmachine update branch

**Comment by abdonpijpelink** [comment]
@elasticmachine update branch

**Comment by ywangd** [comment]
@abdonpijpelink The CI has always been failing because it cannot download a 8.4.4 artefact of the ML package. I think that is probably because we don't plan to release a 8.4.4 version. If that's the case, should I just close this doc PR?

**Comment by abdonpijpelink** [comment]
Yes, let's just close the 8.4 and 8.5 backports unmerged. 8.6 is the current version by now.

**Pull request closed without merging**
