### PR TITLE
Handle range query edge case

### LINKED ISSUE #63386: Using empty string in range query 'gt' returns no documents
I have created a new Index and then added two documents to it.

`PUT test_index`
`PUT /test_index/_doc/1 { "A" : "5" }`
`PUT /test_index/_doc/2 { "B" : "5" }`

After that I searched for every document with A greater than emty in that index,

`GET test_index/_search { "query": { "range": { "A": { "gt": "" } } }, "size": 2000 }`

and received no document.

`{ "took" : 0, "timed_out" : false, "_shards" : { "total" : 1, "successful" : 1, "skipped" : 0, "failed" : 0 }, "hits" : { "total" : { "value" : 0, "relation" : "eq" }, "max_score" : null, "hits" : [ ] } }`

On the other hand when I searched for every document with A greater than equal empty,

`GET test_index/_search { "query": { "range": { "A": { "gte": "" } } }, "size": 2000 }`

I received one document.

`{ "took" : 0, "timed_out" : false, "_shards" : { "total" : 1, "successful" : 1, "skipped" : 0, "failed" : 0 }, "hits" : { "total" : { "value" : 1, "relation" : "eq" }, "max_score" : 1.0, "hits" : [ { "_index" : "test_index", "_type" : "_doc", "_id" : "1", "_score" : 1.0, "_source" : { "A" : "5" } } ] } }`

Why does the greater than comparison behave different and does not return a document, too?

### PR DESCRIPTION
**Pull request by cbuescher**
Currently when searching with an empty string as lower bound for a range query
on text-based fields we return all documents when 'gte' is used (including the
lower bound) but no documents when 'gt' is used. This might seem
counterintuitive since every value should be greate than the empty string. This
PR fixed this special edge case by implicitely setting the "lower" include flag
in this case before constructing the TermRangeQuery.

Closes #63386

### CODE REVIEW

**Comment by romseygeek** [comment]
I'm confused, why is an empty BytesRef not comparing as strictly less than any other term?

**Comment by cbuescher** [comment]
I believe I tracked it down to https://github.com/apache/lucene-solr/blob/master/lucene/core/src/java/org/apache/lucene/util/automaton/Automata.java#L257 where in case `minInclusive` is false we don't generate the match-all state or whatever that automaton does there. That happens for empty string and "gt" currently. For "gte" all is well since 'minInclusive' is true then.

**Comment by cbuescher** [comment]
There are even safeguard this doesn't happen for 'null' values. I decided to but the change into `StringFieldType` since I thought the behaviour down in Lucene land is expected like this elsewhere.

**Comment by romseygeek** [comment]
I think this is a bug at the lucene level - if max is null and min is of length 0, then we should be returning a match-any binary no matter what the 'includeLower' value is, surely?

**Comment by cbuescher** [comment]
> I think this is a bug at the lucene level - if max is null and min is of length 0, then we should be returning a match-any binary no matter what the 'includeLower' value is, surely?

That what I wasn't sure about. I opted fixing on our side but if you think this is a Lucene bug I can open a fix there as well.

**Comment by romseygeek** [comment]
> but if you think this is a Lucene bug I can open a fix there as well.

+1

**Comment by cbuescher** [comment]
@romseygeek I opened https://github.com/apache/lucene-solr/pull/1976 with a fix in the `Automata` helper class. Would be great if you could take a look, if you think that is a better place to fix we can close this.

**Comment by cbuescher** [comment]
After  apache/lucene-solr#1976 is merged, I'm keeping this PR open to add tests that confirm the fix is also used by ES. This will happen once we move to a current 8.7 snapshot or release. I expect for SimpleSearchIT to fail until then but pass once we merge the fix in.

**Comment by cbuescher** [comment]
@elasticmachine update branch

**Comment by cbuescher** [comment]
@elasticmachine update branch

**Comment by cbuescher** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample-windows

**Comment by cbuescher** [comment]
@romseygeek this has been fixed in apache/lucene-solr#1976  which we use on master and 7.x now. I'd just like to add this test on our side to verify and test this behaviour going forward. Would you mind taking a quick look if you agree with adding this?

**Review by romseygeek — APPROVED** [review]
LGTM! Thanks for handling this @cbuescher

**Pull request merged**
