### PR TITLE
Escape CLI parameters when starting elasticsearch

### LINKED ISSUE #12677: elasticsearch script does not work with arguments that have spaces
If you attempt to start elasticsearch and have an argument that has a space in it, the argument is not parsed correctly and the value after the space is treated as a separate argument.

```
$ bin/elasticsearch -Des.pidfile="/path/with space/es.pid"
ERROR: Parameter [space/es.pid]does not start with --
```

The fix is probably similar to the ones in #12508

### PR DESCRIPTION
**Pull request by xuzha**
I'm not sure if I should do this. 

Closes #12677

### CODE REVIEW

**Comment by dakrone** [comment]
I actually think we should switch to `\"$@\"` instead of `\"$*\"`, see http://www.bashguru.com/2009/11/how-to-pass-arguments-to-shell-script.html for the difference when quoted (particularly for files with spaces in the name).

**Comment by xuzha** [comment]
Hmm, probably I am not quite understand. But I don't think there is any difference between ```\"$*\"``` and ```\"$@\" ```, we escape the double quotes there which will be passed into java program, and ```$*``` and ```$@``` became same. 

Try this dirty bash script 
```
#!/bin/bash

function print_args_at {
    printf "%s\n" "$@"
}

function print_args_star {
    printf "%s\n" "$*"
}

function print_args_star1 {
    printf "%s\n" \"$*\"
}

function print_args_star2 {
    printf "%s\n" \"$@\"
}

print_args_at "one" "two three" "four"
print_args_star "one" "two three" "four"
print_args_star1 "one" "two three" "four"
print_args_star2 "one" "two three" "four"
```

**Comment by rmuir** [comment]
I am working to make integration tests always use spaces in directory names (some fixes are needed) to blast out these bugs. But I agree with @dakrone here.

**Comment by xuzha** [comment]
OK, thanks guys, updated.

**Comment by clintongormley** [comment]
@spinscale @xuzha is this PR related to https://github.com/elastic/elasticsearch/pull/12709 ?

**Comment by spinscale** [comment]
Does this work for you? `./bin/elasticsearch  -Des.pidfile="/path/with space/es.pid"` - results in this error to me:

```
Exception in thread "main" java.nio.file.AccessDeniedException: /path
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.Files.createAndCheckIsDirectory(Files.jav
...
```

Also, calling something like `/bin/elasticsearch --http.cors.enabled true --http.cors.allow-origin 'foo'` results in this as only a single argument is passed?

```
ERROR: Parameter [http.cors.enabled true http.cors.allow-origin foo] needs value
```

**Comment by xuzha** [comment]
@spinscale You are right, adding \" \" make them only a single argument is passed.  But AccessDeniedException is the expected exception, right?

Anyway, Robert has a much better fix 12710. Ill just close this dumb one.

**Pull request closed without merging**
