### PR TITLE
Correct typo in class name of StatsAggregator

### LINKED ISSUE #14730: StatsAggegator has a missing character.
This is a minor issue or is not issue.

is it right StatsAggegator? (https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/search/aggregations/metrics/stats/StatsAggegator.java)
I think that StatsAggegator will be StatsAggregator.

Thanks.

### PR DESCRIPTION
**Pull request by martinstuga**
Closes #14730

### CODE REVIEW

**Comment by colings86** [comment]
@martinstuga thanks for the PR, could you sign the Contributer Licence Agreeement (https://www.elastic.co/contributor-agreement/) so we can merge this?

**Comment by martinstuga** [comment]
@colings86 I've already signed CLA twice. I don't know why, but it's still appearing as not signed. May you help me please?

**Comment by colings86** [comment]
@martinstuga it looks like the email you used to sign the CLA is different from the email on your commit. You could add the email address you use in your commits to your Github profile (you can make it private so it doesn't show up on your public profile) and this will allow our CLA checker tool to link your Github commits with your CLA signature in the future.

**Comment by martinstuga** [comment]
Thanks for the help about the CLA. I'm seeing that you're moving forward with this issue.

**Comment by colings86** [comment]
@martinstuga unfortunately at the moment the build fails with your change applied. Could you update this PR to fix the error, rebase your change onto the latest master and ensure `gradle assemble` runs successfully?

The error I get when running `gradle assemble` is:

```
/Users/colin/Dev/git/elasticsearch/core/src/main/java/org/elasticsearch/search/aggregations/metrics/stats/StatsParser.java:37: error: package StatsAggegator does not exist
        return new StatsAggegator.Factory(aggregationName, config);
```

**Pull request closed without merging**
