### PR TITLE
Make No. of Transport Threads == Available CPUs

### PR DESCRIPTION
**Pull request by original-brownbear**
We never do any file IO or other blocking work on the transport threads
so no tangible benefit can be derived from using more threads than CPUs
for IO.
There are however significant downsides to using more threads than necessary
with Netty in particular. Since we use the default setting for
`io.netty.allocator.useCacheForAllThreads` which is `true` we end up
using `16MB` of thread local buffer cache for each transport thread (as Tim points out this is the upper bound/worst case scenario).
Meaning we potentially waste CPUs x 16MB of heap.

### CODE REVIEW

**Comment by tbrooks8** [comment]
This is a discuss, so we I'm sure we will discuss it. I'm onboard with this and I will also bring back and update the shared event loops PR.

> we end up using 16MB of thread local buffer cache for each transport thread.

These chunks are allocated in arenas. The number of arenas is by default the number of CPUs. The setting `useCacheForAllThreads` impacts caching recently used `ByteBuf` thread locally. Fewer threads mean that the allocations (usually 32KB for TLS or 64KB socket reads) from the Arena will have more efficient reuse in the cache. But is only related to the number of chunks allocated through a level of indirection.

**Comment by original-brownbear** [comment]
Thanks Tim, updated the OP with your input. The 16M/thread is the upper bound (if getting really unlucky) not a set number. 
Now that #46346 is merged this change is less impactful but still the same arguments apply I think.

**Comment by original-brownbear** [comment]
We discussed this during our team meeting and since there were no objections to doing this I'm removing the discuss label.

**Comment by original-brownbear** [comment]
@elasticmachine update branch

**Review by Tim-Brooks — APPROVED** [review]
LGTM

**Comment by original-brownbear** [comment]
Thanks Tim!

**Pull request merged**
