### PR TITLE
Handle inbound exceptions on streaming request APIs

### PR DESCRIPTION
**Pull request by DaveCTurner**
Today if we submit a request with e.g. invalid credentials to the
`/_bulk` API then we throw a `ClassCastException` trying to cast the
`DefaultHttpRequest` to a `FullHttpRequest` on the error path. This
commit fixes the problem.

### CODE REVIEW

**Comment by DaveCTurner** [comment]
`>non-issue` because the bug wasn't released

**Review by Tim-Brooks — APPROVED** [review]
LGTM

@mhl-b - I wonder if this (`request.decoderResult().isFailure()`) is something that could also be tested at the IT level in `Netty4IncrementalRequestHandlingIT`? As a follow-up?

**Comment by DaveCTurner** [comment]
:+1: to capturing this in a single-JVM test too, I was just a little surprised we didn't already have end-to-end coverage of this case too

**Comment by mhl-b** [comment]
Before streaming every request was full http request, including decoder failures. I'm surprised to see default http request on error path. Will take a closer look.

**Comment by mhl-b** [comment]
It's likely result of bypassing aggregator, which always emits full requests. I will add test.

**Comment by mhl-b** [comment]
A smaller / simpler change would be adding `request.decoderResult().isFailure()` into Netty4HttpAggregator decider. Should be one line change that will invoke old code path. Anyway both options should go away with aggregator removal.

**Review by mhl-b — APPROVED** [review]

**Comment by DaveCTurner** [comment]
Superseded by https://github.com/elastic/elasticsearch/pull/113303.

**Pull request closed without merging**
