### PR TITLE
Wrapper for chunked Murmur3_x64_128 hashing of multiple byte arrays

### PR DESCRIPTION
**Pull request by danhermann**
Provides a wrapper around the x64_128 variant of the Murmur3 hash algorithm in `org.elasticsearch.common.hash.MurmurHash3` that provides the same API as `java.security.MessageDigest` and permits chunked hashing of successive byte arrays rather than requiring the entirety of the input to be provided in a single byte array. This is useful when the input is large and/or when it is successively obtained via object traversal or the like.

Prerequisite for https://github.com/elastic/elasticsearch/issues/69182

### CODE REVIEW

**Comment by danhermann** [comment]
Tagging the aggregations team as this code appears to be used there. If this change is not of consequence to you, please feel free to disregard.

**Comment by danhermann** [comment]
@elasticmachine update branch

**Review by jbaiera — APPROVED** [review]
LGTM!

**Comment by danhermann** [comment]
Thanks, @jbaiera!

**Pull request merged**
