### PR TITLE
Adjust RestHighLevelClient method modifiers

### PR DESCRIPTION
**Pull request by javanna**
`RestHighLevelClient` can be subclassed to add support for additional methods, but its public and protected method should be final.

### CODE REVIEW

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by javanna** [comment]
thanks @jasontedor !

**Review by tlrx — APPROVED** [review]

**Comment by mveitas** [comment]
@javanna with these changes to make methods final, it makes it hard to write a wrapper class around the `RestHighLevelClient` to be able to apply some sort of decorator. What I was hoping to do is create a wrapper around the class to be able to instrument the client and record metrics around the different types of operations, the timing, etc.

Would you be opposed to some sort of interface that the `RestHighLevelClient` implements? Having an interface would guarantee that any changes to public methods (additions, removals, etc) are accounted for when using some sort of decorator pattern.

**Comment by javanna** [comment]
hi @mveitas good point, would you mind opening a new issue so we can mark it discuss and discuss it with the rest of the team? Thank you!

**Pull request merged**
