### PR TITLE
Docs: Use the default distribution to test docs

### PR DESCRIPTION
**Pull request by nik9000**
Switch the docs tests from the `oss-zip` distribution to the `zip` distribution which contains x-pack. This should allow us to fold the x-pack docs into the oss ones. You can continue to run the docs tests with the oss distribution with `./gradlew -p docs -Dtests.distribution=oss-zip`.

Relates to #30665.

### CODE REVIEW

**Comment by nik9000** [comment]
The test that failed was one of mine, but it timed out and doesn't for me locally:
```
19:20:46 ERROR   1110s | DocsClientYamlTestSuiteIT.test {yaml=reference/cat/templates/line_7} <<< FAILURES!
19:20:46    > Throwable #1: java.lang.Exception: Test abandoned because suite timeout was reached.
```

I believe this is caused by us deleting all of the templates between test runs. x-pack re-adds them. I've been working on a solution to this but I'd like to deal with it as a followup to this. So I'll add a longer timeout for these tests in this PR and try to remove it in the followup.

**Comment by nik9000** [comment]
I've changed the regex. Lets see if that does the trick.

**Comment by nik9000** [comment]
> I've changed the regex. Lets see if that does the trick.

Hurray!

**Review by jasontedor — APPROVED** [review]
LGTM. Though, can you leave a comment on some of the substitutions? They took me some time to grok.

**Comment by nik9000** [comment]
> LGTM. Though, can you leave a comment on some of the substitutions? They took me some time to grok.

Sure!

**Comment by nik9000** [comment]
Thanks for reviewing @jasontedor! I'm going to add some comments and merge when I can!

**Pull request merged**
