### PR TITLE
Add deprecation mention for size=0

### PR DESCRIPTION
**Pull request by GlenRSmith**

### CODE REVIEW

**Comment by GlenRSmith** [comment]
@colings86 @debadair

**Comment by colings86** [comment]
LGTM

**Comment by clintongormley** [comment]
thanks @GlenRSmith  merged

**Comment by kaleemullah** [comment]
Then how to fetch all the terms in an agg? Right now, its showing 10 only.

**Comment by nik9000** [comment]
> Then how to fetch all the terms in an agg? Right now, its showing 10 only.

You can make the number fairly large, but `0`, the only all option is deprecated because it requires that we return arbitrarily large results which can fill up memory.

**Comment by kaleemullah** [comment]
@nik9000 hmm, Thanks.

**Pull request merged**
