### PR TITLE
[DOCS] Relocate several APIs to REST APIs section

### PR DESCRIPTION
**Pull request by jrodewig**
Relocates the following API sections under [REST APIs](https://www.elastic.co/guide/en/elasticsearch/reference/master/rest-apis.html):
* API Conventions
* Document APIs
* Search APIs
* Index APIs (previously named Indices APIs)
* cat APIs
* Cluster APIs

Also makes the following supporting changes:
- Removes the previous index APIs page under REST APIs. Adds a redirect for the removed page.
- Removes several [partintro] macros so the docs build correctly

### Preview
You can preview these navigation changes at https://es-demo-docs.firebaseapp.com/

### CODE REVIEW

**Review by debadair — APPROVED** [review]
LGTM!

**Comment by jrodewig** [comment]
Post-merge note: I've since reverted this PR as it unintentionally broke several links for deeply nested pages.

I'll work on fixing those and re-apply the commit afterward.

**Comment by jrodewig** [comment]
Here are the PRs to fix those broken links:
- elastic/elasticsearch/pull/44279
- elastic/kibana/pull/41001
- elastic/elasticsearch-hadoop/pull/1317
- elastic/elasticsearch-js/pull/902
- elastic/stack-docs/pull/411

**Comment by jrodewig** [comment]
Re-attempted the move this morning, but there were several broken links I couldn't fix by end of day.

In particular, elasticsearch-js was difficult to wrangle.

Will discuss more with the ES team and re-attempt at a later date.

**Pull request merged**
