### PR TITLE
[DOCS] Add tip for Kibana anonymous authentication

### LINKED ISSUE #73022: [DOCS] Add link from ES anonymous access to Kibana anonymous feature
The [Elasticsearch Anonymous access feature](https://www.elastic.co/guide/en/elasticsearch/reference/current/anonymous-access.html) is useful, but it's the wrong tool for people who want provide anonymous access to Kibana.  
For that, they should use the [Kibana Anonymous authentication feature](https://www.elastic.co/guide/en/kibana/current/kibana-authentication.html#anonymous-authentication).

However, the ES feature tends to show up in searches more frequently, and people try to use it to solve their Kibana access needs, and end having a bad time.  

We should add a `NOTE` at the top of the ES page, guiding people to the Kibana page if they want to provide anonymous access to Kibana (including embedding Kibana in an iframe).

### PR DESCRIPTION
**Pull request by jrodewig**
You shouldn't use Elasticsearch's anonymous access to provide access to Kibana
without requiring credentials. Instead, you should use Kibana's anonymous
authentication feature. However, the Elasticsearch anonymous access tends to be
more popular in search results.

This adds a brief tip that directs users to Kibana's anonymous authentication
feature.

Closes https://github.com/elastic/elasticsearch/issues/73022

### Preview
https://elasticsearch_73858.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/anonymous-access.html

### CODE REVIEW

**Comment by jrodewig** [comment]
@elasticmachine update branch

**Comment by jrodewig** [comment]
@elasticmachine update branch

**Comment by jrodewig** [comment]
@elasticmachine run elasticsearch-ci/packaging-tests-windows-sample

**Review by tvernum — APPROVED** [review]
LGTM, thanks @jrodewig

**Pull request merged**
