### PR TITLE
[DOCS] Update wildcard support for removing aliases

### PR DESCRIPTION
**Pull request by jrodewig**
You can now use a wildcard pattern to remove data stream and index
aliases in the same action/request.

Relates to #74403.

### Previews
* Aliases API: https://elasticsearch_74561.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/indices-aliases.html#indices-aliases-api-request-body
* Delete alias API: https://elasticsearch_74561.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/indices-delete-alias.html#delete-alias-api-path-params

### CODE REVIEW

**Review by martijnvg — APPROVED** [review]
LGTM, thanks for keeping the docs in sync!

**Comment by jrodewig** [comment]
Thanks @martijnvg

**Comment by jrodewig** [comment]
@elasticmachine ok to test

**Comment by jrodewig** [comment]
@elasticmachine update branch

**Pull request merged**
