### PR TITLE
Update index.asciidoc

### PR DESCRIPTION
**Pull request by iamjay**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?

### CODE REVIEW

**Comment by nik9000** [comment]
Change looks good. Can you sign the CLA? We need it for every single character.

**Comment by iamjay** [comment]
It's literally is a single character :) Anyway, CLA is signed.

**Comment by nik9000** [comment]
I know! I'm not particularly fond of having to ask it all the time either but since I'm not a lawyer I just have to trust the reasoning.

**Comment by nik9000** [comment]
Merged. Thanks @iamjay!

**Pull request merged**
