### PR TITLE
Ensure TermsEnum action works correctly with API keys

### PR DESCRIPTION
**Pull request by ywangd**
An API key's permission is bounded by its owner user's permission. When checking for DLS access, both the key's permission and the owner user's permission must be consulted. The access is granted only when it is granted by both. This PR ensures this logic is correctly enforced by the termsEnum action.

### CODE REVIEW

**Review by jakelandis — APPROVED** [review]
LGTM

**Comment by ywangd** [comment]
@elasticmachine update branch

**Comment by ywangd** [comment]
@elasticmachine update branch

**Comment by ywangd** [comment]
@elasticmachine run elasticsearch-ci/part-1 elasticsearch-ci/part-2

**Comment by ywangd** [comment]
@elasticmachine run elasticsearch-ci/part-2

**Pull request merged**
