### PR TITLE
Remove hand-coded XContent duplicate checks

### LINKED ISSUE #22253: Cleanup obsolete hand-coded XContent duplicate checks
With #22073 and #22225 we enabled strict duplicate checks for XContent. Although our benchmarks only showed a negligible performance drop of 1 - 2% (see #19614), Elasticsearch 6.0 still allows to disable the strict duplicate checks with an undocumented flag. Hence, we also needed to keep the existing hand-coded duplicate checks around in case Elasticsearch is started with disabled XContent parser duplicate checks.

In Elasticsearch 7.0, we should remove the undocumented fallback to disable strict duplicate checks and also remove our hand-coded duplicate checks.

### PR DESCRIPTION
**Pull request by danielmitterdorfer**
With this commit we cleanup hand-coded duplicate checks in XContent
parsing. They were necessary previously but since we reconfigured the
underlying parser in #22073 and #22225, these checks are obsolete and
were also ineffective unless an undocumented system property has been
set. As we also remove this escape hatch, we can remove the additional
checks as well.

Closes #22253

### CODE REVIEW

**Comment by danielmitterdorfer** [comment]
Note to reviewers: I intentionally kept tests so we check that duplicates are indeed detected.

**Comment by danielmitterdorfer** [comment]
>>   Note to reviewers: I intentionally kept tests so we check that duplicates are indeed detected.

> I don't think we need to do this. 

Fine for me. Then I'll remove these tests soon.

**Review by jasontedor — APPROVED** [review]
LGTM.

**Review by nik9000 — APPROVED** [review]
LGTM2!

**Comment by danielmitterdorfer** [comment]
@elasticmachine test this please

**Pull request merged**
