### PR TITLE
[ML] Force delete trained models

### PR DESCRIPTION
**Pull request by dimitris-athanasiou**
Adds a `force` parameter to the delete trained models API
which when set to `true` allows deletion of a model that
is referenced by ingest pipelines or has a started deployment.

### CODE REVIEW

**Review by sethmlarson — APPROVED** [review]

**Review by benwtrent — APPROVED** [review]
:shipit:

**Comment by dimitris-athanasiou** [comment]
@elasticmachine update branch

**Comment by dimitris-athanasiou** [comment]
@benwtrent Could you please also take a look at the `Force stop deployment before deleting` commit?

**Review by benwtrent — APPROVED** [review]
changes to stop the deployment make sense. 

As long as we have a test covering force deleting a deployed model also deletes the allocation then this is g2g

**Comment by dimitris-athanasiou** [comment]
> As long as we have a test covering force deleting a deployed model also deletes the allocation then this is g2g

Good point. I'm testing force deleting a model with deployment but I don't assert the allocation was actually stopped. Let me add an assertion on cluster state.

**Review by lcawl — APPROVED** [review]
Documentation LGTM

**Comment by dimitris-athanasiou** [comment]
@elasticmachine update branch

**Comment by dimitris-athanasiou** [comment]
@elasticmachine update branch

**Pull request merged**
