### PR TITLE
Enable the `get_user_privileges` REST API test

### PR DESCRIPTION
**Pull request by arteam**
It was muted in #77553, but can be enabled again after #77777 was merged to 7.x

#77797 will make sure that this test will pass regardless of the internal details of `HashSet` in the JDK

### CODE REVIEW

**Comment by arteam** [comment]
@elasticmachine run elasticsearch-ci/packaging-tests-unix-sample

**Comment by arteam** [comment]
@elasticmachine update branch

**Review by jakelandis — APPROVED** [review]
LGTM

**Comment by arteam** [comment]
Thanks, Jake!

**Pull request merged**
