### PR TITLE
Log missing file exception when failing to read metadata snapshot

### PR DESCRIPTION
**Pull request by ginolzh**
There is a logging statement that is able to catch two exception types (FileNotFoundException or NoSuchFileException) but cannot distinguish which type of exception occurred just base on the log message. Maybe adding a stack trace could help.

### CODE REVIEW

**Review by dnhatn — APPROVED** [review]
LGTM.

@elasticmachine test this please.

**Comment by jasontedor** [comment]
Yet these two exceptions represent the same failure: a file that is not found?

**Comment by lzh3636** [comment]
Maybe there're some slight differences between these two exceptions, according to the java documentation it describes FileNotFoundException as: 
"This exception will be thrown by the FileInputStream, FileOutputStream, and RandomAccessFile constructors when a file with the specified pathname does not exist. It will also be thrown by these constructors **if the file does exist but for some reason is inaccessible**, for example when an attempt is made to open a read-only file for writing."

And for NoSuchFileException it is: "Checked exception thrown when an attempt is made to access a file that does not exist."

**Comment by bleskes** [comment]
@jasontedor anything you want done here?

**Review by ywelsch — APPROVED** [review]
LGTM. While logging the exception, we also get info about the file that's missing. Given that this should very rarely happen, I think it's ok having the stack trace.

**Comment by ywelsch** [comment]
@elasticmachine test this please

**Pull request merged**
