### PR TITLE
Rename MetaData to Metadata in all of the places

### PR DESCRIPTION
**Pull request by jasontedor**
This is a simple naming change PR, to fix the fact that "metadata" is a single English word, and for too long we have not followed general naming conventions for it. We are also not consistent about it, for example, METADATA instead of META_DATA if we were trying to be consistent with MetaData (although METADATA is correct when considered in the context of "metadata"). This was a simple find and replace across the code base, only taking a few minutes to fix this naming issue forever.

### CODE REVIEW

**Comment by rjernst** [comment]
Not looking at the actual diff given the size of this, but LGTM. We should separately look at having a more clarifying name (what metadata for *what*?)

**Review by rjernst — APPROVED** [review]

**Comment by ywelsch** [comment]
This silently reverted one of my PRs (#54519) that was merged before this change, and I only saw this by chance now 2 months later...
Perhaps worth looking into what went wrong here during the merge of this PR.

**Comment by jasontedor** [comment]
@ywelsch Can you clarify which PR was silently reverted, since you linked back to this PR I can not investigate. 🙏

**Comment by jasontedor** [comment]
I don't know what could have happened here. This change was purely mechanical, and the lines that you're referencing would not have had any merge conflicts with the lines changed in that file in this PR. Interestingly, the way that I did the 7.x change was not to cherry-pick back, but merely to repeat the mechanical steps I took to prepare the change in master too, so it's surprising that those same steps would cause problems in master but not 7.x. Sorry for the trouble, I'm glad that you caught the reversion.

**Pull request merged**
