### PR TITLE
EQL: consistent naming for event type vs event category

### PR DESCRIPTION
**Pull request by aleksmaus**
Related to https://github.com/elastic/elasticsearch/issues/52941

### CODE REVIEW

**Comment by jrodewig** [comment]
Excited about these changes. I'll work on syncing up the existing docs to match the new field name + defaults. Thanks @aleksmaus.

**Review by costin — APPROVED** [review]
LGTM

**Review by imotov — APPROVED** [review]
LGTM

**Comment by imotov** [comment]
@elasticmachine run elasticsearch-ci/default-distro

**Pull request merged**
