### PR TITLE
[DOCS] Reformat rollup APIs to use new API format

### PR DESCRIPTION
**Pull request by lcawl**
Related to https://github.com/elastic/docs/issues/937

With elastic/docs#938, we created a standard template
for Elastic API Reference documentation.

This PR edits some initial rollup APIs to use that template. It also makes use of some shared attributes that were implemented for rollup terms in https://github.com/elastic/docs/pull/969

### CODE REVIEW

**Comment by lcawl** [comment]
For a preview, see https://doc-review-63bf6.firebaseapp.com/es2/rollup-put-job.html

**Review by polyfractal — APPROVED** [review]
LGTM from a rollup perspective.  

Out of curiosity, why remove the 404 response examples?  Don't want to show exception messages in the API docs?

**Comment by lcawl** [comment]
> Out of curiosity, why remove the 404 response examples? Don't want to show exception messages in the API docs?

After I added the "Response codes" section, the example seemed redundant. We're trying to have brief examples in these reference pages if possible. If you feel strongly about adding it back, however, I can do so.

**Comment by polyfractal** [comment]
No strong feelings, mostly just curious for future reference when writing docs.  Thanks! :+1:

**Pull request merged**
