### PR TITLE
Windows service installation should allow multiple values in ES_JAVA_OPTS

### LINKED ISSUE #64029: Unable to Install ES7.9.2 as Windows Service with ES_JAVA_OPTS in env var
**Elasticsearch version** (`bin/elasticsearch --version`): ES 7.9.2

**Plugins installed**: []

**JVM version** (`java -version`): Bundled JDK

**OS version** (`uname -a` if on a Unix-like system): Windows 10

**Description of the problem including expected versus actual behavior**:
Unable to install elasticsearch as windows service when we set Xms and Xmx via windows env var ES_JAVA_OPTS
installation is okay if heap is set via jvm_options file.

**Steps to reproduce**:

1. Set ES_JAVA_OPTS env var with: `-Xms4g -Xmx4g`
2. Try to install Elasticsearch as a Windows service with
`elasticsearch-service.bat install`
3. Installation failed due to semicolon being added in between the heap config.

**Provide logs (if relevant)**:
```
D:\ES7_test\elasticsearch-7.9.2\bin>echo %ES_JAVA_OPTS%
-Xms4g -Xmx4g

D:\ES7_test\elasticsearch-7.9.2\bin>elasticsearch-service.bat install
Installing service      :  "elasticsearch-service-x64"
Using JAVA_HOME (64-bit):  ""D:\ES7_test\elasticsearch-7.9.2\jdk""
Exception in thread "main" java.lang.RuntimeException: starting java failed with [1]
output:

error:
Invalid initial heap size: -Xms4g;-Xmx4g
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
        at org.elasticsearch.tools.launchers.JvmErgonomics.flagsFinal(JvmErgonomics.java:126)
        at org.elasticsearch.tools.launchers.JvmErgonomics.finalJvmOptions(JvmErgonomics.java:88)
        at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:59)
        at org.elasticsearch.tools.launchers.JvmOptionsParser.jvmOptions(JvmOptionsParser.java:137)
        at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:95)
```

### PR DESCRIPTION
**Pull request by williamrandolph**
Users have reported a bug in the handling of `ES_JAVA_OPTS` with the Windows Service installation. It looks like we are converting space delimiters in ES_JAVA_OPTS to semicolon delimiters before calling our JVM Ergonomics utility, but the utility splits ES_JAVA_OPTS on whitespace.

I'm starting with a packaging test, but I have a fix for `elasticsearch-service.bat` that I will push as soon as I see the expected test failure in the OS tests.

Fixes #64029

### CODE REVIEW

**Comment by williamrandolph** [comment]
Here is a build with the expected test failure: https://gradle-enterprise.elastic.co/s/pvdiqgwoors5m/console-log?task=:qa:os:destructiveDistroTest.oss-windows-archive

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by williamrandolph** [comment]
Backport PR for tests on 7.x: #64437

**Comment by williamrandolph** [comment]
Backport commits:
7.10: 572b455ee3ba3b0bfb6d862e41129acbf315fa3f
7.9: 39f36535ded

**Pull request merged**
