### PR TITLE
Change the ingest simulate api to not include dropped documents

### LINKED ISSUE #36150: Simulate Ingest API: Drop processor cannot be verified
**Describe the feature**: Using the simulation API for custom pipelines, it is not possible to find out, if a document would be dropped

Create a pipeline that drops all documents

```
PUT _ingest/pipeline/droppipeline
{
  "processors": [
    {
      "drop": {}
    }
  ]
}

PUT foo/bar/1?pipeline=droppipeline
{
  "message": "123"
}

# document does not exist
GET foo/bar/1
```

However running the simulate API does not indicate that the document will not be created

```
POST _ingest/pipeline/droppipeline/_simulate
{
  "docs": [
    {
      "_source": {
        "message": "text"
      }
    }
  ]
}

```

returns

```
{
  "docs" : [
    {
      "doc" : {
        "_index" : "_index",
        "_type" : "_type",
        "_id" : "_id",
        "_source" : {
          "message" : "text"
        },
        "_ingest" : {
          "timestamp" : "2018-12-03T10:16:52.719501Z"
        }
      }
    }
  ]
}

```

### PR DESCRIPTION
**Pull request by martijnvg**
If documents are dropped by the `drop` processor then
these documents are returned as a `null` value in the response.

### Example

Create pipeline:

```
PUT _ingest/pipeline/droppipeline
{
    "processors": [
        {
            "set": {
                "field": "bla",
                "value": "val"
            }
        },
        {
            "drop": {}
        }
    ]
}
```

Simulate request:

```
POST _ingest/pipeline/droppipeline/_simulate
{
    "docs": [
        {
            "_source": {
                "message": "text"
            }
        }
    ]
}
```

Response:

```json
{
    "docs": [
        null
    ]
}
```

Response if verbose is enabled:

```json
{
    "docs": [
        {
            "processor_results": [
                {
                    "doc": {
                        "_index": "_index",
                        "_type": "_doc",
                        "_id": "_id",
                        "_source": {
                            "message": "text",
                            "bla": "val"
                        },
                        "_ingest": {
                            "timestamp": "2019-07-10T11:07:10.758315Z"
                        }
                    }
                },
                null
            ]
        }
    ]
}
```

Closes #36150

### CODE REVIEW

**Comment by jakelandis** [comment]
Testing this change and if I add a processor after the drop, I would expect for verbose to stop the output on the `null`

For example:
```
PUT _ingest/pipeline/droppipeline
{
    "processors": [
        {
            "set": {
                "field": "a",
                "value": "val"
            }
        },
        {
            "drop": {}
        },
         {
            "set": {
                "field": "b",
                "value": "val2"
            }
        }
    ]
}
```
```
POST _ingest/pipeline/droppipeline/_simulate?verbose
{
    "docs": [
        {
            "_source": {
                "message": "text"
            }
        }
    ]
}
```
results in 
```
{
  "docs" : [
    {
      "processor_results" : [
        {
          "doc" : {
            "_index" : "_index",
            "_type" : "_doc",
            "_id" : "_id",
            "_source" : {
              "a" : "val",
              "message" : "text"
            },
            "_ingest" : {
              "timestamp" : "2019-07-17T20:45:05.431236Z"
            }
          }
        },
        null,
        {
          "doc" : {
            "_index" : "_index",
            "_type" : "_doc",
            "_id" : "_id",
            "_source" : {
              "a" : "val",
              "b" : "val2",
              "message" : "text"
            },
            "_ingest" : {
              "timestamp" : "2019-07-17T20:45:05.431236Z"
            }
          }
        }
      ]
    }
  ]
}
```
I would expect 
```
{
  "docs" : [
    {
      "processor_results" : [
        {
          "doc" : {
            "_index" : "_index",
            "_type" : "_doc",
            "_id" : "_id",
            "_source" : {
              "a" : "val",
              "message" : "text"
            },
            "_ingest" : {
              "timestamp" : "2019-07-17T20:45:05.431236Z"
            }
          }
        },
        null        
      ]
    }
  ]
}
```
(or possibly null, null)

**Comment by jakelandis** [comment]
looks good other then the one issue ^^ above

**Comment by martijnvg** [comment]
@jakelandis I pushed to address the issue: 68b5d8d399d0465e9f1c50397e6c527bb0df7bda

**Review by jakelandis — APPROVED** [review]
LGTM

**Pull request merged**
