### PR TITLE
Decref CacheFileRegion after read is done not before

### PR DESCRIPTION
**Pull request by tlrx**
The CacheFileRegion instance is decref before the read operation is executed, meaning that the SharedBytes.IO instance can return to the pool of free regions, being polled and written for another cache file region by another thread, before the first read is effectively completed (and will return incorrect bytes).

### CODE REVIEW

**Review by original-brownbear — APPROVED** [review]
:shipit:

**Comment by original-brownbear** [comment]
@tlrx only thing to fix is the title, CacheFileRegion is what you decrement here :)

**Comment by tlrx** [comment]
> @tlrx only thing to fix is the title, CacheFileRegion is what you decrement here :)

 🤦🏻 Thanks for noticing!

**Comment by DaveCTurner** [comment]
When assertions are enabled, could we fill regions with junk on release? That would make it easier to catch this kind of thing I think.

**Pull request merged**
