### PR TITLE
Update experimental labels in the docs

### PR DESCRIPTION
**Pull request by clintongormley**
Relates https://github.com/elastic/elasticsearch/issues/19798

Removed experimental label from:
* Painless
* Diversified Sampler Agg
* Sampler Agg
* Significant Terms Agg
* Terms Agg document count error and execution_hint
* Cardinality Agg precision_threshold
* Pipeline Aggregations
* index.shard.check_on_startup
* index.store.type (added warning)
* Preloading data into the file system cache
* foreach ingest processor
* Field caps API
* Profile API

Added experimental label to:
* Moving Average Agg Prediction

Changed experimental to beta for:
* Adjacency matrix agg
* Normalizers
* Tasks API
* Index sorting

Labelled experimental in Lucene:
* ICU plugin custom rules file
* Flatten graph token filter
* Synonym graph token filter
* Word delimiter graph token filter
* Simple pattern tokenizer
* Simple pattern split tokenizer

Replaced experimental label with warning that details may change in the future:
* Analysis explain output format
* Segments verbose output format
* Percentile Agg compression and HDR Histogram
* Percentile Rank Agg HDR Histogram

### CODE REVIEW

**Comment by s1monw** [comment]
Awesome! Thanks for doing this!

**Comment by jpountz** [comment]
> Percentile (Rank) Agg compression and HDR Histogram

I would leave them experimental as these options depend too much on the internal implementation? Or we'd need to make these options a bit more generic like we did for the `precision_threshold` of the `cardinality` impl.

> Preloading data into the file system cache

Is it worth keeping experimental until we have a nicer API? The current one, based on file extensions, requires knowledge of low-level Lucene implementation details. I see you changed some APIs from `experimental` to `expert`, which would work for me too.

Otherwise LGTM

**Review by s1monw — APPROVED** [review]

**Review by eskibars — COMMENTED** [review]
I do have just 2 questions on the experimental text around _segments and _analyze.  I get that we depend on the output of Lucene, but to me that seems independent of whether it's experimental or not.  It may make the output format vary on a more frequent basis, which I consider different (worthy of a warning, but a different type of warning).

**Comment by clintongormley** [comment]
@eskibars @jpountz I've removed the experimental label from file preloading, HDR, analyze verbose output, and segment verbose output, and replaced it with a note that the syntax may change in the future.

**Comment by jpountz** [comment]
Thanks @clintongormley

**Pull request merged**
