### PR TITLE
Add `active_only` flag to Get API Key REST spec

### PR DESCRIPTION
**Pull request by n1v0lg**
https://github.com/elastic/elasticsearch/pull/98259 added a new flag for the Get API key API. I missed adding it to the REST API spec originally. 

This PR corrects the REST spec.

### CODE REVIEW

**Comment by n1v0lg** [comment]
@elastic/clients-team we introduced this change back in 8.10 -- do we have an approach for backporting this kind of change to older versions of ES? I can add older ES version labels (for 8.10 and 8.11) just want to make sure that's appropriate, given that we are generally backporting to those branches anymore. Thanks and sorry about the hassle 🙏

**Review by slobodanadamovic — APPROVED** [review]
LGTM

Would it make sense to add a YAML test for `active_only` flag?

**Review by jfreden — APPROVED** [review]
LGTM!

**Comment by n1v0lg** [comment]
@elasticmachine update branch

**Comment by n1v0lg** [comment]
@elasticmachine update branch

**Pull request merged**
