### PR TITLE
Register reserved routes so we do not register them by accident

### PR DESCRIPTION
**Pull request by dakrone**
This commits adds four "reserved" paths that Elasticsearch should not register under any cases. By registering these and returning a bad request (we don't *actually* serve them), we can ensure that if we ever try to register them in the path, Elasticsearch will trip an assertion and fail to build.

Must be merged *after* #92879

### CODE REVIEW

**Comment by dakrone** [comment]
An alternative to this (perhaps for the core/infra team to discuss), would be to special case these URIs in the `RestController` itself, to prevent registering them. Either way would be fine with me, so let me know and I'll change this PR for the other option.

**Comment by rjernst** [comment]
I think I would prefer this as a hardcoded list checked in handler registration. Then a dummy handler isn't needed?

**Comment by gmarouli** [comment]
> I think I would prefer this as a hardcoded list checked in handler registration. Then a dummy handler isn't needed?

I am also leaning towards such an approach. I was even thinking that we could maybe verify this in a test. My rationale is that we add this to protect the developers of elasticsearch (or plugins?) to use a path that is reserved for a different purpose, a test or a check in the code is sufficient I believe without exposing these endpoints to our users.

**Comment by andreidan** [comment]
Thanks for working on this Lee! 

++ on Mary's suggestion to have this validation as a test (I believe iterating over the `RestController#handlers` and checking the paths don't contain reserved values would do the trick)

**Comment by mattc58** [comment]
This approach will work well. However, I can see a future where we continue to add to the list of reserved URL paths. Should we consider using a single path prefix for anything in the future? Perhaps something like `_reserved_proxy_/` or `_reserved_/` or some such? So we'd add that to the list of reserved paths in `RestReservedAction`.

**Comment by dakrone** [comment]
I moved the validation to the `RestController` and added a (very simple) test.

**Review by rjernst — APPROVED** [review]
LGTM!

**Comment by dakrone** [comment]
@elasticmachine update branch

**Comment by dakrone** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|7.17|[](https://github.com/elastic/elasticsearch/pull/92994)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
