### PR TITLE
Deprecate the count api in favour of search with size 0

### PR DESCRIPTION
**Pull request by javanna**
Relates to #13928

### CODE REVIEW

**Comment by s1monw** [comment]
LGTM - once question, should we use the deprecation logger if somebody uses it?

**Comment by javanna** [comment]
> should we use the deprecation logger if somebody uses it?

I pushed a new commit that makes sure we don't use count from the REST layer, so we can safely use the deprecation logger to signal usages of count from the java api, which is going to be removed. @s1monw can you please have another look?

**Comment by s1monw** [comment]
LGTM

**Comment by javanna** [comment]
Pushed to 2.x and 2.1.

**Pull request closed without merging**
