### PR TITLE
SQL: Add ability to perform CCS through SQL querying

### PR DESCRIPTION
**Pull request by bpintea**
This adds the ability to perform cross cluster searching through SQL.
This is done by simply using the CCS-specific `cluster:index` notation,
where the "cluster" maps to an SQL catalog and "index" to a table;
patterns are supported for both. Noteworthy here is that a search runs
either on the local or remote clusters, but not both (which is a
CCS-specific behavior).

Another limitation is currently that table enumeration in remote
clusters will not contain aliases (not reported through field caps).
Also, frozen indices are currently not listed as such (they're listed as
normal indices).

`SYS COLUMNS` command will not take a catalog pattern - an exact match is
required -, following xDBC spec. `SYS TABLES` can, however.

The query API now takes a new parameter, `catalog`, whose value is prefixed
 to the index in the query, before execution, if the index is not already qualified
 (which takes precedence).

### CODE REVIEW

**Review by costin — COMMENTED** [review]
Gave a first round of feedback. Looks good overall.
It's not clear to me what test are running against a catalog and which one are not.
SELECT FROM table
vs
SELECT FROM local:table
vs
SELECT FROM remote:table

**Comment by bpintea** [comment]
> It's not clear to me what test are running against a catalog and which one are not.
> SELECT FROM table
> vs
> SELECT FROM local:table
> vs
> SELECT FROM remote:table

The JDBC driver [now](https://github.com/elastic/elasticsearch/pull/78903/commits/2ee6bf997a957964fcd58fd13b5f3765514a57bd) takes a new parameter, `catalog`, whose value is prefixed to the index, if this is not already qualified.

The `JdbcCsvSpecIT` test will randomly alternate between `SELECT FROM table` (with a `"catalog": "remote"` param) and `SELECT FROM remote:table`. Currently all the data is indexed in the remote cluster only.

**Review by astefan — COMMENTED** [review]
Looks good overall. Left some minor comments.

**Review by astefan — COMMENTED** [review]
Left a second round of comments/questions.

**Review by astefan — APPROVED** [review]
LGTM

**Pull request merged**
