### PR TITLE
[Monitoring] Update beats version

### PR DESCRIPTION
**Pull request by chrisronline**
Follows up from https://github.com/elastic/elasticsearch/pull/33286

Updates the version number of the template file

cc @pickypg

### CODE REVIEW

**Comment by chrisronline** [comment]
Test failure seems unrelated:
> 19:51:09 Caused: hudson.remoting.ChannelClosedException: Channel "unknown": Remote call on JNLP4-connect connection from elasticsearch-ci-immutable-centos-7-1537900681512810758.c.elastic-ci-prod.internal/10.224.15.211:48510 failed. The channel is closing down or has closed down

**Comment by chrisronline** [comment]
retest

**Comment by chrisronline** [comment]
jenkins test this

**Review by pickypg — APPROVED** [review]
LGTM. Note: this does not need to target master because the version there is 7.0.

**Review by ruflin — APPROVED** [review]

**Pull request merged**
