### PR TITLE
Data stream parse timestamp use Java 14 switch expressions

### PR DESCRIPTION
**Pull request by weizijun**
Data stream parse timestamp use Java 14 switch expressions.

### CODE REVIEW

**Comment by weizijun** [comment]
@elasticmachine update branch

**Comment by Navanit-git** [comment]
LGTM @weizijun

**Review by martijnvg — COMMENTED** [review]
Looks good! Maybe remove the changelog entry here? For the same reason mentioned [here](https://github.com/elastic/elasticsearch/pull/84391#discussion_r818769148).

**Comment by weizijun** [comment]
@elasticmachine update branch

**Comment by weizijun** [comment]
> Looks good! Maybe remove the changelog entry here? For the same reason mentioned [here](https://github.com/elastic/elasticsearch/pull/84391#discussion_r818769148).

done

**Comment by martijnvg** [comment]
@elasticmachine test this please

**Review by martijnvg — APPROVED** [review]

**Pull request merged**
