### PR TITLE
Add methods to prevent allocating long arrays during child navigation on H3 api

### PR DESCRIPTION
**Pull request by iverase**
Currently when navigating from an H3 cell to its children, we need to call the method `#h3ToChildren` which returns an array containing the children, therefore for each call we need to create a new array. It is not difficult to add methods that gives you the size of the of the children and methods that return the children for each  position. Therefore we can navigate the children in the following fashion without an intermediate array:

```
for (int i = 0; i < H3.h3ToChildrenSize(h3); i++) {
    doSomething(H3.childPosToCell(h3, i));
}
```

This PR adds the methods:

```
long childPosToH3(long h3, int childPos)
String childPosToH3(String h3, int childPos)
long  noChildIntersectingPosToCell(long h3, int childPos)
String  noChildIntersectingPosToCell(String h3, int childPos)

long h3ToChildrenSize(long h3, int childRes)
int h3ToChildrenSize(long h3)
int h3ToChildrenSize(String h3)
int h3ToNotIntersectingChildrenSize(long h3)
int h3ToNotIntersectingChildrenSize(String h3)
```
Which allows navigating to the children cells without using intermediate arrays.

### CODE REVIEW

**Comment by iverase** [comment]
I hit https://github.com/elastic/elasticsearch/issues/91915 which is unrelated to this PR and it is a bug in the spatial3d library we are using.

**Comment by iverase** [comment]
@elasticmachine run elasticsearch-ci/part-1

**Review by craigtaverner — APPROVED** [review]
Nice improvement. I did notice that the deleted Iterator class had a lot of very descriptive and perhaps informative comments. Any chance these can be saved (perhaps adding comments to the new methods)?

**Comment by iverase** [comment]
Not sure if it is worthy as all those comments relate when trying to iterate over several resolutions but we only support one step navigation where  nothing of what is there is really useful.

**Comment by iverase** [comment]
I added comments regarding pentagon skip digit.

**Pull request merged**
