### PR TITLE
Improved error message for absence of indices closes #38964

### LINKED ISSUE #38964: Cannot apply settings to all indices
**Elasticsearch version** (`bin/elasticsearch --version`):
7.0.0-beta1
**OS version** (`uname -a` if on a Unix-like system):
docker
**Description of the problem including expected versus actual behavior**:

Cannot apply settings to all indices

**Steps to reproduce**:

```bash
curl -X PUT \
  http://localhost:9200/_settings \
  -H 'Content-Type: application/json' \
  -d '{
    "index.blocks.read_only_allow_delete": null
}'
```

Returns the error below :

**Provide logs (if relevant)**:

```json
{
    "error": {
        "root_cause": [
            {
                "type": "index_not_found_exception",
                "reason": "no such index [null]",
                "resource.type": "index_expression",
                "resource.id": "_all"
            }
        ],
        "type": "index_not_found_exception",
        "reason": "no such index [null]",
        "resource.type": "index_expression",
        "resource.id": "_all"
    },
    "status": 404
}
```

Refer to doc : https://www.elastic.co/guide/en/elasticsearch/reference/7.0/indices-update-settings.html

> The REST endpoint is /_settings (to update all indices) or {index}/_settings to update one (or more) indices settings. The body of the request includes the updated settings, for example:

### PR DESCRIPTION
**Pull request by Eunovo**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by javanna** [comment]
jenkins test this please

**Comment by javanna** [comment]
thanks for opening this PR @Eunovo ! The fix looks good to me and tests are green. Could you please add a test though, for instance to `IndexNameExpressionResolverTests`, that verifies that the error message is correct?

**Comment by Eunovo** [comment]
@javanna it will take some time for me to clone the repo to my Machine (Things are a little complicated where I'm located). I would prefer not to do so at this time, but if  it is completely necessary I will.

**Comment by Eunovo** [comment]
@javanna to add something like 

testConcreteIndiciesNoIndiciesErrorMessage()

to 

https://github.com/Eunovo/elasticsearch/blob/master/server/src/test/java/org/elasticsearch/cluster/metadata/IndexNameExpressionResolverTests.java

**Comment by javanna** [comment]
yes @Eunovo something along those lines sounds good.

**Comment by javanna** [comment]
hi @Eunovo ,  did you have a chance to work on the requested changes? I think that the git history contains non relevant changes, that may have been caused by rebasing. Would you mind fixing that either in this PR or by opening a new one that contains only your own commits? Thanks!

**Comment by Eunovo** [comment]
@javanna I'll open a new pull request

**Pull request closed without merging**
