### PR TITLE
Upgrade to Lucene-8.10.0-snapshot-bf2fcb53079

### PR DESCRIPTION
**Pull request by dnhatn**
To include [LUCENE-10106](https://issues.apache.org/jira/browse/LUCENE-10106) so we don't need to revert the sort optimization introduced in https://github.com/elastic/elasticsearch/pull/64292.

### CODE REVIEW

**Review by romseygeek — APPROVED** [review]
LGTM, thanks @dnhatn

**Review by mayya-sharipova — APPROVED** [review]
Thanks a lot @dnhatn

**Comment by mayya-sharipova** [comment]
It looks like this test is failing:  "org.elasticsearch.xpack.core.security.support.AutomatonsTests.testSettingMaxDeterminizedStates" 
Looks to be related to [this lucene commit](https://github.com/apache/lucene/commit/c4cf7aa3e199c53d9cf9401363b0c65df5c36111#)

**Comment by dnhatn** [comment]
@mayya-sharipova We are now failing with the validation introduced in https://github.com/apache/lucene/pull/283. The problem is that we use `SortField.LONG` for an integer field. Would you mind taking a look?

**Comment by mayya-sharipova** [comment]
Sorry for the trouble @dnhatn.  We need to backport this @jimczi [PR](https://github.com/apache/lucene/pull/291)  to lucene-solr 8.x. I will do that.

**Pull request merged**
