### PR TITLE
Return 404 when deleting a non existing data stream

### LINKED ISSUE #62022: Deleting a nonexistent data stream returns 200, should be 404
Try deleting a non-existent data stream:

```
DELETE /_data_stream/test
```

The response is 200 `acknowledge: true`, but I'd expect it to be a 404.

### PR DESCRIPTION
**Pull request by martijnvg**
Return a 404 http status code when attempting to delete a non existing data stream.
However only return a 404 when targeting a data stream without any wildcards.

Closes #62022

### CODE REVIEW

**Review by danhermann — APPROVED** [review]
LGTM. The only thing I might suggest would be moving the logic for `nameContainsWildcardPatterns` to the transport action or making it dynamically evaluated in the request class so it doesn't have to be part of the serialized request.

**Comment by martijnvg** [comment]
> The only thing I might suggest would be moving the logic for nameContainsWildcardPatterns to the transport action or making it dynamically evaluated in the request class so it doesn't have to be part of the serialized request.

I don't like the current approach too, but I don't see how this can be done differently. In the case the security rewrites any wildcard expressions in indices/names then the the transport action doesn't know whether wildcards have been used. This way when the rest action creates the transport request, we record whether the original indices/names contained wildcards.

**Comment by danhermann** [comment]
> > The only thing I might suggest would be moving the logic for nameContainsWildcardPatterns to the transport action or making it dynamically evaluated in the request class so it doesn't have to be part of the serialized request.
> 
> I don't like the current approach too, but I don't see how this can be done differently. In the case the security rewrites any wildcard expressions in indices/names then the the transport action doesn't know whether wildcards have been used. This way when the rest action creates the transport request, we record whether the original indices/names contained wildcards.

Ah, right, I forgot about security. The delete index request has this behavior and I think it's because security preserves the existence of a wildcard in the original request by replacing the requested indices with the `[*, -*]` pair when the wildcards match no indices for which the user is authorized.

**Comment by martijnvg** [comment]
> The delete index request has this behavior and I think it's because security preserves the existence of a wildcard in the original request by replacing the requested indices with the [*, -*] pair when the wildcards match no indices for which the user is authorized.

Right, but in the case the a user specifies logs-* as index and the user has privileges to access one or more indices starting with logs-* prefix then the transport action doesn't know whether wildcard patterns were used, since the wildcard expressions would have been replaced with the actual authorized indices.

**Comment by danhermann** [comment]
This looks like the best that can be done without revamping how security does resource-based authorization.

**Comment by martijnvg** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample-windows

**Comment by martijnvg** [comment]
@elasticmachine update branch

**Comment by martijnvg** [comment]
@elasticmachine update branch

**Pull request merged**
