### PR TITLE
Added standard deviation / variance sampling to extended stats

### LINKED ISSUE #49554: Add standard deviation / variance sampling to extended stats aggregation
Currently Elasticsearch offers standard deviation (STDDEV) and variance (VAR) both in [population form](https://en.wikipedia.org/wiki/Standard_deviation) however there's also the `sampling` form which depending on the data size, can yield significantly different results.
As it's just a matter of a (somewhat) different formula, it should be straight forward to expand the current implementation [Extended Stats](https://www.elastic.co/guide/en/elasticsearch///reference/current/search-aggregations-metrics-extendedstats-aggregation.html) to support this variant as well.

Potentially to avoid any ambiguities going forward, the current `std_deviation` could be aliased to `std_deviation_population` (same for `variance`) so one could easily pick up the desired type and while also being clear about what type the default fields are.

The improved response can look something like this:

```json
{
    ...

    "aggregations": {
        "grades_stats": {
           "count": 2,
           "min": 50.0,
           "max": 100.0,
           "avg": 75.0,
           "sum": 150.0,
           "sum_of_squares": 12500.0,
           "variance": 625.0,
           "variance_population": 625.0,  // same as "variance"
           "variance_sampling" : ...
           "std_deviation": 25.0,
           "std_deviation_population": 25.0, // same as std_deviation
           "std_deviation_sampling": ...,
           "std_deviation_bounds": {
            "upper": 125.0,
            "lower": 25.0
           },
        }
    }
}
```

### PR DESCRIPTION
**Pull request by andrewjohnson2**
Per 49554 I added standard deviation sampling and variance sampling to the extended stats interface. 

Closes #49554

### CODE REVIEW

**Review by costin — COMMENTED** [review]
LGTM.
I'm not sure if the lower/upper bounds shouldn't be different between std population and sampling.

**Review by csoulios — CHANGES_REQUESTED** [review]
Thank you for taking the time to implement this feature. 
Generally, LGTM too. 

Regarding upper and lower bounds, they are definitely different between population and sampling standard deviation. For the sake of completeness, I think they should be added too.

**Comment by polyfractal** [comment]
It would also be nice if the documentation could mention that the existing `std_dev` and `variance` are "population" metrics, so the user isn't confused by the new fields with identical values.

**Comment by andrewjohnson2** [comment]
thanks for the feedback! I will make those changes.

**Comment by imotov** [comment]
@elasticmachine test this please

**Comment by imotov** [comment]
@elasticmachine test this please

**Comment by imotov** [comment]
@costin, @csoulios I have added upper and lower bounds. @polyfractal I have added docs. Any other suggestions?

**Review by polyfractal — APPROVED** [review]
LGTM, thanks for pushing it over the finish line @imotov :)

**Review by csoulios — APPROVED** [review]

**Comment by imotov** [comment]
Thanks to @andrewjohnson2 for the PR and to @polyfractal and @csoulios for quick reviews!

**Pull request merged**
