### PR TITLE
Add RHEL UBI to dependency report

### PR DESCRIPTION
**Pull request by pugnascotia**
Add information about RHEL UBI to the dependency report task.

### CODE REVIEW

**Review by rjernst — APPROVED** [review]
LGTM, but wouldn't this be confusing for someone looking at the third party deps report and seeing UBI in there when they are not using docker (or the non UBI docker image)?

**Comment by pugnascotia** [comment]
As far as I am aware, the deps output goes to [a page on the website](https://www.elastic.co/third-party-dependencies), not into the ES distribution file itself.

**Review by mgreau — APPROVED** [review]
LGTM

**Comment by rjernst** [comment]
The website page is my exact concern. AFAIK we haven't had any docker specific dips shown in that report before. I wonder if we need a different dependency report. The problem I see is we have many distributions, yet the dependency report is inclusive of all of our distributions.

**Comment by pugnascotia** [comment]
Backported to `7.x` in cc33df87d398aadd6259fa4ed873c1da4a7a8bc2

**Pull request merged**
