### PR TITLE
Add BWC layer for Exceptions

### PR DESCRIPTION
**Pull request by s1monw**
Today it's not possible to add exceptions to the serialization layer
without breaking BWC. This commit adds the ability to specify the Version
an exception was added that allows to fall back not NotSerializableExceptionWrapper
if the exception is not present in the streams version.

Relates to #21656

### CODE REVIEW

**Comment by s1monw** [comment]
@ywelsch can you take a look

**Review by ywelsch — APPROVED** [review]
LGTM, I think the change in `Store` should be reverted though.

**Comment by s1monw** [comment]
@ywelsch I rolled back the changes to Store.java

**Comment by ywelsch** [comment]
5.0.2 backport: 83f6e84

**Comment by ywelsch** [comment]
adaptation to v6.0.0 to support 5.0.2 backport: c521219

**Comment by s1monw** [comment]
thanks @ywelsch

**Comment by ywelsch** [comment]
adaptation to v5.1.0 to support 5.0.2 backport: 05529d9

**Pull request merged**
