### PR TITLE
Time zone issue

### PR DESCRIPTION
**Pull request by priyadarsh**
Timezone shouldn't be part of date time or date for auto detection of date

### CODE REVIEW

**Comment by priyadarsh** [comment]
Signed the aggreement

**Comment by jpountz** [comment]
Sorry but I'm not sure to understand the motivation of this change? The timezone part is indeed optional and if you don't provide it then elasticsearch will assume UTC. But if you do provide it then elasticsearch will still auto-detect dates and make use of the time-zone parameter to parse the date correctly.

**Comment by priyadarsh** [comment]
Sorry for not being clear. Auto detection of date string was not working in 2.0 when timezone is passed. So I assumed that timezone is not required. I should have raised an issue. Please close this request if the timezone is optional and I will raise a separate issue.

**Comment by jpountz** [comment]
> Auto detection of date string was not working in 2.0 when timezone is passed.

Can you give an example of document that fails auto-detection of a date field so that we can look into the problem?

**Comment by clintongormley** [comment]
@priyadarsh Auto-detection of dates with time zones works correctly:

    DELETE test 
    
    PUT test/test/1
    {
      "date": "2010-01-01T12:00:00+02:00"
    }
    
    GET test/_mapping

return:

    {
      "test": {
        "mappings": {
          "test": {
            "properties": {
              "date": {
                "type": "date",
                "format": "strict_date_optional_time||epoch_millis"
              }
            }
          }
        }
      }
    }


Note: The time zone must use two digits for the hour, ie `+02:00`, but not `+2:00`

**Pull request closed without merging**
