### PR TITLE
Cleanup some Dead Code in o.e.index.store

### PR DESCRIPTION
**Pull request by original-brownbear**
One obviously unused method and an incorrect Javadoc that
referenced an otherwise unused class.

### CODE REVIEW

**Review by dnhatn — APPROVED** [review]
LGTM

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/1 (some unrelated Gradle thing that keeps happening today)

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/1 (some unrelated Gradle thing that keeps happening today)

**Comment by original-brownbear** [comment]
Thanks Nhat!

**Pull request merged**
