### PR TITLE
[8.12] [LTR] Enable by default on stateful only (#103333)

### PR DESCRIPTION
**Pull request by afoucret**
Backports the following commits to 8.12:
 - [LTR] Enable by default on stateful only (#103333)

### CODE REVIEW

**Review by Mikep86 — APPROVED** [review]

**Review by kderusso — APPROVED** [review]
LGTM

**Comment by afoucret** [comment]
@elasticsearchmachine  run elasticsearch-ci/packaging-tests-windows-sample

**Comment by afoucret** [comment]
@elasticsearchmachine run elasticsearch-ci/windows-2019

**Comment by afoucret** [comment]
@elasticsearchmachine run elasticsearch-ci

**Review by saikatsarkar056 — APPROVED** [review]

**Pull request merged**
