### PR TITLE
Add license checks for autoscaling

### PR DESCRIPTION
**Pull request by jasontedor**
This commit enables license checks for autoscaling. Autoscaling will be licensed under at the Enterprise license tier. All REST actions except for deleting autoscaling policies when a license is out of compliance.

### CODE REVIEW

**Review by henningandersen — APPROVED** [review]
LGTM.

**Comment by jasontedor** [comment]
@elasticmachine update branch

**Comment by jasontedor** [comment]
@elasticmachine update branch

**Comment by jasontedor** [comment]
@elasticmachine update branch

**Comment by jasontedor** [comment]
@elasticmachine update branch

**Pull request merged**
