### PR TITLE
Release notes for 7.9.2

### PR DESCRIPTION
**Pull request by danhermann**
Please adjust reviewers as appropriate.

### Preview

https://elasticsearch_62664.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/7.9/release-notes-7.9.2.html

### CODE REVIEW

**Review by jrodewig — APPROVED** [review]
LGTM. Pushed one commit to add an xref to the release notes page.

**Comment by lcawl** [comment]
Added PRs from https://raw.githubusercontent.com/elastic/ml-cpp/7.9/docs/CHANGELOG.asciidoc and removed a misidentified transform issue.

**Review by lcawl — APPROVED** [review]
ML details LGTM

**Comment by danhermann** [comment]
Thank you, @lcawl and @jrodewig for the review. I updated the PR in https://github.com/elastic/elasticsearch/pull/62664/commits/0fbf59e1405c1bb6e513612f8491fd25fa4e331e to include the new items added in BC2. Only the ES binaries were changed so there should be no new ML items.

**Review by jrodewig — APPROVED** [review]
The BC2 additions LGTM.

**Pull request merged**
