### PR TITLE
Refactor TransportSingleShardAction to serialize Writeable responses

### PR DESCRIPTION
**Pull request by talevy**
Previously, TransportSingleShardAction required constructing a new
empty response object. This response object's Streamable readFrom
was used. As part of the migration to Writeable, the interface here
was updated to leverage Writeable.Reader.

relates to #34389 (meta issue for Writeable refactor).

Should wait for #41915 before merging this

I tried making only the changes necessary to migrate to the new interface:

~~protected abstract Response newResponse();~~
protected abstract Writeable.Reader<Response> getResponseReader();

### CODE REVIEW

**Comment by talevy** [comment]
thanks for all your refactoring help @romseygeek and @javanna, to continue to do my part, I opened this in response to this adapter I saw: https://github.com/elastic/elasticsearch/pull/41915/files#r282295096.

this can wait for that PR first, though

**Review by romseygeek — APPROVED** [review]
LGTM

A next step could be to change TransportSingleShardAction to take a Writeable.Reader<Request> rather than a Supplier<Request> - I'll try pulling on that string next and see how big a ball I end up untying.

**Review by javanna — APPROVED** [review]
LGTM too thanks @talevy

**Comment by talevy** [comment]
run elasticsearch-ci/docbldesx

**Pull request merged**
