### PR TITLE
Added short comment on snapshotting closed indices

### PR DESCRIPTION
**Pull request by ppf2**
Trying again, didn't pick up changed file last time.

### CODE REVIEW

**Comment by imotov** [comment]
I think it should be "If the `indices` parameter specified includes *any* closed indices....". Otherwise LGTM.

**Comment by bleskes** [comment]
I might be missing something but I think we can also improve on the error message in this case? If the error message was clear like "can't snapshot closed indices" ,we could just say that only open yellow indices can be snapshotted. @imotov , what do you think?

**Comment by ppf2** [comment]
+1 on @bleskes 's idea on improving the reason message

**Comment by imotov** [comment]
@bleskes, @ppf2 I think you are right. I opened PR, which makes the message more clear.

**Comment by clintongormley** [comment]
Hi @ppf2 

It looks like you've mixed two different changes into this PR: one for Java versions and one for snapshot/restore. The latter is no longer accurate since https://github.com/elastic/elasticsearch/pull/10608 was pushed.

I'm going to close this PR - please feel free to open a new one with just the Java changes (or just push those changes directly)

thanks

**Pull request closed without merging**
