### PR TITLE
Fix compiler warnings

### PR DESCRIPTION
**Pull request by rjernst**
We have a handful of compiler warnings, mostly because of passing an
array to varargs methods. This change fixes these warnings and adds
-Werror so we don't get anymore of these warnings.

Note this does _not_ enable deprecation or unchecked type warnings, so
these remain "hidden". We should work towards removing those as well,
but this is a first step.

### CODE REVIEW

**Comment by rmuir** [comment]
Looks great!

> Note this does not enable deprecation or unchecked type warnings, so
> these remain "hidden". We should work towards removing those as well,
> but this is a first step.

Good, it at least prevents warnings of other types from stacking up. How bad is the unchecked situation? We should really open a followup for that one.

Deprecation is more complicated, especially if we want to deprecate our own apis. That one is less important I think.

**Comment by rjernst** [comment]
> How bad is the unchecked situation? 

Hundreds of warnings...

**Comment by rmuir** [comment]
Can we also turn on -Xlint ? I don't care if we then have to add -Xlint:-serial to disable some of the stupid ones, or ones that need fixes, but it would be nice to know where we stand.

**Comment by rjernst** [comment]
I turned on -Xlint and disabled the frequent ones I found, and fixed a handful of easy ones. There are some tricky ones we should really look into...

However, while core main/test now passes compile, I get a failure compiling tests for distribution/tar. But there is no warning, or any error at all... @dadoonet Could you try my branch and see if you understand why? I've run with -X but I don't see anything that explains why the failure occurred.

**Comment by s1monw** [comment]
> However, while core main/test now passes compile, I get a failure compiling tests for distribution/tar. But there is no warning, or any error at all... @dadoonet Could you try my branch and see if you understand why? I've run with -X but I don't see anything that explains why the failure occurred.

this is likely your JVM / Compiler we had problems her with `java version "1.8.0_31"` so if you run that I'd upgrade

**Comment by s1monw** [comment]
this is really weird if you run `mvn clean test-compile -X` you get the classpath it uses etc. to pass to `javac`. If I do this manually I get the following error:

```
warning: [path] bad path element "/Users/simon/projects/elasticsearch/distribution/tar/target/classes": no such file or directory
error: warnings found and -Werror specified
1 error
1 warning
```

creating `target/classes` fixes the issue

**Comment by s1monw** [comment]
hmm without `-Xlint:all` it passes

**Comment by dadoonet** [comment]
Funny. The same is happening in plugins but not for all plugins...
Analysis are working fine. Cloud-azure is failing... 

```
warning: [path] bad path element "/Users/dpilato/.m2/repository/com/sun/xml/bind/jaxb-impl/2.2.3-1/jaxb-api.jar": no such file or directory
warning: [path] bad path element "/Users/dpilato/.m2/repository/com/sun/xml/bind/jaxb-impl/2.2.3-1/activation.jar": no such file or directory
warning: [path] bad path element "/Users/dpilato/.m2/repository/com/sun/xml/bind/jaxb-impl/2.2.3-1/jsr173_1.0_api.jar": no such file or directory
warning: [path] bad path element "/Users/dpilato/.m2/repository/com/sun/xml/bind/jaxb-impl/2.2.3-1/jaxb1-impl.jar": no such file or directory
error: warnings found and -Werror specified
1 error
4 warnings
```

Looking at this ATM.

**Comment by dadoonet** [comment]
@rjernst Adding `<arg>-Xlint:-path</arg>` fixes the issue.

**Comment by dadoonet** [comment]
Just wondering if we should add a maven property like 

```xml
<lint.level>-Werror</lint.level>
```

And then define instead of `<arg>-Werror</arg>`:

```xml
<arg>${xlint.level}</arg>
```

So we could potentially run: `mvn clean install -Dlint.level=` which will not stop the build but WARN errors

**Comment by dadoonet** [comment]
@rjernst If you don't want to bypass path checks for each module, then add in parent pom:

```
<properties>
    <xlint.path></xlint.path>
</properties>
```

And:

```
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.3</version>
                    <configuration>
                        <fork>true</fork>
                        <maxmem>512m</maxmem>
                        <!-- REMOVE WHEN UPGRADE:
                             see https://jira.codehaus.org/browse/MCOMPILER-209 it's a bug where
                             incremental compilation doesn't work unless it's set to false causeing
                             recompilation of the entire codebase each time without any changes. Should
                             be fixed in version > 3.1
                         -->
                        <useIncrementalCompilation>false</useIncrementalCompilation>
                        <showWarnings>true</showWarnings>
                        <compilerArgs>
                            <arg>-XDignore.symbol.file</arg>
                            <arg>-Xlint:all</arg>
                            <arg>${xlint.path}</arg>
                            <arg>-Xlint:-cast</arg>
                            <arg>-Xlint:-deprecation</arg>
                            <arg>-Xlint:-fallthrough</arg>
                            <arg>-Xlint:-overrides</arg>
                            <arg>-Xlint:-rawtypes</arg>
                            <arg>-Xlint:-serial</arg>
                            <arg>-Xlint:-try</arg>
                            <arg>-Xlint:-unchecked</arg>
                            <arg>-Werror</arg>
                        </compilerArgs>
                    </configuration>
                </plugin>
```

In distribution/pom.xml:

```
<properties>
    <xlint.path>-Xlint:-path</xlint.path>
</properties>
```

Same in cloud-azure (and may be some others)...

**Comment by rjernst** [comment]
> Just wondering if we should add a maven property

No, I don't think we should do that, because the next step is "let's set the default back to warn". This PR fixes issues, we don't want to go backwards from there. And there are some we really need to investigate (see some of the TODOs I added in this).

**Comment by rjernst** [comment]
@dadoonet thanks for the suggestion on parameterizing -Xling:-path. I actually want to just be able to add additional compiler args within a child pom, eg core. This way the warning removals can be isolated to the modules that need them, instead of allowing leniency in all modules.

**Comment by dadoonet** [comment]
@rjernst then add in parent pom:

```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>3.3</version>
    <configuration>
        <fork>true</fork>
        <maxmem>512m</maxmem>
        <!-- REMOVE WHEN UPGRADE:
             see https://jira.codehaus.org/browse/MCOMPILER-209 it's a bug where
             incremental compilation doesn't work unless it's set to false causeing
             recompilation of the entire codebase each time without any changes. Should
             be fixed in version > 3.1
         -->
        <useIncrementalCompilation>false</useIncrementalCompilation>
        <showWarnings>true</showWarnings>
        <compilerArgs>
            <arg>-XDignore.symbol.file</arg>
            <arg>-Xlint:all</arg>
            <arg>-Xlint:-path</arg>
            <arg>-Werror</arg>
        </compilerArgs>
    </configuration>
</plugin>
```

In core/pom.xml:

```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <configuration>
        <compilerArgs>
            <arg>-XDignore.symbol.file</arg>
            <arg>-Xlint:all</arg>
            <arg>-Xlint:-path</arg>
            <arg>-Werror</arg>
            <arg>-Xlint:-cast</arg>
            <arg>-Xlint:-deprecation</arg>
            <arg>-Xlint:-fallthrough</arg>
            <arg>-Xlint:-overrides</arg>
            <arg>-Xlint:-rawtypes</arg>
            <arg>-Xlint:-serial</arg>
            <arg>-Xlint:-try</arg>
            <arg>-Xlint:-unchecked</arg>
        </compilerArgs>
    </configuration>
</plugin>
```

But you don't really inherit from parent pom. You have to declare again all compilerArgs.

**Comment by dadoonet** [comment]
Ok so here is a better solution.

In `/pom.xml`:

```xml
    <properties>
        <xlint.options/>
    </properties>

...

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.3</version>
                    <configuration>
                        <fork>true</fork>
                        <maxmem>512m</maxmem>
                        <!-- REMOVE WHEN UPGRADE:
                             see https://jira.codehaus.org/browse/MCOMPILER-209 it's a bug where
                             incremental compilation doesn't work unless it's set to false causeing
                             recompilation of the entire codebase each time without any changes. Should
                             be fixed in version > 3.1
                         -->
                        <useIncrementalCompilation>false</useIncrementalCompilation>
                        <showWarnings>true</showWarnings>
                        <compilerArgs>
                            <arg>-XDignore.symbol.file</arg>
                            <arg>-Xlint:all</arg>
                            <arg>-Xlint:-path</arg>
                            <arg>${xlint.options}</arg>
                            <arg>-Werror</arg>
                        </compilerArgs>
                    </configuration>
                </plugin>
```

In `core/pom.xml`:

```
    <properties>
        <xlint.options>-Xlint:-cast,-deprecation,-fallthrough,-overrides,-rawtypes,-serial,-try,-unchecked</xlint.options>
    </properties>
```

That said, there are also some deprecated classes in plugins, so I would also add in parent pom `-deprecation` option.

**Comment by rjernst** [comment]
@dadoonet @s1monw  Thanks for maven help. I've added suppressions and ignores specific to each module where needed. I think this is ready.

**Comment by rjernst** [comment]
Pushing as this really hasn't changed other than limiting which xlint options are used.

**Pull request merged**
