### PR TITLE
[ML] Make PUT data frame analytics action a master node action

### PR DESCRIPTION
**Pull request by dimitris-athanasiou**
While it seemed like the PUT data frame analytics action did not
have to be a master node action as the config is stored in an index
rather than the cluster state, there are other subtle nuances which
make it worthwhile to convert it. In particular, it helps maintain
order of execution for put actions which are anyhow user driven and
are expected to have low volume.

This commit converts `TransportPutDataFrameAnalyticsAction` from
a handled transport action to a master node action.

Note this means that the action might fail in a mixed cluster
but as the API is still experimental and not widely used there will
be few moments more suitable to make this change than now.

### CODE REVIEW

**Comment by dimitris-athanasiou** [comment]
run elasticsearch-ci/bwc

**Comment by dimitris-athanasiou** [comment]
run elasticsearch-ci/default-distro

**Review by przemekwitek — APPROVED** [review]
LGTM

**Review by droberts195 — APPROVED** [review]
LGTM

**Comment by dimitris-athanasiou** [comment]
@elasticmachine update branch

**Pull request merged**
