### PR TITLE
Make version field names more meaningful 

### PR DESCRIPTION
**Pull request by alpar-t**
Replaces the recently added  `version.build_version` with `version.qualified` in the main response. 
We refer to it as `version_qualified` in the doc tests.

### CODE REVIEW

**Comment by atorok** [comment]
CC @elastic/es-clients

**Review by nik9000 — APPROVED** [review]
LGTM.  Thanks for doing it!

**Comment by jasontedor** [comment]
I am sorry I am catching this after merge, but I am not onboard with this change. Why are we not reporting the qualifier in the version.number field as we did previously?

**Comment by atorok** [comment]
@jasontedor that was my initial line of thinking but then I looked at how snapshot is treated and taught of being consistent with that. The server does no longer grasp the concept of a qualifier, the only reason it's not fully cleaned up is that we still have some versions that have it. Server does know about the version as presented by the build which has both qualifier and snapshot. Are you ok with having `version.number` potentially contain both snapshot and qualifier ? This would imply that `Version.fromString` would ignore them when creating a `Version` object. 
@nik9000  do you like that proposal ?

**Pull request merged**
