### PR TITLE
Enhance multiple data path shard allocation strategy

### PR DESCRIPTION
**Pull request by howardhuanghua**
Current 6.x including master branch have issue with shard path allocation strategy in multiple data path scenario. If one of the path has most free space left, it will be allocated several times of shards compare to other path which would cause IO performance imbalance.

Current code logic tries to use three level compare to sort multiple paths during selecting path.
1. Shard count of current index on each data path.
2. Total shard count over all indices on each data path.
3. Free space on each data path.

But for second condition, **this count get from IndexService.java line 352-360, it's only count shard number for current index.** So the first and second condition should be the same.

I moved calculating shard count for each path logic into ShardPath.java, and work through data path to calculate shard count, current index shard count and free space for each path together.
NewPathForShardTests.java test case also has been updated, I think we don't need to pass dataPathToShardCount parameter anymore, instead we should calculate it internally. 

Thanks,
Howard

### CODE REVIEW

**Comment by pcsanwald** [comment]
@danielmitterdorfer we discussed this in fixit friday, can your team have a look at this PR?

**Comment by danielmitterdorfer** [comment]
@pcsanwald sure, I originally labelled it as "discuss" as I thought it might be of interest to the entire team.

**Comment by yunchenglu** [comment]
I think the original code has considered about shard count, it just only consider about local index, so we can reuse this as global indices shard count. it is simpler
So I Pull Request #37644 
@danielmitterdorfer @pcsanwald @howardhuanghua

**Comment by howardhuanghua** [comment]
Thanks @yunchenglu @ywelsch @danielmitterdorfer @pcsanwald 
The reasons I considered to put global shard per path calculation in ShardPath.java selectNewPathForShard are:
1. Only multiple data path case needs to consider global shard per path.
   We have "if (paths.length != 1)" pre-condition. Otherwise we need to always traverse all the indices shard path in IndicesService.java.

2. In multiple data path case, I traverse global indices shard path one time in selectNewPathForShard function to calculate both pathToGloableShardCount, pathToCurrentIndexShardCount and pathToSpace mappings. Then we don't need separate loop to re-calculate each of them.

Previously, I have considered to get shard count to path mapping through global cluster state or in memory meta info, but I haven't found it. So I reused the shard path traversing. But this may have potential performance issue when node gets huge shards.

Thanks,
Howard

**Comment by howardhuanghua** [comment]
@danielmitterdorfer Would you please help to check this PR?

**Comment by rjernst** [comment]
Multiple data paths will be deprecated in 7.13 and removed in 8.0 (see https://github.com/elastic/elasticsearch/issues/71205). Given that, I believe this PR is no longer relevant, so I will close it.

**Pull request closed without merging**
