### PR TITLE
[ML] JIndex: Restore finalize job action

### PR DESCRIPTION
**Pull request by davidkyle**
Feature branch PR for the master feature branch

TransportFinalizeJobExecutionAction has already been restored to 6.x and its use simplifies the code in AutoDetectResultsProcessor.

Plus some small non-functional changes to match the 6.x branch

This is the same as previously opened #35856 but without the extra 300 commits

### CODE REVIEW

**Review by droberts195 — APPROVED** [review]
LGTM

**Comment by davidkyle** [comment]
run gradle build tests 2

**Comment by davidkyle** [comment]
The rolling upgrade tests are failing because the PR build runs against 6.x instead of the feature branch version of 6.x The specific problem is [streaming MlMetaData](https://github.com/elastic/elasticsearch/blob/feature-jindex-master/x-pack/plugin/core/src/main/java/org/elasticsearch/xpack/core/ml/MlMetadata.java#L169) 

```
        if (out.getVersion().onOrAfter(Version.V_6_6_0)) {
            out.writeOptionalLong(lastMemoryRefreshVersion);
        }
```

This code is on the feature branches not the trunk branches so the above is written by the upgraded node but not read by a 6.6 nodes leaving it on the wire and subsequently breaking parsing of the clusterstate routing table.

**Comment by davidkyle** [comment]
Merging without a green build as the BWC tests will never go green. Feature branch CI will find errors.

**Pull request merged**
