### PR TITLE
Contradictory type checks

### PR DESCRIPTION
**Pull request by krisds**
As requested, I will split #38033 into separate PRs. Here is the second part.

This one resolves:
* [Contradictory type checks](https://lgtm.com/projects/g/elastic/elasticsearch/snapshot/dist-1916470085-1548143539391/files/x-pack/plugin/sql/src/main/java/org/elasticsearch/xpack/sql/planner/QueryTranslator.java#xa88ea97f7b1036f1:1)

### CODE REVIEW

**Comment by costin** [comment]
Looks like I've commented incorrectly at https://github.com/elastic/elasticsearch/pull/38151#issuecomment-459666276

I'll post it here FTR:
> Thanks for raising the PR.
> However I don't think the proposed solution is correct; I can see how an analysis tool will pick it up (Literal and NamedExpression used to be different hierarchies which got unified at some point though they might be split again).
> As the literal already inherits the NamedExpression behavior , the correct solution would be to remove the literal check all together - let me know if you want to pursue this or not.
> Thanks,

**Comment by javanna** [comment]
hi @krisds have you seen the comment above? Are you for addressing your PR? Thanks!

**Comment by krisds** [comment]
@javanna Yes, I can fix that. Will do.

**Comment by javanna** [comment]
@costin can you have a look and merge this when ready please?

**Comment by javanna** [comment]
test this please

**Comment by matriv** [comment]
Closing this PR as the code has been changed and the relevant block doesn't exist anymore.

**Pull request closed without merging**
