### PR TITLE
RestClient: on retry timeout add root exception

### PR DESCRIPTION
**Pull request by Timshel**

### CODE REVIEW

**Review by cbuescher — APPROVED** [review]
LGTM, will kick of a CI build before merging this.

**Comment by cbuescher** [comment]
@elasticmachine test this please

**Comment by javanna** [comment]
can we have a test for this?

**Comment by Timshel** [comment]
I just realized that another fix might be to move `listener.trackFailure(exception);` before the `if (timeout <= 0)` block this way the `Exception` would be added to the suppressed list as usual.

**Comment by Timshel** [comment]
From what I understand calling first `trackFailure` will add the root exception to `FailureTrackingResponseListener` and then the following call to `onDefinitiveFailure` will have for result to add this root exception in the suppressed list of the `IOException`.

If we take two different scenario (with multiple available nodes in both case) : 
 - 1 : the timeout delay is set to 0 there is no retry
 - 2 : the timeout is sufficient for one retry which fail

With no fix the result look like :
 - 1 : `IOException()`
 - 2 : `IOException(suppressed: [Call1Exception])`

With the current PR fix the resulting IOException look like :
 - 1 : `IOException(cause: Call1Exception)`
 - 2 : `IOException(suppressed: [Call1Exception], cause:  Call2Exception)`

If the `trackFailure` is always called before checking the time left it will look like :
 - 1 : `IOException(suppressed: [Call1Exception])`
 - 2 : `IOException(suppressed: [Call1Exception, Call2Exception])`

At first I thought always having the exceptions in suppressed might be better, but after writing it, I think always having the exception of the last call in cause (easier to access than the suppressed list) might be better.

So in the end I think the current PR is better (Sorry for the complications :).

**Comment by javanna** [comment]
hey @Timshel thanks for the explanation. I think we are in agreement, but I have another question: when the retry timeout is set to `0`, what would be the suppressed exception if there were no previous retries? Seems to me that there would be no cause, but I may be missing something.

I am also considering changing the behaviour here to rely solely on socket and connect timeout from the underlying http client for the first attempt, without having the maxRetryTimeout affect it. retry timeout instead should kick from the second attempt on. What do you think about this?

**Comment by Timshel** [comment]
When the retry is set to 0, the exception is the initial error. In my exemple `Call2Exception` is the first retry call.

I'm not sure I understand, if by first attempt you mean first retry then I don't believe it's possible because `startTime` is the start of the original query. 
When `timeout > 0` it could be set as the timeout of the retry query.

**Comment by Timshel** [comment]
Is there anything blocking the merge of this PR ?

**Comment by nik9000** [comment]
@javanna, I think this one is at least missing a test. Maybe it needs to change in some way based on the conversation you had above? Can you comment?

**Comment by jasontedor** [comment]
@elasticmachine test this please

**Review by jasontedor — APPROVED** [review]
LGTM. I don't think adding a test here is necessary, we don't add tests everywhere that we catch and rewrap an exception.

**Comment by jasontedor** [comment]
Thanks @Timshel. Sorry the delay in seeing this one integrated.

**Pull request merged**
