### PR TITLE
Add logging in GlobalCheckpointSyncIT

### LINKED ISSUE #88428: [CI] GlobalCheckpointSyncIT testBackgroundGlobalCheckpointSync failing
**Build scan:**
https://gradle-enterprise.elastic.co/s/frehaqs2hrhe4/tests/:server:internalClusterTest/org.elasticsearch.index.seqno.GlobalCheckpointSyncIT/testBackgroundGlobalCheckpointSync

**Reproduction line:**
`./gradlew ':server:internalClusterTest' --tests "org.elasticsearch.index.seqno.GlobalCheckpointSyncIT.testBackgroundGlobalCheckpointSync" -Dtests.seed=19EB2D16676B55E5 -Dtests.locale=es-SV -Dtests.timezone=Indian/Antananarivo -Druntime.java=17`

**Applicable branches:**
8.3

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.index.seqno.GlobalCheckpointSyncIT&tests.test=testBackgroundGlobalCheckpointSync

**Failure excerpt:**
```
org.apache.lucene.store.AlreadyClosedException: engine is closed

  at __randomizedtesting.SeedInfo.seed([19EB2D16676B55E5:C85E2309EA9D031E]:0)
  at org.elasticsearch.index.shard.IndexShard.getEngine(IndexShard.java:2971)
  at org.elasticsearch.index.shard.IndexShard.seqNoStats(IndexShard.java:1261)
  at org.elasticsearch.index.seqno.GlobalCheckpointSyncIT.lambda$runGlobalCheckpointSyncTest$7(GlobalCheckpointSyncIT.java:197)
  at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1086)
  at org.elasticsearch.index.seqno.GlobalCheckpointSyncIT.runGlobalCheckpointSyncTest(GlobalCheckpointSyncIT.java:192)
  at org.elasticsearch.index.seqno.GlobalCheckpointSyncIT.testBackgroundGlobalCheckpointSync(GlobalCheckpointSyncIT.java:89)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:568)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:44)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:45)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:38)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at org.apache.lucene.tests.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
  at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
  at org.apache.lucene.tests.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:44)
  at org.apache.lucene.tests.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:60)
  at org.apache.lucene.tests.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:47)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:833)

```

### PR DESCRIPTION
**Pull request by Tim-Brooks**
The test GlobalCheckpointSyncIT#testBackgroundGlobalCheckpointSync
failed once recently due to an engine already close exception. It has
not occurred again and the reasoning is unclear.

This commit adds a log line to indicate exactly when it happens, which
shard it is, and what the current state of the index shard is.

Closes #88428.

### CODE REVIEW

**Review by kingherc — COMMENTED** [review]
LGTM. Could also just add a logger.info/debug that always happens for all shard IDs/states, instead of try/catching alternatively. But I assume you'd like to log the specific shard ID/state, right @tbrooks8 ?

**Review by DaveCTurner — APPROVED** [review]
LGTM2 but note that we're not including the `AlreadyClosedException` (plus stack trace) in the log message. Not sure of the context but maybe that'd be helpful?

**Comment by tbrooks8** [comment]
> LGTM2 but note that we're not including the AlreadyClosedException (plus stack trace) in the log message. Not sure of the context but maybe that'd be helpful?

@DaveCTurner 

The exception gets thrown and ends up as the test failure. So that is why I left it out so it did not get printed twice? I mostly wanted to propagate the shard id and state if this happens again. Does this make sense?

**Comment by DaveCTurner** [comment]
> Does this make sense?

Yep, perfectly, just thought it worth checking.

**Comment by tbrooks8** [comment]
>  But I assume you'd like to log the specific shard ID/state, right @tbrooks8 ?

Yes pretty much just trying to catch in a face of an unexpected failure.

**Pull request merged**
