### PR TITLE
Rollup performance improvement:  index bucket replace map with smile builder

### PR DESCRIPTION
**Pull request by weizijun**
index bucket replace map with smile builder.
It can greatly improve the build source and index api performance.

### CODE REVIEW

**Comment by csoulios** [comment]
@elasticmachine ok to test

**Review by csoulios — COMMENTED** [review]
This change theoretically improves indexing performance.
Have you benchmarked its impact? Can you share any numbers?

Also, can you please merge from upstream and resolve conflicts?

Thanks

**Comment by weizijun** [comment]
before:


after:


In my benchmark, the downsampling cost from 2.4 minute to 2.2 minute.

**Comment by csoulios** [comment]
@weizijun thanks for posting the graphs and results. 

It is worth noting the downsampling interval as well as the ratio of source_index_doc_count/rollup_index_doc_count.

We deem the downsampling operation spends more time in reading the source index than writing to the rollup index. So, improving the write part of the operation will yield small improvements compared to improving the read part.

However, this change makes perfect sense and we plan to merge it.

**Review by csoulios — APPROVED** [review]
LGTM!

**Comment by weizijun** [comment]
> @weizijun thanks for posting the graphs and results.
> 
> It is worth noting the downsampling interval as well as the ratio of source_index_doc_count/rollup_index_doc_count.
> 
> We deem the downsampling operation spends more time in reading the source index than writing to the rollup index. So, improving the write part of the operation will yield small improvements compared to improving the read part.
> 
> However, this change makes perfect sense and we plan to merge it.

Thanks @csoulios !

**Pull request merged**
