### PR TITLE
add local cardinality

### PR DESCRIPTION
**Pull request by yynil**
if the distinct value is already the routing one, just merge the HLL's results instead of the objects.

### CODE REVIEW

**Comment by yynil** [comment]
For a distinct count metric aggregation, if the distinct value is already the routing one, user_id for an example, the merge node doesn't need to merge all HLL objects. The merge node just needs to merge the result(just a long value) of all distributed HLL objects in all shard nodes. It saves the network and cpu in both the shard nodes and the merge node.
Though it's rare in a lot of distinct aggregation that the distinct value equals the routing value, it's useful for those who already do the tricks. It's especially useful in calculating the unique users in web analytics.

**Comment by jpountz** [comment]
Things are indeed much easier if the field values are unique per shard. We would probably not even need HLL and could just collect seen ordinals in a bit set and count the number of set bits.

I will put this PR on hold as there is a large ongoing refactoring of aggregations (#14136) but tend to agree it would be nice to do something.

**Comment by dakrone** [comment]
@jpountz now that the agg refactoring is merged is this something we should revisit?

**Comment by jpountz** [comment]
Yes.

**Comment by yynil** [comment]
In case this implementation, I find there is a bug in it. I will submit another code change to this repository to fix this bug.

**Comment by yynil** [comment]
Hi,@jpountz  I just checked the fixes I've made recently. The fixes include : 1. fix the status missing after reducing. 2. make it compilable in the upstream/master.
However I still have a serious situation that's test. The previous test cases I wrote can't be compiled and the new environment is quite a myth for me. I hope I could understand the system more quickly, but without any instructions, the improvements are very little. Would you please show me some full examples that I can write the cardinality test case? Thanks a lot!

**Comment by yynil** [comment]
@jpountz Also what I wanna do is the exact cardinality using local bitmap based on the local cardinality function. But I need to finish the test case first, then I can continue to develop more codes.

**Comment by jpountz** [comment]
> However I still have a serious situation that's test. The previous test cases I wrote can't be compiled and the new environment is quite a myth for me.

What exact problem are you having? Maybe you can look at how other aggregations work?

> Also what I wanna do is the exact cardinality using local bitmap based on the local cardinality function.

+1. I think we could do it automatically when there is a single queried shard (SearchContext.numberOfShards() == 1) and the memory usage of the bitmap would be lower than the HyperLogLog structure.

**Comment by yynil** [comment]
Actually the problem is that I'm not very familiar with JUnit. So I want to find some already implemented aggregation test cases and copy&modify them. Unfortunately my lack of JUnit knowledge didn't find out which aggregation test case in the mainstream repository is complete. Never mind I will solve the problem anyway.
For the bitmap function, I wanna to create a new optional parameter in the cardinality  aggregation since we have various situations to use Elastic Search. In some cases memory does matter and in other cases memory doesn't. I think it will be better to leave this decision to the actual users.

**Comment by jpountz** [comment]
I would suggest that we deal with the bitmap optimization in a different PR and focus on transporting the shard cardinality rather than the HyperLogLog structure in this one. Does it work for you?

> For the bitmap function, I wanna to create a new optional parameter in the cardinality aggregation since we have various situations to use Elastic Search.

I do not want to add too many parameters to this aggregation. In my opinion, there should be a single parameter that tells elasticsearch that it can assume that shards have disjoint values. This will mean that it can transport the cardinality using a long rather than the HyperLogLog structure. And also that it can use a bitmap locally if the memory usage of the bitmap would be less than the hyperloglog for the configured `precision_threshold`. If someone wants to use a bitmap all the time, (s)he would just have to pass a high value for `precision_threshold.

By the way, maybe we should rename `isSumDirectly` to `disjoint_shard_values`. I think this is more descriptive of what this optimization is about?

**Comment by yynil** [comment]
@jpountz you suggestions are good to me, I'll change the configuration and make only one parameter exist, then the precision can help to decide if bitmap is used. 
For the JUnit test, I'm a little bit confused about the tests in the aggregation packages. For an example, the average test, there are two files AvgIT and AvgTests. Neither one is testable. From my understanding, AvgTests should do the real job, am I right?
I also wanna know the schedule of 5.0.0. Since I'm kinda busy for now, I'm afraid I can't catch up your guys pace.

**Comment by jpountz** [comment]
> AvgIT and AvgTests

AvgTests tests things like serialization and parameter validation. AvgIT starts an elasticsearch cluster, runs avg aggregations on it and checks the response (`IT` stands for Integration Test). What do you mean by "neither one is testable"?

> I also wanna know the schedule of 5.0.0. Since I'm kinda busy for now, I'm afraid I can't catch up your guys pace. 

We are working towards releasing 5.0, but there is no date set in stone.  The only thing I can tell for sure that it will still take at least a couple more weeks since we only released an alpha version so far. For the record, there would be no issue getting this feature in 5.1 or 5.2.

**Comment by yynil** [comment]
> "neither one is testable"?
I use "gradle test --tests" parameter, when I input *Avg*, no tests run. But when I run *JsonVsCborTests*, it tests and run successfully. I'll do deeper dig to understand it better.

**Comment by rjernst** [comment]
> I use "gradle test --tests" parameter, when I input Avg, no tests run

The `--tests` parameter doesn't work because we dont use the gradle test runner. See `TESTING.asciidoc` at the root of the project for help on how to run individual tests.

**Comment by dakrone** [comment]
@jpountz can this be marked as un-stalled now that the aggregation refactor is done, or is there still interest in this PR?

**Comment by dakrone** [comment]
@jpountz ping again about this

**Comment by dakrone** [comment]
@jpountz is this still stalled?

**Comment by jpountz** [comment]
I am +1 on reviving this PR.

**Comment by dakrone** [comment]
@yynil would you be willing to merge master into this branch to fix up the conflicts so it can be review again?

**Comment by rjernst** [comment]
@yynil I'm closing this PR as it appears dead. Please feel free to reopen when/if you have the time to sync it up with the latest master.

**Pull request closed without merging**
