### PR TITLE
Fix shutdown race condition in server start

### PR DESCRIPTION
**Pull request by rjernst**
When the server CLI is preparing to start Elasticsearch, it may receive a SIGTERM. That signal causes the close method of the CLI to be invoked, which checks for a non-null server process, and stops it if it exists. Since shutdown occurs in a different thread, it is possible close is invoked, sees the server process is null, so skips calling close, but then before close finishes the server process is started.

Normally the above case is ok; the close method will cause Java to exit, and the child process will be sent a SIGTERM. However, in the case of serverless, close is wrapped so that the CLI can wait on uploading possible heapdumps. This presents the possibility that close thinks the child process has been stopped, but it hasn't, so the wrapped close waits indefinitely on the child process that was started up during the race.

This commit guards against the startup race by locking the critical sections that create the child process and stop it. Either the child process is created first, and will then be stopped immediately, or close is invoked first, marking that the CLI is shutting down, and creating the child process will be skipped.

### CODE REVIEW

**Comment by rjernst** [comment]
Note that this is only applicable when the ServerCli is subclassed and close overriden, so I've marked this as a non-issue.

**Review by ldematte — APPROVED** [review]
That's very cool! How did you find it?

**Comment by rjernst** [comment]
> How did you find it?
I saw we were actually getting the SIGTERM that disappeared, inside the cli. Once I knew that, I stared at the code, and realized the finished latch could cause us to block indefinitely, so I thought about how that might never release. :)

**Comment by ldematte** [comment]
Nice! Thanks for the explanation (and for fixing this)

**Pull request merged**
