### PR TITLE
Remove deprecated endpoints of hot threads API

### PR DESCRIPTION
**Pull request by muachilin**
This PR proceeds to remove deprecated endpoints in hot threads action.

[issue: #52640]

### CODE REVIEW

**Review by nik9000 — APPROVED** [review]
Looks good to me!

**Comment by nik9000** [comment]
@elasticmachine, test this please.

@jasontedor, do you think this is worth a line in the breaking changes list? We never documented these in the first place but it'd be a kind thing to do I think.

**Comment by jasontedor** [comment]
Yes, we should add a note to the breaking changes docs. While these endpoints were not documented in the reference docs, they are in the REST spec. Also, we try to document when we break other things we don’t document, for example, the recent removal of the undocumented `node.local_storage` setting.

**Comment by nik9000** [comment]
> Yes, we should add a note to the breaking changes docs. While these endpoints were not documented in the reference docs, they are in the REST spec. Also, we try to document when we break other things we don’t document, for example, the recent removal of the undocumented `node.local_storage` setting.

+1

@muachilin, would you like to add an update to `docs/reference/release-notes/8.0.0-alpha1.asciidoc` for the breaking change? I'd be happy to do it if you don't find it obvious what to add.

Also, it looks like there is a checkstyle error. Could you fix it?
```
RestNodesHotThreadsAction.java:37:8: Unused import - java.util.Locale. [UnusedImports]
```

Somthing like:
```
./gradlew -p server precommit && ./gradlew -p server check
```
would probably be worth doing on this locally.

**Comment by muachilin** [comment]
@elasticmachine, test this please.

**Comment by muachilin** [comment]
@elasticmachine update branch

**Comment by nik9000** [comment]
@elasticmachine, test this please.

**Comment by nik9000** [comment]
I think this is good! I'm going to merge.

**Comment by nik9000** [comment]
Thanks @muachilin !

**Comment by muachilin** [comment]
Thank you!

**Pull request merged**
