### PR TITLE
Consistent case in CLI option descriptions

### PR DESCRIPTION
**Pull request by orhantoy**
I noticed a few inconsistencies in the CLI option descriptions:

```
$ bin/elasticsearch --help
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
starts elasticsearch

Option                Description
------                -----------
-E <KeyValuePair>     Configure a setting
-V, --version         Prints elasticsearch version information and exits
-d, --daemonize       Starts Elasticsearch in the background
-h, --help            show help
-p, --pidfile <Path>  Creates a pid file in the specified path on start
-q, --quiet           Turns off standard output/error streams logging in console
-s, --silent          show minimal output
-v, --verbose         show verbose output
```

1. `Prints elasticsearch [...]` vs `Starts Elasticsearch [...]`
2. Starting with lowercase in `show help`, `show minimal output` and `show verbose output`
3. Also, command description is currently all lowercase: `starts elasticsearch`

### CODE REVIEW

**Comment by orhantoy** [comment]
Noticed that the other CLIs like `bin/elasticsearch-setup-passwords`, `bin/elasticsearch-certgen` etc also have inconsistencies. Might be worth looking into those as well.

**Comment by rjernst** [comment]
@elasticmachine ok to test

**Comment by rjernst** [comment]
@elasticmachine update branch

**Comment by rjernst** [comment]
Thanks for the contribution @orhantoy.

**Pull request merged**
