### PR TITLE
Rest-High-Level-Client:fix uri encode bug when url path start with '/'

### LINKED ISSUE #34433: [Rest High Level Client]:Error parse when document Id start with '/'
**Describe the feature**:

**Elasticsearch version** :6.4.0

**Plugins installed**: []

**JVM version** :1.8

**OS version**:win10

**Rest High Level Client Version**:6.4.2

**Description of the problem including expected versus actual behavior**:
The rest-high-level-client make mistakes when a document id start with '/'

**Steps to reproduce**:

 1.
```
       RestHighLevelClient client = new RestHighLevelClient(
                RestClient.builder(new HttpHost("localhost", 9200, "http")));

        /*the expected id is /abc/error_id*/
        GetRequest request = new GetRequest("index", "type", "/abc/error_id");
        GetResponse rsp = client.get(request, RequestOptions.DEFAULT);
        /*the actual id is error_id*/
        System.out.println(rsp.getId());
```
 2.
```
      RestHighLevelClient client = new RestHighLevelClient(
                RestClient.builder(new HttpHost("localhost", 9200, "http")));

        /*the expected id is /id*/
        GetRequest request = new GetRequest("index", "type", "/id");
        GetResponse rsp = client.get(request, RequestOptions.DEFAULT);

       you will get a exception in this case:

Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1931)
	at org.elasticsearch.client.RequestConverters$EndpointBuilder.encodePart(RequestConverters.java:1532)
	at org.elasticsearch.client.RequestConverters$EndpointBuilder.addPathPart(RequestConverters.java:1503)
	at org.elasticsearch.client.RequestConverters.endpoint(RequestConverters.java:1150)
	at org.elasticsearch.client.RequestConverters.getStyleRequest(RequestConverters.java:463)
	at org.elasticsearch.client.RequestConverters.get(RequestConverters.java:459)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1252)
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1231)
	at org.elasticsearch.client.RestHighLevelClient.get(RestHighLevelClient.java:416)
	at EsTest.main(EsTest.java:20)
```
 3.
```
RestHighLevelClient client = new RestHighLevelClient(
                RestClient.builder(new HttpHost("localhost", 9200, "http")));

        /*the expected id is ///error_id*/
        GetRequest request = new GetRequest("index", "type", "///error_id");
        GetResponse rsp = client.get(request, RequestOptions.DEFAULT);
        /*the actual id is /error_id*/
        System.out.println(rsp.getId());
```
4.
```
     RestHighLevelClient client = new RestHighLevelClient(
                RestClient.builder(new HttpHost("localhost", 9200, "http")));

        /*the expected id is ///error_id*/
        GetRequest request = new GetRequest("index", "type", "/-//error_id");
        GetResponse rsp = client.get(request, RequestOptions.DEFAULT);

       you will get a exception in this case:

java.net.URISyntaxException: Illegal character in hostname at index 2: //-//error_id
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.parseHostname(URI.java:3387)
	at java.net.URI$Parser.parseServer(URI.java:3236)
	at java.net.URI$Parser.parseAuthority(URI.java:3155)
	at java.net.URI$Parser.parseHierarchical(URI.java:3097)
	at java.net.URI$Parser.parse(URI.java:3063)
	at java.net.URI.<init>(URI.java:673)
	at org.elasticsearch.client.RequestConverters$EndpointBuilder.encodePart(RequestConverters.java:1530)
```

**Reason:**
In the function encodePart(RequestConverter.java)
```
private static String encodePart(String pathPart) {
            try {
                //encode each part (e.g. index, type and id) separately before merging them into the path
                //we prepend "/" to the path part to make this pate absolute, otherwise there can be issues with
                //paths that start with `-` or contain `:`
---->  bug code:  URI uri = new URI(null, null, null, -1, "/" + pathPart, null, null);
                //manually encode any slash that each part may contain
                return uri.getRawPath().substring(1).replaceAll("/", "%2F");
            } catch (URISyntaxException e) {
                throw new IllegalArgumentException("Path part [" + pathPart + "] couldn't be encoded", e);
            }
        }
```
a URI look likes:[scheme:][//authority][path][?query][#fragment] 
when you set pathPart to something start with '/',for example /abc, then call method "new URI(null, null, null, -1, "//abc", null, null);" .the "//abc" will be parse as "authority"  because "//" stand for authority!,uri.getRawPath() would return null in this situation.

when you set pathPart to something like '/abc/def,then call method  "new URI(null, null, null, -1, "//abc/def", null, null);"，“//abc“ will be parse as “authority” and “/def” will be parse as path, uri.getRawPath() would return "def" 

A solution to this problem is to add “///” when partPart startwith '/'
```
new URI(null, null, null, -1, pathPart.startsWith("/") ? "///"+pathPart : "/" + pathPart, null, null)
```

**if that's ok, i'm gald to provide a PR**

### PR DESCRIPTION
**Pull request by roycarser**
Closes #34433"
set userinfo and host parts of URI to something not null so that the path part will not be parsed as them

### CODE REVIEW

**Comment by hub-cap** [comment]
Hi @roycarser, sorry for taking a while to get back to you. I researched the problem, and whats happening is part of the forward slashes are being interpreted as a blank authority, as per https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/net/URI.java#L3161-L3166 . Changing the `URI` construction to use a `//` authority like below will cause all of your additional tests to pass. Since its been a while I can push this change for you, or Id be happy to have you push it as well. Once you push it, please do a git merge of master so we can ensure all of the tests can be run on our CI infrastructure.

```
URI uri = new URI(null, "//", "/" + pathPart, null, null);
```

**Review by hub-cap — CHANGES_REQUESTED** [review]
doh, I didnt leave the prior comment about the `URI` construction as a 'request changes', sorry about extra notification!

**Comment by roycarser** [comment]
that's fine, I will finish it quickly

**Comment by hub-cap** [comment]
Id like you to leave a comment in there expressing why we need the authority to be non empty. Something like

```
// the authority must be an empty string and not null, else paths that being with slashes could have them misinterpreted as part of the authority.
URI uri = new URI(null, "", "/" + pathPart, null, null);
```

Please note that I tested this with a blank / empty authority and it worked as well, so lets remove the `"//"` in favor for a blank string so its slightly less confusing.

**Comment by roycarser** [comment]
The code has been commited.

**Comment by elasticcla** [comment]
Hi @roycarser, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/elasticsearch/pull/34436.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Review by hub-cap — APPROVED** [review]
awesome. Ill run it thru the paces and then backport it accordingly

**Comment by hub-cap** [comment]
@elasticmachine ok to test

**Comment by hub-cap** [comment]
Thank you for the commit! Im going to backport it accordingly to 7.1.0

**Comment by ern** [comment]
Seeing this issue in 6.8, any chance we can get this backported to 6.8 also?

**Pull request merged**
