### PR TITLE
HLRC _render/template with leading /

### LINKED ISSUE #57575: HLRC dispatches certain HTTP requests without leading '/'
**Elasticsearch version** (`bin/elasticsearch --version`): 7.7.0 (running via Docker on EC2 instance to demo)

**Plugins installed**: None

**JVM version** (`java -version`): 
```
openjdk version "14" 2020-03-17
OpenJDK Runtime Environment AdoptOpenJDK (build 14+36)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14+36, mixed mode, sharing)
```

**OS version** (`uname -a` if on a Unix-like system): `Linux bbac52d60db2 4.14.177-139.254.amzn2.x86_64 #1 SMP Thu May 7 18:48:23 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Description of the problem including expected versus actual behavior**: When Elasticsearch is fronted behind a load balancer (e.g. an AWS Classic ELB or Application Load Balancer), HLRC's `searchTemplate()` method with simulate flag enabled results in an error returned by application load balancer. Expectation is that requests are dispatched successfully.

**Steps to reproduce**: Perform search template request using HLRC with simulate flag enabled.

A quick and dirty demo client is available [here](https://github.com/meserrano/elasticsearch-hlrc-bug-demo/blob/master/src/main/java/com/meserrano/DemoHLRCRootlessPathBug.java) to demonstrate the issue.

1. Front Elasticsearch cluster behind an HTTP application load balancer
2. Execute search template request with simulate flag enabled

**Provide logs (if relevant)**:

```
org.elasticsearch.ElasticsearchStatusException: Unable to parse response body
    at org.elasticsearch.client.RestHighLevelClient.parseResponseException (RestHighLevelClient.java:1868)
    at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest (RestHighLevelClient.java:1622)
    at org.elasticsearch.client.RestHighLevelClient.performRequest (RestHighLevelClient.java:1579)
    at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity (RestHighLevelClient.java:1549)
    at org.elasticsearch.client.RestHighLevelClient.searchTemplate (RestHighLevelClient.java:1251)
    at com.meserrano.ESClientFacade.searchTemplate (ESClientFacade.java:58)
    at com.meserrano.DemoHLRCRootlessPathBug.main (DemoHLRCRootlessPathBug.java:33)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:567)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:282)
    at java.lang.Thread.run (Thread.java:830)
Caused by: org.elasticsearch.client.ResponseException: method [GET], host [http://ElasticsearchDemoHLRCBug-LB-1435840320.us-west-2.elb.amazonaws.com:9200], URI [_render/template], status line [HTTP/1.1 400 Bad Request]
<html>
<head><title>400 Bad Request</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
</body>
</html>

    at org.elasticsearch.client.RestClient.convertResponse (RestClient.java:283)
    at org.elasticsearch.client.RestClient.performRequest (RestClient.java:261)
    at org.elasticsearch.client.RestClient.performRequest (RestClient.java:235)
    at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest (RestHighLevelClient.java:1609)
    at org.elasticsearch.client.RestHighLevelClient.performRequest (RestHighLevelClient.java:1579)
    at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity (RestHighLevelClient.java:1549)
    at org.elasticsearch.client.RestHighLevelClient.searchTemplate (RestHighLevelClient.java:1251)
    at com.meserrano.ESClientFacade.searchTemplate (ESClientFacade.java:58)
    at com.meserrano.DemoHLRCRootlessPathBug.main (DemoHLRCRootlessPathBug.java:33)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:567)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:282)
    at java.lang.Thread.run (Thread.java:830)

```

### PR DESCRIPTION
**Pull request by floriandulzky**
fix #57575

### CODE REVIEW

**Comment by danhermann** [comment]
@floriandulzky, thanks for fixing this bug. If you can sign the CLA above, I can help you get this PR reviewed and merged.

**Comment by floriandulzky** [comment]
> @floriandulzky, thanks for fixing this bug. If you can sign the CLA above, I can help you get this PR reviewed and merged.

I already did it 2 times.

**Comment by gmarouli** [comment]
Hi @floriandulzky , I am sorry to see you are having troubles with the CLA. Would you like to try it one more time? It's been a long while so whatever was causing issue might be fixed already.

Furthermore, the high level rest client has been removed from `8.x` but we could still apply your contribution on the `7.x`. If you are interested let's continue with this PR, if not I will proceed in closing it.

**Comment by gmarouli** [comment]
Since there hasn't been any activity for a month. I will proceed on closing this issue. @floriandulzky thank you for the effort and if you see that you would like to pick it up again ping me. I will be happy to see it through.

**Pull request closed without merging**
