### PR TITLE
Remove the unused executor builder for vector tile plugin

### PR DESCRIPTION
**Pull request by iverase**
It looks like a left over from the original development of this end point and not used anywhere.  Even if it is not an issue for the correct behaviour of Elasticsearch it can be a breaking change. In the remote case the user has tried to configure the threadpool in the Elasticsearch yml file, for example trying to change the size:

```
thread_pool.vectortile.size=8
```

Elasticsearch would not start until the line is removed from the file.

### CODE REVIEW

**Comment by iverase** [comment]
@elasticmachine update branch

**Review by craigtaverner — APPROVED** [review]
LGTM

**Comment by iverase** [comment]
@elasticmachine update branch

**Comment by iverase** [comment]
@elasticmachine run elasticsearch-ci/part-1

**Comment by iverase** [comment]
@elasticmachine update branch

**Pull request merged**
