### PR TITLE
Make Noderesolver robust against null values

### PR DESCRIPTION
**Pull request by hendrikmuhs**
make node resolving more robust by ignoring null values. This is a bug in
the usage of this class, however you don't want NPE's in prod. The root cause
might be a corner case. Because silencing the root cause is bad, the assert 
causes a fail if assertions are enabled	

relates #62847

### CODE REVIEW

**Comment by hendrikmuhs** [comment]
run elasticsearch-ci/bwc
run elasticsearch-ci/default-distro

**Comment by hendrikmuhs** [comment]
@elasticmachine update branch

**Review by DaveCTurner — CHANGES_REQUESTED** [review]
I think the _empty_ case can happen, e.g. `GET _nodes/,/`, but +1 to defensively catching `null` like this.

Would you adjust `DiscoveryNodesTests` to match?

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Pull request merged**
