### PR TITLE
In the field capabilities API, re-add support for `fields` in the request body

### LINKED ISSUE #86875: Support fields under body as well as in url for field_caps API.
### Description

Before ES 7.x it was possible to provide a list of fields by URL or BODY request for field_caps API.
https://www.elastic.co/guide/en/elasticsearch/reference/6.8/search-field-caps.html
`POST _field_caps
{
   "fields" : ["rating"]
}`

Starting from 7.x this feature was removed, and only one possible way it uses URI but in this case, it is possible to have an error 414 (Request-URI Too Long).

I would like to return this feature back.

### PR DESCRIPTION
**Pull request by likzn**
Close: #86875
Main Change: As title

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by likzn** [comment]
Sorry, i had signed CLA. But i dont know why the status is still not signed yet.

**Comment by likzn** [comment]
@jtibshirani  Hi, PTAL if free~

**Review by jtibshirani — COMMENTED** [review]
This looks good overall. Before merging, we should add a couple more tests:
* We should make sure `FieldCapabilitiesRequestTests` covers this case. We can add a method like `testFromXContent` that tries to parse a request body containing `fields`.
* In the REST yaml test `field_caps/10_basic.yml`, we can update one of the tests to use `fields` in the `body` instead of a parameter. This gives extra confidence it works end-to-end.

**Comment by likzn** [comment]
@jtibshirani Thanks for reviewing! I had update something. PTAL

**Comment by jtibshirani** [comment]
@elasticmachine run tests

**Comment by jtibshirani** [comment]
@elasticmachine test this please

**Comment by jtibshirani** [comment]
@elasticmachine test this please

**Comment by jtibshirani** [comment]
@elasticmachine ok to test

**Comment by jtibshirani** [comment]
This is looking good to me. I started a full test run and noticed one failure. Here's the line to reproduce commandline:

```
./gradlew ':qa:mixed-cluster:v7.17.6#mixedClusterTest' -Dtests.class="org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=field_caps/10_basic/Get simple field caps}" -Dtests.seed=21789A66BDE37D85
```

What this test does is call the "Get simple field caps" case in a mixed cluster of ES 8.5 (latest version) and 7.17 nodes. Could you look into the test failure? Let me know if I can help, it may be a little tricky.

**Comment by likzn** [comment]
@jtibshirani Done, i update this case `Get simple field caps`. But i forget to add `version skip`
```
  - skip:
      version: " - 8.4.99"
      reason: re-add support for fields in the request body in 8.5
```

**Review by jtibshirani — APPROVED** [review]

**Comment by jtibshirani** [comment]
Thanks for debugging that. I pushed a change to separate the test into a new case, so that we don't need to skip "Get simple field caps" in mixed cluster tests.

**Pull request merged**
