### PR TITLE
Upgrade to Gradle 6.1

### PR DESCRIPTION
**Pull request by mark-vieira**
Preliminary testing for support with Gradle 6.1. This release also includes a fix for https://github.com/gradle/gradle/issues/11426 so we are removing the workaround put in place for this issue.

In addition to the fix above, Gradle 6.1 introduces and incubating API for the concept of build services, which will allow us to clean up several nasty hacks in our build logic.
https://docs.gradle.org/current/javadoc/org/gradle/api/services/BuildService.html

### CODE REVIEW

**Comment by mark-vieira** [comment]
@elasticmachine test this again

**Comment by mark-vieira** [comment]
@elasticmachine retest this please

**Comment by mark-vieira** [comment]
@elasticmachine update branch

**Comment by mark-vieira** [comment]
@elasticmachine update branch

**Review by rjernst — APPROVED** [review]
LGTM

**Pull request merged**
