### PR TITLE
[DOCS] Add release notes for 7.15.0

### PR DESCRIPTION
**Pull request by joegallo**

### CODE REVIEW

**Comment by joegallo** [comment]
I'm not sure why the build is failing on `invalid reference: breaking-changes-7.15`, it looks to me like that already exists ([link](https://github.com/elastic/elasticsearch/blame/7.15/docs/reference/migration/migrate_7_15.asciidoc#L21)).

**Comment by joegallo** [comment]
Still needs the changes to `docs/reference/release-notes/highlights.asciidoc`.

**Comment by joegallo** [comment]
The [breaking changes for 7.15](https://github.com/elastic/elasticsearch/pulls?q=+is%3Apr+label%3A%3Ebreaking+label%3Av7.15.0+) mostly seem academic -- the `quota-aware-fs` change is sortof an internal only implementation detail, and the `vector field` change is 'just' a change to the usage API (which, again, sortof an internal only implementation detail).

**Comment by joegallo** [comment]
https://elasticsearch_78152.docs-preview.app.elstc.co/diff

**Review by lockewritesdocs — APPROVED** [review]
LGTM 👍 Ship it!

**Pull request merged**
