### PR TITLE
Update reference docs for geocentroid aggregation.

### LINKED ISSUE #24140: [Docs] Define centroid
I suspect that many will not know what a **centroid** is. The docs for the **geo centroid aggregation** should define what this is. 

https://www.elastic.co/guide/en/elasticsearch/reference/5.3/search-aggregations-metrics-geocentroid-aggregation.html

### PR DESCRIPTION
**Pull request by aleph-zero**
This includes a link to the Wikipedia page explaining what a centroid
is.

Closes #24140

### CODE REVIEW

**Review by nik9000 — APPROVED** [review]
LGTM so long as the link renders well.

**Comment by nik9000** [comment]
I just checked locally. The link looks good.

**Comment by karmi** [comment]
Hi @aleph-zero, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/elasticsearch/pull/24141.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by nik9000** [comment]
Thanks @aleph-zero! After some trouble with the CLA checker everything looks good so I'll merge and cherry-pick as appropriate.

**Comment by nik9000** [comment]
All merged! Thanks again @aleph-zero!

**Pull request merged**
