### PR TITLE
Add xpack usage stats for the spatial plugin

### PR DESCRIPTION
**Pull request by talevy**
This commit leverages the analytics plugin's aggregation usage
framework and adopts it to the spatial plugin.

This is just a skeleton, as there are no aggregations to
be tracked just yet, but future ones will be introduced and
their usage should be tracked here.

### CODE REVIEW

**Review by imotov — APPROVED** [review]
LGTM

**Comment by talevy** [comment]
thanks @imotov!

**Comment by talevy** [comment]
@elasticmachine elasticsearch-ci/packaging-sample-windows

**Comment by talevy** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample-windows

**Review by polyfractal — COMMENTED** [review]
LGTM2, thanks for adding this :)

**Review by polyfractal — APPROVED** [review]

**Pull request merged**
