### PR TITLE
Don't allow secure settings in YML config (109115)

### PR DESCRIPTION
**Pull request by alexey-ivanov-es**
Elasticsearch should refuse to start
if a secure setting is defined in elasticsearch.yml, in order to protect users from accidentally putting their secrets in a place where they are unexpectedly visible

Fixes #109115

### CODE REVIEW

**Review by prdoyle — APPROVED** [review]
Seems straightforward

**Review by DaveCTurner — DISMISSED** [review]
Hang on, I think this is a breaking change, we need to clear it with the breaking changes committee first and document it as breaking. I suspect we should be emitting warnings in 8.x as well to help folks avoid the problem before it actually takes effect.

**Comment by alexey-ivanov-es** [comment]
@DaveCTurner I discussed this with @rjernst and he said: "I confirmed that we are ok to proceed with the above change. it's an edge case which is in a gray area we shouldn't need an explicit breaking change issue for."

**Comment by DaveCTurner** [comment]
Ok carry on then.

**Pull request merged**
