### PR TITLE
Bump source compatibility version to Java 17

### PR DESCRIPTION
**Pull request by mark-vieira**
Use the Java 17 JDK for the build in CI. This doesn't yet change the minimum compiler version so 17 is not yet _required_.

### CODE REVIEW

**Comment by mark-vieira** [comment]
@elasticmachine update branch

**Review by pugnascotia — COMMENTED** [review]
What happened to all the `qa/wildfly` files?

**Comment by mark-vieira** [comment]
There's no Java 17 Docker image for Wildfly and while investigating I realized that QA module is simply testing that that HLRC can run inside a Wildfly container. But since we've removed the HLRC in 8.0 we don't need that testing anymore at all.

**Review by pugnascotia — APPROVED** [review]
Ah nice, LGTM then 👍

**Comment by mark-vieira** [comment]
@elasticmachine update branch

**Comment by mark-vieira** [comment]
@elasticmachine run elasticsearch-ci/part-2

**Pull request merged**
