### PR TITLE
Make multi search tasks cancellable

### PR DESCRIPTION
**Pull request by javanna**
Today multi search tasks, created through MultiSearchRequest#createTask
end up being the default task instance which is not cancellable. With
this change we make them a search task, which is cancellable, and also
cancels all the sub-tasks when cancelled.

### CODE REVIEW

**Review by imotov — COMMENTED** [review]
I think it should work, but I would feel better if we had an integration level test that really checks that we connected all dots here. You can probably modify SearchCancellationIT to randomly wrap it into MultiSearch from time to time.

**Comment by javanna** [comment]
Turns out that an integration test is needed, and it proves that cancelling msearch requests does not really cancel all the corresponding searches as there are three levels of tasks: msearch -> search -> shard level search . I will work on making cancelling a task work for this scenario, but it will require a separate change.

**Comment by javanna** [comment]
This PR can be resumed once #50990 is fixed.

**Comment by javanna** [comment]
This PR can be resumed once #50990 is fixed.

**Comment by javanna** [comment]
This PR can be resumed once #50990 is fixed.

**Comment by javanna** [comment]
This PR can be resumed once #50990 is fixed.

**Comment by javanna** [comment]
This PR can be resumed once #50990 is fixed.

**Comment by javanna** [comment]
I removed the stalled label, I will pick this back up shortly given that the tasks framework now supports hierarchical cancellation of tasks.

**Comment by javanna** [comment]
This was implemented in #61337

**Pull request closed without merging**
