### PR TITLE
add data tier configuration information for Cloud

### PR DESCRIPTION
**Pull request by DanRoscigno**
Adds the Cloud method for adding warm, cold, frozen tiers to the data tiers documentation.

### CODE REVIEW

**Comment by jrodewig** [comment]
Thanks for getting the ball rolling here @DanRoscigno. While your content is great, its location felt kinda awkward.

I pushed https://github.com/elastic/elasticsearch/pull/84518/commits/8ae42c2fd53a4cc4d3778e3815baeecf5f77f9a4 to:

- Move the content to its own section with separate headings
- Add some additional details to the procedural steps

Since this is @debadair's sandbox, I'd like to get approval before merging this in. Thanks!

**Comment by DanRoscigno** [comment]
Thanks for adding in the disable a data tier page, I was not aware of that one!

**Comment by DanRoscigno** [comment]
I worked through the ILM tutorial and updated one of the Cloud console images (it still had sliders)

**Review by debadair — APPROVED** [review]
LGTM. Thanks for adding this!

**Comment by DanRoscigno** [comment]
@elasticmachine retest this please

**Comment by jrodewig** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.1|[](https://github.com/elastic/elasticsearch/pull/84806)|
|✅|8.0|[](https://github.com/elastic/elasticsearch/pull/84807)|


### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
