### PR TITLE
Upgrade to lucene-5.4-snapshot-1710880.

### PR DESCRIPTION
**Pull request by jpountz**

### CODE REVIEW

**Comment by mikemccand** [comment]
LGTM

**Comment by s1monw** [comment]
cool push it so I can clean up IndexSearcherWrapper

**Comment by jpountz** [comment]
I rebased and updated the PR to adapt to #14311. @rmuir Can you look?

**Comment by rmuir** [comment]
+1 I just went to do this (sorry, i intended to before falling asleep) and saw you already did it. looks great.

**Pull request merged**
