### PR TITLE
Regression: flattened (label) fields when downsampling

### PR DESCRIPTION
**Pull request by mjmbischoff**
Reproduce in dev-tools:
```
DELETE dummy_downsample
DELETE my-downsampled-time-series-index

PUT dummy_downsample
{
  "mappings": {
    "properties": {
      "@timestamp": {
        "type": "date"
      },
      "flattened": {
        "type": "flattened"
      },
      "keyword": {
        "type": "keyword",
        "time_series_dimension": true
      }
    }
  },
  "settings": {
    "index.mode": "time_series",
    "routing_path": [
      "keyword"
    ],
    "index.time_series.start_time": "2024-09-10T07:00:00.000Z",
    "index.time_series.end_time": "2024-09-10T08:00:00.000Z"
  }
}

POST dummy_downsample/_doc/
{
  "@timestamp": "2024-09-10T07:50:00.000Z",
  "flattened": {
    "key": "value"
  },
  "keyword": "keyword1"
}

POST dummy_downsample/_close
PUT dummy_downsample/_settings
{
  "index.blocks.write": "true"
}
POST dummy_downsample/_open

POST /dummy_downsample/_downsample/my-downsampled-time-series-index
{
  "fixed_interval": "1m"
}
```

last call results in a 500 response code under 8.15. Looking into things, it seems that instead of an object, the value of field of the flattened object is being presented for insertion which fails because the flattened field expects an object.

This however succeeds/silently fails in 8.11

### CODE REVIEW

**Comment by mjmbischoff** [comment]
on a related note, it seems a nullpointer exception is thrown if one runs a downsample on a closed index.

**Comment by mjmbischoff** [comment]
https://github.com/elastic/elasticsearch/pull/110066 seems related but the changes look ok.

**Comment by mjmbischoff** [comment]
Taking a closer look it seems that under 8.11 it might be silently failing as no docs are in the downsampled index.

**Comment by martijnvg** [comment]
@mjmbischoff We took a look at the problem that this PR tries to fix and opened #116319. I think instead of ignoring flattened fields, I think we can include it. I think we need a dedicated field producer for it.

**Comment by mjmbischoff** [comment]
@martijnvg Definitely would prefer regenerating the source instead, I had trouble 'grabbing' the data needed, not sure the abstractions are quite right - which is why I fell back to dropping it for now

**Comment by mjmbischoff** [comment]
superseded by https://github.com/elastic/elasticsearch/pull/118816

**Pull request closed without merging**
