### PR TITLE
Minor hygiene, Removed Redundant inheritance

### PR DESCRIPTION
**Pull request by souravmitra**

### CODE REVIEW

**Comment by clintongormley** [comment]
thanks for the PR @souravmitra - please could I ask you to sign the CLA so that we can merge it in?
http://www.elasticsearch.org/contributor-agreement/

**Comment by souravmitra** [comment]
@clintongormley - I already signed the CLA before the PR. Do i need to do it again?

**Comment by clintongormley** [comment]
ah - your github email address is different, hence the problem. i've found your signature. thanks!

**Comment by jpountz** [comment]
Merged, thanks!

**Pull request closed without merging**
