### PR TITLE
[7.x][REST Compatible API] Route refactoring

### PR DESCRIPTION
**Pull request by joegallo**
Backport of #69573

Mostly a straightforward backport, but there's no actual Rest Compatible API mechanism on this branch, so not all the work from #69573 was relevant in terms of a backport. Note especially that [`RestApiVersion`](https://github.com/elastic/elasticsearch/pull/70109/files#diff-b6823833e3de861b77d89774433cbbcd4011bc6c3379c2cbd55acabc7ac87d1b) is backported, but just serves as a trivial marker interface. In particular, notice that it isn't used at all from [`MethodHandlers`](https://github.com/elastic/elasticsearch/pull/70109/files#diff-3e936de706a937952383b22e2a9351fe791beeb829265d5b67f2c7b1cc649765).

Also, it should be no surprise that the diff here is bigger than on the original PR -- there were more `DeprecatedRoute`s and `ReplacedRoute`s on `7.x` than there are on `master`.

### CODE REVIEW

**Comment by joegallo** [comment]
@elasticmachine update branch

**Review by pgomulka — APPROVED** [review]
LGTM,
just a side note: it would be much easier to follow up with a separate PR that only performs the formatting and style (singletonList or unmodifiableList) in files that would be untouched in this PR without formatting changes. 
I feel that for smaller PRs it is totally fine to include small refactorings, but this one ended up very big and it would be easier to work with if it touched only files affected by RestApiVersion.V7 and routes refactoring change.

**Review by jakelandis — APPROVED** [review]
LGTM

**Comment by jakelandis** [comment]
@elasticmachine update branch

**Pull request merged**
