### PR TITLE
[DOCS] Add Docker port warning from #48142

### PR DESCRIPTION
**Pull request by Kovah**
@jrodewig @pugnascotia

This is the new pull request pushing changes from the original pull request #48142 to master. Please see the original pull request for more details.

PS: CLA is already signed.

### CODE REVIEW

**Comment by pugnascotia** [comment]
Thanks for redoing this on `master`. What did you think about my suggested wording?

```
Please note that this configuration exposes port 9200 on all network
interfaces, and given how Docker manipulates `iptables` on Linux, this
means that your {es} cluster is publically accessible, potentially ignoring
any firewall settings.  If you don't want to expose port 9200 and instead
use a reverse proxy, replace `9200:9200` with `127.0.0.1:9200:9200` in the
docker-compose.yml file. {es} will then only be accessible from the host
machine itself.
```

At a minimum, the text should use "{es}" instead of "Elasticsearch", to match the rest of the docs.

**Comment by pugnascotia** [comment]
@elasticmachine test this please

**Review by pugnascotia — APPROVED** [review]

**Review by jrodewig — APPROVED** [review]
LGTM. I'll merge these changes. Thanks @Kovah.

**Comment by Kovah** [comment]
Great, thank you all for the support with this!

**Pull request merged**
