### PR TITLE
Fix compilation error in UpdateSettingsIT

### PR DESCRIPTION
**Pull request by davidkyle**
Fix compilation after backport of #31286

### CODE REVIEW

**Review by ywelsch — APPROVED** [review]
LGTM

**Comment by jasontedor** [comment]
I am sorry for this; I am confused though since I did a 6.x build locally so now I'm looking into this to see why I didn't see the issue.

**Comment by nik9000** [comment]
> I am sorry for this; I am confused though since I did a 6.x build locally so now I'm looking into this to see why I didn't see the issue.

Did you do a 6.x build locally, see that it passed, then `git pull elastic 6.x --rebase` then push? I tend to do that without looking at what I pulled and I really shouldn't. Because of things like this.

**Comment by nik9000** [comment]
> Did you do a 6.x build locally, see that it passed, then git pull elastic 6.x --rebase then push? I tend to do that without looking at what I pulled and I really shouldn't. Because of things like this.

Actually, that doesn't make sense in this case.

**Review by nik9000 — APPROVED** [review]

**Comment by davidkyle** [comment]
The PR build failed on a BWC test. 

```
Execution failed for task ':distribution:bwc:staged-minor-snapshot:buildBwcVersion'.
```

I'm merging anyway as the test passes locally and delaying only causes more build failures.

**Comment by jasontedor** [comment]
I am really confused how this happened and again I am really sorry. I ran this earlier this morning before pushing:

```
[jason@totoro ~]$ cde6
[jason@totoro elasticsearch-6.x]$ ./gradlew :server:test -Dtests.jvms=10

To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/4.7/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing

> Task :buildSrc:compileGroovy
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/home/jason/.gradle/wrapper/dists/gradle-4.7-all/4cret0dgl5o3b21weaoncl7ys/gradle-4.7/lib/groovy-all-2.4.12.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

> Task :buildSrc:test
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/home/jason/.gradle/wrapper/dists/gradle-4.7-all/4cret0dgl5o3b21weaoncl7ys/gradle-4.7/lib/groovy-all-2.4.12.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

> Configure project :benchmarks
=======================================
Elasticsearch Build Hamster says Hello!
=======================================
  Gradle Version        : 4.7
  OS Info               : Linux 4.16.8-300.fc28.x86_64 (amd64)
  JDK Version           : Oracle Corporation 10.0.1 [OpenJDK 64-Bit Server VM 10.0.1+10]
  JAVA_HOME             : /opt/java/jdk-10.0.1
  Random Testing Seed   : 7148D52068F0EC06

> Task :libs:core:jar
Building without git revision id.

> Task :libs:cli:jar
Building without git revision id.

> Task :libs:plugin-classloader:jar
Building without git revision id.

> Task :libs:secure-sm:jar
Building without git revision id.

> Task :libs:x-content:compileJava
Note: /home/jason/src/elastic/elasticsearch-6.x/libs/x-content/src/main/java/org/elasticsearch/common/xcontent/json/JsonXContentGenerator.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :libs:x-content:jar
Building without git revision id.

> Task :server:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :client:rest:jar
Building without git revision id.

> Task :server:jar
Building without git revision id.

> Task :test:framework:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :test:framework:jar
Building without git revision id.

> Task :server:compileTestJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :server:test
==> Test Info: seed=889AF62AA3FC6929; jvms=10; suites=1082

HEARTBEAT J6 PID(5176@totoro.home.tedor.me): 2018-06-13T10:22:24, stalled for 10.1s at: RefreshListenersTests.testConcurrentRefresh
HEARTBEAT J8 PID(5175@totoro.home.tedor.me): 2018-06-13T10:22:28, stalled for 11.0s at: IntegerRandomBinaryDocValuesRangeQueryTests.testRandomBig
HEARTBEAT J9 PID(5178@totoro.home.tedor.me): 2018-06-13T10:22:30, stalled for 11.2s at: LongRandomBinaryDocValuesRangeQueryTests.testRandomBig
HEARTBEAT J3 PID(5174@totoro.home.tedor.me): 2018-06-13T10:22:52, stalled for 10.2s at: UUIDTests.testCompression
[ant:junit4] JVM J5: stderr was not empty, see: /home/jason/src/elastic/elasticsearch-6.x/server/build/testrun/test/temp/junit4-J5-20180613_102144_3115720320356623204720.syserr
[ant:junit4] JVM J8: stderr was not empty, see: /home/jason/src/elastic/elasticsearch-6.x/server/build/testrun/test/temp/junit4-J8-20180613_102144_3116243785585159539697.syserr
[ant:junit4] JVM J9: stderr was not empty, see: /home/jason/src/elastic/elasticsearch-6.x/server/build/testrun/test/temp/junit4-J9-20180613_102144_3116152583805943632192.syserr
[ant:junit4] JVM J4: stderr was not empty, see: /home/jason/src/elastic/elasticsearch-6.x/server/build/testrun/test/temp/junit4-J4-20180613_102144_31115827232888390586456.syserr
[ant:junit4] JVM J3: stderr was not empty, see: /home/jason/src/elastic/elasticsearch-6.x/server/build/testrun/test/temp/junit4-J3-20180613_102144_31114303748139346165823.syserr
[ant:junit4] JVM J0: stderr was not empty, see: /home/jason/src/elastic/elasticsearch-6.x/server/build/testrun/test/temp/junit4-J0-20180613_102144_31110473365995124837755.syserr
[ant:junit4] JVM J2: stderr was not empty, see: /home/jason/src/elastic/elasticsearch-6.x/server/build/testrun/test/temp/junit4-J2-20180613_102144_31113600026226998572522.syserr
[ant:junit4] JVM J7: stderr was not empty, see: /home/jason/src/elastic/elasticsearch-6.x/server/build/testrun/test/temp/junit4-J7-20180613_102144_31115952941359037374798.syserr
[ant:junit4] JVM J1: stderr was not empty, see: /home/jason/src/elastic/elasticsearch-6.x/server/build/testrun/test/temp/junit4-J1-20180613_102144_31117163802475345932981.syserr
[ant:junit4] JVM J6: stderr was not empty, see: /home/jason/src/elastic/elasticsearch-6.x/server/build/testrun/test/temp/junit4-J6-20180613_102144_31110198832496197982827.syserr

> Task :server:test
Slow Tests Summary:
 21.76s | org.elasticsearch.index.engine.InternalEngineTests
 21.19s | org.elasticsearch.index.shard.IndexShardTests
 20.02s | org.elasticsearch.index.shard.RefreshListenersTests
 16.34s | org.elasticsearch.action.admin.cluster.node.tasks.TransportTasksActionTests
 14.71s | org.apache.lucene.queries.IntegerRandomBinaryDocValuesRangeQueryTests

==> Test Summary: 1082 suites (1 ignored), 7052 tests, 41 ignored (41 assumptions)

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.7/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 2m 22s
25 actionable tasks: 25 executed
[jason@totoro elasticsearch-6.x]$ ./gradlew :server:integTest -Dtests.jvms=10
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/4.7/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing

> Configure project :benchmarks
=======================================
Elasticsearch Build Hamster says Hello!
=======================================
  Gradle Version        : 4.7
  OS Info               : Linux 4.16.8-300.fc28.x86_64 (amd64)
  JDK Version           : Oracle Corporation 10.0.1 [OpenJDK 64-Bit Server VM 10.0.1+10]
  JAVA_HOME             : /opt/java/jdk-10.0.1
  Random Testing Seed   : AE34FB6E5177CBB3

> Task :server:integTest
==> Test Info: seed=2621D9AD9A082E30; jvms=10; suites=299

HEARTBEAT J6 PID(15615@totoro.home.tedor.me): 2018-06-13T10:23:37, stalled for 10.2s at: ClusterStateDiffIT.testClusterStateDiffSerialization
HEARTBEAT J9 PID(15610@totoro.home.tedor.me): 2018-06-13T10:23:39, stalled for 11.5s at: IndexLifecycleActionIT.testIndexLifecycleActionsWith11Shards1Backup
HEARTBEAT J6 PID(15615@totoro.home.tedor.me): 2018-06-13T10:23:47, stalled for 20.2s at: ClusterStateDiffIT.testClusterStateDiffSerialization
HEARTBEAT J9 PID(15610@totoro.home.tedor.me): 2018-06-13T10:24:05, stalled for 10.6s at: IndicesDocumentationIT.testPutMappingDocumentation
HEARTBEAT J8 PID(15612@totoro.home.tedor.me): 2018-06-13T10:24:09, stalled for 10.8s at: FullRollingRestartIT.testFullRollingRestart
HEARTBEAT J7 PID(15613@totoro.home.tedor.me): 2018-06-13T10:24:11, stalled for 10.8s at: IndicesStoreIntegrationIT.testShardActiveElseWhere
HEARTBEAT J7 PID(15613@totoro.home.tedor.me): 2018-06-13T10:24:21, stalled for 20.8s at: IndicesStoreIntegrationIT.testShardActiveElseWhere
HEARTBEAT J6 PID(15615@totoro.home.tedor.me): 2018-06-13T10:24:25, stalled for 12.0s at: IndexStatsIT.testConcurrentIndexingAndStatsRequests
HEARTBEAT J7 PID(15613@totoro.home.tedor.me): 2018-06-13T10:24:31, stalled for 30.8s at: IndicesStoreIntegrationIT.testShardActiveElseWhere
HEARTBEAT J1 PID(15652@totoro.home.tedor.me): 2018-06-13T10:24:33, stalled for 10.5s at: GlobalCheckpointSyncIT.testBackgroundGlobalCheckpointSync
HEARTBEAT J8 PID(15612@totoro.home.tedor.me): 2018-06-13T10:24:33, stalled for 10.0s at: BulkWithUpdatesIT.testBulkUpdateLargerVolume
HEARTBEAT J9 PID(15610@totoro.home.tedor.me): 2018-06-13T10:24:47, stalled for 11.5s at: RecoveryWhileUnderLoadIT.testRecoverWhileUnderLoadWithReducedAllowedNodes
HEARTBEAT J0 PID(15648@totoro.home.tedor.me): 2018-06-13T10:24:49, stalled for 11.2s at: ReverseNestedIT (suite)
HEARTBEAT J9 PID(15610@totoro.home.tedor.me): 2018-06-13T10:24:57, stalled for 21.5s at: RecoveryWhileUnderLoadIT.testRecoverWhileUnderLoadWithReducedAllowedNodes
HEARTBEAT J6 PID(15615@totoro.home.tedor.me): 2018-06-13T10:25:05, stalled for 10.6s at: BucketSelectorIT (suite)
HEARTBEAT J8 PID(15612@totoro.home.tedor.me): 2018-06-13T10:25:15, stalled for 10.2s at: IndexTemplateBlocksIT.testIndexTemplatesWithBlocks
HEARTBEAT J6 PID(15615@totoro.home.tedor.me): 2018-06-13T10:25:23, stalled for 11.8s at: FsBlobStoreRepositoryIT.testSnapshotAndRestore
HEARTBEAT J5 PID(15611@totoro.home.tedor.me): 2018-06-13T10:25:41, stalled for 11.5s at: DedicatedClusterSnapshotRestoreIT.testMasterAndDataShutdownDuringSnapshot
HEARTBEAT J5 PID(15611@totoro.home.tedor.me): 2018-06-13T10:25:51, stalled for 21.5s at: DedicatedClusterSnapshotRestoreIT.testMasterAndDataShutdownDuringSnapshot
HEARTBEAT J5 PID(15611@totoro.home.tedor.me): 2018-06-13T10:26:01, stalled for 31.5s at: DedicatedClusterSnapshotRestoreIT.testMasterAndDataShutdownDuringSnapshot
HEARTBEAT J8 PID(15612@totoro.home.tedor.me): 2018-06-13T10:26:15, stalled for 11.0s at: RandomScoreFunctionIT.testSeeds
HEARTBEAT J2 PID(15714@totoro.home.tedor.me): 2018-06-13T10:26:15, stalled for 10.8s at: PrimaryAllocationIT.testDoNotRemoveAllocationIdOnNodeLeave
HEARTBEAT J0 PID(15648@totoro.home.tedor.me): 2018-06-13T10:26:27, stalled for 10.5s at: ContextCompletionSuggestSearchIT.testSingleContextBoosting
HEARTBEAT J1 PID(15652@totoro.home.tedor.me): 2018-06-13T10:26:29, stalled for 10.1s at: AckClusterUpdateSettingsIT.testOpenIndexNoAcknowledgement
HEARTBEAT J2 PID(15714@totoro.home.tedor.me): 2018-06-13T10:26:31, stalled for 11.1s at: PrimaryAllocationIT.testDoNotAllowStaleReplicasToBePromotedToPrimary
HEARTBEAT J4 PID(15614@totoro.home.tedor.me): 2018-06-13T10:26:33, stalled for 10.0s at: ClusterDisruptionIT.testSendingShardFailure
HEARTBEAT J7 PID(15613@totoro.home.tedor.me): 2018-06-13T10:26:37, stalled for 10.8s at: SingleNodeDiscoveryIT.testDoesNotRespondToZenPings
HEARTBEAT J5 PID(15611@totoro.home.tedor.me): 2018-06-13T10:26:37, stalled for 11.7s at: SnapshotDisruptionIT.testDisruptionOnSnapshotInitialization
HEARTBEAT J1 PID(15652@totoro.home.tedor.me): 2018-06-13T10:26:43, stalled for 11.8s at: AckClusterUpdateSettingsIT.testAckingFailsIfNotPublishedToAllNodes
HEARTBEAT J9 PID(15610@totoro.home.tedor.me): 2018-06-13T10:26:47, stalled for 11.9s at: MasterDisruptionIT.testMasterNodeGCs
HEARTBEAT J5 PID(15611@totoro.home.tedor.me): 2018-06-13T10:26:47, stalled for 21.7s at: SnapshotDisruptionIT.testDisruptionOnSnapshotInitialization
HEARTBEAT J8 PID(15612@totoro.home.tedor.me): 2018-06-13T10:26:49, stalled for 10.1s at: DiscoveryDisruptionIT.testElectMasterWithLatestVersion
HEARTBEAT J2 PID(15714@totoro.home.tedor.me): 2018-06-13T10:26:55, stalled for 11.1s at: PrimaryAllocationIT.testRemoveAllocationIdOnWriteAfterNodeLeave
HEARTBEAT J5 PID(15611@totoro.home.tedor.me): 2018-06-13T10:26:57, stalled for 31.7s at: SnapshotDisruptionIT.testDisruptionOnSnapshotInitialization
HEARTBEAT J6 PID(15615@totoro.home.tedor.me): 2018-06-13T10:27:01, stalled for 10.9s at: UpdateMappingIntegrationIT.testDynamicUpdates
HEARTBEAT J9 PID(15610@totoro.home.tedor.me): 2018-06-13T10:27:01, stalled for 10.6s at: MasterDisruptionIT.testStaleMasterNotHijackingMajority
[ant:junit4] JVM J5: stderr was not empty, see: /home/jason/src/elastic/elasticsearch-6.x/server/build/testrun/integTest/temp/junit4-J5-20180613_102323_8278991628234885885391.syserr
HEARTBEAT J9 PID(15610@totoro.home.tedor.me): 2018-06-13T10:27:25, stalled for 10.1s at: MasterDisruptionIT.testIsolateMasterAndVerifyClusterStateConsensus
HEARTBEAT J9 PID(15610@totoro.home.tedor.me): 2018-06-13T10:27:43, stalled for 10.5s at: MasterDisruptionIT.testVerifyApiBlocksDuringPartition

> Task :server:integTest
Slow Tests Summary:
 94.47s | org.elasticsearch.cluster.routing.PrimaryAllocationIT
 81.66s | org.elasticsearch.discovery.MasterDisruptionIT
 62.96s | org.elasticsearch.snapshots.SharedClusterSnapshotRestoreIT
 60.64s | org.elasticsearch.snapshots.DedicatedClusterSnapshotRestoreIT
 57.61s | org.elasticsearch.discovery.DiscoveryDisruptionIT

==> Test Summary: 299 suites, 2222 tests, 3 ignored (3 assumptions)

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.7/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 4m 40s
25 actionable tasks: 1 executed, 24 up-to-date
```

Yet if I run this now from the same directory I get:

```
[jason@totoro elasticsearch-6.x]$ ./gradlew :server:compileTestJava
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/4.7/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing

> Task :buildSrc:compileGroovy
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/home/jason/.gradle/wrapper/dists/gradle-4.7-all/4cret0dgl5o3b21weaoncl7ys/gradle-4.7/lib/groovy-all-2.4.12.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

> Task :buildSrc:test
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/home/jason/.gradle/wrapper/dists/gradle-4.7-all/4cret0dgl5o3b21weaoncl7ys/gradle-4.7/lib/groovy-all-2.4.12.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

> Configure project :benchmarks
=======================================
Elasticsearch Build Hamster says Hello!
=======================================
  Gradle Version        : 4.7
  OS Info               : Linux 4.16.8-300.fc28.x86_64 (amd64)
  JDK Version           : Oracle Corporation 10.0.1 [OpenJDK 64-Bit Server VM 10.0.1+10]
  JAVA_HOME             : /opt/java/jdk-10.0.1
  Random Testing Seed   : C606E2AF6816353C

> Task :libs:core:jar
Building without git revision id.

> Task :libs:cli:jar
Building without git revision id.

> Task :libs:plugin-classloader:jar
Building without git revision id.

> Task :libs:secure-sm:jar
Building without git revision id.

> Task :libs:x-content:jar
Building without git revision id.

> Task :server:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :client:rest:jar
Building without git revision id.

> Task :server:jar
Building without git revision id.

> Task :test:framework:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :test:framework:jar
Building without git revision id.

> Task :server:compileTestJava
/home/jason/src/elastic/elasticsearch-6.x/server/src/test/java/org/elasticsearch/indices/settings/UpdateSettingsIT.java:165: error: wrong number of type arguments; required 3
                extends Action<UpdateInternalIndexAction.Request, UpdateInternalIndexAction.Response> {
                              ^
/home/jason/src/elastic/elasticsearch-6.x/server/src/test/java/org/elasticsearch/indices/settings/UpdateSettingsIT.java:213: error: method does not override or implement a method from a supertype
            @Override
            ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors

> Task :server:compileTestJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':server:compileTestJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.7/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 8s
23 actionable tasks: 14 executed, 9 up-to-date
[jason@totoro elasticsearch-6.x]$ 
```

so clearly something awful happened and I don't know what it is.

**Pull request merged**
