### PR TITLE
Minimize cache file locking during prewarming

### PR DESCRIPTION
**Pull request by tlrx**
During prewarming of a Lucene file a `CacheFile` is acquired and then locked for the duration of the prewarming, ie locked until all the part of the file has been downloaded and written to cache on disk. The locking (executed with `CacheFile#fileLock()`) is here to prevent the cache file to be evicted while it is prewarming. 

But holding the lock may take a while for large files, specially since restoring snapshot files now respects the ` indices.recovery.max_bytes_per_sec` setting of ` 40mb` (#58658), and this can have bad consequences like preventing the ` CacheFile` to be evicted, opened or closed. In manual tests this bug slow downs various requests like mounting a new searchable snapshot index or deleting an existing one that is still prewarming.

This pull request reduces the time the lock is held during prewarming so that the read lock is only required when actively writing to the `CacheFile`.

### CODE REVIEW

**Comment by tlrx** [comment]
@elasticmachine update branch

**Comment by tlrx** [comment]
@elasticmachine update branch

**Review by ywelsch — APPROVED** [review]
LGTM

**Comment by tlrx** [comment]
Thanks Yannick

**Pull request merged**
