### PR TITLE
[DOCS] Fixes broken links in rest API spec

### PR DESCRIPTION
**Pull request by szabosteve**
## Overview

This PR fixes two broken links in `indices.add_block.json` and `indices.resolve_index.json`.

### CODE REVIEW

**Review by delvedor — APPROVED** [review]
Thanks!

**Comment by szabosteve** [comment]
@elasticmachine test this please

**Comment by jrodewig** [comment]
@elasticmachine update branch

**Comment by szabosteve** [comment]
**Backport commits:**
7.x: 7c995aa
7.9: d256d13

**Pull request merged**
