### PR TITLE
Add isRunning method to RestClient 

### PR DESCRIPTION
**Pull request by weizijun**
As RestClient maybe broken, mentioned in https://github.com/elastic/elasticsearch/issues/42133.

RestClient Add a isRunning method, so users can check if RestClient is ok. if RestClient is not running, user can reset a new RestClient.

### CODE REVIEW

**Comment by weizijun** [comment]
@jbaiera hi，jbaiera, can you help to review this PR.

**Comment by weizijun** [comment]
@jasontedor  hi，jasontedor, can you help to review this PR.

**Comment by jasontedor** [comment]
@jakelandis Can you help find someone to review this PR?

**Comment by jbaiera** [comment]
@elasticmachine ok to test

**Comment by weizijun** [comment]
@elasticmachine update branch

**Comment by weizijun** [comment]
@elasticmachine update branch

**Comment by weizijun** [comment]
@elasticmachine update branch

**Review by jbaiera — APPROVED** [review]
This LGTM

**Pull request merged**
