### PR TITLE
Remove data_stream from monitoring-mb templates

### LINKED ISSUE #29657: [metricbeat] beats xpack module creates a single datastream per service monitored
When configured with a beat module and `xpack.enabled: true` (https://github.com/elastic/beats/blob/master/metricbeat/modules.d/beat-xpack.yml.disabled), recent builds of metricbeat from the 8.0 branch create daily datastreams, eg. `.monitoring-beats-8-mb-2021.12.29` and then `.monitoring-beats-8-mb-2021.12.30`.

Can metricbeat be updated to only write to a single datastream per thing monitored, ie., the naming would change to `.monitoring-beats-8-mb`?

### PR DESCRIPTION
**Pull request by matschaffer**
This results in plain dated indices being created for the `.monitoring-*-8-mb` pattern and avoids creating a new data stream for each day.

Screen Shot 2022-01-06 at 11 24 35

Fixes: https://github.com/elastic/beats/issues/29657 (or at least eliminates the need for it)

### CODE REVIEW

**Comment by dakrone** [comment]
I would really prefer that we fix this on the metricbeat side and continue to use data streams if possible. Is there a reason we want to revert back to date-based indices outside of resolving the data stream naming issue?

**Comment by matschaffer** [comment]
I consider this a "plan B" - I understand @jasonrhodes and @klacabane are following up on https://github.com/elastic/beats/issues/29657 to try to get beats expertise on what it'd take to write to a non-dated stream.

**Comment by sayden** [comment]
We must keep using data streams and change whatever is necessary in SM UI to avoid accumulating more tech debt. Let's please talk about what Kibana's SM UI from Metricbeat side in a Beats issue and work from there.

**Comment by matschaffer** [comment]
No kibana should work fine either way. This is a plan B since it wasn't clear if we could definitely alter beats to avoid the dated data streams.

Closing in favor of https://github.com/elastic/beats/pull/29775

**Pull request closed without merging**
