### PR TITLE
Fix unnecessary mustache template evaluation

### LINKED ISSUE #110191: Unnecessarily slow performance from Ingest date processors when a templated timezone or locale are used
Mustache template application can be (relatively) expensive, especially in the case of ingest processor execution where we necessarily have to perform it on every document.

There's an edge case of the `date` ingest processor where template application is applied in a loop. Consider the following:

```
PUT _ingest/pipeline/date
{
  "processors": [
    {
      "date": {
        "timezone": "{{{ timezone }}}",
        "field": "date",
        "formats": [
          [...]
        ]
      }
    }
  ]
}

POST _ingest/pipeline/date/_simulate
{
  "docs": [
    {
      "_index": "index",
      "_id": "id",
      "_source": {
        "date": "funtimesahead",
        "timezone": "UTC"
      }
    }
  ]
}
```

In this case, for each document that's processed by the pipeline, we'd attempt to parse `"funtimesahead"` with each format in order until the value is successfully parsed -- that's fine (so to speak). What's not fine is that we happen to run mustache template evaluation inside that loop! The timezone is always going to be `"UTC"` and we can apply the template just once before the loop in order to determine that.

The same issue applies for locale.

-----

Separately (and I doubt there's much we can do about this without eating a breaking change, though perhaps we should document it) -- using a templated value for timezone and locale is not cooperative when the values might not be present. (edit: TODO I need to write this up better, this might warrant being its own separate bug, but I needed somewhere to put the note for now so it's not lost to time.)

### PR DESCRIPTION
**Pull request by kanoshiou**
This PR addresses the performance issue in the date ingest processor where Mustache template evaluation is unnecessarily applied inside a loop. The timezone and locale templates are now evaluated once before the loop, improving efficiency.

Closes #110191

### CODE REVIEW

**Comment by joegallo** [comment]
@kanoshiou this is a great contribution -- thanks for coming to us with a PR. I added some commits as a form of review, basically I took your change a little further.

@parkertimmins I think you should take a look at this one and review it, but I also think the most ideal version of this PR should include a test that proves that even if we have N parsers for a given document, we only invoke mustache template application at most twice (once for the timezone and once for the locale).

FWIW I'm seeing a ~20% speedup in `date` processor invocations locally, so this is a great improvement.

**Comment by kanoshiou** [comment]
@joegallo Thank you for your kind words and for taking the time to review my PR. I appreciate the additional commits and the improvements you’ve made. I’ve learned a lot from your code, and I realize there is still much more for me to learn.

Lastly, I added a test case to ensure mustache template is invoked at most twice with multiple parsers.

**Comment by joegallo** [comment]
938f326b1370e20ed673b5efbea260074e3da12c makes this a better test, IMHO -- as originally written the test passes on `main` without any change to the non-test code, so it doesn't actually set up the scenario where template execution occurs in a loop. I've moved the matching format to the end of the list of formats so that the test will fail on `main` but does continue to pass on this branch.

**Comment by joegallo** [comment]
@elasticmachine test this please

**Review by parkertimmins — APPROVED** [review]
LGTM

**Pull request merged**
