### PR TITLE
Harden index mapping parameter check in enrich runner

### PR DESCRIPTION
**Pull request by dnhatn**
There is a case where the mapper parser throws a MapperParsingException instead of not consuming the `index:false` parameter. We missed that case in the previous fix (see #98038). This PR hardens that check by returning false when hitting a MapperParsingException.

Relates #98038

### CODE REVIEW

**Comment by dnhatn** [comment]
@elasticsearchmachine test this please

**Comment by dnhatn** [comment]
test this please

**Comment by dnhatn** [comment]
run elasticsearch-ci/part-1

**Review by jbaiera — APPROVED** [review]
LGTM! Thanks for jumping on this @dnhatn

**Comment by dnhatn** [comment]
@jbaiera Thanks for reviewing.

**Pull request merged**
