### PR TITLE
Add fast_refresh setting to core fleet-server index templates

### PR DESCRIPTION
**Pull request by michel-laterman**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)? yes
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md)? yes
- ~~If submitting code, have you built your formula locally prior to submission with `gradle check`?~~
- If submitting code, is your pull request against main? Unless there is a good reason otherwise, we prefer pull requests against main and will backport as needed. yes
- ~~If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?~~
- ~~If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.~~

### CODE REVIEW

**Review by joshdover — COMMENTED** [review]
I think we may want this on `.fleet-file` as well

**Comment by michel-laterman** [comment]
@joshdover do you know why some of the unit tests/jobs are failing and how I can fix them?

**Comment by nchaulet** [comment]
Looks like we can only define `fast_refresh` in stateless 
Screenshot 2023-07-25 at 1 05 52 PM

**Comment by michel-laterman** [comment]
Good catch @nchaulet, it's also set as part of the [feature's implementation pr](https://github.com/elastic/elasticsearch/pull/96660).

The description in [this pr](https://github.com/elastic/elasticsearch/pull/97763) indicates that we should be able to define serverless specific templates

**Pull request closed without merging**
