### PR TITLE
Add guidance on using CCR with Logstash

### PR DESCRIPTION
**Pull request by jasontedor**
This commit adds a note to the documentation regarding how to configure Logstash indices in the context of being available as leader indices for cross-cluster replication.

### CODE REVIEW

**Review by talevy — APPROVED** [review]

**Comment by talevy** [comment]
(LGTM once CI is happy)

**Comment by jasontedor** [comment]
@elasticmachine test this please

**Review by talevy — APPROVED** [review]
woohoo! LGTM

**Comment by jasontedor** [comment]
Thanks for reviewing and your support @talevy!

**Pull request merged**
