### PR TITLE
Some elasticsearch-cli tools could not be run not from ES_HOME

### PR DESCRIPTION
**Pull request by andrershov**
The issue was found when working on `elasticsearch-node` tool. 
1) Explicitly set path.data to relative to ES_HOME path in elasticsearch.yml.
2) Run `elasticsearch` from any directory. Elasticsearch is able to correctly start.
3) Stop Elasticsearch.
4) Run `elasticsearch-node unsafe-bootstrap` not from ES_HOME directory.  It will fail with the following exception
```
Exception in thread "main" ElasticsearchException[no node folder is found in data folder(s), node has not been started yet?]
```
This issue happens because `elasticsearch-node` uses `elasticsearch-cli` script that does not cd to ES_HOME before running the tool. `elasticsearch` launch script on the hand cd's to ES_HOME before running es java process.
This PR fixes the issue and adds a new test.
Also tests >=100 are renamed because alphabetic order does not work for them.

### CODE REVIEW

**Review by jasontedor — COMMENTED** [review]
Good change. Let's remove the `cd` from `bin/elasticsearch(.bat)?`.

**Comment by andrershov** [comment]
@jasontedor sorry, I don't undestand why do you propose to remove cd ES_HOME from bin/elasticsearch. bin/elasticsearch is not based on bin/elasticsearch-cli, so cd is still needed there

**Comment by andrershov** [comment]
run elasticsearch-ci/bwc

**Comment by jasontedor** [comment]
Sorry for causing the confusion. What I mean explicitly is, let us relocate this global to `elasticsearch-env`, and then remove this from `elasticsearch` and `elasticsearch-cli`. Does that help.

**Comment by rjernst** [comment]
Why do we need to cd at all? Shouldn't ensuring relative paths work be done in Environment, eg by making the path to path.data relative to ES_HOME if it is not absolute? I don't think we should rely on the working directory at all.

**Comment by jasontedor** [comment]
We need the working directory to be correct for ES for example to set the GC logs path relative to home. It’s not possible otherwise.

**Comment by andrershov** [comment]
Thanks, @jasontedor, I've made requested changes, can you please take a look?

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by jasontedor** [comment]
@andrershov I think that you missed backporting this to 7.x. Also note whether or not #40083 is applicable, and you'll need #40118 too. I've added the `backport pending` label to reflect this.

**Comment by andrershov** [comment]
@jasontedor thank you for noticing this, I've mistakenly pushed 7.x to my fork instead of this repo. Fixed.

**Pull request merged**
