### PR TITLE
Make `keyword` a family of field types

### PR DESCRIPTION
**Pull request by markharwood**
This change introduces a `familyTypeName` method to MappedFieldType for use in the field capabilities API. 
The `constant_keyword` and `wildcard` fields override this to return `keyword` to describe the family to which they belong.

Relates to #53175

### CODE REVIEW

**Comment by markharwood** [comment]
@costin - do you have any pointers for the best place to reset the SQL expectations that are failing here (see test output) now that I've changed the field capabilities as per what we agreed in https://github.com/elastic/elasticsearch/issues/53175 ?

**Comment by jimczi** [comment]
> do you have any pointers for the best place to reset the SQL expectations that are failing here (see test output) now that I've changed the field capabilities as per what we agreed in #53175 ?

I guess we have no choice but to replace all instance of `constant_keyword` by `keyword` in SQL.  It seems that most of the errors are on the test expectation that should be changed to `keyword` or `KEYWORD` depending on the context ?

**Comment by markharwood** [comment]
I got a little lost chasing expected vs actuals discrepancies when it looks like a lot of the expectations might come from `*csv-spec` files.

**Comment by costin** [comment]
@markharwood you're on the right path. The *.csv-spec files are the ones that indicate what we expect. For example:
`org.elasticsearch.xpack.sql.qa.security.JdbcCsvSpecIT.test {alias.testDescribeAlias}` indicates there's a failure inside `alias.csv-spec` for `describeAlias`, namely [here](https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/sql/qa/server/src/main/resources/alias.csv-spec#L28).

Hope this helps.

**Comment by costin** [comment]
Tagging @astefan for awareness since once this PR lands, we should remove the `constant_keyword` handling.

**Review by astefan — APPROVED** [review]
LGTM

**Review by jimczi — APPROVED** [review]
LGTM, we should also update the documentation in `_field_caps` to explain the `keyword` family ?

**Comment by jtibshirani** [comment]
@markharwood perhaps we should make a note in the migration/ breaking changes docs for 7.x explaining that `constant_keyword` is now presented as `keyword`.

**Pull request merged**
