### PR TITLE
Fixing typo for path.conf location

### PR DESCRIPTION
**Pull request by jalvar08**
Changing -Ees.path.conf to -Epath.conf

### CODE REVIEW

**Comment by jasontedor** [comment]
Thanks @jalvar08, can you sign the CLA?

**Comment by jalvar08** [comment]
Hi Jason,

I've tried to sign the page here:
https://www.elastic.co/contributor-agreement

I choose individual contributor and press the sign agreement button and all
it does is refresh the page.

**Comment by jasontedor** [comment]
@jalvar08 I'm sorry for the trouble, I can reproduce your issue. I will follow-up with someone to see if we can get it fixed.

**Comment by jasontedor** [comment]
@jalvar08 I believe the issues with CLA have been addressed if you're interested in trying again?

**Comment by jalvar08** [comment]
Yes it worked this time. I signed it.

**Comment by clintongormley** [comment]
thanks @jalvar08 - merged

**Pull request merged**
