### PR TITLE
Add support for the 'Anonymous IP' database to the geoip processor

### LINKED ISSUE #90789: GeoIP processor support for Maxmind Anonymous-IP-Database
### Description

In addition to the free databases, maxmind also offers where insightful others, especially the anonymous-ip-database:
https://www.maxmind.com/en/solutions/geoip2-enterprise-product-suite/anonymous-ip-database

This database provides information about an IP address being a TOR-node or belonging to some VPN provider.
It would be extremly useful to have the GeoIP processor support also this database - especially for cybersecurity use cases.

### PR DESCRIPTION
**Pull request by joegallo**
Closes https://github.com/elastic/elasticsearch/issues/90789

Adds support for the ['GeoIP2 Anonymous IP'](https://www.maxmind.com/en/solutions/geoip2-enterprise-product-suite/anonymous-ip-database) database from MaxMind to the `geoip` processor.

The `geoip` processor will automatically download the [various 'GeoLite2' databases](https://dev.maxmind.com/geoip/geolite2-free-geolocation-data), but the 'GeoIP2 Anonymous IP' database is not a 'GeoLite2' database -- it's a commercial database available to those with a suitable license from MaxMind.

The support that is being added for it in this PR is in line with the support that we already have for MaxMind's 'GeoIP2 City' and 'GeoIP2 Country' databases -- that is, one would need to arrange their own download management via some custom endpoint or otherwise arrange for the relevant file(s) to be in the `$ES_CONFIG/ingest-geoip` directory on the nodes of the cluster.

### CODE REVIEW

**Comment by joegallo** [comment]
@masseyke and I talked about the source of the `GeoIP2-Anonymous-IP-Test.mmdb` that I've added here -- it's from https://github.com/maxmind/MaxMind-DB/tree/main/test-data. That's the same as all the rest of our `${whatever}-Test.mmdb` files, and we have **many** of them in little nooks and crannies sprinkled around the Elasticsearch codebase. 

As follow up work after this PR, I would like to organize, update, and document all those files so that their provenance is clear.

**Comment by joegallo** [comment]
https://elasticsearch_bk_107287.docs-preview.app.elstc.co/diff docs preview link -- the build passed on the retry there, I'm not going to chase that down since I'm assuming we'll probably end up having another commit here before I merge it.

**Comment by joegallo** [comment]
I merged in `main` and accounted for the new work that has to be done to account for #107000 in the merge commit.

**Review by masseyke — APPROVED** [review]

**Comment by joegallo** [comment]
Related to https://github.com/elastic/elasticsearch/issues/101080

**Pull request merged**
