### PR TITLE
Core: Cut over to the Lucene filter cache.

### PR DESCRIPTION
**Pull request by jpountz**
Custom cache keys are not supported anymore, the filter itself is always used
as the key. However, this new filter cache better deals with large filters:
- filters are deduplicated so that the filter cache only holds a single
  reference to a given filter,
- the filter cache does memory accounting of the filters too, in particular
  TermsFilter implements Accountable and will be properly accounted.

Since custom cache keys are not supported anymore, it is not possible to clear
specific keys from the filter cache.

Time-based expiring is not supported anymore. This should not be an issue given
that cached entries cannot become outdated.

This commit also adds more usage statistics of the filter cache (in addition to
ram usage and evictions):
- hit count,
- miss count,
- total lookup count,
- number of doc id sets that have been cached,
- number of doc id sets in the cache.

In particular, the hit count and cache count are useful in order to figure out
how many times cached filters are reused on average.

### CODE REVIEW

**Comment by jpountz** [comment]
One point I forgot to mention: The previous cache had evictions that ran in O(#filters * #segments) which is essentially the reason why evictions were batched and ran in a background thread. On the other hand, the new cache runs evictions in the current thread and evictions run in O(#segments) when evicting a filter (because the cache is full) and O(1) when evicting a segment (because it got closed).

**Comment by jpountz** [comment]
A better solution would be to switch to IndexSearcher's built-in caching: https://issues.apache.org/jira/browse/LUCENE-6303

**Comment by rmuir** [comment]
I agree, this way caching can happen if e.g. a user sorts by price, uses stuff in a MUST_NOT, etc too.

**Comment by s1monw** [comment]
@jpountz what is the status of this, it would be nice to get this in?

**Comment by jpountz** [comment]
@s1monw I have not closed it yet since there is still some ongoing work on the lucene filter cache but I don't think this PR is necessary anymore if we get to use Lucene 5.1's IndexSearcher's built in caching mechanism. It will require less code than this PR and will also help cache queries that don't need scores.

**Comment by jpountz** [comment]
Closed in favour of https://github.com/elastic/elasticsearch/pull/10897 which gives IndexSearcher full responsibility for caching.

**Pull request closed without merging**
