### PR TITLE
[8.5] [DOCS] native realm needs to be explicitly disabled (#92279)

### PR DESCRIPTION
**Pull request by amyjtechwriter**
Backports the following commits to 8.5:
 - [DOCS] native realm needs to be explicitly disabled (#92279)

### CODE REVIEW

**Comment by amyjtechwriter** [comment]
@elasticmachine run elasticsearch-ci/rest-compatibility

**Comment by amyjtechwriter** [comment]
@elasticmachine run elasticsearch-ci/rest-compatibility

**Comment by amyjtechwriter** [comment]
@elasticsearchmachine update branch

**Comment by amyjtechwriter** [comment]
@elasticsearchmachine update branch

**Comment by amyjtechwriter** [comment]
@elasticmachine run elasticsearch-ci/part-1-fips

**Comment by amyjtechwriter** [comment]
@elasticmachine run elasticsearch-ci/rest-compatibility

**Comment by amyjtechwriter** [comment]
@elasticmachine run elasticsearch-ci/rest-compatibility

**Comment by abdonpijpelink** [comment]
@elasticmachine update branch

**Comment by abdonpijpelink** [comment]
Closing unmerged, as 8.5 is an old version.

**Pull request closed without merging**
