### PR TITLE
Implement Weight#scoreSupplier in SingleValueQuery.LuceneQuery

### PR DESCRIPTION
**Pull request by iverase**
Implementing ScoreSupplier is the recommended way to create a lucene weight nowadays. more over in Lucene 10 you are not allowed to implement Weight#score and you must implement Weight#scoreSupplier. Therefore let's do it now.

### CODE REVIEW

**Review by ChrisHegarty — APPROVED** [review]
LGTM

**Comment by iverase** [comment]
@elasticmachine update branch

**Comment by costin** [comment]
Worth backporting the bug to 8.14.x

**Review by nik9000 — APPROVED** [review]
LGTM, though I think we'll be replacing this query with a new one that @iverase is writing anyway.

**Comment by iverase** [comment]
Yes, I won't be pushing this change but propose this other change: https://github.com/elastic/elasticsearch/pull/110116

**Pull request closed without merging**
