### PR TITLE
Ensure _termStats is supported with function_score

### PR DESCRIPTION
**Pull request by afoucret**
Example usage:

```
GET movies/_search
{
  "query": {
    "function_score": {
      "query": { "match": { "title": "star trek" } },
      "script_score": {
        "script": { "source": "return _termStats.uniqueTermsCount()" }
      },
      "boost_mode": "sum"
    }
  }
}
```

### CODE REVIEW

**Review by rjernst — COMMENTED** [review]
This looks ok, but do we really need this new access in function scores? Function scores have been soft-deprecated (not officially, but we've stated our intention to deprecate them for a long time: https://github.com/elastic/elasticsearch/issues/42811). AFAIK the only remaining bit of work is https://github.com/elastic/elasticsearch/issues/52482 for feature parity with function score. Could we suggest to users they use score scripts instead?

**Comment by benwtrent** [comment]
@rjernst while we have publicly stated this in a single GH issue, I don't see function score as actually deprecated anywhere. Consequently, it isn't.

We should continue to support and update it until we actually deprecate it IMO.

**Review by rjernst — APPROVED** [review]
I'm not strongly opposed to this PR, the code looks fine. But I also don't see why it is _necessary_ since users can use script scores.

**Comment by afoucret** [comment]
@benwtrent @rjernst 

The main reason to add the support to the `function_score` is to provide consistent features to the script in the context of queries.
Also, the current implementation fails quite badly with an assertion error when using `_termStats` in a `function_score`.

**Pull request merged**
