### PR TITLE
Fix the REST FIPS tests

### LINKED ISSUE #60990: CI: FIPS builds in 7.8 and 7.9 failing due to `Crypto provider not installed: BCFIPS`
**Build scan**:
There are plenty:
https://gradle-enterprise.elastic.co/s/cuatj7biqc5vi
https://gradle-enterprise.elastic.co/s/frm5jnlfve2s4
https://gradle-enterprise.elastic.co/s/h3wtibymoo5ik
https://gradle-enterprise.elastic.co/s/bmahzvuq2tt3i

**Repro line**:
Running any YAML test fails.

**Reproduces locally?**:
Yes

**Applicable branches**:
7.8 and 7.9

**Failure excerpt**:
```
23:20:28 > Task :rest-api-spec:yamlRestTestRunner FAILED
23:20:28 java.security.ProviderException: Crypto provider not installed: BCFIPS
23:20:28 	at sun.security.ssl.SunJSSE.<init>(SunJSSE.java:142)
23:20:28 	at sun.security.ssl.SunJSSE.<init>(SunJSSE.java:123)
23:20:28 	at com.sun.net.ssl.internal.ssl.Provider.<init>(Provider.java:51)
23:20:28 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
23:20:28 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
23:20:28 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
23:20:28 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
23:20:28 	at sun.security.jca.ProviderConfig$2.run(ProviderConfig.java:224)
23:20:28 	at sun.security.jca.ProviderConfig$2.run(ProviderConfig.java:206)
23:20:28 	at java.security.AccessController.doPrivileged(Native Method)
```

### PR DESCRIPTION
**Pull request by jakelandis**
When run with the `-Dtests.fips.enabled=true` most all of the REST tests fail. 
This fixes most (all?) of the REST test failures in FIPS mode.

Specifically:

* The bouncy castle library was no longer on the classpath for the tests for 
[yaml/java]RestTests since they explicitly set the classpath to only that of 
the test sourceset. The fix for this to ensure that bouncy castle is added to 
classpath for these (and all) types of tests when running with FIPS.  

* The elasticsearch.java plugin is not applied to every standalone test project. 
This mainly impacts the specialized tests that setup custom test clusters such as CCR.
The fix for this is to hook into the java plugin instead of the elasticsearch.java plugin.  

* One or more project would throw an error about could not change dependency after 
evaluation (it did so without any of the changes here). The fix for this was to move 
the FIPS config out of the TestBasePlugin and just use the classpath addition via 
gradle/fips.gradle.

* Ingest attachment was conditionally disabling integTest, now it conditionally
 disables yamlRestTest

fixes #60990

### CODE REVIEW

**Comment by rjernst** [comment]
> The elasticsearch.java plugin is not applied to every standalone test project.
This mainly impacts the specialized tests that setup custom test clusters such as CCR.
The fix for this is to ensure that the bouncy castle classpath addition is not tied
directly to the elasticsearch.java plugin.

It seems like the testclusters configuration block is still guarded by use of elasticsearch.java. I see that we are now adding the bcfips jar files, but without the necessary jvm args for Tests that are nested underneath the testclusters block, won't we be actually executing the tests without fips?

**Comment by jakelandis** [comment]
> won't we be actually executing the tests without fips?

I expected some failures once run on CI for the reasons you mention, but hadn't considered false positives where it passes but not actually running in FIPS.  I will keep iterating on this ...

**Comment by jakelandis** [comment]
@rjernst this should be ready for review, the additional change is pretty minor but seems to do the trick https://github.com/elastic/elasticsearch/pull/61001/commits/5714e6de22b2a2673f9d2b34221537792c230c2d and pretty confident we won't get false positives. A scan of the filesystem and it appears that the bc jars are landing for all the specialized tests. I still have a couple failures locally, but don't think they are related... in short I am confident that this won't have false positives and fixes it for yaml/java REST tests, but not 100% sure that all tests are passing...need to commit to get CI to run the FIPS tests.

**Review by rjernst — APPROVED** [review]
LGTM

**Pull request merged**
