### PR TITLE
Break up field collapsing tests

### PR DESCRIPTION
**Pull request by mayya-sharipova**
Break up field collapsting tests into 2:
1) simple indexing and 2) indexingwith versions
to check if a problem of documents missing could be because of versions.

Relates to #52416

### CODE REVIEW

**Comment by mayya-sharipova** [comment]
I had a discussion with @ywelsch about this test failure. We initially hypothesize  that **typeless** indexing API could have some problems when using for 6.8 nodes. But after talking to @jtibshirani about this, she pointed out that this should not be a problem, as in our test framework in `ClientYamlTestExecutionContext#adaptRequestForOlderVersion` we add types to requests run agains 6.8 nodes.

So this PR introduces another hypothesis that a problem with missing documents could be related to `version` parameter.  To test this, the original test is broken into two tests: 1) simple indexing and 2) indexing with versions
to check if a problem of documents missing could be because of versions.

**Review by jtibshirani — APPROVED** [review]
I guess we will keep a close eye on the tests since we've unmuted them.

**Comment by mayya-sharipova** [comment]
I've chatted with @dnhatn offline, and he suggested to remove the test with versions entirely, as wee should  have other tests that verify versioning already.

**Review by dnhatn — APPROVED** [review]
LGTM. Thanks Mayya!

**Pull request merged**
