### PR TITLE
Add missing mime4j library

### PR DESCRIPTION
**Pull request by dadoonet**
In some cases (apparently with outlook files), mime4j library is needed.
We removed it in the past which can cause elasticsearch to crash when you are using ingest-attachment (and probably mapper-attachments as well in 2.x series) with a file which requires this library.

Backport of #22764 in 5.x branch
Applying same changes for mapper-attachments plugin (5.x branch)

### CODE REVIEW

**Comment by dadoonet** [comment]
@jasontedor I also applied changes for mapper-attachments. Can you check it please?

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by dadoonet** [comment]
Thanks @jasontedor !

**Comment by dadoonet** [comment]
Also backported to 5.2 branch with 0a8a7eb and 70e3c9f

**Pull request merged**
