### PR TITLE
Save Capturing Lambda in FieldMapper.Parameter Constructor

### PR DESCRIPTION
**Pull request by original-brownbear**
It's in the title. Since this thing is on the hot path of some CS updates
it's nice to clean up the capturing lambda here.

### CODE REVIEW

**Comment by original-brownbear** [comment]
Jenkins run  elasticsearch-ci/bwc

**Comment by original-brownbear** [comment]
@elasticmachine update branch

**Review by dnhatn — APPROVED** [review]
LGTM. Thanks Armin

**Comment by original-brownbear** [comment]
Thanks Nhat!

**Pull request merged**
