### PR TITLE
Optimize BytesReference related code field access patterns

### PR DESCRIPTION
**Pull request by original-brownbear**
Cache object fields (even when final, see https://openjdk.org/jeps/8132243) to generate smaller byte code as well as more optimized compiled code for this performance critical code.

### CODE REVIEW

**Comment by DaveCTurner** [comment]
Well this is just daft...

Could you add comments about this in the code otherwise this'll just accidentally get reverted by other surrounding changes. Also could we see some data to support this change (flamegraphs or similar).

**Comment by original-brownbear** [comment]
Uff but where do I add those comments? It's like a bazillion spots? It's a common optimization in the JDK itself, maybe we can trust people not to touch this stuff? :D I also wanted to do this in more spots actually, so adding a comment everywhere will add loads of lines.

I actually didn't benchmark these change, it's not entirely trivial to get good real world data for the transport messages. But the example from doing this same optimization to `LongHash` in aggs is quite striking:

Before:

image

After:

image

Fully inlined + the 2 things you see sticking out at the top of after (vtable and get) are just stuff that was reordered from elsewhere and isn't actually part of the code of the method. If you try this out with hsdis you can see that you, on x86, basically have a `mov` for every field access while local variable addresses tend to just go to a register if one's available giving you a massive speedup in loop type use-cases in particular.

**Comment by DaveCTurner** [comment]
> Uff but where do I add those comments? It's like a bazillion spots? It's a common optimization in the JDK itself, maybe we can trust people not to touch this stuff?

I don't think it's especially common knowledge no (it's honestly pretty daft that today's JIT can't work this out). There's a good chance of some random contributor + reviewer pair not knowing about this unless we call it out. Just a one-liner linking to the JEP would be enough.

**Comment by original-brownbear** [comment]
Alright then comments added, thanks for taking a look @DaveCTurner !

**Review by DaveCTurner — APPROVED** [review]
LGTM thanks Armin

**Comment by original-brownbear** [comment]
Thanks David!

**Pull request merged**
