### PR TITLE
QL: Make use of Java 17 instanceof pattern matching

### LINKED ISSUE #80884: QL: Make use of Java 17 instanceof pattern matching
Once main moves to JDK 17 language features, it's worth investigating the newly available [instanceof pattern matching](https://docs.oracle.com/en/java/javase/17/language/pattern-matching-instanceof-operator.html).
This translates the pattern:
```java
if (o instanceof Type) {
   Type t = (Type) o;
   // make use of t
   ...
```

to 
```java
if (o instanceof Type t) {
   // make use of t
  ...
```

It's syntactic sugar that removes the explicit cast (by making it inline).

### PR DESCRIPTION
**Pull request by costin**
Replace instanceof / cast with Java 17 instanceof pattern matching.
This small syntactic sugar improves readability and reduces the chance
for errors (by avoid to cast a different variable then the one checked).

Fix #80884

### CODE REVIEW

**Review by Luegg — APPROVED** [review]
Awesome! lgtm.

**Comment by costin** [comment]
@elasticmachine run elasticsearch-ci/part2

**Comment by costin** [comment]
@elasticmachine run elasticsearch-ci/part-2

**Review by bpintea — APPROVED** [review]
Nice!

**Review by astefan — APPROVED** [review]
LGTM

**Comment by costin** [comment]
Due to https://bugs.eclipse.org/bugs/show_bug.cgi?id=574437 I've had to add even more exceptions. I chose to add the exceptions so spotless gets this issue fixed, they can be easily tracked down and removed.
I would advice folks looking to migrate to wait if possible until the tooling gets updated.

**Comment by costin** [comment]
@elasticmachine update branch

**Pull request merged**
