### PR TITLE
Improve FutureUtils.get exception handling

### PR DESCRIPTION
**Pull request by henningandersen**
FutureUtils.get() would unwrap ElasticsearchWrapperExceptions. This
is trappy, since nearly all usages of FutureUtils.get() expected only to
not have to deal with checked exceptions.

In particular, StepListener builds upon ListenableFuture which uses
FutureUtils.get to be informed about the exception passed to onFailure.
This had the bad consequence of masking away any exception that was an
ElasticsearchWrapperException like RemoteTransportException.
Specifically for recovery, this made CircuitBreakerExceptions happening
on the target node look like they originated from the source node.

The only usage that expected that behaviour was AdapterActionFuture.
The unwrap behaviour has been moved to that class.

I marked this for 7.5.2, please consider that too during reviews.

### CODE REVIEW

**Comment by jaymode** [comment]
FutureUtils doesn't document the top level ElasticsearchException is throw away, do you know why it does so? That seems trappy

**Comment by henningandersen** [comment]
Thanks @jaymode , you are right, it is trappy. I originally refrained from fixing it there because this is used in AdapterActionFuture.actionGet (which is used in 100s of places and affects 7.x transport client). Doing more home-work on this, it seems this was originally introduced there to precisely [unwrap things like RemoteTransportException](#1292). A refactor [moved the code out into FutureUtils](#27801) and it has since been used in a couple more places (I believe only to avoid handling checked exceptions, not to get the unwrap effect).

I think the right solution is to not unwrap in FutureUtils and do this in AdapterActionFuture instead. I will amend the PR to reflect that.

**Comment by henningandersen** [comment]
This PR has been updated to fix this in FutureUtils.get() instead and is ready for review.

**Review by jaymode — APPROVED** [review]
LGTM

**Review by dnhatn — APPROVED** [review]
LGTM. Thanks Henning.

**Pull request merged**
