### PR TITLE
EQL: Adds an ability to execute an asynchronous EQL search

### LINKED ISSUE #49638: Make EQL REST Querying API async
Once we have the EQL REST Endpoint created from https://github.com/elastic/elasticsearch/issues/49634 we should explore making the API asynchronous. 

Since EQL queries will require multiple underlying search requests and may need to search through lots of data the queries could take a long time to execute. To give a better user experience it would be good if the query can be executed asynchronously with the user able to request progress and retrieve the final results when they are available.

We already have development underway on adding an asynchronous search API (https://github.com/elastic/elasticsearch/issues/49091) so the user experience we add here should be as similar to that as practical so we have consistency in the approaches. The reason we can't just piggyback on the async search API is that the EQL plugin will need to run extra logic on top of the search API, which will require it to have its own async mechanism.

### PR DESCRIPTION
**Pull request by imotov**
Adds async support to EQL searches

Closes #49638

### CODE REVIEW

**Review by jimczi — APPROVED** [review]
I left the specific EQL part for @costin but the refactoring of the async components looks good to me. Thanks for iterating on this @imotov !

**Comment by imotov** [comment]
@elasticmachine update branch

**Comment by imotov** [comment]
@elasticmachine update branch

**Comment by imotov** [comment]
@elasticmachine update branch

**Review by costin — APPROVED** [review]
LGTM

**Comment by imotov** [comment]
@elasticmachine update branch

**Comment by imotov** [comment]
@jimczi @costin thanks a lot for reviews and guidance!!!

**Pull request merged**
