### PR TITLE
add integration tests for tar/deb/rpm packaging

### PR DESCRIPTION
**Pull request by rmuir**
There are no automated tests for these packages. But we can do various types of verification, at the minimum extract the contents of the package with `dpkg-deb` or `rpm` or `tar`, start elasticsearch, and run integration tests.

These tests are not perfect, they are not installing the stuff on a virtual machine. But they are better than no tests like this, and simple to understand.

There are more cleanups to do here after, but this is really missing.

### CODE REVIEW

**Comment by rmuir** [comment]
`mvn verify` passes on machines with and without these tools (rpm, dpkg-deb) available.

**Comment by spinscale** [comment]
ran this on OSX, where it worked flawless. However on ubuntu it seems to not run as part of the reactor build (ran from the root directory and skipped unit tests as this was a VM), so running `mvn clean verify -Dskip.unit.tests` resulted in

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (integ-setup) on project elasticsearch-tar: An Ant BuildException has occured: The following error occurred while executing this line:
[ERROR] /tmp/elasticsearch/distribution/tar/target/dev-tools/ant/integration-tests.xml:198: The following error occurred while executing this line:
[ERROR] /tmp/elasticsearch/distribution/tar/target/dev-tools/ant/integration-tests.xml:127: The following error occurred while executing this line:
[ERROR] /tmp/elasticsearch/distribution/tar/target/dev-tools/ant/integration-tests.xml:53: /tmp/elasticsearch/distribution/tar/target/integ-tests/es.pid doesn't exist
[ERROR] around Ant part ...<ant antfile="/tmp/elasticsearch/distribution/tar/target/dev-tools/ant/integration-tests.xml" target="start-external-cluster-tar"/>... @ 4:134 in /tmp/elasticsearch/distribution/tar/target/antrun/build-main.xml
[ERROR] -> [Help 1]
```

somehow some old .xml file is being reused or I did anything wrong?

**Comment by rmuir** [comment]
Probably a port conflict (es already running on 9200) or something like that. Thats still a TODO of mine, to use a different port in testing. One that won't conflict with what devs do with their machines :)

**Comment by rmuir** [comment]
@spinscale take a look inside .../distribution/tar/target/integ-tests/elasticsearch-xxxx/logs/prepare-release.log or whatever if you really want to confirm. And if you try again, do full mvn clean and check no other ES is running with `jps` first.

**Comment by spinscale** [comment]
all right worked on osx and ubuntu after cleaning up. awesome!

LGTM

**Pull request merged**
