### PR TITLE
Fix Bootstrap to not call System.exit

### PR DESCRIPTION
**Pull request by rmuir**
Its not going to work: its blocked by security policy
and will just add a confusing SecurityException to the mix, and
bogusly give an exit status of 0 when in fact something bad happened.

Finally, if ES can't startup, it is a serious problem, there is
no sense in hiding the reason why: deliver the full stack trace.

### CODE REVIEW

**Comment by rjernst** [comment]
LGTM

**Comment by jpountz** [comment]
LGTM2

**Comment by jpountz** [comment]
This makes me wonder whether we should make it a forbidden API so that the build would catch if it gets added back?

**Comment by tlrx** [comment]
+1 I like this, it's cleaner now

**Comment by s1monw** [comment]
LGTM 2 FWIW

**Comment by rmuir** [comment]
> This makes me wonder whether we should make it a forbidden API so that the build would catch if it gets added back?

We could, but thats a bigger change impacting a (way-too-huge) codebase. Ill make a followup issue.

**Pull request merged**
