### PR TITLE
fix testRandomRanges failed with -Dtest.seed A4648847991E5C27

### LINKED ISSUE #19697: EquivalenceIT fails reproducibly with a seed
```
  2> REPRODUCE WITH: gradle :core:integTest -Dtests.seed=A4648847991E5C27 -Dtests.class=org.elasticsearch.search.aggregations.EquivalenceIT -Dtests.method="testRandomRanges" -Dtests.security.manager=true -Dtests.jvms=12 -Dtests.locale=nn-NO -Dtests.timezone=Europe/Helsinki
FAILURE 5.55s J10 | EquivalenceIT.testRandomRanges <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 4 expected:<889> but was:<890>
   >    at __randomizedtesting.SeedInfo.seed([A4648847991E5C27:D00DCF66E03EFC10]:0)
   >    at org.elasticsearch.search.aggregations.EquivalenceIT.testRandomRanges(EquivalenceIT.java:186)
   >    at java.lang.Thread.run(Thread.java:745)
```

### PR DESCRIPTION
**Pull request by chengpohi**
Closes #19697

### CODE REVIEW

**Comment by nik9000** [comment]
@elasticmachine , test this patch.

**Comment by nik9000** [comment]
Looks right to me! I've kicked off a CI build of it just in case.

Do you think any other tests in that class have the same problem?

**Comment by chengpohi** [comment]
@nik9000 , I have updated the other test cases in this class, that maybe also occur rounding issue.

**Comment by nik9000** [comment]
@chengpohi merged! Thanks very much for fixing it!

**Pull request merged**
