### PR TITLE
updated module.xml

### PR DESCRIPTION
**Pull request by mr-stephan**
The filenames are updated to fit to the current elasticsearch version 1.4.4.

### CODE REVIEW

**Comment by javanna** [comment]
Thanks @ahrradfahrer may I ask if you already singed our [CLA](https://www.elastic.co/contributor-agreement)? If not could you please do so we can merge your PR?

**Comment by clintongormley** [comment]
CLA signed - need similar updates in 1.5, 1.x and master

**Comment by javanna** [comment]
merged, thanks @fahrradfahrer !

@clintongormley we don't have placeholders for the current es and lucene version do we? that would help keeping them in sync, otherwise they will get outdated again very soon.

**Comment by clintongormley** [comment]
@javanna we have placeholders at the start of some docs, eg see https://raw.githubusercontent.com/elastic/elasticsearch/master/docs/reference/index.asciidoc

**Pull request closed without merging**
