### PR TITLE
Propagate `supportsObjectAutoFlattening` in DocumentParserContext

### PR DESCRIPTION
**Pull request by kkrik-es**
Evaluating this in every context is too expensive.

### CODE REVIEW

**Review by dnhatn — APPROVED** [review]
LGTM. Thanks @kkrik-es

**Review by lkts — APPROVED** [review]
What happens when a child object sets `subobjects: true`? Do we handle this in other place?

**Comment by kkrik-es** [comment]
> What happens when a child object sets `subobjects: true`? Do we handle this in other place?

`true` is not a problem, everything works as before. Setting to `false` or `auto` requires extra work to figure out if subpaths need to be combined.

I added this check to avoid extra work, only to add a ton of the latter..

**Review by martijnvg — APPROVED** [review]
LGTM 🚀

**Pull request merged**
