### PR TITLE
Replace some bounds checking with Objects.checkFromIndexSize

### PR DESCRIPTION
**Pull request by pugnascotia**
Part of #36108. Replace some manual bounds checks with a utility method, which is itself replaced with an optimized version on JDK 9+.

There may be other places where this replacement could be made.

@jpountz since you raised #36108, can you think of anywhere else to make this change? I grepped for a few patterns, but didn't come up with much else. There is [this line in common/lucene/Lucene.java](https://github.com/elastic/elasticsearch/blob/bbc29bb0fd79f8aa124ba1765491cdb4d827c105/server/src/main/java/org/elasticsearch/common/lucene/Lucene.java#L829), but the limits on the bounds checking there look slightly different to `checkFromIndexSize()`.

### CODE REVIEW

**Comment by jasontedor** [comment]
In master, we can use `Objects#checkIndex` and it's friends directly, since we require JDK 11 there. Maybe we don't need to backport this, unless it proves to be a major enhancement, and we can keep it simple and use the underlying API directly in master only?

**Comment by pugnascotia** [comment]
I've replaced the current calls and the ones I added with `Objects.checkFromIndexSize()`

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by pugnascotia** [comment]
@elasticmachine update branch

**Comment by pugnascotia** [comment]
Do we want to leave #36108 open, or shall I close it now?

**Comment by jasontedor** [comment]
Let's close it.

**Pull request merged**
