### PR TITLE
Acknowledge index deletion requests based on standard cluster state acknowledgment

### LINKED ISSUE #18558: [CI] org.elasticsearch.indices.IndicesServiceTests.testDeleteIndexStore fails due to state file not existing
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-intake/636/console

The failure is:

```
ERROR   0.14s J1 | IndicesServiceTests.testDeleteIndexStore <<< FAILURES!
   > Throwable #1: ElasticsearchException[java.io.IOException: failed to read [id:1, legacy:false, file:/var/lib/jenkins/workspace/elastic+elasticsearch+master+multijob-intake/core/build/testrun/test/J1/temp/org.elasticsearch.indices.IndicesServiceTests_678304BAB99F89CE-001/tempDir-011/data/single-node-cluster-CHILD_VM=[1]-CLUSTER_SEED=[3730156636843346220]-HASH=[2CC2E218290088]/nodes/0/_state/global-1.st]]; nested: IOException[failed to read [id:1, legacy:false, file:/var/lib/jenkins/workspace/elastic+elasticsearch+master+multijob-intake/core/build/testrun/test/J1/temp/org.elasticsearch.indices.IndicesServiceTests_678304BAB99F89CE-001/tempDir-011/data/single-node-cluster-CHILD_VM=[1]-CLUSTER_SEED=[3730156636843346220]-HASH=[2CC2E218290088]/nodes/0/_state/global-1.st]]; nested: NoSuchFileException[/var/lib/jenkins/workspace/elastic+elasticsearch+master+multijob-intake/core/build/testrun/test/J1/temp/org.elasticsearch.indices.IndicesServiceTests_678304BAB99F89CE-001/tempDir-011/data/single-node-cluster-CHILD_VM=[1]-CLUSTER_SEED=[3730156636843346220]-HASH=[2CC2E218290088]/nodes/0/_state/global-1.st];
   > 	at __randomizedtesting.SeedInfo.seed([678304BAB99F89CE:D34003C59E7578EF]:0)
   > 	at org.elasticsearch.ExceptionsHelper.maybeThrowRuntimeAndSuppress(ExceptionsHelper.java:164)
   > 	at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:321)
   > 	at org.elasticsearch.gateway.MetaStateService.loadGlobalState(MetaStateService.java:109)
   > 	at org.elasticsearch.gateway.MetaStateService.loadFullState(MetaStateService.java:54)
   > 	at org.elasticsearch.gateway.GatewayMetaState.loadMetaState(GatewayMetaState.java:102)
   > 	at org.elasticsearch.indices.IndicesServiceTests.testDeleteIndexStore(IndicesServiceTests.java:128)
   > 	at java.lang.Thread.run(Thread.java:745)
   > Caused by: java.io.IOException: failed to read [id:1, legacy:false, file:/var/lib/jenkins/workspace/elastic+elasticsearch+master+multijob-intake/core/build/testrun/test/J1/temp/org.elasticsearch.indices.IndicesServiceTests_678304BAB99F89CE-001/tempDir-011/data/single-node-cluster-CHILD_VM=[1]-CLUSTER_SEED=[3730156636843346220]-HASH=[2CC2E218290088]/nodes/0/_state/global-1.st]
   > 	at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:316)
   > 	... 41 more
   > Caused by: java.nio.file.NoSuchFileException: /var/lib/jenkins/workspace/elastic+elasticsearch+master+multijob-intake/core/build/testrun/test/J1/temp/org.elasticsearch.indices.IndicesServiceTests_678304BAB99F89CE-001/tempDir-011/data/single-node-cluster-CHILD_VM=[1]-CLUSTER_SEED=[3730156636843346220]-HASH=[2CC2E218290088]/nodes/0/_state/global-1.st
   > 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
   > 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
   > 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
   > 	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
   > 	at org.apache.lucene.mockfile.FilterFileSystemProvider.newByteChannel(FilterFileSystemProvider.java:212)
   > 	at org.apache.lucene.mockfile.FilterFileSystemProvider.newByteChannel(FilterFileSystemProvider.java:212)
   > 	at org.apache.lucene.mockfile.FilterFileSystemProvider.newByteChannel(FilterFileSystemProvider.java:212)
   > 	at org.apache.lucene.mockfile.HandleTrackingFS.newByteChannel(HandleTrackingFS.java:240)
   > 	at org.apache.lucene.mockfile.FilterFileSystemProvider.newByteChannel(FilterFileSystemProvider.java:212)
   > 	at org.apache.lucene.mockfile.HandleTrackingFS.newByteChannel(HandleTrackingFS.java:240)
   > 	at org.apache.lucene.mockfile.FilterFileSystemProvider.newByteChannel(FilterFileSystemProvider.java:212)
   > 	at java.nio.file.Files.newByteChannel(Files.java:361)
   > 	at java.nio.file.Files.newByteChannel(Files.java:407)
   > 	at org.apache.lucene.store.SimpleFSDirectory.openInput(SimpleFSDirectory.java:77)
   > 	at org.elasticsearch.gateway.MetaDataStateFormat.read(MetaDataStateFormat.java:182)
   > 	at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:311)
   > 	... 41 more
```

However, it does not reproduce, here's the reproduction line:

```
gradle :core:test -Dtests.seed=678304BAB99F89CE -Dtests.class=org.elasticsearch.indices.IndicesServiceTests -Dtests.method="testDeleteIndexStore" -Dtests.security.manager=true -Dtests.locale=sv-SE -Dtests.timezone=Asia/Macau
```

### PR DESCRIPTION
**Pull request by ywelsch**
Index deletion requests currently use a custom acknowledgement mechanism that wait for the data nodes to actually delete the data before acknowledging the request to the client. This was initially put into place as a new index with same name could only be created if the old index was wiped as we used the index name as data folder on the data nodes. With PR #16442, we now use the index uuid as folder name which avoids collision between indices that are named the same (deleted and recreated). This allows us to get rid of the custom acknowledgment mechanism altogether and rely on the standard cluster state-based acknowledgment instead.

Closes #18558

### CODE REVIEW

**Comment by bleskes** [comment]
@ywelsch and I talked about it offline, discussing the fact that this change uses two ack mechanism layered on top of each other (with two futures, two timeouts etc.) which makes things complex. We are currently evaluating whether specific index store deletion acks are needed now that we have uuids as folder names and based on that decide whether we want to invest more time here or just move to the standard cluster state based ack-ing.

**Comment by ywelsch** [comment]
@bleskes I've updated the PR by removing the custom ack mechanism and relying only on the standard cluster state ack.

**Comment by bleskes** [comment]
LGTM. Best stats ever. Can you update the PR description/title?

**Comment by ywelsch** [comment]
Thanks @bleskes! I've updated title/description.

**Pull request merged**
