### PR TITLE
Indices Exists API should return 404 for empty wildcards

### PR DESCRIPTION
**Pull request by polyfractal**
We only checked if resolving an index pattern throws an exception, not the number of resolved indices.  In the case of wildcards, no exception is thrown but the array of concrete indices is empty.

This caused `does_not_exist*` to return a 200 instead of 404.

This commit fixes the issue, refactors slightly to make it testable, and does some refactoring due to legacy line-lengths.  The testability refactor probably wasn't _really_ needed, but it felt odd making the change without adding a test.

### CODE REVIEW

**Comment by polyfractal** [comment]
Jenkins, run gradle build tests

**Review by nik9000 — COMMENTED** [review]
I think this is the right thing to do but it is a breaking change, even though it is fairly hard to bump into and consistent with the way that other APIs work. How would you feel about making this 7.0 only and adding a breaking change note?

**Comment by polyfractal** [comment]
Works for me!  I'll make the change in a few.

**Comment by polyfractal** [comment]
Went to add a yml REST test and it kept failing consistently.  Turns out GetIndicesExists has no associated REST handler, and the [URL is registered to GetIndex instead](https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/rest/action/admin/indices/RestGetIndicesAction.java#L50).

I'm assuming this isn't intentional, because otherwise all the GetIndices code is essentially dead code except for TransportClient usage.  I'll add a REST handler for this and some more tests.

**Comment by javanna** [comment]
It is intentional @polyfractal . The exists actions that are only used by the transport client should be removed, I have looked into this in the past but it's not so easy without breaking the transport client. see https://github.com/elastic/elasticsearch/issues/27681#issuecomment-349572445 for some history.

**Comment by polyfractal** [comment]
Ahh, good to know, thanks for the background @javanna.  I'll take a closer look and see how/if we can adjust the GetIndex actions to behave properly (e.g. an empty wildcard returns `{}` for the GET request which is fine, but that translates into `200 OK` or HEAD requests which is less good)

Thanks!

**Comment by javanna** [comment]
the outlined HEAD behaviour with wildcards is odd, yet if we change that we should also change the GET behaviour by making the API return 404 when there are no matching indices, I think. We should always have consistent behaviour between GET and HEAD, which was the point of the changes that made the exists transport actions obsolete.

**Comment by polyfractal** [comment]
Seeing as this turned out substantially different than I expected, I'm going to close the PR and open an issue to discuss how (or if) the GetIndex actions should be modified to deal with the status code issue.

**Pull request closed without merging**
