### PR TITLE
Fix failure in TransformPivotRestSpecialCasesIT::testIndexTemplateMappingClash

### LINKED ISSUE #71792: [CI] Reproducible Failure in org.elasticsearch.xpack.transform.integration.TransformPivotRestSpecialCasesIT.testIndexTemplateMappingClash
The following fails for me locally every time on current master:

```
 ./gradlew ':x-pack:plugin:transform:qa:single-node-tests:javaRestTest' --tests "org.elasticsearch.xpack.transform.integration.TransformPivotRestSpecialCasesIT.testIndexTemplateMappingClash" -Dtests.seed=642C08CC77828612 -Dtests.security.manager=true -Dtests.locale=sv-SE -Dtests.timezone=ECT -Druntime.java=11
```

fails as:

```
org.elasticsearch.xpack.transform.integration.TransformPivotRestSpecialCasesIT > testIndexTemplateMappingClash FAILED
    org.elasticsearch.client.WarningFailureException: method [PUT], host [http://[::1]:32843], URI [_template/special_pivot_template], status line [HTTP/1.1 200 OK]
    Warnings: [Legacy index templates are deprecated and will be removed completely in a future version. Please use composable templates instead.]
    {"acknowledged":true}
        at __randomizedtesting.SeedInfo.seed([642C08CC77828612:4A70332C96BD2688]:0)
        at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:326)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270)
        at org.elasticsearch.xpack.transform.integration.TransformPivotRestSpecialCasesIT.testIndexTemplateMappingClash(TransformPivotRestSpecialCasesIT.java:66)
REPRODUCE WITH: ./gradlew ':x-pack:plugin:transform:qa:single-node-tests:javaRestTest' --tests "org.elasticsearch.xpack.transform.integration.TransformPivotRestSpecialCasesIT.testIndexTemplateMappingClash" -Dtests.seed=642C08CC77828612 -Dtests.security.manager=true -Dtests.locale=sv-SE -Dtests.timezone=ECT -Druntime.java=11

Suite: Test class org.elasticsearch.xpack.transform.integration.TransformPivotRestSpecialCasesIT
  1> [2021-04-18T14:22:38,405][INFO ][o.e.x.t.i.TransformPivotRestSpecialCasesIT] [testIndexTemplateMappingClash] before test
  1> [2021-04-18T14:22:38,505][INFO ][o.e.x.t.i.TransformPivotRestSpecialCasesIT] [testIndexTemplateMappingClash] initializing REST clients against [http://[::1]:32843, http://127.0.0.1:33657]
  1> [2021-04-18T14:22:39,809][WARN ][o.e.c.RestClient         ] [testIndexTemplateMappingClash] request [PUT http://[::1]:32843/_template/special_pivot_template] returned 1 warnings: [299 Elasticsearch-8.0.0-SNAPSHOT-b390cbda345d4b6b88831f84e516ce6557297cf6 "Legacy index templates are deprecated and will be removed completely in a future version. Please use composable templates instead."]
  1> [2021-04-18T14:22:39,817][INFO ][o.e.x.t.i.TransformPivotRestSpecialCasesIT] [testIndexTemplateMappingClash] writing audit messages to the log
  1> [2021-04-18T14:22:40,123][INFO ][o.e.x.t.i.TransformPivotRestSpecialCasesIT] [testIndexTemplateMappingClash] after test
  2> REPRODUCE WITH: ./gradlew ':x-pack:plugin:transform:qa:single-node-tests:javaRestTest' --tests "org.elasticsearch.xpack.transform.integration.TransformPivotRestSpecialCasesIT.testIndexTemplateMappingClash" -Dtests.seed=642C08CC77828612 -Dtests.security.manager=true -Dtests.locale=sv-SE -Dtests.timezone=ECT -Druntime.java=11
  2> org.elasticsearch.client.WarningFailureException: method [PUT], host [http://[::1]:32843], URI [_template/special_pivot_template], status line [HTTP/1.1 200 OK]
    Warnings: [Legacy index templates are deprecated and will be removed completely in a future version. Please use composable templates instead.]
    {"acknowledged":true}
        at __randomizedtesting.SeedInfo.seed([642C08CC77828612:4A70332C96BD2688]:0)
        at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:326)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270)
        at org.elasticsearch.xpack.transform.integration.TransformPivotRestSpecialCasesIT.testIndexTemplateMappingClash(TransformPivotRestSpecialCasesIT.java:66)
  2> NOTE: leaving temporary files on disk at: /home/brownbear/src/elasticsearch/x-pack/plugin/transform/qa/single-node-tests/build/testrun/javaRestTest/temp/org.elasticsearch.xpack.transform.integration.TransformPivotRestSpecialCasesIT_642C08CC77828612-002
  2> NOTE: test params are: codec=Lucene87, sim=Asserting(RandomSimilarity(queryNorm=false): {}), locale=sv-SE, timezone=ECT
  2> NOTE: Linux 5.8.0-50-generic amd64/Oracle Corporation 11.0.2 (64-bit)/cpus=48,threads=1,free=423123936,total=536870912
  2> NOTE: All tests run in this JVM: [TransformPivotRestSpecialCasesIT]

Tests with failures:
 - org.elasticsearch.xpack.transform.integration.TransformPivotRestSpecialCasesIT.testIndexTemplateMappingClash

1 test completed, 1 failed

=== Log output of node `node{:x-pack:plugin:transform:qa:single-node-tests:javaRestTest-0}` ===

»    ↓ errors and warnings from /home/brownbear/src/elasticsearch/x-pack/plugin/transform/qa/single-node-tests/build/testclusters/javaRestTest-0/logs/javaRestTest.log ↓
» [2021-04-18T14:22:36,838][WARN ][o.e.d.FileBasedSeedHostsProvider] [javaRestTest-0] expected, but did not find, a dynamic hosts list at [/home/brownbear/src/elasticsearch/x-pack/plugin/transform/qa/single-node-tests/build/testclusters/javaRestTest-0/config/unicast_hosts.txt]
»   ↓ last 40 non error or warning messages from /home/brownbear/src/elasticsearch/x-pack/plugin/transform/qa/single-node-tests/build/testclusters/javaRestTest-0/logs/javaRestTest.log ↓
» [2021-04-18T14:22:37,417][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] adding template [.ml-state] for index patterns [.ml-state*]
» [2021-04-18T14:22:37,464][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] adding template [.ml-stats] for index patterns [.ml-stats-*]
» [2021-04-18T14:22:37,517][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] adding component template [metrics-settings]
» [2021-04-18T14:22:37,565][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] adding component template [logs-mappings]
» [2021-04-18T14:22:37,611][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] adding component template [metrics-mappings]
» [2021-04-18T14:22:37,653][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] adding component template [synthetics-settings]
» [2021-04-18T14:22:37,692][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] adding component template [synthetics-mappings]
» [2021-04-18T14:22:37,729][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] adding component template [logs-settings]
» [2021-04-18T14:22:37,803][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] adding index template [.watch-history-14] for index patterns [.watcher-history-14*]
» [2021-04-18T14:22:37,846][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] adding index template [ilm-history] for index patterns [ilm-history-5*]
» [2021-04-18T14:22:37,885][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] adding index template [.slm-history] for index patterns [.slm-history-5*]
» [2021-04-18T14:22:37,923][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] adding component template [.deprecation-indexing-settings]
» [2021-04-18T14:22:37,962][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] adding component template [.deprecation-indexing-mappings]
» [2021-04-18T14:22:38,002][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] adding template [.monitoring-alerts-7] for index patterns [.monitoring-alerts-7]
» [2021-04-18T14:22:38,051][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] adding template [.monitoring-es] for index patterns [.monitoring-es-7-*]
» [2021-04-18T14:22:38,094][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] adding template [.monitoring-kibana] for index patterns [.monitoring-kibana-7-*]
» [2021-04-18T14:22:38,139][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] adding template [.monitoring-logstash] for index patterns [.monitoring-logstash-7-*]
» [2021-04-18T14:22:38,206][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] adding template [.monitoring-beats] for index patterns [.monitoring-beats-7-*]
» [2021-04-18T14:22:38,251][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] adding index template [metrics] for index patterns [metrics-*-*]
» [2021-04-18T14:22:38,292][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] adding index template [synthetics] for index patterns [synthetics-*-*]
» [2021-04-18T14:22:38,333][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] adding index template [logs] for index patterns [logs-*-*]
» [2021-04-18T14:22:38,374][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] adding index template [.deprecation-indexing-template] for index patterns [.logs-deprecation.*]
» [2021-04-18T14:22:38,413][INFO ][o.e.x.i.a.TransportPutLifecycleAction] [javaRestTest-0] adding index lifecycle policy [ml-size-based-ilm-policy]
» [2021-04-18T14:22:38,457][INFO ][o.e.x.i.a.TransportPutLifecycleAction] [javaRestTest-0] adding index lifecycle policy [synthetics]
» [2021-04-18T14:22:38,501][INFO ][o.e.x.i.a.TransportPutLifecycleAction] [javaRestTest-0] adding index lifecycle policy [logs]
» [2021-04-18T14:22:38,540][INFO ][o.e.x.i.a.TransportPutLifecycleAction] [javaRestTest-0] adding index lifecycle policy [metrics]
» [2021-04-18T14:22:38,573][INFO ][o.e.x.i.a.TransportPutLifecycleAction] [javaRestTest-0] adding index lifecycle policy [watch-history-ilm-policy]
» [2021-04-18T14:22:38,608][INFO ][o.e.x.i.a.TransportPutLifecycleAction] [javaRestTest-0] adding index lifecycle policy [ilm-history-ilm-policy]
» [2021-04-18T14:22:38,643][INFO ][o.e.x.i.a.TransportPutLifecycleAction] [javaRestTest-0] adding index lifecycle policy [slm-history-ilm-policy]
» [2021-04-18T14:22:38,681][INFO ][o.e.x.i.a.TransportPutLifecycleAction] [javaRestTest-0] adding index lifecycle policy [.deprecation-indexing-ilm-policy]
» [2021-04-18T14:22:38,729][INFO ][o.e.c.m.MetadataCreateIndexService] [javaRestTest-0] [reviews] creating index, cause [api], templates [], shards [1]/[1]
» [2021-04-18T14:22:38,913][INFO ][o.e.l.LicenseService     ] [javaRestTest-0] license [ae96f6bf-bbcb-4a4d-8ca2-ab856f989cfb] mode [trial] - valid
» [2021-04-18T14:22:38,913][INFO ][o.e.x.s.s.SecurityStatusChangeListener] [javaRestTest-0] Active license is now [TRIAL]; Security is enabled
» [2021-04-18T14:22:39,771][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] adding template [special_pivot_template] for index patterns [special_pivot_template*]
» [2021-04-18T14:22:39,899][INFO ][o.e.c.m.MetadataIndexTemplateService] [javaRestTest-0] removing template [special_pivot_template]
» [2021-04-18T14:22:39,986][INFO ][o.e.x.i.a.TransportPutLifecycleAction] [javaRestTest-0] adding index lifecycle policy [synthetics]
» [2021-04-18T14:22:40,060][INFO ][o.e.x.i.a.TransportPutLifecycleAction] [javaRestTest-0] adding index lifecycle policy [.deprecation-indexing-ilm-policy]
» [2021-04-18T14:22:40,157][INFO ][o.e.c.m.MetadataDeleteIndexService] [javaRestTest-0] [reviews/L1gCjJSXQPGWJdlZ6Qmf7w] deleting index
» [2021-04-18T12:22:40.251227705Z] [BUILD] Stopping node

> Task :x-pack:plugin:transform:qa:single-node-tests:javaRestTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':x-pack:plugin:transform:qa:single-node-tests:javaRestTest'.

```

Also happened on CI now here: https://gradle-enterprise.elastic.co/s/y2c2zcdsg3zhc

### PR DESCRIPTION
**Pull request by danhermann**
Fixes a test that wasn't caught in the PR build for https://github.com/elastic/elasticsearch/pull/71309

Fixes #71792

### CODE REVIEW

**Comment by danhermann** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Review by henningandersen — APPROVED** [review]
LGTM.

**Comment by henningandersen** [comment]
Muted in 7.x and master (#71810).

**Review by hendrikmuhs — APPROVED** [review]
LGTM

But please rebase and unmute https://github.com/elastic/elasticsearch/commit/567c56e5fa8414e7382e046821e4ff052b2e3871 with the merge.

**Comment by danhermann** [comment]
@elasticmachine update branch

**Comment by danhermann** [comment]
Thanks, @henningandersen and @hendrikmuhs.

**Pull request merged**
