### PR TITLE
[Fleet] Add `.fleet-secrets` system index 

### LINKED ISSUE #95143: [Fleet] Create .fleet-secrets system index
Part of https://github.com/elastic/kibana/issues/154715

The `.fleet-secrets` system index should just have a value key. 

Kibana system should only have write and delete access NOT read access.

Fleet server will have read access only. 

Example document:

```
// example document from the .fleet-secrets index 
{
	_id: 'abcd1234'
	_source: {
	   value: "abcd12345678",
      }
}
```

### PR DESCRIPTION
**Pull request by hop-dev**
Part of https://github.com/elastic/kibana/issues/154715

Closes https://github.com/elastic/elasticsearch/issues/95143

The .fleet-secrets index will contain agent policy secrets. An example of a secret is a password or API key. Kibana has write access only to the index, and fleet server has read access.

I have kept it in the fleet area as it is managed by us.

### CODE REVIEW

**Comment by hop-dev** [comment]
@elasticsearchmachine merge upstream

**Review by rjernst — COMMENTED** [review]
I've asked @williamrandolph to take a look, but in the meantime, I have one general thought. While I understand the note about the intention to use this index with enterprise search in the future, I think the name is too generic. It could easily be confused by developers as a general purpose index within Elasticsearch internals, such as .security. I think the name should be narrowed.

One idea is `.external-secrets`. Another (and my preferred) is to use `.fleet-secrets` here, and use another system index name for enterprise search. In any case, these are system indices, so the preferred approach is to wrap these indices with rest apis which have complete control over them. Then the particular index name matters even less.

**Comment by jimczi** [comment]
> One idea is .external-secrets. Another (and my preferred) is to use .fleet-secrets here, and use another system index name for enterprise search. In any case, these are system indices, so the preferred approach is to wrap these indices with rest apis which have complete control over them. Then the particular index name matters even less.

+1 for `.fleet-secrets`, the sharing is not mandatory and we might want different rest APIs for fleet and enterprise-search.

**Comment by hop-dev** [comment]
@rjernst @jimczi I have moved to .fleet-secrets now

**Comment by juliaElastic** [comment]
@rjernst @jimczi Are you ready to approve? We are waiting for this to go ahead with the Fleet feature.

**Comment by juliaElastic** [comment]
@hop-dev updated a few remaining occurrences of `.secrets`.

**Comment by hop-dev** [comment]
@juliaElastic Thanks for that! I have re-posted in `#es-core-infra` to try and get a review

**Review by rjernst — APPROVED** [review]
LGTM

**Pull request merged**
