### PR TITLE
Fix DataTiersMigrationsTests.testIndexDataTierMigration

### LINKED ISSUE #63350: [CI] DataTiersMigrationsTests.testIndexDataTierMigration fails periodically
**Build scan**:
- [7.9.3] https://gradle-enterprise.elastic.co/s/e6moxgn6emvvc
- [7.10.0] https://gradle-enterprise.elastic.co/s/ctax63vbhxdxc
- https://gradle-enterprise.elastic.co/s/zza4pg6ncbpcq

**Repro line**:
```
REPRODUCE WITH: ./gradlew ':x-pack:plugin:ilm:internalClusterTest' --tests "org.elasticsearch.xpack.ilm.DataTiersMigrationsTests.testIndexDataTierMigration" \
  -Dtests.seed=323EED72404458A3 \
  -Dtests.security.manager=true \
  -Dtests.locale=de-CH \
  -Dtests.timezone=Europe/Prague \
  -Druntime.java=11 \
  -Dtests.fips.enabled=true
```
**Reproduces locally?**: No

**Applicable branches**: master

**Failure history**:
- [7.9.3] https://gradle-enterprise.elastic.co/s/hkntbxhn4uzrq  
- [7.10.0] https://gradle-enterprise.elastic.co/s/3uwwc7j6ml3e6 
- https://gradle-enterprise.elastic.co/s/m4eits6zzubhu

**Failure excerpt**:

```
java.lang.AssertionError: 
Expected: is "check-migration"
     but: was "migrate"
	at __randomizedtesting.SeedInfo.seed([323EED72404458A3:8EBC766D3CC57784]:0)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.elasticsearch.xpack.ilm.DataTiersMigrationsTests.lambda$testIndexDataTierMigration$1(DataTiersMigrationsTests.java:141)
	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:934)
	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:907)
	at org.elasticsearch.xpack.ilm.DataTiersMigrationsTests.testIndexDataTierMigration(DataTiersMigrationsTests.java:134)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:49)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:824)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:475)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:955)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:840)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:891)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:902)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:45)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:41)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:40)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:53)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:47)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:64)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:54)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
	at java.base/java.lang.Thread.run(Thread.java:834)
	Suppressed: java.lang.AssertionError: 
Expected: is "cold"
     but: was "warm"
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
		at org.junit.Assert.assertThat(Assert.java:956)
		at org.junit.Assert.assertThat(Assert.java:923)
		at org.elasticsearch.xpack.ilm.DataTiersMigrationsTests.lambda$testIndexDataTierMigration$1(DataTiersMigrationsTests.java:140)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:922)
		... 39 more
	Suppressed: java.lang.AssertionError: 
Expected: is "cold"
     but: was "warm"
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
		at org.junit.Assert.assertThat(Assert.java:956)
		at org.junit.Assert.assertThat(Assert.java:923)
		at org.elasticsearch.xpack.ilm.DataTiersMigrationsTests.lambda$testIndexDataTierMigration$1(DataTiersMigrationsTests.java:140)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:922)
		... 39 more
	Suppressed: java.lang.AssertionError: 
Expected: is "cold"
     but: was "warm"
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
		at org.junit.Assert.assertThat(Assert.java:956)
		at org.junit.Assert.assertThat(Assert.java:923)
		at org.elasticsearch.xpack.ilm.DataTiersMigrationsTests.lambda$testIndexDataTierMigration$1(DataTiersMigrationsTests.java:140)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:922)
		... 39 more
	Suppressed: java.lang.AssertionError: 
Expected: is "cold"
     but: was "warm"
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
		at org.junit.Assert.assertThat(Assert.java:956)
		at org.junit.Assert.assertThat(Assert.java:923)
		at org.elasticsearch.xpack.ilm.DataTiersMigrationsTests.lambda$testIndexDataTierMigration$1(DataTiersMigrationsTests.java:140)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:922)
		... 39 more
	Suppressed: java.lang.AssertionError: 
Expected: is "cold"
     but: was "warm"
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
		at org.junit.Assert.assertThat(Assert.java:956)
		at org.junit.Assert.assertThat(Assert.java:923)
		at org.elasticsearch.xpack.ilm.DataTiersMigrationsTests.lambda$testIndexDataTierMigration$1(DataTiersMigrationsTests.java:140)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:922)
		... 39 more
	Suppressed: java.lang.AssertionError: 
Expected: is "cold"
     but: was "warm"
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
		at org.junit.Assert.assertThat(Assert.java:956)
		at org.junit.Assert.assertThat(Assert.java:923)
		at org.elasticsearch.xpack.ilm.DataTiersMigrationsTests.lambda$testIndexDataTierMigration$1(DataTiersMigrationsTests.java:140)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:922)
		... 39 more
	Suppressed: java.lang.AssertionError: 
Expected: is "cold"
     but: was "warm"
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
		at org.junit.Assert.assertThat(Assert.java:956)
		at org.junit.Assert.assertThat(Assert.java:923)
		at org.elasticsearch.xpack.ilm.DataTiersMigrationsTests.lambda$testIndexDataTierMigration$1(DataTiersMigrationsTests.java:140)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:922)
		... 39 more
	Suppressed: java.lang.AssertionError: 
Expected: is "cold"
     but: was "warm"
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
		at org.junit.Assert.assertThat(Assert.java:956)
		at org.junit.Assert.assertThat(Assert.java:923)
		at org.elasticsearch.xpack.ilm.DataTiersMigrationsTests.lambda$testIndexDataTierMigration$1(DataTiersMigrationsTests.java:140)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:922)
		... 39 more
	Suppressed: java.lang.AssertionError: 
Expected: is "cold"
     but: was "warm"
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
		at org.junit.Assert.assertThat(Assert.java:956)
		at org.junit.Assert.assertThat(Assert.java:923)
		at org.elasticsearch.xpack.ilm.DataTiersMigrationsTests.lambda$testIndexDataTierMigration$1(DataTiersMigrationsTests.java:140)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:922)
		... 39 more
	Suppressed: java.lang.AssertionError: 
Expected: is "cold"
     but: was "warm"
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
		at org.junit.Assert.assertThat(Assert.java:956)
		at org.junit.Assert.assertThat(Assert.java:923)
		at org.elasticsearch.xpack.ilm.DataTiersMigrationsTests.lambda$testIndexDataTierMigration$1(DataTiersMigrationsTests.java:140)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:922)
		... 39 more
	Suppressed: java.lang.AssertionError: 
Expected: is "cold"
     but: was "warm"
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
		at org.junit.Assert.assertThat(Assert.java:956)
		at org.junit.Assert.assertThat(Assert.java:923)
		at org.elasticsearch.xpack.ilm.DataTiersMigrationsTests.lambda$testIndexDataTierMigration$1(DataTiersMigrationsTests.java:140)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:922)
		... 39 more
	Suppressed: java.lang.AssertionError: 
Expected: is "cold"
     but: was "warm"
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
		at org.junit.Assert.assertThat(Assert.java:956)
		at org.junit.Assert.assertThat(Assert.java:923)
		at org.elasticsearch.xpack.ilm.DataTiersMigrationsTests.lambda$testIndexDataTierMigration$1(DataTiersMigrationsTests.java:140)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:922)
		... 39 more
	Suppressed: java.lang.AssertionError: 
Expected: is "cold"
     but: was "warm"
		at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
		at org.junit.Assert.assertThat(Assert.java:956)
		at org.junit.Assert.assertThat(Assert.java:923)
		at org.elasticsearch.xpack.ilm.DataTiersMigrationsTests.lambda$testIndexDataTierMigration$1(DataTiersMigrationsTests.java:140)
		at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:922)
		... 39 more
```

It failed only twice in a week, so I am not going to mute it for now.

### PR DESCRIPTION
**Pull request by dakrone**
This commit adds a reroute prior to checking the migration status. In some cases ILM steps can
advance quickly enough that we won't check whether we can advance due to the cluster state not being
updated (because some types of steps are only checks on new cluster states). Even with the test
setting a poll interval of 1 second, certain steps are not checked because they are waiting for a
new cluster state.

Resolves #63350

### CODE REVIEW

**Comment by dakrone** [comment]
@elasticmachine update branch

**Comment by dakrone** [comment]
@elasticmachine update branch

**Comment by andreidan** [comment]
Thanks for working on this @dakrone 

I don't think I understand this fix though. The test is failing because the `migrate` action didn't move past the `migrate` step which is not conditional, just updating a setting (didn't reach the `check-migration` step). What is `reroute` meant to do in this situation?

As the test is progressively bootstrapping nodes, would this be a case of increasing the timeout used by `assertBusy` from the 10 seconds default to 30?

**Comment by dakrone** [comment]
I think you are correct, I've updated the tests to bump to timeout to 30 seconds (similar to what they are in the other test in this file)

**Comment by andreidan** [comment]
@dakrone do you think the `reroute` api calls are needed still?

**Comment by dakrone** [comment]
@andreidan nope, I just forgot to remove them, should be fixed now!

**Review by andreidan — APPROVED** [review]
LGTM, thanks for fixing this Lee

**Pull request merged**
