### PR TITLE
[DOCS] Qualifies Watcher transforms

### PR DESCRIPTION
**Pull request by lcawl**
This PR updates the terminology used for Watcher transforms (https://www.elastic.co/guide/en/elasticsearch/reference/master/transform.html) so that it's not confused with data transforms (https://www.elastic.co/guide/en/elasticsearch/reference/master/transforms.html).

Depends on https://github.com/elastic/docs/pull/1248

Preview: http://elasticsearch_47482.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/transform.html

### CODE REVIEW

**Comment by lcawl** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Comment by lcawl** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Comment by lcawl** [comment]
@elasticmachine, run elasticsearch-ci/packaging-sample-matrix

**Review by jakelandis — APPROVED** [review]
LGTM

**Pull request merged**
