### PR TITLE
specify that this change has to be made to the host machine

### PR DESCRIPTION
**Pull request by opyate**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by jtibshirani** [comment]
@opyate thanks for your contribution. Could you explain the possible confusion that lead to this change? Where else would you run the command?

**Comment by opyate** [comment]
> @opyate thanks for your contribution. Could you explain the possible confusion that lead to this change? Where else would you run the command?

Inside the Docker container.

**Comment by jtibshirani** [comment]
Thanks for the explanation and sorry that I missed your reply. Could you please sign the CLA so I could merge the change? I understand that it might be surprising you need a CLA for such a small change, but we require it for all changes.

**Comment by opyate** [comment]
> Could you please sign the CLA so I could merge the change? I understand that it might be surprising you need a CLA for such a small change, but we require it for all changes.

Too much friction. I don't really care 😂  Closing.

**Pull request closed without merging**
