### PR TITLE
Add wolfi ess docker image

### PR DESCRIPTION
**Pull request by breskeby**
This adds a ESS variant of a wolfi image.

The image is based on the basic elasticsearch wolfi image. It contains in addition:

- tweaked entry point with `ENTRYPOINT` is `/sbin/tini`, and the `CMD` is `/app/elasticsearch.sh`
- wget included
- filebeat and metricbeat installed to /opt
- all plugins stored in an archive directory

### CODE REVIEW

**Comment by breskeby** [comment]
In the packaging tests I have seen occasionally test022InstallPluginsFromLocalArchive failing but 
1) I couldn't reproduce it manually and 
2) it seems sort of flaky for a while: https://es-delivery-stats.elastic.dev/app/dashboards#/view/dcec9e60-72ac-11ee-8f39-55975ded9e63?_g=(filters:!(),refreshInterval:(pause:!t,value:60000),time:(from:now-2w,to:now))

I plan to investigate those in some after work once this is merged but want to keep that separated to get the wolfi migration going

**Review by brianseeders — APPROVED** [review]

**Comment by mark-vieira** [comment]
Do we need both the existing ubuntu-based cloud-ess image _and_ the wolfi one? My understanding is the later should replace the former.

**Comment by breskeby** [comment]
The idea was to provide both, let the cloud team make the switch when
finished with whatever testing they need and then have the former cloud
images removed.

**Comment by breskeby** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.x|[](https://github.com/elastic/elasticsearch/pull/114111)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
