### PR TITLE
SQL: Fix issue with complex expression as args of PERCENTILE/_RANK

### PR DESCRIPTION
**Pull request by matriv**
When the arguments of PERCENTILE and PERCENTILE_RANK can be folded,
the `ConstantFolding` rule kicks in and calls the `replaceChildren()`
method on `InnerAggregate` which is created from the aggregation rules
of the `Optimizer`. `InnerAggregate` in turn, cannot implement the method
as the logic of creating a new `InnerAggregate` instance from a list of
`Expression`s resides in the Optimizer. So, instead, `ConstantFolding`
should be applied before any of the aggregations related rules.

Fixes: #37099

### CODE REVIEW

**Comment by matriv** [comment]
@costin maybe you have a better suggestion for this

**Review by costin — APPROVED** [review]
LGTM

**Review by astefan — APPROVED** [review]
LGTM

**Comment by matriv** [comment]
Backported to `6.x` with 4a1e66eac6765d65eb2a9f46e3d66d0d2f086100
to `6.6` with 0edaf2b6c1c541d61587edb1fe6fae3b50a7126d
to `6.5` with e48982c7b989e9c54936082cc90134c5c1363901

**Pull request merged**
