### PR TITLE
Make NotMasterException a first class citizen

### PR DESCRIPTION
**Pull request by bleskes**
That exception is currently serialized as its current base class IllegalStateException which confuses code supposed to deal with the stepping down of a master. This is an important exception and we should be able to serialize it correctly. This commit fixes it by moving the exception to inherit from ElasticsearchException and properly register it.

As a bonus I adapted CapturingTransport to properly simulate serialized exceptions.

See https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-os-compatibility/os=debian/751 for an example failure

### CODE REVIEW

**Comment by danielmitterdorfer** [comment]
LGTM

**Comment by jasontedor** [comment]
LGTM.

**Comment by bleskes** [comment]
@danielmitterdorfer @jasontedor thx. I pushed two minor fixes to tests.

**Comment by jasontedor** [comment]
> thx. I pushed two minor fixes to tests.

Still LGTM.

**Pull request merged**
