### PR TITLE
Field stats: Fix NPE for index constraint on empty index

### PR DESCRIPTION
**Pull request by martijnvg**
The field does exist used in the index constraint does exist in the mapping, but no document uses it or the index is empty and this causes an NPE:

```
java.lang.NullPointerException
    at org.elasticsearch.action.fieldstats.TransportFieldStatsTransportAction.newResponse(TransportFieldStatsTransportAction.java:122)
    at org.elasticsearch.action.fieldstats.TransportFieldStatsTransportAction.newResponse(TransportFieldStatsTransportAction.java:54)
    at org.elasticsearch.action.support.broadcast.TransportBroadcastAction$AsyncBroadcastAction.finishHim(TransportBroadcastAction.java:229)
    at org.elasticsearch.action.support.broadcast.TransportBroadcastAction$AsyncBroadcastAction.onOperation(TransportBroadcastAction.java:194)
    at org.elasticsearch.action.support.broadcast.TransportBroadcastAction$AsyncBroadcastAction$1.handleResponse(TransportBroadcastAction.java:174)
    at org.elasticsearch.action.support.broadcast.TransportBroadcastAction$AsyncBroadcastAction$1.handleResponse(TransportBroadcastAction.java:161)
    at org.elasticsearch.transport.TransportService$DirectResponseChannel.processResponse(TransportService.java:785)
    at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:769)
    at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:759)
    at org.elasticsearch.action.support.broadcast.TransportBroadcastAction$ShardTransportHandler.messageReceived(TransportBroadcastAction.java:268)
    at org.elasticsearch.action.support.broadcast.TransportBroadcastAction$ShardTransportHandler.messageReceived(TransportBroadcastAction.java:264)
    at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350)
    at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

### CODE REVIEW

**Comment by jpountz** [comment]
LGTM

**Comment by nik9000** [comment]
LGTM too

**Comment by martijnvg** [comment]
Pushed via: https://github.com/elastic/elasticsearch/commit/1661ce5b8c665b915e71c5488243f13176444d29

**Comment by dakrone** [comment]
@martijnvg looking at the git history for the `2.0` branch, it looks like this was *after* the `v2.0.1` tag, so it should be tagged v2.0.2?

**Comment by clintongormley** [comment]
I've updated the release notes to remove this change from 2.0.1

**Pull request closed without merging**
