### PR TITLE
Shorten field names in EstimateMemoryUsageResponse

### LINKED ISSUE #45741: Rename EstimateMemoryUsage API response's fields
Shorten response's fields names:
- Rename expected_memory_usage_with_one_partition to expected_memory_without_disk
- Rename expected_memory_usage_with_max_partitions to expected_memory_with_disk

This should be done in phases:
1. Mute tests that may be affected
2. Merge in C++ part (https://github.com/elastic/ml-cpp/pull/601)
3. Merge in Java part (https://github.com/elastic/elasticsearch/pull/45719)
4. Unmute tests

### PR DESCRIPTION
**Pull request by przemekwitek**
Changes in EstimateMemoryUsageResponse (both server and client):
* Rename expected_memory_usage_with_one_partition to expected_memory_without_disk
* Rename expected_memory_usage_with_max_partitions to expected_memory_with_disk

Relates https://github.com/elastic/elasticsearch/issues/44699
Closes https://github.com/elastic/elasticsearch/issues/45741

### CODE REVIEW

**Review by benwtrent — APPROVED** [review]

**Comment by przemekwitek** [comment]
run elasticsearch-ci/1

**Comment by przemekwitek** [comment]
run elasticsearch-ci/2

**Comment by przemekwitek** [comment]
run elasticsearch-ci/1

**Comment by przemekwitek** [comment]
run elasticsearch-ci/1

**Pull request merged**
