### PR TITLE
Fix Parsing Bug with Update By Query for Stored Scripts

### LINKED ISSUE #28002: Unable to use stored scripts in _update_by_query
**Elasticsearch version** (`bin/elasticsearch --version`): 
Version: 6.1.1, Build: bd92e7f/2017-12-17T20:23:25.338Z, JVM: 1.8.0_151

**Plugins installed**: 
["x-pack"]

**JVM version** (`java -version`):
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

**OS version** (`uname -a` if on a Unix-like system):
Darwin MacPro.local 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64

**Description of the problem including expected versus actual behavior**:

I'm unable to use stored scripts to update by query. Elasticsearch is returning `"lang cannot be specified for stored scripts` error.

**Steps to reproduce**:

 1. Create a stored script

```
POST _scripts/dummy_script
{
  "script": {
    "source": "ctx._source.my_field = 8",
    "lang": "painless"
  }
}
```

Please note that "lang" parameter is obligatory here.

 2. Index a test document:

```
PUT test/foo/1
{
  "my_field": 10,
  "user_id": 12
}
```

 3. Try to update by query:

```
POST test/_update_by_query
{
  "query": {
    "term": {
      "user_id": 12
    }
  },
  "script": {
    "id": "dummy_script"
  }
}
```

Response:

```
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "lang cannot be specified for stored scripts"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "lang cannot be specified for stored scripts"
  },
  "status": 400
}
```

**Provide logs (if relevant)**: No logs are emitted.

### PR DESCRIPTION
**Pull request by jdconrad**
This changes the parsing logic for stored scripts in update by query to match the parsing logic for scripts in general Elasticsearch.  Ultimately, this should be changed to use Script.parseScript, but for now this is a much simpler fix to get our users up and going again.

Closes #28002

### CODE REVIEW

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by jdconrad** [comment]
@rjernst Thanks for the review!  Will commit once CI is successful.

**Comment by nik9000** [comment]
Thanks for fixing this!

**Comment by tom10271** [comment]
I am sorry but I have this issue and I am using v6.2.3, so which version should I upgrade to? 6.2.3+ or actually 6.2.3 is fixed? What do those tag means? Affected versions or fixed versions?

Thanks for helping

**Comment by jasontedor** [comment]
@tom10271 The version tags are the versions that the fix will be released in. At this time, the fix has been merged to our 6.3, 6.x, and master branches so the fix will be in 6.3.0 and all subsequent releases. At this time, 6.3.0 is not released; and I am sure it will disappoint you to know that we do not provide release dates.

**Pull request merged**
