### PR TITLE
Fix docs sample to not break at next version bump

### PR DESCRIPTION
**Pull request by williamrandolph**
The feature migration sample response in the docs used the following regex to ignore changes in version number:

```
// TESTRESPONSE[s/"minimum_index_version" : "8.0.0"/"minimum_index_version" : $body.$_path/]
```

This meant that a line with `8.9.0` for minimum index version will fail to match once the version number gets bumped on `main`.

We can replace this with the `{version}` variable, which will be replaced by the current version when documents are generated.

### CODE REVIEW

**Review by rjernst — COMMENTED** [review]
Wouldn't changing to 8.0 just delay the issue, ie we need to make further changes when we bump to 9.0? IMO we should strive to avoid these kind of necessary adjustments when bumping.

**Comment by mayya-sharipova** [comment]
@williamrandolph Thanks for looking. I don't know the implication for this change.  Would changing the regex to match any version number be difficult to implement?

**Comment by williamrandolph** [comment]
I've switched to using `{version}` in the json, which will substitute in the current release version. (This doesn't work for generated previews, apparently, but it does work for tests and for docs on the website, for example in the [docs for the cluster stats api](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-stats.html).)

**Review by rjernst — APPROVED** [review]
LGTM

**Pull request merged**
