### PR TITLE
 Backport support for replicating closed indices to 7.x

### PR DESCRIPTION
**Pull request by tlrx**
This is the backport of #39499 for `7.x`.

The change on master is not merged yet but I'm creating the backport PR to let it run few cycles on CI.

### CODE REVIEW

**Comment by tlrx** [comment]
All tests passed:
- elasticsearch-ci/1 — [Details](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-1/9176/)
- elasticsearch-ci/2 — [Details](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-2/9070/)
- elasticsearch-ci/bwc — [Details](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-bwc/946/)
- elasticsearch-ci/default-distro — [Details](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+default-distro/7680/)
- elasticsearch-ci/docbldesx — [Details](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+docbldesx/8123/)
- elasticsearch-ci/oss-distro-docs — [Details](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+oss-distro-docs/12259/)
- elasticsearch-ci/packaging-sample — [Details](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+packaging-tests-sample/10495/)

@elasticmachine test this please

**Comment by tlrx** [comment]
All tests passed again:
- elasticsearch-ci/1 — [Details](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-1/9181/)
- elasticsearch-ci/2 — [Details](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-2/9076/)
- elasticsearch-ci/bwc — [Details](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-bwc/951/)
- elasticsearch-ci/default-distro — [Details](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+default-distro/7685/)
- elasticsearch-ci/docbldesx — [Details](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+docbldesx/8128/)
- elasticsearch-ci/oss-distro-docs — [Details](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+oss-distro-docs/12264/)
- elasticsearch-ci/packaging-sample — [Details](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+packaging-tests-sample/10501/)

@elasticmachine test this please

**Comment by tlrx** [comment]
One job failed with an unrelated issue (#28153):
- elasticsearch-ci/1 — [Failed](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-1/9192/) because of #28153
- elasticsearch-ci/2 — [Details](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-2/9087/)
- elasticsearch-ci/bwc — [Details](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-bwc/962/)
- elasticsearch-ci/default-distro — [Details](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+default-distro/7696/)
- elasticsearch-ci/docbldesx — [Details](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+docbldesx/8139/)
- elasticsearch-ci/oss-distro-docs — [Details](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+oss-distro-docs/12275/)
- elasticsearch-ci/packaging-sample — [Details](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+packaging-tests-sample/10512/)

@elasticmachine test this please

**Comment by tlrx** [comment]
All tests passed again:
- elasticsearch-ci/1 — [Details](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-1/9201/)
- elasticsearch-ci/2 — [Details](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-2/9096/)
- elasticsearch-ci/bwc — [Details](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-bwc/971/)
- elasticsearch-ci/default-distro — [Details](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+default-distro/7704/)
- elasticsearch-ci/docbldesx — [Details](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+docbldesx/8148/)
- elasticsearch-ci/oss-distro-docs — [Details](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+oss-distro-docs/12284/)
- elasticsearch-ci/packaging-sample — [Details](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+packaging-tests-sample/10520//)

@elasticmachine test this please

**Comment by tlrx** [comment]
One job failed:
- elasticsearch-ci/1 — [Failed](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-1/9220/)
- elasticsearch-ci/2 — [Details](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-2/9114/)
- elasticsearch-ci/bwc — [Details](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-bwc/988/)
- elasticsearch-ci/default-distro — [Details](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+default-distro/7721/)
- elasticsearch-ci/docbldesx — [Details](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+docbldesx/8168/)
- elasticsearch-ci/oss-distro-docs — [Details](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+oss-distro-docs/12304/)
- elasticsearch-ci/packaging-sample — [Details](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+packaging-tests-sample/10534/)

@elasticmachine test this please

**Comment by tlrx** [comment]
All tests passed again:
- elasticsearch-ci/1 — [Details](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-1/9248/)
- elasticsearch-ci/2 — [Details](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-2/9141/)
- elasticsearch-ci/bwc — [Details](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request-bwc/1018/)
- elasticsearch-ci/default-distro — [Details](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+default-distro/7749/)
- elasticsearch-ci/docbldesx — [Details](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+docbldesx/8198/)
- elasticsearch-ci/oss-distro-docs — [Details](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+oss-distro-docs/12333/)
- elasticsearch-ci/packaging-sample — [Details](https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+packaging-tests-sample/10559/)

**Comment by tlrx** [comment]
@ywelsch This is ready for review. This backport picks up all the same commits listed in #39499. It adds an extra commit that adapts the code for 7.1.0 (fa346c6b6ec3e446e7dc1bfbf4a1f55f66a0ca1d) and only this one needs to be reviewed.

**Comment by ywelsch** [comment]
I've left one comment about BWC here: https://github.com/elastic/elasticsearch/pull/39506#commitcomment-32540131

**Comment by tlrx** [comment]
@ywelsch I've updated the code. Thanks for spotting my error :/

**Review by ywelsch — APPROVED** [review]
LGTM

**Comment by tlrx** [comment]
Thanks @ywelsch

**Pull request merged**
