### PR TITLE
[DOCS] Remove duplicate word

### PR DESCRIPTION
**Pull request by gaoruifeng**
`require require` --> `require`

### CODE REVIEW

**Comment by jrodewig** [comment]
@gaoruifeng Thanks for the contribution. Can you sign our [CLA](https://www.elastic.co/contributor-agreement)?

We require a signed CLA before we can merge these changes. Please ensure you sign the CLA using the same email address associated with your commit. You can find that email address here:

https://github.com/elastic/elasticsearch/commit/d1e0351565d14c9e8c912ccccc65d208c88549c8.patch

**Comment by gaoruifeng** [comment]
I have just signed CLA, please check it.

**Review by jrodewig — APPROVED** [review]
LGTM. Thanks again @gaoruifeng!

**Comment by jrodewig** [comment]
@elasticmachine ok to test

**Pull request merged**
