### PR TITLE
Test: add a failed xcontent filter test that will wait for jackson upgrade

### PR DESCRIPTION
**Pull request by weizijun**
add a xcontent filter test that will failed, when random to `filterOnParser`.

The test will fixed when jackson upgrade in https://github.com/elastic/elasticsearch/pull/80160

### CODE REVIEW

**Comment by nik9000** [comment]
@elasticmachine, test this please

**Review by nik9000 — APPROVED** [review]

**Comment by nik9000** [comment]
labelbot, please wake up. I've update the labels.

**Comment by weizijun** [comment]
@elasticmachine update branch

**Comment by weizijun** [comment]
@elasticmachine update branch

**Comment by romseygeek** [comment]
@elasticmachine test this please

**Comment by romseygeek** [comment]
@elasticmachine update branch

**Comment by romseygeek** [comment]
@elasticmachine ok to test

**Comment by weizijun** [comment]
@romseygeek Thanks for the merge!

**Pull request merged**
