### PR TITLE
Use quotes in reproduce line task for vagrant failure

### PR DESCRIPTION
**Pull request by rjernst**
This commit wraps the packaging test task for reproducing a vagrant test
failure in quotes. The task names sometimes contain "#", which confuses
bash.

### CODE REVIEW

**Comment by rjernst** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by rjernst** [comment]
@elasticmachine run elasticsearch-ci/1

**Review by jasontedor — APPROVED** [review]
LGTM.

**Review by alpar-t — APPROVED** [review]
LGTM could do it fir all reproduce lines, bwc test could also have `#` in the task name.

**Comment by rjernst** [comment]
> could do it fir all reproduce lines

I will do this in followups as I clean up other areas

**Pull request merged**
