### PR TITLE
Enhance the validation for alias when creating index template or index

### PR DESCRIPTION
**Pull request by gaobinlong**
Relates to #61009， the origin PR #68807 has been reverted by #71739 because there are some failed tests such as `org.elasticsearch.client.indices.CreateIndexRequestTests.testFromXContent` and `org.elasticsearch.client.indices.PutIndexTemplateRequestTests.testFromXContent`.

This new PR resolves the test failures.

The test failures relate to the line: https://github.com/elastic/elasticsearch/blob/048ad991162316a9dba24f0e6a2145d858dd4b3d/server/src/main/java/org/elasticsearch/action/admin/indices/alias/Alias.java#L279

because `is_write_index` can be null, when parsing the alias by the new added code it will throw an IllegalArgumentException with message `Unknown token [VALUE_NULL] in alias...`.

### CODE REVIEW

**Comment by gaobinlong** [comment]
@probakowski ， can you help to take a look at this PR?

**Comment by probakowski** [comment]
thanks for working on this @gaobinlong and sorry for the delay, I'll take a look tomorrow

**Review by probakowski — APPROVED** [review]
Thank you @gaobinlong and sorry for very long delay on this one! Change looks good, I'll merge master just to be sure everything is intact and merge if build is green

**Comment by probakowski** [comment]
@elasticmachine update branch

**Comment by probakowski** [comment]
@elasticmachine test this please

**Comment by probakowski** [comment]
@elasticmachine ok to test

**Comment by probakowski** [comment]
@elasticmachine update branch

**Pull request merged**
