### PR TITLE
EQL: Add HLRC for EQL stats

### PR DESCRIPTION
**Pull request by aleksmaus**
Related to https://github.com/elastic/elasticsearch/issues/51961

@imotov let me know if we can close this issue with this addition or if we should just keep it open for the future API changes.

### CODE REVIEW

**Review by imotov — CHANGES_REQUESTED** [review]
Looks good, but I think it is missing a response serialization test. 

> @imotov let me know if we can close this issue with this addition or if we should just keep it open for the future API changes.

Yes. It should close the issue. We just need to remember to add HLRC client methods when we add new actions in the future.

**Comment by aleksmaus** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by aleksmaus** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by aleksmaus** [comment]
@elasticmachine run elasticsearch-ci/default-distro

**Comment by aleksmaus** [comment]
@elasticmachine run elasticsearch-ci/default-distro

**Comment by aleksmaus** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Review by imotov — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
