### PR TITLE
Allow aggregations using expressions to use _score

### PR DESCRIPTION
**Pull request by jdconrad**
_score was removed from use in aggregations using expressions unintentionally when script contexts were added as part of this PR (https://github.com/elastic/elasticsearch/pull/33820).  This allows _score to once again be used.

### CODE REVIEW

**Review by rjernst — APPROVED** [review]
Lgtm

**Comment by jdconrad** [comment]
@rjernst Thanks for the review.  Will commit as soon as CI passes.

**Comment by jdconrad** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by jdconrad** [comment]
@elasticmachine run elasticsearch-ci/2

**Pull request merged**
