### PR TITLE
MockLogAppender should not always use common prefix for logger names

### PR DESCRIPTION
**Pull request by kingherc**
Only for the ones starting with org.elasticsearch. The rest (e.g., loggers in plugins' tests) can go through with their original names as they are.

### CODE REVIEW

**Review by rjernst — COMMENTED** [review]
What's the purpose of this logger name manipulation? It's been around since the mock log appender was created, but I can't see where it is actually used. It's also set via a system property, so InternalClusterTests can't really set it. I'm wondering if we should just remove this manipulation altogether?

**Comment by kingherc** [comment]
Thanks @rjernst for the suggestion. I was also under the impression that it may be a relic from old times, but did not want to be too intrusive and remove it completely. However, if you agree, we can try it. I also do not see a lot of places using it. So I pushed a commit just now to remove it completely and see if it passes the CI, at which point I think we can safely remove it. I'll invite you for review once again if the CI is green.

**Review by pgomulka — APPROVED** [review]
I think it is safe to remove the use of es.logger.prefix
the use of this goes very far back up to 2016 when it was refactored to no longer use the logger name without a prefixed package
https://github.com/elastic/elasticsearch/pull/20457
https://github.com/elastic/elasticsearch/commit/7560101ec73331acb39a042bde6130e59e4bb630#diff-662b4dd0f3b36b1bdd7d6312291f585e001e0e0bedc8c3594dc52b7d4ebd4c42

**Comment by kingherc** [comment]
Ah thanks @pgomulka ! Great, I'll merge it then.

**Pull request merged**
