### PR TITLE
[docs] fix typo

### PR DESCRIPTION
**Pull request by mendab1e**
Fix [REST in the uri

### CODE REVIEW

**Comment by clintongormley** [comment]
Hi @mendab1e 

Thanks for the fix. Please could I ask you to sign the CLA so that I can merge it in.
http://www.elasticsearch.org/contributor-agreement/

**Comment by mendab1e** [comment]
Hi @clintongormley, I have signed the CLA.

**Comment by clintongormley** [comment]
thanks @mendab1e - merged

**Comment by clintongormley** [comment]
Closed by 6812ed0bb69dedc16dd3b8acb9f97b264f9b50af

**Pull request closed without merging**
