### PR TITLE
Lock-free ListenableFuture

### PR DESCRIPTION
**Pull request by thecoop**

### CODE REVIEW

**Review by DaveCTurner — COMMENTED** [review]
hehe snap (almost) https://github.com/elastic/elasticsearch/pull/93910/files#diff-785af70e26566453564f63bc37ee1b94e298138a2e3748b9c3e992242fdc32e8

In practice almost none of the usages of `ListenableFuture` need it to be a future at all, and I find its behaviour in the presence of interrupts to be fairly trappy (it will throw an `InterruptedException` even if it completed successfully) so I think we should instead work towards replacing it with the non-future `FanOutListener` in due course.

**Comment by thecoop** [comment]
Yeah, this is currently failing a test for some reason I haven't pinned down yet. I think this might be worth getting in if it shows a performance improvement over the locked version, it's a less drastic change than FanOutListener. If not, then we can go with the more involved change to replace it completely.

**Comment by DaveCTurner** [comment]
> Yeah, this is currently failing a test for some reason I haven't pinned down yet

You're completing the subscribed listeners in reverse order.

**Comment by thecoop** [comment]
Doh

**Comment by thecoop** [comment]
Looks like this doesn't offer a significant performance bump - closing for now

**Pull request closed without merging**
