### PR TITLE
Add "fingerprint" ingest processor (#53578)

### PR DESCRIPTION
**Pull request by yyff**
Implements the "fingerprint" ingest processor mentioned by issue #53578, which generates fingerprint from document fields, and is similar to [Logstash Fingerprint filter plugin](https://www.elastic.co/guide/en/logstash/master/plugins-filters-fingerprint.html).

### CODE REVIEW

**Comment by danhermann** [comment]
@yyff, thank you for your work on this ingest processor! We would like to get it merged and will review it in the next week or two. From a quick glance at the code, there are a few things that will need to change, but nothing that should be too difficult.

**Comment by yyff** [comment]
Thanks for uour reply! It’s fine if you need me to do some changes for better code, I’ll take it.

**Comment by danhermann** [comment]
@yyff, apologies for the delay on this one. We would like to merge this processor in alongside our existing Basic-licensed ingest processors that are freely usable outside of specific third-party SaaS offerings. That would entail moving the processor code to the [x-pack ingest module](https://github.com/elastic/elasticsearch/tree/master/x-pack/plugin/ingest/src/main/java/org/elasticsearch/xpack/ingest) and replacing the Apache license headers in the source files with [Elastic license headers](https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/ingest/src/main/java/org/elasticsearch/xpack/ingest/UriPartsProcessor.java#L1). If you are interested in continuing this PR, please let me know if I can help or if you have any questions about it.

**Comment by danhermann** [comment]
Closing this. Please comment here if you are interested in resuming this work and we can revisit it.

**Pull request closed without merging**
