### PR TITLE
Collapse ParametrizedFieldMapper into FieldMapper

### PR DESCRIPTION
**Pull request by romseygeek**
Now that all our FieldMapper implementations extend ParametrizedFieldMapper,
we can collapse the two classes together, and remove a load of cruft from 
FieldMapper that is unused.  In particular:

* we no longer need the lucene FieldType field on FieldMapper
* we no longer use `clone()` for merging, so we can remove it from all impls
* the serialization code in FieldMapper that assumes we're looking at text fields can go

### CODE REVIEW

**Review by nik9000 — APPROVED** [review]
LGTM. Has a couple of test changes that mean we don't need to assert of `FieldType` which is nice.

**Comment by romseygeek** [comment]
@elasticmachine run elasticsearch-ci/2

**Review by javanna — APPROVED** [review]
LGTM thanks for taking the migration to ParametrizedFieldMapper to the finish line!!!

**Comment by romseygeek** [comment]
@elasticmachine update branch

**Comment by romseygeek** [comment]
@elasticmachine update branch

**Comment by romseygeek** [comment]
@elasticmachine update branch

**Comment by romseygeek** [comment]
@elasticmachine update branch

**Pull request merged**
