### PR TITLE
Remove redundant Java check from Sys V init

### PR DESCRIPTION
**Pull request by jasontedor**
In the Sys V init scripts, we check for Java. This is not needed, since the same check happens in elasticsearch-env when starting up. Having this duplicate check has bitten us in the past, where we made a change to the logic in elasticsearch-env, but missed updating it here. Since there is no need for this duplicate check, we remove it from the Sys V init scripts.

Relates #45593

### CODE REVIEW

**Comment by jasontedor** [comment]
The issue that caused the build to fail is a known issue (`resouce_already_exists_exception`), retriggering the build.

@elasticmachine run elasticsearch-ci/1

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by jasontedor** [comment]
@elasticmachine update branch

**Comment by jasontedor** [comment]
@elasticmachine run elasticsearch-ci/1

**Pull request merged**
