### PR TITLE
[Rest Api Compatibility] _time and _term sort orders

### PR DESCRIPTION
**Pull request by pgomulka**
Previously removed in #39450, deprecated in es6 but not removed in es 7.
defaults to _key behaviour

relates #51816

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by pgomulka** [comment]
removal of _time and _term was marked as `discuss` for rest api compatibility. Hence the `team-discuss` label
@elastic/es-analytics-geo let me know if we plan to merge the rest api compatible change or backport the removal to 7.x
I would prefer to merge this PR to master and remove the support to _key and _time in master only. It would be easier for users.

**Comment by nik9000** [comment]
> I would prefer to merge this PR to master and remove the support to _key and _time in master only. It would be easier for users.

Do you mean you'd prefer to just merge this to master, no backports? In other words, this removal gets a super long deprecation cycle? That's fine with me. I don't think it's hurting anyone.

**Comment by pgomulka** [comment]
> Do you mean you'd prefer to just merge this to master, no backports? In other words, this removal gets a super long deprecation cycle? 

yes, there is a chance to make it easier for users to upgrade, so why not :) 
unless there are other reasons to remove it in 7 which I am not aware of.

**Comment by nik9000** [comment]
Yeah - I'm :+1: to do it the way you've proposed. Do we have a way of knowing when to drop support for it? I guess at some point we'll remove the constant you are comparing to and just zap all of the statements it guards.

**Review by nik9000 — APPROVED** [review]

**Comment by pgomulka** [comment]
when we bump RestApiVersion.minimumSupported to 8 (current version would be 9) then the code  https://github.com/elastic/elasticsearch/pull/74919/files#diff-ab996c9a4e31c3c2e1c2df8238d258c0217fecc258066faa02e0c7a5701255afR578 will become dead.
We will likely follow up after a version bump with a cleanup and remove all usages of RestApiVersion.V_7

**Comment by nik9000** [comment]
>  We will likely follow up after a version bump with a cleanup and remove all usages of RestApiVersion.V_7

That's awesome! I that we can remove the dead code in as many changes as we need after dropping the support.

**Pull request merged**
