### PR TITLE
RestUtils.decodeQueryString ignores the URI fragment when parsing a query string

### LINKED ISSUE #13320: RestUtils.decodeQueryString does not correctly handle fragments
For example, this is a simple unit test that fails:

```java
public void testCrazyURL() {
    Map<String, String> params = newHashMap();

    // This is a valid URL
    String uri = "example.com/:@-._~!$&'()*+,=;:@-._~!$&'()*+,=:@-._~!$&'()*+,==?/?:@-._~!$'()*+,;=/?:@-._~!$'()*+,;==#/?:@-._~!$&'()*+,;=";
    RestUtils.decodeQueryString(uri, uri.indexOf('?') + 1, params);
    assertThat(params.get("/?:@-._~!$'()* ,;"), equalTo("/?:@-._~!$'()* ,;=="));
    assertThat(params.size(), equalTo(1));
}
```

### PR DESCRIPTION
**Pull request by camilojd**
Fixes #13320

### CODE REVIEW

**Comment by camilojd** [comment]
FWIW: Just signed the CLA!

**Comment by nik9000** [comment]
Fix looks fine - I'm going to pull it locally and rerun the tests for paranoia's sake.

**Comment by nik9000** [comment]
And tests passed for me locally. I'll merge this to 2.x and master soon.

**Comment by nik9000** [comment]
Merged to master: 6876321581d2154cb4f73b15bae304bdc99f5ed8

I'm backporting to 2.x.

**Comment by nik9000** [comment]
And cherry-picked to 2.x. Thanks @camilojd!

**Comment by camilojd** [comment]
Great. Thank you @nik9000!

**Pull request closed without merging**
