### PR TITLE
Date: Add DateFormatters class that uses java.time

### PR DESCRIPTION
**Pull request by spinscale**
A newly added class called DateFormatters now contains java.time based
builders for dates, which also intends to be fully backwards compatible,
when the name based date formatters are picked.

A duelling test class has been added that ensures the same dates when
parsing java or joda time formatted dates for the name based dates.

A first user of this class is the ingest module, which now uses
java.time under the hood instead of joda time.

Note, that java.time and joda time are not fully backwards compatible,
which also means that old formats will currently not work with this
setup.

### CODE REVIEW

**Comment by spinscale** [comment]
@elasticmachine retest this please

**Comment by spinscale** [comment]
this fails on CI due to a discrepancy between java8 and java 10... java 10 works as expected, but java 8 fails, this is a test that will not work on java8 but will on java10

```
    // java 10 can parse all of these formats just using "+HH:mm"
    // java 8 can not, furthermore even optional formatters seem to break
    // requires more investigation
    // possible candidates for fixes in the openjdk source
    // https://github.com/dmlloyd/openjdk/commit/c4a9c77a0314826b49a98a991035545f768a421a
    // https://github.com/dmlloyd/openjdk/commit/dd0368122c35c6a34f322a633bf98c91b50a3c30
    public void testBrokenWithJava8ButWorksWithJava10() {
        // works
        DateTimeFormatter f1 = new DateTimeFormatterBuilder().appendOffset("+HH:mm", "Z").toFormatter(Locale.ROOT);
        f1.parse("Z");
        f1.parse("-08");
        f1.parse("+08:00");

        // works
        DateTimeFormatter f2 = new DateTimeFormatterBuilder().appendOffset("+HHmm", "Z").toFormatter(Locale.ROOT);
        f2.parse("Z");
        f2.parse("-0800");

        // fails, only the first formatter is able top parse in java8
        DateTimeFormatter f3 = new DateTimeFormatterBuilder().appendOptional(f1).appendOptional(f2).toFormatter(Locale.ROOT);
        f3.parse("Z");
        f3.parse("-08");
        f3.parse("+08:00");
        f3.parse("-0800");
    }

```

**Comment by rjernst** [comment]
@spinscale I see this PR is against the java-time branch. Can this new DateFormatters class be added to master/6.x directly? I noticed there are a lot of unrelated diffs because the branch is out of date from master.

**Comment by spinscale** [comment]
Superceded by #31856 (which is already in master)

**Pull request closed without merging**
