### PR TITLE
Clarify building from sources docs in README

### PR DESCRIPTION
**Pull request by adityasinghraghav**

### CODE REVIEW

**Comment by dakrone** [comment]
Hi, thanks for the submission!

Could I ask you to sign the [CLA](https://www.elastic.co/contributor-agreement/) so we can merge this in?

**Comment by nik9000** [comment]
I think this PR is too a funny branch. I think it should be to master?

**Comment by dakrone** [comment]
@nik9000 I can cherry pick the commit to master easily at least

**Comment by nik9000** [comment]
> @nik9000 I can cherry pick the commit to master easily at least

Yeah, that sounds like a good idea.

**Comment by dakrone** [comment]
@adityasinghraghav actually this is already fixed in the README for the master branch (it uses build/distribution), I think this is not needed since it is opened against a branch that doesn't need the change.

**Pull request closed without merging**
