### PR TITLE
fix a wrong math conclusion

### PR DESCRIPTION
**Pull request by Hearen**
more details, please refer to this question in which I enclose more details I found: https://stackoverflow.com/q/57301510/2361308

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by polyfractal** [comment]
Hmm yeah, I think this is an artifact of our testing infrastructure.  E.g. documentation snippets run against toy datasets and we check the output to make sure it is correct, has the appropriate fields, etc.

I suspect the toy dataset got changed at one point (they are used across a variety of examples, so sometimes they are tweaked to for a different example), broke the test and someone (possibly me!) just updated the aggregation values to match without considering the text.  

I'm going to kick off a Docs CI build, that'll be the fastest way to know.  But I suspect we'll need to adjust the toy dataset to make the numbers work correctly.

@elasticmachine test this please

**Comment by polyfractal** [comment]
Yep, looks like the dataset needs tweaking.  Would you be willing to do that @Hearen?

The dataset which is used by this example is located here: https://github.com/elastic/elasticsearch/blob/master/docs/build.gradle#L443-L470

You can see other examples in that file, but basically, we need to generate a dataset in some manner (algorithmically, by hand, etc) which generates the response you want.

**Comment by Hearen** [comment]
@polyfractal Yes, of course. Thanks for the timely reply, I will look into it when I can and if any help I need, I will ask for help. Have a nice day!

**Comment by polyfractal** [comment]
:heart: Thanks!

**Comment by Hearen** [comment]
@polyfractal I am having problem to `git clone https://github.com/elastic/elasticsearch.git`, so frustrating ;( tried so many times for several days. The network in the company is so aweful, I will have another try later.

**Comment by Hearen** [comment]
@polyfractal I am having problem to `git clone https://github.com/elastic/elasticsearch.git`, so frustrating ;( tried so many times for several days. The network in the company is so aweful, I will have another try later.

**Comment by polyfractal** [comment]
Hmm, not sure what's going on, haven't seen that before.  Sorry I can't be more helpful :(

No rush though, happy to wait until you get things sorted out :)

**Comment by javanna** [comment]
heya @Hearen are you now able to address the review comments you got above?

**Comment by Hearen** [comment]
> heya @Hearen are you now able to address the review comments you got above?

I gave up the issue solving promise. 

Pretty sorry to mention this, I just cannot `git clone` ES recently. I tried about tens of times using different networks, with or without VPN and different versions of git and even in others' PC. Seems it's not possible to have further tries in China recently. 

I will continue to try to contribute in one way or another.

**Comment by jrodewig** [comment]
Superseded by #50052

**Pull request closed without merging**
