### PR TITLE
HLRC - add support for source exists API

### PR DESCRIPTION
**Pull request by markharwood**
API re-uses the GetRequest object (following the precedent set by the plain “exists” api).

Relates to #27205

### CODE REVIEW

**Comment by markharwood** [comment]
jenkins test this

**Comment by markharwood** [comment]
jenkins test this

**Comment by markharwood** [comment]
jenkins test this

**Comment by markharwood** [comment]
jenkins test this

**Review by hub-cap — APPROVED** [review]
Is there anything we can add to existing docs to advertise this? The code itself looks fine.

**Comment by markharwood** [comment]
@hub-cap is this addition to the "exists" page OK? I suspect this `source exists` feature is rarely used so didn't want to create a dedicated page or go too in-depth with examples as a detour on the current `exists` page.

**Pull request merged**
