### PR TITLE
Fix the quotes in the explain message for a script score function without parameters

### PR DESCRIPTION
**Pull request by ankon**
…hout parameters

### CODE REVIEW

**Comment by clintongormley** [comment]
@brwe could you review please?

**Comment by ankon** [comment]
Anything blocking here?

**Comment by nik9000** [comment]
LGTM

**Comment by nik9000** [comment]
@ankon, could you rebase this against master? I'm sorry its so long.

**Comment by ankon** [comment]
@nik9000 sure, can do :)

**Comment by nik9000** [comment]
OK! All tests pass and I'm merged and backporting all the way to 2.x and 2.1 branches.

**Comment by nik9000** [comment]
And done! Thanks @ankon!

**Pull request merged**
