### PR TITLE
Adding tests for TimezoneRounding in 1.x

### PR DESCRIPTION
**Pull request by orenash**
1. Test using the pre_zone_adjust_large_interval option.
2. Test rounding of ambiguous timestamps in local time (after DST switch)

### CODE REVIEW

**Comment by orenash** [comment]
Those tests were written while examining issue #9491.
They all pass after the fix in #9790.

**Comment by cbuescher** [comment]
@orenash Thanks, LGTM. Will merge these along with #9790 on 1.x and 1.4 branch.

**Comment by cbuescher** [comment]
Merged commit with 1.4 (4abb3c6) and 1.x (e0c1c1c)

**Comment by javanna** [comment]
@cbuescher can you label the PR please too?

**Comment by cbuescher** [comment]
@javanna These tests are on 1.4 branch after the 1.4.4 release, also on master with 30fd70f. Set labels accordingly.

**Pull request closed without merging**
