### PR TITLE
Use version-specific documentation link in jvm.options file

### LINKED ISSUE #65808: JVM options file contains links to current docs rather than a specific version
Today the `jvm.options` file includes links to the `current` version of the docs. It'd be better if it linked to the right version, but today there doesn't seem to be a variable that exposes just the `major.minor` string needed to construct that link.

Relates https://github.com/elastic/elasticsearch/pull/61456#discussion_r475779439

This is almost certainly a non-issue today since the content you reach from these links is accurate even if you're not on the latest version. It may silently become an issue in future.

### PR DESCRIPTION
**Pull request by mark-vieira**
We use a hard-coded link to the "current" documentation on Java heap settings in our `jvm.options` file which may very well be out of date with the corresponding version of Elasticsearch the file is coming from.

Closes #65808

### CODE REVIEW

**Comment by mark-vieira** [comment]
@DaveCTurner one thing that just occurred to me after creating this PR is that we _might_ run into issues when folks upgrade, but keep their old `jvm.options` file (which I suspect is common). In that case we'll be linking to a potentially old version of the docs. There's no good way to solve both problems of linking to docs that are _too new_ and linking to docs that are _too old_ so I suspect we have to pick the worse of the two evils here. Thoughts?

**Review by DaveCTurner — COMMENTED** [review]
I figured if this didn't work (e.g. we spelled `project.minor.version` differently in the two places) then we wouldn't be able to build a distribution. But then I tried it and discovered that it didn't, it just left the mis-spelled `@project.minor.vesrion@` literally in the file. Should we be failing the build on that?

Also I think we should make `https://www.elastic.co/guide/en/elasticsearch/reference/current/jvm-options.html` be version-specific too.

**Review by breskeby — APPROVED** [review]
lgtm. would be indeed great if we could fail the build if a token is not been replaced, but as we're using ReplaceToken filter I don't see how to do that in a straight forward fashion.

**Comment by DaveCTurner** [comment]
Acked, ok we'll take the risk of typos here then.

I still think we should fix the link to `ivm-options.html` too tho.

**Pull request merged**
