### PR TITLE
[ML] fix test check as randomness allows for different hours

### LINKED ISSUE #40537: org.elasticsearch.xpack.dataframe.integration.DataFramePivotRestIT.testPivotWithMaxOnDateField fails
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+multijob-darwin-compatibility/313/consoleFull

Reproduce line:
```
./gradlew :x-pack:plugin:data-frame:qa:single-node-tests:integTestRunner -Dtests.seed=33CD822722A48729 -Dtests.class=org.elasticsearch.xpack.dataframe.integration.DataFramePivotRestIT -Dtests.method="testPivotWithMaxOnDateField" -Dtests.security.manager=true -Dtests.locale=vi-VN -Dtests.timezone=America/Merida -Dcompiler.java=12 -Druntime.java=8
```

Looks like this random seed causes the max hour to be `19` and not the expected `20`

```
FAILURE 1.84s | DataFramePivotRestIT.testPivotWithMaxOnDateField <<< FAILURES!
   > Throwable #1: java.lang.AssertionError: 
   > Expected: a string containing "2017-01-15T20:"
   >      but: was "2017-01-15T19:59:54.000Z"
```

### PR DESCRIPTION
**Pull request by benwtrent**
Fixes test as failures are possible due to different random seeds. 

closes #40537

### CODE REVIEW

**Review by davidkyle — APPROVED** [review]
LGTM

**Comment by davidkyle** [comment]
run elasticsearch-ci/2

**Comment by benwtrent** [comment]
run elasticsearch-ci/1 
run elasticsearch-ci/2
run elasticsearch-ci/packaging-sample

**Review by hendrikmuhs — APPROVED** [review]
LGTM

**Comment by benwtrent** [comment]
run elasticsearch-ci/bwc

**Pull request merged**
