### PR TITLE
Add soft-deletes upgrade tests

### PR DESCRIPTION
**Pull request by dnhatn**
This change adds rolling-upgrade and full-cluster-restart tests with soft-deletes enabled. 

Note that these tests are currently broken because we [do not allow](https://github.com/apache/lucene-solr/blob/master/lucene/backward-codecs/src/java/org/apache/lucene/codecs/lucene70/Lucene70Codec.java#L69) update DocValues of old segments (see https://issues.apache.org/jira/browse/LUCENE-8461). I think we need to remove this restriction.

### CODE REVIEW

**Comment by dnhatn** [comment]
Below is the stack trace of the full cluster restart test.

```
|    [2018-12-06T00:26:32,420][WARN ][o.e.c.r.a.AllocationService] [node-1] failing shard [failed shard, shard [testsoftdeletes][0], node[RgRgfC1OQeCSThD4uugJwg], [P], recovery_source[existing store recovery; bootstrap_history_uuid=false], s[INITIALIZING], a[id=zZzX_JD4SmSW8qUgd2Beqg], unassigned_info[[reason=ALLOCATION_FAILED], at[2018-12-05T23:26:32.330Z], failed_attempts[4], delayed=false, details[failed shard on node [7XyQZMeFSYmCqmCUl62NBQ]: shard failure, reason [lucene commit failed], failure IllegalStateException[This codec should only be used for reading, not writing]], allocation_status[fetching_shard_data]], message [shard failure, reason [lucene commit failed]], failure [IllegalStateException[This codec should only be used for reading, not writing]], markAsStale [true]]
|    java.lang.IllegalStateException: This codec should only be used for reading, not writing
|       at org.apache.lucene.codecs.lucene70.Lucene70Codec$2.getDocValuesFormatForField(Lucene70Codec.java:69) ~[lucene-backward-codecs-8.0.0-snapshot-c78429a554.jar:8.0.0-snapshot-c78429a554 c78429a554d28611dacd90c388e6c34039b228d1 - romseygeek - 2018-12-04 10:17:44]
|       at org.apache.lucene.codecs.perfield.PerFieldDocValuesFormat$FieldsWriter.getInstance(PerFieldDocValuesFormat.java:168) ~[lucene-core-8.0.0-snapshot-c78429a554.jar:8.0.0-snapshot-c78429a554 c78429a554d28611dacd90c388e6c34039b228d1 - romseygeek - 2018-12-04 10:17:44]
|       at org.apache.lucene.codecs.perfield.PerFieldDocValuesFormat$FieldsWriter.addNumericField(PerFieldDocValuesFormat.java:109) ~[lucene-core-8.0.0-snapshot-c78429a554.jar:8.0.0-snapshot-c78429a554 c78429a554d28611dacd90c388e6c34039b228d1 - romseygeek - 2018-12-04 10:17:44]
|       at org.apache.lucene.index.ReadersAndUpdates.handleDVUpdates(ReadersAndUpdates.java:368) ~[lucene-core-8.0.0-snapshot-c78429a554.jar:8.0.0-snapshot-c78429a554 c78429a554d28611dacd90c388e6c34039b228d1 - romseygeek - 2018-12-04 10:17:44]
|       at org.apache.lucene.index.ReadersAndUpdates.writeFieldUpdates(ReadersAndUpdates.java:570) ~[lucene-core-8.0.0-snapshot-c78429a554.jar:8.0.0-snapshot-c78429a554 c78429a554d28611dacd90c388e6c34039b228d1 - romseygeek - 2018-12-04 10:17:44]
|       at org.apache.lucene.index.ReaderPool.commit(ReaderPool.java:325) ~[lucene-core-8.0.0-snapshot-c78429a554.jar:8.0.0-snapshot-c78429a554 c78429a554d28611dacd90c388e6c34039b228d1 - romseygeek - 2018-12-04 10:17:44]
|       at org.apache.lucene.index.IndexWriter.writeReaderPool(IndexWriter.java:3328) ~[lucene-core-8.0.0-snapshot-c78429a554.jar:8.0.0-snapshot-c78429a554 c78429a554d28611dacd90c388e6c34039b228d1 - romseygeek - 2018-12-04 10:17:44]
|       at org.apache.lucene.index.IndexWriter.prepareCommitInternal(IndexWriter.java:3239) ~[lucene-core-8.0.0-snapshot-c78429a554.jar:8.0.0-snapshot-c78429a554 c78429a554d28611dacd90c388e6c34039b228d1 - romseygeek - 2018-12-04 10:17:44]
|       at org.apache.lucene.index.IndexWriter.commitInternal(IndexWriter.java:3466) ~[lucene-core-8.0.0-snapshot-c78429a554.jar:8.0.0-snapshot-c78429a554 c78429a554d28611dacd90c388e6c34039b228d1 - romseygeek - 2018-12-04 10:17:44]
|       at org.apache.lucene.index.IndexWriter.commit(IndexWriter.java:3431) ~[lucene-core-8.0.0-snapshot-c78429a554.jar:8.0.0-snapshot-c78429a554 c78429a554d28611dacd90c388e6c34039b228d1 - romseygeek - 2018-12-04 10:17:44]
|       at org.elasticsearch.index.engine.InternalEngine.commitIndexWriter(InternalEngine.java:2324) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
|       at org.elasticsearch.index.engine.InternalEngine.recoverFromTranslogInternal(InternalEngine.java:451) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
|       at org.elasticsearch.index.engine.InternalEngine.recoverFromTranslog(InternalEngine.java:411) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
|       at org.elasticsearch.index.engine.InternalEngine.recoverFromTranslog(InternalEngine.java:109) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
|       at org.elasticsearch.index.shard.IndexShard.openEngineAndRecoverFromTranslog(IndexShard.java:1348) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
|       at org.elasticsearch.index.shard.StoreRecovery.internalRecoverFromStore(StoreRecovery.java:424) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
|       at org.elasticsearch.index.shard.StoreRecovery.lambda$recoverFromStore$0(StoreRecovery.java:95) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
|       at org.elasticsearch.index.shard.StoreRecovery.executeRecovery(StoreRecovery.java:302) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
|       at org.elasticsearch.index.shard.StoreRecovery.recoverFromStore(StoreRecovery.java:93) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
|       at org.elasticsearch.index.shard.IndexShard.recoverFromStore(IndexShard.java:1622) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
|       at org.elasticsearch.index.shard.IndexShard.lambda$startRecovery$6(IndexShard.java:2115) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
|       at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:660) ~[elasticsearch-7.0.0-SNAPSHOT.jar:7.0.0-SNAPSHOT]
|       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
|       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
|       at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by s1monw** [comment]
test LGTM - we need to fix this in lucene updateable DV need this behavior too. @jpountz any objections?

**Comment by jpountz** [comment]
Agreed, this needs fixing (Simon and I just had a discussion, I was surprised that this fails in spite of the fact that we have tests that dv updates work on old indices, but we only seem to test pre-existing fields).

**Comment by s1monw** [comment]
@dnhatn I fixed the issue in lucene. Can you add a new snapshot build?

**Review by s1monw — APPROVED** [review]
LGTM once the test passes

**Comment by dnhatn** [comment]
Thanks @s1monw and @jpountz.

**Pull request merged**
