### PR TITLE
XContentFactory.xContentType: allow for possible UTF-8 BOM for JSON XContentType

### LINKED ISSUE #14442: Elasticsearch _bulk endpoint fails if data contains UTF-8 Byte Order Mark
This looks like a regression because it worked on 1.x

perl -e 'print "\xEF\xBB\xBF"' > test.dat
echo '{ "index" : { "_index" : "test", "_type" : "type1", "_id" : "1" } }' >> test.dat
echo '{ "field1" : "value1" }' >> test.dat

hexdump -C test.dat 

```
00000000  ef bb bf 7b 20 22 69 6e  64 65 78 22 20 3a 20 7b  |...{ "index" : {|
00000010  20 22 5f 69 6e 64 65 78  22 20 3a 20 22 74 65 73  | "_index" : "tes|
00000020  74 22 2c 20 22 5f 74 79  70 65 22 20 3a 20 22 74  |t", "_type" : "t|
00000030  79 70 65 31 22 2c 20 22  5f 69 64 22 20 3a 20 22  |ype1", "_id" : "|
00000040  31 22 20 7d 20 7d 0a 7b  20 22 66 69 65 6c 64 31  |1" } }.{ "field1|
00000050  22 20 3a 20 22 76 61 6c  75 65 31 22 20 7d 0a     |" : "value1" }.|
0000005f
```

Elasticsearch 2.0.0

```
[2015-11-02 17:20:49,328][INFO ][node                     ] [Earthquake] version[2.0.0], pid[77392], build[de54438/2015-10-22T08:09:48Z]
```
curl -XPOST '0:9200/_bulk' --data-binary @test.dat

fails with 

```
{"error":{"root_cause":[{"type":"parse_exception","reason":"Failed to derive xcontent"}],"type":"parse_exception","reason":"Failed to derive xcontent"},"status":400}
```

Server log

```
[2015-11-02 17:21:58,254][INFO ][rest.suppressed          ] /_bulk Params: {}
ElasticsearchParseException[Failed to derive xcontent]
	at org.elasticsearch.common.xcontent.XContentFactory.xContent(XContentFactory.java:293)
	at org.elasticsearch.action.bulk.BulkRequest.add(BulkRequest.java:251)
	at org.elasticsearch.rest.action.bulk.RestBulkAction.handleRequest(RestBulkAction.java:88)
	at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:54)
	at org.elasticsearch.rest.RestController.executeHandler(RestController.java:207)
	at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:166)
	at org.elasticsearch.http.HttpServer.internalDispatchRequest(HttpServer.java:128)
	at org.elasticsearch.http.HttpServer$Dispatcher.dispatchRequest(HttpServer.java:86)
	at org.elasticsearch.http.netty.NettyHttpServerTransport.dispatchRequest(NettyHttpServerTransport.java:348)
	at org.elasticsearch.http.netty.HttpRequestHandler.messageReceived(HttpRequestHandler.java:63)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.http.netty.pipelining.HttpPipeliningHandler.messageReceived(HttpPipeliningHandler.java:60)
	at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:75)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

### PR DESCRIPTION
**Pull request by camilojd**
Fixes #14442.

### CODE REVIEW

**Comment by jpountz** [comment]
This looks good to me. I will leave this PR open for some time to give a chance to other people to chime in, but if there are no objections I will merge this soon.

**Comment by danielmitterdorfer** [comment]
Thanks @camilojd for the PR. It looks good to me too. I'll take care of merging and backporting.

**Comment by danielmitterdorfer** [comment]
Merged to master, 2.x and 2.1

**Comment by jpountz** [comment]
Should it go to 2.0.1 as well?

**Comment by bleskes** [comment]
+1 on 2.0.1 . This can be very tricky to debug if you don't know what's going on (running hexdump is always an indication of fun).

**Comment by danielmitterdorfer** [comment]
@jpountz, @bleskes: Sure, no objections. I was just under the impression that we backport by default only to the 2.1 branch. I'll merge the change to 2.0.1 now.

**Comment by jpountz** [comment]
@danielmitterdorfer This impression is right: we tend to not backport to bugfix branches unless:
 - the bug can't be worked around easily
 - the fix is low-risk

This change seemed eligible to me, hence my proposal, but in general it's good practice to be very careful about backporting changes to bugfix releases: these are releases that users should be able to run almost blindly, so we can't take any risks to introduce new bugs to these branches.

**Comment by danielmitterdorfer** [comment]
@jpountz Thanks for the clarification. I'll keep that in mind.

**Pull request closed without merging**
