### PR TITLE
Update has-parent-query.asciidoc

### PR DESCRIPTION
**Pull request by russcam**
Change reference to `score_mode`, to `score`

### CODE REVIEW

**Comment by russcam** [comment]
I think this change should also be captured in https://www.elastic.co/guide/en/elasticsearch/reference/master/breaking_50_search_changes.html#_changes_to_queries

**Comment by clintongormley** [comment]
> I think this change should also be captured in https://www.elastic.co/guide/en/elasticsearch/reference/master/breaking_50_search_changes.html#_changes_to_queries

Fixed in https://github.com/elastic/elasticsearch/commit/c02450484203a0363461d72ff36512a0134ff8f1

**Comment by russcam** [comment]
To confirm, is `score_mode` _deprecated_ or _removed_?

**Comment by clintongormley** [comment]
deprecated

**Pull request merged**
