### PR TITLE
Add Pause/Resume Auto-Follower APIs to High Level REST Client

### PR DESCRIPTION
**Pull request by tlrx**
This pull request adds support for Pause/Resume Auto-Follower APIs to the HLRC, with the documentation.

Relates #47510

### CODE REVIEW

**Comment by tlrx** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample

**Review by martijnvg — APPROVED** [review]
LGTM

**Comment by tlrx** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample

**Comment by tlrx** [comment]
Thanks @martijnvg

**Pull request merged**
