### PR TITLE
Update configuration.asciidoc

### PR DESCRIPTION
**Pull request by ScsUndefined**
It seems that there are some lines has been placed the wrong place.

### CODE REVIEW

**Comment by ScsUndefined** [comment]
It seems that there are some lines has been placed the wrong place.

**Comment by ScsUndefined** [comment]
It seems that there are some lines has been placed the wrong place.

**Comment by clintongormley** [comment]
Hi @ScsUndefined 

Thanks for the PR.  Please could I ask you to sign the CLA so that I can merge it in?
http://www.elasticsearch.org/contributor-agreement/

Note: the email address you use to sign the CLA must also be present on your github account

**Comment by ScsUndefined** [comment]
all right . wait a moment.

**Comment by ScsUndefined** [comment]
I have signed.

**Comment by clintongormley** [comment]
thanks @ScsUndefined - merged

**Pull request merged**
