### PR TITLE
Add troubleshooting

### PR DESCRIPTION
**Pull request by stefnestor**
👋🏼 consolidating learnings from some recent user experiences  🙏🏼
- @jrodewig, can you help fix links & bullet formatting?
- @mayya-sharipova has been super helpful pinpointing troubleshooting areas, so linking them to review as well

### CODE REVIEW

**Comment by jrodewig** [comment]
@debadair You mind taking a look and shepherding this through merge/backport? 🐑  Thank you!

**Review by mayya-sharipova — CHANGES_REQUESTED** [review]
@stefnestor Thanks for your contribution, but I think we don't need a separate section for ILM forcemerge troubleshooting.  First of all, we should not have issues with forcemerge,  and if there are bugs as in https://github.com/elastic/elasticsearch/pull/69416, we should address and resolve them, as we did,  and there is not need to report them in the documentation. 

It would be nice to have a general section for troubleshooting for elasticsearch.  May be, we can move the suggestions that you outlined to that section, as they are very general and not related specifically to ILM or even force_merge  (e.g. task manager, cat thread pool).  But I don't know if we have or plan to have this "troubleshooting elasticsearch" section, may be @debadair  or @jrodewig  can clarify here. 

Another idea is to add your suggestions into internal troubleshooting guides for elasticsearch and support engineers. I think your suggestions would be very helpful there.

**Comment by mayya-sharipova** [comment]
I wonder if @ @elastic/es-data-management  team can comment as well on this PR.

**Comment by debadair** [comment]
This seems like a good candidate to add to our more general troubleshooting information in https://www.elastic.co/guide/en/elasticsearch/reference/current/fix-common-cluster-issues.html instead. While the particular context that triggered issue was ILM, the recommended actions are more broadly applicable. I'd add the entry there and then reference it from the ILM docs.

**Comment by stefnestor** [comment]
Thanks, Deb! Closing here in favor of the new location ❤️

**Pull request closed without merging**
