### PR TITLE
[ML] Fix and re-enable MlHiddenIndicesFullClusterRestartIT

### PR DESCRIPTION
**Pull request by przemekwitek**
This PR removes the assertion (in `MlConfigIndexMappingsFullClusterRestartIT` test) that verifies that `.ml-config` index does not exist before creating the first ML job.
Since the full cluster restart tests can run in parallel, we cannot make an assumption that this is the case as another test (`MlHiddenIndicesFullClusterRestartIT`) could have already triggered `.ml-config` index creation.
This, as well as fixing annotations index name lets us re-enable `MlHiddenIndicesFullClusterRestartIT` test.

Fixes https://github.com/elastic/elasticsearch/issues/78913

### CODE REVIEW

**Comment by przemekwitek** [comment]
run elasticsearch-ci/part-2 
run elasticsearch-ci/bwc

**Comment by przemekwitek** [comment]
run elasticsearch-ci/bwc

**Comment by przemekwitek** [comment]
run elasticsearch-ci/bwc

**Comment by przemekwitek** [comment]
run elasticsearch-ci/bwc

**Review by dimitris-athanasiou — APPROVED** [review]
LGTM

**Pull request merged**
