### PR TITLE
Universal Profiling: Change profiling-events timestamp mapping

### PR DESCRIPTION
**Pull request by christos68k**
### Summary

Switch `profiling-events/@timestamp` to `date_nanos` for nanosecond resolution. Note that this change is also backwards compatible on ingestion, since clients can continue to pass values in seconds-since-the-epoch.

Don't merge this until the implications for dependents-consumers (e.g. Kibana) are clear.

**NOTE:** This has been postponed until `8.11`, do NOT merge yet!

### CODE REVIEW

**Comment by danielmitterdorfer** [comment]
@elasticsearchmachine merge upstream

**Review by danielmitterdorfer — APPROVED** [review]
LGTM, thanks!

**Comment by cauemarcondes** [comment]
AFAIC we'll need to change kibana to accept in two ways:

1. Update queries to support both formats when filtering by the range from /range to
2. Update date_histogram aggregations adding the new date format: `format": "strict_date_optional_time_nanos||epoch_second"`

**Comment by cauemarcondes** [comment]
I feel like this can be already merged, right @christos68k ? Since both formats will be accepted Kibana should not break.

**Comment by christos68k** [comment]
> I feel like this can be already merged, right @christos68k ? Since both formats will be accepted Kibana should not break.

Both formats are accepted for ingestion, but I think it'll require changes in Kibana as the format that the ES plugin returns data as, will also change. Quoting from the ENG thread:

**Consumption**

Daniel verified that no changes are needed in the ES plugin. However, that still leaves Kibana as something that could be affected. To give a concrete example, existing search queries in profiling-events-all return seconds-since-the-epoch:

```
GET /profiling-events-all/_search
{
  "sort": { "@timestamp": "asc"},
  "query": {"match_all": {}},
  "docvalue_fields": [{"field": "@timestamp"}]
}

=> 

{
  "_index": ".ds-profiling-events-all-2023.07.19-000001",
  "_id": "t9zkbYkBvWIS7GRIkHeU",
  "_score": null,
  "fields": {
    "@timestamp": [
      "1689765799"
    ]
  },
  "sort": [1689765799000]
}

```

With the proposed mapping change, timestamps will be returned as full ISO date-time strings: "2023-07-25T14:57:23.241285059Z" or, if an epoch_second format is provided for the timestamp field in the query, shorter epoch-seconds-with-nanosecond floating point strings: "1690297043.241285059"

**Comment by cauemarcondes** [comment]
@christos68k, would you have a cluster with the old and new data so I can test how kibana will behave?

**Comment by rockdaboot** [comment]
Did anyone made a benchmark yet to see how the mapping change affects storage costs and query latency? We can guess that it is marginal, but knowing would be better.

**Comment by christos68k** [comment]
> Did anyone made a benchmark yet to see how the mapping change affects storage costs and query latency? We can guess that it is marginal, but knowing would be better.

There is no additional storage needed as all dates are stored as Java `long` (8byte) values. I did some simple latency tests with an entry-level cluster when I first proposed this, and I didn't see any differences. There is no additional processing in Kibana.

**Review by rockdaboot — APPROVED** [review]

**Comment by rockdaboot** [comment]
> > Did anyone made a benchmark yet to see how the mapping change affects storage costs and query latency? We can guess that it is marginal, but knowing would be better.
> 
> There is no additional storage needed as all dates are stored as Java `long` (8byte) values. I did some simple latency tests with an entry-level cluster when I first proposed this, and I didn't see any differences.

The compression ratio will change when more somewhat random bits are set in the dates.
The benchmark data currently doesn't reflect that (needs to be changed to use nanoseconds set to != 0).
But we have to live with that anyway, so it's more of an academic question that we don't have to answer now.

**Pull request merged**
