### PR TITLE
Reduce GeoDistance Insanity

### PR DESCRIPTION
**Pull request by nknize**
GeoDistance query, sort, and scripts make use of a crazy GeoDistance enum for handling 4 different ways of computing geo distance: `SLOPPY_ARC`, `ARC`, `FACTOR`, and `PLANE`. Only two of these are useful: `ARC`, `PLANE`. This PR acomplishes the following:
- remove `SLOPPY_ARC`, and `FACTOR`. 
- remove overkill `FixedSourceDistance` helper classes for comuputing Geo distance
- Refactor and deprecate legacy GeoDistance query classes and helpers

### CODE REVIEW

**Comment by jpountz** [comment]
Maybe we could go further, only keep arc, and remove the `distance_type` option in the DSL?

**Comment by jpountz** [comment]
The reasoning is that going forward, LatLonPoint does the distance computation by itself so we should just have a singe implementation that is consistent with how LatLonPoint computes distances so that results of a geo distance range aggregation would be consistent with what a Geo distance range query on LatLonPoint would match?

**Comment by nknize** [comment]
@jpountz +1

That's a good idea. I'll update the PR with the change.

**Comment by clintongormley** [comment]
@nknize a reminder about this one

**Comment by nknize** [comment]
I've updated this PR since first opening it forever ago. Its ready for an updated review. I went ahead and opened a separate issue (#22914) for removing `distance_type` per @jpountz suggestion. Its easier for me to track that change in a separate PR to avoid this change from getting any more harrier than it already is. /cc @clintongormley

**Comment by clintongormley** [comment]
thanks @nknize - In 5.3 we should still accept `sloppy_arc` (translated internally to `arc`) and add deprecation logging.  From 6.0 we can refuse to accept `sloppy_arc`.

**Review by jpountz — APPROVED** [review]
The change looks good to me for master. Like @clintongormley already said, particular care needs to be taken when backporting since we still want to accept `sloppy_arc` on 5.x and parse it as `arc`.

**Comment by clintongormley** [comment]
@nknize please add a note to the 6.0 migration docs about this breaking change

**Pull request merged**
