### PR TITLE
Support rewriteAndFetch on the shard in `DfsQueryPhase`

### PR DESCRIPTION
**Pull request by benwtrent**
The following phases already support `rewriteAndFetch` on the shard:
 - The `DfsPhase` for gathering term statistics
 - QueryThenFetch phase

It seems like an oversight, and honestly prevents more complex rescorers (like the inference_rescorer) from working in the DFSQuery phase.

This commit adds rewriteAndFetch for the `DfsQuery` phase to bring it into parity with the other document shard query phases.

### CODE REVIEW

**Comment by jdconrad** [comment]
@benwtrent So my understanding is this will cover the query phase for `dfs_query_and_fetch` to fetch any necessary models for re-scoring. But I remember you mentioning that we required something for rewriting with re-scoring in the actual dfs phase as well. Was there any update required to the dfs phase to ensure that works correctly?

**Comment by benwtrent** [comment]
@jdconrad the rewriteAndFetch for the DFS phase was done already

**Comment by benwtrent** [comment]
@jdconrad the rewriteAndFetch for the DFS phase was done already

**Comment by benwtrent** [comment]
@jdconrad the rewriteAndFetch for the DFS phase was done already

**Comment by jdconrad** [comment]
Ah, yes. :facepalm: on my part. Apologies for the noise.

**Review by javanna — COMMENTED** [review]
The approach looks sensible to me. Would it be possible to add an artificial test for this that does not depend on ML functionality? I see some existing tests in SearchServiceTests, maybe we could verify there that this additional rewrite is executed etc.?

**Review by javanna — APPROVED** [review]
LGTM thanks for adding that test!

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Pull request merged**
