### PR TITLE
Enable TRACE Logging for test and increase timeout (#88477)

### PR DESCRIPTION
**Pull request by pxsalehi**
Cherry-pick https://github.com/elastic/elasticsearch/pull/88477
Relates https://github.com/elastic/elasticsearch/issues/87952

### CODE REVIEW

**Review by kingherc — APPROVED** [review]
LGTM as long as CI passes. Indeed, a straightforward cherry-pick.

**Comment by pxsalehi** [comment]
@elasticmachine test this
(Seems like an unrelated Linux Packaging issue)

**Comment by pxsalehi** [comment]
@elasticmachine run elasticsearch-ci/bwc
@elasticmachine run elasticsearch-ci/part-2

(Seems like an unrelated Linux Packaging issue)

**Comment by pxsalehi** [comment]
Thanks Iraklis!

**Comment by pxsalehi** [comment]
@elasticmachine update branch

**Comment by pxsalehi** [comment]
Since 8.3 is not needed here too, I'll close this and open a PR just for 7.17.

**Pull request closed without merging**
