### PR TITLE
Clearer error message - installing windows service

### PR DESCRIPTION
**Pull request by nogginbox**
The error message reports it can not find a file in a directory it was not looking for it in.

I've updated the message so it makes it clearer what JAVA_HOME is set to and which directories it tried to find jvm.dll in.

I spent more time than I should have done trying alternate values for JAVA_HOME to try and fix this error, so this error message should save others from this fate. Turns out I got this error because I had installed the client version of Java and not the SE version, and this puts jvm.dll in a different folder inside JAVA_HOME.

### CODE REVIEW

**Comment by NogginBox** [comment]
This is only a small change to wording, but I've signed the contributor's agreement as requested.

**Comment by javanna** [comment]
test this please

**Comment by jasontedor** [comment]
I think that we will need manual testing here too since our PR CI does not currently cover Windows.

**Comment by NogginBox** [comment]
I manually tested this to make sure it printed the error as I expected it to.

The easiest way to test (if you have the correct version of java installed) is to change the value of JAVA_HOME to something wrong and then run.

**Comment by danielmitterdorfer** [comment]
Thanks for the PR. I have tested now several scenarios on different Java versions (Java 8 and Java 10 with Elasticsearch 6.5.2) on Windows Server 2012R2. If `%JAVA_HOME%` points to an invalid directory I get:

> could not find java; set JAVA_HOME or ensure java is in PATH

If I remove / rename `jvm.dll` (in the respective directory), I get a clear error message what's wrong:

> Error: missing `server' JVM at `C:\Program Files\Java\jdk-10.0.1\bin\server\jvm.dll'.
> Please install or use the JRE or JDK that contains these missing components.

(which is raised by the JVM itself when Elasticsearch attempts to invoke `java`)

So I wonder whether this change is actually needed.

**Comment by NogginBox** [comment]
It's a while ago now, but I think the reason I got the message was I had two editions of java installed and JAVA_HOME was pointing at the wrong one. Seeing the path in the error, would have helped me spot this. I would have found this helpful, but perhaps others would not. I like a detailed error message.

**Comment by danielmitterdorfer** [comment]
@elasticmachine test this please

**Comment by danielmitterdorfer** [comment]
@elasticmachine test this please

**Comment by danielmitterdorfer** [comment]
Just fyi: I have merged the latest master on your behalf to ensure all required PR checks can run successfully. No need to do anything on your end.

**Comment by danielmitterdorfer** [comment]
Thanks for your PR. I've merged it now and it will be released in Elasticsearch 7.1.0.

**Comment by danielmitterdorfer** [comment]
Backported to `7.x` in https://github.com/elastic/elasticsearch/pull/39652

**Pull request merged**
