### PR TITLE
Update scroll.asciidoc - clarifying that the `_scroll_id` doesn't always change between `scroll` requests

### PR DESCRIPTION
**Pull request by TimHeckel**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by ywelsch** [comment]
@TimHeckel thanks for the PR. Could you sign our CLA? Once you do, I will be happy to merge your changes.

**Comment by TimHeckel** [comment]
@ywelsch  - i've signed the CLA :) thanks

**Comment by ywelsch** [comment]
@TimHeckel I can find your Github account in our CLA Checker, but it's using a different e-mail than the one you used for the commit (the CLA checker has your `@gmail.com` account while the commit has the `@*box.com` account). Can you add the gmail address to your Github account as well? /cc: @karmi

**Comment by gregolsen** [comment]
@TimHeckel @ywelsch I'm trying to understand under what circumstances scroll id is changed while "scrolling" over the result set. I'm looking through the source code and trying to find a place where it is changed and cannot find any.
There's a `buildScrollId` method in `TransportSearchHelper` that builds a scroll id by serialising query type and node IDs with corresponding file pointers into a Base64-encoded string.
https://github.com/elastic/elasticsearch/blob/99f88f15c5febbca2d13b5b5fda27b844153bf1a/server/src/main/java/org/elasticsearch/action/search/TransportSearchHelper.java#L39

This method is invoked in one single place in `innerRun` of `FetchSearchPhase`:
https://github.com/elastic/elasticsearch/blob/794de63232fb48c8ea29cb662eea153a934301ee/server/src/main/java/org/elasticsearch/action/search/FetchSearchPhase.java#L100

In `sendResponse` of `SearchScrollAsyncAction` `SearchResponse` is instantiated with a scroll id sent in the request, comment explicitly says that scroll id never changes:
https://github.com/elastic/elasticsearch/blob/f1a94de9e76a3efeade252636719e8833aede78f/server/src/main/java/org/elasticsearch/action/search/SearchScrollAsyncAction.java#L245-L252

It seems like scroll id indeed never changes in the context of a given multi-request scrolling operation.

In contrast, when looking at 2.4.6 branch code for `SearchScrollAsyncAction`, scroll id is regenerated after each scroll request.
https://github.com/elastic/elasticsearch/blob/b4f990605052f2f95b40d3b8c7b294122a1ebceb/core/src/main/java/org/elasticsearch/action/search/SearchScrollScanAsyncAction.java#L205-L212

Based on the above I think that in the earlier versions of ES scroll id was regenerated after each request, however in newest version (I checked both master and v6.3.2) scroll id is generated only once and preserved throughout subsequent scroll requests.

Please let me know what am I missing here, thank you!

**Comment by ywelsch** [comment]
@gregolsen Thanks for your analysis. While the scroll id might not be changing, I feel that this is an implementation detail and should not be relied upon. This will give us more options as ES developers to make changes to the underlying implementation of the scroll API. /cc: @elastic/es-search-aggs in case they feel differently

@elasticmachine test this please

**Comment by jimczi** [comment]
I agree with @ywelsch. From an API perspective each response contains the scroll id to use for the next request, that's the contract. The fact that it doesn't change in the current version is an implementation detail that could change in the future so I don't think we should modify the docs.

**Comment by jimczi** [comment]
I am closing this pr because we agreed that this information should not be exposed in the docs. Thanks for your investigations @gregolsen and happy upgrade to 6x !

**Comment by jimczi** [comment]
Discussed with @ywelsch which feels that the new wording makes it more clear that you should not rely on scroll id being stable. Hence I am reopening.

**Comment by javanna** [comment]
retest this please

**Comment by javanna** [comment]
thanks @TimHeckel !

**Pull request merged**
