### PR TITLE
[ML] Use token strings rather than IDs in text expansion

### PR DESCRIPTION
**Pull request by davidkyle**
Results from the text expansion model now use the token string from the input vocabulary rather than the Id.
Additionally token weight pairs are now sorted by weight and returned in a single document rather than an array of docs. This format is more commonly used for rank features fields.

Because rank_features fields cannot contain a `.` character if the token string contains a `.` it is replace with double underscore `__`.  

```
POST _ml/trained_models/text_expansion_model/_infer
{
  "docs": [{"text_field": "pirate ship"}]
}
```

Returns

```
{
  "inference_results": [
    {
      "predicted_value": {
        "pirate": 3.1480324,
        "ship": 2.7033217,
        "pirates": 2.4298668,
        "ships": 1.9557489,
        "treasure": 0.9711017,
        "shipping": 0.75666434,
        "piracy": 0.7324756,
        "boat": 0.71240854,
        "criminal": 0.6781369,
        "gun": 0.5793185,
        "ruin": 0.48752055,
        "toy": 0.44296992,
        "captain": 0.43938705,
        "slave": 0.42513028,
        "party": 0.41519326,
        "discovery": 0.39670518,
        "fake": 0.39445245,
        "submarine": 0.37701997,
        "character": 0.30090195,
        "villain": 0.29887193,
        "castle": 0.28499693,
        "spy": 0.26810843,
        "prison": 0.25391698,
        "quest": 0.24493802,
        "smuggling": 0.23474619,
        "stolen": 0.21570966,
        "jones": 0.21412925,
        "ghost": 0.18707192,
        "devil": 0.18014455,
        "savage": 0.16921283,
        "hero": 0.15776168,
        "smug": 0.14755286,
        "glory": 0.13371459,
        "were": 0.12701046,
        "humor": 0.115971535,
        "henry": 0.1135293,
        "was": 0.104702994,
        "haunted": 0.09767436,
        "who": 0.052228667,
        "alien": 0.029981242,
        "cannon": 0.028697899,
        "slavery": 0.012567138,
        "doll": 0.011823103,
        "destroyed": 0.006246211,
        "dangerous": 0.0058630155,
        "jack": 0.0041660196
      }
    }
  ]
}
```

### CODE REVIEW

**Comment by davidkyle** [comment]
run elasticsearch-ci/bwc

**Review by droberts195 — APPROVED** [review]
LGTM

**Comment by davidkyle** [comment]
Testing with larger datasets I hit an error indexing the tokens in a rank_features field

```[rank_features] fields do not support dots in feature names but found [.]```

Indeed the vocab does contain `.` and several other tokens that themselves contain a `.`. One option to investigate is replacing the `.` in the output vocab

**Comment by davidkyle** [comment]
run elasticsearch-ci/part-2

**Review by droberts195 — APPROVED** [review]
LGTM

**Pull request merged**
