### PR TITLE
Make sure to validate the type before attempting to merge a new mapping.

### PR DESCRIPTION
**Pull request by jtibshirani**
Currently, when adding a new mapping, we attempt to parse + merge it before
checking whether its top-level document type matches the existing type. So when
a user attempts to introduce a new mapping type, we may give a confusing error
message around merging instead of complaining that it's not possible to add
more than one type ("Rejecting mapping update to [my-index] as the final
mapping would have more than 1 type...").

This PR moves the type validation to the start of
`MetaDataMappingService#applyRequest` so that we make sure the type matches
before performing any mapper merging.

We already partially addressed this issue in #29316, but the tests there
focused on `MapperService` and did not catch this problem with end-to-end
mapping updates.

Addresses #43012.

### CODE REVIEW

**Comment by jtibshirani** [comment]
@elasticmachine run elasticsearch-ci/2

**Review by mayya-sharipova — APPROVED** [review]
Thanks @jtibshirani, makes sense

**Comment by jtibshirani** [comment]
Thanks for the review @mayya-sharipova !

**Comment by jtibshirani** [comment]
@elasticmachine run elasticsearch-ci/1

**Pull request merged**
