### PR TITLE
Muting tests for PR https://github.com/elastic/elasticsearch/pull/46414

### PR DESCRIPTION
**Pull request by benwtrent**
Muting the test in preparation for backport PR: https://github.com/elastic/elasticsearch/pull/46748

### CODE REVIEW

**Review by przemekwitek — APPROVED** [review]
LGTM

**Comment by benwtrent** [comment]
run elasticsearch-ci/bwc

**Comment by benwtrent** [comment]
run elasticsearch-ci/bwc

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Comment by benwtrent** [comment]
run elasticsearch-ci/2

**Pull request merged**
