### PR TITLE
Remove unused DelegatingActionListener class

### PR DESCRIPTION
**Pull request by tlrx**
I came accross the unused DelegatingActionListener class.

### CODE REVIEW

**Review by original-brownbear — APPROVED** [review]
LGTM

**Comment by tlrx** [comment]
@elasticmachine test this please

**Comment by tlrx** [comment]
@elasticmachine test this please

**Comment by tlrx** [comment]
@elasticmachine test this please

**Comment by tlrx** [comment]
Thanks @original-brownbear

**Pull request merged**
