### PR TITLE
Move DeleteByQuery and Reindex requests into core

### PR DESCRIPTION
**Pull request by s1monw**
This allows other plugins to use a client to call the functionality
that is in the core modules without duplicating the logic.
Plugins can now safely send the request and response classes via the
client even if the requests are executed locally. All relevant classes
are loaded by the core classloader such that plugins can share them.

### CODE REVIEW

**Comment by s1monw** [comment]
@elasticmachine test this please

**Review by nik9000 — APPROVED** [review]
This seems much better than moving more of reindex's implementation into core and doesn't commit us to cross plugin communication in general while allowing it for reindex specifically. This seems like the best way to resolve this issue.

I can think of at least one followup from this: removing reindex's client jar. It shouldn't be needed if the requests are all in core. I'll have a look at doing that myself as a followup.

**Comment by s1monw** [comment]
@elasticmachine test this please

**Comment by imotov** [comment]
@s1monw, @nik9000 I see that DeleteByQueryAction and UpdateByQueryAction were moved to core, but ReindexAction wasn't. Was this intentional? If it was not, I can start working on moving it to the core as well.

**Comment by nik9000** [comment]
I *think* all the actions need to be moved to core, yeah.

**Comment by imotov** [comment]
ok, I am going to move it then, run tests to make sure it doesn't break anything and will open PR in a bit.

**Comment by nik9000** [comment]
After this commit I *thought* it would be possible to remove the reindex client jar but it turns out that we can't for two reasons:
1. Rethrottling is still only in the reindex plugin.
2. The transport client needs actions to be registered or else it can't proxy requests remotely. This isn't insurmountable but would require a hack like a "fake reindex plugin" or something.

Given those two things, removing the reindex client jar doesn't seem worth it.

**Pull request merged**
