### PR TITLE
Use pattern variables for instanceof for type casting in equals

### PR DESCRIPTION
**Pull request by arteam**
Leverage the [JEP 394](https://openjdk.java.net/jeps/394) and express type casting and the equality check as a single expression.

The biggest issue seems to be that using `instanceof` instead of `getClass` actually can change the semantic of `equals` for non-final classes: two different children of the same parent can be equal if they don't override parent's `equals`.

### CODE REVIEW

**Comment by pugnascotia** [comment]
> The biggest issue seems to be that using instanceof instead of getClass actually can change the semantic of equals for non-final classes: two different children of the same parent can be equal if they don't override parent's equals.

How concerning is this? Should we be being this to Core/Infra for discussion, before we change 800+ classes? I do think this PR is too big to review. If we want to proceed, we should break this down into smaller chunks.

**Comment by arteam** [comment]
> How concerning is this? Should we be being this to Core/Infra for discussion, before we change 800+ classes? I do think this PR is too big to review. If we want to proceed, we should break this down into smaller chunks.

I'm okay to breaking this PR in multiple chunks. I believe it's not very concerning since all the "abstract" classes have children which override the `equals` method. But I can specifically extract such classes from the change. I can find 101 matches for `super.equals(obj) == false` in the code base, so there should be around 20-30 abstract classes provided that a base class has a handful amount of children.

**Review by henningandersen — CHANGES_REQUESTED** [review]
I would prefer not to do this, for two reasons:

1. equals is then no longer symmetric. Suppose you have class `B` extends class `A` and corresponding objects `b` and `a`. If you do `a.equals(b)`, it could be true, whereas b.equals(a) would not be.
2. The `equals` generated by IDEA differs from this. We thus have to hand-craft equals, which is error-prone.

**Comment by arteam** [comment]
Thank you Henning!

I actually was going to close the PR exactly for these both reasons. I found that there are too many side effects for going from `getClass` to `instanceof` (especially for parent classes) and also because Intellij doesn't provide a template for generating `equals` with instanceof for non-final classes.  Anyways, this PR was a very useful exercise for me for learning some advanced refactoring capabilities of IntelliJ.

**Pull request closed without merging**
