### PR TITLE
[8.x] Fix exception message when validating the name of tokenizer(edgeNGram)

### PR DESCRIPTION
**Pull request by YeonghyeonKO**
- Related PRs :
  - #112705
  - #113009 
- Assignee : @YeonghyeonKo @carlosdelest 

The method `getTokenizers` in `CommonAnalysisPlugin` returns IllegalArgumentException with the message:

> The [edgeNGram] tokenizer name was deprecated in 7.6. Please use the tokenizer name to [edge_nGram] for indices created in versions 8 or higher instead.

For IndexVersion **8.x**, `edge_ngram` (not **`edge_nGram`**) is the correct name referred as an `edgeNGram` tokenizer so I ask to change the word in this Pull Request. The PR could reduce confusion in defining edgeNGram tokenizers when statically mapping indices in Elasticsearch 8.x.

After **9.x** version, @javanna's [PR](https://github.com/elastic/elasticsearch/pull/113009) had made the deprecation issue clear and already been merged into `main` branch, so there is no problem.

### CODE REVIEW

**Comment by YeonghyeonKO** [comment]
@carlosdelest
As an external contributor in Elasticsearch, I have no authority to assign you as an assginee/reviewer.

**Comment by carlosdelest** [comment]
@elasticsearchmachine test this please

**Comment by carlosdelest** [comment]
@elasticmachine run elasticsearch-ci/packaging-tests-windows-sample

**Comment by carlosdelest** [comment]
@elasticmachine update branch

**Comment by carlosdelest** [comment]
@elasticsearchmachine test this please

**Comment by carlosdelest** [comment]
@elasticmachine run elasticsearch-ci/part-1

**Comment by carlosdelest** [comment]
@elasticmachine test this please

**Comment by carlosdelest** [comment]
@elasticmachine update branch

**Comment by carlosdelest** [comment]
@elasticmachine test this please

**Review by carlosdelest — APPROVED** [review]

**Comment by carlosdelest** [comment]
It took a while to pass CI on this. Thanks for contributing to Elastic @YeonghyeonKO !

**Comment by YeonghyeonKO** [comment]
@carlosdelest Thank you for reviewing my PR. It took quite long to pass elasticsearch-ci indeed haha

**Pull request merged**
