### PR TITLE
send the fields param via body instead of URL params (elastic#42232)

### LINKED ISSUE #42232: MTermVector Java High Level Client Misses Fields Property
elasticsearch-rest-high-level-client - 7.0.1

Expected vs Actual Behaviour AND steps to reproduce:

1. Create a MultiTermVectorsRequest and add a single TermVectorsRequest WITH a field. 

```
MultiTermVectorsRequest termVectorsRequest = new MultiTermVectorsRequest();

TermVectorsRequest textRequest = new TermVectorsRequest("index", "id");
textRequest.setFields("text");
textRequest.setTermStatistics(true);
textRequest.setFieldStatistics(false);
textRequest.setPositions(false);
textRequest.setOffsets(false);
termVectorsRequest.add(textRequest);

MultiTermVectorsResponse mtermvectors = client.mtermvectors(termVectorsRequest, RequestOptions.DEFAULT);

```

2. When sending to the Java High Level Client, after transformation to low-level REST client format, the fields property is missing! 

When converting to the low-level REST request in internalPerformRequest() within RestHighLevelClient.java it can be inspected that the body of the request will be the following:

```
{
    "docs": [
        {
            "_index": "index",
            "_id": "id",
            "positions": false,
            "offsets": false,
            "field_statistics": false,
            "term_statistics": true
        }
    ]
}
```

Then this is sent to the server. 

3. The elastic search will return no term vectors, since no field was given. And this renders the High Level Java Client useless for multiple term vector retrieval.

### PR DESCRIPTION
**Pull request by peonone**
It fixes #42232
I referred to the conversation from #42877 for the fix.

### CODE REVIEW

**Comment by hub-cap** [comment]
@elasticmachine ok to test

**Comment by hub-cap** [comment]
Thanks for the submission! it looks great.

**Comment by hub-cap** [comment]
Sorry this fell off my radar, getting to it now.

**Comment by hub-cap** [comment]
@elasticmachine update branch

**Review by hub-cap — APPROVED** [review]
LGTM, once this passes tests I can get it merged and backported.

**Comment by danhermann** [comment]
@elasticmachine update branch

**Review by danhermann — APPROVED** [review]
@peonone, thanks for the contribution! I'll get this merged now.

**Pull request merged**
