### PR TITLE
[DOC] Clarify how to remove stack templates (#71254)

### PR DESCRIPTION
**Pull request by jbaiera**
Backport of #71254

* [DOC] Clarify how to remove stack templates
* Add setting and component templates

Co-authored-by: James Rodewig <40268737+jrodewig@users.noreply.github.com>

### CODE REVIEW

**Comment by jbaiera** [comment]
@jrodewig Is there something I'm missing on this backport that is keeping the doc build process from resolving the link to the stack property section?

**Comment by jrodewig** [comment]
Thanks for wrestling with this @jbaiera. I built this locally and don't get the same error.

I have a feeling that the docs CI test is still pulling in old data somewhere. I'm going to try merging in the upstream branch to see if that clears this up.

**Comment by jrodewig** [comment]
@elasticmachine update branch

**Comment by jrodewig** [comment]
I was wrong. It looks like the migration notes gets reused in the Stack installation guide. Converting those xrefs to external links should fix it up.

**Comment by jrodewig** [comment]
Also should note: We only reuse the 7.9 migration guide in the 7.9 version of the Install guide. No need to change those xrefs in #71254

**Review by jrodewig — APPROVED** [review]
This is good to merge at your convenience. Thanks @jbaiera!

**Comment by jbaiera** [comment]
Thanks for the assist @jrodewig!

**Pull request merged**
