### PR TITLE
Remove unsed fields in `RestAnalyzeAction`

### PR DESCRIPTION
**Pull request by chengyang14**
Remove unsed fields in `RestAnalyzeAction`

### CODE REVIEW

**Comment by tvernum** [comment]
@elasticmachine test this please

**Review by cbuescher — CHANGES_REQUESTED** [review]
Hi @chengyang14,

thanks a lot for opening this PR and your contribution to Elasticsearch. I looked at the changes and was suprised we don't use the ParseFields here. I saw we now do the parsing of the "_anaylze" request in the ObjectParser defined in class `AnalyzeAction`. Instead of deleting six of the constants here and leaving the three that are used in `CategorizationAnalyzerConfig`, I think I would be good to move all constants to `AnalyzeAction` and use them in the parser definition there and also point to them from `CategorizationAnalyzerConfig`. Would you mind making those changes?

**Comment by chengyang14** [comment]
Hi @cbuescher 
Thanks for your suggestions, I will move all constants to `AnalyzeAction`.

**Comment by cbuescher** [comment]
@elasticmachine test this please

**Review by cbuescher — APPROVED** [review]
Thanks for the changes, LGTM.
I'll be running our CI test suit before merging.

**Comment by cbuescher** [comment]
@chengyang14 thanks for this change, I merged it to master and the 7.x branch.

**Pull request merged**
