### PR TITLE
Update update-settings.asciidoc

### PR DESCRIPTION
**Pull request by markwalkom**
Made a note that any difference in settings in the yml are handled by only using the elected master ones.

### CODE REVIEW

**Comment by clintongormley** [comment]
@markwalkom this isn't correct

Each node will use the settings as configured in its own config file, unless a cluster settings update request updates a particular dynamic setting

**Comment by markwalkom** [comment]
I thought things like `discovery.zen.minimum_master_nodes` were taken from the master, unless set via the API.

If not, then how do we resolve differences?

**Comment by jasontedor** [comment]
In the case that you're describing where a setting is only configured via the elasticsearch.yml but does not have a transient or persistent value in the cluster settings, each node uses its local value (either from the configuration file or from the default value). This is true even for `discovery.zen.minimum_master_nodes`.

**Comment by markwalkom** [comment]
Then how do we manage discrepancies in these settings? Do we allow some
nodes to have 1, some to have 3, some to have 10?

**Comment by jasontedor** [comment]
Yes.

**Pull request closed without merging**
