### PR TITLE
Remove type parameters from Client.prepareDelete() and Client.prepareUpdate()

### PR DESCRIPTION
**Pull request by romseygeek**
Type parameters are no longer used in DeleteRequest or UpdateRequest; this commit
removes them from the `prepareX` methods on `Client`, as well as removing `setType()`
and deprecated constructors on `XRequestBuilder` objects.

Relates to #41059

### CODE REVIEW

**Comment by romseygeek** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample

**Comment by romseygeek** [comment]
@elasticmachine update branch

**Comment by jtibshirani** [comment]
@romseygeek to check I understand the change -- in addition to removing typed versions of `prepareUpdate` and `prepareDelete`, the PR removes `prepareIndex(index, type)`. But `prepareIndex(index, type, id)` is still present and will be removed in a future PR?

**Comment by romseygeek** [comment]
I had intended to remove prepareIndex(index, type) in a separate PR but rebased against the wrong branch apparently.  I can separate the two changes out if that makes it easier to review?

**Comment by romseygeek** [comment]
@elasticmachine update branch

**Comment by romseygeek** [comment]
@elasticmachine update branch

**Comment by jtibshirani** [comment]
> I had intended to remove prepareIndex(index, type) in a separate PR but rebased against the wrong branch apparently. I can separate the two changes out if that makes it easier to review?

If it's not a ton of work, I think that would be cleanest. But if it will take significant time, we could just update the PR description to clearly list out what has changed, and mention the plan for a follow-up PR?

**Comment by jtibshirani** [comment]
@romseygeek and I discussed offline -- we will keep the change as-is because would be a large amount of work to separate it out.

**Review by jtibshirani — APPROVED** [review]
This looks good to me.

**Comment by romseygeek** [comment]
@elasticmachine update branch

**Pull request merged**
