### PR TITLE
Issue #37303 - Invalid variance fix

### LINKED ISSUE #37303: Invalid variance computed in extended_stats aggregation
**Elasticsearch version** (`bin/elasticsearch --version`): 6.1.4

**Plugins installed**: n/a

**JVM version** (`java -version`): 1.8.191

**OS version** (`uname -a` if on a Unix-like system): Centos 7.5

**Description of the problem including expected versus actual behavior**:
In some conditions, the variance computed in an extended_stats aggregation is computed as a negative number that should never append.

The variance is a sum of positive numbers, hence cannot be negative. What makes it negative here is the way it is computed (probably as the difference of two positive numbers here: "sum_of_squares / count" and "avg * avg"). Due to the non-infinite precision of floating point numbers, both numbers are 'almost' the same...

**Proposed solution**:

At least prevent negative values to appear in the variance: add a "Math.max(0.0, ...)" to the existing computation formula.

**Steps to reproduce**:

Using the attached zip file, do the following :

- in env.properties: put the host/port to the elastic-search instance (default: localhost:9200)
- run ./reproduce.sh my-test-index (or any other index name, beware, this index will be dropped!)

What does it do?

- drop the given index
- create it new with a specific mapping: index: long, amount: double
- load 3 documents with same amount: 49.95
- ask for an "extended_stats" aggregation on the amounts

**Provide logs (if relevant)**:
```
{"acknowledged":true}

{"acknowledged":true,"shards_acknowledged":true,"index":"my-test-index"}

{"_index":"my-test-index","_type":"document","_id":"BErfN2gBWLZgAGEHAdb8","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":0,"_primary_term":1}

{"_index":"my-test-index","_type":"document","_id":"BUrfN2gBWLZgAGEHAtY2","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":0,"_primary_term":1}

{"_index":"my-test-index","_type":"document","_id":"BkrfN2gBWLZgAGEHAtZd","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":0,"_primary_term":1}

{"_shards":{"total":10,"successful":5,"failed":0}}
{
 "took" : 1,
 "timed_out" : false,
 "_shards" : {
   "total" : 5,
   "successful" : 5,
   "skipped" : 0,
   "failed" : 0
 },
 "hits" : {
   "total" : 3,
   "max_score" : 1.0,
   "hits" : [
     {
       "_index" : "my-test-index",
       "_type" : "document",
       "_id" : "BUrfN2gBWLZgAGEHAtY2",
       "_score" : 1.0,
       "_source" : {
         "amount" : 49.95,
         "index" : 2
       }
     },
     {
       "_index" : "my-test-index",
       "_type" : "document",
       "_id" : "BErfN2gBWLZgAGEHAdb8",
       "_score" : 1.0,
       "_source" : {
         "amount" : 49.95,
         "index" : 1
       }
     },
     {
       "_index" : "my-test-index",
       "_type" : "document",
       "_id" : "BkrfN2gBWLZgAGEHAtZd",
       "_score" : 1.0,
       "_source" : {
         "amount" : 49.95,
         "index" : 3
       }
     }
   ]
 },
 "aggregations" : {
   "amount" : {
     "count" : 3,
     "min" : 49.95,
     "max" : 49.95,
     "avg" : 49.95000000000001,
     "sum" : 149.85000000000002,
     "sum_of_squares" : 7485.0075000000015,
     "variance" : -3.0316490059097606E-13,
     "std_deviation" : "NaN",
     "std_deviation_bounds" : {
       "upper" : "NaN",
       "lower" : "NaN"
     }
   }
 }
}
```

**File used to reproduce**:
[to-reproduce-it.zip](https://github.com/elastic/elasticsearch/files/2745481/to-reproduce-it.zip)

### PR DESCRIPTION
**Pull request by vishnugt**
- Fixed Invalid variance computed in extended_stats aggregation #37303
- Problem is due to the non-infinite precision of floating point numbers and due to the way variance is being calculated, it is sometimes obtained as negative numbers, but variances are always non-negative.
- NaN handled - If the variance computed is NaN, the comparison in the code would fail and hence would return NaN(which is what we need)
- This closes #37303

### CODE REVIEW

**Comment by polyfractal** [comment]
Thanks @vishnugt!   Just had a quick skim, would you mind adding a few tests that shows each aggregator does the right thing in this scenario?  That way we don't accidentally break this functionality in the future.

After the tests are added I'll kick off a CI build and give it a more thorough review.  Thanks again!

**Comment by vishnugt** [comment]
I have added a test case for the _getVariance_ method in _InternalExtendedStats_ class, which seems to be the core part.
The reason I've added the condition in other places is just to make sure the variance won't be negative.

Regarding the test case, I had to hardcode a couple of values, because I couldn't reliably generate the expected result in any particular range.

**Comment by polyfractal** [comment]
Great, thanks @vishnugt!  I think hard-coding the values is perfectly fine in this case, it's a very specific scenario that's being fixed.  Kicking off a CI build!

@elasticmachine test this please

**Comment by polyfractal** [comment]
@elasticmachine test this please

**Comment by polyfractal** [comment]
Heya @vishnugt, we're having some test troubles in CI unrelated to this PR.  I'll kick off another build once we resolve the CI stuff, because otherwise it's going to just keep failing for unrelated reasons.  Sorry for the delay!

**Comment by vishnugt** [comment]
Hey @polyfractal, thanks for letting me know that its an issue unrelated to this PR.

**Comment by polyfractal** [comment]
@elasticmachine test this please

**Comment by polyfractal** [comment]
Heya @vishnugt, CI has cleared up a bit.  Would you mind merging master into the PR and I'll kick off another set of builds?

Thanks!

**Comment by vishnugt** [comment]
Hey @polyfractal, I just merged the master into the PR, would you mind kicking off a CI build?

Thanks!

**Comment by polyfractal** [comment]
@elasticmachine test this please

**Comment by vishnugt** [comment]
Hey @polyfractal, I checked the logs as to see why elasticsearch-ci/1 build is failing, and I don't think its related to this PR.

**Comment by polyfractal** [comment]
Hmm I agree, I think it's related to https://github.com/elastic/elasticsearch/pull/37792

Would you mind merging in most recent master once more?  On that note, if you'd like I can help out merging in master to your branch in the future, since CI can be finicky at times.  Would help expedite getting this in :)

**Comment by vishnugt** [comment]
Hey @polyfractal, I just merged this with the recent master.  

I would be more than happy to let you help me with merging, I sent you a collaborator request for my fork of elasticsearch, though I'm not quite sure if this is what you meant.  Please let me know if I have to do anything else on my side to let you help merge.

**Comment by polyfractal** [comment]
@elasticmachine test this please

> I would be more than happy to let you help me with merging, I sent you a collaborator request for my fork of elasticsearch, though I'm not quite sure if this is what you meant. Please let me know if I have to do anything else on my side to let you help merge.

Ah oops, my fault. All that's needed is a checkbox on the PR itself that allows repo maintainers to push to the PR (it should be checked by default, I just like to double-check with contributors so they know what's going on, when new commits show up)

Will help with merging and getting this passed, thanks!

**Comment by vishnugt** [comment]
Ah okay, thanks for clarifying! 
And yay, it passed all the checks this time!

**Comment by polyfractal** [comment]
adcc08a87d810d4d

Merging!  Thanks for your patience with our CI, it's had a rough week :)

**Comment by vishnugt** [comment]
Thank you so much, it's my first PR, hope to send more :)

Thanks for helping till the end!

**Comment by polyfractal** [comment]
No problem, you did all the hard work :)  Looking forward to future PRs!

**Comment by mysticaltech** [comment]
Hey folks, I am sorry to say this is just a patch for a totally wrong variance calculation method. The sum of square method used here should is plain wrong for floating point calculations as it introduces a phenomenon called "catastrophic cancellation" hence the negative values, instead you should perform calculation with the simple Welford algorithm as presented here https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance#Welford's_online_algorithm

**Comment by polyfractal** [comment]
Heya @mysticaltech, thanks for the note!  I mentioned this in a different ticket (https://github.com/elastic/elasticsearch/issues/50416#issuecomment-570287093), but forgot to open a followup ticket to change the algo.  Thanks for the ping, I'll open one to track this particular enhancement :+1:

**Comment by mysticaltech** [comment]
Thanks @polyfractal, that's great, if I knew enough about Elastic Search I would try to help, the Welford algorithm is quite simple and very stable numerically. If it can help, here's a Javascript implementation adapted from the [wikipedia page](https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance#Welford's_online_algorithm) python one https://gist.github.com/mysticaltech/7ceb16eaa6ad00209e6fd87a55785991

**Comment by polyfractal** [comment]
Thanks @mysticaltech :)  I suspect the hard part will actually be unrelated to the algo entirely, it'll be around dealing with backwards compat with older versions (since we'll need to support the old algo serialization, etc).  Cheers!

**Comment by mysticaltech** [comment]
@polyfractal Yes I understand, it makes sense. But the variance should end up being the same, unless for cases where there was too much error and folks adapted to that. That said, I fully agree that such a change would be too risky (even though theoretically it shouldn't be). So I would suggest keeping all variance method by default using the sum of square, and adding an **optional flag** to switch to Welford. This way, folks will have to manually specify Welford. And if the M2 moment aggregate is calculation is added, this can be done in one-pass if I'm not mistaken.

**Pull request merged**
