### PR TITLE
Support field collapsing with search_after

### PR DESCRIPTION
**Pull request by jtibshirani**
Backport of #73023.

### CODE REVIEW

**Comment by jtibshirani** [comment]
@elasticmachine run elasticsearch-ci/part-2

**Comment by prestonhansen** [comment]
hi @jtibshirani, bit of a naive question, but is this backport expected to work in all ES 7.X versions?

I was playing around with using this in ES `7.1.1` and get an error message about the feature not being enabled


Maybe it's because of the `minimum_wire_compatibility_version`?
```
"version" : {
    "number" : "7.1.1",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "7a013de",
    "build_date" : "2019-05-23T14:04:00.380842Z",
    "build_snapshot" : false,
    "lucene_version" : "8.0.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
```

**Comment by jtibshirani** [comment]
Hello @prestonhansen, we typically only backport features to the latest minor release. This one in particular was released in 7.14. You can check what releases a feature made it into by looking at the labels on the original PR: https://github.com/elastic/elasticsearch/pull/73023.

**Comment by prestonhansen** [comment]
great, thank you!

**Pull request merged**
