### PR TITLE
Fix FiltersAggregation NPE when `filters` is empty

### LINKED ISSUE #41408: null_pointer_exception when filters aggregation is empty
**Elasticsearch version**: 7.0.0 (reproducible on official docker)

The following request:
```json
GET _search
{
  "aggs": {
    "my_filters": {
      "filters": {}
    }
  }
}
```

Results in:
```json
{
  "error": {
    "root_cause": [
      {
        "type": "null_pointer_exception",
        "reason": null
      }
    ],
    "type": "null_pointer_exception",
    "reason": null
  },
  "status": 500
}
```
Workaround is easy but it should probably be fixed.

### PR DESCRIPTION
**Pull request by polyfractal**
If `keyedFilters` is null the code assumes there are unkeyed filters...which will NPE if the unkeyed filters was actually empty.

This refactors to simplify the filter assignment a bit, adds an empty check and tidies up some formatting.

It also fixes a few tests that _should_ have exposed this NPE, but due to how they were setup (using try blocks) the exception was hidden. The try blocks are removed so that any future exceptions are not swallowed.

I _wanted_ to refactor the agg to use our static parsers, but the filters agg is super lenient which makes parsing tricky (anonymous array of filter objects or keyed object of filters, default other bucket name or configurable, boolean to control other bucket which interacts with other key).  I think we should probably just simplify the agg... will open a different issue about that.

Closes https://github.com/elastic/elasticsearch/issues/41408

### CODE REVIEW

**Review by javanna — APPROVED** [review]
LGTM and looks clearer too. One thing I don't follow is where the tests were swallowing the NPE, the try was there only to close the parser when done?

**Comment by polyfractal** [comment]
Huh... yeah you're right.  I was thinking the `try` would swallow exceptions, but it's just acting as a `finally` for the resources and should rethrow anything inside the try block.

Lemme make sure I'm fixing what I think I'm fixing. :)  Going to doublecheck the tests and the original NPE.

**Comment by polyfractal** [comment]
Oh right, I see.  The tests don't cover the NPE case... I misread the original query.  It's a completely empty `filters` agg, not an empty `filters` array/object inside the `filters` agg.  

The fix works as intended because it prevents keyed/unkeyed from being null, but I'll add a test for the empty filter agg, revert the `try...` changes and adjust the commit message.

**Comment by javanna** [comment]
sounds good thanks @polyfractal !

**Comment by polyfractal** [comment]
@elasticmachine test this

**Comment by polyfractal** [comment]
@elasticmachine run elasticsearch-ci/1
@elasticmachine run elasticsearch-ci/1

**Comment by polyfractal** [comment]
@elasticmachine run elasticsearch-ci/default-distro
@elasticmachine run elasticsearch-ci/bwc

**Comment by polyfractal** [comment]
CI is green but a bit stale for my liking and I've been bit by that recently, sooo....

@elasticmachine retest this please

**Pull request merged**
