### PR TITLE
fix threshold spelling errors

### PR DESCRIPTION
**Pull request by weizijun**
this pr fix word misspelling. I fixed all treshold misspelling to right threshold.

### CODE REVIEW

**Comment by weizijun** [comment]
@ywelsch can you commit this pr?

**Comment by ywelsch** [comment]
@elasticmachine update branch

**Comment by ywelsch** [comment]
@elasticmachine test this please

**Review by ywelsch — APPROVED** [review]
LGTM

**Comment by weizijun** [comment]
@ywelsch thank you!

**Pull request merged**
