### PR TITLE
remove index.lifecycle.skip setting

### PR DESCRIPTION
**Pull request by talevy**
With the introduction of _ilm/stop and _ilm/start APIs, the
use cases where one would only target a select group
of indices to start/stop has been reduced. Since there is no
strong use-case for skipping specific indices, it is best to
remove this functionality and only adding if later desired, with the
hopes of keeping things more simple.

### CODE REVIEW

**Review by colings86 — APPROVED** [review]
LGTM if CI passes

**Comment by talevy** [comment]
thanks for the review @colings86. 🤞

**Comment by talevy** [comment]
test this please

**Review by AthenaEryma — COMMENTED** [review]
LGTM too, assuming CI is green.

~~One note: https://github.com/elastic/elasticsearch/blob/index-lifecycle/x-pack/docs/en/ilm/pause-resume-ilm.asciidoc still mentions that "ILM can be skipped on a per-index basis", but since that isn't actual documentation yet it's probably fine.~~ This doc is changed in your other PR, ignore this comment.

**Review by AthenaEryma — APPROVED** [review]
In case it wasn't clear I meant to approve this rather than just comment.

**Pull request merged**
