### PR TITLE
Remove typo put-lifecycle.asciidoc

### PR DESCRIPTION
**Pull request by TimBosman**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against main? Unless there is a good reason otherwise, we prefer pull requests against main and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by kingherc** [comment]
@elasticmachine update branch

**Comment by kingherc** [comment]
Hi @TimBosman , I changed the target branch to be main instead of 8.14, but it resulted in some merge conflicts. Would you be able to rebase the PR on top of `main` please?

**Comment by leemthompo** [comment]
@kingherc we could also just merge to 8.14 and forward port to main/8.15 by adding version labels and `auto-backport-and-merge`

**Comment by kingherc** [comment]
@leemthompo Interesting, I have never used the "backport" labels to forward port (especially to main). Let me see if I can do this now.

**Review by leemthompo — APPROVED** [review]

**Comment by leemthompo** [comment]
hmmmmm that _should_ have worked 😄

**Comment by kingherc** [comment]
Possibly does not forward port automatically.

@TimBosman Could I ask you to issue a new PR with your typo fix against the `main` branch?

**Pull request merged**
