### PR TITLE
Remove assertion that checks the exception message on AzureBlobContainerRetriesTests#testRetryUntilFail

### LINKED ISSUE #66865: AzureBlobContainerRetriesTests testRetryUntilFail fails
**Build scan**:
https://gradle-enterprise.elastic.co/s/yb7lph3epqlqy

**Repro line**:
./gradlew ':plugins:repository-azure:test' --tests "org.elasticsearch.repositories.azure.AzureBlobContainerRetriesTests.testRetryUntilFail" \
  -Dtests.seed=E146AF3527EDBEB \
  -Dtests.security.manager=true \
  -Dbuild.snapshot=false \
  -Dtests.jvm.argline="-Dbuild.snapshot=false" \
  -Dtests.locale=en-IE \
  -Dtests.timezone=America/Fort_Wayne \
  -Druntime.java=8

**Reproduces locally?**:
No

**Applicable branches**:
7.11,  7.x, master

**Failure history**:
 9 failures from Dec 22 to Dec 29

**Failure excerpt**:

```
org.elasticsearch.repositories.azure.AzureBlobContainerRetriesTests > testRetryUntilFail FAILED
09:10:38     java.lang.AssertionError: 
09:10:38     Expected: <3>
09:10:38          but: was <2>
09:10:38         at __randomizedtesting.SeedInfo.seed([E146AF3527EDBEB:E214676353BDDD3B]:0)
09:10:38         at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
09:10:38         at org.junit.Assert.assertThat(Assert.java:956)
09:10:38         at org.junit.Assert.assertThat(Assert.java:923)
09:10:38         at org.elasticsearch.repositories.azure.AzureBlobContainerRetriesTests.testRetryUntilFail(AzureBlobContainerRetriesTests.java:440)
```

Possibly related to https://github.com/elastic/elasticsearch/pull/66531

### PR DESCRIPTION
**Pull request by fcofdez**
The error message might change depending on the timing when we try
to read from the stream. Since we already check that we're not able
to read any data from the stream this assertion doesn't add much value.

Closes #66865

### CODE REVIEW

**Comment by fcofdez** [comment]
This test is cursed 😅

**Review by original-brownbear — APPROVED** [review]
LGTM :)

**Review by original-brownbear — CHANGES_REQUESTED** [review]
Ah sorry second thoughts ... shouldn't we still suppress the `IOException` even if the message may vary?

**Comment by fcofdez** [comment]
We close the exchange in the finally block, I think that's enough?

**Comment by original-brownbear** [comment]
> We close the exchange in the finally block, I think that's enough?

It's not I'm afraid, when setting up the HTTP server we add an execution wrapper that rethrows any exception as `AssertionError` to kill the test on unexpected failures so we gotta suppress that exception I think, otherwise we'll still fail in the same spot just differently.

**Comment by fcofdez** [comment]
I think we only do that on `org.elasticsearch.repositories.ESMockAPIBasedRepositoryIntegTestCase#startHttpServer` and in this tests we're using a plain `MockHttpServer`. In any case I'll suppress the exception #:+1:

**Review by original-brownbear — APPROVED** [review]
LGMT thanks!

+ you're right ... my bad for mixing up our uses of the mock http server :)

**Pull request merged**
