### PR TITLE
Remove version from rollup

### PR DESCRIPTION
**Pull request by mosche**
Remove version from rollup in a backwards compatible way (keeping the `rollup-version` field with an empty string value).

Considering rollup will eventually be removed, it seems unnecessary to go though a deprecation process for `rollup-version` at this point.

### CODE REVIEW

**Comment by thecoop** [comment]
How will previous versions react to the empty rollup-version field? Will they see it at all?

**Comment by mosche** [comment]
> How will previous versions react to the empty rollup-version field? Will they see it at all?

Previous versions do this (pointless) check, despite `stringVersion` not being used at all.
But it obviously makes it hard to simply remove the field.

```java
String stringVersion = (String) ((Map<String, Object>) m).get(Rollup.ROLLUP_TEMPLATE_VERSION_FIELD);
if (stringVersion == null) {
  listener.onFailure(new IllegalStateException("Could not determine version of existing rollup metadata for index [" + indexName + "]"));
  return;
}
```

**Comment by thecoop** [comment]
Ah, checks against null, so empty string is fine.

**Review by thecoop — APPROVED** [review]
LGTM from the version side

**Review by martijnvg — APPROVED** [review]
lgtm

**Pull request merged**
