### PR TITLE
Remove type from VersionConflictEngineException.

### PR DESCRIPTION
**Pull request by jpountz**
It initially mentioned the type in the exception because the type used to be
required to uniquely identify a document. This is not necessary anymore given
that indices have at most one type.

### CODE REVIEW

**Review by cbuescher — APPROVED** [review]
@jpountz there appear to be some tests that check the exception message details that are currently failing, but other than that LGTM as soon as CI is green.

**Review by dnhatn — APPROVED** [review]
LGTM2.

**Comment by jpountz** [comment]
Test this please.

**Comment by ywelsch** [comment]
@jpountz do you still want to get this in?

**Comment by jpountz** [comment]
Yes, sorry it's taking so long. I need to dig into the build failures but I've had other priorities recently. I'll try to come back to this one soon.

**Pull request merged**
