### PR TITLE
Fork Lucene PatternTokenizer to apply LUCENE-6814

### LINKED ISSUE #13721: Leaky PatternTokenizer
Analyzer component reuse does not interact well with `PatternTokenizer` (and possibly other tokenizers, but I haven't looked into them). https://github.com/elastic/elasticsearch/pull/6792 changed the `PatternAnalyzer` from lucene's deprecated version (that packaged its own `PatternTokenizer`) to a standalone `PatternTokenizer`. Under the hood, lucene uses `StringBuilder` to store field values during tokenization but never reclaims storage (e.g. with `trimToSize()`). This causes PatternTokenizer to grow to the largest field the Tokenizer encounters.

The use case we're encountering this issue with is using a custom `PatternTokenizer` for indexing logs, creating indices corresponding to log timestamp. We're running 1.6.2, but so far I don't see anything that this has been fixed in later versions. This really hurts with a large number of indices.

I was looking into closing Analyzers when indices go inactive, but it's been a bit rough trying to find the right place to put it. I'm sure there's probably a better solution as well. Reverting https://github.com/elastic/elasticsearch/pull/6792 is an option if lucene's PatternAnalyzer can be vendored (was removed in 5.x).

In the meantime, are there any short term solutions to explicitly freeing up Analyzers? `index.blocks.read_only` looked promising, but from what I can tell, it only causes requests to be rejected and doesn't release Analyzers (though I might be mistaken). Closing and reopening indices isn't a particularly good option for our use case either.

### PR DESCRIPTION
**Pull request by achow**
While LUCENE-6814 fixes #13721, it will only make it into Lucene 5.4. This will make it only available to elasticsearch 2.0.

There appears to be a very low chance of LUCENE-6814 getting fixed in 4.10, which elasticsearch 1.x uses. I've made a copy of Lucene 4.10.4 PatternTokenizer with the fix so that 1.x versions will also be able to benefit.

### CODE REVIEW

**Comment by s1monw** [comment]
> While LUCENE-6814 fixes #13721, it will only make it into Lucene 5.4. This will make it only available to elasticsearch 2.0.

2.0 is based off Lucene 5.2.1 and 2.1 will be on 5.3 so this will only make it into 2.2 I think we also need to fork this into 2.1 and 2.0? @mikemccand WDYT

**Comment by mikemccand** [comment]
> I think we also need to fork this into 2.1 and 2.0? @mikemccand WDYT

+1

I'll push this to 1.7, 2.0 and 2.1.

**Comment by mikemccand** [comment]
@achow Sorry, one more thing: can you restore the original (Apache) license headers on the forked sources?  Thank you.

**Comment by achow** [comment]
@mikemccand updated.

**Comment by mikemccand** [comment]
Thanks @achow, this looks great, I'll merge shortly!

**Comment by mikemccand** [comment]
Still working to forward port this, struggling with the license checker which is angry that these sources have Apache copyright headers ...

**Pull request merged**
