### PR TITLE
Remove tribe node support

### PR DESCRIPTION
**Pull request by s1monw**
Tribe node has been super-seeded by Cross-Cluster-Search. This change
removes the tribe node support entirely. 
The tribe feature was deprecated in 5.4 and announced for removal in 7.0

### CODE REVIEW

**Review by jasontedor — APPROVED** [review]
LGTM.

**Review by bleskes — APPROVED** [review]
LGMT2

**Comment by epixa** [comment]
Mind holding off about 24 hours while we gut Kibana as well?  I don't want master tests to start failing because Kibana is lagging.

**Comment by s1monw** [comment]
@epixa sure thing gimme a heads-up once you are ready

**Comment by epixa** [comment]
PR is up https://github.com/elastic/kibana/pull/16397.  I'll ping here when it is merged.

**Comment by epixa** [comment]
Tribe has been removed from Kibana master, so merge away!

**Pull request merged**
