### PR TITLE
Checkstyle: require braces around do, for, and while clauses

### PR DESCRIPTION
**Pull request by williamrandolph**
While investigating some [strange behavior in our spotless formatter](https://github.com/elastic/elasticsearch/pull/103073), we came across some control flow statements without braces. Such statements can be risky: it may be visually unclear which statements are associated with a conditional branch, and it's easy to introduce errors when commenting out code or making complicated merges.

This PR adds a Checkstyle NeedsBraces check, which will be enforced by the precommit step of our build, and updates all cases that would fail the checkstyle check. We leave out the `if` and `else` statement: there are thousands of uses of `if` without braces in our codebase, many of them auto-generated for `equals` methods. We also allow the "empty loop" construct:

```
while (checkCondition())
    ;
```

Whether an empty block with a `// do nothing` comment is clearer seems to me a matter of taste.

### CODE REVIEW

**Review by rjernst — COMMENTED** [review]
The change looks good. My only thought is whether we should leave off the `else` since we are not doing `if`. It looks a bit weird in the cases we have an inline `if` without braces, but the else has braces and now is on multiple lines.

**Comment by thecoop** [comment]
I think it is still clearer to have `if xxx return aaa else return bbb` style statements in small methods, rather than just cutting off the `else`, so I would be in favour of adding brackets rather than removing the `else`, but I'm happy to go with the majority here.

**Comment by williamrandolph** [comment]
It sounds like the consensus position is that we leave both if and else alone, but make checkstyle require braces on non-empty loops. I'll proceed with that.

**Review by rjernst — APPROVED** [review]
LGTM

**Review by thecoop — APPROVED** [review]

**Review by mark-vieira — APPROVED** [review]

**Pull request merged**
