### PR TITLE
Fix reindex-from-remote for parent/child from <2.0

### LINKED ISSUE #21044: Investigate reindex-from-remote and parent/child
It [looks like](https://discuss.elastic.co/t/upgrading-1-7-5-0-with-reindex-from-remote-and-parent-child-docs/63463) reindex-from-remote and parent/child don't always play well together.

### PR DESCRIPTION
**Pull request by nik9000**
Versions before 2.0 needed to be told to return interesting fields
like `_parent`, `_routing`, and `_ttl`. And they come
back inside a `fields` block which we need to parse.

Closes #21044

### CODE REVIEW

**Comment by nik9000** [comment]
This is also a bug in 5.0.0 but I don't think it is going to make it....

**Comment by nik9000** [comment]
@dakrone, would you mind having a look? I think you reviewed the reindex-from-remote work before....

**Review by dakrone — APPROVED** [review]
LGTM, but are we sure we want to translate a deprecated feature from an earlier version of ES to the newer one? (`_ttl`)

**Comment by nik9000** [comment]
I just backported this to the 5.0 branch so it'll go out with 5.0.1.

**Pull request merged**
