### PR TITLE
ESQL: Reenable yaml tests

### PR DESCRIPTION
**Pull request by nik9000**
This reenables are yaml tests we disabled while building block tracking. They all pass for me. I believe we've covered their cases.

### CODE REVIEW

**Review by bpintea — APPROVED** [review]
lgtm

**Comment by nik9000** [comment]
Thanks @bpintea !

**Comment by nik9000** [comment]
update branch

**Comment by nik9000** [comment]
> update branch

Fine then. I'll do it myself.

**Pull request merged**
