### PR TITLE
[DOCS] Removes out-dated info from Watcher limitations

### PR DESCRIPTION
**Pull request by lcawl**
This PR removes the following Watcher limitation from the documentation:

https://www.elastic.co/guide/en/elastic-stack-overview/master/watcher-limitations.html#_watcher_ui

There is no longer a "Save" button so this work-around no longer applies.

### CODE REVIEW

**Comment by jakelandis** [comment]
The save button is still there, it is just called `Create watch` or `Save watch` and moved.

image
edit:
image


However, with out any history or context, this seems like an odd thing to call out in the first place. 

I am +1 to accept this change as-is or +1 to update the image. 

cc @elastic/es-ui

**Comment by alisonelizabeth** [comment]
++ to @jakelandis's comment.

FWIW I think this would apply to many of our apps, not just watcher, so it seems strange that we were only calling it out for watcher.

**Comment by cjcenizal** [comment]
I think we had good intentions when we originally added this documentation but I agree that it's incongruous with the rest of our content and removing it is for the best.

**Comment by jakelandis** [comment]
thanks @alisonelizabeth  @cjcenizal 

LGTM as-is to remove it (but may want to tweak the commit message).

**Review by jakelandis — APPROVED** [review]

**Pull request merged**
