### PR TITLE
Remove hidden file leniency from plugin service

### PR DESCRIPTION
**Pull request by jasontedor**
This commit removes some leniency from the plugin service which skips hidden files in the plugins directory. We really want to ensure the integrity of the plugin folder, so hasta la vista leniency.

Relates #12465

### CODE REVIEW

**Comment by rjernst** [comment]
LGTM

**Comment by jasontedor** [comment]
Thanks @rjernst.

**Comment by jasontedor** [comment]
I think it's important to point out that a reason that this leniency is so dangerous is because when we install a plugin we explode it into a hidden temporary directory in the plugins folder. If something blows up during plugin installation (which we try to clean up gracefully), this hidden folder will remain. Leniency allows this go undetected, and that is bad for the user. This leniency is a bug.

**Comment by Antman261** [comment]
But this doesn't help users understand what to do - this has occurred for me after initial install. Instead of a solution I get a stack trace and some google treasure hunting until I stumble on this issue. Not a great first impression of ElasticSearch.

**Pull request merged**
