### PR TITLE
Fix failed dependency resolution with external build-tools users

### LINKED ISSUE #45073: Upgrading external plugins to 7.3.0 fails
**Elasticsearch version** (`bin/elasticsearch --version`): 7.3.0

**Description of the problem including expected versus actual behavior**:

Upgrading to 7.3.0 seems to show some error in build tools.

**Steps to reproduce**:

After upgrading to gradle 5.5 (or 5.5.1) the following exception occurs:

```
./gradlew clean check
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/../cookiecutter-elasticsearch-ingest-processor/ingest-awesome/build.gradle' line: 18

* What went wrong:
A problem occurred evaluating root project 'ingest-awesome'.
> Failed to apply plugin [id 'elasticsearch.esplugin']
   > Could not create task ':integTest'.
      > Could not create task of type 'RestIntegTestTask'.
         > Project with path ':rest-api-spec' could not be found in root project 'ingest-awesome'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring root project 'ingest-awesome'.
> Failed to notify project evaluation listener.
   > Must specify license and notice file for project :
   > Must specify license and notice file for project :
   > Must specify license and notice file for project :
   > Could not get unknown property 'bundlePlugin' for task set of type org.gradle.api.internal.tasks.DefaultTaskContainer.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
```

You can use https://github.com/spinscale/elasticsearch-ingest-langdetect as a base and change `gradle/wrapper/gradle-wrapper.properties` to use gradle 5.5 and then the error manifests.

### PR DESCRIPTION
**Pull request by mark-vieira**
This PR fixes https://github.com/elastic/elasticsearch/issues/45073.

### CODE REVIEW

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by mark-vieira** [comment]
@elasticmachine retest this please

**Comment by mark-vieira** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by mark-vieira** [comment]
@elasticmeachine update branch

**Pull request merged**
