### PR TITLE
[Issue-27716]: CONTRIBUTING.md IntelliJ configurations settings are confusing

### PR DESCRIPTION
**Pull request by avneesh91**
1. Added the Application to the edit configurations help section for IntelliJ.
2. Added information about how to run a local copy of elasticsearch from the source.

### CODE REVIEW

**Review by martijnvg — CHANGES_REQUESTED** [review]
@avneesh91 The paragraph is talking this setting in the context of running tests. So instead of `Application`, I think it should be `Defaults > JUnit`?

**Comment by jasontedor** [comment]
For future reference, we do not require an issue to open a PR against. For a PR like this, a straight PR with no issue is preferred.

**Comment by avneesh91** [comment]
@martijnvg Thanks for reviewing my pull request. Changed the line as per the comment
@jasontedor Closed the issue.

**Review by martijnvg — APPROVED** [review]
Thanks @avneesh91!

**Pull request merged**
