### PR TITLE
Correct profiled rewrite time for knn with a pre-filter

### PR DESCRIPTION
**Pull request by benwtrent**
kNN profiling will fire multiple rewrite actions in a row without stopping a previous one. Right now, this means in production, the rewrite times are inaccurate for knn with a prefilter as we inaccurately calculate the total time (prefilter rewrite & knn rewrite). 

This adjusts the interface for rewriting timing to allow concurrent rewriters which then each can update the total rewrite time that we return to the user. 

Relates to: https://github.com/elastic/elasticsearch/issues/104131

### CODE REVIEW

**Review by carlosdelest — APPROVED** [review]
The changes LGTM.

Should we test the rewrite time in the profile results? Would it make sense to check that `stopAndAddRewriteTime` has been called N times depending on the query structure?

**Review by javanna — APPROVED** [review]
neat, thanks for fixing

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Pull request merged**
