### PR TITLE
[maven] reorganize the codebase (round 2)

### PR DESCRIPTION
**Pull request by rmuir**
Continuation of #11470  (i pushed commits to my branch, and tested modifications)

### CODE REVIEW

**Comment by dakrone** [comment]
LGTM

As an aside, I did run the migrate script and it looks like it's already found issues (awesome!):

```
[INFO] Reactor Summary:
[INFO] 
[INFO] Elasticsearch Build Resources ...................... SUCCESS [  0.409 s]
[INFO] Elasticsearch Parent POM ........................... SUCCESS [  1.543 s]
[INFO] Elasticsearch Core ................................. SUCCESS [ 13.067 s]
[INFO] Elasticsearch Plugin POM ........................... SUCCESS [ 10.420 s]
[INFO] Elasticsearch Japanese (kuromoji) Analysis plugin .. FAILURE [  6.381 s]
[INFO] Elasticsearch Smart Chinese Analysis plugin ........ SKIPPED
[INFO] Elasticsearch Stempel (Polish) Analysis plugin ..... SKIPPED
[INFO] Elasticsearch Phonetic Analysis plugin ............. SKIPPED
[INFO] Elasticsearch ICU Analysis plugin .................. SKIPPED
[INFO] Elasticsearch Mapper Attachment plugin ............. SKIPPED
[INFO] Elasticsearch Google Compute Engine cloud plugin ... SKIPPED
[INFO] Elasticsearch Azure cloud plugin ................... SKIPPED
[INFO] Elasticsearch AWS cloud plugin ..................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 40.166 s
[INFO] Finished at: 2015-06-04T09:07:45-06:00
[INFO] Final Memory: 67M/2216M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project elasticsearch-analysis-kuromoji: Compilation failure: Compilation failure:
[ERROR] /home/hinmanm/src/elasticsearch/plugins/analysis-kuromoji/src/main/java/org/elasticsearch/index/analysis/JapaneseStopTokenFilterFactory.java:[28,39] error: cannot find symbol
[ERROR] symbol:   class ImmutableMap
[ERROR] location: package org.elasticsearch.common.collect
[ERROR] /home/hinmanm/src/elasticsearch/plugins/analysis-kuromoji/src/main/java/org/elasticsearch/plugin/analysis/kuromoji/AnalysisKuromojiPlugin.java:[22,39] error: cannot find symbol
[ERROR] symbol:   class ImmutableList
[ERROR] location: package org.elasticsearch.common.collect
[ERROR] /home/hinmanm/src/elasticsearch/plugins/analysis-kuromoji/src/main/java/org/elasticsearch/index/analysis/JapaneseStopTokenFilterFactory.java:[53,8] error: cannot find symbol
[ERROR] symbol:   class ImmutableMap
[ERROR] location: class JapaneseStopTokenFilterFactory
[ERROR] /home/hinmanm/src/elasticsearch/plugins/analysis-kuromoji/src/main/java/org/elasticsearch/plugin/analysis/kuromoji/AnalysisKuromojiPlugin.java:[47,15] error: cannot find symbol
[ERROR] -> [Help 1]
```

These can be fixed after this PR though.

**Comment by rmuir** [comment]
@s1monw has been digging into this. we are concerned things are really working properly with shading.

**Comment by s1monw** [comment]
rob and myself worked on this and fixed that build. We still have to work on preserving history a bit more but if you do fetch the branch and run

```
mvn clean test-compile -Delasticsearch.thirdparty.config=unshaded
```
it works as well as if you run 
```
mvn clean install -DskipTests
```

I guess this could help with the history http://gbayer.com/development/moving-files-from-one-git-repository-to-another-preserving-history/

**Comment by s1monw** [comment]
LGTM lets move here @rmuir ?

**Pull request merged**
