### PR TITLE
Extra kibana_system privileges for Fleet transform upgrades

### PR DESCRIPTION
**Pull request by droberts195**
These changes go with those of elastic/kibana#142920.

As we formalize the process by which the Fleet package installer will upgrade transforms more operations are required for managing the transforms and the related destination index:

1. Need to be able to add an alias on the transform destination index and adjust which indices it points to when upgrading the transform.
2. Need to be able to remove a default ingest pipeline from the settings of an old transform destination index during an upgrade that deletes the ingest pipeline.

### CODE REVIEW

**Comment by droberts195** [comment]
cc @qn895

**Comment by ywangd** [comment]
Ping @elastic/kibana-security for awareness

**Comment by azasypkin** [comment]
Thanks for the ping @ywangd! Looks good from the Kibana Security perspective.

**Comment by ywangd** [comment]
@droberts195 I think this should be `>enhancement`. Do you have a reason to label it as `>non-issue`?

**Comment by droberts195** [comment]
> Do you have a reason to label it as `>non-issue`?

I thought it best not to clutter the release notes with internal implementation details. (I'm assuming that we don't expect external users to use the `kibana_system` role directly.)

But I'm happy to make this `>enhancement` if that fits better with what the security team usually puts in the release notes.

**Comment by droberts195** [comment]
@elasticmachine update branch

**Review by ywangd — APPROVED** [review]
LGTM

**Pull request merged**
