### PR TITLE
Document a number of enrich node settings.

### PR DESCRIPTION
**Pull request by martijnvg**
Add a section in the docs that describe a number of node level settings
for the enrich processor.

### CODE REVIEW

**Review by jrodewig — COMMENTED** [review]
Thanks @martijnvg. This looks good overall. Two bigger pieces of feedback:

1. We don't explain `enrich coordinator` or `enrich policy executor` in the current docs. It'd be good to explain those concisely somewhere before introducing the settings.

2. I think this content may fit better at the end of this file:
https://github.com/elastic/elasticsearch/edit/master/docs/reference/ingest/enrich.asciidoc

**Review by jrodewig — APPROVED** [review]
Thanks @martijnvg. There is one typo.

Other than that, I left some suggestions that you can take or ignore as wanted.

I'm still a little confused by what we mean by "node component" here. Is it just some threads on the ingest node? Can you indicate which ingest node is a coordinator vs executor?

**Comment by martijnvg** [comment]
> I'm still a little confused by what we mean by "node component" here. Is it just some threads on the ingest node? Can you indicate which ingest node is a coordinator vs executor?

@jrodewig Does this change clarify this: 8b4da68a6cfbdf8c66c4fd78e2487237bd417dff

**Review by jrodewig — APPROVED** [review]
LGTM. Thanks for the iteration. This addressed my concerns!

**Pull request merged**
