### PR TITLE
Format doc_value fields

### PR DESCRIPTION
**Pull request by jpountz**
Backport of #22146

Note to reviewers: the diff between this change and #22146 is contained in the 2nd commit.

### CODE REVIEW

**Comment by jimczi** [comment]
LGTM
You can maybe add a small note in the docs regarding the new `use_field_mapping` option ?

**Review by nik9000 — APPROVED** [review]
Same comment and Jim. It looks like you'd documented `use_field_mapping` in the breaking changes doc which didn't survive the backport proposal.

**Comment by javanna** [comment]
what happened to this PR? seems like it stayed opened for months despite it had LGTMs, and then it was closed without further commenting.

**Comment by javanna** [comment]
I think it got closed because it was opened against 5.x, which was deleted.

**Comment by jpountz** [comment]
Right. This PR requires sync with the Kibana team since it is going to be a breaking change for them and I never took the time to do it. I'll try to do it during the 6.x series.

**Pull request closed without merging**
