### PR TITLE
Add FIPS 140 mode to XPack Usage API

### PR DESCRIPTION
**Pull request by jkakavas**
This change adds support for the FIPS 140 mode to be
retrieved via the XPack Usage API.

### CODE REVIEW

**Comment by jkakavas** [comment]
@hub-cap would you mind taking a look at this ? Thanks :pray:

**Review by hub-cap — APPROVED** [review]

**Comment by jkakavas** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample-matrix

**Comment by jkakavas** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by jkakavas** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample

**Pull request merged**
