### PR TITLE
[Inference API] alibabacloud ai search service support chunk infer to support semantic_text field

### PR DESCRIPTION
**Pull request by weizijun**
The `doChunkedInfer` method is not implement before, I add the support. It used for write the semantic_text field.

### CODE REVIEW

**Comment by weizijun** [comment]
Hi @davidkyle, could you please review this PR?

**Review by davidkyle — APPROVED** [review]
LGTM

Thanks @weizijun, I had noticed chunking was missing and was about to start work on the same change when I saw your PR 🙇

**Comment by davidkyle** [comment]
@elasticmachine test this please

**Comment by davidkyle** [comment]
@elasticmachine test this please

**Pull request merged**
