### PR TITLE
Upgrade Netty to 4.1.94.Final

### PR DESCRIPTION
**Pull request by kingherc**
Just staying up to date.

Followed similar approach as previous upgrade PR https://github.com/elastic/elasticsearch/pull/95575 .

### CODE REVIEW

**Comment by kingherc** [comment]
@elasticmachine please run elasticsearch-ci/example-plugins

**Comment by kingherc** [comment]
Ignore the elasticsearch-ci/example-plugins failure as that's gonna fail until some new artifacts are built.

**Review by original-brownbear — APPROVED** [review]

**Comment by kingherc** [comment]
@elasticmachine please run elasticsearch-ci/example-plugins

**Comment by kingherc** [comment]
@elasticmachine please run elasticsearch-ci/example-plugins

**Pull request merged**
