### PR TITLE
Remove DeprecationLogger from AbstractIndexComponent

### PR DESCRIPTION
**Pull request by original-brownbear**
Random find This is not used any longer.

### CODE REVIEW

**Review by rjernst — COMMENTED** [review]
I don't disagree with cleaning up unused members, but is there a cost to keeping it? It seems useful to have at this abstract level, and I suspect it was used before, but we have fewer deprecations at the moment (especially at the index level).

**Comment by original-brownbear** [comment]
> , but is there a cost to keeping it?

Actually yes now that you ask :D in the many-shards benchmarks and in tests the `getLogger()` which looks at the current stack trace actually costs a visible amount of CPU. But also, we could probably a this point do away with the abstract index component altogether. It only has 3 remaining implementations and the logger field is used by only 2 of them, and the index settings field is used by 2. So all in all, having this thing around adds more code than it dries up already I think :)

**Review by rjernst — APPROVED** [review]
Awesome, didn't know we had so few uses left. LGTM.

**Comment by original-brownbear** [comment]
Thanks Ryan!

**Pull request merged**
