### PR TITLE
[Profiling] Allow to wait until resources created

### PR DESCRIPTION
**Pull request by danielmitterdorfer**
With this commit we introduce a new request parameter `wait_for_resources_created` to the profiling status API. This parameter allows callers to wait until all profiling resources have been created (or the request times out). The default behavior remains the same (i.e. the API call returns immediately).

### CODE REVIEW

**Comment by danielmitterdorfer** [comment]
There was a test failure, caused by https://github.com/elastic/elasticsearch/issues/97795.

@elasticsearchmachine run elasticsearch-ci/part-1

**Comment by rockdaboot** [comment]
Code LGTM.
Can you add a step-by-step instruction on how to test the new API?

**Comment by danielmitterdorfer** [comment]
>  Can you add a step-by-step instruction on how to test the new API?

Sure, first the prior behavior is just to return immediately. So, this:

```
GET /_profiling/status
```

will return immediately regardless whether any resources have been created. If you just start an Elasticsearch build based on the code from this PR, e.g. with:

```
./gradlew :run -Drun.license_type=trial -Dtests.heap.size=4G --https
```

and then invoke:

```
GET /_profiling/status?wait_for_resources_created=true&timeout=20s&pretty
```

(or as curl: `curl -v -k -u elastic-admin:elastic-password "https://localhost:9200/_profiling/status?wait_for_resources_created=true&timeout=20s&pretty`) you'll notice that this call blocks for 20 seconds (`timeout`) and the call returns with HTTP 408 and:

```json
{
  "profiling" : {
    "enabled" : true
  },
  "resource_management" : {
    "enabled" : false
  },
  "resources" : {
    "created" : false,
    "pre_8_9_1_data" : false
  }
}
```

If you issue the call above again, but this time - while the blocking status check is running - issue:

```bash
curl -k -u elastic-admin:elastic-password -X PUT "https://localhost:9200/_cluster/settings?pretty" -H 'Content-Type: application/json' -d'
{
  "persistent": {
    "xpack.profiling.templates.enabled": true
  }
}
'
```

you should get HTTP 200 and the following response:

```json
{
  "profiling" : {
    "enabled" : true
  },
  "resource_management" : {
    "enabled" : true
  },
  "resources" : {
    "created" : true,
    "pre_8_9_1_data" : false
  }
}
```

**Comment by rockdaboot** [comment]
```
curl -k -u elastic-admin:elastic-password -X PUT "https://localhost:9200/_cluster/settings?pretty" -H 'Content-Type: application/json' -d'
{
  "persistent": {
    "xpack.profiling.templates.enabled": true
  }
}
'
```
always returns
```
{
  "acknowledged" : true,
  "persistent" : {
    "xpack" : {
      "profiling" : {
        "templates" : {
          "enabled" : "true"
        }
      }
    }
  },
  "transient" : { }
}
```
during the status request and after the status request finished.

**Comment by rockdaboot** [comment]
Ah sorry, I misunderstood what you said. Setting the cluster settings make the status call return immediately - and the response is what you said. That makes sense now 😄

**Review by rockdaboot — APPROVED** [review]
LGTM and works as expected.

**Comment by danielmitterdorfer** [comment]
Thanks for the review!

**Pull request merged**
