### PR TITLE
Remove ability to ingore files from spec validation

### PR DESCRIPTION
**Pull request by jakelandis**
An ignore parameter was originally added to the ValidateJsonAgainstSchemaTask 
to allow the build to pass for REST specs that did not properly validate 
against the schema.

Since the introduction of this task, all schemas that did not validate have 
been fixed to now validate properly.

This commit removes the ability to ignore specific files for validation. This 
allows any consumers the assurance that all REST specs validate against the schema.

### CODE REVIEW

**Comment by jakelandis** [comment]
cc: @elastic/es-clients

**Review by rjernst — APPROVED** [review]
LGTM

**Review by mark-vieira — APPROVED** [review]
Thanks for following up on this, Jake. 👍

**Comment by russcam** [comment]
Thanks @jakelandis 👍

**Comment by mark-vieira** [comment]
@jakelandis Can we remove the `backport pending` label now?

**Comment by jakelandis** [comment]
@mark-vieira - not yet. The backport PRs failed to pass.  I have a 7.x only PR that will fix them, but it is still under for review : https://github.com/elastic/elasticsearch/pull/56736

**Pull request merged**
