### PR TITLE
Tests: Make $_path support dots in paths

### LINKED ISSUE #28770: Fixing code snippet testing for attributes that contain a period
This issue is related to the instructions in  https://github.com/elastic/elasticsearch/blob/master/docs/README.asciidoc 

// TESTRESPONSE[s/"17179869184"/$body.$_path/] failed because it seemed to stumble over the periods in this code snippet:

```
[source,js]
----
{
  "count": 1,
  "datafeeds": [
    {
      "datafeed_id": "datafeed-total-requests",
      "state": "started",
      "node": {
        ...
        "attributes": {
          "ml.machine_memory": "17179869184",
          "ml.max_open_jobs": "20",
          "ml.enabled": "true"
        }
      },
      "assignment_explanation": ""
    }
  ]
}
----
```

The work-around is as follows:
TESTRESPONSE[s/"17179869184"/$body.datafeeds.0.node.attributes.ml\\.machine_memory/]

Ideally the code snippet testing would be better able to handle the periods.

### PR DESCRIPTION
**Pull request by nik9000**
`$_path` is used by documentation tests to ignore a value from a
response, for example:

```
[source,js]
----
{
  "count": 1,
  "datafeeds": [
    {
      "datafeed_id": "datafeed-total-requests",
      "state": "started",
      "node": {
        ...
        "attributes": {
          "ml.machine_memory": "17179869184",
          "ml.max_open_jobs": "20",
          "ml.enabled": "true"
        }
      },
      "assignment_explanation": ""
    }
  ]
}
----
// TESTRESPONSE[s/"17179869184"/$body.$_path/]
```

That example shows `17179869184` in the compiled docs but when it runs
the tests generated by that doc it ignores `17179869184` and asserts
instead that there is a value in that field. This is required because we
can't predict things like "how many milliseconds will this take?" and
"how much memory will this take?".

Before this change it was impossible to use `$_path` when any component
of the path contained a `.`. This fixes the `$_path` evaluator to
properly escape `.`.

Closes #28770

### CODE REVIEW

**Comment by nik9000** [comment]
Pinging @elastic/es-core-infra for review.

**Comment by nik9000** [comment]
I'm not sure which of the `:` labels to give this, so I'm going to stick it in `:core:core` so it doesn't get lost forever.

**Comment by rjernst** [comment]
perhaps we need a `:Core/Test` (ie test infrastructure) label.

**Comment by nik9000** [comment]
> perhaps we need a :Core/Test (ie test infrastructure) label.

I was thinking that but didn't want to unilaterally add it. I figured sticking it in `:Core:Core` would get attention. Bike shedding a bit, I think `:Core/Test Infrastructure` would be slightly more descriptive. It'd make it slightly less likely folks would assign the label for all test issues.

**Comment by rjernst** [comment]
That could be said for many labels under core. For example, `:Core/Settings` and `:Core/Logging`. I don't think we should add "infrastructure" to all these otherwise most of our labels will just be long with the same ending.

**Review by martijnvg — APPROVED** [review]
LGTM - Thanks for fixing!

**Comment by nik9000** [comment]
> perhaps we need a :Core/Test (ie test infrastructure) label.

A few of us (including @rjernst) discussed this over email and decided to move test issues into `:core/build` so we don't need a `:core/test`. As a bonus, I added descriptions to the `:core/*` labels to make them more obvious.

**Pull request merged**
