### PR TITLE
Refresh should not acquire readLock

### PR DESCRIPTION
**Pull request by dnhatn**
Today, we hold the engine readLock while refreshing. Although this choice simplifies the correctness reasoning, it can block IndexShard from closing if warming an external reader takes time. The current implementation of refresh does not need to hold readLock as ReferenceManager can handle errors correctly if the engine is closed in midway.

This PR is a prerequisite that we need to solve #47186.

Relates #47186

### CODE REVIEW

**Comment by dnhatn** [comment]
A known issue tracked at https://github.com/elastic/elasticsearch/issues/46021.

@elasticmachine run elasticsearch-ci/1

**Review by henningandersen — COMMENTED** [review]
This looks good to me, but not sure that counts for this issue. I did try to find a hole in the plot (and were unable to), but the other reviewers have the necessary historic background to do a qualified review.

Maybe also add a test to demonstrate that we do not hold the lock?

**Review by jpountz — APPROVED** [review]

**Comment by dnhatn** [comment]
> Maybe also add a test to demonstrate that we do not hold the lock?
+1. I added that test in https://github.com/elastic/elasticsearch/pull/48414/commits/37e1558c5e3b3cfafb863067cd2bf8d550298529.

**Review by ywelsch — APPROVED** [review]
LGTM. Can you hold off a bit (e.g. a week) to merge this into 7.5 branch (fine to merge to other branches). I would like to give this enough CI testing before it goes into our product.

**Comment by dnhatn** [comment]
@henningandersen @jpountz @ywelsch Thanks for reviewing.

**Comment by dnhatn** [comment]
> Can you hold off a bit (e.g. a week) to merge this into 7.5 branch (fine to merge to other branches).

+1

**Pull request merged**
