### PR TITLE
Promote the Data stream lifecycle feature to Technical Preview

### PR DESCRIPTION
**Pull request by andreidan**
This releases the Data stream lifecycle feature as a
Technical Preview feature. 

Data stream lifecycle, albeit in technical preview, will allow data streams 
to take advantage of a native simplified and resilient lifecycle implementation.

### CODE REVIEW

**Comment by andreidan** [comment]
@elasticmachine run elasticsearch-ci/part-3

**Review by masseyke — APPROVED** [review]
I worry that the "preview" links are a little too sublte, but otherwise looks good to me.

**Comment by andreidan** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by andreidan** [comment]
@masseyke Built the docs pages locally and the fonts look regular. I think it's the preview infrastructure that yields the pages a bit different.

**Pull request merged**
