### PR TITLE
Move CORS Config into :server package

### PR DESCRIPTION
**Pull request by Tim-Brooks**
This commit moves the config that stores Cors options into the server
package. Currently both nio and netty modules must have a copy of this
config. Moving it into server allows one copy and the tests to be in a
common location.

### CODE REVIEW

**Comment by tbrooks8** [comment]
@ywelsch  pointed out that https://github.com/elastic/elasticsearch/pull/42203 was a pretty large PR in terms of reviewing. This PR pulls out only the CORs config and keeps all the logic the same. A follow-up PR will look into fixing bugs and moving the handler into server.

**Review by ywelsch — APPROVED** [review]
Much better to review. LGTM

**Comment by tbrooks8** [comment]
@elasticmachine test this please

**Comment by tbrooks8** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample

**Comment by tbrooks8** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample

**Comment by tbrooks8** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample

**Comment by tbrooks8** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample

**Comment by jpountz** [comment]
@tbrooks8 I'm bumping it to 7.4 since this was merged after the branch has been cut.

**Pull request merged**
