### PR TITLE
Do not use hard-coded ports in tribe tests

### PR DESCRIPTION
**Pull request by jasontedor**
This commit addresses two collections of tribe node tests that were implicitly using hard-coded ports. Since no ports were specified (in particular, an ephemeral port was not specified) the tribe nodes would default to using the default port range of 9300--9304, effectively acting as if they are using hard-coded ports. If we were unfortunate enough to have these tests fail and the JVM is left sitting around, they could cause other tests that are expecting these ports to not be in use to fail. A follow-up will address the fact that these tests are trying to hit ports 9300, 9301, and 9302, but we will attempt to address that later as that seems like a much harder problem given that these are docs tests.

### CODE REVIEW

**Comment by jasontedor** [comment]
retest this please

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by jasontedor** [comment]
retest this please

**Comment by jasontedor** [comment]
test this please

**Pull request merged**
