### PR TITLE
removed 'days' as a valid time unit

### PR DESCRIPTION
**Pull request by forana**
Fixes https://github.com/elastic/beats/issues/8603

### CODE REVIEW

**Comment by danielmitterdorfer** [comment]
Thank you for your interest in Elasticsearch and you pull request. However, I do not think that this is the right approach to address elastic/beats#8603. From an Elasticsearch perspective, it is totally fine to specify a timeout in days and we do not want to remove any docs or support for that. Therefore I will close this PR.

**Comment by forana** [comment]
@danielmitterdorfer ...are you sure it's fine? Have a look at the linked issue - there's at least one situation where it isn't supported. I don't know the elastic stack's code well enough to know that it's _always_ `time.ParseDuration` that's used, but days aren't a supported unit for that.

**Comment by danielmitterdorfer** [comment]
I did have a look at that issue. You are talking about an issue in Beats and I think if it is addressed, it needs to be addressed there and not in Elasticsearch. We still want to support a timeout in days in Elasticsearch. If a system that depends on Elasticsearch does not support it, we will not narrow the range of supported values here but rather the system that depends on Elasticsearch needs to define whether it widens its range of supported values. I hope it makes sense now with this explanation?

**Comment by forana** [comment]
Got it. Thanks!

**Pull request closed without merging**
