### PR TITLE
Only the result of failed action is returned in Bulk response.

### PR DESCRIPTION
**Pull request by sinylei**
Is it possible to make the bulk api return the result only for failed actions?
i.e. the result of success actions is not returned in the response message.

I am writing a tool to create massive docs to es, and using bulk api. But I do not care the result for the docs those processed successfully by es. I only care about the docs created failed.

If the response only contain the failed docs(created failed), the tool will not check all response items and may get more fast and less network traffic.

### CODE REVIEW

**Comment by bleskes** [comment]
@sinylei thanks for the PR but I think something went wrong - you started working on the 6.3 branch rather then master, which made it huge. This should be changed so I can see the changes. That said please see the discussion at https://github.com/elastic/elasticsearch/issues/2661 where we decided not to do this - if you see anything new to add there, please do and we'll reconsider. Note that the performance argument has been considered already - I wouldn't use that unless you have concrete numbers to back you up.

**Comment by sinylei** [comment]
@bleskes I am not sure if the performance would get great improved by short return message, but I am sure it will save a lot of money paid for the network traffic when using in Cloud environment.
For most Cloud platform, the inbound traffic is free and only charge the outbound traffic.
When we deployed a cloud based ES system, and the clients call bulk api, for the cloud ES, the request from client is an inbound traffic, that is free, but the response to client is outbound traffic which needs to be paid at some rate.

**Comment by jbaiera** [comment]
It doesn't look like this PR is targeting the correct branches. I'm going to close this PR out so that updates to the 6.3 branch don't keep drowning out the conversation. As reported in #2661, there needs to be some concrete measured benefit for making this kind of change to the API. We are happy to look into it if there is compelling evidence.

**Comment by fenchu** [comment]
If you need an example look at your own bulk test: (which needs to be updated for 6.4):
[import data for Kibana](https://www.elastic.co/guide/en/kibana/3.0/import-some-data.html)

```
$ time curl -XPUT -H "Content-Type: application/json" http://elastic:9200/_bulk --data-binary "@shakespeare.json" &> out.log

real    0m5.359s
user    0m0.060s
sys     0m0.184s
$ grep -o "\"successful\":1" out.log | wc -l
110486
$ ls -l out.log
-rw-r--r-- 1 sensio sensio 21266955 Nov 13 08:31 out.log
```
21MB of response !!!. please supress this

**Pull request closed without merging**
