### PR TITLE
Add link to upgrading clusters to ccr

### LINKED ISSUE #47218: [DOCS] Document CCR compatibility requirements
### Context

(Courtesy of @jasontedor & @ppf2 in #47185. Thanks!)

CCR has a stricter compatibility requirement than remote clusters do.

The local cluster (the one that is pulling from the remote cluster) must be of a compatible version equal to or newer than the version of the remote cluster. The reason is the same as for allocation of replicas: the local cluster must be able to understand the Lucene segment files that are sent to it, as well as any index settings, mappings, etc.

### PR DESCRIPTION
**Pull request by erzz99**
fixes #47218. I added a link to the upgrading clusters page in the overview page.

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Review by jasontedor — CHANGES_REQUESTED** [review]
Thanks for picking his up @erzz99 although I don't think this is straightforward enough. I think it's making the user work too hard to understand the requirements here. On the one hand, we link to the remote clusters documentation about the versioning, which shows a compatibility matrix that implies a broad range of compatibility, and then we link to the upgrade docs which itself isn't even direct enough about version compatibility. A user then has to piece this information together to understand the version compatibility. I think we should be simple and direct and not link off to two pages to try to answer this question, a user shouldn't have to work so hard.

**Comment by jasontedor** [comment]
@erzz99 Are you interested in taking the PR to completion?

**Comment by erzz99** [comment]
Yes, I'll see it through.
Sorry for the late reply.

Best,
Erskine.

**Comment by jasontedor** [comment]
@erzz99 Just checking in to see if you can wrap this one up?

**Comment by ywelsch** [comment]
@jrodewig can you take this one over? Thank you

**Comment by jrodewig** [comment]
@ywelsch  Will do. Thanks for routing.

**Comment by jrodewig** [comment]
@erzz99 I'm going to close this PR and attempt to address #47218 via a separate PR.

**Pull request closed without merging**
