### PR TITLE
Move the IndexDeletionPolicy to be engine internal

### PR DESCRIPTION
**Pull request by bleskes**
The `IndexDeletionPolicy` is currently instantiated by `IndexShard` and is then passed through to the engine as a parameter. That's a shame as it is really just an implementation detail and the engine already has a method to acquire a commit.

This is preparing for a follow up PR that will we connect the index deletion policy with a new translog deletion policy.

Relates to #10708

### CODE REVIEW

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by bleskes** [comment]
Thx @jasontedor . I will give it a bit and backport.

**Comment by jasontedor** [comment]
My preference would be to leave the 5.x branches the same and to not backport this. This branch (master) is going to diverge from the backport anyway.

**Comment by bleskes** [comment]
Sure. I removed the 5.5.0 label.

**Pull request merged**
