### PR TITLE
Deduplicate the name of the aggregation when deserializing InternalAgregation

### PR DESCRIPTION
**Pull request by iverase**
In https://github.com/elastic/elasticsearch/pull/112707 we added infrastructure to deduplicate objects where deserailizing internal aggregations. Let' use it to deduplicate the names of InternalAgregation objects.

### CODE REVIEW

**Comment by iverase** [comment]
@elasticmachine update branch

**Comment by iverase** [comment]
@elasticmachine update branch

**Comment by iverase** [comment]
@elasticmachine update branch

**Review by not-napoleon — APPROVED** [review]
LGTM

**Pull request merged**
