### PR TITLE
Update geohash-cell-query.asciidoc

### PR DESCRIPTION
**Pull request by jjlin12**
sorry to be that guy

### CODE REVIEW

**Comment by jasontedor** [comment]
There's nothing to be sorry about, we appreciate these pull requests. However, can you please sign the CLA and please force push a new commit with a better commit message than "sorry to be that guy"?

**Comment by jjlin12** [comment]
@jasontedor If by "better" you mean, "change it to more accurately describe the commit", then yes.  Let's remember who's doing who a favor here.

**Comment by jjlin12** [comment]
@jasontedor done

**Comment by jasontedor** [comment]
> Let's remember who's doing who a favor here.

These sorts of comments help absolutely no one, especially since I doubt their veracity and their relevance to my request is zero.

**Comment by jasontedor** [comment]
Thank you for noticing and fixing this @jjlin12, your attention is appreciated.

**Pull request merged**
