### PR TITLE
Remove JWT realm feature flag.

### PR DESCRIPTION
**Pull request by justincr-elastic**

### CODE REVIEW

**Comment by justincr-elastic** [comment]
@elasticsearchmachine update branch

**Comment by justincr-elastic** [comment]
@elasticsearchmachine update branch

**Comment by justincr-elastic** [comment]
@elasticsearchmachine update branch

**Comment by justincr-elastic** [comment]
Strange Gradle 8.0 error. Retrying build.

**Comment by justincr-elastic** [comment]
@elasticmachine update branch

**Comment by justincr-elastic** [comment]
Convert to draft because #84740 is adding more usages of the feature flag. This PR #84845 will need to wait for the changes in PR #84740 to be merged.

**Comment by tvernum** [comment]
Is this ready for review? We need to move forward with this pretty soon.

**Comment by justincr-elastic** [comment]
@elasticmachine update branch

**Comment by justincr-elastic** [comment]
@elasticmachine update branch

**Comment by justincr-elastic** [comment]
It is ready for review.

**Review by albertzaharovits — APPROVED** [review]

**Comment by justincr-elastic** [comment]
Thank you.

**Pull request merged**
