### PR TITLE
Painless: encapsulate Struct logic

### PR DESCRIPTION
**Pull request by nik9000**
It feels like we should do this if we're going to support whitelist
nesting. We think we want whitelist nesting because the whitelists
take up a non-trivial amount of heap.

### CODE REVIEW

**Comment by nik9000** [comment]
@jdconrad do you think this is a useful direction or something we should avoid?

**Comment by rjernst** [comment]
I don't think we need whitelist nesting, and I think these structs should stay simple structs. We can share this information across Definition instances without nesting.

**Comment by nik9000** [comment]
@jdconrad and I talked about nesting definitions a while back because the definitions themselves take up a fair bit of space on the heap. I suppose we only need this kind of thing if we expect both to

**Comment by jdconrad** [comment]
I think we need a more structured plan, nesting or not.  The small steps seem unfocused at this point.  The plumbing PR made sense because no matter what a non-static Definition was going to have to be available everywhere.  Even with nesting this PR doesn't make sense to me because the only nesting that would need to occur is to get the actual structs which can be accomplished within the getType methods of Definition at the top level.  The two important goals to be accomplished are this 1) establish the ability to have independent whitelists per context
2) share as much as possible because the whitelist is a memory hog

**Pull request closed without merging**
