### PR TITLE
[ML]Fix the bug where the run() function of ExecutableInferenceRequest throws an exception when get inferenceEntityId.

### PR DESCRIPTION
**Pull request by Huaixinww**
when testing the inference api, we discovered that if `var inferenceEntityId = request.createHttpRequest().inferenceEntityId();` throws an exception, this exception won't be caught, so the listener.onFailure() function won't be called until timeout. This is because createHttpRequest() may validate some input parameters and throw an exception. I think we can get  the inferenceEntityId by request.getInferenceEntityId(). If there are other considerations here, please let me know.

### CODE REVIEW

**Review by davidkyle — COMMENTED** [review]
Thanks @Huaixinww this change is good.

I notice that the `AmazonBedrockRequest` class has a work around for this issue

https://github.com/elastic/elasticsearch/blob/52e591d6a61c5093535e683bdec1880ef671584f/x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/request/amazonbedrock/AmazonBedrockRequest.java#L44

Please can you update that comment and code. Something

```
    /**
     * Amazon Bedrock uses the AWS SDK, and will not create its own Http Request
     */
    @Override
    public final HttpRequest createHttpRequest() {
        throw new UnsupportedOperationException("Amazon Bedrock does not use Http Requests");
    }
```

**Comment by Huaixinww** [comment]
> Thanks @Huaixinww this change is good.
> 
> I notice that the `AmazonBedrockRequest` class has a work around for this issue
> 
> https://github.com/elastic/elasticsearch/blob/52e591d6a61c5093535e683bdec1880ef671584f/x-pack/plugin/inference/src/main/java/org/elasticsearch/xpack/inference/external/request/amazonbedrock/AmazonBedrockRequest.java#L44
> 
> Please can you update that comment and code. Something
> 
> ```
>     /**
>      * Amazon Bedrock uses the AWS SDK, and will not create its own Http Request
>      */
>     @Override
>     public final HttpRequest createHttpRequest() {
>         throw new UnsupportedOperationException("Amazon Bedrock does not use Http Requests");
>     }
> ```

ok, I'v updated this comment and code. Thank you!
Please let me know if there is anything else to add to this PR?

**Review by davidkyle — APPROVED** [review]
LGTM

Thank for this fix @Huaixinww

**Comment by mark-vieira** [comment]
@elasticsearchmachine generate changelog

**Comment by davidkyle** [comment]
@Huaixinww, CI failed because of a missing change log file. Usually that is created automatically but in this case I manually edited the file and pushed it to your branch

**Comment by Huaixinww** [comment]
> @Huaixinww, CI failed because of a missing change log file. Usually that is created automatically but in this case I manually edited the file and pushed it to your branch

@davidkyle thanks a lot!

**Comment by davidkyle** [comment]
@Huaixinww the CI tests have passed please merge the PR when you are ready. And thanks for your contribution.

**Comment by Huaixinww** [comment]
@davidkyle Thank you very much for your review! If you find it suitable, I would greatly appreciate it if you could merge it. Thank you again!

**Comment by davidkyle** [comment]
Thanks @Huaixinww I've merged into main and backported the fix to 8.15.2

**Pull request merged**
