### PR TITLE
Minor Code Performance Improvement

### PR DESCRIPTION
**Pull request by mosbat**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against main? Unless there is a good reason otherwise, we prefer pull requests against main and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/main/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by mosbat** [comment]
#115969

**Comment by thecoop** [comment]
Many thanks for your interest in Elasticsearch.

Whilst we appreciate the work, as given in our contributing guidelines, we generally do not accept arbitrary improvements such as this PR, especially over such a large set of files. This is too many for us to review appropriately.

As such, I'll close this PR.

**Comment by mosbat** [comment]
> Many thanks for your interest in Elasticsearch.
> 
> Whilst we appreciate the work, as given in our contributing guidelines, we generally do not accept arbitrary improvements such as this PR, especially over such a large set of files. This is too many for us to review appropriately.
> 
> As such, I'll close this PR.

I went through the contributor guidelines but no mention of how I can raise this issue. Can you please help me maybe with a hint or what would be appropriate?

Despite the large number of files, the changes are actually quite straightforward and obvious ...

**Comment by rjernst** [comment]
From CONTRIBUTING.md:

```
We normally immediately reject isolated PRs that only perform simple refactorings or otherwise "tidy up" certain aspects of the code. We think the benefits of this kind of change are very small, and in our experience it is not worth investing the substantial effort needed to review them. This especially includes changes suggested by tools.
```

> Despite the large number of files, the changes are actually quite straightforward and obvious

It still takes time. This PR is massive, over 1500 lines. There is not a single type of change, but many different types (method replacement, import tweaks, etc). While the changes may be straightforward, they are not quick to review.

If you want to contribute to Elasticsearch, we suggest looking through open issues marked with the `Good First Issue` label.

**Pull request closed without merging**
