### PR TITLE
Close TokenStream in finally clause

### LINKED ISSUE #11947: Use of pre and post filters throws "TokenStream contract violation: close() call missing"
This happens when using the standard analyzer as a pre and post filter after a direct candidate generator (ES 1.6). When this query was run in a multi-node environment, the error seemed to persist and required a rolling restart.  For example: 

```json
{ "suggest" : {
    "text" : "pizeo",
    "simple_phrase" : {
      "phrase" : {
        "analyzer" : "english",
        "field" : "synopses",
        "direct_generator" : [ {
          "field" : "synopses",
          "suggest_mode" : "always",
          "min_word_length" : 1
        }, {
          "field" : "synopses",
          "suggest_mode" : "always",
          "min_word_length" : 1,
          "pre_filter" : "standard",
          "post_filter" : "standard"
        } ]
      }
    }
  }
}
```
Will throw this error:
```json
{
   "took": 21,
   "timed_out": false,
   "_shards": {
      "total": 4,
      "successful": 1,
      "failed": 3,
      "failures": [
         {
            "index": "project",
            "shard": 0,
            "status": 500,
            "reason": "IllegalStateException[TokenStream contract violation: close() call missing]"
         },
         {
            "index": "project",
            "shard": 2,
            "status": 500,
            "reason": "IllegalStateException[TokenStream contract violation: close() call missing]"
         },
         {
            "index": "project",
            "shard": 3,
            "status": 500,
            "reason": "IllegalStateException[TokenStream contract violation: close() call missing]"
         }
      ]
   },
   "suggest": {
      "simple_phrase": [
         {
            "text": "pizo",
            "offset": 0,
            "length": 4,
            "options": []
         }
      ]
   }
}
```

[2015-06-30 10:16:05,888][DEBUG][action.search.type       ] [Wiz Kid] [project][0], node[OhG1Vc65RPyjCcSlXDbCJQ], [P], s[STARTED]: Failed to execute [org.elasticsearch.action.search.SearchRequest@7bd06ad7] lastShard [true]
java.lang.IllegalStateException: TokenStream contract violation: close() call missing
	at org.apache.lucene.analysis.Tokenizer.setReader(Tokenizer.java:90)
	at org.apache.lucene.analysis.Analyzer$TokenStreamComponents.setReader(Analyzer.java:323)
	at org.apache.lucene.analysis.standard.StandardAnalyzer$1.setReader(StandardAnalyzer.java:133)
	at org.apache.lucene.analysis.Analyzer.tokenStream(Analyzer.java:147)
	at org.elasticsearch.search.suggest.SuggestUtils.analyze(SuggestUtils.java:119)
	at org.elasticsearch.search.suggest.SuggestUtils.analyze(SuggestUtils.java:115)
	at org.elasticsearch.search.suggest.phrase.DirectCandidateGenerator.preFilter(DirectCandidateGenerator.java:133)
	at org.elasticsearch.search.suggest.phrase.DirectCandidateGenerator.frequency(DirectCandidateGenerator.java:92)
	at org.elasticsearch.search.suggest.phrase.DirectCandidateGenerator$2.nextToken(DirectCandidateGenerator.java:155)
	at org.elasticsearch.search.suggest.SuggestUtils.analyze(SuggestUtils.java:130)
	at org.elasticsearch.search.suggest.SuggestUtils.analyze(SuggestUtils.java:122)
	at org.elasticsearch.search.suggest.SuggestUtils.analyze(SuggestUtils.java:115)
	at org.elasticsearch.search.suggest.phrase.DirectCandidateGenerator.postFilter(DirectCandidateGenerator.java:148)
	at org.elasticsearch.search.suggest.phrase.DirectCandidateGenerator.drawCandidates(DirectCandidateGenerator.java:122)
	at org.elasticsearch.search.suggest.phrase.MultiCandidateGeneratorWrapper.drawCandidates(MultiCandidateGeneratorWrapper.java:52)
	at org.elasticsearch.search.suggest.phrase.NoisyChannelSpellChecker.getCorrections(NoisyChannelSpellChecker.java:116)
	at org.elasticsearch.search.suggest.phrase.PhraseSuggester.innerExecute(PhraseSuggester.java:98)
	at org.elasticsearch.search.suggest.phrase.PhraseSuggester.innerExecute(PhraseSuggester.java:54)
	at org.elasticsearch.search.suggest.Suggester.execute(Suggester.java:43)
	at org.elasticsearch.search.suggest.SuggestPhase.execute(SuggestPhase.java:85)
	at org.elasticsearch.search.suggest.SuggestPhase.execute(SuggestPhase.java:74)
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:170)
	at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:289)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:300)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
	at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

### PR DESCRIPTION
**Pull request by mikemccand**
We have a couple places where we might fail to close a `TokenStream` on exception ...

Maybe closes #11947

### CODE REVIEW

**Comment by dakrone** [comment]
LGTM, would be great if we had a nice mock token stream thingy that could keep track of the open streams like we do for thread leaks and unclosed contexts :)

**Comment by johtani** [comment]
Are there same issues?
https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/search/highlight/PlainHighlighter.java#L112
https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/apache/lucene/queryparser/classic/MapperQueryParser.java#L490
https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/apache/lucene/queryparser/classic/MapperQueryParser.java#L621

**Comment by rmuir** [comment]
> LGTM, would be great if we had a nice mock token stream thingy that could keep track of the open streams like we do for thread leaks and unclosed contexts :)

We have MockTokenizer in lucene for this.

**Comment by mikemccand** [comment]
Thanks @johtani, I pushed a few more commits to fix those and some additional places.

I changed a few private APIs to take Analyzer + field + contents, instead of TokenStream, so I could use try-with-resources.

I had to push the close back down into `SuggestUtils.analyze` for a crazy case where the suggester consumed a token stream but recursed on itself and would then try to illegally reuse the same `TokenStream` instance again (while still iterating that `TokenStram` up above).  So the high-level try-with-resources did the close "too late".

**Comment by johtani** [comment]
LGTM

**Pull request merged**
