### PR TITLE
Add validation for empty PutPrivilegeRequest

### PR DESCRIPTION
**Pull request by jkakavas**
Return an error to the user if the put privilege api is called with
an empty body (no privileges)

Resolves: #37561

### CODE REVIEW

**Comment by tvernum** [comment]
I haven't reviewed the code yet, but I would argue that this isn't a serious enough bug to include in a patch release.
I don't think we should backport to `6.6.1`

**Review by tvernum — APPROVED** [review]
LGTM for 6.7 and 7.0
If you're still keen to backport to 6.6.1, then let's discuss.

**Comment by jkakavas** [comment]
> I would argue that this isn't a serious enough bug

Agreed, hence the `>non-issue` label

> serious enough bug to include in a patch release.
> I don't think we should backport to 6.6.1

I don't have a strong opinion on the matter. I thought we, as a general practice, add all bug fixes to the next patch release - no matter the severity, so I went about it as I would for any other PR.

**Comment by jkakavas** [comment]
```
11:10:36 Tests with failures:
11:10:36   - org.elasticsearch.discovery.DiscoveryDisruptionIT.testUnicastSinglePingResponseContainsMaster
11:10:36 
```

run the gradle build tests 1

**Pull request merged**
