### PR TITLE
Correcting a minor typo

### PR DESCRIPTION
**Pull request by sandeepkanabar**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by nik9000** [comment]
LGTM. I'll see about merging this.

**Comment by nik9000** [comment]
Thanks for fixing this @sandeepkanabar! I've merged to 6.3 and forward ported to 6.4, 6.x, and master.

**Comment by sandeepkanabar** [comment]
Thanks Nik.

Won't it need to be back-ported to 5.x versions?

**Comment by sandeepkanabar** [comment]
@nik9000 - won't it need to be back-ported to 5.x versions?

**Comment by nik9000** [comment]
We don't tend to backport minor docs changes all the way back, no. I *love* having the docs tied to a specific version but it does create this question of "how far do you backport?" and we've mostly settled on "not that far".

**Comment by sandeepkanabar** [comment]
Thanks @nik9000  for the clarification. Makes sense.

**Pull request merged**
