### PR TITLE
Enum related performance additions.

### PR DESCRIPTION
**Pull request by KoenDG**
This very small PR is related to issue #24226 it is small exactly to keep it readable. I could make a giant PR with changes and then nobody would read it due to the size. Which reminds me to ping @jprante

This PR focusses on constructs that have been introduced to Java in the past to optimize working with Enums. Particularly:

1. EnumMap: https://docs.oracle.com/javase/8/docs/api/java/util/EnumMap.html

2. EnumSet: https://docs.oracle.com/javase/8/docs/api/java/util/EnumSet.html

These classes are **always** faster in execution and smaller in memory footprint than their regular Map/Set counterparts, as is described in their respective documentation pages.

===========

1. Contributor agreement: I signed it and then nothing happened. The site redirected me to https://www.elastic.co/contributor-agreement?license=icla which is an empty page.

2. Contributor guidelines: I have read them.

3. Gradle check: build successful.

4. PR is against master

5. The PR is not OS specific.

6. I'm not part of a class.

### CODE REVIEW

**Comment by s1monw** [comment]
@elasticmachine ok to test

**Comment by s1monw** [comment]
@KoenDG can you sign the CLA for this?

**Comment by KoenDG** [comment]
@s1monw As stated in the PR, I've tried this URL: https://www.elastic.co/contributor-agreement

Signing as an individual contributor, but it takes me to an empty page. Is there another URL? Do I need to be logged in? Is the CLA actually on github?

After signing, I see this: http://i.imgur.com/tnd0QRB.png

What am I missing?

**Comment by s1monw** [comment]
> What am I missing?

it renders the right page for me maybe try a different browser? I don't know looks like its working for anybody else so far?!

**Comment by KoenDG** [comment]
@s1monw Signed. I'm going assume one of my Chrome plugins was messing things up, since it worked in Edge.

**Comment by s1monw** [comment]
@KoenDG thanks for the PR

**Pull request merged**
