### PR TITLE
Remove the ability to enable doc values with the `fielddata.format` setting.

### PR DESCRIPTION
**Pull request by jpountz**
Doc values can now only be enabled by setting `doc_values: true` in the
mappings. Removing this feature also means that we can now fail mapping updates
that try to disable doc values.

### CODE REVIEW

**Comment by rjernst** [comment]
Great change, +1! I think we can do even better as a followup by removing the doc values as a boolean, since field type already has docvalues type?

**Comment by jpountz** [comment]
Agreed this would simplify...

**Comment by jpountz** [comment]
Fixed via 2aaa5e6448fb96dd80c37827b292592d607398bc

**Comment by ppf2** [comment]
I just saw a mapping file out there in production that has fielddata.format set to doc_values.  By removing this option entirely, will this be a breaking change?  If so, can we add the tagging so we can also document this in the breaking changes doc for 5.0?

**Comment by jpountz** [comment]
@ppf2 This is breaking in the sense that for new indices you will have to use `doc_values: true` instead. However it is backward compatible: existing 2.x indices that use fielddata.format=doc_values will keep working on 5.0.

**Comment by ppf2** [comment]
@jpountz ok thx for clarifying!

**Pull request closed without merging**
