### PR TITLE
Expose index age in ILM explain output

### LINKED ISSUE #38988: ILM: Including "aging" information in Explain lifecycle API
6.6.0

I can see this feature being useful for admins in the field.

Imagine an admin is not seeing indices getting deleted from the cluster per their ILM policy and are wondering how much longer is left on the clock before ILM will consider the indices meeting the "age" requirement for deletion.

Currently, we have this information in the TRACE logging level

```
checking for index age to be at least [20m] before performing actions in the "delete" phase. Now: 1550263112, lifecycle date: 1550262751, age: [6m/360s]
```

It will be helpful to include this in the explain lifecycle API output as well (i.e., how much time is left before it will attempt to execute the next action without requiring admins to do their own time calculations) so that enabling trace logging is not necessary.

### PR DESCRIPTION
**Pull request by dakrone**
This adds the index's age to the ILM explain output, for example:

```
{
  "indices" : {
    "ilm-000001" : {
      "index" : "ilm-000001",
      "managed" : true,
      "policy" : "full-lifecycle",
      "lifecycle_date" : "2019-07-16T19:48:22.294Z",
      "lifecycle_date_millis" : 1563306502294,
      "age" : "1.34m",
      "phase" : "hot",
      "phase_time" : "2019-07-16T19:48:22.487Z",
      ... etc ...
    }
  }
}
```

This age can be used to tell when ILM will transition the index to the
next phase, based on that phase's `min_age`.

Resolves #38988

### CODE REVIEW

**Comment by dakrone** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by dakrone** [comment]
@elasticmachine test this

**Comment by dakrone** [comment]
@elasticmachine retest this please

**Comment by dakrone** [comment]
@elasticmachine update branch

**Comment by dakrone** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by dakrone** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample

**Review by jbaiera — APPROVED** [review]
LGTM

**Pull request merged**
