### PR TITLE
Introduce the dissect library

### PR DESCRIPTION
**Pull request by jakelandis**
The dissect library will be used for the ingest node as an alternative
to Grok to split a string based on a pattern. Dissect differs from
Grok such that regular expressions are not used to split the string.
Note - Regular expressions are used during construction of the
objects, but not in the hot path.

A dissect pattern takes the form of: '%{a} %{b},%{c}' which is
composed of 3 keys (a,b,c) and two delimiters (space and comma).
This dissect pattern will match a string of the form: 'foo bar,baz'
and will result a key/value pairing of 'a=foo, b=bar, and c=baz'.
See the comments in DissectParser for a full explanation.

This commit does not include the ingest node processor that will consume
it. However, the consumption should be a trivial mapping between the
key/value pairing returned by the parser and the key/value pairing
needed for the IngestDocument.

-----------

Note to reviewer(s) - 
* The the ingest node processor that consumes this will be submitted soon. 
* I have not performed performance testing/optimization on this yet, however, I am pretty confident that as-is it will be faster then Grok, but will get some numbers to back that claim.
* Functionality is based on the [Logstash dissect plugin](https://www.elastic.co/guide/en/logstash/master/plugins-filters-dissect.html), however (mostly) due to tight coupling with [Logstash specific code](https://github.com/logstash-plugins/logstash-filter-dissect/tree/master/src/main/java) this implementation does not share any code with Logstash. 
* The Logstash unit tests have been manually ported here as 'testLogstashSpecs'.  The tests most generally passed without any modification, however there are some edge case differences between the implementations that may require further discussion. The test has comments to the differences. 

cc: @guyboertje @ph

### CODE REVIEW

**Comment by jakelandis** [comment]
Changing this PR to a WIP. Running some micro benchmarks shows some potential performance issue in the code, in particular with the match validation (intersection of two lists)  and post processing (grouping and sorting).

**Comment by jakelandis** [comment]
Removed the WIP.  This is ready for review. 

@guyboertje - can you please validate the main logic (there is a test that mirrors logstash specs)
@rjernst - could you also review

**Comment by jakelandis** [comment]
I removed the 6.5.0 label from this PR, since the 6.5.0 will require a fork of this PR that implements slightly different rules. After speaking with @ph (beats) and @guyboertje (logstash) the 7.x goal is for stricter compliance to a newly formalized dissect specification. The 6.x goal is for approximate like for like behavior between the 3 products. 

This means that the 7.x will be a breaking change to the 6.x, hence the breaking tag. 

Specifically, the breaking change will be:
* disambiguate the meaning of `?` - 6.x it can be either a named skip key or the key of the reference (indirect) key/value pair (`?` paired with an `&`)
    * `?` has been replaced by `*` for key/value reference pairing (formerly `?` and `&` pairs, now `*` and `&` pairs). 
    * key/value reference pairings `*` and `&` (formerly `?` and `&`) are required to come in pairs.

**Review by rjernst — APPROVED** [review]
This looks ok from the build side. One general comment is I see a lot of package private methods. If they need to be package private for tests that is fine, but please note this with a comment like `// pkg private for tests` or something like that. Otherwise, please use the least visibility possible.

**Comment by jakelandis** [comment]
@rjernst - thanks , will add package private comments (or reduce scope if possible)

@guyboertje - could you please review ?

**Review by guyboertje — APPROVED** [review]
LGTM

**Comment by jakelandis** [comment]
@guyboertje @rjernst  thanks! 

reduced scope where possible in https://github.com/elastic/elasticsearch/pull/32297/commits/9e43ba86006b77535f3fb8d104f1010176670b3d 

will merge when CI is green.

**Comment by jakelandis** [comment]
Jenkins test this please

**Comment by jakelandis** [comment]
Removing the breaking label ... after further discussion it preferred to have a minor difference between ingest/Logstash/Beats in the 6.x instead of a breaking change in ES. 

I will backport this PR as-is to 6.x (ignore any comments above about breaking changes).

**Pull request merged**
