### PR TITLE
Update RestClientDocumentation.java

### PR DESCRIPTION
**Pull request by wangzhenhui1992**
Refer to an inner class as an inner class in the documentation so it is easier to read.

Issue: #34700

### CODE REVIEW

**Comment by javanna** [comment]
test this please

**Comment by wangzhenhui1992** [comment]
> test this please
@javanna
Thank you for reminding.
But this class is just used to show the snippets in document and I could not find a test class of it.
Did you mean that I need add one?

**Comment by wangzhenhui1992** [comment]
> 17:44:50 [ant:checkstyle] [ERROR] /var/lib/jenkins/workspace/elastic+elasticsearch+pull-request/client/rest/src/test/java/org/elasticsearch/client/documentation/RestClientDocumentation.java:81: Code snippets longer than 76 characters get cut off when rendered in the docs [SnippetLength]
> 17:44:50 > Task :client:rest:checkstyleTest FAILED
> 17:44:50 
> 17:44:50 FAILURE: Build failed with an exception.

It seems that something wrong with the Code snippet length in RestClientDocumentation.java,
Java class format is according to [java-language-formatting-guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#java-language-formatting-guidelines).
I'm thinking of submiting an issue to add a rule of Java classfor code snippet .
Or someone fixes the CI scripts.

**Comment by javanna** [comment]
hi @wangzhenhui1992 sorry about the confusion, "test this please" is a comment to trigger a build through our jenkins bot :) 

The build failed because of a style check, as the line is now too long and would not be nicely displayed in our docs. The problem is that `HttpAsyncResponseConsumerFactory.HeapBufferedResponseConsumerFactory` is too long alone to fit nicely in our docs. I wonder if we should not make this change then. Thoughts @nik9000 ?

**Comment by wangzhenhui1992** [comment]
@javanna @nik9000 
What about defining `30 * 1024 * 1024 * 1024` as an variable named `size` and it will go like this?
```
 private static final RequestOptions COMMON_OPTIONS;
static {
    RequestOptions.Builder builder = RequestOptions.DEFAULT.toBuilder();
    builder.addHeader("Authorization", "Bearer " + TOKEN); 
    int size = 30 * 1024 * 1024 * 1024;
    builder.setHttpAsyncResponseConsumerFactory(           
        new HttpAsyncResponseConsumerFactory.HeapBufferedResponseConsumerFactory(size));
    COMMON_OPTIONS = builder.build();
}
```
And another one : Adding a return code before `30 * 1024 * 1024 * 1024` like below
```
 private static final RequestOptions COMMON_OPTIONS;
static {
    RequestOptions.Builder builder = RequestOptions.DEFAULT.toBuilder();
    builder.addHeader("Authorization", "Bearer " + TOKEN); 
    builder.setHttpAsyncResponseConsumerFactory(           
        new HttpAsyncResponseConsumerFactory.HeapBufferedResponseConsumerFactory(
            30 * 1024 * 1024 * 1024));
    COMMON_OPTIONS = builder.build();
}
```

**Comment by wangzhenhui1992** [comment]
test this please

**Comment by javanna** [comment]
retest this please

**Comment by wangzhenhui1992** [comment]
retest this please

**Comment by wangzhenhui1992** [comment]
Can I trigger it ?

**Comment by javanna** [comment]
retest this please

**Comment by hub-cap** [comment]
@wangzhenhui1992 only people in the elastic organization can trigger a test build. We are happy to do it for you :)

**Comment by javanna** [comment]
hi @wangzhenhui1992 would you mind merging master in? Sorry for the trouble, I think some of the failures we are getting here are due to problems that have now been solved on master.

**Comment by nik9000** [comment]
Sorry about not commenting earlier. The change is fine with me so long as the line length checker likes it. We really don't have much room on those snippets.

**Comment by wangzhenhui1992** [comment]
> @wangzhenhui1992 only people in the elastic organization can trigger a test build. We are happy to do it for you :)

Thank you

**Comment by wangzhenhui1992** [comment]
> Sorry about not commenting earlier. The change is fine with me so long as the line length checker likes it. We really don't have much room on those snippets.

Thank you

**Comment by wangzhenhui1992** [comment]
> hi @wangzhenhui1992 would you mind merging master in? Sorry for the trouble, I think some of the failures we are getting here are due to problems that have now been solved on master.

@javanna  Of course OK. Let me have a try and then I will mention you with the PR.

**Comment by javanna** [comment]
Closed in favour of #34834

**Pull request closed without merging**
