### PR TITLE
SCRIPTING: Move terms_set Context to its Own Class

### PR DESCRIPTION
**Pull request by original-brownbear**
* Extracted TermsSetQueryScript
* Kept mechanics close to what they were with SearchScript

### CODE REVIEW

**Review by rjernst — COMMENTED** [review]
Thanks @original-brownbear. This looks good, except that it is missing backcompat, which I think is important. Eg `doc` can be accessed through `params.doc`. We need a way to detect and deprecate these uses. The current idea @jdconrad and I have discussed is a wrapper Map around `params` that also takes in a set of keys that are deprecated, and the deprecation logger. Then on `get` calls, the deprecated set can be checked. We could reuse this wrapper Map for converting the other script uses to contexts as well.

**Comment by rjernst** [comment]
We could theoretically *not* have backcompat for `params.doc` when that use is not documented. For example, we could use this PR as is, but would still need it for minimum should match scripts because they have special values passed in by the script execution in `params`, which we need to add as variables in the new context and deprecate their use through params. I would be ok with this, if we get at least a loose consensus from the group first.

**Comment by original-brownbear** [comment]
@rjernst 

> The current idea @jdconrad and I have discussed is a wrapper Map around params that also takes in a set of keys that are deprecated, and the deprecation logger. Then on get calls, the deprecated set can be checked. We could reuse this wrapper Map for converting the other script uses to contexts as well.

Jup, the two of us discussed this too on Friday :) I'm fine adding an implementation of this here, it's really not that hard to implement and gives us a general solution to the problem. => go ahead an implement here? :)

**Comment by rjernst** [comment]
Sure, here is great!

**Comment by original-brownbear** [comment]
@rjernst done, let me know what you think about the approach of passing a map of keys to deprecation messages. I kinda liked this because it would give us a natural way of handling various messages where we want to give additional context like e.g. https://github.com/elastic/elasticsearch/blob/79375d35bbfdfcd380049cbc59d259fc31102d00/server/src/main/java/org/elasticsearch/action/update/UpdateHelper.java#L293

**Review by rjernst — APPROVED** [review]
LGTM, but I wonder if the map to a full message is needed, or if we could just have the new variable name that should be used. This way the messages can be consistent for params deprecations.

**Pull request merged**
