### PR TITLE
More pipeline aggregation cleanup

### PR DESCRIPTION
**Pull request by nik9000**
This replaces the last bit of validation that pipeline aggregations
performed on the data nodes with explicit checks in a few
`PipelineAggregationBuilders`. We were *already* catching these
validation errors for pipeline aggregations that require that their
parent be sequentially ordered. This just adds validation for pipelines
that require *any* parent like `bucket_selector` and `bucket_sort`.

### CODE REVIEW

**Comment by nik9000** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample-matrix-unix

**Comment by nik9000** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample-unix  and run  elasticsearch-ci/packaging-sample-matrix-unix

**Comment by nik9000** [comment]
@elasticmachine, test this please

**Review by polyfractal — APPROVED** [review]
And there was much rejoicing. :tada:

**Comment by nik9000** [comment]
Thanks @polyfractal!

**Pull request merged**
