### PR TITLE
Some community plugins appear to be outdated

### PR DESCRIPTION
**Pull request by bastbnl**
Added a paragraph which still contains the plugins, but added a description showing the plugins are available for version 5 and earlier

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by javanna** [comment]
can somebody @elastic/es-docs have a look at this please?

**Comment by jrodewig** [comment]
Thanks for your contribution @bastbnl.

It looks like this PR is on the version 6.6 branch, which is no longer supported. I can make an exception here, but generally we avoid making changes to documentation past their support lifecycle.

It also looks like several of these links are still present in our master and current documentation. In those cases, it may make more sense to simply remove the links.

**Review by jrodewig — CHANGES_REQUESTED** [review]
Let's remove these links rather than point out their no longer supported.

**Comment by bastbnl** [comment]
Thanks for getting back @jrodewig. Do you want me to do the same for master?

**Review by jrodewig — APPROVED** [review]

**Comment by jrodewig** [comment]
@bastbnl Sure. I'll forwardport this as needed. Thank you again for your contribution.

**Pull request merged**
