### PR TITLE
Dry up Empty ActionResponse Implementations

### PR DESCRIPTION
**Pull request by original-brownbear**
No need to have multiple empty action response implementations.
=> Use a single class and singleton for all of them like we do for
empty flat transport responses.

Similar to e.g. https://github.com/elastic/elasticsearch/pull/63335

### CODE REVIEW

**Comment by original-brownbear** [comment]
Jenkins test this

**Comment by original-brownbear** [comment]
Jenkins test this

**Comment by original-brownbear** [comment]
Jenkins test this

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/2

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by original-brownbear** [comment]
Thanks Ryan!

**Pull request merged**
