### PR TITLE
Fixed very small typo in date in documentation

### PR DESCRIPTION
**Pull request by jashgala**
Replaced `22rd` with `22nd` inline.
Simple as that :)

### CODE REVIEW

**Comment by dliappis** [comment]
@lcawl I think this could be back ported way back, feel free to adjust labels as needed.

**Comment by dliappis** [comment]
@elasticmachine test this please

**Review by jrodewig — APPROVED** [review]
LGTM.

Thanks @jashgala and @dliappis! I'll go ahead and merge this. Will take of the backports too.

**Comment by jashgala** [comment]
Thanks!

**Pull request merged**
