### PR TITLE
Fix typo in Rectangle() error message

### PR DESCRIPTION
**Pull request by mhogeweg**
line 73 said: 'max y cannot be less than min x', while this should be 'min y'

### CODE REVIEW

**Review by jrodewig — APPROVED** [review]
LGTM, but I'll defer to @imotov for final approval.

**Comment by jrodewig** [comment]
@elasticmachine ok to test

**Comment by jrodewig** [comment]
@elasticmachine update branch

**Comment by imotov** [comment]
@elasticmachine test this please

**Review by imotov — APPROVED** [review]
Good catch! LGTM.

**Pull request merged**
