### PR TITLE
ESQL: Add block factory to GROK command

### PR DESCRIPTION
**Pull request by luigidellaquila**
Add DriverContext and BlockFactory to GROK command to properly handle circuit breaking
See https://github.com/elastic/elasticsearch/issues/99826

### CODE REVIEW

**Review by nik9000 — APPROVED** [review]
Could you update the tests in `ColumnExtractOperatorTests#smallEnoughToCircuitBreak`. 

It'd also be cool if you could double check that the CrankyBreaker causes failures that we clean up correctly. I'd try commenting out your `Release` call of the builder and rerunning the tests.

**Comment by luigidellaquila** [comment]
Thanks Nik, I checked and I can confirm that the breaker causes failures if we don't close/clean up components correctly.

**Comment by luigidellaquila** [comment]
@elasticmachine run elasticsearch-ci/part-2

**Comment by luigidellaquila** [comment]
@elasticmachine update branch

**Pull request merged**
