### PR TITLE
[ingest] Don't do DNS lookups from GeoIpProcessor

### PR DESCRIPTION
**Pull request by rmuir**
There is no need to involve DNS in this!

### CODE REVIEW

**Comment by bleskes** [comment]
Lgtm. Good catch.

**Comment by s1monw** [comment]
grrrr... can we make this a forbidden API and only use it where it's justified / suppressed for a reason?

**Comment by bleskes** [comment]
++

**Comment by martijnvg** [comment]
+1 to remove

I thought it would be useful for cases hostnames are provided instead of ip addresses. Although this is maybe unlikely, I thought it would help.

**Comment by martijnvg** [comment]
and in the case just an ip address is provided no actual dns lookup is being done.

**Comment by rmuir** [comment]
If the user has data with hostnames, they have a real problem on their hands to resolve these in any efficient way, we can't do it "on the side".

Using InetAddress is not a good solution, it will result in memory leaks (we must assume each host is cached infinitely). In general with any massive use of DNS (via InetAddress, JNDI, etc) we have to worry about craziness like exhaustion of entropy on the machine (securerandom is used for DNS port randomization to "help" address spoofing), bogus data (e.g. NXDOMAIN hijacking), tons of network traffic, throttling, triggering alarms, etc.

I am aware that doing DNS operations on millions of log records, etc is sometimes something people want. But DNS is a very complex serious beast, its definitely a distributed database query, and should always be explicit. Doing it for lots of data is even more complicated if you want it to be anywhere near correct or efficient.

**Comment by rmuir** [comment]
> and in the case just an ip address is provided no actual dns lookup is being done.

Right, my specific concern is right now it will silently do tons of DNS in cases where an ip address is not provided, e.g. `HostNameLookups On` (http://httpd.apache.org/docs/2.4/mod/core.html#hostnamelookups). We should fail rather than silently be slow in this case!

**Comment by martijnvg** [comment]
Thanks for the explanation. I underestimated the slowness / costs here. LGTM

**Comment by martijnvg** [comment]
like @s1monw suggested, we should make this is a forbidden api.

**Comment by rmuir** [comment]
I'll followup with a forbidden api patch for master. I'm concerned about false positive rate, but I totally agree with the trap (esp. considering the trappiness of InetAddress here, which is why @jasontedor added a parsing method that doesn't go to DNS).

**Pull request merged**
