### PR TITLE
Fix serialization of put/delete shutdown requests

### LINKED ISSUE #107857: `PutShutdownNodeAction.Request` does not preserve parent task or timeouts on the wire
`PutShutdownNodeAction.Request` is an `AcknowledgedRequest` whose transport-protocol representation therefore should start with the parent task ID followed by the `?masterNodeTimeout` and `?timeout` parameters. However we do not call the superclass `writeTo()` method when serializing it so these fields are omitted, and therefore we end up with the default 30s timeouts (and no parent task ID) on a remote master node.

### PR DESCRIPTION
**Pull request by DaveCTurner**
Closes #107857

### CODE REVIEW

**Review by ldematte — APPROVED** [review]
LGTM

**Comment by thecoop** [comment]
8.13 and 8.14 backports are https://github.com/elastic/elasticsearch/pull/108250 and https://github.com/elastic/elasticsearch/pull/108251 respectively. Note the interdependent uses of the 8.13 and 8.14 transport patch versions

**Comment by ldematte** [comment]
Still good after the backports

**Comment by thecoop** [comment]
@elasticmachine update branch

**Pull request merged**
