### PR TITLE
SQL: Add `CAST` and `CONVERT` to `SHOW FUNCTIONS`

### PR DESCRIPTION
**Pull request by matriv**
Fixes: #34939

### CODE REVIEW

**Comment by matriv** [comment]
retest this please

**Comment by matriv** [comment]
@bpintea I've chosen to show `CAST` and `CONVERT` with type: `DATA_TYPE_CONVERSION` instead of `SCALAR` as most DBs list `CAST` in a different section than scalar functions. What do you think? Is it ok for ODBC, or should I list them as `SCALAR` ?

**Review by costin — COMMENTED** [review]
I would stick with `SCALAR` since essentially that's what they are doing. `DATA_TYPE_CONVERSION` is a long description (with underscores) and I'm not sure what are the expected grouping names.

**Review by astefan — APPROVED** [review]
LGTM

**Comment by bpintea** [comment]
> Is it ok for ODBC, or should I list them as `SCALAR` ?

AFA ODBC is concerned, the way we list the function is orthogonal to it; i.e. there's no API which maps directly to this catalog call a.t.m.

AFAI can tell, ODBC [lists it](https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqlgetinfo-function?view=sql-server-2017#scalar-function-information) however as a scalar function, under the type `SQL_CONVERT_FUNCTIONS`, where the supported conversions (or "functions") are are to be inquired with types provided in the [following paragraph](https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqlgetinfo-function?view=sql-server-2017#conversion-information).

A while ago we have decided not to obtain this information from ES/SQL dynamically, but to rather hard coded it in the driver. But even if we were to change that decision, in the listing we now have, the `type` column would not suffice to cover the API call where it could be relevant (`SQLGetInfo()`), since the supported conversions are not part of that listing. 
This is why we have no direct mapping on this catalog call and why the way we do the listing is atm not relevant to the driver.

**Comment by matriv** [comment]
@bpintea Thanks a lot for looking into this! Changing the type to `SCALAR`.

**Review by costin — APPROVED** [review]
LGTM

**Comment by matriv** [comment]
Backported to `6.x` with 71704fa4919a557b00b42fb9e2fda165c004b893

**Comment by matriv** [comment]
Backported to `6.5` with 7e995e09bd375b533ea799a8b8738987ecc83523

**Pull request merged**
