### PR TITLE
Update Elasticsearch Apache 2.0 licensed source code to use new dual SSPL+Elastic software license

### PR DESCRIPTION
**Pull request by mark-vieira**
As per the new licensing change for Elasticsearch and Kibana (explained in great detail [in this blog post](https://www.elastic.co/blog/licensing-change)) this pull request move existing Apache 2.0 licensed source code to the new dual license SSPL+Elastic license. Changes include:

- Updating LICENSE and NOTICE files throughout the code base, as well as those packaged in our published artifacts
- Update IDE integration to now use the new license header on newly created source files
- Remove references to the "OSS" distribution from our documentation
- Update build time verification checks to no longer allow Apache 2.0 license header in Elasticsearch source code
- Replace all existing Apache 2.0 license headers for non-xpack code with updated header (vendored code with Apache 2.0 headers obviously remains the same).

This pull request will be impossible to keep up to date with upstream changes from `master` so it is not intend to be actually merged. Updates + actual commit/push will be done manually. This PR is mainly for validation in CI as well as manual review by the team. As such it will be marked as WIP.

### CODE REVIEW

**Review by breskeby — APPROVED** [review]

**Review by breskeby — APPROVED** [review]
obviously didn't check all 8000+ files. checked the build logic bits though. lgtm

**Comment by pugnascotia** [comment]
We need some changes in `distribution/docker/build.gradle` as we supply the license for property replacement in the `Dockerfile`.

**Comment by mark-vieira** [comment]
@pugnascotia to confirm, you are just referring to what we use for the container labels as we don't seem to copy a distinct license _file_ for the image (besides UBI and IronBank)?

**Comment by pugnascotia** [comment]
@mark-vieira yes, just that. We do perform some license copying, but we don't change them. Iron Bank has its own license file, as well, but that's the Elastic license + addendums.

**Comment by mark-vieira** [comment]
@elasticmachine update branch

**Comment by mark-vieira** [comment]
This has been pushed manually.

**Pull request closed without merging**
