### PR TITLE
give access to some histogram related information

### PR DESCRIPTION
**Pull request by swachter**
Issue: https://github.com/elastic/elasticsearch/issues/69054

### CODE REVIEW

**Comment by nik9000** [comment]
Hello @swachter sorry this took so long for us to reply to. It looks like we've got a hole somewhere in our triage process. Anyway! We can't accept the change as it stands because we don't really think of all of the `public` methods as public API. I mean, they are *are* part of the public API because plugins might need them, but they aren't in that we're not careful with them. Thus the whole version lock on plugins thing. Anyway, the trouble with these is that it isn't really obvious what they are for so even if we did merge them there's a good chance we'd drop them a year later. I'm not really sure how to fix that. I mean, one way would be to open a PR to add the whole proportional sum agg. If you could do that and if we merged it then we'd be sure to keep it working forever. But that ain't always possible. I'm open to ideas, but not sure of anything that'd work.

Also! Check out `AbstractRateAggregator#findSizedBucketAncestor`. Its not 100% right, but it seems to do similar stuff. We found there are problems when the parent isn't a direct parent which makes the lookup funky. Also check out `DateHistogramAggregator.FromDateRange` for an example of why a change your making might fail in sneaky situations.

Now that I think about it, is `SizedBucketAggreregator` enough for you? It doesn't add as much as you do, but its something.

**Comment by swachter** [comment]
Hi @nik9000 thanks for looking into this! It is interesting that you do similar things with the `SizedBucketAggregator`.

Unfortunately, the information that `SizedBucketAggregator` exposes is not enough. Instead of the `bucketSize`, we would need the `bucketStart`/`bucketEnd` or `bucketStart`/`bucketSize`. In my PR I tried to expose the interval, offset and bucket key in order to calculate the `bucketStart` and `bucketEnd`.

Do you think it is feasable to augment the `SizedBucketAggregator` interface to provide that information?

Another possibility I see would be to use the standard "sum" aggregation. The values would be calculated by a script that would need the `bucketStart`/`buckend` and in its [field context](https://www.elastic.co/guide/en/elasticsearch/painless/master/painless-field-context.html).

**Comment by nik9000** [comment]
The tricky bit is knowing that folks are using it. Like I said, we don't have a public API so much as just expose all the the internals to plugins. And these methods, public or not, are internals to us. So we could add them in this PR and remove them in the next and not notice. And we don't have a lot of appetite for expanding those value scripts, especially with all the work we just did for runtime fields. Is your proportional sum something you'd be interested in contributing? That'd for sure wedge these in place.

**Comment by swachter** [comment]
> Is your proportional sum something you'd be interested in contributing? That'd for sure wedge these in place.

Sure, I would be interested in contributing our proportional sum plugin. I wonder how much flexibility it would require to be general enough.

ATM the parent aggregation of a proportional sum aggregation must be a range histogram, i.e. documents have a range valued field and they are assigned to corresponding buckets (one or more). The proportional sum aggregation is like the `sum` aggregation with the only difference that the added values are multiplied by a factor. For each summand the factor is calculated by `bucketSize / rangeOfDocumentSize`. Maybe the `SizedBucketAggreregator` interface could provide that information in some way. It knows the buckets and it knows the range valued field. 

Would it be general enough to have the factor calculation hard wired like this or should it be more flexible?

**Comment by nik9000** [comment]
Sorry it took me so long to reply. If you have the code in a plugin I'd open a PR with it. At worst we look at it and say "no". But I don't really see the problem. I admit I still don't fully understand it, but I'd get it from the code I think.

**Comment by swachter** [comment]
> Sorry it took me so long to reply. If you have the code in a plugin I'd open a PR with it. At worst we look at it and say "no". But I don't really see the problem. I admit I still don't fully understand it, but I'd get it from the code I think.

I created the issue https://github.com/elastic/elasticsearch/issues/71189 with the accompanying PR https://github.com/elastic/elasticsearch/pull/71191

I would be happy if you could have a look onto it.

**Comment by swachter** [comment]
replaced by issue https://github.com/elastic/elasticsearch/issues/71189

**Pull request closed without merging**
