### PR TITLE
Rename cloud-gce plugin to discovery-gce plugin

### PR DESCRIPTION
**Pull request by dadoonet**
Follow up azure and aws splits, we need to be consistent and rename `cloud-gce` to `discovery-gce`.

### CODE REVIEW

**Comment by bleskes** [comment]
LGTM. Don't we want to document this as a breaking change somewhere...?

**Comment by dadoonet** [comment]
Indeed! Thanks. Will add this.

**Comment by dadoonet** [comment]
I pushed a new version and was almost ready to go but GCE tests are failing when running from Maven. And they pass when ran from the IDE... :(

Need to fix that first obviously.

**Comment by dadoonet** [comment]
So I added some traces, tried to debug that but I have no clue of what is happening.

It sounds like this method is never called when you run tests from the command line (mvn install): https://github.com/dadoonet/elasticsearch/blob/pr/rename-gce/plugins/discovery-gce/src/test/java/org/elasticsearch/discovery/gce/GceComputeServiceMock.java#L60

When you run it from the IDE this method is called.

@rmuir Any idea?

**Comment by bleskes** [comment]
@dadoonet can I help here somehow?

**Comment by dadoonet** [comment]
@bleskes If you have any idea why the branch fails on Maven, then yes you can definitely help.
I did not find the cause for now.

**Comment by dadoonet** [comment]
@bleskes sounds like after rebasing everything looks better. Will run all `mvn install` now and will merge if success.

Thanks!

**Comment by bleskes** [comment]
great.

**Pull request merged**
