### PR TITLE
Introduce the index.downsample.origin.name and index.downsample.origin.uuid settings

### PR DESCRIPTION
**Pull request by andreidan**
This proposes introducing two new settings we configure when downsampling:
`index.downsample.origin.name`
`index.downsample.origin.uuid`

These settings will carry on the name and uuid of the first source index we downsample (like the source.name and source.uuid settings behaved before this PR).

This also changes the behaviour of `index.downsample.source.name` and `index.downsample.source.uuid` to always reflect the source of the current downsampling round.

If an index is downsampled once, both the source and origin settings will have the same value.

However, for subsequent downsampling operations, a later downsampling round will have the actual index name and uuid that were used as the source of the downsampling operation configured 
e.g.
`downsample-350s-.ds-metrics-foo-2023.08.17-000001` will have the `index.downsample.source.name` configured to `downsample-1s-.ds-metrics-foo-2023.08.17-000001` and `index.downsample.origin.name` configured to `.ds-metrics-foo-2023.08.17-000001`.

Note that this will help us simplify things in data stream lifecycle as with subsequent 
downsampling configuration we currently have to store the true source of the downsampling operation
in the downsample index metadata ( https://github.com/elastic/elasticsearch/blob/main/modules/data-streams/src/main/java/org/elasticsearch/datastreams/lifecycle/downsampling/ReplaceSourceWithDownsampleIndexTask.java#L173 )

If you agree with this proposal we'll have to manually backport to 8.10 as well to make sure the `generateDownsampleIndexName` method is consistent across releases https://github.com/elastic/elasticsearch/blob/main/server/src/main/java/org/elasticsearch/action/downsample/DownsampleConfig.java#L249

Note that the `index.provided_name` setting which is set on indices when rolling over cannot act like a 
source (initially I thought we can use that instead of introducing a new setting, the origin one) because 
it contains date-math patterns.

### CODE REVIEW

**Review by csoulios — APPROVED** [review]
LGTM!

The way we had original thought about this index setting was that we only care about the orifinal (raw) index that data was downsampled from. We needed this information for the cases where we queried multiple downsampled indices that originate from the same source/index.

So the way it currently works `index.downsample.source.*` settings are exactly what you added as `index.downsample.origin.*`

If this change is useful for ILM, I am happy with it. Also, this change should be a breaking change under norman circumstances. However, we do not use any of the `index.downsample.source.*` settings right now. 

> Note that the index.provided_name setting which is set on indices when rolling over cannot act like a source (initially I thought we can use that instead of introducing a new setting, the origin one) because it contains date-math patterns.

Agree

**Review by salvatore-campagna — APPROVED** [review]

**Comment by salvatore-campagna** [comment]
@andreidan It is not clear to me why in ILM we need to know the `origin`.

My understanding is that the "downsample of downsample" use case is triggered by an ILM policy which, for instance, has a downsample action in the hot phase and a downsample action in the warm phase. If I understand correctly the `origin` would point the index name and uuid of the index in the hot phase (always) no matter if we are downsampling from hot to warm or from warm to cold. While the `source` would be the index name and uuid of the index in the hot phase (when downsampling from hot to warm) and the index name and uuid of the index in the warm phase (when downsampling from warm to cold)...right? But why do we need to know the origin(al) index name and uuid?

**Comment by andreidan** [comment]
@csoulios 

> this change should be a breaking change under norman circumstances. However, we do not use any of the index.downsample.source.* settings right now.

So I thought about that as well, but based on lack of usages and the fact that we don't document these settings publicly it seems that it's not breaking - if you all agree as well :)

**Review by martijnvg — APPROVED** [review]
LGTM

**Comment by andreidan** [comment]
@elasticmachine update branch

**Comment by andreidan** [comment]
Thanks for the review @salvatore-campagna @csoulios @martijnvg ❤️

**Pull request merged**
