### PR TITLE
Consider copy_to in synthetic source implementation for binary field

### PR DESCRIPTION
**Pull request by lkts**
This was missed in previous PR - we need to be consistent with how other fields handle this.

### CODE REVIEW

**Comment by lkts** [comment]
@elasticmachine update branch

**Comment by lkts** [comment]
CI failure https://github.com/elastic/elasticsearch/issues/107782

**Comment by lkts** [comment]
buildkite test this

**Review by martijnvg — APPROVED** [review]
lgtm

**Pull request merged**
