### PR TITLE
Consistent update of stage and failure message in IndexShardSnapshotStatus

### LINKED ISSUE #26480: [CI] SharedClusterSnapshotRestoreIT#testGetSnapshotsRequest failing
I feel that I am to blame for this because of the https://github.com/elastic/elasticsearch/pull/26463, but I cannot reproduce locally

link:
https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+master+oracle-periodic/605/console

trace

```
20:51:14   1> org.elasticsearch.repositories.RepositoryException: [test-repo] could not read repository data from index blob
20:51:14   1> 	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.getRepositoryData(BlobStoreRepository.java:648) ~[main/:?]
20:51:14   1> 	at org.elasticsearch.snapshots.SnapshotsService.createSnapshot(SnapshotsService.java:236) ~[main/:?]
20:51:14   1> 	at org.elasticsearch.action.admin.cluster.snapshots.create.TransportCreateSnapshotAction.masterOperation(TransportCreateSnapshotAction.java:82) ~[main/:?]
20:51:14   1> 	at org.elasticsearch.action.admin.cluster.snapshots.create.TransportCreateSnapshotAction.masterOperation(TransportCreateSnapshotAction.java:41) ~[main/:?]
20:51:14   1> 	at org.elasticsearch.action.support.master.TransportMasterNodeAction.masterOperation(TransportMasterNodeAction.java:87) ~[main/:?]
20:51:14   1> 	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$2.doRun(TransportMasterNodeAction.java:166) ~[main/:?]
20:51:14   1> 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) ~[main/:?]
20:51:14   1> 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[main/:?]
20:51:14   1> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_144]
20:51:14   1> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_144]
20:51:14   1> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
20:51:14   1> Caused by: java.io.IOException: Random IOException
20:51:14   1> 	at org.elasticsearch.snapshots.mockstore.MockRepository$MockBlobStore$MockBlobContainer.maybeIOExceptionOrBlock(MockRepository.java:276) ~[test/:?]
20:51:14   1> 	at org.elasticsearch.snapshots.mockstore.MockRepository$MockBlobStore$MockBlobContainer.listBlobsByPrefix(MockRepository.java:336) ~[test/:?]
20:51:14   1> 	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.listBlobsToGetLatestIndexId(BlobStoreRepository.java:777) ~[main/:?]
20:51:14   1> 	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.latestIndexBlobId(BlobStoreRepository.java:755) ~[main/:?]
20:51:14   1> 	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.getRepositoryData(BlobStoreRepository.java:607) ~[main/:?]
20:51:14   1> 	... 10 more
20:51:14   1> [2017-09-02T06:51:05,705][INFO ][o.e.s.SharedClusterSnapshotRestoreIT] 
```

reproduce with:

```
gradle :core:integTest \
  -Dtests.seed=3BFDC6F19B3167C4 \
  -Dtests.class=org.elasticsearch.snapshots.SharedClusterSnapshotRestoreIT \
  -Dtests.method="testGetSnapshotsRequest" \
  -Dtests.security.manager=true \
  -Dtests.locale=mk \
  -Dtests.timezone=Australia/Brisbane
```

### PR DESCRIPTION
**Pull request by tlrx**
As @ywelsch commented in https://github.com/elastic/elasticsearch/issues/26480#issuecomment-331383391, `IndexShardSnapshotStatus` is not consistently updated. 

This pull request adds a synchronized `updateStage(stage, failure)` to ensure that both fields are updated at the same time and also makes the fields volatile so that threads always read the latest values.

Closes #26480

### CODE REVIEW

**Review by ywelsch — CHANGES_REQUESTED** [review]
This does not fix the issue, unfortunately. Although updateStage is synchronized, access to the volatile fields is still non-synchronized, which means that when we first call stage() and then failure() to read the values, we can still observe a stage which is FAILURE but a failure that is not set. We need not only atomic writes, but also atomic access to the <stage, failure> field pair.

**Comment by tlrx** [comment]
@ywelsch I've been to quick on this, sorry. I change the stage / failure getter to be synchronized too.

**Comment by ywelsch** [comment]
This still won't allow the stage & failure pair to be consistently read. Assume the following sequence:
- read stage
- update(stage, failure)
- read failure

**Comment by tlrx** [comment]
@ywelsch Right again, I'll revisit this correctly and update the code.

**Comment by tlrx** [comment]
Closed in favor of #28130

**Pull request closed without merging**
