### PR TITLE
Disable console logging

### PR DESCRIPTION
**Pull request by jasontedor**
Previously we would disable console logging in certain circumstances
(for example, if Elasticsearch is not in the foreground, or if
Elasticsearch is in the foreground but an exception was thrown during
bootstrap). This commit makes this handling work with Log4j 2. This will
prevent users from seeing double bootstrap check failure messages.

### CODE REVIEW

**Comment by jasontedor** [comment]
retest this please

**Comment by jasontedor** [comment]
retest this please

**Comment by jaymode** [comment]
LGTM

**Comment by jasontedor** [comment]
Thanks @jaymode!

**Pull request merged**
