### PR TITLE
Add Default ELSER 2 Capability

### PR DESCRIPTION
**Pull request by Mikep86**
Adds a default ELSER 2 capability, which is used to conditionally run some semantic text YAML tests that were previously broken (and thus, muted) in release mode.

Addresses #114376 and #114412

### CODE REVIEW

**Comment by carlosdelest** [comment]
@elasticsearchmachine update branch

**Comment by carlosdelest** [comment]
@elasticmachine update branch

**Comment by Mikep86** [comment]
@elasticmachine update branch

**Review by carlosdelest — APPROVED** [review]

**Review by maxhniebergall — APPROVED** [review]
LGTM

**Comment by Mikep86** [comment]
@elasticmachine update branch

**Comment by Mikep86** [comment]
@elasticmachine run elasticsearch-ci

**Comment by Mikep86** [comment]
@elasticmachine run ci

**Comment by Mikep86** [comment]
buildkite test this

**Comment by Mikep86** [comment]
@elasticmachine update branch

**Comment by Mikep86** [comment]
Removed the release test CI check due to the large number of random, unrelated release tests currently failing that otherwise block us from merging this PR. I checked the two affected YAML tests locally and both are skipped as expected in release mode.

**Comment by Mikep86** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.x|[](https://github.com/elastic/elasticsearch/pull/116120)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
