### PR TITLE
Fix command line to run doc tests in docs/README.

### PR DESCRIPTION
**Pull request by jpountz**
It runs `gradle` instead of `gradlew` and has an extra `\`.

### CODE REVIEW

**Review by alpar-t — APPROVED** [review]
LGTM 

/cc @mark-vieira

**Comment by mark-vieira** [comment]
This looks fine although after merging #40978 the preferred method is to use `--tests` but the old system properties technically do still work.

**Comment by jpountz** [comment]
Happy to change it to use the preferred method. @mark-vieira do you mean it should be `./gradlew :docs:check --tests "*rollover*"`?

**Comment by mark-vieira** [comment]
@jpountz you have to pass `--tests` to the actual test task, so in the case the correct command would be ```./gradlew :docs:integTestRunner --tests "*rollover*"```

**Comment by jpountz** [comment]
:+1:

**Pull request merged**
