### PR TITLE
Phonetic: Remove class that is part of commons-codec

### PR DESCRIPTION
**Pull request by spinscale**
This class was copied from commons-codec trunk and is now part of the stable
release since 2012.

### CODE REVIEW

**Review by cbuescher — APPROVED** [review]
Just did a side-by-side comparison and the class from commons-codec looks equivalent to me. LGTM

**Comment by cbuescher** [comment]
@spinscale care to merge or should I do it?

**Comment by spinscale** [comment]
please go ahead, as I am not sure into which branches this should go in as well.

**Comment by cbuescher** [comment]
@spinscale since its a non-issue cleanup I'd say 8.0 is okay, or do you have a different opinion?

**Pull request merged**
