### PR TITLE
Remove TODO in a test for verifying start of the week

### PR DESCRIPTION
**Pull request by pgomulka**
The test should be run against 7.7 version at least, as this was only backported and released in that version

relates SPI based implementation https://github.com/elastic/elasticsearch/pull/48209
relates backport https://github.com/elastic/elasticsearch/pull/48349

### CODE REVIEW

**Comment by pgomulka** [comment]
ok to test

**Comment by pugnascotia** [comment]
There's a test failure that looks like it may be related to the change?

**Comment by pgomulka** [comment]
@pugnascotia yes, I am surprised to see this. Somehow build is not passing `-Djava.locale.providers=SPI,COMPAT` when running this test. Will investigate

**Comment by pgomulka** [comment]
@elasticmachine update branch

**Review by pugnascotia — APPROVED** [review]

**Review by nik9000 — APPROVED** [review]
LGTM. Thanks for clearing the TODO!

**Pull request merged**
