### PR TITLE
update to the max file descriptors number

### PR DESCRIPTION
**Pull request by robb3rt**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by rjernst** [comment]
Thanks for the PR @robb3rt. Can you please explain why you believe this documentation needs updating? The docs match the bootstrap check we have in place for max file descriptors.

**Comment by robb3rt** [comment]
@rjernst the max file descriptors should be `65536` or higher or bootstrap checks will fail. Right now the commands we list to set the max file descriptors set it to `65535` instead.

Also quoting our documentation:
>Make sure to increase the limit on the number of open files descriptors for
the user running Elasticsearch to ***65,536*** or higher.

**Comment by rjernst** [comment]
Which version of Elasticsearch are you using? This was changed to 65535 in #37537, which merged to 6.7 and 7.0. The documentation matches the check.

**Comment by rjernst** [comment]
I think the discrepancy is in the line that you quoted in your last comment, which should be changed to 65535. It was not caught in #37537 because it contains a comma.

**Comment by javanna** [comment]
hi @robb3rt do you plan on updating your PR based on the comments you received above?

**Comment by danielmitterdorfer** [comment]
I'm closing this PR meanwhile due to lack of feedback. If there is interest to continue with this PR, please reopen. Thank you. :)

**Pull request closed without merging**
