### PR TITLE
Output more information when gradle can't start elasticsearch

### PR DESCRIPTION
**Pull request by nik9000**
When the build tries to start an elasticsearch instance but the start fails
if it fails to find the log file then we log a line about how we can't find
the file.

Also log the command that we attempted to use.

### CODE REVIEW

**Comment by dakrone** [comment]
LGTM, thanks!

**Comment by nik9000** [comment]
@rjernst do you have an opinion?

**Comment by rjernst** [comment]
Should we log the command line and environment at info level outside of error conditions? Exec tasks log at info level what they are running (sort of) but now that we are using ant exec here we get nothing.

**Comment by nik9000** [comment]
> Should we log the command line and environment at info level outside of error conditions? Exec tasks log at info level what they are running (sort of) but now that we are using ant exec here we get nothing.

I like logging it at error level if it fails. I can log it at info level if it doesn't?

**Comment by rjernst** [comment]
Well my point is we should log it before we try to run the command.

**Comment by nik9000** [comment]
> Well my point is we should log it before we try to run the command.

Sure - I can do that too.

**Comment by nik9000** [comment]
@rjernst how about now?

**Comment by rjernst** [comment]
LGTM, thanks!

**Pull request merged**
