### PR TITLE
Revert "Remove aggregation's postCollect phase

### LINKED ISSUE #66876: Sorting terms buckets on nested or parent or child aggregations silently sorts incorrectly
When you sort the `terms` aggregation on `nested` or a `child` or a `parent` aggregation the on-data-node sorting sorts by "empty" values. This can be masked by a large enough `shard_size` so it has slipped through our test cases for a while, but [this](https://gist.github.com/nik9000/3cc956d1bc420f3b7c5734ef99aeded0) shows the failures. It looks like this is caused because we delay collecting parent and nested until right before we build buckets.

Replaces #53534 and #53570. Both are about error messages trying to sort. You actually can sort now, it just doesn't work :cry:.

Relates to #63811.

### PR DESCRIPTION
**Pull request by imotov**
This partially reverts #64016 and  and adds #67839 and adds
additional tests that would have caught issues with the changes
in #64016. It's mostly Nik's code, I am just cleaning things up
a bit. This commit only fixes nested aggs. Fixing the children aggs
is more difficult issue. 

Relates to #66876

Co-authored-by: Nik Everett <nik9000@gmail.com>

### CODE REVIEW

**Comment by imotov** [comment]
@elasticmachine update branch

**Review by nik9000 — APPROVED** [review]
LGTM. Good luck with the trickier bit!

I still don't like postCollect because we have to delay it sometimes so it feels *wrong*. But this fixes the issue and we'll come up with something better later.

**Comment by imotov** [comment]
I don't like this either, but it looks like we need to find a better solution.

**Comment by nik9000** [comment]
It looks like something went wrong with the backport to 7.11 and this doesn't solve the issue on the branch. I've removed the 7.11.2 label because, while the code is in that release, its not doing what we thought it did.

**Comment by imotov** [comment]
Interesting, it's definitely in v7.11.2:
```
› git log v7.11.2 --oneline | grep 'Revert "Remove aggregation'
27e59ab83d0 [7.11] Revert "Remove aggregation's postCollect phase (#68942) (#69066)
```

And changes are [there](https://github.com/elastic/elasticsearch/blob/3e5a16cfec5/modules/parent-join/src/main/java/org/elasticsearch/join/aggregations/ParentJoinAggregator.java#L105)

**Comment by nik9000** [comment]
When I dropped the label I had incorrectly thought that we intended this PR to fix a particular bug who's test had suddenly started failing. It wasn't. We were just adding the test to make sure we had it for when we *do* fix the bug. So it's correct to say that this is in 7.11.2.

**Pull request merged**
