### PR TITLE
Add Enrich Origin

### PR DESCRIPTION
**Pull request by jbaiera**
This PR adds an origin for the Enrich feature, and modifies the background maintenance task to use the origin when executing client operations. Without this fix, the maintenance task fails to execute when security is enabled.

### CODE REVIEW

**Review by hub-cap — APPROVED** [review]
sorry, this was my mistake. LGTM. I knew i was going to mess the origin (or lack thereof) stuff up.

**Review by martijnvg — APPROVED** [review]
LGTM

**Comment by jbaiera** [comment]
@elasticmachine update branch

**Comment by jbaiera** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample-matrix

**Comment by jbaiera** [comment]
@elasticmachine update branch

**Comment by jbaiera** [comment]
@elasticmachine update branch

**Pull request merged**
