### PR TITLE
Increase assertAllCancellableTasksAreCancelled timeout

### PR DESCRIPTION
**Pull request by pxsalehi**
The following two failures happen rarely, but both fail in the same `assertBusy` block. I don't have a clue why, and couldn't reproduce them. Considering the amount of checks in that block, maybe a larger timeout is more suitable. (Also it seems from the test history, it is not uncommon for those tests to take 2-3s, so every few thousand runs hitting the 10s timeout seems likely, IMO!) 
Relates https://github.com/elastic/elasticsearch/issues/88884, https://github.com/elastic/elasticsearch/issues/88201

### CODE REVIEW

**Review by kingherc — APPROVED** [review]
LGTM, assuming CI passes. Hope it was just the timeout the reason for the failures! :crossed_fingers:

**Comment by pxsalehi** [comment]
Thanks @kingherc. Do you know actually if backporting to 8.3 is necessary here? I have the impression that since main is now 8.5, only the CI for 8.4 will be periodically running, and there is no more 8.3 changes.

**Comment by kingherc** [comment]
@pxsalehi seeing the release schedule, I believe 8.3 may not be necessary. But feel free to check with the team as well to be certain.

**Comment by pxsalehi** [comment]
Yes, I thought the same. I think I'll take out the 8.3. Thanks.

**Comment by pxsalehi** [comment]
@elasticmachine update branch

**Pull request merged**
