### PR TITLE
Converting Derivative Pipeline Agg integration test into  AggregatorTestsCase.

### PR DESCRIPTION
**Pull request by mirkojotic**
This is a WIP PR for this conversion as a part of #36015 

I tried not modifying any tests but just change the underlying setup. That being said I did hit a couple of snags.

[testPartiallyUnmapped](https://github.com/elastic/elasticsearch/blob/b08cffad48ed3833e69611fb5bfbc9bb85c2f72b/server/src/test/java/org/elasticsearch/search/aggregations/pipeline/DerivativeIT.java#L355) method seems to be using two indices. I wasn't sure how to handle that so I'm open to any suggestions.

In [testAvgMovavgDerivNPE](https://github.com/elastic/elasticsearch/blob/b08cffad48ed3833e69611fb5bfbc9bb85c2f72b/server/src/test/java/org/elasticsearch/search/aggregations/pipeline/DerivativeIT.java#L630) I tried using `NumericDocValuesField` for "value" field but since it's sometimes `null` it would throw an NPE. Again any advice is welcome :)

Anywhere in the file where [number of hits](https://github.com/elastic/elasticsearch/blob/b08cffad48ed3833e69611fb5bfbc9bb85c2f72b/server/src/test/java/org/elasticsearch/search/aggregations/pipeline/DerivativeIT.java#L391) is referenced I would loop over buckets and get doc count. Not sure if proper approach.

If I made some more errors or if something can be improved I'm always open to suggestions or direction.

@polyfractal

### CODE REVIEW

**Comment by polyfractal** [comment]
Awesome, thanks for working on this!

> [testPartiallyUnmapped](https://github.com/elastic/elasticsearch/blob/b08cffad48ed3833e69611fb5bfbc9bb85c2f72b/server/src/test/java/org/elasticsearch/search/aggregations/pipeline/DerivativeIT.java#L355) method seems to be using two indices. I wasn't sure how to handle that so I'm open to any suggestions.

Hmm, yeah, I'm not sure if we'll be able to replicate that at the moment.  We'd have to modify AggregatorTestCase to accept multiple `IndexSearcher`, then generate and merge multiple `ShardSearcher`'s.  Pretty outside the scope of this PR, and probably not worth the hassle.

I'd say :+1: to just skipping the partially-unmapped test.

> In [testAvgMovavgDerivNPE](https://github.com/elastic/elasticsearch/blob/b08cffad48ed3833e69611fb5bfbc9bb85c2f72b/server/src/test/java/org/elasticsearch/search/aggregations/pipeline/DerivativeIT.java#L630) I tried using `NumericDocValuesField` for "value" field but since it's sometimes `null` it would throw an NPE. Again any advice is welcome :)

Was the NPE when adding the null value, or when testing?

I think you can do `document.add(new NumericDocValuesField("value", null));` to add it, the `Document` will accept a `Long` (which allows it being null).

> Anywhere in the file where [number of hits](https://github.com/elastic/elasticsearch/blob/b08cffad48ed3833e69611fb5bfbc9bb85c2f72b/server/src/test/java/org/elasticsearch/search/aggregations/pipeline/DerivativeIT.java#L391) is referenced I would loop over buckets and get doc count. Not sure if proper approach.

Ahh, yeah, that works :)  We don't have access to the total hit count easily in these tests, so that's a good proxy.  Word of warning though, I think it works for these tests but it could be fragile elsewhere.  A document is allowed to be added to multiple buckets (e.g. overlapping ranges, multiple values that each land in a different bucket, etc) so doc_count doesn't always equal the total hits.

I think that's an assertion we can drop if it becomes flaky, although from skimming the tests I think it will be fine here.

I didn't look suuuper closely at all the tests yet, but from a skim I think they look good!  Thanks for doing these!  Once we've resolved the NPE test I'll kick off a build and give all the tests a closer look. :)

**Comment by mirkojotic** [comment]
No problem. It wasn't a difficult process as I followed what you did for the initial one 😊

I think you can do document.add(new NumericDocValuesField("value", null)); to add it, the Document will accept a Long (which allows it being null).

This is what I tried first and it would throw a NPE. But let me go back and re-check it and report back.

**Comment by polyfractal** [comment]
Hm gotcha, I'll take a closer look today.  The alternative is to just skip the field in that document (which is essentially equivalent), but I think there's already a test that skips.  I'll go digging to see the history of that NPE test, it looks like something that was added for a specific issue.  If it only pertains to XContent parsing or something we can probably ignore it.

**Comment by mirkojotic** [comment]
Sounds good. Let me know if you want me to look into the history of it.

And my current solution just skips indexing that field if it's null. Which is only twice.

**Comment by polyfractal** [comment]
I had a quick look and it seems to originate from https://github.com/elastic/elasticsearch/commit/39a067aa3f453480940d2124b813c13593a87c06, and is basically just testing that the derivative can handle missing/skipped values.  So I think the approach of just omitting it from the document is fine here, which is equivalent to setting null in the JSON (e.g. we just don't add nulls to documents).

Think this is ready for CI test runs in that case?

**Comment by mirkojotic** [comment]
Great. In that case I believe it is.

**Comment by polyfractal** [comment]
:+1: 

@elasticmachine test this please

**Comment by mirkojotic** [comment]
I have code style issues. I completely overlooked that. I'm sorry. 

I'll make sure that's fixed and let you know.

**Comment by mirkojotic** [comment]
@polyfractal I've fixed the style issues and `gradle checkStyle` is successful. So I think it's ready for another CI run.

One problem I had is that `gradle check` isn't really running well for me and it never was. It doesn't finish successfully and I'm not sure why. I made a docker container where I have jdk 11 and gradle 5.2.1 and still no luck.

**Comment by Blackiie** [comment]
Aún no entiendo esto muy bien pero, aquí estoy asiendo presencia y trataré
de seguirlo asiendo 😀. Gracias!!

**Comment by polyfractal** [comment]
@elasticmachine test this please

@mirkojotic Hmm, what sort of errors are you getting?  Are you invoking it with the gradle wrapper (`gradlew` instead of `gradle`)?  

If you're just seeing test failures, and not something that looks like the gradle build itself is broken... it could just be unrelated failures.  We're actually in a team-wide effort at the moment to fix flaky/broken tests since the spurious failure rate has creeped up over time, so you may have run into an unrelated broken test.

Also as a tip for running checkstyle stuff fast, you can do `./gradlew precommit --parallel` which will speed it up a bit :)  Parallel test runs unfortunately have issues at the moment, so `--parallel` won't work for `check`, `test`, etc.

**Comment by mirkojotic** [comment]
Well it failed again. I looked at Jenkins console of the first CI and couldn't discern what went wrong. I'm willing to work on it whatever it is so any help with figuring out the cause is appreciated.

**Comment by andyb-elastic** [comment]
@mirkojotic the latest CI failures should be resolved by merging master back into your branch (there were some changes to the build since your branch was created)

https://scans.gradle.com/s/5nbkdc76vfpk2/console-log?task=:distribution:bwc:minor:checkoutBwcBranch

```
:distribution:bwc:minor:checkoutBwcBranch FAILED
--
Checking out elasticsearch elastic/6.x for branch 6.x
error: pathspec 'elastic/6.x' did not match any file(s) known to git.
```

**Comment by mirkojotic** [comment]
@andyb-elastic I did a quick fetch of upstream, merge into feature branch. Hope that's what you meant.

Since you asked @polyfractal this is one of the errors I'm getting. There is around 30 and all very similar `NoClassDefFoundError`.
```
Suite: org.elasticsearch.test.VersionUtilsTests
ERROR   0.00s J1 | VersionUtilsTests (suite) <<< FAILURES!
   > Throwable #1: java.lang.NoClassDefFoundError: Could not initialize class org.elasticsearch.test.ESTestCase
   >    at java.base/java.lang.Class.forName0(Native Method)
   >    at java.base/java.lang.Class.forName(Class.java:398)
Completed [24/36] on J1 in 0.03s, 0 tests, 1 error <<< FAILURES!
```

Anyhow It might be ready for another CI run.

**Comment by andyb-elastic** [comment]
@elasticmachine test this please

@mirkojotic yup that's what I meant. I checked out your branch and I'm not seeing that issue with `NoClassDefFoundError` in my environment

You've probably seen this already, but here's our [high level guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-to-the-elasticsearch-codebase) on setting up your environment for our build. Some people find they have to set the relevant `JAVA_HOME` variables in their shell profile rather than just in the shell they're running gradlew from, due to how gradle works

I'm assuming you're running gradlew from the shell here, when seeing problems that look like issues with the build,  I usually run a `git -xdf clean` to clean out anything that may be lingering from previous builds (this will delete anything that's not committed)

**Comment by mirkojotic** [comment]
Well, some progress has been made 😊 

@andyb-elastic I didn't even think that there's something wrong with the tests, is definitely my environment. I'll try out your suggestion. 

I got another issue in CI 2 that I don't understand.

**Comment by polyfractal** [comment]
I think that CI 2 failure is unrelated, alas. :(

@elasticmachine run elasticsearch-ci/2

**Comment by mirkojotic** [comment]
Hurray! I'll be watching for comments.

Thank you both for being patient!

**Comment by polyfractal** [comment]
adcc08a87d810d4d 

Merging, and will backport to 7.x as well.  Thanks @mirkojotic!

**Comment by polyfractal** [comment]
Also a note: I figure we can let these churn away on CI for a little bit, then remove the duplicated parts from the existing integration tests once we think it's stable.  :)

**Comment by mirkojotic** [comment]
@polyfractal awesome! Happy to hear it!

I'll get to work on some other ones if it makes sense.

**Pull request merged**
