### PR TITLE
Do not use UnsafePlainActionFuture to avoid possible starvation

### PR DESCRIPTION
**Pull request by volodk85**
After merging other work in serverless, it won't initiate cache population on a prewarming thread any more, so there will not be possible to be blocked on prewarming thread

ES-8641

### CODE REVIEW

**Comment by volodk85** [comment]
Should go after https://github.com/elastic/elasticsearch-serverless/pull/2555
(it contains fix which brakes connection between cache filling threads by forking to `generic`)

**Review by henningandersen — APPROVED** [review]
LGTM (after referenced PR is merged).

We should ensure we have additional CI runs, perhaps both locally and in CI, to ensure we catch it in case we missed something in relation to this.

**Review by arteam — APPROVED** [review]
LGTM2

**Review by arteam — APPROVED** [review]
LGTM2

**Pull request merged**
