### PR TITLE
Do not set fatal exception when shard follow task is stopped.

### PR DESCRIPTION
**Pull request by martijnvg**
When shard follow task is cancelled while fetching operations then
the fatal exception field should not be set.

Otherwise a retryable error can be set as a fatel error and
that is confusing if a user just happen to fetch shard follow stats
around the time when this happens.

### CODE REVIEW

**Review by dnhatn — APPROVED** [review]
Nice find. LGTM.

**Comment by martijnvg** [comment]
@elasticmachine run gradle build tests 1

**Review by jasontedor — APPROVED** [review]
LGTM. Great catch.

**Comment by martijnvg** [comment]
@elasticmachine run gradle build tests 2

**Pull request merged**
