### PR TITLE
Fix testMaxThreadAndMergeCount

### PR DESCRIPTION
**Pull request by mattweber**
Fix testMaxThreadAndMergeCount from failing when the host
machine has < 8 cores.

This test kept failing for me since my dev machine only has 4 cores and this test tried to set the `NODE_PROCESSORS_SETTING` to 8 even though it has a max value of the number of cores (4).

### CODE REVIEW

**Comment by mattweber** [comment]
@romseygeek maybe you can have a look at this?

**Comment by romseygeek** [comment]
@elasticmachine test this please

**Comment by romseygeek** [comment]
@elasticmachine update branch

**Comment by romseygeek** [comment]
@elasticmachine test this please

**Comment by romseygeek** [comment]
Hi @mattweber, it looks as though this change causes the test in the lines above your change to fail - can you take a look?

**Comment by ywelsch** [comment]
Closing due to inactivity.

**Pull request closed without merging**
