### PR TITLE
[TEST] Add test for integer_range fields in query_string queries

### PR DESCRIPTION
**Pull request by romseygeek**
This commit just adds a test for integer_range, if it looks sensible then I'll add tests for the other range field types

### CODE REVIEW

**Comment by romseygeek** [comment]
Ping @jpountz

**Review by jpountz — COMMENTED** [review]
Oh cool, so this worked already. +1 to adding tests for other types as well.

**Comment by romseygeek** [comment]
Tests for all other types added @jpountz .  Would be nice to extend this to support multi-dimensional ranges as well, but that will be a bit more involved, I think.

**Review by jpountz — APPROVED** [review]

**Comment by jpountz** [comment]
@romseygeek Thanks for the tests! You might want to add "Closes #XXXX" to the commit message so that it closes the issue on merge. This also makes it easier to correlate Github issues with commits when looking at the git log.

**Pull request merged**
