### PR TITLE
Upgrade Netty to 4.1.52.Final

### PR DESCRIPTION
**Pull request by odidev**
- Update Netty to 4.1.52 which includes both security fixes and AArch64 performance improvements
- Refer release notes for detail:
  - https://netty.io/news/2020/05/13/4-1-50-Final.html
  - https://netty.io/news/2020/09/08/4-1-52-Final.html

### CODE REVIEW

**Comment by odidev** [comment]
Hi,
Please have a look in this PR.

**Comment by original-brownbear** [comment]
Jenkins test this

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/bwc

**Comment by original-brownbear** [comment]
Hi @odidev 

thanks for opening this. Could  you please merge current `master` into this branch again? It's slightly outdated and that's making our backwards compatibility tests fail I think.

**Comment by odidev** [comment]
Hi @original-brownbear , 
Thanks for your reply. Merged this branch with the current master.

**Comment by original-brownbear** [comment]
Jenkins test this

**Comment by tbrooks8** [comment]
We have upgraded past this version at this point.

**Pull request closed without merging**
