### PR TITLE
If not set JAVA_HOME then use the JDK that Gradle was run with instead

### PR DESCRIPTION
**Pull request by RickyLau**
Build multiple version of elasticsearch, need't change JAVA_HOME.
Just change Gradle runtime JDK.

### CODE REVIEW

**Comment by vboulaye** [comment]
Hi, 
I was just about to create a pull request regarding a similar issue: In my case I have the JAVA_HOME set globally to jdk8 by default and I override the JVM inside the Intellij project, 
I would rather have the launch jvm used over the one set in JAVA_HOME when we know that gradle was started from the IDE (vboulaye@dacb96b59e3ed12d16a121312342da3c6c272b17 ). 
Otherwise it would be nice to get a failure message that indicates from where the jvm was set (the running one or the JAVA_HOME env). Right now the message explains clearly that the version is incorrect but not why it chose it:

```
Caused by: org.gradle.api.GradleException: the compiler java.home must be 
set to a JDK installation directory for Java 11 but is [/home/user/.jenv/versions/1.8]
 corresponding to [1.8]
```

**Comment by atorok** [comment]
Thanks for the PR @RickyLau I think we had a few reasons not to do this this and actually require that `JAVA_HOME` is set historically, but I don't think those apply any more. 
@rjernst @jasontedor can you think of reasons we would still need the env var set, especially now that we bundle the JDK ? I looked trough the code and couldn't not find any, 

@elasticmachine test this please 

( CI does set JAVA_HOME so the PR checks won't really cover this one )

**Comment by RickyLau** [comment]
In IntelliJ IDEA ,when JAVA_HOME not set 
`if (System.getProperty("idea.active") != null || System.getProperty("eclipse.launcher") != null) {
                // IntelliJ does not set JAVA_HOME, so we use the JDK that Gradle was run with
                return Jvm.current().javaHome
            }
`  This condition always return false.

**Comment by rjernst** [comment]
@RickyLau what version of IntelliJ are you running? I think the properties set by it changed recently, so we need to adjust our detection.

@atorok We still use JAVA_HOME for unit tests.

**Comment by vboulaye** [comment]
Hi @rjernst,

It was in fact me who was speaking about Intellij, the initial PR was only about not failing when neither JAVA_HOME nor the ide "detection" properties are set.

My case is a little bit different, I have a JAVA_HOME set globally by default to v8, and when using Intellij to run the build, the version from JAVA_HOME is used instead of the one defined in Intellij.

But the build task correctly detect that I am launching from the IDE (when I switch the 2 tests) so I suppose the property is set. I am using  version 2018.3.5.

**Comment by RickyLau** [comment]
> @RickyLau what version of IntelliJ are you running? I think the properties set by it changed recently, so we need to adjust our detection.
> 
> @atorok We still use JAVA_HOME for unit tests.

 I am using version 2018.3.5.
Dos adjust our detection for  IntelliJ IDEA lauch properties or just delete judge statement..

**Comment by atorok** [comment]
@rjernst we configure all test tasks with `jvm "${project.runtimeJavaHome}/bin/java"` which I think will work correctly with this change.

**Comment by atorok** [comment]
@RickyLau I just noticed your PR is targeted against `7.x` can you please target `master` ? We'll back-port from there.

**Comment by RickyLau** [comment]
> @RickyLau I just noticed your PR is targeted against `7.x` can you please target `master` ? We'll back-port from there.

OK

**Comment by RickyLau** [comment]
@atorok  new PR for #40622 ,  Please help me close current PR.

**Pull request closed without merging**
