### PR TITLE
Add extra assertions on FollowingEngineTests#fetchOperations

### PR DESCRIPTION
**Pull request by fcofdez**
Relates to #72527

#72527 fails from time to time when an operation applied to the follower engine has a `seqNo > maxSeqNoOfUpdatesOrDeletes`. Before applying a batch of operations the follower engine updates `maxSeqNoOfUpdatesOrDeletes` with the leader engine value meaning that `maxSeqNoOfUpdatesOrDeletes >= seqNo` so my only theory so far is that `InternalEngine#newChangesSnapshot` is returning ops beyond the requested range.

### CODE REVIEW

**Comment by fcofdez** [comment]
@elasticmachine update branch

**Review by henningandersen — APPROVED** [review]
LGTM though I added an update that I hope you will explore to the original issue.

**Comment by fcofdez** [comment]
@elasticmachine update branch

**Comment by fcofdez** [comment]
I'm closing this as I found the issue in https://github.com/elastic/elasticsearch/issues/72527#issuecomment-868380996 it was unrelated to the proposed changes.

**Pull request closed without merging**
