### PR TITLE
Move randomized runner gradle plugin to external dependency

### PR DESCRIPTION
**Pull request by rjernst**
The randomized testing gradle code belongs with the randomized testing
library. This moves it to its own repository, which is now published as
a snapshot in nexus.

See #13930

### CODE REVIEW

**Comment by rjernst** [comment]
FYI, eventually the gradle plugin can move inside the randomizedtesting library directly. But this plugin is still young and immature. So in the meantime, it has its own repository right next to randomizedtesting.

**Comment by rjernst** [comment]
And the repo is here:
https://github.com/randomizedtesting/gradle-randomized-testing-plugin

**Comment by jpountz** [comment]
LGTM

**Comment by rjernst** [comment]
I'm holding off on pushing this to ease the ability for others to contribute to cleanups as we stabilize the gradle build.

**Comment by dakrone** [comment]
@rjernst do we still need to hold off on this, or can it be merged?

**Comment by dakrone** [comment]
@rjernst do we still need to hold off on merging this?

**Comment by rjernst** [comment]
I need to get back around to making a real release of the randomized testing gradle project. Right now it is just a very old snapshot.

**Comment by dakrone** [comment]
Okay, I'll mark this as stalled waiting on a release of the randomized testing gradle project then.

**Comment by dakrone** [comment]
@rjernst is this still stalled?

**Comment by rjernst** [comment]
Unfortunately yes. It is stalled in that I have had no time to work on documenting everything in there (eg all the settings, how to use it, etc).

**Comment by rjernst** [comment]
I'm closing this PR and will reopen when I have time to prepare the gradle randomized testing plugin for release to maven.

**Pull request closed without merging**
