### PR TITLE
Adjust use of Deprecated Netty API

### PR DESCRIPTION
**Pull request by original-brownbear**
* With the recent upgrade to Netty 4.1.36 `exceptionCaught` became deprecated on `ChannelHandlerAdapter` and I made the advised change to implementing it on `ChannelInboundHandlerAdapter` instead to fix the deprecation

### CODE REVIEW

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/2

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/1

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/1

**Review by Tim-Brooks — APPROVED** [review]
LGTM

**Comment by original-brownbear** [comment]
thanks @tbrooks8 !

**Pull request merged**
