### PR TITLE
MINOR: a few of improvements

### PR DESCRIPTION
**Pull request by asdf2014**

### CODE REVIEW

**Comment by asdf2014** [comment]
@cbuescher PTAL

**Comment by matriv** [comment]
Hello @asdf2014,

Thank you for your interest in the project and your contribution.
We'll go ahead and proceed with the PR but please check the [general guidelines regarding contribution](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-code-and-documentation-changes) for the next time:
```
Note that it is unlikely the project will merge refactors for the sake of refactoring. These types of pull requests have a high cost to maintainers in reviewing and testing with little to no tangible benefit. This especially includes changes generated by tools. For example, converting all generic interface instances to use the diamond operator.
```

**Comment by matriv** [comment]
@elasticmachine ok to test

**Comment by matriv** [comment]
@elasticmachine update branch

**Pull request merged**
