### PR TITLE
Minor documentation fix in enroll node API section

### PR DESCRIPTION
**Pull request by jsvd**
Path should be `/_security/enroll/node` and not `/security/enroll/node`.

### CODE REVIEW

**Comment by jsvd** [comment]
Test failure:

```
11:27:29 Tests with failures:
11:27:29  - org.elasticsearch.action.admin.indices.diskusage.IndexDiskUsageAnalyzerIT.testFailingTargetShards
```

**Review by albertzaharovits — APPROVED** [review]

**Comment by jsvd** [comment]
@albertzaharovits apologies I missed that this was reviewed, should I merge it myself? I'm not 100% sure on the right tagging/merging etiquette.

**Comment by lockewritesdocs** [comment]
@elasticmachine update branch

**Comment by lockewritesdocs** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.2|[](https://github.com/elastic/elasticsearch/pull/86627)|
|✅|8.1|[](https://github.com/elastic/elasticsearch/pull/86628)|
|✅|8.0|[](https://github.com/elastic/elasticsearch/pull/86629)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Comment by lockewritesdocs** [comment]
> @albertzaharovits apologies I missed that this was reviewed, should I merge it myself? I'm not 100% sure on the right tagging/merging etiquette.

@jsvd, I added the labels and backported the changes, so you're all set!

**Pull request merged**
