### PR TITLE
Add Lintian overrides to ignore Intel MKL not linked to libc

### LINKED ISSUE #87632: [CI] DebMetadataTests test05CheckLintian failing
This is an upgraded version of Lintian on Ubuntu 22.04 taking offence at the Intel MKL libraries not being linked against libc:

```
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_avx2.so	
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_avx512.so	
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_avx512_mic.so	
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_core.so	
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_def.so	
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_gnu_thread.so	
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_intel_lp64.so	
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_mc3.so	
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_vml_avx.so	
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_vml_avx2.so	
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_vml_avx512.so	
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_vml_avx512_mic.so	
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_vml_cmpt.so	
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_vml_def.so	
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_vml_mc3.so	
```

**Build scan:**
https://gradle-enterprise.elastic.co/s/tkvxgodtbhuzm/tests/:qa:os:destructiveDistroTest.default-deb/org.elasticsearch.packaging.test.DebMetadataTests/test05CheckLintian

**Reproduction line:**
`null`

**Applicable branches:**
master, 8.3

**Reproduces locally?:**
Didn't try

**Failure history:**
https://gradle-enterprise.elastic.co/scans/tests?tests.container=org.elasticsearch.packaging.test.DebMetadataTests&tests.test=test05CheckLintian

**Failure excerpt:**
```
org.elasticsearch.packaging.util.Shell$ShellException: Command was not successful: [bash -c lintian --fail-on warning /var/lib/jenkins/workspace/elastic+elasticsearch+main+multijob+packaging-tests-unix/os/ubuntu-22.04-packaging/distribution/packages/deb/build/distributions/elasticsearch-8.4.0-SNAPSHOT-amd64.deb]
   result: exitCode = [2] stdout = [E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_avx.so
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_avx2.so
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_avx512.so
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_avx512_mic.so
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_core.so
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_def.so
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_gnu_thread.so
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_intel_lp64.so
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_mc3.so
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_vml_avx.so
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_vml_avx2.so
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_vml_avx512.so
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_vml_avx512_mic.so
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_vml_cmpt.so
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_vml_def.so
E: elasticsearch: library-not-linked-against-libc usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/lib/libmkl_vml_mc3.so
E: elasticsearch: malformed-override Unknown tag systemd-service-file-outside-lib in line 28
W: elasticsearch: mismatched-override unknown-field elasticsearch-*.deb License
W: elasticsearch: unknown-field License
N: 354 hints overridden (190 errors, 121 warnings, 43 info); 5 unused overrides] stderr = [running with root privileges is not recommended!]

  at __randomizedtesting.SeedInfo.seed([755215F255DF0D76:B5AC891EEFAB68CD]:0)
  at org.elasticsearch.packaging.util.Shell.runScript(Shell.java:143)
  at org.elasticsearch.packaging.util.Shell.run(Shell.java:73)
  at org.elasticsearch.packaging.test.DebMetadataTests.test05CheckLintian(DebMetadataTests.java:38)
  at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  at java.lang.reflect.Method.invoke(Method.java:577)
  at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
  at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
  at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:375)
  at com.carrotsearch.randomizedtesting.ThreadLeakControl.lambda$forkTimeoutingTask$0(ThreadLeakControl.java:831)
  at java.lang.Thread.run(Thread.java:833)

```

### PR DESCRIPTION
**Pull request by droberts195**
We don't build these libraries ourselves and the license forbids
us from modifying them in any way, so we won't be able to make
this rule pass on them. All we can do is override it.

Fixes #87632

### CODE REVIEW

**Comment by mark-vieira** [comment]
Looks like Ubuntu 22.04 wasn't added to the pull request jobs. I've fixed that so will kick off the tests again to ensure this fixed the issue. Thanks, David!

**Comment by mark-vieira** [comment]
@elasticmachine update branch

**Comment by mark-vieira** [comment]
Looks like we're still getting a warning

```
W: elasticsearch: mismatched-override unknown-field elasticsearch-*.deb License
W: elasticsearch: unknown-field License
```

It seems to be complaining the existing override for `unknown-field elasticsearch-*.deb License` doesn't match? Should we make the wildcard more lenient?

**Review by pugnascotia — APPROVED** [review]

**Comment by droberts195** [comment]
> Looks like we're still getting a warning

The syntax of that override was wrong - fixed in https://github.com/elastic/elasticsearch/pull/87706/commits/c709209f2ff46f6139cb8cc768f884d840222d60: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+packaging-tests-unix/307/PACKAGING_TASK=destructiveDistroTest.packages,os=ubuntu-22.04-packaging/

**Comment by droberts195** [comment]
Now it fails on Debian 11: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+packaging-tests-unix/307/PACKAGING_TASK=destructiveDistroTest.packages,os=debian-11-packaging/console

```
08:46:11   2> org.elasticsearch.packaging.util.Shell$ShellException: Command was not successful: [bash -c lintian --fail-on warning /var/lib/jenkins/workspace/elastic+elasticsearch+pull-request+packaging-tests-unix/PACKAGING_TASK/destructiveDistroTest.packages/os/debian-11-packaging/distribution/packages/deb/build/distributions/elasticsearch-8.4.0-SNAPSHOT-amd64.deb]
08:46:11        result: exitCode = [2] stdout = [W: elasticsearch: mismatched-override unknown-field License
08:46:11     W: elasticsearch: unknown-field elasticsearch-8.4.0-SNAPSHOT-amd64.deb License
08:46:11     N: 355 hints overridden (191 errors, 121 warnings, 43 info); 6 unused overrides] stderr = [warning: running with root privileges is not recommended!]
```

It seems we need both overrides, plus one to say not to worry about incorrect override syntax.

**Comment by droberts195** [comment]
`elasticsearch-ci/packaging-tests-unix` is never going to fully pass as there don't seem to be any Oracle Linux 7 workers available at the moment.  But the latest packaging tests, https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+packaging-tests-unix/310/, have now passed on all available platforms, including all those that would run Lintian, so effectively this PR has passed CI now.

**Review by rjernst — APPROVED** [review]
LGTM

**Review by mark-vieira — APPROVED** [review]

**Pull request merged**
