### PR TITLE
[ML] rename frequent_items to frequent_item_sets and make it GA

### PR DESCRIPTION
**Pull request by hendrikmuhs**
rename frequent_items to frequent_item_sets and remove the experimental batch

For backwards compatibility, the aggregation will remain working using `frequent_items` and use the deprecation logger to hint users to migrate to the new name.

### CODE REVIEW

**Comment by hendrikmuhs** [comment]
@szabosteve We've decided rename `frequent_items` to `frequent_item_sets` this name fits better. Looking at the _existing_ documentation we always spoke about frequent item sets there. So the the rename was overdue. The same applies for the code.

@droberts195 @szabosteve As part of this PR I additionally removed the experimental flag and filled in the changelog. Please have a look. I can split this into two PR's if you think that's better.

**Review by szabosteve — APPROVED** [review]
Thanks for handling the docs changes and adding the release highlight label! Text LGTM.

**Review by droberts195 — APPROVED** [review]
LGTM

**Comment by droberts195** [comment]
Corresponding Kibana change: https://github.com/elastic/kibana/pull/150150

**Pull request merged**
