### PR TITLE
Add option to skip signing rpm

### PR DESCRIPTION
**Pull request by nik9000**
Fix contributing.md note about fedora.

### CODE REVIEW

**Comment by dakrone** [comment]
It looks like it bypassed signing the RPM, but it needs to bypass signing the DEB too:

```
[INFO] --- jdeb:1.4:jdeb (default) @ elasticsearch ---
[INFO] Passphrase was not encrypted
[INFO] Creating debian package: /home/hinmanm/es/elasticsearch/distribution/deb/target/releases/elasticsearch-2.3.0-SNAPSHOT.deb
[WARNING] Signing requested, but no key supplied
[ERROR] Failed to create debian package /home/hinmanm/es/elasticsearch/distribution/deb/target/releases/elasticsearch-2.3.0-SNAPSHOT.deb
org.vafer.jdeb.PackagingException: Failed to create debian package /home/hinmanm/es/elasticsearch/distribution/deb/target/releases/elasticsearch-2.3.0-SNAPSHOT.deb
	at org.vafer.jdeb.DebMaker.makeDeb(DebMaker.java:296)
	at org.vafer.jdeb.maven.DebMojo.execute(DebMojo.java:552)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.NullPointerException
	at org.vafer.jdeb.signing.PGPSigner.getSecretKey(PGPSigner.java:146)
	at org.vafer.jdeb.signing.PGPSigner.<init>(PGPSigner.java:54)
	at org.vafer.jdeb.DebMaker.makeDeb(DebMaker.java:280)
	... 23 more
```

**Comment by nik9000** [comment]
> It looks like it bypassed signing the RPM, but it needs to bypass signing the DEB too:

Bah. I'm getting sloppy. Will fix.

**Comment by nik9000** [comment]
@dakrone that should help

**Comment by dakrone** [comment]
@nik9000 tested and this works now, LGTM, thanks!

**Pull request merged**
