### PR TITLE
Docs: fix typo in cache source code

### PR DESCRIPTION
**Pull request by razic**
fixed a typo `iff` should be `if`

### CODE REVIEW

**Comment by jasontedor** [comment]
This is not a typographical error. We are using `iff` here to mean "if and only if".

**Review by jbaiera — APPROVED** [review]
LGTM!

**Comment by razic** [comment]
sorry :laughing:

**Comment by nik9000** [comment]
This comes a couple of times a year. Maybe we shouldn't use `iff` to use "if and only if".

**Pull request closed without merging**
