### PR TITLE
Extract the snapshot/restore full cluster restart tests from the translog full cluster restart tests

### LINKED ISSUE #25203: Snapshot/restore test in full cluster restart/upgrade tests fail
I'd wanted to debug this but it looks like I'm not going to have time. The test makes a snapsot in 5.6 and then does a full cluster restart to upgrade to master. Then it does `GET /_snapshot/repo/_all` and looks for the snapshot and doesn't find it.

### PR DESCRIPTION
**Pull request by nik9000**
Extract the snapshot/restore full cluster restart tests from the translog full cluster restart tests. That way they are easier to read.

Closes #25203

### CODE REVIEW

**Review by abeyad — APPROVED** [review]
LGTM

**Review by imotov — COMMENTED** [review]
The snapshot test fails because we wipe out all snapshots at [the end of the test](https://github.com/elastic/elasticsearch/blob/18f16ba555f0ba35213885c7203deeddeed552e5/test/framework/src/main/java/org/elasticsearch/test/rest/ESRestTestCase.java#L204). While `preserveReposUponCompletion()` preserves the repository themselves the repository end up with all snapshots deleted in it. After I commented out the `wipeSnapshots` method call the test passed. It looks like we need another `preserveSnapshotsUponCompletion()` flag that will preserve both repos and snapshots in them.

**Comment by nik9000** [comment]
Thanks @imotov! I'm fixing it now.

**Comment by nik9000** [comment]
@abeyad  and @imotov: I pushed the fix @imotov recommended.

**Review by imotov — APPROVED** [review]
I am just wondering who is going to clean the snapshots after the test and shouldn't `preserveSnapshotsUponCompletion()` and `preserveReposUponCompletion()` can be something like `runningAgainstOldCluster == false` instead of always be `true`? Otherwise LGTM.

**Review by abeyad — APPROVED** [review]
Still LGTM

**Comment by nik9000** [comment]
> I am just wondering who is going to clean the snapshots after the test and shouldn't preserveSnapshotsUponCompletion() and preserveReposUponCompletion() can be something like runningAgainstOldCluster == false instead of always be true?

I think it has to stay true the whole time because the wipe is done after every test rather than after the whole suite.

The snapshots aren't cleaned up by the test at all - we leave them until either `gradle clean`, `git clean -df` or the next test is run - when the next test is run gradle will clean the shared directory before starting.

**Comment by imotov** [comment]
@nik9000 yep, good point.

**Pull request merged**
