### PR TITLE
[ML] Remove excessive logging from ML upgrade mode

### PR DESCRIPTION
**Pull request by droberts195**
While looking into another issue I noticed that
when enabling or disabling ML upgrade mode some
very low level messages are logged at the INFO
level.  This commit reduces that to TRACE.

### CODE REVIEW

**Review by dimitris-athanasiou — APPROVED** [review]
LGTM

**Comment by droberts195** [comment]
@elasticmachine update branch

**Comment by droberts195** [comment]
run elasticsearch-ci/2

**Comment by droberts195** [comment]
Turns out this logging wasn't in 7.x at all, so no need to backport

**Pull request merged**
