### PR TITLE
Correct the query dsl for watching elasticsearch version

### PR DESCRIPTION
**Pull request by gaobinlong**
Relates to #58261.

The `term` query should be looking at the `cluster_uuid` field in [elasticsearch_version_mismatch.json](https://github.com/elastic/elasticsearch/blob/f00c8abe20c6fc9487cca961a89c188b3c700cc8/x-pack/plugin/monitoring/src/main/resources/monitoring/watches/elasticsearch_version_mismatch.json#L39).

### CODE REVIEW

**Comment by LeeDr** [comment]
@jakelandis any thoughts on this one line fix?  I'm just testing rolling upgrade and alerts in Kibana and hit this issue.

**Comment by jakelandis** [comment]
@elasticmachine update branch

**Comment by jakelandis** [comment]
@elasticmachine ok to test

**Comment by gaobinlong** [comment]
@jakelandis, all checks have passed yet, can this PR be approved now?

**Comment by jakelandis** [comment]
thanks @gaobinlong ! (sorry it took so long to merge in ... it fell off my radar at some point)

**Pull request merged**
