### PR TITLE
Upgrade to Lucene 7.0.0

### PR DESCRIPTION
**Pull request by jasontedor**
This commit upgrades to the GA release of Luence 7!

### CODE REVIEW

**Review by martijnvg — APPROVED** [review]
:+1:

**Review by rjernst — APPROVED** [review]
LGTM

**Comment by nknize** [comment]
:+1:  

need to remove `-SNAPSHOT` from line 3 in `docs/Version.asciidoc`

**Review by nknize — CHANGES_REQUESTED** [review]
need to remove -SNAPSHOT from line 3 in docs/Version.asciidoc

**Comment by jasontedor** [comment]
@nknize I've updated, can you review again?

**Pull request merged**
