### PR TITLE
Fix typo in terms-query

### PR DESCRIPTION
**Pull request by JacobAMason**
Found a typo. You don't have to merge this if you don't want to, just tracking it here.

### CODE REVIEW

**Comment by JacobAMason** [comment]
That bizarre license agreement just runs into an nginx error, so I'm just ignoring that.

**Comment by nik9000** [comment]
> That bizarre license agreement just runs into an nginx error, so I'm just ignoring that.

We can't merge anything unless you've signed it. https://www.elastic.co/contributor-agreement resolves for me though.

**Comment by JacobAMason** [comment]
I checked the documentation and it looks like this may have been fixed in a later version, because it's fine by 5.4

**Comment by clintongormley** [comment]
thanks for letting us know @JacobAMason

**Pull request closed without merging**
