### PR TITLE
Remove Dep. on SnapshotsService in SnapshotShardsService

### PR DESCRIPTION
**Pull request by original-brownbear**
SnapshotShardsService depends on the RepositoriesService
not the SnapshotsService, no need to have this indirection.

### CODE REVIEW

**Review by tlrx — APPROVED** [review]
LGTM

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/1

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/1

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/1

**Comment by original-brownbear** [comment]
Thanks @tlrx !

**Pull request merged**
