### PR TITLE
Security: reorder realms based on last success

### PR DESCRIPTION
**Pull request by jaymode**
This commit reorders the realm list for iteration based on the last
successful authentication for the given principal. This is an
optimization to prevent unnecessary iteration over realms if we can
make a smart guess on which realm to try first.

### CODE REVIEW

**Comment by tvernum** [comment]
I'm concerned about changing this behaviour in a minor.

The problem comes when there are multiple realms that can handle the same principal, and the higher priority one is temporarily unavailable.
In that case we will cache the second realm as the authenticating realm, and the only solution is to clear the cache (which customers don't tend to do).

I think we should default the setting to `false` when it is backported to 6.7

**Comment by jaymode** [comment]
> I think we should default the setting to false when it is backported to 6.7

I am fine with doing that

**Review by albertzaharovits — APPROVED** [review]
LGTM

**Review by tvernum — COMMENTED** [review]
I wonder if we want to do something about the cache on security index status change.
One of:
1. don't populate the cache if the security index is red (probably because it has not yet been recovered)
2. don't consult the cache if the security index is red
3. clear the cache on security index state change (like `NativeRealm.onSecurityIndexStateChange`)

I think (3) is the more consistent approach with our other security caches.

**Review by tvernum — APPROVED** [review]
:+1:

**Pull request merged**
