### PR TITLE
Copy_from on set processor should deep copy non-primitive mutable types

### LINKED ISSUE #69348: copy_from option on set processor links rather than copies complex content
**Elasticsearch version** (`bin/elasticsearch --version`): 7.11.0+

**Steps to reproduce**:
```
POST _ingest/pipeline/_simulate
{
  "pipeline": {
    "processors": [
      {
        "set": {
          "field": "foo2",
          "copy_from": "foo"
        }
      },
      {
        "set": {
          "field": "foo2.bar",
          "value": "changed"
        }
      }
    ]
  },
  "docs": [
    {
      "_source": {
        "foo": {
          "bar": "baz"
        }
      }
    }
  ]
}
```
produces:
```
  "_source" : {
    "foo2" : {
      "bar" : "changed"
    },
    "foo" : {
      "bar" : "changed"
    }
  }
```
which shows that `foo2` is linked to the content of `foo` and cannot be changed independently.

### PR DESCRIPTION
**Pull request by danhermann**
Fixes #69348

### CODE REVIEW

**Comment by danhermann** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by danhermann** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by danhermann** [comment]
@elasticmachine update branch

**Comment by danhermann** [comment]
@elasticmachine run elasticsearch-ci/2

**Review by jbaiera — APPROVED** [review]
LGTM

**Comment by danhermann** [comment]
Thank you, @jbaiera!

**Pull request merged**
