### PR TITLE
Upgrade to Gradle 5.6.3

### PR DESCRIPTION
**Pull request by alpar-t**
This PR upgrades to [5.6.3](https://github.com/gradle/gradle/releases/tag/v5.6.3).
Nothing particualrily of interest for us, just keeping up to date.

### CODE REVIEW

**Comment by atorok** [comment]
@elasticmachine test this please

**Comment by atorok** [comment]
@elasticmachine run elasticsearch-ci/oss-distro-docs and run elasticsearch-ci/default-distro  and don't forget to also  run  elasticsearch-ci/bwc

**Comment by atorok** [comment]
@elasticmachine update branch

**Comment by atorok** [comment]
@elasticmachine update branch

**Comment by atorok** [comment]
@elasticmachine update branch

**Comment by atorok** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample-matrix

**Review by mark-vieira — APPROVED** [review]
LGTM

**Pull request merged**
