### PR TITLE
Exposing the ability to log deprecated settings at non-critical level

### PR DESCRIPTION
**Pull request by masseyke**
A recent change for the deprecation logs provided the capability to emit deprecation's at critical vs. warning levels, #77482.
However deprecated settings always log at critical level without the ability to express that the setting deprecation is only a
warning.

This commit exposes the ability to set the deprecation level when deprecating a setting.
Relates #78781

### CODE REVIEW

**Review by rjernst — COMMENTED** [review]
Looks good in general, I just have a few comments about not adding more variants of methods in HeaderWarning and ESTestCase.

**Comment by masseyke** [comment]
@elasticmachine update branch

**Review by rjernst — COMMENTED** [review]
Looks good, but one last question

**Review by rjernst — APPROVED** [review]
LGTM

**Pull request merged**
