### PR TITLE
Fix ResourceNotFoundException in testUpdateStoreKeepAlive.

### PR DESCRIPTION
**Pull request by jtibshirani**
In the final part of this test, we update the expiration time to 1ms. The 'get
async search' method first updates the expiration time, then fetches the
response in a separate request. So the maintenance service could remove the
document right after it's updated, which means the get request fails with a
ResourceNotFoundException.

For now we just modify the test to handle this possibility. It should be very
rare in practice, since usually the maintenance service runs every 1 hour
(whereas in tests it runs every 100ms).

Addresses #67092.

### CODE REVIEW

**Comment by jtibshirani** [comment]
There are ways to fix the underlying behavior instead of modifying the test. For example, we could fetch the document within the update request. Or maybe we could perform the 'get' before the 'update'. Since this will be such a rare issue in practice, I preferred to make a simple test fix for now.

**Review by cbuescher — APPROVED** [review]
LGTM, I read through the issue description and explanation here and I think expecting (and ignoring) this specific exception in the test makes sense. Just for my understanding, your last comment on #67092 sounds like you expect other kind of errors that might lead to other test failures, would you say we keep that issue open for now or close and wait if this fixied most occurances in the near future?

**Review by ywelsch — APPROVED** [review]
LGTM

**Comment by jtibshirani** [comment]
@cbuescher you're right that there are other failures. I don't really expect this to fix them too. I plan to close that issue in favor of a new one targeting the other errors.

**Comment by tlrx** [comment]
Should we backport this to 7.17 ? The test failed today https://gradle-enterprise.elastic.co/s/tapqjkeh4pyew/

**Pull request merged**
