### PR TITLE
Remove mapping boost parameter entirely

### PR DESCRIPTION
**Pull request by romseygeek**
Follow up to #62623, this commit removes support in 8x for index-time boosts.
There is no longer a `boost` field on `MappedFieldType`.  Indexes created in 8x
and after will throw exceptions if a `boost` parameter is included in mappings,
and indexes created in 7x will emit warnings.

### CODE REVIEW

**Comment by romseygeek** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample-windows

**Comment by romseygeek** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by romseygeek** [comment]
@elasticmachine update branch

**Review by jimczi — COMMENTED** [review]
The change looks good to me. I wonder if we should continue to accept `boost` on indices create before 8 tough ? We could also ignore the `boost` option on these indices or even rewrite them automatically to remove the option ? I am not sure if this really needed but I wanted to list the options since this parameter exists for a long time in our mappings.

**Comment by romseygeek** [comment]
The boosts still have an effect in some places in 7x, so I think we need to keep them until 8 unfortunately.  Rewriting automatically would be nice, and useful in some other places as well (for example, removing legacy type names from 7x mappings) but it is a larger change because it breaks some of the assumptions we use to check that mappings are correctly serialized in mixed clusters during upgrades.

**Comment by romseygeek** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample-windows

**Review by jimczi — APPROVED** [review]
LGTM, we discussed offline and have decided to act the removal. We expect the boost to be marginally used so it shouldn't cause issues. We have time to revert before the next major if we find a reason that would make the upgrade to  8 more difficult.

**Pull request merged**
