### PR TITLE
Updating docs to include max number for the `size` parameter

### PR DESCRIPTION
**Pull request by adityasrini**
Updating asciidocs to include a max number for the `size` parameter and clarify the reason for its existence. Also adding a space between `update_by_query` (or `reindex` or `delete_by_query`) field and "ed" at the end of the bullet point to make the `update_by_query` field take on a code font. Resolves issue #26981

### CODE REVIEW

**Comment by nik9000** [comment]
I *think* it'd be better to add the documentation for the `size` parameter to the ` URL Parameters` section. Can you add it there instead?

**Comment by nik9000** [comment]
Sorry to take so long to review this. I ended up having to re-image my desktop and got seriously distracted getting it back up and running properly....

**Comment by adityasrini** [comment]
Just wondering where the right place to put the `size` information would be. Does this seem appropriate? Because the `size` is not exclusive to those query API's/



 > In addition to the standard parameters like pretty, the Delete By Query API also supports `refresh`, `wait_for_completion`, `wait_for_active_shards`, `timeout`, `scroll`, and `size`. The `size` parameter can not be more than the `index.max_result_window` index setting which defaults to 10,000

I used an oxford comma here. If that's not within the documenting style used at ES, I wont have an issue taking it out.

**Comment by adityasrini** [comment]
Hello there! Would someone mind looking into this?

**Comment by adityasrini** [comment]
Closing this since this issue has been fixed in a recent update.

**Pull request closed without merging**
