### PR TITLE
Upgrade bundled JDK to Java 19

### PR DESCRIPTION
**Pull request by mark-vieira**
Java 19 has gone GA and Java 18 is now EOL. Update the bundled JDK runtime in Elasticsearch distributions to Java 19.

### CODE REVIEW

**Comment by mark-vieira** [comment]
@elasticsearchmachine update branch

**Comment by mark-vieira** [comment]
@elasticmachine run elasticsearch-ci/release-tests

**Comment by mark-vieira** [comment]
@elasticmachine run elasticsearch-ci/release-tests

**Comment by mark-vieira** [comment]
@elasticmachine update branch

**Review by breskeby — APPROVED** [review]
I have seen the docs build error a few times now. Will look into this.

**Comment by mark-vieira** [comment]
@elasticmachine update branch

**Pull request merged**
