### PR TITLE
System indices auto-create for searchable-snapshots

### PR DESCRIPTION
**Pull request by pugnascotia**
Part of #61656.

Use the system indices auto-creation infrastructure for the searchable
snapshots plugin.

### CODE REVIEW

**Review by jaymode — APPROVED** [review]
LGTM

**Review by tlrx — APPROVED** [review]
LGTM

**Comment by henningandersen** [comment]
@pugnascotia while backporting #66687, I came to a conflict since this looks like it was not backported. The labelling on this PR suggests it should be backported. Can you clarify whether a backport is missing or the labelling is wrong?

**Comment by pugnascotia** [comment]
@henningandersen I think this an oversight on my part. I'll get it fixed up, thanks for alerting me.

**Pull request merged**
