### PR TITLE
Add 5.3 version constant

### PR DESCRIPTION
**Pull request by rjernst**
This change adds 5.3 and updates 5.x branch to have 5.3 as latest.

### CODE REVIEW

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by jasontedor** [comment]
I just remembered one other place that needs to change: the index.asciidoc files in docs.

**Comment by jasontedor** [comment]
I pushed 0babe9a4aee10891b39b766ff11e197877c846ee.

**Comment by jasontedor** [comment]
I also pushed 3faa840da1422a285fd4b2b5c6b3bd10ac428628.

**Comment by rjernst** [comment]
Thanks @jasontedor

**Comment by jasontedor** [comment]
I pushed df425a1e96206e3c67b1ad75f0c843572b9ddd59 for 5.2.

**Pull request merged**
