### PR TITLE
[8.x] Remove match command (#113383)

### PR DESCRIPTION
**Pull request by ioanatia**
Backports the following commits to 8.x:
 - Remove match command (#113383)

### CODE REVIEW

**Comment by ioanatia** [comment]
@elasticmachine merge upstream

**Comment by ioanatia** [comment]
@elasticmachine merge upstream

**Comment by ioanatia** [comment]
I merged upstream thinking some of the failures have been solved in the meantime.
Looking at the failures they are unrelated to the changes - I also see some of these changes happening in other PRs.
None of them are ES|QL related.
Leaving this PR open has the potential of making it difficult to merge any other backports that touch the lexer/parser due to conflicts.
I am not a fan of merging by bypassing branch protections, but I will do that in this case.

**Comment by DaveCTurner** [comment]
Hi @ioanatia, please don't merge things without a clean CI run. Just because it's hitting failures that appear to be unrelated doesn't mean that there aren't other failures later on in the build that _are_ related to this change. We can get into a massive mess if that starts to happen.

Please instead either wait for the problems to be resolved (ping the relevant folks if needed) or else mute the problematic tests yourself.

**Pull request merged**
