### PR TITLE
Make hashed token ids url safe

### PR DESCRIPTION
**Pull request by jaymode**
This commit changes the way token ids are hashed so that the output is
url safe without requiring encoding. This follows the pattern that we
use for document ids that are autogenerated, see UUIDs and the
associated classes for additional details.

### CODE REVIEW

**Comment by jaymode** [comment]
@elasticmachine run elasticsearch-ci/bwc elasticsearch-ci/default-distro

**Comment by jaymode** [comment]
For some background, I came across this while implementing #42471 and switching the token auth tests to use the high level rest client. Around 50% of the time a update request would fail with a document missing exception. Looking closely, there is a mismatch with the encoding by the rest client and the decoding by the server wrt the `+` symbol. The server decodes that as a space, which results in the document missing exception. This mismatch needs to be fixed as well but we should take this opportunity to use a url safe id that doesn't need encoding.

**Review by jkakavas — APPROVED** [review]
LGTM. Thanks for catching this Jay

**Comment by jkakavas** [comment]
`testInvalidateCorrectTokensFromLogoutRequest` is failing because we use the token's length as an indication of whether we're dealing with a hashed token or not*  in 

https://github.com/elastic/elasticsearch/blob/49bd667cbd156fbd588d867c40f8b760c47281e1/x-pack/plugin/security/src/main/java/org/elasticsearch/xpack/security/authc/TokenService.java#L819:L822

Now that Base64 `urlEncoder` is used without padding, the expected length needs to be adjusted. I took the liberty of making the change and trigger CI in the interest of time. 


* When logout is invoked, we search for all the tokens of the user in the tokens index and then invaliate the ones we found ( which are hashed ), but when a specific token is requested to be invalidated by the user, we have it in the format that the user has it ( not hashed )

**Pull request merged**
