### PR TITLE
Harden ops counting in AbstractSearchAsyncAction

### PR DESCRIPTION
**Pull request by s1monw**
Today we account for too many response with an `IllegalStateException` in
`AbstractSearchAsyncAction` while this is something that should never happen
we should rather assert that we are always have less or equal the number of
expected ops when waiting for responses.

### CODE REVIEW

**Review by jpountz — COMMENTED** [review]
Can you make it a hard AssertionError so that it would not be ignored when assertions are disabled?

**Comment by s1monw** [comment]
done @jpountz

**Review by jpountz — APPROVED** [review]
LGTM

**Comment by s1monw** [comment]
@elasticmachine test this please

**Pull request merged**
