### PR TITLE
Skip capturing least/most FS info for an FS with no total

### PR DESCRIPTION
**Pull request by dakrone**
If an operating system reports -1 for the total bytes of a filesystem
path, we should ignore it when capturing the least and most available
statistics.

Relates to #15919

### CODE REVIEW

**Comment by rmuir** [comment]
the logic looks fine for this, but we may want to add a test for negative free (but not total). I know this can happen on freebsd.

**Comment by dakrone** [comment]
Pushed another commit that tests when 'free' is negative but total is not.

**Comment by rmuir** [comment]
thanks!

**Comment by dakrone** [comment]
I merged this into master and 2.x

**Pull request closed without merging**
