### PR TITLE
Fix Failures in HierarchyCircuitBreakerServiceTests (#81073)

### PR DESCRIPTION
**Pull request by original-brownbear**
In #81033 the type of map that is iterated over to compute the various
usage values was changed. This changed the order of the various breakers
in the exception string and made it less deterministic (although it was always
just deterministic by accident in these tests).
=> we shouldn't assume any order in the assertions

backport of #81073

### CODE REVIEW

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/rest-compatibility

**Comment by arteam** [comment]
@elasticmachine 
run elasticsearch-ci/bwc
run elasticsearch-ci/rest-compatibility

**Comment by droberts195** [comment]
Since the BWC tests aren't disabled you'll need to wait for https://github.com/elastic/elasticsearch/pull/82475 to be merged then merge master into this PR.  The BWC tests can't pass until that's done (or the BWC tests are disabled of course).

**Comment by original-brownbear** [comment]
@elasticmachine update branch

**Pull request merged**
