### PR TITLE
Fix highlighting for match_phrase_prefix query inside nested

### LINKED ISSUE #70922: Highlight field query does not contain highlight(s) after migration to 7.6.2
**Elasticsearch version** (`bin/elasticsearch --version`): 7.6.2

**Plugins installed**: []

**JVM version** (`java -version`): 1.8

**OS version** (`uname -a` if on a Unix-like system): Ubuntu 5.4.0-70-generic, Elastic running as container

**Description of the problem including expected versus actual behavior**:
I'm trying to migrate from Elastic 6.6.2 to 7.6.2 and the queries containing highlight fields don't work any longer. The same query returns results containing highlighted values in 6.x version, but it doesn't contain any highlight field for 7.6.2.
To me it looks like a regression bug.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

Mapping is the following:
```
{
  "candidate-profiles" : {
    "mappings" : {
      "properties" : {
        "_class" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "availability" : {
          "type" : "keyword"
        },
        "availabilityEndDate" : {
          "type" : "date",
          "format" : "date"
        },
        "drivingCategories" : {
          "type" : "keyword"
        },
        "externalId" : {
          "type" : "keyword"
        },
        "gender" : {
          "type" : "keyword"
        },
        "geoPoint" : {
          "type" : "geo_point"
        },
        "highestDegree" : {
          "type" : "text"
        },
        "highestEducationLevel" : {
          "type" : "integer"
        },
        "id" : {
          "type" : "keyword"
        },
        "jobExperiences" : {
          "type" : "nested",
          "properties" : {
            "degree" : {
              "type" : "integer"
            },
            "education" : {
              "type" : "integer"
            },
            "experience" : {
              "type" : "integer"
            },
            "graduation" : {
              "type" : "keyword"
            },
            "isLastJob" : {
              "type" : "boolean"
            },
            "occupation" : {
              "properties" : {
                "avamCode" : {
                  "type" : "long"
                },
                "bfsCode" : {
                  "type" : "long"
                }
              }
            },
            "remark" : {
              "type" : "search_as_you_type",
              "analyzer" : "ascii_folding",
              "max_shingle_size" : 3
            },
            "wanted" : {
              "type" : "boolean"
            }
          }
        },
        "languages" : {
          "type" : "nested",
          "properties" : {
            "code" : {
              "type" : "text",
              "analyzer" : "language_iso_code_synonym_analyzer"
            },
            "spokenLevel" : {
              "type" : "integer"
            },
            "writtenLevel" : {
              "type" : "integer"
            }
          }
        },
        "preferredWorkCantons" : {
          "type" : "keyword"
        },
        "preferredWorkRegions" : {
          "type" : "keyword"
        },
        "protected" : {
          "type" : "boolean"
        },
        "public" : {
          "type" : "boolean"
        },
        "residenceCantonCode" : {
          "type" : "keyword"
        },
        "showProtectedData" : {
          "type" : "boolean"
        },
        "workForms" : {
          "type" : "keyword"
        },
        "workLoad" : {
          "type" : "integer"
        }
      }
    }
  }
}
```

Sample data:
```
{
  "took" : 2,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 3,
      "relation" : "eq"
    },
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "candidate-profiles",
        "_type" : "_doc",
        "_id" : "57070211-81ac-4b2f-80ac-491617d78277",
        "_score" : 1.0,
        "_source" : {
          "_class" : "ch.admin.seco.service.candidate.domain.candidate.elasticsearch.CandidateProfileDocument",
          "id" : "57070211-81ac-4b2f-80ac-491617d78277",
          "externalId" : "plrggAwm7UudpyOwutb0oHLCbI8EzueE",
          "public" : true,
          "protected" : false,
          "showProtectedData" : false,
          "gender" : "MALE",
          "availability" : "IMMEDIATE",
          "residenceCantonCode" : "en",
          "workForms" : [
            "SHIFT_WORK",
            "HOME_WORK"
          ],
          "preferredWorkRegions" : [
            "zr",
            "xr"
          ],
          "preferredWorkCantons" : [
            "gr"
          ],
          "jobExperiences" : [
            {
              "occupation" : {
                "avamCode" : 12,
                "bfsCode" : 1112
              },
              "experience" : 3,
              "graduation" : "NONE",
              "degree" : 12,
              "education" : 4,
              "remark" : "Java developer",
              "isLastJob" : false,
              "wanted" : true
            },
            {
              "occupation" : {
                "avamCode" : 11,
                "bfsCode" : 1111
              },
              "experience" : 3,
              "graduation" : "NONE",
              "degree" : 12,
              "education" : 4,
              "remark" : "angular",
              "isLastJob" : true,
              "wanted" : true
            }
          ],
          "languages" : [
            {
              "code" : "en",
              "writtenLevel" : 2,
              "spokenLevel" : 3
            }
          ],
          "drivingCategories" : [
            "D",
            "B"
          ],
          "highestEducationLevel" : 4,
          "highestDegree" : "TER_BACHELOR_UNIVERSITAET",
          "workLoad" : 0,
          "availabilityEndDate" : "2021-04-10",
          "geoPoint" : {
            "lat" : 9.25,
            "lon" : 7.12
          }
        }
      },
      {
        "_index" : "candidate-profiles",
        "_type" : "_doc",
        "_id" : "fbbb486b-6116-459a-8dd7-6f1abb847155",
        "_score" : 1.0,
        "_source" : {
          "_class" : "ch.admin.seco.service.candidate.domain.candidate.elasticsearch.CandidateProfileDocument",
          "id" : "fbbb486b-6116-459a-8dd7-6f1abb847155",
          "externalId" : "xllDWQLiHb30vL0XrBy87MZsMHMF8AsZ",
          "public" : true,
          "protected" : false,
          "showProtectedData" : false,
          "gender" : "MALE",
          "availability" : "IMMEDIATE",
          "residenceCantonCode" : "en",
          "workForms" : [
            "SHIFT_WORK",
            "HOME_WORK"
          ],
          "preferredWorkRegions" : [
            "zr",
            "xr"
          ],
          "preferredWorkCantons" : [
            "gr"
          ],
          "jobExperiences" : [
            {
              "occupation" : {
                "avamCode" : 12,
                "bfsCode" : 1112
              },
              "experience" : 3,
              "graduation" : "NONE",
              "degree" : 12,
              "education" : 4,
              "remark" : "Java software developer with angular experience",
              "isLastJob" : true,
              "wanted" : true
            }
          ],
          "languages" : [
            {
              "code" : "en",
              "writtenLevel" : 2,
              "spokenLevel" : 3
            }
          ],
          "drivingCategories" : [
            "D",
            "B"
          ],
          "highestEducationLevel" : 4,
          "highestDegree" : "TER_BACHELOR_UNIVERSITAET",
          "workLoad" : 0,
          "availabilityEndDate" : "2021-04-10",
          "geoPoint" : {
            "lat" : 9.25,
            "lon" : 7.12
          }
        }
      },
      {
        "_index" : "candidate-profiles",
        "_type" : "_doc",
        "_id" : "3c0a9098-93dc-45fc-87ea-73eeea8cc66c",
        "_score" : 1.0,
        "_source" : {
          "_class" : "ch.admin.seco.service.candidate.domain.candidate.elasticsearch.CandidateProfileDocument",
          "id" : "3c0a9098-93dc-45fc-87ea-73eeea8cc66c",
          "externalId" : "O5kcwg5G43jTh6a38UqlNM7DCPa3aUIr",
          "public" : true,
          "protected" : false,
          "showProtectedData" : false,
          "gender" : "MALE",
          "availability" : "IMMEDIATE",
          "residenceCantonCode" : "en",
          "workForms" : [
            "SHIFT_WORK",
            "HOME_WORK"
          ],
          "preferredWorkRegions" : [
            "zr",
            "xr"
          ],
          "preferredWorkCantons" : [
            "gr"
          ],
          "jobExperiences" : [
            {
              "occupation" : {
                "avamCode" : 13,
                "bfsCode" : 1113
              },
              "experience" : 3,
              "graduation" : "NONE",
              "degree" : 12,
              "education" : 4,
              "remark" : "Objective-C/Swift developer",
              "isLastJob" : true,
              "wanted" : true
            }
          ],
          "languages" : [
            {
              "code" : "en",
              "writtenLevel" : 2,
              "spokenLevel" : 3
            }
          ],
          "drivingCategories" : [
            "D",
            "B"
          ],
          "highestEducationLevel" : 4,
          "highestDegree" : "TER_BACHELOR_UNIVERSITAET",
          "workLoad" : 0,
          "availabilityEndDate" : "2021-04-10",
          "geoPoint" : {
            "lat" : 9.25,
            "lon" : 7.12
          }
        }
      }
    ]
  }
}

```

Here is the query, as I have it right now:
```GET candidate-profiles/_search
{
  "highlight": {
    "fields": {
      "jobExperiences.remark": {
        "fragment_size": 300,
        "number_of_fragments": 10
      }
    }
  },
  "query": {
    "bool": {
      "must": [
        {
          "nested": {
            "query": {
              "bool": {
                "must": [
                  {
                    "match_phrase_prefix": {
                      "jobExperiences.remark": {
                        "query": "developer",
                        "slop": 0,
                        "max_expansions": 50,
                        "boost": 1
                      }
                    }
                  },
                  {
                    "term": {
                      "jobExperiences.wanted": {
                        "value": true,
                        "boost": 1
                      }
                    }
                  }
                ],
                "adjust_pure_negative": true,
                "boost": 1
              }
            },
            "path": "jobExperiences",
            "ignore_unmapped": false,
            "score_mode": "avg",
            "boost": 1
          }
        }
      ],
      "adjust_pure_negative": true,
      "boost": 1
    }
  }
}```

1. Build a query for 6.6.2 with highlight field.
2. Query results contain highlighted values
3. Take the exact same query into 7.6.2. Query returns the correct results, but without highlight at all.

### PR DESCRIPTION
**Pull request by cbuescher**
Some refactoring between versions 7.2 and 7.3 seems to have broken highlighting
using the default "unified" highlighter when using a `match_phrase_prefix` query
inside a nested query. Re-adding handling of `ESToParentBlockJoinQuery` to the
CustomUnifiedHighlighter#rewriteCustomQuery method solves the problem.

Closes #70922

### CODE REVIEW

**Comment by cbuescher** [comment]
fyi the commit that removed the rewrite was 01ab82f866d311f3128e8089bc2497d71fdfa6a9 when moving to Lucene 8.1. Maybe this logic needs to go somewhere else, but it seems to solve the issue and fixes the test in this location.

**Comment by cbuescher** [comment]
@jimczi would you mind taking a look at this since you seem to have authored the commit that adapts to Lucene 8.1 and removes the code that I added again. Maybe there are other options to fix this bug that I haven't considered.

**Review by jimczi — APPROVED** [review]
LGTM

**Comment by cbuescher** [comment]
@jimczi thanks for the review

**Pull request merged**
