### PR TITLE
QL: Remove constant_keyword field type

### PR DESCRIPTION
**Pull request by astefan**
Removes constant_keyword field type from *QL, after the [keyword family of fields](https://github.com/elastic/elasticsearch/pull/58315) has been added to Elasticsearch.

Addresses https://github.com/elastic/elasticsearch/issues/58471.

### CODE REVIEW

**Comment by astefan** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample-windows

**Review by bpintea — APPROVED** [review]
LGTM and the tests I've run work as expected.
However, there is a theoretical possibility that an old driver (say 7.8) will send a request with a parameter of this type (to a 7.10 server). With the PR we'd reject the request which does break the backwards compatibility strictly speaking. But I believe this is such a small corner case and so unlikely that it's negligible.

**Comment by bpintea** [comment]
> there is a theoretical possibility that an old driver (say 7.8) will send a request with a parameter of this type (to a 7.10 server). With the PR we'd reject the request which does break the backwards compatibility strictly speaking.

Looking deeper into the issue, the statement above is wrong and I think we could still safely merge the PR (past the PR conflict resolution).
As far as the JDBC client is concerned, the types we report are uniquely identified by their name, not `DATE_TYPE` or some other ID:
```
        TYPE_NAME        |   DATA_TYPE   |   ...
-------------------------+---------------+---------------+-...
CONSTANT_KEYWORD         |12             |...
IP                       |12             |...
KEYWORD                  |12             |...
TEXT                     |12             |...
```

We don't export a "ConstantKeyword" class in our JDBC driver and the the [JDBC interface](https://docs.oracle.com/en/java/javase/15/docs/api/java.sql/java/sql/PreparedStatement.html#setObject(int,java.lang.Object,java.sql.SQLType)) won't take a type name when setting parameters, but only a `SQLType`, which maps the reported `DATA_TYPE` and which is always a [VARCHAR](https://github.com/elastic/elasticsearch/blob/3f8ee81634e4a791ffc1756dbb7c7e0df57e5d1c/x-pack/plugin/sql/jdbc/src/main/java/org/elasticsearch/xpack/sql/jdbc/EsType.java#L28) (so changing that enum is luckly irrelevant). Meaning that all our JDBC driver releases send `KEYWORD` parameter types.


The only way to send a `CONSTANT_KEYWORD` parameter is directly over the REST if'ace (which btw, I'm not sure if it's bwc-tested?). And which might still not be worth the effort of accommodating for, backwards compatibility-wise.

WDYT, @costin, @astefan?

**Comment by costin** [comment]
LGTM

**Review by costin — COMMENTED** [review]
LGTM

**Review by costin — APPROVED** [review]

**Comment by bpintea** [comment]
@elasticmachine update branch

**Comment by bpintea** [comment]
@elasticmachine update branch

**Comment by bpintea** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample-unix

**Comment by bpintea** [comment]
@elasticmachine update branch

**Pull request merged**
