### PR TITLE
Removal of dead code in ScriptedMetricAggregationBuilder

### PR DESCRIPTION
**Pull request by KoenDG**
This code removes a few lines of dead code from ScriptedMetricAggregationBuilder. Just completely dead code, it adds things to a Set that is then not used in any way.

This PR is related to PR #24321 as requested by @jasontedor 

===========

1. Contributor agreement: Has been signed

2. Contributor guidelines: I have read them.

3. Gradle check: build successful.

4. PR is against master

5. The PR is not OS specific.

6. I'm not part of a class.

### CODE REVIEW

**Review by abeyad — APPROVED** [review]
LGTM

**Review by nik9000 — APPROVED** [review]
He's dead, Jim.

**Review by abeyad — CHANGES_REQUESTED** [review]
@KoenDG there are now unused imports (`Set` and `HashSet`) if those can please be removed

**Comment by KoenDG** [comment]
@abeyad Thanks for catching that. Imports removed.

**Review by abeyad — APPROVED** [review]
LGTM

**Comment by abeyad** [comment]
thank you @KoenDG

**Pull request merged**
