### PR TITLE
Formalize and Streamline Buffer Sizes used by Repositories

### PR DESCRIPTION
**Pull request by original-brownbear**
Due to complicated access checks (reads and writes execute in their own access context) on some repositories (GCS, Azure, HDFS), using a hard coded buffer size of 4k for restores was needlessly inefficient.
By the same token, the use of stream copying with the default 8k buffer size  for blob writes was inefficient as well.

We also had dedicated, undocumented buffer size settings for HDFS and FS repositories. For these two we would use a 100k buffer by default. We did not have such a setting for e.g. GCS though, which would only use an 8k read buffer which is needlessly small for reading from a raw `URLConnection`.

This commit adds an undocumented setting that sets the default buffer size to `128k` for all repositories. It removes wasteful allocation of such a large buffer for small writes and reads in case of HDFS and FS repositories (i.e. still using the smaller buffer to write metadata) but uses a large buffer for doing restores and uploading segment blobs.

This should speed up Azure and GCS restores and snapshots in a non-trivial way as well as save some memory when reading small blobs on FS and HFDS repositories.

Marking as draft for now since I think this needs some discussion and up-front benchmarking. The benchmarking is something that is being looked into by @hub-cap in the near future as far as I understand.

-> @hub-cap you can use this branch and just set the repository setting `buffer_size` if you want to experiment with different buffer sizes for restores :)

Some caveats:

* The buffer sizing is still not 100% stream-lined and I left out adjusting it for e.g. S3 writes (those are hitting the physical limits of S3 anyway according to our benchmarks) and limited myself to the known performance pain points for now
* For ranged-reads from fs-repositories by searchable snapshots the buffer size is now reduced. I don't know if this matters much, but if we think it does we should fix it by using larger buffers upstream in searchable snapshots IMO. 8k buffers aren't great for disk writes either so we should use a larger copy buffer instead of a larger read buffer in the repository impl.

### CODE REVIEW

**Comment by original-brownbear** [comment]
@hub-cap tested this and saw an up to 25% increase in restore speeds on GCS. I'm marking this ready for review. I think this will also be very helpful on Azure in improving throughput. I wouldn't make this setting public for users to play with since there's probably not much point in doing so and a lot of mistakes can be made. `128k` seems like a reasonable choice that likely won't have any serious memory effects even with a larger number of snapshot threads while still way lowering the number of expensive things that happen on every write for some repositories by a significant factor (either x32 for restores or x16 for snapshots in most cases)

**Review by ywelsch — APPROVED** [review]
LGTM. Should we get this into 7.9 as it helps with snapshot performance?

**Comment by original-brownbear** [comment]
Thanks @ywelsch !

> Should we get this into 7.9 as it helps with snapshot performance?

Yea, let's do that, IMO -> will do.

**Comment by ydubreuil** [comment]
Linking to https://github.com/elastic/cloud/issues/58379#issuecomment-653038076 to give some more context on what happens at the block layer level. It makes total sense to use a bigger buffer size to avoid syscall costs.

**Pull request merged**
