### PR TITLE
Use versions specific distribution folders so we don't need to clean up

### LINKED ISSUE #46014: [CI] :qa:full-cluster-restart:v7.3.2#upgradedClusterTest Failed on Windows
The test goal failed with this error:

```

* Where:
--
Build file 'C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\qa\full-cluster-restart\build.gradle' line: 63
 
* What went wrong:
Execution failed for task ':qa:full-cluster-restart:v7.3.2#upgradedClusterTest'.
> Unable to delete directory 'C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\qa\full-cluster-restart\build\testclusters\v7.3.2-0\distro'
Failed to delete some children. This might happen because a process has files open or has its working directory set in the target directory.
- C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\qa\full-cluster-restart\build\testclusters\v7.3.2-0\distro\lib\elasticsearch-7.3.2-SNAPSHOT.jar
- C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\qa\full-cluster-restart\build\testclusters\v7.3.2-0\distro\lib\elasticsearch-cli-7.3.2-SNAPSHOT.jar
- C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\qa\full-cluster-restart\build\testclusters\v7.3.2-0\distro\lib\elasticsearch-core-7.3.2-SNAPSHOT.jar
- C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\qa\full-cluster-restart\build\testclusters\v7.3.2-0\distro\lib\elasticsearch-geo-7.3.2-SNAPSHOT.jar
- C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\qa\full-cluster-restart\build\testclusters\v7.3.2-0\distro\lib\elasticsearch-launchers-7.3.2-SNAPSHOT.jar
- C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\qa\full-cluster-restart\build\testclusters\v7.3.2-0\distro\lib\elasticsearch-plugin-classloader-7.3.2-SNAPSHOT.jar
- C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\qa\full-cluster-restart\build\testclusters\v7.3.2-0\distro\lib\elasticsearch-secure-sm-7.3.2-SNAPSHOT.jar
- C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\qa\full-cluster-restart\build\testclusters\v7.3.2-0\distro\lib\elasticsearch-x-content-7.3.2-SNAPSHOT.jar
- C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\qa\full-cluster-restart\build\testclusters\v7.3.2-0\distro\lib\HdrHistogram-2.1.9.jar
- C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\qa\full-cluster-restart\build\testclusters\v7.3.2-0\distro\lib\hppc-0.8.1.jar
- C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\qa\full-cluster-restart\build\testclusters\v7.3.2-0\distro\lib\jackson-core-2.8.11.jar
- C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\qa\full-cluster-restart\build\testclusters\v7.3.2-0\distro\lib\jackson-dataformat-cbor-2.8.11.jar
- C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\qa\full-cluster-restart\build\testclusters\v7.3.2-0\distro\lib\jackson-dataformat-smile-2.8.11.jar
- C:\Users\jenkins\workspace\elastic+elasticsearch+master+multijob-windows-compatibility\os\windows-2016\qa\full-cluster-restart\build\testclusters\v7.3.2-0\distro\lib\jackson-dataformat-yaml-2.8.11.jar

```

Not sure where this is coming from, but it seems first a cluster fails to form and then the cleanup fails because Gradle tries to delete files still in use by a running test cluster.

[Build Scan](https://scans.gradle.com/s/kcwp26sgeicyi)

### PR DESCRIPTION
**Pull request by alpar-t**
When retarting the cluster we clean up old distribution files that might
still be in use by the OS.
Windows closes resources of ded processes async, so we do a couple of
retries to get arround it.

Closes #46014

### CODE REVIEW

**Review by mark-vieira — COMMENTED** [review]
Perhaps instead we should do a proper shutdown when performing a restart? It seems the rationale in the [comment here](https://github.com/elastic/elasticsearch/blob/96b4f3df9067d579bf7e22e09613ea94f4f05462/buildSrc/src/main/java/org/elasticsearch/gradle/testclusters/ElasticsearchNode.java#L730-L731) is no longer accurate.

**Comment by atorok** [comment]
@mark-vieira we could do that in addition to what's being done here. 
Shutting down gracefully does not guarantee that we'll be able to remove the files, it's just how Windows works.  On the other hand, we would be testing something a bit different as shutting down non gracefully is probably more prone to corruption or other issues that could be caught by the test

**Comment by mark-vieira** [comment]
I'm wondering if the improvements in Gradle 6.0 described [here](https://docs.gradle.org/nightly/release-notes.html#more-robust-file-deletion-on-windows) might help us as well.

**Comment by rjernst** [comment]
It's still unclear to me why we are doing deletions within sync. Why are we not using unique directories per started instance of ES? This goes back to immutability of nodes; I don't think we should be reusing the same directory, but pointing the "restarted" node to the old data directory.

**Review by rjernst — COMMENTED** [review]
Thanks for the change @atorok. This looks better. The PR title should be changed though. Also, why is there a version number in two different locations within the path now?

**Comment by atorok** [comment]
@rjernst It's because we have the "old" version in the cluster name for bwc tests. The cluster which tests backwards compatibility wit `7.5.0` will be called `v7.5.0`.

**Comment by atorok** [comment]
@elasticmachine run elasticsearch-ci/1 and  run  elasticsearch-ci/2

**Comment by atorok** [comment]
@elasticmachine run elasticsearch-ci/1 and run elasticsearch-ci/2

**Review by mark-vieira — APPROVED** [review]
👍 on these changes. I think having per-version folders will help with debugging as well when thing go haywire as we can see the history of the cluster. Deleting stuff could potentially remove helpful data that useful to debugging failures.

**Review by rjernst — APPROVED** [review]
LGTM too

**Comment by mark-vieira** [comment]
@atorok What's holding up the backport here?

**Comment by atorok** [comment]
Nothing any more, the previous back-ports just went trough so will do it soon

**Pull request merged**
