### PR TITLE
Register `indices.query.bool.max_clause_count` setting

### LINKED ISSUE #18336: index.query.bool.max_clause_count can not be set
Index level setting is not allowed in elastic search.yml with 5.0.0-alpha2.

And with _setting or _template API I got:
{
"error": {
"root_cause": [
{
"type": "illegal_argument_exception",
"reason": "unknown setting [index.query.bool.max_clause_count]"
}
],
"type": "illegal_argument_exception",
"reason": "unknown setting [index.query.bool.max_clause_count]"
},
"status": 400
}

Is this a bug? Any work-around?

### PR DESCRIPTION
**Pull request by s1monw**
This commit registers `indices.query.bool.max_clause_count` as a node
level setting and removes support for its synonym setting
`index.query.bool.max_clause_count`.

Closes #18336

### CODE REVIEW

**Comment by rjernst** [comment]
Lgtm

**Comment by bleskes** [comment]
Can we maybe add a little explaination to the breaking change as to why it has to be a node level setting, despite of the fact that at face value it should be an index level and isn't really node dependent?  (i.e., Lucene has this as a static thing, so it has to be like this). Also, I see it is marked as deprecated, is there is any other better way to accomplish this/plans to make one? if so it will be nice to mention that as well.

**Comment by s1monw** [comment]
@bleskes I don't get what you mean it was never a index level setting. it just had the confusing prefix.

**Comment by rjernst** [comment]
I wonder if we should (in addition to this good rename) move the settings validation check in SettingsModule before the check for index level settings existing in node settings? This improves the output here so we get "did you mean" behavior with the old setting like this:

```
[elasticsearch] Exception in thread "main" java.lang.IllegalArgumentException: unknown setting [index.query.bool.max_clause_count] did you mean [indices.query.bool.max_clause_count]?
```

Otherwise with this change we get a confusing message stating the setting should be moved to indexes:

```
[elasticsearch] Please ensure all required values are updated on all indices by executing:
[elasticsearch] curl -XPUT 'http://localhost:9200/_all/_settings?preserve_existing=true' -d '{
[elasticsearch] "index.query.bool.max_clause_count" : "200"
[elasticsearch] }'
```

**Comment by bleskes** [comment]
> it was never a index level setting. it just had the confusing prefix.

Oh , you are of course right. Got confused by the confusing prefix. Sorry for the noise re that. 

My question re-deprecation still stands though - is there (a plan for) an alternative configuration option?

**Comment by s1monw** [comment]
> My question re-deprecation still stands though - is there (a plan for) an alternative configuration option?

I think there aren't any satisfying ways to fix this. For instance you would need to add a setter to anything that can rewrite to BQ which can set a setter on BQ to pass on the setting. One way of doing it would be a thread local which sucks too but I think that's the reason for the simple but global way of setting it.

**Comment by s1monw** [comment]
> I wonder if we should (in addition to this good rename) move the settings validation check in SettingsModule before the check for index level settings existing in node settings? This improves the output here so we get "did you mean" behavior with the old setting like this:

@rjernst I think the check it correct there otherwise you won't get past that point since the other leftover `index.*` settings you have in the node settings will cause failures otherwise. I think I will just special case that setting there?

**Comment by rjernst** [comment]
>  I think I will just special case that setting there?

Sure, sounds good.

**Comment by bleskes** [comment]
> I think there aren't any satisfying ways to fix this.

Sure. Does this mean we should not mark the settings as deprecated?

**Comment by s1monw** [comment]
> Sure. Does this mean we should not mark the settings as deprecated?

I don't see where this PR deprecates anything? I am confused how is this related?

**Comment by bleskes** [comment]
> I don't see where this PR deprecates anything?

The reason why I mentioned is the usage of `Setting.Property.Deprecated` [here](https://github.com/elastic/elasticsearch/pull/18341/files#diff-cc9584700dd179d6f04f643b578a85f9R295).

**Comment by s1monw** [comment]
> The reason why I mentioned is the usage of Setting.Property.Deprecated here.

how the fuck.... not sure how that got there - not intended. That explains the confusion :) I will fix and push

**Pull request merged**
