### PR TITLE
Update update.asciidoc

### PR DESCRIPTION
**Pull request by Mengbuxiu**
my elasticsearch version is 7.15.2, and I found it's not working, so I changed it.

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Review by Mengbuxiu — COMMENTED** [review]
sign

**Comment by Mengbuxiu** [comment]
pull

**Comment by jrodewig** [comment]
Hi @Mengbuxiu,

Thanks for raising this PR. However, these changes kind of defeat the purpose of this section and example. The example needs to include the `scripted_upsert` parameter.

The example likely didn't work because it uses a stored script id rather than specifying the source in the request. I've opened https://github.com/elastic/elasticsearch/pull/81481 to address that and make the example more copy/paste-able.

I'm going to close this PR. Thanks again!

**Comment by Mengbuxiu** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        understand,thand you.
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                woooodlin
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    On 12/8/2021 06:36，James ***@***.***> wrote： 



Hi @Mengbuxiu,
Thanks for raising this PR. However, these changes kind of defeat the purpose of this section and example. The example needs to include the scripted_upsert parameter.
The example likely didn't work because it uses a stored script id rather than specifying the source in the request. I've opened #81481 to address that and make the example more copy/paste-able.
I'm going to close this PR. Thanks again!

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Pull request closed without merging**
