### PR TITLE
Fix Bug Causing Queued Snapshots of Deleted Indices to Never Finalize

### PR DESCRIPTION
**Pull request by original-brownbear**
We have to run the loop checking for completed snapshots if we see an index disappearing.
Otherwise, we never get around to finalizing a queued snapshot stuck after a clone if the
index is deleted during cloning and have to needlessly wait to finalize partial snapshots that 
get completed through concurrent index deletes.

### CODE REVIEW

**Comment by original-brownbear** [comment]
@elasticmachine update branch

**Review by tlrx — APPROVED** [review]
LGTM but another pair of eyes would be good

**Review by DaveCTurner — APPROVED** [review]
LGTM2

**Comment by original-brownbear** [comment]
Thanks Tanguy + David!

**Pull request merged**
