### PR TITLE
Validate composite afterKey formatting in standard InternalComposite constructor only

### PR DESCRIPTION
**Pull request by romseygeek**
We can't validate inputs in a StreamInput constructor, because these constructors
expect everything to be well-formed, and if we throw an exception here we can
knock a node over.  However, we still want to validate composite afterKeys before
we serialize to XContent, as chunked x-content serialization assumes that we don't
throw exceptions at this point either.

This commit adds afterKey validation to the standard InternalComposite constructor,
which will always be used on the co-ordinating node to reduce InternalComposites
that may have come from remote nodes with no validation, because we enforce 
reduction even on composite aggregations from a single shard.

### CODE REVIEW

**Comment by romseygeek** [comment]
Trying this one again...  The only places that this doesn't cover is in eql, where we only use a composite terms agg so formatting doesn't apply, and in rollup where there is already a comment that says `TODO handle failures` (cc @salvatore-campagna) so I don't think I'm breaking anything extra.  Testing this is tricky though, especially as the last version of this passed CI happily before being merged.

**Review by not-napoleon — APPROVED** [review]
I mean, it looks good to me, but so did the last one.  🤞🏼

**Comment by martijnvg** [comment]
Maybe the label `test-full-bwc` should be added here? Since the failure of the previous pr were mainly bwc failures?

**Comment by romseygeek** [comment]
@elasticmachine update branch

**Comment by martijnvg** [comment]
@elasticmachine run elasticsearch-ci/full-bwc

**Comment by martijnvg** [comment]
(last full bwc failure was caused by some network issue)

**Comment by romseygeek** [comment]
@elasticmachine update branch

**Comment by romseygeek** [comment]
BWC seems happy @martijnvg - are we ok for me to merge?

**Review by martijnvg — APPROVED** [review]
> BWC seems happy @martijnvg - are we ok for me to merge?

Yes. LGTM.

**Pull request merged**
