### PR TITLE
[DOCS] remove es.scripting.update.ctx_in_params system property for 7.x

### PR DESCRIPTION
**Pull request by ielatif**
Closing #41642

### CODE REVIEW

**Comment by elasticcla** [comment]
Hi @ielatif, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in your Git [commit](https://github.com/elastic/elasticsearch/pull/41643.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by ielatif** [comment]
Closing https://github.com/elastic/elasticsearch/issues/41642

**Comment by ielatif** [comment]
@elasticmachine test this please

**Comment by nik9000** [comment]
@elasticmachine, test this please.

@ielatif, Elasticmachine is deaf to folks outside of the `elastic` organization.

**Comment by ielatif** [comment]
> @elasticmachine, test this please.
> 
> @ielatif, Elasticmachine is deaf to folks outside of the `elastic` organization.

Thanks

**Comment by ielatif** [comment]
@rjernst can you please review this?

**Comment by rjernst** [comment]
Looks good, thanks for the PR!

**Review by rjernst — APPROVED** [review]

**Pull request merged**
