### PR TITLE
_validate request does not honour ignore_unavailable

### LINKED ISSUE #116594: `_validate` doesn't honour ignore_unavailable option with closed index
**Elasticsearch version: current master** 

### Descprition
Calling the `_validate` API against an existing and closed index with `ignore_unavailable=true` fails with `cluster_block_exception`.

### Steps to Reproduce
```
PUT myindex

POST myindex/_close

POST myindex/_validate/query?explain=true&ignore_unavailable=true
{
  "query":{
    "query_string":{
      "query":"abc AND" 
    }
  }
}
```

The last step will fail with:
```
{
    "error": {
        "root_cause": [
            {
                "type": "cluster_block_exception",
                "reason": "index [myindex] blocked by: [FORBIDDEN/4/index closed];"
            }
        ],
        "type": "cluster_block_exception",
        "reason": "index [myindex] blocked by: [FORBIDDEN/4/index closed];"
    },
    "status": 403
}
```

### Definition of Done

The API should return an `index_closed_exception` for the case of a closed index
```
GET myindex/_field_caps?fields=price

{
    "error": {
        "root_cause": [
            {
                "type": "index_closed_exception",
                "reason": "closed",
                "index_uuid": "B9sFIzOCRB-yPjh2Q9x1TA",
                "index": "myindex"
            }
        ],
        "type": "index_closed_exception",
        "reason": "closed",
        "index_uuid": "B9sFIzOCRB-yPjh2Q9x1TA",
        "index": "myindex"
    },
    "status": 400
}
```

And ignore the closed index, when `ignore_unavailable=true`

```GET myindex/_field_caps?fields=price&ignore_unavailable=true


{
    "indices": [],
    "fields": {}
}
```

### PR DESCRIPTION
**Pull request by drempapis**
Querying an existing and `closed` index fails with `cluster_block_exception` when the _validate with ignore_unavailable=true is called.

Similar case to #116021
Closes #116594

### CODE REVIEW

**Comment by drempapis** [comment]
@elasticmachine update branch

**Review by piergm — APPROVED** [review]
LGTM! 😄 Thanks for working on this @drempapis

**Comment by drempapis** [comment]
@elasticmachine update branch

**Comment by javanna** [comment]
@drempapis did you mean to backport this to 8.x as well?

**Comment by drempapis** [comment]
> @drempapis did you mean to backport this to 8.x as well?

Yes, that was my intention

**Comment by drempapis** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.x|[](https://github.com/elastic/elasticsearch/pull/116717)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

**Pull request merged**
