### PR TITLE
add 7.1.1 and 6.8.1 versions

### PR DESCRIPTION
**Pull request by jakelandis**
Related: https://github.com/elastic/elasticsearch/pull/42240
Related: https://github.com/elastic/elasticsearch/pull/42242
Related: https://github.com/elastic/elasticsearch/pull/42253

### CODE REVIEW

**Review by rjernst — APPROVED** [review]
LGTM

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by jakelandis** [comment]
@elasticmachine run elasticsearch-ci/1

**Comment by jakelandis** [comment]
@elasticmachine run elasticsearch-ci/bwc
@elasticmachine run elasticsearch-ci/default-distro

**Pull request merged**
