### PR TITLE
fix assertShardStats in RoutingNodes

### PR DESCRIPTION
**Pull request by asce0705**
The last shard id is ignored while asserting the assigned shardRoutings in RoutingNodes.

### CODE REVIEW

**Comment by asce0705** [comment]
> Pinging @elastic/es-distributed (Team:Distributed)

Is there anything I can help for this pull request?

**Comment by DaveCTurner** [comment]
@elasticmachine ok to test

**Comment by DaveCTurner** [comment]
Failure is https://github.com/elastic/elasticsearch/issues/66907. @elasticmachine please run elasticsearch-ci/1

**Comment by DaveCTurner** [comment]
@elasticmachine update branch

**Pull request merged**
