### PR TITLE
Warn of change of default of wait_for_active_shards

### LINKED ISSUE #66419: Undocumented(?) change in default for wait_for_active_shards on close index requests
In 7.x the default for `?wait_for_active_shards` on a `POST /index/_close` request is `NONE` (i.e. do not wait) whereas in 8.0 it defaults to `DEFAULT` (i.e. whatever the index metadata says). I took a quick look at the breaking changes docs for 8.0 and didn't see this mentioned, and nor do I see anywhere that we're emitting deprecation logs indicating the change in behaviour.

This caught me out when writing some tests (see https://github.com/elastic/elasticsearch/pull/66415). Should we consider this a breaking change and warn on cases where folk are relying on it? Perhaps not, it might not break anything. I'm opening this issue to remind us to discuss it at some point before releasing 8.0.

@tlrx WDYT?

### PR DESCRIPTION
**Pull request by DaveCTurner**
In 7.x the close indices API defaults to `?wait_for_active_shards=0` but
from 8.0 it will default to respecting the index settings instead. This
commit introduces the `index-setting` value for this parameter on this
API allowing users to opt-in to the future behaviour today, and starts
to emit a deprecation warning for users that use the default.

Relates #67158
Closes #66419

### CODE REVIEW

**Review by tlrx — DISMISSED** [review]

**Comment by DaveCTurner** [comment]
Sorry about all the iterations here @tlrx, `./gradlew check` fails for me for unrelated reasons so I've been trying to run all the relevant-looking things and am relying on CI to run everything else. I'm going to have to port some of these changes to `master` too. Bear with me.

**Comment by DaveCTurner** [comment]
Ok this is good for another look now, sorry again for all the extra noise.

**Review by tlrx — APPROVED** [review]
LGTM

**Comment by DaveCTurner** [comment]
:sob: in 11381c3f136d1f43fca6cf6484e3766a06424044 I have reverted this because it causes `master` BWC tests to fail thanks to the generation of warnings that `master` does not expect. I'll work on a PR to address that in `master`.

**Comment by DaveCTurner** [comment]
I have opened #67527 to undo the revert and reinstate this commit.

**Pull request merged**
