### PR TITLE
New field mapping flag - allow_multiple_values

### LINKED ISSUE #58523: Add 'singleton' flag to field mappers?
Datastreams have a first-class concept of a timestamp field. Each document in the datastream must contain exactly one value for the designated timestamp field, so that we know where to route the document when partitioning by time. In #58582 we're adding index-time validation for this requirement. The current implementation is very narrow in scope and adds special document parsing logic just for datastream timestamps.

I was wondering if this validation could be useful more generally. We could add a 'singleton' flag to field mappers -- when it is set, the mapper will verify that it encounters one (and only one) value in each document:

```
"product_identifier": {
  "type": "keyword",
  "singleton": true
}
```

Such an option could be helpful for modeling fields that an application requires to have exactly one value, like identifiers, timestamps, content types, etc.

### PR DESCRIPTION
**Pull request by markharwood**
When set to false documents that present arrays instead of single values are rejected at ingest time.
TODO - docs

Closes #58523

### CODE REVIEW

**Comment by weizijun** [comment]
@markharwood will the feature to be merged soon?

**Comment by markharwood** [comment]
>will the feature to be merged soon?

We're gathering interest in this change. While there are advantages to this feature there have been some reservations which are:
* this could be the start of a "slippery slope" to taking care of all validation e.g. supporting enums which is something we don't want to do.
* For use cases like observability, users would rather index and live with messy data than reject any documents

Can you say anything about your interest in this feature?

**Comment by weizijun** [comment]
> > will the feature to be merged soon?
> 
> We're gathering interest in this change. While there are advantages to this feature there have been some reservations which are:
> 
> * this could be the start of a "slippery slope" to taking care of all validation e.g. supporting enums which is something we don't want to do.
> * For use cases like observability, users would rather index and live with messy data than reject any documents
> 
> Can you say anything about your interest in this feature?

about this PR: https://github.com/elastic/elasticsearch/pull/80685, I also add a single value parameter, when your PR merged, I will change my logic. It can resolve `aggregate_metric_double` performance problem.

**Comment by javanna** [comment]
This PR was never completed, closing.

**Comment by ebuildy** [comment]
My 2 cents, we use elasticsearch as data store with Apache Spark as data engine (with Kafka / S3 parquet files).

This work like a charm, but we miss a real data integrity with elasticsearch, anyone can add a bad document with an array instead of a concrete string, the document will be accepted but will break all our data pipeline (also there is no way to find the bad document ....).

I think "validation" is a good thing, we can put data on elasticsearch with so many ways:

- bulk / index API
- spark jobs
- transformation
- snapshot restore
- update by query

It's always a good thing to have guarantee about what the data is.

As reference: https://discuss.elastic.co/t/mapping-how-to-disable-array-of-string/315782

**Pull request closed without merging**
