### PR TITLE
[ES|QL] Reduce memory usage of MvSliceTests on Spatial Data Types

### PR DESCRIPTION
**Pull request by fang-xing-esql**
Resolves :#107756

Reduce the memory usage of MvSliceTests by generating less data for testing on spatial data types.

### CODE REVIEW

**Comment by not-napoleon** [comment]
I'd like to understand why the production code is OOMing here, and if there's anything we can do to fix that, rather than working around it in the test.  @craigtaverner this seems to be related to the Spatial ES|QL, can you take a look and see if anything sparks an idea?

**Comment by nik9000** [comment]
Now that I think about it, this should throw a CircuitBreaker instead of OOM. Unless the test has done something that disables that somehow. Or maybe we set the limit too high?

**Comment by fang-xing-esql** [comment]
> I'd like to understand why the production code is OOMing here, and if there's anything we can do to fix that, rather than working around it in the test. @craigtaverner this seems to be related to the Spatial ES|QL, can you take a look and see if anything sparks an idea?

The issue seems to be that MvSliceTests created a lot of spatial objects, when Nik and I looked together, the size of the spatial objects in total is ~200M, that's the main memory consumer. So we put an upper limit on the total size of BytesRef generated by testEvaluateBlock. I also chatted with Craig about whether we can limit the size of a spatial object, it might be more complicated than putting an upper limit solution. I also reduced the number of spatial objects created by the tests, as we can live with a smaller scale here I think.

**Comment by craigtaverner** [comment]
I think that spatial data using a lot more memory than other data is an entirely expected behaviour. The data used in the tests is being generated by the same Lucene random generators that are used in many other spatial tests (those in Elasticsearch _search and aggs in particular). Having said that, @iverase has pointed out that the ES|QL stack uses more memory for all types than the _search stack, due to copying data into Blocks before usage. This means that memory hogs like `geo_shape` will be even more dramatic in ES|QL than in _search. If the point of these tests is to demonstrate that memory issue, then hiding it with tweaks to the tests would be a mistake. However, I do not believe that is the point of these tests. They test behaviour, not memory consumption. I think generating less data is a viable fix here. But at the same time we should have benchmarks for performance and memory usage that do care about large objects like `geo_shape`, and we should make a plan for how to deal with this, particularly in memory constrained environments.

**Comment by not-napoleon** [comment]
++ what Nik said.  I think this is a fine fix for the test, but I am concerned that we OOM'd instead of circuit breaking here.  That's what I'd like to understand better.  If we want to merge this to stop the test failing while we investigate the OOM, that's fine by me.

**Comment by fang-xing-esql** [comment]
> For folks playing along - we're pretty sure we're going to reduce the memory usage here. That's not the thing holding this up. The real question is "why didn't the test throw a circuit breaker?" Because _that_ feels like it might matter.

After taking a closer look at the BytesRefBlockBuilder and how it adjusts the CircuitBreaker, it looks questionable to me that BytesRefBlockBuilder "adjustBreaker" properly, or I didn't fully understand how it works yet. 

Unlike the other BlockBuiders, BytesRefBlockBuilder does not have a values array, its valuesLength() always return Integer.MAX_VALUE, and elementSize() is -1, this is understandable as BytesRefBlockBuilder takes various length string. However when new values are added into the BytesRefBlockBuilder, it may not adjust the circuit breaker properly.

There are a few places in AbstractBlockBuilder, that the used size of a circuit breaker is adjusted when a new value is added to a builder.

```
protected final void ensureCapacity() {
    int valuesLength = valuesLength();  ==> BytesRefBlockBuilder always return Integer.MAX_VALUE.
    if (valueCount < valuesLength) {   
        return;
    }
    int newSize = ArrayUtil.oversize(valueCount, elementSize());  ==> the following won't be executed in our case
    adjustBreaker(newSize * elementSize());
    growValuesArray(newSize);
    adjustBreaker(-valuesLength * elementSize());
}
```

```
private void setFirstValue(int position, int value) {
    if (position >= firstValueIndexes.length) {
        final int currentSize = firstValueIndexes.length;
        // We grow the `firstValueIndexes` at the same rate as the `values` array, but independently.
        final int newLength = ArrayUtil.oversize(position + 1, Integer.BYTES);
        adjustBreaker((long) newLength * Integer.BYTES);  ==> this is way smaller than the actual value size
        firstValueIndexes = ArrayUtil.growExact(firstValueIndexes, newLength);
        adjustBreaker(-(long) currentSize * Integer.BYTES);
    }
    firstValueIndexes[position] = value;
}
```
The call to adjustBreaker increase the breaker’s used size by newLength * Integer.BYTES, this is way smaller than the actual values copied into the BytesRefBlockBuilder.

I might be wrong, but these are the main reason that I found so far that BytesRefBlockBuilder doesn't adjust circuit breaker size properly.

**Comment by nik9000** [comment]
> I might be wrong, but these are the main reason that I found so far that BytesRefBlockBuilder doesn't adjust circuit breaker size properly.

`BytesRefBlockBuilder` is indeed pretty special here. It's backing the data in a `BytesRefArray` which bumps the breaker on it's own.

**Comment by fang-xing-esql** [comment]
> > I might be wrong, but these are the main reason that I found so far that BytesRefBlockBuilder doesn't adjust circuit breaker size properly.
> 
> `BytesRefBlockBuilder` is indeed pretty special here. It's backing the data in a `BytesRefArray` which bumps the breaker on it's own.

Thanks for the hint Nik! The MockBigArrays created by AbstractFunctionTestCases do not have a circuit breaker set properly. I'll keep this PR to reduce the test data size only, and address the MockBigArrays in a different PR.

**Comment by fang-xing-esql** [comment]
Close this as #108195 resolved the #107756

**Pull request closed without merging**
