### PR TITLE
Remove a couple of awaitsfix in EsqlActionIT

### PR DESCRIPTION
**Pull request by ChrisHegarty**
This commit removes a couple of awaits fixes in EsqlActionIT that are no longer needed - previous changes have resolved the underlying issue and the test scenarios now run successfully consistently.

### CODE REVIEW

**Comment by ChrisHegarty** [comment]
Note: currently the complete EsqlActionIT test is marked awaits fix, but the test will be reenabled soon by #100370.

**Comment by ChrisHegarty** [comment]
Argh! :-( 

loopy testing has now hit this:
```
REPRODUCE WITH: ./gradlew 'null' --tests "org.elasticsearch.xpack.esql.action.EsqlActionIT.testFromLimit [seed=[362F331FBB1FF941:1155810CE0590A89]]" -Dtests.seed=362F331FBB1FF941 -Dtests.locale=sk-SK -Dtests.timezone=Europe/Mariehamn -Druntime.java=19

java.lang.AssertionError: Request breaker not reset to 0 on node: node_s0
Expected: <0L>
     but: was <64L>
Expected :<0L>
Actual   :<64L>
at __randomizedtesting.SeedInfo.seed([362F331FBB1FF941:1155810CE0590A89]:0)
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
at org.junit.Assert.assertThat(Assert.java:956)
at org.elasticsearch.test.InternalTestCluster.lambda$ensureEstimatedStats$41(InternalTestCluster.java:2439)
at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1196)
at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:1169)
at org.elasticsearch.test.InternalTestCluster.ensureEstimatedStats(InternalTestCluster.java:2437)
at org.elasticsearch.test.TestCluster.assertAfterTest(TestCluster.java:92)
at org.elasticsearch.test.InternalTestCluster.assertAfterTest(InternalTestCluster.java:2486)
at org.elasticsearch.test.ESIntegTestCase.afterInternal(ESIntegTestCase.java:590)
....
```

**Review by bpintea — APPROVED** [review]
lgtm

**Comment by dnhatn** [comment]
> REPRODUCE WITH: ./gradlew 'null' --tests "org.elasticsearch.xpack.esql.action.EsqlActionIT.testFromLimit [seed=[362F331FBB1FF941:1155810CE0590A89]]" -Dtests.seed=362F331FBB1FF941 -Dtests.locale=sk-SK -Dtests.timezone=Europe/Mariehamn -Druntime.java=19

I have a theory and I will look into this.

**Pull request closed without merging**
