### PR TITLE
Update Elasticsearch to lucene-9.3.0

### PR DESCRIPTION
**Pull request by iverase**
Lucene 9.3.0 just been released.

### CODE REVIEW

**Comment by iverase** [comment]
@elasticsearchmachine run elasticsearch-ci/example-plugins

**Review by mayya-sharipova — APPROVED** [review]
@iverase Thanks, LGTM!

**Comment by iverase** [comment]
@elasticmachine run elasticsearch-ci/example-plugins

**Comment by iverase** [comment]
@elasticmachine run elasticsearch-ci/example-plugins

**Pull request merged**
