### PR TITLE
Can load non-PreBuiltTokenFilter in Analyze API

### PR DESCRIPTION
**Pull request by johtani**
Fix the error when using default min_hash in analyze API

### CODE REVIEW

**Comment by johtani** [comment]
retest this please

**Comment by johtani** [comment]
retest this please

**Comment by nik9000** [comment]
LGTM

**Comment by nik9000** [comment]
I took an educated guess as to which versions this effects. Can you verify and cherry pick after merging?

**Comment by johtani** [comment]
@nik9000 Thanks! Sure I will cherry pick after merging after CI success...

**Comment by johtani** [comment]
For 5.0 : https://github.com/elastic/elasticsearch/commit/a342821e0774ce11ba18f17c568a3c1179a2b9c9

**Comment by johtani** [comment]
For 5.x : 405cfe6ed0eebe4004a6eb6f0a6d7111a98c733a

**Pull request merged**
