### PR TITLE
Bump version to 5.1.3

### PR DESCRIPTION
**Pull request by dakrone**
Bumps version and adds the BWC indices

### CODE REVIEW

**Comment by jasontedor** [comment]
Can you bump the docs versions too:

```bash
13:21:37 1d [jason:~/src/elastic/elasticsearch-5.x/docs] 5.1 ± ack "version.*5.1.2"
groovy-api/index.asciidoc
4::version: 5.1.2

java-api/index.asciidoc
4::version: 5.1.2

java-rest/index.asciidoc
4::version: 5.1.2

plugins/index.asciidoc
5::version:        5.1.2

reference/index.asciidoc
4::version:        5.1.2
```

**Comment by jasontedor** [comment]
Also, I think the label should be v5.1.3.

**Comment by dakrone** [comment]
I bumped the documentation as well, thanks @jasontedor

**Review by jasontedor — APPROVED** [review]
LGTM.

**Pull request merged**
