### PR TITLE
Fixing some missing slash

### PR DESCRIPTION
**Pull request by InferGuard**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by nik9000** [comment]
I don't believe these slashes are required in Kibana's CONSOLE and we don't fail the build without them and I *think* the `COPY AS CURL` links should work with or without the slashes. So I'm not sure this is worth doing.

Fun fact: originally, when I was implementing the automatic testing of CONSOLE snippets the `/`s weren't allowed. @clintongormley preferred having them so I made it possible to keep them in. Since then I've come around to his way of thinking. I'd be happy to require the `/` as part of the Elasticsearch build if @clintongormley thinks that is worth doing. If so we can merge this as a start of the migration to adding the `/`s.

Also, you'd need to sign the CLA for us to merge this. We require it for all changes no matter where they are in the repository, no matter how big or how small.

**Comment by clintongormley** [comment]
>  I'd be happy to require the / as part of the Elasticsearch build if @clintongormley thinks that is worth doing.

I'm not sure it is worth enforcing, especially as they're not required by Console. For me, either form is acceptable

**Comment by nik9000** [comment]
It'd only be worth enforcing from a documentation consistency standpoint.

**Comment by LinuxArchitects** [comment]
It's up to you guys but the things is,  sometimes you can see :
`POST _tasks/task_id:1/_cancel`
 and sometimes you can see this as well:
`GET /_tasks/taskId:1`
in the same doc

**Comment by dakrone** [comment]
I think since we have a mix across the codebase it's not worth having one unless we standardize everywhere. With that in mind I'm going to close this PR, but please do comment if you disagree!

**Pull request closed without merging**
