### PR TITLE
Allow Unknown Fields on RepositoryData

### PR DESCRIPTION
**Pull request by original-brownbear**
* Allow unknown fields on `RepositoryData` for future compatibility when we might want to add more fields to the `index-N` blobs

### CODE REVIEW

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/2 (some Jenkins failure)

**Comment by original-brownbear** [comment]
@ywelsch @andrershov as discussed elsewhere, this would add the version to `RepositoryData`. Annoyingly enough, it's not so easy (as in it takes some code, not that it's conceptually hard) to make `BlobStoreRepository` know whether or not it's in a mixed cluster with nodes not able to handle the version field in the repository data (no transport or cluster service in that class, so we have to change the interface).
Maybe we could do a trivial upgrade path here (since we don't urgently need that version information in `repositoryData` anyway ... just add it in `8.0` and harden `7.3/7.x` to ignore unknown fields when deserializing `RepositoryData` => happy?

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/1

**Comment by ywelsch** [comment]
There's no immediate need for this, but let's make the parsing for RepositoryData more lenient for now (so that we can later on add fields when needed)

**Comment by original-brownbear** [comment]
@ywelsch sounds good, make it lenient in `7.x` as well?

**Comment by ywelsch** [comment]
yes

**Comment by original-brownbear** [comment]
@ywelsch alright reverted everything but the lenient parsing and adjusted PR description :)

**Review by tlrx — COMMENTED** [review]
I think that this change deserves a randomized test

**Comment by original-brownbear** [comment]
@tlrx @ywelsch On second thought: I wonder how wise this change is in isolation.
Assuming we would be using this to add some important (meta-)data to the repository in the future, then unless further precautions are taken the following unfortunate sequence of events could easily happen:
1. Create snapshots in a future version that require some field "X" in RepositoryData
2. Accidentally add repo to 8.0 cluster and delete a snapshot (the new RepositoryData written will then lose the contents of "X")
3. From the perspective of future version 9.0 (or whatever), the missing "X" has caused the repo to be corrupted

... maybe it's smarter to go through the pain of refactoring things enough so that in a mixed cluster situation the lowest version of `RepositoryData` is serialized (so that in a mixed master situation no unreadable RepositoryData is written until all master's are upgraded) and we keep this as a safe-guard against corrupting the repository?

**Comment by ywelsch** [comment]
ok, I'm fine with closing this one. In theory we can reintroduce this change in 7.latest if need be.

**Pull request closed without merging**
