### PR TITLE
Add test for dense transport versions

### PR DESCRIPTION
**Pull request by rjernst**
Now that 8.x is branched from main, all transport version changes must be backported until 9.0 is ready to diverge. This commit adds a test which ensures transport versions are densely packed, ie there are no gaps at the granularity the version id is bumped (multiples of 1000).

### CODE REVIEW

**Review by ldematte — APPROVED** [review]
👍

**Comment by thecoop** [comment]
Does this also need to be backported to 8.16?

**Comment by bitomukesh** [comment]
<div>
<h2>Changelist by Bito</h2>
    <p>This pull request implements the following key changes.</p>

<div>
<table width="100%">
<tbody>
  <tr>
    <th>Key Change</th>
    <th>Files Impacted</th>
  </tr>

<tr>
<td width="30%">
    <b>Testing</b> - New Test for Dense Transport Versions
</td>
<td width="70%">


<div>

-&nbsp;[`TransportVersionTests.java`](https://github.com/elastic/elasticsearch/pull/113213/files#diff-f92d12ddc9833ee160c53dfc6693451345c9d0c1c4343cb57682601a39f24cec) - Added a new test method to ensure transport versions are densely packed
</div>
</td>
</tr>

</tbody>
</table>
</div>
</div>

**Comment by rjernst** [comment]
> Does this also need to be backported to 8.16?

Yes.

**Pull request merged**
