### PR TITLE
Add a data stream timestamp parsing benchmark

### PR DESCRIPTION
**Pull request by weizijun**
I add a benchmark to test the timestamp parsing. Here is the result:
```
Benchmark                        (fieldCount)  (type)  Mode  Cnt      Score   Error  Units
FilterTimestampBenchmark.filter           100   first  avgt    2    287.594          ns/op
FilterTimestampBenchmark.filter           100  middle  avgt    2   3916.184          ns/op
FilterTimestampBenchmark.filter           100    last  avgt    2   6252.155          ns/op
FilterTimestampBenchmark.filter           500   first  avgt    2    358.984          ns/op
FilterTimestampBenchmark.filter           500  middle  avgt    2  18263.286          ns/op
FilterTimestampBenchmark.filter           500    last  avgt    2  35881.173          ns/op
FilterTimestampBenchmark.filter          1000   first  avgt    2    381.409          ns/op
FilterTimestampBenchmark.filter          1000  middle  avgt    2  33776.770          ns/op
FilterTimestampBenchmark.filter          1000    last  avgt    2  76794.686          ns/op
```
The results show that the earlier the timestamp field is located, the lower the parsing cost. If the timestamp is the first field, the cost is very small.

And I add a timesamp fieldType in FilterContentBenchmark ,here is a result:
```
Benchmark                                                                  (fieldType)  (inclusive)         (type)  Mode  Cnt       Score   Error  Units
FilterContentBenchmark.filterWithBuilder                                     timestamp         true  cluster_stats  avgt    2  106958.390          ns/op
FilterContentBenchmark.filterWithMap                                         timestamp         true  cluster_stats  avgt    2  135732.682          ns/op
FilterContentBenchmark.filterWithNewParserConfig                             timestamp         true  cluster_stats  avgt    2   87477.616          ns/op
FilterContentBenchmark.filterWithParserConfigCreated                         timestamp         true  cluster_stats  avgt    2   81663.135          ns/op
FilterContentBenchmark.filterWithParserConfigCreatedMatchDotsInFieldNames    timestamp         true  cluster_stats  avgt    2   83431.003          ns/op
```

The `FilterContentBenchmark.filterWithParserConfigCreated` result is the current code that `TS_EXTRACT_CONFIG` use. It's the best performance.

### CODE REVIEW

**Comment by weizijun** [comment]
@elasticmachine update branch

**Comment by weizijun** [comment]
> @weizijun what is the purpose of adding this micro benchmark? The newly added benchmark isn't benchmarking something tsdb specific. Just xcontent parsing with tsdb inspired test data. It isn't like `FilterContentBenchmark` which micro benchmarks a specific feature of xcontent, namely filtered parsing.

`FilterTimestampBenchmark` is used to benchmark the cost of data stream @timestamp field parse. The results show that the earlier the timestamp field is located, the lower the parsing cost. If the timestamp is the first field, the cost is very small.

**Comment by martijnvg** [comment]
> FilterTimestampBenchmark is used to benchmark the cost of data stream @timestamp field parse. The results show that the earlier the timestamp field is located, the lower the parsing cost. If the timestamp is the first field, the cost is very small.

I see, but that is true for any field, right? Any field that is located in the beginning has a lower parsing cost, so this isn't anything specific to tsdb data streams.

**Comment by weizijun** [comment]
> I see, but that is true for any field, right? Any field that is located in the beginning has a lower parsing cost, so this isn't anything specific to tsdb data streams.

yeah, because the tsdb data streams will use the parse to get timestamp field, and to choice the write index. This increases the cost of writing. If the timestamp is the first field, the cost is lower, but if the timestamp is the last field, the cost is higher.

**Comment by martijnvg** [comment]
> yeah, because the tsdb data streams will use the parse to get timestamp field, and to choice the write index. This increases the cost of writing. If the timestamp is the first field, the cost is lower, but if the timestamp is the last field, the cost is higher.

For each bulk item in bulk request, we now will parse the source in order to get the timestamp. I agree, that this has an overhead, especially if the entire source needs to be parsed, because `@timestamp` happens to be the last field.

This benchmarks emulates how `@timestamp` field gets parsed with custom code, which is based on the code in `IndexAbstraction.java`. It isn't benchmarking production code. This benchmarks just shows that performance of extracting a field value is dependant of the location where the target field is located. I don't think we need to have a benchmark for that?

**Comment by weizijun** [comment]
> This benchmarks emulates how `@timestamp` field gets parsed with custom code, which is based on the code in `IndexAbstraction.java`. It isn't benchmarking production code. This benchmarks just shows that performance of extracting a field value is dependant of the location where the target field is located. I don't think we need to have a benchmark for that?

This benchmark is to benchmark the additional cost of data stream in tsdb mode. And it will also need a rally test case.

**Pull request closed without merging**
