### PR TITLE
run bwc test also as integ test and share methods

### PR DESCRIPTION
**Pull request by brwe**
We had no itegration test before with long terms and several shards only
a bwc test.

related to #14948

### CODE REVIEW

**Comment by brwe** [comment]
@nik9000 would you like to take a look?

**Comment by nik9000** [comment]
Looks great! Every time I do this I have to tweak the pom to make sure the shared test method are included. Do you have to do that too? It typically comes up when I do a clean compile.

**Comment by brwe** [comment]
I placed them in org/elasticsearch/test which is packaged (thanks @s1monw for the tip). I can put it somewhere else though and tweak the pom instead. Would that be better?

**Comment by nik9000** [comment]
> I placed them in org/elasticsearch/test which is packaged

Ah. Whatever works is fine with me!

**Comment by nik9000** [comment]
So LGTM.

**Pull request merged**
