### PR TITLE
Remove Lifecycle#stop()

### PR DESCRIPTION
**Pull request by s1monw**
We don't allow stopping services anyway so all this code is confusing and
just wrong. We eventually once we remove guice can simplify this even further
towards a simple closeable but for now all the stop code can just go into close()

### CODE REVIEW

**Comment by martijnvg** [comment]
LGTM, nice stats and I'm looking forward to simply using closable!

**Comment by s1monw** [comment]
I get some test failure crazyness related to discovery here. there is too much magic in here I don't really get. I don't think I will have the patience to fix that but maybe somebody with more disco knowledge can chime in @bleskes @martijnvg

**Comment by bleskes** [comment]
Would love to. Can you give an example of the failures?

**Comment by s1monw** [comment]
`DiscoveryWithServiceDisruptionsIT.testVerifyApiBlocksDuringPartition` for example

**Comment by martijnvg** [comment]
@s1monw @bleskes the discovery tests failures are caused by the fact the in places we used to call stop() on MasterFaultDetection and NodesFaultDetection we now call close() which does more than just stop() did before.

I added back the stop() methods in MasterFaultDetection and NodesFaultDetection and updated ZenDiscovery to use them when we rejoin or detected that we lost the master, then the discovery tests pass. Maybe we can maybe rename the stop() method to interrupt() or pause() or something like that.

**Comment by s1monw** [comment]
> I added back the stop() methods in MasterFaultDetection and NodesFaultDetection and updated ZenDiscovery to use them when we rejoin or detected that we lost the master, then the discovery tests pass. Maybe we can maybe rename the stop() method to interrupt() or pause() or something like that.

I am ok with adding it back on both of these classes as long as the interface is clean. Can you share your code?

**Comment by bleskes** [comment]
+1 on leaving them in the classes. We do use the "stop/start" semantics here. I think it's OK (the FaultDetection class doesn't even inherit from LifecycleComponent ).

**Comment by martijnvg** [comment]
Sure, the changes:

```patch
Index: core/src/main/java/org/elasticsearch/discovery/zen/fd/MasterFaultDetection.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- core/src/main/java/org/elasticsearch/discovery/zen/fd/MasterFaultDetection.java	(date 1448630180000)
+++ core/src/main/java/org/elasticsearch/discovery/zen/fd/MasterFaultDetection.java	(revision )
@@ -129,7 +129,7 @@
         threadPool.schedule(pingInterval, ThreadPool.Names.SAME, masterPinger);
     }
 
-    private void stop(String reason) {
+    public void stop(String reason) {
         synchronized (masterNodeMutex) {
             if (masterNode != null) {
                 if (logger.isDebugEnabled()) {
Index: core/src/main/java/org/elasticsearch/discovery/zen/fd/NodesFaultDetection.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- core/src/main/java/org/elasticsearch/discovery/zen/fd/NodesFaultDetection.java	(date 1448630180000)
+++ core/src/main/java/org/elasticsearch/discovery/zen/fd/NodesFaultDetection.java	(revision )
@@ -106,10 +106,14 @@
         }
     }
 
+    public void stop() {
+        nodesFD.clear();
+    }
+
     @Override
     public void close() {
         super.close();
-        nodesFD.clear();
+        stop();
     }
 
     @Override
Index: core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java	(date 1448630180000)
+++ core/src/main/java/org/elasticsearch/discovery/zen/ZenDiscovery.java	(revision )
@@ -662,7 +662,7 @@
                     return newState;
 
                 } else {
-                    nodesFD.close();
+                    nodesFD.stop();
                     if (electedMaster != null) {
                         discoveryNodes = DiscoveryNodes.builder(discoveryNodes).masterNodeId(electedMaster.id()).build();
                         masterFD.restart(electedMaster, "possible elected master since master left (reason = " + reason + ")");
@@ -951,8 +951,8 @@
         assert Thread.currentThread().getName().contains(InternalClusterService.UPDATE_THREAD_NAME);
 
         logger.warn(reason + ", current nodes: {}", clusterState.nodes());
-        nodesFD.close();
-        masterFD.close(reason);
+        nodesFD.stop();
+        masterFD.stop(reason);
 
 
         ClusterBlocks clusterBlocks = ClusterBlocks.builder().blocks(clusterState.blocks())

```

**Comment by clintongormley** [comment]
@s1monw still want to get this in?

**Comment by dakrone** [comment]
@s1monw is this still useful? Re-ping as the code freeze for 5.0 is approaching soon :)

**Comment by s1monw** [comment]
closing

**Pull request closed without merging**
