### PR TITLE
FiltersAggregationBuilder: rewriting filter queries, the same way as in FilterAggregationBuilder

### PR DESCRIPTION
**Pull request by artnowo**
We use wrapper queries for user-supplied filters aggregations. In 5 `WrapperQueryBuilder` forces query to be rewritten, but it doesn't happen in `FiltersAggregationBuilder`. However, since 5.1 it was implemented in `FilterAggregationBuilder` and this pull request does basically the same, but for a list of filters instead of a single filter.

Example:
For these three documents:
```
curl -XPUT localhost:9200/test/test/1?pretty -d '{"title":"foo bar baz"}'
curl -XPUT localhost:9200/test/test/2?pretty -d '{"title":"foo foo foo"}'
curl -XPUT localhost:9200/test/test/3?pretty -d '{"title":"bar baz bax"}'
```

You'll get a proper response for this request:
```
curl -XGET localhost:9200/test/test/_search?pretty -d '{
  "size":0,
  "aggs": {
    "titles": {
      "filters": {
        "filters" : {
          "titleterms" : {
            "terms" : {
              "title": ["foo"]
            }
          }
        }
      }
    }
  }
}'
```

But for this one, equivalent, but making use of the wrapper query you'll get unsupported operation exception:
```
curl -XGET localhost:9200/test/test/_search?pretty -d '{
  "size":0,
  "aggs": {
    "titles": {
      "filters": {
        "filters" : {
          "titleterms" : {
            "wrapper" : {
              "query": "InRlcm1zIiA6IHsgInRpdGxlIjogWyJmb28iXSB9"
            }
          }
        }
      }
    }
  }
}'
```

Response:
```
{
  "error" : {
  "root_cause" : [
    {
    "type" : "unsupported_operation_exception",
    "reason" : "this query must be rewritten first"
    }
  ],
  "type" : "search_phase_execution_exception",
  "reason" : "all shards failed",
  "phase" : "query",
  "grouped" : true,
  "failed_shards" : [
    {
    "shard" : 0,
    "index" : "test",
    "node" : "TazxVGAYRki28XXNUgmdAg",
    "reason" : {
      "type" : "unsupported_operation_exception",
      "reason" : "this query must be rewritten first"
    }
    }
  ],
  "caused_by" : {
    "type" : "unsupported_operation_exception",
    "reason" : "this query must be rewritten first"
  }
  },
  "status" : 500
}
```

Stacktrace:
```
Caused by: java.lang.UnsupportedOperationException: this query must be rewritten first
	at org.elasticsearch.index.query.WrapperQueryBuilder.doToQuery(WrapperQueryBuilder.java:149) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:97) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.index.query.AbstractQueryBuilder.toFilter(AbstractQueryBuilder.java:119) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.search.aggregations.bucket.filters.FiltersAggregatorFactory.<init>(FiltersAggregatorFactory.java:58) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.search.aggregations.bucket.filters.FiltersAggregationBuilder.doBuild(FiltersAggregationBuilder.java:176) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.search.aggregations.AbstractAggregationBuilder.build(AbstractAggregationBuilder.java:126) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.search.aggregations.AggregatorFactories$Builder.build(AggregatorFactories.java:211) ~[elasticsearch-5.1.1.jar:5.1.1]
(...)
```

### CODE REVIEW

**Comment by karmi** [comment]
Hi @artnowo, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/elasticsearch/pull/22076.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by artnowo** [comment]
Hi,

I used this e-mail in commit by mistake, I'm committing definitely as the
e-mail used in the CLA. Can we do it another way around - I'll overwrite
commit in my forked repo with a correct e-mail and then we use the new
commit in the PR? Or should I close the PR and create a new one?

Regards,
Artur

2016-12-09 14:57 GMT+01:00 Karel Minarik <notifications@github.com>:

**Comment by artnowo** [comment]
This is related to my question here: https://github.com/elastic/elasticsearch/pull/21303#issuecomment-265991883

**Comment by karmi** [comment]
@artnowo, all checks are good now, I guess you've force pushed a commit with the address used for the CLA signature, which is the best solution, thanks!

**Comment by artnowo** [comment]
@karmi Exactly. :)

**Comment by s1monw** [comment]
@artnowo can you add a test that triggers the problem? just like here https://github.com/elastic/elasticsearch/pull/21303/files#diff-714e0cdea931e7f28eb9102b36a657c9

the fix looks good I think be we need a test to ensure that this is covered. If you add a rest test you can run them  using `gradle :distribution:integ-test-zip check` but make sure you run `gradle clean` before you add the test

**Comment by artnowo** [comment]
@s1monw I added a test (see the second commit), but have some problem with running. I run with `gradle :distribution:integ-test-zip:integTest check` and the result is as follows:

```
1> [2016-12-10T22:19:01,935][INFO ][o.e.t.r.IntegTestZipClientYamlTestSuiteIT] [test {p0=search.aggregation/60_filters/Filters aggs with wrapper query}]: before test
1> [2016-12-10T22:19:02,086][INFO ][o.e.t.r.IntegTestZipClientYamlTestSuiteIT] [test {p0=search.aggregation/60_filters/Filters aggs with wrapper query}]: after test
1> [2016-12-10T22:19:02,088][INFO ][o.e.t.r.IntegTestZipClientYamlTestSuiteIT] Stash dump on failure [{
1>   "stash" : {
1>     "body" : {
1>       "error" : {
1>         "root_cause" : [
1>           {
1>             "type" : "parse_exception",
1>             "reason" : "Failed to derive xcontent"
1>           }
1>         ],
1>         "type" : "search_phase_execution_exception",
1>         "reason" : "all shards failed",
1>         "phase" : "query_fetch",
1>         "grouped" : true,
1>         "failed_shards" : [
1>           {
1>             "shard" : 0,
1>             "index" : "test",
1>             "node" : "849ajQ2oSliHAjkVK-DfQg",
1>             "reason" : {
1>               "type" : "parse_exception",
1>               "reason" : "Failed to derive xcontent"
1>             }
1>           }
1>         ],
1>         "caused_by" : {
1>           "type" : "parse_exception",
1>           "reason" : "Failed to derive xcontent"
1>         }
1>       },
1>       "status" : 400
1>     }
1>   }
1> }]
2> REPRODUCE WITH: gradle :distribution:integ-test-zip:integTest -Dtests.seed=D9F0614351EE8F3B -Dtests.class=org.elasticsearch.test.rest.IntegTestZipClientYamlTestSuiteIT -Dtests.method="test {p0=search.aggregation/60_filters/Filters aggs with wrapper query}" -Dtests.security.manager=true -Dtests.locale=ar-MA -Dtests.timezone=MET
FAILURE 0.16s | IntegTestZipClientYamlTestSuiteIT.test {p0=search.aggregation/60_filters/Filters aggs with wrapper query} <<< FAILURES!
 > Throwable #1: java.lang.AssertionError: Failure at [search.aggregation/60_filters:45]: expected [2xx] status code but api [search] returned [400 Bad Request] [{"error":{"root_cause":[{"type":"parse_exception","reason":"Failed to derive xcontent"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query_fetch","grouped":true,"failed_shards":[{"shard":0,"index":"test","node":"849ajQ2oSliHAjkVK-DfQg","reason":{"type":"parse_exception","reason":"Failed to derive xcontent"}}],"caused_by":{"type":"parse_exception","reason":"Failed to derive xcontent"}},"status":400}]
 > 	at __randomizedtesting.SeedInfo.seed([D9F0614351EE8F3B:51A45E99FF12E2C3]:0)
 > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:374)
 > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.test(ESClientYamlSuiteTestCase.java:354)
 > 	at java.lang.Thread.run(Thread.java:745)
 > Caused by: java.lang.AssertionError: expected [2xx] status code but api [search] returned [400 Bad Request] [{"error":{"root_cause":[{"type":"parse_exception","reason":"Failed to derive xcontent"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query_fetch","grouped":true,"failed_shards":[{"shard":0,"index":"test","node":"849ajQ2oSliHAjkVK-DfQg","reason":{"type":"parse_exception","reason":"Failed to derive xcontent"}}],"caused_by":{"type":"parse_exception","reason":"Failed to derive xcontent"}},"status":400}]
 > 	at org.elasticsearch.test.rest.yaml.section.DoSection.execute(DoSection.java:145)
 > 	at org.elasticsearch.test.rest.yaml.ESClientYamlSuiteTestCase.executeSection(ESClientYamlSuiteTestCase.java:370)
 > 	... 37 more
```

I tried both JSON (as committed) and YAML syntax:
```
search:
  body:
      size: 0
      aggs:
          titles:
              filters:
                  filters:
                      titleterms:
                          wrapper:
                              query: InRlcm1zIiA6IHsgInRpdGxlIjogWyJmb28iXSB9
```
but the result is the same.

**Comment by s1monw** [comment]
I think you are passing a malformed query ie. 

 * `InRlcm1zIiA6IHsgInRpdGxlIjogWyJmb28iXSB9` -> `"terms" : { "title": ["foo"] }`

but you want:
 * `eyJ0ZXJtcyIgOiB7ICJ0aXRsZSI6IFsiZm9vIl0gfX0=` -> `{"terms" : { "title": ["foo"] }}`

then your test should work...

```diff
diff --git a/rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/60_filters.yaml b/rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/60_filters.yaml
index 4a83fd7..3d26569 100644
--- a/rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/60_filters.yaml
+++ b/rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/60_filters.yaml
@@ -44,7 +44,7 @@ setup:
 
   - do:
       search:
-        body: {"size": 0, "aggs": {"titles": {"filters": {"filters" : {"titleterms" : {"wrapper" : {"query": "InRlcm1zIiA6IHsgInRpdGxlIjogWyJmb28iXSB9"}}}}}}}
+        body: {"size": 0, "aggs": {"titles": {"filters": {"filters" : {"titleterms" : {"wrapper" : {"query": "eyJ0ZXJtcyIgOiB7ICJ0aXRsZSI6IFsiZm9vIl0gfX0="}}}}}}}
 
   # validate result
   - match: { hits.total: 3 }
```

this does it for me

**Comment by artnowo** [comment]
Right, your version works for me as well - thank you! Interesting that both encoded queries work when issued with curl, but only the second one is accepted in tests.

**Comment by s1monw** [comment]
@elasticmachine test this please

**Comment by s1monw** [comment]
@elasticmachine test this please

**Comment by s1monw** [comment]
@artnowo thanks so much for this fix, I will backport it to the relevant branches

**Comment by artnowo** [comment]
Great, thanks @s1monw!

**Comment by javanna** [comment]
Hi @artnowo quick question. You are using wrapper query builder through the java api right? Just double checking that using wrapper through the REST layer makes very little sense. Thanks!

**Comment by artnowo** [comment]
Hi, of course we use it via the Java API. I used JSON in PR description only because it was easier to present and reproduce the problem.

**Comment by javanna** [comment]
makes sense, thanks for the feedback @artnowo

**Pull request merged**
