### PR TITLE
First set of dependencies for OpentTelemetry

### PR DESCRIPTION
**Pull request by tlrx**

### CODE REVIEW

**Review by dimitris-athanasiou — APPROVED** [review]
LGTM

**Review by DaveCTurner — APPROVED** [review]
LGTM

**Comment by cyrille-leclerc** [comment]
FYI to control the version of the Otel artifacts, there are 2 OpenTelemetry BOMs:
```
implementation 'io.opentelemetry:opentelemetry-bom:1.9.0'
implementation 'io.opentelemetry:opentelemetry-bom-alpha:1.9.0-alpha'
```

**Comment by cyrille-leclerc** [comment]
FYI:
* https://github.com/jenkinsci/opentelemetry-plugin/blob/opentelemetry-0.22-beta-3/pom.xml#L40-L53
* https://github.com/open-telemetry/opentelemetry-java-contrib/blob/294aade72ffd7bb17330f1213621130ea69cef92/dependencyManagement/build.gradle.kts#L21

**Pull request merged**
