### PR TITLE
Test histogram with zero-count buckets and synthetic source

### PR DESCRIPTION
**Pull request by salvatore-campagna**
Indexing a histogram in an index with synthetic source enabled
results in missing buckets when fetching back the document if
the histogram includes zero-count buckets.
This happens because we do not store zero counts and the bucket
value into the histogram doc values, in such a way to save space.

### CODE REVIEW

**Comment by salvatore-campagna** [comment]
@martijnvg any chance to have a look at this?

**Review by martijnvg — APPROVED** [review]
LGTM

**Comment by salvatore-campagna** [comment]
@elasticsearchmachine test this please

**Comment by salvatore-campagna** [comment]
@elasticsearchmachine test this please

**Pull request merged**
