### PR TITLE
Update release notes to BC9

### PR DESCRIPTION
**Pull request by craigtaverner**
Just reverting the upgrade of bundled JDK to 20.

### CODE REVIEW

**Review by abdonpijpelink — APPROVED** [review]
LGTM

**Comment by craigtaverner** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by craigtaverner** [comment]
@elasticmachine please test this

**Comment by craigtaverner** [comment]
@elasticmachine run elasticsearch-ci/docs

**Pull request merged**
