### PR TITLE
Only allow one type on 6.0 indices

### PR DESCRIPTION
**Pull request by jpountz**
This adds the `index.mapping.single_type` setting, which enforces that indices
have at most one type when it is true. The default value is true for 6.0+ indices
and false for old indices.

Most of the change is about fixing tests that created multiple types to either
create a single `_type` instead or set `index.mapping.single_type` to `false`
(eg. for parent/child tests, which still require multiple types).

Relates #15613

### CODE REVIEW

**Comment by jpountz** [comment]
Note to reviewers: the PR is a bit large but you can focus on changes in `MapperService.java`, `TypeFieldMapper.java`, `MapperServiceTests.java` and `TypeFieldMapperTests.java`. Other changes are just about fixing tests so that they pass.

**Comment by jpountz** [comment]
@martijnvg @jimczi Maybe you could have a look since it is a bit related to #20257. What I have been doing for now with parent/child tests was just to enable the `_type` field in the tests.

**Comment by rjernst** [comment]
I think maybe having this on `_type` will be confusing for users, and that it would be cleaner (both for users, and code wise) for this to be an index setting. Having it be enabled/disabled on the `_type` field has a sense that one could have it set differently for different document types, but in fact the entire point is it must be set to true on all of them, or false on the one type.

**Comment by clintongormley** [comment]
@rjernst good point - i'm happy to go with an index setting

**Comment by jpountz** [comment]
I'll go with `index.mapper.single_type` if that works for everyone.

**Comment by jpountz** [comment]
Done. I actually went with `index.mapping.single_type` since we only had one setting prefixed by `index.mapper` while the other ones are prefixed by `index.mapping`.

**Review by jimczi — APPROVED** [review]
LGTM

**Comment by jpountz** [comment]
I will merge this PR with a default value of `false` for now to give people who directly test against master a grace period they can use to set `index.mapping.single_type` on indices that still use multiple types.

**Comment by jpountz** [comment]
Removing the `breaking` label since the actual break comes in #24428.

**Comment by kukuxiahuni** [comment]
I have a question。 now my index and type used like this, bussiness_index/2017-11-12,bussiness_index/2017-11-13. just one index and more type.the type was every date string, and each type store the data of that day. when only one type in a index, how can i change my index structure??

**Comment by jpountz** [comment]
You cannot change the index structure in a single type. This kind of problem is typically solved by having time-based indices rather than types.

Note: please use discuss.elastic.co to ask questions rather than Github.

**Pull request merged**
