### PR TITLE
Log more information in debug when synonyms fail updates

### PR DESCRIPTION
**Pull request by benwtrent**
Related to: https://github.com/elastic/elasticsearch/issues/102261

In test failures, we are not receiving any information around the bulk indexing cause stacktrace, just the message. 

This adds debug logging and grabs the first stacktrace over all indices. Additionally, the logger groups by the failure message in an effort to find unique failures over all the indices.

### CODE REVIEW

**Review by kderusso — APPROVED** [review]

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Review by carlosdelest — APPROVED** [review]

**Comment by carlosdelest** [comment]
@elasticmachine update branch

**Comment by carlosdelest** [comment]
@elasticmachine run elasticsearch-ci/part-1

**Comment by benwtrent** [comment]
@elasticmachine run elasticsearch-ci/part-2
@elasticmachine run elasticsearch-ci/part-4
@elasticmachine run elasticsearch-ci/bwc-snapshots
@elasticmachine run elasticsearch-ci/packaging-tests-windows-sample

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Pull request merged**
