### PR TITLE
Make hits.total an object in the search response

### PR DESCRIPTION
**Pull request by jimczi**
This commit changes the format of the `hits.total` in the search response to be an object with
a `value` and a `relation`. The `value` indicates the number of hits that match the query and the
`relation` indicates whether the number is accurate (in which case the relation is equals to `eq`)
or a lower bound of the total (in which case it is equals to `gte`).
This change also adds a parameter called `rest_total_hits_as_int` that can be used in the
search APIs to opt out from this change (retrieve the total hits as a number in the rest response).
Note that currently all search responses are accurate (`track_total_hits: true`) or they don't contain
`hits.total` (`track_total_hits: true`). We'll add a way to get a lower bound of the total hits in a
follow up (to allow numbers to be passed to `track_total_hits`).

Relates #33028

### CODE REVIEW

**Comment by jimczi** [comment]
Note that this pr depends on #35848 to pass the BWC rest tests.

**Comment by jimczi** [comment]
test this please

**Review by jpountz — CHANGES_REQUESTED** [review]
The change looks good overall. Let's maybe check the value of `relation` in the documentation of the REST client. It's probably fine to assume the value is accurate in tests, but documentation should show that `value` must always be interpreted in the context of `relation`?

**Comment by jimczi** [comment]
@jpountz I changed the docs for the REST client. I also pushed a change to force Watcher to use the new request parameter (`rest_total_hits_as_int`) with the `search` input. This makes all existing watches compatible with the new version (ES 7), WDYT ?

**Comment by jimczi** [comment]
We discussed offline with @jpountz and decided that watcher should also use the new format. I opened https://github.com/elastic/elasticsearch/issues/36008 to add the support for `rest_total_hits_as_int` in the search watcher input and will open a separate pr to handle the new format in watcher.

**Comment by jimczi** [comment]
@elasticmachine run the gradle build tests 2

**Comment by jimczi** [comment]
run sample packaging tests

**Comment by jimczi** [comment]
run default distro tests

**Comment by jimczi** [comment]
run the gradle build tests 2

**Comment by jimczi** [comment]
run the gradle build tests 2

**Comment by Musfiqur01** [comment]
Will not this break the Rest api in 6.x while the upgrade is happening? We are using the java rest api 6.7 and I did not find any  way of setting track_total_hits=true and rest_total_hits_as_int=true.

**Comment by jimczi** [comment]
@Musfiqur01, see https://github.com/elastic/elasticsearch/pull/46076, clients sets this option automatically from version `6.8.3`.

**Comment by Musfiqur01** [comment]
nice.
What about setting track_total_hits = true?

-Musfiqur

**Pull request merged**
