### PR TITLE
[7.x] introduce 6.8.9 as a version

### PR DESCRIPTION
**Pull request by jakelandis**
_DO NOT MERGE UNTIL 6.8.8 IS RELEASED_

_tests will fail until https://github.com/elastic/elasticsearch/pull/53816 is merged_

### CODE REVIEW

**Review by bpintea — APPROVED** [review]
LGTM

**Comment by jakelandis** [comment]
@elasticmachine run elasticsearch-ci/bwc
@elasticmachine run elasticsearch-ci/default-distro

**Comment by jakelandis** [comment]
@elasticmachine update branch

**Comment by jakelandis** [comment]
@elasticmachine run elasticsearch-ci/1

**Pull request merged**
