### PR TITLE
TESTS: Dry up Netty Test Utilities

### PR DESCRIPTION
**Pull request by original-brownbear**
* Created module to collect Netty test utilities in
  * Cleaned up duplicate test rule for joining Netty internal threads
      * Also added test rule to `org.elasticsearch.transport.netty4.SimpleNetty4TransportTests` that was also logging the leak warning (though it never failed with it at least) that necessitated this.

### CODE REVIEW

**Review by Tim-Brooks — CHANGES_REQUESTED** [review]
I don't think that `Netty4HttpClient.java` requires the introduction of a new test module. That class should only be used by the netty module. It was duplicated in nio to get nio up and running. But I think the correct approach is that the test client in nio should be driven by nio (essentially `NioHttpClient.java`). 

I'll let Jason comment on the `StopNettyThreads` component of this PR as I am less familiar with that.

**Comment by original-brownbear** [comment]
@tbrooks8 I basically got motivated to extract that client because it was sort of at the center of most of the recent leaks so I figured that it would be nice to only have to go through one set of stack traces there. But yea if it's short lived idk probably not worth the noise ... (though the background thread stopping I'm more convinced should be extracted, we're using it in a bunch of places already and should probably add it to all the places that currently show the thread leak warning for those 2 background threads and the logic in that rule is somewhat nontrivial).

**Comment by ywelsch** [comment]
@original-brownbear do you still want to get this in?

**Comment by original-brownbear** [comment]
Ah not this is way outdated now I think we can kill it (sorry for forgetting + thanks for pinging), the related Netty functionality should be going away soon anyway.

**Pull request closed without merging**
