### PR TITLE
[#28594] Added SocketAccess using AccessController with permissions

### LINKED ISSUE #28594: SocketAccess using AccessController with permissions
Java 8 defines a new [`AccessController#doPrivileged`](https://docs.oracle.com/javase/8/docs/api/java/security/AccessController.html#doPrivileged-java.security.PrivilegedExceptionAction-java.security.AccessControlContext-java.security.Permission...-) method that allows to specify a limited set of permissions, instead of granting all.

We have several `SocketAccess` classes scattered around plugins, e.g.,
https://github.com/elastic/elasticsearch/blob/da1a10fa9266770769881b222ee99e7bdd6af4c2/plugins/discovery-ec2/src/main/java/org/elasticsearch/discovery/ec2/SocketAccess.java#L48

I think it would be beneficial to collate all `SocketAccess` classes under a single `org.elasticsearch.common` one and use the new `doPriviledge` with permissions facility.

### PR DESCRIPTION
**Pull request by sohaibiftikhar**
Java 8 defines a new [`AccessController#doPrivileged`](https://docs.oracle.com/javase/9/docs/api/java/security/AccessController.html) method that allows to specify a limited set of permissions, instead of granting all.

There are several SocketAccess/Access classes scattered around plugins.

It would be beneficial to collate all SocketAccess classes under a single org.elasticsearch.common one and use the new `doPriviledge` with permissions facility.

Resolves #28594

**Checklist**
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)? Yes
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)? Yes
- If submitting code, have you built your formula locally prior to submission with `gradle check`? Yes. Tests failing. Review needed before proceeding.
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed. Yes
- If submitting code, have you checked that your submission is for an [OS that we support](https://www.elastic.co/support/matrix#show_os)? Yes
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that. NA

### CODE REVIEW

**Comment by rjernst** [comment]
I don't think this will actually work. The reason these classes exist is because the server jar does not have socket permissions, but having the code to call doPrivileged inside the server jar means it would be on the stack when SecurityManager checks. However, I do think consolidating these helper classes might be possible using the AccessControllerContext, but then the helper method should require that parameter, and not have all these other variants. And I also don't think this should be specific to SocketAccess (as the copied class name implies).

/cc @elastic/es-core-infra

**Comment by sohaibiftikhar** [comment]
@rjernst Thanks for the review. 

>The reason these classes exist is because the server jar does not have socket permissions

Yes. I actually figured that access part out. I am running tests now to verify if moving the context out works.

>  And I also don't think this should be specific to SocketAccess (as the copied class name implies).

Do you have a suggestion for the class name? Does `CommonAccessController` make more sense?

**Comment by rjernst** [comment]
I would call it AccessControllerUtil, and only have the exception based methods, as all the rest can just be called on AccessController directly. The utility is in the exception type being unwrapped.

**Comment by sohaibiftikhar** [comment]
I don't think moving out the context works either. I am sorry I should have read the documentation earlier. From the documentation for [AccessController](https://docs.oracle.com/javase/8/docs/api/java/security/AccessController.html#doPrivileged-java.security.PrivilegedAction-java.security.AccessControlContext-)

> The action is performed with the intersection of the permissions possessed by the caller's protection domain, and those possessed by the domains represented by the specified AccessControlContext.

More details for the algorithm for checking permissions can be found [here](https://docs.oracle.com/javase/8/docs/technotes/guides/security/spec/security-spec.doc4.html).

Since the calling stack's permissions are always in the intersection this seems pretty much impossible IMHO. What we could do is basically add generic exception methods to all the old `SocketAccess` classes).

**Comment by jasontedor** [comment]
> Since the calling stack's permissions are always in the intersection this seems pretty much impossible IMHO.

I agree. I appreciate the research that you put into this though.

**Pull request closed without merging**
