### PR TITLE
Add SpecialPermission to guard exceptions to security policy.

### PR DESCRIPTION
**Pull request by rmuir**
In some cases (e.g. buggy cloud libraries, scripting engines), we must
grant dangerous permissions to contained cases. Those AccessController blocks
are dangerous, since they truncate the stack, and can allow privilege escalation.

This PR adds a simple permission to check before each one, so that unprivileged code
like groovy scripts, can't do anything they shouldn't be allowed to do otherwise.

### CODE REVIEW

**Comment by jdconrad** [comment]
LGTM

**Comment by rmuir** [comment]
I added another commit with additional paranoia for two scripting cases.

**Comment by jdconrad** [comment]
Still LGTM.

**Comment by kimchy** [comment]
@rmuir is my understanding correct that we should always call this now instead of mistakenly only called `AccessController` without it? If so, maybe in a future change, we can forbid calling AccessController except in a wrapper class, that does the security manager special permission check automatically?

**Comment by rmuir** [comment]
That is the basics of it. See my second commit though, its just as bad if e.g. you get a SomethingEvil in a block but then expose it to another method unprotected. 

As far as a helper method, i don't think we should do it, because it will corrupt the stack with additional codebases and will not work :)

I have tried really hard to set things up, in such a way that we avoid code like this in general, the security stuff should be transparent:  but we have these exceptions to the rules, and I want to prevent "race to the bottom" where the least secure plugin you have drags down the entire system.

**Comment by rmuir** [comment]
Some of these things are explained in a better way than I can, via http://www.oracle.com/technetwork/java/seccodeguide-139067.html#9

Especially ones like 9.5, which is what groovyscriptingengine does (it caches that classloader).

**Comment by rmuir** [comment]
A great example is groovy scripts today, we give them minimal permissions (https://github.com/elastic/elasticsearch/blob/master/core/src/main/resources/org/elasticsearch/bootstrap/groovy.policy#L24-L31), but if you had the python plugin installed, all the script has to do is get ahold of scripting service and compile a python plugin that has no "sandboxing" (using the word lightly), and now it has elevated its privileges. This check will prevent it, because it will not have SpecialPermission.

Going forward I would like to improve the other engines to be more limited, just like we do with groovy, but today that is just not the case.

**Comment by kimchy** [comment]
ahh, I see, thanks for the explanation !

**Comment by rmuir** [comment]
the helper method idea is still a good one, we can look into it in the future. we might be able to do something "sneaky" (e.g. with accesscontrolcontext) and then like you say, we can use forbidden apis...

methods like that are tricky business though... so I went with the straightforward approach here as a start.

**Comment by rmuir** [comment]
I just backported this to 2.x

**Pull request closed without merging**
