### PR TITLE
Fix table formatting of options

### PR DESCRIPTION
**Pull request by antondollmaier**
Add missing colon in list of options to fix table layout.

### CODE REVIEW

**Comment by antondollmaier** [comment]
> Please, read and sign the above mentioned agreement if you want to contribute to this project

Done!

**Comment by jrodewig** [comment]
@elasticmachine test this please

**Review by jrodewig — APPROVED** [review]
LGTM. Thanks for fixing this @antondollmaier.

**Comment by jrodewig** [comment]
### Backport commits
master e9c8c03feea
7.x 35c8226419b
7.6 b080144

**Pull request merged**
