### PR TITLE
Fix NullPointerException in shard snapshot code

### PR DESCRIPTION
**Pull request by DiannaHohensee**
Closes ES-9093

~But I haven't figured out why the ci is failing yet..~ Fixed testing, yay.

### CODE REVIEW

**Comment by idegtiarenko** [comment]
To be precise, this will replace the NPE with ShardNotFoundException?
Do we handle it differently?

**Comment by DiannaHohensee** [comment]
@idegtiarenko would you mind reviewing, since you've taken a look? Or I can find someone else.

**Comment by DiannaHohensee** [comment]
[This was Armin's PR](https://github.com/elastic/elasticsearch/commit/ba46bd4ad8e7e87ce0a7b1847cb1b898dfcf9ffb) to fix this in master, for reference.

**Review by idegtiarenko — APPROVED** [review]
Makes sense. 
Please note, including some description of what is changed and how it is going to fix the issue generally helps to expedite the review.

**Pull request merged**
