### PR TITLE
Stop Resolving Fallback IndexId

### PR DESCRIPTION
**Pull request by original-brownbear**
There is no reason to still resolve a
fallback `IndexId` or `SnapshotId` in `RepositoryData`.
These only apply to
`2.x` repos and those we can't read anymore
anyway because they use an `/index` instead of
an `/index-N` blob at the repo root for which
at least 7.x+ does not contain the logic to find
it. 
This also makes the method do what the JavaDoc 
claims it already does.
Also, fixes a source-only-snapshot test that used the index id
instead of its name on the recovery source and just randomly worked still
because of this fallback.

### CODE REVIEW

**Comment by original-brownbear** [comment]
Jenkins test this

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/bwc

**Comment by original-brownbear** [comment]
Jenkins run elasticsearch-ci/default-distro

**Review by ywelsch — APPROVED** [review]
LGTM

**Pull request merged**
