### PR TITLE
Remove include_type_name from the relevant APIs.

### PR DESCRIPTION
**Pull request by jtibshirani**
We've decided that the bulk, delete, get, index, update, and search APIs should not contain this request parameter, and we will instead accept both typed and typeless calls.

### CODE REVIEW

**Comment by jtibshirani** [comment]
@elasticmachine test this please

**Review by cbuescher — APPROVED** [review]
I only looked at a subset of the test changes, but the main code changes look good to me, at least wrt. to the goal of the PR that you mentioned in the descrption. Not sure if other follow-up discussion need to happen, but the change by itself is good I think.

**Comment by jtibshirani** [comment]
Thanks @cbuescher for taking a look. We've agreed on this point, and are tracking the plan and required work here: https://github.com/elastic/elasticsearch/issues/35190

**Comment by jtibshirani** [comment]
CC @elastic/es-clients

**Pull request merged**
