### PR TITLE
Do not prefix already prefixed format with 8

### PR DESCRIPTION
**Pull request by pgomulka**
It happens when a locale is specified on a mapping that a new
JavaDateFormatter is created with a new mapping and already prefixed
with 8 format is prefixed again. This should change avoids this
behavior.

- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?
- Have you followed the [contributor guidelines](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md)?
- If submitting code, have you built your formula locally prior to submission with `gradle check`?
- If submitting code, is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed.
- If submitting code, have you checked that your submission is for an [OS and architecture that we support](https://www.elastic.co/support/matrix#show_os)?
- If you are submitting this code for a class then read our [policy](https://github.com/elastic/elasticsearch/blob/master/CONTRIBUTING.md#contributing-as-part-of-a-class) for that.

### CODE REVIEW

**Comment by pgomulka** [comment]
discovered with yml test failure #47983

**Comment by pgomulka** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample-matrix

**Review by rjernst — APPROVED** [review]
Looks fine. Just to double check: we would have never serialized multiple 8's right?

**Comment by pgomulka** [comment]
@elasticmachine run elasticsearch-ci/2

**Comment by pgomulka** [comment]
@rjernst good point, when serialising, it probably won't (I can't see how this could happen)
But when deserialising it would deserialise with double `8`
added a testcase that fails without the change in `JavaDateFormatter`

**Pull request merged**
