### PR TITLE
Configurable media_type for mustache template encoding on append processor

### PR DESCRIPTION
**Pull request by danhermann**
Adds the same capability to the append processor that was added to the set processor in https://github.com/elastic/elasticsearch/pull/65314.

### CODE REVIEW

**Comment by danhermann** [comment]
@elasticmachine retest this please

**Comment by danhermann** [comment]
@elasticmachine update branch

**Review by dakrone — APPROVED** [review]
LGTM

**Comment by danhermann** [comment]
Thank you, @dakrone!

**Pull request merged**
