### PR TITLE
Align all usages of protobuf to be 3.21.9

### PR DESCRIPTION
**Pull request by masseyke**
Upgrading to protobuf 3.21.9 everywhere. (copy of #91726)

### CODE REVIEW

**Comment by masseyke** [comment]
I'm leaving protobuf-java-2.5.0.jar and hadoop-shaded-protobuf_3_7-1.1.1.jar in the verification metadata xml because they are used by the [hdfs2-fixture](https://github.com/elastic/elasticsearch/blob/main/test/fixtures/hdfs2-fixture/build.gradle#L12), which we use to make sure we are backwards compatible with hdfs 2. They are test-only dependencies.

**Comment by masseyke** [comment]
@elasticmachine run elasticsearch-ci/part-1

**Comment by masseyke** [comment]
@elasticmachine run elasticsearch-ci/docs-check

**Comment by masseyke** [comment]
@elasticmachine run elasticsearch-ci/part-1

**Review by jbaiera — APPROVED** [review]
If CI is all happy then I'm happy with this

**Comment by gwbrown** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|7.17|[](https://github.com/elastic/elasticsearch/pull/95431)|


### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
