### PR TITLE
Fix dim validation for bit element_type

### PR DESCRIPTION
**Pull request by benwtrent**
A silly bug has reared its ugly head. Apparently, our dimension validations are predicated on JSON parsing order, that is not good. 

So, this commit adjusts the dim validations so that it is an actual validation, instead of something that occurs during parsing.

Additionally, I found that our custom formats were not overriding `getMaxDimensions` correctly. Typically, and in production, this isn't that big of a deal, but I have found it useful to do this for other testing purposes (so that we don't have to rely on the perfield codec for more direct and advanced testing).

### CODE REVIEW

**Review by john-wagster — APPROVED** [review]
LGTM

**Review by tteofili — APPROVED** [review]
LGTM, good catch Ben!

**Review by carlosdelest — APPROVED** [review]

**Comment by benwtrent** [comment]
@elasticmachine update branch

**Comment by benwtrent** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.15|[](https://github.com/elastic/elasticsearch/pull/114610)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
