### PR TITLE
GET _lifecycle returns data streams without lifecycle

### PR DESCRIPTION
**Pull request by andreidan**
This changes the `GET _data_stream/ds_name/_lifecycle` endpoint to return the data stream name even if it doesn't have a lifecycle configured.

e.g.
```
{
  "data_streams": [
    {
      "name": "logs-nginx"
    }
  ]
}
```
Relates to https://github.com/elastic/elasticsearch/issues/93596

### CODE REVIEW

**Comment by andreidan** [comment]
Test failure was fixed with https://github.com/elastic/elasticsearch/pull/95193

@elasticmachine update branch

**Comment by andreidan** [comment]
@elasticmachine update branch

**Comment by andreidan** [comment]
@elasticmachine update branch

**Comment by andreidan** [comment]
@elasticmachine run elasticsearch-ci/packaging-tests-windows-sample

**Comment by masseyke** [comment]
Makes sense to me. We ought to update the documentation though to say that the `lifecycle` field will be missing if the data stream has no lifecycle though (https://github.com/elastic/elasticsearch/blob/main/docs/reference/dlm/apis/get-lifecycle.asciidoc).

**Comment by andreidan** [comment]
@elasticmachine update branch

**Review by masseyke — APPROVED** [review]
LGTM

**Pull request merged**
