### PR TITLE
Node level can match action

### PR DESCRIPTION
**Pull request by ywelsch**
Changes can-match from a shard-level to a node-level action, which helps avoid an explosion of shard-level can-match subrequests in clusters with many shards, that can cause stability issues. Also introduces a new `search_coordination` thread pool to handle the sending and handling of node-level can-match requests.

### CODE REVIEW

**Review by dnhatn — COMMENTED** [review]
Thanks Yannick! I think the production code is ready :). We just need to add some tests then 🚢!

**Review by jimczi — COMMENTED** [review]
The change looks great! 
I left one comment regarding the wait for checkpoint option.
I wonder, as a follow up, if we should use the new thread pool for the coordination of the other phases too ?

**Review by jimczi — APPROVED** [review]

**Review by dnhatn — APPROVED** [review]
LGTM. Thanks @ywelsch.

**Comment by dnhatn** [comment]
@elasticmachine update branch

**Pull request merged**
