### PR TITLE
Add deprecation warning for Force Merge API

### PR DESCRIPTION
**Pull request by tlrx**
This pull request adds a deprecation warning in 7.x for the Force Merge API when both  `only_expunge_deletes` and `max_num_segments` are set in a request.

Relates #44761

### CODE REVIEW

**Review by dnhatn — APPROVED** [review]
LGTM

**Comment by tlrx** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by tlrx** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by tlrx** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by tlrx** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by tlrx** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by tlrx** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Comment by tlrx** [comment]
Thanks @dnhatn

**Pull request merged**
