### PR TITLE
SQL: Translate MIN/MAX on keyword fields as FIRST/LAST

### PR DESCRIPTION
**Pull request by matriv**
Although the translation rule was implemented in the `Optimizer`
and the docs are in place, the rule was not added in the list of rules
 to be executed.

Relates to #41195
Follows #37936

### CODE REVIEW

**Review by astefan — COMMENTED** [review]
Can you add a test to `QueryTranslatorTests` specifically for MIN(string) and MAX(string), please?
And I would also like to see more tests in general, with these two for strings.

**Comment by matriv** [comment]
There are already tests for optimizer: https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/optimizer/OptimizerTests.java#L1236
and 
https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/sql/src/test/java/org/elasticsearch/xpack/sql/optimizer/OptimizerTests.java#L1260

Would you like to add more integration tests?

**Comment by astefan** [comment]
I missed those from OptimizerTests class; if you believe they are enough, it's ok with me. I was used to those in the QueryTranslatorTests class.

Yes, more integration tests are welcomed. The more, the better. Thanks.

**Review by costin — APPROVED** [review]
+1 on having a bit more integration tests - they don't hurt and will check potential mistakes.

**Comment by matriv** [comment]
Added also query translator tests and one more integ test.
MIN/MAX on keyword cannot be used in HAVING currently (there is a limitation documented) so I couldn't think of another integration test.

**Review by astefan — APPROVED** [review]
LGTM

**Pull request merged**
