### PR TITLE
Let fast vector highlighter also extract terms from the nested query's inner query.

### PR DESCRIPTION
**Pull request by martijnvg**
PR for #19265

### CODE REVIEW

**Comment by nik9000** [comment]
I don't know the `ToParentBlockJoinQuery` at all but this is how I'd hack support for it into the FVH. I might try to open a Lucene issue to get it in instead/in addition, but otherwise LGTM.

**Comment by jpountz** [comment]
+1 to the Lucene issue and LGTM to this one

**Comment by martijnvg** [comment]
@nik9000 @jpountz I'll open an issue in Lucene. I initially thought that the highlighter module didn't depend on the join module, but I was wrong, it does!

**Comment by martijnvg** [comment]
The Lucene issue for referencing: https://issues.apache.org/jira/browse/LUCENE-7376

**Pull request merged**
