### PR TITLE
Deprecate setting `max_merge_at_once_explicit`

### PR DESCRIPTION
**Pull request by dnhatn**
This setting has been removed in Lucene 9.

### CODE REVIEW

**Review by romseygeek — APPROVED** [review]
LGTM, thanks @dnhatn

**Comment by dnhatn** [comment]
Thanks Alan!

**Comment by dakrone** [comment]
@dnhatn would you be able to add this setting to the deprecation API in a follow-up PR? That way users start getting notified about it sooner rather than later, and it lowers the chance that we forget about adding it at a later time.

**Comment by jpountz** [comment]
I wonder if we actually should add it to the deprecation API. It doesn't hurt to have this setting set on old indices, it will just be ignored with this PR, and then archived once we effectively remove the setting. So not having it in the deprecation API could be a nicer user experience: less noise in the deprecation API and Elasticsearch takes care of the migration for existing indices?

**Comment by jpountz** [comment]
Reading more about the migration API it looks like it's still expected to cover changes that users do not need to take action on, using the `warning` level instead of `critical`, as a way to convey information about the fact that the behavior will change in future versions. So I guess we need to add this setting there then.

**Pull request merged**
