### PR TITLE
Correctly migrate system indices that are still using named types

### PR DESCRIPTION
**Pull request by AthenaEryma**
Prior to this PR, the system index migration facility did not use the
index type configured in the descriptor, instead always using `_doc`.

This PR adjusts the migration facility to use the index type specified
in the descriptor instead.

Note that this PR is only targeted at 7.17, as it is the only version impacted.

Fixes https://github.com/elastic/elasticsearch/issues/83779

### CODE REVIEW

**Review by grcevski — COMMENTED** [review]
The change looks good to me!

I had a few questions:

- If we are only putting this change in 7.17, does it make sense for us to add an assert in 8.x that will check that the indexType is always '_doc', since we aren't expecting it to be a named type? 
- I don't know the extent of testing we do for system index migration, does it make sense to add a test for this specific case?

**Comment by gwbrown** [comment]
> If we are only putting this change in 7.17, does it make sense for us to add an assert in 8.x that will check that the indexType is always '_doc', since we aren't expecting it to be a named type?

I would agree with you except that `SystemIndexDescriptor` doesn't have the `indexType` property in 8.x, which is a big part of why this bug exists in the first place (I didn't know about `indexType` until I got very confused tracking down this bug). Similarly, the API in use here doesn't have a type parameter in 8.x: https://github.com/elastic/elasticsearch/blob/4cf37b7cc96f8c0268fbff36c8955a91b9c4e42d/server/src/main/java/org/elasticsearch/upgrades/SystemIndexMigrator.java#L471

> I don't know the extent of testing we do for system index migration, does it make sense to add a test for this specific case?

It does make sense to test this! But I wanted to get the PR up ASAP, and adding a test could be done in a follow-up if necessary if we wanted to get the fix in urgently. I'll look at adding a test to this PR.

**Review by grcevski — APPROVED** [review]
LGTM! If the fix is urgent let's do it, we can follow-up with a test. Since I'm getting myself up to speed in this area, I can add the test with your help.

**Comment by rjernst** [comment]
>  we can follow-up with a test

Pushing a fix without tests leaves the real possibility that the behavior is still unknowingly broken. We can't be sure something is fixed unless it is tested.

**Comment by gwbrown** [comment]
I've adjusted the tests so that they cover this case; there's not a new test case to do so, I just adjusted the test definitions to cover this case and added a comment about why they're that way. I confirmed this makes all of these tests fail without the fix originally present in this PR.

**Review by rjernst — APPROVED** [review]
LGTM

**Pull request merged**
