### PR TITLE
Log Slowness on Sending Transport Messages

### PR DESCRIPTION
**Pull request by original-brownbear**
Similar to #62444 but for the outbound path.

This does not detect slowness in individual transport handler logic,
this is done via the inbound handler logging already, but instead
warns if it takes a long time to hand off the message to the relevant
transport thread and then transfer the message over the wire.
This gives some visibility into the stability of the network
connection itself and into the reasons for slow network
responses (if they are the result of slow networking on the sender).

Example log lines:

```
[2021-01-19T00:54:04,105][WARN ][o.e.t.OutboundHandler    ] [node_t1] sending transport message [MessageSerializer{Request{internal:discovery/request_peers}{17}{false}{false}{false}}] of size [276] on [NioSocketChannel{localAddress=/127.0.0.1:43786, remoteAddress=127.0.0.1/127.0.0.1:38915}] took [5602ms] which is above the warn threshold of [5000ms]
[2021-01-19T00:54:04,105][WARN ][o.e.t.OutboundHandler    ] [node_t0] sending transport message [MessageSerializer{Response{12}{true}{false}{false}{class org.elasticsearch.transport.RemoteTransportException}}] of size [734] on [NioSocketChannel{localAddress=/127.0.0.1:38915, remoteAddress=/127.0.0.1:43782}] took [7202ms] which is above the warn threshold of [5000ms]
```

### CODE REVIEW

**Review by DaveCTurner — COMMENTED** [review]
Looks _ok_ but I'm not sure this will actually give us much more useful information. If we want a more general picture of the health of transport threads can we collect any statistics to give us that picture rather than the one-shot warnings proposed here?

**Comment by original-brownbear** [comment]
>  If we want a more general picture of the health of transport threads can we collect any statistics to give us that picture rather than the one-shot warnings proposed here?

It's tricky to do very general statistics I think. We don't have a way of hooking into Netty at the level of the `.select` call for example as far as I can tell. Obviously we could collect the outbound delay into a histogram of sorts which would be more helpful but also more work. I figured this was a pretty quick and easy way of at least revealing another problematic class of transport issues.

> I'm not sure this will actually give us much more useful information.

I think this will reveal two things that we don't get from the inbound delay warning:
* Slow networking like we've seen a lot due to e.g. re-transmits or other intermittent issues that introduce huge amounts of latency
* Overwhelmed connections if we only see the warning for some profiles/connections
* Some indication of low bandwidth if this only shows up for very large messages

-> IMO this is kind of neat for debugging stuff like:

```
Received response for a request that has timed out, sent [{}/{}ms] ago, timed out [{}/{}ms] ago
```

if we get `WARN` about this on the response sender side (which we would be getting in case of massive re-transmit counts for example).

**Comment by DaveCTurner** [comment]
Hmm I'm still not seeing how we'd use these messages in practice.

TCP retransmits won't push back on us at the application level until the transmit buffer for that channel fills up (hundreds of kB normally, and often "tuned" much higher), so we'll only see this warning on a flaky/slow network on connections that are consistently high-throughput. Latency-sensitive low-throughput connections like `PING` won't trigger this at all.

We also can't distinguish a flaky network from a case where the receiver's transport threads are blocked for long enough that the corresponding receive buffer fills up, so I think this won't help much with an investigation into a latency spike.

I think we'd get more useful information about network health from [Metricbeat](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-system-network_summary.html) since it can look deeper into the stats. Can we use `NETLINK_INET_DIAG` ourselves from Java-land? That'd let us get detail on the individual channels like buffer fill rates and retransmits. Or even just reading `/proc/net/tcp`?

**Comment by original-brownbear** [comment]
> We also can't distinguish a flaky network from a case where the receiver's transport threads are blocked for long enough that the corresponding receive buffer fills up, so I think this won't help much with an investigation into a latency spike.

In this case you would still at least get an indication that the sender tried sending a response and that it took a long time to go out. If this is the receivers fault then you'd see similar logging on other connections to that receiver with a good chance. If you only ever see this logged on a single node then you can take it as an indication that that node might be in some trouble.

I'm not claiming that this is going to give us a massive boost in what we can debug in detail, but I think it gives us a lot more coverage in terms of surfacing that a problem exists (and makes understanding some timing easier when debugging). But it's a cheap thing to add and it gives us an indication on the health of the transport threads on a specific node. Plus it catches things on the transport threads outside of slow inbound handler execution (e.g. something like "accept0" being stuck for many seconds constantly). Also, it allows for correlating slow inbound handler logging with corresponding problems in sending out requests (if `can_match` took long enough to log, we'd also get a corresponding log for a `PING` that didn't go out in time and such).

> I think we'd get more useful information about network health from Metricbeat since it can look deeper into the stats. Can we use NETLINK_INET_DIAG ourselves from Java-land? That'd let us get detail on the individual channels like buffer fill rates and retransmits. Or even just reading /proc/net/tcp?

Definitely +1 to the above. But that's a significant effort to implement by comparison. 

Though even if we had that I think there is some value in logging here (or some other spot that would indicate if a transport thread is slow to execute an item) to catch overwhelmed transport threads. Like for example a your node handles an avalanche of inbound requests that all take 100ms to execute on a transport thread which blocks a bunch of other unrelated connections from getting their pings out.
Or as discussed recently, maybe catching (or not ...) the correlation between slow logging and transport thread slowness.

**Review by DaveCTurner — APPROVED** [review]
> If this is the receivers fault then you'd see similar logging on other connections to that receiver with a good chance.

Right, but you'd also see this if, say, the receiver's NIC was just randomly dropping stuff.

Although I remain sceptical that this will help us much in practice, I'm giving this a LGTM since it's a pretty low-cost change.

**Comment by original-brownbear** [comment]
Thanks David!

**Pull request merged**
