### PR TITLE
Fix: added missing skip

### PR DESCRIPTION
**Pull request by delvedor**
In `indices.split/30_copy_settings.yml` we are using the `arbitrary_key` feature, but it is not declared inside the skip list.

Related: https://github.com/elastic/elasticsearch/pull/40052
/cc @elastic/es-clients

### CODE REVIEW

**Review by DaveCTurner — CHANGES_REQUESTED** [review]
Good catch @delvedor; however the build is failing due to a syntax error in this change:

```
        ParsingException[Error parsing test named [Copy settings during split index]]; nested: IllegalArgumentException[Expected [START_OBJECT, found [VALUE_NULL], the skip section is not properly indented];
```

**Comment by DaveCTurner** [comment]
@elasticmachine please run elasticsearch-ci/1

**Comment by DaveCTurner** [comment]
Discovered while backporting that this had been there but was removed by accident in #41165. I checked that change in detail and couldn't see any other cases that needed this fix.

**Comment by delvedor** [comment]
Great, thank you @DaveCTurner!

**Pull request merged**
