### PR TITLE
Close engine before reset log appender

### LINKED ISSUE #50315: [CI] InternalEngineTests.testIndexWriterInfoStream failure
Reproduce line:

```
./gradlew ':server:unitTest' -Dtests.seed=23A79BFD76C74CE -Dtests.class=org.elasticsearch.index.engine.InternalEngineTests -Dtests.method="testIndexWriterInfoStream" -Dtests.security.manager=true -Dtests.locale=zh-Hans-CN -Dtests.timezone=Atlantic/Stanley -Dcompiler.java=12 -Druntime.java=12
```

I was unable to reproduce it locally

Failure:

```
FAILURE 0.36s J13 | InternalEngineTests.testIndexWriterInfoStream <<< FAILURES!
13:55:36    > Throwable #1: java.lang.AssertionError: 
13:55:36    > Expected: an empty collection
13:55:36    >      but: <[Attempted to append to non-started appender testIndexWriterInfoStream]>
13:55:36    > 	at __randomizedtesting.SeedInfo.seed([23A79BFD76C74CE:303742EE3F4AC155]:0)
13:55:36    > 	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
13:55:36    > 	at org.elasticsearch.test.ESTestCase.checkStaticState(ESTestCase.java:516)
13:55:36    > 	at org.elasticsearch.test.ESTestCase.after(ESTestCase.java:365)
13:55:36    > 	at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
13:55:36    > 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:55:36    > 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
13:55:36    > 	at java.base/java.lang.Thread.run(Thread.java:835)
```

Branch: 6.8

Failure happens when running tear down validation in ESTestCase.checkStaticState(...)

Build url: https://gradle-enterprise.elastic.co/s/csltgh2b5h22w

### PR DESCRIPTION
**Pull request by dnhatn**
>   1> [2019-12-18T08:55:30,347][TRACE][o.e.i.e.E.MS             ] [[index] [index][0] elasticsearch[[index][0]: Lucene Merge Thread #0] MS:   merge thread: start
  1> 2019-12-18 08:55:30,375 elasticsearch[[index][0]: Lucene Merge Thread #0] ERROR Attempted to append to non-started appender testIndexWriterInfoStream

Merge threads can run and access the mock appender after we have stopped it.

Closes #50315

### CODE REVIEW

**Comment by dnhatn** [comment]
run elasticsearch-ci/packaging-sample-matrix-unix

**Review by ywelsch — APPROVED** [review]
LGTM

**Comment by dnhatn** [comment]
@elasticmachine update branch

**Comment by dnhatn** [comment]
@elasticmachine update branch

**Comment by dnhatn** [comment]
> testHistoryIsWrittenWithDeletion

run elasticsearch-ci/2

**Comment by dnhatn** [comment]
Thanks Yannick.

**Pull request merged**
