### PR TITLE
Fix range queries on runtime double field

### LINKED ISSUE #71786: Runtime field doesn't work correctly with range query when emitted value is 0.0
**Elasticsearch version** (`bin/elasticsearch --version`): 7.12.0

**Plugins installed**: []

**JVM version** (`java -version`): java version "16" 2021-03-16

**OS version** (`uname -a` if on a Unix-like system): MacOS Catalina, Version 10.15.7

**Description of the problem including expected versus actual behavior**:
When emitting the value 0.0 for a runtime time field of type double, a range query with lt (less equal) returns the wrong result.

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) index creation, mappings, settings, query etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. Create an index with a runtime field of type double. The runtime field emits always the value 0.0.
```
 PUT my-index
 {
   "mappings": {
     "runtime": {
       "field1": {
         "type": "double",
         "script": {
           "source": "emit(0.0)"
         }
       }
     }
   }
}
```

 2. Insert a document to the index
```
PUT my-index/_doc/1
{}
```

 3. Search for the document using this range query
```
GET my-index/_search
{
  "query": {
    "range": {
      "field1": {
        "lt": 0
      }
    }
  }, 
  "docvalue_fields": ["field1"]
}
```
This range query returns the inserted document which is a wrong result. Please note that the range query condition is <0 - hence this query shouldn't return any documents. I noticed that this problem only occurs when emitting the value 0. Other  values (e.g. 1.0, 2.0, 3.0...) work as expected.

### PR DESCRIPTION
**Pull request by cbuescher**
DoubleScriptFieldRangeQuery which is used on runtime fields of type "double"
currently uses simple double type comparison for checking its upper and lower
bounds. Unfortunately it seems that -0.0 == 0.0, but when we want to exclude a
0.0 bound via "lt" the generated range query uses -0.0 as its upper bound which
erroneously includes the 0.0 value. We can use `Double.compare` instead which
seems to handle this edge case well.

Closes #71786

### CODE REVIEW

**Review by jimczi — APPROVED** [review]
LGTM, good catch!

**Comment by cbuescher** [comment]
@elasticmachine run elasticsearch-ci/bwc
@elasticmachine run elasticsearch-ci/rest-compat

**Comment by cbuescher** [comment]
@elasticmachine update branch

**Comment by javanna** [comment]
thanks for fixing this @cbuescher !

**Pull request merged**
