### PR TITLE
Correct context for ClusterConnManager listener

### PR DESCRIPTION
**Pull request by DaveCTurner**
Today `ClusterConnectionManager#connectToNode` completes its listeners
in the thread context in which the connection completes, which may not
be the correct context if there are multiple concurrent connection
attempts. With this commit we make sure to complete each listener in the
context in which it was passed to the corresponding call to
`connectToNode`.

### CODE REVIEW

**Comment by idegtiarenko** [comment]
@elasticmachine please run elasticsearch-ci/rest-compatibility

**Comment by DaveCTurner** [comment]
https://github.com/elastic/elasticsearch/pull/83170 will fix the failure

@elasticmachine please run elasticsearch-ci/part-1

**Review by original-brownbear — APPROVED** [review]
LGTM

Are we sure about backporting to 7.17 though? I can't think of a bug this would cause?

**Comment by DaveCTurner** [comment]
> Are we sure about backporting to 7.17 though? I can't think of a bug this would cause?

Yeah it might not be a real bug, at least not right now, but also not a controversial bugfix so worth the backport IMO.

**Pull request merged**
