### PR TITLE
Remove ordinal member from Operator enum

### PR DESCRIPTION
**Pull request by javanna**
Use the already available enum ordinal instead.

### CODE REVIEW

**Comment by cbuescher** [comment]
LGTM, one question though. I thought the explicit ordinal was there to prevent accidental mixups in the enum order, also to make clearer that we rely on this ordering in serialization. Just want to make sure I understand this so we can apply it to other enums where necessary.

**Comment by javanna** [comment]
I see what you mean, I think it is safe to use, of course we shouldn't go and change the order in the enum though... I saw Simon do the same in another PR as well ;)

**Comment by cbuescher** [comment]
I'm more asking for best practices for other enums where order/naming might change, e.g. if we decide to remove a member of the enum at some point, serialization breaks. That doesn't happen when we explicitly choose the value. This is not an issue here, mostly asking for future reference.

**Comment by alexksikes** [comment]
That is true it will be harder to maintain bwc in this case, but I do much prefer the simplicity of this. The other way is to directly serialize the name of the enum if we don't care about the extra bits.

**Comment by javanna** [comment]
Once we do run into bw comp issues with this, not likely to happen, they can be handled adding back some layer very similar to what we are removing here, taking into account the previous ordering. We don'd need it now and we most likely won't need it in the future either. That's my take. The reason why I didn't propose this from the beginning is that I didn't know we could do this, purely ignorance on my end :)

**Pull request merged**
