### PR TITLE
Suppress error message when `/proc/sys/vm/max_map_count` is not exists.

### PR DESCRIPTION
**Pull request by Milly**
If `/proc/sys/vm/max_map_count` is not exists,
Before patch: `$(cat /proc/sys/vm/max_map_count)` is evaluated before test, and show error message like `cat: /proc/sys/vm/max_map_count: No such file or directory`.
After patch: Separate a file exists test and call cat.

### CODE REVIEW

**Comment by Milly** [comment]
#27236

**Comment by dliappis** [comment]
Thank you for the PR and sorry for the time taken to review.

I can see the issue here since `-a` is not a shell control operator (i.e. doesn't short circuit). I was able to reproduce the problem with something like (note the `syste` typo is intentional to simulate a file not present):

```
$ MAX_MAP_COUNT=200000; if [ -n "$MAX_MAP_COUNT" -a -f /proc/system/vm/max_map_count -a "$MAX_MAP_COUNT" -gt $(cat /proc/syste/vm/max_map_count) ]; then echo "max_map_count needs to change"; else echo "no change needed"; fi
cat: /proc/syste/vm/max_map_count: No such file or directory
-bash: [: too many arguments
no change needed
```

vs your suggestion:

```
$ MAX_MAP_COUNT=200000; if [ -n "$MAX_MAP_COUNT" -a -f /proc/system/vm/max_map_count ] && ["$MAX_MAP_COUNT" -gt $(cat /proc/syste/vm/max_map_count) ]; then echo "max_map_count needs to change"; else echo "no change needed"; fi
no change needed
```

Normally we'd like to have some tests to ensure this is working as expected, as shown e.g. here: https://github.com/elastic/elasticsearch/pull/31285/files. However, I think that it will be rather hard to mock `/proc/sys/vm/max_map_count` (make it go away) for packaging tests. I am not sure in which environments this happens, I am guessing `/proc/sys/vm/max_map_count` is unavailable with certain OS's inside Docker e.g. on certain k8s platforms.

@danielmitterdorfer are we ok to contain the complexity here by not seeking a way to test this?

**Review by dliappis — APPROVED** [review]
LGTM from me, I left a comment on why I think adding a test, albeit useful, would be a complicated thing, hence, this can be merge as is.

**Comment by dliappis** [comment]
@elasticmachine test this please

**Comment by dliappis** [comment]
@Milly  would it be possible that you merge master into the branch of your fork used for this PR (and push to the same) so that we can resolve some CI failures?

**Comment by danielmitterdorfer** [comment]
> @danielmitterdorfer are we ok to contain the complexity here by not seeking a way to test this?

Yes, I agree with your reasoning.

**Comment by danielmitterdorfer** [comment]
@elasticmachine test this please

**Comment by danielmitterdorfer** [comment]
@Milly I have merged the latest master now into your fork on your behalf so we can get a successful CI build and we'll take it from there. /cc: @dliappis.

**Comment by danielmitterdorfer** [comment]
The packaging tests failed while starting a Windows Vagrant box which seems unrelated to me.

@elasticmachine run elasticsearch-ci/packaging

**Comment by dliappis** [comment]
Thanks @danielmitterdorfer, all CI is green now, so will merge.

**Pull request merged**
