### PR TITLE
[DOCS]  SQL: Document `null` handling for functions

### LINKED ISSUE #74193: [DOCS] Document `null`/edge case handling for SQL functions
We don't consistently document how our [SQL functions](https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-functions.html) handle `null` values and other edge cases (such as negative integers in string function args). We should update the docs for each function so users know what to expect.

Due to the number of functions, we'll likely need to break this up over several PRs. We should prioritize string functions so we can document the changes in https://github.com/elastic/elasticsearch/pull/68379

- [ ] Aggregate functions #74444
- [ ] Grouping functions #74444
- [ ] Date/Time and Interval Functions #74444
- [x] ~Full-Text Search Functions~ (already done)
- [ ] Mathematical Functions #74444
- [x] String Functions #74201, #74255
- [ ] Type Conversion Functions #74444
- [ ] Geo Functions #74444
- [x] ~Conditional Functions And Expressions~ (already done)
- [x] ~System Functions~ (already done)

CC @astefan

### PR DESCRIPTION
**Pull request by jrodewig**
Closes #74193.

### Previews
* Aggregate functions: https://elasticsearch_74444.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/sql-functions-aggs.html
* Date/time functions: https://elasticsearch_74444.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/sql-functions-datetime.html
* Geo functions: https://elasticsearch_74444.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/sql-functions-geo.html
* Grouping functions: https://elasticsearch_74444.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/sql-functions-grouping.html
* Math functions: https://elasticsearch_74444.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/sql-functions-math.html
* Type conversion functions: https://elasticsearch_74444.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/sql-functions-type-conversion.html

### CODE REVIEW

**Comment by matriv** [comment]
Regarding the date-time functions we also mention this in the description, for example: https://github.com/elastic/elasticsearch/pull/74444/files#diff-34118c3c46bec17c634fc5efa70c4ff0ff62e198a106564f175d1dae4d754447R705 
(`if one of the arguments is null then a null is returned`)

Should we keep this as well ?

**Comment by jrodewig** [comment]
Thanks for catching that @matriv. I've removed those statements from the date/time function docs with 1f9209ad0604b3b5f58fd40b47b8409ad0cbf670.

**Review by matriv — APPROVED** [review]
LGTM. Thank you!

**Comment by jrodewig** [comment]
Thanks @matriv!

**Pull request merged**
