### PR TITLE
Do not use hard links on MacOS in EvilNodeTests

### LINKED ISSUE #39302: EvilNodeTests failure in CI
This fails reproducibly in 5.6:
```
REPRODUCE WITH: ./gradlew :qa:evil-tests:test \
  -Dtests.seed=BDA213671F433276 \
  -Dtests.class=org.elasticsearch.node.EvilNodeTests \
  -Dtests.method="testDefaultPathDataIncludedInPathData" \
  -Dtests.security.manager=false \
  -Dtests.locale=pl \
  -Dtests.timezone=America/Dominica
```

```
> Throwable #1: java.nio.file.FileSystemException: /Users/romseygeek/projects/elasticsearch-5.6/qa/evil-tests/build/testrun/test/J0/temp/org.elasticsearch.node.EvilNodeTests_BDA213671F433276-001/tempDir-004/link -> /Users/romseygeek/projects/elasticsearch-5.6/qa/evil-tests/build/testrun/test/J0/temp/org.elasticsearch.node.EvilNodeTests_BDA213671F433276-001/tempDir-003: Operation not permitted
   >    at __randomizedtesting.SeedInfo.seed([BDA213671F433276:8DF45C3472C48CCF]:0)
   >    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
   >    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
   >    at sun.nio.fs.UnixFileSystemProvider.createLink(UnixFileSystemProvider.java:476)
   >    at org.apache.lucene.mockfile.FilterFileSystemProvider.createLink(FilterFileSystemProvider.java:233)
   >    at org.apache.lucene.mockfile.FilterFileSystemProvider.createLink(FilterFileSystemProvider.java:233)
   >    at java.nio.file.Files.createLink(Files.java:1086)
   >    at org.elasticsearch.node.EvilNodeTests.testDefaultPathDataIncludedInPathData(EvilNodeTests.java:61)
   >    at java.lang.Thread.run(Thread.java:748)
```

https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+5.6+multijob-darwin-compatibility/258/console

### PR DESCRIPTION
**Pull request by danielmitterdorfer**
With this commit we don't test hard links anymore on MacOS in
`EvilNodeTests`. Directory hard links were once supported on the HFS+
file system (as an undocumented feature) but are gone with the APFS
file system. Attempting to create a directory hard link using the `link`
system call on APFS results in `EPERM`.

See also https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/APFS_Guide/FAQ/FAQ.html

Closes #39302

### CODE REVIEW

**Review by romseygeek — APPROVED** [review]
LGTM, thanks @danielmitterdorfer

**Comment by danielmitterdorfer** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample

**Review by jasontedor — APPROVED** [review]
LGTM.

**Comment by danielmitterdorfer** [comment]
@elasticmachine run elasticsearch-ci/packaging-sample

**Comment by danielmitterdorfer** [comment]
@elasticmachine run elasticsearch-ci/bwc

**Pull request merged**
